rippled: ripple::RPC::detail::ErrorCategory Class Reference
ripple::RPC::detail::ErrorCategory Class Reference
Public Types
typedef ripple::unordered_map
< error_code_i, ErrorInfo > Map
Public Member Functions
ErrorCategory ()
ErrorInfo const & get (error_code_i code) const
Private Member Functions
void add (error_code_i code, std::string const &token, std::string const &message)
Private Attributes
Map m_map
ErrorInfo m_unknown
Detailed Description
Definition at line 42 of file ErrorCodes.cpp.
Member Typedef Documentation
typedef ripple::unordered_map<error_code_i, ErrorInfo> ripple::RPC::detail::ErrorCategory::Map
Definition at line 45 of file ErrorCodes.cpp.
Constructor & Destructor Documentation
ripple::RPC::detail::ErrorCategory::ErrorCategory () inline
Definition at line 47 of file ErrorCodes.cpp.
References add(), ripple::rpcACT_BITCOIN, ripple::rpcACT_EXISTS, ripple::rpcACT_MALFORMED, ripple::rpcACT_NOT_FOUND, ripple::rpcATX_DEPRECATED, ripple::rpcBAD_BLOB, ripple::rpcBAD_FEATURE, ripple::rpcBAD_ISSUER, ripple::rpcBAD_MARKET, ripple::rpcBAD_SECRET, ripple::rpcBAD_SEED, ripple::rpcBAD_SYNTAX, ripple::rpcCOMMAND_MISSING, ripple::rpcDST_ACT_MALFORMED, ripple::rpcDST_ACT_MISSING, ripple::rpcDST_AMT_MALFORMED, ripple::rpcDST_ISR_MALFORMED, ripple::rpcFAIL_GEN_DECRYPT, ripple::rpcFORBIDDEN, ripple::rpcGETS_ACT_MALFORMED, ripple::rpcGETS_AMT_MALFORMED, ripple::rpcHIGH_FEE, ripple::rpcHOST_IP_MALFORMED, ripple::rpcINSUF_FUNDS, ripple::rpcINTERNAL, ripple::rpcINVALID_PARAMS, ripple::rpcJSON_RPC, ripple::rpcLGR_IDX_MALFORMED, ripple::rpcLGR_IDXS_INVALID, ripple::rpcLGR_NOT_FOUND, ripple::rpcMASTER_DISABLED, ripple::rpcNICKNAME_MALFORMED, ripple::rpcNICKNAME_MISSING, ripple::rpcNICKNAME_PERM, ripple::rpcNO_ACCOUNT, ripple::rpcNO_CLOSED, ripple::rpcNO_CURRENT, ripple::rpcNO_EVENTS, ripple::rpcNO_GEN_DECRYPT, ripple::rpcNO_NETWORK, ripple::rpcNO_PATH, ripple::rpcNO_PERMISSION, ripple::rpcNO_PF_REQUEST, ripple::rpcNOT_IMPL, ripple::rpcNOT_STANDALONE, ripple::rpcNOT_SUPPORTED, ripple::rpcPASSWD_CHANGED, ripple::rpcPAYS_ACT_MALFORMED, ripple::rpcPAYS_AMT_MALFORMED, ripple::rpcPORT_MALFORMED, ripple::rpcPUBLIC_MALFORMED, ripple::rpcQUALITY_MALFORMED, ripple::rpcSLOW_DOWN, ripple::rpcSRC_ACT_MALFORMED, ripple::rpcSRC_ACT_MISSING, ripple::rpcSRC_ACT_NOT_FOUND, ripple::rpcSRC_AMT_MALFORMED, ripple::rpcSRC_CUR_MALFORMED, ripple::rpcSRC_ISR_MALFORMED, ripple::rpcSRC_UNCLAIMED, ripple::rpcTOO_BUSY, ripple::rpcTXN_NOT_FOUND, ripple::rpcUNKNOWN_COMMAND, and ripple::rpcWRONG_SEED.
         : m_unknown (rpcUNKNOWN, "unknown", "An unknown error code.")
     {
         add (rpcACT_BITCOIN,           "actBitcoin",        "Account is bitcoin address.");
         add (rpcACT_EXISTS,            "actExists",         "Account already exists.");
         add (rpcACT_MALFORMED,         "actMalformed",      "Account malformed.");
         add (rpcACT_NOT_FOUND,         "actNotFound",       "Account not found.");
         add (rpcBAD_BLOB,              "badBlob",           "Blob must be a non-empty hex string.");
         add (rpcBAD_FEATURE,           "badFeature",        "Feature unknown or invalid.");
         add (rpcBAD_ISSUER,            "badIssuer",         "Issuer account malformed.");
         add (rpcBAD_MARKET,            "badMarket",         "No such market.");
         add (rpcBAD_SECRET,            "badSecret",         "Secret does not match account.");
         add (rpcBAD_SEED,              "badSeed",           "Disallowed seed.");
         add (rpcBAD_SYNTAX,            "badSyntax",         "Syntax error.");
         add (rpcCOMMAND_MISSING,       "commandMissing",    "Missing command entry.");
         add (rpcDST_ACT_MALFORMED,     "dstActMalformed",   "Destination account is malformed.");
         add (rpcDST_ACT_MISSING,       "dstActMissing",     "Destination account does not exist.");
         add (rpcDST_AMT_MALFORMED,     "dstAmtMalformed",   "Destination amount/currency/issuer is malformed.");
         add (rpcDST_ISR_MALFORMED,     "dstIsrMalformed",   "Destination issuer is malformed.");
         add (rpcFAIL_GEN_DECRYPT,      "failGenDecrypt",    "Failed to decrypt generator.");
         add (rpcFORBIDDEN,             "forbidden",         "Bad credentials.");
         add (rpcGETS_ACT_MALFORMED,    "getsActMalformed",  "Gets account malformed.");
         add (rpcGETS_AMT_MALFORMED,    "getsAmtMalformed",  "Gets amount malformed.");
         add (rpcHIGH_FEE,              "highFee",           "Current transaction fee exceeds your limit.");
         add (rpcHOST_IP_MALFORMED,     "hostIpMalformed",   "Host IP is malformed.");
         add (rpcINSUF_FUNDS,           "insufFunds",        "Insufficient funds.");
         add (rpcINTERNAL,              "internal",          "Internal error.");
         add (rpcINVALID_PARAMS,        "invalidParams",     "Invalid parameters.");
         add (rpcJSON_RPC,              "json_rpc",          "JSON-RPC transport error.");
         add (rpcLGR_IDXS_INVALID,      "lgrIdxsInvalid",    "Ledger indexes invalid.");
         add (rpcLGR_IDX_MALFORMED,     "lgrIdxMalformed",   "Ledger index malformed.");
         add (rpcLGR_NOT_FOUND,         "lgrNotFound",       "Ledger not found.");
         add (rpcMASTER_DISABLED,       "masterDisabled",    "Master key is disabled.");
         add (rpcNICKNAME_MALFORMED,    "nicknameMalformed", "Nickname is malformed.");
         add (rpcNICKNAME_MISSING,      "nicknameMissing",   "Nickname does not exist.");
         add (rpcNICKNAME_PERM,         "nicknamePerm",      "Account does not control nickname.");
         add (rpcNOT_IMPL,              "notImpl",           "Not implemented.");
         add (rpcNO_ACCOUNT,            "noAccount",         "No such account.");
         add (rpcNO_CLOSED,             "noClosed",          "Closed ledger is unavailable.");
         add (rpcNO_CURRENT,            "noCurrent",         "Current ledger is unavailable.");
         add (rpcNO_EVENTS,             "noEvents",          "Current transport does not support events.");
         add (rpcNO_GEN_DECRYPT,        "noGenDecrypt",      "Password failed to decrypt master public generator.");
         add (rpcNO_NETWORK,            "noNetwork",         "Not synced to Ripple network.");
         add (rpcNO_PATH,               "noPath",            "Unable to find a ripple path.");
         add (rpcNO_PERMISSION,         "noPermission",      "You don't have permission for this command.");
         add (rpcNO_PF_REQUEST,         "noPathRequest",     "No pathfinding request in progress.");
         add (rpcNOT_STANDALONE,        "notStandAlone",     "Operation valid in debug mode only.");
         add (rpcNOT_SUPPORTED,         "notSupported",      "Operation not supported.");
         add (rpcPASSWD_CHANGED,        "passwdChanged",     "Wrong key, password changed.");
         add (rpcPAYS_ACT_MALFORMED,    "paysActMalformed",  "Pays account malformed.");
         add (rpcPAYS_AMT_MALFORMED,    "paysAmtMalformed",  "Pays amount malformed.");
         add (rpcPORT_MALFORMED,        "portMalformed",     "Port is malformed.");
         add (rpcPUBLIC_MALFORMED,      "publicMalformed",   "Public key is malformed.");
         add (rpcQUALITY_MALFORMED,     "qualityMalformed",  "Quality malformed.");
         add (rpcSRC_ACT_MALFORMED,     "srcActMalformed",   "Source account is malformed.");
         add (rpcSRC_ACT_MISSING,       "srcActMissing",     "Source account not provided.");
         add (rpcSRC_ACT_NOT_FOUND,     "srcActNotFound",    "Source account not found.");
         add (rpcSRC_AMT_MALFORMED,     "srcAmtMalformed",   "Source amount/currency/issuer is malformed.");
         add (rpcSRC_CUR_MALFORMED,     "srcCurMalformed",   "Source currency is malformed.");
         add (rpcSRC_ISR_MALFORMED,     "srcIsrMalformed",   "Source issuer is malformed.");
         add (rpcSRC_UNCLAIMED,         "srcUnclaimed",      "Source account is not claimed.");
         add (rpcTXN_NOT_FOUND,         "txnNotFound",       "Transaction not found.");
         add (rpcUNKNOWN_COMMAND,       "unknownCmd",        "Unknown method.");
         add (rpcWRONG_SEED,            "wrongSeed",         "The regular key does not point as the master key.");
         add (rpcTOO_BUSY,              "tooBusy",           "The server is too busy to help you now.");
         add (rpcSLOW_DOWN,             "slowDown",          "You are placing too much load on the server.");
         add (rpcATX_DEPRECATED,        "deprecated",        "Use the new API or specify a ledger range.");
     }
Member Function Documentation
void ripple::RPC::detail::ErrorCategory::add (error_code_i code, std::string const & token, std::string const & message) inline private
Definition at line 125 of file ErrorCodes.cpp.
References m_map.
Referenced by ErrorCategory().
     {
         std::pair <Map::iterator, bool> result (
             m_map.emplace (std::piecewise_construct,
                 std::forward_as_tuple (code), std::forward_as_tuple (
                     code, token, message)));
         if (! result.second)
             throw std::invalid_argument ("duplicate error code");
     }
ErrorInfo const& ripple::RPC::detail::ErrorCategory::get (error_code_i code) const inline
Definition at line 116 of file ErrorCodes.cpp.
References m_map, and m_unknown.
Referenced by ripple::RPC::get_error_info().
     {
         Map::const_iterator const iter (m_map.find (code));
         if (iter != m_map.end())
             return iter->second;
         return m_unknown;
     }
Member Data Documentation
Map ripple::RPC::detail::ErrorCategory::m_map private
Definition at line 137 of file ErrorCodes.cpp.
Referenced by add(), and get().
ErrorInfo ripple::RPC::detail::ErrorCategory::m_unknown private
Definition at line 138 of file ErrorCodes.cpp.
Referenced by get().
The documentation for this class was generated from the following file:
rippled/src/ripple_rpc/impl/ErrorCodes.cpp