rippled: ripple::PaymentTransactor Class Reference
ripple::PaymentTransactor Class Reference
#include <PaymentTransactor.h>
Public Member Functions
PaymentTransactor (SerializedTransaction const &txn, TransactionEngineParams params, TransactionEngine *engine)
TER doApply ()
Public Member Functions inherited from ripple::Transactor
TER apply ()
Static Private Attributes
static std::size_t const MaxPathSize = 6
Additional Inherited Members
Static Public Member Functions inherited from ripple::Transactor
static std::unique_ptr
< Transactor > makeTransactor (SerializedTransaction const &txn, TransactionEngineParams params, TransactionEngine *engine)
Protected Member Functions inherited from ripple::Transactor
virtual TER preCheck ()
virtual TER checkSeq ()
virtual TER payFee ()
void calculateFee ()
virtual std::uint64_t calculateBaseFee ()
virtual TER checkSig ()
Transactor (const SerializedTransaction &txn, TransactionEngineParams params, TransactionEngine *engine, beast::Journal journal=beast::Journal())
virtual bool mustHaveValidAccount ()
Protected Attributes inherited from ripple::Transactor
SerializedTransaction const & mTxn
TransactionEngine * mEngine
TransactionEngineParams mParams
uint160 mTxnAccountID
STAmount mFeeDue
STAmount mPriorBalance
STAmount mSourceBalance
SLE::pointer mTxnAccount
bool mHasAuthKey
bool mSigMaster
RippleAddress mSigningPubKey
beast::Journal m_journal
Detailed Description
Definition at line 34 of file PaymentTransactor.h.
Constructor & Destructor Documentation
ripple::PaymentTransactor::PaymentTransactor (SerializedTransaction const & txn, TransactionEngineParams params, TransactionEngine * engine) inline
Definition at line 41 of file PaymentTransactor.h.
         : Transactor (
             txn,
             params,
             engine,
             LogPartition::getJournal <PaymentTransactorLog> ())
     {
     }
Member Function Documentation
TER ripple::PaymentTransactor::doApply () virtual
Implements ripple::Transactor.
Definition at line 22 of file PaymentTransactor.cpp.
References CURRENCY_BAD, ripple::TransactionEngine::entryCache(), ripple::TransactionEngine::entryCreate(), ripple::TransactionEngine::entryModify(), ripple::Ledger::getAccountRootIndex(), ripple::STAmount::getCurrency(), ripple::STAmount::getExponent(), ripple::STObject::getFieldAccount160(), ripple::STObject::getFieldAmount(), ripple::STObject::getFieldPathSet(), ripple::STObject::getFlags(), ripple::STAmount::getFullText(), ripple::TransactionEngine::getLedger(), ripple::STAmount::getMantissa(), ripple::STAmount::getNValue(), ripple::STAmount::getText(), ripple::SerializedTransaction::getTransactionFee(), ripple::is_bit_set(), ripple::STObject::isFieldPresent(), ripple::STAmount::isLegalNet(), ripple::STAmount::isNative(), isTerRetry, ripple::base_uint< BITS >::isZero(), ripple::lsfPasswordSpent, ripple::lsfRequireDestTag, ripple::ltACCOUNT_ROOT, ripple::Transactor::m_journal, ripple::max(), MaxPathSize, ripple::Transactor::mEngine, ripple::Transactor::mParams, ripple::Transactor::mPriorBalance, ripple::Transactor::mSourceBalance, ripple::Transactor::mTxn, ripple::Transactor::mTxnAccount, ripple::Transactor::mTxnAccountID, ripple::RippleCalc::rippleCalc(), ripple::LedgerEntrySet::setDeliveredAmount(), ripple::STPathSet::size(), ripple::tapOPEN_LEDGER, ripple::tecNO_DST, ripple::tecNO_DST_INSUF_XRP, ripple::tecPATH_DRY, ripple::tecUNFUNDED_PAYMENT, ripple::tefDST_TAG_NEEDED, ripple::tefEXCEPTION, ripple::telBAD_PATH_COUNT, ripple::telNO_DST_PARTIAL, ripple::temBAD_AMOUNT, ripple::temBAD_CURRENCY, ripple::temBAD_SEND_XRP_LIMIT, ripple::temBAD_SEND_XRP_MAX, ripple::temBAD_SEND_XRP_NO_DIRECT, ripple::temBAD_SEND_XRP_PARTIAL, ripple::temBAD_SEND_XRP_PATHS, ripple::temDST_NEEDED, ripple::temINVALID_FLAG, ripple::temREDUNDANT, ripple::temREDUNDANT_SEND_MAX, ripple::tesSUCCESS, ripple::tfLimitQuality, ripple::tfNoRippleDirect, ripple::tfPartialPayment, ripple::tfPaymentMask, ripple::base_uint< BITS >::ToString(), beast::Journal::trace, ripple::transResultInfo(), and ripple::TransactionEngine::view().
 {
     // Ripple if source or destination is non-native or if there are paths.
     std::uint32_t const uTxFlags = mTxn.getFlags ();
     bool const bPartialPayment = is_bit_set (uTxFlags, tfPartialPayment);
     bool const bLimitQuality = is_bit_set (uTxFlags, tfLimitQuality);
     bool const bNoRippleDirect = is_bit_set (uTxFlags, tfNoRippleDirect);
     bool const bPaths = mTxn.isFieldPresent (sfPaths);
     bool const bMax = mTxn.isFieldPresent (sfSendMax);
     uint160 const uDstAccountID = mTxn.getFieldAccount160 (sfDestination);
     STAmount const saDstAmount = mTxn.getFieldAmount (sfAmount);
     STAmount const saMaxAmount = bMax
                                    ? mTxn.getFieldAmount (sfSendMax)
                                    : saDstAmount.isNative ()
                                    ? saDstAmount
                                    : STAmount (saDstAmount.getCurrency (),
                                         mTxnAccountID,
                                         saDstAmount.getMantissa (),
                                         saDstAmount.getExponent (),
                                         saDstAmount < zero);
     uint160 const uSrcCurrency = saMaxAmount.getCurrency ();
     uint160 const uDstCurrency = saDstAmount.getCurrency ();
     bool const bXRPDirect = uSrcCurrency.isZero () && uDstCurrency.isZero ();
     m_journal.trace <<
         "saMaxAmount=" << saMaxAmount.getFullText () <<
         " saDstAmount=" << saDstAmount.getFullText ();
     if (!saDstAmount.isLegalNet () || !saMaxAmount.isLegalNet ())
         return temBAD_AMOUNT;
     if (uTxFlags & tfPaymentMask)
     {
         m_journal.trace <<
             "Malformed transaction: Invalid flags set.";
         return temINVALID_FLAG;
     }
     else if (!uDstAccountID)
     {
         m_journal.trace <<
             "Malformed transaction: Payment destination account not specified.";
         return temDST_NEEDED;
     }
     else if (bMax && saMaxAmount <= zero)
     {
         m_journal.trace <<
             "Malformed transaction: bad max amount: " << saMaxAmount.getFullText ();
         return temBAD_AMOUNT;
     }
     else if (saDstAmount <= zero)
     {
         m_journal.trace <<
             "Malformed transaction: bad dst amount: " << saDstAmount.getFullText ();
         return temBAD_AMOUNT;
     }
     else if (CURRENCY_BAD == uSrcCurrency || CURRENCY_BAD == uDstCurrency)
     {
         m_journal.trace <<
             "Malformed transaction: Bad currency.";
         return temBAD_CURRENCY;
     }
     else if (mTxnAccountID == uDstAccountID && uSrcCurrency == uDstCurrency && !bPaths)
     {
         m_journal.trace <<
             "Malformed transaction: Redundant transaction:" <<
             " src=" << mTxnAccountID.ToString () <<
             " dst=" << uDstAccountID.ToString () <<
             " src_cur=" << uSrcCurrency.ToString () <<
             " dst_cur=" << uDstCurrency.ToString ();
         return temREDUNDANT;
     }
     else if (bMax && saMaxAmount == saDstAmount && saMaxAmount.getCurrency () == saDstAmount.getCurrency ())
     {
         m_journal.trace <<
             "Malformed transaction: Redundant SendMax.";
         return temREDUNDANT_SEND_MAX;
     }
     else if (bXRPDirect && bMax)
     {
         m_journal.trace <<
             "Malformed transaction: SendMax specified for XRP to XRP.";
         return temBAD_SEND_XRP_MAX;
     }
     else if (bXRPDirect && bPaths)
     {
         m_journal.trace <<
             "Malformed transaction: Paths specified for XRP to XRP.";
         return temBAD_SEND_XRP_PATHS;
     }
     else if (bXRPDirect && bPartialPayment)
     {
         m_journal.trace <<
             "Malformed transaction: Partial payment specified for XRP to XRP.";
         return temBAD_SEND_XRP_PARTIAL;
     }
     else if (bXRPDirect && bLimitQuality)
     {
         m_journal.trace <<
             "Malformed transaction: Limit quality specified for XRP to XRP.";
         return temBAD_SEND_XRP_LIMIT;
     }
     else if (bXRPDirect && bNoRippleDirect)
     {
         m_journal.trace <<
             "Malformed transaction: No ripple direct specified for XRP to XRP.";
         return temBAD_SEND_XRP_NO_DIRECT;
     }
     SLE::pointer sleDst (mEngine->entryCache (
         ltACCOUNT_ROOT, Ledger::getAccountRootIndex (uDstAccountID)));
     if (!sleDst)
     {
         // Destination account does not exist.
         if (!saDstAmount.isNative ())
         {
             m_journal.trace <<
                 "Delay transaction: Destination account does not exist.";
             // Another transaction could create the account and then this transaction would succeed.
             return tecNO_DST;
         }
         else if (is_bit_set (mParams, tapOPEN_LEDGER) && bPartialPayment)
         {
             // Make retry work smaller, by rejecting this.
             m_journal.trace <<
                 "Delay transaction: Partial payment not allowed to create account.";
             // Another transaction could create the account and then this
             // transaction would succeed.
             return telNO_DST_PARTIAL;
         }
         // Note: Reserve is not scaled by load.
         else if (saDstAmount.getNValue () < mEngine->getLedger ()->getReserve (0))
         {
             m_journal.trace <<
                 "Delay transaction: Destination account does not exist. " <<
                 "Insufficent payment to create account.";
             // Another transaction could create the account and then this
             // transaction would succeed.
             return tecNO_DST_INSUF_XRP;
         }
         // Create the account.
         sleDst = mEngine->entryCreate (
             ltACCOUNT_ROOT, Ledger::getAccountRootIndex (uDstAccountID));
         sleDst->setFieldAccount (sfAccount, uDstAccountID);
         sleDst->setFieldU32 (sfSequence, 1);
     }
     else if ((sleDst->getFlags () & lsfRequireDestTag) && !mTxn.isFieldPresent (sfDestinationTag))
     {
         m_journal.trace <<
             "Malformed transaction: DestinationTag required.";
         return tefDST_TAG_NEEDED;
     }
     else
     {
         mEngine->entryModify (sleDst);
     }
     TER terResult;
     // XXX Should bMax be sufficient to imply ripple?
     bool const bRipple = bPaths || bMax || !saDstAmount.isNative ();
     if (bRipple)
     {
         // Ripple payment
         STPathSet spsPaths = mTxn.getFieldPathSet (sfPaths);
         std::vector<PathState::pointer> vpsExpanded;
         STAmount saMaxAmountAct;
         STAmount saDstAmountAct;
         try
         {
             bool const openLedger = is_bit_set (mParams, tapOPEN_LEDGER);
             bool const tooManyPaths = spsPaths.size () > MaxPathSize;
             terResult = openLedger && tooManyPaths
                         ? telBAD_PATH_COUNT // Too many paths for proposed ledger.
                         : RippleCalc::rippleCalc (
                               mEngine->view (),
                               saMaxAmountAct,
                               saDstAmountAct,
                               vpsExpanded,
                               saMaxAmount,
                               saDstAmount,
                               uDstAccountID,
                               mTxnAccountID,
                               spsPaths,
                               bPartialPayment,
                               bLimitQuality,
                               bNoRippleDirect, // Always compute for finalizing ledger.
                               false, // Not standalone, delete unfundeds.
                               is_bit_set (mParams, tapOPEN_LEDGER));
             if (isTerRetry(terResult))
                 terResult = tecPATH_DRY;
             if ((tesSUCCESS == terResult) && (saDstAmountAct != saDstAmount))
                 mEngine->view().setDeliveredAmount (saDstAmountAct);
         }
         catch (std::exception const& e)
         {
             m_journal.trace <<
                 "Caught throw: " << e.what ();
             terResult   = tefEXCEPTION;
         }
     }
     else
     {
         // Direct XRP payment.
         std::uint32_t const uOwnerCount (mTxnAccount->getFieldU32 (sfOwnerCount));
         std::uint64_t const uReserve (mEngine->getLedger ()->getReserve (uOwnerCount));
         // Make sure have enough reserve to send. Allow final spend to use reserve for fee.
         if (mPriorBalance < saDstAmount + std::max(uReserve, mTxn.getTransactionFee ().getNValue ()))
         {
             // Vote no. However, transaction might succeed, if applied in a different order.
             m_journal.trace << "Delay transaction: Insufficient funds: " <<
                 " " << mPriorBalance.getText () <<
                 " / " << (saDstAmount + uReserve).getText () <<
                 " (" << uReserve << ")";
             terResult   = tecUNFUNDED_PAYMENT;
         }
         else
         {
             mTxnAccount->setFieldAmount (sfBalance, mSourceBalance - saDstAmount);
             sleDst->setFieldAmount (sfBalance, sleDst->getFieldAmount (sfBalance) + saDstAmount);
             // re-arm the password change fee if we can and need to
             if ((sleDst->getFlags () & lsfPasswordSpent))
                 sleDst->clearFlag (lsfPasswordSpent);
             terResult = tesSUCCESS;
         }
     }
     std::string strToken;
     std::string strHuman;
     if (transResultInfo (terResult, strToken, strHuman))
     {
         m_journal.trace <<
             strToken << ": " << strHuman;
     }
     else
     {
         assert (false);
     }
     return terResult;
 }
Member Data Documentation
std::size_t const ripple::PaymentTransactor::MaxPathSize = 6 static private
Definition at line 38 of file PaymentTransactor.h.
Referenced by doApply().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/transactors/PaymentTransactor.h
rippled/src/ripple_app/transactors/PaymentTransactor.cpp