rippled: beast::StringCreationHelper Class Reference
beast::StringCreationHelper Class Reference
Public Member Functions
StringCreationHelper (const size_t initialBytes)
StringCreationHelper (const String::CharPointerType s)
void write (beast_wchar c)
Public Attributes
String result
String::CharPointerType source
Private Attributes
String::CharPointerType dest
size_t allocatedBytes
size_t bytesWritten
Detailed Description
Definition at line 1106 of file String.cpp.
Constructor & Destructor Documentation
beast::StringCreationHelper::StringCreationHelper (const size_t initialBytes) inline
Definition at line 1109 of file String.cpp.
         : source (nullptr), dest (nullptr), allocatedBytes (initialBytes), bytesWritten (0)
     {
         result.preallocateBytes (allocatedBytes);
         dest = result.getCharPointer();
     }
beast::StringCreationHelper::StringCreationHelper (const String::CharPointerType s) inline
Definition at line 1116 of file String.cpp.
         : source (s), dest (nullptr), allocatedBytes (StringHolder::getAllocatedNumBytes (s)), bytesWritten (0)
     {
         result.preallocateBytes (allocatedBytes);
         dest = result.getCharPointer();
     }
Member Function Documentation
void beast::StringCreationHelper::write (beast_wchar c) inline
Definition at line 1123 of file String.cpp.
References beast::addBytesToPointer(), beast::bmax(), and beast::CharPointer_UTF8::getBytesRequiredFor().
Referenced by beast::String::createStringFromData(), beast::String::removeCharacters(), beast::String::replaceCharacter(), beast::String::replaceCharacters(), beast::String::retainCharacters(), beast::String::toLowerCase(), and beast::String::toUpperCase().
     {
         bytesWritten += String::CharPointerType::getBytesRequiredFor (c);
         if (bytesWritten > allocatedBytes)
         {
             allocatedBytes += bmax ((size_t) 8, allocatedBytes / 16);
             const size_t destOffset = (size_t) (((char*) dest.getAddress()) - (char*) result.getCharPointer().getAddress());
             result.preallocateBytes (allocatedBytes);
             dest = addBytesToPointer (result.getCharPointer().getAddress(), (int) destOffset);
         }
         dest.write (c);
     }
Member Data Documentation
size_t beast::StringCreationHelper::allocatedBytes private
Definition at line 1143 of file String.cpp.
size_t beast::StringCreationHelper::bytesWritten private
Definition at line 1143 of file String.cpp.
String::CharPointerType beast::StringCreationHelper::dest private
Definition at line 1142 of file String.cpp.
String beast::StringCreationHelper::result
Definition at line 1138 of file String.cpp.
Referenced by beast::String::createStringFromData(), beast::String::removeCharacters(), beast::String::replaceCharacter(), beast::String::replaceCharacters(), beast::String::retainCharacters(), beast::String::toLowerCase(), and beast::String::toUpperCase().
String::CharPointerType beast::StringCreationHelper::source
Definition at line 1139 of file String.cpp.
Referenced by beast::String::removeCharacters(), beast::String::replaceCharacter(), beast::String::replaceCharacters(), beast::String::retainCharacters(), beast::String::toLowerCase(), and beast::String::toUpperCase().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/strings/impl/String.cpp