rippled: beast::detail::HashGenerator< Type > Struct Template Reference
beast::detail::HashGenerator< Type > Struct Template Reference
Public Types
enum
Static Public Member Functions
template<typename CharPointer >
static Type calculate (CharPointer t) noexcept
Detailed Description
template<typename Type>
struct beast::detail::HashGenerator< Type >
Definition at line 416 of file String.cpp.
Member Enumeration Documentation
template<typename Type > anonymous enum
Definition at line 429 of file String.cpp.
 { multiplier = sizeof (Type) > 4 ? 101 : 31 };
Member Function Documentation
template<typename Type > template<typename CharPointer > static Type beast::detail::HashGenerator< Type >::calculate (CharPointer t) inline static noexcept
Definition at line 419 of file String.cpp.
Referenced by beast::String::hash(), beast::String::hashCode(), and beast::String::hashCode64().
     {
         Type result = Type();
         while (! t.isEmpty())
             result = multiplier * result + t.getAndAdvance();
         return result;
     }
The documentation for this struct was generated from the following file:
rippled/src/beast/beast/strings/impl/String.cpp