rippled: rocksdb::Duration Class Reference
rocksdb::Duration Class Reference
Public Member Functions
Duration (int max_seconds, long long max_ops)
bool Done (int increment)
Private Attributes
int max_seconds_
long long max_ops_
long long ops_
double start_at_
Detailed Description
Definition at line 719 of file db_bench.cc.
Constructor & Destructor Documentation
rocksdb::Duration::Duration (int max_seconds, long long max_ops) inline
Definition at line 721 of file db_bench.cc.
References max_ops_, max_seconds_, rocksdb::Env::NowMicros(), ops_, and start_at_.
{
     max_seconds_ = max_seconds;
     max_ops_= max_ops;
     ops_ = 0;
     start_at_ = FLAGS_env->NowMicros();
   }
Member Function Documentation
bool rocksdb::Duration::Done (int increment) inline
Definition at line 728 of file db_bench.cc.
References max_ops_, max_seconds_, rocksdb::Env::NowMicros(), ops_, and start_at_.
Referenced by rocksdb::Benchmark::AppendRandom(), rocksdb::Benchmark::DoDelete(), rocksdb::Benchmark::DoWrite(), rocksdb::Benchmark::MergeRandom(), rocksdb::Benchmark::PrefixScanRandom(), rocksdb::Benchmark::ReadHot(), rocksdb::Benchmark::ReadMissing(), rocksdb::Benchmark::ReadRandom(), rocksdb::Benchmark::ReadRandomWriteRandom(), rocksdb::Benchmark::ReadRandomWriteRandomMultiGet(), rocksdb::Benchmark::SeekRandom(), and rocksdb::Benchmark::UpdateRandom().
{
     if (increment <= 0) increment = 1;    // avoid Done(0) and infinite loops
     ops_ += increment;
     if (max_seconds_) {
       // Recheck every appx 1000 ops (exact iff increment is factor of 1000)
       if ((ops_/1000) != ((ops_-increment)/1000)) {
         double now = FLAGS_env->NowMicros();
         return ((now - start_at_) / 1000000.0) >= max_seconds_;
       } else {
         return false;
       }
     } else {
       return ops_ > max_ops_;
     }
   }
Member Data Documentation
long long rocksdb::Duration::max_ops_ private
Definition at line 747 of file db_bench.cc.
Referenced by Done(), and Duration().
int rocksdb::Duration::max_seconds_ private
Definition at line 746 of file db_bench.cc.
Referenced by Done(), and Duration().
long long rocksdb::Duration::ops_ private
Definition at line 748 of file db_bench.cc.
Referenced by Done(), and Duration().
double rocksdb::Duration::start_at_ private
Definition at line 749 of file db_bench.cc.
Referenced by Done(), and Duration().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/db/db_bench.cc