rippled: beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::KeyValueEqual Class Reference
beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::KeyValueEqual Class Reference
Public Member Functions
KeyValueEqual ()
KeyValueEqual (KeyEqual const &keyEqual)
bool operator() (Key const &k, element const &e) const
bool operator() (element const &e, Key const &k) const
bool operator() (element const &lhs, element const &rhs) const
KeyEqual & key_eq ()
KeyEqual const & key_eq () const
Additional Inherited Members
Private Member Functions inherited from beast::empty_base_optimization< KeyEqual >
empty_base_optimization ()=default
empty_base_optimization (KeyEqualconst &t)
empty_base_optimization (KeyEqual &&t)
KeyEqual & member () noexcept
KeyEqualconst & member () const noexcept
Detailed Description
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>>
class beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::KeyValueEqual
Definition at line 203 of file aged_unordered_container.h.
Constructor & Destructor Documentation
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::KeyValueEqual::KeyValueEqual () inline
Definition at line 208 of file aged_unordered_container.h.
         {
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::KeyValueEqual::KeyValueEqual (KeyEqual const & keyEqual) inline
Definition at line 212 of file aged_unordered_container.h.
             : empty_base_optimization <KeyEqual> (keyEqual)
         {
         }
Member Function Documentation
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> KeyEqual& beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::KeyValueEqual::key_eq () inline
Definition at line 248 of file aged_unordered_container.h.
Referenced by beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::key_eq().
         {
             return this->member();
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> KeyEqual const& beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::KeyValueEqual::key_eq () const inline
Definition at line 253 of file aged_unordered_container.h.
         {
             return this->member();
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> bool beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::KeyValueEqual::operator() (Key const & k, element const & e) const inline
Definition at line 233 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::extract(), and beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::element::value.
         {
             return this->member() (k, extract (e.value));
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> bool beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::KeyValueEqual::operator() (element const & e, Key const & k) const inline
Definition at line 238 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::extract(), and beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::element::value.
         {
             return this->member() (extract (e.value), k);
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> bool beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::KeyValueEqual::operator() (element const & lhs, element const & rhs) const inline
Definition at line 243 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::extract(), and beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::element::value.
         {
             return this->member() (extract (lhs.value), extract (rhs.value));
         }
The documentation for this class was generated from the following file:
rippled/src/beast/beast/container/detail/aged_unordered_container.h