rippled: Json::DefaultValueAllocator Class Reference
Json::DefaultValueAllocator Class Reference
Public Member Functions
virtual ~DefaultValueAllocator ()
virtual char * makeMemberName (const char *memberName)
virtual void releaseMemberName (char *memberName)
virtual char * duplicateStringValue (const char *value, unsigned int length=unknown)
virtual void releaseStringValue (char *value)
Public Member Functions inherited from Json::ValueAllocator
virtual ~ValueAllocator ()
Additional Inherited Members
Public Types inherited from Json::ValueAllocator
enum { unknown = (unsigned) - 1 }
Detailed Description
Definition at line 61 of file json_value.cpp.
Constructor & Destructor Documentation
virtual Json::DefaultValueAllocator::~DefaultValueAllocator () inline virtual
Definition at line 64 of file json_value.cpp.
     {
     }
Member Function Documentation
virtual char* Json::DefaultValueAllocator::duplicateStringValue (const char * value, unsigned int length = unknown) inline virtual
Implements Json::ValueAllocator.
Definition at line 78 of file json_value.cpp.
References Json::ValueAllocator::unknown.
Referenced by makeMemberName().
     {
         //@todo invesgate this old optimization
         //if ( !value  ||  value[0] == 0 )
         //   return 0;
         if ( length == unknown )
             length = (unsigned int)strlen (value);
         char* newString = static_cast<char*> ( malloc ( length + 1 ) );
         memcpy ( newString, value, length );
         newString[length] = 0;
         return newString;
     }
virtual char* Json::DefaultValueAllocator::makeMemberName (const char * memberName) inline virtual
Implements Json::ValueAllocator.
Definition at line 68 of file json_value.cpp.
References duplicateStringValue().
     {
         return duplicateStringValue ( memberName );
     }
virtual void Json::DefaultValueAllocator::releaseMemberName (char * memberName) inline virtual
Implements Json::ValueAllocator.
Definition at line 73 of file json_value.cpp.
References releaseStringValue().
     {
         releaseStringValue ( memberName );
     }
virtual void Json::DefaultValueAllocator::releaseStringValue (char * value) inline virtual
Implements Json::ValueAllocator.
Definition at line 94 of file json_value.cpp.
Referenced by releaseMemberName().
     {
         if ( value )
             free ( value );
     }
The documentation for this class was generated from the following file:
rippled/src/ripple/json/impl/json_value.cpp