rippled: beast::ServiceQueue_timing_test Class Reference
beast::ServiceQueue_timing_test Class Reference
Classes
struct Consumer
struct Producer
class Stopwatch
Public Member Functions
template<typename Allocator >
void testThreads (int nConsumers, int nProducers)
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Static Public Attributes
static int const callsPerThread = 50000
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 32 of file ServiceQueue.cpp.
Member Function Documentation
void beast::ServiceQueue_timing_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 178 of file ServiceQueue.cpp.
     {
 #if 1
         testThreads <std::allocator<char> > (1, 1);
         testThreads <std::allocator<char> > (1, 4);
         testThreads <std::allocator<char> > (1, 16);
         testThreads <std::allocator<char> > (4, 1);
         testThreads <std::allocator<char> > (8, 16);
 #endif
 #if 0
         testThreads <detail::ServiceQueueAllocator<char> > (1, 1);
         testThreads <detail::ServiceQueueAllocator<char> > (1, 4);
         testThreads <detail::ServiceQueueAllocator<char> > (1, 16);
         testThreads <detail::ServiceQueueAllocator<char> > (4, 1);
         testThreads <detail::ServiceQueueAllocator<char> > (8, 16);
 #endif
     }
template<typename Allocator > void beast::ServiceQueue_timing_test::testThreads (int nConsumers, int nProducers) inline
Definition at line 131 of file ServiceQueue.cpp.
References beast::ServiceQueue_timing_test::Stopwatch::getElapsed(), beast::unit_test::suite::log, name, beast::Random::nextInt64(), beast::unit_test::suite::pass(), and beast::unit_test::suite::testcase().
     {
         std::stringstream ss;
         ss <<
             nConsumers << " consumers, " <<
             nProducers << " producers, Allocator = " <<
             typeid(Allocator).name();
         testcase (ss.str());
         typedef ServiceQueueType <Allocator> ServiceType;
         ServiceType service (nConsumers);
         std::vector <std::unique_ptr <Consumer <ServiceType> > > consumers;
         std::vector <std::unique_ptr <Producer <ServiceType> > > producers;
         consumers.reserve (nConsumers);
         producers.reserve (nProducers);
         Random r;
         for (int i = 0; i < nConsumers; ++i)
             consumers.emplace_back (new Consumer <ServiceType> (i + 1,
                 r.nextInt64(), service));
         for (int i = 0; i < nProducers; ++i)
             producers.emplace_back (new Producer <ServiceType> (i + 1,
                 r.nextInt64(), service));
         Stopwatch t;
         for (std::size_t i = 0; i < producers.size(); ++i)
             producers[i]->startThread();
         for (std::size_t i = 0; i < producers.size(); ++i)
             producers[i]->waitForThreadToExit();
         for (std::size_t i = 0; i < consumers.size(); ++i)
             service.dispatch (std::bind (&Consumer <ServiceType>::stop_one));
         for (std::size_t i = 0; i < consumers.size(); ++i)
             consumers[i]->waitForThreadToExit();
         double const seconds (t.getElapsed());
         log << seconds << " seconds";
         pass();
     }
Member Data Documentation
int const beast::ServiceQueue_timing_test::callsPerThread = 50000 static
Definition at line 49 of file ServiceQueue.cpp.
Referenced by beast::ServiceQueue_timing_test::Producer< ServiceType >::run().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/threads/tests/ServiceQueue.cpp