rippled: rocksdb::Slice Class Reference
rocksdb::Slice Class Reference
#include <slice.h>
Public Member Functions
Slice ()
Slice (const char *d, size_t n)
Slice (const std::string &s)
Slice (const char *s)
const char * data () const
size_t size () const
bool empty () const
char operator[] (size_t n) const
void clear ()
void remove_prefix (size_t n)
std::string ToString (bool hex=false) const
int compare (const Slice &b) const
bool starts_with (const Slice &x) const
Public Attributes
const char * data_
size_t size_
Detailed Description
Definition at line 29 of file slice.h.
Constructor & Destructor Documentation
rocksdb::Slice::Slice () inline
Definition at line 32 of file slice.h.
 : data_(""), size_(0) { }
rocksdb::Slice::Slice (const char * d, size_t n) inline
Definition at line 35 of file slice.h.
 : data_(d), size_(n) { }
rocksdb::Slice::Slice (const std::string & s) inline
Definition at line 39 of file slice.h.
 : data_(s.data()), size_(s.size()) { }
rocksdb::Slice::Slice (const char * s) inline
Definition at line 43 of file slice.h.
 : data_(s), size_(strlen(s)) { }
Member Function Documentation
void rocksdb::Slice::clear () inline
Definition at line 62 of file slice.h.
References data_, and size_.
Referenced by rocksdb::Block::Iter::CorruptionError(), rocksdb::DBImpl::DoCompactionWork(), rocksdb::log::Reader::ReadPhysicalRecord(), rocksdb::log::Reader::ReadRecord(), and rocksdb::log::LogTest::StringSource::Skip().
 { data_ = ""; size_ = 0; }
int rocksdb::Slice::compare (const Slice & b) const inline
Definition at line 124 of file slice.h.
References data_, and size_.
Referenced by rocksdb::CompareIterators(), rocksdb::TtlTest::SleepCompactCheckIter(), and rocksdb::TEST().
{
   const int min_len = (size_ < b.size_) ? size_ : b.size_;
   int r = memcmp(data_, b.data_, min_len);
   if (r == 0) {
     if (size_ < b.size_) r = -1;
     else if (size_ > b.size_) r = +1;
   }
   return r;
 }
const char* rocksdb::Slice::data () const inline
Definition at line 46 of file slice.h.
References data_.
Referenced by rocksdb::StringAppendTESTOperator::_AssocPartialMerge(), rocksdb::BlockBuilder::Add(), rocksdb::BlockBasedTableBuilder::Add(), rocksdb::MemTable::Add(), rocksdb::RegularKeysStartWithA::Add(), rocksdb::SimpleTableBuilder::Add(), rocksdb::FilterBlockBuilder::AddKey(), rocksdb::log::Writer::AddRecord(), rocksdb::FakeWritableFile::Append(), rocksdb::log::LogTest::StringDest::Append(), rocksdb::StringSink::Append(), rocksdb::AppendInternalKey(), rocksdb::Benchmark::AppendRandom(), rocksdb::DBWithTTL::AppendTS(), rocksdb::AppendWithSpace(), rocksdb::BitStreamGetInt(), rocksdb::BuildTable(), rocksdb::BZip2CompressionSupported(), rocksdb::log::LogTest::CheckInitialOffsetRecord(), leveldb_comparator_t::Compare(), rocksdb::InternalKeyComparator::Compare(), leveldb_filterpolicy_t::CreateFilter(), rocksdb::Footer::DecodeFrom(), rocksdb::InternalKey::DecodeFrom(), rocksdb::DecodeKey(), rocksdb::DBImpl::DoCompactionWork(), rocksdb::EncodeKey(), rocksdb::ExtractUserKey(), rocksdb::ExtractValueType(), rocksdb::TtlCompactionFilter::Filter(), rocksdb::FilterBlockReader::FilterBlockReader(), rocksdb::InternalKeyComparator::FindShortestSeparator(), rocksdb::InternalKeyComparator::FindShortSuccessor(), rocksdb::StringAppendTESTOperator::FullMerge(), rocksdb::TtlMergeOperator::FullMerge(), rocksdb::DBClientProxy::get(), rocksdb::MemTable::Get(), rocksdb::GetFileIterator(), rocksdb::GetInternalKeySeqno(), rocksdb::GetLengthPrefixedSlice(), rocksdb::GetVarint32(), rocksdb::GetVarint64(), rocksdb::BlockBasedTableBuilder::InsertBlockInCache(), rocksdb::RedisListIterator::InsertElement(), rocksdb::DBWithTTL::IsStale(), rocksdb::TestHashFilter::KeyMayMatch(), leveldb_filterpolicy_t::KeyMayMatch(), leveldb_iter_key(), leveldb_iter_value(), leveldb_writebatch_iterate(), rocksdb::LookupKey::LookupKey(), rocksdb::StringAppendOperator::Merge(), rocksdb::Block::Iter::NextEntryOffset(), rocksdb::StressTest::OperateDb(), std::hash< rocksdb::Slice >::operator()(), rocksdb::stl_wrappers::Hash::operator()(), rocksdb::operator==(), rocksdb::ParseInternalKey(), rocksdb::TtlMergeOperator::PartialMerge(), rocksdb::Version::PrefixMayMatch(), rocksdb::RedisLists::Print(), rocksdb::BlobStore::Put(), rocksdb::PutLengthPrefixedSlice(), rocksdb::PutLengthPrefixedSliceParts(), rocksdb::RedisLists::Range(), rocksdb::log::LogTest::StringSource::Read(), rocksdb::ReadFileToString(), rocksdb::log::Reader::ReadPhysicalRecord(), rocksdb::log::Reader::ReadRecord(), rocksdb::DBWithTTL::SanityCheckTimestamp(), rocksdb::SaveValue(), rocksdb::DBClientProxy::scan(), rocksdb::WriteBatchInternal::SetContents(), rocksdb::SliceToTestKey(), rocksdb::Benchmark::SnappyCompress(), rocksdb::SnappyCompressionSupported(), rocksdb::Benchmark::SnappyUncompress(), rocksdb::Status::Status(), rocksdb::TEST(), rocksdb::TtlIterator::timestamp(), rocksdb::MemTable::Update(), rocksdb::MemTableRep::UserKey(), rocksdb::MemTableIterator::value(), rocksdb::BlockBasedTableBuilder::WriteBlock(), rocksdb::BlockBasedTableBuilder::WriteRawBlock(), and rocksdb::ZlibCompressionSupported().
 { return data_; }
bool rocksdb::Slice::empty () const inline
Definition at line 52 of file slice.h.
References size_.
Referenced by rocksdb::AppendWithSpace(), rocksdb::BlockBasedTable::BlockReader(), rocksdb::ConsumeChar(), rocksdb::ConsumeDecimalNumber(), rocksdb::VersionEdit::DecodeFrom(), rocksdb::DBImpl::GetProperty(), rocksdb::WriteBatch::Iterate(), rocksdb::ParseFileName(), and rocksdb::ReadFileToString().
 { return size_ == 0; }
char rocksdb::Slice::operator[] (size_t n) const inline
Definition at line 56 of file slice.h.
References data_, and size().
{
     assert(n < size());
     return data_[n];
   }
void rocksdb::Slice::remove_prefix (size_t n) inline
Definition at line 65 of file slice.h.
References data_, size(), and size_.
Referenced by rocksdb::ConsumeChar(), rocksdb::ConsumeDecimalNumber(), rocksdb::GetLengthPrefixedSlice(), rocksdb::DBImpl::GetProperty(), rocksdb::WriteBatch::Iterate(), rocksdb::ParseFileName(), rocksdb::log::LogTest::StringSource::Read(), rocksdb::log::Reader::ReadPhysicalRecord(), rocksdb::SetCurrentFile(), and rocksdb::log::LogTest::StringSource::Skip().
{
     assert(n <= size());
     data_ += n;
     size_ -= n;
   }
size_t rocksdb::Slice::size () const inline
Definition at line 49 of file slice.h.
References size_.
Referenced by rocksdb::StringAppendTESTOperator::_AssocPartialMerge(), rocksdb::BlockBuilder::Add(), rocksdb::BlockBasedTableBuilder::Add(), rocksdb::MemTable::Add(), rocksdb::SimpleTableBuilder::Add(), rocksdb::FilterBlockBuilder::AddKey(), rocksdb::log::Writer::AddRecord(), rocksdb::FakeWritableFile::Append(), rocksdb::log::LogTest::StringDest::Append(), rocksdb::StringSink::Append(), rocksdb::AppendEscapedStringTo(), rocksdb::AppendInternalKey(), rocksdb::Benchmark::AppendRandom(), rocksdb::DBWithTTL::AppendTS(), rocksdb::AppendWithSpace(), rocksdb::BitStreamGetInt(), rocksdb::BuildTable(), rocksdb::BZip2CompressionSupported(), rocksdb::log::LogTest::CheckInitialOffsetRecord(), rocksdb::TestKeyComparator::Compare(), leveldb_comparator_t::Compare(), rocksdb::InternalKeyComparator::Compare(), leveldb_filterpolicy_t::CreateFilter(), rocksdb::Footer::DecodeFrom(), rocksdb::InternalKey::DecodeFrom(), rocksdb::DecodeKey(), rocksdb::WALDumperCommand::DoCommand(), rocksdb::DBImpl::DoCompactionWork(), rocksdb::EncodeKey(), rocksdb::BlockBuilder::EstimateSizeAfterKV(), rocksdb::ExtractUserKey(), rocksdb::ExtractValueType(), rocksdb::TtlCompactionFilter::Filter(), rocksdb::TtlTest::TestFilter::Filter(), rocksdb::FilterBlockReader::FilterBlockReader(), rocksdb::InternalKeyComparator::FindShortestSeparator(), rocksdb::InternalKeyComparator::FindShortSuccessor(), rocksdb::SimpleTableBuilder::Finish(), rocksdb::StringAppendTESTOperator::FullMerge(), rocksdb::TtlMergeOperator::FullMerge(), rocksdb::DBClientProxy::get(), rocksdb::MemTable::Get(), rocksdb::BlobStore::Get(), rocksdb::GetFileIterator(), rocksdb::GetInternalKeySeqno(), rocksdb::GetLengthPrefixedSlice(), rocksdb::DBImpl::GetProperty(), rocksdb::GetVarint32(), rocksdb::GetVarint64(), rocksdb::BlockBasedTableBuilder::InsertBlockInCache(), rocksdb::RedisListIterator::InsertElement(), rocksdb::InternalKeyEncodingLength(), rocksdb::IsSingleVarint(), rocksdb::DBWithTTL::IsStale(), rocksdb::WriteBatch::Iterate(), rocksdb::TestHashFilter::KeyMayMatch(), leveldb_filterpolicy_t::KeyMayMatch(), leveldb_iter_key(), leveldb_iter_value(), leveldb_writebatch_iterate(), rocksdb::LookupKey::LookupKey(), rocksdb::StringAppendOperator::Merge(), rocksdb::Block::Iter::NextEntryOffset(), rocksdb::TransactionLogIteratorImpl::NextImpl(), rocksdb::BlockBasedTable::Open(), rocksdb::StressTest::OperateDb(), std::hash< rocksdb::Slice >::operator()(), rocksdb::stl_wrappers::Hash::operator()(), rocksdb::operator==(), operator[](), rocksdb::ParseFileName(), rocksdb::ParseInternalKey(), rocksdb::TtlMergeOperator::PartialMerge(), rocksdb::RedisLists::Print(), rocksdb::BlobStore::Put(), rocksdb::PutLengthPrefixedSlice(), rocksdb::PutLengthPrefixedSliceParts(), rocksdb::RedisLists::Range(), rocksdb::log::LogTest::StringSource::Read(), rocksdb::ReadFileToString(), rocksdb::BlockBasedTable::ReadFilter(), rocksdb::DBImpl::ReadFirstLine(), rocksdb::log::Reader::ReadPhysicalRecord(), rocksdb::log::Reader::ReadRecord(), rocksdb::Benchmark::ReadReverse(), rocksdb::Benchmark::ReadSequential(), rocksdb::DBImpl::RecoverLogFile(), remove_prefix(), rocksdb::log::Reader::ReportDrop(), rocksdb::DBWithTTL::SanityCheckTimestamp(), rocksdb::SaveValue(), rocksdb::DBClientProxy::scan(), rocksdb::TransactionLogIteratorImpl::SeekToStartSequence(), rocksdb::WriteBatchInternal::SetContents(), rocksdb::RedisListIterator::SizeOf(), rocksdb::log::LogTest::StringSource::Skip(), rocksdb::Benchmark::SnappyCompress(), rocksdb::SnappyCompressionSupported(), rocksdb::Benchmark::SnappyUncompress(), rocksdb::Status::Status(), rocksdb::TEST(), rocksdb::TtlIterator::timestamp(), rocksdb::MemTable::Update(), rocksdb::MemTableRep::UserKey(), rocksdb::MemTableIterator::value(), rocksdb::BlockBasedTableBuilder::WriteBlock(), rocksdb::BlockBasedTableBuilder::WriteRawBlock(), and rocksdb::ZlibCompressionSupported().
 { return size_; }
bool rocksdb::Slice::starts_with (const Slice & x) const inline
Definition at line 93 of file slice.h.
References data_, and size_.
Referenced by rocksdb::Benchmark::Benchmark(), rocksdb::DBImpl::GetProperty(), rocksdb::StressTest::OperateDb(), rocksdb::ParseFileName(), rocksdb::Benchmark::PrefixScanRandom(), rocksdb::SetCurrentFile(), rocksdb::StressTest::StressTest(), and rocksdb::TEST().
{
     return ((size_ >= x.size_) &&
             (memcmp(data_, x.data_, x.size_) == 0));
   }
std::string rocksdb::Slice::ToString (bool hex = false) const inline
Definition at line 72 of file slice.h.
References data_, and size_.
Referenced by rocksdb::BloomTest::Add(), rocksdb::Constructor::Add(), rocksdb::DBTest::AllEntriesFor(), rocksdb::ParsedInternalKey::DebugString(), rocksdb::VersionEdit::DecodeFrom(), rocksdb::InMemoryHandler::Delete(), rocksdb::Benchmark::DeleteMany(), rocksdb::DBDumperCommand::DoCommand(), rocksdb::ScanCommand::DoCommand(), rocksdb::DBImpl::DoCompactionWork(), rocksdb::TtlTest::TestFilter::Filter(), rocksdb::BlockConstructor::FinishImpl(), rocksdb::MemTable::Get(), rocksdb::Benchmark::GetMany(), rocksdb::RedisLists::Index(), rocksdb::DBTest::IterStatus(), rocksdb::SimpleTableDBTest::IterStatus(), main(), rocksdb::MakeKey(), rocksdb::MergeHelper::MergeUntil(), rocksdb::StressTest::MultiDelete(), rocksdb::StressTest::MultiGet(), rocksdb::StressTest::MultiPrefixScan(), rocksdb::StressTest::MultiPut(), rocksdb::RedisLists::PopLeft(), rocksdb::RedisLists::Print(), rocksdb::PrintContents(), rocksdb::Benchmark::PrintEnvironment(), rocksdb::InMemoryHandler::Put(), rocksdb::Benchmark::PutMany(), rocksdb::log::LogTest::Read(), rocksdb::SstFileReader::ReadSequential(), rocksdb::Stats::Report(), rocksdb::Benchmark::Run(), rocksdb::SaveValue(), rocksdb::ModelDB::ModelIter::Seek(), rocksdb::VersionEdit::SetComparatorName(), rocksdb::SetCurrentFile(), rocksdb::VersionSet::SetupOtherInputs(), rocksdb::TEST(), rocksdb::TestKey(), rocksdb::Harness::ToString(), and rocksdb::ModelDB::Write().
{
     if (hex) {
       std::string result;
       char buf[10];
       for (size_t i = 0; i < size_; i++) {
         snprintf(buf, 10, "%02X", (unsigned char)data_[i]);
         result += buf;
       }
       return result;
     } else {
       return std::string(data_, size_);
     }
   }
Member Data Documentation
const char* rocksdb::Slice::data_
Definition at line 99 of file slice.h.
Referenced by clear(), compare(), data(), operator[](), remove_prefix(), starts_with(), and ToString().
size_t rocksdb::Slice::size_
Definition at line 100 of file slice.h.
Referenced by clear(), compare(), empty(), remove_prefix(), size(), starts_with(), ToString(), and rocksdb::TtlIterator::value().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/include/rocksdb/slice.h