rippled: ripple::uint128 Class Reference
ripple::uint128 Class Reference
#include <UInt128.h>
Public Types
typedef base_uint128 basetype
Public Types inherited from ripple::base_uint< BITS >
typedef std::size_t size_type
typedef std::ptrdiff_t difference_type
typedef unsigned char value_type
typedef value_type * pointer
typedef value_type & reference
typedef value_type const * const_pointer
typedef value_type const & const_reference
typedef pointer iterator
typedef const_pointer const_iterator
typedef std::reverse_iterator
< iterator > reverse_iterator
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator
typedef beast::hardened_hash
< base_uint > hasher
Public Member Functions
uint128 ()
uint128 (const basetype &b)
uint128 & operator= (const basetype &b)
uint128 (Blob const &vch)
Public Member Functions inherited from ripple::base_uint< BITS >
base_uint ()
pointer data ()
const_pointer data () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
const_iterator cbegin () const
const_iterator cend () const
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
bool isZero () const
bool isNonZero () const
bool operator! () const
const base_uint operator~ () const
base_uint & operator= (std::uint64_t uHost)
base_uint & operator^= (const base_uint &b)
base_uint & operator&= (const base_uint &b)
base_uint & operator|= (const base_uint &b)
base_uint & operator++ ()
const base_uint operator++ (int)
base_uint & operator-- ()
const base_uint operator-- (int)
base_uint & operator+= (const base_uint &b)
std::string GetHex () const
void SetHexExact (const char *psz)
bool SetHex (const char *psz, bool bStrict=false)
bool SetHex (const std::string &str, bool bStrict=false)
void SetHexExact (const std::string &str)
std::string ToString () const
unsigned int size () const
void zero ()
unsigned int GetSerializeSize (int nType=0) const
template<typename Stream >
void Serialize (Stream &s, int nType=0) const
template<typename Stream >
void Unserialize (Stream &s, int nType=0)
Static Public Member Functions
static uint128 low128 (base_uint256 const &b)
Private Member Functions
uint128 (value_type const *ptr)
Additional Inherited Members
Static Public Attributes inherited from ripple::base_uint< BITS >
static std::size_t const bytes = (BITS/8)
Protected Types inherited from ripple::base_uint< BITS >
enum { WIDTH = BITS / 32 }
Protected Member Functions inherited from ripple::base_uint< BITS >
base_uint (void const *data, FromVoid)
Protected Attributes inherited from ripple::base_uint< BITS >
unsigned int pn [WIDTH]
Detailed Description
Definition at line 32 of file UInt128.h.
Member Typedef Documentation
typedef base_uint128 ripple::uint128::basetype
Definition at line 41 of file UInt128.h.
Constructor & Destructor Documentation
ripple::uint128::uint128 (value_type const * ptr) inline private
Definition at line 35 of file UInt128.h.
References ripple::base_uint< BITS >::bytes, and ripple::base_uint< BITS >::pn.
     {
         memcpy (pn, ptr, bytes);
     }
ripple::uint128::uint128 () inline
Definition at line 43 of file UInt128.h.
References ripple::base_uint< BITS >::zero().
Referenced by low128().
     {
         zero ();
     }
ripple::uint128::uint128 (const basetype & b) inline
Definition at line 48 of file UInt128.h.
     {
         *this = b;
     }
ripple::uint128::uint128 (Blob const & vch) inline explicit
Definition at line 61 of file UInt128.h.
References ripple::base_uint< BITS >::pn, ripple::base_uint< BITS >::size(), and ripple::base_uint< BITS >::zero().
     {
         if (vch.size () == size ())
             memcpy (pn, &vch[0], size ());
         else
             zero ();
     }
Member Function Documentation
static uint128 ripple::uint128::low128 (base_uint256 const & b) inline static
Definition at line 69 of file UInt128.h.
References ripple::base_uint< BITS >::data(), and uint128().
Referenced by ripple::CKey::PassPhraseToKey().
     {
         return uint128 (b.data());
     }
uint128& ripple::uint128::operator= (const basetype & b) inline
Definition at line 53 of file UInt128.h.
References ripple::base_uint< BITS >::pn, and ripple::base_uint< BITS >::WIDTH.
     {
         for (int i = 0; i < WIDTH; i++)
             pn[i] = b.pn[i];
         return *this;
     }
The documentation for this class was generated from the following file:
rippled/src/ripple/types/api/UInt128.h