rippled: beast::CharPointer_UTF32 Class Reference
beast::CharPointer_UTF32 Class Reference
#include <CharPointer_UTF32.h>
Public Types
typedef beast_wchar CharType
Public Member Functions
CharPointer_UTF32 (const CharType *const rawPointer) noexcept
CharPointer_UTF32 (const CharPointer_UTF32 &other) noexcept
CharPointer_UTF32 operator= (CharPointer_UTF32 other) noexcept
CharPointer_UTF32 operator= (const CharType *text) noexcept
bool operator== (CharPointer_UTF32 other) const noexcept
bool operator!= (CharPointer_UTF32 other) const noexcept
bool operator<= (CharPointer_UTF32 other) const noexcept
bool operator< (CharPointer_UTF32 other) const noexcept
bool operator>= (CharPointer_UTF32 other) const noexcept
bool operator> (CharPointer_UTF32 other) const noexcept
CharType * getAddress () const noexcept
operator const CharType * () const noexcept
bool isEmpty () const noexcept
beast_wchar operator* () const noexcept
CharPointer_UTF32 operator++ () noexcept
CharPointer_UTF32 operator-- () noexcept
beast_wchar getAndAdvance () noexcept
CharPointer_UTF32 operator++ (int) noexcept
void operator+= (const int numToSkip) noexcept
void operator-= (const int numToSkip) noexcept
beast_wchar & operator[] (const int characterIndex) const noexcept
CharPointer_UTF32 operator+ (const int numToSkip) const noexcept
CharPointer_UTF32 operator- (const int numToSkip) const noexcept
void write (const beast_wchar charToWrite) noexcept
void replaceChar (const beast_wchar newChar) noexcept
void writeNull () const noexcept
size_t length () const noexcept
size_t lengthUpTo (const size_t maxCharsToCount) const noexcept
size_t lengthUpTo (const CharPointer_UTF32 end) const noexcept
size_t sizeInBytes () const noexcept
CharPointer_UTF32 findTerminatingNull () const noexcept
template<typename CharPointer >
void writeAll (const CharPointer src) noexcept
void writeAll (const CharPointer_UTF32 src) noexcept
template<typename CharPointer >
size_t writeWithDestByteLimit (const CharPointer src, const size_t maxDestBytes) noexcept
template<typename CharPointer >
void writeWithCharLimit (const CharPointer src, const int maxChars) noexcept
template<typename CharPointer >
int compare (const CharPointer other) const noexcept
int compare (const CharPointer_UTF32 other) const noexcept
template<typename CharPointer >
int compareUpTo (const CharPointer other, const int maxChars) const noexcept
template<typename CharPointer >
int compareIgnoreCase (const CharPointer other) const
template<typename CharPointer >
int compareIgnoreCaseUpTo (const CharPointer other, const int maxChars) const noexcept
template<typename CharPointer >
int indexOf (const CharPointer stringToFind) const noexcept
int indexOf (const beast_wchar charToFind) const noexcept
int indexOf (const beast_wchar charToFind, const bool ignoreCase) const noexcept
bool isWhitespace () const
bool isDigit () const
bool isLetter () const
bool isLetterOrDigit () const
bool isUpperCase () const
bool isLowerCase () const
beast_wchar toUpperCase () const noexcept
beast_wchar toLowerCase () const noexcept
int getIntValue32 () const noexcept
std::int64_t getIntValue64 () const noexcept
double getDoubleValue () const noexcept
CharPointer_UTF32 findEndOfWhitespace () const noexcept
CharPointer_UTF32 atomicSwap (const CharPointer_UTF32 newValue)
Static Public Member Functions
static size_t getBytesRequiredFor (const beast_wchar) noexcept
template<class CharPointer >
static size_t getBytesRequiredFor (const CharPointer text) noexcept
static bool canRepresent (beast_wchar character) noexcept
static bool isValidString (const CharType *dataToTest, int maxBytesToRead)
Private Attributes
CharType * data
Detailed Description
Wraps a pointer to a null-terminated UTF-32 character string, and provides various methods to operate on the data.
See Also
CharPointer_UTF8, CharPointer_UTF16
Definition at line 42 of file CharPointer_UTF32.h.
Member Typedef Documentation
typedef beast_wchar beast::CharPointer_UTF32::CharType
Definition at line 45 of file CharPointer_UTF32.h.
Constructor & Destructor Documentation
beast::CharPointer_UTF32::CharPointer_UTF32 (const CharType *const rawPointer) inline explicit noexcept
Definition at line 47 of file CharPointer_UTF32.h.
Referenced by atomicSwap(), findTerminatingNull(), operator+(), and operator-().
         : data (const_cast <CharType*> (rawPointer))
     {
     }
beast::CharPointer_UTF32::CharPointer_UTF32 (const CharPointer_UTF32 & other) inline noexcept
Definition at line 52 of file CharPointer_UTF32.h.
         : data (other.data)
     {
     }
Member Function Documentation
CharPointer_UTF32 beast::CharPointer_UTF32::atomicSwap (const CharPointer_UTF32 newValue) inline
Atomically swaps this pointer for a new value, returning the previous value.
Definition at line 371 of file CharPointer_UTF32.h.
References CharPointer_UTF32(), and data.
     {
         return CharPointer_UTF32 (reinterpret_cast <Atomic<CharType*>&> (data).exchange (newValue.data));
     }
static bool beast::CharPointer_UTF32::canRepresent (beast_wchar character) inline static noexcept
Returns true if the given unicode character can be represented in this encoding.
Definition at line 353 of file CharPointer_UTF32.h.
Referenced by isValidString().
     {
         return ((unsigned int) character) < (unsigned int) 0x10ffff;
     }
template<typename CharPointer > int beast::CharPointer_UTF32::compare (const CharPointer other) const inline noexcept
Compares this string with another one.
Definition at line 259 of file CharPointer_UTF32.h.
References beast::CharacterFunctions::compare().
     {
         return CharacterFunctions::compare (*this, other);
     }
int beast::CharPointer_UTF32::compare (const CharPointer_UTF32 other) const inline noexcept
Compares this string with another one.
Definition at line 266 of file CharPointer_UTF32.h.
References data.
     {
         return wcscmp (data, other.data);
     }
template<typename CharPointer > int beast::CharPointer_UTF32::compareIgnoreCase (const CharPointer other) const inline
Compares this string with another one.
Definition at line 281 of file CharPointer_UTF32.h.
References beast::CharacterFunctions::compareIgnoreCase().
     {
         return CharacterFunctions::compareIgnoreCase (*this, other);
     }
template<typename CharPointer > int beast::CharPointer_UTF32::compareIgnoreCaseUpTo (const CharPointer other, const int maxChars) const inline noexcept
Compares this string with another one, up to a specified number of characters.
Definition at line 288 of file CharPointer_UTF32.h.
References beast::CharacterFunctions::compareIgnoreCaseUpTo().
     {
         return CharacterFunctions::compareIgnoreCaseUpTo (*this, other, maxChars);
     }
template<typename CharPointer > int beast::CharPointer_UTF32::compareUpTo (const CharPointer other, const int maxChars) const inline noexcept
Compares this string with another one, up to a specified number of characters.
Definition at line 274 of file CharPointer_UTF32.h.
References beast::CharacterFunctions::compareUpTo().
     {
         return CharacterFunctions::compareUpTo (*this, other, maxChars);
     }
CharPointer_UTF32 beast::CharPointer_UTF32::findEndOfWhitespace () const inline noexcept
Returns the first non-whitespace character in the string.
Definition at line 350 of file CharPointer_UTF32.h.
References beast::CharacterFunctions::findEndOfWhitespace().
 { return CharacterFunctions::findEndOfWhitespace (*this); }
CharPointer_UTF32 beast::CharPointer_UTF32::findTerminatingNull () const inline noexcept
Returns a pointer to the null character that terminates this string.
Definition at line 213 of file CharPointer_UTF32.h.
References CharPointer_UTF32(), data, and length().
     {
         return CharPointer_UTF32 (data + length());
     }
CharType* beast::CharPointer_UTF32::getAddress () const inline noexcept
Returns the address that this pointer is pointing to.
Definition at line 78 of file CharPointer_UTF32.h.
References data.
 { return data; }
beast_wchar beast::CharPointer_UTF32::getAndAdvance () inline noexcept
Returns the character that this pointer is currently pointing to, and then advances the pointer to point to the next character.
Definition at line 105 of file CharPointer_UTF32.h.
References data.
 { return *data++; }
static size_t beast::CharPointer_UTF32::getBytesRequiredFor (const beast_wchar) inline static noexcept
Returns the number of bytes that would be needed to represent the given unicode character in this encoding format.
Definition at line 197 of file CharPointer_UTF32.h.
     {
         return sizeof (CharType);
     }
template<class CharPointer > static size_t beast::CharPointer_UTF32::getBytesRequiredFor (const CharPointer text) inline static noexcept
Returns the number of bytes that would be needed to represent the given string in this encoding format. The value returned does NOT include the terminating null character.
Definition at line 207 of file CharPointer_UTF32.h.
     {
         return sizeof (CharType) * text.length();
     }
double beast::CharPointer_UTF32::getDoubleValue () const inline noexcept
Parses this string as a floating point double.
Definition at line 347 of file CharPointer_UTF32.h.
References beast::CharacterFunctions::getDoubleValue().
 { return CharacterFunctions::getDoubleValue (*this); }
int beast::CharPointer_UTF32::getIntValue32 () const inline noexcept
Parses this string as a 32-bit integer.
Definition at line 342 of file CharPointer_UTF32.h.
 { return CharacterFunctions::getIntValue <int, CharPointer_UTF32> (*this); }
std::int64_t beast::CharPointer_UTF32::getIntValue64 () const inline noexcept
Parses this string as a 64-bit integer.
Definition at line 344 of file CharPointer_UTF32.h.
 { return CharacterFunctions::getIntValue <std::int64_t, CharPointer_UTF32> (*this); }
template<typename CharPointer > int beast::CharPointer_UTF32::indexOf (const CharPointer stringToFind) const inline noexcept
Returns the character index of a substring, or -1 if it isn't found.
Definition at line 295 of file CharPointer_UTF32.h.
References beast::CharacterFunctions::indexOf().
     {
         return CharacterFunctions::indexOf (*this, stringToFind);
     }
int beast::CharPointer_UTF32::indexOf (const beast_wchar charToFind) const inline noexcept
Returns the character index of a unicode character, or -1 if it isn't found.
Definition at line 301 of file CharPointer_UTF32.h.
References data.
     {
         int i = 0;
         while (data[i] != 0)
         {
             if (data[i] == charToFind)
                 return i;
             ++i;
         }
         return -1;
     }
int beast::CharPointer_UTF32::indexOf (const beast_wchar charToFind, const bool ignoreCase) const inline noexcept
Returns the character index of a unicode character, or -1 if it isn't found.
Definition at line 317 of file CharPointer_UTF32.h.
References beast::CharacterFunctions::indexOfChar(), and beast::CharacterFunctions::indexOfCharIgnoreCase().
     {
         return ignoreCase ? CharacterFunctions::indexOfCharIgnoreCase (*this, charToFind)
                           : CharacterFunctions::indexOfChar (*this, charToFind);
     }
bool beast::CharPointer_UTF32::isDigit () const inline
Returns true if the first character of this string is a digit.
Definition at line 326 of file CharPointer_UTF32.h.
References data, and beast::CharacterFunctions::isDigit().
 { return CharacterFunctions::isDigit (*data) != 0; }
bool beast::CharPointer_UTF32::isEmpty () const inline noexcept
Returns true if this pointer is pointing to a null character.
Definition at line 84 of file CharPointer_UTF32.h.
References data.
 { return *data == 0; }
bool beast::CharPointer_UTF32::isLetter () const inline
Returns true if the first character of this string is a letter.
Definition at line 328 of file CharPointer_UTF32.h.
References data, and beast::CharacterFunctions::isLetter().
 { return CharacterFunctions::isLetter (*data) != 0; }
bool beast::CharPointer_UTF32::isLetterOrDigit () const inline
Returns true if the first character of this string is a letter or digit.
Definition at line 330 of file CharPointer_UTF32.h.
References data, and beast::CharacterFunctions::isLetterOrDigit().
 { return CharacterFunctions::isLetterOrDigit (*data) != 0; }
bool beast::CharPointer_UTF32::isLowerCase () const inline
Returns true if the first character of this string is lower-case.
Definition at line 334 of file CharPointer_UTF32.h.
References data, and beast::CharacterFunctions::isLowerCase().
 { return CharacterFunctions::isLowerCase (*data) != 0; }
bool beast::CharPointer_UTF32::isUpperCase () const inline
Returns true if the first character of this string is upper-case.
Definition at line 332 of file CharPointer_UTF32.h.
References data, and beast::CharacterFunctions::isUpperCase().
 { return CharacterFunctions::isUpperCase (*data) != 0; }
static bool beast::CharPointer_UTF32::isValidString (const CharType * dataToTest, int maxBytesToRead) inline static
Returns true if this data contains a valid string in this encoding.
Definition at line 359 of file CharPointer_UTF32.h.
References canRepresent().
     {
         maxBytesToRead /= sizeof (CharType);
         while (--maxBytesToRead >= 0 && *dataToTest != 0)
             if (! canRepresent (*dataToTest++))
                 return false;
         return true;
     }
bool beast::CharPointer_UTF32::isWhitespace () const inline
Returns true if the first character of this string is whitespace.
Definition at line 324 of file CharPointer_UTF32.h.
References data, and beast::CharacterFunctions::isWhitespace().
 { return CharacterFunctions::isWhitespace (*data) != 0; }
size_t beast::CharPointer_UTF32::length () const inline noexcept
Returns the number of characters in this string.
Definition at line 162 of file CharPointer_UTF32.h.
References data.
Referenced by findTerminatingNull(), and sizeInBytes().
     {
        #if BEAST_NATIVE_WCHAR_IS_UTF32 && ! BEAST_ANDROID
         return wcslen (data);
        #else
         size_t n = 0;
         while (data[n] != 0)
             ++n;
         return n;
        #endif
     }
size_t beast::CharPointer_UTF32::lengthUpTo (const size_t maxCharsToCount) const inline noexcept
Returns the number of characters in this string, or the given value, whichever is lower.
Definition at line 175 of file CharPointer_UTF32.h.
References beast::CharacterFunctions::lengthUpTo().
     {
         return CharacterFunctions::lengthUpTo (*this, maxCharsToCount);
     }
size_t beast::CharPointer_UTF32::lengthUpTo (const CharPointer_UTF32 end) const inline noexcept
Returns the number of characters in this string, or up to the given end pointer, whichever is lower.
Definition at line 181 of file CharPointer_UTF32.h.
References beast::CharacterFunctions::lengthUpTo().
     {
         return CharacterFunctions::lengthUpTo (*this, end);
     }
beast::CharPointer_UTF32::operator const CharType * () const inline noexcept
Returns the address that this pointer is pointing to.
Definition at line 81 of file CharPointer_UTF32.h.
References data.
 { return data; }
bool beast::CharPointer_UTF32::operator!= (CharPointer_UTF32 other) const inline noexcept
Definition at line 71 of file CharPointer_UTF32.h.
References data.
 { return data != other.data; }
beast_wchar beast::CharPointer_UTF32::operator* () const inline noexcept
Returns the unicode character that this pointer is pointing to.
Definition at line 87 of file CharPointer_UTF32.h.
References data.
 { return *data; }
CharPointer_UTF32 beast::CharPointer_UTF32::operator+ (const int numToSkip) const inline noexcept
Returns a pointer which is moved forwards from this one by the specified number of characters.
Definition at line 133 of file CharPointer_UTF32.h.
References CharPointer_UTF32(), and data.
     {
         return CharPointer_UTF32 (data + numToSkip);
     }
CharPointer_UTF32 beast::CharPointer_UTF32::operator++ () inline noexcept
Moves this pointer along to the next character in the string.
Definition at line 90 of file CharPointer_UTF32.h.
References data.
     {
         ++data;
         return *this;
     }
CharPointer_UTF32 beast::CharPointer_UTF32::operator++ (int) inline noexcept
Moves this pointer along to the next character in the string.
Definition at line 108 of file CharPointer_UTF32.h.
References data.
     {
         CharPointer_UTF32 temp (*this);
         ++data;
         return temp;
     }
void beast::CharPointer_UTF32::operator+= (const int numToSkip) inline noexcept
Moves this pointer forwards by the specified number of characters.
Definition at line 116 of file CharPointer_UTF32.h.
References data.
     {
         data += numToSkip;
     }
CharPointer_UTF32 beast::CharPointer_UTF32::operator- (const int numToSkip) const inline noexcept
Returns a pointer which is moved backwards from this one by the specified number of characters.
Definition at line 139 of file CharPointer_UTF32.h.
References CharPointer_UTF32(), and data.
     {
         return CharPointer_UTF32 (data - numToSkip);
     }
CharPointer_UTF32 beast::CharPointer_UTF32::operator-- () inline noexcept
Moves this pointer to the previous character in the string.
Definition at line 97 of file CharPointer_UTF32.h.
References data.
     {
         --data;
         return *this;
     }
void beast::CharPointer_UTF32::operator-= (const int numToSkip) inline noexcept
Definition at line 121 of file CharPointer_UTF32.h.
References data.
     {
         data -= numToSkip;
     }
bool beast::CharPointer_UTF32::operator< (CharPointer_UTF32 other) const inline noexcept
Definition at line 73 of file CharPointer_UTF32.h.
References data.
 { return data <  other.data; }
bool beast::CharPointer_UTF32::operator<= (CharPointer_UTF32 other) const inline noexcept
Definition at line 72 of file CharPointer_UTF32.h.
References data.
 { return data <= other.data; }
CharPointer_UTF32 beast::CharPointer_UTF32::operator= (CharPointer_UTF32 other) inline noexcept
Definition at line 57 of file CharPointer_UTF32.h.
References data.
     {
         data = other.data;
         return *this;
     }
CharPointer_UTF32 beast::CharPointer_UTF32::operator= (const CharType * text) inline noexcept
Definition at line 63 of file CharPointer_UTF32.h.
References data.
     {
         data = const_cast <CharType*> (text);
         return *this;
     }
bool beast::CharPointer_UTF32::operator== (CharPointer_UTF32 other) const inline noexcept
This is a pointer comparison, it doesn't compare the actual text.
Definition at line 70 of file CharPointer_UTF32.h.
References data.
 { return data == other.data; }
bool beast::CharPointer_UTF32::operator> (CharPointer_UTF32 other) const inline noexcept
Definition at line 75 of file CharPointer_UTF32.h.
References data.
 { return data >  other.data; }
bool beast::CharPointer_UTF32::operator>= (CharPointer_UTF32 other) const inline noexcept
Definition at line 74 of file CharPointer_UTF32.h.
References data.
 { return data >= other.data; }
beast_wchar& beast::CharPointer_UTF32::operator[] (const int characterIndex) const inline noexcept
Returns the character at a given character index from the start of the string.
Definition at line 127 of file CharPointer_UTF32.h.
References data.
     {
         return data [characterIndex];
     }
void beast::CharPointer_UTF32::replaceChar (const beast_wchar newChar) inline noexcept
Definition at line 150 of file CharPointer_UTF32.h.
References data.
     {
         *data = newChar;
     }
size_t beast::CharPointer_UTF32::sizeInBytes () const inline noexcept
Returns the number of bytes that are used to represent this string. This includes the terminating null character.
Definition at line 189 of file CharPointer_UTF32.h.
References length().
     {
         return sizeof (CharType) * (length() + 1);
     }
beast_wchar beast::CharPointer_UTF32::toLowerCase () const inline noexcept
Returns a lower-case version of the first character of this string.
Definition at line 339 of file CharPointer_UTF32.h.
References data, and beast::CharacterFunctions::toLowerCase().
 { return CharacterFunctions::toLowerCase (*data); }
beast_wchar beast::CharPointer_UTF32::toUpperCase () const inline noexcept
Returns an upper-case version of the first character of this string.
Definition at line 337 of file CharPointer_UTF32.h.
References data, and beast::CharacterFunctions::toUpperCase().
 { return CharacterFunctions::toUpperCase (*data); }
void beast::CharPointer_UTF32::write (const beast_wchar charToWrite) inline noexcept
Writes a unicode character to this string, and advances this pointer to point to the next position.
Definition at line 145 of file CharPointer_UTF32.h.
References data.
     {
         *data++ = charToWrite;
     }
template<typename CharPointer > void beast::CharPointer_UTF32::writeAll (const CharPointer src) inline noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
Definition at line 220 of file CharPointer_UTF32.h.
References beast::CharacterFunctions::copyAll().
     {
         CharacterFunctions::copyAll (*this, src);
     }
void beast::CharPointer_UTF32::writeAll (const CharPointer_UTF32 src) inline noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
Definition at line 226 of file CharPointer_UTF32.h.
References data.
     {
         const CharType* s = src.data;
         while ((*data = *s) != 0)
         {
             ++data;
             ++s;
         }
     }
void beast::CharPointer_UTF32::writeNull () const inline noexcept
Writes a null character to this string (leaving the pointer's position unchanged).
Definition at line 156 of file CharPointer_UTF32.h.
References data.
     {
         *data = 0;
     }
template<typename CharPointer > void beast::CharPointer_UTF32::writeWithCharLimit (const CharPointer src, const int maxChars) inline noexcept
Copies a source string to this pointer, advancing this pointer as it goes. The maxChars parameter specifies the maximum number of characters that can be written to the destination buffer before stopping (including the terminating null).
Definition at line 252 of file CharPointer_UTF32.h.
References beast::CharacterFunctions::copyWithCharLimit().
     {
         CharacterFunctions::copyWithCharLimit (*this, src, maxChars);
     }
template<typename CharPointer > size_t beast::CharPointer_UTF32::writeWithDestByteLimit (const CharPointer src, const size_t maxDestBytes) inline noexcept
Copies a source string to this pointer, advancing this pointer as it goes. The maxDestBytes parameter specifies the maximum number of bytes that can be written to the destination buffer before stopping.
Definition at line 242 of file CharPointer_UTF32.h.
References beast::CharacterFunctions::copyWithDestByteLimit().
     {
         return CharacterFunctions::copyWithDestByteLimit (*this, src, maxDestBytes);
     }
Member Data Documentation
CharType* beast::CharPointer_UTF32::data private
Definition at line 377 of file CharPointer_UTF32.h.
Referenced by atomicSwap(), compare(), findTerminatingNull(), getAddress(), getAndAdvance(), indexOf(), isDigit(), isEmpty(), isLetter(), isLetterOrDigit(), isLowerCase(), isUpperCase(), isWhitespace(), length(), operator const CharType *(), operator!=(), operator*(), operator+(), operator++(), operator+=(), operator-(), operator--(), operator-=(), operator<(), operator<=(), operator=(), operator==(), operator>(), operator>=(), operator[](), replaceChar(), toLowerCase(), toUpperCase(), write(), writeAll(), and writeNull().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/strings/CharPointer_UTF32.h