rippled: beast.util.Dict Namespace Reference
beast.util.Dict Namespace Reference
Functions
def compose
def get_items_with_prefix
def compose_prefix_dicts
Function Documentation
def beast.util.Dict.compose (dicts)
Definition at line 3 of file Dict.py.
Referenced by beast.util.Dict.compose_prefix_dicts().
 def compose(*dicts):
     result = {}
     for d in dicts:
         result.update(**d)
     return result
def beast.util.Dict.compose_prefix_dicts (key, mapping)
Definition at line 16 of file Dict.py.
References beast.util.Dict.compose(), and beast.util.Dict.get_items_with_prefix().
 def compose_prefix_dicts(key, mapping):
     return compose(*get_items_with_prefix(key, mapping))
def beast.util.Dict.get_items_with_prefix (key, mapping)
Get all elements from the mapping whose keys are a prefix of the given
key, sorted by increasing key length.
Definition at line 9 of file Dict.py.
Referenced by beast.util.Dict.compose_prefix_dicts().
 def get_items_with_prefix(key, mapping):
     """Get all elements from the mapping whose keys are a prefix of the given
     key, sorted by increasing key length."""
     for k, v in sorted(mapping.items()):
         if key.startswith(k):
             yield v