rippled: ripple::InboundLedgers Class Reference
ripple::InboundLedgers Class Reference abstract
#include <InboundLedgers.h>
Public Types
typedef beast::abstract_clock
< std::chrono::seconds > clock_type
Public Member Functions
virtual ~InboundLedgers ()=0
virtual InboundLedger::pointer findCreate (uint256 const &hash, std::uint32_t seq, InboundLedger::fcReason)=0
virtual InboundLedger::pointer find (LedgerHash const &hash)=0
virtual bool hasLedger (LedgerHash const &ledgerHash)=0
virtual void dropLedger (LedgerHash const &ledgerHash)=0
virtual bool gotLedgerData (LedgerHash const &ledgerHash, boost::shared_ptr< Peer >, boost::shared_ptr< protocol::TMLedgerData >)=0
virtual void doLedgerData (Job &, LedgerHash hash)=0
virtual void gotStaleData (boost::shared_ptr< protocol::TMLedgerData > packet)=0
virtual int getFetchCount (int &timeoutCount)=0
virtual void logFailure (uint256 const &h)=0
virtual bool isFailure (uint256 const &h)=0
virtual void clearFailures ()=0
virtual Json::Value getInfo ()=0
virtual void gotFetchPack (Job &)=0
virtual void sweep ()=0
virtual void onStop ()=0
Static Public Member Functions
static InboundLedgers * New (clock_type &clock, beast::Stoppable &parent, beast::insight::Collector::ptr const &collector)
Detailed Description
Manages the lifetime of inbound ledgers.
See Also
InboundLedger
Definition at line 29 of file InboundLedgers.h.
Member Typedef Documentation
typedef beast::abstract_clock<std::chrono::seconds> ripple::InboundLedgers::clock_type
Definition at line 32 of file InboundLedgers.h.
Constructor & Destructor Documentation
ripple::InboundLedgers::~InboundLedgers () pure virtual
Definition at line 394 of file InboundLedgers.cpp.
 {
 }
Member Function Documentation
virtual void ripple::InboundLedgers::clearFailures () pure virtual
Implemented in ripple::InboundLedgersImp.
Referenced by ripple::NetworkOPsImp::clearLedgerFetch().
virtual void ripple::InboundLedgers::doLedgerData (Job & , LedgerHash hash) pure virtual
Implemented in ripple::InboundLedgersImp.
Referenced by ripple::InboundLedgersImp::gotLedgerData().
virtual void ripple::InboundLedgers::dropLedger (LedgerHash const & ledgerHash) pure virtual
Implemented in ripple::InboundLedgersImp.
Referenced by ripple::NetworkOPsImp::checkLastClosedLedger(), ripple::LedgerMasterImp::findNewLedgersToPublish(), and ripple::TACompletionHandler().
virtual InboundLedger::pointer ripple::InboundLedgers::find (LedgerHash const & hash) pure virtual
Implemented in ripple::InboundLedgersImp.
virtual InboundLedger::pointer ripple::InboundLedgers::findCreate (uint256 const & hash, std::uint32_t seq, InboundLedger::fcReason) pure virtual
Implemented in ripple::InboundLedgersImp.
Referenced by ripple::LedgerMasterImp::checkAccept(), ripple::NetworkOPsImp::checkLastClosedLedger(), ripple::LedgerMasterImp::doAdvance(), ripple::LedgerCleanerImp::doLedger(), ripple::LedgerMasterImp::failedSave(), ripple::LedgerMasterImp::findAcquireLedger(), ripple::LedgerMasterImp::findNewLedgersToPublish(), ripple::LedgerCleanerImp::getLedgerHash(), ripple::LedgerConsensusImp::handleLCL(), ripple::NetworkOPsImp::missingNodeInLedger(), ripple::LedgerMasterImp::updatePaths(), and ripple::Ledger::visitStateItems().
virtual int ripple::InboundLedgers::getFetchCount (int & timeoutCount) pure virtual
Implemented in ripple::InboundLedgersImp.
virtual Json::Value ripple::InboundLedgers::getInfo () pure virtual
Implemented in ripple::InboundLedgersImp.
Referenced by ripple::NetworkOPsImp::getLedgerFetchInfo().
virtual void ripple::InboundLedgers::gotFetchPack (Job &) pure virtual
Implemented in ripple::InboundLedgersImp.
Referenced by ripple::NetworkOPsImp::gotFetchPack().
virtual bool ripple::InboundLedgers::gotLedgerData (LedgerHash const & ledgerHash, boost::shared_ptr< Peer > , boost::shared_ptr< protocol::TMLedgerData >) pure virtual
Implemented in ripple::InboundLedgersImp.
virtual void ripple::InboundLedgers::gotStaleData (boost::shared_ptr< protocol::TMLedgerData > packet) pure virtual
Implemented in ripple::InboundLedgersImp.
Referenced by ripple::InboundLedgersImp::gotLedgerData(), and ripple::InboundLedger::~InboundLedger().
virtual bool ripple::InboundLedgers::hasLedger (LedgerHash const & ledgerHash) pure virtual
Implemented in ripple::InboundLedgersImp.
virtual bool ripple::InboundLedgers::isFailure (uint256 const & h) pure virtual
Implemented in ripple::InboundLedgersImp.
Referenced by ripple::LedgerMasterImp::doAdvance().
virtual void ripple::InboundLedgers::logFailure (uint256 const & h) pure virtual
Implemented in ripple::InboundLedgersImp.
Referenced by ripple::InboundLedger::done().
InboundLedgers * ripple::InboundLedgers::New (clock_type & clock, beast::Stoppable & parent, beast::insight::Collector::ptr const & collector) static
Definition at line 398 of file InboundLedgers.cpp.
 {
     return new InboundLedgersImp (clock, parent, collector);
 }
virtual void ripple::InboundLedgers::onStop () pure virtual
Implemented in ripple::InboundLedgersImp.
virtual void ripple::InboundLedgers::sweep () pure virtual
Implemented in ripple::InboundLedgersImp.
Referenced by ripple::ApplicationImp::doSweep().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/ledger/InboundLedgers.h
rippled/src/ripple_app/ledger/InboundLedgers.cpp