rippled: beast::HTTPHeaders Class Reference
beast::HTTPHeaders Class Reference
#include <HTTPHeaders.h>
Public Member Functions
HTTPHeaders ()
HTTPHeaders (StringPairArray &fields)
HTTPHeaders (StringPairArray const &fields)
HTTPHeaders (HTTPHeaders const &other)
HTTPHeaders & operator= (HTTPHeaders const &other)
bool empty () const
std::size_t size () const
String toString () const
HTTPField at (int index) const
HTTPField operator[] (int index) const
String get (String const &field) const
String operator[] (String const &field) const
Private Attributes
StringPairArray m_fields
Detailed Description
A set of HTTP headers.
Definition at line 26 of file HTTPHeaders.h.
Constructor & Destructor Documentation
beast::HTTPHeaders::HTTPHeaders ()
Construct an empty set of headers.
Definition at line 22 of file HTTPHeaders.cpp.
 {
 }
beast::HTTPHeaders::HTTPHeaders (StringPairArray & fields)
Construct headers taking ownership of a field array. The callers value is overwritten.
Definition at line 26 of file HTTPHeaders.cpp.
References m_fields, and beast::StringPairArray::swapWith().
 {
     m_fields.swapWith (fields);
 }
beast::HTTPHeaders::HTTPHeaders (StringPairArray const & fields)
Construct a copy of headers from an array.
Definition at line 31 of file HTTPHeaders.cpp.
     : m_fields (fields)
 {
 }
beast::HTTPHeaders::HTTPHeaders (HTTPHeaders const & other)
Construct a copy of headers.
Definition at line 36 of file HTTPHeaders.cpp.
     : m_fields (other.m_fields)
 {
 }
Member Function Documentation
HTTPField beast::HTTPHeaders::at (int index) const
Random access to fields by index.
Definition at line 57 of file HTTPHeaders.cpp.
References beast::StringPairArray::getAllKeys(), beast::StringPairArray::getAllValues(), and m_fields.
Referenced by operator[](), and toString().
 {
     return HTTPField (m_fields.getAllKeys () [index],
                       m_fields.getAllValues () [index]);
 }
bool beast::HTTPHeaders::empty () const
Returns true if the container is empty.
Definition at line 47 of file HTTPHeaders.cpp.
References m_fields, and beast::StringPairArray::size().
 {
     return m_fields.size () == 0;
 }
String beast::HTTPHeaders::get (String const & field) const
Associative access to fields by name. If the field is not present, an empty string is returned.
Definition at line 68 of file HTTPHeaders.cpp.
References beast::field(), and m_fields.
 {
     return m_fields [field];
 }
HTTPHeaders & beast::HTTPHeaders::operator= (HTTPHeaders const & other)
Assign a copy of headers.
Definition at line 41 of file HTTPHeaders.cpp.
References m_fields.
 {
     m_fields = other.m_fields;
     return *this;
 }
HTTPField beast::HTTPHeaders::operator[] (int index) const
Definition at line 63 of file HTTPHeaders.cpp.
References at().
 {
     return at (index);
 }
String beast::HTTPHeaders::operator[] (String const & field) const
Definition at line 73 of file HTTPHeaders.cpp.
References beast::field().
 {
     return get (field);
 }
std::size_t beast::HTTPHeaders::size () const
Returns the number of fields in the container.
Definition at line 52 of file HTTPHeaders.cpp.
References m_fields, and beast::StringPairArray::size().
Referenced by beast::asio::HTTPClient_test::print().
 {
     return m_fields.size ();
 }
String beast::HTTPHeaders::toString () const
Outputs all the headers into one string.
Definition at line 78 of file HTTPHeaders.cpp.
References at(), beast::field(), m_fields, beast::HTTPField::name(), beast::newLine, beast::StringPairArray::size(), and beast::HTTPField::value().
Referenced by beast::HTTPMessage::toString().
 {
     String s;
     for (int i = 0; i < m_fields.size (); ++i)
     {
         HTTPField const field (at(i));
         s << field.name() << ": " << field.value() << newLine;
     }
     return s;
 }
Member Data Documentation
StringPairArray beast::HTTPHeaders::m_fields private
Definition at line 70 of file HTTPHeaders.h.
Referenced by at(), empty(), get(), HTTPHeaders(), operator=(), size(), and toString().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_asio/http/HTTPHeaders.h
rippled/src/beast/modules/beast_asio/http/HTTPHeaders.cpp