rippled: ripple::TrustSetTransactor Class Reference
ripple::TrustSetTransactor Class Reference
#include <TrustSetTransactor.h>
Public Member Functions
TrustSetTransactor (SerializedTransaction const &txn, TransactionEngineParams params, TransactionEngine *engine)
TER doApply ()
Public Member Functions inherited from ripple::Transactor
TER apply ()
Additional Inherited Members
Static Public Member Functions inherited from ripple::Transactor
static std::unique_ptr
< Transactor > makeTransactor (SerializedTransaction const &txn, TransactionEngineParams params, TransactionEngine *engine)
Protected Member Functions inherited from ripple::Transactor
virtual TER preCheck ()
virtual TER checkSeq ()
virtual TER payFee ()
void calculateFee ()
virtual std::uint64_t calculateBaseFee ()
virtual TER checkSig ()
Transactor (const SerializedTransaction &txn, TransactionEngineParams params, TransactionEngine *engine, beast::Journal journal=beast::Journal())
virtual bool mustHaveValidAccount ()
Protected Attributes inherited from ripple::Transactor
SerializedTransaction const & mTxn
TransactionEngine * mEngine
TransactionEngineParams mParams
uint160 mTxnAccountID
STAmount mFeeDue
STAmount mPriorBalance
STAmount mSourceBalance
SLE::pointer mTxnAccount
bool mHasAuthKey
bool mSigMaster
RippleAddress mSigningPubKey
beast::Journal m_journal
Detailed Description
Definition at line 34 of file TrustSetTransactor.h.
Constructor & Destructor Documentation
ripple::TrustSetTransactor::TrustSetTransactor (SerializedTransaction const & txn, TransactionEngineParams params, TransactionEngine * engine) inline
Definition at line 38 of file TrustSetTransactor.h.
         : Transactor (
             txn,
             params,
             engine,
             LogPartition::getJournal <TrustSetTransactorLog> ())
     {
     }
Member Function Documentation
TER ripple::TrustSetTransactor::doApply () virtual
Implements ripple::Transactor.
Definition at line 22 of file TrustSetTransactor.cpp.
References ACCOUNT_ONE, CURRENCY_BAD, ripple::TransactionEngine::entryCache(), ripple::TransactionEngine::entryModify(), ripple::Ledger::getAccountRootIndex(), ripple::STObject::getFieldAmount(), ripple::STObject::getFieldU32(), ripple::STObject::getFlags(), ripple::TransactionEngine::getLedger(), ripple::STAmount::getNValue(), ripple::Ledger::getRippleStateIndex(), ripple::is_bit_set(), ripple::STObject::isFieldPresent(), ripple::lsfHighAuth, ripple::lsfHighNoRipple, ripple::lsfHighReserve, ripple::lsfLowAuth, ripple::lsfLowNoRipple, ripple::lsfLowReserve, ripple::lsfRequireAuth, ripple::ltACCOUNT_ROOT, ripple::ltRIPPLE_STATE, ripple::Transactor::m_journal, ripple::Transactor::mEngine, ripple::Transactor::mPriorBalance, ripple::Transactor::mTxn, ripple::Transactor::mTxnAccount, ripple::Transactor::mTxnAccountID, ripple::LedgerEntrySet::ownerCountAdjust(), QUALITY_ONE, ripple::STAmount::setIssuer(), ripple::tecINSUF_RESERVE_LINE, ripple::tecNO_DST, ripple::tecNO_LINE_INSUF_RESERVE, ripple::tecNO_LINE_REDUNDANT, ripple::tefNO_AUTH_REQUIRED, ripple::temBAD_AMOUNT, ripple::temBAD_CURRENCY, ripple::temBAD_LIMIT, ripple::temDST_IS_SRC, ripple::temDST_NEEDED, ripple::temINVALID_FLAG, ripple::tesSUCCESS, ripple::tfClearNoRipple, ripple::tfSetfAuth, ripple::tfSetNoRipple, ripple::tfTrustSetMask, ripple::base_uint< BITS >::ToString(), beast::Journal::trace, ripple::LedgerEntrySet::trustCreate(), ripple::LedgerEntrySet::trustDelete(), ripple::TransactionEngine::view(), and beast::Journal::warning.
 {
     TER terResult = tesSUCCESS;
     STAmount const saLimitAmount (mTxn.getFieldAmount (sfLimitAmount));
     bool const bQualityIn (mTxn.isFieldPresent (sfQualityIn));
     bool const bQualityOut (mTxn.isFieldPresent (sfQualityOut));
     uint160 const uCurrencyID (saLimitAmount.getCurrency ());
     uint160 uDstAccountID (saLimitAmount.getIssuer ());
     // true, iff current is high account.
     bool const bHigh = mTxnAccountID > uDstAccountID;
     std::uint32_t uQualityIn (bQualityIn ? mTxn.getFieldU32 (sfQualityIn) : 0);
     std::uint32_t uQualityOut (bQualityOut ? mTxn.getFieldU32 (sfQualityOut) : 0);
     if (!saLimitAmount.isLegalNet ())
         return temBAD_AMOUNT;
     if (bQualityIn && QUALITY_ONE == uQualityIn)
         uQualityIn = 0;
     if (bQualityOut && QUALITY_ONE == uQualityOut)
         uQualityOut = 0;
     std::uint32_t const uTxFlags = mTxn.getFlags ();
     if (uTxFlags & tfTrustSetMask)
     {
         m_journal.trace <<
             "Malformed transaction: Invalid flags set.";
         return temINVALID_FLAG;
     }
     bool const bSetAuth = is_bit_set (uTxFlags, tfSetfAuth);
     bool const bSetNoRipple = is_bit_set (uTxFlags, tfSetNoRipple);
     bool const bClearNoRipple  = is_bit_set (uTxFlags, tfClearNoRipple);
     if (bSetAuth && !is_bit_set (mTxnAccount->getFieldU32 (sfFlags), lsfRequireAuth))
     {
         m_journal.trace <<
             "Retry: Auth not required.";
         return tefNO_AUTH_REQUIRED;
     }
     if (saLimitAmount.isNative ())
     {
         m_journal.trace <<
             "Malformed transaction: Native credit limit: " <<
             saLimitAmount.getFullText ();
         return temBAD_LIMIT;
     }
     if (saLimitAmount < zero)
     {
         m_journal.trace <<
             "Malformed transaction: Negative credit limit.";
         return temBAD_LIMIT;
     }
     // Check if destination makes sense.
     if (!uDstAccountID || uDstAccountID == ACCOUNT_ONE)
     {
         m_journal.trace <<
             "Malformed transaction: Destination account not specified.";
         return temDST_NEEDED;
     }
     if (mTxnAccountID == uDstAccountID)
     {
         SLE::pointer selDelete (
             mEngine->entryCache (ltRIPPLE_STATE,
                 Ledger::getRippleStateIndex (
                     mTxnAccountID, uDstAccountID, uCurrencyID)));
         if (selDelete)
         {
             m_journal.warning <<
                 "Clearing redundant line.";
             return mEngine->view ().trustDelete (
                 selDelete, mTxnAccountID, uDstAccountID);
         }
         else
         {
             m_journal.trace <<
                 "Malformed transaction: Can not extend credit to self.";
             return temDST_IS_SRC;
         }
     }
     SLE::pointer sleDst (mEngine->entryCache (
         ltACCOUNT_ROOT, Ledger::getAccountRootIndex (uDstAccountID)));
     if (!sleDst)
     {
         m_journal.trace <<
             "Delay transaction: Destination account does not exist.";
         return tecNO_DST;
     }
     std::uint32_t const uOwnerCount (mTxnAccount->getFieldU32 (sfOwnerCount));
     // The reserve required to create the line.
     std::uint64_t const uReserveCreate =
         (uOwnerCount < 2)
             ? 0
             : mEngine->getLedger ()->getReserve (uOwnerCount + 1);
     STAmount saLimitAllow = saLimitAmount;
     saLimitAllow.setIssuer (mTxnAccountID);
     SLE::pointer sleRippleState (mEngine->entryCache (ltRIPPLE_STATE,
         Ledger::getRippleStateIndex (mTxnAccountID, uDstAccountID, uCurrencyID)));
     if (sleRippleState)
     {
         STAmount        saLowBalance;
         STAmount        saLowLimit;
         STAmount        saHighBalance;
         STAmount        saHighLimit;
         std::uint32_t   uLowQualityIn;
         std::uint32_t   uLowQualityOut;
         std::uint32_t   uHighQualityIn;
         std::uint32_t   uHighQualityOut;
         const uint160&  uLowAccountID   = !bHigh ? mTxnAccountID : uDstAccountID;
         const uint160&  uHighAccountID  =  bHigh ? mTxnAccountID : uDstAccountID;
         SLE::ref        sleLowAccount   = !bHigh ? mTxnAccount : sleDst;
         SLE::ref        sleHighAccount  =  bHigh ? mTxnAccount : sleDst;
         //
         // Balances
         //
         saLowBalance    = sleRippleState->getFieldAmount (sfBalance);
         saHighBalance   = -saLowBalance;
         //
         // Limits
         //
         sleRippleState->setFieldAmount (!bHigh ? sfLowLimit : sfHighLimit, saLimitAllow);
         saLowLimit  = !bHigh ? saLimitAllow : sleRippleState->getFieldAmount (sfLowLimit);
         saHighLimit =  bHigh ? saLimitAllow : sleRippleState->getFieldAmount (sfHighLimit);
         //
         // Quality in
         //
         if (!bQualityIn)
         {
             // Not setting. Just get it.
             uLowQualityIn   = sleRippleState->getFieldU32 (sfLowQualityIn);
             uHighQualityIn  = sleRippleState->getFieldU32 (sfHighQualityIn);
         }
         else if (uQualityIn)
         {
             // Setting.
             sleRippleState->setFieldU32 (!bHigh ? sfLowQualityIn : sfHighQualityIn, uQualityIn);
             uLowQualityIn   = !bHigh ? uQualityIn : sleRippleState->getFieldU32 (sfLowQualityIn);
             uHighQualityIn  =  bHigh ? uQualityIn : sleRippleState->getFieldU32 (sfHighQualityIn);
         }
         else
         {
             // Clearing.
             sleRippleState->makeFieldAbsent (!bHigh ? sfLowQualityIn : sfHighQualityIn);
             uLowQualityIn   = !bHigh ? 0 : sleRippleState->getFieldU32 (sfLowQualityIn);
             uHighQualityIn  =  bHigh ? 0 : sleRippleState->getFieldU32 (sfHighQualityIn);
         }
         if (QUALITY_ONE == uLowQualityIn)   uLowQualityIn   = 0;
         if (QUALITY_ONE == uHighQualityIn)  uHighQualityIn  = 0;
         //
         // Quality out
         //
         if (!bQualityOut)
         {
             // Not setting. Just get it.
             uLowQualityOut  = sleRippleState->getFieldU32 (sfLowQualityOut);
             uHighQualityOut = sleRippleState->getFieldU32 (sfHighQualityOut);
         }
         else if (uQualityOut)
         {
             // Setting.
             sleRippleState->setFieldU32 (!bHigh ? sfLowQualityOut : sfHighQualityOut, uQualityOut);
             uLowQualityOut  = !bHigh ? uQualityOut : sleRippleState->getFieldU32 (sfLowQualityOut);
             uHighQualityOut =  bHigh ? uQualityOut : sleRippleState->getFieldU32 (sfHighQualityOut);
         }
         else
         {
             // Clearing.
             sleRippleState->makeFieldAbsent (!bHigh ? sfLowQualityOut : sfHighQualityOut);
             uLowQualityOut  = !bHigh ? 0 : sleRippleState->getFieldU32 (sfLowQualityOut);
             uHighQualityOut =  bHigh ? 0 : sleRippleState->getFieldU32 (sfHighQualityOut);
         }
         std::uint32_t const uFlagsIn (sleRippleState->getFieldU32 (sfFlags));
         std::uint32_t uFlagsOut (uFlagsIn);
         if (bSetNoRipple && !bClearNoRipple && (bHigh ? saHighBalance : saLowBalance) >= zero)
         {
             uFlagsOut           |= (bHigh ? lsfHighNoRipple : lsfLowNoRipple);
         }
         else if (bClearNoRipple && !bSetNoRipple)
         {
             uFlagsOut           &= ~(bHigh ? lsfHighNoRipple : lsfLowNoRipple);
         }
         if (QUALITY_ONE == uLowQualityOut)  uLowQualityOut  = 0;
         if (QUALITY_ONE == uHighQualityOut) uHighQualityOut = 0;
         bool const  bLowReserveSet      = uLowQualityIn || uLowQualityOut ||
                                           is_bit_set (uFlagsOut, lsfLowNoRipple) ||
                                           !!saLowLimit || saLowBalance > zero;
         bool const  bLowReserveClear    = !bLowReserveSet;
         bool const  bHighReserveSet     = uHighQualityIn || uHighQualityOut ||
                                           is_bit_set (uFlagsOut, lsfHighNoRipple) ||
                                           !!saHighLimit || saHighBalance > zero;
         bool const  bHighReserveClear   = !bHighReserveSet;
         bool const  bDefault            = bLowReserveClear && bHighReserveClear;
         bool const  bLowReserved        = is_bit_set (uFlagsIn, lsfLowReserve);
         bool const  bHighReserved       = is_bit_set (uFlagsIn, lsfHighReserve);
         bool        bReserveIncrease    = false;
         if (bSetAuth)
         {
             uFlagsOut           |= (bHigh ? lsfHighAuth : lsfLowAuth);
         }
         if (bLowReserveSet && !bLowReserved)
         {
             // Set reserve for low account.
             mEngine->view ().ownerCountAdjust (uLowAccountID, 1, sleLowAccount);
             uFlagsOut           |= lsfLowReserve;
             if (!bHigh)
                 bReserveIncrease    = true;
         }
         if (bLowReserveClear && bLowReserved)
         {
             // Clear reserve for low account.
             mEngine->view ().ownerCountAdjust (uLowAccountID, -1, sleLowAccount);
             uFlagsOut   &= ~lsfLowReserve;
         }
         if (bHighReserveSet && !bHighReserved)
         {
             // Set reserve for high account.
             mEngine->view ().ownerCountAdjust (uHighAccountID, 1, sleHighAccount);
             uFlagsOut   |= lsfHighReserve;
             if (bHigh)
                 bReserveIncrease    = true;
         }
         if (bHighReserveClear && bHighReserved)
         {
             // Clear reserve for high account.
             mEngine->view ().ownerCountAdjust (uHighAccountID, -1, sleHighAccount);
             uFlagsOut   &= ~lsfHighReserve;
         }
         if (uFlagsIn != uFlagsOut)
             sleRippleState->setFieldU32 (sfFlags, uFlagsOut);
         if (bDefault || CURRENCY_BAD == uCurrencyID)
         {
             // Delete.
             terResult   = mEngine->view ().trustDelete (sleRippleState, uLowAccountID, uHighAccountID);
         }
         else if (bReserveIncrease
                  && mPriorBalance.getNValue () < uReserveCreate) // Reserve is not scaled by load.
         {
             m_journal.trace <<
                 "Delay transaction: Insufficent reserve to add trust line.";
             // Another transaction could provide XRP to the account and then
             // this transaction would succeed.
             terResult   = tecINSUF_RESERVE_LINE;
         }
         else
         {
             mEngine->entryModify (sleRippleState);
             m_journal.trace <<
                 "Modify ripple line";
         }
     }
     // Line does not exist.
     else if (!saLimitAmount                                     // Setting default limit.
              && (!bQualityIn || !uQualityIn)                         // Not setting quality in or setting default quality in.
              && (!bQualityOut || !uQualityOut))                      // Not setting quality out or setting default quality out.
     {
         m_journal.trace <<
             "Redundant: Setting non-existent ripple line to defaults.";
         return tecNO_LINE_REDUNDANT;
     }
     else if (mPriorBalance.getNValue () < uReserveCreate)       // Reserve is not scaled by load.
     {
         m_journal.trace <<
             "Delay transaction: Line does not exist. Insufficent reserve to create line.";
         // Another transaction could create the account and then this transaction would succeed.
         terResult = tecNO_LINE_INSUF_RESERVE;
     }
     else if (CURRENCY_BAD == uCurrencyID)
     {
         terResult   = temBAD_CURRENCY;
     }
     else
     {
         // Zero balance in currency.
         STAmount saBalance (STAmount (uCurrencyID, ACCOUNT_ONE));
         m_journal.trace <<
             "doTrustSet: Creating ripple line: " <<
             Ledger::getRippleStateIndex (mTxnAccountID, uDstAccountID, uCurrencyID).ToString ();
         // Create a new ripple line.
         terResult = mEngine->view ().trustCreate (
                           bHigh,
                           mTxnAccountID,
                           uDstAccountID,
                           Ledger::getRippleStateIndex (mTxnAccountID, uDstAccountID, uCurrencyID),
                           mTxnAccount,
                           bSetAuth,
                           bSetNoRipple && !bClearNoRipple,
                           saBalance,
                           saLimitAllow,       // Limit for who is being charged.
                           uQualityIn,
                           uQualityOut);
     }
     return terResult;
 }
The documentation for this class was generated from the following files:
rippled/src/ripple_app/transactors/TrustSetTransactor.h
rippled/src/ripple_app/transactors/TrustSetTransactor.cpp