rippled: beast::IP::AddressV4 Struct Reference
beast::IP::AddressV4 Struct Reference
#include <IPAddressV4.h>
Classes
class Proxy
Public Member Functions
AddressV4 ()
AddressV4 (std::uint32_t value_)
AddressV4 (std::uint8_t a, std::uint8_t b, std::uint8_t c, std::uint8_t d)
bool is_broadcast () const
Static Public Member Functions
static std::pair< AddressV4, bool > from_string (std::string const &s)
static AddressV4 any ()
static AddressV4 loopback ()
static AddressV4 broadcast ()
static AddressV4 broadcast (AddressV4 const &address)
static AddressV4 broadcast (AddressV4 const &address, AddressV4 const &mask)
static char get_class (AddressV4 const &address)
static AddressV4 netmask (char address_class)
static AddressV4 netmask (AddressV4 const &v)
Friends
bool operator== (AddressV4 const &lhs, AddressV4 const &rhs)
bool operator< (AddressV4 const &lhs, AddressV4 const &rhs)
bool operator!= (AddressV4 const &lhs, AddressV4 const &rhs)
bool operator> (AddressV4 const &lhs, AddressV4 const &rhs)
bool operator<= (AddressV4 const &lhs, AddressV4 const &rhs)
bool operator>= (AddressV4 const &lhs, AddressV4 const &rhs)
std::uint32_t value
Proxy< true > operator[] (std::size_t index) const
Proxy< false > operator[] (std::size_t index)
Detailed Description
Represents a version 4 IP address.
Definition at line 34 of file IPAddressV4.h.
Constructor & Destructor Documentation
beast::IP::AddressV4::AddressV4 ()
Default constructor represents the 'any' address.
Definition at line 33 of file IPAddressV4.cpp.
Referenced by any(), broadcast(), loopback(), and netmask().
     : value (0)
 {
 }
beast::IP::AddressV4::AddressV4 (std::uint32_t value_) explicit
Construct from a 32-bit unsigned.
Note
Octets are formed in order from the MSB to the LSB.
Definition at line 38 of file IPAddressV4.cpp.
     : value (value_)
 {
 }
beast::IP::AddressV4::AddressV4 (std::uint8_t a, std::uint8_t b, std::uint8_t c, std::uint8_t d)
Construct from four individual octets..
Note
The resulting address is a.b.c.d
Definition at line 43 of file IPAddressV4.cpp.
     : value ((a<<24)|(b<<16)|(c<<8)|d)
 {
 }
Member Function Documentation
static AddressV4 beast::IP::AddressV4::any () inline static
Returns an address that represents 'any' address.
Definition at line 55 of file IPAddressV4.h.
References AddressV4().
         { return AddressV4(); }
static AddressV4 beast::IP::AddressV4::broadcast () inline static
Returns an address that represents the broadcast address.
Definition at line 63 of file IPAddressV4.h.
References AddressV4().
Referenced by broadcast(), is_broadcast(), and beast::IP::is_public().
         { return AddressV4 (0xffffffff); }
AddressV4 beast::IP::AddressV4::broadcast (AddressV4 const & address) static
Returns the broadcast address for the specified address.
Definition at line 58 of file IPAddressV4.cpp.
References broadcast(), and netmask().
 {
     return broadcast (address, netmask (address));
 }
AddressV4 beast::IP::AddressV4::broadcast (AddressV4 const & address, AddressV4 const & mask) static
Returns the broadcast address corresponding to the address and mask.
Definition at line 63 of file IPAddressV4.cpp.
References AddressV4(), and value.
 {
     return AddressV4 (address.value | (mask.value ^ 0xffffffff));
 }
std::pair< AddressV4, bool > beast::IP::AddressV4::from_string (std::string const & s) static
Create an address from an IPv4 address string in dotted decimal form.
Returns
A pair with the address, and bool set to true on success.
Definition at line 48 of file IPAddressV4.cpp.
Referenced by beast::IP::IPEndpoint_test::failParseV4(), and beast::IP::IPEndpoint_test::shouldParseV4().
 {
     std::stringstream is (s);
     AddressV4 addr;
     is >> addr;
     if (! is.fail() && is.rdbuf()->in_avail() == 0)
         return std::make_pair (addr, true);
     return std::make_pair (AddressV4 (), false);
 }
char beast::IP::AddressV4::get_class (AddressV4 const & address) static
Returns the address class for the given address.
Note
Class 'D' represents multicast addresses (224.*.*.*).
Definition at line 69 of file IPAddressV4.cpp.
References value.
Referenced by netmask(), and beast::IP::IPEndpoint_test::testEndpoint().
 {
     static char const* table = "AAAABBCD";
     return table [(addr.value & 0xE0000000) >> 29];
 }
bool beast::IP::AddressV4::is_broadcast () const inline
Returns true if this is a broadcast address.
Definition at line 74 of file IPAddressV4.h.
References broadcast().
         { return *this == broadcast (*this); }
static AddressV4 beast::IP::AddressV4::loopback () inline static
Returns an address that represents the loopback address.
Definition at line 59 of file IPAddressV4.h.
References AddressV4().
         { return AddressV4 (0x7f000001); }
AddressV4 beast::IP::AddressV4::netmask (char address_class) static
Returns the netmask for the address class or address.
Definition at line 75 of file IPAddressV4.cpp.
References AddressV4().
Referenced by broadcast(), and netmask().
 {
     switch (address_class)
     {
     case 'A': return AddressV4 (0xff000000);
     case 'B': return AddressV4 (0xffff0000);
     case 'C': return AddressV4 (0xffffff00);
     case 'D':
     default:
         break;
     }
     return AddressV4 (0xffffffff);
 }
AddressV4 beast::IP::AddressV4::netmask (AddressV4 const & v) static
Definition at line 89 of file IPAddressV4.cpp.
References get_class(), and netmask().
 {
     return netmask (get_class (addr));
 }
AddressV4::Proxy< true > beast::IP::AddressV4::operator[] (std::size_t index) const
Definition at line 94 of file IPAddressV4.cpp.
References value.
 {
     switch (index)
     {
     default:
         throw std::out_of_range ("bad array index");
     case 0: return Proxy <true> (24, &value);
     case 1: return Proxy <true> (16, &value);
     case 2: return Proxy <true> ( 8, &value);
     case 3: return Proxy <true> ( 0, &value);
     };
 };
AddressV4::Proxy< false > beast::IP::AddressV4::operator[] (std::size_t index)
Definition at line 107 of file IPAddressV4.cpp.
References value.
 {
     switch (index)
     {
     default:
         throw std::out_of_range ("bad array index");
     case 0: return Proxy <false> (24, &value);
     case 1: return Proxy <false> (16, &value);
     case 2: return Proxy <false> ( 8, &value);
     case 3: return Proxy <false> ( 0, &value);
     };
 };
Friends And Related Function Documentation
bool operator!= (AddressV4 const & lhs, AddressV4 const & rhs) friend
Definition at line 95 of file IPAddressV4.h.
         { return ! (lhs == rhs); }
bool operator< (AddressV4 const & lhs, AddressV4 const & rhs) friend
Definition at line 92 of file IPAddressV4.h.
         { return lhs.value < rhs.value; }
bool operator<= (AddressV4 const & lhs, AddressV4 const & rhs) friend
Definition at line 99 of file IPAddressV4.h.
         { return ! (lhs > rhs); }
bool operator== (AddressV4 const & lhs, AddressV4 const & rhs) friend
Arithmetic comparison.
Definition at line 90 of file IPAddressV4.h.
         { return lhs.value == rhs.value; }
bool operator> (AddressV4 const & lhs, AddressV4 const & rhs) friend
Definition at line 97 of file IPAddressV4.h.
         { return rhs < lhs; }
bool operator>= (AddressV4 const & lhs, AddressV4 const & rhs) friend
Definition at line 101 of file IPAddressV4.h.
         { return ! (rhs > lhs); }
Member Data Documentation
std::uint32_t beast::IP::AddressV4::value
The value as a 32 bit unsigned.
Definition at line 145 of file IPAddressV4.h.
Referenced by broadcast(), get_class(), beast::IP::hash_value(), beast::IP::is_loopback(), beast::IP::is_multicast(), beast::IP::is_private(), beast::IP::is_unspecified(), operator[](), ripple::OverlayImpl::send(), beast::IP::IPEndpoint_test::testAddressV4(), beast::IP::to_asio_address(), and beast::insight::detail::StatsDCollectorImp::to_endpoint().
The documentation for this struct was generated from the following files:
rippled/src/beast/beast/net/IPAddressV4.h
rippled/src/beast/beast/net/impl/IPAddressV4.cpp