rippled: ripple::OverlayImpl Class Reference
ripple::OverlayImpl Class Reference
#include <OverlayImpl.h>
Public Types
typedef
boost::asio::ip::tcp::socket socket_type
typedef std::unordered_map
< PeerFinder::Slot::ptr,
boost::weak_ptr< PeerImp > > PeersBySlot
typedef boost::unordered_map
< RippleAddress, Peer::ptr > PeerByPublicKey
typedef std::unordered_map
< Peer::ShortId, Peer::ptr > PeerByShortId
Public Types inherited from ripple::Overlay
typedef std::vector< Peer::ptr > PeerSequence
Public Member Functions
OverlayImpl (Stoppable &parent, Resource::Manager &resourceManager, SiteFiles::Manager &siteFiles, beast::File const &pathToDbFileOrDirectory, Resolver &resolver, boost::asio::io_service &io_service, boost::asio::ssl::context &ssl_context)
~OverlayImpl ()
OverlayImpl (OverlayImpl const &)=delete
OverlayImpl & operator= (OverlayImpl const &)=delete
void accept (bool proxyHandshake, socket_type &&socket)
void connect (beast::IP::Endpoint const &remote_endpoint)
Peer::ShortId next_id ()
void check_stopped ()
void release ()
void remove (PeerFinder::Slot::ptr const &slot)
void connect (std::vector< beast::IP::Endpoint > const &list)
void activate (PeerFinder::Slot::ptr const &slot)
void send (PeerFinder::Slot::ptr const &slot, std::vector< PeerFinder::Endpoint > const &endpoints)
void disconnect (PeerFinder::Slot::ptr const &slot, bool graceful)
void onPrepare () override
void onStart () override
void close_all (bool graceful)
void onStop () override
void onChildrenStopped () override
void onWrite (beast::PropertyStream::Map &stream)
void onPeerActivated (Peer::ptr const &peer)
void onPeerDisconnect (Peer::ptr const &peer)
std::size_t size ()
Json::Value json ()
Overlay::PeerSequence getActivePeers ()
Peer::ptr findPeerByShortID (Peer::ShortId const &id)
Public Member Functions inherited from ripple::Overlay
virtual ~Overlay ()=default
template<typename Function >
std::enable_if_t
< !std::is_void< typename
Function::return_type >::value,
typename Function::return_type > foreach (Function f)
template<class Function >
std::enable_if_t< std::is_void
< typename
Function::return_type >::value,
typename Function::return_type > foreach (Function f)
Public Member Functions inherited from beast::Stoppable
Stoppable (char const *name, Stoppable &parent)
virtual ~Stoppable ()
bool isStopping () const
bool isStopped () const
bool areChildrenStopped () const
void stopped ()
Public Member Functions inherited from beast::PropertyStream::Source
Source (std::string const &name)
~Source ()
std::string const & name () const
void add (Source &source)
template<class Derived >
Derived * add (Derived *child)
void remove (Source &child)
void removeAll ()
void write_one (PropertyStream &stream)
void write (PropertyStream &stream)
void write (PropertyStream &stream, std::string const &path)
std::pair< Source *, bool > find (std::string path)
Source * find_one_deep (std::string const &name)
PropertyStream::Source * find_path (std::string path)
PropertyStream::Source * find_one (std::string const &name)
Public Member Functions inherited from ripple::PeerFinder::Callback
virtual void send (Slot::ptr const &slot, Endpoints const &endpoints)=0
Public Attributes
std::recursive_mutex m_mutex
std::condition_variable_any m_cond
std::size_t m_child_count
beast::Journal m_journal
Resource::Manager & m_resourceManager
std::unique_ptr
< PeerFinder::Manager > m_peerFinder
boost::asio::io_service & m_io_service
boost::asio::ssl::context & m_ssl_context
PeersBySlot m_peers
PeerByPublicKey m_publicKeyMap
PeerByShortId m_shortIdMap
std::unique_ptr< PeerDoor > m_doorDirect
std::unique_ptr< PeerDoor > m_doorProxy
Resolver & m_resolver
beast::Atomic< Peer::ShortId > m_nextShortId
Additional Inherited Members
Static Public Member Functions inherited from beast::PropertyStream::Source
static bool peel_leading_slash (std::string *path)
static bool peel_trailing_slashstar (std::string *path)
static std::string peel_name (std::string *path)
Protected Member Functions inherited from ripple::Overlay
Overlay (Stoppable &parent)
Protected Attributes inherited from beast::Stoppable
char const * m_name
RootStoppable & m_root
Child m_child
Atomic< int > m_started
bool volatile m_stopped
bool volatile m_childrenStopped
Children m_children
WaitableEvent m_stoppedEvent
Detailed Description
Definition at line 46 of file OverlayImpl.h.
Member Typedef Documentation
typedef boost::unordered_map< RippleAddress, Peer::ptr> ripple::OverlayImpl::PeerByPublicKey
Definition at line 57 of file OverlayImpl.h.
typedef std::unordered_map< Peer::ShortId, Peer::ptr> ripple::OverlayImpl::PeerByShortId
Definition at line 60 of file OverlayImpl.h.
typedef std::unordered_map<PeerFinder::Slot::ptr, boost::weak_ptr <PeerImp> > ripple::OverlayImpl::PeersBySlot
Definition at line 54 of file OverlayImpl.h.
typedef boost::asio::ip::tcp::socket ripple::OverlayImpl::socket_type
Definition at line 51 of file OverlayImpl.h.
Constructor & Destructor Documentation
ripple::OverlayImpl::OverlayImpl (Stoppable & parent, Resource::Manager & resourceManager, SiteFiles::Manager & siteFiles, beast::File const & pathToDbFileOrDirectory, Resolver & resolver, boost::asio::io_service & io_service, boost::asio::ssl::context & ssl_context)
Definition at line 80 of file OverlayImpl.cpp.
     : Overlay (parent)
     , m_child_count (1)
     , m_journal (LogPartition::getJournal <PeersLog> ())
     , m_resourceManager (resourceManager)
     , m_peerFinder (add (PeerFinder::Manager::New (
         *this,
         siteFiles,
         pathToDbFileOrDirectory,
         *this,
         get_seconds_clock (),
         LogPartition::getJournal <PeerFinderLog> ())))
     , m_io_service (io_service)
     , m_ssl_context (ssl_context)
     , m_resolver (resolver)
 {
 }
ripple::OverlayImpl::~OverlayImpl ()
Definition at line 104 of file OverlayImpl.cpp.
References m_child_count, m_cond, and m_mutex.
 {
     // Block until dependent objects have been destroyed.
     // This is just to catch improper use of the Stoppable API.
     //
     std::unique_lock <decltype(m_mutex)> lock (m_mutex);
     m_cond.wait (lock, [this] {
         return this->m_child_count == 0; });
 }
ripple::OverlayImpl::OverlayImpl (OverlayImpl const &) delete
Member Function Documentation
void ripple::OverlayImpl::accept (bool proxyHandshake, socket_type && socket)
Process an incoming connection using the Peer protocol. The caller transfers ownership of the socket via rvalue move.
Parameters
proxyHandshake true If a PROXY handshake is required.
socket A socket in the accepted state.
Definition at line 115 of file OverlayImpl.cpp.
References beast::IPAddressConversion::from_asio(), m_child_count, m_mutex, m_peerFinder, m_peers, m_resourceManager, m_ssl_context, ripple::MultiSocket::Flag::proxy, ripple::MultiSocket::Flag::server_role, ripple::MultiSocket::Flag::ssl_required, and ripple::MultiSocket::Flag::with().
Referenced by ripple::PeerDoorImp::handleAccept().
 {
     // An error getting an endpoint means the connection closed.
     // Just do nothing and the socket will be closed by the caller.
     boost::system::error_code ec;
     auto const local_endpoint_native (socket.local_endpoint (ec));
     if (ec)
         return;
     auto const remote_endpoint_native (socket.remote_endpoint (ec));
     if (ec)
         return;
     auto const local_endpoint (
         beast::IPAddressConversion::from_asio (local_endpoint_native));
     auto const remote_endpoint (
         beast::IPAddressConversion::from_asio (remote_endpoint_native));
     PeerFinder::Slot::ptr const slot (m_peerFinder->new_inbound_slot (
         local_endpoint, remote_endpoint));
     if (slot == nullptr)
         return;
     MultiSocket::Flag flags (
         MultiSocket::Flag::server_role | MultiSocket::Flag::ssl_required);
     if (proxyHandshake)
         flags = flags.with (MultiSocket::Flag::proxy);
     PeerImp::ptr const peer (boost::make_shared <PeerImp> (
         std::move (socket), remote_endpoint, *this, m_resourceManager,
             *m_peerFinder, slot, m_ssl_context, flags));
     {
         std::lock_guard <decltype(m_mutex)> lock (m_mutex);
         {
             std::pair <PeersBySlot::iterator, bool> const result (
                 m_peers.emplace (slot, peer));
             assert (result.second);
         }
         ++m_child_count;
         // This has to happen while holding the lock,
         // otherwise the socket might not be canceled during a stop.
         peer->start ();
     }
 }
void ripple::OverlayImpl::activate (PeerFinder::Slot::ptr const & slot) virtual
Activate the handshaked peer with the specified address.
Implements ripple::PeerFinder::Callback.
Definition at line 262 of file OverlayImpl.cpp.
References m_journal, m_mutex, m_peers, and beast::Journal::trace.
 {
     m_journal.trace <<
         "Activate " << slot->remote_endpoint();
     std::lock_guard <decltype(m_mutex)> lock (m_mutex);
     PeersBySlot::iterator const iter (m_peers.find (slot));
     assert (iter != m_peers.end ());
     PeerImp::ptr const peer (iter->second.lock());
     assert (peer != nullptr);
     peer->activate ();
 }
void ripple::OverlayImpl::check_stopped ()
Definition at line 213 of file OverlayImpl.cpp.
References beast::Stoppable::areChildrenStopped(), beast::Journal::info, m_child_count, m_cond, m_journal, and beast::Stoppable::stopped().
Referenced by onChildrenStopped(), and release().
 {
     // To be stopped, child Stoppable objects must be stopped
     // and the count of dependent objects must be zero
     if (areChildrenStopped () && m_child_count == 0)
     {
         m_cond.notify_all ();
         m_journal.info <<
             "Stopped.";
         stopped ();
     }
 }
void ripple::OverlayImpl::close_all (bool graceful)
Close all peer connections. If graceful is true then active Requirements: Caller must hold the mutex.
Definition at line 438 of file OverlayImpl.cpp.
References m_peers.
Referenced by onStop().
 {
     for (auto const& entry : m_peers)
     {
         PeerImp::ptr const peer (entry.second.lock());
         // VFALCO The only case where the weak_ptr is expired should be if
         //        ~PeerImp is pre-empted before it calls m_peers.remove()
         //
         if (peer != nullptr)
             peer->close (graceful);
     }
 }
void ripple::OverlayImpl::connect (beast::IP::Endpoint const & remote_endpoint) virtual
Implements ripple::Overlay.
Definition at line 164 of file OverlayImpl.cpp.
References ripple::MultiSocket::Flag::client_role, beast::Journal::debug, beast::Stoppable::isStopping(), m_child_count, m_io_service, m_journal, m_mutex, m_peerFinder, m_peers, m_resourceManager, m_ssl_context, and ripple::MultiSocket::Flag::ssl.
Referenced by connect().
 {
     if (isStopping())
     {
         m_journal.debug <<
             "Skipping " << remote_endpoint <<
             " connect on stop";
         return;
     }
     PeerFinder::Slot::ptr const slot (
         m_peerFinder->new_outbound_slot (remote_endpoint));
     if (slot == nullptr)
         return;
     MultiSocket::Flag const flags (
         MultiSocket::Flag::client_role | MultiSocket::Flag::ssl);
     PeerImp::ptr const peer (boost::make_shared <PeerImp> (
         remote_endpoint, m_io_service, *this, m_resourceManager,
             *m_peerFinder, slot, m_ssl_context, flags));
     {
         std::lock_guard <decltype(m_mutex)> lock (m_mutex);
         {
             std::pair <PeersBySlot::iterator, bool> const result (
                 m_peers.emplace (slot, peer));
             assert (result.second);
         }
         ++m_child_count;
         // This has to happen while holding the lock,
         // otherwise the socket might not be canceled during a stop.
         peer->start ();
     }
 }
void ripple::OverlayImpl::connect (std::vector< beast::IP::Endpoint > const & addresses) virtual
Initiate outgoing Peer connections to the specified set of endpoints.
Implements ripple::PeerFinder::Callback.
Definition at line 254 of file OverlayImpl.cpp.
References connect().
 {
     for (std::vector <beast::IP::Endpoint>::const_iterator iter (list.begin());
         iter != list.end(); ++iter)
         connect (*iter);
 }
void ripple::OverlayImpl::disconnect (PeerFinder::Slot::ptr const & slot, bool graceful) virtual
Disconnect the handshaked peer with the specified address.
Parameters
graceful true to wait for send buffers to drain before closing.
Implements ripple::PeerFinder::Callback.
Definition at line 314 of file OverlayImpl.cpp.
References m_journal, m_mutex, m_peers, and beast::Journal::trace.
 {
     if (m_journal.trace) m_journal.trace <<
         "Disconnect " << slot->remote_endpoint () <<
         (graceful ? "gracefully" : "");
     std::lock_guard <decltype(m_mutex)> lock (m_mutex);
     PeersBySlot::iterator const iter (m_peers.find (slot));
     assert (iter != m_peers.end ());
     PeerImp::ptr const peer (iter->second.lock());
     assert (peer != nullptr);
     peer->close (graceful);
     //peer->detach ("disc", false);
 }
Peer::ptr ripple::OverlayImpl::findPeerByShortID (Peer::ShortId const & id) virtual
Implements ripple::Overlay.
Definition at line 572 of file OverlayImpl.cpp.
References m_mutex, and m_shortIdMap.
Referenced by ripple::PeerImp::recvLedger().
 {
     std::lock_guard <decltype(m_mutex)> lock (m_mutex);
     PeerByShortId::iterator const iter (
         m_shortIdMap.find (id));
     if (iter != m_shortIdMap.end ())
         return iter->second;
     return Peer::ptr();
 }
Overlay::PeerSequence ripple::OverlayImpl::getActivePeers () virtual
Implements ripple::Overlay.
Definition at line 554 of file OverlayImpl.cpp.
References m_mutex, and m_publicKeyMap.
Referenced by ripple::PeerImp::getLedger().
 {
     Overlay::PeerSequence ret;
     std::lock_guard <decltype(m_mutex)> lock (m_mutex);
     ret.reserve (m_publicKeyMap.size ());
     BOOST_FOREACH (PeerByPublicKey::value_type const& pair, m_publicKeyMap)
     {
         assert (!!pair.second);
         ret.push_back (pair.second);
     }
     return ret;
 }
Json::Value ripple::OverlayImpl::json () virtual
Implements ripple::Overlay.
Definition at line 548 of file OverlayImpl.cpp.
 {
     return foreach (get_peer_json());
 }
Peer::ShortId ripple::OverlayImpl::next_id ()
Definition at line 203 of file OverlayImpl.cpp.
References m_nextShortId.
Referenced by ripple::PeerImp::activate().
 {
     return ++m_nextShortId;
 }
void ripple::OverlayImpl::onChildrenStopped () override virtual
Override called when all children have stopped.
The call is made on an unspecified, implementation-specific thread. onStop and onChildrenStopped will never be called concurrently, across all Stoppable objects descended from the same root, inclusive of the root.
It is safe to call isStopping, isStopped, and areChildrenStopped from within this function; The values returned will always be valid and never change during the callback.
The default implementation does nothing.
Thread safety: May not block for long periods. Guaranteed only to be called once. Must be safe to call from any thread at any time.
Reimplemented from beast::Stoppable.
Definition at line 468 of file OverlayImpl.cpp.
References check_stopped(), and m_mutex.
 {
     std::lock_guard <decltype(m_mutex)> lock (m_mutex);
     check_stopped ();
 }
void ripple::OverlayImpl::onPeerActivated (Peer::ptr const & peer) virtual
A peer has connected successfully This is called after the peer handshake has been completed and during peer activation. At this point, the peer address and the public key are known.
Implements ripple::Overlay.
Definition at line 492 of file OverlayImpl.cpp.
References beast::Journal::debug, m_journal, m_mutex, m_publicKeyMap, m_shortIdMap, and size().
Referenced by ripple::PeerImp::activate().
 {
     std::lock_guard <decltype(m_mutex)> lock (m_mutex);
     // Now track this peer
     {
         auto const result (m_shortIdMap.emplace (
             std::piecewise_construct,
                 std::make_tuple (peer->getShortId()),
                     std::make_tuple (peer)));
         assert(result.second);
     }
     {
         auto const result (m_publicKeyMap.emplace (
             boost::unordered::piecewise_construct,
                 boost::make_tuple (peer->getNodePublic()),
                     boost::make_tuple (peer)));
         assert(result.second);
     }
     m_journal.debug <<
         "activated " << peer->getRemoteAddress() <<
         " (" << peer->getShortId() <<
         ":" << RipplePublicKey(peer->getNodePublic()) << ")";
     // We just accepted this peer so we have non-zero active peers
     assert(size() != 0);
 }
void ripple::OverlayImpl::onPeerDisconnect (Peer::ptr const & peer) virtual
A peer is being disconnected This is called during the disconnection of a known, activated peer. It will not be called for outbound peer connections that don't succeed or for connections of peers that are dropped prior to being activated.
Implements ripple::Overlay.
Definition at line 528 of file OverlayImpl.cpp.
References m_mutex, m_publicKeyMap, and m_shortIdMap.
Referenced by ripple::PeerImp::detach().
 {
     std::lock_guard <decltype(m_mutex)> lock (m_mutex);
     m_shortIdMap.erase (peer->getShortId ());
     m_publicKeyMap.erase (peer->getNodePublic ());
 }
void ripple::OverlayImpl::onPrepare () override virtual
Override called during preparation. Since all other Stoppable objects in the tree have already been constructed, this provides an opportunity to perform initialization which depends on calling into other Stoppable objects. This call is made on the same thread that called prepare(). The default implementation does nothing. Guaranteed to only be called once.
Reimplemented from beast::Stoppable.
Definition at line 337 of file OverlayImpl.cpp.
References ripple::PeerFinder::Config::applyTuning(), ripple::PeerFinder::Config::autoConnect, base, ripple::PeerFinder::Config::calcOutPeers(), ripple::PeerFinder::Config::features, ripple::getConfig(), ripple::Config::IPS_FIXED, ripple::PeerFinder::Config::listeningPort, m_doorDirect, m_doorProxy, m_io_service, m_peerFinder, m_resolver, ripple::make_PeerDoor(), ripple::PeerFinder::Config::maxPeers, beast::PropertyStream::Source::name(), ripple::PeerFinder::Config::outPeers, ripple::Config::PEER_PRIVATE, ripple::Config::peerListeningPort, ripple::Config::PEERS_MAX, ripple::Resolver::resolve(), ripple::Config::RUN_STANDALONE, ripple::PeerDoor::sslAndPROXYRequired, ripple::PeerDoor::sslRequired, ripple::to_string(), and ripple::PeerFinder::Config::wantIncoming.
 {
     PeerFinder::Config config;
     if (getConfig ().PEERS_MAX != 0)
         config.maxPeers = getConfig ().PEERS_MAX;
     config.outPeers = config.calcOutPeers();
     config.wantIncoming =
         (! getConfig ().PEER_PRIVATE) &&
         (getConfig().peerListeningPort != 0);
     // if it's a private peer or we are running as standalone
     // automatic connections would defeat the purpose.
     config.autoConnect =
         !getConfig().RUN_STANDALONE &&
         !getConfig().PEER_PRIVATE;
     config.listeningPort = getConfig().peerListeningPort;
     config.features = "";
     // Enforce business rules
     config.applyTuning ();
     m_peerFinder->setConfig (config);
     auto bootstrapIps (getConfig ().IPS);
     // If no IPs are specified, use the Ripple Labs round robin
     // pool to get some servers to insert into the boot cache.
     if (bootstrapIps.empty ())
         bootstrapIps.push_back ("r.ripple.com 51235");
     if (!bootstrapIps.empty ())
     {
         m_resolver.resolve (bootstrapIps,
             [this](
                 std::string const& name,
                 std::vector <beast::IP::Endpoint> const& addresses)
             {
                 std::vector <std::string> ips;
                 for (auto const& addr : addresses)
                     ips.push_back (to_string (addr));
                 std::string const base ("config: ");
                 if (!ips.empty ())
                     m_peerFinder->addFallbackStrings (base + name, ips);
             });
     }
     // Add the ips_fixed from the rippled.cfg file
     if (! getConfig ().RUN_STANDALONE && !getConfig ().IPS_FIXED.empty ())
     {
         m_resolver.resolve (getConfig ().IPS_FIXED,
             [this](
                 std::string const& name,
                 std::vector <beast::IP::Endpoint> const& addresses)
             {
                 if (!addresses.empty ())
                     m_peerFinder->addFixedPeer (name, addresses);
             });
     }
     // Configure the peer doors, which allow the server to accept incoming
     // peer connections:
     if (! getConfig ().RUN_STANDALONE)
     {
         m_doorDirect = make_PeerDoor (
             PeerDoor::sslRequired,
             *this,
             getConfig ().PEER_IP,
             getConfig ().peerListeningPort,
             m_io_service);
         if (getConfig ().peerPROXYListeningPort != 0)
         {
             m_doorProxy = make_PeerDoor (
                 PeerDoor::sslAndPROXYRequired,
                 *this,
                 getConfig ().PEER_IP,
                 getConfig ().peerPROXYListeningPort,
                 m_io_service);
         }
     }
 }
void ripple::OverlayImpl::onStart () override virtual
Override called during start.
Reimplemented from beast::Stoppable.
Definition at line 428 of file OverlayImpl.cpp.
 {
 }
void ripple::OverlayImpl::onStop () override virtual
Override called when the stop notification is issued.
The call is made on an unspecified, implementation-specific thread. onStop and onChildrenStopped will never be called concurrently, across all Stoppable objects descended from the same root, inclusive of the root.
It is safe to call isStopping, isStopped, and areChildrenStopped from within this function; The values returned will always be valid and never change during the callback.
The default implementation simply calls stopped(). This is applicable when the Stoppable has a trivial stop operation (or no stop operation), and we are merely using the Stoppable API to position it as a dependency of some parent service.
Thread safety: May not block for long periods. Guaranteed only to be called once. Must be safe to call from any thread at any time.
Reimplemented from beast::Stoppable.
Definition at line 453 of file OverlayImpl.cpp.
References close_all(), m_doorDirect, m_doorProxy, m_mutex, and release().
 {
     if (m_doorDirect)
         m_doorDirect->stop();
     if (m_doorProxy)
         m_doorProxy->stop();
     std::lock_guard <decltype(m_mutex)> lock (m_mutex);
     // Take off the extra count we added in the constructor
     release();
     close_all (false);
 }
void ripple::OverlayImpl::onWrite (beast::PropertyStream::Map &) virtual
Subclass override. The default version does nothing.
Reimplemented from beast::PropertyStream::Source.
Definition at line 481 of file OverlayImpl.cpp.
 {
 }
OverlayImpl& ripple::OverlayImpl::operator= (OverlayImpl const &) delete
void ripple::OverlayImpl::release ()
Definition at line 229 of file OverlayImpl.cpp.
References check_stopped(), and m_child_count.
Referenced by onStop(), and remove().
 {
     if (--m_child_count == 0)
         check_stopped ();
 }
void ripple::OverlayImpl::remove (PeerFinder::Slot::ptr const & slot) virtual
Implements ripple::Overlay.
Definition at line 236 of file OverlayImpl.cpp.
References m_mutex, m_peers, and release().
Referenced by ripple::PeerImp::~PeerImp().
 {
     std::lock_guard <decltype(m_mutex)> lock (m_mutex);
     PeersBySlot::iterator const iter (m_peers.find (slot));
     assert (iter != m_peers.end ());
     m_peers.erase (iter);
     release();
 }
void ripple::OverlayImpl::send (PeerFinder::Slot::ptr const & slot, std::vector< PeerFinder::Endpoint > const & endpoints)
Definition at line 277 of file OverlayImpl.cpp.
References ripple::PeerFinder::Endpoint::address, ripple::PeerFinder::Endpoint::hops, beast::IP::Endpoint::is_v4(), m_mutex, m_peers, beast::IP::Endpoint::port(), beast::IP::Endpoint::to_v4(), beast::toNetworkByteOrder(), and beast::IP::AddressV4::value.
 {
     typedef std::vector <PeerFinder::Endpoint> List;
     protocol::TMEndpoints tm;
     for (List::const_iterator iter (endpoints.begin());
         iter != endpoints.end(); ++iter)
     {
         PeerFinder::Endpoint const& ep (*iter);
         protocol::TMEndpoint& tme (*tm.add_endpoints());
         if (ep.address.is_v4())
             tme.mutable_ipv4()->set_ipv4(
                 beast::toNetworkByteOrder (ep.address.to_v4().value));
         else
             tme.mutable_ipv4()->set_ipv4(0);
         tme.mutable_ipv4()->set_ipv4port (ep.address.port());
         tme.set_hops (ep.hops);
     }
     tm.set_version (1);
     Message::pointer msg (
         boost::make_shared <Message> (
             tm, protocol::mtENDPOINTS));
     {
         std::lock_guard <decltype(m_mutex)> lock (m_mutex);
         PeersBySlot::iterator const iter (m_peers.find (slot));
         assert (iter != m_peers.end ());
         PeerImp::ptr const peer (iter->second.lock());
         assert (peer != nullptr);
         peer->sendPacket (msg, false);
     }
 }
std::size_t ripple::OverlayImpl::size () virtual
The number of active peers on the network Active peers are only those peers that have completed the handshake and are running the Ripple protocol.
Implements ripple::Overlay.
Definition at line 540 of file OverlayImpl.cpp.
References m_mutex, and m_publicKeyMap.
Referenced by onPeerActivated().
 {
     std::lock_guard <decltype(m_mutex)> lock (m_mutex);
     return m_publicKeyMap.size ();
 }
Member Data Documentation
std::size_t ripple::OverlayImpl::m_child_count
Definition at line 68 of file OverlayImpl.h.
Referenced by accept(), check_stopped(), connect(), release(), and ~OverlayImpl().
std::condition_variable_any ripple::OverlayImpl::m_cond
Definition at line 65 of file OverlayImpl.h.
Referenced by check_stopped(), and ~OverlayImpl().
std::unique_ptr<PeerDoor> ripple::OverlayImpl::m_doorDirect
The peer door for regular SSL connections
Definition at line 88 of file OverlayImpl.h.
Referenced by onPrepare(), and onStop().
std::unique_ptr<PeerDoor> ripple::OverlayImpl::m_doorProxy
The peer door for proxy connections
Definition at line 91 of file OverlayImpl.h.
Referenced by onPrepare(), and onStop().
boost::asio::io_service& ripple::OverlayImpl::m_io_service
Definition at line 75 of file OverlayImpl.h.
Referenced by connect(), and onPrepare().
beast::Journal ripple::OverlayImpl::m_journal
Definition at line 70 of file OverlayImpl.h.
Referenced by activate(), check_stopped(), connect(), disconnect(), and onPeerActivated().
std::recursive_mutex ripple::OverlayImpl::m_mutex
Definition at line 62 of file OverlayImpl.h.
Referenced by accept(), activate(), connect(), disconnect(), findPeerByShortID(), getActivePeers(), onChildrenStopped(), onPeerActivated(), onPeerDisconnect(), onStop(), remove(), send(), size(), and ~OverlayImpl().
beast::Atomic<Peer::ShortId> ripple::OverlayImpl::m_nextShortId
Monotically increasing identifiers for peers
Definition at line 97 of file OverlayImpl.h.
Referenced by next_id().
std::unique_ptr<PeerFinder::Manager> ripple::OverlayImpl::m_peerFinder
Definition at line 73 of file OverlayImpl.h.
Referenced by accept(), connect(), and onPrepare().
PeersBySlot ripple::OverlayImpl::m_peers
Associates slots to peers.
Definition at line 79 of file OverlayImpl.h.
Referenced by accept(), activate(), close_all(), connect(), disconnect(), remove(), and send().
PeerByPublicKey ripple::OverlayImpl::m_publicKeyMap
Tracks peers by their public key
Definition at line 82 of file OverlayImpl.h.
Referenced by getActivePeers(), onPeerActivated(), onPeerDisconnect(), and size().
Resolver& ripple::OverlayImpl::m_resolver
The resolver we use for peer hostnames
Definition at line 94 of file OverlayImpl.h.
Referenced by onPrepare().
Resource::Manager& ripple::OverlayImpl::m_resourceManager
Definition at line 71 of file OverlayImpl.h.
Referenced by accept(), and connect().
PeerByShortId ripple::OverlayImpl::m_shortIdMap
Tracks peers by their session ID
Definition at line 85 of file OverlayImpl.h.
Referenced by findPeerByShortID(), onPeerActivated(), and onPeerDisconnect().
boost::asio::ssl::context& ripple::OverlayImpl::m_ssl_context
Definition at line 76 of file OverlayImpl.h.
Referenced by accept(), and connect().
The documentation for this class was generated from the following files:
rippled/src/ripple_overlay/impl/OverlayImpl.h
rippled/src/ripple_overlay/impl/OverlayImpl.cpp