rippled: beast::asio::bind_handler_test Class Reference
beast::asio::bind_handler_test Class Reference
Public Member Functions
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Static Public Member Functions
static void foo (int)
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 35 of file bind_handler.test.cpp.
Member Function Documentation
static void beast::asio::bind_handler_test::foo (int) inline static
Definition at line 38 of file bind_handler.test.cpp.
Referenced by run().
     {
     }
void beast::asio::bind_handler_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 42 of file bind_handler.test.cpp.
References beast::asio::bind_handler(), ripple::f, foo(), and beast::unit_test::suite::pass().
     {
         auto f (bind_handler (
             std::bind (&foo, std::placeholders::_1),
             42));
         f();
         pass();
     }
The documentation for this class was generated from the following file:
rippled/src/beast/beast/asio/tests/bind_handler.test.cpp