rippled: beast::AtExitHook Class Reference
beast::AtExitHook Class Reference abstract
#include <AtExitHook.h>
Classes
class Item
class Manager
Protected Member Functions
AtExitHook ()
virtual ~AtExitHook ()
virtual void onExit ()=0
Private Attributes
Item m_item
Detailed Description
Hook for performing activity on program exit.
These hooks execute when objects with static storage duration are destroyed. The hooks are called in the reverse order that they were created.
To use, derive your class from AtExitHook and implement onExit. Alternatively, add AtExitMemberHook as a data member of your class and then provide your own onExit function with this signature:
void onExit ()
See Also
AtExitMemberHook
Definition at line 46 of file AtExitHook.h.
Constructor & Destructor Documentation
beast::AtExitHook::AtExitHook () protected
Definition at line 119 of file AtExitHook.cpp.
References beast::AtExitHook::Manager::get(), beast::AtExitHook::Manager::insert(), and m_item.
     : m_item (this)
 {
 #if BEAST_IOS
     // Patrick Dehne:
     //      AtExitHook::Manager::insert crashes on iOS
     //      if the storage is not accessed before it is used.
     //
     // VFALCO TODO Figure out why and fix it cleanly if needed.
     //
     char* hack = AtExitHook::Manager::s_list.s_storage;
 #endif
     Manager::get().insert (m_item);
 }
beast::AtExitHook::~AtExitHook () protected virtual
Definition at line 135 of file AtExitHook.cpp.
References beast::AtExitHook::Manager::erase(), beast::AtExitHook::Manager::get(), and m_item.
 {
     Manager::get().erase (m_item);
 }
Member Function Documentation
virtual void beast::AtExitHook::onExit () protected pure virtual
Called at program exit.
Implemented in beast::AtExitMemberHook< Object >, and beast::AtExitMemberHook< beast::SharedSingleton >.
Referenced by beast::AtExitHook::Manager::doStaticDetruction().
Member Data Documentation
Item beast::AtExitHook::m_item private
Definition at line 69 of file AtExitHook.h.
Referenced by AtExitHook(), and ~AtExitHook().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_core/time/AtExitHook.h
rippled/src/beast/modules/beast_core/time/AtExitHook.cpp