rippled: beast::MemoryOutputStream Class Reference
beast::MemoryOutputStream Class Reference
#include <MemoryOutputStream.h>
Public Member Functions
MemoryOutputStream (size_t initialSize=256)
MemoryOutputStream (MemoryBlock &memoryBlockToWriteTo, bool appendToExistingBlockContent)
MemoryOutputStream (void *destBuffer, size_t destBufferSize)
~MemoryOutputStream ()
const void * getData () const noexcept
size_t getDataSize () const noexcept
void reset () noexcept
void preallocate (size_t bytesToPreallocate)
bool appendUTF8Char (beast_wchar character)
String toUTF8 () const
String toString () const
MemoryBlock getMemoryBlock () const
void flush ()
bool write (const void *, size_t) override
std::int64_t getPosition () override
bool setPosition (std::int64_t) override
int writeFromInputStream (InputStream &, std::int64_t maxNumBytesToWrite) override
bool writeRepeatedByte (std::uint8_t byte, size_t numTimesToRepeat) override
Public Member Functions inherited from beast::OutputStream
virtual ~OutputStream ()
virtual bool writeByte (char byte)
virtual bool writeBool (bool boolValue)
virtual bool writeShort (short value)
virtual bool writeShortBigEndian (short value)
virtual bool writeInt32 (std::int32_t value)
virtual bool writeInt (int value)
virtual bool writeInt32BigEndian (std::int32_t value)
virtual bool writeIntBigEndian (int value)
virtual bool writeInt64 (std::int64_t value)
virtual bool writeInt64BigEndian (std::int64_t value)
virtual bool writeFloat (float value)
virtual bool writeFloatBigEndian (float value)
virtual bool writeDouble (double value)
virtual bool writeDoubleBigEndian (double value)
template<class T >
bool writeType (T value)
template<class T >
bool writeTypeBigEndian (T value)
virtual bool writeCompressedInt (int value)
virtual bool writeString (const String &text)
virtual bool writeText (const String &text, bool asUTF16, bool writeUTF16ByteOrderMark)
void setNewLineString (const String &newLineString)
const String & getNewLineString () const noexcept
template<>
bool writeType (char v)
template<>
bool writeType (short v)
template<>
bool writeType (unsigned char v)
template<>
bool writeType (unsigned short v)
template<>
bool writeType (float v)
template<>
bool writeType (double v)
template<>
bool writeTypeBigEndian (char v)
template<>
bool writeTypeBigEndian (short v)
template<>
bool writeTypeBigEndian (unsigned char v)
template<>
bool writeTypeBigEndian (unsigned short v)
template<>
bool writeTypeBigEndian (float v)
template<>
bool writeTypeBigEndian (double v)
Private Member Functions
void trimExternalBlockSize ()
char * prepareToWrite (size_t)
Private Attributes
MemoryBlock *const blockToUse
MemoryBlock internalBlock
void * externalData
size_t position
size_t size
size_t availableSize
Additional Inherited Members
Protected Member Functions inherited from beast::OutputStream
OutputStream ()
Detailed Description
Writes data to an internal memory buffer, which grows as required.
The data that was written into the stream can then be accessed later as a contiguous block of memory. Writes data to an internal memory buffer, which grows as required.
The data that was written into the stream can then be accessed later as a contiguous block of memory.
Definition at line 44 of file MemoryOutputStream.h.
Constructor & Destructor Documentation
beast::MemoryOutputStream::MemoryOutputStream (size_t initialSize = 256)
Creates an empty memory stream, ready to be written into.
Parameters
initialSize the intial amount of capacity to allocate for writing into
Definition at line 27 of file MemoryOutputStream.cpp.
References internalBlock, and beast::MemoryBlock::setSize().
   : blockToUse (&internalBlock), externalData (nullptr),
     position (0), size (0), availableSize (0)
 {
     internalBlock.setSize (initialSize, false);
 }
beast::MemoryOutputStream::MemoryOutputStream (MemoryBlock & memoryBlockToWriteTo, bool appendToExistingBlockContent)
Creates a memory stream for writing into into a pre-existing MemoryBlock object.
Note that the destination block will always be larger than the amount of data that has been written to the stream, because the MemoryOutputStream keeps some spare capactity at its end. To trim the block's size down to fit the actual data, call flush(), or delete the MemoryOutputStream.
Parameters
memoryBlockToWriteTo the block into which new data will be written.
appendToExistingBlockContent if this is true, the contents of the block will be kept, and new data will be appended to it. If false, the block will be cleared before use
Definition at line 34 of file MemoryOutputStream.cpp.
References beast::MemoryBlock::getSize(), position, and size.
   : blockToUse (&memoryBlockToWriteTo), externalData (nullptr),
     position (0), size (0), availableSize (0)
 {
     if (appendToExistingBlockContent)
         position = size = memoryBlockToWriteTo.getSize();
 }
beast::MemoryOutputStream::MemoryOutputStream (void * destBuffer, size_t destBufferSize)
Creates a MemoryOutputStream that will write into a user-supplied, fixed-size block of memory.
When using this mode, the stream will write directly into this memory area until it's full, at which point write operations will fail.
Definition at line 43 of file MemoryOutputStream.cpp.
References bassert, and externalData.
   : blockToUse (nullptr), externalData (destBuffer),
     position (0), size (0), availableSize (destBufferSize)
 {
     bassert (externalData != nullptr); // This must be a valid pointer.
 }
beast::MemoryOutputStream::~MemoryOutputStream ()
Destructor. This will free any data that was written to it.
Definition at line 50 of file MemoryOutputStream.cpp.
References trimExternalBlockSize().
 {
     trimExternalBlockSize();
 }
Member Function Documentation
bool beast::MemoryOutputStream::appendUTF8Char (beast_wchar character)
Appends the utf-8 bytes for a unicode character
Definition at line 136 of file MemoryOutputStream.cpp.
References beast::CharPointer_UTF8::getBytesRequiredFor(), prepareToWrite(), and beast::CharPointer_UTF8::write().
 {
     if (char* dest = prepareToWrite (CharPointer_UTF8::getBytesRequiredFor (c)))
     {
         CharPointer_UTF8 (dest).write (c);
         return true;
     }
     return false;
 }
void beast::MemoryOutputStream::flush () virtual
If the stream is writing to a user-supplied MemoryBlock, this will trim any excess capacity off the block, so that its length matches the amount of actual data that has been written so far.
Implements beast::OutputStream.
Definition at line 55 of file MemoryOutputStream.cpp.
References trimExternalBlockSize().
 {
     trimExternalBlockSize();
 }
const void * beast::MemoryOutputStream::getData () const noexcept
Returns a pointer to the data that has been written to the stream.
See Also
getDataSize
Definition at line 152 of file MemoryOutputStream.cpp.
References blockToUse, externalData, beast::MemoryBlock::getData(), beast::MemoryBlock::getSize(), and size.
Referenced by getMemoryBlock(), beast::operator<<(), toString(), and toUTF8().
 {
     if (blockToUse == nullptr)
         return externalData;
     if (blockToUse->getSize() > size)
         static_cast <char*> (blockToUse->getData()) [size] = 0;
     return blockToUse->getData();
 }
size_t beast::MemoryOutputStream::getDataSize () const inline noexcept
Returns the number of bytes of data that have been written to the stream.
See Also
getData
Definition at line 92 of file MemoryOutputStream.h.
References size.
Referenced by getMemoryBlock(), beast::operator<<(), toString(), and toUTF8().
 { return size; }
MemoryBlock beast::MemoryOutputStream::getMemoryBlock () const
Returns a copy of the stream's data as a memory block.
Definition at line 147 of file MemoryOutputStream.cpp.
References getData(), and getDataSize().
 {
     return MemoryBlock (getData(), getDataSize());
 }
std::int64_t beast::MemoryOutputStream::getPosition () inline override virtual
Returns the stream's current position.
See Also
setPosition
Implements beast::OutputStream.
Definition at line 124 of file MemoryOutputStream.h.
References position.
 { return position; }
void beast::MemoryOutputStream::preallocate (size_t bytesToPreallocate)
Increases the internal storage capacity to be able to contain at least the specified amount of data without needing to be resized.
Definition at line 66 of file MemoryOutputStream.cpp.
References blockToUse, and beast::MemoryBlock::ensureSize().
Referenced by writeFromInputStream().
 {
     if (blockToUse != nullptr)
         blockToUse->ensureSize (bytesToPreallocate + 1);
 }
char * beast::MemoryOutputStream::prepareToWrite (size_t numBytes) private
Definition at line 78 of file MemoryOutputStream.cpp.
References availableSize, bassert, blockToUse, beast::bmax(), beast::bmin(), beast::MemoryBlock::ensureSize(), externalData, beast::MemoryBlock::getData(), beast::MemoryBlock::getSize(), position, and size.
Referenced by appendUTF8Char(), write(), and writeRepeatedByte().
 {
     bassert ((std::ptrdiff_t) numBytes >= 0);
     size_t storageNeeded = position + numBytes;
     char* data;
     if (blockToUse != nullptr)
     {
         if (storageNeeded >= blockToUse->getSize())
             blockToUse->ensureSize ((storageNeeded + bmin (storageNeeded / 2, (size_t) (1024 * 1024)) + 32) & ~31u);
         data = static_cast <char*> (blockToUse->getData());
     }
     else
     {
         if (storageNeeded > availableSize)
             return nullptr;
         data = static_cast <char*> (externalData);
     }
     char* const writePointer = data + position;
     position += numBytes;
     size = bmax (size, position);
     return writePointer;
 }
void beast::MemoryOutputStream::reset () noexcept
Resets the stream, clearing any data that has been written to it so far.
Definition at line 72 of file MemoryOutputStream.cpp.
References position, and size.
 {
     position = 0;
     size = 0;
 }
bool beast::MemoryOutputStream::setPosition (std::int64_t newPosition) override virtual
Tries to move the stream's output position.
Not all streams will be able to seek to a new position - this will return false if it fails to work.
See Also
getPosition
Implements beast::OutputStream.
Definition at line 163 of file MemoryOutputStream.cpp.
References beast::blimit(), position, and size.
 {
     if (newPosition <= (std::int64_t) size)
     {
         // ok to seek backwards
         position = blimit ((size_t) 0, size, (size_t) newPosition);
         return true;
     }
     // can't move beyond the end of the stream..
     return false;
 }
String beast::MemoryOutputStream::toString () const
Attempts to detect the encoding of the data and convert it to a string.
See Also
String::createStringFromData
Definition at line 199 of file MemoryOutputStream.cpp.
References beast::String::createStringFromData(), getData(), and getDataSize().
Referenced by beast::InputStream::readEntireStreamAsString().
 {
     return String::createStringFromData (getData(), (int) getDataSize());
 }
String beast::MemoryOutputStream::toUTF8 () const
Returns a String created from the (UTF8) data that has been written to the stream.
Definition at line 193 of file MemoryOutputStream.cpp.
References getData(), and getDataSize().
 {
     const char* const d = static_cast <const char*> (getData());
     return String (CharPointer_UTF8 (d), CharPointer_UTF8 (d + getDataSize()));
 }
void beast::MemoryOutputStream::trimExternalBlockSize () private
Definition at line 60 of file MemoryOutputStream.cpp.
References blockToUse, internalBlock, beast::MemoryBlock::setSize(), and size.
Referenced by flush(), and ~MemoryOutputStream().
 {
     if (blockToUse != &internalBlock && blockToUse != nullptr)
         blockToUse->setSize (size, false);
 }
bool beast::MemoryOutputStream::write (const void * dataToWrite, size_t numberOfBytes) override virtual
Writes a block of data to the stream.
When creating a subclass of OutputStream, this is the only write method that needs to be overloaded - the base class has methods for writing other types of data which use this to do the work.
Parameters
dataToWrite the target buffer to receive the data. This must not be null.
numberOfBytes the number of bytes to write.
Returns
false if the write operation fails for some reason
Implements beast::OutputStream.
Definition at line 106 of file MemoryOutputStream.cpp.
References bassert, and prepareToWrite().
 {
     bassert (buffer != nullptr);
     if (howMany == 0)
         return true;
     if (char* dest = prepareToWrite (howMany))
     {
         memcpy (dest, buffer, howMany);
         return true;
     }
     return false;
 }
int beast::MemoryOutputStream::writeFromInputStream (InputStream & source, std::int64_t maxNumBytesToWrite) override virtual
Reads data from an input stream and writes it to this stream.
Parameters
source the stream to read from
maxNumBytesToWrite the number of bytes to read from the stream (if this is less than zero, it will keep reading until the input is exhausted)
Returns
the number of bytes written
Reimplemented from beast::OutputStream.
Definition at line 176 of file MemoryOutputStream.cpp.
References blockToUse, beast::InputStream::getPosition(), beast::MemoryBlock::getSize(), beast::InputStream::getTotalLength(), preallocate(), and beast::OutputStream::writeFromInputStream().
Referenced by beast::InputStream::readIntoMemoryBlock().
 {
     // before writing from an input, see if we can preallocate to make it more efficient..
     std::int64_t availableData = source.getTotalLength() - source.getPosition();
     if (availableData > 0)
     {
         if (maxNumBytesToWrite > availableData)
             maxNumBytesToWrite = availableData;
         if (blockToUse != nullptr)
             preallocate (blockToUse->getSize() + (size_t) maxNumBytesToWrite);
     }
     return OutputStream::writeFromInputStream (source, maxNumBytesToWrite);
 }
bool beast::MemoryOutputStream::writeRepeatedByte (std::uint8_t byte, size_t numTimesToRepeat) override virtual
Writes a byte to the output stream a given number of times.
Returns
false if the write operation fails for some reason
Reimplemented from beast::OutputStream.
Definition at line 122 of file MemoryOutputStream.cpp.
References prepareToWrite().
 {
     if (howMany == 0)
         return true;
     if (char* dest = prepareToWrite (howMany))
     {
         memset (dest, byte, howMany);
         return true;
     }
     return false;
 }
Member Data Documentation
size_t beast::MemoryOutputStream::availableSize private
Definition at line 137 of file MemoryOutputStream.h.
Referenced by prepareToWrite().
MemoryBlock* const beast::MemoryOutputStream::blockToUse private
Definition at line 134 of file MemoryOutputStream.h.
Referenced by getData(), preallocate(), prepareToWrite(), trimExternalBlockSize(), and writeFromInputStream().
void* beast::MemoryOutputStream::externalData private
Definition at line 136 of file MemoryOutputStream.h.
Referenced by getData(), MemoryOutputStream(), and prepareToWrite().
MemoryBlock beast::MemoryOutputStream::internalBlock private
Definition at line 135 of file MemoryOutputStream.h.
Referenced by MemoryOutputStream(), and trimExternalBlockSize().
size_t beast::MemoryOutputStream::position private
Definition at line 137 of file MemoryOutputStream.h.
Referenced by getPosition(), MemoryOutputStream(), prepareToWrite(), reset(), and setPosition().
size_t beast::MemoryOutputStream::size private
Definition at line 137 of file MemoryOutputStream.h.
Referenced by getData(), getDataSize(), MemoryOutputStream(), prepareToWrite(), reset(), setPosition(), and trimExternalBlockSize().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_core/streams/MemoryOutputStream.h
rippled/src/beast/modules/beast_core/streams/MemoryOutputStream.cpp