rippled: beast::sqdb::detail::ref_counted_prepare_info Class Reference
beast::sqdb::detail::ref_counted_prepare_info Class Reference
#include <ref_counted_prepare_info.h>
Public Member Functions
ref_counted_prepare_info (session &s)
void exchange (into_type_ptr const &i)
void exchange (use_type_ptr const &u)
virtual void final_action ()
std::string get_query () const
Public Member Functions inherited from beast::sqdb::detail::ref_counted_statement_base
ref_counted_statement_base (session &s)
virtual ~ref_counted_statement_base ()
void addref ()
void release ()
template<typename T >
void accumulate (T const &t)
std::ostringstream & get_query_stream ()
Public Attributes
std::vector< into_type_base * > m_intos
std::vector< use_type_base * > m_uses
Public Attributes inherited from beast::sqdb::detail::ref_counted_statement_base
Error * m_perror
int m_refs
session & m_session
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
Definition at line 70 of file ref_counted_prepare_info.h.
Constructor & Destructor Documentation
beast::sqdb::detail::ref_counted_prepare_info::ref_counted_prepare_info (session & s)
Definition at line 64 of file ref_counted_prepare_info.cpp.
     : ref_counted_statement_base(s)
 {
 }
Member Function Documentation
void beast::sqdb::detail::ref_counted_prepare_info::exchange (into_type_ptr const & i)
Definition at line 69 of file ref_counted_prepare_info.cpp.
References beast::sqdb::detail::type_ptr< T >::get(), m_intos, and beast::sqdb::detail::type_ptr< T >::release().
Referenced by beast::sqdb::detail::prepare_temp_type::operator,().
 {
     m_intos.push_back(i.get());
     i.release();
 }
void beast::sqdb::detail::ref_counted_prepare_info::exchange (use_type_ptr const & u)
Definition at line 75 of file ref_counted_prepare_info.cpp.
References beast::sqdb::detail::type_ptr< T >::get(), m_uses, and beast::sqdb::detail::type_ptr< T >::release().
 {
     m_uses.push_back(u.get());
     u.release();
 }
void beast::sqdb::detail::ref_counted_prepare_info::final_action () virtual
Implements beast::sqdb::detail::ref_counted_statement_base.
Definition at line 81 of file ref_counted_prepare_info.cpp.
References m_intos, and m_uses.
 {
     for (std::size_t i = m_intos.size(); i > 0; --i)
     {
         delete m_intos[i - 1];
         m_intos.resize(i - 1);
     }
     for (std::size_t i = m_uses.size(); i > 0; --i)
     {
         delete m_uses[i - 1];
         m_uses.resize(i - 1);
     }
 }
std::string beast::sqdb::detail::ref_counted_prepare_info::get_query () const
Definition at line 96 of file ref_counted_prepare_info.cpp.
References beast::sqdb::session::get_query_stream(), and beast::sqdb::detail::ref_counted_statement_base::m_session.
Referenced by beast::sqdb::detail::statement_imp::statement_imp().
 {
     return m_session.get_query_stream().str();
 }
Member Data Documentation
std::vector<into_type_base*> beast::sqdb::detail::ref_counted_prepare_info::m_intos
Definition at line 81 of file ref_counted_prepare_info.h.
Referenced by exchange(), final_action(), and beast::sqdb::detail::statement_imp::statement_imp().
std::vector<use_type_base*> beast::sqdb::detail::ref_counted_prepare_info::m_uses
Definition at line 82 of file ref_counted_prepare_info.h.
Referenced by exchange(), final_action(), and beast::sqdb::detail::statement_imp::statement_imp().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_sqdb/detail/ref_counted_prepare_info.h
rippled/src/beast/modules/beast_sqdb/source/ref_counted_prepare_info.cpp