rippled: ripple::SqliteBackend Class Reference
ripple::SqliteBackend Class Reference
Public Member Functions
SqliteBackend (std::string const &path)
~SqliteBackend ()
std::string getName ()
NodeStore::Status fetch (void const *key, NodeObject::Ptr *pObject)
void store (NodeObject::ref object)
void storeBatch (NodeStore::Batch const &batch)
void visitAll (NodeStore::VisitCallback &callback)
int getWriteLoad ()
void doBind (SqliteStatement &statement, NodeObject::ref object)
NodeObjectType getTypeFromString (std::string const &s)
Public Member Functions inherited from ripple::NodeStore::Backend
virtual ~Backend ()=0
virtual void store (NodeObject::Ptr const &object)=0
Private Attributes
std::string const m_name
std::unique_ptr< DatabaseCon > m_db
Detailed Description
Definition at line 48 of file SqliteFactory.cpp.
Constructor & Destructor Documentation
ripple::SqliteBackend::SqliteBackend (std::string const & path) inline explicit
Definition at line 51 of file SqliteFactory.cpp.
References ripple::getConfig(), m_db, ripple::siHashNodeDBCache, and beast::String::toStdString().
         : m_name (path)
         , m_db (new DatabaseCon(path, s_nodeStoreDBInit, s_nodeStoreDBCount))
     {
         beast::String s;
         // VFALCO TODO Remove this dependency on theConfig
         //
         s << "PRAGMA cache_size=-" << beast::String (getConfig ().getSize(siHashNodeDBCache) * 1024);
         m_db->getDB()->executeSQL (s.toStdString ().c_str ());
     }
ripple::SqliteBackend::~SqliteBackend () inline
Definition at line 63 of file SqliteFactory.cpp.
     {
     }
Member Function Documentation
void ripple::SqliteBackend::doBind (SqliteStatement & statement, NodeObject::ref object) inline
Definition at line 183 of file SqliteFactory.cpp.
References ripple::SqliteStatement::bind(), ripple::SqliteStatement::bindStatic(), ripple::hotACCOUNT_NODE, ripple::hotLEDGER, ripple::hotTRANSACTION, and ripple::hotTRANSACTION_NODE.
Referenced by storeBatch().
     {
         char const* type;
         switch (object->getType())
         {
             case hotLEDGER:             type = "L"; break;
             case hotTRANSACTION:        type = "T"; break;
             case hotACCOUNT_NODE:       type = "A"; break;
             case hotTRANSACTION_NODE:   type = "N"; break;
             default:                    type = "U";
         }
         statement.bind(1, object->getHash().GetHex());
         statement.bind(2, type);
         statement.bind(3, object->getIndex());
         statement.bindStatic(4, object->getData());
     }
NodeStore::Status ripple::SqliteBackend::fetch (void const * key, NodeObject::Ptr * pObject) inline virtual
Fetch a single object. If the object is not found or an error is encountered, the result will indicate the condition.
Note
This will be called concurrently.
Parameters
key A pointer to the key data.
pObject [out] The created object if successful.
Returns
The result of the operation.
Implements ripple::NodeStore::Backend.
Definition at line 74 of file SqliteFactory.cpp.
References ripple::SqliteStatement::bind(), ripple::NodeObject::createObject(), ripple::uint256::fromVoid(), getTypeFromString(), hash, m_db, ripple::NodeStore::notFound, and ripple::NodeStore::ok.
     {
         NodeStore::Status result = NodeStore::ok;
         pObject->reset ();
         {
             DeprecatedScopedLock sl (m_db->getDBLock());
             uint256 const hash (uint256::fromVoid (key));
             static SqliteStatement pSt (m_db->getDB()->getSqliteDB(),
                 "SELECT ObjType,LedgerIndex,Object FROM CommittedObjects WHERE Hash = ?;");
             pSt.bind (1, hash.GetHex());
             if (pSt.isRow (pSt.step()))
             {
                 // VFALCO NOTE This is unfortunately needed,
                 //             the DatabaseCon creates the blob?
                 Blob data (pSt.getBlob (2));
                 *pObject = NodeObject::createObject (
                     getTypeFromString (pSt.peekString (0)),
                     pSt.getUInt32 (1),
                     data,
                     hash);
             }
             else
             {
                 result = NodeStore::notFound;
             }
             pSt.reset();
         }
         return result;
     }
std::string ripple::SqliteBackend::getName () inline virtual
Get the human-readable name of this backend. This is used for diagnostic output.
Implements ripple::NodeStore::Backend.
Definition at line 67 of file SqliteFactory.cpp.
References m_name.
     {
         return m_name;
     }
NodeObjectType ripple::SqliteBackend::getTypeFromString (std::string const & s) inline
Definition at line 201 of file SqliteFactory.cpp.
References ripple::hotACCOUNT_NODE, ripple::hotLEDGER, ripple::hotTRANSACTION, ripple::hotTRANSACTION_NODE, and ripple::hotUNKNOWN.
Referenced by fetch(), and visitAll().
     {
         NodeObjectType type = hotUNKNOWN;
         if (!s.empty ())
         {
             switch (s [0])
             {
                 case 'L': type = hotLEDGER; break;
                 case 'T': type = hotTRANSACTION; break;
                 case 'A': type = hotACCOUNT_NODE; break;
                 case 'N': type = hotTRANSACTION_NODE; break;
             }
         }
         return type;
     }
int ripple::SqliteBackend::getWriteLoad () inline virtual
Estimate the number of write operations pending.
Implements ripple::NodeStore::Backend.
Definition at line 176 of file SqliteFactory.cpp.
     {
         return 0;
     }
void ripple::SqliteBackend::store (NodeObject::ref object) inline
Definition at line 112 of file SqliteFactory.cpp.
References storeBatch().
     {
         NodeStore::Batch batch;
         batch.push_back (object);
         storeBatch (batch);
     }
void ripple::SqliteBackend::storeBatch (NodeStore::Batch const & batch) inline virtual
Store a group of objects.
Note
This function will not be called concurrently with itself or store.
Implements ripple::NodeStore::Backend.
Definition at line 121 of file SqliteFactory.cpp.
References doBind(), m_db, and ripple::SqliteStatement::step().
Referenced by store().
     {
         // VFALCO TODO Rewrite this to use Beast::db
         DeprecatedScopedLock sl (m_db->getDBLock());
         static SqliteStatement pStB (m_db->getDB()->getSqliteDB(), "BEGIN TRANSACTION;");
         static SqliteStatement pStE (m_db->getDB()->getSqliteDB(), "END TRANSACTION;");
         static SqliteStatement pSt (m_db->getDB()->getSqliteDB(),
             "INSERT OR IGNORE INTO CommittedObjects "
                 "(Hash,ObjType,LedgerIndex,Object) VALUES (?, ?, ?, ?);");
         pStB.step();
         pStB.reset();
         BOOST_FOREACH (NodeObject::Ptr const& object, batch)
         {
             doBind (pSt, object);
             pSt.step();
             pSt.reset();
         }
         pStE.step();
         pStE.reset();
     }
void ripple::SqliteBackend::visitAll (NodeStore::VisitCallback & callback) inline virtual
Visit every object in the database This is usually called during import.
Note
This routine will not be called concurrently with itself or other methods.
See Also
import, VisitCallback
Implements ripple::NodeStore::Backend.
Definition at line 148 of file SqliteFactory.cpp.
References ripple::NodeObject::createObject(), getTypeFromString(), hash, m_db, ripple::base_uint< BITS >::SetHexExact(), and ripple::NodeStore::VisitCallback::visitObject().
     {
         // No lock needed as per the visitAll() API
         uint256 hash;
         static SqliteStatement pSt(m_db->getDB()->getSqliteDB(),
             "SELECT ObjType,LedgerIndex,Object,Hash FROM CommittedObjects;");
         while (pSt.isRow (pSt.step()))
         {
             hash.SetHexExact(pSt.getString(3));
             // VFALCO NOTE This is unfortunately needed,
             //             the DatabaseCon creates the blob?
             Blob data (pSt.getBlob (2));
             NodeObject::Ptr const object (NodeObject::createObject (
                 getTypeFromString (pSt.peekString (0)),
                 pSt.getUInt32 (1),
                 data,
                 hash));
             callback.visitObject (object);
         }
         pSt.reset ();
     }
Member Data Documentation
std::unique_ptr<DatabaseCon> ripple::SqliteBackend::m_db private
Definition at line 220 of file SqliteFactory.cpp.
Referenced by fetch(), SqliteBackend(), storeBatch(), and visitAll().
std::string const ripple::SqliteBackend::m_name private
Definition at line 219 of file SqliteFactory.cpp.
Referenced by getName().
The documentation for this class was generated from the following file:
rippled/src/ripple_app/node/SqliteFactory.cpp