rippled: rocksdb::MergeHelper Class Reference
rocksdb::MergeHelper Class Reference
#include <merge_helper.h>
Public Member Functions
MergeHelper (const Comparator *user_comparator, const MergeOperator *user_merge_operator, Logger *logger, bool assert_valid_internal_key)
void MergeUntil (Iterator *iter, SequenceNumber stop_before=0, bool at_bottom=false, shared_ptr< Statistics > stats=nullptr)
bool IsSuccess ()
Slice key ()
Slice value ()
const std::deque< std::string > & keys ()
const std::deque< std::string > & values ()
Private Attributes
const Comparator * user_comparator_
const MergeOperator * user_merge_operator_
Logger * logger_
bool assert_valid_internal_key_
std::deque< std::string > keys_
std::deque< std::string > operands_
bool success_
Detailed Description
Definition at line 22 of file merge_helper.h.
Constructor & Destructor Documentation
rocksdb::MergeHelper::MergeHelper (const Comparator * user_comparator, const MergeOperator * user_merge_operator, Logger * logger, bool assert_valid_internal_key) inline
Definition at line 24 of file merge_helper.h.
       : user_comparator_(user_comparator),
         user_merge_operator_(user_merge_operator),
         logger_(logger),
         assert_valid_internal_key_(assert_valid_internal_key),
         keys_(),
         operands_(),
         success_(false) {}
Member Function Documentation
bool rocksdb::MergeHelper::IsSuccess () inline
Definition at line 79 of file merge_helper.h.
References success_.
 { return success_; }
Slice rocksdb::MergeHelper::key () inline
Definition at line 80 of file merge_helper.h.
References keys_, and success_.
Referenced by MergeUntil().
 { assert(success_); return Slice(keys_.back()); }
const std::deque<std::string>& rocksdb::MergeHelper::keys () inline
Definition at line 82 of file merge_helper.h.
References keys_, and success_.
 { assert(!success_); return keys_; }
void rocksdb::MergeHelper::MergeUntil (Iterator * iter, SequenceNumber stop_before = 0, bool at_bottom = false, shared_ptr< Statistics > stats = nullptr)
Definition at line 22 of file merge_helper.cc.
References assert_valid_internal_key_, rocksdb::Comparator::Compare(), rocksdb::MergeOperator::FullMerge(), rocksdb::Iterator::key(), key(), keys_, rocksdb::kTypeDeletion, rocksdb::kTypeMerge, rocksdb::kTypeValue, logger_, rocksdb::Iterator::Next(), rocksdb::NUMBER_MERGE_FAILURES, operands_, rocksdb::ParseInternalKey(), rocksdb::MergeOperator::PartialMerge(), rocksdb::RecordTick(), rocksdb::ParsedInternalKey::sequence, success_, beast::asio::swap(), rocksdb::Slice::ToString(), rocksdb::ParsedInternalKey::type, rocksdb::UpdateInternalKey(), user_comparator_, rocksdb::ParsedInternalKey::user_key, user_merge_operator_, rocksdb::Iterator::Valid(), rocksdb::Iterator::value(), and value().
{
   // Get a copy of the internal key, before it's invalidated by iter->Next()
   // Also maintain the list of merge operands seen.
   keys_.clear();
   operands_.clear();
   keys_.push_front(iter->key().ToString());
   operands_.push_front(iter->value().ToString());
   success_ = false;   // Will become true if we hit Put/Delete or bottom
   // We need to parse the internal key again as the parsed key is
   // backed by the internal key!
   // Assume no internal key corruption as it has been successfully parsed
   // by the caller.
   // Invariant: keys_.back() will not change. Hence, orig_ikey is always valid.
   ParsedInternalKey orig_ikey;
   ParseInternalKey(keys_.back(), &orig_ikey);
   bool hit_the_next_user_key = false;
   ParsedInternalKey ikey;
   std::string merge_result;  // Temporary value for merge results
   for (iter->Next(); iter->Valid(); iter->Next()) {
     assert(operands_.size() >= 1);        // Should be invariants!
     assert(keys_.size() == operands_.size());
     if (!ParseInternalKey(iter->key(), &ikey)) {
       // stop at corrupted key
       if (assert_valid_internal_key_) {
         assert(!"corrupted internal key is not expected");
       }
       break;
     }
     if (user_comparator_->Compare(ikey.user_key, orig_ikey.user_key) != 0) {
       // hit a different user key, stop right here
       hit_the_next_user_key = true;
       break;
     }
     if (stop_before && ikey.sequence <= stop_before) {
       // hit an entry that's visible by the previous snapshot, can't touch that
       break;
     }
     // At this point we are guaranteed that we need to process this key.
     if (kTypeDeletion == ikey.type) {
       // hit a delete
       //   => merge nullptr with operands_
       //   => store result in operands_.back() (and update keys_.back())
       //   => change the entry type to kTypeValue for keys_.back()
       // We are done! Return a success if the merge passes.
       success_ = user_merge_operator_->FullMerge(ikey.user_key, nullptr,
                                                  operands_, &merge_result,
                                                  logger_);
       // We store the result in keys_.back() and operands_.back()
       // if nothing went wrong (i.e.: no operand corruption on disk)
       if (success_) {
         std::string& key = keys_.back();  // The original key encountered
         orig_ikey.type = kTypeValue;
         UpdateInternalKey(&key[0], key.size(),
                           orig_ikey.sequence, orig_ikey.type);
         swap(operands_.back(), merge_result);
       } else {
         RecordTick(stats, NUMBER_MERGE_FAILURES);
       }
       // move iter to the next entry (before doing anything else)
       iter->Next();
       return;
     }
     if (kTypeValue == ikey.type) {
       // hit a put
       //   => merge the put value with operands_
       //   => store result in operands_.back() (and update keys_.back())
       //   => change the entry type to kTypeValue for keys_.back()
       // We are done! Success!
       const Slice value = iter->value();
       success_ = user_merge_operator_->FullMerge(ikey.user_key, &value,
                                                  operands_, &merge_result,
                                                  logger_);
       // We store the result in keys_.back() and operands_.back()
       // if nothing went wrong (i.e.: no operand corruption on disk)
       if (success_) {
         std::string& key = keys_.back();  // The original key encountered
         orig_ikey.type = kTypeValue;
         UpdateInternalKey(&key[0], key.size(),
                           orig_ikey.sequence, orig_ikey.type);
         swap(operands_.back(), merge_result);
       } else {
         RecordTick(stats, NUMBER_MERGE_FAILURES);
       }
       // move iter to the next entry
       iter->Next();
       return;
     }
     if (kTypeMerge == ikey.type) {
       // hit a merge
       //   => merge the operand into the front of the operands_ list
       //   => use the user's associative merge function to determine how.
       //   => then continue because we haven't yet seen a Put/Delete.
       assert(!operands_.empty()); // Should have at least one element in it
       keys_.push_front(iter->key().ToString());
       operands_.push_front(iter->value().ToString());
       while (operands_.size() >= 2) {
         // Returns false when the merge_operator can no longer process it
         if (user_merge_operator_->PartialMerge(ikey.user_key,
                                                Slice(operands_[0]),
                                                Slice(operands_[1]),
                                                &merge_result,
                                                logger_)) {
           // Merging of operands (associative merge) was successful.
           // Replace these frontmost two operands with the merge result
           keys_.pop_front();
           operands_.pop_front();
           swap(operands_.front(), merge_result);
         } else {
           // Merging of operands (associative merge) returned false.
           // The user merge_operator does not know how to merge these operands.
           // So we just stack them up until we find a Put/Delete or end of key.
           break;
         }
       }
       continue;
     }
   }
   // We are sure we have seen this key's entire history if we are at the
   // last level and exhausted all internal keys of this user key.
   // NOTE: !iter->Valid() does not necessarily mean we hit the
   // beginning of a user key, as versions of a user key might be
   // split into multiple files (even files on the same level)
   // and some files might not be included in the compaction/merge.
   //
   // There are also cases where we have seen the root of history of this
   // key without being sure of it. Then, we simply miss the opportunity
   // to combine the keys. Since VersionSet::SetupOtherInputs() always makes
   // sure that all merge-operands on the same level get compacted together,
   // this will simply lead to these merge operands moving to the next level.
   //
   // So, we only perform the following logic (to merge all operands together
   // without a Put/Delete) if we are certain that we have seen the end of key.
   bool surely_seen_the_beginning = hit_the_next_user_key && at_bottom;
   if (surely_seen_the_beginning) {
     // do a final merge with nullptr as the existing value and say
     // bye to the merge type (it's now converted to a Put)
     assert(kTypeMerge == orig_ikey.type);
     assert(operands_.size() >= 1);
     assert(operands_.size() == keys_.size());
     success_ = user_merge_operator_->FullMerge(orig_ikey.user_key, nullptr,
                                                operands_, &merge_result,
                                                logger_);
     if (success_) {
       std::string& key = keys_.back();  // The original key encountered
       orig_ikey.type = kTypeValue;
       UpdateInternalKey(&key[0], key.size(),
                         orig_ikey.sequence, orig_ikey.type);
       // The final value() is always stored in operands_.back()
       swap(operands_.back(),merge_result);
     } else {
       RecordTick(stats, NUMBER_MERGE_FAILURES);
       // Do nothing if not success_. Leave keys() and operands() as they are.
     }
   }
 }
Slice rocksdb::MergeHelper::value () inline
Definition at line 81 of file merge_helper.h.
References operands_, and success_.
Referenced by MergeUntil().
 { assert(success_); return Slice(operands_.back()); }
const std::deque<std::string>& rocksdb::MergeHelper::values () inline
Definition at line 83 of file merge_helper.h.
References operands_, and success_.
{
     assert(!success_); return operands_;
   }
Member Data Documentation
bool rocksdb::MergeHelper::assert_valid_internal_key_ private
Definition at line 91 of file merge_helper.h.
Referenced by MergeUntil().
std::deque<std::string> rocksdb::MergeHelper::keys_ private
Definition at line 95 of file merge_helper.h.
Referenced by key(), keys(), and MergeUntil().
Logger* rocksdb::MergeHelper::logger_ private
Definition at line 90 of file merge_helper.h.
Referenced by MergeUntil().
std::deque<std::string> rocksdb::MergeHelper::operands_ private
Definition at line 96 of file merge_helper.h.
Referenced by MergeUntil(), value(), and values().
bool rocksdb::MergeHelper::success_ private
Definition at line 97 of file merge_helper.h.
Referenced by IsSuccess(), key(), keys(), MergeUntil(), value(), and values().
const Comparator* rocksdb::MergeHelper::user_comparator_ private
Definition at line 88 of file merge_helper.h.
Referenced by MergeUntil().
const MergeOperator* rocksdb::MergeHelper::user_merge_operator_ private
Definition at line 89 of file merge_helper.h.
Referenced by MergeUntil().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/db/merge_helper.h
rippled/src/ripple/rocksdb/rocksdb/db/merge_helper.cc