rippled: ripple::STUInt16 Class Reference
ripple::STUInt16 Class Reference
#include <SerializedTypes.h>
Public Member Functions
STUInt16 (std::uint16_t v=0)
STUInt16 (SField::ref n, std::uint16_t v=0)
SerializedTypeID getSType () const
std::string getText () const
Json::Value getJson (int) const
void add (Serializer &s) const
std::uint16_t getValue () const
void setValue (std::uint16_t v)
operator std::uint16_t () const
virtual bool isEquivalent (const SerializedType &t) const
virtual bool isDefault () const
Public Member Functions inherited from ripple::SerializedType
SerializedType ()
SerializedType (SField::ref n)
virtual ~SerializedType ()
void setFName (SField::ref n)
SField::ref getFName () const
std::string getName () const
std::unique_ptr< SerializedType > clone () const
virtual std::string getFullText () const
void addFieldID (Serializer &s) const
SerializedType & operator= (const SerializedType &t)
bool operator== (const SerializedType &t) const
bool operator!= (const SerializedType &t) const
template<class D >
D & downcast ()
template<class D >
D const & downcast () const
Static Public Member Functions
static std::unique_ptr
< SerializedType > deserialize (SerializerIterator &sit, SField::ref name)
Static Public Member Functions inherited from ripple::SerializedType
static std::unique_ptr
< SerializedType > deserialize (SField::ref name)
Private Member Functions
STUInt16 * duplicate () const
Static Private Member Functions
static STUInt16 * construct (SerializerIterator &, SField::ref name)
Private Attributes
std::uint16_t value
Additional Inherited Members
Protected Attributes inherited from ripple::SerializedType
SField::ptr fName
Detailed Description
Definition at line 280 of file SerializedTypes.h.
Constructor & Destructor Documentation
ripple::STUInt16::STUInt16 (std::uint16_t v = 0) inline
Definition at line 284 of file SerializedTypes.h.
Referenced by construct(), and duplicate().
                                  : value (v)
     {
         ;
     }
ripple::STUInt16::STUInt16 (SField::ref n, std::uint16_t v = 0) inline
Definition at line 288 of file SerializedTypes.h.
                                               : SerializedType (n), value (v)
     {
         ;
     }
Member Function Documentation
void ripple::STUInt16::add (Serializer & s) const inline virtual
Reimplemented from ripple::SerializedType.
Definition at line 303 of file SerializedTypes.h.
References ripple::Serializer::add16(), and value.
     {
         s.add16 (value);
     }
STUInt16 * ripple::STUInt16::construct (SerializerIterator & u, SField::ref name) static private
Definition at line 140 of file SerializedTypes.cpp.
References ripple::SerializerIterator::get16(), and STUInt16().
Referenced by deserialize().
 {
     return new STUInt16 (name, u.get16 ());
 }
static std::unique_ptr<SerializedType> ripple::STUInt16::deserialize (SerializerIterator & sit, SField::ref name) inline static
Definition at line 292 of file SerializedTypes.h.
References construct().
Referenced by ripple::STObject::makeDeserializedObject().
     {
         return std::unique_ptr<SerializedType> (construct (sit, name));
     }
STUInt16* ripple::STUInt16::duplicate () const inline private virtual
Reimplemented from ripple::SerializedType.
Definition at line 330 of file SerializedTypes.h.
References STUInt16().
     {
         return new STUInt16 (*this);
     }
Json::Value ripple::STUInt16::getJson (int) const virtual
Reimplemented from ripple::SerializedType.
Definition at line 168 of file SerializedTypes.cpp.
References ripple::KnownFormats< KeyType >::findByType(), ripple::SerializedType::getFName(), ripple::TxFormats::getInstance(), ripple::LedgerFormats::getInstance(), and value.
 {
     if (getFName () == sfLedgerEntryType)
     {
         LedgerFormats::Item const* const item =
             LedgerFormats::getInstance ()->findByType (static_cast <LedgerEntryType> (value));
         if (item != nullptr)
             return item->getName ();
     }
     if (getFName () == sfTransactionType)
     {
         TxFormats::Item const* const item =
             TxFormats::getInstance()->findByType (static_cast <TxType> (value));
         if (item != nullptr)
             return item->getName ();
     }
     return value;
 }
SerializedTypeID ripple::STUInt16::getSType () const inline virtual
Reimplemented from ripple::SerializedType.
Definition at line 297 of file SerializedTypes.h.
     {
         return STI_UINT16;
     }
std::string ripple::STUInt16::getText () const virtual
Reimplemented from ripple::SerializedType.
Definition at line 145 of file SerializedTypes.cpp.
References ripple::KnownFormats< KeyType >::findByType(), ripple::SerializedType::getFName(), ripple::TxFormats::getInstance(), ripple::LedgerFormats::getInstance(), and value.
 {
     if (getFName () == sfLedgerEntryType)
     {
         LedgerFormats::Item const* const item =
             LedgerFormats::getInstance ()->findByType (static_cast <LedgerEntryType> (value));
         if (item != nullptr)
             return item->getName ();
     }
     if (getFName () == sfTransactionType)
     {
         TxFormats::Item const* const item =
             TxFormats::getInstance()->findByType (static_cast <TxType> (value));
         if (item != nullptr)
             return item->getName ();
     }
     return beast::lexicalCastThrow <std::string> (value);
 }
std::uint16_t ripple::STUInt16::getValue () const inline
Definition at line 308 of file SerializedTypes.h.
References value.
Referenced by ripple::STObject::getFieldU16().
     {
         return value;
     }
virtual bool ripple::STUInt16::isDefault () const inline virtual
Reimplemented from ripple::SerializedType.
Definition at line 322 of file SerializedTypes.h.
References value.
     {
         return value == 0;
     }
bool ripple::STUInt16::isEquivalent (const SerializedType & t) const virtual
Reimplemented from ripple::SerializedType.
Definition at line 191 of file SerializedTypes.cpp.
References value.
 {
     const STUInt16* v = dynamic_cast<const STUInt16*> (&t);
     return v && (value == v->value);
 }
ripple::STUInt16::operator std::uint16_t () const inline
Definition at line 317 of file SerializedTypes.h.
References value.
     {
         return value;
     }
void ripple::STUInt16::setValue (std::uint16_t v) inline
Definition at line 312 of file SerializedTypes.h.
References value.
Referenced by ripple::STObject::setFieldU16().
     {
         value = v;
     }
Member Data Documentation
std::uint16_t ripple::STUInt16::value private
Definition at line 328 of file SerializedTypes.h.
Referenced by add(), getJson(), getText(), getValue(), isDefault(), isEquivalent(), operator std::uint16_t(), and setValue().
The documentation for this class was generated from the following files:
rippled/src/ripple_data/protocol/SerializedTypes.h
rippled/src/ripple_data/protocol/SerializedTypes.cpp