rippled: beast::HexEncoding Class Reference
beast::HexEncoding Class Reference
Static Public Member Functions
template<std::size_t Bytes>
static std::string encode (UnsignedInteger< Bytes > const &v)
template<std::size_t Bytes>
static bool decode (UnsignedInteger< Bytes > &rv, std::string const &s)
static std::string const & alphabet ()
static std::vector< int > const & inverse_alphabet ()
static std::vector< int > invert (std::string const &alphabet, int radix)
Detailed Description
Foolproof hexadecimal encoding and decoding facility. This is to check the correctness of the more complex converters.
Definition at line 133 of file BinaryEncoding.cpp.
Member Function Documentation
static std::string const& beast::HexEncoding::alphabet () inline static
Definition at line 174 of file BinaryEncoding.cpp.
Referenced by encode(), and inverse_alphabet().
     {
         static std::string s ("0123456789ABCDEF");
         return s;
     }
template<std::size_t Bytes> static bool beast::HexEncoding::decode (UnsignedInteger< Bytes > & rv, std::string const & s) inline static
Definition at line 153 of file BinaryEncoding.cpp.
References beast::UnsignedInteger< Bytes >::begin(), and inverse_alphabet().
Referenced by beast::BinaryEncoding_test::testBase16().
     {
         // can't have an odd size
         if (s.size() & 1)
             return false;
         std::uint8_t* dest (rv.begin()-1);
         int const* const tab (&inverse_alphabet().front());
         for (std::string::const_iterator iter (s.begin()); iter != s.end();)
         {
             int const n1 (tab [*iter++]);
             if (n1 == -1)
                 return false;
             int const n2 (tab [*iter++]);
             if (n2 == -1)
                 return false;
             *++dest = ((std::uint8_t)((n1<<4)|n2));
         }
         return true;
     }
template<std::size_t Bytes> static std::string beast::HexEncoding::encode (UnsignedInteger< Bytes > const & v) inline static
Definition at line 137 of file BinaryEncoding.cpp.
References alphabet(), beast::UnsignedInteger< Bytes >::cbegin(), and beast::UnsignedInteger< Bytes >::size.
Referenced by beast::BinaryEncoding_test::testBase16().
     {
         std::string s;
         std::uint8_t const* src (v.cbegin()-1);
         char const* const tab (alphabet().c_str());
         s.reserve (Bytes * 2);
         for (std::size_t bytes (v.size);bytes--;)
         {
             std::uint8_t const v (*++src);
             s.push_back (tab [v>>4]);
             s.push_back (tab [v&0x0f]);
         }
         return s;
     }
static std::vector<int> const& beast::HexEncoding::inverse_alphabet () inline static
Definition at line 180 of file BinaryEncoding.cpp.
References alphabet(), and invert().
Referenced by decode().
     {
         static std::vector <int> s (invert (alphabet(), 16));
         return s;
     }
static std::vector<int> beast::HexEncoding::invert (std::string const & alphabet, int radix) inline static
Build the inverse mapping table from characters to digits.
Definition at line 188 of file BinaryEncoding.cpp.
Referenced by inverse_alphabet().
     {
         std::vector <int> table (256, -1);
         for (int i (0); i < radix; ++i)
             table [alphabet [i]] = int(i);
         return table;
     }
The documentation for this class was generated from the following file:
rippled/src/beast/beast/crypto/tests/BinaryEncoding.cpp