rippled: beast::asio::buffer_sequence< Buffer > Class Template Reference
beast::asio::buffer_sequence< Buffer > Class Template Reference
#include <buffer_sequence.h>
Public Types
typedef Buffer value_type
typedef
sequence_type::const_iterator const_iterator
Public Member Functions
buffer_sequence ()
template<class BufferSequence , class = std::enable_if_t <std::is_constructible < Buffer, typename BufferSequence::value_type>::value>>
buffer_sequence (BufferSequence const &s)
template<class FwdIter , class = std::enable_if_t <std::is_constructible < Buffer, typename std::iterator_traits < FwdIter>::value_type>::value>>
buffer_sequence (FwdIter first, FwdIter last)
template<class BufferSequence >
std::enable_if_t
< std::is_constructible
< Buffer, typename
BufferSequence::value_type >
::value, buffer_sequence & > operator= (BufferSequence const &s)
const_iterator begin () const noexcept
const_iterator end () const noexcept
Private Types
typedef std::vector< Buffer > sequence_type
Private Member Functions
template<class FwdIter >
void assign (FwdIter first, FwdIter last)
Private Attributes
sequence_type m_buffers
Detailed Description
template<class Buffer>
class beast::asio::buffer_sequence< Buffer >
Definition at line 35 of file buffer_sequence.h.
Member Typedef Documentation
template<class Buffer > typedef sequence_type::const_iterator beast::asio::buffer_sequence< Buffer >::const_iterator
Definition at line 42 of file buffer_sequence.h.
template<class Buffer > typedef std::vector<Buffer> beast::asio::buffer_sequence< Buffer >::sequence_type private
Definition at line 38 of file buffer_sequence.h.
template<class Buffer > typedef Buffer beast::asio::buffer_sequence< Buffer >::value_type
Definition at line 41 of file buffer_sequence.h.
Constructor & Destructor Documentation
template<class Buffer > beast::asio::buffer_sequence< Buffer >::buffer_sequence () inline
Definition at line 57 of file buffer_sequence.h.
     {
     }
template<class Buffer > template<class BufferSequence , class = std::enable_if_t <std::is_constructible < Buffer, typename BufferSequence::value_type>::value>> beast::asio::buffer_sequence< Buffer >::buffer_sequence (BufferSequence const & s) inline
Definition at line 66 of file buffer_sequence.h.
References beast::asio::buffer_sequence< Buffer >::assign().
     {
         assign (std::begin (s), std::end (s));
     }
template<class Buffer > template<class FwdIter , class = std::enable_if_t <std::is_constructible < Buffer, typename std::iterator_traits < FwdIter>::value_type>::value>> beast::asio::buffer_sequence< Buffer >::buffer_sequence (FwdIter first, FwdIter last) inline
Definition at line 77 of file buffer_sequence.h.
References beast::asio::buffer_sequence< Buffer >::assign().
     {
         assign (first, last);
     }
Member Function Documentation
template<class Buffer > template<class FwdIter > void beast::asio::buffer_sequence< Buffer >::assign (FwdIter first, FwdIter last) inline private
Definition at line 48 of file buffer_sequence.h.
References beast.util.Iter::first(), and beast::asio::buffer_sequence< Buffer >::m_buffers.
Referenced by beast::asio::buffer_sequence< Buffer >::buffer_sequence(), and beast::asio::buffer_sequence< Buffer >::operator=().
     {
         m_buffers.clear();
         m_buffers.reserve (std::distance (first, last));
         for (;first != last; ++first)
             m_buffers.push_back (*first);
     }
template<class Buffer > const_iterator beast::asio::buffer_sequence< Buffer >::begin () const inline noexcept
Definition at line 93 of file buffer_sequence.h.
References beast::asio::buffer_sequence< Buffer >::m_buffers.
     {
         return m_buffers.begin ();
     }
template<class Buffer > const_iterator beast::asio::buffer_sequence< Buffer >::end () const inline noexcept
Definition at line 99 of file buffer_sequence.h.
References beast::asio::buffer_sequence< Buffer >::m_buffers.
     {
         return m_buffers.end ();
     }
template<class Buffer > template<class BufferSequence > std::enable_if_t<std::is_constructible < Buffer, typename BufferSequence::value_type>::value, buffer_sequence& > beast::asio::buffer_sequence< Buffer >::operator= (BufferSequence const & s) inline
Definition at line 87 of file buffer_sequence.h.
References beast::asio::buffer_sequence< Buffer >::assign().
     {
         return assign (s);
     }
Member Data Documentation
template<class Buffer > sequence_type beast::asio::buffer_sequence< Buffer >::m_buffers private
Definition at line 45 of file buffer_sequence.h.
Referenced by beast::asio::buffer_sequence< Buffer >::assign(), beast::asio::buffer_sequence< Buffer >::begin(), and beast::asio::buffer_sequence< Buffer >::end().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/asio/buffer_sequence.h