rippled: ripple::PeerFinder::Logic Class Reference
ripple::PeerFinder::Logic Class Reference
#include <Logic.h>
Classes
struct State
Public Types
typedef std::map
< beast::IP::Endpoint,
std::shared_ptr< SlotImp > > Slots
typedef std::map
< beast::IP::Endpoint, Fixed > FixedSlots
typedef std::set< RipplePublicKey > Keys
typedef std::multiset
< beast::IP::Endpoint > ConnectedAddresses
typedef beast::SharedData< State > SharedState
Public Member Functions
Logic (clock_type &clock, Callback &callback, Store &store, Checker &checker, beast::Journal journal)
void load ()
void stop ()
void setConfig (Config const &config)
void addFixedPeer (std::string const &name, std::vector< beast::IP::Endpoint > const &addresses)
void checkComplete (beast::IP::Endpoint const &address, beast::IP::Endpoint const &checkedAddress, Checker::Result const &result)
SlotImp::ptr new_inbound_slot (beast::IP::Endpoint const &local_endpoint, beast::IP::Endpoint const &remote_endpoint)
SlotImp::ptr new_outbound_slot (beast::IP::Endpoint const &remote_endpoint)
void on_connected (SlotImp::ptr const &slot, beast::IP::Endpoint const &local_endpoint)
void on_handshake (SlotImp::ptr const &slot, RipplePublicKey const &key, bool cluster)
void preprocess (SlotImp::ptr const &slot, Endpoints &list, SharedState::Access &state)
void on_endpoints (SlotImp::ptr const &slot, Endpoints list)
void on_legacy_endpoints (IPAddresses const &list)
void remove (SlotImp::ptr const &slot, SharedState::Access &state)
void on_closed (SlotImp::ptr const &slot)
void on_cancel (SlotImp::ptr const &slot)
bool fixed (beast::IP::Endpoint const &endpoint, SharedState::Access &state) const
bool fixed (beast::IP::Address const &address, SharedState::Access &state) const
template<class Container >
void get_fixed (std::size_t needed, Container &c, SharedState::Access &state)
void squelch_slots (SharedState::Access &state)
void autoconnect ()
void addStaticSource (beast::SharedPtr< Source > const &source)
void addSource (beast::SharedPtr< Source > const &source)
void expire ()
void periodicActivity ()
bool addBootcacheAddress (beast::IP::Endpoint const &address, SharedState::Access &state)
int addBootcacheAddresses (IPAddresses const &list)
void fetch (beast::SharedPtr< Source > const &source)
bool is_valid_address (beast::IP::Endpoint const &address)
void redirect (SlotImp::ptr const &slot, SharedState::Access &state)
void broadcast ()
void writeSlots (beast::PropertyStream::Set &set, Slots const &slots)
void onWrite (beast::PropertyStream::Map &map)
State const & state () const
Counts const & counts () const
Static Public Member Functions
static std::string stateString (Slot::State state)
Public Attributes
beast::Journal m_journal
SharedState m_state
clock_type & m_clock
Callback & m_callback
Store & m_store
Checker & m_checker
std::vector< beast::SharedPtr
< Source > > m_sources
clock_type::time_point m_whenBroadcast
ConnectHandouts::Squelches m_squelches
Detailed Description
The Logic for maintaining the list of Slot addresses. We keep this in a separate class so it can be instantiated for unit tests.
Definition at line 43 of file Logic.h.
Member Typedef Documentation
typedef std::multiset<beast::IP::Endpoint> ripple::PeerFinder::Logic::ConnectedAddresses
Definition at line 59 of file Logic.h.
typedef std::map<beast::IP::Endpoint, Fixed> ripple::PeerFinder::Logic::FixedSlots
Definition at line 52 of file Logic.h.
typedef std::set<RipplePublicKey> ripple::PeerFinder::Logic::Keys
Definition at line 55 of file Logic.h.
typedef beast::SharedData<State> ripple::PeerFinder::Logic::SharedState
Definition at line 110 of file Logic.h.
typedef std::map<beast::IP::Endpoint, std::shared_ptr <SlotImp> > ripple::PeerFinder::Logic::Slots
Definition at line 50 of file Logic.h.
Constructor & Destructor Documentation
ripple::PeerFinder::Logic::Logic (clock_type & clock, Callback & callback, Store & store, Checker & checker, beast::Journal journal) inline
Definition at line 128 of file Logic.h.
References setConfig().
         : m_journal (journal, Reporting::logic)
         , m_state (&store, std::ref (clock), journal)
         , m_clock (clock)
         , m_callback (callback)
         , m_store (store)
         , m_checker (checker)
         , m_whenBroadcast (m_clock.now())
         , m_squelches (m_clock)
     {
         setConfig (Config ());
     }
Member Function Documentation
bool ripple::PeerFinder::Logic::addBootcacheAddress (beast::IP::Endpoint const & address, SharedState::Access & state) inline
Definition at line 937 of file Logic.h.
Referenced by addBootcacheAddresses().
     {
         return state->bootcache.insert (address);
     }
int ripple::PeerFinder::Logic::addBootcacheAddresses (IPAddresses const & list) inline
Definition at line 946 of file Logic.h.
References addBootcacheAddress(), m_state, and state().
Referenced by fetch().
     {
         int count (0);
         SharedState::Access state (m_state);
         for (auto addr : list)
         {
             if (addBootcacheAddress (addr, state))
                 ++count;
         }
         return count;
     }
void ripple::PeerFinder::Logic::addFixedPeer (std::string const & name, std::vector< beast::IP::Endpoint > const & addresses) inline
Definition at line 182 of file Logic.h.
References beast::Journal::debug, beast::Journal::info, m_clock, m_journal, m_state, and state().
Referenced by ripple::PeerFinder::ManagerImp::addFixedPeer().
     {
         SharedState::Access state (m_state);
         if (addresses.empty ())
         {
             if (m_journal.info) m_journal.info <<
                 "Could not resolve fixed slot '" << name << "'";
             return;
         }
         for (auto const& remote_address : addresses)
         {
             auto result (state->fixed.emplace (std::piecewise_construct,
                 std::forward_as_tuple (remote_address),
                     std::make_tuple (std::ref (m_clock))));
             if (result.second)
             {
                 if (m_journal.debug) m_journal.debug << beast::leftw (18) <<
                     "Logic add fixed" << "'" << name <<
                     "' at " << remote_address;
                 return;
             }
         }
     }
void ripple::PeerFinder::Logic::addSource (beast::SharedPtr< Source > const & source) inline
Definition at line 886 of file Logic.h.
References m_sources.
     {
         m_sources.push_back (source);
     }
void ripple::PeerFinder::Logic::addStaticSource (beast::SharedPtr< Source > const & source) inline
Definition at line 881 of file Logic.h.
References fetch().
Referenced by ripple::PeerFinder::ManagerImp::addFallbackStrings().
     {
         fetch (source);
     }
void ripple::PeerFinder::Logic::autoconnect () inline
Create new outbound connection attempts as needed. This implements PeerFinder's "Outbound Connection Strategy"
Definition at line 773 of file Logic.h.
References ripple::PeerFinder::Callback::connect(), beast::Journal::debug, ripple::PeerFinder::ConnectHandouts::full(), get_fixed(), ripple::PeerFinder::handout(), ripple::PeerFinder::ConnectHandouts::list(), m_callback, m_journal, m_squelches, m_state, squelch_slots(), state(), and ripple::PeerFinder::ConnectHandouts::try_insert().
Referenced by periodicActivity().
     {
         SharedState::Access state (m_state);
         // Count how many more outbound attempts to make
         //
         auto needed (state->counts.attempts_needed ());
         if (needed == 0)
             return;
         ConnectHandouts h (needed, m_squelches);
         // Make sure we don't connect to already-connected entries.
         squelch_slots (state);
         // 1. Use Fixed if:
         //    Fixed active count is below fixed count AND
         //      ( There are eligible fixed addresses to try OR
         //        Any outbound attempts are in progress)
         //
         if (state->counts.fixed_active() < state->fixed.size ())
         {
             get_fixed (needed, h.list(), state);
             if (! h.list().empty ())
             {
                 if (m_journal.debug) m_journal.debug << beast::leftw (18) <<
                     "Logic connect " << h.list().size() << " fixed";
                 m_callback.connect (h.list());
                 return;
             }
             if (state->counts.attempts() > 0)
             {
                 if (m_journal.debug) m_journal.debug << beast::leftw (18) <<
                     "Logic waiting on " <<
                         state->counts.attempts() << " attempts";
                 return;
             }
         }
         // Only proceed if auto connect is enabled and we
         // have less than the desired number of outbound slots
         //
         if (! state->config.autoConnect ||
             state->counts.out_active () >= state->counts.out_max ())
             return;
         // 2. Use Livecache if:
         //    There are any entries in the cache OR
         //    Any outbound attempts are in progress
         //
         {
             state->livecache.hops.shuffle();
             handout (&h, (&h)+1,
                 state->livecache.hops.rbegin(),
                     state->livecache.hops.rend());
             if (! h.list().empty ())
             {
                 if (m_journal.debug) m_journal.debug << beast::leftw (18) <<
                     "Logic connect " << h.list().size () << " live " <<
                     ((h.list().size () > 1) ? "endpoints" : "endpoint");
                 m_callback.connect (h.list());
                 return;
             }
             else if (state->counts.attempts() > 0)
             {
                 if (m_journal.debug) m_journal.debug << beast::leftw (18) <<
                     "Logic waiting on " <<
                         state->counts.attempts() << " attempts";
                 return;
             }
         }
         /*  3. Bootcache refill
             If the Bootcache is empty, try to get addresses from the current
             set of Sources and add them into the Bootstrap cache.
             Pseudocode:
                 If (    domainNames.count() > 0 AND (
                            unusedBootstrapIPs.count() == 0
                         OR activeNameResolutions.count() > 0) )
                     ForOneOrMore (DomainName that hasn't been resolved recently)
                         Contact DomainName and add entries to the unusedBootstrapIPs
                     return;
         */
         // 4. Use Bootcache if:
         //    There are any entries we haven't tried lately
         //
         for (auto iter (state->bootcache.begin());
             ! h.full() && iter != state->bootcache.end(); ++iter)
             h.try_insert (*iter);
         if (! h.list().empty ())
         {
             if (m_journal.debug) m_journal.debug << beast::leftw (18) <<
                 "Logic connect " << h.list().size () << " boot " <<
                 ((h.list().size () > 1) ? "addresses" : "address");
             m_callback.connect (h.list());
             return;
         }
         // If we get here we are stuck
     }
void ripple::PeerFinder::Logic::broadcast () inline
Definition at line 1045 of file Logic.h.
References ripple::PeerFinder::Slot::active, ripple::PeerFinder::Endpoint::address, beast::IP::Endpoint::at_port(), ripple::PeerFinder::handout(), ripple::PeerFinder::Endpoint::hops, m_callback, m_journal, m_state, ripple::PeerFinder::Callback::send(), state(), beast::Journal::trace, and value.
Referenced by periodicActivity().
     {
         SharedState::Access state (m_state);
         std::vector <SlotHandouts> targets;
         {
             // build list of active slots
             std::vector <SlotImp::ptr> slots;
             slots.reserve (state->slots.size());
             std::for_each (state->slots.cbegin(), state->slots.cend(),
                 [&slots](Slots::value_type const& value)
                 {
                     if (value.second->state() == Slot::active)
                         slots.emplace_back (value.second);
                 });
             std::random_shuffle (slots.begin(), slots.end());
             // build target vector
             targets.reserve (slots.size());
             std::for_each (slots.cbegin(), slots.cend(),
                 [&targets](SlotImp::ptr const& slot)
                 {
                     targets.emplace_back (slot);
                 });
         }
         /* VFALCO NOTE
             This is a temporary measure. Once we know our own IP
             address, the correct solution is to put it into the Livecache
             at hops 0, and go through the regular handout path. This way
             we avoid handing our address out too frequenty, which this code
             suffers from.
         */
         // Add an entry for ourselves if:
         // 1. We want incoming
         // 2. We have slots
         // 3. We haven't failed the firewalled test
         //
         if (state->config.wantIncoming &&
             state->counts.inboundSlots() > 0)
         {
             Endpoint ep;
             ep.hops = 0;
             ep.address = beast::IP::Endpoint (
                 beast::IP::AddressV4 ()).at_port (
                     state->config.listeningPort);
             for (auto& t : targets)
                 t.insert (ep);
         }
         // build sequence of endpoints by hops
         state->livecache.hops.shuffle();
         handout (targets.begin(), targets.end(),
             state->livecache.hops.begin(),
                 state->livecache.hops.end());
         // broadcast
         for (auto const& t : targets)
         {
             SlotImp::ptr const& slot (t.slot());
             auto const& list (t.list());
             if (m_journal.trace) m_journal.trace << beast::leftw (18) <<
                 "Logic sending " << slot->remote_endpoint() <<
                 " with " << list.size() <<
                 ((list.size() == 1) ? " endpoint" : " endpoints");
             m_callback.send (slot, list);
         }
     }
void ripple::PeerFinder::Logic::checkComplete (beast::IP::Endpoint const & address, beast::IP::Endpoint const & checkedAddress, Checker::Result const & result) inline
Definition at line 213 of file Logic.h.
References ripple::PeerFinder::Checker::Result::canAccept, beast::Journal::debug, ripple::PeerFinder::Checker::Result::error, beast::Journal::error, beast::Journal::info, m_journal, m_state, and state().
Referenced by on_endpoints().
     {
         if (result.error == boost::asio::error::operation_aborted)
             return;
         SharedState::Access state (m_state);
         Slots::iterator const iter (state->slots.find (address));
         SlotImp& slot (*iter->second);
         if (iter == state->slots.end())
         {
             // The slot disconnected before we finished the check
             if (m_journal.debug) m_journal.debug << beast::leftw (18) <<
                 "Logic tested " << address <<
                 " but the connection was closed";
             return;
         }
         // Mark that a check for this slot is finished.
         slot.connectivityCheckInProgress = false;
         if (! result.error)
         {
             slot.checked = true;
             slot.canAccept = result.canAccept;
             if (slot.canAccept)
             {
                 if (m_journal.debug) m_journal.debug << beast::leftw (18) <<
                     "Logic testing " << address << " succeeded";
             }
             else
             {
                 if (m_journal.info) m_journal.info << beast::leftw (18) <<
                     "Logic testing " << address << " failed";
             }
         }
         else
         {
             // VFALCO TODO Should we retry depending on the error?
             slot.checked = true;
             slot.canAccept = false;
             if (m_journal.error) m_journal.error << beast::leftw (18) <<
                 "Logic testing " << iter->first << " with error, " <<
                 result.error.message();
         }
         if (! slot.canAccept)
             state->bootcache.on_failure (address);
     }
Counts const& ripple::PeerFinder::Logic::counts () const inline
Definition at line 1188 of file Logic.h.
References m_state.
     {
         return SharedState::ConstAccess (m_state)->counts;
     }
void ripple::PeerFinder::Logic::expire () inline
Definition at line 894 of file Logic.h.
References beast::expire(), m_squelches, m_state, ripple::PeerFinder::Tuning::recentAttemptDuration(), and state().
Referenced by periodicActivity().
     {
         SharedState::Access state (m_state);
         // Expire the Livecache
         state->livecache.expire ();
         // Expire the recent cache in each slot
         for (auto const& entry : state->slots)
             entry.second->expire();
         // Expire the recent attempts table
         beast::expire (m_squelches,
             Tuning::recentAttemptDuration);
     }
void ripple::PeerFinder::Logic::fetch (beast::SharedPtr< Source > const & source) inline
Definition at line 959 of file Logic.h.
References addBootcacheAddresses(), ripple::PeerFinder::Source::Results::addresses, ripple::PeerFinder::Source::Results::error, beast::Journal::error, beast::Journal::info, m_journal, m_state, and state().
Referenced by addStaticSource().
     {
         Source::Results results;
         {
             {
                 SharedState::Access state (m_state);
                 if (state->stopping)
                     return;
                 state->fetchSource = source;
             }
             // VFALCO NOTE The fetch is synchronous,
             //             not sure if that's a good thing.
             //
             source->fetch (results, m_journal);
             {
                 SharedState::Access state (m_state);
                 if (state->stopping)
                     return;
                 state->fetchSource = nullptr;
             }
         }
         if (! results.error)
         {
             int const count (addBootcacheAddresses (results.addresses));
             if (m_journal.info) m_journal.info << beast::leftw (18) <<
                 "Logic added " << count <<
                 " new " << ((count == 1) ? "address" : "addresses") <<
                 " from " << source->name();
         }
         else
         {
             if (m_journal.error) m_journal.error << beast::leftw (18) <<
                 "Logic failed " << "'" << source->name() << "' fetch, " <<
                 results.error.message();
         }
     }
bool ripple::PeerFinder::Logic::fixed (beast::IP::Endpoint const & endpoint, SharedState::Access & state) const inline
Definition at line 709 of file Logic.h.
Referenced by new_inbound_slot(), and new_outbound_slot().
     {
         for (auto const& entry : state->fixed)
             if (entry.first == endpoint)
                 return true;
         return false;
     }
bool ripple::PeerFinder::Logic::fixed (beast::IP::Address const & address, SharedState::Access & state) const inline
Definition at line 719 of file Logic.h.
     {
         for (auto const& entry : state->fixed)
             if (entry.first.address () == address)
                 return true;
         return false;
     }
template<class Container > void ripple::PeerFinder::Logic::get_fixed (std::size_t needed, Container & c, SharedState::Access & state) inline
Adds eligible Fixed addresses for outbound attempts.
Definition at line 735 of file Logic.h.
References m_clock, and beast::abstract_clock< Duration >::now().
Referenced by autoconnect().
     {
         auto const now (m_clock.now());
         for (auto iter = state->fixed.begin ();
             needed && iter != state->fixed.end (); ++iter)
         {
             auto const& address (iter->first.address());
             if (iter->second.when() <= now && std::none_of (
                 state->slots.cbegin(), state->slots.cend(),
                     [address](Slots::value_type const& v)
                     {
                         return address == v.first.address();
                     }))
             {
                 c.push_back (iter->first);
                 --needed;
             }
         }
     }
bool ripple::PeerFinder::Logic::is_valid_address (beast::IP::Endpoint const & address) inline
Definition at line 1007 of file Logic.h.
References beast::IP::is_public(), beast::IP::is_unspecified(), and beast::IP::Endpoint::port().
Referenced by preprocess().
     {
         if (is_unspecified (address))
             return false;
         if (! is_public (address))
             return false;
         if (address.port() == 0)
             return false;
         return true;
     }
void ripple::PeerFinder::Logic::load () inline
Definition at line 148 of file Logic.h.
References m_state, and state().
Referenced by ripple::PeerFinder::ManagerImp::init().
     {
         SharedState::Access state (m_state);
         state->bootcache.load ();
     }
SlotImp::ptr ripple::PeerFinder::Logic::new_inbound_slot (beast::IP::Endpoint const & local_endpoint, beast::IP::Endpoint const & remote_endpoint) inline
Definition at line 268 of file Logic.h.
References beast::IP::Endpoint::address(), beast::IP::Endpoint::at_port(), beast::Journal::debug, fixed(), m_clock, m_journal, m_state, state(), and beast::Journal::warning.
Referenced by ripple::PeerFinder::ManagerImp::new_inbound_slot().
     {
         if (m_journal.debug) m_journal.debug << beast::leftw (18) <<
             "Logic accept" << remote_endpoint <<
             " on local " << local_endpoint;
         SharedState::Access state (m_state);
         // Check for self-connect by address
         {
             auto const iter (state->slots.find (local_endpoint));
             if (iter != state->slots.end ())
             {
                 Slot::ptr const& self (iter->second);
                 assert ((self->local_endpoint () == boost::none) ||
                     (self->local_endpoint () == remote_endpoint));
                 if (m_journal.warning) m_journal.warning << beast::leftw (18) <<
                     "Logic dropping " << remote_endpoint <<
                     " as self connect";
                 return SlotImp::ptr ();
             }
         }
         // Create the slot
         SlotImp::ptr const slot (std::make_shared <SlotImp> (local_endpoint,
             remote_endpoint, fixed (remote_endpoint.address (), state),
                 m_clock));
         // Add slot to table
         auto const result (state->slots.emplace (
             slot->remote_endpoint (), slot));
         // Remote address must not already exist
         assert (result.second);
         // Add to the connected address list
         state->connected_addresses.emplace (remote_endpoint.at_port (0));
         // Update counts
         state->counts.add (*slot);
         return result.first->second;
     }
SlotImp::ptr ripple::PeerFinder::Logic::new_outbound_slot (beast::IP::Endpoint const & remote_endpoint) inline
Definition at line 310 of file Logic.h.
References beast::IP::Endpoint::at_port(), beast::Journal::debug, fixed(), m_clock, m_journal, m_state, state(), and beast::Journal::warning.
Referenced by ripple::PeerFinder::ManagerImp::new_outbound_slot().
     {
         if (m_journal.debug) m_journal.debug << beast::leftw (18) <<
             "Logic connect " << remote_endpoint;
         SharedState::Access state (m_state);
         // Check for duplicate connection
         if (state->slots.find (remote_endpoint) !=
             state->slots.end ())
         {
             if (m_journal.warning) m_journal.warning << beast::leftw (18) <<
                 "Logic dropping " << remote_endpoint <<
                 " as duplicate connect";
             return SlotImp::ptr ();
         }
         // Create the slot
         SlotImp::ptr const slot (std::make_shared <SlotImp> (
             remote_endpoint, fixed (remote_endpoint, state), m_clock));
         // Add slot to table
         std::pair <Slots::iterator, bool> result (
             state->slots.emplace (slot->remote_endpoint (),
                 slot));
         // Remote address must not already exist
         assert (result.second);
         // Add to the connected address list
         state->connected_addresses.emplace (remote_endpoint.at_port (0));
         // Update counts
         state->counts.add (*slot);
         return result.first->second;
     }
void ripple::PeerFinder::Logic::on_cancel (SlotImp::ptr const & slot) inline
Definition at line 696 of file Logic.h.
References m_journal, m_state, state(), and beast::Journal::trace.
Referenced by ripple::PeerFinder::ManagerImp::on_cancel().
     {
         SharedState::Access state (m_state);
         remove (slot, state);
         if (m_journal.trace) m_journal.trace << beast::leftw (18) <<
             "Logic cancel " << slot->remote_endpoint();
     }
void ripple::PeerFinder::Logic::on_closed (SlotImp::ptr const & slot) inline
Definition at line 647 of file Logic.h.
References ripple::PeerFinder::Slot::accept, ripple::PeerFinder::Slot::active, ripple::PeerFinder::Slot::closing, ripple::PeerFinder::Slot::connect, ripple::PeerFinder::Slot::connected, beast::Journal::debug, m_clock, m_journal, m_state, beast::abstract_clock< Duration >::now(), state(), and beast::Journal::trace.
Referenced by ripple::PeerFinder::ManagerImp::on_closed().
     {
         SharedState::Access state (m_state);
         remove (slot, state);
         // Mark fixed slot failure
         if (slot->fixed() && ! slot->inbound() && slot->state() != Slot::active)
         {
             auto iter (state->fixed.find (slot->remote_endpoint()));
             assert (iter != state->fixed.end ());
             iter->second.failure (m_clock.now ());
             if (m_journal.debug) m_journal.debug << beast::leftw (18) <<
                 "Logic fixed " << slot->remote_endpoint () << " failed";
         }
         // Do state specific bookkeeping
         switch (slot->state())
         {
         case Slot::accept:
             if (m_journal.trace) m_journal.trace << beast::leftw (18) <<
                 "Logic accept " << slot->remote_endpoint () << " failed";
             break;
         case Slot::connect:
         case Slot::connected:
             state->bootcache.on_failure (slot->remote_endpoint ());
             // VFALCO TODO If the address exists in the ephemeral/live
             //             endpoint livecache then we should mark the failure
             // as if it didn't pass the listening test. We should also
             // avoid propagating the address.
             break;
         case Slot::active:
             if (m_journal.trace) m_journal.trace << beast::leftw (18) <<
                 "Logic close " << slot->remote_endpoint();
             break;
         case Slot::closing:
             if (m_journal.trace) m_journal.trace << beast::leftw (18) <<
                 "Logic finished " << slot->remote_endpoint();
             break;
         default:
             assert (false);
             break;
         }
     }
void ripple::PeerFinder::Logic::on_connected (SlotImp::ptr const & slot, beast::IP::Endpoint const & local_endpoint) inline
Definition at line 347 of file Logic.h.
References ripple::PeerFinder::Slot::connected, ripple::PeerFinder::Callback::disconnect(), m_callback, m_journal, m_state, state(), beast::Journal::trace, and beast::Journal::warning.
Referenced by ripple::PeerFinder::ManagerImp::on_connected().
     {
         if (m_journal.trace) m_journal.trace << beast::leftw (18) <<
             "Logic connected" << slot->remote_endpoint () <<
             " on local " << local_endpoint;
         SharedState::Access state (m_state);
         // The object must exist in our table
         assert (state->slots.find (slot->remote_endpoint ()) !=
             state->slots.end ());
         // Assign the local endpoint now that it's known
         slot->local_endpoint (local_endpoint);
         // Check for self-connect by address
         {
             auto const iter (state->slots.find (local_endpoint));
             if (iter != state->slots.end ())
             {
                 Slot::ptr const& self (iter->second);
                 assert (self->local_endpoint () == slot->remote_endpoint ());
                 if (m_journal.warning) m_journal.warning << beast::leftw (18) <<
                     "Logic dropping " << slot->remote_endpoint () <<
                     " as self connect";
                 m_callback.disconnect (slot, false);
                 return;
             }
         }
         // Update counts
         state->counts.remove (*slot);
         slot->state (Slot::connected);
         state->counts.add (*slot);
     }
void ripple::PeerFinder::Logic::on_endpoints (SlotImp::ptr const & slot, Endpoints list) inline
Definition at line 531 of file Logic.h.
References ripple::PeerFinder::Slot::active, ripple::PeerFinder::Endpoint::address, ripple::PeerFinder::Checker::async_test(), checkComplete(), ripple::PeerFinder::Endpoint::hops, m_checker, m_clock, m_journal, m_state, beast::abstract_clock< Duration >::now(), preprocess(), ripple::PeerFinder::Tuning::secondsPerMessage(), state(), beast::Journal::trace, and beast::Journal::warning.
Referenced by ripple::PeerFinder::ManagerImp::on_endpoints().
     {
         if (m_journal.trace) m_journal.trace << beast::leftw (18) <<
             "Endpoints from " << slot->remote_endpoint () <<
             " contained " << list.size () <<
             ((list.size() > 1) ? " entries" : " entry");
         SharedState::Access state (m_state);
         // The object must exist in our table
         assert (state->slots.find (slot->remote_endpoint ()) !=
             state->slots.end ());
         // Must be handshaked!
         assert (slot->state() == Slot::active);
         preprocess (slot, list, state);
         clock_type::time_point const now (m_clock.now());
         for (auto iter (list.cbegin()); iter != list.cend(); ++iter)
         {
             Endpoint const& ep (*iter);
             assert (ep.hops != 0);
             slot->recent.insert (ep.address, ep.hops);
             // Note hops has been incremented, so 1
             // means a directly connected neighbor.
             //
             if (ep.hops == 1)
             {
                 if (slot->connectivityCheckInProgress)
                 {
                     if (m_journal.warning) m_journal.warning << beast::leftw (18) <<
                         "Logic testing " << ep.address << " already in progress";
                     continue;
                 }
                 if (! slot->checked)
                 {
                     // Mark that a check for this slot is now in progress.
                     slot->connectivityCheckInProgress = true;
                     // Test the slot's listening port before
                     // adding it to the livecache for the first time.
                     //
                     m_checker.async_test (ep.address, bind (
                         &Logic::checkComplete, this, slot->remote_endpoint (),
                             ep.address, beast::_1));
                     // Note that we simply discard the first Endpoint
                     // that the neighbor sends when we perform the
                     // listening test. They will just send us another
                     // one in a few seconds.
                     continue;
                 }
                 // If they failed the test then skip the address
                 if (! slot->canAccept)
                     continue;
             }
             // We only add to the livecache if the neighbor passed the
             // listening test, else we silently drop their messsage
             // since their listening port is misconfigured.
             //
             state->livecache.insert (ep);
             state->bootcache.insert (ep.address);
         }
         slot->whenAcceptEndpoints = now + Tuning::secondsPerMessage;
     }
void ripple::PeerFinder::Logic::on_handshake (SlotImp::ptr const & slot, RipplePublicKey const & key, bool cluster) inline
Definition at line 383 of file Logic.h.
References ripple::PeerFinder::Slot::accept, ripple::PeerFinder::Callback::activate(), ripple::PeerFinder::Slot::connected, beast::Journal::debug, ripple::PeerFinder::Callback::disconnect(), m_callback, m_clock, m_journal, m_state, beast::abstract_clock< Duration >::now(), redirect(), state(), and beast::Journal::trace.
Referenced by ripple::PeerFinder::ManagerImp::on_handshake().
     {
         if (m_journal.debug) m_journal.debug << beast::leftw (18) <<
             "Logic handshake " << slot->remote_endpoint () <<
             " with " << (cluster ? "clustered " : "") << "key " << key;
         SharedState::Access state (m_state);
         // The object must exist in our table
         assert (state->slots.find (slot->remote_endpoint ()) !=
             state->slots.end ());
         // Must be accepted or connected
         assert (slot->state() == Slot::accept ||
             slot->state() == Slot::connected);
         // Check for duplicate connection by key
         if (state->keys.find (key) != state->keys.end())
         {
             m_callback.disconnect (slot, true);
             return;
         }
         // See if we have an open space for this slot
         if (state->counts.can_activate (*slot))
         {
             // Set key and cluster right before adding to the map
             // otherwise we could assert later when erasing the key.
             state->counts.remove (*slot);
             slot->public_key (key);
             slot->cluster (cluster);
             state->counts.add (*slot);
             // Add the public key to the active set
             std::pair <Keys::iterator, bool> const result (
                 state->keys.insert (key));
             // Public key must not already exist
             assert (result.second);
             // Change state and update counts
             state->counts.remove (*slot);
             slot->activate (m_clock.now ());
             state->counts.add (*slot);
             if (! slot->inbound())
                 state->bootcache.on_success (
                     slot->remote_endpoint());
             // Mark fixed slot success
             if (slot->fixed() && ! slot->inbound())
             {
                 auto iter (state->fixed.find (slot->remote_endpoint()));
                 assert (iter != state->fixed.end ());
                 iter->second.success (m_clock.now ());
                 if (m_journal.trace) m_journal.trace << beast::leftw (18) <<
                     "Logic fixed " << slot->remote_endpoint () << " success";
             }
             m_callback.activate (slot);
         }
         else
         {
             if (! slot->inbound())
                 state->bootcache.on_success (
                     slot->remote_endpoint());
             // Maybe give them some addresses to try
             if (slot->inbound ())
                 redirect (slot, state);
             m_callback.disconnect (slot, true);
         }
     }
void ripple::PeerFinder::Logic::on_legacy_endpoints (IPAddresses const & list) inline
Definition at line 609 of file Logic.h.
References m_state, and state().
Referenced by ripple::PeerFinder::ManagerImp::on_legacy_endpoints().
     {
         // Ignoring them also seems a valid choice.
         SharedState::Access state (m_state);
         for (IPAddresses::const_iterator iter (list.begin());
             iter != list.end(); ++iter)
             state->bootcache.insert (*iter);
     }
void ripple::PeerFinder::Logic::onWrite (beast::PropertyStream::Map & map) inline
Definition at line 1141 of file Logic.h.
References m_state, state(), and writeSlots().
Referenced by ripple::PeerFinder::ManagerImp::onWrite().
     {
         SharedState::Access state (m_state);
         // VFALCO NOTE These ugly casts are needed because
         //             of how std::size_t is declared on some linuxes
         //
         map ["bootcache"]   = std::uint32_t (state->bootcache.size());
         map ["fixed"]       = std::uint32_t (state->fixed.size());
         {
             beast::PropertyStream::Set child ("peers", map);
             writeSlots (child, state->slots);
         }
         {
             beast::PropertyStream::Map child ("counts", map);
             state->counts.onWrite (child);
         }
         {
             beast::PropertyStream::Map child ("config", map);
             state->config.onWrite (child);
         }
         {
             beast::PropertyStream::Map child ("livecache", map);
             state->livecache.onWrite (child);
         }
         {
             beast::PropertyStream::Map child ("bootcache", map);
             state->bootcache.onWrite (child);
         }
     }
void ripple::PeerFinder::Logic::periodicActivity () inline
Definition at line 911 of file Logic.h.
References autoconnect(), broadcast(), expire(), m_clock, m_state, m_whenBroadcast, beast::abstract_clock< Duration >::now(), ripple::PeerFinder::Tuning::secondsPerMessage(), and state().
Referenced by ripple::PeerFinder::ManagerImp::onDeadlineTimer().
     {
         SharedState::Access state (m_state);
         clock_type::time_point const now (m_clock.now());
         autoconnect ();
         expire ();
         state->bootcache.periodicActivity ();
         if (m_whenBroadcast <= now)
         {
             broadcast ();
             m_whenBroadcast = now + Tuning::secondsPerMessage;
         }
     }
void ripple::PeerFinder::Logic::preprocess (SlotImp::ptr const & slot, Endpoints & list, SharedState::Access & state) inline
Definition at line 460 of file Logic.h.
References ripple::PeerFinder::Endpoint::address, beast::IP::Endpoint::address(), beast::IP::Endpoint::at_port(), ripple::PeerFinder::Endpoint::hops, is_valid_address(), m_journal, ripple::PeerFinder::Tuning::maxHops, beast::IP::Endpoint::port(), and beast::Journal::warning.
Referenced by on_endpoints().
     {
         bool neighbor (false);
         for (auto iter (list.begin()); iter != list.end();)
         {
             Endpoint& ep (*iter);
             // Enforce hop limit
             if (ep.hops > Tuning::maxHops)
             {
                 if (m_journal.warning) m_journal.warning << beast::leftw (18) <<
                     "Endpoints drop " << ep.address <<
                     " for excess hops " << ep.hops;
                 iter = list.erase (iter);
                 continue;
             }
             // See if we are directly connected
             if (ep.hops == 0)
             {
                 if (! neighbor)
                 {
                     // Fill in our neighbors remote address
                     neighbor = true;
                     ep.address = slot->remote_endpoint().at_port (
                         ep.address.port ());
                 }
                 else
                 {
                     if (m_journal.warning) m_journal.warning << beast::leftw (18) <<
                         "Endpoints drop " << ep.address <<
                         " for extra self";
                     iter = list.erase (iter);
                     continue;
                 }
             }
             // Discard invalid addresses
             if (! is_valid_address (ep.address))
             {
                 if (m_journal.warning) m_journal.warning << beast::leftw (18) <<
                     "Endpoints drop " << ep.address <<
                     " as invalid";
                 iter = list.erase (iter);
                 continue;
             }
             // Filter duplicates
             if (std::any_of (list.begin(), iter,
                 [ep](Endpoints::value_type const& other)
                 {
                     return ep.address == other.address;
                 }))
             {
                 if (m_journal.warning) m_journal.warning << beast::leftw (18) <<
                     "Endpoints drop " << ep.address <<
                     " as duplicate";
                 iter = list.erase (iter);
                 continue;
             }
             // Increment hop count on the incoming message, so
             // we store it at the hop count we will send it at.
             //
             ++ep.hops;
             ++iter;
         }
     }
void ripple::PeerFinder::Logic::redirect (SlotImp::ptr const & slot, SharedState::Access & state) inline
Definition at line 1021 of file Logic.h.
References ripple::PeerFinder::handout(), ripple::PeerFinder::RedirectHandouts::list(), m_callback, m_journal, ripple::PeerFinder::Callback::send(), beast::Journal::trace, and beast::Journal::warning.
Referenced by on_handshake().
     {
         RedirectHandouts h (slot);
         state->livecache.hops.shuffle();
         handout (&h, (&h)+1,
             state->livecache.hops.begin(),
                 state->livecache.hops.end());
         if (! h.list().empty ())
         {
             if (m_journal.trace) m_journal.trace << beast::leftw (18) <<
                 "Logic redirect " << slot->remote_endpoint() <<
                 " with " << h.list().size() <<
                 ((h.list().size() == 1) ? " address" : " addresses");
             m_callback.send (slot, h.list());
         }
         else
         {
             if (m_journal.warning) m_journal.warning << beast::leftw (18) <<
                 "Logic deferred " << slot->remote_endpoint();
         }
     }
void ripple::PeerFinder::Logic::remove (SlotImp::ptr const & slot, SharedState::Access & state) inline
Definition at line 618 of file Logic.h.
     {
         Slots::iterator const iter (state->slots.find (
             slot->remote_endpoint ()));
         // The slot must exist in the table
         assert (iter != state->slots.end ());
         // Remove from slot by IP table
         state->slots.erase (iter);
         // Remove the key if present
         if (slot->public_key () != boost::none)
         {
             Keys::iterator const iter (state->keys.find (*slot->public_key()));
             // Key must exist
             assert (iter != state->keys.end ());
             state->keys.erase (iter);
         }
         // Remove from connected address table
         {
             auto const iter (state->connected_addresses.find (
                 slot->remote_endpoint().at_port (0)));
             // Address must exist
             assert (iter != state->connected_addresses.end ());
             state->connected_addresses.erase (iter);
         }
         // Update counts
         state->counts.remove (*slot);
     }
void ripple::PeerFinder::Logic::setConfig (Config const & config) inline
Definition at line 175 of file Logic.h.
References m_state, and state().
Referenced by Logic(), and ripple::PeerFinder::ManagerImp::setConfig().
     {
         SharedState::Access state (m_state);
         state->config = config;
         state->counts.onConfig (state->config);
     }
void ripple::PeerFinder::Logic::squelch_slots (SharedState::Access & state) inline
Definition at line 759 of file Logic.h.
References beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::insert(), m_squelches, and beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::touch().
Referenced by autoconnect().
     {
         for (auto const& s : state->slots)
         {
             auto const result (m_squelches.insert (
                 s.second->remote_endpoint().address()));
             if (! result.second)
                 m_squelches.touch (result.first);
         }
     }
State const& ripple::PeerFinder::Logic::state () const inline
Definition at line 1183 of file Logic.h.
References m_state.
Referenced by addBootcacheAddresses(), addFixedPeer(), autoconnect(), broadcast(), checkComplete(), expire(), fetch(), load(), new_inbound_slot(), new_outbound_slot(), on_cancel(), on_closed(), on_connected(), on_endpoints(), on_handshake(), on_legacy_endpoints(), onWrite(), periodicActivity(), setConfig(), and stop().
     {
         return *SharedState::ConstAccess (m_state);
     }
static std::string ripple::PeerFinder::Logic::stateString (Slot::State state) inline static
Definition at line 1193 of file Logic.h.
References ripple::PeerFinder::Slot::accept, ripple::PeerFinder::Slot::active, ripple::PeerFinder::Slot::closing, ripple::PeerFinder::Slot::connect, and ripple::PeerFinder::Slot::connected.
Referenced by writeSlots().
     {
         switch (state)
         {
         case Slot::accept:     return "accept";
         case Slot::connect:    return "connect";
         case Slot::connected:  return "connected";
         case Slot::active:     return "active";
         case Slot::closing:    return "closing";
         default:
             break;
         };
         return "?";
     }
void ripple::PeerFinder::Logic::stop () inline
Stop the logic. This will cancel the current fetch and set the stopping flag to true to prevent further fetches. Thread safety: Safe to call from any thread.
Definition at line 161 of file Logic.h.
References m_state, and state().
Referenced by ripple::PeerFinder::ManagerImp::onStop().
     {
         SharedState::Access state (m_state);
         state->stopping = true;
         if (state->fetchSource != nullptr)
             state->fetchSource->cancel ();
     }
void ripple::PeerFinder::Logic::writeSlots (beast::PropertyStream::Set & set, Slots const & slots) inline
Definition at line 1121 of file Logic.h.
References ripple::PeerFinder::SlotImp::cluster(), ripple::PeerFinder::SlotImp::fixed(), ripple::PeerFinder::SlotImp::inbound(), ripple::PeerFinder::SlotImp::local_endpoint(), ripple::PeerFinder::SlotImp::remote_endpoint(), ripple::PeerFinder::SlotImp::state(), stateString(), and ripple::to_string().
Referenced by onWrite().
     {
         for (auto const& entry : slots)
         {
             beast::PropertyStream::Map item (set);
             SlotImp const& slot (*entry.second);
             if (slot.local_endpoint () != boost::none)
                 item ["local_address"] = to_string (*slot.local_endpoint ());
             item ["remote_address"]   = to_string (slot.remote_endpoint ());
             if (slot.inbound())
                 item ["inbound"]    = "yes";
             if (slot.fixed())
                 item ["fixed"]      = "yes";
             if (slot.cluster())
                 item ["cluster"]    = "yes";
             item ["state"] = stateString (slot.state());
         }
     }
Member Data Documentation
Callback& ripple::PeerFinder::Logic::m_callback
Definition at line 115 of file Logic.h.
Referenced by autoconnect(), broadcast(), on_connected(), on_handshake(), and redirect().
Checker& ripple::PeerFinder::Logic::m_checker
Definition at line 117 of file Logic.h.
Referenced by on_endpoints().
clock_type& ripple::PeerFinder::Logic::m_clock
Definition at line 114 of file Logic.h.
Referenced by addFixedPeer(), get_fixed(), new_inbound_slot(), new_outbound_slot(), on_closed(), on_endpoints(), on_handshake(), and periodicActivity().
beast::Journal ripple::PeerFinder::Logic::m_journal
Definition at line 112 of file Logic.h.
Referenced by addFixedPeer(), autoconnect(), broadcast(), checkComplete(), fetch(), new_inbound_slot(), new_outbound_slot(), on_cancel(), on_closed(), on_connected(), on_endpoints(), on_handshake(), preprocess(), and redirect().
std::vector<beast::SharedPtr <Source> > ripple::PeerFinder::Logic::m_sources
Definition at line 120 of file Logic.h.
Referenced by addSource().
ConnectHandouts::Squelches ripple::PeerFinder::Logic::m_squelches
Definition at line 124 of file Logic.h.
Referenced by autoconnect(), expire(), and squelch_slots().
SharedState ripple::PeerFinder::Logic::m_state
Definition at line 113 of file Logic.h.
Referenced by addBootcacheAddresses(), addFixedPeer(), autoconnect(), broadcast(), checkComplete(), counts(), expire(), fetch(), load(), new_inbound_slot(), new_outbound_slot(), on_cancel(), on_closed(), on_connected(), on_endpoints(), on_handshake(), on_legacy_endpoints(), onWrite(), periodicActivity(), setConfig(), state(), and stop().
Store& ripple::PeerFinder::Logic::m_store
Definition at line 116 of file Logic.h.
clock_type::time_point ripple::PeerFinder::Logic::m_whenBroadcast
Definition at line 122 of file Logic.h.
Referenced by periodicActivity().
The documentation for this class was generated from the following file:
rippled/src/ripple/peerfinder/impl/Logic.h