rippled: beast::LexicalCast_test Class Reference
beast::LexicalCast_test Class Reference
Public Member Functions
template<class IntType >
void testInteger (IntType in)
template<class IntType >
void testIntegers (Random &r)
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Static Public Member Functions
template<class IntType >
static IntType nextRandomInt (Random &r)
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 61 of file LexicalCast.cpp.
Member Function Documentation
template<class IntType > static IntType beast::LexicalCast_test::nextRandomInt (Random & r) inline static
Definition at line 65 of file LexicalCast.cpp.
References beast::Random::nextInt64().
     {
         return static_cast <IntType> (r.nextInt64 ());
     }
void beast::LexicalCast_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 108 of file LexicalCast.cpp.
     {
         std::int64_t const seedValue = 50;
         Random r (seedValue);
         testIntegers <int> (r);
         testIntegers <unsigned int> (r);
         testIntegers <short> (r);
         testIntegers <unsigned short> (r);
         testIntegers <std::int32_t> (r);
         testIntegers <std::uint32_t> (r);
         testIntegers <std::int64_t> (r);
         testIntegers <std::uint64_t> (r);
     }
template<class IntType > void beast::LexicalCast_test::testInteger (IntType in) inline
Definition at line 71 of file LexicalCast.cpp.
References beast::unit_test::suite::expect(), and beast::lexicalCastChecked().
Referenced by testIntegers().
     {
         String s;
         IntType out (in+1);
         expect (lexicalCastChecked (s, in));
         expect (lexicalCastChecked (out, s));
         expect (out == in);
     }
template<class IntType > void beast::LexicalCast_test::testIntegers (Random & r) inline
Definition at line 82 of file LexicalCast.cpp.
References ripple::max(), ripple::min(), name, beast::unit_test::suite::testcase(), testInteger(), and value.
     {
         {
             std::stringstream ss;
             ss <<
                 "random " << typeid (IntType).name ();
             testcase (ss.str());
             for (int i = 0; i < 1000; ++i)
             {
                 IntType const value (nextRandomInt <IntType> (r));
                 testInteger (value);
             }
         }
         {
             std::stringstream ss;
             ss <<
                 "numeric_limits <" << typeid (IntType).name () << ">";
             testcase (ss.str());
             testInteger (std::numeric_limits <IntType>::min ());
             testInteger (std::numeric_limits <IntType>::max ());
         }
     }
The documentation for this class was generated from the following file:
rippled/src/beast/modules/beast_core/text/LexicalCast.cpp