rippled: rocksdb::Blob Struct Reference
rocksdb::Blob Struct Reference
#include <blob_store.h>
Public Member Functions
std::string ToString () const
Blob (const std::string &blob)
Blob (uint32_t bucket_id, uint32_t offset, uint32_t size)
Blob ()
void SetOneChunk (uint32_t bucket_id, uint32_t offset, uint32_t size)
uint32_t Size () const
Public Attributes
std::vector< BlobChunk > chunks
Detailed Description
Definition at line 41 of file blob_store.h.
Constructor & Destructor Documentation
rocksdb::Blob::Blob (const std::string & blob) explicit
Definition at line 38 of file blob_store.cc.
References rocksdb::DecodeFixed32().
{
   for (uint32_t i = 0; i < blob.size(); ) {
     uint32_t t[3] = {0};
     for (int j = 0; j < 3 && i + sizeof(uint32_t) - 1 < blob.size();
                     ++j, i += sizeof(uint32_t)) {
       t[j] = DecodeFixed32(blob.data() + i);
     }
     chunks.push_back(BlobChunk(t[0], t[1], t[2]));
   }
 }
rocksdb::Blob::Blob (uint32_t bucket_id, uint32_t offset, uint32_t size) inline
Definition at line 47 of file blob_store.h.
References SetOneChunk().
{
     SetOneChunk(bucket_id, offset, size);
   }
rocksdb::Blob::Blob () inline
Definition at line 50 of file blob_store.h.
 {}
Member Function Documentation
void rocksdb::Blob::SetOneChunk (uint32_t bucket_id, uint32_t offset, uint32_t size) inline
Definition at line 52 of file blob_store.h.
References chunks.
Referenced by Blob().
{
     chunks.clear();
     chunks.push_back(BlobChunk(bucket_id, offset, size));
   }
uint32_t rocksdb::Blob::Size () const inline
Definition at line 57 of file blob_store.h.
References chunks.
Referenced by rocksdb::BlobStore::Get().
                         { // in blocks
     uint32_t ret = 0;
     for (auto chunk : chunks) {
       ret += chunk.size;
     }
     assert(ret > 0);
     return ret;
   }
string rocksdb::Blob::ToString () const
Definition at line 28 of file blob_store.cc.
References rocksdb::PutFixed32().
Referenced by rocksdb::TEST().
{
   string ret;
   for (auto chunk : chunks) {
     PutFixed32(&ret, chunk.bucket_id);
     PutFixed32(&ret, chunk.offset);
     PutFixed32(&ret, chunk.size);
   }
   return ret;
 }
Member Data Documentation
std::vector<BlobChunk> rocksdb::Blob::chunks
Definition at line 67 of file blob_store.h.
Referenced by rocksdb::FreeList::Allocate(), rocksdb::FreeList::Free(), rocksdb::BlobStore::Get(), rocksdb::FreeList::Overlap(), rocksdb::BlobStore::Put(), SetOneChunk(), Size(), and rocksdb::TEST().
The documentation for this struct was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/util/blob_store.h
rippled/src/ripple/rocksdb/rocksdb/util/blob_store.cc