rippled: ripple::STUInt8 Class Reference
ripple::STUInt8 Class Reference
#include <SerializedTypes.h>
Public Member Functions
STUInt8 (unsigned char v=0)
STUInt8 (SField::ref n, unsigned char v=0)
SerializedTypeID getSType () const
std::string getText () const
Json::Value getJson (int) const
void add (Serializer &s) const
unsigned char getValue () const
void setValue (unsigned char v)
operator unsigned char () const
virtual bool isEquivalent (const SerializedType &t) const
virtual bool isDefault () const
Public Member Functions inherited from ripple::SerializedType
SerializedType ()
SerializedType (SField::ref n)
virtual ~SerializedType ()
void setFName (SField::ref n)
SField::ref getFName () const
std::string getName () const
std::unique_ptr< SerializedType > clone () const
virtual std::string getFullText () const
void addFieldID (Serializer &s) const
SerializedType & operator= (const SerializedType &t)
bool operator== (const SerializedType &t) const
bool operator!= (const SerializedType &t) const
template<class D >
D & downcast ()
template<class D >
D const & downcast () const
Static Public Member Functions
static std::unique_ptr
< SerializedType > deserialize (SerializerIterator &sit, SField::ref name)
Static Public Member Functions inherited from ripple::SerializedType
static std::unique_ptr
< SerializedType > deserialize (SField::ref name)
Private Member Functions
STUInt8 * duplicate () const
Static Private Member Functions
static STUInt8 * construct (SerializerIterator &, SField::ref f)
Private Attributes
unsigned char value
Additional Inherited Members
Protected Attributes inherited from ripple::SerializedType
SField::ptr fName
Detailed Description
Definition at line 221 of file SerializedTypes.h.
Constructor & Destructor Documentation
ripple::STUInt8::STUInt8 (unsigned char v = 0) inline
Definition at line 225 of file SerializedTypes.h.
Referenced by construct(), and duplicate().
                                   : value (v)
     {
         ;
     }
ripple::STUInt8::STUInt8 (SField::ref n, unsigned char v = 0) inline
Definition at line 229 of file SerializedTypes.h.
                                                : SerializedType (n), value (v)
     {
         ;
     }
Member Function Documentation
void ripple::STUInt8::add (Serializer & s) const inline virtual
Reimplemented from ripple::SerializedType.
Definition at line 244 of file SerializedTypes.h.
References ripple::Serializer::add8(), and value.
     {
         s.add8 (value);
     }
STUInt8 * ripple::STUInt8::construct (SerializerIterator & u, SField::ref f) static private
Definition at line 101 of file SerializedTypes.cpp.
References ripple::SerializerIterator::get8(), and STUInt8().
Referenced by deserialize().
 {
     return new STUInt8 (name, u.get8 ());
 }
static std::unique_ptr<SerializedType> ripple::STUInt8::deserialize (SerializerIterator & sit, SField::ref name) inline static
Definition at line 233 of file SerializedTypes.h.
References construct().
Referenced by ripple::STObject::makeDeserializedObject().
     {
         return std::unique_ptr<SerializedType> (construct (sit, name));
     }
STUInt8* ripple::STUInt8::duplicate () const inline private virtual
Reimplemented from ripple::SerializedType.
Definition at line 271 of file SerializedTypes.h.
References STUInt8().
     {
         return new STUInt8 (*this);
     }
Json::Value ripple::STUInt8::getJson (int) const virtual
Reimplemented from ripple::SerializedType.
Definition at line 119 of file SerializedTypes.cpp.
References ripple::SerializedType::getFName(), ripple::lsWARNING, ripple::transResultInfo(), value, and WriteLog.
 {
     if (getFName () == sfTransactionResult)
     {
         std::string token, human;
         if (transResultInfo (static_cast<TER> (value), token, human))
             return token;
         else
             WriteLog (lsWARNING, SerializedType) << "Unknown result code in metadata: " << value;
     }
     return value;
 }
SerializedTypeID ripple::STUInt8::getSType () const inline virtual
Reimplemented from ripple::SerializedType.
Definition at line 238 of file SerializedTypes.h.
     {
         return STI_UINT8;
     }
std::string ripple::STUInt8::getText () const virtual
Reimplemented from ripple::SerializedType.
Definition at line 106 of file SerializedTypes.cpp.
References ripple::SerializedType::getFName(), ripple::transResultInfo(), and value.
 {
     if (getFName () == sfTransactionResult)
     {
         std::string token, human;
         if (transResultInfo (static_cast<TER> (value), token, human))
             return human;
     }
     return beast::lexicalCastThrow <std::string> (value);
 }
unsigned char ripple::STUInt8::getValue () const inline
Definition at line 249 of file SerializedTypes.h.
References value.
Referenced by ripple::STObject::getFieldU8().
     {
         return value;
     }
virtual bool ripple::STUInt8::isDefault () const inline virtual
Reimplemented from ripple::SerializedType.
Definition at line 263 of file SerializedTypes.h.
References value.
     {
         return value == 0;
     }
bool ripple::STUInt8::isEquivalent (const SerializedType & t) const virtual
Reimplemented from ripple::SerializedType.
Definition at line 134 of file SerializedTypes.cpp.
References value.
 {
     const STUInt8* v = dynamic_cast<const STUInt8*> (&t);
     return v && (value == v->value);
 }
ripple::STUInt8::operator unsigned char () const inline
Definition at line 258 of file SerializedTypes.h.
References value.
     {
         return value;
     }
void ripple::STUInt8::setValue (unsigned char v) inline
Definition at line 253 of file SerializedTypes.h.
References value.
Referenced by ripple::STObject::setFieldU8().
     {
         value = v;
     }
Member Data Documentation
unsigned char ripple::STUInt8::value private
Definition at line 269 of file SerializedTypes.h.
Referenced by add(), getJson(), getText(), getValue(), isDefault(), isEquivalent(), operator unsigned char(), and setValue().
The documentation for this class was generated from the following files:
rippled/src/ripple_data/protocol/SerializedTypes.h
rippled/src/ripple_data/protocol/SerializedTypes.cpp