rippled: beast::BSDStatsHelpers Namespace Reference
beast::BSDStatsHelpers Namespace Reference
Functions
String getDmesgInfo (const char *const key)
Function Documentation
String beast::BSDStatsHelpers::getDmesgInfo (const char *const key)
Definition at line 214 of file bsd_SystemStats.cpp.
References beast::String::empty, beast::File::readLines(), and beast::StringArray::size().
Referenced by beast::SystemStats::getCpuSpeedInMegaherz(), beast::SystemStats::getCpuVendor(), and beast::CPUInformation::initialise().
     {
         StringArray lines;
         File ("/var/run/dmesg.boot").readLines (lines);
         for (int i = lines.size(); --i >= 0;) // (NB - it's important that this runs in reverse order)
             if (lines[i].startsWith (key))
                 return lines[i].substring (strlen (key)).trim();
         return String::empty;
     }