rippled: beast::asio::HandshakeDetectLogic Class Reference
beast::asio::HandshakeDetectLogic Class Reference abstract
#include <HandshakeDetectLogic.h>
Public Member Functions
HandshakeDetectLogic ()
virtual std::size_t max_needed ()=0
virtual std::size_t bytes_consumed ()=0
bool finished () const noexcept
bool success () const noexcept
Protected Member Functions
void conclude (bool success=true)
void fail ()
Private Attributes
bool m_finished
bool m_success
Detailed Description
Definition at line 26 of file HandshakeDetectLogic.h.
Constructor & Destructor Documentation
beast::asio::HandshakeDetectLogic::HandshakeDetectLogic () inline
Definition at line 29 of file HandshakeDetectLogic.h.
         : m_finished (false)
         , m_success (false)
     {
     }
Member Function Documentation
virtual std::size_t beast::asio::HandshakeDetectLogic::bytes_consumed () pure virtual
How many bytes the handshake consumes. If the detector processes the entire handshake this will be non zero. The SSL detector would return 0, since we want all the existing bytes to be passed on.
Implemented in beast::asio::HandshakeDetectLogicPROXY, beast::asio::HandshakeDetectLogicSSL2, and beast::asio::HandshakeDetectLogicSSL3.
void beast::asio::HandshakeDetectLogic::conclude (bool success = true) inline protected
Definition at line 70 of file HandshakeDetectLogic.h.
References m_finished, m_success, and success().
Referenced by beast::asio::HandshakeDetectLogicSSL3::analyze(), beast::asio::HandshakeDetectLogicSSL2::analyze(), beast::asio::HandshakeDetectLogicPROXY::analyze(), and fail().
     {
         m_finished = true;
         m_success = success;
     }
void beast::asio::HandshakeDetectLogic::fail () inline protected
Definition at line 76 of file HandshakeDetectLogic.h.
References conclude().
Referenced by beast::asio::HandshakeDetectLogicSSL3::analyze(), beast::asio::HandshakeDetectLogicSSL2::analyze(), and ldb_test.LDBTestCase::assertRunFAILFull().
     {
         conclude (false);
     }
bool beast::asio::HandshakeDetectLogic::finished () const inline noexcept
Return true if we have enough data to form a conclusion.
Definition at line 57 of file HandshakeDetectLogic.h.
References m_finished.
Referenced by ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::async_handshake().
     {
         return m_finished;
     }
virtual std::size_t beast::asio::HandshakeDetectLogic::max_needed () pure virtual
How many bytes maximum we might need.
This is the largest number of bytes that the detector might need in order to come to a conclusion about whether or not the handshake is a match. Depending on the data, it could come to that conclusion sooner though.
Use read_some instead of read so that the detect logic can reject the handshake sooner if possible.
Implemented in beast::asio::HandshakeDetectLogicPROXY, beast::asio::HandshakeDetectLogicSSL2, and beast::asio::HandshakeDetectLogicSSL3.
bool beast::asio::HandshakeDetectLogic::success () const inline noexcept
Return true if we came to a conclusion and the data matched.
Definition at line 64 of file HandshakeDetectLogic.h.
References m_finished, and m_success.
Referenced by ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::async_handshake(), and conclude().
     {
         return m_finished && m_success;
     }
Member Data Documentation
bool beast::asio::HandshakeDetectLogic::m_finished private
Definition at line 82 of file HandshakeDetectLogic.h.
Referenced by conclude(), finished(), and success().
bool beast::asio::HandshakeDetectLogic::m_success private
Definition at line 83 of file HandshakeDetectLogic.h.
Referenced by conclude(), and success().
The documentation for this class was generated from the following file:
rippled/src/beast/modules/beast_asio/protocol/HandshakeDetectLogic.h