rippled: rocksdb::FindFileTest Class Reference
rocksdb::FindFileTest Class Reference
Public Member Functions
FindFileTest ()
~FindFileTest ()
void Add (const char *smallest, const char *largest, SequenceNumber smallest_seq=100, SequenceNumber largest_seq=100)
int Find (const char *key)
bool Overlaps (const char *smallest, const char *largest)
Public Attributes
std::vector< FileMetaData * > files_
bool disjoint_sorted_files_
Detailed Description
Definition at line 17 of file version_set_test.cc.
Constructor & Destructor Documentation
rocksdb::FindFileTest::FindFileTest () inline
Definition at line 22 of file version_set_test.cc.
 : disjoint_sorted_files_(true) { }
rocksdb::FindFileTest::~FindFileTest () inline
Definition at line 24 of file version_set_test.cc.
References files_.
                   {
     for (unsigned int i = 0; i < files_.size(); i++) {
       delete files_[i];
     }
   }
Member Function Documentation
void rocksdb::FindFileTest::Add (const char * smallest, const char * largest, SequenceNumber smallest_seq = 100, SequenceNumber largest_seq = 100) inline
Definition at line 30 of file version_set_test.cc.
References ripple::f, files_, rocksdb::kTypeValue, rocksdb::FileMetaData::largest, rocksdb::FileMetaData::number, and rocksdb::FileMetaData::smallest.
{
     FileMetaData* f = new FileMetaData;
     f->number = files_.size() + 1;
     f->smallest = InternalKey(smallest, smallest_seq, kTypeValue);
     f->largest = InternalKey(largest, largest_seq, kTypeValue);
     files_.push_back(f);
   }
int rocksdb::FindFileTest::Find (const char * key) inline
Definition at line 40 of file version_set_test.cc.
References rocksdb::BytewiseComparator(), rocksdb::InternalKey::Encode(), files_, rocksdb::FindFile(), and rocksdb::kTypeValue.
{
     InternalKey target(key, 100, kTypeValue);
     InternalKeyComparator cmp(BytewiseComparator());
     return FindFile(cmp, files_, target.Encode());
   }
bool rocksdb::FindFileTest::Overlaps (const char * smallest, const char * largest) inline
Definition at line 46 of file version_set_test.cc.
References rocksdb::BytewiseComparator(), disjoint_sorted_files_, files_, and rocksdb::SomeFileOverlapsRange().
{
     InternalKeyComparator cmp(BytewiseComparator());
     Slice s(smallest != nullptr ? smallest : "");
     Slice l(largest != nullptr ? largest : "");
     return SomeFileOverlapsRange(cmp, disjoint_sorted_files_, files_,
                                  (smallest != nullptr ? &s : nullptr),
                                  (largest != nullptr ? &l : nullptr));
   }
Member Data Documentation
bool rocksdb::FindFileTest::disjoint_sorted_files_
Definition at line 20 of file version_set_test.cc.
Referenced by Overlaps().
std::vector<FileMetaData*> rocksdb::FindFileTest::files_
Definition at line 19 of file version_set_test.cc.
Referenced by Add(), Find(), Overlaps(), and ~FindFileTest().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/db/version_set_test.cc