rippled: beast::Sha256 Namespace Reference
beast::Sha256 Namespace Reference
Namespaces
detail
Classes
class Context
Typedefs
typedef std::array
< std::uint8_t, digestLength > digest_type
Enumerations
enum { digestLength = 32, blockLength = 64 }
Functions
digest_type const & empty_digest ()
void * hash (void const *buffer, std::size_t bytes, void *digest)
digest_type & hash (void const *buffer, std::size_t bytes, digest_type &digest)
digest_type hash (void const *buffer, std::size_t bytes)
void * hash (std::int8_t const *begin, std::int8_t const *end, void *digest)
void * hash (std::uint8_t const *begin, std::uint8_t const *end, void *digest)
digest_type hash (std::int8_t const *begin, std::int8_t const *end)
digest_type hash (std::uint8_t const *begin, std::uint8_t const *end)
template<typename T >
void * hash (T const &t, void *digest)
template<typename T >
digest_type & hash (T const &t, digest_type &digest)
template<typename T >
digest_type hash (T const &t)
void * hash (void const *source_digest, void *digest)
digest_type & hash (void const *source_digest, digest_type &digest)
digest_type hash (void const *source_digest)
Typedef Documentation
typedef std::array<std::uint8_t, digestLength> beast::Sha256::digest_type
A container suitable for holding the resulting hash.
Definition at line 40 of file Sha256.h.
Enumeration Type Documentation
anonymous enum
Enumerator
digestLength
blockLength
Definition at line 33 of file Sha256.h.
 {
     digestLength = 32,
     blockLength = 64
 };
Function Documentation
digest_type const & beast::Sha256::empty_digest ()
Returns the hash produced by a single octet equal to zero.
Definition at line 63 of file Sha256.cpp.
 {
     struct Holder
     {
         Holder ()
         {
             std::uint8_t zero (0);
             hash (zero, digest);
         }
         digest_type digest;
     };
     static Holder const holder;
     return holder.digest;
 }
void * beast::Sha256::hash (void const * buffer, std::size_t bytes, void * digest)
Performs an entire hashing operation in a single step. A zero length input sequence produces the empty_digest().
Returns
The resulting digest depending on the arguments.
Definition at line 81 of file Sha256.cpp.
References beast::Sha256::Context::finish(), and beast::Sha256::Context::update().
Referenced by ripple::CryptoIdentifier< 33, 35, true >::construct(), hash(), and beast::hardened_hash_sha256_test::testSHA256().
 {
     Context h;
     h.update (buffer, bytes);
     h.finish (digest);
     return digest;
 }
digest_type & beast::Sha256::hash (void const * buffer, std::size_t bytes, digest_type & digest)
Definition at line 89 of file Sha256.cpp.
References hash().
 {
     hash (buffer, bytes, digest.data());
     return digest;
 }
digest_type beast::Sha256::hash (void const * buffer, std::size_t bytes)
Definition at line 95 of file Sha256.cpp.
References hash().
 {
     digest_type digest;
     hash (buffer, bytes, digest);
     return digest;
 }
void * beast::Sha256::hash (std::int8_t const * begin, std::int8_t const * end, void * digest)
Definition at line 102 of file Sha256.cpp.
References hash().
 {
     return hash (begin, end - begin, digest);
 }
void * beast::Sha256::hash (std::uint8_t const * begin, std::uint8_t const * end, void * digest)
Definition at line 107 of file Sha256.cpp.
 {
     return hash (begin, end - begin, digest);
 }
digest_type beast::Sha256::hash (std::int8_t const * begin, std::int8_t const * end)
Definition at line 112 of file Sha256.cpp.
 {
     digest_type digest;
     hash (begin, end - begin, digest);
     return digest;
 }
digest_type beast::Sha256::hash (std::uint8_t const * begin, std::uint8_t const * end)
Definition at line 119 of file Sha256.cpp.
References hash().
 {
     digest_type digest;
     hash (begin, end - begin, digest);
     return digest;
 }
template<typename T > void* beast::Sha256::hash (T const & t, void * digest)
Definition at line 124 of file Sha256.h.
References hash(), and T.
 {
     return hash (&t, sizeof(T), digest);
 }
void * beast::Sha256::hash (void const * source_digest, void * digest)
Calculate the hash of a hash in one step. The memory pointed to by source_digest must be at least digestLength bytes or undefined behavior results.
Definition at line 126 of file Sha256.cpp.
References digestLength, and hash().
 {
     return hash (source_digest, digestLength, digest);
 }
template<typename T > digest_type& beast::Sha256::hash (T const & t, digest_type & digest)
Definition at line 130 of file Sha256.h.
References hash(), and T.
 {
     return hash (&t, sizeof(T), digest);
 }
digest_type & beast::Sha256::hash (void const * source_digest, digest_type & digest)
Definition at line 131 of file Sha256.cpp.
References digestLength, and hash().
 {
     return hash (source_digest, digestLength, digest);
 }
template<typename T > digest_type beast::Sha256::hash (T const & t)
Definition at line 136 of file Sha256.h.
References hash(), and T.
 {
     digest_type digest;
     hash (&t, sizeof(T), digest);
     return digest;
 }
digest_type beast::Sha256::hash (void const * source_digest)
Definition at line 136 of file Sha256.cpp.
 {
     digest_type digest;
     hash (source_digest, digestLength, digest);
     return digest;
 }