rippled: rocksdb::ScanCommand Class Reference
rocksdb::ScanCommand Class Reference
#include <ldb_cmd.h>
Public Member Functions
ScanCommand (const vector< string > &params, const map< string, string > &options, const vector< string > &flags)
virtual void DoCommand ()
Public Member Functions inherited from rocksdb::LDBCommand
bool ValidateCmdLineOptions ()
virtual Options PrepareOptionsForOpenDB ()
virtual void SetOptions (Options options)
virtual bool NoDBOpen ()
virtual ~LDBCommand ()
void Run ()
LDBCommandExecuteResult GetExecuteState ()
void ClearPreviousRunState ()
Static Public Member Functions
static string Name ()
static void Help (string &ret)
Static Public Member Functions inherited from rocksdb::LDBCommand
static LDBCommand * InitFromCmdLineArgs (const vector< string > &args, const Options &options=Options())
static LDBCommand * InitFromCmdLineArgs (int argc, char **argv, const Options &options=Options())
static string HexToString (const string &str)
static string StringToHex (const string &str)
Private Attributes
string start_key_
string end_key_
bool start_key_specified_
bool end_key_specified_
int max_keys_scanned_
Additional Inherited Members
Static Public Attributes inherited from rocksdb::LDBCommand
static const string ARG_DB = "db"
static const string ARG_HEX = "hex"
static const string ARG_KEY_HEX = "key_hex"
static const string ARG_VALUE_HEX = "value_hex"
static const string ARG_TTL = "ttl"
static const string ARG_TTL_START = "start_time"
static const string ARG_TTL_END = "end_time"
static const string ARG_TIMESTAMP = "timestamp"
static const string ARG_FROM = "from"
static const string ARG_TO = "to"
static const string ARG_MAX_KEYS = "max_keys"
static const string ARG_BLOOM_BITS = "bloom_bits"
static const string ARG_COMPRESSION_TYPE = "compression_type"
static const string ARG_BLOCK_SIZE = "block_size"
static const string ARG_AUTO_COMPACTION = "auto_compaction"
static const string ARG_WRITE_BUFFER_SIZE = "write_buffer_size"
static const string ARG_FILE_SIZE = "file_size"
static const string ARG_CREATE_IF_MISSING = "create_if_missing"
static const char * DELIM = " ==> "
Protected Member Functions inherited from rocksdb::LDBCommand
bool ParseKeyValue (const string &line, string *key, string *value, bool is_key_hex, bool is_value_hex)
LDBCommand (const map< string, string > &options, const vector< string > &flags, bool is_read_only, const vector< string > &valid_cmd_line_options)
void OpenDB ()
void CloseDB ()
vector< string > BuildCmdLineOptions (vector< string > options)
bool ParseIntOption (const map< string, string > &options, const string &option, int &value, LDBCommandExecuteResult &exec_state)
bool ParseStringOption (const map< string, string > &options, const string &option, string *value)
Static Protected Member Functions inherited from rocksdb::LDBCommand
static string PrintKeyValue (const string &key, const string &value, bool is_key_hex, bool is_value_hex)
static string PrintKeyValue (const string &key, const string &value, bool is_hex)
static bool IsFlagPresent (const vector< string > &flags, const string &flag)
static string HelpRangeCmdArgs ()
Protected Attributes inherited from rocksdb::LDBCommand
LDBCommandExecuteResult exec_state_
string db_path_
DB * db_
StackableDB * sdb_
bool is_read_only_
bool is_key_hex_
bool is_value_hex_
bool is_db_ttl_
bool timestamp_
const map< string, string > option_map_
const vector< string > flags_
const vector< string > valid_cmd_line_options_
Options options_
Detailed Description
Definition at line 615 of file ldb_cmd.h.
Constructor & Destructor Documentation
rocksdb::ScanCommand::ScanCommand (const vector< string > & params, const map< string, string > & options, const vector< string > & flags)
Member Function Documentation
void rocksdb::ScanCommand::DoCommand () virtual
Implements rocksdb::LDBCommand.
Definition at line 1548 of file ldb_cmd.cc.
References rocksdb::LDBCommand::ARG_TTL_END, rocksdb::LDBCommand::ARG_TTL_START, rocksdb::LDBCommand::db_, end_key_, end_key_specified_, rocksdb::LDBCommand::exec_state_, rocksdb::LDBCommandExecuteResult::FAILED(), rocksdb::LDBCommand::is_db_ttl_, rocksdb::LDBCommand::is_key_hex_, rocksdb::LDBCommand::is_value_hex_, rocksdb::Iterator::key(), rocksdb::DBWithTTL::kMaxTimestamp, rocksdb::DBWithTTL::kMinTimestamp, max_keys_scanned_, rocksdb::DB::NewIterator(), rocksdb::Iterator::Next(), rocksdb::Status::ok(), rocksdb::LDBCommand::option_map_, rocksdb::LDBCommand::ParseIntOption(), rocksdb::ReadableTime(), rocksdb::Iterator::Seek(), rocksdb::Iterator::SeekToFirst(), start_key_, start_key_specified_, rocksdb::Iterator::status(), rocksdb::LDBCommand::StringToHex(), rocksdb::TtlIterator::timestamp(), rocksdb::LDBCommand::timestamp_, rocksdb::Slice::ToString(), rocksdb::Status::ToString(), rocksdb::Iterator::Valid(), and rocksdb::Iterator::value().
{
   int num_keys_scanned = 0;
   Iterator* it = db_->NewIterator(ReadOptions());
   if (start_key_specified_) {
     it->Seek(start_key_);
   } else {
     it->SeekToFirst();
   }
   int ttl_start;
   if (!ParseIntOption(option_map_, ARG_TTL_START, ttl_start, exec_state_)) {
     ttl_start = DBWithTTL::kMinTimestamp; // TTL introduction time
   }
   int ttl_end;
   if (!ParseIntOption(option_map_, ARG_TTL_END, ttl_end, exec_state_)) {
     ttl_end = DBWithTTL::kMaxTimestamp; // Max time allowed by TTL feature
   }
   if (ttl_end < ttl_start) {
     fprintf(stderr, "Error: End time can't be less than start time\n");
     delete it;
     return;
   }
   if (is_db_ttl_ && timestamp_) {
     fprintf(stdout, "Scanning key-values from %s to %s\n",
             ReadableTime(ttl_start).c_str(), ReadableTime(ttl_end).c_str());
   }
   for ( ;
         it->Valid() && (!end_key_specified_ || it->key().ToString() < end_key_);
         it->Next()) {
     string key = it->key().ToString();
     if (is_db_ttl_) {
       TtlIterator* it_ttl = dynamic_cast<TtlIterator*>(it);
       assert(it_ttl);
       int rawtime = it_ttl->timestamp();
       if (rawtime < ttl_start || rawtime >= ttl_end) {
         continue;
       }
       if (timestamp_) {
         fprintf(stdout, "%s ", ReadableTime(rawtime).c_str());
       }
     }
     string value = it->value().ToString();
     fprintf(stdout, "%s : %s\n",
           (is_key_hex_ ? StringToHex(key) : key).c_str(),
           (is_value_hex_ ? StringToHex(value) : value).c_str()
         );
     num_keys_scanned++;
     if (max_keys_scanned_ >= 0 && num_keys_scanned >= max_keys_scanned_) {
       break;
     }
   }
   if (!it->status().ok()) {  // Check for any errors found during the scan
     exec_state_ = LDBCommandExecuteResult::FAILED(it->status().ToString());
   }
   delete it;
 }
void rocksdb::ScanCommand::Help (string & ret) static
Definition at line 1536 of file ldb_cmd.cc.
References rocksdb::LDBCommand::ARG_MAX_KEYS, rocksdb::LDBCommand::ARG_TIMESTAMP, rocksdb::LDBCommand::ARG_TTL, rocksdb::LDBCommand::ARG_TTL_END, rocksdb::LDBCommand::ARG_TTL_START, rocksdb::LDBCommand::HelpRangeCmdArgs(), and Name().
Referenced by rocksdb::LDBCommandRunner::PrintHelp().
{
   ret.append("  ");
   ret.append(ScanCommand::Name());
   ret.append(HelpRangeCmdArgs());
   ret.append(" [--" + ARG_TTL + "]");
   ret.append(" [--" + ARG_TIMESTAMP + "]");
   ret.append(" [--" + ARG_MAX_KEYS + "=<N>q] ");
   ret.append(" [--" + ARG_TTL_START + "=<N>:- is inclusive]");
   ret.append(" [--" + ARG_TTL_END + "=<N>:- is exclusive]");
   ret.append("\n");
 }
static string rocksdb::ScanCommand::Name () inline static
Definition at line 617 of file ldb_cmd.h.
Referenced by Help(), and rocksdb::LDBCommand::SelectCommand().
 { return "scan"; }
Member Data Documentation
string rocksdb::ScanCommand::end_key_ private
Definition at line 628 of file ldb_cmd.h.
Referenced by DoCommand().
bool rocksdb::ScanCommand::end_key_specified_ private
Definition at line 630 of file ldb_cmd.h.
Referenced by DoCommand().
int rocksdb::ScanCommand::max_keys_scanned_ private
Definition at line 631 of file ldb_cmd.h.
Referenced by DoCommand().
string rocksdb::ScanCommand::start_key_ private
Definition at line 627 of file ldb_cmd.h.
Referenced by DoCommand().
bool rocksdb::ScanCommand::start_key_specified_ private
Definition at line 629 of file ldb_cmd.h.
Referenced by DoCommand().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/util/ldb_cmd.h
rippled/src/ripple/rocksdb/rocksdb/util/ldb_cmd.cc