rippled: beast::PropertyStream::Source Class Reference
beast::PropertyStream::Source Class Reference
#include <PropertyStream.h>
Classes
struct State
Public Member Functions
Source (std::string const &name)
~Source ()
std::string const & name () const
void add (Source &source)
template<class Derived >
Derived * add (Derived *child)
void remove (Source &child)
void removeAll ()
void write_one (PropertyStream &stream)
void write (PropertyStream &stream)
void write (PropertyStream &stream, std::string const &path)
std::pair< Source *, bool > find (std::string path)
Source * find_one_deep (std::string const &name)
PropertyStream::Source * find_path (std::string path)
PropertyStream::Source * find_one (std::string const &name)
virtual void onWrite (Map &)
Static Public Member Functions
static bool peel_leading_slash (std::string *path)
static bool peel_trailing_slashstar (std::string *path)
static std::string peel_name (std::string *path)
Private Types
typedef SharedData< State > SharedState
Private Member Functions
void remove (SharedState::Access &state, SharedState::Access &childState)
void removeAll (SharedState::Access &state)
void write (SharedState::Access &state, PropertyStream &stream)
Private Attributes
std::string const m_name
SharedState m_state
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
Subclasses can be called to write to a stream and have children.
Definition at line 270 of file PropertyStream.h.
Member Typedef Documentation
typedef SharedData<State> beast::PropertyStream::Source::SharedState private
Definition at line 285 of file PropertyStream.h.
Constructor & Destructor Documentation
beast::PropertyStream::Source::Source (std::string const & name) explicit
Definition at line 180 of file PropertyStream.cpp.
     : m_name (name)
     , m_state (this)
 {
 }
beast::PropertyStream::Source::~Source ()
Definition at line 186 of file PropertyStream.cpp.
 {
     SharedState::Access state (m_state);
     if (state->parent != nullptr)
         state->parent->remove (*this);
     removeAll (state);
 }
Member Function Documentation
void beast::PropertyStream::Source::add (Source & source)
Add a child source.
Definition at line 199 of file PropertyStream.cpp.
References bassert, and m_state.
Referenced by ripple::ApplicationImp::ApplicationImp(), beast::PropertyStream_test::run(), and ripple::ApplicationImp::setup().
 {
     SharedState::Access state (m_state);
     SharedState::Access childState (source.m_state);
     bassert (childState->parent == nullptr);
     state->children.push_back (childState->item);
     childState->parent = this;
 }
template<class Derived > Derived* beast::PropertyStream::Source::add (Derived * child) inline
Add a child source by pointer. The source pointer is returned so it can be used in ctor-initializers.
Definition at line 313 of file PropertyStream.h.
References beast::PropertyStream::add().
     {
         add (*static_cast <Source*>(child));
         return child;
     }
std::pair< PropertyStream::Source *, bool > beast::PropertyStream::Source::find (std::string path)
Parse the dot-delimited Source path and return the result. The first value will be a pointer to the Source object corresponding to the given path. If no Source object exists, then the first value will be nullptr and the second value will be undefined. The second value is a boolean indicating whether or not the path string specifies the wildcard character '*' as the last character.
print statement examples "parent.child" prints child and all of its children "parent.child." start at the parent and print down to child "parent.grandchild" prints nothing- grandchild not direct discendent "parent.grandchild." starts at the parent and prints down to grandchild "parent.grandchild.*" starts at parent, print through grandchild children
Definition at line 271 of file PropertyStream.cpp.
References find_path(), and name.
Referenced by beast::PropertyStream_test::test_find().
 {
     bool const deep (peel_trailing_slashstar (&path));
     bool const rooted (peel_leading_slash (&path));
     Source* source (this);
     if (! path.empty())
     {
         if (! rooted)
         {
             std::string const name (peel_name (&path));
             source = find_one_deep (name);
             if (source == nullptr)
                 return std::make_pair (nullptr, deep);
         }
         source = source->find_path (path);
     }
     return std::make_pair (source, deep);
 }
PropertyStream::Source * beast::PropertyStream::Source::find_one (std::string const & name)
Definition at line 367 of file PropertyStream.cpp.
References name.
Referenced by find_path(), and beast::PropertyStream_test::test_find_one().
 {
     SharedState::Access state (this->m_state);
     for (auto& s : state->children)
     {
         if (s.source().m_name == name)
             return &s.source();
     }
     return nullptr;
 }
PropertyStream::Source * beast::PropertyStream::Source::find_one_deep (std::string const & name)
Definition at line 334 of file PropertyStream.cpp.
References find_one_deep().
Referenced by find_one_deep(), and beast::PropertyStream_test::test_find_one_deep().
 {
     Source* found = find_one (name);
     if (found != nullptr)
         return found;
     SharedState::Access state (this->m_state);
     for (auto& s : state->children)
     {
         found = s.source().find_one_deep (name);
         if (found != nullptr)
             return found;
     }
     return nullptr;
 }
PropertyStream::Source * beast::PropertyStream::Source::find_path (std::string path)
Definition at line 349 of file PropertyStream.cpp.
References find_one(), and name.
Referenced by find(), and beast::PropertyStream_test::test_find_path().
 {
     if (path.empty())
         return this;
     Source* source (this);
     do
     {
         std::string const name (peel_name (&path));
         if(name.empty ())
             break;
         source = source->find_one(name);
     }
     while (source != nullptr);
     return source;
 }
std::string const & beast::PropertyStream::Source::name () const
Returns the name of this source.
Definition at line 194 of file PropertyStream.cpp.
Referenced by ripple::OverlayImpl::onPrepare(), and ripple::PeerFinder::ManagerImp::parseBootstrapIPs().
 {
     return m_name;
 }
void beast::PropertyStream::Source::onWrite (Map &) virtual
Subclass override. The default version does nothing.
Reimplemented in ripple::ApplicationImp, ripple::Validators::ManagerImp, ripple::PeerFinder::ManagerImp, ripple::OverlayImpl, ripple::LedgerCleanerImp, ripple::SiteFiles::ManagerImp, and ripple::Resource::ManagerImp.
Definition at line 378 of file PropertyStream.cpp.
 {
 }
bool beast::PropertyStream::Source::peel_leading_slash (std::string * path) static
Definition at line 290 of file PropertyStream.cpp.
Referenced by beast::PropertyStream_test::test_peel_leading_slash().
 {
     if (! path->empty() && path->front() == '/')
     {
         *path = std::string (path->begin() + 1, path->end());
         return true;
     }
     return false;
 }
std::string beast::PropertyStream::Source::peel_name (std::string * path) static
Definition at line 315 of file PropertyStream.cpp.
References beast.util.Iter::first().
Referenced by beast::PropertyStream_test::test_peel_name().
 {
     if (path->empty())
         return "";
     std::string::const_iterator first = (*path).begin();
     std::string::const_iterator last = (*path).end();
     std::string::const_iterator pos (std::find (first, last, '/'));
     std::string s (first, pos);
     if (pos != last)
         *path = std::string (pos+1, last);
     else
         *path = std::string ();
     return s;
 }
bool beast::PropertyStream::Source::peel_trailing_slashstar (std::string * path) static
Definition at line 300 of file PropertyStream.cpp.
Referenced by beast::PropertyStream_test::test_peel_trailing_slashstar().
 {
     bool found(false);
     if (path->empty())
         return false;
     if (path->back() == '*')
     {
         found = true;
         path->pop_back();
     }
     if(! path->empty() && path->back() == '/')
         path->pop_back();
     return found;
 }
void beast::PropertyStream::Source::remove (SharedState::Access & state, SharedState::Access & childState) private
Definition at line 384 of file PropertyStream.cpp.
References bassert.
 {
     bassert (childState->parent == this);
     state->children.erase (
         state->children.iterator_to (
             childState->item));
     childState->parent = nullptr;
 }
void beast::PropertyStream::Source::remove (Source & child)
Remove a child source from this Source.
Definition at line 208 of file PropertyStream.cpp.
References m_state.
 {
     SharedState::Access state (m_state);
     SharedState::Access childState (child.m_state);
     remove (state, childState);
 }
void beast::PropertyStream::Source::removeAll (SharedState::Access & state) private
Definition at line 394 of file PropertyStream.cpp.
 {
     for (List <Item>::iterator iter (state->children.begin());
         iter != state->children.end();)
     {
         SharedState::Access childState ((*iter)->m_state);
         remove (state, childState);
     }
 }
void beast::PropertyStream::Source::removeAll ()
Remove all child sources of this Source.
Definition at line 215 of file PropertyStream.cpp.
 {
     SharedState::Access state (m_state);
     removeAll (state);
 }
void beast::PropertyStream::Source::write (SharedState::Access & state, PropertyStream & stream) private
Definition at line 223 of file PropertyStream.cpp.
Referenced by write().
 {
     for (List <Item>::iterator iter (state->children.begin());
         iter != state->children.end(); ++iter)
     {
         Source& source (iter->source());
         Map map (source.name(), stream);
         source.write (stream);
     }
 }
void beast::PropertyStream::Source::write (PropertyStream & stream)
write this source and all its children recursively to the stream.
Definition at line 243 of file PropertyStream.cpp.
References write().
Referenced by ripple::RPCHandler::doPrint(), and ripple::RPC::DoPrint::operator()().
 {
     Map map (m_name, stream);
     onWrite (map);
     SharedState::Access state (m_state);
     for (List <Item>::iterator iter (state->children.begin());
         iter != state->children.end(); ++iter)
     {
         Source& source (iter->source());
         source.write (stream);
     }
 }
void beast::PropertyStream::Source::write (PropertyStream & stream, std::string const & path)
Parse the path and write the corresponding Source and optional children. If the source is found, it is written. If the wildcard character '*' exists as the last character in the path, then all the children are written recursively.
Definition at line 258 of file PropertyStream.cpp.
 {
     std::pair <Source*, bool> result (find (path));
     if (result.first == nullptr)
         return;
     if (result.second)
         result.first->write (stream);
     else
         result.first->write_one (stream);
 }
void beast::PropertyStream::Source::write_one (PropertyStream & stream)
Write only this Source to the stream.
Definition at line 237 of file PropertyStream.cpp.
 {
     Map map (m_name, stream);
     onWrite (map);
 }
Member Data Documentation
std::string const beast::PropertyStream::Source::m_name private
Definition at line 287 of file PropertyStream.h.
SharedState beast::PropertyStream::Source::m_state private
Definition at line 288 of file PropertyStream.h.
Referenced by add(), and remove().
The documentation for this class was generated from the following files:
rippled/src/beast/beast/utility/PropertyStream.h
rippled/src/beast/beast/utility/impl/PropertyStream.cpp