rippled: ripple::PathRequests Class Reference
ripple::PathRequests Class Reference
#include <PathRequests.h>
Public Member Functions
PathRequests (beast::Journal journal, beast::insight::Collector::ptr const &collector)
void updateAll (const boost::shared_ptr< Ledger > &ledger, CancelCallback shouldCancel)
RippleLineCache::pointer getLineCache (Ledger::pointer &ledger, bool authoritative)
Json::Value makePathRequest (boost::shared_ptr< InfoSub > const &subscriber, const boost::shared_ptr< Ledger > &ledger, const Json::Value &request)
void reportFast (int milliseconds)
void reportFull (int milliseconds)
Private Types
typedef RippleRecursiveMutex LockType
typedef std::lock_guard< LockType > ScopedLockType
Private Attributes
beast::Journal mJournal
beast::insight::Event mFast
beast::insight::Event mFull
std::vector< PathRequest::wptr > mRequests
RippleLineCache::pointer mLineCache
beast::Atomic< int > mLastIdentifier
LockType mLock
Detailed Description
Definition at line 25 of file PathRequests.h.
Member Typedef Documentation
typedef RippleRecursiveMutex ripple::PathRequests::LockType private
Definition at line 69 of file PathRequests.h.
typedef std::lock_guard<LockType> ripple::PathRequests::ScopedLockType private
Definition at line 70 of file PathRequests.h.
Constructor & Destructor Documentation
ripple::PathRequests::PathRequests (beast::Journal journal, beast::insight::Collector::ptr const & collector) inline
Definition at line 28 of file PathRequests.h.
References mFast, and mFull.
         : mJournal (journal)
         , mLastIdentifier (0)
     {
         mFast = collector->make_event ("pathfind_fast");
         mFull = collector->make_event ("pathfind_full");
     }
Member Function Documentation
RippleLineCache::pointer ripple::PathRequests::getLineCache (Ledger::pointer & ledger, bool authoritative)
Get the current RippleLineCache, updating it if necessary. Get the correct ledger to use.
Definition at line 25 of file PathRequests.cpp.
References mLineCache, and mLock.
Referenced by ripple::RPCHandler::doRipplePathFind(), makePathRequest(), and updateAll().
 {
     ScopedLockType sl (mLock);
     std::uint32_t lineSeq = mLineCache ? mLineCache->getLedger()->getLedgerSeq() : 0;
     std::uint32_t lgrSeq = ledger->getLedgerSeq();
     if ( (lineSeq == 0) ||                                 // no ledger
          (authoritative && (lgrSeq > lineSeq)) ||          // newer authoritative ledger
          (authoritative && ((lgrSeq + 8)  < lineSeq)) ||   // we jumped way back for some reason
          (lgrSeq > (lineSeq + 8)))                         // we jumped way forward for some reason
     {
         ledger = boost::make_shared<Ledger>(*ledger, false); // Take a snapshot of the ledger
         mLineCache = boost::make_shared<RippleLineCache> (ledger);
     }
     else
     {
         ledger = mLineCache->getLedger();
     }
     return mLineCache;
 }
Json::Value ripple::PathRequests::makePathRequest (boost::shared_ptr< InfoSub > const & subscriber, const boost::shared_ptr< Ledger > & ledger, const Json::Value & request)
Definition at line 162 of file PathRequests.cpp.
References ripple::getApp(), ripple::Application::getLedgerMaster(), getLineCache(), mJournal, mLastIdentifier, mLock, mRequests, and ripple::LedgerMaster::newPathRequest().
Referenced by ripple::RPCHandler::doPathFind().
 {
     PathRequest::pointer req = boost::make_shared<PathRequest> (
         subscriber, ++mLastIdentifier, *this, mJournal);
     Ledger::pointer ledger = inLedger;
     RippleLineCache::pointer cache;
     {
         ScopedLockType sl (mLock);
         cache = getLineCache (ledger, false);
     }
     bool valid = false;
     Json::Value result = req->doCreate (ledger, cache, requestJson, valid);
     if (valid)
     {
         {
             ScopedLockType sl (mLock);
             // Insert after any older unserviced requests but before any serviced requests
             std::vector<PathRequest::wptr>::iterator it = mRequests.begin ();
             while (it != mRequests.end ())
             {
                 PathRequest::pointer req = it->lock ();
                 if (req && !req->isNew ())
                     break; // This request has been handled, we come before it
                 // This is a newer request, we come after it
                 ++it;
             }
             mRequests.insert (it, PathRequest::wptr (req));
         }
         subscriber->setPathRequest (req);
         getApp().getLedgerMaster().newPathRequest();
     }
     return result;
 }
void ripple::PathRequests::reportFast (int milliseconds) inline
Definition at line 45 of file PathRequests.h.
References mFast, and beast::insight::Event::notify().
Referenced by ripple::PathRequest::doUpdate().
     {
         mFast.notify (static_cast < beast::insight::Event::value_type> (milliseconds));
     }
void ripple::PathRequests::reportFull (int milliseconds) inline
Definition at line 50 of file PathRequests.h.
References mFull, and beast::insight::Event::notify().
Referenced by ripple::PathRequest::doUpdate().
     {
         mFull.notify (static_cast < beast::insight::Event::value_type> (milliseconds));
     }
void ripple::PathRequests::updateAll (const boost::shared_ptr< Ledger > & ledger, CancelCallback shouldCancel)
Definition at line 47 of file PathRequests.cpp.
References beast::Journal::debug, ripple::Resource::feePathFindUpdate, ripple::getApp(), ripple::Application::getLedgerMaster(), getLineCache(), ripple::LedgerMaster::isNewPathRequest(), ripple::jtPATH_FIND, mJournal, mLock, mRequests, requests, and beast::Journal::trace.
Referenced by ripple::LedgerMasterImp::updatePaths().
 {
     std::vector<PathRequest::wptr> requests;
     LoadEvent::autoptr event (getApp().getJobQueue().getLoadEventAP(jtPATH_FIND, "PathRequest::updateAll"));
     // Get the ledger and cache we should be using
     Ledger::pointer ledger = inLedger;
     RippleLineCache::pointer cache;
     {
         ScopedLockType sl (mLock);
         requests = mRequests;
         cache = getLineCache (ledger, true);
     }
     bool newRequests = getApp().getLedgerMaster().isNewPathRequest();
     bool mustBreak = false;
     mJournal.trace << "updateAll seq=" << ledger->getLedgerSeq() << ", " <<
         requests.size() << " requests";
     int processed = 0, removed = 0;
     do
     {
         BOOST_FOREACH (PathRequest::wref wRequest, requests)
         {
             if (shouldCancel())
                 break;
             bool remove = true;
             PathRequest::pointer pRequest = wRequest.lock ();
             if (pRequest)
             {
                 if (!pRequest->needsUpdate (newRequests, ledger->getLedgerSeq ()))
                     remove = false;
                 else
                 {
                     InfoSub::pointer ipSub = pRequest->getSubscriber ();
                     if (ipSub)
                     {
                         ipSub->getConsumer ().charge (Resource::feePathFindUpdate);
                         if (!ipSub->getConsumer ().warn ())
{
                             Json::Value update = pRequest->doUpdate (cache, false);
                             update["type"] = "path_find";
                             ipSub->send (update, false);
                             remove = false;
                             ++processed;
                         }
                     }
                 }
             }
             if (remove)
             {
                 PathRequest::pointer pRequest = wRequest.lock ();
                 ScopedLockType sl (mLock);
                 // Remove any dangling weak pointers or weak pointers that refer to this path request.
                 std::vector<PathRequest::wptr>::iterator it = mRequests.begin();
                 while (it != mRequests.end())
                 {
                     PathRequest::pointer itRequest = it->lock ();
                     if (!itRequest || (itRequest == pRequest))
                     {
                         ++removed;
                         it = mRequests.erase (it);
                     }
                     else
                         ++it;
                 }
             }
             mustBreak = !newRequests && getApp().getLedgerMaster().isNewPathRequest();
             if (mustBreak) // We weren't handling new requests and then there was a new request
                 break;
         }
         if (mustBreak)
         { // a new request came in while we were working
             newRequests = true;
         }
         else if (newRequests)
         { // we only did new requests, so we always need a last pass
             newRequests = getApp().getLedgerMaster().isNewPathRequest();
         }
         else
         { // check if there are any new requests, otherwise we are done
             newRequests = getApp().getLedgerMaster().isNewPathRequest();
             if (!newRequests) // We did a full pass and there are no new requests
                 return;
         }
         {
             // Get the latest requests, cache, and ledger for next pass
             ScopedLockType sl (mLock);
             if (mRequests.empty())
                 break;
             requests = mRequests;
             cache = getLineCache (ledger, false);
         }
     }
     while (!shouldCancel ());
     mJournal.debug << "updateAll complete " << processed << " process and " <<
         removed << " removed";
 }
Member Data Documentation
beast::insight::Event ripple::PathRequests::mFast private
Definition at line 58 of file PathRequests.h.
Referenced by PathRequests(), and reportFast().
beast::insight::Event ripple::PathRequests::mFull private
Definition at line 59 of file PathRequests.h.
Referenced by PathRequests(), and reportFull().
beast::Journal ripple::PathRequests::mJournal private
Definition at line 56 of file PathRequests.h.
Referenced by makePathRequest(), and updateAll().
beast::Atomic<int> ripple::PathRequests::mLastIdentifier private
Definition at line 67 of file PathRequests.h.
Referenced by makePathRequest().
RippleLineCache::pointer ripple::PathRequests::mLineCache private
Definition at line 65 of file PathRequests.h.
Referenced by getLineCache().
LockType ripple::PathRequests::mLock private
Definition at line 71 of file PathRequests.h.
Referenced by getLineCache(), makePathRequest(), and updateAll().
std::vector<PathRequest::wptr> ripple::PathRequests::mRequests private
Definition at line 62 of file PathRequests.h.
Referenced by makePathRequest(), and updateAll().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/paths/PathRequests.h
rippled/src/ripple_app/paths/PathRequests.cpp