rippled: ripple::RPCDoorImp Class Reference
ripple::RPCDoorImp Class Reference
Public Member Functions
RPCDoorImp (boost::asio::io_service &io_service, RPCServer::Handler &handler)
~RPCDoorImp ()
void startListening ()
bool isClientAllowed (const std::string &ip)
void handleConnect (RPCServerImp::pointer new_connection, boost::system::error_code const &error)
Public Member Functions inherited from ripple::RPCDoor
virtual ~RPCDoor ()
Private Attributes
RPCServer::Handler & m_rpcServerHandler
boost::asio::ip::tcp::acceptor mAcceptor
boost::asio::deadline_timer mDelayTimer
beast::ScopedPointer
< RippleSSLContext > m_sslContext
Additional Inherited Members
Static Public Member Functions inherited from ripple::RPCDoor
static RPCDoor * New (boost::asio::io_service &io_service, RPCServer::Handler &handler)
Detailed Description
Definition at line 26 of file RPCDoor.cpp.
Constructor & Destructor Documentation
ripple::RPCDoorImp::RPCDoorImp (boost::asio::io_service & io_service, RPCServer::Handler & handler) inline
Definition at line 29 of file RPCDoor.cpp.
References ripple::getConfig(), ripple::Config::getRpcAddress(), ripple::lsINFO, ripple::Config::RPC_ALLOW_REMOTE, beast::String::toRawUTF8(), and WriteLog.
         : m_rpcServerHandler (handler)
         , mAcceptor (io_service,
                      boost::asio::ip::tcp::endpoint (boost::asio::ip::address::from_string (getConfig ().getRpcIP ()), getConfig ().getRpcPort ()))
         , mDelayTimer (io_service)
         , m_sslContext ((getConfig ().RPC_SECURE == 0) ?
                 RippleSSLContext::createBare () :
                 RippleSSLContext::createAuthenticated (
                     getConfig ().RPC_SSL_KEY,
                     getConfig ().RPC_SSL_CERT,
                     getConfig ().RPC_SSL_CHAIN))
     {
         WriteLog (lsINFO, RPCDoor) << "RPC port: " << getConfig ().getRpcAddress().toRawUTF8() << " allow remote: " << getConfig ().RPC_ALLOW_REMOTE;
         startListening ();
     }
ripple::RPCDoorImp::~RPCDoorImp () inline
Definition at line 48 of file RPCDoor.cpp.
References ripple::getConfig(), ripple::Config::getRpcAddress(), ripple::lsINFO, ripple::Config::RPC_ALLOW_REMOTE, beast::String::toRawUTF8(), and WriteLog.
     {
         WriteLog (lsINFO, RPCDoor) <<
             "RPC port: " << getConfig ().getRpcAddress().toRawUTF8() <<
             " allow remote: " << getConfig ().RPC_ALLOW_REMOTE;
     }
Member Function Documentation
void ripple::RPCDoorImp::handleConnect (RPCServerImp::pointer new_connection, boost::system::error_code const & error) inline
Definition at line 90 of file RPCDoor.cpp.
References ripple::RPCServer::connected(), ripple::lsINFO, startListening(), and WriteLog.
Referenced by startListening().
     {
         bool delay = false;
         if (!error)
         {
             // Restrict callers by IP
             std::string client_ip (
                 new_connection->getRemoteEndpoint ().address ().to_string ());
             if (! isClientAllowed (client_ip))
             {
                 startListening ();
                 return;
             }
             new_connection->getSocket ().async_handshake (AutoSocket::ssl_socket::server,
                     boost::bind (&RPCServer::connected, new_connection));
         }
         else
         {
             if (error == boost::system::errc::too_many_files_open)
                 delay = true;
             WriteLog (lsINFO, RPCDoor) << "RPCDoorImp::handleConnect Error: " << error;
         }
         if (delay)
         {
             mDelayTimer.expires_from_now (boost::posix_time::milliseconds (1000));
             mDelayTimer.async_wait (boost::bind (&RPCDoorImp::startListening, this));
         }
         else
         {
             startListening ();
         }
     }
bool ripple::RPCDoorImp::isClientAllowed (const std::string & ip) inline
Definition at line 75 of file RPCDoor.cpp.
References ripple::getConfig().
     {
         if (getConfig ().RPC_ALLOW_REMOTE)
             return true;
         // VFALCO TODO Represent ip addresses as a structure. Use isLoopback() member here
         //
         if (ip == "127.0.0.1")
             return true;
         return false;
     }
void ripple::RPCDoorImp::startListening () inline
Definition at line 57 of file RPCDoor.cpp.
References handleConnect().
Referenced by handleConnect().
     {
         // VFALCO NOTE Why not use make_shared?
         RPCServerImp::pointer new_connection (boost::make_shared <RPCServerImp> (
             boost::ref (mAcceptor.get_io_service ()),
                 boost::ref (m_sslContext->get ()),
                     boost::ref (m_rpcServerHandler)));
         mAcceptor.set_option (boost::asio::ip::tcp::acceptor::reuse_address (true));
         mAcceptor.async_accept (new_connection->getRawSocket (),
             new_connection->getRemoteEndpoint (),
             boost::bind (&RPCDoorImp::handleConnect, this,
                 new_connection, boost::asio::placeholders::error));
     }
Member Data Documentation
RPCServer::Handler& ripple::RPCDoorImp::m_rpcServerHandler private
Definition at line 130 of file RPCDoor.cpp.
beast::ScopedPointer<RippleSSLContext> ripple::RPCDoorImp::m_sslContext private
Definition at line 133 of file RPCDoor.cpp.
boost::asio::ip::tcp::acceptor ripple::RPCDoorImp::mAcceptor private
Definition at line 131 of file RPCDoor.cpp.
boost::asio::deadline_timer ripple::RPCDoorImp::mDelayTimer private
Definition at line 132 of file RPCDoor.cpp.
The documentation for this class was generated from the following file:
rippled/src/ripple_net/basics/RPCDoor.cpp