rippled: beast::asio::enable_wait_for_async< Derived > Class Template Reference
beast::asio::enable_wait_for_async< Derived > Class Template Reference
#include <enable_wait_for_async.h>
Public Member Functions
void wait_for_async ()
Protected Member Functions
enable_wait_for_async ()
~enable_wait_for_async ()
template<class Handler >
detail::ref_counted_wrapped_handler
< enable_wait_for_async,
std::remove_reference_t
< Handler > > wrap_with_counter (Handler &&handler, bool continuation=false)
template<class Handler >
detail::ref_counted_wrapped_handler
< enable_wait_for_async,
std::remove_reference_t
< Handler > > wrap_with_counter (continuation_t, Handler &&handler)
Private Member Functions
BEAST_DEFINE_IS_CALL_POSSIBLE (has_on_wait_for_async, on_wait_for_async)
void increment ()
void notify (std::true_type)
void notify (std::false_type)
void decrement ()
Private Attributes
std::mutex m_mutex
std::condition_variable m_cond
std::size_t m_count
Friends
template<class Owner , class Handler >
class detail::ref_counted_wrapped_handler
Detailed Description
template<class Derived>
class beast::asio::enable_wait_for_async< Derived >
Facilitates blocking until no completion handlers are remaining. If Derived has this member function:
void on_wait_for_async (void)
Then it will be called every time the number of pending completion handlers transitions to zero from a non-zero value. The call is made while holding the internal mutex.
Definition at line 173 of file enable_wait_for_async.h.
Constructor & Destructor Documentation
template<class Derived > beast::asio::enable_wait_for_async< Derived >::enable_wait_for_async () inline protected
Definition at line 224 of file enable_wait_for_async.h.
Referenced by beast::asio::enable_wait_for_async< Derived >::wrap_with_counter().
         : m_count (0)
     {
     }
template<class Derived > beast::asio::enable_wait_for_async< Derived >::~enable_wait_for_async () inline protected
Definition at line 229 of file enable_wait_for_async.h.
References beast::asio::enable_wait_for_async< Derived >::m_count.
     {
         assert (m_count == 0);
     }
Member Function Documentation
template<class Derived > beast::asio::enable_wait_for_async< Derived >::BEAST_DEFINE_IS_CALL_POSSIBLE (has_on_wait_for_async , on_wait_for_async) private
template<class Derived > void beast::asio::enable_wait_for_async< Derived >::decrement () inline private
Definition at line 194 of file enable_wait_for_async.h.
References beast::asio::enable_wait_for_async< Derived >::m_cond, beast::asio::enable_wait_for_async< Derived >::m_count, beast::asio::enable_wait_for_async< Derived >::m_mutex, beast::asio::enable_wait_for_async< Derived >::notify(), and value.
     {
         std::lock_guard <decltype(m_mutex)> lock (m_mutex);
         --m_count;
         if (m_count == 0)
         {
             m_cond.notify_all();
             notify (std::integral_constant <bool,
                 has_on_wait_for_async<Derived, void(void)>::value>());
         }
     }
template<class Derived > void beast::asio::enable_wait_for_async< Derived >::increment () inline private
Definition at line 179 of file enable_wait_for_async.h.
References beast::asio::enable_wait_for_async< Derived >::m_count, and beast::asio::enable_wait_for_async< Derived >::m_mutex.
     {
         std::lock_guard <decltype(m_mutex)> lock (m_mutex);
         ++m_count;
     }
template<class Derived > void beast::asio::enable_wait_for_async< Derived >::notify (std::true_type) inline private
Definition at line 185 of file enable_wait_for_async.h.
Referenced by beast::asio::enable_wait_for_async< Derived >::decrement().
     {
         static_cast <Derived*> (this)->on_wait_for_async();
     }
template<class Derived > void beast::asio::enable_wait_for_async< Derived >::notify (std::false_type) inline private
Definition at line 190 of file enable_wait_for_async.h.
     {
     }
template<class Derived > void beast::asio::enable_wait_for_async< Derived >::wait_for_async () inline
Blocks if there are any pending completion handlers.
Definition at line 216 of file enable_wait_for_async.h.
References beast::asio::enable_wait_for_async< Derived >::m_cond, beast::asio::enable_wait_for_async< Derived >::m_count, and beast::asio::enable_wait_for_async< Derived >::m_mutex.
     {
         std::unique_lock <decltype (m_mutex)> lock (m_mutex);
         while (m_count != 0)
             m_cond.wait (lock);
     }
template<class Derived > template<class Handler > detail::ref_counted_wrapped_handler< enable_wait_for_async, std::remove_reference_t <Handler> > beast::asio::enable_wait_for_async< Derived >::wrap_with_counter (Handler && handler, bool continuation = false) inline protected
Wraps the specified handler so it can be counted.
Definition at line 241 of file enable_wait_for_async.h.
References beast::asio::continuation, and beast::asio::enable_wait_for_async< Derived >::enable_wait_for_async().
     {
         return detail::ref_counted_wrapped_handler <enable_wait_for_async,
             std::remove_reference_t <Handler>> (*this,
                 std::forward <Handler> (handler), continuation);
     }
template<class Derived > template<class Handler > detail::ref_counted_wrapped_handler< enable_wait_for_async, std::remove_reference_t <Handler> > beast::asio::enable_wait_for_async< Derived >::wrap_with_counter (continuation_t , Handler && handler) inline protected
Definition at line 253 of file enable_wait_for_async.h.
References beast::asio::enable_wait_for_async< Derived >::enable_wait_for_async().
     {
         return detail::ref_counted_wrapped_handler <enable_wait_for_async,
             std::remove_reference_t <Handler>> (*this,
                 std::forward <Handler> (handler), true);
     }
Friends And Related Function Documentation
template<class Derived > template<class Owner , class Handler > friend class detail::ref_counted_wrapped_handler friend
Definition at line 207 of file enable_wait_for_async.h.
Member Data Documentation
template<class Derived > std::condition_variable beast::asio::enable_wait_for_async< Derived >::m_cond private
Definition at line 210 of file enable_wait_for_async.h.
Referenced by beast::asio::enable_wait_for_async< Derived >::decrement(), and beast::asio::enable_wait_for_async< Derived >::wait_for_async().
template<class Derived > std::size_t beast::asio::enable_wait_for_async< Derived >::m_count private
Definition at line 211 of file enable_wait_for_async.h.
Referenced by beast::asio::enable_wait_for_async< Derived >::decrement(), beast::asio::enable_wait_for_async< Derived >::increment(), beast::asio::enable_wait_for_async< Derived >::wait_for_async(), and beast::asio::enable_wait_for_async< Derived >::~enable_wait_for_async().
template<class Derived > std::mutex beast::asio::enable_wait_for_async< Derived >::m_mutex private
Definition at line 209 of file enable_wait_for_async.h.
Referenced by beast::asio::enable_wait_for_async< Derived >::decrement(), beast::asio::enable_wait_for_async< Derived >::increment(), and beast::asio::enable_wait_for_async< Derived >::wait_for_async().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/asio/enable_wait_for_async.h