rippled: sqlite3_vfs Struct Reference
sqlite3_vfs Struct Reference
#include <sqlite3.h>
Public Attributes
int iVersion
int szOsFile
int mxPathname
sqlite3_vfs * pNext
const char * zName
void * pAppData
int(* xOpen)(sqlite3_vfs *, const char *zName, sqlite3_file *, int flags, int *pOutFlags)
int(* xDelete)(sqlite3_vfs *, const char *zName, int syncDir)
int(* xAccess)(sqlite3_vfs *, const char *zName, int flags, int *pResOut)
int(* xFullPathname)(sqlite3_vfs *, const char *zName, int nOut, char *zOut)
void *(* xDlOpen)(sqlite3_vfs *, const char *zFilename)
void(* xDlError)(sqlite3_vfs *, int nByte, char *zErrMsg)
void(*(* xDlSym)(sqlite3_vfs *, void *, const char *zSymbol))(void)
void(* xDlClose)(sqlite3_vfs *, void *)
int(* xRandomness)(sqlite3_vfs *, int nByte, char *zOut)
int(* xSleep)(sqlite3_vfs *, int microseconds)
int(* xCurrentTime)(sqlite3_vfs *, double *)
int(* xGetLastError)(sqlite3_vfs *, int, char *)
int(* xCurrentTimeInt64)(sqlite3_vfs *, sqlite3_int64 *)
int(* xSetSystemCall)(sqlite3_vfs *, const char *zName, sqlite3_syscall_ptr)
sqlite3_syscall_ptr(* xGetSystemCall)(sqlite3_vfs *, const char *zName)
const char *(* xNextSystemCall)(sqlite3_vfs *, const char *zName)
Detailed Description
Definition at line 1256 of file sqlite3.c.
Member Data Documentation
int sqlite3_vfs::iVersion
Definition at line 1257 of file sqlite3.c.
Referenced by sqlite3OsCurrentTimeInt64().
int sqlite3_vfs::mxPathname
Definition at line 1259 of file sqlite3.c.
Referenced by pager_delmaster(), pager_playback(), sqlite3BtreeOpen(), sqlite3PagerOpen(), unixFileControl(), and unixFullPathname().
void * sqlite3_vfs::pAppData
Definition at line 1262 of file sqlite3.c.
sqlite3_vfs * sqlite3_vfs::pNext
Definition at line 1260 of file sqlite3.c.
Referenced by sqlite3_vfs_find(), sqlite3_vfs_register(), and vfsUnlink().
int sqlite3_vfs::szOsFile
Definition at line 1258 of file sqlite3.c.
Referenced by pager_delmaster(), sqlite3OsOpenMalloc(), sqlite3PagerOpen(), and sqlite3WalOpen().
int(* sqlite3_vfs::xAccess)(sqlite3_vfs *, const char *zName, int flags, int *pResOut)
Definition at line 1266 of file sqlite3.c.
Referenced by sqlite3OsAccess().
int(* sqlite3_vfs::xCurrentTime)(sqlite3_vfs *, double *)
Definition at line 1274 of file sqlite3.c.
Referenced by sqlite3OsCurrentTimeInt64().
int(* sqlite3_vfs::xCurrentTimeInt64)(sqlite3_vfs *, sqlite3_int64 *)
Definition at line 1280 of file sqlite3.c.
Referenced by sqlite3OsCurrentTimeInt64().
int(* sqlite3_vfs::xDelete)(sqlite3_vfs *, const char *zName, int syncDir)
Definition at line 1265 of file sqlite3.c.
Referenced by sqlite3OsDelete().
void(* sqlite3_vfs::xDlClose)(sqlite3_vfs *, void *)
Definition at line 1271 of file sqlite3.c.
Referenced by sqlite3OsDlClose().
void(* sqlite3_vfs::xDlError)(sqlite3_vfs *, int nByte, char *zErrMsg)
Definition at line 1269 of file sqlite3.c.
Referenced by sqlite3OsDlError().
void *(* sqlite3_vfs::xDlOpen)(sqlite3_vfs *, const char *zFilename)
Definition at line 1268 of file sqlite3.c.
Referenced by sqlite3OsDlOpen().
void(*(* sqlite3_vfs::xDlSym)(sqlite3_vfs *, void *, const char *zSymbol))(void)
Definition at line 1270 of file sqlite3.c.
int(* sqlite3_vfs::xFullPathname)(sqlite3_vfs *, const char *zName, int nOut, char *zOut)
Definition at line 1267 of file sqlite3.c.
Referenced by sqlite3OsFullPathname().
int(* sqlite3_vfs::xGetLastError)(sqlite3_vfs *, int, char *)
Definition at line 1275 of file sqlite3.c.
sqlite3_syscall_ptr(* sqlite3_vfs::xGetSystemCall)(sqlite3_vfs *, const char *zName)
Definition at line 1286 of file sqlite3.c.
const char *(* sqlite3_vfs::xNextSystemCall)(sqlite3_vfs *, const char *zName)
Definition at line 1287 of file sqlite3.c.
int(* sqlite3_vfs::xOpen)(sqlite3_vfs *, const char *zName, sqlite3_file *, int flags, int *pOutFlags)
Definition at line 1263 of file sqlite3.c.
Referenced by sqlite3OsOpen(), and unixOpen().
int(* sqlite3_vfs::xRandomness)(sqlite3_vfs *, int nByte, char *zOut)
Definition at line 1272 of file sqlite3.c.
Referenced by sqlite3OsRandomness().
int(* sqlite3_vfs::xSetSystemCall)(sqlite3_vfs *, const char *zName, sqlite3_syscall_ptr)
Definition at line 1285 of file sqlite3.c.
int(* sqlite3_vfs::xSleep)(sqlite3_vfs *, int microseconds)
Definition at line 1273 of file sqlite3.c.
Referenced by sqlite3OsSleep().
const char * sqlite3_vfs::zName
Definition at line 1261 of file sqlite3.c.
Referenced by attachFunc(), sqlite3_vfs_find(), and unixFileControl().
The documentation for this struct was generated from the following files:
rippled/src/beast/modules/beast_sqlite/sqlite/sqlite3.c
rippled/src/beast/modules/beast_sqlite/sqlite/sqlite3.h