rippled: ripple::PeerFinder::CheckerImp Class Reference
ripple::PeerFinder::CheckerImp Class Reference
Classes
class Request
struct State
Public Member Functions
CheckerImp ()
~CheckerImp ()
void cancel ()
void async_test (beast::IP::Endpoint const &endpoint, beast::asio::shared_handler< void(Result)> handler)
Public Member Functions inherited from ripple::PeerFinder::Checker
virtual ~Checker ()
Private Types
typedef beast::SharedData< State > SharedState
Private Types inherited from beast::Thread
typedef void * ThreadID
Private Member Functions
void add (Request &request)
void remove (Request &request)
void run ()
Private Member Functions inherited from beast::Thread
Thread (const String &threadName)
virtual ~Thread ()
void startThread ()
void startThread (int priority)
bool stopThread (int timeOutMilliseconds=-1)
void stopThreadAsync ()
bool isThreadRunning () const
void signalThreadShouldExit ()
bool threadShouldExit () const
bool waitForThreadToExit (int timeOutMilliseconds=-1) const
bool setPriority (int priority)
void setAffinityMask (std::uint32_t affinityMask)
bool wait (int timeOutMilliseconds=-1) const
void notify () const
ThreadID getThreadId () const noexcept
const String & getThreadName () const
Private Attributes
SharedState m_state
boost::asio::io_service m_io_service
boost::optional
< boost::asio::io_service::work > m_work
Additional Inherited Members
Static Public Member Functions inherited from ripple::PeerFinder::Checker
static Checker * New ()
Static Private Member Functions inherited from beast::Thread
static bool setCurrentThreadPriority (int priority)
static void setCurrentThreadAffinityMask (std::uint32_t affinityMask)
static void sleep (int milliseconds)
static void yield ()
static ThreadID getCurrentThreadId ()
static Thread * getCurrentThread ()
static void setCurrentThreadName (const String &newThreadName)
Detailed Description
Definition at line 26 of file Checker.cpp.
Member Typedef Documentation
typedef beast::SharedData<State> ripple::PeerFinder::CheckerImp::SharedState private
Definition at line 39 of file Checker.cpp.
Constructor & Destructor Documentation
ripple::PeerFinder::CheckerImp::CheckerImp () inline
Definition at line 130 of file Checker.cpp.
References beast::Thread::startThread().
         : Thread ("PeerFinder::Checker")
         , m_work (boost::in_place (boost::ref (m_io_service)))
     {
         startThread ();
     }
ripple::PeerFinder::CheckerImp::~CheckerImp () inline
Definition at line 137 of file Checker.cpp.
References cancel(), m_work, and beast::Thread::stopThread().
     {
         // cancel pending i/o
         cancel();
         // destroy the io_service::work object
         m_work = boost::none;
         // signal and wait for the thread to exit gracefully
         stopThread ();
     }
Member Function Documentation
void ripple::PeerFinder::CheckerImp::add (Request & request) inline private
Definition at line 112 of file Checker.cpp.
References m_state.
Referenced by ripple::PeerFinder::CheckerImp::Request::Request().
     {
         SharedState::Access state (m_state);
         state->list.push_back (request);
     }
void ripple::PeerFinder::CheckerImp::async_test (beast::IP::Endpoint const & endpoint, beast::asio::shared_handler< void(Result)> handler) inline virtual
Performs an async connection test on the specified endpoint. The port must be non-zero.
Implements ripple::PeerFinder::Checker.
Definition at line 157 of file Checker.cpp.
References m_io_service.
     {
         new Request (*this, m_io_service, endpoint, handler);
     }
void ripple::PeerFinder::CheckerImp::cancel () inline virtual
Cancel pending I/O. This issues cancel orders for all pending I/O operations and then returns immediately. Handlers will receive operation_aborted errors, or if they were already queued they will complete normally.
Implements ripple::PeerFinder::Checker.
Definition at line 149 of file Checker.cpp.
References m_state.
Referenced by ~CheckerImp().
     {
         SharedState::Access state (m_state);
         for (beast::List <Request>::iterator iter (state->list.begin());
             iter != state->list.end(); ++iter)
             iter->cancel();
     }
void ripple::PeerFinder::CheckerImp::remove (Request & request) inline private
Definition at line 118 of file Checker.cpp.
References m_state.
Referenced by ripple::PeerFinder::CheckerImp::Request::~Request().
     {
         SharedState::Access state (m_state);
         state->list.erase (state->list.iterator_to (request));
     }
void ripple::PeerFinder::CheckerImp::run () inline private virtual
Must be implemented to perform the thread's actual code.
Remember that the thread must regularly check the threadShouldExit() method whilst running, and if this returns true it should return from the run() method as soon as possible to avoid being forcibly killed.
See Also
threadShouldExit, startThread
Implements beast::Thread.
Definition at line 124 of file Checker.cpp.
References m_io_service.
     {
         m_io_service.run ();
     }
Member Data Documentation
boost::asio::io_service ripple::PeerFinder::CheckerImp::m_io_service private
Definition at line 42 of file Checker.cpp.
Referenced by async_test(), and run().
SharedState ripple::PeerFinder::CheckerImp::m_state private
Definition at line 41 of file Checker.cpp.
Referenced by add(), cancel(), and remove().
boost::optional<boost::asio::io_service::work> ripple::PeerFinder::CheckerImp::m_work private
Definition at line 43 of file Checker.cpp.
Referenced by ~CheckerImp().
The documentation for this class was generated from the following file:
rippled/src/ripple/peerfinder/impl/Checker.cpp