rippled: beast::CharPointer_UTF8 Class Reference
beast::CharPointer_UTF8 Class Reference
#include <CharPointer_UTF8.h>
Public Types
enum { byteOrderMark1 = 0xef, byteOrderMark2 = 0xbb, byteOrderMark3 = 0xbf }
typedef char CharType
Public Member Functions
CharPointer_UTF8 (const CharType *const rawPointer) noexcept
CharPointer_UTF8 (const CharPointer_UTF8 &other) noexcept
CharPointer_UTF8 operator= (CharPointer_UTF8 other) noexcept
CharPointer_UTF8 operator= (const CharType *text) noexcept
bool operator== (CharPointer_UTF8 other) const noexcept
bool operator!= (CharPointer_UTF8 other) const noexcept
bool operator<= (CharPointer_UTF8 other) const noexcept
bool operator< (CharPointer_UTF8 other) const noexcept
bool operator>= (CharPointer_UTF8 other) const noexcept
bool operator> (CharPointer_UTF8 other) const noexcept
CharType * getAddress () const noexcept
operator const CharType * () const noexcept
bool isEmpty () const noexcept
beast_wchar operator* () const noexcept
CharPointer_UTF8 & operator++ () noexcept
CharPointer_UTF8 operator-- () noexcept
beast_wchar getAndAdvance () noexcept
CharPointer_UTF8 operator++ (int) noexcept
void operator+= (int numToSkip) noexcept
void operator-= (int numToSkip) noexcept
beast_wchar operator[] (int characterIndex) const noexcept
CharPointer_UTF8 operator+ (int numToSkip) const noexcept
CharPointer_UTF8 operator- (int numToSkip) const noexcept
size_t length () const noexcept
size_t lengthUpTo (const size_t maxCharsToCount) const noexcept
size_t lengthUpTo (const CharPointer_UTF8 end) const noexcept
size_t sizeInBytes () const noexcept
CharPointer_UTF8 findTerminatingNull () const noexcept
void write (const beast_wchar charToWrite) noexcept
void writeNull () const noexcept
template<typename CharPointer >
void writeAll (const CharPointer src) noexcept
void writeAll (const CharPointer_UTF8 src) noexcept
template<typename CharPointer >
size_t writeWithDestByteLimit (const CharPointer src, const size_t maxDestBytes) noexcept
template<typename CharPointer >
void writeWithCharLimit (const CharPointer src, const int maxChars) noexcept
template<typename CharPointer >
int compare (const CharPointer other) const noexcept
template<typename CharPointer >
int compareUpTo (const CharPointer other, const int maxChars) const noexcept
template<typename CharPointer >
int compareIgnoreCase (const CharPointer other) const noexcept
int compareIgnoreCase (const CharPointer_UTF8 other) const noexcept
template<typename CharPointer >
int compareIgnoreCaseUpTo (const CharPointer other, const int maxChars) const noexcept
template<typename CharPointer >
int indexOf (const CharPointer stringToFind) const noexcept
int indexOf (const beast_wchar charToFind) const noexcept
int indexOf (const beast_wchar charToFind, const bool ignoreCase) const noexcept
bool isWhitespace () const noexcept
bool isDigit () const noexcept
bool isLetter () const noexcept
bool isLetterOrDigit () const noexcept
bool isUpperCase () const noexcept
bool isLowerCase () const noexcept
beast_wchar toUpperCase () const noexcept
beast_wchar toLowerCase () const noexcept
int getIntValue32 () const noexcept
std::int64_t getIntValue64 () const noexcept
double getDoubleValue () const noexcept
CharPointer_UTF8 findEndOfWhitespace () const noexcept
CharPointer_UTF8 atomicSwap (const CharPointer_UTF8 newValue)
Static Public Member Functions
static size_t getBytesRequiredFor (const beast_wchar charToWrite) noexcept
template<class CharPointer >
static size_t getBytesRequiredFor (CharPointer text) noexcept
static bool canRepresent (beast_wchar character) noexcept
static bool isValidString (const CharType *dataToTest, int maxBytesToRead)
static bool isByteOrderMark (const void *possibleByteOrder) noexcept
Private Attributes
CharType * data
Detailed Description
Wraps a pointer to a null-terminated UTF-8 character string, and provides various methods to operate on the data.
See Also
CharPointer_UTF16, CharPointer_UTF32
Definition at line 43 of file CharPointer_UTF8.h.
Member Typedef Documentation
typedef char beast::CharPointer_UTF8::CharType
Definition at line 46 of file CharPointer_UTF8.h.
Member Enumeration Documentation
anonymous enum
These values are the byte-order mark (BOM) values for a UTF-8 stream.
Enumerator
byteOrderMark1
byteOrderMark2
byteOrderMark3
Definition at line 559 of file CharPointer_UTF8.h.
     {
         byteOrderMark1 = 0xef,
         byteOrderMark2 = 0xbb,
         byteOrderMark3 = 0xbf
     };
Constructor & Destructor Documentation
beast::CharPointer_UTF8::CharPointer_UTF8 (const CharType *const rawPointer) inline explicit noexcept
Definition at line 48 of file CharPointer_UTF8.h.
Referenced by atomicSwap(), and findTerminatingNull().
         : data (const_cast <CharType*> (rawPointer))
     {
     }
beast::CharPointer_UTF8::CharPointer_UTF8 (const CharPointer_UTF8 & other) inline noexcept
Definition at line 53 of file CharPointer_UTF8.h.
         : data (other.data)
     {
     }
Member Function Documentation
CharPointer_UTF8 beast::CharPointer_UTF8::atomicSwap (const CharPointer_UTF8 newValue) inline
Atomically swaps this pointer for a new value, returning the previous value.
Definition at line 553 of file CharPointer_UTF8.h.
References CharPointer_UTF8(), and data.
     {
         return CharPointer_UTF8 (reinterpret_cast <Atomic<CharType*>&> (data).exchange (newValue.data));
     }
static bool beast::CharPointer_UTF8::canRepresent (beast_wchar character) inline static noexcept
Returns true if the given unicode character can be represented in this encoding.
Definition at line 509 of file CharPointer_UTF8.h.
     {
         return ((unsigned int) character) < (unsigned int) 0x10ffff;
     }
template<typename CharPointer > int beast::CharPointer_UTF8::compare (const CharPointer other) const inline noexcept
Compares this string with another one.
Definition at line 413 of file CharPointer_UTF8.h.
References beast::CharacterFunctions::compare().
     {
         return CharacterFunctions::compare (*this, other);
     }
template<typename CharPointer > int beast::CharPointer_UTF8::compareIgnoreCase (const CharPointer other) const inline noexcept
Compares this string with another one.
Definition at line 427 of file CharPointer_UTF8.h.
References beast::CharacterFunctions::compareIgnoreCase().
Referenced by beast::String::compareLexicographically().
     {
         return CharacterFunctions::compareIgnoreCase (*this, other);
     }
int beast::CharPointer_UTF8::compareIgnoreCase (const CharPointer_UTF8 other) const inline noexcept
Compares this string with another one.
Definition at line 433 of file CharPointer_UTF8.h.
References data.
     {
        #if BEAST_WINDOWS
         return stricmp (data, other.data);
        #else
         return strcasecmp (data, other.data);
        #endif
     }
template<typename CharPointer > int beast::CharPointer_UTF8::compareIgnoreCaseUpTo (const CharPointer other, const int maxChars) const inline noexcept
Compares this string with another one, up to a specified number of characters.
Definition at line 444 of file CharPointer_UTF8.h.
References beast::CharacterFunctions::compareIgnoreCaseUpTo().
Referenced by beast::String::indexOfWholeWordIgnoreCase(), and beast::String::lastIndexOfIgnoreCase().
     {
         return CharacterFunctions::compareIgnoreCaseUpTo (*this, other, maxChars);
     }
template<typename CharPointer > int beast::CharPointer_UTF8::compareUpTo (const CharPointer other, const int maxChars) const inline noexcept
Compares this string with another one, up to a specified number of characters.
Definition at line 420 of file CharPointer_UTF8.h.
References beast::CharacterFunctions::compareUpTo().
Referenced by beast::String::indexOfWholeWord(), and beast::String::lastIndexOf().
     {
         return CharacterFunctions::compareUpTo (*this, other, maxChars);
     }
CharPointer_UTF8 beast::CharPointer_UTF8::findEndOfWhitespace () const inline noexcept
Returns the first non-whitespace character in the string.
Definition at line 506 of file CharPointer_UTF8.h.
References beast::CharacterFunctions::findEndOfWhitespace().
 { return CharacterFunctions::findEndOfWhitespace (*this); }
CharPointer_UTF8 beast::CharPointer_UTF8::findTerminatingNull () const inline noexcept
Returns a pointer to the null character that terminates this string.
Definition at line 335 of file CharPointer_UTF8.h.
References CharPointer_UTF8(), and data.
Referenced by beast::String::appendCharPointer(), beast::String::getByteOffsetOfEnd(), and beast::String::replaceSection().
     {
         return CharPointer_UTF8 (data + strlen (data));
     }
CharType* beast::CharPointer_UTF8::getAddress () const inline noexcept
Returns the address that this pointer is pointing to.
Definition at line 79 of file CharPointer_UTF8.h.
References data.
Referenced by beast::String::appendCharPointer(), beast::StringArray::appendNumbersToDuplicates(), beast::StringHolder::createFromCharPointer(), beast::String::getByteOffsetOfEnd(), beast::StringHolder::makeUnique(), beast::StringHolder::makeUniqueWithByteSize(), beast::DynamicLibrary::open(), beast::operator<<(), beast::String::paddedLeft(), beast::String::paddedRight(), and beast::String::replaceSection().
 { return data; }
beast_wchar beast::CharPointer_UTF8::getAndAdvance () inline noexcept
Returns the character that this pointer is currently pointing to, and then advances the pointer to point to the next character.
Definition at line 155 of file CharPointer_UTF8.h.
References data.
Referenced by beast::String::containsAnyOf(), beast::String::containsOnly(), beast::countNumberOfSeparators(), beast::MemoryBlock::fromBase64Encoding(), beast::File::getRelativePathFrom(), beast::String::indexOfAnyOf(), beast::String::indexOfChar(), beast::String::lastIndexOfAnyOf(), beast::String::lastIndexOfChar(), beast::MemoryBlock::loadFromHexString(), beast::String::removeCharacters(), beast::String::replaceCharacter(), beast::String::replaceCharacters(), beast::String::retainCharacters(), and beast::OutputStream::writeText().
     {
         const signed char byte = (signed char) *data++;
         if (byte >= 0)
             return (beast_wchar) (std::uint8_t) byte;
         std::uint32_t n = (std::uint32_t) (std::uint8_t) byte;
         std::uint32_t mask = 0x7f;
         std::uint32_t bit = 0x40;
         int numExtraValues = 0;
         while ((n & bit) != 0 && bit > 0x8)
         {
             mask >>= 1;
             ++numExtraValues;
             bit >>= 1;
         }
         n &= mask;
         while (--numExtraValues >= 0)
         {
             const std::uint32_t nextByte = (std::uint32_t) (std::uint8_t) *data++;
             if ((nextByte & 0xc0) != 0x80)
                 break;
             n <<= 6;
             n |= (nextByte & 0x3f);
         }
         return (beast_wchar) n;
     }
static size_t beast::CharPointer_UTF8::getBytesRequiredFor (const beast_wchar charToWrite) inline static noexcept
Returns the number of bytes that would be needed to represent the given unicode character in this encoding format.
Definition at line 299 of file CharPointer_UTF8.h.
Referenced by beast::String::appendCharPointer(), beast::MemoryOutputStream::appendUTF8Char(), beast::String::charToString(), beast::StringHolder::createFromCharPointer(), getBytesRequiredFor(), beast::String::getNumBytesAsUTF8(), and beast::StringCreationHelper::write().
     {
         size_t num = 1;
         const std::uint32_t c = (std::uint32_t) charToWrite;
         if (c >= 0x80)
         {
             ++num;
             if (c >= 0x800)
             {
                 ++num;
                 if (c >= 0x10000)
                     ++num;
             }
         }
         return num;
     }
template<class CharPointer > static size_t beast::CharPointer_UTF8::getBytesRequiredFor (CharPointer text) inline static noexcept
Returns the number of bytes that would be needed to represent the given string in this encoding format. The value returned does NOT include the terminating null character.
Definition at line 323 of file CharPointer_UTF8.h.
References getBytesRequiredFor().
     {
         size_t count = 0;
         beast_wchar n;
         while ((n = text.getAndAdvance()) != 0)
             count += getBytesRequiredFor (n);
         return count;
     }
double beast::CharPointer_UTF8::getDoubleValue () const inline noexcept
Parses this string as a floating point double.
Definition at line 503 of file CharPointer_UTF8.h.
References beast::CharacterFunctions::getDoubleValue().
 { return CharacterFunctions::getDoubleValue (*this); }
int beast::CharPointer_UTF8::getIntValue32 () const inline noexcept
Parses this string as a 32-bit integer.
Definition at line 488 of file CharPointer_UTF8.h.
References data.
 { return atoi (data); }
std::int64_t beast::CharPointer_UTF8::getIntValue64 () const inline noexcept
Parses this string as a 64-bit integer.
Definition at line 491 of file CharPointer_UTF8.h.
References data.
     {
        #if BEAST_LINUX || BEAST_ANDROID
         return atoll (data);
        #elif BEAST_WINDOWS
         return _atoi64 (data);
        #else
         return CharacterFunctions::getIntValue <std::int64_t, CharPointer_UTF8> (*this);
        #endif
     }
template<typename CharPointer > int beast::CharPointer_UTF8::indexOf (const CharPointer stringToFind) const inline noexcept
Returns the character index of a substring, or -1 if it isn't found.
Definition at line 451 of file CharPointer_UTF8.h.
References beast::CharacterFunctions::indexOf().
Referenced by beast::String::indexOf().
     {
         return CharacterFunctions::indexOf (*this, stringToFind);
     }
int beast::CharPointer_UTF8::indexOf (const beast_wchar charToFind) const inline noexcept
Returns the character index of a unicode character, or -1 if it isn't found.
Definition at line 457 of file CharPointer_UTF8.h.
References beast::CharacterFunctions::indexOfChar().
     {
         return CharacterFunctions::indexOfChar (*this, charToFind);
     }
int beast::CharPointer_UTF8::indexOf (const beast_wchar charToFind, const bool ignoreCase) const inline noexcept
Returns the character index of a unicode character, or -1 if it isn't found.
Definition at line 463 of file CharPointer_UTF8.h.
References beast::CharacterFunctions::indexOfChar(), and beast::CharacterFunctions::indexOfCharIgnoreCase().
     {
         return ignoreCase ? CharacterFunctions::indexOfCharIgnoreCase (*this, charToFind)
                           : CharacterFunctions::indexOfChar (*this, charToFind);
     }
static bool beast::CharPointer_UTF8::isByteOrderMark (const void * possibleByteOrder) inline static noexcept
Returns true if the first three bytes in this pointer are the UTF8 byte-order mark (BOM). The pointer must not be null, and must point to at least 3 valid bytes.
Definition at line 569 of file CharPointer_UTF8.h.
References bassert, byteOrderMark1, byteOrderMark2, and byteOrderMark3.
Referenced by beast::String::createStringFromData().
     {
         bassert (possibleByteOrder != nullptr);
         const std::uint8_t* const c = static_cast<const std::uint8_t*> (possibleByteOrder);
         return c[0] == (std::uint8_t) byteOrderMark1
             && c[1] == (std::uint8_t) byteOrderMark2
             && c[2] == (std::uint8_t) byteOrderMark3;
     }
bool beast::CharPointer_UTF8::isDigit () const inline noexcept
Returns true if the first character of this string is a digit.
Definition at line 472 of file CharPointer_UTF8.h.
References data.
 { return *data >= '0' && *data <= '9'; }
bool beast::CharPointer_UTF8::isEmpty () const inline noexcept
Returns true if this pointer is pointing to a null character.
Definition at line 85 of file CharPointer_UTF8.h.
References data.
Referenced by beast::StringArray::addLines(), beast::StringArray::addTokens(), beast::String::compareLexicographically(), beast::String::containsAnyOf(), beast::String::containsNonWhitespaceChars(), beast::String::containsOnly(), beast::StringHolder::createFromCharPointer(), beast::String::indexOf(), beast::String::indexOfAnyOf(), beast::String::indexOfChar(), beast::String::indexOfIgnoreCase(), beast::String::initialSectionContainingOnly(), beast::String::initialSectionNotContaining(), beast::String::lastIndexOfAnyOf(), beast::String::lastIndexOfChar(), beast::String::paddedLeft(), beast::String::paddedRight(), beast::String::replaceSection(), and beast::String::substring().
 { return *data == 0; }
bool beast::CharPointer_UTF8::isLetter () const inline noexcept
Returns true if the first character of this string is a letter.
Definition at line 474 of file CharPointer_UTF8.h.
References beast::CharacterFunctions::isLetter().
 { return CharacterFunctions::isLetter (operator*()) != 0; }
bool beast::CharPointer_UTF8::isLetterOrDigit () const inline noexcept
Returns true if the first character of this string is a letter or digit.
Definition at line 476 of file CharPointer_UTF8.h.
References beast::CharacterFunctions::isLetterOrDigit().
Referenced by beast::String::compareLexicographically().
 { return CharacterFunctions::isLetterOrDigit (operator*()) != 0; }
bool beast::CharPointer_UTF8::isLowerCase () const inline noexcept
Returns true if the first character of this string is lower-case.
Definition at line 480 of file CharPointer_UTF8.h.
References beast::CharacterFunctions::isLowerCase().
 { return CharacterFunctions::isLowerCase (operator*()) != 0; }
bool beast::CharPointer_UTF8::isUpperCase () const inline noexcept
Returns true if the first character of this string is upper-case.
Definition at line 478 of file CharPointer_UTF8.h.
References beast::CharacterFunctions::isUpperCase().
 { return CharacterFunctions::isUpperCase (operator*()) != 0; }
static bool beast::CharPointer_UTF8::isValidString (const CharType * dataToTest, int maxBytesToRead) inline static
Returns true if this data contains a valid string in this encoding.
Definition at line 515 of file CharPointer_UTF8.h.
     {
         while (--maxBytesToRead >= 0 && *dataToTest != 0)
         {
             const signed char byte = (signed char) *dataToTest++;
             if (byte < 0)
             {
                 std::uint8_t bit = 0x40;
                 int numExtraValues = 0;
                 while ((byte & bit) != 0)
                 {
                     if (bit < 8)
                         return false;
                     ++numExtraValues;
                     bit >>= 1;
                     if (bit == 8 && (numExtraValues > maxBytesToRead
                                        || *CharPointer_UTF8 (dataToTest - 1) > 0x10ffff))
                         return false;
                 }
                 maxBytesToRead -= numExtraValues;
                 if (maxBytesToRead < 0)
                     return false;
                 while (--numExtraValues >= 0)
                     if ((*dataToTest++ & 0xc0) != 0x80)
                         return false;
             }
         }
         return true;
     }
bool beast::CharPointer_UTF8::isWhitespace () const inline noexcept
Returns true if the first character of this string is whitespace.
Definition at line 470 of file CharPointer_UTF8.h.
References data.
Referenced by beast::String::containsNonWhitespaceChars().
 { return *data == ' ' || (*data <= 13 && *data >= 9); }
size_t beast::CharPointer_UTF8::length () const inline noexcept
Returns the number of characters in this string.
Definition at line 244 of file CharPointer_UTF8.h.
References data.
Referenced by beast::String::indexOfWholeWord(), beast::String::indexOfWholeWordIgnoreCase(), and beast::String::length().
     {
         const CharType* d = data;
         size_t count = 0;
         for (;;)
         {
             const std::uint32_t n = (std::uint32_t) (std::uint8_t) *d++;
             if ((n & 0x80) != 0)
             {
                 std::uint32_t bit = 0x40;
                 while ((n & bit) != 0)
                 {
                     ++d;
                     bit >>= 1;
                     if (bit == 0)
                         break; // illegal utf-8 sequence
                 }
             }
             else if (n == 0)
                 break;
             ++count;
         }
         return count;
     }
size_t beast::CharPointer_UTF8::lengthUpTo (const size_t maxCharsToCount) const inline noexcept
Returns the number of characters in this string, or the given value, whichever is lower.
Definition at line 276 of file CharPointer_UTF8.h.
References beast::CharacterFunctions::lengthUpTo().
     {
         return CharacterFunctions::lengthUpTo (*this, maxCharsToCount);
     }
size_t beast::CharPointer_UTF8::lengthUpTo (const CharPointer_UTF8 end) const inline noexcept
Returns the number of characters in this string, or up to the given end pointer, whichever is lower.
Definition at line 282 of file CharPointer_UTF8.h.
References beast::CharacterFunctions::lengthUpTo().
     {
         return CharacterFunctions::lengthUpTo (*this, end);
     }
beast::CharPointer_UTF8::operator const CharType * () const inline noexcept
Returns the address that this pointer is pointing to.
Definition at line 82 of file CharPointer_UTF8.h.
References data.
 { return data; }
bool beast::CharPointer_UTF8::operator!= (CharPointer_UTF8 other) const inline noexcept
Definition at line 72 of file CharPointer_UTF8.h.
References data.
 { return data != other.data; }
beast_wchar beast::CharPointer_UTF8::operator* () const inline noexcept
Returns the unicode character that this pointer is pointing to.
Definition at line 88 of file CharPointer_UTF8.h.
References data.
     {
         const signed char byte = (signed char) *data;
         if (byte >= 0)
             return (beast_wchar) (std::uint8_t) byte;
         std::uint32_t n = (std::uint32_t) (std::uint8_t) byte;
         std::uint32_t mask = 0x7f;
         std::uint32_t bit = 0x40;
         size_t numExtraValues = 0;
         while ((n & bit) != 0 && bit > 0x10)
         {
             mask >>= 1;
             ++numExtraValues;
             bit >>= 1;
         }
         n &= mask;
         for (size_t i = 1; i <= numExtraValues; ++i)
         {
             const std::uint8_t nextByte = (std::uint8_t) data [i];
             if ((nextByte & 0xc0) != 0x80)
                 break;
             n <<= 6;
             n |= (nextByte & 0x3f);
         }
         return (beast_wchar) n;
     }
CharPointer_UTF8 beast::CharPointer_UTF8::operator+ (int numToSkip) const inline noexcept
Returns a pointer which is moved forwards from this one by the specified number of characters.
Definition at line 228 of file CharPointer_UTF8.h.
     {
         CharPointer_UTF8 p (*this);
         p += numToSkip;
         return p;
     }
CharPointer_UTF8& beast::CharPointer_UTF8::operator++ () inline noexcept
Moves this pointer along to the next character in the string.
Definition at line 124 of file CharPointer_UTF8.h.
References data.
     {
         const signed char n = (signed char) *data++;
         if (n < 0)
         {
             beast_wchar bit = 0x40;
             while ((n & bit) != 0 && bit > 0x8)
             {
                 ++data;
                 bit >>= 1;
             }
         }
         return *this;
     }
CharPointer_UTF8 beast::CharPointer_UTF8::operator++ (int) inline noexcept
Moves this pointer along to the next character in the string.
Definition at line 191 of file CharPointer_UTF8.h.
     {
         CharPointer_UTF8 temp (*this);
         ++*this;
         return temp;
     }
void beast::CharPointer_UTF8::operator+= (int numToSkip) inline noexcept
Moves this pointer forwards by the specified number of characters.
Definition at line 199 of file CharPointer_UTF8.h.
Referenced by operator-=().
     {
         if (numToSkip < 0)
         {
             while (++numToSkip <= 0)
                 --*this;
         }
         else
         {
             while (--numToSkip >= 0)
                 ++*this;
         }
     }
CharPointer_UTF8 beast::CharPointer_UTF8::operator- (int numToSkip) const inline noexcept
Returns a pointer which is moved backwards from this one by the specified number of characters.
Definition at line 236 of file CharPointer_UTF8.h.
     {
         CharPointer_UTF8 p (*this);
         p += -numToSkip;
         return p;
     }
CharPointer_UTF8 beast::CharPointer_UTF8::operator-- () inline noexcept
Moves this pointer back to the previous character in the string.
Definition at line 143 of file CharPointer_UTF8.h.
References data.
     {
         int count = 0;
         while ((*--data & 0xc0) == 0x80 && ++count < 4)
         {}
         return *this;
     }
void beast::CharPointer_UTF8::operator-= (int numToSkip) inline noexcept
Moves this pointer backwards by the specified number of characters.
Definition at line 214 of file CharPointer_UTF8.h.
References operator+=().
     {
         operator+= (-numToSkip);
     }
bool beast::CharPointer_UTF8::operator< (CharPointer_UTF8 other) const inline noexcept
Definition at line 74 of file CharPointer_UTF8.h.
References data.
 { return data <  other.data; }
bool beast::CharPointer_UTF8::operator<= (CharPointer_UTF8 other) const inline noexcept
Definition at line 73 of file CharPointer_UTF8.h.
References data.
 { return data <= other.data; }
CharPointer_UTF8 beast::CharPointer_UTF8::operator= (CharPointer_UTF8 other) inline noexcept
Definition at line 58 of file CharPointer_UTF8.h.
References data.
     {
         data = other.data;
         return *this;
     }
CharPointer_UTF8 beast::CharPointer_UTF8::operator= (const CharType * text) inline noexcept
Definition at line 64 of file CharPointer_UTF8.h.
References data.
     {
         data = const_cast <CharType*> (text);
         return *this;
     }
bool beast::CharPointer_UTF8::operator== (CharPointer_UTF8 other) const inline noexcept
This is a pointer comparison, it doesn't compare the actual text.
Definition at line 71 of file CharPointer_UTF8.h.
References data.
 { return data == other.data; }
bool beast::CharPointer_UTF8::operator> (CharPointer_UTF8 other) const inline noexcept
Definition at line 76 of file CharPointer_UTF8.h.
References data.
 { return data >  other.data; }
bool beast::CharPointer_UTF8::operator>= (CharPointer_UTF8 other) const inline noexcept
Definition at line 75 of file CharPointer_UTF8.h.
References data.
 { return data >= other.data; }
beast_wchar beast::CharPointer_UTF8::operator[] (int characterIndex) const inline noexcept
Returns the character at a given character index from the start of the string.
Definition at line 220 of file CharPointer_UTF8.h.
     {
         CharPointer_UTF8 p (*this);
         p += characterIndex;
         return *p;
     }
size_t beast::CharPointer_UTF8::sizeInBytes () const inline noexcept
Returns the number of bytes that are used to represent this string. This includes the terminating null character.
Definition at line 290 of file CharPointer_UTF8.h.
References bassert, and data.
Referenced by beast::StringArray::joinIntoString().
     {
         bassert (data != nullptr);
         return strlen (data) + 1;
     }
beast_wchar beast::CharPointer_UTF8::toLowerCase () const inline noexcept
Returns a lower-case version of the first character of this string.
Definition at line 485 of file CharPointer_UTF8.h.
References beast::CharacterFunctions::toLowerCase().
Referenced by beast::String::toLowerCase().
 { return CharacterFunctions::toLowerCase (operator*()); }
beast_wchar beast::CharPointer_UTF8::toUpperCase () const inline noexcept
Returns an upper-case version of the first character of this string.
Definition at line 483 of file CharPointer_UTF8.h.
References beast::CharacterFunctions::toUpperCase().
Referenced by beast::String::toUpperCase().
 { return CharacterFunctions::toUpperCase (operator*()); }
void beast::CharPointer_UTF8::write (const beast_wchar charToWrite) inline noexcept
Writes a unicode character to this string, and advances this pointer to point to the next position.
Definition at line 341 of file CharPointer_UTF8.h.
References data.
Referenced by beast::MemoryOutputStream::appendUTF8Char(), beast::String::charToString(), beast::String::paddedLeft(), beast::String::paddedRight(), and beast::MemoryBlock::toBase64Encoding().
     {
         const std::uint32_t c = (std::uint32_t) charToWrite;
         if (c >= 0x80)
         {
             int numExtraBytes = 1;
             if (c >= 0x800)
             {
                 ++numExtraBytes;
                 if (c >= 0x10000)
                     ++numExtraBytes;
             }
             *data++ = (CharType) ((std::uint32_t) (0xff << (7 - numExtraBytes)) | (c >> (numExtraBytes * 6)));
             while (--numExtraBytes >= 0)
                 *data++ = (CharType) (0x80 | (0x3f & (c >> (numExtraBytes * 6))));
         }
         else
         {
             *data++ = (CharType) c;
         }
     }
template<typename CharPointer > void beast::CharPointer_UTF8::writeAll (const CharPointer src) inline noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
Definition at line 374 of file CharPointer_UTF8.h.
References beast::CharacterFunctions::copyAll().
Referenced by beast::StringHolder::createFromCharPointer(), beast::operator<<(), beast::String::paddedLeft(), and beast::String::paddedRight().
     {
         CharacterFunctions::copyAll (*this, src);
     }
void beast::CharPointer_UTF8::writeAll (const CharPointer_UTF8 src) inline noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
Definition at line 380 of file CharPointer_UTF8.h.
References data.
     {
         const CharType* s = src.data;
         while ((*data = *s) != 0)
         {
             ++data;
             ++s;
         }
     }
void beast::CharPointer_UTF8::writeNull () const inline noexcept
Writes a null character to this string (leaving the pointer's position unchanged).
Definition at line 367 of file CharPointer_UTF8.h.
References data.
Referenced by beast::String::appendCharPointer(), beast::String::charToString(), beast::String::paddedRight(), and beast::String::replaceSection().
     {
         *data = 0;
     }
template<typename CharPointer > void beast::CharPointer_UTF8::writeWithCharLimit (const CharPointer src, const int maxChars) inline noexcept
Copies a source string to this pointer, advancing this pointer as it goes. The maxChars parameter specifies the maximum number of characters that can be written to the destination buffer before stopping (including the terminating null).
Definition at line 406 of file CharPointer_UTF8.h.
References beast::CharacterFunctions::copyWithCharLimit().
Referenced by beast::StringHolder::createFromCharPointer(), beast::StringHolder::createFromFixedLength(), and beast::String::operator+=().
     {
         CharacterFunctions::copyWithCharLimit (*this, src, maxChars);
     }
template<typename CharPointer > size_t beast::CharPointer_UTF8::writeWithDestByteLimit (const CharPointer src, const size_t maxDestBytes) inline noexcept
Copies a source string to this pointer, advancing this pointer as it goes. The maxDestBytes parameter specifies the maximum number of bytes that can be written to the destination buffer before stopping.
Definition at line 396 of file CharPointer_UTF8.h.
References beast::CharacterFunctions::copyWithDestByteLimit().
     {
         return CharacterFunctions::copyWithDestByteLimit (*this, src, maxDestBytes);
     }
Member Data Documentation
CharType* beast::CharPointer_UTF8::data private
Definition at line 580 of file CharPointer_UTF8.h.
Referenced by atomicSwap(), compareIgnoreCase(), findTerminatingNull(), getAddress(), getAndAdvance(), getIntValue32(), getIntValue64(), isDigit(), isEmpty(), isWhitespace(), length(), operator const CharType *(), operator!=(), operator*(), operator++(), operator--(), operator<(), operator<=(), operator=(), operator==(), operator>(), operator>=(), sizeInBytes(), write(), writeAll(), and writeNull().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/strings/CharPointer_UTF8.h