rippled: ripple::Resource::ManagerImp Class Reference
ripple::Resource::ManagerImp Class Reference
Public Member Functions
ManagerImp (beast::insight::Collector::ptr const &collector, beast::Journal journal)
~ManagerImp ()
Consumer newInboundEndpoint (beast::IP::Endpoint const &address)
Consumer newOutboundEndpoint (beast::IP::Endpoint const &address)
Consumer newAdminEndpoint (std::string const &name)
Gossip exportConsumers ()
void importConsumers (std::string const &origin, Gossip const &gossip)
Json::Value getJson ()
Json::Value getJson (int threshold)
void onWrite (beast::PropertyStream::Map &map)
void run ()
Public Member Functions inherited from ripple::Resource::Manager
virtual ~Manager ()=0
Public Member Functions inherited from beast::PropertyStream::Source
Source (std::string const &name)
~Source ()
std::string const & name () const
void add (Source &source)
template<class Derived >
Derived * add (Derived *child)
void remove (Source &child)
void removeAll ()
void write_one (PropertyStream &stream)
void write (PropertyStream &stream)
void write (PropertyStream &stream, std::string const &path)
std::pair< Source *, bool > find (std::string path)
Source * find_one_deep (std::string const &name)
PropertyStream::Source * find_path (std::string path)
PropertyStream::Source * find_one (std::string const &name)
Public Member Functions inherited from beast::Thread
Thread (const String &threadName)
virtual ~Thread ()
void startThread ()
void startThread (int priority)
bool stopThread (int timeOutMilliseconds=-1)
void stopThreadAsync ()
bool isThreadRunning () const
void signalThreadShouldExit ()
bool threadShouldExit () const
bool waitForThreadToExit (int timeOutMilliseconds=-1) const
bool setPriority (int priority)
void setAffinityMask (std::uint32_t affinityMask)
bool wait (int timeOutMilliseconds=-1) const
void notify () const
ThreadID getThreadId () const noexcept
const String & getThreadName () const
Public Attributes
beast::Journal m_journal
Logic m_logic
Additional Inherited Members
Public Types inherited from beast::Thread
typedef void * ThreadID
Static Public Member Functions inherited from beast::PropertyStream::Source
static bool peel_leading_slash (std::string *path)
static bool peel_trailing_slashstar (std::string *path)
static std::string peel_name (std::string *path)
Static Public Member Functions inherited from beast::Thread
static bool setCurrentThreadPriority (int priority)
static void setCurrentThreadAffinityMask (std::uint32_t affinityMask)
static void sleep (int milliseconds)
static void yield ()
static ThreadID getCurrentThreadId ()
static Thread * getCurrentThread ()
static void setCurrentThreadName (const String &newThreadName)
Protected Member Functions inherited from ripple::Resource::Manager
Manager ()
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
Definition at line 25 of file Manager.cpp.
Constructor & Destructor Documentation
ripple::Resource::ManagerImp::ManagerImp (beast::insight::Collector::ptr const & collector, beast::Journal journal) inline
Definition at line 33 of file Manager.cpp.
References beast::Thread::startThread().
         : Thread ("Resource::Manager")
         , m_journal (journal)
         , m_logic (collector, get_seconds_clock (), journal)
     {
         startThread ();
     }
ripple::Resource::ManagerImp::~ManagerImp () inline
Definition at line 42 of file Manager.cpp.
References beast::Thread::stopThread().
     {
         stopThread ();
     }
Member Function Documentation
Gossip ripple::Resource::ManagerImp::exportConsumers () inline virtual
Extract packaged consumer information for export.
Implements ripple::Resource::Manager.
Definition at line 62 of file Manager.cpp.
References ripple::Resource::Logic::exportConsumers(), and m_logic.
     {
         return m_logic.exportConsumers();
     }
Json::Value ripple::Resource::ManagerImp::getJson () inline virtual
Extract consumer information for reporting.
Implements ripple::Resource::Manager.
Definition at line 74 of file Manager.cpp.
References ripple::Resource::Logic::getJson(), and m_logic.
     {
         return m_logic.getJson ();
     }
Json::Value ripple::Resource::ManagerImp::getJson (int threshold) inline virtual
Implements ripple::Resource::Manager.
Definition at line 79 of file Manager.cpp.
References ripple::Resource::Logic::getJson(), and m_logic.
     {
         return m_logic.getJson (threshold);
     }
void ripple::Resource::ManagerImp::importConsumers (std::string const & origin, Gossip const & gossip) inline virtual
Import packaged consumer information.
Parameters
origin An identifier that unique labels the origin.
Implements ripple::Resource::Manager.
Definition at line 67 of file Manager.cpp.
References ripple::Resource::Logic::importConsumers(), and m_logic.
     {
         m_logic.importConsumers (origin, gossip);
     }
Consumer ripple::Resource::ManagerImp::newAdminEndpoint (std::string const & name) inline virtual
Create a new endpoint keyed by name.
Implements ripple::Resource::Manager.
Definition at line 57 of file Manager.cpp.
References m_logic, and ripple::Resource::Logic::newAdminEndpoint().
     {
         return m_logic.newAdminEndpoint (name);
     }
Consumer ripple::Resource::ManagerImp::newInboundEndpoint (beast::IP::Endpoint const & address) inline virtual
Create a new endpoint keyed by inbound IP address.
Implements ripple::Resource::Manager.
Definition at line 47 of file Manager.cpp.
References m_logic, and ripple::Resource::Logic::newInboundEndpoint().
     {
         return m_logic.newInboundEndpoint (address);
     }
Consumer ripple::Resource::ManagerImp::newOutboundEndpoint (beast::IP::Endpoint const & address) inline virtual
Create a new endpoint keyed by outbound IP address and port.
Implements ripple::Resource::Manager.
Definition at line 52 of file Manager.cpp.
References m_logic, and ripple::Resource::Logic::newOutboundEndpoint().
     {
         return m_logic.newOutboundEndpoint (address);
     }
void ripple::Resource::ManagerImp::onWrite (beast::PropertyStream::Map &) inline virtual
Subclass override. The default version does nothing.
Reimplemented from beast::PropertyStream::Source.
Definition at line 86 of file Manager.cpp.
References m_logic, and ripple::Resource::Logic::onWrite().
     {
         m_logic.onWrite (map);
     }
void ripple::Resource::ManagerImp::run () inline virtual
Must be implemented to perform the thread's actual code.
Remember that the thread must regularly check the threadShouldExit() method whilst running, and if this returns true it should return from the run() method as soon as possible to avoid being forcibly killed.
See Also
threadShouldExit, startThread
Implements beast::Thread.
Definition at line 93 of file Manager.cpp.
References m_logic, ripple::Resource::Logic::periodicActivity(), beast::Thread::threadShouldExit(), and beast::Thread::wait().
     {
         do
         {
             m_logic.periodicActivity();
             wait (1000);
         }
         while (! threadShouldExit ());
     }
Member Data Documentation
beast::Journal ripple::Resource::ManagerImp::m_journal
Definition at line 30 of file Manager.cpp.
Logic ripple::Resource::ManagerImp::m_logic
Definition at line 31 of file Manager.cpp.
Referenced by exportConsumers(), getJson(), importConsumers(), newAdminEndpoint(), newInboundEndpoint(), newOutboundEndpoint(), onWrite(), and run().
The documentation for this class was generated from the following file:
rippled/src/ripple/resource/impl/Manager.cpp