rippled: ripple::FetchPack_test Class Reference
ripple::FetchPack_test Class Reference
Classes
struct TestFilter
Public Types
enum { tableItems = 100, tableItemsExtra = 20 }
typedef ripple::unordered_map
< uint256, Blob > Map
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Member Functions
void on_fetch (Map &map, uint256 const &hash, Blob const &blob)
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Additional Inherited Members
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 26 of file FetchPackTests.cpp.
Member Typedef Documentation
typedef ripple::unordered_map<uint256, Blob> ripple::FetchPack_test::Map
Definition at line 35 of file FetchPackTests.cpp.
Member Enumeration Documentation
anonymous enum
Enumerator
tableItems
tableItemsExtra
Definition at line 29 of file FetchPackTests.cpp.
     {
         tableItems = 100,
         tableItemsExtra = 20
     };
Member Function Documentation
void ripple::FetchPack_test::on_fetch (Map & map, uint256 const & hash, Blob const & blob) inline
Definition at line 67 of file FetchPackTests.cpp.
References beast::unit_test::suite::expect(), ripple::Serializer::getSHA512Half(), and hash.
     {
         Serializer s (blob);
         expect (s.getSHA512Half() == hash, "Hash mismatch");
         map.emplace (hash, blob);
     }
void ripple::FetchPack_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 74 of file FetchPackTests.cpp.
References ripple::get_seconds_clock(), beast::unit_test::suite::pass(), and ripple::smtFREE.
     {
         using namespace RadixMap;
         FullBelowCache fullBelowCache ("test.full_below",
             get_seconds_clock ());
         boost::shared_ptr <Table> t1 (boost::make_shared <Table> (
             smtFREE, fullBelowCache));
         pass ();
 //         beast::Random r;
 //         add_random_items (tableItems, *t1, r);
 //         boost::shared_ptr <Table> t2 (t1->snapShot (true));
 //
 //         add_random_items (tableItemsExtra, *t1, r);
 //         add_random_items (tableItemsExtra, *t2, r);
         // turn t1 into t2
 //         Map map;
 //         t2->getFetchPack (t1.get(), true, 1000000, std::bind (
 //             &FetchPack_test::on_fetch, this, std::ref (map), std::placeholders::_1, std::placeholders::_2));
 //         t1->getFetchPack (nullptr, true, 1000000, std::bind (
 //             &FetchPack_test::on_fetch, this, std::ref (map), std::placeholders::_1, std::placeholders::_2));
         // try to rebuild t2 from the fetch pack
 //         boost::shared_ptr <Table> t3;
 //         try
 //         {
 //             TestFilter filter (map, beast::Journal());
 //
 //             t3 = boost::make_shared <Table> (smtFREE, t2->getHash (),
 //                 fullBelowCache);
 //
 //             expect (t3->fetchRoot (t2->getHash (), &filter), "unable to get root");
 //
 //             // everything should be in the pack, no hashes should be needed
 //             std::vector <uint256> hashes = t3->getNeededHashes(1, &filter);
 //             expect (hashes.empty(), "missing hashes");
 //
 //             expect (t3->getHash () == t2->getHash (), "root hashes do not match");
 //             expect (t3->deepCompare (*t2), "failed compare");
 //         }
 //         catch (...)
 //         {
 //             fail ("unhandled exception");
 //         }
     }
The documentation for this class was generated from the following file:
rippled/src/ripple_app/shamap/FetchPackTests.cpp