rippled: rocksdb::Random64 Class Reference
rocksdb::Random64 Class Reference
#include <random.h>
Public Member Functions
Random64 (uint64_t s)
uint64_t Next ()
uint64_t Uniform (uint64_t n)
bool OneIn (uint64_t n)
uint64_t Skewed (int max_log)
Private Attributes
std::mt19937_64 generator_
Detailed Description
Definition at line 62 of file random.h.
Constructor & Destructor Documentation
rocksdb::Random64::Random64 (uint64_t s) inline explicit
Definition at line 67 of file random.h.
 : generator_(s) { }
Member Function Documentation
uint64_t rocksdb::Random64::Next () inline
Definition at line 70 of file random.h.
References generator_.
Referenced by rocksdb::Benchmark::AppendRandom(), rocksdb::Benchmark::DoDelete(), rocksdb::Benchmark::DoWrite(), rocksdb::Benchmark::MergeRandom(), rocksdb::Benchmark::MultiGetRandom(), rocksdb::Benchmark::PrefixScanRandom(), rocksdb::Benchmark::RandomWithVerify(), rocksdb::Benchmark::ReadHot(), rocksdb::Benchmark::ReadMissing(), rocksdb::Benchmark::ReadRandom(), rocksdb::Benchmark::ReadRandomWriteRandom(), rocksdb::Benchmark::ReadRandomWriteRandomMultiGet(), rocksdb::Benchmark::ReadWhileWriting(), rocksdb::Benchmark::SeekRandom(), and rocksdb::Benchmark::UpdateRandom().
 { return generator_(); }
bool rocksdb::Random64::OneIn (uint64_t n) inline
Definition at line 80 of file random.h.
References Uniform().
 { return Uniform(n) == 0; }
uint64_t rocksdb::Random64::Skewed (int max_log) inline
Definition at line 85 of file random.h.
References Uniform().
{
     return Uniform(1 << Uniform(max_log + 1));
   }
uint64_t rocksdb::Random64::Uniform (uint64_t n) inline
Definition at line 74 of file random.h.
References generator_.
Referenced by rocksdb::Env::GenerateUniqueId(), OneIn(), and Skewed().
{
     return std::uniform_int_distribution<uint64_t>(0, n - 1)(generator_);
   }
Member Data Documentation
std::mt19937_64 rocksdb::Random64::generator_ private
Definition at line 64 of file random.h.
Referenced by Next(), and Uniform().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/util/random.h