rippled: rocksdb::MemTableConstructor Class Reference
rocksdb::MemTableConstructor Class Reference
Public Member Functions
MemTableConstructor (const Comparator *cmp)
~MemTableConstructor ()
virtual Status FinishImpl (const Options &options, const KVMap &data)
virtual Iterator * NewIterator () const
Public Member Functions inherited from rocksdb::Constructor
Constructor (const Comparator *cmp)
virtual ~Constructor ()
void Add (const std::string &key, const Slice &value)
void Finish (const Options &options, std::vector< std::string > *keys, KVMap *kvmap)
virtual const KVMap & data ()
virtual DB * db () const
Private Attributes
InternalKeyComparator internal_comparator_
MemTable * memtable_
std::shared_ptr< SkipListFactory > table_factory_
Detailed Description
Definition at line 367 of file table_test.cc.
Constructor & Destructor Documentation
rocksdb::MemTableConstructor::MemTableConstructor (const Comparator * cmp) inline explicit
Definition at line 369 of file table_test.cc.
References internal_comparator_, memtable_, rocksdb::MemTable::Ref(), and table_factory_.
       : Constructor(cmp),
         internal_comparator_(cmp),
         table_factory_(new SkipListFactory) {
     memtable_ = new MemTable(internal_comparator_, table_factory_);
     memtable_->Ref();
   }
rocksdb::MemTableConstructor::~MemTableConstructor () inline
Definition at line 376 of file table_test.cc.
References memtable_, and rocksdb::MemTable::Unref().
{
     memtable_->Unref();
   }
Member Function Documentation
virtual Status rocksdb::MemTableConstructor::FinishImpl (const Options & options, const KVMap & data) inline virtual
Implements rocksdb::Constructor.
Definition at line 379 of file table_test.cc.
References rocksdb::MemTable::Add(), internal_comparator_, rocksdb::kTypeValue, memtable_, rocksdb::Status::OK(), rocksdb::MemTable::Ref(), table_factory_, and rocksdb::MemTable::Unref().
{
     memtable_->Unref();
     memtable_ = new MemTable(internal_comparator_, table_factory_);
     memtable_->Ref();
     int seq = 1;
     for (KVMap::const_iterator it = data.begin();
          it != data.end();
          ++it) {
       memtable_->Add(seq, kTypeValue, it->first, it->second);
       seq++;
     }
     return Status::OK();
   }
virtual Iterator* rocksdb::MemTableConstructor::NewIterator () const inline virtual
Implements rocksdb::Constructor.
Definition at line 392 of file table_test.cc.
References memtable_, and rocksdb::MemTable::NewIterator().
{
     return new KeyConvertingIterator(memtable_->NewIterator());
   }
Member Data Documentation
InternalKeyComparator rocksdb::MemTableConstructor::internal_comparator_ private
Definition at line 397 of file table_test.cc.
Referenced by FinishImpl(), and MemTableConstructor().
MemTable* rocksdb::MemTableConstructor::memtable_ private
Definition at line 398 of file table_test.cc.
Referenced by FinishImpl(), MemTableConstructor(), NewIterator(), and ~MemTableConstructor().
std::shared_ptr<SkipListFactory> rocksdb::MemTableConstructor::table_factory_ private
Definition at line 399 of file table_test.cc.
Referenced by FinishImpl(), and MemTableConstructor().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/table/table_test.cc