rippled: beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::config_t Class Reference
beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::config_t Class Reference
Public Member Functions
config_t (clock_type &clock_)
config_t (clock_type &clock_, Compare const &comp)
config_t (clock_type &clock_, Allocator const &alloc_)
config_t (clock_type &clock_, Compare const &comp, Allocator const &alloc_)
config_t (config_t const &other)
config_t (config_t const &other, Allocator const &alloc)
config_t (config_t &&other)
config_t (config_t &&other, Allocator const &alloc)
config_t & operator= (config_t const &other)
config_t & operator= (config_t &&other)
Compare & compare ()
Compare const & compare () const
KeyValueCompare & key_compare ()
KeyValueCompare const & key_compare () const
ElementAllocator & alloc ()
ElementAllocator const & alloc () const
Public Attributes
std::reference_wrapper
< clock_type > clock
Additional Inherited Members
Private Member Functions inherited from beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::KeyValueCompare
KeyValueCompare ()
KeyValueCompare (Compare const &compare)
bool operator() (Key const &k, element const &e) const
bool operator() (element const &e, Key const &k) const
Compare & compare ()
Compare const & compare () const
Private Member Functions inherited from beast::empty_base_optimization< ElementAllocator >
empty_base_optimization ()=default
empty_base_optimization (ElementAllocatorconst &t)
empty_base_optimization (ElementAllocator &&t)
ElementAllocator & member () noexcept
ElementAllocatorconst & member () const noexcept
Detailed Description
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>>
class beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::config_t
Definition at line 254 of file aged_ordered_container.h.
Constructor & Destructor Documentation
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::config_t::config_t (clock_type & clock_) inline explicit
Definition at line 259 of file aged_ordered_container.h.
             : clock (clock_)
         {
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::config_t::config_t (clock_type & clock_, Compare const & comp) inline
Definition at line 265 of file aged_ordered_container.h.
             : KeyValueCompare (comp)
             , clock (clock_)
         {
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::config_t::config_t (clock_type & clock_, Allocator const & alloc_) inline
Definition at line 273 of file aged_ordered_container.h.
             : empty_base_optimization <ElementAllocator> (alloc_)
             , clock (clock_)
         {
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::config_t::config_t (clock_type & clock_, Compare const & comp, Allocator const & alloc_) inline
Definition at line 281 of file aged_ordered_container.h.
             : KeyValueCompare (comp)
             , empty_base_optimization <ElementAllocator> (alloc_)
             , clock (clock_)
         {
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::config_t::config_t (config_t const & other) inline
Definition at line 291 of file aged_ordered_container.h.
             : KeyValueCompare (other.key_compare())
             , empty_base_optimization <ElementAllocator> (
                 ElementAllocatorTraits::
                     select_on_container_copy_construction (
                         other.alloc()))
             , clock (other.clock)
         {
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::config_t::config_t (config_t const & other, Allocator const & alloc) inline
Definition at line 301 of file aged_ordered_container.h.
             : KeyValueCompare (other.key_compare())
             , empty_base_optimization <ElementAllocator> (alloc)
             , clock (other.clock)
         {
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::config_t::config_t (config_t && other) inline
Definition at line 308 of file aged_ordered_container.h.
             : KeyValueCompare (std::move (other.key_compare()))
             , empty_base_optimization <ElementAllocator> (
                 std::move (other))
             , clock (other.clock)
         {
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::config_t::config_t (config_t && other, Allocator const & alloc) inline
Definition at line 316 of file aged_ordered_container.h.
             : KeyValueCompare (std::move (other.key_compare()))
             , empty_base_optimization <ElementAllocator> (alloc)
             , clock (other.clock)
         {
         }
Member Function Documentation
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> ElementAllocator& beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::config_t::alloc () inline
Definition at line 362 of file aged_ordered_container.h.
References beast::empty_base_optimization< ElementAllocator >::member().
Referenced by beast::detail::aged_ordered_container< beast::IP::Address >::delete_element(), beast::detail::aged_ordered_container< beast::IP::Address >::get_allocator(), beast::detail::aged_ordered_container< beast::IP::Address >::new_element(), and beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::config_t::operator=().
         {
             return empty_base_optimization <
                 ElementAllocator>::member();
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> ElementAllocator const& beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::config_t::alloc () const inline
Definition at line 368 of file aged_ordered_container.h.
References beast::empty_base_optimization< ElementAllocator >::member().
         {
             return empty_base_optimization <
                 ElementAllocator>::member();
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> Compare& beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::config_t::compare () inline
Definition at line 342 of file aged_ordered_container.h.
References beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::KeyValueCompare::compare().
Referenced by beast::detail::aged_ordered_container< beast::IP::Address >::key_comp(), beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::config_t::operator=(), and beast::detail::aged_ordered_container< beast::IP::Address >::value_comp().
         {
             return KeyValueCompare::compare();
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> Compare const& beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::config_t::compare () const inline
Definition at line 347 of file aged_ordered_container.h.
References beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::KeyValueCompare::compare().
         {
             return KeyValueCompare::compare();
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> KeyValueCompare& beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::config_t::key_compare () inline
Definition at line 352 of file aged_ordered_container.h.
Referenced by beast::detail::aged_ordered_container< beast::IP::Address >::count(), beast::detail::aged_ordered_container< beast::IP::Address >::equal_range(), beast::detail::aged_ordered_container< beast::IP::Address >::find(), beast::detail::aged_ordered_container< beast::IP::Address >::lower_bound(), and beast::detail::aged_ordered_container< beast::IP::Address >::upper_bound().
         {
             return *this;
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> KeyValueCompare const& beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::config_t::key_compare () const inline
Definition at line 357 of file aged_ordered_container.h.
         {
             return *this;
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> config_t& beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::config_t::operator= (config_t const & other) inline
Definition at line 323 of file aged_ordered_container.h.
References beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::config_t::alloc(), beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::config_t::clock, and beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::config_t::compare().
         {
             if (this != &other)
             {
                 compare() = other.compare();
                 alloc() = other.alloc();
                 clock = other.clock;
             }
             return *this;
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> config_t& beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::config_t::operator= (config_t && other) inline
Definition at line 334 of file aged_ordered_container.h.
References beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::config_t::alloc(), beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::config_t::clock, and beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::config_t::compare().
         {
             compare() = std::move (other.compare());
             alloc() = std::move (other.alloc());
             clock = other.clock;
             return *this;
         }
Member Data Documentation
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> std::reference_wrapper<clock_type> beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::config_t::clock
Definition at line 374 of file aged_ordered_container.h.
Referenced by beast::detail::aged_ordered_container< beast::IP::Address >::clock(), and beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::config_t::operator=().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/container/detail/aged_ordered_container.h