rippled: rippled/src/ripple/rocksdb/rocksdb/tools/sst_dump.cc File Reference
sst_dump.cc File Reference
#include <map>
#include <string>
#include <vector>
#include "db/dbformat.h"
#include "db/memtable.h"
#include "db/write_batch_internal.h"
#include "rocksdb/db.h"
#include "rocksdb/env.h"
#include "rocksdb/iterator.h"
#include "rocksdb/table.h"
#include "table/block.h"
#include "table/block_builder.h"
#include "table/format.h"
#include "util/ldb_cmd.h"
#include "util/random.h"
#include "util/testharness.h"
#include "util/testutil.h"
Classes
class rocksdb::SstFileReader
Namespaces
rocksdb
Constant Groups
rocksdb
Functions
static void print_help ()
string HexToString (const string &str)
int main (int argc, char **argv)
Function Documentation
string HexToString (const string & str)
Definition at line 143 of file sst_dump.cc.
Referenced by rocksdb::is_input_key_hex_(), main(), rocksdb::max_keys_scanned_(), rocksdb::null_to_(), rocksdb::LDBCommand::ParseKeyValue(), and rocksdb::print_stats_().
{
   string parsed;
   if (str[0] != '0' || str[1] != 'x') {
     fprintf(stderr, "Invalid hex input %s.  Must start with 0x\n",
             str.c_str());
     throw "Invalid hex input";
   }
   for (unsigned int i = 2; i < str.length();) {
     int c;
     sscanf(str.c_str() + i, "%2X", &c);
     parsed.push_back(c);
     i += 2;
   }
   return parsed;
 }
int main (int argc, char ** argv)
Definition at line 160 of file sst_dump.cc.
References rocksdb::Env::Default(), env, filename, rocksdb::Env::GetChildren(), rocksdb::SstFileReader::GetReadNumber(), HexToString(), rocksdb::Status::ok(), print_help(), rocksdb::SstFileReader::ReadSequential(), rocksdb::Slice::ToString(), and rocksdb::Status::ToString().
{
   const char* dir_or_file = nullptr;
   uint64_t read_num = -1;
   std::string command;
   char junk;
   uint64_t n;
   bool verify_checksum = false;
   bool output_hex = false;
   bool input_key_hex = false;
   bool has_from = false;
   bool has_to = false;
   std::string from_key;
   std::string to_key;
   for (int i = 1; i < argc; i++)
   {
     if (strncmp(argv[i], "--file=", 7) == 0) {
       dir_or_file = argv[i] + 7;
     } else if (strcmp(argv[i], "--output_hex") == 0) {
       output_hex = true;
     } else if (strcmp(argv[i], "--input_key_hex") == 0) {
       input_key_hex = true;
     } else if (sscanf(argv[i],
                "--read_num=%lu%c",
                (unsigned long*)&n, &junk) == 1) {
       read_num = n;
     } else if (strcmp(argv[i], "--verify_checksum") == 0) {
       verify_checksum = true;
     } else if (strncmp(argv[i], "--command=", 10) == 0) {
       command = argv[i] + 10;
     } else if (strncmp(argv[i], "--from=", 7) == 0) {
       from_key = argv[i] + 7;
       has_from = true;
     } else if (strncmp(argv[i], "--to=", 5) == 0) {
       to_key = argv[i] + 5;
       has_to = true;
     }else {
       print_help();
       exit(1);
     }
   }
   if (input_key_hex) {
     if (has_from) {
       from_key = HexToString(from_key);
     }
     if (has_to) {
       to_key = HexToString(to_key);
     }
   }
   if(dir_or_file == nullptr) {
     print_help();
     exit(1);
   }
   std::vector<std::string> filenames;
   rocksdb::Env* env = rocksdb::Env::Default();
   rocksdb::Status st = env->GetChildren(dir_or_file, &filenames);
   bool dir = true;
   if (!st.ok()) {
     filenames.clear();
     filenames.push_back(dir_or_file);
     dir = false;
   }
   std::cout << "from [" << rocksdb::Slice(from_key).ToString(true)
             << "] to [" << rocksdb::Slice(to_key).ToString(true) << "]\n";
   uint64_t total_read = 0;
   for (size_t i = 0; i < filenames.size(); i++) {
     std::string filename = filenames.at(i);
     if (filename.length() <= 4 ||
         filename.rfind(".sst") != filename.length() - 4) {
       //ignore
       continue;
     }
     if(dir) {
       filename = std::string(dir_or_file) + "/" + filename;
     }
     rocksdb::SstFileReader reader(filename, verify_checksum,
                                   output_hex);
     rocksdb::Status st;
     // scan all files in give file path.
     if (command == "" || command == "scan" || command == "check") {
       st = reader.ReadSequential(command != "check",
                                  read_num > 0 ? (read_num - total_read) :
                                                 read_num,
                                  has_from, from_key, has_to, to_key);
       if (!st.ok()) {
         fprintf(stderr, "%s: %s\n", filename.c_str(),
             st.ToString().c_str());
       }
       total_read += reader.GetReadNumber();
       if (read_num > 0 && total_read > read_num) {
         break;
       }
     }
   }
 }
static void print_help () static
Definition at line 132 of file sst_dump.cc.
Referenced by main().
{
   fprintf(stderr,
       "sst_dump [--command=check|scan] [--verify_checksum] "
       "--file=data_dir_OR_sst_file"
       " [--output_hex]"
       " [--input_key_hex]"
       " [--from=<user_key>]"
       " [--to=<user_key>]"
       " [--read_num=NUM]\n");
 }