rippled: beast::insight::Collector Class Reference
beast::insight::Collector Class Reference abstract
#include <Collector.h>
Public Types
typedef std::shared_ptr
< Collector > ptr
Public Member Functions
virtual ~Collector ()=0
template<class Handler >
Hook make_hook (Handler handler)
virtual Hook make_hook (HookImpl::HandlerType const &handler)=0
virtual Counter make_counter (std::string const &name)=0
Counter make_counter (std::string const &prefix, std::string const &name)
virtual Event make_event (std::string const &name)=0
Event make_event (std::string const &prefix, std::string const &name)
virtual Gauge make_gauge (std::string const &name)=0
Gauge make_gauge (std::string const &prefix, std::string const &name)
virtual Meter make_meter (std::string const &name)=0
Meter make_meter (std::string const &prefix, std::string const &name)
Detailed Description
Interface for a manager that allows collection of metrics.
To export metrics from a class, pass and save a shared_ptr to this interface in the class constructor. Create the metric objects as desired (counters, events, gauges, meters, and an optional hook) using the interface.
See Also
Counter, Event, Gauge, Hook, Meter
NullCollector, StatsDCollector
Definition at line 44 of file Collector.h.
Member Typedef Documentation
typedef std::shared_ptr<Collector> beast::insight::Collector::ptr
Definition at line 47 of file Collector.h.
Constructor & Destructor Documentation
beast::insight::Collector::~Collector () pure virtual
Definition at line 23 of file Collector.cpp.
 {
 }
Member Function Documentation
virtual Counter beast::insight::Collector::make_counter (std::string const & name) pure virtual
Create a counter with the specified name.
See Also
Counter
Implemented in beast::insight::detail::StatsDCollectorImp, beast::insight::detail::NullCollectorImp, and beast::insight::detail::GroupImp.
Referenced by make_counter().
Counter beast::insight::Collector::make_counter (std::string const & prefix, std::string const & name) inline
Definition at line 79 of file Collector.h.
References make_counter().
     {
         if (prefix.empty ())
             return make_counter (name);
         return make_counter (prefix + "." + name);
     }
virtual Event beast::insight::Collector::make_event (std::string const & name) pure virtual
Create an event with the specified name.
See Also
Event
Implemented in beast::insight::detail::StatsDCollectorImp, beast::insight::detail::NullCollectorImp, and beast::insight::detail::GroupImp.
Referenced by make_event().
Event beast::insight::Collector::make_event (std::string const & prefix, std::string const & name) inline
Definition at line 93 of file Collector.h.
References make_event().
     {
         if (prefix.empty ())
             return make_event (name);
         return make_event (prefix + "." + name);
     }
virtual Gauge beast::insight::Collector::make_gauge (std::string const & name) pure virtual
Create a gauge with the specified name.
See Also
Gauge
Implemented in beast::insight::detail::StatsDCollectorImp, beast::insight::detail::NullCollectorImp, and beast::insight::detail::GroupImp.
Referenced by make_gauge().
Gauge beast::insight::Collector::make_gauge (std::string const & prefix, std::string const & name) inline
Definition at line 107 of file Collector.h.
References make_gauge().
     {
         if (prefix.empty ())
             return make_gauge (name);
         return make_gauge (prefix + "." + name);
     }
template<class Handler > Hook beast::insight::Collector::make_hook (Handler handler) inline
Create a hook.
A hook is called at each collection interval, on an implementation defined thread. This is a convenience facility for gathering metrics in the polling style. The typical usage is to update all the metrics of interest in the handler.
Handler will be called with this signature: void handler (void)
See Also
Hook
Definition at line 65 of file Collector.h.
     {
         return make_hook (HookImpl::HandlerType (handler));
     }
virtual Hook beast::insight::Collector::make_hook (HookImpl::HandlerType const & handler) pure virtual
Implemented in beast::insight::detail::StatsDCollectorImp, beast::insight::detail::NullCollectorImp, and beast::insight::detail::GroupImp.
virtual Meter beast::insight::Collector::make_meter (std::string const & name) pure virtual
Create a meter with the specified name.
See Also
Meter
Implemented in beast::insight::detail::StatsDCollectorImp, beast::insight::detail::NullCollectorImp, and beast::insight::detail::GroupImp.
Referenced by make_meter().
Meter beast::insight::Collector::make_meter (std::string const & prefix, std::string const & name) inline
Definition at line 121 of file Collector.h.
References make_meter().
     {
         if (prefix.empty ())
             return make_meter (name);
         return make_meter (prefix + "." + name);
     }
The documentation for this class was generated from the following files:
rippled/src/beast/beast/insight/Collector.h
rippled/src/beast/beast/insight/impl/Collector.cpp