rippled: ripple::RPCCall Class Reference
ripple::RPCCall Class Reference
#include <RPCCall.h>
Static Public Member Functions
static int fromCommandLine (const std::vector< std::string > &vCmd)
static void fromNetwork (boost::asio::io_service &io_service, const std::string &strIp, const int iPort, const std::string &strUsername, const std::string &strPassword, const std::string &strPath, const std::string &strMethod, const Json::Value &jvParams, const bool bSSL, std::function< void(const Json::Value &jvInput)> callbackFuncP=std::function< void(const Json::Value &jvInput)>())
Detailed Description
Processes Ripple RPC calls.
Definition at line 34 of file RPCCall.h.
Member Function Documentation
int ripple::RPCCall::fromCommandLine (const std::vector< std::string > & vCmd) static
Definition at line 956 of file RPCCall.cpp.
References Json::Value::append(), Json::arrayValue, Json::Value::asString(), BIND_TYPE, ripple::RPCCallImp::callRPCHandler(), fromNetwork(), ripple::getConfig(), Json::Value::isMember(), ripple::lsTRACE, Json::objectValue, P_1, ripple::RPCParser::parseCommand(), ripple::Config::RPC_ADMIN_PASSWORD, ripple::Config::RPC_ADMIN_USER, ripple::rpcError(), ripple::rpcINTERNAL, ripple::rpcJSON_RPC, Json::Value::toStyledString(), rocksdb::crc32c::Value(), and WriteLog.
Referenced by ripple::run().
 {
     Json::Value jvOutput;
     int         nRet = 0;
     Json::Value jvRequest (Json::objectValue);
     try
     {
         RPCParser   rpParser;
         Json::Value jvRpcParams (Json::arrayValue);
         if (vCmd.empty ()) return 1;                                            // 1 = print usage.
         for (int i = 1; i != vCmd.size (); i++)
             jvRpcParams.append (vCmd[i]);
         Json::Value jvRpc   = Json::Value (Json::objectValue);
         jvRpc["method"] = vCmd[0];
         jvRpc["params"] = jvRpcParams;
         jvRequest   = rpParser.parseCommand (vCmd[0], jvRpcParams, true);
         WriteLog (lsTRACE, RPCParser) << "RPC Request: " << jvRequest << std::endl;
         if (jvRequest.isMember ("error"))
         {
             jvOutput            = jvRequest;
             jvOutput["rpc"]     = jvRpc;
         }
         else
         {
             Json::Value jvParams (Json::arrayValue);
             jvParams.append (jvRequest);
             if (!getConfig ().RPC_ADMIN_USER.empty ())
                 jvRequest["admin_user"]     = getConfig ().RPC_ADMIN_USER;
             if (!getConfig ().RPC_ADMIN_PASSWORD.empty ())
                 jvRequest["admin_password"] = getConfig ().RPC_ADMIN_PASSWORD;
             boost::asio::io_service         isService;
             fromNetwork (
                 isService,
                 getConfig ().getRpcIP (),
                 getConfig ().getRpcPort (),
                 getConfig ().RPC_USER,
                 getConfig ().RPC_PASSWORD,
                 "",
                 jvRequest.isMember ("method")           // Allow parser to rewrite method.
                     ? jvRequest["method"].asString () : vCmd[0],
                 jvParams,                               // Parsed, execute.
                 false,
                 BIND_TYPE (RPCCallImp::callRPCHandler, &jvOutput, P_1));
             isService.run (); // This blocks until there is no more outstanding async calls.
             if (jvOutput.isMember ("result"))
             {
                 // Had a successful JSON-RPC 2.0 call.
                 jvOutput    = jvOutput["result"];
                 // jvOutput may report a server side error.
                 // It should report "status".
             }
             else
             {
                 // Transport error.
                 Json::Value jvRpcError  = jvOutput;
                 jvOutput            = rpcError (rpcJSON_RPC);
                 jvOutput["result"]  = jvRpcError;
             }
             // If had an error, supply invokation in result.
             if (jvOutput.isMember ("error"))
             {
                 jvOutput["rpc"]             = jvRpc;            // How the command was seen as method + params.
                 jvOutput["request_sent"]    = jvRequest;        // How the command was translated.
             }
         }
         if (jvOutput.isMember ("error"))
         {
             jvOutput["status"]  = "error";
             nRet    = jvOutput.isMember ("error_code")
                       ? beast::lexicalCast <int> (jvOutput["error_code"].asString ())
                       : 1;
         }
         // YYY We could have a command line flag for single line output for scripts.
         // YYY We would intercept output here and simplify it.
     }
     catch (std::exception& e)
     {
         jvOutput                = rpcError (rpcINTERNAL);
         jvOutput["error_what"]  = e.what ();
         nRet                    = rpcINTERNAL;
     }
     catch (...)
     {
         jvOutput                = rpcError (rpcINTERNAL);
         jvOutput["error_what"]  = "exception";
         nRet                    = rpcINTERNAL;
     }
     std::cout << jvOutput.toStyledString ();
     return nRet;
 }
void ripple::RPCCall::fromNetwork (boost::asio::io_service & io_service, const std::string & strIp, const int iPort, const std::string & strUsername, const std::string & strPassword, const std::string & strPath, const std::string & strMethod, const Json::Value & jvParams, const bool bSSL, std::function< void(const Json::Value &jvInput)> callbackFuncP = std::function<void (const Json::Value& jvInput)> ()) static
Definition at line 1072 of file RPCCall.cpp.
References BIND_TYPE, ripple::RPCParser::EncodeBase64(), ripple::getConfig(), ripple::RPCCallImp::onRequest(), ripple::RPCCallImp::onResponse(), P_1, P_2, P_3, and ripple::HTTPClient::request().
Referenced by fromCommandLine(), and ripple::RPCSubImp::sendThread().
 {
     // Connect to localhost
     if (!getConfig ().QUIET)
     {
         Log::out() << "Connecting to: " << strIp << ":" << iPort;
         //  Log::out() << "Username: " << strUsername << ":" << strPassword;
         //  Log::out() << "Path: " << strPath;
         //  Log::out() << "Method: " << strMethod;
     }
     // HTTP basic authentication
     std::string strUserPass64 = RPCParser::EncodeBase64 (strUsername + ":" + strPassword);
     std::map<std::string, std::string> mapRequestHeaders;
     mapRequestHeaders["Authorization"] = std::string ("Basic ") + strUserPass64;
     // Send request
     // Log(lsDEBUG) << "requesting" << std::endl;
     // WriteLog (lsDEBUG, RPCParser) << "send request " << strMethod << " : " << strRequest << std::endl;
     const int RPC_REPLY_MAX_BYTES (256*1024*1024);
     const int RPC_NOTIFY_SECONDS (600);
     HTTPClient::request (
         bSSL,
         io_service,
         strIp,
         iPort,
         BIND_TYPE (
             &RPCCallImp::onRequest,
             strMethod,
             jvParams,
             mapRequestHeaders,
             strPath, P_1, P_2),
         RPC_REPLY_MAX_BYTES,
         boost::posix_time::seconds (RPC_NOTIFY_SECONDS),
         BIND_TYPE (&RPCCallImp::onResponse, callbackFuncP, P_1, P_2, P_3));
 }
The documentation for this class was generated from the following files:
rippled/src/ripple_net/rpc/RPCCall.h
rippled/src/ripple_net/rpc/RPCCall.cpp