rippled: ripple::version::CheckLibraryVersions_test Struct Reference
ripple::version::CheckLibraryVersions_test Struct Reference
Public Member Functions
void print_message ()
void test_bad_ssl ()
void test_bad_boost ()
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 98 of file CheckLibraryVersions.cpp.
Member Function Documentation
void ripple::version::CheckLibraryVersions_test::print_message () inline
Definition at line 100 of file CheckLibraryVersions.cpp.
References ripple::version::boostMinimal, ripple::version::boostVersion(), beast::unit_test::suite::log, ripple::version::openSSLMinimal, and ripple::version::openSSLVersion().
Referenced by run().
     {
         log << "ssl minimal: " << openSSLMinimal << "\n"
             << "ssl actual:  " << openSSLVersion() << "\n"
             << "boost minimal: " << boostMinimal << "\n"
             << "boost actual:  " << boostVersion() << "\n"
             << std::flush;
     }
void ripple::version::CheckLibraryVersions_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 138 of file CheckLibraryVersions.cpp.
References ripple::version::checkLibraryVersions(), print_message(), test_bad_boost(), and test_bad_ssl().
     {
         print_message();
         checkLibraryVersions();
         test_bad_ssl();
         test_bad_boost();
     }
void ripple::version::CheckLibraryVersions_test::test_bad_boost () inline
Definition at line 123 of file CheckLibraryVersions.cpp.
References ripple::version::boostVersion(), ripple::version::checkBoost(), and beast::unit_test::suite::unexpected().
Referenced by run().
     {
         std::string error;
         try {
             checkBoost(boostVersion(105400));
         } catch (std::runtime_error& e) {
             error = e.what();
         }
         auto expectedError = "Your Boost library is out of date.\n"
           "Your version: 1.54.0\n"
           "Required version: ";
         unexpected(error.find(expectedError) != 0, error);
     }
void ripple::version::CheckLibraryVersions_test::test_bad_ssl () inline
Definition at line 109 of file CheckLibraryVersions.cpp.
References ripple::version::checkOpenSSL(), ripple::version::openSSLVersion(), and beast::unit_test::suite::unexpected().
Referenced by run().
     {
         std::string error;
         try {
             checkOpenSSL(openSSLVersion(0x0090819fL));
         } catch (std::runtime_error& e) {
             error = e.what();
         }
         auto expectedError = "Your OpenSSL library is out of date.\n"
           "Your version: 0.9.8-o\n"
           "Required version: ";
         unexpected(error.find(expectedError) != 0, error);
     }
The documentation for this struct was generated from the following file:
rippled/src/ripple_basics/system/CheckLibraryVersions.cpp