rippled: ripple::TestOverlay Namespace Reference
ripple::TestOverlay Namespace Reference
Classes
class Network1_test
class is_to_pred
class BasicMessage
class BasicLink
class BasicPeer
class BasicNetwork
class Network2_test
struct Results
class SimplePayload
class MessageType
class ConnectionType
class PeerType
class NetworkType
class StateBase
class PeerLogicBase
class NoInitPolicy
class PremadeInitPolicy
class ConfigType
Functions
template<typename PeerType >
is_to_pred< PeerType > is_to (PeerType const &to)
template<typename PeerType >
bool is_connected (PeerType const &from, PeerType const &to)
template<typename PeerContainer >
void iterate (PeerContainer &s)
BEAST_DEFINE_TESTSUITE_MANUAL (Network1, overlay, ripple)
BEAST_DEFINE_TESTSUITE_MANUAL (Network2, overlay, ripple)
Detailed Description
A simulated peer to peer network for unit tests.
Function Documentation
ripple::TestOverlay::BEAST_DEFINE_TESTSUITE_MANUAL (Network1 , overlay , ripple)
ripple::TestOverlay::BEAST_DEFINE_TESTSUITE_MANUAL (Network2 , overlay , ripple)
template<typename PeerType > bool ripple::TestOverlay::is_connected (PeerType const & from, PeerType const & to)
Returns true if the peers are connected.
Definition at line 196 of file TestOverlay.cpp.
References is_to().
Referenced by ripple::TestOverlay::Network2_test::make_connections().
 {
     return std::find_if (from.links().begin(), from.links().end(),
         is_to (to)) != from.links().end();
 }
template<typename PeerType > is_to_pred<PeerType> ripple::TestOverlay::is_to (PeerType const & to)
Returns a new is_to_pred for the specified peer.
Definition at line 189 of file TestOverlay.cpp.
Referenced by ripple::TestOverlay::BasicPeer< Peer, Message >::disconnect(), is_connected(), and ripple::TestOverlay::BasicPeer< Peer, Message >::~BasicPeer().
 {
     return is_to_pred <PeerType> (to);
 }
template<typename PeerContainer > void ripple::TestOverlay::iterate (PeerContainer & s)
Definition at line 385 of file TestOverlay.cpp.
Referenced by ripple::TestOverlay::Network2_test::test1().
 {
     for (typename PeerContainer::iterator iter (s.begin()); iter != s.end();)
     {
         typename PeerContainer::iterator const cur (iter++);
         cur->pre_step();
     }
     for (typename PeerContainer::iterator iter (s.begin()); iter != s.end();)
     {
         typename PeerContainer::iterator const cur (iter++);
         cur->step();
     }
 }