rippled: ripple::NodeStore::Backend Class Reference
ripple::NodeStore::Backend Class Reference abstract
#include <Backend.h>
Public Member Functions
virtual ~Backend ()=0
virtual std::string getName ()=0
virtual Status fetch (void const *key, NodeObject::Ptr *pObject)=0
virtual void store (NodeObject::Ptr const &object)=0
virtual void storeBatch (Batch const &batch)=0
virtual void visitAll (VisitCallback &callback)=0
virtual int getWriteLoad ()=0
Detailed Description
A backend used for the store.
The NodeStore uses a swappable backend so that other database systems can be tried. Different databases may offer various features such as improved performance, fault tolerant or distributed storage, or all in-memory operation.
A given instance of a backend is fixed to a particular key size.
Definition at line 35 of file Backend.h.
Constructor & Destructor Documentation
ripple::NodeStore::Backend::~Backend () pure virtual
Destroy the backend.
All open files are closed and flushed. If there are batched writes or other tasks scheduled, they will be completed before this call returns.
Definition at line 23 of file Backend.cpp.
 {
 }
Member Function Documentation
virtual Status ripple::NodeStore::Backend::fetch (void const * key, NodeObject::Ptr * pObject) pure virtual
Fetch a single object. If the object is not found or an error is encountered, the result will indicate the condition.
Note
This will be called concurrently.
Parameters
key A pointer to the key data.
pObject [out] The created object if successful.
Returns
The result of the operation.
Implemented in ripple::NodeStore::LevelDBBackend, ripple::SqliteBackend, ripple::NodeStore::MemoryBackend, and ripple::NodeStore::NullBackend.
Referenced by ripple::NodeStore::TestBase::fetchCopyOfBatch(), and ripple::NodeStore::DatabaseImp::fetchInternal().
virtual std::string ripple::NodeStore::Backend::getName () pure virtual
Get the human-readable name of this backend. This is used for diagnostic output.
Implemented in ripple::NodeStore::LevelDBBackend, ripple::SqliteBackend, ripple::NodeStore::MemoryBackend, and ripple::NodeStore::NullBackend.
virtual int ripple::NodeStore::Backend::getWriteLoad () pure virtual
Estimate the number of write operations pending.
Implemented in ripple::NodeStore::LevelDBBackend, ripple::SqliteBackend, ripple::NodeStore::MemoryBackend, and ripple::NodeStore::NullBackend.
virtual void ripple::NodeStore::Backend::store (NodeObject::Ptr const & object) pure virtual
Store a single object. Depending on the implementation this may happen immediately or deferred using a scheduled task.
Note
This will be called concurrently.
Parameters
object The object to store.
Referenced by ripple::NodeStore::TestBase::storeBatch().
virtual void ripple::NodeStore::Backend::storeBatch (Batch const & batch) pure virtual
Store a group of objects.
Note
This function will not be called concurrently with itself or store.
Implemented in ripple::NodeStore::LevelDBBackend, ripple::SqliteBackend, ripple::NodeStore::MemoryBackend, and ripple::NodeStore::NullBackend.
virtual void ripple::NodeStore::Backend::visitAll (VisitCallback & callback) pure virtual
Visit every object in the database This is usually called during import.
Note
This routine will not be called concurrently with itself or other methods.
See Also
import, VisitCallback
Implemented in ripple::NodeStore::LevelDBBackend, ripple::SqliteBackend, ripple::NodeStore::MemoryBackend, and ripple::NodeStore::NullBackend.
The documentation for this class was generated from the following files:
rippled/src/ripple_core/nodestore/api/Backend.h
rippled/src/ripple_core/nodestore/impl/Backend.cpp