rippled: ripple::CKey_test Class Reference
ripple::CKey_test Class Reference
Public Member Functions
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 32 of file CKey.cpp.
Member Function Documentation
void ripple::CKey_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 36 of file CKey.cpp.
References ripple::base_uint< BITS >::GetHex(), ripple::CKey::GetPrivateKeyU(), ripple::base_uint< BITS >::SetHex(), ripple::RippleAddress::setSeed(), and beast::unit_test::suite::unexpected().
     {
         uint128 seed1, seed2;
         seed1.SetHex ("71ED064155FFADFA38782C5E0158CB26");
         seed2.SetHex ("CF0C3BE4485961858C4198515AE5B965");
         CKey root1 (seed1), root2 (seed2);
         uint256 priv1, priv2;
         root1.GetPrivateKeyU (priv1);
         root2.GetPrivateKeyU (priv2);
         unexpected (priv1.GetHex () != "7CFBA64F771E93E817E15039215430B53F7401C34931D111EAB3510B22DBB0D8",
             "Incorrect private key for generator");
         unexpected (priv2.GetHex () != "98BC2EACB26EB021D1A6293C044D88BA2F0B6729A2772DEEBF2E21A263C1740B",
             "Incorrect private key for generator");
         RippleAddress nSeed;
         nSeed.setSeed (seed1);
         unexpected (nSeed.humanSeed () != "shHM53KPZ87Gwdqarm1bAmPeXg8Tn",
             "Incorrect human seed");
         unexpected (nSeed.humanSeed1751 () != "MAD BODY ACE MINT OKAY HUB WHAT DATA SACK FLAT DANA MATH",
             "Incorrect 1751 seed");
     }
The documentation for this class was generated from the following file:
rippled/src/ripple_data/crypto/CKey.cpp