rippled: rocksdb::SimpleTableIterator Class Reference
rocksdb::SimpleTableIterator Class Reference
Public Member Functions
SimpleTableIterator (SimpleTableReader *table)
~SimpleTableIterator ()
bool Valid () const
void SeekToFirst ()
void SeekToLast ()
void Seek (const Slice &target)
void Next ()
void Prev ()
Slice key () const
Slice value () const
Status status () const
Public Member Functions inherited from rocksdb::Iterator
Iterator ()
virtual ~Iterator ()
void RegisterCleanup (CleanupFunction function, void *arg1, void *arg2)
Private Member Functions
SimpleTableIterator (const SimpleTableIterator &)=delete
void operator= (const Iterator &)=delete
Private Attributes
SimpleTableReader * table_
uint64_t offset_
uint64_t next_offset_
Slice key_
Slice value_
char tmp_str_ [4]
char * key_str_
char * value_str_
int value_str_len_
Status status_
Additional Inherited Members
Public Types inherited from rocksdb::Iterator
typedef void(* CleanupFunction)(void *arg1, void *arg2)
Detailed Description
Definition at line 120 of file simple_table_db_test.cc.
Constructor & Destructor Documentation
rocksdb::SimpleTableIterator::SimpleTableIterator (SimpleTableReader * table) explicit
Definition at line 307 of file simple_table_db_test.cc.
References rocksdb::SimpleTableReader::Rep::GetInternalKeyLength(), key_str_, SeekToFirst(), and value_str_len_.
                                                                  :
     table_(table) {
   key_str_ = new char[SimpleTableReader::Rep::GetInternalKeyLength()];
   value_str_len_ = -1;
   SeekToFirst();
 }
rocksdb::SimpleTableIterator::~SimpleTableIterator ()
Definition at line 314 of file simple_table_db_test.cc.
References key_str_, value_str_, and value_str_len_.
{
  delete[] key_str_;
  if (value_str_len_ >= 0) {
    delete[] value_str_;
  }
 }
rocksdb::SimpleTableIterator::SimpleTableIterator (const SimpleTableIterator &) private delete
Member Function Documentation
Slice rocksdb::SimpleTableIterator::key () const virtual
Implements rocksdb::Iterator.
Definition at line 378 of file simple_table_db_test.cc.
References rocksdb::Options::info_log, key_, rocksdb::Log(), rocksdb::SimpleTableReader::Rep::options, rocksdb::SimpleTableReader::rep_, and table_.
Referenced by rocksdb::SimpleTableReader::Get().
{
   Log(table_->rep_->options.info_log, "key!!!!");
   return key_;
 }
void rocksdb::SimpleTableIterator::Next () virtual
Implements rocksdb::Iterator.
Definition at line 342 of file simple_table_db_test.cc.
References rocksdb::DecodeFixed32(), rocksdb::SimpleTableReader::Rep::file, rocksdb::SimpleTableReader::Rep::GetInternalKeyLength(), rocksdb::SimpleTableReader::Rep::index_start_offset, key_, key_str_, next_offset_, offset_, rocksdb::SimpleTableReader::rep_, table_, tmp_str_, value_, value_str_, and value_str_len_.
Referenced by rocksdb::SimpleTableReader::Get(), Seek(), and SeekToFirst().
{
   offset_ = next_offset_;
   if (offset_ >= table_->rep_->index_start_offset) {
     return;
   }
   Slice result;
   int internal_key_size = SimpleTableReader::Rep::GetInternalKeyLength();
   Status s = table_->rep_->file->Read(next_offset_, internal_key_size, &result,
                                       key_str_);
   next_offset_ += internal_key_size;
   key_ = result;
   Slice value_size_slice;
   s = table_->rep_->file->Read(next_offset_, 4, &value_size_slice, tmp_str_);
   next_offset_ += 4;
   uint32_t value_size = DecodeFixed32(tmp_str_);
   Slice value_slice;
   if ((int) value_size > value_str_len_) {
     if (value_str_len_ >= 0) {
       delete[] value_str_;
     }
     value_str_ = new char[value_size];
     value_str_len_ = value_size;
   }
   s = table_->rep_->file->Read(next_offset_, value_size, &value_slice,
                                value_str_);
   next_offset_ += value_size;
   value_ = value_slice;
 }
void rocksdb::SimpleTableIterator::operator= (const Iterator &) private delete
void rocksdb::SimpleTableIterator::Prev () virtual
Implements rocksdb::Iterator.
Definition at line 374 of file simple_table_db_test.cc.
{
   assert(false);
 }
void rocksdb::SimpleTableIterator::Seek (const Slice & target) virtual
Implements rocksdb::Iterator.
Definition at line 334 of file simple_table_db_test.cc.
References rocksdb::SimpleTableReader::GetOffset(), Next(), next_offset_, rocksdb::Status::ok(), status_, and table_.
Referenced by rocksdb::SimpleTableReader::Get().
{
   Status s = table_->GetOffset(target, &next_offset_);
   if (!s.ok()) {
     status_ = s;
   }
   Next();
 }
void rocksdb::SimpleTableIterator::SeekToFirst () virtual
Implements rocksdb::Iterator.
Definition at line 325 of file simple_table_db_test.cc.
References Next(), and next_offset_.
Referenced by SimpleTableIterator().
{
   next_offset_ = 0;
   Next();
 }
void rocksdb::SimpleTableIterator::SeekToLast () virtual
Implements rocksdb::Iterator.
Definition at line 330 of file simple_table_db_test.cc.
{
   assert(false);
 }
Status rocksdb::SimpleTableIterator::status () const virtual
Implements rocksdb::Iterator.
Definition at line 387 of file simple_table_db_test.cc.
References status_.
Referenced by rocksdb::SimpleTableReader::Get().
{
   return status_;
 }
bool rocksdb::SimpleTableIterator::Valid () const virtual
Implements rocksdb::Iterator.
Definition at line 321 of file simple_table_db_test.cc.
References rocksdb::SimpleTableReader::Rep::index_start_offset, offset_, rocksdb::SimpleTableReader::rep_, and table_.
Referenced by rocksdb::SimpleTableReader::Get().
{
   return offset_ < table_->rep_->index_start_offset;
 }
Slice rocksdb::SimpleTableIterator::value () const virtual
Implements rocksdb::Iterator.
Definition at line 383 of file simple_table_db_test.cc.
References value_.
Referenced by rocksdb::SimpleTableReader::Get().
{
   return value_;
 }
Member Data Documentation
Slice rocksdb::SimpleTableIterator::key_ private
Definition at line 147 of file simple_table_db_test.cc.
Referenced by key(), and Next().
char* rocksdb::SimpleTableIterator::key_str_ private
Definition at line 150 of file simple_table_db_test.cc.
Referenced by Next(), SimpleTableIterator(), and ~SimpleTableIterator().
uint64_t rocksdb::SimpleTableIterator::next_offset_ private
Definition at line 146 of file simple_table_db_test.cc.
Referenced by Next(), Seek(), and SeekToFirst().
uint64_t rocksdb::SimpleTableIterator::offset_ private
Definition at line 145 of file simple_table_db_test.cc.
Referenced by Next(), and Valid().
Status rocksdb::SimpleTableIterator::status_ private
Definition at line 153 of file simple_table_db_test.cc.
Referenced by Seek(), and status().
SimpleTableReader* rocksdb::SimpleTableIterator::table_ private
Definition at line 144 of file simple_table_db_test.cc.
Referenced by key(), Next(), Seek(), and Valid().
char rocksdb::SimpleTableIterator::tmp_str_[4] private
Definition at line 149 of file simple_table_db_test.cc.
Referenced by Next().
Slice rocksdb::SimpleTableIterator::value_ private
Definition at line 148 of file simple_table_db_test.cc.
Referenced by Next(), and value().
char* rocksdb::SimpleTableIterator::value_str_ private
Definition at line 151 of file simple_table_db_test.cc.
Referenced by Next(), and ~SimpleTableIterator().
int rocksdb::SimpleTableIterator::value_str_len_ private
Definition at line 152 of file simple_table_db_test.cc.
Referenced by Next(), SimpleTableIterator(), and ~SimpleTableIterator().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/db/simple_table_db_test.cc