rippled: beast::asio::memory_buffer< T, Alloc > Class Template Reference
beast::asio::memory_buffer< T, Alloc > Class Template Reference
#include <memory_buffer.h>
Public Types
typedef std::size_t size_type
typedef std::ptrdiff_t difference_type
typedef T & reference
typedef T const & const_reference
typedef T * pointer
typedef T const * const_pointer
typedef Alloc allocator_type
typedef T * iterator
typedef T const * const_iterator
typedef std::reverse_iterator
< iterator > reverse_iterator
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator
Public Member Functions
memory_buffer ()
memory_buffer (memory_buffer &&other)
memory_buffer (size_type n)
memory_buffer (Alloc const &alloc)
memory_buffer (size_type n, Alloc const &alloc)
~memory_buffer ()
memory_buffer & operator= (memory_buffer const &)=delete
allocator_type get_allocator () const
boost::asio::mutable_buffer buffer ()
boost::asio::const_buffer buffer () const
boost::asio::mutable_buffers_1 buffers ()
boost::asio::const_buffers_1 buffers () const
operator boost::asio::mutable_buffer ()
operator boost::asio::const_buffer () const
operator boost::asio::mutable_buffers_1 ()
operator boost::asio::const_buffers_1 () const
reference at (size_type pos)
const_reference at (size_type pos) const
reference operator[] (size_type pos) noexcept
const_reference operator[] (size_type pos) const noexcept
reference back () noexcept
const_reference back () const noexcept
reference front () noexcept
const_reference front () const noexcept
pointer data () noexcept
const_pointer data () const noexcept
iterator begin () noexcept
const_iterator begin () const noexcept
const_iterator cbegin () const noexcept
iterator end () noexcept
const_iterator end () const noexcept
const_iterator cend () const noexcept
reverse_iterator rbegin () noexcept
const_reverse_iterator rbegin () const noexcept
const_reverse_iterator crbegin () const noexcept
reverse_iterator rend () noexcept
const_reverse_iterator rend () const noexcept
const_reverse_iterator crend () const noexcept
bool empty () const noexcept
size_type size () const noexcept
size_type max_size () const noexcept
size_type capacity () const noexcept
size_type bytes () const
Private Types
typedef
empty_base_optimization< Alloc > Base
using AllocTraits = std::allocator_traits< Alloc >
Private Attributes
T * m_base
std::size_t m_size
Friends
template<class U , class A >
void swap (memory_buffer< U, A > &lhs, memory_buffer< U, A > &rhs) noexcept
Additional Inherited Members
Private Member Functions inherited from beast::empty_base_optimization< Alloc >
empty_base_optimization ()=default
empty_base_optimization (Allocconst &t)
empty_base_optimization (Alloc &&t)
Alloc & member () noexcept
Allocconst & member () const noexcept
Detailed Description
template<class T, class Alloc = std::allocator <T>>
class beast::asio::memory_buffer< T, Alloc >
Definition at line 39 of file memory_buffer.h.
Member Typedef Documentation
template<class T, class Alloc = std::allocator <T>> typedef Alloc beast::asio::memory_buffer< T, Alloc >::allocator_type
Definition at line 61 of file memory_buffer.h.
template<class T, class Alloc = std::allocator <T>> using beast::asio::memory_buffer< T, Alloc >::AllocTraits = std::allocator_traits <Alloc> private
Definition at line 49 of file memory_buffer.h.
template<class T, class Alloc = std::allocator <T>> typedef empty_base_optimization<Alloc> beast::asio::memory_buffer< T, Alloc >::Base private
Definition at line 45 of file memory_buffer.h.
template<class T, class Alloc = std::allocator <T>> typedef T const* beast::asio::memory_buffer< T, Alloc >::const_iterator
Definition at line 63 of file memory_buffer.h.
template<class T, class Alloc = std::allocator <T>> typedef T const* beast::asio::memory_buffer< T, Alloc >::const_pointer
Definition at line 60 of file memory_buffer.h.
template<class T, class Alloc = std::allocator <T>> typedef T const& beast::asio::memory_buffer< T, Alloc >::const_reference
Definition at line 58 of file memory_buffer.h.
template<class T, class Alloc = std::allocator <T>> typedef std::reverse_iterator<const_iterator> beast::asio::memory_buffer< T, Alloc >::const_reverse_iterator
Definition at line 65 of file memory_buffer.h.
template<class T, class Alloc = std::allocator <T>> typedef std::ptrdiff_t beast::asio::memory_buffer< T, Alloc >::difference_type
Definition at line 56 of file memory_buffer.h.
template<class T, class Alloc = std::allocator <T>> typedef T* beast::asio::memory_buffer< T, Alloc >::iterator
Definition at line 62 of file memory_buffer.h.
template<class T, class Alloc = std::allocator <T>> typedef T* beast::asio::memory_buffer< T, Alloc >::pointer
Definition at line 59 of file memory_buffer.h.
template<class T, class Alloc = std::allocator <T>> typedef T& beast::asio::memory_buffer< T, Alloc >::reference
Definition at line 57 of file memory_buffer.h.
template<class T, class Alloc = std::allocator <T>> typedef std::reverse_iterator<iterator> beast::asio::memory_buffer< T, Alloc >::reverse_iterator
Definition at line 64 of file memory_buffer.h.
template<class T, class Alloc = std::allocator <T>> typedef std::size_t beast::asio::memory_buffer< T, Alloc >::size_type
Definition at line 55 of file memory_buffer.h.
Constructor & Destructor Documentation
template<class T, class Alloc = std::allocator <T>> beast::asio::memory_buffer< T, Alloc >::memory_buffer () inline
Definition at line 67 of file memory_buffer.h.
         : m_base (nullptr)
         , m_size (0)
     {
     }
template<class T, class Alloc = std::allocator <T>> beast::asio::memory_buffer< T, Alloc >::memory_buffer (memory_buffer< T, Alloc > && other) inline
Definition at line 73 of file memory_buffer.h.
         : Base (std::move (other))
         , m_base (other.m_base)
         , m_size (other.m_size)
     {
         other.m_base = nullptr;
         other.m_size = 0;
     }
template<class T, class Alloc = std::allocator <T>> beast::asio::memory_buffer< T, Alloc >::memory_buffer (size_type n) inline explicit
Definition at line 82 of file memory_buffer.h.
         : m_base (AllocTraits::allocate (Base::member(), n))
         , m_size (n)
     {
     }
template<class T, class Alloc = std::allocator <T>> beast::asio::memory_buffer< T, Alloc >::memory_buffer (Alloc const & alloc) inline explicit
Definition at line 88 of file memory_buffer.h.
         : Base (alloc)
         , m_base (nullptr)
         , m_size (0)
     {
     }
template<class T, class Alloc = std::allocator <T>> beast::asio::memory_buffer< T, Alloc >::memory_buffer (size_type n, Alloc const & alloc) inline
Definition at line 95 of file memory_buffer.h.
         : Base (alloc)
         , m_base (AllocTraits::allocate (Base::member(), n))
         , m_size (n)
     {
     }
template<class T, class Alloc = std::allocator <T>> beast::asio::memory_buffer< T, Alloc >::~memory_buffer () inline
Definition at line 102 of file memory_buffer.h.
References beast::asio::memory_buffer< T, Alloc >::m_base, beast::asio::memory_buffer< T, Alloc >::m_size, and beast::empty_base_optimization< Alloc >::member().
     {
         if (m_base != nullptr)
             AllocTraits::deallocate (Base::member(), m_base, m_size);
     }
Member Function Documentation
template<class T, class Alloc = std::allocator <T>> reference beast::asio::memory_buffer< T, Alloc >::at (size_type pos) inline
Definition at line 173 of file memory_buffer.h.
References beast::asio::memory_buffer< T, Alloc >::m_base, and beast::asio::memory_buffer< T, Alloc >::size().
     {
         if (! (pos < size()))
             throw std::out_of_range ("bad array index");
         return m_base [pos];
     }
template<class T, class Alloc = std::allocator <T>> const_reference beast::asio::memory_buffer< T, Alloc >::at (size_type pos) const inline
Definition at line 181 of file memory_buffer.h.
References beast::asio::memory_buffer< T, Alloc >::m_base, and beast::asio::memory_buffer< T, Alloc >::size().
     {
         if (! (pos < size()))
             throw std::out_of_range ("bad array index");
         return m_base [pos];
     }
template<class T, class Alloc = std::allocator <T>> reference beast::asio::memory_buffer< T, Alloc >::back () inline noexcept
Definition at line 201 of file memory_buffer.h.
References beast::asio::memory_buffer< T, Alloc >::m_base, and beast::asio::memory_buffer< T, Alloc >::m_size.
     {
         return m_base [m_size - 1];
     }
template<class T, class Alloc = std::allocator <T>> const_reference beast::asio::memory_buffer< T, Alloc >::back () const inline noexcept
Definition at line 207 of file memory_buffer.h.
References beast::asio::memory_buffer< T, Alloc >::m_base, and beast::asio::memory_buffer< T, Alloc >::m_size.
     {
         return m_base [m_size - 1];
     }
template<class T, class Alloc = std::allocator <T>> iterator beast::asio::memory_buffer< T, Alloc >::begin () inline noexcept
Definition at line 241 of file memory_buffer.h.
References beast::asio::memory_buffer< T, Alloc >::m_base.
Referenced by beast::asio::memory_buffer< T, Alloc >::rend().
     {
         return m_base;
     }
template<class T, class Alloc = std::allocator <T>> const_iterator beast::asio::memory_buffer< T, Alloc >::begin () const inline noexcept
Definition at line 247 of file memory_buffer.h.
References beast::asio::memory_buffer< T, Alloc >::m_base.
     {
         return m_base;
     }
template<class T, class Alloc = std::allocator <T>> boost::asio::mutable_buffer beast::asio::memory_buffer< T, Alloc >::buffer () inline
Definition at line 121 of file memory_buffer.h.
References beast::asio::memory_buffer< T, Alloc >::bytes(), and beast::asio::memory_buffer< T, Alloc >::data().
Referenced by beast::asio::memory_buffer< T, Alloc >::operator boost::asio::const_buffer(), and beast::asio::memory_buffer< T, Alloc >::operator boost::asio::mutable_buffer().
     {
         return boost::asio::mutable_buffer (
             data(), bytes());
     }
template<class T, class Alloc = std::allocator <T>> boost::asio::const_buffer beast::asio::memory_buffer< T, Alloc >::buffer () const inline
Definition at line 128 of file memory_buffer.h.
References beast::asio::memory_buffer< T, Alloc >::bytes(), and beast::asio::memory_buffer< T, Alloc >::data().
     {
         return boost::asio::const_buffer (
             data(), bytes());
     }
template<class T, class Alloc = std::allocator <T>> boost::asio::mutable_buffers_1 beast::asio::memory_buffer< T, Alloc >::buffers () inline
Definition at line 135 of file memory_buffer.h.
References beast::asio::memory_buffer< T, Alloc >::bytes(), and beast::asio::memory_buffer< T, Alloc >::data().
Referenced by beast::asio::memory_buffer< T, Alloc >::operator boost::asio::const_buffers_1(), and beast::asio::memory_buffer< T, Alloc >::operator boost::asio::mutable_buffers_1().
     {
         return boost::asio::mutable_buffers_1 (
             data(), bytes());
     }
template<class T, class Alloc = std::allocator <T>> boost::asio::const_buffers_1 beast::asio::memory_buffer< T, Alloc >::buffers () const inline
Definition at line 142 of file memory_buffer.h.
References beast::asio::memory_buffer< T, Alloc >::bytes(), and beast::asio::memory_buffer< T, Alloc >::data().
     {
         return boost::asio::const_buffers_1 (
             data(), bytes());
     }
template<class T, class Alloc = std::allocator <T>> size_type beast::asio::memory_buffer< T, Alloc >::bytes () const inline
Definition at line 340 of file memory_buffer.h.
References beast::asio::memory_buffer< T, Alloc >::m_size, and T.
Referenced by beast::asio::memory_buffer< T, Alloc >::buffer(), and beast::asio::memory_buffer< T, Alloc >::buffers().
     {
         return m_size * sizeof(T);
     }
template<class T, class Alloc = std::allocator <T>> size_type beast::asio::memory_buffer< T, Alloc >::capacity () const inline noexcept
Definition at line 335 of file memory_buffer.h.
References beast::asio::memory_buffer< T, Alloc >::size().
     {
         return size();
     }
template<class T, class Alloc = std::allocator <T>> const_iterator beast::asio::memory_buffer< T, Alloc >::cbegin () const inline noexcept
Definition at line 253 of file memory_buffer.h.
References beast::asio::memory_buffer< T, Alloc >::m_base.
Referenced by beast::asio::memory_buffer< T, Alloc >::crend(), beast::asio::operator==(), and beast::asio::memory_buffer< T, Alloc >::rend().
     {
         return m_base;
     }
template<class T, class Alloc = std::allocator <T>> const_iterator beast::asio::memory_buffer< T, Alloc >::cend () const inline noexcept
Definition at line 271 of file memory_buffer.h.
References beast::asio::memory_buffer< T, Alloc >::m_base, and beast::asio::memory_buffer< T, Alloc >::m_size.
Referenced by beast::asio::memory_buffer< T, Alloc >::crbegin(), beast::asio::operator==(), and beast::asio::memory_buffer< T, Alloc >::rbegin().
     {
         return m_base + m_size;
     }
template<class T, class Alloc = std::allocator <T>> const_reverse_iterator beast::asio::memory_buffer< T, Alloc >::crbegin () const inline noexcept
Definition at line 289 of file memory_buffer.h.
References beast::asio::memory_buffer< T, Alloc >::cend().
     {
         return const_reverse_iterator (cend());
     }
template<class T, class Alloc = std::allocator <T>> const_reverse_iterator beast::asio::memory_buffer< T, Alloc >::crend () const inline noexcept
Definition at line 307 of file memory_buffer.h.
References beast::asio::memory_buffer< T, Alloc >::cbegin().
     {
         return const_reverse_iterator (cbegin());
     }
template<class T, class Alloc = std::allocator <T>> pointer beast::asio::memory_buffer< T, Alloc >::data () inline noexcept
Definition at line 225 of file memory_buffer.h.
References beast::asio::memory_buffer< T, Alloc >::m_base.
Referenced by beast::asio::memory_buffer< T, Alloc >::buffer(), and beast::asio::memory_buffer< T, Alloc >::buffers().
     {
         return m_base;
     }
template<class T, class Alloc = std::allocator <T>> const_pointer beast::asio::memory_buffer< T, Alloc >::data () const inline noexcept
Definition at line 231 of file memory_buffer.h.
References beast::asio::memory_buffer< T, Alloc >::m_base.
     {
         return m_base;
     }
template<class T, class Alloc = std::allocator <T>> bool beast::asio::memory_buffer< T, Alloc >::empty () const inline noexcept
Definition at line 317 of file memory_buffer.h.
References beast::asio::memory_buffer< T, Alloc >::m_size.
     {
         return m_size == 0;
     }
template<class T, class Alloc = std::allocator <T>> iterator beast::asio::memory_buffer< T, Alloc >::end () inline noexcept
Definition at line 259 of file memory_buffer.h.
References beast::asio::memory_buffer< T, Alloc >::m_base, and beast::asio::memory_buffer< T, Alloc >::m_size.
Referenced by beast::asio::memory_buffer< T, Alloc >::rbegin().
     {
         return m_base + m_size;
     }
template<class T, class Alloc = std::allocator <T>> const_iterator beast::asio::memory_buffer< T, Alloc >::end () const inline noexcept
Definition at line 265 of file memory_buffer.h.
References beast::asio::memory_buffer< T, Alloc >::m_base, and beast::asio::memory_buffer< T, Alloc >::m_size.
     {
         return m_base + m_size;
     }
template<class T, class Alloc = std::allocator <T>> reference beast::asio::memory_buffer< T, Alloc >::front () inline noexcept
Definition at line 213 of file memory_buffer.h.
References beast::asio::memory_buffer< T, Alloc >::m_base.
     {
         return *m_base;
     }
template<class T, class Alloc = std::allocator <T>> const_reference beast::asio::memory_buffer< T, Alloc >::front () const inline noexcept
Definition at line 219 of file memory_buffer.h.
References beast::asio::memory_buffer< T, Alloc >::m_base.
     {
         return *m_base;
     }
template<class T, class Alloc = std::allocator <T>> allocator_type beast::asio::memory_buffer< T, Alloc >::get_allocator () const inline
Definition at line 111 of file memory_buffer.h.
References beast::empty_base_optimization< Alloc >::member().
     {
         return Base::member;
     }
template<class T, class Alloc = std::allocator <T>> size_type beast::asio::memory_buffer< T, Alloc >::max_size () const inline noexcept
Definition at line 329 of file memory_buffer.h.
References beast::asio::memory_buffer< T, Alloc >::size().
     {
         return size();
     }
template<class T, class Alloc = std::allocator <T>> beast::asio::memory_buffer< T, Alloc >::operator boost::asio::const_buffer () const inline
Definition at line 153 of file memory_buffer.h.
References beast::asio::memory_buffer< T, Alloc >::buffer().
     {
         return buffer();
     }
template<class T, class Alloc = std::allocator <T>> beast::asio::memory_buffer< T, Alloc >::operator boost::asio::const_buffers_1 () const inline
Definition at line 163 of file memory_buffer.h.
References beast::asio::memory_buffer< T, Alloc >::buffers().
     {
         return buffers();
     }
template<class T, class Alloc = std::allocator <T>> beast::asio::memory_buffer< T, Alloc >::operator boost::asio::mutable_buffer () inline
Definition at line 148 of file memory_buffer.h.
References beast::asio::memory_buffer< T, Alloc >::buffer().
     {
         return buffer();
     }
template<class T, class Alloc = std::allocator <T>> beast::asio::memory_buffer< T, Alloc >::operator boost::asio::mutable_buffers_1 () inline
Definition at line 158 of file memory_buffer.h.
References beast::asio::memory_buffer< T, Alloc >::buffers().
     {
         return buffers();
     }
template<class T, class Alloc = std::allocator <T>> memory_buffer& beast::asio::memory_buffer< T, Alloc >::operator= (memory_buffer< T, Alloc > const &) delete
template<class T, class Alloc = std::allocator <T>> reference beast::asio::memory_buffer< T, Alloc >::operator[] (size_type pos) inline noexcept
Definition at line 189 of file memory_buffer.h.
References beast::asio::memory_buffer< T, Alloc >::m_base.
     {
         return m_base [pos];
     }
template<class T, class Alloc = std::allocator <T>> const_reference beast::asio::memory_buffer< T, Alloc >::operator[] (size_type pos) const inline noexcept
Definition at line 195 of file memory_buffer.h.
References beast::asio::memory_buffer< T, Alloc >::m_base.
     {
         return m_base [pos];
     }
template<class T, class Alloc = std::allocator <T>> reverse_iterator beast::asio::memory_buffer< T, Alloc >::rbegin () inline noexcept
Definition at line 277 of file memory_buffer.h.
References beast::asio::memory_buffer< T, Alloc >::end().
     {
         return reverse_iterator (end());
     }
template<class T, class Alloc = std::allocator <T>> const_reverse_iterator beast::asio::memory_buffer< T, Alloc >::rbegin () const inline noexcept
Definition at line 283 of file memory_buffer.h.
References beast::asio::memory_buffer< T, Alloc >::cend().
     {
         return const_reverse_iterator (cend());
     }
template<class T, class Alloc = std::allocator <T>> reverse_iterator beast::asio::memory_buffer< T, Alloc >::rend () inline noexcept
Definition at line 295 of file memory_buffer.h.
References beast::asio::memory_buffer< T, Alloc >::begin().
     {
         return reverse_iterator (begin());
     }
template<class T, class Alloc = std::allocator <T>> const_reverse_iterator beast::asio::memory_buffer< T, Alloc >::rend () const inline noexcept
Definition at line 301 of file memory_buffer.h.
References beast::asio::memory_buffer< T, Alloc >::cbegin().
     {
         return const_reverse_iterator (cbegin());
     }
template<class T, class Alloc = std::allocator <T>> size_type beast::asio::memory_buffer< T, Alloc >::size () const inline noexcept
Definition at line 323 of file memory_buffer.h.
References beast::asio::memory_buffer< T, Alloc >::m_size.
Referenced by beast::asio::memory_buffer< T, Alloc >::at(), beast::asio::memory_buffer< T, Alloc >::capacity(), and beast::asio::memory_buffer< T, Alloc >::max_size().
     {
         return m_size;
     }
Friends And Related Function Documentation
template<class T, class Alloc = std::allocator <T>> template<class U , class A > void swap (memory_buffer< U, A > & lhs, memory_buffer< U, A > & rhs) friend
Member Data Documentation
template<class T, class Alloc = std::allocator <T>> T* beast::asio::memory_buffer< T, Alloc >::m_base private
Definition at line 51 of file memory_buffer.h.
Referenced by beast::asio::memory_buffer< T, Alloc >::at(), beast::asio::memory_buffer< T, Alloc >::back(), beast::asio::memory_buffer< T, Alloc >::begin(), beast::asio::memory_buffer< T, Alloc >::cbegin(), beast::asio::memory_buffer< T, Alloc >::cend(), beast::asio::memory_buffer< T, Alloc >::data(), beast::asio::memory_buffer< T, Alloc >::end(), beast::asio::memory_buffer< T, Alloc >::front(), beast::asio::memory_buffer< T, Alloc >::operator[](), and beast::asio::memory_buffer< T, Alloc >::~memory_buffer().
template<class T, class Alloc = std::allocator <T>> std::size_t beast::asio::memory_buffer< T, Alloc >::m_size private
Definition at line 52 of file memory_buffer.h.
Referenced by beast::asio::memory_buffer< T, Alloc >::back(), beast::asio::memory_buffer< T, Alloc >::bytes(), beast::asio::memory_buffer< T, Alloc >::cend(), beast::asio::memory_buffer< T, Alloc >::empty(), beast::asio::memory_buffer< T, Alloc >::end(), beast::asio::memory_buffer< T, Alloc >::size(), and beast::asio::memory_buffer< T, Alloc >::~memory_buffer().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/asio/memory_buffer.h