rippled: ripple::PeerFinder::Livecache< class > Class Template Reference
ripple::PeerFinder::Livecache< class > Class Template Reference
#include <Livecache.h>
Classes
class hops_t
Public Types
typedef Allocator allocator_type
Public Member Functions
Livecache (clock_type &clock, beast::Journal journal, Allocator alloc=Allocator())
bool empty () const
cache_type::size_type size () const
void expire ()
void insert (Endpoint const &ep)
void dump (beast::Journal::ScopedStream &ss) const
void onWrite (beast::PropertyStream::Map &map)
Public Attributes
class
ripple::PeerFinder::Livecache::hops_t hops
Private Types
typedef beast::aged_map
< beast::IP::Endpoint, Element,
std::chrono::seconds,
std::less< beast::IP::Endpoint >
, Allocator > cache_type
Private Attributes
beast::Journal m_journal
cache_type m_cache
Additional Inherited Members
Detailed Description
template<class>
class ripple::PeerFinder::Livecache< class >
The Livecache holds the short-lived relayed Endpoint messages.
Since peers only advertise themselves when they have open slots, we want these messags to expire rather quickly after the peer becomes full.
Addresses added to the cache are not connection-tested to see if they are connectible (with one small exception regarding neighbors). Therefore, these addresses are not suitable for persisting across launches or for bootstrapping, because they do not have verifiable and locally observed uptime and connectibility information.
Definition at line 33 of file Livecache.h.
Member Typedef Documentation
template<class > typedef Allocator ripple::PeerFinder::Livecache< class >::allocator_type
Definition at line 196 of file Livecache.h.
template<class > typedef beast::aged_map< beast::IP::Endpoint, Element, std::chrono::seconds, std::less <beast::IP::Endpoint>, Allocator > ripple::PeerFinder::Livecache< class >::cache_type private
Definition at line 190 of file Livecache.h.
Constructor & Destructor Documentation
template<class Allocator > ripple::PeerFinder::Livecache< Allocator >::Livecache (clock_type & clock, beast::Journal journal, Allocator alloc = Allocator())
Create the cache.
Definition at line 367 of file Livecache.h.
     : m_journal (journal)
     , m_cache (clock, alloc)
     , hops (alloc)
 {
 }
Member Function Documentation
template<class Allocator > void ripple::PeerFinder::Livecache< Allocator >::dump (beast::Journal::ScopedStream & ss) const
Produce diagnostic output.
Definition at line 452 of file Livecache.h.
References ripple::PeerFinder::Livecache< class >::size().
 {
     ss << std::endl << std::endl <<
         "Livecache (size " << m_cache.size() << ")";
     for (auto const& entry : m_cache)
     {
         auto const& e (entry.second);
         ss << std::endl <<
             e.endpoint.address << ", " <<
             e.endpoint.hops << " hops";
     }
 }
template<class > bool ripple::PeerFinder::Livecache< class >::empty () const inline
Returns true if the cache is empty.
Definition at line 340 of file Livecache.h.
References beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::empty(), and ripple::PeerFinder::Livecache< class >::m_cache.
     {
         return m_cache.empty ();
     }
template<class Allocator > void ripple::PeerFinder::Livecache< Allocator >::expire ()
Erase entries whose time has expired.
Definition at line 379 of file Livecache.h.
References ripple::PeerFinder::Tuning::liveCacheSecondsToLive().
 {
     std::size_t n (0);
     typename cache_type::time_point const expired (
         m_cache.clock().now() - Tuning::liveCacheSecondsToLive);
     for (auto iter (m_cache.chronological.begin());
         iter != m_cache.chronological.end() && iter.when() <= expired;)
     {
         Element& e (iter->second);
         hops.remove (e);
         iter = m_cache.erase (iter);
         ++n;
     }
     if (n > 0)
     {
         if (m_journal.debug) m_journal.debug << beast::leftw (18) <<
             "Livecache expired " << n <<
             ((n > 1) ? " entries" : " entry");
     }
 }
template<class Allocator > void ripple::PeerFinder::Livecache< Allocator >::insert (Endpoint const & ep)
Creates or updates an existing Element based on a new message.
Definition at line 401 of file Livecache.h.
References ripple::PeerFinder::Tuning::maxHops.
 {
     // The caller already incremented hop, so if we got a
     // message at maxHops we will store it at maxHops + 1.
     // This means we won't give out the address to other peers
     // but we will use it to make connections and hand it out
     // when redirecting.
     //
     assert (ep.hops <= (Tuning::maxHops + 1));
     std::pair <typename cache_type::iterator, bool> result (
         m_cache.emplace (ep.address, ep));
     Element& e (result.first->second);
     if (result.second)
     {
         hops.insert (e);
         if (m_journal.debug) m_journal.debug << beast::leftw (18) <<
             "Livecache insert " << ep.address <<
             " at hops " << ep.hops;
         return;
     }
     else if (! result.second && (ep.hops > e.endpoint.hops))
     {
         // Drop duplicates at higher hops
         std::size_t const excess (
             ep.hops - e.endpoint.hops);
         if (m_journal.trace) m_journal.trace << beast::leftw(18) <<
             "Livecache drop " << ep.address <<
             " at hops +" << excess;
         return;
     }
     m_cache.touch (result.first);
     // Address already in the cache so update metadata
     if (ep.hops < e.endpoint.hops)
     {
         hops.reinsert (e, ep.hops);
         if (m_journal.debug) m_journal.debug << beast::leftw (18) <<
             "Livecache update " << ep.address <<
             " at hops " << ep.hops;
     }
     else
     {
         if (m_journal.trace) m_journal.trace << beast::leftw (18) <<
             "Livecache refresh " << ep.address <<
             " at hops " << ep.hops;
     }
 }
template<class Allocator > void ripple::PeerFinder::Livecache< Allocator >::onWrite (beast::PropertyStream::Map & map)
Output statistics.
Definition at line 467 of file Livecache.h.
References ripple::PeerFinder::Tuning::liveCacheSecondsToLive().
 {
     typename cache_type::time_point const expired (
         m_cache.clock().now() - Tuning::liveCacheSecondsToLive);
     map ["size"] = size ();
     map ["hist"] = hops.histogram();
     beast::PropertyStream::Set set ("entries", map);
     for (auto iter (m_cache.cbegin()); iter != m_cache.cend(); ++iter)
     {
         auto const& e (iter->second);
         beast::PropertyStream::Map item (set);
         item ["hops"] = e.endpoint.hops;
         item ["address"] = e.endpoint.address.to_string ();
         std::stringstream ss;
         ss << iter.when() - expired;
         item ["expires"] = ss.str();
     }
 }
template<class > cache_type::size_type ripple::PeerFinder::Livecache< class >::size () const inline
Returns the number of entries in the cache.
Definition at line 346 of file Livecache.h.
References ripple::PeerFinder::Livecache< class >::m_cache, and beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::size().
Referenced by ripple::PeerFinder::Livecache< class >::dump().
     {
         return m_cache.size();
     }
Member Data Documentation
template<class > class ripple::PeerFinder::Livecache::hops_t ripple::PeerFinder::Livecache< class >::hops
template<class > cache_type ripple::PeerFinder::Livecache< class >::m_cache private
Definition at line 193 of file Livecache.h.
Referenced by ripple::PeerFinder::Livecache< class >::empty(), and ripple::PeerFinder::Livecache< class >::size().
template<class > beast::Journal ripple::PeerFinder::Livecache< class >::m_journal private
Definition at line 192 of file Livecache.h.
The documentation for this class was generated from the following file:
rippled/src/ripple/peerfinder/impl/Livecache.h