rippled: rocksdb::StringLists Class Reference
rocksdb::StringLists Class Reference
Public Member Functions
StringLists (std::shared_ptr< DB > db)
bool Append (const std::string &key, const std::string &val)
bool Get (const std::string &key, std::string *const result)
Private Attributes
std::shared_ptr< DB > db_
WriteOptions merge_option_
ReadOptions get_option_
Detailed Description
StringLists represents a set of string-lists, each with a key-index. Supports Append(list, string) and Get(list)
Definition at line 52 of file stringappend_test.cc.
Constructor & Destructor Documentation
rocksdb::StringLists::StringLists (std::shared_ptr< DB > db) inline
Definition at line 56 of file stringappend_test.cc.
       : db_(db),
         merge_option_(),
         get_option_() {
     assert(db);
   }
Member Function Documentation
bool rocksdb::StringLists::Append (const std::string & key, const std::string & val) inline
Definition at line 64 of file stringappend_test.cc.
References db_, rocksdb::DBImpl::Merge(), and rocksdb::Status::ToString().
Referenced by rocksdb::TEST().
{
     Slice valSlice(val.data(), val.size());
     auto s = db_->Merge(merge_option_, key, valSlice);
     if (s.ok()) {
       return true;
     } else {
       std::cerr << "ERROR " << s.ToString() << std::endl;
       return false;
     }
   }
bool rocksdb::StringLists::Get (const std::string & key, std::string *const result) inline
Definition at line 77 of file stringappend_test.cc.
References db_, rocksdb::DBImpl::Get(), and rocksdb::Status::ToString().
Referenced by rocksdb::TEST().
{
     assert(result != NULL); // we should have a place to store the result
     auto s = db_->Get(get_option_, key, result);
     if (s.ok()) {
       return true;
     }
     // Either key does not exist, or there is some error.
     *result = "";       // Always return empty string (just for convention)
     //NotFound is okay; just return empty (similar to std::map)
     //But network or db errors, etc, should fail the test (or at least yell)
     if (!s.IsNotFound()) {
       std::cerr << "ERROR " << s.ToString() << std::endl;
     }
     // Always return false if s.ok() was not true
     return false;
   }
Member Data Documentation
std::shared_ptr<DB> rocksdb::StringLists::db_ private
Definition at line 100 of file stringappend_test.cc.
ReadOptions rocksdb::StringLists::get_option_ private
Definition at line 102 of file stringappend_test.cc.
WriteOptions rocksdb::StringLists::merge_option_ private
Definition at line 101 of file stringappend_test.cc.
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/utilities/merge_operators/string_append/stringappend_test.cc