rippled: rocksdb::TransactionLogIteratorImpl Class Reference
rocksdb::TransactionLogIteratorImpl Class Reference
#include <transaction_log_impl.h>
Public Member Functions
TransactionLogIteratorImpl (const std::string &dir, const Options *options, const EnvOptions &soptions, const SequenceNumber seqNum, std::unique_ptr< VectorLogPtr > files, DBImpl const *const dbimpl)
virtual bool Valid ()
virtual void Next ()
virtual Status status ()
virtual BatchResult GetBatch ()
Public Member Functions inherited from rocksdb::TransactionLogIterator
TransactionLogIterator ()
virtual ~TransactionLogIterator ()
Private Member Functions
Status OpenLogFile (const LogFile *logFile, unique_ptr< SequentialFile > *file)
bool RestrictedRead (Slice *record, std::string *scratch)
void SeekToStartSequence (uint64_t startFileIndex=0, bool strict=false)
void NextImpl (bool internal=false)
bool IsBatchExpected (const WriteBatch *batch, SequenceNumber expectedSeq)
void UpdateCurrentWriteBatch (const Slice &record)
Status OpenLogReader (const LogFile *file)
Private Attributes
const std::string & dir_
const Options * options_
const EnvOptions & soptions_
SequenceNumber startingSequenceNumber_
std::unique_ptr< VectorLogPtr > files_
bool started_
bool isValid_
Status currentStatus_
size_t currentFileIndex_
std::unique_ptr< WriteBatch > currentBatch_
unique_ptr< log::Reader > currentLogReader_
LogReporter reporter_
SequenceNumber currentBatchSeq_
SequenceNumber currentLastSeq_
DBImpl const *const dbimpl_
Detailed Description
Definition at line 67 of file transaction_log_impl.h.
Constructor & Destructor Documentation
rocksdb::TransactionLogIteratorImpl::TransactionLogIteratorImpl (const std::string & dir, const Options * options, const EnvOptions & soptions, const SequenceNumber seqNum, std::unique_ptr< VectorLogPtr > files, DBImpl const *const dbimpl)
Definition at line 11 of file transaction_log_impl.cc.
References dbimpl_, rocksdb::LogReporter::env, rocksdb::Options::env, files_, rocksdb::LogReporter::info_log, rocksdb::Options::info_log, options_, reporter_, and SeekToStartSequence().
                                                         :
     dir_(dir),
     options_(options),
     soptions_(soptions),
     startingSequenceNumber_(seq),
     files_(std::move(files)),
     started_(false),
     isValid_(false),
     currentFileIndex_(0),
     currentBatchSeq_(0),
     currentLastSeq_(0),
     dbimpl_(dbimpl) {
   assert(files_ != nullptr);
   assert(dbimpl_ != nullptr);
   reporter_.env = options_->env;
   reporter_.info_log = options_->info_log.get();
   SeekToStartSequence(); // Seek till starting sequence
 }
Member Function Documentation
BatchResult rocksdb::TransactionLogIteratorImpl::GetBatch () virtual
Implements rocksdb::TransactionLogIterator.
Definition at line 60 of file transaction_log_impl.cc.
References currentBatch_, currentBatchSeq_, isValid_, rocksdb::BatchResult::sequence, and rocksdb::BatchResult::writeBatchPtr.
{
   assert(isValid_);  //  cannot call in a non valid state.
   BatchResult result;
   result.sequence = currentBatchSeq_;
   result.writeBatchPtr = std::move(currentBatch_);
   return result;
 }
bool rocksdb::TransactionLogIteratorImpl::IsBatchExpected (const WriteBatch * batch, SequenceNumber expectedSeq) private
Definition at line 200 of file transaction_log_impl.cc.
References dbimpl_, rocksdb::DBImpl::GetLatestSequenceNumber(), rocksdb::LogReporter::Info(), reporter_, and rocksdb::WriteBatchInternal::Sequence().
Referenced by UpdateCurrentWriteBatch().
{
   assert(batch);
   SequenceNumber batchSeq = WriteBatchInternal::Sequence(batch);
   if (batchSeq != expectedSeq) {
     char buf[200];
     snprintf(buf, sizeof(buf),
              "Discontinuity in log records. Got seq=%lu, Expected seq=%lu, "
              "Last flushed seq=%lu.Log iterator will reseek the correct "
              "batch.",
              (unsigned long)batchSeq,
              (unsigned long)expectedSeq,
              (unsigned long)dbimpl_->GetLatestSequenceNumber());
     reporter_.Info(buf);
     return false;
   }
   return true;
 }
void rocksdb::TransactionLogIteratorImpl::Next () virtual
Implements rocksdb::TransactionLogIterator.
Definition at line 144 of file transaction_log_impl.cc.
References NextImpl().
{
   return NextImpl(false);
 }
void rocksdb::TransactionLogIteratorImpl::NextImpl (bool internal = false) private
Definition at line 148 of file transaction_log_impl.cc.
References rocksdb::LogReporter::Corruption(), rocksdb::Status::Corruption(), currentFileIndex_, currentLastSeq_, currentLogReader_, currentStatus_, dbimpl_, files_, rocksdb::DBImpl::GetLatestSequenceNumber(), rocksdb::Status::IOError(), isValid_, rocksdb::Status::OK(), rocksdb::Status::ok(), OpenLogReader(), reporter_, RestrictedRead(), SeekToStartSequence(), rocksdb::Slice::size(), started_, status(), and UpdateCurrentWriteBatch().
Referenced by Next(), and SeekToStartSequence().
{
   std::string scratch;
   Slice record;
   isValid_ = false;
   if (!internal && !started_) {
     // Runs every time until we can seek to the start sequence
     return SeekToStartSequence();
   }
   while(true) {
     assert(currentLogReader_);
     if (currentLogReader_->IsEOF()) {
       currentLogReader_->UnmarkEOF();
     }
     while (RestrictedRead(&record, &scratch)) {
       if (record.size() < 12) {
         reporter_.Corruption(
           record.size(), Status::Corruption("very small log record"));
         continue;
       } else {
         // started_ should be true if called by application
         assert(internal || started_);
         // started_ should be false if called internally
         assert(!internal || !started_);
         UpdateCurrentWriteBatch(record);
         if (internal && !started_) {
           started_ = true;
         }
         return;
       }
     }
     // Open the next file
     if (currentFileIndex_ < files_->size() - 1) {
       ++currentFileIndex_;
       Status status =OpenLogReader(files_->at(currentFileIndex_).get());
       if (!status.ok()) {
         isValid_ = false;
         currentStatus_ = status;
         return;
       }
     } else {
       isValid_ = false;
       if (currentLastSeq_ == dbimpl_->GetLatestSequenceNumber()) {
         currentStatus_ = Status::OK();
       } else {
         currentStatus_ = Status::IOError("NO MORE DATA LEFT");
       }
       return;
     }
   }
 }
Status rocksdb::TransactionLogIteratorImpl::OpenLogFile (const LogFile * logFile, unique_ptr< SequentialFile > * file) private
Definition at line 37 of file transaction_log_impl.cc.
References rocksdb::ArchivedLogFileName(), dir_, env, rocksdb::Options::env, rocksdb::Status::IOError(), rocksdb::kArchivedLogFile, rocksdb::LogFileName(), rocksdb::LogFile::LogNumber(), rocksdb::Env::NewSequentialFile(), options_, soptions_, status(), and rocksdb::LogFile::Type().
Referenced by OpenLogReader().
{
   Env* env = options_->env;
   if (logFile->Type() == kArchivedLogFile) {
     std::string fname = ArchivedLogFileName(dir_, logFile->LogNumber());
     return env->NewSequentialFile(fname, file, soptions_);
   } else {
     std::string fname = LogFileName(dir_, logFile->LogNumber());
     Status status = env->NewSequentialFile(fname, file, soptions_);
     if (!status.ok()) {
       //  If cannot open file in DB directory.
       //  Try the archive dir, as it could have moved in the meanwhile.
       fname = ArchivedLogFileName(dir_, logFile->LogNumber());
       status = env->NewSequentialFile(fname, file, soptions_);
       if (!status.ok()) {
         return Status::IOError("Requested file not present in the dir");
       }
     }
     return status;
   }
 }
Status rocksdb::TransactionLogIteratorImpl::OpenLogReader (const LogFile * file) private
Definition at line 252 of file transaction_log_impl.cc.
References currentLogReader_, rocksdb::Status::OK(), rocksdb::Status::ok(), OpenLogFile(), reporter_, and status().
Referenced by NextImpl(), and SeekToStartSequence().
{
   unique_ptr<SequentialFile> file;
   Status status = OpenLogFile(logFile, &file);
   if (!status.ok()) {
     return status;
   }
   assert(file);
   currentLogReader_.reset(
     new log::Reader(std::move(file), &reporter_, true, 0)
   );
   return Status::OK();
 }
bool rocksdb::TransactionLogIteratorImpl::RestrictedRead (Slice * record, std::string * scratch) private
Definition at line 76 of file transaction_log_impl.cc.
References currentLastSeq_, currentLogReader_, dbimpl_, and rocksdb::DBImpl::GetLatestSequenceNumber().
Referenced by NextImpl(), and SeekToStartSequence().
{
   // Don't read if no more complete entries to read from logs
   if (currentLastSeq_ >= dbimpl_->GetLatestSequenceNumber()) {
     return false;
   }
   return currentLogReader_->ReadRecord(record, scratch);
 }
void rocksdb::TransactionLogIteratorImpl::SeekToStartSequence (uint64_t startFileIndex = 0, bool strict = false) private
Definition at line 86 of file transaction_log_impl.cc.
References rocksdb::LogReporter::Corruption(), rocksdb::Status::Corruption(), currentBatchSeq_, currentLastSeq_, currentStatus_, files_, rocksdb::LogReporter::Info(), isValid_, NextImpl(), rocksdb::Status::ok(), OpenLogReader(), reporter_, RestrictedRead(), rocksdb::Slice::size(), started_, startingSequenceNumber_, rocksdb::Status::ToString(), and UpdateCurrentWriteBatch().
Referenced by NextImpl(), TransactionLogIteratorImpl(), and UpdateCurrentWriteBatch().
                  {
   std::string scratch;
   Slice record;
   started_ = false;
   isValid_ = false;
   if (files_->size() <= startFileIndex) {
     return;
   }
   Status s = OpenLogReader(files_->at(startFileIndex).get());
   if (!s.ok()) {
     currentStatus_ = s;
     return;
   }
   while (RestrictedRead(&record, &scratch)) {
     if (record.size() < 12) {
       reporter_.Corruption(
         record.size(), Status::Corruption("very small log record"));
       continue;
     }
     UpdateCurrentWriteBatch(record);
     if (currentLastSeq_ >= startingSequenceNumber_) {
       if (strict && currentBatchSeq_ != startingSequenceNumber_) {
         currentStatus_ = Status::Corruption("Gap in sequence number. Could not "
                                             "seek to required sequence number");
         reporter_.Info(currentStatus_.ToString().c_str());
         return;
       } else if (strict) {
         reporter_.Info("Could seek required sequence number. Iterator will "
                        "continue.");
       }
       isValid_ = true;
       started_ = true; // set started_ as we could seek till starting sequence
       return;
     } else {
       isValid_ = false;
     }
   }
   // Could not find start sequence in first file. Normally this must be the
   // only file. Otherwise log the error and let the iterator return next entry
   // If strict is set, we want to seek exactly till the start sequence and it
   // should have been present in the file we scanned above
   if (strict) {
     currentStatus_ = Status::Corruption("Gap in sequence number. Could not "
                                         "seek to required sequence number");
     reporter_.Info(currentStatus_.ToString().c_str());
   } else if (files_->size() != 1) {
     currentStatus_ = Status::Corruption("Start sequence was not found, "
                                         "skipping to the next available");
     reporter_.Info(currentStatus_.ToString().c_str());
     // Let NextImpl find the next available entry. started_ remains false
     // because we don't want to check for gaps while moving to start sequence
     NextImpl(true);
   }
 }
Status rocksdb::TransactionLogIteratorImpl::status () virtual
Implements rocksdb::TransactionLogIterator.
Definition at line 68 of file transaction_log_impl.cc.
References currentStatus_.
Referenced by NextImpl(), OpenLogFile(), and OpenLogReader().
{
   return currentStatus_;
 }
void rocksdb::TransactionLogIteratorImpl::UpdateCurrentWriteBatch (const Slice & record) private
Definition at line 220 of file transaction_log_impl.cc.
References rocksdb::WriteBatchInternal::Count(), currentBatch_, currentBatchSeq_, currentFileIndex_, currentLastSeq_, currentStatus_, IsBatchExpected(), isValid_, rocksdb::Status::NotFound(), rocksdb::Status::OK(), SeekToStartSequence(), rocksdb::WriteBatchInternal::Sequence(), rocksdb::WriteBatchInternal::SetContents(), started_, and startingSequenceNumber_.
Referenced by NextImpl(), and SeekToStartSequence().
{
   std::unique_ptr<WriteBatch> batch(new WriteBatch());
   WriteBatchInternal::SetContents(batch.get(), record);
   SequenceNumber expectedSeq = currentLastSeq_ + 1;
   // If the iterator has started, then confirm that we get continuous batches
   if (started_ && !IsBatchExpected(batch.get(), expectedSeq)) {
     // Seek to the batch having expected sequence number
     if (expectedSeq < files_->at(currentFileIndex_)->StartSequence()) {
       // Expected batch must lie in the previous log file
       // Avoid underflow.
       if (currentFileIndex_ != 0) {
         currentFileIndex_--;
       }
     }
     startingSequenceNumber_ = expectedSeq;
     // currentStatus_ will be set to Ok if reseek succeeds
     currentStatus_ = Status::NotFound("Gap in sequence numbers");
     return SeekToStartSequence(currentFileIndex_, true);
   }
   currentBatchSeq_ = WriteBatchInternal::Sequence(batch.get());
   currentLastSeq_ = currentBatchSeq_ +
                     WriteBatchInternal::Count(batch.get()) - 1;
   // currentBatchSeq_ can only change here
   assert(currentLastSeq_ <= dbimpl_->GetLatestSequenceNumber());
   currentBatch_ = move(batch);
   isValid_ = true;
   currentStatus_ = Status::OK();
 }
bool rocksdb::TransactionLogIteratorImpl::Valid () virtual
Implements rocksdb::TransactionLogIterator.
Definition at line 72 of file transaction_log_impl.cc.
References isValid_, and started_.
{
   return started_ && isValid_;
 }
Member Data Documentation
std::unique_ptr<WriteBatch> rocksdb::TransactionLogIteratorImpl::currentBatch_ private
Definition at line 94 of file transaction_log_impl.h.
Referenced by GetBatch(), and UpdateCurrentWriteBatch().
SequenceNumber rocksdb::TransactionLogIteratorImpl::currentBatchSeq_ private
Definition at line 98 of file transaction_log_impl.h.
Referenced by GetBatch(), SeekToStartSequence(), and UpdateCurrentWriteBatch().
size_t rocksdb::TransactionLogIteratorImpl::currentFileIndex_ private
Definition at line 93 of file transaction_log_impl.h.
Referenced by NextImpl(), and UpdateCurrentWriteBatch().
SequenceNumber rocksdb::TransactionLogIteratorImpl::currentLastSeq_ private
Definition at line 99 of file transaction_log_impl.h.
Referenced by NextImpl(), RestrictedRead(), SeekToStartSequence(), and UpdateCurrentWriteBatch().
unique_ptr<log::Reader> rocksdb::TransactionLogIteratorImpl::currentLogReader_ private
Definition at line 95 of file transaction_log_impl.h.
Referenced by NextImpl(), OpenLogReader(), and RestrictedRead().
Status rocksdb::TransactionLogIteratorImpl::currentStatus_ private
Definition at line 92 of file transaction_log_impl.h.
Referenced by NextImpl(), SeekToStartSequence(), status(), and UpdateCurrentWriteBatch().
DBImpl const* const rocksdb::TransactionLogIteratorImpl::dbimpl_ private
Definition at line 100 of file transaction_log_impl.h.
Referenced by IsBatchExpected(), NextImpl(), RestrictedRead(), and TransactionLogIteratorImpl().
const std::string& rocksdb::TransactionLogIteratorImpl::dir_ private
Definition at line 85 of file transaction_log_impl.h.
Referenced by OpenLogFile().
std::unique_ptr<VectorLogPtr> rocksdb::TransactionLogIteratorImpl::files_ private
Definition at line 89 of file transaction_log_impl.h.
Referenced by NextImpl(), SeekToStartSequence(), and TransactionLogIteratorImpl().
bool rocksdb::TransactionLogIteratorImpl::isValid_ private
Definition at line 91 of file transaction_log_impl.h.
Referenced by GetBatch(), NextImpl(), SeekToStartSequence(), UpdateCurrentWriteBatch(), and Valid().
const Options* rocksdb::TransactionLogIteratorImpl::options_ private
Definition at line 86 of file transaction_log_impl.h.
Referenced by OpenLogFile(), and TransactionLogIteratorImpl().
LogReporter rocksdb::TransactionLogIteratorImpl::reporter_ private
Definition at line 97 of file transaction_log_impl.h.
Referenced by IsBatchExpected(), NextImpl(), OpenLogReader(), SeekToStartSequence(), and TransactionLogIteratorImpl().
const EnvOptions& rocksdb::TransactionLogIteratorImpl::soptions_ private
Definition at line 87 of file transaction_log_impl.h.
Referenced by OpenLogFile().
bool rocksdb::TransactionLogIteratorImpl::started_ private
Definition at line 90 of file transaction_log_impl.h.
Referenced by NextImpl(), SeekToStartSequence(), UpdateCurrentWriteBatch(), and Valid().
SequenceNumber rocksdb::TransactionLogIteratorImpl::startingSequenceNumber_ private
Definition at line 88 of file transaction_log_impl.h.
Referenced by SeekToStartSequence(), and UpdateCurrentWriteBatch().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/db/transaction_log_impl.h
rippled/src/ripple/rocksdb/rocksdb/db/transaction_log_impl.cc