rippled: rocksdb::WriteBatch Class Reference
rocksdb::WriteBatch Class Reference
#include <write_batch.h>
Classes
class Handler
Public Member Functions
WriteBatch ()
~WriteBatch ()
void Put (const Slice &key, const Slice &value)
void Put (const SliceParts &key, const SliceParts &value)
void Merge (const Slice &key, const Slice &value)
void Delete (const Slice &key)
void PutLogData (const Slice &blob)
void Clear ()
Status Iterate (Handler *handler) const
std::string Data ()
int Count () const
WriteBatch (std::string rep)
Private Attributes
std::string rep_
Friends
class WriteBatchInternal
Detailed Description
Definition at line 36 of file write_batch.h.
Constructor & Destructor Documentation
rocksdb::WriteBatch::WriteBatch ()
Definition at line 39 of file write_batch.cc.
References Clear().
{
   Clear();
 }
rocksdb::WriteBatch::~WriteBatch ()
Definition at line 43 of file write_batch.cc.
 { }
rocksdb::WriteBatch::WriteBatch (std::string rep) inline explicit
Definition at line 97 of file write_batch.h.
 : rep_(rep) {}
Member Function Documentation
void rocksdb::WriteBatch::Clear ()
Definition at line 60 of file write_batch.cc.
References rocksdb::kHeader, and rep_.
Referenced by rocksdb::CorruptionTest::Build(), rocksdb::Benchmark::DoDelete(), rocksdb::Benchmark::DoWrite(), leveldb_writebatch_clear(), rocksdb::TEST(), rocksdb::DBImpl::Write(), WriteBatch(), and rocksdb::Benchmark::WriteFromStdin().
{
   rep_.clear();
   rep_.resize(kHeader);
 }
int rocksdb::WriteBatch::Count () const
Definition at line 65 of file write_batch.cc.
References rocksdb::WriteBatchInternal::Count().
Referenced by rocksdb::WriteBatchInternal::Append(), rocksdb::TEST(), and rocksdb::Benchmark::WriteFromStdin().
{
   return WriteBatchInternal::Count(this);
 }
std::string rocksdb::WriteBatch::Data () inline
Definition at line 91 of file write_batch.h.
References rep_.
 { return rep_; }
void rocksdb::WriteBatch::Delete (const Slice & key)
Definition at line 156 of file write_batch.cc.
References rocksdb::WriteBatchInternal::Count(), rocksdb::kTypeDeletion, rocksdb::PutLengthPrefixedSlice(), rep_, and rocksdb::WriteBatchInternal::SetCount().
Referenced by rocksdb::DB::Delete(), rocksdb::Benchmark::DeleteMany(), rocksdb::Benchmark::DoDelete(), leveldb_writebatch_delete(), rocksdb::TtlTest::MakePutWriteBatch(), rocksdb::StressTest::MultiDelete(), and rocksdb::TEST().
{
   WriteBatchInternal::SetCount(this, WriteBatchInternal::Count(this) + 1);
   rep_.push_back(static_cast<char>(kTypeDeletion));
   PutLengthPrefixedSlice(&rep_, key);
 }
Status rocksdb::WriteBatch::Iterate (Handler * handler) const
Definition at line 69 of file write_batch.cc.
References rocksdb::WriteBatch::Handler::Continue(), rocksdb::Status::Corruption(), rocksdb::WriteBatchInternal::Count(), rocksdb::WriteBatch::Handler::Delete(), rocksdb::Slice::empty(), rocksdb::GetLengthPrefixedSlice(), rocksdb::kHeader, rocksdb::kTypeDeletion, rocksdb::kTypeLogData, rocksdb::kTypeMerge, rocksdb::kTypeValue, rocksdb::WriteBatch::Handler::LogData(), rocksdb::WriteBatch::Handler::Merge(), rocksdb::Status::OK(), rocksdb::WriteBatch::Handler::Put(), rocksdb::Slice::remove_prefix(), rep_, rocksdb::Slice::size(), and value.
Referenced by rocksdb::WALDumperCommand::DoCommand(), rocksdb::WriteBatchInternal::InsertInto(), leveldb_writebatch_iterate(), rocksdb::TEST(), rocksdb::DBWithTTL::Write(), and rocksdb::ModelDB::Write().
{
   Slice input(rep_);
   if (input.size() < kHeader) {
     return Status::Corruption("malformed WriteBatch (too small)");
   }
   input.remove_prefix(kHeader);
   Slice key, value, blob;
   int found = 0;
   while (!input.empty() && handler->Continue()) {
     char tag = input[0];
     input.remove_prefix(1);
     switch (tag) {
       case kTypeValue:
         if (GetLengthPrefixedSlice(&input, &key) &&
             GetLengthPrefixedSlice(&input, &value)) {
           handler->Put(key, value);
           found++;
         } else {
           return Status::Corruption("bad WriteBatch Put");
         }
         break;
       case kTypeDeletion:
         if (GetLengthPrefixedSlice(&input, &key)) {
           handler->Delete(key);
           found++;
         } else {
           return Status::Corruption("bad WriteBatch Delete");
         }
         break;
       case kTypeMerge:
         if (GetLengthPrefixedSlice(&input, &key) &&
             GetLengthPrefixedSlice(&input, &value)) {
           handler->Merge(key, value);
           found++;
         } else {
           return Status::Corruption("bad WriteBatch Merge");
         }
         break;
       case kTypeLogData:
         if (GetLengthPrefixedSlice(&input, &blob)) {
           handler->LogData(blob);
         } else {
           return Status::Corruption("bad WriteBatch Blob");
         }
         break;
       default:
         return Status::Corruption("unknown WriteBatch tag");
     }
   }
   if (found != WriteBatchInternal::Count(this)) {
     return Status::Corruption("WriteBatch has wrong count");
   } else {
     return Status::OK();
   }
 }
void rocksdb::WriteBatch::Merge (const Slice & key, const Slice & value)
Definition at line 162 of file write_batch.cc.
References rocksdb::WriteBatchInternal::Count(), rocksdb::kTypeMerge, rocksdb::PutLengthPrefixedSlice(), rep_, and rocksdb::WriteBatchInternal::SetCount().
Referenced by rocksdb::DBWithTTL::Merge(), rocksdb::DB::Merge(), rocksdb::StressTest::MultiPut(), and rocksdb::TEST().
{
   WriteBatchInternal::SetCount(this, WriteBatchInternal::Count(this) + 1);
   rep_.push_back(static_cast<char>(kTypeMerge));
   PutLengthPrefixedSlice(&rep_, key);
   PutLengthPrefixedSlice(&rep_, value);
 }
void rocksdb::WriteBatch::Put (const Slice & key, const Slice & value)
Definition at line 142 of file write_batch.cc.
References rocksdb::WriteBatchInternal::Count(), rocksdb::kTypeValue, rocksdb::PutLengthPrefixedSlice(), rep_, and rocksdb::WriteBatchInternal::SetCount().
Referenced by rocksdb::CorruptionTest::Build(), rocksdb::Benchmark::DoWrite(), rocksdb::DBConstructor::FinishImpl(), leveldb_writebatch_put(), rocksdb::TtlTest::MakePutWriteBatch(), rocksdb::StressTest::MultiPut(), rocksdb::DBWithTTL::Put(), rocksdb::DB::Put(), rocksdb::Benchmark::PutMany(), rocksdb::TEST(), and rocksdb::Benchmark::WriteFromStdin().
{
   WriteBatchInternal::SetCount(this, WriteBatchInternal::Count(this) + 1);
   rep_.push_back(static_cast<char>(kTypeValue));
   PutLengthPrefixedSlice(&rep_, key);
   PutLengthPrefixedSlice(&rep_, value);
 }
void rocksdb::WriteBatch::Put (const SliceParts & key, const SliceParts & value)
Definition at line 149 of file write_batch.cc.
References rocksdb::WriteBatchInternal::Count(), rocksdb::kTypeValue, rocksdb::PutLengthPrefixedSliceParts(), rep_, and rocksdb::WriteBatchInternal::SetCount().
{
   WriteBatchInternal::SetCount(this, WriteBatchInternal::Count(this) + 1);
   rep_.push_back(static_cast<char>(kTypeValue));
   PutLengthPrefixedSliceParts(&rep_, key);
   PutLengthPrefixedSliceParts(&rep_, value);
 }
void rocksdb::WriteBatch::PutLogData (const Slice & blob)
Definition at line 169 of file write_batch.cc.
References rocksdb::kTypeLogData, rocksdb::PutLengthPrefixedSlice(), and rep_.
Referenced by rocksdb::TEST().
{
   rep_.push_back(static_cast<char>(kTypeLogData));
   PutLengthPrefixedSlice(&rep_, blob);
 }
Friends And Related Function Documentation
friend class WriteBatchInternal friend
Definition at line 100 of file write_batch.h.
Member Data Documentation
std::string rocksdb::WriteBatch::rep_ private
Definition at line 102 of file write_batch.h.
Referenced by rocksdb::WriteBatchInternal::Append(), rocksdb::WriteBatchInternal::ByteSize(), Clear(), rocksdb::WriteBatchInternal::Contents(), rocksdb::WriteBatchInternal::Count(), Data(), Delete(), Iterate(), Merge(), Put(), PutLogData(), rocksdb::WriteBatchInternal::Sequence(), rocksdb::WriteBatchInternal::SetContents(), rocksdb::WriteBatchInternal::SetCount(), and rocksdb::WriteBatchInternal::SetSequence().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/include/rocksdb/write_batch.h
rippled/src/ripple/rocksdb/rocksdb/db/write_batch.cc