rippled: rocksdb::VersionSet Class Reference
rocksdb::VersionSet Class Reference
#include <version_set.h>
Classes
class Builder
struct FileSummaryStorage
struct fsize
struct LevelSummaryStorage
struct ManifestWriter
Public Types
typedef struct
rocksdb::VersionSet::fsize Fsize
Public Member Functions
VersionSet (const std::string &dbname, const Options *options, const EnvOptions &storage_options, TableCache *table_cache, const InternalKeyComparator *)
~VersionSet ()
Status LogAndApply (VersionEdit *edit, port::Mutex *mu, bool new_descriptor_log=false)
Status Recover ()
Status ReduceNumberOfLevels (int new_levels, port::Mutex *mu)
Version * current () const
uint64_t ManifestFileNumber () const
uint64_t NewFileNumber ()
void ReuseFileNumber (uint64_t file_number)
int NumLevelFiles (int level) const
int64_t NumLevelBytes (int level) const
uint64_t LastSequence () const
void SetLastSequence (uint64_t s)
void MarkFileNumberUsed (uint64_t number)
uint64_t LogNumber () const
uint64_t PrevLogNumber () const
int NumberLevels () const
Compaction * PickCompaction ()
Compaction * CompactRange (int level, const InternalKey *begin, const InternalKey *end)
int64_t MaxNextLevelOverlappingBytes ()
Iterator * MakeInputIterator (Compaction *c)
bool NeedsSizeCompaction () const
bool NeedsCompaction () const
double MaxCompactionScore () const
int MaxCompactionScoreLevel () const
void AddLiveFiles (std::vector< uint64_t > *live_list)
void AddLiveFilesCurrentVersion (std::set< uint64_t > *live)
uint64_t ApproximateOffsetOf (Version *v, const InternalKey &key)
const char * LevelSummary (LevelSummaryStorage *scratch) const
Status DumpManifest (Options &options, std::string &manifestFileName, bool verbose, bool hex=false)
const char * LevelDataSizeSummary (LevelSummaryStorage *scratch) const
const char * LevelFileSummary (FileSummaryStorage *scratch, int level) const
const uint64_t ManifestFileSize ()
Compaction * PickCompactionBySize (int level, double score)
Compaction * PickCompactionUniversal (int level, double score)
Compaction * PickCompactionUniversalReadAmp (int level, double score, unsigned int ratio, unsigned int num_files)
Compaction * PickCompactionUniversalSizeAmp (int level, double score)
void ReleaseCompactionFiles (Compaction *c, Status status)
bool VerifyCompactionFileConsistency (Compaction *c)
void UpdateFilesBySize (Version *v)
uint64_t MaxFileSizeForLevel (int level)
double MaxBytesForLevel (int level)
Status GetMetadataForFile (uint64_t number, int *filelevel, FileMetaData *metadata)
void GetLiveFilesMetaData (std::vector< LiveFileMetaData > *metadata)
void GetObsoleteFiles (std::vector< FileMetaData * > *files)
Private Member Functions
void Init (int num_levels)
void Finalize (Version *v, std::vector< uint64_t > &)
void GetRange (const std::vector< FileMetaData * > &inputs, InternalKey *smallest, InternalKey *largest)
void GetRange2 (const std::vector< FileMetaData * > &inputs1, const std::vector< FileMetaData * > &inputs2, InternalKey *smallest, InternalKey *largest)
void ExpandWhileOverlapping (Compaction *c)
void SetupOtherInputs (Compaction *c)
Status WriteSnapshot (log::Writer *log)
void AppendVersion (Version *v)
bool ManifestContains (const std::string &record) const
uint64_t ExpandedCompactionByteSizeLimit (int level)
uint64_t MaxGrandParentOverlapBytes (int level)
VersionSet (const VersionSet &)
void operator= (const VersionSet &)
void SizeBeingCompacted (std::vector< uint64_t > &)
bool ParentRangeInCompaction (const InternalKey *smallest, const InternalKey *largest, int level, int *index)
bool FilesInCompaction (std::vector< FileMetaData * > &files)
void LogAndApplyHelper (Builder *b, Version *v, VersionEdit *edit, port::Mutex *mu)
Private Attributes
Env *const env_
const std::string dbname_
const Options *const options_
TableCache *const table_cache_
const InternalKeyComparator icmp_
uint64_t next_file_number_
uint64_t manifest_file_number_
uint64_t last_sequence_
uint64_t log_number_
uint64_t prev_log_number_
int num_levels_
unique_ptr< log::Writer > descriptor_log_
Version dummy_versions_
Version * current_
std::string * compact_pointer_
uint64_t * max_file_size_
uint64_t * level_max_bytes_
std::vector< std::set
< Compaction * > > compactions_in_progress_
uint64_t current_version_number_
std::deque< ManifestWriter * > manifest_writers_
uint64_t last_observed_manifest_size_
std::vector< FileMetaData * > obsolete_files_
const EnvOptions & storage_options_
const EnvOptions storage_options_compactions_
Friends
class Compaction
class Version
Detailed Description
Definition at line 221 of file version_set.h.
Member Typedef Documentation
typedef struct rocksdb::VersionSet::fsize rocksdb::VersionSet::Fsize
Constructor & Destructor Documentation
rocksdb::VersionSet::VersionSet (const std::string & dbname, const Options * options, const EnvOptions & storage_options, TableCache * table_cache, const InternalKeyComparator * cmp)
Definition at line 1133 of file version_set.cc.
References AppendVersion(), compact_pointer_, current_version_number_, Init(), rocksdb::Options::num_levels, options_, and Version.
     : env_(options->env),
       dbname_(dbname),
       options_(options),
       table_cache_(table_cache),
       icmp_(*cmp),
       next_file_number_(2),
       manifest_file_number_(0),  // Filled by Recover()
       last_sequence_(0),
       log_number_(0),
       prev_log_number_(0),
       num_levels_(options_->num_levels),
       dummy_versions_(this),
       current_(nullptr),
       compactions_in_progress_(options_->num_levels),
       current_version_number_(0),
       last_observed_manifest_size_(0),
       storage_options_(storage_options),
       storage_options_compactions_(storage_options_)  {
   compact_pointer_ = new std::string[options_->num_levels];
   Init(options_->num_levels);
   AppendVersion(new Version(this, current_version_number_++));
 }
rocksdb::VersionSet::~VersionSet ()
Definition at line 1161 of file version_set.cc.
References compact_pointer_, current_, dummy_versions_, level_max_bytes_, max_file_size_, rocksdb::Version::next_, obsolete_files_, and rocksdb::Version::Unref().
{
   current_->Unref();
   assert(dummy_versions_.next_ == &dummy_versions_);  // List must be empty
   for (auto file : obsolete_files_) {
     delete file;
   }
   obsolete_files_.clear();
   delete[] compact_pointer_;
   delete[] max_file_size_;
   delete[] level_max_bytes_;
 }
rocksdb::VersionSet::VersionSet (const VersionSet &) private
Member Function Documentation
void rocksdb::VersionSet::AddLiveFiles (std::vector< uint64_t > * live_list)
Definition at line 1967 of file version_set.cc.
References dummy_versions_, ripple::f, rocksdb::Version::next_, and NumberLevels().
{
   // pre-calculate space requirement
   int64_t total_files = 0;
   for (Version* v = dummy_versions_.next_;
        v != &dummy_versions_;
        v = v->next_) {
     for (int level = 0; level < NumberLevels(); level++) {
       total_files += v->files_[level].size();
     }
   }
   // just one time extension to the right size
   live_list->reserve(live_list->size() + total_files);
   for (Version* v = dummy_versions_.next_;
        v != &dummy_versions_;
        v = v->next_) {
     for (int level = 0; level < NumberLevels(); level++) {
       for (const auto& f : v->files_[level]) {
         live_list->push_back(f->number);
       }
     }
   }
 }
void rocksdb::VersionSet::AddLiveFilesCurrentVersion (std::set< uint64_t > * live)
Definition at line 1992 of file version_set.cc.
References current_, rocksdb::Version::files_, and NumberLevels().
{
   Version* v = current_;
   for (int level = 0; level < NumberLevels(); level++) {
     const std::vector<FileMetaData*>& files = v->files_[level];
     for (size_t i = 0; i < files.size(); i++) {
       live->insert(files[i]->number);
     }
   }
 }
void rocksdb::VersionSet::AppendVersion (Version * v) private
Definition at line 1193 of file version_set.cc.
References current_, dummy_versions_, rocksdb::Version::next_, rocksdb::Version::prev_, rocksdb::Version::Ref(), rocksdb::Version::refs_, and rocksdb::Version::Unref().
Referenced by DumpManifest(), LogAndApply(), Recover(), and VersionSet().
{
   // Make "v" current
   assert(v->refs_ == 0);
   assert(v != current_);
   if (current_ != nullptr) {
     assert(current_->refs_ > 0);
     current_->Unref();
   }
   current_ = v;
   v->Ref();
   // Append to linked list
   v->prev_ = dummy_versions_.prev_;
   v->next_ = &dummy_versions_;
   v->prev_->next_ = v;
   v->next_->prev_ = v;
 }
uint64_t rocksdb::VersionSet::ApproximateOffsetOf (Version * v, const InternalKey & key)
Definition at line 1934 of file version_set.cc.
References rocksdb::TableReader::ApproximateOffsetOf(), rocksdb::InternalKeyComparator::Compare(), rocksdb::InternalKey::Encode(), rocksdb::Version::files_, icmp_, rocksdb::TableCache::NewIterator(), NumberLevels(), storage_options_, and table_cache_.
{
   uint64_t result = 0;
   for (int level = 0; level < NumberLevels(); level++) {
     const std::vector<FileMetaData*>& files = v->files_[level];
     for (size_t i = 0; i < files.size(); i++) {
       if (icmp_.Compare(files[i]->largest, ikey) <= 0) {
         // Entire file is before "ikey", so just add the file size
         result += files[i]->file_size;
       } else if (icmp_.Compare(files[i]->smallest, ikey) > 0) {
         // Entire file is after "ikey", so ignore
         if (level > 0) {
           // Files other than level 0 are sorted by meta->smallest, so
           // no further files in this level will contain data for
           // "ikey".
           break;
         }
       } else {
         // "ikey" falls in the range for this table.  Add the
         // approximate offset of "ikey" within the table.
         TableReader* table_reader_ptr;
         Iterator* iter = table_cache_->NewIterator(
             ReadOptions(), storage_options_, files[i]->number,
             files[i]->file_size, &table_reader_ptr);
         if (table_reader_ptr != nullptr) {
           result += table_reader_ptr->ApproximateOffsetOf(ikey.Encode());
         }
         delete iter;
       }
     }
   }
   return result;
 }
Compaction * rocksdb::VersionSet::CompactRange (int level, const InternalKey * begin, const InternalKey * end)
Definition at line 2904 of file version_set.cc.
References Compaction, rocksdb::Options::compaction_style, current_, ExpandWhileOverlapping(), rocksdb::Version::GetOverlappingInputs(), rocksdb::Options::info_log, rocksdb::Compaction::input_version_, rocksdb::Compaction::inputs_, rocksdb::kCompactionStyleUniversal, rocksdb::Log(), rocksdb::Compaction::MarkFilesBeingCompacted(), MaxFileSizeForLevel(), MaxGrandParentOverlapBytes(), NumberLevels(), options_, rocksdb::Version::Ref(), rocksdb::Compaction::SetupBottomMostLevel(), SetupOtherInputs(), and rocksdb::Options::source_compaction_factor.
{
   std::vector<FileMetaData*> inputs;
   // All files are 'overlapping' in universal style compaction.
   // We have to compact the entire range in one shot.
   if (options_->compaction_style == kCompactionStyleUniversal) {
     begin = nullptr;
     end = nullptr;
   }
   current_->GetOverlappingInputs(level, begin, end, &inputs);
   if (inputs.empty()) {
     return nullptr;
   }
   // Avoid compacting too much in one shot in case the range is large.
   // But we cannot do this for level-0 since level-0 files can overlap
   // and we must not pick one file and drop another older file if the
   // two files overlap.
   if (level > 0) {
     const uint64_t limit = MaxFileSizeForLevel(level) *
                          options_->source_compaction_factor;
     uint64_t total = 0;
     for (size_t i = 0; i < inputs.size(); ++i) {
       uint64_t s = inputs[i]->file_size;
       total += s;
       if (total >= limit) {
         inputs.resize(i + 1);
         break;
       }
     }
   }
   int out_level = (options_->compaction_style == kCompactionStyleUniversal) ?
                   level : level+1;
   Compaction* c = new Compaction(level, out_level, MaxFileSizeForLevel(out_level),
     MaxGrandParentOverlapBytes(level), NumberLevels());
   c->inputs_[0] = inputs;
   ExpandWhileOverlapping(c);
   if (c == nullptr) {
     Log(options_->info_log, "Could not compact due to expansion failure.\n");
     return nullptr;
   }
   c->input_version_ = current_;
   c->input_version_->Ref();
   SetupOtherInputs(c);
   // These files that are to be manaully compacted do not trample
   // upon other files because manual compactions are processed when
   // the system has a max of 1 background compaction thread.
   c->MarkFilesBeingCompacted(true);
   // Is this compaction creating a file at the bottommost level
   c->SetupBottomMostLevel(true);
   return c;
 }
Version* rocksdb::VersionSet::current () const inline
Definition at line 250 of file version_set.h.
References current_.
Referenced by Recover().
 { return current_; }
Status rocksdb::VersionSet::DumpManifest (Options & options, std::string & manifestFileName, bool verbose, bool hex = false)
Definition at line 1539 of file version_set.cc.
References AppendVersion(), rocksdb::VersionSet::Builder::Apply(), rocksdb::VersionEdit::comparator_, rocksdb::Status::Corruption(), current_, rocksdb::VersionEdit::DebugString(), rocksdb::Version::DebugString(), rocksdb::VersionEdit::DecodeFrom(), rocksdb::Options::env, Finalize(), rocksdb::VersionEdit::has_comparator_, rocksdb::VersionEdit::has_last_sequence_, rocksdb::VersionEdit::has_log_number_, rocksdb::VersionEdit::has_next_file_number_, rocksdb::VersionEdit::has_prev_log_number_, icmp_, rocksdb::Status::InvalidArgument(), rocksdb::VersionEdit::last_sequence_, last_sequence_, rocksdb::VersionEdit::log_number_, log_number_, manifest_file_number_, MarkFileNumberUsed(), rocksdb::Comparator::Name(), rocksdb::Env::NewSequentialFile(), rocksdb::VersionEdit::next_file_number_, next_file_number_, NumberLevels(), rocksdb::Status::ok(), rocksdb::VersionEdit::prev_log_number_, prev_log_number_, rocksdb::log::Reader::ReadRecord(), rocksdb::VersionSet::Builder::SaveTo(), SizeBeingCompacted(), storage_options_, rocksdb::InternalKeyComparator::user_comparator(), and Version.
Referenced by rocksdb::ManifestDumpCommand::DoCommand().
{
   struct LogReporter : public log::Reader::Reporter {
     Status* status;
     virtual void Corruption(size_t bytes, const Status& s) {
       if (this->status->ok()) *this->status = s;
     }
   };
   // Open the specified manifest file.
   unique_ptr<SequentialFile> file;
   Status s = options.env->NewSequentialFile(dscname, &file, storage_options_);
   if (!s.ok()) {
     return s;
   }
   bool have_log_number = false;
   bool have_prev_log_number = false;
   bool have_next_file = false;
   bool have_last_sequence = false;
   uint64_t next_file = 0;
   uint64_t last_sequence = 0;
   uint64_t log_number = 0;
   uint64_t prev_log_number = 0;
   int count = 0;
   VersionSet::Builder builder(this, current_);
   {
     LogReporter reporter;
     reporter.status = &s;
     log::Reader reader(std::move(file), &reporter, true/*checksum*/,
                        0/*initial_offset*/);
     Slice record;
     std::string scratch;
     while (reader.ReadRecord(&record, &scratch) && s.ok()) {
       VersionEdit edit(NumberLevels());
       s = edit.DecodeFrom(record);
       if (s.ok()) {
         if (edit.has_comparator_ &&
             edit.comparator_ != icmp_.user_comparator()->Name()) {
           s = Status::InvalidArgument(icmp_.user_comparator()->Name(),
                                       "does not match existing comparator " +
                                       edit.comparator_);
         }
       }
       // Write out each individual edit
       if (verbose) {
         printf("*************************Edit[%d] = %s\n",
                 count, edit.DebugString(hex).c_str());
       }
       count++;
       if (s.ok()) {
         builder.Apply(&edit);
       }
       if (edit.has_log_number_) {
         log_number = edit.log_number_;
         have_log_number = true;
       }
       if (edit.has_prev_log_number_) {
         prev_log_number = edit.prev_log_number_;
         have_prev_log_number = true;
       }
       if (edit.has_next_file_number_) {
         next_file = edit.next_file_number_;
         have_next_file = true;
       }
       if (edit.has_last_sequence_) {
         last_sequence = edit.last_sequence_;
         have_last_sequence = true;
       }
     }
   }
   file.reset();
   if (s.ok()) {
     if (!have_next_file) {
       s = Status::Corruption("no meta-nextfile entry in descriptor");
       printf("no meta-nextfile entry in descriptor");
     } else if (!have_log_number) {
       s = Status::Corruption("no meta-lognumber entry in descriptor");
       printf("no meta-lognumber entry in descriptor");
     } else if (!have_last_sequence) {
       printf("no last-sequence-number entry in descriptor");
       s = Status::Corruption("no last-sequence-number entry in descriptor");
     }
     if (!have_prev_log_number) {
       prev_log_number = 0;
     }
     MarkFileNumberUsed(prev_log_number);
     MarkFileNumberUsed(log_number);
   }
   if (s.ok()) {
     Version* v = new Version(this, 0);
     builder.SaveTo(v);
     // Install recovered version
     std::vector<uint64_t> size_being_compacted(NumberLevels()-1);
     SizeBeingCompacted(size_being_compacted);
     Finalize(v, size_being_compacted);
     AppendVersion(v);
     manifest_file_number_ = next_file;
     next_file_number_ = next_file + 1;
     last_sequence_ = last_sequence;
     log_number_ = log_number;
     prev_log_number_ = prev_log_number;
     printf("manifest_file_number %lu next_file_number %lu last_sequence "
            "%lu log_number %lu  prev_log_number %lu\n",
            (unsigned long)manifest_file_number_,
            (unsigned long)next_file_number_,
            (unsigned long)last_sequence,
            (unsigned long)log_number,
            (unsigned long)prev_log_number);
     printf("%s \n", v->DebugString(hex).c_str());
   }
   return s;
 }
uint64_t rocksdb::VersionSet::ExpandedCompactionByteSizeLimit (int level) private
Definition at line 2113 of file version_set.cc.
References rocksdb::Options::expanded_compaction_factor, MaxFileSizeForLevel(), and options_.
Referenced by SetupOtherInputs().
{
   uint64_t result = MaxFileSizeForLevel(level);
   result *= options_->expanded_compaction_factor;
   return result;
 }
void rocksdb::VersionSet::ExpandWhileOverlapping (Compaction * c) private
Definition at line 2727 of file version_set.cc.
References current_, FilesInCompaction(), rocksdb::Version::GetOverlappingInputs(), GetRange(), rocksdb::Compaction::inputs_, rocksdb::Compaction::level(), and ParentRangeInCompaction().
Referenced by CompactRange(), and PickCompaction().
{
   // If inputs are empty then there is nothing to expand.
   if (!c || c->inputs_[0].empty()) {
     return;
   }
   // GetOverlappingInputs will always do the right thing for level-0.
   // So we don't need to do any expansion if level == 0.
   if (c->level() == 0) {
     return;
   }
   const int level = c->level();
   InternalKey smallest, largest;
   // Keep expanding c->inputs_[0] until we are sure that there is a
   // "clean cut" boundary between the files in input and the surrounding files.
   // This will ensure that no parts of a key are lost during compaction.
   int hint_index = -1;
   size_t old_size;
   do {
     old_size = c->inputs_[0].size();
     GetRange(c->inputs_[0], &smallest, &largest);
     c->inputs_[0].clear();
     current_->GetOverlappingInputs(level, &smallest, &largest, &c->inputs_[0],
                                    hint_index, &hint_index);
   } while(c->inputs_[0].size() > old_size);
   // Get the new range
   GetRange(c->inputs_[0], &smallest, &largest);
   // If, after the expansion, there are files that are already under
   // compaction, then we must drop/cancel this compaction.
   int parent_index = -1;
   if (FilesInCompaction(c->inputs_[0]) ||
       ParentRangeInCompaction(&smallest, &largest, level, &parent_index)) {
     c->inputs_[0].clear();
     c->inputs_[1].clear();
     delete c;
     c = nullptr;
   }
 }
bool rocksdb::VersionSet::FilesInCompaction (std::vector< FileMetaData * > & files) private
Definition at line 2708 of file version_set.cc.
Referenced by ExpandWhileOverlapping(), ParentRangeInCompaction(), and SetupOtherInputs().
{
   for (unsigned int i = 0; i < files.size(); i++) {
     if (files[i]->being_compacted) {
       return true;
     }
   }
   return false;
 }
void rocksdb::VersionSet::Finalize (Version * v, std::vector< uint64_t > & size_being_compacted) private
Definition at line 1674 of file version_set.cc.
References rocksdb::Version::compaction_level_, rocksdb::Version::compaction_score_, rocksdb::Options::compaction_style, rocksdb::Version::files_, rocksdb::kCompactionStyleUniversal, rocksdb::Options::level0_file_num_compaction_trigger, rocksdb::Options::level0_slowdown_writes_trigger, rocksdb::Options::level0_stop_writes_trigger, rocksdb::Version::max_compaction_score_, rocksdb::Version::max_compaction_score_level_, MaxBytesForLevel(), NumberLevels(), options_, beast::hash_metrics::detail::score(), and rocksdb::TotalFileSize().
Referenced by DumpManifest(), LogAndApply(), PickCompaction(), and Recover().
{
   double max_score = 0;
   int max_score_level = 0;
   int num_levels_to_check =
       (options_->compaction_style != kCompactionStyleUniversal) ?
           NumberLevels() - 1 : 1;
   for (int level = 0; level < num_levels_to_check; level++) {
     double score;
     if (level == 0) {
       // We treat level-0 specially by bounding the number of files
       // instead of number of bytes for two reasons:
       //
       // (1) With larger write-buffer sizes, it is nice not to do too
       // many level-0 compactions.
       //
       // (2) The files in level-0 are merged on every read and
       // therefore we wish to avoid too many files when the individual
       // file size is small (perhaps because of a small write-buffer
       // setting, or very high compression ratios, or lots of
       // overwrites/deletions).
       int numfiles = 0;
       for (unsigned int i = 0; i < v->files_[level].size(); i++) {
         if (!v->files_[level][i]->being_compacted) {
           numfiles++;
         }
       }
       // If we are slowing down writes, then we better compact that first
       if (numfiles >= options_->level0_stop_writes_trigger) {
         score = 1000000;
         // Log(options_->info_log, "XXX score l0 = 1000000000 max");
       } else if (numfiles >= options_->level0_slowdown_writes_trigger) {
         score = 10000;
         // Log(options_->info_log, "XXX score l0 = 1000000 medium");
       } else {
         score = numfiles /
           static_cast<double>(options_->level0_file_num_compaction_trigger);
         if (score >= 1) {
           // Log(options_->info_log, "XXX score l0 = %d least", (int)score);
         }
       }
     } else {
       // Compute the ratio of current size to size limit.
       const uint64_t level_bytes = TotalFileSize(v->files_[level]) -
                                    size_being_compacted[level];
       score = static_cast<double>(level_bytes) / MaxBytesForLevel(level);
       if (score > 1) {
         // Log(options_->info_log, "XXX score l%d = %d ", level, (int)score);
       }
       if (max_score < score) {
         max_score = score;
         max_score_level = level;
       }
     }
     v->compaction_level_[level] = level;
     v->compaction_score_[level] = score;
   }
   // update the max compaction score in levels 1 to n-1
   v->max_compaction_score_ = max_score;
   v->max_compaction_score_level_ = max_score_level;
   // sort all the levels based on their score. Higher scores get listed
   // first. Use bubble sort because the number of entries are small.
   for (int i = 0; i <  NumberLevels()-2; i++) {
     for (int j = i+1; j < NumberLevels()-1; j++) {
       if (v->compaction_score_[i] < v->compaction_score_[j]) {
         double score = v->compaction_score_[i];
         int level = v->compaction_level_[i];
         v->compaction_score_[i] = v->compaction_score_[j];
         v->compaction_level_[i] = v->compaction_level_[j];
         v->compaction_score_[j] = score;
         v->compaction_level_[j] = level;
       }
     }
   }
 }
void rocksdb::VersionSet::GetLiveFilesMetaData (std::vector< LiveFileMetaData > * metadata)
Definition at line 2879 of file version_set.cc.
References current_, rocksdb::Version::files_, rocksdb::LiveFileMetaData::largest_seqno, rocksdb::LiveFileMetaData::largestkey, rocksdb::LiveFileMetaData::level, rocksdb::LiveFileMetaData::name, NumberLevels(), rocksdb::LiveFileMetaData::size, rocksdb::LiveFileMetaData::smallest_seqno, rocksdb::LiveFileMetaData::smallestkey, and rocksdb::TableFileName().
{
   for (int level = 0; level < NumberLevels(); level++) {
     const std::vector<FileMetaData*>& files = current_->files_[level];
     for (size_t i = 0; i < files.size(); i++) {
       LiveFileMetaData filemetadata;
       filemetadata.name = TableFileName("", files[i]->number);
       filemetadata.level = level;
       filemetadata.size = files[i]->file_size;
       filemetadata.smallestkey = files[i]->smallest.user_key().ToString();
       filemetadata.largestkey = files[i]->largest.user_key().ToString();
       filemetadata.smallest_seqno = files[i]->smallest_seqno;
       filemetadata.largest_seqno = files[i]->largest_seqno;
       metadata->push_back(filemetadata);
     }
   }
 }
Status rocksdb::VersionSet::GetMetadataForFile (uint64_t number, int * filelevel, FileMetaData * metadata)
Definition at line 2862 of file version_set.cc.
References current_, rocksdb::Version::files_, rocksdb::Status::NotFound(), NumberLevels(), and rocksdb::Status::OK().
{
   for (int level = 0; level < NumberLevels(); level++) {
     const std::vector<FileMetaData*>& files = current_->files_[level];
     for (size_t i = 0; i < files.size(); i++) {
       if (files[i]->number == number) {
         *meta = *files[i];
         *filelevel = level;
         return Status::OK();
       }
     }
   }
   return Status::NotFound("File not present in any level");
 }
void rocksdb::VersionSet::GetObsoleteFiles (std::vector< FileMetaData * > * files)
Definition at line 2897 of file version_set.cc.
References obsolete_files_.
{
   files->insert(files->end(),
                 obsolete_files_.begin(),
                 obsolete_files_.end());
   obsolete_files_.clear();
 }
void rocksdb::VersionSet::GetRange (const std::vector< FileMetaData * > & inputs, InternalKey * smallest, InternalKey * largest) private
Definition at line 2029 of file version_set.cc.
References rocksdb::InternalKey::Clear(), rocksdb::InternalKeyComparator::Compare(), ripple::f, icmp_, rocksdb::FileMetaData::largest, and rocksdb::FileMetaData::smallest.
Referenced by ExpandWhileOverlapping(), GetRange2(), PickCompaction(), and SetupOtherInputs().
{
   assert(!inputs.empty());
   smallest->Clear();
   largest->Clear();
   for (size_t i = 0; i < inputs.size(); i++) {
     FileMetaData* f = inputs[i];
     if (i == 0) {
       *smallest = f->smallest;
       *largest = f->largest;
     } else {
       if (icmp_.Compare(f->smallest, *smallest) < 0) {
         *smallest = f->smallest;
       }
       if (icmp_.Compare(f->largest, *largest) > 0) {
         *largest = f->largest;
       }
     }
   }
 }
void rocksdb::VersionSet::GetRange2 (const std::vector< FileMetaData * > & inputs1, const std::vector< FileMetaData * > & inputs2, InternalKey * smallest, InternalKey * largest) private
Definition at line 2054 of file version_set.cc.
References GetRange().
Referenced by SetupOtherInputs().
{
   std::vector<FileMetaData*> all = inputs1;
   all.insert(all.end(), inputs2.begin(), inputs2.end());
   GetRange(all, smallest, largest);
 }
void rocksdb::VersionSet::Init (int num_levels) private
Definition at line 1173 of file version_set.cc.
References rocksdb::Options::compaction_style, rocksdb::kCompactionStyleUniversal, level_max_bytes_, rocksdb::Options::max_bytes_for_level_base, rocksdb::Options::max_bytes_for_level_multiplier, rocksdb::Options::max_bytes_for_level_multiplier_additional, max_file_size_, options_, rocksdb::Options::target_file_size_base, rocksdb::Options::target_file_size_multiplier, and ULLONG_MAX.
Referenced by ReduceNumberOfLevels(), and VersionSet().
{
   max_file_size_ = new uint64_t[num_levels];
   level_max_bytes_ = new uint64_t[num_levels];
   int target_file_size_multiplier = options_->target_file_size_multiplier;
   int max_bytes_multiplier = options_->max_bytes_for_level_multiplier;
   for (int i = 0; i < num_levels; i++) {
     if (i == 0 && options_->compaction_style == kCompactionStyleUniversal) {
       max_file_size_[i] = ULLONG_MAX;
       level_max_bytes_[i] = options_->max_bytes_for_level_base;
     } else if (i > 1) {
       max_file_size_[i] = max_file_size_[i-1] * target_file_size_multiplier;
       level_max_bytes_[i] = level_max_bytes_[i-1] * max_bytes_multiplier *
         options_->max_bytes_for_level_multiplier_additional[i-1];
     } else {
       max_file_size_[i] = options_->target_file_size_base;
       level_max_bytes_[i] = options_->max_bytes_for_level_base;
     }
   }
 }
uint64_t rocksdb::VersionSet::LastSequence () const inline
Definition at line 274 of file version_set.h.
References last_sequence_.
 { return last_sequence_; }
const char * rocksdb::VersionSet::LevelDataSizeSummary (LevelSummaryStorage * scratch) const
Definition at line 1870 of file version_set.cc.
References rocksdb::VersionSet::LevelSummaryStorage::buffer, NumberLevels(), and NumLevelBytes().
{
   int len = snprintf(scratch->buffer, sizeof(scratch->buffer), "files_size[");
   for (int i = 0; i < NumberLevels(); i++) {
     int sz = sizeof(scratch->buffer) - len;
     int ret = snprintf(scratch->buffer + len, sz, "%lu ",
         (unsigned long)NumLevelBytes(i));
     if (ret < 0 || ret >= sz)
       break;
     len += ret;
   }
   snprintf(scratch->buffer + len, sizeof(scratch->buffer) - len, "]");
   return scratch->buffer;
 }
const char * rocksdb::VersionSet::LevelFileSummary (FileSummaryStorage * scratch, int level) const
Definition at line 1885 of file version_set.cc.
References rocksdb::FileMetaData::being_compacted, rocksdb::VersionSet::FileSummaryStorage::buffer, current_, ripple::f, rocksdb::FileMetaData::file_size, rocksdb::Version::files_, rocksdb::FileMetaData::number, and rocksdb::FileMetaData::smallest_seqno.
Referenced by PickCompactionUniversal().
{
   int len = snprintf(scratch->buffer, sizeof(scratch->buffer), "files_size[");
   for (unsigned int i = 0; i < current_->files_[level].size(); i++) {
     FileMetaData* f = current_->files_[level][i];
     int sz = sizeof(scratch->buffer) - len;
     int ret = snprintf(scratch->buffer + len, sz,
                        "#%lu(seq=%lu,sz=%lu,%lu) ",
                        (unsigned long)f->number,
                        (unsigned long)f->smallest_seqno,
                        (unsigned long)f->file_size,
                        (unsigned long)f->being_compacted);
     if (ret < 0 || ret >= sz)
       break;
     len += ret;
   }
   snprintf(scratch->buffer + len, sizeof(scratch->buffer) - len, "]");
   return scratch->buffer;
 }
const char * rocksdb::VersionSet::LevelSummary (LevelSummaryStorage * scratch) const
Definition at line 1856 of file version_set.cc.
References rocksdb::VersionSet::LevelSummaryStorage::buffer, current_, rocksdb::Version::files_, and NumberLevels().
{
   int len = snprintf(scratch->buffer, sizeof(scratch->buffer), "files[");
   for (int i = 0; i < NumberLevels(); i++) {
     int sz = sizeof(scratch->buffer) - len;
     int ret = snprintf(scratch->buffer + len, sz, "%d ",
         int(current_->files_[i].size()));
     if (ret < 0 || ret >= sz)
       break;
     len += ret;
   }
   snprintf(scratch->buffer + len, sizeof(scratch->buffer) - len, "]");
   return scratch->buffer;
 }
Status rocksdb::VersionSet::LogAndApply (VersionEdit * edit, port::Mutex * mu, bool new_descriptor_log = false)
Definition at line 1211 of file version_set.cc.
References AppendVersion(), rocksdb::port::Mutex::AssertHeld(), current_, current_version_number_, rocksdb::VersionSet::ManifestWriter::cv, dbname_, rocksdb::Env::DeleteFile(), descriptor_log_, rocksdb::DescriptorFileName(), rocksdb::VersionSet::ManifestWriter::done, rocksdb::VersionSet::ManifestWriter::edit, env_, Finalize(), rocksdb::Version::GetVersionNumber(), rocksdb::Options::info_log, last_observed_manifest_size_, rocksdb::port::Mutex::Lock(), rocksdb::Log(), rocksdb::VersionEdit::log_number_, log_number_, LogAndApplyHelper(), rocksdb::LogFlush(), manifest_file_number_, rocksdb::MANIFEST_FILE_SYNC_MICROS, manifest_writers_, ManifestContains(), rocksdb::Options::max_manifest_file_size, NewFileNumber(), rocksdb::Env::NewWritableFile(), next_file_number_, NumberLevels(), rocksdb::Version::offset_manifest_file_, rocksdb::Status::OK(), rocksdb::Status::ok(), options_, rocksdb::VersionEdit::prev_log_number_, prev_log_number_, rocksdb::VersionSet::Builder::SaveTo(), rocksdb::SetCurrentFile(), rocksdb::VersionEdit::SetNextFile(), rocksdb::port::CondVar::Signal(), SizeBeingCompacted(), rocksdb::Options::statistics, rocksdb::VersionSet::ManifestWriter::status, storage_options_, rocksdb::Status::ToString(), rocksdb::port::Mutex::Unlock(), UpdateFilesBySize(), rocksdb::Options::use_fsync, Version, rocksdb::port::CondVar::Wait(), and WriteSnapshot().
Referenced by rocksdb::BM_LogAndApply(), rocksdb::MemTableList::InstallMemtableFlushResults(), and ReduceNumberOfLevels().
{
   mu->AssertHeld();
   // queue our request
   ManifestWriter w(mu, edit);
   manifest_writers_.push_back(&w);
   while (!w.done && &w != manifest_writers_.front()) {
     w.cv.Wait();
   }
   if (w.done) {
     return w.status;
   }
   std::vector<VersionEdit*> batch_edits;
   Version* v = new Version(this, current_version_number_++);
   Builder builder(this, current_);
   // process all requests in the queue
   ManifestWriter* last_writer = &w;
   assert(!manifest_writers_.empty());
   assert(manifest_writers_.front() == &w);
   std::deque<ManifestWriter*>::iterator iter = manifest_writers_.begin();
   for (; iter != manifest_writers_.end(); ++iter) {
     last_writer = *iter;
     LogAndApplyHelper(&builder, v, last_writer->edit, mu);
     batch_edits.push_back(last_writer->edit);
   }
   builder.SaveTo(v);
   // Initialize new descriptor log file if necessary by creating
   // a temporary file that contains a snapshot of the current version.
   std::string new_manifest_file;
   uint64_t new_manifest_file_size = 0;
   Status s;
   // we will need this if we are creating new manifest
   uint64_t old_manifest_file_number = manifest_file_number_;
   //  No need to perform this check if a new Manifest is being created anyways.
   if (!descriptor_log_ ||
       last_observed_manifest_size_ > options_->max_manifest_file_size) {
     new_descriptor_log = true;
     manifest_file_number_ = NewFileNumber(); // Change manifest file no.
   }
   if (new_descriptor_log) {
     new_manifest_file = DescriptorFileName(dbname_, manifest_file_number_);
     edit->SetNextFile(next_file_number_);
   }
   // Unlock during expensive MANIFEST log write. New writes cannot get here
   // because &w is ensuring that all new writes get queued.
   {
     // calculate the amount of data being compacted at every level
     std::vector<uint64_t> size_being_compacted(NumberLevels()-1);
     SizeBeingCompacted(size_being_compacted);
     mu->Unlock();
     // This is fine because everything inside of this block is serialized --
     // only one thread can be here at the same time
     if (!new_manifest_file.empty()) {
       unique_ptr<WritableFile> descriptor_file;
       s = env_->NewWritableFile(new_manifest_file, &descriptor_file,
                                 storage_options_);
       if (s.ok()) {
         descriptor_log_.reset(new log::Writer(std::move(descriptor_file)));
         s = WriteSnapshot(descriptor_log_.get());
       }
     }
     // The calls to Finalize and UpdateFilesBySize are cpu-heavy
     // and is best called outside the mutex.
     Finalize(v, size_being_compacted);
     UpdateFilesBySize(v);
     // Write new record to MANIFEST log
     if (s.ok()) {
       std::string record;
       for (unsigned int i = 0; i < batch_edits.size(); i++) {
         batch_edits[i]->EncodeTo(&record);
         s = descriptor_log_->AddRecord(record);
         if (!s.ok()) {
           break;
         }
       }
       if (s.ok()) {
         if (options_->use_fsync) {
           StopWatch sw(env_, options_->statistics, MANIFEST_FILE_SYNC_MICROS);
           s = descriptor_log_->file()->Fsync();
         } else {
           StopWatch sw(env_, options_->statistics, MANIFEST_FILE_SYNC_MICROS);
           s = descriptor_log_->file()->Sync();
         }
       }
       if (!s.ok()) {
         Log(options_->info_log, "MANIFEST write: %s\n", s.ToString().c_str());
         if (ManifestContains(record)) {
           Log(options_->info_log,
               "MANIFEST contains log record despite error; advancing to new "
               "version to prevent mismatch between in-memory and logged state"
               " If paranoid is set, then the db is now in readonly mode.");
           s = Status::OK();
         }
       }
     }
     // If we just created a new descriptor file, install it by writing a
     // new CURRENT file that points to it.
     if (s.ok() && !new_manifest_file.empty()) {
       s = SetCurrentFile(env_, dbname_, manifest_file_number_);
       if (s.ok() && old_manifest_file_number < manifest_file_number_) {
         // delete old manifest file
         Log(options_->info_log,
             "Deleting manifest %lu current manifest %lu\n",
             (unsigned long)old_manifest_file_number,
             (unsigned long)manifest_file_number_);
         // we don't care about an error here, PurgeObsoleteFiles will take care
         // of it later
         env_->DeleteFile(DescriptorFileName(dbname_, old_manifest_file_number));
       }
     }
     // find offset in manifest file where this version is stored.
     new_manifest_file_size = descriptor_log_->file()->GetFileSize();
     LogFlush(options_->info_log);
     mu->Lock();
     // cache the manifest_file_size so that it can be used to rollover in the
     // next call to LogAndApply
     last_observed_manifest_size_ = new_manifest_file_size;
   }
   // Install the new version
   if (s.ok()) {
     v->offset_manifest_file_ = new_manifest_file_size;
     AppendVersion(v);
     log_number_ = edit->log_number_;
     prev_log_number_ = edit->prev_log_number_;
   } else {
     Log(options_->info_log, "Error in committing version %lu",
         (unsigned long)v->GetVersionNumber());
     delete v;
     if (!new_manifest_file.empty()) {
       descriptor_log_.reset();
       env_->DeleteFile(new_manifest_file);
     }
   }
   // wake up all the waiting writers
   while (true) {
     ManifestWriter* ready = manifest_writers_.front();
     manifest_writers_.pop_front();
     if (ready != &w) {
       ready->status = s;
       ready->done = true;
       ready->cv.Signal();
     }
     if (ready == last_writer) break;
   }
   // Notify new head of write queue
   if (!manifest_writers_.empty()) {
     manifest_writers_.front()->cv.Signal();
   }
   return s;
 }
void rocksdb::VersionSet::LogAndApplyHelper (Builder * b, Version * v, VersionEdit * edit, port::Mutex * mu) private
Definition at line 1379 of file version_set.cc.
References rocksdb::VersionSet::Builder::Apply(), rocksdb::port::Mutex::AssertHeld(), rocksdb::VersionEdit::has_log_number_, rocksdb::VersionEdit::has_prev_log_number_, last_sequence_, rocksdb::VersionEdit::log_number_, log_number_, next_file_number_, prev_log_number_, rocksdb::VersionEdit::SetLastSequence(), rocksdb::VersionEdit::SetLogNumber(), rocksdb::VersionEdit::SetNextFile(), and rocksdb::VersionEdit::SetPrevLogNumber().
Referenced by LogAndApply().
{
   mu->AssertHeld();
   if (edit->has_log_number_) {
     assert(edit->log_number_ >= log_number_);
     assert(edit->log_number_ < next_file_number_);
   } else {
     edit->SetLogNumber(log_number_);
   }
   if (!edit->has_prev_log_number_) {
     edit->SetPrevLogNumber(prev_log_number_);
   }
   edit->SetNextFile(next_file_number_);
   edit->SetLastSequence(last_sequence_);
   builder->Apply(edit);
 }
uint64_t rocksdb::VersionSet::LogNumber () const inline
Definition at line 286 of file version_set.h.
References log_number_.
 { return log_number_; }
Iterator * rocksdb::VersionSet::MakeInputIterator (Compaction * c)
Definition at line 2063 of file version_set.cc.
References rocksdb::ReadOptions::fill_cache, rocksdb::GetFileIterator(), icmp_, rocksdb::Compaction::inputs_, rocksdb::Compaction::level(), rocksdb::TableCache::NewIterator(), rocksdb::NewMergingIterator(), rocksdb::NewTwoLevelIterator(), options_, rocksdb::Options::paranoid_checks, storage_options_, storage_options_compactions_, table_cache_, and rocksdb::ReadOptions::verify_checksums.
{
   ReadOptions options;
   options.verify_checksums = options_->paranoid_checks;
   options.fill_cache = false;
   // Level-0 files have to be merged together.  For other levels,
   // we will make a concatenating iterator per level.
   // TODO(opt): use concatenating iterator for level-0 if there is no overlap
   const int space = (c->level() == 0 ? c->inputs_[0].size() + 1 : 2);
   Iterator** list = new Iterator*[space];
   int num = 0;
   for (int which = 0; which < 2; which++) {
     if (!c->inputs_[which].empty()) {
       if (c->level() + which == 0) {
         const std::vector<FileMetaData*>& files = c->inputs_[which];
         for (size_t i = 0; i < files.size(); i++) {
           list[num++] = table_cache_->NewIterator(
               options, storage_options_compactions_,
               files[i]->number, files[i]->file_size, nullptr,
               true /* for compaction */);
         }
       } else {
         // Create concatenating iterator for the files from this level
         list[num++] = NewTwoLevelIterator(
             new Version::LevelFileNumIterator(icmp_, &c->inputs_[which]),
             &GetFileIterator, table_cache_, options, storage_options_,
             true /* for compaction */);
       }
     }
   }
   assert(num <= space);
   Iterator* result = NewMergingIterator(&icmp_, list, num);
   delete[] list;
   return result;
 }
bool rocksdb::VersionSet::ManifestContains (const std::string & record) const private
Definition at line 1907 of file version_set.cc.
References dbname_, rocksdb::DescriptorFileName(), env_, rocksdb::Options::info_log, rocksdb::Log(), manifest_file_number_, rocksdb::Env::NewSequentialFile(), rocksdb::Status::ok(), options_, rocksdb::log::Reader::ReadRecord(), storage_options_, and rocksdb::Status::ToString().
Referenced by LogAndApply().
{
   std::string fname = DescriptorFileName(dbname_, manifest_file_number_);
   Log(options_->info_log, "ManifestContains: checking %s\n", fname.c_str());
   unique_ptr<SequentialFile> file;
   Status s = env_->NewSequentialFile(fname, &file, storage_options_);
   if (!s.ok()) {
     Log(options_->info_log, "ManifestContains: %s\n", s.ToString().c_str());
     Log(options_->info_log,
         "ManifestContains: is unable to reopen the manifest file  %s",
         fname.c_str());
     return false;
   }
   log::Reader reader(std::move(file), nullptr, true/*checksum*/, 0);
   Slice r;
   std::string scratch;
   bool result = false;
   while (reader.ReadRecord(&r, &scratch)) {
     if (r == Slice(record)) {
       result = true;
       break;
     }
   }
   Log(options_->info_log, "ManifestContains: result = %d\n", result ? 1 : 0);
   return result;
 }
uint64_t rocksdb::VersionSet::ManifestFileNumber () const inline
Definition at line 253 of file version_set.h.
References manifest_file_number_.
 { return manifest_file_number_; }
const uint64_t rocksdb::VersionSet::ManifestFileSize () inline
Definition at line 386 of file version_set.h.
References current_, and rocksdb::Version::offset_manifest_file_.
 { return current_->offset_manifest_file_; }
void rocksdb::VersionSet::MarkFileNumberUsed (uint64_t number)
Definition at line 1668 of file version_set.cc.
References next_file_number_.
Referenced by DumpManifest(), and Recover().
{
   if (next_file_number_ <= number) {
     next_file_number_ = number + 1;
   }
 }
double rocksdb::VersionSet::MaxBytesForLevel (int level)
Definition at line 2099 of file version_set.cc.
References level_max_bytes_, and NumberLevels().
Referenced by Finalize().
{
   // Note: the result for level zero is not really used since we set
   // the level-0 compaction threshold based on number of files.
   assert(level >= 0);
   assert(level < NumberLevels());
   return level_max_bytes_[level];
 }
double rocksdb::VersionSet::MaxCompactionScore () const inline
Definition at line 344 of file version_set.h.
References current_, and rocksdb::Version::max_compaction_score_.
{
     return current_->max_compaction_score_;
   }
int rocksdb::VersionSet::MaxCompactionScoreLevel () const inline
Definition at line 349 of file version_set.h.
References current_, and rocksdb::Version::max_compaction_score_level_.
{
     return current_->max_compaction_score_level_;
   }
uint64_t rocksdb::VersionSet::MaxFileSizeForLevel (int level)
Definition at line 2107 of file version_set.cc.
References max_file_size_, and NumberLevels().
Referenced by CompactRange(), ExpandedCompactionByteSizeLimit(), MaxGrandParentOverlapBytes(), PickCompaction(), PickCompactionBySize(), PickCompactionUniversalReadAmp(), and PickCompactionUniversalSizeAmp().
{
   assert(level >= 0);
   assert(level < NumberLevels());
   return max_file_size_[level];
 }
uint64_t rocksdb::VersionSet::MaxGrandParentOverlapBytes (int level) private
Definition at line 2119 of file version_set.cc.
References rocksdb::Options::max_grandparent_overlap_factor, MaxFileSizeForLevel(), and options_.
Referenced by CompactRange(), PickCompaction(), PickCompactionBySize(), and rocksdb::Version::PickLevelForMemTableOutput().
{
   uint64_t result = MaxFileSizeForLevel(level);
   result *= options_->max_grandparent_overlap_factor;
   return result;
 }
int64_t rocksdb::VersionSet::MaxNextLevelOverlappingBytes ()
Definition at line 2009 of file version_set.cc.
References current_, ripple::f, rocksdb::Version::files_, rocksdb::Version::GetOverlappingInputs(), rocksdb::FileMetaData::largest, NumberLevels(), rocksdb::FileMetaData::smallest, and rocksdb::TotalFileSize().
{
   uint64_t result = 0;
   std::vector<FileMetaData*> overlaps;
   for (int level = 1; level < NumberLevels() - 1; level++) {
     for (size_t i = 0; i < current_->files_[level].size(); i++) {
       const FileMetaData* f = current_->files_[level][i];
       current_->GetOverlappingInputs(level+1, &f->smallest, &f->largest,
                                      &overlaps);
       const uint64_t sum = TotalFileSize(overlaps);
       if (sum > result) {
         result = sum;
       }
     }
   }
   return result;
 }
bool rocksdb::VersionSet::NeedsCompaction () const inline
Definition at line 338 of file version_set.h.
References current_, rocksdb::Version::file_to_compact_, and NeedsSizeCompaction().
{
     return ((current_->file_to_compact_ != nullptr) ||
             NeedsSizeCompaction());
   }
bool rocksdb::VersionSet::NeedsSizeCompaction () const inline
Definition at line 319 of file version_set.h.
References rocksdb::Version::compaction_score_, rocksdb::Options::compaction_style, current_, rocksdb::kCompactionStyleUniversal, NumberLevels(), and options_.
Referenced by NeedsCompaction().
{
     // In universal compaction case, this check doesn't really
     // check the compaction condition, but checks num of files threshold
     // only. We are not going to miss any compaction opportunity
     // but it's likely that more compactions are scheduled but
     // ending up with nothing to do. We can improve it later.
     // TODO: improve this function to be accurate for universal
     //       compactions.
     int num_levels_to_check =
         (options_->compaction_style != kCompactionStyleUniversal) ?
             NumberLevels() - 1 : 1;
     for (int i = 0; i < num_levels_to_check; i++) {
       if (current_->compaction_score_[i] >= 1) {
         return true;
       }
     }
     return false;
   }
uint64_t rocksdb::VersionSet::NewFileNumber () inline
Definition at line 256 of file version_set.h.
References next_file_number_.
Referenced by LogAndApply().
 { return next_file_number_++; }
int rocksdb::VersionSet::NumberLevels () const inline
Definition at line 292 of file version_set.h.
References num_levels_.
Referenced by rocksdb::Version::AddIterators(), AddLiveFiles(), AddLiveFilesCurrentVersion(), ApproximateOffsetOf(), rocksdb::BM_LogAndApply(), rocksdb::VersionSet::Builder::Builder(), rocksdb::VersionSet::Builder::CheckConsistency(), CompactRange(), rocksdb::Version::DebugString(), DumpManifest(), Finalize(), rocksdb::Version::Get(), GetLiveFilesMetaData(), GetMetadataForFile(), rocksdb::ReduceDBLevelsCommand::GetOldNumOfLevels(), LevelDataSizeSummary(), LevelSummary(), LogAndApply(), MaxBytesForLevel(), MaxFileSizeForLevel(), MaxNextLevelOverlappingBytes(), NeedsSizeCompaction(), NumLevelBytes(), NumLevelFiles(), PickCompaction(), PickCompactionBySize(), PickCompactionUniversalReadAmp(), PickCompactionUniversalSizeAmp(), rocksdb::Version::PickLevelForMemTableOutput(), Recover(), ReduceNumberOfLevels(), rocksdb::VersionSet::Builder::SaveTo(), rocksdb::Compaction::SetupBottomMostLevel(), SetupOtherInputs(), SizeBeingCompacted(), UpdateFilesBySize(), WriteSnapshot(), rocksdb::VersionSet::Builder::~Builder(), and rocksdb::Version::~Version().
 { return num_levels_; }
int64_t rocksdb::VersionSet::NumLevelBytes (int level) const
Definition at line 2002 of file version_set.cc.
References current_, rocksdb::Version::files_, NumberLevels(), and rocksdb::TotalFileSize().
Referenced by LevelDataSizeSummary().
{
   assert(level >= 0);
   assert(level < NumberLevels());
   assert(current_);
   return TotalFileSize(current_->files_[level]);
 }
int rocksdb::VersionSet::NumLevelFiles (int level) const
Definition at line 1850 of file version_set.cc.
References current_, rocksdb::Version::files_, and NumberLevels().
Referenced by rocksdb::ReduceDBLevelsCommand::GetOldNumOfLevels(), ReduceNumberOfLevels(), and rocksdb::Compaction::SetupBottomMostLevel().
{
   assert(level >= 0);
   assert(level < NumberLevels());
   return current_->files_[level].size();
 }
void rocksdb::VersionSet::operator= (const VersionSet &) private
bool rocksdb::VersionSet::ParentRangeInCompaction (const InternalKey * smallest, const InternalKey * largest, int level, int * index) private
Definition at line 2698 of file version_set.cc.
References current_, FilesInCompaction(), and rocksdb::Version::GetOverlappingInputs().
Referenced by ExpandWhileOverlapping(), PickCompaction(), and PickCompactionBySize().
{
   std::vector<FileMetaData*> inputs;
   current_->GetOverlappingInputs(level+1, smallest, largest,
                                  &inputs, *parent_index, parent_index);
   return FilesInCompaction(inputs);
 }
Compaction * rocksdb::VersionSet::PickCompaction ()
Definition at line 2595 of file version_set.cc.
References rocksdb::FileMetaData::being_compacted, Compaction, rocksdb::Version::compaction_level_, rocksdb::Version::compaction_score_, rocksdb::Options::compaction_style, compactions_in_progress_, current_, ExpandWhileOverlapping(), ripple::f, rocksdb::Version::file_to_compact_, rocksdb::Version::file_to_compact_level_, Finalize(), rocksdb::Version::GetOverlappingInputs(), GetRange(), rocksdb::Compaction::input_version_, rocksdb::Compaction::inputs_, rocksdb::kCompactionStyleUniversal, rocksdb::FileMetaData::largest, rocksdb::Compaction::MarkFilesBeingCompacted(), MaxFileSizeForLevel(), MaxGrandParentOverlapBytes(), NumberLevels(), options_, rocksdb::Compaction::parent_index_, ParentRangeInCompaction(), PickCompactionBySize(), PickCompactionUniversal(), rocksdb::Version::Ref(), rocksdb::Compaction::SetupBottomMostLevel(), SetupOtherInputs(), SizeBeingCompacted(), rocksdb::FileMetaData::smallest, and rocksdb::Version::vset_.
{
   Compaction* c = nullptr;
   int level = -1;
   // Compute the compactions needed. It is better to do it here
   // and also in LogAndApply(), otherwise the values could be stale.
   std::vector<uint64_t> size_being_compacted(NumberLevels()-1);
   current_->vset_->SizeBeingCompacted(size_being_compacted);
   Finalize(current_, size_being_compacted);
   // In universal style of compaction, compact L0 files back into L0.
   if (options_->compaction_style ==  kCompactionStyleUniversal) {
     int level = 0;
     c = PickCompactionUniversal(level, current_->compaction_score_[level]);
     return c;
   }
   // We prefer compactions triggered by too much data in a level over
   // the compactions triggered by seeks.
   //
   // Find the compactions by size on all levels.
   for (int i = 0; i < NumberLevels()-1; i++) {
     assert(i == 0 || current_->compaction_score_[i] <=
                      current_->compaction_score_[i-1]);
     level = current_->compaction_level_[i];
     if ((current_->compaction_score_[i] >= 1)) {
       c = PickCompactionBySize(level, current_->compaction_score_[i]);
       ExpandWhileOverlapping(c);
       if (c != nullptr) {
         break;
       }
     }
   }
   // Find compactions needed by seeks
   FileMetaData* f = current_->file_to_compact_;
   if (c == nullptr && f != nullptr && !f->being_compacted) {
     level = current_->file_to_compact_level_;
     int parent_index = -1;
     // Only allow one level 0 compaction at a time.
     // Do not pick this file if its parents at level+1 are being compacted.
     if (level != 0 || compactions_in_progress_[0].empty()) {
       if(!ParentRangeInCompaction(&f->smallest, &f->largest, level,
                                   &parent_index)) {
         c = new Compaction(level, level+1, MaxFileSizeForLevel(level+1),
                 MaxGrandParentOverlapBytes(level), NumberLevels(), true);
         c->inputs_[0].push_back(f);
         c->parent_index_ = parent_index;
         current_->file_to_compact_ = nullptr;
         ExpandWhileOverlapping(c);
       }
     }
   }
   if (c == nullptr) {
     return nullptr;
   }
   c->input_version_ = current_;
   c->input_version_->Ref();
   // Two level 0 compaction won't run at the same time, so don't need to worry
   // about files on level 0 being compacted.
   if (level == 0) {
     assert(compactions_in_progress_[0].empty());
     InternalKey smallest, largest;
     GetRange(c->inputs_[0], &smallest, &largest);
     // Note that the next call will discard the file we placed in
     // c->inputs_[0] earlier and replace it with an overlapping set
     // which will include the picked file.
     c->inputs_[0].clear();
     current_->GetOverlappingInputs(0, &smallest, &largest, &c->inputs_[0]);
     // If we include more L0 files in the same compaction run it can
     // cause the 'smallest' and 'largest' key to get extended to a
     // larger range. So, re-invoke GetRange to get the new key range
     GetRange(c->inputs_[0], &smallest, &largest);
     if (ParentRangeInCompaction(&smallest, &largest,
                                 level, &c->parent_index_)) {
       delete c;
       return nullptr;
     }
     assert(!c->inputs_[0].empty());
   }
   // Setup "level+1" files (inputs_[1])
   SetupOtherInputs(c);
   // mark all the files that are being compacted
   c->MarkFilesBeingCompacted(true);
   // Is this compaction creating a file at the bottommost level
   c->SetupBottomMostLevel(false);
   // remember this currently undergoing compaction
   compactions_in_progress_[level].insert(c);
   return c;
 }
Compaction * rocksdb::VersionSet::PickCompactionBySize (int level, double score)
Definition at line 2522 of file version_set.cc.
References rocksdb::Compaction::base_index_, rocksdb::FileMetaData::being_compacted, Compaction, compactions_in_progress_, current_, ripple::f, rocksdb::FileMetaData::file_size, rocksdb::Version::files_, rocksdb::Version::files_by_size_, rocksdb::Compaction::inputs_, rocksdb::FileMetaData::largest, MaxFileSizeForLevel(), MaxGrandParentOverlapBytes(), rocksdb::Version::next_file_to_compact_by_size_, rocksdb::Version::number_of_files_to_sort_, NumberLevels(), rocksdb::Compaction::parent_index_, ParentRangeInCompaction(), beast::hash_metrics::detail::score(), rocksdb::Compaction::score_, and rocksdb::FileMetaData::smallest.
Referenced by PickCompaction().
{
   Compaction* c = nullptr;
   // level 0 files are overlapping. So we cannot pick more
   // than one concurrent compactions at this level. This
   // could be made better by looking at key-ranges that are
   // being compacted at level 0.
   if (level == 0 && compactions_in_progress_[level].size() == 1) {
     return nullptr;
   }
   assert(level >= 0);
   assert(level+1 < NumberLevels());
   c = new Compaction(level, level+1, MaxFileSizeForLevel(level+1),
       MaxGrandParentOverlapBytes(level), NumberLevels());
   c->score_ = score;
   // Pick the largest file in this level that is not already
   // being compacted
   std::vector<int>& file_size = current_->files_by_size_[level];
   // record the first file that is not yet compacted
   int nextIndex = -1;
   for (unsigned int i = current_->next_file_to_compact_by_size_[level];
        i < file_size.size(); i++) {
     int index = file_size[i];
     FileMetaData* f = current_->files_[level][index];
     // check to verify files are arranged in descending size
     assert((i == file_size.size() - 1) ||
            (i >= Version::number_of_files_to_sort_-1) ||
           (f->file_size >= current_->files_[level][file_size[i+1]]->file_size));
     // do not pick a file to compact if it is being compacted
     // from n-1 level.
     if (f->being_compacted) {
       continue;
     }
     // remember the startIndex for the next call to PickCompaction
     if (nextIndex == -1) {
       nextIndex = i;
     }
     //if (i > Version::number_of_files_to_sort_) {
     //  Log(options_->info_log, "XXX Looking at index %d", i);
     //}
     // Do not pick this file if its parents at level+1 are being compacted.
     // Maybe we can avoid redoing this work in SetupOtherInputs
     int parent_index = -1;
     if (ParentRangeInCompaction(&f->smallest, &f->largest, level,
                                 &parent_index)) {
       continue;
     }
     c->inputs_[0].push_back(f);
     c->base_index_ = index;
     c->parent_index_ = parent_index;
     break;
   }
   if (c->inputs_[0].empty()) {
     delete c;
     c = nullptr;
   }
   // store where to start the iteration in the next call to PickCompaction
   current_->next_file_to_compact_by_size_[level] = nextIndex;
   return c;
 }
Compaction * rocksdb::VersionSet::PickCompactionUniversal (int level, double score)
Definition at line 2443 of file version_set.cc.
References rocksdb::Options::compaction_options_universal, compactions_in_progress_, current_, ripple::f, rocksdb::Version::files_, rocksdb::Version::files_by_size_, rocksdb::Options::info_log, rocksdb::FileMetaData::largest_seqno, rocksdb::Options::level0_file_num_compaction_trigger, LevelFileSummary(), rocksdb::Log(), rocksdb::NUM_FILES_IN_SINGLE_COMPACTION, options_, PickCompactionUniversalReadAmp(), PickCompactionUniversalSizeAmp(), rocksdb::Version::Ref(), rocksdb::CompactionOptionsUniversal::size_ratio, rocksdb::FileMetaData::smallest_seqno, and rocksdb::Options::statistics.
Referenced by PickCompaction().
{
   assert (level == 0);
   if ((current_->files_[level].size() <
       (unsigned int)options_->level0_file_num_compaction_trigger)) {
     Log(options_->info_log, "Universal: nothing to do\n");
     return nullptr;
   }
   VersionSet::FileSummaryStorage tmp;
   Log(options_->info_log, "Universal: candidate files(%lu): %s\n",
       current_->files_[level].size(),
       LevelFileSummary(&tmp, 0));
   // Check for size amplification first.
   Compaction* c = PickCompactionUniversalSizeAmp(level, score);
   if (c == nullptr) {
     // Size amplification is within limits. Try reducing read
     // amplification while maintaining file size ratios.
     unsigned int ratio = options_->compaction_options_universal.size_ratio;
     c = PickCompactionUniversalReadAmp(level, score, ratio, UINT_MAX);
     // Size amplification and file size ratios are within configured limits.
     // If max read amplification is exceeding configured limits, then force
     // compaction without looking at filesize ratios and try to reduce
     // the number of files to fewer than level0_file_num_compaction_trigger.
     if (c == nullptr) {
       unsigned int num_files = current_->files_[level].size() -
                                options_->level0_file_num_compaction_trigger;
       c = PickCompactionUniversalReadAmp(level, score, UINT_MAX, num_files);
     }
   }
   if (c == nullptr) {
     return nullptr;
   }
   assert(c->inputs_[0].size() > 1);
   // validate that all the chosen files are non overlapping in time
   FileMetaData* newerfile __attribute__((unused)) = nullptr;
   for (unsigned int i = 0; i < c->inputs_[0].size(); i++) {
     FileMetaData* f = c->inputs_[0][i];
     assert (f->smallest_seqno <= f->largest_seqno);
     assert(newerfile == nullptr ||
            newerfile->smallest_seqno > f->largest_seqno);
     newerfile = f;
   }
   // The files are sorted from newest first to oldest last.
   std::vector<int>& file_by_time = current_->files_by_size_[level];
   // Is the earliest file part of this compaction?
   int last_index = file_by_time[file_by_time.size()-1];
   FileMetaData* last_file = current_->files_[level][last_index];
   if (c->inputs_[0][c->inputs_[0].size()-1] == last_file) {
     c->bottommost_level_ = true;
   }
   // update statistics
   if (options_->statistics != nullptr) {
     options_->statistics->measureTime(NUM_FILES_IN_SINGLE_COMPACTION,
                                       c->inputs_[0].size());
   }
   c->input_version_ = current_;
   c->input_version_->Ref();
   // mark all the files that are being compacted
   c->MarkFilesBeingCompacted(true);
   // remember this currently undergoing compaction
   compactions_in_progress_[level].insert(c);
   // Record whether this compaction includes all sst files.
   // For now, it is only relevant in universal compaction mode.
   c->is_full_compaction_ = (c->inputs_[0].size() == current_->files_[0].size());
   return c;
 }
Compaction * rocksdb::VersionSet::PickCompactionUniversalReadAmp (int level, double score, unsigned int ratio, unsigned int num_files)
Definition at line 2313 of file version_set.cc.
References rocksdb::FileMetaData::being_compacted, Compaction, rocksdb::Options::compaction_options_universal, rocksdb::CompactionOptionsUniversal::compression_size_percent, current_, ripple::f, rocksdb::FileMetaData::file_size, rocksdb::Version::files_, rocksdb::Version::files_by_size_, rocksdb::Options::info_log, rocksdb::Compaction::inputs_, rocksdb::Log(), ripple::max(), rocksdb::CompactionOptionsUniversal::max_merge_width, MaxFileSizeForLevel(), ripple::min(), rocksdb::CompactionOptionsUniversal::min_merge_width, rocksdb::FileMetaData::number, NumberLevels(), options_, beast::hash_metrics::detail::score(), rocksdb::Compaction::score_, and rocksdb::TotalFileSize().
Referenced by PickCompactionUniversal().
{
   unsigned int min_merge_width =
     options_->compaction_options_universal.min_merge_width;
   unsigned int max_merge_width =
     options_->compaction_options_universal.max_merge_width;
   // The files are sorted from newest first to oldest last.
   std::vector<int>& file_by_time = current_->files_by_size_[level];
   FileMetaData* f = nullptr;
   bool done = false;
   int start_index = 0;
   unsigned int candidate_count;
   assert(file_by_time.size() == current_->files_[level].size());
   unsigned int max_files_to_compact = std::min(max_merge_width,
                                        max_number_of_files_to_compact);
   min_merge_width = std::max(min_merge_width, 2U);
   // Considers a candidate file only if it is smaller than the
   // total size accumulated so far.
   for (unsigned int loop = 0; loop < file_by_time.size(); loop++) {
     candidate_count = 0;
     // Skip files that are already being compacted
     for (f = nullptr; loop < file_by_time.size(); loop++) {
       int index = file_by_time[loop];
       f = current_->files_[level][index];
       if (!f->being_compacted) {
         candidate_count = 1;
         break;
       }
       Log(options_->info_log,
           "Universal: file %lu[%d] being compacted, skipping",
           (unsigned long)f->number, loop);
       f = nullptr;
     }
     // This file is not being compacted. Consider it as the
     // first candidate to be compacted.
     uint64_t candidate_size =  f != nullptr? f->file_size : 0;
     if (f != nullptr) {
       Log(options_->info_log, "Universal: Possible candidate file %lu[%d].",
           (unsigned long)f->number, loop);
     }
     // Check if the suceeding files need compaction.
     for (unsigned int i = loop+1;
          candidate_count < max_files_to_compact && i < file_by_time.size();
          i++) {
       int index = file_by_time[i];
       FileMetaData* f = current_->files_[level][index];
       if (f->being_compacted) {
         break;
       }
       // pick files if the total candidate file size (increased by the
       // specified ratio) is still larger than the next candidate file.
       uint64_t sz = (candidate_size * (100L + ratio)) /100;
       if (sz < f->file_size) {
         break;
       }
       candidate_count++;
       candidate_size += f->file_size;
     }
     // Found a series of consecutive files that need compaction.
     if (candidate_count >= (unsigned int)min_merge_width) {
       start_index = loop;
       done = true;
       break;
     } else {
       for (unsigned int i = loop;
            i < loop + candidate_count && i < file_by_time.size(); i++) {
        int index = file_by_time[i];
        FileMetaData* f = current_->files_[level][index];
        Log(options_->info_log,
            "Universal: Skipping file %lu[%d] with size %lu %d\n",
            (unsigned long)f->number,
            i,
            (unsigned long)f->file_size,
            f->being_compacted);
       }
     }
   }
   if (!done || candidate_count <= 1) {
     return nullptr;
   }
   unsigned int first_index_after = start_index + candidate_count;
   // Compression is enabled if files compacted earlier already reached
   // size ratio of compression.
   bool enable_compression = true;
   int ratio_to_compress =
       options_->compaction_options_universal.compression_size_percent;
   if (ratio_to_compress >= 0) {
     uint64_t total_size = TotalFileSize(current_->files_[level]);
     uint64_t older_file_size = 0;
     for (unsigned int i = file_by_time.size() - 1; i >= first_index_after;
         i--) {
       older_file_size += current_->files_[level][file_by_time[i]]->file_size;
       if (older_file_size * 100L >= total_size * (long) ratio_to_compress) {
         enable_compression = false;
         break;
       }
     }
   }
   Compaction* c = new Compaction(level, level, MaxFileSizeForLevel(level),
                                  LLONG_MAX, NumberLevels(), false,
                                  enable_compression);
   c->score_ = score;
   for (unsigned int i = start_index; i < first_index_after; i++) {
     int index = file_by_time[i];
     FileMetaData* f = current_->files_[level][index];
     c->inputs_[0].push_back(f);
     Log(options_->info_log, "Universal: Picking file %lu[%d] with size %lu\n",
         (unsigned long)f->number,
         i,
         (unsigned long)f->file_size);
   }
   return c;
 }
Compaction * rocksdb::VersionSet::PickCompactionUniversalSizeAmp (int level, double score)
Definition at line 2209 of file version_set.cc.
References rocksdb::FileMetaData::being_compacted, Compaction, rocksdb::Options::compaction_options_universal, current_, ripple::f, rocksdb::FileMetaData::file_size, rocksdb::Version::files_, rocksdb::Version::files_by_size_, rocksdb::Options::info_log, rocksdb::Log(), MaxFileSizeForLevel(), rocksdb::FileMetaData::number, NumberLevels(), options_, and beast::hash_metrics::detail::score().
Referenced by PickCompactionUniversal().
{
   assert (level == 0);
   // percentage flexibilty while reducing size amplification
   uint64_t ratio = options_->compaction_options_universal.
                      max_size_amplification_percent;
   // The files are sorted from newest first to oldest last.
   std::vector<int>& file_by_time = current_->files_by_size_[level];
   assert(file_by_time.size() == current_->files_[level].size());
   unsigned int candidate_count = 0;
   uint64_t candidate_size = 0;
   unsigned int start_index = 0;
   FileMetaData* f = nullptr;
   // Skip files that are already being compacted
   for (unsigned int loop = 0; loop < file_by_time.size() - 1; loop++) {
     int index = file_by_time[loop];
     f = current_->files_[level][index];
     if (!f->being_compacted) {
       start_index = loop;         // Consider this as the first candidate.
       break;
     }
     Log(options_->info_log, "Universal: skipping file %lu[%d] compacted %s",
         (unsigned long)f->number,
         loop,
         " cannot be a candidate to reduce size amp.\n");
     f = nullptr;
   }
   if (f == nullptr) {
     return nullptr;             // no candidate files
   }
   Log(options_->info_log, "Universal: First candidate file %lu[%d] %s",
       (unsigned long)f->number,
       start_index,
       " to reduce size amp.\n");
   // keep adding up all the remaining files
   for (unsigned int loop = start_index; loop < file_by_time.size() - 1;
        loop++) {
     int index = file_by_time[loop];
     f = current_->files_[level][index];
     if (f->being_compacted) {
       Log(options_->info_log,
           "Universal: Possible candidate file %lu[%d] %s.",
           (unsigned long)f->number,
           loop,
           " is already being compacted. No size amp reduction possible.\n");
       return nullptr;
     }
     candidate_size += f->file_size;
     candidate_count++;
   }
   if (candidate_count == 0) {
     return nullptr;
   }
   // size of earliest file
   int index = file_by_time[file_by_time.size() - 1];
   uint64_t earliest_file_size = current_->files_[level][index]->file_size;
   // size amplification = percentage of additional size
   if (candidate_size * 100 < ratio * earliest_file_size) {
     Log(options_->info_log,
         "Universal: size amp not needed. newer-files-total-size %lu "
         "earliest-file-size %lu",
         (unsigned long)candidate_size,
         (unsigned long)earliest_file_size);
     return nullptr;
   } else {
     Log(options_->info_log,
         "Universal: size amp needed. newer-files-total-size %lu "
         "earliest-file-size %lu",
         (unsigned long)candidate_size,
         (unsigned long)earliest_file_size);
   }
   assert(start_index >= 0 && start_index < file_by_time.size() - 1);
   // create a compaction request
   // We always compact all the files, so always compress.
   Compaction* c = new Compaction(level, level, MaxFileSizeForLevel(level),
                                  LLONG_MAX, NumberLevels(), false,
                                  true);
   c->score_ = score;
   for (unsigned int loop = start_index; loop < file_by_time.size(); loop++) {
     int index = file_by_time[loop];
     f = current_->files_[level][index];
     c->inputs_[0].push_back(f);
     Log(options_->info_log,
         "Universal: size amp picking file %lu[%d] with size %lu",
         (unsigned long)f->number,
         index,
         (unsigned long)f->file_size);
   }
   return c;
 }
uint64_t rocksdb::VersionSet::PrevLogNumber () const inline
Definition at line 290 of file version_set.h.
References prev_log_number_.
 { return prev_log_number_; }
Status rocksdb::VersionSet::Recover ()
Definition at line 1400 of file version_set.cc.
References AppendVersion(), rocksdb::VersionSet::Builder::Apply(), rocksdb::VersionEdit::comparator_, rocksdb::Status::Corruption(), current(), current_, current_version_number_, rocksdb::CurrentFileName(), dbname_, rocksdb::VersionEdit::DecodeFrom(), env_, Finalize(), rocksdb::Env::GetFileSize(), rocksdb::VersionEdit::has_comparator_, rocksdb::VersionEdit::has_last_sequence_, rocksdb::VersionEdit::has_log_number_, rocksdb::VersionEdit::has_next_file_number_, rocksdb::VersionEdit::has_prev_log_number_, icmp_, rocksdb::Options::info_log, rocksdb::Status::InvalidArgument(), rocksdb::VersionEdit::last_sequence_, last_sequence_, rocksdb::Log(), rocksdb::VersionEdit::log_number_, log_number_, manifest_file_number_, MarkFileNumberUsed(), rocksdb::Comparator::Name(), rocksdb::Env::NewSequentialFile(), rocksdb::VersionEdit::next_file_number_, next_file_number_, NumberLevels(), rocksdb::Version::offset_manifest_file_, rocksdb::Status::ok(), options_, rocksdb::VersionEdit::prev_log_number_, prev_log_number_, rocksdb::ReadFileToString(), rocksdb::log::Reader::ReadRecord(), rocksdb::VersionSet::Builder::SaveTo(), SizeBeingCompacted(), storage_options_, rocksdb::InternalKeyComparator::user_comparator(), and Version.
Referenced by rocksdb::BM_LogAndApply(), rocksdb::ReduceDBLevelsCommand::DoCommand(), and rocksdb::ReduceDBLevelsCommand::GetOldNumOfLevels().
{
   struct LogReporter : public log::Reader::Reporter {
     Status* status;
     virtual void Corruption(size_t bytes, const Status& s) {
       if (this->status->ok()) *this->status = s;
     }
   };
   // Read "CURRENT" file, which contains a pointer to the current manifest file
   std::string current;
   Status s = ReadFileToString(env_, CurrentFileName(dbname_), &current);
   if (!s.ok()) {
     return s;
   }
   if (current.empty() || current[current.size()-1] != '\n') {
     return Status::Corruption("CURRENT file does not end with newline");
   }
   current.resize(current.size() - 1);
   Log(options_->info_log, "Recovering from manifest file:%s\n",
       current.c_str());
   std::string dscname = dbname_ + "/" + current;
   unique_ptr<SequentialFile> file;
   s = env_->NewSequentialFile(dscname, &file, storage_options_);
   if (!s.ok()) {
     return s;
   }
   uint64_t manifest_file_size;
   s = env_->GetFileSize(dscname, &manifest_file_size);
   if (!s.ok()) {
     return s;
   }
   bool have_log_number = false;
   bool have_prev_log_number = false;
   bool have_next_file = false;
   bool have_last_sequence = false;
   uint64_t next_file = 0;
   uint64_t last_sequence = 0;
   uint64_t log_number = 0;
   uint64_t prev_log_number = 0;
   Builder builder(this, current_);
   {
     LogReporter reporter;
     reporter.status = &s;
     log::Reader reader(std::move(file), &reporter, true/*checksum*/,
                        0/*initial_offset*/);
     Slice record;
     std::string scratch;
     while (reader.ReadRecord(&record, &scratch) && s.ok()) {
       VersionEdit edit(NumberLevels());
       s = edit.DecodeFrom(record);
       if (s.ok()) {
         if (edit.has_comparator_ &&
             edit.comparator_ != icmp_.user_comparator()->Name()) {
           s = Status::InvalidArgument(icmp_.user_comparator()->Name(),
                                       "does not match existing comparator " +
                                       edit.comparator_);
         }
       }
       if (s.ok()) {
         builder.Apply(&edit);
       }
       if (edit.has_log_number_) {
         log_number = edit.log_number_;
         have_log_number = true;
       }
       if (edit.has_prev_log_number_) {
         prev_log_number = edit.prev_log_number_;
         have_prev_log_number = true;
       }
       if (edit.has_next_file_number_) {
         next_file = edit.next_file_number_;
         have_next_file = true;
       }
       if (edit.has_last_sequence_) {
         last_sequence = edit.last_sequence_;
         have_last_sequence = true;
       }
     }
   }
   file.reset();
   if (s.ok()) {
     if (!have_next_file) {
       s = Status::Corruption("no meta-nextfile entry in descriptor");
     } else if (!have_log_number) {
       s = Status::Corruption("no meta-lognumber entry in descriptor");
     } else if (!have_last_sequence) {
       s = Status::Corruption("no last-sequence-number entry in descriptor");
     }
     if (!have_prev_log_number) {
       prev_log_number = 0;
     }
     MarkFileNumberUsed(prev_log_number);
     MarkFileNumberUsed(log_number);
   }
   if (s.ok()) {
     Version* v = new Version(this, current_version_number_++);
     builder.SaveTo(v);
     // Install recovered version
     std::vector<uint64_t> size_being_compacted(NumberLevels()-1);
     SizeBeingCompacted(size_being_compacted);
     Finalize(v, size_being_compacted);
     v->offset_manifest_file_ = manifest_file_size;
     AppendVersion(v);
     manifest_file_number_ = next_file;
     next_file_number_ = next_file + 1;
     last_sequence_ = last_sequence;
     log_number_ = log_number;
     prev_log_number_ = prev_log_number;
     Log(options_->info_log, "Recovered from manifest file:%s succeeded,"
         "manifest_file_number is %lu, next_file_number is %lu, "
         "last_sequence is %lu, log_number is %lu,"
         "prev_log_number is %lu\n",
         current.c_str(),
         (unsigned long)manifest_file_number_,
         (unsigned long)next_file_number_,
         (unsigned long)last_sequence_,
         (unsigned long)log_number_,
         (unsigned long)prev_log_number_);
   }
   return s;
 }
Status rocksdb::VersionSet::ReduceNumberOfLevels (int new_levels, port::Mutex * mu)
Definition at line 20 of file version_set_reduce_num_levels.cc.
References compact_pointer_, current_, rocksdb::Version::files_, Init(), rocksdb::Status::InvalidArgument(), level_max_bytes_, LogAndApply(), max_file_size_, num_levels_, NumberLevels(), NumLevelFiles(), and rocksdb::Status::OK().
Referenced by rocksdb::ReduceDBLevelsCommand::DoCommand().
{
   if(new_levels <= 1) {
     return Status::InvalidArgument(
         "Number of levels needs to be bigger than 1");
   }
   Version* current_version = current_;
   int current_levels = NumberLevels();
   if (current_levels <= new_levels) {
     return Status::OK();
   }
   // Make sure there are file only on one level from
   // (new_levels-1) to (current_levels-1)
   int first_nonempty_level = -1;
   int first_nonempty_level_filenum = 0;
   for (int i = new_levels - 1; i < current_levels; i++) {
     int file_num = NumLevelFiles(i);
     if (file_num != 0) {
       if (first_nonempty_level < 0) {
         first_nonempty_level = i;
         first_nonempty_level_filenum = file_num;
       } else {
         char msg[255];
         sprintf(msg, "Found at least two levels containing files: "
             "[%d:%d],[%d:%d].\n",
             first_nonempty_level, first_nonempty_level_filenum, i, file_num);
         return Status::InvalidArgument(msg);
       }
     }
   }
   Status st;
   std::vector<FileMetaData*>*  old_files_list = current_version->files_;
   std::vector<FileMetaData*>* new_files_list =
       new std::vector<FileMetaData*>[new_levels];
   for (int i = 0; i < new_levels - 1; i++) {
     new_files_list[i] = old_files_list[i];
   }
   if (first_nonempty_level > 0) {
     new_files_list[new_levels - 1] = old_files_list[first_nonempty_level];
   }
   delete[] current_version->files_;
   current_version->files_ = new_files_list;
   delete[] compact_pointer_;
   delete[] max_file_size_;
   delete[] level_max_bytes_;
   num_levels_ = new_levels;
   compact_pointer_ = new std::string[new_levels];
   Init(new_levels);
   VersionEdit ve(new_levels);
   st = LogAndApply(&ve , mu, true);
   return st;
 }
void rocksdb::VersionSet::ReleaseCompactionFiles (Compaction * c, Status status)
Definition at line 2175 of file version_set.cc.
References compactions_in_progress_, rocksdb::Compaction::level(), rocksdb::Compaction::MarkFilesBeingCompacted(), rocksdb::Status::ok(), and rocksdb::Compaction::ResetNextCompactionIndex().
{
   c->MarkFilesBeingCompacted(false);
   compactions_in_progress_[c->level()].erase(c);
   if (!status.ok()) {
     c->ResetNextCompactionIndex();
   }
 }
void rocksdb::VersionSet::ReuseFileNumber (uint64_t file_number) inline
Definition at line 261 of file version_set.h.
References next_file_number_.
{
     if (next_file_number_ == file_number + 1) {
       next_file_number_ = file_number;
     }
   }
void rocksdb::VersionSet::SetLastSequence (uint64_t s) inline
Definition at line 277 of file version_set.h.
References last_sequence_.
{
     assert(s >= last_sequence_);
     last_sequence_ = s;
   }
void rocksdb::VersionSet::SetupOtherInputs (Compaction * c) private
Definition at line 2774 of file version_set.cc.
References rocksdb::Compaction::base_index_, compact_pointer_, current_, rocksdb::InternalKey::DebugString(), rocksdb::Compaction::edit_, rocksdb::InternalKey::Encode(), ExpandedCompactionByteSizeLimit(), FilesInCompaction(), rocksdb::Version::GetOverlappingInputs(), GetRange(), GetRange2(), rocksdb::Compaction::grandparents_, rocksdb::Version::HasOverlappingUserKey(), rocksdb::Options::info_log, rocksdb::Compaction::inputs_, rocksdb::Compaction::level(), rocksdb::Log(), NumberLevels(), options_, rocksdb::Compaction::parent_index_, rocksdb::VersionEdit::SetCompactPointer(), rocksdb::Slice::ToString(), and rocksdb::TotalFileSize().
Referenced by CompactRange(), and PickCompaction().
{
   // If inputs are empty, then there is nothing to expand.
   if (c->inputs_[0].empty()) {
     return;
   }
   const int level = c->level();
   InternalKey smallest, largest;
   // Get the range one last time.
   GetRange(c->inputs_[0], &smallest, &largest);
   // Populate the set of next-level files (inputs_[1]) to include in compaction
   current_->GetOverlappingInputs(level+1, &smallest, &largest, &c->inputs_[1],
                                  c->parent_index_, &c->parent_index_);
   // Get entire range covered by compaction
   InternalKey all_start, all_limit;
   GetRange2(c->inputs_[0], c->inputs_[1], &all_start, &all_limit);
   // See if we can further grow the number of inputs in "level" without
   // changing the number of "level+1" files we pick up. We also choose NOT
   // to expand if this would cause "level" to include some entries for some
   // user key, while excluding other entries for the same user key. This
   // can happen when one user key spans multiple files.
   if (!c->inputs_[1].empty()) {
     std::vector<FileMetaData*> expanded0;
     current_->GetOverlappingInputs(level, &all_start, &all_limit, &expanded0,
                                    c->base_index_, nullptr);
     const uint64_t inputs0_size = TotalFileSize(c->inputs_[0]);
     const uint64_t inputs1_size = TotalFileSize(c->inputs_[1]);
     const uint64_t expanded0_size = TotalFileSize(expanded0);
     uint64_t limit = ExpandedCompactionByteSizeLimit(level);
     if (expanded0.size() > c->inputs_[0].size() &&
         inputs1_size + expanded0_size < limit &&
         !FilesInCompaction(expanded0) &&
         !current_->HasOverlappingUserKey(&expanded0, level)) {
       InternalKey new_start, new_limit;
       GetRange(expanded0, &new_start, &new_limit);
       std::vector<FileMetaData*> expanded1;
       current_->GetOverlappingInputs(level+1, &new_start, &new_limit,
                                      &expanded1, c->parent_index_,
                                      &c->parent_index_);
       if (expanded1.size() == c->inputs_[1].size() &&
           !FilesInCompaction(expanded1)) {
         Log(options_->info_log,
             "Expanding@%lu %lu+%lu (%lu+%lu bytes) to %lu+%lu (%lu+%lu bytes)"
             "\n",
             (unsigned long)level,
             (unsigned long)(c->inputs_[0].size()),
             (unsigned long)(c->inputs_[1].size()),
             (unsigned long)inputs0_size,
             (unsigned long)inputs1_size,
             (unsigned long)(expanded0.size()),
             (unsigned long)(expanded1.size()),
             (unsigned long)expanded0_size,
             (unsigned long)inputs1_size);
         smallest = new_start;
         largest = new_limit;
         c->inputs_[0] = expanded0;
         c->inputs_[1] = expanded1;
         GetRange2(c->inputs_[0], c->inputs_[1], &all_start, &all_limit);
       }
     }
   }
   // Compute the set of grandparent files that overlap this compaction
   // (parent == level+1; grandparent == level+2)
   if (level + 2 < NumberLevels()) {
     current_->GetOverlappingInputs(level + 2, &all_start, &all_limit,
                                    &c->grandparents_);
   }
   if (false) {
     Log(options_->info_log, "Compacting %d '%s' .. '%s'",
         level,
         smallest.DebugString().c_str(),
         largest.DebugString().c_str());
   }
   // Update the place where we will do the next compaction for this level.
   // We update this immediately instead of waiting for the VersionEdit
   // to be applied so that if the compaction fails, we will try a different
   // key range next time.
   compact_pointer_[level] = largest.Encode().ToString();
   c->edit_->SetCompactPointer(level, largest);
 }
void rocksdb::VersionSet::SizeBeingCompacted (std::vector< uint64_t > & sizes) private
Definition at line 2185 of file version_set.cc.
References compactions_in_progress_, rocksdb::FileMetaData::file_size, rocksdb::Compaction::input(), rocksdb::Compaction::level(), rocksdb::Compaction::num_input_files(), and NumberLevels().
Referenced by DumpManifest(), LogAndApply(), PickCompaction(), and Recover().
{
   for (int level = 0; level < NumberLevels()-1; level++) {
     uint64_t total = 0;
     for (std::set<Compaction*>::iterator it =
          compactions_in_progress_[level].begin();
          it != compactions_in_progress_[level].end();
          ++it) {
       Compaction* c = (*it);
       assert(c->level() == level);
       for (int i = 0; i < c->num_input_files(0); i++) {
         total += c->input(0,i)->file_size;
       }
     }
     sizes[level] = total;
   }
 }
void rocksdb::VersionSet::UpdateFilesBySize (Version * v)
Definition at line 1776 of file version_set.cc.
References rocksdb::Options::compaction_style, rocksdb::compareSeqnoDescending(), rocksdb::compareSizeDescending(), rocksdb::Version::files_, rocksdb::Version::files_by_size_, rocksdb::kCompactionStyleUniversal, rocksdb::Version::next_file_to_compact_by_size_, rocksdb::Version::number_of_files_to_sort_, NumberLevels(), and options_.
Referenced by LogAndApply().
{
   // No need to sort the highest level because it is never compacted.
   int max_level = (options_->compaction_style == kCompactionStyleUniversal) ?
                   NumberLevels() : NumberLevels() - 1;
   for (int level = 0; level < max_level; level++) {
     const std::vector<FileMetaData*>& files = v->files_[level];
     std::vector<int>& files_by_size = v->files_by_size_[level];
     assert(files_by_size.size() == 0);
     // populate a temp vector for sorting based on size
     std::vector<Fsize> temp(files.size());
     for (unsigned int i = 0; i < files.size(); i++) {
       temp[i].index = i;
       temp[i].file = files[i];
     }
     // sort the top number_of_files_to_sort_ based on file size
     if (options_->compaction_style == kCompactionStyleUniversal) {
       int num = temp.size();
       std::partial_sort(temp.begin(),  temp.begin() + num,
                         temp.end(), compareSeqnoDescending);
     } else {
       int num = Version::number_of_files_to_sort_;
       if (num > (int)temp.size()) {
         num = temp.size();
       }
       std::partial_sort(temp.begin(),  temp.begin() + num,
                         temp.end(), compareSizeDescending);
     }
     assert(temp.size() == files.size());
     // initialize files_by_size_
     for (unsigned int i = 0; i < temp.size(); i++) {
       files_by_size.push_back(temp[i].index);
     }
     v->next_file_to_compact_by_size_[level] = 0;
     assert(v->files_[level].size() == v->files_by_size_[level].size());
   }
 }
bool rocksdb::VersionSet::VerifyCompactionFileConsistency (Compaction * c)
Definition at line 2127 of file version_set.cc.
References current_, ripple::f, rocksdb::Version::files_, rocksdb::Options::info_log, rocksdb::Compaction::input(), rocksdb::Compaction::input_version_, rocksdb::Compaction::level(), rocksdb::Log(), rocksdb::Compaction::num_input_files(), rocksdb::FileMetaData::number, and options_.
{
 #ifndef NDEBUG
   if (c->input_version_ != current_) {
     Log(options_->info_log, "VerifyCompactionFileConsistency version mismatch");
   }
   // verify files in level
   int level = c->level();
   for (int i = 0; i < c->num_input_files(0); i++) {
     uint64_t number = c->input(0,i)->number;
     // look for this file in the current version
     bool found = false;
     for (unsigned int j = 0; j < current_->files_[level].size(); j++) {
       FileMetaData* f = current_->files_[level][j];
       if (f->number == number) {
         found = true;
         break;
       }
     }
     if (!found) {
       return false; // input files non existant in current version
     }
   }
   // verify level+1 files
   level++;
   for (int i = 0; i < c->num_input_files(1); i++) {
     uint64_t number = c->input(1,i)->number;
     // look for this file in the current version
     bool found = false;
     for (unsigned int j = 0; j < current_->files_[level].size(); j++) {
       FileMetaData* f = current_->files_[level][j];
       if (f->number == number) {
         found = true;
         break;
       }
     }
     if (!found) {
       return false; // input files non existant in current version
     }
   }
 #endif
   return true;     // everything good
 }
Status rocksdb::VersionSet::WriteSnapshot (log::Writer * log) private
Definition at line 1819 of file version_set.cc.
References rocksdb::VersionEdit::AddFile(), rocksdb::log::Writer::AddRecord(), compact_pointer_, current_, rocksdb::InternalKey::DecodeFrom(), rocksdb::VersionEdit::EncodeTo(), ripple::f, rocksdb::FileMetaData::file_size, rocksdb::Version::files_, icmp_, rocksdb::FileMetaData::largest, rocksdb::FileMetaData::largest_seqno, rocksdb::Comparator::Name(), rocksdb::FileMetaData::number, NumberLevels(), rocksdb::VersionEdit::SetCompactPointer(), rocksdb::VersionEdit::SetComparatorName(), rocksdb::FileMetaData::smallest, rocksdb::FileMetaData::smallest_seqno, and rocksdb::InternalKeyComparator::user_comparator().
Referenced by LogAndApply().
{
   // TODO: Break up into multiple records to reduce memory usage on recovery?
   // Save metadata
   VersionEdit edit(NumberLevels());
   edit.SetComparatorName(icmp_.user_comparator()->Name());
   // Save compaction pointers
   for (int level = 0; level < NumberLevels(); level++) {
     if (!compact_pointer_[level].empty()) {
       InternalKey key;
       key.DecodeFrom(compact_pointer_[level]);
       edit.SetCompactPointer(level, key);
     }
   }
   // Save files
   for (int level = 0; level < NumberLevels(); level++) {
     const std::vector<FileMetaData*>& files = current_->files_[level];
     for (size_t i = 0; i < files.size(); i++) {
       const FileMetaData* f = files[i];
       edit.AddFile(level, f->number, f->file_size, f->smallest, f->largest,
                    f->smallest_seqno, f->largest_seqno);
     }
   }
   std::string record;
   edit.EncodeTo(&record);
   return log->AddRecord(record);
 }
Friends And Related Function Documentation
friend class Compaction friend
Definition at line 438 of file version_set.h.
Referenced by CompactRange(), PickCompaction(), PickCompactionBySize(), PickCompactionUniversalReadAmp(), and PickCompactionUniversalSizeAmp().
friend class Version friend
Definition at line 441 of file version_set.h.
Referenced by DumpManifest(), LogAndApply(), Recover(), and VersionSet().
Member Data Documentation
std::string* rocksdb::VersionSet::compact_pointer_ private
Definition at line 491 of file version_set.h.
Referenced by rocksdb::VersionSet::Builder::Apply(), ReduceNumberOfLevels(), SetupOtherInputs(), VersionSet(), WriteSnapshot(), and ~VersionSet().
std::vector<std::set<Compaction*> > rocksdb::VersionSet::compactions_in_progress_ private
Definition at line 500 of file version_set.h.
Referenced by PickCompaction(), PickCompactionBySize(), PickCompactionUniversal(), ReleaseCompactionFiles(), and SizeBeingCompacted().
Version* rocksdb::VersionSet::current_ private
Definition at line 487 of file version_set.h.
Referenced by AddLiveFilesCurrentVersion(), AppendVersion(), CompactRange(), current(), DumpManifest(), ExpandWhileOverlapping(), GetLiveFilesMetaData(), GetMetadataForFile(), LevelFileSummary(), LevelSummary(), LogAndApply(), ManifestFileSize(), MaxCompactionScore(), MaxCompactionScoreLevel(), MaxNextLevelOverlappingBytes(), NeedsCompaction(), NeedsSizeCompaction(), NumLevelBytes(), NumLevelFiles(), ParentRangeInCompaction(), PickCompaction(), PickCompactionBySize(), PickCompactionUniversal(), PickCompactionUniversalReadAmp(), PickCompactionUniversalSizeAmp(), Recover(), ReduceNumberOfLevels(), SetupOtherInputs(), VerifyCompactionFileConsistency(), WriteSnapshot(), and ~VersionSet().
uint64_t rocksdb::VersionSet::current_version_number_ private
Definition at line 503 of file version_set.h.
Referenced by LogAndApply(), Recover(), and VersionSet().
const std::string rocksdb::VersionSet::dbname_ private
Definition at line 472 of file version_set.h.
Referenced by LogAndApply(), ManifestContains(), and Recover().
unique_ptr<log::Writer> rocksdb::VersionSet::descriptor_log_ private
Definition at line 485 of file version_set.h.
Referenced by LogAndApply().
Version rocksdb::VersionSet::dummy_versions_ private
Definition at line 486 of file version_set.h.
Referenced by AddLiveFiles(), AppendVersion(), rocksdb::Version::Unref(), and ~VersionSet().
Env* const rocksdb::VersionSet::env_ private
Definition at line 471 of file version_set.h.
Referenced by LogAndApply(), ManifestContains(), and Recover().
const InternalKeyComparator rocksdb::VersionSet::icmp_ private
Definition at line 475 of file version_set.h.
Referenced by ApproximateOffsetOf(), rocksdb::VersionSet::Builder::Builder(), rocksdb::VersionSet::Builder::CheckConsistency(), DumpManifest(), rocksdb::Version::ExtendOverlappingInputs(), rocksdb::Version::Get(), rocksdb::Version::GetOverlappingInputs(), rocksdb::Version::GetOverlappingInputsBinarySearch(), GetRange(), rocksdb::Version::HasOverlappingUserKey(), rocksdb::Compaction::IsBaseLevelForKey(), MakeInputIterator(), rocksdb::VersionSet::Builder::MaybeAddFile(), rocksdb::Version::NewConcatenatingIterator(), rocksdb::Version::OverlapInLevel(), Recover(), rocksdb::VersionSet::Builder::SaveTo(), rocksdb::Compaction::ShouldStopBefore(), and WriteSnapshot().
uint64_t rocksdb::VersionSet::last_observed_manifest_size_ private
Definition at line 510 of file version_set.h.
Referenced by LogAndApply().
uint64_t rocksdb::VersionSet::last_sequence_ private
Definition at line 478 of file version_set.h.
Referenced by DumpManifest(), LastSequence(), LogAndApplyHelper(), Recover(), and SetLastSequence().
uint64_t* rocksdb::VersionSet::level_max_bytes_ private
Definition at line 497 of file version_set.h.
Referenced by Init(), MaxBytesForLevel(), ReduceNumberOfLevels(), and ~VersionSet().
uint64_t rocksdb::VersionSet::log_number_ private
Definition at line 479 of file version_set.h.
Referenced by DumpManifest(), LogAndApply(), LogAndApplyHelper(), LogNumber(), and Recover().
uint64_t rocksdb::VersionSet::manifest_file_number_ private
Definition at line 477 of file version_set.h.
Referenced by DumpManifest(), LogAndApply(), ManifestContains(), ManifestFileNumber(), and Recover().
std::deque<ManifestWriter*> rocksdb::VersionSet::manifest_writers_ private
Definition at line 506 of file version_set.h.
Referenced by LogAndApply().
uint64_t* rocksdb::VersionSet::max_file_size_ private
Definition at line 494 of file version_set.h.
Referenced by Init(), MaxFileSizeForLevel(), ReduceNumberOfLevels(), and ~VersionSet().
uint64_t rocksdb::VersionSet::next_file_number_ private
Definition at line 476 of file version_set.h.
Referenced by DumpManifest(), LogAndApply(), LogAndApplyHelper(), MarkFileNumberUsed(), NewFileNumber(), Recover(), and ReuseFileNumber().
int rocksdb::VersionSet::num_levels_ private
Definition at line 482 of file version_set.h.
Referenced by NumberLevels(), and ReduceNumberOfLevels().
std::vector<FileMetaData*> rocksdb::VersionSet::obsolete_files_ private
Definition at line 512 of file version_set.h.
Referenced by GetObsoleteFiles(), rocksdb::Version::~Version(), and ~VersionSet().
const Options* const rocksdb::VersionSet::options_ private
Definition at line 473 of file version_set.h.
Referenced by CompactRange(), ExpandedCompactionByteSizeLimit(), Finalize(), rocksdb::Version::Get(), Init(), rocksdb::Compaction::IsBaseLevelForKey(), LogAndApply(), MakeInputIterator(), ManifestContains(), MaxGrandParentOverlapBytes(), NeedsSizeCompaction(), PickCompaction(), PickCompactionUniversal(), PickCompactionUniversalReadAmp(), PickCompactionUniversalSizeAmp(), rocksdb::Version::PickLevelForMemTableOutput(), Recover(), rocksdb::Compaction::SetupBottomMostLevel(), SetupOtherInputs(), UpdateFilesBySize(), VerifyCompactionFileConsistency(), and VersionSet().
uint64_t rocksdb::VersionSet::prev_log_number_ private
Definition at line 480 of file version_set.h.
Referenced by DumpManifest(), LogAndApply(), LogAndApplyHelper(), PrevLogNumber(), and Recover().
const EnvOptions& rocksdb::VersionSet::storage_options_ private
Definition at line 515 of file version_set.h.
Referenced by ApproximateOffsetOf(), DumpManifest(), LogAndApply(), MakeInputIterator(), ManifestContains(), and Recover().
const EnvOptions rocksdb::VersionSet::storage_options_compactions_ private
Definition at line 519 of file version_set.h.
Referenced by MakeInputIterator().
TableCache* const rocksdb::VersionSet::table_cache_ private
Definition at line 474 of file version_set.h.
Referenced by rocksdb::Version::AddIterators(), ApproximateOffsetOf(), rocksdb::Version::Get(), MakeInputIterator(), rocksdb::Version::NewConcatenatingIterator(), and rocksdb::Version::PrefixMayMatch().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/db/version_set.h
rippled/src/ripple/rocksdb/rocksdb/db/version_set.cc
rippled/src/ripple/rocksdb/rocksdb/db/version_set_reduce_num_levels.cc