rippled: beast::PropertyStream::Set Class Reference
beast::PropertyStream::Set Class Reference
#include <PropertyStream.h>
Public Member Functions
Set (Set &set)
Set (std::string const &key, Map &map)
Set (std::string const &key, PropertyStream &stream)
~Set ()
PropertyStream & stream ()
PropertyStream const & stream () const
template<typename Value >
void add (Value value) const
Private Attributes
PropertyStream & m_stream
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
Definition at line 244 of file PropertyStream.h.
Constructor & Destructor Documentation
beast::PropertyStream::Set::Set (Set & set) explicit
Definition at line 141 of file PropertyStream.cpp.
References beast::PropertyStream::array_begin(), and m_stream.
     : m_stream (set.m_stream)
 {
     m_stream.array_begin ();
 }
beast::PropertyStream::Set::Set (std::string const & key, Map & map)
Definition at line 147 of file PropertyStream.cpp.
References beast::PropertyStream::array_begin(), and m_stream.
     : m_stream (map.stream())
 {
     m_stream.array_begin (key);
 }
beast::PropertyStream::Set::Set (std::string const & key, PropertyStream & stream)
Definition at line 153 of file PropertyStream.cpp.
References beast::PropertyStream::array_begin(), and m_stream.
     : m_stream (stream)
 {
     m_stream.array_begin (key);
 }
beast::PropertyStream::Set::~Set ()
Definition at line 159 of file PropertyStream.cpp.
 {
     m_stream.array_end ();
 }
Member Function Documentation
template<typename Value > void beast::PropertyStream::Set::add (Value value) const inline
Definition at line 259 of file PropertyStream.h.
Referenced by ripple::Validators::ManagerImp::onWrite().
         { m_stream.add (value); }
PropertyStream & beast::PropertyStream::Set::stream ()
Definition at line 164 of file PropertyStream.cpp.
 {
     return m_stream;
 }
PropertyStream const & beast::PropertyStream::Set::stream () const
Definition at line 169 of file PropertyStream.cpp.
 {
     return m_stream;
 }
Member Data Documentation
PropertyStream& beast::PropertyStream::Set::m_stream private
Definition at line 247 of file PropertyStream.h.
Referenced by Set().
The documentation for this class was generated from the following files:
rippled/src/beast/beast/utility/PropertyStream.h
rippled/src/beast/beast/utility/impl/PropertyStream.cpp