rippled: ripple::uint160 Class Reference
ripple::uint160 Class Reference
#include <UInt160.h>
Public Types
typedef base_uint160 basetype
Public Types inherited from ripple::base_uint< BITS >
typedef std::size_t size_type
typedef std::ptrdiff_t difference_type
typedef unsigned char value_type
typedef value_type * pointer
typedef value_type & reference
typedef value_type const * const_pointer
typedef value_type const & const_reference
typedef pointer iterator
typedef const_pointer const_iterator
typedef std::reverse_iterator
< iterator > reverse_iterator
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator
typedef beast::hardened_hash
< base_uint > hasher
Public Member Functions
uint160 ()
uint160 (const basetype &b)
uint160 & operator= (const basetype &b)
uint160 (std::uint64_t b)
uint160 & operator= (std::uint64_t uHost)
uint160 (const std::string &str)
uint160 (Blob const &vch)
base_uint256 to256 () const
Public Member Functions inherited from ripple::base_uint< BITS >
base_uint ()
pointer data ()
const_pointer data () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
const_iterator cbegin () const
const_iterator cend () const
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
bool isZero () const
bool isNonZero () const
bool operator! () const
const base_uint operator~ () const
base_uint & operator= (std::uint64_t uHost)
base_uint & operator^= (const base_uint &b)
base_uint & operator&= (const base_uint &b)
base_uint & operator|= (const base_uint &b)
base_uint & operator++ ()
const base_uint operator++ (int)
base_uint & operator-- ()
const base_uint operator-- (int)
base_uint & operator+= (const base_uint &b)
std::string GetHex () const
void SetHexExact (const char *psz)
bool SetHex (const char *psz, bool bStrict=false)
bool SetHex (const std::string &str, bool bStrict=false)
void SetHexExact (const std::string &str)
std::string ToString () const
unsigned int size () const
void zero ()
unsigned int GetSerializeSize (int nType=0) const
template<typename Stream >
void Serialize (Stream &s, int nType=0) const
template<typename Stream >
void Unserialize (Stream &s, int nType=0)
Additional Inherited Members
Static Public Attributes inherited from ripple::base_uint< BITS >
static std::size_t const bytes = (BITS/8)
Protected Types inherited from ripple::base_uint< BITS >
enum { WIDTH = BITS / 32 }
Protected Member Functions inherited from ripple::base_uint< BITS >
base_uint (void const *data, FromVoid)
Protected Attributes inherited from ripple::base_uint< BITS >
unsigned int pn [WIDTH]
Detailed Description
Definition at line 33 of file UInt160.h.
Member Typedef Documentation
typedef base_uint160 ripple::uint160::basetype
Definition at line 36 of file UInt160.h.
Constructor & Destructor Documentation
ripple::uint160::uint160 () inline
Definition at line 38 of file UInt160.h.
References ripple::base_uint< BITS >::zero().
     {
         zero ();
     }
ripple::uint160::uint160 (const basetype & b) inline
Definition at line 43 of file UInt160.h.
     {
         *this   = b;
     }
ripple::uint160::uint160 (std::uint64_t b) inline explicit
Definition at line 56 of file UInt160.h.
     {
         *this = b;
     }
ripple::uint160::uint160 (const std::string & str) inline explicit
Definition at line 71 of file UInt160.h.
References ripple::base_uint< BITS >::SetHex().
     {
         SetHex (str);
     }
ripple::uint160::uint160 (Blob const & vch) inline explicit
Definition at line 76 of file UInt160.h.
References ripple::base_uint< BITS >::pn, and ripple::base_uint< BITS >::zero().
     {
         if (vch.size () == sizeof (pn))
             memcpy (pn, &vch[0], sizeof (pn));
         else
             zero ();
     }
Member Function Documentation
uint160& ripple::uint160::operator= (const basetype & b) inline
Definition at line 48 of file UInt160.h.
References ripple::base_uint< BITS >::pn, and ripple::base_uint< BITS >::WIDTH.
     {
         for (int i = 0; i < WIDTH; i++)
             pn[i] = b.pn[i];
         return *this;
     }
uint160& ripple::uint160::operator= (std::uint64_t uHost) inline
Definition at line 61 of file UInt160.h.
References ripple::base_uint< BITS >::end(), and ripple::base_uint< BITS >::zero().
     {
         zero ();
         // Put in least significant bits.
         ((std::uint64_t*) end ())[-1]   = htobe64 (uHost);
         return *this;
     }
base_uint256 ripple::uint160::to256 () const
Definition at line 22 of file UInt160.cpp.
References ripple::base_uint< BITS >::begin(), and ripple::base_uint< BITS >::size().
Referenced by ripple::RadixMap::make_random_item(), and ripple::SHAMapSync_test::makeRandomAS().
 {
     uint256 m;
     memcpy (m.begin (), begin (), size ());
     return m;
 }
The documentation for this class was generated from the following files:
rippled/src/ripple/types/api/UInt160.h
rippled/src/ripple/types/impl/UInt160.cpp