rippled: rocksdb::Harness Class Reference
rocksdb::Harness Class Reference
Public Member Functions
Harness ()
void Init (const TestArgs &args)
~Harness ()
void Add (const std::string &key, const std::string &value)
void Test (Random *rnd)
void TestForwardScan (const std::vector< std::string > &keys, const KVMap &data)
void TestBackwardScan (const std::vector< std::string > &keys, const KVMap &data)
void TestRandomAccess (Random *rnd, const std::vector< std::string > &keys, const KVMap &data)
std::string ToString (const KVMap &data, const KVMap::const_iterator &it)
std::string ToString (const KVMap &data, const KVMap::const_reverse_iterator &it)
std::string ToString (const Iterator *it)
std::string PickRandomKey (Random *rnd, const std::vector< std::string > &keys)
DB * db () const
Private Attributes
Options options_ = Options()
Constructor * constructor_
Detailed Description
Definition at line 535 of file table_test.cc.
Constructor & Destructor Documentation
rocksdb::Harness::Harness () inline
Definition at line 537 of file table_test.cc.
 : constructor_(nullptr) { }
rocksdb::Harness::~Harness () inline
Definition at line 568 of file table_test.cc.
References constructor_.
              {
     delete constructor_;
   }
Member Function Documentation
void rocksdb::Harness::Add (const std::string & key, const std::string & value) inline
Definition at line 572 of file table_test.cc.
References rocksdb::Constructor::Add(), and constructor_.
{
     constructor_->Add(key, value);
   }
DB* rocksdb::Harness::db () const inline
Definition at line 739 of file table_test.cc.
References constructor_, and rocksdb::Constructor::db().
 { return constructor_->db(); }
void rocksdb::Harness::Init (const TestArgs & args) inline
Definition at line 539 of file table_test.cc.
References rocksdb::Options::block_restart_interval, rocksdb::Options::block_size, rocksdb::BLOCK_TEST, rocksdb::Options::comparator, rocksdb::Options::compression, rocksdb::TestArgs::compression, constructor_, rocksdb::DB_TEST, rocksdb::MEMTABLE_TEST, options_, rocksdb::TestArgs::restart_interval, rocksdb::TestArgs::reverse_compare, rocksdb::reverse_key_comparator, rocksdb::TABLE_TEST, and rocksdb::TestArgs::type.
{
     delete constructor_;
     constructor_ = nullptr;
     options_ = Options();
     options_.block_restart_interval = args.restart_interval;
     options_.compression = args.compression;
     // Use shorter block size for tests to exercise block boundary
     // conditions more.
     options_.block_size = 256;
     if (args.reverse_compare) {
       options_.comparator = &reverse_key_comparator;
     }
     switch (args.type) {
       case TABLE_TEST:
         constructor_ = new BlockBasedTableConstructor(options_.comparator);
         break;
       case BLOCK_TEST:
         constructor_ = new BlockConstructor(options_.comparator);
         break;
       case MEMTABLE_TEST:
         constructor_ = new MemTableConstructor(options_.comparator);
         break;
       case DB_TEST:
         constructor_ = new DBConstructor(options_.comparator);
         break;
     }
   }
std::string rocksdb::Harness::PickRandomKey (Random * rnd, const std::vector< std::string > & keys) inline
Definition at line 711 of file table_test.cc.
References rocksdb::Options::comparator, rocksdb::Increment(), options_, and rocksdb::Random::Uniform().
Referenced by TestRandomAccess().
{
     if (keys.empty()) {
       return "foo";
     } else {
       const int index = rnd->Uniform(keys.size());
       std::string result = keys[index];
       switch (rnd->Uniform(3)) {
         case 0:
           // Return an existing key
           break;
         case 1: {
           // Attempt to return something smaller than an existing key
           if (result.size() > 0 && result[result.size()-1] > '\0') {
             result[result.size()-1]--;
           }
           break;
         }
         case 2: {
           // Return something larger than an existing key
           Increment(options_.comparator, &result);
           break;
         }
       }
       return result;
     }
   }
void rocksdb::Harness::Test (Random * rnd) inline
Definition at line 576 of file table_test.cc.
References constructor_, rocksdb::Constructor::Finish(), options_, TestBackwardScan(), TestForwardScan(), and TestRandomAccess().
{
     std::vector<std::string> keys;
     KVMap data;
     constructor_->Finish(options_, &keys, &data);
     TestForwardScan(keys, data);
     TestBackwardScan(keys, data);
     TestRandomAccess(rnd, keys, data);
   }
void rocksdb::Harness::TestBackwardScan (const std::vector< std::string > & keys, const KVMap & data) inline
Definition at line 601 of file table_test.cc.
References ASSERT_EQ, ASSERT_TRUE, constructor_, rocksdb::Constructor::NewIterator(), rocksdb::Iterator::Prev(), rocksdb::Iterator::SeekToLast(), ToString(), and rocksdb::Iterator::Valid().
Referenced by Test().
{
     Iterator* iter = constructor_->NewIterator();
     ASSERT_TRUE(!iter->Valid());
     iter->SeekToLast();
     for (KVMap::const_reverse_iterator model_iter = data.rbegin();
          model_iter != data.rend();
          ++model_iter) {
       ASSERT_EQ(ToString(data, model_iter), ToString(iter));
       iter->Prev();
     }
     ASSERT_TRUE(!iter->Valid());
     delete iter;
   }
void rocksdb::Harness::TestForwardScan (const std::vector< std::string > & keys, const KVMap & data) inline
Definition at line 586 of file table_test.cc.
References ASSERT_EQ, ASSERT_TRUE, constructor_, rocksdb::Constructor::NewIterator(), rocksdb::Iterator::Next(), rocksdb::Iterator::SeekToFirst(), ToString(), and rocksdb::Iterator::Valid().
Referenced by Test().
{
     Iterator* iter = constructor_->NewIterator();
     ASSERT_TRUE(!iter->Valid());
     iter->SeekToFirst();
     for (KVMap::const_iterator model_iter = data.begin();
          model_iter != data.end();
          ++model_iter) {
       ASSERT_EQ(ToString(data, model_iter), ToString(iter));
       iter->Next();
     }
     ASSERT_TRUE(!iter->Valid());
     delete iter;
   }
void rocksdb::Harness::TestRandomAccess (Random * rnd, const std::vector< std::string > & keys, const KVMap & data) inline
Definition at line 616 of file table_test.cc.
References ASSERT_EQ, ASSERT_TRUE, constructor_, rocksdb::EscapeString(), rocksdb::kVerbose, rocksdb::Constructor::NewIterator(), rocksdb::Iterator::Next(), PickRandomKey(), rocksdb::Iterator::Prev(), rocksdb::Iterator::Seek(), rocksdb::Iterator::SeekToFirst(), rocksdb::Iterator::SeekToLast(), ToString(), rocksdb::Random::Uniform(), and rocksdb::Iterator::Valid().
Referenced by Test().
{
     static const bool kVerbose = false;
     Iterator* iter = constructor_->NewIterator();
     ASSERT_TRUE(!iter->Valid());
     KVMap::const_iterator model_iter = data.begin();
     if (kVerbose) fprintf(stderr, "---\n");
     for (int i = 0; i < 200; i++) {
       const int toss = rnd->Uniform(5);
       switch (toss) {
         case 0: {
           if (iter->Valid()) {
             if (kVerbose) fprintf(stderr, "Next\n");
             iter->Next();
             ++model_iter;
             ASSERT_EQ(ToString(data, model_iter), ToString(iter));
           }
           break;
         }
         case 1: {
           if (kVerbose) fprintf(stderr, "SeekToFirst\n");
           iter->SeekToFirst();
           model_iter = data.begin();
           ASSERT_EQ(ToString(data, model_iter), ToString(iter));
           break;
         }
         case 2: {
           std::string key = PickRandomKey(rnd, keys);
           model_iter = data.lower_bound(key);
           if (kVerbose) fprintf(stderr, "Seek '%s'\n",
                                 EscapeString(key).c_str());
           iter->Seek(Slice(key));
           ASSERT_EQ(ToString(data, model_iter), ToString(iter));
           break;
         }
         case 3: {
           if (iter->Valid()) {
             if (kVerbose) fprintf(stderr, "Prev\n");
             iter->Prev();
             if (model_iter == data.begin()) {
               model_iter = data.end();   // Wrap around to invalid value
             } else {
               --model_iter;
             }
             ASSERT_EQ(ToString(data, model_iter), ToString(iter));
           }
           break;
         }
         case 4: {
           if (kVerbose) fprintf(stderr, "SeekToLast\n");
           iter->SeekToLast();
           if (keys.empty()) {
             model_iter = data.end();
           } else {
             std::string last = data.rbegin()->first;
             model_iter = data.lower_bound(last);
           }
           ASSERT_EQ(ToString(data, model_iter), ToString(iter));
           break;
         }
       }
     }
     delete iter;
   }
std::string rocksdb::Harness::ToString (const KVMap & data, const KVMap::const_iterator & it) inline
Definition at line 686 of file table_test.cc.
Referenced by TestBackwardScan(), TestForwardScan(), and TestRandomAccess().
{
     if (it == data.end()) {
       return "END";
     } else {
       return "'" + it->first + "->" + it->second + "'";
     }
   }
std::string rocksdb::Harness::ToString (const KVMap & data, const KVMap::const_reverse_iterator & it) inline
Definition at line 694 of file table_test.cc.
{
     if (it == data.rend()) {
       return "END";
     } else {
       return "'" + it->first + "->" + it->second + "'";
     }
   }
std::string rocksdb::Harness::ToString (const Iterator * it) inline
Definition at line 703 of file table_test.cc.
References rocksdb::Iterator::key(), rocksdb::Slice::ToString(), rocksdb::Iterator::Valid(), and rocksdb::Iterator::value().
{
     if (!it->Valid()) {
       return "END";
     } else {
       return "'" + it->key().ToString() + "->" + it->value().ToString() + "'";
     }
   }
Member Data Documentation
Constructor* rocksdb::Harness::constructor_ private
Definition at line 743 of file table_test.cc.
Referenced by Add(), db(), Init(), Test(), TestBackwardScan(), TestForwardScan(), TestRandomAccess(), and ~Harness().
Options rocksdb::Harness::options_ = Options() private
Definition at line 742 of file table_test.cc.
Referenced by Init(), PickRandomKey(), and Test().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/table/table_test.cc