rippled: rocksdb::WriteBatch::Handler Class Reference
rocksdb::WriteBatch::Handler Class Reference abstract
#include <write_batch.h>
Public Member Functions
virtual ~Handler ()
virtual void Put (const Slice &key, const Slice &value)=0
virtual void Merge (const Slice &key, const Slice &value)
virtual void LogData (const Slice &blob)
virtual void Delete (const Slice &key)=0
virtual bool Continue ()
Detailed Description
Definition at line 72 of file write_batch.h.
Constructor & Destructor Documentation
rocksdb::WriteBatch::Handler::~Handler () virtual
Definition at line 45 of file write_batch.cc.
 { }
Member Function Documentation
bool rocksdb::WriteBatch::Handler::Continue () virtual
Definition at line 56 of file write_batch.cc.
Referenced by rocksdb::WriteBatch::Iterate().
{
   return true;
 }
virtual void rocksdb::WriteBatch::Handler::Delete (const Slice & key) pure virtual
Implemented in rocksdb::InMemoryHandler.
Referenced by rocksdb::WriteBatch::Iterate().
void rocksdb::WriteBatch::Handler::LogData (const Slice & blob) virtual
Definition at line 51 of file write_batch.cc.
Referenced by rocksdb::WriteBatch::Iterate().
{
   // If the user has not specified something to do with blobs, then we ignore
   // them.
 }
void rocksdb::WriteBatch::Handler::Merge (const Slice & key, const Slice & value) virtual
Definition at line 47 of file write_batch.cc.
Referenced by rocksdb::WriteBatch::Iterate().
{
   throw std::runtime_error("Handler::Merge not implemented!");
 }
virtual void rocksdb::WriteBatch::Handler::Put (const Slice & key, const Slice & value) pure virtual
Implemented in rocksdb::InMemoryHandler.
Referenced by rocksdb::WriteBatch::Iterate().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/include/rocksdb/write_batch.h
rippled/src/ripple/rocksdb/rocksdb/db/write_batch.cc