rippled: ripple::STUInt32 Class Reference
ripple::STUInt32 Class Reference
#include <SerializedTypes.h>
Public Member Functions
STUInt32 (std::uint32_t v=0)
STUInt32 (SField::ref n, std::uint32_t v=0)
SerializedTypeID getSType () const
std::string getText () const
Json::Value getJson (int) const
void add (Serializer &s) const
std::uint32_t getValue () const
void setValue (std::uint32_t v)
operator std::uint32_t () const
virtual bool isEquivalent (const SerializedType &t) const
virtual bool isDefault () const
Public Member Functions inherited from ripple::SerializedType
SerializedType ()
SerializedType (SField::ref n)
virtual ~SerializedType ()
void setFName (SField::ref n)
SField::ref getFName () const
std::string getName () const
std::unique_ptr< SerializedType > clone () const
virtual std::string getFullText () const
void addFieldID (Serializer &s) const
SerializedType & operator= (const SerializedType &t)
bool operator== (const SerializedType &t) const
bool operator!= (const SerializedType &t) const
template<class D >
D & downcast ()
template<class D >
D const & downcast () const
Static Public Member Functions
static std::unique_ptr
< SerializedType > deserialize (SerializerIterator &sit, SField::ref name)
Static Public Member Functions inherited from ripple::SerializedType
static std::unique_ptr
< SerializedType > deserialize (SField::ref name)
Private Member Functions
STUInt32 * duplicate () const
Static Private Member Functions
static STUInt32 * construct (SerializerIterator &, SField::ref name)
Private Attributes
std::uint32_t value
Additional Inherited Members
Protected Attributes inherited from ripple::SerializedType
SField::ptr fName
Detailed Description
Definition at line 339 of file SerializedTypes.h.
Constructor & Destructor Documentation
ripple::STUInt32::STUInt32 (std::uint32_t v = 0) inline
Definition at line 343 of file SerializedTypes.h.
Referenced by construct(), and duplicate().
                                  : value (v)
     {
         ;
     }
ripple::STUInt32::STUInt32 (SField::ref n, std::uint32_t v = 0) inline
Definition at line 347 of file SerializedTypes.h.
                                               : SerializedType (n), value (v)
     {
         ;
     }
Member Function Documentation
void ripple::STUInt32::add (Serializer & s) const inline virtual
Reimplemented from ripple::SerializedType.
Definition at line 362 of file SerializedTypes.h.
References ripple::Serializer::add32(), and value.
     {
         s.add32 (value);
     }
STUInt32 * ripple::STUInt32::construct (SerializerIterator & u, SField::ref name) static private
Definition at line 197 of file SerializedTypes.cpp.
References ripple::SerializerIterator::get32(), and STUInt32().
Referenced by deserialize().
 {
     return new STUInt32 (name, u.get32 ());
 }
static std::unique_ptr<SerializedType> ripple::STUInt32::deserialize (SerializerIterator & sit, SField::ref name) inline static
Definition at line 351 of file SerializedTypes.h.
References construct().
Referenced by ripple::STObject::makeDeserializedObject().
     {
         return std::unique_ptr<SerializedType> (construct (sit, name));
     }
STUInt32* ripple::STUInt32::duplicate () const inline private virtual
Reimplemented from ripple::SerializedType.
Definition at line 389 of file SerializedTypes.h.
References STUInt32().
     {
         return new STUInt32 (*this);
     }
Json::Value ripple::STUInt32::getJson (int) const virtual
Reimplemented from ripple::SerializedType.
Definition at line 207 of file SerializedTypes.cpp.
References value.
 {
     return value;
 }
SerializedTypeID ripple::STUInt32::getSType () const inline virtual
Reimplemented from ripple::SerializedType.
Definition at line 356 of file SerializedTypes.h.
     {
         return STI_UINT32;
     }
std::string ripple::STUInt32::getText () const virtual
Reimplemented from ripple::SerializedType.
Definition at line 202 of file SerializedTypes.cpp.
References value.
 {
     return beast::lexicalCastThrow <std::string> (value);
 }
std::uint32_t ripple::STUInt32::getValue () const inline
Definition at line 367 of file SerializedTypes.h.
References value.
Referenced by ripple::STObject::clearFlag(), ripple::STObject::getFieldU32(), ripple::STObject::getFlags(), and ripple::STObject::setFlag().
     {
         return value;
     }
virtual bool ripple::STUInt32::isDefault () const inline virtual
Reimplemented from ripple::SerializedType.
Definition at line 381 of file SerializedTypes.h.
References value.
     {
         return value == 0;
     }
bool ripple::STUInt32::isEquivalent (const SerializedType & t) const virtual
Reimplemented from ripple::SerializedType.
Definition at line 212 of file SerializedTypes.cpp.
References value.
 {
     const STUInt32* v = dynamic_cast<const STUInt32*> (&t);
     return v && (value == v->value);
 }
ripple::STUInt32::operator std::uint32_t () const inline
Definition at line 376 of file SerializedTypes.h.
References value.
     {
         return value;
     }
void ripple::STUInt32::setValue (std::uint32_t v) inline
Definition at line 371 of file SerializedTypes.h.
References value.
Referenced by ripple::STObject::clearFlag(), ripple::STObject::setFieldU32(), and ripple::STObject::setFlag().
     {
         value = v;
     }
Member Data Documentation
std::uint32_t ripple::STUInt32::value private
Definition at line 387 of file SerializedTypes.h.
Referenced by add(), getJson(), getText(), getValue(), isDefault(), isEquivalent(), operator std::uint32_t(), and setValue().
The documentation for this class was generated from the following files:
rippled/src/ripple_data/protocol/SerializedTypes.h
rippled/src/ripple_data/protocol/SerializedTypes.cpp