rippled: Json::StyledStreamWriter Class Reference
Json::StyledStreamWriter Class Reference
Writes a Value in JSON format in a human friendly way, to a stream rather than to a string.
#include <json_writer.h>
Public Member Functions
StyledStreamWriter (std::string indentation="\t")
~StyledStreamWriter ()
void write (std::ostream &out, const Value &root)
Serialize a Value in JSON format.
Private Types
typedef std::vector< std::string > ChildValues
Private Member Functions
void writeValue (const Value &value)
void writeArrayValue (const Value &value)
bool isMultineArray (const Value &value)
void pushValue (const std::string &value)
void writeIndent ()
void writeWithIndent (const std::string &value)
void indent ()
void unindent ()
void writeCommentBeforeValue (const Value &root)
void writeCommentAfterValueOnSameLine (const Value &root)
bool hasCommentForValue (const Value &value)
Static Private Member Functions
static std::string normalizeEOL (const std::string &text)
Private Attributes
ChildValues childValues_
std::ostream * document_
std::string indentString_
int rightMargin_
std::string indentation_
bool addChildValues_
Detailed Description
Writes a Value in JSON format in a human friendly way, to a stream rather than to a string.
The rules for line break and indent are as follow:
Object value:
if empty then print {} without indent and line break
if not empty the print '{', line break & indent, print one value per line and then unindent and line break and print '}'.
Array value:
if empty then print [] without indent and line break
if the array contains no object value, empty array or some other value types, and all the values fit on one lines, then print the array on a single line.
otherwise, it the values do not fit on one line, or the array contains object or non empty array, then print one value per line.
If the Value have comments then they are outputed according to their CommentPlacement.
Parameters
indentation Each level will be indented by this amount extra.
See Also
Reader, Value, Value::setComment()
Definition at line 137 of file json_writer.h.
Member Typedef Documentation
typedef std::vector<std::string> Json::StyledStreamWriter::ChildValues private
Definition at line 165 of file json_writer.h.
Constructor & Destructor Documentation
Json::StyledStreamWriter::StyledStreamWriter (std::string indentation = "\t")
Definition at line 593 of file json_writer.cpp.
     : document_ (nullptr)
     , rightMargin_ ( 74 )
     , indentation_ ( indentation )
 {
 }
Json::StyledStreamWriter::~StyledStreamWriter () inline
Definition at line 141 of file json_writer.h.
 {}
Member Function Documentation
bool Json::StyledStreamWriter::hasCommentForValue (const Value & value) private
Definition at line 866 of file json_writer.cpp.
References Json::commentAfter, Json::commentAfterOnSameLine, Json::commentBefore, and Json::Value::hasComment().
Referenced by isMultineArray().
 {
     return value.hasComment ( commentBefore )
            ||  value.hasComment ( commentAfterOnSameLine )
            ||  value.hasComment ( commentAfter );
 }
void Json::StyledStreamWriter::indent () private
Definition at line 825 of file json_writer.cpp.
References indentation_, and indentString_.
Referenced by writeArrayValue(), and writeValue().
 {
     indentString_ += indentation_;
 }
bool Json::StyledStreamWriter::isMultineArray (const Value & value) private
Definition at line 752 of file json_writer.cpp.
References addChildValues_, childValues_, hasCommentForValue(), Json::Value::isArray(), Json::Value::isObject(), rightMargin_, Json::Value::size(), and writeValue().
Referenced by writeArrayValue().
 {
     int size = value.size ();
     bool isMultiLine = size * 3 >= rightMargin_ ;
     childValues_.clear ();
     for ( int index = 0; index < size  &&  !isMultiLine; ++index )
     {
         const Value& childValue = value[index];
         isMultiLine = isMultiLine  ||
                       ( (childValue.isArray ()  ||  childValue.isObject ())  &&
                         childValue.size () > 0 );
     }
     if ( !isMultiLine ) // check if line length > max line length
     {
         childValues_.reserve ( size );
         addChildValues_ = true;
         int lineLength = 4 + (size - 1) * 2; // '[ ' + ', '*n + ' ]'
         for ( int index = 0; index < size  &&  !isMultiLine; ++index )
         {
             writeValue ( value[index] );
             lineLength += int ( childValues_[index].length () );
             isMultiLine = isMultiLine  &&  hasCommentForValue ( value[index] );
         }
         addChildValues_ = false;
         isMultiLine = isMultiLine  ||  lineLength >= rightMargin_;
     }
     return isMultiLine;
 }
std::string Json::StyledStreamWriter::normalizeEOL (const std::string & text) static private
Definition at line 875 of file json_writer.cpp.
Referenced by writeCommentAfterValueOnSameLine(), and writeCommentBeforeValue().
 {
     std::string normalized;
     normalized.reserve ( text.length () );
     const char* begin = text.c_str ();
     const char* end = begin + text.length ();
     const char* current = begin;
     while ( current != end )
     {
         char c = *current++;
         if ( c == '\r' ) // mac or dos EOL
         {
             if ( *current == '\n' ) // convert dos EOL
                 ++current;
             normalized += '\n';
         }
         else // handle unix EOL & other char
             normalized += c;
     }
     return normalized;
 }
void Json::StyledStreamWriter::pushValue (const std::string & value) private
Definition at line 788 of file json_writer.cpp.
References addChildValues_, childValues_, document_, and value.
Referenced by writeArrayValue(), and writeValue().
 {
     if ( addChildValues_ )
         childValues_.push_back ( value );
     else
         *document_ << value;
 }
void Json::StyledStreamWriter::unindent () private
Definition at line 832 of file json_writer.cpp.
References indentation_, and indentString_.
Referenced by writeArrayValue(), and writeValue().
 {
     assert ( indentString_.size () >= indentation_.size () );
     indentString_.resize ( indentString_.size () - indentation_.size () );
 }
void Json::StyledStreamWriter::write (std::ostream & out, const Value & root)
Serialize a Value in JSON format.
Parameters
out Stream to write to. (Can be ostringstream, e.g.)
root Value to serialize.
Note
There is no point in deriving from Writer, since write() should not return a value.
Definition at line 602 of file json_writer.cpp.
References addChildValues_, document_, indentString_, writeCommentAfterValueOnSameLine(), writeCommentBeforeValue(), and writeValue().
Referenced by Json::operator<<().
 {
     document_ = &out;
     addChildValues_ = false;
     indentString_ = "";
     writeCommentBeforeValue ( root );
     writeValue ( root );
     writeCommentAfterValueOnSameLine ( root );
     *document_ << "\n";
     document_ = nullptr; // Forget the stream, for safety.
 }
void Json::StyledStreamWriter::writeArrayValue (const Value & value) private
Definition at line 689 of file json_writer.cpp.
References childValues_, document_, indent(), isMultineArray(), pushValue(), Json::Value::size(), unindent(), writeCommentAfterValueOnSameLine(), writeCommentBeforeValue(), writeIndent(), writeValue(), and writeWithIndent().
Referenced by writeValue().
 {
     unsigned size = value.size ();
     if ( size == 0 )
         pushValue ( "[]" );
     else
     {
         bool isArrayMultiLine = isMultineArray ( value );
         if ( isArrayMultiLine )
         {
             writeWithIndent ( "[" );
             indent ();
             bool hasChildValue = !childValues_.empty ();
             unsigned index = 0;
             while ( true )
             {
                 const Value& childValue = value[index];
                 writeCommentBeforeValue ( childValue );
                 if ( hasChildValue )
                     writeWithIndent ( childValues_[index] );
                 else
                 {
                     writeIndent ();
                     writeValue ( childValue );
                 }
                 if ( ++index == size )
                 {
                     writeCommentAfterValueOnSameLine ( childValue );
                     break;
                 }
                 *document_ << ",";
                 writeCommentAfterValueOnSameLine ( childValue );
             }
             unindent ();
             writeWithIndent ( "]" );
         }
         else // output on a single line
         {
             assert ( childValues_.size () == size );
             *document_ << "[ ";
             for ( unsigned index = 0; index < size; ++index )
             {
                 if ( index > 0 )
                     *document_ << ", ";
                 *document_ << childValues_[index];
             }
             *document_ << " ]";
         }
     }
 }
void Json::StyledStreamWriter::writeCommentAfterValueOnSameLine (const Value & root) private
Definition at line 851 of file json_writer.cpp.
References Json::commentAfter, Json::commentAfterOnSameLine, document_, Json::Value::getComment(), Json::Value::hasComment(), and normalizeEOL().
Referenced by write(), writeArrayValue(), and writeValue().
 {
     if ( root.hasComment ( commentAfterOnSameLine ) )
         *document_ << " " + normalizeEOL ( root.getComment ( commentAfterOnSameLine ) );
     if ( root.hasComment ( commentAfter ) )
     {
         *document_ << "\n";
         *document_ << normalizeEOL ( root.getComment ( commentAfter ) );
         *document_ << "\n";
     }
 }
void Json::StyledStreamWriter::writeCommentBeforeValue (const Value & root) private
Definition at line 840 of file json_writer.cpp.
References Json::commentBefore, document_, Json::Value::getComment(), Json::Value::hasComment(), and normalizeEOL().
Referenced by write(), writeArrayValue(), and writeValue().
 {
     if ( !root.hasComment ( commentBefore ) )
         return;
     *document_ << normalizeEOL ( root.getComment ( commentBefore ) );
     *document_ << "\n";
 }
void Json::StyledStreamWriter::writeIndent () private
Definition at line 798 of file json_writer.cpp.
References document_, and indentString_.
Referenced by writeArrayValue(), and writeWithIndent().
 {
     /*
       Some comments in this method would have been nice. ;-)
      if ( !document_.empty() )
      {
         char last = document_[document_.length()-1];
         if ( last == ' ' )     // already indented
            return;
         if ( last != '\n' )    // Comments may add new-line
            *document_ << '\n';
      }
     */
     *document_ << '\n' << indentString_;
 }
void Json::StyledStreamWriter::writeValue (const Value & value) private
Definition at line 616 of file json_writer.cpp.
References Json::arrayValue, Json::Value::asBool(), Json::Value::asCString(), Json::Value::asDouble(), Json::Value::asInt(), Json::Value::asUInt(), Json::booleanValue, document_, Json::Value::getMemberNames(), indent(), Json::intValue, name, Json::nullValue, Json::objectValue, pushValue(), Json::realValue, Json::stringValue, Json::Value::type(), Json::uintValue, unindent(), Json::valueToQuotedString(), Json::valueToString(), writeArrayValue(), writeCommentAfterValueOnSameLine(), writeCommentBeforeValue(), and writeWithIndent().
Referenced by isMultineArray(), write(), and writeArrayValue().
 {
     switch ( value.type () )
     {
     case nullValue:
         pushValue ( "null" );
         break;
     case intValue:
         pushValue ( valueToString ( value.asInt () ) );
         break;
     case uintValue:
         pushValue ( valueToString ( value.asUInt () ) );
         break;
     case realValue:
         pushValue ( valueToString ( value.asDouble () ) );
         break;
     case stringValue:
         pushValue ( valueToQuotedString ( value.asCString () ) );
         break;
     case booleanValue:
         pushValue ( valueToString ( value.asBool () ) );
         break;
     case arrayValue:
         writeArrayValue ( value);
         break;
     case objectValue:
     {
         Value::Members members ( value.getMemberNames () );
         if ( members.empty () )
             pushValue ( "{}" );
         else
         {
             writeWithIndent ( "{" );
             indent ();
             Value::Members::iterator it = members.begin ();
             while ( true )
             {
                 const std::string& name = *it;
                 const Value& childValue = value[name];
                 writeCommentBeforeValue ( childValue );
                 writeWithIndent ( valueToQuotedString ( name.c_str () ) );
                 *document_ << " : ";
                 writeValue ( childValue );
                 if ( ++it == members.end () )
                 {
                     writeCommentAfterValueOnSameLine ( childValue );
                     break;
                 }
                 *document_ << ",";
                 writeCommentAfterValueOnSameLine ( childValue );
             }
             unindent ();
             writeWithIndent ( "}" );
         }
     }
     break;
     }
 }
void Json::StyledStreamWriter::writeWithIndent (const std::string & value) private
Definition at line 817 of file json_writer.cpp.
References document_, value, and writeIndent().
Referenced by writeArrayValue(), and writeValue().
 {
     writeIndent ();
     *document_ << value;
 }
Member Data Documentation
bool Json::StyledStreamWriter::addChildValues_ private
Definition at line 172 of file json_writer.h.
Referenced by isMultineArray(), pushValue(), and write().
ChildValues Json::StyledStreamWriter::childValues_ private
Definition at line 167 of file json_writer.h.
Referenced by isMultineArray(), pushValue(), and writeArrayValue().
std::ostream* Json::StyledStreamWriter::document_ private
Definition at line 168 of file json_writer.h.
Referenced by pushValue(), write(), writeArrayValue(), writeCommentAfterValueOnSameLine(), writeCommentBeforeValue(), writeIndent(), writeValue(), and writeWithIndent().
std::string Json::StyledStreamWriter::indentation_ private
Definition at line 171 of file json_writer.h.
Referenced by indent(), and unindent().
std::string Json::StyledStreamWriter::indentString_ private
Definition at line 169 of file json_writer.h.
Referenced by indent(), unindent(), write(), and writeIndent().
int Json::StyledStreamWriter::rightMargin_ private
Definition at line 170 of file json_writer.h.
Referenced by isMultineArray().
The documentation for this class was generated from the following files:
rippled/src/ripple/json/api/json_writer.h
rippled/src/ripple/json/impl/json_writer.cpp