rippled: beast::FileHelpers Namespace Reference
beast::FileHelpers Namespace Reference
Functions
static bool isFileOnDriveType (const File &f, const char *const *types)
static bool isHiddenFile (const String &path)
static bool launchExecutable (const String &pathAndArguments)
Function Documentation
static bool beast::FileHelpers::isFileOnDriveType (const File & f, const char *const * types) static
Definition at line 61 of file mac_Files.mm.
References beast::String::equalsIgnoreCase().
     {
         struct statfs buf;
         if (beast_doStatFS (f, buf))
         {
             const String type (buf.f_fstypename);
             while (*types != 0)
                 if (type.equalsIgnoreCase (*types++))
                     return true;
         }
         return false;
     }
static bool beast::FileHelpers::isHiddenFile (const String & path) static
Definition at line 77 of file mac_Files.mm.
References BEAST_AUTORELEASEPOOL, beast::File::getFileName(), beast::String::startsWithChar(), and beast::String::toRawUTF8().
     {
        #if defined (MAC_OS_X_VERSION_10_6) && MAC_OS_X_VERSION_MIN_REQUIRED >= MAC_OS_X_VERSION_10_6
         BEAST_AUTORELEASEPOOL
         {
             NSNumber* hidden = nil;
             NSError* err = nil;
             return [[NSURL fileURLWithPath: beastStringToNS (path)]
                         getResourceValue: &hidden forKey: NSURLIsHiddenKey error: &err]
                     && [hidden boolValue];
         }
        #elif BEAST_IOS
         return File (path).getFileName().startsWithChar ('.');
        #else
         FSRef ref;
         LSItemInfoRecord info;
         return FSPathMakeRefWithOptions ((const UInt8*) path.toRawUTF8(), kFSPathMakeRefDoNotFollowLeafSymlink, &ref, 0) == noErr
                  && LSCopyItemInfoForRef (&ref, kLSRequestBasicFlagsOnly, &info) == noErr
                  && (info.flags & kLSItemInfoIsInvisible) != 0;
        #endif
     }
static bool beast::FileHelpers::launchExecutable (const String & pathAndArguments) static
Definition at line 109 of file mac_Files.mm.
References beast::String::toUTF8().
     {
         const char* const argv[4] = { "/bin/sh", "-c", pathAndArguments.toUTF8(), 0 };
         const int cpid = fork();
         if (cpid == 0)
         {
             // Child process
             if (execve (argv[0], (char**) argv, 0) < 0)
                 exit (0);
         }
         else
         {
             if (cpid < 0)
                 return false;
         }
         return true;
     }