rippled: beast::asio::InputParser::State Struct Reference
beast::asio::InputParser::State Struct Reference
#include <InputParser.h>
Public Types
enum State_t { pass, fail, more }
Public Member Functions
State ()
State (State_t state)
State (bool condition)
State & operator= (State_t state)
bool eof () const noexcept
bool stop () const noexcept
bool passed () const noexcept
bool failed () const noexcept
operator bool () const noexcept
Private Attributes
State_t m_state
Detailed Description
Tri-valued parsing state. This is convertible to bool which means continue. Or you can use stop() to decide if you should return. After a stop you can use failed () to determine if parsing failed.
Definition at line 33 of file InputParser.h.
Member Enumeration Documentation
enum beast::asio::InputParser::State::State_t
Enumerator
pass
fail
more
Definition at line 35 of file InputParser.h.
     {
         pass, // passed the parse
         fail, // failed the parse
         more  // didn't fail but need more bytes
     };
Constructor & Destructor Documentation
beast::asio::InputParser::State::State () inline
Definition at line 42 of file InputParser.h.
 : m_state (more) { }
beast::asio::InputParser::State::State (State_t state) inline
Definition at line 44 of file InputParser.h.
 : m_state (state) { }
beast::asio::InputParser::State::State (bool condition) inline
Implicit construction from bool. If condition is true then the parse passes, else need more.
Definition at line 49 of file InputParser.h.
 : m_state (condition ? pass : more) { }
Member Function Documentation
bool beast::asio::InputParser::State::eof () const inline noexcept
Definition at line 53 of file InputParser.h.
References m_state, and more.
Referenced by beast::asio::InputParser::Get< UInt32Str >::func().
 { return m_state == more; }
bool beast::asio::InputParser::State::failed () const inline noexcept
Definition at line 56 of file InputParser.h.
References fail, and m_state.
Referenced by beast::asio::HandshakeDetectLogicPROXY::analyze(), and beast::asio::InputParser::Get< UInt32Str >::func().
 { return m_state == fail; }
beast::asio::InputParser::State::operator bool () const inline explicit noexcept
Definition at line 57 of file InputParser.h.
References m_state, and pass.
 { return m_state == pass; }
State& beast::asio::InputParser::State::operator= (State_t state) inline
Definition at line 51 of file InputParser.h.
References m_state.
 { m_state = state; return *this; }
bool beast::asio::InputParser::State::passed () const inline noexcept
Definition at line 55 of file InputParser.h.
References m_state, and pass.
Referenced by beast::asio::HandshakeDetectLogicPROXY::analyze(), beast::asio::InputParser::Match< T >::func(), beast::asio::InputParser::Get< UInt16Str >::func(), beast::asio::InputParser::Get< UInt8Str >::func(), beast::asio::InputParser::match(), beast::asio::InputParser::peek(), and beast::asio::InputParser::read().
 { return m_state == pass; }
bool beast::asio::InputParser::State::stop () const inline noexcept
Definition at line 54 of file InputParser.h.
References m_state, and pass.
 { return m_state != pass; }
Member Data Documentation
State_t beast::asio::InputParser::State::m_state private
Definition at line 60 of file InputParser.h.
Referenced by eof(), failed(), operator bool(), operator=(), passed(), and stop().
The documentation for this struct was generated from the following file:
rippled/src/beast/modules/beast_asio/protocol/InputParser.h