rippled: ripple::AcceptedLedger Class Reference
ripple::AcceptedLedger Class Reference
#include <AcceptedLedger.h>
Public Types
typedef boost::shared_ptr
< AcceptedLedger > pointer
typedef const pointer & ret
typedef std::map< int,
AcceptedLedgerTx::pointer > map_t
typedef map_t::value_type value_type
typedef map_t::const_iterator const_iterator
Public Member Functions
Ledger::ref getLedger () const
const map_t & getMap () const
int getLedgerSeq () const
int getTxnCount () const
AcceptedLedgerTx::pointer getTxn (int) const
Static Public Member Functions
static pointer makeAcceptedLedger (Ledger::ref ledger)
static void sweep ()
static float getCacheHitRate ()
Private Member Functions
AcceptedLedger (Ledger::ref ledger)
void insert (AcceptedLedgerTx::ref)
Private Attributes
Ledger::pointer mLedger
map_t mMap
Static Private Attributes
static TaggedCache< uint256,
AcceptedLedger > s_cache
Detailed Description
A ledger that has become irrevocable.
An accepted ledger is a ledger that has a sufficient number of validations to convince the local server that it is irrevocable.
The existence of an accepted ledger implies all preceding ledgers are accepted.
Definition at line 41 of file AcceptedLedger.h.
Member Typedef Documentation
typedef map_t::const_iterator ripple::AcceptedLedger::const_iterator
Definition at line 48 of file AcceptedLedger.h.
typedef std::map<int, AcceptedLedgerTx::pointer> ripple::AcceptedLedger::map_t
Definition at line 46 of file AcceptedLedger.h.
typedef boost::shared_ptr<AcceptedLedger> ripple::AcceptedLedger::pointer
Definition at line 44 of file AcceptedLedger.h.
typedef const pointer& ripple::AcceptedLedger::ret
Definition at line 45 of file AcceptedLedger.h.
typedef map_t::value_type ripple::AcceptedLedger::value_type
Definition at line 47 of file AcceptedLedger.h.
Constructor & Destructor Documentation
ripple::AcceptedLedger::AcceptedLedger (Ledger::ref ledger) explicit private
Definition at line 29 of file AcceptedLedger.cpp.
References insert(), ripple::SHAMap::peekFirstItem(), and ripple::SHAMap::peekNextItem().
                                                 : mLedger (ledger)
 {
     SHAMap& txSet = *ledger->peekTransactionMap ();
     for (SHAMapItem::pointer item = txSet.peekFirstItem (); !!item; item = txSet.peekNextItem (item->getTag ()))
     {
         SerializerIterator sit (item->peekSerializer ());
         insert (boost::make_shared<AcceptedLedgerTx> (ledger->getLedgerSeq (), boost::ref (sit)));
     }
 }
Member Function Documentation
static float ripple::AcceptedLedger::getCacheHitRate () inline static
Definition at line 75 of file AcceptedLedger.h.
References s_cache.
Referenced by ripple::RPCHandler::doGetCounts().
     {
         return s_cache.getHitRate ();
     }
Ledger::ref ripple::AcceptedLedger::getLedger () const inline
Definition at line 57 of file AcceptedLedger.h.
References mLedger.
     {
         return mLedger;
     }
int ripple::AcceptedLedger::getLedgerSeq () const inline
Definition at line 66 of file AcceptedLedger.h.
References mLedger.
     {
         return mLedger->getLedgerSeq ();
     }
const map_t& ripple::AcceptedLedger::getMap () const inline
Definition at line 61 of file AcceptedLedger.h.
References mMap.
     {
         return mMap;
     }
AcceptedLedgerTx::pointer ripple::AcceptedLedger::getTxn (int i) const
Definition at line 58 of file AcceptedLedger.cpp.
References mMap.
 {
     map_t::const_iterator it = mMap.find (i);
     if (it == mMap.end ())
         return AcceptedLedgerTx::pointer ();
     return it->second;
 }
int ripple::AcceptedLedger::getTxnCount () const inline
Definition at line 70 of file AcceptedLedger.h.
References mMap.
     {
         return mMap.size ();
     }
void ripple::AcceptedLedger::insert (AcceptedLedgerTx::ref at) private
Definition at line 52 of file AcceptedLedger.cpp.
References mMap.
Referenced by AcceptedLedger().
 {
     assert (mMap.find (at->getIndex ()) == mMap.end ());
     mMap.insert (std::make_pair (at->getIndex (), at));
 }
AcceptedLedger::pointer ripple::AcceptedLedger::makeAcceptedLedger (Ledger::ref ledger) static
Definition at line 40 of file AcceptedLedger.cpp.
References s_cache.
Referenced by ripple::NetworkOPsImp::pubLedger(), and ripple::Ledger::saveValidatedLedger().
 {
     AcceptedLedger::pointer ret = s_cache.fetch (ledger->getHash ());
     if (ret)
         return ret;
     ret = AcceptedLedger::pointer (new AcceptedLedger (ledger));
     s_cache.canonicalize (ledger->getHash (), ret);
     return ret;
 }
static void ripple::AcceptedLedger::sweep () inline static
Definition at line 52 of file AcceptedLedger.h.
References s_cache.
Referenced by ripple::ApplicationImp::doSweep().
     {
         s_cache.sweep ();
     }
Member Data Documentation
Ledger::pointer ripple::AcceptedLedger::mLedger private
Definition at line 90 of file AcceptedLedger.h.
Referenced by getLedger(), and getLedgerSeq().
map_t ripple::AcceptedLedger::mMap private
Definition at line 91 of file AcceptedLedger.h.
Referenced by getMap(), getTxn(), getTxnCount(), and insert().
TaggedCache< uint256, AcceptedLedger > ripple::AcceptedLedger::s_cache static private
Definition at line 88 of file AcceptedLedger.h.
Referenced by getCacheHitRate(), makeAcceptedLedger(), and sweep().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/ledger/AcceptedLedger.h
rippled/src/ripple_app/ledger/AcceptedLedger.cpp