rippled: ripple::LedgerCleanerImp Class Reference
ripple::LedgerCleanerImp Class Reference
Classes
struct State
Public Types
typedef beast::SharedData< State > SharedState
Public Types inherited from beast::Thread
typedef void * ThreadID
Public Member Functions
LedgerCleanerImp (Stoppable &stoppable, beast::Journal journal)
~LedgerCleanerImp ()
void onPrepare ()
void onStart ()
void onStop ()
void onWrite (beast::PropertyStream::Map &map)
void doClean (Json::Value const &params)
void init ()
void run ()
LedgerHash getLedgerHash (Ledger::pointer ledger, LedgerIndex index)
bool doLedger (LedgerIndex const &ledgerIndex, LedgerHash const &ledgerHash, bool doNodes, bool doTxns)
LedgerHash getHash (LedgerIndex const &ledgerIndex, Ledger::pointer &referenceLedger)
void doLedgerCleaner ()
Public Member Functions inherited from ripple::LedgerCleaner
virtual ~LedgerCleaner ()=0
Public Member Functions inherited from beast::Stoppable
Stoppable (char const *name, Stoppable &parent)
virtual ~Stoppable ()
bool isStopping () const
bool isStopped () const
bool areChildrenStopped () const
void stopped ()
virtual void onChildrenStopped ()
Public Member Functions inherited from beast::PropertyStream::Source
Source (std::string const &name)
~Source ()
std::string const & name () const
void add (Source &source)
template<class Derived >
Derived * add (Derived *child)
void remove (Source &child)
void removeAll ()
void write_one (PropertyStream &stream)
void write (PropertyStream &stream)
void write (PropertyStream &stream, std::string const &path)
std::pair< Source *, bool > find (std::string path)
Source * find_one_deep (std::string const &name)
PropertyStream::Source * find_path (std::string path)
PropertyStream::Source * find_one (std::string const &name)
Public Member Functions inherited from beast::Thread
Thread (const String &threadName)
virtual ~Thread ()
void startThread ()
void startThread (int priority)
bool stopThread (int timeOutMilliseconds=-1)
void stopThreadAsync ()
bool isThreadRunning () const
void signalThreadShouldExit ()
bool threadShouldExit () const
bool waitForThreadToExit (int timeOutMilliseconds=-1) const
bool setPriority (int priority)
void setAffinityMask (std::uint32_t affinityMask)
bool wait (int timeOutMilliseconds=-1) const
void notify () const
ThreadID getThreadId () const noexcept
const String & getThreadName () const
Public Attributes
SharedState m_state
beast::Journal m_journal
Additional Inherited Members
Static Public Member Functions inherited from ripple::LedgerCleaner
static LedgerCleaner * New (Stoppable &parent, beast::Journal journal)
Static Public Member Functions inherited from beast::Thread
static bool setCurrentThreadPriority (int priority)
static void setCurrentThreadAffinityMask (std::uint32_t affinityMask)
static void sleep (int milliseconds)
static void yield ()
static ThreadID getCurrentThreadId ()
static Thread * getCurrentThread ()
static void setCurrentThreadName (const String &newThreadName)
Protected Member Functions inherited from ripple::LedgerCleaner
LedgerCleaner (Stoppable &parent)
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Protected Attributes inherited from beast::Stoppable
char const * m_name
RootStoppable & m_root
Child m_child
Atomic< int > m_started
bool volatile m_stopped
bool volatile m_childrenStopped
Children m_children
WaitableEvent m_stoppedEvent
Detailed Description
Definition at line 36 of file LedgerCleaner.cpp.
Member Typedef Documentation
typedef beast::SharedData<State> ripple::LedgerCleanerImp::SharedState
Definition at line 60 of file LedgerCleaner.cpp.
Constructor & Destructor Documentation
ripple::LedgerCleanerImp::LedgerCleanerImp (Stoppable & stoppable, beast::Journal journal) inline
Definition at line 67 of file LedgerCleaner.cpp.
         : LedgerCleaner (stoppable)
         , Thread ("LedgerCleaner")
         , m_journal (journal)
     {
     }
ripple::LedgerCleanerImp::~LedgerCleanerImp () inline
Definition at line 76 of file LedgerCleaner.cpp.
References beast::Thread::stopThread().
     {
         stopThread ();
     }
Member Function Documentation
void ripple::LedgerCleanerImp::doClean (Json::Value const & parameters) inline virtual
Start a long running task to clean the ledger. The ledger is cleaned asynchronously, on an implementation defined thread. This function call does not block. The long running task will be stopped if the Stoppable stops.
Thread safety: Safe to call from any thread at any time.
Parameters
parameters A Json object with configurable parameters.
Implements ripple::LedgerCleaner.
Definition at line 133 of file LedgerCleaner.cpp.
References Json::Value::asBool(), Json::Value::asUInt(), ripple::getApp(), ripple::LedgerMaster::getFullValidatedRange(), ripple::Application::getLedgerMaster(), Json::Value::isMember(), m_state, and beast::Thread::notify().
     {
         LedgerIndex minRange;
         LedgerIndex maxRange;
         getApp().getLedgerMaster().getFullValidatedRange (minRange, maxRange);
         {
             SharedState::Access state (m_state);
             state->maxRange = maxRange;
             state->minRange = minRange;
             state->checkNodes = false;
             state->fixTxns = false;
             state->failures = 0;
             /*
             JSON Parameters:
                 All parameters are optional. By default the cleaner cleans
                 things it thinks are necessary. This behavior can be modified
                 using the following options supplied via JSON RPC:
                 "ledger"
                     A single unsigned integer representing an individual
                     ledger to clean.
                 "min_ledger", "max_ledger"
                     Unsigned integers representing the starting and ending
                     ledger numbers to clean. If unspecified, clean all ledgers.
                 "full"
                     A boolean. When set to true, means clean everything possible.
                 "fix_txns"
                     A boolean value indicating whether or not to fix the
                     transactions in the database as well.
                 "check_nodes"
                     A boolean, when set to true means check the nodes.
                 "stop"
                     A boolean, when set to true informs the cleaner to gracefully
                     stop its current activities if any cleaning is taking place.
             */
             // Quick way to fix a single ledger
             if (params.isMember("ledger"))
             {
                 state->maxRange = params["ledger"].asUInt();
                 state->minRange = params["ledger"].asUInt();
                 state->fixTxns = true;
                 state->checkNodes = true;
             }
             if (params.isMember("max_ledger"))
                  state->maxRange = params["max_ledger"].asUInt();
             if (params.isMember("min_ledger"))
                 state->minRange = params["min_ledger"].asUInt();
             if (params.isMember("full"))
                 state->fixTxns = state->checkNodes = params["full"].asBool();
             if (params.isMember("fix_txns"))
                 state->fixTxns = params["fix_txns"].asBool();
             if (params.isMember("check_nodes"))
                 state->checkNodes = params["check_nodes"].asBool();
             if (params.isMember("stop") && params["stop"].asBool())
                 state->minRange = state->maxRange = 0;
         }
         notify();
     }
bool ripple::LedgerCleanerImp::doLedger (LedgerIndex const & ledgerIndex, LedgerHash const & ledgerHash, bool doNodes, bool doTxns) inline
Process a single ledger
Parameters
ledgerIndex The index of the ledger to process.
ledgerHash The known correct hash of the ledger.
doNodes Ensure all ledger nodes are in the node db.
doTxns Reprocess (account) transactions to SQL databases.
Returns
true if the ledger was cleaned.
Definition at line 262 of file LedgerCleaner.cpp.
References beast::Journal::debug, ripple::InboundLedger::fcGENERIC, ripple::LedgerMaster::findAcquireLedger(), ripple::InboundLedgers::findCreate(), ripple::LedgerMaster::fixIndex(), ripple::getApp(), ripple::Application::getInboundLedgers(), ripple::Application::getLedgerMaster(), ripple::Ledger::loadByIndex(), and m_journal.
Referenced by doLedgerCleaner().
     {
         Ledger::pointer nodeLedger = getApp().getLedgerMaster().findAcquireLedger(ledgerIndex, ledgerHash);
         if (!nodeLedger)
         {
             m_journal.debug << "Ledger " << ledgerIndex << " not available";
             return false;
         }
         Ledger::pointer dbLedger = Ledger::loadByIndex(ledgerIndex);
         if (! dbLedger ||
             (dbLedger->getHash() != ledgerHash) ||
             (dbLedger->getParentHash() != nodeLedger->getParentHash()))
         {
             // Ideally we'd also check for more than one ledger with that index
             m_journal.debug <<
                 "Ledger " << ledgerIndex << " mismatches SQL DB";
             doTxns = true;
         }
         if(! getApp().getLedgerMaster().fixIndex(ledgerIndex, ledgerHash))
         {
             m_journal.debug << "ledger " << ledgerIndex << " had wrong entry in history";
             doTxns = true;
         }
         if (doNodes && !nodeLedger->walkLedger())
         {
             m_journal.debug << "Ledger " << ledgerIndex << " is missing nodes";
             getApp().getInboundLedgers().findCreate(ledgerHash, ledgerIndex, InboundLedger::fcGENERIC);
             return false;
         }
         if (doTxns && !nodeLedger->pendSaveValidated(true, false))
         {
             m_journal.debug << "Failed to save ledger " << ledgerIndex;
             return false;
         }
         nodeLedger->dropCache();
         return true;
     }
void ripple::LedgerCleanerImp::doLedgerCleaner () inline
Run the ledger cleaner.
Definition at line 360 of file LedgerCleaner.cpp.
References beast::Journal::debug, doLedger(), ripple::getApp(), getHash(), beast::Journal::info, ripple::base_uint< BITS >::isZero(), m_journal, m_state, beast::Thread::sleep(), and beast::Thread::threadShouldExit().
Referenced by run().
     {
         Ledger::pointer goodLedger;
         while (! this->threadShouldExit())
         {
             LedgerIndex ledgerIndex;
             LedgerHash ledgerHash;
             bool doNodes;
             bool doTxns;
             while (getApp().getFeeTrack().isLoadedLocal())
             {
                 m_journal.debug << "Waiting for load to subside";
                 sleep(5000);
                 if (this->threadShouldExit ())
                     return;
             }
             {
                 SharedState::Access state (m_state);
                 if ((state->minRange > state->maxRange) ||
                     (state->maxRange == 0) || (state->minRange == 0))
                 {
                     state->minRange = state->maxRange = 0;
                     return;
                 }
                 ledgerIndex = state->maxRange;
                 doNodes = state->checkNodes;
                 doTxns = state->fixTxns;
             }
             ledgerHash = getHash(ledgerIndex, goodLedger);
             bool fail = false;
             if (ledgerHash.isZero())
             {
                 m_journal.info << "Unable to get hash for ledger " << ledgerIndex;
                 fail = true;
             }
             else if (!doLedger(ledgerIndex, ledgerHash, doNodes, doTxns))
             {
                 m_journal.info << "Failed to process ledger " << ledgerIndex;
                 fail = true;
             }
             if (fail)
             {
                 {
                     SharedState::Access state (m_state);
                     ++state->failures;
                 }
                 sleep(2000); // Wait for acquiring to catch up to us
             }
             else
             {
                 {
                     SharedState::Access state (m_state);
                     if (ledgerIndex == state->minRange)
                         ++state->minRange;
                     if (ledgerIndex == state->maxRange)
                         --state->maxRange;
                     state->failures = 0;
                 }
                 sleep(100); // Reduce I/O pressure a bit
             }
         }
     }
LedgerHash ripple::LedgerCleanerImp::getHash (LedgerIndex const & ledgerIndex, Ledger::pointer & referenceLedger) inline
Returns the hash of the specified ledger.
Parameters
ledgerIndex The index of the desired ledger.
referenceLedger [out] An optional known good subsequent ledger.
Returns
The hash of the ledger. This will be all-bits-zero if not found.
Definition at line 315 of file LedgerCleaner.cpp.
References ripple::LedgerMaster::findAcquireLedger(), ripple::getApp(), getLedgerHash(), ripple::Application::getLedgerMaster(), ripple::LedgerMaster::getValidatedLedger(), ripple::base_uint< BITS >::isNonZero(), ripple::base_uint< BITS >::isZero(), m_journal, and beast::Journal::warning.
Referenced by doLedgerCleaner().
     {
         LedgerHash ledgerHash;
         if (!referenceLedger || (referenceLedger->getLedgerSeq() < ledgerIndex))
         {
             referenceLedger = getApp().getLedgerMaster().getValidatedLedger();
             if (!referenceLedger)
             {
                 m_journal.warning << "No validated ledger";
                 return ledgerHash; // Nothing we can do. No validated ledger.
             }
         }
         if (referenceLedger->getLedgerSeq() >= ledgerIndex)
         {
             // See if the hash for the ledger we need is in the reference ledger
             ledgerHash = getLedgerHash(referenceLedger, ledgerIndex);
             if (ledgerHash.isZero())
             {
                 // No, Try to get another ledger that might have the hash we need
                 // Compute the index and hash of a ledger that will have the hash we need
                 LedgerIndex refIndex = (ledgerIndex + 255) & (~255);
                 LedgerHash refHash = getLedgerHash (referenceLedger, refIndex);
                 bool const nonzero (refHash.isNonZero ());
                 assert (nonzero);
                 if (nonzero)
                 {
                     // We found the hash and sequence of a better reference ledger
                     referenceLedger = getApp().getLedgerMaster().findAcquireLedger (refIndex, refHash);
                     if (referenceLedger)
                         ledgerHash = getLedgerHash(referenceLedger, ledgerIndex);
                 }
             }
         }
         else
             m_journal.warning << "Validated ledger is prior to target ledger";
         return ledgerHash;
     }
LedgerHash ripple::LedgerCleanerImp::getLedgerHash (Ledger::pointer ledger, LedgerIndex index) inline
Definition at line 238 of file LedgerCleaner.cpp.
References ripple::InboundLedger::fcGENERIC, ripple::InboundLedgers::findCreate(), ripple::getApp(), ripple::Application::getInboundLedgers(), hash, m_journal, and beast::Journal::warning.
Referenced by getHash().
     {
         LedgerHash hash;
         try
         {
             hash = ledger->getLedgerHash(index);
         }
         catch (SHAMapMissingNode &)
         {
             m_journal.warning <<
                 "Node missing from ledger " << ledger->getLedgerSeq();
             getApp().getInboundLedgers().findCreate (
                 ledger->getHash(), ledger->getLedgerSeq(), InboundLedger::fcGENERIC);
         }
         return hash;
     }
void ripple::LedgerCleanerImp::init () inline
Definition at line 215 of file LedgerCleaner.cpp.
References beast::Journal::debug, and m_journal.
Referenced by run().
     {
         m_journal.debug << "Initializing";
     }
void ripple::LedgerCleanerImp::onPrepare () inline virtual
Override called during preparation. Since all other Stoppable objects in the tree have already been constructed, this provides an opportunity to perform initialization which depends on calling into other Stoppable objects. This call is made on the same thread that called prepare(). The default implementation does nothing. Guaranteed to only be called once.
Reimplemented from beast::Stoppable.
Definition at line 87 of file LedgerCleaner.cpp.
     {
     }
void ripple::LedgerCleanerImp::onStart () inline virtual
Override called during start.
Reimplemented from beast::Stoppable.
Definition at line 91 of file LedgerCleaner.cpp.
References beast::Thread::startThread().
     {
         startThread();
     }
void ripple::LedgerCleanerImp::onStop () inline virtual
Override called when the stop notification is issued.
The call is made on an unspecified, implementation-specific thread. onStop and onChildrenStopped will never be called concurrently, across all Stoppable objects descended from the same root, inclusive of the root.
It is safe to call isStopping, isStopped, and areChildrenStopped from within this function; The values returned will always be valid and never change during the callback.
The default implementation simply calls stopped(). This is applicable when the Stoppable has a trivial stop operation (or no stop operation), and we are merely using the Stoppable API to position it as a dependency of some parent service.
Thread safety: May not block for long periods. Guaranteed only to be called once. Must be safe to call from any thread at any time.
Reimplemented from beast::Stoppable.
Definition at line 96 of file LedgerCleaner.cpp.
References beast::Journal::info, m_journal, beast::Thread::notify(), and beast::Thread::signalThreadShouldExit().
     {
         m_journal.info << "Stopping";
         signalThreadShouldExit();
         notify();
     }
void ripple::LedgerCleanerImp::onWrite (beast::PropertyStream::Map &) inline virtual
Subclass override. The default version does nothing.
Reimplemented from beast::PropertyStream::Source.
Definition at line 109 of file LedgerCleaner.cpp.
References m_state.
     {
         SharedState::Access state (m_state);
         if (state->maxRange == 0)
             map["status"] = "idle";
         else
         {
             map["status"] = "running";
             map["ledger_min"] = state->minRange;
             map["ledger_max"] = state->maxRange;
             map["check_nodes"] = state->checkNodes ? "true" : "false";
             map["fix_txns"] = state->fixTxns ? "true" : "false";
             if (state->failures > 0)
                 map["fail_counts"] = state->failures;
         }
     }
void ripple::LedgerCleanerImp::run () inline virtual
Must be implemented to perform the thread's actual code.
Remember that the thread must regularly check the threadShouldExit() method whilst running, and if this returns true it should return from the run() method as soon as possible to avoid being forcibly killed.
See Also
threadShouldExit, startThread
Implements beast::Thread.
Definition at line 220 of file LedgerCleaner.cpp.
References beast::Journal::debug, doLedgerCleaner(), init(), m_journal, beast::Stoppable::stopped(), beast::Thread::threadShouldExit(), and beast::Thread::wait().
     {
         m_journal.debug << "Started";
         init ();
         while (! this->threadShouldExit())
         {
             this->wait ();
             if (! this->threadShouldExit())
             {
                 doLedgerCleaner();
             }
         }
         stopped();
     }
Member Data Documentation
beast::Journal ripple::LedgerCleanerImp::m_journal
Definition at line 63 of file LedgerCleaner.cpp.
Referenced by doLedger(), doLedgerCleaner(), getHash(), getLedgerHash(), init(), onStop(), and run().
SharedState ripple::LedgerCleanerImp::m_state
Definition at line 62 of file LedgerCleaner.cpp.
Referenced by doClean(), doLedgerCleaner(), and onWrite().
The documentation for this class was generated from the following file:
rippled/src/ripple_app/ledger/LedgerCleaner.cpp