rippled: rocksdb::test::ErrorEnv Class Reference
rocksdb::test::ErrorEnv Class Reference
#include <testutil.h>
Public Member Functions
ErrorEnv ()
virtual Status NewWritableFile (const std::string &fname, unique_ptr< WritableFile > *result, const EnvOptions &soptions)
Public Member Functions inherited from rocksdb::EnvWrapper
EnvWrapper (Env *t)
virtual ~EnvWrapper ()
Env * target () const
Status NewSequentialFile (const std::string &f, unique_ptr< SequentialFile > *r, const EnvOptions &options)
Status NewRandomAccessFile (const std::string &f, unique_ptr< RandomAccessFile > *r, const EnvOptions &options)
Status NewRandomRWFile (const std::string &f, unique_ptr< RandomRWFile > *r, const EnvOptions &options)
bool FileExists (const std::string &f)
Status GetChildren (const std::string &dir, std::vector< std::string > *r)
Status DeleteFile (const std::string &f)
Status CreateDir (const std::string &d)
Status CreateDirIfMissing (const std::string &d)
Status DeleteDir (const std::string &d)
Status GetFileSize (const std::string &f, uint64_t *s)
Status GetFileModificationTime (const std::string &fname, uint64_t *file_mtime)
Status RenameFile (const std::string &s, const std::string &t)
Status LockFile (const std::string &f, FileLock **l)
Status UnlockFile (FileLock *l)
void Schedule (void(*f)(void *), void *a, Priority pri)
void StartThread (void(*f)(void *), void *a)
virtual Status GetTestDirectory (std::string *path)
virtual Status NewLogger (const std::string &fname, shared_ptr< Logger > *result)
uint64_t NowMicros ()
void SleepForMicroseconds (int micros)
Status GetHostName (char *name, uint64_t len)
Status GetCurrentTime (int64_t *unix_time)
Status GetAbsolutePath (const std::string &db_path, std::string *output_path)
void SetBackgroundThreads (int num, Priority pri)
std::string TimeToString (uint64_t time)
Public Member Functions inherited from rocksdb::Env
Env ()
virtual ~Env ()
virtual void Schedule (void(*function)(void *arg), void *arg, Priority pri=LOW)=0
virtual void StartThread (void(*function)(void *arg), void *arg)=0
virtual uint64_t NowNanos ()
virtual std::string GenerateUniqueId ()
Public Attributes
bool writable_file_error_
int num_writable_file_errors_
Additional Inherited Members
Public Types inherited from rocksdb::Env
enum Priority { LOW, HIGH, TOTAL }
Static Public Member Functions inherited from rocksdb::Env
static Env * Default ()
Detailed Description
Definition at line 33 of file testutil.h.
Constructor & Destructor Documentation
rocksdb::test::ErrorEnv::ErrorEnv () inline
Definition at line 38 of file testutil.h.
              : EnvWrapper(Env::Default()),
                writable_file_error_(false),
                num_writable_file_errors_(0) { }
Member Function Documentation
virtual Status rocksdb::test::ErrorEnv::NewWritableFile (const std::string & fname, unique_ptr< WritableFile > * result, const EnvOptions & soptions) inline virtual
Reimplemented from rocksdb::EnvWrapper.
Definition at line 42 of file testutil.h.
References rocksdb::Status::IOError(), rocksdb::Env::NewWritableFile(), num_writable_file_errors_, rocksdb::EnvWrapper::target(), and writable_file_error_.
{
     result->reset();
     if (writable_file_error_) {
       ++num_writable_file_errors_;
       return Status::IOError(fname, "fake error");
     }
     return target()->NewWritableFile(fname, result, soptions);
   }
Member Data Documentation
int rocksdb::test::ErrorEnv::num_writable_file_errors_
Definition at line 36 of file testutil.h.
Referenced by NewWritableFile().
bool rocksdb::test::ErrorEnv::writable_file_error_
Definition at line 35 of file testutil.h.
Referenced by NewWritableFile().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/util/testutil.h