rippled: ripple::TransactionMetaSet Class Reference
ripple::TransactionMetaSet Class Reference
#include <TransactionMeta.h>
Public Types
typedef boost::shared_ptr
< TransactionMetaSet > pointer
typedef const pointer & ref
Public Member Functions
TransactionMetaSet ()
TransactionMetaSet (uint256 const &txID, std::uint32_t ledger, std::uint32_t index)
TransactionMetaSet (uint256 const &txID, std::uint32_t ledger, Blob const &)
void init (uint256 const &transactionID, std::uint32_t ledger)
void clear ()
void swap (TransactionMetaSet &)
uint256 const & getTxID ()
std::uint32_t getLgrSeq ()
int getResult () const
TER getResultTER () const
std::uint32_t getIndex () const
bool isNodeAffected (uint256 const &) const
void setAffectedNode (uint256 const &, SField::ref type, std::uint16_t nodeType)
STObject & getAffectedNode (SLE::ref node, SField::ref type)
STObject & getAffectedNode (uint256 const &)
const STObject & peekAffectedNode (uint256 const &) const
std::vector< RippleAddress > getAffectedAccounts ()
Json::Value getJson (int p) const
void addRaw (Serializer &, TER, std::uint32_t index)
STObject getAsObject () const
STArray & getNodes ()
void setDeliveredAmount (STAmount const &delivered)
STAmount getDeliveredAmount () const
bool hasDeliveredAmount () const
Static Public Member Functions
static bool thread (STObject &node, uint256 const &prevTxID, std::uint32_t prevLgrID)
Private Attributes
uint256 mTransactionID
std::uint32_t mLedger
std::uint32_t mIndex
int mResult
boost::optional< STAmount > mDelivered
STArray mNodes
Detailed Description
Definition at line 25 of file TransactionMeta.h.
Member Typedef Documentation
typedef boost::shared_ptr<TransactionMetaSet> ripple::TransactionMetaSet::pointer
Definition at line 28 of file TransactionMeta.h.
typedef const pointer& ripple::TransactionMetaSet::ref
Definition at line 29 of file TransactionMeta.h.
Constructor & Destructor Documentation
ripple::TransactionMetaSet::TransactionMetaSet () inline
Definition at line 32 of file TransactionMeta.h.
         : mLedger (0)
         , mIndex (static_cast<std::uint32_t> (-1))
         , mResult (255)
     {
     }
ripple::TransactionMetaSet::TransactionMetaSet (uint256 const & txID, std::uint32_t ledger, std::uint32_t index) inline
Definition at line 39 of file TransactionMeta.h.
         : mTransactionID (txID)
         , mLedger (ledger)
         , mIndex (static_cast<std::uint32_t> (-1))
         , mResult (255)
     {
     }
ripple::TransactionMetaSet::TransactionMetaSet (uint256 const & txID, std::uint32_t ledger, Blob const & vec)
Definition at line 26 of file TransactionMeta.cpp.
References ripple::STObject::deserialize(), ripple::STObject::getField(), ripple::STObject::getFieldAmount(), ripple::STObject::getFieldU32(), ripple::STObject::getFieldU8(), and ripple::STObject::isFieldPresent().
                                                                                                 :
     mTransactionID (txid), mLedger (ledger), mNodes (sfAffectedNodes, 32)
 {
     Serializer s (vec);
     SerializerIterator sit (s);
     std::unique_ptr<SerializedType> pobj = STObject::deserialize (sit, sfAffectedNodes);
     STObject* obj = static_cast<STObject*> (pobj.get ());
     if (!obj)
         throw std::runtime_error ("bad metadata");
     mResult = obj->getFieldU8 (sfTransactionResult);
     mIndex = obj->getFieldU32 (sfTransactionIndex);
     mNodes = * dynamic_cast<STArray*> (&obj->getField (sfAffectedNodes));
     if (obj->isFieldPresent (sfDeliveredAmount))
         setDeliveredAmount (obj->getFieldAmount (sfDeliveredAmount));
 }
Member Function Documentation
void ripple::TransactionMetaSet::addRaw (Serializer & s, TER result, std::uint32_t index)
Definition at line 227 of file TransactionMeta.cpp.
References ripple::STObject::add(), ripple::compare(), getAsObject(), mIndex, mNodes, mResult, and ripple::STArray::sort().
Referenced by ripple::LedgerEntrySet::calcRawMeta().
 {
     mResult = static_cast<int> (result);
     mIndex = index;
     assert ((mResult == 0) || ((mResult > 100) && (mResult <= 255)));
     mNodes.sort (compare);
     getAsObject ().add (s);
 }
void ripple::TransactionMetaSet::clear () inline
Definition at line 50 of file TransactionMeta.h.
References ripple::STArray::clear(), and mNodes.
Referenced by ripple::LedgerEntrySet::clear().
     {
         mNodes.clear ();
     }
std::vector< RippleAddress > ripple::TransactionMetaSet::getAffectedAccounts ()
Definition at line 88 of file TransactionMeta.cpp.
References ripple::RPC::accounts(), ripple::addIfUnique(), beast::field(), ripple::STObject::getFieldIndex(), ripple::SerializedType::getFName(), ripple::STAmount::getIssuer(), ripple::SerializedType::getJson(), ripple::STAccount::getValueNCA(), ripple::base_uint< BITS >::isNonZero(), ripple::lsFATAL, mNodes, ripple::STObject::peekAtIndex(), ripple::STObject::peekData(), ripple::RippleAddress::setAccountID(), and WriteLog.
 {
     std::vector<RippleAddress> accounts;
     accounts.reserve (10);
     // This code should match the behavior of the JS method:
     // Meta#getAffectedAccounts
     BOOST_FOREACH (const STObject & it, mNodes)
     {
         int index = it.getFieldIndex ((it.getFName () == sfCreatedNode) ? sfNewFields : sfFinalFields);
         if (index != -1)
         {
             const STObject* inner = dynamic_cast<const STObject*> (&it.peekAtIndex (index));
             if (inner)
             {
                 BOOST_FOREACH (const SerializedType & field, inner->peekData ())
                 {
                     const STAccount* sa = dynamic_cast<const STAccount*> (&field);
                     if (sa)
                         addIfUnique (accounts, sa->getValueNCA ());
                     else if ((field.getFName () == sfLowLimit) || (field.getFName () == sfHighLimit) ||
                              (field.getFName () == sfTakerPays) || (field.getFName () == sfTakerGets))
                     {
                         const STAmount* lim = dynamic_cast<const STAmount*> (&field);
                         if (lim != nullptr)
{
                             uint160 issuer = lim->getIssuer ();
                             if (issuer.isNonZero ())
{
                                 RippleAddress na;
                                 na.setAccountID (issuer);
                                 addIfUnique (accounts, na);
                             }
                         }
                         else
{
                             WriteLog (lsFATAL, TransactionMetaSet) << "limit is not amount " << field.getJson (0);
                         }
                     }
                 }
             }
             else assert (false);
         }
     }
     return accounts;
 }
STObject & ripple::TransactionMetaSet::getAffectedNode (SLE::ref node, SField::ref type)
Definition at line 141 of file TransactionMeta.cpp.
References ripple::STArray::back(), ripple::STObject::getFieldH256(), ripple::SerializedType::getFName(), mNodes, ripple::STArray::push_back(), ripple::STObject::setFieldH256(), and ripple::STObject::setFieldU16().
Referenced by ripple::LedgerEntrySet::calcRawMeta(), and ripple::LedgerEntrySet::threadTx().
 {
     assert (&type);
     uint256 index = node->getIndex ();
     BOOST_FOREACH (STObject & it, mNodes)
     {
         if (it.getFieldH256 (sfLedgerIndex) == index)
             return it;
     }
     mNodes.push_back (STObject (type));
     STObject& obj = mNodes.back ();
     assert (obj.getFName () == type);
     obj.setFieldH256 (sfLedgerIndex, index);
     obj.setFieldU16 (sfLedgerEntryType, node->getFieldU16 (sfLedgerEntryType));
     return obj;
 }
STObject & ripple::TransactionMetaSet::getAffectedNode (uint256 const & node)
Definition at line 160 of file TransactionMeta.cpp.
References ripple::STObject::getFieldH256(), and mNodes.
 {
     BOOST_FOREACH (STObject & it, mNodes)
     {
         if (it.getFieldH256 (sfLedgerIndex) == node)
             return it;
     }
     assert (false);
     throw std::runtime_error ("Affected node not found");
 }
STObject ripple::TransactionMetaSet::getAsObject () const
Definition at line 215 of file TransactionMeta.cpp.
References ripple::STObject::addObject(), getDeliveredAmount(), hasDeliveredAmount(), mIndex, mNodes, mResult, ripple::STObject::setFieldAmount(), ripple::STObject::setFieldU32(), and ripple::STObject::setFieldU8().
Referenced by addRaw(), and getJson().
 {
     STObject metaData (sfTransactionMetaData);
     assert (mResult != 255);
     metaData.setFieldU8 (sfTransactionResult, mResult);
     metaData.setFieldU32 (sfTransactionIndex, mIndex);
     metaData.addObject (mNodes);
     if (hasDeliveredAmount ())
         metaData.setFieldAmount (sfDeliveredAmount, getDeliveredAmount ());
     return metaData;
 }
STAmount ripple::TransactionMetaSet::getDeliveredAmount () const inline
Definition at line 102 of file TransactionMeta.h.
References hasDeliveredAmount(), and mDelivered.
Referenced by getAsObject().
     {
         assert (hasDeliveredAmount ());
         return *mDelivered;
     }
std::uint32_t ripple::TransactionMetaSet::getIndex () const inline
Definition at line 72 of file TransactionMeta.h.
References mIndex.
Referenced by ripple::addTxnSeqField().
     {
         return mIndex;
     }
Json::Value ripple::TransactionMetaSet::getJson (int p) const inline
Definition at line 85 of file TransactionMeta.h.
References getAsObject(), and ripple::STObject::getJson().
Referenced by ripple::LedgerEntrySet::calcRawMeta(), and ripple::LedgerEntrySet::getJson().
     {
         return getAsObject ().getJson (p);
     }
std::uint32_t ripple::TransactionMetaSet::getLgrSeq () inline
Definition at line 60 of file TransactionMeta.h.
References mLedger.
Referenced by ripple::LedgerEntrySet::threadTx().
     {
         return mLedger;
     }
STArray& ripple::TransactionMetaSet::getNodes () inline
Definition at line 92 of file TransactionMeta.h.
References mNodes.
     {
         return (mNodes);
     }
int ripple::TransactionMetaSet::getResult () const inline
Definition at line 64 of file TransactionMeta.h.
References mResult.
     {
         return mResult;
     }
TER ripple::TransactionMetaSet::getResultTER () const inline
Definition at line 68 of file TransactionMeta.h.
References mResult.
     {
         return static_cast<TER> (mResult);
     }
uint256 const& ripple::TransactionMetaSet::getTxID () inline
Definition at line 56 of file TransactionMeta.h.
References mTransactionID.
Referenced by ripple::LedgerEntrySet::threadTx().
     {
         return mTransactionID;
     }
bool ripple::TransactionMetaSet::hasDeliveredAmount () const inline
Definition at line 108 of file TransactionMeta.h.
References mDelivered.
Referenced by getAsObject(), and getDeliveredAmount().
     {
          return mDelivered;
     }
void ripple::TransactionMetaSet::init (uint256 const & transactionID, std::uint32_t ledger)
Definition at line 181 of file TransactionMeta.cpp.
References id, mDelivered, mLedger, mNodes, and mTransactionID.
Referenced by ripple::LedgerEntrySet::init().
 {
     mTransactionID = id;
     mLedger = ledger;
     mNodes = STArray (sfAffectedNodes, 32);
     mDelivered = boost::optional <STAmount> ();
 }
bool ripple::TransactionMetaSet::isNodeAffected (uint256 const & node) const
Definition at line 46 of file TransactionMeta.cpp.
References ripple::STObject::getFieldH256(), and mNodes.
 {
     BOOST_FOREACH (const STObject & it, mNodes)
     if (it.getFieldH256 (sfLedgerIndex) == node)
         return true;
     return false;
 }
const STObject & ripple::TransactionMetaSet::peekAffectedNode (uint256 const & node) const
Definition at line 171 of file TransactionMeta.cpp.
References ripple::STObject::getFieldH256(), and mNodes.
 {
     BOOST_FOREACH (const STObject & it, mNodes)
     if (it.getFieldH256 (sfLedgerIndex) == node)
         return it;
     throw std::runtime_error ("Affected node not found");
 }
void ripple::TransactionMetaSet::setAffectedNode (uint256 const & node, SField::ref type, std::uint16_t nodeType)
Definition at line 56 of file TransactionMeta.cpp.
References ripple::STArray::back(), ripple::STObject::getFieldH256(), ripple::SerializedType::getFName(), mNodes, ripple::STArray::push_back(), ripple::STObject::setFieldH256(), ripple::STObject::setFieldU16(), and ripple::SerializedType::setFName().
Referenced by ripple::LedgerEntrySet::calcRawMeta().
 {
     // make sure the node exists and force its type
     BOOST_FOREACH (STObject & it, mNodes)
     {
         if (it.getFieldH256 (sfLedgerIndex) == node)
         {
             it.setFName (type);
             it.setFieldU16 (sfLedgerEntryType, nodeType);
             return;
         }
     }
     mNodes.push_back (STObject (type));
     STObject& obj = mNodes.back ();
     assert (obj.getFName () == type);
     obj.setFieldH256 (sfLedgerIndex, node);
     obj.setFieldU16 (sfLedgerEntryType, nodeType);
 }
void ripple::TransactionMetaSet::setDeliveredAmount (STAmount const & delivered) inline
Definition at line 97 of file TransactionMeta.h.
References mDelivered.
Referenced by ripple::LedgerEntrySet::setDeliveredAmount().
     {
         mDelivered.reset (delivered);
     }
void ripple::TransactionMetaSet::swap (TransactionMetaSet & s)
Definition at line 189 of file TransactionMeta.cpp.
References mLedger, mNodes, mTransactionID, and ripple::STArray::swap().
Referenced by ripple::LedgerEntrySet::swapWith().
 {
     assert ((mTransactionID == s.mTransactionID) && (mLedger == s.mLedger));
     mNodes.swap (s.mNodes);
 }
bool ripple::TransactionMetaSet::thread (STObject & node, uint256 const & prevTxID, std::uint32_t prevLgrID) static
Definition at line 195 of file TransactionMeta.cpp.
References ripple::STObject::getFieldH256(), ripple::STObject::getFieldIndex(), ripple::STObject::getFieldU32(), ripple::STObject::setFieldH256(), and ripple::STObject::setFieldU32().
Referenced by ripple::LedgerEntrySet::threadTx().
 {
     if (node.getFieldIndex (sfPreviousTxnID) == -1)
     {
         assert (node.getFieldIndex (sfPreviousTxnLgrSeq) == -1);
         node.setFieldH256 (sfPreviousTxnID, prevTxID);
         node.setFieldU32 (sfPreviousTxnLgrSeq, prevLgrID);
         return true;
     }
     assert (node.getFieldH256 (sfPreviousTxnID) == prevTxID);
     assert (node.getFieldU32 (sfPreviousTxnLgrSeq) == prevLgrID);
     return false;
 }
Member Data Documentation
boost::optional<STAmount> ripple::TransactionMetaSet::mDelivered private
Definition at line 121 of file TransactionMeta.h.
Referenced by getDeliveredAmount(), hasDeliveredAmount(), init(), and setDeliveredAmount().
std::uint32_t ripple::TransactionMetaSet::mIndex private
Definition at line 118 of file TransactionMeta.h.
Referenced by addRaw(), getAsObject(), and getIndex().
std::uint32_t ripple::TransactionMetaSet::mLedger private
Definition at line 117 of file TransactionMeta.h.
Referenced by getLgrSeq(), init(), and swap().
STArray ripple::TransactionMetaSet::mNodes private
Definition at line 123 of file TransactionMeta.h.
Referenced by addRaw(), clear(), getAffectedAccounts(), getAffectedNode(), getAsObject(), getNodes(), init(), isNodeAffected(), peekAffectedNode(), setAffectedNode(), and swap().
int ripple::TransactionMetaSet::mResult private
Definition at line 119 of file TransactionMeta.h.
Referenced by addRaw(), getAsObject(), getResult(), and getResultTER().
uint256 ripple::TransactionMetaSet::mTransactionID private
Definition at line 116 of file TransactionMeta.h.
Referenced by getTxID(), init(), and swap().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/tx/TransactionMeta.h
rippled/src/ripple_app/tx/TransactionMeta.cpp