rippled: beast::UnsignedInteger< Bytes > Class Template Reference
beast::UnsignedInteger< Bytes > Class Template Reference
#include <UnsignedInteger.h>
Classes
class equal
Public Types
typedef std::uint32_t IntCalcType
typedef UnsignedIntegerCalc
< IntCalcType > CalcType
typedef std::uint8_t value_type
typedef value_type * iterator
typedef value_type const * const_iterator
typedef hardened_hash
< UnsignedInteger > hasher
Public Member Functions
UnsignedInteger ()
UnsignedInteger (UnsignedInteger const &other)
UnsignedInteger & operator= (UnsignedInteger const &other)
void fill (value_type value)
void clear ()
CalcType toCalcType (bool convert=true)
bool isZero () const
bool isNotZero () const
operator bool () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
const_iterator cbegin () const
const_iterator cend () const
int compare (UnsignedInteger const &other) const
bool operator== (UnsignedInteger const &other) const
bool operator!= (UnsignedInteger const &other) const
bool operator< (UnsignedInteger const &other) const
bool operator<= (UnsignedInteger const &other) const
bool operator> (UnsignedInteger const &other) const
bool operator>= (UnsignedInteger const &other) const
UnsignedInteger (void const *buf)
template<typename InputIt >
UnsignedInteger (InputIt first, InputIt last)
Static Public Member Functions
template<class UnsignedIntegralType >
static UnsignedInteger createFromInteger (UnsignedIntegralType value)
static UnsignedInteger createFilled (value_type value)
Static Public Attributes
static std::size_t const size = Bytes
Private Member Functions
value_type * get ()
value_type const * get () const
Private Attributes
IntCalcType m_values [CalcCount]
Static Private Attributes
static std::size_t const CalcCount = (Bytes + sizeof (IntCalcType) - 1) / sizeof (IntCalcType)
Detailed Description
template<std::size_t Bytes>
class beast::UnsignedInteger< Bytes >
Represents a set of bits of fixed size.
The data is stored in "canonical" format which is network (big endian) byte order, most significant byte first.
In this implementation the pointer to the beginning of the canonical format may not be aligned.
Definition at line 46 of file UnsignedInteger.h.
Member Typedef Documentation
template<std::size_t Bytes> typedef UnsignedIntegerCalc<IntCalcType> beast::UnsignedInteger< Bytes >::CalcType
Definition at line 56 of file UnsignedInteger.h.
template<std::size_t Bytes> typedef value_type const* beast::UnsignedInteger< Bytes >::const_iterator
Definition at line 61 of file UnsignedInteger.h.
template<std::size_t Bytes> typedef hardened_hash<UnsignedInteger> beast::UnsignedInteger< Bytes >::hasher
Hardened hash function for use with hash based containers. The seed is used to make the hash unpredictable. This prevents attackers from exploiting crafted inputs to produce degenerate containers.
Definition at line 68 of file UnsignedInteger.h.
template<std::size_t Bytes> typedef std::uint32_t beast::UnsignedInteger< Bytes >::IntCalcType
Definition at line 53 of file UnsignedInteger.h.
template<std::size_t Bytes> typedef value_type* beast::UnsignedInteger< Bytes >::iterator
Definition at line 60 of file UnsignedInteger.h.
template<std::size_t Bytes> typedef std::uint8_t beast::UnsignedInteger< Bytes >::value_type
Definition at line 59 of file UnsignedInteger.h.
Constructor & Destructor Documentation
template<std::size_t Bytes> beast::UnsignedInteger< Bytes >::UnsignedInteger () inline
Construct the object. The values are uninitialized.
Definition at line 85 of file UnsignedInteger.h.
     {
     }
template<std::size_t Bytes> beast::UnsignedInteger< Bytes >::UnsignedInteger (UnsignedInteger< Bytes > const & other) inline
Construct a copy.
Definition at line 90 of file UnsignedInteger.h.
References beast::UnsignedInteger< Bytes >::operator=().
     {
         this->operator= (other);
     }
template<std::size_t Bytes> beast::UnsignedInteger< Bytes >::UnsignedInteger (void const * buf) inline explicit
Construct from a raw memory. The area pointed to by buffer must be at least Bytes in size, or else undefined behavior will result.
Definition at line 100 of file UnsignedInteger.h.
References beast::UnsignedInteger< Bytes >::begin(), and beast::UnsignedInteger< Bytes >::m_values.
     {
         m_values [0] = 0; // clear any pad bytes
         std::memcpy (begin(), buf, Bytes);
     }
template<std::size_t Bytes> template<typename InputIt > beast::UnsignedInteger< Bytes >::UnsignedInteger (InputIt first, InputIt last) inline
Definition at line 107 of file UnsignedInteger.h.
References beast::UnsignedInteger< Bytes >::begin(), beast::UnsignedInteger< Bytes >::m_values, and beast::UnsignedInteger< Bytes >::size.
     {
         m_values [0] = 0; // clear any pad bytes
         assert (std::distance (first, last) == size);
         std::copy (first, last, begin());
     }
Member Function Documentation
template<std::size_t Bytes> iterator beast::UnsignedInteger< Bytes >::begin () inline
Get an iterator to the beginning.
Definition at line 195 of file UnsignedInteger.h.
Referenced by beast::HexEncoding::decode(), and beast::UnsignedInteger< Bytes >::UnsignedInteger().
     {
         return get();
     }
template<std::size_t Bytes> const_iterator beast::UnsignedInteger< Bytes >::begin () const inline
Get a const iterator to the beginning.
Definition at line 207 of file UnsignedInteger.h.
     {
         return get();
     }
template<std::size_t Bytes> const_iterator beast::UnsignedInteger< Bytes >::cbegin () const inline
Get a const iterator to the beginning.
Definition at line 219 of file UnsignedInteger.h.
Referenced by beast::UnsignedInteger< Bytes >::compare(), and beast::HexEncoding::encode().
     {
         return get();
     }
template<std::size_t Bytes> const_iterator beast::UnsignedInteger< Bytes >::cend () const inline
Get a const iterator to past-the-end.
Definition at line 225 of file UnsignedInteger.h.
     {
         return get()+Bytes;
     }
template<std::size_t Bytes> void beast::UnsignedInteger< Bytes >::clear () inline
Clear the contents to zero.
Definition at line 156 of file UnsignedInteger.h.
References beast::UnsignedInteger< Bytes >::CalcCount, and beast::UnsignedInteger< Bytes >::m_values.
Referenced by beast::UnsignedInteger< Bytes >::createFromInteger().
     {
         std::fill (m_values, m_values + CalcCount, 0);
     }
template<std::size_t Bytes> int beast::UnsignedInteger< Bytes >::compare (UnsignedInteger< Bytes > const & other) const inline
Compare two objects of equal size. The comparison is performed using a numeric lexicographical comparison.
Definition at line 233 of file UnsignedInteger.h.
References beast::UnsignedInteger< Bytes >::cbegin().
Referenced by beast::UnsignedInteger< Bytes >::operator!=(), beast::UnsignedInteger< Bytes >::equal::operator()(), beast::UnsignedInteger< Bytes >::operator<(), beast::UnsignedInteger< Bytes >::operator<=(), beast::UnsignedInteger< Bytes >::operator==(), beast::UnsignedInteger< Bytes >::operator>(), and beast::UnsignedInteger< Bytes >::operator>=().
     {
         return memcmp (cbegin (), other.cbegin (), Bytes);
     }
template<std::size_t Bytes> static UnsignedInteger beast::UnsignedInteger< Bytes >::createFilled (value_type value) inline static
Construct with a filled value.
Definition at line 140 of file UnsignedInteger.h.
References beast::UnsignedInteger< Bytes >::fill().
     {
         UnsignedInteger result;
         result.fill (value);
         return result;
     }
template<std::size_t Bytes> template<class UnsignedIntegralType > static UnsignedInteger beast::UnsignedInteger< Bytes >::createFromInteger (UnsignedIntegralType value) inline static
Create from an integer type.
Invariant
IntegerType must be an unsigned integer type.
Definition at line 127 of file UnsignedInteger.h.
References beast::UnsignedInteger< Bytes >::clear(), beast::UnsignedInteger< Bytes >::end(), ripple::min(), and value.
     {
         static_assert (Bytes >= sizeof (UnsignedIntegralType),
             "Bytes is too small.");
         UnsignedInteger <Bytes> result;
         value = toNetworkByteOrder <UnsignedIntegralType> (value);
         result.clear ();
         std::memcpy (result.end () - sizeof (value), &value,
             std::min (Bytes, sizeof (value)));
         return result;
     }
template<std::size_t Bytes> iterator beast::UnsignedInteger< Bytes >::end () inline
Get an iterator to past-the-end.
Definition at line 201 of file UnsignedInteger.h.
Referenced by beast::UnsignedInteger< Bytes >::createFromInteger().
     {
         return get()+Bytes;
     }
template<std::size_t Bytes> const_iterator beast::UnsignedInteger< Bytes >::end () const inline
Get a const iterator to past-the-end.
Definition at line 213 of file UnsignedInteger.h.
     {
         return get()+Bytes;
     }
template<std::size_t Bytes> void beast::UnsignedInteger< Bytes >::fill (value_type value) inline
Fill with a particular byte value.
Definition at line 148 of file UnsignedInteger.h.
References beast::UnsignedInteger< Bytes >::CalcCount, and beast::UnsignedInteger< Bytes >::m_values.
Referenced by beast::UnsignedInteger< Bytes >::createFilled().
     {
         IntCalcType c;
         memset (&c, value, sizeof (c));
         std::fill (m_values, m_values + CalcCount, c);
     }
template<std::size_t Bytes> value_type* beast::UnsignedInteger< Bytes >::get () inline private
Definition at line 277 of file UnsignedInteger.h.
References beast::UnsignedInteger< Bytes >::m_values.
     {
         return (reinterpret_cast <value_type*> (&m_values [0])) +
             ((sizeof(IntCalcType)-(Bytes&(sizeof(IntCalcType)-1)))&(sizeof(IntCalcType)-1));
     }
template<std::size_t Bytes> value_type const* beast::UnsignedInteger< Bytes >::get () const inline private
Definition at line 283 of file UnsignedInteger.h.
References beast::UnsignedInteger< Bytes >::m_values.
     {
         return (reinterpret_cast <value_type const*> (&m_values [0])) +
             ((sizeof(IntCalcType)-(Bytes&(sizeof(IntCalcType)-1)))&(sizeof(IntCalcType)-1));
     }
template<std::size_t Bytes> bool beast::UnsignedInteger< Bytes >::isNotZero () const inline
Determine if any bit is non-zero.
Definition at line 180 of file UnsignedInteger.h.
References beast::UnsignedInteger< Bytes >::isZero().
Referenced by beast::UnsignedInteger< Bytes >::operator bool().
     {
         return ! isZero ();
     }
template<std::size_t Bytes> bool beast::UnsignedInteger< Bytes >::isZero () const inline
Determine if all bits are zero.
Definition at line 168 of file UnsignedInteger.h.
References beast::UnsignedInteger< Bytes >::CalcCount, and beast::UnsignedInteger< Bytes >::m_values.
Referenced by beast::UnsignedInteger< Bytes >::isNotZero().
     {
         for (int i = 0; i < CalcCount; ++i)
         {
             if (m_values [i] != 0)
                 return false;
         }
         return true;
     }
template<std::size_t Bytes> beast::UnsignedInteger< Bytes >::operator bool () const inline explicit
Support conversion to bool.
Returns
true if any bit is non-zero.
Definition at line 189 of file UnsignedInteger.h.
References beast::UnsignedInteger< Bytes >::isNotZero().
     {
         return isNotZero ();
     }
template<std::size_t Bytes> bool beast::UnsignedInteger< Bytes >::operator!= (UnsignedInteger< Bytes > const & other) const inline
Determine inequality.
Definition at line 245 of file UnsignedInteger.h.
References beast::UnsignedInteger< Bytes >::compare().
     {
         return compare (other) != 0;
     }
template<std::size_t Bytes> bool beast::UnsignedInteger< Bytes >::operator< (UnsignedInteger< Bytes > const & other) const inline
Ordered comparison.
Definition at line 251 of file UnsignedInteger.h.
References beast::UnsignedInteger< Bytes >::compare().
     {
         return compare (other) < 0;
     }
template<std::size_t Bytes> bool beast::UnsignedInteger< Bytes >::operator<= (UnsignedInteger< Bytes > const & other) const inline
Ordered comparison.
Definition at line 257 of file UnsignedInteger.h.
References beast::UnsignedInteger< Bytes >::compare().
     {
         return compare (other) <= 0;
     }
template<std::size_t Bytes> UnsignedInteger& beast::UnsignedInteger< Bytes >::operator= (UnsignedInteger< Bytes > const & other) inline
Assign from another UnsignedInteger.
Definition at line 116 of file UnsignedInteger.h.
References beast::UnsignedInteger< Bytes >::CalcCount, and beast::UnsignedInteger< Bytes >::m_values.
Referenced by beast::UnsignedInteger< Bytes >::UnsignedInteger().
     {
         // Perform an aligned, all inclusive copy that includes padding.
         std::copy (other.m_values, other.m_values + CalcCount, m_values);
         return *this;
     }
template<std::size_t Bytes> bool beast::UnsignedInteger< Bytes >::operator== (UnsignedInteger< Bytes > const & other) const inline
Determine equality.
Definition at line 239 of file UnsignedInteger.h.
References beast::UnsignedInteger< Bytes >::compare().
     {
         return compare (other) == 0;
     }
template<std::size_t Bytes> bool beast::UnsignedInteger< Bytes >::operator> (UnsignedInteger< Bytes > const & other) const inline
Ordered comparison.
Definition at line 263 of file UnsignedInteger.h.
References beast::UnsignedInteger< Bytes >::compare().
     {
         return compare (other) > 0;
     }
template<std::size_t Bytes> bool beast::UnsignedInteger< Bytes >::operator>= (UnsignedInteger< Bytes > const & other) const inline
Ordered comparison.
Definition at line 269 of file UnsignedInteger.h.
References beast::UnsignedInteger< Bytes >::compare().
     {
         return compare (other) >= 0;
     }
template<std::size_t Bytes> CalcType beast::UnsignedInteger< Bytes >::toCalcType (bool convert = true) inline
Convert to calculation format.
Definition at line 162 of file UnsignedInteger.h.
References beast::UnsignedIntegerCalc< UInt >::fromCanonical(), and beast::UnsignedInteger< Bytes >::m_values.
Referenced by beast::BinaryEncoding::decode(), and beast::BinaryEncoding::encode().
     {
         return CalcType::fromCanonical (m_values, Bytes, convert);
     }
Member Data Documentation
template<std::size_t Bytes> std::size_t const beast::UnsignedInteger< Bytes >::CalcCount = (Bytes + sizeof (IntCalcType) - 1) / sizeof (IntCalcType) static private
Definition at line 275 of file UnsignedInteger.h.
Referenced by beast::UnsignedInteger< Bytes >::clear(), beast::UnsignedInteger< Bytes >::fill(), beast::UnsignedInteger< Bytes >::isZero(), and beast::UnsignedInteger< Bytes >::operator=().
template<std::size_t Bytes> IntCalcType beast::UnsignedInteger< Bytes >::m_values[CalcCount] private
Definition at line 289 of file UnsignedInteger.h.
Referenced by beast::UnsignedInteger< Bytes >::clear(), beast::UnsignedInteger< Bytes >::fill(), beast::UnsignedInteger< Bytes >::get(), beast::UnsignedInteger< Bytes >::isZero(), beast::UnsignedInteger< Bytes >::operator=(), beast::UnsignedInteger< Bytes >::toCalcType(), and beast::UnsignedInteger< Bytes >::UnsignedInteger().
template<std::size_t Bytes> std::size_t const beast::UnsignedInteger< Bytes >::size = Bytes static
Constant for determining the number of bytes.
Definition at line 50 of file UnsignedInteger.h.
Referenced by beast::HexEncoding::encode(), and beast::UnsignedInteger< Bytes >::UnsignedInteger().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/crypto/UnsignedInteger.h