rippled: beast::IPAddressConversion Struct Reference
beast::IPAddressConversion Struct Reference
#include <IPAddressConversion.h>
Static Public Member Functions
static IP::Endpoint from_asio (boost::asio::ip::address const &address)
static IP::Endpoint from_asio (boost::asio::ip::tcp::endpoint const &endpoint)
static boost::asio::ip::address to_asio_address (IP::Endpoint const &address)
static
boost::asio::ip::tcp::endpoint to_asio_endpoint (IP::Endpoint const &address)
Detailed Description
Definition at line 54 of file IPAddressConversion.h.
Member Function Documentation
static IP::Endpoint beast::IPAddressConversion::from_asio (boost::asio::ip::address const & address) inline static
Definition at line 56 of file IPAddressConversion.h.
References beast::IP::from_asio().
Referenced by ripple::OverlayImpl::accept(), ripple::ResolverAsioImpl::do_finish(), ripple::RPCServerImp::handleRequest(), ripple::MultiSocketType< socket_type & >::local_endpoint(), ripple::PeerImp::onConnect(), ripple::PeerDoorImp::PeerDoorImp(), and ripple::MultiSocketType< socket_type & >::remote_endpoint().
         { return IP::from_asio (address); }
static IP::Endpoint beast::IPAddressConversion::from_asio (boost::asio::ip::tcp::endpoint const & endpoint) inline static
Definition at line 58 of file IPAddressConversion.h.
References beast::IP::from_asio().
         { return IP::from_asio (endpoint); }
static boost::asio::ip::address beast::IPAddressConversion::to_asio_address (IP::Endpoint const & address) inline static
Definition at line 60 of file IPAddressConversion.h.
References beast::IP::to_asio_address().
         { return IP::to_asio_address (address); }
static boost::asio::ip::tcp::endpoint beast::IPAddressConversion::to_asio_endpoint (IP::Endpoint const & address) inline static
Definition at line 62 of file IPAddressConversion.h.
References beast::IP::to_asio_endpoint().
Referenced by ripple::PeerImp::connect(), and ripple::PeerFinder::CheckerImp::Request::Request().
         { return IP::to_asio_endpoint (address); }
The documentation for this struct was generated from the following file:
rippled/src/beast/beast/asio/IPAddressConversion.h