rippled: ripple::Validators::Utilities Class Reference
ripple::Validators::Utilities Class Reference
#include <Utilities.h>
Classes
class FollowingVerticalWhite
struct Helpers
class ParseResultLine
Public Types
typedef std::vector< std::string > Strings
Static Public Member Functions
template<typename BidirectionalIterator , typename LineFunction >
static void processLines (BidirectionalIterator first, BidirectionalIterator last, LineFunction f)
static void parseResultLine (Source::Results &results, std::string const &line, beast::Journal journal=beast::Journal())
static beast::String itos (int i, int fieldSize=0)
static int stoi (beast::String &s, int fieldSize, int minValue, int maxValue, beast::beast_wchar delimiter)
static beast::String timeToString (beast::Time const &t)
static beast::Time stringToTime (beast::String s)
static bool parseInfoLine (Source::Item &item, std::string const &line, beast::Journal journal)
Detailed Description
Common code for Validators classes.
Definition at line 27 of file Utilities.h.
Member Typedef Documentation
typedef std::vector<std::string> ripple::Validators::Utilities::Strings
Definition at line 30 of file Utilities.h.
Member Function Documentation
beast::String ripple::Validators::Utilities::itos (int i, int fieldSize = 0) static
Definition at line 139 of file Utilities.cpp.
References beast::String::fromNumber(), and beast::String::paddedLeft().
Referenced by stoi(), and timeToString().
 {
     return beast::String::fromNumber (i).paddedLeft (beast::beast_wchar('0'), fieldSize);
 }
bool ripple::Validators::Utilities::parseInfoLine (Source::Item & item, std::string const & line, beast::Journal journal) static
Parse a string into a Source::Item.
Returns
true on success.
Definition at line 77 of file Utilities.cpp.
References beast::Journal::error, ripple::IdentifierType< RipplePublicKeyTraits >::from_string(), ripple::Validators::Source::Item::label, beast::asio::InputParser::match(), ripple::Validators::Source::Item::publicKey, ripple::Validators::Utilities::Helpers::reComment(), and ripple::Validators::Utilities::Helpers::reInfo().
Referenced by parseResultLine().
 {
     bool success (false);
     boost::smatch match;
     if (boost::regex_match (line, match, Helpers::reInfo ()))
     {
         std::string const encodedKey (match [1]);
         std::string const commentText (match [2]);
         std::pair <RipplePublicKey, bool> results (
             RipplePublicKey::from_string (encodedKey));
         if (results.second)
         {
             // We got a public key.
             item.label = commentText;
             item.publicKey = results.first;
             success = true;
         }
         else
         {
             // Some other junk.
             journal.error << "Invalid RipplePublicKey: '" << encodedKey << "'";
         }
     }
     else if (boost::regex_match (line, match, Helpers::reComment ()))
     {
         // it's a comment
     }
     else
     {
         // Log a warning about a parsing error
         journal.error << "Invalid Validators source line:" << std::endl << line;
     }
     return success;
 }
void ripple::Validators::Utilities::parseResultLine (Source::Results & results, std::string const & line, beast::Journal journal = beast::Journal()) static
Parse a string into the Source::Results. Invalid or comment lines will be skipped. Lines containing validator info will be added to the Results object. Metadata lines will update the corresponding Results fields.
Definition at line 122 of file Utilities.cpp.
References ripple::Validators::Source::Results::list, parseInfoLine(), and ripple::Validators::Source::Results::success.
Referenced by ripple::Validators::SourceStringsImp::fetch(), and ripple::Validators::Utilities::ParseResultLine::operator()().
 {
     Source::Item item;
     bool success = parseInfoLine (item, line, journal);
     if (success)
     {
         results.list.push_back (item);
         results.success = true;
     }
 }
template<typename BidirectionalIterator , typename LineFunction > static void ripple::Validators::Utilities::processLines (BidirectionalIterator first, BidirectionalIterator last, LineFunction f) inline static
Call LineFunction for each newline-separated line in the input. LineFunction will be called with this signature:
void LineFunction (BidirectionalIterator first, BidirectionalIterator last)
Where first and last mark the beginning and ending of the line. The last line in the input may or may not contain the trailing newline.
Definition at line 100 of file Utilities.h.
References ripple::f.
Referenced by ripple::Validators::SourceFileImp::fetch(), and ripple::Validators::SourceURLImp::fetch().
     {
         for (;;)
         {
             BidirectionalIterator split (std::find_if (
                 first, last, FollowingVerticalWhite ()));
             f (first, split);
             if (split == last)
                 break;
             first = split;
         }
     }
int ripple::Validators::Utilities::stoi (beast::String & s, int fieldSize, int minValue, int maxValue, beast::beast_wchar delimiter) static
Definition at line 160 of file Utilities.cpp.
References itos(), and beast::String::substring().
Referenced by stringToTime().
 {
     int const needed (fieldSize + ((delimiter != 0) ? 1 : 0));
     beast::String const v (s.substring (0, needed));
     s = s.substring (v.length ());
     if (s.length() == needed)
     {
         int const v (s.getIntValue());
         if (s.startsWith (itos (v, fieldSize)) &&
             v >= minValue && v <= maxValue &&
             (delimiter == 0 || s.endsWithChar (delimiter)))
         {
             return v;
         }
     }
     return -1; // fail
 }
beast::Time ripple::Validators::Utilities::stringToTime (beast::String s) static
Definition at line 179 of file Utilities.cpp.
References beast::String::isNotEmpty(), ripple::min(), and stoi().
Referenced by ripple::Validators::StoreSqdb::select().
 {
     if (s.isNotEmpty ())
     {
         int const year (stoi (s, 4, 1970, 9999, '-'));
         int const mon  (stoi (s, 2,    0,   11, '-'));
         int const day  (stoi (s, 2,    1,   31, ' '));
         int const hour (stoi (s, 2,    0,   23, ':'));
         int const min  (stoi (s, 2,    0,   59, ':'));
         int const sec  (stoi (s, 2,    0,   59,  0 ));
         if (year != -1 &&
             mon  != -1 &&
             day  != -1 &&
             hour != -1 &&
             min  != -1 &&
             sec  != -1)
         {
             // local time
             return beast::Time (year, mon, day, hour, min, sec, 0, true);
         }
     }
     return beast::Time (0);
 }
beast::String ripple::Validators::Utilities::timeToString (beast::Time const & t) static
Definition at line 144 of file Utilities.cpp.
References beast::String::empty, beast::Time::getDayOfMonth(), beast::Time::getHours(), beast::Time::getMinutes(), beast::Time::getMonth(), beast::Time::getSeconds(), beast::Time::getYear(), beast::Time::isNotNull(), and itos().
Referenced by ripple::Validators::StoreSqdb::insert(), and ripple::Validators::StoreSqdb::update().
 {
     if (t.isNotNull ())
     {
         return
             itos (t.getYear(), 4)        + "-" +
             itos (t.getMonth(), 2)       + "-" +
             itos (t.getDayOfMonth (), 2) + " " +
             itos (t.getHours () , 2)     + ":" +
             itos (t.getMinutes (), 2)    + ":" +
             itos (t.getSeconds(), 2);
     }
     return beast::String::empty;
 }
The documentation for this class was generated from the following files:
rippled/src/ripple/validators/impl/Utilities.h
rippled/src/ripple/validators/impl/Utilities.cpp