rippled: rocksdb::Constructor Class Reference
rocksdb::Constructor Class Reference abstract
Public Member Functions
Constructor (const Comparator *cmp)
virtual ~Constructor ()
void Add (const std::string &key, const Slice &value)
void Finish (const Options &options, std::vector< std::string > *keys, KVMap *kvmap)
virtual Status FinishImpl (const Options &options, const KVMap &data)=0
virtual Iterator * NewIterator () const =0
virtual const KVMap & data ()
virtual DB * db () const
Private Attributes
KVMap data_
Detailed Description
Definition at line 163 of file table_test.cc.
Constructor & Destructor Documentation
rocksdb::Constructor::Constructor (const Comparator * cmp) inline explicit
Definition at line 165 of file table_test.cc.
 : data_(anon::STLLessThan(cmp)) { }
virtual rocksdb::Constructor::~Constructor () inline virtual
Definition at line 166 of file table_test.cc.
 { }
Member Function Documentation
void rocksdb::Constructor::Add (const std::string & key, const Slice & value) inline
Definition at line 168 of file table_test.cc.
References data_, and rocksdb::Slice::ToString().
Referenced by rocksdb::Harness::Add(), rocksdb::Do_Compression_Test(), and rocksdb::TEST().
{
     data_[key] = value.ToString();
   }
virtual const KVMap& rocksdb::Constructor::data () inline virtual
Definition at line 195 of file table_test.cc.
References data_.
 { return data_; }
virtual DB* rocksdb::Constructor::db () const inline virtual
Reimplemented in rocksdb::DBConstructor.
Definition at line 197 of file table_test.cc.
Referenced by rocksdb::Harness::db().
 { return nullptr; }  // Overridden in DBConstructor
void rocksdb::Constructor::Finish (const Options & options, std::vector< std::string > * keys, KVMap * kvmap) inline
Definition at line 175 of file table_test.cc.
References ASSERT_TRUE, data_, FinishImpl(), rocksdb::Status::ok(), and rocksdb::Status::ToString().
Referenced by rocksdb::Do_Compression_Test(), rocksdb::Harness::Test(), and rocksdb::TEST().
{
     *kvmap = data_;
     keys->clear();
     for (KVMap::const_iterator it = data_.begin();
          it != data_.end();
          ++it) {
       keys->push_back(it->first);
     }
     data_.clear();
     Status s = FinishImpl(options, *kvmap);
     ASSERT_TRUE(s.ok()) << s.ToString();
   }
virtual Status rocksdb::Constructor::FinishImpl (const Options & options, const KVMap & data) pure virtual
Implemented in rocksdb::DBConstructor, rocksdb::MemTableConstructor, rocksdb::BlockBasedTableConstructor, and rocksdb::BlockConstructor.
Referenced by Finish().
virtual Iterator* rocksdb::Constructor::NewIterator () const pure virtual
Implemented in rocksdb::DBConstructor, rocksdb::MemTableConstructor, rocksdb::BlockBasedTableConstructor, and rocksdb::BlockConstructor.
Referenced by rocksdb::Harness::TestBackwardScan(), rocksdb::Harness::TestForwardScan(), and rocksdb::Harness::TestRandomAccess().
Member Data Documentation
KVMap rocksdb::Constructor::data_ private
Definition at line 200 of file table_test.cc.
Referenced by Add(), data(), and Finish().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/table/table_test.cc