rippled: beast::IP::Address Class Reference
beast::IP::Address Class Reference
#include <IPAddress.h>
Public Member Functions
Address ()
Address (AddressV4 const &addr)
Address (AddressV6 const &addr)
std::string to_string () const
bool is_v4 () const
bool is_v6 () const
AddressV4 const & to_v4 () const
AddressV6 const & to_v6 () const
Address & operator= (AddressV4 const &addr)
Address & operator= (AddressV6 const &addr)
Static Public Member Functions
static std::pair< Address, bool > from_string (std::string const &s)
Private Types
enum Type { ipv4, ipv6 }
Private Attributes
Type m_type
AddressV4 m_v4
AddressV6 m_v6
Friends
template<class Hasher >
void hash_append (Hasher &h, Address const &addr)
bool operator== (Address const &lhs, Address const &rhs)
bool operator< (Address const &lhs, Address const &rhs)
bool operator!= (Address const &lhs, Address const &rhs)
bool operator> (Address const &lhs, Address const &rhs)
bool operator<= (Address const &lhs, Address const &rhs)
bool operator>= (Address const &lhs, Address const &rhs)
Detailed Description
A version-independent IP address. This object can represent either an IPv4 or IPv6 address.
Definition at line 41 of file IPAddress.h.
Member Enumeration Documentation
enum beast::IP::Address::Type private
Enumerator
ipv4
ipv6
Definition at line 213 of file IPAddress.h.
     {
         ipv4,
         ipv6
     };
Constructor & Destructor Documentation
beast::IP::Address::Address () inline
Create an unspecified IPv4 address.
Definition at line 45 of file IPAddress.h.
         : m_type (ipv4)
     {
     }
beast::IP::Address::Address (AddressV4 const & addr) inline
Create an IPv4 address.
Definition at line 51 of file IPAddress.h.
         : m_type (ipv4)
         , m_v4 (addr)
     {
     }
beast::IP::Address::Address (AddressV6 const & addr) inline
Create an IPv6 address.
Definition at line 58 of file IPAddress.h.
         : m_type (ipv6)
         , m_v6 (addr)
     {
     }
Member Function Documentation
std::pair< Address, bool > beast::IP::Address::from_string (std::string const & s) inline static
Create an Address from a string.
Returns
A pair with the address, and bool set to true on success.
Definition at line 318 of file IPAddress.h.
Referenced by beast::IP::IPEndpoint_test::testAddress().
 {
     std::stringstream is (s);
     Address addr;
     is >> addr;
     if (! is.fail() && is.rdbuf()->in_avail() == 0)
         return std::make_pair (addr, true);
     return std::make_pair (Address (), false);
 }
bool beast::IP::Address::is_v4 () const inline
Returns true if this address represents an IPv4 address.
Definition at line 103 of file IPAddress.h.
References ipv4, and m_type.
Referenced by beast::IP::hash_value(), beast::IP::is_loopback(), beast::IP::is_multicast(), beast::IP::is_private(), beast::IP::is_public(), beast::IP::is_unspecified(), beast::IP::Endpoint::is_v4(), beast::IP::to_asio_address(), and to_string().
     {
         return m_type == ipv4;
     }
bool beast::IP::Address::is_v6 () const inline
Returns true if this address represents an IPv6 address.
Definition at line 110 of file IPAddress.h.
References ipv6, and m_type.
Referenced by beast::IP::Endpoint::is_v6().
     {
         return m_type == ipv6;
     }
Address& beast::IP::Address::operator= (AddressV4 const & addr) inline
Assign a copy from another address in any format.
Definition at line 67 of file IPAddress.h.
References ipv4, m_type, m_v4, and m_v6.
     {
         m_type = ipv4;
         m_v6 = AddressV6();
         m_v4 = addr;
         return *this;
     }
Address& beast::IP::Address::operator= (AddressV6 const & addr) inline
Definition at line 76 of file IPAddress.h.
References ipv6, m_type, m_v4, and m_v6.
     {
         m_type = ipv6;
         m_v4 = AddressV4();
         m_v6 = addr;
         return *this;
     }
std::string beast::IP::Address::to_string () const inline
Returns a string representing the address.
Definition at line 94 of file IPAddress.h.
References is_v4(), beast::IP::to_string(), to_v4(), and to_v6().
Referenced by beast::IP::to_string().
     {
         return (is_v4 ())
             ? IP::to_string (to_v4())
             : IP::to_string (to_v6());
     }
AddressV4 const& beast::IP::Address::to_v4 () const inline
Returns the IPv4 address. Precondition: is_v4() == true
Definition at line 120 of file IPAddress.h.
References ipv4, m_type, and m_v4.
Referenced by beast::IP::hash_value(), beast::IP::is_loopback(), beast::IP::is_multicast(), beast::IP::is_private(), beast::IP::is_public(), beast::IP::is_unspecified(), beast::IP::to_asio_address(), to_string(), and beast::IP::Endpoint::to_v4().
     {
         if (m_type != ipv4)
             throw std::bad_cast();
         return m_v4;
     }
AddressV6 const& beast::IP::Address::to_v6 () const inline
Returns the IPv6 address. Precondition: is_v6() == true
Definition at line 133 of file IPAddress.h.
References ipv6, m_type, and m_v6.
Referenced by beast::IP::hash_value(), beast::IP::is_loopback(), beast::IP::is_multicast(), beast::IP::is_private(), beast::IP::is_public(), beast::IP::is_unspecified(), to_string(), and beast::IP::Endpoint::to_v6().
     {
         if (m_type != ipv6)
             throw std::bad_cast();
         return m_v6;
     }
Friends And Related Function Documentation
template<class Hasher > void hash_append (Hasher & h, Address const & addr) friend
Definition at line 143 of file IPAddress.h.
     {
         using beast::hash_append;
         if (addr.is_v4 ())
             hash_append(h, addr.to_v4 ());
         else
             hash_append(h, addr.to_v6 ());
     }
bool operator!= (Address const & lhs, Address const & rhs) friend
Definition at line 185 of file IPAddress.h.
     {
         return ! (lhs == rhs);
     }
bool operator< (Address const & lhs, Address const & rhs) friend
Definition at line 174 of file IPAddress.h.
     {
         if (lhs.m_type < rhs.m_type)
             return true;
         if (lhs.is_v4 ())
             return lhs.to_v4() < rhs.to_v4();
         return lhs.to_v6() < rhs.to_v6();
     }
bool operator<= (Address const & lhs, Address const & rhs) friend
Definition at line 199 of file IPAddress.h.
     {
         return ! (lhs > rhs);
     }
bool operator== (Address const & lhs, Address const & rhs) friend
Arithmetic comparison.
Definition at line 156 of file IPAddress.h.
     {
         if (lhs.is_v4 ())
         {
             if (rhs.is_v4 ())
                 return lhs.to_v4() == rhs.to_v4();
         }
         else
         {
             if (rhs.is_v6 ())
                 return lhs.to_v6() == rhs.to_v6();
         }
         return false;
     }
bool operator> (Address const & lhs, Address const & rhs) friend
Definition at line 192 of file IPAddress.h.
     {
         return rhs < lhs;
     }
bool operator>= (Address const & lhs, Address const & rhs) friend
Definition at line 206 of file IPAddress.h.
     {
         return ! (rhs > lhs);
     }
Member Data Documentation
Type beast::IP::Address::m_type private
Definition at line 219 of file IPAddress.h.
Referenced by is_v4(), is_v6(), operator=(), to_v4(), and to_v6().
AddressV4 beast::IP::Address::m_v4 private
Definition at line 220 of file IPAddress.h.
Referenced by operator=(), and to_v4().
AddressV6 beast::IP::Address::m_v6 private
Definition at line 221 of file IPAddress.h.
Referenced by operator=(), and to_v6().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/net/IPAddress.h