rippled: rocksdb::LDBCommandExecuteResult Class Reference
rocksdb::LDBCommandExecuteResult Class Reference
#include <ldb_cmd_execute_result.h>
Public Types
enum State { EXEC_NOT_STARTED = 0, EXEC_SUCCEED = 1, EXEC_FAILED = 2 }
Public Member Functions
LDBCommandExecuteResult ()
LDBCommandExecuteResult (State state, std::string &msg)
std::string ToString ()
void Reset ()
bool IsSucceed ()
bool IsNotStarted ()
bool IsFailed ()
Static Public Member Functions
static LDBCommandExecuteResult SUCCEED (std::string msg)
static LDBCommandExecuteResult FAILED (std::string msg)
Private Member Functions
bool operator== (const LDBCommandExecuteResult &)
bool operator!= (const LDBCommandExecuteResult &)
Private Attributes
State state_
std::string message_
Detailed Description
Definition at line 10 of file ldb_cmd_execute_result.h.
Member Enumeration Documentation
enum rocksdb::LDBCommandExecuteResult::State
Enumerator
EXEC_NOT_STARTED
EXEC_SUCCEED
EXEC_FAILED
Definition at line 12 of file ldb_cmd_execute_result.h.
              {
     EXEC_NOT_STARTED = 0, EXEC_SUCCEED = 1, EXEC_FAILED = 2,
   };
Constructor & Destructor Documentation
rocksdb::LDBCommandExecuteResult::LDBCommandExecuteResult () inline
Definition at line 16 of file ldb_cmd_execute_result.h.
References EXEC_NOT_STARTED, message_, and state_.
Referenced by FAILED(), and SUCCEED().
{
     state_ = EXEC_NOT_STARTED;
     message_ = "";
   }
rocksdb::LDBCommandExecuteResult::LDBCommandExecuteResult (State state, std::string & msg) inline
Definition at line 21 of file ldb_cmd_execute_result.h.
References message_, and state_.
{
     state_ = state;
     message_ = msg;
   }
Member Function Documentation
static LDBCommandExecuteResult rocksdb::LDBCommandExecuteResult::FAILED (std::string msg) inline static
Definition at line 64 of file ldb_cmd_execute_result.h.
References EXEC_FAILED, and LDBCommandExecuteResult().
Referenced by rocksdb::DBDumperCommand::DoCommand(), rocksdb::InternalDumpCommand::DoCommand(), rocksdb::ManifestDumpCommand::DoCommand(), rocksdb::ReduceDBLevelsCommand::DoCommand(), rocksdb::ChangeCompactionStyleCommand::DoCommand(), rocksdb::WALDumperCommand::DoCommand(), rocksdb::GetCommand::DoCommand(), rocksdb::ScanCommand::DoCommand(), rocksdb::if(), rocksdb::max_keys_scanned_(), rocksdb::new_compaction_style_(), rocksdb::LDBCommand::OpenDB(), rocksdb::LDBCommand::ParseIntOption(), rocksdb::path_(), rocksdb::LDBCommand::PrepareOptionsForOpenDB(), rocksdb::print_old_levels_(), rocksdb::print_stats_(), and rocksdb::print_values_().
{
     return LDBCommandExecuteResult(EXEC_FAILED, msg);
   }
bool rocksdb::LDBCommandExecuteResult::IsFailed () inline
Definition at line 56 of file ldb_cmd_execute_result.h.
References EXEC_FAILED, and state_.
Referenced by rocksdb::LDBCommandRunner::RunCommand().
                   {
     return state_ == EXEC_FAILED;
   }
bool rocksdb::LDBCommandExecuteResult::IsNotStarted () inline
Definition at line 52 of file ldb_cmd_execute_result.h.
References EXEC_NOT_STARTED, and state_.
Referenced by rocksdb::LDBCommand::OpenDB(), and rocksdb::LDBCommand::Run().
                       {
     return state_ == EXEC_NOT_STARTED;
   }
bool rocksdb::LDBCommandExecuteResult::IsSucceed () inline
Definition at line 48 of file ldb_cmd_execute_result.h.
References EXEC_SUCCEED, and state_.
Referenced by rocksdb::ReduceLevelTest::ReduceLevels().
                    {
     return state_ == EXEC_SUCCEED;
   }
bool rocksdb::LDBCommandExecuteResult::operator!= (const LDBCommandExecuteResult &) private
bool rocksdb::LDBCommandExecuteResult::operator== (const LDBCommandExecuteResult &) private
void rocksdb::LDBCommandExecuteResult::Reset () inline
Definition at line 43 of file ldb_cmd_execute_result.h.
References EXEC_NOT_STARTED, message_, and state_.
Referenced by rocksdb::LDBCommand::ClearPreviousRunState().
                {
     state_ = EXEC_NOT_STARTED;
     message_ = "";
   }
static LDBCommandExecuteResult rocksdb::LDBCommandExecuteResult::SUCCEED (std::string msg) inline static
Definition at line 60 of file ldb_cmd_execute_result.h.
References EXEC_SUCCEED, and LDBCommandExecuteResult().
Referenced by rocksdb::CompactorCommand::DoCommand(), and rocksdb::LDBCommand::Run().
{
     return LDBCommandExecuteResult(EXEC_SUCCEED, msg);
   }
std::string rocksdb::LDBCommandExecuteResult::ToString () inline
Definition at line 26 of file ldb_cmd_execute_result.h.
References EXEC_FAILED, EXEC_NOT_STARTED, EXEC_SUCCEED, message_, and state_.
Referenced by rocksdb::LDBCommandRunner::RunCommand().
{
     std::string ret;
     switch (state_) {
     case EXEC_SUCCEED:
       break;
     case EXEC_FAILED:
       ret.append("Failed: ");
       break;
     case EXEC_NOT_STARTED:
       ret.append("Not started: ");
     }
     if (!message_.empty()) {
       ret.append(message_);
     }
     return ret;
   }
Member Data Documentation
std::string rocksdb::LDBCommandExecuteResult::message_ private
Definition at line 70 of file ldb_cmd_execute_result.h.
Referenced by LDBCommandExecuteResult(), Reset(), and ToString().
State rocksdb::LDBCommandExecuteResult::state_ private
Definition at line 69 of file ldb_cmd_execute_result.h.
Referenced by IsFailed(), IsNotStarted(), IsSucceed(), LDBCommandExecuteResult(), Reset(), and ToString().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/util/ldb_cmd_execute_result.h