rippled: ripple::WalletAddTransactor Class Reference
ripple::WalletAddTransactor Class Reference
#include <WalletAddTransactor.h>
Public Member Functions
WalletAddTransactor (SerializedTransaction const &txn, TransactionEngineParams params, TransactionEngine *engine)
TER doApply ()
Public Member Functions inherited from ripple::Transactor
TER apply ()
Additional Inherited Members
Static Public Member Functions inherited from ripple::Transactor
static std::unique_ptr
< Transactor > makeTransactor (SerializedTransaction const &txn, TransactionEngineParams params, TransactionEngine *engine)
Protected Member Functions inherited from ripple::Transactor
virtual TER preCheck ()
virtual TER checkSeq ()
virtual TER payFee ()
void calculateFee ()
virtual std::uint64_t calculateBaseFee ()
virtual TER checkSig ()
Transactor (const SerializedTransaction &txn, TransactionEngineParams params, TransactionEngine *engine, beast::Journal journal=beast::Journal())
virtual bool mustHaveValidAccount ()
Protected Attributes inherited from ripple::Transactor
SerializedTransaction const & mTxn
TransactionEngine * mEngine
TransactionEngineParams mParams
uint160 mTxnAccountID
STAmount mFeeDue
STAmount mPriorBalance
STAmount mSourceBalance
SLE::pointer mTxnAccount
bool mHasAuthKey
bool mSigMaster
RippleAddress mSigningPubKey
beast::Journal m_journal
Detailed Description
Definition at line 34 of file WalletAddTransactor.h.
Constructor & Destructor Documentation
ripple::WalletAddTransactor::WalletAddTransactor (SerializedTransaction const & txn, TransactionEngineParams params, TransactionEngine * engine) inline
Definition at line 38 of file WalletAddTransactor.h.
         : Transactor (
             txn,
             params,
             engine,
             LogPartition::getJournal <WalletAddTransactorLog> ())
     {
     }
Member Function Documentation
TER ripple::WalletAddTransactor::doApply () virtual
Implements ripple::Transactor.
Definition at line 22 of file WalletAddTransactor.cpp.
References ripple::RippleAddress::createAccountPublic(), ripple::TransactionEngine::entryCache(), ripple::TransactionEngine::entryCreate(), ripple::Ledger::getAccountRootIndex(), ripple::STObject::getFieldAccount160(), ripple::STObject::getFieldAmount(), ripple::STObject::getFieldVL(), ripple::STObject::getFlags(), ripple::TransactionEngine::getLedger(), ripple::Serializer::getSHA512Half(), ripple::STAmount::getText(), ripple::SerializedTransaction::getTransactionFee(), ripple::ltACCOUNT_ROOT, ripple::Transactor::m_journal, ripple::Transactor::mEngine, ripple::Transactor::mTxn, ripple::Transactor::mTxnAccount, ripple::tecUNFUNDED_ADD, ripple::tefBAD_ADD_AUTH, ripple::tefCREATED, ripple::temINVALID_FLAG, ripple::tesSUCCESS, ripple::tfUniversalMask, and beast::Journal::trace.
 {
     std::uint32_t const uTxFlags = mTxn.getFlags ();
     if (uTxFlags & tfUniversalMask)
     {
         m_journal.trace <<
             "Malformed transaction: Invalid flags set.";
         return temINVALID_FLAG;
     }
     Blob const vucPubKey    = mTxn.getFieldVL (sfPublicKey);
     Blob const vucSignature = mTxn.getFieldVL (sfSignature);
     uint160 const uAuthKeyID (mTxn.getFieldAccount160 (sfRegularKey));
     RippleAddress const naMasterPubKey (
         RippleAddress::createAccountPublic (vucPubKey));
     uint160 const uDstAccountID (naMasterPubKey.getAccountID ());
     // FIXME: This should be moved to the transaction's signature check logic and cached
     if (!naMasterPubKey.accountPublicVerify (
         Serializer::getSHA512Half (uAuthKeyID.begin (), uAuthKeyID.size ()),
         vucSignature, ECDSA::not_strict))
     {
         m_journal.trace <<
             "Unauthorized: bad signature ";
         return tefBAD_ADD_AUTH;
     }
     SLE::pointer sleDst (mEngine->entryCache (
         ltACCOUNT_ROOT, Ledger::getAccountRootIndex (uDstAccountID)));
     if (sleDst)
     {
         m_journal.trace <<
             "account already created";
         return tefCREATED;
     }
     // Direct XRP payment.
     STAmount saDstAmount = mTxn.getFieldAmount (sfAmount);
     STAmount saPaid = mTxn.getTransactionFee ();
     STAmount const saSrcBalance = mTxnAccount->getFieldAmount (sfBalance);
     std::uint32_t const uOwnerCount = mTxnAccount->getFieldU32 (sfOwnerCount);
     std::uint64_t const uReserve = mEngine->getLedger ()->getReserve (uOwnerCount);
     // Make sure have enough reserve to send. Allow final spend to use reserve
     // for fee.
     // Note: Reserve is not scaled by fee.
     if (saSrcBalance + saPaid < saDstAmount + uReserve)
     {
         // Vote no. However, transaction might succeed, if applied in a
         // different order.
         m_journal.trace <<
             "Delay transaction: Insufficient funds: %s / %s (%d)" <<
             saSrcBalance.getText () << " / " <<
             (saDstAmount + uReserve).getText () << " with reserve = " <<
             uReserve;
         return tecUNFUNDED_ADD;
     }
     // Deduct initial balance from source account.
     mTxnAccount->setFieldAmount (sfBalance, saSrcBalance - saDstAmount);
     // Create the account.
     sleDst  = mEngine->entryCreate (ltACCOUNT_ROOT,
         Ledger::getAccountRootIndex (uDstAccountID));
     sleDst->setFieldAccount (sfAccount, uDstAccountID);
     sleDst->setFieldU32 (sfSequence, 1);
     sleDst->setFieldAmount (sfBalance, saDstAmount);
     sleDst->setFieldAccount (sfRegularKey, uAuthKeyID);
     return tesSUCCESS;
 }
The documentation for this class was generated from the following files:
rippled/src/ripple_app/transactors/WalletAddTransactor.h
rippled/src/ripple_app/transactors/WalletAddTransactor.cpp