rippled: beast::ServiceQueue_test Class Reference
beast::ServiceQueue_test Class Reference
Classes
struct ServiceThread
Public Member Functions
void testThreads (int n)
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Static Public Attributes
static std::size_t const totalCalls = 10000
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 202 of file ServiceQueue.cpp.
Member Function Documentation
void beast::ServiceQueue_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 285 of file ServiceQueue.cpp.
References testThreads().
     {
         testThreads (1);
         testThreads (4);
         testThreads (16);
     }
void beast::ServiceQueue_test::testThreads (int n) inline
Definition at line 261 of file ServiceQueue.cpp.
References beast::ServiceQueueType< Allocator >::dispatch(), beast::ServiceQueue_test::ServiceThread::handler(), beast::unit_test::suite::pass(), beast::ServiceQueue_test::ServiceThread::stop_one(), beast::unit_test::suite::testcase(), and totalCalls.
Referenced by run().
     {
         std::stringstream ss;
         ss << n << " threads";
         testcase (ss.str());
         Random r;
         std::size_t const callsPerThread (totalCalls / n);
         ServiceQueue service (n);
         std::vector <std::unique_ptr <ServiceThread> > threads;
         threads.reserve (n);
         for (int i = 0; i < n; ++i)
             threads.emplace_back (new ServiceThread (i + 1,
                 r.nextInt64(), service));
         for (std::size_t i = n * callsPerThread; i; --i)
             service.dispatch (std::bind (&ServiceThread::handler));
         for (std::size_t i = 0; i < threads.size(); ++i)
             service.dispatch (std::bind (&ServiceThread::stop_one));
         for (std::size_t i = 0; i < threads.size(); ++i)
             threads[i]->waitForThreadToExit();
         pass();
     }
Member Data Documentation
std::size_t const beast::ServiceQueue_test::totalCalls = 10000 static
Definition at line 259 of file ServiceQueue.cpp.
Referenced by testThreads().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/threads/tests/ServiceQueue.cpp