rippled: ripple::Serializer_test Class Reference
ripple::Serializer_test Class Reference
Public Member Functions
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 691 of file Serializer.cpp.
Member Function Documentation
void ripple::Serializer_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 694 of file Serializer.cpp.
References ripple::Serializer::add256(), ripple::Serializer::add32(), ripple::Serializer::addRaw(), beast::unit_test::suite::expect(), ripple::Serializer::getPrefixHash(), ripple::Serializer::getSHA512Half(), and ripple::Serializer::peekData().
     {
         Serializer s1;
         s1.add32 (3);
         s1.add256 (uint256 ());
         Serializer s2;
         s2.add32 (0x12345600);
         s2.addRaw (s1.peekData ());
         expect (s1.getPrefixHash (0x12345600) == s2.getSHA512Half ());
     }
The documentation for this class was generated from the following file:
rippled/src/ripple_data/protocol/Serializer.cpp