rippled: beast::WaitableEvent Class Reference
beast::WaitableEvent Class Reference
#include <WaitableEvent.h>
Public Member Functions
WaitableEvent (bool manualReset=false, bool initiallySignaled=false)
~WaitableEvent ()
void signal () const
void reset () const
bool wait () const
bool wait (int timeOutMilliseconds) const
Private Attributes
pthread_cond_t condition
pthread_mutex_t mutex
bool triggered
bool manualReset
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
Allows threads to wait for events triggered by other threads. A thread can call wait() on a WaitableEvent, and this will suspend the calling thread until another thread wakes it up by calling the signal() method.
Definition at line 41 of file WaitableEvent.h.
Constructor & Destructor Documentation
beast::WaitableEvent::WaitableEvent (bool manualReset = false, bool initiallySignaled = false) explicit
Creates a WaitableEvent object.
Parameters
manualReset If this is false, the event will be reset automatically when the wait() method is called. If manualReset is true, then once the event is signalled, the only way to reset it will be by calling the reset() method.
initiallySignaled If this is true then the event will be signaled when the constructor returns.
Definition at line 76 of file WaitableEvent.cpp.
References condition, mutex, and signal().
     : triggered (false), manualReset (useManualReset)
 {
     pthread_cond_init (&condition, 0);
     pthread_mutexattr_t atts;
     pthread_mutexattr_init (&atts);
    #if ! BEAST_ANDROID
     pthread_mutexattr_setprotocol (&atts, PTHREAD_PRIO_INHERIT);
    #endif
     pthread_mutex_init (&mutex, &atts);
     if (initiallySignaled)
         signal ();
 }
beast::WaitableEvent::~WaitableEvent ()
Destructor.
If other threads are waiting on this object when it gets deleted, this can cause nasty errors, so be careful!
Definition at line 92 of file WaitableEvent.cpp.
References condition, and mutex.
 {
     pthread_cond_destroy (&condition);
     pthread_mutex_destroy (&mutex);
 }
Member Function Documentation
void beast::WaitableEvent::reset () const
Resets the event to an unsignalled state.
If it's not already signalled, this does nothing.
Definition at line 159 of file WaitableEvent.cpp.
References mutex, and triggered.
Referenced by beast::asio::HTTPClientType::add(), and ripple::ResolverAsioImpl::start().
 {
     pthread_mutex_lock (&mutex);
     triggered = false;
     pthread_mutex_unlock (&mutex);
 }
void beast::WaitableEvent::signal () const
Wakes up any threads that are currently waiting on this object.
If signal() is called when nothing is waiting, the next thread to call wait() will return immediately and reset the signal.
If the WaitableEvent is manual reset, all current and future threads that wait upon this object will be woken, until reset() is explicitly called.
If the WaitableEvent is automatic reset, and one or more threads is waiting upon the object, then one of them will be woken up. If no threads are currently waiting, then the next thread to call wait() will be woken up. As soon as a thread is woken, the signal is automatically reset.
See Also
wait, reset
Definition at line 151 of file WaitableEvent.cpp.
References condition, mutex, and triggered.
Referenced by ripple::ResolverAsioImpl::asyncHandlersComplete(), beast::asio::TestPeerType< Logic, Details >::do_listen(), beast::asio::TestPeerType< Logic, Details >::finished(), beast::Thread::notify(), beast::asio::HTTPClientType::remove(), ripple::HTTP::ServerImpl::run(), beast::ServiceQueueBase::Waiter::signal(), ripple::ApplicationImp::signalStop(), beast::Thread::startThread(), beast::Stoppable::stopped(), and WaitableEvent().
 {
     pthread_mutex_lock (&mutex);
     triggered = true;
     pthread_cond_broadcast (&condition);
     pthread_mutex_unlock (&mutex);
 }
bool beast::WaitableEvent::wait () const
Suspends the calling thread until the event has been signalled.
This will wait until the object's signal() method is called by another thread, or until the timeout expires.
After the event has been signalled, this method will return true and if manualReset was set to false in the WaitableEvent's constructor, then the event will be reset.
Parameters
timeOutMilliseconds the maximum time to wait, in milliseconds. A negative value will cause it to wait forever.
Returns
true if the object has been signalled, false if the timeout expires first.
See Also
signal, reset
Definition at line 98 of file WaitableEvent.cpp.
Referenced by beast::asio::TestPeerType< Logic, Details >::join(), beast::Workers::pauseAllThreadsAndWait(), ripple::ApplicationImp::run(), beast::asio::TestPeerType< Logic, Details >::start(), ripple::HTTP::ServerImpl::stop(), ripple::ResolverAsioImpl::stop(), beast::Stoppable::stopRecursive(), beast::Thread::threadEntryPoint(), beast::asio::HTTPClientType::wait(), beast::Thread::wait(), and beast::ServiceQueueBase::Waiter::wait().
 {
     return wait (-1);
 }
bool beast::WaitableEvent::wait (int timeOutMilliseconds) const
Definition at line 103 of file WaitableEvent.cpp.
References condition, manualReset, mutex, and triggered.
 {
     pthread_mutex_lock (&mutex);
     if (! triggered)
     {
         if (timeOutMillisecs < 0)
         {
             do
             {
                 pthread_cond_wait (&condition, &mutex);
             }
             while (! triggered);
         }
         else
         {
             struct timeval now;
             gettimeofday (&now, 0);
             struct timespec time;
             time.tv_sec  = now.tv_sec  + (timeOutMillisecs / 1000);
             time.tv_nsec = (now.tv_usec + ((timeOutMillisecs % 1000) * 1000)) * 1000;
             if (time.tv_nsec >= 1000000000)
             {
                 time.tv_nsec -= 1000000000;
                 time.tv_sec++;
             }
             do
             {
                 if (pthread_cond_timedwait (&condition, &mutex, &time) == ETIMEDOUT)
                 {
                     pthread_mutex_unlock (&mutex);
                     return false;
                 }
             }
             while (! triggered);
         }
     }
     if (! manualReset)
         triggered = false;
     pthread_mutex_unlock (&mutex);
     return true;
 }
Member Data Documentation
pthread_cond_t beast::WaitableEvent::condition mutable private
Definition at line 115 of file WaitableEvent.h.
Referenced by signal(), wait(), WaitableEvent(), and ~WaitableEvent().
bool beast::WaitableEvent::manualReset mutable private
Definition at line 118 of file WaitableEvent.h.
Referenced by wait().
pthread_mutex_t beast::WaitableEvent::mutex mutable private
Definition at line 116 of file WaitableEvent.h.
Referenced by reset(), signal(), wait(), WaitableEvent(), and ~WaitableEvent().
bool beast::WaitableEvent::triggered mutable private
Definition at line 117 of file WaitableEvent.h.
Referenced by reset(), signal(), and wait().
The documentation for this class was generated from the following files:
rippled/src/beast/beast/threads/WaitableEvent.h
rippled/src/beast/beast/threads/impl/WaitableEvent.cpp