rippled: ripple::NodeStore::NodeStoreTiming_test Class Reference
ripple::NodeStore::NodeStoreTiming_test Class Reference
Classes
class Stopwatch
Public Types
enum { numObjectsToTest = 10000 }
Public Types inherited from ripple::NodeStore::TestBase
enum { maxPayloadBytes = 2000, numObjectsToTest = 2000 }
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Member Functions
void testBackend (beast::String type, std::int64_t const seedValue)
void run ()
Public Member Functions inherited from ripple::NodeStore::TestBase
void storeBatch (Backend &backend, Batch const &batch)
void fetchCopyOfBatch (Backend &backend, Batch *pCopy, Batch const &batch)
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Additional Inherited Members
Static Public Member Functions inherited from ripple::NodeStore::TestBase
static void createPredictableBatch (Batch &batch, int startingIndex, int numObjects, std::int64_t seedValue)
static bool areBatchesEqual (Batch const &lhs, Batch const &rhs)
static void storeBatch (Database &db, Batch const &batch)
static void fetchCopyOfBatch (Database &db, Batch *pCopy, Batch const &batch)
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 23 of file TimingTests.cpp.
Member Enumeration Documentation
anonymous enum
Enumerator
numObjectsToTest
Definition at line 26 of file TimingTests.cpp.
     {
         numObjectsToTest     = 10000
     };
Member Function Documentation
void ripple::NodeStore::NodeStoreTiming_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 111 of file TimingTests.cpp.
References testBackend().
     {
         int const seedValue = 50;
         testBackend ("leveldb", seedValue);
     #if RIPPLE_HYPERLEVELDB_AVAILABLE
         testBackend ("hyperleveldb", seedValue);
     #endif
     #if RIPPLE_ROCKSDB_AVAILABLE
         testBackend ("rocksdb", seedValue);
     #endif
     #if RIPPLE_ENABLE_SQLITE_BACKEND_TESTS
         testBackend ("sqlite", seedValue);
     #endif
     }
void ripple::NodeStore::NodeStoreTiming_test::testBackend (beast::String type, std::int64_t const seedValue) inline
Definition at line 56 of file TimingTests.cpp.
References ripple::NodeStore::TestBase::createPredictableBatch(), beast::File::createTempFile(), ripple::NodeStore::TestBase::fetchCopyOfBatch(), beast::File::getFullPathName(), beast::unit_test::suite::log, ripple::NodeStore::make_Manager(), numObjectsToTest, beast.util.CleanCPPFiles::path, ripple::NodeStore::TestBase::storeBatch(), beast::unit_test::suite::testcase(), and beast::String::toStdString().
Referenced by run().
     {
         std::unique_ptr <Manager> manager (make_Manager ());
         DummyScheduler scheduler;
         beast::String s;
         s << "Testing backend '" << type << "' performance";
         testcase (s.toStdString());
         beast::StringPairArray params;
         beast::File const path (beast::File::createTempFile ("node_db"));
         params.set ("type", type);
         params.set ("path", path.getFullPathName ());
         // Create batches
         NodeStore::Batch batch1;
         createPredictableBatch (batch1, 0, numObjectsToTest, seedValue);
         NodeStore::Batch batch2;
         createPredictableBatch (batch2, 0, numObjectsToTest, seedValue);
         beast::Journal j;
         // Open the backend
         std::unique_ptr <Backend> backend (manager->make_Backend (
             params, scheduler, j));
         Stopwatch t;
         // Individual write batch test
         t.start ();
         storeBatch (*backend, batch1);
         s = "";
         s << "  Single write: " << beast::String (t.getElapsed (), 2) << " seconds";
         log << s.toStdString();
         // Bulk write batch test
         t.start ();
         backend->storeBatch (batch2);
         s = "";
         s << "  Batch write:  " << beast::String (t.getElapsed (), 2) << " seconds";
         log << s.toStdString();
         // Read test
         Batch copy;
         t.start ();
         fetchCopyOfBatch (*backend, &copy, batch1);
         fetchCopyOfBatch (*backend, &copy, batch2);
         s = "";
         s << "  Batch read:   " << beast::String (t.getElapsed (), 2) << " seconds";
         log << s.toStdString();
     }
The documentation for this class was generated from the following file:
rippled/src/ripple_core/nodestore/tests/TimingTests.cpp