rippled: ripple::JobQueue Class Reference
ripple::JobQueue Class Reference abstract
#include <JobQueue.h>
Public Member Functions
virtual ~JobQueue ()
virtual void addJob (JobType type, std::string const &name, boost::function< void(Job &)> const &job)=0
virtual int getJobCount (JobType t)=0
virtual int getJobCountTotal (JobType t)=0
virtual int getJobCountGE (JobType t)=0
virtual void shutdown ()=0
virtual void setThreadCount (int c, bool const standaloneMode)=0
virtual LoadEvent::pointer getLoadEvent (JobType t, const std::string &name)=0
virtual LoadEvent::autoptr getLoadEventAP (JobType t, const std::string &name)=0
virtual bool isOverloaded ()=0
virtual Json::Value getJson (int c=0)=0
Public Member Functions inherited from beast::Stoppable
Stoppable (char const *name, Stoppable &parent)
virtual ~Stoppable ()
bool isStopping () const
bool isStopped () const
bool areChildrenStopped () const
void stopped ()
virtual void onPrepare ()
virtual void onStart ()
virtual void onStop ()
virtual void onChildrenStopped ()
Protected Member Functions
JobQueue (char const *name, Stoppable &parent)
Protected Member Functions inherited from beast::Stoppable
Stoppable (char const *name, RootStoppable &root)
Additional Inherited Members
Protected Attributes inherited from beast::Stoppable
char const * m_name
RootStoppable & m_root
Child m_child
Atomic< int > m_started
bool volatile m_stopped
bool volatile m_childrenStopped
Children m_children
WaitableEvent m_stoppedEvent
Detailed Description
Definition at line 27 of file JobQueue.h.
Constructor & Destructor Documentation
ripple::JobQueue::JobQueue (char const * name, Stoppable & parent) protected
Definition at line 669 of file JobQueue.cpp.
     : Stoppable (name, parent)
 {
 }
virtual ripple::JobQueue::~JobQueue () inline virtual
Definition at line 33 of file JobQueue.h.
 { }
Member Function Documentation
virtual void ripple::JobQueue::addJob (JobType type, std::string const & name, boost::function< void(Job &)> const & job) pure virtual
Implemented in ripple::JobQueueImp.
Referenced by ripple::LedgerConsensusImp::beginAccept(), ripple::ValidationsImp::condWrite(), ripple::WSServerHandler< endpoint_type >::do_messages(), ripple::LedgerMasterImp::doAdvance(), ripple::WSServerHandler< endpoint_type >::doClose(), ripple::PeerImp::doFetchPack(), ripple::SqliteDatabase::doHook(), ripple::TransactionAcquire::done(), ripple::InboundLedger::done(), ripple::NetworkOPsImp::gotFetchPack(), ripple::InboundLedgersImp::gotLedgerData(), ripple::ConsensusTransSetSF::gotNode(), ripple::LedgerConsensusImp::handleLCL(), ripple::LedgerMasterImp::newPFWork(), ripple::WSServerHandler< endpoint_type >::on_message(), ripple::UniqueNodeListImp::onDeadlineTimer(), ripple::NetworkOPsImp::onDeadlineTimer(), ripple::RPCHTTPServerImp::onRequest(), ripple::LedgerConsensusImp::peerHasSet(), ripple::Ledger::pendSaveValidated(), ripple::PeerImp::recvGetLedger(), ripple::PeerImp::recvProofWork(), ripple::PeerImp::recvPropose(), ripple::PeerImp::recvTransaction(), ripple::PeerImp::recvValidation(), ripple::NetworkOPsImp::reportFeeChange(), ripple::NodeStoreScheduler::scheduleTask(), ripple::OrderBookDB::setup(), ripple::NetworkOPsImp::submitTransaction(), ripple::PeerSet::TimerEntry(), and ripple::LedgerMasterImp::tryAdvance().
virtual int ripple::JobQueue::getJobCount (JobType t) pure virtual
Implemented in ripple::JobQueueImp.
Referenced by ripple::LedgerMasterImp::doAdvance().
virtual int ripple::JobQueue::getJobCountGE (JobType t) pure virtual
Implemented in ripple::JobQueueImp.
Referenced by ripple::RPCHandler::doCommand().
virtual int ripple::JobQueue::getJobCountTotal (JobType t) pure virtual
Implemented in ripple::JobQueueImp.
Referenced by ripple::PeerSet::TimerEntry().
virtual Json::Value ripple::JobQueue::getJson (int c = 0) pure virtual
Implemented in ripple::JobQueueImp.
Referenced by ripple::NetworkOPsImp::getServerInfo(), and ripple::LoadManagerImp::run().
virtual LoadEvent::pointer ripple::JobQueue::getLoadEvent (JobType t, const std::string & name) pure virtual
Implemented in ripple::JobQueueImp.
Referenced by ripple::Pathfinder::Pathfinder().
virtual LoadEvent::autoptr ripple::JobQueue::getLoadEventAP (JobType t, const std::string & name) pure virtual
Implemented in ripple::JobQueueImp.
Referenced by ripple::RPCHandler::doCommand(), ripple::NetworkOPsImp::processTransactionCb(), and ripple::NetworkOPsImp::runTransactionQueue().
virtual bool ripple::JobQueue::isOverloaded () pure virtual
Implemented in ripple::JobQueueImp.
virtual void ripple::JobQueue::setThreadCount (int c, bool const standaloneMode) pure virtual
Implemented in ripple::JobQueueImp.
virtual void ripple::JobQueue::shutdown () pure virtual
Implemented in ripple::JobQueueImp.
The documentation for this class was generated from the following files:
rippled/src/ripple_core/functional/JobQueue.h
rippled/src/ripple_core/functional/JobQueue.cpp