rippled: beast::Atomic< Type > Class Template Reference
beast::Atomic< Type > Class Template Reference
#include <Atomic.h>
Public Member Functions
Atomic () noexcept
Atomic (const Type initialValue) noexcept
Atomic (const Atomic &other) noexcept
~Atomic () noexcept
Type get () const noexcept
Atomic & operator= (const Atomic &other) noexcept
Atomic & operator= (const Type newValue) noexcept
void set (Type newValue) noexcept
Type exchange (Type value) noexcept
Type operator+= (Type amountToAdd) noexcept
Type operator-= (Type amountToSubtract) noexcept
Type operator++ () noexcept
Type operator-- () noexcept
bool compareAndSetBool (Type newValue, Type valueToCompare) noexcept
Type compareAndSetValue (Type newValue, Type valueToCompare) noexcept
Public Attributes
volatile Type value
Private Member Functions
Type operator++ (int)
Type operator-- (int)
template<typename ValueType >
ValueType negateValue (ValueType n) noexcept
template<typename PointerType >
PointerType * negateValue (PointerType *n) noexcept
Static Private Member Functions
template<typename Dest , typename Source >
static Dest castTo (Source value) noexcept
static Type castFrom32Bit (std::int32_t value) noexcept
static Type castFrom64Bit (std::int64_t value) noexcept
static std::int32_t castTo32Bit (Type value) noexcept
static std::int64_t castTo64Bit (Type value) noexcept
Detailed Description
template<typename Type>
class beast::Atomic< Type >
Simple class to hold a primitive value and perform atomic operations on it.
The type used must be a 32 or 64 bit primitive, like an int, pointer, etc. There are methods to perform most of the basic atomic operations.
Definition at line 44 of file Atomic.h.
Constructor & Destructor Documentation
template<typename Type> beast::Atomic< Type >::Atomic () inline noexcept
Creates a new value, initialised to zero.
Definition at line 48 of file Atomic.h.
         : value (0)
     {
     }
template<typename Type> beast::Atomic< Type >::Atomic (const Type initialValue) inline noexcept
Creates a new value, with a given initial value.
Definition at line 54 of file Atomic.h.
         : value (initialValue)
     {
     }
template<typename Type> beast::Atomic< Type >::Atomic (const Atomic< Type > & other) inline noexcept
Copies another value (atomically).
Definition at line 60 of file Atomic.h.
         : value (other.get())
     {
     }
template<typename Type> beast::Atomic< Type >::~Atomic () inline noexcept
Destructor.
Definition at line 66 of file Atomic.h.
     {
         // This class can only be used for types which are 32 or 64 bits in size.
         static_bassert (sizeof (Type) == 4 || sizeof (Type) == 8);
     }
Member Function Documentation
template<typename Type> static Type beast::Atomic< Type >::castFrom32Bit (std::int32_t value) inline static private noexcept
Definition at line 162 of file Atomic.h.
 { return castTo <Type, std::int32_t> (value); }
template<typename Type> static Type beast::Atomic< Type >::castFrom64Bit (std::int64_t value) inline static private noexcept
Definition at line 163 of file Atomic.h.
 { return castTo <Type, std::int64_t> (value); }
template<typename Type> template<typename Dest , typename Source > static Dest beast::Atomic< Type >::castTo (Source value) inline static private noexcept
Definition at line 160 of file Atomic.h.
 { union { Dest d; Source s; } u; u.s = value; return u.d; }
template<typename Type> static std::int32_t beast::Atomic< Type >::castTo32Bit (Type value) inline static private noexcept
Definition at line 164 of file Atomic.h.
 { return castTo <std::int32_t, Type> (value); }
template<typename Type> static std::int64_t beast::Atomic< Type >::castTo64Bit (Type value) inline static private noexcept
Definition at line 165 of file Atomic.h.
 { return castTo <std::int64_t, Type> (value); }
template<typename Type> bool beast::Atomic< Type >::compareAndSetBool (Type newValue, Type valueToCompare) inline noexcept
Atomically compares this value with a target value, and if it is equal, sets this to be equal to a new value.
This operation is the atomic equivalent of doing this:
bool compareAndSetBool (Type newValue, Type valueToCompare)
{
    if (get() == valueToCompare)
    {
        set (newValue);
        return true;
    }
    return false;
}
Returns
true if the comparison was true and the value was replaced; false if the comparison failed and the value was left unchanged.
See Also
compareAndSetValue
Definition at line 375 of file Atomic.h.
References value.
Referenced by beast::StaticObject< Object, Tag >::get(), beast::RootStoppable::prepare(), beast::RootStoppable::start(), beast::RootStoppable::stop(), beast::RootStoppable::stopAsync(), beast::Atomic_test::testFloat(), and beast::SpinLock::tryEnter().
 {
   #if BEAST_ATOMICS_MAC
     return sizeof (Type) == 4 ? OSAtomicCompareAndSwap32Barrier ((int32_t) castTo32Bit (valueToCompare), (int32_t) castTo32Bit (newValue), (BEAST_MAC_ATOMICS_VOLATILE int32_t*) &value)
                               : OSAtomicCompareAndSwap64Barrier ((int64_t) castTo64Bit (valueToCompare), (int64_t) castTo64Bit (newValue), (BEAST_MAC_ATOMICS_VOLATILE int64_t*) &value);
   #elif BEAST_ATOMICS_WINDOWS
     return compareAndSetValue (newValue, valueToCompare) == valueToCompare;
   #elif BEAST_ATOMICS_GCC
     return sizeof (Type) == 4 ? __sync_bool_compare_and_swap ((volatile std::int32_t*) &value, castTo32Bit (valueToCompare), castTo32Bit (newValue))
                               : __sync_bool_compare_and_swap ((volatile std::int64_t*) &value, castTo64Bit (valueToCompare), castTo64Bit (newValue));
   #endif
 }
template<typename Type> Type beast::Atomic< Type >::compareAndSetValue (Type newValue, Type valueToCompare) inline noexcept
Atomically compares this value with a target value, and if it is equal, sets this to be equal to a new value.
This operation is the atomic equivalent of doing this:
Type compareAndSetValue (Type newValue, Type valueToCompare)
{
    Type oldValue = get();
    if (oldValue == valueToCompare)
        set (newValue);
    return oldValue;
}
Returns
the old value before it was changed.
See Also
compareAndSetBool
Definition at line 389 of file Atomic.h.
References beast::beast_InterlockedCompareExchange(), beast::beast_InterlockedCompareExchange64(), and value.
Referenced by beast::Atomic_test::testFloat().
 {
   #if BEAST_ATOMICS_MAC
     for (;;) // Annoying workaround for only having a bool CAS operation..
     {
         if (compareAndSetBool (newValue, valueToCompare))
             return valueToCompare;
         const Type result = value;
         if (result != valueToCompare)
             return result;
     }
   #elif BEAST_ATOMICS_WINDOWS
     return sizeof (Type) == 4 ? castFrom32Bit ((std::int32_t) beast_InterlockedCompareExchange ((volatile long*) &value, (long) castTo32Bit (newValue), (long) castTo32Bit (valueToCompare)))
                               : castFrom64Bit ((std::int64_t) beast_InterlockedCompareExchange64 ((volatile __int64*) &value, (__int64) castTo64Bit (newValue), (__int64) castTo64Bit (valueToCompare)));
   #elif BEAST_ATOMICS_GCC
     return sizeof (Type) == 4 ? castFrom32Bit ((std::int32_t) __sync_val_compare_and_swap ((volatile std::int32_t*) &value, castTo32Bit (valueToCompare), castTo32Bit (newValue)))
                               : castFrom64Bit ((std::int64_t) __sync_val_compare_and_swap ((volatile std::int64_t*) &value, castTo64Bit (valueToCompare), castTo64Bit (newValue)));
   #endif
 }
template<typename Type> Type beast::Atomic< Type >::exchange (Type value) inline noexcept
Atomically sets the current value, returning the value that was replaced.
Definition at line 290 of file Atomic.h.
References beast::beast_InterlockedExchange(), beast::beast_InterlockedExchange64(), and value.
Referenced by beast::Atomic< ripple::Peer::ShortId >::operator=(), beast::Atomic< ripple::Peer::ShortId >::set(), and beast::Atomic_test::testFloat().
 {
   #if BEAST_ATOMICS_MAC || BEAST_ATOMICS_GCC
     Type currentVal = value;
     while (! compareAndSetBool (newValue, currentVal)) { currentVal = value; }
     return currentVal;
   #elif BEAST_ATOMICS_WINDOWS
     return sizeof (Type) == 4 ? castFrom32Bit ((std::int32_t) beast_InterlockedExchange ((volatile long*) &value, (long) castTo32Bit (newValue)))
                               : castFrom64Bit ((std::int64_t) beast_InterlockedExchange64 ((volatile __int64*) &value, (__int64) castTo64Bit (newValue)));
   #endif
 }
template<typename Type > Type beast::Atomic< Type >::get () const inline noexcept
Atomically reads and returns the current value.
Definition at line 275 of file Atomic.h.
References beast::beast_InterlockedExchangeAdd(), beast::beast_InterlockedExchangeAdd64(), and value.
Referenced by beast::StaticObject< Object, Tag >::get(), beast::RootStoppable::isStopping(), beast::StringHolder::makeUnique(), beast::StringHolder::makeUniqueWithByteSize(), beast::Workers::numberOfCurrentlyRunningTasks(), ripple::IoServicePool::onThreadExit(), beast::ServiceQueueBase::reset(), beast::RootStoppable::stop(), beast::ServiceQueueBase::stopped(), beast::Atomic_test::testFloat(), beast::Atomic_test::testInteger(), beast::asio::AsyncObject< Peer >::~AsyncObject(), and beast::Stoppable::~Stoppable().
 {
   #if BEAST_ATOMICS_MAC
     return sizeof (Type) == 4 ? castFrom32Bit ((std::int32_t) OSAtomicAdd32Barrier ((int32_t) 0, (BEAST_MAC_ATOMICS_VOLATILE int32_t*) &value))
                               : castFrom64Bit ((std::int64_t) OSAtomicAdd64Barrier ((int64_t) 0, (BEAST_MAC_ATOMICS_VOLATILE int64_t*) &value));
   #elif BEAST_ATOMICS_WINDOWS
     return sizeof (Type) == 4 ? castFrom32Bit ((std::int32_t) beast_InterlockedExchangeAdd ((volatile long*) &value, (long) 0))
                               : castFrom64Bit ((std::int64_t) beast_InterlockedExchangeAdd64 ((volatile __int64*) &value, (__int64) 0));
   #elif BEAST_ATOMICS_GCC
     return sizeof (Type) == 4 ? castFrom32Bit ((std::int32_t) __sync_add_and_fetch ((volatile std::int32_t*) &value, 0))
                               : castFrom64Bit ((std::int64_t) __sync_add_and_fetch ((volatile std::int64_t*) &value, 0));
   #endif
 }
template<typename Type> template<typename ValueType > ValueType beast::Atomic< Type >::negateValue (ValueType n) inline private noexcept
This templated negate function will negate pointers as well as integers
Definition at line 173 of file Atomic.h.
     {
         return sizeof (ValueType) == 1 ? (ValueType) -(signed char) n
             : (sizeof (ValueType) == 2 ? (ValueType) -(short) n
             : (sizeof (ValueType) == 4 ? (ValueType) -(int) n
             : ((ValueType) -(std::int64_t) n)));
     }
template<typename Type> template<typename PointerType > PointerType* beast::Atomic< Type >::negateValue (PointerType * n) inline private noexcept
This templated negate function will negate pointers as well as integers
Definition at line 183 of file Atomic.h.
     {
         return reinterpret_cast <PointerType*> (-reinterpret_cast <std::intptr_t> (n));
     }
template<typename Type > Type beast::Atomic< Type >::operator++ () inline noexcept
Atomically increments this value, returning the new value.
Definition at line 331 of file Atomic.h.
References beast::beast_InterlockedIncrement(), beast::beast_InterlockedIncrement64(), and value.
 {
   #if BEAST_ATOMICS_MAC
 #   ifdef __clang__
 #       pragma clang diagnostic push
 #       pragma clang diagnostic ignored "-Wint-to-void-pointer-cast"
 #       pragma clang diagnostic ignored "-Wint-to-pointer-cast"
 #   endif
     return sizeof (Type) == 4 ? (Type) OSAtomicIncrement32Barrier ((BEAST_MAC_ATOMICS_VOLATILE int32_t*) &value)
                               : (Type) OSAtomicIncrement64Barrier ((BEAST_MAC_ATOMICS_VOLATILE int64_t*) &value);
 #   ifdef __clang__
 #       pragma clang diagnostic pop
 #   endif
   #elif BEAST_ATOMICS_WINDOWS
     return sizeof (Type) == 4 ? (Type) beast_InterlockedIncrement ((volatile long*) &value)
                               : (Type) beast_InterlockedIncrement64 ((volatile __int64*) &value);
   #elif BEAST_ATOMICS_GCC
     return (Type) __sync_add_and_fetch (&value, (Type) 1);
   #endif
 }
template<typename Type> Type beast::Atomic< Type >::operator++ (int) private
template<typename Type> Type beast::Atomic< Type >::operator+= (Type amountToAdd) inline noexcept
Atomically adds a number to this value, returning the new value.
Definition at line 303 of file Atomic.h.
References beast::beast_InterlockedExchangeAdd(), beast::beast_InterlockedExchangeAdd64(), and value.
 {
   #if BEAST_ATOMICS_MAC
 #   ifdef __clang__
 #       pragma clang diagnostic push
 #       pragma clang diagnostic ignored "-Wint-to-void-pointer-cast"
 #       pragma clang diagnostic ignored "-Wint-to-pointer-cast"
 #   endif
     return sizeof (Type) == 4 ? (Type) OSAtomicAdd32Barrier ((int32_t) castTo32Bit (amountToAdd), (BEAST_MAC_ATOMICS_VOLATILE int32_t*) &value)
                               : (Type) OSAtomicAdd64Barrier ((int64_t) amountToAdd, (BEAST_MAC_ATOMICS_VOLATILE int64_t*) &value);
 #   ifdef __clang__
 #       pragma clang diagnostic pop
 #   endif
   #elif BEAST_ATOMICS_WINDOWS
     return sizeof (Type) == 4 ? (Type) (beast_InterlockedExchangeAdd ((volatile long*) &value, (long) amountToAdd) + (long) amountToAdd)
                               : (Type) (beast_InterlockedExchangeAdd64 ((volatile __int64*) &value, (__int64) amountToAdd) + (__int64) amountToAdd);
   #elif BEAST_ATOMICS_GCC
     return (Type) __sync_add_and_fetch (&value, amountToAdd);
   #endif
 }
template<typename Type > Type beast::Atomic< Type >::operator-- () inline noexcept
Atomically decrements this value, returning the new value.
Definition at line 353 of file Atomic.h.
References beast::beast_InterlockedDecrement(), beast::beast_InterlockedDecrement64(), and value.
 {
   #if BEAST_ATOMICS_MAC
 #   ifdef __clang__
 #       pragma clang diagnostic push
 #       pragma clang diagnostic ignored "-Wint-to-void-pointer-cast"
 #       pragma clang diagnostic ignored "-Wint-to-pointer-cast"
 #   endif
     return sizeof (Type) == 4 ? (Type) OSAtomicDecrement32Barrier ((BEAST_MAC_ATOMICS_VOLATILE int32_t*) &value)
                               : (Type) OSAtomicDecrement64Barrier ((BEAST_MAC_ATOMICS_VOLATILE int64_t*) &value);
 #   ifdef __clang__
 #       pragma clang diagnostic pop
 #   endif
   #elif BEAST_ATOMICS_WINDOWS
     return sizeof (Type) == 4 ? (Type) beast_InterlockedDecrement ((volatile long*) &value)
                               : (Type) beast_InterlockedDecrement64 ((volatile __int64*) &value);
   #elif BEAST_ATOMICS_GCC
     return (Type) __sync_add_and_fetch (&value, (Type) -1);
   #endif
 }
template<typename Type> Type beast::Atomic< Type >::operator-- (int) private
template<typename Type> Type beast::Atomic< Type >::operator-= (Type amountToSubtract) inline noexcept
Atomically subtracts a number from this value, returning the new value.
Definition at line 325 of file Atomic.h.
 {
     return operator+= (negateValue (amountToSubtract));
 }
template<typename Type> Atomic& beast::Atomic< Type >::operator= (const Atomic< Type > & other) inline noexcept
Copies another value onto this one (atomically).
Definition at line 76 of file Atomic.h.
       { exchange (other.get()); return *this; }
template<typename Type> Atomic& beast::Atomic< Type >::operator= (const Type newValue) inline noexcept
Copies another value onto this one (atomically).
Definition at line 80 of file Atomic.h.
       { exchange (newValue); return *this; }
template<typename Type> void beast::Atomic< Type >::set (Type newValue) inline noexcept
Atomically sets the current value.
Definition at line 84 of file Atomic.h.
Referenced by beast::ServiceQueueBase::reset(), beast::ServiceQueueBase::stop(), and beast::Atomic_test::testInteger().
       { exchange (newValue); }
Member Data Documentation
template<typename Type> volatile Type beast::Atomic< Type >::value
The raw value that this class operates on. This is exposed publically in case you need to manipulate it directly for performance reasons.
Definition at line 156 of file Atomic.h.
Referenced by beast::Atomic< ripple::Peer::ShortId >::castFrom32Bit(), beast::Atomic< ripple::Peer::ShortId >::castFrom64Bit(), beast::Atomic< ripple::Peer::ShortId >::castTo(), beast::Atomic< ripple::Peer::ShortId >::castTo32Bit(), beast::Atomic< ripple::Peer::ShortId >::castTo64Bit(), beast::StringHolder::createUninitialisedBytes(), beast::SpinLock::exit(), and beast::Atomic_test::testInteger().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/Atomic.h