rippled: ripple::HTTP::Server Class Reference
ripple::HTTP::Server Class Reference
#include <Server.h>
Public Member Functions
Server (Handler &handler, beast::Journal journal)
virtual ~Server ()
beast::Journal const & journal () const
Ports const & getPorts () const
void setPorts (Ports const &ports)
void stopAsync ()
void stop ()
Private Attributes
std::unique_ptr< ServerImpl > m_impl
Detailed Description
Multi-threaded, asynchronous HTTP server.
Definition at line 33 of file Server.h.
Constructor & Destructor Documentation
ripple::HTTP::Server::Server (Handler & handler, beast::Journal journal)
Create the server using the specified handler.
Definition at line 23 of file Server.cpp.
     : m_impl (new ServerImpl (*this, handler, journal))
 {
 }
ripple::HTTP::Server::~Server () virtual
Destroy the server. This blocks until the server stops.
Definition at line 28 of file Server.cpp.
References stop().
 {
     stop();
 }
Member Function Documentation
Ports const & ripple::HTTP::Server::getPorts () const
Returns the listening ports settings. Thread safety: Safe to call from any thread. Cannot be called concurrently with setPorts.
Definition at line 38 of file Server.cpp.
References m_impl.
 {
     return m_impl->getPorts();
 }
beast::Journal const & ripple::HTTP::Server::journal () const
Returns the Journal associated with the server.
Definition at line 33 of file Server.cpp.
References m_impl.
 {
     return m_impl->journal();
 }
void ripple::HTTP::Server::setPorts (Ports const & ports)
Set the listening ports settings. These take effect immediately. Any current ports that are not in the new set will be closed. Established connections will not be disturbed. Thread safety: Cannot be called concurrently.
Definition at line 43 of file Server.cpp.
References m_impl.
Referenced by ripple::RPCHTTPServerImp::setup().
 {
     m_impl->setPorts (ports);
 }
void ripple::HTTP::Server::stop ()
Notify the server to stop, and block until the stop is complete. The handler's onStopped method will be called when the stop completes. Thread safety: Cannot be called concurrently. Cannot be called from the thread of execution of any Handler functions.
Definition at line 53 of file Server.cpp.
References m_impl.
Referenced by ripple::RPCHTTPServerImp::~RPCHTTPServerImp(), and ~Server().
 {
     m_impl->stop(true);
 }
void ripple::HTTP::Server::stopAsync ()
Notify the server to stop, without blocking. Thread safety: Safe to call concurrently from any thread.
Definition at line 48 of file Server.cpp.
References m_impl.
Referenced by ripple::RPCHTTPServerImp::onStop().
 {
     m_impl->stop(false);
 }
Member Data Documentation
std::unique_ptr<ServerImpl> ripple::HTTP::Server::m_impl private
Definition at line 77 of file Server.h.
Referenced by getPorts(), journal(), setPorts(), stop(), and stopAsync().
The documentation for this class was generated from the following files:
rippled/src/ripple/http/api/Server.h
rippled/src/ripple/http/impl/Server.cpp