rippled: ripple::HTTP::Peer Class Reference
ripple::HTTP::Peer Class Reference
#include <Peer.h>
Public Types
enum { bufferSize = 8192, maxRequestBytes = 32 * 1024, dataTimeoutSeconds = 10, requestTimeoutSeconds = 30 }
typedef beast::SharedPtr< Peer > Ptr
Public Member Functions
Peer (ServerImpl &impl, Port const &port)
~Peer ()
beast::Journal journal ()
beast::IP::Endpoint remoteAddress ()
bool headersComplete ()
beast::HTTPHeaders headers ()
beast::SharedPtr
< beast::HTTPRequest > const & request ()
std::string content ()
void write (void const *buffer, std::size_t bytes)
void detach ()
void close ()
void asyncHandlersComplete ()
void handle_accept ()
void handle_write (SharedBuffer const &buf, CompletionCounter)
void handle_handshake (error_code ec, CompletionCounter)
void handle_data_timer (error_code ec, CompletionCounter)
void handle_request_timer (error_code ec, CompletionCounter)
void handle_write (error_code ec, std::size_t bytes_transferred, SharedBuffer buf, CompletionCounter)
void handle_read (error_code ec, std::size_t bytes_transferred, CompletionCounter)
void handle_headers ()
void handle_request ()
void handle_close (CompletionCounter)
socket & get_socket ()
Session & session ()
void cancel ()
void failed (error_code const &ec)
void async_read_some ()
void async_write (SharedBuffer const &buf)
template<typename BufferSequence >
void async_write (BufferSequence const &buffers)
Public Member Functions inherited from beast::SharedObject
void incReferenceCount () const noexcept
void decReferenceCount () const
int getReferenceCount () const noexcept
Public Member Functions inherited from beast::asio::AsyncObject< Peer >
~AsyncObject ()
void addReference ()
void removeReference ()
Public Member Functions inherited from ripple::HTTP::Session
void write (std::string const &s)
template<typename BufferSequence >
void write (BufferSequence const &buffers)
ScopedStream operator<< (std::ostream &manip(std::ostream &))
template<typename T >
ScopedStream operator<< (T const &t)
Public Attributes
ServerImpl & m_impl
boost::asio::io_service::strand m_strand
boost::asio::deadline_timer m_data_timer
boost::asio::deadline_timer m_request_timer
std::unique_ptr< MultiSocket > m_socket
beast::MemoryBlock m_buffer
beast::HTTPRequestParser m_parser
int m_writesPending
bool m_closed
bool m_callClose
beast::SharedPtr< Peer > m_detach_ref
boost::optional
< boost::asio::io_service::work > m_work
int m_errorCode
std::atomic< int > m_detached
Public Attributes inherited from ripple::HTTP::Session
void * tag
Additional Inherited Members
Protected Member Functions inherited from beast::SharedObject
SharedObject ()
virtual ~SharedObject ()
virtual void destroy () const
void resetReferenceCount () noexcept
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
Represents an active connection.
Definition at line 34 of file Peer.h.
Member Typedef Documentation
typedef beast::SharedPtr<Peer> ripple::HTTP::Peer::Ptr
Definition at line 58 of file Peer.h.
Member Enumeration Documentation
anonymous enum
Enumerator
bufferSize
maxRequestBytes
dataTimeoutSeconds
requestTimeoutSeconds
Definition at line 42 of file Peer.h.
     {
         // Size of our receive buffer
         bufferSize = 8192,
         // Largest HTTP request allowed
         maxRequestBytes = 32 * 1024,
         // Max seconds without receiving a byte
         dataTimeoutSeconds = 10,
         // Max seconds without completing the request
         requestTimeoutSeconds = 30
     };
Constructor & Destructor Documentation
ripple::HTTP::Peer::Peer (ServerImpl & impl, Port const & port) inline
Definition at line 77 of file Peer.h.
References ripple::HTTP::ServerImpl::add(), ripple::HTTP::Port::allow_ssl, bassertfalse, ripple::HTTP::Port::context, beast::asio::SSLContext::get(), ripple::HTTP::ServerImpl::get_io_service(), m_impl, m_socket, ripple::MultiSocket::New(), ripple::HTTP::Port::no_ssl, ripple::MultiSocket::none, ripple::HTTP::Port::require_ssl, ripple::HTTP::Port::security, ripple::MultiSocket::server_ssl, ripple::MultiSocket::server_ssl_required, and ripple::HTTP::Session::tag.
         : m_impl (impl)
         , m_strand (m_impl.get_io_service())
         , m_data_timer (m_impl.get_io_service())
         , m_request_timer (m_impl.get_io_service())
         , m_buffer (bufferSize)
         , m_writesPending (0)
         , m_closed (false)
         , m_callClose (false)
         , m_errorCode (0)
         , m_detached (0)
     {
         tag = nullptr;
         int flags;
         switch (port.security)
         {
         default:
             bassertfalse;
         case Port::no_ssl:      flags = MultiSocket::none; break;
         case Port::allow_ssl:   flags = MultiSocket::server_ssl; break;
         case Port::require_ssl: flags = MultiSocket::server_ssl_required; break;
         }
         m_socket.reset (MultiSocket::New (
             m_impl.get_io_service(), port.context->get(), flags));
         m_impl.add (*this);
     }
ripple::HTTP::Peer::~Peer () inline
Definition at line 107 of file Peer.h.
References ripple::HTTP::ServerImpl::handler(), m_callClose, m_errorCode, m_impl, ripple::HTTP::Handler::onClose(), ripple::HTTP::ServerImpl::remove(), and session().
     {
         if (m_callClose)
             m_impl.handler().onClose (session(), m_errorCode);
         m_impl.remove (*this);
     }
Member Function Documentation
void ripple::HTTP::Peer::async_read_some () inline
Definition at line 450 of file Peer.h.
References dataTimeoutSeconds, beast::MemoryBlock::getData(), beast::MemoryBlock::getSize(), handle_data_timer(), handle_read(), m_buffer, m_data_timer, m_socket, and m_strand.
Referenced by handle_accept(), handle_handshake(), and handle_read().
     {
         // re-arm the data timer
         // (this cancels the previous wait, if any)
         //
         m_data_timer.expires_from_now (
             boost::posix_time::seconds (
                 dataTimeoutSeconds));
         m_data_timer.async_wait (m_strand.wrap (boost::bind (
             &Peer::handle_data_timer, Ptr(this),
                 boost::asio::placeholders::error,
                     CompletionCounter (this))));
         // issue the read
         //
         boost::asio::mutable_buffers_1 buf (
             m_buffer.getData (), m_buffer.getSize ());
         m_socket->async_read_some (buf, m_strand.wrap (
             boost::bind (&Peer::handle_read, Ptr (this),
                 boost::asio::placeholders::error,
                     boost::asio::placeholders::bytes_transferred,
                         CompletionCounter (this))));
     }
void ripple::HTTP::Peer::async_write (SharedBuffer const & buf) inline
Definition at line 477 of file Peer.h.
References bassert, beast::asio::SharedArg< T >::get(), handle_write(), m_socket, m_strand, and m_writesPending.
Referenced by async_write(), and handle_write().
     {
         bassert (buf.get().size() > 0);
         ++m_writesPending;
         // Send the copy. We pass the SharedBuffer in the last parameter
         // so that a reference is maintained as the handler gets copied.
         // When the final completion function returns, the reference
         // count will drop to zero and the buffer will be freed.
         //
         boost::asio::async_write (*m_socket,
             boost::asio::const_buffers_1 (&(*buf)[0], buf->size()),
                 m_strand.wrap (boost::bind (&Peer::handle_write,
                     Ptr (this), boost::asio::placeholders::error,
                         boost::asio::placeholders::bytes_transferred,
                             buf, CompletionCounter (this))));
     }
template<typename BufferSequence > void ripple::HTTP::Peer::async_write (BufferSequence const & buffers) inline
Definition at line 498 of file Peer.h.
References async_write().
     {
         // Iterate over each linear vector in the BufferSequence.
         for (typename BufferSequence::const_iterator iter (buffers.begin());
             iter != buffers.end(); ++iter)
         {
             typename BufferSequence::value_type const& buffer (*iter);
             // Put a copy of this section of the buffer sequence into
             // a reference counted, shared container.
             //
             async_write (SharedBuffer (
                 boost::asio::buffer_cast <char const*> (buffer),
                     boost::asio::buffer_size (buffer)));
         }
     }
void ripple::HTTP::Peer::asyncHandlersComplete () inline
Definition at line 204 of file Peer.h.
     {
     }
void ripple::HTTP::Peer::cancel () inline
Definition at line 432 of file Peer.h.
References m_data_timer, m_request_timer, and m_socket.
Referenced by failed(), and handle_accept().
     {
         error_code ec;
         m_data_timer.cancel (ec);
         m_request_timer.cancel (ec);
         m_socket->cancel (ec);
         m_socket->shutdown (socket::shutdown_both);
     }
void ripple::HTTP::Peer::close () inline virtual
Close the session. This will be performed asynchronously. The session will be closed gracefully after all pending writes have completed.
Implements ripple::HTTP::Session.
Definition at line 190 of file Peer.h.
References ripple::HTTP::ServerImpl::get_io_service(), handle_close(), m_impl, and m_strand.
     {
         // Make sure this happens on an io_service thread.
         m_impl.get_io_service().dispatch (m_strand.wrap (
             boost::bind (&Peer::handle_close, Ptr (this),
                 CompletionCounter (this))));
     }
std::string ripple::HTTP::Peer::content () inline virtual
Returns the entire Content-Body, if the request is complete.
Implements ripple::HTTP::Session.
Definition at line 147 of file Peer.h.
References m_parser, and beast::HTTPRequestParser::request().
     {
         std::string s;
         beast::DynamicBuffer const& body (
             m_parser.request()->body ());
         s.resize (body.size ());
         boost::asio::buffer_copy (
             boost::asio::buffer (&s[0],
                 s.size()), body.data <boost::asio::const_buffer>());
         return s;
     }
void ripple::HTTP::Peer::detach () inline virtual
Detach the session. This holds the session open so that the response can be sent asynchronously. Calls to io_service::run made by the server will not return until all detached sessions are closed.
Implements ripple::HTTP::Session.
Definition at line 170 of file Peer.h.
References bassert, ripple::HTTP::ServerImpl::get_io_service(), m_detach_ref, m_detached, m_impl, and m_work.
     {
         if (m_detached.exchange (1) == 0)
         {
             bassert (! m_work);
             bassert (m_detach_ref.empty());
             // Maintain an additional reference while detached
             m_detach_ref = this;
             // Prevent the io_service from running out of work.
             // The work object will be destroyed with the Peer
             // after the Session is closed and handlers complete.
             //
             m_work = boost::in_place (boost::ref (
                 m_impl.get_io_service()));
         }
     }
void ripple::HTTP::Peer::failed (error_code const & ec) inline
Definition at line 442 of file Peer.h.
References bassert, cancel(), and m_errorCode.
Referenced by handle_data_timer(), handle_handshake(), handle_read(), handle_request_timer(), and handle_write().
     {
         m_errorCode = ec.value();
         bassert (m_errorCode != 0);
         cancel ();
     }
socket& ripple::HTTP::Peer::get_socket () inline
Definition at line 420 of file Peer.h.
References m_socket.
Referenced by ripple::HTTP::Door::async_accept(), and remoteAddress().
     {
         return m_socket->this_layer<socket>();
     }
void ripple::HTTP::Peer::handle_accept () inline
Definition at line 209 of file Peer.h.
References async_read_some(), cancel(), handle_handshake(), handle_request_timer(), ripple::HTTP::ServerImpl::handler(), m_callClose, m_closed, m_impl, m_request_timer, m_socket, m_strand, ripple::HTTP::Handler::onAccept(), requestTimeoutSeconds, and session().
     {
         m_callClose = true;
         m_impl.handler().onAccept (session());
         if (m_closed)
         {
             cancel();
             return;
         }
         m_request_timer.expires_from_now (
             boost::posix_time::seconds (
                 requestTimeoutSeconds));
         m_request_timer.async_wait (m_strand.wrap (boost::bind (
             &Peer::handle_request_timer, Ptr(this),
                 boost::asio::placeholders::error,
                     CompletionCounter (this))));
         if (m_socket->needs_handshake ())
         {
             m_socket->async_handshake (beast::asio::abstract_socket::server,
                 m_strand.wrap (boost::bind (&Peer::handle_handshake, Ptr(this),
                     boost::asio::placeholders::error,
                         CompletionCounter (this))));
         }
         else
         {
             async_read_some();
         }
     }
void ripple::HTTP::Peer::handle_close (CompletionCounter) inline
Definition at line 406 of file Peer.h.
References m_closed, and m_detach_ref.
Referenced by close().
     {
         m_closed = true;
         // Release our additional reference
         m_detach_ref = nullptr;
     }
void ripple::HTTP::Peer::handle_data_timer (error_code ec, CompletionCounter) inline
Definition at line 267 of file Peer.h.
References failed(), and m_closed.
Referenced by async_read_some().
     {
         if (ec == boost::asio::error::operation_aborted)
             return;
         if (m_closed)
             return;
         if (ec != 0)
         {
             failed (ec);
             return;
         }
         failed (boost::system::errc::make_error_code (
             boost::system::errc::timed_out));
     }
void ripple::HTTP::Peer::handle_handshake (error_code ec, CompletionCounter) inline
Definition at line 251 of file Peer.h.
References async_read_some(), and failed().
Referenced by handle_accept().
     {
         if (ec == boost::asio::error::operation_aborted)
             return;
         if (ec != 0)
         {
             failed (ec);
             return;
         }
         async_read_some();
     }
void ripple::HTTP::Peer::handle_headers () inline
Definition at line 387 of file Peer.h.
References ripple::HTTP::ServerImpl::handler(), m_impl, ripple::HTTP::Handler::onHeaders(), and session().
Referenced by handle_read(), and handle_request().
     {
         m_impl.handler().onHeaders (session());
     }
void ripple::HTTP::Peer::handle_read (error_code ec, std::size_t bytes_transferred, CompletionCounter) inline
Definition at line 324 of file Peer.h.
References async_read_some(), beast::HTTPParser::error(), failed(), beast::HTTPParser::fields(), beast::HTTPParser::finished(), beast::MemoryBlock::getData(), handle_headers(), handle_request(), m_buffer, m_closed, m_data_timer, m_parser, m_request_timer, m_socket, beast::HTTPParser::process(), beast::HTTPParser::process_eof(), and beast::StringPairArray::size().
Referenced by async_read_some().
     {
         if (ec == boost::asio::error::operation_aborted)
             return;
         if (ec != 0 && ec != boost::asio::error::eof)
         {
             failed (ec);
             return;
         }
         std::size_t const bytes_parsed (m_parser.process (
             m_buffer.getData(), bytes_transferred));
         if (m_parser.error() ||
             bytes_parsed != bytes_transferred)
         {
             failed (boost::system::errc::make_error_code (
                 boost::system::errc::bad_message));
             return;
         }
         if (ec == boost::asio::error::eof)
         {
             m_parser.process_eof();
             ec = error_code();
         }
         if (m_parser.error())
         {
             failed (boost::system::errc::make_error_code (
                 boost::system::errc::bad_message));
             return;
         }
         if (! m_parser.finished())
         {
             // Feed some headers to the callback
             if (m_parser.fields().size() > 0)
             {
                 handle_headers();
                 if (m_closed)
                     return;
             }
         }
         if (m_parser.finished ())
         {
             m_data_timer.cancel();
             // VFALCO NOTE: Should we cancel this one?
             m_request_timer.cancel();
             if (! m_socket->needs_handshake())
                 m_socket->shutdown (socket::shutdown_receive);
             handle_request ();
             return;
         }
         async_read_some();
     }
void ripple::HTTP::Peer::handle_request () inline
Definition at line 393 of file Peer.h.
References handle_headers(), ripple::HTTP::ServerImpl::handler(), m_closed, m_impl, ripple::HTTP::Handler::onRequest(), and session().
Referenced by handle_read().
     {
         // This is to guarantee onHeaders is called at least once.
         handle_headers();
         if (m_closed)
             return;
         // Process the HTTPRequest
         m_impl.handler().onRequest (session());
     }
void ripple::HTTP::Peer::handle_request_timer (error_code ec, CompletionCounter) inline
Definition at line 287 of file Peer.h.
References failed(), and m_closed.
Referenced by handle_accept().
     {
         if (ec == boost::asio::error::operation_aborted)
             return;
         if (m_closed)
             return;
         if (ec != 0)
         {
             failed (ec);
             return;
         }
         failed (boost::system::errc::make_error_code (
             boost::system::errc::timed_out));
     }
void ripple::HTTP::Peer::handle_write (SharedBuffer const & buf, CompletionCounter) inline
Definition at line 244 of file Peer.h.
References async_write().
Referenced by async_write(), and write().
     {
         async_write (buf);
     }
void ripple::HTTP::Peer::handle_write (error_code ec, std::size_t bytes_transferred, SharedBuffer buf, CompletionCounter) inline
Definition at line 306 of file Peer.h.
References bassert, failed(), m_closed, m_socket, and m_writesPending.
     {
         if (ec == boost::asio::error::operation_aborted)
             return;
         if (ec != 0)
         {
             failed (ec);
             return;
         }
         bassert (m_writesPending > 0);
         if (--m_writesPending == 0 && m_closed)
             m_socket->shutdown (socket::shutdown_send);
     }
beast::HTTPHeaders ripple::HTTP::Peer::headers () inline virtual
Returns the currently known set of headers.
Implements ripple::HTTP::Session.
Definition at line 135 of file Peer.h.
References beast::HTTPParser::fields(), and m_parser.
     {
         return beast::HTTPHeaders (m_parser.fields());
     }
bool ripple::HTTP::Peer::headersComplete () inline virtual
Returns true if the full HTTP headers have been received.
Implements ripple::HTTP::Session.
Definition at line 130 of file Peer.h.
References beast::HTTPParser::headersComplete(), and m_parser.
     {
         return m_parser.headersComplete();
     }
beast::Journal ripple::HTTP::Peer::journal () inline virtual
Returns the Journal to use for logging.
Implements ripple::HTTP::Session.
Definition at line 120 of file Peer.h.
References ripple::HTTP::ServerImpl::journal(), and m_impl.
     {
         return m_impl.journal();
     }
beast::IP::Endpoint ripple::HTTP::Peer::remoteAddress () inline virtual
Returns the remote address of the connection.
Implements ripple::HTTP::Session.
Definition at line 125 of file Peer.h.
References ripple::HTTP::from_asio(), and get_socket().
     {
         return from_asio (get_socket().remote_endpoint());
     }
beast::SharedPtr<beast::HTTPRequest> const& ripple::HTTP::Peer::request () inline virtual
Returns the complete HTTP request when it is known.
Implements ripple::HTTP::Session.
Definition at line 140 of file Peer.h.
References m_parser, and beast::HTTPRequestParser::request().
     {
         return m_parser.request();
     }
Session& ripple::HTTP::Peer::session () inline
Definition at line 426 of file Peer.h.
Referenced by handle_accept(), handle_headers(), handle_request(), and ~Peer().
     {
         return *this;
     }
void ripple::HTTP::Peer::write (void const * buffer, std::size_t bytes) inline virtual
Implements ripple::HTTP::Session.
Definition at line 160 of file Peer.h.
References ripple::HTTP::ServerImpl::get_io_service(), handle_write(), m_impl, and m_strand.
     {
         // Make sure this happens on an io_service thread.
         m_impl.get_io_service().dispatch (m_strand.wrap (
             boost::bind (&Peer::handle_write, Ptr (this),
                 SharedBuffer (static_cast <char const*> (buffer), bytes),
                     CompletionCounter (this))));
     }
Member Data Documentation
beast::MemoryBlock ripple::HTTP::Peer::m_buffer
Definition at line 65 of file Peer.h.
Referenced by async_read_some(), and handle_read().
bool ripple::HTTP::Peer::m_callClose
Definition at line 69 of file Peer.h.
Referenced by handle_accept(), and ~Peer().
bool ripple::HTTP::Peer::m_closed
Definition at line 68 of file Peer.h.
Referenced by handle_accept(), handle_close(), handle_data_timer(), handle_read(), handle_request(), handle_request_timer(), and handle_write().
boost::asio::deadline_timer ripple::HTTP::Peer::m_data_timer
Definition at line 62 of file Peer.h.
Referenced by async_read_some(), cancel(), and handle_read().
beast::SharedPtr<Peer> ripple::HTTP::Peer::m_detach_ref
Definition at line 70 of file Peer.h.
Referenced by detach(), and handle_close().
std::atomic<int> ripple::HTTP::Peer::m_detached
Definition at line 73 of file Peer.h.
Referenced by detach().
int ripple::HTTP::Peer::m_errorCode
Definition at line 72 of file Peer.h.
Referenced by failed(), and ~Peer().
ServerImpl& ripple::HTTP::Peer::m_impl
Definition at line 60 of file Peer.h.
Referenced by close(), detach(), handle_accept(), handle_headers(), handle_request(), journal(), Peer(), write(), and ~Peer().
beast::HTTPRequestParser ripple::HTTP::Peer::m_parser
Definition at line 66 of file Peer.h.
Referenced by content(), handle_read(), headers(), headersComplete(), and request().
boost::asio::deadline_timer ripple::HTTP::Peer::m_request_timer
Definition at line 63 of file Peer.h.
Referenced by cancel(), handle_accept(), and handle_read().
std::unique_ptr<MultiSocket> ripple::HTTP::Peer::m_socket
Definition at line 64 of file Peer.h.
Referenced by async_read_some(), async_write(), cancel(), get_socket(), handle_accept(), handle_read(), handle_write(), and Peer().
boost::asio::io_service::strand ripple::HTTP::Peer::m_strand
Definition at line 61 of file Peer.h.
Referenced by async_read_some(), async_write(), close(), handle_accept(), and write().
boost::optional<boost::asio::io_service::work> ripple::HTTP::Peer::m_work
Definition at line 71 of file Peer.h.
Referenced by detach().
int ripple::HTTP::Peer::m_writesPending
Definition at line 67 of file Peer.h.
Referenced by async_write(), and handle_write().
The documentation for this class was generated from the following file:
rippled/src/ripple/http/impl/Peer.h