rippled: ripple::LedgerProposal Class Reference
ripple::LedgerProposal Class Reference
#include <LedgerProposal.h>
Public Types
typedef boost::shared_ptr
< LedgerProposal > pointer
typedef const pointer & ref
Public Member Functions
LedgerProposal (uint256 const &prevLgr, std::uint32_t proposeSeq, uint256 const &propose, std::uint32_t closeTime, const RippleAddress &naPeerPublic, uint256 const &suppress)
LedgerProposal (const RippleAddress &pubKey, const RippleAddress &privKey, uint256 const &prevLedger, uint256 const &position, std::uint32_t closeTime)
LedgerProposal (uint256 const &prevLedger, uint256 const &position, std::uint32_t closeTime)
uint256 getSigningHash () const
bool checkSign (const std::string &signature, uint256 const &signingHash)
bool checkSign (const std::string &signature)
bool checkSign ()
const uint160 & getPeerID () const
uint256 const & getCurrentHash () const
uint256 const & getPrevLedger () const
uint256 const & getSuppressionID () const
std::uint32_t getProposeSeq () const
std::uint32_t getCloseTime () const
const RippleAddress & peekPublic () const
Blob getPubKey () const
Blob sign ()
void setPrevLedger (uint256 const &prevLedger)
void setSignature (const std::string &signature)
bool hasSignature ()
bool isPrevLedger (uint256 const &pl)
bool isBowOut ()
const boost::posix_time::ptime getCreateTime ()
bool isStale (boost::posix_time::ptime cutoff)
bool changePosition (uint256 const &newPosition, std::uint32_t newCloseTime)
void bowOut ()
Json::Value getJson () const
Public Member Functions inherited from ripple::CountedObject< LedgerProposal >
CountedObject ()
CountedObject (CountedObject const &)
~CountedObject ()
Static Public Member Functions
static char const * getCountedObjectName ()
static uint256 computeSuppressionID (uint256 const &proposeHash, uint256 const &previousLedger, std::uint32_t proposeSeq, std::uint32_t closeTime, Blob const &pubKey, Blob const &signature)
Static Public Attributes
static const std::uint32_t seqLeave = 0xffffffff
Private Attributes
uint256 mPreviousLedger
uint256 mCurrentHash
uint256 mSuppression
std::uint32_t mCloseTime
std::uint32_t mProposeSeq
uint160 mPeerID
RippleAddress mPublicKey
RippleAddress mPrivateKey
std::string mSignature
boost::posix_time::ptime mTime
Detailed Description
Definition at line 25 of file LedgerProposal.h.
Member Typedef Documentation
typedef boost::shared_ptr<LedgerProposal> ripple::LedgerProposal::pointer
Definition at line 33 of file LedgerProposal.h.
typedef const pointer& ripple::LedgerProposal::ref
Definition at line 34 of file LedgerProposal.h.
Constructor & Destructor Documentation
ripple::LedgerProposal::LedgerProposal (uint256 const & prevLgr, std::uint32_t proposeSeq, uint256 const & propose, std::uint32_t closeTime, const RippleAddress & naPeerPublic, uint256 const & suppress)
Definition at line 22 of file LedgerProposal.cpp.
References ripple::RippleAddress::getNodeID(), mPeerID, mPublicKey, and mTime.
                                                                                                :
     mPreviousLedger (pLgr), mCurrentHash (tx), mSuppression (suppression), mCloseTime (closeTime),
     mProposeSeq (seq), mPublicKey (naPeerPublic)
 {
     // XXX Validate key.
     // if (!mKey->SetPubKey(pubKey))
     // throw std::runtime_error("Invalid public key in proposal");
     mPeerID         = mPublicKey.getNodeID ();
     mTime           = boost::posix_time::second_clock::universal_time ();
 }
ripple::LedgerProposal::LedgerProposal (const RippleAddress & pubKey, const RippleAddress & privKey, uint256 const & prevLedger, uint256 const & position, std::uint32_t closeTime)
Definition at line 37 of file LedgerProposal.cpp.
References ripple::RippleAddress::getNodeID(), mPeerID, mPublicKey, and mTime.
                                                        :
     mPreviousLedger (prevLgr), mCurrentHash (position), mCloseTime (closeTime), mProposeSeq (0),
     mPublicKey (naPub), mPrivateKey (naPriv)
 {
     mPeerID      = mPublicKey.getNodeID ();
     mTime        = boost::posix_time::second_clock::universal_time ();
 }
ripple::LedgerProposal::LedgerProposal (uint256 const & prevLedger, uint256 const & position, std::uint32_t closeTime)
Definition at line 47 of file LedgerProposal.cpp.
References mTime.
                                                        :
     mPreviousLedger (prevLgr), mCurrentHash (position), mCloseTime (closeTime), mProposeSeq (0)
 {
     mTime       = boost::posix_time::second_clock::universal_time ();
 }
Member Function Documentation
void ripple::LedgerProposal::bowOut ()
Definition at line 105 of file LedgerProposal.cpp.
References mProposeSeq, mTime, and seqLeave.
 {
     mTime           = boost::posix_time::second_clock::universal_time ();
     mProposeSeq     = seqLeave;
 }
bool ripple::LedgerProposal::changePosition (uint256 const & newPosition, std::uint32_t newCloseTime)
Definition at line 93 of file LedgerProposal.cpp.
References mCloseTime, mCurrentHash, mProposeSeq, mTime, and seqLeave.
 {
     if (mProposeSeq == seqLeave)
         return false;
     mCurrentHash    = newPosition;
     mCloseTime      = closeTime;
     mTime           = boost::posix_time::second_clock::universal_time ();
     ++mProposeSeq;
     return true;
 }
bool ripple::LedgerProposal::checkSign (const std::string & signature, uint256 const & signingHash)
Definition at line 88 of file LedgerProposal.cpp.
References mPublicKey, and ripple::RippleAddress::verifyNodePublic().
 {
     return mPublicKey.verifyNodePublic (signingHash, signature, ECDSA::not_strict);
 }
bool ripple::LedgerProposal::checkSign (const std::string & signature) inline
Definition at line 49 of file LedgerProposal.h.
References checkSign(), and getSigningHash().
     {
         return checkSign (signature, getSigningHash ());
     }
bool ripple::LedgerProposal::checkSign () inline
Definition at line 53 of file LedgerProposal.h.
References getSigningHash(), and mSignature.
Referenced by checkSign().
     {
         return checkSign (mSignature, getSigningHash ());
     }
uint256 ripple::LedgerProposal::computeSuppressionID (uint256 const & proposeHash, uint256 const & previousLedger, std::uint32_t proposeSeq, std::uint32_t closeTime, Blob const & pubKey, Blob const & signature) static
Definition at line 68 of file LedgerProposal.cpp.
References ripple::Serializer::add256(), ripple::Serializer::add32(), ripple::Serializer::addVL(), and ripple::Serializer::getSHA512Half().
Referenced by ripple::PeerImp::recvPropose(), and sign().
 {
     Serializer s (512);
     s.add256 (proposeHash);
     s.add256 (previousLedger);
     s.add32 (proposeSeq);
     s.add32 (closeTime);
     s.addVL (pubKey);
     s.addVL (signature);
     return s.getSHA512Half ();
 }
std::uint32_t ripple::LedgerProposal::getCloseTime () const inline
Definition at line 78 of file LedgerProposal.h.
References mCloseTime.
     {
         return mCloseTime;
     }
static char const* ripple::LedgerProposal::getCountedObjectName () inline static
Definition at line 29 of file LedgerProposal.h.
 { return "LedgerProposal"; }
const boost::posix_time::ptime ripple::LedgerProposal::getCreateTime () inline
Definition at line 113 of file LedgerProposal.h.
References mTime.
     {
         return mTime;
     }
uint256 const& ripple::LedgerProposal::getCurrentHash () const inline
Definition at line 62 of file LedgerProposal.h.
References mCurrentHash.
     {
         return mCurrentHash;
     }
Json::Value ripple::LedgerProposal::getJson () const
Definition at line 126 of file LedgerProposal.cpp.
References ripple::base_uint< BITS >::GetHex(), ripple::RippleAddress::humanNodePublic(), ripple::RippleAddress::isValid(), mCloseTime, mCurrentHash, mPreviousLedger, mProposeSeq, mPublicKey, Json::objectValue, and seqLeave.
 {
     Json::Value ret = Json::objectValue;
     ret["previous_ledger"] = mPreviousLedger.GetHex ();
     if (mProposeSeq != seqLeave)
     {
         ret["transaction_hash"] = mCurrentHash.GetHex ();
         ret["propose_seq"] = mProposeSeq;
     }
     ret["close_time"] = mCloseTime;
     if (mPublicKey.isValid ())
         ret["peer_id"] = mPublicKey.humanNodePublic ();
     return ret;
 }
const uint160& ripple::LedgerProposal::getPeerID () const inline
Definition at line 58 of file LedgerProposal.h.
References mPeerID.
     {
         return mPeerID;
     }
uint256 const& ripple::LedgerProposal::getPrevLedger () const inline
Definition at line 66 of file LedgerProposal.h.
References mPreviousLedger.
     {
         return mPreviousLedger;
     }
std::uint32_t ripple::LedgerProposal::getProposeSeq () const inline
Definition at line 74 of file LedgerProposal.h.
References mProposeSeq.
     {
         return mProposeSeq;
     }
Blob ripple::LedgerProposal::getPubKey () const inline
Definition at line 86 of file LedgerProposal.h.
References ripple::RippleAddress::getNodePublic(), and mPublicKey.
     {
         return mPublicKey.getNodePublic ();
     }
uint256 ripple::LedgerProposal::getSigningHash () const
Definition at line 54 of file LedgerProposal.cpp.
References ripple::Serializer::add256(), ripple::Serializer::add32(), ripple::getConfig(), ripple::Serializer::getSHA512Half(), mCloseTime, mCurrentHash, mPreviousLedger, and mProposeSeq.
Referenced by checkSign(), and sign().
 {
     Serializer s ((32 + 32 + 32 + 256 + 256) / 8);
     s.add32 (getConfig ().SIGN_PROPOSAL);
     s.add32 (mProposeSeq);
     s.add32 (mCloseTime);
     s.add256 (mPreviousLedger);
     s.add256 (mCurrentHash);
     return s.getSHA512Half ();
 }
uint256 const& ripple::LedgerProposal::getSuppressionID () const inline
Definition at line 70 of file LedgerProposal.h.
References mSuppression.
     {
         return mSuppression;
     }
bool ripple::LedgerProposal::hasSignature () inline
Definition at line 100 of file LedgerProposal.h.
References mSignature.
     {
         return !mSignature.empty ();
     }
bool ripple::LedgerProposal::isBowOut () inline
Definition at line 108 of file LedgerProposal.h.
References mProposeSeq, and seqLeave.
     {
         return mProposeSeq == seqLeave;
     }
bool ripple::LedgerProposal::isPrevLedger (uint256 const & pl) inline
Definition at line 104 of file LedgerProposal.h.
References mPreviousLedger.
     {
         return mPreviousLedger == pl;
     }
bool ripple::LedgerProposal::isStale (boost::posix_time::ptime cutoff) inline
Definition at line 117 of file LedgerProposal.h.
References mTime.
     {
         return mTime <= cutoff;
     }
const RippleAddress& ripple::LedgerProposal::peekPublic () const inline
Definition at line 82 of file LedgerProposal.h.
References mPublicKey.
     {
         return mPublicKey;
     }
void ripple::LedgerProposal::setPrevLedger (uint256 const & prevLedger) inline
Definition at line 92 of file LedgerProposal.h.
References mPreviousLedger.
     {
         mPreviousLedger = prevLedger;
     }
void ripple::LedgerProposal::setSignature (const std::string & signature) inline
Definition at line 96 of file LedgerProposal.h.
References mSignature.
     {
         mSignature = signature;
     }
Blob ripple::LedgerProposal::sign (void)
Definition at line 111 of file LedgerProposal.cpp.
References computeSuppressionID(), ripple::RippleAddress::getNodePublic(), getSigningHash(), mCloseTime, mCurrentHash, mPreviousLedger, mPrivateKey, mProposeSeq, mPublicKey, mSuppression, and ripple::RippleAddress::signNodePrivate().
 {
     Blob ret;
     mPrivateKey.signNodePrivate (getSigningHash (), ret);
     // XXX If this can fail, find out sooner.
     // if (!mPrivateKey.signNodePrivate(getSigningHash(), ret))
     //  throw std::runtime_error("unable to sign proposal");
     mSuppression = computeSuppressionID (mCurrentHash, mPreviousLedger, mProposeSeq,
         mCloseTime, mPublicKey.getNodePublic (), ret);
     return ret;
 }
Member Data Documentation
std::uint32_t ripple::LedgerProposal::mCloseTime private
Definition at line 136 of file LedgerProposal.h.
Referenced by changePosition(), getCloseTime(), getJson(), getSigningHash(), and sign().
uint256 ripple::LedgerProposal::mCurrentHash private
Definition at line 135 of file LedgerProposal.h.
Referenced by changePosition(), getCurrentHash(), getJson(), getSigningHash(), and sign().
uint160 ripple::LedgerProposal::mPeerID private
Definition at line 138 of file LedgerProposal.h.
Referenced by getPeerID(), and LedgerProposal().
uint256 ripple::LedgerProposal::mPreviousLedger private
Definition at line 135 of file LedgerProposal.h.
Referenced by getJson(), getPrevLedger(), getSigningHash(), isPrevLedger(), setPrevLedger(), and sign().
RippleAddress ripple::LedgerProposal::mPrivateKey private
Definition at line 140 of file LedgerProposal.h.
Referenced by sign().
std::uint32_t ripple::LedgerProposal::mProposeSeq private
Definition at line 136 of file LedgerProposal.h.
Referenced by bowOut(), changePosition(), getJson(), getProposeSeq(), getSigningHash(), isBowOut(), and sign().
RippleAddress ripple::LedgerProposal::mPublicKey private
Definition at line 139 of file LedgerProposal.h.
Referenced by checkSign(), getJson(), getPubKey(), LedgerProposal(), peekPublic(), and sign().
std::string ripple::LedgerProposal::mSignature private
Definition at line 142 of file LedgerProposal.h.
Referenced by checkSign(), hasSignature(), and setSignature().
uint256 ripple::LedgerProposal::mSuppression private
Definition at line 135 of file LedgerProposal.h.
Referenced by getSuppressionID(), and sign().
boost::posix_time::ptime ripple::LedgerProposal::mTime private
Definition at line 143 of file LedgerProposal.h.
Referenced by bowOut(), changePosition(), getCreateTime(), isStale(), and LedgerProposal().
const std::uint32_t ripple::LedgerProposal::seqLeave = 0xffffffff static
Definition at line 31 of file LedgerProposal.h.
Referenced by bowOut(), changePosition(), getJson(), isBowOut(), and ripple::LedgerConsensusImp::peerPosition().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/ledger/LedgerProposal.h
rippled/src/ripple_app/ledger/LedgerProposal.cpp