rippled: ShellStateConnecting Class Reference
ShellStateConnecting Class Reference
#include <ShellState.h>
Public Member Functions
virtual void run (ShellContext *)
Public Member Functions inherited from ShellState
virtual ~ShellState ()
Static Public Member Functions
static ShellStateConnecting * getInstance (void)
Private Member Functions
ShellStateConnecting ()
virtual ~ShellStateConnecting ()
Detailed Description
Definition at line 53 of file ShellState.h.
Constructor & Destructor Documentation
ShellStateConnecting::ShellStateConnecting () inline private
Definition at line 63 of file ShellState.h.
 {}
virtual ShellStateConnecting::~ShellStateConnecting () inline private virtual
Definition at line 64 of file ShellState.h.
 {}
Member Function Documentation
static ShellStateConnecting* ShellStateConnecting::getInstance (void) inline static
Definition at line 55 of file ShellState.h.
References instance.
Referenced by ShellStateConnected::handleConError(), and ShellStateStart::run().
{
     static ShellStateConnecting instance;
     return &instance;
   }
void ShellStateConnecting::run (ShellContext * c) virtual
Implements ShellState.
Definition at line 30 of file ShellState.cpp.
References ShellContext::changeState(), ShellContext::connect(), ShellStateStop::getInstance(), and ShellStateConnected::getInstance().
{
   try {
     c->connect();
   } catch (const TTransportException & e) {
     cout << e.what() << endl;
     c->changeState(ShellStateStop::getInstance());
     return;
   }
   c->changeState(ShellStateConnected::getInstance());
 }
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/tools/shell/ShellState.h
rippled/src/ripple/rocksdb/rocksdb/tools/shell/ShellState.cpp