rippled: beast::UnsignedIntegerCalc< UInt > Class Template Reference
beast::UnsignedIntegerCalc< UInt > Class Template Reference
#include <UnsignedIntegerCalc.h>
Classes
struct And
struct Not
struct Or
struct Xor
Public Types
typedef
detail::DoubleWidthUInt< UInt >
::type UIntBig
typedef std::size_t size_type
Public Member Functions
UnsignedIntegerCalc ()
UnsignedIntegerCalc (UnsignedIntegerCalc const &other)
UnsignedIntegerCalc (size_type count, UInt *values)
void toCanonical ()
UnsignedIntegerCalc & operator= (UnsignedIntegerCalc const &other)
bool isZero () const
bool isNotZero () const
operator bool () const
bool empty () const
size_type size () const
UInt operator[] (size_type n) const
int compare (UnsignedIntegerCalc const &other) const
bool operator== (UnsignedIntegerCalc const &other) const
bool operator!= (UnsignedIntegerCalc const &other) const
bool operator< (UnsignedIntegerCalc const &other) const
bool operator<= (UnsignedIntegerCalc const &other) const
bool operator> (UnsignedIntegerCalc const &other) const
bool operator>= (UnsignedIntegerCalc const &other) const
void clear ()
UnsignedIntegerCalc & operator|= (UnsignedIntegerCalc const &rhs)
UnsignedIntegerCalc & operator&= (UnsignedIntegerCalc const &rhs)
UnsignedIntegerCalc & operator^= (UnsignedIntegerCalc const &rhs)
UnsignedIntegerCalc & operator+= (UnsignedIntegerCalc const &v)
UnsignedIntegerCalc & operator+= (UInt rhs)
UnsignedIntegerCalc & operator*= (UInt rhs)
UnsignedIntegerCalc operator/= (UInt rhs)
UInt operator% (UInt rhs) const
Static Public Member Functions
static UnsignedIntegerCalc fromCanonical (void *buffer, size_type const bytes, bool swizzle=true)
Static Public Attributes
static UInt const maxUInt = ((UInt)(-1))
static size_type const numBits = (sizeof(UInt)*8)
Private Member Functions
template<class Operator >
void unaryAssign (Operator op=Operator())
template<class Operator >
void binaryAssign (UnsignedIntegerCalc const &other, Operator op=Operator())
Private Attributes
size_type m_size
UInt * m_values
Detailed Description
template<typename UInt>
class beast::UnsignedIntegerCalc< UInt >
Multiprecision unsigned integer suitable for calculations.
The data is stored in "calculation" format, which means it can be readily used for performing calculations, but no raw access to the bytes are provided. To transmit a serialized unsigned integer or perform base encodings, it must be converted back into UnsignedInteger. The number is represented as a series of native UInt unsigned integer types, in order of increasing significance.
This is a lightweight object, storage and ownership of the underlying data buffer is an external responsibility. The makes the class cheap to copy and pass by value.
A consequence of this ownership model is that arithmetics operators which return results by value cannot be included in the interface.
Definition at line 69 of file UnsignedIntegerCalc.h.
Member Typedef Documentation
template<typename UInt > typedef std::size_t beast::UnsignedIntegerCalc< UInt >::size_type
Definition at line 74 of file UnsignedIntegerCalc.h.
template<typename UInt > typedef detail::DoubleWidthUInt<UInt>::type beast::UnsignedIntegerCalc< UInt >::UIntBig
Definition at line 72 of file UnsignedIntegerCalc.h.
Constructor & Destructor Documentation
template<typename UInt > beast::UnsignedIntegerCalc< UInt >::UnsignedIntegerCalc () inline
Construct an empty integer / zero bits.
Definition at line 82 of file UnsignedIntegerCalc.h.
Referenced by beast::UnsignedIntegerCalc< UInt >::fromCanonical().
         : m_size (0)
         , m_values (nullptr)
     {
     }
template<typename UInt > beast::UnsignedIntegerCalc< UInt >::UnsignedIntegerCalc (UnsignedIntegerCalc< UInt > const & other) inline
Construct a reference to an existing buffer.
Definition at line 89 of file UnsignedIntegerCalc.h.
         : m_size (other.m_size)
         , m_values (other.m_values)
     {
     }
template<typename UInt > beast::UnsignedIntegerCalc< UInt >::UnsignedIntegerCalc (size_type count, UInt * values) inline
Construct from an existing array of values. The existing data must already be in the "calculation" format.
Definition at line 98 of file UnsignedIntegerCalc.h.
         : m_size (count)
         , m_values (values)
     {
     }
Member Function Documentation
template<typename UInt > template<class Operator > void beast::UnsignedIntegerCalc< UInt >::binaryAssign (UnsignedIntegerCalc< UInt > const & other, Operator op = Operator ()) inline private
Definition at line 425 of file UnsignedIntegerCalc.h.
References beast::UnsignedIntegerCalc< UInt >::m_values, and beast::UnsignedIntegerCalc< UInt >::size().
Referenced by beast::UnsignedIntegerCalc< UInt >::operator&=(), beast::UnsignedIntegerCalc< UInt >::operator^=(), and beast::UnsignedIntegerCalc< UInt >::operator|=().
     {
         UInt* dest (m_values + size());
         size_type n (size());
         for (; n-- > other.size();)
             *--dest = 0;
         UInt const* rhs (other.m_values + n);
         for (UInt const* rhs (other.m_values + n); n--;)
             op (*--dest, *--rhs);
     }
template<typename UInt > void beast::UnsignedIntegerCalc< UInt >::clear () inline
Assign zero.
Definition at line 286 of file UnsignedIntegerCalc.h.
References beast::UnsignedIntegerCalc< UInt >::m_values, and beast::UnsignedIntegerCalc< UInt >::size().
     {
         UInt* dest (m_values - 1);
         for (size_type n (size()); n--;)
             *++dest = 0;
     }
template<typename UInt > int beast::UnsignedIntegerCalc< UInt >::compare (UnsignedIntegerCalc< UInt > const & other) const inline
Universal comparison. The comparison is performed numerically. The return values have the same meaning as memcmp().
Definition at line 223 of file UnsignedIntegerCalc.h.
References lhs, ripple::max(), and beast::UnsignedIntegerCalc< UInt >::size().
Referenced by beast::UnsignedIntegerCalc< UInt >::operator!=(), beast::UnsignedIntegerCalc< UInt >::operator<(), beast::UnsignedIntegerCalc< UInt >::operator<=(), beast::UnsignedIntegerCalc< UInt >::operator==(), beast::UnsignedIntegerCalc< UInt >::operator>(), and beast::UnsignedIntegerCalc< UInt >::operator>=().
     {
         if (size() == 0)
         {
             if (other.size() == 0)
                 return 0;
             return  -1;
         }
         else if (other.size() == 0)
         {
             return 1;
         }
         for (size_type n (std::max (size(), other.size())); n--;)
         {
             UInt lhs ((*this)[n]);
             UInt rhs (other[n]);
             if (lhs < rhs)
                 return -1;
             else if (lhs > rhs)
                 return 1;
         }
         return 0;
     }
template<typename UInt > bool beast::UnsignedIntegerCalc< UInt >::empty () const inline
Returns true if the buffer has 0 values.
Definition at line 198 of file UnsignedIntegerCalc.h.
References beast::UnsignedIntegerCalc< UInt >::m_size.
     {
         return m_size == 0;
     }
template<typename UInt > static UnsignedIntegerCalc beast::UnsignedIntegerCalc< UInt >::fromCanonical (void * buffer, size_type const bytes, bool swizzle = true) inline static
Convert to calculation format from canonical format. This overwrites the callers memory without transferring ownership. Canonical format is defined as a big endian byte oriented multiprecision integer format. The buffer should point to the beginning of the storage area and not the beginning of the canonical data. Bytes is the desired canonical bytes.
Definition at line 111 of file UnsignedIntegerCalc.h.
References beast::asio::swap(), and beast::UnsignedIntegerCalc< UInt >::UnsignedIntegerCalc().
Referenced by beast::UnsignedInteger< Bytes >::toCalcType().
     {
         UInt* const values (reinterpret_cast <UInt*> (buffer));
         size_type const count ((bytes + sizeof (UInt) - 1) / sizeof (UInt));
         if (swizzle)
         {
             // Zero fill the possibly uninitialized pad bytes
             std::memset (buffer, 0,
                 ((sizeof(UInt)-(bytes&(sizeof(UInt)-1)))&(sizeof(UInt)-1)));
             // Swap and swizzle
             UInt* lo (values);
             UInt* hi (values + count - 1);
             while (lo < hi)
             {
                 std::swap (*lo, *hi);
                 *lo = fromNetworkByteOrder <UInt> (*lo);
                 ++lo;
                 *hi = fromNetworkByteOrder <UInt> (*hi);
                 ++hi;
             }
             if (lo == hi)
                 *lo = fromNetworkByteOrder <UInt> (*lo);
         }
         return UnsignedIntegerCalc (count, values);
     }
template<typename UInt > bool beast::UnsignedIntegerCalc< UInt >::isNotZero () const inline
Returns true if this represents any number other than zero.
Definition at line 185 of file UnsignedIntegerCalc.h.
References beast::UnsignedIntegerCalc< UInt >::isZero().
Referenced by beast::UnsignedIntegerCalc< UInt >::operator bool().
     {
         return ! isZero ();
     }
template<typename UInt > bool beast::UnsignedIntegerCalc< UInt >::isZero () const inline
Returns true if this represents the number zero.
Definition at line 176 of file UnsignedIntegerCalc.h.
References beast::UnsignedIntegerCalc< UInt >::m_values, and beast::UnsignedIntegerCalc< UInt >::size().
Referenced by beast::UnsignedIntegerCalc< UInt >::isNotZero().
     {
         for (size_type n (size()); n--;)
             if (m_values [n] != 0)
                 return false;
         return true;
     }
template<typename UInt > beast::UnsignedIntegerCalc< UInt >::operator bool () const inline explicit
Safe conversion to bool, true means a non-zero value.
Definition at line 192 of file UnsignedIntegerCalc.h.
References beast::UnsignedIntegerCalc< UInt >::isNotZero().
     {
         return isNotZero ();
     }
template<typename UInt > bool beast::UnsignedIntegerCalc< UInt >::operator!= (UnsignedIntegerCalc< UInt > const & other) const inline
Determine inequality.
Definition at line 256 of file UnsignedIntegerCalc.h.
References beast::UnsignedIntegerCalc< UInt >::compare().
     {
         return compare (other) != 0;
     }
template<typename UInt > UInt beast::UnsignedIntegerCalc< UInt >::operator% (UInt rhs) const inline
Small modulus.
Definition at line 387 of file UnsignedIntegerCalc.h.
References lhs, beast::UnsignedIntegerCalc< UInt >::m_values, beast::UnsignedIntegerCalc< UInt >::numBits, and beast::UnsignedIntegerCalc< UInt >::size().
     {
         UIntBig modsq = 1;
         UIntBig result = 0;
         UInt const* lhs (m_values);
         for (size_type n (size()); n--; ++lhs)
         {
             for (int bit (0); bit < numBits; ++bit)
             {
                 if (((*lhs) & (1 << bit)) != 0)
                 {
                     result += modsq;
                     if (result >= rhs)
                         result -= rhs;
                 }
                 modsq <<= 1;
                 if (modsq >= rhs)
                     modsq -= rhs;
             }
         }
         return UInt (result);
     }
template<typename UInt > UnsignedIntegerCalc& beast::UnsignedIntegerCalc< UInt >::operator&= (UnsignedIntegerCalc< UInt > const & rhs) inline
Perform bitwise logical-and.
Definition at line 310 of file UnsignedIntegerCalc.h.
References beast::UnsignedIntegerCalc< UInt >::binaryAssign().
     {
         binaryAssign (rhs, And());
         return *this;
     }
template<typename UInt > UnsignedIntegerCalc& beast::UnsignedIntegerCalc< UInt >::operator*= (UInt rhs) inline
Perform small multiply.
Definition at line 356 of file UnsignedIntegerCalc.h.
References lhs, beast::UnsignedIntegerCalc< UInt >::m_values, beast::UnsignedIntegerCalc< UInt >::maxUInt, beast::UnsignedIntegerCalc< UInt >::numBits, and beast::UnsignedIntegerCalc< UInt >::size().
     {
         UIntBig carry (0);
         UInt* lhs (m_values - 1);
         for (size_type n (size()); n--;)
         {
             UIntBig part (carry);
             carry = 0;
             part += (*++lhs) * UIntBig(rhs);
             carry = part >> numBits;
             *lhs = UInt (part & maxUInt);
         }
         assert (carry == 0); // overflow
         return *this;
     }
template<typename UInt > UnsignedIntegerCalc& beast::UnsignedIntegerCalc< UInt >::operator+= (UnsignedIntegerCalc< UInt > const & v) inline
Perform addition.
Definition at line 324 of file UnsignedIntegerCalc.h.
References lhs, beast::UnsignedIntegerCalc< UInt >::m_values, beast::UnsignedIntegerCalc< UInt >::maxUInt, and beast::UnsignedIntegerCalc< UInt >::size().
Referenced by beast::UnsignedIntegerCalc< UInt >::operator+=().
     {
         UIntBig carry (0);
         UInt* lhs (m_values);
         UInt const* rhs (v.m_values - 1);
         for (size_type n (0); n<size() || n<v.size(); ++n)
         {
             UIntBig part (carry);
             carry = 0;
             if (n < size())
                 part += *lhs;
             if (n < v.size())
                 part += *++rhs;
             if (part > maxUInt)
             {
                 part &= maxUInt;
                 carry = 1;
             }
             *lhs++ = UInt (part);
         }
         assert (carry == 0); // overflow
         return *this;
     }
template<typename UInt > UnsignedIntegerCalc& beast::UnsignedIntegerCalc< UInt >::operator+= (UInt rhs) inline
Perform small addition.
Definition at line 349 of file UnsignedIntegerCalc.h.
References beast::UnsignedIntegerCalc< UInt >::operator+=().
     {
         UnsignedIntegerCalc const v (1, &rhs);
         return operator+= (v);
     }
template<typename UInt > UnsignedIntegerCalc beast::UnsignedIntegerCalc< UInt >::operator/= (UInt rhs) inline
Small division.
Definition at line 373 of file UnsignedIntegerCalc.h.
References lhs, beast::UnsignedIntegerCalc< UInt >::m_values, beast::UnsignedIntegerCalc< UInt >::numBits, and beast::UnsignedIntegerCalc< UInt >::size().
     {
         UIntBig dividend (0);
         UInt* lhs (m_values+size());
         for (size_type n (size()); n--;)
         {
             dividend |= *--lhs;
             *lhs = UInt (dividend / rhs);
             dividend = (dividend % rhs) << numBits;
         }
         return *this;
     }
template<typename UInt > bool beast::UnsignedIntegerCalc< UInt >::operator< (UnsignedIntegerCalc< UInt > const & other) const inline
Ordered comparison.
Definition at line 262 of file UnsignedIntegerCalc.h.
References beast::UnsignedIntegerCalc< UInt >::compare().
     {
         return compare (other) < 0;
     }
template<typename UInt > bool beast::UnsignedIntegerCalc< UInt >::operator<= (UnsignedIntegerCalc< UInt > const & other) const inline
Ordered comparison.
Definition at line 268 of file UnsignedIntegerCalc.h.
References beast::UnsignedIntegerCalc< UInt >::compare().
     {
         return compare (other) <= 0;
     }
template<typename UInt > UnsignedIntegerCalc& beast::UnsignedIntegerCalc< UInt >::operator= (UnsignedIntegerCalc< UInt > const & other) inline
Assign a value from another integer.
Note
This does not transfer the reference to the buffer, it copies the values from one buffer to the other.
Definition at line 162 of file UnsignedIntegerCalc.h.
References beast::UnsignedIntegerCalc< UInt >::m_values, and beast::UnsignedIntegerCalc< UInt >::size().
     {
         assert (other.size() <= size());
         size_type n (size());
         UInt* dest (m_values + size());
         for (; n-- > other.size();)
             *--dest = 0;
         UInt const* rhs (other.m_values + n);
         for (; n--;)
             *--dest = *--rhs;
         return *this;
     }
template<typename UInt > bool beast::UnsignedIntegerCalc< UInt >::operator== (UnsignedIntegerCalc< UInt > const & other) const inline
Determine equality.
Definition at line 250 of file UnsignedIntegerCalc.h.
References beast::UnsignedIntegerCalc< UInt >::compare().
     {
         return compare (other) == 0;
     }
template<typename UInt > bool beast::UnsignedIntegerCalc< UInt >::operator> (UnsignedIntegerCalc< UInt > const & other) const inline
Ordered comparison.
Definition at line 274 of file UnsignedIntegerCalc.h.
References beast::UnsignedIntegerCalc< UInt >::compare().
     {
         return compare (other) > 0;
     }
template<typename UInt > bool beast::UnsignedIntegerCalc< UInt >::operator>= (UnsignedIntegerCalc< UInt > const & other) const inline
Ordered comparison.
Definition at line 280 of file UnsignedIntegerCalc.h.
References beast::UnsignedIntegerCalc< UInt >::compare().
     {
         return compare (other) >= 0;
     }
template<typename UInt > UInt beast::UnsignedIntegerCalc< UInt >::operator[] (size_type n) const inline
Safe array indexing to arbitrary positions. If the index is out of range, zero is returned.
Definition at line 212 of file UnsignedIntegerCalc.h.
References beast::UnsignedIntegerCalc< UInt >::m_values, and beast::UnsignedIntegerCalc< UInt >::size().
     {
         if (n >= 0 && n < size())
             return m_values [n];
         return 0;
     }
template<typename UInt > UnsignedIntegerCalc& beast::UnsignedIntegerCalc< UInt >::operator^= (UnsignedIntegerCalc< UInt > const & rhs) inline
Perform bitwise logical-xor.
Definition at line 317 of file UnsignedIntegerCalc.h.
References beast::UnsignedIntegerCalc< UInt >::binaryAssign().
     {
         binaryAssign (rhs, Xor());
         return *this;
     }
template<typename UInt > UnsignedIntegerCalc& beast::UnsignedIntegerCalc< UInt >::operator|= (UnsignedIntegerCalc< UInt > const & rhs) inline
Perform bitwise logical-not. Perform bitwise logical-or.
Definition at line 303 of file UnsignedIntegerCalc.h.
References beast::UnsignedIntegerCalc< UInt >::binaryAssign().
     {
         binaryAssign (rhs, Or());
         return *this;
     }
template<typename UInt > size_type beast::UnsignedIntegerCalc< UInt >::size () const inline
Returns the size of the buffer, in values.
Definition at line 204 of file UnsignedIntegerCalc.h.
References beast::UnsignedIntegerCalc< UInt >::m_size.
Referenced by beast::UnsignedIntegerCalc< UInt >::binaryAssign(), beast::UnsignedIntegerCalc< UInt >::clear(), beast::UnsignedIntegerCalc< UInt >::compare(), beast::UnsignedIntegerCalc< UInt >::isZero(), beast::UnsignedIntegerCalc< UInt >::operator%(), beast::UnsignedIntegerCalc< UInt >::operator*=(), beast::UnsignedIntegerCalc< UInt >::operator+=(), beast::UnsignedIntegerCalc< UInt >::operator/=(), beast::UnsignedIntegerCalc< UInt >::operator=(), beast::UnsignedIntegerCalc< UInt >::operator[](), and beast::UnsignedIntegerCalc< UInt >::unaryAssign().
     {
         return m_size;
     }
template<typename UInt > void beast::UnsignedIntegerCalc< UInt >::toCanonical () inline
Convert the buffer back into canonical format. Since ownership was never transferred, the caller's data is restored to its original format. Typically this will be done as the last step of a series of operations.
Definition at line 143 of file UnsignedIntegerCalc.h.
References beast::UnsignedIntegerCalc< UInt >::m_size, beast::UnsignedIntegerCalc< UInt >::m_values, and beast::asio::swap().
     {
         // Swap and swizzle
         UInt* lo (m_values);
         UInt* hi (m_values + m_size - 1);
         while (lo < hi)
         {
             std::swap (*lo, *hi);
             *lo = toNetworkByteOrder <UInt> (*lo); ++lo;
             *hi = toNetworkByteOrder <UInt> (*hi); --hi;
         }
         if (lo == hi)
             *lo = toNetworkByteOrder <UInt> (*lo);
     }
template<typename UInt > template<class Operator > void beast::UnsignedIntegerCalc< UInt >::unaryAssign (Operator op = Operator()) inline private
Definition at line 417 of file UnsignedIntegerCalc.h.
References beast::UnsignedIntegerCalc< UInt >::m_values, and beast::UnsignedIntegerCalc< UInt >::size().
     {
         UInt* dest (m_values-1);
         for (size_type n (size()); n--;)
             op (*++dest);
     }
Member Data Documentation
template<typename UInt > size_type beast::UnsignedIntegerCalc< UInt >::m_size private
Definition at line 436 of file UnsignedIntegerCalc.h.
Referenced by beast::UnsignedIntegerCalc< UInt >::empty(), beast::UnsignedIntegerCalc< UInt >::size(), and beast::UnsignedIntegerCalc< UInt >::toCanonical().
template<typename UInt > UInt* beast::UnsignedIntegerCalc< UInt >::m_values private
Definition at line 437 of file UnsignedIntegerCalc.h.
Referenced by beast::UnsignedIntegerCalc< UInt >::binaryAssign(), beast::UnsignedIntegerCalc< UInt >::clear(), beast::UnsignedIntegerCalc< UInt >::isZero(), beast::UnsignedIntegerCalc< UInt >::operator%(), beast::UnsignedIntegerCalc< UInt >::operator*=(), beast::UnsignedIntegerCalc< UInt >::operator+=(), beast::UnsignedIntegerCalc< UInt >::operator/=(), beast::UnsignedIntegerCalc< UInt >::operator=(), beast::UnsignedIntegerCalc< UInt >::operator[](), beast::UnsignedIntegerCalc< UInt >::toCanonical(), and beast::UnsignedIntegerCalc< UInt >::unaryAssign().
template<typename UInt > UInt const beast::UnsignedIntegerCalc< UInt >::maxUInt = ((UInt)(-1)) static
Definition at line 76 of file UnsignedIntegerCalc.h.
Referenced by beast::UnsignedIntegerCalc< UInt >::operator*=(), and beast::UnsignedIntegerCalc< UInt >::operator+=().
template<typename UInt > size_type const beast::UnsignedIntegerCalc< UInt >::numBits = (sizeof(UInt)*8) static
Definition at line 77 of file UnsignedIntegerCalc.h.
Referenced by beast::UnsignedIntegerCalc< UInt >::operator%(), beast::UnsignedIntegerCalc< UInt >::operator*=(), and beast::UnsignedIntegerCalc< UInt >::operator/=().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/crypto/UnsignedIntegerCalc.h