rippled: rocksdb::InternalKeyComparator Class Reference
rocksdb::InternalKeyComparator Class Reference
#include <dbformat.h>
Public Member Functions
InternalKeyComparator (const Comparator *c)
virtual const char * Name () const
virtual int Compare (const Slice &a, const Slice &b) const
virtual void FindShortestSeparator (std::string *start, const Slice &limit) const
virtual void FindShortSuccessor (std::string *key) const
const Comparator * user_comparator () const
int Compare (const InternalKey &a, const InternalKey &b) const
Public Member Functions inherited from rocksdb::Comparator
virtual ~Comparator ()
Private Attributes
const Comparator * user_comparator_
std::string name_
Detailed Description
Definition at line 90 of file dbformat.h.
Constructor & Destructor Documentation
rocksdb::InternalKeyComparator::InternalKeyComparator (const Comparator * c) inline explicit
Definition at line 95 of file dbformat.h.
                                                       : user_comparator_(c),
     name_("rocksdb.InternalKeyComparator:" +
           std::string(user_comparator_->Name())) {
   }
Member Function Documentation
int rocksdb::InternalKeyComparator::Compare (const Slice & a, const Slice & b) const virtual
Implements rocksdb::Comparator.
Definition at line 56 of file dbformat.cc.
References rocksdb::BumpPerfCount(), rocksdb::Comparator::Compare(), rocksdb::Slice::data(), rocksdb::DecodeFixed64(), rocksdb::ExtractUserKey(), rocksdb::perf_context, rocksdb::Slice::size(), user_comparator_, and rocksdb::PerfContext::user_key_comparison_count.
Referenced by rocksdb::VersionSet::ApproximateOffsetOf(), rocksdb::VersionSet::Builder::CheckConsistency(), Compare(), FindShortestSeparator(), FindShortSuccessor(), rocksdb::Version::Get(), rocksdb::VersionSet::GetRange(), rocksdb::VersionSet::Builder::MaybeAddFile(), rocksdb::MemTable::KeyComparator::operator()(), rocksdb::VersionSet::Builder::BySmallestKey::operator()(), and rocksdb::Compaction::ShouldStopBefore().
{
   // Order by:
   //    increasing user key (according to user-supplied comparator)
   //    decreasing sequence number
   //    decreasing type (though sequence# should be enough to disambiguate)
   int r = user_comparator_->Compare(ExtractUserKey(akey), ExtractUserKey(bkey));
   BumpPerfCount(&perf_context.user_key_comparison_count);
   if (r == 0) {
     const uint64_t anum = DecodeFixed64(akey.data() + akey.size() - 8);
     const uint64_t bnum = DecodeFixed64(bkey.data() + bkey.size() - 8);
     if (anum > bnum) {
       r = -1;
     } else if (anum < bnum) {
       r = +1;
     }
   }
   return r;
 }
int rocksdb::InternalKeyComparator::Compare (const InternalKey & a, const InternalKey & b) const inline
Definition at line 153 of file dbformat.h.
References Compare(), and rocksdb::InternalKey::Encode().
{
   return Compare(a.Encode(), b.Encode());
 }
void rocksdb::InternalKeyComparator::FindShortestSeparator (std::string * start, const Slice & limit) const virtual
Implements rocksdb::Comparator.
Definition at line 75 of file dbformat.cc.
References rocksdb::Comparator::Compare(), Compare(), rocksdb::Slice::data(), rocksdb::ExtractUserKey(), rocksdb::Comparator::FindShortestSeparator(), rocksdb::kMaxSequenceNumber, rocksdb::kValueTypeForSeek, rocksdb::PackSequenceAndType(), rocksdb::PutFixed64(), rocksdb::Slice::size(), and user_comparator_.
Referenced by rocksdb::Shorten().
{
   // Attempt to shorten the user portion of the key
   Slice user_start = ExtractUserKey(*start);
   Slice user_limit = ExtractUserKey(limit);
   std::string tmp(user_start.data(), user_start.size());
   user_comparator_->FindShortestSeparator(&tmp, user_limit);
   if (tmp.size() < user_start.size() &&
       user_comparator_->Compare(user_start, tmp) < 0) {
     // User key has become shorter physically, but larger logically.
     // Tack on the earliest possible number to the shortened user key.
     PutFixed64(&tmp, PackSequenceAndType(kMaxSequenceNumber,kValueTypeForSeek));
     assert(this->Compare(*start, tmp) < 0);
     assert(this->Compare(tmp, limit) < 0);
     start->swap(tmp);
   }
 }
void rocksdb::InternalKeyComparator::FindShortSuccessor (std::string * key) const virtual
Implements rocksdb::Comparator.
Definition at line 94 of file dbformat.cc.
References rocksdb::Comparator::Compare(), Compare(), rocksdb::Slice::data(), rocksdb::ExtractUserKey(), rocksdb::Comparator::FindShortSuccessor(), rocksdb::kMaxSequenceNumber, rocksdb::kValueTypeForSeek, rocksdb::PackSequenceAndType(), rocksdb::PutFixed64(), rocksdb::Slice::size(), user_comparator_, and user_key.
Referenced by rocksdb::ShortSuccessor().
{
   Slice user_key = ExtractUserKey(*key);
   std::string tmp(user_key.data(), user_key.size());
   user_comparator_->FindShortSuccessor(&tmp);
   if (tmp.size() < user_key.size() &&
       user_comparator_->Compare(user_key, tmp) < 0) {
     // User key has become shorter physically, but larger logically.
     // Tack on the earliest possible number to the shortened user key.
     PutFixed64(&tmp, PackSequenceAndType(kMaxSequenceNumber,kValueTypeForSeek));
     assert(this->Compare(*key, tmp) < 0);
     key->swap(tmp);
   }
 }
const char * rocksdb::InternalKeyComparator::Name () const virtual
Implements rocksdb::Comparator.
Definition at line 52 of file dbformat.cc.
References name_.
{
   return name_.c_str();
 }
const Comparator* rocksdb::InternalKeyComparator::user_comparator () const inline
Definition at line 107 of file dbformat.h.
References user_comparator_.
Referenced by rocksdb::VersionSet::DumpManifest(), rocksdb::Version::ExtendOverlappingInputs(), rocksdb::Version::Get(), rocksdb::MemTable::Get(), rocksdb::Version::GetOverlappingInputs(), rocksdb::Version::GetOverlappingInputsBinarySearch(), rocksdb::Version::HasOverlappingUserKey(), rocksdb::Compaction::IsBaseLevelForKey(), rocksdb::VersionSet::Recover(), rocksdb::SomeFileOverlapsRange(), rocksdb::MemTable::Update(), rocksdb::DBImpl::user_comparator(), and rocksdb::VersionSet::WriteSnapshot().
 { return user_comparator_; }
Member Data Documentation
std::string rocksdb::InternalKeyComparator::name_ private
Definition at line 93 of file dbformat.h.
Referenced by Name().
const Comparator* rocksdb::InternalKeyComparator::user_comparator_ private
Definition at line 92 of file dbformat.h.
Referenced by Compare(), FindShortestSeparator(), FindShortSuccessor(), and user_comparator().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/db/dbformat.h
rippled/src/ripple/rocksdb/rocksdb/db/dbformat.cc