rippled: ripple::base_uint< BITS > Class Template Reference
ripple::base_uint< BITS > Class Template Reference
#include <base_uint.h>
Classes
struct FromVoid
class key_equal
Public Types
typedef std::size_t size_type
typedef std::ptrdiff_t difference_type
typedef unsigned char value_type
typedef value_type * pointer
typedef value_type & reference
typedef value_type const * const_pointer
typedef value_type const & const_reference
typedef pointer iterator
typedef const_pointer const_iterator
typedef std::reverse_iterator
< iterator > reverse_iterator
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator
typedef beast::hardened_hash
< base_uint > hasher
Public Member Functions
base_uint ()
pointer data ()
const_pointer data () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
const_iterator cbegin () const
const_iterator cend () const
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
bool isZero () const
bool isNonZero () const
bool operator! () const
const base_uint operator~ () const
base_uint & operator= (std::uint64_t uHost)
base_uint & operator^= (const base_uint &b)
base_uint & operator&= (const base_uint &b)
base_uint & operator|= (const base_uint &b)
base_uint & operator++ ()
const base_uint operator++ (int)
base_uint & operator-- ()
const base_uint operator-- (int)
base_uint & operator+= (const base_uint &b)
std::string GetHex () const
void SetHexExact (const char *psz)
bool SetHex (const char *psz, bool bStrict=false)
bool SetHex (const std::string &str, bool bStrict=false)
void SetHexExact (const std::string &str)
std::string ToString () const
unsigned int size () const
void zero ()
unsigned int GetSerializeSize (int nType=0) const
template<typename Stream >
void Serialize (Stream &s, int nType=0) const
template<typename Stream >
void Unserialize (Stream &s, int nType=0)
Static Public Attributes
static std::size_t const bytes = (BITS/8)
Protected Types
enum { WIDTH = BITS / 32 }
Protected Member Functions
base_uint (void const *data, FromVoid)
Protected Attributes
unsigned int pn [WIDTH]
Friends
class uint128
class uint160
class uint256
template<class Hasher >
void hash_append (Hasher &h, base_uint const &a) noexcept
int compare (const base_uint &a, const base_uint &b)
bool operator< (const base_uint &a, const base_uint &b)
bool operator<= (const base_uint &a, const base_uint &b)
bool operator> (const base_uint &a, const base_uint &b)
bool operator>= (const base_uint &a, const base_uint &b)
bool operator== (const base_uint &a, const base_uint &b)
bool operator!= (const base_uint &a, const base_uint &b)
int Testuint256AdHoc (std::vector< std::string > vArg)
Detailed Description
template<unsigned int BITS>
class ripple::base_uint< BITS >
Definition at line 51 of file base_uint.h.
Member Typedef Documentation
template<unsigned int BITS> typedef const_pointer ripple::base_uint< BITS >::const_iterator
Definition at line 85 of file base_uint.h.
template<unsigned int BITS> typedef value_type const* ripple::base_uint< BITS >::const_pointer
Definition at line 82 of file base_uint.h.
template<unsigned int BITS> typedef value_type const& ripple::base_uint< BITS >::const_reference
Definition at line 83 of file base_uint.h.
template<unsigned int BITS> typedef std::reverse_iterator<const_iterator> ripple::base_uint< BITS >::const_reverse_iterator
Definition at line 89 of file base_uint.h.
template<unsigned int BITS> typedef std::ptrdiff_t ripple::base_uint< BITS >::difference_type
Definition at line 78 of file base_uint.h.
template<unsigned int BITS> typedef beast::hardened_hash<base_uint> ripple::base_uint< BITS >::hasher
Value hashing function. The seed prevents crafted inputs from causing degenarate parent containers.
Definition at line 111 of file base_uint.h.
template<unsigned int BITS> typedef pointer ripple::base_uint< BITS >::iterator
Definition at line 84 of file base_uint.h.
template<unsigned int BITS> typedef value_type* ripple::base_uint< BITS >::pointer
Definition at line 80 of file base_uint.h.
template<unsigned int BITS> typedef value_type& ripple::base_uint< BITS >::reference
Definition at line 81 of file base_uint.h.
template<unsigned int BITS> typedef std::reverse_iterator<iterator> ripple::base_uint< BITS >::reverse_iterator
Definition at line 87 of file base_uint.h.
template<unsigned int BITS> typedef std::size_t ripple::base_uint< BITS >::size_type
Definition at line 77 of file base_uint.h.
template<unsigned int BITS> typedef unsigned char ripple::base_uint< BITS >::value_type
Definition at line 79 of file base_uint.h.
Member Enumeration Documentation
template<unsigned int BITS> anonymous enum protected
Enumerator
WIDTH
Definition at line 57 of file base_uint.h.
 { WIDTH = BITS / 32 };
Constructor & Destructor Documentation
template<unsigned int BITS> ripple::base_uint< BITS >::base_uint () inline
Construct uninitialized. Requirements: std::is_trivially_constructible<base_uint>::value == true
Definition at line 68 of file base_uint.h.
 { }
template<unsigned int BITS> ripple::base_uint< BITS >::base_uint (void const * data, FromVoid) inline protected
Construct from a raw pointer.
The buffer pointed to by data must be at least 32 bytes.
Definition at line 133 of file base_uint.h.
References ripple::base_uint< BITS >::pn.
     {
         memcpy (&pn [0], data, BITS / 8);
     }
Member Function Documentation
template<unsigned int BITS> iterator ripple::base_uint< BITS >::begin () inline
Definition at line 94 of file base_uint.h.
References ripple::base_uint< BITS >::data().
Referenced by ripple::Serializer::add128(), ripple::Serializer::add160(), ripple::Serializer::add256(), ripple::PeerImp::checkPropose(), ripple::SHAMapNode::ClassInit(), ripple::SimpleIdentifier< 32 >::construct(), ripple::AccountState::createGravatarUrl(), ripple::NodeStore::TestBase::PredictableObjectFactory::createObject(), ripple::PeerImp::doFetchPack(), ripple::PeerImp::doProofOfWork(), ripple::RPCHandler::doRandom(), ripple::NodeStore::DatabaseImp::fetchInternal(), ripple::Base58::fourbyte_hash256(), ripple::fpAppender(), ripple::Serializer::get128(), ripple::Serializer::get160(), ripple::Serializer::get256(), ripple::SHAMapNode::getChildNodeID(), ripple::ProofOfWork::getDifficulty(), ripple::base_uint< BITS >::GetHex(), ripple::PeerImp::getLedger(), ripple::CKey::GetPrivateKeyU(), ripple::ProofOfWorkFactoryImp::getProof(), ripple::CBigNum::getuint256(), ripple::STAccount::getValueH160(), ripple::RippleAddress::humanSeed1751(), ripple::ProofOfWorkFactoryImp::ProofOfWorkFactoryImp(), ripple::PeerImp::recvGetObjectByHash(), ripple::PeerImp::recvHaveTxSet(), ripple::PeerImp::recvHello(), ripple::PeerImp::recvLedger(), ripple::PeerImp::recvProofWork(), ripple::PeerImp::recvPropose(), ripple::PeerImp::recvStatus(), ripple::base_uint< BITS >::rend(), ripple::SHAMapNode::selectBranch(), ripple::LedgerConsensusImp::sendHaveTxSet(), ripple::PeerImp::sendHello(), ripple::RippleAddress::setAccountID(), ripple::RippleAddress::setAccountPrivate(), ripple::SHAMapNode::setMHash(), ripple::RippleAddress::setNodePrivate(), ripple::CKey::SetPrivateKeyU(), ripple::RippleAddress::setSeed(), ripple::RippleAddress::setSeedRandom(), ripple::CBigNum::setuint256(), ripple::STAccount::setValueH160(), ripple::SHAMapNode::SHAMapNode(), ripple::CKey::Sign(), ripple::STAccount::STAccount(), ripple::LedgerConsensusImp::statusChange(), ripple::strHex(), ripple::NetworkOPsImp::subServer(), ripple::NetworkOPsImp::switchLastClosedLedger(), ripple::uint160::to256(), ripple::TransactionAcquire::trigger(), ripple::InboundLedger::trigger(), and ripple::CKey::Verify().
 { return data(); }
template<unsigned int BITS> const_iterator ripple::base_uint< BITS >::begin () const inline
Definition at line 96 of file base_uint.h.
References ripple::base_uint< BITS >::data().
 { return data(); }
template<unsigned int BITS> const_iterator ripple::base_uint< BITS >::cbegin () const inline
Definition at line 98 of file base_uint.h.
References ripple::base_uint< BITS >::data().
Referenced by ripple::base_uint< BITS >::crend(), and ripple::SimpleIdentifier< 32 >::to_string().
 { return data(); }
template<unsigned int BITS> const_iterator ripple::base_uint< BITS >::cend () const inline
Definition at line 99 of file base_uint.h.
References ripple::base_uint< BITS >::bytes, and ripple::base_uint< BITS >::data().
Referenced by ripple::base_uint< BITS >::crbegin().
 { return data()+bytes; }
template<unsigned int BITS> const_reverse_iterator ripple::base_uint< BITS >::crbegin () const inline
Definition at line 105 of file base_uint.h.
References ripple::base_uint< BITS >::cend().
 { return cend(); }
template<unsigned int BITS> const_reverse_iterator ripple::base_uint< BITS >::crend () const inline
Definition at line 106 of file base_uint.h.
References ripple::base_uint< BITS >::cbegin().
 { return cbegin(); }
template<unsigned int BITS> pointer ripple::base_uint< BITS >::data () inline
Definition at line 91 of file base_uint.h.
References ripple::base_uint< BITS >::pn.
Referenced by ripple::base_uint< BITS >::begin(), ripple::base_uint< BITS >::cbegin(), ripple::base_uint< BITS >::cend(), ripple::base_uint< BITS >::end(), ripple::uint128::low128(), and ripple::CKey::Verify().
 { return reinterpret_cast<pointer>(pn); }
template<unsigned int BITS> const_pointer ripple::base_uint< BITS >::data () const inline
Definition at line 92 of file base_uint.h.
References ripple::base_uint< BITS >::pn.
 { return reinterpret_cast<const_pointer>(pn); }
template<unsigned int BITS> iterator ripple::base_uint< BITS >::end () inline
Definition at line 95 of file base_uint.h.
References ripple::base_uint< BITS >::bytes, and ripple::base_uint< BITS >::data().
Referenced by ripple::Serializer::add128(), ripple::Serializer::add160(), ripple::Serializer::add256(), ripple::AccountState::createGravatarUrl(), ripple::Base58::decodeWithCheck(), ripple::Ledger::getQuality(), ripple::Ledger::getQualityIndex(), ripple::RippleAddress::humanSeed1751(), ripple::uint160::operator=(), ripple::uint256::operator=(), ripple::base_uint< BITS >::operator=(), ripple::base_uint< BITS >::rbegin(), ripple::base_uint< BITS >::SetHex(), ripple::base_uint< BITS >::SetHexExact(), ripple::STAccount::setValueH160(), and ripple::STAccount::STAccount().
 { return data()+bytes; }
template<unsigned int BITS> const_iterator ripple::base_uint< BITS >::end () const inline
Definition at line 97 of file base_uint.h.
References ripple::base_uint< BITS >::bytes, and ripple::base_uint< BITS >::data().
 { return data()+bytes; }
template<unsigned int BITS> std::string ripple::base_uint< BITS >::GetHex () const inline
Definition at line 316 of file base_uint.h.
References ripple::base_uint< BITS >::begin(), ripple::base_uint< BITS >::size(), and ripple::strHex().
Referenced by ripple::DirectoryEntryIterator::addJson(), ripple::BookDirIterator::addJson(), ripple::InboundLedger::addPeers(), ripple::Ledger::assertSane(), ripple::LedgerMasterImp::checkAccept(), ripple::ProofOfWorkFactoryImp::checkProof(), ripple::STAmount::createHumanCurrency(), ripple::RPCHandler::doLedgerData(), ripple::RPCHandler::doProofSolve(), ripple::BookDirIterator::firstDirectory(), ripple::DirectoryEntryIterator::firstEntry(), ripple::Ledger::getAccountState(), ripple::FeaturesImpl::getCreate(), ripple::SerializedTransaction::getFullText(), ripple::SerializedLedgerEntry::getFullText(), ripple::SerializedLedgerEntry::getJson(), ripple::FeaturesImpl::getJson(), ripple::InboundLedger::getJson(), ripple::SerializedTransaction::getJson(), ripple::LedgerConsensusImp::getJson(), ripple::RippleState::getJson(), ripple::LedgerProposal::getJson(), ripple::Ledger::getJson(), ripple::PeerImp::getLedger(), ripple::BookDirIterator::getOfferIterator(), ripple::ProofOfWorkFactoryImp::getProof(), ripple::STAmount::getRaw(), ripple::SHAMapNode::getString(), ripple::SHAMapTreeNode::getString(), ripple::SerializedLedgerEntry::getText(), ripple::STHash128::getText(), ripple::STHash160::getText(), ripple::STHash256::getText(), ripple::PeerImp::json(), ripple::Ledger::loadByHash(), ripple::BookDirIterator::nextDirectory(), ripple::DirectoryEntryIterator::nextEntry(), ripple::LedgerConsensusImp::peerPosition(), ripple::RippleCalc::rippleCalc(), ripple::CKey_test::run(), ripple::Ledger::saveValidatedLedger(), ripple::UniqueNodeListImp::setSeedDomains(), ripple::UniqueNodeListImp::setSeedNodes(), and ripple::base_uint< BITS >::ToString().
     {
         return strHex (begin (), size ());
     }
template<unsigned int BITS> unsigned int ripple::base_uint< BITS >::GetSerializeSize (int nType = 0) const inline
Definition at line 452 of file base_uint.h.
References ripple::base_uint< BITS >::pn.
Referenced by ripple::PeerImp::sendHello().
     {
         return sizeof (pn);
     }
template<unsigned int BITS> bool ripple::base_uint< BITS >::isNonZero () const inline
Definition at line 147 of file base_uint.h.
References ripple::base_uint< BITS >::isZero().
Referenced by ripple::Ledger::assertSane(), ripple::NetworkOPsImp::checkLastClosedLedger(), ripple::PeerImp::checkPropose(), ripple::ChangeTransactor::checkSig(), ripple::SHAMap::delItem(), ripple::LedgerMasterImp::doAdvance(), ripple::RPCHandler::doLedgerEntry(), ripple::RPCHandler::doRipplePathFind(), ripple::InboundLedgersImp::dropLedger(), ripple::LedgerEntrySet::entryCache(), ripple::LedgerEntrySet::entryCreate(), ripple::InboundLedgersImp::find(), ripple::InboundLedgersImp::findCreate(), ripple::LedgerMasterImp::fixMismatch(), ripple::TransactionMetaSet::getAffectedAccounts(), ripple::ValidationsImp::getCurrentValidations(), ripple::LedgerCleanerImp::getHash(), ripple::LedgerMasterImp::getHashBySeq(), ripple::Ledger::getHashesByIndex(), ripple::LedgerMasterImp::getLedgerHash(), ripple::SerializedTransaction::getMentionedAccounts(), ripple::Ledger::getNeededAccountStateHashes(), ripple::Ledger::getNeededTransactionHashes(), ripple::LedgerMasterImp::getNeededValidations(), ripple::LedgerEntrySet::getNextLedgerIndex(), ripple::SerializedLedgerEntry::getOwners(), ripple::InboundLedgersImp::hasLedger(), ripple::Ledger::isValidBook(), ripple::Ledger::Ledger(), ripple::PathRequest::parseJson(), ripple::Pathfinder::Pathfinder(), ripple::ChangeTransactor::preCheck(), ripple::PeerImp::recvPropose(), ripple::SerializedValidation::SerializedValidation(), ripple::SHAMapTreeNode::setChildHash(), ripple::Ledger::visitStateItems(), and ripple::LedgerMasterImp::walkHashBySeq().
     {
         return !isZero ();
     }
template<unsigned int BITS> bool ripple::base_uint< BITS >::isZero () const inline
Definition at line 138 of file base_uint.h.
References ripple::base_uint< BITS >::pn, and ripple::base_uint< BITS >::WIDTH.
Referenced by ripple::FeaturesImpl::addKnown(), ripple::Pathfinder::addLink(), ripple::OrderBookDB::addOrderBook(), ripple::LedgerHistory::builtLedger(), ripple::RippleCalc::calcNodeAccountFwd(), ripple::STAmount::canonicalize(), ripple::STAmount::createHumanCurrency(), ripple::STAmount::divRound(), ripple::PaymentTransactor::doApply(), ripple::RPCHandler::doFeature(), ripple::LedgerCleanerImp::doLedgerCleaner(), ripple::PeerImp::doProofOfWork(), ripple::RPCHandler::doRipplePathFind(), ripple::PathRequest::doUpdate(), ripple::LedgerMasterImp::findNewLedgersToPublish(), ripple::Pathfinder::findPaths(), ripple::LedgerCleanerImp::getHash(), ripple::LedgerMasterImp::getLedgerByHash(), ripple::LedgerMasterImp::getLedgerHash(), ripple::SHAMapNode::getString(), ripple::LedgerConsensusImp::getTransactionTree(), ripple::SHAMapMissingNode::hasTargetIndex(), ripple::STAmount::isDefault(), ripple::STHash128::isDefault(), ripple::STHash160::isDefault(), ripple::STHash256::isDefault(), ripple::base_uint< BITS >::isNonZero(), ripple::STPathElement::isOffer(), ripple::Ledger::isValidBook(), ripple::Pathfinder::matchesOrigin(), ripple::NetworkOPsImp::missingNodeInLedger(), ripple::STAmount::mulRound(), ripple::STAmount::multiply(), ripple::BookDirIterator::nextDirectory(), ripple::DirectoryEntryIterator::nextEntry(), ripple::base_uint< BITS >::operator!(), ripple::BookDirIterator::operator==(), ripple::PathRequest::parseJson(), ripple::Pathfinder::Pathfinder(), ripple::PeerImp::recvStatus(), ripple::BookDirIterator::resync(), ripple::ProofOfWork_test::run(), ripple::STAmount::setFullValue(), ripple::SHAMapTreeNode::SHAMapTreeNode(), ripple::STAmount::STAmount(), ripple::STPathElement::STPathElement(), ripple::LedgerEntrySet::threadTx(), ripple::NetworkOPsImp::tryStartConsensus(), ripple::updateHelper(), ripple::LedgerHistory::validatedLedger(), and ripple::LedgerMasterImp::walkHashBySeq().
     {
         for (int i = 0; i < WIDTH; i++)
             if (pn[i] != 0)
                 return false;
         return true;
     }
template<unsigned int BITS> bool ripple::base_uint< BITS >::operator! () const inline
Definition at line 152 of file base_uint.h.
References ripple::base_uint< BITS >::isZero().
     {
         return isZero ();
     }
template<unsigned int BITS> base_uint& ripple::base_uint< BITS >::operator&= (const base_uint< BITS > & b) inline
Definition at line 185 of file base_uint.h.
References ripple::base_uint< BITS >::pn, and ripple::base_uint< BITS >::WIDTH.
     {
         for (int i = 0; i < WIDTH; i++)
             pn[i] &= b.pn[i];
         return *this;
     }
template<unsigned int BITS> base_uint& ripple::base_uint< BITS >::operator++ () inline
Definition at line 201 of file base_uint.h.
References ripple::base_uint< BITS >::pn, and ripple::base_uint< BITS >::WIDTH.
     {
         // prefix operator
         for (int i = WIDTH - 1; i >= 0; --i)
         {
             pn[i] = htobe32 (be32toh (pn[i]) + 1);
             if (pn[i] != 0)
                 break;
         }
         return *this;
     }
template<unsigned int BITS> const base_uint ripple::base_uint< BITS >::operator++ (int) inline
Definition at line 215 of file base_uint.h.
     {
         // postfix operator
         const base_uint ret = *this;
         ++ (*this);
         return ret;
     }
template<unsigned int BITS> base_uint& ripple::base_uint< BITS >::operator+= (const base_uint< BITS > & b) inline
Definition at line 247 of file base_uint.h.
References ripple::base_uint< BITS >::pn, and ripple::base_uint< BITS >::WIDTH.
     {
         std::uint64_t carry = 0;
         for (int i = WIDTH; i--;)
         {
             std::uint64_t n = carry + be32toh (pn[i]) + be32toh (b.pn[i]);
             pn[i] = htobe32 (n & 0xffffffff);
             carry = n >> 32;
         }
         return *this;
     }
template<unsigned int BITS> base_uint& ripple::base_uint< BITS >::operator-- () inline
Definition at line 224 of file base_uint.h.
References ripple::base_uint< BITS >::pn, prev, and ripple::base_uint< BITS >::WIDTH.
     {
         for (int i = WIDTH - 1; i >= 0; --i)
         {
             std::uint32_t prev = pn[i];
             pn[i] = htobe32 (be32toh (pn[i]) - 1);
             if (prev != 0)
                 break;
         }
         return *this;
     }
template<unsigned int BITS> const base_uint ripple::base_uint< BITS >::operator-- (int) inline
Definition at line 238 of file base_uint.h.
     {
         // postfix operator
         const base_uint ret = *this;
         -- (*this);
         return ret;
     }
template<unsigned int BITS> base_uint& ripple::base_uint< BITS >::operator= (std::uint64_t uHost) inline
Definition at line 167 of file base_uint.h.
References ripple::base_uint< BITS >::end(), and ripple::base_uint< BITS >::zero().
     {
         zero ();
         // Put in least significant bits.
         ((std::uint64_t*) end ())[-1] = htobe64 (uHost);
         return *this;
     }
template<unsigned int BITS> base_uint& ripple::base_uint< BITS >::operator^= (const base_uint< BITS > & b) inline
Definition at line 177 of file base_uint.h.
References ripple::base_uint< BITS >::pn, and ripple::base_uint< BITS >::WIDTH.
     {
         for (int i = 0; i < WIDTH; i++)
             pn[i] ^= b.pn[i];
         return *this;
     }
template<unsigned int BITS> base_uint& ripple::base_uint< BITS >::operator|= (const base_uint< BITS > & b) inline
Definition at line 193 of file base_uint.h.
References ripple::base_uint< BITS >::pn, and ripple::base_uint< BITS >::WIDTH.
     {
         for (int i = 0; i < WIDTH; i++)
             pn[i] |= b.pn[i];
         return *this;
     }
template<unsigned int BITS> const base_uint ripple::base_uint< BITS >::operator~ () const inline
Definition at line 157 of file base_uint.h.
References ripple::base_uint< BITS >::pn, and ripple::base_uint< BITS >::WIDTH.
     {
         base_uint ret;
         for (int i = 0; i < WIDTH; i++)
             ret.pn[i] = ~pn[i];
         return ret;
     }
template<unsigned int BITS> reverse_iterator ripple::base_uint< BITS >::rbegin () inline
Definition at line 101 of file base_uint.h.
References ripple::base_uint< BITS >::end().
 { return end(); }
template<unsigned int BITS> const_reverse_iterator ripple::base_uint< BITS >::rbegin () const inline
Definition at line 103 of file base_uint.h.
References ripple::base_uint< BITS >::end().
 { return end(); }
template<unsigned int BITS> reverse_iterator ripple::base_uint< BITS >::rend () inline
Definition at line 102 of file base_uint.h.
References ripple::base_uint< BITS >::begin().
 { return begin(); }
template<unsigned int BITS> const_reverse_iterator ripple::base_uint< BITS >::rend () const inline
Definition at line 104 of file base_uint.h.
References ripple::base_uint< BITS >::begin().
 { return begin(); }
template<unsigned int BITS> template<typename Stream > void ripple::base_uint< BITS >::Serialize (Stream & s, int nType = 0) const inline
Definition at line 458 of file base_uint.h.
References ripple::base_uint< BITS >::pn.
     {
         s.write ((char*)pn, sizeof (pn));
     }
template<unsigned int BITS> bool ripple::base_uint< BITS >::SetHex (const char * psz, bool bStrict = false) inline
Definition at line 362 of file base_uint.h.
References ripple::base_uint< BITS >::end(), ripple::base_uint< BITS >::size(), and ripple::base_uint< BITS >::zero().
Referenced by ripple::FeaturesImpl::addKnown(), ripple::addTxnSeqField(), ripple::ProofOfWorkFactoryImp::checkProof(), ripple::STAmount::currencyFromString(), ripple::RPCHandler::doFeature(), ripple::RPCHandler::doLedgerData(), ripple::RPCHandler::doLedgerEntry(), ripple::RPCHandler::doTransactionEntry(), ripple::ProofOfWorkFactoryImp::getPowEntry(), ripple::UniqueNodeListImp::getSeedDomains(), ripple::UniqueNodeListImp::getSeedNodes(), ripple::ApplicationImp::loadOldLedger(), ripple::RPC::lookupLedger(), ripple::STParsedJSON::parse(), ripple::ProofOfWork::ProofOfWork(), ripple::CKey_test::run(), ripple::SHAMap_test::run(), ripple::ProofOfWorkFactoryImp::setDifficulty(), ripple::base_uint< BITS >::SetHex(), ripple::DirectoryEntryIterator::setJson(), ripple::RippleAddress::setSeedGeneric(), ripple::STHash128::STHash128(), ripple::STHash160::STHash160(), ripple::STHash256::STHash256(), ripple::uint160::uint160(), and ripple::uint256::uint256().
     {
         // skip leading spaces
         if (!bStrict)
             while (isspace (*psz))
                 psz++;
         // skip 0x
         if (!bStrict && psz[0] == '0' && tolower (psz[1]) == 'x')
             psz += 2;
         // hex char to int
         static signed char phexdigit[256] =
         {
             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
             0, 1, 2, 3,  4, 5, 6, 7,  8, 9, -1, -1, -1, -1, -1, -1,
             -1, 0xa, 0xb, 0xc, 0xd, 0xe, 0xf, -1, -1, -1, -1, -1, -1, -1, -1, -1,
             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
             -1, 0xa, 0xb, 0xc, 0xd, 0xe, 0xf, -1, -1, -1, -1, -1, -1, -1, -1, -1,
             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
         };
         const unsigned char* pEnd   = reinterpret_cast<const unsigned char*> (psz);
         const unsigned char* pBegin = pEnd;
         // Find end.
         while (phexdigit[*pEnd] >= 0)
             pEnd++;
         // Take only last digits of over long string.
         if ((unsigned int) (pEnd - pBegin) > 2 * size ())
             pBegin = pEnd - 2 * size ();
         unsigned char* pOut = end () - ((pEnd - pBegin + 1) / 2);
         zero ();
         if ((pEnd - pBegin) & 1)
             *pOut++ = phexdigit[*pBegin++];
         while (pBegin != pEnd)
         {
             unsigned char   cHigh   = phexdigit[*pBegin++] << 4;
             unsigned char   cLow    = pBegin == pEnd
                                       ? 0
                                       : phexdigit[*pBegin++];
             *pOut++ = cHigh | cLow;
         }
         return !*pEnd;
     }
template<unsigned int BITS> bool ripple::base_uint< BITS >::SetHex (const std::string & str, bool bStrict = false) inline
Definition at line 427 of file base_uint.h.
References ripple::base_uint< BITS >::SetHex().
     {
         return SetHex (str.c_str (), bStrict);
     }
template<unsigned int BITS> void ripple::base_uint< BITS >::SetHexExact (const char * psz) inline
Definition at line 321 of file base_uint.h.
References ripple::base_uint< BITS >::end(), and ripple::base_uint< BITS >::pn.
Referenced by ripple::Ledger::getHashByIndex(), ripple::Ledger::getHashesByIndex(), ripple::Ledger::getSQL(), ripple::Ledger::getSQL1(), ripple::base_uint< BITS >::SetHexExact(), ripple::BookDirIterator::setJson(), and ripple::SqliteBackend::visitAll().
     {
         // must be precisely the correct number of hex digits
         static signed char phexdigit[256] =
         {
             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
             0, 1, 2, 3,  4, 5, 6, 7,  8, 9, -1, -1, -1, -1, -1, -1,
             -1, 0xa, 0xb, 0xc, 0xd, 0xe, 0xf, -1, -1, -1, -1, -1, -1, -1, -1, -1,
             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
             -1, 0xa, 0xb, 0xc, 0xd, 0xe, 0xf, -1, -1, -1, -1, -1, -1, -1, -1, -1,
             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
         };
         char* pOut  = reinterpret_cast<char*> (pn);
         for (int i = 0; i < sizeof (pn); ++i)
         {
             *pOut = phexdigit[*psz++] << 4;
             *pOut++ |= phexdigit[*psz++];
         }
         assert (*psz == 0);
         assert (pOut == reinterpret_cast<char*> (end ()));
     }
template<unsigned int BITS> void ripple::base_uint< BITS >::SetHexExact (const std::string & str) inline
Definition at line 432 of file base_uint.h.
References ripple::base_uint< BITS >::SetHexExact().
     {
         SetHexExact (str.c_str ());
     }
template<unsigned int BITS> unsigned int ripple::base_uint< BITS >::size () const inline
Definition at line 442 of file base_uint.h.
References ripple::base_uint< BITS >::pn.
Referenced by ripple::NodeStore::TestBase::PredictableObjectFactory::createObject(), ripple::PeerImp::doProofOfWork(), ripple::RPCHandler::doRandom(), ripple::base_uint< BITS >::GetHex(), ripple::PeerImp::getLedger(), ripple::CKey::GetPrivateKeyU(), ripple::ProofOfWorkFactoryImp::getProof(), ripple::CBigNum::getuint256(), ripple::ProofOfWorkFactoryImp::ProofOfWorkFactoryImp(), ripple::PeerImp::recvGetObjectByHash(), ripple::base_uint< BITS >::SetHex(), ripple::CKey::SetPrivateKeyU(), ripple::RippleAddress::setSeedRandom(), ripple::CBigNum::setuint256(), ripple::CKey::Sign(), ripple::LedgerConsensusImp::statusChange(), ripple::strHex(), ripple::NetworkOPsImp::subServer(), ripple::NetworkOPsImp::switchLastClosedLedger(), ripple::uint160::to256(), ripple::TransactionAcquire::trigger(), ripple::InboundLedger::trigger(), ripple::uint128::uint128(), and ripple::CKey::Verify().
     {
         return sizeof (pn);
     }
template<unsigned int BITS> std::string ripple::base_uint< BITS >::ToString () const inline
Definition at line 437 of file base_uint.h.
References ripple::base_uint< BITS >::GetHex().
Referenced by ripple::STAmount::createHumanCurrency(), ripple::LedgerEntrySet::dirAdd(), ripple::LedgerEntrySet::dirDelete(), ripple::TrustSetTransactor::doApply(), ripple::OfferCancelTransactor::doApply(), ripple::PaymentTransactor::doApply(), ripple::OfferCreateTransactor::doApply(), ripple::RPCHandler::doLedgerClosed(), ripple::RPCHandler::doLedgerEntry(), ripple::RPCHandler::doRandom(), ripple::RPCHandler::doWalletPropose(), ripple::Ledger::getBookBase(), ripple::NetworkOPsImp::getDirNodeInfo(), ripple::RPC::lookupLedger(), ripple::NetworkOPsImp::subServer(), ripple::OfferCreateTransactor::takeOffers(), and ripple::Testuint256AdHoc().
     {
         return GetHex ();
     }
template<unsigned int BITS> template<typename Stream > void ripple::base_uint< BITS >::Unserialize (Stream & s, int nType = 0) inline
Definition at line 464 of file base_uint.h.
References ripple::base_uint< BITS >::pn.
     {
         s.read ((char*)pn, sizeof (pn));
     }
template<unsigned int BITS> void ripple::base_uint< BITS >::zero () inline
Definition at line 447 of file base_uint.h.
References ripple::base_uint< BITS >::pn.
Referenced by ripple::STAmount::currencyFromString(), ripple::PeerImp::cycleStatus(), ripple::LedgerEntrySet::dirNext(), ripple::CKey::GenerateRootDeterministicKey(), ripple::CKey::GetPrivateKeyU(), ripple::UniqueNodeListImp::getSeedDomains(), ripple::UniqueNodeListImp::getSeedNodes(), ripple::SHAMapTreeNode::makeInner(), ripple::DirectoryEntryIterator::nextEntry(), ripple::uint160::operator=(), ripple::uint256::operator=(), ripple::base_uint< BITS >::operator=(), ripple::PeerImp::recvHello(), ripple::PeerImp::recvStatus(), ripple::PathState::setCanonical(), ripple::base_uint< BITS >::SetHex(), ripple::uint128::uint128(), ripple::uint160::uint160(), ripple::uint256::uint256(), ripple::Ledger::updateHash(), and ripple::SHAMapTreeNode::updateHash().
     {
         memset (&pn[0], 0, sizeof (pn));
     }
Friends And Related Function Documentation
template<unsigned int BITS> int compare (const base_uint< BITS > & a, const base_uint< BITS > & b) friend
Definition at line 269 of file base_uint.h.
     {
         const unsigned char* pA     = a.begin ();
         const unsigned char* pAEnd  = a.end ();
         const unsigned char* pB     = b.begin ();
         while (*pA == *pB)
         {
             if (++pA == pAEnd)
                 return 0;
             ++pB;
         }
         return (*pA < *pB) ? -1 : 1;
     }
template<unsigned int BITS> template<class Hasher > void hash_append (Hasher & h, base_uint< BITS > const & a) friend
Definition at line 263 of file base_uint.h.
     {
         using beast::hash_append;
         hash_append (h, a.pn);
     }
template<unsigned int BITS> bool operator!= (const base_uint< BITS > & a, const base_uint< BITS > & b) friend
Definition at line 311 of file base_uint.h.
     {
         return memcmp (a.pn, b.pn, sizeof (a.pn)) != 0;
     }
template<unsigned int BITS> bool operator< (const base_uint< BITS > & a, const base_uint< BITS > & b) friend
Definition at line 286 of file base_uint.h.
     {
         return compare (a, b) < 0;
     }
template<unsigned int BITS> bool operator<= (const base_uint< BITS > & a, const base_uint< BITS > & b) friend
Definition at line 291 of file base_uint.h.
     {
         return compare (a, b) <= 0;
     }
template<unsigned int BITS> bool operator== (const base_uint< BITS > & a, const base_uint< BITS > & b) friend
Definition at line 306 of file base_uint.h.
     {
         return memcmp (a.pn, b.pn, sizeof (a.pn)) == 0;
     }
template<unsigned int BITS> bool operator> (const base_uint< BITS > & a, const base_uint< BITS > & b) friend
Definition at line 296 of file base_uint.h.
     {
         return compare (a, b) > 0;
     }
template<unsigned int BITS> bool operator>= (const base_uint< BITS > & a, const base_uint< BITS > & b) friend
Definition at line 301 of file base_uint.h.
     {
         return compare (a, b) >= 0;
     }
template<unsigned int BITS> int Testuint256AdHoc (std::vector< std::string > vArg) friend
template<unsigned int BITS> friend class uint128 friend
Definition at line 469 of file base_uint.h.
template<unsigned int BITS> friend class uint160 friend
Definition at line 470 of file base_uint.h.
template<unsigned int BITS> friend class uint256 friend
Definition at line 471 of file base_uint.h.
Member Data Documentation
template<unsigned int BITS> std::size_t const ripple::base_uint< BITS >::bytes = (BITS/8) static
Definition at line 75 of file base_uint.h.
Referenced by ripple::base_uint< BITS >::cend(), ripple::base_uint< BITS >::end(), and ripple::uint128::uint128().
template<unsigned int BITS> unsigned int ripple::base_uint< BITS >::pn[WIDTH] protected
Definition at line 61 of file base_uint.h.
Referenced by ripple::base_uint< BITS >::base_uint(), ripple::base_uint< BITS >::data(), ripple::base_uint< BITS >::GetSerializeSize(), ripple::base_uint< BITS >::isZero(), ripple::base_uint< BITS >::operator&=(), ripple::base_uint< BITS >::operator++(), ripple::base_uint< BITS >::operator+=(), ripple::base_uint< BITS >::operator--(), ripple::uint160::operator=(), ripple::uint256::operator=(), ripple::uint128::operator=(), ripple::base_uint< BITS >::operator^=(), ripple::base_uint< BITS >::operator|=(), ripple::base_uint< BITS >::operator~(), ripple::base_uint< BITS >::Serialize(), ripple::base_uint< BITS >::SetHexExact(), ripple::base_uint< BITS >::size(), ripple::uint128::uint128(), ripple::uint160::uint160(), ripple::uint256::uint256(), ripple::base_uint< BITS >::Unserialize(), and ripple::base_uint< BITS >::zero().
The documentation for this class was generated from the following file:
rippled/src/ripple/types/api/base_uint.h