rippled: beast::FatalError Class Reference
beast::FatalError Class Reference
#include <FatalError.h>
Classes
struct Reporter
Public Member Functions
FatalError (char const *message, char const *filePath, int lineNumber)
Static Public Member Functions
static Reporter * getReporter ()
static Reporter * setReporter (Reporter *reporter)
Static Private Attributes
static Reporter * s_reporter
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
Signal a fatal error.
A fatal error indicates that the program has encountered an unexpected situation and cannot continue safely. Reasons for raising a fatal error would be to protect data integrity, prevent valuable resources from being wasted, or to ensure that the user does not experience undefined behavior.
This function will end the process with exit code EXIT_FAILURE. Before the process is terminated, a listener object gets notified so that the client application can perform logging or emit further diagnostics.
Definition at line 37 of file FatalError.h.
Constructor & Destructor Documentation
beast::FatalError::FatalError (char const * message, char const * filePath, int lineNumber)
Raise a fatal error.
If multiple threads raise an error, only one will succeed. The other threads will be blocked before the process terminates.
Parameters
message A null terminated string, which should come from a constant.
filePath Pass FILE here.
lineNumber Pass LINE here.
Definition at line 88 of file FatalError.cpp.
References beast::SystemStats::getStackBacktrace(), beast::FatalError::Reporter::onFatalError(), s_reporter, beast::Process::terminate(), and beast::String::toRawUTF8().
 {
     typedef CriticalSection LockType;
     static LockType s_mutex;
     std::lock_guard <LockType> lock (s_mutex);
     String const backtraceString = SystemStats::getStackBacktrace ();
     char const* const szStackBacktrace = backtraceString.toRawUTF8 ();
     String const fileNameString = fileName;
     char const* const szFileName = fileNameString.toRawUTF8 ();
     Reporter* const reporter (s_reporter);
     if (reporter != nullptr)
     {
         reporter->onFatalError (message, szStackBacktrace, szFileName, lineNumber);
     }
     Process::terminate ();
 }
Member Function Documentation
FatalError::Reporter * beast::FatalError::getReporter () static
Returns the current fatal error reporter.
Definition at line 76 of file FatalError.cpp.
References s_reporter.
 {
     return s_reporter;
 }
FatalError::Reporter * beast::FatalError::setReporter (Reporter * reporter) static
Set the fatal error reporter.
Note that if a fatal error is raised during the construction of objects with static storage duration, it might not be possible to set the reporter before the error is raised. The solution is not to use objects with static storage duration that have non-trivial constructors, use SharedSingleton instead.
The default behavior when no reporter is set is to invoke the base class version of Reporter::onFatalError.
If a reporter was previously set, this routine will do nothing.
Returns
The previous Reporter (Which may be null).
See Also
SharedSingleton, Reporter
Definition at line 81 of file FatalError.cpp.
References s_reporter.
Referenced by ripple::FatalErrorReporter::FatalErrorReporter(), and ripple::FatalErrorReporter::~FatalErrorReporter().
 {
     Reporter* const previous (s_reporter);
     s_reporter = reporter;
     return previous;
 }
Member Data Documentation
FatalError::Reporter * beast::FatalError::s_reporter static private
Definition at line 149 of file FatalError.h.
Referenced by FatalError(), getReporter(), and setReporter().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_core/diagnostic/FatalError.h
rippled/src/beast/modules/beast_core/diagnostic/FatalError.cpp