rippled: rocksdb::WriteBatchInternal Class Reference
rocksdb::WriteBatchInternal Class Reference
#include <write_batch_internal.h>
Static Public Member Functions
static int Count (const WriteBatch *batch)
static void SetCount (WriteBatch *batch, int n)
static SequenceNumber Sequence (const WriteBatch *batch)
static void SetSequence (WriteBatch *batch, SequenceNumber seq)
static Slice Contents (const WriteBatch *batch)
static size_t ByteSize (const WriteBatch *batch)
static void SetContents (WriteBatch *batch, const Slice &contents)
static Status InsertInto (const WriteBatch *batch, MemTable *memtable, const Options *opts, DB *db=nullptr, const bool filter_del=false)
static void Append (WriteBatch *dst, const WriteBatch *src)
Detailed Description
Definition at line 22 of file write_batch_internal.h.
Member Function Documentation
void rocksdb::WriteBatchInternal::Append (WriteBatch * dst, const WriteBatch * src) static
Definition at line 241 of file write_batch.cc.
References rocksdb::WriteBatch::Count(), rocksdb::kHeader, and rocksdb::WriteBatch::rep_.
Referenced by rocksdb::DBImpl::BuildBatchGroup(), and rocksdb::TEST().
{
   SetCount(dst, Count(dst) + Count(src));
   assert(src->rep_.size() >= kHeader);
   dst->rep_.append(src->rep_.data() + kHeader, src->rep_.size() - kHeader);
 }
static size_t rocksdb::WriteBatchInternal::ByteSize (const WriteBatch * batch) inline static
Definition at line 41 of file write_batch_internal.h.
References rocksdb::WriteBatch::rep_.
Referenced by rocksdb::DBImpl::BuildBatchGroup(), rocksdb::WALDumperCommand::DoCommand(), and rocksdb::DBImpl::Write().
{
     return batch->rep_.size();
   }
static Slice rocksdb::WriteBatchInternal::Contents (const WriteBatch * batch) inline static
Definition at line 37 of file write_batch_internal.h.
References rocksdb::WriteBatch::rep_.
Referenced by rocksdb::TEST(), and rocksdb::DBImpl::Write().
{
     return Slice(batch->rep_);
   }
int rocksdb::WriteBatchInternal::Count (const WriteBatch * batch) static
Definition at line 126 of file write_batch.cc.
References rocksdb::DecodeFixed32(), and rocksdb::WriteBatch::rep_.
Referenced by rocksdb::DBImpl::BuildBatchGroup(), rocksdb::WriteBatch::Count(), rocksdb::WriteBatch::Delete(), rocksdb::WALDumperCommand::DoCommand(), rocksdb::WriteBatch::Iterate(), rocksdb::WriteBatch::Merge(), rocksdb::PrintContents(), rocksdb::WriteBatch::Put(), rocksdb::DBImpl::RecoverLogFile(), rocksdb::TEST(), rocksdb::TransactionLogIteratorImpl::UpdateCurrentWriteBatch(), and rocksdb::DBImpl::Write().
{
   return DecodeFixed32(b->rep_.data() + 8);
 }
Status rocksdb::WriteBatchInternal::InsertInto (const WriteBatch * batch, MemTable * memtable, const Options * opts, DB * db = nullptr, const bool filter_del = false) static
Definition at line 228 of file write_batch.cc.
References rocksdb::WriteBatch::Iterate(), and Sequence().
Referenced by rocksdb::PrintContents(), rocksdb::DBImpl::RecoverLogFile(), rocksdb::TEST(), and rocksdb::DBImpl::Write().
{
   MemTableInserter inserter(WriteBatchInternal::Sequence(b), mem, opts, db,
                             filter_deletes);
   return b->Iterate(&inserter);
 }
SequenceNumber rocksdb::WriteBatchInternal::Sequence (const WriteBatch * batch) static
Definition at line 134 of file write_batch.cc.
References rocksdb::DecodeFixed64(), and rocksdb::WriteBatch::rep_.
Referenced by rocksdb::DBImpl::AppendSortedWalsOfType(), rocksdb::WALDumperCommand::DoCommand(), InsertInto(), rocksdb::TransactionLogIteratorImpl::IsBatchExpected(), rocksdb::DBImpl::RecoverLogFile(), rocksdb::TEST(), and rocksdb::TransactionLogIteratorImpl::UpdateCurrentWriteBatch().
{
   return SequenceNumber(DecodeFixed64(b->rep_.data()));
 }
void rocksdb::WriteBatchInternal::SetContents (WriteBatch * batch, const Slice & contents) static
Definition at line 236 of file write_batch.cc.
References rocksdb::Slice::data(), rocksdb::kHeader, rocksdb::WriteBatch::rep_, and rocksdb::Slice::size().
Referenced by rocksdb::WALDumperCommand::DoCommand(), rocksdb::DBImpl::ReadFirstLine(), rocksdb::DBImpl::RecoverLogFile(), rocksdb::TEST(), and rocksdb::TransactionLogIteratorImpl::UpdateCurrentWriteBatch().
{
   assert(contents.size() >= kHeader);
   b->rep_.assign(contents.data(), contents.size());
 }
void rocksdb::WriteBatchInternal::SetCount (WriteBatch * batch, int n) static
Definition at line 130 of file write_batch.cc.
References rocksdb::EncodeFixed32(), and rocksdb::WriteBatch::rep_.
Referenced by rocksdb::WriteBatch::Delete(), rocksdb::WriteBatch::Merge(), and rocksdb::WriteBatch::Put().
{
   EncodeFixed32(&b->rep_[8], n);
 }
void rocksdb::WriteBatchInternal::SetSequence (WriteBatch * batch, SequenceNumber seq) static
Definition at line 138 of file write_batch.cc.
References rocksdb::EncodeFixed64(), and rocksdb::WriteBatch::rep_.
Referenced by rocksdb::TEST(), and rocksdb::DBImpl::Write().
{
   EncodeFixed64(&b->rep_[0], seq);
 }
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/db/write_batch_internal.h
rippled/src/ripple/rocksdb/rocksdb/db/write_batch.cc