rippled: ripple::ApplicationImp Class Reference
ripple::ApplicationImp Class Reference
Classes
class sample_io_service_latency
Public Member Functions
ApplicationImp ()
CollectorManager & getCollectorManager ()
FullBelowCache & getFullBelowCache ()
JobQueue & getJobQueue ()
RPC::Manager & getRPCManager ()
SiteFiles::Manager & getSiteFiles ()
LocalCredentials & getLocalCredentials ()
NetworkOPs & getOPs ()
boost::asio::io_service & getIOService ()
LedgerMaster & getLedgerMaster ()
InboundLedgers & getInboundLedgers ()
TransactionMaster & getMasterTransaction ()
NodeCache & getTempNodeCache ()
NodeStore::Database & getNodeStore ()
Application::LockType & getMasterLock ()
LoadManager & getLoadManager ()
Resource::Manager & getResourceManager ()
TxQueue & getTxQueue ()
OrderBookDB & getOrderBookDB ()
PathRequests & getPathRequests ()
SLECache & getSLECache ()
Validators::Manager & getValidators ()
FeatureTable & getFeatureTable ()
LoadFeeTrack & getFeeTrack ()
IHashRouter & getHashRouter ()
Validations & getValidations ()
UniqueNodeList & getUNL ()
ProofOfWorkFactory & getProofOfWorkFactory ()
Overlay & overlay ()
bool running ()
bool getSystemTimeOffset (int &offset)
DatabaseCon * getRpcDB ()
DatabaseCon * getTxnDB ()
DatabaseCon * getLedgerDB ()
DatabaseCon * getWalletDB ()
bool isShutdown ()
void initSqliteDb (int index)
void initSqliteDbs ()
void setup ()
void prepareValidators ()
void onPrepare ()
void onStart ()
void onStop ()
void onWrite (beast::PropertyStream::Map &stream)
void run ()
void doStop ()
void signalStop ()
void onDeadlineTimer (beast::DeadlineTimer &timer)
void doSweep (Job &j)
Public Member Functions inherited from ripple::ApplicationImpBase
ApplicationImpBase ()
~ApplicationImpBase ()
Public Member Functions inherited from ripple::Application
Application ()
virtual ~Application ()
Public Member Functions inherited from beast::PropertyStream::Source
Source (std::string const &name)
~Source ()
std::string const & name () const
void add (Source &source)
template<class Derived >
Derived * add (Derived *child)
void remove (Source &child)
void removeAll ()
void write_one (PropertyStream &stream)
void write (PropertyStream &stream)
void write (PropertyStream &stream, std::string const &path)
std::pair< Source *, bool > find (std::string path)
Source * find_one_deep (std::string const &name)
PropertyStream::Source * find_path (std::string path)
PropertyStream::Source * find_one (std::string const &name)
Public Member Functions inherited from beast::RootStoppable
RootStoppable (char const *name)
~RootStoppable ()
bool isStopping () const
void prepare ()
void start ()
void stop (Journal journal=Journal())
void stopAsync ()
Public Member Functions inherited from beast::Stoppable
Stoppable (char const *name, Stoppable &parent)
virtual ~Stoppable ()
bool isStopping () const
bool isStopped () const
bool areChildrenStopped () const
void stopped ()
virtual void onChildrenStopped ()
Static Public Member Functions
static std::vector
< std::unique_ptr
< NodeStore::Factory > > make_Factories ()
static DatabaseCon * openDatabaseCon (const char *fileName, const char *dbInit[], int dbCount)
Static Public Member Functions inherited from ripple::ApplicationImpBase
static Application & getInstance ()
Public Attributes
beast::Journal m_journal
Application::LockType m_masterMutex
std::unique_ptr
< NodeStore::Manager > m_nodeStoreManager
NodeCache m_tempNodeCache
SLECache m_sleCache
LocalCredentials m_localCredentials
TransactionMaster m_txMaster
std::unique_ptr< CollectorManager > m_collectorManager
std::unique_ptr
< Resource::Manager > m_resourceManager
std::unique_ptr< FullBelowCache > m_fullBelowCache
NodeStoreScheduler m_nodeStoreScheduler
std::unique_ptr< JobQueue > m_jobQueue
IoServicePool m_mainIoPool
std::unique_ptr
< SiteFiles::Manager > m_siteFiles
std::unique_ptr< RPC::Manager > m_rpcManager
OrderBookDB m_orderBookDB
std::unique_ptr< PathRequests > m_pathRequests
std::unique_ptr< LedgerMaster > m_ledgerMaster
std::unique_ptr< InboundLedgers > m_inboundLedgers
std::unique_ptr< NetworkOPs > m_networkOPs
std::unique_ptr< UniqueNodeList > m_deprecatedUNL
std::unique_ptr< RPCHTTPServer > m_rpcHTTPServer
RPCServerHandler m_rpcServerHandler
std::unique_ptr
< NodeStore::Database > m_nodeStore
std::unique_ptr< SNTPClient > m_sntpClient
std::unique_ptr< TxQueue > m_txQueue
std::unique_ptr
< Validators::Manager > m_validators
std::unique_ptr< FeatureTable > m_featureTable
std::unique_ptr< LoadFeeTrack > mFeeTrack
std::unique_ptr< IHashRouter > mHashRouter
std::unique_ptr< Validations > mValidations
std::unique_ptr
< ProofOfWorkFactory > mProofOfWorkFactory
std::unique_ptr< LoadManager > m_loadManager
beast::DeadlineTimer m_sweepTimer
bool volatile mShutdown
std::unique_ptr< DatabaseCon > mRpcDB
std::unique_ptr< DatabaseCon > mTxnDB
std::unique_ptr< DatabaseCon > mLedgerDB
std::unique_ptr< DatabaseCon > mWalletDB
std::unique_ptr
< beast::asio::SSLContext > m_peerSSLContext
std::unique_ptr
< beast::asio::SSLContext > m_wsSSLContext
std::unique_ptr< Overlay > m_peers
std::unique_ptr< RPCDoor > m_rpcDoor
std::unique_ptr< WSDoor > m_wsPublicDoor
std::unique_ptr< WSDoor > m_wsPrivateDoor
std::unique_ptr< WSDoor > m_wsProxyDoor
beast::WaitableEvent m_stop
std::unique_ptr< ResolverAsio > m_resolver
beast::io_latency_probe
< std::chrono::steady_clock > m_probe
Private Member Functions
void updateTables ()
void startNewLedger ()
bool loadOldLedger (const std::string &, bool)
void onAnnounceAddress ()
Additional Inherited Members
Public Types inherited from ripple::Application
typedef RippleRecursiveMutex LockType
typedef std::unique_lock
< LockType > ScopedLockType
Static Public Attributes inherited from ripple::ApplicationImpBase
static Application * s_instance
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Protected Member Functions inherited from beast::Stoppable
Stoppable (char const *name, RootStoppable &root)
Protected Attributes inherited from beast::Stoppable
char const * m_name
RootStoppable & m_root
Child m_child
Atomic< int > m_started
bool volatile m_stopped
bool volatile m_childrenStopped
Children m_children
WaitableEvent m_stoppedEvent
Detailed Description
Definition at line 103 of file Application.cpp.
Constructor & Destructor Documentation
ripple::ApplicationImp::ApplicationImp () inline
Definition at line 213 of file Application.cpp.
References beast::PropertyStream::Source::add(), ripple::HashMaps::getInstance(), ripple::HashMaps::initializeNonce(), m_jobQueue, m_ledgerMaster, m_nodeStoreScheduler, m_resourceManager, and ripple::NodeStoreScheduler::setJobQueue().
         : RootStoppable ("Application")
         , m_journal (LogPartition::getJournal <ApplicationLog> ())
         , m_nodeStoreManager (NodeStore::make_Manager (
             std::move (make_Factories ())))
         , m_tempNodeCache ("NodeCache", 16384, 90, get_seconds_clock (),
             LogPartition::getJournal <TaggedCacheLog> ())
         , m_sleCache ("LedgerEntryCache", 4096, 120, get_seconds_clock (),
             LogPartition::getJournal <TaggedCacheLog> ())
         , m_collectorManager (CollectorManager::New (
             getConfig().insightSettings,
                 LogPartition::getJournal <CollectorManager> ()))
         , m_resourceManager (Resource::make_Manager (
             m_collectorManager->collector(),
                 LogPartition::getJournal <ResourceManagerLog> ()))
         , m_fullBelowCache (std::make_unique <FullBelowCache> (
             "full_below", get_seconds_clock (), m_collectorManager->collector (),
                 fullBelowTargetSize, fullBelowExpirationSeconds))
         , m_nodeStoreScheduler (*this)
         // The JobQueue has to come pretty early since
         // almost everything is a Stoppable child of the JobQueue.
         //
         , m_jobQueue (make_JobQueue (m_collectorManager->group ("jobq"),
             m_nodeStoreScheduler, LogPartition::getJournal <JobQueueLog> ()))
         // The io_service must be a child of the JobQueue since we call addJob
         // in response to newtwork data from peers and also client requests.
         //
         , m_mainIoPool (*m_jobQueue, "io", (getConfig ().NODE_SIZE >= 2) ? 2 : 1)
         //
         // Anything which calls addJob must be a descendant of the JobQueue
         //
         , m_siteFiles (SiteFiles::Manager::New (
             *this, LogPartition::getJournal <SiteFilesLog> ()))
         , m_rpcManager (RPC::make_Manager (LogPartition::getJournal <RPCManagerLog> ()))
         , m_orderBookDB (*m_jobQueue)
         , m_pathRequests ( new PathRequests (
             LogPartition::getJournal <PathRequestLog> (), m_collectorManager->collector ()))
         , m_ledgerMaster (LedgerMaster::New (
             *m_jobQueue, LogPartition::getJournal <LedgerMaster> ()))
         // VFALCO NOTE must come before NetworkOPs to prevent a crash due
         //             to dependencies in the destructor.
         //
         , m_inboundLedgers (InboundLedgers::New (get_seconds_clock (), *m_jobQueue,
                             m_collectorManager->collector ()))
         // VFALCO NOTE Does NetworkOPs depend on LedgerMaster?
         , m_networkOPs (NetworkOPs::New (get_seconds_clock (), *m_ledgerMaster,
             *m_jobQueue, LogPartition::getJournal <NetworkOPsLog> ()))
         // VFALCO NOTE LocalCredentials starts the deprecated UNL service
         , m_deprecatedUNL (UniqueNodeList::New (*m_jobQueue))
         , m_rpcHTTPServer (RPCHTTPServer::New (*m_networkOPs,
             LogPartition::getJournal <HTTPServerLog> (), *m_jobQueue, *m_networkOPs, *m_resourceManager))
         , m_rpcServerHandler (*m_networkOPs, *m_resourceManager) // passive object, not a Service
         , m_nodeStore (m_nodeStoreManager->make_Database ("NodeStore.main", m_nodeStoreScheduler,
             LogPartition::getJournal <NodeObject> (), 4, // four read threads for now
                 getConfig ().nodeDatabase, getConfig ().ephemeralNodeDatabase))
         , m_sntpClient (SNTPClient::New (*this))
         , m_txQueue (TxQueue::New ())
         , m_validators (add (Validators::Manager::New (
             *this,
             getConfig ().getModuleDatabasePath (),
             LogPartition::getJournal <ValidatorsLog> ())))
         , m_featureTable (make_FeatureTable (weeks(2), MAJORITY_FRACTION, // 200/256
             LogPartition::getJournal <FeaturesLog> ()))
         , mFeeTrack (LoadFeeTrack::New (LogPartition::getJournal <LoadManagerLog> ()))
         , mHashRouter (IHashRouter::New (IHashRouter::getDefaultHoldTime ()))
         , mValidations (Validations::New ())
         , mProofOfWorkFactory (ProofOfWorkFactory::New ())
         , m_loadManager (LoadManager::New (*this, LogPartition::getJournal <LoadManagerLog> ()))
         , m_sweepTimer (this)
         , mShutdown (false)
         , m_resolver (ResolverAsio::New (m_mainIoPool.getService (), beast::Journal ()))
         , m_probe (std::chrono::milliseconds (100), m_mainIoPool.getService())
     {
         add (m_resourceManager.get ());
         //
         // VFALCO - READ THIS!
         //
         //  Do not start threads, open sockets, or do any sort of "real work"
         //  inside the constructor. Put it in onStart instead. Or if you must,
         //  put it in setup (but everything in setup should be moved to onStart
         //  anyway.
         //
         //  The reason is that the unit tests require the Application object to
         //  be created (since so much code calls getApp()). But we don't actually
         //  start all the threads, sockets, and services when running the unit
         //  tests. Therefore anything which needs to be stopped will not get
         //  stopped correctly if it is started in this constructor.
         //
         // VFALCO HACK
         m_nodeStoreScheduler.setJobQueue (*m_jobQueue);
         add (m_ledgerMaster->getPropertySource ());
         // VFALCO TODO remove these once the call is thread safe.
         HashMaps::getInstance ().initializeNonce <size_t> ();
     }
Member Function Documentation
void ripple::ApplicationImp::doStop () inline
Definition at line 968 of file Application.cpp.
References beast::Journal::info, m_journal, beast::RootStoppable::stop(), and ripple::StopSustain().
Referenced by run().
     {
         m_journal.info << "Received shutdown request";
         StopSustain ();
         stop (m_journal);
     }
void ripple::ApplicationImp::doSweep (Job & j) inline
Definition at line 1004 of file Application.cpp.
References ripple::getConfig(), getInboundLedgers(), ripple::logTimedCall(), m_fullBelowCache, m_journal, m_ledgerMaster, m_networkOPs, m_nodeStore, m_sleCache, m_sweepTimer, m_tempNodeCache, m_txMaster, mValidations, beast::DeadlineTimer::setExpiration(), ripple::siSweepInterval, ripple::TransactionMaster::sweep(), ripple::AcceptedLedger::sweep(), ripple::Validations::sweep(), ripple::InboundLedgers::sweep(), ripple::LedgerMaster::sweep(), ripple::NodeStore::Database::sweep(), ripple::TaggedCache< uint256, SerializedLedgerEntry >::sweep(), ripple::TaggedCache< uint256, Blob >::sweep(), ripple::SHAMap::sweep(), ripple::NetworkOPs::sweepFetchPack(), and beast::Journal::warning.
Referenced by onDeadlineTimer().
     {
         // VFALCO NOTE Does the order of calls matter?
         // VFALCO TODO fix the dependency inversion using an observer,
         //         have listeners register for "onSweep ()" notification.
         //
         m_fullBelowCache->sweep ();
         logTimedCall (m_journal.warning, "TransactionMaster::sweep", __FILE__, __LINE__, boost::bind (
             &TransactionMaster::sweep, &m_txMaster));
         logTimedCall (m_journal.warning, "NodeStore::sweep", __FILE__, __LINE__, boost::bind (
             &NodeStore::Database::sweep, m_nodeStore.get ()));
         logTimedCall (m_journal.warning, "LedgerMaster::sweep", __FILE__, __LINE__, boost::bind (
             &LedgerMaster::sweep, m_ledgerMaster.get()));
         logTimedCall (m_journal.warning, "TempNodeCache::sweep", __FILE__, __LINE__, boost::bind (
             &NodeCache::sweep, &m_tempNodeCache));
         logTimedCall (m_journal.warning, "Validations::sweep", __FILE__, __LINE__, boost::bind (
             &Validations::sweep, mValidations.get ()));
         logTimedCall (m_journal.warning, "InboundLedgers::sweep", __FILE__, __LINE__, boost::bind (
             &InboundLedgers::sweep, &getInboundLedgers ()));
         logTimedCall (m_journal.warning, "SLECache::sweep", __FILE__, __LINE__, boost::bind (
             &SLECache::sweep, &m_sleCache));
         logTimedCall (m_journal.warning, "AcceptedLedger::sweep", __FILE__, __LINE__,
             &AcceptedLedger::sweep);
         logTimedCall (m_journal.warning, "SHAMap::sweep", __FILE__, __LINE__,
             &SHAMap::sweep);
         logTimedCall (m_journal.warning, "NetworkOPs::sweepFetchPack", __FILE__, __LINE__, boost::bind (
             &NetworkOPs::sweepFetchPack, m_networkOPs.get ()));
         // VFALCO NOTE does the call to sweep() happen on another thread?
         m_sweepTimer.setExpiration (getConfig ().getSize (siSweepInterval));
     }
CollectorManager& ripple::ApplicationImp::getCollectorManager () inline virtual
Implements ripple::Application.
Definition at line 348 of file Application.cpp.
References m_collectorManager.
     {
         return *m_collectorManager;
     }
FeatureTable& ripple::ApplicationImp::getFeatureTable () inline virtual
Implements ripple::Application.
Definition at line 453 of file Application.cpp.
References m_featureTable.
     {
         return *m_featureTable;
     }
LoadFeeTrack& ripple::ApplicationImp::getFeeTrack () inline virtual
Implements ripple::Application.
Definition at line 458 of file Application.cpp.
References mFeeTrack.
     {
         return *mFeeTrack;
     }
FullBelowCache& ripple::ApplicationImp::getFullBelowCache () inline virtual
Implements ripple::Application.
Definition at line 353 of file Application.cpp.
References m_fullBelowCache.
     {
         return *m_fullBelowCache;
     }
IHashRouter& ripple::ApplicationImp::getHashRouter () inline virtual
Implements ripple::Application.
Definition at line 463 of file Application.cpp.
References mHashRouter.
     {
         return *mHashRouter;
     }
InboundLedgers& ripple::ApplicationImp::getInboundLedgers () inline virtual
Implements ripple::Application.
Definition at line 393 of file Application.cpp.
References m_inboundLedgers.
Referenced by doSweep().
     {
         return *m_inboundLedgers;
     }
boost::asio::io_service& ripple::ApplicationImp::getIOService () inline virtual
Implements ripple::Application.
Definition at line 383 of file Application.cpp.
References m_mainIoPool.
     {
         return m_mainIoPool;
     }
JobQueue& ripple::ApplicationImp::getJobQueue () inline virtual
Implements ripple::Application.
Definition at line 358 of file Application.cpp.
References m_jobQueue.
     {
         return *m_jobQueue;
     }
DatabaseCon* ripple::ApplicationImp::getLedgerDB () inline virtual
Implements ripple::Application.
Definition at line 506 of file Application.cpp.
References mLedgerDB.
     {
         return mLedgerDB.get();
     }
LedgerMaster& ripple::ApplicationImp::getLedgerMaster () inline virtual
Implements ripple::Application.
Definition at line 388 of file Application.cpp.
References m_ledgerMaster.
Referenced by loadOldLedger(), and setup().
     {
         return *m_ledgerMaster;
     }
LoadManager& ripple::ApplicationImp::getLoadManager () inline virtual
Implements ripple::Application.
Definition at line 418 of file Application.cpp.
References m_loadManager.
     {
         return *m_loadManager;
     }
LocalCredentials& ripple::ApplicationImp::getLocalCredentials () inline virtual
Implements ripple::Application.
Definition at line 373 of file Application.cpp.
References m_localCredentials.
     {
         return m_localCredentials ;
     }
Application::LockType& ripple::ApplicationImp::getMasterLock () inline virtual
Implements ripple::Application.
Definition at line 413 of file Application.cpp.
References m_masterMutex.
     {
         return m_masterMutex;
     }
TransactionMaster& ripple::ApplicationImp::getMasterTransaction () inline virtual
Implements ripple::Application.
Definition at line 398 of file Application.cpp.
References m_txMaster.
     {
         return m_txMaster;
     }
NodeStore::Database& ripple::ApplicationImp::getNodeStore () inline virtual
Implements ripple::Application.
Definition at line 408 of file Application.cpp.
References m_nodeStore.
     {
         return *m_nodeStore;
     }
NetworkOPs& ripple::ApplicationImp::getOPs () inline virtual
Implements ripple::Application.
Definition at line 378 of file Application.cpp.
References m_networkOPs.
Referenced by setup().
     {
         return *m_networkOPs;
     }
OrderBookDB& ripple::ApplicationImp::getOrderBookDB () inline virtual
Implements ripple::Application.
Definition at line 433 of file Application.cpp.
References m_orderBookDB.
     {
         return m_orderBookDB;
     }
PathRequests& ripple::ApplicationImp::getPathRequests () inline virtual
Implements ripple::Application.
Definition at line 438 of file Application.cpp.
References m_pathRequests.
     {
         return *m_pathRequests;
     }
ProofOfWorkFactory& ripple::ApplicationImp::getProofOfWorkFactory () inline virtual
Implements ripple::Application.
Definition at line 478 of file Application.cpp.
References mProofOfWorkFactory.
     {
         return *mProofOfWorkFactory;
     }
Resource::Manager& ripple::ApplicationImp::getResourceManager () inline virtual
Implements ripple::Application.
Definition at line 423 of file Application.cpp.
References m_resourceManager.
     {
         return *m_resourceManager;
     }
DatabaseCon* ripple::ApplicationImp::getRpcDB () inline virtual
Implements ripple::Application.
Definition at line 498 of file Application.cpp.
References mRpcDB.
     {
         return mRpcDB.get();
     }
RPC::Manager& ripple::ApplicationImp::getRPCManager () inline virtual
Implements ripple::Application.
Definition at line 363 of file Application.cpp.
References m_rpcManager.
     {
         return *m_rpcManager;
     }
SiteFiles::Manager& ripple::ApplicationImp::getSiteFiles () inline virtual
Implements ripple::Application.
Definition at line 368 of file Application.cpp.
References m_siteFiles.
     {
         return *m_siteFiles;
     }
SLECache& ripple::ApplicationImp::getSLECache () inline virtual
Implements ripple::Application.
Definition at line 443 of file Application.cpp.
References m_sleCache.
     {
         return m_sleCache;
     }
bool ripple::ApplicationImp::getSystemTimeOffset (int & offset) inline virtual
Implements ripple::Application.
Definition at line 493 of file Application.cpp.
References m_sntpClient.
     {
         return m_sntpClient->getOffset (offset);
     }
NodeCache& ripple::ApplicationImp::getTempNodeCache () inline virtual
Implements ripple::Application.
Definition at line 403 of file Application.cpp.
References m_tempNodeCache.
     {
         return m_tempNodeCache;
     }
DatabaseCon* ripple::ApplicationImp::getTxnDB () inline virtual
Implements ripple::Application.
Definition at line 502 of file Application.cpp.
References mTxnDB.
Referenced by updateTables().
     {
         return mTxnDB.get();
     }
TxQueue& ripple::ApplicationImp::getTxQueue () inline virtual
Implements ripple::Application.
Definition at line 428 of file Application.cpp.
References m_txQueue.
     {
         return *m_txQueue;
     }
UniqueNodeList& ripple::ApplicationImp::getUNL () inline virtual
Implements ripple::Application.
Definition at line 473 of file Application.cpp.
References m_deprecatedUNL.
Referenced by setup().
     {
         return *m_deprecatedUNL;
     }
Validations& ripple::ApplicationImp::getValidations () inline virtual
Implements ripple::Application.
Definition at line 468 of file Application.cpp.
References mValidations.
     {
         return *mValidations;
     }
Validators::Manager& ripple::ApplicationImp::getValidators () inline virtual
Implements ripple::Application.
Definition at line 448 of file Application.cpp.
References m_validators.
     {
         return *m_validators;
     }
DatabaseCon* ripple::ApplicationImp::getWalletDB () inline virtual
Retrieve the "wallet database"
It looks like this is used to store the unique node list.
Implements ripple::Application.
Definition at line 510 of file Application.cpp.
References mWalletDB.
     {
         return mWalletDB.get();
     }
void ripple::ApplicationImp::initSqliteDb (int index) inline
Definition at line 529 of file Application.cpp.
References ripple::LedgerDBCount, ripple::LedgerDBInit, mLedgerDB, mRpcDB, mTxnDB, mWalletDB, openDatabaseCon(), ripple::RpcDBCount, ripple::RpcDBInit, ripple::TxnDBCount, ripple::TxnDBInit, ripple::WalletDBCount, and ripple::WalletDBInit.
Referenced by initSqliteDbs().
     {
         switch (index)
         {
         case 0: mRpcDB.reset (openDatabaseCon ("rpc.db", RpcDBInit, RpcDBCount)); break;
         case 1: mTxnDB.reset (openDatabaseCon ("transaction.db", TxnDBInit, TxnDBCount)); break;
         case 2: mLedgerDB.reset (openDatabaseCon ("ledger.db", LedgerDBInit, LedgerDBCount)); break;
         case 3: mWalletDB.reset (openDatabaseCon ("wallet.db", WalletDBInit, WalletDBCount)); break;
         };
     }
void ripple::ApplicationImp::initSqliteDbs () inline
Definition at line 540 of file Application.cpp.
References initSqliteDb().
Referenced by setup().
     {
         // VFALCO NOTE DBs are no longer initialized in parallel, since we
         //             dont want unowned threads and because ParallelFor
         //             is broken.
         //
         for (int i = 0; i < 4; ++i)
             initSqliteDb (i);
     }
bool ripple::ApplicationImp::isShutdown () inline virtual
Implements ripple::Application.
Definition at line 515 of file Application.cpp.
References mShutdown.
     {
         return mShutdown;
     }
bool ripple::ApplicationImp::loadOldLedger (const std::string & l, bool bReplay) private
Definition at line 1088 of file Application.cpp.
References beast::Journal::fatal, ripple::LedgerMaster::getCurrentLedger(), ripple::Ledger::getLastFullLedger(), getLedgerMaster(), hash, beast::Journal::info, ripple::Ledger::loadByHash(), ripple::Ledger::loadByIndex(), m_journal, m_ledgerMaster, m_networkOPs, ripple::base_uint< BITS >::SetHex(), and beast::Journal::warning.
Referenced by setup().
 {
     try
     {
         Ledger::pointer loadLedger, replayLedger;
         if (l.empty () || (l == "latest"))
             loadLedger = Ledger::getLastFullLedger ();
         else if (l.length () == 64)
         {
             // by hash
             uint256 hash;
             hash.SetHex (l);
             loadLedger = Ledger::loadByHash (hash);
         }
         else // assume by sequence
             loadLedger = Ledger::loadByIndex (beast::lexicalCastThrow <std::uint32_t> (l));
         if (!loadLedger)
         {
             m_journal.fatal << "No Ledger found?" << std::endl;
             return false;
         }
         if (bReplay)
         { // Replay a ledger close with same prior ledger and transactions
             replayLedger = loadLedger; // this ledger holds the transactions we want to replay
             loadLedger = Ledger::loadByIndex (replayLedger->getLedgerSeq() - 1); // this is the prior ledger
             if (!loadLedger || (replayLedger->getParentHash() != loadLedger->getHash()))
             {
                 m_journal.fatal << "Replay ledger missing/damaged";
                 assert (false);
                 return false;
             }
         }
         loadLedger->setClosed ();
         m_journal.info << "Loading ledger " << loadLedger->getHash () << " seq:" << loadLedger->getLedgerSeq ();
         if (loadLedger->getAccountHash ().isZero ())
         {
             m_journal.fatal << "Ledger is empty.";
             assert (false);
             return false;
         }
         if (!loadLedger->walkLedger ())
         {
             m_journal.fatal << "Ledger is missing nodes.";
             return false;
         }
         if (!loadLedger->assertSane ())
         {
             m_journal.fatal << "Ledger is not sane.";
             return false;
         }
         m_ledgerMaster->setLedgerRangePresent (loadLedger->getLedgerSeq (), loadLedger->getLedgerSeq ());
         Ledger::pointer openLedger = boost::make_shared<Ledger> (false, boost::ref (*loadLedger));
         m_ledgerMaster->switchLedgers (loadLedger, openLedger);
         m_ledgerMaster->forceValid(loadLedger);
         m_networkOPs->setLastCloseTime (loadLedger->getCloseTimeNC ());
         if (bReplay)
         { // inject transaction from replayLedger into consensus set
             SHAMap::ref txns = replayLedger->peekTransactionMap();
             Ledger::ref cur = getLedgerMaster().getCurrentLedger();
             for (SHAMapItem::pointer it = txns->peekFirstItem(); it != nullptr; it = txns->peekNextItem(it->getTag()))
             {
                 Transaction::pointer txn = replayLedger->getTransaction(it->getTag());
                 m_journal.info << txn->getJson(0);
                 Serializer s;
                 txn->getSTransaction()->add(s);
                 if (!cur->addTransaction(it->getTag(), s))
                 {
                     m_journal.warning << "Unable to add transaction " << it->getTag();
                 }
             }
         }
     }
     catch (SHAMapMissingNode&)
     {
         m_journal.fatal << "Data is missing for selected ledger";
         return false;
     }
     catch (boost::bad_lexical_cast&)
     {
         m_journal.fatal << "Ledger specified '" << l << "' is not valid";
         return false;
     }
     return true;
 }
static std::vector<std::unique_ptr <NodeStore::Factory> > ripple::ApplicationImp::make_Factories () inline static
Definition at line 199 of file Application.cpp.
References ripple::make_SqliteFactory().
     {
         std::vector <std::unique_ptr <NodeStore::Factory>> list;
         // VFALCO NOTE SqliteFactory is here because it has
         //             dependencies like SqliteDatabase and DatabaseCon
         //
         list.emplace_back (make_SqliteFactory ());
         return list;
     }
void ripple::ApplicationImp::onAnnounceAddress () private
Definition at line 1370 of file Application.cpp.
 {
     // NIKB CODEME
 }
void ripple::ApplicationImp::onDeadlineTimer (beast::DeadlineTimer & timer) inline virtual
Reimplemented from beast::DeadlineTimer::Listener.
Definition at line 983 of file Application.cpp.
References BIND_TYPE, doSweep(), beast::Journal::fatal, ripple::getApp(), ripple::getConfig(), ripple::jtSWEEP, m_jobQueue, m_journal, m_sweepTimer, P_1, and ripple::Application::signalStop().
     {
         if (timer == m_sweepTimer)
         {
             // VFALCO TODO Move all this into doSweep
             boost::filesystem::space_info space = boost::filesystem::space (getConfig ().DATA_DIR);
             // VFALCO TODO Give this magic constant a name and move it into a well documented header
             //
             if (space.available < (512 * 1024 * 1024))
             {
                 m_journal.fatal << "Remaining free disk space is less than 512MB";
                 getApp().signalStop ();
             }
             m_jobQueue->addJob(jtSWEEP, "sweep",
                 BIND_TYPE(&ApplicationImp::doSweep, this, P_1));
         }
     }
void ripple::ApplicationImp::onPrepare () inline virtual
Override called during preparation. Since all other Stoppable objects in the tree have already been constructed, this provides an opportunity to perform initialization which depends on calling into other Stoppable objects. This call is made on the same thread that called prepare(). The default implementation does nothing. Guaranteed to only be called once.
Reimplemented from beast::Stoppable.
Definition at line 840 of file Application.cpp.
References prepareValidators().
     {
         prepareValidators ();
     }
void ripple::ApplicationImp::onStart () inline virtual
Override called during start.
Reimplemented from beast::Stoppable.
Definition at line 845 of file Application.cpp.
References beast::Journal::debug, m_collectorManager, m_journal, m_probe, m_resolver, m_sweepTimer, beast::io_latency_probe< Clock >::sample(), and beast::DeadlineTimer::setExpiration().
     {
         m_journal.debug << "Application starting";
         m_sweepTimer.setExpiration (10);
         m_probe.sample (sample_io_service_latency (
             m_collectorManager->collector()->make_event (
                 "ios_latency"), LogPartition::getJournal <ApplicationLog> ()));
         m_resolver->start ();
     }
void ripple::ApplicationImp::onStop () inline virtual
Override called when the stop notification is issued.
The call is made on an unspecified, implementation-specific thread. onStop and onChildrenStopped will never be called concurrently, across all Stoppable objects descended from the same root, inclusive of the root.
It is safe to call isStopping, isStopped, and areChildrenStopped from within this function; The values returned will always be valid and never change during the callback.
The default implementation simply calls stopped(). This is applicable when the Stoppable has a trivial stop operation (or no stop operation), and we are merely using the Stoppable API to position it as a dependency of some parent service.
Thread safety: May not block for long periods. Guaranteed only to be called once. Must be safe to call from any thread at any time.
Reimplemented from beast::Stoppable.
Definition at line 859 of file Application.cpp.
References beast::DeadlineTimer::cancel(), beast::io_latency_probe< Clock >::cancel(), beast::io_latency_probe< Clock >::cancel_async(), beast::Journal::debug, m_journal, m_probe, m_resolver, m_sweepTimer, mShutdown, mValidations, and beast::Stoppable::stopped().
     {
         m_journal.debug << "Application stopping";
         m_probe.cancel_async ();
         // VFALCO Enormous hack, we have to force the probe to cancel
         //        before we stop the io_service queue or else it never
         //        unblocks in its destructor. The fix is to make all
         //        io_objects gracefully handle exit so that we can
         //        naturally return from io_service::run() instead of
         //        forcing a call to io_service::stop()
         m_probe.cancel ();
         m_resolver->stop_async ();
         // NIKB This is a hack - we need to wait for the resolver to
         //      stop. before we stop the io_server_queue or weird
         //      things will happen.
         m_resolver->stop ();
         m_sweepTimer.cancel ();
         // VFALCO TODO get rid of this flag
         mShutdown = true;
         mValidations->flush ();
         mShutdown = false;
         stopped ();
     }
void ripple::ApplicationImp::onWrite (beast::PropertyStream::Map &) inline virtual
Subclass override. The default version does nothing.
Reimplemented from beast::PropertyStream::Source.
Definition at line 896 of file Application.cpp.
     {
     }
static DatabaseCon* ripple::ApplicationImp::openDatabaseCon (const char * fileName, const char * dbInit[], int dbCount) inline static
Definition at line 522 of file Application.cpp.
Referenced by initSqliteDb().
     {
         return new DatabaseCon (fileName, dbInit, dbCount);
     }
Overlay& ripple::ApplicationImp::overlay () inline virtual
Implements ripple::Application.
Definition at line 483 of file Application.cpp.
References m_peers.
     {
         return *m_peers;
     }
void ripple::ApplicationImp::prepareValidators () inline
Definition at line 811 of file Application.cpp.
References ripple::getConfig(), m_validators, and beast::File::nonexistent().
Referenced by onPrepare().
     {
 #if 1
         {
             std::vector <std::string> const& strings (getConfig().validators);
             m_validators->addStrings ("rippled.cfg", strings);
         }
 #endif
 #if 1
         if (! getConfig().getValidatorsURL().empty())
         {
             m_validators->addURL (getConfig().getValidatorsURL());
         }
 #endif
 #if 1
         if (getConfig().getValidatorsFile() != beast::File::nonexistent ())
         {
             m_validators->addFile (getConfig().getValidatorsFile());
         }
 #endif
     }
void ripple::ApplicationImp::run (void) inline virtual
Implements ripple::Application.
Definition at line 902 of file Application.cpp.
References ripple::LoadManager::activateDeadlockDetector(), ripple::doShutdown, doStop(), ripple::getApp(), ripple::getConfig(), ripple::Application::getLoadManager(), beast::Journal::info, m_journal, m_stop, mShutdown, beast::RootStoppable::prepare(), beast::RootStoppable::start(), and beast::WaitableEvent::wait().
     {
         // VFALCO NOTE I put this here in the hopes that when unit tests run (which
         //             tragically require an Application object to exist or else they
         //             crash), the run() function will not get called and we will
         //             avoid doing silly things like contacting the SNTP server, or
         //             running the various logic threads like Validators, PeerFinder, etc.
         prepare ();
         start ();
         {
             if (!getConfig ().RUN_STANDALONE)
             {
                 // VFALCO NOTE This seems unnecessary. If we properly refactor the load
                 //             manager then the deadlock detector can just always be "armed"
                 //
                 getApp().getLoadManager ().activateDeadlockDetector ();
             }
         }
         // Wait for the stop signal
 #ifdef SIGINT
         for(;;)
         {
             bool const signaled (m_stop.wait (100));
             if (signaled)
                 break;
             // VFALCO NOTE It is unfortunate that we have to resort to
             //             polling but thats what the signal() interface
             //             forces us to do.
             //
             if (doShutdown)
                 break;
         }
 #else
         m_stop.wait ();
 #endif
         // Stop the server. When this returns, all
         // Stoppable objects should be stopped.
         doStop ();
         {
             // These two asssignment should no longer be necessary
             // once the WSDoor cancels its pending I/O correctly
             //m_wsPublicDoor = nullptr;
             //m_wsPrivateDoor = nullptr;
             //m_wsProxyDoor = nullptr;
             // VFALCO TODO Try to not have to do this early, by using observers to
             //             eliminate LoadManager's dependency inversions.
             //
             // This deletes the object and therefore, stops the thread.
             //m_loadManager = nullptr;
             m_journal.info << "Done.";
             // VFALCO NOTE This is a sign that something is wrong somewhere, it
             //             shouldn't be necessary to sleep until some flag is set.
             while (mShutdown)
                 boost::this_thread::sleep (boost::posix_time::milliseconds (100));
         }
     }
bool ripple::ApplicationImp::running () inline virtual
Implements ripple::Application.
Definition at line 489 of file Application.cpp.
References mTxnDB.
     {
         return mTxnDB != nullptr;
     }
void ripple::ApplicationImp::setup () inline virtual
Implements ripple::Application.
Definition at line 561 of file Application.cpp.
References beast::PropertyStream::Source::add(), ripple::RippleSSLContext::createAnonymous(), ripple::RippleSSLContext::createAuthenticated(), ripple::RippleSSLContext::createWebSocket(), ripple::Database::executeSQL(), beast::Journal::fatal, ripple::Config::FRESH, ripple::LogSink::get(), ripple::getApp(), ripple::getConfig(), ripple::DatabaseCon::getDB(), ripple::Application::getLedgerDB(), getLedgerMaster(), getOPs(), ripple::Application::getTxnDB(), getUNL(), beast::Journal::info, ripple::Pathfinder::initPathTable(), initSqliteDbs(), ripple::Config::LOAD, loadOldLedger(), ripple::lsDEBUG, m_featureTable, m_jobQueue, m_journal, m_ledgerMaster, m_localCredentials, m_mainIoPool, m_networkOPs, m_nodeStore, m_orderBookDB, m_peers, m_peerSSLContext, m_resolver, m_resourceManager, m_rpcDoor, m_rpcServerHandler, m_siteFiles, m_sleCache, m_sntpClient, m_wsPrivateDoor, m_wsProxyDoor, m_wsPublicDoor, m_wsSSLContext, ripple::make_Overlay(), mLedgerDB, mTxnDB, mValidations, ripple::Config::NETWORK, ripple::RPCDoor::New(), ripple::WSDoor::New(), ripple::UniqueNodeList::nodeBootstrap(), ripple::Config::REPLAY, ripple::Config::RUN_STANDALONE, ripple::LogPartition::setConsoleOutput(), ripple::LogPartition::setSeverity(), ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::setTargetAge(), ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::setTargetSize(), ripple::SHAMap::setTreeCache(), ripple::OrderBookDB::setup(), ripple::Application::signalStop(), ripple::siLedgerAge, ripple::siLedgerSize, ripple::siLgrDBCache, ripple::siNodeCacheAge, ripple::siNodeCacheSize, ripple::siSLECacheAge, ripple::siSLECacheSize, ripple::siTreeCacheAge, ripple::siTreeCacheSize, ripple::siTxnDBCache, ripple::siValidationsAge, ripple::siValidationsSize, ripple::LocalCredentials::start(), startNewLedger(), updateTables(), beast::Journal::warning, ripple::Config::WEBSOCKET_PORT, ripple::Config::WEBSOCKET_PROXY_PORT, and ripple::Config::WEBSOCKET_PUBLIC_PORT.
     {
         // VFALCO NOTE: 0 means use heuristics to determine the thread count.
         m_jobQueue->setThreadCount (0, getConfig ().RUN_STANDALONE);
     #if ! BEAST_WIN32
     #ifdef SIGINT
         if (!getConfig ().RUN_STANDALONE)
         {
             struct sigaction sa;
             memset (&sa, 0, sizeof (sa));
             sa.sa_handler = &ApplicationImp::sigIntHandler;
             sigaction (SIGINT, &sa, nullptr);
         }
     #endif
     #endif
         assert (mTxnDB == nullptr);
         if (!getConfig ().DEBUG_LOGFILE.empty ())
         {
             // Let debug messages go to the file but only WARNING or higher to regular output (unless verbose)
             LogSink::get()->setLogFile (getConfig ().DEBUG_LOGFILE);
             if (LogSink::get()->getMinSeverity () > lsDEBUG)
                 LogPartition::setSeverity (lsDEBUG);
         }
         if (!getConfig().CONSOLE_LOG_OUTPUT.empty())
         {
             LogPartition::setConsoleOutput (getConfig().CONSOLE_LOG_OUTPUT);
         }
         if (!getConfig ().RUN_STANDALONE)
             m_sntpClient->init (getConfig ().SNTP_SERVERS);
         initSqliteDbs ();
         getApp().getLedgerDB ()->getDB ()->executeSQL (boost::str (boost::format ("PRAGMA cache_size=-%d;") %
                 (getConfig ().getSize (siLgrDBCache) * 1024)));
         getApp().getTxnDB ()->getDB ()->executeSQL (boost::str (boost::format ("PRAGMA cache_size=-%d;") %
                 (getConfig ().getSize (siTxnDBCache) * 1024)));
         mTxnDB->getDB ()->setupCheckpointing (m_jobQueue.get());
         mLedgerDB->getDB ()->setupCheckpointing (m_jobQueue.get());
         if (!getConfig ().RUN_STANDALONE)
             updateTables ();
         m_featureTable->addInitial ();
         Pathfinder::initPathTable ();
         m_ledgerMaster->setMinValidations (getConfig ().VALIDATION_QUORUM);
         if (getConfig ().START_UP == Config::FRESH)
         {
             m_journal.info << "Starting new Ledger";
             startNewLedger ();
         }
         else if ((getConfig ().START_UP == Config::LOAD) || (getConfig ().START_UP == Config::REPLAY))
         {
             m_journal.info << "Loading specified Ledger";
             if (!loadOldLedger (getConfig ().START_LEDGER, getConfig ().START_UP == Config::REPLAY))
             {
                 // wtf?
                 getApp().signalStop ();
                 exit (-1);
             }
         }
         else if (getConfig ().START_UP == Config::NETWORK)
         {
             // This should probably become the default once we have a stable network
             if (!getConfig ().RUN_STANDALONE)
                 m_networkOPs->needNetworkLedger ();
             startNewLedger ();
         }
         else
             startNewLedger ();
         m_orderBookDB.setup (getApp().getLedgerMaster ().getCurrentLedger ());
         //
         // Begin validation and ip maintenance.
         // - LocalCredentials maintains local information: including identity and network connection persistence information.
         //
         // VFALCO NOTE this starts the UNL
         m_localCredentials.start ();
         //
         // Set up UNL.
         //
         if (!getConfig ().RUN_STANDALONE)
             getUNL ().nodeBootstrap ();
         mValidations->tune (getConfig ().getSize (siValidationsSize), getConfig ().getSize (siValidationsAge));
         m_nodeStore->tune (getConfig ().getSize (siNodeCacheSize), getConfig ().getSize (siNodeCacheAge));
         m_ledgerMaster->tune (getConfig ().getSize (siLedgerSize), getConfig ().getSize (siLedgerAge));
         m_sleCache.setTargetSize (getConfig ().getSize (siSLECacheSize));
         m_sleCache.setTargetAge (getConfig ().getSize (siSLECacheAge));
         SHAMap::setTreeCache (getConfig ().getSize (siTreeCacheSize), getConfig ().getSize (siTreeCacheAge));
         //----------------------------------------------------------------------
         //
         //
         // SSL context used for Peer connections.
         {
             m_peerSSLContext.reset (RippleSSLContext::createAnonymous (
                 getConfig ().PEER_SSL_CIPHER_LIST));
             // VFALCO NOTE, It seems the WebSocket context never has
             // set_verify_mode called, for either setting of WEBSOCKET_SECURE
             m_peerSSLContext->get().set_verify_mode (boost::asio::ssl::verify_none);
         }
         // VFALCO NOTE Unfortunately, in stand-alone mode some code still
         //             foolishly calls overlay(). When this is fixed we can
         //             move the instantiation inside a conditional:
         //
         //             if (!getConfig ().RUN_STANDALONE)
         m_peers = make_Overlay (m_mainIoPool, *m_resourceManager,
             *m_siteFiles, getConfig ().getModuleDatabasePath (),
             *m_resolver, m_mainIoPool, m_peerSSLContext->get ());
         // add to Stoppable
         add (*m_peers);
         // SSL context used for WebSocket connections.
         if (getConfig ().WEBSOCKET_SECURE)
         {
             m_wsSSLContext.reset (RippleSSLContext::createAuthenticated (
                 getConfig ().WEBSOCKET_SSL_KEY,
                 getConfig ().WEBSOCKET_SSL_CERT,
                 getConfig ().WEBSOCKET_SSL_CHAIN));
         }
         else
         {
             m_wsSSLContext.reset (RippleSSLContext::createWebSocket ());
         }
         // Create private listening WebSocket socket
         //
         if (!getConfig ().WEBSOCKET_IP.empty () && getConfig ().WEBSOCKET_PORT)
         {
             m_wsPrivateDoor.reset (WSDoor::New (*m_resourceManager,
                 getOPs(), getConfig ().WEBSOCKET_IP,
                     getConfig ().WEBSOCKET_PORT, false, false,
                         m_wsSSLContext->get ()));
             if (m_wsPrivateDoor == nullptr)
             {
                 beast::FatalError ("Could not open the WebSocket private interface.",
                     __FILE__, __LINE__);
             }
         }
         else
         {
             m_journal.info << "WebSocket private interface: disabled";
         }
         // Create public listening WebSocket socket
         //
         if (!getConfig ().WEBSOCKET_PUBLIC_IP.empty () && getConfig ().WEBSOCKET_PUBLIC_PORT)
         {
             m_wsPublicDoor.reset (WSDoor::New (*m_resourceManager,
                 getOPs(), getConfig ().WEBSOCKET_PUBLIC_IP,
                     getConfig ().WEBSOCKET_PUBLIC_PORT, true, false,
                         m_wsSSLContext->get ()));
             if (m_wsPublicDoor == nullptr)
             {
                 beast::FatalError ("Could not open the WebSocket public interface.",
                     __FILE__, __LINE__);
             }
         }
         else
         {
             m_journal.info << "WebSocket public interface: disabled";
         }
         if (!getConfig ().WEBSOCKET_PROXY_IP.empty () && getConfig ().WEBSOCKET_PROXY_PORT)
         {
             m_wsProxyDoor.reset (WSDoor::New (*m_resourceManager,
                 getOPs(), getConfig ().WEBSOCKET_PROXY_IP,
                     getConfig ().WEBSOCKET_PROXY_PORT, true, true,
                         m_wsSSLContext->get ()));
             if (m_wsProxyDoor == nullptr)
             {
                 beast::FatalError ("Could not open the WebSocket public interface.",
                     __FILE__, __LINE__);
             }
         }
         //
         //
         //----------------------------------------------------------------------
         //
         // Allow RPC connections.
         //
         if (! getConfig ().getRpcIP().empty () && getConfig ().getRpcPort() != 0)
         {
             try
             {
                 m_rpcDoor.reset (RPCDoor::New (m_mainIoPool, m_rpcServerHandler));
             }
             catch (const std::exception& e)
             {
                 // Must run as directed or exit.
                 m_journal.fatal <<
                     "Can not open RPC service: " << e.what ();
                 exit (3);
             }
         }
         else
         {
             m_journal.info << "RPC interface: disabled";
         }
         //
         // Begin connecting to network.
         //
         if (!getConfig ().RUN_STANDALONE)
         {
             // Should this message be here, conceptually? In theory this sort
             // of message, if displayed, should be displayed from PeerFinder.
             if (getConfig ().PEER_PRIVATE && getConfig ().IPS.empty ())
                 m_journal.warning << "No outbound peer connections will be made";
             // VFALCO NOTE the state timer resets the deadlock detector.
             //
             m_networkOPs->setStateTimer ();
         }
         else
         {
             m_journal.warning << "Running in standalone mode";
             m_networkOPs->setStandAlone ();
         }
     }
void ripple::ApplicationImp::signalStop () inline virtual
Implements ripple::Application.
Definition at line 976 of file Application.cpp.
References m_stop, and beast::WaitableEvent::signal().
     {
         // Unblock the main thread (which is sitting in run()).
         //
         m_stop.signal();
     }
void ripple::ApplicationImp::startNewLedger () private
Definition at line 1058 of file Application.cpp.
References ripple::RippleAddress::createAccountPublic(), ripple::RippleAddress::createGeneratorPublic(), ripple::RippleAddress::createSeedGeneric(), ripple::RippleAddress::humanAccountID(), ripple::RippleAddress::humanSeed(), beast::Journal::info, m_journal, m_ledgerMaster, m_networkOPs, and SYSTEM_CURRENCY_START.
Referenced by setup().
 {
     // New stuff.
     RippleAddress   rootSeedMaster      = RippleAddress::createSeedGeneric ("masterpassphrase");
     RippleAddress   rootGeneratorMaster = RippleAddress::createGeneratorPublic (rootSeedMaster);
     RippleAddress   rootAddress         = RippleAddress::createAccountPublic (rootGeneratorMaster, 0);
     // Print enough information to be able to claim root account.
     m_journal.info << "Root master seed: " << rootSeedMaster.humanSeed ();
     m_journal.info << "Root account: " << rootAddress.humanAccountID ();
     {
         Ledger::pointer firstLedger = boost::make_shared<Ledger> (rootAddress, SYSTEM_CURRENCY_START);
         assert (!!firstLedger->getAccountState (rootAddress));
         // WRITEME: Add any default features
         // WRITEME: Set default fee/reserve
         firstLedger->updateHash ();
         firstLedger->setClosed ();
         firstLedger->setAccepted ();
         m_ledgerMaster->pushLedger (firstLedger);
         Ledger::pointer secondLedger = boost::make_shared<Ledger> (true, boost::ref (*firstLedger));
         secondLedger->setClosed ();
         secondLedger->setAccepted ();
         m_ledgerMaster->pushLedger (secondLedger, boost::make_shared<Ledger> (true, boost::ref (*secondLedger)));
         assert (!!secondLedger->getAccountState (rootAddress));
         m_networkOPs->setLastCloseTime (secondLedger->getCloseTimeNC ());
     }
 }
void ripple::ApplicationImp::updateTables () private
Definition at line 1333 of file Application.cpp.
References ripple::addTxnSeqField(), ripple::getApp(), ripple::getConfig(), ripple::NodeStore::Database::getName(), ripple::Application::getNodeStore(), getTxnDB(), ripple::NodeStore::Database::import(), rocksdb::Log(), ripple::lsFATAL, ripple::lsWARNING, m_nodeStoreManager, ripple::schemaHas(), ripple::StopSustain(), and WriteLog.
Referenced by setup().
 {
     if (getConfig ().nodeDatabase.size () <= 0)
     {
         Log (lsFATAL) << "The [node_db] configuration setting has been updated and must be set";
         StopSustain ();
         exit (1);
     }
     // perform any needed table updates
     assert (schemaHas (getApp().getTxnDB (), "AccountTransactions", 0, "TransID"));
     assert (!schemaHas (getApp().getTxnDB (), "AccountTransactions", 0, "foobar"));
     addTxnSeqField ();
     if (schemaHas (getApp().getTxnDB (), "AccountTransactions", 0, "PRIMARY"))
     {
         Log (lsFATAL) << "AccountTransactions database should not have a primary key";
         StopSustain ();
         exit (1);
     }
     if (getConfig ().doImport)
     {
         NodeStore::DummyScheduler scheduler;
         std::unique_ptr <NodeStore::Database> source (
             m_nodeStoreManager->make_Database ("NodeStore.import", scheduler,
                 LogPartition::getJournal <NodeObject> (), 0,
                     getConfig ().importNodeDatabase));
         WriteLog (lsWARNING, NodeObject) <<
             "Node import from '" << source->getName () << "' to '"
                                  << getApp().getNodeStore().getName () << "'.";
         getApp().getNodeStore().import (*source);
     }
 }
Member Data Documentation
std::unique_ptr<CollectorManager> ripple::ApplicationImp::m_collectorManager
Definition at line 121 of file Application.cpp.
Referenced by getCollectorManager(), and onStart().
std::unique_ptr<UniqueNodeList> ripple::ApplicationImp::m_deprecatedUNL
Definition at line 137 of file Application.cpp.
Referenced by getUNL().
std::unique_ptr<FeatureTable> ripple::ApplicationImp::m_featureTable
Definition at line 144 of file Application.cpp.
Referenced by getFeatureTable(), and setup().
std::unique_ptr<FullBelowCache> ripple::ApplicationImp::m_fullBelowCache
Definition at line 123 of file Application.cpp.
Referenced by doSweep(), and getFullBelowCache().
std::unique_ptr<InboundLedgers> ripple::ApplicationImp::m_inboundLedgers
Definition at line 135 of file Application.cpp.
Referenced by getInboundLedgers().
std::unique_ptr<JobQueue> ripple::ApplicationImp::m_jobQueue
Definition at line 127 of file Application.cpp.
Referenced by ApplicationImp(), getJobQueue(), onDeadlineTimer(), and setup().
beast::Journal ripple::ApplicationImp::m_journal
Definition at line 110 of file Application.cpp.
Referenced by doStop(), doSweep(), loadOldLedger(), onDeadlineTimer(), onStart(), onStop(), run(), setup(), and startNewLedger().
std::unique_ptr<LedgerMaster> ripple::ApplicationImp::m_ledgerMaster
Definition at line 134 of file Application.cpp.
Referenced by ApplicationImp(), doSweep(), getLedgerMaster(), loadOldLedger(), setup(), and startNewLedger().
std::unique_ptr<LoadManager> ripple::ApplicationImp::m_loadManager
Definition at line 149 of file Application.cpp.
Referenced by getLoadManager().
LocalCredentials ripple::ApplicationImp::m_localCredentials
Definition at line 118 of file Application.cpp.
Referenced by getLocalCredentials(), and setup().
IoServicePool ripple::ApplicationImp::m_mainIoPool
Definition at line 128 of file Application.cpp.
Referenced by getIOService(), and setup().
Application::LockType ripple::ApplicationImp::m_masterMutex
Definition at line 111 of file Application.cpp.
Referenced by getMasterLock().
std::unique_ptr<NetworkOPs> ripple::ApplicationImp::m_networkOPs
Definition at line 136 of file Application.cpp.
Referenced by doSweep(), getOPs(), loadOldLedger(), setup(), and startNewLedger().
std::unique_ptr<NodeStore::Database> ripple::ApplicationImp::m_nodeStore
Definition at line 140 of file Application.cpp.
Referenced by doSweep(), getNodeStore(), and setup().
std::unique_ptr<NodeStore::Manager> ripple::ApplicationImp::m_nodeStoreManager
Definition at line 114 of file Application.cpp.
Referenced by updateTables().
NodeStoreScheduler ripple::ApplicationImp::m_nodeStoreScheduler
Definition at line 126 of file Application.cpp.
Referenced by ApplicationImp().
OrderBookDB ripple::ApplicationImp::m_orderBookDB
Definition at line 132 of file Application.cpp.
Referenced by getOrderBookDB(), and setup().
std::unique_ptr<PathRequests> ripple::ApplicationImp::m_pathRequests
Definition at line 133 of file Application.cpp.
Referenced by getPathRequests().
std::unique_ptr<Overlay> ripple::ApplicationImp::m_peers
Definition at line 160 of file Application.cpp.
Referenced by overlay(), and setup().
std::unique_ptr<beast::asio::SSLContext> ripple::ApplicationImp::m_peerSSLContext
Definition at line 158 of file Application.cpp.
Referenced by setup().
beast::io_latency_probe<std::chrono::steady_clock> ripple::ApplicationImp::m_probe
Definition at line 170 of file Application.cpp.
Referenced by onStart(), and onStop().
std::unique_ptr<ResolverAsio> ripple::ApplicationImp::m_resolver
Definition at line 168 of file Application.cpp.
Referenced by onStart(), onStop(), and setup().
std::unique_ptr<Resource::Manager> ripple::ApplicationImp::m_resourceManager
Definition at line 122 of file Application.cpp.
Referenced by ApplicationImp(), getResourceManager(), and setup().
std::unique_ptr<RPCDoor> ripple::ApplicationImp::m_rpcDoor
Definition at line 161 of file Application.cpp.
Referenced by setup().
std::unique_ptr<RPCHTTPServer> ripple::ApplicationImp::m_rpcHTTPServer
Definition at line 138 of file Application.cpp.
std::unique_ptr<RPC::Manager> ripple::ApplicationImp::m_rpcManager
Definition at line 130 of file Application.cpp.
Referenced by getRPCManager().
RPCServerHandler ripple::ApplicationImp::m_rpcServerHandler
Definition at line 139 of file Application.cpp.
Referenced by setup().
std::unique_ptr<SiteFiles::Manager> ripple::ApplicationImp::m_siteFiles
Definition at line 129 of file Application.cpp.
Referenced by getSiteFiles(), and setup().
SLECache ripple::ApplicationImp::m_sleCache
Definition at line 117 of file Application.cpp.
Referenced by doSweep(), getSLECache(), and setup().
std::unique_ptr<SNTPClient> ripple::ApplicationImp::m_sntpClient
Definition at line 141 of file Application.cpp.
Referenced by getSystemTimeOffset(), and setup().
beast::WaitableEvent ripple::ApplicationImp::m_stop
Definition at line 166 of file Application.cpp.
Referenced by run(), and signalStop().
beast::DeadlineTimer ripple::ApplicationImp::m_sweepTimer
Definition at line 150 of file Application.cpp.
Referenced by doSweep(), onDeadlineTimer(), onStart(), and onStop().
NodeCache ripple::ApplicationImp::m_tempNodeCache
Definition at line 116 of file Application.cpp.
Referenced by doSweep(), and getTempNodeCache().
TransactionMaster ripple::ApplicationImp::m_txMaster
Definition at line 119 of file Application.cpp.
Referenced by doSweep(), and getMasterTransaction().
std::unique_ptr<TxQueue> ripple::ApplicationImp::m_txQueue
Definition at line 142 of file Application.cpp.
Referenced by getTxQueue().
std::unique_ptr<Validators::Manager> ripple::ApplicationImp::m_validators
Definition at line 143 of file Application.cpp.
Referenced by getValidators(), and prepareValidators().
std::unique_ptr<WSDoor> ripple::ApplicationImp::m_wsPrivateDoor
Definition at line 163 of file Application.cpp.
Referenced by setup().
std::unique_ptr<WSDoor> ripple::ApplicationImp::m_wsProxyDoor
Definition at line 164 of file Application.cpp.
Referenced by setup().
std::unique_ptr<WSDoor> ripple::ApplicationImp::m_wsPublicDoor
Definition at line 162 of file Application.cpp.
Referenced by setup().
std::unique_ptr<beast::asio::SSLContext> ripple::ApplicationImp::m_wsSSLContext
Definition at line 159 of file Application.cpp.
Referenced by setup().
std::unique_ptr<LoadFeeTrack> ripple::ApplicationImp::mFeeTrack
Definition at line 145 of file Application.cpp.
Referenced by getFeeTrack().
std::unique_ptr<IHashRouter> ripple::ApplicationImp::mHashRouter
Definition at line 146 of file Application.cpp.
Referenced by getHashRouter().
std::unique_ptr<DatabaseCon> ripple::ApplicationImp::mLedgerDB
Definition at line 155 of file Application.cpp.
Referenced by getLedgerDB(), initSqliteDb(), and setup().
std::unique_ptr<ProofOfWorkFactory> ripple::ApplicationImp::mProofOfWorkFactory
Definition at line 148 of file Application.cpp.
Referenced by getProofOfWorkFactory().
std::unique_ptr<DatabaseCon> ripple::ApplicationImp::mRpcDB
Definition at line 153 of file Application.cpp.
Referenced by getRpcDB(), and initSqliteDb().
bool volatile ripple::ApplicationImp::mShutdown
Definition at line 151 of file Application.cpp.
Referenced by isShutdown(), onStop(), and run().
std::unique_ptr<DatabaseCon> ripple::ApplicationImp::mTxnDB
Definition at line 154 of file Application.cpp.
Referenced by getTxnDB(), initSqliteDb(), running(), and setup().
std::unique_ptr<Validations> ripple::ApplicationImp::mValidations
Definition at line 147 of file Application.cpp.
Referenced by doSweep(), getValidations(), onStop(), and setup().
std::unique_ptr<DatabaseCon> ripple::ApplicationImp::mWalletDB
Definition at line 156 of file Application.cpp.
Referenced by getWalletDB(), and initSqliteDb().
The documentation for this class was generated from the following file:
rippled/src/ripple_app/main/Application.cpp