rippled: rocksdb::Comparator Class Reference
rocksdb::Comparator Class Reference abstract
#include <comparator.h>
Public Member Functions
virtual ~Comparator ()
virtual int Compare (const Slice &a, const Slice &b) const =0
virtual const char * Name () const =0
virtual void FindShortestSeparator (std::string *start, const Slice &limit) const =0
virtual void FindShortSuccessor (std::string *key) const =0
Detailed Description
Definition at line 22 of file comparator.h.
Constructor & Destructor Documentation
rocksdb::Comparator::~Comparator () virtual
Definition at line 19 of file comparator.cc.
 { }
Member Function Documentation
virtual int rocksdb::Comparator::Compare (const Slice & a, const Slice & b) const pure virtual
Implemented in rocksdb::InternalKeyComparator, leveldb_comparator_t, and rocksdb::TestKeyComparator.
Referenced by rocksdb::BlockBuilder::Add(), rocksdb::BlockBasedTableBuilder::Add(), rocksdb::FilterBlockBuilder::AddKey(), rocksdb::AfterFile(), rocksdb::DBTest::AllEntriesFor(), rocksdb::BeforeFile(), rocksdb::BuildTable(), rocksdb::Block::Iter::Compare(), rocksdb::InternalKeyComparator::Compare(), rocksdb::InternalDumpCommand::DoCommand(), rocksdb::Version::ExtendOverlappingInputs(), rocksdb::InternalKeyComparator::FindShortestSeparator(), rocksdb::InternalKeyComparator::FindShortSuccessor(), rocksdb::Version::Get(), rocksdb::MemTable::Get(), rocksdb::SimpleTableReader::GetOffset(), rocksdb::Version::GetOverlappingInputs(), rocksdb::Version::GetOverlappingInputsBinarySearch(), rocksdb::Version::HasOverlappingUserKey(), rocksdb::Compaction::IsBaseLevelForKey(), rocksdb::MergeHelper::MergeUntil(), rocksdb::MaxIteratorComparator::operator()(), rocksdb::MinIteratorComparator::operator()(), rocksdb::anon::STLLessThan::operator()(), rocksdb::BlockBasedTable::ReadProperties(), rocksdb::TEST(), and rocksdb::MemTable::Update().
virtual void rocksdb::Comparator::FindShortestSeparator (std::string * start, const Slice & limit) const pure virtual
Implemented in rocksdb::InternalKeyComparator, rocksdb::TestKeyComparator, and leveldb_comparator_t.
Referenced by rocksdb::BlockBasedTableBuilder::Add(), rocksdb::InternalKeyComparator::FindShortestSeparator(), and rocksdb::TEST().
virtual void rocksdb::Comparator::FindShortSuccessor (std::string * key) const pure virtual
Implemented in rocksdb::InternalKeyComparator, rocksdb::TestKeyComparator, and leveldb_comparator_t.
Referenced by rocksdb::InternalKeyComparator::FindShortSuccessor(), rocksdb::BlockBasedTableBuilder::Finish(), and rocksdb::TEST().
virtual const char* rocksdb::Comparator::Name () const pure virtual
Implemented in rocksdb::InternalKeyComparator, rocksdb::TestKeyComparator, and leveldb_comparator_t.
Referenced by rocksdb::Options::Dump(), rocksdb::VersionSet::DumpManifest(), rocksdb::VersionSet::Recover(), and rocksdb::VersionSet::WriteSnapshot().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/include/rocksdb/comparator.h
rippled/src/ripple/rocksdb/rocksdb/util/comparator.cc