rippled: rocksdb::PrefixTest Class Reference
rocksdb::PrefixTest Class Reference
Public Member Functions
std::shared_ptr< DB > OpenDb ()
~PrefixTest ()
Protected Attributes
Options options
Detailed Description
Definition at line 97 of file prefix_test.cc.
Constructor & Destructor Documentation
rocksdb::PrefixTest::~PrefixTest () inline
Definition at line 126 of file prefix_test.cc.
References rocksdb::Options::comparator, and options.
                 {
     delete options.comparator;
   }
Member Function Documentation
std::shared_ptr<DB> rocksdb::PrefixTest::OpenDb () inline
Definition at line 99 of file prefix_test.cc.
References ASSERT_OK, rocksdb::Options::comparator, rocksdb::Options::create_if_missing, db, FLAGS_max_write_buffer_number, FLAGS_min_write_buffer_number_to_merge, FLAGS_write_buffer_size, rocksdb::kDbName, rocksdb::Options::max_write_buffer_number, rocksdb::Options::memtable_factory, rocksdb::Options::min_write_buffer_number_to_merge, rocksdb::NewFixedPrefixTransform(), rocksdb::NewHashSkipListRepFactory(), rocksdb::DB::Open(), options, rocksdb::Options::prefix_extractor, and rocksdb::Options::write_buffer_size.
{
     DB* db;
     options.create_if_missing = true;
     options.write_buffer_size = FLAGS_write_buffer_size;
     options.max_write_buffer_number = FLAGS_max_write_buffer_number;
     options.min_write_buffer_number_to_merge =
       FLAGS_min_write_buffer_number_to_merge;
     options.comparator = new TestKeyComparator();
     if (FLAGS_use_prefix_hash_memtable) {
       auto prefix_extractor = NewFixedPrefixTransform(8);
       options.prefix_extractor = prefix_extractor;
       if (FLAGS_use_nolock_version) {
         options.memtable_factory.reset(NewHashSkipListRepFactory(
             prefix_extractor, FLAGS_bucket_count));
       } else {
         options.memtable_factory =
           std::make_shared<rocksdb::PrefixHashRepFactory>(
             prefix_extractor, FLAGS_bucket_count, FLAGS_num_locks);
       }
     }
     Status s = DB::Open(options, kDbName,  &db);
     ASSERT_OK(s);
     return std::shared_ptr<DB>(db);
   }
Member Data Documentation
Options rocksdb::PrefixTest::options protected
Definition at line 130 of file prefix_test.cc.
Referenced by OpenDb(), and ~PrefixTest().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/db/prefix_test.cc