rippled: rocksdb::WritableFile Class Reference
rocksdb::WritableFile Class Reference abstract
#include <env.h>
Public Member Functions
WritableFile ()
virtual ~WritableFile ()
virtual Status Append (const Slice &data)=0
virtual Status Close ()=0
virtual Status Flush ()=0
virtual Status Sync ()=0
virtual Status Fsync ()
virtual uint64_t GetFileSize ()
void SetPreallocationBlockSize (size_t size)
virtual void GetPreallocationStatus (size_t *block_size, size_t *last_allocated_block)
virtual size_t GetUniqueId (char *id, size_t max_size) const
virtual Status InvalidateCache (size_t offset, size_t length)
Protected Member Functions
void PrepareWrite (size_t offset, size_t len)
virtual Status Allocate (off_t offset, off_t len)
virtual Status RangeSync (off_t offset, off_t nbytes)
Private Member Functions
WritableFile (const WritableFile &)
void operator= (const WritableFile &)
Private Attributes
size_t last_preallocated_block_
size_t preallocation_block_size_
Detailed Description
Definition at line 335 of file env.h.
Constructor & Destructor Documentation
rocksdb::WritableFile::WritableFile () inline
Definition at line 337 of file env.h.
                  : last_preallocated_block_(0), preallocation_block_size_ (0) {
   }
rocksdb::WritableFile::~WritableFile () virtual
Definition at line 24 of file env.cc.
{
 }
rocksdb::WritableFile::WritableFile (const WritableFile &) private
Member Function Documentation
virtual Status rocksdb::WritableFile::Allocate (off_t offset, off_t len) inline protected virtual
Definition at line 420 of file env.h.
References rocksdb::Status::OK().
Referenced by PrepareWrite().
{
     return Status::OK();
   }
virtual Status rocksdb::WritableFile::Append (const Slice & data) pure virtual
Implemented in rocksdb::StringSink, rocksdb::log::LogTest::StringDest, and rocksdb::FakeWritableFile.
Referenced by rocksdb::SimpleTableBuilder::Add(), rocksdb::DoWriteStringToFile(), rocksdb::BlockBasedTableBuilder::Finish(), rocksdb::SimpleTableBuilder::Finish(), rocksdb::TEST(), and rocksdb::BlockBasedTableBuilder::WriteRawBlock().
virtual Status rocksdb::WritableFile::Close () pure virtual
Implemented in rocksdb::StringSink, rocksdb::log::LogTest::StringDest, and rocksdb::FakeWritableFile.
Referenced by rocksdb::BuildTable(), and rocksdb::TableReaderBenchmark().
virtual Status rocksdb::WritableFile::Flush () pure virtual
Implemented in rocksdb::StringSink, rocksdb::log::LogTest::StringDest, and rocksdb::FakeWritableFile.
Referenced by rocksdb::BlockBasedTableBuilder::Flush().
virtual Status rocksdb::WritableFile::Fsync () inline virtual
Definition at line 352 of file env.h.
References Sync().
Referenced by rocksdb::BuildTable().
{
     return Sync();
   }
virtual uint64_t rocksdb::WritableFile::GetFileSize () inline virtual
Definition at line 359 of file env.h.
{
     return 0;
   }
virtual void rocksdb::WritableFile::GetPreallocationStatus (size_t * block_size, size_t * last_allocated_block) inline virtual
Definition at line 373 of file env.h.
References last_preallocated_block_, and preallocation_block_size_.
Referenced by rocksdb::TEST().
{
     *last_allocated_block = last_preallocated_block_;
     *block_size = preallocation_block_size_;
   }
virtual size_t rocksdb::WritableFile::GetUniqueId (char * id, size_t max_size) const inline virtual
Definition at line 380 of file env.h.
Referenced by rocksdb::BlockBasedTable::GenerateCachePrefix().
{
     return 0; // Default implementation to prevent issues with backwards
   }
virtual Status rocksdb::WritableFile::InvalidateCache (size_t offset, size_t length) inline virtual
Definition at line 388 of file env.h.
References rocksdb::Status::NotSupported().
Referenced by rocksdb::BlockBasedTableBuilder::InsertBlockInCache().
{
     return Status::NotSupported("InvalidateCache not supported.");
   }
void rocksdb::WritableFile::operator= (const WritableFile &) private
void rocksdb::WritableFile::PrepareWrite (size_t offset, size_t len) inline protected
Definition at line 398 of file env.h.
References Allocate(), last_preallocated_block_, and preallocation_block_size_.
{
     if (preallocation_block_size_ == 0) {
       return;
     }
     // If this write would cross one or more preallocation blocks,
     // determine what the last preallocation block necesessary to
     // cover this write would be and Allocate to that point.
     const auto block_size = preallocation_block_size_;
     size_t new_last_preallocated_block =
       (offset + len + block_size - 1) / block_size;
     if (new_last_preallocated_block > last_preallocated_block_) {
       size_t num_spanned_blocks =
         new_last_preallocated_block - last_preallocated_block_;
       Allocate(block_size * last_preallocated_block_,
                block_size * num_spanned_blocks);
       last_preallocated_block_ = new_last_preallocated_block;
     }
   }
virtual Status rocksdb::WritableFile::RangeSync (off_t offset, off_t nbytes) inline protected virtual
Definition at line 430 of file env.h.
References rocksdb::Status::OK().
{
     return Status::OK();
   }
void rocksdb::WritableFile::SetPreallocationBlockSize (size_t size) inline
Definition at line 369 of file env.h.
References preallocation_block_size_.
Referenced by rocksdb::TEST().
{
     preallocation_block_size_ = size;
   }
virtual Status rocksdb::WritableFile::Sync () pure virtual
Implemented in rocksdb::StringSink, rocksdb::log::LogTest::StringDest, and rocksdb::FakeWritableFile.
Referenced by rocksdb::BuildTable(), rocksdb::DoWriteStringToFile(), and Fsync().
Member Data Documentation
size_t rocksdb::WritableFile::last_preallocated_block_ private
Definition at line 435 of file env.h.
Referenced by GetPreallocationStatus(), and PrepareWrite().
size_t rocksdb::WritableFile::preallocation_block_size_ private
Definition at line 436 of file env.h.
Referenced by GetPreallocationStatus(), PrepareWrite(), and SetPreallocationBlockSize().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/include/rocksdb/env.h
rippled/src/ripple/rocksdb/rocksdb/util/env.cc