rippled: rocksdb::AssociativeMergeOperator Class Reference
rocksdb::AssociativeMergeOperator Class Reference abstract
#include <merge_operator.h>
Public Member Functions
virtual ~AssociativeMergeOperator ()
virtual bool Merge (const Slice &key, const Slice *existing_value, const Slice &value, std::string *new_value, Logger *logger) const =0
Public Member Functions inherited from rocksdb::MergeOperator
virtual ~MergeOperator ()
virtual const char * Name () const =0
Private Member Functions
virtual bool FullMerge (const Slice &key, const Slice *existing_value, const std::deque< std::string > &operand_list, std::string *new_value, Logger *logger) const override
virtual bool PartialMerge (const Slice &key, const Slice &left_operand, const Slice &right_operand, std::string *new_value, Logger *logger) const override
Detailed Description
Definition at line 108 of file merge_operator.h.
Constructor & Destructor Documentation
virtual rocksdb::AssociativeMergeOperator::~AssociativeMergeOperator () inline virtual
Definition at line 110 of file merge_operator.h.
 {}
Member Function Documentation
bool rocksdb::AssociativeMergeOperator::FullMerge (const Slice & key, const Slice * existing_value, const std::deque< std::string > & operand_list, std::string * new_value, Logger * logger) const override private virtual
Implements rocksdb::MergeOperator.
Definition at line 17 of file merge_operator.cc.
References Merge(), beast::asio::swap(), and value.
{
   // Simply loop through the operands
   Slice temp_existing;
   std::string temp_value;
   for (const auto& operand : operand_list) {
     Slice value(operand);
     if (!Merge(key, existing_value, value, &temp_value, logger)) {
       return false;
     }
     swap(temp_value, *new_value);
     temp_existing = Slice(*new_value);
     existing_value = &temp_existing;
   }
   // The result will be in *new_value. All merges succeeded.
   return true;
 }
virtual bool rocksdb::AssociativeMergeOperator::Merge (const Slice & key, const Slice * existing_value, const Slice & value, std::string * new_value, Logger * logger) const pure virtual
Implemented in rocksdb::StringAppendOperator.
Referenced by FullMerge(), and PartialMerge().
bool rocksdb::AssociativeMergeOperator::PartialMerge (const Slice & key, const Slice & left_operand, const Slice & right_operand, std::string * new_value, Logger * logger) const override private virtual
Implements rocksdb::MergeOperator.
Definition at line 43 of file merge_operator.cc.
References Merge().
{
   return Merge(key, &left_operand, right_operand, new_value, logger);
 }
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/include/rocksdb/merge_operator.h
rippled/src/ripple/rocksdb/rocksdb/db/merge_operator.cc