rippled: beast::PropertyStream::Map Class Reference
beast::PropertyStream::Map Class Reference
#include <PropertyStream.h>
Public Member Functions
Map (PropertyStream &stream)
Map (Set &parent)
Map (std::string const &key, Map &parent)
Map (std::string const &key, PropertyStream &stream)
~Map ()
PropertyStream & stream ()
PropertyStream const & stream () const
template<typename Value >
void add (std::string const &key, Value value) const
template<typename Key , typename Value >
void add (Key key, Value value) const
Proxy operator[] (std::string const &key)
Proxy operator[] (char const *key)
template<typename Key >
Proxy operator[] (Key key) const
Private Attributes
PropertyStream & m_stream
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
Definition at line 186 of file PropertyStream.h.
Constructor & Destructor Documentation
beast::PropertyStream::Map::Map (PropertyStream & stream) explicit
Definition at line 92 of file PropertyStream.cpp.
     : m_stream (stream)
 {
 }
beast::PropertyStream::Map::Map (Set & parent) explicit
Definition at line 97 of file PropertyStream.cpp.
References m_stream, and beast::PropertyStream::map_begin().
     : m_stream (parent.stream())
 {
     m_stream.map_begin ();
 }
beast::PropertyStream::Map::Map (std::string const & key, Map & parent)
Definition at line 103 of file PropertyStream.cpp.
References m_stream, and beast::PropertyStream::map_begin().
     : m_stream (map.stream())
 {
     m_stream.map_begin (key);
 }
beast::PropertyStream::Map::Map (std::string const & key, PropertyStream & stream)
Definition at line 109 of file PropertyStream.cpp.
References m_stream, and beast::PropertyStream::map_begin().
     : m_stream (stream)
 {
     m_stream.map_begin (key);
 }
beast::PropertyStream::Map::~Map ()
Definition at line 115 of file PropertyStream.cpp.
 {
     m_stream.map_end ();
 }
Member Function Documentation
template<typename Value > void beast::PropertyStream::Map::add (std::string const & key, Value value) const inline
Definition at line 202 of file PropertyStream.h.
References beast::PropertyStream::add(), and m_stream.
Referenced by add(), and beast::PropertyStream::Proxy::operator=().
     {
         m_stream.add (key, value);
     }
template<typename Key , typename Value > void beast::PropertyStream::Map::add (Key key, Value value) const inline
Definition at line 208 of file PropertyStream.h.
References add(), and value.
     {
         std::stringstream ss;
         ss << key;
         add (ss.str(), value);
     }
PropertyStream::Proxy beast::PropertyStream::Map::operator[] (std::string const & key)
Definition at line 130 of file PropertyStream.cpp.
 {
     return Proxy (*this, key);
 }
Proxy beast::PropertyStream::Map::operator[] (char const * key) inline
Definition at line 217 of file PropertyStream.h.
         { return Proxy (*this, key); }
template<typename Key > Proxy beast::PropertyStream::Map::operator[] (Key key) const inline
Definition at line 221 of file PropertyStream.h.
     {
         std::stringstream ss;
         ss << key;
         return Proxy (*this, ss.str());
     }
PropertyStream & beast::PropertyStream::Map::stream ()
Definition at line 120 of file PropertyStream.cpp.
 {
     return m_stream;
 }
PropertyStream const & beast::PropertyStream::Map::stream () const
Definition at line 125 of file PropertyStream.cpp.
 {
     return m_stream;
 }
Member Data Documentation
PropertyStream& beast::PropertyStream::Map::m_stream private
Definition at line 189 of file PropertyStream.h.
Referenced by add(), and Map().
The documentation for this class was generated from the following files:
rippled/src/beast/beast/utility/PropertyStream.h
rippled/src/beast/beast/utility/impl/PropertyStream.cpp