rippled: ripple::Ledger Class Reference
ripple::Ledger Class Reference
#include <Ledger.h>
Public Types
enum TransResult {
TR_ERROR = -1, TR_SUCCESS = 0, TR_NOTFOUND = 1, TR_ALREADY = 2,
TR_BADTRANS = 3, TR_BADACCT = 4, TR_INSUFF = 5, TR_PASTASEQ = 6,
TR_PREASEQ = 7, TR_BADLSEQ = 8, TR_TOOSMALL = 9
}
typedef boost::shared_ptr< Ledger > pointer
typedef const
boost::shared_ptr< Ledger > & ref
Public Member Functions
Ledger (const RippleAddress &masterID, std::uint64_t startAmount)
Ledger (uint256 const &parentHash, uint256 const &transHash, uint256 const &accountHash, std::uint64_t totCoins, std::uint32_t closeTime, std::uint32_t parentCloseTime, int closeFlags, int closeResolution, std::uint32_t ledgerSeq, bool &loaded)
Ledger (Blob const &rawLedger, bool hasPrefix)
Ledger (const std::string &rawLedger, bool hasPrefix)
Ledger (bool dummy, Ledger &previous)
Ledger (Ledger &target, bool isMutable)
~Ledger ()
void updateHash ()
void setClosed ()
void setValidated ()
void setAccepted (std::uint32_t closeTime, int closeResolution, bool correctCloseTime)
void setAccepted ()
void setImmutable ()
bool isClosed ()
bool isAccepted ()
bool isValidated ()
bool isImmutable ()
bool isFixed ()
void setFull ()
void addRaw (Serializer &s) const
void setRaw (Serializer &s, bool hasPrefix)
uint256 getHash ()
uint256 const & getParentHash () const
uint256 const & getTransHash () const
uint256 const & getAccountHash () const
std::uint64_t getTotalCoins () const
void destroyCoins (std::uint64_t fee)
std::uint32_t getCloseTimeNC () const
std::uint32_t getParentCloseTimeNC () const
std::uint32_t getLedgerSeq () const
int getCloseResolution () const
bool getCloseAgree () const
void setCloseTime (std::uint32_t ct)
void setCloseTime (boost::posix_time::ptime)
boost::posix_time::ptime getCloseTime () const
SHAMap::ref peekTransactionMap ()
SHAMap::ref peekAccountStateMap ()
void dropCache ()
void setAcquiring (void)
bool isAcquiring (void)
bool isAcquiringTx (void)
bool isAcquiringAS (void)
bool addTransaction (uint256 const &id, const Serializer &txn)
bool addTransaction (uint256 const &id, const Serializer &txn, const Serializer &metaData)
bool hasTransaction (uint256 const &TransID) const
Transaction::pointer getTransaction (uint256 const &transID) const
bool getTransaction (uint256 const &transID, Transaction::pointer &txn, TransactionMetaSet::pointer &txMeta)
bool getTransactionMeta (uint256 const &transID, TransactionMetaSet::pointer &txMeta)
bool getMetaHex (uint256 const &transID, std::string &hex)
SerializedTransaction::pointer getSMTransaction (SHAMapItem::ref, SHAMapTreeNode::TNType, TransactionMetaSet::pointer &txMeta)
bool hasAccount (const RippleAddress &acctID)
AccountState::pointer getAccountState (const RippleAddress &acctID)
LedgerStateParms writeBack (LedgerStateParms parms, SLE::ref)
SLE::pointer getAccountRoot (const uint160 &accountID)
SLE::pointer getAccountRoot (const RippleAddress &naAccountID)
void updateSkipList ()
void visitAccountItems (const uint160 &acctID, std::function< void(SLE::ref)>)
void visitStateItems (std::function< void(SLE::ref)>)
bool pendSaveValidated (bool isSynchronous, bool isCurrent)
SLE::pointer getSLE (uint256 const &uHash)
SLE::pointer getSLEi (uint256 const &uHash)
uint256 getFirstLedgerIndex ()
uint256 getLastLedgerIndex ()
uint256 getNextLedgerIndex (uint256 const &uHash)
uint256 getNextLedgerIndex (uint256 const &uHash, uint256 const &uEnd)
uint256 getPrevLedgerIndex (uint256 const &uHash)
uint256 getPrevLedgerIndex (uint256 const &uHash, uint256 const &uBegin)
uint256 getLedgerHash (std::uint32_t ledgerIndex)
std::vector< std::pair
< std::uint32_t, uint256 > > getLedgerHashes ()
std::vector< uint256 > getLedgerFeatures ()
std::vector< uint256 > getNeededTransactionHashes (int max, SHAMapSyncFilter *filter)
std::vector< uint256 > getNeededAccountStateHashes (int max, SHAMapSyncFilter *filter)
SLE::pointer getGenerator (const uint160 &uGeneratorID)
NicknameState::pointer getNicknameState (uint256 const &uNickname)
NicknameState::pointer getNicknameState (const std::string &strNickname)
SLE::pointer getNickname (uint256 const &uNickname)
SLE::pointer getNickname (const std::string &strNickname)
SLE::pointer getOffer (uint256 const &uIndex)
SLE::pointer getOffer (const uint160 &uAccountID, std::uint32_t uSequence)
SLE::pointer getDirNode (uint256 const &uNodeIndex)
SLE::pointer getRippleState (uint256 const &uNode)
SLE::pointer getRippleState (const RippleAddress &naA, const RippleAddress &naB, const uint160 &uCurrency)
SLE::pointer getRippleState (const uint160 &uiA, const uint160 &uiB, const uint160 &uCurrency)
std::uint32_t getReferenceFeeUnits ()
std::uint64_t getBaseFee ()
std::uint64_t getReserve (int increments)
std::uint64_t getReserveInc ()
std::uint64_t scaleFeeBase (std::uint64_t fee)
std::uint64_t scaleFeeLoad (std::uint64_t fee, bool bAdmin)
Json::Value getJson (int options)
void addJson (Json::Value &, int options)
bool walkLedger ()
bool assertSane ()
Public Member Functions inherited from ripple::CountedObject< Ledger >
CountedObject ()
CountedObject (CountedObject const &)
~CountedObject ()
Static Public Member Functions
static char const * getCountedObjectName ()
static Ledger::pointer getSQL (const std::string &sqlStatement)
static Ledger::pointer getSQL1 (SqliteStatement *)
static void getSQL2 (Ledger::ref)
static Ledger::pointer getLastFullLedger ()
static std::uint32_t roundCloseTime (std::uint32_t closeTime, std::uint32_t closeResolution)
static
SerializedTransaction::pointer getSTransaction (SHAMapItem::ref, SHAMapTreeNode::TNType)
static Ledger::pointer loadByIndex (std::uint32_t ledgerIndex)
static Ledger::pointer loadByHash (uint256 const &ledgerHash)
static uint256 getHashByIndex (std::uint32_t index)
static bool getHashesByIndex (std::uint32_t index, uint256 &ledgerHash, uint256 &parentHash)
static std::map< std::uint32_t,
std::pair< uint256, uint256 > > getHashesByIndex (std::uint32_t minSeq, std::uint32_t maxSeq)
static uint256 getLedgerHashIndex ()
static uint256 getLedgerHashIndex (std::uint32_t desiredLedgerIndex)
static int getLedgerHashOffset (std::uint32_t desiredLedgerIndex)
static int getLedgerHashOffset (std::uint32_t desiredLedgerIndex, std::uint32_t currentLedgerIndex)
static uint256 getLedgerFeatureIndex ()
static uint256 getLedgerFeeIndex ()
static uint256 getAccountRootIndex (const uint160 &uAccountID)
static uint256 getAccountRootIndex (const RippleAddress &account)
static uint256 getGeneratorIndex (const uint160 &uGeneratorID)
static uint256 getNicknameHash (const std::string &strNickname)
static uint256 getNicknameIndex (uint256 const &uNickname)
static bool isValidBook (const uint160 &uTakerPaysCurrency, const uint160 &uTakerPaysIssuerID, const uint160 &uTakerGetsCurrency, const uint160 &uTakerGetsIssuerID)
static uint256 getBookBase (const uint160 &uTakerPaysCurrency, const uint160 &uTakerPaysIssuerID, const uint160 &uTakerGetsCurrency, const uint160 &uTakerGetsIssuerID)
static uint256 getOfferIndex (const uint160 &uAccountID, std::uint32_t uSequence)
static uint256 getOwnerDirIndex (const uint160 &uAccountID)
static uint256 getDirNodeIndex (uint256 const &uDirRoot, const std::uint64_t uNodeIndex=0)
static void ownerDirDescriber (SLE::ref, bool, const uint160 &owner)
static uint256 getQualityIndex (uint256 const &uBase, const std::uint64_t uNodeDir=0)
static uint256 getQualityNext (uint256 const &uBase)
static std::uint64_t getQuality (uint256 const &uBase)
static void qualityDirDescriber (SLE::ref, bool, const uint160 &uTakerPaysCurrency, const uint160 &uTakerPaysIssuer, const uint160 &uTakerGetsCurrency, const uint160 &uTakerGetsIssuer, const std::uint64_t &uRate)
static uint256 getRippleStateIndex (const RippleAddress &naA, const RippleAddress &naB, const uint160 &uCurrency)
static uint256 getRippleStateIndex (const uint160 &uiA, const uint160 &uiB, const uint160 &uCurrency)
static std::set< std::uint32_t > getPendingSaves ()
Static Public Attributes
static const std::uint32_t sLCF_NoConsensusTime = 1
Protected Member Functions
SLE::pointer getASNode (LedgerStateParms &parms, uint256 const &nodeID, LedgerEntryType let)
SLE::pointer getASNodeI (uint256 const &nodeID, LedgerEntryType let)
void saveValidatedLedgerAsync (Job &, bool current)
bool saveValidatedLedger (bool current)
void updateFees ()
Protected Member Functions inherited from ripple::LedgerBase
LedgerBase ()
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Private Types
typedef RippleMutex StaticLockType
typedef std::lock_guard
< StaticLockType > StaticScopedLockType
Private Member Functions
void initializeFees ()
Private Attributes
uint256 mHash
uint256 mParentHash
uint256 mTransHash
uint256 mAccountHash
std::uint64_t mTotCoins
std::uint32_t mLedgerSeq
std::uint32_t mCloseTime
std::uint32_t mParentCloseTime
int mCloseResolution
std::uint32_t mCloseFlags
bool mClosed
bool mValidated
bool mValidHash
bool mAccepted
bool mImmutable
std::uint32_t mReferenceFeeUnits
std::uint32_t mReserveBase
std::uint32_t mReserveIncrement
std::uint64_t mBaseFee
SHAMap::pointer mTransactionMap
SHAMap::pointer mAccountStateMap
Static Private Attributes
static StaticLockType sPendingSaveLock
static std::set< std::uint32_t > sPendingSaves
Additional Inherited Members
Protected Types inherited from ripple::LedgerBase
typedef RippleRecursiveMutex LockType
typedef std::lock_guard< LockType > ScopedLockType
Protected Attributes inherited from ripple::LedgerBase
LockType mLock
Detailed Description
Holds some or all of a ledger. This can hold just the header, a partial set of data, or the entire set of data. It all depends on what is in the corresponding SHAMap entry. Various functions are provided to populate or depopulate the caches that the object holds references to.
Definition at line 74 of file Ledger.h.
Member Typedef Documentation
typedef boost::shared_ptr<Ledger> ripple::Ledger::pointer
Definition at line 83 of file Ledger.h.
typedef const boost::shared_ptr<Ledger>& ripple::Ledger::ref
Definition at line 84 of file Ledger.h.
typedef RippleMutex ripple::Ledger::StaticLockType private
Definition at line 511 of file Ledger.h.
typedef std::lock_guard<StaticLockType> ripple::Ledger::StaticScopedLockType private
Definition at line 512 of file Ledger.h.
Member Enumeration Documentation
enum ripple::Ledger::TransResult
Enumerator
TR_ERROR
TR_SUCCESS
TR_NOTFOUND
TR_ALREADY
TR_BADTRANS
TR_BADACCT
TR_INSUFF
TR_PASTASEQ
TR_PREASEQ
TR_BADLSEQ
TR_TOOSMALL
Definition at line 86 of file Ledger.h.
     {
         TR_ERROR    = -1,
         TR_SUCCESS  = 0,
         TR_NOTFOUND = 1,
         TR_ALREADY  = 2,
         TR_BADTRANS = 3,    // the transaction itself is corrupt
         TR_BADACCT  = 4,    // one of the accounts is invalid
         TR_INSUFF   = 5,    // the sending(apply)/receiving(remove) account is broke
         TR_PASTASEQ = 6,    // account is past this transaction
         TR_PREASEQ  = 7,    // account is missing transactions before this
         TR_BADLSEQ  = 8,    // ledger too early
         TR_TOOSMALL = 9,    // amount is less than Tx fee
     };
Constructor & Destructor Documentation
ripple::Ledger::Ledger (const RippleAddress & masterID, std::uint64_t startAmount)
Definition at line 30 of file Ledger.cpp.
References ripple::SHAMap::flushDirty(), ripple::hotACCOUNT_NODE, initializeFees(), ripple::lepCREATE, ripple::lsTRACE, mAccountStateMap, mLedgerSeq, writeBack(), and WriteLog.
     : mTotCoins (startAmount)
     , mLedgerSeq (1) // First Ledger
     , mCloseTime (0)
     , mParentCloseTime (0)
     , mCloseResolution (LEDGER_TIME_ACCURACY)
     , mCloseFlags (0)
     , mClosed (false)
     , mValidated (false)
     , mValidHash (false)
     , mAccepted (false)
     , mImmutable (false)
     , mTransactionMap  (boost::make_shared <SHAMap> (smtTRANSACTION,
         std::ref (getApp().getFullBelowCache())))
     , mAccountStateMap (boost::make_shared <SHAMap> (smtSTATE,
         std::ref (getApp().getFullBelowCache())))
 {
     // special case: put coins in root account
     AccountState::pointer startAccount = boost::make_shared<AccountState> (masterID);
     startAccount->peekSLE ().setFieldAmount (sfBalance, startAmount);
     startAccount->peekSLE ().setFieldU32 (sfSequence, 1);
     WriteLog (lsTRACE, Ledger) << "root account: " << startAccount->peekSLE ().getJson (0);
     mAccountStateMap->armDirty ();
     writeBack (lepCREATE, startAccount->getSLE ());
     SHAMap::flushDirty (*mAccountStateMap->disarmDirty (), 256, hotACCOUNT_NODE, mLedgerSeq);
     initializeFees ();
 }
ripple::Ledger::Ledger (uint256 const & parentHash, uint256 const & transHash, uint256 const & accountHash, std::uint64_t totCoins, std::uint32_t closeTime, std::uint32_t parentCloseTime, int closeFlags, int closeResolution, std::uint32_t ledgerSeq, bool & loaded)
Definition at line 65 of file Ledger.cpp.
References initializeFees(), ripple::base_uint< BITS >::isNonZero(), ripple::lsWARNING, mAccountHash, mAccountStateMap, mTransactionMap, mTransHash, updateHash(), and WriteLog.
     : mParentHash (parentHash)
     , mTransHash (transHash)
     , mAccountHash (accountHash)
     , mTotCoins (totCoins)
     , mLedgerSeq (ledgerSeq)
     , mCloseTime (closeTime)
     , mParentCloseTime (parentCloseTime)
     , mCloseResolution (closeResolution)
     , mCloseFlags (closeFlags)
     , mClosed (false)
     , mValidated (false)
     , mValidHash (false)
     , mAccepted (false)
     , mImmutable (true)
     , mTransactionMap (boost::make_shared <SHAMap> (
         smtTRANSACTION, transHash, std::ref (getApp().getFullBelowCache())))
     , mAccountStateMap (boost::make_shared <SHAMap> (smtSTATE, accountHash,
         std::ref (getApp().getFullBelowCache())))
 {
     updateHash ();
     loaded = true;
     if (mTransHash.isNonZero () && !mTransactionMap->fetchRoot (mTransHash, nullptr))
     {
         loaded = false;
         WriteLog (lsWARNING, Ledger) << "Don't have TX root for ledger";
     }
     if (mAccountHash.isNonZero () && !mAccountStateMap->fetchRoot (mAccountHash, nullptr))
     {
         loaded = false;
         WriteLog (lsWARNING, Ledger) << "Don't have AS root for ledger";
     }
     mTransactionMap->setImmutable ();
     mAccountStateMap->setImmutable ();
     initializeFees ();
 }
ripple::Ledger::Ledger (Blob const & rawLedger, bool hasPrefix)
Definition at line 177 of file Ledger.cpp.
References initializeFees(), and setRaw().
     : mClosed (false)
     , mValidated (false)
     , mValidHash (false)
     , mAccepted (false)
     , mImmutable (true)
 {
     Serializer s (rawLedger);
     setRaw (s, hasPrefix);
     initializeFees ();
 }
ripple::Ledger::Ledger (const std::string & rawLedger, bool hasPrefix)
Definition at line 192 of file Ledger.cpp.
References initializeFees(), and setRaw().
     : mClosed (false)
     , mValidated (false)
     , mValidHash (false)
     , mAccepted (false)
     , mImmutable (true)
 {
     Serializer s (rawLedger);
     setRaw (s, hasPrefix);
     initializeFees ();
 }
ripple::Ledger::Ledger (bool dummy, Ledger & previous)
Definition at line 138 of file Ledger.cpp.
References ripple::getApp(), getCloseAgree(), getCloseTimeNC(), getHash(), ripple::ContinuousLedgerTiming::getNextLedgerTimeResolution(), initializeFees(), ripple::base_uint< BITS >::isNonZero(), mCloseResolution, mCloseTime, mLedgerSeq, mParentHash, roundCloseTime(), and updateHash().
     : mTotCoins (prevLedger.mTotCoins)
     , mLedgerSeq (prevLedger.mLedgerSeq + 1)
     , mParentCloseTime (prevLedger.mCloseTime)
     , mCloseResolution (prevLedger.mCloseResolution)
     , mCloseFlags (0)
     , mClosed (false)
     , mValidated (false)
     , mValidHash (false)
     , mAccepted (false)
     , mImmutable (false)
     , mTransactionMap (boost::make_shared <SHAMap> (smtTRANSACTION,
         std::ref (getApp().getFullBelowCache())))
     , mAccountStateMap (prevLedger.mAccountStateMap->snapShot (true))
 {
     prevLedger.updateHash ();
     mParentHash = prevLedger.getHash ();
     assert (mParentHash.isNonZero ());
     mCloseResolution = ContinuousLedgerTiming::getNextLedgerTimeResolution (
                            prevLedger.mCloseResolution,
                            prevLedger.getCloseAgree (),
                            mLedgerSeq);
     if (prevLedger.mCloseTime == 0)
     {
         mCloseTime = roundCloseTime (getApp().getOPs ().getCloseTimeNC (), mCloseResolution);
     }
     else
     {
         mCloseTime = prevLedger.mCloseTime + mCloseResolution;
     }
     initializeFees ();
 }
ripple::Ledger::Ledger (Ledger & target, bool isMutable)
Definition at line 116 of file Ledger.cpp.
References initializeFees(), and updateHash().
     : mParentHash (ledger.mParentHash)
     , mTotCoins (ledger.mTotCoins)
     , mLedgerSeq (ledger.mLedgerSeq)
     , mCloseTime (ledger.mCloseTime)
     , mParentCloseTime (ledger.mParentCloseTime)
     , mCloseResolution (ledger.mCloseResolution)
     , mCloseFlags (ledger.mCloseFlags)
     , mClosed (ledger.mClosed)
     , mValidated (ledger.mValidated)
     , mValidHash (false)
     , mAccepted (ledger.mAccepted)
     , mImmutable (!isMutable)
     , mTransactionMap (ledger.mTransactionMap->snapShot (isMutable))
     , mAccountStateMap (ledger.mAccountStateMap->snapShot (isMutable))
 {
     updateHash ();
     initializeFees ();
 }
ripple::Ledger::~Ledger ()
Definition at line 204 of file Ledger.cpp.
References beast::String::fromNumber(), mAccountStateMap, and mTransactionMap.
 {
     if (mTransactionMap)
     {
         logTimedDestroy <Ledger> (mTransactionMap,
             beast::String ("mTransactionMap with ") +
                 beast::String::fromNumber (mTransactionMap->size ()) + " items");
     }
     if (mAccountStateMap)
     {
         logTimedDestroy <Ledger> (mAccountStateMap,
             beast::String ("mAccountStateMap with ") +
                 beast::String::fromNumber (mAccountStateMap->size ()) + " items");
     }
 }
Member Function Documentation
void ripple::Ledger::addJson (Json::Value & ret, int options)
Definition at line 1006 of file Ledger.cpp.
References getJson().
 {
     ret["ledger"] = getJson (options);
 }
void ripple::Ledger::addRaw (Serializer & s) const
Definition at line 285 of file Ledger.cpp.
References ripple::Serializer::add256(), ripple::Serializer::add32(), ripple::Serializer::add64(), ripple::Serializer::add8(), mAccountHash, mCloseFlags, mCloseResolution, mCloseTime, mLedgerSeq, mParentCloseTime, mParentHash, mTotCoins, and mTransHash.
Referenced by saveValidatedLedger(), and updateHash().
 {
     s.add32 (mLedgerSeq);
     s.add64 (mTotCoins);
     s.add256 (mParentHash);
     s.add256 (mTransHash);
     s.add256 (mAccountHash);
     s.add32 (mParentCloseTime);
     s.add32 (mCloseTime);
     s.add8 (mCloseResolution);
     s.add8 (mCloseFlags);
 }
bool ripple::Ledger::addTransaction (uint256 const & id, const Serializer & txn)
Definition at line 366 of file Ledger.cpp.
References ripple::lsWARNING, mTransactionMap, mValidHash, ripple::Serializer::peekData(), and WriteLog.
 {
     // low-level - just add to table
     SHAMapItem::pointer item = boost::make_shared<SHAMapItem> (txID, txn.peekData ());
     if (!mTransactionMap->addGiveItem (item, true, false))
     {
         WriteLog (lsWARNING, Ledger) << "Attempt to add transaction to ledger that already had it";
         return false;
     }
     mValidHash = false;
     return true;
 }
bool ripple::Ledger::addTransaction (uint256 const & id, const Serializer & txn, const Serializer & metaData)
Definition at line 381 of file Ledger.cpp.
References ripple::Serializer::addVL(), ripple::Serializer::getDataLength(), ripple::lsFATAL, mTransactionMap, mValidHash, ripple::Serializer::peekData(), and WriteLog.
 {
     // low-level - just add to table
     Serializer s (txn.getDataLength () + md.getDataLength () + 16);
     s.addVL (txn.peekData ());
     s.addVL (md.peekData ());
     SHAMapItem::pointer item = boost::make_shared<SHAMapItem> (txID, s.peekData ());
     if (!mTransactionMap->addGiveItem (item, true, true))
     {
         WriteLog (lsFATAL, Ledger) << "Attempt to add transaction+MD to ledger that already had it";
         return false;
     }
     mValidHash = false;
     return true;
 }
bool ripple::Ledger::assertSane ()
Definition at line 1796 of file Ledger.cpp.
References ripple::base_uint< BITS >::GetHex(), getJson(), ripple::base_uint< BITS >::isNonZero(), rocksdb::Log(), ripple::lsFATAL, mAccountHash, mAccountStateMap, mHash, mTransactionMap, and mTransHash.
 {
     if (mHash.isNonZero () &&
             mAccountHash.isNonZero () &&
             mAccountStateMap &&
             mTransactionMap &&
             (mAccountHash == mAccountStateMap->getHash ()) &&
             (mTransHash == mTransactionMap->getHash ()))
     {
         return true;
     }
     Log (lsFATAL) << "ledger is not sane";
     Json::Value j = getJson (0);
     j ["accountTreeHash"] = mAccountHash.GetHex ();
     j ["transTreeHash"] = mTransHash.GetHex ();
     assert (false);
     return false;
 }
void ripple::Ledger::destroyCoins (std::uint64_t fee) inline
Definition at line 187 of file Ledger.h.
References mTotCoins.
     {
         mTotCoins -= fee;
     }
void ripple::Ledger::dropCache () inline
Definition at line 230 of file Ledger.h.
References isImmutable(), mAccountStateMap, and mTransactionMap.
     {
         assert (isImmutable ());
         if (mTransactionMap)
             mTransactionMap->dropCache ();
         if (mAccountStateMap)
             mAccountStateMap->dropCache ();
     }
uint256 const& ripple::Ledger::getAccountHash () const inline
Definition at line 179 of file Ledger.h.
References mAccountHash.
Referenced by saveValidatedLedger().
     {
         return mAccountHash;
     }
SLE::pointer ripple::Ledger::getAccountRoot (const uint160 & accountID)
Definition at line 1402 of file Ledger.cpp.
References getAccountRootIndex(), getASNodeI(), and ripple::ltACCOUNT_ROOT.
 {
     return getASNodeI (getAccountRootIndex (accountID), ltACCOUNT_ROOT);
 }
SLE::pointer ripple::Ledger::getAccountRoot (const RippleAddress & naAccountID)
Definition at line 1407 of file Ledger.cpp.
References ripple::RippleAddress::getAccountID(), getAccountRootIndex(), getASNodeI(), and ripple::ltACCOUNT_ROOT.
 {
     return getASNodeI (getAccountRootIndex (naAccountID.getAccountID ()), ltACCOUNT_ROOT);
 }
uint256 ripple::Ledger::getAccountRootIndex (const uint160 & uAccountID) static
Definition at line 1489 of file Ledger.cpp.
References ripple::Serializer::add16(), ripple::Serializer::add160(), ripple::Serializer::getSHA512Half(), and ripple::spaceAccount.
Referenced by ripple::LedgerEntrySet::accountHolds(), ripple::LedgerEntrySet::accountSend(), ripple::AccountState::AccountState(), ripple::Pathfinder::addLink(), ripple::Transactor::apply(), ripple::TransactionEngine::applyTransaction(), ripple::WalletAddTransactor::doApply(), ripple::TrustSetTransactor::doApply(), ripple::PaymentTransactor::doApply(), ripple::OfferCreateTransactor::doApply(), ripple::RPCHandler::doLedgerEntry(), ripple::Pathfinder::findPaths(), getAccountRoot(), getAccountRootIndex(), getAccountState(), ripple::SerializedLedgerEntry::getOwners(), ripple::Pathfinder::getPathsOut(), hasAccount(), ripple::LedgerEntrySet::ownerCountAdjust(), ripple::PathState::pushNode(), ripple::LedgerEntrySet::rippleCredit(), ripple::LedgerEntrySet::rippleTransferRate(), ripple::LedgerEntrySet::threadTx(), and ripple::RPC::transactionSign().
 {
     Serializer  s (22);
     s.add16 (spaceAccount); //  2
     s.add160 (uAccountID);  // 20
     return s.getSHA512Half ();
 }
static uint256 ripple::Ledger::getAccountRootIndex (const RippleAddress & account) inline static
Definition at line 313 of file Ledger.h.
References ripple::RippleAddress::getAccountID(), and getAccountRootIndex().
     {
         return getAccountRootIndex (account.getAccountID ());
     }
AccountState::pointer ripple::Ledger::getAccountState (const RippleAddress & acctID)
Definition at line 326 of file Ledger.cpp.
References getAccountRootIndex(), ripple::base_uint< BITS >::GetHex(), getSLEi(), ripple::RippleAddress::humanAccountID(), ripple::lsDEBUG, ripple::ltACCOUNT_ROOT, and WriteLog.
 {
 #ifdef BEAST_DEBUG
     //  Log::out() << "Ledger:getAccountState(" << accountID.humanAccountID() << ")";
 #endif
     SLE::pointer sle = getSLEi (Ledger::getAccountRootIndex (accountID));
     if (!sle)
     {
         WriteLog (lsDEBUG, Ledger) << "Ledger:getAccountState:" <<
             " not found: " << accountID.humanAccountID () <<
             ": " << Ledger::getAccountRootIndex (accountID).GetHex ();
         return AccountState::pointer ();
     }
     if (sle->getType () != ltACCOUNT_ROOT)
         return AccountState::pointer ();
     return boost::make_shared<AccountState> (sle, accountID);
 }
SLE::pointer ripple::Ledger::getASNode (LedgerStateParms & parms, uint256 const & nodeID, LedgerEntryType let) protected
Definition at line 1367 of file Ledger.cpp.
References ripple::lepCREATE, ripple::lepCREATED, ripple::lepMISSING, ripple::lepOKAY, ripple::lepWRONGTYPE, and mAccountStateMap.
Referenced by updateFees().
 {
     SHAMapItem::pointer account = mAccountStateMap->peekItem (nodeID);
     if (!account)
     {
         if ( (parms & lepCREATE) == 0 )
         {
             parms = lepMISSING;
             return SLE::pointer ();
         }
         parms = parms | lepCREATED | lepOKAY;
         SLE::pointer sle = boost::make_shared<SLE> (let, nodeID);
         return sle;
     }
     SLE::pointer sle =
         boost::make_shared<SLE> (account->peekSerializer (), nodeID);
     if (sle->getType () != let)
     {
         // maybe it's a currency or something
         parms = parms | lepWRONGTYPE;
         return SLE::pointer ();
     }
     parms = parms | lepOKAY;
     return sle;
 }
SLE::pointer ripple::Ledger::getASNodeI (uint256 const & nodeID, LedgerEntryType let) protected
Definition at line 1357 of file Ledger.cpp.
References getSLEi().
Referenced by getAccountRoot(), getDirNode(), getGenerator(), getNickname(), getOffer(), and getRippleState().
 {
     SLE::pointer node = getSLEi (nodeID);
     if (node && (node->getType () != let))
         node.reset ();
     return node;
 }
std::uint64_t ripple::Ledger::getBaseFee () inline
Definition at line 441 of file Ledger.h.
References mBaseFee, and updateFees().
     {
         if (!mBaseFee) updateFees ();
         return mBaseFee;
     }
uint256 ripple::Ledger::getBookBase (const uint160 & uTakerPaysCurrency, const uint160 & uTakerPaysIssuerID, const uint160 & uTakerGetsCurrency, const uint160 & uTakerGetsIssuerID) static
Definition at line 1670 of file Ledger.cpp.
References ripple::Serializer::add16(), ripple::Serializer::add160(), ripple::RippleAddress::createHumanAccountID(), ripple::STAmount::createHumanCurrency(), getQualityIndex(), ripple::Serializer::getSHA512Half(), isValidBook(), ripple::lsTRACE, ripple::spaceBookDir, ripple::base_uint< BITS >::ToString(), and WriteLog.
Referenced by ripple::OrderBookDB::addOrderBook(), ripple::BookDirIterator::BookDirIterator(), ripple::RippleCalc::calcNodeAdvance(), ripple::OfferCreateTransactor::doApply(), ripple::NetworkOPsImp::getBookPage(), and ripple::updateHelper().
 {
     Serializer  s (82);
     s.add16 (spaceBookDir);         //  2
     s.add160 (uTakerPaysCurrency);  // 20
     s.add160 (uTakerGetsCurrency);  // 20
     s.add160 (uTakerPaysIssuerID);  // 20
     s.add160 (uTakerGetsIssuerID);  // 20
     uint256 uBaseIndex  = getQualityIndex (s.getSHA512Half ()); // Return with quality 0.
     WriteLog (lsTRACE, Ledger) << "getBookBase" <<
         "(" << STAmount::createHumanCurrency (uTakerPaysCurrency) <<
         "," << RippleAddress::createHumanAccountID (uTakerPaysIssuerID) <<
         "," << STAmount::createHumanCurrency (uTakerGetsCurrency) <<
         "," << RippleAddress::createHumanAccountID (uTakerGetsIssuerID) <<
         ") = " << uBaseIndex.ToString ();
     assert (isValidBook (uTakerPaysCurrency, uTakerPaysIssuerID, uTakerGetsCurrency, uTakerGetsIssuerID));
     return uBaseIndex;
 }
bool ripple::Ledger::getCloseAgree () const inline
Definition at line 207 of file Ledger.h.
References mCloseFlags, and sLCF_NoConsensusTime.
Referenced by Ledger().
     {
         return (mCloseFlags & sLCF_NoConsensusTime) == 0;
     }
int ripple::Ledger::getCloseResolution () const inline
Definition at line 203 of file Ledger.h.
References mCloseResolution.
     {
         return mCloseResolution;
     }
boost::posix_time::ptime ripple::Ledger::getCloseTime () const
Definition at line 1140 of file Ledger.cpp.
References mCloseTime, and ripple::ptFromSeconds().
 {
     return ptFromSeconds (mCloseTime);
 }
std::uint32_t ripple::Ledger::getCloseTimeNC () const inline
Definition at line 191 of file Ledger.h.
References mCloseTime.
Referenced by Ledger().
     {
         return mCloseTime;
     }
static char const* ripple::Ledger::getCountedObjectName () inline static
Definition at line 81 of file Ledger.h.
 { return "Ledger"; }
SLE::pointer ripple::Ledger::getDirNode (uint256 const & uNodeIndex)
Definition at line 1416 of file Ledger.cpp.
References getASNodeI(), and ripple::ltDIR_NODE.
 {
     return getASNodeI (uNodeIndex, ltDIR_NODE);
 }
uint256 ripple::Ledger::getDirNodeIndex (uint256 const & uDirRoot, const std::uint64_t uNodeIndex = 0) static
Definition at line 1695 of file Ledger.cpp.
References ripple::Serializer::add16(), ripple::Serializer::add256(), ripple::Serializer::add64(), ripple::Serializer::getSHA512Half(), and ripple::spaceDirNode.
Referenced by ripple::LedgerEntrySet::dirAdd(), ripple::LedgerEntrySet::dirCount(), ripple::LedgerEntrySet::dirDelete(), ripple::LedgerEntrySet::dirIsEmpty(), ripple::LedgerEntrySet::dirNext(), ripple::RPCHandler::doLedgerEntry(), ripple::AccountItems::fillItems(), ripple::NetworkOPsImp::getOwnerInfo(), and visitAccountItems().
 {
     if (uNodeIndex)
     {
         Serializer  s (42);
         s.add16 (spaceDirNode);     //  2
         s.add256 (uDirRoot);        // 32
         s.add64 (uNodeIndex);       //  8
         return s.getSHA512Half ();
     }
     else
     {
         return uDirRoot;
     }
 }
uint256 ripple::Ledger::getFirstLedgerIndex ()
Definition at line 1313 of file Ledger.cpp.
References mAccountStateMap.
 {
     SHAMapItem::pointer node = mAccountStateMap->peekFirstItem ();
     return node ? node->getTag () : uint256 ();
 }
SLE::pointer ripple::Ledger::getGenerator (const uint160 & uGeneratorID)
Definition at line 1425 of file Ledger.cpp.
References getASNodeI(), getGeneratorIndex(), and ripple::ltGENERATOR_MAP.
 {
     return getASNodeI (getGeneratorIndex (uGeneratorID), ltGENERATOR_MAP);
 }
uint256 ripple::Ledger::getGeneratorIndex (const uint160 & uGeneratorID) static
Definition at line 1713 of file Ledger.cpp.
References ripple::Serializer::add16(), ripple::Serializer::add160(), ripple::Serializer::getSHA512Half(), and ripple::spaceGenerator.
Referenced by ripple::RPCHandler::doLedgerEntry(), and getGenerator().
 {
     Serializer  s (22);
     s.add16 (spaceGenerator);   //  2
     s.add160 (uGeneratorID);    // 20
     return s.getSHA512Half ();
 }
uint256 ripple::Ledger::getHash ()
Definition at line 550 of file Ledger.cpp.
References mHash, mValidHash, and updateHash().
Referenced by getLedgerHash(), Ledger(), pendSaveValidated(), saveValidatedLedger(), and ripple::LedgerConsensusImp::statusChange().
 {
     if (!mValidHash)
         updateHash ();
     return mHash;
 }
uint256 ripple::Ledger::getHashByIndex (std::uint32_t index) static
Definition at line 882 of file Ledger.cpp.
References db, ripple::Database::endIterRows(), ripple::Database::executeSQL(), ripple::getApp(), ripple::DatabaseCon::getDB(), ripple::Application::getLedgerDB(), ripple::Database::getStr(), hash, ripple::base_uint< BITS >::SetHexExact(), and ripple::Database::startIterRows().
Referenced by ripple::LedgerMasterImp::doAdvance(), and ripple::LedgerMasterImp::getHashBySeq().
 {
     uint256 ret;
     std::string sql = "SELECT LedgerHash FROM Ledgers INDEXED BY SeqLedger WHERE LedgerSeq='";
     sql.append (beast::lexicalCastThrow <std::string> (ledgerIndex));
     sql.append ("';");
     std::string hash;
     {
         Database* db = getApp().getLedgerDB ()->getDB ();
         DeprecatedScopedLock sl (getApp().getLedgerDB ()->getDBLock ());
         if (!db->executeSQL (sql) || !db->startIterRows ())
             return ret;
         db->getStr ("LedgerHash", hash);
         db->endIterRows ();
     }
     ret.SetHexExact (hash);
     return ret;
 }
bool ripple::Ledger::getHashesByIndex (std::uint32_t index, uint256 & ledgerHash, uint256 & parentHash) static
Definition at line 906 of file Ledger.cpp.
References ripple::SqliteStatement::bind(), db, ripple::Database::endIterRows(), ripple::Database::executeSQL(), ripple::getApp(), ripple::DatabaseCon::getDB(), ripple::DatabaseCon::getDBLock(), ripple::Application::getLedgerDB(), ripple::Database::getSqliteDB(), ripple::Database::getStr(), hash, ripple::base_uint< BITS >::isNonZero(), ripple::lsFATAL, ripple::lsTRACE, ripple::base_uint< BITS >::SetHexExact(), ripple::Database::startIterRows(), and WriteLog.
Referenced by ripple::LedgerMasterImp::tryFill().
 {
 #ifndef NO_SQLITE3_PREPARE
     DatabaseCon* con = getApp().getLedgerDB ();
     DeprecatedScopedLock sl (con->getDBLock ());
     SqliteStatement pSt (con->getDB ()->getSqliteDB (),
                          "SELECT LedgerHash,PrevHash FROM Ledgers INDEXED BY SeqLedger Where LedgerSeq = ?;");
     pSt.bind (1, ledgerIndex);
     int ret = pSt.step ();
     if (pSt.isDone (ret))
     {
         WriteLog (lsTRACE, Ledger) << "Don't have ledger " << ledgerIndex;
         return false;
     }
     if (!pSt.isRow (ret))
     {
         assert (false);
         WriteLog (lsFATAL, Ledger) << "Unexpected statement result " << ret;
         return false;
     }
     ledgerHash.SetHexExact (pSt.peekString (0));
     parentHash.SetHexExact (pSt.peekString (1));
     return true;
 #else
     std::string sql = "SELECT LedgerHash,PrevHash FROM Ledgers WHERE LedgerSeq='";
     sql.append (beast::lexicalCastThrow <std::string> (ledgerIndex));
     sql.append ("';");
     std::string hash, prevHash;
     {
         Database* db = getApp().getLedgerDB ()->getDB ();
         DeprecatedScopedLock sl (getApp().getLedgerDB ()->getDBLock ());
         if (!db->executeSQL (sql) || !db->startIterRows ())
             return false;
         db->getStr ("LedgerHash", hash);
         db->getStr ("PrevHash", prevHash);
         db->endIterRows ();
     }
     ledgerHash.SetHexExact (hash);
     parentHash.SetHexExact (prevHash);
     assert (ledgerHash.isNonZero () && ((ledgerIndex == 0) || parentHash.isNonZero ()));
     return true;
 #endif
 }
std::map< std::uint32_t, std::pair< uint256, uint256 > > ripple::Ledger::getHashesByIndex (std::uint32_t minSeq, std::uint32_t maxSeq) static
Definition at line 968 of file Ledger.cpp.
References ripple::getApp(), ripple::DatabaseCon::getDB(), ripple::DatabaseCon::getDBLock(), ripple::Application::getLedgerDB(), and ripple::Database::getSqliteDB().
 {
     std::map< std::uint32_t, std::pair<uint256, uint256> > ret;
     std::string sql = "SELECT LedgerSeq,LedgerHash,PrevHash FROM Ledgers WHERE LedgerSeq >= ";
     sql.append (beast::lexicalCastThrow <std::string> (minSeq));
     sql.append (" AND LedgerSeq <= ");
     sql.append (beast::lexicalCastThrow <std::string> (maxSeq));
     sql.append (";");
     DatabaseCon* con = getApp().getLedgerDB ();
     DeprecatedScopedLock sl (con->getDBLock ());
     SqliteStatement pSt (con->getDB ()->getSqliteDB (), sql);
     while (pSt.isRow (pSt.step ()))
     {
         std::pair<uint256, uint256>& hashes = ret[pSt.getUInt32 (0)];
         hashes.first.SetHexExact (pSt.peekString (1));
         hashes.second.SetHexExact (pSt.peekString (2));
     }
     return ret;
 }
Json::Value ripple::Ledger::getJson (int options)
Definition at line 1021 of file Ledger.cpp.
References Json::Value::append(), Json::arrayValue, BIND_TYPE, ripple::base_uint< BITS >::GetHex(), ripple::SerializedTransaction::getJson(), ripple::is_bit_set(), LEDGER_JSON_DUMP_STATE, LEDGER_JSON_DUMP_TXRP, LEDGER_JSON_EXPAND, LEDGER_JSON_FULL, mAccepted, mAccountHash, mAccountStateMap, mClosed, mCloseFlags, mCloseResolution, mCloseTime, meta, mHash, mLedgerSeq, ripple::LedgerBase::mLock, mParentHash, mTotCoins, mTransactionMap, mTransHash, Json::objectValue, P_1, ripple::ptFromSeconds(), sLCF_NoConsensusTime, ripple::stateItemFullAppender(), ripple::stateItemTagAppender(), ripple::SHAMapTreeNode::tnTRANSACTION_MD, ripple::SHAMapTreeNode::tnTRANSACTION_NM, and visitStateItems().
Referenced by addJson(), assertSane(), and saveValidatedLedger().
 {
     Json::Value ledger (Json::objectValue);
     bool bFull = is_bit_set (options, LEDGER_JSON_FULL);
     ScopedLockType sl (mLock);
     ledger["seqNum"]                = beast::lexicalCastThrow <std::string> (mLedgerSeq); // DEPRECATED
     ledger["parent_hash"]           = mParentHash.GetHex ();
     ledger["ledger_index"]          = beast::lexicalCastThrow <std::string> (mLedgerSeq);
     if (mClosed || bFull)
     {
         if (mClosed)
             ledger["closed"] = true;
         ledger["hash"]              = mHash.GetHex ();                              // DEPRECATED
         ledger["totalCoins"]        = beast::lexicalCastThrow <std::string> (mTotCoins); // DEPRECATED
         ledger["ledger_hash"]       = mHash.GetHex ();
         ledger["transaction_hash"]  = mTransHash.GetHex ();
         ledger["account_hash"]      = mAccountHash.GetHex ();
         ledger["accepted"]          = mAccepted;
         ledger["total_coins"]       = beast::lexicalCastThrow <std::string> (mTotCoins);
         if (mCloseTime != 0)
         {
             ledger["close_time"]            = mCloseTime;
             ledger["close_time_human"]      = boost::posix_time::to_simple_string (ptFromSeconds (mCloseTime));
             ledger["close_time_resolution"] = mCloseResolution;
             if ((mCloseFlags & sLCF_NoConsensusTime) != 0)
                 ledger["close_time_estimated"] = true;
         }
     }
     else
     {
         ledger["closed"] = false;
     }
     if (mTransactionMap && (bFull || is_bit_set (options, LEDGER_JSON_DUMP_TXRP)))
     {
         Json::Value txns (Json::arrayValue);
         SHAMapTreeNode::TNType type;
         for (SHAMapItem::pointer item = mTransactionMap->peekFirstItem (type); !!item;
                 item = mTransactionMap->peekNextItem (item->getTag (), type))
         {
             if (bFull || is_bit_set (options, LEDGER_JSON_EXPAND))
             {
                 if (type == SHAMapTreeNode::tnTRANSACTION_NM)
                 {
                     SerializerIterator sit (item->peekSerializer ());
                     SerializedTransaction txn (sit);
                     txns.append (txn.getJson (0));
                 }
                 else if (type == SHAMapTreeNode::tnTRANSACTION_MD)
                 {
                     SerializerIterator sit (item->peekSerializer ());
                     Serializer sTxn (sit.getVL ());
                     SerializerIterator tsit (sTxn);
                     SerializedTransaction txn (tsit);
                     TransactionMetaSet meta (item->getTag (), mLedgerSeq, sit.getVL ());
                     Json::Value txJson = txn.getJson (0);
                     txJson["metaData"] = meta.getJson (0);
                     txns.append (txJson);
                 }
                 else
                 {
                     Json::Value error = Json::objectValue;
                     error[item->getTag ().GetHex ()] = type;
                     txns.append (error);
                 }
             }
             else txns.append (item->getTag ().GetHex ());
         }
         ledger["transactions"] = txns;
     }
     if (mAccountStateMap && (bFull || is_bit_set (options, LEDGER_JSON_DUMP_STATE)))
     {
         Json::Value& state = (ledger["accountState"] = Json::arrayValue);
         if (bFull || is_bit_set (options, LEDGER_JSON_EXPAND))
             visitStateItems(BIND_TYPE(stateItemFullAppender, std::ref(state), P_1));
         else
             mAccountStateMap->visitLeaves(BIND_TYPE(stateItemTagAppender, std::ref(state), P_1));
     }
     return ledger;
 }
Ledger::pointer ripple::Ledger::getLastFullLedger () static
Definition at line 993 of file Ledger.cpp.
References getSQL(), ripple::lsWARNING, and WriteLog.
Referenced by ripple::ApplicationImp::loadOldLedger().
 {
     try
     {
         return getSQL ("SELECT * from Ledgers order by LedgerSeq desc limit 1;");
     }
     catch (SHAMapMissingNode& sn)
     {
         WriteLog (lsWARNING, Ledger) << "Database contains ledger with missing nodes: " << sn;
         return Ledger::pointer ();
     }
 }
uint256 ripple::Ledger::getLastLedgerIndex ()
Definition at line 1319 of file Ledger.cpp.
References mAccountStateMap.
 {
     SHAMapItem::pointer node = mAccountStateMap->peekLastItem ();
     return node ? node->getTag () : uint256 ();
 }
uint256 ripple::Ledger::getLedgerFeatureIndex () static
Definition at line 1507 of file Ledger.cpp.
References ripple::Serializer::add16(), ripple::Serializer::getSHA512Half(), and ripple::spaceFeature.
Referenced by ripple::ChangeTransactor::applyFeature(), and getLedgerFeatures().
 {
     // get the index of the node that holds the enabled features
     Serializer s (2);
     s.add16 (spaceFeature);
     return s.getSHA512Half ();
 }
std::vector< uint256 > ripple::Ledger::getLedgerFeatures ()
Definition at line 1619 of file Ledger.cpp.
References getLedgerFeatureIndex(), and getSLEi().
 {
     std::vector<uint256> usFeatures;
     SLE::pointer sleFeatures = getSLEi (getLedgerFeatureIndex ());
     if (sleFeatures)
         usFeatures = sleFeatures->getFieldV256 (sfFeatures).peekValue ();
     return usFeatures;
 }
uint256 ripple::Ledger::getLedgerFeeIndex () static
Definition at line 1499 of file Ledger.cpp.
References ripple::Serializer::add16(), ripple::Serializer::getSHA512Half(), and ripple::spaceFee.
Referenced by ripple::ChangeTransactor::applyFee(), and updateFees().
 {
     // get the index of the node that holds the fee schedul
     Serializer s (2);
     s.add16 (spaceFee);
     return s.getSHA512Half ();
 }
uint256 ripple::Ledger::getLedgerHash (std::uint32_t ledgerIndex)
Definition at line 1533 of file Ledger.cpp.
References ripple::STVector256::at(), getHash(), getLedgerHashIndex(), getSLEi(), ripple::lsWARNING, mLedgerSeq, mParentHash, ripple::STVector256::size(), and WriteLog.
 {
     // return the hash of the specified ledger, 0 if not available
     // easy cases
     if (ledgerIndex > mLedgerSeq)
     {
         WriteLog (lsWARNING, Ledger) << "Can't get seq " << ledgerIndex << " from " << mLedgerSeq << " future";
         return uint256 ();
     }
     if (ledgerIndex == mLedgerSeq)
         return getHash ();
     if (ledgerIndex == (mLedgerSeq - 1))
         return mParentHash;
     // within 256
     int diff = mLedgerSeq - ledgerIndex;
     if (diff <= 256)
     {
         SLE::pointer hashIndex = getSLEi (getLedgerHashIndex ());
         if (hashIndex)
         {
             assert (hashIndex->getFieldU32 (sfLastLedgerSequence) == (mLedgerSeq - 1));
             STVector256 vec = hashIndex->getFieldV256 (sfHashes);
             if (vec.size () >= diff)
                 return vec.at (vec.size () - diff);
             WriteLog (lsWARNING, Ledger) << "Ledger " << mLedgerSeq << " missing hash for " << ledgerIndex
                                          << " (" << vec.size () << "," << diff << ")";
         }
         else
         {
             WriteLog (lsWARNING, Ledger) << "Ledger " << mLedgerSeq << ":" << getHash () << " missing normal list";
         }
     }
     if ((ledgerIndex & 0xff) != 0)
     {
         WriteLog (lsWARNING, Ledger) << "Can't get seq " << ledgerIndex << " from " << mLedgerSeq << " past";
         return uint256 ();
     }
     // in skiplist
     SLE::pointer hashIndex = getSLEi (getLedgerHashIndex (ledgerIndex));
     if (hashIndex)
     {
         int lastSeq = hashIndex->getFieldU32 (sfLastLedgerSequence);
         assert (lastSeq >= ledgerIndex);
         assert ((lastSeq & 0xff) == 0);
         int sDiff = (lastSeq - ledgerIndex) >> 8;
         STVector256 vec = hashIndex->getFieldV256 (sfHashes);
         if (vec.size () > sDiff)
             return vec.at (vec.size () - sDiff - 1);
     }
     WriteLog (lsWARNING, Ledger) << "Can't get seq " << ledgerIndex << " from " << mLedgerSeq << " error";
     return uint256 ();
 }
std::vector< std::pair< std::uint32_t, uint256 > > ripple::Ledger::getLedgerHashes ()
Definition at line 1600 of file Ledger.cpp.
References ripple::STVector256::at(), getLedgerHashIndex(), getSLEi(), and ripple::STVector256::size().
 {
     std::vector< std::pair<std::uint32_t, uint256> > ret;
     SLE::pointer hashIndex = getSLEi (getLedgerHashIndex ());
     if (hashIndex)
     {
         STVector256 vec = hashIndex->getFieldV256 (sfHashes);
         int size = vec.size ();
         ret.reserve (size);
         std::uint32_t seq = hashIndex->getFieldU32 (sfLastLedgerSequence) - size;
         for (int i = 0; i < size; ++i)
             ret.push_back (std::make_pair (++seq, vec.at (i)));
     }
     return ret;
 }
uint256 ripple::Ledger::getLedgerHashIndex () static
Definition at line 1515 of file Ledger.cpp.
References ripple::Serializer::add16(), ripple::Serializer::getSHA512Half(), and ripple::spaceSkipList.
Referenced by getLedgerHash(), getLedgerHashes(), and updateSkipList().
 {
     // get the index of the node that holds the last 256 ledgers
     Serializer s (2);
     s.add16 (spaceSkipList);
     return s.getSHA512Half ();
 }
uint256 ripple::Ledger::getLedgerHashIndex (std::uint32_t desiredLedgerIndex) static
Definition at line 1523 of file Ledger.cpp.
References ripple::Serializer::add16(), ripple::Serializer::add32(), ripple::Serializer::getSHA512Half(), and ripple::spaceSkipList.
 {
     // get the index of the node that holds the set of 256 ledgers that includes this ledger's hash
     // (or the first ledger after it if it's not a multiple of 256)
     Serializer s (6);
     s.add16 (spaceSkipList);
     s.add32 (desiredLedgerIndex >> 16);
     return s.getSHA512Half ();
 }
static int ripple::Ledger::getLedgerHashOffset (std::uint32_t desiredLedgerIndex) static
static int ripple::Ledger::getLedgerHashOffset (std::uint32_t desiredLedgerIndex, std::uint32_t currentLedgerIndex) static
std::uint32_t ripple::Ledger::getLedgerSeq () const inline
Definition at line 199 of file Ledger.h.
References mLedgerSeq.
Referenced by pendSaveValidated(), saveValidatedLedger(), and ripple::LedgerConsensusImp::statusChange().
     {
         return mLedgerSeq;
     }
bool ripple::Ledger::getMetaHex (uint256 const & transID, std::string & hex)
Definition at line 533 of file Ledger.cpp.
References ripple::SerializerIterator::getVL(), mTransactionMap, ripple::strHex(), and ripple::SHAMapTreeNode::tnTRANSACTION_MD.
 {
     SHAMapTreeNode::TNType type;
     SHAMapItem::pointer item = mTransactionMap->peekItem (transID, type);
     if (!item)
         return false;
     if (type != SHAMapTreeNode::tnTRANSACTION_MD)
         return false;
     SerializerIterator it (item->peekSerializer ());
     it.getVL (); // skip transaction
     hex = strHex (it.getVL ());
     return true;
 }
std::vector< uint256 > ripple::Ledger::getNeededAccountStateHashes (int max, SHAMapSyncFilter * filter)
Definition at line 2034 of file Ledger.cpp.
References ripple::base_uint< BITS >::isNonZero(), mAccountHash, and mAccountStateMap.
 {
     std::vector<uint256> ret;
     if (mAccountHash.isNonZero ())
     {
         if (mAccountStateMap->getHash ().isZero ())
             ret.push_back (mAccountHash);
         else
             ret = mAccountStateMap->getNeededHashes (max, filter);
     }
     return ret;
 }
std::vector< uint256 > ripple::Ledger::getNeededTransactionHashes (int max, SHAMapSyncFilter * filter)
Definition at line 2019 of file Ledger.cpp.
References ripple::base_uint< BITS >::isNonZero(), mTransactionMap, and mTransHash.
 {
     std::vector<uint256> ret;
     if (mTransHash.isNonZero ())
     {
         if (mTransactionMap->getHash ().isZero ())
             ret.push_back (mTransHash);
         else
             ret = mTransactionMap->getNeededHashes (max, filter);
     }
     return ret;
 }
uint256 ripple::Ledger::getNextLedgerIndex (uint256 const & uHash)
Definition at line 1325 of file Ledger.cpp.
References mAccountStateMap.
 {
     SHAMapItem::pointer node = mAccountStateMap->peekNextItem (uHash);
     return node ? node->getTag () : uint256 ();
 }
uint256 ripple::Ledger::getNextLedgerIndex (uint256 const & uHash, uint256 const & uEnd)
Definition at line 1331 of file Ledger.cpp.
References mAccountStateMap.
 {
     SHAMapItem::pointer node = mAccountStateMap->peekNextItem (uHash);
     if ((!node) || (node->getTag () > uEnd))
         return uint256 ();
     return node->getTag ();
 }
SLE::pointer ripple::Ledger::getNickname (uint256 const & uNickname)
Definition at line 1434 of file Ledger.cpp.
References getASNodeI(), and ripple::ltNICKNAME.
Referenced by getNickname().
 {
     return getASNodeI (uNickname, ltNICKNAME);
 }
SLE::pointer ripple::Ledger::getNickname (const std::string & strNickname) inline
Definition at line 343 of file Ledger.h.
References getNickname(), and getNicknameHash().
     {
         return getNickname (getNicknameHash (strNickname));
     }
static uint256 ripple::Ledger::getNicknameHash (const std::string & strNickname) inline static
Definition at line 330 of file Ledger.h.
References ripple::Serializer::getSHA256().
Referenced by getNickname(), and getNicknameState().
     {
         Serializer s (strNickname);
         return s.getSHA256 ();
     }
uint256 ripple::Ledger::getNicknameIndex (uint256 const & uNickname) static
Definition at line 1726 of file Ledger.cpp.
References ripple::Serializer::add16(), ripple::Serializer::add256(), ripple::Serializer::getSHA512Half(), and ripple::spaceNickname.
Referenced by getNicknameState().
 {
     Serializer  s (34);
     s.add16 (spaceNickname);    //  2
     s.add256 (uNickname);       // 32
     return s.getSHA512Half ();
 }
NicknameState::pointer ripple::Ledger::getNicknameState (uint256 const & uNickname)
Definition at line 349 of file Ledger.cpp.
References getNicknameIndex(), ripple::ltNICKNAME, and mAccountStateMap.
Referenced by getNicknameState().
 {
     SHAMapItem::pointer item = mAccountStateMap->peekItem (Ledger::getNicknameIndex (uNickname));
     if (!item)
     {
         return NicknameState::pointer ();
     }
     SerializedLedgerEntry::pointer sle =
         boost::make_shared<SerializedLedgerEntry> (item->peekSerializer (), item->getTag ());
     if (sle->getType () != ltNICKNAME) return NicknameState::pointer ();
     return boost::make_shared<NicknameState> (sle);
 }
NicknameState::pointer ripple::Ledger::getNicknameState (const std::string & strNickname) inline
Definition at line 337 of file Ledger.h.
References getNicknameHash(), and getNicknameState().
     {
         return getNicknameState (getNicknameHash (strNickname));
     }
SLE::pointer ripple::Ledger::getOffer (uint256 const & uIndex)
Definition at line 1444 of file Ledger.cpp.
References getASNodeI(), and ripple::ltOFFER.
Referenced by getOffer().
 {
     return getASNodeI (uIndex, ltOFFER);
 }
SLE::pointer ripple::Ledger::getOffer (const uint160 & uAccountID, std::uint32_t uSequence) inline
Definition at line 367 of file Ledger.h.
References getOffer(), and getOfferIndex().
     {
         return getOffer (getOfferIndex (uAccountID, uSequence));
     }
uint256 ripple::Ledger::getOfferIndex (const uint160 & uAccountID, std::uint32_t uSequence) static
Definition at line 1736 of file Ledger.cpp.
References ripple::Serializer::add16(), ripple::Serializer::add160(), ripple::Serializer::add32(), ripple::Serializer::getSHA512Half(), and ripple::spaceOffer.
Referenced by ripple::OfferCancelTransactor::doApply(), ripple::OfferCreateTransactor::doApply(), ripple::RPCHandler::doLedgerEntry(), and getOffer().
 {
     Serializer  s (26);
     s.add16 (spaceOffer);       //  2
     s.add160 (uAccountID);      // 20
     s.add32 (uSequence);        //  4
     return s.getSHA512Half ();
 }
uint256 ripple::Ledger::getOwnerDirIndex (const uint160 & uAccountID) static
Definition at line 1747 of file Ledger.cpp.
References ripple::Serializer::add16(), ripple::Serializer::add160(), ripple::Serializer::getSHA512Half(), and ripple::spaceOwnerDir.
Referenced by ripple::AccountSetTransactor::doApply(), ripple::OfferCreateTransactor::doApply(), ripple::RPCHandler::doLedgerEntry(), ripple::AccountItems::fillItems(), ripple::LedgerEntrySet::offerDelete(), ripple::LedgerEntrySet::trustCreate(), ripple::LedgerEntrySet::trustDelete(), and visitAccountItems().
 {
     Serializer  s (22);
     s.add16 (spaceOwnerDir);    //  2
     s.add160 (uAccountID);      // 20
     return s.getSHA512Half ();
 }
std::uint32_t ripple::Ledger::getParentCloseTimeNC () const inline
Definition at line 195 of file Ledger.h.
References mParentCloseTime.
     {
         return mParentCloseTime;
     }
uint256 const& ripple::Ledger::getParentHash () const inline
Definition at line 171 of file Ledger.h.
References mParentHash.
Referenced by ripple::LedgerConsensusImp::statusChange(), and ripple::LedgerConsensusImp::takeInitialPosition().
     {
         return mParentHash;
     }
std::set< std::uint32_t > ripple::Ledger::getPendingSaves () static
Definition at line 1932 of file Ledger.cpp.
References sPendingSaveLock, and sPendingSaves.
Referenced by ripple::LedgerMasterImp::getValidatedRange().
 {
    StaticScopedLockType sl (sPendingSaveLock);
    return sPendingSaves;
 }
uint256 ripple::Ledger::getPrevLedgerIndex (uint256 const & uHash)
Definition at line 1341 of file Ledger.cpp.
References mAccountStateMap.
 {
     SHAMapItem::pointer node = mAccountStateMap->peekPrevItem (uHash);
     return node ? node->getTag () : uint256 ();
 }
uint256 ripple::Ledger::getPrevLedgerIndex (uint256 const & uHash, uint256 const & uBegin)
Definition at line 1347 of file Ledger.cpp.
References mAccountStateMap.
 {
     SHAMapItem::pointer node = mAccountStateMap->peekNextItem (uHash);
     if ((!node) || (node->getTag () < uBegin))
         return uint256 ();
     return node->getTag ();
 }
std::uint64_t ripple::Ledger::getQuality (uint256 const & uBase) static
Definition at line 1473 of file Ledger.cpp.
References ripple::base_uint< BITS >::end().
Referenced by ripple::RippleCalc::calcNodeAdvance(), ripple::NetworkOPsImp::getBookPage(), ripple::BookDirIterator::getCurrentQuality(), ripple::BookDirIterator::getRate(), ripple::core::BookTip::quality(), and ripple::Ledger_test::run().
 {
     return be64toh (((std::uint64_t*) uBase.end ())[-1]);
 }
uint256 ripple::Ledger::getQualityIndex (uint256 const & uBase, const std::uint64_t uNodeDir = 0) static
Definition at line 1459 of file Ledger.cpp.
References ripple::base_uint< BITS >::end().
Referenced by ripple::OfferCreateTransactor::doApply(), and getBookBase().
 {
     // Indexes are stored in big endian format: they print as hex as stored.
     // Most significant bytes are first.  Least significant bytes represent adjacent entries.
     // We place uNodeDir in the 8 right most bytes to be adjacent.
     // Want uNodeDir in big endian format so ++ goes to the next entry for indexes.
     uint256 uNode (uBase);
     ((std::uint64_t*) uNode.end ())[-1] = htobe64 (uNodeDir);
     return uNode;
 }
uint256 ripple::Ledger::getQualityNext (uint256 const & uBase) static
Definition at line 1478 of file Ledger.cpp.
Referenced by ripple::BookDirIterator::BookDirIterator(), ripple::RippleCalc::calcNodeAdvance(), and ripple::NetworkOPsImp::getBookPage().
 {
     static  uint256 uNext ("10000000000000000");
     uint256 uResult = uBase;
     uResult += uNext;
     return uResult;
 }
std::uint32_t ripple::Ledger::getReferenceFeeUnits () inline
Definition at line 434 of file Ledger.h.
References mBaseFee, mReferenceFeeUnits, and updateFees().
     {
         if (!mBaseFee) updateFees ();
         return mReferenceFeeUnits;
     }
std::uint64_t ripple::Ledger::getReserve (int increments) inline
Definition at line 448 of file Ledger.h.
References mBaseFee, mReserveBase, mReserveIncrement, scaleFeeBase(), and updateFees().
     {
         if (!mBaseFee) updateFees ();
         return scaleFeeBase (static_cast<std::uint64_t> (increments) * mReserveIncrement + mReserveBase);
     }
std::uint64_t ripple::Ledger::getReserveInc () inline
Definition at line 455 of file Ledger.h.
References mBaseFee, mReserveIncrement, and updateFees().
     {
         if (!mBaseFee) updateFees ();
         return mReserveIncrement;
     }
SLE::pointer ripple::Ledger::getRippleState (uint256 const & uNode)
Definition at line 1453 of file Ledger.cpp.
References getASNodeI(), and ripple::ltRIPPLE_STATE.
Referenced by getRippleState().
 {
     return getASNodeI (uNode, ltRIPPLE_STATE);
 }
SLE::pointer ripple::Ledger::getRippleState (const RippleAddress & naA, const RippleAddress & naB, const uint160 & uCurrency) inline
Definition at line 424 of file Ledger.h.
References getRippleState(), and getRippleStateIndex().
     {
         return getRippleState (getRippleStateIndex (naA, naB, uCurrency));
     }
SLE::pointer ripple::Ledger::getRippleState (const uint160 & uiA, const uint160 & uiB, const uint160 & uCurrency) inline
Definition at line 429 of file Ledger.h.
References ripple::RippleAddress::createAccountID(), getRippleState(), and getRippleStateIndex().
     {
         return getRippleState (getRippleStateIndex (RippleAddress::createAccountID (uiA), RippleAddress::createAccountID (uiB), uCurrency));
     }
uint256 ripple::Ledger::getRippleStateIndex (const RippleAddress & naA, const RippleAddress & naB, const uint160 & uCurrency) static
Definition at line 1757 of file Ledger.cpp.
References ripple::Serializer::add16(), ripple::Serializer::add160(), ripple::RippleAddress::getAccountID(), ripple::Serializer::getSHA512Half(), and ripple::spaceRipple.
Referenced by ripple::PathState::checkNoRipple(), ripple::TrustSetTransactor::doApply(), ripple::OfferCreateTransactor::doApply(), ripple::RPCHandler::doLedgerEntry(), getRippleState(), getRippleStateIndex(), ripple::Pathfinder::isNoRipple(), ripple::PathState::pushNode(), ripple::LedgerEntrySet::rippleCredit(), ripple::LedgerEntrySet::rippleHolds(), ripple::LedgerEntrySet::rippleLimit(), ripple::LedgerEntrySet::rippleOwed(), and ripple::LedgerEntrySet::rippleQualityIn().
 {
     uint160     uAID    = naA.getAccountID ();
     uint160     uBID    = naB.getAccountID ();
     bool        bAltB   = uAID < uBID;
     Serializer  s (62);
     s.add16 (spaceRipple);          //  2
     s.add160 (bAltB ? uAID : uBID); // 20
     s.add160 (bAltB ? uBID : uAID); // 20
     s.add160 (uCurrency);           // 20
     return s.getSHA512Half ();
 }
static uint256 ripple::Ledger::getRippleStateIndex (const uint160 & uiA, const uint160 & uiB, const uint160 & uCurrency) inline static
Definition at line 417 of file Ledger.h.
References ripple::RippleAddress::createAccountID(), and getRippleStateIndex().
     {
         return getRippleStateIndex (RippleAddress::createAccountID (uiA), RippleAddress::createAccountID (uiB), uCurrency);
     }
SLE::pointer ripple::Ledger::getSLE (uint256 const & uHash)
Definition at line 1191 of file Ledger.cpp.
References mAccountStateMap.
Referenced by updateSkipList().
 {
     SHAMapItem::pointer node = mAccountStateMap->peekItem (uHash);
     if (!node)
         return SLE::pointer ();
     return boost::make_shared<SLE> (node->peekSerializer (), node->getTag ());
 }
SLE::pointer ripple::Ledger::getSLEi (uint256 const & uHash)
Definition at line 1201 of file Ledger.cpp.
References ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::canonicalize(), ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::fetch(), ripple::getApp(), ripple::Application::getSLECache(), hash, and mAccountStateMap.
Referenced by getAccountState(), getASNodeI(), getLedgerFeatures(), getLedgerHash(), getLedgerHashes(), and visitAccountItems().
 {
     uint256 hash;
     SHAMapItem::pointer node = mAccountStateMap->peekItem (uId, hash);
     if (!node)
         return SLE::pointer ();
     SLE::pointer ret = getApp().getSLECache ().fetch (hash);
     if (!ret)
     {
         ret = boost::make_shared<SLE> (node->peekSerializer (), node->getTag ());
         ret->setImmutable ();
         getApp().getSLECache ().canonicalize (hash, ret);
     }
     return ret;
 }
SerializedTransaction::pointer ripple::Ledger::getSMTransaction (SHAMapItem::ref item, SHAMapTreeNode::TNType type, TransactionMetaSet::pointer & txMeta)
Definition at line 452 of file Ledger.cpp.
References mLedgerSeq, ripple::SerializerIterator::reset(), ripple::SHAMapTreeNode::tnTRANSACTION_MD, and ripple::SHAMapTreeNode::tnTRANSACTION_NM.
 {
     SerializerIterator sit (item->peekSerializer ());
     if (type == SHAMapTreeNode::tnTRANSACTION_NM)
     {
         txMeta.reset ();
         return boost::make_shared<SerializedTransaction> (boost::ref (sit));
     }
     else if (type == SHAMapTreeNode::tnTRANSACTION_MD)
     {
         Serializer sTxn (sit.getVL ());
         SerializerIterator tSit (sTxn);
         txMeta = boost::make_shared<TransactionMetaSet> (item->getTag (), mLedgerSeq, sit.getVL ());
         return boost::make_shared<SerializedTransaction> (boost::ref (tSit));
     }
     txMeta.reset ();
     return SerializedTransaction::pointer ();
 }
Ledger::pointer ripple::Ledger::getSQL (const std::string & sqlStatement) static
Definition at line 762 of file Ledger.cpp.
References db, ripple::Database::endIterRows(), ripple::Database::executeSQL(), ripple::getApp(), ripple::Database::getBigInt(), ripple::DatabaseCon::getDB(), ripple::Application::getLedgerDB(), ripple::Database::getStr(), hash, LEDGER_JSON_FULL, rocksdb::Log(), ripple::lsERROR, ripple::lsTRACE, ripple::base_uint< BITS >::SetHexExact(), ShouldLog, ripple::Database::startIterRows(), and WriteLog.
Referenced by getLastFullLedger().
 {
     // only used with sqlite3 prepared statements not used
     uint256 ledgerHash, prevHash, accountHash, transHash;
     std::uint64_t totCoins;
     std::uint32_t closingTime, prevClosingTime, ledgerSeq;
     int closeResolution;
     unsigned closeFlags;
     std::string hash;
     {
         Database* db = getApp().getLedgerDB ()->getDB ();
         DeprecatedScopedLock sl (getApp().getLedgerDB ()->getDBLock ());
         if (!db->executeSQL (sql) || !db->startIterRows ())
             return Ledger::pointer ();
         db->getStr ("LedgerHash", hash);
         ledgerHash.SetHexExact (hash);
         db->getStr ("PrevHash", hash);
         prevHash.SetHexExact (hash);
         db->getStr ("AccountSetHash", hash);
         accountHash.SetHexExact (hash);
         db->getStr ("TransSetHash", hash);
         transHash.SetHexExact (hash);
         totCoins = db->getBigInt ("TotalCoins");
         closingTime = db->getBigInt ("ClosingTime");
         prevClosingTime = db->getBigInt ("PrevClosingTime");
         closeResolution = db->getBigInt ("CloseTimeRes");
         closeFlags = db->getBigInt ("CloseFlags");
         ledgerSeq = db->getBigInt ("LedgerSeq");
         db->endIterRows ();
     }
     // CAUTION: code below appears in two places
     bool loaded;
     Ledger::pointer ret (new Ledger (prevHash, transHash, accountHash, totCoins,
                                      closingTime, prevClosingTime, closeFlags, closeResolution, ledgerSeq, loaded));
     if (!loaded)
         return Ledger::pointer ();
     ret->setClosed ();
     if (getApp().getOPs ().haveLedger (ledgerSeq))
     {
         ret->setAccepted ();
         ret->setValidated ();
     }
     if (ret->getHash () != ledgerHash)
     {
         if (ShouldLog (lsERROR, Ledger))
         {
             Log (lsERROR) << "Failed on ledger";
             Json::Value p;
             ret->addJson (p, LEDGER_JSON_FULL);
             Log (lsERROR) << p;
         }
         assert (false);
         return Ledger::pointer ();
     }
     WriteLog (lsTRACE, Ledger) << "Loaded ledger: " << ledgerHash;
     return ret;
 }
Ledger::pointer ripple::Ledger::getSQL1 (SqliteStatement * stmt) static
Definition at line 830 of file Ledger.cpp.
References ripple::SqliteStatement::getError(), ripple::SqliteStatement::getInt64(), ripple::SqliteStatement::getUInt32(), ripple::SqliteStatement::isDone(), ripple::SqliteStatement::isRow(), ripple::lsINFO, ripple::SqliteStatement::peekString(), ripple::base_uint< BITS >::SetHexExact(), ripple::SqliteStatement::step(), and WriteLog.
Referenced by loadByHash(), and loadByIndex().
 {
     int iRet = stmt->step ();
     if (stmt->isDone (iRet))
         return Ledger::pointer ();
     if (!stmt->isRow (iRet))
     {
         WriteLog (lsINFO, Ledger) << "Ledger not found: " << iRet << " = " << stmt->getError (iRet);
         return Ledger::pointer ();
     }
     uint256 ledgerHash, prevHash, accountHash, transHash;
     std::uint64_t totCoins;
     std::uint32_t closingTime, prevClosingTime, ledgerSeq;
     int closeResolution;
     unsigned closeFlags;
     ledgerHash.SetHexExact (stmt->peekString (0));
     prevHash.SetHexExact (stmt->peekString (1));
     accountHash.SetHexExact (stmt->peekString (2));
     transHash.SetHexExact (stmt->peekString (3));
     totCoins = stmt->getInt64 (4);
     closingTime = stmt->getUInt32 (5);
     prevClosingTime = stmt->getUInt32 (6);
     closeResolution = stmt->getUInt32 (7);
     closeFlags = stmt->getUInt32 (8);
     ledgerSeq = stmt->getUInt32 (9);
     // CAUTION: code below appears in two places
     bool loaded;
     Ledger::pointer ret (new Ledger (prevHash, transHash, accountHash, totCoins,
                                      closingTime, prevClosingTime, closeFlags, closeResolution, ledgerSeq, loaded));
     if (!loaded)
         return Ledger::pointer ();
     return ret;
 }
void ripple::Ledger::getSQL2 (Ledger::ref ret) static
Definition at line 871 of file Ledger.cpp.
References ripple::getApp(), ripple::lsTRACE, and WriteLog.
Referenced by loadByHash(), and loadByIndex().
 {
     ret->setClosed ();
     ret->setImmutable ();
     if (getApp().getOPs ().haveLedger (ret->getLedgerSeq ()))
         ret->setAccepted ();
     WriteLog (lsTRACE, Ledger) << "Loaded ledger: " << ret->getHash ().GetHex ();
 }
SerializedTransaction::pointer ripple::Ledger::getSTransaction (SHAMapItem::ref item, SHAMapTreeNode::TNType type) static
Definition at line 436 of file Ledger.cpp.
References ripple::SHAMapTreeNode::tnTRANSACTION_MD, and ripple::SHAMapTreeNode::tnTRANSACTION_NM.
 {
     SerializerIterator sit (item->peekSerializer ());
     if (type == SHAMapTreeNode::tnTRANSACTION_NM)
         return boost::make_shared<SerializedTransaction> (boost::ref (sit));
     else if (type == SHAMapTreeNode::tnTRANSACTION_MD)
     {
         Serializer sTxn (sit.getVL ());
         SerializerIterator tSit (sTxn);
         return boost::make_shared<SerializedTransaction> (boost::ref (tSit));
     }
     return SerializedTransaction::pointer ();
 }
std::uint64_t ripple::Ledger::getTotalCoins () const inline
Definition at line 183 of file Ledger.h.
References mTotCoins.
     {
         return mTotCoins;
     }
Transaction::pointer ripple::Ledger::getTransaction (uint256 const & transID) const
Definition at line 399 of file Ledger.cpp.
References ripple::TransactionMaster::canonicalize(), ripple::COMMITTED, ripple::TransactionMaster::fetch(), ripple::getApp(), ripple::Application::getMasterTransaction(), ripple::INCLUDED, mClosed, mLedgerSeq, mTransactionMap, ripple::NEW, ripple::Transaction::sharedTransaction(), ripple::SHAMapTreeNode::tnTRANSACTION_MD, and ripple::SHAMapTreeNode::tnTRANSACTION_NM.
 {
     SHAMapTreeNode::TNType type;
     SHAMapItem::pointer item = mTransactionMap->peekItem (transID, type);
     if (!item) return Transaction::pointer ();
     Transaction::pointer txn = getApp().getMasterTransaction ().fetch (transID, false);
     if (txn)
         return txn;
     if (type == SHAMapTreeNode::tnTRANSACTION_NM)
         txn = Transaction::sharedTransaction (item->peekData (), true);
     else if (type == SHAMapTreeNode::tnTRANSACTION_MD)
     {
         Blob txnData;
         int txnLength;
         if (!item->peekSerializer ().getVL (txnData, 0, txnLength))
             return Transaction::pointer ();
         txn = Transaction::sharedTransaction (txnData, false);
     }
     else
     {
         assert (false);
         return Transaction::pointer ();
     }
     if (txn->getStatus () == NEW)
         txn->setStatus (mClosed ? COMMITTED : INCLUDED, mLedgerSeq);
     getApp().getMasterTransaction ().canonicalize (&txn);
     return txn;
 }
bool ripple::Ledger::getTransaction (uint256 const & transID, Transaction::pointer & txn, TransactionMetaSet::pointer & txMeta)
Definition at line 475 of file Ledger.cpp.
References ripple::TransactionMaster::canonicalize(), ripple::COMMITTED, ripple::TransactionMaster::fetch(), ripple::getApp(), ripple::Application::getMasterTransaction(), ripple::INCLUDED, mClosed, mLedgerSeq, mTransactionMap, ripple::NEW, ripple::Transaction::sharedTransaction(), ripple::SHAMapTreeNode::tnTRANSACTION_MD, and ripple::SHAMapTreeNode::tnTRANSACTION_NM.
 {
     SHAMapTreeNode::TNType type;
     SHAMapItem::pointer item = mTransactionMap->peekItem (txID, type);
     if (!item)
         return false;
     if (type == SHAMapTreeNode::tnTRANSACTION_NM)
     {
         // in tree with no metadata
         txn = getApp().getMasterTransaction ().fetch (txID, false);
         meta.reset ();
         if (!txn)
             txn = Transaction::sharedTransaction (item->peekData (), true);
     }
     else if (type == SHAMapTreeNode::tnTRANSACTION_MD)
     {
         // in tree with metadata
         SerializerIterator it (item->peekSerializer ());
         txn = getApp().getMasterTransaction ().fetch (txID, false);
         if (!txn)
             txn = Transaction::sharedTransaction (it.getVL (), true);
         else
             it.getVL (); // skip transaction
         meta = boost::make_shared<TransactionMetaSet> (txID, mLedgerSeq, it.getVL ());
     }
     else
         return false;
     if (txn->getStatus () == NEW)
         txn->setStatus (mClosed ? COMMITTED : INCLUDED, mLedgerSeq);
     getApp().getMasterTransaction ().canonicalize (&txn);
     return true;
 }
bool ripple::Ledger::getTransactionMeta (uint256 const & transID, TransactionMetaSet::pointer & txMeta)
Definition at line 515 of file Ledger.cpp.
References ripple::SerializerIterator::getVL(), mLedgerSeq, mTransactionMap, and ripple::SHAMapTreeNode::tnTRANSACTION_MD.
 {
     SHAMapTreeNode::TNType type;
     SHAMapItem::pointer item = mTransactionMap->peekItem (txID, type);
     if (!item)
         return false;
     if (type != SHAMapTreeNode::tnTRANSACTION_MD)
         return false;
     SerializerIterator it (item->peekSerializer ());
     it.getVL (); // skip transaction
     meta = boost::make_shared<TransactionMetaSet> (txID, mLedgerSeq, it.getVL ());
     return true;
 }
uint256 const& ripple::Ledger::getTransHash () const inline
Definition at line 175 of file Ledger.h.
References mTransHash.
Referenced by saveValidatedLedger().
     {
         return mTransHash;
     }
bool ripple::Ledger::hasAccount (const RippleAddress & acctID)
Definition at line 321 of file Ledger.cpp.
References getAccountRootIndex(), and mAccountStateMap.
 {
     return mAccountStateMap->hasItem (Ledger::getAccountRootIndex (accountID));
 }
bool ripple::Ledger::hasTransaction (uint256 const & TransID) const inline
Definition at line 250 of file Ledger.h.
References mTransactionMap.
Referenced by ripple::LedgerConsensusImp::takeInitialPosition().
     {
         return mTransactionMap->hasItem (TransID);
     }
void ripple::Ledger::initializeFees () private
Definition at line 1958 of file Ledger.cpp.
References mBaseFee, mReferenceFeeUnits, mReserveBase, and mReserveIncrement.
Referenced by Ledger().
 {
     mBaseFee = 0;
     mReferenceFeeUnits = 0;
     mReserveBase = 0;
     mReserveIncrement = 0;
 }
bool ripple::Ledger::isAccepted () inline
Definition at line 144 of file Ledger.h.
References mAccepted.
     {
         return mAccepted;
     }
bool ripple::Ledger::isAcquiring (void)
Definition at line 1125 of file Ledger.cpp.
References isAcquiringAS(), and isAcquiringTx().
 {
     return isAcquiringTx () || isAcquiringAS ();
 }
bool ripple::Ledger::isAcquiringAS (void)
Definition at line 1135 of file Ledger.cpp.
References mAccountStateMap.
Referenced by isAcquiring().
 {
     return mAccountStateMap->isSynching ();
 }
bool ripple::Ledger::isAcquiringTx (void)
Definition at line 1130 of file Ledger.cpp.
References mTransactionMap.
Referenced by isAcquiring().
 {
     return mTransactionMap->isSynching ();
 }
bool ripple::Ledger::isClosed () inline
Definition at line 140 of file Ledger.h.
References mClosed.
     {
         return mClosed;
     }
bool ripple::Ledger::isFixed () inline
Definition at line 156 of file Ledger.h.
References mClosed, and mImmutable.
     {
         return mClosed || mImmutable;
     }
bool ripple::Ledger::isImmutable () inline
Definition at line 152 of file Ledger.h.
References mImmutable.
Referenced by dropCache(), and pendSaveValidated().
     {
         return mImmutable;
     }
bool ripple::Ledger::isValidated () inline
Definition at line 148 of file Ledger.h.
References mValidated.
     {
         return mValidated;
     }
bool ripple::Ledger::isValidBook (const uint160 & uTakerPaysCurrency, const uint160 & uTakerPaysIssuerID, const uint160 & uTakerGetsCurrency, const uint160 & uTakerGetsIssuerID) static
Definition at line 1633 of file Ledger.cpp.
References ripple::base_uint< BITS >::isNonZero(), and ripple::base_uint< BITS >::isZero().
Referenced by ripple::RPCHandler::doSubscribe(), and getBookBase().
 {
     if (uTakerPaysCurrency.isZero ())
     {
         // XRP in
         if (uTakerPaysIssuerID.isNonZero ())    // XRP cannot have an issuer
             return false;
         if (uTakerGetsCurrency.isZero ())       // XRP to XRP not allowed
             return false;
         if (uTakerGetsIssuerID.isZero ())       // non-XRP must have issuer
             return false;
         return true;
     }
     // non-XRP in
     if (uTakerPaysIssuerID.isZero ())           // non-XRP must have issuer
         return false;
     if (uTakerGetsCurrency.isZero ())           // non-XRP to XRP
     {
         if (uTakerGetsIssuerID.isNonZero ())    // XRP cannot have issuer
             return false;
     }
     else                                        // non-XRP to non-XRP
     {
         if ((uTakerPaysCurrency == uTakerGetsCurrency) && (uTakerGetsIssuerID == uTakerPaysIssuerID))
             return false;                       // Input and output cannot be identical
     }
     return true;
 }
Ledger::pointer ripple::Ledger::loadByHash (uint256 const & ledgerHash) static
Definition at line 714 of file Ledger.cpp.
References ripple::SqliteStatement::bind(), db, ripple::getApp(), ripple::DatabaseCon::getDB(), ripple::base_uint< BITS >::GetHex(), ripple::Application::getLedgerDB(), getSQL1(), getSQL2(), and ripple::Database::getSqliteDB().
Referenced by ripple::LedgerHistory::getLedgerByHash(), and ripple::ApplicationImp::loadOldLedger().
 {
     Ledger::pointer ledger;
     {
         Database* db = getApp().getLedgerDB ()->getDB ();
         DeprecatedScopedLock sl (getApp().getLedgerDB ()->getDBLock ());
         SqliteStatement pSt (db->getSqliteDB (), "SELECT "
                              "LedgerHash,PrevHash,AccountSetHash,TransSetHash,TotalCoins,"
                              "ClosingTime,PrevClosingTime,CloseTimeRes,CloseFlags,LedgerSeq"
                              " from Ledgers WHERE LedgerHash = ?;");
         pSt.bind (1, ledgerHash.GetHex ());
         ledger = getSQL1 (&pSt);
     }
     if (ledger)
     {
         assert (ledger->getHash () == ledgerHash);
         Ledger::getSQL2 (ledger);
         ledger->setFull ();
     }
     return ledger;
 }
Ledger::pointer ripple::Ledger::loadByIndex (std::uint32_t ledgerIndex) static
Definition at line 689 of file Ledger.cpp.
References ripple::SqliteStatement::bind(), db, ripple::getApp(), ripple::DatabaseCon::getDB(), ripple::Application::getLedgerDB(), getSQL1(), getSQL2(), and ripple::Database::getSqliteDB().
Referenced by ripple::LedgerCleanerImp::doLedger(), ripple::LedgerHistory::getLedgerBySeq(), and ripple::ApplicationImp::loadOldLedger().
 {
     Ledger::pointer ledger;
     {
         Database* db = getApp().getLedgerDB ()->getDB ();
         DeprecatedScopedLock sl (getApp().getLedgerDB ()->getDBLock ());
         SqliteStatement pSt (db->getSqliteDB (), "SELECT "
                              "LedgerHash,PrevHash,AccountSetHash,TransSetHash,TotalCoins,"
                              "ClosingTime,PrevClosingTime,CloseTimeRes,CloseFlags,LedgerSeq"
                              " from Ledgers WHERE LedgerSeq = ?;");
         pSt.bind (1, ledgerIndex);
         ledger = getSQL1 (&pSt);
     }
     if (ledger)
     {
         Ledger::getSQL2 (ledger);
         ledger->setFull ();
     }
     return ledger;
 }
void ripple::Ledger::ownerDirDescriber (SLE::ref sle, bool , const uint160 & owner) static
Definition at line 1938 of file Ledger.cpp.
Referenced by ripple::OfferCreateTransactor::doApply(), and ripple::LedgerEntrySet::trustCreate().
 {
     sle->setFieldAccount (sfOwner, owner);
 }
SHAMap::ref ripple::Ledger::peekAccountStateMap () inline
Definition at line 226 of file Ledger.h.
References mAccountStateMap.
     {
         return mAccountStateMap;
     }
SHAMap::ref ripple::Ledger::peekTransactionMap () inline
Definition at line 222 of file Ledger.h.
References mTransactionMap.
Referenced by ripple::LedgerConsensusImp::takeInitialPosition().
     {
         return mTransactionMap;
     }
bool ripple::Ledger::pendSaveValidated (bool isSynchronous, bool isCurrent)
Save, or arrange to save, a fully-validated ledger Returns false on error
Definition at line 1895 of file Ledger.cpp.
References ripple::JobQueue::addJob(), BIND_TYPE, ripple::getApp(), getHash(), ripple::Application::getJobQueue(), getLedgerSeq(), isImmutable(), ripple::jtPUBLEDGER, ripple::jtPUBOLDLEDGER, ripple::lsDEBUG, P_1, saveValidatedLedger(), saveValidatedLedgerAsync(), SF_SAVED, sPendingSaveLock, sPendingSaves, and WriteLog.
 {
     if (!getApp().getHashRouter ().setFlag (getHash (), SF_SAVED))
     {
         WriteLog (lsDEBUG, Ledger) << "Double pend save for " << getLedgerSeq();
         return true;
     }
     assert (isImmutable ());
     {
         StaticScopedLockType sl (sPendingSaveLock);
         if (!sPendingSaves.insert(getLedgerSeq()).second)
         {
             WriteLog (lsDEBUG, Ledger) << "Pend save with seq in pending saves " << getLedgerSeq();
             return true;
         }
     }
     if (isSynchronous)
     {
         return saveValidatedLedger(isCurrent);
     }
     else if (isCurrent)
     {
         getApp().getJobQueue ().addJob (jtPUBLEDGER, "Ledger::pendSave",
             BIND_TYPE (&Ledger::saveValidatedLedgerAsync, shared_from_this (), P_1, isCurrent));
     }
     else
     {
         getApp().getJobQueue ().addJob (jtPUBOLDLEDGER, "Ledger::pendOldSave",
             BIND_TYPE (&Ledger::saveValidatedLedgerAsync, shared_from_this (), P_1, isCurrent));
     }
     return true;
 }
void ripple::Ledger::qualityDirDescriber (SLE::ref sle, bool isNew, const uint160 & uTakerPaysCurrency, const uint160 & uTakerPaysIssuer, const uint160 & uTakerGetsCurrency, const uint160 & uTakerGetsIssuer, const std::uint64_t & uRate) static
Definition at line 1943 of file Ledger.cpp.
References ripple::OrderBookDB::addOrderBook(), ripple::getApp(), and ripple::Application::getOrderBookDB().
Referenced by ripple::OfferCreateTransactor::doApply().
 {
     sle->setFieldH160 (sfTakerPaysCurrency, uTakerPaysCurrency);
     sle->setFieldH160 (sfTakerPaysIssuer, uTakerPaysIssuer);
     sle->setFieldH160 (sfTakerGetsCurrency, uTakerGetsCurrency);
     sle->setFieldH160 (sfTakerGetsIssuer, uTakerGetsIssuer);
     sle->setFieldU64 (sfExchangeRate, uRate);
     if (isNew)
         getApp().getOrderBookDB().addOrderBook(uTakerPaysCurrency, uTakerGetsCurrency,
                                                uTakerPaysIssuer, uTakerGetsIssuer);
 }
std::uint32_t ripple::Ledger::roundCloseTime (std::uint32_t closeTime, std::uint32_t closeResolution) static
Definition at line 1883 of file Ledger.cpp.
Referenced by Ledger(), ripple::LedgerConsensusImp::roundCloseTime(), and setAccepted().
 {
     if (closeTime == 0)
         return 0;
     closeTime += (closeResolution / 2);
     return closeTime - (closeTime % closeResolution);
 }
bool ripple::Ledger::saveValidatedLedger (bool current) protected
Definition at line 558 of file Ledger.cpp.
References ripple::Serializer::add32(), addRaw(), db, ripple::Database::executeSQL(), ripple::LedgerMaster::failedSave(), beast.util.Iter::first(), getAccountHash(), ripple::getApp(), ripple::DatabaseCon::getDB(), getHash(), ripple::base_uint< BITS >::GetHex(), getJson(), ripple::Application::getLedgerDB(), ripple::Application::getLedgerMaster(), getLedgerSeq(), ripple::Application::getMasterTransaction(), ripple::SerializedTransaction::getMetaSQLInsertReplaceHeader(), ripple::Application::getNodeStore(), getTransHash(), ripple::Application::getTxnDB(), ripple::hotLEDGER, ripple::TransactionMaster::inLedger(), ripple::HashPrefix::ledgerMaster, ripple::lsFATAL, ripple::lsTRACE, ripple::lsWARNING, mAccountHash, mAccountStateMap, ripple::AcceptedLedger::makeAcceptedLedger(), mCloseFlags, mCloseResolution, mCloseTime, mHash, mLedgerSeq, ripple::Serializer::modData(), mParentCloseTime, mParentHash, mTotCoins, mTransactionMap, mTransHash, sPendingSaveLock, sPendingSaves, ripple::NodeStore::Database::store(), and WriteLog.
Referenced by pendSaveValidated(), and saveValidatedLedgerAsync().
 {
     WriteLog (lsTRACE, Ledger) << "saveValidatedLedger " << (current ? "" : "fromAcquire ") << getLedgerSeq ();
     static boost::format deleteLedger ("DELETE FROM Ledgers WHERE LedgerSeq = %u;");
     static boost::format deleteTrans1 ("DELETE FROM Transactions WHERE LedgerSeq = %u;");
     static boost::format deleteTrans2 ("DELETE FROM AccountTransactions WHERE LedgerSeq = %u;");
     static boost::format deleteAcctTrans ("DELETE FROM AccountTransactions WHERE TransID = '%s';");
     static boost::format transExists ("SELECT Status FROM Transactions WHERE TransID = '%s';");
     static boost::format
     updateTx ("UPDATE Transactions SET LedgerSeq = %u, Status = '%c', TxnMeta = %s WHERE TransID = '%s';");
     static boost::format addLedger ("INSERT OR REPLACE INTO Ledgers "
                                     "(LedgerHash,LedgerSeq,PrevHash,TotalCoins,ClosingTime,PrevClosingTime,CloseTimeRes,CloseFlags,"
                                     "AccountSetHash,TransSetHash) VALUES ('%s','%u','%s','%s','%u','%u','%d','%u','%s','%s');");
     if (!getAccountHash ().isNonZero ())
     {
         WriteLog (lsFATAL, Ledger) << "AH is zero: " << getJson (0);
         assert (false);
     }
     if (getAccountHash () != mAccountStateMap->getHash ())
     {
         WriteLog (lsFATAL, Ledger) << "sAL: " << getAccountHash () << " != " << mAccountStateMap->getHash ();
         WriteLog (lsFATAL, Ledger) << "saveAcceptedLedger: seq=" << mLedgerSeq << ", current=" << current;
         assert (false);
     }
     assert (getTransHash () == mTransactionMap->getHash ());
     // Save the ledger header in the hashed object store
     {
         Serializer s (128);
         s.add32 (HashPrefix::ledgerMaster);
         addRaw (s);
         getApp().getNodeStore ().store (hotLEDGER, mLedgerSeq, s.modData (), mHash);
     }
     AcceptedLedger::pointer aLedger;
     try
     {
         aLedger = AcceptedLedger::makeAcceptedLedger (shared_from_this ());
     }
     catch (...)
     {
         WriteLog (lsWARNING, Ledger) << "An accepted ledger was missing nodes";
         getApp().getLedgerMaster().failedSave(mLedgerSeq, mHash);
         { // Clients can now trust the database for information about this ledger sequence
             StaticScopedLockType sl (sPendingSaveLock);
             sPendingSaves.erase(getLedgerSeq());
         }
         return false;
     }
     {
         DeprecatedScopedLock sl (getApp().getLedgerDB ()->getDBLock ());
         getApp().getLedgerDB ()->getDB ()->executeSQL (boost::str (deleteLedger % mLedgerSeq));
     }
     {
         Database* db = getApp().getTxnDB ()->getDB ();
         DeprecatedScopedLock dbLock (getApp().getTxnDB ()->getDBLock ());
         db->executeSQL ("BEGIN TRANSACTION;");
         db->executeSQL (boost::str (deleteTrans1 % mLedgerSeq));
         db->executeSQL (boost::str (deleteTrans2 % mLedgerSeq));
         BOOST_FOREACH (const AcceptedLedger::value_type & vt, aLedger->getMap ())
         {
             uint256 txID = vt.second->getTransactionID ();
             getApp().getMasterTransaction ().inLedger (txID, mLedgerSeq);
             db->executeSQL (boost::str (deleteAcctTrans % txID.GetHex ()));
             const std::vector<RippleAddress>& accts = vt.second->getAffected ();
             if (!accts.empty ())
             {
                 std::string sql = "INSERT INTO AccountTransactions (TransID, Account, LedgerSeq, TxnSeq) VALUES ";
                 bool first = true;
                 for (std::vector<RippleAddress>::const_iterator it = accts.begin (), end = accts.end (); it != end; ++it)
                 {
                     if (!first)
                         sql += ", ('";
                     else
                     {
                         sql += "('";
                         first = false;
                     }
                     sql += txID.GetHex ();
                     sql += "','";
                     sql += it->humanAccountID ();
                     sql += "',";
                     sql += beast::lexicalCastThrow <std::string> (getLedgerSeq ());
                     sql += ",";
                     sql += beast::lexicalCastThrow <std::string> (vt.second->getTxnSeq ());
                     sql += ")";
                 }
                 sql += ";";
                 WriteLog (lsTRACE, Ledger) << "ActTx: " << sql;
                 db->executeSQL (sql);
             }
             else
                 WriteLog (lsWARNING, Ledger) << "Transaction in ledger " << mLedgerSeq << " affects no accounts";
             db->executeSQL (SerializedTransaction::getMetaSQLInsertReplaceHeader () +
                             vt.second->getTxn ()->getMetaSQL (getLedgerSeq (), vt.second->getEscMeta ()) + ";");
         }
         db->executeSQL ("COMMIT TRANSACTION;");
     }
     {
         DeprecatedScopedLock sl (getApp().getLedgerDB ()->getDBLock ());
         getApp().getLedgerDB ()->getDB ()->executeSQL (boost::str (addLedger %
                 getHash ().GetHex () % mLedgerSeq % mParentHash.GetHex () %
                 beast::lexicalCastThrow <std::string> (mTotCoins) % mCloseTime % mParentCloseTime %
                 mCloseResolution % mCloseFlags % mAccountHash.GetHex () % mTransHash.GetHex ()));
     }
     { // Clients can now trust the database for information about this ledger sequence
         StaticScopedLockType sl (sPendingSaveLock);
         sPendingSaves.erase(getLedgerSeq());
     }
     return true;
 }
void ripple::Ledger::saveValidatedLedgerAsync (Job & , bool current) inline protected
Definition at line 479 of file Ledger.h.
References saveValidatedLedger().
Referenced by pendSaveValidated().
     {
         saveValidatedLedger(current);
     }
std::uint64_t ripple::Ledger::scaleFeeBase (std::uint64_t fee)
Definition at line 2003 of file Ledger.cpp.
References ripple::getApp(), ripple::Application::getFeeTrack(), mBaseFee, mReferenceFeeUnits, ripple::LoadFeeTrack::scaleFeeBase(), and updateFees().
Referenced by getReserve().
 {
     if (!mBaseFee)
         updateFees ();
     return getApp().getFeeTrack ().scaleFeeBase (fee, mBaseFee, mReferenceFeeUnits);
 }
std::uint64_t ripple::Ledger::scaleFeeLoad (std::uint64_t fee, bool bAdmin)
Definition at line 2011 of file Ledger.cpp.
References ripple::getApp(), ripple::Application::getFeeTrack(), mBaseFee, mReferenceFeeUnits, ripple::LoadFeeTrack::scaleFeeLoad(), and updateFees().
 {
     if (!mBaseFee)
         updateFees ();
     return getApp().getFeeTrack ().scaleFeeLoad (fee, mBaseFee, mReferenceFeeUnits, bAdmin);
 }
void ripple::Ledger::setAccepted (std::uint32_t closeTime, int closeResolution, bool correctCloseTime)
Definition at line 298 of file Ledger.cpp.
References mAccepted, mClosed, mCloseFlags, mCloseResolution, mCloseTime, roundCloseTime(), setImmutable(), and sLCF_NoConsensusTime.
 {
     // used when we witnessed the consensus
     // Rounds the close time, updates the hash, and sets the ledger accepted and immutable
     assert (mClosed && !mAccepted);
     mCloseTime = correctCloseTime ? roundCloseTime (closeTime, closeResolution) : closeTime;
     mCloseResolution = closeResolution;
     mCloseFlags = correctCloseTime ? 0 : sLCF_NoConsensusTime;
     mAccepted = true;
     setImmutable ();
 }
void ripple::Ledger::setAccepted ()
Definition at line 310 of file Ledger.cpp.
References mAccepted, mCloseFlags, mCloseResolution, mCloseTime, roundCloseTime(), setImmutable(), and sLCF_NoConsensusTime.
 {
     // used when we acquired the ledger
     // FIXME assert(mClosed && (mCloseTime != 0) && (mCloseResolution != 0));
     if ((mCloseFlags & sLCF_NoConsensusTime) == 0)
         mCloseTime = roundCloseTime (mCloseTime, mCloseResolution);
     mAccepted = true;
     setImmutable ();
 }
void ripple::Ledger::setAcquiring (void)
Definition at line 1117 of file Ledger.cpp.
References mAccountStateMap, and mTransactionMap.
 {
     if (!mTransactionMap || !mAccountStateMap) throw std::runtime_error ("invalid map");
     mTransactionMap->setSynching ();
     mAccountStateMap->setSynching ();
 }
void ripple::Ledger::setClosed () inline
Definition at line 129 of file Ledger.h.
References mClosed.
     {
         mClosed = true;
     }
void ripple::Ledger::setCloseTime (std::uint32_t ct) inline
Definition at line 213 of file Ledger.h.
References mCloseTime, and mImmutable.
     {
         assert (!mImmutable);
         mCloseTime = ct;
     }
void ripple::Ledger::setCloseTime (boost::posix_time::ptime ptm)
Definition at line 1145 of file Ledger.cpp.
References ripple::iToSeconds(), mCloseTime, and mImmutable.
 {
     assert (!mImmutable);
     mCloseTime = iToSeconds (ptm);
 }
void ripple::Ledger::setFull () inline
Definition at line 160 of file Ledger.h.
References mAccountStateMap, mLedgerSeq, and mTransactionMap.
     {
         mTransactionMap->setLedgerSeq (mLedgerSeq);
         mAccountStateMap->setLedgerSeq (mLedgerSeq);
     }
void ripple::Ledger::setImmutable ()
Definition at line 221 of file Ledger.cpp.
References mAccountStateMap, mImmutable, mTransactionMap, and updateHash().
Referenced by setAccepted().
 {
     // Updates the hash and marks the ledger and its maps immutable
     updateHash ();
     mImmutable = true;
     if (mTransactionMap)
         mTransactionMap->setImmutable ();
     if (mAccountStateMap)
         mAccountStateMap->setImmutable ();
 }
void ripple::Ledger::setRaw (Serializer & s, bool hasPrefix)
Definition at line 258 of file Ledger.cpp.
References ripple::SerializerIterator::get256(), ripple::SerializerIterator::get32(), ripple::SerializerIterator::get64(), ripple::SerializerIterator::get8(), ripple::getApp(), mAccountHash, mAccountStateMap, mCloseFlags, mCloseResolution, mCloseTime, mLedgerSeq, mParentCloseTime, mParentHash, mTotCoins, mTransactionMap, mTransHash, mValidHash, ripple::smtSTATE, ripple::smtTRANSACTION, and updateHash().
Referenced by Ledger().
 {
     SerializerIterator sit (s);
     if (hasPrefix)
         sit.get32 ();
     mLedgerSeq =        sit.get32 ();
     mTotCoins =         sit.get64 ();
     mParentHash =       sit.get256 ();
     mTransHash =        sit.get256 ();
     mAccountHash =      sit.get256 ();
     mParentCloseTime =  sit.get32 ();
     mCloseTime =        sit.get32 ();
     mCloseResolution =  sit.get8 ();
     mCloseFlags =       sit.get8 ();
     updateHash ();
     if (mValidHash)
     {
         mTransactionMap = boost::make_shared<SHAMap> (smtTRANSACTION, mTransHash,
             std::ref (getApp().getFullBelowCache()));
         mAccountStateMap = boost::make_shared<SHAMap> (smtSTATE, mAccountHash,
             std::ref (getApp().getFullBelowCache()));
     }
 }
void ripple::Ledger::setValidated () inline
Definition at line 133 of file Ledger.h.
References mValidated.
     {
         mValidated = true;
     }
void ripple::Ledger::updateFees () protected
Definition at line 1966 of file Ledger.cpp.
References ripple::Config::FEE_ACCOUNT_RESERVE, ripple::Config::FEE_DEFAULT, ripple::Config::FEE_OWNER_RESERVE, getASNode(), ripple::getConfig(), getLedgerFeeIndex(), ripple::lepNONE, ripple::ltFEE_SETTINGS, mBaseFee, mReferenceFeeUnits, mReserveBase, mReserveIncrement, and sPendingSaveLock.
Referenced by getBaseFee(), getReferenceFeeUnits(), getReserve(), getReserveInc(), scaleFeeBase(), and scaleFeeLoad().
 {
     std::uint64_t baseFee = getConfig ().FEE_DEFAULT;
     std::uint32_t referenceFeeUnits = 10;
     std::uint32_t reserveBase = getConfig ().FEE_ACCOUNT_RESERVE;
     std::int64_t reserveIncrement = getConfig ().FEE_OWNER_RESERVE;
     LedgerStateParms p = lepNONE;
     SLE::pointer sle = getASNode (p, Ledger::getLedgerFeeIndex (), ltFEE_SETTINGS);
     if (sle)
     {
         if (sle->getFieldIndex (sfBaseFee) != -1)
             baseFee = sle->getFieldU64 (sfBaseFee);
         if (sle->getFieldIndex (sfReferenceFeeUnits) != -1)
             referenceFeeUnits = sle->getFieldU32 (sfReferenceFeeUnits);
         if (sle->getFieldIndex (sfReserveBase) != -1)
             reserveBase = sle->getFieldU32 (sfReserveBase);
         if (sle->getFieldIndex (sfReserveIncrement) != -1)
             reserveIncrement = sle->getFieldU32 (sfReserveIncrement);
     }
     {
         StaticScopedLockType sl (sPendingSaveLock);
         if (mBaseFee == 0)
         {
             mBaseFee = baseFee;
             mReferenceFeeUnits = referenceFeeUnits;
             mReserveBase = reserveBase;
             mReserveIncrement = reserveIncrement;
         }
     }
 }
void ripple::Ledger::updateHash ()
Definition at line 235 of file Ledger.cpp.
References ripple::Serializer::add32(), addRaw(), ripple::Serializer::getSHA512Half(), ripple::HashPrefix::ledgerMaster, mAccountHash, mAccountStateMap, mHash, mImmutable, mTransactionMap, mTransHash, mValidHash, and ripple::base_uint< BITS >::zero().
Referenced by getHash(), Ledger(), setImmutable(), and setRaw().
 {
     if (!mImmutable)
     {
         if (mTransactionMap)
             mTransHash = mTransactionMap->getHash ();
         else
             mTransHash.zero ();
         if (mAccountStateMap)
             mAccountHash = mAccountStateMap->getHash ();
         else
             mAccountHash.zero ();
     }
     // VFALCO TODO Fix this hard coded magic number 122
     Serializer s (122);
     s.add32 (HashPrefix::ledgerMaster);
     addRaw (s);
     mHash = s.getSHA512Half ();
     mValidHash = true;
 }
void ripple::Ledger::updateSkipList ()
Definition at line 1821 of file Ledger.cpp.
References getLedgerHashIndex(), getSLE(), hash, ripple::lepCREATE, ripple::lepERROR, ripple::ltLEDGER_HASHES, mLedgerSeq, mParentHash, and writeBack().
 {
     if (mLedgerSeq == 0) // genesis ledger has no previous ledger
         return;
     std::uint32_t prevIndex = mLedgerSeq - 1;
     // update record of every 256th ledger
     if ((prevIndex & 0xff) == 0)
     {
         uint256 hash = getLedgerHashIndex (prevIndex);
         SLE::pointer skipList = getSLE (hash);
         std::vector<uint256> hashes;
         // VFALCO TODO Document this skip list concept
         if (!skipList)
             skipList = boost::make_shared<SLE> (ltLEDGER_HASHES, hash);
         else
             hashes = skipList->getFieldV256 (sfHashes).peekValue ();
         assert (hashes.size () <= 256);
         hashes.push_back (mParentHash);
         skipList->setFieldV256 (sfHashes, STVector256 (hashes));
         skipList->setFieldU32 (sfLastLedgerSequence, prevIndex);
         if (writeBack (lepCREATE, skipList) == lepERROR)
         {
             assert (false);
         }
     }
     // update record of past 256 ledger
     uint256 hash = getLedgerHashIndex ();
     SLE::pointer skipList = getSLE (hash);
     std::vector <uint256> hashes;
     if (!skipList)
     {
         skipList = boost::make_shared<SLE> (ltLEDGER_HASHES, hash);
     }
     else
     {
         hashes = skipList->getFieldV256 (sfHashes).peekValue ();
     }
     assert (hashes.size () <= 256);
     if (hashes.size () == 256)
         hashes.erase (hashes.begin ());
     hashes.push_back (mParentHash);
     skipList->setFieldV256 (sfHashes, STVector256 (hashes));
     skipList->setFieldU32 (sfLastLedgerSequence, prevIndex);
     if (writeBack (lepCREATE, skipList) == lepERROR)
     {
         assert (false);
     }
 }
void ripple::Ledger::visitAccountItems (const uint160 & acctID, std::function< void(SLE::ref)> func)
Definition at line 1222 of file Ledger.cpp.
References func, getDirNodeIndex(), getOwnerDirIndex(), getSLEi(), and ripple::ltDIR_NODE.
 {
     // Visit each item in this account's owner directory
     uint256 rootIndex       = Ledger::getOwnerDirIndex (accountID);
     uint256 currentIndex    = rootIndex;
     while (1)
     {
         SLE::pointer ownerDir   = getSLEi (currentIndex);
         if (!ownerDir || (ownerDir->getType () != ltDIR_NODE))
             return;
         BOOST_FOREACH (uint256 const & uNode, ownerDir->getFieldV256 (sfIndexes).peekValue ())
         {
             func (getSLEi (uNode));
         }
         std::uint64_t uNodeNext = ownerDir->getFieldU64 (sfIndexNext);
         if (!uNodeNext)
             return;
         currentIndex    = Ledger::getDirNodeIndex (rootIndex, uNodeNext);
     }
 }
void ripple::Ledger::visitStateItems (std::function< void(SLE::ref)> function)
Definition at line 1255 of file Ledger.cpp.
References BIND_TYPE, ripple::InboundLedger::fcGENERIC, ripple::InboundLedgers::findCreate(), ripple::getApp(), ripple::Application::getInboundLedgers(), ripple::base_uint< BITS >::isNonZero(), mAccountStateMap, mHash, mLedgerSeq, P_1, and ripple::visitHelper().
Referenced by getJson().
 {
     try
     {
         if (mAccountStateMap)
             mAccountStateMap->visitLeaves(BIND_TYPE(&visitHelper, std::ref(function), P_1));
     }
     catch (SHAMapMissingNode&)
     {
         if (mHash.isNonZero ())
             getApp().getInboundLedgers().findCreate(mHash, mLedgerSeq, InboundLedger::fcGENERIC);
         throw;
     }
 }
bool ripple::Ledger::walkLedger ()
Definition at line 1772 of file Ledger.cpp.
References rocksdb::Log(), ripple::lsINFO, mAccountStateMap, mTransactionMap, and ShouldLog.
 {
     std::vector <SHAMapMissingNode> missingNodes1;
     std::vector <SHAMapMissingNode> missingNodes2;
     mAccountStateMap->walkMap (missingNodes1, 32);
     if (ShouldLog (lsINFO, Ledger) && !missingNodes1.empty ())
     {
         Log (lsINFO) << missingNodes1.size () << " missing account node(s)";
         Log (lsINFO) << "First: " << missingNodes1[0];
     }
     mTransactionMap->walkMap (missingNodes2, 32);
     if (ShouldLog (lsINFO, Ledger) && !missingNodes2.empty ())
     {
         Log (lsINFO) << missingNodes2.size () << " missing transaction node(s)";
         Log (lsINFO) << "First: " << missingNodes2[0];
     }
     return missingNodes1.empty () && missingNodes2.empty ();
 }
LedgerStateParms ripple::Ledger::writeBack (LedgerStateParms parms, SLE::ref entry)
Definition at line 1151 of file Ledger.cpp.
References ripple::lepCREATE, ripple::lepCREATED, ripple::lepERROR, ripple::lepMISSING, ripple::lepOKAY, rocksdb::Log(), ripple::lsERROR, and mAccountStateMap.
Referenced by Ledger(), and updateSkipList().
 {
     bool create = false;
     if (!mAccountStateMap->hasItem (entry->getIndex ()))
     {
         if ((parms & lepCREATE) == 0)
         {
             Log (lsERROR) << "WriteBack non-existent node without create";
             return lepMISSING;
         }
         create = true;
     }
     SHAMapItem::pointer item = boost::make_shared<SHAMapItem> (entry->getIndex ());
     entry->add (item->peekSerializer ());
     if (create)
     {
         assert (!mAccountStateMap->hasItem (entry->getIndex ()));
         if (!mAccountStateMap->addGiveItem (item, false, false))
         {
             assert (false);
             return lepERROR;
         }
         return lepCREATED;
     }
     if (!mAccountStateMap->updateGiveItem (item, false, false))
     {
         assert (false);
         return lepERROR;
     }
     return lepOKAY;
 }
Member Data Documentation
bool ripple::Ledger::mAccepted private
Definition at line 502 of file Ledger.h.
Referenced by getJson(), isAccepted(), and setAccepted().
uint256 ripple::Ledger::mAccountHash private
Definition at line 495 of file Ledger.h.
Referenced by addRaw(), assertSane(), getAccountHash(), getJson(), getNeededAccountStateHashes(), Ledger(), saveValidatedLedger(), setRaw(), and updateHash().
SHAMap::pointer ripple::Ledger::mAccountStateMap private
Definition at line 509 of file Ledger.h.
Referenced by assertSane(), dropCache(), getASNode(), getFirstLedgerIndex(), getJson(), getLastLedgerIndex(), getNeededAccountStateHashes(), getNextLedgerIndex(), getNicknameState(), getPrevLedgerIndex(), getSLE(), getSLEi(), hasAccount(), isAcquiringAS(), Ledger(), peekAccountStateMap(), saveValidatedLedger(), setAcquiring(), setFull(), setImmutable(), setRaw(), updateHash(), visitStateItems(), walkLedger(), writeBack(), and ~Ledger().
std::uint64_t ripple::Ledger::mBaseFee private
Definition at line 506 of file Ledger.h.
Referenced by getBaseFee(), getReferenceFeeUnits(), getReserve(), getReserveInc(), initializeFees(), scaleFeeBase(), scaleFeeLoad(), and updateFees().
bool ripple::Ledger::mClosed private
Definition at line 502 of file Ledger.h.
Referenced by getJson(), getTransaction(), isClosed(), isFixed(), setAccepted(), and setClosed().
std::uint32_t ripple::Ledger::mCloseFlags private
Definition at line 501 of file Ledger.h.
Referenced by addRaw(), getCloseAgree(), getJson(), saveValidatedLedger(), setAccepted(), and setRaw().
int ripple::Ledger::mCloseResolution private
Definition at line 500 of file Ledger.h.
Referenced by addRaw(), getCloseResolution(), getJson(), Ledger(), saveValidatedLedger(), setAccepted(), and setRaw().
std::uint32_t ripple::Ledger::mCloseTime private
Definition at line 498 of file Ledger.h.
Referenced by addRaw(), getCloseTime(), getCloseTimeNC(), getJson(), Ledger(), saveValidatedLedger(), setAccepted(), setCloseTime(), and setRaw().
uint256 ripple::Ledger::mHash private
Definition at line 492 of file Ledger.h.
Referenced by assertSane(), getHash(), getJson(), saveValidatedLedger(), updateHash(), and visitStateItems().
bool ripple::Ledger::mImmutable private
Definition at line 502 of file Ledger.h.
Referenced by isFixed(), isImmutable(), setCloseTime(), setImmutable(), and updateHash().
std::uint32_t ripple::Ledger::mLedgerSeq private
Definition at line 497 of file Ledger.h.
Referenced by addRaw(), getJson(), getLedgerHash(), getLedgerSeq(), getSMTransaction(), getTransaction(), getTransactionMeta(), Ledger(), saveValidatedLedger(), setFull(), setRaw(), updateSkipList(), and visitStateItems().
std::uint32_t ripple::Ledger::mParentCloseTime private
Definition at line 499 of file Ledger.h.
Referenced by addRaw(), getParentCloseTimeNC(), saveValidatedLedger(), and setRaw().
uint256 ripple::Ledger::mParentHash private
Definition at line 493 of file Ledger.h.
Referenced by addRaw(), getJson(), getLedgerHash(), getParentHash(), Ledger(), saveValidatedLedger(), setRaw(), and updateSkipList().
std::uint32_t ripple::Ledger::mReferenceFeeUnits private
Definition at line 504 of file Ledger.h.
Referenced by getReferenceFeeUnits(), initializeFees(), scaleFeeBase(), scaleFeeLoad(), and updateFees().
std::uint32_t ripple::Ledger::mReserveBase private
Definition at line 505 of file Ledger.h.
Referenced by getReserve(), initializeFees(), and updateFees().
std::uint32_t ripple::Ledger::mReserveIncrement private
Definition at line 505 of file Ledger.h.
Referenced by getReserve(), getReserveInc(), initializeFees(), and updateFees().
std::uint64_t ripple::Ledger::mTotCoins private
Definition at line 496 of file Ledger.h.
Referenced by addRaw(), destroyCoins(), getJson(), getTotalCoins(), saveValidatedLedger(), and setRaw().
SHAMap::pointer ripple::Ledger::mTransactionMap private
Definition at line 508 of file Ledger.h.
Referenced by addTransaction(), assertSane(), dropCache(), getJson(), getMetaHex(), getNeededTransactionHashes(), getTransaction(), getTransactionMeta(), hasTransaction(), isAcquiringTx(), Ledger(), peekTransactionMap(), saveValidatedLedger(), setAcquiring(), setFull(), setImmutable(), setRaw(), updateHash(), walkLedger(), and ~Ledger().
uint256 ripple::Ledger::mTransHash private
Definition at line 494 of file Ledger.h.
Referenced by addRaw(), assertSane(), getJson(), getNeededTransactionHashes(), getTransHash(), Ledger(), saveValidatedLedger(), setRaw(), and updateHash().
bool ripple::Ledger::mValidated private
Definition at line 502 of file Ledger.h.
Referenced by isValidated(), and setValidated().
bool ripple::Ledger::mValidHash private
Definition at line 502 of file Ledger.h.
Referenced by addTransaction(), getHash(), setRaw(), and updateHash().
const std::uint32_t ripple::Ledger::sLCF_NoConsensusTime = 1 static
Definition at line 102 of file Ledger.h.
Referenced by getCloseAgree(), getJson(), and setAccepted().
Ledger::StaticLockType ripple::Ledger::sPendingSaveLock static private
Definition at line 514 of file Ledger.h.
Referenced by getPendingSaves(), pendSaveValidated(), saveValidatedLedger(), and updateFees().
std::set< std::uint32_t > ripple::Ledger::sPendingSaves static private
Definition at line 516 of file Ledger.h.
Referenced by getPendingSaves(), pendSaveValidated(), and saveValidatedLedger().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/ledger/Ledger.h
rippled/src/ripple_app/ledger/Ledger.cpp