rippled: rocksdb::CacheTest Class Reference
rocksdb::CacheTest Class Reference
Public Member Functions
CacheTest ()
~CacheTest ()
int Lookup (shared_ptr< Cache > cache, int key)
void Insert (shared_ptr< Cache > cache, int key, int value, int charge=1)
void Erase (shared_ptr< Cache > cache, int key)
int Lookup (int key)
void Insert (int key, int value, int charge=1)
void Erase (int key)
int Lookup2 (int key)
void Insert2 (int key, int value, int charge=1)
void Erase2 (int key)
Static Public Member Functions
static void Deleter (const Slice &key, void *v)
Public Attributes
std::vector< int > deleted_keys_
std::vector< int > deleted_values_
shared_ptr< Cache > cache_
shared_ptr< Cache > cache2_
Static Public Attributes
static CacheTest * current_
static const int kCacheSize = 1000
static const int kNumShardBits = 4
static const int kRemoveScanCountLimit = 16
static const int kCacheSize2 = 100
static const int kNumShardBits2 = 2
static const int kRemoveScanCountLimit2 = 200
Detailed Description
Definition at line 33 of file cache_test.cc.
Constructor & Destructor Documentation
rocksdb::CacheTest::CacheTest () inline
Definition at line 55 of file cache_test.cc.
References current_.
               :
       cache_(NewLRUCache(kCacheSize, kNumShardBits, kRemoveScanCountLimit)),
       cache2_(NewLRUCache(kCacheSize2, kNumShardBits2,
                           kRemoveScanCountLimit2)) {
     current_ = this;
   }
rocksdb::CacheTest::~CacheTest () inline
Definition at line 62 of file cache_test.cc.
                {
   }
Member Function Documentation
static void rocksdb::CacheTest::Deleter (const Slice & key, void * v) inline static
Definition at line 37 of file cache_test.cc.
References current_, rocksdb::DecodeKey(), rocksdb::DecodeValue(), deleted_keys_, and deleted_values_.
Referenced by Insert().
{
     current_->deleted_keys_.push_back(DecodeKey(key));
     current_->deleted_values_.push_back(DecodeValue(v));
   }
void rocksdb::CacheTest::Erase (shared_ptr< Cache > cache, int key) inline
Definition at line 79 of file cache_test.cc.
References rocksdb::EncodeKey().
Referenced by Erase(), and Erase2().
{
     cache->Erase(EncodeKey(key));
   }
void rocksdb::CacheTest::Erase (int key) inline
Definition at line 92 of file cache_test.cc.
References cache_, and Erase().
                       {
     Erase(cache_, key);
   }
void rocksdb::CacheTest::Erase2 (int key) inline
Definition at line 104 of file cache_test.cc.
References cache2_, and Erase().
{
     Erase(cache2_, key);
   }
void rocksdb::CacheTest::Insert (shared_ptr< Cache > cache, int key, int value, int charge = 1) inline
Definition at line 74 of file cache_test.cc.
References charge, Deleter(), rocksdb::EncodeKey(), and rocksdb::EncodeValue().
Referenced by Insert(), and Insert2().
{
     cache->Release(cache->Insert(EncodeKey(key), EncodeValue(value), charge,
                                   &CacheTest::Deleter));
   }
void rocksdb::CacheTest::Insert (int key, int value, int charge = 1) inline
Definition at line 88 of file cache_test.cc.
References cache_, charge, and Insert().
{
     Insert(cache_, key, value, charge);
   }
void rocksdb::CacheTest::Insert2 (int key, int value, int charge = 1) inline
Definition at line 100 of file cache_test.cc.
References cache2_, charge, and Insert().
{
     Insert(cache2_, key, value, charge);
   }
int rocksdb::CacheTest::Lookup (shared_ptr< Cache > cache, int key) inline
Definition at line 65 of file cache_test.cc.
References rocksdb::DecodeValue(), and rocksdb::EncodeKey().
Referenced by Lookup(), and Lookup2().
{
     Cache::Handle* handle = cache->Lookup(EncodeKey(key));
     const int r = (handle == nullptr) ? -1 : DecodeValue(cache->Value(handle));
     if (handle != nullptr) {
       cache->Release(handle);
     }
     return r;
   }
int rocksdb::CacheTest::Lookup (int key) inline
Definition at line 84 of file cache_test.cc.
References cache_, and Lookup().
                       {
     return Lookup(cache_, key);
   }
int rocksdb::CacheTest::Lookup2 (int key) inline
Definition at line 96 of file cache_test.cc.
References cache2_, and Lookup().
{
     return Lookup(cache2_, key);
   }
Member Data Documentation
shared_ptr<Cache> rocksdb::CacheTest::cache2_
Definition at line 53 of file cache_test.cc.
Referenced by Erase2(), Insert2(), and Lookup2().
shared_ptr<Cache> rocksdb::CacheTest::cache_
Definition at line 52 of file cache_test.cc.
Referenced by Erase(), Insert(), and Lookup().
CacheTest * rocksdb::CacheTest::current_ static
Definition at line 35 of file cache_test.cc.
Referenced by CacheTest(), and Deleter().
std::vector<int> rocksdb::CacheTest::deleted_keys_
Definition at line 50 of file cache_test.cc.
Referenced by Deleter().
std::vector<int> rocksdb::CacheTest::deleted_values_
Definition at line 51 of file cache_test.cc.
Referenced by Deleter().
const int rocksdb::CacheTest::kCacheSize = 1000 static
Definition at line 42 of file cache_test.cc.
const int rocksdb::CacheTest::kCacheSize2 = 100 static
Definition at line 46 of file cache_test.cc.
const int rocksdb::CacheTest::kNumShardBits = 4 static
Definition at line 43 of file cache_test.cc.
const int rocksdb::CacheTest::kNumShardBits2 = 2 static
Definition at line 47 of file cache_test.cc.
const int rocksdb::CacheTest::kRemoveScanCountLimit = 16 static
Definition at line 44 of file cache_test.cc.
const int rocksdb::CacheTest::kRemoveScanCountLimit2 = 200 static
Definition at line 48 of file cache_test.cc.
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/util/cache_test.cc