rippled: beast::sqdb::detail::type_ptr< T > Class Template Reference
beast::sqdb::detail::type_ptr< T > Class Template Reference
#include <type_ptr.h>
Public Member Functions
type_ptr (T *p)
~type_ptr ()
T * get () const
void release () const
Private Attributes
T * m_p
Detailed Description
template<typename T>
class beast::sqdb::detail::type_ptr< T >
Definition at line 69 of file type_ptr.h.
Constructor & Destructor Documentation
template<typename T > beast::sqdb::detail::type_ptr< T >::type_ptr (T * p) inline
Definition at line 72 of file type_ptr.h.
 : m_p(p) { }
template<typename T > beast::sqdb::detail::type_ptr< T >::~type_ptr () inline
Definition at line 73 of file type_ptr.h.
References beast::sqdb::detail::type_ptr< T >::m_p.
     {
         delete m_p;
     }
Member Function Documentation
template<typename T > T* beast::sqdb::detail::type_ptr< T >::get () const inline
Definition at line 78 of file type_ptr.h.
References beast::sqdb::detail::type_ptr< T >::m_p.
Referenced by beast::sqdb::detail::ref_counted_prepare_info::exchange(), and beast::sqdb::detail::statement_imp::exchange().
     {
         return m_p;
     }
template<typename T > void beast::sqdb::detail::type_ptr< T >::release () const inline
Definition at line 82 of file type_ptr.h.
References beast::sqdb::detail::type_ptr< T >::m_p.
Referenced by beast::sqdb::detail::ref_counted_prepare_info::exchange(), and beast::sqdb::detail::statement_imp::exchange().
     {
         m_p = 0;
     }
Member Data Documentation
template<typename T > T* beast::sqdb::detail::type_ptr< T >::m_p mutable private
Definition at line 88 of file type_ptr.h.
Referenced by beast::sqdb::detail::type_ptr< T >::get(), beast::sqdb::detail::type_ptr< T >::release(), and beast::sqdb::detail::type_ptr< T >::~type_ptr().
The documentation for this class was generated from the following file:
rippled/src/beast/modules/beast_sqdb/detail/type_ptr.h