rippled: rocksdb::port::Mutex Class Reference
rocksdb::port::Mutex Class Reference
#include <port_example.h>
Public Member Functions
Mutex ()
~Mutex ()
void Lock ()
void Unlock ()
void AssertHeld ()
Mutex (bool adaptive=false)
~Mutex ()
void Lock ()
void Unlock ()
void AssertHeld ()
Private Member Functions
Mutex (const Mutex &)
void operator= (const Mutex &)
Private Attributes
pthread_mutex_t mu_
Friends
class CondVar
Detailed Description
Definition at line 31 of file port_example.h.
Constructor & Destructor Documentation
rocksdb::port::Mutex::Mutex ()
rocksdb::port::Mutex::~Mutex ()
Definition at line 46 of file port_posix.cc.
References mu_, and rocksdb::port::PthreadCall().
 { PthreadCall("destroy mutex", pthread_mutex_destroy(&mu_)); }
rocksdb::port::Mutex::Mutex (bool adaptive = false)
Definition at line 27 of file port_posix.cc.
References mu_, and rocksdb::port::PthreadCall().
{
 #ifdef OS_LINUX
   if (!adaptive) {
     PthreadCall("init mutex", pthread_mutex_init(&mu_, NULL));
   } else {
     pthread_mutexattr_t mutex_attr;
     PthreadCall("init mutex attr", pthread_mutexattr_init(&mutex_attr));
     PthreadCall("set mutex attr",
                 pthread_mutexattr_settype(&mutex_attr,
                                           PTHREAD_MUTEX_ADAPTIVE_NP));
     PthreadCall("init mutex", pthread_mutex_init(&mu_, &mutex_attr));
     PthreadCall("destroy mutex attr",
                 pthread_mutexattr_destroy(&mutex_attr));
   }
 #else // ignore adaptive for non-linux platform
   PthreadCall("init mutex", pthread_mutex_init(&mu_, NULL));
 #endif // OS_LINUX
 }
rocksdb::port::Mutex::~Mutex ()
rocksdb::port::Mutex::Mutex (const Mutex &) private
Member Function Documentation
void rocksdb::port::Mutex::AssertHeld ()
Referenced by rocksdb::DBImpl::AllocateCompactionOutputFileNumbers(), rocksdb::DBImpl::BackgroundCompaction(), rocksdb::DBImpl::CleanupCompaction(), rocksdb::DBImpl::DeleteObsoleteFiles(), rocksdb::DBImpl::FindMinimumEmptyLevelFitting(), rocksdb::DBImpl::FindObsoleteFiles(), rocksdb::DBImpl::FlushMemTableToOutputFile(), rocksdb::DBImpl::InstallCompactionResults(), rocksdb::MemTableList::InstallMemtableFlushResults(), rocksdb::VersionSet::LogAndApply(), rocksdb::VersionSet::LogAndApplyHelper(), rocksdb::DBImpl::MakeRoomForWrite(), rocksdb::DBImpl::MaybeScheduleFlushOrCompaction(), rocksdb::DBImpl::Recover(), rocksdb::DBImpl::RecoverLogFile(), rocksdb::DBImpl::ReleaseCompactionUnusedFileNumbers(), rocksdb::DBImpl::WriteLevel0Table(), and rocksdb::DBImpl::WriteLevel0TableForRecovery().
void rocksdb::port::Mutex::AssertHeld () inline
Definition at line 95 of file port_posix.h.
 { }
void rocksdb::port::Mutex::Lock ()
Definition at line 48 of file port_posix.cc.
References mu_, and rocksdb::port::PthreadCall().
Referenced by rocksdb::DBImpl::BackgroundCallCompaction(), rocksdb::DBImpl::BackgroundCallFlush(), rocksdb::TestState::Change(), rocksdb::ReduceDBLevelsCommand::DoCommand(), rocksdb::DBImpl::DoCompactionWork(), rocksdb::DBImpl::GetImpl(), rocksdb::VersionSet::LogAndApply(), rocksdb::DBImpl::LogDBDeployStats(), rocksdb::DBImpl::MakeRoomForWrite(), rocksdb::DBImpl::MultiGet(), rocksdb::MutexLock::MutexLock(), rocksdb::DBImpl::NewInternalIterator(), rocksdb::DB::Open(), rocksdb::DBImpl::OpenCompactionOutputFile(), rocksdb::Benchmark::RunBenchmark(), rocksdb::TEST(), rocksdb::DBImpl::TEST_Destroy_DBImpl(), rocksdb::ThreadBody(), rocksdb::TestState::Wait(), rocksdb::DBImpl::Write(), rocksdb::DBImpl::WriteLevel0Table(), rocksdb::DBImpl::WriteLevel0TableForRecovery(), and rocksdb::DBImpl::~DBImpl().
 { PthreadCall("lock", pthread_mutex_lock(&mu_)); }
void rocksdb::port::Mutex::Lock ()
void rocksdb::port::Mutex::operator= (const Mutex &) private
void rocksdb::port::Mutex::Unlock ()
Definition at line 50 of file port_posix.cc.
References mu_, and rocksdb::port::PthreadCall().
Referenced by rocksdb::DBImpl::BackgroundCallCompaction(), rocksdb::DBImpl::BackgroundCallFlush(), rocksdb::TestState::Change(), rocksdb::ReduceDBLevelsCommand::DoCommand(), rocksdb::DBImpl::DoCompactionWork(), rocksdb::DBImpl::GetImpl(), rocksdb::VersionSet::LogAndApply(), rocksdb::DBImpl::LogDBDeployStats(), rocksdb::DBImpl::MakeRoomForWrite(), rocksdb::DBImpl::MultiGet(), rocksdb::DBImpl::NewInternalIterator(), rocksdb::DB::Open(), rocksdb::DBImpl::OpenCompactionOutputFile(), rocksdb::Benchmark::RunBenchmark(), rocksdb::TEST(), rocksdb::DBImpl::TEST_Destroy_DBImpl(), rocksdb::ThreadBody(), rocksdb::TestState::Wait(), rocksdb::DBImpl::Write(), rocksdb::DBImpl::WriteLevel0Table(), rocksdb::DBImpl::WriteLevel0TableForRecovery(), rocksdb::DBImpl::~DBImpl(), and rocksdb::MutexLock::~MutexLock().
 { PthreadCall("unlock", pthread_mutex_unlock(&mu_)); }
void rocksdb::port::Mutex::Unlock ()
Friends And Related Function Documentation
friend class CondVar friend
Definition at line 98 of file port_posix.h.
Member Data Documentation
pthread_mutex_t rocksdb::port::Mutex::mu_ private
Definition at line 99 of file port_posix.h.
Referenced by Lock(), Mutex(), Unlock(), rocksdb::port::CondVar::Wait(), and ~Mutex().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/port/port_example.h
rippled/src/ripple/rocksdb/rocksdb/port/port_posix.h
rippled/src/ripple/rocksdb/rocksdb/port/port_posix.cc