rippled: ripple::Base58 Class Reference
ripple::Base58 Class Reference
#include <Base58.h>
Classes
class Alphabet
Static Public Member Functions
static Alphabet const & getBitcoinAlphabet ()
static Alphabet const & getRippleAlphabet ()
static std::string raw_encode (unsigned char const *begin, unsigned char const *end, Alphabet const &alphabet, bool withCheck)
static void fourbyte_hash256 (void *out, void const *in, std::size_t bytes)
template<class InputIt >
static std::string encode (InputIt first, InputIt last, Alphabet const &alphabet, bool withCheck)
static Alphabet const & getCurrentAlphabet ()
static void setCurrentAlphabet (Alphabet const &alphabet)
template<class Container >
static std::string encode (Container const &container)
template<class Container >
static std::string encodeWithCheck (Container const &container)
static std::string encode (const unsigned char *pbegin, const unsigned char *pend)
static bool raw_decode (char const *first, char const *last, void *dest, std::size_t size, bool checked, Alphabet const &alphabet)
static bool decode (const char *psz, Blob &vchRet, Alphabet const &alphabet=getCurrentAlphabet())
static bool decode (const std::string &str, Blob &vchRet)
static bool decodeWithCheck (const char *psz, Blob &vchRet, Alphabet const &alphabet=getCurrentAlphabet())
static bool decodeWithCheck (const std::string &str, Blob &vchRet, Alphabet const &alphabet=getCurrentAlphabet())
Static Private Attributes
static Alphabet const * s_currentAlphabet = &Base58::getRippleAlphabet ()
Detailed Description
Performs Base 58 encoding and decoding.
Definition at line 43 of file Base58.h.
Member Function Documentation
bool ripple::Base58::decode (const char * psz, Blob & vchRet, Alphabet const & alphabet = getCurrentAlphabet ()) static
Definition at line 161 of file Base58.cpp.
References ripple::Base58::Alphabet::chars(), ripple::CBigNum::getvch(), and ripple::CBigNum::setuint().
Referenced by decode(), and decodeWithCheck().
 {
     CAutoBN_CTX pctx;
     vchRet.clear ();
     CBigNum bn58 = 58;
     CBigNum bn = 0;
     CBigNum bnChar;
     while (isspace (*psz))
         psz++;
     // Convert big endian string to bignum
     for (const char* p = psz; *p; p++)
     {
         // VFALCO TODO Make this use the inverse table!
         //             Or better yet ditch this and call raw_decode
         //
         const char* p1 = strchr (alphabet.chars(), *p);
         if (p1 == nullptr)
         {
             while (isspace (*p))
                 p++;
             if (*p != '\0')
                 return false;
             break;
         }
         bnChar.setuint (p1 - alphabet.chars());
         if (!BN_mul (&bn, &bn, &bn58, pctx))
             throw bignum_error ("DecodeBase58 : BN_mul failed");
         bn += bnChar;
     }
     // Get bignum as little endian data
     Blob vchTmp = bn.getvch ();
     // Trim off sign byte if present
     if (vchTmp.size () >= 2 && vchTmp.end ()[-1] == 0 && vchTmp.end ()[-2] >= 0x80)
         vchTmp.erase (vchTmp.end () - 1);
     // Restore leading zeros
     int nLeadingZeros = 0;
     for (const char* p = psz; *p == alphabet.chars()[0]; p++)
         nLeadingZeros++;
     vchRet.assign (nLeadingZeros + vchTmp.size (), 0);
     // Convert little endian data to big endian
     std::reverse_copy (vchTmp.begin (), vchTmp.end (), vchRet.end () - vchTmp.size ());
     return true;
 }
bool ripple::Base58::decode (const std::string & str, Blob & vchRet) static
Definition at line 219 of file Base58.cpp.
References decode().
 {
     return decode (str.c_str (), vchRet);
 }
bool ripple::Base58::decodeWithCheck (const char * psz, Blob & vchRet, Alphabet const & alphabet = getCurrentAlphabet()) static
Definition at line 224 of file Base58.cpp.
References decode(), ripple::base_uint< BITS >::end(), hash, and ripple::SHA256Hash().
Referenced by decodeWithCheck(), and ripple::CBase58Data::SetString().
 {
     if (!decode (psz, vchRet, alphabet))
         return false;
     if (vchRet.size () < 4)
     {
         vchRet.clear ();
         return false;
     }
     uint256 hash = SHA256Hash (vchRet.begin (), vchRet.end () - 4);
     if (memcmp (&hash, &vchRet.end ()[-4], 4) != 0)
     {
         vchRet.clear ();
         return false;
     }
     vchRet.resize (vchRet.size () - 4);
     return true;
 }
bool ripple::Base58::decodeWithCheck (const std::string & str, Blob & vchRet, Alphabet const & alphabet = getCurrentAlphabet()) static
Definition at line 247 of file Base58.cpp.
References decodeWithCheck().
 {
     return decodeWithCheck (str.c_str (), vchRet, alphabet);
 }
template<class InputIt > static std::string ripple::Base58::encode (InputIt first, InputIt last, Alphabet const & alphabet, bool withCheck) inline static
Definition at line 86 of file Base58.h.
References beast.util.Iter::first(), fourbyte_hash256(), hash, and raw_encode().
Referenced by encode(), and encodeWithCheck().
     {
         typedef typename std::iterator_traits<InputIt>::value_type value_type;
         std::vector <typename std::remove_const <value_type>::type> v;
         std::size_t const size (std::distance (first, last));
         if (withCheck)
         {
             v.reserve (size + 1 + 4);
             v.insert (v.begin(), first, last);
             unsigned char hash [4];
             fourbyte_hash256 (hash, &v.front(), v.size());
             v.resize (0);
             // Place the hash reversed in the front
             std::copy (std::reverse_iterator <unsigned char const*> (hash+4),
                        std::reverse_iterator <unsigned char const*> (hash),
                        std::back_inserter (v));
         }
         else
         {
             v.reserve (size + 1);
         }
         // Append input little endian
         std::copy (std::reverse_iterator <InputIt> (last),
                    std::reverse_iterator <InputIt> (first),
                    std::back_inserter (v));
         // Pad zero to make the BIGNUM positive
         v.push_back (0);
         return raw_encode (&v.front(), &v.back()+1, alphabet, withCheck);
     }
template<class Container > static std::string ripple::Base58::encode (Container const & container) inline static
Definition at line 124 of file Base58.h.
References encode(), and getCurrentAlphabet().
     {
         return encode (container.container.begin(), container.end(),
             getCurrentAlphabet(), false);
     }
static std::string ripple::Base58::encode (const unsigned char * pbegin, const unsigned char * pend) inline static
Definition at line 137 of file Base58.h.
References encode(), and getCurrentAlphabet().
     {
         return encode (pbegin, pend, getCurrentAlphabet(), false);
     }
template<class Container > static std::string ripple::Base58::encodeWithCheck (Container const & container) inline static
Definition at line 131 of file Base58.h.
References encode(), and getCurrentAlphabet().
Referenced by ripple::CBase58Data::ToString().
     {
         return encode (&container.front(), &container.back()+1,
             getCurrentAlphabet(), true);
     }
void ripple::Base58::fourbyte_hash256 (void * out, void const * in, std::size_t bytes) static
Definition at line 29 of file Base58.cpp.
References ripple::base_uint< BITS >::begin(), hash, and ripple::SHA256Hash().
Referenced by encode(), and raw_decode().
 {
     unsigned char const* const p (
         static_cast <unsigned char const*>(in));
     uint256 hash (SHA256Hash (p, p + bytes));
     memcpy (out, hash.begin(), 4);
 }
Base58::Alphabet const & ripple::Base58::getBitcoinAlphabet () static
Definition at line 37 of file Base58.cpp.
Referenced by ripple::RPC::accountFromString().
 {
     static Alphabet alphabet (
         "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"
         );
     return alphabet;
 }
Base58::Alphabet const & ripple::Base58::getCurrentAlphabet () static
Definition at line 91 of file Base58.cpp.
References s_currentAlphabet.
Referenced by encode(), and encodeWithCheck().
 {
     return *s_currentAlphabet;
 }
Base58::Alphabet const & ripple::Base58::getRippleAlphabet () static
Definition at line 45 of file Base58.cpp.
Referenced by ripple::CryptoIdentifier< 33, 35, true >::from_string(), ripple::RippleAccountIDTraits::to_string(), and ripple::CryptoIdentifier< 33, 35, true >::to_string().
 {
     static Alphabet alphabet (
         "rpshnaf39wBUDNEGHJKLM4PQRST7VWXYZ2bcdeCg65jkm8oFqi1tuvAxyz"
         );
     return alphabet;
 }
bool ripple::Base58::raw_decode (char const * first, char const * last, void * dest, std::size_t size, bool checked, Alphabet const & alphabet) static
Definition at line 103 of file Base58.cpp.
References fourbyte_hash256(), ripple::Base58::Alphabet::from_char(), ripple::CBigNum::getvch(), and ripple::CBigNum::setuint().
Referenced by ripple::CryptoIdentifier< 33, 35, true >::from_string().
 {
     CAutoBN_CTX pctx;
     CBigNum bn58 = 58;
     CBigNum bn = 0;
     CBigNum bnChar;
     // Convert big endian string to bignum
     for (char const* p = first; p != last; ++p)
     {
         int i (alphabet.from_char (*p));
         if (i == -1)
             return false;
         bnChar.setuint ((unsigned int) i);
         int const success (BN_mul (&bn, &bn, &bn58, pctx));
         assert (success);
         bn += bnChar;
     }
     // Get bignum as little endian data
     Blob vchTmp = bn.getvch ();
     // Trim off sign byte if present
     if (vchTmp.size () >= 2 && vchTmp.end ()[-1] == 0 && vchTmp.end ()[-2] >= 0x80)
         vchTmp.erase (vchTmp.end () - 1);
     char* const out (static_cast <char*> (dest));
     // Count leading zeros
     int nLeadingZeros = 0;
     for (char const* p = first; p!=last && *p==alphabet[0]; p++)
         nLeadingZeros++;
     // Verify that the size is correct
     if (vchTmp.size() + nLeadingZeros != size)
         return false;
     // Fill the leading zeros
     memset (out, 0, nLeadingZeros);
     // Copy little endian data to big endian
     std::reverse_copy (vchTmp.begin (), vchTmp.end (),
         out + nLeadingZeros);
     if (checked)
     {
         char hash4 [4];
         fourbyte_hash256 (hash4, out, size - 4);
         if (memcmp (hash4, out + size - 4, 4) != 0)
             return false;
     }
     return true;
 }
std::string ripple::Base58::raw_encode (unsigned char const * begin, unsigned char const * end, Alphabet const & alphabet, bool withCheck) static
Definition at line 53 of file Base58.cpp.
References ripple::CBigNum::getuint().
Referenced by encode(), ripple::RippleAccountIDTraits::to_string(), and ripple::CryptoIdentifier< 33, 35, true >::to_string().
 {
     CAutoBN_CTX pctx;
     CBigNum bn58 = 58;
     CBigNum bn0 = 0;
     // Convert little endian data to bignum
     CBigNum bn (begin, end);
     std::size_t const size (std::distance (begin, end));
     // Convert bignum to std::string
     std::string str;
     // Expected size increase from base58 conversion is approximately 137%
     // use 138% to be safe
     str.reserve (size * 138 / 100 + 1);
     CBigNum dv;
     CBigNum rem;
     while (bn > bn0)
     {
         if (!BN_div (&dv, &rem, &bn, &bn58, pctx))
             throw bignum_error ("EncodeBase58 : BN_div failed");
         bn = dv;
         unsigned int c = rem.getuint ();
         str += alphabet [c];
     }
     for (const unsigned char* p = end-2; p >= begin && *p == 0; p--)
         str += alphabet [0];
     // Convert little endian std::string to big endian
     reverse (str.begin (), str.end ());
     return str;
 }
void ripple::Base58::setCurrentAlphabet (Alphabet const & alphabet) static
Definition at line 96 of file Base58.cpp.
References s_currentAlphabet.
 {
     s_currentAlphabet = &alphabet;
 }
Member Data Documentation
Base58::Alphabet const * ripple::Base58::s_currentAlphabet = &Base58::getRippleAlphabet () static private
Definition at line 155 of file Base58.h.
Referenced by getCurrentAlphabet(), and setCurrentAlphabet().
The documentation for this class was generated from the following files:
rippled/src/ripple/types/api/Base58.h
rippled/src/ripple/types/impl/Base58.cpp