rippled: ripple::AccountState Class Reference
ripple::AccountState Class Reference
#include <AccountState.h>
Public Types
typedef boost::shared_ptr
< AccountState > pointer
Public Member Functions
AccountState (RippleAddress const &naAccountID)
AccountState (SLE::ref ledgerEntry, RippleAddress const &naAccountI)
bool haveAuthorizedKey ()
RippleAddress getAuthorizedKey ()
STAmount getBalance () const
std::uint32_t getSeq () const
SerializedLedgerEntry::pointer getSLE ()
SerializedLedgerEntry const & peekSLE () const
SerializedLedgerEntry & peekSLE ()
Blob getRaw () const
void addJson (Json::Value &value)
void dump ()
Static Public Member Functions
static std::string createGravatarUrl (uint128 uEmailHash)
Private Attributes
RippleAddress const mAccountID
RippleAddress mAuthorizedKey
SerializedLedgerEntry::pointer mLedgerEntry
bool mValid
Detailed Description
Definition at line 29 of file AccountState.h.
Member Typedef Documentation
typedef boost::shared_ptr<AccountState> ripple::AccountState::pointer
Definition at line 32 of file AccountState.h.
Constructor & Destructor Documentation
ripple::AccountState::AccountState (RippleAddress const & naAccountID) explicit
Definition at line 22 of file AccountState.cpp.
References ripple::RippleAddress::getAccountID(), ripple::Ledger::getAccountRootIndex(), ripple::RippleAddress::isValid(), ripple::ltACCOUNT_ROOT, mLedgerEntry, and mValid.
     : mAccountID (naAccountID)
     , mValid (false)
 {
     if (naAccountID.isValid ())
     {
         mValid = true;
         mLedgerEntry = boost::make_shared <SerializedLedgerEntry> (
                            ltACCOUNT_ROOT, Ledger::getAccountRootIndex (naAccountID));
         mLedgerEntry->setFieldAccount (sfAccount, naAccountID.getAccountID ());
     }
 }
ripple::AccountState::AccountState (SLE::ref ledgerEntry, RippleAddress const & naAccountI)
Definition at line 37 of file AccountState.cpp.
References ripple::ltACCOUNT_ROOT, mLedgerEntry, and mValid.
                                                                                 :
     mAccountID (naAccountID), mLedgerEntry (ledgerEntry), mValid (false)
 {
     if (!mLedgerEntry)
         return;
     if (mLedgerEntry->getType () != ltACCOUNT_ROOT)
         return;
     mValid = true;
 }
Member Function Documentation
void ripple::AccountState::addJson (Json::Value & value)
Definition at line 62 of file AccountState.cpp.
References createGravatarUrl(), mLedgerEntry, and mValid.
Referenced by dump().
 {
     val = mLedgerEntry->getJson (0);
     if (mValid)
     {
         if (mLedgerEntry->isFieldPresent (sfEmailHash))
             val["urlgravatar"]  = createGravatarUrl (mLedgerEntry->getFieldH128 (sfEmailHash));
     }
     else
     {
         val["Invalid"] = true;
     }
 }
std::string ripple::AccountState::createGravatarUrl (uint128 uEmailHash) static
Definition at line 51 of file AccountState.cpp.
References ripple::base_uint< BITS >::begin(), ripple::base_uint< BITS >::end(), and ripple::strHex().
Referenced by addJson().
 {
     Blob    vucMD5 (uEmailHash.begin (), uEmailHash.end ());
     std::string                 strMD5Lower = strHex (vucMD5);
     boost::to_lower (strMD5Lower);
     // VFALCO TODO Give a name and move this constant to a more visible location.
     //             Also shouldn't this be https?
     return str (boost::format ("http://www.gravatar.com/avatar/%s") % strMD5Lower);
 }
void ripple::AccountState::dump ()
Definition at line 77 of file AccountState.cpp.
References addJson(), rocksdb::Log(), ripple::lsINFO, and Json::objectValue.
 {
     Json::Value j (Json::objectValue);
     addJson (j);
     Log (lsINFO) << j;
 }
RippleAddress ripple::AccountState::getAuthorizedKey () inline
Definition at line 46 of file AccountState.h.
References mLedgerEntry.
     {
         return mLedgerEntry->getFieldAccount (sfRegularKey);
     }
STAmount ripple::AccountState::getBalance () const inline
Definition at line 51 of file AccountState.h.
References mLedgerEntry.
     {
         return mLedgerEntry->getFieldAmount (sfBalance);
     }
Blob ripple::AccountState::getRaw () const
std::uint32_t ripple::AccountState::getSeq () const inline
Definition at line 56 of file AccountState.h.
References mLedgerEntry.
     {
         return mLedgerEntry->getFieldU32 (sfSequence);
     }
SerializedLedgerEntry::pointer ripple::AccountState::getSLE () inline
Definition at line 61 of file AccountState.h.
References mLedgerEntry.
     {
         return mLedgerEntry;
     }
bool ripple::AccountState::haveAuthorizedKey () inline
Definition at line 41 of file AccountState.h.
References mLedgerEntry.
     {
         return mLedgerEntry->isFieldPresent (sfRegularKey);
     }
SerializedLedgerEntry const& ripple::AccountState::peekSLE () const inline
Definition at line 66 of file AccountState.h.
References mLedgerEntry.
     {
         return *mLedgerEntry;
     }
SerializedLedgerEntry& ripple::AccountState::peekSLE () inline
Definition at line 71 of file AccountState.h.
References mLedgerEntry.
     {
         return *mLedgerEntry;
     }
Member Data Documentation
RippleAddress const ripple::AccountState::mAccountID private
Definition at line 85 of file AccountState.h.
RippleAddress ripple::AccountState::mAuthorizedKey private
Definition at line 86 of file AccountState.h.
SerializedLedgerEntry::pointer ripple::AccountState::mLedgerEntry private
Definition at line 87 of file AccountState.h.
Referenced by AccountState(), addJson(), getAuthorizedKey(), getBalance(), getSeq(), getSLE(), haveAuthorizedKey(), and peekSLE().
bool ripple::AccountState::mValid private
Definition at line 89 of file AccountState.h.
Referenced by AccountState(), and addJson().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/misc/AccountState.h
rippled/src/ripple_app/misc/AccountState.cpp