rippled: ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex > Class Template Reference
ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex > Class Template Reference
#include <TaggedCache.h>
Classes
class Entry
struct Stats
Public Types
typedef Mutex mutex_type
typedef std::unique_lock
< mutex_type > ScopedLockType
typedef std::lock_guard
< mutex_type > lock_guard
typedef Key key_type
typedef T mapped_type
typedef boost::weak_ptr
< mapped_type > weak_mapped_ptr
typedef boost::shared_ptr
< mapped_type > mapped_ptr
typedef beast::abstract_clock
< std::chrono::seconds > clock_type
Public Member Functions
TaggedCache (std::string const &name, int size, clock_type::rep expiration_seconds, clock_type &clock, beast::Journal journal, beast::insight::Collector::ptr const &collector=beast::insight::NullCollector::New())
clock_type & clock ()
int getTargetSize () const
void setTargetSize (int s)
clock_type::rep getTargetAge () const
void setTargetAge (clock_type::rep s)
int getCacheSize ()
int getTrackSize ()
float getHitRate ()
void clearStats ()
void clear ()
void sweep ()
bool del (const key_type &key, bool valid)
bool canonicalize (const key_type &key, boost::shared_ptr< T > &data, bool replace=false)
boost::shared_ptr< T > fetch (const key_type &key)
bool insert (key_type const &key, T const &value)
bool retrieve (const key_type &key, T &data)
bool refreshIfPresent (const key_type &key)
mutex_type & peekMutex ()
Private Types
typedef std::pair< key_type,
Entry > cache_pair
typedef ripple::unordered_map
< key_type, Entry, Hash,
KeyEqual > cache_type
typedef cache_type::iterator cache_iterator
Private Member Functions
void collect_metrics ()
Private Attributes
beast::Journal m_journal
clock_type & m_clock
Stats m_stats
mutex_type m_mutex
std::string m_name
int m_target_size
clock_type::duration m_target_age
int m_cache_count
cache_type m_cache
std::uint64_t m_hits
std::uint64_t m_misses
Detailed Description
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex>
class ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >
Map/cache combination. This class implements a cache and a map. The cache keeps objects alive in the map. The map allows multiple code paths that reference objects with the same tag to get the same actual object.
So long as data is in the cache, it will stay in memory. If it stays in memory even after it is ejected from the cache, the map will track it.
Note
Callers must not modify data objects that are stored in the cache unless they hold their own lock over all cache operations.
Definition at line 61 of file TaggedCache.h.
Member Typedef Documentation
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> typedef cache_type::iterator ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::cache_iterator private
Definition at line 533 of file TaggedCache.h.
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> typedef std::pair<key_type, Entry> ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::cache_pair private
Definition at line 531 of file TaggedCache.h.
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> typedef ripple::unordered_map<key_type, Entry, Hash, KeyEqual> ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::cache_type private
Definition at line 532 of file TaggedCache.h.
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> typedef beast::abstract_clock<std::chrono::seconds> ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::clock_type
Definition at line 73 of file TaggedCache.h.
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> typedef Key ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::key_type
Definition at line 68 of file TaggedCache.h.
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> typedef std::lock_guard<mutex_type> ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::lock_guard
Definition at line 67 of file TaggedCache.h.
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> typedef boost::shared_ptr<mapped_type> ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::mapped_ptr
Definition at line 72 of file TaggedCache.h.
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> typedef T ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::mapped_type
Definition at line 69 of file TaggedCache.h.
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> typedef Mutex ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::mutex_type
Definition at line 64 of file TaggedCache.h.
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> typedef std::unique_lock<mutex_type> ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::ScopedLockType
Definition at line 66 of file TaggedCache.h.
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> typedef boost::weak_ptr<mapped_type> ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::weak_mapped_ptr
Definition at line 71 of file TaggedCache.h.
Constructor & Destructor Documentation
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::TaggedCache (std::string const & name, int size, clock_type::rep expiration_seconds, clock_type & clock, beast::Journal journal, beast::insight::Collector::ptr const & collector = beast::insight::NullCollector::New ()) inline
Definition at line 77 of file TaggedCache.h.
         : m_journal (journal)
         , m_clock (clock)
         , m_stats (name,
             std::bind (&TaggedCache::collect_metrics, this),
                 collector)
         , m_name (name)
         , m_target_size (size)
         , m_target_age (std::chrono::seconds (expiration_seconds))
         , m_cache_count (0)
         , m_hits (0)
         , m_misses (0)
     {
     }
Member Function Documentation
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> bool ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::canonicalize (const key_type & key, boost::shared_ptr< T > & data, bool replace = false) inline
Replace aliased objects with originals.
Due to concurrency it is possible for two separate objects with the same content and referring to the same unique "thing" to exist. This routine eliminates the duplicate and performs a replacement on the callers shared pointer if needed.
Parameters
key The key corresponding to the object
data A shared pointer to the data corresponding to the object.
replace true if data is the up to date version of the object.
Returns
true If the key already existed.
Definition at line 296 of file TaggedCache.h.
Referenced by ripple::NetworkOPsImp::addFetchPack(), ripple::LedgerHistory::addLedger(), ripple::LedgerHistory::builtLedger(), ripple::ValidationsImp::findCreateSet(), ripple::LedgerHistory::getLedgerByHash(), ripple::LedgerHistory::getLedgerBySeq(), ripple::Ledger::getSLEi(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::insert(), and ripple::LedgerHistory::validatedLedger().
     {
         // Return canonical value, store if needed, refresh in cache
         // Return values: true=we had the data already
         lock_guard lock (m_mutex);
         cache_iterator cit = m_cache.find (key);
         if (cit == m_cache.end ())
         {
             m_cache.insert (cache_pair (key, Entry (m_clock.now(), data)));
             ++m_cache_count;
             return false;
         }
         Entry& entry = cit->second;
         entry.touch (m_clock.now());
         if (entry.isCached ())
         {
             if (replace)
             {
                 entry.ptr = data;
                 entry.weak_ptr = data;
             }
             else
             {
                 data = entry.ptr;
             }
             return true;
         }
         mapped_ptr cachedData = entry.lock ();
         if (cachedData)
         {
             if (replace)
             {
                 entry.ptr = data;
                 entry.weak_ptr = data;
             }
             else
             {
                 entry.ptr = cachedData;
                 data = cachedData;
             }
             ++m_cache_count;
             return true;
         }
         entry.ptr = data;
         entry.weak_ptr = data;
         ++m_cache_count;
         return false;
     }
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> void ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::clear () inline
Definition at line 158 of file TaggedCache.h.
     {
         lock_guard lock (m_mutex);
         m_cache.clear ();
         m_cache_count = 0;
     }
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> void ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::clearStats () inline
Definition at line 151 of file TaggedCache.h.
     {
         lock_guard lock (m_mutex);
         m_hits = 0;
         m_misses = 0;
     }
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> clock_type& ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::clock () inline
Return the clock associated with the cache.
Definition at line 96 of file TaggedCache.h.
     {
         return m_clock;
     }
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> void ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::collect_metrics () inline private
Definition at line 477 of file TaggedCache.h.
     {
         m_stats.size.set (getCacheSize ());
         {
             beast::insight::Gauge::value_type hit_rate (0);
             {
                 lock_guard lock (m_mutex);
                 auto const total (m_hits + m_misses);
                 if (total != 0)
                     hit_rate = (m_hits * 100) / total;
             }
             m_stats.hit_rate.set (hit_rate);
         }
     }
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> bool ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::del (const key_type & key, bool valid) inline
Definition at line 256 of file TaggedCache.h.
Referenced by ripple::NetworkOPsImp::getFetchPack().
     {
         // Remove from cache, if !valid, remove from map too. Returns true if removed from cache
         lock_guard lock (m_mutex);
         cache_iterator cit = m_cache.find (key);
         if (cit == m_cache.end ())
             return false;
         Entry& entry = cit->second;
         bool ret = false;
         if (entry.isCached ())
         {
             --m_cache_count;
             entry.ptr.reset ();
             ret = true;
         }
         if (!valid || entry.isExpired ())
             m_cache.erase (cit);
         return ret;
     }
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> boost::shared_ptr<T> ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::fetch (const key_type & key) inline
Definition at line 355 of file TaggedCache.h.
Referenced by ripple::ValidationsImp::findCreateSet(), ripple::ValidationsImp::findSet(), ripple::LedgerHistory::getLedgerByHash(), ripple::Ledger::getSLEi(), and ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::retrieve().
     {
         // fetch us a shared pointer to the stored data object
         lock_guard lock (m_mutex);
         cache_iterator cit = m_cache.find (key);
         if (cit == m_cache.end ())
         {
             ++m_misses;
             return mapped_ptr ();
         }
         Entry& entry = cit->second;
         entry.touch (m_clock.now());
         if (entry.isCached ())
         {
             ++m_hits;
             return entry.ptr;
         }
         entry.ptr = entry.lock ();
         if (entry.isCached ())
         {
             // independent of cache size, so not counted as a hit
             ++m_cache_count;
             return entry.ptr;
         }
         m_cache.erase (cit);
         ++m_misses;
         return mapped_ptr ();
     }
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> int ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::getCacheSize () inline
Definition at line 133 of file TaggedCache.h.
Referenced by ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::collect_metrics(), ripple::NetworkOPsImp::getFetchSize(), and ripple::NetworkOPsImp::getServerInfo().
     {
         lock_guard lock (m_mutex);
         return m_cache_count;
     }
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> float ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::getHitRate () inline
Definition at line 145 of file TaggedCache.h.
Referenced by ripple::RPCHandler::doGetCounts(), and ripple::LedgerHistory::getCacheHitRate().
     {
         lock_guard lock (m_mutex);
         return (static_cast<float> (m_hits) * 100) / (1.0f + m_hits + m_misses);
     }
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> clock_type::rep ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::getTargetAge () const inline
Definition at line 119 of file TaggedCache.h.
     {
         lock_guard lock (m_mutex);
         return m_target_age.count();
     }
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> int ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::getTargetSize () const inline
Definition at line 101 of file TaggedCache.h.
     {
         lock_guard lock (m_mutex);
         return m_target_size;
     }
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> int ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::getTrackSize () inline
Definition at line 139 of file TaggedCache.h.
     {
         lock_guard lock (m_mutex);
         return m_cache.size ();
     }
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> bool ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::insert (key_type const & key, T const & value) inline
Insert the element into the container. If the key already exists, nothing happens.
Returns
true If the element was inserted
Definition at line 395 of file TaggedCache.h.
Referenced by ripple::ConsensusTransSetSF::gotNode().
     {
         mapped_ptr p (boost::make_shared <T> (
             std::cref (value)));
         return canonicalize (key, p);
     }
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> mutex_type& ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::peekMutex () inline
Definition at line 471 of file TaggedCache.h.
Referenced by ripple::LedgerHistory::addLedger(), ripple::LedgerHistory::builtLedger(), ripple::LedgerHistory::fixIndex(), ripple::LedgerHistory::getLedgerBySeq(), ripple::LedgerHistory::getLedgerHash(), and ripple::LedgerHistory::validatedLedger().
     {
         return m_mutex;
     }
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> bool ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::refreshIfPresent (const key_type & key) inline
Refresh the expiration time on a key.
Parameters
key The key to refresh.
Returns
true if the key was found and the object is cached.
Definition at line 424 of file TaggedCache.h.
     {
         bool found = false;
         // If present, make current in cache
         lock_guard lock (m_mutex);
         cache_iterator cit = m_cache.find (key);
         if (cit != m_cache.end ())
         {
             Entry& entry = cit->second;
             if (! entry.isCached ())
             {
                 // Convert weak to strong.
                 entry.ptr = entry.lock ();
                 if (entry.isCached ())
                 {
                     // We just put the object back in cache
                     ++m_cache_count;
                     entry.touch (m_clock.now());
                     found = true;
                 }
                 else
                 {
                     // Couldn't get strong pointer,
                     // object fell out of the cache so remove the entry.
                     m_cache.erase (cit);
                 }
             }
             else
             {
                 // It's cached so update the timer
                 entry.touch (m_clock.now());
                 found = true;
             }
         }
         else
         {
             // not present
         }
         return found;
     }
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> bool ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::retrieve (const key_type & key, T & data) inline
Definition at line 407 of file TaggedCache.h.
Referenced by ripple::NetworkOPsImp::getFetchPack(), and ripple::ConsensusTransSetSF::haveNode().
     {
         // retrieve the value of the stored data
         mapped_ptr entry = fetch (key);
         if (!entry)
             return false;
         data = *entry;
         return true;
     }
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> void ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::setTargetAge (clock_type::rep s) inline
Definition at line 125 of file TaggedCache.h.
Referenced by ripple::ApplicationImp::setup(), ripple::LedgerHistory::tune(), and ripple::ValidationsImp::tune().
     {
         lock_guard lock (m_mutex);
         m_target_age = std::chrono::seconds (s);
         if (m_journal.debug) m_journal.debug <<
             m_name << " target age set to " << m_target_age;
     }
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> void ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::setTargetSize (int s) inline
Definition at line 107 of file TaggedCache.h.
Referenced by ripple::ApplicationImp::setup(), ripple::LedgerHistory::tune(), and ripple::ValidationsImp::tune().
     {
         lock_guard lock (m_mutex);
         m_target_size = s;
         if (s > 0)
             m_cache.rehash (static_cast<std::size_t> ((s + (s >> 2)) / m_cache.max_load_factor () + 1));
         if (m_journal.debug) m_journal.debug <<
             m_name << " target size set to " << s;
     }
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> void ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::sweep () inline
Definition at line 165 of file TaggedCache.h.
Referenced by ripple::LedgerHistory::sweep(), ripple::ValidationsImp::sweep(), and ripple::NetworkOPsImp::sweepFetchPack().
     {
         int cacheRemovals = 0;
         int mapRemovals = 0;
         int cc = 0;
         // Keep references to all the stuff we sweep
         // so that we can destroy them outside the lock.
         //
         std::vector <mapped_ptr> stuffToSweep;
         {
             clock_type::time_point const now (m_clock.now());
             clock_type::time_point when_expire;
             lock_guard lock (m_mutex);
             if (m_target_size == 0 ||
                 (static_cast<int> (m_cache.size ()) <= m_target_size))
             {
                 when_expire = now - m_target_age;
             }
             else
             {
                 when_expire = now - clock_type::duration (
                     m_target_age.count() * m_target_size / m_cache.size ());
                 clock_type::duration const minimumAge (
                     std::chrono::seconds (1));
                 if (when_expire > (now - minimumAge))
                     when_expire = now - minimumAge;
                 if (m_journal.trace) m_journal.trace <<
                     m_name << " is growing fast " << m_cache.size () << " of " << m_target_size <<
                         " aging at " << (now - when_expire) << " of " << m_target_age;
             }
             stuffToSweep.reserve (m_cache.size ());
             cache_iterator cit = m_cache.begin ();
             while (cit != m_cache.end ())
             {
                 if (cit->second.isWeak ())
                 {
                     // weak
                     if (cit->second.isExpired ())
                     {
                         ++mapRemovals;
                         cit = m_cache.erase (cit);
                     }
                     else
                     {
                         ++cit;
                     }
                 }
                 else if (cit->second.last_access <= when_expire)
                 {
                     // strong, expired
                     --m_cache_count;
                     ++cacheRemovals;
                     if (cit->second.ptr.unique ())
                     {
                         stuffToSweep.push_back (cit->second.ptr);
                         ++mapRemovals;
                         cit = m_cache.erase (cit);
                     }
                     else
                     {
                         // remains weakly cached
                         cit->second.ptr.reset ();
                         ++cit;
                     }
                 }
                 else
                 {
                     // strong, not expired
                     ++cc;
                     ++cit;
                 }
             }
         }
         if (m_journal.trace && (mapRemovals || cacheRemovals)) m_journal.trace <<
             m_name << ": cache = " << m_cache.size () << "-" << cacheRemovals <<
                 ", map-=" << mapRemovals;
         // At this point stuffToSweep will go out of scope outside the lock
         // and decrement the reference count on each strong pointer.
     }
Member Data Documentation
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> cache_type ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::m_cache private
Definition at line 552 of file TaggedCache.h.
Referenced by ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::canonicalize(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::clear(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::del(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::fetch(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::getTrackSize(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::refreshIfPresent(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::setTargetSize(), and ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::sweep().
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> int ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::m_cache_count private
Definition at line 551 of file TaggedCache.h.
Referenced by ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::canonicalize(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::clear(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::del(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::fetch(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::getCacheSize(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::refreshIfPresent(), and ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::sweep().
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> clock_type& ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::m_clock private
Definition at line 536 of file TaggedCache.h.
Referenced by ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::canonicalize(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::clock(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::fetch(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::refreshIfPresent(), and ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::sweep().
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> std::uint64_t ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::m_hits private
Definition at line 553 of file TaggedCache.h.
Referenced by ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::clearStats(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::collect_metrics(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::fetch(), and ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::getHitRate().
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> beast::Journal ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::m_journal private
Definition at line 535 of file TaggedCache.h.
Referenced by ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::setTargetAge(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::setTargetSize(), and ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::sweep().
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> std::uint64_t ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::m_misses private
Definition at line 554 of file TaggedCache.h.
Referenced by ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::clearStats(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::collect_metrics(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::fetch(), and ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::getHitRate().
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> mutex_type ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::m_mutex mutable private
Definition at line 539 of file TaggedCache.h.
Referenced by ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::canonicalize(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::clear(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::clearStats(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::collect_metrics(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::del(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::fetch(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::getCacheSize(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::getHitRate(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::getTargetAge(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::getTargetSize(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::getTrackSize(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::peekMutex(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::refreshIfPresent(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::setTargetAge(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::setTargetSize(), and ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::sweep().
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> std::string ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::m_name private
Definition at line 542 of file TaggedCache.h.
Referenced by ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::setTargetAge(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::setTargetSize(), and ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::sweep().
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> Stats ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::m_stats private
Definition at line 537 of file TaggedCache.h.
Referenced by ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::collect_metrics().
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> clock_type::duration ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::m_target_age private
Definition at line 548 of file TaggedCache.h.
Referenced by ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::getTargetAge(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::setTargetAge(), and ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::sweep().
template<class Key, class T, class Hash = beast::hardened_hash <Key>, class KeyEqual = std::equal_to <Key>, class Mutex = std::recursive_mutex> int ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::m_target_size private
Definition at line 545 of file TaggedCache.h.
Referenced by ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::getTargetSize(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::setTargetSize(), and ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::sweep().
The documentation for this class was generated from the following file:
rippled/src/ripple/common/TaggedCache.h