rippled: ripple::UptimeTimer Class Reference
ripple::UptimeTimer Class Reference
#include <UptimeTimer.h>
Public Member Functions
int getElapsedSeconds () const
void beginManualUpdates ()
void endManualUpdates ()
void incrementElapsedTime ()
Static Public Member Functions
static UptimeTimer & getInstance ()
Private Member Functions
UptimeTimer ()
~UptimeTimer ()
Private Attributes
int volatile m_elapsedTime
time_t m_startTime
bool m_isUpdatingManually
Detailed Description
Tracks program uptime.
The timer can be switched to a manual system of updating, to reduce system calls. (?)
Definition at line 31 of file UptimeTimer.h.
Constructor & Destructor Documentation
ripple::UptimeTimer::UptimeTimer () private
Definition at line 22 of file UptimeTimer.cpp.
     : m_elapsedTime (0)
     , m_startTime (::time (0))
     , m_isUpdatingManually (false)
 {
 }
ripple::UptimeTimer::~UptimeTimer () private
Definition at line 29 of file UptimeTimer.cpp.
 {
 }
Member Function Documentation
void ripple::UptimeTimer::beginManualUpdates ()
Definition at line 51 of file UptimeTimer.cpp.
References m_isUpdatingManually.
Referenced by ripple::LoadManagerImp::LoadManagerImp().
 {
     //assert (!m_isUpdatingManually);
     m_isUpdatingManually = true;
 }
void ripple::UptimeTimer::endManualUpdates ()
Definition at line 58 of file UptimeTimer.cpp.
References m_isUpdatingManually.
Referenced by ripple::LoadManagerImp::~LoadManagerImp().
 {
     //assert (m_isUpdatingManually);
     m_isUpdatingManually = false;
 }
int ripple::UptimeTimer::getElapsedSeconds () const
Definition at line 33 of file UptimeTimer.cpp.
References m_elapsedTime, m_isUpdatingManually, m_startTime, and beast::memoryBarrier().
Referenced by ripple::RPCHandler::doGetCounts(), ripple::HashRouter::findCreateEntry(), ripple::UptimeTimerAdapter::getElapsedSeconds(), ripple::LoadManagerImp::resetDeadlockDetector(), ripple::LoadManagerImp::run(), and ripple::LoadMonitor::update().
 {
     int result;
     if (m_isUpdatingManually)
     {
         beast::memoryBarrier();
         result = m_elapsedTime;
     }
     else
     {
         // VFALCO TODO use time_t instead of int return
         result = static_cast <int> (::time (0) - m_startTime);
     }
     return result;
 }
UptimeTimer & ripple::UptimeTimer::getInstance (void) static
Definition at line 71 of file UptimeTimer.cpp.
References instance.
Referenced by ripple::PeerImp::doFetchPack(), ripple::RPCHandler::doGetCounts(), ripple::HashRouter::findCreateEntry(), ripple::UptimeTimerAdapter::getElapsedSeconds(), ripple::LoadManagerImp::LoadManagerImp(), ripple::NetworkOPsImp::makeFetchPack(), ripple::LoadManagerImp::resetDeadlockDetector(), ripple::LoadManagerImp::run(), ripple::LoadMonitor::update(), and ripple::LoadManagerImp::~LoadManagerImp().
 {
     static UptimeTimer instance;
     return instance;
 }
void ripple::UptimeTimer::incrementElapsedTime ()
Definition at line 65 of file UptimeTimer.cpp.
References m_elapsedTime.
Referenced by ripple::LoadManagerImp::run().
 {
     //assert (m_isUpdatingManually);
     ++m_elapsedTime;
 }
Member Data Documentation
int volatile ripple::UptimeTimer::m_elapsedTime private
Definition at line 49 of file UptimeTimer.h.
Referenced by getElapsedSeconds(), and incrementElapsedTime().
bool ripple::UptimeTimer::m_isUpdatingManually private
Definition at line 53 of file UptimeTimer.h.
Referenced by beginManualUpdates(), endManualUpdates(), and getElapsedSeconds().
time_t ripple::UptimeTimer::m_startTime private
Definition at line 51 of file UptimeTimer.h.
Referenced by getElapsedSeconds().
The documentation for this class was generated from the following files:
rippled/src/ripple_basics/utility/UptimeTimer.h
rippled/src/ripple_basics/utility/UptimeTimer.cpp