rippled: ripple::Resource Namespace Reference
ripple::Resource Namespace Reference
Classes
class Charge
class Consumer
struct Gossip
class Manager
struct Entry
struct Import
struct Key
class Logic
class ManagerImp
class Manager_test
Typedefs
typedef beast::abstract_clock
< std::chrono::seconds > clock_type
Enumerations
enum Disposition { ok, warn, drop }
enum Kind { kindInbound, kindOutbound, kindAdmin }
enum {
warningThreshold = 500, dropThreshold = 1500, secondsUntilExpiration = 300, decayWindowSeconds = 32,
minimumGossipBalance = 100, gossipExpirationSeconds = 30
}
Functions
std::ostream & operator<< (std::ostream &os, Charge const &v)
std::ostream & operator<< (std::ostream &os, Consumer const &v)
Charge legacyFee (LoadType t)
std::unique_ptr< Manager > make_Manager (beast::insight::Collector::ptr const &collector, beast::Journal journal)
std::ostream & operator<< (std::ostream &os, Entry const &v)
Charge const feeInvalidRequest (10,"malformed request")
Charge const feeRequestNoReply (1,"unsatisfiable request")
Charge const feeInvalidSignature (100,"invalid signature")
Charge const feeUnwantedData (5,"useless data")
Charge const feeBadProofOfWork (250,"incorrect proof of work")
Charge const feeBadData (20,"invalid data")
Charge const feeInvalidRPC (10,"malformed RPC")
Charge const feeReferenceRPC (2,"reference RPC")
Charge const feeExceptionRPC (10,"exceptioned RPC")
Charge const feeLightRPC (5,"light RPC")
Charge const feeLowBurdenRPC (20,"low RPC")
Charge const feeMediumBurdenRPC (40,"medium RPC")
Charge const feeHighBurdenRPC (300,"heavy RPC")
Charge const feePathFindUpdate (100,"path update")
Charge const feeNewTrustedNote (10,"trusted note")
Charge const feeNewValidTx (10,"valid tx")
Charge const feeSatisfiedRequest (10,"needed data")
Charge const feeRequestedData (50,"costly request")
Charge const feeCheapQuery (10,"trivial query")
Charge const feeWarning (200,"received warning")
Charge const feeDrop (300,"dropped")
BEAST_DEFINE_TESTSUITE (Manager, resource, ripple)
Variables
Charge const feeInvalidRequest
Charge const feeRequestNoReply
Charge const feeInvalidSignature
Charge const feeUnwantedData
Charge const feeBadProofOfWork
Charge const feeBadData
Charge const feeInvalidRPC
Charge const feeReferenceRPC
Charge const feeExceptionRPC
Charge const feeLightRPC
Charge const feeLowBurdenRPC
Charge const feeMediumBurdenRPC
Charge const feeHighBurdenRPC
Charge const feePathFindUpdate
Charge const feeNewTrustedNote
Charge const feeNewValidTx
Charge const feeSatisfiedRequest
Charge const feeRequestedData
Charge const feeCheapQuery
Charge const feeWarning
Charge const feeDrop
Typedef Documentation
typedef beast::abstract_clock<std::chrono::seconds> ripple::Resource::clock_type
Definition at line 26 of file Entry.h.
Enumeration Type Documentation
anonymous enum
Tunable constants.
Enumerator
warningThreshold
dropThreshold
secondsUntilExpiration
decayWindowSeconds
minimumGossipBalance
gossipExpirationSeconds
Definition at line 27 of file Tuning.h.
 {
     // Balance at which a warning is issued
      warningThreshold           = 500
     // Balance at which the consumer is disconnected
     ,dropThreshold              = 1500
     // The number of seconds until an inactive table item is removed
     ,secondsUntilExpiration     = 300
     // The number of seconds in the exponential decay window
     // (This should be a power of two)
     ,decayWindowSeconds         = 32
     // The minimum balance required in order to include a load source in gossip
     ,minimumGossipBalance       = 100
     // Number of seconds until imported gossip expires
     ,gossipExpirationSeconds    = 30
 };
enum ripple::Resource::Disposition
The disposition of a consumer after applying a load charge.
Enumerator
ok
No action required. Consumer should be warned that consumption is high.
warn
Consumer should be disconnected for excess consumption.
drop
Definition at line 27 of file Disposition.h.
 {
     ok
     ,warn
     ,drop
 };
enum ripple::Resource::Kind
Enumerator
kindInbound
kindOutbound
kindAdmin
Definition at line 27 of file Kind.h.
 {
      kindInbound
     ,kindOutbound
     ,kindAdmin
 };
Function Documentation
ripple::Resource::BEAST_DEFINE_TESTSUITE (Manager , resource , ripple)
Charge const ripple::Resource::feeBadData (20 , "invalid data")
Charge const ripple::Resource::feeBadProofOfWork (250 , "incorrect proof of work")
Charge const ripple::Resource::feeCheapQuery (10 , "trivial query")
Charge const ripple::Resource::feeDrop (300 , "dropped")
Charge const ripple::Resource::feeExceptionRPC (10 , "exceptioned RPC")
Charge const ripple::Resource::feeHighBurdenRPC (300 , "heavy RPC")
Charge const ripple::Resource::feeInvalidRequest (10 , "malformed request")
Charge const ripple::Resource::feeInvalidRPC (10 , "malformed RPC")
Charge const ripple::Resource::feeInvalidSignature (100 , "invalid signature")
Charge const ripple::Resource::feeLightRPC (5 , "light RPC")
Charge const ripple::Resource::feeLowBurdenRPC (20 , "low RPC")
Charge const ripple::Resource::feeMediumBurdenRPC (40 , "medium RPC")
Charge const ripple::Resource::feeNewTrustedNote (10 , "trusted note")
Charge const ripple::Resource::feeNewValidTx (10 , "valid tx")
Charge const ripple::Resource::feePathFindUpdate (100 , "path update")
Charge const ripple::Resource::feeReferenceRPC (2 , "reference RPC")
Charge const ripple::Resource::feeRequestedData (50 , "costly request")
Charge const ripple::Resource::feeRequestNoReply (1 , "unsatisfiable request")
Charge const ripple::Resource::feeSatisfiedRequest (10 , "needed data")
Charge const ripple::Resource::feeUnwantedData (5 , "useless data")
Charge const ripple::Resource::feeWarning (200 , "received warning")
Charge ripple::Resource::legacyFee (LoadType t)
Returns an appropriate Charge based on the legacy LoadType.
Definition at line 23 of file LegacyFees.cpp.
References bassertfalse, feeBadData, feeBadProofOfWork, feeCheapQuery, feeExceptionRPC, feeHighBurdenRPC, feeInvalidRequest, feeInvalidRPC, feeInvalidSignature, feeLightRPC, feeLowBurdenRPC, feeMediumBurdenRPC, feeNewTrustedNote, feeNewValidTx, feeReferenceRPC, feeRequestedData, feeRequestNoReply, feeSatisfiedRequest, feeUnwantedData, ripple::LT_BadData, ripple::LT_BadPoW, ripple::LT_CheapQuery, ripple::LT_InvalidRequest, ripple::LT_InvalidSignature, ripple::LT_NeededData, ripple::LT_NewTransaction, ripple::LT_NewTrusted, ripple::LT_RequestData, ripple::LT_RequestNoReply, ripple::LT_RPCException, ripple::LT_RPCInvalid, ripple::LT_RPCReference, and ripple::LT_UnwantedData.
 {
     switch (t)
     {
     case LT_InvalidRequest:     return feeInvalidRequest;
     case LT_RequestNoReply:     return feeRequestNoReply;
     case LT_InvalidSignature:   return feeInvalidSignature;
     case LT_UnwantedData:       return feeUnwantedData;
     case LT_BadPoW:             return feeBadProofOfWork;
     case LT_BadData:            return feeBadData;
     case LT_RPCInvalid:         return feeInvalidRPC;
     case LT_RPCReference:       return feeReferenceRPC;
     case LT_RPCException:       return feeExceptionRPC;
 #if 0
     case LT_RPCLight:           return feeLightRPC;
     case LT_RPCBurdenLow:       return feeLowBurdenRPC;
     case LT_RPCBurdenMedium:    return feeMediumBurdenRPC;
     case LT_RPCBurdenHigh:      return feeHighBurdenRPC;
 #endif
     case LT_NewTrusted:         return feeNewTrustedNote;
     case LT_NewTransaction:     return feeNewValidTx;
     case LT_NeededData:         return feeSatisfiedRequest;
     case LT_RequestData:        return feeRequestedData;
     default:
         bassertfalse;
     case LT_CheapQuery:         return feeCheapQuery;
     };
     return feeInvalidRequest;
 };
std::unique_ptr< Manager > ripple::Resource::make_Manager (beast::insight::Collector::ptr const & collector, beast::Journal journal)
Definition at line 117 of file Manager.cpp.
 {
     return std::make_unique <ManagerImp> (collector, journal);
 }
std::ostream & ripple::Resource::operator<< (std::ostream & os, Charge const & v)
Definition at line 53 of file Charge.cpp.
References ripple::Resource::Charge::to_string().
 {
     os << v.to_string();
     return os;
 }
std::ostream & ripple::Resource::operator<< (std::ostream & os, Consumer const & v)
Definition at line 137 of file Consumer.cpp.
References ripple::Resource::Consumer::to_string().
 {
     os << v.to_string();
     return os;
 }
std::ostream& ripple::Resource::operator<< (std::ostream & os, Entry const & v)
Definition at line 96 of file Entry.h.
References ripple::Resource::Entry::to_string().
 {
     os << v.to_string();
     return os;
 }
Variable Documentation
Charge const ripple::Resource::feeBadData(20,"invalid data")
Referenced by legacyFee().
Charge const ripple::Resource::feeBadProofOfWork(250,"incorrect proof of work")
Referenced by legacyFee(), and ripple::PeerImp::recvProofWork().
Charge const ripple::Resource::feeCheapQuery(10,"trivial query")
Referenced by legacyFee().
Charge const ripple::Resource::feeDrop(300,"dropped")
Referenced by ripple::Resource::Logic::disconnect().
Charge const ripple::Resource::feeExceptionRPC(10,"exceptioned RPC")
Referenced by ripple::RPCHandler::doCommand(), and legacyFee().
Charge const ripple::Resource::feeHighBurdenRPC(300,"heavy RPC")
Referenced by ripple::RPCHandler::doAccountTxOld(), ripple::RPCHandler::doLedger(), ripple::RPCHandler::doPathFind(), ripple::RPCHandler::doRipplePathFind(), ripple::RPCHandler::doSign(), and legacyFee().
Charge const ripple::Resource::feeInvalidRequest(10,"malformed request")
Schedule of fees charged for imposing load on the server.
Referenced by ripple::PeerImp::checkTransaction(), ripple::PeerImp::checkValidation(), ripple::PeerImp::doFetchPack(), ripple::PeerImp::getLedger(), legacyFee(), ripple::InboundLedger::processData(), ripple::PeerImp::recvHaveTxSet(), ripple::PeerImp::recvLedger(), ripple::PeerImp::recvProofWork(), ripple::PeerImp::recvPropose(), and ripple::PeerImp::recvValidation().
Charge const ripple::Resource::feeInvalidRPC(10,"malformed RPC")
Referenced by ripple::WSConnection::invokeCommand(), and legacyFee().
Charge const ripple::Resource::feeInvalidSignature(100,"invalid signature")
Referenced by ripple::PeerImp::checkPropose(), ripple::PeerImp::checkTransaction(), legacyFee(), ripple::PeerImp::recvPropose(), and ripple::PeerImp::recvTransaction().
Charge const ripple::Resource::feeLightRPC(5,"light RPC")
Referenced by legacyFee().
Charge const ripple::Resource::feeLowBurdenRPC(20,"low RPC")
Referenced by legacyFee().
Charge const ripple::Resource::feeMediumBurdenRPC(40,"medium RPC")
Referenced by ripple::RPCHandler::doAccountLines(), ripple::RPCHandler::doAccountOffers(), ripple::RPCHandler::doAccountTx(), ripple::RPCHandler::doBookOffers(), ripple::RPCHandler::doSubmit(), ripple::RPCHandler::doSubscribe(), ripple::RPCHandler::doTxHistory(), and legacyFee().
Charge const ripple::Resource::feeNewTrustedNote(10,"trusted note")
Referenced by legacyFee().
Charge const ripple::Resource::feeNewValidTx(10,"valid tx")
Referenced by legacyFee().
Charge const ripple::Resource::feePathFindUpdate(100,"path update")
Referenced by ripple::PathRequests::updateAll().
Charge const ripple::Resource::feeReferenceRPC(2,"reference RPC")
Referenced by ripple::RPCHandler::doCommand(), ripple::WSConnection::invokeCommand(), legacyFee(), ripple::RPCServerHandler::processRequest(), ripple::RPCHTTPServerImp::processRequest(), and ripple::startServer().
Charge const ripple::Resource::feeRequestedData(50,"costly request")
Referenced by legacyFee().
Charge const ripple::Resource::feeRequestNoReply(1,"unsatisfiable request")
Referenced by ripple::PeerImp::doFetchPack(), and legacyFee().
Charge const ripple::Resource::feeSatisfiedRequest(10,"needed data")
Referenced by legacyFee().
Charge const ripple::Resource::feeUnwantedData(5,"useless data")
Referenced by ripple::PeerImp::checkTransaction(), legacyFee(), ripple::PeerImp::recvCluster(), ripple::PeerImp::recvHaveTxSet(), ripple::PeerImp::recvLedger(), and ripple::PeerImp::recvValidation().
Charge const ripple::Resource::feeWarning(200,"received warning")
Referenced by ripple::Resource::Logic::warn().