rippled: beast::LinkedListPointer< ObjectType > Class Template Reference
beast::LinkedListPointer< ObjectType > Class Template Reference
#include <LinkedListPointer.h>
Classes
class Appender
Public Member Functions
LinkedListPointer () noexcept
LinkedListPointer (ObjectType *const headItem) noexcept
LinkedListPointer & operator= (ObjectType *const newItem) noexcept
operator ObjectType * () const noexcept
ObjectType * get () const noexcept
LinkedListPointer & getLast () noexcept
int size () const noexcept
LinkedListPointer & operator[] (int index) noexcept
const LinkedListPointer & operator[] (int index) const noexcept
bool contains (const ObjectType *const itemToLookFor) const noexcept
void insertNext (ObjectType *const newItem)
void insertAtIndex (int index, ObjectType *newItem)
ObjectType * replaceNext (ObjectType *const newItem) noexcept
void append (ObjectType *const newItem)
void addCopyOfList (const LinkedListPointer &other)
ObjectType * removeNext () noexcept
void remove (ObjectType *const itemToRemove)
void deleteAll ()
LinkedListPointer * findPointerTo (ObjectType *const itemToLookFor) noexcept
void copyToArray (ObjectType **destArray) const noexcept
void swapWith (LinkedListPointer &other) noexcept
Private Attributes
ObjectType * item
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
template<class ObjectType>
class beast::LinkedListPointer< ObjectType >
Helps to manipulate singly-linked lists of objects.
For objects that are designed to contain a pointer to the subsequent item in the list, this class contains methods to deal with the list. To use it, the ObjectType class that it points to must contain a LinkedListPointer called nextListItem, e.g.
struct MyObject
{
    int x, y, z;
    // A linkable object must contain a member with this name and type, which must be
    // accessible by the LinkedListPointer class. (This doesn't mean it has to be public -
    // you could make your class a friend of a LinkedListPointer<MyObject> instead).
    LinkedListPointer<MyObject> nextListItem;
};
LinkedListPointer<MyObject> myList;
myList.append (new MyObject());
myList.append (new MyObject());
int numItems = myList.size(); // returns 2
MyObject* lastInList = myList.getLast();
Definition at line 58 of file LinkedListPointer.h.
Constructor & Destructor Documentation
template<class ObjectType > beast::LinkedListPointer< ObjectType >::LinkedListPointer () inline noexcept
Creates a null pointer to an empty list.
Definition at line 63 of file LinkedListPointer.h.
         : item (nullptr)
     {
     }
template<class ObjectType > beast::LinkedListPointer< ObjectType >::LinkedListPointer (ObjectType *const headItem) inline explicit noexcept
Creates a pointer to a list whose head is the item provided.
Definition at line 69 of file LinkedListPointer.h.
         : item (headItem)
     {
     }
Member Function Documentation
template<class ObjectType > void beast::LinkedListPointer< ObjectType >::addCopyOfList (const LinkedListPointer< ObjectType > & other) inline
Creates copies of all the items in another list and adds them to this one. This will use the ObjectType's copy constructor to try to create copies of each item in the other list, and appends them to this list.
Definition at line 240 of file LinkedListPointer.h.
References beast::LinkedListPointer< ObjectType >::insertNext(), and beast::LinkedListPointer< ObjectType >::item.
     {
         LinkedListPointer* insertPoint = this;
         for (ObjectType* i = other.item; i != nullptr; i = i->nextListItem)
         {
             insertPoint->insertNext (new ObjectType (*i));
             insertPoint = &(insertPoint->item->nextListItem);
         }
     }
template<class ObjectType > void beast::LinkedListPointer< ObjectType >::append (ObjectType *const newItem) inline
Adds an item to the end of the list.
This operation involves iterating the whole list, so can be slow - if you need to append a number of items to your list, it's much more efficient to use the Appender class than to repeatedly call append().
Definition at line 231 of file LinkedListPointer.h.
References beast::LinkedListPointer< ObjectType >::getLast(), and beast::LinkedListPointer< ObjectType >::item.
     {
         getLast().item = newItem;
     }
template<class ObjectType > bool beast::LinkedListPointer< ObjectType >::contains (const ObjectType *const itemToLookFor) const inline noexcept
Returns true if the list contains the given item.
Definition at line 171 of file LinkedListPointer.h.
References beast::LinkedListPointer< ObjectType >::item.
     {
         for (ObjectType* i = item; i != nullptr; i = i->nextListItem)
             if (itemToLookFor == i)
                 return true;
         return false;
     }
template<class ObjectType > void beast::LinkedListPointer< ObjectType >::copyToArray (ObjectType ** destArray) const inline noexcept
Copies the items in the list to an array. The destArray must contain enough elements to hold the entire list - no checks are made for this!
Definition at line 313 of file LinkedListPointer.h.
References bassert, and beast::LinkedListPointer< ObjectType >::item.
     {
         bassert (destArray != nullptr);
         for (ObjectType* i = item; i != nullptr; i = i->nextListItem)
             *destArray++ = i;
     }
template<class ObjectType > void beast::LinkedListPointer< ObjectType >::deleteAll () inline
Iterates the list, calling the delete operator on all of its elements and leaving this pointer empty.
Definition at line 280 of file LinkedListPointer.h.
References beast::LinkedListPointer< ObjectType >::item.
     {
         while (item != nullptr)
         {
             ObjectType* const oldItem = item;
             item = oldItem->nextListItem;
             delete oldItem;
         }
     }
template<class ObjectType > LinkedListPointer* beast::LinkedListPointer< ObjectType >::findPointerTo (ObjectType *const itemToLookFor) inline noexcept
Finds a pointer to a given item. If the item is found in the list, this returns the pointer that points to it. If the item isn't found, this returns null.
Definition at line 294 of file LinkedListPointer.h.
References beast::LinkedListPointer< ObjectType >::item.
Referenced by beast::LinkedListPointer< ObjectType >::remove().
     {
         LinkedListPointer* l = this;
         while (l->item != nullptr)
         {
             if (l->item == itemToLookFor)
                 return l;
             l = &(l->item->nextListItem);
         }
         return nullptr;
     }
template<class ObjectType > ObjectType* beast::LinkedListPointer< ObjectType >::get () const inline noexcept
Returns the item which this pointer points to.
Definition at line 106 of file LinkedListPointer.h.
References beast::LinkedListPointer< ObjectType >::item.
     {
         return item;
     }
template<class ObjectType > LinkedListPointer& beast::LinkedListPointer< ObjectType >::getLast () inline noexcept
Returns the last item in the list which this pointer points to. This will iterate the list and return the last item found. Obviously the speed of this operation will be proportional to the size of the list. If the list is empty the return value will be this object. If you're planning on appending a number of items to your list, it's much more efficient to use the Appender class than to repeatedly call getLast() to find the end.
Definition at line 118 of file LinkedListPointer.h.
References beast::LinkedListPointer< ObjectType >::item.
Referenced by beast::LinkedListPointer< ObjectType >::append().
     {
         LinkedListPointer* l = this;
         while (l->item != nullptr)
             l = &(l->item->nextListItem);
         return *l;
     }
template<class ObjectType > void beast::LinkedListPointer< ObjectType >::insertAtIndex (int index, ObjectType * newItem) inline
Inserts an item at a numeric index in the list. Obviously this will involve iterating the list to find the item at the given index, so be careful about the impact this may have on execution time.
Definition at line 196 of file LinkedListPointer.h.
References bassert, beast::LinkedListPointer< ObjectType >::insertNext(), and beast::LinkedListPointer< ObjectType >::item.
     {
         bassert (newItem != nullptr);
         LinkedListPointer* l = this;
         while (index != 0 && l->item != nullptr)
         {
             l = &(l->item->nextListItem);
             --index;
         }
         l->insertNext (newItem);
     }
template<class ObjectType > void beast::LinkedListPointer< ObjectType >::insertNext (ObjectType *const newItem) inline
Inserts an item into the list, placing it before the item that this pointer currently points to.
Definition at line 184 of file LinkedListPointer.h.
References bassert, and beast::LinkedListPointer< ObjectType >::item.
Referenced by beast::LinkedListPointer< ObjectType >::addCopyOfList(), and beast::LinkedListPointer< ObjectType >::insertAtIndex().
     {
         bassert (newItem != nullptr);
         bassert (newItem->nextListItem == nullptr);
         newItem->nextListItem = item;
         item = newItem;
     }
template<class ObjectType > beast::LinkedListPointer< ObjectType >::operator ObjectType * () const inline noexcept
Returns the item which this pointer points to.
Definition at line 100 of file LinkedListPointer.h.
References beast::LinkedListPointer< ObjectType >::item.
     {
         return item;
     }
template<class ObjectType > LinkedListPointer& beast::LinkedListPointer< ObjectType >::operator= (ObjectType *const newItem) inline noexcept
Sets this pointer to point to a new list.
Definition at line 75 of file LinkedListPointer.h.
References beast::LinkedListPointer< ObjectType >::item.
     {
         item = newItem;
         return *this;
     }
template<class ObjectType > LinkedListPointer& beast::LinkedListPointer< ObjectType >::operator[] (int index) inline noexcept
Returns the item at a given index in the list. Since the only way to find an item is to iterate the list, this operation can obviously be slow, depending on its size, so you should be careful when using this in algorithms.
Definition at line 146 of file LinkedListPointer.h.
References beast::LinkedListPointer< ObjectType >::item.
     {
         LinkedListPointer* l = this;
         while (--index >= 0 && l->item != nullptr)
             l = &(l->item->nextListItem);
         return *l;
     }
template<class ObjectType > const LinkedListPointer& beast::LinkedListPointer< ObjectType >::operator[] (int index) const inline noexcept
Returns the item at a given index in the list. Since the only way to find an item is to iterate the list, this operation can obviously be slow, depending on its size, so you should be careful when using this in algorithms.
Definition at line 160 of file LinkedListPointer.h.
References beast::LinkedListPointer< ObjectType >::item.
     {
         const LinkedListPointer* l = this;
         while (--index >= 0 && l->item != nullptr)
             l = &(l->item->nextListItem);
         return *l;
     }
template<class ObjectType > void beast::LinkedListPointer< ObjectType >::remove (ObjectType *const itemToRemove) inline
Removes a specific item from the list. Note that this will not delete the item, it simply unlinks it from the list.
Definition at line 271 of file LinkedListPointer.h.
References beast::LinkedListPointer< ObjectType >::findPointerTo().
     {
         if (LinkedListPointer* const l = findPointerTo (itemToRemove))
             l->removeNext();
     }
template<class ObjectType > ObjectType* beast::LinkedListPointer< ObjectType >::removeNext () inline noexcept
Removes the head item from the list. This won't delete the object that is removed, but returns it, so the caller can delete it if necessary.
Definition at line 255 of file LinkedListPointer.h.
References beast::LinkedListPointer< ObjectType >::item.
     {
         ObjectType* const oldItem = item;
         if (oldItem != nullptr)
         {
             item = oldItem->nextListItem;
             oldItem->nextListItem.item = nullptr;
         }
         return oldItem;
     }
template<class ObjectType > ObjectType* beast::LinkedListPointer< ObjectType >::replaceNext (ObjectType *const newItem) inline noexcept
Replaces the object that this pointer points to, appending the rest of the list to the new object, and returning the old one.
Definition at line 213 of file LinkedListPointer.h.
References bassert, and beast::LinkedListPointer< ObjectType >::item.
     {
         bassert (newItem != nullptr);
         bassert (newItem->nextListItem == nullptr);
         ObjectType* const oldItem = item;
         item = newItem;
         item->nextListItem = oldItem->nextListItem.item;
         oldItem->nextListItem.item = nullptr;
         return oldItem;
     }
template<class ObjectType > int beast::LinkedListPointer< ObjectType >::size () const inline noexcept
Returns the number of items in the list. Obviously with a simple linked list, getting the size involves iterating the list, so this can be a lengthy operation - be careful when using this method in your code.
Definition at line 132 of file LinkedListPointer.h.
References beast::LinkedListPointer< ObjectType >::item.
     {
         int total = 0;
         for (ObjectType* i = item; i != nullptr; i = i->nextListItem)
             ++total;
         return total;
     }
template<class ObjectType > void beast::LinkedListPointer< ObjectType >::swapWith (LinkedListPointer< ObjectType > & other) inline noexcept
Swaps this pointer with another one
Definition at line 322 of file LinkedListPointer.h.
References beast::LinkedListPointer< ObjectType >::item, and beast::asio::swap().
     {
         std::swap (item, other.item);
     }
Member Data Documentation
template<class ObjectType > ObjectType* beast::LinkedListPointer< ObjectType >::item private
Definition at line 360 of file LinkedListPointer.h.
Referenced by beast::LinkedListPointer< ObjectType >::addCopyOfList(), beast::LinkedListPointer< ObjectType >::append(), beast::LinkedListPointer< ObjectType >::contains(), beast::LinkedListPointer< ObjectType >::copyToArray(), beast::LinkedListPointer< ObjectType >::deleteAll(), beast::LinkedListPointer< ObjectType >::findPointerTo(), beast::LinkedListPointer< ObjectType >::get(), beast::LinkedListPointer< ObjectType >::getLast(), beast::LinkedListPointer< ObjectType >::insertAtIndex(), beast::LinkedListPointer< ObjectType >::insertNext(), beast::LinkedListPointer< ObjectType >::operator ObjectType *(), beast::LinkedListPointer< ObjectType >::operator=(), beast::LinkedListPointer< ObjectType >::operator[](), beast::LinkedListPointer< ObjectType >::removeNext(), beast::LinkedListPointer< ObjectType >::replaceNext(), beast::LinkedListPointer< ObjectType >::size(), and beast::LinkedListPointer< ObjectType >::swapWith().
The documentation for this class was generated from the following file:
rippled/src/beast/modules/beast_core/containers/LinkedListPointer.h