rippled: ripple::SOTemplate Class Reference
ripple::SOTemplate Class Reference
#include <SerializedObjectTemplate.h>
Public Types
typedef std::unique_ptr
< SOElement const > value_type
typedef std::vector< value_type > list_type
Public Member Functions
SOTemplate ()
list_type const & peek () const
void push_back (SOElement const &r)
int getIndex (SField::ref) const
Private Attributes
list_type mTypes
std::vector< int > mIndex
Detailed Description
Defines the fields and their attributes within a SerializedObject. Each subclass of SerializedObject will provide its own template describing the available fields and their metadata attributes.
Definition at line 59 of file SerializedObjectTemplate.h.
Member Typedef Documentation
typedef std::vector<value_type> ripple::SOTemplate::list_type
Definition at line 63 of file SerializedObjectTemplate.h.
typedef std::unique_ptr<SOElement const> ripple::SOTemplate::value_type
Definition at line 62 of file SerializedObjectTemplate.h.
Constructor & Destructor Documentation
ripple::SOTemplate::SOTemplate ()
Create an empty template. After creating the template, call push_back with the desired fields.
See Also
push_back
Definition at line 22 of file SerializedObjectTemplate.cpp.
 {
 }
Member Function Documentation
int ripple::SOTemplate::getIndex (SField::ref f) const
Retrieve the position of a named field.
Definition at line 55 of file SerializedObjectTemplate.cpp.
References ripple::SField::getNum(), and mIndex.
Referenced by ripple::STObject::getFieldIndex(), ripple::STObject::isFieldAllowed(), and push_back().
 {
     // The mapping table should be large enough for any possible field
     //
     assert (f.getNum () < mIndex.size ());
     return mIndex[f.getNum ()];
 }
list_type const& ripple::SOTemplate::peek () const inline
Definition at line 75 of file SerializedObjectTemplate.h.
References mTypes.
Referenced by ripple::STObject::isValidForType(), ripple::STObject::set(), and ripple::STObject::setType().
     {
         return mTypes;
     }
void ripple::SOTemplate::push_back (SOElement const & r)
Add an element to the template.
Definition at line 26 of file SerializedObjectTemplate.cpp.
References ripple::SOElement::e_field, getIndex(), ripple::SField::getNum(), ripple::SField::getNumFields(), mIndex, and mTypes.
Referenced by ripple::SerializedValidation::getFormat(), ripple::KnownFormats< KeyType >::Item::operator<<(), and ripple::SerializedObject_test::testSerialization().
 {
     // Ensure there is the enough space in the index mapping
     // table for all possible fields.
     //
     if (mIndex.empty ())
     {
         // Unmapped indices will be set to -1
         //
         mIndex.resize (SField::getNumFields () + 1, -1);
     }
     // Make sure the field's index is in range
     //
     assert (r.e_field.getNum () < mIndex.size ());
     // Make sure that this field hasn't already been assigned
     //
     assert (getIndex (r.e_field) == -1);
     // Add the field to the index mapping table
     //
     mIndex [r.e_field.getNum ()] = mTypes.size ();
     // Append the new element.
     //
     mTypes.push_back (value_type (new SOElement (r)));
 }
Member Data Documentation
std::vector<int> ripple::SOTemplate::mIndex private
Definition at line 89 of file SerializedObjectTemplate.h.
Referenced by getIndex(), and push_back().
list_type ripple::SOTemplate::mTypes private
Definition at line 87 of file SerializedObjectTemplate.h.
Referenced by peek(), and push_back().
The documentation for this class was generated from the following files:
rippled/src/ripple_data/protocol/SerializedObjectTemplate.h
rippled/src/ripple_data/protocol/SerializedObjectTemplate.cpp