rippled: rocksdb::SimpleTableDBTest Class Reference
rocksdb::SimpleTableDBTest Class Reference
Public Member Functions
SimpleTableDBTest ()
~SimpleTableDBTest ()
Options CurrentOptions ()
DBImpl * dbfull ()
void Reopen (Options *options=nullptr)
void Close ()
void DestroyAndReopen (Options *options=nullptr)
void Destroy (Options *options)
Status PureReopen (Options *options, DB **db)
Status TryReopen (Options *options=nullptr)
Status Put (const Slice &k, const Slice &v)
Status Delete (const std::string &k)
std::string Get (const std::string &k, const Snapshot *snapshot=nullptr)
int NumTableFilesAtLevel (int level)
std::string FilesPerLevel ()
std::string IterStatus (Iterator *iter)
Public Attributes
std::string dbname_
Env * env_
DB * db_
Options last_options_
Detailed Description
Definition at line 567 of file simple_table_db_test.cc.
Constructor & Destructor Documentation
rocksdb::SimpleTableDBTest::SimpleTableDBTest () inline
Definition at line 576 of file simple_table_db_test.cc.
References ASSERT_OK, db_, dbname_, rocksdb::DestroyDB(), Reopen(), and rocksdb::test::TmpDir().
                       :
       env_(Env::Default()) {
     dbname_ = test::TmpDir() + "/simple_table_db_test";
     ASSERT_OK(DestroyDB(dbname_, Options()));
     db_ = nullptr;
     Reopen();
   }
rocksdb::SimpleTableDBTest::~SimpleTableDBTest () inline
Definition at line 584 of file simple_table_db_test.cc.
References ASSERT_OK, db_, dbname_, and rocksdb::DestroyDB().
{
     delete db_;
     ASSERT_OK(DestroyDB(dbname_, Options()));
   }
Member Function Documentation
void rocksdb::SimpleTableDBTest::Close () inline
Definition at line 604 of file simple_table_db_test.cc.
References db_.
                {
     delete db_;
     db_ = nullptr;
   }
Options rocksdb::SimpleTableDBTest::CurrentOptions () inline
Definition at line 590 of file simple_table_db_test.cc.
References rocksdb::Options::table_factory.
Referenced by TryReopen().
{
     Options options;
     options.table_factory.reset(new SimpleTableFactory());
     return options;
   }
DBImpl* rocksdb::SimpleTableDBTest::dbfull () inline
Definition at line 596 of file simple_table_db_test.cc.
References db_.
                    {
     return reinterpret_cast<DBImpl*>(db_);
   }
Status rocksdb::SimpleTableDBTest::Delete (const std::string & k) inline
Definition at line 644 of file simple_table_db_test.cc.
References db_, and rocksdb::DB::Delete().
{
     return db_->Delete(WriteOptions(), k);
   }
void rocksdb::SimpleTableDBTest::Destroy (Options * options) inline
Definition at line 615 of file simple_table_db_test.cc.
References ASSERT_OK, db_, dbname_, and rocksdb::DestroyDB().
Referenced by DestroyAndReopen().
{
     delete db_;
     db_ = nullptr;
     ASSERT_OK(DestroyDB(dbname_, *options));
   }
void rocksdb::SimpleTableDBTest::DestroyAndReopen (Options * options = nullptr) inline
Definition at line 609 of file simple_table_db_test.cc.
References ASSERT_OK, Destroy(), last_options_, and TryReopen().
{
     //Destroy using last options
     Destroy(&last_options_);
     ASSERT_OK(TryReopen(options));
   }
std::string rocksdb::SimpleTableDBTest::FilesPerLevel () inline
Definition at line 671 of file simple_table_db_test.cc.
References db_, ripple::f, rocksdb::DB::NumberLevels(), and NumTableFilesAtLevel().
{
     std::string result;
     int last_non_zero_offset = 0;
     for (int level = 0; level < db_->NumberLevels(); level++) {
       int f = NumTableFilesAtLevel(level);
       char buf[100];
       snprintf(buf, sizeof(buf), "%s%d", (level ? "," : ""), f);
       result += buf;
       if (f > 0) {
         last_non_zero_offset = result.size();
       }
     }
     result.resize(last_non_zero_offset);
     return result;
   }
std::string rocksdb::SimpleTableDBTest::Get (const std::string & k, const Snapshot * snapshot = nullptr) inline
Definition at line 648 of file simple_table_db_test.cc.
References db_, rocksdb::DB::Get(), rocksdb::Status::IsNotFound(), rocksdb::Status::ok(), rocksdb::ReadOptions::snapshot, and rocksdb::Status::ToString().
{
     ReadOptions options;
     options.snapshot = snapshot;
     std::string result;
     Status s = db_->Get(options, k, &result);
     if (s.IsNotFound()) {
       result = "NOT_FOUND";
     } else if (!s.ok()) {
       result = s.ToString();
     }
     return result;
   }
std::string rocksdb::SimpleTableDBTest::IterStatus (Iterator * iter) inline
Definition at line 687 of file simple_table_db_test.cc.
References rocksdb::Iterator::key(), rocksdb::Slice::ToString(), rocksdb::Iterator::Valid(), and rocksdb::Iterator::value().
{
     std::string result;
     if (iter->Valid()) {
       result = iter->key().ToString() + "->" + iter->value().ToString();
     } else {
       result = "(invalid)";
     }
     return result;
   }
int rocksdb::SimpleTableDBTest::NumTableFilesAtLevel (int level) inline
Definition at line 662 of file simple_table_db_test.cc.
References ASSERT_TRUE, db_, rocksdb::DB::GetProperty(), and rocksdb::NumberToString().
Referenced by FilesPerLevel().
{
     std::string property;
     ASSERT_TRUE(
         db_->GetProperty("rocksdb.num-files-at-level" + NumberToString(level),
                          &property));
     return atoi(property.c_str());
   }
Status rocksdb::SimpleTableDBTest::PureReopen (Options * options, DB ** db) inline
Definition at line 621 of file simple_table_db_test.cc.
References dbname_, and rocksdb::DB::Open().
{
     return DB::Open(*options, dbname_, db);
   }
Status rocksdb::SimpleTableDBTest::Put (const Slice & k, const Slice & v) inline
Definition at line 640 of file simple_table_db_test.cc.
References db_, and rocksdb::DB::Put().
{
     return db_->Put(WriteOptions(), k, v);
   }
void rocksdb::SimpleTableDBTest::Reopen (Options * options = nullptr) inline
Definition at line 600 of file simple_table_db_test.cc.
References ASSERT_OK, and TryReopen().
Referenced by SimpleTableDBTest().
{
     ASSERT_OK(TryReopen(options));
   }
Status rocksdb::SimpleTableDBTest::TryReopen (Options * options = nullptr) inline
Definition at line 625 of file simple_table_db_test.cc.
References rocksdb::Options::create_if_missing, CurrentOptions(), db_, dbname_, last_options_, and rocksdb::DB::Open().
Referenced by DestroyAndReopen(), and Reopen().
{
     delete db_;
     db_ = nullptr;
     Options opts;
     if (options != nullptr) {
       opts = *options;
     } else {
       opts = CurrentOptions();
       opts.create_if_missing = true;
     }
     last_options_ = opts;
     return DB::Open(opts, dbname_, &db_);
   }
Member Data Documentation
DB* rocksdb::SimpleTableDBTest::db_
Definition at line 572 of file simple_table_db_test.cc.
Referenced by Close(), dbfull(), Delete(), Destroy(), FilesPerLevel(), Get(), NumTableFilesAtLevel(), Put(), SimpleTableDBTest(), TryReopen(), and ~SimpleTableDBTest().
std::string rocksdb::SimpleTableDBTest::dbname_
Definition at line 570 of file simple_table_db_test.cc.
Referenced by Destroy(), PureReopen(), SimpleTableDBTest(), TryReopen(), and ~SimpleTableDBTest().
Env* rocksdb::SimpleTableDBTest::env_
Definition at line 571 of file simple_table_db_test.cc.
Options rocksdb::SimpleTableDBTest::last_options_
Definition at line 574 of file simple_table_db_test.cc.
Referenced by DestroyAndReopen(), and TryReopen().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/db/simple_table_db_test.cc