rippled: ripple::Transaction Class Reference
ripple::Transaction Class Reference
#include <Transaction.h>
Public Types
typedef boost::shared_ptr
< Transaction > pointer
typedef const pointer & ref
Public Member Functions
Transaction (SerializedTransaction::ref st, bool bValidate)
Transaction (TxType ttKind, const RippleAddress &naPublicKey, const RippleAddress &naSourceAccount, std::uint32_t uSeq, const STAmount &saFee, std::uint32_t uSourceTag)
bool sign (const RippleAddress &naAccountPrivate)
bool checkSign () const
void updateID ()
SerializedTransaction::ref getSTransaction ()
uint256 const & getID () const
const RippleAddress & getFromAccount () const
STAmount getAmount () const
STAmount getFee () const
std::uint32_t getFromAccountSeq () const
std::uint32_t getSourceTag () const
Blob getSignature () const
LedgerIndex getLedger () const
TransStatus getStatus () const
TER getResult ()
void setResult (TER terResult)
void setStatus (TransStatus status, std::uint32_t ledgerSeq)
void setStatus (TransStatus status)
void setLedger (LedgerIndex ledger)
bool operator< (const Transaction &) const
bool operator> (const Transaction &) const
bool operator== (const Transaction &) const
bool operator!= (const Transaction &) const
bool operator<= (const Transaction &) const
bool operator>= (const Transaction &) const
Json::Value getJson (int options, bool binary=false) const
Public Member Functions inherited from ripple::CountedObject< Transaction >
CountedObject ()
CountedObject (CountedObject const &)
~CountedObject ()
Static Public Member Functions
static char const * getCountedObjectName ()
static Transaction::pointer sharedTransaction (Blob const &vucTransaction, bool bValidate)
static Transaction::pointer transactionFromSQL (Database *db, bool bValidate)
static Transaction::pointer load (uint256 const &id)
static bool convertToTransactions (std::uint32_t ourLedgerSeq, std::uint32_t otherLedgerSeq, bool checkFirstTransactions, bool checkSecondTransactions, const SHAMap::Delta &inMap, std::map< uint256, std::pair< Transaction::pointer, Transaction::pointer > > &outMap)
static bool isHexTxID (const std::string &)
Static Protected Member Functions
static Transaction::pointer transactionFromSQL (const std::string &statement)
Private Attributes
uint256 mTransactionID
RippleAddress mAccountFrom
RippleAddress mFromPubKey
RippleAddress mSourcePrivate
LedgerIndex mInLedger
TransStatus mStatus
TER mResult
SerializedTransaction::pointer mTransaction
Detailed Description
Definition at line 45 of file Transaction.h.
Member Typedef Documentation
typedef boost::shared_ptr<Transaction> ripple::Transaction::pointer
Definition at line 52 of file Transaction.h.
typedef const pointer& ripple::Transaction::ref
Definition at line 53 of file Transaction.h.
Constructor & Destructor Documentation
ripple::Transaction::Transaction (SerializedTransaction::ref st, bool bValidate)
Definition at line 22 of file Transaction.cpp.
References checkSign(), mAccountFrom, mFromPubKey, mStatus, mTransaction, mTransactionID, ripple::NEW, ripple::passesLocalChecks(), and ripple::RippleAddress::setAccountPublic().
     : mInLedger (0), mStatus (INVALID), mResult (temUNCERTAIN), mTransaction (sit)
 {
     try
     {
         mFromPubKey.setAccountPublic (mTransaction->getSigningPubKey ());
         mTransactionID  = mTransaction->getTransactionID ();
         mAccountFrom    = mTransaction->getSourceAccount ();
     }
     catch (...)
     {
         return;
     }
     if (!bValidate || (passesLocalChecks (*mTransaction) && checkSign ()))
         mStatus = NEW;
 }
ripple::Transaction::Transaction (TxType ttKind, const RippleAddress & naPublicKey, const RippleAddress & naSourceAccount, std::uint32_t uSeq, const STAmount & saFee, std::uint32_t uSourceTag)
Definition at line 62 of file Transaction.cpp.
References ripple::RippleAddress::isValid(), mAccountFrom, mFromPubKey, and mTransaction.
                                       :
     mAccountFrom (naSourceAccount), mFromPubKey (naPublicKey), mInLedger (0), mStatus (NEW), mResult (temUNCERTAIN)
 {
     assert (mFromPubKey.isValid ());
     mTransaction    = boost::make_shared<SerializedTransaction> (ttKind);
     // Log(lsINFO) << str(boost::format("Transaction: account: %s") % naSourceAccount.humanAccountID());
     // Log(lsINFO) << str(boost::format("Transaction: mAccountFrom: %s") % mAccountFrom.humanAccountID());
     mTransaction->setSigningPubKey (mFromPubKey);
     mTransaction->setSourceAccount (mAccountFrom);
     mTransaction->setSequence (uSeq);
     mTransaction->setTransactionFee (saFee);
     if (uSourceTag)
     {
         mTransaction->makeFieldPresent (sfSourceTag);
         mTransaction->setFieldU32 (sfSourceTag, uSourceTag);
     }
 }
Member Function Documentation
bool ripple::Transaction::checkSign () const
Definition at line 122 of file Transaction.cpp.
References ripple::RippleAddress::isValid(), rocksdb::Log(), ripple::lsWARNING, mFromPubKey, and mTransaction.
Referenced by Transaction().
 {
     if (!mFromPubKey.isValid ())
     {
         Log (lsWARNING) << "Transaction has bad source public key";
         return false;
     }
     return mTransaction->checkSign (mFromPubKey);
 }
bool ripple::Transaction::convertToTransactions (std::uint32_t ourLedgerSeq, std::uint32_t otherLedgerSeq, bool checkFirstTransactions, bool checkSecondTransactions, const SHAMap::Delta & inMap, std::map< uint256, std::pair< Transaction::pointer, Transaction::pointer > > & outMap) static
Definition at line 280 of file Transaction.cpp.
References beast.util.Iter::first(), id, ripple::INCLUDED, ripple::INVALID, and sharedTransaction().
 {
     // convert a straight SHAMap payload difference to a transaction difference table
     // return value: true=ledgers are valid, false=a ledger is invalid
     SHAMap::Delta::const_iterator it;
     for (it = inMap.begin (); it != inMap.end (); ++it)
     {
         uint256 const& id = it->first;
         SHAMapItem::ref first = it->second.first;
         SHAMapItem::ref second = it->second.second;
         Transaction::pointer firstTrans, secondTrans;
         if (!!first)
         {
             // transaction in our table
             firstTrans = sharedTransaction (first->peekData (), checkFirstTransactions);
             if ((firstTrans->getStatus () == INVALID) || (firstTrans->getID () != id ))
             {
                 firstTrans->setStatus (INVALID, firstLedgerSeq);
                 return false;
             }
             else firstTrans->setStatus (INCLUDED, firstLedgerSeq);
         }
         if (!!second)
         {
             // transaction in other table
             secondTrans = sharedTransaction (second->peekData (), checkSecondTransactions);
             if ((secondTrans->getStatus () == INVALID) || (secondTrans->getID () != id))
             {
                 secondTrans->setStatus (INVALID, secondLedgerSeq);
                 return false;
             }
             else secondTrans->setStatus (INCLUDED, secondLedgerSeq);
         }
         assert (firstTrans || secondTrans);
         if (firstTrans && secondTrans && (firstTrans->getStatus () != INVALID) && (secondTrans->getStatus () != INVALID))
             return false; // one or the other SHAMap is structurally invalid or a miracle has happened
         outMap[id] = std::pair<Transaction::pointer, Transaction::pointer> (firstTrans, secondTrans);
     }
     return true;
 }
STAmount ripple::Transaction::getAmount () const inline
Definition at line 94 of file Transaction.h.
References mTransaction.
     {
         return mTransaction->getFieldU64 (sfAmount);
     }
static char const* ripple::Transaction::getCountedObjectName () inline static
Definition at line 50 of file Transaction.h.
 { return "Transaction"; }
STAmount ripple::Transaction::getFee () const inline
Definition at line 99 of file Transaction.h.
References mTransaction.
     {
         return mTransaction->getTransactionFee ();
     }
const RippleAddress& ripple::Transaction::getFromAccount () const inline
Definition at line 89 of file Transaction.h.
References mAccountFrom.
     {
         return mAccountFrom;
     }
std::uint32_t ripple::Transaction::getFromAccountSeq () const inline
Definition at line 104 of file Transaction.h.
References mTransaction.
     {
         return mTransaction->getSequence ();
     }
uint256 const& ripple::Transaction::getID () const inline
Definition at line 84 of file Transaction.h.
References mTransactionID.
     {
         return mTransactionID;
     }
Json::Value ripple::Transaction::getJson (int options, bool binary = false) const
Definition at line 334 of file Transaction.cpp.
References ripple::getApp(), ripple::LedgerMaster::getLedgerBySeq(), ripple::Application::getLedgerMaster(), mInLedger, and mTransaction.
 {
     Json::Value ret (mTransaction->getJson (0, binary));
     if (mInLedger)
     {
         ret["inLedger"] = mInLedger;        // Deprecated.
         ret["ledger_index"] = mInLedger;
         if (options == 1)
         {
             Ledger::pointer ledger = getApp().getLedgerMaster ().getLedgerBySeq (mInLedger);
             if (ledger)
                 ret["date"] = ledger->getCloseTimeNC ();
         }
     }
     return ret;
 }
LedgerIndex ripple::Transaction::getLedger () const inline
Definition at line 120 of file Transaction.h.
References mInLedger.
     {
         return mInLedger;
     }
TER ripple::Transaction::getResult () inline
Definition at line 130 of file Transaction.h.
References mResult.
     {
         return mResult;
     }
Blob ripple::Transaction::getSignature () const inline
Definition at line 115 of file Transaction.h.
References mTransaction.
     {
         return mTransaction->getSignature ();
     }
std::uint32_t ripple::Transaction::getSourceTag () const inline
Definition at line 109 of file Transaction.h.
References mTransaction.
     {
         return mTransaction->getFieldU32 (sfSourceTag);
     }
TransStatus ripple::Transaction::getStatus () const inline
Definition at line 125 of file Transaction.h.
References mStatus.
     {
         return mStatus;
     }
SerializedTransaction::ref ripple::Transaction::getSTransaction () inline
Definition at line 79 of file Transaction.h.
References mTransaction.
Referenced by sign().
     {
         return mTransaction;
     }
bool ripple::Transaction::isHexTxID (const std::string & txid) static
Definition at line 355 of file Transaction.cpp.
Referenced by ripple::RPCHandler::doTx().
 {
     if (txid.size () != 64)
         return false;
     auto const ret = std::find_if_not (txid.begin (), txid.end (),
         std::bind (
             std::isxdigit <std::string::value_type>,
             std::placeholders::_1,
             std::locale ()));
     return (ret == txid.end ());
 }
Transaction::pointer ripple::Transaction::load (uint256 const & id) static
Definition at line 272 of file Transaction.cpp.
References transactionFromSQL().
Referenced by ripple::TransactionMaster::fetch(), and ripple::NetworkOPsImp::findTransactionByID().
 {
     std::string sql = "SELECT LedgerSeq,Status,RawTxn FROM Transactions WHERE TransID='";
     sql.append (id.GetHex ());
     sql.append ("';");
     return transactionFromSQL (sql);
 }
bool ripple::Transaction::operator!= (const Transaction &) const
bool ripple::Transaction::operator< (const Transaction &) const
bool ripple::Transaction::operator<= (const Transaction &) const
bool ripple::Transaction::operator== (const Transaction &) const
bool ripple::Transaction::operator> (const Transaction &) const
bool ripple::Transaction::operator>= (const Transaction &) const
void ripple::Transaction::setLedger (LedgerIndex ledger) inline
Definition at line 147 of file Transaction.h.
References mInLedger.
     {
         mInLedger = ledger;
     }
void ripple::Transaction::setResult (TER terResult) inline
Definition at line 135 of file Transaction.h.
References mResult.
     {
         mResult = terResult;
     }
void ripple::Transaction::setStatus (TransStatus status, std::uint32_t ledgerSeq)
Definition at line 133 of file Transaction.cpp.
References mInLedger, and mStatus.
 {
     mStatus     = ts;
     mInLedger   = lseq;
 }
void ripple::Transaction::setStatus (TransStatus status) inline
Definition at line 142 of file Transaction.h.
References mStatus.
     {
         mStatus = status;
     }
Transaction::pointer ripple::Transaction::sharedTransaction (Blob const & vucTransaction, bool bValidate) static
Definition at line 40 of file Transaction.cpp.
References rocksdb::Log(), and ripple::lsWARNING.
Referenced by convertToTransactions(), ripple::Ledger::getTransaction(), and ripple::NetworkOPsImp::submitTransactionSync().
 {
     try
     {
         Serializer          s (vucTransaction);
         SerializerIterator  sit (s);
         SerializedTransaction::pointer  st  = boost::make_shared<SerializedTransaction> (boost::ref (sit));
         return boost::make_shared<Transaction> (st, bValidate);
     }
     catch (...)
     {
         Log (lsWARNING) << "Exception constructing transaction";
         return boost::shared_ptr<Transaction> ();
     }
 }
bool ripple::Transaction::sign (const RippleAddress & naAccountPrivate)
Definition at line 90 of file Transaction.cpp.
References getSTransaction(), ripple::INCOMPLETE, ripple::RippleAddress::isValid(), rocksdb::Log(), ripple::lsWARNING, mStatus, and updateID().
 {
     bool    bResult = true;
     if (!naAccountPrivate.isValid ())
     {
         Log (lsWARNING) << "No private key for signing";
         bResult = false;
     }
     getSTransaction ()->sign (naAccountPrivate);
     if (bResult)
     {
         updateID ();
     }
     else
     {
         mStatus = INCOMPLETE;
     }
     return bResult;
 }
Transaction::pointer ripple::Transaction::transactionFromSQL (Database * db, bool bValidate) static
Definition at line 139 of file Transaction.cpp.
References ripple::Serializer::begin(), ripple::COMMITTED, ripple::CONFLICTED, ripple::Database::getBinary(), ripple::Database::getInt(), ripple::Serializer::getLength(), ripple::Database::getStr(), ripple::HELD, ripple::INCLUDED, ripple::INVALID, ripple::NEW, ripple::Serializer::resize(), TXN_SQL_CONFLICT, TXN_SQL_HELD, TXN_SQL_INCLUDED, TXN_SQL_NEW, TXN_SQL_UNKNOWN, and TXN_SQL_VALIDATED.
Referenced by ripple::RPCHandler::doTxHistory(), ripple::NetworkOPsImp::getAccountTxs(), ripple::NetworkOPsImp::getTxsAccount(), and load().
 {
     Serializer rawTxn;
     std::string status;
     std::uint32_t inLedger;
     int txSize = 2048;
     rawTxn.resize (txSize);
     db->getStr ("Status", status);
     inLedger = db->getInt ("LedgerSeq");
     txSize = db->getBinary ("RawTxn", &*rawTxn.begin (), rawTxn.getLength ());
     if (txSize > rawTxn.getLength ())
     {
         rawTxn.resize (txSize);
         db->getBinary ("RawTxn", &*rawTxn.begin (), rawTxn.getLength ());
     }
     rawTxn.resize (txSize);
     SerializerIterator it (rawTxn);
     SerializedTransaction::pointer txn = boost::make_shared<SerializedTransaction> (boost::ref (it));
     Transaction::pointer tr = boost::make_shared<Transaction> (txn, bValidate);
     TransStatus st (INVALID);
     switch (status[0])
     {
     case TXN_SQL_NEW:
         st = NEW;
         break;
     case TXN_SQL_CONFLICT:
         st = CONFLICTED;
         break;
     case TXN_SQL_HELD:
         st = HELD;
         break;
     case TXN_SQL_VALIDATED:
         st = COMMITTED;
         break;
     case TXN_SQL_INCLUDED:
         st = INCLUDED;
         break;
     case TXN_SQL_UNKNOWN:
         break;
     default:
         assert (false);
     }
     tr->setStatus (st);
     tr->setLedger (inLedger);
     return tr;
 }
Transaction::pointer ripple::Transaction::transactionFromSQL (const std::string & statement) static protected
Definition at line 201 of file Transaction.cpp.
References ripple::Serializer::begin(), ripple::COMMITTED, ripple::CONFLICTED, db, ripple::Database::endIterRows(), ripple::Database::executeSQL(), ripple::getApp(), ripple::Database::getBinary(), ripple::DatabaseCon::getDB(), ripple::Database::getInt(), ripple::Serializer::getLength(), ripple::Database::getStr(), ripple::Application::getTxnDB(), ripple::HELD, ripple::INCLUDED, ripple::INVALID, ripple::NEW, ripple::Serializer::resize(), ripple::Database::startIterRows(), TXN_SQL_CONFLICT, TXN_SQL_HELD, TXN_SQL_INCLUDED, TXN_SQL_NEW, TXN_SQL_UNKNOWN, and TXN_SQL_VALIDATED.
 {
     Serializer rawTxn;
     std::string status;
     std::uint32_t inLedger;
     int txSize = 2048;
     rawTxn.resize (txSize);
     {
         DeprecatedScopedLock sl (getApp().getTxnDB ()->getDBLock ());
         Database* db = getApp().getTxnDB ()->getDB ();
         if (!db->executeSQL (sql, true) || !db->startIterRows ())
             return Transaction::pointer ();
         db->getStr ("Status", status);
         inLedger = db->getInt ("LedgerSeq");
         txSize = db->getBinary ("RawTxn", &*rawTxn.begin (), rawTxn.getLength ());
         if (txSize > rawTxn.getLength ())
         {
             rawTxn.resize (txSize);
             db->getBinary ("RawTxn", &*rawTxn.begin (), rawTxn.getLength ());
         }
         db->endIterRows ();
     }
     rawTxn.resize (txSize);
     SerializerIterator it (rawTxn);
     SerializedTransaction::pointer txn = boost::make_shared<SerializedTransaction> (boost::ref (it));
     Transaction::pointer tr = boost::make_shared<Transaction> (txn, true);
     TransStatus st (INVALID);
     switch (status[0])
     {
     case TXN_SQL_NEW:
         st = NEW;
         break;
     case TXN_SQL_CONFLICT:
         st = CONFLICTED;
         break;
     case TXN_SQL_HELD:
         st = HELD;
         break;
     case TXN_SQL_VALIDATED:
         st = COMMITTED;
         break;
     case TXN_SQL_INCLUDED:
         st = INCLUDED;
         break;
     case TXN_SQL_UNKNOWN:
         break;
     default:
         assert (false);
     }
     tr->setStatus (st);
     tr->setLedger (inLedger);
     return tr;
 }
void ripple::Transaction::updateID () inline
Definition at line 74 of file Transaction.h.
References mTransaction, and mTransactionID.
Referenced by sign().
     {
         mTransactionID = mTransaction->getTransactionID ();
     }
Member Data Documentation
RippleAddress ripple::Transaction::mAccountFrom private
Definition at line 179 of file Transaction.h.
Referenced by getFromAccount(), and Transaction().
RippleAddress ripple::Transaction::mFromPubKey private
Definition at line 180 of file Transaction.h.
Referenced by checkSign(), and Transaction().
LedgerIndex ripple::Transaction::mInLedger private
Definition at line 183 of file Transaction.h.
Referenced by getJson(), getLedger(), setLedger(), and setStatus().
TER ripple::Transaction::mResult private
Definition at line 185 of file Transaction.h.
Referenced by getResult(), and setResult().
RippleAddress ripple::Transaction::mSourcePrivate private
Definition at line 181 of file Transaction.h.
TransStatus ripple::Transaction::mStatus private
Definition at line 184 of file Transaction.h.
Referenced by getStatus(), setStatus(), sign(), and Transaction().
SerializedTransaction::pointer ripple::Transaction::mTransaction private
Definition at line 187 of file Transaction.h.
Referenced by checkSign(), getAmount(), getFee(), getFromAccountSeq(), getJson(), getSignature(), getSourceTag(), getSTransaction(), Transaction(), and updateID().
uint256 ripple::Transaction::mTransactionID private
Definition at line 178 of file Transaction.h.
Referenced by getID(), Transaction(), and updateID().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/tx/Transaction.h
rippled/src/ripple_app/tx/Transaction.cpp