rippled: rocksdb::InternalFilterPolicy Class Reference
rocksdb::InternalFilterPolicy Class Reference
#include <dbformat.h>
Public Member Functions
InternalFilterPolicy (const FilterPolicy *p)
virtual const char * Name () const
virtual void CreateFilter (const Slice *keys, int n, std::string *dst) const
virtual bool KeyMayMatch (const Slice &key, const Slice &filter) const
Public Member Functions inherited from rocksdb::FilterPolicy
virtual ~FilterPolicy ()
Private Attributes
const FilterPolicy *const user_policy_
Detailed Description
Definition at line 113 of file dbformat.h.
Constructor & Destructor Documentation
rocksdb::InternalFilterPolicy::InternalFilterPolicy (const FilterPolicy * p) inline explicit
Definition at line 117 of file dbformat.h.
 : user_policy_(p) { }
Member Function Documentation
void rocksdb::InternalFilterPolicy::CreateFilter (const Slice * keys, int n, std::string * dst) const virtual
Implements rocksdb::FilterPolicy.
Definition at line 112 of file dbformat.cc.
References rocksdb::FilterPolicy::CreateFilter(), rocksdb::ExtractUserKey(), and user_policy_.
{
   // We rely on the fact that the code in table.cc does not mind us
   // adjusting keys[].
   Slice* mkey = const_cast<Slice*>(keys);
   for (int i = 0; i < n; i++) {
     mkey[i] = ExtractUserKey(keys[i]);
     // TODO(sanjay): Suppress dups?
   }
   user_policy_->CreateFilter(keys, n, dst);
 }
bool rocksdb::InternalFilterPolicy::KeyMayMatch (const Slice & key, const Slice & filter) const virtual
Implements rocksdb::FilterPolicy.
Definition at line 124 of file dbformat.cc.
References rocksdb::ExtractUserKey(), rocksdb::FilterPolicy::KeyMayMatch(), and user_policy_.
{
   return user_policy_->KeyMayMatch(ExtractUserKey(key), f);
 }
const char * rocksdb::InternalFilterPolicy::Name () const virtual
Implements rocksdb::FilterPolicy.
Definition at line 108 of file dbformat.cc.
References rocksdb::FilterPolicy::Name(), and user_policy_.
{
   return user_policy_->Name();
 }
Member Data Documentation
const FilterPolicy* const rocksdb::InternalFilterPolicy::user_policy_ private
Definition at line 115 of file dbformat.h.
Referenced by CreateFilter(), KeyMayMatch(), and Name().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/db/dbformat.h
rippled/src/ripple/rocksdb/rocksdb/db/dbformat.cc