rippled: rippled/src/ripple/rocksdb/rocksdb/db/db_bench.cc File Reference
db_bench.cc File Reference
#include <cstddef>
#include <sys/types.h>
#include <stdio.h>
#include <stdlib.h>
#include <gflags/gflags.h>
#include "db_impl.h"
#include "version_set.h"
#include "db_statistics.h"
#include "../include/rocksdb/options.h"
#include "../include/rocksdb/cache.h"
#include "../include/rocksdb/db.h"
#include "../include/rocksdb/env.h"
#include "../include/rocksdb/memtablerep.h"
#include "../include/rocksdb/write_batch.h"
#include "../include/rocksdb/statistics.h"
#include "../port/port.h"
#include "../util/bit_set.h"
#include "../util/crc32c.h"
#include "../util/histogram.h"
#include "../util/mutexlock.h"
#include "../util/random.h"
#include "../util/stack_trace.h"
#include "../util/string_util.h"
#include "../util/testutil.h"
#include "hdfs/env_hdfs.h"
#include "utilities/merge_operators.h"
Classes
class rocksdb::RandomGenerator
class rocksdb::Stats
struct rocksdb::SharedState
struct rocksdb::ThreadState
class rocksdb::Duration
class rocksdb::Benchmark
struct rocksdb::Benchmark::ThreadArg
Namespaces
rocksdb
Constant Groups
rocksdb
Enumerations
enum RepFactory {
kSkipList, kPrefixHash, kUnsorted, kVectorRep,
kSkipList, kPrefixHash, kUnsorted, kVectorRep
}
Functions
DEFINE_string (benchmarks,"fillseq,""fillsync,""fillrandom,""overwrite,""readrandom,""readrandom,""readseq,""readreverse,""compact,""readrandom,""readseq,""readreverse,""readwhilewriting,""readrandomwriterandom,""updaterandom,""randomwithverify,""fill100K,""crc32c,""snappycomp,""snappyuncomp,""acquireload,""fillfromstdin,","Comma-separated list of operations to run in the specified order""Actual benchmarks:\n""\tfillseq -- write N values in sequential key"" order in async mode\n""\tfillrandom -- write N values in random key order in async"" mode\n""\toverwrite -- overwrite N values in random key order in"" async mode\n""\tfillsync -- write N/100 values in random key order in ""sync mode\n""\tfill100K -- write N/1000 100K values in random order in"" async mode\n""\tdeleteseq -- delete N keys in sequential order\n""\tdeleterandom -- delete N keys in random order\n""\treadseq -- read N times sequentially\n""\treadreverse -- read N times in reverse order\n""\treadrandom -- read N times in random order\n""\treadmissing -- read N missing keys in random order\n""\treadhot -- read N times in random order from 1% section ""of DB\n""\treadwhilewriting -- 1 writer, N threads doing random ""reads\n""\treadrandomwriterandom -- N threads doing random-read, ""random-write\n""\tprefixscanrandom -- prefix scan N times in random order\n""\tupdaterandom -- N threads doing read-modify-write for random ""keys\n""\tappendrandom -- N threads doing read-modify-write with ""growing values\n""\tmergerandom -- same as updaterandom/appendrandom using merge"" operator. ""Must be used with merge_operator\n""\tseekrandom -- N random seeks\n""\tcrc32c -- repeated crc32c of 4K of data\n""\tacquireload -- load N*1000 times\n""Meta operations:\n""\tcompact -- Compact the entire DB\n""\tstats -- Print DB stats\n""\tlevelstats -- Print the number of files and bytes per level\n""\tsstables -- Print sstable info\n""\theapprofile -- Dump a heap profile (if supported by this"" port)\n")
DEFINE_int64 (num, 1000000,"Number of key/values to place in database")
DEFINE_int64 (numdistinct, 1000,"Number of distinct keys to use. Used in RandomWithVerify to ""read/write on fewer keys so that gets are more likely to find the"" key and puts are more likely to update the same key")
DEFINE_int64 (reads,-1,"Number of read operations to do. ""If negative, do FLAGS_num reads.")
DEFINE_int64 (read_range, 1,"When ==1 reads use ::Get, when >1 reads use"" an iterator")
DEFINE_bool (use_prefix_blooms, false,"Whether to place prefixes in blooms")
DEFINE_bool (use_prefix_api, false,"Whether to set ReadOptions.prefix for"" prefixscanrandom. If true, use_prefix_blooms must also be true.")
DEFINE_int64 (seed, 0,"Seed base for random number generators. ""When 0 it is deterministic.")
DEFINE_int32 (threads, 1,"Number of concurrent threads to run.")
DEFINE_int32 (duration, 0,"Time in seconds for the random-ops tests to run."" When 0 then num & reads determine the test duration")
DEFINE_int32 (value_size, 100,"Size of each value")
static bool ValidateKeySize (const char *flagname, int32_t value)
DEFINE_int32 (key_size, 16,"size of each key")
DEFINE_double (compression_ratio, 0.5,"Arrange to generate values that shrink"" to this fraction of their original size after compression")
DEFINE_bool (histogram, false,"Print histogram of operation timings")
DEFINE_int32 (write_buffer_size, rocksdb::Options().write_buffer_size,"Number of bytes to buffer in memtable before compacting")
DEFINE_int32 (max_write_buffer_number, rocksdb::Options().max_write_buffer_number,"The number of in-memory memtables. Each memtable is of size""write_buffer_size.")
DEFINE_int32 (min_write_buffer_number_to_merge, rocksdb::Options().min_write_buffer_number_to_merge,"The minimum number of write buffers that will be merged together""before writing to storage. This is cheap because it is an""in-memory merge. If this feature is not enabled, then all these""write buffers are flushed to L0 as separate files and this ""increases read amplification because a get request has to check"" in all of these files. Also, an in-memory merge may result in"" writing less data to storage if there are duplicate records "" in each of these individual write buffers.")
DEFINE_int32 (max_background_compactions, rocksdb::Options().max_background_compactions,"The maximum number of concurrent background compactions"" that can occur in parallel.")
DEFINE_int32 (compaction_style,(int32_t) rocksdb::Options().compaction_style,"style of compaction: level-based vs universal")
DEFINE_int32 (universal_size_ratio, 0,"Percentage flexibility while comparing file size"" (for universal compaction only).")
DEFINE_int32 (universal_min_merge_width, 0,"The minimum number of files in a"" single compaction run (for universal compaction only).")
DEFINE_int32 (universal_max_merge_width, 0,"The max number of files to compact"" in universal style compaction")
DEFINE_int32 (universal_max_size_amplification_percent, 0,"The max size amplification for universal style compaction")
DEFINE_int64 (cache_size,-1,"Number of bytes to use as a cache of uncompressed""data. Negative means use default settings.")
DEFINE_int32 (block_size, rocksdb::Options().block_size,"Number of bytes in a block.")
DEFINE_int64 (compressed_cache_size,-1,"Number of bytes to use as a cache of compressed data.")
DEFINE_int32 (open_files, rocksdb::Options().max_open_files,"Maximum number of files to keep open at the same time"" (use default if == 0)")
DEFINE_int32 (bloom_bits,-1,"Bloom filter bits per key. Negative means"" use default settings.")
DEFINE_bool (use_existing_db, false,"If true, do not destroy the existing"" database. If you set this flag and also specify a benchmark that"" wants a fresh database, that benchmark will fail.")
DEFINE_string (db,"","Use the db with the following name.")
static bool ValidateCacheNumshardbits (const char *flagname, int32_t value)
DEFINE_int32 (cache_numshardbits,-1,"Number of shards for the block cache"" is 2 ** cache_numshardbits. Negative means use default settings."" This is applied only if FLAGS_cache_size is non-negative.")
DEFINE_int32 (cache_remove_scan_count_limit, 32,"")
DEFINE_bool (verify_checksum, false,"Verify checksum for every block read"" from storage")
DEFINE_bool (statistics, false,"Database statistics")
DEFINE_int64 (writes,-1,"Number of write operations to do. If negative, do"" --num reads.")
DEFINE_int32 (writes_per_second, 0,"Per-thread rate limit on writes per second."" No limit when <= 0. Only for the readwhilewriting test.")
DEFINE_bool (sync, false,"Sync all writes to disk")
DEFINE_bool (disable_data_sync, false,"If true, do not wait until data is"" synced to disk.")
DEFINE_bool (use_fsync, false,"If true, issue fsync instead of fdatasync")
DEFINE_bool (disable_wal, false,"If true, do not write WAL for write.")
DEFINE_bool (use_snapshot, false,"If true, create a snapshot per query when"" randomread benchmark is used")
DEFINE_bool (get_approx, false,"If true, call GetApproximateSizes per query"" when read_range is > 1 and randomread benchmark is used")
DEFINE_int32 (num_levels, 7,"The total number of levels")
DEFINE_int32 (target_file_size_base, 2 *1048576,"Target file size at level-1")
DEFINE_int32 (target_file_size_multiplier, 1,"A multiplier to compute target level-N file size (N >= 2)")
DEFINE_uint64 (max_bytes_for_level_base, 10 *1048576,"Max bytes for level-1")
DEFINE_int32 (max_bytes_for_level_multiplier, 10,"A multiplier to compute max bytes for level-N (N >= 2)")
DEFINE_string (max_bytes_for_level_multiplier_additional,"","A vector that specifies additional fanout per level")
DEFINE_int32 (level0_stop_writes_trigger, 12,"Number of files in level-0"" that will trigger put stop.")
DEFINE_int32 (level0_slowdown_writes_trigger, 8,"Number of files in level-0"" that will slow down writes.")
DEFINE_int32 (level0_file_num_compaction_trigger, 4,"Number of files in level-0"" when compactions start")
static bool ValidateInt32Percent (const char *flagname, int32_t value)
DEFINE_int32 (readwritepercent, 90,"Ratio of reads to reads/writes (expressed"" as percentage) for the ReadRandomWriteRandom workload. The ""default value 90 means 90% operations out of all reads and writes"" operations are reads. In other words, 9 gets for every 1 put.")
DEFINE_int32 (deletepercent, 2,"Percentage of deletes out of reads/writes/""deletes (used in RandomWithVerify only). RandomWithVerify ""calculates writepercent as (100 - FLAGS_readwritepercent - ""deletepercent), so deletepercent must be smaller than (100 - ""FLAGS_readwritepercent)")
DEFINE_int32 (disable_seek_compaction, false,"Option to disable compaction"" triggered by read.")
DEFINE_uint64 (delete_obsolete_files_period_micros, 0,"Option to delete ""obsolete files periodically. 0 means that obsolete files are"" deleted after every compaction run.")
enum rocksdb::CompressionType StringToCompressionType (const char *ctype)
DEFINE_string (compression_type,"snappy","Algorithm to use to compress the database")
DEFINE_int32 (min_level_to_compress,-1,"If non-negative, compression starts"" from this level. Levels with number < min_level_to_compress are"" not compressed. Otherwise, apply compression_type to ""all levels.")
static bool ValidateTableCacheNumshardbits (const char *flagname, int32_t value)
DEFINE_int32 (table_cache_numshardbits, 4,"")
DEFINE_string (hdfs,"","Name of hdfs environment")
DEFINE_int64 (stats_interval, 0,"Stats are reported every N operations when ""this is greater than zero. When 0 the interval grows over time.")
DEFINE_int32 (stats_per_interval, 0,"Reports additional stats per interval when"" this is greater than 0.")
static bool ValidateRateLimit (const char *flagname, double value)
DEFINE_double (soft_rate_limit, 0.0,"")
DEFINE_double (hard_rate_limit, 0.0,"When not equal to 0 this make threads ""sleep at each stats reporting interval until the compaction"" score for all levels is less than or equal to this value.")
DEFINE_int32 (rate_limit_delay_max_milliseconds, 1000,"When hard_rate_limit is set then this is the max time a put will"" be stalled.")
DEFINE_int32 (max_grandparent_overlap_factor, 10,"Control maximum bytes of ""overlaps in grandparent (i.e., level+2) before we stop building a"" single file in a level->level+1 compaction.")
DEFINE_bool (readonly, false,"Run read only benchmarks.")
DEFINE_bool (disable_auto_compactions, false,"Do not auto trigger compactions")
DEFINE_int32 (source_compaction_factor, 1,"Cap the size of data in level-K for"" a compaction run that compacts Level-K with Level-(K+1) (for"" K >= 1)")
DEFINE_uint64 (wal_ttl_seconds, 0,"Set the TTL for the WAL Files in seconds.")
DEFINE_uint64 (wal_size_limit_MB, 0,"Set the size limit for the WAL Files"" in MB.")
DEFINE_bool (bufferedio, rocksdb::EnvOptions().use_os_buffer,"Allow buffered io using OS buffers")
DEFINE_bool (mmap_read, rocksdb::EnvOptions().use_mmap_reads,"Allow reads to occur via mmap-ing files")
DEFINE_bool (mmap_write, rocksdb::EnvOptions().use_mmap_writes,"Allow writes to occur via mmap-ing files")
DEFINE_bool (advise_random_on_open, rocksdb::Options().advise_random_on_open,"Advise random access on table file open")
DEFINE_string (compaction_fadvice,"NORMAL","Access pattern advice when a file is compacted")
DEFINE_bool (use_multiget, false,"Use multiget to access a series of keys instead of get")
DEFINE_int64 (keys_per_multiget, 90,"If use_multiget is true, determines number"" of keys to group per call Arbitrary default is good because it"" agrees with readwritepercent")
DEFINE_bool (warn_missing_keys, true,"Print a message to user when a key is"" missing in a Get/MultiGet call")
DEFINE_bool (use_adaptive_mutex, rocksdb::Options().use_adaptive_mutex,"Use adaptive mutex")
DEFINE_uint64 (bytes_per_sync, rocksdb::Options().bytes_per_sync,"Allows OS to incrementally sync files to disk while they are"" being written, in the background. Issue one request for every"" bytes_per_sync written. 0 turns it off.")
DEFINE_bool (filter_deletes, false," On true, deletes use bloom-filter and drop"" the delete if key not present")
static bool ValidatePrefixSize (const char *flagname, int32_t value)
DEFINE_int32 (prefix_size, 0,"Control the prefix size for PrefixHashRep")
enum RepFactory StringToRepFactory (const char *ctype)
DEFINE_string (memtablerep,"skip_list","")
DEFINE_string (merge_operator,"","The merge operator to use with the database.""If a new merge operator is specified, be sure to use fresh"" database The possible merge operators are defined in"" utilities/merge_operators.h")
static void rocksdb::AppendWithSpace (std::string *str, Slice msg)
int main (int argc, char **argv)
Variables
static const int kMaxKeySize = 128
static rocksdb::CompactionStyle FLAGS_compaction_style_e
static class std::shared_ptr
< rocksdb::Statistics > dbstats
static std::vector< int > FLAGS_max_bytes_for_level_multiplier_additional_v
static enum
rocksdb::CompressionType FLAGS_compression_type_e
static rocksdb::Env * FLAGS_env = rocksdb::Env::Default()
static auto FLAGS_compaction_fadvice_e
static enum RepFactory FLAGS_rep_factory
static const bool FLAGS_soft_rate_limit_dummy
static const bool FLAGS_hard_rate_limit_dummy
static const bool FLAGS_prefix_size_dummy
static const bool FLAGS_key_size_dummy
static const bool FLAGS_cache_numshardbits_dummy
static const bool FLAGS_readwritepercent_dummy
static const bool FLAGS_deletepercent_dummy
static const bool FLAGS_table_cache_numshardbits_dummy
Enumeration Type Documentation
enum RepFactory
Enumerator
kSkipList
kPrefixHash
kUnsorted
kVectorRep
kSkipList
kPrefixHash
kUnsorted
kVectorRep
Definition at line 436 of file db_bench.cc.
                 {
   kSkipList,
   kPrefixHash,
   kUnsorted,
   kVectorRep
 };
Function Documentation
DEFINE_bool (use_prefix_blooms , false , "Whether to place prefixes in blooms")
DEFINE_bool (use_prefix_api , false , "Whether to set ReadOptions.prefix for"" prefixscanrandom. If true, use_prefix_blooms must also be true.")
DEFINE_bool (histogram , false , "Print histogram of operation timings")
DEFINE_bool (use_existing_db , false , "If true, do not destroy the existing""database.If you set this flag and also specify a benchmark that""wants a fresh database, that benchmark will fail.")
DEFINE_bool (verify_checksum , false , "Verify checksum for every block read"" from storage")
DEFINE_bool (statistics , false , "Database statistics")
DEFINE_bool (sync , false , "Sync all writes to disk")
DEFINE_bool (disable_data_sync , false , "If true, do not wait until data is""synced to disk.")
DEFINE_bool (use_fsync , false , "If true, issue fsync instead of fdatasync")
DEFINE_bool (disable_wal , false , "If true, do not write WAL for write.")
DEFINE_bool (use_snapshot , false , "If true, create a snapshot per query when""randomread benchmark is used")
DEFINE_bool (get_approx , false , "If true, call GetApproximateSizes per query""when read_range is, 1 and randomread benchmark is used")
DEFINE_bool (readonly , false , "Run read only benchmarks.")
DEFINE_bool (disable_auto_compactions , false , "Do not auto trigger compactions")
DEFINE_bool (bufferedio , rocksdb::EnvOptions(). use_os_buffer, "Allow buffered io using OS buffers")
DEFINE_bool (mmap_read , rocksdb::EnvOptions(). use_mmap_reads, "Allow reads to occur via mmap-ing files")
DEFINE_bool (mmap_write , rocksdb::EnvOptions(). use_mmap_writes, "Allow writes to occur via mmap-ing files")
DEFINE_bool (advise_random_on_open , rocksdb::Options(). advise_random_on_open, "Advise random access on table file open")
DEFINE_bool (use_multiget , false , "Use multiget to access a series of keys instead of get")
DEFINE_bool (warn_missing_keys , true , "Print a message to user when a key is"" missing in a Get/MultiGet call")
DEFINE_bool (use_adaptive_mutex , rocksdb::Options(). use_adaptive_mutex, "Use adaptive mutex")
DEFINE_bool (filter_deletes , false , " On true, deletes use bloom-filter and drop""the delete if key not present")
DEFINE_double (compression_ratio , 0. 5, "Arrange to generate values that shrink"" to this fraction of their original size after compression")
DEFINE_double (soft_rate_limit , 0. 0, "")
DEFINE_double (hard_rate_limit , 0. 0, "When not equal to 0 this make threads ""sleep at each stats reporting interval until the compaction"" score for all levels is less than or equal to this value.")
DEFINE_int32 (threads , 1 , "Number of concurrent threads to run.")
DEFINE_int32 (duration , 0 , "Time in seconds for the random-ops tests to run."" When 0 then num & reads determine the test duration")
DEFINE_int32 (value_size , 100 , "Size of each value")
DEFINE_int32 (key_size , 16 , "size of each key")
DEFINE_int32 (write_buffer_size , rocksdb::Options(). write_buffer_size, "Number of bytes to buffer in memtable before compacting")
DEFINE_int32 (max_write_buffer_number , rocksdb::Options(). max_write_buffer_number, "The number of in-memory memtables. Each memtable is of size""write_buffer_size.")
DEFINE_int32 (min_write_buffer_number_to_merge , rocksdb::Options(). min_write_buffer_number_to_merge, "The minimum number of write buffers that will be merged together""before writing to storage. This is cheap because it is an""in-memory merge. If this feature is not enabled, then all these""write buffers are flushed to L0 as separate files and this""increases read amplification because a get request has to check""in all of these files. Also, an in-memory merge may result in""writing less data to storage if there are duplicate records""in each of these individual write buffers.")
DEFINE_int32 (max_background_compactions , rocksdb::Options(). max_background_compactions, "The maximum number of concurrent background compactions"" that can occur in parallel.")
DEFINE_int32 (compaction_style , (int32_t) rocksdb::Options(). compaction_style, "style of compaction: level-based vs universal")
DEFINE_int32 (universal_size_ratio , 0 , "Percentage flexibility while comparing file size"" (for universal compaction only).")
DEFINE_int32 (universal_min_merge_width , 0 , "The minimum number of files in a"" single compaction run (for universal compaction only).")
DEFINE_int32 (universal_max_merge_width , 0 , "The max number of files to compact"" in universal style compaction")
DEFINE_int32 (universal_max_size_amplification_percent , 0 , "The max size amplification for universal style compaction")
DEFINE_int32 (block_size , rocksdb::Options(). block_size, "Number of bytes in a block.")
DEFINE_int32 (open_files , rocksdb::Options(). max_open_files, "Maximum number of files to keep open at the same time"" (use default if == 0)")
DEFINE_int32 (bloom_bits , - 1, "Bloom filter bits per key. Negative means"" use default settings.")
DEFINE_int32 (cache_numshardbits , - 1, "Number of shards for the block cache"" is 2 ** cache_numshardbits. Negative means use default settings."" This is applied only if FLAGS_cache_size is non-negative.")
DEFINE_int32 (cache_remove_scan_count_limit , 32 , "")
DEFINE_int32 (writes_per_second , 0 , "Per-thread rate limit on writes per second."" No limit when <= 0. Only for the readwhilewriting test.")
DEFINE_int32 (num_levels , 7 , "The total number of levels")
DEFINE_int32 (target_file_size_base , 2 * 1048576, "Target file size at level-1")
DEFINE_int32 (target_file_size_multiplier , 1 , "A multiplier to compute target level-N file size (N >= 2)")
DEFINE_int32 (max_bytes_for_level_multiplier , 10 , "A multiplier to compute max bytes for level-N (N >= 2)")
DEFINE_int32 (level0_stop_writes_trigger , 12 , "Number of files in level-0"" that will trigger put stop.")
DEFINE_int32 (level0_slowdown_writes_trigger , 8 , "Number of files in level-0"" that will slow down writes.")
DEFINE_int32 (level0_file_num_compaction_trigger , 4 , "Number of files in level-0"" when compactions start")
DEFINE_int32 (readwritepercent , 90 , "Ratio of reads to reads/writes (expressed"" as percentage) for the ReadRandomWriteRandom workload. The ""default value 90 means 90% operations out of all reads and writes"" operations are reads. In other words, 9 gets for every 1 put.")
DEFINE_int32 (deletepercent , 2 , "Percentage of deletes out of reads/writes/""deletes used in RandomWithVerify only). RandomWithVerify ""calculates writepercent as (100 - FLAGS_readwritepercent - ""deletepercent, so deletepercent must be smaller than(100-""FLAGS_readwritepercent)")
DEFINE_int32 (disable_seek_compaction , false , "Option to disable compaction"" triggered by read.")
DEFINE_int32 (min_level_to_compress , - 1, "If non- negative)
DEFINE_int32 (table_cache_numshardbits , 4 , "")
DEFINE_int32 (stats_per_interval , 0 , "Reports additional stats per interval when"" this is greater than 0.")
DEFINE_int32 (rate_limit_delay_max_milliseconds , 1000 , "When hard_rate_limit is set then this is the max time a put will"" be stalled.")
DEFINE_int32 (max_grandparent_overlap_factor , 10 , "Control maximum bytes of ""overlaps in grandparent (i.e., level+2) before we stop building a"" single file in a level->level+1 compaction.")
DEFINE_int32 (source_compaction_factor , 1 , "Cap the size of data in level-K for"" a compaction run that compacts Level-K with Level-(K+1) (for"" K >= 1)")
DEFINE_int32 (prefix_size , 0 , "Control the prefix size for PrefixHashRep")
DEFINE_int64 (num , 1000000 , "Number of key/values to place in database")
DEFINE_int64 (numdistinct , 1000 , "Number of distinct keys to use. Used in RandomWithVerify to ""read/write on fewer keys so that gets are more likely to find the"" key and puts are more likely to update the same key")
DEFINE_int64 (reads , - 1, "Number of read operations to do. ""If negative, do FLAGS_num reads.")
DEFINE_int64 (read_range , 1 , " When = =1 reads use ::Get, when , 1 reads use""an iterator")
DEFINE_int64 (seed , 0 , "Seed base for random number generators. ""When 0 it is deterministic.")
DEFINE_int64 (cache_size , - 1, "Number of bytes to use as a cache of uncompressed""data. Negative means use default settings.")
DEFINE_int64 (compressed_cache_size , - 1, "Number of bytes to use as a cache of compressed data.")
DEFINE_int64 (writes , - 1, "Number of write operations to do. If negative, do""--num reads.")
DEFINE_int64 (stats_interval , 0 , "Stats are reported every N operations when ""this is greater than zero. When 0 the interval grows over time.")
DEFINE_int64 (keys_per_multiget , 90 , "If use_multiget is true, determines number""of keys to group per call Arbitrary default is good because it""agrees with readwritepercent")
DEFINE_string (benchmarks , " fillseq, "" fillsync, "" fillrandom, "" overwrite, "" readrandom, "" readrandom, "" readseq, "" readreverse, "" compact, "" readrandom, "" readseq, "" readreverse, "" readwhilewriting, "" readrandomwriterandom, "" updaterandom, "" randomwithverify, "" fill100K, "" crc32c, "" snappycomp, "" snappyuncomp, "" acquireload, "" fillfromstdin, " , "Comma-separated list of operations to run in the specified order""Actual benchmarks:\n""\tfillseq -- write N values in sequential key"" order in async mode\n""\tfillrandom -- write N values in random key order in async"" mode\n""\toverwrite -- overwrite N values in random key order in"" async mode\n""\tfillsync -- write N/100 values in random key order in ""sync mode\n""\tfill100K -- write N/1000 100K values in random order in"" async mode\n""\tdeleteseq -- delete N keys in sequential order\n""\tdeleterandom -- delete N keys in random order\n""\treadseq -- read N times sequentially\n""\treadreverse -- read N times in reverse order\n""\treadrandom -- read N times in random order\n""\treadmissing -- read N missing keys in random order\n""\treadhot -- read N times in random order from 1% section ""of DB\n""\treadwhilewriting -- 1 writer, N threads doing random""reads\n""\treadrandomwriterandom--N threads doing random- read, ""random-write\n""\tprefixscanrandom--prefix scan N times in random order\n""\tupdaterandom--N threads doing read-modify-write for random""keys\n""\tappendrandom--N threads doing read-modify-write with""growing values\n""\tmergerandom--same as updaterandom/appendrandom using merge""operator.""Must be used with merge_operator\n""\tseekrandom--N random seeks\n""\tcrc32c--repeated crc32c of 4K of data\n""\tacquireload--load N *1000 times\n""Meta operations:\n""\tcompact--Compact the entire DB\n""\tstats--Print DB stats\n""\tlevelstats--Print the number of files and bytes per level\n""\tsstables--Print sstable info\n""\theapprofile--Dump a heap profile(if supported by this""port)\n")
DEFINE_string (db , "" , "Use the db with the following name.")
DEFINE_string (max_bytes_for_level_multiplier_additional , "" , "A vector that specifies additional fanout per level")
DEFINE_string (compression_type , "snappy" , "Algorithm to use to compress the database")
DEFINE_string (hdfs , "" , "Name of hdfs environment")
DEFINE_string (compaction_fadvice , "NORMAL" , "Access pattern advice when a file is compacted")
DEFINE_string (memtablerep , "skip_list" , "")
DEFINE_string (merge_operator , "" , "The merge operator to use with the database.""If a new merge operator is specified, be sure to use fresh""database The possible merge operators are defined in""utilities/merge_operators.h")
DEFINE_uint64 (max_bytes_for_level_base , 10 * 1048576, "Max bytes for level-1")
DEFINE_uint64 (delete_obsolete_files_period_micros , 0 , "Option to delete ""obsolete files periodically. 0 means that obsolete files are"" deleted after every compaction run.")
DEFINE_uint64 (wal_ttl_seconds , 0 , "Set the TTL for the WAL Files in seconds.")
DEFINE_uint64 (wal_size_limit_MB , 0 , "Set the size limit for the WAL Files"" in MB.")
DEFINE_uint64 (bytes_per_sync , rocksdb::Options(). bytes_per_sync, "Allows OS to incrementally sync files to disk while they are"" being written, in the background.Issue one request for every""bytes_per_sync written.0 turns it off.")
int main (int argc, char ** argv)
Definition at line 2420 of file db_bench.cc.
References rocksdb::CreateDBStatistics(), dbstats, rocksdb::Env::Default(), FLAGS_compaction_fadvice_e, FLAGS_max_bytes_for_level_multiplier_additional_v, rocksdb::Env::GetTestDirectory(), rocksdb::InstallStackTraceHandler(), rocksdb::Options::NONE, rocksdb::Options::NORMAL, rocksdb::Benchmark::Run(), rocksdb::Options::SEQUENTIAL, rocksdb::Env::SetBackgroundThreads(), rocksdb::stringSplit(), StringToCompressionType(), StringToRepFactory(), and rocksdb::Options::WILLNEED.
{
   rocksdb::InstallStackTraceHandler();
   google::SetUsageMessage(std::string("\nUSAGE:\n") + std::string(argv[0]) +
                           " [OPTIONS]...");
   google::ParseCommandLineFlags(&argc, &argv, true);
   FLAGS_compaction_style_e = (rocksdb::CompactionStyle) FLAGS_compaction_style;
   if (FLAGS_statistics) {
     dbstats = rocksdb::CreateDBStatistics();
   }
   std::vector<std::string> fanout =
     rocksdb::stringSplit(FLAGS_max_bytes_for_level_multiplier_additional, ',');
   for (unsigned int j= 0; j < fanout.size(); j++) {
     FLAGS_max_bytes_for_level_multiplier_additional_v.push_back(
       std::stoi(fanout[j]));
   }
   FLAGS_compression_type_e =
     StringToCompressionType(FLAGS_compression_type.c_str());
   if (!FLAGS_hdfs.empty()) {
     FLAGS_env  = new rocksdb::HdfsEnv(FLAGS_hdfs);
   }
   if (!strcasecmp(FLAGS_compaction_fadvice.c_str(), "NONE"))
     FLAGS_compaction_fadvice_e = rocksdb::Options::NONE;
   else if (!strcasecmp(FLAGS_compaction_fadvice.c_str(), "NORMAL"))
     FLAGS_compaction_fadvice_e = rocksdb::Options::NORMAL;
   else if (!strcasecmp(FLAGS_compaction_fadvice.c_str(), "SEQUENTIAL"))
     FLAGS_compaction_fadvice_e = rocksdb::Options::SEQUENTIAL;
   else if (!strcasecmp(FLAGS_compaction_fadvice.c_str(), "WILLNEED"))
     FLAGS_compaction_fadvice_e = rocksdb::Options::WILLNEED;
   else {
     fprintf(stdout, "Unknown compaction fadvice:%s\n",
             FLAGS_compaction_fadvice.c_str());
   }
   FLAGS_rep_factory = StringToRepFactory(FLAGS_memtablerep.c_str());
   // The number of background threads should be at least as much the
   // max number of concurrent compactions.
   FLAGS_env->SetBackgroundThreads(FLAGS_max_background_compactions);
   // Choose a location for the test database if none given with --db=<path>
   if (FLAGS_db.empty()) {
     std::string default_db_path;
     rocksdb::Env::Default()->GetTestDirectory(&default_db_path);
     default_db_path += "/dbbench";
     FLAGS_db = default_db_path;
   }
   rocksdb::Benchmark benchmark;
   benchmark.Run();
   return 0;
 }
enum rocksdb::CompressionType StringToCompressionType (const char * ctype)
Definition at line 307 of file db_bench.cc.
References rocksdb::kBZip2Compression, rocksdb::kNoCompression, rocksdb::kSnappyCompression, and rocksdb::kZlibCompression.
Referenced by main().
{
   assert(ctype);
   if (!strcasecmp(ctype, "none"))
     return rocksdb::kNoCompression;
   else if (!strcasecmp(ctype, "snappy"))
     return rocksdb::kSnappyCompression;
   else if (!strcasecmp(ctype, "zlib"))
     return rocksdb::kZlibCompression;
   else if (!strcasecmp(ctype, "bzip2"))
     return rocksdb::kBZip2Compression;
   fprintf(stdout, "Cannot parse compression type '%s'\n", ctype);
   return rocksdb::kSnappyCompression; //default value
 }
enum RepFactory StringToRepFactory (const char * ctype)
Definition at line 442 of file db_bench.cc.
References kPrefixHash, kSkipList, kUnsorted, and kVectorRep.
Referenced by main().
{
   assert(ctype);
   if (!strcasecmp(ctype, "skip_list"))
     return kSkipList;
   else if (!strcasecmp(ctype, "prefix_hash"))
     return kPrefixHash;
   else if (!strcasecmp(ctype, "unsorted"))
     return kUnsorted;
   else if (!strcasecmp(ctype, "vector"))
     return kVectorRep;
   fprintf(stdout, "Cannot parse memreptable %s\n", ctype);
   return kSkipList;
 }
static bool ValidateCacheNumshardbits (const char * flagname, int32_t value) static
Definition at line 215 of file db_bench.cc.
{
   if (value >= 20) {
     fprintf(stderr, "Invalid value for --%s: %d, must be < 20\n",
             flagname, value);
     return false;
   }
   return true;
 }
static bool ValidateInt32Percent (const char * flagname, int32_t value) static
Definition at line 281 of file db_bench.cc.
References value.
{
   if (value <= 0 || value>=100) {
     fprintf(stderr, "Invalid value for --%s: %d, 0< pct <100 \n",
             flagname, value);
     return false;
   }
   return true;
 }
static bool ValidateKeySize (const char * flagname, int32_t value) static
Definition at line 137 of file db_bench.cc.
References kMaxKeySize.
{
   if (value > kMaxKeySize) {
     fprintf(stderr, "Invalid value for --%s: %d, must be < %d\n",
             flagname, value, kMaxKeySize);
     return false;
   }
   return true;
 }
static bool ValidatePrefixSize (const char * flagname, int32_t value) static
Definition at line 426 of file db_bench.cc.
{
   if (value < 0 || value>=2000000000) {
     fprintf(stderr, "Invalid value for --%s: %d. 0<= PrefixSize <=2000000000\n",
             flagname, value);
     return false;
   }
   return true;
 }
static bool ValidateRateLimit (const char * flagname, double value) static
Definition at line 353 of file db_bench.cc.
{
   static constexpr double EPSILON = 1e-10;
   if ( value < -EPSILON ) {
     fprintf(stderr, "Invalid value for --%s: %12.6f, must be >= 0.0\n",
             flagname, value);
     return false;
   }
   return true;
 }
static bool ValidateTableCacheNumshardbits (const char * flagname, int32_t value) static
Definition at line 332 of file db_bench.cc.
{
   if (0 >= value || value > 20) {
     fprintf(stderr, "Invalid value for --%s: %d, must be  0 < val <= 20\n",
             flagname, value);
     return false;
   }
   return true;
 }
Variable Documentation
class std::shared_ptr< rocksdb::Statistics > dbstats static
Definition at line 233 of file db_bench.cc.
Referenced by main(), rocksdb::Benchmark::Open(), rocksdb::DBImpl::PrintStatistics(), and rocksdb::Benchmark::Run().
const bool FLAGS_cache_numshardbits_dummy static
Initial value:
=
  google::RegisterFlagValidator(&FLAGS_cache_numshardbits,
                                &ValidateCacheNumshardbits)
Definition at line 478 of file db_bench.cc.
auto FLAGS_compaction_fadvice_e static
Initial value:
=
  rocksdb::Options().access_hint_on_compaction_start
Definition at line 402 of file db_bench.cc.
Referenced by main(), and rocksdb::Benchmark::Open().
rocksdb::CompactionStyle FLAGS_compaction_style_e static
Definition at line 176 of file db_bench.cc.
Referenced by rocksdb::Benchmark::Open().
enum rocksdb::CompressionType FLAGS_compression_type_e static
Initial value:
=
    rocksdb::kSnappyCompression
Definition at line 324 of file db_bench.cc.
Referenced by rocksdb::Benchmark::Open().
const bool FLAGS_deletepercent_dummy static
Initial value:
=
  google::RegisterFlagValidator(&FLAGS_deletepercent,
                                &ValidateInt32Percent)
Definition at line 486 of file db_bench.cc.
rocksdb::Env* FLAGS_env = rocksdb::Env::Default() static
Definition at line 345 of file db_bench.cc.
Referenced by rocksdb::Benchmark::Open().
const bool FLAGS_hard_rate_limit_dummy static
Initial value:
=
  google::RegisterFlagValidator(&FLAGS_hard_rate_limit, &ValidateRateLimit)
Definition at line 469 of file db_bench.cc.
const bool FLAGS_key_size_dummy static
Initial value:
=
  google::RegisterFlagValidator(&FLAGS_key_size, &ValidateKeySize)
Definition at line 475 of file db_bench.cc.
std::vector<int> FLAGS_max_bytes_for_level_multiplier_additional_v static
Definition at line 268 of file db_bench.cc.
Referenced by main(), and rocksdb::Benchmark::Open().
const bool FLAGS_prefix_size_dummy static
Initial value:
=
  google::RegisterFlagValidator(&FLAGS_prefix_size, &ValidatePrefixSize)
Definition at line 472 of file db_bench.cc.
const bool FLAGS_readwritepercent_dummy static
Initial value:
=
  google::RegisterFlagValidator(&FLAGS_readwritepercent,
                                &ValidateInt32Percent)
Definition at line 482 of file db_bench.cc.
enum RepFactory FLAGS_rep_factory static
Definition at line 457 of file db_bench.cc.
const bool FLAGS_soft_rate_limit_dummy static
Initial value:
=
  google::RegisterFlagValidator(&FLAGS_soft_rate_limit,
                                &ValidateRateLimit)
Definition at line 465 of file db_bench.cc.
const bool FLAGS_table_cache_numshardbits_dummy static
Initial value:
=
  google::RegisterFlagValidator(&FLAGS_table_cache_numshardbits,
                                &ValidateTableCacheNumshardbits)
Definition at line 490 of file db_bench.cc.
const int kMaxKeySize = 128 static
Definition at line 136 of file db_bench.cc.
Referenced by rocksdb::Benchmark::GenerateKeyFromInt(), and ValidateKeySize().