rippled: ripple::SNTPClientImp Class Reference
ripple::SNTPClientImp Class Reference
Classes
class SNTPQuery
Public Member Functions
SNTPClientImp (Stoppable &parent)
~SNTPClientImp ()
void onStart ()
void onStop ()
void run ()
void init (const std::vector< std::string > &servers)
void addServer (const std::string &server)
void queryAll ()
bool getOffset (int &offset)
bool doQuery ()
void resolveComplete (const boost::system::error_code &error, boost::asio::ip::udp::resolver::iterator it)
void receivePacket (const boost::system::error_code &error, std::size_t bytes_xferd)
void sendComplete (const boost::system::error_code &error, std::size_t)
void processReply ()
void timerEntry (const boost::system::error_code &error)
Public Member Functions inherited from ripple::SNTPClient
virtual ~SNTPClient ()
Public Member Functions inherited from beast::Stoppable
Stoppable (char const *name, Stoppable &parent)
virtual ~Stoppable ()
bool isStopping () const
bool isStopped () const
bool areChildrenStopped () const
void stopped ()
virtual void onPrepare ()
virtual void onChildrenStopped ()
Public Member Functions inherited from beast::Thread
Thread (const String &threadName)
virtual ~Thread ()
void startThread ()
void startThread (int priority)
bool stopThread (int timeOutMilliseconds=-1)
void stopThreadAsync ()
bool isThreadRunning () const
void signalThreadShouldExit ()
bool threadShouldExit () const
bool waitForThreadToExit (int timeOutMilliseconds=-1) const
bool setPriority (int priority)
void setAffinityMask (std::uint32_t affinityMask)
bool wait (int timeOutMilliseconds=-1) const
void notify () const
ThreadID getThreadId () const noexcept
const String & getThreadName () const
Private Types
typedef RippleMutex LockType
typedef std::lock_guard< LockType > ScopedLockType
Private Attributes
LockType mLock
boost::asio::io_service m_io_service
std::map
< boost::asio::ip::udp::endpoint,
SNTPQuery > mQueries
boost::asio::ip::udp::socket mSocket
boost::asio::deadline_timer mTimer
boost::asio::ip::udp::resolver mResolver
std::vector< std::pair
< std::string, time_t > > mServers
int mOffset
time_t mLastOffsetUpdate
std::list< int > mOffsetList
std::vector< uint8_t > mReceiveBuffer
boost::asio::ip::udp::endpoint mReceiveEndpoint
Additional Inherited Members
Public Types inherited from beast::Thread
typedef void * ThreadID
Static Public Member Functions inherited from ripple::SNTPClient
static SNTPClient * New (beast::Stoppable &parent)
Static Public Member Functions inherited from beast::Thread
static bool setCurrentThreadPriority (int priority)
static void setCurrentThreadAffinityMask (std::uint32_t affinityMask)
static void sleep (int milliseconds)
static void yield ()
static ThreadID getCurrentThreadId ()
static Thread * getCurrentThread ()
static void setCurrentThreadName (const String &newThreadName)
Protected Member Functions inherited from ripple::SNTPClient
SNTPClient (beast::Stoppable &parent)
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Protected Attributes inherited from beast::Stoppable
char const * m_name
RootStoppable & m_root
Child m_child
Atomic< int > m_started
bool volatile m_stopped
bool volatile m_childrenStopped
Children m_children
WaitableEvent m_stoppedEvent
Detailed Description
Definition at line 58 of file SNTPClient.cpp.
Member Typedef Documentation
typedef RippleMutex ripple::SNTPClientImp::LockType private
Definition at line 342 of file SNTPClient.cpp.
typedef std::lock_guard<LockType> ripple::SNTPClientImp::ScopedLockType private
Definition at line 343 of file SNTPClient.cpp.
Constructor & Destructor Documentation
ripple::SNTPClientImp::SNTPClientImp (Stoppable & parent) inline explicit
Definition at line 79 of file SNTPClient.cpp.
References mReceiveBuffer, mReceiveEndpoint, mSocket, mTimer, NTP_QUERY_FREQUENCY, receivePacket(), and timerEntry().
         : SNTPClient (parent)
         , Thread ("SNTPClient")
         , mSocket (m_io_service)
         , mTimer (m_io_service)
         , mResolver (m_io_service)
         , mOffset (0)
         , mLastOffsetUpdate ((time_t) - 1)
         , mReceiveBuffer (256)
     {
         mSocket.open (boost::asio::ip::udp::v4 ());
         mSocket.async_receive_from (boost::asio::buffer (mReceiveBuffer, 256),
             mReceiveEndpoint, boost::bind (
                 &SNTPClientImp::receivePacket, this,
                     boost::asio::placeholders::error,
                         boost::asio::placeholders::bytes_transferred));
         mTimer.expires_from_now (boost::posix_time::seconds (NTP_QUERY_FREQUENCY));
         mTimer.async_wait (boost::bind (&SNTPClientImp::timerEntry, this, boost::asio::placeholders::error));
     }
ripple::SNTPClientImp::~SNTPClientImp () inline
Definition at line 101 of file SNTPClient.cpp.
References beast::Thread::stopThread().
     {
         stopThread ();
     }
Member Function Documentation
void ripple::SNTPClientImp::addServer (const std::string & server) inline virtual
Implements ripple::SNTPClient.
Definition at line 143 of file SNTPClient.cpp.
References mLock, and mServers.
Referenced by init().
     {
         ScopedLockType sl (mLock);
         mServers.push_back (std::make_pair (server, (time_t) - 1));
     }
bool ripple::SNTPClientImp::doQuery () inline
Definition at line 166 of file SNTPClient.cpp.
References ripple::lsTRACE, mLock, mResolver, mServers, NTP_MIN_QUERY, resolveComplete(), and WriteLog.
Referenced by queryAll(), and timerEntry().
     {
         ScopedLockType sl (mLock);
         std::vector< std::pair<std::string, time_t> >::iterator best = mServers.end ();
         for (std::vector< std::pair<std::string, time_t> >::iterator it = mServers.begin (), end = best;
                 it != end; ++it)
             if ((best == end) || (it->second == (time_t) - 1) || (it->second < best->second))
                 best = it;
         if (best == mServers.end ())
         {
             WriteLog (lsTRACE, SNTPClient) << "SNTP: No server to query";
             return false;
         }
         time_t now = time (nullptr);
         if ((best->second != (time_t) - 1) && ((best->second + NTP_MIN_QUERY) >= now))
         {
             WriteLog (lsTRACE, SNTPClient) << "SNTP: All servers recently queried";
             return false;
         }
         best->second = now;
         boost::asio::ip::udp::resolver::query query (boost::asio::ip::udp::v4 (), best->first, "ntp");
         mResolver.async_resolve (query,
                                  boost::bind (&SNTPClientImp::resolveComplete, this,
                                               boost::asio::placeholders::error, boost::asio::placeholders::iterator));
     #ifdef SNTP_DEBUG
         WriteLog (lsTRACE, SNTPClient) << "SNTP: Resolve pending for " << best->first;
     #endif
         return true;
     }
bool ripple::SNTPClientImp::getOffset (int & offset) inline virtual
Implements ripple::SNTPClient.
Definition at line 155 of file SNTPClient.cpp.
References mLastOffsetUpdate, mLock, mOffset, and NTP_TIMESTAMP_VALID.
     {
         ScopedLockType sl (mLock);
         if ((mLastOffsetUpdate == (time_t) - 1) || ((mLastOffsetUpdate + NTP_TIMESTAMP_VALID) < time (nullptr)))
             return false;
         offset = mOffset;
         return true;
     }
void ripple::SNTPClientImp::init (const std::vector< std::string > & servers) inline virtual
Implements ripple::SNTPClient.
Definition at line 128 of file SNTPClient.cpp.
References addServer(), ripple::lsINFO, queryAll(), and WriteLog.
     {
         std::vector<std::string>::const_iterator it = servers.begin ();
         if (it == servers.end ())
         {
             WriteLog (lsINFO, SNTPClient) << "SNTP: no server specified";
             return;
         }
         BOOST_FOREACH (const std::string & it, servers)
         addServer (it);
         queryAll ();
     }
void ripple::SNTPClientImp::onStart () inline virtual
Override called during start.
Reimplemented from beast::Stoppable.
Definition at line 108 of file SNTPClient.cpp.
References beast::Thread::startThread().
     {
         startThread ();
     }
void ripple::SNTPClientImp::onStop () inline virtual
Override called when the stop notification is issued.
The call is made on an unspecified, implementation-specific thread. onStop and onChildrenStopped will never be called concurrently, across all Stoppable objects descended from the same root, inclusive of the root.
It is safe to call isStopping, isStopped, and areChildrenStopped from within this function; The values returned will always be valid and never change during the callback.
The default implementation simply calls stopped(). This is applicable when the Stoppable has a trivial stop operation (or no stop operation), and we are merely using the Stoppable API to position it as a dependency of some parent service.
Thread safety: May not block for long periods. Guaranteed only to be called once. Must be safe to call from any thread at any time.
Reimplemented from beast::Stoppable.
Definition at line 113 of file SNTPClient.cpp.
References m_io_service.
     {
         // HACK!
         m_io_service.stop ();
     }
void ripple::SNTPClientImp::processReply () inline
Definition at line 278 of file SNTPClient.cpp.
References CondLog, ripple::lsINFO, ripple::lsTRACE, mLastOffsetUpdate, mOffset, mOffsetList, mReceiveBuffer, mReceiveEndpoint, NTP_OFF_INFO, NTP_OFF_RECVTS_INT, NTP_SAMPLE_WINDOW, NTP_UNIX_OFFSET, and WriteLog.
Referenced by receivePacket().
     {
         assert (mReceiveBuffer.size () >= 48);
         std::uint32_t* recvBuffer = reinterpret_cast<std::uint32_t*> (&mReceiveBuffer.front ());
         unsigned info = ntohl (recvBuffer[NTP_OFF_INFO]);
         int64_t timev = ntohl (recvBuffer[NTP_OFF_RECVTS_INT]);
         unsigned stratum = (info >> 16) & 0xff;
         if ((info >> 30) == 3)
         {
             WriteLog (lsINFO, SNTPClient) << "SNTP: Alarm condition " << mReceiveEndpoint;
             return;
         }
         if ((stratum == 0) || (stratum > 14))
         {
             WriteLog (lsINFO, SNTPClient) << "SNTP: Unreasonable stratum (" << stratum << ") from " << mReceiveEndpoint;
             return;
         }
         std::int64_t now = static_cast<int> (time (nullptr));
         timev -= now;
         timev -= NTP_UNIX_OFFSET;
         // add offset to list, replacing oldest one if appropriate
         mOffsetList.push_back (timev);
         if (mOffsetList.size () >= NTP_SAMPLE_WINDOW)
             mOffsetList.pop_front ();
         mLastOffsetUpdate = now;
         // select median time
         std::list<int> offsetList = mOffsetList;
         offsetList.sort ();
         int j = offsetList.size ();
         std::list<int>::iterator it = offsetList.begin ();
         for (int i = 0; i < (j / 2); ++i)
             ++it;
         mOffset = *it;
         if ((j % 2) == 0)
             mOffset = (mOffset + (*--it)) / 2;
         if ((mOffset == -1) || (mOffset == 1)) // small corrections likely do more harm than good
             mOffset = 0;
         CondLog (timev || mOffset, lsTRACE, SNTPClient) << "SNTP: Offset is " << timev << ", new system offset is " << mOffset;
     }
void ripple::SNTPClientImp::queryAll () inline virtual
Implements ripple::SNTPClient.
Definition at line 149 of file SNTPClient.cpp.
References doQuery(), and nothing.
Referenced by init().
     {
         while (doQuery ())
             nothing ();
     }
void ripple::SNTPClientImp::receivePacket (const boost::system::error_code & error, std::size_t bytes_xferd) inline
Definition at line 238 of file SNTPClient.cpp.
References ripple::lsDEBUG, ripple::lsTRACE, ripple::lsWARNING, mLock, mQueries, mReceiveBuffer, mReceiveEndpoint, mSocket, NTP_OFF_ORGTS_FRAC, processReply(), and WriteLog.
Referenced by SNTPClientImp().
     {
         if (!error)
         {
             ScopedLockType sl (mLock);
     #ifdef SNTP_DEBUG
             WriteLog (lsTRACE, SNTPClient) << "SNTP: Packet from " << mReceiveEndpoint;
     #endif
             std::map<boost::asio::ip::udp::endpoint, SNTPQuery>::iterator query = mQueries.find (mReceiveEndpoint);
             if (query == mQueries.end ())
                 WriteLog (lsDEBUG, SNTPClient) << "SNTP: Reply from " << mReceiveEndpoint << " found without matching query";
             else if (query->second.mReceivedReply)
                 WriteLog (lsDEBUG, SNTPClient) << "SNTP: Duplicate response from " << mReceiveEndpoint;
             else
             {
                 query->second.mReceivedReply = true;
                 if (time (nullptr) > (query->second.mLocalTimeSent + 1))
                     WriteLog (lsWARNING, SNTPClient) << "SNTP: Late response from " << mReceiveEndpoint;
                 else if (bytes_xferd < 48)
                     WriteLog (lsWARNING, SNTPClient) << "SNTP: Short reply from " << mReceiveEndpoint
                                                      << " (" << bytes_xferd << ") " << mReceiveBuffer.size ();
                 else if (reinterpret_cast<std::uint32_t*> (&mReceiveBuffer[0])[NTP_OFF_ORGTS_FRAC] != query->second.mQueryNonce)
                     WriteLog (lsWARNING, SNTPClient) << "SNTP: Reply from " << mReceiveEndpoint << "had wrong nonce";
                 else
                     processReply ();
             }
         }
         mSocket.async_receive_from (boost::asio::buffer (mReceiveBuffer, 256), mReceiveEndpoint,
                                     boost::bind (&SNTPClientImp::receivePacket, this, boost::asio::placeholders::error,
                                             boost::asio::placeholders::bytes_transferred));
     }
void ripple::SNTPClientImp::resolveComplete (const boost::system::error_code & error, boost::asio::ip::udp::resolver::iterator it) inline
Definition at line 202 of file SNTPClient.cpp.
References ripple::RandomNumbers::fill(), ripple::RandomNumbers::getInstance(), ripple::lsTRACE, ripple::SNTPClientImp::SNTPQuery::mLocalTimeSent, mLock, mQueries, ripple::SNTPClientImp::SNTPQuery::mQueryNonce, ripple::SNTPClientImp::SNTPQuery::mReceivedReply, mSocket, NTP_OFF_XMITTS_FRAC, NTP_OFF_XMITTS_INT, NTP_UNIX_OFFSET, rand, sendComplete(), ripple::SNTPQueryData, and WriteLog.
Referenced by doQuery().
     {
         if (!error)
         {
             boost::asio::ip::udp::resolver::iterator sel = it;
             int i = 1;
             while (++it != boost::asio::ip::udp::resolver::iterator ())
                 if ((rand () % ++i) == 0)
                     sel = it;
             if (sel != boost::asio::ip::udp::resolver::iterator ())
             {
                 ScopedLockType sl (mLock);
                 SNTPQuery& query = mQueries[*sel];
                 time_t now = time (nullptr);
                 if ((query.mLocalTimeSent == now) || ((query.mLocalTimeSent + 1) == now))
                 {
                     // This can happen if the same IP address is reached through multiple names
                     WriteLog (lsTRACE, SNTPClient) << "SNTP: Redundant query suppressed";
                     return;
                 }
                 query.mReceivedReply = false;
                 query.mLocalTimeSent = now;
                 RandomNumbers::getInstance ().fill (&query.mQueryNonce);
                 reinterpret_cast<std::uint32_t*> (SNTPQueryData)[NTP_OFF_XMITTS_INT] = static_cast<std::uint32_t> (time (nullptr)) + NTP_UNIX_OFFSET;
                 reinterpret_cast<std::uint32_t*> (SNTPQueryData)[NTP_OFF_XMITTS_FRAC] = query.mQueryNonce;
                 mSocket.async_send_to (boost::asio::buffer (SNTPQueryData, 48), *sel,
                                        boost::bind (&SNTPClientImp::sendComplete, this,
                                                     boost::asio::placeholders::error, boost::asio::placeholders::bytes_transferred));
             }
         }
     }
void ripple::SNTPClientImp::run () inline virtual
Must be implemented to perform the thread's actual code.
Remember that the thread must regularly check the threadShouldExit() method whilst running, and if this returns true it should return from the run() method as soon as possible to avoid being forcibly killed.
See Also
threadShouldExit, startThread
Implements beast::Thread.
Definition at line 119 of file SNTPClient.cpp.
References m_io_service, and beast::Stoppable::stopped().
     {
         m_io_service.run ();
         stopped ();
     }
void ripple::SNTPClientImp::sendComplete (const boost::system::error_code & error, std::size_t) inline
Definition at line 273 of file SNTPClient.cpp.
References CondLog, and ripple::lsWARNING.
Referenced by resolveComplete().
     {
         CondLog (error, lsWARNING, SNTPClient) << "SNTP: Send error";
     }
void ripple::SNTPClientImp::timerEntry (const boost::system::error_code & error) inline
Definition at line 331 of file SNTPClient.cpp.
References doQuery(), mTimer, and NTP_QUERY_FREQUENCY.
Referenced by SNTPClientImp().
     {
         if (!error)
         {
             doQuery ();
             mTimer.expires_from_now (boost::posix_time::seconds (NTP_QUERY_FREQUENCY));
             mTimer.async_wait (boost::bind (&SNTPClientImp::timerEntry, this, boost::asio::placeholders::error));
         }
     }
Member Data Documentation
boost::asio::io_service ripple::SNTPClientImp::m_io_service private
Definition at line 346 of file SNTPClient.cpp.
Referenced by onStop(), and run().
time_t ripple::SNTPClientImp::mLastOffsetUpdate private
Definition at line 356 of file SNTPClient.cpp.
Referenced by getOffset(), and processReply().
LockType ripple::SNTPClientImp::mLock private
Definition at line 344 of file SNTPClient.cpp.
Referenced by addServer(), doQuery(), getOffset(), receivePacket(), and resolveComplete().
int ripple::SNTPClientImp::mOffset private
Definition at line 355 of file SNTPClient.cpp.
Referenced by getOffset(), and processReply().
std::list<int> ripple::SNTPClientImp::mOffsetList private
Definition at line 357 of file SNTPClient.cpp.
Referenced by processReply().
std::map<boost::asio::ip::udp::endpoint, SNTPQuery> ripple::SNTPClientImp::mQueries private
Definition at line 347 of file SNTPClient.cpp.
Referenced by receivePacket(), and resolveComplete().
std::vector<uint8_t> ripple::SNTPClientImp::mReceiveBuffer private
Definition at line 359 of file SNTPClient.cpp.
Referenced by processReply(), receivePacket(), and SNTPClientImp().
boost::asio::ip::udp::endpoint ripple::SNTPClientImp::mReceiveEndpoint private
Definition at line 360 of file SNTPClient.cpp.
Referenced by processReply(), receivePacket(), and SNTPClientImp().
boost::asio::ip::udp::resolver ripple::SNTPClientImp::mResolver private
Definition at line 351 of file SNTPClient.cpp.
Referenced by doQuery().
std::vector< std::pair<std::string, time_t> > ripple::SNTPClientImp::mServers private
Definition at line 353 of file SNTPClient.cpp.
Referenced by addServer(), and doQuery().
boost::asio::ip::udp::socket ripple::SNTPClientImp::mSocket private
Definition at line 349 of file SNTPClient.cpp.
Referenced by receivePacket(), resolveComplete(), and SNTPClientImp().
boost::asio::deadline_timer ripple::SNTPClientImp::mTimer private
Definition at line 350 of file SNTPClient.cpp.
Referenced by SNTPClientImp(), and timerEntry().
The documentation for this class was generated from the following file:
rippled/src/ripple_net/basics/SNTPClient.cpp