rippled: std::detail Namespace Reference
std::detail Namespace Reference
Classes
struct compile_time_all
struct compile_time_all<>
struct compile_time_all< Arg0, Argn...>
struct sizeof_workaround
struct index_tuple
struct build_index_tuple
struct build_index_tuple< 0 >
struct make_integer_sequence
struct make_integer_sequence< T, N, index_tuple< Ints...> >
Functions
template<class Pred , class FwdIt1 , class FwdIt2 >
bool equal (FwdIt1 first1, FwdIt1 last1, FwdIt2 first2, FwdIt2 last2, Pred pred, std::input_iterator_tag, std::input_iterator_tag)
template<class Pred , class RanIt1 , class RanIt2 >
bool equal (RanIt1 first1, RanIt1 last1, RanIt2 first2, RanIt2 last2, Pred pred, random_access_iterator_tag, random_access_iterator_tag)
Function Documentation
template<class Pred , class FwdIt1 , class FwdIt2 > bool std::detail::equal (FwdIt1 first1, FwdIt1 last1, FwdIt2 first2, FwdIt2 last2, Pred pred, std::input_iterator_tag , std::input_iterator_tag)
Definition at line 35 of file algorithm.h.
Referenced by beast::buffer_view_test::check(), ripple::ECDSACanonical_test::convertNonCanonical(), ripple::operator==(), beast::asio::operator==(), beast::operator==(), beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::operator==(), beast::buffer_view_test::testAssign(), beast::aged_associative_container_test_base::testChronological(), and beast::buffer_view_test::testConstruct().
 {
     for (; first1 != last1 && first2 != last2; ++first1, ++first2)
         if (! pred (*first1, *first2))
             return false;
     return first1 == last1 && first2 == last2;
 }
template<class Pred , class RanIt1 , class RanIt2 > bool std::detail::equal (RanIt1 first1, RanIt1 last1, RanIt2 first2, RanIt2 last2, Pred pred, random_access_iterator_tag , random_access_iterator_tag)
Definition at line 46 of file algorithm.h.
 {
     if (std::distance (first1, last1) !=
             std::distance (first2, last2))
         return false;
     for (; first1 != last1; ++first1, ++first2)
         if (! pred (*first1, *first2))
             return false;
     return true;
 }