rippled: beast::unit_test::detail Namespace Reference
beast::unit_test::detail Namespace Reference
Classes
class print_test
struct global_suite_instance
Functions
BEAST_DEFINE_TESTSUITE_MANUAL (print, unit_test, beast)
suite_list & global_suites ()
Function Documentation
beast::unit_test::detail::BEAST_DEFINE_TESTSUITE_MANUAL (print , unit_test , beast)
suite_list& beast::unit_test::detail::global_suites () inline
Definition at line 33 of file global_suites.h.
Referenced by beast::unit_test::detail::global_suite_instance< Suite >::global_suite_instance(), beast::unit_test::global_suites(), beast::unit_test::detail::print_test::run(), and ripple::runUnitTests().
 {
     static suite_list s;
     return s;
 }