rippled: ripple::SerializedValidation Class Reference
ripple::SerializedValidation Class Reference
#include <SerializedValidation.h>
Public Types
enum { kFullFlag = 0x1 }
typedef boost::shared_ptr
< SerializedValidation > pointer
typedef const
boost::shared_ptr
< SerializedValidation > & ref
Public Types inherited from ripple::STObject
typedef boost::ptr_vector
< SerializedType >::iterator iterator
typedef boost::ptr_vector
< SerializedType >
::const_iterator const_iterator
Public Member Functions
SerializedValidation (SerializerIterator &sit, bool checkSignature=true)
SerializedValidation (uint256 const &ledgerHash, std::uint32_t signTime, const RippleAddress &raPub, bool isFull)
uint256 getLedgerHash () const
std::uint32_t getSignTime () const
std::uint32_t getFlags () const
RippleAddress getSignerPublic () const
uint160 getNodeID () const
bool isValid () const
bool isFull () const
bool isTrusted () const
uint256 getSigningHash () const
bool isValid (uint256 const &) const
void setTrusted ()
Blob getSigned () const
Blob getSignature () const
void sign (uint256 &signingHash, const RippleAddress &raPrivate)
void sign (const RippleAddress &raPrivate)
uint256 const & getPreviousHash ()
bool isPreviousHash (uint256 const &h) const
void setPreviousHash (uint256 const &h)
Public Member Functions inherited from ripple::STObject
STObject ()
STObject (SField::ref name)
STObject (const SOTemplate &type, SField::ref name)
STObject (const SOTemplate &type, SerializerIterator &sit, SField::ref name)
STObject (SField::ref name, boost::ptr_vector< SerializedType > &data)
std::unique_ptr< STObject > oClone () const
virtual ~STObject ()
bool setType (const SOTemplate &type)
bool isValidForType ()
bool isFieldAllowed (SField::ref)
bool isFree () const
void set (const SOTemplate &)
bool set (SerializerIterator &u, int depth=0)
virtual SerializedTypeID getSType () const
virtual bool isEquivalent (const SerializedType &t) const
virtual bool isDefault () const
virtual void add (Serializer &s) const
void add (Serializer &s, bool withSignature) const
Serializer getSerializer () const
std::string getFullText () const
std::string getText () const
virtual Json::Value getJson (int options) const
int addObject (const SerializedType &t)
int giveObject (std::unique_ptr< SerializedType > t)
int giveObject (SerializedType *t)
const boost::ptr_vector
< SerializedType > & peekData () const
boost::ptr_vector
< SerializedType > & peekData ()
SerializedType & front ()
const SerializedType & front () const
SerializedType & back ()
const SerializedType & back () const
int getCount () const
bool setFlag (std::uint32_t)
bool clearFlag (std::uint32_t)
bool isFlag (std::uint32_t) const
std::uint32_t getFlags () const
uint256 getHash (std::uint32_t prefix) const
uint256 getSigningHash (std::uint32_t prefix) const
const SerializedType & peekAtIndex (int offset) const
SerializedType & getIndex (int offset)
const SerializedType * peekAtPIndex (int offset) const
SerializedType * getPIndex (int offset)
int getFieldIndex (SField::ref field) const
SField::ref getFieldSType (int index) const
const SerializedType & peekAtField (SField::ref field) const
SerializedType & getField (SField::ref field)
const SerializedType * peekAtPField (SField::ref field) const
SerializedType * getPField (SField::ref field, bool createOkay=false)
std::string getFieldString (SField::ref field) const
unsigned char getFieldU8 (SField::ref field) const
std::uint16_t getFieldU16 (SField::ref field) const
std::uint32_t getFieldU32 (SField::ref field) const
std::uint64_t getFieldU64 (SField::ref field) const
uint128 getFieldH128 (SField::ref field) const
uint160 getFieldH160 (SField::ref field) const
uint256 getFieldH256 (SField::ref field) const
RippleAddress getFieldAccount (SField::ref field) const
uint160 getFieldAccount160 (SField::ref field) const
Blob getFieldVL (SField::ref field) const
const STAmount & getFieldAmount (SField::ref field) const
const STPathSet & getFieldPathSet (SField::ref field) const
const STVector256 & getFieldV256 (SField::ref field) const
const STArray & getFieldArray (SField::ref field) const
void setFieldU8 (SField::ref field, unsigned char)
void setFieldU16 (SField::ref field, std::uint16_t)
void setFieldU32 (SField::ref field, std::uint32_t)
void setFieldU64 (SField::ref field, std::uint64_t)
void setFieldH128 (SField::ref field, const uint128 &)
void setFieldH160 (SField::ref field, const uint160 &)
void setFieldH256 (SField::ref field, uint256 const &)
void setFieldVL (SField::ref field, Blob const &)
void setFieldAccount (SField::ref field, const uint160 &)
void setFieldAccount (SField::ref field, const RippleAddress &addr)
void setFieldAmount (SField::ref field, const STAmount &)
void setFieldPathSet (SField::ref field, const STPathSet &)
void setFieldV256 (SField::ref field, const STVector256 &v)
STObject & peekFieldObject (SField::ref field)
bool isFieldPresent (SField::ref field) const
SerializedType * makeFieldPresent (SField::ref field)
void makeFieldAbsent (SField::ref field)
bool delField (SField::ref field)
void delField (int index)
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
bool empty () const
bool hasMatchingEntry (const SerializedType &)
bool operator== (const STObject &o) const
bool operator!= (const STObject &o) const
Public Member Functions inherited from ripple::SerializedType
SerializedType ()
SerializedType (SField::ref n)
virtual ~SerializedType ()
void setFName (SField::ref n)
SField::ref getFName () const
std::string getName () const
std::unique_ptr< SerializedType > clone () const
void addFieldID (Serializer &s) const
SerializedType & operator= (const SerializedType &t)
bool operator== (const SerializedType &t) const
bool operator!= (const SerializedType &t) const
template<class D >
D & downcast ()
template<class D >
D const & downcast () const
Public Member Functions inherited from ripple::CountedObject< STObject >
CountedObject ()
CountedObject (CountedObject const &)
~CountedObject ()
Public Member Functions inherited from ripple::CountedObject< SerializedValidation >
CountedObject ()
CountedObject (CountedObject const &)
~CountedObject ()
Static Public Member Functions
static char const * getCountedObjectName ()
Static Public Member Functions inherited from ripple::STObject
static char const * getCountedObjectName ()
static std::unique_ptr
< SerializedType > deserialize (SerializerIterator &sit, SField::ref name)
static std::unique_ptr
< SerializedType > makeDefaultObject (SerializedTypeID id, SField::ref name)
static std::unique_ptr
< SerializedType > makeDeserializedObject (SerializedTypeID id, SField::ref name, SerializerIterator &, int depth)
static std::unique_ptr
< SerializedType > makeNonPresentObject (SField::ref name)
static std::unique_ptr
< SerializedType > makeDefaultObject (SField::ref name)
Static Public Member Functions inherited from ripple::SerializedType
static std::unique_ptr
< SerializedType > deserialize (SField::ref name)
Private Member Functions
void setNode ()
Static Private Member Functions
static SOTemplate const & getFormat ()
Private Attributes
uint256 mPreviousHash
uint160 mNodeID
bool mTrusted
Additional Inherited Members
Protected Attributes inherited from ripple::SerializedType
SField::ptr fName
Detailed Description
Definition at line 28 of file SerializedValidation.h.
Member Typedef Documentation
typedef boost::shared_ptr<SerializedValidation> ripple::SerializedValidation::pointer
Definition at line 35 of file SerializedValidation.h.
typedef const boost::shared_ptr<SerializedValidation>& ripple::SerializedValidation::ref
Definition at line 36 of file SerializedValidation.h.
Member Enumeration Documentation
anonymous enum
Enumerator
kFullFlag
Definition at line 38 of file SerializedValidation.h.
     {
         kFullFlag = 0x1
     };
Constructor & Destructor Documentation
ripple::SerializedValidation::SerializedValidation (SerializerIterator & sit, bool checkSignature = true)
Definition at line 22 of file SerializedValidation.cpp.
References ripple::RippleAddress::createNodePublic(), ripple::STObject::getFieldVL(), ripple::STObject::getJson(), ripple::RippleAddress::getNodeID(), ripple::base_uint< BITS >::isNonZero(), isValid(), rocksdb::Log(), ripple::lsTRACE, and mNodeID.
     : STObject (getFormat (), sit, sfValidation)
     , mTrusted (false)
 {
     mNodeID = RippleAddress::createNodePublic (getFieldVL (sfSigningPubKey)).getNodeID ();
     assert (mNodeID.isNonZero ());
     if  (checkSignature && !isValid ())
     {
         Log (lsTRACE) << "Invalid validation " << getJson (0);
         throw std::runtime_error ("Invalid validation");
     }
 }
ripple::SerializedValidation::SerializedValidation (uint256 const & ledgerHash, std::uint32_t signTime, const RippleAddress & raPub, bool isFull)
Definition at line 36 of file SerializedValidation.cpp.
References ripple::RippleAddress::getNodeID(), ripple::RippleAddress::getNodePublic(), kFullFlag, mNodeID, ripple::STObject::setFieldH256(), ripple::STObject::setFieldU32(), ripple::STObject::setFieldVL(), and ripple::STObject::setFlag().
     : STObject (getFormat (), sfValidation)
     , mTrusted (false)
 {
     // Does not sign
     setFieldH256 (sfLedgerHash, ledgerHash);
     setFieldU32 (sfSigningTime, signTime);
     setFieldVL (sfSigningPubKey, raPub.getNodePublic ());
     mNodeID = raPub.getNodeID ();
     assert (mNodeID.isNonZero ());
     if (!isFull)
         setFlag (kFullFlag);
 }
Member Function Documentation
static char const* ripple::SerializedValidation::getCountedObjectName () inline static
Definition at line 33 of file SerializedValidation.h.
 { return "SerializedValidation"; }
std::uint32_t ripple::SerializedValidation::getFlags (void) const
Definition at line 85 of file SerializedValidation.cpp.
References ripple::STObject::getFieldU32().
Referenced by isFull(), and isValid().
 {
     return getFieldU32 (sfFlags);
 }
SOTemplate const & ripple::SerializedValidation::getFormat () static private
Definition at line 136 of file SerializedValidation.cpp.
References ripple::SOTemplate::push_back(), ripple::SOE_OPTIONAL, and ripple::SOE_REQUIRED.
 {
     struct FormatHolder
     {
         SOTemplate format;
         FormatHolder ()
         {
             format.push_back (SOElement (sfFlags,           SOE_REQUIRED));
             format.push_back (SOElement (sfLedgerHash,      SOE_REQUIRED));
             format.push_back (SOElement (sfLedgerSequence,  SOE_OPTIONAL));
             format.push_back (SOElement (sfCloseTime,       SOE_OPTIONAL));
             format.push_back (SOElement (sfLoadFee,         SOE_OPTIONAL));
             format.push_back (SOElement (sfFeatures,        SOE_OPTIONAL));
             format.push_back (SOElement (sfBaseFee,         SOE_OPTIONAL));
             format.push_back (SOElement (sfReserveBase,     SOE_OPTIONAL));
             format.push_back (SOElement (sfReserveIncrement, SOE_OPTIONAL));
             format.push_back (SOElement (sfSigningTime,     SOE_REQUIRED));
             format.push_back (SOElement (sfSigningPubKey,   SOE_REQUIRED));
             format.push_back (SOElement (sfSignature,       SOE_OPTIONAL));
         }
     };
     static FormatHolder holder;
     return holder.format;
 }
uint256 ripple::SerializedValidation::getLedgerHash () const
Definition at line 75 of file SerializedValidation.cpp.
References ripple::STObject::getFieldH256().
Referenced by ripple::PeerImp::checkValidation().
 {
     return getFieldH256 (sfLedgerHash);
 }
uint160 ripple::SerializedValidation::getNodeID () const inline
Definition at line 54 of file SerializedValidation.h.
References mNodeID.
     {
         return mNodeID;
     }
uint256 const& ripple::SerializedValidation::getPreviousHash () inline
Definition at line 77 of file SerializedValidation.h.
References mPreviousHash.
     {
         return mPreviousHash;
     }
Blob ripple::SerializedValidation::getSignature () const
Definition at line 124 of file SerializedValidation.cpp.
References ripple::STObject::getFieldVL().
 {
     return getFieldVL (sfSignature);
 }
Blob ripple::SerializedValidation::getSigned () const
Definition at line 129 of file SerializedValidation.cpp.
References ripple::STObject::add(), and ripple::Serializer::peekData().
 {
     Serializer s;
     add (s);
     return s.peekData ();
 }
RippleAddress ripple::SerializedValidation::getSignerPublic () const
Definition at line 112 of file SerializedValidation.cpp.
References ripple::STObject::getFieldVL(), and ripple::RippleAddress::setNodePublic().
Referenced by ripple::PeerImp::checkValidation().
 {
     RippleAddress a;
     a.setNodePublic (getFieldVL (sfSigningPubKey));
     return a;
 }
uint256 ripple::SerializedValidation::getSigningHash () const
Definition at line 70 of file SerializedValidation.cpp.
References ripple::getConfig(), and ripple::STObject::getSigningHash().
Referenced by isValid(), and sign().
 {
     return STObject::getSigningHash (getConfig ().SIGN_VALIDATION);
 }
std::uint32_t ripple::SerializedValidation::getSignTime () const
Definition at line 80 of file SerializedValidation.cpp.
References ripple::STObject::getFieldU32().
 {
     return getFieldU32 (sfSigningTime);
 }
bool ripple::SerializedValidation::isFull () const
Definition at line 119 of file SerializedValidation.cpp.
References getFlags(), and kFullFlag.
 {
     return (getFlags () & kFullFlag) != 0;
 }
bool ripple::SerializedValidation::isPreviousHash (uint256 const & h) const inline
Definition at line 81 of file SerializedValidation.h.
References mPreviousHash.
     {
         return mPreviousHash == h;
     }
bool ripple::SerializedValidation::isTrusted () const inline
Definition at line 60 of file SerializedValidation.h.
References mTrusted.
Referenced by ripple::FeeVoteImpl::doVoting().
     {
         return mTrusted;
     }
bool ripple::SerializedValidation::isValid () const
Definition at line 90 of file SerializedValidation.cpp.
References getSigningHash().
Referenced by SerializedValidation().
 {
     return isValid (getSigningHash ());
 }
bool ripple::SerializedValidation::isValid (uint256 const & signingHash) const
Definition at line 95 of file SerializedValidation.cpp.
References ripple::RippleAddress::createNodePublic(), ripple::STObject::getFieldVL(), getFlags(), ripple::RippleAddress::isValid(), rocksdb::Log(), ripple::lsINFO, ripple::RippleAddress::verifyNodePublic(), and ripple::vfFullyCanonicalSig.
 {
     try
     {
         const ECDSA fullyCanonical = getFlags () & vfFullyCanonicalSig ?
                                             ECDSA::strict : ECDSA::not_strict;
         RippleAddress   raPublicKey = RippleAddress::createNodePublic (getFieldVL (sfSigningPubKey));
         return raPublicKey.isValid () &&
             raPublicKey.verifyNodePublic (signingHash, getFieldVL (sfSignature), fullyCanonical);
     }
     catch (...)
     {
         Log (lsINFO) << "exception validating validation";
         return false;
     }
 }
void ripple::SerializedValidation::setNode () private
void ripple::SerializedValidation::setPreviousHash (uint256 const & h) inline
Definition at line 85 of file SerializedValidation.h.
References mPreviousHash.
     {
         mPreviousHash = h;
     }
void ripple::SerializedValidation::setTrusted () inline
Definition at line 67 of file SerializedValidation.h.
References mTrusted.
     {
         mTrusted = true;
     }
void ripple::SerializedValidation::sign (uint256 & signingHash, const RippleAddress & raPrivate)
Definition at line 60 of file SerializedValidation.cpp.
References getSigningHash(), ripple::STObject::setFieldVL(), ripple::STObject::setFlag(), ripple::RippleAddress::signNodePrivate(), and ripple::vfFullyCanonicalSig.
Referenced by sign().
 {
     setFlag (vfFullyCanonicalSig);
     signingHash = getSigningHash ();
     Blob signature;
     raPriv.signNodePrivate (signingHash, signature);
     setFieldVL (sfSignature, signature);
 }
void ripple::SerializedValidation::sign (const RippleAddress & raPrivate)
Definition at line 54 of file SerializedValidation.cpp.
References sign().
 {
     uint256 signingHash;
     sign (signingHash, raPriv);
 }
Member Data Documentation
uint160 ripple::SerializedValidation::mNodeID private
Definition at line 96 of file SerializedValidation.h.
Referenced by getNodeID(), and SerializedValidation().
uint256 ripple::SerializedValidation::mPreviousHash private
Definition at line 95 of file SerializedValidation.h.
Referenced by getPreviousHash(), isPreviousHash(), and setPreviousHash().
bool ripple::SerializedValidation::mTrusted private
Definition at line 97 of file SerializedValidation.h.
Referenced by isTrusted(), and setTrusted().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/ledger/SerializedValidation.h
rippled/src/ripple_app/ledger/SerializedValidation.cpp