rippled: ripple::STAmount_test Class Reference
ripple::STAmount_test Class Reference
Public Member Functions
bool roundTest (int n, int d, int m)
void mulTest (int a, int b)
void testSetValue ()
void testNativeCurrency ()
void testCustomCurrency ()
void testArithmetic ()
template<class Cond >
bool expect (Cond cond, beast::String const &s)
template<class Cond >
bool expect (Cond cond)
void testUnderflow ()
void testRounding ()
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Static Public Member Functions
static STAmount serializeAndDeserialize (const STAmount &s)
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 1177 of file STAmount.cpp.
Member Function Documentation
template<class Cond > bool ripple::STAmount_test::expect (Cond cond, beast::String const & s) inline
Definition at line 1695 of file STAmount.cpp.
References beast::IP::detail::expect(), and beast::String::toStdString().
Referenced by mulTest(), roundTest(), testSetValue(), and testUnderflow().
     {
         return suite::expect (cond, s.toStdString());
     }
template<class Cond > bool ripple::STAmount_test::expect (Cond cond) inline
Definition at line 1702 of file STAmount.cpp.
References beast::IP::detail::expect().
     {
         return suite::expect (cond);
     }
void ripple::STAmount_test::mulTest (int a, int b) inline
Definition at line 1229 of file STAmount.cpp.
References ACCOUNT_ONE, CURRENCY_ONE, expect(), beast::unit_test::suite::fail(), ripple::STAmount::getFullText(), ripple::STAmount::isNative(), ripple::lsWARNING, ripple::STAmount::multiply(), beast::unit_test::suite::pass(), and WriteLog.
Referenced by testArithmetic().
     {
         STAmount aa (CURRENCY_ONE, ACCOUNT_ONE, a);
         STAmount bb (CURRENCY_ONE, ACCOUNT_ONE, b);
         STAmount prod1 (STAmount::multiply (aa, bb, CURRENCY_ONE, ACCOUNT_ONE));
         expect (! prod1.isNative ());
         STAmount prod2 (CURRENCY_ONE, ACCOUNT_ONE, static_cast<std::uint64_t> (a) * static_cast<std::uint64_t> (b));
         if (prod1 != prod2)
         {
             WriteLog (lsWARNING, STAmount) << "nn(" << aa.getFullText () << " * " << bb.getFullText () << ") = " << prod1.getFullText ()
                                            << " not " << prod2.getFullText ();
             fail ("Multiplication result is not exact");
         }
         else
         {
             pass ();
         }
         aa = a;
         prod1 = STAmount::multiply (aa, bb, CURRENCY_ONE, ACCOUNT_ONE);
         if (prod1 != prod2)
         {
             WriteLog (lsWARNING, STAmount) << "n(" << aa.getFullText () << " * " << bb.getFullText () << ") = " << prod1.getFullText ()
                                            << " not " << prod2.getFullText ();
             fail ("Multiplication result is not exact");
         }
         else
         {
             pass ();
         }
     }
bool ripple::STAmount_test::roundTest (int n, int d, int m) inline
Definition at line 1193 of file STAmount.cpp.
References ACCOUNT_ONE, CURRENCY_ONE, ripple::STAmount::divide(), expect(), beast::unit_test::suite::fail(), ripple::STAmount::getText(), ripple::STAmount::isNative(), ripple::lsWARNING, ripple::STAmount::multiply(), beast::unit_test::suite::pass(), ripple::STAmount::roundSelf(), ripple::STAmount::throwComparable(), and WriteLog.
Referenced by testArithmetic().
     {
         // check STAmount rounding
         STAmount num (CURRENCY_ONE, ACCOUNT_ONE, n);
         STAmount den (CURRENCY_ONE, ACCOUNT_ONE, d);
         STAmount mul (CURRENCY_ONE, ACCOUNT_ONE, m);
         STAmount quot = STAmount::divide (n, d, CURRENCY_ONE, ACCOUNT_ONE);
         STAmount res = STAmount::multiply (quot, mul, CURRENCY_ONE, ACCOUNT_ONE);
         expect (! res.isNative (), "Product should not be native");
         res.roundSelf ();
         STAmount cmp (CURRENCY_ONE, ACCOUNT_ONE, (n * m) / d);
         expect (! cmp.isNative (), "Comparison amount should not be native");
         if (res != cmp)
         {
             cmp.throwComparable (res);
             WriteLog (lsWARNING, STAmount) << "(" << num.getText () << "/" << den.getText () << ") X " << mul.getText () << " = "
                                        << res.getText () << " not " << cmp.getText ();
             fail ("Rounding");
             return false;
         }
         else
         {
             pass ();
         }
         return true;
     }
void ripple::STAmount_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 1806 of file STAmount.cpp.
References testArithmetic(), testCustomCurrency(), testNativeCurrency(), testRounding(), testSetValue(), and testUnderflow().
     {
         testSetValue ();
         testNativeCurrency ();
         testCustomCurrency ();
         testArithmetic ();
         testUnderflow ();
         testRounding ();
     }
static STAmount ripple::STAmount_test::serializeAndDeserialize (const STAmount & s) inline static
Definition at line 1180 of file STAmount.cpp.
References ripple::STAmount::add(), and ripple::STAmount::deserialize().
Referenced by testCustomCurrency(), and testNativeCurrency().
     {
         Serializer ser;
         s.add (ser);
         SerializerIterator sit (ser);
         return STAmount::deserialize (sit);
     }
void ripple::STAmount_test::testArithmetic () inline
Definition at line 1629 of file STAmount.cpp.
References ACCOUNT_ONE, CURRENCY_ONE, beast::unit_test::suite::fail(), ripple::STAmount::getRate(), ripple::CBigNum::getuint64(), ripple::lsFATAL, mulTest(), beast::unit_test::suite::pass(), rand, roundTest(), ripple::CBigNum::setuint64(), beast::unit_test::suite::testcase(), ripple::CBigNum::ToString(), beast::unit_test::suite::unexpected(), and WriteLog.
Referenced by run().
     {
         testcase ("arithmetic");
         CBigNum b;
         for (int i = 0; i < 16; ++i)
         {
             std::uint64_t r = rand ();
             r <<= 32;
             r |= rand ();
             b.setuint64 (r);
             if (b.getuint64 () != r)
             {
                 WriteLog (lsFATAL, STAmount) << r << " != " << b.getuint64 () << " " << b.ToString (16);
                 fail ("setull64/getull64 failure");
             }
             else
             {
                 pass ();
             }
         }
         // Test currency multiplication and division operations such as
         // convertToDisplayAmount, convertToInternalAmount, getRate, getClaimed, and getNeeded
         unexpected (STAmount::getRate (STAmount (1), STAmount (10)) != (((100ull - 14) << (64 - 8)) | 1000000000000000ull),
             "STAmount getRate fail 1");
         unexpected (STAmount::getRate (STAmount (10), STAmount (1)) != (((100ull - 16) << (64 - 8)) | 1000000000000000ull),
             "STAmount getRate fail 2");
         unexpected (STAmount::getRate (STAmount (CURRENCY_ONE, ACCOUNT_ONE, 1), STAmount (CURRENCY_ONE, ACCOUNT_ONE, 10)) != (((100ull - 14) << (64 - 8)) | 1000000000000000ull),
             "STAmount getRate fail 3");
         unexpected (STAmount::getRate (STAmount (CURRENCY_ONE, ACCOUNT_ONE, 10), STAmount (CURRENCY_ONE, ACCOUNT_ONE, 1)) != (((100ull - 16) << (64 - 8)) | 1000000000000000ull),
             "STAmount getRate fail 4");
         unexpected (STAmount::getRate (STAmount (CURRENCY_ONE, ACCOUNT_ONE, 1), STAmount (10)) != (((100ull - 14) << (64 - 8)) | 1000000000000000ull),
             "STAmount getRate fail 5");
         unexpected (STAmount::getRate (STAmount (CURRENCY_ONE, ACCOUNT_ONE, 10), STAmount (1)) != (((100ull - 16) << (64 - 8)) | 1000000000000000ull),
             "STAmount getRate fail 6");
         unexpected (STAmount::getRate (STAmount (1), STAmount (CURRENCY_ONE, ACCOUNT_ONE, 10)) != (((100ull - 14) << (64 - 8)) | 1000000000000000ull),
             "STAmount getRate fail 7");
         unexpected (STAmount::getRate (STAmount (10), STAmount (CURRENCY_ONE, ACCOUNT_ONE, 1)) != (((100ull - 16) << (64 - 8)) | 1000000000000000ull),
             "STAmount getRate fail 8");
         roundTest (1, 3, 3);
         roundTest (2, 3, 9);
         roundTest (1, 7, 21);
         roundTest (1, 2, 4);
         roundTest (3, 9, 18);
         roundTest (7, 11, 44);
         for (int i = 0; i <= 100000; ++i)
             mulTest (rand () % 10000000, rand () % 10000000);
     }
void ripple::STAmount_test::testCustomCurrency () inline
Definition at line 1443 of file STAmount.cpp.
References ACCOUNT_ONE, ACCOUNT_XRP, CURRENCY_ONE, ripple::STAmount::divide(), beast::unit_test::suite::fail(), ripple::STAmount::getRate(), ripple::STAmount::getRaw(), ripple::STAmount::getText(), ripple::STAmount::isNative(), ripple::lsFATAL, ripple::STAmount::multiply(), beast::unit_test::suite::pass(), serializeAndDeserialize(), ripple::STAmount::setRate(), beast::unit_test::suite::testcase(), beast::unit_test::suite::unexpected(), and WriteLog.
Referenced by run().
     {
         testcase ("custom currency");
         STAmount zeroSt (CURRENCY_ONE, ACCOUNT_ONE), one (CURRENCY_ONE, ACCOUNT_ONE, 1), hundred (CURRENCY_ONE, ACCOUNT_ONE, 100);
         serializeAndDeserialize (one).getRaw ();
         unexpected (serializeAndDeserialize (zeroSt) != zeroSt, "STAmount fail");
         unexpected (serializeAndDeserialize (one) != one, "STAmount fail");
         unexpected (serializeAndDeserialize (hundred) != hundred, "STAmount fail");
         unexpected (zeroSt.isNative (), "STAmount fail");
         unexpected (hundred.isNative (), "STAmount fail");
         unexpected (zeroSt != zero, "STAmount fail");
         unexpected (one == zero, "STAmount fail");
         unexpected (hundred == zero, "STAmount fail");
         unexpected ((zeroSt < zeroSt), "STAmount fail");
         unexpected (! (zeroSt < one), "STAmount fail");
         unexpected (! (zeroSt < hundred), "STAmount fail");
         unexpected ((one < zeroSt), "STAmount fail");
         unexpected ((one < one), "STAmount fail");
         unexpected (! (one < hundred), "STAmount fail");
         unexpected ((hundred < zeroSt), "STAmount fail");
         unexpected ((hundred < one), "STAmount fail");
         unexpected ((hundred < hundred), "STAmount fail");
         unexpected ((zeroSt > zeroSt), "STAmount fail");
         unexpected ((zeroSt > one), "STAmount fail");
         unexpected ((zeroSt > hundred), "STAmount fail");
         unexpected (! (one > zeroSt), "STAmount fail");
         unexpected ((one > one), "STAmount fail");
         unexpected ((one > hundred), "STAmount fail");
         unexpected (! (hundred > zeroSt), "STAmount fail");
         unexpected (! (hundred > one), "STAmount fail");
         unexpected ((hundred > hundred), "STAmount fail");
         unexpected (! (zeroSt <= zeroSt), "STAmount fail");
         unexpected (! (zeroSt <= one), "STAmount fail");
         unexpected (! (zeroSt <= hundred), "STAmount fail");
         unexpected ((one <= zeroSt), "STAmount fail");
         unexpected (! (one <= one), "STAmount fail");
         unexpected (! (one <= hundred), "STAmount fail");
         unexpected ((hundred <= zeroSt), "STAmount fail");
         unexpected ((hundred <= one), "STAmount fail");
         unexpected (! (hundred <= hundred), "STAmount fail");
         unexpected (! (zeroSt >= zeroSt), "STAmount fail");
         unexpected ((zeroSt >= one), "STAmount fail");
         unexpected ((zeroSt >= hundred), "STAmount fail");
         unexpected (! (one >= zeroSt), "STAmount fail");
         unexpected (! (one >= one), "STAmount fail");
         unexpected ((one >= hundred), "STAmount fail");
         unexpected (! (hundred >= zeroSt), "STAmount fail");
         unexpected (! (hundred >= one), "STAmount fail");
         unexpected (! (hundred >= hundred), "STAmount fail");
         unexpected (! (zeroSt == zeroSt), "STAmount fail");
         unexpected ((zeroSt == one), "STAmount fail");
         unexpected ((zeroSt == hundred), "STAmount fail");
         unexpected ((one == zeroSt), "STAmount fail");
         unexpected (! (one == one), "STAmount fail");
         unexpected ((one == hundred), "STAmount fail");
         unexpected ((hundred == zeroSt), "STAmount fail");
         unexpected ((hundred == one), "STAmount fail");
         unexpected (! (hundred == hundred), "STAmount fail");
         unexpected ((zeroSt != zeroSt), "STAmount fail");
         unexpected (! (zeroSt != one), "STAmount fail");
         unexpected (! (zeroSt != hundred), "STAmount fail");
         unexpected (! (one != zeroSt), "STAmount fail");
         unexpected ((one != one), "STAmount fail");
         unexpected (! (one != hundred), "STAmount fail");
         unexpected (! (hundred != zeroSt), "STAmount fail");
         unexpected (! (hundred != one), "STAmount fail");
         unexpected ((hundred != hundred), "STAmount fail");
         unexpected (STAmount (CURRENCY_ONE, ACCOUNT_ONE).getText () != "0", "STAmount fail");
         unexpected (STAmount (CURRENCY_ONE, ACCOUNT_ONE, 31).getText () != "31", "STAmount fail");
         unexpected (STAmount (CURRENCY_ONE, ACCOUNT_ONE, 31, 1).getText () != "310", "STAmount fail");
         unexpected (STAmount (CURRENCY_ONE, ACCOUNT_ONE, 31, -1).getText () != "3.1", "STAmount fail");
         unexpected (STAmount (CURRENCY_ONE, ACCOUNT_ONE, 31, -2).getText () != "0.31", "STAmount fail");
         unexpected (STAmount::multiply (STAmount (CURRENCY_ONE, ACCOUNT_ONE, 20), STAmount (3), CURRENCY_ONE, ACCOUNT_ONE).getText () != "60",
             "STAmount multiply fail 1");
         unexpected (STAmount::multiply (STAmount (CURRENCY_ONE, ACCOUNT_ONE, 20), STAmount (3), uint160 (), ACCOUNT_XRP).getText () != "60",
             "STAmount multiply fail 2");
         unexpected (STAmount::multiply (STAmount (20), STAmount (3), CURRENCY_ONE, ACCOUNT_ONE).getText () != "60",
             "STAmount multiply fail 3");
         unexpected (STAmount::multiply (STAmount (20), STAmount (3), uint160 (), ACCOUNT_XRP).getText () != "60",
             "STAmount multiply fail 4");
         if (STAmount::divide (STAmount (CURRENCY_ONE, ACCOUNT_ONE, 60), STAmount (3), CURRENCY_ONE, ACCOUNT_ONE).getText () != "20")
         {
             WriteLog (lsFATAL, STAmount) << "60/3 = " <<
                                          STAmount::divide (STAmount (CURRENCY_ONE, ACCOUNT_ONE, 60),
                                                  STAmount (3), CURRENCY_ONE, ACCOUNT_ONE).getText ();
             fail ("STAmount divide fail");
         }
         else
         {
             pass ();
         }
         unexpected (STAmount::divide (STAmount (CURRENCY_ONE, ACCOUNT_ONE, 60), STAmount (3), uint160 (), ACCOUNT_XRP).getText () != "20",
             "STAmount divide fail");
         unexpected (STAmount::divide (STAmount (CURRENCY_ONE, ACCOUNT_ONE, 60), STAmount (CURRENCY_ONE, ACCOUNT_ONE, 3), CURRENCY_ONE, ACCOUNT_ONE).getText () != "20",
             "STAmount divide fail");
         unexpected (STAmount::divide (STAmount (CURRENCY_ONE, ACCOUNT_ONE, 60), STAmount (CURRENCY_ONE, ACCOUNT_ONE, 3), uint160 (), ACCOUNT_XRP).getText () != "20",
             "STAmount divide fail");
         STAmount a1 (CURRENCY_ONE, ACCOUNT_ONE, 60), a2 (CURRENCY_ONE, ACCOUNT_ONE, 10, -1);
         unexpected (STAmount::divide (a2, a1, CURRENCY_ONE, ACCOUNT_ONE) != STAmount::setRate (STAmount::getRate (a1, a2)),
             "STAmount setRate(getRate) fail");
         unexpected (STAmount::divide (a1, a2, CURRENCY_ONE, ACCOUNT_ONE) != STAmount::setRate (STAmount::getRate (a2, a1)),
             "STAmount setRate(getRate) fail");
     }
void ripple::STAmount_test::testNativeCurrency () inline
Definition at line 1293 of file STAmount.cpp.
References ripple::STAmount::createHumanCurrency(), ripple::STAmount::currencyFromString(), ripple::STAmount::isNative(), serializeAndDeserialize(), beast::unit_test::suite::testcase(), and beast::unit_test::suite::unexpected().
Referenced by run().
     {
         testcase ("native currency");
         STAmount zeroSt, one (1), hundred (100);
         unexpected (serializeAndDeserialize (zeroSt) != zeroSt, "STAmount fail");
         unexpected (serializeAndDeserialize (one) != one, "STAmount fail");
         unexpected (serializeAndDeserialize (hundred) != hundred, "STAmount fail");
         unexpected (!zeroSt.isNative (), "STAmount fail");
         unexpected (!hundred.isNative (), "STAmount fail");
         unexpected (zeroSt != zero, "STAmount fail");
         unexpected (one == zero, "STAmount fail");
         unexpected (hundred == zero, "STAmount fail");
         unexpected ((zeroSt < zeroSt), "STAmount fail");
         unexpected (! (zeroSt < one), "STAmount fail");
         unexpected (! (zeroSt < hundred), "STAmount fail");
         unexpected ((one < zeroSt), "STAmount fail");
         unexpected ((one < one), "STAmount fail");
         unexpected (! (one < hundred), "STAmount fail");
         unexpected ((hundred < zeroSt), "STAmount fail");
         unexpected ((hundred < one), "STAmount fail");
         unexpected ((hundred < hundred), "STAmount fail");
         unexpected ((zeroSt > zeroSt), "STAmount fail");
         unexpected ((zeroSt > one), "STAmount fail");
         unexpected ((zeroSt > hundred), "STAmount fail");
         unexpected (! (one > zeroSt), "STAmount fail");
         unexpected ((one > one), "STAmount fail");
         unexpected ((one > hundred), "STAmount fail");
         unexpected (! (hundred > zeroSt), "STAmount fail");
         unexpected (! (hundred > one), "STAmount fail");
         unexpected ((hundred > hundred), "STAmount fail");
         unexpected (! (zeroSt <= zeroSt), "STAmount fail");
         unexpected (! (zeroSt <= one), "STAmount fail");
         unexpected (! (zeroSt <= hundred), "STAmount fail");
         unexpected ((one <= zeroSt), "STAmount fail");
         unexpected (! (one <= one), "STAmount fail");
         unexpected (! (one <= hundred), "STAmount fail");
         unexpected ((hundred <= zeroSt), "STAmount fail");
         unexpected ((hundred <= one), "STAmount fail");
         unexpected (! (hundred <= hundred), "STAmount fail");
         unexpected (! (zeroSt >= zeroSt), "STAmount fail");
         unexpected ((zeroSt >= one), "STAmount fail");
         unexpected ((zeroSt >= hundred), "STAmount fail");
         unexpected (! (one >= zeroSt), "STAmount fail");
         unexpected (! (one >= one), "STAmount fail");
         unexpected ((one >= hundred), "STAmount fail");
         unexpected (! (hundred >= zeroSt), "STAmount fail");
         unexpected (! (hundred >= one), "STAmount fail");
         unexpected (! (hundred >= hundred), "STAmount fail");
         unexpected (! (zeroSt == zeroSt), "STAmount fail");
         unexpected ((zeroSt == one), "STAmount fail");
         unexpected ((zeroSt == hundred), "STAmount fail");
         unexpected ((one == zeroSt), "STAmount fail");
         unexpected (! (one == one), "STAmount fail");
         unexpected ((one == hundred), "STAmount fail");
         unexpected ((hundred == zeroSt), "STAmount fail");
         unexpected ((hundred == one), "STAmount fail");
         unexpected (! (hundred == hundred), "STAmount fail");
         unexpected ((zeroSt != zeroSt), "STAmount fail");
         unexpected (! (zeroSt != one), "STAmount fail");
         unexpected (! (zeroSt != hundred), "STAmount fail");
         unexpected (! (one != zeroSt), "STAmount fail");
         unexpected ((one != one), "STAmount fail");
         unexpected (! (one != hundred), "STAmount fail");
         unexpected (! (hundred != zeroSt), "STAmount fail");
         unexpected (! (hundred != one), "STAmount fail");
         unexpected ((hundred != hundred), "STAmount fail");
         unexpected (STAmount ().getText () != "0", "STAmount fail");
         unexpected (STAmount (31).getText () != "31", "STAmount fail");
         unexpected (STAmount (310).getText () != "310", "STAmount fail");
         unexpected (STAmount::createHumanCurrency (uint160 ()) != "XRP", "cHC(XRP)");
         uint160 c;
         unexpected (!STAmount::currencyFromString (c, "USD"), "create USD currency");
         unexpected (STAmount::createHumanCurrency (c) != "USD", "check USD currency");
         const std::string cur = "015841551A748AD2C1F76FF6ECB0CCCD00000000";
         unexpected (!STAmount::currencyFromString (c, cur), "create custom currency");
         unexpected (STAmount::createHumanCurrency (c) != cur, "check custom currency");
         unexpected (c != uint160 (cur), "check custom currency");
     }
void ripple::STAmount_test::testRounding () inline
Definition at line 1751 of file STAmount.cpp.
References ACCOUNT_ONE, ripple::STAmount::addRound(), ripple::STAmount::canonicalizeRound(), CURRENCY_ONE, ripple::STAmount::divide(), ripple::STAmount::divRound(), ripple::lsINFO, ripple::STAmount::mulRound(), ripple::STAmount::multiply(), value, and WriteLog.
Referenced by run().
     {
         // VFALCO TODO There are no actual tests here, just printed output?
         //             Change this to actually do something.
 #if 0
         beginTestCase ("rounding ");
         std::uint64_t value = 25000000000000000ull;
         int offset = -14;
         STAmount::canonicalizeRound (false, value, offset, true);
         STAmount one (CURRENCY_ONE, ACCOUNT_ONE, 1);
         STAmount two (CURRENCY_ONE, ACCOUNT_ONE, 2);
         STAmount three (CURRENCY_ONE, ACCOUNT_ONE, 3);
         STAmount oneThird1 = STAmount::divRound (one, three, CURRENCY_ONE, ACCOUNT_ONE, false);
         STAmount oneThird2 = STAmount::divide (one, three, CURRENCY_ONE, ACCOUNT_ONE);
         STAmount oneThird3 = STAmount::divRound (one, three, CURRENCY_ONE, ACCOUNT_ONE, true);
         WriteLog (lsINFO, STAmount) << oneThird1;
         WriteLog (lsINFO, STAmount) << oneThird2;
         WriteLog (lsINFO, STAmount) << oneThird3;
         STAmount twoThird1 = STAmount::divRound (two, three, CURRENCY_ONE, ACCOUNT_ONE, false);
         STAmount twoThird2 = STAmount::divide (two, three, CURRENCY_ONE, ACCOUNT_ONE);
         STAmount twoThird3 = STAmount::divRound (two, three, CURRENCY_ONE, ACCOUNT_ONE, true);
         WriteLog (lsINFO, STAmount) << twoThird1;
         WriteLog (lsINFO, STAmount) << twoThird2;
         WriteLog (lsINFO, STAmount) << twoThird3;
         STAmount oneA = STAmount::mulRound (oneThird1, three, CURRENCY_ONE, ACCOUNT_ONE, false);
         STAmount oneB = STAmount::multiply (oneThird2, three, CURRENCY_ONE, ACCOUNT_ONE);
         STAmount oneC = STAmount::mulRound (oneThird3, three, CURRENCY_ONE, ACCOUNT_ONE, true);
         WriteLog (lsINFO, STAmount) << oneA;
         WriteLog (lsINFO, STAmount) << oneB;
         WriteLog (lsINFO, STAmount) << oneC;
         STAmount fourThirdsA = STAmount::addRound (twoThird2, twoThird2, false);
         STAmount fourThirdsB = twoThird2 + twoThird2;
         STAmount fourThirdsC = STAmount::addRound (twoThird2, twoThird2, true);
         WriteLog (lsINFO, STAmount) << fourThirdsA;
         WriteLog (lsINFO, STAmount) << fourThirdsB;
         WriteLog (lsINFO, STAmount) << fourThirdsC;
         STAmount dripTest1 = STAmount::mulRound (twoThird2, two, uint160 (), uint160 (), false);
         STAmount dripTest2 = STAmount::multiply (twoThird2, two, uint160 (), uint160 ());
         STAmount dripTest3 = STAmount::mulRound (twoThird2, two, uint160 (), uint160 (), true);
         WriteLog (lsINFO, STAmount) << dripTest1;
         WriteLog (lsINFO, STAmount) << dripTest2;
         WriteLog (lsINFO, STAmount) << dripTest3;
 #endif
     }
void ripple::STAmount_test::testSetValue () inline
Definition at line 1268 of file STAmount.cpp.
References expect(), ripple::STAmount::getNValue(), ripple::STAmount::setFullValue(), SYSTEM_CURRENCY_PARTS, and beast::unit_test::suite::testcase().
Referenced by run().
     {
         testcase ("set value");
         STAmount    saTmp;
     #if 0
         // Check native floats
         saTmp.setFullValue ("1^0");
         BOOST_CHECK_MESSAGE (SYSTEM_CURRENCY_PARTS == saTmp.getNValue (), "float integer failed");
         saTmp.setFullValue ("0^1");
         BOOST_CHECK_MESSAGE (SYSTEM_CURRENCY_PARTS / 10 == saTmp.getNValue (), "float fraction failed");
         saTmp.setFullValue ("0^12");
         BOOST_CHECK_MESSAGE (12 * SYSTEM_CURRENCY_PARTS / 100 == saTmp.getNValue (), "float fraction failed");
         saTmp.setFullValue ("1^2");
         BOOST_CHECK_MESSAGE (SYSTEM_CURRENCY_PARTS + (2 * SYSTEM_CURRENCY_PARTS / 10) == saTmp.getNValue (), "float combined failed");
     #endif
         // Check native integer
         saTmp.setFullValue ("1");
         expect (1 == saTmp.getNValue (), "should be equal");
     }
void ripple::STAmount_test::testUnderflow () inline
Definition at line 1707 of file STAmount.cpp.
References ACCOUNT_ONE, ripple::STAmount::cMaxNative, ripple::STAmount::cMaxOffset, ripple::STAmount::cMaxValue, ripple::STAmount::cMinOffset, ripple::STAmount::cMinValue, CURRENCY_ONE, ripple::STAmount::divide(), expect(), ripple::STAmount::getRate(), ripple::STAmount::getText(), ripple::STAmount::multiply(), and beast::unit_test::suite::testcase().
Referenced by run().
     {
         testcase ("underflow");
         STAmount bigNative (STAmount::cMaxNative / 2);
         STAmount bigValue (CURRENCY_ONE, ACCOUNT_ONE,
                            (STAmount::cMinValue + STAmount::cMaxValue) / 2, STAmount::cMaxOffset - 1);
         STAmount smallValue (CURRENCY_ONE, ACCOUNT_ONE,
                              (STAmount::cMinValue + STAmount::cMaxValue) / 2, STAmount::cMinOffset + 1);
         STAmount zeroSt (CURRENCY_ONE, ACCOUNT_ONE, 0);
         STAmount smallXsmall = STAmount::multiply (smallValue, smallValue, CURRENCY_ONE, ACCOUNT_ONE);
         expect (smallXsmall == zero, "smallXsmall != 0");
         STAmount bigDsmall = STAmount::divide (smallValue, bigValue, CURRENCY_ONE, ACCOUNT_ONE);
         expect (bigDsmall == zero, beast::String ("small/big != 0: ") + bigDsmall.getText ());
         bigDsmall = STAmount::divide (smallValue, bigNative, CURRENCY_ONE, uint160 ());
         expect (bigDsmall == zero, beast::String ("small/bigNative != 0: ") + bigDsmall.getText ());
         bigDsmall = STAmount::divide (smallValue, bigValue, uint160 (), uint160 ());
         expect (bigDsmall == zero, beast::String ("(small/big)->N != 0: ") + bigDsmall.getText ());
         bigDsmall = STAmount::divide (smallValue, bigNative, uint160 (), uint160 ());
         expect (bigDsmall == zero, beast::String ("(small/bigNative)->N != 0: ") + bigDsmall.getText ());
         // very bad offer
         std::uint64_t r = STAmount::getRate (smallValue, bigValue);
         expect (r == 0, "getRate(smallOut/bigIn) != 0");
         // very good offer
         r = STAmount::getRate (bigValue, smallValue);
         expect (r == 0, "getRate(smallIn/bigOUt) != 0");
     }
The documentation for this class was generated from the following file:
rippled/src/ripple_data/protocol/STAmount.cpp