rippled: Json::Value::CZString Class Reference
Json::Value::CZString Class Reference
Public Types
enum DuplicationPolicy { noDuplication = 0, duplicate, duplicateOnCopy }
Public Member Functions
CZString (int index)
CZString (const char *cstr, DuplicationPolicy allocate)
CZString (const CZString &other)
~CZString ()
CZString & operator= (const CZString &other)
bool operator< (const CZString &other) const
bool operator== (const CZString &other) const
int index () const
const char * c_str () const
bool isStaticString () const
Private Member Functions
void swap (CZString &other)
Private Attributes
const char * cstr_
int index_
Detailed Description
Definition at line 141 of file json_value.h.
Member Enumeration Documentation
enum Json::Value::CZString::DuplicationPolicy
Enumerator
noDuplication
duplicate
duplicateOnCopy
Definition at line 144 of file json_value.h.
         {
             noDuplication = 0,
             duplicate,
             duplicateOnCopy
         };
Constructor & Destructor Documentation
Json::Value::CZString::CZString (int index)
Definition at line 178 of file json_value.cpp.
     : cstr_ ( 0 )
     , index_ ( index )
 {
 }
Json::Value::CZString::CZString (const char * cstr, DuplicationPolicy allocate)
Definition at line 184 of file json_value.cpp.
     : cstr_ ( allocate == duplicate ? valueAllocator ()->makeMemberName (cstr)
               : cstr )
     , index_ ( allocate )
 {
 }
Json::Value::CZString::CZString (const CZString & other)
Definition at line 191 of file json_value.cpp.
     : cstr_ ( other.index_ != noDuplication&&   other.cstr_ != 0
               ?  valueAllocator ()->makeMemberName ( other.cstr_ )
               : other.cstr_ )
     , index_ ( other.cstr_ ? (other.index_ == noDuplication ? noDuplication : duplicate)
                : other.index_ )
 {
 }
Json::Value::CZString::~CZString ()
Definition at line 200 of file json_value.cpp.
References cstr_, duplicate, index_, Json::ValueAllocator::releaseMemberName(), and Json::valueAllocator().
 {
     if ( cstr_  &&  index_ == duplicate )
         valueAllocator ()->releaseMemberName ( const_cast<char*> ( cstr_ ) );
 }
Member Function Documentation
const char * Json::Value::CZString::c_str () const
Definition at line 248 of file json_value.cpp.
 {
     return cstr_;
 }
int Json::Value::CZString::index () const
Definition at line 241 of file json_value.cpp.
 {
     return index_;
 }
bool Json::Value::CZString::isStaticString () const
Definition at line 254 of file json_value.cpp.
 {
     return index_ == noDuplication;
 }
bool Json::Value::CZString::operator< (const CZString & other) const
Definition at line 222 of file json_value.cpp.
 {
     if ( cstr_ )
         return strcmp ( cstr_, other.cstr_ ) < 0;
     return index_ < other.index_;
 }
Value::CZString & Json::Value::CZString::operator= (const CZString & other)
Definition at line 214 of file json_value.cpp.
References Json::Value::swap().
 {
     CZString temp ( other );
     swap ( temp );
     return *this;
 }
bool Json::Value::CZString::operator== (const CZString & other) const
Definition at line 231 of file json_value.cpp.
References cstr_, and index_.
 {
     if ( cstr_ )
         return strcmp ( cstr_, other.cstr_ ) == 0;
     return index_ == other.index_;
 }
void Json::Value::CZString::swap (CZString & other) private
Definition at line 207 of file json_value.cpp.
References cstr_, index_, and beast::asio::swap().
 {
     std::swap ( cstr_, other.cstr_ );
     std::swap ( index_, other.index_ );
 }
Member Data Documentation
const char* Json::Value::CZString::cstr_ private
Definition at line 162 of file json_value.h.
Referenced by operator==(), swap(), and ~CZString().
int Json::Value::CZString::index_ private
Definition at line 163 of file json_value.h.
Referenced by operator==(), swap(), and ~CZString().
The documentation for this class was generated from the following files:
rippled/src/ripple/json/api/json_value.h
rippled/src/ripple/json/impl/json_value.cpp