rippled: rocksdb::Cache Class Reference
rocksdb::Cache Class Reference abstract
#include <cache.h>
Classes
struct Handle
Public Member Functions
Cache ()
virtual ~Cache ()
virtual Handle * Insert (const Slice &key, void *value, size_t charge, void(*deleter)(const Slice &key, void *value))=0
virtual Handle * Lookup (const Slice &key)=0
virtual void Release (Handle *handle)=0
virtual void * Value (Handle *handle)=0
virtual void Erase (const Slice &key)=0
virtual uint64_t NewId ()=0
virtual size_t GetCapacity ()=0
Private Member Functions
void LRU_Remove (Handle *e)
void LRU_Append (Handle *e)
void Unref (Handle *e)
Cache (const Cache &)
void operator= (const Cache &)
Private Attributes
Rep * rep_
Detailed Description
Definition at line 52 of file cache.h.
Constructor & Destructor Documentation
rocksdb::Cache::Cache () inline
Definition at line 54 of file cache.h.
 { }
rocksdb::Cache::~Cache () virtual
Definition at line 22 of file cache.cc.
               {
 }
rocksdb::Cache::Cache (const Cache &) private
Member Function Documentation
virtual void rocksdb::Cache::Erase (const Slice & key) pure virtual
virtual size_t rocksdb::Cache::GetCapacity () pure virtual
virtual Handle* rocksdb::Cache::Insert (const Slice & key, void * value, size_t charge, void(*)(const Slice &key, void *value) deleter) pure virtual
Referenced by rocksdb::BlockBasedTable::BlockReader(), rocksdb::BlockBasedTable::GetBlock(), rocksdb::BlockBasedTable::GetFilter(), and rocksdb::BlockBasedTableBuilder::InsertBlockInCache().
virtual Handle* rocksdb::Cache::Lookup (const Slice & key) pure virtual
Referenced by rocksdb::BlockBasedTable::BlockReader().
void rocksdb::Cache::LRU_Append (Handle * e) private
void rocksdb::Cache::LRU_Remove (Handle * e) private
virtual uint64_t rocksdb::Cache::NewId () pure virtual
void rocksdb::Cache::operator= (const Cache &) private
virtual void rocksdb::Cache::Release (Handle * handle) pure virtual
Referenced by rocksdb::BlockBasedTable::BlockReader(), rocksdb::BlockBasedTableBuilder::InsertBlockInCache(), rocksdb::BlockBasedTable::CachableEntry< TValue >::Release(), and rocksdb::UnrefEntry().
void rocksdb::Cache::Unref (Handle * e) private
virtual void* rocksdb::Cache::Value (Handle * handle) pure virtual
Referenced by rocksdb::BlockBasedTable::BlockReader(), rocksdb::BlockBasedTable::GetBlock(), and rocksdb::BlockBasedTable::GetFilter().
Member Data Documentation
Rep* rocksdb::Cache::rep_ private
Definition at line 112 of file cache.h.
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/include/rocksdb/cache.h
rippled/src/ripple/rocksdb/rocksdb/util/cache.cc