rippled: Json::Value::CommentInfo Struct Reference
Json::Value::CommentInfo Struct Reference
Public Member Functions
CommentInfo ()
~CommentInfo ()
void setComment (const char *text)
Public Attributes
char * comment_
Detailed Description
Definition at line 418 of file json_value.h.
Constructor & Destructor Documentation
Json::Value::CommentInfo::CommentInfo ()
Definition at line 141 of file json_value.cpp.
     : comment_ ( 0 )
 {
 }
Json::Value::CommentInfo::~CommentInfo ()
Definition at line 146 of file json_value.cpp.
References Json::ValueAllocator::releaseStringValue(), and Json::valueAllocator().
 {
     if ( comment_ )
         valueAllocator ()->releaseStringValue ( comment_ );
 }
Member Function Documentation
void Json::Value::CommentInfo::setComment (const char * text)
Definition at line 154 of file json_value.cpp.
References Json::ValueAllocator::releaseStringValue(), and Json::valueAllocator().
Referenced by Json::Value::setComment(), and Json::Value::Value().
 {
     if ( comment_ )
         valueAllocator ()->releaseStringValue ( comment_ );
     JSON_ASSERT ( text );
     JSON_ASSERT_MESSAGE ( text[0] == '\0' || text[0] == '/', "Comments must start with /");
     // It seems that /**/ style comments are acceptable as well.
     comment_ = valueAllocator ()->duplicateStringValue ( text );
 }
Member Data Documentation
char* Json::Value::CommentInfo::comment_
Definition at line 425 of file json_value.h.
Referenced by Json::Value::getComment(), Json::Value::hasComment(), and Json::Value::Value().
The documentation for this struct was generated from the following files:
rippled/src/ripple/json/api/json_value.h
rippled/src/ripple/json/impl/json_value.cpp