rippled: rocksdb::LogReporter Struct Reference
rocksdb::LogReporter Struct Reference
#include <transaction_log_impl.h>
Public Member Functions
virtual void Corruption (size_t bytes, const Status &s)
virtual void Info (const char *s)
Public Member Functions inherited from rocksdb::log::Reader::Reporter
virtual ~Reporter ()
Public Attributes
Env * env
Logger * info_log
Detailed Description
Definition at line 19 of file transaction_log_impl.h.
Member Function Documentation
virtual void rocksdb::LogReporter::Corruption (size_t bytes, const Status & s) inline virtual
Implements rocksdb::log::Reader::Reporter.
Definition at line 22 of file transaction_log_impl.h.
References info_log, rocksdb::Log(), and rocksdb::Status::ToString().
Referenced by rocksdb::TransactionLogIteratorImpl::NextImpl(), rocksdb::DBImpl::ReadFirstLine(), rocksdb::DBImpl::RecoverLogFile(), and rocksdb::TransactionLogIteratorImpl::SeekToStartSequence().
{
     Log(info_log, "dropping %zu bytes; %s", bytes, s.ToString().c_str());
   }
virtual void rocksdb::LogReporter::Info (const char * s) inline virtual
Definition at line 25 of file transaction_log_impl.h.
References info_log, and rocksdb::Log().
Referenced by rocksdb::TransactionLogIteratorImpl::IsBatchExpected(), and rocksdb::TransactionLogIteratorImpl::SeekToStartSequence().
{
     Log(info_log, "%s", s);
   }
Member Data Documentation
Env* rocksdb::LogReporter::env
Definition at line 20 of file transaction_log_impl.h.
Referenced by rocksdb::DBImpl::ReadFirstLine(), rocksdb::DBImpl::RecoverLogFile(), and rocksdb::TransactionLogIteratorImpl::TransactionLogIteratorImpl().
Logger* rocksdb::LogReporter::info_log
Definition at line 21 of file transaction_log_impl.h.
Referenced by Corruption(), Info(), rocksdb::DBImpl::ReadFirstLine(), rocksdb::DBImpl::RecoverLogFile(), and rocksdb::TransactionLogIteratorImpl::TransactionLogIteratorImpl().
The documentation for this struct was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/db/transaction_log_impl.h