rippled: beast::sqdb::detail::standard_use_type Class Reference
beast::sqdb::detail::standard_use_type Class Reference
#include <use_type.h>
Public Member Functions
standard_use_type (void *data, exchange_type type, bool bReadOnly)
standard_use_type (void *data, exchange_type type, indicator &ind, bool bReadOnly)
virtual ~standard_use_type ()
virtual void bind (statement_imp &st, int &iParam)
virtual void do_use ()
virtual void post_use ()
virtual void clean_up ()
virtual void convert_to_base ()
virtual void convert_from_base ()
Public Member Functions inherited from beast::sqdb::detail::use_type_base
virtual ~use_type_base ()
Private Member Functions
void clean_up_backend ()
Private Attributes
void * m_data
exchange_type m_type
indicator * m_ind
bool m_bReadOnly
statement_imp * m_st
int m_iParam
Detailed Description
Definition at line 82 of file use_type.h.
Constructor & Destructor Documentation
beast::sqdb::detail::standard_use_type::standard_use_type (void * data, exchange_type type, bool bReadOnly) inline
Definition at line 85 of file use_type.h.
         : m_data(data), m_type(type), m_ind(0), m_bReadOnly(bReadOnly) {}
beast::sqdb::detail::standard_use_type::standard_use_type (void * data, exchange_type type, indicator & ind, bool bReadOnly) inline
Definition at line 87 of file use_type.h.
         : m_data(data), m_type(type), m_ind(&ind), m_bReadOnly(bReadOnly) {}
beast::sqdb::detail::standard_use_type::~standard_use_type () virtual
Definition at line 66 of file use_type.cpp.
 {
 }
Member Function Documentation
void beast::sqdb::detail::standard_use_type::bind (statement_imp & st, int & iParam) virtual
Implements beast::sqdb::detail::use_type_base.
Definition at line 70 of file use_type.cpp.
References m_iParam, and m_st.
 {
     m_st = &st;
     m_iParam = iParam++;
 }
void beast::sqdb::detail::standard_use_type::clean_up () virtual
Implements beast::sqdb::detail::use_type_base.
Definition at line 222 of file use_type.cpp.
 {
 }
void beast::sqdb::detail::standard_use_type::clean_up_backend () private
virtual void beast::sqdb::detail::standard_use_type::convert_from_base () inline virtual
Reimplemented in beast::sqdb::detail::conversion_use_type< T >.
Definition at line 96 of file use_type.h.
Referenced by post_use().
 {}
virtual void beast::sqdb::detail::standard_use_type::convert_to_base () inline virtual
Reimplemented in beast::sqdb::detail::conversion_use_type< T >.
Definition at line 95 of file use_type.h.
Referenced by do_use().
 {}
void beast::sqdb::detail::standard_use_type::do_use () virtual
Implements beast::sqdb::detail::use_type_base.
Definition at line 96 of file use_type.cpp.
References convert_to_base(), m_data, m_iParam, m_st, beast::sqdb::detail::statement_imp::m_stmt, m_type, sqlite3_bind_double, sqlite3_bind_int, sqlite3_bind_int64, sqlite3_bind_null, sqlite3_bind_text, sqlite3_bind_text16, SQLITE_OK, SQLITE_STATIC, beast::sqdb::detail::sqliteError(), beast::String::toUTF8(), beast::sqdb::detail::x_beastString, beast::sqdb::detail::x_blob, beast::sqdb::detail::x_bool, beast::sqdb::detail::x_char, beast::sqdb::detail::x_cstring, beast::sqdb::detail::x_cwstring, beast::sqdb::detail::x_double, beast::sqdb::detail::x_float, beast::sqdb::detail::x_int, beast::sqdb::detail::x_long, beast::sqdb::detail::x_longdouble, beast::sqdb::detail::x_longlong, beast::sqdb::detail::x_null, beast::sqdb::detail::x_short, beast::sqdb::detail::x_stdstring, beast::sqdb::detail::x_stdtm, beast::sqdb::detail::x_stdwstring, beast::sqdb::detail::x_uchar, beast::sqdb::detail::x_uint, beast::sqdb::detail::x_ulong, beast::sqdb::detail::x_ulonglong, and beast::sqdb::detail::x_ushort.
 {
     int result = SQLITE_OK;
     convert_to_base();
     switch (m_type)
     {
     case x_null:
         result = sqlite3_bind_null(m_st->m_stmt, m_iParam);
         break;
     case x_bool:
         result = sqlite3_bind_int(m_st->m_stmt, m_iParam, as <bool> (m_data) ? 1 : 0);
         break;
     case x_char:
         result = sqlite3_bind_int(m_st->m_stmt, m_iParam, as <char> (m_data));
         break;
     case x_uchar:
         result = sqlite3_bind_int(m_st->m_stmt, m_iParam, as <unsigned char> (m_data));
         break;
     case x_short:
         result = sqlite3_bind_int(m_st->m_stmt, m_iParam, as <short> (m_data));
         break;
     case x_ushort:
         result = sqlite3_bind_int(m_st->m_stmt, m_iParam, as <unsigned short> (m_data));
         break;
     case x_int:
         result = sqlite3_bind_int(m_st->m_stmt, m_iParam, as <int> (m_data));
         break;
     case x_uint:
         result = sqlite3_bind_int64(m_st->m_stmt, m_iParam, as <unsigned int> (m_data));
         break;
     case x_long:
         result = sqlite3_bind_int(m_st->m_stmt, m_iParam, as <long> (m_data));
         break;
     case x_ulong:
         result = sqlite3_bind_int64(m_st->m_stmt, m_iParam, as <unsigned long> (m_data));
         break;
     case x_longlong:
         result = sqlite3_bind_int64(m_st->m_stmt, m_iParam, as <long long> (m_data));
         break;
     case x_ulonglong:
         result = sqlite3_bind_int64(m_st->m_stmt, m_iParam, as <unsigned long long> (m_data));
         break;
     case x_float:
         result = sqlite3_bind_double(m_st->m_stmt, m_iParam, as <float> (m_data));
         break;
     case x_double:
         result = sqlite3_bind_double(m_st->m_stmt, m_iParam, as <double> (m_data));
         break;
 #if 0
     case x_longdouble:
         result = sqlite3_bind_double(m_st->m_stmt, m_iParam, as <long double> (m_data));
         break;
 #endif
     case x_cstring:
         result = sqlite3_bind_text(m_st->m_stmt, m_iParam, as <char*> (m_data), -1, SQLITE_STATIC);
         break;
     case x_cwstring:
         result = sqlite3_bind_text16(m_st->m_stmt, m_iParam, as <wchar_t*> (m_data), -1, SQLITE_STATIC);
         break;
     case x_stdstring:
     {
         std::string const& s = as <std::string> (m_data);
         result = sqlite3_bind_text(m_st->m_stmt,
                                    m_iParam,
                                    s.c_str(),
                                    int(s.size() * sizeof(s[0])),
                                    SQLITE_STATIC);
     }
     break;
     case x_stdwstring:
     {
         std::wstring const& s = as <std::wstring> (m_data);
         result = sqlite3_bind_text16(m_st->m_stmt,
                                      m_iParam,
                                      s.c_str(),
                                      int(s.size() * sizeof(s[0])),
                                      SQLITE_STATIC);
     }
     break;
     case x_beastString:
     {
         String const& s = as <String> (m_data);
         result = sqlite3_bind_text(m_st->m_stmt,
                                    m_iParam,
                                    s.toUTF8(),
                                    -1,
                                    SQLITE_STATIC);
     }
     break;
     case x_stdtm:
     case x_blob:
     default:
         throw std::invalid_argument ("bad parameter");
     }
     if (result != SQLITE_OK)
         throw detail::sqliteError(__FILE__, __LINE__, result);
 }
void beast::sqdb::detail::standard_use_type::post_use () virtual
Implements beast::sqdb::detail::use_type_base.
Definition at line 217 of file use_type.cpp.
References convert_from_base().
 {
     convert_from_base();
 }
Member Data Documentation
bool beast::sqdb::detail::standard_use_type::m_bReadOnly private
Definition at line 105 of file use_type.h.
void* beast::sqdb::detail::standard_use_type::m_data private
Definition at line 102 of file use_type.h.
Referenced by do_use().
indicator* beast::sqdb::detail::standard_use_type::m_ind private
Definition at line 104 of file use_type.h.
int beast::sqdb::detail::standard_use_type::m_iParam private
Definition at line 107 of file use_type.h.
Referenced by bind(), and do_use().
statement_imp* beast::sqdb::detail::standard_use_type::m_st private
Definition at line 106 of file use_type.h.
Referenced by bind(), and do_use().
exchange_type beast::sqdb::detail::standard_use_type::m_type private
Definition at line 103 of file use_type.h.
Referenced by do_use().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_sqdb/detail/use_type.h
rippled/src/beast/modules/beast_sqdb/source/use_type.cpp