rippled: beast::SemanticVersion Class Reference
beast::SemanticVersion Class Reference
#include <SemanticVersion.h>
Public Member Functions
SemanticVersion ()
bool parse (String input)
String print () const
bool isRelease () const noexcept
bool isPreRelease () const noexcept
int compare (SemanticVersion const &rhs) const noexcept
bool operator== (SemanticVersion const &other) const noexcept
bool operator!= (SemanticVersion const &other) const noexcept
bool operator>= (SemanticVersion const &other) const noexcept
bool operator<= (SemanticVersion const &other) const noexcept
bool operator> (SemanticVersion const &other) const noexcept
bool operator< (SemanticVersion const &other) const noexcept
Public Attributes
int majorVersion
int minorVersion
int patchVersion
StringArray preReleaseIdentifiers
StringArray metaData
Static Private Member Functions
static bool isNumeric (String const &s)
static String printIdentifiers (StringArray const &list)
static bool chop (String const &what, String &input)
static bool chopUInt (int *value, int limit, String &input)
static bool chopIdentifier (String *value, bool allowLeadingZeroes, String &input)
static bool chopIdentifiers (StringArray *value, bool preRelease, String &input)
Detailed Description
A Semantic Version number.
Identifies the build of a particular version of software using the Semantic Versioning Specification described here:
http://semver.org/
Definition at line 33 of file SemanticVersion.h.
Constructor & Destructor Documentation
beast::SemanticVersion::SemanticVersion ()
Definition at line 24 of file SemanticVersion.cpp.
     : majorVersion (0)
     , minorVersion (0)
     , patchVersion (0)
 {
 }
Member Function Documentation
bool beast::SemanticVersion::chop (String const & what, String & input) static private
Definition at line 174 of file SemanticVersion.cpp.
References beast::String::length(), beast::String::startsWith(), and beast::String::substring().
Referenced by chopIdentifiers(), and parse().
 {
     if (input.startsWith (what))
     {
         input = input.substring (what.length ());
         return true;
     }
     return false;
 }
bool beast::SemanticVersion::chopIdentifier (String * value, bool allowLeadingZeroes, String & input) static private
Definition at line 237 of file SemanticVersion.cpp.
References beast::String::charToString(), beast::String::contains(), beast::String::length(), and beast::String::substring().
Referenced by chopIdentifiers().
 {
     // Must not be empty
     if (input.length () <= 0)
         return false;
     // Must not have a leading 0
     if (! allowLeadingZeroes && input [0] == '0')
         return false;
     // Find the first character that cannot be part of an identifier
     int i;
     for (i = 0; i < input.length (); ++i)
     {
         static char const* validSet =
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-";
         if (! String (validSet).contains (String::charToString (input [i])))
             break;
     }
     // Must not be empty
     if (i <= 0)
         return false;
     *value = input.substring (0, i);
     input = input.substring (i);
     return true;
 }
bool beast::SemanticVersion::chopIdentifiers (StringArray * value, bool preRelease, String & input) static private
Definition at line 269 of file SemanticVersion.cpp.
References beast::StringArray::add(), chop(), chopIdentifier(), and beast::String::length().
Referenced by parse().
 {
     if (input.length () <= 0)
         return false;
     for (;;)
     {
         String s;
         if (! chopIdentifier (&s, allowLeadingZeroes, input))
             return false;
         value->add (s);
         if (! chop (".", input))
             break;
     }
     return true;
 }
bool beast::SemanticVersion::chopUInt (int * value, int limit, String & input) static private
Definition at line 201 of file SemanticVersion.cpp.
References beast::String::getIntValue(), beast::CharacterFunctions::isDigit(), beast::String::length(), and beast::String::substring().
Referenced by parse().
 {
     // Must not be empty
     if (input.length () <= 0)
         return false;
     int firstNonDigit = 0;
     for (; firstNonDigit < input.length (); ++firstNonDigit)
     {
         if (! CharacterFunctions::isDigit (input [firstNonDigit]))
             break;
     }
     String const s = input.substring (0, firstNonDigit);
     // Must not be empty
     if (s.length () <= 0)
         return false;
     int const n = s.getIntValue ();
     // Must not have leading zeroes
     if (String (n) != s)
         return false;
     // Must not be out of range
     if (n < 0 || n > limit)
         return false;
     input = input.substring (s.length ());
     *value = n;
     return true;
 }
int beast::SemanticVersion::compare (SemanticVersion const & rhs) const noexcept
Compare this against another version. The comparison follows the rules as per the specification.
Definition at line 97 of file SemanticVersion.cpp.
References bassert, beast::bmax(), beast::String::compareLexicographically(), and beast::String::getIntValue().
Referenced by beast::SemanticVersion_test::checkLessInternal(), operator!=(), operator<(), operator<=(), operator==(), operator>(), and operator>=().
 {
     if (majorVersion > rhs.majorVersion)
         return 1;
     else if (majorVersion < rhs.majorVersion)
         return -1;
     if (minorVersion > rhs.minorVersion)
         return 1;
     else if (minorVersion < rhs.minorVersion)
         return -1;
     if (patchVersion > rhs.patchVersion)
         return 1;
     else if (patchVersion < rhs.patchVersion)
         return -1;
     if (isPreRelease () || rhs.isPreRelease ())
     {
         // Pre-releases have a lower precedence
         if (isRelease () && rhs.isPreRelease ())
             return 1;
         else if (isPreRelease () && rhs.isRelease ())
             return -1;
         // Compare pre-release identifiers
         for (int i = 0; i < bmax (preReleaseIdentifiers.size (), rhs.preReleaseIdentifiers.size ()); ++i)
         {
             // A larger list of identifiers has a higher precedence
             if (i >= rhs.preReleaseIdentifiers.size ())
                 return 1;
             else if (i >= preReleaseIdentifiers.size ())
                 return -1;
             String const& left (preReleaseIdentifiers [i]);
             String const& right (rhs.preReleaseIdentifiers [i]);
             // Numeric identifiers have lower precedence
             if (! isNumeric (left) && isNumeric (right))
                 return 1;
             else if (isNumeric (left) && ! isNumeric (right))
                 return -1;
             if (isNumeric (left))
             {
                 bassert (isNumeric (right));
                 int const iLeft (left.getIntValue ());
                 int const iRight (right.getIntValue ());
                 if (iLeft > iRight)
                     return 1;
                 else if (iLeft < iRight)
                     return -1;
             }
             else
             {
                 bassert (! isNumeric (right));
                 int result = left.compareLexicographically (right);
                 if (result != 0)
                     return result;
             }
         }
     }
     // metadata is ignored
     return 0;
 }
bool beast::SemanticVersion::isNumeric (String const & s) static private
Definition at line 169 of file SemanticVersion.cpp.
References beast::String::getIntValue().
 {
     return String (s.getIntValue ()) == s;
 }
bool beast::SemanticVersion::isPreRelease () const inline noexcept
Definition at line 54 of file SemanticVersion.h.
References isRelease().
 { return ! isRelease (); }
bool beast::SemanticVersion::isRelease () const inline noexcept
Definition at line 53 of file SemanticVersion.h.
References preReleaseIdentifiers, and beast::StringArray::size().
Referenced by isPreRelease().
 { return preReleaseIdentifiers.size () <= 0; }
bool beast::SemanticVersion::operator!= (SemanticVersion const & other) const inline noexcept
Definition at line 62 of file SemanticVersion.h.
References compare().
 { return compare (other) != 0; }
bool beast::SemanticVersion::operator< (SemanticVersion const & other) const inline noexcept
Definition at line 66 of file SemanticVersion.h.
References compare().
 { return compare (other) <  0; }
bool beast::SemanticVersion::operator<= (SemanticVersion const & other) const inline noexcept
Definition at line 64 of file SemanticVersion.h.
References compare().
 { return compare (other) <= 0; }
bool beast::SemanticVersion::operator== (SemanticVersion const & other) const inline noexcept
Definition at line 61 of file SemanticVersion.h.
References compare().
 { return compare (other) == 0; }
bool beast::SemanticVersion::operator> (SemanticVersion const & other) const inline noexcept
Definition at line 65 of file SemanticVersion.h.
References compare().
 { return compare (other) >  0; }
bool beast::SemanticVersion::operator>= (SemanticVersion const & other) const inline noexcept
Definition at line 63 of file SemanticVersion.h.
References compare().
 { return compare (other) >= 0; }
bool beast::SemanticVersion::parse (String input)
Parse a semantic version string. The parsing is as strict as possible.
Returns
true if the string was parsed.
Definition at line 31 of file SemanticVersion.cpp.
References chop(), chopIdentifiers(), chopUInt(), beast::String::length(), majorVersion, ripple::max(), metaData, minorVersion, patchVersion, preReleaseIdentifiers, beast::StringArray::size(), and beast::String::trim().
Referenced by beast::SemanticVersion_test::checkLessInternal(), beast::SemanticVersion_test::checkPass(), beast::SemanticVersion_test::checkValues(), ripple::version::checkVersion(), ripple::BuildInfo::getVersionString(), and ripple::BuildInfo_test::testVersion().
 {
     // May not have leading or trailing whitespace
     if (input.trim () != input)
         return false;
     // Must have major version number
     if (! chopUInt (&majorVersion, std::numeric_limits <int>::max (), input))
         return false;
     if (! chop (".", input))
         return false;
     // Must have minor version number
     if (! chopUInt (&minorVersion, std::numeric_limits <int>::max (), input))
         return false;
     if (! chop (".", input))
         return false;
     // Must have patch version number
     if (! chopUInt (&patchVersion, std::numeric_limits <int>::max (), input))
         return false;
     // May have pre-release identifier list
     if (chop ("-", input))
     {
         chopIdentifiers (&preReleaseIdentifiers, false, input);
         // Must not be empty
         if (preReleaseIdentifiers.size () <= 0)
             return false;
     }
     // May have metadata identifier list
     if (chop ("+", input))
     {
         chopIdentifiers (&metaData, true, input);
         // Must not be empty
         if (metaData.size () <= 0)
             return false;
     }
     // May not have anything left
     if (input.length () > 0)
         return false;
     return true;
 }
String beast::SemanticVersion::print () const
Produce a string from semantic version components.
Definition at line 82 of file SemanticVersion.cpp.
References majorVersion, metaData, minorVersion, patchVersion, preReleaseIdentifiers, printIdentifiers(), and beast::StringArray::size().
Referenced by beast::SemanticVersion_test::checkPass(), and ripple::BuildInfo::getVersionString().
 {
     String s;
     s << String (majorVersion) << "." << String (minorVersion) << "." << String (patchVersion);
     if (preReleaseIdentifiers.size () > 0)
         s << "-" << printIdentifiers (preReleaseIdentifiers);
     if (metaData.size () > 0)
         s << "+" << printIdentifiers (metaData);
     return s;
 }
String beast::SemanticVersion::printIdentifiers (StringArray const & list) static private
Definition at line 186 of file SemanticVersion.cpp.
References beast::StringArray::size().
Referenced by print().
 {
     String s;
     if (list.size () > 0)
     {
         s << list [0];
         for (int i = 1; i < list.size (); ++i)
             s << "." << list [i];
     }
     return s;
 }
Member Data Documentation
int beast::SemanticVersion::majorVersion
Definition at line 36 of file SemanticVersion.h.
Referenced by beast::SemanticVersion_test::checkValues(), parse(), and print().
StringArray beast::SemanticVersion::metaData
Definition at line 40 of file SemanticVersion.h.
Referenced by beast::SemanticVersion_test::checkValues(), parse(), and print().
int beast::SemanticVersion::minorVersion
Definition at line 37 of file SemanticVersion.h.
Referenced by beast::SemanticVersion_test::checkValues(), parse(), and print().
int beast::SemanticVersion::patchVersion
Definition at line 38 of file SemanticVersion.h.
Referenced by beast::SemanticVersion_test::checkValues(), parse(), and print().
StringArray beast::SemanticVersion::preReleaseIdentifiers
Definition at line 39 of file SemanticVersion.h.
Referenced by beast::SemanticVersion_test::checkValues(), isRelease(), parse(), and print().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_core/diagnostic/SemanticVersion.h
rippled/src/beast/modules/beast_core/diagnostic/SemanticVersion.cpp