rippled: ripple::NodeStore::LevelDBBackend Class Reference
ripple::NodeStore::LevelDBBackend Class Reference
Public Member Functions
LevelDBBackend (int keyBytes, Parameters const &keyValues, Scheduler &scheduler, beast::Journal journal)
std::string getName ()
Status fetch (void const *key, NodeObject::Ptr *pObject)
void store (NodeObject::ref object)
void storeBatch (Batch const &batch)
void visitAll (VisitCallback &callback)
int getWriteLoad ()
void writeBatch (Batch const &batch)
Public Member Functions inherited from ripple::NodeStore::Backend
virtual ~Backend ()=0
virtual void store (NodeObject::Ptr const &object)=0
Public Attributes
beast::Journal m_journal
size_t const m_keyBytes
Scheduler & m_scheduler
BatchWriter m_batch
std::string m_name
std::unique_ptr< leveldb::DB > m_db
Detailed Description
Definition at line 23 of file LevelDBFactory.cpp.
Constructor & Destructor Documentation
ripple::NodeStore::LevelDBBackend::LevelDBBackend (int keyBytes, Parameters const & keyValues, Scheduler & scheduler, beast::Journal journal) inline
Definition at line 36 of file LevelDBFactory.cpp.
References db, ripple::getConfig(), m_db, m_name, rocksdb::NewBloomFilterPolicy(), rocksdb::NewLRUCache(), and ripple::siHashNodeDBCache.
         : m_journal (journal)
         , m_keyBytes (keyBytes)
         , m_scheduler (scheduler)
         , m_batch (*this, scheduler)
         , m_name (keyValues ["path"].toStdString ())
     {
         if (m_name.empty())
             throw std::runtime_error ("Missing path in LevelDBFactory backend");
         leveldb::Options options;
         options.create_if_missing = true;
         if (keyValues["cache_mb"].isEmpty())
         {
             options.block_cache = leveldb::NewLRUCache (getConfig ().getSize (siHashNodeDBCache) * 1024 * 1024);
         }
         else
         {
             options.block_cache = leveldb::NewLRUCache (keyValues["cache_mb"].getIntValue() * 1024L * 1024L);
         }
         if (keyValues["filter_bits"].isEmpty())
         {
             if (getConfig ().NODE_SIZE >= 2)
                 options.filter_policy = leveldb::NewBloomFilterPolicy (10);
         }
         else if (keyValues["filter_bits"].getIntValue() != 0)
         {
             options.filter_policy = leveldb::NewBloomFilterPolicy (keyValues["filter_bits"].getIntValue());
         }
         if (! keyValues["open_files"].isEmpty())
         {
             options.max_open_files = keyValues["open_files"].getIntValue();
         }
         leveldb::DB* db = nullptr;
         leveldb::Status status = leveldb::DB::Open (options, m_name, &db);
         if (!status.ok () || !db)
             throw std::runtime_error (std::string("Unable to open/create leveldb: ") + status.ToString());
         m_db.reset (db);
     }
Member Function Documentation
Status ripple::NodeStore::LevelDBBackend::fetch (void const * key, NodeObject::Ptr * pObject) inline virtual
Fetch a single object. If the object is not found or an error is encountered, the result will indicate the condition.
Note
This will be called concurrently.
Parameters
key A pointer to the key data.
pObject [out] The created object if successful.
Returns
The result of the operation.
Implements ripple::NodeStore::Backend.
Definition at line 89 of file LevelDBFactory.cpp.
References ripple::NodeStore::DecodedBlob::createObject(), ripple::NodeStore::dataCorrupt, m_db, m_keyBytes, ripple::NodeStore::notFound, ripple::NodeStore::ok, ripple::NodeStore::unknown, and ripple::NodeStore::DecodedBlob::wasOk().
     {
         pObject->reset ();
         Status status (ok);
         leveldb::ReadOptions const options;
         leveldb::Slice const slice (static_cast <char const*> (key), m_keyBytes);
         std::string string;
         leveldb::Status getStatus = m_db->Get (options, slice, &string);
         if (getStatus.ok ())
         {
             DecodedBlob decoded (key, string.data (), string.size ());
             if (decoded.wasOk ())
             {
                 *pObject = decoded.createObject ();
             }
             else
             {
                 // Decoding failed, probably corrupted!
                 //
                 status = dataCorrupt;
             }
         }
         else
         {
             if (getStatus.IsCorruption ())
             {
                 status = dataCorrupt;
             }
             else if (getStatus.IsNotFound ())
             {
                 status = notFound;
             }
             else
             {
                 status = unknown;
             }
         }
         return status;
     }
std::string ripple::NodeStore::LevelDBBackend::getName () inline virtual
Get the human-readable name of this backend. This is used for diagnostic output.
Implements ripple::NodeStore::Backend.
Definition at line 82 of file LevelDBFactory.cpp.
References m_name.
     {
         return m_name;
     }
int ripple::NodeStore::LevelDBBackend::getWriteLoad () inline virtual
Estimate the number of write operations pending.
Implements ripple::NodeStore::Backend.
Definition at line 197 of file LevelDBFactory.cpp.
References ripple::NodeStore::BatchWriter::getWriteLoad(), and m_batch.
     {
         return m_batch.getWriteLoad ();
     }
void ripple::NodeStore::LevelDBBackend::store (NodeObject::ref object) inline
Definition at line 135 of file LevelDBFactory.cpp.
References m_batch, and ripple::NodeStore::BatchWriter::store().
     {
         m_batch.store (object);
     }
void ripple::NodeStore::LevelDBBackend::storeBatch (Batch const & batch) inline virtual
Store a group of objects.
Note
This function will not be called concurrently with itself or store.
Implements ripple::NodeStore::Backend.
Definition at line 140 of file LevelDBFactory.cpp.
References ripple::NodeStore::EncodedBlob::getData(), ripple::NodeStore::EncodedBlob::getKey(), ripple::NodeStore::EncodedBlob::getSize(), m_db, m_keyBytes, and ripple::NodeStore::EncodedBlob::prepare().
Referenced by writeBatch().
     {
         leveldb::WriteBatch wb;
         EncodedBlob encoded;
         BOOST_FOREACH (NodeObject::ref object, batch)
         {
             encoded.prepare (object);
             wb.Put (
                 leveldb::Slice (reinterpret_cast <char const*> (
                     encoded.getKey ()), m_keyBytes),
                 leveldb::Slice (reinterpret_cast <char const*> (
                     encoded.getData ()), encoded.getSize ()));
         }
         leveldb::WriteOptions const options;
         m_db->Write (options, &wb).ok ();
     }
void ripple::NodeStore::LevelDBBackend::visitAll (VisitCallback & callback) inline virtual
Visit every object in the database This is usually called during import.
Note
This routine will not be called concurrently with itself or other methods.
See Also
import, VisitCallback
Implements ripple::NodeStore::Backend.
Definition at line 162 of file LevelDBFactory.cpp.
References ripple::lsFATAL, m_db, m_keyBytes, ripple::NodeStore::VisitCallback::visitObject(), and WriteLog.
     {
         leveldb::ReadOptions const options;
         std::unique_ptr <leveldb::Iterator> it (m_db->NewIterator (options));
         for (it->SeekToFirst (); it->Valid (); it->Next ())
         {
             if (it->key ().size () == m_keyBytes)
             {
                 DecodedBlob decoded (it->key ().data (),
                                                 it->value ().data (),
                                                 it->value ().size ());
                 if (decoded.wasOk ())
                 {
                     NodeObject::Ptr object (decoded.createObject ());
                     callback.visitObject (object);
                 }
                 else
                 {
                     // Uh oh, corrupted data!
                     WriteLog (lsFATAL, NodeObject) << "Corrupt NodeObject #" << uint256 (it->key ().data ());
                 }
             }
             else
             {
                 // VFALCO NOTE What does it mean to find an
                 //             incorrectly sized key? Corruption?
                 WriteLog (lsFATAL, NodeObject) << "Bad key size = " << it->key ().size ();
             }
         }
     }
void ripple::NodeStore::LevelDBBackend::writeBatch (Batch const & batch) inline virtual
Implements ripple::NodeStore::BatchWriter::Callback.
Definition at line 204 of file LevelDBFactory.cpp.
References storeBatch().
     {
         storeBatch (batch);
     }
Member Data Documentation
BatchWriter ripple::NodeStore::LevelDBBackend::m_batch
Definition at line 32 of file LevelDBFactory.cpp.
Referenced by getWriteLoad(), and store().
std::unique_ptr<leveldb::DB> ripple::NodeStore::LevelDBBackend::m_db
Definition at line 34 of file LevelDBFactory.cpp.
Referenced by fetch(), LevelDBBackend(), storeBatch(), and visitAll().
beast::Journal ripple::NodeStore::LevelDBBackend::m_journal
Definition at line 29 of file LevelDBFactory.cpp.
size_t const ripple::NodeStore::LevelDBBackend::m_keyBytes
Definition at line 30 of file LevelDBFactory.cpp.
Referenced by fetch(), storeBatch(), and visitAll().
std::string ripple::NodeStore::LevelDBBackend::m_name
Definition at line 33 of file LevelDBFactory.cpp.
Referenced by getName(), and LevelDBBackend().
Scheduler& ripple::NodeStore::LevelDBBackend::m_scheduler
Definition at line 31 of file LevelDBFactory.cpp.
The documentation for this class was generated from the following file:
rippled/src/ripple_core/nodestore/backend/LevelDBFactory.cpp