rippled: beast::HTTPParser Class Reference
beast::HTTPParser Class Reference
#include <HTTPParser.h>
Public Types
enum Type { typeRequest, typeResponse }
Public Member Functions
HTTPParser (Type type)
~HTTPParser ()
unsigned char error () const
String message () const
std::size_t process (void const *buf, std::size_t bytes)
void process_eof ()
bool finished () const
StringPairArray const & fields () const
bool headersComplete () const
SharedPtr< HTTPRequest > const & request ()
SharedPtr< HTTPResponse > const & response ()
Protected Attributes
Type m_type
std::unique_ptr< HTTPParserImpl > m_impl
SharedPtr< HTTPRequest > m_request
SharedPtr< HTTPResponse > m_response
Detailed Description
A parser for HTTPRequest and HTTPResponse objects.
Definition at line 28 of file HTTPParser.h.
Member Enumeration Documentation
enum beast::HTTPParser::Type
Enumerator
typeRequest
typeResponse
Definition at line 31 of file HTTPParser.h.
     {
         typeRequest,
         typeResponse
     };
Constructor & Destructor Documentation
beast::HTTPParser::HTTPParser (Type type) explicit
Construct a new parser for the specified HTTPMessage type.
Definition at line 22 of file HTTPParser.cpp.
     : m_type (type)
     , m_impl (new HTTPParserImpl (
         (type == typeResponse) ? joyent::HTTP_RESPONSE : joyent::HTTP_REQUEST))
 {
 }
beast::HTTPParser::~HTTPParser ()
Destroy the parser.
Definition at line 29 of file HTTPParser.cpp.
 {
 }
Member Function Documentation
unsigned char beast::HTTPParser::error () const
Returns a non zero error code if parsing fails.
Definition at line 33 of file HTTPParser.cpp.
References m_impl.
Referenced by ripple::HTTP::Peer::handle_read(), and beast::asio::HTTPClientType::Session::handle_read().
 {
     return m_impl->http_errno ();
 }
StringPairArray const & beast::HTTPParser::fields () const
Peek at the header fields as they are being built. Only complete pairs will show up, never partial strings.
Definition at line 84 of file HTTPParser.cpp.
References m_impl.
Referenced by ripple::HTTP::Peer::handle_read(), and ripple::HTTP::Peer::headers().
 {
     return m_impl->fields();
 }
bool beast::HTTPParser::finished () const
Returns true when parsing is successful and complete.
Definition at line 79 of file HTTPParser.cpp.
References m_impl.
Referenced by ripple::HTTP::Peer::handle_read(), and beast::asio::HTTPClientType::Session::handle_read().
 {
     return m_impl->finished();
 }
bool beast::HTTPParser::headersComplete () const
Returns true if all the HTTP headers have been received.
Definition at line 89 of file HTTPParser.cpp.
References m_impl.
Referenced by ripple::HTTP::Peer::headersComplete().
 {
     return m_impl->headers_complete();
 }
String beast::HTTPParser::message () const
Returns the error message text when error is non zero.
Definition at line 38 of file HTTPParser.cpp.
References m_impl.
 {
     return m_impl->http_errno_message ();
 }
std::size_t beast::HTTPParser::process (void const * buf, std::size_t bytes)
Parse the buffer and return the amount used. Typically it is an error when this returns less than the amount passed in.
Definition at line 43 of file HTTPParser.cpp.
References bassertfalse, m_impl, m_request, m_response, m_type, typeRequest, and typeResponse.
Referenced by ripple::HTTP::Peer::handle_read(), and beast::asio::HTTPClientType::Session::handle_read().
 {
     std::size_t const bytes_used (m_impl->process (buf, bytes));
     if (m_impl->finished ())
     {
         if (m_type == typeRequest)
         {
             m_request = new HTTPRequest (
                 m_impl->version (),
                 m_impl->fields (),
                 m_impl->body (),
                 m_impl->method ());
         }
         else if (m_type == typeResponse)
         {
             m_response = new HTTPResponse (
                 m_impl->version (),
                 m_impl->fields (),
                 m_impl->body (),
                 m_impl->status_code ());
         }
         else
         {
             bassertfalse;
         }
     }
     return bytes_used;
 }
void beast::HTTPParser::process_eof ()
Notify the parser that eof was received.
Definition at line 74 of file HTTPParser.cpp.
References m_impl.
Referenced by ripple::HTTP::Peer::handle_read(), and beast::asio::HTTPClientType::Session::handle_read().
 {
     m_impl->process_eof ();
 }
SharedPtr< HTTPRequest > const & beast::HTTPParser::request ()
Return the HTTPRequest object produced from the parsiing. Only valid after finished returns true.
Definition at line 94 of file HTTPParser.cpp.
References bassert, m_request, m_type, and typeRequest.
 {
     bassert (m_type == typeRequest);
     return m_request;
 }
SharedPtr< HTTPResponse > const & beast::HTTPParser::response ()
Return the HTTPResponse object produced from the parsing. Only valid after finished returns true.
Definition at line 101 of file HTTPParser.cpp.
References bassert, m_response, m_type, and typeResponse.
 {
     bassert (m_type == typeResponse);
     return m_response;
 }
Member Data Documentation
std::unique_ptr<HTTPParserImpl> beast::HTTPParser::m_impl protected
Definition at line 82 of file HTTPParser.h.
Referenced by error(), fields(), finished(), headersComplete(), message(), process(), and process_eof().
SharedPtr<HTTPRequest> beast::HTTPParser::m_request protected
Definition at line 83 of file HTTPParser.h.
Referenced by process(), beast::HTTPRequestParser::request(), and request().
SharedPtr<HTTPResponse> beast::HTTPParser::m_response protected
Definition at line 84 of file HTTPParser.h.
Referenced by process(), beast::HTTPResponseParser::response(), and response().
Type beast::HTTPParser::m_type protected
Definition at line 81 of file HTTPParser.h.
Referenced by process(), request(), and response().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_asio/http/HTTPParser.h
rippled/src/beast/modules/beast_asio/http/HTTPParser.cpp