rippled: rocksdb::TableReader Class Reference
rocksdb::TableReader Class Reference abstract
#include <table.h>
Public Member Functions
virtual ~TableReader ()
virtual bool PrefixMayMatch (const Slice &internal_prefix)=0
virtual Iterator * NewIterator (const ReadOptions &)=0
virtual uint64_t ApproximateOffsetOf (const Slice &key)=0
virtual bool TEST_KeyInCache (const ReadOptions &options, const Slice &key)=0
virtual void SetupForCompaction ()=0
virtual TableProperties & GetTableProperties ()=0
virtual Status Get (const ReadOptions &readOptions, const Slice &key, void *handle_context, bool(*result_handler)(void *handle_context, const Slice &k, const Slice &v, bool didIO), void(*mark_key_may_exist_handler)(void *handle_context)=nullptr)=0
Detailed Description
Definition at line 69 of file table.h.
Constructor & Destructor Documentation
virtual rocksdb::TableReader::~TableReader () inline virtual
Definition at line 71 of file table.h.
 {}
Member Function Documentation
virtual uint64_t rocksdb::TableReader::ApproximateOffsetOf (const Slice & key) pure virtual
Implemented in rocksdb::SimpleTableReader, and rocksdb::BlockBasedTable.
Referenced by rocksdb::VersionSet::ApproximateOffsetOf().
virtual Status rocksdb::TableReader::Get (const ReadOptions & readOptions, const Slice & key, void * handle_context, bool(*)(void *handle_context, const Slice &k, const Slice &v, bool didIO) result_handler, void(*)(void *handle_context) mark_key_may_exist_handler = nullptr) pure virtual
Implemented in rocksdb::BlockBasedTable.
Referenced by rocksdb::TableCache::Get(), and rocksdb::TableReaderBenchmark().
virtual TableProperties& rocksdb::TableReader::GetTableProperties () pure virtual
Implemented in rocksdb::SimpleTableReader, and rocksdb::BlockBasedTable.
Referenced by rocksdb::TEST().
virtual Iterator* rocksdb::TableReader::NewIterator (const ReadOptions &) pure virtual
Implemented in rocksdb::SimpleTableReader, and rocksdb::BlockBasedTable.
Referenced by rocksdb::TableCache::NewIterator(), and rocksdb::TableReaderBenchmark().
virtual bool rocksdb::TableReader::PrefixMayMatch (const Slice & internal_prefix) pure virtual
Implemented in rocksdb::SimpleTableReader, and rocksdb::BlockBasedTable.
Referenced by rocksdb::TableCache::PrefixMayMatch().
virtual void rocksdb::TableReader::SetupForCompaction () pure virtual
Implemented in rocksdb::SimpleTableReader, and rocksdb::BlockBasedTable.
Referenced by rocksdb::TableCache::NewIterator().
virtual bool rocksdb::TableReader::TEST_KeyInCache (const ReadOptions & options, const Slice & key) pure virtual
Implemented in rocksdb::SimpleTableReader, and rocksdb::BlockBasedTable.
Referenced by rocksdb::TEST().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/include/rocksdb/table.h