rippled: ripple::FeaturesImpl Class Reference
ripple::FeaturesImpl Class Reference
Public Member Functions
FeaturesImpl (std::chrono::seconds majorityTime, int majorityFraction, beast::Journal journal)
void addInitial () override
FeatureState * addKnown (const char *featureID, const char *friendlyName, bool veto) override
uint256 get (const std::string &name) override
bool veto (uint256 const &feature) override
bool unVeto (uint256 const &feature) override
bool enable (uint256 const &feature) override
bool disable (uint256 const &feature) override
bool isEnabled (uint256 const &feature) override
bool isSupported (uint256 const &feature) override
void setEnabled (const std::vector< uint256 > &features) override
void setSupported (const std::vector< uint256 > &features) override
void reportValidations (const FeatureSet &) override
Json::Value getJson (int) override
Json::Value getJson (uint256 const &) override
void doValidation (Ledger::ref lastClosedLedger, STObject &baseValidation) override
void doVoting (Ledger::ref lastClosedLedger, SHAMap::ref initialPosition) override
featureList_t getVetoed ()
featureList_t getEnabled ()
featureList_t getToEnable (core::Clock::time_point closeTime)
featureList_t getDesired ()
Public Member Functions inherited from ripple::FeatureTable
virtual ~FeatureTable ()
Protected Types
typedef ripple::unordered_map
< uint256, FeatureState > featureMap_t
typedef std::pair< const
uint256, FeatureState > featureIt_t
typedef boost::unordered_set
< uint256 > featureList_t
typedef RippleMutex LockType
typedef std::lock_guard< LockType > ScopedLockType
Protected Member Functions
FeatureState * getCreate (uint256 const &feature, bool create)
bool shouldEnable (std::uint32_t closeTime, const FeatureState &fs)
void setJson (Json::Value &v, const FeatureState &)
Protected Attributes
LockType mLock
featureMap_t mFeatureMap
std::chrono::seconds m_majorityTime
int mMajorityFraction
core::Clock::time_point m_firstReport
core::Clock::time_point m_lastReport
beast::Journal m_journal
Detailed Description
Track the list of "features"
A "feature" is an option that can affect transaction processing rules that is identified by a 256-bit feature identifier and adopted, or rejected, by the network.
Definition at line 28 of file FeaturesImpl.cpp.
Member Typedef Documentation
typedef std::pair<const uint256, FeatureState> ripple::FeaturesImpl::featureIt_t protected
Definition at line 33 of file FeaturesImpl.cpp.
typedef boost::unordered_set<uint256> ripple::FeaturesImpl::featureList_t protected
Definition at line 34 of file FeaturesImpl.cpp.
typedef ripple::unordered_map<uint256, FeatureState> ripple::FeaturesImpl::featureMap_t protected
Definition at line 32 of file FeaturesImpl.cpp.
typedef RippleMutex ripple::FeaturesImpl::LockType protected
Definition at line 36 of file FeaturesImpl.cpp.
typedef std::lock_guard<LockType> ripple::FeaturesImpl::ScopedLockType protected
Definition at line 37 of file FeaturesImpl.cpp.
Constructor & Destructor Documentation
ripple::FeaturesImpl::FeaturesImpl (std::chrono::seconds majorityTime, int majorityFraction, beast::Journal journal) inline
Definition at line 53 of file FeaturesImpl.cpp.
         : m_majorityTime (majorityTime)
         , mMajorityFraction (majorityFraction)
         , m_firstReport (0)
         , m_lastReport (0)
         , m_journal (journal)
     {
     }
Member Function Documentation
void ripple::FeaturesImpl::addInitial () override virtual
Implements ripple::FeatureTable.
Definition at line 96 of file FeaturesImpl.cpp.
 {
     // For each feature this version supports, construct the FeatureState object by calling
     // addKnown. Set any vetoes or defaults. A pointer to the FeatureState can be stashed
 }
FeatureState * ripple::FeaturesImpl::addKnown (const char * featureID, const char * friendlyName, bool veto) override virtual
Implements ripple::FeatureTable.
Definition at line 150 of file FeaturesImpl.cpp.
References ripple::f, getCreate(), hash, ripple::base_uint< BITS >::isZero(), ripple::FeatureState::mSupported, ripple::FeatureState::mVetoed, ripple::FeatureState::setFriendlyName(), ripple::base_uint< BITS >::SetHex(), and veto().
 {
     uint256 hash;
     hash.SetHex (featureID);
     if (hash.isZero ())
     {
         assert (false);
         return nullptr;
     }
     FeatureState* f = getCreate (hash, true);
     if (friendlyName != nullptr)
         f->setFriendlyName (friendlyName);
     f->mVetoed = veto;
     f->mSupported = true;
     return f;
 }
bool ripple::FeaturesImpl::disable (uint256 const & feature) override virtual
Implements ripple::FeatureTable.
Definition at line 213 of file FeaturesImpl.cpp.
References getCreate(), ripple::FeatureState::mEnabled, and mLock.
 {
     ScopedLockType sl (mLock);
     FeatureState* s = getCreate (feature, false);
     if (!s || !s->mEnabled)
         return false;
     s->mEnabled = false;
     return true;
 }
void ripple::FeaturesImpl::doValidation (Ledger::ref lastClosedLedger, STObject & baseValidation) override virtual
Implements ripple::FeatureTable.
Definition at line 423 of file FeaturesImpl.cpp.
References ripple::STVector256::addValue(), getDesired(), ripple::STObject::setFieldV256(), and ripple::STVector256::sort().
 {
     featureList_t lFeatures = getDesired ();
     if (lFeatures.empty ())
         return;
     STVector256 vFeatures (sfFeatures);
     for (auto const& uFeature : lFeatures)
     {
         vFeatures.addValue (uFeature);
     }
     vFeatures.sort ();
     baseValidation.setFieldV256 (sfFeatures, vFeatures);
 }
void ripple::FeaturesImpl::doVoting (Ledger::ref lastClosedLedger, SHAMap::ref initialPosition) override virtual
Implements ripple::FeatureTable.
Definition at line 440 of file FeaturesImpl.cpp.
References ripple::STObject::add(), ripple::getApp(), getToEnable(), ripple::SerializedTransaction::getTransactionID(), ripple::Validations::getValidations(), ripple::Application::getValidations(), m_journal, ripple::Serializer::peekData(), reportValidations(), ripple::STObject::setFieldAccount(), ripple::STObject::setFieldH256(), ripple::ttFEATURE, and beast::Journal::warning.
 {
     // LCL must be flag ledger
     assert((lastClosedLedger->getLedgerSeq () % 256) == 0);
     FeatureSet featureSet (lastClosedLedger->getParentCloseTimeNC ());
     // get validations for ledger before flag ledger
     ValidationSet valSet = getApp().getValidations ().getValidations (lastClosedLedger->getParentHash ());
     for (auto const& entry : valSet)
     {
         auto const& val = *entry.second;
         if (val.isTrusted ())
         {
             featureSet.addVoter ();
             if (val.isFieldPresent (sfFeatures))
             {
                 for (auto const& feature : val.getFieldV256 (sfFeatures))
                 {
                     featureSet.addVote (feature);
                 }
             }
         }
     }
     reportValidations (featureSet);
     featureList_t lFeatures = getToEnable (lastClosedLedger->getCloseTimeNC ());
     for (auto const& uFeature : lFeatures)
     {
         if (m_journal.warning) m_journal.warning <<
             "Voting for feature: " << uFeature;
         // Create the transaction to enable the feature
         SerializedTransaction trans (ttFEATURE);
         trans.setFieldAccount (sfAccount, uint160 ());
         trans.setFieldH256 (sfFeature, uFeature);
         uint256 txID = trans.getTransactionID ();
         if (m_journal.warning) m_journal.warning <<
             "Vote ID: " << txID;
         // Inject the transaction into our initial proposal
         Serializer s;
         trans.add (s, true);
 #if RIPPLE_PROPOSE_FEATURES
         SHAMapItem::pointer tItem = boost::make_shared<SHAMapItem> (txID, s.peekData ());
         if (!initialPosition->addGiveItem (tItem, true, false))
         {
             if (m_journal.warning) m_journal.warning <<
                 "Ledger already had feature transaction";
         }
 #endif
     }
 }
bool ripple::FeaturesImpl::enable (uint256 const & feature) override virtual
Implements ripple::FeatureTable.
Definition at line 200 of file FeaturesImpl.cpp.
References getCreate(), ripple::FeatureState::mEnabled, and mLock.
 {
     ScopedLockType sl (mLock);
     FeatureState* s = getCreate (feature, true);
     if (s->mEnabled)
         return false;
     s->mEnabled = true;
     return true;
 }
uint256 ripple::FeaturesImpl::get (const std::string & name) override virtual
Implements ripple::FeatureTable.
Definition at line 138 of file FeaturesImpl.cpp.
References mFeatureMap.
 {
     for (auto const& e : mFeatureMap)
     {
         if (name == e.second.mFriendlyName)
             return e.first;
     }
     return uint256 ();
 }
FeatureState * ripple::FeaturesImpl::getCreate (uint256 const & feature, bool create) protected
Definition at line 103 of file FeaturesImpl.cpp.
References db, ripple::Database::endIterRows(), ripple::Database::executeSQL(), ripple::getApp(), ripple::Database::getBigInt(), ripple::DatabaseCon::getDB(), ripple::base_uint< BITS >::GetHex(), ripple::Application::getWalletDB(), ripple::FeatureState::m_firstMajority, ripple::FeatureState::m_lastMajority, mFeatureMap, and ripple::Database::startIterRows().
Referenced by addKnown(), disable(), enable(), getJson(), isEnabled(), isSupported(), unVeto(), and veto().
 {
     // call with the mutex held
     auto iter (mFeatureMap.find (featureHash));
     if (iter == mFeatureMap.end ())
     {
         if (!create)
             return nullptr;
         FeatureState* feature = & (mFeatureMap[featureHash]);
         {
             std::string query = "SELECT FirstMajority,LastMajority FROM Features WHERE hash='";
             query.append (featureHash.GetHex ());
             query.append ("';");
             DeprecatedScopedLock sl (getApp().getWalletDB ()->getDBLock ());
             Database* db = getApp().getWalletDB ()->getDB ();
             if (db->executeSQL (query) && db->startIterRows ())
             {
                 feature->m_firstMajority = db->getBigInt("FirstMajority");
                 feature->m_lastMajority = db->getBigInt("LastMajority");
                 db->endIterRows ();
             }
         }
         return feature;
     }
     return & (iter->second);
 }
FeaturesImpl::featureList_t ripple::FeaturesImpl::getDesired ()
Definition at line 302 of file FeaturesImpl.cpp.
References mFeatureMap, and mLock.
Referenced by doValidation().
 {
     featureList_t ret;
     ScopedLockType sl (mLock);
     for (auto const& e : mFeatureMap)
     {
         if (e.second.mSupported && !e.second.mEnabled && !e.second.mVetoed)
             ret.insert (e.first);
     }
     return ret;
 }
FeaturesImpl::featureList_t ripple::FeaturesImpl::getEnabled ()
Definition at line 255 of file FeaturesImpl.cpp.
References mFeatureMap, and mLock.
 {
     featureList_t ret;
     ScopedLockType sl (mLock);
     for (auto const& e : mFeatureMap)
     {
         if (e.second.mEnabled)
             ret.insert (e.first);
     }
     return ret;
 }
Json::Value ripple::FeaturesImpl::getJson (int) override virtual
Implements ripple::FeatureTable.
Definition at line 499 of file FeaturesImpl.cpp.
References mFeatureMap, mLock, Json::objectValue, and setJson().
 {
     Json::Value ret(Json::objectValue);
     {
         ScopedLockType sl(mLock);
         for (auto const& e : mFeatureMap)
         {
             setJson (ret[e.first.GetHex ()] = Json::objectValue, e.second);
         }
     }
     return ret;
 }
Json::Value ripple::FeaturesImpl::getJson (uint256 const & featureID) override virtual
Implements ripple::FeatureTable.
Definition at line 559 of file FeaturesImpl.cpp.
References getCreate(), ripple::base_uint< BITS >::GetHex(), mLock, Json::objectValue, and setJson().
 {
     Json::Value ret = Json::objectValue;
     Json::Value& jFeature = (ret[featureID.GetHex()] = Json::objectValue);
     {
         ScopedLockType sl(mLock);
         FeatureState *featureState = getCreate (featureID, true);
         setJson (jFeature, *featureState);
     }
     return ret;
 }
FeaturesImpl::featureList_t ripple::FeaturesImpl::getToEnable (core::Clock::time_point closeTime)
Definition at line 284 of file FeaturesImpl.cpp.
References m_lastReport, mFeatureMap, mLock, and shouldEnable().
Referenced by doVoting().
 {
     featureList_t ret;
     ScopedLockType sl (mLock);
     if (m_lastReport != 0)
     {
         for (auto const& e : mFeatureMap)
         {
             if (shouldEnable (closeTime, e.second))
                 ret.insert (e.first);
         }
     }
     return ret;
 }
FeaturesImpl::featureList_t ripple::FeaturesImpl::getVetoed ()
Definition at line 242 of file FeaturesImpl.cpp.
References mFeatureMap, and mLock.
 {
     featureList_t ret;
     ScopedLockType sl (mLock);
     for (auto const& e : mFeatureMap)
     {
         if (e.second.mVetoed)
             ret.insert (e.first);
     }
     return ret;
 }
bool ripple::FeaturesImpl::isEnabled (uint256 const & feature) override virtual
Implements ripple::FeatureTable.
Definition at line 226 of file FeaturesImpl.cpp.
References getCreate(), ripple::FeatureState::mEnabled, and mLock.
 {
     ScopedLockType sl (mLock);
     FeatureState* s = getCreate (feature, false);
     return s && s->mEnabled;
 }
bool ripple::FeaturesImpl::isSupported (uint256 const & feature) override virtual
Implements ripple::FeatureTable.
Definition at line 234 of file FeaturesImpl.cpp.
References getCreate(), mLock, and ripple::FeatureState::mSupported.
 {
     ScopedLockType sl (mLock);
     FeatureState* s = getCreate (feature, false);
     return s && s->mSupported;
 }
void ripple::FeaturesImpl::reportValidations (const FeatureSet & set) override virtual
Implements ripple::FeatureTable.
Definition at line 317 of file FeaturesImpl.cpp.
References db, beast::Journal::debug, ripple::Database::executeSQL(), ripple::getApp(), ripple::DatabaseCon::getDB(), ripple::Application::getWalletDB(), hash, ripple::FeatureState::m_firstMajority, m_firstReport, m_journal, ripple::FeatureState::m_lastMajority, m_lastReport, ripple::FeatureSet::mCloseTime, mFeatureMap, mLock, mMajorityFraction, ripple::FeatureSet::mTrustedValidations, ripple::FeatureSet::mVotes, and beast::Journal::warning.
Referenced by doVoting().
 {
     if (set.mTrustedValidations == 0)
         return;
     int threshold = (set.mTrustedValidations * mMajorityFraction) / 256;
     typedef std::map<uint256, int>::value_type u256_int_pair;
     ScopedLockType sl (mLock);
     if (m_firstReport == 0)
         m_firstReport = set.mCloseTime;
     std::vector<uint256> changedFeatures;
     changedFeatures.resize (set.mVotes.size ());
     for (auto const& e : set.mVotes)
     {
         FeatureState& state = mFeatureMap[e.first];
         if (m_journal.debug) m_journal.debug <<
             "Feature " << e.first.GetHex () <<
             " has " << e.second <<
             " votes, needs " << threshold;
         if (e.second >= threshold)
         {
             // we have a majority
             state.m_lastMajority = set.mCloseTime;
             if (state.m_firstMajority == 0)
             {
                 if (m_journal.warning) m_journal.warning <<
                     "Feature " << e.first <<
                     " attains a majority vote";
                 state.m_firstMajority = set.mCloseTime;
                 changedFeatures.push_back (e.first);
             }
         }
         else // we have no majority
         {
             if (state.m_firstMajority != 0)
             {
                 if (m_journal.warning) m_journal.warning <<
                     "Feature " << e.first <<
                     " loses majority vote";
                 state.m_firstMajority = 0;
                 state.m_lastMajority = 0;
                 changedFeatures.push_back (e.first);
             }
         }
     }
     m_lastReport = set.mCloseTime;
     if (!changedFeatures.empty ())
     {
         DeprecatedScopedLock sl (getApp().getWalletDB ()->getDBLock ());
         Database* db = getApp().getWalletDB ()->getDB ();
         db->executeSQL ("BEGIN TRANSACTION;");
         for (auto const& hash : changedFeatures)
         {
             FeatureState& fState = mFeatureMap[hash];
             db->executeSQL (boost::str (boost::format (
                                             "UPDATE Features SET FirstMajority = %d WHERE Hash = '%s';"
                                         ) % fState.m_firstMajority % hash.GetHex ()));
             db->executeSQL (boost::str (boost::format (
                                             "UPDATE Features SET LastMajority = %d WHERE Hash = '%s';"
                                             ) % fState.m_lastMajority % hash.GetHex()));
         }
         db->executeSQL ("END TRANSACTION;");
         changedFeatures.clear ();
     }
 }
void ripple::FeaturesImpl::setEnabled (const std::vector< uint256 > & features) override virtual
Implements ripple::FeatureTable.
Definition at line 395 of file FeaturesImpl.cpp.
References mFeatureMap, and mLock.
 {
     ScopedLockType sl (mLock);
     for (auto& e : mFeatureMap)
     {
         e.second.mEnabled = false;
     }
     for (auto const& e : features)
     {
         mFeatureMap[e].mEnabled = true;
     }
 }
void ripple::FeaturesImpl::setJson (Json::Value & v, const FeatureState & fs) protected
Definition at line 513 of file FeaturesImpl.cpp.
References rocksdb::if(), ripple::FeatureState::m_firstMajority, m_firstReport, ripple::FeatureState::m_lastMajority, m_lastReport, ripple::FeatureState::mEnabled, ripple::FeatureState::mFriendlyName, ripple::FeatureState::mSupported, and ripple::FeatureState::mVetoed.
Referenced by getJson().
 {
     if (!fs.mFriendlyName.empty())
         v["name"] = fs.mFriendlyName;
     v["supported"] = fs.mSupported;
     v["vetoed"] = fs.mVetoed;
     if (fs.mEnabled)
         v["enabled"] = true;
     else
     {
         v["enabled"] = false;
         if (m_lastReport != 0)
         {
             if (fs.m_lastMajority == 0)
             {
                 v["majority"] = false;
             }
             else
             {
                 if (fs.m_firstMajority != 0)
                 {
                     if (fs.m_firstMajority == m_firstReport)
                         v["majority_start"] = "start";
                     else
                         v["majority_start"] = fs.m_firstMajority;
                 }
                 if (fs.m_lastMajority != 0)
                 {
                     if (fs.m_lastMajority == m_lastReport)
                         v["majority_until"] = "now";
                     else
                         v["majority_until"] = fs.m_lastMajority;
                 }
             }
         }
     }
     if (fs.mVetoed)
         v["veto"] = true;
 }
void ripple::FeaturesImpl::setSupported (const std::vector< uint256 > & features) override virtual
Implements ripple::FeatureTable.
Definition at line 409 of file FeaturesImpl.cpp.
References mFeatureMap, and mLock.
 {
     ScopedLockType sl (mLock);
     for (auto &e : mFeatureMap)
     {
         e.second.mSupported = false;
     }
     for (auto const& e : features)
     {
         mFeatureMap[e].mSupported = true;
     }
 }
bool ripple::FeaturesImpl::shouldEnable (std::uint32_t closeTime, const FeatureState & fs) protected
Definition at line 268 of file FeaturesImpl.cpp.
References ripple::FeatureState::m_firstMajority, m_firstReport, ripple::FeatureState::m_lastMajority, m_lastReport, m_majorityTime, ripple::FeatureState::mEnabled, ripple::FeatureState::mSupported, and ripple::FeatureState::mVetoed.
Referenced by getToEnable().
 {
     if (fs.mVetoed || fs.mEnabled || !fs.mSupported || (fs.m_lastMajority != m_lastReport))
         return false;
     if (fs.m_firstMajority == m_firstReport)
     {
         // had a majority when we first started the server, relaxed check
         // WRITEME
     }
     // didn't have a majority when we first started the server, normal check
     return (fs.m_lastMajority - fs.m_firstMajority) > m_majorityTime.count();
 }
bool ripple::FeaturesImpl::unVeto (uint256 const & feature) override virtual
Implements ripple::FeatureTable.
Definition at line 187 of file FeaturesImpl.cpp.
References getCreate(), mLock, and ripple::FeatureState::mVetoed.
 {
     ScopedLockType sl (mLock);
     FeatureState* s = getCreate (feature, false);
     if (!s || !s->mVetoed)
         return false;
     s->mVetoed = false;
     return true;
 }
bool ripple::FeaturesImpl::veto (uint256 const & feature) override virtual
Implements ripple::FeatureTable.
Definition at line 174 of file FeaturesImpl.cpp.
References getCreate(), mLock, and ripple::FeatureState::mVetoed.
Referenced by addKnown().
 {
     ScopedLockType sl (mLock);
     FeatureState* s = getCreate (feature, true);
     if (s->mVetoed)
         return false;
     s->mVetoed = true;
     return true;
 }
Member Data Documentation
core::Clock::time_point ripple::FeaturesImpl::m_firstReport protected
Definition at line 43 of file FeaturesImpl.cpp.
Referenced by reportValidations(), setJson(), and shouldEnable().
beast::Journal ripple::FeaturesImpl::m_journal protected
Definition at line 45 of file FeaturesImpl.cpp.
Referenced by doVoting(), and reportValidations().
core::Clock::time_point ripple::FeaturesImpl::m_lastReport protected
Definition at line 44 of file FeaturesImpl.cpp.
Referenced by getToEnable(), reportValidations(), setJson(), and shouldEnable().
std::chrono::seconds ripple::FeaturesImpl::m_majorityTime protected
Definition at line 41 of file FeaturesImpl.cpp.
Referenced by shouldEnable().
featureMap_t ripple::FeaturesImpl::mFeatureMap protected
Definition at line 40 of file FeaturesImpl.cpp.
Referenced by get(), getCreate(), getDesired(), getEnabled(), getJson(), getToEnable(), getVetoed(), reportValidations(), setEnabled(), and setSupported().
LockType ripple::FeaturesImpl::mLock protected
Definition at line 38 of file FeaturesImpl.cpp.
Referenced by disable(), enable(), getDesired(), getEnabled(), getJson(), getToEnable(), getVetoed(), isEnabled(), isSupported(), reportValidations(), setEnabled(), setSupported(), unVeto(), and veto().
int ripple::FeaturesImpl::mMajorityFraction protected
Definition at line 42 of file FeaturesImpl.cpp.
Referenced by reportValidations().
The documentation for this class was generated from the following file:
rippled/src/ripple_app/misc/FeaturesImpl.cpp