rippled: ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream > Class Template Reference
ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream > Class Template Reference
#include <MultiSocketType.h>
Public Types
typedef
beast::asio::shared_handler_allocator
< char > Allocator
Public Member Functions
AsyncOp (MultiSocketType< StreamSocket > &owner, Stream &stream, handshake_type type, beast::asio::const_buffers const &buffers, error_handler const &handler)
~AsyncOp ()
void start ()
Public Attributes
error_handler m_handler
MultiSocketType< StreamSocket > & m_owner
Stream & m_stream
handshake_type const m_type
boost::asio::basic_streambuf
< Allocator > m_buffer
beast::asio::HandshakeDetectorType
< next_layer_type,
beast::asio::HandshakeDetectLogicPROXY > m_proxy
beast::asio::HandshakeDetectorType
< next_layer_type,
beast::asio::HandshakeDetectLogicSSL3 > m_ssl
bool m_first_time
Private Member Functions
void on_complete (error_code ec)
void on_final (error_code ec)
void async_handshake (error_code ec)
Detailed Description
template<class StreamSocket>
template<typename Stream>
class ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >
Definition at line 857 of file MultiSocketType.h.
Member Typedef Documentation
template<class StreamSocket> template<typename Stream > typedef beast::asio::shared_handler_allocator<char> ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::Allocator
Definition at line 864 of file MultiSocketType.h.
Constructor & Destructor Documentation
template<class StreamSocket> template<typename Stream > ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::AsyncOp (MultiSocketType< StreamSocket > & owner, Stream & stream, handshake_type type, beast::asio::const_buffers const & buffers, error_handler const & handler) inline
Definition at line 878 of file MultiSocketType.h.
References ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::m_buffer.
             : m_handler (handler)
             , m_owner (owner)
             , m_stream (stream)
             , m_type (type)
         #if RIPPLE_MULTISOCKET_NO_ALLOCATOR
             , m_buffer (std::numeric_limits <std::size_t>::max())
         #else
             , m_buffer (std::numeric_limits <std::size_t>::max(), handler)
         #endif
             , m_first_time (true)
         {
             // Prepare our rolling detect buffer with any input
             //
             // NOTE We have to do this in reverse order from the synchronous
             // version because the callers buffers won't be in scope inside
             // our call.
             //
             m_buffer.commit (boost::asio::buffer_copy (
                 m_buffer.prepare (boost::asio::buffer_size (buffers)),
                     buffers));
         }
template<class StreamSocket> template<typename Stream > ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::~AsyncOp () inline
Definition at line 904 of file MultiSocketType.h.
         {
         }
Member Function Documentation
template<class StreamSocket> template<typename Stream > void ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::async_handshake (error_code ec) inline private
Definition at line 952 of file MultiSocketType.h.
References beast::asio::HandshakeDetectorType< Stream, Logic >::async_detect(), bassert, beast::asio::HandshakeDetectLogic::finished(), beast::asio::HandshakeDetectLogicPROXY::getInfo(), beast::asio::HandshakeDetectorType< Stream, Logic >::getLogic(), ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::m_buffer, ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::m_first_time, ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::m_handler, ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::m_owner, ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::m_proxy, ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::m_ssl, ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::m_stream, ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::m_type, ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::on_complete(), ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::on_final(), ripple::MultiSocket::Flag::proxy, ripple::MultiSocket::Flag::ssl, ripple::MultiSocket::Flag::ssl_required, ripple::MultiSocketType< StreamSocket >::stateDetectSSL, ripple::MultiSocketType< StreamSocket >::stateExpectPROXY, ripple::MultiSocketType< StreamSocket >::stateHandshake, ripple::MultiSocketType< StreamSocket >::stateHandshakeFinal, ripple::MultiSocketType< StreamSocket >::stateNone, ripple::MultiSocketType< StreamSocket >::stateReady, beast::asio::HandshakeDetectLogic::success(), and beast::asio::wrap_handler().
Referenced by ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::on_complete(), and ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::start().
         {
             while (!ec)
             {
                 if (m_owner.m_state == stateReady)
                 {
                     // Always need shutdown if handshake successful.
                     m_owner.m_needsShutdown = true;
                     break;
                 }
                 switch (m_owner.m_state)
                 {
                 case stateHandshakeFinal:
                     {
                         // Have to set this beforehand even
                         // though we might get an error.
                         //
                         m_owner.m_state = stateReady;
                         m_owner.stream ().async_handshake (m_type,
                             beast::asio::wrap_handler (std::bind (
                                 &AsyncOp::on_complete, this->shared_from_this(),
                                     beast::asio::placeholders::error),
                                         m_handler, m_first_time));
                     }
                     return;
                 case stateExpectPROXY:
                     {
                         if (m_proxy.getLogic ().finished ())
{
                             if (m_proxy.getLogic ().success ())
{
                                 m_owner.m_proxyInfo =
                                     m_proxy.getLogic ().getInfo ();
                                 m_owner.m_proxyInfoSet = true;
                                 // Strip off the PROXY flag.
                                 m_owner.m_flags = m_owner.m_flags.without (
                                     Flag::proxy);
                                 // Update handshake state with the
                                 // leftover bytes.
                                 ec = m_owner.initHandshake (m_type,
                                     m_buffer.data ());
                                 break;
                             }
                             // Didn't get the PROXY handshake we needed
                             ec = m_owner.handshake_error ();
                             break;
                         }
                         m_proxy.async_detect (m_stream, m_buffer,
                             beast::asio::wrap_handler (std::bind (
                                 &AsyncOp::on_complete, this->shared_from_this(),
                                     beast::asio::placeholders::error),
                                         m_handler, m_first_time));
                     }
                     return;
                 case stateDetectSSL:
                     {
                         if (m_ssl.getLogic ().finished ())
{
                             // Was it SSL?
                             if (m_ssl.getLogic ().success ())
{
                                 // Convert the ssl flag to ssl_required
                                 m_owner.m_flags = m_owner.m_flags.with (
                                     Flag::ssl_required).without (Flag::ssl);
                             }
                             else
{
                                 // Not SSL, strip the ssl flag
                                 m_owner.m_flags = m_owner.m_flags.without (
                                     Flag::ssl);
                             }
                             // Update handshake state with the leftover bytes.
                             ec = m_owner.initHandshake (m_type,
                                 m_buffer.data ());
                             break;
                         }
                         m_ssl.async_detect (m_stream, m_buffer,
                             beast::asio::wrap_handler (std::bind (
                                 &AsyncOp::on_complete, this->shared_from_this(),
                                     beast::asio::placeholders::error),
                                         m_handler, m_first_time));
                     }
                     return;
                 case stateNone:
                 case stateReady:
                 case stateHandshake:
                 default:
                     fatal_error ("invalid state");
                     ec = m_owner.handshake_error ();
                 }
             }
             bassert (ec || (m_owner.m_state == stateReady &&
                 m_owner.m_needsShutdown));
             on_final (ec);
         }
template<class StreamSocket> template<typename Stream > void ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::on_complete (error_code ec) inline private
Definition at line 937 of file MultiSocketType.h.
References ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::async_handshake(), and ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::m_first_time.
Referenced by ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::async_handshake().
         {
             m_first_time = false;
             async_handshake(ec);
         }
template<class StreamSocket> template<typename Stream > void ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::on_final (error_code ec) inline private
Definition at line 943 of file MultiSocketType.h.
References ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::m_handler.
Referenced by ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::async_handshake(), and ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::start().
         {
             m_handler (ec);
         }
template<class StreamSocket> template<typename Stream > void ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::start () inline
Definition at line 910 of file MultiSocketType.h.
References ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::async_handshake(), ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::m_handler, ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::m_owner, ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::m_type, ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::on_final(), ripple::MultiSocketType< StreamSocket >::stateReady, and beast::asio::wrap_handler().
         {
             error_code ec (m_owner.initHandshake (m_type));
             if (! ec)
             {
                 if (m_owner.m_state != stateReady)
                 {
                     async_handshake (ec);
                     return;
                 }
                 // Always need shutdown if handshake successful.
                 m_owner.m_needsShutdown = true;
             }
             // Post to the io_service, otherwise we would allow the
             // handler to be invoked from within an initiating function.
             // We can't use io_service::wrap because that calls dispatch
             // instead of post.
             //
             m_owner.get_io_service().post (beast::asio::wrap_handler (
                 std::bind (&AsyncOp::on_final, this->shared_from_this(),
                     ec), m_handler));
         }
Member Data Documentation
template<class StreamSocket> template<typename Stream > boost::asio::basic_streambuf<Allocator> ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::m_buffer
Definition at line 871 of file MultiSocketType.h.
Referenced by ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::async_handshake(), and ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::AsyncOp().
template<class StreamSocket> template<typename Stream > bool ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::m_first_time
Definition at line 876 of file MultiSocketType.h.
Referenced by ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::async_handshake(), and ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::on_complete().
template<class StreamSocket> template<typename Stream > error_handler ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::m_handler
Definition at line 867 of file MultiSocketType.h.
Referenced by ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::async_handshake(), ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::on_final(), and ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::start().
template<class StreamSocket> template<typename Stream > MultiSocketType<StreamSocket>& ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::m_owner
Definition at line 868 of file MultiSocketType.h.
Referenced by ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::async_handshake(), and ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::start().
template<class StreamSocket> template<typename Stream > beast::asio::HandshakeDetectorType<next_layer_type, beast::asio::HandshakeDetectLogicPROXY> ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::m_proxy
Definition at line 873 of file MultiSocketType.h.
Referenced by ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::async_handshake().
template<class StreamSocket> template<typename Stream > beast::asio::HandshakeDetectorType<next_layer_type, beast::asio::HandshakeDetectLogicSSL3> ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::m_ssl
Definition at line 875 of file MultiSocketType.h.
Referenced by ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::async_handshake().
template<class StreamSocket> template<typename Stream > Stream& ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::m_stream
Definition at line 869 of file MultiSocketType.h.
Referenced by ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::async_handshake().
template<class StreamSocket> template<typename Stream > handshake_type const ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::m_type
Definition at line 870 of file MultiSocketType.h.
Referenced by ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::async_handshake(), and ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::start().
The documentation for this class was generated from the following file:
rippled/src/ripple/common/impl/MultiSocketType.h