rippled: rocksdb::Footer Class Reference
rocksdb::Footer Class Reference
#include <format.h>
Public Types
enum { kEncodedLength = 2*BlockHandle::kMaxEncodedLength + 8 }
Public Member Functions
Footer ()
const BlockHandle & metaindex_handle () const
void set_metaindex_handle (const BlockHandle &h)
const BlockHandle & index_handle () const
void set_index_handle (const BlockHandle &h)
void EncodeTo (std::string *dst) const
Status DecodeFrom (Slice *input)
Private Attributes
BlockHandle metaindex_handle_
BlockHandle index_handle_
Detailed Description
Definition at line 51 of file format.h.
Member Enumeration Documentation
anonymous enum
Enumerator
kEncodedLength
Definition at line 73 of file format.h.
        {
     kEncodedLength = 2*BlockHandle::kMaxEncodedLength + 8
   };
Constructor & Destructor Documentation
rocksdb::Footer::Footer () inline
Definition at line 53 of file format.h.
 { }
Member Function Documentation
Status rocksdb::Footer::DecodeFrom (Slice * input)
Definition at line 50 of file format.cc.
References rocksdb::Slice::data(), rocksdb::DecodeFixed32(), rocksdb::BlockHandle::DecodeFrom(), index_handle_, rocksdb::Status::InvalidArgument(), kEncodedLength, rocksdb::kTableMagicNumber, metaindex_handle_, rocksdb::Status::ok(), and rocksdb::Slice::size().
Referenced by rocksdb::BlockBasedTable::Open().
{
   assert(input != nullptr);
   assert(input->size() >= kEncodedLength);
   const char* magic_ptr = input->data() + kEncodedLength - 8;
   const uint32_t magic_lo = DecodeFixed32(magic_ptr);
   const uint32_t magic_hi = DecodeFixed32(magic_ptr + 4);
   const uint64_t magic = ((static_cast<uint64_t>(magic_hi) << 32) |
                           (static_cast<uint64_t>(magic_lo)));
   if (magic != kTableMagicNumber) {
     return Status::InvalidArgument("not an sstable (bad magic number)");
   }
   Status result = metaindex_handle_.DecodeFrom(input);
   if (result.ok()) {
     result = index_handle_.DecodeFrom(input);
   }
   if (result.ok()) {
     // We skip over any leftover data (just padding for now) in "input"
     const char* end = magic_ptr + 8;
     *input = Slice(end, input->data() + input->size() - end);
   }
   return result;
 }
void rocksdb::Footer::EncodeTo (std::string * dst) const
Definition at line 38 of file format.cc.
References rocksdb::BlockHandle::EncodeTo(), index_handle_, kEncodedLength, rocksdb::BlockHandle::kMaxEncodedLength, rocksdb::kTableMagicNumber, metaindex_handle_, and rocksdb::PutFixed32().
Referenced by rocksdb::BlockBasedTableBuilder::Finish().
{
 #ifndef NDEBUG
   const size_t original_size = dst->size();
 #endif
   metaindex_handle_.EncodeTo(dst);
   index_handle_.EncodeTo(dst);
   dst->resize(2 * BlockHandle::kMaxEncodedLength);  // Padding
   PutFixed32(dst, static_cast<uint32_t>(kTableMagicNumber & 0xffffffffu));
   PutFixed32(dst, static_cast<uint32_t>(kTableMagicNumber >> 32));
   assert(dst->size() == original_size + kEncodedLength);
 }
const BlockHandle& rocksdb::Footer::index_handle () const inline
Definition at line 60 of file format.h.
References index_handle_.
Referenced by rocksdb::BlockBasedTable::Open().
{
     return index_handle_;
   }
const BlockHandle& rocksdb::Footer::metaindex_handle () const inline
Definition at line 56 of file format.h.
References metaindex_handle_.
Referenced by rocksdb::BlockBasedTable::Open().
 { return metaindex_handle_; }
void rocksdb::Footer::set_index_handle (const BlockHandle & h) inline
Definition at line 63 of file format.h.
References index_handle_.
Referenced by rocksdb::BlockBasedTableBuilder::Finish().
{
     index_handle_ = h;
   }
void rocksdb::Footer::set_metaindex_handle (const BlockHandle & h) inline
Definition at line 57 of file format.h.
References metaindex_handle_.
Referenced by rocksdb::BlockBasedTableBuilder::Finish().
 { metaindex_handle_ = h; }
Member Data Documentation
BlockHandle rocksdb::Footer::index_handle_ private
Definition at line 79 of file format.h.
Referenced by DecodeFrom(), EncodeTo(), index_handle(), and set_index_handle().
BlockHandle rocksdb::Footer::metaindex_handle_ private
Definition at line 78 of file format.h.
Referenced by DecodeFrom(), EncodeTo(), metaindex_handle(), and set_metaindex_handle().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/table/format.h
rippled/src/ripple/rocksdb/rocksdb/table/format.cc