rippled: beast::StringArray Class Reference
beast::StringArray Class Reference
#include <StringArray.h>
Public Member Functions
StringArray () noexcept
StringArray (const StringArray &other)
StringArray (const String &firstValue)
StringArray (const String *strings, int numberOfStrings)
StringArray (const char *const *strings, int numberOfStrings)
StringArray (const char *const *strings)
StringArray (const wchar_t *const *strings)
StringArray (const wchar_t *const *strings, int numberOfStrings)
~StringArray ()
StringArray & operator= (const StringArray &other)
void swapWith (StringArray &other) noexcept
bool operator== (const StringArray &other) const noexcept
bool operator!= (const StringArray &other) const noexcept
int size () const noexcept
const String & operator[] (int index) const noexcept
String & getReference (int index) noexcept
String * begin () const noexcept
String * end () const noexcept
bool contains (const String &stringToLookFor, bool ignoreCase=false) const
int indexOf (const String &stringToLookFor, bool ignoreCase=false, int startIndex=0) const
void add (const String &stringToAdd)
void insert (int index, const String &stringToAdd)
void addIfNotAlreadyThere (const String &stringToAdd, bool ignoreCase=false)
void set (int index, const String &newString)
void addArray (const StringArray &other, int startIndex=0, int numElementsToAdd=-1)
int addTokens (const String &stringToTokenise, bool preserveQuotedStrings)
int addTokens (const String &stringToTokenise, const String &breakCharacters, const String &quoteCharacters)
int addLines (const String &stringToBreakUp)
void clear ()
void remove (int index)
void removeString (const String &stringToRemove, bool ignoreCase=false)
void removeRange (int startIndex, int numberToRemove)
void removeDuplicates (bool ignoreCase)
void removeEmptyStrings (bool removeWhitespaceStrings=true)
void move (int currentIndex, int newIndex) noexcept
void trim ()
void appendNumbersToDuplicates (bool ignoreCaseWhenComparing, bool appendNumberToFirstInstance, CharPointer_UTF8 preNumberString=CharPointer_UTF8(nullptr), CharPointer_UTF8 postNumberString=CharPointer_UTF8(nullptr))
String joinIntoString (const String &separatorString, int startIndex=0, int numberOfElements=-1) const
void sort (bool ignoreCase)
void ensureStorageAllocated (int minNumElements)
void minimiseStorageOverheads ()
Static Public Member Functions
static StringArray fromTokens (const String &stringToTokenise, bool preserveQuotedStrings)
static StringArray fromTokens (const String &stringToTokenise, const String &breakCharacters, const String &quoteCharacters)
static StringArray fromLines (const String &stringToBreakUp)
Private Attributes
Array< String > strings
Detailed Description
A special array for holding a list of strings.
See Also
String, StringPairArray
Definition at line 38 of file StringArray.h.
Constructor & Destructor Documentation
beast::StringArray::StringArray () noexcept
Creates an empty string array
Definition at line 27 of file StringArray.cpp.
 {
 }
beast::StringArray::StringArray (const StringArray & other)
Creates a copy of another string array
Definition at line 31 of file StringArray.cpp.
     : strings (other.strings)
 {
 }
beast::StringArray::StringArray (const String & firstValue) explicit
Creates an array containing a single string.
Definition at line 43 of file StringArray.cpp.
References strings.
 {
     strings.add (firstValue);
 }
beast::StringArray::StringArray (const String * strings, int numberOfStrings)
Creates an array from a raw array of strings.
Parameters
strings an array of strings to add
numberOfStrings how many items there are in the array
Definition at line 66 of file StringArray.cpp.
References beast::StringArrayHelpers::addArray(), and strings.
 {
     StringArrayHelpers::addArray (strings, initialStrings, numberOfStrings);
 }
beast::StringArray::StringArray (const char *const * strings, int numberOfStrings)
Creates a copy of an array of string literals.
Parameters
strings an array of strings to add. Null pointers in the array will be treated as empty strings
numberOfStrings how many items there are in the array
Definition at line 76 of file StringArray.cpp.
References beast::StringArrayHelpers::addArray(), and strings.
 {
     StringArrayHelpers::addArray (strings, initialStrings, numberOfStrings);
 }
beast::StringArray::StringArray (const char *const * strings) explicit
Creates a copy of a null-terminated array of string literals.
Each item from the array passed-in is added, until it encounters a null pointer, at which point it stops.
Definition at line 71 of file StringArray.cpp.
References beast::StringArrayHelpers::addArray(), and strings.
 {
     StringArrayHelpers::addArray (strings, initialStrings);
 }
beast::StringArray::StringArray (const wchar_t *const * strings) explicit
Creates a copy of a null-terminated array of string literals. Each item from the array passed-in is added, until it encounters a null pointer, at which point it stops.
Definition at line 81 of file StringArray.cpp.
References beast::StringArrayHelpers::addArray(), and strings.
 {
     StringArrayHelpers::addArray (strings, initialStrings);
 }
beast::StringArray::StringArray (const wchar_t *const * strings, int numberOfStrings)
Creates a copy of an array of string literals.
Parameters
strings an array of strings to add. Null pointers in the array will be treated as empty strings
numberOfStrings how many items there are in the array
Definition at line 86 of file StringArray.cpp.
References beast::StringArrayHelpers::addArray(), and strings.
 {
     StringArrayHelpers::addArray (strings, initialStrings, numberOfStrings);
 }
beast::StringArray::~StringArray ()
Destructor.
Definition at line 105 of file StringArray.cpp.
 {
 }
Member Function Documentation
void beast::StringArray::add (const String & stringToAdd)
Appends a string at the end of the array.
Definition at line 150 of file StringArray.cpp.
References strings.
Referenced by addIfNotAlreadyThere(), ripple::Validators::ManagerImp::addStrings(), beast::SemanticVersion::chopIdentifiers(), beast::SemanticVersion_test::ids(), beast::Process::openDocument(), and beast::StringPairArray::set().
 {
     strings.add (newString);
 }
void beast::StringArray::addArray (const StringArray & other, int startIndex = 0, int numElementsToAdd = -1)
Appends some strings from another array to the end of this one.
Parameters
other the array to add
startIndex the first element of the other array to add
numElementsToAdd the maximum number of elements to add (if this is less than zero, they are all added)
Definition at line 166 of file StringArray.cpp.
References bassertfalse, size(), and strings.
 {
     if (startIndex < 0)
     {
         bassertfalse;
         startIndex = 0;
     }
     if (numElementsToAdd < 0 || startIndex + numElementsToAdd > otherArray.size())
         numElementsToAdd = otherArray.size() - startIndex;
     while (--numElementsToAdd >= 0)
         strings.add (otherArray.strings.getReference (startIndex++));
 }
void beast::StringArray::addIfNotAlreadyThere (const String & stringToAdd, bool ignoreCase = false)
Adds a string to the array as long as it's not already in there.
The search can optionally be case-insensitive.
Definition at line 160 of file StringArray.cpp.
References add(), and contains().
 {
     if (! contains (newString, ignoreCase))
         add (newString);
 }
int beast::StringArray::addLines (const String & stringToBreakUp)
Breaks up a string into lines and adds them to this array.
This breaks a string down into lines separated by \n or \r\n, and adds each line to the array. Line-break characters are omitted from the strings that are added to the array.
Definition at line 392 of file StringArray.cpp.
References beast::String::getCharPointer(), beast::CharPointer_UTF8::isEmpty(), and strings.
Referenced by fromLines(), and beast::File::readLines().
 {
     int numLines = 0;
     String::CharPointerType text (sourceText.getCharPointer());
     bool finished = text.isEmpty();
     while (! finished)
     {
         for (String::CharPointerType startOfLine (text);;)
         {
             const String::CharPointerType endOfLine (text);
             switch (text.getAndAdvance())
             {
                 case 0:     finished = true; break;
                 case '\n':  break;
                 case '\r':  if (*text == '\n') ++text; break;
                 default:    continue;
             }
             strings.add (String (startOfLine, endOfLine));
             ++numLines;
             break;
         }
     }
     return numLines;
 }
int beast::StringArray::addTokens (const String & stringToTokenise, bool preserveQuotedStrings)
Breaks up a string into tokens and adds them to this array.
This will tokenise the given string using whitespace characters as the token delimiters, and will add these tokens to the end of the array.
Returns
the number of tokens added
See Also
fromTokens
Definition at line 362 of file StringArray.cpp.
Referenced by fromTokens(), beast::FileSearchPath::init(), and beast::parseWildcards().
 {
     return addTokens (text, " \n\r\t", preserveQuotedStrings ? "\"" : "");
 }
int beast::StringArray::addTokens (const String & stringToTokenise, const String & breakCharacters, const String & quoteCharacters)
Breaks up a string into tokens and adds them to this array.
This will tokenise the given string (using the string passed in to define the token delimiters), and will add these tokens to the end of the array.
Parameters
stringToTokenise the string to tokenise
breakCharacters a string of characters, any of which will be considered to be a token delimiter.
quoteCharacters if this string isn't empty, it defines a set of characters which are treated as quotes. Any text occurring between quotes is not broken up into tokens.
Returns
the number of tokens added
See Also
fromTokens
Definition at line 367 of file StringArray.cpp.
References beast::CharacterFunctions::findEndOfToken(), beast::String::getCharPointer(), beast::CharPointer_UTF8::isEmpty(), and strings.
 {
     int num = 0;
     String::CharPointerType t (text.getCharPointer());
     if (! t.isEmpty())
     {
         for (;;)
         {
             String::CharPointerType tokenEnd (CharacterFunctions::findEndOfToken (t,
                                                                                   breakCharacters.getCharPointer(),
                                                                                   quoteCharacters.getCharPointer()));
             strings.add (String (t, tokenEnd));
             ++num;
             if (tokenEnd.isEmpty())
                 break;
             t = ++tokenEnd;
         }
     }
     return num;
 }
void beast::StringArray::appendNumbersToDuplicates (bool ignoreCaseWhenComparing, bool appendNumberToFirstInstance, CharPointer_UTF8 preNumberString = CharPointer_UTF8 (nullptr), CharPointer_UTF8 postNumberString = CharPointer_UTF8 (nullptr))
Adds numbers to the strings in the array, to make each string unique.
This will add numbers to the ends of groups of similar strings. e.g. if there are two "moose" strings, they will become "moose (1)" and "moose (2)"
Parameters
ignoreCaseWhenComparing whether the comparison used is case-insensitive
appendNumberToFirstInstance whether the first of a group of similar strings also has a number appended to it.
preNumberString when adding a number, this string is added before the number. If you pass 0, a default string will be used, which adds brackets around the number.
postNumberString this string is appended after any numbers that are added. If you pass 0, a default string will be used, which adds brackets around the number.
Definition at line 466 of file StringArray.cpp.
References beast::CharPointer_UTF8::getAddress(), indexOf(), set(), size(), and strings.
 {
     CharPointer_UTF8 defaultPre (" ("), defaultPost (")");
     if (preNumberString.getAddress() == nullptr)
         preNumberString = defaultPre;
     if (postNumberString.getAddress() == nullptr)
         postNumberString = defaultPost;
     for (int i = 0; i < size() - 1; ++i)
     {
         String& s = strings.getReference(i);
         int nextIndex = indexOf (s, ignoreCase, i + 1);
         if (nextIndex >= 0)
         {
             const String original (s);
             int number = 0;
             if (appendNumberToFirstInstance)
                 s = original + String (preNumberString) + String (++number) + String (postNumberString);
             else
                 ++number;
             while (nextIndex >= 0)
             {
                 set (nextIndex, (*this)[nextIndex] + String (preNumberString) + String (++number) + String (postNumberString));
                 nextIndex = indexOf (original, ignoreCase, nextIndex + 1);
             }
         }
     }
 }
String* beast::StringArray::begin () const inline noexcept
Returns a pointer to the first String in the array. This method is provided for compatibility with standard C++ iteration mechanisms.
Definition at line 136 of file StringArray.h.
     {
         return strings.begin();
     }
void beast::StringArray::clear ()
Removes all elements from the array.
Definition at line 131 of file StringArray.cpp.
References strings.
Referenced by beast::StringPairArray::clear(), and beast::FileSearchPath::init().
 {
     strings.clear();
 }
bool beast::StringArray::contains (const String & stringToLookFor, bool ignoreCase = false) const
Searches for a string in the array.
The comparison will be case-insensitive if the ignoreCase parameter is true.
Returns
true if the string is found inside the array
Definition at line 186 of file StringArray.cpp.
References size(), and strings.
Referenced by addIfNotAlreadyThere().
 {
     if (ignoreCase)
     {
         for (int i = size(); --i >= 0;)
             if (strings.getReference(i).equalsIgnoreCase (stringToLookFor))
                 return true;
     }
     else
     {
         for (int i = size(); --i >= 0;)
             if (stringToLookFor == strings.getReference(i))
                 return true;
     }
     return false;
 }
String* beast::StringArray::end () const inline noexcept
Returns a pointer to the String which follows the last element in the array. This method is provided for compatibility with standard C++ iteration mechanisms.
Definition at line 144 of file StringArray.h.
     {
         return strings.end();
     }
void beast::StringArray::ensureStorageAllocated (int minNumElements)
Increases the array's internal storage to hold a minimum number of elements.
Calling this before adding a large known number of elements means that the array won't have to keep dynamically resizing itself as the elements are added, and it'll therefore be more efficient.
Definition at line 505 of file StringArray.cpp.
References strings.
Referenced by ripple::Validators::ManagerImp::addStrings().
 {
     strings.ensureStorageAllocated (minNumElements);
 }
StringArray beast::StringArray::fromLines (const String & stringToBreakUp) static
Returns an array containing the lines in a given string.
This breaks a string down into lines separated by \n or \r\n, and returns an array containing these lines. Line-break characters are omitted from the strings that are added to the array.
Definition at line 438 of file StringArray.cpp.
References addLines().
 {
     StringArray s;
     s.addLines (stringToBreakUp);
     return s;
 }
StringArray beast::StringArray::fromTokens (const String & stringToTokenise, bool preserveQuotedStrings) static
Returns an array containing the tokens in a given string.
This will tokenise the given string using whitespace characters as the token delimiters, and return these tokens as an array.
See Also
addTokens
Definition at line 421 of file StringArray.cpp.
References addTokens().
 {
     StringArray s;
     s.addTokens (stringToTokenise, preserveQuotedStrings);
     return s;
 }
StringArray beast::StringArray::fromTokens (const String & stringToTokenise, const String & breakCharacters, const String & quoteCharacters) static
Returns an array containing the tokens in a given string.
This will tokenise the given string using whitespace characters as the token delimiters, and return these tokens as an array.
Parameters
stringToTokenise the string to tokenise
breakCharacters a string of characters, any of which will be considered to be a token delimiter.
quoteCharacters if this string isn't empty, it defines a set of characters which are treated as quotes. Any text occurring between quotes is not broken up into tokens.
See Also
addTokens
Definition at line 429 of file StringArray.cpp.
References addTokens().
 {
     StringArray s;
     s.addTokens (stringToTokenise, breakCharacters, quoteCharacters);
     return s;
 }
String & beast::StringArray::getReference (int index) noexcept
Returns a reference to one of the strings in the array. This lets you modify a string in-place in the array, but you must be sure that the index is in-range.
Definition at line 144 of file StringArray.cpp.
References bassert, and beast::isPositiveAndBelow().
 {
     bassert (isPositiveAndBelow (index, strings.size()));
     return strings.getReference (index);
 }
int beast::StringArray::indexOf (const String & stringToLookFor, bool ignoreCase = false, int startIndex = 0) const
Searches for a string in the array.
The comparison will be case-insensitive if the ignoreCase parameter is true.
Parameters
stringToLookFor the string to try to find
ignoreCase whether the comparison should be case-insensitive
startIndex the first index to start searching from
Returns
the index of the first occurrence of the string in this array, or -1 if it isn't found.
Definition at line 204 of file StringArray.cpp.
References size(), and strings.
Referenced by appendNumbersToDuplicates(), beast::StringPairArray::getValue(), beast::StringPairArray::operator[](), beast::StringPairArray::remove(), removeDuplicates(), and beast::StringPairArray::set().
 {
     if (i < 0)
         i = 0;
     const int numElements = size();
     if (ignoreCase)
     {
         while (i < numElements)
         {
             if (strings.getReference(i).equalsIgnoreCase (stringToLookFor))
                 return i;
             ++i;
         }
     }
     else
     {
         while (i < numElements)
         {
             if (stringToLookFor == strings.getReference (i))
                 return i;
             ++i;
         }
     }
     return -1;
 }
void beast::StringArray::insert (int index, const String & stringToAdd)
Inserts a string into the array.
This will insert a string into the array at the given index, moving up the other elements to make room for it. If the index is less than zero or greater than the size of the array, the new string will be added to the end of the array.
Definition at line 155 of file StringArray.cpp.
References strings.
Referenced by beast::FileSearchPath::add().
 {
     strings.insert (index, newString);
 }
String beast::StringArray::joinIntoString (const String & separatorString, int startIndex = 0, int numberOfElements = -1) const
Joins the strings in the array together into one string.
This will join a range of elements from the array into a string, separating them with a given string.
e.g. joinIntoString (",") will turn an array of "a" "b" and "c" into "a,b,c".
Parameters
separatorString the string to insert between all the strings
startIndex the first element to join
numberOfElements how many elements to join together. If this is less than zero, all available elements will be used.
Definition at line 321 of file StringArray.cpp.
References beast::bmin(), beast::String::empty, beast::String::getCharPointer(), beast::String::isEmpty(), beast::String::preallocateBytes(), size(), beast::CharPointer_UTF8::sizeInBytes(), and strings.
Referenced by beast::Process::openDocument(), and beast::FileSearchPath::toString().
 {
     const int last = (numberToJoin < 0) ? size()
                                         : bmin (size(), start + numberToJoin);
     if (start < 0)
         start = 0;
     if (start >= last)
         return String::empty;
     if (start == last - 1)
         return strings.getReference (start);
     const size_t separatorBytes = separator.getCharPointer().sizeInBytes() - sizeof (String::CharPointerType::CharType);
     size_t bytesNeeded = separatorBytes * (size_t) (last - start - 1);
     for (int i = start; i < last; ++i)
         bytesNeeded += strings.getReference(i).getCharPointer().sizeInBytes() - sizeof (String::CharPointerType::CharType);
     String result;
     result.preallocateBytes (bytesNeeded);
     String::CharPointerType dest (result.getCharPointer());
     while (start < last)
     {
         const String& s = strings.getReference (start);
         if (! s.isEmpty())
             dest.writeAll (s.getCharPointer());
         if (++start < last && separatorBytes > 0)
             dest.writeAll (separator.getCharPointer());
     }
     dest.writeNull();
     return result;
 }
void beast::StringArray::minimiseStorageOverheads ()
Reduces the amount of storage being used by the array.
Arrays typically allocate slightly more storage than they need, and after removing elements, they may have quite a lot of unused space allocated. This method will reduce the amount of allocated storage to a minimum.
Definition at line 510 of file StringArray.cpp.
References strings.
Referenced by beast::StringPairArray::minimiseStorageOverheads().
 {
     strings.minimiseStorageOverheads();
 }
void beast::StringArray::move (int currentIndex, int newIndex) noexcept
Moves one of the strings to a different position.
This will move the string to a specified index, shuffling along any intervening elements as required.
So for example, if you have the array { 0, 1, 2, 3, 4, 5 } then calling move (2, 4) would result in { 0, 1, 3, 4, 2, 5 }.
Parameters
currentIndex the index of the value to be moved. If this isn't a valid index, then nothing will be done
newIndex the index at which you'd like this value to end up. If this is less than zero, the value will be moved to the end of the array
Definition at line 314 of file StringArray.cpp.
 {
     strings.move (currentIndex, newIndex);
 }
bool beast::StringArray::operator!= (const StringArray & other) const noexcept
Compares two arrays. Comparisons are case-sensitive.
Returns
false if the other array contains exactly the same strings in the same order
Definition at line 121 of file StringArray.cpp.
References beast::operator==().
 {
     return ! operator== (other);
 }
StringArray & beast::StringArray::operator= (const StringArray & other)
Copies the contents of another string array into this one
Definition at line 91 of file StringArray.cpp.
References strings.
 {
     strings = other.strings;
     return *this;
 }
bool beast::StringArray::operator== (const StringArray & other) const noexcept
Compares two arrays. Comparisons are case-sensitive.
Returns
true only if the other array contains exactly the same strings in the same order
Definition at line 109 of file StringArray.cpp.
 {
     if (other.size() != size())
         return false;
     for (int i = size(); --i >= 0;)
         if (other.strings.getReference(i) != strings.getReference(i))
             return false;
     return true;
 }
const String & beast::StringArray::operator[] (int index) const noexcept
Returns one of the strings from the array.
If the index is out-of-range, an empty string is returned.
Obviously the reference returned shouldn't be stored for later use, as the string it refers to may disappear when the array changes.
Definition at line 136 of file StringArray.cpp.
References beast::String::empty, and beast::isPositiveAndBelow().
 {
     if (isPositiveAndBelow (index, strings.size()))
         return strings.getReference (index);
     return String::empty;
 }
void beast::StringArray::remove (int index)
Removes a string from the array.
If the index is out-of-range, no action will be taken.
Definition at line 236 of file StringArray.cpp.
References strings.
Referenced by beast::FileSearchPath::remove(), beast::StringPairArray::remove(), beast::FileSearchPath::removeNonExistentPaths(), and beast::FileSearchPath::removeRedundantPaths().
 {
     strings.remove (index);
 }
void beast::StringArray::removeDuplicates (bool ignoreCase)
Removes any duplicated elements from the array.
If any string appears in the array more than once, only the first occurrence of it will be retained.
Parameters
ignoreCase whether to use a case-insensitive comparison
Definition at line 446 of file StringArray.cpp.
References indexOf(), size(), and strings.
 {
     for (int i = 0; i < size() - 1; ++i)
     {
         const String s (strings.getReference(i));
         int nextIndex = i + 1;
         for (;;)
         {
             nextIndex = indexOf (s, ignoreCase, nextIndex);
             if (nextIndex < 0)
                 break;
             strings.remove (nextIndex);
         }
     }
 }
void beast::StringArray::removeEmptyStrings (bool removeWhitespaceStrings = true)
Removes empty strings from the array.
Parameters
removeWhitespaceStrings if true, strings that only contain whitespace characters will also be removed
Definition at line 264 of file StringArray.cpp.
References size(), and strings.
Referenced by beast::FileSearchPath::init(), and beast::parseWildcards().
 {
     if (removeWhitespaceStrings)
     {
         for (int i = size(); --i >= 0;)
             if (! strings.getReference(i).containsNonWhitespaceChars())
                 strings.remove (i);
     }
     else
     {
         for (int i = size(); --i >= 0;)
             if (strings.getReference(i).isEmpty())
                 strings.remove (i);
     }
 }
void beast::StringArray::removeRange (int startIndex, int numberToRemove)
Removes a range of elements from the array.
This will remove a set of elements, starting from the given index, and move subsequent elements down to close the gap.
If the range extends beyond the bounds of the array, it will be safely clipped to the size of the array.
Parameters
startIndex the index of the first element to remove
numberToRemove how many elements should be removed
Definition at line 258 of file StringArray.cpp.
References strings.
 {
     strings.removeRange (startIndex, numberToRemove);
 }
void beast::StringArray::removeString (const String & stringToRemove, bool ignoreCase = false)
Finds a string in the array and removes it.
This will remove the first occurrence of the given string from the array. The comparison may be case-insensitive depending on the ignoreCase parameter.
Definition at line 241 of file StringArray.cpp.
References size(), and strings.
 {
     if (ignoreCase)
     {
         for (int i = size(); --i >= 0;)
             if (strings.getReference(i).equalsIgnoreCase (stringToRemove))
                 strings.remove (i);
     }
     else
     {
         for (int i = size(); --i >= 0;)
             if (stringToRemove == strings.getReference (i))
                 strings.remove (i);
     }
 }
void beast::StringArray::set (int index, const String & newString)
Replaces one of the strings in the array with another one.
If the index is higher than the array's size, the new string will be added to the end of the array; if it's less than zero nothing happens.
Definition at line 181 of file StringArray.cpp.
References strings.
Referenced by appendNumbersToDuplicates(), beast::FileSearchPath::init(), beast::StringPairArray::set(), and beast::FileSearchPath::toString().
 {
     strings.set (index, newString);
 }
int beast::StringArray::size () const inline noexcept
Returns the number of strings in the array
Definition at line 116 of file StringArray.h.
Referenced by addArray(), beast::FileSearchPath::addIfNotAlreadyThere(), ripple::Validators::ManagerImp::addStrings(), appendNumbersToDuplicates(), contains(), ripple::Validators::SourceStringsImp::fetch(), beast::fileMatches(), beast::FileSearchPath::findChildFiles(), beast::LinuxStatsHelpers::getCpuInfo(), beast::StringPairArray::getDescription(), beast::BSDStatsHelpers::getDmesgInfo(), beast::FileSearchPath::getNumPaths(), indexOf(), beast::FileSearchPath::init(), beast::FileSearchPath::isFileInPath(), beast::SemanticVersion::isRelease(), joinIntoString(), beast::DirectoryIterator::next(), beast::StringPairArray::operator==(), beast::SemanticVersion::parse(), beast::SemanticVersion::print(), beast::SemanticVersion::printIdentifiers(), removeDuplicates(), removeEmptyStrings(), beast::FileSearchPath::removeNonExistentPaths(), beast::FileSearchPath::removeRedundantPaths(), removeString(), beast::resolveXDGFolder(), beast::StringPairArray::size(), beast::FileSearchPath::toString(), and trim().
 { return strings.size(); };
void beast::StringArray::sort (bool ignoreCase)
Sorts the array into alphabetical order.
Parameters
ignoreCase if true, the comparisons used will be case-sensitive.
Definition at line 300 of file StringArray.cpp.
References strings.
 {
     if (ignoreCase)
     {
         InternalStringArrayComparator_CaseInsensitive comp;
         strings.sort (comp);
     }
     else
     {
         InternalStringArrayComparator_CaseSensitive comp;
         strings.sort (comp);
     }
 }
void beast::StringArray::swapWith (StringArray & other) noexcept
Swaps the contents of this and another StringArray.
Definition at line 126 of file StringArray.cpp.
Referenced by beast::StringPairArray::swapWith().
 {
     strings.swapWith (other.strings);
 }
void beast::StringArray::trim ()
Deletes any whitespace characters from the starts and ends of all the strings.
Definition at line 280 of file StringArray.cpp.
References size(), strings, and beast::String::trim().
Referenced by beast::LinuxStatsHelpers::getCpuInfo(), beast::FileSearchPath::init(), and beast::parseWildcards().
 {
     for (int i = size(); --i >= 0;)
     {
         String& s = strings.getReference(i);
         s = s.trim();
     }
 }
Member Data Documentation
Array<String> beast::StringArray::strings private
Definition at line 409 of file StringArray.h.
Referenced by add(), addArray(), addLines(), addTokens(), appendNumbersToDuplicates(), clear(), contains(), ensureStorageAllocated(), indexOf(), insert(), joinIntoString(), minimiseStorageOverheads(), operator=(), remove(), removeDuplicates(), removeEmptyStrings(), removeRange(), removeString(), set(), sort(), StringArray(), and trim().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_core/text/StringArray.h
rippled/src/beast/modules/beast_core/text/StringArray.cpp