rippled: beast::Workers Class Reference
beast::Workers Class Reference
#include <Workers.h>
Classes
struct Callback
struct PausedTag
class Worker
Public Member Functions
Workers (Callback &callback, String const &threadNames="Worker", int numberOfThreads=SystemStats::getNumCpus())
~Workers ()
int getNumberOfThreads () const noexcept
void setNumberOfThreads (int numberOfThreads)
void pauseAllThreadsAndWait ()
void addTask ()
int numberOfCurrentlyRunningTasks () const noexcept
Static Private Member Functions
static void deleteWorkers (LockFreeStack< Worker > &stack)
Private Attributes
Callback & m_callback
String m_threadNames
WaitableEvent m_allPaused
semaphore m_semaphore
int m_numberOfThreads
Atomic< int > m_activeCount
Atomic< int > m_pauseCount
Atomic< int > m_runningTaskCount
LockFreeStack< Worker > m_everyone
LockFreeStack< Worker, PausedTag > m_paused
Detailed Description
A group of threads that process tasks.
Definition at line 30 of file Workers.h.
Constructor & Destructor Documentation
beast::Workers::Workers (Callback & callback, String const & threadNames = "Worker", int numberOfThreads = SystemStats::getNumCpus ()) explicit
Create the object.
A number of initial threads may be optionally specified. The default is to create one thread per CPU.
Parameters
threadNames The name given to each created worker thread.
Definition at line 24 of file Workers.cpp.
References setNumberOfThreads().
     : m_callback (callback)
     , m_threadNames (threadNames)
     , m_allPaused (true, true)
     , m_semaphore (0)
     , m_numberOfThreads (0)
 {
     setNumberOfThreads (numberOfThreads);
 }
beast::Workers::~Workers ()
Definition at line 34 of file Workers.cpp.
References deleteWorkers(), m_everyone, and pauseAllThreadsAndWait().
 {
     pauseAllThreadsAndWait ();
     deleteWorkers (m_everyone);
 }
Member Function Documentation
void beast::Workers::addTask ()
Add a task to be performed.
Every call to addTask will eventually result in a call to Callback::processTask unless the Workers object is destroyed or the number of threads is never set above zero.
Note
This function is thread-safe.
Definition at line 108 of file Workers.cpp.
References m_semaphore, and beast::basic_semaphore< Mutex, CondVar >::signal().
Referenced by ripple::JobQueueImp::finishJob(), ripple::JobQueueImp::queueJob(), and beast::Workers_test::testThreads().
 {
     m_semaphore.signal ();
 }
void beast::Workers::deleteWorkers (LockFreeStack< Worker > & stack) static private
Definition at line 118 of file Workers.cpp.
References beast::LockFreeStack< Element, Tag >::pop_front().
Referenced by ~Workers().
 {
     for (;;)
     {
         Worker* const worker = stack.pop_front ();
         if (worker != nullptr)
         {
             // This call blocks until the thread orderly exits
             delete worker;
         }
         else
         {
             break;
         }
     }
 }
int beast::Workers::getNumberOfThreads () const noexcept
Retrieve the desired number of threads.
This just returns the number of active threads that were requested. If there was a recent call to setNumberOfThreads, the actual number of active threads may be temporarily different from what was last requested.
Note
This function is not thread-safe.
Definition at line 41 of file Workers.cpp.
References m_numberOfThreads.
Referenced by ripple::JobQueueImp::addJob(), ripple::JobQueueImp::getJson(), and beast::Workers_test::testThreads().
 {
     return m_numberOfThreads;
 }
int beast::Workers::numberOfCurrentlyRunningTasks () const noexcept
Get the number of currently executing calls of Callback::processTask. While this function is thread-safe, the value may not stay accurate for very long. It's mainly for diagnostic purposes.
Definition at line 113 of file Workers.cpp.
References beast::Atomic< Type >::get(), and m_runningTaskCount.
Referenced by pauseAllThreadsAndWait().
 {
     return m_runningTaskCount.get ();
 }
void beast::Workers::pauseAllThreadsAndWait ()
Pause all threads and wait until they are paused.
If a thread is processing a task it will pause as soon as the task completes. There may still be tasks signaled even after all threads have paused.
Note
This function is not thread-safe.
Definition at line 99 of file Workers.cpp.
References bassert, m_allPaused, numberOfCurrentlyRunningTasks(), setNumberOfThreads(), and beast::WaitableEvent::wait().
Referenced by ripple::JobQueueImp::shutdown(), beast::Workers_test::testThreads(), and ~Workers().
 {
     setNumberOfThreads (0);
     m_allPaused.wait ();
     bassert (numberOfCurrentlyRunningTasks () == 0);
 }
void beast::Workers::setNumberOfThreads (int numberOfThreads)
Set the desired number of threads.
Note
This function is not thread-safe.
Definition at line 50 of file Workers.cpp.
References m_everyone, m_numberOfThreads, m_pauseCount, m_paused, m_semaphore, m_threadNames, beast::Thread::notify(), and beast::basic_semaphore< Mutex, CondVar >::signal().
Referenced by pauseAllThreadsAndWait(), ripple::JobQueueImp::setThreadCount(), beast::Workers_test::testThreads(), and Workers().
 {
     if (m_numberOfThreads != numberOfThreads)
     {
         if (numberOfThreads > m_numberOfThreads)
         {
             // Increasing the number of working threads
             int const amount = numberOfThreads - m_numberOfThreads;
             for (int i = 0; i < amount; ++i)
             {
                 // See if we can reuse a paused worker
                 Worker* worker = m_paused.pop_front ();
                 if (worker != nullptr)
                 {
                     // If we got here then the worker thread is at [1]
                     // This will unblock their call to wait()
                     //
                     worker->notify ();
                 }
                 else
                 {
                     worker = new Worker (*this, m_threadNames);
                 }
                 m_everyone.push_front (worker);
             }
         }
         else if (numberOfThreads < m_numberOfThreads)
         {
             // Decreasing the number of working threads
             int const amount = m_numberOfThreads - numberOfThreads;
             for (int i = 0; i < amount; ++i)
             {
                 ++m_pauseCount;
                 // Pausing a thread counts as one "internal task"
                 m_semaphore.signal ();
             }
         }
         m_numberOfThreads = numberOfThreads;
     }
 }
Member Data Documentation
Atomic<int> beast::Workers::m_activeCount private
Definition at line 140 of file Workers.h.
WaitableEvent beast::Workers::m_allPaused private
Definition at line 137 of file Workers.h.
Referenced by pauseAllThreadsAndWait().
Callback& beast::Workers::m_callback private
Definition at line 135 of file Workers.h.
LockFreeStack<Worker> beast::Workers::m_everyone private
Definition at line 143 of file Workers.h.
Referenced by setNumberOfThreads(), and ~Workers().
int beast::Workers::m_numberOfThreads private
Definition at line 139 of file Workers.h.
Referenced by getNumberOfThreads(), and setNumberOfThreads().
Atomic<int> beast::Workers::m_pauseCount private
Definition at line 141 of file Workers.h.
Referenced by setNumberOfThreads().
LockFreeStack<Worker, PausedTag> beast::Workers::m_paused private
Definition at line 144 of file Workers.h.
Referenced by setNumberOfThreads().
Atomic<int> beast::Workers::m_runningTaskCount private
Definition at line 142 of file Workers.h.
Referenced by numberOfCurrentlyRunningTasks().
semaphore beast::Workers::m_semaphore private
Definition at line 138 of file Workers.h.
Referenced by addTask(), and setNumberOfThreads().
String beast::Workers::m_threadNames private
Definition at line 136 of file Workers.h.
Referenced by setNumberOfThreads().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_core/thread/Workers.h
rippled/src/beast/modules/beast_core/thread/Workers.cpp