rippled: rocksdb::FilterBlockReader Class Reference
rocksdb::FilterBlockReader Class Reference
#include <filter_block.h>
Public Member Functions
FilterBlockReader (const Options &opt, const Slice &contents, bool delete_contents_after_use=false)
bool KeyMayMatch (uint64_t block_offset, const Slice &key)
bool PrefixMayMatch (uint64_t block_offset, const Slice &prefix)
Private Member Functions
bool MayMatch (uint64_t block_offset, const Slice &entry)
Private Attributes
const FilterPolicy * policy_
const SliceTransform * prefix_extractor_
bool whole_key_filtering_
const char * data_
const char * offset_
size_t num_
size_t base_lg_
std::unique_ptr< const char[]> filter_data
Detailed Description
Definition at line 64 of file filter_block.h.
Constructor & Destructor Documentation
rocksdb::FilterBlockReader::FilterBlockReader (const Options & opt, const Slice & contents, bool delete_contents_after_use = false)
Definition at line 133 of file filter_block.cc.
References base_lg_, rocksdb::Slice::data(), data_, rocksdb::DecodeFixed32(), filter_data, num_, offset_, and rocksdb::Slice::size().
     : policy_(opt.filter_policy),
       prefix_extractor_(opt.prefix_extractor),
       whole_key_filtering_(opt.whole_key_filtering),
       data_(nullptr),
       offset_(nullptr),
       num_(0),
       base_lg_(0) {
   size_t n = contents.size();
   if (n < 5) return;  // 1 byte for base_lg_ and 4 for start of offset array
   base_lg_ = contents[n-1];
   uint32_t last_word = DecodeFixed32(contents.data() + n - 5);
   if (last_word > n - 5) return;
   data_ = contents.data();
   offset_ = data_ + last_word;
   num_ = (n - 5 - last_word) / 4;
   if (delete_contents_after_use) {
     filter_data.reset(contents.data());
   }
 }
Member Function Documentation
bool rocksdb::FilterBlockReader::KeyMayMatch (uint64_t block_offset, const Slice & key)
Definition at line 155 of file filter_block.cc.
References MayMatch(), and whole_key_filtering_.
Referenced by rocksdb::BlockBasedTable::Get(), and rocksdb::TEST().
{
   if (!whole_key_filtering_) {
     return true;
   }
   return MayMatch(block_offset, key);
 }
bool rocksdb::FilterBlockReader::MayMatch (uint64_t block_offset, const Slice & entry) private
Definition at line 171 of file filter_block.cc.
References base_lg_, data_, rocksdb::DecodeFixed32(), rocksdb::FilterPolicy::KeyMayMatch(), num_, offset_, and policy_.
Referenced by KeyMayMatch(), and PrefixMayMatch().
{
   uint64_t index = block_offset >> base_lg_;
   if (index < num_) {
     uint32_t start = DecodeFixed32(offset_ + index*4);
     uint32_t limit = DecodeFixed32(offset_ + index*4 + 4);
     if (start <= limit && limit <= (offset_ - data_)) {
       Slice filter = Slice(data_ + start, limit - start);
       return policy_->KeyMayMatch(entry, filter);
     } else if (start == limit) {
       // Empty filters do not match any entries
       return false;
     }
   }
   return true;  // Errors are treated as potential matches
 }
bool rocksdb::FilterBlockReader::PrefixMayMatch (uint64_t block_offset, const Slice & prefix)
Definition at line 163 of file filter_block.cc.
References MayMatch(), and prefix_extractor_.
{
   if (!prefix_extractor_) {
     return true;
   }
   return MayMatch(block_offset, prefix);
 }
Member Data Documentation
size_t rocksdb::FilterBlockReader::base_lg_ private
Definition at line 81 of file filter_block.h.
Referenced by FilterBlockReader(), and MayMatch().
const char* rocksdb::FilterBlockReader::data_ private
Definition at line 78 of file filter_block.h.
Referenced by FilterBlockReader(), and MayMatch().
std::unique_ptr<const char[]> rocksdb::FilterBlockReader::filter_data private
Definition at line 82 of file filter_block.h.
Referenced by FilterBlockReader().
size_t rocksdb::FilterBlockReader::num_ private
Definition at line 80 of file filter_block.h.
Referenced by FilterBlockReader(), and MayMatch().
const char* rocksdb::FilterBlockReader::offset_ private
Definition at line 79 of file filter_block.h.
Referenced by FilterBlockReader(), and MayMatch().
const FilterPolicy* rocksdb::FilterBlockReader::policy_ private
Definition at line 75 of file filter_block.h.
Referenced by MayMatch().
const SliceTransform* rocksdb::FilterBlockReader::prefix_extractor_ private
Definition at line 76 of file filter_block.h.
Referenced by PrefixMayMatch().
bool rocksdb::FilterBlockReader::whole_key_filtering_ private
Definition at line 77 of file filter_block.h.
Referenced by KeyMayMatch().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/table/filter_block.h
rippled/src/ripple/rocksdb/rocksdb/table/filter_block.cc