rippled: ripple::StringUtilities_test Class Reference
ripple::StringUtilities_test Class Reference
Public Member Functions
void testUnHexSuccess (std::string strIn, std::string strExpected)
void testUnHexFailure (std::string strIn)
void testUnHex ()
void testParseUrl ()
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 326 of file StringUtilities.cpp.
Member Function Documentation
void ripple::StringUtilities_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 415 of file StringUtilities.cpp.
References testParseUrl(), and testUnHex().
     {
         testParseUrl ();
         testUnHex ();
     }
void ripple::StringUtilities_test::testParseUrl () inline
Definition at line 369 of file StringUtilities.cpp.
References ripple::parseUrl(), beast::unit_test::suite::testcase(), and beast::unit_test::suite::unexpected().
Referenced by run().
     {
         testcase ("parseUrl");
         std::string strScheme;
         std::string strDomain;
         int         iPort;
         std::string strPath;
         unexpected (!parseUrl ("lower://domain", strScheme, strDomain, iPort, strPath),
             "parseUrl: lower://domain failed");
         unexpected (strScheme != "lower",
             "parseUrl: lower://domain : scheme failed");
         unexpected (strDomain != "domain",
             "parseUrl: lower://domain : domain failed");
         unexpected (iPort != -1,
             "parseUrl: lower://domain : port failed");
         unexpected (strPath != "",
             "parseUrl: lower://domain : path failed");
         unexpected (!parseUrl ("UPPER://domain:234/", strScheme, strDomain, iPort, strPath),
             "parseUrl: UPPER://domain:234/ failed");
         unexpected (strScheme != "upper",
             "parseUrl: UPPER://domain:234/ : scheme failed");
         unexpected (iPort != 234,
             boost::str (boost::format ("parseUrl: UPPER://domain:234/ : port failed: %d") % iPort));
         unexpected (strPath != "/",
             "parseUrl: UPPER://domain:234/ : path failed");
         unexpected (!parseUrl ("Mixed://domain/path", strScheme, strDomain, iPort, strPath),
             "parseUrl: Mixed://domain/path failed");
         unexpected (strScheme != "mixed",
             "parseUrl: Mixed://domain/path tolower failed");
         unexpected (strPath != "/path",
             "parseUrl: Mixed://domain/path path failed");
     }
void ripple::StringUtilities_test::testUnHex () inline
Definition at line 351 of file StringUtilities.cpp.
References beast::unit_test::suite::testcase(), testUnHexFailure(), and testUnHexSuccess().
Referenced by run().
     {
         testcase ("strUnHex");
         testUnHexSuccess ("526970706c6544", "RippleD");
         testUnHexSuccess ("A", "\n");
         testUnHexSuccess ("0A", "\n");
         testUnHexSuccess ("D0A", "\r\n");
         testUnHexSuccess ("0D0A", "\r\n");
         testUnHexSuccess ("200D0A", " \r\n");
         testUnHexSuccess ("282A2B2C2D2E2F29", "(*+,-./)");
         // Check for things which contain some or only invalid characters
         testUnHexFailure ("123X");
         testUnHexFailure ("V");
         testUnHexFailure ("XRP");
     }
void ripple::StringUtilities_test::testUnHexFailure (std::string strIn) inline
Definition at line 340 of file StringUtilities.cpp.
References beast::unit_test::suite::expect(), and ripple::strUnHex().
Referenced by testUnHex().
     {
         std::string strOut;
         expect (strUnHex (strOut, strIn) == -1,
             "strUnHex: parsing incorrect input succeeded");
         expect (strOut.empty (),
             "strUnHex: parsing incorrect input returned data");
     }
void ripple::StringUtilities_test::testUnHexSuccess (std::string strIn, std::string strExpected) inline
Definition at line 329 of file StringUtilities.cpp.
References beast::unit_test::suite::expect(), and ripple::strUnHex().
Referenced by testUnHex().
     {
         std::string strOut;
         expect (strUnHex (strOut, strIn) == strExpected.length (),
             "strUnHex: parsing correct input failed");
         expect (strOut == strExpected,
             "strUnHex: parsing doesn't produce expected result");
     }
The documentation for this class was generated from the following file:
rippled/src/ripple_basics/utility/StringUtilities.cpp