rippled: rocksdb::DBImpl Class Reference
rocksdb::DBImpl Class Reference
#include <db_impl.h>
Classes
struct CompactionState
struct CompactionStats
struct DeletionState
struct ManualCompaction
struct StatsSnapshot
struct Writer
Public Member Functions
DBImpl (const Options &options, const std::string &dbname)
virtual ~DBImpl ()
virtual Status Put (const WriteOptions &, const Slice &key, const Slice &value)
virtual Status Merge (const WriteOptions &, const Slice &key, const Slice &value)
virtual Status Delete (const WriteOptions &, const Slice &key)
virtual Status Write (const WriteOptions &options, WriteBatch *updates)
virtual Status Get (const ReadOptions &options, const Slice &key, std::string *value)
virtual std::vector< Status > MultiGet (const ReadOptions &options, const std::vector< Slice > &keys, std::vector< std::string > *values)
virtual bool KeyMayExist (const ReadOptions &options, const Slice &key, std::string *value, bool *value_found=nullptr)
virtual Iterator * NewIterator (const ReadOptions &)
virtual const Snapshot * GetSnapshot ()
virtual void ReleaseSnapshot (const Snapshot *snapshot)
virtual bool GetProperty (const Slice &property, std::string *value)
virtual void GetApproximateSizes (const Range *range, int n, uint64_t *sizes)
virtual void CompactRange (const Slice *begin, const Slice *end, bool reduce_level=false, int target_level=-1)
virtual int NumberLevels ()
virtual int MaxMemCompactionLevel ()
virtual int Level0StopWriteTrigger ()
virtual Status Flush (const FlushOptions &options)
virtual Status DisableFileDeletions ()
virtual Status EnableFileDeletions ()
virtual Status GetLiveFiles (std::vector< std::string > &, uint64_t *manifest_file_size, bool flush_memtable=true)
virtual Status GetSortedWalFiles (VectorLogPtr &files)
virtual SequenceNumber GetLatestSequenceNumber () const
virtual Status GetUpdatesSince (SequenceNumber seq_number, unique_ptr< TransactionLogIterator > *iter)
virtual Status DeleteFile (std::string name)
virtual void GetLiveFilesMetaData (std::vector< LiveFileMetaData > *metadata)
void TEST_CompactRange (int level, const Slice *begin, const Slice *end)
Status TEST_FlushMemTable ()
Status TEST_WaitForFlushMemTable ()
Status TEST_WaitForCompact ()
Iterator * TEST_NewInternalIterator ()
int64_t TEST_MaxNextLevelOverlappingBytes ()
void TEST_Destroy_DBImpl ()
uint64_t TEST_Current_Manifest_FileNo ()
void TEST_PurgeObsoleteteWAL ()
uint64_t TEST_GetLevel0TotalSize ()
void TEST_SetDefaultTimeToCheck (uint64_t default_interval_to_delete_obsolete_WAL)
void FindObsoleteFiles (DeletionState &deletion_state, bool force, bool no_full_scan=false)
void PurgeObsoleteFiles (DeletionState &deletion_state)
Public Member Functions inherited from rocksdb::DB
DB ()
virtual ~DB ()
Protected Member Functions
const Comparator * user_comparator () const
MemTable * GetMemTable ()
Iterator * NewInternalIterator (const ReadOptions &, SequenceNumber *latest_snapshot)
Protected Attributes
Env *const env_
const std::string dbname_
unique_ptr< VersionSet > versions_
const InternalKeyComparator internal_comparator_
const Options options_
Private Member Functions
Status NewDB ()
Status Recover (VersionEdit *edit, MemTable *external_table=nullptr, bool error_if_log_file_exist=false)
void MaybeIgnoreError (Status *s) const
const Status CreateArchivalDirectory ()
void DeleteObsoleteFiles ()
Status FlushMemTableToOutputFile (bool *madeProgress, DeletionState &deletion_state)
Status RecoverLogFile (uint64_t log_number, VersionEdit *edit, SequenceNumber *max_sequence, MemTable *external_table)
Status WriteLevel0TableForRecovery (MemTable *mem, VersionEdit *edit)
Status WriteLevel0Table (std::vector< MemTable * > &mems, VersionEdit *edit, uint64_t *filenumber)
uint64_t SlowdownAmount (int n, int top, int bottom)
Status MakeRoomForWrite (bool force)
WriteBatch * BuildBatchGroup (Writer **last_writer)
Status FlushMemTable (const FlushOptions &options)
Status WaitForFlushMemTable ()
void MaybeScheduleLogDBDeployStats ()
void LogDBDeployStats ()
void MaybeScheduleFlushOrCompaction ()
void BackgroundCallCompaction ()
void BackgroundCallFlush ()
Status BackgroundCompaction (bool *madeProgress, DeletionState &deletion_state)
Status BackgroundFlush (bool *madeProgress, DeletionState &deletion_state)
void CleanupCompaction (CompactionState *compact, Status status)
Status DoCompactionWork (CompactionState *compact, DeletionState &deletion_state)
Status OpenCompactionOutputFile (CompactionState *compact)
Status FinishCompactionOutputFile (CompactionState *compact, Iterator *input)
Status InstallCompactionResults (CompactionState *compact)
void AllocateCompactionOutputFileNumbers (CompactionState *compact)
void ReleaseCompactionUnusedFileNumbers (CompactionState *compact)
void PurgeObsoleteWALFiles ()
Status AppendSortedWalsOfType (const std::string &path, VectorLogPtr &log_files, WalFileType type)
Status RetainProbableWalFiles (VectorLogPtr &all_logs, const SequenceNumber target)
bool CheckWalFileExistsAndEmpty (const WalFileType type, const uint64_t number)
Status ReadFirstRecord (const WalFileType type, const uint64_t number, WriteBatch *const result)
Status ReadFirstLine (const std::string &fname, WriteBatch *const batch)
void PrintStatistics ()
void MaybeDumpStats ()
int FindMinimumEmptyLevelFitting (int level)
void ReFitLevel (int level, int target_level=-1)
DBImpl (const DBImpl &)
void operator= (const DBImpl &)
void DelayLoggingAndReset ()
SequenceNumber findEarliestVisibleSnapshot (SequenceNumber in, std::vector< SequenceNumber > &snapshots, SequenceNumber *prev_snapshot)
Status GetImpl (const ReadOptions &options, const Slice &key, std::string *value, bool *value_found=nullptr)
Static Private Member Functions
static void BGLogDBDeployStats (void *db)
static void BGWorkCompaction (void *db)
static void BGWorkFlush (void *db)
Private Attributes
const InternalFilterPolicy internal_filter_policy_
bool owns_info_log_
unique_ptr< TableCache > table_cache_
FileLock * db_lock_
port::Mutex mutex_
port::AtomicPointer shutting_down_
port::CondVar bg_cv_
std::shared_ptr
< MemTableRepFactory > mem_rep_factory_
MemTable * mem_
MemTableList imm_
uint64_t logfile_number_
unique_ptr< log::Writer > log_
std::string host_name_
std::deque< Writer * > writers_
WriteBatch tmp_batch_
SnapshotList snapshots_
std::set< uint64_t > pending_outputs_
int bg_compaction_scheduled_
int bg_flush_scheduled_
bool bg_logstats_scheduled_
ManualCompaction * manual_compaction_
Status bg_error_
std::unique_ptr< StatsLogger > logger_
int64_t volatile last_log_ts
bool disable_delete_obsolete_files_
uint64_t delete_obsolete_files_last_run_
uint64_t purge_wal_files_last_run_
std::atomic< uint64_t > last_stats_dump_time_microsec_
uint64_t default_interval_to_delete_obsolete_WAL_
uint64_t stall_level0_slowdown_
uint64_t stall_memtable_compaction_
uint64_t stall_level0_num_files_
std::vector< uint64_t > stall_leveln_slowdown_
uint64_t stall_level0_slowdown_count_
uint64_t stall_memtable_compaction_count_
uint64_t stall_level0_num_files_count_
std::vector< uint64_t > stall_leveln_slowdown_count_
const uint64_t started_at_
bool flush_on_destroy_
std::vector< CompactionStats > stats_
StatsSnapshot last_stats_
std::string db_absolute_path_
int delayed_writes_
const EnvOptions storage_options_
bool bg_work_gate_closed_
bool refitting_level_
Static Private Attributes
static const int KEEP_LOG_FILE_NUM = 1000
Friends
class DB
Additional Inherited Members
Static Public Member Functions inherited from rocksdb::DB
static Status Open (const Options &options, const std::string &name, DB **dbptr)
static Status OpenForReadOnly (const Options &options, const std::string &name, DB **dbptr, bool error_if_log_file_exist=false)
Detailed Description
Definition at line 34 of file db_impl.h.
Constructor & Destructor Documentation
rocksdb::DBImpl::DBImpl (const Options & options, const std::string & dbname)
Definition at line 226 of file db_impl.cc.
References db_absolute_path_, dbname_, rocksdb::Options::Dump(), rocksdb::dumpLeveldbBuildVersion(), env_, rocksdb::Env::GetAbsolutePath(), rocksdb::Env::GetHostName(), host_name_, rocksdb::Options::info_log, internal_comparator_, last_log_ts, rocksdb::Log(), rocksdb::LogFlush(), rocksdb::Options::max_open_files, mem_, name, rocksdb::Options::num_levels, rocksdb::Status::ok(), options_, rocksdb::MemTable::Ref(), stall_leveln_slowdown_, stall_leveln_slowdown_count_, storage_options_, table_cache_, and versions_.
     : env_(options.env),
       dbname_(dbname),
       internal_comparator_(options.comparator),
       options_(SanitizeOptions(
           dbname, &internal_comparator_, &internal_filter_policy_, options)),
       internal_filter_policy_(options.filter_policy),
       owns_info_log_(options_.info_log != options.info_log),
       db_lock_(nullptr),
       mutex_(options.use_adaptive_mutex),
       shutting_down_(nullptr),
       bg_cv_(&mutex_),
       mem_rep_factory_(options_.memtable_factory),
       mem_(new MemTable(internal_comparator_, mem_rep_factory_,
         NumberLevels(), options_)),
       logfile_number_(0),
       tmp_batch_(),
       bg_compaction_scheduled_(0),
       bg_flush_scheduled_(0),
       bg_logstats_scheduled_(false),
       manual_compaction_(nullptr),
       logger_(nullptr),
       disable_delete_obsolete_files_(false),
       delete_obsolete_files_last_run_(options.env->NowMicros()),
       purge_wal_files_last_run_(0),
       last_stats_dump_time_microsec_(0),
       default_interval_to_delete_obsolete_WAL_(600),
       stall_level0_slowdown_(0),
       stall_memtable_compaction_(0),
       stall_level0_num_files_(0),
       stall_level0_slowdown_count_(0),
       stall_memtable_compaction_count_(0),
       stall_level0_num_files_count_(0),
       started_at_(options.env->NowMicros()),
       flush_on_destroy_(false),
       stats_(options.num_levels),
       delayed_writes_(0),
       storage_options_(options),
       bg_work_gate_closed_(false),
       refitting_level_(false) {
   mem_->Ref();
   env_->GetAbsolutePath(dbname, &db_absolute_path_);
   stall_leveln_slowdown_.resize(options.num_levels);
   stall_leveln_slowdown_count_.resize(options.num_levels);
   for (int i = 0; i < options.num_levels; ++i) {
     stall_leveln_slowdown_[i] = 0;
     stall_leveln_slowdown_count_[i] = 0;
   }
   // Reserve ten files or so for other uses and give the rest to TableCache.
   const int table_cache_size = options_.max_open_files - 10;
   table_cache_.reset(new TableCache(dbname_, &options_,
                                     storage_options_, table_cache_size));
   versions_.reset(new VersionSet(dbname_, &options_, storage_options_,
                                  table_cache_.get(), &internal_comparator_));
 #ifdef ROCKSDB_LDB_BUILD_VERSION
   dumpLeveldbBuildVersion(options_.info_log.get());
 #endif
   options_.Dump(options_.info_log.get());
   char name[100];
   Status st = env_->GetHostName(name, 100L);
   if (st.ok()) {
     host_name_ = name;
   } else {
     Log(options_.info_log, "Can't get hostname, use localhost as host name.");
     host_name_ = "localhost";
   }
   last_log_ts = 0;
   LogFlush(options_.info_log);
 }
rocksdb::DBImpl::~DBImpl () virtual
Definition at line 305 of file db_impl.cc.
References bg_compaction_scheduled_, bg_cv_, bg_flush_scheduled_, bg_logstats_scheduled_, db_lock_, env_, flush_on_destroy_, FlushMemTable(), rocksdb::MemTable::GetFirstSequenceNumber(), imm_, rocksdb::Options::info_log, rocksdb::port::Mutex::Lock(), rocksdb::LogFlush(), mem_, mutex_, options_, rocksdb::port::AtomicPointer::Release_Store(), shutting_down_, rocksdb::port::Mutex::Unlock(), rocksdb::Env::UnlockFile(), rocksdb::MemTable::Unref(), rocksdb::MemTableList::UnrefAll(), and rocksdb::port::CondVar::Wait().
                 {
   // Wait for background work to finish
   if (flush_on_destroy_ && mem_->GetFirstSequenceNumber() != 0) {
     FlushMemTable(FlushOptions());
   }
   mutex_.Lock();
   shutting_down_.Release_Store(this);  // Any non-nullptr value is ok
   while (bg_compaction_scheduled_ ||
          bg_flush_scheduled_ ||
          bg_logstats_scheduled_) {
     bg_cv_.Wait();
   }
   mutex_.Unlock();
   if (db_lock_ != nullptr) {
     env_->UnlockFile(db_lock_);
   }
   if (mem_ != nullptr) mem_->Unref();
   imm_.UnrefAll();
   LogFlush(options_.info_log);
 }
rocksdb::DBImpl::DBImpl (const DBImpl &) private
Member Function Documentation
void rocksdb::DBImpl::AllocateCompactionOutputFileNumbers (CompactionState * compact) private
Definition at line 1887 of file db_impl.cc.
References rocksdb::DBImpl::CompactionState::allocated_file_numbers, rocksdb::port::Mutex::AssertHeld(), rocksdb::DBImpl::CompactionState::builder, rocksdb::DBImpl::CompactionState::compaction, mutex_, rocksdb::Compaction::num_input_files(), pending_outputs_, and versions_.
Referenced by DoCompactionWork().
{
   mutex_.AssertHeld();
   assert(compact != nullptr);
   assert(compact->builder == nullptr);
   int filesNeeded = compact->compaction->num_input_files(1);
   for (int i = 0; i < filesNeeded; i++) {
     uint64_t file_number = versions_->NewFileNumber();
     pending_outputs_.insert(file_number);
     compact->allocated_file_numbers.push_back(file_number);
   }
 }
Status rocksdb::DBImpl::AppendSortedWalsOfType (const std::string & path, VectorLogPtr & log_files, WalFileType type) private
Definition at line 1442 of file db_impl.cc.
References CheckWalFileExistsAndEmpty(), env_, ripple::f, rocksdb::Env::GetChildren(), rocksdb::Env::GetFileSize(), rocksdb::kLogFile, rocksdb::LogFileName(), rocksdb::Status::ok(), rocksdb::ParseFileName(), ReadFirstRecord(), and rocksdb::WriteBatchInternal::Sequence().
Referenced by GetSortedWalFiles(), and PurgeObsoleteWALFiles().
{
   std::vector<std::string> all_files;
   const Status status = env_->GetChildren(path, &all_files);
   if (!status.ok()) {
     return status;
   }
   log_files.reserve(log_files.size() + all_files.size());
   VectorLogPtr::iterator pos_start;
   if (!log_files.empty()) {
     pos_start = log_files.end() - 1;
   } else {
     pos_start = log_files.begin();
   }
   for (const auto& f : all_files) {
     uint64_t number;
     FileType type;
     if (ParseFileName(f, &number, &type) && type == kLogFile){
       WriteBatch batch;
       Status s = ReadFirstRecord(log_type, number, &batch);
       if (!s.ok()) {
         if (CheckWalFileExistsAndEmpty(log_type, number)) {
           continue;
         }
         return s;
       }
       uint64_t size_bytes;
       s = env_->GetFileSize(LogFileName(path, number), &size_bytes);
       if (!s.ok()) {
         return s;
       }
       log_files.push_back(std::move(unique_ptr<LogFile>(new LogFileImpl(
         number, log_type, WriteBatchInternal::Sequence(&batch), size_bytes))));
     }
   }
   CompareLogByPointer compare_log_files;
   std::sort(pos_start, log_files.end(), compare_log_files);
   return status;
 }
void rocksdb::DBImpl::BackgroundCallCompaction () private
Definition at line 1694 of file db_impl.cc.
References rocksdb::port::AtomicPointer::Acquire_Load(), BackgroundCompaction(), bg_compaction_scheduled_, bg_cv_, env_, FindObsoleteFiles(), rocksdb::DBImpl::DeletionState::HaveSomethingToDelete(), rocksdb::Options::info_log, rocksdb::port::Mutex::Lock(), rocksdb::Log(), rocksdb::LogFlush(), MaybeDumpStats(), MaybeScheduleFlushOrCompaction(), MaybeScheduleLogDBDeployStats(), mutex_, rocksdb::Status::ok(), options_, PurgeObsoleteFiles(), shutting_down_, rocksdb::port::CondVar::SignalAll(), rocksdb::Env::SleepForMicroseconds(), rocksdb::Status::ToString(), and rocksdb::port::Mutex::Unlock().
Referenced by BGWorkCompaction().
{
   bool madeProgress = false;
   DeletionState deletion_state;
   MaybeDumpStats();
   MutexLock l(&mutex_);
   // Log(options_.info_log, "XXX BG Thread %llx process new work item", pthread_self());
   assert(bg_compaction_scheduled_);
   Status s;
   if (!shutting_down_.Acquire_Load()) {
     s = BackgroundCompaction(&madeProgress, deletion_state);
     if (!s.ok()) {
       // Wait a little bit before retrying background compaction in
       // case this is an environmental problem and we do not want to
       // chew up resources for failed compactions for the duration of
       // the problem.
       bg_cv_.SignalAll();  // In case a waiter can proceed despite the error
       Log(options_.info_log, "Waiting after background compaction error: %s",
           s.ToString().c_str());
       mutex_.Unlock();
       LogFlush(options_.info_log);
       env_->SleepForMicroseconds(1000000);
       mutex_.Lock();
     }
   }
   // If !s.ok(), this means that Compaction failed. In that case, we want
   // to delete all obsolete files we might have created and we force
   // FindObsoleteFiles(). This is because deletion_state does not catch
   // all created files if compaction failed.
   FindObsoleteFiles(deletion_state, !s.ok());
   // delete unnecessary files if any, this is done outside the mutex
   if (deletion_state.HaveSomethingToDelete()) {
     mutex_.Unlock();
     PurgeObsoleteFiles(deletion_state);
     mutex_.Lock();
   }
   bg_compaction_scheduled_--;
   MaybeScheduleLogDBDeployStats();
   // Previous compaction may have produced too many files in a level,
   // So reschedule another compaction if we made progress in the
   // last compaction.
   if (madeProgress) {
     MaybeScheduleFlushOrCompaction();
   }
   bg_cv_.SignalAll();
 }
void rocksdb::DBImpl::BackgroundCallFlush () private
Definition at line 1648 of file db_impl.cc.
References rocksdb::port::AtomicPointer::Acquire_Load(), BackgroundFlush(), bg_cv_, bg_flush_scheduled_, env_, FindObsoleteFiles(), rocksdb::DBImpl::DeletionState::HaveSomethingToDelete(), rocksdb::Options::info_log, rocksdb::port::Mutex::Lock(), rocksdb::Log(), rocksdb::LogFlush(), MaybeScheduleFlushOrCompaction(), mutex_, rocksdb::Status::ok(), options_, PurgeObsoleteFiles(), shutting_down_, rocksdb::port::CondVar::SignalAll(), rocksdb::Env::SleepForMicroseconds(), rocksdb::Status::ToString(), and rocksdb::port::Mutex::Unlock().
Referenced by BGWorkFlush().
{
   bool madeProgress = false;
   DeletionState deletion_state;
   assert(bg_flush_scheduled_);
   MutexLock l(&mutex_);
   Status s;
   if (!shutting_down_.Acquire_Load()) {
     s = BackgroundFlush(&madeProgress, deletion_state);
     if (!s.ok()) {
       // Wait a little bit before retrying background compaction in
       // case this is an environmental problem and we do not want to
       // chew up resources for failed compactions for the duration of
       // the problem.
       bg_cv_.SignalAll();  // In case a waiter can proceed despite the error
       Log(options_.info_log, "Waiting after background flush error: %s",
           s.ToString().c_str());
       mutex_.Unlock();
       LogFlush(options_.info_log);
       env_->SleepForMicroseconds(1000000);
       mutex_.Lock();
     }
   }
   // If !s.ok(), this means that Flush failed. In that case, we want
   // to delete all obsolete files and we force FindObsoleteFiles()
   FindObsoleteFiles(deletion_state, !s.ok());
   // delete unnecessary files if any, this is done outside the mutex
   if (deletion_state.HaveSomethingToDelete()) {
     mutex_.Unlock();
     PurgeObsoleteFiles(deletion_state);
     mutex_.Lock();
   }
   bg_flush_scheduled_--;
   if (madeProgress) {
     MaybeScheduleFlushOrCompaction();
   }
   bg_cv_.SignalAll();
 }
Status rocksdb::DBImpl::BackgroundCompaction (bool * madeProgress, DeletionState & deletion_state) private
Definition at line 1747 of file db_impl.cc.
References rocksdb::port::AtomicPointer::Acquire_Load(), rocksdb::port::Mutex::AssertHeld(), rocksdb::DBImpl::ManualCompaction::begin, bg_compaction_scheduled_, bg_error_, CleanupCompaction(), rocksdb::Options::compaction_style, rocksdb::InternalKey::DebugString(), rocksdb::Options::disable_auto_compactions, DoCompactionWork(), rocksdb::DBImpl::ManualCompaction::done, rocksdb::DBImpl::ManualCompaction::end, ripple::f, FlushMemTableToOutputFile(), imm_, rocksdb::DBImpl::ManualCompaction::in_progress, rocksdb::Options::info_log, rocksdb::MemTableList::IsFlushPending(), rocksdb::kCompactionStyleUniversal, rocksdb::DBImpl::ManualCompaction::level, rocksdb::Log(), manual_compaction_, rocksdb::Options::max_background_compactions, MaybeScheduleFlushOrCompaction(), rocksdb::Options::min_write_buffer_number_to_merge, mutex_, rocksdb::Status::ok(), options_, rocksdb::Options::paranoid_checks, shutting_down_, rocksdb::DBImpl::ManualCompaction::tmp_storage, rocksdb::Status::ToString(), and versions_.
Referenced by BackgroundCallCompaction().
{
   *madeProgress = false;
   mutex_.AssertHeld();
   // TODO: remove memtable flush from formal compaction
   while (imm_.IsFlushPending(options_.min_write_buffer_number_to_merge)) {
     Log(options_.info_log,
         "BackgroundCompaction doing FlushMemTableToOutputFile, compaction slots "
         "available %d",
         options_.max_background_compactions - bg_compaction_scheduled_);
     Status stat = FlushMemTableToOutputFile(madeProgress, deletion_state);
     if (!stat.ok()) {
       return stat;
     }
   }
   unique_ptr<Compaction> c;
   bool is_manual = (manual_compaction_ != nullptr) &&
                    (manual_compaction_->in_progress == false);
   InternalKey manual_end;
   if (is_manual) {
     ManualCompaction* m = manual_compaction_;
     assert(!m->in_progress);
     m->in_progress = true; // another thread cannot pick up the same work
     c.reset(versions_->CompactRange(m->level, m->begin, m->end));
     if (c) {
       manual_end = c->input(0, c->num_input_files(0) - 1)->largest;
     } else {
       m->done = true;
     }
     Log(options_.info_log,
         "Manual compaction at level-%d from %s .. %s; will stop at %s\n",
         m->level,
         (m->begin ? m->begin->DebugString().c_str() : "(begin)"),
         (m->end ? m->end->DebugString().c_str() : "(end)"),
         (m->done ? "(end)" : manual_end.DebugString().c_str()));
   } else if (!options_.disable_auto_compactions) {
     c.reset(versions_->PickCompaction());
   }
   Status status;
   if (!c) {
     // Nothing to do
     Log(options_.info_log, "Compaction nothing to do");
   } else if (!is_manual && c->IsTrivialMove()) {
     // Move file to next level
     assert(c->num_input_files(0) == 1);
     FileMetaData* f = c->input(0, 0);
     c->edit()->DeleteFile(c->level(), f->number);
     c->edit()->AddFile(c->level() + 1, f->number, f->file_size,
                        f->smallest, f->largest,
                        f->smallest_seqno, f->largest_seqno);
     status = versions_->LogAndApply(c->edit(), &mutex_);
     VersionSet::LevelSummaryStorage tmp;
     Log(options_.info_log, "Moved #%lld to level-%d %lld bytes %s: %s\n",
         static_cast<unsigned long long>(f->number),
         c->level() + 1,
         static_cast<unsigned long long>(f->file_size),
         status.ToString().c_str(),
         versions_->LevelSummary(&tmp));
     versions_->ReleaseCompactionFiles(c.get(), status);
     *madeProgress = true;
   } else {
     MaybeScheduleFlushOrCompaction(); // do more compaction work in parallel.
     CompactionState* compact = new CompactionState(c.get());
     status = DoCompactionWork(compact, deletion_state);
     CleanupCompaction(compact, status);
     versions_->ReleaseCompactionFiles(c.get(), status);
     c->ReleaseInputs();
     *madeProgress = true;
   }
   c.reset();
   if (status.ok()) {
     // Done
   } else if (shutting_down_.Acquire_Load()) {
     // Ignore compaction errors found during shutting down
   } else {
     Log(options_.info_log,
         "Compaction error: %s", status.ToString().c_str());
     if (options_.paranoid_checks && bg_error_.ok()) {
       bg_error_ = status;
     }
   }
   if (is_manual) {
     ManualCompaction* m = manual_compaction_;
     if (!status.ok()) {
       m->done = true;
     }
     // For universal compaction:
     //   Because universal compaction always happens at level 0, so one
     //   compaction will pick up all overlapped files. No files will be
     //   filtered out due to size limit and left for a successive compaction.
     //   So we can safely conclude the current compaction.
     //
     //   Also note that, if we don't stop here, then the current compaction
     //   writes a new file back to level 0, which will be used in successive
     //   compaction. Hence the manual compaction will never finish.
     if (options_.compaction_style == kCompactionStyleUniversal) {
       m->done = true;
     }
     if (!m->done) {
       // We only compacted part of the requested range.  Update *m
       // to the range that is left to be compacted.
       m->tmp_storage = manual_end;
       m->begin = &m->tmp_storage;
     }
     m->in_progress = false; // not being processed anymore
     manual_compaction_ = nullptr;
   }
   return status;
 }
Status rocksdb::DBImpl::BackgroundFlush (bool * madeProgress, DeletionState & deletion_state) private
Definition at line 1635 of file db_impl.cc.
References bg_flush_scheduled_, FlushMemTableToOutputFile(), imm_, rocksdb::Options::info_log, rocksdb::MemTableList::IsFlushPending(), rocksdb::Log(), rocksdb::Options::max_background_flushes, rocksdb::Options::min_write_buffer_number_to_merge, rocksdb::Status::ok(), and options_.
Referenced by BackgroundCallFlush().
{
   Status stat;
   while (stat.ok() &&
          imm_.IsFlushPending(options_.min_write_buffer_number_to_merge)) {
     Log(options_.info_log,
         "BackgroundCallFlush doing FlushMemTableToOutputFile, flush slots available %d",
         options_.max_background_flushes - bg_flush_scheduled_);
     stat = FlushMemTableToOutputFile(madeProgress, deletion_state);
   }
   return stat;
 }
void rocksdb::DBImpl::BGLogDBDeployStats (void * db) static private
Definition at line 47 of file db_stats_logger.cc.
References db, and LogDBDeployStats().
Referenced by MaybeScheduleLogDBDeployStats().
{
   DBImpl* db_inst = reinterpret_cast<DBImpl*>(db);
   db_inst->LogDBDeployStats();
 }
void rocksdb::DBImpl::BGWorkCompaction (void * db) static private
Definition at line 1631 of file db_impl.cc.
References BackgroundCallCompaction(), and db.
Referenced by MaybeScheduleFlushOrCompaction().
{
   reinterpret_cast<DBImpl*>(db)->BackgroundCallCompaction();
 }
void rocksdb::DBImpl::BGWorkFlush (void * db) static private
Definition at line 1627 of file db_impl.cc.
References BackgroundCallFlush(), and db.
Referenced by MaybeScheduleFlushOrCompaction().
{
   reinterpret_cast<DBImpl*>(db)->BackgroundCallFlush();
 }
WriteBatch * rocksdb::DBImpl::BuildBatchGroup (Writer ** last_writer) private
Definition at line 2866 of file db_impl.cc.
References rocksdb::WriteBatchInternal::Append(), rocksdb::DBImpl::Writer::batch, rocksdb::WriteBatchInternal::ByteSize(), rocksdb::WriteBatchInternal::Count(), rocksdb::DBImpl::Writer::disableWAL, beast.util.Iter::first(), rocksdb::DBImpl::Writer::sync, tmp_batch_, and writers_.
Referenced by Write().
{
   assert(!writers_.empty());
   Writer* first = writers_.front();
   WriteBatch* result = first->batch;
   assert(result != nullptr);
   size_t size = WriteBatchInternal::ByteSize(first->batch);
   // Allow the group to grow up to a maximum size, but if the
   // original write is small, limit the growth so we do not slow
   // down the small write too much.
   size_t max_size = 1 << 20;
   if (size <= (128<<10)) {
     max_size = size + (128<<10);
   }
   *last_writer = first;
   std::deque<Writer*>::iterator iter = writers_.begin();
   ++iter;  // Advance past "first"
   for (; iter != writers_.end(); ++iter) {
     Writer* w = *iter;
     if (w->sync && !first->sync) {
       // Do not include a sync write into a batch handled by a non-sync write.
       break;
     }
     if (!w->disableWAL && first->disableWAL) {
       // Do not include a write that needs WAL into a batch that has
       // WAL disabled.
       break;
     }
     if (w->batch != nullptr) {
       size += WriteBatchInternal::ByteSize(w->batch);
       if (size > max_size) {
         // Do not make batch too big
         break;
       }
       // Append to *reuslt
       if (result == first->batch) {
         // Switch to temporary batch instead of disturbing caller's batch
         result = &tmp_batch_;
         assert(WriteBatchInternal::Count(result) == 0);
         WriteBatchInternal::Append(result, first->batch);
       }
       WriteBatchInternal::Append(result, w->batch);
     }
     *last_writer = w;
   }
   return result;
 }
bool rocksdb::DBImpl::CheckWalFileExistsAndEmpty (const WalFileType type, const uint64_t number) private
Definition at line 1353 of file db_impl.cc.
References rocksdb::ArchivedLogFileName(), env_, rocksdb::Env::GetFileSize(), rocksdb::kAliveLogFile, rocksdb::LogFileName(), rocksdb::Status::ok(), options_, and rocksdb::Options::wal_dir.
Referenced by AppendSortedWalsOfType().
{
   const std::string fname = (type == kAliveLogFile) ?
     LogFileName(options_.wal_dir, number) :
     ArchivedLogFileName(options_.wal_dir, number);
   uint64_t file_size;
   Status s = env_->GetFileSize(fname, &file_size);
   return (s.ok() && (file_size == 0));
 }
void rocksdb::DBImpl::CleanupCompaction (CompactionState * compact, Status status) private
Definition at line 1862 of file db_impl.cc.
References rocksdb::port::Mutex::AssertHeld(), rocksdb::DBImpl::CompactionState::builder, mutex_, rocksdb::DBImpl::CompactionState::Output::number, rocksdb::Status::ok(), rocksdb::DBImpl::CompactionState::outfile, rocksdb::DBImpl::CompactionState::outputs, pending_outputs_, and table_cache_.
Referenced by BackgroundCompaction().
{
   mutex_.AssertHeld();
   if (compact->builder != nullptr) {
     // May happen if we get a shutdown call in the middle of compaction
     compact->builder->Abandon();
     compact->builder.reset();
   } else {
     assert(compact->outfile == nullptr);
   }
   for (size_t i = 0; i < compact->outputs.size(); i++) {
     const CompactionState::Output& out = compact->outputs[i];
     pending_outputs_.erase(out.number);
     // If this file was inserted into the table cache then remove
     // them here because this compaction was not committed.
     if (!status.ok()) {
       table_cache_->Evict(out.number);
     }
   }
   delete compact;
 }
void rocksdb::DBImpl::CompactRange (const Slice * begin, const Slice * end, bool reduce_level = false, int target_level = -1) virtual
Implements rocksdb::DB.
Reimplemented in rocksdb::DBImplReadOnly.
Definition at line 1184 of file db_impl.cc.
References base, rocksdb::Options::info_log, rocksdb::LogFlush(), mutex_, NumberLevels(), options_, rocksdb::Version::OverlapInLevel(), ReFitLevel(), TEST_CompactRange(), TEST_FlushMemTable(), and versions_.
Referenced by rocksdb::PrefixScanInit(), and rocksdb::TEST().
{
   int max_level_with_files = 1;
   {
     MutexLock l(&mutex_);
     Version* base = versions_->current();
     for (int level = 1; level < NumberLevels(); level++) {
       if (base->OverlapInLevel(level, begin, end)) {
         max_level_with_files = level;
       }
     }
   }
   TEST_FlushMemTable(); // TODO(sanjay): Skip if memtable does not overlap
   for (int level = 0; level < max_level_with_files; level++) {
     TEST_CompactRange(level, begin, end);
   }
   if (reduce_level) {
     ReFitLevel(max_level_with_files, target_level);
   }
   LogFlush(options_.info_log);
 }
const Status rocksdb::DBImpl::CreateArchivalDirectory () private
Definition at line 401 of file db_impl.cc.
References rocksdb::ArchivalDirectory(), rocksdb::Env::CreateDirIfMissing(), env_, rocksdb::Status::OK(), options_, rocksdb::Options::wal_dir, rocksdb::Options::WAL_size_limit_MB, and rocksdb::Options::WAL_ttl_seconds.
Referenced by rocksdb::DB::Open().
{
   if (options_.WAL_ttl_seconds > 0 || options_.WAL_size_limit_MB > 0) {
     std::string archivalPath = ArchivalDirectory(options_.wal_dir);
     return env_->CreateDirIfMissing(archivalPath);
   }
   return Status::OK();
 }
void rocksdb::DBImpl::DelayLoggingAndReset () inline private
Definition at line 3348 of file db_impl.cc.
References delayed_writes_, rocksdb::Options::info_log, rocksdb::Log(), and options_.
Referenced by MakeRoomForWrite().
{
   if (delayed_writes_ > 0) {
     Log(options_.info_log, "delayed %d write...\n", delayed_writes_ );
     delayed_writes_ = 0;
   }
 }
Status rocksdb::DBImpl::Delete (const WriteOptions & options, const Slice & key) virtual
Implements rocksdb::DB.
Reimplemented in rocksdb::DBImplReadOnly.
Definition at line 2755 of file db_impl.cc.
References rocksdb::DB::Delete().
Referenced by Counters::remove(), and rocksdb::TEST().
{
   return DB::Delete(options, key);
 }
Status rocksdb::DBImpl::DeleteFile (std::string name) virtual
Implements rocksdb::DB.
Definition at line 3355 of file db_impl.cc.
References rocksdb::FileMetaData::being_compacted, rocksdb::VersionEdit::DeleteFile(), rocksdb::Env::DeleteFile(), env_, FindObsoleteFiles(), rocksdb::Options::info_log, rocksdb::Status::InvalidArgument(), rocksdb::kArchivedLogFile, rocksdb::kLogFile, rocksdb::kTableFile, rocksdb::Log(), rocksdb::LogFlush(), mutex_, rocksdb::Status::NotSupported(), NumberLevels(), rocksdb::Status::OK(), rocksdb::Status::ok(), options_, rocksdb::ParseFileName(), PurgeObsoleteFiles(), versions_, and rocksdb::Options::wal_dir.
Referenced by PurgeObsoleteWALFiles(), and rocksdb::TEST().
{
   uint64_t number;
   FileType type;
   WalFileType log_type;
   if (!ParseFileName(name, &number, &type, &log_type) ||
       (type != kTableFile && type != kLogFile)) {
     Log(options_.info_log, "DeleteFile %s failed.\n", name.c_str());
     return Status::InvalidArgument("Invalid file name");
   }
   Status status;
   if (type == kLogFile) {
     // Only allow deleting archived log files
     if (log_type != kArchivedLogFile) {
       Log(options_.info_log, "DeleteFile %s failed.\n", name.c_str());
       return Status::NotSupported("Delete only supported for archived logs");
     }
     status = env_->DeleteFile(options_.wal_dir + "/" + name.c_str());
     if (!status.ok()) {
       Log(options_.info_log, "DeleteFile %s failed.\n", name.c_str());
     }
     return status;
   }
   int level;
   FileMetaData metadata;
   int maxlevel = NumberLevels();
   VersionEdit edit(maxlevel);
   DeletionState deletion_state;
   {
     MutexLock l(&mutex_);
     status = versions_->GetMetadataForFile(number, &level, &metadata);
     if (!status.ok()) {
       Log(options_.info_log, "DeleteFile %s failed. File not found\n",
                              name.c_str());
       return Status::InvalidArgument("File not found");
     }
     assert((level > 0) && (level < maxlevel));
     // If the file is being compacted no need to delete.
     if (metadata.being_compacted) {
       Log(options_.info_log,
           "DeleteFile %s Skipped. File about to be compacted\n", name.c_str());
       return Status::OK();
     }
     // Only the files in the last level can be deleted externally.
     // This is to make sure that any deletion tombstones are not
     // lost. Check that the level passed is the last level.
     for (int i = level + 1; i < maxlevel; i++) {
       if (versions_->NumLevelFiles(i) != 0) {
         Log(options_.info_log,
             "DeleteFile %s FAILED. File not in last level\n", name.c_str());
         return Status::InvalidArgument("File not in last level");
       }
     }
     edit.DeleteFile(level, number);
     status = versions_->LogAndApply(&edit, &mutex_);
     FindObsoleteFiles(deletion_state, false);
   } // lock released here
   LogFlush(options_.info_log);
   if (status.ok()) {
     // remove files outside the db-lock
     PurgeObsoleteFiles(deletion_state);
   }
   return status;
 }
void rocksdb::DBImpl::DeleteObsoleteFiles () private
Definition at line 635 of file db_impl.cc.
References rocksdb::port::Mutex::AssertHeld(), FindObsoleteFiles(), mutex_, and PurgeObsoleteFiles().
Referenced by rocksdb::DB::Open().
{
   mutex_.AssertHeld();
   DeletionState deletion_state;
   FindObsoleteFiles(deletion_state, true);
   PurgeObsoleteFiles(deletion_state);
 }
Status rocksdb::DBImpl::DisableFileDeletions () virtual
Implements rocksdb::DB.
Reimplemented in rocksdb::DBImplReadOnly.
Definition at line 23 of file db_filesnapshot.cc.
References disable_delete_obsolete_files_, rocksdb::Options::info_log, rocksdb::Log(), mutex_, rocksdb::Status::OK(), and options_.
{
   MutexLock l(&mutex_);
   disable_delete_obsolete_files_ = true;
   Log(options_.info_log, "File Deletions Disabled");
   return Status::OK();
 }
Status rocksdb::DBImpl::DoCompactionWork (CompactionState * compact, DeletionState & deletion_state) private
Definition at line 2074 of file db_impl.cc.
References rocksdb::port::AtomicPointer::Acquire_Load(), AllocateCompactionOutputFileNumbers(), bg_compaction_scheduled_, bg_cv_, rocksdb::Compaction::BottomMostLevel(), rocksdb::DBImpl::CompactionState::builder, rocksdb::DBImpl::CompactionStats::bytes_readn, rocksdb::DBImpl::CompactionStats::bytes_readnp1, rocksdb::DBImpl::CompactionStats::bytes_written, rocksdb::Slice::clear(), rocksdb::DBImpl::CompactionState::compaction, rocksdb::Options::compaction_filter, rocksdb::Options::compaction_filter_factory, rocksdb::COMPACTION_KEY_DROP_NEWER_ENTRY, rocksdb::COMPACTION_KEY_DROP_OBSOLETE, rocksdb::COMPACTION_KEY_DROP_USER, rocksdb::Options::compaction_style, rocksdb::COMPACTION_TIME, rocksdb::DBImpl::CompactionState::current_output(), rocksdb::Slice::data(), rocksdb::InternalKey::DecodeFrom(), ripple::Resource::drop, env_, rocksdb::DBImpl::CompactionState::existing_snapshots, rocksdb::FileMetaData::file_size, rocksdb::DBImpl::CompactionStats::files_in_leveln, rocksdb::DBImpl::CompactionStats::files_in_levelnp1, rocksdb::DBImpl::CompactionStats::files_out_levelnp1, findEarliestVisibleSnapshot(), FinishCompactionOutputFile(), FlushMemTableToOutputFile(), rocksdb::SnapshotList::getAll(), rocksdb::DBImpl::CompactionState::GetFilterContext(), rocksdb::GetInternalKeySeqno(), imm_, rocksdb::MemTableList::imm_flush_needed, rocksdb::Options::info_log, rocksdb::Compaction::input(), InstallCompactionResults(), rocksdb::Status::IOError(), rocksdb::Compaction::IsBaseLevelForKey(), rocksdb::MemTableList::IsFlushPending(), rocksdb::kCompactionStyleLevel, rocksdb::kMaxSequenceNumber, rocksdb::kTypeDeletion, rocksdb::kTypeMerge, rocksdb::kTypeValue, rocksdb::DBImpl::CompactionState::Output::largest, rocksdb::DBImpl::CompactionState::Output::largest_seqno, rocksdb::Compaction::level(), rocksdb::port::Mutex::Lock(), rocksdb::Log(), rocksdb::LogFlush(), ripple::max(), rocksdb::Options::max_background_compactions, rocksdb::Compaction::MaxOutputFileSize(), rocksdb::Options::merge_operator, rocksdb::DBImpl::CompactionStats::micros, ripple::min(), rocksdb::Options::min_write_buffer_number_to_merge, mutex_, rocksdb::port::AtomicPointer::NoBarrier_Load(), rocksdb::Env::NowMicros(), rocksdb::Compaction::num_input_files(), rocksdb::Status::ok(), OpenCompactionOutputFile(), options_, rocksdb::DBImpl::CompactionState::outfile, rocksdb::Compaction::output_level(), rocksdb::DBImpl::CompactionState::outputs, rocksdb::ParseInternalKey(), rocksdb::RecordTick(), ReleaseCompactionUnusedFileNumbers(), rocksdb::Compaction::score(), rocksdb::ParsedInternalKey::sequence, rocksdb::Compaction::ShouldStopBefore(), shutting_down_, rocksdb::port::CondVar::SignalAll(), rocksdb::Slice::size(), rocksdb::DBImpl::CompactionState::Output::smallest, rocksdb::DBImpl::CompactionState::Output::smallest_seqno, snapshots_, rocksdb::Options::statistics, stats, stats_, rocksdb::Compaction::Summary(), rocksdb::Slice::ToString(), rocksdb::Status::ToString(), rocksdb::ParsedInternalKey::type, rocksdb::port::Mutex::Unlock(), rocksdb::UpdateInternalKey(), user_comparator(), rocksdb::ParsedInternalKey::user_key, value, and versions_.
Referenced by BackgroundCompaction().
{
   assert(compact);
   int64_t imm_micros = 0;  // Micros spent doing imm_ compactions
   Log(options_.info_log,
       "Compacting %d@%d + %d@%d files, score %.2f slots available %d",
       compact->compaction->num_input_files(0),
       compact->compaction->level(),
       compact->compaction->num_input_files(1),
       compact->compaction->level() + 1,
       compact->compaction->score(),
       options_.max_background_compactions - bg_compaction_scheduled_);
   char scratch[256];
   compact->compaction->Summary(scratch, sizeof(scratch));
   Log(options_.info_log, "Compaction start summary: %s\n", scratch);
   assert(versions_->NumLevelFiles(compact->compaction->level()) > 0);
   assert(compact->builder == nullptr);
   assert(!compact->outfile);
   SequenceNumber visible_at_tip = 0;
   SequenceNumber earliest_snapshot;
   SequenceNumber latest_snapshot = 0;
   snapshots_.getAll(compact->existing_snapshots);
   if (compact->existing_snapshots.size() == 0) {
     // optimize for fast path if there are no snapshots
     visible_at_tip = versions_->LastSequence();
     earliest_snapshot = visible_at_tip;
   } else {
     latest_snapshot = compact->existing_snapshots.back();
     // Add the current seqno as the 'latest' virtual
     // snapshot to the end of this list.
     compact->existing_snapshots.push_back(versions_->LastSequence());
     earliest_snapshot = compact->existing_snapshots[0];
   }
   // Is this compaction producing files at the bottommost level?
   bool bottommost_level = compact->compaction->BottomMostLevel();
   // Allocate the output file numbers before we release the lock
   AllocateCompactionOutputFileNumbers(compact);
   // Release mutex while we're actually doing the compaction work
   mutex_.Unlock();
   const uint64_t start_micros = env_->NowMicros();
   unique_ptr<Iterator> input(versions_->MakeInputIterator(compact->compaction));
   input->SeekToFirst();
   Status status;
   ParsedInternalKey ikey;
   std::string current_user_key;
   bool has_current_user_key = false;
   SequenceNumber last_sequence_for_key __attribute__((unused)) =
     kMaxSequenceNumber;
   SequenceNumber visible_in_snapshot = kMaxSequenceNumber;
   std::string compaction_filter_value;
   std::vector<char> delete_key; // for compaction filter
   MergeHelper merge(user_comparator(), options_.merge_operator.get(),
                     options_.info_log.get(),
                     false /* internal key corruption is expected */);
   auto compaction_filter = options_.compaction_filter;
   std::unique_ptr<CompactionFilter> compaction_filter_from_factory = nullptr;
   if (!compaction_filter) {
     auto context = compact->GetFilterContext();
     compaction_filter_from_factory =
       options_.compaction_filter_factory->CreateCompactionFilter(context);
     compaction_filter = compaction_filter_from_factory.get();
   }
   for (; input->Valid() && !shutting_down_.Acquire_Load(); ) {
     // Prioritize immutable compaction work
     // TODO: remove memtable flush from normal compaction work
     if (imm_.imm_flush_needed.NoBarrier_Load() != nullptr) {
       const uint64_t imm_start = env_->NowMicros();
       LogFlush(options_.info_log);
       mutex_.Lock();
       if (imm_.IsFlushPending(options_.min_write_buffer_number_to_merge)) {
         FlushMemTableToOutputFile(nullptr, deletion_state);
         bg_cv_.SignalAll();  // Wakeup MakeRoomForWrite() if necessary
       }
       mutex_.Unlock();
       imm_micros += (env_->NowMicros() - imm_start);
     }
     Slice key = input->key();
     Slice value = input->value();
     if (compact->compaction->ShouldStopBefore(key) &&
         compact->builder != nullptr) {
       status = FinishCompactionOutputFile(compact, input.get());
       if (!status.ok()) {
         break;
       }
     }
     // Handle key/value, add to state, etc.
     bool drop = false;
     bool current_entry_is_merging = false;
     if (!ParseInternalKey(key, &ikey)) {
       // Do not hide error keys
       // TODO: error key stays in db forever? Figure out the intention/rationale
       // v10 error v8 : we cannot hide v8 even though it's pretty obvious.
       current_user_key.clear();
       has_current_user_key = false;
       last_sequence_for_key = kMaxSequenceNumber;
       visible_in_snapshot = kMaxSequenceNumber;
     } else {
       if (!has_current_user_key ||
           user_comparator()->Compare(ikey.user_key,
                                      Slice(current_user_key)) != 0) {
         // First occurrence of this user key
         current_user_key.assign(ikey.user_key.data(), ikey.user_key.size());
         has_current_user_key = true;
         last_sequence_for_key = kMaxSequenceNumber;
         visible_in_snapshot = kMaxSequenceNumber;
         // apply the compaction filter to the first occurrence of the user key
         if (compaction_filter &&
             ikey.type == kTypeValue &&
             (visible_at_tip || ikey.sequence > latest_snapshot)) {
           // If the user has specified a compaction filter and the sequence
           // number is greater than any external snapshot, then invoke the
           // filter.
           // If the return value of the compaction filter is true, replace
           // the entry with a delete marker.
           bool value_changed = false;
           compaction_filter_value.clear();
           bool to_delete =
             compaction_filter->Filter(compact->compaction->level(),
                                                ikey.user_key, value,
                                                &compaction_filter_value,
                                                &value_changed);
           if (to_delete) {
             // make a copy of the original key
             delete_key.assign(key.data(), key.data() + key.size());
             // convert it to a delete
             UpdateInternalKey(&delete_key[0], delete_key.size(),
                               ikey.sequence, kTypeDeletion);
             // anchor the key again
             key = Slice(&delete_key[0], delete_key.size());
             // needed because ikey is backed by key
             ParseInternalKey(key, &ikey);
             // no value associated with delete
             value.clear();
             RecordTick(options_.statistics, COMPACTION_KEY_DROP_USER);
           } else if (value_changed) {
             value = compaction_filter_value;
           }
         }
       }
       // If there are no snapshots, then this kv affect visibility at tip.
       // Otherwise, search though all existing snapshots to find
       // the earlist snapshot that is affected by this kv.
       SequenceNumber prev_snapshot = 0; // 0 means no previous snapshot
       SequenceNumber visible = visible_at_tip ?
         visible_at_tip :
         findEarliestVisibleSnapshot(ikey.sequence,
                                     compact->existing_snapshots,
                                     &prev_snapshot);
       if (visible_in_snapshot == visible) {
         // If the earliest snapshot is which this key is visible in
         // is the same as the visibily of a previous instance of the
         // same key, then this kv is not visible in any snapshot.
         // Hidden by an newer entry for same user key
         // TODO: why not > ?
         assert(last_sequence_for_key >= ikey.sequence);
         drop = true;    // (A)
         RecordTick(options_.statistics, COMPACTION_KEY_DROP_NEWER_ENTRY);
       } else if (ikey.type == kTypeDeletion &&
                  ikey.sequence <= earliest_snapshot &&
                  compact->compaction->IsBaseLevelForKey(ikey.user_key)) {
         // For this user key:
         // (1) there is no data in higher levels
         // (2) data in lower levels will have larger sequence numbers
         // (3) data in layers that are being compacted here and have
         //     smaller sequence numbers will be dropped in the next
         //     few iterations of this loop (by rule (A) above).
         // Therefore this deletion marker is obsolete and can be dropped.
         drop = true;
         RecordTick(options_.statistics, COMPACTION_KEY_DROP_OBSOLETE);
       } else if (ikey.type == kTypeMerge) {
         // We know the merge type entry is not hidden, otherwise we would
         // have hit (A)
         // We encapsulate the merge related state machine in a different
         // object to minimize change to the existing flow. Turn out this
         // logic could also be nicely re-used for memtable flush purge
         // optimization in BuildTable.
         merge.MergeUntil(input.get(), prev_snapshot, bottommost_level,
                          options_.statistics);
         current_entry_is_merging = true;
         if (merge.IsSuccess()) {
           // Successfully found Put/Delete/(end-of-key-range) while merging
           // Get the merge result
           key = merge.key();
           ParseInternalKey(key, &ikey);
           value = merge.value();
         } else {
           // Did not find a Put/Delete/(end-of-key-range) while merging
           // We now have some stack of merge operands to write out.
           // NOTE: key,value, and ikey are now referring to old entries.
           //       These will be correctly set below.
           assert(!merge.keys().empty());
           assert(merge.keys().size() == merge.values().size());
           // Hack to make sure last_sequence_for_key is correct
           ParseInternalKey(merge.keys().front(), &ikey);
         }
       }
       last_sequence_for_key = ikey.sequence;
       visible_in_snapshot = visible;
     }
 #if 0
     Log(options_.info_log,
         "  Compact: %s, seq %d, type: %d %d, drop: %d, is_base: %d, "
         "%d smallest_snapshot: %d level: %d bottommost %d",
         ikey.user_key.ToString().c_str(),
         (int)ikey.sequence, ikey.type, kTypeValue, drop,
         compact->compaction->IsBaseLevelForKey(ikey.user_key),
         (int)last_sequence_for_key, (int)earliest_snapshot,
         compact->compaction->level(), bottommost_level);
 #endif
     if (!drop) {
       // We may write a single key (e.g.: for Put/Delete or successful merge).
       // Or we may instead have to write a sequence/list of keys.
       // We have to write a sequence iff we have an unsuccessful merge
       bool has_merge_list = current_entry_is_merging && !merge.IsSuccess();
       const std::deque<std::string>* keys = nullptr;
       const std::deque<std::string>* values = nullptr;
       std::deque<std::string>::const_reverse_iterator key_iter;
       std::deque<std::string>::const_reverse_iterator value_iter;
       if (has_merge_list) {
         keys = &merge.keys();
         values = &merge.values();
         key_iter = keys->rbegin();    // The back (*rbegin()) is the first key
         value_iter = values->rbegin();
         key = Slice(*key_iter);
         value = Slice(*value_iter);
       }
       // If we have a list of keys to write, traverse the list.
       // If we have a single key to write, simply write that key.
       while (true) {
         // Invariant: key,value,ikey will always be the next entry to write
         char* kptr = (char*)key.data();
         std::string kstr;
         // Zeroing out the sequence number leads to better compression.
         // If this is the bottommost level (no files in lower levels)
         // and the earliest snapshot is larger than this seqno
         // then we can squash the seqno to zero.
         if (options_.compaction_style == kCompactionStyleLevel &&
             bottommost_level && ikey.sequence < earliest_snapshot &&
             ikey.type != kTypeMerge) {
           assert(ikey.type != kTypeDeletion);
           // make a copy because updating in place would cause problems
           // with the priority queue that is managing the input key iterator
           kstr.assign(key.data(), key.size());
           kptr = (char *)kstr.c_str();
           UpdateInternalKey(kptr, key.size(), (uint64_t)0, ikey.type);
         }
         Slice newkey(kptr, key.size());
         assert((key.clear(), 1)); // we do not need 'key' anymore
         // Open output file if necessary
         if (compact->builder == nullptr) {
           status = OpenCompactionOutputFile(compact);
           if (!status.ok()) {
             break;
           }
         }
         SequenceNumber seqno = GetInternalKeySeqno(newkey);
         if (compact->builder->NumEntries() == 0) {
           compact->current_output()->smallest.DecodeFrom(newkey);
           compact->current_output()->smallest_seqno = seqno;
         } else {
           compact->current_output()->smallest_seqno =
             std::min(compact->current_output()->smallest_seqno, seqno);
         }
         compact->current_output()->largest.DecodeFrom(newkey);
         compact->builder->Add(newkey, value);
         compact->current_output()->largest_seqno =
           std::max(compact->current_output()->largest_seqno, seqno);
         // Close output file if it is big enough
         if (compact->builder->FileSize() >=
             compact->compaction->MaxOutputFileSize()) {
           status = FinishCompactionOutputFile(compact, input.get());
           if (!status.ok()) {
             break;
           }
         }
         // If we have a list of entries, move to next element
         // If we only had one entry, then break the loop.
         if (has_merge_list) {
           ++key_iter;
           ++value_iter;
           // If at end of list
           if (key_iter == keys->rend() || value_iter == values->rend()) {
             // Sanity Check: if one ends, then both end
             assert(key_iter == keys->rend() && value_iter == values->rend());
             break;
           }
           // Otherwise not at end of list. Update key, value, and ikey.
           key = Slice(*key_iter);
           value = Slice(*value_iter);
           ParseInternalKey(key, &ikey);
         } else{
           // Only had one item to begin with (Put/Delete)
           break;
         }
       }
     }
     // MergeUntil has moved input to the next entry
     if (!current_entry_is_merging) {
       input->Next();
     }
   }
   if (status.ok() && shutting_down_.Acquire_Load()) {
     status = Status::IOError("Database shutdown started during compaction");
   }
   if (status.ok() && compact->builder != nullptr) {
     status = FinishCompactionOutputFile(compact, input.get());
   }
   if (status.ok()) {
     status = input->status();
   }
   input.reset();
   CompactionStats stats;
   stats.micros = env_->NowMicros() - start_micros - imm_micros;
   if (options_.statistics) {
     options_.statistics->measureTime(COMPACTION_TIME, stats.micros);
   }
   stats.files_in_leveln = compact->compaction->num_input_files(0);
   stats.files_in_levelnp1 = compact->compaction->num_input_files(1);
   int num_output_files = compact->outputs.size();
   if (compact->builder != nullptr) {
     // An error occurred so ignore the last output.
     assert(num_output_files > 0);
     --num_output_files;
   }
   stats.files_out_levelnp1 = num_output_files;
   for (int i = 0; i < compact->compaction->num_input_files(0); i++)
     stats.bytes_readn += compact->compaction->input(0, i)->file_size;
   for (int i = 0; i < compact->compaction->num_input_files(1); i++)
     stats.bytes_readnp1 += compact->compaction->input(1, i)->file_size;
   for (int i = 0; i < num_output_files; i++) {
     stats.bytes_written += compact->outputs[i].file_size;
   }
   LogFlush(options_.info_log);
   mutex_.Lock();
   stats_[compact->compaction->output_level()].Add(stats);
   // if there were any unused file number (mostly in case of
   // compaction error), free up the entry from pending_putputs
   ReleaseCompactionUnusedFileNumbers(compact);
   if (status.ok()) {
     status = InstallCompactionResults(compact);
   }
   VersionSet::LevelSummaryStorage tmp;
   Log(options_.info_log,
       "compacted to: %s, %.1f MB/sec, level %d, files in(%d, %d) out(%d) "
       "MB in(%.1f, %.1f) out(%.1f), read-write-amplify(%.1f) "
       "write-amplify(%.1f) %s\n",
       versions_->LevelSummary(&tmp),
       (stats.bytes_readn + stats.bytes_readnp1 + stats.bytes_written) /
           (double) stats.micros,
       compact->compaction->output_level(),
       stats.files_in_leveln, stats.files_in_levelnp1, stats.files_out_levelnp1,
       stats.bytes_readn / 1048576.0,
       stats.bytes_readnp1 / 1048576.0,
       stats.bytes_written / 1048576.0,
       (stats.bytes_written + stats.bytes_readnp1 + stats.bytes_readn) /
           (double) stats.bytes_readn,
       stats.bytes_written / (double) stats.bytes_readn,
       status.ToString().c_str());
   return status;
 }
Status rocksdb::DBImpl::EnableFileDeletions () virtual
Implements rocksdb::DB.
Reimplemented in rocksdb::DBImplReadOnly.
Definition at line 30 of file db_filesnapshot.cc.
References disable_delete_obsolete_files_, FindObsoleteFiles(), rocksdb::Options::info_log, rocksdb::Log(), rocksdb::LogFlush(), mutex_, rocksdb::Status::OK(), options_, and PurgeObsoleteFiles().
{
   DeletionState deletion_state;
   {
     MutexLock l(&mutex_);
     disable_delete_obsolete_files_ = false;
     Log(options_.info_log, "File Deletions Enabled");
     FindObsoleteFiles(deletion_state, true);
   }
   PurgeObsoleteFiles(deletion_state);
   LogFlush(options_.info_log);
   return Status::OK();
 }
SequenceNumber rocksdb::DBImpl::findEarliestVisibleSnapshot (SequenceNumber in, std::vector< SequenceNumber > & snapshots, SequenceNumber * prev_snapshot) inline private
Definition at line 2053 of file db_impl.cc.
References rocksdb::Options::info_log, rocksdb::Log(), options_, and prev.
Referenced by DoCompactionWork().
{
   SequenceNumber prev __attribute__((unused)) = 0;
   for (const auto cur : snapshots) {
     assert(prev <= cur);
     if (cur >= in) {
       *prev_snapshot = prev;
       return cur;
     }
     prev = cur; // assignment
     assert(prev);
   }
   Log(options_.info_log,
       "Looking for seqid %lu but maxseqid is %lu",
       (unsigned long)in,
       (unsigned long)snapshots[snapshots.size()-1]);
   assert(0);
   return 0;
 }
int rocksdb::DBImpl::FindMinimumEmptyLevelFitting (int level) private
Definition at line 1208 of file db_impl.cc.
References rocksdb::port::Mutex::AssertHeld(), mutex_, and versions_.
Referenced by ReFitLevel().
{
   mutex_.AssertHeld();
   int minimum_level = level;
   for (int i = level - 1; i > 0; --i) {
     // stop if level i is not empty
     if (versions_->NumLevelFiles(i) > 0) break;
     // stop if level i is too small (cannot fit the level files)
     if (versions_->MaxBytesForLevel(i) < versions_->NumLevelBytes(level)) break;
     minimum_level = i;
   }
   return minimum_level;
 }
void rocksdb::DBImpl::FindObsoleteFiles (DeletionState & deletion_state, bool force, bool no_full_scan = false)
Definition at line 444 of file db_impl.cc.
References rocksdb::DBImpl::DeletionState::all_files, rocksdb::port::Mutex::AssertHeld(), dbname_, delete_obsolete_files_last_run_, rocksdb::Options::delete_obsolete_files_period_micros, disable_delete_obsolete_files_, env_, rocksdb::Env::GetChildren(), rocksdb::DBImpl::DeletionState::HaveSomethingToDelete(), rocksdb::DBImpl::DeletionState::log_number, rocksdb::DBImpl::DeletionState::manifest_file_number, mutex_, rocksdb::Env::NowMicros(), options_, pending_outputs_, rocksdb::DBImpl::DeletionState::prev_log_number, rocksdb::DBImpl::DeletionState::sst_delete_files, rocksdb::DBImpl::DeletionState::sst_live, versions_, and rocksdb::Options::wal_dir.
Referenced by BackgroundCallCompaction(), BackgroundCallFlush(), DeleteFile(), DeleteObsoleteFiles(), and EnableFileDeletions().
{
   mutex_.AssertHeld();
   // if deletion is disabled, do nothing
   if (disable_delete_obsolete_files_) {
     return;
   }
   bool doing_the_full_scan = false;
   // logic for figurint out if we're doing the full scan
   if (no_full_scan) {
     doing_the_full_scan = false;
   } else if (force || options_.delete_obsolete_files_period_micros == 0) {
     doing_the_full_scan = true;
   } else {
     const uint64_t now_micros = env_->NowMicros();
     if (delete_obsolete_files_last_run_ +
         options_.delete_obsolete_files_period_micros < now_micros) {
       doing_the_full_scan = true;
       delete_obsolete_files_last_run_ = now_micros;
     }
   }
   // get obsolete files
   versions_->GetObsoleteFiles(&deletion_state.sst_delete_files);
   // store the current filenum, lognum, etc
   deletion_state.manifest_file_number = versions_->ManifestFileNumber();
   deletion_state.log_number = versions_->LogNumber();
   deletion_state.prev_log_number = versions_->PrevLogNumber();
   if (!doing_the_full_scan && !deletion_state.HaveSomethingToDelete()) {
     // avoid filling up sst_live if we're sure that we
     // are not going to do the full scan and that we don't have
     // anything to delete at the moment
     return;
   }
   // don't delete live files
   deletion_state.sst_live.assign(pending_outputs_.begin(),
                                  pending_outputs_.end());
   versions_->AddLiveFiles(&deletion_state.sst_live);
   if (doing_the_full_scan) {
     // set of all files in the directory
     env_->GetChildren(dbname_, &deletion_state.all_files); // Ignore errors
     //Add log files in wal_dir
     if (options_.wal_dir != dbname_) {
       std::vector<std::string> log_files;
       env_->GetChildren(options_.wal_dir, &log_files); // Ignore errors
       deletion_state.all_files.insert(
         deletion_state.all_files.end(),
         log_files.begin(),
         log_files.end()
       );
     }
   }
 }
Status rocksdb::DBImpl::FinishCompactionOutputFile (CompactionState * compact, Iterator * input) private
Definition at line 1952 of file db_impl.cc.
References rocksdb::DBImpl::CompactionState::builder, rocksdb::COMPACTION_OUTFILE_SYNC_MICROS, rocksdb::DBImpl::CompactionState::current_output(), rocksdb::Options::disableDataSync, env_, rocksdb::DBImpl::CompactionState::Output::file_size, rocksdb::Options::info_log, rocksdb::Log(), rocksdb::DBImpl::CompactionState::Output::number, rocksdb::Status::ok(), options_, rocksdb::DBImpl::CompactionState::outfile, rocksdb::Options::statistics, rocksdb::Iterator::status(), storage_options_, table_cache_, rocksdb::DBImpl::CompactionState::total_bytes, and rocksdb::Options::use_fsync.
Referenced by DoCompactionWork().
{
   assert(compact != nullptr);
   assert(compact->outfile);
   assert(compact->builder != nullptr);
   const uint64_t output_number = compact->current_output()->number;
   assert(output_number != 0);
   // Check for iterator errors
   Status s = input->status();
   const uint64_t current_entries = compact->builder->NumEntries();
   if (s.ok()) {
     s = compact->builder->Finish();
   } else {
     compact->builder->Abandon();
   }
   const uint64_t current_bytes = compact->builder->FileSize();
   compact->current_output()->file_size = current_bytes;
   compact->total_bytes += current_bytes;
   compact->builder.reset();
   // Finish and check for file errors
   if (s.ok() && !options_.disableDataSync) {
     if (options_.use_fsync) {
       StopWatch sw(env_, options_.statistics, COMPACTION_OUTFILE_SYNC_MICROS);
       s = compact->outfile->Fsync();
     } else {
       StopWatch sw(env_, options_.statistics, COMPACTION_OUTFILE_SYNC_MICROS);
       s = compact->outfile->Sync();
     }
   }
   if (s.ok()) {
     s = compact->outfile->Close();
   }
   compact->outfile.reset();
   if (s.ok() && current_entries > 0) {
     // Verify that the table is usable
     Iterator* iter = table_cache_->NewIterator(ReadOptions(),
                                                storage_options_,
                                                output_number,
                                                current_bytes);
     s = iter->status();
     delete iter;
     if (s.ok()) {
       Log(options_.info_log,
           "Generated table #%lu: %lu keys, %lu bytes",
           (unsigned long) output_number,
           (unsigned long) current_entries,
           (unsigned long) current_bytes);
     }
   }
   return s;
 }
Status rocksdb::DBImpl::Flush (const FlushOptions & options) virtual
Implements rocksdb::DB.
Reimplemented in rocksdb::DBImplReadOnly.
Definition at line 1291 of file db_impl.cc.
References FlushMemTable().
Referenced by GetLiveFiles(), and rocksdb::TEST().
{
   Status status = FlushMemTable(options);
   return status;
 }
Status rocksdb::DBImpl::FlushMemTable (const FlushOptions & options) private
Definition at line 1554 of file db_impl.cc.
References rocksdb::Status::ok(), rocksdb::FlushOptions::wait, WaitForFlushMemTable(), and Write().
Referenced by Flush(), TEST_FlushMemTable(), and ~DBImpl().
{
   // nullptr batch means just wait for earlier writes to be done
   Status s = Write(WriteOptions(), nullptr);
   if (s.ok() && options.wait) {
     // Wait until the compaction completes
     s = WaitForFlushMemTable();
   }
   return s;
 }
Status rocksdb::DBImpl::FlushMemTableToOutputFile (bool * madeProgress, DeletionState & deletion_state) private
Definition at line 1113 of file db_impl.cc.
References rocksdb::port::AtomicPointer::Acquire_Load(), rocksdb::port::Mutex::AssertHeld(), disable_delete_obsolete_files_, rocksdb::MemTable::GetEdits(), imm_, rocksdb::Options::info_log, rocksdb::MemTableList::InstallMemtableFlushResults(), rocksdb::Status::IOError(), rocksdb::MemTableList::IsFlushPending(), rocksdb::Log(), rocksdb::DBImpl::DeletionState::log_delete_files, MaybeScheduleLogDBDeployStats(), mem, rocksdb::Options::min_write_buffer_number_to_merge, mutex_, rocksdb::Status::ok(), options_, pending_outputs_, rocksdb::MemTableList::PickMemtablesToFlush(), rocksdb::VersionEdit::SetLogNumber(), rocksdb::VersionEdit::SetPrevLogNumber(), shutting_down_, rocksdb::MemTableList::size(), versions_, and WriteLevel0Table().
Referenced by BackgroundCompaction(), BackgroundFlush(), and DoCompactionWork().
{
   mutex_.AssertHeld();
   assert(imm_.size() != 0);
   if (!imm_.IsFlushPending(options_.min_write_buffer_number_to_merge)) {
     Log(options_.info_log, "FlushMemTableToOutputFile already in progress");
     Status s = Status::IOError("FlushMemTableToOutputFile already in progress");
     return s;
   }
   // Save the contents of the earliest memtable as a new Table
   uint64_t file_number;
   std::vector<MemTable*> mems;
   imm_.PickMemtablesToFlush(&mems);
   if (mems.empty()) {
     Log(options_.info_log, "Nothing in memstore to flush");
     Status s = Status::IOError("Nothing in memstore to flush");
     return s;
   }
   // record the logfile_number_ before we release the mutex
   // entries mems are (implicitly) sorted in ascending order by their created
   // time. We will use the first memtable's `edit` to keep the meta info for
   // this flush.
   MemTable* m = mems[0];
   VersionEdit* edit = m->GetEdits();
   edit->SetPrevLogNumber(0);
   // SetLogNumber(log_num) indicates logs with number smaller than log_num
   // will no longer be picked up for recovery.
   edit->SetLogNumber(
       mems.back()->GetNextLogNumber()
   );
   std::vector<uint64_t> logs_to_delete;
   for (auto mem : mems) {
     logs_to_delete.push_back(mem->GetLogNumber());
   }
   // This will release and re-acquire the mutex.
   Status s = WriteLevel0Table(mems, edit, &file_number);
   if (s.ok() && shutting_down_.Acquire_Load()) {
     s = Status::IOError(
       "Database shutdown started during memtable compaction"
     );
   }
   // Replace immutable memtable with the generated Table
   s = imm_.InstallMemtableFlushResults(
     mems, versions_.get(), s, &mutex_, options_.info_log.get(),
     file_number, pending_outputs_);
   if (s.ok()) {
     if (madeProgress) {
       *madeProgress = 1;
     }
     MaybeScheduleLogDBDeployStats();
     if (!disable_delete_obsolete_files_) {
       // add to deletion state
       deletion_state.log_delete_files.insert(
           deletion_state.log_delete_files.end(),
           logs_to_delete.begin(),
           logs_to_delete.end());
     }
   }
   return s;
 }
Status rocksdb::DBImpl::Get (const ReadOptions & options, const Slice & key, std::string * value) virtual
Implements rocksdb::DB.
Reimplemented in rocksdb::DBImplReadOnly.
Definition at line 2548 of file db_impl.cc.
References GetImpl().
Referenced by rocksdb::StringLists::Get(), Counters::get(), rocksdb::ProfileKeyComparison(), and rocksdb::TEST().
{
   return GetImpl(options, key, value);
 }
void rocksdb::DBImpl::GetApproximateSizes (const Range * range, int n, uint64_t * sizes) virtual
Implements rocksdb::DB.
Definition at line 3322 of file db_impl.cc.
References rocksdb::kMaxSequenceNumber, rocksdb::kValueTypeForSeek, mutex_, rocksdb::Version::Unref(), and versions_.
                      {
   // TODO(opt): better implementation
   Version* v;
   {
     MutexLock l(&mutex_);
     versions_->current()->Ref();
     v = versions_->current();
   }
   for (int i = 0; i < n; i++) {
     // Convert user_key into a corresponding internal key.
     InternalKey k1(range[i].start, kMaxSequenceNumber, kValueTypeForSeek);
     InternalKey k2(range[i].limit, kMaxSequenceNumber, kValueTypeForSeek);
     uint64_t start = versions_->ApproximateOffsetOf(v, k1);
     uint64_t limit = versions_->ApproximateOffsetOf(v, k2);
     sizes[i] = (limit >= start ? limit - start : 0);
   }
   {
     MutexLock l(&mutex_);
     v->Unref();
   }
 }
Status rocksdb::DBImpl::GetImpl (const ReadOptions & options, const Slice & key, std::string * value, bool * value_found = nullptr) private
Definition at line 2554 of file db_impl.cc.
References rocksdb::BYTES_READ, rocksdb::DB_GET, rocksdb::Options::disable_seek_compaction, env_, rocksdb::MemTableList::Get(), rocksdb::Version::Get(), rocksdb::MemTable::Get(), imm_, rocksdb::Options::info_log, rocksdb::port::Mutex::Lock(), rocksdb::LogFlush(), MaybeScheduleFlushOrCompaction(), mem, mem_, merge_operands, mutex_, rocksdb::NUMBER_KEYS_READ, options_, rocksdb::RecordTick(), rocksdb::MemTable::Ref(), rocksdb::Version::Ref(), rocksdb::MemTableList::RefAll(), rocksdb::ReadOptions::snapshot, rocksdb::Options::statistics, stats, rocksdb::port::Mutex::Unlock(), rocksdb::MemTable::Unref(), rocksdb::Version::Unref(), rocksdb::MemTableList::UnrefAll(), rocksdb::Version::UpdateStats(), and versions_.
Referenced by Get(), and KeyMayExist().
{
   Status s;
   StopWatch sw(env_, options_.statistics, DB_GET);
   SequenceNumber snapshot;
   mutex_.Lock();
   if (options.snapshot != nullptr) {
     snapshot = reinterpret_cast<const SnapshotImpl*>(options.snapshot)->number_;
   } else {
     snapshot = versions_->LastSequence();
   }
   MemTable* mem = mem_;
   MemTableList imm = imm_;
   Version* current = versions_->current();
   mem->Ref();
   imm.RefAll();
   current->Ref();
   // Unlock while reading from files and memtables
   mutex_.Unlock();
   bool have_stat_update = false;
   Version::GetStats stats;
   // Prepare to store a list of merge operations if merge occurs.
   std::deque<std::string> merge_operands;
   // First look in the memtable, then in the immutable memtable (if any).
   // s is both in/out. When in, s could either be OK or MergeInProgress.
   // merge_operands will contain the sequence of merges in the latter case.
   LookupKey lkey(key, snapshot);
   if (mem->Get(lkey, value, &s, &merge_operands, options_)) {
     // Done
   } else if (imm.Get(lkey, value, &s, &merge_operands, options_)) {
     // Done
   } else {
     current->Get(options, lkey, value, &s, &merge_operands, &stats,
                  options_, value_found);
     have_stat_update = true;
   }
   mutex_.Lock();
   if (!options_.disable_seek_compaction &&
       have_stat_update && current->UpdateStats(stats)) {
     MaybeScheduleFlushOrCompaction();
   }
   mem->Unref();
   imm.UnrefAll();
   current->Unref();
   mutex_.Unlock();
   LogFlush(options_.info_log);
   // Note, tickers are atomic now - no lock protection needed any more.
   RecordTick(options_.statistics, NUMBER_KEYS_READ);
   RecordTick(options_.statistics, BYTES_READ, value->size());
   return s;
 }
SequenceNumber rocksdb::DBImpl::GetLatestSequenceNumber () const virtual
Implements rocksdb::DB.
Definition at line 1296 of file db_impl.cc.
References versions_.
Referenced by rocksdb::TransactionLogIteratorImpl::IsBatchExpected(), rocksdb::TransactionLogIteratorImpl::NextImpl(), and rocksdb::TransactionLogIteratorImpl::RestrictedRead().
{
   return versions_->LastSequence();
 }
Status rocksdb::DBImpl::GetLiveFiles (std::vector< std::string > & ret, uint64_t * manifest_file_size, bool flush_memtable = true) virtual
Implements rocksdb::DB.
Reimplemented in rocksdb::DBImplReadOnly.
Definition at line 43 of file db_filesnapshot.cc.
References rocksdb::CurrentFileName(), rocksdb::DescriptorFileName(), Flush(), rocksdb::Options::info_log, rocksdb::Log(), mutex_, rocksdb::Status::OK(), rocksdb::Status::ok(), options_, rocksdb::TableFileName(), rocksdb::Status::ToString(), and versions_.
{
   *manifest_file_size = 0;
   if (flush_memtable) {
     // flush all dirty data to disk.
     Status status =  Flush(FlushOptions());
     if (!status.ok()) {
       Log(options_.info_log, "Cannot Flush data %s\n",
           status.ToString().c_str());
       return status;
     }
   }
   MutexLock l(&mutex_);
   // Make a set of all of the live *.sst files
   std::set<uint64_t> live;
   versions_->AddLiveFilesCurrentVersion(&live);
   ret.clear();
   ret.reserve(live.size() + 2); //*.sst + CURRENT + MANIFEST
   // create names of the live files. The names are not absolute
   // paths, instead they are relative to dbname_;
   for (auto live_file : live) {
     ret.push_back(TableFileName("", live_file));
   }
   ret.push_back(CurrentFileName(""));
   ret.push_back(DescriptorFileName("", versions_->ManifestFileNumber()));
   // find length of manifest file while holding the mutex lock
   *manifest_file_size = versions_->ManifestFileSize();
   return Status::OK();
 }
void rocksdb::DBImpl::GetLiveFilesMetaData (std::vector< LiveFileMetaData > * metadata) virtual
Reimplemented from rocksdb::DB.
Definition at line 3424 of file db_impl.cc.
References mutex_, and versions_.
Referenced by rocksdb::TEST().
{
   MutexLock l(&mutex_);
   return versions_->GetLiveFilesMetaData(metadata);
 }
MemTable* rocksdb::DBImpl::GetMemTable () inline protected
Definition at line 185 of file db_impl.h.
References mem_.
Referenced by rocksdb::DBImplReadOnly::Get(), and rocksdb::DB::OpenForReadOnly().
{
     return mem_;
   }
bool rocksdb::DBImpl::GetProperty (const Slice & property, std::string * value) virtual
Implements rocksdb::DB.
Definition at line 3116 of file db_impl.cc.
References rocksdb::DBImpl::StatsSnapshot::bytes_new_, rocksdb::DBImpl::StatsSnapshot::bytes_read_, rocksdb::DBImpl::StatsSnapshot::bytes_written_, rocksdb::ConsumeDecimalNumber(), rocksdb::Slice::empty(), env_, imm_, Json::in(), last_stats_, mutex_, rocksdb::Env::NowMicros(), NumberLevels(), ripple::Resource::ok, std::chrono::prefix, rocksdb::Slice::remove_prefix(), rocksdb::DBImpl::StatsSnapshot::seconds_up_, rocksdb::Slice::size(), rocksdb::MemTableList::size(), stall_level0_num_files_, stall_level0_num_files_count_, stall_level0_slowdown_, stall_level0_slowdown_count_, stall_leveln_slowdown_, stall_leveln_slowdown_count_, stall_memtable_compaction_, stall_memtable_compaction_count_, started_at_, rocksdb::Slice::starts_with(), stats_, beast::IP::to_string(), and versions_.
Referenced by MaybeDumpStats().
{
   value->clear();
   MutexLock l(&mutex_);
   Slice in = property;
   Slice prefix("rocksdb.");
   if (!in.starts_with(prefix)) return false;
   in.remove_prefix(prefix.size());
   if (in.starts_with("num-files-at-level")) {
     in.remove_prefix(strlen("num-files-at-level"));
     uint64_t level;
     bool ok = ConsumeDecimalNumber(&in, &level) && in.empty();
     if (!ok || (int)level >= NumberLevels()) {
       return false;
     } else {
       char buf[100];
       snprintf(buf, sizeof(buf), "%d",
                versions_->NumLevelFiles(static_cast<int>(level)));
       *value = buf;
       return true;
     }
   } else if (in == "levelstats") {
     char buf[1000];
     snprintf(buf, sizeof(buf),
              "Level Files Size(MB)\n"
              "--------------------\n");
     value->append(buf);
     for (int level = 0; level < NumberLevels(); level++) {
       snprintf(buf, sizeof(buf),
                "%3d %8d %8.0f\n",
                level,
                versions_->NumLevelFiles(level),
                versions_->NumLevelBytes(level) / 1048576.0);
       value->append(buf);
     }
     return true;
   } else if (in == "stats") {
     char buf[1000];
     uint64_t total_bytes_written = 0;
     uint64_t total_bytes_read = 0;
     uint64_t micros_up = env_->NowMicros() - started_at_;
     // Add "+1" to make sure seconds_up is > 0 and avoid NaN later
     double seconds_up = (micros_up + 1) / 1000000.0;
     uint64_t total_slowdown = 0;
     uint64_t total_slowdown_count = 0;
     uint64_t interval_bytes_written = 0;
     uint64_t interval_bytes_read = 0;
     uint64_t interval_bytes_new = 0;
     double   interval_seconds_up = 0;
     // Pardon the long line but I think it is easier to read this way.
     snprintf(buf, sizeof(buf),
              "                               Compactions\n"
              "Level  Files Size(MB) Score Time(sec)  Read(MB) Write(MB)    Rn(MB)  Rnp1(MB)  Wnew(MB) RW-Amplify Read(MB/s) Write(MB/s)      Rn     Rnp1     Wnp1     NewW    Count  Ln-stall Stall-cnt\n"
              "--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n"
              );
     value->append(buf);
     for (int level = 0; level < NumberLevels(); level++) {
       int files = versions_->NumLevelFiles(level);
       if (stats_[level].micros > 0 || files > 0) {
         int64_t bytes_read = stats_[level].bytes_readn +
                              stats_[level].bytes_readnp1;
         int64_t bytes_new = stats_[level].bytes_written -
                             stats_[level].bytes_readnp1;
         double amplify = (stats_[level].bytes_readn == 0)
             ? 0.0
             : (stats_[level].bytes_written +
                stats_[level].bytes_readnp1 +
                stats_[level].bytes_readn) /
                 (double) stats_[level].bytes_readn;
         total_bytes_read += bytes_read;
         total_bytes_written += stats_[level].bytes_written;
         snprintf(
             buf, sizeof(buf),
             "%3d %8d %8.0f %5.1f %9.0f %9.0f %9.0f %9.0f %9.0f %9.0f %10.1f %9.1f %11.1f %8d %8d %8d %8d %8d %9.1f %9lu\n",
             level,
             files,
             versions_->NumLevelBytes(level) / 1048576.0,
             versions_->NumLevelBytes(level) /
                 versions_->MaxBytesForLevel(level),
             stats_[level].micros / 1e6,
             bytes_read / 1048576.0,
             stats_[level].bytes_written / 1048576.0,
             stats_[level].bytes_readn / 1048576.0,
             stats_[level].bytes_readnp1 / 1048576.0,
             bytes_new / 1048576.0,
             amplify,
             // +1 to avoid division by 0
             (bytes_read / 1048576.0) / ((stats_[level].micros+1) / 1000000.0),
             (stats_[level].bytes_written / 1048576.0) /
                 ((stats_[level].micros+1) / 1000000.0),
             stats_[level].files_in_leveln,
             stats_[level].files_in_levelnp1,
             stats_[level].files_out_levelnp1,
             stats_[level].files_out_levelnp1 - stats_[level].files_in_levelnp1,
             stats_[level].count,
             stall_leveln_slowdown_[level] / 1000000.0,
             (unsigned long) stall_leveln_slowdown_count_[level]);
         total_slowdown += stall_leveln_slowdown_[level];
         total_slowdown_count += stall_leveln_slowdown_count_[level];
         value->append(buf);
       }
     }
     interval_bytes_new = stats_[0].bytes_written - last_stats_.bytes_new_;
     interval_bytes_read = total_bytes_read - last_stats_.bytes_read_;
     interval_bytes_written = total_bytes_written - last_stats_.bytes_written_;
     interval_seconds_up = seconds_up - last_stats_.seconds_up_;
     snprintf(buf, sizeof(buf), "Uptime(secs): %.1f total, %.1f interval\n",
              seconds_up, interval_seconds_up);
     value->append(buf);
     snprintf(buf, sizeof(buf),
              "Compaction IO cumulative (GB): "
              "%.2f new, %.2f read, %.2f write, %.2f read+write\n",
              stats_[0].bytes_written / (1048576.0 * 1024),
              total_bytes_read / (1048576.0 * 1024),
              total_bytes_written / (1048576.0 * 1024),
              (total_bytes_read + total_bytes_written) / (1048576.0 * 1024));
     value->append(buf);
     snprintf(buf, sizeof(buf),
              "Compaction IO cumulative (MB/sec): "
              "%.1f new, %.1f read, %.1f write, %.1f read+write\n",
              stats_[0].bytes_written / 1048576.0 / seconds_up,
              total_bytes_read / 1048576.0 / seconds_up,
              total_bytes_written / 1048576.0 / seconds_up,
              (total_bytes_read + total_bytes_written) / 1048576.0 / seconds_up);
     value->append(buf);
     // +1 to avoid divide by 0 and NaN
     snprintf(buf, sizeof(buf),
              "Amplification cumulative: %.1f write, %.1f compaction\n",
              (double) total_bytes_written / (stats_[0].bytes_written+1),
              (double) (total_bytes_written + total_bytes_read)
                   / (stats_[0].bytes_written+1));
     value->append(buf);
     snprintf(buf, sizeof(buf),
              "Compaction IO interval (MB): "
              "%.2f new, %.2f read, %.2f write, %.2f read+write\n",
              interval_bytes_new / 1048576.0,
              interval_bytes_read/ 1048576.0,
              interval_bytes_written / 1048576.0,
              (interval_bytes_read + interval_bytes_written) / 1048576.0);
     value->append(buf);
     snprintf(buf, sizeof(buf),
              "Compaction IO interval (MB/sec): "
              "%.1f new, %.1f read, %.1f write, %.1f read+write\n",
              interval_bytes_new / 1048576.0 / interval_seconds_up,
              interval_bytes_read / 1048576.0 / interval_seconds_up,
              interval_bytes_written / 1048576.0 / interval_seconds_up,
              (interval_bytes_read + interval_bytes_written)
                  / 1048576.0 / interval_seconds_up);
     value->append(buf);
     // +1 to avoid divide by 0 and NaN
     snprintf(buf, sizeof(buf),
              "Amplification interval: %.1f write, %.1f compaction\n",
              (double) interval_bytes_written / (interval_bytes_new+1),
              (double) (interval_bytes_written + interval_bytes_read) /
                   (interval_bytes_new+1));
     value->append(buf);
     snprintf(buf, sizeof(buf),
             "Stalls(secs): %.3f level0_slowdown, %.3f level0_numfiles, "
             "%.3f memtable_compaction, %.3f leveln_slowdown\n",
             stall_level0_slowdown_ / 1000000.0,
             stall_level0_num_files_ / 1000000.0,
             stall_memtable_compaction_ / 1000000.0,
             total_slowdown / 1000000.0);
     value->append(buf);
     snprintf(buf, sizeof(buf),
             "Stalls(count): %lu level0_slowdown, %lu level0_numfiles, "
             "%lu memtable_compaction, %lu leveln_slowdown\n",
             (unsigned long) stall_level0_slowdown_count_,
             (unsigned long) stall_level0_num_files_count_,
             (unsigned long) stall_memtable_compaction_count_,
             (unsigned long) total_slowdown_count);
     value->append(buf);
     last_stats_.bytes_read_ = total_bytes_read;
     last_stats_.bytes_written_ = total_bytes_written;
     last_stats_.bytes_new_ = stats_[0].bytes_written;
     last_stats_.seconds_up_ = seconds_up;
     return true;
   } else if (in == "sstables") {
     *value = versions_->current()->DebugString();
     return true;
   } else if (in == "num-immutable-mem-table") {
     *value = std::to_string(imm_.size());
     return true;
   }
   return false;
 }
const Snapshot * rocksdb::DBImpl::GetSnapshot () virtual
Implements rocksdb::DB.
Definition at line 2731 of file db_impl.cc.
References mutex_, rocksdb::SnapshotList::New(), snapshots_, and versions_.
Referenced by rocksdb::TEST().
{
   MutexLock l(&mutex_);
   return snapshots_.New(versions_->LastSequence());
 }
Status rocksdb::DBImpl::GetSortedWalFiles (VectorLogPtr & files) virtual
Implements rocksdb::DB.
Definition at line 83 of file db_filesnapshot.cc.
References AppendSortedWalsOfType(), rocksdb::ArchivalDirectory(), env_, rocksdb::Env::FileExists(), rocksdb::kAliveLogFile, rocksdb::kArchivedLogFile, rocksdb::Status::ok(), options_, and rocksdb::Options::wal_dir.
Referenced by GetUpdatesSince(), and rocksdb::TEST().
{
   // First get sorted files in archive dir, then append sorted files from main
   // dir to maintain sorted order
   // list wal files in archive dir.
   Status s;
   std::string archivedir = ArchivalDirectory(options_.wal_dir);
   if (env_->FileExists(archivedir)) {
     s = AppendSortedWalsOfType(archivedir, files, kArchivedLogFile);
     if (!s.ok()) {
       return s;
     }
   }
   // list wal files in main db dir.
   return AppendSortedWalsOfType(options_.wal_dir, files, kAliveLogFile);
 }
Status rocksdb::DBImpl::GetUpdatesSince (SequenceNumber seq_number, unique_ptr< TransactionLogIterator > * iter) virtual
Implements rocksdb::DB.
Definition at line 1300 of file db_impl.cc.
References rocksdb::GET_UPDATES_SINCE_CALLS, GetSortedWalFiles(), rocksdb::Status::IOError(), rocksdb::Status::ok(), options_, rocksdb::RecordTick(), RetainProbableWalFiles(), rocksdb::Options::statistics, storage_options_, versions_, and rocksdb::Options::wal_dir.
Referenced by rocksdb::DBTest::OpenTransactionLogIter().
{
   RecordTick(options_.statistics, GET_UPDATES_SINCE_CALLS);
   if (seq > versions_->LastSequence()) {
     return Status::IOError("Requested sequence not yet written in the db");
   }
   //  Get all sorted Wal Files.
   //  Do binary search and open files and find the seq number.
   std::unique_ptr<VectorLogPtr> wal_files(new VectorLogPtr);
   Status s = GetSortedWalFiles(*wal_files);
   if (!s.ok()) {
     return s;
   }
   s = RetainProbableWalFiles(*wal_files, seq);
   if (!s.ok()) {
     return s;
   }
   iter->reset(
     new TransactionLogIteratorImpl(options_.wal_dir,
                                    &options_,
                                    storage_options_,
                                    seq,
                                    std::move(wal_files),
                                    this));
   return (*iter)->status();
 }
Status rocksdb::DBImpl::InstallCompactionResults (CompactionState * compact) private
Definition at line 2009 of file db_impl.cc.
References rocksdb::VersionEdit::AddFile(), rocksdb::Compaction::AddInputDeletions(), rocksdb::port::Mutex::AssertHeld(), rocksdb::DBImpl::CompactionState::compaction, rocksdb::Options::compaction_style, rocksdb::Compaction::edit(), rocksdb::DBImpl::CompactionState::Output::file_size, rocksdb::Options::info_log, rocksdb::Status::IOError(), rocksdb::kCompactionStyleUniversal, rocksdb::DBImpl::CompactionState::Output::largest, rocksdb::DBImpl::CompactionState::Output::largest_seqno, rocksdb::Compaction::level(), rocksdb::Log(), mutex_, rocksdb::Compaction::num_input_files(), rocksdb::DBImpl::CompactionState::Output::number, options_, rocksdb::DBImpl::CompactionState::outputs, rocksdb::DBImpl::CompactionState::Output::smallest, rocksdb::DBImpl::CompactionState::Output::smallest_seqno, rocksdb::DBImpl::CompactionState::total_bytes, and versions_.
Referenced by DoCompactionWork().
{
   mutex_.AssertHeld();
   // paranoia: verify that the files that we started with
   // still exist in the current version and in the same original level.
   // This ensures that a concurrent compaction did not erroneously
   // pick the same files to compact.
   if (!versions_->VerifyCompactionFileConsistency(compact->compaction)) {
     Log(options_.info_log,  "Compaction %d@%d + %d@%d files aborted",
       compact->compaction->num_input_files(0),
       compact->compaction->level(),
       compact->compaction->num_input_files(1),
       compact->compaction->level() + 1);
     return Status::IOError("Compaction input files inconsistent");
   }
   Log(options_.info_log,  "Compacted %d@%d + %d@%d files => %lld bytes",
       compact->compaction->num_input_files(0),
       compact->compaction->level(),
       compact->compaction->num_input_files(1),
       compact->compaction->level() + 1,
       static_cast<long long>(compact->total_bytes));
   // Add compaction outputs
   compact->compaction->AddInputDeletions(compact->compaction->edit());
   const int level = compact->compaction->level();
   for (size_t i = 0; i < compact->outputs.size(); i++) {
     const CompactionState::Output& out = compact->outputs[i];
     compact->compaction->edit()->AddFile(
         (options_.compaction_style == kCompactionStyleUniversal) ?
           level : level + 1,
         out.number, out.file_size, out.smallest, out.largest,
         out.smallest_seqno, out.largest_seqno);
   }
   return versions_->LogAndApply(compact->compaction->edit(), &mutex_);
 }
bool rocksdb::DBImpl::KeyMayExist (const ReadOptions & options, const Slice & key, std::string * value, bool * value_found = nullptr) virtual
Reimplemented from rocksdb::DB.
Definition at line 2696 of file db_impl.cc.
References GetImpl(), rocksdb::kBlockCacheTier, and rocksdb::ReadOptions::read_tier.
Referenced by rocksdb::TEST().
{
   if (value_found != nullptr) {
     // falsify later if key-may-exist but can't fetch value
     *value_found = true;
   }
   ReadOptions roptions = options;
   roptions.read_tier = kBlockCacheTier; // read from block cache only
   auto s = GetImpl(roptions, key, value, value_found);
   // If options.block_cache != nullptr and the index block of the table didn't
   // not present in block_cache, the return value will be Status::Incomplete.
   // In this case, key may still exist in the table.
   return s.ok() || s.IsIncomplete();
 }
int rocksdb::DBImpl::Level0StopWriteTrigger () virtual
Implements rocksdb::DB.
Definition at line 1287 of file db_impl.cc.
References rocksdb::Options::level0_stop_writes_trigger, and options_.
{
   return options_.level0_stop_writes_trigger;
 }
void rocksdb::DBImpl::LogDBDeployStats () private
Definition at line 52 of file db_stats_logger.cc.
References rocksdb::port::AtomicPointer::Acquire_Load(), bg_cv_, bg_logstats_scheduled_, db_absolute_path_, env_, rocksdb::Env::GetCurrentTime(), host_name_, rocksdb::kMajorVersion, rocksdb::kMinorVersion, rocksdb::port::Mutex::Lock(), logger_, mutex_, shutting_down_, rocksdb::port::CondVar::SignalAll(), rocksdb::port::Mutex::Unlock(), and versions_.
Referenced by BGLogDBDeployStats().
{
   mutex_.Lock();
   if (shutting_down_.Acquire_Load()) {
     bg_logstats_scheduled_ = false;
     bg_cv_.SignalAll();
     mutex_.Unlock();
     return;
   }
   char tmp_ver[100];
   sprintf(tmp_ver, "%d.%d", kMajorVersion, kMinorVersion);
   std::string version_info(tmp_ver);
   uint64_t file_total_size = 0;
   uint32_t file_total_num = 0;
   for (int i = 0; i < versions_->NumberLevels(); i++) {
     file_total_num += versions_->NumLevelFiles(i);
     file_total_size += versions_->NumLevelBytes(i);
   }
   VersionSet::LevelSummaryStorage scratch;
   const char* file_num_summary = versions_->LevelSummary(&scratch);
   std::string file_num_per_level(file_num_summary);
   std::string data_size_per_level(file_num_summary);
   mutex_.Unlock();
   int64_t unix_ts;
   env_->GetCurrentTime(&unix_ts);
   logger_->Log_Deploy_Stats(version_info, host_name_,
       db_absolute_path_, file_total_size, file_total_num, file_num_per_level,
       data_size_per_level, unix_ts);
   mutex_.Lock();
   bg_logstats_scheduled_ = false;
   bg_cv_.SignalAll();
   mutex_.Unlock();
 }
Status rocksdb::DBImpl::MakeRoomForWrite (bool force) private
Definition at line 2953 of file db_impl.cc.
References rocksdb::MemTableList::Add(), rocksdb::MemTable::ApproximateMemoryUsage(), rocksdb::port::Mutex::AssertHeld(), bg_cv_, bg_error_, delayed_writes_, DelayLoggingAndReset(), rocksdb::StopWatch::ElapsedMicros(), env_, rocksdb::MemTableList::FlushRequested(), rocksdb::Options::hard_rate_limit, rocksdb::HARD_RATE_LIMIT_DELAY_COUNT, imm_, rocksdb::Options::info_log, internal_comparator_, rocksdb::Options::level0_slowdown_writes_trigger, rocksdb::Options::level0_stop_writes_trigger, rocksdb::port::Mutex::Lock(), rocksdb::Log(), log_, logfile_number_, rocksdb::LogFileName(), ripple::max(), rocksdb::Options::max_write_buffer_number, MaybeScheduleFlushOrCompaction(), mem_, mem_rep_factory_, mutex_, rocksdb::Env::NewWritableFile(), NumberLevels(), rocksdb::Status::ok(), options_, rocksdb::Options::rate_limit_delay_max_milliseconds, rocksdb::RATE_LIMIT_DELAY_MILLIS, rocksdb::RecordTick(), rocksdb::MemTable::Ref(), beast::hash_metrics::detail::score(), rocksdb::MemTable::SetLogNumber(), rocksdb::MemTable::SetNextLogNumber(), rocksdb::MemTableList::size(), rocksdb::Env::SleepForMicroseconds(), SlowdownAmount(), rocksdb::Options::soft_rate_limit, rocksdb::SOFT_RATE_LIMIT_DELAY_COUNT, rocksdb::STALL_L0_NUM_FILES_COUNT, rocksdb::STALL_L0_NUM_FILES_MICROS, rocksdb::STALL_L0_SLOWDOWN_COUNT, rocksdb::STALL_L0_SLOWDOWN_MICROS, stall_level0_num_files_, stall_level0_num_files_count_, stall_level0_slowdown_, stall_level0_slowdown_count_, stall_leveln_slowdown_, stall_leveln_slowdown_count_, stall_memtable_compaction_, rocksdb::STALL_MEMTABLE_COMPACTION_COUNT, stall_memtable_compaction_count_, rocksdb::STALL_MEMTABLE_COMPACTION_MICROS, rocksdb::Options::statistics, storage_options_, rocksdb::port::Mutex::Unlock(), rocksdb::EnvOptions::use_mmap_writes, versions_, rocksdb::port::CondVar::Wait(), rocksdb::Options::wal_dir, rocksdb::Options::write_buffer_size, and writers_.
Referenced by Write().
{
   mutex_.AssertHeld();
   assert(!writers_.empty());
   bool allow_delay = !force;
   bool allow_hard_rate_limit_delay = !force;
   bool allow_soft_rate_limit_delay = !force;
   uint64_t rate_limit_delay_millis = 0;
   Status s;
   double score;
   while (true) {
     if (!bg_error_.ok()) {
       // Yield previous error
       s = bg_error_;
       break;
     } else if (
         allow_delay &&
         versions_->NumLevelFiles(0) >=
           options_.level0_slowdown_writes_trigger) {
       // We are getting close to hitting a hard limit on the number of
       // L0 files.  Rather than delaying a single write by several
       // seconds when we hit the hard limit, start delaying each
       // individual write by 0-1ms to reduce latency variance.  Also,
       // this delay hands over some CPU to the compaction thread in
       // case it is sharing the same core as the writer.
       mutex_.Unlock();
       uint64_t delayed;
       {
         StopWatch sw(env_, options_.statistics, STALL_L0_SLOWDOWN_COUNT);
         env_->SleepForMicroseconds(
           SlowdownAmount(versions_->NumLevelFiles(0),
                          options_.level0_slowdown_writes_trigger,
                          options_.level0_stop_writes_trigger)
         );
         delayed = sw.ElapsedMicros();
       }
       RecordTick(options_.statistics, STALL_L0_SLOWDOWN_MICROS, delayed);
       stall_level0_slowdown_ += delayed;
       stall_level0_slowdown_count_++;
       allow_delay = false;  // Do not delay a single write more than once
       mutex_.Lock();
       delayed_writes_++;
     } else if (!force &&
                (mem_->ApproximateMemoryUsage() <= options_.write_buffer_size)) {
       // There is room in current memtable
       if (allow_delay) {
         DelayLoggingAndReset();
       }
       break;
     } else if (imm_.size() == options_.max_write_buffer_number - 1) {
       // We have filled up the current memtable, but the previous
       // ones are still being compacted, so we wait.
       DelayLoggingAndReset();
       Log(options_.info_log, "wait for memtable compaction...\n");
       uint64_t stall;
       {
         StopWatch sw(env_, options_.statistics,
           STALL_MEMTABLE_COMPACTION_COUNT);
         bg_cv_.Wait();
         stall = sw.ElapsedMicros();
       }
       RecordTick(options_.statistics, STALL_MEMTABLE_COMPACTION_MICROS, stall);
       stall_memtable_compaction_ += stall;
       stall_memtable_compaction_count_++;
     } else if (versions_->NumLevelFiles(0) >=
                options_.level0_stop_writes_trigger) {
       // There are too many level-0 files.
       DelayLoggingAndReset();
       Log(options_.info_log, "wait for fewer level0 files...\n");
       uint64_t stall;
       {
         StopWatch sw(env_, options_.statistics, STALL_L0_NUM_FILES_COUNT);
         bg_cv_.Wait();
         stall = sw.ElapsedMicros();
       }
       RecordTick(options_.statistics, STALL_L0_NUM_FILES_MICROS, stall);
       stall_level0_num_files_ += stall;
       stall_level0_num_files_count_++;
     } else if (
         allow_hard_rate_limit_delay &&
         options_.hard_rate_limit > 1.0 &&
         (score = versions_->MaxCompactionScore()) > options_.hard_rate_limit) {
       // Delay a write when the compaction score for any level is too large.
       int max_level = versions_->MaxCompactionScoreLevel();
       mutex_.Unlock();
       uint64_t delayed;
       {
         StopWatch sw(env_, options_.statistics, HARD_RATE_LIMIT_DELAY_COUNT);
         env_->SleepForMicroseconds(1000);
         delayed = sw.ElapsedMicros();
       }
       stall_leveln_slowdown_[max_level] += delayed;
       stall_leveln_slowdown_count_[max_level]++;
       // Make sure the following value doesn't round to zero.
       uint64_t rate_limit = std::max((delayed / 1000), (uint64_t) 1);
       rate_limit_delay_millis += rate_limit;
       RecordTick(options_.statistics, RATE_LIMIT_DELAY_MILLIS, rate_limit);
       if (options_.rate_limit_delay_max_milliseconds > 0 &&
           rate_limit_delay_millis >=
           (unsigned)options_.rate_limit_delay_max_milliseconds) {
         allow_hard_rate_limit_delay = false;
       }
       mutex_.Lock();
     } else if (
         allow_soft_rate_limit_delay &&
         options_.soft_rate_limit > 0.0 &&
         (score = versions_->MaxCompactionScore()) > options_.soft_rate_limit) {
       // Delay a write when the compaction score for any level is too large.
       // TODO: add statistics
       mutex_.Unlock();
       {
         StopWatch sw(env_, options_.statistics, SOFT_RATE_LIMIT_DELAY_COUNT);
         env_->SleepForMicroseconds(SlowdownAmount(
           score,
           options_.soft_rate_limit,
           options_.hard_rate_limit)
         );
         rate_limit_delay_millis += sw.ElapsedMicros();
       }
       allow_soft_rate_limit_delay = false;
       mutex_.Lock();
     } else {
       // Attempt to switch to a new memtable and trigger compaction of old
       DelayLoggingAndReset();
       assert(versions_->PrevLogNumber() == 0);
       uint64_t new_log_number = versions_->NewFileNumber();
       unique_ptr<WritableFile> lfile;
       EnvOptions soptions(storage_options_);
       soptions.use_mmap_writes = false;
       s = env_->NewWritableFile(
             LogFileName(options_.wal_dir, new_log_number),
             &lfile,
             soptions
           );
       if (!s.ok()) {
         // Avoid chewing through file number space in a tight loop.
         versions_->ReuseFileNumber(new_log_number);
         break;
       }
       // Our final size should be less than write_buffer_size
       // (compression, etc) but err on the side of caution.
       lfile->SetPreallocationBlockSize(1.1 * options_.write_buffer_size);
       logfile_number_ = new_log_number;
       log_.reset(new log::Writer(std::move(lfile)));
       mem_->SetNextLogNumber(logfile_number_);
       imm_.Add(mem_);
       if (force) {
         imm_.FlushRequested();
       }
       mem_ = new MemTable(
           internal_comparator_, mem_rep_factory_, NumberLevels(), options_);
       mem_->Ref();
       Log(options_.info_log,
           "New memtable created with log file: #%lu\n",
           (unsigned long)logfile_number_);
       mem_->SetLogNumber(logfile_number_);
       force = false;   // Do not force another compaction if have room
       MaybeScheduleFlushOrCompaction();
     }
   }
   return s;
 }
int rocksdb::DBImpl::MaxMemCompactionLevel () virtual
Implements rocksdb::DB.
Definition at line 1283 of file db_impl.cc.
References rocksdb::Options::max_mem_compaction_level, and options_.
Referenced by rocksdb::TEST().
{
   return options_.max_mem_compaction_level;
 }
void rocksdb::DBImpl::MaybeDumpStats () private
Definition at line 418 of file db_impl.cc.
References env_, GetProperty(), rocksdb::Options::info_log, last_stats_dump_time_microsec_, rocksdb::Log(), rocksdb::Env::NowMicros(), options_, PrintStatistics(), stats, and rocksdb::Options::stats_dump_period_sec.
Referenced by BackgroundCallCompaction().
{
   if (options_.stats_dump_period_sec == 0) return;
   const uint64_t now_micros = env_->NowMicros();
   if (last_stats_dump_time_microsec_ +
       options_.stats_dump_period_sec * 1000000
       <= now_micros) {
     // Multiple threads could race in here simultaneously.
     // However, the last one will update last_stats_dump_time_microsec_
     // atomically. We could see more than one dump during one dump
     // period in rare cases.
     last_stats_dump_time_microsec_ = now_micros;
     std::string stats;
     GetProperty("rocksdb.stats", &stats);
     Log(options_.info_log, "%s", stats.c_str());
     PrintStatistics();
   }
 }
void rocksdb::DBImpl::MaybeIgnoreError (Status * s) const private
Definition at line 392 of file db_impl.cc.
References rocksdb::Options::info_log, rocksdb::Log(), rocksdb::Status::OK(), rocksdb::Status::ok(), options_, rocksdb::Options::paranoid_checks, and rocksdb::Status::ToString().
Referenced by RecoverLogFile().
{
   if (s->ok() || options_.paranoid_checks) {
     // No change needed
   } else {
     Log(options_.info_log, "Ignoring error %s", s->ToString().c_str());
     *s = Status::OK();
   }
 }
void rocksdb::DBImpl::MaybeScheduleFlushOrCompaction () private
Definition at line 1600 of file db_impl.cc.
References rocksdb::port::AtomicPointer::Acquire_Load(), rocksdb::port::Mutex::AssertHeld(), bg_compaction_scheduled_, bg_flush_scheduled_, bg_work_gate_closed_, BGWorkCompaction(), BGWorkFlush(), env_, imm_, rocksdb::MemTableList::IsFlushPending(), manual_compaction_, rocksdb::Options::max_background_compactions, rocksdb::Options::max_background_flushes, rocksdb::Options::min_write_buffer_number_to_merge, mutex_, options_, rocksdb::Env::Schedule(), shutting_down_, and versions_.
Referenced by BackgroundCallCompaction(), BackgroundCallFlush(), BackgroundCompaction(), GetImpl(), MakeRoomForWrite(), MultiGet(), rocksdb::DB::Open(), and TEST_CompactRange().
{
   mutex_.AssertHeld();
   if (bg_work_gate_closed_) {
     // gate closed for backgrond work
   } else if (shutting_down_.Acquire_Load()) {
     // DB is being deleted; no more background compactions
   } else {
     bool is_flush_pending =
       imm_.IsFlushPending(options_.min_write_buffer_number_to_merge);
     if (is_flush_pending &&
         (bg_flush_scheduled_ < options_.max_background_flushes)) {
       // memtable flush needed
       bg_flush_scheduled_++;
       env_->Schedule(&DBImpl::BGWorkFlush, this, Env::Priority::HIGH);
     }
     if ((manual_compaction_ ||
          versions_->NeedsCompaction() ||
          (is_flush_pending && (options_.max_background_flushes <= 0))) &&
         bg_compaction_scheduled_ < options_.max_background_compactions) {
       // compaction needed, or memtable flush needed but HIGH pool not enabled.
       bg_compaction_scheduled_++;
       env_->Schedule(&DBImpl::BGWorkCompaction, this, Env::Priority::LOW);
     }
   }
 }
void rocksdb::DBImpl::MaybeScheduleLogDBDeployStats () private
Definition at line 22 of file db_stats_logger.cc.
References rocksdb::port::AtomicPointer::Acquire_Load(), bg_logstats_scheduled_, BGLogDBDeployStats(), rocksdb::Options::db_stats_log_interval, env_, rocksdb::Env::GetCurrentTime(), host_name_, last_log_ts, logger_, rocksdb::Status::ok(), options_, rocksdb::Env::Schedule(), and shutting_down_.
Referenced by BackgroundCallCompaction(), FlushMemTableToOutputFile(), and rocksdb::DB::Open().
{
   // There is a lock in the actual logger.
   if (!logger_ || options_.db_stats_log_interval < 0
       || host_name_.empty()) {
     return;
   }
   if(bg_logstats_scheduled_ || shutting_down_.Acquire_Load()) {
     // Already scheduled
   } else {
     int64_t current_ts = 0;
     Status st = env_->GetCurrentTime(&current_ts);
     if (!st.ok()) {
       return;
     }
     if ((current_ts - last_log_ts) < options_.db_stats_log_interval) {
       return;
     }
     last_log_ts = current_ts;
     bg_logstats_scheduled_ = true;
     env_->Schedule(&DBImpl::BGLogDBDeployStats, this);
   }
 }
Status rocksdb::DBImpl::Merge (const WriteOptions & o, const Slice & key, const Slice & value) virtual
Implements rocksdb::DB.
Reimplemented in rocksdb::DBImplReadOnly.
Definition at line 2746 of file db_impl.cc.
References rocksdb::DB::Merge(), rocksdb::Options::merge_operator, rocksdb::Status::NotSupported(), and options_.
Referenced by MergeBasedCounters::add(), and rocksdb::StringLists::Append().
{
   if (!options_.merge_operator) {
     return Status::NotSupported("Provide a merge_operator when opening DB");
   } else {
     return DB::Merge(o, key, val);
   }
 }
std::vector< Status > rocksdb::DBImpl::MultiGet (const ReadOptions & options, const std::vector< Slice > & keys, std::vector< std::string > * values) virtual
Implements rocksdb::DB.
Definition at line 2616 of file db_impl.cc.
References rocksdb::DB_MULTIGET, rocksdb::Options::disable_seek_compaction, env_, rocksdb::MemTableList::Get(), rocksdb::Version::Get(), rocksdb::MemTable::Get(), imm_, rocksdb::Options::info_log, rocksdb::port::Mutex::Lock(), rocksdb::LogFlush(), MaybeScheduleFlushOrCompaction(), mem, mem_, merge_operands, mutex_, rocksdb::NUMBER_MULTIGET_BYTES_READ, rocksdb::NUMBER_MULTIGET_CALLS, rocksdb::NUMBER_MULTIGET_KEYS_READ, rocksdb::Status::ok(), options_, rocksdb::RecordTick(), rocksdb::MemTable::Ref(), rocksdb::Version::Ref(), rocksdb::MemTableList::RefAll(), rocksdb::ReadOptions::snapshot, rocksdb::Options::statistics, stats, rocksdb::port::Mutex::Unlock(), rocksdb::MemTable::Unref(), rocksdb::Version::Unref(), rocksdb::MemTableList::UnrefAll(), rocksdb::Version::UpdateStats(), value, and versions_.
Referenced by rocksdb::TEST().
{
   StopWatch sw(env_, options_.statistics, DB_MULTIGET);
   SequenceNumber snapshot;
   mutex_.Lock();
   if (options.snapshot != nullptr) {
     snapshot = reinterpret_cast<const SnapshotImpl*>(options.snapshot)->number_;
   } else {
     snapshot = versions_->LastSequence();
   }
   MemTable* mem = mem_;
   MemTableList imm = imm_;
   Version* current = versions_->current();
   mem->Ref();
   imm.RefAll();
   current->Ref();
   // Unlock while reading from files and memtables
   mutex_.Unlock();
   bool have_stat_update = false;
   Version::GetStats stats;
   // Prepare to store a list of merge operations if merge occurs.
   std::deque<std::string> merge_operands;
   // Note: this always resizes the values array
   int numKeys = keys.size();
   std::vector<Status> statList(numKeys);
   values->resize(numKeys);
   // Keep track of bytes that we read for statistics-recording later
   uint64_t bytesRead = 0;
   // For each of the given keys, apply the entire "get" process as follows:
   // First look in the memtable, then in the immutable memtable (if any).
   // s is both in/out. When in, s could either be OK or MergeInProgress.
   // merge_operands will contain the sequence of merges in the latter case.
   for (int i=0; i<numKeys; ++i) {
     merge_operands.clear();
     Status& s = statList[i];
     std::string* value = &(*values)[i];
     LookupKey lkey(keys[i], snapshot);
     if (mem->Get(lkey, value, &s, &merge_operands, options_)) {
       // Done
     } else if (imm.Get(lkey, value, &s, &merge_operands, options_)) {
       // Done
     } else {
       current->Get(options, lkey, value, &s, &merge_operands, &stats, options_);
       have_stat_update = true;
     }
     if (s.ok()) {
       bytesRead += value->size();
     }
   }
   // Post processing (decrement reference counts and record statistics)
   mutex_.Lock();
   if (!options_.disable_seek_compaction &&
       have_stat_update && current->UpdateStats(stats)) {
     MaybeScheduleFlushOrCompaction();
   }
   mem->Unref();
   imm.UnrefAll();
   current->Unref();
   mutex_.Unlock();
   LogFlush(options_.info_log);
   RecordTick(options_.statistics, NUMBER_MULTIGET_CALLS);
   RecordTick(options_.statistics, NUMBER_MULTIGET_KEYS_READ, numKeys);
   RecordTick(options_.statistics, NUMBER_MULTIGET_BYTES_READ, bytesRead);
   return statList;
 }
Status rocksdb::DBImpl::NewDB () private
Definition at line 363 of file db_impl.cc.
References rocksdb::log::Writer::AddRecord(), dbname_, rocksdb::Env::DeleteFile(), rocksdb::DescriptorFileName(), rocksdb::VersionEdit::EncodeTo(), env_, rocksdb::Options::manifest_preallocation_size, rocksdb::Env::NewWritableFile(), NumberLevels(), rocksdb::Status::ok(), options_, rocksdb::VersionEdit::SetComparatorName(), rocksdb::SetCurrentFile(), rocksdb::VersionEdit::SetLastSequence(), rocksdb::VersionEdit::SetLogNumber(), rocksdb::VersionEdit::SetNextFile(), storage_options_, and user_comparator().
Referenced by Recover().
                      {
   VersionEdit new_db(NumberLevels());
   new_db.SetComparatorName(user_comparator()->Name());
   new_db.SetLogNumber(0);
   new_db.SetNextFile(2);
   new_db.SetLastSequence(0);
   const std::string manifest = DescriptorFileName(dbname_, 1);
   unique_ptr<WritableFile> file;
   Status s = env_->NewWritableFile(manifest, &file, storage_options_);
   if (!s.ok()) {
     return s;
   }
   file->SetPreallocationBlockSize(options_.manifest_preallocation_size);
   {
     log::Writer log(std::move(file));
     std::string record;
     new_db.EncodeTo(&record);
     s = log.AddRecord(record);
   }
   if (s.ok()) {
     // Make "CURRENT" file that points to the new manifest file.
     s = SetCurrentFile(env_, dbname_, 1);
   } else {
     env_->DeleteFile(manifest);
   }
   return s;
 }
Iterator * rocksdb::DBImpl::NewInternalIterator (const ReadOptions & options, SequenceNumber * latest_snapshot) protected
Definition at line 2499 of file db_impl.cc.
References rocksdb::MemTableList::GetMemTables(), imm_, rocksdb::Options::info_log, internal_comparator_, rocksdb::port::Mutex::Lock(), rocksdb::LogFlush(), mem_, mutex_, rocksdb::MemTable::NewIterator(), rocksdb::NewMergingIterator(), options_, rocksdb::MemTable::Ref(), rocksdb::Iterator::RegisterCleanup(), storage_options_, rocksdb::port::Mutex::Unlock(), and versions_.
Referenced by rocksdb::DBImplReadOnly::NewIterator(), NewIterator(), and TEST_NewInternalIterator().
{
   IterState* cleanup = new IterState;
   mutex_.Lock();
   *latest_snapshot = versions_->LastSequence();
   // Collect together all needed child iterators for mem
   std::vector<Iterator*> list;
   mem_->Ref();
   list.push_back(mem_->NewIterator(options));
   cleanup->mem.push_back(mem_);
   // Collect together all needed child iterators for imm_
   std::vector<MemTable*> immutables;
   imm_.GetMemTables(&immutables);
   for (unsigned int i = 0; i < immutables.size(); i++) {
     MemTable* m = immutables[i];
     m->Ref();
     list.push_back(m->NewIterator(options));
     cleanup->mem.push_back(m);
   }
   // Collect iterators for files in L0 - Ln
   versions_->current()->AddIterators(options, storage_options_, &list);
   Iterator* internal_iter =
       NewMergingIterator(&internal_comparator_, &list[0], list.size());
   versions_->current()->Ref();
   cleanup->mu = &mutex_;
   cleanup->db = this;
   cleanup->version = versions_->current();
   internal_iter->RegisterCleanup(CleanupIteratorState, cleanup, nullptr);
   mutex_.Unlock();
   LogFlush(options_.info_log);
   return internal_iter;
 }
Iterator * rocksdb::DBImpl::NewIterator (const ReadOptions & options) virtual
Implements rocksdb::DB.
Reimplemented in rocksdb::DBImplReadOnly.
Definition at line 2714 of file db_impl.cc.
References dbname_, env_, rocksdb::NewDBIterator(), NewInternalIterator(), options_, rocksdb::ReadOptions::prefix, rocksdb::Options::prefix_extractor, rocksdb::ReadOptions::snapshot, and user_comparator().
Referenced by rocksdb::TEST().
{
   SequenceNumber latest_snapshot;
   Iterator* iter = NewInternalIterator(options, &latest_snapshot);
   iter = NewDBIterator(
              &dbname_, env_, options_, user_comparator(), iter,
              (options.snapshot != nullptr
               ? reinterpret_cast<const SnapshotImpl*>(options.snapshot)->number_
               : latest_snapshot));
   if (options.prefix) {
     // use extra wrapper to exclude any keys from the results which
     // don't begin with the prefix
     iter = new PrefixFilterIterator(iter, *options.prefix,
                                     options_.prefix_extractor);
   }
   return iter;
 }
int rocksdb::DBImpl::NumberLevels () virtual
Implements rocksdb::DB.
Definition at line 1279 of file db_impl.cc.
References rocksdb::Options::num_levels, and options_.
Referenced by CompactRange(), DeleteFile(), GetProperty(), MakeRoomForWrite(), NewDB(), rocksdb::DB::Open(), rocksdb::DB::OpenForReadOnly(), RecoverLogFile(), ReFitLevel(), and rocksdb::TEST().
{
   return options_.num_levels;
 }
Status rocksdb::DBImpl::OpenCompactionOutputFile (CompactionState * compact) private
Definition at line 1908 of file db_impl.cc.
References rocksdb::DBImpl::CompactionState::allocated_file_numbers, rocksdb::DBImpl::CompactionState::builder, rocksdb::InternalKey::Clear(), rocksdb::DBImpl::CompactionState::compaction, dbname_, rocksdb::Compaction::enable_compression(), env_, rocksdb::GetCompressionType(), rocksdb::GetTableBuilder(), rocksdb::Options::info_log, rocksdb::DBImpl::CompactionState::Output::largest, rocksdb::DBImpl::CompactionState::Output::largest_seqno, rocksdb::port::Mutex::Lock(), rocksdb::LogFlush(), mutex_, rocksdb::Env::NewWritableFile(), rocksdb::DBImpl::CompactionState::Output::number, rocksdb::Status::ok(), options_, rocksdb::DBImpl::CompactionState::outfile, rocksdb::Compaction::output_level(), rocksdb::DBImpl::CompactionState::outputs, pending_outputs_, rocksdb::DBImpl::CompactionState::Output::smallest, rocksdb::DBImpl::CompactionState::Output::smallest_seqno, storage_options_, rocksdb::TableFileName(), rocksdb::port::Mutex::Unlock(), and versions_.
Referenced by DoCompactionWork().
{
   assert(compact != nullptr);
   assert(compact->builder == nullptr);
   uint64_t file_number;
   // If we have not yet exhausted the pre-allocated file numbers,
   // then use the one from the front. Otherwise, we have to acquire
   // the heavyweight lock and allocate a new file number.
   if (!compact->allocated_file_numbers.empty()) {
     file_number = compact->allocated_file_numbers.front();
     compact->allocated_file_numbers.pop_front();
   } else {
     mutex_.Lock();
     file_number = versions_->NewFileNumber();
     pending_outputs_.insert(file_number);
     mutex_.Unlock();
   }
   CompactionState::Output out;
   out.number = file_number;
   out.smallest.Clear();
   out.largest.Clear();
   out.smallest_seqno = out.largest_seqno = 0;
   compact->outputs.push_back(out);
   // Make the output file
   std::string fname = TableFileName(dbname_, file_number);
   Status s = env_->NewWritableFile(fname, &compact->outfile, storage_options_);
   if (s.ok()) {
     // Over-estimate slightly so we don't end up just barely crossing
     // the threshold.
     compact->outfile->SetPreallocationBlockSize(
       1.1 * versions_->MaxFileSizeForLevel(compact->compaction->output_level()));
     CompressionType compression_type = GetCompressionType(
         options_, compact->compaction->output_level(),
         compact->compaction->enable_compression());
     compact->builder.reset(
         GetTableBuilder(options_, compact->outfile.get(), compression_type));
   }
   LogFlush(options_.info_log);
   return s;
 }
void rocksdb::DBImpl::operator= (const DBImpl &) private
void rocksdb::DBImpl::PrintStatistics () private
Definition at line 409 of file db_impl.cc.
References dbstats, rocksdb::Options::info_log, rocksdb::Log(), options_, and rocksdb::Options::statistics.
Referenced by MaybeDumpStats().
{
   auto dbstats = options_.statistics;
   if (dbstats) {
     Log(options_.info_log,
         "STATISTCS:\n %s",
         dbstats->ToString().c_str());
   }
 }
void rocksdb::DBImpl::PurgeObsoleteFiles (DeletionState & deletion_state)
Definition at line 511 of file db_impl.cc.
References rocksdb::DBImpl::DeletionState::all_files, rocksdb::ArchivedLogFileName(), rocksdb::Options::db_log_dir, dbname_, rocksdb::Env::DeleteFile(), env_, rocksdb::Options::info_log, rocksdb::kCurrentFile, rocksdb::kDBLockFile, rocksdb::kDescriptorFile, rocksdb::Options::keep_log_file_num, rocksdb::kIdentityFile, rocksdb::kInfoLogFile, rocksdb::kLogFile, rocksdb::kMetaDatabase, rocksdb::kTableFile, rocksdb::kTempFile, rocksdb::Log(), rocksdb::DBImpl::DeletionState::log_delete_files, rocksdb::DBImpl::DeletionState::log_number, rocksdb::LogFileName(), rocksdb::LogFlush(), rocksdb::DBImpl::DeletionState::manifest_file_number, rocksdb::Status::ok(), options_, rocksdb::ParseFileName(), rocksdb::DBImpl::DeletionState::prev_log_number, PurgeObsoleteWALFiles(), rocksdb::Env::RenameFile(), rocksdb::DBImpl::DeletionState::sst_delete_files, rocksdb::DBImpl::DeletionState::sst_live, table_cache_, rocksdb::TableFileName(), rocksdb::Status::ToString(), rocksdb::Options::wal_dir, rocksdb::Options::WAL_size_limit_MB, and rocksdb::Options::WAL_ttl_seconds.
Referenced by BackgroundCallCompaction(), BackgroundCallFlush(), DeleteFile(), DeleteObsoleteFiles(), and EnableFileDeletions().
{
   // this checks if FindObsoleteFiles() was run before. If not, don't do
   // PurgeObsoleteFiles(). If FindObsoleteFiles() was run, we need to also
   // run PurgeObsoleteFiles(), even if disable_delete_obsolete_files_ is true
   if (state.manifest_file_number == 0) {
     return;
   }
   uint64_t number;
   FileType type;
   std::vector<std::string> old_log_files;
   // Now, convert live list to an unordered set, WITHOUT mutex held;
   // set is slow.
   std::unordered_set<uint64_t> live_set(state.sst_live.begin(),
                                         state.sst_live.end());
   state.all_files.reserve(state.all_files.size() +
       state.sst_delete_files.size());
   for (auto file : state.sst_delete_files) {
     state.all_files.push_back(TableFileName("", file->number).substr(1));
     delete file;
   }
   state.all_files.reserve(state.all_files.size() +
       state.log_delete_files.size());
   for (auto filenum : state.log_delete_files) {
     if (filenum > 0) {
       state.all_files.push_back(LogFileName("", filenum).substr(1));
     }
   }
   // dedup state.all_files so we don't try to delete the same
   // file twice
   sort(state.all_files.begin(), state.all_files.end());
   auto unique_end = unique(state.all_files.begin(), state.all_files.end());
   for (size_t i = 0; state.all_files.begin() + i < unique_end; i++) {
     if (ParseFileName(state.all_files[i], &number, &type)) {
       bool keep = true;
       switch (type) {
         case kLogFile:
           keep = ((number >= state.log_number) ||
                   (number == state.prev_log_number));
           break;
         case kDescriptorFile:
           // Keep my manifest file, and any newer incarnations'
           // (in case there is a race that allows other incarnations)
           keep = (number >= state.manifest_file_number);
           break;
         case kTableFile:
           keep = (live_set.find(number) != live_set.end());
           break;
         case kTempFile:
           // Any temp files that are currently being written to must
           // be recorded in pending_outputs_, which is inserted into "live"
           keep = (live_set.find(number) != live_set.end());
           break;
         case kInfoLogFile:
           keep = true;
           if (number != 0) {
             old_log_files.push_back(state.all_files[i]);
           }
           break;
         case kCurrentFile:
         case kDBLockFile:
         case kIdentityFile:
         case kMetaDatabase:
           keep = true;
           break;
       }
       if (!keep) {
         if (type == kTableFile) {
           // evict from cache
           table_cache_->Evict(number);
         }
         std::string fname = ((type == kLogFile) ? options_.wal_dir : dbname_) +
             "/" + state.all_files[i];
         Log(options_.info_log,
             "Delete type=%d #%lu",
             int(type),
             (unsigned long)number);
         Status st;
         if (type == kLogFile && (options_.WAL_ttl_seconds > 0 ||
               options_.WAL_size_limit_MB > 0)) {
             st = env_->RenameFile(fname,
                 ArchivedLogFileName(options_.wal_dir, number));
             if (!st.ok()) {
               Log(options_.info_log,
                   "RenameFile logfile #%lu FAILED -- %s\n",
                   (unsigned long)number, st.ToString().c_str());
             }
         } else {
           st = env_->DeleteFile(fname);
           if (!st.ok()) {
             Log(options_.info_log, "Delete type=%d #%lu FAILED -- %s\n",
                 int(type), (unsigned long)number, st.ToString().c_str());
           }
         }
       }
     }
   }
   // Delete old info log files.
   size_t old_log_file_count = old_log_files.size();
   // NOTE: Currently we only support log purge when options_.db_log_dir is
   // located in `dbname` directory.
   if (old_log_file_count >= options_.keep_log_file_num &&
       options_.db_log_dir.empty()) {
     std::sort(old_log_files.begin(), old_log_files.end());
     size_t end = old_log_file_count - options_.keep_log_file_num;
     for (unsigned int i = 0; i <= end; i++) {
       std::string& to_delete = old_log_files.at(i);
       // Log(options_.info_log, "Delete type=%d %s\n",
       //     int(kInfoLogFile), to_delete.c_str());
       env_->DeleteFile(dbname_ + "/" + to_delete);
     }
   }
   PurgeObsoleteWALFiles();
   LogFlush(options_.info_log);
 }
void rocksdb::DBImpl::PurgeObsoleteWALFiles () private
Definition at line 650 of file db_impl.cc.
References AppendSortedWalsOfType(), rocksdb::ArchivalDirectory(), default_interval_to_delete_obsolete_WAL_, DeleteFile(), rocksdb::Env::DeleteFile(), env_, ripple::f, rocksdb::Env::GetChildren(), rocksdb::Env::GetCurrentTime(), rocksdb::Env::GetFileModificationTime(), rocksdb::Env::GetFileSize(), rocksdb::if(), rocksdb::Options::info_log, rocksdb::kArchivedLogFile, rocksdb::kLogFile, rocksdb::Log(), ripple::max(), rocksdb::Status::ok(), options_, rocksdb::ParseFileName(), purge_wal_files_last_run_, rocksdb::Status::ToString(), rocksdb::Options::wal_dir, rocksdb::Options::WAL_size_limit_MB, and rocksdb::Options::WAL_ttl_seconds.
Referenced by PurgeObsoleteFiles(), and TEST_PurgeObsoleteteWAL().
{
   bool const ttl_enabled = options_.WAL_ttl_seconds > 0;
   bool const size_limit_enabled =  options_.WAL_size_limit_MB > 0;
   if (!ttl_enabled && !size_limit_enabled) {
     return;
   }
   int64_t current_time;
   Status s = env_->GetCurrentTime(&current_time);
   if (!s.ok()) {
     Log(options_.info_log, "Can't get current time: %s", s.ToString().c_str());
     assert(false);
     return;
   }
   uint64_t const now_seconds = static_cast<uint64_t>(current_time);
   uint64_t const time_to_check = (ttl_enabled && !size_limit_enabled) ?
     options_.WAL_ttl_seconds / 2 : default_interval_to_delete_obsolete_WAL_;
   if (purge_wal_files_last_run_ + time_to_check > now_seconds) {
     return;
   }
   purge_wal_files_last_run_ = now_seconds;
   std::string archival_dir = ArchivalDirectory(options_.wal_dir);
   std::vector<std::string> files;
   s = env_->GetChildren(archival_dir, &files);
   if (!s.ok()) {
     Log(options_.info_log, "Can't get archive files: %s", s.ToString().c_str());
     assert(false);
     return;
   }
   size_t log_files_num = 0;
   uint64_t log_file_size = 0;
   for (auto& f : files) {
     uint64_t number;
     FileType type;
     if (ParseFileName(f, &number, &type) && type == kLogFile) {
       std::string const file_path = archival_dir + "/" + f;
       if (ttl_enabled) {
         uint64_t file_m_time;
         Status const s = env_->GetFileModificationTime(file_path,
           &file_m_time);
         if (!s.ok()) {
           Log(options_.info_log, "Can't get file mod time: %s: %s",
               file_path.c_str(), s.ToString().c_str());
           continue;
         }
         if (now_seconds - file_m_time > options_.WAL_ttl_seconds) {
           Status const s = env_->DeleteFile(file_path);
           if (!s.ok()) {
             Log(options_.info_log, "Can't delete file: %s: %s",
                 file_path.c_str(), s.ToString().c_str());
             continue;
           }
           continue;
         }
       }
       if (size_limit_enabled) {
         uint64_t file_size;
         Status const s = env_->GetFileSize(file_path, &file_size);
         if (!s.ok()) {
           Log(options_.info_log, "Can't get file size: %s: %s",
               file_path.c_str(), s.ToString().c_str());
           return;
         } else {
           if (file_size > 0) {
             log_file_size = std::max(log_file_size, file_size);
             ++log_files_num;
           } else {
             Status s = env_->DeleteFile(file_path);
             if (!s.ok()) {
               Log(options_.info_log, "Can't delete file: %s: %s",
                   file_path.c_str(), s.ToString().c_str());
               continue;
             }
           }
         }
       }
     }
   }
   if (0 == log_files_num || !size_limit_enabled) {
     return;
   }
   size_t const files_keep_num = options_.WAL_size_limit_MB *
     1024 * 1024 / log_file_size;
   if (log_files_num <= files_keep_num) {
     return;
   }
   size_t files_del_num = log_files_num - files_keep_num;
   VectorLogPtr archived_logs;
   AppendSortedWalsOfType(archival_dir, archived_logs, kArchivedLogFile);
   if (files_del_num > archived_logs.size()) {
     Log(options_.info_log, "Trying to delete more archived log files than "
         "exist. Deleting all");
     files_del_num = archived_logs.size();
   }
   for (size_t i = 0; i < files_del_num; ++i) {
     std::string const file_path = archived_logs[i]->PathName();
     Status const s = DeleteFile(file_path);
     if (!s.ok()) {
       Log(options_.info_log, "Can't delete file: %s: %s",
           file_path.c_str(), s.ToString().c_str());
       continue;
     }
   }
 }
Status rocksdb::DBImpl::Put (const WriteOptions & o, const Slice & key, const Slice & value) virtual
Implements rocksdb::DB.
Reimplemented in rocksdb::DBImplReadOnly.
Definition at line 2742 of file db_impl.cc.
References rocksdb::DB::Put().
Referenced by rocksdb::ProfileKeyComparison(), Counters::set(), and rocksdb::TEST().
{
   return DB::Put(o, key, val);
 }
Status rocksdb::DBImpl::ReadFirstLine (const std::string & fname, WriteBatch *const batch) private
Definition at line 1387 of file db_impl.cc.
References rocksdb::LogReporter::Corruption(), rocksdb::Status::Corruption(), rocksdb::LogReporter::env, env, env_, rocksdb::LogReporter::info_log, rocksdb::Options::info_log, rocksdb::Status::IOError(), rocksdb::Log(), rocksdb::Env::NewSequentialFile(), rocksdb::Status::OK(), rocksdb::Status::ok(), options_, rocksdb::Options::paranoid_checks, rocksdb::log::Reader::ReadRecord(), rocksdb::WriteBatchInternal::SetContents(), rocksdb::Slice::size(), storage_options_, and rocksdb::Status::ToString().
Referenced by ReadFirstRecord().
{
   struct LogReporter : public log::Reader::Reporter {
     Env* env;
     Logger* info_log;
     const char* fname;
     Status* status;  // nullptr if options_.paranoid_checks==false
     virtual void Corruption(size_t bytes, const Status& s) {
       Log(info_log, "%s%s: dropping %d bytes; %s",
           (this->status == nullptr ? "(ignoring error) " : ""),
           fname, static_cast<int>(bytes), s.ToString().c_str());
       if (this->status != nullptr && this->status->ok()) *this->status = s;
     }
   };
   unique_ptr<SequentialFile> file;
   Status status = env_->NewSequentialFile(fname, &file, storage_options_);
   if (!status.ok()) {
     return status;
   }
   LogReporter reporter;
   reporter.env = env_;
   reporter.info_log = options_.info_log.get();
   reporter.fname = fname.c_str();
   reporter.status = (options_.paranoid_checks ? &status : nullptr);
   log::Reader reader(std::move(file), &reporter, true/*checksum*/,
                      0/*initial_offset*/);
   std::string scratch;
   Slice record;
   if (reader.ReadRecord(&record, &scratch) && status.ok()) {
     if (record.size() < 12) {
       reporter.Corruption(
           record.size(), Status::Corruption("log record too small"));
       return Status::IOError("Corruption noted");
       //  TODO read record's till the first no corrupt entry?
     }
     WriteBatchInternal::SetContents(batch, record);
     return Status::OK();
   }
   return Status::IOError("Error reading from file " + fname);
 }
Status rocksdb::DBImpl::ReadFirstRecord (const WalFileType type, const uint64_t number, WriteBatch *const result) private
Definition at line 1363 of file db_impl.cc.
References rocksdb::ArchivedLogFileName(), rocksdb::Status::IOError(), rocksdb::kAliveLogFile, rocksdb::kArchivedLogFile, rocksdb::LogFileName(), rocksdb::Status::NotSupported(), rocksdb::Status::OK(), rocksdb::Status::ok(), options_, ReadFirstLine(), beast::IP::to_string(), and rocksdb::Options::wal_dir.
Referenced by AppendSortedWalsOfType().
{
   if (type == kAliveLogFile) {
     std::string fname = LogFileName(options_.wal_dir, number);
     Status status = ReadFirstLine(fname, result);
     if (!status.ok()) {
       //  check if the file got moved to archive.
       std::string archived_file =
         ArchivedLogFileName(options_.wal_dir, number);
       Status s = ReadFirstLine(archived_file, result);
       if (!s.ok()) {
         return Status::IOError("Log File has been deleted: " + archived_file);
       }
     }
     return Status::OK();
   } else if (type == kArchivedLogFile) {
     std::string fname = ArchivedLogFileName(options_.wal_dir, number);
     Status status = ReadFirstLine(fname, result);
     return status;
   }
   return Status::NotSupported("File Type Not Known: " + std::to_string(type));
 }
Status rocksdb::DBImpl::Recover (VersionEdit * edit, MemTable * external_table = nullptr, bool error_if_log_file_exist = false) private
Definition at line 768 of file db_impl.cc.
References rocksdb::port::Mutex::AssertHeld(), rocksdb::Status::Corruption(), rocksdb::Options::create_if_missing, rocksdb::Env::CreateDirIfMissing(), rocksdb::CurrentFileName(), db_lock_, dbname_, env_, rocksdb::Options::error_if_exists, rocksdb::Env::FileExists(), rocksdb::Env::GetChildren(), rocksdb::IdentityFileName(), rocksdb::Status::InvalidArgument(), rocksdb::kLogFile, rocksdb::Env::LockFile(), rocksdb::LockFileName(), max_sequence, mutex_, NewDB(), rocksdb::Status::ok(), options_, rocksdb::ParseFileName(), RecoverLogFile(), rocksdb::SEQUENCE_NUMBER, rocksdb::SetIdentityFile(), rocksdb::SetTickerCount(), rocksdb::Options::statistics, versions_, and rocksdb::Options::wal_dir.
Referenced by rocksdb::DB::Open().
{
   mutex_.AssertHeld();
   assert(db_lock_ == nullptr);
   if (!external_table) {
     // We call CreateDirIfMissing() as the directory may already exist (if we
     // are reopening a DB), when this happens we don't want creating the
     // directory to cause an error. However, we need to check if creating the
     // directory fails or else we may get an obscure message about the lock
     // file not existing. One real-world example of this occurring is if
     // env->CreateDirIfMissing() doesn't create intermediate directories, e.g.
     // when dbname_ is "dir/db" but when "dir" doesn't exist.
     Status s = env_->CreateDirIfMissing(dbname_);
     if (!s.ok()) {
       return s;
     }
     s = env_->LockFile(LockFileName(dbname_), &db_lock_);
     if (!s.ok()) {
       return s;
     }
     if (!env_->FileExists(CurrentFileName(dbname_))) {
       if (options_.create_if_missing) {
         // TODO: add merge_operator name check
         s = NewDB();
         if (!s.ok()) {
           return s;
         }
       } else {
         return Status::InvalidArgument(
             dbname_, "does not exist (create_if_missing is false)");
       }
     } else {
       if (options_.error_if_exists) {
         return Status::InvalidArgument(
             dbname_, "exists (error_if_exists is true)");
       }
     }
     // Check for the IDENTITY file and create it if not there
     if (!env_->FileExists(IdentityFileName(dbname_))) {
       s = SetIdentityFile(env_, dbname_);
       if (!s.ok()) {
         return s;
       }
     }
   }
   Status s = versions_->Recover();
   if (s.ok()) {
     SequenceNumber max_sequence(0);
     // Recover from all newer log files than the ones named in the
     // descriptor (new log files may have been added by the previous
     // incarnation without registering them in the descriptor).
     //
     // Note that PrevLogNumber() is no longer used, but we pay
     // attention to it in case we are recovering a database
     // produced by an older version of rocksdb.
     const uint64_t min_log = versions_->LogNumber();
     const uint64_t prev_log = versions_->PrevLogNumber();
     std::vector<std::string> filenames;
     s = env_->GetChildren(options_.wal_dir, &filenames);
     if (!s.ok()) {
       return s;
     }
     uint64_t number;
     FileType type;
     std::vector<uint64_t> logs;
     for (size_t i = 0; i < filenames.size(); i++) {
       if (ParseFileName(filenames[i], &number, &type)
           && type == kLogFile
           && ((number >= min_log) || (number == prev_log))) {
         logs.push_back(number);
       }
     }
     if (logs.size() > 0 && error_if_log_file_exist) {
       return Status::Corruption(""
           "The db was opened in readonly mode with error_if_log_file_exist"
           "flag but a log file already exists");
     }
     // Recover in the order in which the logs were generated
     std::sort(logs.begin(), logs.end());
     for (size_t i = 0; i < logs.size(); i++) {
       s = RecoverLogFile(logs[i], edit, &max_sequence, external_table);
       // The previous incarnation may not have written any MANIFEST
       // records after allocating this log number.  So we manually
       // update the file number allocation counter in VersionSet.
       versions_->MarkFileNumberUsed(logs[i]);
     }
     if (s.ok()) {
       if (versions_->LastSequence() < max_sequence) {
         versions_->SetLastSequence(max_sequence);
       }
       SetTickerCount(options_.statistics, SEQUENCE_NUMBER,
                      versions_->LastSequence());
     }
   }
   return s;
 }
Status rocksdb::DBImpl::RecoverLogFile (uint64_t log_number, VersionEdit * edit, SequenceNumber * max_sequence, MemTable * external_table) private
Definition at line 874 of file db_impl.cc.
References rocksdb::MemTable::ApproximateMemoryUsage(), rocksdb::port::Mutex::AssertHeld(), rocksdb::LogReporter::Corruption(), rocksdb::Status::Corruption(), rocksdb::WriteBatchInternal::Count(), rocksdb::LogReporter::env, env, env_, rocksdb::LogReporter::info_log, rocksdb::Options::info_log, rocksdb::WriteBatchInternal::InsertInto(), internal_comparator_, rocksdb::Log(), rocksdb::LogFileName(), MaybeIgnoreError(), mem, mem_rep_factory_, mutex_, rocksdb::Env::NewSequentialFile(), NumberLevels(), rocksdb::Status::ok(), options_, rocksdb::Options::paranoid_checks, rocksdb::log::Reader::ReadRecord(), rocksdb::MemTable::Ref(), rocksdb::WriteBatchInternal::Sequence(), rocksdb::WriteBatchInternal::SetContents(), rocksdb::Slice::size(), rocksdb::Options::skip_log_error_on_recovery, storage_options_, rocksdb::Status::ToString(), rocksdb::MemTable::Unref(), rocksdb::Options::wal_dir, rocksdb::Options::write_buffer_size, and WriteLevel0TableForRecovery().
Referenced by Recover().
{
   struct LogReporter : public log::Reader::Reporter {
     Env* env;
     Logger* info_log;
     const char* fname;
     Status* status;  // nullptr if options_.paranoid_checks==false or
                      //            options_.skip_log_error_on_recovery==true
     virtual void Corruption(size_t bytes, const Status& s) {
       Log(info_log, "%s%s: dropping %d bytes; %s",
           (this->status == nullptr ? "(ignoring error) " : ""),
           fname, static_cast<int>(bytes), s.ToString().c_str());
       if (this->status != nullptr && this->status->ok()) *this->status = s;
     }
   };
   mutex_.AssertHeld();
   // Open the log file
   std::string fname = LogFileName(options_.wal_dir, log_number);
   unique_ptr<SequentialFile> file;
   Status status = env_->NewSequentialFile(fname, &file, storage_options_);
   if (!status.ok()) {
     MaybeIgnoreError(&status);
     return status;
   }
   // Create the log reader.
   LogReporter reporter;
   reporter.env = env_;
   reporter.info_log = options_.info_log.get();
   reporter.fname = fname.c_str();
   reporter.status = (options_.paranoid_checks &&
                      !options_.skip_log_error_on_recovery ? &status : nullptr);
   // We intentially make log::Reader do checksumming even if
   // paranoid_checks==false so that corruptions cause entire commits
   // to be skipped instead of propagating bad information (like overly
   // large sequence numbers).
   log::Reader reader(std::move(file), &reporter, true/*checksum*/,
                      0/*initial_offset*/);
   Log(options_.info_log, "Recovering log #%lu",
       (unsigned long) log_number);
   // Read all the records and add to a memtable
   std::string scratch;
   Slice record;
   WriteBatch batch;
   MemTable* mem = nullptr;
   if (external_table) {
     mem = external_table;
   }
   while (reader.ReadRecord(&record, &scratch) && status.ok()) {
     if (record.size() < 12) {
       reporter.Corruption(
           record.size(), Status::Corruption("log record too small"));
       continue;
     }
     WriteBatchInternal::SetContents(&batch, record);
     if (mem == nullptr) {
       mem = new MemTable(internal_comparator_, mem_rep_factory_,
         NumberLevels(), options_);
       mem->Ref();
     }
     status = WriteBatchInternal::InsertInto(&batch, mem, &options_);
     MaybeIgnoreError(&status);
     if (!status.ok()) {
       break;
     }
     const SequenceNumber last_seq =
         WriteBatchInternal::Sequence(&batch) +
         WriteBatchInternal::Count(&batch) - 1;
     if (last_seq > *max_sequence) {
       *max_sequence = last_seq;
     }
     if (!external_table &&
         mem->ApproximateMemoryUsage() > options_.write_buffer_size) {
       status = WriteLevel0TableForRecovery(mem, edit);
       if (!status.ok()) {
         // Reflect errors immediately so that conditions like full
         // file-systems cause the DB::Open() to fail.
         break;
       }
       mem->Unref();
       mem = nullptr;
     }
   }
   if (status.ok() && mem != nullptr && !external_table) {
     status = WriteLevel0TableForRecovery(mem, edit);
     // Reflect errors immediately so that conditions like full
     // file-systems cause the DB::Open() to fail.
   }
   if (mem != nullptr && !external_table) mem->Unref();
   return status;
 }
void rocksdb::DBImpl::ReFitLevel (int level, int target_level = -1) private
Definition at line 1223 of file db_impl.cc.
References bg_compaction_scheduled_, bg_cv_, bg_flush_scheduled_, bg_work_gate_closed_, ripple::f, FindMinimumEmptyLevelFitting(), rocksdb::Options::info_log, rocksdb::Log(), mutex_, NumberLevels(), options_, refitting_level_, versions_, and rocksdb::port::CondVar::Wait().
Referenced by CompactRange().
{
   assert(level < NumberLevels());
   MutexLock l(&mutex_);
   // only allow one thread refitting
   if (refitting_level_) {
     Log(options_.info_log, "ReFitLevel: another thread is refitting");
     return;
   }
   refitting_level_ = true;
   // wait for all background threads to stop
   bg_work_gate_closed_ = true;
   while (bg_compaction_scheduled_ > 0 || bg_flush_scheduled_) {
     Log(options_.info_log,
         "RefitLevel: waiting for background threads to stop: %d %d",
         bg_compaction_scheduled_, bg_flush_scheduled_);
     bg_cv_.Wait();
   }
   // move to a smaller level
   int to_level = target_level;
   if (target_level < 0) {
     to_level = FindMinimumEmptyLevelFitting(level);
   }
   assert(to_level <= level);
   if (to_level < level) {
     Log(options_.info_log, "Before refitting:\n%s",
         versions_->current()->DebugString().data());
     VersionEdit edit(NumberLevels());
     for (const auto& f : versions_->current()->files_[level]) {
       edit.DeleteFile(level, f->number);
       edit.AddFile(to_level, f->number, f->file_size, f->smallest, f->largest,
                    f->smallest_seqno, f->largest_seqno);
     }
     Log(options_.info_log, "Apply version edit:\n%s",
         edit.DebugString().data());
     auto status = versions_->LogAndApply(&edit, &mutex_);
     Log(options_.info_log, "LogAndApply: %s\n", status.ToString().data());
     if (status.ok()) {
       Log(options_.info_log, "After refitting:\n%s",
           versions_->current()->DebugString().data());
     }
   }
   refitting_level_ = false;
   bg_work_gate_closed_ = false;
 }
void rocksdb::DBImpl::ReleaseCompactionUnusedFileNumbers (CompactionState * compact) private
Definition at line 1900 of file db_impl.cc.
References rocksdb::DBImpl::CompactionState::allocated_file_numbers, rocksdb::port::Mutex::AssertHeld(), mutex_, and pending_outputs_.
Referenced by DoCompactionWork().
{
   mutex_.AssertHeld();
   for (const auto file_number : compact->allocated_file_numbers) {
     pending_outputs_.erase(file_number);
     // Log(options_.info_log, "XXX releasing unused file num %d", file_number);
   }
 }
void rocksdb::DBImpl::ReleaseSnapshot (const Snapshot * snapshot) virtual
Implements rocksdb::DB.
Definition at line 2736 of file db_impl.cc.
References rocksdb::SnapshotList::Delete(), mutex_, and snapshots_.
Referenced by rocksdb::TEST().
{
   MutexLock l(&mutex_);
   snapshots_.Delete(reinterpret_cast<const SnapshotImpl*>(s));
 }
Status rocksdb::DBImpl::RetainProbableWalFiles (VectorLogPtr & all_logs, const SequenceNumber target) private
Definition at line 1330 of file db_impl.cc.
References ripple::max(), and rocksdb::Status::OK().
Referenced by GetUpdatesSince().
{
   long start = 0; // signed to avoid overflow when target is < first file.
   long end = static_cast<long>(all_logs.size()) - 1;
   // Binary Search. avoid opening all files.
   while (end >= start) {
     long mid = start + (end - start) / 2;  // Avoid overflow.
     SequenceNumber current_seq_num = all_logs.at(mid)->StartSequence();
     if (current_seq_num == target) {
       end = mid;
       break;
     } else if (current_seq_num < target) {
       start = mid + 1;
     } else {
       end = mid - 1;
     }
   }
   size_t start_index = std::max(0l, end); // end could be -ve.
   // The last wal file is always included
   all_logs.erase(all_logs.begin(), all_logs.begin() + start_index);
   return Status::OK();
 }
uint64_t rocksdb::DBImpl::SlowdownAmount (int n, int top, int bottom) private
Definition at line 2930 of file db_impl.cc.
Referenced by MakeRoomForWrite().
{
   uint64_t delay;
   if (n >= top) {
     delay = 1000;
   }
   else if (n < bottom) {
     delay = 0;
   }
   else {
     // If we are here, we know that:
     //   level0_start_slowdown <= n < level0_slowdown
     // since the previous two conditions are false.
     float how_much =
       (float) (n - bottom) /
               (top - bottom);
     delay = how_much * how_much * 1000;
   }
   assert(delay <= 1000);
   return delay;
 }
void rocksdb::DBImpl::TEST_CompactRange (int level, const Slice * begin, const Slice * end)
Definition at line 1485 of file db_impl.cc.
References rocksdb::DBImpl::ManualCompaction::begin, bg_compaction_scheduled_, bg_cv_, rocksdb::Options::compaction_style, rocksdb::DBImpl::ManualCompaction::done, rocksdb::DBImpl::ManualCompaction::end, rocksdb::DBImpl::ManualCompaction::in_progress, rocksdb::Options::info_log, rocksdb::kCompactionStyleUniversal, rocksdb::kMaxSequenceNumber, rocksdb::kValueTypeForSeek, rocksdb::DBImpl::ManualCompaction::level, rocksdb::Log(), manual_compaction_, rocksdb::Options::max_background_compactions, MaybeScheduleFlushOrCompaction(), mutex_, options_, and rocksdb::port::CondVar::Wait().
Referenced by CompactRange(), and rocksdb::TEST().
{
   assert(level >= 0);
   InternalKey begin_storage, end_storage;
   ManualCompaction manual;
   manual.level = level;
   manual.done = false;
   manual.in_progress = false;
   // For universal compaction, we enforce every manual compaction to compact
   // all files.
   if (begin == nullptr ||
       options_.compaction_style == kCompactionStyleUniversal) {
     manual.begin = nullptr;
   } else {
     begin_storage = InternalKey(*begin, kMaxSequenceNumber, kValueTypeForSeek);
     manual.begin = &begin_storage;
   }
   if (end == nullptr ||
       options_.compaction_style == kCompactionStyleUniversal) {
     manual.end = nullptr;
   } else {
     end_storage = InternalKey(*end, 0, static_cast<ValueType>(0));
     manual.end = &end_storage;
   }
   MutexLock l(&mutex_);
   // When a manual compaction arrives, temporarily throttle down
   // the number of background compaction threads to 1. This is
   // needed to ensure that this manual compaction can compact
   // any range of keys/files. We artificialy increase
   // bg_compaction_scheduled_ by a large number, this causes
   // the system to have a single background thread. Now,
   // this manual compaction can progress without stomping
   // on any other concurrent compactions.
   const int LargeNumber = 10000000;
   const int newvalue = options_.max_background_compactions-1;
   bg_compaction_scheduled_ += LargeNumber;
   while (bg_compaction_scheduled_ > LargeNumber) {
     Log(options_.info_log, "Manual compaction request waiting for background threads to fall below 1");
     bg_cv_.Wait();
   }
   Log(options_.info_log, "Manual compaction starting");
   while (!manual.done) {
     while (manual_compaction_ != nullptr) {
       bg_cv_.Wait();
     }
     manual_compaction_ = &manual;
     if (bg_compaction_scheduled_ == LargeNumber) {
       bg_compaction_scheduled_ = newvalue;
     }
     MaybeScheduleFlushOrCompaction();
     while (manual_compaction_ == &manual) {
       bg_cv_.Wait();
     }
   }
   assert(!manual.in_progress);
   // wait till there are no background threads scheduled
   bg_compaction_scheduled_ += LargeNumber;
   while (bg_compaction_scheduled_ > LargeNumber + newvalue) {
     Log(options_.info_log, "Manual compaction resetting background threads");
     bg_cv_.Wait();
   }
   bg_compaction_scheduled_ = 0;
 }
uint64_t rocksdb::DBImpl::TEST_Current_Manifest_FileNo ()
Definition at line 359 of file db_impl.cc.
References versions_.
{
   return versions_->ManifestFileNumber();
 }
void rocksdb::DBImpl::TEST_Destroy_DBImpl ()
Definition at line 329 of file db_impl.cc.
References bg_compaction_scheduled_, bg_cv_, bg_flush_scheduled_, bg_logstats_scheduled_, bg_work_gate_closed_, db_lock_, env_, flush_on_destroy_, rocksdb::Options::info_log, rocksdb::port::Mutex::Lock(), log_, rocksdb::LogFlush(), mutex_, options_, table_cache_, rocksdb::port::Mutex::Unlock(), rocksdb::Env::UnlockFile(), versions_, and rocksdb::port::CondVar::Wait().
{
   // ensure that no new memtable flushes can occur
   flush_on_destroy_ = false;
   // wait till all background compactions are done.
   mutex_.Lock();
   while (bg_compaction_scheduled_ ||
          bg_flush_scheduled_ ||
          bg_logstats_scheduled_) {
     bg_cv_.Wait();
   }
   // Prevent new compactions from occuring.
   bg_work_gate_closed_ = true;
   const int LargeNumber = 10000000;
   bg_compaction_scheduled_ += LargeNumber;
   mutex_.Unlock();
   LogFlush(options_.info_log);
   // force release the lock file.
   if (db_lock_ != nullptr) {
     env_->UnlockFile(db_lock_);
   }
   log_.reset();
   versions_.reset();
   table_cache_.reset();
 }
Status rocksdb::DBImpl::TEST_FlushMemTable ()
Definition at line 1577 of file db_impl.cc.
References FlushMemTable().
Referenced by rocksdb::ReduceLevelTest::CompactMemTable(), CompactRange(), rocksdb::DeleteFileTest::CreateTwoLevels(), rocksdb::DBTest::MakeTables(), rocksdb::PrefixScanInit(), and rocksdb::TEST().
{
   return FlushMemTable(FlushOptions());
 }
uint64_t rocksdb::DBImpl::TEST_GetLevel0TotalSize () inline
Definition at line 119 of file db_impl.h.
References versions_.
 { return versions_->NumLevelBytes(0);}
int64_t rocksdb::DBImpl::TEST_MaxNextLevelOverlappingBytes ()
Definition at line 2543 of file db_impl.cc.
References mutex_, and versions_.
{
   MutexLock l(&mutex_);
   return versions_->MaxNextLevelOverlappingBytes();
 }
Iterator * rocksdb::DBImpl::TEST_NewInternalIterator ()
Definition at line 2538 of file db_impl.cc.
References NewInternalIterator().
Referenced by rocksdb::DBTest::AllEntriesFor(), and rocksdb::InternalDumpCommand::DoCommand().
{
   SequenceNumber ignored;
   return NewInternalIterator(ReadOptions(), &ignored);
 }
void rocksdb::DBImpl::TEST_PurgeObsoleteteWAL ()
Definition at line 1690 of file db_impl.cc.
References PurgeObsoleteWALFiles().
{
   PurgeObsoleteWALFiles();
 }
void rocksdb::DBImpl::TEST_SetDefaultTimeToCheck (uint64_t default_interval_to_delete_obsolete_WAL) inline
Definition at line 121 of file db_impl.h.
References default_interval_to_delete_obsolete_WAL_.
   {
     default_interval_to_delete_obsolete_WAL_ = default_interval_to_delete_obsolete_WAL;
   }
Status rocksdb::DBImpl::TEST_WaitForCompact ()
Definition at line 1585 of file db_impl.cc.
References bg_compaction_scheduled_, bg_cv_, bg_error_, bg_flush_scheduled_, mutex_, rocksdb::Status::ok(), and rocksdb::port::CondVar::Wait().
Referenced by rocksdb::TEST().
{
   // Wait until the compaction completes
   // TODO: a bug here. This function actually does not necessarily
   // wait for compact. It actually waits for scheduled compaction
   // OR flush to finish.
   MutexLock l(&mutex_);
   while ((bg_compaction_scheduled_ || bg_flush_scheduled_) &&
          bg_error_.ok()) {
     bg_cv_.Wait();
   }
   return bg_error_;
 }
Status rocksdb::DBImpl::TEST_WaitForFlushMemTable ()
Definition at line 1581 of file db_impl.cc.
References WaitForFlushMemTable().
Referenced by rocksdb::DeleteFileTest::CreateTwoLevels().
{
   return WaitForFlushMemTable();
 }
const Comparator* rocksdb::DBImpl::user_comparator () const inline protected
Definition at line 181 of file db_impl.h.
References internal_comparator_, and rocksdb::InternalKeyComparator::user_comparator().
Referenced by DoCompactionWork(), NewDB(), rocksdb::DBImplReadOnly::NewIterator(), NewIterator(), WriteLevel0Table(), and WriteLevel0TableForRecovery().
{
     return internal_comparator_.user_comparator();
   }
Status rocksdb::DBImpl::WaitForFlushMemTable () private
Definition at line 1564 of file db_impl.cc.
References bg_cv_, bg_error_, imm_, mutex_, rocksdb::Status::ok(), rocksdb::MemTableList::size(), and rocksdb::port::CondVar::Wait().
Referenced by FlushMemTable(), and TEST_WaitForFlushMemTable().
{
   Status s;
   // Wait until the compaction completes
   MutexLock l(&mutex_);
   while (imm_.size() > 0 && bg_error_.ok()) {
     bg_cv_.Wait();
   }
   if (imm_.size() != 0) {
     s = bg_error_;
   }
   return s;
 }
Status rocksdb::DBImpl::Write (const WriteOptions & options, WriteBatch * updates) virtual
Implements rocksdb::DB.
Reimplemented in rocksdb::DBImplReadOnly.
Definition at line 2759 of file db_impl.cc.
References rocksdb::DBImpl::Writer::batch, bg_error_, BuildBatchGroup(), rocksdb::BumpPerfTime(), rocksdb::BYTES_WRITTEN, rocksdb::WriteBatchInternal::ByteSize(), rocksdb::WriteBatch::Clear(), rocksdb::WriteBatchInternal::Contents(), rocksdb::WriteBatchInternal::Count(), rocksdb::DBImpl::Writer::cv, rocksdb::DB_WRITE, rocksdb::DBImpl::Writer::disableWAL, rocksdb::WriteOptions::disableWAL, rocksdb::DBImpl::Writer::done, env_, rocksdb::Options::filter_deletes, flush_on_destroy_, rocksdb::Options::info_log, rocksdb::WriteBatchInternal::InsertInto(), rocksdb::port::Mutex::Lock(), log_, rocksdb::LogFlush(), MakeRoomForWrite(), mem_, mutex_, rocksdb::NUMBER_KEYS_WRITTEN, rocksdb::Status::ok(), options_, rocksdb::Options::paranoid_checks, rocksdb::perf_context, rocksdb::RecordTick(), rocksdb::SEQUENCE_NUMBER, rocksdb::WriteBatchInternal::SetSequence(), rocksdb::SetTickerCount(), rocksdb::port::CondVar::Signal(), rocksdb::StartPerfTimer(), rocksdb::Options::statistics, rocksdb::DBImpl::Writer::status, rocksdb::DBImpl::Writer::sync, rocksdb::WriteOptions::sync, tmp_batch_, rocksdb::port::Mutex::Unlock(), rocksdb::Options::use_fsync, versions_, rocksdb::port::CondVar::Wait(), rocksdb::WAL_FILE_SYNC_MICROS, rocksdb::PerfContext::wal_write_time, and writers_.
Referenced by FlushMemTable(), and rocksdb::TEST().
{
   Writer w(&mutex_);
   w.batch = my_batch;
   w.sync = options.sync;
   w.disableWAL = options.disableWAL;
   w.done = false;
   StopWatch sw(env_, options_.statistics, DB_WRITE);
   MutexLock l(&mutex_);
   writers_.push_back(&w);
   while (!w.done && &w != writers_.front()) {
     w.cv.Wait();
   }
   if (w.done) {
     return w.status;
   }
   // May temporarily unlock and wait.
   Status status = MakeRoomForWrite(my_batch == nullptr);
   uint64_t last_sequence = versions_->LastSequence();
   Writer* last_writer = &w;
   if (status.ok() && my_batch != nullptr) {  // nullptr batch is for compactions
     // TODO: BuildBatchGroup physically concatenate/copy all write batches into
     // a new one. Mem copy is done with the lock held. Ideally, we only need
     // the lock to obtain the last_writer and the references to all batches.
     // Creation (copy) of the merged batch could have been done outside of the
     // lock protected region.
     WriteBatch* updates = BuildBatchGroup(&last_writer);
     // Add to log and apply to memtable.  We can release the lock
     // during this phase since &w is currently responsible for logging
     // and protects against concurrent loggers and concurrent writes
     // into mem_.
     {
       mutex_.Unlock();
       const SequenceNumber current_sequence = last_sequence + 1;
       WriteBatchInternal::SetSequence(updates, current_sequence);
       int my_batch_count = WriteBatchInternal::Count(updates);
       last_sequence += my_batch_count;
       // Record statistics
       RecordTick(options_.statistics, NUMBER_KEYS_WRITTEN, my_batch_count);
       RecordTick(options_.statistics,
                  BYTES_WRITTEN,
                  WriteBatchInternal::ByteSize(updates));
       if (options.disableWAL) {
         flush_on_destroy_ = true;
       }
       if (!options.disableWAL) {
         StopWatchNano timer(env_);
         StartPerfTimer(&timer);
         status = log_->AddRecord(WriteBatchInternal::Contents(updates));
         BumpPerfTime(&perf_context.wal_write_time, &timer);
         if (status.ok() && options.sync) {
           if (options_.use_fsync) {
             StopWatch(env_, options_.statistics, WAL_FILE_SYNC_MICROS);
             status = log_->file()->Fsync();
           } else {
             StopWatch(env_, options_.statistics, WAL_FILE_SYNC_MICROS);
             status = log_->file()->Sync();
           }
         }
       }
       if (status.ok()) {
         status = WriteBatchInternal::InsertInto(updates, mem_, &options_, this,
                                                 options_.filter_deletes);
         if (!status.ok()) {
           // Panic for in-memory corruptions
           // Note that existing logic was not sound. Any partial failure writing
           // into the memtable would result in a state that some write ops might
           // have succeeded in memtable but Status reports error for all writes.
           throw std::runtime_error("In memory WriteBatch corruption!");
         }
         SetTickerCount(options_.statistics, SEQUENCE_NUMBER, last_sequence);
       }
       LogFlush(options_.info_log);
       mutex_.Lock();
       if (status.ok()) {
         versions_->SetLastSequence(last_sequence);
       }
     }
     if (updates == &tmp_batch_) tmp_batch_.Clear();
   }
   if (options_.paranoid_checks && !status.ok() && bg_error_.ok()) {
     bg_error_ = status; // stop compaction & fail any further writes
   }
   while (true) {
     Writer* ready = writers_.front();
     writers_.pop_front();
     if (ready != &w) {
       ready->status = status;
       ready->done = true;
       ready->cv.Signal();
     }
     if (ready == last_writer) break;
   }
   // Notify new head of write queue
   if (!writers_.empty()) {
     writers_.front()->cv.Signal();
   }
   return status;
 }
Status rocksdb::DBImpl::WriteLevel0Table (std::vector< MemTable * > & mems, VersionEdit * edit, uint64_t * filenumber) private
Definition at line 1025 of file db_impl.cc.
References rocksdb::VersionEdit::AddFile(), rocksdb::port::Mutex::AssertHeld(), base, rocksdb::BuildTable(), rocksdb::DBImpl::CompactionStats::bytes_written, rocksdb::Options::compaction_options_universal, rocksdb::Options::compaction_style, rocksdb::CompactionOptionsUniversal::compression_size_percent, dbname_, env_, rocksdb::FileMetaData::file_size, rocksdb::SnapshotList::GetNewest(), rocksdb::Options::info_log, internal_comparator_, rocksdb::kCompactionStyleLevel, rocksdb::kCompactionStyleUniversal, rocksdb::FileMetaData::largest, rocksdb::FileMetaData::largest_seqno, rocksdb::port::Mutex::Lock(), rocksdb::Log(), rocksdb::LogFlush(), rocksdb::Options::max_background_compactions, meta, rocksdb::DBImpl::CompactionStats::micros, mutex_, rocksdb::NewMergingIterator(), rocksdb::Env::NowMicros(), rocksdb::FileMetaData::number, rocksdb::Status::ok(), options_, pending_outputs_, rocksdb::Version::PickLevelForMemTableOutput(), rocksdb::Version::Ref(), rocksdb::FileMetaData::smallest, rocksdb::FileMetaData::smallest_seqno, snapshots_, stats, stats_, storage_options_, table_cache_, rocksdb::Status::ToString(), rocksdb::port::Mutex::Unlock(), rocksdb::Version::Unref(), user_comparator(), rocksdb::InternalKey::user_key(), and versions_.
Referenced by FlushMemTableToOutputFile().
{
   mutex_.AssertHeld();
   const uint64_t start_micros = env_->NowMicros();
   FileMetaData meta;
   meta.number = versions_->NewFileNumber();
   *filenumber = meta.number;
   pending_outputs_.insert(meta.number);
   std::vector<Iterator*> list;
   for (MemTable* m : mems) {
     Log(options_.info_log,
         "Flushing memtable with log file: %lu\n",
         (unsigned long)m->GetLogNumber());
     list.push_back(m->NewIterator());
   }
   Iterator* iter = NewMergingIterator(&internal_comparator_, &list[0],
                                       list.size());
   const SequenceNumber newest_snapshot = snapshots_.GetNewest();
   const SequenceNumber earliest_seqno_in_memtable =
     mems[0]->GetFirstSequenceNumber();
   Log(options_.info_log,
       "Level-0 flush table #%lu: started",
       (unsigned long)meta.number);
   Version* base = versions_->current();
   base->Ref();          // it is likely that we do not need this reference
   Status s;
   {
     mutex_.Unlock();
     // We skip compression if universal compression is used and the size
     // threshold is set for compression.
     bool enable_compression = (options_.compaction_style
         != kCompactionStyleUniversal ||
         options_.compaction_options_universal.compression_size_percent < 0);
     s = BuildTable(dbname_, env_, options_, storage_options_,
                    table_cache_.get(), iter, &meta,
                    user_comparator(), newest_snapshot,
                    earliest_seqno_in_memtable, enable_compression);
     LogFlush(options_.info_log);
     mutex_.Lock();
   }
   base->Unref();
   Log(options_.info_log, "Level-0 flush table #%lu: %lu bytes %s",
       (unsigned long) meta.number,
       (unsigned long) meta.file_size,
       s.ToString().c_str());
   delete iter;
   // re-acquire the most current version
   base = versions_->current();
   // There could be multiple threads writing to its own level-0 file.
   // The pending_outputs cannot be cleared here, otherwise this newly
   // created file might not be considered as a live-file by another
   // compaction thread that is concurrently deleting obselete files.
   // The pending_outputs can be cleared only after the new version is
   // committed so that other threads can recognize this file as a
   // valid one.
   // pending_outputs_.erase(meta.number);
   // Note that if file_size is zero, the file has been deleted and
   // should not be added to the manifest.
   int level = 0;
   if (s.ok() && meta.file_size > 0) {
     const Slice min_user_key = meta.smallest.user_key();
     const Slice max_user_key = meta.largest.user_key();
     // if we have more than 1 background thread, then we cannot
     // insert files directly into higher levels because some other
     // threads could be concurrently producing compacted files for
     // that key range.
     if (base != nullptr && options_.max_background_compactions <= 1 &&
         options_.compaction_style == kCompactionStyleLevel) {
       level = base->PickLevelForMemTableOutput(min_user_key, max_user_key);
     }
     edit->AddFile(level, meta.number, meta.file_size,
                   meta.smallest, meta.largest,
                   meta.smallest_seqno, meta.largest_seqno);
   }
   CompactionStats stats;
   stats.micros = env_->NowMicros() - start_micros;
   stats.bytes_written = meta.file_size;
   stats_[level].Add(stats);
   return s;
 }
Status rocksdb::DBImpl::WriteLevel0TableForRecovery (MemTable * mem, VersionEdit * edit) private
Definition at line 975 of file db_impl.cc.
References rocksdb::VersionEdit::AddFile(), rocksdb::port::Mutex::AssertHeld(), rocksdb::BuildTable(), rocksdb::DBImpl::CompactionStats::bytes_written, dbname_, env_, rocksdb::FileMetaData::file_size, rocksdb::DBImpl::CompactionStats::files_out_levelnp1, rocksdb::MemTable::GetFirstSequenceNumber(), rocksdb::SnapshotList::GetNewest(), rocksdb::Options::info_log, rocksdb::FileMetaData::largest, rocksdb::FileMetaData::largest_seqno, rocksdb::port::Mutex::Lock(), rocksdb::Log(), rocksdb::LogFlush(), meta, rocksdb::DBImpl::CompactionStats::micros, mutex_, rocksdb::MemTable::NewIterator(), rocksdb::Env::NowMicros(), rocksdb::FileMetaData::number, rocksdb::Status::ok(), options_, pending_outputs_, rocksdb::FileMetaData::smallest, rocksdb::FileMetaData::smallest_seqno, snapshots_, stats, stats_, storage_options_, table_cache_, rocksdb::Status::ToString(), rocksdb::port::Mutex::Unlock(), user_comparator(), and versions_.
Referenced by RecoverLogFile().
{
   mutex_.AssertHeld();
   const uint64_t start_micros = env_->NowMicros();
   FileMetaData meta;
   meta.number = versions_->NewFileNumber();
   pending_outputs_.insert(meta.number);
   Iterator* iter = mem->NewIterator();
   const SequenceNumber newest_snapshot = snapshots_.GetNewest();
   const SequenceNumber earliest_seqno_in_memtable =
     mem->GetFirstSequenceNumber();
   Log(options_.info_log, "Level-0 table #%lu: started",
       (unsigned long) meta.number);
   Status s;
   {
     mutex_.Unlock();
     s = BuildTable(dbname_, env_, options_, storage_options_,
                    table_cache_.get(), iter, &meta,
                    user_comparator(), newest_snapshot,
                    earliest_seqno_in_memtable, true);
     LogFlush(options_.info_log);
     mutex_.Lock();
   }
   Log(options_.info_log, "Level-0 table #%lu: %lu bytes %s",
       (unsigned long) meta.number,
       (unsigned long) meta.file_size,
       s.ToString().c_str());
   delete iter;
   pending_outputs_.erase(meta.number);
   // Note that if file_size is zero, the file has been deleted and
   // should not be added to the manifest.
   int level = 0;
   if (s.ok() && meta.file_size > 0) {
     edit->AddFile(level, meta.number, meta.file_size,
                   meta.smallest, meta.largest,
                   meta.smallest_seqno, meta.largest_seqno);
   }
   CompactionStats stats;
   stats.micros = env_->NowMicros() - start_micros;
   stats.bytes_written = meta.file_size;
   stats.files_out_levelnp1 = 1;
   stats_[level].Add(stats);
   return s;
 }
Friends And Related Function Documentation
friend class DB friend
Definition at line 193 of file db_impl.h.
Member Data Documentation
int rocksdb::DBImpl::bg_compaction_scheduled_ private
Definition at line 329 of file db_impl.h.
Referenced by BackgroundCallCompaction(), BackgroundCompaction(), DoCompactionWork(), MaybeScheduleFlushOrCompaction(), ReFitLevel(), TEST_CompactRange(), TEST_Destroy_DBImpl(), TEST_WaitForCompact(), and ~DBImpl().
port::CondVar rocksdb::DBImpl::bg_cv_ private
Definition at line 309 of file db_impl.h.
Referenced by BackgroundCallCompaction(), BackgroundCallFlush(), DoCompactionWork(), LogDBDeployStats(), MakeRoomForWrite(), ReFitLevel(), TEST_CompactRange(), TEST_Destroy_DBImpl(), TEST_WaitForCompact(), WaitForFlushMemTable(), and ~DBImpl().
Status rocksdb::DBImpl::bg_error_ private
Definition at line 349 of file db_impl.h.
Referenced by BackgroundCompaction(), MakeRoomForWrite(), TEST_WaitForCompact(), WaitForFlushMemTable(), and Write().
int rocksdb::DBImpl::bg_flush_scheduled_ private
Definition at line 332 of file db_impl.h.
Referenced by BackgroundCallFlush(), BackgroundFlush(), MaybeScheduleFlushOrCompaction(), ReFitLevel(), TEST_Destroy_DBImpl(), TEST_WaitForCompact(), and ~DBImpl().
bool rocksdb::DBImpl::bg_logstats_scheduled_ private
Definition at line 335 of file db_impl.h.
Referenced by LogDBDeployStats(), MaybeScheduleLogDBDeployStats(), TEST_Destroy_DBImpl(), and ~DBImpl().
bool rocksdb::DBImpl::bg_work_gate_closed_ private
Definition at line 454 of file db_impl.h.
Referenced by MaybeScheduleFlushOrCompaction(), ReFitLevel(), and TEST_Destroy_DBImpl().
std::string rocksdb::DBImpl::db_absolute_path_ private
Definition at line 445 of file db_impl.h.
Referenced by DBImpl(), and LogDBDeployStats().
FileLock* rocksdb::DBImpl::db_lock_ private
Definition at line 304 of file db_impl.h.
Referenced by Recover(), TEST_Destroy_DBImpl(), and ~DBImpl().
const std::string rocksdb::DBImpl::dbname_ protected
Definition at line 176 of file db_impl.h.
Referenced by DBImpl(), FindObsoleteFiles(), NewDB(), rocksdb::DBImplReadOnly::NewIterator(), NewIterator(), OpenCompactionOutputFile(), PurgeObsoleteFiles(), Recover(), WriteLevel0Table(), and WriteLevel0TableForRecovery().
uint64_t rocksdb::DBImpl::default_interval_to_delete_obsolete_WAL_ private
Definition at line 369 of file db_impl.h.
Referenced by PurgeObsoleteWALFiles(), and TEST_SetDefaultTimeToCheck().
int rocksdb::DBImpl::delayed_writes_ private
Definition at line 448 of file db_impl.h.
Referenced by DelayLoggingAndReset(), and MakeRoomForWrite().
uint64_t rocksdb::DBImpl::delete_obsolete_files_last_run_ private
Definition at line 359 of file db_impl.h.
Referenced by FindObsoleteFiles().
bool rocksdb::DBImpl::disable_delete_obsolete_files_ private
Definition at line 356 of file db_impl.h.
Referenced by DisableFileDeletions(), EnableFileDeletions(), FindObsoleteFiles(), and FlushMemTableToOutputFile().
Env* const rocksdb::DBImpl::env_ protected
Definition at line 175 of file db_impl.h.
Referenced by AppendSortedWalsOfType(), BackgroundCallCompaction(), BackgroundCallFlush(), CheckWalFileExistsAndEmpty(), CreateArchivalDirectory(), DBImpl(), DeleteFile(), DoCompactionWork(), FindObsoleteFiles(), FinishCompactionOutputFile(), GetImpl(), GetProperty(), GetSortedWalFiles(), LogDBDeployStats(), MakeRoomForWrite(), MaybeDumpStats(), MaybeScheduleFlushOrCompaction(), MaybeScheduleLogDBDeployStats(), MultiGet(), NewDB(), rocksdb::DBImplReadOnly::NewIterator(), NewIterator(), rocksdb::DB::Open(), OpenCompactionOutputFile(), PurgeObsoleteFiles(), PurgeObsoleteWALFiles(), ReadFirstLine(), Recover(), RecoverLogFile(), TEST_Destroy_DBImpl(), Write(), WriteLevel0Table(), WriteLevel0TableForRecovery(), and ~DBImpl().
bool rocksdb::DBImpl::flush_on_destroy_ private
Definition at line 384 of file db_impl.h.
Referenced by TEST_Destroy_DBImpl(), Write(), and ~DBImpl().
std::string rocksdb::DBImpl::host_name_ private
Definition at line 316 of file db_impl.h.
Referenced by DBImpl(), LogDBDeployStats(), and MaybeScheduleLogDBDeployStats().
MemTableList rocksdb::DBImpl::imm_ private
Definition at line 312 of file db_impl.h.
Referenced by BackgroundCompaction(), BackgroundFlush(), DoCompactionWork(), FlushMemTableToOutputFile(), GetImpl(), GetProperty(), MakeRoomForWrite(), MaybeScheduleFlushOrCompaction(), MultiGet(), NewInternalIterator(), WaitForFlushMemTable(), and ~DBImpl().
const InternalKeyComparator rocksdb::DBImpl::internal_comparator_ protected
Definition at line 178 of file db_impl.h.
Referenced by DBImpl(), MakeRoomForWrite(), NewInternalIterator(), RecoverLogFile(), user_comparator(), and WriteLevel0Table().
const InternalFilterPolicy rocksdb::DBImpl::internal_filter_policy_ private
Definition at line 297 of file db_impl.h.
const int rocksdb::DBImpl::KEEP_LOG_FILE_NUM = 1000 static private
Definition at line 444 of file db_impl.h.
int64_t volatile rocksdb::DBImpl::last_log_ts private
Definition at line 353 of file db_impl.h.
Referenced by DBImpl(), and MaybeScheduleLogDBDeployStats().
StatsSnapshot rocksdb::DBImpl::last_stats_ private
Definition at line 442 of file db_impl.h.
Referenced by GetProperty().
std::atomic<uint64_t> rocksdb::DBImpl::last_stats_dump_time_microsec_ private
Definition at line 365 of file db_impl.h.
Referenced by MaybeDumpStats().
unique_ptr<log::Writer> rocksdb::DBImpl::log_ private
Definition at line 314 of file db_impl.h.
Referenced by MakeRoomForWrite(), rocksdb::DB::Open(), TEST_Destroy_DBImpl(), and Write().
uint64_t rocksdb::DBImpl::logfile_number_ private
Definition at line 313 of file db_impl.h.
Referenced by MakeRoomForWrite(), and rocksdb::DB::Open().
std::unique_ptr<StatsLogger> rocksdb::DBImpl::logger_ private
Definition at line 351 of file db_impl.h.
Referenced by LogDBDeployStats(), and MaybeScheduleLogDBDeployStats().
ManualCompaction* rocksdb::DBImpl::manual_compaction_ private
Definition at line 346 of file db_impl.h.
Referenced by BackgroundCompaction(), MaybeScheduleFlushOrCompaction(), and TEST_CompactRange().
MemTable* rocksdb::DBImpl::mem_ private
Definition at line 311 of file db_impl.h.
Referenced by DBImpl(), GetImpl(), GetMemTable(), MakeRoomForWrite(), MultiGet(), NewInternalIterator(), rocksdb::DB::Open(), Write(), and ~DBImpl().
std::shared_ptr<MemTableRepFactory> rocksdb::DBImpl::mem_rep_factory_ private
Definition at line 310 of file db_impl.h.
Referenced by MakeRoomForWrite(), and RecoverLogFile().
port::Mutex rocksdb::DBImpl::mutex_ private
Definition at line 307 of file db_impl.h.
Referenced by AllocateCompactionOutputFileNumbers(), BackgroundCallCompaction(), BackgroundCallFlush(), BackgroundCompaction(), CleanupCompaction(), CompactRange(), DeleteFile(), DeleteObsoleteFiles(), DisableFileDeletions(), DoCompactionWork(), EnableFileDeletions(), FindMinimumEmptyLevelFitting(), FindObsoleteFiles(), FlushMemTableToOutputFile(), GetApproximateSizes(), GetImpl(), GetLiveFiles(), GetLiveFilesMetaData(), GetProperty(), GetSnapshot(), InstallCompactionResults(), LogDBDeployStats(), MakeRoomForWrite(), MaybeScheduleFlushOrCompaction(), MultiGet(), NewInternalIterator(), rocksdb::DB::Open(), OpenCompactionOutputFile(), Recover(), RecoverLogFile(), ReFitLevel(), ReleaseCompactionUnusedFileNumbers(), ReleaseSnapshot(), TEST_CompactRange(), TEST_Destroy_DBImpl(), TEST_MaxNextLevelOverlappingBytes(), TEST_WaitForCompact(), WaitForFlushMemTable(), Write(), WriteLevel0Table(), WriteLevel0TableForRecovery(), and ~DBImpl().
const Options rocksdb::DBImpl::options_ protected
Definition at line 179 of file db_impl.h.
Referenced by BackgroundCallCompaction(), BackgroundCallFlush(), BackgroundCompaction(), BackgroundFlush(), CheckWalFileExistsAndEmpty(), CompactRange(), CreateArchivalDirectory(), DBImpl(), rocksdb::DBImplReadOnly::DBImplReadOnly(), DelayLoggingAndReset(), DeleteFile(), DisableFileDeletions(), DoCompactionWork(), EnableFileDeletions(), findEarliestVisibleSnapshot(), FindObsoleteFiles(), FinishCompactionOutputFile(), FlushMemTableToOutputFile(), rocksdb::DBImplReadOnly::Get(), GetImpl(), GetLiveFiles(), GetSortedWalFiles(), GetUpdatesSince(), InstallCompactionResults(), Level0StopWriteTrigger(), MakeRoomForWrite(), MaxMemCompactionLevel(), MaybeDumpStats(), MaybeIgnoreError(), MaybeScheduleFlushOrCompaction(), MaybeScheduleLogDBDeployStats(), Merge(), MultiGet(), NewDB(), NewInternalIterator(), rocksdb::DBImplReadOnly::NewIterator(), NewIterator(), NumberLevels(), rocksdb::DB::Open(), OpenCompactionOutputFile(), PrintStatistics(), PurgeObsoleteFiles(), PurgeObsoleteWALFiles(), ReadFirstLine(), ReadFirstRecord(), Recover(), RecoverLogFile(), ReFitLevel(), TEST_CompactRange(), TEST_Destroy_DBImpl(), Write(), WriteLevel0Table(), WriteLevel0TableForRecovery(), and ~DBImpl().
bool rocksdb::DBImpl::owns_info_log_ private
Definition at line 298 of file db_impl.h.
std::set<uint64_t> rocksdb::DBImpl::pending_outputs_ private
Definition at line 326 of file db_impl.h.
Referenced by AllocateCompactionOutputFileNumbers(), CleanupCompaction(), FindObsoleteFiles(), FlushMemTableToOutputFile(), OpenCompactionOutputFile(), ReleaseCompactionUnusedFileNumbers(), WriteLevel0Table(), and WriteLevel0TableForRecovery().
uint64_t rocksdb::DBImpl::purge_wal_files_last_run_ private
Definition at line 362 of file db_impl.h.
Referenced by PurgeObsoleteWALFiles().
bool rocksdb::DBImpl::refitting_level_ private
Definition at line 457 of file db_impl.h.
Referenced by ReFitLevel().
port::AtomicPointer rocksdb::DBImpl::shutting_down_ private
Definition at line 308 of file db_impl.h.
Referenced by BackgroundCallCompaction(), BackgroundCallFlush(), BackgroundCompaction(), DoCompactionWork(), FlushMemTableToOutputFile(), LogDBDeployStats(), MaybeScheduleFlushOrCompaction(), MaybeScheduleLogDBDeployStats(), and ~DBImpl().
SnapshotList rocksdb::DBImpl::snapshots_ private
Definition at line 322 of file db_impl.h.
Referenced by DoCompactionWork(), GetSnapshot(), ReleaseSnapshot(), WriteLevel0Table(), and WriteLevel0TableForRecovery().
uint64_t rocksdb::DBImpl::stall_level0_num_files_ private
Definition at line 374 of file db_impl.h.
Referenced by GetProperty(), and MakeRoomForWrite().
uint64_t rocksdb::DBImpl::stall_level0_num_files_count_ private
Definition at line 378 of file db_impl.h.
Referenced by GetProperty(), and MakeRoomForWrite().
uint64_t rocksdb::DBImpl::stall_level0_slowdown_ private
Definition at line 372 of file db_impl.h.
Referenced by GetProperty(), and MakeRoomForWrite().
uint64_t rocksdb::DBImpl::stall_level0_slowdown_count_ private
Definition at line 376 of file db_impl.h.
Referenced by GetProperty(), and MakeRoomForWrite().
std::vector<uint64_t> rocksdb::DBImpl::stall_leveln_slowdown_ private
Definition at line 375 of file db_impl.h.
Referenced by DBImpl(), GetProperty(), and MakeRoomForWrite().
std::vector<uint64_t> rocksdb::DBImpl::stall_leveln_slowdown_count_ private
Definition at line 379 of file db_impl.h.
Referenced by DBImpl(), GetProperty(), and MakeRoomForWrite().
uint64_t rocksdb::DBImpl::stall_memtable_compaction_ private
Definition at line 373 of file db_impl.h.
Referenced by GetProperty(), and MakeRoomForWrite().
uint64_t rocksdb::DBImpl::stall_memtable_compaction_count_ private
Definition at line 377 of file db_impl.h.
Referenced by GetProperty(), and MakeRoomForWrite().
const uint64_t rocksdb::DBImpl::started_at_ private
Definition at line 382 of file db_impl.h.
Referenced by GetProperty().
std::vector<CompactionStats> rocksdb::DBImpl::stats_ private
Definition at line 429 of file db_impl.h.
Referenced by DoCompactionWork(), GetProperty(), WriteLevel0Table(), and WriteLevel0TableForRecovery().
const EnvOptions rocksdb::DBImpl::storage_options_ private
Definition at line 451 of file db_impl.h.
Referenced by DBImpl(), FinishCompactionOutputFile(), GetUpdatesSince(), MakeRoomForWrite(), NewDB(), NewInternalIterator(), OpenCompactionOutputFile(), ReadFirstLine(), RecoverLogFile(), WriteLevel0Table(), and WriteLevel0TableForRecovery().
unique_ptr<TableCache> rocksdb::DBImpl::table_cache_ private
Definition at line 301 of file db_impl.h.
Referenced by CleanupCompaction(), DBImpl(), FinishCompactionOutputFile(), PurgeObsoleteFiles(), TEST_Destroy_DBImpl(), WriteLevel0Table(), and WriteLevel0TableForRecovery().
WriteBatch rocksdb::DBImpl::tmp_batch_ private
Definition at line 320 of file db_impl.h.
Referenced by BuildBatchGroup(), and Write().
unique_ptr<VersionSet> rocksdb::DBImpl::versions_ protected
Definition at line 177 of file db_impl.h.
Referenced by AllocateCompactionOutputFileNumbers(), BackgroundCompaction(), CompactRange(), DBImpl(), DeleteFile(), DoCompactionWork(), FindMinimumEmptyLevelFitting(), FindObsoleteFiles(), FlushMemTableToOutputFile(), rocksdb::DBImplReadOnly::Get(), GetApproximateSizes(), GetImpl(), GetLatestSequenceNumber(), GetLiveFiles(), GetLiveFilesMetaData(), GetProperty(), GetSnapshot(), GetUpdatesSince(), InstallCompactionResults(), LogDBDeployStats(), MakeRoomForWrite(), MaybeScheduleFlushOrCompaction(), MultiGet(), NewInternalIterator(), rocksdb::DB::Open(), OpenCompactionOutputFile(), Recover(), ReFitLevel(), TEST_Current_Manifest_FileNo(), TEST_Destroy_DBImpl(), TEST_GetLevel0TotalSize(), TEST_MaxNextLevelOverlappingBytes(), Write(), WriteLevel0Table(), and WriteLevel0TableForRecovery().
std::deque<Writer*> rocksdb::DBImpl::writers_ private
Definition at line 319 of file db_impl.h.
Referenced by BuildBatchGroup(), MakeRoomForWrite(), and Write().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/db/db_impl.h
rippled/src/ripple/rocksdb/rocksdb/db/db_filesnapshot.cc
rippled/src/ripple/rocksdb/rocksdb/db/db_impl.cc
rippled/src/ripple/rocksdb/rocksdb/db/db_stats_logger.cc