rippled: ripple::STUInt64 Class Reference
ripple::STUInt64 Class Reference
#include <SerializedTypes.h>
Public Member Functions
STUInt64 (std::uint64_t v=0)
STUInt64 (SField::ref n, std::uint64_t v=0)
SerializedTypeID getSType () const
std::string getText () const
Json::Value getJson (int) const
void add (Serializer &s) const
std::uint64_t getValue () const
void setValue (std::uint64_t v)
operator std::uint64_t () const
virtual bool isEquivalent (const SerializedType &t) const
virtual bool isDefault () const
Public Member Functions inherited from ripple::SerializedType
SerializedType ()
SerializedType (SField::ref n)
virtual ~SerializedType ()
void setFName (SField::ref n)
SField::ref getFName () const
std::string getName () const
std::unique_ptr< SerializedType > clone () const
virtual std::string getFullText () const
void addFieldID (Serializer &s) const
SerializedType & operator= (const SerializedType &t)
bool operator== (const SerializedType &t) const
bool operator!= (const SerializedType &t) const
template<class D >
D & downcast ()
template<class D >
D const & downcast () const
Static Public Member Functions
static std::unique_ptr
< SerializedType > deserialize (SerializerIterator &sit, SField::ref name)
Static Public Member Functions inherited from ripple::SerializedType
static std::unique_ptr
< SerializedType > deserialize (SField::ref name)
Private Member Functions
STUInt64 * duplicate () const
Static Private Member Functions
static STUInt64 * construct (SerializerIterator &, SField::ref name)
Private Attributes
std::uint64_t value
Additional Inherited Members
Protected Attributes inherited from ripple::SerializedType
SField::ptr fName
Detailed Description
Definition at line 398 of file SerializedTypes.h.
Constructor & Destructor Documentation
ripple::STUInt64::STUInt64 (std::uint64_t v = 0) inline
Definition at line 401 of file SerializedTypes.h.
Referenced by construct(), and duplicate().
                                  : value (v)
     {
         ;
     }
ripple::STUInt64::STUInt64 (SField::ref n, std::uint64_t v = 0) inline
Definition at line 405 of file SerializedTypes.h.
                                               : SerializedType (n), value (v)
     {
         ;
     }
Member Function Documentation
void ripple::STUInt64::add (Serializer & s) const inline virtual
Reimplemented from ripple::SerializedType.
Definition at line 420 of file SerializedTypes.h.
References ripple::Serializer::add64(), and value.
     {
         s.add64 (value);
     }
STUInt64 * ripple::STUInt64::construct (SerializerIterator & u, SField::ref name) static private
Definition at line 218 of file SerializedTypes.cpp.
References ripple::SerializerIterator::get64(), and STUInt64().
Referenced by deserialize().
 {
     return new STUInt64 (name, u.get64 ());
 }
static std::unique_ptr<SerializedType> ripple::STUInt64::deserialize (SerializerIterator & sit, SField::ref name) inline static
Definition at line 409 of file SerializedTypes.h.
References construct().
Referenced by ripple::STObject::makeDeserializedObject().
     {
         return std::unique_ptr<SerializedType> (construct (sit, name));
     }
STUInt64* ripple::STUInt64::duplicate () const inline private virtual
Reimplemented from ripple::SerializedType.
Definition at line 447 of file SerializedTypes.h.
References STUInt64().
     {
         return new STUInt64 (*this);
     }
Json::Value ripple::STUInt64::getJson (int) const virtual
Reimplemented from ripple::SerializedType.
Definition at line 228 of file SerializedTypes.cpp.
References ripple::strHex(), and value.
 {
     return strHex (value);
 }
SerializedTypeID ripple::STUInt64::getSType () const inline virtual
Reimplemented from ripple::SerializedType.
Definition at line 414 of file SerializedTypes.h.
     {
         return STI_UINT64;
     }
std::string ripple::STUInt64::getText () const virtual
Reimplemented from ripple::SerializedType.
Definition at line 223 of file SerializedTypes.cpp.
References value.
 {
     return beast::lexicalCastThrow <std::string> (value);
 }
std::uint64_t ripple::STUInt64::getValue () const inline
Definition at line 425 of file SerializedTypes.h.
References value.
Referenced by ripple::STObject::getFieldU64().
     {
         return value;
     }
virtual bool ripple::STUInt64::isDefault () const inline virtual
Reimplemented from ripple::SerializedType.
Definition at line 439 of file SerializedTypes.h.
References value.
     {
         return value == 0;
     }
bool ripple::STUInt64::isEquivalent (const SerializedType & t) const virtual
Reimplemented from ripple::SerializedType.
Definition at line 233 of file SerializedTypes.cpp.
References value.
 {
     const STUInt64* v = dynamic_cast<const STUInt64*> (&t);
     return v && (value == v->value);
 }
ripple::STUInt64::operator std::uint64_t () const inline
Definition at line 434 of file SerializedTypes.h.
References value.
     {
         return value;
     }
void ripple::STUInt64::setValue (std::uint64_t v) inline
Definition at line 429 of file SerializedTypes.h.
References value.
Referenced by ripple::STObject::setFieldU64().
     {
         value = v;
     }
Member Data Documentation
std::uint64_t ripple::STUInt64::value private
Definition at line 445 of file SerializedTypes.h.
Referenced by add(), getJson(), getText(), getValue(), isDefault(), isEquivalent(), operator std::uint64_t(), and setValue().
The documentation for this class was generated from the following files:
rippled/src/ripple_data/protocol/SerializedTypes.h
rippled/src/ripple_data/protocol/SerializedTypes.cpp