rippled: ripple::HTTPClientImp Class Reference
ripple::HTTPClientImp Class Reference
Public Member Functions
HTTPClientImp (boost::asio::io_service &io_service, const unsigned short port, std::size_t responseMax)
void makeGet (const std::string &strPath, boost::asio::streambuf &sb, const std::string &strHost)
void request (bool bSSL, std::deque< std::string > deqSites, std::function< void(boost::asio::streambuf &sb, const std::string &strHost)> build, boost::posix_time::time_duration timeout, std::function< bool(const boost::system::error_code &ecResult, int iStatus, const std::string &strData)> complete)
void get (bool bSSL, std::deque< std::string > deqSites, const std::string &strPath, boost::posix_time::time_duration timeout, std::function< bool(const boost::system::error_code &ecResult, int iStatus, const std::string &strData)> complete)
void httpsNext ()
void handleDeadline (const boost::system::error_code &ecResult)
void handleShutdown (const boost::system::error_code &ecResult)
void handleResolve (const boost::system::error_code &ecResult, boost::asio::ip::tcp::resolver::iterator itrEndpoint)
void handleConnect (const boost::system::error_code &ecResult)
void handleRequest (const boost::system::error_code &ecResult)
void handleWrite (const boost::system::error_code &ecResult, std::size_t bytes_transferred)
void handleHeader (const boost::system::error_code &ecResult, std::size_t bytes_transferred)
void handleData (const boost::system::error_code &ecResult, std::size_t bytes_transferred)
void invokeComplete (const boost::system::error_code &ecResult, int iStatus=0, const std::string &strData="")
Static Public Member Functions
static bool onSMSResponse (const boost::system::error_code &ecResult, int iStatus, const std::string &strData)
Static Public Member Functions inherited from ripple::HTTPClient
static void initializeSSLContext ()
static void get (bool bSSL, boost::asio::io_service &io_service, std::deque< std::string > deqSites, const unsigned short port, const std::string &strPath, std::size_t responseMax, boost::posix_time::time_duration timeout, std::function< bool(const boost::system::error_code &ecResult, int iStatus, const std::string &strData)> complete)
static void get (bool bSSL, boost::asio::io_service &io_service, std::string strSite, const unsigned short port, const std::string &strPath, std::size_t responseMax, boost::posix_time::time_duration timeout, std::function< bool(const boost::system::error_code &ecResult, int iStatus, const std::string &strData)> complete)
static void request (bool bSSL, boost::asio::io_service &io_service, std::string strSite, const unsigned short port, std::function< void(boost::asio::streambuf &sb, const std::string &strHost)> build, std::size_t responseMax, boost::posix_time::time_duration timeout, std::function< bool(const boost::system::error_code &ecResult, int iStatus, const std::string &strData)> complete)
static void sendSMS (boost::asio::io_service &io_service, const std::string &strText)
Private Types
typedef boost::shared_ptr
< HTTPClient > pointer
Private Attributes
bool mSSL
AutoSocket mSocket
boost::asio::ip::tcp::resolver mResolver
boost::shared_ptr
< boost::asio::ip::tcp::resolver::query > mQuery
boost::asio::streambuf mRequest
boost::asio::streambuf mHeader
boost::asio::streambuf mResponse
std::string mBody
const unsigned short mPort
int mResponseMax
int mStatus
std::function< void(boost::asio::streambuf
&sb, const std::string
&strHost)> mBuild
std::function< bool(const
boost::system::error_code
&ecResult, int iStatus, const
std::string &strData)> mComplete
boost::asio::deadline_timer mDeadline
boost::system::error_code mShutdown
std::deque< std::string > mDeqSites
boost::posix_time::time_duration mTimeout
Additional Inherited Members
Public Types inherited from ripple::HTTPClient
enum { maxClientHeaderBytes = 32 * 1024 }
enum { smsTimeoutSeconds = 30 }
Detailed Description
Definition at line 84 of file HTTPClient.cpp.
Member Typedef Documentation
typedef boost::shared_ptr<HTTPClient> ripple::HTTPClientImp::pointer private
Definition at line 497 of file HTTPClient.cpp.
Constructor & Destructor Documentation
ripple::HTTPClientImp::HTTPClientImp (boost::asio::io_service & io_service, const unsigned short port, std::size_t responseMax) inline
Definition at line 90 of file HTTPClient.cpp.
References ripple::getConfig(), mSocket, and AutoSocket::SSLSocket().
         : mSocket (io_service, beast::SharedSingleton <HTTPClientSSLContext>::get()->context())
         , mResolver (io_service)
         , mHeader (maxClientHeaderBytes)
         , mPort (port)
         , mResponseMax (responseMax)
         , mDeadline (io_service)
     {
         if (!getConfig ().SSL_VERIFY)
             mSocket.SSLSocket ().set_verify_mode (boost::asio::ssl::verify_none);
     }
Member Function Documentation
void ripple::HTTPClientImp::get (bool bSSL, std::deque< std::string > deqSites, const std::string & strPath, boost::posix_time::time_duration timeout, std::function< bool(const boost::system::error_code &ecResult, int iStatus, const std::string &strData)> complete) inline
Definition at line 139 of file HTTPClient.cpp.
References BIND_TYPE, makeGet(), mComplete, mTimeout, P_1, P_2, and request().
     {
         mComplete   = complete;
         mTimeout    = timeout;
         request (
             bSSL,
             deqSites,
             BIND_TYPE (&HTTPClientImp::makeGet, shared_from_this (), strPath, P_1, P_2),
             timeout,
             complete);
     }
void ripple::HTTPClientImp::handleConnect (const boost::system::error_code & ecResult) inline
Definition at line 275 of file HTTPClient.cpp.
References AutoSocket::async_handshake(), ripple::getConfig(), handleRequest(), invokeComplete(), ripple::lsTRACE, mDeqSites, mShutdown, mSocket, mSSL, AutoSocket::verify(), and WriteLog.
Referenced by handleResolve().
     {
         if (!mShutdown)
             mShutdown   = ecResult;
         if (mShutdown)
         {
             WriteLog (lsTRACE, HTTPClient) << "Connect error: " << mShutdown.message ();
         }
         if (!mShutdown)
         {
             WriteLog (lsTRACE, HTTPClient) << "Connected.";
             if (getConfig ().SSL_VERIFY)
             {
                 mShutdown   = mSocket.verify (mDeqSites[0]);
                 if (mShutdown)
                 {
                     WriteLog (lsTRACE, HTTPClient) << "set_verify_callback: " << mDeqSites[0] << ": " << mShutdown.message ();
                 }
             }
         }
         if (mShutdown)
         {
             invokeComplete (mShutdown);
         }
         else if (mSSL)
         {
             mSocket.async_handshake (
                 AutoSocket::ssl_socket::client,
                 boost::bind (
                     &HTTPClientImp::handleRequest,
                     shared_from_this (),
                     boost::asio::placeholders::error));
         }
         else
         {
             handleRequest (ecResult);
         }
     }
void ripple::HTTPClientImp::handleData (const boost::system::error_code & ecResult, std::size_t bytes_transferred) inline
Definition at line 426 of file HTTPClient.cpp.
References invokeComplete(), ripple::lsTRACE, mBody, mResponse, mShutdown, mStatus, nothing, and WriteLog.
Referenced by handleHeader().
     {
         if (!mShutdown)
             mShutdown   = ecResult;
         if (mShutdown && mShutdown != boost::asio::error::eof)
         {
             WriteLog (lsTRACE, HTTPClient) << "Read error: " << mShutdown.message ();
             invokeComplete (mShutdown);
         }
         else
         {
             if (mShutdown)
             {
                 WriteLog (lsTRACE, HTTPClient) << "Complete.";
                 nothing ();
             }
             else
             {
                 mResponse.commit (bytes_transferred);
                 std::string strBody ((std::istreambuf_iterator<char> (&mResponse)), std::istreambuf_iterator<char> ());
                 invokeComplete (ecResult, mStatus, mBody + strBody);
             }
         }
     }
void ripple::HTTPClientImp::handleDeadline (const boost::system::error_code & ecResult) inline
Definition at line 201 of file HTTPClient.cpp.
References AutoSocket::async_shutdown(), handleShutdown(), ripple::lsTRACE, mDeqSites, mResolver, mShutdown, mSocket, nothing, and WriteLog.
Referenced by httpsNext().
     {
         if (ecResult == boost::asio::error::operation_aborted)
         {
             // Timer canceled because deadline no longer needed.
             WriteLog (lsTRACE, HTTPClient) << "Deadline cancelled.";
             nothing (); // Aborter is done.
         }
         else if (ecResult)
         {
             WriteLog (lsTRACE, HTTPClient) << "Deadline error: " << mDeqSites[0] << ": " << ecResult.message ();
             // Can't do anything sound.
             abort ();
         }
         else
         {
             WriteLog (lsTRACE, HTTPClient) << "Deadline arrived.";
             // Mark us as shutting down.
             // XXX Use our own error code.
             mShutdown   = boost::system::error_code (boost::system::errc::bad_address, boost::system::system_category ());
             // Cancel any resolving.
             mResolver.cancel ();
             // Stop the transaction.
             mSocket.async_shutdown (boost::bind (
                                         &HTTPClientImp::handleShutdown,
                                         shared_from_this (),
                                         boost::asio::placeholders::error));
         }
     }
void ripple::HTTPClientImp::handleHeader (const boost::system::error_code & ecResult, std::size_t bytes_transferred) inline
Definition at line 370 of file HTTPClient.cpp.
References AutoSocket::async_read(), handleData(), invokeComplete(), ripple::lsTRACE, mBody, mHeader, mResponse, mResponseMax, mSocket, mStatus, and WriteLog.
Referenced by handleWrite().
     {
         std::string     strHeader ((std::istreambuf_iterator<char> (&mHeader)), std::istreambuf_iterator<char> ());
         WriteLog (lsTRACE, HTTPClient) << "Header: \"" << strHeader << "\"";
         static boost::regex reStatus ("\\`HTTP/1\\S+ (\\d{3}) .*\\'");          // HTTP/1.1 200 OK
         static boost::regex reSize ("\\`.*\\r\\nContent-Length:\\s+([0-9]+).*\\'");
         static boost::regex reBody ("\\`.*\\r\\n\\r\\n(.*)\\'");
         boost::smatch   smMatch;
         bool    bMatch  = boost::regex_match (strHeader, smMatch, reStatus);    // Match status code.
         if (!bMatch)
         {
             // XXX Use our own error code.
             WriteLog (lsTRACE, HTTPClient) << "No status code";
             invokeComplete (boost::system::error_code (boost::system::errc::bad_address, boost::system::system_category ()));
             return;
         }
         mStatus = beast::lexicalCastThrow <int> (std::string (smMatch[1]));
         if (boost::regex_match (strHeader, smMatch, reBody)) // we got some body
             mBody = smMatch[1];
         if (boost::regex_match (strHeader, smMatch, reSize))
         {
             int size = beast::lexicalCastThrow <int> (std::string(smMatch[1]));
             if (size < mResponseMax)
                 mResponseMax = size;
         }
         if (mResponseMax == 0)
         {
             // no body wanted or available
             invokeComplete (ecResult, mStatus);
         }
         else if (mBody.size () >= mResponseMax)
         {
             // we got the whole thing
             invokeComplete (ecResult, mStatus, mBody);
         }
         else
         {
             mSocket.async_read (
                 mResponse.prepare (mResponseMax - mBody.size ()),
                 boost::asio::transfer_all (),
                 boost::bind (&HTTPClientImp::handleData,
                              shared_from_this (),
                              boost::asio::placeholders::error,
                              boost::asio::placeholders::bytes_transferred));
         }
     }
void ripple::HTTPClientImp::handleRequest (const boost::system::error_code & ecResult) inline
Definition at line 319 of file HTTPClient.cpp.
References AutoSocket::async_write(), handleWrite(), invokeComplete(), ripple::lsTRACE, mBuild, mDeqSites, mRequest, mShutdown, mSocket, and WriteLog.
Referenced by handleConnect().
     {
         if (!mShutdown)
             mShutdown   = ecResult;
         if (mShutdown)
         {
             WriteLog (lsTRACE, HTTPClient) << "Handshake error:" << mShutdown.message ();
             invokeComplete (mShutdown);
         }
         else
         {
             WriteLog (lsTRACE, HTTPClient) << "Session started.";
             mBuild (mRequest, mDeqSites[0]);
             mSocket.async_write (
                 mRequest,
                 boost::bind (&HTTPClientImp::handleWrite,
                              shared_from_this (),
                              boost::asio::placeholders::error,
                              boost::asio::placeholders::bytes_transferred));
         }
     }
void ripple::HTTPClientImp::handleResolve (const boost::system::error_code & ecResult, boost::asio::ip::tcp::resolver::iterator itrEndpoint) inline
Definition at line 247 of file HTTPClient.cpp.
References handleConnect(), invokeComplete(), AutoSocket::lowest_layer(), ripple::lsTRACE, mDeqSites, mShutdown, mSocket, and WriteLog.
Referenced by httpsNext().
     {
         if (!mShutdown)
             mShutdown   = ecResult;
         if (mShutdown)
         {
             WriteLog (lsTRACE, HTTPClient) << "Resolve error: " << mDeqSites[0] << ": " << mShutdown.message ();
             invokeComplete (mShutdown);
         }
         else
         {
             WriteLog (lsTRACE, HTTPClient) << "Resolve complete.";
             boost::asio::async_connect (
                 mSocket.lowest_layer (),
                 itrEndpoint,
                 boost::bind (
                     &HTTPClientImp::handleConnect,
                     shared_from_this (),
                     boost::asio::placeholders::error));
         }
     }
void ripple::HTTPClientImp::handleShutdown (const boost::system::error_code & ecResult) inline
Definition at line 237 of file HTTPClient.cpp.
References ripple::lsTRACE, mDeqSites, and WriteLog.
Referenced by handleDeadline().
     {
         if (ecResult)
         {
             WriteLog (lsTRACE, HTTPClient) << "Shutdown error: " << mDeqSites[0] << ": " << ecResult.message ();
         }
     }
void ripple::HTTPClientImp::handleWrite (const boost::system::error_code & ecResult, std::size_t bytes_transferred) inline
Definition at line 345 of file HTTPClient.cpp.
References AutoSocket::async_read_until(), handleHeader(), invokeComplete(), ripple::lsTRACE, mHeader, mShutdown, mSocket, and WriteLog.
Referenced by handleRequest().
     {
         if (!mShutdown)
             mShutdown   = ecResult;
         if (mShutdown)
         {
             WriteLog (lsTRACE, HTTPClient) << "Write error: " << mShutdown.message ();
             invokeComplete (mShutdown);
         }
         else
         {
             WriteLog (lsTRACE, HTTPClient) << "Wrote.";
             mSocket.async_read_until (
                 mHeader,
                 "\r\n\r\n",
                 boost::bind (&HTTPClientImp::handleHeader,
                              shared_from_this (),
                              boost::asio::placeholders::error,
                              boost::asio::placeholders::bytes_transferred));
         }
     }
void ripple::HTTPClientImp::httpsNext () inline
Definition at line 161 of file HTTPClient.cpp.
References handleDeadline(), handleResolve(), invokeComplete(), ripple::lsTRACE, mDeadline, mDeqSites, mPort, mQuery, mResolver, mShutdown, mTimeout, and WriteLog.
Referenced by invokeComplete(), and request().
     {
         WriteLog (lsTRACE, HTTPClient) << "Fetch: " << mDeqSites[0];
         boost::shared_ptr <boost::asio::ip::tcp::resolver::query> query (
             new boost::asio::ip::tcp::resolver::query (
                 mDeqSites[0],
                 beast::lexicalCast <std::string> (mPort),
                 boost::asio::ip::resolver_query_base::numeric_service));
         mQuery  = query;
         mDeadline.expires_from_now (mTimeout, mShutdown);
         WriteLog (lsTRACE, HTTPClient) << "expires_from_now: " << mShutdown.message ();
         if (!mShutdown)
         {
             mDeadline.async_wait (
                 boost::bind (
                     &HTTPClientImp::handleDeadline,
                     shared_from_this (),
                     boost::asio::placeholders::error));
         }
         if (!mShutdown)
         {
             WriteLog (lsTRACE, HTTPClient) << "Resolving: " << mDeqSites[0];
             mResolver.async_resolve (*mQuery,
                                      boost::bind (
                                          &HTTPClientImp::handleResolve,
                                          shared_from_this (),
                                          boost::asio::placeholders::error,
                                          boost::asio::placeholders::iterator));
         }
         if (mShutdown)
             invokeComplete (mShutdown);
     }
void ripple::HTTPClientImp::invokeComplete (const boost::system::error_code & ecResult, int iStatus = 0, const std::string & strData = "") inline
Definition at line 455 of file HTTPClient.cpp.
References httpsNext(), ripple::lsDEBUG, ripple::lsTRACE, mComplete, mDeadline, mDeqSites, and WriteLog.
Referenced by handleConnect(), handleData(), handleHeader(), handleRequest(), handleResolve(), handleWrite(), and httpsNext().
     {
         boost::system::error_code ecCancel;
         (void) mDeadline.cancel (ecCancel);
         if (ecCancel)
         {
             WriteLog (lsTRACE, HTTPClient) << "invokeComplete: Deadline cancel error: " << ecCancel.message ();
         }
         WriteLog (lsDEBUG, HTTPClient) << "invokeComplete: Deadline popping: " << mDeqSites.size ();
         if (!mDeqSites.empty ())
         {
             mDeqSites.pop_front ();
         }
         bool    bAgain  = true;
         if (mDeqSites.empty () || !ecResult)
         {
             // ecResult: !0 = had an error, last entry
             //    iStatus: result, if no error
             //  strData: data, if no error
             bAgain  = mComplete && mComplete (ecResult ? ecResult : ecCancel, iStatus, strData);
         }
         if (!mDeqSites.empty () && bAgain)
         {
             httpsNext ();
         }
     }
void ripple::HTTPClientImp::makeGet (const std::string & strPath, boost::asio::streambuf & sb, const std::string & strHost) inline
Definition at line 106 of file HTTPClient.cpp.
Referenced by get().
     {
         std::ostream    osRequest (&sb);
         osRequest <<
                   "GET " << strPath << " HTTP/1.0\r\n"
                   "Host: " << strHost << "\r\n"
                   "Accept: */*\r\n"                       // YYY Do we need this line?
                   "Connection: close\r\n\r\n";
     }
static bool ripple::HTTPClientImp::onSMSResponse (const boost::system::error_code & ecResult, int iStatus, const std::string & strData) inline static
Definition at line 489 of file HTTPClient.cpp.
References ripple::lsINFO, and WriteLog.
Referenced by ripple::HTTPClient::sendSMS().
     {
         WriteLog (lsINFO, HTTPClient) << "SMS: Response:" << iStatus << " :" << strData;
         return true;
     }
void ripple::HTTPClientImp::request (bool bSSL, std::deque< std::string > deqSites, std::function< void(boost::asio::streambuf &sb, const std::string &strHost)> build, boost::posix_time::time_duration timeout, std::function< bool(const boost::system::error_code &ecResult, int iStatus, const std::string &strData)> complete) inline
Definition at line 120 of file HTTPClient.cpp.
References httpsNext(), mBuild, mComplete, mDeqSites, mSSL, and mTimeout.
Referenced by get().
     {
         mSSL        = bSSL;
         mDeqSites   = deqSites;
         mBuild      = build;
         mComplete   = complete;
         mTimeout    = timeout;
         httpsNext ();
     }
Member Data Documentation
std::string ripple::HTTPClientImp::mBody private
Definition at line 506 of file HTTPClient.cpp.
Referenced by handleData(), and handleHeader().
std::function<void (boost::asio::streambuf& sb, const std::string& strHost)> ripple::HTTPClientImp::mBuild private
Definition at line 510 of file HTTPClient.cpp.
Referenced by handleRequest(), and request().
std::function<bool (const boost::system::error_code& ecResult, int iStatus, const std::string& strData)> ripple::HTTPClientImp::mComplete private
Definition at line 511 of file HTTPClient.cpp.
Referenced by get(), invokeComplete(), and request().
boost::asio::deadline_timer ripple::HTTPClientImp::mDeadline private
Definition at line 513 of file HTTPClient.cpp.
Referenced by httpsNext(), and invokeComplete().
std::deque<std::string> ripple::HTTPClientImp::mDeqSites private
Definition at line 518 of file HTTPClient.cpp.
Referenced by handleConnect(), handleDeadline(), handleRequest(), handleResolve(), handleShutdown(), httpsNext(), invokeComplete(), and request().
boost::asio::streambuf ripple::HTTPClientImp::mHeader private
Definition at line 504 of file HTTPClient.cpp.
Referenced by handleHeader(), and handleWrite().
const unsigned short ripple::HTTPClientImp::mPort private
Definition at line 507 of file HTTPClient.cpp.
Referenced by httpsNext().
boost::shared_ptr<boost::asio::ip::tcp::resolver::query> ripple::HTTPClientImp::mQuery private
Definition at line 502 of file HTTPClient.cpp.
Referenced by httpsNext().
boost::asio::streambuf ripple::HTTPClientImp::mRequest private
Definition at line 503 of file HTTPClient.cpp.
Referenced by handleRequest().
boost::asio::ip::tcp::resolver ripple::HTTPClientImp::mResolver private
Definition at line 501 of file HTTPClient.cpp.
Referenced by handleDeadline(), and httpsNext().
boost::asio::streambuf ripple::HTTPClientImp::mResponse private
Definition at line 505 of file HTTPClient.cpp.
Referenced by handleData(), and handleHeader().
int ripple::HTTPClientImp::mResponseMax private
Definition at line 508 of file HTTPClient.cpp.
Referenced by handleHeader().
boost::system::error_code ripple::HTTPClientImp::mShutdown private
Definition at line 516 of file HTTPClient.cpp.
Referenced by handleConnect(), handleData(), handleDeadline(), handleRequest(), handleResolve(), handleWrite(), and httpsNext().
AutoSocket ripple::HTTPClientImp::mSocket private
Definition at line 500 of file HTTPClient.cpp.
Referenced by handleConnect(), handleDeadline(), handleHeader(), handleRequest(), handleResolve(), handleWrite(), and HTTPClientImp().
bool ripple::HTTPClientImp::mSSL private
Definition at line 499 of file HTTPClient.cpp.
Referenced by handleConnect(), and request().
int ripple::HTTPClientImp::mStatus private
Definition at line 509 of file HTTPClient.cpp.
Referenced by handleData(), and handleHeader().
boost::posix_time::time_duration ripple::HTTPClientImp::mTimeout private
Definition at line 519 of file HTTPClient.cpp.
Referenced by get(), httpsNext(), and request().
The documentation for this class was generated from the following file:
rippled/src/ripple_net/basics/HTTPClient.cpp