rippled: beast::asio::HTTPClientType Class Reference
beast::asio::HTTPClientType Class Reference
Classes
class Session
struct State
Public Types
typedef SharedData< State > SharedState
Public Types inherited from beast::asio::HTTPClientBase
typedef boost::system::error_code error_type
typedef SharedPtr< HTTPResponse > value_type
typedef std::pair< error_type,
value_type > result_type
Public Member Functions
HTTPClientType (Journal journal, double timeoutSeconds, std::size_t messageLimitBytes, std::size_t bufferSize)
~HTTPClientType ()
result_type get (URL const &url)
void async_get (boost::asio::io_service &io_service, URL const &url, asio::shared_handler< void(result_type)> handler)
void cancel ()
void wait ()
void add (Session &session)
void remove (Session &session)
Journal journal () const
boost::asio::io_service & get_io_service ()
Public Member Functions inherited from beast::asio::HTTPClientBase
virtual ~HTTPClientBase ()
Static Public Member Functions
static void handle_get (result_type const &result, result_type *dest)
static boost::asio::const_buffers_1 stringBuffer (String const &s)
template<typename Query >
static Query queryFromURL (URL const &url)
Static Public Member Functions inherited from beast::asio::HTTPClientBase
static HTTPClientBase * New (Journal journal=Journal(), double timeoutSeconds=30, std::size_t messageLimitBytes=256 *1024, std::size_t bufferSize=16 *1024)
Public Attributes
SharedState m_state
Journal m_journal
double m_timeoutSeconds
std::size_t m_messageLimitBytes
std::size_t m_bufferSize
boost::asio::io_service m_io_service
WaitableEvent m_stopped
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
Definition at line 29 of file HTTPClientType.cpp.
Member Typedef Documentation
typedef SharedData<State> beast::asio::HTTPClientType::SharedState
Definition at line 39 of file HTTPClientType.cpp.
Constructor & Destructor Documentation
beast::asio::HTTPClientType::HTTPClientType (Journal journal, double timeoutSeconds, std::size_t messageLimitBytes, std::size_t bufferSize) inline
Definition at line 51 of file HTTPClientType.cpp.
         : m_journal (journal)
         , m_timeoutSeconds (timeoutSeconds)
         , m_messageLimitBytes (messageLimitBytes)
         , m_bufferSize (bufferSize)
         , m_stopped (true, true) // manual reset, initially signaled
     {
     }
beast::asio::HTTPClientType::~HTTPClientType () inline
Definition at line 64 of file HTTPClientType.cpp.
References cancel(), and wait().
     {
         cancel();
         wait();
     }
Member Function Documentation
void beast::asio::HTTPClientType::add (Session & session) inline
Definition at line 102 of file HTTPClientType.cpp.
References m_state, m_stopped, and beast::WaitableEvent::reset().
Referenced by beast::asio::HTTPClientType::Session::Session().
     {
         SharedState::Access state (m_state);
         if (state->list.empty())
             m_stopped.reset();
         state->list.push_back (session);
     }
void beast::asio::HTTPClientType::async_get (boost::asio::io_service & io_service, URL const & url, asio::shared_handler< void(result_type)> handler) inline virtual
Perform an asynchronous get on the specified URL. Handler will be called with this signature: void (result_type)
Implements beast::asio::HTTPClientBase.
Definition at line 80 of file HTTPClientType.cpp.
References m_bufferSize, m_messageLimitBytes, and m_timeoutSeconds.
Referenced by get().
     {
         new Session (*this, io_service, url,
             handler, m_timeoutSeconds, m_messageLimitBytes, m_bufferSize);
     }
void beast::asio::HTTPClientType::cancel () inline virtual
Cancel all pending asynchronous operations.
Implements beast::asio::HTTPClientBase.
Definition at line 87 of file HTTPClientType.cpp.
References m_state.
Referenced by ~HTTPClientType().
     {
         SharedState::Access state (m_state);
         for (List <Session>::iterator iter (state->list.begin());
             iter != state->list.end(); ++iter)
             iter->cancel();
     }
result_type beast::asio::HTTPClientType::get (URL const & url) inline virtual
Implements beast::asio::HTTPClientBase.
Definition at line 70 of file HTTPClientType.cpp.
References async_get(), and handle_get().
     {
         result_type result;
         boost::asio::io_service io_service;
         async_get (io_service, url, beast::bind (
             &HTTPClientType::handle_get, beast::placeholders::_1, &result));
         io_service.run ();
         return result;
     }
boost::asio::io_service& beast::asio::HTTPClientType::get_io_service () inline
Definition at line 128 of file HTTPClientType.cpp.
References m_io_service.
     {
         return m_io_service;
     }
static void beast::asio::HTTPClientType::handle_get (result_type const & result, result_type * dest) inline static
Definition at line 118 of file HTTPClientType.cpp.
Referenced by get().
     {
         *dest = result;
     }
Journal beast::asio::HTTPClientType::journal () const inline
Definition at line 123 of file HTTPClientType.cpp.
References m_journal.
     {
         return m_journal;
     }
template<typename Query > static Query beast::asio::HTTPClientType::queryFromURL (URL const & url) inline static
Helper function to fill out a Query from a URL.
Definition at line 143 of file HTTPClientType.cpp.
References beast::URL::host(), beast::URL::port(), beast::URL::port_string(), beast::URL::scheme(), and beast::String::toStdString().
     {
         if (url.port () != 0)
         {
             return Query (
                 url.host().toStdString(),
                 url.port_string().toStdString(),
                 Query::numeric_service);
         }
         return Query (
             url.host().toStdString(),
             url.scheme().toStdString());
     }
void beast::asio::HTTPClientType::remove (Session & session) inline
Definition at line 110 of file HTTPClientType.cpp.
References m_state, m_stopped, and beast::WaitableEvent::signal().
Referenced by beast::asio::HTTPClientType::Session::~Session().
     {
         SharedState::Access state (m_state);
         state->list.erase (state->list.iterator_to (session));
         if (state->list.empty())
             m_stopped.signal();
     }
static boost::asio::const_buffers_1 beast::asio::HTTPClientType::stringBuffer (String const & s) inline static
Helper function to get a const_buffer from a String.
Definition at line 136 of file HTTPClientType.cpp.
References beast::String::getCharPointer(), and beast::String::length().
Referenced by beast::asio::HTTPClientType::Session::handle_handshake().
     {
         return boost::asio::const_buffers_1 (s.getCharPointer (), s.length ());
     }
void beast::asio::HTTPClientType::wait () inline virtual
Block until all asynchronous i/o completes.
Implements beast::asio::HTTPClientBase.
Definition at line 95 of file HTTPClientType.cpp.
References m_stopped, and beast::WaitableEvent::wait().
Referenced by ~HTTPClientType().
     {
         m_stopped.wait();
     }
Member Data Documentation
std::size_t beast::asio::HTTPClientType::m_bufferSize
Definition at line 45 of file HTTPClientType.cpp.
Referenced by async_get().
boost::asio::io_service beast::asio::HTTPClientType::m_io_service
Definition at line 46 of file HTTPClientType.cpp.
Referenced by get_io_service().
Journal beast::asio::HTTPClientType::m_journal
Definition at line 42 of file HTTPClientType.cpp.
Referenced by journal().
std::size_t beast::asio::HTTPClientType::m_messageLimitBytes
Definition at line 44 of file HTTPClientType.cpp.
Referenced by async_get().
SharedState beast::asio::HTTPClientType::m_state
Definition at line 41 of file HTTPClientType.cpp.
Referenced by add(), cancel(), and remove().
WaitableEvent beast::asio::HTTPClientType::m_stopped
Definition at line 47 of file HTTPClientType.cpp.
Referenced by add(), remove(), and wait().
double beast::asio::HTTPClientType::m_timeoutSeconds
Definition at line 43 of file HTTPClientType.cpp.
Referenced by async_get().
The documentation for this class was generated from the following file:
rippled/src/beast/modules/beast_asio/http/HTTPClientType.cpp