rippled: ldb_test Namespace Reference
ldb_test Namespace Reference
Classes
class LDBTestCase
Functions
def my_check_output
def run_err_null
Function Documentation
def ldb_test.my_check_output (popenargs, kwargs)
If we had python 2.7, we should simply use subprocess.check_output.
This is a stop-gap solution for python 2.6
Definition at line 9 of file ldb_test.py.
Referenced by ldb_test.LDBTestCase.assertRunFAILFull(), and ldb_test.LDBTestCase.assertRunOKFull().
 def my_check_output(*popenargs, **kwargs):
     """
     If we had python 2.7, we should simply use subprocess.check_output.
     This is a stop-gap solution for python 2.6
     """
     if 'stdout' in kwargs:
         raise ValueError('stdout argument not allowed, it will be overridden.')
     process = subprocess.Popen(stderr=subprocess.PIPE, stdout=subprocess.PIPE,
                                *popenargs, **kwargs)
     output, unused_err = process.communicate()
     retcode = process.poll()
     if retcode:
         cmd = kwargs.get("args")
         if cmd is None:
             cmd = popenargs[0]
         raise Exception("Exit code is not 0.  It is %d.  Command: %s" %
                 (retcode, cmd))
     return output
def ldb_test.run_err_null (cmd)
Definition at line 28 of file ldb_test.py.
Referenced by ldb_test.LDBTestCase.dumpDb(), ldb_test.LDBTestCase.loadDb(), and ldb_test.LDBTestCase.testMiscAdminTask().
 def run_err_null(cmd):
     return os.system(cmd + " 2>/dev/null ")