rippled: ripple::OrderBookIterator Class Reference
ripple::OrderBookIterator Class Reference
#include <OrderBookIterator.h>
Public Member Functions
OrderBookIterator (LedgerEntrySet &set, uint160 const &uInCurrency, uint160 const &uInIssuer, uint160 const &uOutCurrency, uint160 const &uOutIssuer)
OrderBookIterator & operator= (OrderBookIterator const &)=default
bool addJson (Json::Value &) const
bool setJson (Json::Value const &)
STAmount getCurrentRate () const
std::uint64_t getCurrentQuality () const
uint256 getCurrentIndex () const
uint256 getCurrentDirectory () const
SLE::pointer getCurrentOffer ()
bool firstOffer ()
bool nextOffer ()
bool nextDir ()
bool firstOfferInDir ()
bool nextOfferInDir ()
bool rewind ()
LedgerEntrySet & peekEntrySet ()
BookDirIterator const & peekDirIterator () const
DirectoryEntryIterator const & peekDirectoryEntryIterator () const
BookDirIterator & peekDirIterator ()
DirectoryEntryIterator & peekDirectoryEntryIterator ()
bool operator== (OrderBookIterator const &other) const
bool operator!= (OrderBookIterator const &other) const
Private Attributes
std::reference_wrapper
< LedgerEntrySet > mEntrySet
BookDirIterator mDirectoryIterator
DirectoryEntryIterator mOfferIterator
Detailed Description
An iterator that walks the offers in a book CAUTION: The LedgerEntrySet must remain valid for the life of the iterator
Definition at line 128 of file OrderBookIterator.h.
Constructor & Destructor Documentation
ripple::OrderBookIterator::OrderBookIterator (LedgerEntrySet & set, uint160 const & uInCurrency, uint160 const & uInIssuer, uint160 const & uOutCurrency, uint160 const & uOutIssuer) inline
Definition at line 131 of file OrderBookIterator.h.
                                    :
             mEntrySet (set),
             mDirectoryIterator (uInCurrency, uInIssuer, uOutCurrency, uOutIssuer)
     {
     }
Member Function Documentation
bool ripple::OrderBookIterator::addJson (Json::Value & jv) const
Definition at line 114 of file OrderBookIterator.cpp.
References ripple::DirectoryEntryIterator::addJson(), ripple::BookDirIterator::addJson(), mDirectoryIterator, and mOfferIterator.
 {
     return mOfferIterator.addJson(jv) && mDirectoryIterator.addJson(jv);
 }
bool ripple::OrderBookIterator::firstOffer ()
Position the iterator at the first offer in the first directory. Returns whether there is an offer to point to.
Go to the first offer in the first directory
Definition at line 153 of file OrderBookIterator.cpp.
References ripple::BookDirIterator::firstDirectory(), ripple::BookDirIterator::getOfferIterator(), ripple::lsTRACE, mDirectoryIterator, mEntrySet, mOfferIterator, nextOffer(), and WriteLog.
 {
     WriteLog (lsTRACE, Ledger) << "OrderBookIterator: first offer";
     // Go to first directory in order book
     if (!mDirectoryIterator.firstDirectory (mEntrySet))
     {
         WriteLog (lsTRACE, Ledger) << "OrderBookIterator: no first directory";
         return false;
     }
     mOfferIterator = mDirectoryIterator.getOfferIterator ();
     // Take the next offer
     return nextOffer();
 }
bool ripple::OrderBookIterator::firstOfferInDir ()
Position the iterator at the first offer in the current directory. Returns whether there is an offer in the directory.
uint256 ripple::OrderBookIterator::getCurrentDirectory () const
Definition at line 134 of file OrderBookIterator.cpp.
References ripple::DirectoryEntryIterator::getDirectory(), and mOfferIterator.
 {
     return mOfferIterator.getDirectory ();
 }
uint256 ripple::OrderBookIterator::getCurrentIndex () const
Definition at line 139 of file OrderBookIterator.cpp.
References ripple::DirectoryEntryIterator::getEntryLedgerIndex(), and mOfferIterator.
 {
     return mOfferIterator.getEntryLedgerIndex();
 }
SLE::pointer ripple::OrderBookIterator::getCurrentOffer ()
Retrieve the offer the iterator points to
Definition at line 146 of file OrderBookIterator.cpp.
References ripple::DirectoryEntryIterator::getEntry(), ripple::ltOFFER, mEntrySet, and mOfferIterator.
 {
     return mOfferIterator.getEntry (mEntrySet, ltOFFER);
 }
std::uint64_t ripple::OrderBookIterator::getCurrentQuality () const
Definition at line 129 of file OrderBookIterator.cpp.
References ripple::BookDirIterator::getCurrentQuality(), and mDirectoryIterator.
 {
     return mDirectoryIterator.getCurrentQuality();
 }
STAmount ripple::OrderBookIterator::getCurrentRate () const
Definition at line 124 of file OrderBookIterator.cpp.
References ripple::BookDirIterator::getCurrentRate(), and mDirectoryIterator.
 {
     return mDirectoryIterator.getCurrentRate();
 }
bool ripple::OrderBookIterator::nextDir ()
Position the iterator at the first offer in the next directory. Returns whether there is a next directory to point to.
Go to before the first offer in the next directory
Definition at line 210 of file OrderBookIterator.cpp.
References ripple::BookDirIterator::getOfferIterator(), mDirectoryIterator, mEntrySet, mOfferIterator, and ripple::BookDirIterator::nextDirectory().
 {
     if (!mDirectoryIterator.nextDirectory (mEntrySet))
         return false;
     mOfferIterator = mDirectoryIterator.getOfferIterator ();
     return true;
 }
bool ripple::OrderBookIterator::nextOffer ()
Position the iterator at the next offer, going to the next directory if needed Returns whether there is a next offer.
Go to the next offer, possibly changing directories
Definition at line 170 of file OrderBookIterator.cpp.
References ripple::BookDirIterator::getOfferIterator(), ripple::lsTRACE, mDirectoryIterator, mEntrySet, mOfferIterator, ripple::BookDirIterator::nextDirectory(), ripple::DirectoryEntryIterator::nextEntry(), and WriteLog.
Referenced by firstOffer(), and rewind().
 {
     WriteLog (lsTRACE, Ledger) << "OrderBookIterator: next offer";
     do
     {
          // Is there a next offer in the current directory
          if (mOfferIterator.nextEntry (mEntrySet))
          {
              WriteLog (lsTRACE, Ledger) << "OrderBookIterator: there is a next offer in this directory";
              return true;
          }
          // Is there a next directory
          if (!mDirectoryIterator.nextDirectory (mEntrySet))
          {
              WriteLog (lsTRACE, Ledger) << "OrderBookIterator: there is no next directory";
              return false;
          }
          WriteLog (lsTRACE, Ledger) << "OrderBookIterator: going to next directory";
          // Set to before its first offer
          mOfferIterator = mDirectoryIterator.getOfferIterator ();
      }
      while (1);
 }
bool ripple::OrderBookIterator::nextOfferInDir ()
Position the iterator at the next offer in the current directory. Returns whether there is a next offer in the directory.
Advance to the next offer in this directory
Definition at line 222 of file OrderBookIterator.cpp.
References mEntrySet, mOfferIterator, and ripple::DirectoryEntryIterator::nextEntry().
 {
     return mOfferIterator.nextEntry (mEntrySet);
 }
bool ripple::OrderBookIterator::operator!= (OrderBookIterator const & other) const inline
Definition at line 225 of file OrderBookIterator.h.
     {
         return ! (*this == other);
     }
OrderBookIterator& ripple::OrderBookIterator::operator= (OrderBookIterator const &) default
bool ripple::OrderBookIterator::operator== (OrderBookIterator const & other) const inline
Definition at line 216 of file OrderBookIterator.h.
References mDirectoryIterator, mEntrySet, and mOfferIterator.
     {
         return
             std::addressof(mEntrySet) == std::addressof(other.mEntrySet) &&
             mDirectoryIterator == other.mDirectoryIterator &&
             mOfferIterator == mOfferIterator;
     }
DirectoryEntryIterator const& ripple::OrderBookIterator::peekDirectoryEntryIterator () const inline
Definition at line 200 of file OrderBookIterator.h.
References mOfferIterator.
     {
         return mOfferIterator;
     }
DirectoryEntryIterator& ripple::OrderBookIterator::peekDirectoryEntryIterator () inline
Definition at line 210 of file OrderBookIterator.h.
References mOfferIterator.
     {
         return mOfferIterator;
     }
BookDirIterator const& ripple::OrderBookIterator::peekDirIterator () const inline
Definition at line 195 of file OrderBookIterator.h.
References mDirectoryIterator.
     {
         return mDirectoryIterator;
     }
BookDirIterator& ripple::OrderBookIterator::peekDirIterator () inline
Definition at line 205 of file OrderBookIterator.h.
References mDirectoryIterator.
     {
         return mDirectoryIterator;
     }
LedgerEntrySet& ripple::OrderBookIterator::peekEntrySet () inline
Definition at line 190 of file OrderBookIterator.h.
References mEntrySet.
     {
         return mEntrySet;
     }
bool ripple::OrderBookIterator::rewind ()
Position the iterator at the first offer at the current quality. If none, position the iterator at the first offer at the next quality. This rather odd semantic is required by the payment engine.
Rewind to the beginning of this directory, then take the next offer
Definition at line 199 of file OrderBookIterator.cpp.
References ripple::BookDirIterator::getOfferIterator(), mDirectoryIterator, mEntrySet, mOfferIterator, nextOffer(), and ripple::BookDirIterator::resync().
 {
     if (!mDirectoryIterator.resync (mEntrySet))
         return false;
     mOfferIterator = mDirectoryIterator.getOfferIterator ();
     return nextOffer ();
 }
bool ripple::OrderBookIterator::setJson (Json::Value const & jv)
Definition at line 119 of file OrderBookIterator.cpp.
References mDirectoryIterator, mEntrySet, mOfferIterator, ripple::DirectoryEntryIterator::setJson(), and ripple::BookDirIterator::setJson().
 {
     return mDirectoryIterator.setJson (jv) && mOfferIterator.setJson (jv, mEntrySet);
 }
Member Data Documentation
BookDirIterator ripple::OrderBookIterator::mDirectoryIterator private
Definition at line 232 of file OrderBookIterator.h.
Referenced by addJson(), firstOffer(), getCurrentQuality(), getCurrentRate(), nextDir(), nextOffer(), operator==(), peekDirIterator(), rewind(), and setJson().
std::reference_wrapper<LedgerEntrySet> ripple::OrderBookIterator::mEntrySet private
Definition at line 231 of file OrderBookIterator.h.
Referenced by firstOffer(), getCurrentOffer(), nextDir(), nextOffer(), nextOfferInDir(), operator==(), peekEntrySet(), rewind(), and setJson().
DirectoryEntryIterator ripple::OrderBookIterator::mOfferIterator private
Definition at line 233 of file OrderBookIterator.h.
Referenced by addJson(), firstOffer(), getCurrentDirectory(), getCurrentIndex(), getCurrentOffer(), nextDir(), nextOffer(), nextOfferInDir(), operator==(), peekDirectoryEntryIterator(), rewind(), and setJson().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/ledger/OrderBookIterator.h
rippled/src/ripple_app/ledger/OrderBookIterator.cpp