rippled: ripple::JobQueueImp Class Reference
ripple::JobQueueImp Class Reference
Public Types
typedef std::set< Job > JobSet
typedef std::map< JobType,
JobTypeData > JobDataMap
typedef
beast::CriticalSection::ScopedLockType ScopedLock
Public Member Functions
JobQueueImp (beast::insight::Collector::ptr const &collector, Stoppable &parent, beast::Journal journal)
~JobQueueImp ()
void collect ()
void addJob (JobType type, std::string const &name, boost::function< void(Job &)> const &jobFunc)
int getJobCount (JobType t)
int getJobCountTotal (JobType t)
int getJobCountGE (JobType t)
void shutdown ()
void setThreadCount (int c, bool const standaloneMode)
LoadEvent::pointer getLoadEvent (JobType t, const std::string &name)
LoadEvent::autoptr getLoadEventAP (JobType t, const std::string &name)
bool isOverloaded ()
Json::Value getJson (int)
Public Member Functions inherited from ripple::JobQueue
virtual ~JobQueue ()
Public Member Functions inherited from beast::Stoppable
Stoppable (char const *name, Stoppable &parent)
virtual ~Stoppable ()
bool isStopping () const
bool isStopped () const
bool areChildrenStopped () const
void stopped ()
virtual void onPrepare ()
virtual void onStart ()
Static Public Member Functions
static JobTypes const & getJobTypes ()
Public Attributes
beast::Journal m_journal
beast::CriticalSection m_mutex
std::uint64_t m_lastJob
JobSet m_jobSet
JobDataMap m_jobData
JobTypeData m_invalidJobData
int m_processCount
beast::Workers m_workers
CancelCallback m_cancelCallback
beast::insight::Collector::ptr m_collector
beast::insight::Gauge job_count
beast::insight::Hook hook
Private Member Functions
JobTypeData & getJobTypeData (JobType type)
void checkStopped (ScopedLock const &lock)
void queueJob (Job const &job, ScopedLock const &lock)
void getNextJob (Job &job, ScopedLock const &lock)
void finishJob (Job const &job, ScopedLock const &lock)
template<class Rep , class Period >
void on_dequeue (JobType type, std::chrono::duration< Rep, Period > const &value)
template<class Rep , class Period >
void on_execute (JobType type, std::chrono::duration< Rep, Period > const &value)
void processTask ()
bool skipOnStop (JobType type)
int getJobLimit (JobType type)
void onStop ()
void onChildrenStopped ()
Additional Inherited Members
Protected Member Functions inherited from ripple::JobQueue
JobQueue (char const *name, Stoppable &parent)
Protected Attributes inherited from beast::Stoppable
char const * m_name
RootStoppable & m_root
Child m_child
Atomic< int > m_started
bool volatile m_stopped
bool volatile m_childrenStopped
Children m_children
WaitableEvent m_stoppedEvent
Detailed Description
Definition at line 34 of file JobQueue.cpp.
Member Typedef Documentation
typedef std::map<JobType, JobTypeData> ripple::JobQueueImp::JobDataMap
Definition at line 40 of file JobQueue.cpp.
typedef std::set<Job> ripple::JobQueueImp::JobSet
Definition at line 39 of file JobQueue.cpp.
typedef beast::CriticalSection::ScopedLockType ripple::JobQueueImp::ScopedLock
Definition at line 41 of file JobQueue.cpp.
Constructor & Destructor Documentation
ripple::JobQueueImp::JobQueueImp (beast::insight::Collector::ptr const & collector, Stoppable & parent, beast::Journal journal) inline
Definition at line 70 of file JobQueue.cpp.
References collect(), getJobTypes(), hook, job_count, m_collector, m_jobData, m_mutex, and ripple::JobTypeInfo::type().
         : JobQueue ("JobQueue", parent)
         , m_journal (journal)
         , m_lastJob (0)
         , m_invalidJobData (getJobTypes ().getInvalid (), collector)
         , m_processCount (0)
         , m_workers (*this, "JobQueue", 0)
         , m_cancelCallback (boost::bind (&Stoppable::isStopping, this))
         , m_collector (collector)
     {
         hook = m_collector->make_hook (std::bind (
             &JobQueueImp::collect, this));
         job_count = m_collector->make_gauge ("job_count");
         {
             ScopedLock lock (m_mutex);
             for (auto const& x : getJobTypes ())
             {
                 JobTypeInfo const& jt = x.second;
                 // And create dynamic information for all jobs
                 auto const result (m_jobData.emplace (std::piecewise_construct,
                     std::forward_as_tuple (jt.type ()),
                     std::forward_as_tuple (jt, m_collector)));
                 assert (result.second == true);
             }
         }
     }
ripple::JobQueueImp::~JobQueueImp () inline
Definition at line 101 of file JobQueue.cpp.
References hook.
     {
         // Must unhook before destroying
         hook = beast::insight::Hook ();
     }
Member Function Documentation
void ripple::JobQueueImp::addJob (JobType type, std::string const & name, boost::function< void(Job &)> const & jobFunc) inline virtual
Implements ripple::JobQueue.
Definition at line 113 of file JobQueue.cpp.
References beast::Stoppable::areChildrenStopped(), beast::Journal::debug, beast::Workers::getNumberOfThreads(), beast::Stoppable::isStopped(), beast::Stoppable::isStopping(), ripple::jtCLIENT, ripple::jtINVALID, ripple::JobTypeData::load(), m_cancelCallback, m_jobData, m_jobSet, m_journal, m_lastJob, m_mutex, m_processCount, m_workers, queueJob(), and skipOnStop().
     {
         assert (type != jtINVALID);
         JobDataMap::iterator iter (m_jobData.find (type));
         assert (iter != m_jobData.end ());
         if (iter == m_jobData.end ())
             return;
         JobTypeData& data (iter->second);
         // FIXME: Workaround incorrect client shutdown ordering
         // do not add jobs to a queue with no threads
         assert (type == jtCLIENT || m_workers.getNumberOfThreads () > 0);
         {
             // If this goes off it means that a child didn't follow
             // the Stoppable API rules. A job may only be added if:
             //
             //  - The JobQueue has NOT stopped
             //          AND
             //      * We are currently processing jobs
             //          OR
             //      * We have have pending jobs
             //          OR
             //      * Not all children are stopped
             //
             ScopedLock lock (m_mutex);
             assert (! isStopped() && (
                 m_processCount>0 ||
                 ! m_jobSet.empty () ||
                 ! areChildrenStopped()));
         }
         // Don't even add it to the queue if we're stopping
         // and the job type is marked for skipOnStop.
         //
         if (isStopping() && skipOnStop (type))
         {
             m_journal.debug <<
                 "Skipping addJob ('" << name << "')";
             return;
         }
         {
             ScopedLock lock (m_mutex);
             std::pair <std::set <Job>::iterator, bool> result (
                 m_jobSet.insert (Job (type, name, ++m_lastJob,
                     data.load (), jobFunc, m_cancelCallback)));
             queueJob (*result.first, lock);
         }
     }
void ripple::JobQueueImp::checkStopped (ScopedLock const & lock) inline private
Definition at line 358 of file JobQueue.cpp.
References beast::Stoppable::areChildrenStopped(), beast::Stoppable::isStopping(), m_jobSet, m_processCount, and beast::Stoppable::stopped().
Referenced by onChildrenStopped(), and processTask().
     {
         // We are stopped when all of the following are true:
         //
         //  1. A stop notification was received
         //  2. All Stoppable children have stopped
         //  3. There are no executing calls to processTask
         //  4. There are no remaining Jobs in the job set
         //
         if (isStopping() &&
             areChildrenStopped() &&
             (m_processCount == 0) &&
             m_jobSet.empty())
         {
             stopped();
         }
     }
void ripple::JobQueueImp::collect () inline
Definition at line 107 of file JobQueue.cpp.
References job_count, m_jobSet, and m_mutex.
Referenced by JobQueueImp().
     {
         ScopedLock lock (m_mutex);
         job_count = m_jobSet.size ();
     }
void ripple::JobQueueImp::finishJob (Job const & job, ScopedLock const & lock) inline private
Definition at line 481 of file JobQueue.cpp.
References beast::Workers::addTask(), ripple::JobTypeData::deferred, getJobLimit(), getJobTypeData(), ripple::Job::getType(), ripple::jtINVALID, m_jobSet, m_workers, ripple::JobTypeData::running, and ripple::JobTypeData::waiting.
Referenced by processTask().
     {
         JobType const type = job.getType ();
         assert (m_jobSet.find (job) == m_jobSet.end ());
         assert (type != jtINVALID);
         JobTypeData& data (getJobTypeData (type));
         // Queue a deferred task if possible
         if (data.deferred > 0)
         {
             assert (data.running + data.waiting >= getJobLimit (type));
             --data.deferred;
             m_workers.addTask ();
         }
         --data.running;
     }
int ripple::JobQueueImp::getJobCount (JobType t) inline virtual
Implements ripple::JobQueue.
Definition at line 169 of file JobQueue.cpp.
References m_jobData, and m_mutex.
     {
         ScopedLock lock (m_mutex);
         JobDataMap::const_iterator c = m_jobData.find (t);
         return (c == m_jobData.end ())
             ? 0
             : c->second.waiting;
     }
int ripple::JobQueueImp::getJobCountGE (JobType t) inline virtual
Implements ripple::JobQueue.
Definition at line 191 of file JobQueue.cpp.
References m_jobData, and m_mutex.
     {
         // return the number of jobs at this priority level or greater
         int ret = 0;
         ScopedLock lock (m_mutex);
         for (auto const& x : m_jobData)
         {
             if (x.first >= t)
                 ret += x.second.waiting;
         }
         return ret;
     }
int ripple::JobQueueImp::getJobCountTotal (JobType t) inline virtual
Implements ripple::JobQueue.
Definition at line 180 of file JobQueue.cpp.
References m_jobData, and m_mutex.
     {
         ScopedLock lock (m_mutex);
         JobDataMap::const_iterator c = m_jobData.find (t);
         return (c == m_jobData.end ())
             ? 0
             : (c->second.waiting + c->second.running);
     }
int ripple::JobQueueImp::getJobLimit (JobType type) inline private
Definition at line 597 of file JobQueue.cpp.
References getJobTypes(), ripple::jtINVALID, ripple::JobTypeInfo::limit(), and ripple::JobTypeInfo::type().
Referenced by finishJob(), getNextJob(), and queueJob().
     {
         JobTypeInfo const& j (getJobTypes ().get (type));
         assert (j.type () != jtINVALID);
         return j.limit ();
     }
JobTypeData& ripple::JobQueueImp::getJobTypeData (JobType type) inline private
Definition at line 341 of file JobQueue.cpp.
References m_invalidJobData, and m_jobData.
Referenced by finishJob(), getNextJob(), on_dequeue(), on_execute(), processTask(), and queueJob().
     {
         JobDataMap::iterator c (m_jobData.find (type));
         assert (c != m_jobData.end ());
         // NIKB: This is ugly and I hate it. We must remove jtINVALID completely
         //       and use something sane.
         if (c == m_jobData.end ())
             return m_invalidJobData;
         return c->second;
     }
static JobTypes const& ripple::JobQueueImp::getJobTypes () inline static
Definition at line 62 of file JobQueue.cpp.
Referenced by getJobLimit(), JobQueueImp(), and skipOnStop().
     {
         static JobTypes types;
         return types;
     }
Json::Value ripple::JobQueueImp::getJson (int) inline virtual
Implements ripple::JobQueue.
Definition at line 283 of file JobQueue.cpp.
References Json::Value::append(), Json::arrayValue, beast::Workers::getNumberOfThreads(), ripple::jtGENERIC, ripple::jtINVALID, m_jobData, m_mutex, m_workers, ripple::JobTypeData::name(), Json::objectValue, ripple::JobTypeData::running, ripple::JobTypeData::stats(), stats, and ripple::JobTypeData::waiting.
     {
         Json::Value ret (Json::objectValue);
         ret["threads"] = m_workers.getNumberOfThreads ();
         Json::Value priorities = Json::arrayValue;
         ScopedLock lock (m_mutex);
         for (auto& x : m_jobData)
         {
             assert (x.first != jtINVALID);
             if (x.first == jtGENERIC)
                 continue;
             JobTypeData& data (x.second);
             LoadMonitor::Stats stats (data.stats ());
             int waiting (data.waiting);
             int running (data.running);
             if ((stats.count != 0) || (waiting != 0) ||
                 (stats.latencyPeak != 0) || (running != 0))
             {
                 Json::Value& pri = priorities.append (Json::objectValue);
                 pri["job_type"] = data.name ();
                 if (stats.isOverloaded)
                     pri["over_target"] = true;
                 if (waiting != 0)
                     pri["waiting"] = waiting;
                 if (stats.count != 0)
                     pri["per_second"] = static_cast<int> (stats.count);
                 if (stats.latencyPeak != 0)
                     pri["peak_time"] = static_cast<int> (stats.latencyPeak);
                 if (stats.latencyAvg != 0)
                     pri["avg_time"] = static_cast<int> (stats.latencyAvg);
                 if (running != 0)
                     pri["in_progress"] = running;
             }
         }
         ret["job_types"] = priorities;
         return ret;
     }
LoadEvent::pointer ripple::JobQueueImp::getLoadEvent (JobType t, const std::string & name) inline virtual
Implements ripple::JobQueue.
Definition at line 246 of file JobQueue.cpp.
References m_jobData.
     {
         JobDataMap::iterator iter (m_jobData.find (t));
         assert (iter != m_jobData.end ());
         if (iter == m_jobData.end ())
             return boost::shared_ptr<LoadEvent> ();
         return boost::make_shared<LoadEvent> (
             boost::ref (iter-> second.load ()), name, true);
     }
LoadEvent::autoptr ripple::JobQueueImp::getLoadEventAP (JobType t, const std::string & name) inline virtual
Implements ripple::JobQueue.
Definition at line 258 of file JobQueue.cpp.
References m_jobData, and name.
     {
         JobDataMap::iterator iter (m_jobData.find (t));
         assert (iter != m_jobData.end ());
         if (iter == m_jobData.end ())
             return LoadEvent::autoptr ();
         return LoadEvent::autoptr (
             new LoadEvent (iter-> second.load (), name, true));
     }
void ripple::JobQueueImp::getNextJob (Job & job, ScopedLock const & lock) inline private
Definition at line 433 of file JobQueue.cpp.
References getJobLimit(), getJobTypeData(), ripple::jtINVALID, m_jobSet, ripple::JobTypeData::running, ripple::JobTypeData::type(), and ripple::JobTypeData::waiting.
Referenced by processTask().
     {
         assert (! m_jobSet.empty ());
         JobSet::const_iterator iter;
         for (iter = m_jobSet.begin (); iter != m_jobSet.end (); ++iter)
         {
             JobTypeData& data (getJobTypeData (iter->getType ()));
             assert (data.running <= getJobLimit (data.type ()));
             // Run this job if we're running below the limit.
             if (data.running < getJobLimit (data.type ()))
             {
                 assert (data.waiting > 0);
                 break;
             }
         }
         assert (iter != m_jobSet.end ());
         JobType const type = iter->getType ();
         JobTypeData& data (getJobTypeData (type));
         assert (type != jtINVALID);
         job = *iter;
         m_jobSet.erase (iter);
         --data.waiting;
         ++data.running;
     }
bool ripple::JobQueueImp::isOverloaded () inline virtual
Implements ripple::JobQueue.
Definition at line 270 of file JobQueue.cpp.
References m_jobData.
     {
         int count = 0;
         for (auto& x : m_jobData)
         {
             if (x.second.load ().isOver ())
                 ++count;
         }
         return count > 0;
     }
template<class Rep , class Period > void ripple::JobQueueImp::on_dequeue (JobType type, std::chrono::duration< Rep, Period > const & value) inline private
Definition at line 504 of file JobQueue.cpp.
References ripple::JobTypeData::dequeue, getJobTypeData(), and beast::insight::Event::notify().
Referenced by processTask().
     {
         auto const ms (ceil <std::chrono::milliseconds> (value));
         if (ms.count() >= 10)
             getJobTypeData (type).dequeue.notify (ms);
     }
template<class Rep , class Period > void ripple::JobQueueImp::on_execute (JobType type, std::chrono::duration< Rep, Period > const & value) inline private
Definition at line 514 of file JobQueue.cpp.
References ripple::JobTypeData::execute, getJobTypeData(), and beast::insight::Event::notify().
Referenced by processTask().
     {
         auto const ms (ceil <std::chrono::milliseconds> (value));
         if (ms.count() >= 10)
             getJobTypeData (type).execute.notify (ms);
     }
void ripple::JobQueueImp::onChildrenStopped () inline private virtual
Override called when all children have stopped.
The call is made on an unspecified, implementation-specific thread. onStop and onChildrenStopped will never be called concurrently, across all Stoppable objects descended from the same root, inclusive of the root.
It is safe to call isStopping, isStopped, and areChildrenStopped from within this function; The values returned will always be valid and never change during the callback.
The default implementation does nothing.
Thread safety: May not block for long periods. Guaranteed only to be called once. Must be safe to call from any thread at any time.
Reimplemented from beast::Stoppable.
Definition at line 659 of file JobQueue.cpp.
References checkStopped(), and m_mutex.
     {
         ScopedLock lock (m_mutex);
         checkStopped (lock);
     }
void ripple::JobQueueImp::onStop () inline private virtual
Override called when the stop notification is issued.
The call is made on an unspecified, implementation-specific thread. onStop and onChildrenStopped will never be called concurrently, across all Stoppable objects descended from the same root, inclusive of the root.
It is safe to call isStopping, isStopped, and areChildrenStopped from within this function; The values returned will always be valid and never change during the callback.
The default implementation simply calls stopped(). This is applicable when the Stoppable has a trivial stop operation (or no stop operation), and we are merely using the Stoppable API to position it as a dependency of some parent service.
Thread safety: May not block for long periods. Guaranteed only to be called once. Must be safe to call from any thread at any time.
Reimplemented from beast::Stoppable.
Definition at line 607 of file JobQueue.cpp.
     {
         // VFALCO NOTE I wanted to remove all the jobs that are skippable
         //             but then the Workers count of tasks to process
         //             goes wrong.
         /*
         {
             ScopedLock lock (m_mutex);
             // Remove all jobs whose type is skipOnStop
             typedef ripple::unordered_map <JobType, std::size_t> JobDataMap;
             JobDataMap counts;
             bool const report (m_journal.debug.active());
             for (JobSet::const_iterator iter (m_jobSet.begin());
                 iter != m_jobSet.end();)
             {
                 if (skipOnStop (iter->getType()))
                 {
                     if (report)
                     {
                         std::pair <JobDataMap::iterator, bool> result (
                             counts.insert (std::make_pair (iter->getType(), 1)));
                         if (! result.second)
                             ++(result.first->second);
                     }
                     iter = m_jobSet.erase (iter);
                 }
                 else
                 {
                     ++iter;
                 }
             }
             if (report)
             {
                 beast::Journal::ScopedStream s (m_journal.debug);
                 for (JobDataMap::const_iterator iter (counts.begin());
                     iter != counts.end(); ++iter)
                 {
                     s << std::endl <<
                         "Removed " << iter->second <<
                         " skiponStop jobs of type " << Job::toString (iter->first);
                 }
             }
         }
         */
     }
void ripple::JobQueueImp::processTask () inline private virtual
Perform a task.
The call is made on a thread owned by Workers. It is important that you only process one task from inside your callback. Each call to addTask will result in exactly one call to processTask.
See Also
Workers::addTask
Implements beast::Workers::Callback.
Definition at line 536 of file JobQueue.cpp.
References checkStopped(), ripple::Job::doJob(), finishJob(), getJobTypeData(), getNextJob(), ripple::Job::getType(), ripple::JobTypeData::info, beast::Stoppable::isStopping(), m_journal, m_mutex, m_processCount, ripple::JobTypeData::name(), on_dequeue(), on_execute(), ripple::Job::queue_time(), beast::Thread::setCurrentThreadName(), ripple::JobTypeInfo::skip(), and beast::Journal::trace.
     {
         Job job;
         {
             ScopedLock lock (m_mutex);
             getNextJob (job, lock);
             ++m_processCount;
         }
         JobTypeData& data (getJobTypeData (job.getType ()));
         // Skip the job if we are stopping and the
         // skipOnStop flag is set for the job type
         //
         if (!isStopping() || !data.info.skip ())
         {
             beast::Thread::setCurrentThreadName (data.name ());
             m_journal.trace << "Doing " << data.name () << " job";
             Job::clock_type::time_point const start_time (
                 Job::clock_type::now());
             on_dequeue (job.getType (), start_time - job.queue_time ());
             job.doJob ();
             on_execute (job.getType (), Job::clock_type::now() - start_time);
         }
         else
         {
             m_journal.trace << "Skipping processTask ('" << data.name () << "')";
         }
         {
             ScopedLock lock (m_mutex);
             finishJob (job, lock);
             --m_processCount;
             checkStopped (lock);
         }
         // Note that when Job::~Job is called, the last reference
         // to the associated LoadEvent object (in the Job) may be destroyed.
     }
void ripple::JobQueueImp::queueJob (Job const & job, ScopedLock const & lock) inline private
Definition at line 392 of file JobQueue.cpp.
References beast::Workers::addTask(), getJobLimit(), getJobTypeData(), ripple::Job::getType(), ripple::jtINVALID, m_jobSet, and m_workers.
Referenced by addJob().
     {
         JobType const type (job.getType ());
         assert (type != jtINVALID);
         assert (m_jobSet.find (job) != m_jobSet.end ());
         JobTypeData& data (getJobTypeData (type));
         if (data.waiting + data.running < getJobLimit (type))
         {
             m_workers.addTask ();
         }
         else
         {
             // defer the task until we go below the limit
             //
             ++data.deferred;
         }
         ++data.waiting;
     }
void ripple::JobQueueImp::setThreadCount (int c, bool const standaloneMode) inline virtual
Implements ripple::JobQueue.
Definition at line 217 of file JobQueue.cpp.
References beast::SystemStats::getNumCpus(), beast::Journal::info, m_journal, m_workers, and beast::Workers::setNumberOfThreads().
     {
         if (standaloneMode)
         {
             c = 1;
         }
         else if (c == 0)
         {
             c = beast::SystemStats::getNumCpus ();
             // VFALCO NOTE According to boost, hardware_concurrency cannot return
             //             negative numbers/
             //
             if (c < 0)
                 c = 2; // VFALCO NOTE Why 2?
             if (c > 4) // I/O will bottleneck
                 c = 4;
             c += 2;
             m_journal.info << "Auto-tuning to " << c <<
                               " validation/transaction/proposal threads";
         }
         m_workers.setNumberOfThreads (c);
     }
void ripple::JobQueueImp::shutdown () inline virtual
Implements ripple::JobQueue.
Definition at line 209 of file JobQueue.cpp.
References beast::Journal::info, m_journal, m_workers, and beast::Workers::pauseAllThreadsAndWait().
     {
         m_journal.info <<  "Job queue shutting down";
         m_workers.pauseAllThreadsAndWait ();
     }
bool ripple::JobQueueImp::skipOnStop (JobType type) inline private
Definition at line 585 of file JobQueue.cpp.
References getJobTypes(), ripple::jtINVALID, ripple::JobTypeInfo::skip(), and ripple::JobTypeInfo::type().
Referenced by addJob().
     {
         JobTypeInfo const& j (getJobTypes ().get (type));
         assert (j.type () != jtINVALID);
         return j.skip ();
     }
Member Data Documentation
beast::insight::Hook ripple::JobQueueImp::hook
Definition at line 59 of file JobQueue.cpp.
Referenced by JobQueueImp(), and ~JobQueueImp().
beast::insight::Gauge ripple::JobQueueImp::job_count
Definition at line 58 of file JobQueue.cpp.
Referenced by collect(), and JobQueueImp().
CancelCallback ripple::JobQueueImp::m_cancelCallback
Definition at line 54 of file JobQueue.cpp.
Referenced by addJob().
beast::insight::Collector::ptr ripple::JobQueueImp::m_collector
Definition at line 57 of file JobQueue.cpp.
Referenced by JobQueueImp().
JobTypeData ripple::JobQueueImp::m_invalidJobData
Definition at line 48 of file JobQueue.cpp.
Referenced by getJobTypeData().
JobDataMap ripple::JobQueueImp::m_jobData
Definition at line 47 of file JobQueue.cpp.
Referenced by addJob(), getJobCount(), getJobCountGE(), getJobCountTotal(), getJobTypeData(), getJson(), getLoadEvent(), getLoadEventAP(), isOverloaded(), and JobQueueImp().
JobSet ripple::JobQueueImp::m_jobSet
Definition at line 46 of file JobQueue.cpp.
Referenced by addJob(), checkStopped(), collect(), finishJob(), getNextJob(), and queueJob().
beast::Journal ripple::JobQueueImp::m_journal
Definition at line 43 of file JobQueue.cpp.
Referenced by addJob(), processTask(), setThreadCount(), and shutdown().
std::uint64_t ripple::JobQueueImp::m_lastJob
Definition at line 45 of file JobQueue.cpp.
Referenced by addJob().
beast::CriticalSection ripple::JobQueueImp::m_mutex
Definition at line 44 of file JobQueue.cpp.
Referenced by addJob(), collect(), getJobCount(), getJobCountGE(), getJobCountTotal(), getJson(), JobQueueImp(), onChildrenStopped(), and processTask().
int ripple::JobQueueImp::m_processCount
Definition at line 51 of file JobQueue.cpp.
Referenced by addJob(), checkStopped(), and processTask().
beast::Workers ripple::JobQueueImp::m_workers
Definition at line 53 of file JobQueue.cpp.
Referenced by addJob(), finishJob(), getJson(), queueJob(), setThreadCount(), and shutdown().
The documentation for this class was generated from the following file:
rippled/src/ripple_core/functional/JobQueue.cpp