rippled: ripple::core::BookTip Class Reference
ripple::core::BookTip Class Reference
#include <BookTip.h>
Public Member Functions
BookTip (LedgerView &view, BookRef book)
uint256 const & dir () const noexcept
uint256 const & index () const noexcept
Quality const quality () const noexcept
SLE::pointer const & entry () const noexcept
bool step ()
Private Member Functions
LedgerView & view () const noexcept
Private Attributes
std::reference_wrapper
< LedgerView > m_view
bool m_valid
uint256 m_book
uint256 m_end
uint256 m_dir
uint256 m_index
SLE::pointer m_entry
Detailed Description
Iterates and consumes raw offers in an order book. Offers are presented from highest quality to lowest quality. This will return all offers present including missing, invalid, unfunded, etc.
Definition at line 38 of file BookTip.h.
Constructor & Destructor Documentation
ripple::core::BookTip::BookTip (LedgerView & view, BookRef book) inline
Create the iterator.
Definition at line 57 of file BookTip.h.
         : m_view (view)
         , m_valid (false)
         , m_book (Ledger::getBookBase (
             book.in.currency, book.in.issuer,
             book.out.currency, book.out.issuer))
         , m_end (Ledger::getQualityNext (m_book))
     {
     }
Member Function Documentation
uint256 const& ripple::core::BookTip::dir () const inline noexcept
Definition at line 68 of file BookTip.h.
References m_dir.
Referenced by ripple::core::OfferStream::dir(), ripple::core::OfferStream::erase(), and step().
     {
         return m_dir;
     }
SLE::pointer const& ripple::core::BookTip::entry () const inline noexcept
Definition at line 86 of file BookTip.h.
References m_entry.
Referenced by ripple::core::OfferStream::step().
     {
         return m_entry;
     }
uint256 const& ripple::core::BookTip::index () const inline noexcept
Definition at line 74 of file BookTip.h.
References m_index.
Referenced by ripple::core::OfferStream::erase().
     {
         return m_index;
     }
Quality const ripple::core::BookTip::quality () const inline noexcept
Definition at line 80 of file BookTip.h.
References ripple::Ledger::getQuality(), and m_dir.
Referenced by ripple::core::OfferStream::step().
     {
         return Quality (Ledger::getQuality (m_dir));
     }
bool ripple::core::BookTip::step () inline
Erases the current offer and advance to the next offer. Complexity: Constant
Returns
true if there is a next offer
Definition at line 96 of file BookTip.h.
References dir(), ripple::LedgerEntrySet::entryCache(), ripple::ltOFFER, m_book, m_dir, m_end, m_entry, m_index, m_valid, ripple::LedgerEntrySet::offerDelete(), and view().
Referenced by ripple::core::OfferStream::step().
     {
         if (m_valid)
         {
             if (m_entry)
             {
                 view().offerDelete (m_index);
                 m_entry = nullptr;
             }
         }
         for(;;)
         {
             // See if there's an entry at or worse than current quality.
             auto const page (
                 view().getNextLedgerIndex (m_book, m_end));
             if (page.isZero())
                 return false;
             unsigned int di (0);
             SLE::pointer dir;
             if (view().dirFirst (page, dir, di, m_index))
             {
                 m_dir = dir->getIndex();
                 m_entry = view().entryCache (ltOFFER, m_index);
                 m_valid = true;
                 // Next query should start before this directory
                 m_book = page;
                 // The quality immediately before the next quality
                 --m_book;
                 break;
             }
             // There should never be an empty directory but just in case,
             // we handle that case by advancing to the next directory.
             m_book = page;
         }
         return true;
     }
LedgerView& ripple::core::BookTip::view () const inline private noexcept
Definition at line 50 of file BookTip.h.
References m_view.
Referenced by step().
     {
         return m_view;
     }
Member Data Documentation
uint256 ripple::core::BookTip::m_book private
Definition at line 43 of file BookTip.h.
Referenced by step().
uint256 ripple::core::BookTip::m_dir private
Definition at line 45 of file BookTip.h.
Referenced by dir(), quality(), and step().
uint256 ripple::core::BookTip::m_end private
Definition at line 44 of file BookTip.h.
Referenced by step().
SLE::pointer ripple::core::BookTip::m_entry private
Definition at line 47 of file BookTip.h.
Referenced by entry(), and step().
uint256 ripple::core::BookTip::m_index private
Definition at line 46 of file BookTip.h.
Referenced by index(), and step().
bool ripple::core::BookTip::m_valid private
Definition at line 42 of file BookTip.h.
Referenced by step().
std::reference_wrapper<LedgerView> ripple::core::BookTip::m_view private
Definition at line 41 of file BookTip.h.
Referenced by view().
The documentation for this class was generated from the following file:
rippled/src/ripple_app/book/BookTip.h