rippled: ripple::ResolverAsioImpl Class Reference
ripple::ResolverAsioImpl Class Reference
Classes
struct Work
Public Types
typedef std::pair< std::string,
std::string > HostAndPort
Public Member Functions
ResolverAsioImpl (boost::asio::io_service &io_service, beast::Journal journal)
~ResolverAsioImpl ()
void asyncHandlersComplete ()
void start ()
void stop_async ()
void stop ()
void resolve (std::vector< std::string > const &names, HandlerType const &handler)
void do_stop (CompletionCounter)
void do_finish (std::string name, boost::system::error_code const &ec, HandlerType handler, boost::asio::ip::tcp::resolver::iterator iter, CompletionCounter)
HostAndPort parseName (std::string const &str)
void do_work (CompletionCounter)
void do_resolve (std::vector< std::string > const &names, HandlerType const &handler, CompletionCounter)
Public Member Functions inherited from beast::asio::AsyncObject< ResolverAsioImpl >
~AsyncObject ()
void addReference ()
void removeReference ()
Public Attributes
beast::Journal m_journal
boost::asio::io_service & m_io_service
boost::asio::io_service::strand m_strand
boost::asio::ip::tcp::resolver m_resolver
beast::WaitableEvent m_stop_complete
std::atomic< bool > m_stop_called
std::atomic< bool > m_stopped
std::deque< Work > m_work
Additional Inherited Members
Static Public Member Functions inherited from ripple::ResolverAsio
static ResolverAsio * New (boost::asio::io_service &io_service, beast::Journal journal)
Detailed Description
Definition at line 35 of file ResolverAsio.cpp.
Member Typedef Documentation
typedef std::pair<std::string, std::string> ripple::ResolverAsioImpl::HostAndPort
Definition at line 40 of file ResolverAsio.cpp.
Constructor & Destructor Documentation
ripple::ResolverAsioImpl::ResolverAsioImpl (boost::asio::io_service & io_service, beast::Journal journal) inline
Definition at line 71 of file ResolverAsio.cpp.
             : m_journal (journal)
             , m_io_service (io_service)
             , m_strand (io_service)
             , m_resolver (io_service)
             , m_stop_complete (true, true)
             , m_stop_called (false)
             , m_stopped (true)
     {
     }
ripple::ResolverAsioImpl::~ResolverAsioImpl () inline
Definition at line 84 of file ResolverAsio.cpp.
References m_stopped, and m_work.
     {
         assert (m_work.empty ());
         assert (m_stopped);
     }
Member Function Documentation
void ripple::ResolverAsioImpl::asyncHandlersComplete () inline
Definition at line 92 of file ResolverAsio.cpp.
References m_stop_complete, and beast::WaitableEvent::signal().
     {
         m_stop_complete.signal ();
     }
void ripple::ResolverAsioImpl::do_finish (std::string name, boost::system::error_code const & ec, HandlerType handler, boost::asio::ip::tcp::resolver::iterator iter, CompletionCounter) inline
Definition at line 167 of file ResolverAsio.cpp.
References do_work(), beast::IPAddressConversion::from_asio(), m_io_service, and m_strand.
Referenced by do_work().
     {
         if (ec == boost::asio::error::operation_aborted)
             return;
         std::vector <beast::IP::Endpoint> addresses;
         // If we get an error message back, we don't return any
         // results that we may have gotten.
         if (ec == 0)
         {
             while (iter != boost::asio::ip::tcp::resolver::iterator())
             {
                 addresses.push_back (beast::IPAddressConversion::from_asio (*iter));
                 ++iter;
             }
         }
         handler (name, addresses);
         m_io_service.post (m_strand.wrap (boost::bind (
             &ResolverAsioImpl::do_work, this,
                 CompletionCounter (this))));
     }
void ripple::ResolverAsioImpl::do_resolve (std::vector< std::string > const & names, HandlerType const & handler, CompletionCounter) inline
Definition at line 279 of file ResolverAsio.cpp.
References beast::Journal::debug, do_work(), m_io_service, m_journal, m_stop_called, m_strand, and m_work.
Referenced by resolve().
     {
         assert (! names.empty());
         if (m_stop_called == false)
         {
             m_work.emplace_back (names, handler);
             m_journal.debug <<
                 "Queued new job with " << names.size() <<
                 " tasks. " << m_work.size() << " jobs outstanding.";
             if (m_work.size() == 1)
             {
                 m_io_service.post (m_strand.wrap (boost::bind (
                     &ResolverAsioImpl::do_work, this,
                         CompletionCounter (this))));
             }
         }
     }
void ripple::ResolverAsioImpl::do_stop (CompletionCounter) inline
Definition at line 154 of file ResolverAsio.cpp.
References m_resolver, m_stop_called, m_stopped, m_work, and beast::asio::AsyncObject< ResolverAsioImpl >::removeReference().
Referenced by stop_async().
     {
         assert (m_stop_called == true);
         if (m_stopped.exchange (true) == false)
         {
             m_work.clear ();
             m_resolver.cancel ();
             removeReference ();
         }
     }
void ripple::ResolverAsioImpl::do_work (CompletionCounter) inline
Definition at line 238 of file ResolverAsio.cpp.
References do_finish(), beast::Journal::error, m_io_service, m_journal, m_resolver, m_stop_called, m_strand, m_work, name, and parseName().
Referenced by do_finish(), and do_resolve().
     {
         if (m_stop_called == true)
             return;
         // We don't have any work to do at this time
         if (m_work.empty ())
             return;
         std::string const name (m_work.front ().names.back());
         HandlerType handler (m_work.front ().handler);
         m_work.front ().names.pop_back ();
         if (m_work.front ().names.empty ())
             m_work.pop_front();
         HostAndPort const hp (parseName (name));
         if (hp.first.empty ())
         {
             m_journal.error <<
                 "Unable to parse '" << name << "'";
             m_io_service.post (m_strand.wrap (boost::bind (
                 &ResolverAsioImpl::do_work, this,
                 CompletionCounter (this))));
             return;
         }
         boost::asio::ip::tcp::resolver::query query (
             hp.first, hp.second);
         m_resolver.async_resolve (query, boost::bind (
             &ResolverAsioImpl::do_finish, this, name,
                 boost::asio::placeholders::error, handler,
                     boost::asio::placeholders::iterator,
                         CompletionCounter (this)));
     }
HostAndPort ripple::ResolverAsioImpl::parseName (std::string const & str) inline
Definition at line 197 of file ResolverAsio.cpp.
References base.
Referenced by do_work().
     {
         // Attempt to find the first and last non-whitespace
         auto const find_whitespace = std::bind (
             &std::isspace <std::string::value_type>,
             std::placeholders::_1,
             std::locale ());
         auto host_first = std::find_if_not (
             str.begin (), str.end (), find_whitespace);
         auto port_last = std::find_if_not (
             str.rbegin (), str.rend(), find_whitespace).base();
         // This should only happen for all-whitespace strings
         if (host_first >= port_last)
             return std::make_pair(std::string (), std::string ());
         // Attempt to find the first and last valid port separators
         auto const find_port_separator = [](char const c) -> bool
         {
             if (std::isspace (c))
                 return true;
             if (c == ':')
                 return true;
             return false;
         };
         auto host_last = std::find_if (
             host_first, port_last, find_port_separator);
         auto port_first = std::find_if_not (
             host_last, port_last, find_port_separator);
         return make_pair (
             std::string (host_first, host_last),
             std::string (port_first, port_last));
     }
void ripple::ResolverAsioImpl::resolve (std::vector< std::string > const & names, HandlerType const & handler) inline virtual
Implements ripple::Resolver.
Definition at line 137 of file ResolverAsio.cpp.
References do_resolve(), m_io_service, m_stop_called, m_stopped, and m_strand.
     {
         assert (m_stop_called == false);
         assert (m_stopped == true);
         assert (!names.empty());
         // TODO NIKB use rvalue references to construct and move
         //           reducing cost.
         m_io_service.dispatch (m_strand.wrap (boost::bind (
             &ResolverAsioImpl::do_resolve, this,
                 names, handler, CompletionCounter (this))));
     }
void ripple::ResolverAsioImpl::start () inline virtual
Issue a synchronous start request.
Implements ripple::Resolver.
Definition at line 103 of file ResolverAsio.cpp.
References beast::asio::AsyncObject< ResolverAsioImpl >::addReference(), m_stop_called, m_stop_complete, m_stopped, m_work, and beast::WaitableEvent::reset().
     {
         assert (m_work.empty ());
         assert (m_stopped == true);
         assert (m_stop_called == false);
         if (m_stopped.exchange (false) == true)
         {
             m_stop_complete.reset ();
             addReference ();
         }
     }
void ripple::ResolverAsioImpl::stop () inline virtual
Issue a synchronous stop request.
Implements ripple::Resolver.
Definition at line 128 of file ResolverAsio.cpp.
References beast::Journal::debug, m_journal, m_stop_complete, stop_async(), and beast::WaitableEvent::wait().
     {
         stop_async ();
         m_journal.debug << "Waiting to stop";
         m_stop_complete.wait();
         m_journal.debug << "Stopped";
     }
void ripple::ResolverAsioImpl::stop_async () inline virtual
Issue an asynchronous stop request.
Implements ripple::Resolver.
Definition at line 116 of file ResolverAsio.cpp.
References beast::Journal::debug, do_stop(), m_io_service, m_journal, m_stop_called, and m_strand.
Referenced by stop().
     {
         if (m_stop_called.exchange (true) == false)
         {
             m_io_service.dispatch (m_strand.wrap (boost::bind (
                 &ResolverAsioImpl::do_stop,
                     this, CompletionCounter (this))));
             m_journal.debug << "Queued a stop request";
         }
     }
Member Data Documentation
boost::asio::io_service& ripple::ResolverAsioImpl::m_io_service
Definition at line 44 of file ResolverAsio.cpp.
Referenced by do_finish(), do_resolve(), do_work(), resolve(), and stop_async().
beast::Journal ripple::ResolverAsioImpl::m_journal
Definition at line 42 of file ResolverAsio.cpp.
Referenced by do_resolve(), do_work(), stop(), and stop_async().
boost::asio::ip::tcp::resolver ripple::ResolverAsioImpl::m_resolver
Definition at line 46 of file ResolverAsio.cpp.
Referenced by do_stop(), and do_work().
std::atomic<bool> ripple::ResolverAsioImpl::m_stop_called
Definition at line 49 of file ResolverAsio.cpp.
Referenced by do_resolve(), do_stop(), do_work(), resolve(), start(), and stop_async().
beast::WaitableEvent ripple::ResolverAsioImpl::m_stop_complete
Definition at line 48 of file ResolverAsio.cpp.
Referenced by asyncHandlersComplete(), start(), and stop().
std::atomic<bool> ripple::ResolverAsioImpl::m_stopped
Definition at line 50 of file ResolverAsio.cpp.
Referenced by do_stop(), resolve(), start(), and ~ResolverAsioImpl().
boost::asio::io_service::strand ripple::ResolverAsioImpl::m_strand
Definition at line 45 of file ResolverAsio.cpp.
Referenced by do_finish(), do_resolve(), do_work(), resolve(), and stop_async().
std::deque<Work> ripple::ResolverAsioImpl::m_work
Definition at line 69 of file ResolverAsio.cpp.
Referenced by do_resolve(), do_stop(), do_work(), start(), and ~ResolverAsioImpl().
The documentation for this class was generated from the following file:
rippled/src/ripple/common/impl/ResolverAsio.cpp