rippled: rippled/src/ripple/rocksdb/rocksdb/db/c.cc File Reference
c.cc File Reference
#include "rocksdb/c.h"
#include <stdlib.h>
#include <unistd.h>
#include "rocksdb/cache.h"
#include "rocksdb/comparator.h"
#include "rocksdb/db.h"
#include "rocksdb/env.h"
#include "rocksdb/filter_policy.h"
#include "rocksdb/iterator.h"
#include "rocksdb/options.h"
#include "rocksdb/status.h"
#include "rocksdb/write_batch.h"
Classes
struct leveldb_t
struct leveldb_iterator_t
struct leveldb_writebatch_t
struct leveldb_snapshot_t
struct leveldb_readoptions_t
struct leveldb_writeoptions_t
struct leveldb_options_t
struct leveldb_seqfile_t
struct leveldb_randomfile_t
struct leveldb_writablefile_t
struct leveldb_filelock_t
struct leveldb_logger_t
struct leveldb_cache_t
struct leveldb_comparator_t
struct leveldb_filterpolicy_t
struct leveldb_env_t
Functions
static bool SaveError (char **errptr, const Status &s)
static char * CopyString (const std::string &str)
leveldb_t * leveldb_open (const leveldb_options_t *options, const char *name, char **errptr)
void leveldb_close (leveldb_t *db)
void leveldb_put (leveldb_t *db, const leveldb_writeoptions_t *options, const char *key, size_t keylen, const char *val, size_t vallen, char **errptr)
void leveldb_delete (leveldb_t *db, const leveldb_writeoptions_t *options, const char *key, size_t keylen, char **errptr)
void leveldb_write (leveldb_t *db, const leveldb_writeoptions_t *options, leveldb_writebatch_t *batch, char **errptr)
char * leveldb_get (leveldb_t *db, const leveldb_readoptions_t *options, const char *key, size_t keylen, size_t *vallen, char **errptr)
leveldb_iterator_t * leveldb_create_iterator (leveldb_t *db, const leveldb_readoptions_t *options)
const leveldb_snapshot_t * leveldb_create_snapshot (leveldb_t *db)
void leveldb_release_snapshot (leveldb_t *db, const leveldb_snapshot_t *snapshot)
char * leveldb_property_value (leveldb_t *db, const char *propname)
void leveldb_approximate_sizes (leveldb_t *db, int num_ranges, const char *const *range_start_key, const size_t *range_start_key_len, const char *const *range_limit_key, const size_t *range_limit_key_len, uint64_t *sizes)
void leveldb_compact_range (leveldb_t *db, const char *start_key, size_t start_key_len, const char *limit_key, size_t limit_key_len)
void leveldb_destroy_db (const leveldb_options_t *options, const char *name, char **errptr)
void leveldb_repair_db (const leveldb_options_t *options, const char *name, char **errptr)
void leveldb_iter_destroy (leveldb_iterator_t *iter)
unsigned char leveldb_iter_valid (const leveldb_iterator_t *iter)
void leveldb_iter_seek_to_first (leveldb_iterator_t *iter)
void leveldb_iter_seek_to_last (leveldb_iterator_t *iter)
void leveldb_iter_seek (leveldb_iterator_t *iter, const char *k, size_t klen)
void leveldb_iter_next (leveldb_iterator_t *iter)
void leveldb_iter_prev (leveldb_iterator_t *iter)
const char * leveldb_iter_key (const leveldb_iterator_t *iter, size_t *klen)
const char * leveldb_iter_value (const leveldb_iterator_t *iter, size_t *vlen)
void leveldb_iter_get_error (const leveldb_iterator_t *iter, char **errptr)
leveldb_writebatch_t * leveldb_writebatch_create ()
void leveldb_writebatch_destroy (leveldb_writebatch_t *b)
void leveldb_writebatch_clear (leveldb_writebatch_t *b)
void leveldb_writebatch_put (leveldb_writebatch_t *b, const char *key, size_t klen, const char *val, size_t vlen)
void leveldb_writebatch_delete (leveldb_writebatch_t *b, const char *key, size_t klen)
void leveldb_writebatch_iterate (leveldb_writebatch_t *b, void *state, void(*put)(void *, const char *k, size_t klen, const char *v, size_t vlen), void(*deleted)(void *, const char *k, size_t klen))
leveldb_options_t * leveldb_options_create ()
void leveldb_options_destroy (leveldb_options_t *options)
void leveldb_options_set_comparator (leveldb_options_t *opt, leveldb_comparator_t *cmp)
void leveldb_options_set_filter_policy (leveldb_options_t *opt, leveldb_filterpolicy_t *policy)
void leveldb_options_set_create_if_missing (leveldb_options_t *opt, unsigned char v)
void leveldb_options_set_error_if_exists (leveldb_options_t *opt, unsigned char v)
void leveldb_options_set_paranoid_checks (leveldb_options_t *opt, unsigned char v)
void leveldb_options_set_env (leveldb_options_t *opt, leveldb_env_t *env)
void leveldb_options_set_info_log (leveldb_options_t *opt, leveldb_logger_t *l)
void leveldb_options_set_write_buffer_size (leveldb_options_t *opt, size_t s)
void leveldb_options_set_max_open_files (leveldb_options_t *opt, int n)
void leveldb_options_set_cache (leveldb_options_t *opt, leveldb_cache_t *c)
void leveldb_options_set_block_size (leveldb_options_t *opt, size_t s)
void leveldb_options_set_block_restart_interval (leveldb_options_t *opt, int n)
void leveldb_options_set_target_file_size_base (leveldb_options_t *opt, uint64_t n)
void leveldb_options_set_target_file_size_multiplier (leveldb_options_t *opt, int n)
void leveldb_options_set_max_bytes_for_level_base (leveldb_options_t *opt, uint64_t n)
void leveldb_options_set_max_bytes_for_level_multiplier (leveldb_options_t *opt, int n)
void leveldb_options_set_expanded_compaction_factor (leveldb_options_t *opt, int n)
void leveldb_options_set_max_grandparent_overlap_factor (leveldb_options_t *opt, int n)
void leveldb_options_set_num_levels (leveldb_options_t *opt, int n)
void leveldb_options_set_level0_file_num_compaction_trigger (leveldb_options_t *opt, int n)
void leveldb_options_set_level0_slowdown_writes_trigger (leveldb_options_t *opt, int n)
void leveldb_options_set_level0_stop_writes_trigger (leveldb_options_t *opt, int n)
void leveldb_options_set_max_mem_compaction_level (leveldb_options_t *opt, int n)
void leveldb_options_set_compression (leveldb_options_t *opt, int t)
void leveldb_options_set_compression_per_level (leveldb_options_t *opt, int *level_values, size_t num_levels)
void leveldb_options_set_compression_options (leveldb_options_t *opt, int w_bits, int level, int strategy)
void leveldb_options_set_disable_data_sync (leveldb_options_t *opt, bool disable_data_sync)
void leveldb_options_set_use_fsync (leveldb_options_t *opt, bool use_fsync)
void leveldb_options_set_db_stats_log_interval (leveldb_options_t *opt, int db_stats_log_interval)
void leveldb_options_set_db_log_dir (leveldb_options_t *opt, const char *db_log_dir)
void leveldb_options_set_WAL_ttl_seconds (leveldb_options_t *opt, uint64_t ttl)
void leveldb_options_set_WAL_size_limit_MB (leveldb_options_t *opt, uint64_t limit)
leveldb_comparator_t * leveldb_comparator_create (void *state, void(*destructor)(void *), int(*compare)(void *, const char *a, size_t alen, const char *b, size_t blen), const char *(*name)(void *))
void leveldb_comparator_destroy (leveldb_comparator_t *cmp)
leveldb_filterpolicy_t * leveldb_filterpolicy_create (void *state, void(*destructor)(void *), char *(*create_filter)(void *, const char *const *key_array, const size_t *key_length_array, int num_keys, size_t *filter_length), unsigned char(*key_may_match)(void *, const char *key, size_t length, const char *filter, size_t filter_length), const char *(*name)(void *))
void leveldb_filterpolicy_destroy (leveldb_filterpolicy_t *filter)
leveldb_filterpolicy_t * leveldb_filterpolicy_create_bloom (int bits_per_key)
leveldb_readoptions_t * leveldb_readoptions_create ()
void leveldb_readoptions_destroy (leveldb_readoptions_t *opt)
void leveldb_readoptions_set_verify_checksums (leveldb_readoptions_t *opt, unsigned char v)
void leveldb_readoptions_set_fill_cache (leveldb_readoptions_t *opt, unsigned char v)
void leveldb_readoptions_set_snapshot (leveldb_readoptions_t *opt, const leveldb_snapshot_t *snap)
leveldb_writeoptions_t * leveldb_writeoptions_create ()
void leveldb_writeoptions_destroy (leveldb_writeoptions_t *opt)
void leveldb_writeoptions_set_sync (leveldb_writeoptions_t *opt, unsigned char v)
leveldb_cache_t * leveldb_cache_create_lru (size_t capacity)
void leveldb_cache_destroy (leveldb_cache_t *cache)
leveldb_env_t * leveldb_create_default_env ()
void leveldb_env_destroy (leveldb_env_t *env)
Function Documentation
static char* CopyString (const std::string & str) static
Definition at line 151 of file c.cc.
Referenced by leveldb_get().
{
   char* result = reinterpret_cast<char*>(malloc(sizeof(char) * str.size()));
   memcpy(result, str.data(), sizeof(char) * str.size());
   return result;
 }
void leveldb_approximate_sizes (leveldb_t * db, int num_ranges, const char *const * range_start_key, const size_t * range_start_key_len, const char *const * range_limit_key, const size_t * range_limit_key_len, uint64_t * sizes)
Definition at line 257 of file c.cc.
References rocksdb::DB::GetApproximateSizes(), rocksdb::Range::limit, leveldb_t::rep, and rocksdb::Range::start.
Referenced by main().
                      {
   Range* ranges = new Range[num_ranges];
   for (int i = 0; i < num_ranges; i++) {
     ranges[i].start = Slice(range_start_key[i], range_start_key_len[i]);
     ranges[i].limit = Slice(range_limit_key[i], range_limit_key_len[i]);
   }
   db->rep->GetApproximateSizes(ranges, num_ranges, sizes);
   delete[] ranges;
 }
leveldb_cache_t* leveldb_cache_create_lru (size_t capacity)
Definition at line 669 of file c.cc.
References rocksdb::NewLRUCache(), and leveldb_cache_t::rep.
Referenced by main().
{
   leveldb_cache_t* c = new leveldb_cache_t;
   c->rep = NewLRUCache(capacity);
   return c;
 }
void leveldb_cache_destroy (leveldb_cache_t * cache)
Definition at line 675 of file c.cc.
Referenced by main().
{
   delete cache;
 }
void leveldb_close (leveldb_t * db)
Definition at line 170 of file c.cc.
References db, and leveldb_t::rep.
Referenced by main().
{
   delete db->rep;
   delete db;
 }
void leveldb_compact_range (leveldb_t * db, const char * start_key, size_t start_key_len, const char * limit_key, size_t limit_key_len)
Definition at line 272 of file c.cc.
References rocksdb::DB::CompactRange(), and leveldb_t::rep.
Referenced by main().
{
   Slice a, b;
   db->rep->CompactRange(
       // Pass NULL Slice if corresponding "const char*" is NULL
       (start_key ? (a = Slice(start_key, start_key_len), &a) : NULL),
       (limit_key ? (b = Slice(limit_key, limit_key_len), &b) : NULL));
 }
leveldb_comparator_t* leveldb_comparator_create (void * state, void(*)(void *) destructor, int(*)(void *, const char *a, size_t alen, const char *b, size_t blen) compare, const char *(*)(void *) name)
Definition at line 562 of file c.cc.
References ripple::compare(), leveldb_comparator_t::compare_, leveldb_comparator_t::destructor_, name, leveldb_comparator_t::name_, and leveldb_comparator_t::state_.
Referenced by main().
{
   leveldb_comparator_t* result = new leveldb_comparator_t;
   result->state_ = state;
   result->destructor_ = destructor;
   result->compare_ = compare;
   result->name_ = name;
   return result;
 }
void leveldb_comparator_destroy (leveldb_comparator_t * cmp)
Definition at line 578 of file c.cc.
Referenced by main().
{
   delete cmp;
 }
leveldb_env_t* leveldb_create_default_env ()
Definition at line 679 of file c.cc.
References leveldb_env_t::is_default, and leveldb_env_t::rep.
Referenced by main().
{
   leveldb_env_t* result = new leveldb_env_t;
   result->rep = Env::Default();
   result->is_default = true;
   return result;
 }
leveldb_iterator_t* leveldb_create_iterator (leveldb_t * db, const leveldb_readoptions_t * options)
Definition at line 223 of file c.cc.
References rocksdb::DB::NewIterator(), leveldb_t::rep, leveldb_iterator_t::rep, and leveldb_readoptions_t::rep.
Referenced by main().
{
   leveldb_iterator_t* result = new leveldb_iterator_t;
   result->rep = db->rep->NewIterator(options->rep);
   return result;
 }
const leveldb_snapshot_t* leveldb_create_snapshot (leveldb_t * db)
Definition at line 231 of file c.cc.
References rocksdb::DB::GetSnapshot(), leveldb_t::rep, and leveldb_snapshot_t::rep.
Referenced by main().
                    {
   leveldb_snapshot_t* result = new leveldb_snapshot_t;
   result->rep = db->rep->GetSnapshot();
   return result;
 }
void leveldb_delete (leveldb_t * db, const leveldb_writeoptions_t * options, const char * key, size_t keylen, char ** errptr)
Definition at line 185 of file c.cc.
References rocksdb::DB::Delete(), leveldb_t::rep, leveldb_writeoptions_t::rep, and SaveError().
Referenced by main().
                    {
   SaveError(errptr, db->rep->Delete(options->rep, Slice(key, keylen)));
 }
void leveldb_destroy_db (const leveldb_options_t * options, const char * name, char ** errptr)
Definition at line 283 of file c.cc.
References rocksdb::DestroyDB(), leveldb_options_t::rep, and SaveError().
Referenced by main().
                    {
   SaveError(errptr, DestroyDB(name, options->rep));
 }
void leveldb_env_destroy (leveldb_env_t * env)
Definition at line 686 of file c.cc.
References env, leveldb_env_t::is_default, and leveldb_env_t::rep.
Referenced by main().
{
   if (!env->is_default) delete env->rep;
   delete env;
 }
leveldb_filterpolicy_t* leveldb_filterpolicy_create (void * state, void(*)(void *) destructor, char *(*)(void *, const char *const *key_array, const size_t *key_length_array, int num_keys, size_t *filter_length) create_filter, unsigned char(*)(void *, const char *key, size_t length, const char *filter, size_t filter_length) key_may_match, const char *(*)(void *) name)
Definition at line 582 of file c.cc.
References leveldb_filterpolicy_t::create_, leveldb_filterpolicy_t::destructor_, leveldb_filterpolicy_t::key_match_, name, leveldb_filterpolicy_t::name_, and leveldb_filterpolicy_t::state_.
Referenced by main().
{
   leveldb_filterpolicy_t* result = new leveldb_filterpolicy_t;
   result->state_ = state;
   result->destructor_ = destructor;
   result->create_ = create_filter;
   result->key_match_ = key_may_match;
   result->name_ = name;
   return result;
 }
leveldb_filterpolicy_t* leveldb_filterpolicy_create_bloom (int bits_per_key)
Definition at line 608 of file c.cc.
References leveldb_filterpolicy_t::CreateFilter(), leveldb_filterpolicy_t::KeyMayMatch(), leveldb_filterpolicy_t::Name(), and rocksdb::NewBloomFilterPolicy().
Referenced by main().
{
   // Make a leveldb_filterpolicy_t, but override all of its methods so
   // they delegate to a NewBloomFilterPolicy() instead of user
   // supplied C functions.
   struct Wrapper : public leveldb_filterpolicy_t {
     const FilterPolicy* rep_;
     ~Wrapper() { delete rep_; }
     const char* Name() const { return rep_->Name(); }
     void CreateFilter(const Slice* keys, int n, std::string* dst) const {
       return rep_->CreateFilter(keys, n, dst);
     }
     bool KeyMayMatch(const Slice& key, const Slice& filter) const {
       return rep_->KeyMayMatch(key, filter);
     }
     static void DoNothing(void*) { }
   };
   Wrapper* wrapper = new Wrapper;
   wrapper->rep_ = NewBloomFilterPolicy(bits_per_key);
   wrapper->state_ = NULL;
   wrapper->destructor_ = &Wrapper::DoNothing;
   return wrapper;
 }
void leveldb_filterpolicy_destroy (leveldb_filterpolicy_t * filter)
Definition at line 604 of file c.cc.
Referenced by main().
{
   delete filter;
 }
char* leveldb_get (leveldb_t * db, const leveldb_readoptions_t * options, const char * key, size_t keylen, size_t * vallen, char ** errptr)
Definition at line 202 of file c.cc.
References CopyString(), rocksdb::DB::Get(), rocksdb::Status::IsNotFound(), rocksdb::Status::ok(), leveldb_t::rep, leveldb_readoptions_t::rep, and SaveError().
Referenced by CheckGet().
                    {
   char* result = NULL;
   std::string tmp;
   Status s = db->rep->Get(options->rep, Slice(key, keylen), &tmp);
   if (s.ok()) {
     *vallen = tmp.size();
     result = CopyString(tmp);
   } else {
     *vallen = 0;
     if (!s.IsNotFound()) {
       SaveError(errptr, s);
     }
   }
   return result;
 }
void leveldb_iter_destroy (leveldb_iterator_t * iter)
Definition at line 297 of file c.cc.
References leveldb_iterator_t::rep.
Referenced by main().
{
   delete iter->rep;
   delete iter;
 }
void leveldb_iter_get_error (const leveldb_iterator_t * iter, char ** errptr)
Definition at line 338 of file c.cc.
References leveldb_iterator_t::rep, SaveError(), and rocksdb::Iterator::status().
Referenced by main().
{
   SaveError(errptr, iter->rep->status());
 }
const char* leveldb_iter_key (const leveldb_iterator_t * iter, size_t * klen)
Definition at line 326 of file c.cc.
References rocksdb::Slice::data(), rocksdb::Iterator::key(), leveldb_iterator_t::rep, and rocksdb::Slice::size().
Referenced by CheckIter().
{
   Slice s = iter->rep->key();
   *klen = s.size();
   return s.data();
 }
void leveldb_iter_next (leveldb_iterator_t * iter)
Definition at line 318 of file c.cc.
References rocksdb::Iterator::Next(), and leveldb_iterator_t::rep.
Referenced by main().
{
   iter->rep->Next();
 }
void leveldb_iter_prev (leveldb_iterator_t * iter)
Definition at line 322 of file c.cc.
References rocksdb::Iterator::Prev(), and leveldb_iterator_t::rep.
Referenced by main().
{
   iter->rep->Prev();
 }
void leveldb_iter_seek (leveldb_iterator_t * iter, const char * k, size_t klen)
Definition at line 314 of file c.cc.
References leveldb_iterator_t::rep, and rocksdb::Iterator::Seek().
Referenced by main().
{
   iter->rep->Seek(Slice(k, klen));
 }
void leveldb_iter_seek_to_first (leveldb_iterator_t * iter)
Definition at line 306 of file c.cc.
References leveldb_iterator_t::rep, and rocksdb::Iterator::SeekToFirst().
Referenced by main().
{
   iter->rep->SeekToFirst();
 }
void leveldb_iter_seek_to_last (leveldb_iterator_t * iter)
Definition at line 310 of file c.cc.
References leveldb_iterator_t::rep, and rocksdb::Iterator::SeekToLast().
Referenced by main().
{
   iter->rep->SeekToLast();
 }
unsigned char leveldb_iter_valid (const leveldb_iterator_t * iter)
Definition at line 302 of file c.cc.
References leveldb_iterator_t::rep, and rocksdb::Iterator::Valid().
Referenced by main().
{
   return iter->rep->Valid();
 }
const char* leveldb_iter_value (const leveldb_iterator_t * iter, size_t * vlen)
Definition at line 332 of file c.cc.
References rocksdb::Slice::data(), leveldb_iterator_t::rep, rocksdb::Slice::size(), and rocksdb::Iterator::value().
Referenced by CheckIter().
{
   Slice s = iter->rep->value();
   *vlen = s.size();
   return s.data();
 }
leveldb_t* leveldb_open (const leveldb_options_t * options, const char * name, char ** errptr)
Definition at line 157 of file c.cc.
References db, leveldb_t::rep, leveldb_options_t::rep, and SaveError().
Referenced by main().
                    {
   DB* db;
   if (SaveError(errptr, DB::Open(options->rep, std::string(name), &db))) {
     return NULL;
   }
   leveldb_t* result = new leveldb_t;
   result->rep = db;
   return result;
 }
leveldb_options_t* leveldb_options_create ()
Definition at line 391 of file c.cc.
Referenced by main().
{
   return new leveldb_options_t;
 }
void leveldb_options_destroy (leveldb_options_t * options)
Definition at line 395 of file c.cc.
Referenced by main().
{
   delete options;
 }
void leveldb_options_set_block_restart_interval (leveldb_options_t * opt, int n)
Definition at line 454 of file c.cc.
References rocksdb::Options::block_restart_interval, and leveldb_options_t::rep.
Referenced by main().
{
   opt->rep.block_restart_interval = n;
 }
void leveldb_options_set_block_size (leveldb_options_t * opt, size_t s)
Definition at line 450 of file c.cc.
References rocksdb::Options::block_size, and leveldb_options_t::rep.
Referenced by main().
{
   opt->rep.block_size = s;
 }
void leveldb_options_set_cache (leveldb_options_t * opt, leveldb_cache_t * c)
Definition at line 444 of file c.cc.
References rocksdb::Options::block_cache, leveldb_options_t::rep, and leveldb_cache_t::rep.
Referenced by main().
{
   if (c) {
     opt->rep.block_cache = c->rep;
   }
 }
void leveldb_options_set_comparator (leveldb_options_t * opt, leveldb_comparator_t * cmp)
Definition at line 399 of file c.cc.
References rocksdb::Options::comparator, and leveldb_options_t::rep.
Referenced by main().
{
   opt->rep.comparator = cmp;
 }
void leveldb_options_set_compression (leveldb_options_t * opt, int t)
Definition at line 512 of file c.cc.
References rocksdb::Options::compression, and leveldb_options_t::rep.
Referenced by main().
{
   opt->rep.compression = static_cast<CompressionType>(t);
 }
void leveldb_options_set_compression_options (leveldb_options_t * opt, int w_bits, int level, int strategy)
Definition at line 526 of file c.cc.
References rocksdb::Options::compression_opts, rocksdb::CompressionOptions::level, leveldb_options_t::rep, rocksdb::CompressionOptions::strategy, and rocksdb::CompressionOptions::window_bits.
Referenced by main().
{
   opt->rep.compression_opts.window_bits = w_bits;
   opt->rep.compression_opts.level = level;
   opt->rep.compression_opts.strategy = strategy;
 }
void leveldb_options_set_compression_per_level (leveldb_options_t * opt, int * level_values, size_t num_levels)
Definition at line 516 of file c.cc.
References rocksdb::Options::compression_per_level, and leveldb_options_t::rep.
Referenced by main().
{
   opt->rep.compression_per_level.resize(num_levels);
   for (size_t i = 0; i < num_levels; ++i) {
     opt->rep.compression_per_level[i] =
       static_cast<CompressionType>(level_values[i]);
   }
 }
void leveldb_options_set_create_if_missing (leveldb_options_t * opt, unsigned char v)
Definition at line 411 of file c.cc.
References rocksdb::Options::create_if_missing, and leveldb_options_t::rep.
Referenced by main().
{
   opt->rep.create_if_missing = v;
 }
void leveldb_options_set_db_log_dir (leveldb_options_t * opt, const char * db_log_dir)
Definition at line 548 of file c.cc.
References rocksdb::Options::db_log_dir, and leveldb_options_t::rep.
{
   opt->rep.db_log_dir = db_log_dir;
 }
void leveldb_options_set_db_stats_log_interval (leveldb_options_t * opt, int db_stats_log_interval)
Definition at line 543 of file c.cc.
References rocksdb::Options::db_stats_log_interval, and leveldb_options_t::rep.
{
   opt->rep.db_stats_log_interval = db_stats_log_interval;
 }
void leveldb_options_set_disable_data_sync (leveldb_options_t * opt, bool disable_data_sync)
Definition at line 533 of file c.cc.
References rocksdb::Options::disableDataSync, and leveldb_options_t::rep.
{
   opt->rep.disableDataSync = disable_data_sync;
 }
void leveldb_options_set_env (leveldb_options_t * opt, leveldb_env_t * env)
Definition at line 426 of file c.cc.
References rocksdb::Options::env, leveldb_options_t::rep, and leveldb_env_t::rep.
Referenced by main().
{
   opt->rep.env = (env ? env->rep : NULL);
 }
void leveldb_options_set_error_if_exists (leveldb_options_t * opt, unsigned char v)
Definition at line 416 of file c.cc.
References rocksdb::Options::error_if_exists, and leveldb_options_t::rep.
Referenced by main().
{
   opt->rep.error_if_exists = v;
 }
void leveldb_options_set_expanded_compaction_factor (leveldb_options_t * opt, int n)
Definition at line 478 of file c.cc.
References rocksdb::Options::expanded_compaction_factor, and leveldb_options_t::rep.
{
   opt->rep.expanded_compaction_factor = n;
 }
void leveldb_options_set_filter_policy (leveldb_options_t * opt, leveldb_filterpolicy_t * policy)
Definition at line 405 of file c.cc.
References rocksdb::Options::filter_policy, and leveldb_options_t::rep.
Referenced by main().
{
   opt->rep.filter_policy = policy;
 }
void leveldb_options_set_info_log (leveldb_options_t * opt, leveldb_logger_t * l)
Definition at line 430 of file c.cc.
References rocksdb::Options::info_log, leveldb_options_t::rep, and leveldb_logger_t::rep.
Referenced by main().
{
   if (l) {
     opt->rep.info_log = l->rep;
   }
 }
void leveldb_options_set_level0_file_num_compaction_trigger (leveldb_options_t * opt, int n)
Definition at line 492 of file c.cc.
References rocksdb::Options::level0_file_num_compaction_trigger, and leveldb_options_t::rep.
{
   opt->rep.level0_file_num_compaction_trigger = n;
 }
void leveldb_options_set_level0_slowdown_writes_trigger (leveldb_options_t * opt, int n)
Definition at line 497 of file c.cc.
References rocksdb::Options::level0_slowdown_writes_trigger, and leveldb_options_t::rep.
{
   opt->rep.level0_slowdown_writes_trigger = n;
 }
void leveldb_options_set_level0_stop_writes_trigger (leveldb_options_t * opt, int n)
Definition at line 502 of file c.cc.
References rocksdb::Options::level0_stop_writes_trigger, and leveldb_options_t::rep.
{
   opt->rep.level0_stop_writes_trigger = n;
 }
void leveldb_options_set_max_bytes_for_level_base (leveldb_options_t * opt, uint64_t n)
Definition at line 468 of file c.cc.
References rocksdb::Options::max_bytes_for_level_base, and leveldb_options_t::rep.
{
   opt->rep.max_bytes_for_level_base = n;
 }
void leveldb_options_set_max_bytes_for_level_multiplier (leveldb_options_t * opt, int n)
Definition at line 473 of file c.cc.
References rocksdb::Options::max_bytes_for_level_multiplier, and leveldb_options_t::rep.
{
   opt->rep.max_bytes_for_level_multiplier = n;
 }
void leveldb_options_set_max_grandparent_overlap_factor (leveldb_options_t * opt, int n)
Definition at line 483 of file c.cc.
References rocksdb::Options::max_grandparent_overlap_factor, and leveldb_options_t::rep.
{
   opt->rep.max_grandparent_overlap_factor = n;
 }
void leveldb_options_set_max_mem_compaction_level (leveldb_options_t * opt, int n)
Definition at line 507 of file c.cc.
References rocksdb::Options::max_mem_compaction_level, and leveldb_options_t::rep.
{
   opt->rep.max_mem_compaction_level = n;
 }
void leveldb_options_set_max_open_files (leveldb_options_t * opt, int n)
Definition at line 440 of file c.cc.
References rocksdb::Options::max_open_files, and leveldb_options_t::rep.
Referenced by main().
{
   opt->rep.max_open_files = n;
 }
void leveldb_options_set_num_levels (leveldb_options_t * opt, int n)
Definition at line 488 of file c.cc.
References rocksdb::Options::num_levels, and leveldb_options_t::rep.
{
   opt->rep.num_levels = n;
 }
void leveldb_options_set_paranoid_checks (leveldb_options_t * opt, unsigned char v)
Definition at line 421 of file c.cc.
References rocksdb::Options::paranoid_checks, and leveldb_options_t::rep.
Referenced by main().
{
   opt->rep.paranoid_checks = v;
 }
void leveldb_options_set_target_file_size_base (leveldb_options_t * opt, uint64_t n)
Definition at line 458 of file c.cc.
References leveldb_options_t::rep, and rocksdb::Options::target_file_size_base.
{
   opt->rep.target_file_size_base = n;
 }
void leveldb_options_set_target_file_size_multiplier (leveldb_options_t * opt, int n)
Definition at line 463 of file c.cc.
References leveldb_options_t::rep, and rocksdb::Options::target_file_size_multiplier.
{
   opt->rep.target_file_size_multiplier = n;
 }
void leveldb_options_set_use_fsync (leveldb_options_t * opt, bool use_fsync)
Definition at line 538 of file c.cc.
References leveldb_options_t::rep, and rocksdb::Options::use_fsync.
{
   opt->rep.use_fsync = use_fsync;
 }
void leveldb_options_set_WAL_size_limit_MB (leveldb_options_t * opt, uint64_t limit)
Definition at line 557 of file c.cc.
References leveldb_options_t::rep, and rocksdb::Options::WAL_size_limit_MB.
{
   opt->rep.WAL_size_limit_MB = limit;
 }
void leveldb_options_set_WAL_ttl_seconds (leveldb_options_t * opt, uint64_t ttl)
Definition at line 553 of file c.cc.
References leveldb_options_t::rep, and rocksdb::Options::WAL_ttl_seconds.
{
   opt->rep.WAL_ttl_seconds = ttl;
 }
void leveldb_options_set_write_buffer_size (leveldb_options_t * opt, size_t s)
Definition at line 436 of file c.cc.
References leveldb_options_t::rep, and rocksdb::Options::write_buffer_size.
Referenced by main().
{
   opt->rep.write_buffer_size = s;
 }
char* leveldb_property_value (leveldb_t * db, const char * propname)
Definition at line 245 of file c.cc.
References rocksdb::DB::GetProperty(), and leveldb_t::rep.
Referenced by main().
{
   std::string tmp;
   if (db->rep->GetProperty(Slice(propname), &tmp)) {
     // We use strdup() since we expect human readable output.
     return strdup(tmp.c_str());
   } else {
     return NULL;
   }
 }
void leveldb_put (leveldb_t * db, const leveldb_writeoptions_t * options, const char * key, size_t keylen, const char * val, size_t vallen, char ** errptr)
Definition at line 175 of file c.cc.
References rocksdb::DB::Put(), leveldb_t::rep, leveldb_writeoptions_t::rep, and SaveError().
Referenced by main().
                    {
   SaveError(errptr,
             db->rep->Put(options->rep, Slice(key, keylen), Slice(val, vallen)));
 }
leveldb_readoptions_t* leveldb_readoptions_create ()
Definition at line 631 of file c.cc.
Referenced by main().
{
   return new leveldb_readoptions_t;
 }
void leveldb_readoptions_destroy (leveldb_readoptions_t * opt)
Definition at line 635 of file c.cc.
Referenced by main().
{
   delete opt;
 }
void leveldb_readoptions_set_fill_cache (leveldb_readoptions_t * opt, unsigned char v)
Definition at line 645 of file c.cc.
References rocksdb::ReadOptions::fill_cache, and leveldb_readoptions_t::rep.
Referenced by main().
{
   opt->rep.fill_cache = v;
 }
void leveldb_readoptions_set_snapshot (leveldb_readoptions_t * opt, const leveldb_snapshot_t * snap)
Definition at line 650 of file c.cc.
References leveldb_snapshot_t::rep, leveldb_readoptions_t::rep, and rocksdb::ReadOptions::snapshot.
Referenced by main().
{
   opt->rep.snapshot = (snap ? snap->rep : NULL);
 }
void leveldb_readoptions_set_verify_checksums (leveldb_readoptions_t * opt, unsigned char v)
Definition at line 639 of file c.cc.
References leveldb_readoptions_t::rep, and rocksdb::ReadOptions::verify_checksums.
Referenced by main().
                      {
   opt->rep.verify_checksums = v;
 }
void leveldb_release_snapshot (leveldb_t * db, const leveldb_snapshot_t * snapshot)
Definition at line 238 of file c.cc.
References rocksdb::DB::ReleaseSnapshot(), leveldb_t::rep, and leveldb_snapshot_t::rep.
Referenced by main().
{
   db->rep->ReleaseSnapshot(snapshot->rep);
   delete snapshot;
 }
void leveldb_repair_db (const leveldb_options_t * options, const char * name, char ** errptr)
Definition at line 290 of file c.cc.
References leveldb_options_t::rep, rocksdb::RepairDB(), and SaveError().
Referenced by main().
                    {
   SaveError(errptr, RepairDB(name, options->rep));
 }
void leveldb_write (leveldb_t * db, const leveldb_writeoptions_t * options, leveldb_writebatch_t * batch, char ** errptr)
Definition at line 194 of file c.cc.
References leveldb_t::rep, leveldb_writebatch_t::rep, leveldb_writeoptions_t::rep, SaveError(), and rocksdb::DB::Write().
Referenced by main().
                    {
   SaveError(errptr, db->rep->Write(options->rep, &batch->rep));
 }
void leveldb_writebatch_clear (leveldb_writebatch_t * b)
Definition at line 350 of file c.cc.
References rocksdb::WriteBatch::Clear(), and leveldb_writebatch_t::rep.
Referenced by main().
{
   b->rep.Clear();
 }
leveldb_writebatch_t* leveldb_writebatch_create ()
Definition at line 342 of file c.cc.
Referenced by main().
{
   return new leveldb_writebatch_t;
 }
void leveldb_writebatch_delete (leveldb_writebatch_t * b, const char * key, size_t klen)
Definition at line 361 of file c.cc.
References rocksdb::WriteBatch::Delete(), and leveldb_writebatch_t::rep.
Referenced by main().
{
   b->rep.Delete(Slice(key, klen));
 }
void leveldb_writebatch_destroy (leveldb_writebatch_t * b)
Definition at line 346 of file c.cc.
Referenced by main().
{
   delete b;
 }
void leveldb_writebatch_iterate (leveldb_writebatch_t * b, void * state, void(*)(void *, const char *k, size_t klen, const char *v, size_t vlen) put, void(*)(void *, const char *k, size_t klen) deleted)
Definition at line 367 of file c.cc.
References rocksdb::Slice::data(), rocksdb::WriteBatch::Iterate(), leveldb_writebatch_t::rep, rocksdb::Slice::size(), and value.
Referenced by main().
{
   class H : public WriteBatch::Handler {
    public:
     void* state_;
     void (*put_)(void*, const char* k, size_t klen, const char* v, size_t vlen);
     void (*deleted_)(void*, const char* k, size_t klen);
     virtual void Put(const Slice& key, const Slice& value) {
       (*put_)(state_, key.data(), key.size(), value.data(), value.size());
     }
     virtual void Delete(const Slice& key) {
       (*deleted_)(state_, key.data(), key.size());
     }
   };
   H handler;
   handler.state_ = state;
   handler.put_ = put;
   handler.deleted_ = deleted;
   b->rep.Iterate(&handler);
 }
void leveldb_writebatch_put (leveldb_writebatch_t * b, const char * key, size_t klen, const char * val, size_t vlen)
Definition at line 354 of file c.cc.
References rocksdb::WriteBatch::Put(), and leveldb_writebatch_t::rep.
Referenced by main().
{
   b->rep.Put(Slice(key, klen), Slice(val, vlen));
 }
leveldb_writeoptions_t* leveldb_writeoptions_create ()
Definition at line 656 of file c.cc.
Referenced by main().
{
   return new leveldb_writeoptions_t;
 }
void leveldb_writeoptions_destroy (leveldb_writeoptions_t * opt)
Definition at line 660 of file c.cc.
Referenced by main().
{
   delete opt;
 }
void leveldb_writeoptions_set_sync (leveldb_writeoptions_t * opt, unsigned char v)
Definition at line 664 of file c.cc.
References leveldb_writeoptions_t::rep, and rocksdb::WriteOptions::sync.
Referenced by main().
{
   opt->rep.sync = v;
 }
static bool SaveError (char ** errptr, const Status & s) static
Definition at line 137 of file c.cc.
References rocksdb::Status::ok(), and rocksdb::Status::ToString().
Referenced by leveldb_delete(), leveldb_destroy_db(), leveldb_get(), leveldb_iter_get_error(), leveldb_open(), leveldb_put(), leveldb_repair_db(), and leveldb_write().
{
   assert(errptr != NULL);
   if (s.ok()) {
     return false;
   } else if (*errptr == NULL) {
     *errptr = strdup(s.ToString().c_str());
   } else {
     // TODO(sanjay): Merge with existing error?
     free(*errptr);
     *errptr = strdup(s.ToString().c_str());
   }
   return true;
 }