rippled: beast::SpinLock Class Reference
beast::SpinLock Class Reference
#include <SpinLock.h>
Public Types
typedef std::lock_guard< SpinLock > ScopedLockType
typedef UnlockGuard< SpinLock > ScopedUnlockType
Public Member Functions
SpinLock () noexcept
~SpinLock () noexcept
void enter () const noexcept
bool tryEnter () const noexcept
void exit () const noexcept
void lock () const
void unlock () const
bool try_lock () const
Private Attributes
Atomic< int > m_lock
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
A simple spin-lock class that can be used as a simple, low-overhead mutex for uncontended situations.
Note that unlike a CriticalSection, this type of lock is not re-entrant, and may be less efficient when used it a highly contended situation, but it's very small and requires almost no initialisation. It's most appropriate for simple situations where you're only going to hold the lock for a very brief time.
See Also
CriticalSection
Definition at line 47 of file SpinLock.h.
Member Typedef Documentation
typedef std::lock_guard<SpinLock> beast::SpinLock::ScopedLockType
Provides the type of scoped lock to use for locking a SpinLock.
Definition at line 51 of file SpinLock.h.
typedef UnlockGuard<SpinLock> beast::SpinLock::ScopedUnlockType
Provides the type of scoped unlocker to use with a SpinLock.
Definition at line 54 of file SpinLock.h.
Constructor & Destructor Documentation
beast::SpinLock::SpinLock () inline noexcept
Definition at line 56 of file SpinLock.h.
 {}
beast::SpinLock::~SpinLock () inline noexcept
Definition at line 57 of file SpinLock.h.
 {}
Member Function Documentation
void beast::SpinLock::enter () const noexcept
Acquires the lock. This will block until the lock has been successfully acquired by this thread. Note that a SpinLock is NOT re-entrant, and is not smart enough to know whether the caller thread already has the lock - so if a thread tries to acquire a lock that it already holds, this method will never return!
It's strongly recommended that you never call this method directly - instead use the ScopedLockType class to manage the locking using an RAII pattern instead.
Definition at line 275 of file Thread.cpp.
References tryEnter(), and beast::Thread::yield().
Referenced by lock().
 {
     if (! tryEnter())
     {
         for (int i = 20; --i >= 0;)
             if (tryEnter())
                 return;
         while (! tryEnter())
             Thread::yield();
     }
 }
void beast::SpinLock::exit () const inline noexcept
Releases the lock.
Definition at line 77 of file SpinLock.h.
References bassert, m_lock, and beast::Atomic< Type >::value.
Referenced by unlock().
     {
         bassert (m_lock.value == 1); // Agh! Releasing a lock that isn't currently held!
         m_lock = 0;
     }
void beast::SpinLock::lock () const inline
Definition at line 83 of file SpinLock.h.
References enter().
         { enter(); }
bool beast::SpinLock::try_lock () const inline
Definition at line 87 of file SpinLock.h.
References tryEnter().
         { return tryEnter(); }
bool beast::SpinLock::tryEnter () const inline noexcept
Attempts to acquire the lock, returning true if this was successful.
Definition at line 71 of file SpinLock.h.
References beast::Atomic< Type >::compareAndSetBool(), and m_lock.
Referenced by enter(), and try_lock().
     {
         return m_lock.compareAndSetBool (1, 0);
     }
void beast::SpinLock::unlock () const inline
Definition at line 85 of file SpinLock.h.
References exit().
         { exit(); }
Member Data Documentation
Atomic<int> beast::SpinLock::m_lock mutable private
Definition at line 92 of file SpinLock.h.
Referenced by exit(), and tryEnter().
The documentation for this class was generated from the following files:
rippled/src/beast/beast/threads/SpinLock.h
rippled/src/beast/beast/threads/impl/Thread.cpp