rippled: ripple::FeeVoteImpl Class Reference
ripple::FeeVoteImpl Class Reference
Classes
class VotableInteger
Public Member Functions
FeeVoteImpl (std::uint64_t targetBaseFee, std::uint32_t targetReserveBase, std::uint32_t targetReserveIncrement, beast::Journal journal)
void doValidation (Ledger::ref lastClosedLedger, STObject &baseValidation) override
void doVoting (Ledger::ref lastClosedLedger, SHAMap::ref initialPosition) override
Public Member Functions inherited from ripple::FeeVote
virtual ~FeeVote ()
Private Attributes
std::uint64_t mTargetBaseFee
std::uint32_t mTargetReserveBase
std::uint32_t mTargetReserveIncrement
beast::Journal m_journal
Detailed Description
Definition at line 24 of file FeeVoteImpl.cpp.
Constructor & Destructor Documentation
ripple::FeeVoteImpl::FeeVoteImpl (std::uint64_t targetBaseFee, std::uint32_t targetReserveBase, std::uint32_t targetReserveIncrement, beast::Journal journal) inline
Definition at line 88 of file FeeVoteImpl.cpp.
         : mTargetBaseFee (targetBaseFee)
         , mTargetReserveBase (targetReserveBase)
         , mTargetReserveIncrement (targetReserveIncrement)
         , m_journal (journal)
     {
     }
Member Function Documentation
void ripple::FeeVoteImpl::doValidation (Ledger::ref lastClosedLedger, STObject & baseValidation) inline override virtual
Add local fee preference to validation.
Parameters
lastClosedLedger
baseValidation
Implements ripple::FeeVote.
Definition at line 100 of file FeeVoteImpl.cpp.
References beast::Journal::info, m_journal, mTargetBaseFee, mTargetReserveBase, mTargetReserveIncrement, ripple::STObject::setFieldU32(), and ripple::STObject::setFieldU64().
     {
         if (lastClosedLedger->getBaseFee () != mTargetBaseFee)
         {
             if (m_journal.info) m_journal.info <<
                 "Voting for base fee of " << mTargetBaseFee;
             baseValidation.setFieldU64 (sfBaseFee, mTargetBaseFee);
         }
         if (lastClosedLedger->getReserve (0) != mTargetReserveBase)
         {
             if (m_journal.info) m_journal.info <<
                 "Voting for base resrve of " << mTargetReserveBase;
             baseValidation.setFieldU32(sfReserveBase, mTargetReserveBase);
         }
         if (lastClosedLedger->getReserveInc () != mTargetReserveIncrement)
         {
             if (m_journal.info) m_journal.info <<
                 "Voting for reserve increment of " << mTargetReserveIncrement;
             baseValidation.setFieldU32 (sfReserveIncrement, mTargetReserveIncrement);
         }
     }
void ripple::FeeVoteImpl::doVoting (Ledger::ref lastClosedLedger, SHAMap::ref initialPosition) inline override virtual
Cast our local vote on the fee.
Parameters
lastClosedLedger
initialPosition
Implements ripple::FeeVote.
Definition at line 130 of file FeeVoteImpl.cpp.
References ripple::STObject::add(), ripple::getApp(), ripple::STObject::getFieldU32(), ripple::STObject::getFieldU64(), ripple::SerializedTransaction::getTransactionID(), ripple::Validations::getValidations(), ripple::Application::getValidations(), ripple::STObject::isFieldPresent(), ripple::SerializedValidation::isTrusted(), m_journal, mTargetBaseFee, mTargetReserveBase, mTargetReserveIncrement, ripple::Serializer::peekData(), ripple::STObject::setFieldAccount(), ripple::STObject::setFieldU32(), ripple::STObject::setFieldU64(), ripple::ttFEE, and beast::Journal::warning.
     {
         // LCL must be flag ledger
         assert ((lastClosedLedger->getLedgerSeq () % 256) == 0);
         VotableInteger<std::uint64_t> baseFeeVote (lastClosedLedger->getBaseFee (), mTargetBaseFee);
         VotableInteger<std::uint32_t> baseReserveVote (lastClosedLedger->getReserve (0), mTargetReserveBase);
         VotableInteger<std::uint32_t> incReserveVote (lastClosedLedger->getReserveInc (), mTargetReserveIncrement);
         // get validations for ledger before flag
         ValidationSet set = getApp().getValidations ().getValidations (lastClosedLedger->getParentHash ());
         for (auto const& e : set)
         {
             SerializedValidation const& val = *e.second;
             if (val.isTrusted ())
             {
                 if (val.isFieldPresent (sfBaseFee))
                 {
                     baseFeeVote.addVote (val.getFieldU64 (sfBaseFee));
                 }
                 else
                 {
                     baseFeeVote.noVote ();
                 }
                 if (val.isFieldPresent (sfReserveBase))
                 {
                     baseReserveVote.addVote (val.getFieldU32 (sfReserveBase));
                 }
                 else
                 {
                     baseReserveVote.noVote ();
                 }
                 if (val.isFieldPresent (sfReserveIncrement))
                 {
                     incReserveVote.addVote (val.getFieldU32 (sfReserveIncrement));
                 }
                 else
                 {
                     incReserveVote.noVote ();
                 }
             }
         }
         // choose our positions
         std::uint64_t baseFee = baseFeeVote.getVotes ();
         std::uint32_t baseReserve = baseReserveVote.getVotes ();
         std::uint32_t incReserve = incReserveVote.getVotes ();
         // add transactions to our position
         if ((baseFee != lastClosedLedger->getBaseFee ()) ||
                 (baseReserve != lastClosedLedger->getReserve (0)) ||
                 (incReserve != lastClosedLedger->getReserveInc ()))
         {
             if (m_journal.warning) m_journal.warning <<
                 "We are voting for a fee change: " << baseFee <<
                 "/" << baseReserve <<
                 "/" << incReserve;
             SerializedTransaction trans (ttFEE);
             trans.setFieldAccount (sfAccount, uint160 ());
             trans.setFieldU64 (sfBaseFee, baseFee);
             trans.setFieldU32 (sfReferenceFeeUnits, 10);
             trans.setFieldU32 (sfReserveBase, baseReserve);
             trans.setFieldU32 (sfReserveIncrement, incReserve);
             uint256 txID = trans.getTransactionID ();
             if (m_journal.warning) m_journal.warning <<
                 "Vote: " << txID;
             Serializer s;
             trans.add (s, true);
             SHAMapItem::pointer tItem = boost::make_shared<SHAMapItem> (txID, s.peekData ());
             if (!initialPosition->addGiveItem (tItem, true, false))
             {
                 if (m_journal.warning) m_journal.warning <<
                     "Ledger already had fee change";
             }
         }
     }
Member Data Documentation
beast::Journal ripple::FeeVoteImpl::m_journal private
Definition at line 220 of file FeeVoteImpl.cpp.
Referenced by doValidation(), and doVoting().
std::uint64_t ripple::FeeVoteImpl::mTargetBaseFee private
Definition at line 217 of file FeeVoteImpl.cpp.
Referenced by doValidation(), and doVoting().
std::uint32_t ripple::FeeVoteImpl::mTargetReserveBase private
Definition at line 218 of file FeeVoteImpl.cpp.
Referenced by doValidation(), and doVoting().
std::uint32_t ripple::FeeVoteImpl::mTargetReserveIncrement private
Definition at line 219 of file FeeVoteImpl.cpp.
Referenced by doValidation(), and doVoting().
The documentation for this class was generated from the following file:
rippled/src/ripple_app/misc/FeeVoteImpl.cpp