rippled: beast::ScopedWrapperContext< Context, ScopedType > Class Template Reference
beast::ScopedWrapperContext< Context, ScopedType > Class Template Reference
#include <ScopedWrapperContext.h>
Classes
class Scope
Public Types
typedef Context context_type
typedef ScopedType scoped_type
Public Member Functions
ScopedWrapperContext ()
template<typename Arg >
ScopedWrapperContext (Arg &arg)
template<typename Handler >
detail::ScopedWrapper
< ScopedType, Context, Handler > wrap (Handler const &handler)
Private Attributes
Context m_context
Detailed Description
template<typename Context, typename ScopedType>
class beast::ScopedWrapperContext< Context, ScopedType >
Helper to eliminate the template argument at call sites.
Definition at line 56 of file ScopedWrapperContext.h.
Member Typedef Documentation
template<typename Context, typename ScopedType> typedef Context beast::ScopedWrapperContext< Context, ScopedType >::context_type
Definition at line 59 of file ScopedWrapperContext.h.
template<typename Context, typename ScopedType> typedef ScopedType beast::ScopedWrapperContext< Context, ScopedType >::scoped_type
Definition at line 60 of file ScopedWrapperContext.h.
Constructor & Destructor Documentation
template<typename Context, typename ScopedType> beast::ScopedWrapperContext< Context, ScopedType >::ScopedWrapperContext () inline
Definition at line 74 of file ScopedWrapperContext.h.
         { }
template<typename Context, typename ScopedType> template<typename Arg > beast::ScopedWrapperContext< Context, ScopedType >::ScopedWrapperContext (Arg & arg) inline explicit
Definition at line 78 of file ScopedWrapperContext.h.
         : m_context (arg)
     {
     }
Member Function Documentation
template<typename Context, typename ScopedType> template<typename Handler > detail::ScopedWrapper<ScopedType, Context, Handler> beast::ScopedWrapperContext< Context, ScopedType >::wrap (Handler const & handler) inline
Definition at line 84 of file ScopedWrapperContext.h.
Referenced by ripple::PeerFinder::ManagerImp::addFallbackStrings(), ripple::PeerFinder::ManagerImp::addFixedPeer(), ripple::Validators::ManagerImp::addSource(), ripple::Validators::ManagerImp::addStaticSource(), ripple::Validators::ManagerImp::ledgerClosed(), ripple::PeerFinder::ManagerImp::onDeadlineTimer(), ripple::Validators::ManagerImp::onDeadlineTimer(), ripple::Validators::ManagerImp::onStart(), ripple::PeerFinder::ManagerImp::onStop(), ripple::Validators::ManagerImp::onStop(), ripple::Validators::ManagerImp::receiveValidation(), and ripple::PeerFinder::ManagerImp::setConfig().
     {
         return detail::ScopedWrapper <ScopedType, Context, Handler> (
             m_context, handler);
     }
Member Data Documentation
template<typename Context, typename ScopedType> Context beast::ScopedWrapperContext< Context, ScopedType >::m_context mutable private
Definition at line 92 of file ScopedWrapperContext.h.
Referenced by beast::ScopedWrapperContext< beast::RecursiveMutex, beast::RecursiveMutex::ScopedLockType >::wrap().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/threads/ScopedWrapperContext.h