rippled: rocksdb::Compaction Class Reference
rocksdb::Compaction Class Reference
#include <version_set.h>
Public Member Functions
~Compaction ()
int level () const
int output_level () const
VersionEdit * edit ()
int num_input_files (int which) const
FileMetaData * input (int which, int i) const
uint64_t MaxOutputFileSize () const
bool enable_compression () const
bool IsTrivialMove () const
void AddInputDeletions (VersionEdit *edit)
bool IsBaseLevelForKey (const Slice &user_key)
bool ShouldStopBefore (const Slice &internal_key)
void ReleaseInputs ()
void Summary (char *output, int len)
double score () const
bool BottomMostLevel ()
bool IsFullCompaction ()
Private Member Functions
Compaction (int level, int out_level, uint64_t target_file_size, uint64_t max_grandparent_overlap_bytes, int number_levels, bool seek_compaction=false, bool enable_compression=true)
void MarkFilesBeingCompacted (bool)
void SetupBottomMostLevel (bool isManual)
void ResetNextCompactionIndex ()
Private Attributes
int level_
int out_level_
uint64_t max_output_file_size_
uint64_t maxGrandParentOverlapBytes_
Version * input_version_
VersionEdit * edit_
int number_levels_
bool seek_compaction_
bool enable_compression_
std::vector< FileMetaData * > inputs_ [2]
std::vector< FileMetaData * > grandparents_
size_t grandparent_index_
bool seen_key_
uint64_t overlapped_bytes_
int base_index_
int parent_index_
double score_
bool bottommost_level_
bool is_full_compaction_
std::vector< size_t > level_ptrs_
Friends
class Version
class VersionSet
Detailed Description
Definition at line 541 of file version_set.h.
Constructor & Destructor Documentation
rocksdb::Compaction::~Compaction ()
Definition at line 2991 of file version_set.cc.
References edit_, input_version_, and rocksdb::Version::Unref().
{
   delete edit_;
   if (input_version_ != nullptr) {
     input_version_->Unref();
   }
 }
rocksdb::Compaction::Compaction (int level, int out_level, uint64_t target_file_size, uint64_t max_grandparent_overlap_bytes, int number_levels, bool seek_compaction = false, bool enable_compression = true) explicit private
Definition at line 2965 of file version_set.cc.
References edit_, level_ptrs_, and number_levels_.
     : level_(level),
       out_level_(out_level),
       max_output_file_size_(target_file_size),
       maxGrandParentOverlapBytes_(max_grandparent_overlap_bytes),
       input_version_(nullptr),
       number_levels_(number_levels),
       seek_compaction_(seek_compaction),
       enable_compression_(enable_compression),
       grandparent_index_(0),
       seen_key_(false),
       overlapped_bytes_(0),
       base_index_(-1),
       parent_index_(-1),
       score_(0),
       bottommost_level_(false),
       is_full_compaction_(false),
       level_ptrs_(std::vector<size_t>(number_levels)) {
   edit_ = new VersionEdit(number_levels_);
   for (int i = 0; i < number_levels_; i++) {
     level_ptrs_[i] = 0;
   }
 }
Member Function Documentation
void rocksdb::Compaction::AddInputDeletions (VersionEdit * edit)
Definition at line 3007 of file version_set.cc.
References rocksdb::VersionEdit::DeleteFile(), inputs_, and level_.
Referenced by rocksdb::DBImpl::InstallCompactionResults().
{
   for (int which = 0; which < 2; which++) {
     for (size_t i = 0; i < inputs_[which].size(); i++) {
       edit->DeleteFile(level_ + which, inputs_[which][i]->number);
     }
   }
 }
bool rocksdb::Compaction::BottomMostLevel () inline
Definition at line 594 of file version_set.h.
References bottommost_level_.
Referenced by rocksdb::DBImpl::DoCompactionWork().
 { return bottommost_level_; }
VersionEdit* rocksdb::Compaction::edit () inline
Definition at line 554 of file version_set.h.
References edit_.
Referenced by rocksdb::DBImpl::InstallCompactionResults().
 { return edit_; }
bool rocksdb::Compaction::enable_compression () const inline
Definition at line 566 of file version_set.h.
References enable_compression_.
Referenced by rocksdb::DBImpl::OpenCompactionOutputFile().
 { return enable_compression_; }
FileMetaData* rocksdb::Compaction::input (int which, int i) const inline
Definition at line 560 of file version_set.h.
References inputs_.
Referenced by rocksdb::DBImpl::DoCompactionWork(), rocksdb::VersionSet::SizeBeingCompacted(), and rocksdb::VersionSet::VerifyCompactionFileConsistency().
 { return inputs_[which][i]; }
bool rocksdb::Compaction::IsBaseLevelForKey (const Slice & user_key)
Definition at line 3015 of file version_set.cc.
References bottommost_level_, rocksdb::Options::compaction_style, rocksdb::Comparator::Compare(), ripple::f, rocksdb::Version::files_, rocksdb::VersionSet::icmp_, input_version_, rocksdb::kCompactionStyleUniversal, rocksdb::FileMetaData::largest, level_, level_ptrs_, number_levels_, rocksdb::VersionSet::options_, rocksdb::FileMetaData::smallest, rocksdb::InternalKeyComparator::user_comparator(), rocksdb::InternalKey::user_key(), and rocksdb::Version::vset_.
Referenced by rocksdb::DBImpl::DoCompactionWork().
{
   if (input_version_->vset_->options_->compaction_style ==
       kCompactionStyleUniversal) {
     return bottommost_level_;
   }
   // Maybe use binary search to find right entry instead of linear search?
   const Comparator* user_cmp = input_version_->vset_->icmp_.user_comparator();
   for (int lvl = level_ + 2; lvl < number_levels_; lvl++) {
     const std::vector<FileMetaData*>& files = input_version_->files_[lvl];
     for (; level_ptrs_[lvl] < files.size(); ) {
       FileMetaData* f = files[level_ptrs_[lvl]];
       if (user_cmp->Compare(user_key, f->largest.user_key()) <= 0) {
         // We've advanced far enough
         if (user_cmp->Compare(user_key, f->smallest.user_key()) >= 0) {
           // Key falls in this file's range, so definitely not base level
           return false;
         }
         break;
       }
       level_ptrs_[lvl]++;
     }
   }
   return true;
 }
bool rocksdb::Compaction::IsFullCompaction () inline
Definition at line 597 of file version_set.h.
References is_full_compaction_.
Referenced by rocksdb::DBImpl::CompactionState::GetFilterContext().
 { return is_full_compaction_; }
bool rocksdb::Compaction::IsTrivialMove () const
Definition at line 2998 of file version_set.cc.
References grandparents_, maxGrandParentOverlapBytes_, num_input_files(), and rocksdb::TotalFileSize().
{
   // Avoid a move if there is lots of overlapping grandparent data.
   // Otherwise, the move could create a parent file that will require
   // a very expensive merge later on.
   return (num_input_files(0) == 1 &&
           num_input_files(1) == 0 &&
           TotalFileSize(grandparents_) <= maxGrandParentOverlapBytes_);
 }
int rocksdb::Compaction::level () const inline
Definition at line 547 of file version_set.h.
References level_.
Referenced by rocksdb::DBImpl::DoCompactionWork(), rocksdb::VersionSet::ExpandWhileOverlapping(), rocksdb::DBImpl::InstallCompactionResults(), rocksdb::VersionSet::MakeInputIterator(), rocksdb::VersionSet::ReleaseCompactionFiles(), SetupBottomMostLevel(), rocksdb::VersionSet::SetupOtherInputs(), rocksdb::VersionSet::SizeBeingCompacted(), and rocksdb::VersionSet::VerifyCompactionFileConsistency().
 { return level_; }
void rocksdb::Compaction::MarkFilesBeingCompacted (bool value) private
Definition at line 3067 of file version_set.cc.
References inputs_, and value.
Referenced by rocksdb::VersionSet::CompactRange(), rocksdb::VersionSet::PickCompaction(), and rocksdb::VersionSet::ReleaseCompactionFiles().
{
   for (int i = 0; i < 2; i++) {
     std::vector<FileMetaData*> v = inputs_[i];
     for (unsigned int j = 0; j < inputs_[i].size(); j++) {
       assert(value ? !inputs_[i][j]->being_compacted :
                       inputs_[i][j]->being_compacted);
       inputs_[i][j]->being_compacted = value;
     }
   }
 }
uint64_t rocksdb::Compaction::MaxOutputFileSize () const inline
Definition at line 563 of file version_set.h.
References max_output_file_size_.
Referenced by rocksdb::DBImpl::DoCompactionWork().
 { return max_output_file_size_; }
int rocksdb::Compaction::num_input_files (int which) const inline
Definition at line 557 of file version_set.h.
References inputs_.
Referenced by rocksdb::DBImpl::AllocateCompactionOutputFileNumbers(), rocksdb::DBImpl::DoCompactionWork(), rocksdb::DBImpl::InstallCompactionResults(), IsTrivialMove(), rocksdb::VersionSet::SizeBeingCompacted(), and rocksdb::VersionSet::VerifyCompactionFileConsistency().
 { return inputs_[which].size(); }
int rocksdb::Compaction::output_level () const inline
Definition at line 550 of file version_set.h.
References out_level_.
Referenced by rocksdb::DBImpl::DoCompactionWork(), and rocksdb::DBImpl::OpenCompactionOutputFile().
 { return out_level_; }
void rocksdb::Compaction::ReleaseInputs ()
Definition at line 3103 of file version_set.cc.
References input_version_, and rocksdb::Version::Unref().
{
   if (input_version_ != nullptr) {
     input_version_->Unref();
     input_version_ = nullptr;
   }
 }
void rocksdb::Compaction::ResetNextCompactionIndex () private
Definition at line 3110 of file version_set.cc.
References input_version_, level_, and rocksdb::Version::ResetNextCompactionIndex().
Referenced by rocksdb::VersionSet::ReleaseCompactionFiles().
{
   input_version_->ResetNextCompactionIndex(level_);
 }
double rocksdb::Compaction::score () const inline
Definition at line 591 of file version_set.h.
References score_.
Referenced by rocksdb::DBImpl::DoCompactionWork().
 { return score_; }
void rocksdb::Compaction::SetupBottomMostLevel (bool isManual) private
Definition at line 3079 of file version_set.cc.
References bottommost_level_, rocksdb::Options::compaction_style, input_version_, rocksdb::kCompactionStyleUniversal, level(), rocksdb::VersionSet::NumberLevels(), rocksdb::VersionSet::NumLevelFiles(), rocksdb::VersionSet::options_, and rocksdb::Version::vset_.
Referenced by rocksdb::VersionSet::CompactRange(), and rocksdb::VersionSet::PickCompaction().
{
   if (input_version_->vset_->options_->compaction_style  ==
          kCompactionStyleUniversal) {
     // If universal compaction style is used and manual
     // compaction is occuring, then we are guaranteed that
     // all files will be picked in a single compaction
     // run. We can safely set bottommost_level_ = true.
     // If it is not manual compaction, then bottommost_level_
     // is already set when the Compaction was created.
     if (isManual) {
       bottommost_level_ = true;
     }
     return;
   }
   bottommost_level_ = true;
   int num_levels = input_version_->vset_->NumberLevels();
   for (int i = level() + 2; i < num_levels; i++) {
     if (input_version_->vset_->NumLevelFiles(i) > 0) {
       bottommost_level_ = false;
       break;
     }
   }
 }
bool rocksdb::Compaction::ShouldStopBefore (const Slice & internal_key)
Definition at line 3040 of file version_set.cc.
References rocksdb::InternalKeyComparator::Compare(), grandparent_index_, grandparents_, rocksdb::VersionSet::icmp_, input_version_, maxGrandParentOverlapBytes_, overlapped_bytes_, seen_key_, and rocksdb::Version::vset_.
Referenced by rocksdb::DBImpl::DoCompactionWork().
{
   // Scan to find earliest grandparent file that contains key.
   const InternalKeyComparator* icmp = &input_version_->vset_->icmp_;
   while (grandparent_index_ < grandparents_.size() &&
       icmp->Compare(internal_key,
                     grandparents_[grandparent_index_]->largest.Encode()) > 0) {
     if (seen_key_) {
       overlapped_bytes_ += grandparents_[grandparent_index_]->file_size;
     }
     assert(grandparent_index_ + 1 >= grandparents_.size() ||
            icmp->Compare(grandparents_[grandparent_index_]->largest.Encode(),
                          grandparents_[grandparent_index_+1]->smallest.Encode())
                          < 0);
     grandparent_index_++;
   }
   seen_key_ = true;
   if (overlapped_bytes_ > maxGrandParentOverlapBytes_) {
     // Too much overlap for current output; start new output
     overlapped_bytes_ = 0;
     return true;
   } else {
     return false;
   }
 }
void rocksdb::Compaction::Summary (char * output, int len)
Definition at line 3129 of file version_set.cc.
References rocksdb::Version::GetVersionNumber(), input_version_, inputs_, rocksdb::InputSummary(), level_, and seek_compaction_.
Referenced by rocksdb::DBImpl::DoCompactionWork().
{
   int write = snprintf(output, len,
       "Base version %lu Base level %d, seek compaction:%d, inputs:",
       (unsigned long)input_version_->GetVersionNumber(),
       level_,
       seek_compaction_);
   if (write < 0 || write > len) {
     return;
   }
   char level_low_summary[100];
   InputSummary(inputs_[0], level_low_summary, sizeof(level_low_summary));
   char level_up_summary[100];
   if (inputs_[1].size()) {
     InputSummary(inputs_[1], level_up_summary, sizeof(level_up_summary));
   } else {
     level_up_summary[0] = '\0';
   }
   snprintf(output + write, len - write, "[%s],[%s]",
       level_low_summary, level_up_summary);
 }
Friends And Related Function Documentation
friend class Version friend
Definition at line 600 of file version_set.h.
friend class VersionSet friend
Definition at line 601 of file version_set.h.
Member Data Documentation
int rocksdb::Compaction::base_index_ private
Definition at line 628 of file version_set.h.
Referenced by rocksdb::VersionSet::PickCompactionBySize(), and rocksdb::VersionSet::SetupOtherInputs().
bool rocksdb::Compaction::bottommost_level_ private
Definition at line 633 of file version_set.h.
Referenced by BottomMostLevel(), IsBaseLevelForKey(), and SetupBottomMostLevel().
VersionEdit* rocksdb::Compaction::edit_ private
Definition at line 612 of file version_set.h.
Referenced by Compaction(), edit(), rocksdb::VersionSet::SetupOtherInputs(), and ~Compaction().
bool rocksdb::Compaction::enable_compression_ private
Definition at line 616 of file version_set.h.
Referenced by enable_compression().
size_t rocksdb::Compaction::grandparent_index_ private
Definition at line 624 of file version_set.h.
Referenced by ShouldStopBefore().
std::vector<FileMetaData*> rocksdb::Compaction::grandparents_ private
Definition at line 623 of file version_set.h.
Referenced by IsTrivialMove(), rocksdb::VersionSet::SetupOtherInputs(), and ShouldStopBefore().
Version* rocksdb::Compaction::input_version_ private
Definition at line 611 of file version_set.h.
Referenced by rocksdb::VersionSet::CompactRange(), IsBaseLevelForKey(), rocksdb::VersionSet::PickCompaction(), ReleaseInputs(), ResetNextCompactionIndex(), SetupBottomMostLevel(), ShouldStopBefore(), Summary(), rocksdb::VersionSet::VerifyCompactionFileConsistency(), and ~Compaction().
std::vector<FileMetaData*> rocksdb::Compaction::inputs_[2] private
Definition at line 619 of file version_set.h.
Referenced by AddInputDeletions(), rocksdb::VersionSet::CompactRange(), rocksdb::VersionSet::ExpandWhileOverlapping(), input(), rocksdb::VersionSet::MakeInputIterator(), MarkFilesBeingCompacted(), num_input_files(), rocksdb::VersionSet::PickCompaction(), rocksdb::VersionSet::PickCompactionBySize(), rocksdb::VersionSet::PickCompactionUniversalReadAmp(), rocksdb::VersionSet::SetupOtherInputs(), and Summary().
bool rocksdb::Compaction::is_full_compaction_ private
Definition at line 635 of file version_set.h.
Referenced by IsFullCompaction().
int rocksdb::Compaction::level_ private
Definition at line 607 of file version_set.h.
Referenced by AddInputDeletions(), IsBaseLevelForKey(), level(), ResetNextCompactionIndex(), and Summary().
std::vector<size_t> rocksdb::Compaction::level_ptrs_ private
Definition at line 641 of file version_set.h.
Referenced by Compaction(), and IsBaseLevelForKey().
uint64_t rocksdb::Compaction::max_output_file_size_ private
Definition at line 609 of file version_set.h.
Referenced by MaxOutputFileSize().
uint64_t rocksdb::Compaction::maxGrandParentOverlapBytes_ private
Definition at line 610 of file version_set.h.
Referenced by IsTrivialMove(), and ShouldStopBefore().
int rocksdb::Compaction::number_levels_ private
Definition at line 613 of file version_set.h.
Referenced by Compaction(), and IsBaseLevelForKey().
int rocksdb::Compaction::out_level_ private
Definition at line 608 of file version_set.h.
Referenced by output_level().
uint64_t rocksdb::Compaction::overlapped_bytes_ private
Definition at line 626 of file version_set.h.
Referenced by ShouldStopBefore().
int rocksdb::Compaction::parent_index_ private
Definition at line 629 of file version_set.h.
Referenced by rocksdb::VersionSet::PickCompaction(), rocksdb::VersionSet::PickCompactionBySize(), and rocksdb::VersionSet::SetupOtherInputs().
double rocksdb::Compaction::score_ private
Definition at line 630 of file version_set.h.
Referenced by rocksdb::VersionSet::PickCompactionBySize(), rocksdb::VersionSet::PickCompactionUniversalReadAmp(), and score().
bool rocksdb::Compaction::seek_compaction_ private
Definition at line 615 of file version_set.h.
Referenced by Summary().
bool rocksdb::Compaction::seen_key_ private
Definition at line 625 of file version_set.h.
Referenced by ShouldStopBefore().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/db/version_set.h
rippled/src/ripple/rocksdb/rocksdb/db/version_set.cc