rippled: beast::Sha256::Context Class Reference
beast::Sha256::Context Class Reference
#include <Sha256.h>
Public Member Functions
Context ()
void update (void const *buffer, std::size_t bytes)
void update (std::int8_t const *begin, std::int8_t const *end)
void update (std::uint8_t const *begin, std::uint8_t const *end)
template<typename T >
void update (T const &t)
void * finish (void *digest)
digest_type & finish (digest_type &digest)
digest_type finish ()
Private Attributes
detail::Context m_context
Detailed Description
Computes the Sha256 hash of data.
Definition at line 52 of file Sha256.h.
Constructor & Destructor Documentation
beast::Sha256::Context::Context ()
Create a new hasher prepared for input.
Definition at line 45 of file Sha256.cpp.
References m_context, and beast::Sha256::detail::SHA256_Init().
 {
     detail::SHA256_Init (&m_context);
 }
Member Function Documentation
void * beast::Sha256::Context::finish (void * digest)
Finalize the hash process and store the digest. The memory pointed to by digest must be at least digestLength bytes. This object may not be re-used after calling finish.
Returns
A pointer to the passed hash buffer.
Definition at line 55 of file Sha256.cpp.
Referenced by beast::Sha256::hash().
 {
     detail::SHA256_Final (static_cast <std::uint8_t*> (hash), &m_context);
     return hash;
 }
digest_type& beast::Sha256::Context::finish (digest_type & digest) inline
Definition at line 87 of file Sha256.h.
References finish().
     {
         finish (digest.data());
         return digest;
     }
digest_type beast::Sha256::Context::finish () inline
Definition at line 93 of file Sha256.h.
Referenced by finish().
     {
         digest_type digest;
         finish (digest);
         return digest;
     }
void beast::Sha256::Context::update (void const * buffer, std::size_t bytes)
Update the hashing context with the input sequence.
Definition at line 50 of file Sha256.cpp.
Referenced by beast::Sha256::hash(), and update().
 {
     detail::SHA256_Update (&m_context, static_cast <std::uint8_t const*> (buffer), bytes);
 }
void beast::Sha256::Context::update (std::int8_t const * begin, std::int8_t const * end) inline
Definition at line 62 of file Sha256.h.
References update().
     {
         update (begin, end - begin);
     }
void beast::Sha256::Context::update (std::uint8_t const * begin, std::uint8_t const * end) inline
Definition at line 67 of file Sha256.h.
References update().
     {
         update (begin, end - begin);
     }
template<typename T > void beast::Sha256::Context::update (T const & t) inline
Definition at line 73 of file Sha256.h.
References T, and update().
     {
         update (&t, sizeof(T));
     }
Member Data Documentation
detail::Context beast::Sha256::Context::m_context private
Definition at line 102 of file Sha256.h.
Referenced by Context().
The documentation for this class was generated from the following files:
rippled/src/beast/beast/crypto/Sha256.h
rippled/src/beast/beast/crypto/impl/Sha256.cpp