rippled: ripple::Validators::Logic_test Class Reference
ripple::Validators::Logic_test Class Reference
Classes
struct Params
struct Payload
class PeerLogic
struct TestSource
class TestStore
Public Types
enum { numberOfTestValidators = 1000, numberofTestSources = 50 }
typedef Params::Network Network
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Member Functions
void addSources (Logic &logic)
void testLogic ()
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Additional Inherited Members
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 25 of file Tests.cpp.
Member Typedef Documentation
typedef Params::Network ripple::Validators::Logic_test::Network
Definition at line 96 of file Tests.cpp.
Member Enumeration Documentation
anonymous enum
Enumerator
numberOfTestValidators
numberofTestSources
Definition at line 28 of file Tests.cpp.
     {
         numberOfTestValidators = 1000,
         numberofTestSources = 50
     };
Member Function Documentation
void ripple::Validators::Logic_test::addSources (Logic & logic) inline
Definition at line 175 of file Tests.cpp.
References ripple::Validators::Logic::add(), beast::String::fromNumber(), name, beast::Random::nextInt(), numberofTestSources, and numberOfTestValidators.
Referenced by testLogic().
     {
         beast::Random r;
         for (int i = 1; i <= numberofTestSources; ++i)
         {
             beast::String const name (beast::String::fromNumber (i));
             std::uint32_t const start = r.nextInt (numberOfTestValidators);
             std::uint32_t const end   = start + r.nextInt (numberOfTestValidators);
             logic.add (new TestSource (name, start, end));
         }
     }
void ripple::Validators::Logic_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 215 of file Tests.cpp.
References testLogic().
     {
         testLogic ();
     }
void ripple::Validators::Logic_test::testLogic () inline
Definition at line 187 of file Tests.cpp.
References addSources(), beast::unit_test::suite::expect(), beast::File::getSpecialLocation(), ripple::Validators::StoreSqdb::open(), beast::unit_test::suite::pass(), and beast::File::userDocumentsDirectory.
Referenced by run().
     {
         //TestStore store;
         StoreSqdb storage;
         beast::File const file (
             beast::File::getSpecialLocation (
                 beast::File::userDocumentsDirectory).getChildFile (
                     "validators-test.sqlite"));
         // Can't call this 'error' because of ADL and Journal::error
         beast::Error err (storage.open (file));
         expect (! err, err.what());
         Logic logic (storage, beast::Journal ());
         logic.load ();
         addSources (logic);
         logic.fetch_one ();
         ChosenList::Ptr list (logic.getChosen ());
         pass ();
     }
The documentation for this class was generated from the following file:
rippled/src/ripple/validators/impl/Tests.cpp