rippled: beast::PropertyStream Class Reference
beast::PropertyStream Class Reference abstract
#include <PropertyStream.h>
Classes
class Item
class Map
class Proxy
class Set
class Source
Public Member Functions
PropertyStream ()
virtual ~PropertyStream ()
Protected Member Functions
virtual void map_begin ()=0
virtual void map_begin (std::string const &key)=0
virtual void map_end ()=0
virtual void add (std::string const &key, std::string const &value)=0
void add (std::string const &key, char const *value)
template<typename Value >
void lexical_add (std::string const &key, Value value)
virtual void add (std::string const &key, bool value)
virtual void add (std::string const &key, char value)
virtual void add (std::string const &key, signed char value)
virtual void add (std::string const &key, unsigned char value)
virtual void add (std::string const &key, wchar_t value)
virtual void add (std::string const &key, short value)
virtual void add (std::string const &key, unsigned short value)
virtual void add (std::string const &key, int value)
virtual void add (std::string const &key, unsigned int value)
virtual void add (std::string const &key, long value)
virtual void add (std::string const &key, unsigned long value)
virtual void add (std::string const &key, long long value)
virtual void add (std::string const &key, unsigned long long value)
virtual void add (std::string const &key, float value)
virtual void add (std::string const &key, double value)
virtual void add (std::string const &key, long double value)
virtual void array_begin ()=0
virtual void array_begin (std::string const &key)=0
virtual void array_end ()=0
virtual void add (std::string const &value)=0
void add (char const *value)
template<typename Value >
void lexical_add (Value value)
virtual void add (bool value)
virtual void add (char value)
virtual void add (signed char value)
virtual void add (unsigned char value)
virtual void add (wchar_t value)
virtual void add (short value)
virtual void add (unsigned short value)
virtual void add (int value)
virtual void add (unsigned int value)
virtual void add (long value)
virtual void add (unsigned long value)
virtual void add (long long value)
virtual void add (unsigned long long value)
virtual void add (float value)
virtual void add (double value)
virtual void add (long double value)
Detailed Description
Abstract stream with RAII containers that produce a property tree.
Definition at line 37 of file PropertyStream.h.
Constructor & Destructor Documentation
beast::PropertyStream::PropertyStream ()
Definition at line 410 of file PropertyStream.cpp.
 {
 }
beast::PropertyStream::~PropertyStream () virtual
Definition at line 414 of file PropertyStream.cpp.
 {
 }
Member Function Documentation
virtual void beast::PropertyStream::add (std::string const & key, std::string const & value) protected pure virtual
Implemented in ripple::JsonPropertyStream.
Referenced by add(), beast::PropertyStream::Map::add(), beast::PropertyStream::Source::add(), and lexical_add().
void beast::PropertyStream::add (std::string const & key, char const * value) inline protected
Definition at line 54 of file PropertyStream.h.
References add().
     {
         add (key, std::string (value));
     }
void beast::PropertyStream::add (std::string const & key, bool value) protected virtual
Definition at line 418 of file PropertyStream.cpp.
References add().
 {
     if (value)
         add (key, "true");
     else
         add (key, "false");
 }
void beast::PropertyStream::add (std::string const & key, char value) protected virtual
Definition at line 426 of file PropertyStream.cpp.
References lexical_add().
 {
     lexical_add (key, value);
 }
void beast::PropertyStream::add (std::string const & key, signed char value) protected virtual
Definition at line 431 of file PropertyStream.cpp.
References lexical_add().
 {
     lexical_add (key, value);
 }
void beast::PropertyStream::add (std::string const & key, unsigned char value) protected virtual
Definition at line 436 of file PropertyStream.cpp.
References lexical_add().
 {
     lexical_add (key, value);
 }
void beast::PropertyStream::add (std::string const & key, wchar_t value) protected virtual
Definition at line 441 of file PropertyStream.cpp.
References lexical_add().
 {
     lexical_add (key, value);
 }
void beast::PropertyStream::add (std::string const & key, short value) protected virtual
Reimplemented in ripple::JsonPropertyStream.
Definition at line 458 of file PropertyStream.cpp.
References lexical_add().
 {
     lexical_add (key, value);
 }
void beast::PropertyStream::add (std::string const & key, unsigned short value) protected virtual
Reimplemented in ripple::JsonPropertyStream.
Definition at line 463 of file PropertyStream.cpp.
References lexical_add().
 {
     lexical_add (key, value);
 }
void beast::PropertyStream::add (std::string const & key, int value) protected virtual
Reimplemented in ripple::JsonPropertyStream.
Definition at line 468 of file PropertyStream.cpp.
References lexical_add().
 {
     lexical_add (key, value);
 }
void beast::PropertyStream::add (std::string const & key, unsigned int value) protected virtual
Reimplemented in ripple::JsonPropertyStream.
Definition at line 473 of file PropertyStream.cpp.
References lexical_add().
 {
     lexical_add (key, value);
 }
void beast::PropertyStream::add (std::string const & key, long value) protected virtual
Reimplemented in ripple::JsonPropertyStream.
Definition at line 478 of file PropertyStream.cpp.
References lexical_add().
 {
     lexical_add (key, value);
 }
void beast::PropertyStream::add (std::string const & key, unsigned long value) protected virtual
Definition at line 483 of file PropertyStream.cpp.
References lexical_add().
 {
     lexical_add (key, value);
 }
void beast::PropertyStream::add (std::string const & key, long long value) protected virtual
Definition at line 488 of file PropertyStream.cpp.
References lexical_add().
 {
     lexical_add (key, value);
 }
void beast::PropertyStream::add (std::string const & key, unsigned long long value) protected virtual
Definition at line 493 of file PropertyStream.cpp.
References lexical_add().
 {
     lexical_add (key, value);
 }
void beast::PropertyStream::add (std::string const & key, float value) protected virtual
Reimplemented in ripple::JsonPropertyStream.
Definition at line 498 of file PropertyStream.cpp.
References lexical_add().
 {
     lexical_add (key, value);
 }
void beast::PropertyStream::add (std::string const & key, double value) protected virtual
Reimplemented in ripple::JsonPropertyStream.
Definition at line 503 of file PropertyStream.cpp.
References lexical_add().
 {
     lexical_add (key, value);
 }
void beast::PropertyStream::add (std::string const & key, long double value) protected virtual
Definition at line 508 of file PropertyStream.cpp.
References lexical_add().
 {
     lexical_add (key, value);
 }
virtual void beast::PropertyStream::add (std::string const & value) protected pure virtual
Implemented in ripple::JsonPropertyStream.
void beast::PropertyStream::add (char const * value) inline protected
Definition at line 94 of file PropertyStream.h.
References add().
     {
         add (std::string (value));
     }
void beast::PropertyStream::add (bool value) protected virtual
Definition at line 513 of file PropertyStream.cpp.
References add().
 {
     if (value)
         add ("true");
     else
         add ("false");
 }
void beast::PropertyStream::add (char value) protected virtual
Definition at line 521 of file PropertyStream.cpp.
References lexical_add().
 {
     lexical_add (value);
 }
void beast::PropertyStream::add (signed char value) protected virtual
Definition at line 526 of file PropertyStream.cpp.
References lexical_add().
 {
     lexical_add (value);
 }
void beast::PropertyStream::add (unsigned char value) protected virtual
Definition at line 531 of file PropertyStream.cpp.
References lexical_add().
 {
     lexical_add (value);
 }
void beast::PropertyStream::add (wchar_t value) protected virtual
Definition at line 536 of file PropertyStream.cpp.
References lexical_add().
 {
     lexical_add (value);
 }
void beast::PropertyStream::add (short value) protected virtual
Reimplemented in ripple::JsonPropertyStream.
Definition at line 553 of file PropertyStream.cpp.
References lexical_add().
 {
     lexical_add (value);
 }
void beast::PropertyStream::add (unsigned short value) protected virtual
Reimplemented in ripple::JsonPropertyStream.
Definition at line 558 of file PropertyStream.cpp.
References lexical_add().
 {
     lexical_add (value);
 }
void beast::PropertyStream::add (int value) protected virtual
Reimplemented in ripple::JsonPropertyStream.
Definition at line 563 of file PropertyStream.cpp.
References lexical_add().
 {
     lexical_add (value);
 }
void beast::PropertyStream::add (unsigned int value) protected virtual
Reimplemented in ripple::JsonPropertyStream.
Definition at line 568 of file PropertyStream.cpp.
References lexical_add().
 {
     lexical_add (value);
 }
void beast::PropertyStream::add (long value) protected virtual
Reimplemented in ripple::JsonPropertyStream.
Definition at line 573 of file PropertyStream.cpp.
References lexical_add().
 {
     lexical_add (value);
 }
void beast::PropertyStream::add (unsigned long value) protected virtual
Definition at line 578 of file PropertyStream.cpp.
References lexical_add().
 {
     lexical_add (value);
 }
void beast::PropertyStream::add (long long value) protected virtual
Definition at line 583 of file PropertyStream.cpp.
References lexical_add().
 {
     lexical_add (value);
 }
void beast::PropertyStream::add (unsigned long long value) protected virtual
Definition at line 588 of file PropertyStream.cpp.
References lexical_add().
 {
     lexical_add (value);
 }
void beast::PropertyStream::add (float value) protected virtual
Reimplemented in ripple::JsonPropertyStream.
Definition at line 593 of file PropertyStream.cpp.
References lexical_add().
 {
     lexical_add (value);
 }
void beast::PropertyStream::add (double value) protected virtual
Reimplemented in ripple::JsonPropertyStream.
Definition at line 598 of file PropertyStream.cpp.
References lexical_add().
 {
     lexical_add (value);
 }
void beast::PropertyStream::add (long double value) protected virtual
Definition at line 603 of file PropertyStream.cpp.
References lexical_add().
 {
     lexical_add (value);
 }
virtual void beast::PropertyStream::array_begin () protected pure virtual
Implemented in ripple::JsonPropertyStream.
Referenced by beast::PropertyStream::Set::Set().
virtual void beast::PropertyStream::array_begin (std::string const & key) protected pure virtual
Implemented in ripple::JsonPropertyStream.
virtual void beast::PropertyStream::array_end () protected pure virtual
Implemented in ripple::JsonPropertyStream.
template<typename Value > void beast::PropertyStream::lexical_add (std::string const & key, Value value) inline protected
Definition at line 60 of file PropertyStream.h.
References add(), and value.
Referenced by add().
     {
         std::stringstream ss;
         ss << value;
         add (key, ss.str());
     }
template<typename Value > void beast::PropertyStream::lexical_add (Value value) inline protected
Definition at line 100 of file PropertyStream.h.
References add(), and value.
     {
         std::stringstream ss;
         ss << value;
         add (ss.str());
     }
virtual void beast::PropertyStream::map_begin () protected pure virtual
Implemented in ripple::JsonPropertyStream.
Referenced by beast::PropertyStream::Map::Map().
virtual void beast::PropertyStream::map_begin (std::string const & key) protected pure virtual
Implemented in ripple::JsonPropertyStream.
virtual void beast::PropertyStream::map_end () protected pure virtual
Implemented in ripple::JsonPropertyStream.
The documentation for this class was generated from the following files:
rippled/src/beast/beast/utility/PropertyStream.h
rippled/src/beast/beast/utility/impl/PropertyStream.cpp