rippled: rocksdb::Stats Class Reference
rocksdb::Stats Class Reference
Public Member Functions
Stats ()
void Start (int id)
void Merge (const Stats &other)
void Stop ()
void AddMessage (Slice msg)
void SetId (int id)
void SetExcludeFromMerge ()
void FinishedSingleOp (DB *db)
void AddBytes (int64_t n)
void Report (const Slice &name)
Private Attributes
int id_
double start_
double finish_
double seconds_
long long done_
long long last_report_done_
long long next_report_
int64_t bytes_
double last_op_finish_
double last_report_finish_
HistogramImpl hist_
std::string message_
bool exclude_from_merge_
Detailed Description
Definition at line 536 of file db_bench.cc.
Constructor & Destructor Documentation
rocksdb::Stats::Stats () inline
Definition at line 553 of file db_bench.cc.
References Start().
 { Start(-1); }
Member Function Documentation
void rocksdb::Stats::AddBytes (int64_t n) inline
Definition at line 651 of file db_bench.cc.
References bytes_.
Referenced by rocksdb::Benchmark::Crc32c(), rocksdb::Benchmark::DoWrite(), rocksdb::Benchmark::ReadReverse(), rocksdb::Benchmark::ReadSequential(), rocksdb::Benchmark::SnappyCompress(), rocksdb::Benchmark::SnappyUncompress(), and rocksdb::Benchmark::WriteFromStdin().
{
     bytes_ += n;
   }
void rocksdb::Stats::AddMessage (Slice msg) inline
Definition at line 592 of file db_bench.cc.
References rocksdb::AppendWithSpace(), and message_.
Referenced by rocksdb::Benchmark::AcquireLoad(), rocksdb::Benchmark::AppendRandom(), rocksdb::Benchmark::Crc32c(), rocksdb::Benchmark::DoWrite(), rocksdb::Benchmark::MergeRandom(), rocksdb::Benchmark::PrefixScanRandom(), rocksdb::Benchmark::RandomWithVerify(), rocksdb::Benchmark::ReadHot(), rocksdb::Benchmark::ReadRandom(), rocksdb::Benchmark::ReadRandomWriteRandom(), rocksdb::Benchmark::ReadRandomWriteRandomMultiGet(), rocksdb::Benchmark::SeekRandom(), rocksdb::Benchmark::SnappyCompress(), rocksdb::Benchmark::SnappyUncompress(), and rocksdb::Benchmark::UpdateRandom().
{
     AppendWithSpace(&message_, msg);
   }
void rocksdb::Stats::FinishedSingleOp (DB * db) inline
Definition at line 599 of file db_bench.cc.
References rocksdb::HistogramImpl::Add(), done_, rocksdb::DB::GetProperty(), hist_, id_, last_op_finish_, last_report_done_, last_report_finish_, next_report_, rocksdb::Env::NowMicros(), start_, stats, and rocksdb::Env::TimeToString().
Referenced by rocksdb::Benchmark::AcquireLoad(), rocksdb::Benchmark::AppendRandom(), rocksdb::Benchmark::Crc32c(), rocksdb::Benchmark::DoDelete(), rocksdb::Benchmark::DoWrite(), rocksdb::Benchmark::MergeRandom(), rocksdb::Benchmark::PrefixScanRandom(), rocksdb::Benchmark::RandomWithVerify(), rocksdb::Benchmark::ReadHot(), rocksdb::Benchmark::ReadMissing(), rocksdb::Benchmark::ReadRandom(), rocksdb::Benchmark::ReadRandomWriteRandom(), rocksdb::Benchmark::ReadRandomWriteRandomMultiGet(), rocksdb::Benchmark::ReadReverse(), rocksdb::Benchmark::ReadSequential(), rocksdb::Benchmark::ReadWhileWriting(), rocksdb::Benchmark::SeekRandom(), rocksdb::Benchmark::SnappyCompress(), rocksdb::Benchmark::SnappyUncompress(), rocksdb::Benchmark::UpdateRandom(), and rocksdb::Benchmark::WriteFromStdin().
{
     if (FLAGS_histogram) {
       double now = FLAGS_env->NowMicros();
       double micros = now - last_op_finish_;
       hist_.Add(micros);
       if (micros > 20000 && !FLAGS_stats_interval) {
         fprintf(stderr, "long op: %.1f micros%30s\r", micros, "");
         fflush(stderr);
       }
       last_op_finish_ = now;
     }
     done_++;
     if (done_ >= next_report_) {
       if (!FLAGS_stats_interval) {
         if      (next_report_ < 1000)   next_report_ += 100;
         else if (next_report_ < 5000)   next_report_ += 500;
         else if (next_report_ < 10000)  next_report_ += 1000;
         else if (next_report_ < 50000)  next_report_ += 5000;
         else if (next_report_ < 100000) next_report_ += 10000;
         else if (next_report_ < 500000) next_report_ += 50000;
         else                            next_report_ += 100000;
         fprintf(stderr, "... finished %lld ops%30s\r", done_, "");
         fflush(stderr);
       } else {
         double now = FLAGS_env->NowMicros();
         fprintf(stderr,
                 "%s ... thread %d: (%lld,%lld) ops and "
                 "(%.1f,%.1f) ops/second in (%.6f,%.6f) seconds\n",
                 FLAGS_env->TimeToString((uint64_t) now/1000000).c_str(),
                 id_,
                 done_ - last_report_done_, done_,
                 (done_ - last_report_done_) /
                 ((now - last_report_finish_) / 1000000.0),
                 done_ / ((now - start_) / 1000000.0),
                 (now - last_report_finish_) / 1000000.0,
                 (now - start_) / 1000000.0);
         if (FLAGS_stats_per_interval) {
           std::string stats;
           if (db && db->GetProperty("rocksdb.stats", &stats))
             fprintf(stderr, "%s\n", stats.c_str());
         }
         fflush(stderr);
         next_report_ += FLAGS_stats_interval;
         last_report_finish_ = now;
         last_report_done_ = done_;
       }
     }
   }
void rocksdb::Stats::Merge (const Stats & other) inline
Definition at line 572 of file db_bench.cc.
References bytes_, done_, exclude_from_merge_, finish_, hist_, rocksdb::HistogramImpl::Merge(), message_, seconds_, and start_.
Referenced by rocksdb::Benchmark::RunBenchmark().
{
     if (other.exclude_from_merge_)
       return;
     hist_.Merge(other.hist_);
     done_ += other.done_;
     bytes_ += other.bytes_;
     seconds_ += other.seconds_;
     if (other.start_ < start_) start_ = other.start_;
     if (other.finish_ > finish_) finish_ = other.finish_;
     // Just keep the messages from one thread
     if (message_.empty()) message_ = other.message_;
   }
void rocksdb::Stats::Report (const Slice & name) inline
Definition at line 655 of file db_bench.cc.
References rocksdb::AppendWithSpace(), bytes_, done_, finish_, hist_, message_, start_, rocksdb::HistogramImpl::ToString(), and rocksdb::Slice::ToString().
Referenced by rocksdb::Benchmark::RunBenchmark().
{
     // Pretend at least one op was done in case we are running a benchmark
     // that does not call FinishedSingleOp().
     if (done_ < 1) done_ = 1;
     std::string extra;
     if (bytes_ > 0) {
       // Rate is computed on actual elapsed time, not the sum of per-thread
       // elapsed times.
       double elapsed = (finish_ - start_) * 1e-6;
       char rate[100];
       snprintf(rate, sizeof(rate), "%6.1f MB/s",
                (bytes_ / 1048576.0) / elapsed);
       extra = rate;
     }
     AppendWithSpace(&extra, message_);
     double elapsed = (finish_ - start_) * 1e-6;
     double throughput = (double)done_/elapsed;
     fprintf(stdout, "%-12s : %11.3f micros/op %ld ops/sec;%s%s\n",
             name.ToString().c_str(),
             elapsed * 1e6 / done_,
             (long)throughput,
             (extra.empty() ? "" : " "),
             extra.c_str());
     if (FLAGS_histogram) {
       fprintf(stdout, "Microseconds per op:\n%s\n", hist_.ToString().c_str());
     }
     fflush(stdout);
   }
void rocksdb::Stats::SetExcludeFromMerge () inline
Definition at line 597 of file db_bench.cc.
References exclude_from_merge_.
Referenced by rocksdb::Benchmark::ReadWhileWriting().
 { exclude_from_merge_ = true; }
void rocksdb::Stats::SetId (int id) inline
Definition at line 596 of file db_bench.cc.
References id, and id_.
 { id_ = id; }
void rocksdb::Stats::Start (int id) inline
Definition at line 555 of file db_bench.cc.
References bytes_, rocksdb::HistogramImpl::Clear(), done_, exclude_from_merge_, finish_, hist_, id, id_, last_op_finish_, last_report_done_, last_report_finish_, message_, next_report_, rocksdb::Env::NowMicros(), seconds_, and start_.
Referenced by Stats(), and rocksdb::Benchmark::ThreadBody().
                      {
     id_ = id;
     next_report_ = FLAGS_stats_interval ? FLAGS_stats_interval : 100;
     last_op_finish_ = start_;
     hist_.Clear();
     done_ = 0;
     last_report_done_ = 0;
     bytes_ = 0;
     seconds_ = 0;
     start_ = FLAGS_env->NowMicros();
     finish_ = start_;
     last_report_finish_ = start_;
     message_.clear();
     // When set, stats from this thread won't be merged with others.
     exclude_from_merge_ = false;
   }
void rocksdb::Stats::Stop () inline
Definition at line 587 of file db_bench.cc.
References finish_, rocksdb::Env::NowMicros(), seconds_, and start_.
Referenced by rocksdb::Benchmark::ThreadBody().
               {
     finish_ = FLAGS_env->NowMicros();
     seconds_ = (finish_ - start_) * 1e-6;
   }
Member Data Documentation
int64_t rocksdb::Stats::bytes_ private
Definition at line 545 of file db_bench.cc.
Referenced by AddBytes(), Merge(), Report(), and Start().
long long rocksdb::Stats::done_ private
Definition at line 542 of file db_bench.cc.
Referenced by FinishedSingleOp(), Merge(), Report(), and Start().
bool rocksdb::Stats::exclude_from_merge_ private
Definition at line 550 of file db_bench.cc.
Referenced by Merge(), SetExcludeFromMerge(), and Start().
double rocksdb::Stats::finish_ private
Definition at line 540 of file db_bench.cc.
Referenced by Merge(), Report(), Start(), and Stop().
HistogramImpl rocksdb::Stats::hist_ private
Definition at line 548 of file db_bench.cc.
Referenced by FinishedSingleOp(), Merge(), Report(), and Start().
int rocksdb::Stats::id_ private
Definition at line 538 of file db_bench.cc.
Referenced by FinishedSingleOp(), SetId(), and Start().
double rocksdb::Stats::last_op_finish_ private
Definition at line 546 of file db_bench.cc.
Referenced by FinishedSingleOp(), and Start().
long long rocksdb::Stats::last_report_done_ private
Definition at line 543 of file db_bench.cc.
Referenced by FinishedSingleOp(), and Start().
double rocksdb::Stats::last_report_finish_ private
Definition at line 547 of file db_bench.cc.
Referenced by FinishedSingleOp(), and Start().
std::string rocksdb::Stats::message_ private
Definition at line 549 of file db_bench.cc.
Referenced by AddMessage(), Merge(), Report(), and Start().
long long rocksdb::Stats::next_report_ private
Definition at line 544 of file db_bench.cc.
Referenced by FinishedSingleOp(), and Start().
double rocksdb::Stats::seconds_ private
Definition at line 541 of file db_bench.cc.
Referenced by Merge(), Start(), and Stop().
double rocksdb::Stats::start_ private
Definition at line 539 of file db_bench.cc.
Referenced by FinishedSingleOp(), Merge(), Report(), Start(), and Stop().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/db/db_bench.cc