rippled: rocksdb::TtlIterator Class Reference
rocksdb::TtlIterator Class Reference
#include <db_ttl.h>
Public Member Functions
TtlIterator (Iterator *iter)
~TtlIterator ()
bool Valid () const
void SeekToFirst ()
void SeekToLast ()
void Seek (const Slice &target)
void Next ()
void Prev ()
Slice key () const
int32_t timestamp () const
Slice value () const
Status status () const
Public Member Functions inherited from rocksdb::Iterator
Iterator ()
virtual ~Iterator ()
void RegisterCleanup (CleanupFunction function, void *arg1, void *arg2)
Private Attributes
Iterator * iter_
Additional Inherited Members
Public Types inherited from rocksdb::Iterator
typedef void(* CleanupFunction)(void *arg1, void *arg2)
Detailed Description
Definition at line 116 of file db_ttl.h.
Constructor & Destructor Documentation
rocksdb::TtlIterator::TtlIterator (Iterator * iter) inline explicit
Definition at line 119 of file db_ttl.h.
References iter_.
     : iter_(iter) {
     assert(iter_);
   }
rocksdb::TtlIterator::~TtlIterator () inline
Definition at line 124 of file db_ttl.h.
References iter_.
                  {
     delete iter_;
   }
Member Function Documentation
Slice rocksdb::TtlIterator::key () const inline virtual
Implements rocksdb::Iterator.
Definition at line 152 of file db_ttl.h.
References iter_, and rocksdb::Iterator::key().
                     {
     return iter_->key();
   }
void rocksdb::TtlIterator::Next () inline virtual
Implements rocksdb::Iterator.
Definition at line 144 of file db_ttl.h.
References iter_, and rocksdb::Iterator::Next().
               {
     iter_->Next();
   }
void rocksdb::TtlIterator::Prev () inline virtual
Implements rocksdb::Iterator.
Definition at line 148 of file db_ttl.h.
References iter_, and rocksdb::Iterator::Prev().
               {
     iter_->Prev();
   }
void rocksdb::TtlIterator::Seek (const Slice & target) inline virtual
Implements rocksdb::Iterator.
Definition at line 140 of file db_ttl.h.
References iter_, and rocksdb::Iterator::Seek().
{
     iter_->Seek(target);
   }
void rocksdb::TtlIterator::SeekToFirst () inline virtual
Implements rocksdb::Iterator.
Definition at line 132 of file db_ttl.h.
References iter_, and rocksdb::Iterator::SeekToFirst().
                      {
     iter_->SeekToFirst();
   }
void rocksdb::TtlIterator::SeekToLast () inline virtual
Implements rocksdb::Iterator.
Definition at line 136 of file db_ttl.h.
References iter_, and rocksdb::Iterator::SeekToLast().
                     {
     iter_->SeekToLast();
   }
Status rocksdb::TtlIterator::status () const inline virtual
Implements rocksdb::Iterator.
Definition at line 169 of file db_ttl.h.
References iter_, and rocksdb::Iterator::status().
{
     return iter_->status();
   }
int32_t rocksdb::TtlIterator::timestamp () const inline
Definition at line 156 of file db_ttl.h.
References rocksdb::Slice::data(), rocksdb::DecodeFixed32(), iter_, rocksdb::DBWithTTL::kTSLength, rocksdb::Slice::size(), and rocksdb::Iterator::value().
Referenced by rocksdb::DBDumperCommand::DoCommand(), and rocksdb::ScanCommand::DoCommand().
{
     return DecodeFixed32(
       iter_->value().data() + iter_->value().size() - DBWithTTL::kTSLength);
   }
bool rocksdb::TtlIterator::Valid () const inline virtual
Implements rocksdb::Iterator.
Definition at line 128 of file db_ttl.h.
References iter_, and rocksdb::Iterator::Valid().
                      {
     return iter_->Valid();
   }
Slice rocksdb::TtlIterator::value () const inline virtual
Implements rocksdb::Iterator.
Definition at line 161 of file db_ttl.h.
References iter_, rocksdb::DBWithTTL::kTSLength, ripple::Resource::ok, rocksdb::DBWithTTL::SanityCheckTimestamp(), rocksdb::Slice::size_, and rocksdb::Iterator::value().
                       {
     //TODO: handle timestamp corruption like in general iterator semantics
     assert(DBWithTTL::SanityCheckTimestamp(iter_->value()).ok());
     Slice trimmed_value = iter_->value();
     trimmed_value.size_ -= DBWithTTL::kTSLength;
     return trimmed_value;
   }
Member Data Documentation
Iterator* rocksdb::TtlIterator::iter_ private
Definition at line 174 of file db_ttl.h.
Referenced by key(), Next(), Prev(), Seek(), SeekToFirst(), SeekToLast(), status(), timestamp(), TtlIterator(), Valid(), value(), and ~TtlIterator().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/utilities/ttl/db_ttl.h