rippled: ripple::Resource::Entry Struct Reference
ripple::Resource::Entry Struct Reference
#include <Entry.h>
Public Member Functions
Entry (int)
std::string to_string () const
bool admin () const
int balance (clock_type::rep const now)
int add (int charge, clock_type::rep const now)
Public Attributes
Key const * key
int refcount
DecayingSample
< decayWindowSeconds > local_balance
int remote_balance
Disposition disposition
clock_type::rep lastWarningTime
clock_type::rep whenExpires
Detailed Description
Definition at line 29 of file Entry.h.
Constructor & Destructor Documentation
ripple::Resource::Entry::Entry (int) inline
Definition at line 32 of file Entry.h.
         : refcount (0)
         , remote_balance (0)
         , disposition (ok)
         , lastWarningTime (0)
         , whenExpires (0)
     {
     }
Member Function Documentation
int ripple::Resource::Entry::add (int charge, clock_type::rep const now) inline
Definition at line 69 of file Entry.h.
References ripple::DecayingSample< Window, Value, Elapsed >::add(), local_balance, and remote_balance.
Referenced by ripple::Resource::Logic::charge().
     {
         return local_balance.add (charge, now) + remote_balance;
     }
bool ripple::Resource::Entry::admin () const inline
Definition at line 56 of file Entry.h.
References key, ripple::Resource::Key::kind, and ripple::Resource::kindAdmin.
Referenced by ripple::Resource::Consumer::admin(), ripple::Resource::Logic::disconnect(), and ripple::Resource::Logic::warn().
     {
         return key->kind == kindAdmin;
     }
int ripple::Resource::Entry::balance (clock_type::rep const now) inline
Definition at line 62 of file Entry.h.
References local_balance, remote_balance, and ripple::DecayingSample< Window, Value, Elapsed >::value().
Referenced by ripple::Resource::Logic::balance(), ripple::Resource::Logic::disconnect(), and ripple::Resource::Logic::warn().
     {
         return local_balance.value (now) + remote_balance;
     }
std::string ripple::Resource::Entry::to_string () const inline
Definition at line 41 of file Entry.h.
References ripple::Resource::Key::address, bassertfalse, key, ripple::Resource::Key::kind, ripple::Resource::kindAdmin, ripple::Resource::kindInbound, ripple::Resource::kindOutbound, ripple::Resource::Key::name, and beast::IP::Endpoint::to_string().
Referenced by ripple::Resource::operator<<(), and ripple::Resource::Consumer::to_string().
     {
         switch (key->kind)
         {
         case kindInbound:   return key->address.to_string();
         case kindOutbound:  return key->address.to_string();
         case kindAdmin:     return std::string ("\"") + key->name + "\"";
         default:
             bassertfalse;
         }
         return "(undefined)";
     }
Member Data Documentation
Disposition ripple::Resource::Entry::disposition
Definition at line 87 of file Entry.h.
Key const* ripple::Resource::Entry::key
Definition at line 75 of file Entry.h.
Referenced by admin(), ripple::Resource::Logic::elevateToAdminEndpoint(), ripple::Resource::Logic::newAdminEndpoint(), ripple::Resource::Logic::newInboundEndpoint(), ripple::Resource::Logic::newOutboundEndpoint(), ripple::Resource::Logic::release(), and to_string().
clock_type::rep ripple::Resource::Entry::lastWarningTime
Definition at line 90 of file Entry.h.
Referenced by ripple::Resource::Logic::warn().
DecayingSample<decayWindowSeconds> ripple::Resource::Entry::local_balance
Definition at line 81 of file Entry.h.
Referenced by add(), and balance().
int ripple::Resource::Entry::refcount
Definition at line 78 of file Entry.h.
Referenced by ripple::Resource::Logic::acquire(), ripple::Resource::Logic::erase(), and ripple::Resource::Logic::release().
int ripple::Resource::Entry::remote_balance
Definition at line 84 of file Entry.h.
Referenced by add(), balance(), and ripple::Resource::Logic::importConsumers().
clock_type::rep ripple::Resource::Entry::whenExpires
Definition at line 93 of file Entry.h.
Referenced by ripple::Resource::Logic::release().
The documentation for this struct was generated from the following file:
rippled/src/ripple/resource/impl/Entry.h