rippled: rocksdb::ModelDB Class Reference
rocksdb::ModelDB Class Reference
Classes
class ModelIter
class ModelSnapshot
Public Member Functions
ModelDB (const Options &options)
virtual Status Put (const WriteOptions &o, const Slice &k, const Slice &v)
virtual Status Merge (const WriteOptions &o, const Slice &k, const Slice &v)
virtual Status Delete (const WriteOptions &o, const Slice &key)
virtual Status Get (const ReadOptions &options, const Slice &key, std::string *value)
virtual std::vector< Status > MultiGet (const ReadOptions &options, const std::vector< Slice > &keys, std::vector< std::string > *values)
virtual bool KeyMayExist (const ReadOptions &options, const Slice &key, std::string *value, bool *value_found=nullptr)
virtual Iterator * NewIterator (const ReadOptions &options)
virtual const Snapshot * GetSnapshot ()
virtual void ReleaseSnapshot (const Snapshot *snapshot)
virtual Status Write (const WriteOptions &options, WriteBatch *batch)
virtual bool GetProperty (const Slice &property, std::string *value)
virtual void GetApproximateSizes (const Range *r, int n, uint64_t *sizes)
virtual void CompactRange (const Slice *start, const Slice *end, bool reduce_level, int target_level)
virtual int NumberLevels ()
virtual int MaxMemCompactionLevel ()
virtual int Level0StopWriteTrigger ()
virtual Status Flush (const rocksdb::FlushOptions &options)
virtual Status DisableFileDeletions ()
virtual Status EnableFileDeletions ()
virtual Status GetLiveFiles (std::vector< std::string > &, uint64_t *size, bool flush_memtable=true)
virtual Status GetSortedWalFiles (VectorLogPtr &files)
virtual Status DeleteFile (std::string name)
virtual SequenceNumber GetLatestSequenceNumber () const
virtual Status GetUpdatesSince (rocksdb::SequenceNumber, unique_ptr< rocksdb::TransactionLogIterator > *)
Public Member Functions inherited from rocksdb::DB
DB ()
virtual ~DB ()
virtual void GetLiveFilesMetaData (std::vector< LiveFileMetaData > *metadata)
Private Attributes
const Options options_
KVMap map_
Additional Inherited Members
Static Public Member Functions inherited from rocksdb::DB
static Status Open (const Options &options, const std::string &name, DB **dbptr)
static Status OpenForReadOnly (const Options &options, const std::string &name, DB **dbptr, bool error_if_log_file_exist=false)
Detailed Description
Definition at line 4360 of file db_test.cc.
Constructor & Destructor Documentation
rocksdb::ModelDB::ModelDB (const Options & options) inline explicit
Definition at line 4367 of file db_test.cc.
 : options_(options) { }
Member Function Documentation
virtual void rocksdb::ModelDB::CompactRange (const Slice * start, const Slice * end, bool reduce_level, int target_level) inline virtual
Implements rocksdb::DB.
Definition at line 4446 of file db_test.cc.
{
   }
virtual Status rocksdb::ModelDB::Delete (const WriteOptions & o, const Slice & key) inline virtual
Implements rocksdb::DB.
Definition at line 4374 of file db_test.cc.
References rocksdb::DB::Delete().
Referenced by rocksdb::TEST(), and Write().
{
     return DB::Delete(o, key);
   }
virtual Status rocksdb::ModelDB::DeleteFile (std::string name) inline virtual
Implements rocksdb::DB.
Definition at line 4485 of file db_test.cc.
References rocksdb::Status::OK().
{
     return Status::OK();
   }
virtual Status rocksdb::ModelDB::DisableFileDeletions () inline virtual
Implements rocksdb::DB.
Definition at line 4470 of file db_test.cc.
References rocksdb::Status::OK().
{
     return Status::OK();
   }
virtual Status rocksdb::ModelDB::EnableFileDeletions () inline virtual
Implements rocksdb::DB.
Definition at line 4473 of file db_test.cc.
References rocksdb::Status::OK().
{
     return Status::OK();
   }
virtual Status rocksdb::ModelDB::Flush (const rocksdb::FlushOptions & options) inline virtual
Implements rocksdb::DB.
Definition at line 4465 of file db_test.cc.
{
     Status ret;
     return ret;
   }
virtual Status rocksdb::ModelDB::Get (const ReadOptions & options, const Slice & key, std::string * value) inline virtual
Implements rocksdb::DB.
Definition at line 4377 of file db_test.cc.
References rocksdb::Status::NotSupported().
{
     return Status::NotSupported(key);
   }
virtual void rocksdb::ModelDB::GetApproximateSizes (const Range * r, int n, uint64_t * sizes) inline virtual
Implements rocksdb::DB.
Definition at line 4441 of file db_test.cc.
{
     for (int i = 0; i < n; i++) {
       sizes[i] = 0;
     }
   }
virtual SequenceNumber rocksdb::ModelDB::GetLatestSequenceNumber () const inline virtual
Implements rocksdb::DB.
Definition at line 4489 of file db_test.cc.
{
     return 0;
   }
virtual Status rocksdb::ModelDB::GetLiveFiles (std::vector< std::string > & , uint64_t * size, bool flush_memtable = true) inline virtual
Implements rocksdb::DB.
Definition at line 4476 of file db_test.cc.
References rocksdb::Status::OK().
{
     return Status::OK();
   }
virtual bool rocksdb::ModelDB::GetProperty (const Slice & property, std::string * value) inline virtual
Implements rocksdb::DB.
Definition at line 4438 of file db_test.cc.
{
     return false;
   }
virtual const Snapshot* rocksdb::ModelDB::GetSnapshot () inline virtual
Implements rocksdb::DB.
Definition at line 4409 of file db_test.cc.
References rocksdb::ModelDB::ModelSnapshot::map_, and map_.
Referenced by rocksdb::TEST().
{
     ModelSnapshot* snapshot = new ModelSnapshot;
     snapshot->map_ = map_;
     return snapshot;
   }
virtual Status rocksdb::ModelDB::GetSortedWalFiles (VectorLogPtr & files) inline virtual
Implements rocksdb::DB.
Definition at line 4481 of file db_test.cc.
References rocksdb::Status::OK().
{
     return Status::OK();
   }
virtual Status rocksdb::ModelDB::GetUpdatesSince (rocksdb::SequenceNumber , unique_ptr< rocksdb::TransactionLogIterator > *) inline virtual
Implements rocksdb::DB.
Definition at line 4492 of file db_test.cc.
References rocksdb::Status::NotSupported().
{
     return Status::NotSupported("Not supported in Model DB");
   }
virtual bool rocksdb::ModelDB::KeyMayExist (const ReadOptions & options, const Slice & key, std::string * value, bool * value_found = nullptr) inline virtual
Reimplemented from rocksdb::DB.
Definition at line 4389 of file db_test.cc.
References value_found.
{
     if (value_found != nullptr) {
       *value_found = false;
     }
     return true; // Not Supported directly
   }
virtual int rocksdb::ModelDB::Level0StopWriteTrigger () inline virtual
Implements rocksdb::DB.
Definition at line 4460 of file db_test.cc.
   {
   return -1;
   }
virtual int rocksdb::ModelDB::MaxMemCompactionLevel () inline virtual
Implements rocksdb::DB.
Definition at line 4455 of file db_test.cc.
   {
   return 1;
   }
virtual Status rocksdb::ModelDB::Merge (const WriteOptions & o, const Slice & k, const Slice & v) inline virtual
Implements rocksdb::DB.
Definition at line 4371 of file db_test.cc.
References rocksdb::DB::Merge().
Referenced by Write().
{
     return DB::Merge(o, k, v);
   }
virtual std::vector<Status> rocksdb::ModelDB::MultiGet (const ReadOptions & options, const std::vector< Slice > & keys, std::vector< std::string > * values) inline virtual
Implements rocksdb::DB.
Definition at line 4382 of file db_test.cc.
References rocksdb::Status::NotSupported().
{
     std::vector<Status> s(keys.size(),
                           Status::NotSupported("Not implemented."));
     return s;
   }
virtual Iterator* rocksdb::ModelDB::NewIterator (const ReadOptions & options) inline virtual
Implements rocksdb::DB.
Definition at line 4398 of file db_test.cc.
References map_, and rocksdb::ReadOptions::snapshot.
{
     if (options.snapshot == nullptr) {
       KVMap* saved = new KVMap;
       *saved = map_;
       return new ModelIter(saved, true);
     } else {
       const KVMap* snapshot_state =
           &(reinterpret_cast<const ModelSnapshot*>(options.snapshot)->map_);
       return new ModelIter(snapshot_state, false);
     }
   }
virtual int rocksdb::ModelDB::NumberLevels () inline virtual
Implements rocksdb::DB.
Definition at line 4450 of file db_test.cc.
   {
   return 1;
   }
virtual Status rocksdb::ModelDB::Put (const WriteOptions & o, const Slice & k, const Slice & v) inline virtual
Implements rocksdb::DB.
Definition at line 4368 of file db_test.cc.
References rocksdb::DB::Put().
Referenced by rocksdb::TEST(), and Write().
{
     return DB::Put(o, k, v);
   }
virtual void rocksdb::ModelDB::ReleaseSnapshot (const Snapshot * snapshot) inline virtual
Implements rocksdb::DB.
Definition at line 4415 of file db_test.cc.
Referenced by rocksdb::TEST().
{
     delete reinterpret_cast<const ModelSnapshot*>(snapshot);
   }
virtual Status rocksdb::ModelDB::Write (const WriteOptions & options, WriteBatch * batch) inline virtual
Implements rocksdb::DB.
Definition at line 4418 of file db_test.cc.
References Delete(), rocksdb::WriteBatch::Iterate(), map_, Merge(), Put(), and rocksdb::Slice::ToString().
Referenced by rocksdb::TEST().
{
     class Handler : public WriteBatch::Handler {
      public:
       KVMap* map_;
       virtual void Put(const Slice& key, const Slice& value) {
         (*map_)[key.ToString()] = value.ToString();
       }
       virtual void Merge(const Slice& key, const Slice& value) {
         // ignore merge for now
         //(*map_)[key.ToString()] = value.ToString();
       }
       virtual void Delete(const Slice& key) {
         map_->erase(key.ToString());
       }
     };
     Handler handler;
     handler.map_ = &map_;
     return batch->Iterate(&handler);
   }
Member Data Documentation
KVMap rocksdb::ModelDB::map_ private
Definition at line 4529 of file db_test.cc.
Referenced by GetSnapshot(), NewIterator(), and Write().
const Options rocksdb::ModelDB::options_ private
Definition at line 4528 of file db_test.cc.
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/db/db_test.cc