rippled: ripple::Validators::Logic Class Reference
ripple::Validators::Logic Class Reference
#include <Logic.h>
Classes
struct State
Public Types
typedef beast::SharedData< State > SharedState
typedef std::vector< SourceDesc > SourceTable
typedef ripple::unordered_map
< RipplePublicKey, Validator,
beast::hardened_hash
< RipplePublicKey > > ValidatorTable
typedef CycledSet
< ReceivedValidation,
ReceivedValidationHash,
ReceivedValidationKeyEqual > SeenValidations
typedef CycledSet
< RippleLedgerHash,
RippleLedgerHash::hasher,
RippleLedgerHash::key_equal > SeenLedgerHashes
Public Member Functions
Logic (Store &store, beast::Journal journal=beast::Journal())
void stop ()
void load ()
bool findSourceByID (beast::String id)
void addStatic (beast::SharedPtr< Source > source)
void add (beast::SharedPtr< Source > source)
std::size_t merge (std::vector< Source::Item > const &list, Source *source)
std::size_t remove (std::vector< Source::Item > const &list, Source *source)
void buildChosen ()
void dirtyChosen ()
void checkChosen ()
ChosenList::Ptr getChosen ()
void fetch (SourceDesc &desc)
void expire (SourceDesc &desc)
std::size_t fetch_one ()
void receiveValidation (ReceivedValidation const &rv)
void ledgerClosed (RippleLedgerHash const &ledgerHash)
bool isTrustedPublicKeyHash (RipplePublicKeyHash const &publicKeyHash)
Public Attributes
SharedState m_state
Store & m_store
beast::Journal m_journal
int m_ledgerID
bool m_rebuildChosenList
ChosenList::Ptr m_chosenList
SourceTable m_sources
ValidatorTable m_validators
SeenValidations m_seenValidations
SeenLedgerHashes m_seenLedgerHashes
Detailed Description
Definition at line 32 of file Logic.h.
Member Typedef Documentation
typedef CycledSet<RippleLedgerHash, RippleLedgerHash::hasher, RippleLedgerHash::key_equal> ripple::Validators::Logic::SeenLedgerHashes
Definition at line 87 of file Logic.h.
typedef CycledSet<ReceivedValidation, ReceivedValidationHash, ReceivedValidationKeyEqual> ripple::Validators::Logic::SeenValidations
Definition at line 80 of file Logic.h.
typedef beast::SharedData<State> ripple::Validators::Logic::SharedState
Definition at line 48 of file Logic.h.
typedef std::vector<SourceDesc> ripple::Validators::Logic::SourceTable
Definition at line 66 of file Logic.h.
typedef ripple::unordered_map< RipplePublicKey, Validator, beast::hardened_hash<RipplePublicKey> > ripple::Validators::Logic::ValidatorTable
Definition at line 73 of file Logic.h.
Constructor & Destructor Documentation
ripple::Validators::Logic::Logic (Store & store, beast::Journal journal = beast::Journal ()) inline explicit
Definition at line 92 of file Logic.h.
References m_sources.
         : m_store (store)
         , m_journal (journal)
         , m_ledgerID (0)
         , m_rebuildChosenList (false)
         , m_seenValidations (seenValidationsCacheSize)
         , m_seenLedgerHashes (seenLedgersCacheSize)
     {
         m_sources.reserve (16);
     }
Member Function Documentation
void ripple::Validators::Logic::add (beast::SharedPtr< Source > source) inline
Definition at line 168 of file Logic.h.
References beast::Journal::error, findSourceByID(), beast::Journal::info, ripple::Validators::Store::insert(), m_journal, m_sources, m_store, merge(), and ripple::Validators::SourceDesc::source.
Referenced by ripple::Validators::ManagerImp::addSource(), and ripple::Validators::Logic_test::addSources().
     {
         if (findSourceByID (source->uniqueID()))
         {
             std::unique_ptr <Source> object (source);
             m_journal.error <<
                 "Duplicate " << *source;
             return;
         }
         m_journal.info <<
             "Adding " << *source;
         {
             m_sources.resize (m_sources.size() + 1);
             SourceDesc& desc (m_sources.back());
             desc.source = source;
             m_store.insert (desc);
             merge (desc.results.list, desc.source);
         }
     }
void ripple::Validators::Logic::addStatic (beast::SharedPtr< Source > source) inline
Definition at line 138 of file Logic.h.
References beast::Journal::error, findSourceByID(), ripple::Validators::Source::Results::list, m_journal, merge(), ripple::Validators::Source::Results::success, and beast::Journal::trace.
Referenced by ripple::Validators::ManagerImp::addStaticSource().
     {
         if (findSourceByID (source->uniqueID()))
         {
             m_journal.error <<
                 "Duplicate static " << *source;
             return;
         }
         m_journal.trace <<
             "Addding static " << *source;
         Source::Results results;
         source->fetch (results, m_journal);
         if (results.success)
         {
             std::size_t const numAdded (merge (results.list, source));
             m_journal.trace <<
                 "Added " << numAdded <<
                 " trusted validators from " << *source;
         }
         else
         {
             // TODO: Report the error
         }
     }
void ripple::Validators::Logic::buildChosen () inline
Rebuild the Chosen List.
Definition at line 246 of file Logic.h.
References beast::Journal::debug, beast::String::fromNumber(), m_chosenList, m_journal, and m_validators.
Referenced by checkChosen().
     {
         ChosenList::Ptr list (new ChosenList (m_validators.size ()));
         for (ValidatorTable::const_iterator iter = m_validators.begin ();
             iter != m_validators.end (); ++iter)
         {
             ChosenList::Info item;
             list->insert (iter->first, item);
         }
         // This is thread safe
         m_chosenList = list;
         m_journal.debug <<
             "Rebuilt chosen list with " <<
             beast::String::fromNumber (m_chosenList->size()) << " entries";
     }
void ripple::Validators::Logic::checkChosen () inline
Rebuild the Chosen List if necessary.
Definition at line 272 of file Logic.h.
References buildChosen(), and m_rebuildChosenList.
Referenced by fetch().
     {
         if (m_rebuildChosenList)
         {
             buildChosen ();
             m_rebuildChosenList = false;
         }
     }
void ripple::Validators::Logic::dirtyChosen () inline
Mark the Chosen List for a rebuild.
Definition at line 266 of file Logic.h.
References m_rebuildChosenList.
Referenced by merge(), and remove().
     {
         m_rebuildChosenList = true;
     }
void ripple::Validators::Logic::expire (SourceDesc & desc) inline
Expire a source's list of validators.
Definition at line 384 of file Logic.h.
References ripple::Validators::Source::Results::list, m_store, ripple::Validators::SourceDesc::results, ripple::Validators::SourceDesc::source, and ripple::Validators::Store::update().
Referenced by fetch_one().
     {
         // Decrement reference count on each validator
         remove (desc.results.list, desc.source);
         m_store.update (desc);
     }
void ripple::Validators::Logic::fetch (SourceDesc & desc) inline
Perform a fetch on the source.
Definition at line 296 of file Logic.h.
References checkChosen(), beast::Journal::debug, beast::Journal::error, beast::Time::getCurrentTime(), beast::Journal::info, ripple::Validators::Source::Results::list, m_journal, m_state, m_store, merge(), ripple::Validators::SourceDesc::numberOfFailures, ripple::Validators::SourceDesc::results, ripple::Validators::secondsBetweenFetches, ripple::Validators::SourceDesc::source, ripple::Validators::SourceDesc::status, ripple::Validators::SourceDesc::statusFailed, ripple::Validators::SourceDesc::statusFetched, ripple::Validators::Source::Results::success, beast::asio::swap(), ripple::Validators::Store::update(), and ripple::Validators::SourceDesc::whenToFetch.
Referenced by fetch_one().
     {
         beast::SharedPtr <Source> const& source (desc.source);
         Source::Results results;
         {
             {
                 SharedState::Access state (m_state);
                 if (state->stopping)
                     return;
                 state->fetchSource = source;
             }
             source->fetch (results, m_journal);
             {
                 SharedState::Access state (m_state);
                 if (state->stopping)
                     return;
                 state->fetchSource = nullptr;
             }
         }
         // Reset fetch timer for the source->
         desc.whenToFetch = beast::Time::getCurrentTime () +
             beast::RelativeTime (secondsBetweenFetches);
         if (results.success)
         {
             // Count the number fetched
             std::size_t const numFetched (
                 results.list.size());
             // Add the new source item to the map
             std::size_t const numAdded (
                 merge (results.list, source));
             // Swap lists
             std::swap (desc.results, results);
             // Remove the old source item from the map
             std::size_t const numRemoved (remove (results.list, source));
             // Report
             if (numAdded > numRemoved)
             {
                 m_journal.info <<
                     "Fetched " << numFetched <<
                     "(" << (numAdded - numRemoved) << " new) " <<
                     " trusted validators from " << *source;
             }
             else if (numRemoved > numAdded)
             {
                 m_journal.info <<
                     "Fetched " << numFetched <<
                     "(" << numRemoved - numAdded << " removed) " <<
                     " trusted validators from " << *source;
             }
             else
             {
                 m_journal.debug <<
                     "Fetched " << numFetched <<
                     " trusted validators from " << *source;
             }
             // See if we need to rebuild
             checkChosen ();
             // Reset failure status
             desc.numberOfFailures = 0;
             desc.status = SourceDesc::statusFetched;
             // Update the source's list in the store
             m_store.update (desc, true);
         }
         else
         {
             m_journal.error <<
                 "Failed to fetch " << *source;
             ++desc.numberOfFailures;
             desc.status = SourceDesc::statusFailed;
             // Record the failure in the Store
             m_store.update (desc);
         }
     }
std::size_t ripple::Validators::Logic::fetch_one () inline
Process up to one source that needs fetching.
Returns
The number of sources that were fetched.
Definition at line 395 of file Logic.h.
References ripple::Validators::SourceDesc::expirationTime, expire(), fetch(), beast::Time::getCurrentTime(), beast::Time::isNotNull(), m_sources, and ripple::Validators::SourceDesc::whenToFetch.
Referenced by ripple::Validators::ManagerImp::checkSources().
     {
         std::size_t n (0);
         beast::Time const currentTime (beast::Time::getCurrentTime ());
         for (SourceTable::iterator iter = m_sources.begin ();
             (n == 0) && iter != m_sources.end (); ++iter)
         {
             SourceDesc& desc (*iter);
             // See if we should fetch
             //
             if (desc.whenToFetch <= currentTime)
             {
                 fetch (desc);
                 ++n;
             }
             // See if we need to expire
             //
             if (desc.expirationTime.isNotNull () &&
                 desc.expirationTime <= currentTime)
             {
                 expire (desc);
             }
         }
         return n;
     }
bool ripple::Validators::Logic::findSourceByID (beast::String id) inline
Definition at line 126 of file Logic.h.
References id, and m_sources.
Referenced by add(), and addStatic().
     {
         for (SourceTable::const_iterator iter (m_sources.begin());
             iter != m_sources.end(); ++iter)
             if (iter->source->uniqueID() == id)
                 return true;
         return false;
     }
ChosenList::Ptr ripple::Validators::Logic::getChosen () inline
Returns the current Chosen list. This can be called from any thread at any time.
Definition at line 284 of file Logic.h.
References m_chosenList.
     {
         return m_chosenList;
     }
bool ripple::Validators::Logic::isTrustedPublicKeyHash (RipplePublicKeyHash const & publicKeyHash) inline
Definition at line 480 of file Logic.h.
References m_chosenList.
     {
         return m_chosenList->containsPublicKeyHash (publicKeyHash);
     }
void ripple::Validators::Logic::ledgerClosed (RippleLedgerHash const & ledgerHash) inline
Definition at line 459 of file Logic.h.
References ripple::CycledSet< Key, Hash, KeyEqual, Allocator >::insert(), ripple::Validators::Validator::ledgerClosed(), m_journal, m_ledgerID, m_seenLedgerHashes, m_validators, and beast::Journal::trace.
Referenced by ripple::Validators::ManagerImp::ledgerClosed().
     {
         // Filter duplicates (defensive programming)
         if (! m_seenLedgerHashes.insert (ledgerHash))
             return;
         ++m_ledgerID;
         m_journal.trace <<
             "Closed ledger " << m_ledgerID;
         for (ValidatorTable::iterator iter (m_validators.begin());
             iter != m_validators.end(); ++iter)
         {
             Validator& v (iter->second);
             v.ledgerClosed (ledgerHash);
         }
     }
void ripple::Validators::Logic::load () inline
Definition at line 119 of file Logic.h.
Referenced by ripple::Validators::ManagerImp::init().
     {
         // load data from the database
     }
std::size_t ripple::Validators::Logic::merge (std::vector< Source::Item > const & list, Source * source) inline
Definition at line 193 of file Logic.h.
References dirtyChosen(), m_validators, and ripple::Validators::Source::Item::publicKey.
Referenced by add(), addStatic(), and fetch().
     {
         std::size_t numAdded (0);
         for (std::size_t i = 0; i < list.size (); ++i)
         {
             Source::Item const& item (list [i]);
             std::pair <ValidatorTable::iterator, bool> results (
                 m_validators.emplace (item.publicKey, Validator ()));
             Validator& validatorInfo (results.first->second);
             validatorInfo.addRef();
             if (results.second)
             {
                 // This is a new one
                 ++numAdded;
                 dirtyChosen ();
             }
         }
         return numAdded;
     }
void ripple::Validators::Logic::receiveValidation (ReceivedValidation const & rv) inline
Definition at line 433 of file Logic.h.
References ripple::CycledSet< Key, Hash, KeyEqual, Allocator >::insert(), ripple::Validators::ReceivedValidation::ledgerHash, m_journal, m_seenValidations, m_validators, ripple::Validators::ReceivedValidation::publicKey, and beast::Journal::trace.
Referenced by ripple::Validators::ManagerImp::receiveValidation().
     {
         // Accept validation from the trusted list
         ValidatorTable::iterator iter (m_validators.find (rv.publicKey));
         if (iter != m_validators.end ())
         {
             // Filter duplicates (defensive programming)
             if (! m_seenValidations.insert (rv))
                 return;
             iter->second.receiveValidation (rv.ledgerHash);
             m_journal.trace <<
                 "New trusted validation for " << rv.ledgerHash <<
                 " from " << rv.publicKey;
         }
         else
         {
             m_journal.trace <<
                 "Untrusted validation for " << rv.ledgerHash <<
                 " from " << rv.publicKey;
         }
     }
std::size_t ripple::Validators::Logic::remove (std::vector< Source::Item > const & list, Source * source) inline
Definition at line 217 of file Logic.h.
References bassert, dirtyChosen(), m_validators, and ripple::Validators::Source::Item::publicKey.
     {
         std::size_t numRemoved (0);
         for (std::size_t i = 0; i < list.size (); ++i)
         {
             Source::Item const& item (list [i]);
             ValidatorTable::iterator iter (m_validators.find (item.publicKey));
             bassert (iter != m_validators.end ());
             Validator& validatorInfo (iter->second);
             if (validatorInfo.release())
             {
                 // Last reference removed
                 ++numRemoved;
                 m_validators.erase (iter);
                 dirtyChosen ();
             }
         }
         return numRemoved;
     }
void ripple::Validators::Logic::stop (void) inline
Stop the logic. This will cancel the current fetch and set the stopping flag to true to prevent further fetches. Thread safety: Safe to call from any thread.
Definition at line 109 of file Logic.h.
References m_state.
Referenced by ripple::Validators::ManagerImp::onStop().
     {
         SharedState::Access state (m_state);
         state->stopping = true;
         if (state->fetchSource != nullptr)
             state->fetchSource->cancel ();
     }
Member Data Documentation
ChosenList::Ptr ripple::Validators::Logic::m_chosenList
Definition at line 62 of file Logic.h.
Referenced by buildChosen(), getChosen(), isTrustedPublicKeyHash(), and ripple::Validators::ManagerImp::onWrite().
beast::Journal ripple::Validators::Logic::m_journal
Definition at line 53 of file Logic.h.
Referenced by add(), addStatic(), buildChosen(), fetch(), ledgerClosed(), and receiveValidation().
int ripple::Validators::Logic::m_ledgerID
Definition at line 57 of file Logic.h.
Referenced by ledgerClosed().
bool ripple::Validators::Logic::m_rebuildChosenList
Definition at line 61 of file Logic.h.
Referenced by checkChosen(), and dirtyChosen().
SeenLedgerHashes ripple::Validators::Logic::m_seenLedgerHashes
Definition at line 88 of file Logic.h.
Referenced by ledgerClosed().
SeenValidations ripple::Validators::Logic::m_seenValidations
Definition at line 81 of file Logic.h.
Referenced by receiveValidation().
SourceTable ripple::Validators::Logic::m_sources
Definition at line 67 of file Logic.h.
Referenced by add(), fetch_one(), findSourceByID(), Logic(), and ripple::Validators::ManagerImp::onWrite().
SharedState ripple::Validators::Logic::m_state
Definition at line 50 of file Logic.h.
Referenced by fetch(), and stop().
Store& ripple::Validators::Logic::m_store
Definition at line 52 of file Logic.h.
Referenced by add(), expire(), and fetch().
ValidatorTable ripple::Validators::Logic::m_validators
Definition at line 74 of file Logic.h.
Referenced by buildChosen(), ledgerClosed(), merge(), ripple::Validators::ManagerImp::onWrite(), receiveValidation(), and remove().
The documentation for this class was generated from the following file:
rippled/src/ripple/validators/impl/Logic.h