rippled: beast::TimeHelpers Namespace Reference
beast::TimeHelpers Namespace Reference
Functions
static struct tm millisToLocal (const std::int64_t millis) noexcept
static int extendedModulo (const std::int64_t value, const int modulo) noexcept
static String formatString (const String &format, const struct tm *const tm)
Variables
static std::uint32_t lastMSCounterValue = 0
Function Documentation
static int beast::TimeHelpers::extendedModulo (const std::int64_t value, const int modulo) static noexcept
Definition at line 83 of file Time.cpp.
References value.
Referenced by beast::Time::getMilliseconds(), and beast::Time::getSeconds().
     {
         return (int) (value >= 0 ? (value % modulo)
                                  : (value - ((value / modulo) + 1) * modulo));
     }
static String beast::TimeHelpers::formatString (const String & format, const struct tm *const tm) inline static
Definition at line 89 of file Time.cpp.
References beast::String::toUTF32(), beast::String::toUTF8(), and beast::String::toWideCharPointer().
Referenced by beast::Time::formatted().
     {
        #if BEAST_ANDROID
         typedef CharPointer_UTF8  StringType;
        #elif BEAST_WINDOWS
         typedef CharPointer_UTF16 StringType;
        #else
         typedef CharPointer_UTF32 StringType;
        #endif
         for (size_t bufferSize = 256; ; bufferSize += 256)
         {
             HeapBlock<StringType::CharType> buffer (bufferSize);
            #if BEAST_ANDROID
             const size_t numChars = strftime (buffer, bufferSize - 1, format.toUTF8(), tm);
            #elif BEAST_WINDOWS
             const size_t numChars = wcsftime (buffer, bufferSize - 1, format.toWideCharPointer(), tm);
            #else
             const size_t numChars = wcsftime (buffer, bufferSize - 1, format.toUTF32(), tm);
            #endif
             if (numChars > 0)
                 return String (StringType (buffer),
                                StringType (buffer) + (int) numChars);
         }
     }
static struct tm beast::TimeHelpers::millisToLocal (const std::int64_t millis) static noexcept
Definition at line 29 of file Time.cpp.
References beast::Time::toMilliseconds(), and beast::zerostruct().
Referenced by beast::Time::formatted(), beast::Time::getDayOfMonth(), beast::Time::getDayOfWeek(), beast::Time::getDayOfYear(), beast::Time::getHours(), beast::Time::getMinutes(), beast::Time::getMonth(), beast::Time::getYear(), and beast::Time::isDaylightSavingTime().
     {
         struct tm result;
         const std::int64_t seconds = millis / 1000;
         if (seconds < 86400LL || seconds >= 2145916800LL)
         {
             // use extended maths for dates beyond 1970 to 2037..
             const int timeZoneAdjustment = 31536000 - (int) (Time (1971, 0, 1, 0, 0).toMilliseconds() / 1000);
             const std::int64_t jdm = seconds + timeZoneAdjustment + 210866803200LL;
             const int days = (int) (jdm / 86400LL);
             const int a = 32044 + days;
             const int b = (4 * a + 3) / 146097;
             const int c = a - (b * 146097) / 4;
             const int d = (4 * c + 3) / 1461;
             const int e = c - (d * 1461) / 4;
             const int m = (5 * e + 2) / 153;
             result.tm_mday  = e - (153 * m + 2) / 5 + 1;
             result.tm_mon   = m + 2 - 12 * (m / 10);
             result.tm_year  = b * 100 + d - 6700 + (m / 10);
             result.tm_wday  = (days + 1) % 7;
             result.tm_yday  = -1;
             int t = (int) (jdm % 86400LL);
             result.tm_hour  = t / 3600;
             t %= 3600;
             result.tm_min   = t / 60;
             result.tm_sec   = t % 60;
             result.tm_isdst = -1;
         }
         else
         {
             time_t now = static_cast <time_t> (seconds);
           #if BEAST_WINDOWS
            #ifdef _INC_TIME_INL
             if (now >= 0 && now <= 0x793406fff)
                 localtime_s (&result, &now);
             else
                 zerostruct (result);
            #else
             result = *localtime (&now);
            #endif
           #else
             localtime_r (&now, &result); // more thread-safe
           #endif
         }
         return result;
     }
Variable Documentation
std::uint32_t beast::TimeHelpers::lastMSCounterValue = 0 static
Definition at line 117 of file Time.cpp.
Referenced by beast::Time::getApproximateMillisecondCounter(), and beast::Time::getMillisecondCounter().