rippled: rocksdb::StackableDB Class Reference
rocksdb::StackableDB Class Reference
#include <stackable_db.h>
Public Member Functions
StackableDB (StackableDB *sdb)
virtual DB * GetRawDB ()
virtual Status Put (const WriteOptions &options, const Slice &key, const Slice &val) override
virtual Status Get (const ReadOptions &options, const Slice &key, std::string *value) override
virtual std::vector< Status > MultiGet (const ReadOptions &options, const std::vector< Slice > &keys, std::vector< std::string > *values) override
virtual bool KeyMayExist (const ReadOptions &options, const Slice &key, std::string *value, bool *value_found=nullptr) override
virtual Status Delete (const WriteOptions &wopts, const Slice &key) override
virtual Status Merge (const WriteOptions &options, const Slice &key, const Slice &value) override
virtual Status Write (const WriteOptions &opts, WriteBatch *updates) override
virtual Iterator * NewIterator (const ReadOptions &opts) override
virtual const Snapshot * GetSnapshot () override
virtual void ReleaseSnapshot (const Snapshot *snapshot) override
virtual bool GetProperty (const Slice &property, std::string *value) override
virtual void GetApproximateSizes (const Range *r, int n, uint64_t *sizes) override
virtual void CompactRange (const Slice *begin, const Slice *end, bool reduce_level=false, int target_level=-1) override
virtual int NumberLevels () override
virtual int MaxMemCompactionLevel () override
virtual int Level0StopWriteTrigger () override
virtual Status Flush (const FlushOptions &fopts) override
virtual Status DisableFileDeletions () override
virtual Status EnableFileDeletions () override
virtual Status GetLiveFiles (std::vector< std::string > &vec, uint64_t *mfs, bool flush_memtable=true) override
virtual SequenceNumber GetLatestSequenceNumber () const override
virtual Status GetSortedWalFiles (VectorLogPtr &files) override
virtual Status DeleteFile (std::string name) override
virtual Status GetUpdatesSince (SequenceNumber seq_number, unique_ptr< TransactionLogIterator > *iter) override
Public Member Functions inherited from rocksdb::DB
DB ()
virtual ~DB ()
virtual void GetLiveFilesMetaData (std::vector< LiveFileMetaData > *metadata)
Static Public Member Functions
static StackableDB * DBToStackableDB (DB *db)
Static Public Member Functions inherited from rocksdb::DB
static Status Open (const Options &options, const std::string &name, DB **dbptr)
static Status OpenForReadOnly (const Options &options, const std::string &name, DB **dbptr, bool error_if_log_file_exist=false)
Protected Attributes
StackableDB * sdb_
Detailed Description
Definition at line 11 of file stackable_db.h.
Constructor & Destructor Documentation
rocksdb::StackableDB::StackableDB (StackableDB * sdb) inline explicit
Definition at line 13 of file stackable_db.h.
Referenced by DBToStackableDB().
 : sdb_(sdb) {}
Member Function Documentation
virtual void rocksdb::StackableDB::CompactRange (const Slice * begin, const Slice * end, bool reduce_level = false, int target_level = -1) inline override virtual
Implements rocksdb::DB.
Reimplemented in rocksdb::DBWithTTL.
Definition at line 104 of file stackable_db.h.
References CompactRange(), and sdb_.
Referenced by CompactRange(), and rocksdb::TtlTest::ManualCompact().
{
     return sdb_->CompactRange(begin, end, reduce_level, target_level);
   }
static StackableDB* rocksdb::StackableDB::DBToStackableDB (DB * db) inline static
Definition at line 23 of file stackable_db.h.
References db_, GetRawDB(), and StackableDB().
{
     class NewStackableDB : public StackableDB {
      public:
       NewStackableDB(DB* db)
         : StackableDB(nullptr),
           db_(db) {}
       DB* GetRawDB() {
         return db_;
       }
      private:
       DB* db_;
     };
     return new NewStackableDB(db);
   }
virtual Status rocksdb::StackableDB::Delete (const WriteOptions & wopts, const Slice & key) inline override virtual
Implements rocksdb::DB.
Reimplemented in rocksdb::DBWithTTL.
Definition at line 66 of file stackable_db.h.
References Delete(), and sdb_.
Referenced by Delete().
{
     return sdb_->Delete(wopts, key);
   }
virtual Status rocksdb::StackableDB::DeleteFile (std::string name) inline override virtual
Implements rocksdb::DB.
Reimplemented in rocksdb::DBWithTTL.
Definition at line 147 of file stackable_db.h.
References DeleteFile(), and sdb_.
Referenced by DeleteFile().
{
     return sdb_->DeleteFile(name);
   }
virtual Status rocksdb::StackableDB::DisableFileDeletions () inline override virtual
Implements rocksdb::DB.
Reimplemented in rocksdb::DBWithTTL.
Definition at line 126 of file stackable_db.h.
References DisableFileDeletions(), and sdb_.
Referenced by DisableFileDeletions().
{
     return sdb_->DisableFileDeletions();
   }
virtual Status rocksdb::StackableDB::EnableFileDeletions () inline override virtual
Implements rocksdb::DB.
Reimplemented in rocksdb::DBWithTTL.
Definition at line 130 of file stackable_db.h.
References EnableFileDeletions(), and sdb_.
Referenced by EnableFileDeletions().
{
     return sdb_->EnableFileDeletions();
   }
virtual Status rocksdb::StackableDB::Flush (const FlushOptions & fopts) inline override virtual
Implements rocksdb::DB.
Reimplemented in rocksdb::DBWithTTL.
Definition at line 122 of file stackable_db.h.
References Flush(), and sdb_.
Referenced by Flush(), rocksdb::TtlTest::MakePutWriteBatch(), and rocksdb::TtlTest::PutValues().
{
     return sdb_->Flush(fopts);
   }
virtual Status rocksdb::StackableDB::Get (const ReadOptions & options, const Slice & key, std::string * value) inline override virtual
Implements rocksdb::DB.
Reimplemented in rocksdb::DBWithTTL.
Definition at line 46 of file stackable_db.h.
References Get(), and sdb_.
Referenced by Get(), and rocksdb::TtlTest::SleepCompactCheck().
{
     return sdb_->Get(options, key, value);
   }
virtual void rocksdb::StackableDB::GetApproximateSizes (const Range * r, int n, uint64_t * sizes) inline override virtual
Implements rocksdb::DB.
Reimplemented in rocksdb::DBWithTTL.
Definition at line 99 of file stackable_db.h.
References GetApproximateSizes(), and sdb_.
Referenced by GetApproximateSizes().
              {
       return sdb_->GetApproximateSizes(r, n, sizes);
   }
virtual SequenceNumber rocksdb::StackableDB::GetLatestSequenceNumber () const inline override virtual
Implements rocksdb::DB.
Reimplemented in rocksdb::DBWithTTL.
Definition at line 139 of file stackable_db.h.
References GetLatestSequenceNumber(), and sdb_.
Referenced by GetLatestSequenceNumber().
{
     return sdb_->GetLatestSequenceNumber();
   }
virtual Status rocksdb::StackableDB::GetLiveFiles (std::vector< std::string > & vec, uint64_t * mfs, bool flush_memtable = true) inline override virtual
Implements rocksdb::DB.
Reimplemented in rocksdb::DBWithTTL.
Definition at line 134 of file stackable_db.h.
References GetLiveFiles(), and sdb_.
Referenced by GetLiveFiles().
{
       return sdb_->GetLiveFiles(vec, mfs, flush_memtable);
   }
virtual bool rocksdb::StackableDB::GetProperty (const Slice & property, std::string * value) inline override virtual
Implements rocksdb::DB.
Reimplemented in rocksdb::DBWithTTL.
Definition at line 94 of file stackable_db.h.
References GetProperty(), and sdb_.
Referenced by GetProperty().
              {
       return sdb_->GetProperty(property, value);
   }
virtual DB* rocksdb::StackableDB::GetRawDB () inline virtual
Reimplemented in rocksdb::DBWithTTL.
Definition at line 16 of file stackable_db.h.
References GetRawDB(), and sdb_.
Referenced by DBToStackableDB(), and GetRawDB().
{
     return sdb_->GetRawDB();
   }
virtual const Snapshot* rocksdb::StackableDB::GetSnapshot () inline override virtual
Implements rocksdb::DB.
Reimplemented in rocksdb::DBWithTTL.
Definition at line 86 of file stackable_db.h.
References GetSnapshot(), and sdb_.
Referenced by GetSnapshot().
{
     return sdb_->GetSnapshot();
   }
virtual Status rocksdb::StackableDB::GetSortedWalFiles (VectorLogPtr & files) inline override virtual
Implements rocksdb::DB.
Reimplemented in rocksdb::DBWithTTL.
Definition at line 143 of file stackable_db.h.
References GetSortedWalFiles(), and sdb_.
Referenced by GetSortedWalFiles().
{
     return sdb_->GetSortedWalFiles(files);
   }
virtual Status rocksdb::StackableDB::GetUpdatesSince (SequenceNumber seq_number, unique_ptr< TransactionLogIterator > * iter) inline override virtual
Implements rocksdb::DB.
Reimplemented in rocksdb::DBWithTTL.
Definition at line 151 of file stackable_db.h.
References GetUpdatesSince(), and sdb_.
Referenced by GetUpdatesSince().
              {
       return sdb_->GetUpdatesSince(seq_number, iter);
   }
virtual bool rocksdb::StackableDB::KeyMayExist (const ReadOptions & options, const Slice & key, std::string * value, bool * value_found = nullptr) inline override virtual
Reimplemented from rocksdb::DB.
Reimplemented in rocksdb::DBWithTTL.
Definition at line 59 of file stackable_db.h.
References KeyMayExist(), sdb_, and value_found.
Referenced by KeyMayExist(), and rocksdb::TtlTest::SimpleKeyMayExistCheck().
{
     return sdb_->KeyMayExist(options, key, value, value_found);
   }
virtual int rocksdb::StackableDB::Level0StopWriteTrigger () inline override virtual
Implements rocksdb::DB.
Reimplemented in rocksdb::DBWithTTL.
Definition at line 118 of file stackable_db.h.
References Level0StopWriteTrigger(), and sdb_.
Referenced by Level0StopWriteTrigger().
{
     return sdb_->Level0StopWriteTrigger();
   }
virtual int rocksdb::StackableDB::MaxMemCompactionLevel () inline override virtual
Implements rocksdb::DB.
Reimplemented in rocksdb::DBWithTTL.
Definition at line 114 of file stackable_db.h.
References MaxMemCompactionLevel(), and sdb_.
Referenced by MaxMemCompactionLevel().
{
     return sdb_->MaxMemCompactionLevel();
   }
virtual Status rocksdb::StackableDB::Merge (const WriteOptions & options, const Slice & key, const Slice & value) inline override virtual
Implements rocksdb::DB.
Reimplemented in rocksdb::DBWithTTL.
Definition at line 70 of file stackable_db.h.
References Merge(), and sdb_.
Referenced by Merge().
{
     return sdb_->Merge(options, key, value);
   }
virtual std::vector<Status> rocksdb::StackableDB::MultiGet (const ReadOptions & options, const std::vector< Slice > & keys, std::vector< std::string > * values) inline override virtual
Implements rocksdb::DB.
Reimplemented in rocksdb::DBWithTTL.
Definition at line 52 of file stackable_db.h.
References MultiGet(), and sdb_.
Referenced by MultiGet().
              {
       return sdb_->MultiGet(options, keys, values);
   }
virtual Iterator* rocksdb::StackableDB::NewIterator (const ReadOptions & opts) inline override virtual
Implements rocksdb::DB.
Reimplemented in rocksdb::DBWithTTL.
Definition at line 82 of file stackable_db.h.
References NewIterator(), and sdb_.
Referenced by NewIterator(), and rocksdb::TtlTest::SleepCompactCheckIter().
{
     return sdb_->NewIterator(opts);
   }
virtual int rocksdb::StackableDB::NumberLevels () inline override virtual
Implements rocksdb::DB.
Reimplemented in rocksdb::DBWithTTL.
Definition at line 110 of file stackable_db.h.
References NumberLevels(), and sdb_.
Referenced by NumberLevels().
{
     return sdb_->NumberLevels();
   }
virtual Status rocksdb::StackableDB::Put (const WriteOptions & options, const Slice & key, const Slice & val) inline override virtual
Implements rocksdb::DB.
Reimplemented in rocksdb::DBWithTTL.
Definition at line 40 of file stackable_db.h.
References Put(), and sdb_.
Referenced by Put(), and rocksdb::TtlTest::PutValues().
{
     return sdb_->Put(options, key, val);
   }
virtual void rocksdb::StackableDB::ReleaseSnapshot (const Snapshot * snapshot) inline override virtual
Implements rocksdb::DB.
Reimplemented in rocksdb::DBWithTTL.
Definition at line 90 of file stackable_db.h.
References ReleaseSnapshot(), and sdb_.
Referenced by ReleaseSnapshot().
{
     return sdb_->ReleaseSnapshot(snapshot);
   }
virtual Status rocksdb::StackableDB::Write (const WriteOptions & opts, WriteBatch * updates) inline override virtual
Implements rocksdb::DB.
Reimplemented in rocksdb::DBWithTTL.
Definition at line 77 of file stackable_db.h.
References sdb_, and Write().
Referenced by rocksdb::TtlTest::MakePutWriteBatch(), and Write().
              {
       return sdb_->Write(opts, updates);
   }
Member Data Documentation
StackableDB* rocksdb::StackableDB::sdb_ protected
Definition at line 158 of file stackable_db.h.
Referenced by CompactRange(), Delete(), DeleteFile(), DisableFileDeletions(), EnableFileDeletions(), Flush(), Get(), GetApproximateSizes(), GetLatestSequenceNumber(), GetLiveFiles(), GetProperty(), GetRawDB(), GetSnapshot(), GetSortedWalFiles(), GetUpdatesSince(), KeyMayExist(), Level0StopWriteTrigger(), MaxMemCompactionLevel(), Merge(), MultiGet(), NewIterator(), NumberLevels(), Put(), ReleaseSnapshot(), and Write().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/include/utilities/stackable_db.h