rippled: rocksdb::LookupKey Class Reference
rocksdb::LookupKey Class Reference
#include <dbformat.h>
Public Member Functions
LookupKey (const Slice &user_key, SequenceNumber sequence)
~LookupKey ()
Slice memtable_key () const
Slice internal_key () const
Slice user_key () const
Private Member Functions
LookupKey (const LookupKey &)
void operator= (const LookupKey &)
Private Attributes
const char * start_
const char * kstart_
const char * end_
char space_ [200]
Detailed Description
Definition at line 190 of file dbformat.h.
Constructor & Destructor Documentation
rocksdb::LookupKey::LookupKey (const Slice & user_key, SequenceNumber sequence)
Definition at line 128 of file dbformat.cc.
References rocksdb::Slice::data(), rocksdb::EncodeFixed64(), rocksdb::EncodeVarint32(), end_, kstart_, rocksdb::kValueTypeForSeek, rocksdb::PackSequenceAndType(), rocksdb::Slice::size(), space_, and start_.
{
   size_t usize = user_key.size();
   size_t needed = usize + 13;  // A conservative estimate
   char* dst;
   if (needed <= sizeof(space_)) {
     dst = space_;
   } else {
     dst = new char[needed];
   }
   start_ = dst;
   dst = EncodeVarint32(dst, usize + 8);
   kstart_ = dst;
   memcpy(dst, user_key.data(), usize);
   dst += usize;
   EncodeFixed64(dst, PackSequenceAndType(s, kValueTypeForSeek));
   dst += 8;
   end_ = dst;
 }
rocksdb::LookupKey::~LookupKey () inline
Definition at line 225 of file dbformat.h.
References space_, and start_.
{
   if (start_ != space_) delete[] start_;
 }
rocksdb::LookupKey::LookupKey (const LookupKey &) private
Member Function Documentation
Slice rocksdb::LookupKey::internal_key () const inline
Definition at line 202 of file dbformat.h.
References end_, and kstart_.
Referenced by rocksdb::Version::Get().
 { return Slice(kstart_, end_ - kstart_); }
Slice rocksdb::LookupKey::memtable_key () const inline
Definition at line 199 of file dbformat.h.
References end_, and start_.
Referenced by rocksdb::MemTable::Get(), and rocksdb::MemTable::Update().
 { return Slice(start_, end_ - start_); }
void rocksdb::LookupKey::operator= (const LookupKey &) private
Slice rocksdb::LookupKey::user_key () const inline
Definition at line 205 of file dbformat.h.
References end_, and kstart_.
Referenced by rocksdb::Version::Get(), rocksdb::MemTable::Get(), and rocksdb::MemTable::Update().
 { return Slice(kstart_, end_ - kstart_ - 8); }
Member Data Documentation
const char* rocksdb::LookupKey::end_ private
Definition at line 217 of file dbformat.h.
Referenced by internal_key(), LookupKey(), memtable_key(), and user_key().
const char* rocksdb::LookupKey::kstart_ private
Definition at line 216 of file dbformat.h.
Referenced by internal_key(), LookupKey(), and user_key().
char rocksdb::LookupKey::space_[200] private
Definition at line 218 of file dbformat.h.
Referenced by LookupKey(), and ~LookupKey().
const char* rocksdb::LookupKey::start_ private
Definition at line 215 of file dbformat.h.
Referenced by LookupKey(), memtable_key(), and ~LookupKey().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/db/dbformat.h
rippled/src/ripple/rocksdb/rocksdb/db/dbformat.cc