rippled: ripple::RippleAddress Class Reference
ripple::RippleAddress Class Reference
#include <RippleAddress.h>
Public Member Functions
RippleAddress ()
bool isValid () const
void clear ()
bool isSet () const
std::string humanAddressType () const
uint160 getNodeID () const
Blob const & getNodePublic () const
std::string humanNodePublic () const
bool setNodePublic (const std::string &strPublic)
void setNodePublic (Blob const &vPublic)
bool verifyNodePublic (uint256 const &hash, Blob const &vchSig, ECDSA mustBeFullyCanonical) const
bool verifyNodePublic (uint256 const &hash, const std::string &strSig, ECDSA mustBeFullyCanonical) const
Blob const & getNodePrivateData () const
uint256 getNodePrivate () const
std::string humanNodePrivate () const
bool setNodePrivate (const std::string &strPrivate)
void setNodePrivate (Blob const &vPrivate)
void setNodePrivate (uint256 hash256)
void signNodePrivate (uint256 const &hash, Blob &vchSig) const
uint160 getAccountID () const
std::string humanAccountID () const
bool setAccountID (const std::string &strAccountID, Base58::Alphabet const &alphabet=Base58::getCurrentAlphabet())
void setAccountID (const uint160 &hash160In)
Blob const & getAccountPublic () const
std::string humanAccountPublic () const
bool setAccountPublic (const std::string &strPublic)
void setAccountPublic (Blob const &vPublic)
void setAccountPublic (const RippleAddress &generator, int seq)
bool accountPublicVerify (uint256 const &uHash, Blob const &vucSig, ECDSA mustBeFullyCanonical) const
uint256 getAccountPrivate () const
std::string humanAccountPrivate () const
bool setAccountPrivate (const std::string &strPrivate)
void setAccountPrivate (Blob const &vPrivate)
void setAccountPrivate (uint256 hash256)
void setAccountPrivate (const RippleAddress &naGenerator, const RippleAddress &naSeed, int seq)
bool accountPrivateSign (uint256 const &uHash, Blob &vucSig) const
Blob accountPrivateEncrypt (const RippleAddress &naPublicTo, Blob const &vucPlainText) const
Blob accountPrivateDecrypt (const RippleAddress &naPublicFrom, Blob const &vucCipherText) const
BIGNUM * getGeneratorBN () const
Blob const & getGenerator () const
std::string humanGenerator () const
bool setGenerator (const std::string &strGenerator)
void setGenerator (Blob const &vPublic)
uint128 getSeed () const
std::string humanSeed () const
std::string humanSeed1751 () const
bool setSeed (const std::string &strSeed)
int setSeed1751 (const std::string &strHuman1751)
bool setSeedGeneric (const std::string &strText)
void setSeed (uint128 hash128)
void setSeedRandom ()
Public Member Functions inherited from ripple::CBase58Data
bool SetString (const char *psz, unsigned char version, Base58::Alphabet const &alphabet=Base58::getCurrentAlphabet())
bool SetString (const std::string &str, unsigned char version)
std::string ToString () const
int CompareTo (const CBase58Data &b58) const
bool operator== (const CBase58Data &b58) const
bool operator!= (const CBase58Data &b58) const
bool operator<= (const CBase58Data &b58) const
bool operator>= (const CBase58Data &b58) const
bool operator< (const CBase58Data &b58) const
bool operator> (const CBase58Data &b58) const
Static Public Member Functions
static RippleAddress createNodePublic (const RippleAddress &naSeed)
static RippleAddress createNodePublic (Blob const &vPublic)
static RippleAddress createNodePublic (const std::string &strPublic)
static RippleAddress createNodePrivate (const RippleAddress &naSeed)
static RippleAddress createAccountID (const std::string &strAccountID)
static RippleAddress createAccountID (const uint160 &uiAccountID)
static std::string createHumanAccountID (const uint160 &uiAccountID)
static std::string createHumanAccountID (Blob const &vPrivate)
static RippleAddress createAccountPublic (Blob const &vPublic)
static std::string createHumanAccountPublic (Blob const &vPublic)
static RippleAddress createAccountPublic (const RippleAddress &naGenerator, int iSeq)
static RippleAddress createAccountPrivate (const RippleAddress &naGenerator, const RippleAddress &naSeed, int iSeq)
static RippleAddress createAccountPrivate (Blob const &vPrivate)
static std::string createHumanAccountPrivate (Blob const &vPrivate)
static RippleAddress createGeneratorPublic (const RippleAddress &naSeed)
static RippleAddress createSeedRandom ()
static RippleAddress createSeedGeneric (const std::string &strText)
Private Types
enum VersionEncoding {
VER_NONE = 1, VER_NODE_PUBLIC = 28, VER_NODE_PRIVATE = 32, VER_ACCOUNT_ID = 0,
VER_ACCOUNT_PUBLIC = 35, VER_ACCOUNT_PRIVATE = 34, VER_FAMILY_GENERATOR = 41, VER_FAMILY_SEED = 33
}
Private Attributes
bool mIsValid
Additional Inherited Members
Protected Member Functions inherited from ripple::CBase58Data
CBase58Data ()
~CBase58Data ()
void SetData (int nVersionIn, Blob const &vchDataIn)
void SetData (int nVersionIn, const void *pdata, size_t nSize)
void SetData (int nVersionIn, const unsigned char *pbegin, const unsigned char *pend)
Protected Attributes inherited from ripple::CBase58Data
unsigned char nVersion
Blob vchData
Detailed Description
Definition at line 43 of file RippleAddress.h.
Member Enumeration Documentation
enum ripple::RippleAddress::VersionEncoding private
Enumerator
VER_NONE
VER_NODE_PUBLIC
VER_NODE_PRIVATE
VER_ACCOUNT_ID
VER_ACCOUNT_PUBLIC
VER_ACCOUNT_PRIVATE
VER_FAMILY_GENERATOR
VER_FAMILY_SEED
Definition at line 46 of file RippleAddress.h.
     {
         VER_NONE                = 1,
         VER_NODE_PUBLIC         = 28,
         VER_NODE_PRIVATE        = 32,
         VER_ACCOUNT_ID          = 0,
         VER_ACCOUNT_PUBLIC      = 35,
         VER_ACCOUNT_PRIVATE     = 34,
         VER_FAMILY_GENERATOR    = 41,
         VER_FAMILY_SEED         = 33,
     } VersionEncoding;
Constructor & Destructor Documentation
ripple::RippleAddress::RippleAddress ()
Definition at line 26 of file RippleAddress.cpp.
     : mIsValid (false)
 {
     nVersion = VER_NONE;
 }
Member Function Documentation
Blob ripple::RippleAddress::accountPrivateDecrypt (const RippleAddress & naPublicFrom, Blob const & vucCipherText) const
Definition at line 627 of file RippleAddress.cpp.
References ripple::CKey::decryptECIES(), getAccountPrivate(), getAccountPublic(), ripple::lsWARNING, nothing, ripple::CKey::SetPrivateKeyU(), ripple::CKey::SetPubKey(), and WriteLog.
Referenced by ripple::RPC::accountFromString(), ripple::RPC::getMasterGenerator(), and ripple::RippleAddress_test::run().
 {
     CKey                        ckPrivate;
     CKey                        ckPublic;
     Blob    vucPlainText;
     if (!ckPublic.SetPubKey (naPublicFrom.getAccountPublic ()))
     {
         // Bad public key.
         WriteLog (lsWARNING, RippleAddress) << "accountPrivateDecrypt: Bad public key.";
     }
     else if (!ckPrivate.SetPrivateKeyU (getAccountPrivate ()))
     {
         // Bad private key.
         WriteLog (lsWARNING, RippleAddress) << "accountPrivateDecrypt: Bad private key.";
     }
     else
     {
         try
         {
             vucPlainText = ckPrivate.decryptECIES (ckPublic, vucCipherText);
         }
         catch (...)
         {
             nothing ();
         }
     }
     return vucPlainText;
 }
Blob ripple::RippleAddress::accountPrivateEncrypt (const RippleAddress & naPublicTo, Blob const & vucPlainText) const
Definition at line 596 of file RippleAddress.cpp.
References ripple::CKey::encryptECIES(), getAccountPrivate(), getAccountPublic(), ripple::lsWARNING, nothing, ripple::CKey::SetPrivateKeyU(), ripple::CKey::SetPubKey(), and WriteLog.
Referenced by ripple::RippleAddress_test::run().
 {
     CKey                        ckPrivate;
     CKey                        ckPublic;
     Blob    vucCipherText;
     if (!ckPublic.SetPubKey (naPublicTo.getAccountPublic ()))
     {
         // Bad public key.
         WriteLog (lsWARNING, RippleAddress) << "accountPrivateEncrypt: Bad public key.";
     }
     else if (!ckPrivate.SetPrivateKeyU (getAccountPrivate ()))
     {
         // Bad private key.
         WriteLog (lsWARNING, RippleAddress) << "accountPrivateEncrypt: Bad private key.";
     }
     else
     {
         try
         {
             vucCipherText = ckPrivate.encryptECIES (ckPublic, vucPlainText);
         }
         catch (...)
         {
             nothing ();
         }
     }
     return vucCipherText;
 }
bool ripple::RippleAddress::accountPrivateSign (uint256 const & uHash, Blob & vucSig) const
Definition at line 555 of file RippleAddress.cpp.
References CondLog, getAccountPrivate(), ripple::lsWARNING, ripple::CKey::SetPrivateKeyU(), ripple::CKey::Sign(), and WriteLog.
Referenced by ripple::RippleAddress_test::run(), and ripple::SerializedTransaction::sign().
 {
     CKey        ckPrivate;
     bool        bResult;
     if (!ckPrivate.SetPrivateKeyU (getAccountPrivate ()))
     {
         // Bad private key.
         WriteLog (lsWARNING, RippleAddress) << "accountPrivateSign: Bad private key.";
         bResult = false;
     }
     else
     {
         bResult = ckPrivate.Sign (uHash, vucSig);
         CondLog (!bResult, lsWARNING, RippleAddress) << "accountPrivateSign: Signing failed.";
     }
     return bResult;
 }
bool ripple::RippleAddress::accountPublicVerify (uint256 const & uHash, Blob const & vucSig, ECDSA mustBeFullyCanonical) const
Definition at line 451 of file RippleAddress.cpp.
References getAccountPublic(), ripple::isCanonicalECDSASig(), ripple::lsWARNING, ripple::CKey::SetPubKey(), ripple::CKey::Verify(), and WriteLog.
Referenced by ripple::SerializedTransaction::checkSign().
 {
     CKey        ckPublic;
     bool        bVerified = isCanonicalECDSASig (vucSig, fullyCanonical);
     if (bVerified && !ckPublic.SetPubKey (getAccountPublic ()))
     {
         // Bad private key.
         WriteLog (lsWARNING, RippleAddress) << "accountPublicVerify: Bad private key.";
         bVerified   = false;
     }
     else
     {
         bVerified   = ckPublic.Verify (uHash, vucSig);
     }
     return bVerified;
 }
void ripple::RippleAddress::clear ()
Definition at line 32 of file RippleAddress.cpp.
References mIsValid, ripple::CBase58Data::nVersion, ripple::CBase58Data::vchData, and VER_NONE.
Referenced by ripple::PeerImp::detach(), ripple::RPCHandler::doValidationSeed(), ripple::UniqueNodeListImp::getSeedDomains(), ripple::UniqueNodeListImp::getSeedNodes(), ripple::RPC::parseAccountIds(), and ripple::PeerImp::recvHello().
 {
     nVersion = VER_NONE;
     vchData.clear ();
     mIsValid = false;
 }
static RippleAddress ripple::RippleAddress::createAccountID (const std::string & strAccountID) inline static
Definition at line 116 of file RippleAddress.h.
References setAccountID().
Referenced by createHumanAccountID(), ripple::SerializedLedgerEntry::getFirstOwner(), ripple::Ledger::getRippleState(), ripple::Ledger::getRippleStateIndex(), and ripple::SerializedLedgerEntry::getSecondOwner().
     {
         RippleAddress na;
         na.setAccountID (strAccountID);
         return na;
     }
RippleAddress ripple::RippleAddress::createAccountID (const uint160 & uiAccountID) static
Definition at line 471 of file RippleAddress.cpp.
References setAccountID().
 {
     RippleAddress   na;
     na.setAccountID (uiAccountID);
     return na;
 }
RippleAddress ripple::RippleAddress::createAccountPrivate (const RippleAddress & naGenerator, const RippleAddress & naSeed, int iSeq) static
Definition at line 484 of file RippleAddress.cpp.
References setAccountPrivate().
Referenced by createHumanAccountID(), createHumanAccountPrivate(), ripple::SerializedTransaction_test::run(), ripple::RippleAddress_test::run(), ripple::RippleIdentifier_test::run(), and ripple::RPC::transactionSign().
 {
     RippleAddress   naNew;
     naNew.setAccountPrivate (naGenerator, naSeed, iSeq);
     return naNew;
 }
static RippleAddress ripple::RippleAddress::createAccountPrivate (Blob const & vPrivate) inline static
Definition at line 188 of file RippleAddress.h.
References setAccountPrivate().
     {
         RippleAddress   naNew;
         naNew.setAccountPrivate (vPrivate);
         return naNew;
     }
static RippleAddress ripple::RippleAddress::createAccountPublic (Blob const & vPublic) inline static
Definition at line 148 of file RippleAddress.h.
References setAccountPublic().
Referenced by createHumanAccountPublic(), ripple::WalletAddTransactor::doApply(), ripple::Transactor::preCheck(), ripple::SerializedTransaction_test::run(), ripple::RippleAddress_test::run(), ripple::RippleIdentifier_test::run(), ripple::ApplicationImp::startNewLedger(), ripple::RPC::JSONRPC_test::testAutoFillFees(), and ripple::RPC::transactionSign().
     {
         RippleAddress   naNew;
         naNew.setAccountPublic (vPublic);
         return naNew;
     }
RippleAddress ripple::RippleAddress::createAccountPublic (const RippleAddress & naGenerator, int iSeq) static
Definition at line 383 of file RippleAddress.cpp.
References ripple::CKey::GetPubKey(), and setAccountPublic().
 {
     CKey            ckPub (naGenerator, iSeq);
     RippleAddress   naNew;
     naNew.setAccountPublic (ckPub.GetPubKey ());
     return naNew;
 }
RippleAddress ripple::RippleAddress::createGeneratorPublic (const RippleAddress & naSeed) static
Definition at line 729 of file RippleAddress.cpp.
References getSeed(), and setGenerator().
Referenced by ripple::RPC::accountFromString(), ripple::RPC::authorize(), ripple::RPCHandler::doLedgerEntry(), ripple::RPCHandler::doWalletAccounts(), ripple::RPCHandler::doWalletPropose(), ripple::RPCHandler::doWalletSeed(), ripple::RPC::getMasterGenerator(), ripple::SerializedTransaction_test::run(), ripple::RippleAddress_test::run(), ripple::RippleIdentifier_test::run(), ripple::ApplicationImp::startNewLedger(), ripple::RPC::JSONRPC_test::testAutoFillFees(), and ripple::RPC::transactionSign().
 {
     CKey            ckSeed (naSeed.getSeed ());
     RippleAddress   naNew;
     naNew.setGenerator (ckSeed.GetPubKey ());
     return naNew;
 }
static std::string ripple::RippleAddress::createHumanAccountID (const uint160 & uiAccountID) inline static
Definition at line 125 of file RippleAddress.h.
References createAccountID(), and humanAccountID().
Referenced by ripple::LedgerEntrySet::accountFunds(), ripple::LedgerEntrySet::accountHolds(), ripple::LedgerEntrySet::accountSend(), ripple::RippleCalc::calcNodeAccountFwd(), ripple::RippleCalc::calcNodeAccountRev(), ripple::RippleCalc::calcNodeAdvance(), ripple::RippleCalc::calcNodeDeliverFwd(), ripple::RippleCalc::calcNodeDeliverRev(), ripple::RippleCalc::calcNodeRev(), ripple::PathState::checkNoRipple(), ripple::RPCHandler::doAccountLines(), ripple::OfferCancelTransactor::doApply(), ripple::OfferCreateTransactor::doApply(), ripple::Pathfinder::findPaths(), ripple::Ledger::getBookBase(), ripple::NetworkOPsImp::getBookPage(), ripple::STAmount::getFullText(), ripple::PathState::Node::getJson(), ripple::STPath::getJson(), ripple::PathState::pushImply(), ripple::PathState::pushNode(), ripple::RippleCalc::rippleCalc(), ripple::LedgerEntrySet::rippleCredit(), ripple::LedgerEntrySet::rippleOwed(), ripple::LedgerEntrySet::rippleQualityIn(), ripple::LedgerEntrySet::rippleSend(), ripple::LedgerEntrySet::rippleTransferRate(), ripple::PathState::setCanonical(), ripple::PathState::setExpanded(), ripple::STAmount::setJson(), and ripple::OfferCreateTransactor::takeOffers().
     {
         return createAccountID (uiAccountID).humanAccountID ();
     }
static std::string ripple::RippleAddress::createHumanAccountID (Blob const & vPrivate) inline static
Definition at line 130 of file RippleAddress.h.
References createAccountPrivate(), and humanAccountID().
     {
         return createAccountPrivate (vPrivate).humanAccountID ();
     }
static std::string ripple::RippleAddress::createHumanAccountPrivate (Blob const & vPrivate) inline static
Definition at line 197 of file RippleAddress.h.
References createAccountPrivate(), and humanAccountPrivate().
     {
         return createAccountPrivate (vPrivate).humanAccountPrivate ();
     }
static std::string ripple::RippleAddress::createHumanAccountPublic (Blob const & vPublic) inline static
Definition at line 157 of file RippleAddress.h.
References createAccountPublic(), and humanAccountPublic().
     {
         return createAccountPublic (vPublic).humanAccountPublic ();
     }
RippleAddress ripple::RippleAddress::createNodePrivate (const RippleAddress & naSeed) static
Definition at line 199 of file RippleAddress.cpp.
References ripple::CKey::GetPrivateKeyU(), getSeed(), and setNodePrivate().
Referenced by ripple::RPCHandler::doValidationSeed(), ripple::Config::load(), ripple::LocalCredentials::nodeIdentityCreate(), ripple::RippleAddress_test::run(), and ripple::RippleIdentifier_test::run().
 {
     uint256         uPrivKey;
     RippleAddress   naNew;
     CKey            ckSeed (naSeed.getSeed ());
     ckSeed.GetPrivateKeyU (uPrivKey);
     naNew.setNodePrivate (uPrivKey);
     return naNew;
 }
RippleAddress ripple::RippleAddress::createNodePublic (const RippleAddress & naSeed) static
Definition at line 80 of file RippleAddress.cpp.
References getSeed(), and setNodePublic().
Referenced by ripple::RPCHandler::doValidationCreate(), ripple::RPCHandler::doValidationSeed(), ripple::SerializedValidation::isValid(), ripple::Config::load(), ripple::LocalCredentials::nodeIdentityCreate(), ripple::PeerImp::recvPropose(), ripple::RippleAddress_test::run(), ripple::RippleIdentifier_test::run(), ripple::SerializedValidation::SerializedValidation(), and ripple::UniqueNodeListImp::trustedLoad().
 {
     CKey            ckSeed (naSeed.getSeed ());
     RippleAddress   naNew;
     // YYY Should there be a GetPubKey() equiv that returns a uint256?
     naNew.setNodePublic (ckSeed.GetPubKey ());
     return naNew;
 }
RippleAddress ripple::RippleAddress::createNodePublic (Blob const & vPublic) static
Definition at line 91 of file RippleAddress.cpp.
References setNodePublic().
 {
     RippleAddress   naNew;
     naNew.setNodePublic (vPublic);
     return naNew;
 }
RippleAddress ripple::RippleAddress::createNodePublic (const std::string & strPublic) static
Definition at line 100 of file RippleAddress.cpp.
References setNodePublic().
 {
     RippleAddress   naNew;
     naNew.setNodePublic (strPublic);
     return naNew;
 }
RippleAddress ripple::RippleAddress::createSeedGeneric (const std::string & strText) static
Definition at line 888 of file RippleAddress.cpp.
References setSeedGeneric().
Referenced by ripple::ApplicationImp::startNewLedger(), ripple::RPC::JSONRPC_test::testAutoFillFees(), and ripple::RPC::transactionSign().
 {
     RippleAddress   naNew;
     naNew.setSeedGeneric (strText);
     return naNew;
 }
RippleAddress ripple::RippleAddress::createSeedRandom () static
Definition at line 879 of file RippleAddress.cpp.
References setSeedRandom().
Referenced by ripple::LocalCredentials::nodeIdentityCreate().
 {
     RippleAddress   naNew;
     naNew.setSeedRandom ();
     return naNew;
 }
uint160 ripple::RippleAddress::getAccountID () const
Definition at line 292 of file RippleAddress.cpp.
References ripple::Hash160(), ripple::CBase58Data::nVersion, ripple::CBase58Data::vchData, VER_ACCOUNT_ID, VER_ACCOUNT_PUBLIC, and VER_NONE.
Referenced by ripple::RPC::accountFromString(), ripple::AccountState::AccountState(), ripple::RPC::authorize(), ripple::RegularKeySetTransactor::calculateBaseFee(), ripple::Transactor::checkSig(), ripple::RPCHandler::doAccountCurrencies(), ripple::RPCHandler::doAccountLines(), ripple::RPCHandler::doAccountOffers(), ripple::RPCHandler::doBookOffers(), ripple::RPCHandler::doLedgerEntry(), ripple::RPCHandler::doRipplePathFind(), ripple::RPCHandler::doSubscribe(), ripple::PathRequest::doUpdate(), ripple::Ledger::getAccountRoot(), ripple::Ledger::getAccountRootIndex(), ripple::RPC::getMasterGenerator(), ripple::NetworkOPsImp::getOwnerInfo(), ripple::Ledger::getRippleStateIndex(), humanAccountID(), ripple::STAmount::issuerFromString(), ripple::RippleAccountIDTraits::assign< RippleAddress >::operator()(), ripple::STParsedJSON::parse(), ripple::Transactor::preCheck(), ripple::ChangeTransactor::preCheck(), ripple::NetworkOPsImp::pubAccountTransaction(), ripple::STObject::setFieldAccount(), ripple::STAmount::setFullValue(), ripple::STAccount::setValueNCA(), ripple::NetworkOPsImp::subAccount(), ripple::LedgerEntrySet::threadTx(), ripple::RPC::transactionSign(), ripple::NetworkOPsImp::unsubAccount(), ripple::usAccountDestCurrencies(), and ripple::usAccountSourceCurrencies().
 {
     switch (nVersion)
     {
     case VER_NONE:
         throw std::runtime_error ("unset source - getAccountID");
     case VER_ACCOUNT_ID:
         return uint160 (vchData);
     case VER_ACCOUNT_PUBLIC:
         // Note, we are encoding the left.
         return Hash160 (vchData);
     default:
         throw std::runtime_error (str (boost::format ("bad source: %d") % int (nVersion)));
     }
 }
uint256 ripple::RippleAddress::getAccountPrivate () const
Definition at line 493 of file RippleAddress.cpp.
References ripple::CBase58Data::nVersion, ripple::CBase58Data::vchData, VER_ACCOUNT_PRIVATE, and VER_NONE.
Referenced by accountPrivateDecrypt(), accountPrivateEncrypt(), accountPrivateSign(), and ripple::RippleAccountPrivateKeyTraits::assign< RippleAddress >::operator()().
 {
     switch (nVersion)
     {
     case VER_NONE:
         throw std::runtime_error ("unset source - getAccountPrivate");
     case VER_ACCOUNT_PRIVATE:
         return uint256 (vchData);
     default:
         throw std::runtime_error (str (boost::format ("bad source: %d") % int (nVersion)));
     }
 }
Blob const & ripple::RippleAddress::getAccountPublic () const
Definition at line 393 of file RippleAddress.cpp.
References ripple::CBase58Data::nVersion, ripple::CBase58Data::vchData, VER_ACCOUNT_ID, VER_ACCOUNT_PUBLIC, and VER_NONE.
Referenced by accountPrivateDecrypt(), accountPrivateEncrypt(), accountPublicVerify(), ripple::RPCHandler::doWalletPropose(), ripple::RippleAccountPublicKeyTraits::assign< RippleAddress >::operator()(), ripple::SerializedTransaction_test::run(), ripple::SerializedTransaction::setSigningPubKey(), and ripple::RPC::transactionSign().
 {
     switch (nVersion)
     {
     case VER_NONE:
         throw std::runtime_error ("unset source - getAccountPublic");
     case VER_ACCOUNT_ID:
         throw std::runtime_error ("public not available from account id");
         break;
     case VER_ACCOUNT_PUBLIC:
         return vchData;
     default:
         throw std::runtime_error (str (boost::format ("bad source: %d") % int (nVersion)));
     }
 }
Blob const & ripple::RippleAddress::getGenerator () const
Definition at line 683 of file RippleAddress.cpp.
References ripple::CBase58Data::nVersion, ripple::CBase58Data::vchData, VER_FAMILY_GENERATOR, and VER_NONE.
Referenced by ripple::makeHash().
 {
     // returns the public generator
     switch (nVersion)
     {
     case VER_NONE:
         throw std::runtime_error ("unset source - getGenerator");
     case VER_FAMILY_GENERATOR:
         // Do nothing.
         return vchData;
     default:
         throw std::runtime_error (str (boost::format ("bad source: %d") % int (nVersion)));
     }
 }
BIGNUM * ripple::RippleAddress::getGeneratorBN () const
Definition at line 662 of file RippleAddress.cpp.
References ripple::CBase58Data::nVersion, ripple::CBase58Data::vchData, VER_FAMILY_GENERATOR, and VER_NONE.
Referenced by ripple::CKey::GeneratePublicDeterministicKey().
 {
     // returns the public generator
     switch (nVersion)
     {
     case VER_NONE:
         throw std::runtime_error ("unset source - getGeneratorBN");
     case VER_FAMILY_GENERATOR:
         // Do nothing.
         break;
     default:
         throw std::runtime_error (str (boost::format ("bad source: %d") % int (nVersion)));
     }
     BIGNUM* ret = BN_bin2bn (&vchData[0], vchData.size (), nullptr);
     assert (ret);
     return ret;
 }
uint160 ripple::RippleAddress::getNodeID () const
Definition at line 109 of file RippleAddress.cpp.
References ripple::Hash160(), ripple::CBase58Data::nVersion, ripple::CBase58Data::vchData, VER_NODE_PUBLIC, and VER_NONE.
Referenced by ripple::ValidationsImp::addValidation(), ripple::NetworkOPsImp::checkLastClosedLedger(), ripple::LedgerProposal::LedgerProposal(), ripple::RipplePublicKeyHashTraits::assign< RippleAddress >::operator()(), ripple::SerializedValidation::SerializedValidation(), and ripple::NetworkOPsImp::storeProposal().
 {
     switch (nVersion)
     {
     case VER_NONE:
         throw std::runtime_error ("unset source - getNodeID");
     case VER_NODE_PUBLIC:
         // Note, we are encoding the left.
         return Hash160 (vchData);
     default:
         throw std::runtime_error (str (boost::format ("bad source: %d") % int (nVersion)));
     }
 }
uint256 ripple::RippleAddress::getNodePrivate () const
Definition at line 227 of file RippleAddress.cpp.
References ripple::CBase58Data::nVersion, ripple::CBase58Data::vchData, VER_NODE_PRIVATE, and VER_NONE.
Referenced by ripple::RipplePrivateKeyTraits::assign< RippleAddress >::operator()(), and signNodePrivate().
 {
     switch (nVersion)
     {
     case VER_NONE:
         throw std::runtime_error ("unset source = getNodePrivate");
     case VER_NODE_PRIVATE:
         return uint256 (vchData);
     default:
         throw std::runtime_error (str (boost::format ("bad source: %d") % int (nVersion)));
     }
 }
Blob const & ripple::RippleAddress::getNodePrivateData () const
Definition at line 212 of file RippleAddress.cpp.
References ripple::CBase58Data::nVersion, ripple::CBase58Data::vchData, VER_NODE_PRIVATE, and VER_NONE.
 {
     switch (nVersion)
     {
     case VER_NONE:
         throw std::runtime_error ("unset source - getNodePrivateData");
     case VER_NODE_PRIVATE:
         return vchData;
     default:
         throw std::runtime_error (str (boost::format ("bad source: %d") % int (nVersion)));
     }
 }
Blob const & ripple::RippleAddress::getNodePublic () const
Definition at line 124 of file RippleAddress.cpp.
References ripple::CBase58Data::nVersion, ripple::CBase58Data::vchData, VER_NODE_PUBLIC, and VER_NONE.
Referenced by ripple::LedgerProposal::getPubKey(), ripple::RipplePublicKeyTraits::assign< RippleAddress >::operator()(), ripple::SerializedValidation::SerializedValidation(), ripple::LedgerProposal::sign(), and verifyNodePublic().
 {
     switch (nVersion)
     {
     case VER_NONE:
         throw std::runtime_error ("unset source - getNodePublic");
     case VER_NODE_PUBLIC:
         return vchData;
     default:
         throw std::runtime_error (str (boost::format ("bad source: %d") % int (nVersion)));
     }
 }
uint128 ripple::RippleAddress::getSeed () const
Definition at line 743 of file RippleAddress.cpp.
References ripple::CBase58Data::nVersion, ripple::CBase58Data::vchData, VER_FAMILY_SEED, and VER_NONE.
Referenced by createGeneratorPublic(), createNodePrivate(), createNodePublic(), ripple::RPCHandler::doWalletPropose(), humanSeed1751(), and setAccountPrivate().
 {
     switch (nVersion)
     {
     case VER_NONE:
         throw std::runtime_error ("unset source - getSeed");
     case VER_FAMILY_SEED:
         return uint128 (vchData);
     default:
         throw std::runtime_error (str (boost::format ("bad source: %d") % int (nVersion)));
     }
 }
std::string ripple::RippleAddress::humanAccountID () const
Definition at line 317 of file RippleAddress.cpp.
References getAccountID(), rocksdb::if(), ripple::CBase58Data::nVersion, ripple::rncMap, ripple::s_lock, setAccountID(), ripple::CBase58Data::ToString(), ripple::CBase58Data::vchData, VER_ACCOUNT_ID, VER_ACCOUNT_PUBLIC, and VER_NONE.
Referenced by ripple::Transactor::apply(), ripple::RPC::authorize(), ripple::AcceptedLedgerTx::buildJson(), createHumanAccountID(), ripple::RPCHandler::doAccountInfo(), ripple::RPCHandler::doAccountLines(), ripple::RPCHandler::doAccountOffers(), ripple::RPCHandler::doAccountTx(), ripple::RPCHandler::doAccountTxOld(), ripple::PathRequest::doCreate(), ripple::RPCHandler::doRipplePathFind(), ripple::PathRequest::doUpdate(), ripple::RPCHandler::doWalletPropose(), ripple::Ledger::getAccountState(), ripple::Offer::getJson(), ripple::STAccount::getText(), ripple::NetworkOPsImp::getTxsAccount(), ripple::NetworkOPsImp::getTxsAccountB(), ripple::RPCParser::parseAccountTransactions(), ripple::RPCParser::parseTxAccount(), ripple::STPath::printDebug(), ripple::STPathSet::printDebug(), ripple::NetworkOPsImp::pubBootstrapAccountInfo(), ripple::RippleIdentifier_test::run(), ripple::ApplicationImp::startNewLedger(), ripple::NetworkOPsImp::subAccount(), ripple::LedgerEntrySet::threadTx(), ripple::RPC::transactionSign(), and ripple::NetworkOPsImp::transactionsSQL().
 {
     switch (nVersion)
     {
     case VER_NONE:
         throw std::runtime_error ("unset source - humanAccountID");
     case VER_ACCOUNT_ID:
     {
         StaticScopedLockType sl (s_lock);
         ripple::unordered_map< Blob , std::string >::iterator it = rncMap.find (vchData);
         if (it != rncMap.end ())
             return it->second;
         // VFALCO NOTE Why do we throw everything out? We could keep two maps
         //             here, switch back and forth keep one of them full and clear the
         //             other on a swap - but always check both maps for cache hits.
         //
         if (rncMap.size () > 250000)
             rncMap.clear ();
         return rncMap[vchData] = ToString ();
     }
     case VER_ACCOUNT_PUBLIC:
     {
         RippleAddress   accountID;
         (void) accountID.setAccountID (getAccountID ());
         return accountID.ToString ();
     }
     default:
         throw std::runtime_error (str (boost::format ("bad source: %d") % int (nVersion)));
     }
 }
std::string ripple::RippleAddress::humanAccountPrivate () const
Definition at line 508 of file RippleAddress.cpp.
References ripple::CBase58Data::nVersion, ripple::CBase58Data::ToString(), VER_ACCOUNT_PRIVATE, and VER_NONE.
Referenced by createHumanAccountPrivate(), ripple::RippleAddress_test::run(), and ripple::RippleIdentifier_test::run().
 {
     switch (nVersion)
     {
     case VER_NONE:
         throw std::runtime_error ("unset source - humanAccountPrivate");
     case VER_ACCOUNT_PRIVATE:
         return ToString ();
     default:
         throw std::runtime_error (str (boost::format ("bad source: %d") % int (nVersion)));
     }
 }
std::string ripple::RippleAddress::humanAccountPublic () const
Definition at line 412 of file RippleAddress.cpp.
References ripple::CBase58Data::nVersion, ripple::CBase58Data::ToString(), VER_ACCOUNT_ID, VER_ACCOUNT_PUBLIC, and VER_NONE.
Referenced by createHumanAccountPublic(), ripple::RPCHandler::doWalletPropose(), and ripple::RippleIdentifier_test::run().
 {
     switch (nVersion)
     {
     case VER_NONE:
         throw std::runtime_error ("unset source - humanAccountPublic");
     case VER_ACCOUNT_ID:
         throw std::runtime_error ("public not available from account id");
     case VER_ACCOUNT_PUBLIC:
         return ToString ();
     default:
         throw std::runtime_error (str (boost::format ("bad source: %d") % int (nVersion)));
     }
 }
std::string ripple::RippleAddress::humanAddressType () const
Definition at line 44 of file RippleAddress.cpp.
References ripple::CBase58Data::nVersion, VER_ACCOUNT_ID, VER_ACCOUNT_PRIVATE, VER_ACCOUNT_PUBLIC, VER_FAMILY_GENERATOR, VER_FAMILY_SEED, VER_NODE_PRIVATE, VER_NODE_PUBLIC, and VER_NONE.
 {
     switch (nVersion)
     {
     case VER_NONE:
         return "VER_NONE";
     case VER_NODE_PUBLIC:
         return "VER_NODE_PUBLIC";
     case VER_NODE_PRIVATE:
         return "VER_NODE_PRIVATE";
     case VER_ACCOUNT_ID:
         return "VER_ACCOUNT_ID";
     case VER_ACCOUNT_PUBLIC:
         return "VER_ACCOUNT_PUBLIC";
     case VER_ACCOUNT_PRIVATE:
         return "VER_ACCOUNT_PRIVATE";
     case VER_FAMILY_GENERATOR:
         return "VER_FAMILY_GENERATOR";
     case VER_FAMILY_SEED:
         return "VER_FAMILY_SEED";
     }
     return "unknown";
 }
std::string ripple::RippleAddress::humanGenerator () const
Definition at line 700 of file RippleAddress.cpp.
References ripple::CBase58Data::nVersion, ripple::CBase58Data::ToString(), VER_FAMILY_GENERATOR, and VER_NONE.
Referenced by ripple::RippleIdentifier_test::run().
 {
     switch (nVersion)
     {
     case VER_NONE:
         throw std::runtime_error ("unset source - humanGenerator");
     case VER_FAMILY_GENERATOR:
         return ToString ();
     default:
         throw std::runtime_error (str (boost::format ("bad source: %d") % int (nVersion)));
     }
 }
std::string ripple::RippleAddress::humanNodePrivate () const
Definition at line 242 of file RippleAddress.cpp.
References ripple::CBase58Data::nVersion, ripple::CBase58Data::ToString(), VER_NODE_PRIVATE, and VER_NONE.
Referenced by ripple::LocalCredentials::nodeIdentityCreate(), ripple::RippleAddress_test::run(), and ripple::RippleIdentifier_test::run().
 {
     switch (nVersion)
     {
     case VER_NONE:
         throw std::runtime_error ("unset source - humanNodePrivate");
     case VER_NODE_PRIVATE:
         return ToString ();
     default:
         throw std::runtime_error (str (boost::format ("bad source: %d") % int (nVersion)));
     }
 }
std::string ripple::RippleAddress::humanNodePublic () const
Definition at line 139 of file RippleAddress.cpp.
References ripple::CBase58Data::nVersion, ripple::CBase58Data::ToString(), VER_NODE_PUBLIC, and VER_NONE.
Referenced by ripple::ValidationsImp::addValidation(), ripple::RPCHandler::doValidationCreate(), ripple::RPCHandler::doValidationSeed(), ripple::LedgerProposal::getJson(), ripple::UniqueNodeListImp::getSeedNodes(), ripple::NetworkOPsImp::getServerInfo(), ripple::LocalCredentials::nodeIdentityCreate(), ripple::UniqueNodeListImp::nodeInUNL(), ripple::UniqueNodeListImp::nodeRemovePublic(), ripple::UniqueNodeListImp::processIps(), ripple::UniqueNodeListImp::processValidators(), ripple::PeerImp::recvHello(), ripple::RippleIdentifier_test::run(), ripple::UniqueNodeListImp::setSeedDomains(), ripple::UniqueNodeListImp::setSeedNodes(), and ripple::LocalCredentials::start().
 {
     switch (nVersion)
     {
     case VER_NONE:
         throw std::runtime_error ("unset source - humanNodePublic");
     case VER_NODE_PUBLIC:
         return ToString ();
     default:
         throw std::runtime_error (str (boost::format ("bad source: %d") % int (nVersion)));
     }
 }
std::string ripple::RippleAddress::humanSeed () const
Definition at line 786 of file RippleAddress.cpp.
References ripple::CBase58Data::nVersion, ripple::CBase58Data::ToString(), VER_FAMILY_SEED, and VER_NONE.
Referenced by ripple::RPCHandler::doValidationCreate(), ripple::RPCHandler::doValidationSeed(), ripple::RPCHandler::doWalletPropose(), ripple::RPCHandler::doWalletSeed(), ripple::RippleAddress_test::run(), ripple::RippleIdentifier_test::run(), and ripple::ApplicationImp::startNewLedger().
 {
     switch (nVersion)
     {
     case VER_NONE:
         throw std::runtime_error ("unset source - humanSeed");
     case VER_FAMILY_SEED:
         return ToString ();
     default:
         throw std::runtime_error (str (boost::format ("bad source: %d") % int (nVersion)));
     }
 }
std::string ripple::RippleAddress::humanSeed1751 () const
Definition at line 758 of file RippleAddress.cpp.
References ripple::base_uint< BITS >::begin(), ripple::base_uint< BITS >::end(), ripple::RFC1751::getEnglishFromKey(), getSeed(), ripple::CBase58Data::nVersion, VER_FAMILY_SEED, and VER_NONE.
Referenced by ripple::RPCHandler::doValidationCreate(), ripple::RPCHandler::doValidationSeed(), ripple::RPCHandler::doWalletPropose(), and ripple::RPCHandler::doWalletSeed().
 {
     switch (nVersion)
     {
     case VER_NONE:
         throw std::runtime_error ("unset source - humanSeed1751");
     case VER_FAMILY_SEED:
     {
         std::string strHuman;
         std::string strLittle;
         std::string strBig;
         uint128 uSeed   = getSeed ();
         strLittle.assign (uSeed.begin (), uSeed.end ());
         strBig.assign (strLittle.rbegin (), strLittle.rend ());
         RFC1751::getEnglishFromKey (strHuman, strBig);
         return strHuman;
     }
     default:
         throw std::runtime_error (str (boost::format ("bad source: %d") % int (nVersion)));
     }
 }
bool ripple::RippleAddress::isSet () const
Definition at line 39 of file RippleAddress.cpp.
References ripple::CBase58Data::nVersion, and VER_NONE.
Referenced by ripple::PathRequest::isValid().
 {
     return nVersion != VER_NONE;
 }
bool ripple::RippleAddress::isValid () const inline
Definition at line 64 of file RippleAddress.h.
References mIsValid.
Referenced by ripple::AccountState::AccountState(), ripple::RPC::authorize(), ripple::Transaction::checkSign(), ripple::PeerImp::detach(), ripple::RPCHandler::doAccountLines(), ripple::LedgerProposal::getJson(), ripple::SerializedValidation::isValid(), ripple::Config::load(), ripple::LocalCredentials::nodeIdentityLoad(), ripple::UniqueNodeListImp::processValidators(), ripple::UniqueNodeListImp::setSeedDomains(), ripple::UniqueNodeListImp::setSeedNodes(), ripple::Transaction::sign(), ripple::Transaction::Transaction(), and ripple::UniqueNodeListImp::trustedLoad().
     {
         return mIsValid;
     }
bool ripple::RippleAddress::setAccountID (const std::string & strAccountID, Base58::Alphabet const & alphabet = Base58::getCurrentAlphabet ())
Definition at line 356 of file RippleAddress.cpp.
References mIsValid, ripple::CBase58Data::SetString(), and VER_ACCOUNT_ID.
Referenced by ripple::RPC::accountFromString(), createAccountID(), ripple::RPCHandler::doAccountTx(), ripple::RPCHandler::doAccountTxOld(), ripple::RPCHandler::doBookOffers(), ripple::RPCHandler::doLedgerEntry(), ripple::RPCHandler::doRipplePathFind(), ripple::RPCHandler::doSubscribe(), ripple::TransactionMetaSet::getAffectedAccounts(), ripple::NetworkOPsImp::getLedgerAffectedAccounts(), ripple::SerializedTransaction::getMentionedAccounts(), ripple::STAccount::getText(), ripple::STAccount::getValueNCA(), humanAccountID(), ripple::STAmount::issuerFromString(), ripple::STParsedJSON::parse(), ripple::RPC::parseAccountIds(), ripple::RPCParser::parseAccountRaw(), ripple::RPCParser::parseAccountTransactions(), ripple::PathRequest::parseJson(), ripple::RPCParser::parseTxAccount(), ripple::STPath::printDebug(), ripple::STPathSet::printDebug(), ripple::STAmount::setFullValue(), setSeedGeneric(), and ripple::RPC::transactionSign().
 {
     if (strAccountID.empty ())
     {
         setAccountID (uint160 ());
         mIsValid    = true;
     }
     else
     {
         mIsValid    = SetString (strAccountID.c_str (), VER_ACCOUNT_ID, alphabet);
     }
     return mIsValid;
 }
void ripple::RippleAddress::setAccountID (const uint160 & hash160In)
Definition at line 372 of file RippleAddress.cpp.
References ripple::base_uint< BITS >::begin(), mIsValid, ripple::CBase58Data::SetData(), and VER_ACCOUNT_ID.
 {
     mIsValid        = true;
     SetData (VER_ACCOUNT_ID, hash160.begin (), 20);
 }
bool ripple::RippleAddress::setAccountPrivate (const std::string & strPrivate)
Definition at line 523 of file RippleAddress.cpp.
References mIsValid, ripple::CBase58Data::SetString(), and VER_ACCOUNT_PRIVATE.
Referenced by ripple::RPC::accountFromString(), ripple::RPC::authorize(), createAccountPrivate(), ripple::RPC::getMasterGenerator(), setAccountPrivate(), and setSeedGeneric().
 {
     mIsValid        = SetString (strPrivate.c_str (), VER_ACCOUNT_PRIVATE);
     return mIsValid;
 }
void ripple::RippleAddress::setAccountPrivate (Blob const & vPrivate)
Definition at line 530 of file RippleAddress.cpp.
References mIsValid, ripple::CBase58Data::SetData(), and VER_ACCOUNT_PRIVATE.
 {
     mIsValid        = true;
     SetData (VER_ACCOUNT_PRIVATE, vPrivate);
 }
void ripple::RippleAddress::setAccountPrivate (uint256 hash256)
Definition at line 537 of file RippleAddress.cpp.
References ripple::base_uint< BITS >::begin(), mIsValid, ripple::CBase58Data::SetData(), and VER_ACCOUNT_PRIVATE.
 {
     mIsValid        = true;
     SetData (VER_ACCOUNT_PRIVATE, hash256.begin (), 32);
 }
void ripple::RippleAddress::setAccountPrivate (const RippleAddress & naGenerator, const RippleAddress & naSeed, int seq)
Definition at line 544 of file RippleAddress.cpp.
References ripple::CKey::GetSecretBN(), getSeed(), and setAccountPrivate().
 {
     CKey    ckPubkey    = CKey (naSeed.getSeed ());
     CKey    ckPrivkey   = CKey (naGenerator, ckPubkey.GetSecretBN (), seq);
     uint256 uPrivKey;
     ckPrivkey.GetPrivateKeyU (uPrivKey);
     setAccountPrivate (uPrivKey);
 }
bool ripple::RippleAddress::setAccountPublic (const std::string & strPublic)
Definition at line 430 of file RippleAddress.cpp.
References mIsValid, ripple::CBase58Data::SetString(), and VER_ACCOUNT_PUBLIC.
Referenced by ripple::RPC::accountFromString(), ripple::RPC::accounts(), ripple::RPC::authorize(), ripple::SerializedTransaction::checkSign(), createAccountPublic(), ripple::RPCHandler::doLedgerEntry(), ripple::RPCHandler::doWalletPropose(), ripple::RPCHandler::doWalletSeed(), ripple::RPC::getMasterGenerator(), ripple::RPCParser::parseAccountRaw(), setAccountPublic(), setSeedGeneric(), and ripple::Transaction::Transaction().
 {
     mIsValid        = SetString (strPublic.c_str (), VER_ACCOUNT_PUBLIC);
     return mIsValid;
 }
void ripple::RippleAddress::setAccountPublic (Blob const & vPublic)
Definition at line 437 of file RippleAddress.cpp.
References mIsValid, ripple::CBase58Data::SetData(), and VER_ACCOUNT_PUBLIC.
 {
     mIsValid        = true;
     SetData (VER_ACCOUNT_PUBLIC, vPublic);
 }
void ripple::RippleAddress::setAccountPublic (const RippleAddress & generator, int seq)
Definition at line 444 of file RippleAddress.cpp.
References ripple::CKey::GetPubKey(), and setAccountPublic().
 {
     CKey    pubkey  = CKey (generator, seq);
     setAccountPublic (pubkey.GetPubKey ());
 }
bool ripple::RippleAddress::setGenerator (const std::string & strGenerator)
Definition at line 715 of file RippleAddress.cpp.
References mIsValid, ripple::CBase58Data::SetString(), and VER_FAMILY_GENERATOR.
Referenced by ripple::RPC::accountFromString(), createGeneratorPublic(), and ripple::RPC::getMasterGenerator().
 {
     mIsValid        = SetString (strGenerator.c_str (), VER_FAMILY_GENERATOR);
     return mIsValid;
 }
void ripple::RippleAddress::setGenerator (Blob const & vPublic)
Definition at line 722 of file RippleAddress.cpp.
References mIsValid, ripple::CBase58Data::SetData(), and VER_FAMILY_GENERATOR.
 {
     mIsValid        = true;
     SetData (VER_FAMILY_GENERATOR, vPublic);
 }
bool ripple::RippleAddress::setNodePrivate (const std::string & strPrivate)
Definition at line 257 of file RippleAddress.cpp.
References mIsValid, ripple::CBase58Data::SetString(), and VER_NODE_PRIVATE.
Referenced by createNodePrivate(), ripple::LocalCredentials::nodeIdentityLoad(), and setSeedGeneric().
 {
     mIsValid        = SetString (strPrivate.c_str (), VER_NODE_PRIVATE);
     return mIsValid;
 }
void ripple::RippleAddress::setNodePrivate (Blob const & vPrivate)
Definition at line 264 of file RippleAddress.cpp.
References mIsValid, ripple::CBase58Data::SetData(), and VER_NODE_PRIVATE.
 {
     mIsValid        = true;
     SetData (VER_NODE_PRIVATE, vPrivate);
 }
void ripple::RippleAddress::setNodePrivate (uint256 hash256)
Definition at line 271 of file RippleAddress.cpp.
References ripple::base_uint< BITS >::begin(), mIsValid, ripple::CBase58Data::SetData(), and VER_NODE_PRIVATE.
 {
     mIsValid        = true;
     SetData (VER_NODE_PRIVATE, hash256.begin (), 32);
 }
bool ripple::RippleAddress::setNodePublic (const std::string & strPublic)
Definition at line 154 of file RippleAddress.cpp.
References mIsValid, ripple::CBase58Data::SetString(), and VER_NODE_PUBLIC.
Referenced by createNodePublic(), ripple::RPCHandler::doUnlAdd(), ripple::RPCHandler::doUnlDelete(), ripple::UniqueNodeListImp::getSeedDomains(), ripple::UniqueNodeListImp::getSeedNodes(), ripple::SerializedValidation::getSignerPublic(), ripple::LocalCredentials::nodeIdentityLoad(), ripple::UniqueNodeListImp::processValidators(), ripple::PeerImp::recvCluster(), ripple::PeerImp::recvHello(), ripple::UniqueNodeListImp::responseFetch(), ripple::UniqueNodeListImp::scoreCompute(), and setSeedGeneric().
 {
     mIsValid        = SetString (strPublic.c_str (), VER_NODE_PUBLIC);
     return mIsValid;
 }
void ripple::RippleAddress::setNodePublic (Blob const & vPublic)
Definition at line 161 of file RippleAddress.cpp.
References mIsValid, ripple::CBase58Data::SetData(), and VER_NODE_PUBLIC.
 {
     mIsValid        = true;
     SetData (VER_NODE_PUBLIC, vPublic);
 }
bool ripple::RippleAddress::setSeed (const std::string & strSeed)
Definition at line 817 of file RippleAddress.cpp.
References mIsValid, ripple::CBase58Data::SetString(), and VER_FAMILY_SEED.
Referenced by ripple::CKey_test::run(), setSeed1751(), setSeedGeneric(), and setSeedRandom().
 {
     mIsValid        = SetString (strSeed.c_str (), VER_FAMILY_SEED);
     return mIsValid;
 }
void ripple::RippleAddress::setSeed (uint128 hash128)
Definition at line 862 of file RippleAddress.cpp.
References ripple::base_uint< BITS >::begin(), mIsValid, ripple::CBase58Data::SetData(), and VER_FAMILY_SEED.
 {
     mIsValid        = true;
     SetData (VER_FAMILY_SEED, hash128.begin (), 16);
 }
int ripple::RippleAddress::setSeed1751 (const std::string & strHuman1751)
Definition at line 801 of file RippleAddress.cpp.
References ripple::RFC1751::getKeyFromEnglish(), and setSeed().
Referenced by setSeedGeneric().
 {
     std::string strKey;
     int         iResult = RFC1751::getKeyFromEnglish (strKey, strHuman1751);
     if (1 == iResult)
     {
         Blob    vchLittle (strKey.rbegin (), strKey.rend ());
         uint128     uSeed (vchLittle);
         setSeed (uSeed);
     }
     return iResult;
 }
bool ripple::RippleAddress::setSeedGeneric (const std::string & strText)
Definition at line 824 of file RippleAddress.cpp.
References nothing, ripple::CKey::PassPhraseToKey(), setAccountID(), setAccountPrivate(), setAccountPublic(), ripple::base_uint< BITS >::SetHex(), setNodePrivate(), setNodePublic(), setSeed(), and setSeed1751().
Referenced by ripple::RPC::accountFromString(), createSeedGeneric(), ripple::RPCHandler::doLedgerEntry(), ripple::RPCHandler::doValidationCreate(), ripple::RPCHandler::doWalletAccounts(), ripple::RPCHandler::doWalletPropose(), ripple::RPCHandler::doWalletSeed(), ripple::Config::load(), ripple::RPCParser::parseAccountRaw(), ripple::UniqueNodeListImp::processValidators(), ripple::RippleAddress_test::run(), ripple::RippleIdentifier_test::run(), and ripple::RPC::transactionSign().
 {
     RippleAddress   naTemp;
     bool            bResult = true;
     uint128         uSeed;
     if (strText.empty ()
             || naTemp.setAccountID (strText)
             || naTemp.setAccountPublic (strText)
             || naTemp.setAccountPrivate (strText)
             || naTemp.setNodePublic (strText)
             || naTemp.setNodePrivate (strText))
     {
         bResult = false;
     }
     else if (strText.length () == 32 && uSeed.SetHex (strText, true))
     {
         setSeed (uSeed);
     }
     else if (setSeed (strText))
     {
         // Log::out() << "Recognized seed.";
         nothing ();
     }
     else if (1 == setSeed1751 (strText))
     {
         // Log::out() << "Recognized 1751 seed.";
         nothing ();
     }
     else
     {
         // Log::out() << "Creating seed from pass phrase.";
         setSeed (CKey::PassPhraseToKey (strText));
     }
     return bResult;
 }
void ripple::RippleAddress::setSeedRandom ()
Definition at line 869 of file RippleAddress.cpp.
References ripple::base_uint< BITS >::begin(), ripple::RandomNumbers::fillBytes(), ripple::RandomNumbers::getInstance(), setSeed(), and ripple::base_uint< BITS >::size().
Referenced by createSeedRandom(), ripple::RPCHandler::doValidationCreate(), ripple::RPCHandler::doWalletPropose(), ripple::RPCHandler::doWalletSeed(), and ripple::SerializedTransaction_test::run().
 {
     // XXX Maybe we should call MakeNewKey
     uint128 key;
     RandomNumbers::getInstance ().fillBytes (key.begin (), key.size ());
     RippleAddress::setSeed (key);
 }
void ripple::RippleAddress::signNodePrivate (uint256 const & hash, Blob & vchSig) const
Definition at line 278 of file RippleAddress.cpp.
References getNodePrivate(), ripple::CKey::SetPrivateKeyU(), and ripple::CKey::Sign().
Referenced by ripple::RippleAddress_test::run(), ripple::PeerImp::sendHello(), ripple::SerializedValidation::sign(), and ripple::LedgerProposal::sign().
 {
     CKey    ckPrivKey;
     ckPrivKey.SetPrivateKeyU (getNodePrivate ());
     if (!ckPrivKey.Sign (hash, vchSig))
         throw std::runtime_error ("Signing failed.");
 }
bool ripple::RippleAddress::verifyNodePublic (uint256 const & hash, Blob const & vchSig, ECDSA mustBeFullyCanonical) const
Definition at line 168 of file RippleAddress.cpp.
References getNodePublic(), ripple::isCanonicalECDSASig(), ripple::CKey::SetPubKey(), and ripple::CKey::Verify().
Referenced by ripple::LedgerProposal::checkSign(), ripple::SerializedValidation::isValid(), ripple::PeerImp::recvHello(), and verifyNodePublic().
 {
     CKey    pubkey  = CKey ();
     bool    bVerified;
     bVerified = isCanonicalECDSASig (vchSig, fullyCanonical);
     if (bVerified && !pubkey.SetPubKey (getNodePublic ()))
     {
         // Failed to set public key.
         bVerified   = false;
     }
     else
     {
         bVerified   = pubkey.Verify (hash, vchSig);
     }
     return bVerified;
 }
bool ripple::RippleAddress::verifyNodePublic (uint256 const & hash, const std::string & strSig, ECDSA mustBeFullyCanonical) const
Definition at line 188 of file RippleAddress.cpp.
References verifyNodePublic().
 {
     Blob vchSig (strSig.begin (), strSig.end ());
     return verifyNodePublic (hash, vchSig, fullyCanonical);
 }
Member Data Documentation
bool ripple::RippleAddress::mIsValid private
Definition at line 58 of file RippleAddress.h.
Referenced by clear(), isValid(), setAccountID(), setAccountPrivate(), setAccountPublic(), setGenerator(), setNodePrivate(), setNodePublic(), and setSeed().
The documentation for this class was generated from the following files:
rippled/src/ripple_data/protocol/RippleAddress.h
rippled/src/ripple_data/protocol/RippleAddress.cpp