rippled: ripple::HTTPClient Class Reference
ripple::HTTPClient Class Reference
#include <HTTPClient.h>
Public Types
enum { maxClientHeaderBytes = 32 * 1024 }
enum { smsTimeoutSeconds = 30 }
Static Public Member Functions
static void initializeSSLContext ()
static void get (bool bSSL, boost::asio::io_service &io_service, std::deque< std::string > deqSites, const unsigned short port, const std::string &strPath, std::size_t responseMax, boost::posix_time::time_duration timeout, std::function< bool(const boost::system::error_code &ecResult, int iStatus, const std::string &strData)> complete)
static void get (bool bSSL, boost::asio::io_service &io_service, std::string strSite, const unsigned short port, const std::string &strPath, std::size_t responseMax, boost::posix_time::time_duration timeout, std::function< bool(const boost::system::error_code &ecResult, int iStatus, const std::string &strData)> complete)
static void request (bool bSSL, boost::asio::io_service &io_service, std::string strSite, const unsigned short port, std::function< void(boost::asio::streambuf &sb, const std::string &strHost)> build, std::size_t responseMax, boost::posix_time::time_duration timeout, std::function< bool(const boost::system::error_code &ecResult, int iStatus, const std::string &strData)> complete)
static void sendSMS (boost::asio::io_service &io_service, const std::string &strText)
Detailed Description
Provides an asynchronous HTTP client implementation with optional SSL.
Definition at line 27 of file HTTPClient.h.
Member Enumeration Documentation
anonymous enum
Enumerator
maxClientHeaderBytes
Definition at line 30 of file HTTPClient.h.
     {
         maxClientHeaderBytes = 32 * 1024
     };
anonymous enum
Enumerator
smsTimeoutSeconds
Definition at line 67 of file HTTPClient.h.
     {
         smsTimeoutSeconds = 30
     };
Member Function Documentation
void ripple::HTTPClient::get (bool bSSL, boost::asio::io_service & io_service, std::deque< std::string > deqSites, const unsigned short port, const std::string & strPath, std::size_t responseMax, boost::posix_time::time_duration timeout, std::function< bool(const boost::system::error_code &ecResult, int iStatus, const std::string &strData)> complete) static
Definition at line 524 of file HTTPClient.cpp.
Referenced by ripple::UniqueNodeListImp::fetchProcess(), ripple::UniqueNodeListImp::getIpsUrl(), ripple::UniqueNodeListImp::getValidatorsUrl(), and ripple::UniqueNodeListImp::nodeNetwork().
 {
     boost::shared_ptr <HTTPClientImp> client (
         new HTTPClientImp (io_service, port, responseMax));
     client->get (bSSL, deqSites, strPath, timeout, complete);
 }
void ripple::HTTPClient::get (bool bSSL, boost::asio::io_service & io_service, std::string strSite, const unsigned short port, const std::string & strPath, std::size_t responseMax, boost::posix_time::time_duration timeout, std::function< bool(const boost::system::error_code &ecResult, int iStatus, const std::string &strData)> complete) static
Definition at line 541 of file HTTPClient.cpp.
 {
     std::deque<std::string> deqSites (1, strSite);
     boost::shared_ptr <HTTPClientImp> client (
         new HTTPClientImp (io_service, port, responseMax));
     client->get (bSSL, deqSites, strPath, timeout, complete);
 }
void ripple::HTTPClient::initializeSSLContext () static
Definition at line 77 of file HTTPClient.cpp.
Referenced by ripple::Config::setup().
 {
     beast::SharedSingleton <HTTPClientSSLContext>::get();
 }
void ripple::HTTPClient::request (bool bSSL, boost::asio::io_service & io_service, std::string strSite, const unsigned short port, std::function< void(boost::asio::streambuf &sb, const std::string &strHost)> build, std::size_t responseMax, boost::posix_time::time_duration timeout, std::function< bool(const boost::system::error_code &ecResult, int iStatus, const std::string &strData)> complete) static
Definition at line 560 of file HTTPClient.cpp.
Referenced by ripple::RPCCall::fromNetwork().
 {
     std::deque<std::string> deqSites (1, strSite);
     boost::shared_ptr <HTTPClientImp> client (
         new HTTPClientImp (io_service, port, responseMax));
     client->request (bSSL, deqSites, setRequest, timeout, complete);
 }
void ripple::HTTPClient::sendSMS (boost::asio::io_service & io_service, const std::string & strText) static
Definition at line 579 of file HTTPClient.cpp.
References BIND_TYPE, ripple::getConfig(), ripple::lsINFO, ripple::lsWARNING, maxClientHeaderBytes, ripple::HTTPClientImp::onSMSResponse(), P_1, P_2, P_3, ripple::parseUrl(), ripple::Config::SMS_FROM, ripple::Config::SMS_KEY, ripple::Config::SMS_SECRET, ripple::Config::SMS_TO, ripple::Config::SMS_URL, smsTimeoutSeconds, ripple::urlEncode(), and WriteLog.
Referenced by ripple::RPCHandler::doSMS().
 {
     std::string strScheme;
     std::string strDomain;
     int         iPort;
     std::string strPath;
     if (getConfig ().SMS_URL == "" || !parseUrl (getConfig ().SMS_URL, strScheme, strDomain, iPort, strPath))
     {
         WriteLog (lsWARNING, HTTPClient) << "SMSRequest: Bad URL:" << getConfig ().SMS_URL;
     }
     else
     {
         bool const bSSL = strScheme == "https";
         std::deque<std::string> deqSites (1, strDomain);
         std::string strURI  =
             boost::str (boost::format ("%s?from=%s&to=%s&api_key=%s&api_secret=%s&text=%s")
                         % (strPath.empty () ? "/" : strPath)
                         % getConfig ().SMS_FROM
                         % getConfig ().SMS_TO
                         % getConfig ().SMS_KEY
                         % getConfig ().SMS_SECRET
                         % urlEncode (strText));
         // WriteLog (lsINFO) << "SMS: Request:" << strURI;
         WriteLog (lsINFO, HTTPClient) << "SMS: Request: '" << strText << "'";
         if (iPort < 0)
             iPort = bSSL ? 443 : 80;
         boost::shared_ptr <HTTPClientImp> client (
             new HTTPClientImp (io_service, iPort, maxClientHeaderBytes));
         client->get (bSSL, deqSites, strURI, boost::posix_time::seconds (smsTimeoutSeconds),
                             BIND_TYPE (&HTTPClientImp::onSMSResponse, P_1, P_2, P_3));
     }
 }
The documentation for this class was generated from the following files:
rippled/src/ripple_net/basics/HTTPClient.h
rippled/src/ripple_net/basics/HTTPClient.cpp