rippled: beast::SemanticVersion_test Class Reference
beast::SemanticVersion_test Class Reference
Public Member Functions
void checkPass (String const &input, bool shouldPass=true)
void checkFail (String const &input)
void checkMeta (String const &input, bool shouldPass)
void checkMetaFail (String const &input)
void checkRelease (String const &input, bool shouldPass=true)
void check (String const &input, bool shouldPass=true)
void negcheck (String const &input)
void testParse ()
void checkValues (String const &input, int majorVersion, int minorVersion, int patchVersion, StringArray const &preReleaseIdentifiers=StringArray(), StringArray const &metaData=StringArray())
void testValues ()
void checkLessInternal (String const &lhs, String const &rhs)
void checkLess (String const &lhs, String const &rhs)
void testCompare ()
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Static Public Member Functions
static StringArray ids ()
static StringArray ids (String const &s1)
static StringArray ids (String const &s1, String const &s2)
static StringArray ids (String const &s1, String const &s2, String const &s3)
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 292 of file SemanticVersion.cpp.
Member Function Documentation
void beast::SemanticVersion_test::check (String const & input, bool shouldPass = true) inline
Definition at line 365 of file SemanticVersion.cpp.
References checkRelease().
Referenced by negcheck(), and testParse().
     {
         checkRelease (input, shouldPass);
     }
void beast::SemanticVersion_test::checkFail (String const & input) inline
Definition at line 310 of file SemanticVersion.cpp.
References checkPass().
Referenced by checkMeta().
     {
         checkPass (input, false);
     }
void beast::SemanticVersion_test::checkLess (String const & lhs, String const & rhs) inline
Definition at line 491 of file SemanticVersion.cpp.
References checkLessInternal().
Referenced by testCompare().
     {
         checkLessInternal (lhs, rhs);
         checkLessInternal (lhs + "+meta", rhs);
         checkLessInternal (lhs, rhs + "+meta");
         checkLessInternal (lhs + "+meta", rhs + "+meta");
     }
void beast::SemanticVersion_test::checkLessInternal (String const & lhs, String const & rhs) inline
Definition at line 472 of file SemanticVersion.cpp.
References beast::SemanticVersion::compare(), beast::unit_test::suite::expect(), and beast::SemanticVersion::parse().
Referenced by checkLess().
     {
         SemanticVersion left;
         SemanticVersion right;
         expect (left.parse (lhs));
         expect (right.parse (rhs));
         expect (left.compare (left) == 0);
         expect (right.compare (right) == 0);
         expect (left.compare (right) < 0);
         expect (right.compare (left) > 0);
         expect (left < right);
         expect (right > left);
         expect (left == left);
         expect (right == right);
     }
void beast::SemanticVersion_test::checkMeta (String const & input, bool shouldPass) inline
Definition at line 316 of file SemanticVersion.cpp.
References checkFail(), and checkPass().
Referenced by checkMetaFail(), and checkRelease().
     {
         checkPass (input, shouldPass);
         checkPass (input + "+a", shouldPass);
         checkPass (input + "+1", shouldPass);
         checkPass (input + "+a.b", shouldPass);
         checkPass (input + "+ab.cd", shouldPass);
         checkFail (input + "!");
         checkFail (input + "+");
         checkFail (input + "++");
         checkFail (input + "+!");
         checkFail (input + "+.");
         checkFail (input + "+a.!");
     }
void beast::SemanticVersion_test::checkMetaFail (String const & input) inline
Definition at line 333 of file SemanticVersion.cpp.
References checkMeta().
Referenced by checkRelease().
     {
         checkMeta (input, false);
     }
void beast::SemanticVersion_test::checkPass (String const & input, bool shouldPass = true) inline
Definition at line 295 of file SemanticVersion.cpp.
References beast::unit_test::suite::expect(), beast::SemanticVersion::parse(), and beast::SemanticVersion::print().
Referenced by checkFail(), and checkMeta().
     {
         SemanticVersion v;
         if (shouldPass )
         {
             expect (v.parse (input));
             expect (v.print () == input);
         }
         else
         {
             expect (! v.parse (input));
         }
     }
void beast::SemanticVersion_test::checkRelease (String const & input, bool shouldPass = true) inline
Definition at line 342 of file SemanticVersion.cpp.
References checkMeta(), and checkMetaFail().
Referenced by check().
     {
         checkMeta (input, shouldPass);
         checkMeta (input + "-1", shouldPass);
         checkMeta (input + "-a", shouldPass);
         checkMeta (input + "-a1", shouldPass);
         checkMeta (input + "-a1.b1", shouldPass);
         checkMeta (input + "-ab.cd", shouldPass);
         checkMeta (input + "--", shouldPass);
         checkMetaFail (input + "+");
         checkMetaFail (input + "!");
         checkMetaFail (input + "-");
         checkMetaFail (input + "-!");
         checkMetaFail (input + "-.");
         checkMetaFail (input + "-a.!");
         checkMetaFail (input + "-0.a");
     }
void beast::SemanticVersion_test::checkValues (String const & input, int majorVersion, int minorVersion, int patchVersion, StringArray const & preReleaseIdentifiers = StringArray (), StringArray const & metaData = StringArray ()) inline
Definition at line 438 of file SemanticVersion.cpp.
References beast::unit_test::suite::expect(), beast::SemanticVersion::majorVersion, beast::SemanticVersion::metaData, beast::SemanticVersion::minorVersion, beast::SemanticVersion::parse(), beast::SemanticVersion::patchVersion, and beast::SemanticVersion::preReleaseIdentifiers.
Referenced by testValues().
     {
         SemanticVersion v;
         expect (v.parse (input));
         expect (v.majorVersion == majorVersion);
         expect (v.minorVersion == minorVersion);
         expect (v.patchVersion == patchVersion);
         expect (v.preReleaseIdentifiers == preReleaseIdentifiers);
         expect (v.metaData == metaData);
     }
static StringArray beast::SemanticVersion_test::ids () inline static
Definition at line 408 of file SemanticVersion.cpp.
Referenced by testValues().
     {
         return StringArray ();
     }
static StringArray beast::SemanticVersion_test::ids (String const & s1) inline static
Definition at line 413 of file SemanticVersion.cpp.
References beast::StringArray::add().
     {
         StringArray v;
         v.add (s1);
         return v;
     }
static StringArray beast::SemanticVersion_test::ids (String const & s1, String const & s2) inline static
Definition at line 420 of file SemanticVersion.cpp.
References beast::StringArray::add().
     {
         StringArray v;
         v.add (s1);
         v.add (s2);
         return v;
     }
static StringArray beast::SemanticVersion_test::ids (String const & s1, String const & s2, String const & s3) inline static
Definition at line 428 of file SemanticVersion.cpp.
References beast::StringArray::add().
     {
         StringArray v;
         v.add (s1);
         v.add (s2);
         v.add (s3);
         return v;
     }
void beast::SemanticVersion_test::negcheck (String const & input) inline
Definition at line 370 of file SemanticVersion.cpp.
References check().
Referenced by testParse().
     {
         check (input, false);
     }
void beast::SemanticVersion_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 511 of file SemanticVersion.cpp.
References testCompare(), testParse(), and testValues().
     {
         testParse ();
         testValues ();
         testCompare ();
     }
void beast::SemanticVersion_test::testCompare () inline
Definition at line 499 of file SemanticVersion.cpp.
References checkLess().
Referenced by run().
     {
         checkLess ("1.0.0-alpha", "1.0.0-alpha.1");
         checkLess ("1.0.0-alpha.1", "1.0.0-alpha.beta");
         checkLess ("1.0.0-alpha.beta", "1.0.0-beta");
         checkLess ("1.0.0-beta", "1.0.0-beta.2");
         checkLess ("1.0.0-beta.2", "1.0.0-beta.11");
         checkLess ("1.0.0-beta.11", "1.0.0-rc.1");
         checkLess ("1.0.0-rc.1", "1.0.0");
         checkLess ("0.9.9", "1.0.0");
     }
void beast::SemanticVersion_test::testParse () inline
Definition at line 375 of file SemanticVersion.cpp.
References check(), negcheck(), and beast::unit_test::suite::testcase().
Referenced by run().
     {
         testcase ("parse");
         check ("0.0.0");
         check ("1.2.3");
         check ("2147483647.2147483647.2147483647"); // max int
         // negative values
         negcheck ("-1.2.3");
         negcheck ("1.-2.3");
         negcheck ("1.2.-3");
         // missing parts
         negcheck ("");
         negcheck ("1");
         negcheck ("1.");
         negcheck ("1.2");
         negcheck ("1.2.");
         negcheck (".2.3");
         // whitespace
         negcheck (" 1.2.3");
         negcheck ("1 .2.3");
         negcheck ("1.2 .3");
         negcheck ("1.2.3 ");
         // leading zeroes
         negcheck ("01.2.3");
         negcheck ("1.02.3");
         negcheck ("1.2.03");
     }
void beast::SemanticVersion_test::testValues () inline
Definition at line 457 of file SemanticVersion.cpp.
References checkValues(), and ids().
Referenced by run().
     {
         checkValues ("0.1.2", 0, 1, 2);
         checkValues ("1.2.3", 1, 2, 3);
         checkValues ("1.2.3-rc1", 1, 2, 3, ids ("rc1"));
         checkValues ("1.2.3-rc1.debug", 1, 2, 3, ids ("rc1", "debug"));
         checkValues ("1.2.3-rc1.debug.asm", 1, 2, 3, ids ("rc1", "debug", "asm"));
         checkValues ("1.2.3+full", 1, 2, 3, ids (), ids ("full"));
         checkValues ("1.2.3+full.prod", 1, 2, 3, ids (), ids ("full", "prod"));
         checkValues ("1.2.3+full.prod.x86", 1, 2, 3, ids (), ids ("full", "prod", "x86"));
         checkValues ("1.2.3-rc1.debug.asm+full.prod.x86", 1, 2, 3,
             ids ("rc1", "debug", "asm"), ids ("full", "prod", "x86"));
     }
The documentation for this class was generated from the following file:
rippled/src/beast/modules/beast_core/diagnostic/SemanticVersion.cpp