rippled: ripple::Validators::SourceURLImp Class Reference
ripple::Validators::SourceURLImp Class Reference
Public Member Functions
SourceURLImp (beast::URL const &url)
~SourceURLImp ()
std::string to_string () const
beast::String uniqueID () const
beast::String createParam ()
void cancel ()
void fetch (Results &results, beast::Journal journal)
Private Attributes
beast::URL m_url
std::unique_ptr
< beast::asio::HTTPClientBase > m_client
Additional Inherited Members
Static Public Member Functions inherited from ripple::Validators::SourceURL
static SourceURL * New (beast::URL const &url)
Protected Member Functions inherited from beast::SharedObject
SharedObject ()
virtual ~SharedObject ()
virtual void destroy () const
void resetReferenceCount () noexcept
Detailed Description
Definition at line 25 of file SourceURL.cpp.
Constructor & Destructor Documentation
ripple::Validators::SourceURLImp::SourceURLImp (beast::URL const & url) inline explicit
Definition at line 30 of file SourceURL.cpp.
         : m_url (url)
         , m_client (beast::asio::HTTPClientBase::New ())
     {
     }
ripple::Validators::SourceURLImp::~SourceURLImp () inline
Definition at line 36 of file SourceURL.cpp.
     {
     }
Member Function Documentation
void ripple::Validators::SourceURLImp::cancel () inline virtual
Cancel any pending fetch. The default implementation does nothing.
Reimplemented from ripple::Validators::Source.
Definition at line 58 of file SourceURL.cpp.
References m_client.
     {
         m_client->cancel ();
     }
beast::String ripple::Validators::SourceURLImp::createParam () inline virtual
A string that is used to recreate the source from the database entry.
Implements ripple::Validators::Source.
Definition at line 53 of file SourceURL.cpp.
References m_url, and beast::URL::toString().
     {
         return m_url.toString();
     }
void ripple::Validators::SourceURLImp::fetch (Results & results, beast::Journal journal) inline virtual
Implements ripple::Validators::Source.
Definition at line 63 of file SourceURL.cpp.
References beast::Journal::error, m_client, m_url, and ripple::Validators::Utilities::processLines().
     {
         auto httpResult (m_client->get (m_url));
         if (httpResult.first == 0)
         {
             Utilities::ParseResultLine lineFunction (results, journal);
             std::string const s (httpResult.second->body().to_string());
             Utilities::processLines (s.begin(), s.end(), lineFunction);
         }
         else
         {
             journal.error <<
                 "HTTP GET to " << m_url <<
                 " failed: '" << httpResult.first.message () << "'";
         }
     }
std::string ripple::Validators::SourceURLImp::to_string () const inline virtual
The name of the source, used in diagnostic output.
Implements ripple::Validators::Source.
Definition at line 40 of file SourceURL.cpp.
References m_url, and beast::URL::to_string().
     {
         std::stringstream ss;
         ss <<
             "URL: '" << m_url.to_string() << "'";
         return ss.str();
     }
beast::String ripple::Validators::SourceURLImp::uniqueID () const inline virtual
An identifier that uniquely describes the source. This is used for identification in the database.
Implements ripple::Validators::Source.
Definition at line 48 of file SourceURL.cpp.
References m_url, and beast::URL::toString().
     {
         return "URL," + m_url.toString();
     }
Member Data Documentation
std::unique_ptr<beast::asio::HTTPClientBase> ripple::Validators::SourceURLImp::m_client private
Definition at line 83 of file SourceURL.cpp.
Referenced by cancel(), and fetch().
beast::URL ripple::Validators::SourceURLImp::m_url private
Definition at line 82 of file SourceURL.cpp.
Referenced by createParam(), fetch(), to_string(), and uniqueID().
The documentation for this class was generated from the following file:
rippled/src/ripple/validators/impl/SourceURL.cpp