rippled: ripple::ContinuousLedgerTiming Class Reference
ripple::ContinuousLedgerTiming Class Reference
#include <LedgerTiming.h>
Static Public Member Functions
static bool shouldClose (bool anyTransactions, int previousProposers, int proposersClosed, int proposerersValidated, int previousMSeconds, int currentMSeconds, int openMSeconds, int idleInterval)
static bool haveConsensus (int previousProposers, int currentProposers, int currentAgree, int currentClosed, int previousAgreeTime, int currentAgreeTime, bool forReal, bool &failed)
static int getNextLedgerTimeResolution (int previousResolution, bool previousAgree, int ledgerSeq)
Static Public Attributes
static int LedgerTimeResolution [] = { 10, 10, 20, 30, 60, 90, 120, 120 }
Detailed Description
Definition at line 79 of file LedgerTiming.h.
Member Function Documentation
int ripple::ContinuousLedgerTiming::getNextLedgerTimeResolution (int previousResolution, bool previousAgree, int ledgerSeq) static
Definition at line 152 of file LedgerTiming.cpp.
References LEDGER_RES_DECREASE, LEDGER_RES_INCREASE, and LedgerTimeResolution.
Referenced by ripple::LedgerConsensusImp::handleLCL(), ripple::Ledger::Ledger(), and ripple::LedgerConsensusImp::LedgerConsensusImp().
 {
     assert (ledgerSeq);
     if ((!previousAgree) && ((ledgerSeq % LEDGER_RES_DECREASE) == 0))
     {
         // reduce resolution
         int i = 1;
         while (LedgerTimeResolution[i] != previousResolution)
             ++i;
         return LedgerTimeResolution[i + 1];
     }
     if ((previousAgree) && ((ledgerSeq % LEDGER_RES_INCREASE) == 0))
     {
         // increase resolution
         int i = 1;
         while (LedgerTimeResolution[i] != previousResolution)
             ++i;
         return LedgerTimeResolution[i - 1];
     }
     return previousResolution;
 }
bool ripple::ContinuousLedgerTiming::haveConsensus (int previousProposers, int currentProposers, int currentAgree, int currentClosed, int previousAgreeTime, int currentAgreeTime, bool forReal, bool & failed) static
Definition at line 99 of file LedgerTiming.cpp.
References CondLog, LEDGER_MIN_CONSENSUS, ripple::lsINFO, ripple::lsTRACE, ripple::lsWARNING, and WriteLog.
Referenced by ripple::LedgerConsensusImp::haveConsensus().
 {
     WriteLog (lsTRACE, LedgerTiming) <<
         "CLC::haveConsensus: prop=" << currentProposers <<
         "/" << previousProposers <<
         " agree=" << currentAgree << " validated=" << currentFinished <<
         " time=" << currentAgreeTime <<  "/" << previousAgreeTime <<
         (forReal ? "" : "X");
     if (currentAgreeTime <= LEDGER_MIN_CONSENSUS)
         return false;
     if (currentProposers < (previousProposers * 3 / 4))
     {
         // Less than 3/4 of the last ledger's proposers are present, we may need more time
         if (currentAgreeTime < (previousAgreeTime + LEDGER_MIN_CONSENSUS))
         {
             CondLog (forReal, lsTRACE, LedgerTiming) <<
                 "too fast, not enough proposers";
             return false;
         }
     }
     // If 80% of current proposers (plus us) agree on a set, we have consensus
     if (((currentAgree * 100 + 100) / (currentProposers + 1)) > 80)
     {
         CondLog (forReal, lsINFO, LedgerTiming) << "normal consensus";
         failed = false;
         return true;
     }
     // If 80% of the nodes on your UNL have moved on, you should declare consensus
     if (((currentFinished * 100) / (currentProposers + 1)) > 80)
     {
         CondLog (forReal, lsWARNING, LedgerTiming) <<
             "We see no consensus, but 80% of nodes have moved on";
         failed = true;
         return true;
     }
     // no consensus yet
     CondLog (forReal, lsTRACE, LedgerTiming) << "no consensus";
     return false;
 }
bool ripple::ContinuousLedgerTiming::shouldClose (bool anyTransactions, int previousProposers, int proposersClosed, int proposerersValidated, int previousMSeconds, int currentMSeconds, int openMSeconds, int idleInterval) static
Definition at line 33 of file LedgerTiming.cpp.
References LEDGER_IDLE_INTERVAL, LEDGER_MIN_CLOSE, ripple::lsDEBUG, ripple::lsTRACE, ripple::lsWARNING, and WriteLog.
Referenced by ripple::LedgerConsensusImp::statePreClose().
 {
     if ((previousMSeconds < -1000) || (previousMSeconds > 600000) ||
             (currentMSeconds < -1000) || (currentMSeconds > 600000))
     {
         WriteLog (lsWARNING, LedgerTiming) <<
             "CLC::shouldClose range Trans=" << (anyTransactions ? "yes" : "no") <<
             " Prop: " << previousProposers << "/" << proposersClosed <<
             " Secs: " << currentMSeconds << " (last: " << previousMSeconds << ")";
         return true;
     }
     if (!anyTransactions)
     {
         // no transactions so far this interval
         if (proposersClosed > (previousProposers / 4)) // did we miss a transaction?
         {
             WriteLog (lsTRACE, LedgerTiming) <<
                 "no transactions, many proposers: now (" << proposersClosed <<
                 " closed, " << previousProposers << " before)";
             return true;
         }
 #if 0 // This false triggers on the genesis ledger
         if (previousMSeconds > (1000 * (LEDGER_IDLE_INTERVAL + 2))) // the last ledger was very slow to close
         {
             WriteLog (lsTRACE, LedgerTiming) << "was slow to converge (p=" << (previousMSeconds) << ")";
             if (previousMSeconds < 2000)
                 return previousMSeconds;
             return previousMSeconds - 1000;
         }
 #endif
         return currentMSeconds >= (idleInterval * 1000); // normal idle
     }
     if ((openMSeconds < LEDGER_MIN_CLOSE) && ((proposersClosed + proposersValidated) < (previousProposers / 2 )))
     {
         WriteLog (lsDEBUG, LedgerTiming) <<
             "Must wait minimum time before closing";
         return false;
     }
     if ((currentMSeconds < previousMSeconds) && ((proposersClosed + proposersValidated) < previousProposers))
     {
         WriteLog (lsDEBUG, LedgerTiming) <<
             "We are waiting for more closes/validations";
         return false;
     }
     return true; // this ledger should close now
 }
Member Data Documentation
int ripple::ContinuousLedgerTiming::LedgerTimeResolution = { 10, 10, 20, 30, 60, 90, 120, 120 } static
Definition at line 83 of file LedgerTiming.h.
Referenced by getNextLedgerTimeResolution().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/ledger/LedgerTiming.h
rippled/src/ripple_app/ledger/LedgerTiming.cpp