rippled: ripple::RPCParser Class Reference
ripple::RPCParser Class Reference
Public Member Functions
Json::Value parseCommand (std::string strMethod, Json::Value jvParams, bool allowAnyCommand)
Static Public Member Functions
static std::string EncodeBase64 (const std::string &s)
Private Types
typedef Json::Value(RPCParser::* parseFuncPtr)(const Json::Value &jvParams)
Private Member Functions
Json::Value parseAsIs (const Json::Value &jvParams)
Json::Value parseInternal (const Json::Value &jvParams)
Json::Value parseFetchInfo (const Json::Value &jvParams)
Json::Value parseAccountTransactions (const Json::Value &jvParams)
Json::Value parseTxAccount (const Json::Value &jvParams)
Json::Value parseBookOffers (const Json::Value &jvParams)
Json::Value parseConnect (const Json::Value &jvParams)
Json::Value parseEvented (const Json::Value &jvParams)
Json::Value parseFeature (const Json::Value &jvParams)
Json::Value parseGetCounts (const Json::Value &jvParams)
Json::Value parseJson (const Json::Value &jvParams)
Json::Value parseLedger (const Json::Value &jvParams)
Json::Value parseLedgerId (const Json::Value &jvParams)
Json::Value parseLogLevel (const Json::Value &jvParams)
Json::Value parseAccountItems (const Json::Value &jvParams)
Json::Value parseAccountCurrencies (const Json::Value &jvParams)
Json::Value parseAccountLines (const Json::Value &jvParams)
Json::Value parseAccountRaw (const Json::Value &jvParams, bool bPeer)
Json::Value parseProofCreate (const Json::Value &jvParams)
Json::Value parseProofSolve (const Json::Value &jvParams)
Json::Value parseProofVerify (const Json::Value &jvParams)
Json::Value parseRipplePathFind (const Json::Value &jvParams)
Json::Value parseSignSubmit (const Json::Value &jvParams)
Json::Value parseSMS (const Json::Value &jvParams)
Json::Value parseTx (const Json::Value &jvParams)
Json::Value parseTxHistory (const Json::Value &jvParams)
Json::Value parseUnlAdd (const Json::Value &jvParams)
Json::Value parseUnlDelete (const Json::Value &jvParams)
Json::Value parseValidationCreate (const Json::Value &jvParams)
Json::Value parseValidationSeed (const Json::Value &jvParams)
Json::Value parseWalletAccounts (const Json::Value &jvParams)
Json::Value parseWalletPropose (const Json::Value &jvParams)
Json::Value parseWalletSeed (const Json::Value &jvParams)
Static Private Member Functions
static bool jvParseLedger (Json::Value &jvRequest, const std::string &strLedger)
static Json::Value jvParseCurrencyIssuer (const std::string &strCurrencyIssuer)
Detailed Description
Definition at line 37 of file RPCCall.cpp.
Member Typedef Documentation
typedef Json::Value(RPCParser::* ripple::RPCParser::parseFuncPtr)(const Json::Value &jvParams) private
Definition at line 91 of file RPCCall.cpp.
Member Function Documentation
static std::string ripple::RPCParser::EncodeBase64 (const std::string & s) inline static
Definition at line 754 of file RPCCall.cpp.
Referenced by ripple::RPCCall::fromNetwork().
     {
         // FIXME: This performs terribly
         BIO* b64, *bmem;
         BUF_MEM* bptr;
         // VFALCO TODO What the heck is BIO and BUF_MEM!?
         //             Surely we don't need OpenSSL or dynamic allocations
         //             to perform a base64 encoding...
         //
         b64 = BIO_new (BIO_f_base64 ());
         BIO_set_flags (b64, BIO_FLAGS_BASE64_NO_NL);
         bmem = BIO_new (BIO_s_mem ());
         b64 = BIO_push (b64, bmem);
         BIO_write (b64, s.data (), s.size ());
         (void) BIO_flush (b64);
         BIO_get_mem_ptr (b64, &bptr);
         std::string result (bptr->data, bptr->length);
         BIO_free_all (b64);
         return result;
     }
static Json::Value ripple::RPCParser::jvParseCurrencyIssuer (const std::string & strCurrencyIssuer) inline static private
Definition at line 61 of file RPCCall.cpp.
References ripple::RPC::make_param_error(), and Json::objectValue.
Referenced by parseBookOffers().
     {
         static boost::regex reCurIss ("\\`([[:alpha:]]{3})(?:/(.+))?\\'");
         boost::smatch   smMatch;
         if (boost::regex_match (strCurrencyIssuer, smMatch, reCurIss))
         {
             Json::Value jvResult (Json::objectValue);
             std::string strCurrency = smMatch[1];
             std::string strIssuer   = smMatch[2];
             jvResult["currency"]    = strCurrency;
             if (strIssuer.length ())
             {
                 // Could confirm issuer is a valid Ripple address.
                 jvResult["issuer"]      = strIssuer;
             }
             return jvResult;
         }
         else
         {
             return RPC::make_param_error (std::string ("Invalid currency/issuer '") +
                     strCurrencyIssuer + "'");
         }
     }
static bool ripple::RPCParser::jvParseLedger (Json::Value & jvRequest, const std::string & strLedger) inline static private
Definition at line 41 of file RPCCall.cpp.
Referenced by parseAccountRaw(), parseAccountTransactions(), parseBookOffers(), parseLedger(), parseRipplePathFind(), and parseTxAccount().
     {
         if (strLedger == "current" || strLedger == "closed" || strLedger == "validated")
         {
             jvRequest["ledger_index"]   = strLedger;
         }
         else if (strLedger.length () == 64)
         {
             // YYY Could confirm this is a uint256.
             jvRequest["ledger_hash"]    = strLedger;
         }
         else
         {
             jvRequest["ledger_index"]   = beast::lexicalCast <std::uint32_t> (strLedger);
         }
         return true;
     }
Json::Value ripple::RPCParser::parseAccountCurrencies (const Json::Value & jvParams) inline private
Definition at line 457 of file RPCCall.cpp.
References parseAccountRaw().
Referenced by parseCommand().
     {
         return parseAccountRaw (jvParams, false);
     }
Json::Value ripple::RPCParser::parseAccountItems (const Json::Value & jvParams) inline private
Definition at line 452 of file RPCCall.cpp.
References parseAccountRaw().
Referenced by parseCommand().
     {
         return parseAccountRaw (jvParams, false);
     }
Json::Value ripple::RPCParser::parseAccountLines (const Json::Value & jvParams) inline private
Definition at line 463 of file RPCCall.cpp.
References parseAccountRaw().
Referenced by parseCommand().
     {
         return parseAccountRaw (jvParams, true);
     }
Json::Value ripple::RPCParser::parseAccountRaw (const Json::Value & jvParams, bool bPeer) inline private
Definition at line 469 of file RPCCall.cpp.
References Json::Value::asString(), jvParseLedger(), Json::objectValue, ripple::rpcACT_MALFORMED, ripple::rpcError(), ripple::rpcLGR_IDX_MALFORMED, ripple::RippleAddress::setAccountID(), ripple::RippleAddress::setAccountPublic(), ripple::RippleAddress::setSeedGeneric(), and Json::Value::size().
Referenced by parseAccountCurrencies(), parseAccountItems(), and parseAccountLines().
     {
         std::string     strIdent    = jvParams[0u].asString ();
         unsigned int    iCursor     = jvParams.size ();
         bool            bStrict     = false;
         std::string     strPeer;
         if (!bPeer && iCursor >= 2 && jvParams[iCursor - 1] == "strict")
         {
             bStrict = true;
             --iCursor;
         }
         if (bPeer && iCursor >= 2)
             strPeer = jvParams[iCursor].asString ();
         int             iIndex      = 0;
         //  int             iIndex      = jvParams.size() >= 2 ? beast::lexicalCast <int>(jvParams[1u].asString()) : 0;
         RippleAddress   raAddress;
         if (!raAddress.setAccountPublic (strIdent) && !raAddress.setAccountID (strIdent) && !raAddress.setSeedGeneric (strIdent))
             return rpcError (rpcACT_MALFORMED);
         // Get info on account.
         Json::Value jvRequest (Json::objectValue);
         jvRequest["account"]    = strIdent;
         if (bStrict)
             jvRequest["strict"]     = 1;
         if (iIndex)
             jvRequest["account_index"]  = iIndex;
         if (!strPeer.empty ())
         {
             RippleAddress   raPeer;
             if (!raPeer.setAccountPublic (strPeer) && !raPeer.setAccountID (strPeer) && !raPeer.setSeedGeneric (strPeer))
                 return rpcError (rpcACT_MALFORMED);
             jvRequest["peer"]   = strPeer;
         }
         if (iCursor == (2 + bPeer) && !jvParseLedger (jvRequest, jvParams[1u + bPeer].asString ()))
             return rpcError (rpcLGR_IDX_MALFORMED);
         return jvRequest;
     }
Json::Value ripple::RPCParser::parseAccountTransactions (const Json::Value & jvParams) inline private
Definition at line 131 of file RPCCall.cpp.
References Json::Value::asInt(), Json::Value::asString(), ripple::RippleAddress::humanAccountID(), jvParseLedger(), nothing, Json::objectValue, ripple::rpcACT_MALFORMED, ripple::rpcError(), ripple::rpcLGR_IDXS_INVALID, ripple::RippleAddress::setAccountID(), and Json::Value::size().
Referenced by parseCommand().
     {
         Json::Value     jvRequest (Json::objectValue);
         RippleAddress   raAccount;
         unsigned int    iParams = jvParams.size ();
         if (!raAccount.setAccountID (jvParams[0u].asString ()))
             return rpcError (rpcACT_MALFORMED);
         jvRequest["account"]    = raAccount.humanAccountID ();
         bool            bDone   = false;
         while (!bDone && iParams >= 2)
         {
             if (jvParams[iParams - 1].asString () == "binary")
             {
                 jvRequest["binary"]     = true;
                 --iParams;
             }
             else if (jvParams[iParams - 1].asString () == "count")
             {
                 jvRequest["count"]      = true;
                 --iParams;
             }
             else if (jvParams[iParams - 1].asString () == "descending")
             {
                 jvRequest["descending"] = true;
                 --iParams;
             }
             else
             {
                 bDone   = true;
             }
         }
         if (1 == iParams)
         {
             nothing ();
         }
         else if (2 == iParams)
         {
             if (!jvParseLedger (jvRequest, jvParams[1u].asString ()))
                 return jvRequest;
         }
         else
         {
             std::int64_t   uLedgerMin  = jvParams[1u].asInt ();
             std::int64_t   uLedgerMax  = jvParams[2u].asInt ();
             if (uLedgerMax != -1 && uLedgerMax < uLedgerMin)
             {
                 return rpcError (rpcLGR_IDXS_INVALID);
             }
             jvRequest["ledger_index_min"]   = jvParams[1u].asInt ();
             jvRequest["ledger_index_max"]   = jvParams[2u].asInt ();
             if (iParams >= 4)
                 jvRequest["limit"]  = jvParams[3u].asInt ();
             if (iParams >= 5)
                 jvRequest["offset"] = jvParams[4u].asInt ();
         }
         return jvRequest;
     }
Json::Value ripple::RPCParser::parseAsIs (const Json::Value & jvParams) inline private
Definition at line 93 of file RPCCall.cpp.
References Json::Value::isArray(), Json::objectValue, and Json::Value::size().
Referenced by parseCommand().
     {
         Json::Value v (Json::objectValue);
         if (jvParams.isArray () && (jvParams.size () > 0))
             v["params"] = jvParams;
         return v;
     }
Json::Value ripple::RPCParser::parseBookOffers (const Json::Value & jvParams) inline private
Definition at line 270 of file RPCCall.cpp.
References Json::Value::asInt(), Json::Value::asString(), ripple::isRpcError(), jvParseCurrencyIssuer(), jvParseLedger(), Json::objectValue, and Json::Value::size().
Referenced by parseCommand().
     {
         Json::Value     jvRequest (Json::objectValue);
         Json::Value     jvTakerPays = jvParseCurrencyIssuer (jvParams[0u].asString ());
         Json::Value     jvTakerGets = jvParseCurrencyIssuer (jvParams[1u].asString ());
         if (isRpcError (jvTakerPays))
         {
             return jvTakerPays;
         }
         else
         {
             jvRequest["taker_pays"] = jvTakerPays;
         }
         if (isRpcError (jvTakerGets))
         {
             return jvTakerGets;
         }
         else
         {
             jvRequest["taker_gets"] = jvTakerGets;
         }
         if (jvParams.size () >= 3)
         {
             jvRequest["issuer"] = jvParams[2u].asString ();
         }
         if (jvParams.size () >= 4 && !jvParseLedger (jvRequest, jvParams[3u].asString ()))
             return jvRequest;
         if (jvParams.size () >= 5)
         {
             int     iLimit  = jvParams[5u].asInt ();
             if (iLimit > 0)
                 jvRequest["limit"]  = iLimit;
         }
         if (jvParams.size () >= 6 && jvParams[5u].asInt ())
         {
             jvRequest["proof"]  = true;
         }
         if (jvParams.size () == 7)
             jvRequest["marker"] = jvParams[6u];
         return jvRequest;
     }
Json::Value ripple::RPCParser::parseCommand (std::string strMethod, Json::Value jvParams, bool allowAnyCommand) inline
Definition at line 782 of file RPCCall.cpp.
References ripple::lsTRACE, ripple::lsWARNING, NUMBER, parseAccountCurrencies(), parseAccountItems(), parseAccountLines(), parseAccountTransactions(), parseAsIs(), parseBookOffers(), parseConnect(), parseEvented(), parseFeature(), parseFetchInfo(), parseGetCounts(), parseInternal(), parseJson(), parseLedger(), parseLedgerId(), parseLogLevel(), parseProofCreate(), parseProofSolve(), parseProofVerify(), parseRipplePathFind(), parseSignSubmit(), parseSMS(), parseTx(), parseTxAccount(), parseTxHistory(), parseUnlAdd(), parseUnlDelete(), parseValidationCreate(), parseValidationSeed(), parseWalletAccounts(), parseWalletPropose(), parseWalletSeed(), ripple::rpcBAD_SYNTAX, ripple::rpcError(), ripple::rpcUNKNOWN_COMMAND, Json::Value::size(), and WriteLog.
Referenced by ripple::RPCCall::fromCommandLine().
     {
         WriteLog (lsTRACE, RPCParser) << "RPC method:" << strMethod;
         WriteLog (lsTRACE, RPCParser) << "RPC params:" << jvParams;
         struct Command
         {
             const char*     pCommand;
             parseFuncPtr    pfpFunc;
             int             iMinParams;
             int             iMaxParams;
         };
         static Command commandsA[] =
         {
             // Request-response methods
             // - Returns an error, or the request.
             // - To modify the method, provide a new method in the request.
             {   "account_currencies",   &RPCParser::parseAccountCurrencies,     1,  2   },
             {   "account_info",         &RPCParser::parseAccountItems,          1,  2   },
             {   "account_lines",        &RPCParser::parseAccountLines,          1,  3   },
             {   "account_offers",       &RPCParser::parseAccountItems,          1,  2   },
             {   "account_tx",           &RPCParser::parseAccountTransactions,   1,  8   },
             {   "book_offers",          &RPCParser::parseBookOffers,            2,  7   },
             {   "connect",              &RPCParser::parseConnect,               1,  2   },
             {   "consensus_info",       &RPCParser::parseAsIs,                  0,  0   },
             {   "feature",              &RPCParser::parseFeature,               0,  2   },
             {   "fetch_info",           &RPCParser::parseFetchInfo,             0,  1   },
             {   "get_counts",           &RPCParser::parseGetCounts,             0,  1   },
             {   "json",                 &RPCParser::parseJson,                  2,  2   },
             {   "ledger",               &RPCParser::parseLedger,                0,  2   },
             {   "ledger_accept",        &RPCParser::parseAsIs,                  0,  0   },
             {   "ledger_closed",        &RPCParser::parseAsIs,                  0,  0   },
             {   "ledger_current",       &RPCParser::parseAsIs,                  0,  0   },
     //      {   "ledger_entry",         &RPCParser::parseLedgerEntry,          -1, -1   },
             {   "ledger_header",        &RPCParser::parseLedgerId,              1,  1   },
             {   "log_level",            &RPCParser::parseLogLevel,              0,  2   },
             {   "logrotate",            &RPCParser::parseAsIs,                  0,  0   },
     //      {   "nickname_info",        &RPCParser::parseNicknameInfo,          1,  1   },
             {   "owner_info",           &RPCParser::parseAccountItems,          1,  2   },
             {   "peers",                &RPCParser::parseAsIs,                  0,  0   },
             {   "ping",                 &RPCParser::parseAsIs,                  0,  0   },
             {   "print",                &RPCParser::parseAsIs,                  0,  1   },
     //      {   "profile",              &RPCParser::parseProfile,               1,  9   },
             {   "proof_create",         &RPCParser::parseProofCreate,           0,  2   },
             {   "proof_solve",          &RPCParser::parseProofSolve,            1,  1   },
             {   "proof_verify",         &RPCParser::parseProofVerify,           2,  4   },
             {   "random",               &RPCParser::parseAsIs,                  0,  0   },
             {   "ripple_path_find",     &RPCParser::parseRipplePathFind,        1,  2   },
             {   "sign",                 &RPCParser::parseSignSubmit,            2,  3   },
             {   "sms",                  &RPCParser::parseSMS,                   1,  1   },
             {   "submit",               &RPCParser::parseSignSubmit,            1,  3   },
             {   "server_info",          &RPCParser::parseAsIs,                  0,  0   },
             {   "server_state",         &RPCParser::parseAsIs,                  0,  0   },
             {   "stop",                 &RPCParser::parseAsIs,                  0,  0   },
     //      {   "transaction_entry",    &RPCParser::parseTransactionEntry,     -1,  -1  },
             {   "tx",                   &RPCParser::parseTx,                    1,  2   },
             {   "tx_account",           &RPCParser::parseTxAccount,             1,  7   },
             {   "tx_history",           &RPCParser::parseTxHistory,             1,  1   },
             {   "unl_add",              &RPCParser::parseUnlAdd,                1,  2   },
             {   "unl_delete",           &RPCParser::parseUnlDelete,             1,  1   },
             {   "unl_list",             &RPCParser::parseAsIs,                  0,  0   },
             {   "unl_load",             &RPCParser::parseAsIs,                  0,  0   },
             {   "unl_network",          &RPCParser::parseAsIs,                  0,  0   },
             {   "unl_reset",            &RPCParser::parseAsIs,                  0,  0   },
             {   "unl_score",            &RPCParser::parseAsIs,                  0,  0   },
             {   "validation_create",    &RPCParser::parseValidationCreate,      0,  1   },
             {   "validation_seed",      &RPCParser::parseValidationSeed,        0,  1   },
             {   "wallet_accounts",      &RPCParser::parseWalletAccounts,        1,  1   },
             {   "wallet_propose",       &RPCParser::parseWalletPropose,         0,  1   },
             {   "wallet_seed",          &RPCParser::parseWalletSeed,            0,  1   },
             {   "internal",             &RPCParser::parseInternal,              1,  -1  },
             // Evented methods
             {   "path_find",            &RPCParser::parseEvented,               -1, -1  },
             {   "subscribe",            &RPCParser::parseEvented,               -1, -1  },
             {   "unsubscribe",          &RPCParser::parseEvented,               -1, -1  },
         };
         int     i = NUMBER (commandsA);
         while (i-- && strMethod != commandsA[i].pCommand)
             ;
         if (i < 0)
         {
             if (!allowAnyCommand)
                 return rpcError (rpcUNKNOWN_COMMAND);
             return parseAsIs (jvParams);
         }
         else if ((commandsA[i].iMinParams >= 0 && jvParams.size () < commandsA[i].iMinParams)
                  || (commandsA[i].iMaxParams >= 0 && jvParams.size () > commandsA[i].iMaxParams))
         {
             WriteLog (lsWARNING, RPCParser) << "Wrong number of parameters: minimum=" << commandsA[i].iMinParams
                                             << " maximum=" << commandsA[i].iMaxParams
                                             << " actual=" << jvParams.size ();
             return rpcError (rpcBAD_SYNTAX);
         }
         return (this->* (commandsA[i].pfpFunc)) (jvParams);
     }
Json::Value ripple::RPCParser::parseConnect (const Json::Value & jvParams) inline private
Definition at line 323 of file RPCCall.cpp.
References Json::Value::asString(), Json::objectValue, and Json::Value::size().
Referenced by parseCommand().
     {
         Json::Value     jvRequest (Json::objectValue);
         jvRequest["ip"] = jvParams[0u].asString ();
         if (jvParams.size () == 2)
             jvRequest["port"]   = jvParams[1u].asUInt ();
         return jvRequest;
     }
Json::Value ripple::RPCParser::parseEvented (const Json::Value & jvParams) inline private
Definition at line 336 of file RPCCall.cpp.
References ripple::rpcError(), and ripple::rpcNO_EVENTS.
Referenced by parseCommand().
     {
         return rpcError (rpcNO_EVENTS);
     }
Json::Value ripple::RPCParser::parseFeature (const Json::Value & jvParams) inline private
Definition at line 342 of file RPCCall.cpp.
References Json::objectValue, and Json::Value::size().
Referenced by parseCommand().
     {
         Json::Value     jvRequest (Json::objectValue);
         if (jvParams.size () > 0)
             jvRequest["feature"]    = jvParams[0u].asString ();
         if (jvParams.size () > 1)
             jvRequest["vote"]       = beast::lexicalCastThrow <bool> (jvParams[1u].asString ());
         return jvRequest;
     }
Json::Value ripple::RPCParser::parseFetchInfo (const Json::Value & jvParams) inline private
Definition at line 119 of file RPCCall.cpp.
References Json::Value::asString(), Json::objectValue, and Json::Value::size().
Referenced by parseCommand().
     {
         Json::Value     jvRequest (Json::objectValue);
         unsigned int    iParams = jvParams.size ();
         if (iParams != 0)
             jvRequest[jvParams[0u].asString()] = true;
         return jvRequest;
     }
Json::Value ripple::RPCParser::parseGetCounts (const Json::Value & jvParams) inline private
Definition at line 356 of file RPCCall.cpp.
References Json::objectValue, and Json::Value::size().
Referenced by parseCommand().
     {
         Json::Value     jvRequest (Json::objectValue);
         if (jvParams.size ())
             jvRequest["min_count"]  = jvParams[0u].asUInt ();
         return jvRequest;
     }
Json::Value ripple::RPCParser::parseInternal (const Json::Value & jvParams) inline private
Definition at line 103 of file RPCCall.cpp.
References Json::Value::append(), Json::arrayValue, Json::objectValue, and Json::Value::size().
Referenced by parseCommand().
     {
         Json::Value v (Json::objectValue);
         v["internal_command"] = jvParams[0u];
         Json::Value params (Json::arrayValue);
         for (unsigned i = 1; i < jvParams.size (); ++i)
             params.append (jvParams[i]);
         v["params"] = params;
         return v;
     }
Json::Value ripple::RPCParser::parseJson (const Json::Value & jvParams) inline private
Definition at line 367 of file RPCCall.cpp.
References Json::Value::asString(), Json::Value::isObject(), ripple::lsTRACE, Json::Reader::parse(), ripple::rpcError(), ripple::rpcINVALID_PARAMS, and WriteLog.
Referenced by parseCommand().
     {
         Json::Reader    reader;
         Json::Value     jvRequest;
         WriteLog (lsTRACE, RPCParser) << "RPC method: " << jvParams[0u];
         WriteLog (lsTRACE, RPCParser) << "RPC json: " << jvParams[1u];
         if (reader.parse (jvParams[1u].asString (), jvRequest))
         {
             if (!jvRequest.isObject ())
                 return rpcError (rpcINVALID_PARAMS);
             jvRequest["method"] = jvParams[0u];
             return jvRequest;
         }
         return rpcError (rpcINVALID_PARAMS);
     }
Json::Value ripple::RPCParser::parseLedger (const Json::Value & jvParams) inline private
Definition at line 389 of file RPCCall.cpp.
References Json::Value::asString(), jvParseLedger(), Json::objectValue, and Json::Value::size().
Referenced by parseCommand().
     {
         Json::Value     jvRequest (Json::objectValue);
         if (!jvParams.size ())
         {
             return jvRequest;
         }
         jvParseLedger (jvRequest, jvParams[0u].asString ());
         if (2 == jvParams.size () && jvParams[1u].asString () == "full")
         {
             jvRequest["full"]   = bool (1);
         }
         return jvRequest;
     }
Json::Value ripple::RPCParser::parseLedgerId (const Json::Value & jvParams) inline private
Definition at line 409 of file RPCCall.cpp.
References Json::Value::asString(), and Json::objectValue.
Referenced by parseCommand().
     {
         Json::Value     jvRequest (Json::objectValue);
         std::string     strLedger   = jvParams[0u].asString ();
         if (strLedger.length () == 32)
         {
             jvRequest["ledger_hash"]    = strLedger;
         }
         else
         {
             jvRequest["ledger_index"]   = beast::lexicalCast <std::uint32_t> (strLedger);
         }
         return jvRequest;
     }
Json::Value ripple::RPCParser::parseLogLevel (const Json::Value & jvParams) inline private
Definition at line 430 of file RPCCall.cpp.
References Json::Value::asString(), Json::objectValue, and Json::Value::size().
Referenced by parseCommand().
     {
         Json::Value     jvRequest (Json::objectValue);
         if (jvParams.size () == 1)
         {
             jvRequest["severity"] = jvParams[0u].asString ();
         }
         else if (jvParams.size () == 2)
         {
             jvRequest["partition"] = jvParams[0u].asString ();
             jvRequest["severity"] = jvParams[1u].asString ();
         }
         return jvRequest;
     }
Json::Value ripple::RPCParser::parseProofCreate (const Json::Value & jvParams) inline private
Definition at line 521 of file RPCCall.cpp.
References Json::Value::size().
Referenced by parseCommand().
     {
         Json::Value     jvRequest;
         if (jvParams.size () >= 1)
             jvRequest["difficulty"] = jvParams[0u].asInt ();
         if (jvParams.size () >= 2)
             jvRequest["secret"] = jvParams[1u].asString ();
         return jvRequest;
     }
Json::Value ripple::RPCParser::parseProofSolve (const Json::Value & jvParams) inline private
Definition at line 535 of file RPCCall.cpp.
References Json::Value::asString().
Referenced by parseCommand().
     {
         Json::Value     jvRequest;
         jvRequest["token"] = jvParams[0u].asString ();
         return jvRequest;
     }
Json::Value ripple::RPCParser::parseProofVerify (const Json::Value & jvParams) inline private
Definition at line 545 of file RPCCall.cpp.
References Json::Value::asString(), and Json::Value::size().
Referenced by parseCommand().
     {
         Json::Value     jvRequest;
         jvRequest["token"] = jvParams[0u].asString ();
         jvRequest["solution"] = jvParams[1u].asString ();
         if (jvParams.size () >= 3)
             jvRequest["difficulty"] = jvParams[2u].asInt ();
         if (jvParams.size () >= 4)
             jvRequest["secret"] = jvParams[3u].asString ();
         return jvRequest;
     }
Json::Value ripple::RPCParser::parseRipplePathFind (const Json::Value & jvParams) inline private
Definition at line 562 of file RPCCall.cpp.
References Json::Value::asString(), jvParseLedger(), ripple::lsTRACE, Json::Reader::parse(), ripple::rpcError(), ripple::rpcINVALID_PARAMS, Json::Value::size(), and WriteLog.
Referenced by parseCommand().
     {
         Json::Reader    reader;
         Json::Value     jvRequest;
         bool            bLedger     = 2 == jvParams.size ();
         WriteLog (lsTRACE, RPCParser) << "RPC json: " << jvParams[0u];
         if (reader.parse (jvParams[0u].asString (), jvRequest))
         {
             if (bLedger)
             {
                 jvParseLedger (jvRequest, jvParams[1u].asString ());
             }
             return jvRequest;
         }
         return rpcError (rpcINVALID_PARAMS);
     }
Json::Value ripple::RPCParser::parseSignSubmit (const Json::Value & jvParams) inline private
Definition at line 588 of file RPCCall.cpp.
References Json::Value::asString(), Json::Reader::parse(), ripple::rpcError(), ripple::rpcINVALID_PARAMS, and Json::Value::size().
Referenced by parseCommand().
     {
         Json::Value     txJSON;
         Json::Reader    reader;
         bool            bOffline    = 3 == jvParams.size () && jvParams[2u].asString () == "offline";
         if (1 == jvParams.size ())
         {
             // Submitting tx_blob
             Json::Value jvRequest;
             jvRequest["tx_blob"]    = jvParams[0u].asString ();
             return jvRequest;
         }
         else if ((2 == jvParams.size () || bOffline)
                  && reader.parse (jvParams[1u].asString (), txJSON))
         {
             // Signing or submitting tx_json.
             Json::Value jvRequest;
             jvRequest["secret"]     = jvParams[0u].asString ();
             jvRequest["tx_json"]    = txJSON;
             if (bOffline)
                 jvRequest["offline"]    = true;
             return jvRequest;
         }
         return rpcError (rpcINVALID_PARAMS);
     }
Json::Value ripple::RPCParser::parseSMS (const Json::Value & jvParams) inline private
Definition at line 623 of file RPCCall.cpp.
References Json::Value::asString().
Referenced by parseCommand().
     {
         Json::Value     jvRequest;
         jvRequest["text"]   = jvParams[0u].asString ();
         return jvRequest;
     }
Json::Value ripple::RPCParser::parseTx (const Json::Value & jvParams) inline private
Definition at line 633 of file RPCCall.cpp.
References Json::Value::asString(), and Json::Value::size().
Referenced by parseCommand().
     {
         Json::Value jvRequest;
         if (jvParams.size () > 1)
         {
             if (jvParams[1u].asString () == "binary")
                 jvRequest["binary"] = true;
         }
         jvRequest["transaction"]    = jvParams[0u].asString ();
         return jvRequest;
     }
Json::Value ripple::RPCParser::parseTxAccount (const Json::Value & jvParams) inline private
Definition at line 200 of file RPCCall.cpp.
References Json::Value::asInt(), Json::Value::asString(), ripple::RippleAddress::humanAccountID(), jvParseLedger(), nothing, Json::objectValue, ripple::rpcACT_MALFORMED, ripple::rpcError(), ripple::rpcLGR_IDXS_INVALID, ripple::RippleAddress::setAccountID(), and Json::Value::size().
Referenced by parseCommand().
     {
         Json::Value     jvRequest (Json::objectValue);
         RippleAddress   raAccount;
         unsigned int    iParams = jvParams.size ();
         if (!raAccount.setAccountID (jvParams[0u].asString ()))
             return rpcError (rpcACT_MALFORMED);
         jvRequest["account"]    = raAccount.humanAccountID ();
         bool            bDone   = false;
         while (!bDone && iParams >= 2)
         {
             if (jvParams[iParams - 1].asString () == "binary")
             {
                 jvRequest["binary"]     = true;
                 --iParams;
             }
             else if (jvParams[iParams - 1].asString () == "count")
             {
                 jvRequest["count"]      = true;
                 --iParams;
             }
             else if (jvParams[iParams - 1].asString () == "forward")
             {
                 jvRequest["forward"] = true;
                 --iParams;
             }
             else
             {
                 bDone   = true;
             }
         }
         if (1 == iParams)
         {
             nothing ();
         }
         else if (2 == iParams)
         {
             if (!jvParseLedger (jvRequest, jvParams[1u].asString ()))
                 return jvRequest;
         }
         else
         {
             std::int64_t   uLedgerMin  = jvParams[1u].asInt ();
             std::int64_t   uLedgerMax  = jvParams[2u].asInt ();
             if (uLedgerMax != -1 && uLedgerMax < uLedgerMin)
             {
                 return rpcError (rpcLGR_IDXS_INVALID);
             }
             jvRequest["ledger_index_min"]   = jvParams[1u].asInt ();
             jvRequest["ledger_index_max"]   = jvParams[2u].asInt ();
             if (iParams >= 4)
                 jvRequest["limit"]  = jvParams[3u].asInt ();
         }
         return jvRequest;
     }
Json::Value ripple::RPCParser::parseTxHistory (const Json::Value & jvParams) inline private
Definition at line 648 of file RPCCall.cpp.
References Json::Value::asUInt().
Referenced by parseCommand().
     {
         Json::Value jvRequest;
         jvRequest["start"]  = jvParams[0u].asUInt ();
         return jvRequest;
     }
Json::Value ripple::RPCParser::parseUnlAdd (const Json::Value & jvParams) inline private
Definition at line 658 of file RPCCall.cpp.
References Json::Value::asString(), ripple::rpcError(), ripple::rpcINVALID_PARAMS, and Json::Value::size().
Referenced by parseCommand().
     {
         std::string strNode     = jvParams[0u].asString ();
         std::string strComment  = (jvParams.size () == 2) ? jvParams[1u].asString () : "";
         RippleAddress   naNodePublic;
         if (strNode.length ())
         {
             Json::Value jvRequest;
             jvRequest["node"]       = strNode;
             if (strComment.length ())
                 jvRequest["comment"]    = strComment;
             return jvRequest;
         }
         return rpcError (rpcINVALID_PARAMS);
     }
Json::Value ripple::RPCParser::parseUnlDelete (const Json::Value & jvParams) inline private
Definition at line 681 of file RPCCall.cpp.
References Json::Value::asString().
Referenced by parseCommand().
     {
         Json::Value jvRequest;
         jvRequest["node"]       = jvParams[0u].asString ();
         return jvRequest;
     }
Json::Value ripple::RPCParser::parseValidationCreate (const Json::Value & jvParams) inline private
Definition at line 694 of file RPCCall.cpp.
References Json::Value::size().
Referenced by parseCommand().
     {
         Json::Value jvRequest;
         if (jvParams.size ())
             jvRequest["secret"]     = jvParams[0u].asString ();
         return jvRequest;
     }
Json::Value ripple::RPCParser::parseValidationSeed (const Json::Value & jvParams) inline private
Definition at line 708 of file RPCCall.cpp.
References Json::Value::size().
Referenced by parseCommand().
     {
         Json::Value jvRequest;
         if (jvParams.size ())
             jvRequest["secret"]     = jvParams[0u].asString ();
         return jvRequest;
     }
Json::Value ripple::RPCParser::parseWalletAccounts (const Json::Value & jvParams) inline private
Definition at line 719 of file RPCCall.cpp.
References Json::Value::asString().
Referenced by parseCommand().
     {
         Json::Value jvRequest;
         jvRequest["seed"]       = jvParams[0u].asString ();
         return jvRequest;
     }
Json::Value ripple::RPCParser::parseWalletPropose (const Json::Value & jvParams) inline private
Definition at line 730 of file RPCCall.cpp.
References Json::Value::size().
Referenced by parseCommand().
     {
         Json::Value jvRequest;
         if (jvParams.size ())
             jvRequest["passphrase"]     = jvParams[0u].asString ();
         return jvRequest;
     }
Json::Value ripple::RPCParser::parseWalletSeed (const Json::Value & jvParams) inline private
Definition at line 741 of file RPCCall.cpp.
References Json::Value::size().
Referenced by parseCommand().
     {
         Json::Value jvRequest;
         if (jvParams.size ())
             jvRequest["secret"]     = jvParams[0u].asString ();
         return jvRequest;
     }
The documentation for this class was generated from the following file:
rippled/src/ripple_net/rpc/RPCCall.cpp