rippled: beast::HTTPResponse Class Reference
beast::HTTPResponse Class Reference
#include <HTTPResponse.h>
Public Member Functions
HTTPResponse (HTTPVersion const &version_, StringPairArray &fields, DynamicBuffer &body, unsigned short status_)
unsigned short status () const
String toString () const
Public Member Functions inherited from beast::HTTPMessage
HTTPMessage (HTTPVersion const &version_, StringPairArray &fields, DynamicBuffer &body)
HTTPVersion const & version () const
HTTPHeaders const & headers () const
DynamicBuffer const & body () const
String toString () const
Public Member Functions inherited from beast::SharedObject
void incReferenceCount () const noexcept
void decReferenceCount () const
int getReferenceCount () const noexcept
Private Attributes
unsigned short m_status
Additional Inherited Members
Protected Member Functions inherited from beast::SharedObject
SharedObject ()
virtual ~SharedObject ()
virtual void destroy () const
void resetReferenceCount () noexcept
Detailed Description
Definition at line 25 of file HTTPResponse.h.
Constructor & Destructor Documentation
beast::HTTPResponse::HTTPResponse (HTTPVersion const & version_, StringPairArray & fields, DynamicBuffer & body, unsigned short status_)
Construct a complete response from values. Ownership of the fields and body parameters are transferred from the caller.
Definition at line 22 of file HTTPResponse.cpp.
     : HTTPMessage (version_, fields, body)
     , m_status (status_)
 {
 }
Member Function Documentation
unsigned short beast::HTTPResponse::status () const
Definition at line 32 of file HTTPResponse.cpp.
References m_status.
Referenced by toString().
 {
     return m_status;
 }
String beast::HTTPResponse::toString () const
Convert the response into a string, excluding the body.
Definition at line 37 of file HTTPResponse.cpp.
References beast::String::fromNumber(), beast::newLine, status(), and beast::HTTPMessage::toString().
 {
     String s;
     s << "Status: " << String::fromNumber (status ()) << newLine;
     s << this->HTTPMessage::toString ();
     return s;
 }
Member Data Documentation
unsigned short beast::HTTPResponse::m_status private
Definition at line 44 of file HTTPResponse.h.
Referenced by status().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_asio/http/HTTPResponse.h
rippled/src/beast/modules/beast_asio/http/HTTPResponse.cpp