rippled: beast::SystemStats Class Reference
beast::SystemStats Class Reference
#include <SystemStats.h>
Public Types
enum OperatingSystemType {
UnknownOS = 0, MacOSX_10_4 = 0x1004, MacOSX_10_5 = 0x1005, MacOSX_10_6 = 0x1006,
MacOSX_10_7 = 0x1007, MacOSX_10_8 = 0x1008, Linux = 0x2000, FreeBSD = 0x2001,
Android = 0x3000, Win2000 = 0x4105, WinXP = 0x4106, WinVista = 0x4107,
Windows7 = 0x4108, Windows8 = 0x4109, Windows = 0x4000, iOS = 0x8000
}
typedef void(* CrashHandlerFunction)()
Static Public Member Functions
static String getBeastVersion ()
static OperatingSystemType getOperatingSystemType ()
static String getOperatingSystemName ()
static bool isOperatingSystem64Bit ()
static String getEnvironmentVariable (const String &name, const String &defaultValue)
static String getLogonName ()
static String getFullUserName ()
static String getComputerName ()
static String getUserLanguage ()
static String getUserRegion ()
static String getDisplayLanguage ()
static int getNumCpus () noexcept
static int getCpuSpeedInMegaherz ()
static String getCpuVendor ()
static bool hasMMX () noexcept
static bool hasSSE () noexcept
static bool hasSSE2 () noexcept
static bool hasSSE3 () noexcept
static bool has3DNow () noexcept
static int getMemorySizeInMegabytes ()
static int getPageSize ()
static String getStackBacktrace ()
static void setApplicationCrashHandler (CrashHandlerFunction)
Private Member Functions
SystemStats ()
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
Contains methods for finding out about the current hardware and OS configuration.
Definition at line 34 of file SystemStats.h.
Member Typedef Documentation
typedef void(* beast::SystemStats::CrashHandlerFunction)()
A void() function type, used by setApplicationCrashHandler().
Definition at line 167 of file SystemStats.h.
Member Enumeration Documentation
enum beast::SystemStats::OperatingSystemType
The set of possible results of the getOperatingSystemType() method.
Enumerator
UnknownOS
MacOSX_10_4
MacOSX_10_5
MacOSX_10_6
MacOSX_10_7
MacOSX_10_8
Linux
FreeBSD
Android
Win2000
WinXP
WinVista
Windows7
Windows8
Windows
To test whether any version of Windows is running, you can use the expression ((getOperatingSystemType() & Windows) != 0).
iOS
Definition at line 45 of file SystemStats.h.
     {
         UnknownOS   = 0,
         MacOSX_10_4 = 0x1004,
         MacOSX_10_5 = 0x1005,
         MacOSX_10_6 = 0x1006,
         MacOSX_10_7 = 0x1007,
         MacOSX_10_8 = 0x1008,
         Linux       = 0x2000,
         FreeBSD     = 0x2001,
         Android     = 0x3000,
         Win2000     = 0x4105,
         WinXP       = 0x4106,
         WinVista    = 0x4107,
         Windows7    = 0x4108,
         Windows8    = 0x4109,
         Windows     = 0x4000,
         iOS         = 0x8000
     };
Constructor & Destructor Documentation
beast::SystemStats::SystemStats () private
Member Function Documentation
String beast::SystemStats::getBeastVersion () static
Returns the current version of BEAST, See also the BEAST_VERSION, BEAST_MAJOR_VERSION and BEAST_MINOR_VERSION macros.
Definition at line 27 of file SystemStats.cpp.
References BEAST_BUILDNUMBER, BEAST_MAJOR_VERSION, BEAST_MINOR_VERSION, BEAST_STRINGIFY, and static_bassert.
 {
     // Some basic tests, to keep an eye on things and make sure these types work ok
     // on all platforms. Let me know if any of these assertions fail on your system!
     static_bassert (sizeof (std::intptr_t) == sizeof (void*));
     static_bassert (sizeof (std::int8_t) == 1);
     static_bassert (sizeof (std::uint8_t) == 1);
     static_bassert (sizeof (std::int16_t) == 2);
     static_bassert (sizeof (std::uint16_t) == 2);
     static_bassert (sizeof (std::int32_t) == 4);
     static_bassert (sizeof (std::uint32_t) == 4);
     static_bassert (sizeof (std::int64_t) == 8);
     static_bassert (sizeof (std::uint64_t) == 8);
     return "Beast v" BEAST_STRINGIFY(BEAST_MAJOR_VERSION)
                 "." BEAST_STRINGIFY(BEAST_MINOR_VERSION)
                 "." BEAST_STRINGIFY(BEAST_BUILDNUMBER);
 }
String beast::SystemStats::getComputerName () static
Returns the host-name of the computer.
Definition at line 273 of file bsd_SystemStats.cpp.
References beast::String::empty, and name.
Referenced by ripple::NetworkOPsImp::getServerInfo().
 {
     char name [256] = { 0 };
     if (gethostname (name, sizeof (name) - 1) == 0)
         return name;
     return String::empty;
 }
int beast::SystemStats::getCpuSpeedInMegaherz () static
Returns the approximate CPU speed.
Returns
the speed in megahertz, e.g. 1500, 2500, 32000 (depending on what year you're reading this...)
Definition at line 233 of file bsd_SystemStats.cpp.
References beast::BSDStatsHelpers::getDmesgInfo(), and beast::roundToInt().
 {
     return roundToInt (BSDStatsHelpers::getDmesgInfo ("CPU:").fromLastOccurrenceOf ("(", false, false).upToFirstOccurrenceOf ("-MHz", false, false).getFloatValue());
 }
String beast::SystemStats::getCpuVendor () static
Returns a string to indicate the CPU vendor. Might not be known on some systems.
Definition at line 228 of file bsd_SystemStats.cpp.
References beast::BSDStatsHelpers::getDmesgInfo(), beast::String::unquoted(), and beast::String::upToFirstOccurrenceOf().
 {
     return BSDStatsHelpers::getDmesgInfo ("  Origin =").upToFirstOccurrenceOf (" ", false, false).unquoted();
 }
String beast::SystemStats::getDisplayLanguage () static
Returns the user's display language. The return value is a 2 or 3 letter language code (ISO 639-1 or ISO 639-2)
Definition at line 299 of file bsd_SystemStats.cpp.
References getUserLanguage().
 {
     return getUserLanguage();
 }
String beast::SystemStats::getEnvironmentVariable (const String & name, const String & defaultValue) static
Returns an environment variable. If the named value isn't set, this will return the defaultValue string instead.
Definition at line 593 of file posix_SharedCode.h.
References beast::String::fromUTF8(), and beast::String::toUTF8().
 {
     if (const char* s = ::getenv (name.toUTF8()))
         return String::fromUTF8 (s);
     return defaultValue;
 }
String beast::SystemStats::getFullUserName () static
Returns the current user's full name, if available. On some OSes, this may just return the same value as getLogonName().
See Also
getLogonName()
Definition at line 268 of file bsd_SystemStats.cpp.
References getLogonName().
 {
     return getLogonName();
 }
String beast::SystemStats::getLogonName () static
Returns the current user's name, if available.
See Also
getFullUserName()
Definition at line 254 of file bsd_SystemStats.cpp.
Referenced by getFullUserName().
 {
     const char* user = getenv ("USER");
     if (user == nullptr)
     {
         struct passwd* const pw = getpwuid (getuid());
         if (pw != nullptr)
             user = pw->pw_name;
     }
     return CharPointer_UTF8 (user);
 }
int beast::SystemStats::getMemorySizeInMegabytes () static
Finds out how much RAM is in the machine.
Returns
the approximate number of megabytes of memory, or zero if something goes wrong when finding out.
Definition at line 238 of file bsd_SystemStats.cpp.
References beast::sysinfo::mem_unit, and beast::sysinfo::totalram.
 {
     struct sysinfo sysi;
     if (sysinfo (&sysi) == 0)
         return (sysi.totalram * sysi.mem_unit / (1024 * 1024));
     return 0;
 }
int beast::SystemStats::getNumCpus () static noexcept
Returns the number of CPU cores.
Definition at line 68 of file SystemStats.cpp.
References beast::getCPUInformation(), and beast::CPUInformation::numCpus.
Referenced by ripple::JobQueueImp::setThreadCount().
 { return getCPUInformation().numCpus; }
String beast::SystemStats::getOperatingSystemName () static
Returns the name of the type of operating system we're running on.
Returns
a string describing the OS type.
See Also
getOperatingSystemType
Definition at line 195 of file bsd_SystemStats.cpp.
Referenced by beast::Debug_test::run().
 {
     return "FreeBSD";
 }
SystemStats::OperatingSystemType beast::SystemStats::getOperatingSystemType () static
Returns the type of operating system we're running on.
Returns
one of the values from the OperatingSystemType enum.
See Also
getOperatingSystemName
Definition at line 190 of file bsd_SystemStats.cpp.
References FreeBSD.
 {
     return FreeBSD;
 }
int beast::SystemStats::getPageSize () static
Returns the system page-size. This is only used by programmers with beards.
Definition at line 248 of file bsd_SystemStats.cpp.
 {
     return sysconf (_SC_PAGESIZE);
 }
String beast::SystemStats::getStackBacktrace () static
Returns a backtrace of the current call-stack. The usefulness of the result will depend on the level of debug symbols that are available in the executable.
Definition at line 76 of file SystemStats.cpp.
References bassertfalse, beast::HeapBlock< ElementType, throwOnFailure >::calloc(), beast::newLine, beast::numElementsInArray(), std::chrono::symbol, beast::String::toHexString(), TRUE, and beast::zerostruct().
Referenced by beast::FatalError::FatalError().
 {
     String result;
    #if BEAST_ANDROID || BEAST_MINGW || BEAST_BSD
     bassertfalse; // sorry, not implemented yet!
    #elif BEAST_WINDOWS
     HANDLE process = GetCurrentProcess();
     SymInitialize (process, nullptr, TRUE);
     void* stack[128];
     int frames = (int) CaptureStackBackTrace (0, numElementsInArray (stack), stack, nullptr);
     HeapBlock<SYMBOL_INFO> symbol;
     symbol.calloc (sizeof (SYMBOL_INFO) + 256, 1);
     symbol->MaxNameLen = 255;
     symbol->SizeOfStruct = sizeof (SYMBOL_INFO);
     for (int i = 0; i < frames; ++i)
     {
         DWORD64 displacement = 0;
         if (SymFromAddr (process, (DWORD64) stack[i], &displacement, symbol))
         {
             result << i << ": ";
             IMAGEHLP_MODULE64 moduleInfo;
             zerostruct (moduleInfo);
             moduleInfo.SizeOfStruct = sizeof (moduleInfo);
             if (::SymGetModuleInfo64 (process, symbol->ModBase, &moduleInfo))
                 result << moduleInfo.ModuleName << ": ";
             result << symbol->Name << " + 0x" << String::toHexString ((std::int64_t) displacement) << newLine;
         }
     }
    #else
     void* stack[128];
     int frames = backtrace (stack, numElementsInArray (stack));
     char** frameStrings = backtrace_symbols (stack, frames);
     for (int i = 0; i < frames; ++i)
         result << frameStrings[i] << newLine;
     ::free (frameStrings);
    #endif
     return result;
 }
String beast::SystemStats::getUserLanguage () static
Returns the language of the user's locale. The return value is a 2 or 3 letter language code (ISO 639-1 or ISO 639-2)
Definition at line 289 of file bsd_SystemStats.cpp.
Referenced by getDisplayLanguage().
 {
     return "Uknown user language";
 }
String beast::SystemStats::getUserRegion () static
Returns the region of the user's locale. The return value is a 2 letter country code (ISO 3166-1 alpha-2).
Definition at line 294 of file bsd_SystemStats.cpp.
 {
     return "Unknown user region";
 }
bool beast::SystemStats::has3DNow () static noexcept
Returns true if AMD 3DNOW instructions are available.
Definition at line 73 of file SystemStats.cpp.
References beast::getCPUInformation(), and beast::CPUInformation::has3DNow.
 { return getCPUInformation().has3DNow; }
bool beast::SystemStats::hasMMX () static noexcept
Returns true if Intel MMX instructions are available.
Definition at line 69 of file SystemStats.cpp.
References beast::getCPUInformation(), and beast::CPUInformation::hasMMX.
 { return getCPUInformation().hasMMX; }
bool beast::SystemStats::hasSSE () static noexcept
Returns true if Intel SSE instructions are available.
Definition at line 70 of file SystemStats.cpp.
References beast::getCPUInformation(), and beast::CPUInformation::hasSSE.
 { return getCPUInformation().hasSSE; }
bool beast::SystemStats::hasSSE2 () static noexcept
Returns true if Intel SSE2 instructions are available.
Definition at line 71 of file SystemStats.cpp.
References beast::getCPUInformation(), and beast::CPUInformation::hasSSE2.
 { return getCPUInformation().hasSSE2; }
bool beast::SystemStats::hasSSE3 () static noexcept
Returns true if Intel SSE2 instructions are available.
Definition at line 72 of file SystemStats.cpp.
References beast::getCPUInformation(), and beast::CPUInformation::hasSSE3.
 { return getCPUInformation().hasSSE3; }
bool beast::SystemStats::isOperatingSystem64Bit () static
Returns true if the OS is 64-bit, or false for a 32-bit OS.
Definition at line 200 of file bsd_SystemStats.cpp.
 {
    #if BEAST_64BIT
     return true;
    #else
     //xxx not sure how to find this out?..
     return false;
    #endif
 }
void beast::SystemStats::setApplicationCrashHandler (CrashHandlerFunction handler) static
Sets up a global callback function that will be called if the application executes some kind of illegal instruction.
You may want to call getStackBacktrace() in your handler function, to find out where the problem happened and log it, etc.
Definition at line 147 of file SystemStats.cpp.
References bassert, beast::beast_siginterrupt(), beast::globalCrashHandler, beast::handleCrash(), and beast::numElementsInArray().
 {
     bassert (handler != nullptr); // This must be a valid function.
     globalCrashHandler = handler;
    #if BEAST_WINDOWS
     SetUnhandledExceptionFilter (handleCrash);
    #else
     const int signals[] = { SIGFPE, SIGILL, SIGSEGV, SIGBUS, SIGABRT, SIGSYS };
     for (int i = 0; i < numElementsInArray (signals); ++i)
     {
         ::signal (signals[i], handleCrash);
         beast_siginterrupt (signals[i], 1);
     }
    #endif
 }
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_core/system/SystemStats.h
rippled/src/beast/modules/beast_core/native/bsd_SystemStats.cpp
rippled/src/beast/modules/beast_core/native/linux_SystemStats.cpp
rippled/src/beast/modules/beast_core/native/mac_SystemStats.mm
rippled/src/beast/modules/beast_core/native/posix_SharedCode.h
rippled/src/beast/modules/beast_core/native/win32_SystemStats.cpp
rippled/src/beast/modules/beast_core/system/SystemStats.cpp