rippled: rocksdb::PrefixFilterIterator Class Reference
rocksdb::PrefixFilterIterator Class Reference
#include <prefix_filter_iterator.h>
Public Member Functions
PrefixFilterIterator (Iterator *iter, const Slice &prefix, const SliceTransform *prefix_extractor)
~PrefixFilterIterator ()
Slice key () const
Slice value () const
Status status () const
void Next ()
void Prev ()
void Seek (const Slice &k)
void SeekToFirst ()
void SeekToLast ()
bool Valid () const
Public Member Functions inherited from rocksdb::Iterator
Iterator ()
virtual ~Iterator ()
void RegisterCleanup (CleanupFunction function, void *arg1, void *arg2)
Private Attributes
Iterator * iter_
const Slice & prefix_
const SliceTransform * prefix_extractor_
Status status_
Additional Inherited Members
Public Types inherited from rocksdb::Iterator
typedef void(* CleanupFunction)(void *arg1, void *arg2)
Detailed Description
Definition at line 18 of file prefix_filter_iterator.h.
Constructor & Destructor Documentation
rocksdb::PrefixFilterIterator::PrefixFilterIterator (Iterator * iter, const Slice & prefix, const SliceTransform * prefix_extractor) inline
Definition at line 26 of file prefix_filter_iterator.h.
References rocksdb::SliceTransform::InRange(), rocksdb::Status::InvalidArgument(), prefix_extractor_, and status_.
                              : iter_(iter), prefix_(prefix),
                                prefix_extractor_(prefix_extractor),
                                status_(Status::OK()) {
     if (prefix_extractor == nullptr) {
       status_ = Status::InvalidArgument("A prefix filter may not be used "
                                         "unless a function is also defined "
                                         "for extracting prefixes");
     } else if (!prefix_extractor_->InRange(prefix)) {
       status_ = Status::InvalidArgument("Must provide a slice for prefix which"
                                         "is a prefix for some key");
     }
   }
rocksdb::PrefixFilterIterator::~PrefixFilterIterator () inline
Definition at line 41 of file prefix_filter_iterator.h.
References iter_.
{
     delete iter_;
   }
Member Function Documentation
Slice rocksdb::PrefixFilterIterator::key () const inline virtual
Implements rocksdb::Iterator.
Definition at line 44 of file prefix_filter_iterator.h.
References iter_, and rocksdb::Iterator::key().
 { return iter_->key(); }
void rocksdb::PrefixFilterIterator::Next () inline virtual
Implements rocksdb::Iterator.
Definition at line 52 of file prefix_filter_iterator.h.
References iter_, and rocksdb::Iterator::Next().
 { iter_->Next(); }
void rocksdb::PrefixFilterIterator::Prev () inline virtual
Implements rocksdb::Iterator.
Definition at line 53 of file prefix_filter_iterator.h.
References iter_, and rocksdb::Iterator::Prev().
 { iter_->Prev(); }
void rocksdb::PrefixFilterIterator::Seek (const Slice & k) inline virtual
Implements rocksdb::Iterator.
Definition at line 54 of file prefix_filter_iterator.h.
References rocksdb::Status::InvalidArgument(), iter_, prefix_, prefix_extractor_, rocksdb::Iterator::Seek(), status_, and rocksdb::SliceTransform::Transform().
Referenced by SeekToFirst().
{
     if (prefix_extractor_->Transform(k) == prefix_) {
       iter_->Seek(k);
     } else {
       status_ = Status::InvalidArgument("Seek must begin with target prefix");
     }
   }
void rocksdb::PrefixFilterIterator::SeekToFirst () inline virtual
Implements rocksdb::Iterator.
Definition at line 61 of file prefix_filter_iterator.h.
References prefix_, and Seek().
                      {
     Seek(prefix_);
   }
void rocksdb::PrefixFilterIterator::SeekToLast () inline virtual
Implements rocksdb::Iterator.
Definition at line 64 of file prefix_filter_iterator.h.
References rocksdb::Status::NotSupported(), and status_.
                     {
     status_ = Status::NotSupported("SeekToLast is incompatible with prefixes");
   }
Status rocksdb::PrefixFilterIterator::status () const inline virtual
Implements rocksdb::Iterator.
Definition at line 46 of file prefix_filter_iterator.h.
References iter_, rocksdb::Status::ok(), rocksdb::Iterator::status(), and status_.
{
     if (!status_.ok()) {
       return status_;
     }
     return iter_->status();
   }
bool rocksdb::PrefixFilterIterator::Valid () const inline virtual
Implements rocksdb::Iterator.
Definition at line 67 of file prefix_filter_iterator.h.
References iter_, rocksdb::Iterator::key(), rocksdb::Status::ok(), prefix_, prefix_extractor_, status_, rocksdb::SliceTransform::Transform(), and rocksdb::Iterator::Valid().
                      {
     return (status_.ok() && iter_->Valid() &&
             prefix_extractor_->Transform(iter_->key()) == prefix_);
   }
Slice rocksdb::PrefixFilterIterator::value () const inline virtual
Implements rocksdb::Iterator.
Definition at line 45 of file prefix_filter_iterator.h.
References iter_, and rocksdb::Iterator::value().
 { return iter_->value(); }
Member Data Documentation
Iterator* rocksdb::PrefixFilterIterator::iter_ private
Definition at line 20 of file prefix_filter_iterator.h.
Referenced by key(), Next(), Prev(), Seek(), status(), Valid(), value(), and ~PrefixFilterIterator().
const Slice& rocksdb::PrefixFilterIterator::prefix_ private
Definition at line 21 of file prefix_filter_iterator.h.
Referenced by Seek(), SeekToFirst(), and Valid().
const SliceTransform* rocksdb::PrefixFilterIterator::prefix_extractor_ private
Definition at line 22 of file prefix_filter_iterator.h.
Referenced by PrefixFilterIterator(), Seek(), and Valid().
Status rocksdb::PrefixFilterIterator::status_ private
Definition at line 23 of file prefix_filter_iterator.h.
Referenced by PrefixFilterIterator(), Seek(), SeekToLast(), status(), and Valid().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/db/prefix_filter_iterator.h