rippled: ripple::Database Class Reference
ripple::Database Class Reference abstract
#include <Database.h>
Public Member Functions
Database (const char *host)
virtual ~Database ()
virtual void connect ()=0
virtual void disconnect ()=0
virtual bool executeSQL (const char *sql, bool fail_okay=false)=0
bool executeSQL (std::string strSql, bool fail_okay=false)
virtual bool startIterRows (bool finalize=true)=0
virtual void endIterRows ()=0
virtual bool getNextRow (bool finalize=true)=0
bool getNull (const char *colName)
char * getStr (const char *colName, std::string &retStr)
std::string getStrBinary (const std::string &strColName)
std::int32_t getInt (const char *colName)
float getFloat (const char *colName)
bool getBool (const char *colName)
int getBinary (const char *colName, unsigned char *buf, int maxSize)
Blob getBinary (const std::string &strColName)
std::uint64_t getBigInt (const char *colName)
virtual bool getNull (int colIndex)=0
virtual char * getStr (int colIndex, std::string &retStr)=0
virtual std::int32_t getInt (int colIndex)=0
virtual float getFloat (int colIndex)=0
virtual bool getBool (int colIndex)=0
virtual int getBinary (int colIndex, unsigned char *buf, int maxSize)=0
virtual std::uint64_t getBigInt (int colIndex)=0
virtual Blob getBinary (int colIndex)=0
virtual bool setupCheckpointing (JobQueue *)
virtual SqliteDatabase * getSqliteDB ()
virtual int getKBUsedAll ()
virtual int getKBUsedDB ()
Protected Member Functions
bool getColNumber (const char *colName, int *retIndex)
Protected Attributes
int mNumCol
std::string mHost
std::vector< std::string > mColNameTable
Detailed Description
Definition at line 41 of file Database.h.
Constructor & Destructor Documentation
ripple::Database::Database (const char * host) explicit
Definition at line 22 of file Database.cpp.
References mHost.
     : mNumCol (0)
 {
     mHost   = host;
 }
ripple::Database::~Database () virtual
Definition at line 28 of file Database.cpp.
 {
 }
Member Function Documentation
virtual void ripple::Database::connect () pure virtual
Implemented in ripple::SqliteDatabase.
Referenced by ripple::DatabaseCon::DatabaseCon().
virtual void ripple::Database::disconnect () pure virtual
Implemented in ripple::SqliteDatabase.
Referenced by ripple::DatabaseCon::~DatabaseCon().
virtual void ripple::Database::endIterRows () pure virtual
Implemented in ripple::SqliteDatabase.
Referenced by ripple::LocalCredentials::dataFetch(), ripple::UniqueNodeListImp::fetchNext(), ripple::FeaturesImpl::getCreate(), ripple::Ledger::getHashByIndex(), ripple::Ledger::getHashesByIndex(), ripple::UniqueNodeListImp::getSeedDomains(), ripple::UniqueNodeListImp::getSeedNodes(), ripple::Ledger::getSQL(), ripple::UniqueNodeListImp::miscLoad(), ripple::UniqueNodeListImp::nodeBootstrap(), ripple::LocalCredentials::nodeIdentityLoad(), and ripple::Transaction::transactionFromSQL().
virtual bool ripple::Database::executeSQL (const char * sql, bool fail_okay = false) pure virtual
Implemented in ripple::SqliteDatabase.
Referenced by ripple::addTxnSeqField(), ripple::DatabaseCon::DatabaseCon(), ripple::LocalCredentials::dataDelete(), ripple::LocalCredentials::dataFetch(), ripple::LocalCredentials::dataStore(), ripple::ValidationsImp::doWrite(), executeSQL(), ripple::UniqueNodeListImp::fetchNext(), ripple::FeaturesImpl::getCreate(), ripple::Ledger::getHashByIndex(), ripple::Ledger::getHashesByIndex(), ripple::UniqueNodeListImp::getSeedDomains(), ripple::UniqueNodeListImp::getSeedNodes(), ripple::Ledger::getSQL(), ripple::UniqueNodeListImp::miscLoad(), ripple::UniqueNodeListImp::miscSave(), ripple::UniqueNodeListImp::nodeBootstrap(), ripple::LocalCredentials::nodeIdentityCreate(), ripple::LocalCredentials::nodeIdentityLoad(), ripple::UniqueNodeListImp::nodeRemoveDomain(), ripple::UniqueNodeListImp::nodeRemovePublic(), ripple::UniqueNodeListImp::nodeReset(), ripple::UniqueNodeListImp::processIps(), ripple::UniqueNodeListImp::processValidators(), ripple::FeaturesImpl::reportValidations(), ripple::Ledger::saveValidatedLedger(), ripple::UniqueNodeListImp::scoreCompute(), ripple::UniqueNodeListImp::setSeedDomains(), ripple::UniqueNodeListImp::setSeedNodes(), ripple::ApplicationImp::setup(), and ripple::Transaction::transactionFromSQL().
bool ripple::Database::executeSQL (std::string strSql, bool fail_okay = false) inline
Definition at line 55 of file Database.h.
References executeSQL().
     {
         return executeSQL (strSql.c_str (), fail_okay);
     }
std::uint64_t ripple::Database::getBigInt (const char * colName)
Definition at line 122 of file Database.cpp.
References getColNumber().
Referenced by ripple::NetworkOPsImp::getAccountTxs(), ripple::FeaturesImpl::getCreate(), ripple::Ledger::getSQL(), and ripple::NetworkOPsImp::getTxsAccount().
 {
     int index;
     if (getColNumber (colName, &index))
     {
         return getBigInt (index);
     }
     return 0;
 }
virtual std::uint64_t ripple::Database::getBigInt (int colIndex) pure virtual
Implemented in ripple::SqliteDatabase.
int ripple::Database::getBinary (const char * colName, unsigned char * buf, int maxSize)
Definition at line 92 of file Database.cpp.
References getColNumber().
Referenced by ripple::addTxnSeqField(), ripple::LocalCredentials::dataFetch(), ripple::NetworkOPsImp::getAccountTxs(), ripple::NetworkOPsImp::getAccountTxsB(), getBinary(), getStrBinary(), ripple::NetworkOPsImp::getTxsAccount(), ripple::NetworkOPsImp::getTxsAccountB(), and ripple::Transaction::transactionFromSQL().
 {
     int index;
     if (getColNumber (colName, &index))
     {
         return (getBinary (index, buf, maxSize));
     }
     return (0);
 }
Blob ripple::Database::getBinary (const std::string & strColName)
Definition at line 104 of file Database.cpp.
References getBinary(), and getColNumber().
 {
     int index;
     if (getColNumber (strColName.c_str (), &index))
     {
         return getBinary (index);
     }
     return Blob ();
 }
virtual int ripple::Database::getBinary (int colIndex, unsigned char * buf, int maxSize) pure virtual
Implemented in ripple::SqliteDatabase.
virtual Blob ripple::Database::getBinary (int colIndex) pure virtual
Implemented in ripple::SqliteDatabase.
bool ripple::Database::getBool (const char * colName)
Definition at line 80 of file Database.cpp.
References getColNumber().
 {
     int index;
     if (getColNumber (colName, &index))
     {
         return getBool (index);
     }
     return 0;
 }
virtual bool ripple::Database::getBool (int colIndex) pure virtual
Implemented in ripple::SqliteDatabase.
bool ripple::Database::getColNumber (const char * colName, int * retIndex) protected
Definition at line 135 of file Database.cpp.
References mColNameTable.
Referenced by getBigInt(), getBinary(), getBool(), getFloat(), getInt(), getNull(), and getStr().
 {
     for (unsigned int n = 0; n < mColNameTable.size (); n++)
     {
         if (strcmp (colName, mColNameTable[n].c_str ()) == 0)
         {
             *retIndex = n;
             return (true);
         }
     }
     return false;
 }
float ripple::Database::getFloat (const char * colName)
Definition at line 68 of file Database.cpp.
References getColNumber().
 {
     int index;
     if (getColNumber (colName, &index))
     {
         return getFloat (index);
     }
     return 0;
 }
virtual float ripple::Database::getFloat (int colIndex) pure virtual
Implemented in ripple::SqliteDatabase.
std::int32_t ripple::Database::getInt (const char * colName)
Definition at line 56 of file Database.cpp.
References getColNumber().
Referenced by ripple::UniqueNodeListImp::fetchNext(), ripple::NetworkOPsImp::getAccountTxsB(), ripple::UniqueNodeListImp::getSeedDomains(), ripple::UniqueNodeListImp::getSeedNodes(), ripple::NetworkOPsImp::getTxsAccount(), ripple::NetworkOPsImp::getTxsAccountB(), ripple::UniqueNodeListImp::miscLoad(), ripple::UniqueNodeListImp::nodeBootstrap(), ripple::UniqueNodeListImp::scoreCompute(), and ripple::Transaction::transactionFromSQL().
 {
     int index;
     if (getColNumber (colName, &index))
     {
         return getInt (index);
     }
     return 0;
 }
virtual std::int32_t ripple::Database::getInt (int colIndex) pure virtual
Implemented in ripple::SqliteDatabase.
virtual int ripple::Database::getKBUsedAll () inline virtual
Reimplemented in ripple::SqliteDatabase.
Definition at line 104 of file Database.h.
Referenced by ripple::RPCHandler::doGetCounts().
     {
         return -1;
     }
virtual int ripple::Database::getKBUsedDB () inline virtual
Reimplemented in ripple::SqliteDatabase.
Definition at line 108 of file Database.h.
Referenced by ripple::RPCHandler::doGetCounts().
     {
         return -1;
     }
virtual bool ripple::Database::getNextRow (bool finalize = true) pure virtual
Implemented in ripple::SqliteDatabase.
bool ripple::Database::getNull (const char * colName)
Definition at line 32 of file Database.cpp.
References getColNumber().
Referenced by ripple::UniqueNodeListImp::getSeedDomains(), ripple::UniqueNodeListImp::getSeedNodes(), and ripple::UniqueNodeListImp::scoreCompute().
 {
     int index;
     if (getColNumber (colName, &index))
     {
         return getNull (index);
     }
     return true;
 }
virtual bool ripple::Database::getNull (int colIndex) pure virtual
Implemented in ripple::SqliteDatabase.
virtual SqliteDatabase* ripple::Database::getSqliteDB () inline virtual
Reimplemented in ripple::SqliteDatabase.
Definition at line 100 of file Database.h.
Referenced by ripple::Ledger::getHashesByIndex(), ripple::Ledger::loadByHash(), and ripple::Ledger::loadByIndex().
     {
         return nullptr;
     }
char * ripple::Database::getStr (const char * colName, std::string & retStr)
Definition at line 44 of file Database.cpp.
References getColNumber().
Referenced by ripple::addTxnSeqField(), ripple::Ledger::getHashByIndex(), ripple::Ledger::getHashesByIndex(), ripple::getSchema(), ripple::UniqueNodeListImp::getSeedDomains(), ripple::UniqueNodeListImp::getSeedNodes(), ripple::Ledger::getSQL(), ripple::LocalCredentials::nodeIdentityLoad(), and ripple::Transaction::transactionFromSQL().
 {
     int index;
     if (getColNumber (colName, &index))
     {
         return getStr (index, retStr);
     }
     return nullptr;
 }
virtual char* ripple::Database::getStr (int colIndex, std::string & retStr) pure virtual
Implemented in ripple::SqliteDatabase.
std::string ripple::Database::getStrBinary (const std::string & strColName)
Definition at line 116 of file Database.cpp.
References getBinary(), and ripple::strCopy().
Referenced by ripple::UniqueNodeListImp::fetchNext(), ripple::NetworkOPsImp::getLedgerAffectedAccounts(), ripple::UniqueNodeListImp::getSeedDomains(), ripple::UniqueNodeListImp::getSeedNodes(), ripple::UniqueNodeListImp::getUnlJson(), ripple::UniqueNodeListImp::scoreCompute(), and ripple::UniqueNodeListImp::trustedLoad().
 {
     // YYY Could eliminate a copy if getStrBinary was a template.
     return strCopy (getBinary (strColName.c_str ()));
 }
virtual bool ripple::Database::setupCheckpointing (JobQueue *) inline virtual
Reimplemented in ripple::SqliteDatabase.
Definition at line 96 of file Database.h.
     {
         return false;
     }
virtual bool ripple::Database::startIterRows (bool finalize = true) pure virtual
Implemented in ripple::SqliteDatabase.
Referenced by ripple::LocalCredentials::dataFetch(), ripple::UniqueNodeListImp::fetchNext(), ripple::FeaturesImpl::getCreate(), ripple::Ledger::getHashByIndex(), ripple::Ledger::getHashesByIndex(), ripple::UniqueNodeListImp::getSeedDomains(), ripple::UniqueNodeListImp::getSeedNodes(), ripple::Ledger::getSQL(), ripple::UniqueNodeListImp::miscLoad(), ripple::UniqueNodeListImp::nodeBootstrap(), ripple::LocalCredentials::nodeIdentityLoad(), and ripple::Transaction::transactionFromSQL().
Member Data Documentation
std::vector<std::string> ripple::Database::mColNameTable protected
Definition at line 118 of file Database.h.
Referenced by getColNumber(), and ripple::SqliteDatabase::startIterRows().
std::string ripple::Database::mHost protected
Definition at line 117 of file Database.h.
Referenced by ripple::SqliteDatabase::connect(), Database(), ripple::SqliteDatabase::doHook(), ripple::SqliteDatabase::executeSQL(), ripple::SqliteDatabase::getAuxConnection(), and ripple::SqliteDatabase::getNextRow().
int ripple::Database::mNumCol protected
Definition at line 116 of file Database.h.
The documentation for this class was generated from the following files:
rippled/src/ripple_app/data/Database.h
rippled/src/ripple_app/data/Database.cpp