rippled: rocksdb::log::LogTest Class Reference
rocksdb::log::LogTest Class Reference
Classes
class ReportCollector
class StringDest
class StringSource
Public Member Functions
LogTest ()
void Write (const std::string &msg)
size_t WrittenBytes () const
std::string Read ()
void IncrementByte (int offset, int delta)
void SetByte (int offset, char new_byte)
void ShrinkSize (int bytes)
void FixChecksum (int header_offset, int len)
void ForceError ()
size_t DroppedBytes () const
std::string ReportMessage () const
std::string MatchError (const std::string &msg) const
void WriteInitialOffsetLog ()
void CheckOffsetPastEndReturnsNoRecords (uint64_t offset_past_end)
void CheckInitialOffsetRecord (uint64_t initial_offset, int expected_record_offset)
Private Member Functions
std::string & dest_contents ()
const std::string & dest_contents () const
void reset_source_contents ()
Private Attributes
unique_ptr< StringDest > dest_holder_
unique_ptr< StringSource > source_holder_
ReportCollector report_
bool reading_
Writer writer_
Reader reader_
Static Private Attributes
static size_t initial_offset_record_sizes_ []
static uint64_t initial_offset_last_record_offsets_ []
Detailed Description
Definition at line 44 of file log_test.cc.
Constructor & Destructor Documentation
rocksdb::log::LogTest::LogTest () inline
Definition at line 138 of file log_test.cc.
             : dest_holder_(new StringDest),
               source_holder_(new StringSource),
               reading_(false),
               writer_(std::move(dest_holder_)),
               reader_(std::move(source_holder_), &report_, true/*checksum*/,
                       0/*initial_offset*/) {
   }
Member Function Documentation
void rocksdb::log::LogTest::CheckInitialOffsetRecord (uint64_t initial_offset, int expected_record_offset) inline
Definition at line 231 of file log_test.cc.
References ASSERT_EQ, ASSERT_TRUE, rocksdb::log::LogTest::StringSource::contents_, rocksdb::Slice::data(), dest_contents(), initial_offset_last_record_offsets_, initial_offset_record_sizes_, reading_, report_, rocksdb::Slice::size(), and WriteInitialOffsetLog().
{
     WriteInitialOffsetLog();
     reading_ = true;
     unique_ptr<StringSource> source(new StringSource);
     source->contents_ = dest_contents();
     unique_ptr<Reader> offset_reader(
       new Reader(std::move(source), &report_, true/*checksum*/,
                  initial_offset));
     Slice record;
     std::string scratch;
     ASSERT_TRUE(offset_reader->ReadRecord(&record, &scratch));
     ASSERT_EQ(initial_offset_record_sizes_[expected_record_offset],
               record.size());
     ASSERT_EQ(initial_offset_last_record_offsets_[expected_record_offset],
               offset_reader->LastRecordOffset());
     ASSERT_EQ((char)('a' + expected_record_offset), record.data()[0]);
   }
void rocksdb::log::LogTest::CheckOffsetPastEndReturnsNoRecords (uint64_t offset_past_end) inline
Definition at line 218 of file log_test.cc.
References ASSERT_TRUE, rocksdb::log::LogTest::StringSource::contents_, dest_contents(), reading_, report_, WriteInitialOffsetLog(), and WrittenBytes().
{
     WriteInitialOffsetLog();
     reading_ = true;
     unique_ptr<StringSource> source(new StringSource);
     source->contents_ = dest_contents();
     unique_ptr<Reader> offset_reader(
       new Reader(std::move(source), &report_, true/*checksum*/,
                  WrittenBytes() + offset_past_end));
     Slice record;
     std::string scratch;
     ASSERT_TRUE(!offset_reader->ReadRecord(&record, &scratch));
   }
std::string& rocksdb::log::LogTest::dest_contents () inline private
Definition at line 108 of file log_test.cc.
References rocksdb::log::Writer::file(), and writer_.
Referenced by CheckInitialOffsetRecord(), CheckOffsetPastEndReturnsNoRecords(), FixChecksum(), IncrementByte(), reset_source_contents(), SetByte(), ShrinkSize(), and WrittenBytes().
{
     auto dest = dynamic_cast<StringDest*>(writer_.file());
     assert(dest);
     return dest->contents_;
   }
const std::string& rocksdb::log::LogTest::dest_contents () const inline private
Definition at line 114 of file log_test.cc.
References rocksdb::log::Writer::file(), and writer_.
{
     auto dest = dynamic_cast<const StringDest*>(writer_.file());
     assert(dest);
     return dest->contents_;
   }
size_t rocksdb::log::LogTest::DroppedBytes () const inline
Definition at line 193 of file log_test.cc.
References rocksdb::log::LogTest::ReportCollector::dropped_bytes_, and report_.
{
     return report_.dropped_bytes_;
   }
void rocksdb::log::LogTest::FixChecksum (int header_offset, int len) inline
Definition at line 181 of file log_test.cc.
References dest_contents(), rocksdb::EncodeFixed32(), rocksdb::crc32c::Mask(), and rocksdb::crc32c::Value().
{
     // Compute crc of type/len/data
     uint32_t crc = crc32c::Value(&dest_contents()[header_offset+6], 1 + len);
     crc = crc32c::Mask(crc);
     EncodeFixed32(&dest_contents()[header_offset], crc);
   }
void rocksdb::log::LogTest::ForceError () inline
Definition at line 188 of file log_test.cc.
References rocksdb::log::Reader::file(), rocksdb::log::LogTest::StringSource::force_error_, and reader_.
                     {
     auto src = dynamic_cast<StringSource*>(reader_.file());
     src->force_error_ = true;
   }
void rocksdb::log::LogTest::IncrementByte (int offset, int delta) inline
Definition at line 169 of file log_test.cc.
References dest_contents().
{
     dest_contents()[offset] += delta;
   }
std::string rocksdb::log::LogTest::MatchError (const std::string & msg) const inline
Definition at line 202 of file log_test.cc.
References rocksdb::log::LogTest::ReportCollector::message_, and report_.
{
     if (report_.message_.find(msg) == std::string::npos) {
       return report_.message_;
     } else {
       return "OK";
     }
   }
std::string rocksdb::log::LogTest::Read () inline
Definition at line 155 of file log_test.cc.
References reader_, reading_, rocksdb::log::Reader::ReadRecord(), reset_source_contents(), and rocksdb::Slice::ToString().
                    {
     if (!reading_) {
       reading_ = true;
       reset_source_contents();
     }
     std::string scratch;
     Slice record;
     if (reader_.ReadRecord(&record, &scratch)) {
       return record.ToString();
     } else {
       return "EOF";
     }
   }
std::string rocksdb::log::LogTest::ReportMessage () const inline
Definition at line 197 of file log_test.cc.
References rocksdb::log::LogTest::ReportCollector::message_, and report_.
{
     return report_.message_;
   }
void rocksdb::log::LogTest::reset_source_contents () inline private
Definition at line 120 of file log_test.cc.
References dest_contents(), rocksdb::log::Reader::file(), and reader_.
Referenced by Read().
{
     auto src = dynamic_cast<StringSource*>(reader_.file());
     assert(src);
     src->contents_ = dest_contents();
   }
void rocksdb::log::LogTest::SetByte (int offset, char new_byte) inline
Definition at line 173 of file log_test.cc.
References dest_contents().
{
     dest_contents()[offset] = new_byte;
   }
void rocksdb::log::LogTest::ShrinkSize (int bytes) inline
Definition at line 177 of file log_test.cc.
References dest_contents().
{
     dest_contents().resize(dest_contents().size() - bytes);
   }
void rocksdb::log::LogTest::Write (const std::string & msg) inline
Definition at line 146 of file log_test.cc.
References rocksdb::log::Writer::AddRecord(), ASSERT_TRUE, reading_, and writer_.
Referenced by WriteInitialOffsetLog().
{
     ASSERT_TRUE(!reading_) << "Write() after starting to read";
     writer_.AddRecord(Slice(msg));
   }
void rocksdb::log::LogTest::WriteInitialOffsetLog () inline
Definition at line 210 of file log_test.cc.
References initial_offset_record_sizes_, and Write().
Referenced by CheckInitialOffsetRecord(), and CheckOffsetPastEndReturnsNoRecords().
{
     for (int i = 0; i < 4; i++) {
       std::string record(initial_offset_record_sizes_[i],
                          static_cast<char>('a' + i));
       Write(record);
     }
   }
size_t rocksdb::log::LogTest::WrittenBytes () const inline
Definition at line 151 of file log_test.cc.
References dest_contents().
Referenced by CheckOffsetPastEndReturnsNoRecords().
{
     return dest_contents().size();
   }
Member Data Documentation
unique_ptr<StringDest> rocksdb::log::LogTest::dest_holder_ private
Definition at line 126 of file log_test.cc.
uint64_t rocksdb::log::LogTest::initial_offset_last_record_offsets_ static private
Initial value:
=
    {0,
     kHeaderSize + 10000,
     2 * (kHeaderSize + 10000),
     2 * (kHeaderSize + 10000) +
         (2 * log::kBlockSize - 1000) + 3 * kHeaderSize}
Definition at line 135 of file log_test.cc.
Referenced by CheckInitialOffsetRecord().
size_t rocksdb::log::LogTest::initial_offset_record_sizes_ static private
Initial value:
=
    {10000,
     10000,
     2 * log::kBlockSize - 1000,
     1}
Definition at line 134 of file log_test.cc.
Referenced by CheckInitialOffsetRecord(), and WriteInitialOffsetLog().
Reader rocksdb::log::LogTest::reader_ private
Definition at line 131 of file log_test.cc.
Referenced by ForceError(), Read(), and reset_source_contents().
bool rocksdb::log::LogTest::reading_ private
Definition at line 129 of file log_test.cc.
Referenced by CheckInitialOffsetRecord(), CheckOffsetPastEndReturnsNoRecords(), Read(), and Write().
ReportCollector rocksdb::log::LogTest::report_ private
Definition at line 128 of file log_test.cc.
Referenced by CheckInitialOffsetRecord(), CheckOffsetPastEndReturnsNoRecords(), DroppedBytes(), MatchError(), and ReportMessage().
unique_ptr<StringSource> rocksdb::log::LogTest::source_holder_ private
Definition at line 127 of file log_test.cc.
Writer rocksdb::log::LogTest::writer_ private
Definition at line 130 of file log_test.cc.
Referenced by dest_contents(), and Write().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/db/log_test.cc