rippled: rocksdb::Random Class Reference
rocksdb::Random Class Reference
#include <random.h>
Public Member Functions
Random (uint32_t s)
uint32_t Next ()
uint32_t Uniform (int n)
bool OneIn (int n)
uint32_t Skewed (int max_log)
Private Attributes
uint32_t seed_
Detailed Description
Definition at line 19 of file random.h.
Constructor & Destructor Documentation
rocksdb::Random::Random (uint32_t s) inline explicit
Definition at line 23 of file random.h.
 : seed_(s & 0x7fffffffu) { }
Member Function Documentation
uint32_t rocksdb::Random::Next () inline
Definition at line 24 of file random.h.
References seed_.
Referenced by OneIn(), rocksdb::SkipList< Key, Comparator >::RandomHeight(), rocksdb::ConcurrentTest::RandomTarget(), rocksdb::ConcurrentTest::ReadStep(), rocksdb::TEST(), Uniform(), and rocksdb::ConcurrentTest::WriteStep().
                   {
     static const uint32_t M = 2147483647L;   // 2^31-1
     static const uint64_t A = 16807;  // bits 14, 8, 7, 5, 2, 1, 0
     // We are computing
     //       seed_ = (seed_ * A) % M,    where M = 2^31-1
     //
     // seed_ must not be zero or M, or else all subsequent computed values
     // will be zero or M respectively.  For all other values, seed_ will end
     // up cycling through every number in [1,M-1]
     uint64_t product = seed_ * A;
     // Compute (product % M) using the fact that ((x << 31) % M) == x.
     seed_ = static_cast<uint32_t>((product >> 31) + (product & M));
     // The first reduction may overflow by 1 bit, so we may need to
     // repeat.  mod == M is not possible; using > allows the faster
     // sign-bit-based test.
     if (seed_ > M) {
       seed_ -= M;
     }
     return seed_;
   }
bool rocksdb::Random::OneIn (int n) inline
Definition at line 51 of file random.h.
References Next().
Referenced by rocksdb::RandomKey(), and rocksdb::TEST().
 { return (Next() % n) == 0; }
uint32_t rocksdb::Random::Skewed (int max_log) inline
Definition at line 56 of file random.h.
References Uniform().
Referenced by rocksdb::RandomKey(), rocksdb::log::RandomSkewedString(), and rocksdb::TEST().
{
     return Uniform(1 << Uniform(max_log + 1));
   }
uint32_t rocksdb::Random::Uniform (int n) inline
Definition at line 47 of file random.h.
References Next().
Referenced by rocksdb::StressTest::Open(), rocksdb::Harness::PickRandomKey(), rocksdb::test::RandomKey(), rocksdb::RandomKey(), rocksdb::test::RandomString(), Skewed(), rocksdb::TableReaderBenchmark(), rocksdb::TEST(), and rocksdb::Harness::TestRandomAccess().
 { return Next() % n; }
Member Data Documentation
uint32_t rocksdb::Random::seed_ private
Definition at line 21 of file random.h.
Referenced by Next().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/util/random.h