rippled: beast::sqdb::detail Namespace Reference
beast::sqdb::detail Namespace Reference
Classes
struct basic_type_tag
struct user_type_tag
struct exchange_traits
struct exchange_traits< bool >
struct exchange_traits< char >
struct exchange_traits< unsigned char >
struct exchange_traits< short >
struct exchange_traits< unsigned short >
struct exchange_traits< int >
struct exchange_traits< unsigned int >
struct exchange_traits< long >
struct exchange_traits< unsigned long >
struct exchange_traits< long long >
struct exchange_traits< unsigned long long >
struct exchange_traits< float >
struct exchange_traits< double >
struct exchange_traits< long double >
struct exchange_traits< char * >
struct exchange_traits< char const * >
struct exchange_traits< wchar_t * >
struct exchange_traits< wchar_t const * >
struct exchange_traits< std::string >
struct exchange_traits< std::wstring >
struct exchange_traits< String >
struct exchange_traits< std::tm >
struct exchange_traits< blob >
class into_type_base
class standard_into_type
class into_type
class once_temp_type
class once_type
class prepare_temp_type
class prepare_type
class ref_counted_prepare_info
class ref_counted_statement_base
class ref_counted_statement
class statement_imp
struct base_value_holder
class conversion_into_type
class conversion_use_type
class type_ptr
class use_type_base
class standard_use_type
class use_type
Typedefs
typedef type_ptr< into_type_base > into_type_ptr
typedef type_ptr< use_type_base > use_type_ptr
Enumerations
enum exchange_type {
x_null, x_bool, x_char, x_uchar,
x_short, x_ushort, x_int, x_uint,
x_long, x_ulong, x_longlong, x_ulonglong,
x_float, x_double, x_longdouble, x_cstring,
x_cwstring, x_stdstring, x_stdwstring, x_beastString,
x_stdtm, x_blob
}
Functions
const Error sqliteError (const char *sourceFileName, int lineNumber, int sqliteErrorCode)
template<typename T >
into_type_ptr do_into (T &t, basic_type_tag)
template<typename T >
into_type_ptr do_into (T &t, indicator &ind, basic_type_tag)
template<typename T >
into_type_ptr do_into (T &t, user_type_tag)
template<typename T >
into_type_ptr do_into (T &t, indicator &ind, user_type_tag)
template<typename T >
use_type_ptr do_use (T &t, user_type_tag)
template<typename T >
use_type_ptr do_use (T const &t, user_type_tag)
template<typename T >
use_type_ptr do_use (T &t, indicator &ind, user_type_tag)
template<typename T >
use_type_ptr do_use (T const &t, indicator &ind, user_type_tag)
use_type_ptr do_use_null ()
template<typename T >
use_type_ptr do_use (T &t, basic_type_tag)
template<typename T >
use_type_ptr do_use (T const &t, basic_type_tag)
template<typename T >
use_type_ptr do_use (T &t, indicator &ind, basic_type_tag)
template<typename T >
use_type_ptr do_use (T const &t, indicator &ind, basic_type_tag)
Typedef Documentation
typedef type_ptr<into_type_base> beast::sqdb::detail::into_type_ptr
Definition at line 76 of file into_type.h.
typedef type_ptr<use_type_base> beast::sqdb::detail::use_type_ptr
Definition at line 79 of file use_type.h.
Enumeration Type Documentation
enum beast::sqdb::detail::exchange_type
Enumerator
x_null
x_bool
x_char
x_uchar
x_short
x_ushort
x_int
x_uint
x_long
x_ulong
x_longlong
x_ulonglong
x_float
x_double
x_longdouble
x_cstring
x_cwstring
x_stdstring
x_stdwstring
x_beastString
x_stdtm
x_blob
Definition at line 74 of file backend.h.
 {
     x_null, // only for input variables
     x_bool,
     x_char,     x_uchar,
     x_short,    x_ushort,
     x_int,      x_uint,
     x_long,     x_ulong,
     x_longlong, x_ulonglong,
     x_float,    x_double,       x_longdouble,
     x_cstring, // null terminated char*, only valid for use_type
     x_cwstring, // null terminated wchar*, only valid for use_type
     x_stdstring,
     x_stdwstring,
     x_beastString,
     x_stdtm,
     x_blob
 };
Function Documentation
template<typename T > into_type_ptr beast::sqdb::detail::do_into (T & t, basic_type_tag)
Definition at line 114 of file into_type.h.
Referenced by beast::sqdb::into().
 {
     return into_type_ptr(new into_type<T>(t));
 }
template<typename T > into_type_ptr beast::sqdb::detail::do_into (T & t, indicator & ind, basic_type_tag)
Definition at line 120 of file into_type.h.
 {
     return into_type_ptr(new into_type<T>(t, ind));
 }
template<typename T > into_type_ptr beast::sqdb::detail::do_into (T & t, user_type_tag)
Definition at line 154 of file type_conversion.h.
 {
     return into_type_ptr(new conversion_into_type<T>(t));
 }
template<typename T > into_type_ptr beast::sqdb::detail::do_into (T & t, indicator & ind, user_type_tag)
Definition at line 160 of file type_conversion.h.
 {
     return into_type_ptr(new conversion_into_type<T>(t, ind));
 }
template<typename T > use_type_ptr beast::sqdb::detail::do_use (T & t, basic_type_tag)
Definition at line 139 of file use_type.h.
 {
     return use_type_ptr(new use_type<T>(t));
 }
template<typename T > use_type_ptr beast::sqdb::detail::do_use (T const & t, basic_type_tag)
Definition at line 145 of file use_type.h.
 {
     return use_type_ptr(new use_type<T>(t));
 }
template<typename T > use_type_ptr beast::sqdb::detail::do_use (T & t, indicator & ind, basic_type_tag)
Definition at line 151 of file use_type.h.
 {
     return use_type_ptr(new use_type<T>(t, ind));
 }
template<typename T > use_type_ptr beast::sqdb::detail::do_use (T const & t, indicator & ind, basic_type_tag)
Definition at line 157 of file use_type.h.
 {
     return use_type_ptr(new use_type<T>(t, ind));
 }
template<typename T > use_type_ptr beast::sqdb::detail::do_use (T & t, user_type_tag)
Definition at line 166 of file type_conversion.h.
Referenced by beast::sqdb::use().
 {
     return use_type_ptr(new conversion_use_type<T>(t));
 }
template<typename T > use_type_ptr beast::sqdb::detail::do_use (T const & t, user_type_tag)
Definition at line 172 of file type_conversion.h.
 {
     return use_type_ptr(new conversion_use_type<T>(t));
 }
template<typename T > use_type_ptr beast::sqdb::detail::do_use (T & t, indicator & ind, user_type_tag)
Definition at line 178 of file type_conversion.h.
 {
     return use_type_ptr(new conversion_use_type<T>(t, ind));
 }
template<typename T > use_type_ptr beast::sqdb::detail::do_use (T const & t, indicator & ind, user_type_tag)
Definition at line 184 of file type_conversion.h.
 {
     return use_type_ptr(new conversion_use_type<T>(t, ind));
 }
use_type_ptr beast::sqdb::detail::do_use_null () inline
Definition at line 133 of file use_type.h.
References x_null.
Referenced by beast::sqdb::use_null().
 {
     return use_type_ptr(new standard_use_type(0, x_null, true));
 }
const Error beast::sqdb::detail::sqliteError (const char * sourceFileName, int lineNumber, int sqliteErrorCode)
Definition at line 69 of file error_codes.cpp.
References beast::Error::badParameter, beast::Error::canceled, beast::Error::fail(), beast::Error::fileInUse, beast::Error::fileIOError, beast::Error::fileNoPerm, beast::Error::fileNoSpace, beast::Error::fileNotFound, beast::Error::general, beast::Error::invalidData, beast::Error::noMemory, beast::Error::noMoreData, SQLITE_ABORT, SQLITE_AUTH, SQLITE_BUSY, SQLITE_CANTOPEN, SQLITE_CONSTRAINT, SQLITE_CORRUPT, SQLITE_DONE, SQLITE_EMPTY, SQLITE_ERROR, SQLITE_FORMAT, SQLITE_FULL, SQLITE_INTERNAL, SQLITE_INTERRUPT, SQLITE_IOERR, SQLITE_LOCKED, SQLITE_MISMATCH, SQLITE_MISUSE, SQLITE_NOLFS, SQLITE_NOMEM, SQLITE_NOTADB, SQLITE_OK, SQLITE_PERM, SQLITE_PROTOCOL, SQLITE_RANGE, SQLITE_READONLY, SQLITE_ROW, SQLITE_SCHEMA, SQLITE_TOOBIG, beast::Error::success, and beast::Error::unexpected.
Referenced by beast::sqdb::detail::standard_use_type::do_use(), beast::sqdb::detail::statement_imp::do_uses(), beast::sqdb::detail::statement_imp::execute(), beast::sqdb::detail::statement_imp::fetch(), beast::sqdb::session::hard_exec(), beast::sqdb::session::open(), beast::sqdb::detail::statement_imp::prepare(), beast::sqdb::blob::read(), beast::sqdb::blob::select(), and beast::sqdb::blob::write().
 {
     /*
     bassert (sqliteErrorCode != SQLITE_ROW &&
              sqliteErrorCode != SQLITE_DONE);
     */
     Error e;
     String s;
     Error::Code c;
     switch (sqliteErrorCode)
     {
         // should never get these two here but include them just in case
     case SQLITE_ROW:
     case SQLITE_DONE:
     case SQLITE_OK:
         // this is fine, and lets us avoid having to explicitly
         // check for SQLITE_OK and just deal in terms of the Error object.
         c = Error::success;
         break;
     case SQLITE_ERROR:
         s = "an sqlite error or missing database was encountered";
         c = Error::general;
         break;
     case SQLITE_INTERNAL:
         s = "sqlite encountered an internal logic error";
         c = Error::unexpected;
         break;
     case SQLITE_PERM:
         s = "sqlite was denied file access permission";
         c = Error::fileNoPerm;
         break;
     case SQLITE_ABORT:
         s = "the sqlite operation was canceled due to a callback";
         c = Error::canceled;
         break;
     case SQLITE_BUSY:
         s = "the sqlite database file is locked";
         c = Error::fileInUse;
         break;
     case SQLITE_LOCKED:
         s = "the sqlite database table was locked";
         c = Error::fileInUse;
         break;
     case SQLITE_NOMEM:
         s = "sqlite ran out of memory";
         c = Error::noMemory;
         break;
     case SQLITE_READONLY:
         s = "sqlite tried to write to a read-only database";
         c = Error::fileNoPerm;
         break;
     case SQLITE_INTERRUPT:
         s = "the sqlite operation was interrupted";
         c = Error::canceled;
         break;
     case SQLITE_IOERR:
         s = "sqlite encountered a device I/O error";
         c = Error::fileIOError;
         break;
     case SQLITE_CORRUPT:
         s = "the sqlite database is corrupt";
         c = Error::invalidData;
         break;
     case SQLITE_FULL:
         s = "the sqlite database is full";
         c = Error::fileNoSpace;
         break;
     case SQLITE_CANTOPEN:
         s = "the sqlite database could not be opened";
         c = Error::fileNotFound;
         break;
     case SQLITE_PROTOCOL:
         s = "sqlite encountered a lock protocol error";
         c = Error::badParameter;
         break;
     case SQLITE_EMPTY:
         s = "the sqlite database is empty";
         c = Error::noMoreData;
         break;
     case SQLITE_SCHEMA:
         s = "the sqlite database scheme was changed";
         c = Error::invalidData;
         break;
     case SQLITE_TOOBIG:
         s = "the sqlite string or blob was too large";
         c = Error::fileNoSpace;
         break;
     case SQLITE_CONSTRAINT:
         s = "the sqlite operation was aborted due to a constraint violation";
         c = Error::badParameter;
         break;
     case SQLITE_MISMATCH:
         s = "the sqlite data was mismatched";
         c = Error::badParameter;
         break;
     case SQLITE_MISUSE:
         s = "the sqlite library parameter was invalid";
         c = Error::badParameter;
         break;
     case SQLITE_NOLFS:
         s = "the sqlite platform feature is unavailable";
         c = Error::badParameter;
         break;
     case SQLITE_AUTH:
         s = "sqlite authorization was denied";
         c = Error::fileNoPerm;
         break;
     case SQLITE_FORMAT:
         s = "the auxiliary sqlite database has an invalid format";
         c = Error::invalidData;
         break;
     case SQLITE_RANGE:
         s = "the sqlite parameter was invalid";
         c = Error::badParameter;
         break;
     case SQLITE_NOTADB:
         s = "the file is not a sqlite database";
         c = Error::invalidData;
         break;
     default:
         s << "an unknown sqlite3 error code #"
           << String(sqliteErrorCode)
           << "was returned";
         c = Error::general;
         break;
     }
     if (c != Error::success)
         e.fail(sourceFileName, lineNumber, s, c);
     return e;
 }