rippled: ripple::NodeStore::Backend_test Class Reference
ripple::NodeStore::Backend_test Class Reference
Public Member Functions
void testBackend (beast::String type, std::int64_t const seedValue, int numObjectsToTest=2000)
void run ()
Public Member Functions inherited from ripple::NodeStore::TestBase
void storeBatch (Backend &backend, Batch const &batch)
void fetchCopyOfBatch (Backend &backend, Batch *pCopy, Batch const &batch)
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Additional Inherited Members
Public Types inherited from ripple::NodeStore::TestBase
enum { maxPayloadBytes = 2000, numObjectsToTest = 2000 }
Static Public Member Functions inherited from ripple::NodeStore::TestBase
static void createPredictableBatch (Batch &batch, int startingIndex, int numObjects, std::int64_t seedValue)
static bool areBatchesEqual (Batch const &lhs, Batch const &rhs)
static void storeBatch (Database &db, Batch const &batch)
static void fetchCopyOfBatch (Database &db, Batch *pCopy, Batch const &batch)
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 27 of file BackendTests.cpp.
Member Function Documentation
void ripple::NodeStore::Backend_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 91 of file BackendTests.cpp.
References testBackend().
     {
         int const seedValue = 50;
         testBackend ("leveldb", seedValue);
     #ifdef RIPPLE_ENABLE_SQLITE_BACKEND_TESTS
         testBackend ("sqlite", seedValue);
     #endif
     #if RIPPLE_HYPERLEVELDB_AVAILABLE
         testBackend ("hyperleveldb", seedValue);
     #endif
     #if RIPPLE_ROCKSDB_AVAILABLE
         testBackend ("rocksdb", seedValue);
     #endif
     }
void ripple::NodeStore::Backend_test::testBackend (beast::String type, std::int64_t const seedValue, int numObjectsToTest = 2000) inline
Definition at line 30 of file BackendTests.cpp.
References ripple::NodeStore::TestBase::areBatchesEqual(), ripple::NodeStore::TestBase::createPredictableBatch(), beast::File::createTempFile(), beast::unit_test::suite::expect(), ripple::NodeStore::TestBase::fetchCopyOfBatch(), beast::File::getFullPathName(), ripple::NodeStore::make_Manager(), ripple::NodeStore::TestBase::numObjectsToTest, beast.util.CleanCPPFiles::path, beast::UnitTestUtilities::repeatableShuffle(), beast::StringPairArray::set(), ripple::NodeStore::TestBase::storeBatch(), and beast::unit_test::suite::testcase().
Referenced by run().
     {
         std::unique_ptr <Manager> manager (make_Manager ());
         DummyScheduler scheduler;
         testcase ((beast::String ("Backend type=") + type).toStdString());
         beast::StringPairArray params;
         beast::File const path (beast::File::createTempFile ("node_db"));
         params.set ("type", type);
         params.set ("path", path.getFullPathName ());
         // Create a batch
         Batch batch;
         createPredictableBatch (batch, 0, numObjectsToTest, seedValue);
         beast::Journal j;
         {
             // Open the backend
             std::unique_ptr <Backend> backend (manager->make_Backend (
                 params, scheduler, j));
             // Write the batch
             storeBatch (*backend, batch);
             {
                 // Read it back in
                 Batch copy;
                 fetchCopyOfBatch (*backend, &copy, batch);
                 expect (areBatchesEqual (batch, copy), "Should be equal");
             }
             {
                 // Reorder and read the copy again
                 Batch copy;
                 beast::UnitTestUtilities::repeatableShuffle (batch.size (), batch, seedValue);
                 fetchCopyOfBatch (*backend, &copy, batch);
                 expect (areBatchesEqual (batch, copy), "Should be equal");
             }
         }
         {
             // Re-open the backend
             std::unique_ptr <Backend> backend (manager->make_Backend (
                 params, scheduler, j));
             // Read it back in
             Batch copy;
             fetchCopyOfBatch (*backend, &copy, batch);
             // Canonicalize the source and destination batches
             std::sort (batch.begin (), batch.end (), NodeObject::LessThan ());
             std::sort (copy.begin (), copy.end (), NodeObject::LessThan ());
             expect (areBatchesEqual (batch, copy), "Should be equal");
         }
     }
The documentation for this class was generated from the following file:
rippled/src/ripple_core/nodestore/tests/BackendTests.cpp