rippled: rocksdb::ArenaImpl Class Reference
rocksdb::ArenaImpl Class Reference
#include <arena_impl.h>
Public Member Functions
ArenaImpl (size_t block_size=kMinBlockSize)
virtual ~ArenaImpl ()
virtual char * Allocate (size_t bytes)
virtual char * AllocateAligned (size_t bytes)
virtual const size_t ApproximateMemoryUsage ()
virtual const size_t MemoryAllocatedBytes ()
Public Member Functions inherited from rocksdb::Arena
Arena ()
virtual ~Arena ()
Private Member Functions
char * AllocateFallback (size_t bytes)
char * AllocateNewBlock (size_t block_bytes)
ArenaImpl (const ArenaImpl &)
void operator= (const ArenaImpl &)
Private Attributes
size_t block_size_
char * alloc_ptr_
size_t alloc_bytes_remaining_
std::vector< char * > blocks_
size_t blocks_memory_
Static Private Attributes
static const size_t kMinBlockSize = 4096
static const size_t kMaxBlockSize = 2 << 30
Detailed Description
Definition at line 23 of file arena_impl.h.
Constructor & Destructor Documentation
rocksdb::ArenaImpl::ArenaImpl (size_t block_size = kMinBlockSize) explicit
Definition at line 14 of file arena_impl.cc.
References alloc_bytes_remaining_, alloc_ptr_, block_size_, blocks_memory_, kMaxBlockSize, and kMinBlockSize.
{
   if (block_size < kMinBlockSize) {
     block_size_ = kMinBlockSize;
   } else if (block_size > kMaxBlockSize) {
     block_size_ = kMaxBlockSize;
   } else {
     block_size_ = block_size;
   }
   blocks_memory_ = 0;
   alloc_ptr_ = nullptr;  // First allocation will allocate a block
   alloc_bytes_remaining_ = 0;
 }
rocksdb::ArenaImpl::~ArenaImpl () virtual
Definition at line 28 of file arena_impl.cc.
References blocks_.
                       {
   for (size_t i = 0; i < blocks_.size(); i++) {
     delete[] blocks_[i];
   }
 }
rocksdb::ArenaImpl::ArenaImpl (const ArenaImpl &) private
Member Function Documentation
char * rocksdb::ArenaImpl::Allocate (size_t bytes) inline virtual
Implements rocksdb::Arena.
Definition at line 70 of file arena_impl.h.
References alloc_bytes_remaining_, alloc_ptr_, and AllocateFallback().
Referenced by rocksdb::MemTable::Add(), and rocksdb::TEST().
{
   // The semantics of what to return are a bit messy if we allow
   // 0-byte allocations, so we disallow them here (we don't need
   // them for our internal use).
   assert(bytes > 0);
   if (bytes <= alloc_bytes_remaining_) {
     char* result = alloc_ptr_;
     alloc_ptr_ += bytes;
     alloc_bytes_remaining_ -= bytes;
     return result;
   }
   return AllocateFallback(bytes);
 }
char * rocksdb::ArenaImpl::AllocateAligned (size_t bytes) virtual
Implements rocksdb::Arena.
Definition at line 52 of file arena_impl.cc.
References alloc_bytes_remaining_, alloc_ptr_, and AllocateFallback().
Referenced by rocksdb::TEST().
{
   const int align = sizeof(void*);    // We'll align to pointer size
   assert((align & (align-1)) == 0);   // Pointer size should be a power of 2
   size_t current_mod = reinterpret_cast<uintptr_t>(alloc_ptr_) & (align-1);
   size_t slop = (current_mod == 0 ? 0 : align - current_mod);
   size_t needed = bytes + slop;
   char* result;
   if (needed <= alloc_bytes_remaining_) {
     result = alloc_ptr_ + slop;
     alloc_ptr_ += needed;
     alloc_bytes_remaining_ -= needed;
   } else {
     // AllocateFallback always returned aligned memory
     result = AllocateFallback(bytes);
   }
   assert((reinterpret_cast<uintptr_t>(result) & (align-1)) == 0);
   return result;
 }
char * rocksdb::ArenaImpl::AllocateFallback (size_t bytes) private
Definition at line 34 of file arena_impl.cc.
References alloc_bytes_remaining_, alloc_ptr_, AllocateNewBlock(), and block_size_.
Referenced by Allocate(), and AllocateAligned().
{
   if (bytes > block_size_ / 4) {
     // Object is more than a quarter of our block size.  Allocate it separately
     // to avoid wasting too much space in leftover bytes.
     char* result = AllocateNewBlock(bytes);
     return result;
   }
   // We waste the remaining space in the current block.
   alloc_ptr_ = AllocateNewBlock(block_size_);
   alloc_bytes_remaining_ = block_size_;
   char* result = alloc_ptr_;
   alloc_ptr_ += bytes;
   alloc_bytes_remaining_ -= bytes;
   return result;
 }
char * rocksdb::ArenaImpl::AllocateNewBlock (size_t block_bytes) private
Definition at line 71 of file arena_impl.cc.
References blocks_, and blocks_memory_.
Referenced by AllocateFallback().
{
   char* result = new char[block_bytes];
   blocks_memory_ += block_bytes;
   blocks_.push_back(result);
   return result;
 }
virtual const size_t rocksdb::ArenaImpl::ApproximateMemoryUsage () inline virtual
Implements rocksdb::Arena.
Definition at line 37 of file arena_impl.h.
References blocks_, and blocks_memory_.
Referenced by rocksdb::MemTable::ApproximateMemoryUsage(), and rocksdb::TEST().
{
     return blocks_memory_ + blocks_.capacity() * sizeof(char*);
   }
virtual const size_t rocksdb::ArenaImpl::MemoryAllocatedBytes () inline virtual
Implements rocksdb::Arena.
Definition at line 41 of file arena_impl.h.
References blocks_memory_.
Referenced by rocksdb::TEST().
{
     return blocks_memory_;
   }
void rocksdb::ArenaImpl::operator= (const ArenaImpl &) private
Member Data Documentation
size_t rocksdb::ArenaImpl::alloc_bytes_remaining_ private
Definition at line 57 of file arena_impl.h.
Referenced by Allocate(), AllocateAligned(), AllocateFallback(), and ArenaImpl().
char* rocksdb::ArenaImpl::alloc_ptr_ private
Definition at line 56 of file arena_impl.h.
Referenced by Allocate(), AllocateAligned(), AllocateFallback(), and ArenaImpl().
size_t rocksdb::ArenaImpl::block_size_ private
Definition at line 53 of file arena_impl.h.
Referenced by AllocateFallback(), and ArenaImpl().
std::vector<char*> rocksdb::ArenaImpl::blocks_ private
Definition at line 60 of file arena_impl.h.
Referenced by AllocateNewBlock(), ApproximateMemoryUsage(), and ~ArenaImpl().
size_t rocksdb::ArenaImpl::blocks_memory_ private
Definition at line 63 of file arena_impl.h.
Referenced by AllocateNewBlock(), ApproximateMemoryUsage(), ArenaImpl(), and MemoryAllocatedBytes().
const size_t rocksdb::ArenaImpl::kMaxBlockSize = 2 << 30 static private
Definition at line 50 of file arena_impl.h.
Referenced by ArenaImpl().
const size_t rocksdb::ArenaImpl::kMinBlockSize = 4096 static private
Definition at line 49 of file arena_impl.h.
Referenced by ArenaImpl().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/util/arena_impl.h
rippled/src/ripple/rocksdb/rocksdb/util/arena_impl.cc