rippled: ripple::TestOverlay::BasicPeer< PeerType, MessageType > Class Template Reference
ripple::TestOverlay::BasicPeer< PeerType, MessageType > Class Template Reference
Public Types
typedef PeerType Peer
typedef MessageType Message
typedef BasicLink< Peer, Message > Link
typedef std::vector< Link > Links
Public Member Functions
~BasicPeer ()
bool operator== (Peer const &rhs) const
Peer & peer ()
Peer const & peer () const
Links & links ()
Links const & links () const
void connect (Peer &to)
void disconnect (Peer &to)
void send (Message const &m)
void pre_step ()
void step ()
Private Attributes
Links m_links
Detailed Description
template<typename PeerType, typename MessageType>
class ripple::TestOverlay::BasicPeer< PeerType, MessageType >
Models a peer.
Definition at line 300 of file TestOverlay.cpp.
Member Typedef Documentation
template<typename PeerType, typename MessageType> typedef BasicLink<Peer, Message> ripple::TestOverlay::BasicPeer< PeerType, MessageType >::Link
Definition at line 305 of file TestOverlay.cpp.
template<typename PeerType, typename MessageType> typedef std::vector<Link> ripple::TestOverlay::BasicPeer< PeerType, MessageType >::Links
Definition at line 306 of file TestOverlay.cpp.
template<typename PeerType, typename MessageType> typedef MessageType ripple::TestOverlay::BasicPeer< PeerType, MessageType >::Message
Definition at line 304 of file TestOverlay.cpp.
template<typename PeerType, typename MessageType> typedef PeerType ripple::TestOverlay::BasicPeer< PeerType, MessageType >::Peer
Definition at line 303 of file TestOverlay.cpp.
Constructor & Destructor Documentation
template<typename PeerType, typename MessageType> ripple::TestOverlay::BasicPeer< PeerType, MessageType >::~BasicPeer () inline
Definition at line 308 of file TestOverlay.cpp.
     {
         for (typename Links::iterator iter (links().begin());
             iter != links().end(); ++iter)
             iter->to().links().erase (std::find_if (
                 iter->to().links().begin(), iter->to().links().end(),
                     is_to (peer())));
     }
Member Function Documentation
template<typename PeerType, typename MessageType> void ripple::TestOverlay::BasicPeer< PeerType, MessageType >::connect (Peer & to) inline
Definition at line 342 of file TestOverlay.cpp.
     {
         m_links.emplace_back (to, peer(), false);
         to.m_links.emplace_back (peer(), to, true);
     }
template<typename PeerType, typename MessageType> void ripple::TestOverlay::BasicPeer< PeerType, MessageType >::disconnect (Peer & to) inline
Definition at line 348 of file TestOverlay.cpp.
     {
         typename Links::iterator const iter (std::find_if (
             links().begin(), links().end(), is_to (to)));
         iter->to().links().erase (std::find_if (
             iter->to().links().begin(), iter->to().links.end(),
                 is_to (peer())));
     }
template<typename PeerType, typename MessageType> Links& ripple::TestOverlay::BasicPeer< PeerType, MessageType >::links () inline
Definition at line 332 of file TestOverlay.cpp.
Referenced by ripple::TestOverlay::BasicPeer< Peer, Message >::disconnect(), ripple::TestOverlay::BasicPeer< Peer, Message >::pre_step(), ripple::TestOverlay::BasicPeer< Peer, Message >::send(), ripple::TestOverlay::BasicPeer< Peer, Message >::step(), and ripple::TestOverlay::BasicPeer< Peer, Message >::~BasicPeer().
     {
         return m_links;
     }
template<typename PeerType, typename MessageType> Links const& ripple::TestOverlay::BasicPeer< PeerType, MessageType >::links () const inline
Definition at line 337 of file TestOverlay.cpp.
     {
         return m_links;
     }
template<typename PeerType, typename MessageType> bool ripple::TestOverlay::BasicPeer< PeerType, MessageType >::operator== (Peer const & rhs) const inline
Definition at line 317 of file TestOverlay.cpp.
     {
         return this == &rhs;
     }
template<typename PeerType, typename MessageType> Peer& ripple::TestOverlay::BasicPeer< PeerType, MessageType >::peer () inline
Definition at line 322 of file TestOverlay.cpp.
Referenced by ripple::TestOverlay::BasicPeer< Peer, Message >::connect(), ripple::TestOverlay::BasicPeer< Peer, Message >::disconnect(), and ripple::TestOverlay::BasicPeer< Peer, Message >::~BasicPeer().
     {
         return *static_cast<Peer*>(this);
     }
template<typename PeerType, typename MessageType> Peer const& ripple::TestOverlay::BasicPeer< PeerType, MessageType >::peer () const inline
Definition at line 327 of file TestOverlay.cpp.
     {
         return *static_cast<Peer const*>(this);
     }
template<typename PeerType, typename MessageType> void ripple::TestOverlay::BasicPeer< PeerType, MessageType >::pre_step () inline
Definition at line 364 of file TestOverlay.cpp.
     {
         for (typename Links::iterator iter (links().begin());
             iter != links().end(); ++iter)
             iter->pre_step ();
     }
template<typename PeerType, typename MessageType> void ripple::TestOverlay::BasicPeer< PeerType, MessageType >::send (Message const & m) inline
Definition at line 357 of file TestOverlay.cpp.
     {
         for (typename Links::iterator iter (links().begin());
             iter != links().end(); ++iter)
             iter->send (m);
     }
template<typename PeerType, typename MessageType> void ripple::TestOverlay::BasicPeer< PeerType, MessageType >::step () inline
Definition at line 371 of file TestOverlay.cpp.
     {
         for (typename Links::iterator iter (links().begin());
             iter != links().end(); ++iter)
             iter->step ();
     }
Member Data Documentation
template<typename PeerType, typename MessageType> Links ripple::TestOverlay::BasicPeer< PeerType, MessageType >::m_links private
Definition at line 379 of file TestOverlay.cpp.
Referenced by ripple::TestOverlay::BasicPeer< Peer, Message >::connect(), and ripple::TestOverlay::BasicPeer< Peer, Message >::links().
The documentation for this class was generated from the following file:
rippled/src/ripple/testoverlay/impl/TestOverlay.cpp