rippled: ripple::ValidationsImp Class Reference
ripple::ValidationsImp Class Reference
Public Member Functions
ValidationsImp ()
Public Member Functions inherited from ripple::Validations
virtual ~Validations ()
Private Types
typedef RippleMutex LockType
typedef std::lock_guard< LockType > ScopedLockType
typedef
beast::GenericScopedUnlock
< LockType > ScopedUnlockType
Private Member Functions
boost::shared_ptr< ValidationSet > findCreateSet (uint256 const &ledgerHash)
boost::shared_ptr< ValidationSet > findSet (uint256 const &ledgerHash)
bool addValidation (SerializedValidation::ref val, const std::string &source)
void tune (int size, int age)
ValidationSet getValidations (uint256 const &ledger)
void getValidationCount (uint256 const &ledger, bool currentOnly, int &trusted, int &untrusted)
void getValidationTypes (uint256 const &ledger, int &full, int &partial)
int getTrustedValidationCount (uint256 const &ledger)
int getFeeAverage (uint256 const &ledger, std::uint64_t ref, std::uint64_t &fee)
int getNodesAfter (uint256 const &ledger)
int getLoadRatio (bool overLoaded)
std::list
< SerializedValidation::pointer > getCurrentTrustedValidations ()
ripple::unordered_map< uint256,
currentValidationCount > getCurrentValidations (uint256 currentLedger, uint256 priorLedger)
void flush ()
void condWrite ()
void doWrite (Job &)
void sweep ()
Private Attributes
LockType mLock
TaggedCache< uint256,
ValidationSet > mValidations
ripple::unordered_map< uint160,
SerializedValidation::pointer > mCurrentValidations
std::vector
< SerializedValidation::pointer > mStaleValidations
bool mWriting
Additional Inherited Members
Static Public Member Functions inherited from ripple::Validations
static Validations * New ()
Detailed Description
Definition at line 29 of file Validations.cpp.
Member Typedef Documentation
typedef RippleMutex ripple::ValidationsImp::LockType private
Definition at line 32 of file Validations.cpp.
typedef std::lock_guard<LockType> ripple::ValidationsImp::ScopedLockType private
Definition at line 33 of file Validations.cpp.
typedef beast::GenericScopedUnlock<LockType> ripple::ValidationsImp::ScopedUnlockType private
Definition at line 34 of file Validations.cpp.
Constructor & Destructor Documentation
ripple::ValidationsImp::ValidationsImp () inline
Definition at line 63 of file Validations.cpp.
         : mValidations ("Validations", 128, 600, get_seconds_clock (),
             LogPartition::getJournal <TaggedCacheLog> ())
         , mWriting (false)
     {
         mStaleValidations.reserve (512);
     }
Member Function Documentation
bool ripple::ValidationsImp::addValidation (SerializedValidation::ref val, const std::string & source) inline private virtual
Implements ripple::Validations.
Definition at line 72 of file Validations.cpp.
References ripple::LedgerMaster::checkAccept(), ripple::getApp(), ripple::NetworkOPs::getCloseTimeNC(), ripple::Application::getLedgerMaster(), ripple::RippleAddress::getNodeID(), ripple::Application::getOPs(), ripple::Application::getUNL(), hash, ripple::RippleAddress::humanNodePublic(), LEDGER_EARLY_INTERVAL, LEDGER_VAL_INTERVAL, ripple::lsDEBUG, ripple::lsWARNING, ripple::UniqueNodeList::nodeInUNL(), and WriteLog.
     {
         RippleAddress signer = val->getSignerPublic ();
         bool isCurrent = false;
         if (!val->isTrusted() && getApp().getUNL().nodeInUNL (signer))
             val->setTrusted();
         std::uint32_t now = getApp().getOPs().getCloseTimeNC();
         std::uint32_t valClose = val->getSignTime();
         if ((now > (valClose - LEDGER_EARLY_INTERVAL)) && (now < (valClose + LEDGER_VAL_INTERVAL)))
             isCurrent = true;
         else
             WriteLog (lsWARNING, Validations) << "Received stale validation now=" << now << ", close=" << valClose;
         if (!val->isTrusted ())
         {
             WriteLog (lsDEBUG, Validations) << "Node " << signer.humanNodePublic () << " not in UNL st=" << val->getSignTime () <<
                                             ", hash=" << val->getLedgerHash () << ", shash=" << val->getSigningHash () << " src=" << source;
         }
         uint256 hash = val->getLedgerHash ();
         uint160 node = signer.getNodeID ();
         if (val->isTrusted () && isCurrent)
         {
             ScopedLockType sl (mLock);
             if (!findCreateSet (hash)->insert (std::make_pair (node, val)).second)
                 return false;
             auto it = mCurrentValidations.find (node);
             if (it == mCurrentValidations.end ())
             {
                 // No previous validation from this validator
                 mCurrentValidations.emplace (node, val);
             }
             else if (!it->second)
             {
                 // Previous validation has expired
                 it->second = val;
             }
             else if (val->getSignTime () > it->second->getSignTime ())
             {
                 // This is a newer validation
                 val->setPreviousHash (it->second->getLedgerHash ());
                 mStaleValidations.push_back (it->second);
                 it->second = val;
                 condWrite ();
             }
             else
             {
                 // We already have a newer validation from this source
                 isCurrent = false;
             }
         }
         WriteLog (lsDEBUG, Validations) << "Val for " << hash << " from " << signer.humanNodePublic ()
                                         << " added " << (val->isTrusted () ? "trusted/" : "UNtrusted/") << (isCurrent ? "current" : "stale");
         if (val->isTrusted () && isCurrent)
         {
             getApp().getLedgerMaster ().checkAccept (hash, val->getFieldU32 (sfLedgerSequence));
             return true;
         }
         // FIXME: This never forwards untrusted validations
         return false;
     }
void ripple::ValidationsImp::condWrite () inline private
Definition at line 415 of file Validations.cpp.
References ripple::JobQueue::addJob(), BIND_TYPE, doWrite(), ripple::getApp(), ripple::Application::getJobQueue(), ripple::jtWRITE, and P_1.
     {
         if (mWriting)
             return;
         mWriting = true;
         getApp().getJobQueue ().addJob (jtWRITE, "Validations::doWrite",
                                        BIND_TYPE (&ValidationsImp::doWrite, this, P_1));
     }
void ripple::ValidationsImp::doWrite (Job &) inline private
Definition at line 425 of file Validations.cpp.
References db, ripple::Serializer::erase(), ripple::Database::executeSQL(), ripple::getApp(), ripple::DatabaseCon::getDB(), ripple::Application::getLedgerDB(), ripple::jtDISK, ripple::Serializer::peekData(), and ripple::sqlEscape().
Referenced by condWrite().
     {
         LoadEvent::autoptr event (getApp().getJobQueue ().getLoadEventAP (jtDISK, "ValidationWrite"));
         boost::format insVal ("INSERT INTO Validations "
                               "(LedgerHash,NodePubKey,SignTime,RawData) VALUES ('%s','%s','%u',%s);");
         ScopedLockType sl (mLock);
         assert (mWriting);
         while (!mStaleValidations.empty ())
         {
             std::vector<SerializedValidation::pointer> vector;
             vector.reserve (512);
             mStaleValidations.swap (vector);
             {
                 ScopedUnlockType sul (mLock);
                 {
                     Database* db = getApp().getLedgerDB ()->getDB ();
                     DeprecatedScopedLock dbl (getApp().getLedgerDB ()->getDBLock ());
                     Serializer s (1024);
                     db->executeSQL ("BEGIN TRANSACTION;");
                     BOOST_FOREACH (SerializedValidation::ref it, vector)
                     {
                         s.erase ();
                         it->add (s);
                         db->executeSQL (boost::str (insVal % it->getLedgerHash ().GetHex ()
                                                     % it->getSignerPublic ().humanNodePublic () % it->getSignTime ()
                                                     % sqlEscape (s.peekData ())));
                     }
                     db->executeSQL ("END TRANSACTION;");
                 }
             }
         }
         mWriting = false;
     }
boost::shared_ptr<ValidationSet> ripple::ValidationsImp::findCreateSet (uint256 const & ledgerHash) inline private
Definition at line 44 of file Validations.cpp.
References ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::canonicalize(), and ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::fetch().
     {
         VSpointer j = mValidations.fetch (ledgerHash);
         if (!j)
         {
             j = boost::make_shared<ValidationSet> ();
             mValidations.canonicalize (ledgerHash, j);
         }
         return j;
     }
boost::shared_ptr<ValidationSet> ripple::ValidationsImp::findSet (uint256 const & ledgerHash) inline private
Definition at line 57 of file Validations.cpp.
References ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::fetch().
     {
         return mValidations.fetch (ledgerHash);
     }
void ripple::ValidationsImp::flush () inline private virtual
Implements ripple::Validations.
Definition at line 388 of file Validations.cpp.
References ripple::lsDEBUG, ripple::lsINFO, and WriteLog.
     {
         bool anyNew = false;
         WriteLog (lsINFO, Validations) << "Flushing validations";
         ScopedLockType sl (mLock);
         BOOST_FOREACH (u160_val_pair & it, mCurrentValidations)
         {
             if (it.second)
                 mStaleValidations.push_back (it.second);
             anyNew = true;
         }
         mCurrentValidations.clear ();
         if (anyNew)
             condWrite ();
         while (mWriting)
         {
             ScopedUnlockType sul (mLock);
             boost::this_thread::sleep (boost::posix_time::milliseconds (100));
         }
         WriteLog (lsDEBUG, Validations) << "Validations flushed";
     }
std::list<SerializedValidation::pointer> ripple::ValidationsImp::getCurrentTrustedValidations () inline private virtual
Implements ripple::Validations.
Definition at line 303 of file Validations.cpp.
References ripple::getApp(), ripple::NetworkOPs::getNetworkTimeNC(), ripple::Application::getOPs(), and LEDGER_VAL_INTERVAL.
     {
         std::uint32_t cutoff = getApp().getOPs ().getNetworkTimeNC () - LEDGER_VAL_INTERVAL;
         std::list<SerializedValidation::pointer> ret;
         ScopedLockType sl (mLock);
         ripple::unordered_map<uint160, SerializedValidation::pointer>::iterator it = mCurrentValidations.begin ();
         while (it != mCurrentValidations.end ())
         {
             if (!it->second) // contains no record
                 it = mCurrentValidations.erase (it);
             else if (it->second->getSignTime () < cutoff)
             {
                 // contains a stale record
                 mStaleValidations.push_back (it->second);
                 it->second.reset ();
                 condWrite ();
                 it = mCurrentValidations.erase (it);
             }
             else
             {
                 // contains a live record
                 if (it->second->isTrusted ())
                     ret.push_back (it->second);
                 ++it;
             }
         }
         return ret;
     }
ripple::unordered_map<uint256, currentValidationCount> ripple::ValidationsImp::getCurrentValidations (uint256 currentLedger, uint256 priorLedger) inline private virtual
Implements ripple::Validations.
Definition at line 338 of file Validations.cpp.
References ripple::getApp(), ripple::NetworkOPs::getNetworkTimeNC(), ripple::Application::getOPs(), ripple::base_uint< BITS >::isNonZero(), LEDGER_VAL_INTERVAL, ripple::lsTRACE, and WriteLog.
     {
         std::uint32_t cutoff = getApp().getOPs ().getNetworkTimeNC () - LEDGER_VAL_INTERVAL;
         bool valCurrentLedger = currentLedger.isNonZero ();
         bool valPriorLedger = priorLedger.isNonZero ();
         ripple::unordered_map<uint256, currentValidationCount> ret;
         ScopedLockType sl (mLock);
         ripple::unordered_map<uint160, SerializedValidation::pointer>::iterator it = mCurrentValidations.begin ();
         while (it != mCurrentValidations.end ())
         {
             if (!it->second) // contains no record
                 it = mCurrentValidations.erase (it);
             else if (it->second->getSignTime () < cutoff)
             {
                 // contains a stale record
                 mStaleValidations.push_back (it->second);
                 it->second.reset ();
                 condWrite ();
                 it = mCurrentValidations.erase (it);
             }
             else
             {
                 // contains a live record
                 bool countPreferred = valCurrentLedger && (it->second->getLedgerHash () == currentLedger);
                 if (!countPreferred && // allow up to one ledger slip in either direction
                         ((valCurrentLedger && it->second->isPreviousHash (currentLedger)) ||
                          (valPriorLedger && (it->second->getLedgerHash () == priorLedger))))
                 {
                     countPreferred = true;
                     WriteLog (lsTRACE, Validations) << "Counting for " << currentLedger << " not " << it->second->getLedgerHash ();
                 }
                 currentValidationCount& p = countPreferred ? ret[currentLedger] : ret[it->second->getLedgerHash ()];
                 ++ (p.first);
                 uint160 ni = it->second->getNodeID ();
                 if (ni > p.second)
                     p.second = ni;
                 ++it;
             }
         }
         return ret;
     }
int ripple::ValidationsImp::getFeeAverage (uint256 const & ledger, std::uint64_t ref, std::uint64_t & fee) inline private virtual
Implements ripple::Validations.
Definition at line 239 of file Validations.cpp.
     {
         int trusted = 0;
         fee = 0;
         ScopedLockType sl (mLock);
         VSpointer set = findSet (ledger);
         if (set)
         {
             BOOST_FOREACH (u160_val_pair & it, *set)
             {
                 if (it.second->isTrusted ())
                 {
                     ++trusted;
                     if (it.second->isFieldPresent(sfLoadFee))
                         fee += it.second->getFieldU32(sfLoadFee);
                     else
                         fee += ref;
                  }
             }
         }
         if (trusted == 0)
             fee = ref;
         else
             fee /= trusted;
         return trusted;
     }
int ripple::ValidationsImp::getLoadRatio (bool overLoaded) inline private virtual
Implements ripple::Validations.
Definition at line 282 of file Validations.cpp.
     {
         // how many trusted nodes are able to keep up, higher is better
         int goodNodes = overLoaded ? 1 : 0;
         int badNodes = overLoaded ? 0 : 1;
         {
             ScopedLockType sl (mLock);
             BOOST_FOREACH (u160_val_pair & it, mCurrentValidations)
             {
                 if (it.second->isTrusted ())
                 {
                     if (it.second->isFull ())
                         ++goodNodes;
                     else
                         ++badNodes;
                 }
             }
         }
         return (goodNodes * 100) / (goodNodes + badNodes);
     }
int ripple::ValidationsImp::getNodesAfter (uint256 const & ledger) inline private virtual
Implements ripple::Validations.
Definition at line 269 of file Validations.cpp.
     {
         // Number of trusted nodes that have moved past this ledger
         int count = 0;
         ScopedLockType sl (mLock);
         BOOST_FOREACH (u160_val_pair & it, mCurrentValidations)
         {
             if (it.second->isTrusted () && it.second->isPreviousHash (ledger))
                 ++count;
         }
         return count;
     }
int ripple::ValidationsImp::getTrustedValidationCount (uint256 const & ledger) inline private virtual
Implements ripple::Validations.
Definition at line 221 of file Validations.cpp.
     {
         int trusted = 0;
         ScopedLockType sl (mLock);
         VSpointer set = findSet (ledger);
         if (set)
         {
             BOOST_FOREACH (u160_val_pair & it, *set)
             {
                 if (it.second->isTrusted ())
                     ++trusted;
             }
         }
         return trusted;
     }
void ripple::ValidationsImp::getValidationCount (uint256 const & ledger, bool currentOnly, int & trusted, int & untrusted) inline private virtual
Implements ripple::Validations.
Definition at line 162 of file Validations.cpp.
References ripple::getApp(), ripple::NetworkOPs::getNetworkTimeNC(), ripple::Application::getOPs(), LEDGER_EARLY_INTERVAL, LEDGER_VAL_INTERVAL, ripple::lsTRACE, and WriteLog.
     {
         trusted = untrusted = 0;
         ScopedLockType sl (mLock);
         VSpointer set = findSet (ledger);
         if (set)
         {
             std::uint32_t now = getApp().getOPs ().getNetworkTimeNC ();
             BOOST_FOREACH (u160_val_pair & it, *set)
             {
                 bool isTrusted = it.second->isTrusted ();
                 if (isTrusted && currentOnly)
                 {
                     std::uint32_t closeTime = it.second->getSignTime ();
                     if ((now < (closeTime - LEDGER_EARLY_INTERVAL)) || (now > (closeTime + LEDGER_VAL_INTERVAL)))
                         isTrusted = false;
                     else
                     {
                         WriteLog (lsTRACE, Validations) << "VC: Untrusted due to time " << ledger;
                     }
                 }
                 if (isTrusted)
                     ++trusted;
                 else
                     ++untrusted;
             }
         }
         WriteLog (lsTRACE, Validations) << "VC: " << ledger << "t:" << trusted << " u:" << untrusted;
     }
ValidationSet ripple::ValidationsImp::getValidations (uint256 const & ledger) inline private virtual
Implements ripple::Validations.
Definition at line 150 of file Validations.cpp.
     {
         {
             ScopedLockType sl (mLock);
             VSpointer set = findSet (ledger);
             if (set)
                 return *set;
         }
         return ValidationSet ();
     }
void ripple::ValidationsImp::getValidationTypes (uint256 const & ledger, int & full, int & partial) inline private virtual
Implements ripple::Validations.
Definition at line 197 of file Validations.cpp.
References ripple::lsTRACE, and WriteLog.
     {
         full = partial = 0;
         ScopedLockType sl (mLock);
         VSpointer set = findSet (ledger);
         if (set)
         {
             BOOST_FOREACH (u160_val_pair & it, *set)
             {
                 if (it.second->isTrusted ())
                 {
                     if (it.second->isFull ())
                         ++full;
                     else
                         ++partial;
                 }
             }
         }
         WriteLog (lsTRACE, Validations) << "VC: " << ledger << "f:" << full << " p:" << partial;
     }
void ripple::ValidationsImp::sweep () inline private virtual
Implements ripple::Validations.
Definition at line 464 of file Validations.cpp.
References ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::sweep().
     {
         ScopedLockType sl (mLock);
         mValidations.sweep ();
     }
void ripple::ValidationsImp::tune (int size, int age) inline private virtual
Implements ripple::Validations.
Definition at line 144 of file Validations.cpp.
References ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::setTargetAge(), and ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::setTargetSize().
     {
         mValidations.setTargetSize (size);
         mValidations.setTargetAge (age);
     }
Member Data Documentation
ripple::unordered_map<uint160, SerializedValidation::pointer> ripple::ValidationsImp::mCurrentValidations private
Definition at line 38 of file Validations.cpp.
LockType ripple::ValidationsImp::mLock private
Definition at line 35 of file Validations.cpp.
std::vector<SerializedValidation::pointer> ripple::ValidationsImp::mStaleValidations private
Definition at line 39 of file Validations.cpp.
TaggedCache<uint256, ValidationSet> ripple::ValidationsImp::mValidations private
Definition at line 37 of file Validations.cpp.
bool ripple::ValidationsImp::mWriting private
Definition at line 41 of file Validations.cpp.
The documentation for this class was generated from the following file:
rippled/src/ripple_app/misc/Validations.cpp