rippled: beast::sqdb::session Class Reference
beast::sqdb::session Class Reference
A session for the embedded database.
#include <session.h>
Classes
class Sqlite3
Public Member Functions
session ()
~session ()
session (session const &deferredClone)
Error clone ()
Error open (String fileName, std::string options="timeout=infinite|mode=create|threads=multi")
void close ()
void begin ()
Error commit ()
void rollback ()
bool in_transaction ()
detail::once_type once (Error &error)
rowid last_insert_rowid ()
std::ostringstream & get_query_stream ()
void log_query (std::string const &query)
void set_got_data (bool bGotData)
bool got_data () const
sqlite3 * get_connection ()
Public Attributes
detail::prepare_type prepare
Private Member Functions
Error hard_exec (std::string const &query)
Private Attributes
SharedPtr< SharedSingleton
< Sqlite3 > > m_instance
bool m_bInTransaction
sqlite3 * m_connection
String m_fileName
std::string m_connectString
std::ostringstream m_query_stream
bool m_bGotData
Detailed Description
A session for the embedded database.
Definition at line 75 of file session.h.
Constructor & Destructor Documentation
beast::sqdb::session::session ()
Definition at line 85 of file session.cpp.
     : prepare (this)
     , m_instance (SharedSingleton <Sqlite3>::getInstance ())
     , m_bInTransaction (false)
     , m_connection (nullptr)
 {
 }
beast::sqdb::session::~session ()
Definition at line 105 of file session.cpp.
References close().
 {
     close();
 }
beast::sqdb::session::session (session const & deferredClone) explicit
Definition at line 93 of file session.cpp.
     : prepare (this)
     , m_instance (SharedSingleton <Sqlite3>::getInstance ())
     , m_bInTransaction (false)
     , m_connection (nullptr)
     , m_fileName (deferredClone.m_fileName)
     , m_connectString (deferredClone.m_connectString)
 {
     // shouldn't be needed since deferredClone did it
     //Sqlite::initialize();
 }
Member Function Documentation
void beast::sqdb::session::begin ()
Definition at line 296 of file session.cpp.
References bassert, hard_exec(), and m_bInTransaction.
Referenced by beast::sqdb::transaction::transaction().
 {
     bassert(!m_bInTransaction);
     m_bInTransaction = true;
     //Error error = hard_exec("BEGIN EXCLUSIVE");
     Error error = hard_exec("BEGIN");
     if (error)
         throw error;
 }
Error beast::sqdb::session::clone ()
Definition at line 110 of file session.cpp.
References m_connection, m_connectString, m_fileName, and open().
 {
     assert (! m_connection);
     return open(m_fileName, m_connectString);
 }
void beast::sqdb::session::close ()
Definition at line 285 of file session.cpp.
References beast::String::empty, m_connection, m_connectString, m_fileName, and sqlite3_close.
Referenced by open(), and ~session().
 {
     if (m_connection)
     {
         sqlite3_close(m_connection);
         m_connection = 0;
         m_fileName = String::empty;
         m_connectString = "";
     }
 }
Error beast::sqdb::session::commit ()
Definition at line 308 of file session.cpp.
References bassert, hard_exec(), and m_bInTransaction.
Referenced by beast::sqdb::transaction::commit().
 {
     bassert(m_bInTransaction);
     m_bInTransaction = false;
     return hard_exec("COMMIT");
 }
sqlite3* beast::sqdb::session::get_connection () inline
Definition at line 131 of file session.h.
References m_connection.
Referenced by beast::sqdb::detail::statement_imp::prepare().
     {
         return m_connection;
     }
std::ostringstream & beast::sqdb::session::get_query_stream ()
Definition at line 335 of file session.cpp.
References m_query_stream.
Referenced by beast::sqdb::detail::ref_counted_statement::final_action(), beast::sqdb::detail::ref_counted_prepare_info::get_query(), beast::sqdb::detail::ref_counted_statement_base::get_query_stream(), beast::sqdb::detail::once_temp_type::once_temp_type(), and beast::sqdb::detail::prepare_temp_type::prepare_temp_type().
 {
     return m_query_stream;
 }
bool beast::sqdb::session::got_data () const
Definition at line 350 of file session.cpp.
References m_bGotData.
Referenced by ripple::Validators::StoreSqdb::update(), and ripple::PeerFinder::StoreSqdb::update().
 {
     return m_bGotData;
 }
Error beast::sqdb::session::hard_exec (std::string const & query) private
Definition at line 355 of file session.cpp.
References m_connection, sqlite3_finalize, sqlite3_prepare_v2, sqlite3_step, SQLITE_DONE, SQLITE_OK, and beast::sqdb::detail::sqliteError().
Referenced by begin(), commit(), and rollback().
 {
     Error error;
     sqlite3_stmt* stmt;
     char const* tail = 0;
     int result = sqlite3_prepare_v2(
                      m_connection,
                      query.c_str(),
                      static_cast<int>(query.size()),
                      &stmt,
                      &tail);
     if (result == SQLITE_OK)
     {
         result = sqlite3_step(stmt);
         sqlite3_finalize(stmt);
     }
     if (result != SQLITE_DONE)
         error = detail::sqliteError(__FILE__, __LINE__, result);
     return error;
 }
bool beast::sqdb::session::in_transaction () inline
Definition at line 114 of file session.h.
References m_bInTransaction.
     {
         return m_bInTransaction;
     }
rowid beast::sqdb::session::last_insert_rowid ()
Definition at line 330 of file session.cpp.
References m_connection, and sqlite3_last_insert_rowid.
Referenced by beast::sqdb::detail::statement_imp::fetch().
 {
     return sqlite3_last_insert_rowid(m_connection);
 }
void beast::sqdb::session::log_query (std::string const & query)
Definition at line 340 of file session.cpp.
Referenced by beast::sqdb::detail::statement_imp::prepare().
 {
     // TODO
 }
detail::once_type beast::sqdb::session::once (Error & error)
Definition at line 325 of file session.cpp.
Referenced by ripple::Validators::StoreSqdb::init(), ripple::PeerFinder::StoreSqdb::init(), ripple::PeerFinder::StoreSqdb::save(), ripple::Validators::StoreSqdb::selectList(), ripple::Validators::StoreSqdb::update(), and ripple::PeerFinder::StoreSqdb::update().
 {
     return detail::once_type(this, error);
 }
Error beast::sqdb::session::open (String fileName, std::string options = "timeout=infinite|mode=create|threads=multi")
Open a database.
The database at the specified path is opened. The connection string is a set of "{key}={value}" pairs separated with the pipe symbol ('|'). Choices for key and value are:
timeout = (number) || "infinite"
mode    = "read" || "write" || "create"
cache   = "shared" || "private"
threads = "single" || "multi"
Definition at line 125 of file session.cpp.
References close(), m_connection, m_connectString, m_fileName, sqlite3_busy_timeout, sqlite3_open_v2, SQLITE_OPEN_CREATE, SQLITE_OPEN_FULLMUTEX, SQLITE_OPEN_NOMUTEX, SQLITE_OPEN_PRIVATECACHE, SQLITE_OPEN_READONLY, SQLITE_OPEN_READWRITE, SQLITE_OPEN_SHAREDCACHE, beast::sqdb::detail::sqliteError(), and beast::String::toUTF8().
Referenced by clone(), ripple::Validators::StoreSqdb::open(), and ripple::PeerFinder::StoreSqdb::open().
 {
     Error err;
     // can't open twice
     assert (! m_connection);
     int mode = 0;
     int flags = 0;
     int timeout = 0;
     std::stringstream ssconn(options);
     while (!err && !ssconn.eof() &&
            ssconn.str().find('=') != std::string::npos)
     {
         std::string key, val;
         std::getline(ssconn, key, '=');
         std::getline(ssconn, val, '|');
         if ("timeout" == key)
         {
             if ("infinite" == val)
             {
                 //timeout = -1;
                 timeout = 0x7fffffff;
             }
             else
             {
                 std::istringstream converter(val);
                 converter >> timeout;
                 if (timeout < 1)
                     timeout = 1;
             }
         }
         else if ("mode" == key)
         {
             if (!(mode & (SQLITE_OPEN_READONLY | SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE)))
             {
                 if ("read" == val)
                 {
                     mode = SQLITE_OPEN_READONLY;
                 }
                 else if ("write" == val)
                 {
                     mode = SQLITE_OPEN_READWRITE;
                 }
                 else if ("create" == val)
                 {
                     mode = SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE;
                 }
                 else
                 {
                     throw std::invalid_argument ("bad parameter");
                 }
             }
             else
             {
                 throw std::invalid_argument ("duplicate parameter");
             }
         }
         /* Most native SQLite libraries don't have these experimental features.
         */
 #if ! VF_USE_NATIVE_SQLITE
         else if ("cache" == key)
         {
             if (!(flags & (SQLITE_OPEN_SHAREDCACHE | SQLITE_OPEN_PRIVATECACHE)))
             {
                 if ("shared" == val)
                 {
                     flags |= SQLITE_OPEN_SHAREDCACHE;
                 }
                 else if ("private" == val)
                 {
                     flags |= SQLITE_OPEN_PRIVATECACHE;
                 }
                 else
                 {
                     throw std::invalid_argument ("bad parameter");
                 }
             }
             else
             {
                 throw std::invalid_argument ("duplicate parameter");
             }
         }
 #endif
         else if ("threads" == key)
         {
             if (!(flags & (SQLITE_OPEN_NOMUTEX | SQLITE_OPEN_FULLMUTEX)))
             {
                 if ("single" == val)
                 {
                     flags |= SQLITE_OPEN_FULLMUTEX;
                 }
                 else if ("multi" == val)
                 {
                     flags |= SQLITE_OPEN_NOMUTEX;
                 }
                 else
                 {
                     throw std::invalid_argument ("bad parameter");
                 }
             }
             else
             {
                 throw std::invalid_argument ("duplicate parameter");
             }
         }
         else
         {
             throw std::invalid_argument ("unknown parameter");
         }
     }
     if (!err)
     {
         if (! mode)
             mode = SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE;
         flags |= mode;
         err = detail::sqliteError(__FILE__, __LINE__,
                                   sqlite3_open_v2(fileName.toUTF8(), &m_connection, flags, 0));
         if (!err)
         {
             if (timeout > 0)
             {
                 err = detail::sqliteError(__FILE__, __LINE__,
                                           sqlite3_busy_timeout(m_connection, timeout));
             }
             /*
             else
             {
               err = detail::sqliteError (__FILE__, __LINE__,
                 sqlite3_busy_handler(m_connection, infiniteBusyHandler, 0));
             }
             */
         }
         if (!err)
         {
             m_fileName = fileName;
             m_connectString = options;
         }
         if (err)
         {
             close();
         }
     }
     return err;
 }
void beast::sqdb::session::rollback ()
Definition at line 315 of file session.cpp.
References bassert, hard_exec(), and m_bInTransaction.
Referenced by beast::sqdb::transaction::rollback().
 {
     bassert(m_bInTransaction);
     m_bInTransaction = false;
     Error error = hard_exec("ROLLBACK");
     if (error)
         throw error;
 }
void beast::sqdb::session::set_got_data (bool bGotData)
Definition at line 345 of file session.cpp.
References m_bGotData.
Referenced by beast::sqdb::detail::statement_imp::execute(), and beast::sqdb::detail::statement_imp::fetch().
 {
     m_bGotData = bGotData;
 }
Member Data Documentation
bool beast::sqdb::session::m_bGotData private
Definition at line 148 of file session.h.
Referenced by got_data(), and set_got_data().
bool beast::sqdb::session::m_bInTransaction private
Definition at line 142 of file session.h.
Referenced by begin(), commit(), in_transaction(), and rollback().
sqlite3* beast::sqdb::session::m_connection private
Definition at line 143 of file session.h.
Referenced by clone(), close(), get_connection(), hard_exec(), last_insert_rowid(), and open().
std::string beast::sqdb::session::m_connectString private
Definition at line 145 of file session.h.
Referenced by clone(), close(), and open().
String beast::sqdb::session::m_fileName private
Definition at line 144 of file session.h.
Referenced by clone(), close(), and open().
SharedPtr<SharedSingleton <Sqlite3> > beast::sqdb::session::m_instance private
Definition at line 140 of file session.h.
std::ostringstream beast::sqdb::session::m_query_stream private
Definition at line 147 of file session.h.
Referenced by get_query_stream().
detail::prepare_type beast::sqdb::session::prepare
Definition at line 120 of file session.h.
Referenced by ripple::Validators::StoreSqdb::insert(), ripple::PeerFinder::StoreSqdb::load(), ripple::PeerFinder::StoreSqdb::save(), ripple::Validators::StoreSqdb::select(), ripple::Validators::StoreSqdb::selectList(), ripple::Validators::StoreSqdb::update(), and ripple::PeerFinder::StoreSqdb::update().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_sqdb/api/session.h
rippled/src/beast/modules/beast_sqdb/source/session.cpp