rippled: beast::asio::TestPeerBasics Class Reference
beast::asio::TestPeerBasics Class Reference
#include <TestPeerBasics.h>
Classes
struct errc
struct Model
Static Public Member Functions
static
boost::asio::ssl::stream_base::handshake_type to_handshake_type (PeerRole const &role)
static
boost::system::error_category
const & test_category () noexcept
static boost::system::error_code make_error (errc::errc_t ev) noexcept
static boost::system::error_code make_error (errc::errc_t ev, boost::system::error_code &ec) noexcept
static bool success (boost::system::error_code const &ec, bool eofIsOkay=false) noexcept
static bool failure (boost::system::error_code const &ec, bool eofIsOkay=false) noexcept
static bool expected (bool condition, boost::system::error_code &ec) noexcept
static bool unexpected (bool condition, boost::system::error_code &ec) noexcept
static bool aborted (boost::system::error_code const &ec) noexcept
static void breakpoint (boost::system::error_code const &ec)
static void breakpoint (char const *const message)
Detailed Description
Common declarations for TestPeer.
See Also
TestPeer
Definition at line 30 of file TestPeerBasics.h.
Member Function Documentation
bool beast::asio::TestPeerBasics::aborted (boost::system::error_code const & ec) static noexcept
Returns true if the error condition indicates an aborted I/O.
Definition at line 140 of file TestPeerBasics.cpp.
Referenced by beast::asio::TestPeerLogicAsyncClient::on_connect_async(), beast::asio::TestPeerLogicAsyncServer::on_connect_async(), beast::asio::TestPeerLogicAsyncClient::on_handshake(), beast::asio::TestPeerLogicAsyncServer::on_handshake(), beast::asio::TestPeerLogicAsyncServer::on_read(), beast::asio::TestPeerLogicAsyncClient::on_read(), beast::asio::TestPeerLogicAsyncClient::on_read_final(), beast::asio::TestPeerLogicAsyncServer::on_shutdown(), beast::asio::TestPeerLogicAsyncClient::on_shutdown(), beast::asio::TestPeerLogicAsyncClient::on_write(), and beast::asio::TestPeerLogicAsyncServer::on_write().
 {
     return ec == boost::asio::error::operation_aborted;
 }
void beast::asio::TestPeerBasics::breakpoint (boost::system::error_code const & ec) static
Provides a place to set a breakpoint to catch a failed condition.
Definition at line 147 of file TestPeerBasics.cpp.
Referenced by expected(), and success().
 {
     // Set a breakpoint here to catch a failure
     std::string const& message = ec.message ();
     char const* const c_str = message.c_str ();
     breakpoint (c_str);
 }
void beast::asio::TestPeerBasics::breakpoint (char const *const message) static
Forces the variable to exist in the debugger.
Definition at line 156 of file TestPeerBasics.cpp.
 {
 }
bool beast::asio::TestPeerBasics::expected (bool condition, boost::system::error_code & ec) static noexcept
Set the error based on a failed condition and return the success.
Definition at line 121 of file TestPeerBasics.cpp.
References breakpoint(), make_error(), and beast::asio::TestPeerBasics::errc::unexpected.
Referenced by beast::asio::TestPeerType< Logic, Details >::on_deadline(), and unexpected().
 {
     if (condition)
     {
         ec = boost::system::error_code ();
     }
     else
     {
         make_error (errc::unexpected, ec);
         breakpoint (ec);
     }
     return condition;
 }
bool beast::asio::TestPeerBasics::failure (boost::system::error_code const & ec, bool eofIsOkay = false) static noexcept
Returns false if the error code indicates failure.
Definition at line 116 of file TestPeerBasics.cpp.
References success().
Referenced by beast::asio::TestPeerType< Logic, Details >::do_listen(), beast::asio::PeerTest::Result::failed(), beast::asio::TestPeerType< Logic, Details >::on_accept(), beast::asio::TestPeerLogicSyncClient::on_connect(), beast::asio::TestPeerLogicSyncServer::on_connect(), beast::asio::TestPeerLogicAsyncClient::on_connect_async(), beast::asio::TestPeerLogicAsyncServer::on_connect_async(), beast::asio::TestPeerLogicAsyncClient::on_handshake(), beast::asio::TestPeerLogicAsyncServer::on_handshake(), beast::asio::TestPeerLogicAsyncServer::on_read(), beast::asio::TestPeerLogicAsyncClient::on_read(), beast::asio::TestPeerLogicAsyncClient::on_write(), beast::asio::TestPeerLogicAsyncServer::on_write(), beast::asio::TestPeerType< Logic, Details >::run_async_server(), beast::asio::TestPeerType< Logic, Details >::run_sync_client(), and beast::asio::TestPeerType< Logic, Details >::run_sync_server().
 {
     return ! success (ec, eofIsOkay);
 }
boost::system::error_code beast::asio::TestPeerBasics::make_error (errc::errc_t ev) static noexcept
Creates a test error_code from the give code value.
Definition at line 96 of file TestPeerBasics.cpp.
References test_category().
Referenced by expected(), beast::asio::TestPeerType< Logic, Details >::join(), make_error(), beast::asio::PeerTest::run(), beast::asio::TestPeerType< Logic, Details >::run(), and beast::asio::PeerTest::Result::timedout().
 {
     return boost::system::error_code (ev, test_category ());
 }
boost::system::error_code beast::asio::TestPeerBasics::make_error (errc::errc_t ev, boost::system::error_code & ec) static noexcept
Sets the passed error_code to a test error and returns it.
Definition at line 101 of file TestPeerBasics.cpp.
References make_error().
 {
     return ec = make_error (ev);
 }
bool beast::asio::TestPeerBasics::success (boost::system::error_code const & ec, bool eofIsOkay = false) static noexcept
Returns true if the error code indicates success.
Definition at line 106 of file TestPeerBasics.cpp.
References breakpoint().
Referenced by failure(), beast::asio::TestPeerLogicAsyncClient::on_read_final(), beast::asio::TestPeerLogicAsyncServer::on_shutdown(), and beast::asio::TestPeerLogicAsyncClient::on_shutdown().
 {
     if (eofIsOkay && ec == boost::asio::error::eof)
         return true;
     if (! ec)
         return true;
     breakpoint (ec);
     return false;
 }
boost::system::error_category const & beast::asio::TestPeerBasics::test_category () static noexcept
Returns the category that represents TestPeer errors.
Definition at line 50 of file TestPeerBasics.cpp.
References beast::asio::TestPeerBasics::errc::exceptioned, name, beast::asio::TestPeerBasics::errc::none, beast::asio::TestPeerBasics::errc::skipped, beast::asio::TestPeerBasics::errc::timeout, and beast::asio::TestPeerBasics::errc::unexpected.
Referenced by make_error().
 {
     struct test_category_type : boost::system::error_category
     {
         char const* name () const noexcept
         {
             return "TestPeer";
         }
         std::string message (int ev) const
         {
             switch (ev)
             {
             case errc::none:          return "No error";
             case errc::timeout:       return "The timeout expired before the test could complete";
             case errc::unexpected:    return "An unexpected test result was encountered";
             case errc::exceptioned:   return "An unexpected exception was thrown";
             case errc::skipped:       return "The test was skipped because of previous errors";
             default:
                 break;
             };
             return "An unknown error";
         }
         boost::system::error_condition default_error_condition (int ev) const noexcept
         {
             return boost::system::error_condition (ev, *this);
         }
         bool equivalent (int ev, boost::system::error_condition const& condition) const noexcept
         {
             return default_error_condition (ev) == condition;
         }
         bool equivalent (boost::system::error_code const& code, int ev) const noexcept
         {
             return *this == code.category() && code.value() == ev;
         }
     };
     static test_category_type category;
     return category;
 }
boost::asio::ssl::stream_base::handshake_type beast::asio::TestPeerBasics::to_handshake_type (PeerRole const & role) static
Convert a PeerRole to boost::asio::ssl::stream_base_handshake_type
Definition at line 41 of file TestPeerBasics.cpp.
References beast::asio::PeerRole::client.
Referenced by beast::asio::TestPeerLogicSyncClient::on_connect(), and beast::asio::TestPeerLogicSyncServer::on_connect().
 {
     if (role == PeerRole::client)
         return boost::asio::ssl::stream_base::client;
     return boost::asio::ssl::stream_base::server;
 }
bool beast::asio::TestPeerBasics::unexpected (bool condition, boost::system::error_code & ec) static noexcept
Set the error based on a passed condition and return the success.
Definition at line 135 of file TestPeerBasics.cpp.
References expected().
Referenced by beast::asio::TestPeerType< Logic, Details >::finished(), beast::asio::TestPeerLogicSyncClient::on_connect(), beast::asio::TestPeerLogicSyncServer::on_connect(), beast::asio::TestPeerLogicAsyncServer::on_read(), beast::asio::TestPeerLogicAsyncClient::on_read(), beast::asio::TestPeerLogicAsyncClient::on_read_final(), beast::asio::TestPeerLogicAsyncClient::on_write(), and beast::asio::TestPeerLogicAsyncServer::on_write().
 {
     return ! expected (condition, ec);
 }
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_asio/tests/TestPeerBasics.h
rippled/src/beast/modules/beast_asio/tests/TestPeerBasics.cpp