rippled: beast::Journal::ScopedStream Class Reference
beast::Journal::ScopedStream Class Reference
#include <Journal.h>
Public Member Functions
ScopedStream (Stream const &stream)
ScopedStream (ScopedStream const &other)
template<typename T >
ScopedStream (Stream const &stream, T const &t)
ScopedStream (Stream const &stream, std::ostream &manip(std::ostream &))
~ScopedStream ()
bool active () const
std::ostringstream & ostream () const
std::ostream & operator<< (std::ostream &manip(std::ostream &)) const
template<typename T >
std::ostream & operator<< (T const &t) const
Private Member Functions
void init ()
ScopedStream & operator= (ScopedStream const &)
Private Attributes
Sink & m_sink
Severity const m_level
bool const m_active
std::ostringstream m_ostream
bool m_toOutputWindow
Detailed Description
Scoped ostream-based container for writing messages to a Journal.
Definition at line 100 of file Journal.h.
Constructor & Destructor Documentation
beast::Journal::ScopedStream::ScopedStream (Stream const & stream) explicit
Definition at line 106 of file Journal.cpp.
References init().
     : m_sink (stream.sink ())
     , m_level (stream.severity ())
     , m_active (stream.active ())
 {
     init ();
 }
beast::Journal::ScopedStream::ScopedStream (ScopedStream const & other)
Definition at line 114 of file Journal.cpp.
References init().
     : m_sink (other.m_sink)
     , m_level (other.m_level)
     , m_active (other.m_active)
 {
     init ();
 }
template<typename T > beast::Journal::ScopedStream::ScopedStream (Stream const & stream, T const & t) inline
Definition at line 107 of file Journal.h.
References active(), and m_ostream.
             : m_sink (stream.sink())
             , m_level (stream.severity())
             , m_active (stream.active ())
         {
             if (active ())
                 m_ostream << t;
         }
beast::Journal::ScopedStream::ScopedStream (Stream const & stream, std::ostream & manipstd::ostream &)
Definition at line 122 of file Journal.cpp.
References active(), init(), and m_ostream.
     : m_sink (stream.sink ())
     , m_level (stream.severity ())
     , m_active (stream.active ())
 {
     init ();
     if (active ())
         m_ostream << manip;
 }
beast::Journal::ScopedStream::~ScopedStream ()
Definition at line 133 of file Journal.cpp.
References beast::Journal::active(), beast::Journal::m_level, beast::Journal::m_sink, and beast::Journal::Sink::write().
 {
     if (active ())
     {
         std::string const& s (m_ostream.str());
         if (! s.empty ())
         {
             if (s == "\n")
                 m_sink.write (m_level, "");
             else
                 m_sink.write (m_level, s);
         }
     }
 }
Member Function Documentation
bool beast::Journal::ScopedStream::active () const inline
Definition at line 121 of file Journal.h.
References m_active.
Referenced by operator<<(), and ScopedStream().
             { return m_active; }
void beast::Journal::ScopedStream::init () private
Definition at line 148 of file Journal.cpp.
Referenced by ScopedStream().
 {
     // Modifiers applied from all ctors
     m_ostream
         << std::boolalpha
         << std::showbase
         //<< std::hex
         ;
 }
std::ostream & beast::Journal::ScopedStream::operator<< (std::ostream & manipstd::ostream &) const
Definition at line 159 of file Journal.cpp.
 {
     return m_ostream << manip;
 }
template<typename T > std::ostream& beast::Journal::ScopedStream::operator<< (T const & t) const inline
Definition at line 130 of file Journal.h.
References active(), and m_ostream.
         {
             if (active ())
                 m_ostream << t;
             return m_ostream;
         }
ScopedStream& beast::Journal::ScopedStream::operator= (ScopedStream const &) private
std::ostringstream & beast::Journal::ScopedStream::ostream () const
Definition at line 164 of file Journal.cpp.
 {
     return m_ostream;
 }
Member Data Documentation
bool const beast::Journal::ScopedStream::m_active private
Definition at line 144 of file Journal.h.
Referenced by active().
Severity const beast::Journal::ScopedStream::m_level private
Definition at line 143 of file Journal.h.
std::ostringstream beast::Journal::ScopedStream::m_ostream mutable private
Definition at line 145 of file Journal.h.
Referenced by operator<<(), and ScopedStream().
Sink& beast::Journal::ScopedStream::m_sink private
Definition at line 142 of file Journal.h.
bool beast::Journal::ScopedStream::m_toOutputWindow private
Definition at line 146 of file Journal.h.
The documentation for this class was generated from the following files:
rippled/src/beast/beast/utility/Journal.h
rippled/src/beast/beast/utility/impl/Journal.cpp