rippled: ripple::Validators::Validator Class Reference
ripple::Validators::Validator Class Reference
#include <Validator.h>
Classes
struct Ledger
Public Member Functions
Validator ()
void addRef ()
bool release ()
Count count () const
void receiveValidation (RippleLedgerHash const &ledgerHash)
void ledgerClosed (RippleLedgerHash const &ledgerHash)
Private Attributes
int m_refCount
typedef CycledMap
< RippleLedgerHash, Ledger,
Count, beast::hardened_hash
< RippleLedgerHash >
, RippleLedgerHash::key_equal > LedgerMap
LedgerMap m_ledgers
Detailed Description
Tracks statistics on a validator.
Definition at line 27 of file Validator.h.
Member Typedef Documentation
typedef CycledMap<RippleLedgerHash, Ledger, Count, beast::hardened_hash<RippleLedgerHash>, RippleLedgerHash::key_equal> ripple::Validators::Validator::LedgerMap private
Holds the state of all recent ledgers for this validator.
Definition at line 47 of file Validator.h.
Constructor & Destructor Documentation
ripple::Validators::Validator::Validator () inline
Definition at line 52 of file Validator.h.
         : m_refCount (0)
         , m_ledgers (ledgersPerValidator)
     {
     }
Member Function Documentation
void ripple::Validators::Validator::addRef () inline
Increment the number of references to this validator.
Definition at line 59 of file Validator.h.
References m_refCount.
         { ++m_refCount; }
Count ripple::Validators::Validator::count () const inline
Returns the composite performance statistics.
Definition at line 70 of file Validator.h.
References ripple::Validators::CycledMap< Key, T, Info, Hash, KeyEqual, Allocator >::back(), ripple::Validators::CycledMap< Key, T, Info, Hash, KeyEqual, Allocator >::front(), and m_ledgers.
Referenced by ledgerClosed(), ripple::Validators::ManagerImp::onWrite(), and receiveValidation().
         { return m_ledgers.front() + m_ledgers.back(); }
void ripple::Validators::Validator::ledgerClosed (RippleLedgerHash const & ledgerHash) inline
Called when a ledger is closed.
Definition at line 93 of file Validator.h.
References ripple::Validators::Count::closed, count(), ripple::Validators::Count::expected, ripple::Validators::CycledMap< Key, T, Info, Hash, KeyEqual, Allocator >::insert(), m_ledgers, and ripple::Validators::Count::received.
Referenced by ripple::Validators::Logic::ledgerClosed().
     {
         std::pair <Ledger&, Count&> result (m_ledgers.insert (
             std::make_pair (ledgerHash, Ledger())));
         Ledger& ledger (result.first);
         Count& count (result.second);
         ledger.closed = true;
         if (ledger.received)
         {
             --count.received;
             ++count.closed;
         }
         else
         {
             ++count.expected;
         }
     }
void ripple::Validators::Validator::receiveValidation (RippleLedgerHash const & ledgerHash) inline
Called upon receipt of a validation.
Definition at line 74 of file Validator.h.
References ripple::Validators::Count::closed, count(), ripple::Validators::Count::expected, ripple::Validators::CycledMap< Key, T, Info, Hash, KeyEqual, Allocator >::insert(), m_ledgers, and ripple::Validators::Count::received.
     {
         std::pair <Ledger&, Count&> result (m_ledgers.insert (
             std::make_pair (ledgerHash, Ledger())));
         Ledger& ledger (result.first);
         Count& count (result.second);
         ledger.received = true;
         if (ledger.closed)
         {
             --count.expected;
             ++count.closed;
         }
         else
         {
             ++count.received;
         }
     }
bool ripple::Validators::Validator::release () inline
Decrement the number of references to this validator. When the reference count reaches zero, the validator will be removed and no longer tracked.
Definition at line 66 of file Validator.h.
References m_refCount.
         { return (--m_refCount) == 0; }
Member Data Documentation
LedgerMap ripple::Validators::Validator::m_ledgers private
Definition at line 48 of file Validator.h.
Referenced by count(), ledgerClosed(), and receiveValidation().
int ripple::Validators::Validator::m_refCount private
Number of sources that reference this validator.
Definition at line 41 of file Validator.h.
Referenced by addRef(), and release().
The documentation for this class was generated from the following file:
rippled/src/ripple/validators/impl/Validator.h