rippled: beast::unit_test::suite_info Class Reference
beast::unit_test::suite_info Class Reference
#include <suite_info.h>
Public Member Functions
suite_info (char const *name, char const *module, char const *library, bool manual, run_type run)
char const * name () const
char const * module () const
char const * library () const
bool manual () const
std::string full_name () const
void run (runner &r) const
Private Types
typedef std::function< void(runner &)> run_type
Private Attributes
char const * m_name
char const * m_module
char const * m_library
bool m_manual
run_type m_run
Detailed Description
Associates a unit test type with metadata.
Definition at line 33 of file suite_info.h.
Member Typedef Documentation
typedef std::function<void (runner&)> beast::unit_test::suite_info::run_type private
Definition at line 36 of file suite_info.h.
Constructor & Destructor Documentation
beast::unit_test::suite_info::suite_info (char const * name, char const * module, char const * library, bool manual, run_type run) inline
Definition at line 45 of file suite_info.h.
         : m_name (name)
         , m_module (module)
         , m_library (library)
         , m_manual (manual)
         , m_run (std::move (run))
     {
     }
Member Function Documentation
std::string beast::unit_test::suite_info::full_name () const inline
Return the canonical suite name as a string.
Definition at line 86 of file suite_info.h.
References m_library, m_module, and m_name.
Referenced by beast::unit_test::recorder::on_suite_begin(), beast::unit_test::reporter::on_suite_begin(), and beast::unit_test::operator<().
     {
         return
             std::string (m_library) + "." +
             std::string (m_module) + "." +
             std::string (m_name);
     }
char const* beast::unit_test::suite_info::library () const inline
Definition at line 72 of file suite_info.h.
References m_library.
Referenced by beast::unit_test::selector::operator()().
     {
         return m_library;
     }
bool beast::unit_test::suite_info::manual () const inline
Returns true if this suite only runs manually.
Definition at line 79 of file suite_info.h.
References m_manual.
Referenced by beast::unit_test::selector::operator()(), and beast::unit_test::detail::print_test::prefix().
     {
         return m_manual;
     }
char const* beast::unit_test::suite_info::module () const inline
Definition at line 66 of file suite_info.h.
References m_module.
Referenced by beast::unit_test::selector::operator()().
     {
         return m_module;
     }
char const* beast::unit_test::suite_info::name () const inline
Definition at line 60 of file suite_info.h.
References m_name.
Referenced by beast::unit_test::selector::operator()().
     {
         return m_name;
     }
void beast::unit_test::suite_info::run (runner & r) const inline
Run a new instance of the associated test suite.
Definition at line 96 of file suite_info.h.
References m_run.
Referenced by beast::unit_test::runner::run().
     {
         m_run (r);
     }
Member Data Documentation
char const* beast::unit_test::suite_info::m_library private
Definition at line 40 of file suite_info.h.
Referenced by full_name(), and library().
bool beast::unit_test::suite_info::m_manual private
Definition at line 41 of file suite_info.h.
Referenced by manual().
char const* beast::unit_test::suite_info::m_module private
Definition at line 39 of file suite_info.h.
Referenced by full_name(), and module().
char const* beast::unit_test::suite_info::m_name private
Definition at line 38 of file suite_info.h.
Referenced by full_name(), and name().
run_type beast::unit_test::suite_info::m_run private
Definition at line 42 of file suite_info.h.
Referenced by run().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/unit_test/suite_info.h