rippled: rocksdb::MemTableList Class Reference
rocksdb::MemTableList Class Reference
#include <memtablelist.h>
Public Member Functions
MemTableList ()
~MemTableList ()
void RefAll ()
void UnrefAll ()
int size ()
bool IsFlushPending (int min_write_buffer_number_to_merge)
void PickMemtablesToFlush (std::vector< MemTable * > *mems)
Status InstallMemtableFlushResults (const std::vector< MemTable * > &m, VersionSet *vset, Status flushStatus, port::Mutex *mu, Logger *info_log, uint64_t file_number, std::set< uint64_t > &pending_outputs)
void Add (MemTable *m)
size_t ApproximateMemoryUsage ()
bool Get (const LookupKey &key, std::string *value, Status *s, std::deque< std::string > *operands, const Options &options)
void GetMemTables (std::vector< MemTable * > *list)
void FlushRequested ()
Public Attributes
port::AtomicPointer imm_flush_needed
Private Attributes
std::list< MemTable * > memlist_
int size_
int num_flush_not_started_
bool commit_in_progress_
bool flush_requested_
Detailed Description
Definition at line 30 of file memtablelist.h.
Constructor & Destructor Documentation
rocksdb::MemTableList::MemTableList () inline
Definition at line 33 of file memtablelist.h.
References imm_flush_needed, and rocksdb::port::AtomicPointer::Release_Store().
                  : size_(0), num_flush_not_started_(0),
     commit_in_progress_(false),
     flush_requested_(false) {
     imm_flush_needed.Release_Store(nullptr);
   }
rocksdb::MemTableList::~MemTableList () inline
Definition at line 38 of file memtablelist.h.
 {};
Member Function Documentation
void rocksdb::MemTableList::Add (MemTable * m)
Definition at line 175 of file memtablelist.cc.
References imm_flush_needed, rocksdb::MemTable::MarkImmutable(), memlist_, num_flush_not_started_, rocksdb::port::AtomicPointer::Release_Store(), and size_.
Referenced by rocksdb::DBImpl::MakeRoomForWrite().
{
   assert(size_ >= num_flush_not_started_);
   size_++;
   memlist_.push_front(m);
   m->MarkImmutable();
   num_flush_not_started_++;
   if (num_flush_not_started_ == 1) {
     imm_flush_needed.Release_Store((void *)1);
   }
 }
size_t rocksdb::MemTableList::ApproximateMemoryUsage ()
Definition at line 187 of file memtablelist.cc.
References memlist_, and size().
{
   size_t size = 0;
   for (auto &memtable : memlist_) {
     size += memtable->ApproximateMemoryUsage();
   }
   return size;
 }
void rocksdb::MemTableList::FlushRequested () inline
Definition at line 84 of file memtablelist.h.
References flush_requested_.
Referenced by rocksdb::DBImpl::MakeRoomForWrite().
 { flush_requested_ = true; }
bool rocksdb::MemTableList::Get (const LookupKey & key, std::string * value, Status * s, std::deque< std::string > * operands, const Options & options)
Definition at line 198 of file memtablelist.cc.
References memlist_.
Referenced by rocksdb::DBImpl::GetImpl(), and rocksdb::DBImpl::MultiGet().
{
   for (auto &memtable : memlist_) {
     if (memtable->Get(key, value, s, operands, options)) {
       return true;
     }
   }
   return false;
 }
void rocksdb::MemTableList::GetMemTables (std::vector< MemTable * > * list)
Definition at line 209 of file memtablelist.cc.
References memlist_.
Referenced by rocksdb::DBImpl::NewInternalIterator().
{
   for (auto &memtable : memlist_) {
     output->push_back(memtable);
   }
 }
Status rocksdb::MemTableList::InstallMemtableFlushResults (const std::vector< MemTable * > & m, VersionSet * vset, Status flushStatus, port::Mutex * mu, Logger * info_log, uint64_t file_number, std::set< uint64_t > & pending_outputs)
Definition at line 73 of file memtablelist.cc.
References rocksdb::port::Mutex::AssertHeld(), rocksdb::VersionEdit::Clear(), commit_in_progress_, rocksdb::MemTable::edit_, rocksdb::MemTable::file_number_, rocksdb::MemTable::flush_completed_, rocksdb::MemTable::flush_in_progress_, imm_flush_needed, rocksdb::Status::IOError(), rocksdb::Log(), rocksdb::VersionSet::LogAndApply(), memlist_, num_flush_not_started_, rocksdb::Status::ok(), rocksdb::port::AtomicPointer::Release_Store(), size_, and rocksdb::MemTable::Unref().
Referenced by rocksdb::DBImpl::FlushMemTableToOutputFile().
{
   mu->AssertHeld();
   // If the flush was not successful, then just reset state.
   // Maybe a suceeding attempt to flush will be successful.
   if (!flushStatus.ok()) {
     for (MemTable* m : mems) {
       assert(m->flush_in_progress_);
       assert(m->file_number_ == 0);
       m->flush_in_progress_ = false;
       m->flush_completed_ = false;
       m->edit_.Clear();
       num_flush_not_started_++;
       imm_flush_needed.Release_Store((void *)1);
       pending_outputs.erase(file_number);
     }
     return flushStatus;
   }
   // flush was sucessful
   for (size_t i = 0; i < mems.size(); ++i) {
     // All the edits are associated with the first memtable of this batch.
     assert(i == 0 || mems[i]->GetEdits()->NumEntries() == 0);
     mems[i]->flush_completed_ = true;
     mems[i]->file_number_ = file_number;
   }
   // if some other thread is already commiting, then return
   Status s;
   if (commit_in_progress_) {
     return s;
   }
   // Only a single thread can be executing this piece of code
   commit_in_progress_ = true;
   // scan all memtables from the earliest, and commit those
   // (in that order) that have finished flushing. Memetables
   // are always committed in the order that they were created.
   while (!memlist_.empty() && s.ok()) {
     MemTable* m = memlist_.back(); // get the last element
     if (!m->flush_completed_) {
       break;
     }
     Log(info_log,
         "Level-0 commit table #%lu started",
         (unsigned long)m->file_number_);
     // this can release and reacquire the mutex.
     s = vset->LogAndApply(&m->edit_, mu);
     // All the later memtables that have the same filenum
     // are part of the same batch. They can be committed now.
     uint64_t mem_id = 1;  // how many memtables has been flushed.
     do {
       if (s.ok()) { // commit new state
         Log(info_log,
             "Level-0 commit table #%lu: memtable #%lu done",
             (unsigned long)m->file_number_,
             (unsigned long)mem_id);
         memlist_.remove(m);
         assert(m->file_number_ > 0);
         // pending_outputs can be cleared only after the newly created file
         // has been written to a committed version so that other concurrently
         // executing compaction threads do not mistakenly assume that this
         // file is not live.
         pending_outputs.erase(m->file_number_);
         m->Unref();
         size_--;
       } else {
         //commit failed. setup state so that we can flush again.
         Log(info_log,
             "Level-0 commit table #%lu: memtable #%lu failed",
             (unsigned long)m->file_number_,
             (unsigned long)mem_id);
         m->flush_completed_ = false;
         m->flush_in_progress_ = false;
         m->edit_.Clear();
         num_flush_not_started_++;
         pending_outputs.erase(m->file_number_);
         m->file_number_ = 0;
         imm_flush_needed.Release_Store((void *)1);
         s = Status::IOError("Unable to commit flushed memtable");
       }
       ++mem_id;
     } while (!memlist_.empty() && (m = memlist_.back()) &&
              m->file_number_ == file_number);
   }
   commit_in_progress_ = false;
   return s;
 }
bool rocksdb::MemTableList::IsFlushPending (int min_write_buffer_number_to_merge)
Definition at line 46 of file memtablelist.cc.
References flush_requested_, imm_flush_needed, rocksdb::port::AtomicPointer::NoBarrier_Load(), and num_flush_not_started_.
Referenced by rocksdb::DBImpl::BackgroundCompaction(), rocksdb::DBImpl::BackgroundFlush(), rocksdb::DBImpl::DoCompactionWork(), rocksdb::DBImpl::FlushMemTableToOutputFile(), and rocksdb::DBImpl::MaybeScheduleFlushOrCompaction().
{
   if ((flush_requested_ && num_flush_not_started_ >= 1) ||
       (num_flush_not_started_ >= min_write_buffer_number_to_merge)) {
     assert(imm_flush_needed.NoBarrier_Load() != nullptr);
     return true;
   }
   return false;
 }
void rocksdb::MemTableList::PickMemtablesToFlush (std::vector< MemTable * > * mems)
Definition at line 56 of file memtablelist.cc.
References rocksdb::MemTable::flush_completed_, rocksdb::MemTable::flush_in_progress_, flush_requested_, imm_flush_needed, memlist_, num_flush_not_started_, and rocksdb::port::AtomicPointer::Release_Store().
Referenced by rocksdb::DBImpl::FlushMemTableToOutputFile().
{
   for (auto it = memlist_.rbegin(); it != memlist_.rend(); it++) {
     MemTable* m = *it;
     if (!m->flush_in_progress_) {
       assert(!m->flush_completed_);
       num_flush_not_started_--;
       if (num_flush_not_started_ == 0) {
         imm_flush_needed.Release_Store(nullptr);
       }
       m->flush_in_progress_ = true; // flushing will start very soon
       ret->push_back(m);
     }
   }
   flush_requested_ = false; // start-flush request is complete
 }
void rocksdb::MemTableList::RefAll ()
Definition at line 25 of file memtablelist.cc.
References memlist_.
Referenced by rocksdb::DBImpl::GetImpl(), and rocksdb::DBImpl::MultiGet().
{
   for (auto &memtable : memlist_) {
     memtable->Ref();
   }
 }
int rocksdb::MemTableList::size ()
Definition at line 39 of file memtablelist.cc.
References num_flush_not_started_, and size_.
Referenced by ApproximateMemoryUsage(), rocksdb::DBImpl::FlushMemTableToOutputFile(), rocksdb::DBImpl::GetProperty(), rocksdb::DBImpl::MakeRoomForWrite(), and rocksdb::DBImpl::WaitForFlushMemTable().
{
   assert(num_flush_not_started_ <= size_);
   return size_;
 }
void rocksdb::MemTableList::UnrefAll ()
Definition at line 32 of file memtablelist.cc.
References memlist_.
Referenced by rocksdb::DBImpl::GetImpl(), rocksdb::DBImpl::MultiGet(), and rocksdb::DBImpl::~DBImpl().
{
   for (auto &memtable : memlist_) {
     memtable->Unref();
   }
 }
Member Data Documentation
bool rocksdb::MemTableList::commit_in_progress_ private
Definition at line 98 of file memtablelist.h.
Referenced by InstallMemtableFlushResults().
bool rocksdb::MemTableList::flush_requested_ private
Definition at line 101 of file memtablelist.h.
Referenced by FlushRequested(), IsFlushPending(), and PickMemtablesToFlush().
port::AtomicPointer rocksdb::MemTableList::imm_flush_needed
Definition at line 38 of file memtablelist.h.
Referenced by Add(), rocksdb::DBImpl::DoCompactionWork(), InstallMemtableFlushResults(), IsFlushPending(), MemTableList(), and PickMemtablesToFlush().
std::list<MemTable*> rocksdb::MemTableList::memlist_ private
Definition at line 91 of file memtablelist.h.
Referenced by Add(), ApproximateMemoryUsage(), Get(), GetMemTables(), InstallMemtableFlushResults(), PickMemtablesToFlush(), RefAll(), and UnrefAll().
int rocksdb::MemTableList::num_flush_not_started_ private
Definition at line 95 of file memtablelist.h.
Referenced by Add(), InstallMemtableFlushResults(), IsFlushPending(), PickMemtablesToFlush(), and size().
int rocksdb::MemTableList::size_ private
Definition at line 92 of file memtablelist.h.
Referenced by Add(), InstallMemtableFlushResults(), and size().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/db/memtablelist.h
rippled/src/ripple/rocksdb/rocksdb/db/memtablelist.cc