rippled: beast::SharedSingleton< Object > Class Template Reference
beast::SharedSingleton< Object > Class Template Reference
#include <SharedSingleton.h>
Classes
class StaticData
Public Types
typedef SharedPtr
< SharedSingleton< Object > > Ptr
Static Public Member Functions
static Ptr get (SingletonLifetime::Lifetime lifetime=SingletonLifetime::persistAfterCreation)
static Ptr getInstance (SingletonLifetime::Lifetime lifetime=SingletonLifetime::persistAfterCreation)
Private Types
typedef SpinLock LockType
Private Member Functions
SharedSingleton (SingletonLifetime::Lifetime lifetime)
~SharedSingleton ()
void onExit ()
void destroy () const
Private Member Functions inherited from beast::SharedObject
void incReferenceCount () const noexcept
void decReferenceCount () const
int getReferenceCount () const noexcept
SharedObject ()
virtual ~SharedObject ()
void resetReferenceCount () noexcept
Static Private Member Functions
static StaticData & getStaticData ()
Private Attributes
SingletonLifetime::Lifetime m_lifetime
AtExitMemberHook< SharedSingleton > m_exitHook
Friends
class SharedPtr< SharedSingleton >
class AtExitMemberHook< SharedSingleton >
Detailed Description
template<class Object>
class beast::SharedSingleton< Object >
Wraps object to produce a reference counted singleton.
Thread-safe singleton which comes into existence on first use. Use this instead of creating objects with static storage duration. These singletons are automatically reference counted, so if you hold a pointer to it in every object that depends on it, the order of destruction of objects is assured to be correct.
Object Requirements: DefaultConstructible TriviallyDestructible (when lifetime == neverDestroyed) Destructible
Definition at line 81 of file SharedSingleton.h.
Member Typedef Documentation
template<class Object> typedef SpinLock beast::SharedSingleton< Object >::LockType private
Definition at line 167 of file SharedSingleton.h.
template<class Object> typedef SharedPtr<SharedSingleton <Object> > beast::SharedSingleton< Object >::Ptr
Definition at line 86 of file SharedSingleton.h.
Constructor & Destructor Documentation
template<class Object> beast::SharedSingleton< Object >::SharedSingleton (SingletonLifetime::Lifetime lifetime) inline explicit private
Definition at line 117 of file SharedSingleton.h.
         : m_lifetime (lifetime)
         , m_exitHook (this)
     {
         if (m_lifetime == SingletonLifetime::persistAfterCreation ||
             m_lifetime == SingletonLifetime::neverDestroyed)
             this->incReferenceCount ();
     }
template<class Object> beast::SharedSingleton< Object >::~SharedSingleton () inline private
Definition at line 126 of file SharedSingleton.h.
Referenced by beast::SharedSingleton< beast::sqdb::session::Sqlite3 >::destroy().
     {
     }
Member Function Documentation
template<class Object> void beast::SharedSingleton< Object >::destroy () const inline private virtual
Destroy the object. Derived classes can override this for different behaviors.
Reimplemented from beast::SharedObject.
Definition at line 136 of file SharedSingleton.h.
     {
         bool callDestructor;
         // Handle the condition where one thread is releasing the last
         // reference just as another thread is trying to acquire it.
         //
         {
             StaticData& staticData (getStaticData ());
             std::lock_guard <LockType> lock (staticData.mutex);
             if (this->getReferenceCount() != 0)
             {
                 callDestructor = false;
             }
             else
             {
                 callDestructor = true;
                 staticData.instance = nullptr;
                 staticData.destructorCalled = true;
             }
         }
         if (callDestructor)
         {
             bassert (m_lifetime != SingletonLifetime::neverDestroyed);
             this->~SharedSingleton();
         }
     }
template<class Object> static Ptr beast::SharedSingleton< Object >::get (SingletonLifetime::Lifetime lifetime = SingletonLifetime::persistAfterCreation) inline static
Definition at line 88 of file SharedSingleton.h.
     {
         StaticData& staticData (getStaticData ());
         SharedSingleton* instance = staticData.instance;
         if (instance == nullptr)
         {
             std::lock_guard <LockType> lock (staticData.mutex);
             instance = staticData.instance;
             if (instance == nullptr)
             {
                 bassert (lifetime == SingletonLifetime::createOnDemand || ! staticData.destructorCalled);
                 staticData.instance = &staticData.object;
                 new (staticData.instance) SharedSingleton (lifetime);
                 memoryBarrier();
                 instance = staticData.instance;
             }
         }
         return instance;
     }
template<class Object> static Ptr beast::SharedSingleton< Object >::getInstance (SingletonLifetime::Lifetime lifetime = SingletonLifetime::persistAfterCreation) inline static
Definition at line 110 of file SharedSingleton.h.
     {
         return get (lifetime);
     }
template<class Object> static StaticData& beast::SharedSingleton< Object >::getStaticData () inline static private
Definition at line 185 of file SharedSingleton.h.
Referenced by beast::SharedSingleton< beast::sqdb::session::Sqlite3 >::destroy(), and beast::SharedSingleton< beast::sqdb::session::Sqlite3 >::get().
     {
         static std::uint8_t storage [sizeof (StaticData)];
         return *(reinterpret_cast <StaticData*> (&storage [0]));
     }
template<class Object> void beast::SharedSingleton< Object >::onExit () inline private
Definition at line 130 of file SharedSingleton.h.
     {
         if (m_lifetime == SingletonLifetime::persistAfterCreation)
             this->decReferenceCount ();
     }
Friends And Related Function Documentation
template<class Object> friend class AtExitMemberHook< SharedSingleton > friend
Definition at line 192 of file SharedSingleton.h.
template<class Object> friend class SharedPtr< SharedSingleton > friend
Definition at line 191 of file SharedSingleton.h.
Member Data Documentation
template<class Object> AtExitMemberHook<SharedSingleton> beast::SharedSingleton< Object >::m_exitHook private
Definition at line 195 of file SharedSingleton.h.
template<class Object> SingletonLifetime::Lifetime beast::SharedSingleton< Object >::m_lifetime private
Definition at line 194 of file SharedSingleton.h.
Referenced by beast::SharedSingleton< beast::sqdb::session::Sqlite3 >::destroy(), beast::SharedSingleton< beast::sqdb::session::Sqlite3 >::onExit(), and beast::SharedSingleton< beast::sqdb::session::Sqlite3 >::SharedSingleton().
The documentation for this class was generated from the following file:
rippled/src/beast/modules/beast_core/memory/SharedSingleton.h