rippled: rocksdb::DBClientProxy Class Reference
rocksdb::DBClientProxy Class Reference
#include <DBClientProxy.h>
Public Member Functions
void connect (void)
bool get (const std::string &db, const std::string &key, std::string &value)
bool put (const std::string &db, const std::string &key, const std::string &value)
bool scan (const std::string &db, const std::string &start_key, const std::string &end_key, const std::string &limit, std::vector< std::pair< std::string, std::string > > &kvs)
bool create (const std::string &db)
DBClientProxy (const std::string &host, int port)
~DBClientProxy ()
Private Member Functions
void cleanUp (void)
void open (const std::string &db)
std::map< std::string,
Trocksdb::DBHandle >::iterator getHandle (const std::string &db)
Private Attributes
const std::string host_
const int port_
std::map< std::string,
Trocksdb::DBHandle > dbToHandle_
boost::shared_ptr
< Trocksdb::DBClient > dbClient_
Detailed Description
Definition at line 23 of file DBClientProxy.h.
Constructor & Destructor Documentation
rocksdb::DBClientProxy::DBClientProxy (const std::string & host, int port)
Definition at line 21 of file DBClientProxy.cpp.
                                                           :
   host_(host),
   port_(port),
   dbToHandle_(),
   dbClient_() {
 }
rocksdb::DBClientProxy::~DBClientProxy ()
Definition at line 28 of file DBClientProxy.cpp.
References cleanUp().
{
   cleanUp();
 }
Member Function Documentation
void rocksdb::DBClientProxy::cleanUp (void) private
Definition at line 49 of file DBClientProxy.cpp.
References dbClient_, and dbToHandle_.
Referenced by connect(), and ~DBClientProxy().
{
   if(dbClient_.get()) {
     for(map<string, DBHandle>::iterator itor = dbToHandle_.begin();
         itor != dbToHandle_.end();
         ++itor) {
       dbClient_->Close(itor->second, itor->first);
     }
     dbClient_.reset();
   }
   dbToHandle_.clear();
 }
void rocksdb::DBClientProxy::connect (void)
Definition at line 33 of file DBClientProxy.cpp.
References cleanUp(), dbClient_, host_, and port_.
Referenced by testDBClientProxy().
{
   cleanUp();
   printf("Connecting to %s:%d\n", host_.c_str(), port_);
   try {
     boost::shared_ptr<TSocket> socket(new TSocket(host_, port_));
     boost::shared_ptr<TTransport> transport(new TBufferedTransport(socket));
     boost::shared_ptr<TBinaryProtocol> protocol(new TBinaryProtocol(transport));
     dbClient_.reset(new DBClient(protocol));
     transport->open();
   } catch (const std::exception & e) {
     dbClient_.reset();
     throw;
   }
 }
bool rocksdb::DBClientProxy::create (const std::string & db)
Definition at line 88 of file DBClientProxy.cpp.
References db, dbClient_, and dbToHandle_.
Referenced by testDBClientProxy().
{
   if(!dbClient_.get()) {
     printf("please connect() first\n");
     return false;
   }
   printf("creating database : %s\n", db.c_str());
   DBOptions opt;
   opt.create_if_missing = true;
   opt.error_if_exists = true;
   DBHandle handle;
   try {
     dbClient_->Open(handle, db, opt);
   }catch (const LeveldbException & e) {
     printf("%s\n", e.message.c_str());
     printf("error code : %d\n", e.errorCode);
     if(kNotFound == e.errorCode) {
       printf("no such database : %s\n", db.c_str());
       return false;;
     } else {
       printf("Unknown error : %d\n", e.errorCode);
       return false;
     }
   }
   dbToHandle_[db] = handle;
   return true;
 }
bool rocksdb::DBClientProxy::get (const std::string & db, const std::string & key, std::string & value)
Definition at line 130 of file DBClientProxy.cpp.
References rocksdb::Slice::data(), dbClient_, dbToHandle_, getHandle(), and rocksdb::Slice::size().
Referenced by testDBClientProxy().
{
   if(!dbClient_.get()) {
     printf("please connect() first\n");
     return false;
   }
   map<string, DBHandle>::iterator itor = getHandle(db);
   if(dbToHandle_.end() == itor) {
     return false;
   }
   ResultItem ret;
   Slice k;
   k.data = key;
   k.size = key.size();
   // we use default values of options here
   ReadOptions opt;
   dbClient_->Get(ret,
                  itor->second,
                  k,
                  opt);
   if(kOk == ret.status) {
     value = ret.value.data;
     return true;
   } else if(kNotFound == ret.status) {
     printf("no such key : %s\n", key.c_str());
     return false;
   } else {
     printf("get data error : %d\n", ret.status);
     return false;
   }
 }
map< string, DBHandle >::iterator rocksdb::DBClientProxy::getHandle (const std::string & db) private
Definition at line 119 of file DBClientProxy.cpp.
References dbToHandle_, and open().
Referenced by get(), put(), and scan().
{
   map<string, DBHandle>::iterator itor = dbToHandle_.find(db);
   if(dbToHandle_.end() == itor) {
     open(db);
     itor = dbToHandle_.find(db);
   }
   return itor;
 }
void rocksdb::DBClientProxy::open (const std::string & db) private
Definition at line 61 of file DBClientProxy.cpp.
References db, dbClient_, and dbToHandle_.
Referenced by getHandle().
{
   if(!dbClient_.get()) {
     printf("please connect() first\n");
     return;
   }
   //  printf("opening database : %s\n", db.c_str());
   // we use default DBOptions here
   DBOptions opt;
   DBHandle handle;
   try {
     dbClient_->Open(handle, db, opt);
   } catch (const LeveldbException & e) {
     printf("%s\n", e.message.c_str());
     if(kIOError == e.errorCode) {
       printf("no such database : %s\n", db.c_str());
       return;
     }else {
       printf("Unknown error : %d\n", e.errorCode);
       return;
     }
   }
   dbToHandle_[db] = handle;
 }
bool rocksdb::DBClientProxy::put (const std::string & db, const std::string & key, const std::string & value)
Definition at line 167 of file DBClientProxy.cpp.
References dbClient_, dbToHandle_, getHandle(), rocksdb::WriteOptions::sync, and value.
Referenced by testDBClientProxy().
{
   if(!dbClient_.get()) {
     printf("please connect() first\n");
     return false;
   }
   map<string, DBHandle>::iterator itor = getHandle(db);
   if(dbToHandle_.end() == itor) {
     return false;
   }
   kv temp;
   temp.key.data = key;
   temp.key.size = key.size();
   temp.value.data = value;
   temp.value.size = value.size();
   WriteOptions opt;
   opt.sync = true;
   Code code;
   code = dbClient_->Put(itor->second,
                         temp,
                         opt);
   if(kOk == code) {
     //    printf("set value finished\n");
     return true;
   } else {
     printf("put data error : %d\n", code);
     return false;
   }
 }
bool rocksdb::DBClientProxy::scan (const std::string & db, const std::string & start_key, const std::string & end_key, const std::string & limit, std::vector< std::pair< std::string, std::string > > & kvs)
Definition at line 202 of file DBClientProxy.cpp.
References rocksdb::Slice::data(), dbClient_, dbToHandle_, getHandle(), and rocksdb::Slice::size().
Referenced by testDBClientProxy().
{
   if(!dbClient_.get()) {
     printf("please connect() first\n");
     return false;
   }
   int limitInt = -1;
   limitInt = atoi(limit.c_str());
   if(limitInt <= 0) {
     printf("Error while parse limit : %s\n", limit.c_str());
     return false;
   }
   if(start_key > end_key) {
     printf("empty range.\n");
     return false;
   }
   map<string, DBHandle>::iterator itor = getHandle(db);
   if(dbToHandle_.end() == itor) {
     return false;
   }
   ResultIterator ret;
   // we use the default values of options here
   ReadOptions opt;
   Slice k;
   k.data = start_key;
   k.size = start_key.size();
   dbClient_->NewIterator(ret,
                          itor->second,
                          opt,
                          seekToKey,
                          k);
   Iterator it;
   if(kOk == ret.status) {
     it = ret.iterator;
   } else {
     printf("get iterator error : %d\n", ret.status);
     return false;
   }
   int idx = 0;
   string ck = start_key;
   while(idx < limitInt && ck < end_key) {
     ResultPair retPair;
     dbClient_->GetNext(retPair, itor->second, it);
     if(kOk == retPair.status) {
       ++idx;
       ck = retPair.keyvalue.key.data;
       if (ck < end_key) {
         kvs.push_back(make_pair(retPair.keyvalue.key.data,
                                 retPair.keyvalue.value.data));
       }
     } else if(kEnd == retPair.status) {
       printf("not enough values\n");
       return true;
     } else {
       printf("GetNext() error : %d\n", retPair.status);
       return false;
     }
   }
   return true;
 }
Member Data Documentation
boost::shared_ptr<Trocksdb::DBClient> rocksdb::DBClientProxy::dbClient_ private
Definition at line 60 of file DBClientProxy.h.
Referenced by cleanUp(), connect(), create(), get(), open(), put(), and scan().
std::map<std::string, Trocksdb::DBHandle> rocksdb::DBClientProxy::dbToHandle_ private
Definition at line 59 of file DBClientProxy.h.
Referenced by cleanUp(), create(), get(), getHandle(), open(), put(), and scan().
const std::string rocksdb::DBClientProxy::host_ private
Definition at line 57 of file DBClientProxy.h.
Referenced by connect().
const int rocksdb::DBClientProxy::port_ private
Definition at line 58 of file DBClientProxy.h.
Referenced by connect().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/tools/shell/DBClientProxy.h
rippled/src/ripple/rocksdb/rocksdb/tools/shell/DBClientProxy.cpp