rippled: rocksdb::VersionSet::Builder Class Reference
rocksdb::VersionSet::Builder Class Reference
Classes
struct BySmallestKey
struct LevelState
Public Member Functions
Builder (VersionSet *vset, Version *base)
~Builder ()
void CheckConsistency (Version *v)
void CheckConsistencyForDeletes (VersionEdit *edit, unsigned int number, int level)
void Apply (VersionEdit *edit)
void SaveTo (Version *v)
void MaybeAddFile (Version *v, int level, FileMetaData *f)
Private Types
typedef std::set< FileMetaData
*, BySmallestKey > FileSet
Private Attributes
VersionSet * vset_
Version * base_
LevelState * levels_
Detailed Description
Definition at line 901 of file version_set.cc.
Member Typedef Documentation
typedef std::set<FileMetaData*, BySmallestKey> rocksdb::VersionSet::Builder::FileSet private
Definition at line 918 of file version_set.cc.
Constructor & Destructor Documentation
rocksdb::VersionSet::Builder::Builder (VersionSet * vset, Version * base) inline
Definition at line 930 of file version_set.cc.
References rocksdb::VersionSet::Builder::LevelState::added_files, base_, rocksdb::VersionSet::icmp_, rocksdb::VersionSet::Builder::BySmallestKey::internal_comparator, levels_, rocksdb::VersionSet::NumberLevels(), rocksdb::Version::Ref(), and vset_.
       : vset_(vset),
         base_(base) {
     base_->Ref();
     levels_ = new LevelState[vset_->NumberLevels()];
     BySmallestKey cmp;
     cmp.internal_comparator = &vset_->icmp_;
     for (int level = 0; level < vset_->NumberLevels(); level++) {
       levels_[level].added_files = new FileSet(cmp);
     }
   }
rocksdb::VersionSet::Builder::~Builder () inline
Definition at line 942 of file version_set.cc.
References rocksdb::VersionSet::Builder::LevelState::added_files, base_, ripple::f, levels_, rocksdb::VersionSet::NumberLevels(), rocksdb::FileMetaData::refs, rocksdb::Version::Unref(), and vset_.
              {
     for (int level = 0; level < vset_->NumberLevels(); level++) {
       const FileSet* added = levels_[level].added_files;
       std::vector<FileMetaData*> to_unref;
       to_unref.reserve(added->size());
       for (FileSet::const_iterator it = added->begin();
           it != added->end(); ++it) {
         to_unref.push_back(*it);
       }
       delete added;
       for (uint32_t i = 0; i < to_unref.size(); i++) {
         FileMetaData* f = to_unref[i];
         f->refs--;
         if (f->refs <= 0) {
           delete f;
         }
       }
     }
     delete[] levels_;
     base_->Unref();
   }
Member Function Documentation
void rocksdb::VersionSet::Builder::Apply (VersionEdit * edit) inline
Definition at line 1033 of file version_set.cc.
References rocksdb::VersionSet::Builder::LevelState::added_files, rocksdb::FileMetaData::allowed_seeks, base_, CheckConsistency(), CheckConsistencyForDeletes(), rocksdb::VersionSet::compact_pointer_, rocksdb::VersionEdit::compact_pointers_, rocksdb::VersionSet::Builder::LevelState::deleted_files, rocksdb::VersionEdit::deleted_files_, ripple::f, rocksdb::FileMetaData::file_size, levels_, rocksdb::VersionEdit::new_files_, rocksdb::FileMetaData::number, rocksdb::FileMetaData::refs, and vset_.
Referenced by rocksdb::VersionSet::DumpManifest(), rocksdb::VersionSet::LogAndApplyHelper(), and rocksdb::VersionSet::Recover().
{
     CheckConsistency(base_);
     // Update compaction pointers
     for (size_t i = 0; i < edit->compact_pointers_.size(); i++) {
       const int level = edit->compact_pointers_[i].first;
       vset_->compact_pointer_[level] =
           edit->compact_pointers_[i].second.Encode().ToString();
     }
     // Delete files
     const VersionEdit::DeletedFileSet& del = edit->deleted_files_;
     for (VersionEdit::DeletedFileSet::const_iterator iter = del.begin();
          iter != del.end();
          ++iter) {
       const int level = iter->first;
       const uint64_t number = iter->second;
       levels_[level].deleted_files.insert(number);
       CheckConsistencyForDeletes(edit, number, level);
     }
     // Add new files
     for (size_t i = 0; i < edit->new_files_.size(); i++) {
       const int level = edit->new_files_[i].first;
       FileMetaData* f = new FileMetaData(edit->new_files_[i].second);
       f->refs = 1;
       // We arrange to automatically compact this file after
       // a certain number of seeks.  Let's assume:
       //   (1) One seek costs 10ms
       //   (2) Writing or reading 1MB costs 10ms (100MB/s)
       //   (3) A compaction of 1MB does 25MB of IO:
       //         1MB read from this level
       //         10-12MB read from next level (boundaries may be misaligned)
       //         10-12MB written to next level
       // This implies that 25 seeks cost the same as the compaction
       // of 1MB of data.  I.e., one seek costs approximately the
       // same as the compaction of 40KB of data.  We are a little
       // conservative and allow approximately one seek for every 16KB
       // of data before triggering a compaction.
       f->allowed_seeks = (f->file_size / 16384);
       if (f->allowed_seeks < 100) f->allowed_seeks = 100;
       levels_[level].deleted_files.erase(f->number);
       levels_[level].added_files->insert(f);
     }
   }
void rocksdb::VersionSet::Builder::CheckConsistency (Version * v) inline
Definition at line 964 of file version_set.cc.
References rocksdb::InternalKeyComparator::Compare(), rocksdb::InternalKey::DebugString(), rocksdb::Version::files_, rocksdb::VersionSet::icmp_, rocksdb::VersionSet::NumberLevels(), and vset_.
Referenced by Apply(), and SaveTo().
{
 #ifndef NDEBUG
     for (int level = 0; level < vset_->NumberLevels(); level++) {
       // Make sure there is no overlap in levels > 0
       if (level > 0) {
         for (uint32_t i = 1; i < v->files_[level].size(); i++) {
           const InternalKey& prev_end = v->files_[level][i-1]->largest;
           const InternalKey& this_begin = v->files_[level][i]->smallest;
           if (vset_->icmp_.Compare(prev_end, this_begin) >= 0) {
             fprintf(stderr, "overlapping ranges in same level %s vs. %s\n",
                     prev_end.DebugString().c_str(),
                     this_begin.DebugString().c_str());
             abort();
           }
         }
       }
     }
 #endif
   }
void rocksdb::VersionSet::Builder::CheckConsistencyForDeletes (VersionEdit * edit, unsigned int number, int level) inline
Definition at line 984 of file version_set.cc.
References rocksdb::VersionSet::Builder::LevelState::added_files, base_, ripple::f, rocksdb::Version::files_, levels_, rocksdb::FileMetaData::number, and rocksdb::VersionEdit::number_levels_.
Referenced by Apply().
                {
 #ifndef NDEBUG
       // a file to be deleted better exist in the previous version
       bool found = false;
       for (int l = 0; !found && l < edit->number_levels_; l++) {
         const std::vector<FileMetaData*>& base_files = base_->files_[l];
         for (unsigned int i = 0; i < base_files.size(); i++) {
           FileMetaData* f = base_files[i];
           if (f->number == number) {
             found =  true;
             break;
           }
         }
       }
       // if the file did not exist in the previous version, then it
       // is possibly moved from lower level to higher level in current
       // version
       for (int l = level+1; !found && l < edit->number_levels_; l++) {
         const FileSet* added = levels_[l].added_files;
         for (FileSet::const_iterator added_iter = added->begin();
              added_iter != added->end(); ++added_iter) {
           FileMetaData* f = *added_iter;
           if (f->number == number) {
             found = true;
             break;
           }
         }
       }
       // maybe this file was added in a previous edit that was Applied
       if (!found) {
         const FileSet* added = levels_[level].added_files;
         for (FileSet::const_iterator added_iter = added->begin();
              added_iter != added->end(); ++added_iter) {
           FileMetaData* f = *added_iter;
           if (f->number == number) {
             found = true;
             break;
           }
         }
       }
       assert(found);
 #endif
   }
void rocksdb::VersionSet::Builder::MaybeAddFile (Version * v, int level, FileMetaData * f) inline
Definition at line 1117 of file version_set.cc.
References rocksdb::InternalKeyComparator::Compare(), rocksdb::Version::files_, rocksdb::VersionSet::icmp_, levels_, rocksdb::FileMetaData::number, rocksdb::FileMetaData::refs, rocksdb::FileMetaData::smallest, and vset_.
Referenced by SaveTo().
{
     if (levels_[level].deleted_files.count(f->number) > 0) {
       // File is deleted: do nothing
     } else {
       std::vector<FileMetaData*>* files = &v->files_[level];
       if (level > 0 && !files->empty()) {
         // Must not overlap
         assert(vset_->icmp_.Compare((*files)[files->size()-1]->largest,
                                     f->smallest) < 0);
       }
       f->refs++;
       files->push_back(f);
     }
   }
void rocksdb::VersionSet::Builder::SaveTo (Version * v) inline
Definition at line 1082 of file version_set.cc.
References rocksdb::VersionSet::Builder::LevelState::added_files, base_, CheckConsistency(), rocksdb::Version::files_, rocksdb::VersionSet::icmp_, rocksdb::VersionSet::Builder::BySmallestKey::internal_comparator, levels_, MaybeAddFile(), rocksdb::VersionSet::NumberLevels(), and vset_.
Referenced by rocksdb::VersionSet::DumpManifest(), rocksdb::VersionSet::LogAndApply(), and rocksdb::VersionSet::Recover().
{
     CheckConsistency(base_);
     CheckConsistency(v);
     BySmallestKey cmp;
     cmp.internal_comparator = &vset_->icmp_;
     for (int level = 0; level < vset_->NumberLevels(); level++) {
       // Merge the set of added files with the set of pre-existing files.
       // Drop any deleted files.  Store the result in *v.
       const std::vector<FileMetaData*>& base_files = base_->files_[level];
       std::vector<FileMetaData*>::const_iterator base_iter = base_files.begin();
       std::vector<FileMetaData*>::const_iterator base_end = base_files.end();
       const FileSet* added = levels_[level].added_files;
       v->files_[level].reserve(base_files.size() + added->size());
       for (FileSet::const_iterator added_iter = added->begin();
            added_iter != added->end();
            ++added_iter) {
         // Add all smaller files listed in base_
         for (std::vector<FileMetaData*>::const_iterator bpos
                  = std::upper_bound(base_iter, base_end, *added_iter, cmp);
              base_iter != bpos;
              ++base_iter) {
           MaybeAddFile(v, level, *base_iter);
         }
         MaybeAddFile(v, level, *added_iter);
       }
       // Add remaining base files
       for (; base_iter != base_end; ++base_iter) {
         MaybeAddFile(v, level, *base_iter);
       }
     }
     CheckConsistency(v);
   }
Member Data Documentation
Version* rocksdb::VersionSet::Builder::base_ private
Definition at line 925 of file version_set.cc.
Referenced by Apply(), Builder(), CheckConsistencyForDeletes(), SaveTo(), and ~Builder().
LevelState* rocksdb::VersionSet::Builder::levels_ private
Definition at line 926 of file version_set.cc.
Referenced by Apply(), Builder(), CheckConsistencyForDeletes(), MaybeAddFile(), SaveTo(), and ~Builder().
VersionSet* rocksdb::VersionSet::Builder::vset_ private
Definition at line 924 of file version_set.cc.
Referenced by Apply(), Builder(), CheckConsistency(), MaybeAddFile(), SaveTo(), and ~Builder().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/db/version_set.cc