rippled: beast::asio::TestPeerLogicAsyncClient Class Reference
beast::asio::TestPeerLogicAsyncClient Class Reference
#include <TestPeerLogicAsyncClient.h>
Public Member Functions
TestPeerLogicAsyncClient (abstract_socket &socket)
PeerRole get_role () const noexcept
Model get_model () const noexcept
void on_connect_async (error_code const &ec)
void on_handshake (error_code const &ec)
void on_write (error_code const &ec, std::size_t bytes_transferred)
void on_read (error_code const &ec, std::size_t bytes_transferred)
void on_read_final (error_code const &ec, std::size_t)
void on_shutdown (error_code const &ec)
Public Member Functions inherited from beast::asio::TestPeerLogic
TestPeerLogic (abstract_socket &socket)
error_code & error () noexcept
error_code const & error () const noexcept
error_code const & error (error_code const &ec) noexcept
abstract_socket & socket () noexcept
virtual void on_connect ()
virtual void finished ()
Private Attributes
boost::asio::streambuf m_buf
Additional Inherited Members
Public Types inherited from beast::asio::TestPeerLogic
typedef boost::system::error_code error_code
Static Public Member Functions inherited from beast::asio::TestPeerLogic
static void pure_virtual ()
Detailed Description
Definition at line 26 of file TestPeerLogicAsyncClient.h.
Constructor & Destructor Documentation
beast::asio::TestPeerLogicAsyncClient::TestPeerLogicAsyncClient (abstract_socket & socket) explicit
Definition at line 23 of file TestPeerLogicAsyncClient.cpp.
     : TestPeerLogic (socket)
 {
 }
Member Function Documentation
TestPeerBasics::Model beast::asio::TestPeerLogicAsyncClient::get_model () const virtual noexcept
Implements beast::asio::TestPeerLogic.
Definition at line 33 of file TestPeerLogicAsyncClient.cpp.
References beast::asio::TestPeerBasics::Model::async.
 {
     return Model::async;
 }
PeerRole beast::asio::TestPeerLogicAsyncClient::get_role () const virtual noexcept
Implements beast::asio::TestPeerLogic.
Definition at line 28 of file TestPeerLogicAsyncClient.cpp.
References beast::asio::PeerRole::client.
 {
     return PeerRole::client;
 }
void beast::asio::TestPeerLogicAsyncClient::on_connect_async (error_code const & ec) virtual
Reimplemented from beast::asio::TestPeerLogic.
Definition at line 38 of file TestPeerLogicAsyncClient.cpp.
References beast::asio::TestPeerBasics::aborted(), beast::asio::abstract_socket::async_handshake(), beast::asio::TestPeerLogic::error(), beast::asio::TestPeerBasics::failure(), beast::asio::TestPeerLogic::finished(), on_handshake(), and beast::asio::TestPeerLogic::socket().
 {
     if (aborted (ec) || failure (error (ec)))
         return finished ();
     if (socket ().needs_handshake ())
     {
         socket ().async_handshake (abstract_socket::client,
             boost::bind (&TestPeerLogicAsyncClient::on_handshake, this,
             boost::asio::placeholders::error));
     }
     else
     {
         on_handshake (ec);
     }
 }
void beast::asio::TestPeerLogicAsyncClient::on_handshake (error_code const & ec)
Definition at line 55 of file TestPeerLogicAsyncClient.cpp.
References beast::asio::TestPeerBasics::aborted(), beast::asio::TestPeerLogic::error(), beast::asio::TestPeerBasics::failure(), beast::asio::TestPeerLogic::finished(), on_write(), and beast::asio::TestPeerLogic::socket().
Referenced by on_connect_async().
 {
     if (aborted (ec) || failure (error (ec)))
         return finished ();
     boost::asio::async_write (socket (), boost::asio::buffer ("hello", 5),
         boost::bind (&TestPeerLogicAsyncClient::on_write, this,
         boost::asio::placeholders::error, boost::asio::placeholders::bytes_transferred));
 }
void beast::asio::TestPeerLogicAsyncClient::on_read (error_code const & ec, std::size_t bytes_transferred)
Definition at line 78 of file TestPeerLogicAsyncClient.cpp.
References beast::asio::TestPeerBasics::aborted(), beast::asio::TestPeerLogic::error(), beast::asio::TestPeerBasics::failure(), beast::asio::TestPeerLogic::finished(), m_buf, on_read_final(), beast::asio::TestPeerLogic::socket(), and beast::asio::TestPeerBasics::unexpected().
Referenced by on_write().
 {
     if (aborted (ec) || failure (error (ec)))
         return finished ();
     if (unexpected (bytes_transferred == 7, error ()))
         return finished ();
     // should check the data here?
     m_buf.consume (bytes_transferred);
     // Fire up a 1 byte read, to wait for the server to
     // shut down its end of the connection.
     boost::asio::async_read (socket (), m_buf.prepare (1),
         boost::bind (&TestPeerLogicAsyncClient::on_read_final, this,
         boost::asio::placeholders::error, boost::asio::placeholders::bytes_transferred));
 }
void beast::asio::TestPeerLogicAsyncClient::on_read_final (error_code const & ec, std::size_t)
Definition at line 96 of file TestPeerLogicAsyncClient.cpp.
References beast::asio::TestPeerBasics::aborted(), beast::asio::abstract_socket::async_shutdown(), beast::asio::TestPeerLogic::error(), beast::asio::TestPeerLogic::finished(), on_shutdown(), beast::asio::TestPeerLogic::socket(), beast::asio::TestPeerBasics::success(), and beast::asio::TestPeerBasics::unexpected().
Referenced by on_read().
 {
     if (aborted (ec))
         return finished ();
     // An eof is the normal case. The server should have closed shop.
     //
     if (ec == boost::asio::error::eof)
     {
         if (socket ().needs_handshake ())
         {
             socket ().async_shutdown (boost::bind (&TestPeerLogicAsyncClient::on_shutdown, this,
                 boost::asio::placeholders::error));
         }
         else
         {
             // on_shutdown will call finished ()
             error_code ec;
             on_shutdown (socket ().shutdown (abstract_socket::shutdown_send, ec));
         }
     }
     else
     {
         // If we don't get eof, then there should be some other
         // error in there. We don't expect the server to send more bytes!
         //
         // This statement will do the following:
         //
         // error (ec)     save ec into our error state
         // success ()     return true if ec represents success
         // unexpected ()  changes error() to 'unexpected' result if
         //                success() returned true
         //
         unexpected (success (error (ec)), error ());
         return finished ();
     }
 }
void beast::asio::TestPeerLogicAsyncClient::on_shutdown (error_code const & ec)
Definition at line 135 of file TestPeerLogicAsyncClient.cpp.
References beast::asio::TestPeerBasics::aborted(), beast::asio::TestPeerLogic::error(), beast::asio::TestPeerLogic::finished(), beast::asio::abstract_socket::shutdown(), beast::asio::TestPeerLogic::socket(), and beast::asio::TestPeerBasics::success().
Referenced by on_read_final().
 {
     if (! aborted (ec))
     {
         if (success (error (ec), true))
         {
             if (socket ().needs_handshake ())
             {
                 socket ().shutdown (abstract_socket::shutdown_send, error ());
             }
             if (! error ())
             {
                 if (success (socket ().close (error ())))
                 {
                     // doing nothing here is intended,
                     // as the calls to success() may set error()
                 }
             }
         }
     }
     finished ();
 }
void beast::asio::TestPeerLogicAsyncClient::on_write (error_code const & ec, std::size_t bytes_transferred)
Definition at line 65 of file TestPeerLogicAsyncClient.cpp.
References beast::asio::TestPeerBasics::aborted(), beast::asio::TestPeerLogic::error(), beast::asio::TestPeerBasics::failure(), beast::asio::TestPeerLogic::finished(), m_buf, on_read(), beast::asio::TestPeerLogic::socket(), and beast::asio::TestPeerBasics::unexpected().
Referenced by on_handshake().
 {
     if (aborted (ec) || failure (error (ec)))
         return finished ();
     if (unexpected (bytes_transferred == 5, error ()))
         return finished ();
     boost::asio::async_read_until (socket (), m_buf, std::string ("goodbye"),
         boost::bind (&TestPeerLogicAsyncClient::on_read, this,
         boost::asio::placeholders::error, boost::asio::placeholders::bytes_transferred));
 }
Member Data Documentation
boost::asio::streambuf beast::asio::TestPeerLogicAsyncClient::m_buf private
Definition at line 39 of file TestPeerLogicAsyncClient.h.
Referenced by on_read(), and on_write().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_asio/tests/TestPeerLogicAsyncClient.h
rippled/src/beast/modules/beast_asio/tests/TestPeerLogicAsyncClient.cpp