rippled: rocksdb::HistogramImpl Class Reference
rocksdb::HistogramImpl Class Reference
#include <histogram.h>
Public Member Functions
HistogramImpl ()
virtual ~HistogramImpl ()
virtual void Clear ()
virtual void Add (uint64_t value)
void Merge (const HistogramImpl &other)
virtual std::string ToString () const
virtual double Median () const
virtual double Percentile (double p) const
virtual double Average () const
virtual double StandardDeviation () const
virtual void Data (HistogramData *const data) const
Private Attributes
double min_
double max_
double num_
double sum_
double sum_squares_
std::vector< uint64_t > buckets_
Detailed Description
Definition at line 53 of file histogram.h.
Constructor & Destructor Documentation
rocksdb::HistogramImpl::HistogramImpl ()
Definition at line 66 of file histogram.cc.
                              :
   min_(bucketMapper.LastValue()),
   max_(0),
   num_(0),
   sum_(0),
   sum_squares_(0),
   buckets_(std::vector<uint64_t>(bucketMapper.BucketCount(), 0)) {}
virtual rocksdb::HistogramImpl::~HistogramImpl () inline virtual
Definition at line 56 of file histogram.h.
 {}
Member Function Documentation
void rocksdb::HistogramImpl::Add (uint64_t value) virtual
Definition at line 83 of file histogram.cc.
References buckets_, max_, min_, num_, sum_, sum_squares_, and value.
Referenced by rocksdb::Stats::FinishedSingleOp(), rocksdb::ProfileKeyComparison(), rocksdb::TableReaderBenchmark(), and rocksdb::TEST().
{
   const size_t index = bucketMapper.IndexForValue(value);
   buckets_[index] += 1;
   if (min_ > value) min_ = value;
   if (max_ < value) max_ = value;
   num_++;
   sum_ += value;
   sum_squares_ += (value * value);
 }
double rocksdb::HistogramImpl::Average () const virtual
Definition at line 133 of file histogram.cc.
References num_, and sum_.
Referenced by Data(), rocksdb::TEST(), and ToString().
{
   if (num_ == 0.0) return 0;
   return sum_ / num_;
 }
void rocksdb::HistogramImpl::Clear () virtual
Definition at line 74 of file histogram.cc.
References buckets_, max_, min_, num_, sum_, and sum_squares_.
Referenced by rocksdb::Stats::Start(), and rocksdb::TEST().
{
   min_ = bucketMapper.LastValue();
   max_ = 0;
   num_ = 0;
   sum_ = 0;
   sum_squares_ = 0;
   buckets_.resize(bucketMapper.BucketCount(), 0);
 }
void rocksdb::HistogramImpl::Data (HistogramData *const data) const virtual
Definition at line 185 of file histogram.cc.
References Average(), rocksdb::HistogramData::average, Median(), rocksdb::HistogramData::median, Percentile(), rocksdb::HistogramData::percentile95, rocksdb::HistogramData::percentile99, rocksdb::HistogramData::standard_deviation, and StandardDeviation().
{
   assert(data);
   data->median = Median();
   data->percentile95 = Percentile(95);
   data->percentile99 = Percentile(99);
   data->average = Average();
   data->standard_deviation = StandardDeviation();
 }
double rocksdb::HistogramImpl::Median () const virtual
Definition at line 104 of file histogram.cc.
References Percentile().
Referenced by Data(), rocksdb::TEST(), and ToString().
{
   return Percentile(50.0);
 }
void rocksdb::HistogramImpl::Merge (const HistogramImpl & other)
Definition at line 93 of file histogram.cc.
References buckets_, max_, min_, num_, sum_, and sum_squares_.
Referenced by rocksdb::Stats::Merge().
{
   if (other.min_ < min_) min_ = other.min_;
   if (other.max_ > max_) max_ = other.max_;
   num_ += other.num_;
   sum_ += other.sum_;
   sum_squares_ += other.sum_squares_;
   for (unsigned int b = 0; b < bucketMapper.BucketCount(); b++) {
     buckets_[b] += other.buckets_[b];
   }
 }
double rocksdb::HistogramImpl::Percentile (double p) const virtual
Definition at line 108 of file histogram.cc.
References buckets_, max_, min_, and num_.
Referenced by Data(), Median(), rocksdb::TEST(), and ToString().
{
   double threshold = num_ * (p / 100.0);
   double sum = 0;
   for (unsigned int b = 0; b < bucketMapper.BucketCount(); b++) {
     sum += buckets_[b];
     if (sum >= threshold) {
       // Scale linearly within this bucket
       double left_point = (b == 0) ? 0 : bucketMapper.BucketLimit(b-1);
       double right_point = bucketMapper.BucketLimit(b);
       double left_sum = sum - buckets_[b];
       double right_sum = sum;
       double pos = 0;
       double right_left_diff = right_sum - left_sum;
       if (right_left_diff != 0) {
        pos = (threshold - left_sum) / (right_sum - left_sum);
       }
       double r = left_point + (right_point - left_point) * pos;
       if (r < min_) r = min_;
       if (r > max_) r = max_;
       return r;
     }
   }
   return max_;
 }
double rocksdb::HistogramImpl::StandardDeviation () const virtual
Definition at line 138 of file histogram.cc.
References num_, sum_, and sum_squares_.
Referenced by Data(), and ToString().
{
   if (num_ == 0.0) return 0;
   double variance = (sum_squares_ * num_ - sum_ * sum_) / (num_ * num_);
   return sqrt(variance);
 }
std::string rocksdb::HistogramImpl::ToString () const virtual
Definition at line 144 of file histogram.cc.
References Average(), buckets_, max_, Median(), min_, num_, Percentile(), and StandardDeviation().
Referenced by rocksdb::ProfileKeyComparison(), rocksdb::Stats::Report(), rocksdb::TableReaderBenchmark(), and rocksdb::TEST().
{
   std::string r;
   char buf[200];
   snprintf(buf, sizeof(buf),
            "Count: %.0f  Average: %.4f  StdDev: %.2f\n",
            num_, Average(), StandardDeviation());
   r.append(buf);
   snprintf(buf, sizeof(buf),
            "Min: %.4f  Median: %.4f  Max: %.4f\n",
            (num_ == 0.0 ? 0.0 : min_), Median(), max_);
   r.append(buf);
   snprintf(buf, sizeof(buf),
            "Percentiles: "
            "P50: %.2f P75: %.2f P99: %.2f P99.9: %.2f P99.99: %.2f\n",
            Percentile(50), Percentile(75), Percentile(99), Percentile(99.9),
            Percentile(99.99));
   r.append(buf);
   r.append("------------------------------------------------------\n");
   const double mult = 100.0 / num_;
   double sum = 0;
   for (unsigned int b = 0; b < bucketMapper.BucketCount(); b++) {
     if (buckets_[b] <= 0.0) continue;
     sum += buckets_[b];
     snprintf(buf, sizeof(buf),
              "[ %7lu, %7lu ) %8lu %7.3f%% %7.3f%% ",
              // left
              (unsigned long)((b == 0) ? 0 : bucketMapper.BucketLimit(b-1)),
              (unsigned long)bucketMapper.BucketLimit(b), // right
              (unsigned long)buckets_[b],                 // count
              (mult * buckets_[b]),        // percentage
              (mult * sum));               // cumulative percentage
     r.append(buf);
     // Add hash marks based on percentage; 20 marks for 100%.
     int marks = static_cast<int>(20*(buckets_[b] / num_) + 0.5);
     r.append(marks, '#');
     r.push_back('\n');
   }
   return r;
 }
Member Data Documentation
std::vector<uint64_t> rocksdb::HistogramImpl::buckets_ private
Definition at line 75 of file histogram.h.
Referenced by Add(), Clear(), Merge(), Percentile(), and ToString().
double rocksdb::HistogramImpl::max_ private
Definition at line 71 of file histogram.h.
Referenced by Add(), Clear(), Merge(), Percentile(), and ToString().
double rocksdb::HistogramImpl::min_ private
Definition at line 70 of file histogram.h.
Referenced by Add(), Clear(), Merge(), Percentile(), and ToString().
double rocksdb::HistogramImpl::num_ private
Definition at line 72 of file histogram.h.
Referenced by Add(), Average(), Clear(), Merge(), Percentile(), StandardDeviation(), and ToString().
double rocksdb::HistogramImpl::sum_ private
Definition at line 73 of file histogram.h.
Referenced by Add(), Average(), Clear(), Merge(), and StandardDeviation().
double rocksdb::HistogramImpl::sum_squares_ private
Definition at line 74 of file histogram.h.
Referenced by Add(), Clear(), Merge(), and StandardDeviation().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/util/histogram.h
rippled/src/ripple/rocksdb/rocksdb/util/histogram.cc