rippled: beast::unit_test::detail::print_test Class Reference
beast::unit_test::detail::print_test Class Reference
Public Member Functions
void print (suite_list &c)
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Static Public Member Functions
static std::string prefix (suite_info const &s)
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
A suite that prints the list of globally defined suites.
Definition at line 32 of file define_print.cpp.
Member Function Documentation
static std::string beast::unit_test::detail::print_test::prefix (suite_info const & s) inline static
Definition at line 37 of file define_print.cpp.
References beast::unit_test::suite_info::manual().
Referenced by print().
     {
         if (s.manual())
             return "|M| ";
         return "    ";
     }
void beast::unit_test::detail::print_test::print (suite_list & c) inline
Definition at line 45 of file define_print.cpp.
References beast::unit_test::suite::log, and prefix().
Referenced by run().
     {
         std::size_t manual (0);
         for (auto const& s : c)
         {
             log <<
                 prefix (s) <<
                 s.full_name();
             if (s.manual())
                 ++manual;
         }
         log <<
             amount (c.size(), "suite") << " total, " <<
             amount (manual, "manual suite")
             ;
     }
void beast::unit_test::detail::print_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 63 of file define_print.cpp.
References beast::unit_test::detail::global_suites(), beast::unit_test::suite::log, beast::unit_test::suite::pass(), and print().
     {
         log << "------------------------------------------";
         print (global_suites());
         log << "------------------------------------------";
         pass();
     }
The documentation for this class was generated from the following file:
rippled/src/beast/beast/unit_test/define_print.cpp