rippled: beast::detail::TrackedScopedLock< Mutex > Class Template Reference
beast::detail::TrackedScopedLock< Mutex > Class Template Reference
#include <ScopedLock.h>
Public Member Functions
TrackedScopedLock (Mutex const &mutex, char const *fileName, int lineNumber) noexcept
~TrackedScopedLock () noexcept
void lock (char const *fileName, int lineNumber) noexcept
void unlock () noexcept
Private Attributes
Mutex const & m_mutex
int m_lock_count
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
template<typename Mutex>
class beast::detail::TrackedScopedLock< Mutex >
Definition at line 32 of file ScopedLock.h.
Constructor & Destructor Documentation
template<typename Mutex > beast::detail::TrackedScopedLock< Mutex >::TrackedScopedLock (Mutex const & mutex, char const * fileName, int lineNumber) inline explicit noexcept
Definition at line 35 of file ScopedLock.h.
References beast::detail::TrackedScopedLock< Mutex >::lock().
         : m_mutex (mutex)
         , m_lock_count (0)
     {
         lock (fileName, lineNumber);
     }
template<typename Mutex > beast::detail::TrackedScopedLock< Mutex >::~TrackedScopedLock () inline noexcept
Definition at line 43 of file ScopedLock.h.
References beast::detail::TrackedScopedLock< Mutex >::m_lock_count, and beast::detail::TrackedScopedLock< Mutex >::unlock().
     {
         if (m_lock_count > 0)
             unlock ();
     }
Member Function Documentation
template<typename Mutex > void beast::detail::TrackedScopedLock< Mutex >::lock (char const * fileName, int lineNumber) inline noexcept
Definition at line 49 of file ScopedLock.h.
References beast::detail::TrackedScopedLock< Mutex >::m_lock_count, and beast::detail::TrackedScopedLock< Mutex >::m_mutex.
Referenced by beast::detail::TrackedScopedLock< Mutex >::TrackedScopedLock().
     {
         ++m_lock_count;
         m_mutex.lock (fileName, lineNumber);
     }
template<typename Mutex > void beast::detail::TrackedScopedLock< Mutex >::unlock () inline noexcept
Definition at line 55 of file ScopedLock.h.
References beast::detail::TrackedScopedLock< Mutex >::m_lock_count, and beast::detail::TrackedScopedLock< Mutex >::m_mutex.
Referenced by beast::detail::TrackedScopedLock< Mutex >::~TrackedScopedLock().
     {
         m_mutex.unlock ();
         --m_lock_count;
     }
Member Data Documentation
template<typename Mutex > int beast::detail::TrackedScopedLock< Mutex >::m_lock_count private
Definition at line 63 of file ScopedLock.h.
Referenced by beast::detail::TrackedScopedLock< Mutex >::lock(), beast::detail::TrackedScopedLock< Mutex >::unlock(), and beast::detail::TrackedScopedLock< Mutex >::~TrackedScopedLock().
template<typename Mutex > Mutex const& beast::detail::TrackedScopedLock< Mutex >::m_mutex private
Definition at line 62 of file ScopedLock.h.
Referenced by beast::detail::TrackedScopedLock< Mutex >::lock(), and beast::detail::TrackedScopedLock< Mutex >::unlock().
The documentation for this class was generated from the following file:
rippled/src/beast/modules/beast_core/thread/detail/ScopedLock.h