rippled: Json::Reader Class Reference
Json::Reader Class Reference
Unserialize a JSON document into a Value.
#include <json_reader.h>
Classes
class ErrorInfo
class Token
Public Types
typedef char Char
typedef const Char * Location
Public Member Functions
Reader ()
Constructs a Reader allowing all features for parsing.
Reader (const Features &features)
Constructs a Reader allowing the specified feature set for parsing.
bool parse (const std::string &document, Value &root, bool collectComments=true)
Read a Value from a JSON document.
bool parse (const char *beginDoc, const char *endDoc, Value &root, bool collectComments=true)
Read a Value from a JSON document.
bool parse (std::istream &is, Value &root, bool collectComments=true)
Parse from input stream.
std::string getFormatedErrorMessages () const
Returns a user friendly string that list errors in the parsed document.
Private Types
enum TokenType {
tokenEndOfStream = 0, tokenObjectBegin, tokenObjectEnd, tokenArrayBegin,
tokenArrayEnd, tokenString, tokenNumber, tokenTrue,
tokenFalse, tokenNull, tokenArraySeparator, tokenMemberSeparator,
tokenComment, tokenError
}
typedef std::deque< ErrorInfo > Errors
typedef std::stack< Value * > Nodes
Private Member Functions
bool expectToken (TokenType type, Token &token, const char *message)
bool readToken (Token &token)
void skipSpaces ()
bool match (Location pattern, int patternLength)
bool readComment ()
bool readCStyleComment ()
bool readCppStyleComment ()
bool readString ()
void readNumber ()
bool readValue ()
bool readObject (Token &token)
bool readArray (Token &token)
bool decodeNumber (Token &token)
bool decodeString (Token &token)
bool decodeString (Token &token, std::string &decoded)
bool decodeDouble (Token &token)
bool decodeUnicodeCodePoint (Token &token, Location &current, Location end, unsigned int &unicode)
bool decodeUnicodeEscapeSequence (Token &token, Location &current, Location end, unsigned int &unicode)
bool addError (const std::string &message, Token &token, Location extra=0)
bool recoverFromError (TokenType skipUntilToken)
bool addErrorAndRecover (const std::string &message, Token &token, TokenType skipUntilToken)
void skipUntilSpace ()
Value & currentValue ()
Char getNextChar ()
void getLocationLineAndColumn (Location location, int &line, int &column) const
std::string getLocationLineAndColumn (Location location) const
void addComment (Location begin, Location end, CommentPlacement placement)
void skipCommentTokens (Token &token)
Private Attributes
Nodes nodes_
Errors errors_
std::string document_
Location begin_
Location end_
Location current_
Location lastValueEnd_
Value * lastValue_
std::string commentsBefore_
Features features_
bool collectComments_
Detailed Description
Unserialize a JSON document into a Value.
Definition at line 29 of file json_reader.h.
Member Typedef Documentation
typedef char Json::Reader::Char
Definition at line 32 of file json_reader.h.
typedef std::deque<ErrorInfo> Json::Reader::Errors private
Definition at line 121 of file json_reader.h.
typedef const Char* Json::Reader::Location
Definition at line 33 of file json_reader.h.
typedef std::stack<Value*> Json::Reader::Nodes private
Definition at line 167 of file json_reader.h.
Member Enumeration Documentation
enum Json::Reader::TokenType private
Enumerator
tokenEndOfStream
tokenObjectBegin
tokenObjectEnd
tokenArrayBegin
tokenArrayEnd
tokenString
tokenNumber
tokenTrue
tokenFalse
tokenNull
tokenArraySeparator
tokenMemberSeparator
tokenComment
tokenError
Definition at line 87 of file json_reader.h.
     {
         tokenEndOfStream = 0,
         tokenObjectBegin,
         tokenObjectEnd,
         tokenArrayBegin,
         tokenArrayEnd,
         tokenString,
         tokenNumber,
         tokenTrue,
         tokenFalse,
         tokenNull,
         tokenArraySeparator,
         tokenMemberSeparator,
         tokenComment,
         tokenError
     };
Constructor & Destructor Documentation
Json::Reader::Reader ()
Constructs a Reader allowing all features for parsing.
Definition at line 117 of file json_reader.cpp.
     : features_ ( Features::all () )
 {
 }
Json::Reader::Reader (const Features & features)
Constructs a Reader allowing the specified feature set for parsing.
Definition at line 123 of file json_reader.cpp.
     : features_ ( features )
 {
 }
Member Function Documentation
void Json::Reader::addComment (Location begin, Location end, CommentPlacement placement) private
Definition at line 452 of file json_reader.cpp.
References collectComments_, Json::commentAfterOnSameLine, commentsBefore_, lastValue_, and Json::Value::setComment().
Referenced by readComment().
 {
     assert ( collectComments_ );
     if ( placement == commentAfterOnSameLine )
     {
         assert ( lastValue_ != 0 );
         lastValue_->setComment ( std::string ( begin, end ), placement );
     }
     else
     {
         if ( !commentsBefore_.empty () )
             commentsBefore_ += "\n";
         commentsBefore_ += std::string ( begin, end );
     }
 }
bool Json::Reader::addError (const std::string & message, Token & token, Location extra = 0) private
Definition at line 905 of file json_reader.cpp.
References errors_, Json::Reader::ErrorInfo::extra_, Json::Reader::ErrorInfo::message_, and Json::Reader::ErrorInfo::token_.
Referenced by addErrorAndRecover(), decodeDouble(), decodeNumber(), decodeString(), decodeUnicodeCodePoint(), decodeUnicodeEscapeSequence(), expectToken(), parse(), readObject(), and readValue().
 {
     ErrorInfo info;
     info.token_ = token;
     info.message_ = message;
     info.extra_ = extra;
     errors_.push_back ( info );
     return false;
 }
bool Json::Reader::addErrorAndRecover (const std::string & message, Token & token, TokenType skipUntilToken) private
Definition at line 939 of file json_reader.cpp.
References addError(), and recoverFromError().
Referenced by readArray(), and readObject().
 {
     addError ( message, token );
     return recoverFromError ( skipUntilToken );
 }
Value & Json::Reader::currentValue () private
Definition at line 949 of file json_reader.cpp.
References nodes_.
Referenced by decodeDouble(), decodeNumber(), decodeString(), readArray(), readObject(), and readValue().
 {
     return * (nodes_.top ());
 }
bool Json::Reader::decodeDouble (Token & token) private
Definition at line 713 of file json_reader.cpp.
References addError(), currentValue(), Json::Reader::Token::end_, Json::Reader::Token::start_, and value.
Referenced by decodeNumber().
 {
     double value = 0;
     const int bufferSize = 32;
     int count;
     int length = int(token.end_ - token.start_);
     // Sanity check to avoid buffer overflow exploits.
     if (length < 0) {
         return addError( "Unable to parse token length", token );
     }
     // Avoid using a string constant for the format control string given to
     // sscanf, as this can cause hard to debug crashes on OS X. See here for more
     // info:
     //
     // http://developer.apple.com/library/mac/#DOCUMENTATION/DeveloperTools/gcc-4.0.1/gcc/Incompatibilities.html
     char format[] = "%lf";
     if ( length <= bufferSize )
     {
         Char buffer[bufferSize+1];
         memcpy( buffer, token.start_, length );
         buffer[length] = 0;
         count = sscanf( buffer, format, &value );
     }
     else
     {
         std::string buffer( token.start_, token.end_ );
         count = sscanf( buffer.c_str(), format, &value );
     }
     if ( count != 1 )
         return addError( "'" + std::string( token.start_, token.end_ ) + "' is not a number.", token );
     currentValue() = value;
     return true;
 }
bool Json::Reader::decodeNumber (Token & token) private
Definition at line 665 of file json_reader.cpp.
References addError(), currentValue(), decodeDouble(), Json::Reader::Token::end_, Json::in(), Json::Value::maxInt, Json::Value::maxUInt, Json::Value::minInt, Json::Reader::Token::start_, and value.
Referenced by readValue().
 {
     bool isDouble = false;
     for ( Location inspect = token.start_; inspect != token.end_; ++inspect )
     {
         isDouble = isDouble
                    ||  in ( *inspect, '.', 'e', 'E', '+' )
                    ||  ( *inspect == '-'  &&  inspect != token.start_ );
     }
     if ( isDouble )
         return decodeDouble ( token );
     Location current = token.start_;
     bool isNegative = *current == '-';
     if ( isNegative )
         ++current;
     Value::UInt threshold = (isNegative ? Value::UInt (-Value::minInt)
                              : Value::maxUInt) / 10;
     Value::UInt value = 0;
     while ( current < token.end_ )
     {
         Char c = *current++;
         if ( c < '0'  ||  c > '9' )
             return addError ( "'" + std::string ( token.start_, token.end_ ) + "' is not a number.", token );
         if ( value >= threshold )
             return decodeDouble ( token );
         value = value * 10 + Value::UInt (c - '0');
     }
     if ( isNegative )
         currentValue () = -Value::Int ( value );
     else if ( value <= Value::UInt (Value::maxInt) )
         currentValue () = Value::Int ( value );
     else
         currentValue () = value;
     return true;
 }
bool Json::Reader::decodeString (Token & token) private
Definition at line 750 of file json_reader.cpp.
References currentValue().
Referenced by readObject(), and readValue().
 {
     std::string decoded;
     if ( !decodeString ( token, decoded ) )
         return false;
     currentValue () = decoded;
     return true;
 }
bool Json::Reader::decodeString (Token & token, std::string & decoded) private
Definition at line 763 of file json_reader.cpp.
References addError(), Json::codePointToUTF8(), decodeUnicodeCodePoint(), Json::Reader::Token::end_, and Json::Reader::Token::start_.
 {
     decoded.reserve ( token.end_ - token.start_ - 2 );
     Location current = token.start_ + 1; // skip '"'
     Location end = token.end_ - 1;      // do not include '"'
     while ( current != end )
     {
         Char c = *current++;
         if ( c == '"' )
             break;
         else if ( c == '\\' )
         {
             if ( current == end )
                 return addError ( "Empty escape sequence in string", token, current );
             Char escape = *current++;
             switch ( escape )
             {
             case '"':
                 decoded += '"';
                 break;
             case '/':
                 decoded += '/';
                 break;
             case '\\':
                 decoded += '\\';
                 break;
             case 'b':
                 decoded += '\b';
                 break;
             case 'f':
                 decoded += '\f';
                 break;
             case 'n':
                 decoded += '\n';
                 break;
             case 'r':
                 decoded += '\r';
                 break;
             case 't':
                 decoded += '\t';
                 break;
             case 'u':
             {
                 unsigned int unicode;
                 if ( !decodeUnicodeCodePoint ( token, current, end, unicode ) )
                     return false;
                 decoded += codePointToUTF8 (unicode);
             }
             break;
             default:
                 return addError ( "Bad escape sequence in string", token, current );
             }
         }
         else
         {
             decoded += c;
         }
     }
     return true;
 }
bool Json::Reader::decodeUnicodeCodePoint (Token & token, Location & current, Location end, unsigned int & unicode) private
Definition at line 841 of file json_reader.cpp.
References addError(), and decodeUnicodeEscapeSequence().
Referenced by decodeString().
 {
     if ( !decodeUnicodeEscapeSequence ( token, current, end, unicode ) )
         return false;
     if (unicode >= 0xD800 && unicode <= 0xDBFF)
     {
         // surrogate pairs
         if (end - current < 6)
             return addError ( "additional six characters expected to parse unicode surrogate pair.", token, current );
         unsigned int surrogatePair;
         if (* (current++) == '\\' && * (current++) == 'u')
         {
             if (decodeUnicodeEscapeSequence ( token, current, end, surrogatePair ))
             {
                 unicode = 0x10000 + ((unicode & 0x3FF) << 10) + (surrogatePair & 0x3FF);
             }
             else
                 return false;
         }
         else
             return addError ( "expecting another \\u token to begin the second half of a unicode surrogate pair", token, current );
     }
     return true;
 }
bool Json::Reader::decodeUnicodeEscapeSequence (Token & token, Location & current, Location end, unsigned int & unicode) private
Definition at line 875 of file json_reader.cpp.
References addError().
Referenced by decodeUnicodeCodePoint().
 {
     if ( end - current < 4 )
         return addError ( "Bad unicode escape sequence in string: four digits expected.", token, current );
     unicode = 0;
     for ( int index = 0; index < 4; ++index )
     {
         Char c = *current++;
         unicode *= 16;
         if ( c >= '0'  &&  c <= '9' )
             unicode += c - '0';
         else if ( c >= 'a'  &&  c <= 'f' )
             unicode += c - 'a' + 10;
         else if ( c >= 'A'  &&  c <= 'F' )
             unicode += c - 'A' + 10;
         else
             return addError ( "Bad unicode escape sequence in string: hexadecimal digit expected.", token, current );
     }
     return true;
 }
bool Json::Reader::expectToken (TokenType type, Token & token, const char * message) private
Definition at line 284 of file json_reader.cpp.
References addError(), readToken(), and Json::Reader::Token::type_.
 {
     readToken ( token );
     if ( token.type_ != type )
         return addError ( message, token );
     return true;
 }
std::string Json::Reader::getFormatedErrorMessages () const
Returns a user friendly string that list errors in the parsed document.
Returns
Formatted error message with the list of errors with their location in the parsed document. An empty string is returned if no error occurred during parsing.
Definition at line 1011 of file json_reader.cpp.
References errors_, Json::Reader::ErrorInfo::extra_, getLocationLineAndColumn(), Json::Reader::ErrorInfo::message_, Json::Reader::Token::start_, and Json::Reader::ErrorInfo::token_.
Referenced by Json::operator>>().
 {
     std::string formattedMessage;
     for ( Errors::const_iterator itError = errors_.begin ();
             itError != errors_.end ();
             ++itError )
     {
         const ErrorInfo& error = *itError;
         formattedMessage += "* " + getLocationLineAndColumn ( error.token_.start_ ) + "\n";
         formattedMessage += "  " + error.message_ + "\n";
         if ( error.extra_ )
             formattedMessage += "See " + getLocationLineAndColumn ( error.extra_ ) + " for detail.\n";
     }
     return formattedMessage;
 }
void Json::Reader::getLocationLineAndColumn (Location location, int & line, int & column) const private
Definition at line 966 of file json_reader.cpp.
References begin_, and end_.
Referenced by getFormatedErrorMessages(), and getLocationLineAndColumn().
 {
     Location current = begin_;
     Location lastLineStart = current;
     line = 0;
     while ( current < location  &&  current != end_ )
     {
         Char c = *current++;
         if ( c == '\r' )
         {
             if ( *current == '\n' )
                 ++current;
             lastLineStart = current;
             ++line;
         }
         else if ( c == '\n' )
         {
             lastLineStart = current;
             ++line;
         }
     }
     // column & line start at 1
     column = int (location - lastLineStart) + 1;
     ++line;
 }
std::string Json::Reader::getLocationLineAndColumn (Location location) const private
Definition at line 1000 of file json_reader.cpp.
References getLocationLineAndColumn().
 {
     int line, column;
     getLocationLineAndColumn ( location, line, column );
     char buffer[18 + 16 + 16 + 1];
     sprintf ( buffer, "Line %d, Column %d", line, column );
     return buffer;
 }
Reader::Char Json::Reader::getNextChar () private
Definition at line 956 of file json_reader.cpp.
References current_, and end_.
Referenced by readComment(), readCppStyleComment(), readCStyleComment(), readString(), and readToken().
 {
     if ( current_ == end_ )
         return 0;
     return *current_++;
 }
bool Json::Reader::match (Location pattern, int patternLength) private
Definition at line 402 of file json_reader.cpp.
References current_, and end_.
Referenced by readToken().
 {
     if ( end_ - current_ < patternLength )
         return false;
     int index = patternLength;
     while ( index-- )
         if ( current_[index] != pattern[index] )
             return false;
     current_ += patternLength;
     return true;
 }
bool Json::Reader::parse (const std::string & document, Value & root, bool collectComments = true)
Read a Value from a JSON document.
Parameters
document UTF-8 encoded string containing the document to read.
root [out] Contains the root value of the document if it was successfully parsed.
collectComments true to collect comment and allow writing them back during serialization, false to discard comments. This parameter is ignored if Features::allowComments_ is false.
Returns
true if the document was successfully parsed, false if an error occurred.
Definition at line 130 of file json_reader.cpp.
References document_.
Referenced by ripple::WSServerHandler< endpoint_type >::do_message(), ripple::Config::load(), ripple::RPCCallImp::onResponse(), Json::operator>>(), parse(), ripple::RPCParser::parseJson(), ripple::SerializedObject_test::parseJSONString(), ripple::RPCParser::parseRipplePathFind(), ripple::RPCParser::parseSignSubmit(), ripple::RPCServerHandler::processRequest(), ripple::RPCHTTPServerImp::processRequest(), ripple::RPC::JSONRPC_test::testAutoFillFees(), and ripple::JsonCpp_test::testBadJson().
 {
     document_ = document;
     const char* begin = document_.c_str ();
     const char* end = begin + document_.length ();
     return parse ( begin, end, root, collectComments );
 }
bool Json::Reader::parse (const char * beginDoc, const char * endDoc, Value & root, bool collectComments = true)
Read a Value from a JSON document.
Parameters
document UTF-8 encoded string containing the document to read.
root [out] Contains the root value of the document if it was successfully parsed.
collectComments true to collect comment and allow writing them back during serialization, false to discard comments. This parameter is ignored if Features::allowComments_ is false.
Returns
true if the document was successfully parsed, false if an error occurred.
Definition at line 159 of file json_reader.cpp.
References addError(), Json::Features::allowComments_, begin_, collectComments_, Json::commentAfter, commentsBefore_, current_, Json::Reader::Token::end_, end_, errors_, features_, Json::Value::isArray(), Json::Value::isObject(), lastValue_, lastValueEnd_, nodes_, readValue(), Json::Value::setComment(), skipCommentTokens(), Json::Reader::Token::start_, Json::Features::strictRoot_, tokenError, and Json::Reader::Token::type_.
 {
     if ( !features_.allowComments_ )
     {
         collectComments = false;
     }
     begin_ = beginDoc;
     end_ = endDoc;
     collectComments_ = collectComments;
     current_ = begin_;
     lastValueEnd_ = 0;
     lastValue_ = 0;
     commentsBefore_ = "";
     errors_.clear ();
     while ( !nodes_.empty () )
         nodes_.pop ();
     nodes_.push ( &root );
     bool successful = readValue ();
     Token token;
     skipCommentTokens ( token );
     if ( collectComments_  &&  !commentsBefore_.empty () )
         root.setComment ( commentsBefore_, commentAfter );
     if ( features_.strictRoot_ )
     {
         if ( !root.isArray ()  &&  !root.isObject () )
         {
             // Set error location to start of doc, ideally should be first token found in doc
             token.type_ = tokenError;
             token.start_ = beginDoc;
             token.end_ = endDoc;
             addError ( "A valid JSON document must be either an array or an object value.",
                        token );
             return false;
         }
     }
     return successful;
 }
bool Json::Reader::parse (std::istream & is, Value & root, bool collectComments = true)
Parse from input stream.
See Also
Json::operator>>(std::istream&, Json::Value&).
Definition at line 142 of file json_reader.cpp.
References parse().
 {
     //std::istream_iterator<char> begin(sin);
     //std::istream_iterator<char> end;
     // Those would allow streamed input from a file, if parse() were a
     // template function.
     // Since std::string is reference-counted, this at least does not
     // create an extra copy.
     std::string doc;
     std::getline (sin, doc, (char)EOF);
     return parse ( doc, root, collectComments );
 }
bool Json::Reader::readArray (Token & token) private
Definition at line 613 of file json_reader.cpp.
References addErrorAndRecover(), Json::arrayValue, current_, currentValue(), nodes_, ripple::Resource::ok, readToken(), readValue(), recoverFromError(), skipSpaces(), tokenArrayEnd, tokenArraySeparator, tokenComment, Json::Reader::Token::type_, rocksdb::crc32c::Value(), and value.
Referenced by readValue().
 {
     currentValue () = Value ( arrayValue );
     skipSpaces ();
     if ( *current_ == ']' ) // empty array
     {
         Token endArray;
         readToken ( endArray );
         return true;
     }
     int index = 0;
     while ( true )
     {
         Value& value = currentValue ()[ index++ ];
         nodes_.push ( &value );
         bool ok = readValue ();
         nodes_.pop ();
         if ( !ok ) // error already set
             return recoverFromError ( tokenArrayEnd );
         Token token;
         // Accept Comment after last item in the array.
         ok = readToken ( token );
         while ( token.type_ == tokenComment  &&  ok )
         {
             ok = readToken ( token );
         }
         bool badTokenType = ( token.type_ == tokenArraySeparator  &&
                               token.type_ == tokenArrayEnd );
         if ( !ok  ||  badTokenType )
         {
             return addErrorAndRecover ( "Missing ',' or ']' in array declaration",
                                         token,
                                         tokenArrayEnd );
         }
         if ( token.type_ == tokenArrayEnd )
             break;
     }
     return true;
 }
bool Json::Reader::readComment () private
Definition at line 420 of file json_reader.cpp.
References addComment(), collectComments_, Json::commentAfterOnSameLine, Json::commentBefore, Json::containsNewLine(), current_, getNextChar(), lastValueEnd_, readCppStyleComment(), and readCStyleComment().
Referenced by readToken().
 {
     Location commentBegin = current_ - 1;
     Char c = getNextChar ();
     bool successful = false;
     if ( c == '*' )
         successful = readCStyleComment ();
     else if ( c == '/' )
         successful = readCppStyleComment ();
     if ( !successful )
         return false;
     if ( collectComments_ )
     {
         CommentPlacement placement = commentBefore;
         if ( lastValueEnd_  &&  !containsNewLine ( lastValueEnd_, commentBegin ) )
         {
             if ( c != '*'  ||  !containsNewLine ( commentBegin, current_ ) )
                 placement = commentAfterOnSameLine;
         }
         addComment ( commentBegin, current_, placement );
     }
     return true;
 }
bool Json::Reader::readCppStyleComment () private
Definition at line 489 of file json_reader.cpp.
References current_, end_, and getNextChar().
Referenced by readComment().
 {
     while ( current_ != end_ )
     {
         Char c = getNextChar ();
         if (  c == '\r'  ||  c == '\n' )
             break;
     }
     return true;
 }
bool Json::Reader::readCStyleComment () private
Definition at line 474 of file json_reader.cpp.
References current_, end_, and getNextChar().
Referenced by readComment().
 {
     while ( current_ != end_ )
     {
         Char c = getNextChar ();
         if ( c == '*'  &&  *current_ == '/' )
             break;
     }
     return getNextChar () == '/';
 }
void Json::Reader::readNumber () private
Definition at line 504 of file json_reader.cpp.
References current_, end_, and Json::in().
Referenced by readToken().
 {
     while ( current_ != end_ )
     {
         if ( ! (*current_ >= '0'  &&  *current_ <= '9')  &&
                 !in ( *current_, '.', 'e', 'E', '+', '-' ) )
             break;
         ++current_;
     }
 }
bool Json::Reader::readObject (Token & token) private
Definition at line 536 of file json_reader.cpp.
References addError(), addErrorAndRecover(), currentValue(), decodeString(), name, nodes_, Json::objectValue, ripple::Resource::ok, readToken(), readValue(), recoverFromError(), tokenArraySeparator, tokenComment, tokenMemberSeparator, tokenObjectEnd, tokenString, Json::Reader::Token::type_, rocksdb::crc32c::Value(), and value.
Referenced by readValue().
 {
     Token tokenName;
     std::string name;
     currentValue () = Value ( objectValue );
     while ( readToken ( tokenName ) )
     {
         bool initialTokenOk = true;
         while ( tokenName.type_ == tokenComment  &&  initialTokenOk )
             initialTokenOk = readToken ( tokenName );
         if  ( !initialTokenOk )
             break;
         if ( tokenName.type_ == tokenObjectEnd  &&  name.empty () ) // empty object
             return true;
         if ( tokenName.type_ != tokenString )
             break;
         name = "";
         if ( !decodeString ( tokenName, name ) )
             return recoverFromError ( tokenObjectEnd );
         Token colon;
         if ( !readToken ( colon ) ||  colon.type_ != tokenMemberSeparator )
         {
             return addErrorAndRecover ( "Missing ':' after object member name",
                                         colon,
                                         tokenObjectEnd );
         }
         // Reject duplicate names
         if (currentValue ().isMember (name))
             return addError ( "Key '" + name + "' appears twice.", tokenName );
         Value& value = currentValue ()[ name ];
         nodes_.push ( &value );
         bool ok = readValue ();
         nodes_.pop ();
         if ( !ok ) // error already set
             return recoverFromError ( tokenObjectEnd );
         Token comma;
         if ( !readToken ( comma )
                 ||  ( comma.type_ != tokenObjectEnd  &&
                       comma.type_ != tokenArraySeparator &&
                       comma.type_ != tokenComment ) )
         {
             return addErrorAndRecover ( "Missing ',' or '}' in object declaration",
                                         comma,
                                         tokenObjectEnd );
         }
         bool finalizeTokenOk = true;
         while ( comma.type_ == tokenComment &&
                 finalizeTokenOk )
             finalizeTokenOk = readToken ( comma );
         if ( comma.type_ == tokenObjectEnd )
             return true;
     }
     return addErrorAndRecover ( "Missing '}' or object member name",
                                 tokenName,
                                 tokenObjectEnd );
 }
bool Json::Reader::readString () private
Definition at line 517 of file json_reader.cpp.
References current_, end_, and getNextChar().
Referenced by readToken().
 {
     Char c = 0;
     while ( current_ != end_ )
     {
         c = getNextChar ();
         if ( c == '\\' )
             getNextChar ();
         else if ( c == '"' )
             break;
     }
     return c == '"';
 }
bool Json::Reader::readToken (Token & token) private
Definition at line 296 of file json_reader.cpp.
References current_, Json::Reader::Token::end_, getNextChar(), match(), ripple::Resource::ok, readComment(), readNumber(), readString(), skipSpaces(), Json::Reader::Token::start_, tokenArrayBegin, tokenArrayEnd, tokenArraySeparator, tokenComment, tokenEndOfStream, tokenError, tokenFalse, tokenMemberSeparator, tokenNull, tokenNumber, tokenObjectBegin, tokenObjectEnd, tokenString, tokenTrue, and Json::Reader::Token::type_.
Referenced by expectToken(), readArray(), readObject(), recoverFromError(), and skipCommentTokens().
 {
     skipSpaces ();
     token.start_ = current_;
     Char c = getNextChar ();
     bool ok = true;
     switch ( c )
     {
     case '{':
         token.type_ = tokenObjectBegin;
         break;
     case '}':
         token.type_ = tokenObjectEnd;
         break;
     case '[':
         token.type_ = tokenArrayBegin;
         break;
     case ']':
         token.type_ = tokenArrayEnd;
         break;
     case '"':
         token.type_ = tokenString;
         ok = readString ();
         break;
     case '/':
         token.type_ = tokenComment;
         ok = readComment ();
         break;
     case '0':
     case '1':
     case '2':
     case '3':
     case '4':
     case '5':
     case '6':
     case '7':
     case '8':
     case '9':
     case '-':
         token.type_ = tokenNumber;
         readNumber ();
         break;
     case 't':
         token.type_ = tokenTrue;
         ok = match ( "rue", 3 );
         break;
     case 'f':
         token.type_ = tokenFalse;
         ok = match ( "alse", 4 );
         break;
     case 'n':
         token.type_ = tokenNull;
         ok = match ( "ull", 3 );
         break;
     case ',':
         token.type_ = tokenArraySeparator;
         break;
     case ':':
         token.type_ = tokenMemberSeparator;
         break;
     case 0:
         token.type_ = tokenEndOfStream;
         break;
     default:
         ok = false;
         break;
     }
     if ( !ok )
         token.type_ = tokenError;
     token.end_ = current_;
     return true;
 }
bool Json::Reader::readValue () private
Definition at line 208 of file json_reader.cpp.
References addError(), collectComments_, Json::commentBefore, commentsBefore_, current_, currentValue(), decodeNumber(), decodeString(), lastValue_, lastValueEnd_, readArray(), readObject(), Json::Value::setComment(), skipCommentTokens(), tokenArrayBegin, tokenFalse, tokenNull, tokenNumber, tokenObjectBegin, tokenString, tokenTrue, Json::Reader::Token::type_, and rocksdb::crc32c::Value().
Referenced by parse(), readArray(), and readObject().
 {
     Token token;
     skipCommentTokens ( token );
     bool successful = true;
     if ( collectComments_  &&  !commentsBefore_.empty () )
     {
         currentValue ().setComment ( commentsBefore_, commentBefore );
         commentsBefore_ = "";
     }
     switch ( token.type_ )
     {
     case tokenObjectBegin:
         successful = readObject ( token );
         break;
     case tokenArrayBegin:
         successful = readArray ( token );
         break;
     case tokenNumber:
         successful = decodeNumber ( token );
         break;
     case tokenString:
         successful = decodeString ( token );
         break;
     case tokenTrue:
         currentValue () = true;
         break;
     case tokenFalse:
         currentValue () = false;
         break;
     case tokenNull:
         currentValue () = Value ();
         break;
     default:
         return addError ( "Syntax error: value, object or array expected.", token );
     }
     if ( collectComments_ )
     {
         lastValueEnd_ = current_;
         lastValue_ = &currentValue ();
     }
     return successful;
 }
bool Json::Reader::recoverFromError (TokenType skipUntilToken) private
Definition at line 919 of file json_reader.cpp.
References errors_, readToken(), and tokenEndOfStream.
Referenced by addErrorAndRecover(), readArray(), and readObject().
 {
     int errorCount = int (errors_.size ());
     Token skip;
     while ( true )
     {
         if ( !readToken (skip) )
             errors_.resize ( errorCount ); // discard errors caused by recovery
         if ( skip.type_ == skipUntilToken  ||  skip.type_ == tokenEndOfStream )
             break;
     }
     errors_.resize ( errorCount );
     return false;
 }
void Json::Reader::skipCommentTokens (Token & token) private
Definition at line 266 of file json_reader.cpp.
References Json::Features::allowComments_, features_, readToken(), tokenComment, and Json::Reader::Token::type_.
Referenced by parse(), and readValue().
 {
     if ( features_.allowComments_ )
     {
         do
         {
             readToken ( token );
         }
         while ( token.type_ == tokenComment );
     }
     else
     {
         readToken ( token );
     }
 }
void Json::Reader::skipSpaces () private
Definition at line 387 of file json_reader.cpp.
References current_, and end_.
Referenced by readArray(), and readToken().
 {
     while ( current_ != end_ )
     {
         Char c = *current_;
         if ( c == ' '  ||  c == '\t'  ||  c == '\r'  ||  c == '\n' )
             ++current_;
         else
             break;
     }
 }
void Json::Reader::skipUntilSpace () private
Member Data Documentation
Location Json::Reader::begin_ private
Definition at line 171 of file json_reader.h.
Referenced by getLocationLineAndColumn(), and parse().
bool Json::Reader::collectComments_ private
Definition at line 178 of file json_reader.h.
Referenced by addComment(), parse(), readComment(), and readValue().
std::string Json::Reader::commentsBefore_ private
Definition at line 176 of file json_reader.h.
Referenced by addComment(), parse(), and readValue().
Location Json::Reader::current_ private
Definition at line 173 of file json_reader.h.
Referenced by getNextChar(), match(), parse(), readArray(), readComment(), readCppStyleComment(), readCStyleComment(), readNumber(), readString(), readToken(), readValue(), and skipSpaces().
std::string Json::Reader::document_ private
Definition at line 170 of file json_reader.h.
Referenced by parse().
Location Json::Reader::end_ private
Definition at line 172 of file json_reader.h.
Referenced by getLocationLineAndColumn(), getNextChar(), match(), parse(), readCppStyleComment(), readCStyleComment(), readNumber(), readString(), and skipSpaces().
Errors Json::Reader::errors_ private
Definition at line 169 of file json_reader.h.
Referenced by addError(), getFormatedErrorMessages(), parse(), and recoverFromError().
Features Json::Reader::features_ private
Definition at line 177 of file json_reader.h.
Referenced by parse(), and skipCommentTokens().
Value* Json::Reader::lastValue_ private
Definition at line 175 of file json_reader.h.
Referenced by addComment(), parse(), and readValue().
Location Json::Reader::lastValueEnd_ private
Definition at line 174 of file json_reader.h.
Referenced by parse(), readComment(), and readValue().
Nodes Json::Reader::nodes_ private
Definition at line 168 of file json_reader.h.
Referenced by currentValue(), parse(), readArray(), and readObject().
The documentation for this class was generated from the following files:
rippled/src/ripple/json/api/json_reader.h
rippled/src/ripple/json/impl/json_reader.cpp