rippled: AutoSocket Class Reference
AutoSocket Class Reference
#include <AutoSocket.h>
Public Types
typedef
boost::asio::ssl::stream
< boost::asio::ip::tcp::socket > ssl_socket
typedef
boost::asio::ip::tcp::socket::endpoint_type endpoint_type
typedef boost::shared_ptr
< ssl_socket > socket_ptr
typedef ssl_socket::next_layer_type plain_socket
typedef
ssl_socket::lowest_layer_type lowest_layer_type
typedef ssl_socket::handshake_type handshake_type
typedef boost::system::error_code error_code
typedef std::function< void(error_code)> callback
Public Member Functions
AutoSocket (boost::asio::io_service &s, boost::asio::ssl::context &c)
AutoSocket (boost::asio::io_service &s, boost::asio::ssl::context &c, bool secureOnly, bool plainOnly)
boost::asio::io_service & get_io_service () noexcept
bool isSecure ()
ssl_socket & SSLSocket ()
plain_socket & PlainSocket ()
void setSSLOnly ()
void setPlainOnly ()
lowest_layer_type & lowest_layer ()
void swap (AutoSocket &s)
boost::system::error_code cancel (boost::system::error_code &ec)
boost::system::error_code verify (const std::string &strDomain)
void async_handshake (handshake_type type, callback cbFunc)
template<typename ShutdownHandler >
void async_shutdown (ShutdownHandler handler)
template<typename Seq , typename Handler >
void async_read_some (const Seq &buffers, Handler handler)
template<typename Seq , typename Condition , typename Handler >
void async_read_until (const Seq &buffers, Condition condition, Handler handler)
template<typename Allocator , typename Handler >
void async_read_until (boost::asio::basic_streambuf< Allocator > &buffers, const std::string &delim, Handler handler)
template<typename Allocator , typename MatchCondition , typename Handler >
void async_read_until (boost::asio::basic_streambuf< Allocator > &buffers, MatchCondition cond, Handler handler)
template<typename Buf , typename Handler >
void async_write (const Buf &buffers, Handler handler)
template<typename Allocator , typename Handler >
void async_write (boost::asio::basic_streambuf< Allocator > &buffers, Handler handler)
template<typename Buf , typename Condition , typename Handler >
void async_read (const Buf &buffers, Condition cond, Handler handler)
template<typename Allocator , typename Condition , typename Handler >
void async_read (boost::asio::basic_streambuf< Allocator > &buffers, Condition cond, Handler handler)
template<typename Buf , typename Handler >
void async_read (const Buf &buffers, Handler handler)
template<typename Seq , typename Handler >
void async_write_some (const Seq &buffers, Handler handler)
Static Public Member Functions
static bool rfc2818_verify (const std::string &domain, bool preverified, boost::asio::ssl::verify_context &ctx)
Protected Member Functions
void handle_autodetect (callback cbFunc, const error_code &ec, size_t bytesTransferred)
Private Attributes
socket_ptr mSocket
bool mSecure
std::vector< char > mBuffer
Static Private Attributes
static ripple::LogPartition AutoSocketPartition
Detailed Description
Definition at line 30 of file AutoSocket.h.
Member Typedef Documentation
typedef std::function<void (error_code)> AutoSocket::callback
Definition at line 40 of file AutoSocket.h.
typedef boost::asio::ip::tcp::socket::endpoint_type AutoSocket::endpoint_type
Definition at line 34 of file AutoSocket.h.
typedef boost::system::error_code AutoSocket::error_code
Definition at line 39 of file AutoSocket.h.
typedef ssl_socket::handshake_type AutoSocket::handshake_type
Definition at line 38 of file AutoSocket.h.
typedef ssl_socket::lowest_layer_type AutoSocket::lowest_layer_type
Definition at line 37 of file AutoSocket.h.
typedef ssl_socket::next_layer_type AutoSocket::plain_socket
Definition at line 36 of file AutoSocket.h.
typedef boost::shared_ptr<ssl_socket> AutoSocket::socket_ptr
Definition at line 35 of file AutoSocket.h.
typedef boost::asio::ssl::stream<boost::asio::ip::tcp::socket> AutoSocket::ssl_socket
Definition at line 33 of file AutoSocket.h.
Constructor & Destructor Documentation
AutoSocket::AutoSocket (boost::asio::io_service & s, boost::asio::ssl::context & c) inline
Definition at line 43 of file AutoSocket.h.
References mSocket.
         : mSecure (false)
         , mBuffer (4)
     {
         mSocket = boost::make_shared<ssl_socket> (boost::ref (s), boost::ref (c));
     }
AutoSocket::AutoSocket (boost::asio::io_service & s, boost::asio::ssl::context & c, bool secureOnly, bool plainOnly) inline
Definition at line 50 of file AutoSocket.h.
References mSocket.
         : mSecure (secureOnly)
         , mBuffer ((plainOnly || secureOnly) ? 0 : 4)
     {
         mSocket = boost::make_shared<ssl_socket> (boost::ref (s), boost::ref (c));
     }
Member Function Documentation
void AutoSocket::async_handshake (handshake_type type, callback cbFunc) inline
Definition at line 134 of file AutoSocket.h.
References beast::asio::bind_handler(), handle_autodetect(), mBuffer, mSecure, and mSocket.
Referenced by ripple::HTTPClientImp::handleConnect().
     {
         if ((type == ssl_socket::client) || (mSecure))
         {
             // must be ssl
             mSecure = true;
             mSocket->async_handshake (type, cbFunc);
         }
         else if (mBuffer.empty ())
         {
             // must be plain
             mSecure = false;
             mSocket->get_io_service ().post (
                 beast::asio::bind_handler (cbFunc, error_code()));
         }
         else
         {
             // autodetect
             mSocket->next_layer ().async_receive (boost::asio::buffer (mBuffer), boost::asio::socket_base::message_peek,
                                                   boost::bind (&AutoSocket::handle_autodetect, this, cbFunc,
                                                           boost::asio::placeholders::error, boost::asio::placeholders::bytes_transferred));
         }
     }
template<typename Buf , typename Condition , typename Handler > void AutoSocket::async_read (const Buf & buffers, Condition cond, Handler handler) inline
Definition at line 234 of file AutoSocket.h.
References isSecure(), mSocket, and PlainSocket().
Referenced by ripple::HTTPClientImp::handleHeader().
     {
         if (isSecure ())
             boost::asio::async_read (*mSocket, buffers, cond, handler);
         else
             boost::asio::async_read (PlainSocket (), buffers, cond, handler);
     }
template<typename Allocator , typename Condition , typename Handler > void AutoSocket::async_read (boost::asio::basic_streambuf< Allocator > & buffers, Condition cond, Handler handler) inline
Definition at line 243 of file AutoSocket.h.
References isSecure(), mSocket, and PlainSocket().
     {
         if (isSecure ())
             boost::asio::async_read (*mSocket, buffers, cond, handler);
         else
             boost::asio::async_read (PlainSocket (), buffers, cond, handler);
     }
template<typename Buf , typename Handler > void AutoSocket::async_read (const Buf & buffers, Handler handler) inline
Definition at line 252 of file AutoSocket.h.
References isSecure(), mSocket, and PlainSocket().
     {
         if (isSecure ())
             boost::asio::async_read (*mSocket, buffers, handler);
         else
             boost::asio::async_read (PlainSocket (), buffers, handler);
     }
template<typename Seq , typename Handler > void AutoSocket::async_read_some (const Seq & buffers, Handler handler) inline
Definition at line 180 of file AutoSocket.h.
References isSecure(), mSocket, and PlainSocket().
     {
         if (isSecure ())
             mSocket->async_read_some (buffers, handler);
         else
             PlainSocket ().async_read_some (buffers, handler);
     }
template<typename Seq , typename Condition , typename Handler > void AutoSocket::async_read_until (const Seq & buffers, Condition condition, Handler handler) inline
Definition at line 189 of file AutoSocket.h.
References isSecure(), mSocket, and PlainSocket().
Referenced by ripple::HTTPClientImp::handleWrite().
     {
         if (isSecure ())
             boost::asio::async_read_until (*mSocket, buffers, condition, handler);
         else
             boost::asio::async_read_until (PlainSocket (), buffers, condition, handler);
     }
template<typename Allocator , typename Handler > void AutoSocket::async_read_until (boost::asio::basic_streambuf< Allocator > & buffers, const std::string & delim, Handler handler) inline
Definition at line 198 of file AutoSocket.h.
References isSecure(), mSocket, and PlainSocket().
     {
         if (isSecure ())
             boost::asio::async_read_until (*mSocket, buffers, delim, handler);
         else
             boost::asio::async_read_until (PlainSocket (), buffers, delim, handler);
     }
template<typename Allocator , typename MatchCondition , typename Handler > void AutoSocket::async_read_until (boost::asio::basic_streambuf< Allocator > & buffers, MatchCondition cond, Handler handler) inline
Definition at line 207 of file AutoSocket.h.
References isSecure(), mSocket, and PlainSocket().
     {
         if (isSecure ())
             boost::asio::async_read_until (*mSocket, buffers, cond, handler);
         else
             boost::asio::async_read_until (PlainSocket (), buffers, cond, handler);
     }
template<typename ShutdownHandler > void AutoSocket::async_shutdown (ShutdownHandler handler) inline
Definition at line 159 of file AutoSocket.h.
References beast::asio::bind_handler(), isSecure(), lowest_layer(), and mSocket.
Referenced by ripple::HTTPClientImp::handleDeadline().
     {
         if (isSecure ())
             mSocket->async_shutdown (handler);
         else
         {
             error_code ec;
             try
             {
                 lowest_layer ().shutdown (plain_socket::shutdown_both);
             }
             catch (boost::system::system_error& e)
             {
                 ec = e.code();
             }
             mSocket->get_io_service ().post (
                 beast::asio::bind_handler (handler, ec));
         }
     }
template<typename Buf , typename Handler > void AutoSocket::async_write (const Buf & buffers, Handler handler) inline
Definition at line 216 of file AutoSocket.h.
References isSecure(), mSocket, and PlainSocket().
Referenced by ripple::HTTPClientImp::handleRequest().
     {
         if (isSecure ())
             boost::asio::async_write (*mSocket, buffers, handler);
         else
             boost::asio::async_write (PlainSocket (), buffers, handler);
     }
template<typename Allocator , typename Handler > void AutoSocket::async_write (boost::asio::basic_streambuf< Allocator > & buffers, Handler handler) inline
Definition at line 225 of file AutoSocket.h.
References isSecure(), mSocket, and PlainSocket().
     {
         if (isSecure ())
             boost::asio::async_write (*mSocket, buffers, handler);
         else
             boost::asio::async_write (PlainSocket (), buffers, handler);
     }
template<typename Seq , typename Handler > void AutoSocket::async_write_some (const Seq & buffers, Handler handler) inline
Definition at line 261 of file AutoSocket.h.
References isSecure(), mSocket, and PlainSocket().
     {
         if (isSecure ())
             mSocket->async_write_some (buffers, handler);
         else
             PlainSocket ().async_write_some (buffers, handler);
     }
boost::system::error_code AutoSocket::cancel (boost::system::error_code & ec) inline
Definition at line 95 of file AutoSocket.h.
References lowest_layer().
     {
         return lowest_layer ().cancel (ec);
     }
boost::asio::io_service& AutoSocket::get_io_service () inline noexcept
Definition at line 57 of file AutoSocket.h.
References mSocket.
     {
         return mSocket->get_io_service ();
     }
void AutoSocket::handle_autodetect (callback cbFunc, const error_code & ec, size_t bytesTransferred) inline protected
Definition at line 270 of file AutoSocket.h.
References AutoSocketPartition, ripple::LogPartition::doLog(), rocksdb::Log(), ripple::lsTRACE, ripple::lsWARNING, mBuffer, mSecure, and mSocket.
Referenced by async_handshake().
     {
         using namespace ripple;
         if (ec)
         {
             Log (lsWARNING, AutoSocketPartition) << "Handle autodetect error: " << ec;
             cbFunc (ec);
         }
         else if ((mBuffer[0] < 127) && (mBuffer[0] > 31) &&
                  ((bytesTransferred < 2) || ((mBuffer[1] < 127) && (mBuffer[1] > 31))) &&
                  ((bytesTransferred < 3) || ((mBuffer[2] < 127) && (mBuffer[2] > 31))) &&
                  ((bytesTransferred < 4) || ((mBuffer[3] < 127) && (mBuffer[3] > 31))))
         {
             // not ssl
             if (AutoSocketPartition.doLog (lsTRACE))
                 Log (lsTRACE, AutoSocketPartition) << "non-SSL";
             mSecure = false;
             cbFunc (ec);
         }
         else
         {
             // ssl
             if (AutoSocketPartition.doLog (lsTRACE))
                 Log (lsTRACE, AutoSocketPartition) << "SSL";
             mSecure = true;
             mSocket->async_handshake (ssl_socket::server, cbFunc);
         }
     }
bool AutoSocket::isSecure () inline
Definition at line 62 of file AutoSocket.h.
References mSecure.
Referenced by async_read(), async_read_some(), async_read_until(), async_shutdown(), async_write(), and async_write_some().
     {
         return mSecure;
     }
lowest_layer_type& AutoSocket::lowest_layer () inline
Definition at line 83 of file AutoSocket.h.
References mSocket.
Referenced by async_shutdown(), cancel(), and ripple::HTTPClientImp::handleResolve().
     {
         return mSocket->lowest_layer ();
     }
plain_socket& AutoSocket::PlainSocket () inline
Definition at line 70 of file AutoSocket.h.
References mSocket.
Referenced by async_read(), async_read_some(), async_read_until(), async_write(), and async_write_some().
     {
         return mSocket->next_layer ();
     }
static bool AutoSocket::rfc2818_verify (const std::string & domain, bool preverified, boost::asio::ssl::verify_context & ctx) inline static
Definition at line 101 of file AutoSocket.h.
References AutoSocketPartition, rocksdb::Log(), and ripple::lsWARNING.
Referenced by verify().
     {
         using namespace ripple;
         if (boost::asio::ssl::rfc2818_verification (domain) (preverified, ctx))
             return true;
         Log (lsWARNING, AutoSocketPartition) << "Outbound SSL connection to " <<
                                              domain << " fails certificate verification";
         return false;
     }
void AutoSocket::setPlainOnly () inline
Definition at line 78 of file AutoSocket.h.
References mBuffer.
     {
         mBuffer.clear ();
     }
void AutoSocket::setSSLOnly () inline
Definition at line 74 of file AutoSocket.h.
References mSecure.
     {
         mSecure = true;
     }
ssl_socket& AutoSocket::SSLSocket () inline
Definition at line 66 of file AutoSocket.h.
References mSocket.
Referenced by ripple::HTTPClientImp::HTTPClientImp().
     {
         return *mSocket;
     }
void AutoSocket::swap (AutoSocket & s) inline
Definition at line 88 of file AutoSocket.h.
References mBuffer, mSecure, mSocket, and beast::asio::swap().
     {
         mBuffer.swap (s.mBuffer);
         mSocket.swap (s.mSocket);
         std::swap (mSecure, s.mSecure);
     }
boost::system::error_code AutoSocket::verify (const std::string & strDomain) inline
Definition at line 113 of file AutoSocket.h.
References mSocket, and rfc2818_verify().
Referenced by ripple::HTTPClientImp::handleConnect().
     {
         boost::system::error_code ec;
         mSocket->set_verify_mode (boost::asio::ssl::verify_peer);
         // XXX Verify semantics of RFC 2818 are what we want.
         mSocket->set_verify_callback (boost::bind (&rfc2818_verify, strDomain, boost::placeholders::_1, boost::placeholders::_2), ec);
         return ec;
     }
Member Data Documentation
ripple::LogPartition AutoSocket::AutoSocketPartition static private
Definition at line 303 of file AutoSocket.h.
Referenced by handle_autodetect(), and rfc2818_verify().
std::vector<char> AutoSocket::mBuffer private
Definition at line 306 of file AutoSocket.h.
Referenced by async_handshake(), handle_autodetect(), setPlainOnly(), and swap().
bool AutoSocket::mSecure private
Definition at line 305 of file AutoSocket.h.
Referenced by async_handshake(), handle_autodetect(), isSecure(), setSSLOnly(), and swap().
socket_ptr AutoSocket::mSocket private
Definition at line 304 of file AutoSocket.h.
Referenced by async_handshake(), async_read(), async_read_some(), async_read_until(), async_shutdown(), async_write(), async_write_some(), AutoSocket(), get_io_service(), handle_autodetect(), lowest_layer(), PlainSocket(), SSLSocket(), swap(), and verify().
The documentation for this class was generated from the following files:
rippled/src/ripple_websocket/autosocket/AutoSocket.h
rippled/src/ripple_websocket/autosocket/AutoSocket.cpp