rippled: ripple::AcceptedLedgerTx Class Reference
ripple::AcceptedLedgerTx Class Reference
#include <AcceptedLedgerTx.h>
Public Types
typedef boost::shared_ptr
< AcceptedLedgerTx > pointer
typedef const pointer & ref
Public Member Functions
AcceptedLedgerTx (LedgerIndex ledgerSeq, SerializerIterator &sit)
AcceptedLedgerTx (SerializedTransaction::ref, TransactionMetaSet::ref)
AcceptedLedgerTx (SerializedTransaction::ref, TER result)
SerializedTransaction::ref getTxn () const
TransactionMetaSet::ref getMeta () const
std::vector< RippleAddress >
const & getAffected () const
TxID getTransactionID () const
TxType getTxnType () const
TER getResult () const
std::uint32_t getTxnSeq () const
bool isApplied () const
int getIndex () const
std::string getEscMeta () const
Json::Value getJson () const
Private Member Functions
void buildJson ()
Private Attributes
SerializedTransaction::pointer mTxn
TransactionMetaSet::pointer mMeta
TER mResult
std::vector< RippleAddress > mAffected
Blob mRawMeta
Json::Value mJson
Detailed Description
A transaction that is in a closed ledger.
Description
An accepted ledger transaction contains additional information that the server needs to tell clients about the transaction. For example,
The transaction in JSON form
Which accounts are affected This is used by InfoSub to report to clients
Cached stuff
See Also
{uri}
Definition at line 44 of file AcceptedLedgerTx.h.
Member Typedef Documentation
typedef boost::shared_ptr<AcceptedLedgerTx> ripple::AcceptedLedgerTx::pointer
Definition at line 47 of file AcceptedLedgerTx.h.
typedef const pointer& ripple::AcceptedLedgerTx::ref
Definition at line 48 of file AcceptedLedgerTx.h.
Constructor & Destructor Documentation
ripple::AcceptedLedgerTx::AcceptedLedgerTx (LedgerIndex ledgerSeq, SerializerIterator & sit)
Definition at line 22 of file AcceptedLedgerTx.cpp.
References buildJson(), ripple::SerializerIterator::getVL(), mAffected, mMeta, mRawMeta, mResult, and mTxn.
 {
     Serializer          txnSer (sit.getVL ());
     SerializerIterator  txnIt (txnSer);
     mTxn =      boost::make_shared<SerializedTransaction> (boost::ref (txnIt));
     mRawMeta =  sit.getVL ();
     mMeta =     boost::make_shared<TransactionMetaSet> (mTxn->getTransactionID (), seq, mRawMeta);
     mAffected = mMeta->getAffectedAccounts ();
     mResult =   mMeta->getResultTER ();
     buildJson ();
 }
ripple::AcceptedLedgerTx::AcceptedLedgerTx (SerializedTransaction::ref txn, TransactionMetaSet::ref met)
Definition at line 35 of file AcceptedLedgerTx.cpp.
References buildJson(), mMeta, and mResult.
                                                                                            :
     mTxn (txn), mMeta (met), mAffected (met->getAffectedAccounts ())
 {
     mResult = mMeta->getResultTER ();
     buildJson ();
 }
ripple::AcceptedLedgerTx::AcceptedLedgerTx (SerializedTransaction::ref txn, TER result)
Definition at line 42 of file AcceptedLedgerTx.cpp.
References buildJson().
                                                                             :
     mTxn (txn), mResult (result), mAffected (txn->getMentionedAccounts ())
 {
     buildJson ();
 }
Member Function Documentation
void ripple::AcceptedLedgerTx::buildJson () private
Definition at line 54 of file AcceptedLedgerTx.cpp.
References Json::Value::append(), Json::arrayValue, ripple::RippleAddress::humanAccountID(), mAffected, mJson, mMeta, mRawMeta, mResult, mTxn, Json::objectValue, ripple::strHex(), and ripple::transHuman().
Referenced by AcceptedLedgerTx().
 {
     mJson = Json::objectValue;
     mJson["transaction"] = mTxn->getJson (0);
     if (mMeta)
     {
         mJson["meta"] = mMeta->getJson (0);
         mJson["raw_meta"] = strHex (mRawMeta);
     }
     mJson["result"] = transHuman (mResult);
     if (!mAffected.empty ())
     {
         Json::Value& affected = (mJson["affected"] = Json::arrayValue);
         BOOST_FOREACH (const RippleAddress & ra, mAffected)
         {
             affected.append (ra.humanAccountID ());
         }
     }
 }
std::vector<RippleAddress> const& ripple::AcceptedLedgerTx::getAffected () const inline
Definition at line 63 of file AcceptedLedgerTx.h.
References mAffected.
Referenced by ripple::NetworkOPsImp::pubAccountTransaction().
     {
         return mAffected;
     }
std::string ripple::AcceptedLedgerTx::getEscMeta () const
Definition at line 48 of file AcceptedLedgerTx.cpp.
References mRawMeta, and ripple::sqlEscape().
 {
     assert (!mRawMeta.empty ());
     return sqlEscape (mRawMeta);
 }
int ripple::AcceptedLedgerTx::getIndex () const inline
Definition at line 89 of file AcceptedLedgerTx.h.
References mMeta.
     {
         return mMeta ? mMeta->getIndex () : 0;
     }
Json::Value ripple::AcceptedLedgerTx::getJson () const inline
Definition at line 94 of file AcceptedLedgerTx.h.
References mJson.
Referenced by ripple::NetworkOPsImp::pubProposedTransaction().
     {
         return mJson;
     }
TransactionMetaSet::ref ripple::AcceptedLedgerTx::getMeta () const inline
Definition at line 59 of file AcceptedLedgerTx.h.
References mMeta.
Referenced by ripple::OrderBookDB::processTxn(), ripple::NetworkOPsImp::pubAccountTransaction(), and ripple::NetworkOPsImp::pubValidatedTransaction().
     {
         return mMeta;
     }
TER ripple::AcceptedLedgerTx::getResult () const inline
Definition at line 76 of file AcceptedLedgerTx.h.
References mResult.
Referenced by ripple::OrderBookDB::processTxn(), ripple::NetworkOPsImp::pubAccountTransaction(), and ripple::NetworkOPsImp::pubValidatedTransaction().
     {
         return mResult;
     }
TxID ripple::AcceptedLedgerTx::getTransactionID () const inline
Definition at line 68 of file AcceptedLedgerTx.h.
References mTxn.
     {
         return mTxn->getTransactionID ();
     }
SerializedTransaction::ref ripple::AcceptedLedgerTx::getTxn () const inline
Definition at line 55 of file AcceptedLedgerTx.h.
References mTxn.
Referenced by ripple::NetworkOPsImp::pubAccountTransaction(), and ripple::NetworkOPsImp::pubValidatedTransaction().
     {
         return mTxn;
     }
std::uint32_t ripple::AcceptedLedgerTx::getTxnSeq () const inline
Definition at line 80 of file AcceptedLedgerTx.h.
References mMeta.
     {
         return mMeta->getIndex ();
     }
TxType ripple::AcceptedLedgerTx::getTxnType () const inline
Definition at line 72 of file AcceptedLedgerTx.h.
References mTxn.
     {
         return mTxn->getTxnType ();
     }
bool ripple::AcceptedLedgerTx::isApplied () const inline
Definition at line 85 of file AcceptedLedgerTx.h.
References mMeta.
Referenced by ripple::NetworkOPsImp::pubAccountTransaction().
     {
         return !!mMeta;
     }
Member Data Documentation
std::vector<RippleAddress> ripple::AcceptedLedgerTx::mAffected private
Definition at line 103 of file AcceptedLedgerTx.h.
Referenced by AcceptedLedgerTx(), buildJson(), and getAffected().
Json::Value ripple::AcceptedLedgerTx::mJson private
Definition at line 105 of file AcceptedLedgerTx.h.
Referenced by buildJson(), and getJson().
TransactionMetaSet::pointer ripple::AcceptedLedgerTx::mMeta private
Definition at line 101 of file AcceptedLedgerTx.h.
Referenced by AcceptedLedgerTx(), buildJson(), getIndex(), getMeta(), getTxnSeq(), and isApplied().
Blob ripple::AcceptedLedgerTx::mRawMeta private
Definition at line 104 of file AcceptedLedgerTx.h.
Referenced by AcceptedLedgerTx(), buildJson(), and getEscMeta().
TER ripple::AcceptedLedgerTx::mResult private
Definition at line 102 of file AcceptedLedgerTx.h.
Referenced by AcceptedLedgerTx(), buildJson(), and getResult().
SerializedTransaction::pointer ripple::AcceptedLedgerTx::mTxn private
Definition at line 100 of file AcceptedLedgerTx.h.
Referenced by AcceptedLedgerTx(), buildJson(), getTransactionID(), getTxn(), and getTxnType().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/ledger/AcceptedLedgerTx.h
rippled/src/ripple_app/ledger/AcceptedLedgerTx.cpp