rippled: ripple::CountedObjects Class Reference
ripple::CountedObjects Class Reference
#include <CountedObject.h>
Classes
class CounterBase
Public Types
typedef std::pair< std::string,
int > Entry
typedef std::vector< Entry > List
Public Member Functions
List getCounts (int minimumThreshold) const
Static Public Member Functions
static CountedObjects & getInstance ()
Private Member Functions
CountedObjects ()
~CountedObjects ()
Private Attributes
std::atomic< int > m_count
std::atomic< CounterBase * > m_head
Detailed Description
Manages all counted object types.
Definition at line 28 of file CountedObject.h.
Member Typedef Documentation
typedef std::pair<std::string, int> ripple::CountedObjects::Entry
Definition at line 33 of file CountedObject.h.
typedef std::vector<Entry> ripple::CountedObjects::List
Definition at line 34 of file CountedObject.h.
Constructor & Destructor Documentation
ripple::CountedObjects::CountedObjects () private
Definition at line 29 of file CountedObject.cpp.
     : m_count (0)
     , m_head (nullptr)
 {
 }
ripple::CountedObjects::~CountedObjects () private
Definition at line 35 of file CountedObject.cpp.
 {
 }
Member Function Documentation
CountedObjects::List ripple::CountedObjects::getCounts (int minimumThreshold) const
Definition at line 39 of file CountedObject.cpp.
References counter, ripple::CountedObjects::CounterBase::getCount(), ripple::CountedObjects::CounterBase::getName(), ripple::CountedObjects::CounterBase::getNext(), m_count, and m_head.
Referenced by ripple::RPCHandler::doGetCounts().
 {
     List counts;
     // When other operations are concurrent, the count
     // might be temporarily less than the actual count.
     int const count = m_count.load ();
     counts.reserve (count);
     CounterBase* counter = m_head.load ();
     while (counter != nullptr)
     {
         if (counter->getCount () >= minimumThreshold)
         {
             Entry entry;
             entry.first = counter->getName ();
             entry.second = counter->getCount ();
             counts.push_back (entry);
         }
         counter = counter->getNext ();
     }
     return counts;
 }
CountedObjects & ripple::CountedObjects::getInstance (void) static
Definition at line 22 of file CountedObject.cpp.
References instance.
Referenced by ripple::CountedObjects::CounterBase::CounterBase(), and ripple::RPCHandler::doGetCounts().
 {
     static CountedObjects instance;
     return instance;
 }
Member Data Documentation
std::atomic<int> ripple::CountedObjects::m_count private
Definition at line 85 of file CountedObject.h.
Referenced by ripple::CountedObjects::CounterBase::CounterBase(), and getCounts().
std::atomic<CounterBase*> ripple::CountedObjects::m_head private
Definition at line 86 of file CountedObject.h.
Referenced by ripple::CountedObjects::CounterBase::CounterBase(), and getCounts().
The documentation for this class was generated from the following files:
rippled/src/ripple_basics/utility/CountedObject.h
rippled/src/ripple_basics/utility/CountedObject.cpp