rippled: ripple::RippleSSLContextImp Class Reference
ripple::RippleSSLContextImp Class Reference
Classes
struct ScopedDHPointer
Public Member Functions
RippleSSLContextImp ()
~RippleSSLContextImp ()
std::string error_message (std::string const &what, boost::system::error_code const &ec)
void initCommon ()
void initAnonymous (std::string const &cipherList)
void initAuthenticated (std::string key_file, std::string cert_file, std::string chain_file)
Static Public Member Functions
static DH * tmp_dh_handler (SSL *, int, int key_length)
static std::string getRawDHParams (int keySize)
static DH * getDH (int keyLength)
Static Public Member Functions inherited from ripple::RippleSSLContext
static std::string getRawDHParams (int keySize)
static RippleSSLContext * createBare ()
static RippleSSLContext * createWebSocket ()
static RippleSSLContext * createAnonymous (std::string const &cipherList)
static RippleSSLContext * createAuthenticated (std::string key_file, std::string cert_file, std::string chain_file)
Private Attributes
boost::asio::ssl::context m_context
Additional Inherited Members
Public Types inherited from beast::asio::SSLContext
typedef boost::asio::ssl::context ContextType
Protected Member Functions inherited from ripple::RippleSSLContext
RippleSSLContext (ContextType &context)
Protected Attributes inherited from beast::asio::SSLContext
ContextType & m_context
Detailed Description
Definition at line 27 of file RippleSSLContext.cpp.
Constructor & Destructor Documentation
ripple::RippleSSLContextImp::RippleSSLContextImp () inline
Definition at line 33 of file RippleSSLContext.cpp.
         : RippleSSLContext (m_context)
         , m_context (boost::asio::ssl::context::sslv23)
     {
     }
ripple::RippleSSLContextImp::~RippleSSLContextImp () inline
Definition at line 39 of file RippleSSLContext.cpp.
     {
     }
Member Function Documentation
std::string ripple::RippleSSLContextImp::error_message (std::string const & what, boost::system::error_code const & ec) inline
Definition at line 49 of file RippleSSLContext.cpp.
Referenced by initAuthenticated().
     {
         std::stringstream ss;
         ss <<
             what << ": " <<
             ec.message() <<
             " (" << ec.value() << ")";
         return ss.str();
     }
static DH* ripple::RippleSSLContextImp::getDH (int keyLength) inline static
Definition at line 269 of file RippleSSLContext.cpp.
References ripple::RippleSSLContextImp::ScopedDHPointer::get(), and getRawDHParams().
Referenced by tmp_dh_handler().
     {
         if (keyLength == 512 || keyLength == 1024)
         {
             static ScopedDHPointer dh512 (getRawDHParams (keyLength));
             return dh512.get ();
         }
         else
         {
             beast::FatalError ("unsupported key length", __FILE__, __LINE__);
         }
         return nullptr;
     }
static std::string ripple::RippleSSLContextImp::getRawDHParams (int keySize) inline static
Definition at line 62 of file RippleSSLContext.cpp.
Referenced by getDH(), and ripple::RippleSSLContext::getRawDHParams().
     {
         std::string params;
         // Original code provided the 512-bit keySize parameters
         // when 1024 bits were requested so we will do the same.
         if (keySize == 1024)
             keySize = 512;
         switch (keySize)
         {
         case 512:
             {
                 // These are the DH parameters that OpenCoin has chosen for Ripple
                 //
                 std::uint8_t const raw [] = {
                     0x30, 0x46, 0x02, 0x41, 0x00, 0x98, 0x15, 0xd2, 0xd0, 0x08, 0x32, 0xda,
                     0xaa, 0xac, 0xc4, 0x71, 0xa3, 0x1b, 0x11, 0xf0, 0x6c, 0x62, 0xb2, 0x35,
                     0x8a, 0x10, 0x92, 0xc6, 0x0a, 0xa3, 0x84, 0x7e, 0xaf, 0x17, 0x29, 0x0b,
                     0x70, 0xef, 0x07, 0x4f, 0xfc, 0x9d, 0x6d, 0x87, 0x99, 0x19, 0x09, 0x5b,
                     0x6e, 0xdb, 0x57, 0x72, 0x4a, 0x7e, 0xcd, 0xaf, 0xbd, 0x3a, 0x97, 0x55,
                     0x51, 0x77, 0x5a, 0x34, 0x7c, 0xe8, 0xc5, 0x71, 0x63, 0x02, 0x01, 0x02
                 };
                 params.resize (sizeof (raw));
                 std::copy (raw, raw + sizeof (raw), params.begin ());
             }
             break;
         };
         return params;
     }
void ripple::RippleSSLContextImp::initAnonymous (std::string const & cipherList) inline
Definition at line 112 of file RippleSSLContext.cpp.
References initCommon(), and m_context.
     {
         initCommon ();
         int const result = SSL_CTX_set_cipher_list (
             m_context.native_handle (),
             cipherList.c_str ());
         if (result != 1)
             beast::FatalError ("invalid cipher list", __FILE__, __LINE__);
     }
void ripple::RippleSSLContextImp::initAuthenticated (std::string key_file, std::string cert_file, std::string chain_file) inline
Definition at line 126 of file RippleSSLContext.cpp.
References error_message(), ripple::f, initCommon(), and m_context.
     {
         initCommon ();
         SSL_CTX* const ssl = m_context.native_handle ();
         bool cert_set = false;
         if (! cert_file.empty ())
         {
             boost::system::error_code ec;
             m_context.use_certificate_file (
                 cert_file, boost::asio::ssl::context::pem, ec);
             if (ec)
             {
                 beast::FatalError (error_message (
                     "Problem with SSL certificate file.", ec).c_str(),
                     __FILE__, __LINE__);
             }
             cert_set = true;
         }
         if (! chain_file.empty ())
         {
             // VFALCO Replace fopen() with RAII
             FILE* f = fopen (chain_file.c_str (), "r");
             if (!f)
             {
                 beast::FatalError (error_message (
                     "Problem opening SSL chain file.", boost::system::error_code (errno,
                     boost::system::generic_category())).c_str(),
                     __FILE__, __LINE__);
             }
             try
             {
                 for (;;)
                 {
                     X509* const x = PEM_read_X509 (f, nullptr, nullptr, nullptr);
                     if (x == nullptr)
                         break;
                     if (! cert_set)
                     {
                         if (SSL_CTX_use_certificate (ssl, x) != 1)
                             beast::FatalError ("Problem retrieving SSL certificate from chain file.",
                                 __FILE__, __LINE__);
                         cert_set = true;
                     }
                     else if (SSL_CTX_add_extra_chain_cert (ssl, x) != 1)
                     {
                         X509_free (x);
                         beast::FatalError ("Problem adding SSL chain certificate.",
                             __FILE__, __LINE__);
                     }
                 }
                 fclose (f);
             }
             catch (...)
             {
                 fclose (f);
                 beast::FatalError ("Reading the SSL chain file generated an exception.",
                     __FILE__, __LINE__);
             }
         }
         if (! key_file.empty ())
         {
             boost::system::error_code ec;
             m_context.use_private_key_file (key_file,
                 boost::asio::ssl::context::pem, ec);
             if (ec)
             {
                 beast::FatalError (error_message (
                     "Problem using the SSL private key file.", ec).c_str(),
                     __FILE__, __LINE__);
             }
         }
         if (SSL_CTX_check_private_key (ssl) != 1)
         {
             beast::FatalError ("Invalid key in SSL private key file.",
                 __FILE__, __LINE__);
         }
     }
void ripple::RippleSSLContextImp::initCommon () inline
Definition at line 98 of file RippleSSLContext.cpp.
References m_context, and tmp_dh_handler().
Referenced by initAnonymous(), and initAuthenticated().
     {
         m_context.set_options (
             boost::asio::ssl::context::default_workarounds |
             boost::asio::ssl::context::no_sslv2 |
             boost::asio::ssl::context::single_dh_use);
         SSL_CTX_set_tmp_dh_callback (
             m_context.native_handle (),
             tmp_dh_handler);
     }
static DH* ripple::RippleSSLContextImp::tmp_dh_handler (SSL * , int , int key_length) inline static
Definition at line 43 of file RippleSSLContext.cpp.
References getDH().
Referenced by initCommon().
     {
         return DHparams_dup (getDH (key_length));
     }
Member Data Documentation
boost::asio::ssl::context ripple::RippleSSLContextImp::m_context private
Definition at line 30 of file RippleSSLContext.cpp.
Referenced by initAnonymous(), initAuthenticated(), and initCommon().
The documentation for this class was generated from the following file:
rippled/src/ripple/common/impl/RippleSSLContext.cpp