rippled: ripple::PeerFinder::Manager Class Reference
ripple::PeerFinder::Manager Class Reference abstract
#include <Manager.h>
Public Member Functions
virtual ~Manager ()
virtual void setConfig (Config const &config)=0
virtual void addFixedPeer (std::string const &name, std::vector< beast::IP::Endpoint > const &addresses)=0
virtual void addFallbackStrings (std::string const &name, std::vector< std::string > const &strings)=0
virtual Slot::ptr new_inbound_slot (beast::IP::Endpoint const &local_endpoint, beast::IP::Endpoint const &remote_endpoint)=0
virtual Slot::ptr new_outbound_slot (beast::IP::Endpoint const &remote_endpoint)=0
virtual void on_connected (Slot::ptr const &slot, beast::IP::Endpoint const &local_endpoint)=0
virtual void on_handshake (Slot::ptr const &slot, RipplePublicKey const &key, bool cluster)=0
virtual void on_endpoints (Slot::ptr const &slot, Endpoints const &endpoints)=0
virtual void on_legacy_endpoints (IPAddresses const &addresses)=0
virtual void on_closed (Slot::ptr const &slot)=0
virtual void on_cancel (Slot::ptr const &slot)=0
Public Member Functions inherited from beast::Stoppable
Stoppable (char const *name, Stoppable &parent)
virtual ~Stoppable ()
bool isStopping () const
bool isStopped () const
bool areChildrenStopped () const
void stopped ()
virtual void onPrepare ()
virtual void onStart ()
virtual void onStop ()
virtual void onChildrenStopped ()
Public Member Functions inherited from beast::PropertyStream::Source
Source (std::string const &name)
~Source ()
std::string const & name () const
void add (Source &source)
template<class Derived >
Derived * add (Derived *child)
void remove (Source &child)
void removeAll ()
void write_one (PropertyStream &stream)
void write (PropertyStream &stream)
void write (PropertyStream &stream, std::string const &path)
std::pair< Source *, bool > find (std::string path)
Source * find_one_deep (std::string const &name)
PropertyStream::Source * find_path (std::string path)
PropertyStream::Source * find_one (std::string const &name)
virtual void onWrite (Map &)
Static Public Member Functions
static Manager * New (Stoppable &parent, SiteFiles::Manager &siteFiles, beast::File const &pathToDbFileOrDirectory, Callback &callback, clock_type &clock, beast::Journal journal)
Static Public Member Functions inherited from beast::PropertyStream::Source
static bool peel_leading_slash (std::string *path)
static bool peel_trailing_slashstar (std::string *path)
static std::string peel_name (std::string *path)
Protected Member Functions
Manager (Stoppable &parent)
Protected Member Functions inherited from beast::Stoppable
Stoppable (char const *name, RootStoppable &root)
Additional Inherited Members
Protected Attributes inherited from beast::Stoppable
char const * m_name
RootStoppable & m_root
Child m_child
Atomic< int > m_started
bool volatile m_stopped
bool volatile m_childrenStopped
Children m_children
WaitableEvent m_stoppedEvent
Detailed Description
Maintains a set of IP addresses used for getting into the network.
Definition at line 35 of file Manager.h.
Constructor & Destructor Documentation
ripple::PeerFinder::Manager::Manager (Stoppable & parent) explicit protected
Definition at line 307 of file Manager.cpp.
     : Stoppable ("PeerFinder", parent)
     , beast::PropertyStream::Source ("peerfinder")
 {
 }
virtual ripple::PeerFinder::Manager::~Manager () inline virtual
Destroy the object. Any pending source fetch operations are aborted. There may be some listener calls made before the destructor returns.
Definition at line 57 of file Manager.h.
 { }
Member Function Documentation
virtual void ripple::PeerFinder::Manager::addFallbackStrings (std::string const & name, std::vector< std::string > const & strings) pure virtual
Add a set of strings as fallback IP::Endpoint sources.
Parameters
name A label used for diagnostics.
Implemented in ripple::PeerFinder::ManagerImp.
virtual void ripple::PeerFinder::Manager::addFixedPeer (std::string const & name, std::vector< beast::IP::Endpoint > const & addresses) pure virtual
Add a peer that should always be connected. This is useful for maintaining a private cluster of peers. The string is the name as specified in the configuration file, along with the set of corresponding IP addresses.
Implemented in ripple::PeerFinder::ManagerImp.
Manager * ripple::PeerFinder::Manager::New (Stoppable & parent, SiteFiles::Manager & siteFiles, beast::File const & pathToDbFileOrDirectory, Callback & callback, clock_type & clock, beast::Journal journal) static
Create a new Manager.
Definition at line 313 of file Manager.cpp.
 {
     return new ManagerImp (parent, siteFiles, databaseFile,
         callback, clock, journal);
 }
virtual Slot::ptr ripple::PeerFinder::Manager::new_inbound_slot (beast::IP::Endpoint const & local_endpoint, beast::IP::Endpoint const & remote_endpoint) pure virtual
Add a URL as a fallback location to obtain IP::Endpoint sources.
Parameters
name A label used for diagnostics.Create a new inbound slot with the specified remote endpoint. If nullptr is returned, then the slot could not be assigned. Usually this is because of a detected self-connection.
Implemented in ripple::PeerFinder::ManagerImp.
virtual Slot::ptr ripple::PeerFinder::Manager::new_outbound_slot (beast::IP::Endpoint const & remote_endpoint) pure virtual
Create a new outbound slot with the specified remote endpoint. If nullptr is returned, then the slot could not be assigned. Usually this is because of a duplicate connection.
Implemented in ripple::PeerFinder::ManagerImp.
virtual void ripple::PeerFinder::Manager::on_cancel (Slot::ptr const & slot) pure virtual
Called when the slot is closed via canceling operations. This is instead of on_closed.
Implemented in ripple::PeerFinder::ManagerImp.
Referenced by ripple::PeerImp::detach().
virtual void ripple::PeerFinder::Manager::on_closed (Slot::ptr const & slot) pure virtual
Called when the slot is closed. This always happens when the socket is closed, unless the socket was canceled.
Implemented in ripple::PeerFinder::ManagerImp.
Referenced by ripple::PeerImp::detach().
virtual void ripple::PeerFinder::Manager::on_connected (Slot::ptr const & slot, beast::IP::Endpoint const & local_endpoint) pure virtual
Called when an outbound connection attempt succeeds. The local endpoint must be valid. If the caller receives an error when retrieving the local endpoint from the socket, it should proceed as if the connection attempt failed by calling on_closed instead of on_connected.
Implemented in ripple::PeerFinder::ManagerImp.
Referenced by ripple::PeerImp::onConnect().
virtual void ripple::PeerFinder::Manager::on_endpoints (Slot::ptr const & slot, Endpoints const & endpoints) pure virtual
Called when mtENDPOINTS is received.
Implemented in ripple::PeerFinder::ManagerImp.
Referenced by ripple::PeerImp::recvEndpoints().
virtual void ripple::PeerFinder::Manager::on_handshake (Slot::ptr const & slot, RipplePublicKey const & key, bool cluster) pure virtual
Called when a handshake is completed.
Implemented in ripple::PeerFinder::ManagerImp.
Referenced by ripple::PeerImp::recvHello().
virtual void ripple::PeerFinder::Manager::on_legacy_endpoints (IPAddresses const & addresses) pure virtual
Called when legacy IP/port addresses are received.
Implemented in ripple::PeerFinder::ManagerImp.
Referenced by ripple::PeerImp::recvPeers().
virtual void ripple::PeerFinder::Manager::setConfig (Config const & config) pure virtual
Set the configuration for the manager. The new settings will be applied asynchronously. Thread safety: Can be called from any threads at any time.
Implemented in ripple::PeerFinder::ManagerImp.
The documentation for this class was generated from the following files:
rippled/src/ripple/peerfinder/api/Manager.h
rippled/src/ripple/peerfinder/impl/Manager.cpp