rippled: ripple::RPCHTTPServerImp Class Reference
ripple::RPCHTTPServerImp Class Reference
Public Member Functions
RPCHTTPServerImp (Stoppable &parent, beast::Journal journal, JobQueue &jobQueue, NetworkOPs &networkOPs, Resource::Manager &resourceManager)
~RPCHTTPServerImp ()
void setup (beast::Journal journal)
void onStop ()
void onChildrenStopped ()
void onAccept (HTTP::Session &session)
void onHeaders (HTTP::Session &session)
void onRequest (HTTP::Session &session)
void onClose (HTTP::Session &session, int errorCode)
void onStopped (HTTP::Server &)
void processSession (Job &job, HTTP::Session &session)
std::string createResponse (int statusCode, std::string const &description)
bool isAuthorized (std::map< std::string, std::string > const &headers)
std::string processRequest (std::string const &request, beast::IP::Endpoint const &remoteIPAddress)
Public Member Functions inherited from ripple::RPCHTTPServer
virtual ~RPCHTTPServer ()
Public Member Functions inherited from beast::Stoppable
Stoppable (char const *name, Stoppable &parent)
virtual ~Stoppable ()
bool isStopping () const
bool isStopped () const
bool areChildrenStopped () const
void stopped ()
virtual void onPrepare ()
virtual void onStart ()
Public Attributes
Resource::Manager & m_resourceManager
beast::Journal m_journal
JobQueue & m_jobQueue
NetworkOPs & m_networkOPs
RPCServerHandler m_deprecatedHandler
HTTP::Server m_server
std::unique_ptr< RippleSSLContext > m_context
Additional Inherited Members
Static Public Member Functions inherited from ripple::RPCHTTPServer
static RPCHTTPServer * New (Stoppable &parent, beast::Journal journal, JobQueue &jobQueue, NetworkOPs &networkOPs, Resource::Manager &resourceManager)
Protected Member Functions inherited from ripple::RPCHTTPServer
RPCHTTPServer (Stoppable &parent)
Protected Attributes inherited from beast::Stoppable
char const * m_name
RootStoppable & m_root
Child m_child
Atomic< int > m_started
bool volatile m_stopped
bool volatile m_childrenStopped
Children m_children
WaitableEvent m_stoppedEvent
Detailed Description
Definition at line 24 of file RPCHTTPServer.cpp.
Constructor & Destructor Documentation
ripple::RPCHTTPServerImp::RPCHTTPServerImp (Stoppable & parent, beast::Journal journal, JobQueue & jobQueue, NetworkOPs & networkOPs, Resource::Manager & resourceManager) inline
Definition at line 38 of file RPCHTTPServer.cpp.
References ripple::RippleSSLContext::createAuthenticated(), ripple::RippleSSLContext::createBare(), ripple::getConfig(), and m_context.
         : RPCHTTPServer (parent)
         , m_resourceManager (resourceManager)
         , m_journal (journal)
         , m_jobQueue (jobQueue)
         , m_networkOPs (networkOPs)
         , m_deprecatedHandler (networkOPs, resourceManager)
         , m_server (*this, journal)
     {
         if (getConfig ().RPC_SECURE == 0)
         {
             m_context.reset (RippleSSLContext::createBare ());
         }
         else
         {
             m_context.reset (RippleSSLContext::createAuthenticated (
                 getConfig ().RPC_SSL_KEY,
                     getConfig ().RPC_SSL_CERT,
                         getConfig ().RPC_SSL_CHAIN));
         }
     }
ripple::RPCHTTPServerImp::~RPCHTTPServerImp () inline
Definition at line 64 of file RPCHTTPServer.cpp.
References m_server, and ripple::HTTP::Server::stop().
     {
         m_server.stop();
     }
Member Function Documentation
std::string ripple::RPCHTTPServerImp::createResponse (int statusCode, std::string const & description) inline
Definition at line 165 of file RPCHTTPServer.cpp.
References ripple::HTTPReply().
Referenced by processRequest().
     {
         return HTTPReply (statusCode, description);
     }
bool ripple::RPCHTTPServerImp::isAuthorized (std::map< std::string, std::string > const & headers) inline
Definition at line 172 of file RPCHTTPServer.cpp.
References ripple::HTTPAuthorized().
     {
         return HTTPAuthorized (headers);
     }
void ripple::RPCHTTPServerImp::onAccept (HTTP::Session & session) inline virtual
Called when the connection is accepted and we know remoteAddress.
Implements ripple::HTTP::Handler.
Definition at line 115 of file RPCHTTPServer.cpp.
References ripple::HTTP::Session::close(), ripple::getConfig(), beast::IP::is_loopback(), and ripple::HTTP::Session::remoteAddress().
     {
         // Reject non-loopback connections if RPC_ALLOW_REMOTE is not set
         if (! getConfig().RPC_ALLOW_REMOTE &&
             ! beast::IP::is_loopback (session.remoteAddress()))
         {
             session.close();
         }
     }
void ripple::RPCHTTPServerImp::onChildrenStopped () inline virtual
Override called when all children have stopped.
The call is made on an unspecified, implementation-specific thread. onStop and onChildrenStopped will never be called concurrently, across all Stoppable objects descended from the same root, inclusive of the root.
It is safe to call isStopping, isStopped, and areChildrenStopped from within this function; The values returned will always be valid and never change during the callback.
The default implementation does nothing.
Thread safety: May not block for long periods. Guaranteed only to be called once. Must be safe to call from any thread at any time.
Reimplemented from beast::Stoppable.
Definition at line 106 of file RPCHTTPServer.cpp.
     {
     }
void ripple::RPCHTTPServerImp::onClose (HTTP::Session & session, int errorCode) inline virtual
Called when the session ends. Guaranteed to be called once.
Parameters
errorCode Non zero for a failed connection.
Implements ripple::HTTP::Handler.
Definition at line 146 of file RPCHTTPServer.cpp.
     {
     }
void ripple::RPCHTTPServerImp::onHeaders (HTTP::Session & session) inline virtual
Called repeatedly as new HTTP headers are received. Guaranteed to be called at least once.
Implements ripple::HTTP::Handler.
Definition at line 125 of file RPCHTTPServer.cpp.
     {
     }
void ripple::RPCHTTPServerImp::onRequest (HTTP::Session & session) inline virtual
Called when we have the full Content-Body.
Implements ripple::HTTP::Handler.
Definition at line 129 of file RPCHTTPServer.cpp.
References ripple::JobQueue::addJob(), ripple::HTTP::Session::detach(), ripple::jtRPC, m_jobQueue, and processSession().
     {
 #if 0
         Job job;
         processSession (job, session);
 #else
         session.detach();
         // The "boost::"'s are a workaround for broken versions of tr1::functional that
         // require the reference wrapper to be callable. HTTP::Session has abstract functions
         // and so references to it are not callable.
         m_jobQueue.addJob (jtRPC, "RPC", boost::bind (
             &RPCHTTPServerImp::processSession, this, boost::_1,
                 boost::ref (session)));
 #endif
     }
void ripple::RPCHTTPServerImp::onStop () inline virtual
Override called when the stop notification is issued.
The call is made on an unspecified, implementation-specific thread. onStop and onChildrenStopped will never be called concurrently, across all Stoppable objects descended from the same root, inclusive of the root.
It is safe to call isStopping, isStopped, and areChildrenStopped from within this function; The values returned will always be valid and never change during the callback.
The default implementation simply calls stopped(). This is applicable when the Stoppable has a trivial stop operation (or no stop operation), and we are merely using the Stoppable API to position it as a dependency of some parent service.
Thread safety: May not block for long periods. Guaranteed only to be called once. Must be safe to call from any thread at any time.
Reimplemented from beast::Stoppable.
Definition at line 101 of file RPCHTTPServer.cpp.
References m_server, and ripple::HTTP::Server::stopAsync().
     {
         m_server.stopAsync();
     }
void ripple::RPCHTTPServerImp::onStopped (HTTP::Server & server) inline virtual
Called when the server has finished its stop.
Implements ripple::HTTP::Handler.
Definition at line 150 of file RPCHTTPServer.cpp.
References beast::Stoppable::stopped().
     {
         stopped();
     }
std::string ripple::RPCHTTPServerImp::processRequest (std::string const & request, beast::IP::Endpoint const & remoteIPAddress) inline
Definition at line 179 of file RPCHTTPServer.cpp.
References ripple::Config::ADMIN, Json::arrayValue, Json::Value::asString(), ripple::Resource::Consumer::charge(), createResponse(), beast::Journal::debug, ripple::Resource::Consumer::disconnect(), ripple::RPCHandler::doRpcCommand(), ripple::Resource::feeReferenceRPC, ripple::Config::FORBID, ripple::getApp(), ripple::getConfig(), ripple::HTTPReply(), Json::Value::isArray(), Json::Value::isNull(), Json::Value::isObject(), Json::Value::isString(), ripple::JSONRPCReply(), m_journal, m_networkOPs, m_resourceManager, ripple::Resource::Manager::newAdminEndpoint(), ripple::Resource::Manager::newInboundEndpoint(), Json::Reader::parse(), beast::IP::Endpoint::to_string(), usage(), and rocksdb::crc32c::Value().
     {
         Json::Value jvRequest;
         {
             Json::Reader reader;
             if ((request.size () > 1000000) ||
                 ! reader.parse (request, jvRequest) ||
                 jvRequest.isNull () ||
                 ! jvRequest.isObject ())
             {
                 return createResponse (400, "Unable to parse request");
             }
         }
         Config::Role const role (getConfig ().getAdminRole (jvRequest, remoteIPAddress));
         Resource::Consumer usage;
         if (role == Config::ADMIN)
             usage = m_resourceManager.newAdminEndpoint (remoteIPAddress.to_string());
         else
             usage = m_resourceManager.newInboundEndpoint(remoteIPAddress);
         if (usage.disconnect ())
             return createResponse (503, "Server is overloaded");
         // Parse id now so errors from here on will have the id
         //
         // VFALCO NOTE Except that "id" isn't included in the following errors...
         //
         Json::Value const id = jvRequest ["id"];
         Json::Value const method = jvRequest ["method"];
         if (method.isNull ())
         {
             return createResponse (400, "Null method");
         }
         else if (! method.isString ())
         {
             return createResponse (400, "method is not string");
         }
         std::string strMethod = method.asString ();
         // Parse params
         Json::Value params = jvRequest ["params"];
         if (params.isNull ())
         {
             params = Json::Value (Json::arrayValue);
         }
         else if (!params.isArray ())
         {
             return HTTPReply (400, "params unparseable");
         }
         // VFALCO TODO Shouldn't we handle this earlier?
         //
         if (role == Config::FORBID)
         {
             // VFALCO TODO Needs implementing
             // FIXME Needs implementing
             // XXX This needs rate limiting to prevent brute forcing password.
             return HTTPReply (403, "Forbidden");
         }
         // This code does all the work on the io_service thread and
         // has no rate-limiting based on source IP or anything.
         // This is a temporary safety
         if ((role != Config::ADMIN) && (getApp().getFeeTrack().isLoadedLocal()))
         {
             return HTTPReply (503, "Unable to service at this time");
         }
         std::string response;
         m_journal.debug << "Query: " << strMethod << params;
         RPCHandler rpcHandler (&m_networkOPs);
         Resource::Charge loadType = Resource::feeReferenceRPC;
         Json::Value const result (rpcHandler.doRpcCommand (
             strMethod, params, role, loadType));
         usage.charge (loadType);
         m_journal.debug << "Reply: " << result;
         response = JSONRPCReply (result, Json::Value (), id);
         return createResponse (200, response);
     }
void ripple::RPCHTTPServerImp::processSession (Job & job, HTTP::Session & session) inline
Definition at line 157 of file RPCHTTPServer.cpp.
References beast::IP::Endpoint::at_port(), ripple::HTTP::Session::close(), ripple::HTTP::Session::content(), m_deprecatedHandler, ripple::RPCServerHandler::processRequest(), ripple::HTTP::Session::remoteAddress(), and ripple::HTTP::Session::write().
Referenced by onRequest().
     {
         session.write (m_deprecatedHandler.processRequest (
             session.content(), session.remoteAddress().at_port(0)));
         session.close();
     }
void ripple::RPCHTTPServerImp::setup (beast::Journal journal) inline virtual
Opens listening ports based on the Config settings.
Implements ripple::RPCHTTPServer.
Definition at line 69 of file RPCHTTPServer.cpp.
References ripple::HTTP::Port::addr, beast::IP::Endpoint::at_port(), ripple::HTTP::Port::context, beast::IP::Endpoint::from_string(), ripple::getConfig(), ripple::Config::getRpcPort(), beast::Journal::info, beast::IP::is_unspecified(), m_context, m_server, ripple::HTTP::Port::port, beast::IP::Endpoint::port(), and ripple::HTTP::Server::setPorts().
     {
         if (! getConfig ().getRpcIP().empty () &&
               getConfig ().getRpcPort() != 0)
         {
             beast::IP::Endpoint ep (beast::IP::Endpoint::from_string (getConfig().getRpcIP()));
             if (! is_unspecified (ep))
             {
                 HTTP::Port port;
                 port.addr = ep.at_port(0);
                 if (getConfig ().getRpcPort() != 0)
                     port.port = getConfig ().getRpcPort();
                 else
                     port.port = ep.port();
                 port.context = m_context.get ();
                 HTTP::Ports ports;
                 ports.push_back (port);
                 m_server.setPorts (ports);
             }
         }
         else
         {
             journal.info << "RPC interface: disabled";
         }
     }
Member Data Documentation
std::unique_ptr<RippleSSLContext> ripple::RPCHTTPServerImp::m_context
Definition at line 36 of file RPCHTTPServer.cpp.
Referenced by RPCHTTPServerImp(), and setup().
RPCServerHandler ripple::RPCHTTPServerImp::m_deprecatedHandler
Definition at line 34 of file RPCHTTPServer.cpp.
Referenced by processSession().
JobQueue& ripple::RPCHTTPServerImp::m_jobQueue
Definition at line 32 of file RPCHTTPServer.cpp.
Referenced by onRequest().
beast::Journal ripple::RPCHTTPServerImp::m_journal
Definition at line 31 of file RPCHTTPServer.cpp.
Referenced by processRequest().
NetworkOPs& ripple::RPCHTTPServerImp::m_networkOPs
Definition at line 33 of file RPCHTTPServer.cpp.
Referenced by processRequest().
Resource::Manager& ripple::RPCHTTPServerImp::m_resourceManager
Definition at line 30 of file RPCHTTPServer.cpp.
Referenced by processRequest().
HTTP::Server ripple::RPCHTTPServerImp::m_server
Definition at line 35 of file RPCHTTPServer.cpp.
Referenced by onStop(), setup(), and ~RPCHTTPServerImp().
The documentation for this class was generated from the following file:
rippled/src/ripple_app/main/RPCHTTPServer.cpp