rippled: rocksdb::log Namespace Reference
rocksdb::log Namespace Reference
Classes
class Reader
class LogTest
class Writer
Enumerations
enum RecordType {
kZeroType = 0, kFullType = 1, kFirstType = 2, kMiddleType = 3,
kLastType = 4
}
Functions
static std::string BigString (const std::string &partial_string, size_t n)
static std::string NumberString (int n)
static std::string RandomSkewedString (int i, Random *rnd)
TEST (LogTest, Empty)
TEST (LogTest, ReadWrite)
TEST (LogTest, ManyBlocks)
TEST (LogTest, Fragmentation)
TEST (LogTest, MarginalTrailer)
TEST (LogTest, MarginalTrailer2)
TEST (LogTest, ShortTrailer)
TEST (LogTest, AlignedEof)
TEST (LogTest, RandomRead)
TEST (LogTest, ReadError)
TEST (LogTest, BadRecordType)
TEST (LogTest, TruncatedTrailingRecord)
TEST (LogTest, BadLength)
TEST (LogTest, ChecksumMismatch)
TEST (LogTest, UnexpectedMiddleType)
TEST (LogTest, UnexpectedLastType)
TEST (LogTest, UnexpectedFullType)
TEST (LogTest, UnexpectedFirstType)
TEST (LogTest, ErrorJoinsRecords)
TEST (LogTest, ReadStart)
TEST (LogTest, ReadSecondOneOff)
TEST (LogTest, ReadSecondTenThousand)
TEST (LogTest, ReadSecondStart)
TEST (LogTest, ReadThirdOneOff)
TEST (LogTest, ReadThirdStart)
TEST (LogTest, ReadFourthOneOff)
TEST (LogTest, ReadFourthFirstBlockTrailer)
TEST (LogTest, ReadFourthMiddleBlock)
TEST (LogTest, ReadFourthLastBlock)
TEST (LogTest, ReadFourthStart)
TEST (LogTest, ReadEnd)
TEST (LogTest, ReadPastEnd)
Variables
static const int kMaxRecordType = kLastType
static const unsigned int kBlockSize = 32768
static const int kHeaderSize = 4 + 1 + 2
Enumeration Type Documentation
enum rocksdb::log::RecordType
Enumerator
kZeroType
kFullType
kFirstType
kMiddleType
kLastType
Definition at line 17 of file log_format.h.
                 {
   // Zero is reserved for preallocated files
   kZeroType = 0,
   kFullType = 1,
   // For fragments
   kFirstType = 2,
   kMiddleType = 3,
   kLastType = 4
 };
Function Documentation
static std::string rocksdb::log::BigString (const std::string & partial_string, size_t n) static
Definition at line 23 of file log_test.cc.
Referenced by RandomSkewedString(), and TEST().
{
   std::string result;
   while (result.size() < n) {
     result.append(partial_string);
   }
   result.resize(n);
   return result;
 }
static std::string rocksdb::log::NumberString (int n) static
Definition at line 33 of file log_test.cc.
Referenced by RandomSkewedString(), and TEST().
{
   char buf[50];
   snprintf(buf, sizeof(buf), "%d.", n);
   return std::string(buf);
 }
static std::string rocksdb::log::RandomSkewedString (int i, Random * rnd) static
Definition at line 40 of file log_test.cc.
References BigString(), NumberString(), and rocksdb::Random::Skewed().
Referenced by TEST().
{
   return BigString(NumberString(i), rnd->Skewed(17));
 }
rocksdb::log::TEST (LogTest , Empty)
Definition at line 266 of file log_test.cc.
References ASSERT_EQ.
                      {
   ASSERT_EQ("EOF", Read());
 }
rocksdb::log::TEST (LogTest , ReadWrite)
Definition at line 270 of file log_test.cc.
References ASSERT_EQ.
{
   Write("foo");
   Write("bar");
   Write("");
   Write("xxxx");
   ASSERT_EQ("foo", Read());
   ASSERT_EQ("bar", Read());
   ASSERT_EQ("", Read());
   ASSERT_EQ("xxxx", Read());
   ASSERT_EQ("EOF", Read());
   ASSERT_EQ("EOF", Read());  // Make sure reads at eof work
 }
rocksdb::log::TEST (LogTest , ManyBlocks)
Definition at line 283 of file log_test.cc.
References ASSERT_EQ, and NumberString().
{
   for (int i = 0; i < 100000; i++) {
     Write(NumberString(i));
   }
   for (int i = 0; i < 100000; i++) {
     ASSERT_EQ(NumberString(i), Read());
   }
   ASSERT_EQ("EOF", Read());
 }
rocksdb::log::TEST (LogTest , Fragmentation)
Definition at line 293 of file log_test.cc.
References ASSERT_EQ, and BigString().
{
   Write("small");
   Write(BigString("medium", 50000));
   Write(BigString("large", 100000));
   ASSERT_EQ("small", Read());
   ASSERT_EQ(BigString("medium", 50000), Read());
   ASSERT_EQ(BigString("large", 100000), Read());
   ASSERT_EQ("EOF", Read());
 }
rocksdb::log::TEST (LogTest , MarginalTrailer)
Definition at line 303 of file log_test.cc.
References ASSERT_EQ, BigString(), kBlockSize, and kHeaderSize.
{
   // Make a trailer that is exactly the same length as an empty record.
   const int n = kBlockSize - 2*kHeaderSize;
   Write(BigString("foo", n));
   ASSERT_EQ((unsigned int)(kBlockSize - kHeaderSize), WrittenBytes());
   Write("");
   Write("bar");
   ASSERT_EQ(BigString("foo", n), Read());
   ASSERT_EQ("", Read());
   ASSERT_EQ("bar", Read());
   ASSERT_EQ("EOF", Read());
 }
rocksdb::log::TEST (LogTest , MarginalTrailer2)
Definition at line 316 of file log_test.cc.
References ASSERT_EQ, BigString(), kBlockSize, and kHeaderSize.
{
   // Make a trailer that is exactly the same length as an empty record.
   const int n = kBlockSize - 2*kHeaderSize;
   Write(BigString("foo", n));
   ASSERT_EQ((unsigned int)(kBlockSize - kHeaderSize), WrittenBytes());
   Write("bar");
   ASSERT_EQ(BigString("foo", n), Read());
   ASSERT_EQ("bar", Read());
   ASSERT_EQ("EOF", Read());
   ASSERT_EQ(0U, DroppedBytes());
   ASSERT_EQ("", ReportMessage());
 }
rocksdb::log::TEST (LogTest , ShortTrailer)
Definition at line 329 of file log_test.cc.
References ASSERT_EQ, BigString(), kBlockSize, and kHeaderSize.
{
   const int n = kBlockSize - 2*kHeaderSize + 4;
   Write(BigString("foo", n));
   ASSERT_EQ((unsigned int)(kBlockSize - kHeaderSize + 4), WrittenBytes());
   Write("");
   Write("bar");
   ASSERT_EQ(BigString("foo", n), Read());
   ASSERT_EQ("", Read());
   ASSERT_EQ("bar", Read());
   ASSERT_EQ("EOF", Read());
 }
rocksdb::log::TEST (LogTest , AlignedEof)
Definition at line 341 of file log_test.cc.
References ASSERT_EQ, BigString(), kBlockSize, and kHeaderSize.
{
   const int n = kBlockSize - 2*kHeaderSize + 4;
   Write(BigString("foo", n));
   ASSERT_EQ((unsigned int)(kBlockSize - kHeaderSize + 4), WrittenBytes());
   ASSERT_EQ(BigString("foo", n), Read());
   ASSERT_EQ("EOF", Read());
 }
rocksdb::log::TEST (LogTest , RandomRead)
Definition at line 349 of file log_test.cc.
References ASSERT_EQ, and RandomSkewedString().
{
   const int N = 500;
   Random write_rnd(301);
   for (int i = 0; i < N; i++) {
     Write(RandomSkewedString(i, &write_rnd));
   }
   Random read_rnd(301);
   for (int i = 0; i < N; i++) {
     ASSERT_EQ(RandomSkewedString(i, &read_rnd), Read());
   }
   ASSERT_EQ("EOF", Read());
 }
rocksdb::log::TEST (LogTest , ReadError)
Definition at line 364 of file log_test.cc.
References ASSERT_EQ, and kBlockSize.
{
   Write("foo");
   ForceError();
   ASSERT_EQ("EOF", Read());
   ASSERT_EQ((unsigned int)kBlockSize, DroppedBytes());
   ASSERT_EQ("OK", MatchError("read error"));
 }
rocksdb::log::TEST (LogTest , BadRecordType)
Definition at line 372 of file log_test.cc.
References ASSERT_EQ.
{
   Write("foo");
   // Type is stored in header[6]
   IncrementByte(6, 100);
   FixChecksum(0, 3);
   ASSERT_EQ("EOF", Read());
   ASSERT_EQ(3U, DroppedBytes());
   ASSERT_EQ("OK", MatchError("unknown record type"));
 }
rocksdb::log::TEST (LogTest , TruncatedTrailingRecord)
Definition at line 382 of file log_test.cc.
References ASSERT_EQ, and kHeaderSize.
{
   Write("foo");
   ShrinkSize(4);   // Drop all payload as well as a header byte
   ASSERT_EQ("EOF", Read());
   ASSERT_EQ((unsigned int)(kHeaderSize - 1), DroppedBytes());
   ASSERT_EQ("OK", MatchError("truncated record at end of file"));
 }
rocksdb::log::TEST (LogTest , BadLength)
Definition at line 390 of file log_test.cc.
References ASSERT_EQ, and kHeaderSize.
{
   Write("foo");
   ShrinkSize(1);
   ASSERT_EQ("EOF", Read());
   ASSERT_EQ((unsigned int)(kHeaderSize + 2), DroppedBytes());
   ASSERT_EQ("OK", MatchError("bad record length"));
 }
rocksdb::log::TEST (LogTest , ChecksumMismatch)
Definition at line 398 of file log_test.cc.
References ASSERT_EQ.
{
   Write("foo");
   IncrementByte(0, 10);
   ASSERT_EQ("EOF", Read());
   ASSERT_EQ(10U, DroppedBytes());
   ASSERT_EQ("OK", MatchError("checksum mismatch"));
 }
rocksdb::log::TEST (LogTest , UnexpectedMiddleType)
Definition at line 406 of file log_test.cc.
References ASSERT_EQ, and kMiddleType.
{
   Write("foo");
   SetByte(6, kMiddleType);
   FixChecksum(0, 3);
   ASSERT_EQ("EOF", Read());
   ASSERT_EQ(3U, DroppedBytes());
   ASSERT_EQ("OK", MatchError("missing start"));
 }
rocksdb::log::TEST (LogTest , UnexpectedLastType)
Definition at line 415 of file log_test.cc.
References ASSERT_EQ, and kLastType.
{
   Write("foo");
   SetByte(6, kLastType);
   FixChecksum(0, 3);
   ASSERT_EQ("EOF", Read());
   ASSERT_EQ(3U, DroppedBytes());
   ASSERT_EQ("OK", MatchError("missing start"));
 }
rocksdb::log::TEST (LogTest , UnexpectedFullType)
Definition at line 424 of file log_test.cc.
References ASSERT_EQ, and kFirstType.
{
   Write("foo");
   Write("bar");
   SetByte(6, kFirstType);
   FixChecksum(0, 3);
   ASSERT_EQ("bar", Read());
   ASSERT_EQ("EOF", Read());
   ASSERT_EQ(3U, DroppedBytes());
   ASSERT_EQ("OK", MatchError("partial record without end"));
 }
rocksdb::log::TEST (LogTest , UnexpectedFirstType)
Definition at line 435 of file log_test.cc.
References ASSERT_EQ, BigString(), and kFirstType.
{
   Write("foo");
   Write(BigString("bar", 100000));
   SetByte(6, kFirstType);
   FixChecksum(0, 3);
   ASSERT_EQ(BigString("bar", 100000), Read());
   ASSERT_EQ("EOF", Read());
   ASSERT_EQ(3U, DroppedBytes());
   ASSERT_EQ("OK", MatchError("partial record without end"));
 }
rocksdb::log::TEST (LogTest , ErrorJoinsRecords)
Definition at line 446 of file log_test.cc.
References ASSERT_EQ, ASSERT_GE, ASSERT_LE, BigString(), and kBlockSize.
{
   // Consider two fragmented records:
   //    first(R1) last(R1) first(R2) last(R2)
   // where the middle two fragments disappear.  We do not want
   // first(R1),last(R2) to get joined and returned as a valid record.
   // Write records that span two blocks
   Write(BigString("foo", kBlockSize));
   Write(BigString("bar", kBlockSize));
   Write("correct");
   // Wipe the middle block
   for (unsigned int offset = kBlockSize; offset < 2*kBlockSize; offset++) {
     SetByte(offset, 'x');
   }
   ASSERT_EQ("correct", Read());
   ASSERT_EQ("EOF", Read());
   const unsigned int dropped = DroppedBytes();
   ASSERT_LE(dropped, 2*kBlockSize + 100);
   ASSERT_GE(dropped, 2*kBlockSize);
 }
rocksdb::log::TEST (LogTest , ReadStart)
Definition at line 469 of file log_test.cc.
{
   CheckInitialOffsetRecord(0, 0);
 }
rocksdb::log::TEST (LogTest , ReadSecondOneOff)
Definition at line 473 of file log_test.cc.
{
   CheckInitialOffsetRecord(1, 1);
 }
rocksdb::log::TEST (LogTest , ReadSecondTenThousand)
Definition at line 477 of file log_test.cc.
{
   CheckInitialOffsetRecord(10000, 1);
 }
rocksdb::log::TEST (LogTest , ReadSecondStart)
Definition at line 481 of file log_test.cc.
{
   CheckInitialOffsetRecord(10007, 1);
 }
rocksdb::log::TEST (LogTest , ReadThirdOneOff)
Definition at line 485 of file log_test.cc.
{
   CheckInitialOffsetRecord(10008, 2);
 }
rocksdb::log::TEST (LogTest , ReadThirdStart)
Definition at line 489 of file log_test.cc.
{
   CheckInitialOffsetRecord(20014, 2);
 }
rocksdb::log::TEST (LogTest , ReadFourthOneOff)
Definition at line 493 of file log_test.cc.
{
   CheckInitialOffsetRecord(20015, 3);
 }
rocksdb::log::TEST (LogTest , ReadFourthFirstBlockTrailer)
Definition at line 497 of file log_test.cc.
References kBlockSize.
{
   CheckInitialOffsetRecord(log::kBlockSize - 4, 3);
 }
rocksdb::log::TEST (LogTest , ReadFourthMiddleBlock)
Definition at line 501 of file log_test.cc.
References kBlockSize.
{
   CheckInitialOffsetRecord(log::kBlockSize + 1, 3);
 }
rocksdb::log::TEST (LogTest , ReadFourthLastBlock)
Definition at line 505 of file log_test.cc.
References kBlockSize.
{
   CheckInitialOffsetRecord(2 * log::kBlockSize + 1, 3);
 }
rocksdb::log::TEST (LogTest , ReadFourthStart)
Definition at line 509 of file log_test.cc.
References kBlockSize, and kHeaderSize.
{
   CheckInitialOffsetRecord(
       2 * (kHeaderSize + 1000) + (2 * log::kBlockSize - 1000) + 3 * kHeaderSize,
       3);
 }
rocksdb::log::TEST (LogTest , ReadEnd)
Definition at line 515 of file log_test.cc.
{
   CheckOffsetPastEndReturnsNoRecords(0);
 }
rocksdb::log::TEST (LogTest , ReadPastEnd)
Definition at line 519 of file log_test.cc.
{
   CheckOffsetPastEndReturnsNoRecords(5);
 }
Variable Documentation
const unsigned int rocksdb::log::kBlockSize = 32768 static
Definition at line 30 of file log_format.h.
Referenced by rocksdb::log::Writer::AddRecord(), rocksdb::log::Writer::EmitPhysicalRecord(), rocksdb::log::Reader::ReadPhysicalRecord(), rocksdb::log::Reader::SkipToInitialBlock(), rocksdb::TEST(), and TEST().
const int rocksdb::log::kHeaderSize = 4 + 1 + 2 static
Definition at line 33 of file log_format.h.
Referenced by rocksdb::log::Writer::AddRecord(), rocksdb::log::Writer::EmitPhysicalRecord(), rocksdb::log::Reader::ReadPhysicalRecord(), and TEST().
const int rocksdb::log::kMaxRecordType = kLastType static
Definition at line 28 of file log_format.h.
Referenced by rocksdb::log::Writer::Writer().