rippled: beast::DynamicLibrary Class Reference
beast::DynamicLibrary Class Reference
#include <DynamicLibrary.h>
Public Member Functions
DynamicLibrary () noexcept
DynamicLibrary (const String &name)
~DynamicLibrary ()
bool open (const String &name)
void close ()
void * getFunction (const String &functionName) noexcept
void * getNativeHandle () const noexcept
Private Attributes
void * handle
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
Handles the opening and closing of DLLs.
This class can be used to open a DLL and get some function pointers from it. Since the DLL is freed when this object is deleted, it's handy for managing library lifetimes using RAII.
Definition at line 37 of file DynamicLibrary.h.
Constructor & Destructor Documentation
beast::DynamicLibrary::DynamicLibrary () inline noexcept
Creates an unopened DynamicLibrary object. Call open() to actually open one.
Definition at line 43 of file DynamicLibrary.h.
 : handle (nullptr) {}
beast::DynamicLibrary::DynamicLibrary (const String & name) inline
Definition at line 47 of file DynamicLibrary.h.
References open().
 : handle (nullptr) { open (name); }
beast::DynamicLibrary::~DynamicLibrary () inline
Destructor. If a library is currently open, it will be closed when this object is destroyed.
Definition at line 52 of file DynamicLibrary.h.
References close().
 { close(); }
Member Function Documentation
void beast::DynamicLibrary::close ()
Releases the currently-open DLL, or has no effect if none was open.
Definition at line 735 of file posix_SharedCode.h.
References handle.
Referenced by open(), and ~DynamicLibrary().
 {
     if (handle != nullptr)
     {
         dlclose (handle);
         handle = nullptr;
     }
 }
void * beast::DynamicLibrary::getFunction (const String & functionName) noexcept
Tries to find a named function in the currently-open DLL, and returns a pointer to it. If no library is open, or if the function isn't found, this will return a null pointer.
Definition at line 744 of file posix_SharedCode.h.
 {
     return handle != nullptr ? dlsym (handle, functionName.toUTF8()) : nullptr;
 }
void* beast::DynamicLibrary::getNativeHandle () const inline noexcept
Returns the platform-specific native library handle. You'll need to cast this to whatever is appropriate for the OS that's in use.
Definition at line 74 of file DynamicLibrary.h.
References handle.
 { return handle; }
bool beast::DynamicLibrary::open (const String & name)
Opens a DLL. The name and the method by which it gets found is of course platform-specific, and may or may not include a path, depending on the OS. If a library is already open when this method is called, it will first close the library before attempting to load the new one.
Returns
true if the library was successfully found and opened.
Definition at line 728 of file posix_SharedCode.h.
References close(), beast::CharPointer_UTF8::getAddress(), handle, beast::String::isEmpty(), and beast::String::toUTF8().
Referenced by DynamicLibrary().
 {
     close();
     handle = dlopen (name.isEmpty() ? nullptr : name.toUTF8().getAddress(), RTLD_LOCAL | RTLD_NOW);
     return handle != nullptr;
 }
Member Data Documentation
void* beast::DynamicLibrary::handle private
Definition at line 77 of file DynamicLibrary.h.
Referenced by close(), getNativeHandle(), and open().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_core/threads/DynamicLibrary.h
rippled/src/beast/modules/beast_core/native/posix_SharedCode.h
rippled/src/beast/modules/beast_core/native/win32_Threads.cpp