rippled: rippled/src/beast/beast/crypto/impl/sha2/sha2.h File Reference
sha2.h File Reference
#include <sys/types.h>
Classes
struct _SHA512_CTX
Macros
#define SHA256_DIGEST_STRING_LENGTH (Sha256::digestLength * 2 + 1)
#define SHA384_BLOCK_LENGTH 128
#define SHA384_DIGEST_LENGTH 48
#define SHA384_DIGEST_STRING_LENGTH (SHA384_DIGEST_LENGTH * 2 + 1)
#define SHA512_BLOCK_LENGTH 128
#define SHA512_DIGEST_LENGTH 64
#define SHA512_DIGEST_STRING_LENGTH (SHA512_DIGEST_LENGTH * 2 + 1)
#define __SHA2_H__
#define SHA256_DIGEST_STRING_LENGTH (Sha256::digestLength * 2 + 1)
#define SHA384_BLOCK_LENGTH 128
#define SHA384_DIGEST_LENGTH 48
#define SHA384_DIGEST_STRING_LENGTH (SHA384_DIGEST_LENGTH * 2 + 1)
#define SHA512_BLOCK_LENGTH 128
#define SHA512_DIGEST_LENGTH 64
#define SHA512_DIGEST_STRING_LENGTH (SHA512_DIGEST_LENGTH * 2 + 1)
Typedefs
typedef struct _SHA512_CTX SHA512_CTX
typedef SHA512_CTX SHA384_CTX
Functions
void SHA256_Init (Sha256::detail::Context *)
void SHA256_Update (Sha256::detail::Context *, const std::uint8_t *, size_t)
void SHA256_Final (std::uint8_t[Sha256::digestLength], Sha256::detail::Context *)
char * SHA256_End (Sha256::detail::Context *, char[SHA256_DIGEST_STRING_LENGTH])
char * SHA256_Data (const std::uint8_t *, size_t, char[SHA256_DIGEST_STRING_LENGTH])
void SHA384_Init (SHA384_CTX *)
void SHA384_Update (SHA384_CTX *, const std::uint8_t *, size_t)
void SHA384_Final (std::uint8_t[SHA384_DIGEST_LENGTH], SHA384_CTX *)
char * SHA384_End (SHA384_CTX *, char[SHA384_DIGEST_STRING_LENGTH])
char * SHA384_Data (const std::uint8_t *, size_t, char[SHA384_DIGEST_STRING_LENGTH])
void SHA512_Init (SHA512_CTX *)
void SHA512_Update (SHA512_CTX *, const std::uint8_t *, size_t)
void SHA512_Final (std::uint8_t[SHA512_DIGEST_LENGTH], SHA512_CTX *)
char * SHA512_End (SHA512_CTX *, char[SHA512_DIGEST_STRING_LENGTH])
char * SHA512_Data (const std::uint8_t *, size_t, char[SHA512_DIGEST_STRING_LENGTH])
Macro Definition Documentation
#define __SHA2_H__
Definition at line 37 of file Sha256.cpp.
#define SHA256_DIGEST_STRING_LENGTH (Sha256::digestLength * 2 + 1)
Definition at line 52 of file Sha256.cpp.
#define SHA256_DIGEST_STRING_LENGTH (Sha256::digestLength * 2 + 1)
#define SHA384_BLOCK_LENGTH 128
Definition at line 53 of file Sha256.cpp.
Referenced by SHA384_Init().
#define SHA384_BLOCK_LENGTH 128
#define SHA384_DIGEST_LENGTH 48
#define SHA384_DIGEST_LENGTH 48
Definition at line 54 of file Sha256.cpp.
Referenced by SHA384_End(), and SHA384_Final().
#define SHA384_DIGEST_STRING_LENGTH (SHA384_DIGEST_LENGTH * 2 + 1)
Definition at line 55 of file Sha256.cpp.
#define SHA384_DIGEST_STRING_LENGTH (SHA384_DIGEST_LENGTH * 2 + 1)
#define SHA512_BLOCK_LENGTH 128
#define SHA512_BLOCK_LENGTH 128
Definition at line 56 of file Sha256.cpp.
Referenced by SHA512_Init(), SHA512_Last(), and SHA512_Update().
#define SHA512_DIGEST_LENGTH 64
#define SHA512_DIGEST_LENGTH 64
Definition at line 57 of file Sha256.cpp.
Referenced by SHA384_Init(), SHA512_End(), SHA512_Final(), and SHA512_Init().
#define SHA512_DIGEST_STRING_LENGTH (SHA512_DIGEST_LENGTH * 2 + 1)
#define SHA512_DIGEST_STRING_LENGTH (SHA512_DIGEST_LENGTH * 2 + 1)
Definition at line 58 of file Sha256.cpp.
Referenced by main().
Typedef Documentation
typedef SHA512_CTX SHA384_CTX
Definition at line 66 of file sha2.h.
typedef struct _SHA512_CTX SHA512_CTX
Function Documentation
char* SHA256_Data (const std::uint8_t * , size_t , char [SHA256_DIGEST_STRING_LENGTH])
Definition at line 643 of file sha2.c.
References SHA256_End(), SHA256_Init(), and SHA256_Update().
{
     Sha256::detail::Context context;
     SHA256_Init(&context);
     SHA256_Update(&context, data, len);
     return SHA256_End(&context, digest);
 }
char* SHA256_End (Sha256::detail::Context * , char [SHA256_DIGEST_STRING_LENGTH])
void SHA256_Final (std::uint8_t [Sha256::digestLength], Sha256::detail::Context *)
void SHA256_Init (Sha256::detail::Context *)
Definition at line 325 of file sha2.c.
References beast::Sha256::blockLength, beast::Sha256::digestLength, MEMCPY_BCOPY, MEMSET_BZERO, and sha256_initial_hash_value.
Referenced by main(), SHA256_Data(), and ripple::SHA256Hash().
{
     if (context == (Sha256::detail::Context*)0) {
         return;
     }
     MEMCPY_BCOPY(context->state, sha256_initial_hash_value, Sha256::digestLength);
     MEMSET_BZERO(context->buffer, Sha256::blockLength);
     context->bitcount = 0;
 }
void SHA256_Update (Sha256::detail::Context * , const std::uint8_t * , size_t)
Definition at line 509 of file sha2.c.
References beast::Sha256::blockLength, MEMCPY_BCOPY, and SHA256_Transform().
Referenced by main(), SHA256_Data(), and ripple::SHA256Hash().
{
     unsigned int    freespace, usedspace;
     if (len == 0) {
         /* Calling with no data is valid - we do nothing */
         return;
     }
     /* Sanity check: */
     assert(context != (Sha256::detail::Context*)0 && data != (sha2_byte*)0);
     usedspace = (context->bitcount >> 3) % Sha256::blockLength;
     if (usedspace > 0) {
         /* Calculate how much free space is available in the buffer */
         freespace = Sha256::blockLength - usedspace;
         if (len >= freespace) {
             /* Fill the buffer completely and process it */
             MEMCPY_BCOPY(&context->buffer[usedspace], data, freespace);
             context->bitcount += freespace << 3;
             len -= freespace;
             data += freespace;
             SHA256_Transform(context, (sha2_word32*)context->buffer);
         } else {
             /* The buffer is not yet full */
             MEMCPY_BCOPY(&context->buffer[usedspace], data, len);
             context->bitcount += len << 3;
             /* Clean up: */
             usedspace = freespace = 0;
             return;
         }
     }
     while (len >= Sha256::blockLength) {
         /* Process as many complete blocks as we can */
         SHA256_Transform(context, (sha2_word32*)data);
         context->bitcount += Sha256::blockLength << 3;
         len -= Sha256::blockLength;
         data += Sha256::blockLength;
     }
     if (len > 0) {
         /* There's left-overs, so save 'em */
         MEMCPY_BCOPY(context->buffer, data, len);
         context->bitcount += len << 3;
     }
     /* Clean up: */
     usedspace = freespace = 0;
 }
char* SHA384_Data (const std::uint8_t * , size_t , char [SHA384_DIGEST_STRING_LENGTH])
Definition at line 1047 of file sha2.c.
References SHA384_End(), SHA384_Init(), and SHA384_Update().
{
     SHA384_CTX  context;
     SHA384_Init(&context);
     SHA384_Update(&context, data, len);
     return SHA384_End(&context, digest);
 }
char* SHA384_End (SHA384_CTX * , char [SHA384_DIGEST_STRING_LENGTH])
void SHA384_Final (std::uint8_t [SHA384_DIGEST_LENGTH], SHA384_CTX *)
void SHA384_Init (SHA384_CTX *)
Definition at line 982 of file sha2.c.
References _SHA512_CTX::bitcount, _SHA512_CTX::buffer, MEMCPY_BCOPY, MEMSET_BZERO, SHA384_BLOCK_LENGTH, sha384_initial_hash_value, SHA512_DIGEST_LENGTH, and _SHA512_CTX::state.
Referenced by main(), and SHA384_Data().
{
     if (context == (SHA384_CTX*)0) {
         return;
     }
     MEMCPY_BCOPY(context->state, sha384_initial_hash_value, SHA512_DIGEST_LENGTH);
     MEMSET_BZERO(context->buffer, SHA384_BLOCK_LENGTH);
     context->bitcount[0] = context->bitcount[1] = 0;
 }
void SHA384_Update (SHA384_CTX * , const std::uint8_t * , size_t)
Definition at line 991 of file sha2.c.
References SHA512_Update().
Referenced by main(), and SHA384_Data().
{
     SHA512_Update((SHA512_CTX*)context, data, len);
 }
char* SHA512_Data (const std::uint8_t * , size_t , char [SHA512_DIGEST_STRING_LENGTH])
Definition at line 972 of file sha2.c.
References SHA512_End(), SHA512_Init(), and SHA512_Update().
{
     SHA512_CTX  context;
     SHA512_Init(&context);
     SHA512_Update(&context, data, len);
     return SHA512_End(&context, digest);
 }
char* SHA512_End (SHA512_CTX * , char [SHA512_DIGEST_STRING_LENGTH])
void SHA512_Final (std::uint8_t [SHA512_DIGEST_LENGTH], SHA512_CTX *)
void SHA512_Init (SHA512_CTX *)
Definition at line 653 of file sha2.c.
References _SHA512_CTX::bitcount, _SHA512_CTX::buffer, MEMCPY_BCOPY, MEMSET_BZERO, SHA512_BLOCK_LENGTH, SHA512_DIGEST_LENGTH, sha512_initial_hash_value, and _SHA512_CTX::state.
Referenced by ripple::Serializer::getPrefixHash(), main(), and SHA512_Data().
{
     if (context == (SHA512_CTX*)0) {
         return;
     }
     MEMCPY_BCOPY(context->state, sha512_initial_hash_value, SHA512_DIGEST_LENGTH);
     MEMSET_BZERO(context->buffer, SHA512_BLOCK_LENGTH);
     context->bitcount[0] = context->bitcount[1] =  0;
 }
void SHA512_Update (SHA512_CTX * , const std::uint8_t * , size_t)
Definition at line 831 of file sha2.c.
References ADDINC128, _SHA512_CTX::bitcount, _SHA512_CTX::buffer, MEMCPY_BCOPY, SHA512_BLOCK_LENGTH, and SHA512_Transform().
Referenced by ripple::Serializer::getPrefixHash(), main(), SHA384_Update(), and SHA512_Data().
{
     unsigned int    freespace, usedspace;
     if (len == 0) {
         /* Calling with no data is valid - we do nothing */
         return;
     }
     /* Sanity check: */
     assert(context != (SHA512_CTX*)0 && data != (sha2_byte*)0);
     usedspace = (context->bitcount[0] >> 3) % SHA512_BLOCK_LENGTH;
     if (usedspace > 0) {
         /* Calculate how much free space is available in the buffer */
         freespace = SHA512_BLOCK_LENGTH - usedspace;
         if (len >= freespace) {
             /* Fill the buffer completely and process it */
             MEMCPY_BCOPY(&context->buffer[usedspace], data, freespace);
             ADDINC128(context->bitcount, freespace << 3);
             len -= freespace;
             data += freespace;
             SHA512_Transform(context, (sha2_word64*)context->buffer);
         } else {
             /* The buffer is not yet full */
             MEMCPY_BCOPY(&context->buffer[usedspace], data, len);
             ADDINC128(context->bitcount, len << 3);
             /* Clean up: */
             usedspace = freespace = 0;
             return;
         }
     }
     while (len >= SHA512_BLOCK_LENGTH) {
         /* Process as many complete blocks as we can */
         SHA512_Transform(context, (sha2_word64*)data);
         ADDINC128(context->bitcount, SHA512_BLOCK_LENGTH << 3);
         len -= SHA512_BLOCK_LENGTH;
         data += SHA512_BLOCK_LENGTH;
     }
     if (len > 0) {
         /* There's left-overs, so save 'em */
         MEMCPY_BCOPY(context->buffer, data, len);
         ADDINC128(context->bitcount, len << 3);
     }
     /* Clean up: */
     usedspace = freespace = 0;
 }