rippled: ripple::PeerSet Class Reference
ripple::PeerSet Class Reference abstract
#include <PeerSet.h>
Public Types
typedef beast::abstract_clock
< std::chrono::seconds > clock_type
Public Member Functions
uint256 const & getHash () const
bool isComplete () const
bool isFailed () const
int getTimeouts () const
bool isActive ()
void progress ()
void clearProgress ()
bool isProgress ()
void touch ()
clock_type::time_point getLastAction () const
bool peerHas (Peer::ptr const &)
void peerHasVoid (Peer::ptr const &peer)
void badPeer (Peer::ptr const &)
void setTimer ()
std::size_t takePeerSetFrom (const PeerSet &s)
std::size_t getPeerCount () const
virtual bool isDone () const
Protected Types
typedef RippleRecursiveMutex LockType
typedef std::unique_lock
< LockType > ScopedLockType
typedef Peer::ShortId PeerIdentifier
typedef int ReceivedChunkCount
typedef ripple::unordered_map
< PeerIdentifier,
ReceivedChunkCount > PeerSetMap
Protected Member Functions
PeerSet (uint256 const &hash, int interval, bool txnData, clock_type &clock, beast::Journal journal)
virtual ~PeerSet ()=0
virtual void newPeer (Peer::ptr const &)=0
virtual void onTimer (bool progress, ScopedLockType &)=0
virtual boost::weak_ptr< PeerSet > pmDowncast ()=0
void setComplete ()
void setFailed ()
void invokeOnTimer ()
void sendRequest (const protocol::TMGetLedger &message)
void sendRequest (const protocol::TMGetLedger &message, Peer::ptr const &peer)
Protected Attributes
beast::Journal m_journal
clock_type & m_clock
LockType mLock
uint256 mHash
int mTimerInterval
int mTimeouts
bool mComplete
bool mFailed
bool mAggressive
bool mTxnData
clock_type::time_point mLastAction
bool mProgress
boost::asio::deadline_timer mTimer
PeerSetMap mPeers
Static Private Member Functions
static void TimerEntry (boost::weak_ptr< PeerSet >, const boost::system::error_code &result)
static void TimerJobEntry (Job &, boost::shared_ptr< PeerSet >)
Detailed Description
A set of peers used to acquire data.
A peer set is used to acquire a ledger or a transaction set.
Definition at line 31 of file PeerSet.h.
Member Typedef Documentation
typedef beast::abstract_clock<std::chrono::seconds> ripple::PeerSet::clock_type
Definition at line 34 of file PeerSet.h.
typedef RippleRecursiveMutex ripple::PeerSet::LockType protected
Definition at line 111 of file PeerSet.h.
typedef Peer::ShortId ripple::PeerSet::PeerIdentifier protected
Definition at line 156 of file PeerSet.h.
typedef ripple::unordered_map<PeerIdentifier, ReceivedChunkCount> ripple::PeerSet::PeerSetMap protected
Definition at line 158 of file PeerSet.h.
typedef int ripple::PeerSet::ReceivedChunkCount protected
Definition at line 157 of file PeerSet.h.
typedef std::unique_lock<LockType> ripple::PeerSet::ScopedLockType protected
Definition at line 112 of file PeerSet.h.
Constructor & Destructor Documentation
ripple::PeerSet::PeerSet (uint256 const & hash, int interval, bool txnData, clock_type & clock, beast::Journal journal) protected
Definition at line 33 of file PeerSet.cpp.
References m_clock, mLastAction, mTimerInterval, and beast::abstract_clock< Duration >::now().
     : m_journal (journal)
     , m_clock (clock)
     , mHash (hash)
     , mTimerInterval (interval)
     , mTimeouts (0)
     , mComplete (false)
     , mFailed (false)
     , mAggressive (false)
     , mTxnData (txnData)
     , mProgress (false)
     , mTimer (getApp().getIOService ())
 {
     mLastAction = m_clock.now();
     assert ((mTimerInterval > 10) && (mTimerInterval < 30000));
 }
ripple::PeerSet::~PeerSet () protected pure virtual
Definition at line 51 of file PeerSet.cpp.
 {
 }
Member Function Documentation
void ripple::PeerSet::badPeer (Peer::ptr const & ptr)
Definition at line 66 of file PeerSet.cpp.
References mLock, and mPeers.
 {
     ScopedLockType sl (mLock);
     mPeers.erase (ptr->getShortId ());
 }
void ripple::PeerSet::clearProgress () inline
Definition at line 64 of file PeerSet.h.
References mProgress.
Referenced by invokeOnTimer().
     {
         mProgress = false;
     }
uint256 const& ripple::PeerSet::getHash () const inline
Definition at line 36 of file PeerSet.h.
References mHash.
Referenced by ripple::InboundLedger::addPeers(), ripple::InboundLedger::init(), ripple::TransactionAcquire::onTimer(), and ripple::TransactionAcquire::takeNodes().
     {
         return mHash;
     }
clock_type::time_point ripple::PeerSet::getLastAction () const inline
Definition at line 79 of file PeerSet.h.
References mLastAction.
     {
         return mLastAction;
     }
std::size_t ripple::PeerSet::getPeerCount () const
Definition at line 187 of file PeerSet.cpp.
References ripple::getApp(), and mPeers.
Referenced by ripple::TransactionAcquire::onTimer(), and ripple::InboundLedger::onTimer().
 {
     std::size_t ret (0);
     for (auto const& p : mPeers)
     {
         if (getApp ().overlay ().findPeerByShortID (p.first))
             ++ret;
     }
     return ret;
 }
int ripple::PeerSet::getTimeouts () const inline
Definition at line 51 of file PeerSet.h.
References mTimeouts.
Referenced by ripple::InboundLedger::getJson(), ripple::TransactionAcquire::onTimer(), ripple::InboundLedger::onTimer(), ripple::TransactionAcquire::trigger(), and ripple::InboundLedger::trigger().
     {
         return mTimeouts;
     }
void ripple::PeerSet::invokeOnTimer () protected
Definition at line 78 of file PeerSet.cpp.
References clearProgress(), isDone(), isProgress(), ripple::lsWARNING, mHash, mLock, mPeers, mTimeouts, onTimer(), setTimer(), and WriteLog.
 {
     ScopedLockType sl (mLock);
     if (isDone ())
         return;
     if (!isProgress())
     {
         ++mTimeouts;
         WriteLog (lsWARNING, InboundLedger) << "Timeout(" << mTimeouts << ") pc=" << mPeers.size () << " acquiring " << mHash;
         onTimer (false, sl);
     }
     else
     {
         clearProgress ();
         onTimer (true, sl);
     }
     if (!isDone ())
         setTimer ();
 }
bool ripple::PeerSet::isActive ()
Definition at line 140 of file PeerSet.cpp.
References isDone(), and mLock.
 {
     ScopedLockType sl (mLock);
     return !isDone ();
 }
bool ripple::PeerSet::isComplete () const inline
Definition at line 41 of file PeerSet.h.
References mComplete.
Referenced by ripple::InboundLedger::done(), and ripple::InboundLedger::isDone().
     {
         return mComplete;
     }
virtual bool ripple::PeerSet::isDone () const inline virtual
Reimplemented in ripple::InboundLedger.
Definition at line 100 of file PeerSet.h.
References mComplete, and mFailed.
Referenced by invokeOnTimer(), and isActive().
     {
         return mComplete || mFailed;
     }
bool ripple::PeerSet::isFailed () const inline
Definition at line 46 of file PeerSet.h.
References mFailed.
Referenced by ripple::InboundLedger::done(), ripple::InboundLedger::init(), and ripple::InboundLedger::isDone().
     {
         return mFailed;
     }
bool ripple::PeerSet::isProgress () inline
Definition at line 69 of file PeerSet.h.
References mProgress.
Referenced by invokeOnTimer(), and ripple::InboundLedger::trigger().
     {
         return mProgress;
     }
virtual void ripple::PeerSet::newPeer (Peer::ptr const &) protected pure virtual
Implemented in ripple::InboundLedger, and ripple::TransactionAcquire.
Referenced by peerHas().
virtual void ripple::PeerSet::onTimer (bool progress, ScopedLockType &) protected pure virtual
Implemented in ripple::InboundLedger, and ripple::TransactionAcquire.
Referenced by invokeOnTimer().
bool ripple::PeerSet::peerHas (Peer::ptr const & ptr)
Definition at line 55 of file PeerSet.cpp.
References mLock, mPeers, and newPeer().
Referenced by ripple::InboundLedger::addPeers(), ripple::TransactionAcquire::onTimer(), and peerHasVoid().
 {
     ScopedLockType sl (mLock);
     if (!mPeers.insert (std::make_pair (ptr->getShortId (), 0)).second)
         return false;
     newPeer (ptr);
     return true;
 }
void ripple::PeerSet::peerHasVoid (Peer::ptr const & peer) inline
Definition at line 89 of file PeerSet.h.
References peerHas().
Referenced by ripple::LedgerConsensusImp::peerHasSet().
     {
         peerHas (peer);
     }
virtual boost::weak_ptr<PeerSet> ripple::PeerSet::pmDowncast () protected pure virtual
Implemented in ripple::InboundLedger, and ripple::TransactionAcquire.
Referenced by setTimer().
void ripple::PeerSet::progress () inline
Definition at line 58 of file PeerSet.h.
References mAggressive, and mProgress.
Referenced by ripple::InboundLedger::processData(), ripple::InboundLedger::takeAsNode(), ripple::InboundLedger::takeBase(), ripple::TransactionAcquire::takeNodes(), and ripple::InboundLedger::takeTxNode().
     {
         mProgress = true;
         mAggressive = false;
     }
void ripple::PeerSet::sendRequest (const protocol::TMGetLedger & message) protected
Definition at line 154 of file PeerSet.cpp.
References ripple::getApp(), mLock, and mPeers.
Referenced by sendRequest(), ripple::TransactionAcquire::trigger(), and ripple::InboundLedger::trigger().
 {
     ScopedLockType sl (mLock);
     if (mPeers.empty ())
         return;
     Message::pointer packet (
         boost::make_shared<Message> (tmGL, protocol::mtGET_LEDGER));
     for (auto const& p : mPeers)
     {
         Peer::ptr peer (getApp().overlay ().findPeerByShortID (p.first));
         if (peer)
             peer->sendPacket (packet, false);
     }
 }
void ripple::PeerSet::sendRequest (const protocol::TMGetLedger & message, Peer::ptr const & peer) protected
Definition at line 146 of file PeerSet.cpp.
References sendRequest().
 {
     if (!peer)
         sendRequest (tmGL);
     else
         peer->sendPacket (boost::make_shared<Message> (tmGL, protocol::mtGET_LEDGER), false);
 }
void ripple::PeerSet::setComplete () inline protected
Definition at line 122 of file PeerSet.h.
References mComplete.
     {
         mComplete = true;
     }
void ripple::PeerSet::setFailed () inline protected
Definition at line 126 of file PeerSet.h.
References mFailed.
Referenced by ripple::InboundLedger::onTimer().
     {
         mFailed = true;
     }
void ripple::PeerSet::setTimer ()
Definition at line 72 of file PeerSet.cpp.
References mTimer, mTimerInterval, pmDowncast(), and TimerEntry().
Referenced by ripple::InboundLedger::init(), and invokeOnTimer().
 {
     mTimer.expires_from_now (boost::posix_time::milliseconds (mTimerInterval));
     mTimer.async_wait (boost::bind (&PeerSet::TimerEntry, pmDowncast (), boost::asio::placeholders::error));
 }
std::size_t ripple::PeerSet::takePeerSetFrom (const PeerSet & s)
Definition at line 173 of file PeerSet.cpp.
References mPeers.
 {
     std::size_t ret = 0;
     mPeers.clear ();
     for (auto const& p : s.mPeers)
     {
         mPeers.insert (std::make_pair (p.first, 0));
         ++ret;
     }
     return ret;
 }
void ripple::PeerSet::TimerEntry (boost::weak_ptr< PeerSet > wptr, const boost::system::error_code & result) static private
Definition at line 101 of file PeerSet.cpp.
References ripple::JobQueue::addJob(), BIND_TYPE, ripple::getApp(), ripple::JobQueue::getJobCountTotal(), ripple::Application::getJobQueue(), ripple::jtLEDGER_DATA, ripple::jtTXN_DATA, ripple::lsDEBUG, P_1, TimerJobEntry(), and WriteLog.
Referenced by setTimer().
 {
     if (result == boost::asio::error::operation_aborted)
         return;
     boost::shared_ptr<PeerSet> ptr = wptr.lock ();
     if (ptr)
     {
         // VFALCO NOTE So this function is really two different functions depending on
         //             the value of mTxnData, which is directly tied to whether we are
         //             a base class of IncomingLedger or TransactionAcquire
         //
         if (ptr->mTxnData)
         {
             getApp().getJobQueue ().addJob (jtTXN_DATA, "timerEntryTxn",
                 BIND_TYPE (&PeerSet::TimerJobEntry, P_1, ptr));
         }
         else
         {
             int jc = getApp().getJobQueue ().getJobCountTotal (jtLEDGER_DATA);
             if (jc > 4)
             {
                 WriteLog (lsDEBUG, InboundLedger) << "Deferring PeerSet timer due to load";
                 ptr->setTimer ();
             }
             else
                 getApp().getJobQueue ().addJob (jtLEDGER_DATA, "timerEntryLgr",
                     BIND_TYPE (&PeerSet::TimerJobEntry, P_1, ptr));
     }
     }
 }
void ripple::PeerSet::TimerJobEntry (Job & , boost::shared_ptr< PeerSet > ptr) static private
Definition at line 135 of file PeerSet.cpp.
Referenced by TimerEntry().
 {
     ptr->invokeOnTimer ();
 }
void ripple::PeerSet::touch () inline
Definition at line 74 of file PeerSet.h.
References m_clock, mLastAction, and beast::abstract_clock< Duration >::now().
Referenced by ripple::InboundLedger::done().
     {
         mLastAction = m_clock.now();
     }
Member Data Documentation
clock_type& ripple::PeerSet::m_clock protected
Definition at line 137 of file PeerSet.h.
Referenced by PeerSet(), and touch().
beast::Journal ripple::PeerSet::m_journal protected
Definition at line 136 of file PeerSet.h.
Referenced by ripple::InboundLedger::addPeers(), ripple::InboundLedger::done(), ripple::InboundLedger::filterNodes(), ripple::InboundLedger::InboundLedger(), ripple::InboundLedger::init(), ripple::InboundLedger::onTimer(), ripple::InboundLedger::processData(), ripple::InboundLedger::takeAsNode(), ripple::InboundLedger::takeBase(), ripple::InboundLedger::takeTxNode(), ripple::InboundLedger::trigger(), and ripple::InboundLedger::tryLocal().
bool ripple::PeerSet::mAggressive protected
Definition at line 146 of file PeerSet.h.
Referenced by ripple::InboundLedger::onTimer(), progress(), and ripple::InboundLedger::trigger().
bool ripple::PeerSet::mComplete protected
Definition at line 144 of file PeerSet.h.
Referenced by ripple::InboundLedger::getJson(), isComplete(), isDone(), setComplete(), ripple::InboundLedger::takeAsNode(), ripple::InboundLedger::takeBase(), ripple::TransactionAcquire::takeNodes(), ripple::InboundLedger::takeTxNode(), ripple::TransactionAcquire::trigger(), ripple::InboundLedger::trigger(), and ripple::InboundLedger::tryLocal().
bool ripple::PeerSet::mFailed protected
Definition at line 145 of file PeerSet.h.
Referenced by ripple::TransactionAcquire::done(), ripple::InboundLedger::getJson(), isDone(), isFailed(), ripple::TransactionAcquire::onTimer(), setFailed(), ripple::InboundLedger::takeAsNode(), ripple::InboundLedger::takeAsRootNode(), ripple::InboundLedger::takeBase(), ripple::TransactionAcquire::takeNodes(), ripple::InboundLedger::takeTxNode(), ripple::InboundLedger::takeTxRootNode(), ripple::TransactionAcquire::trigger(), ripple::InboundLedger::trigger(), and ripple::InboundLedger::tryLocal().
uint256 ripple::PeerSet::mHash protected
Definition at line 141 of file PeerSet.h.
Referenced by ripple::TransactionAcquire::done(), ripple::InboundLedger::done(), getHash(), ripple::InboundLedger::getJson(), ripple::InboundLedger::getNeededHashes(), ripple::InboundLedger::InboundLedger(), invokeOnTimer(), ripple::TransactionAcquire::onTimer(), ripple::InboundLedger::onTimer(), ripple::InboundLedger::takeAsNode(), ripple::InboundLedger::takeBase(), ripple::TransactionAcquire::trigger(), ripple::InboundLedger::trigger(), and ripple::InboundLedger::tryLocal().
clock_type::time_point ripple::PeerSet::mLastAction protected
Definition at line 148 of file PeerSet.h.
Referenced by getLastAction(), PeerSet(), and touch().
LockType ripple::PeerSet::mLock protected
Definition at line 139 of file PeerSet.h.
Referenced by ripple::InboundLedger::addOnComplete(), badPeer(), ripple::InboundLedger::checkLocal(), ripple::InboundLedger::done(), ripple::InboundLedger::getJson(), ripple::InboundLedger::init(), invokeOnTimer(), isActive(), peerHas(), ripple::InboundLedger::processData(), sendRequest(), ripple::InboundLedger::takeAsNode(), and ripple::InboundLedger::trigger().
PeerSetMap ripple::PeerSet::mPeers protected
Definition at line 160 of file PeerSet.h.
Referenced by badPeer(), ripple::InboundLedger::getJson(), getPeerCount(), invokeOnTimer(), peerHas(), sendRequest(), takePeerSetFrom(), and ripple::InboundLedger::trigger().
bool ripple::PeerSet::mProgress protected
Definition at line 149 of file PeerSet.h.
Referenced by clearProgress(), isProgress(), and progress().
int ripple::PeerSet::mTimeouts protected
Definition at line 143 of file PeerSet.h.
Referenced by getTimeouts(), invokeOnTimer(), and ripple::TransactionAcquire::onTimer().
boost::asio::deadline_timer ripple::PeerSet::mTimer protected
Definition at line 153 of file PeerSet.h.
Referenced by setTimer().
int ripple::PeerSet::mTimerInterval protected
Definition at line 142 of file PeerSet.h.
Referenced by PeerSet(), and setTimer().
bool ripple::PeerSet::mTxnData protected
Definition at line 147 of file PeerSet.h.
The documentation for this class was generated from the following files:
rippled/src/ripple_app/peers/PeerSet.h
rippled/src/ripple_app/peers/PeerSet.cpp