rippled: ripple::SHAMapAddNode Class Reference
ripple::SHAMapAddNode Class Reference
#include <SHAMapAddNode.h>
Public Member Functions
SHAMapAddNode ()
SHAMapAddNode (int good, int bad, int duplicate)
void incInvalid ()
void incUseful ()
void incDuplicate ()
void reset ()
int getGood ()
bool isInvalid () const
bool isUseful () const
SHAMapAddNode & operator+= (SHAMapAddNode const &n)
bool isGood () const
std::string get ()
Static Public Member Functions
static SHAMapAddNode duplicate ()
static SHAMapAddNode useful ()
static SHAMapAddNode invalid ()
Private Attributes
int mGood
int mBad
int mDuplicate
Detailed Description
Definition at line 28 of file SHAMapAddNode.h.
Constructor & Destructor Documentation
ripple::SHAMapAddNode::SHAMapAddNode () inline
Definition at line 31 of file SHAMapAddNode.h.
Referenced by duplicate(), invalid(), and useful().
         : mGood (0)
         , mBad (0)
         , mDuplicate (0)
     {
     }
ripple::SHAMapAddNode::SHAMapAddNode (int good, int bad, int duplicate) inline
Definition at line 38 of file SHAMapAddNode.h.
         : mGood(good)
         , mBad(bad)
         , mDuplicate(duplicate)
     {
     }
Member Function Documentation
static SHAMapAddNode ripple::SHAMapAddNode::duplicate () inline static
Definition at line 91 of file SHAMapAddNode.h.
References SHAMapAddNode().
Referenced by ripple::SHAMap::addKnownNode(), and ripple::SHAMap::addRootNode().
     {
         return SHAMapAddNode (0, 0, 1);
     }
std::string ripple::SHAMapAddNode::get () inline
Definition at line 104 of file SHAMapAddNode.h.
References mBad, mDuplicate, and mGood.
Referenced by ripple::InboundLedger::processData().
     {
         std::string ret;
         if (mGood > 0)
         {
             ret.append("good:");
             ret.append(beast::lexicalCastThrow<std::string>(mGood));
         }
         if (mBad > 0)
         {
             if (!ret.empty())
                 ret.append(" ");
          ret.append("bad:");
          ret.append(beast::lexicalCastThrow<std::string>(mBad));
         }
         if (mDuplicate > 0)
         {
             if (!ret.empty())
                 ret.append(" ");
          ret.append("dupe:");
          ret.append(beast::lexicalCastThrow<std::string>(mDuplicate));
         }
         if (ret.empty ())
             ret = "no nodes processed";
         return ret;
     }
int ripple::SHAMapAddNode::getGood () inline
Definition at line 63 of file SHAMapAddNode.h.
References mGood.
Referenced by ripple::InboundLedger::processData().
     {
         return mGood;
     }
void ripple::SHAMapAddNode::incDuplicate () inline
Definition at line 53 of file SHAMapAddNode.h.
References mDuplicate.
Referenced by ripple::InboundLedger::takeAsNode(), ripple::InboundLedger::takeAsRootNode(), ripple::InboundLedger::takeTxNode(), and ripple::InboundLedger::takeTxRootNode().
     {
         ++mDuplicate;
     }
void ripple::SHAMapAddNode::incInvalid () inline
Definition at line 45 of file SHAMapAddNode.h.
References mBad.
Referenced by ripple::InboundLedger::takeAsNode(), ripple::InboundLedger::takeAsRootNode(), ripple::InboundLedger::takeTxNode(), and ripple::InboundLedger::takeTxRootNode().
     {
         ++mBad;
     }
void ripple::SHAMapAddNode::incUseful () inline
Definition at line 49 of file SHAMapAddNode.h.
References mGood.
Referenced by ripple::InboundLedger::processData().
     {
         ++mGood;
     }
static SHAMapAddNode ripple::SHAMapAddNode::invalid () inline static
Definition at line 99 of file SHAMapAddNode.h.
References SHAMapAddNode().
Referenced by ripple::SHAMap::addKnownNode(), ripple::SHAMap::addRootNode(), and ripple::TransactionAcquire::takeNodes().
     {
         return SHAMapAddNode (0, 1, 0);
     }
bool ripple::SHAMapAddNode::isGood () const inline
Definition at line 86 of file SHAMapAddNode.h.
References mBad, mDuplicate, and mGood.
Referenced by ripple::SHAMapSync_test::run(), ripple::InboundLedger::takeAsNode(), and ripple::InboundLedger::takeTxNode().
     {
         return (mGood + mDuplicate) > mBad;
     }
bool ripple::SHAMapAddNode::isInvalid () const inline
Definition at line 68 of file SHAMapAddNode.h.
References mBad.
Referenced by ripple::InboundLedger::processData(), and ripple::PeerImp::recvLedger().
     {
         return mBad > 0;
     }
bool ripple::SHAMapAddNode::isUseful () const inline
Definition at line 72 of file SHAMapAddNode.h.
References mGood.
     {
         return mGood > 0;
     }
SHAMapAddNode& ripple::SHAMapAddNode::operator+= (SHAMapAddNode const & n) inline
Definition at line 77 of file SHAMapAddNode.h.
References mBad, mDuplicate, and mGood.
     {
         mGood += n.mGood;
         mBad += n.mBad;
         mDuplicate += n.mDuplicate;
         return *this;
     }
void ripple::SHAMapAddNode::reset () inline
Definition at line 58 of file SHAMapAddNode.h.
References mBad, mDuplicate, and mGood.
     {
         mGood = mBad = mDuplicate = 0;
     }
static SHAMapAddNode ripple::SHAMapAddNode::useful () inline static
Definition at line 95 of file SHAMapAddNode.h.
References SHAMapAddNode().
Referenced by ripple::SHAMap::addKnownNode(), ripple::SHAMap::addRootNode(), and ripple::TransactionAcquire::takeNodes().
     {
         return SHAMapAddNode (1, 0, 0);
     }
Member Data Documentation
int ripple::SHAMapAddNode::mBad private
Definition at line 134 of file SHAMapAddNode.h.
Referenced by get(), incInvalid(), isGood(), isInvalid(), operator+=(), and reset().
int ripple::SHAMapAddNode::mDuplicate private
Definition at line 135 of file SHAMapAddNode.h.
Referenced by get(), incDuplicate(), isGood(), operator+=(), and reset().
int ripple::SHAMapAddNode::mGood private
Definition at line 133 of file SHAMapAddNode.h.
Referenced by get(), getGood(), incUseful(), isGood(), isUseful(), operator+=(), and reset().
The documentation for this class was generated from the following file:
rippled/src/ripple_app/shamap/SHAMapAddNode.h