rippled: ShellContext Class Reference
ShellContext Class Reference
#include <ShellContext.h>
Public Member Functions
void changeState (ShellState *pState)
void stop (void)
bool ParseInput (void)
void connect (void)
void get (const std::string &db, const std::string &key)
void put (const std::string &db, const std::string &key, const std::string &value)
void scan (const std::string &db, const std::string &start_key, const std::string &end_key, const std::string &limit)
void create (const std::string &db)
void run (void)
ShellContext (int argc, char **argv)
Private Attributes
ShellState * pShellState_
bool exit_
int argc_
char ** argv_
int port_
boost::shared_ptr
< rocksdb::DBClientProxy > clientProxy_
Detailed Description
Definition at line 14 of file ShellContext.h.
Constructor & Destructor Documentation
ShellContext::ShellContext (int argc, char ** argv)
Definition at line 95 of file ShellContext.cpp.
                                                  :
   pShellState_(ShellStateStart::getInstance()),
   exit_(false),
   argc_(argc),
   argv_(argv),
   port_(-1),
   clientProxy_() {
 }
Member Function Documentation
void ShellContext::changeState (ShellState * pState)
Definition at line 23 of file ShellContext.cpp.
Referenced by ShellStateConnected::handleConError(), ShellStateStart::run(), ShellStateConnecting::run(), and ShellStateConnected::run().
{
   pShellState_ = pState;
 }
void ShellContext::connect (void)
Definition at line 51 of file ShellContext.cpp.
Referenced by ShellStateConnecting::run().
{
   clientProxy_->connect();
 }
void ShellContext::create (const std::string & db)
Definition at line 55 of file ShellContext.cpp.
Referenced by ShellStateConnected::run().
{
   if (clientProxy_->create(db)) {
     printf("%s created\n", db.c_str());
   }
 }
void ShellContext::get (const std::string & db, const std::string & key)
Definition at line 61 of file ShellContext.cpp.
Referenced by ShellStateConnected::run().
{
   string v;
   if (clientProxy_->get(db, key, v)) {
     printf("%s\n", v.c_str());
   }
 }
bool ShellContext::ParseInput (void)
Definition at line 31 of file ShellContext.cpp.
Referenced by ShellStateStart::run().
{
   if(argc_ != 3) {
     printf("leveldb_shell host port\n");
     return false;
   }
   port_ = atoi(argv_[2]);
   if(port_ <= 0) {
     printf("Error while parse port : %s\n", argv_[2]);
     return false;
   }
   clientProxy_.reset(new DBClientProxy(argv_[1], port_));
   if(!clientProxy_.get()) {
     return false;
   } else {
     return true;
   }
 }
void ShellContext::put (const std::string & db, const std::string & key, const std::string & value)
Definition at line 69 of file ShellContext.cpp.
Referenced by ShellStateConnected::run().
{
   if (clientProxy_->put(db, key, value)) {
     printf("(%s, %s) has been set\n", key.c_str(), value.c_str());
   }
 }
void ShellContext::run (void)
Definition at line 89 of file ShellContext.cpp.
Referenced by main().
{
   while(!exit_) {
     pShellState_->run(this);
   }
 }
void ShellContext::scan (const std::string & db, const std::string & start_key, const std::string & end_key, const std::string & limit)
Definition at line 77 of file ShellContext.cpp.
References beast.util.Iter::first().
Referenced by ShellStateConnected::run().
{
   vector<pair<string, string> > kvs;
   if (clientProxy_->scan(db, start_key, end_key, limit, kvs)) {
     for(unsigned int i = 0; i < kvs.size(); ++i) {
       printf("%d (%s, %s)\n", i, kvs[i].first.c_str(), kvs[i].second.c_str());
     }
   }
 }
void ShellContext::stop (void)
Definition at line 27 of file ShellContext.cpp.
Referenced by ShellStateStop::run().
{
   exit_ = true;
 }
Member Data Documentation
int ShellContext::argc_ private
Definition at line 45 of file ShellContext.h.
char** ShellContext::argv_ private
Definition at line 46 of file ShellContext.h.
boost::shared_ptr<rocksdb::DBClientProxy> ShellContext::clientProxy_ private
Definition at line 48 of file ShellContext.h.
bool ShellContext::exit_ private
Definition at line 44 of file ShellContext.h.
int ShellContext::port_ private
Definition at line 47 of file ShellContext.h.
ShellState* ShellContext::pShellState_ private
Definition at line 43 of file ShellContext.h.
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/tools/shell/ShellContext.h
rippled/src/ripple/rocksdb/rocksdb/tools/shell/ShellContext.cpp