rippled: ripple::SHAMapTreeNode Class Reference
ripple::SHAMapTreeNode Class Reference
#include <SHAMapTreeNode.h>
Public Types
enum TNType {
tnERROR = 0, tnINNER = 1, tnTRANSACTION_NM = 2, tnTRANSACTION_MD = 3,
tnACCOUNT_STATE = 4
}
typedef boost::shared_ptr
< SHAMapTreeNode > pointer
typedef const
boost::shared_ptr
< SHAMapTreeNode > & ref
Public Member Functions
SHAMapTreeNode (std::uint32_t seq, const SHAMapNode &nodeID)
SHAMapTreeNode (const SHAMapTreeNode &node, std::uint32_t seq)
SHAMapTreeNode (const SHAMapNode &nodeID, SHAMapItem::ref item, TNType type, std::uint32_t seq)
SHAMapTreeNode (const SHAMapNode &id, Blob const &data, std::uint32_t seq, SHANodeFormat format, uint256 const &hash, bool hashValid)
void addRaw (Serializer &, SHANodeFormat format)
virtual bool isPopulated () const
std::uint32_t getSeq () const
void setSeq (std::uint32_t s)
void touch (std::uint32_t s)
uint256 const & getNodeHash () const
TNType getType () const
bool isLeaf () const
bool isInner () const
bool isValid () const
bool isTransaction () const
bool hasMetaData () const
bool isAccountState () const
bool isInnerNode () const
bool setChildHash (int m, uint256 const &hash)
bool isEmptyBranch (int m) const
bool isEmpty () const
int getBranchCount () const
void makeInner ()
uint256 const & getChildHash (int m) const
bool hasItem () const
SHAMapItem::ref peekItem ()
bool setItem (SHAMapItem::ref i, TNType type)
uint256 const & getTag () const
Blob const & peekData ()
bool isFullBelow (void) const
void setFullBelow (void)
virtual void dump ()
virtual std::string getString () const
Public Member Functions inherited from ripple::SHAMapNode
SHAMapNode ()
SHAMapNode (int depth, uint256 const &hash)
int getDepth () const
uint256 const & getNodeID () const
bool isValid () const
bool isRoot () const
size_t getMHash () const
SHAMapNode getParentNodeID () const
SHAMapNode getChildNodeID (int m) const
int selectBranch (uint256 const &hash) const
bool operator< (const SHAMapNode &) const
bool operator> (const SHAMapNode &) const
bool operator<= (const SHAMapNode &) const
bool operator>= (const SHAMapNode &) const
bool operator== (const SHAMapNode &n) const
bool operator== (uint256 const &n) const
bool operator!= (const SHAMapNode &n) const
bool operator!= (uint256 const &n) const
void set (SHAMapNode const &from)
void dump () const
void addIDRaw (Serializer &s) const
std::string getRawString () const
SHAMapNode (const void *ptr, int len)
Public Member Functions inherited from ripple::CountedObject< SHAMapTreeNode >
CountedObject ()
CountedObject (CountedObject const &)
~CountedObject ()
Static Public Member Functions
static char const * getCountedObjectName ()
Static Public Member Functions inherited from ripple::SHAMapNode
static bool ClassInit ()
static uint256 getNodeID (int depth, uint256 const &hash)
static int getRawIDLength (void)
Private Member Functions
SHAMapTreeNode (const SHAMapTreeNode &)
SHAMapTreeNode & operator= (const SHAMapTreeNode &)
bool updateHash ()
Private Attributes
uint256 mHash
uint256 mHashes [16]
SHAMapItem::pointer mItem
std::uint32_t mSeq
std::uint32_t mAccessSeq
TNType mType
int mIsBranch
bool mFullBelow
Friends
class SHAMap
Additional Inherited Members
Protected Member Functions inherited from ripple::SHAMapNode
SHAMapNode (int depth, uint256 const &id, bool)
Detailed Description
Definition at line 34 of file SHAMapTreeNode.h.
Member Typedef Documentation
typedef boost::shared_ptr<SHAMapTreeNode> ripple::SHAMapTreeNode::pointer
Definition at line 41 of file SHAMapTreeNode.h.
typedef const boost::shared_ptr<SHAMapTreeNode>& ripple::SHAMapTreeNode::ref
Definition at line 42 of file SHAMapTreeNode.h.
Member Enumeration Documentation
enum ripple::SHAMapTreeNode::TNType
Enumerator
tnERROR
tnINNER
tnTRANSACTION_NM
tnTRANSACTION_MD
tnACCOUNT_STATE
Definition at line 44 of file SHAMapTreeNode.h.
     {
         tnERROR             = 0,
         tnINNER             = 1,
         tnTRANSACTION_NM    = 2, // transaction, no metadata
         tnTRANSACTION_MD    = 3, // transaction, with metadata
         tnACCOUNT_STATE     = 4
     };
Constructor & Destructor Documentation
ripple::SHAMapTreeNode::SHAMapTreeNode (std::uint32_t seq, const SHAMapNode & nodeID)
Definition at line 22 of file SHAMapTreeNode.cpp.
     : SHAMapNode (nodeID)
     , mHash (std::uint64_t(0))
     , mSeq (seq)
     , mAccessSeq (seq)
     , mType (tnERROR)
     , mIsBranch (0)
     , mFullBelow (false)
 {
 }
ripple::SHAMapTreeNode::SHAMapTreeNode (const SHAMapTreeNode & node, std::uint32_t seq)
Definition at line 33 of file SHAMapTreeNode.cpp.
References mHashes, and mItem.
                                                                            : SHAMapNode (node),
     mHash (node.mHash), mSeq (seq), mType (node.mType), mIsBranch (node.mIsBranch), mFullBelow (false)
 {
     if (node.mItem)
         mItem = node.mItem;
     else
         memcpy (mHashes, node.mHashes, sizeof (mHashes));
 }
ripple::SHAMapTreeNode::SHAMapTreeNode (const SHAMapNode & nodeID, SHAMapItem::ref item, TNType type, std::uint32_t seq)
Definition at line 42 of file SHAMapTreeNode.cpp.
References updateHash().
                                                               :
     SHAMapNode (node), mItem (item), mSeq (seq), mType (type), mIsBranch (0), mFullBelow (false)
 {
     assert (item->peekData ().size () >= 12);
     updateHash ();
 }
ripple::SHAMapTreeNode::SHAMapTreeNode (const SHAMapNode & id, Blob const & data, std::uint32_t seq, SHANodeFormat format, uint256 const & hash, bool hashValid)
Definition at line 50 of file SHAMapTreeNode.cpp.
References ripple::Serializer::chop(), ripple::Serializer::get256(), ripple::Serializer::get8(), ripple::Serializer::getLength(), ripple::Serializer::getPrefixHash(), ripple::Serializer::getSHA512Half(), hash, ripple::HashPrefix::innerNode, ripple::base_uint< BITS >::isZero(), ripple::HashPrefix::leafNode, ripple::lsINFO, mHash, mHashes, mIsBranch, mItem, mType, ripple::Serializer::peekData(), std::chrono::prefix, ripple::Serializer::removeLastByte(), ripple::snfPREFIX, ripple::snfWIRE, ripple::strHex(), tnACCOUNT_STATE, tnINNER, tnTRANSACTION_MD, tnTRANSACTION_NM, ripple::HashPrefix::transactionID, ripple::HashPrefix::txNode, updateHash(), and WriteLog.
                                                                                            :
     SHAMapNode (id), mSeq (seq), mType (tnERROR), mIsBranch (0), mFullBelow (false)
 {
     if (format == snfWIRE)
     {
         Serializer s (rawNode);
         int type = s.removeLastByte ();
         int len = s.getLength ();
         if ((type < 0) || (type > 4))
         {
 #ifdef BEAST_DEBUG
             Log::out() << "Invalid wire format node";
             Log::out() << strHex (rawNode);
             assert (false);
 #endif
             throw std::runtime_error ("invalid node AW type");
         }
         if (type == 0)
         {
             // transaction
             mItem = boost::make_shared<SHAMapItem> (s.getPrefixHash (HashPrefix::transactionID), s.peekData ());
             mType = tnTRANSACTION_NM;
         }
         else if (type == 1)
         {
             // account state
             if (len < (256 / 8))
                 throw std::runtime_error ("short AS node");
             uint256 u;
             s.get256 (u, len - (256 / 8));
             s.chop (256 / 8);
             if (u.isZero ()) throw std::runtime_error ("invalid AS node");
             mItem = boost::make_shared<SHAMapItem> (u, s.peekData ());
             mType = tnACCOUNT_STATE;
         }
         else if (type == 2)
         {
             // full inner
             if (len != 512)
                 throw std::runtime_error ("invalid FI node");
             for (int i = 0; i < 16; ++i)
             {
                 s.get256 (mHashes[i], i * 32);
                 if (mHashes[i].isNonZero ())
                     mIsBranch |= (1 << i);
             }
             mType = tnINNER;
         }
         else if (type == 3)
         {
             // compressed inner
             for (int i = 0; i < (len / 33); ++i)
             {
                 int pos;
                 s.get8 (pos, 32 + (i * 33));
                 if ((pos < 0) || (pos >= 16)) throw std::runtime_error ("invalid CI node");
                 s.get256 (mHashes[pos], i * 33);
                 if (mHashes[pos].isNonZero ())
                     mIsBranch |= (1 << pos);
             }
             mType = tnINNER;
         }
         else if (type == 4)
         {
             // transaction with metadata
             if (len < (256 / 8))
                 throw std::runtime_error ("short TM node");
             uint256 u;
             s.get256 (u, len - (256 / 8));
             s.chop (256 / 8);
             if (u.isZero ())
                 throw std::runtime_error ("invalid TM node");
             mItem = boost::make_shared<SHAMapItem> (u, s.peekData ());
             mType = tnTRANSACTION_MD;
         }
     }
     else if (format == snfPREFIX)
     {
         if (rawNode.size () < 4)
         {
             WriteLog (lsINFO, SHAMapNode) << "size < 4";
             throw std::runtime_error ("invalid P node");
         }
         std::uint32_t prefix = rawNode[0];
         prefix <<= 8;
         prefix |= rawNode[1];
         prefix <<= 8;
         prefix |= rawNode[2];
         prefix <<= 8;
         prefix |= rawNode[3];
         Serializer s (rawNode.begin () + 4, rawNode.end ());
         if (prefix == HashPrefix::transactionID)
         {
             mItem = boost::make_shared<SHAMapItem> (Serializer::getSHA512Half (rawNode), s.peekData ());
             mType = tnTRANSACTION_NM;
         }
         else if (prefix == HashPrefix::leafNode)
         {
             if (s.getLength () < 32)
                 throw std::runtime_error ("short PLN node");
             uint256 u;
             s.get256 (u, s.getLength () - 32);
             s.chop (32);
             if (u.isZero ())
             {
                 WriteLog (lsINFO, SHAMapNode) << "invalid PLN node";
                 throw std::runtime_error ("invalid PLN node");
             }
             mItem = boost::make_shared<SHAMapItem> (u, s.peekData ());
             mType = tnACCOUNT_STATE;
         }
         else if (prefix == HashPrefix::innerNode)
         {
             if (s.getLength () != 512)
                 throw std::runtime_error ("invalid PIN node");
             for (int i = 0; i < 16; ++i)
             {
                 s.get256 (mHashes[i], i * 32);
                 if (mHashes[i].isNonZero ())
                     mIsBranch |= (1 << i);
             }
             mType = tnINNER;
         }
         else if (prefix == HashPrefix::txNode)
         {
             // transaction with metadata
             if (s.getLength () < 32)
                 throw std::runtime_error ("short TXN node");
             uint256 txID;
             s.get256 (txID, s.getLength () - 32);
             s.chop (32);
             mItem = boost::make_shared<SHAMapItem> (txID, s.peekData ());
             mType = tnTRANSACTION_MD;
         }
         else
         {
             WriteLog (lsINFO, SHAMapNode) << "Unknown node prefix " << std::hex << prefix << std::dec;
             throw std::runtime_error ("invalid node prefix");
         }
     }
     else
     {
         assert (false);
         throw std::runtime_error ("Unknown format");
     }
     if (hashValid)
     {
         mHash = hash;
 #if RIPPLE_VERIFY_NODEOBJECT_KEYS
         updateHash ();
         assert (mHash == hash);
 #endif
     }
     else
         updateHash ();
 }
ripple::SHAMapTreeNode::SHAMapTreeNode (const SHAMapTreeNode &) private
Member Function Documentation
void ripple::SHAMapTreeNode::addRaw (Serializer & s, SHANodeFormat format)
Definition at line 287 of file SHAMapTreeNode.cpp.
References ripple::Serializer::add256(), ripple::Serializer::add32(), ripple::Serializer::add8(), ripple::Serializer::addRaw(), getBranchCount(), getNodeHash(), ripple::HashPrefix::innerNode, isEmpty(), isEmptyBranch(), ripple::HashPrefix::leafNode, mHashes, mItem, mType, ripple::snfHASH, ripple::snfPREFIX, ripple::snfWIRE, tnACCOUNT_STATE, tnERROR, tnINNER, tnTRANSACTION_MD, tnTRANSACTION_NM, ripple::HashPrefix::transactionID, and ripple::HashPrefix::txNode.
Referenced by ripple::SHAMap::getFetchPack(), ripple::SHAMap::getNodeFat(), ripple::SHAMap::getPath(), and ripple::InboundLedgersImp::gotStaleData().
 {
     assert ((format == snfPREFIX) || (format == snfWIRE) || (format == snfHASH));
     if (mType == tnERROR)
         throw std::runtime_error ("invalid I node type");
     if (format == snfHASH)
     {
         s.add256 (getNodeHash ());
     }
     else if (mType == tnINNER)
     {
         assert (!isEmpty ());
         if (format == snfPREFIX)
         {
             s.add32 (HashPrefix::innerNode);
             for (int i = 0; i < 16; ++i)
                 s.add256 (mHashes[i]);
         }
         else
         {
             if (getBranchCount () < 12)
             {
                 // compressed node
                 for (int i = 0; i < 16; ++i)
                     if (!isEmptyBranch (i))
                     {
                         s.add256 (mHashes[i]);
                         s.add8 (i);
                     }
                 s.add8 (3);
             }
             else
             {
                 for (int i = 0; i < 16; ++i)
                     s.add256 (mHashes[i]);
                 s.add8 (2);
             }
         }
     }
     else if (mType == tnACCOUNT_STATE)
     {
         if (format == snfPREFIX)
         {
             s.add32 (HashPrefix::leafNode);
             s.addRaw (mItem->peekData ());
             s.add256 (mItem->getTag ());
         }
         else
         {
             s.addRaw (mItem->peekData ());
             s.add256 (mItem->getTag ());
             s.add8 (1);
         }
     }
     else if (mType == tnTRANSACTION_NM)
     {
         if (format == snfPREFIX)
         {
             s.add32 (HashPrefix::transactionID);
             s.addRaw (mItem->peekData ());
         }
         else
         {
             s.addRaw (mItem->peekData ());
             s.add8 (0);
         }
     }
     else if (mType == tnTRANSACTION_MD)
     {
         if (format == snfPREFIX)
         {
             s.add32 (HashPrefix::txNode);
             s.addRaw (mItem->peekData ());
             s.add256 (mItem->getTag ());
         }
         else
         {
             s.addRaw (mItem->peekData ());
             s.add256 (mItem->getTag ());
             s.add8 (4);
         }
     }
     else
         assert (false);
 }
void ripple::SHAMapTreeNode::dump () virtual
Definition at line 414 of file SHAMapTreeNode.cpp.
References ripple::SHAMapNode::getNodeID(), ripple::lsDEBUG, and WriteLog.
 {
     WriteLog (lsDEBUG, SHAMapNode) << "SHAMapTreeNode(" << getNodeID () << ")";
 }
int ripple::SHAMapTreeNode::getBranchCount () const
Definition at line 393 of file SHAMapTreeNode.cpp.
References isEmptyBranch(), and isInner().
Referenced by addRaw().
 {
     assert (isInner ());
     int count = 0;
     for (int i = 0; i < 16; ++i)
         if (!isEmptyBranch (i))
             ++count;
     return count;
 }
uint256 const& ripple::SHAMapTreeNode::getChildHash (int m) const inline
Definition at line 132 of file SHAMapTreeNode.h.
References mHashes, mType, and tnINNER.
Referenced by ripple::SHAMap::compare(), ripple::SHAMap::firstBelow(), ripple::SHAMap::getFetchPack(), ripple::SHAMap::getMissingNodes(), ripple::SHAMap::getNodeFat(), ripple::SHAMap::getNodePointer(), ripple::SHAMap::getPath(), ripple::SHAMap::hasInnerNode(), ripple::SHAMap::hasLeafNode(), ripple::SHAMap::lastBelow(), ripple::SHAMap::onlyBelow(), ripple::SHAMap::visitLeavesInternal(), ripple::SHAMap::walkBranch(), and ripple::SHAMap::walkToPointer().
     {
         assert ((m >= 0) && (m < 16) && (mType == tnINNER));
         return mHashes[m];
     }
static char const* ripple::SHAMapTreeNode::getCountedObjectName () inline static
Definition at line 39 of file SHAMapTreeNode.h.
 { return "SHAMapTreeNode"; }
uint256 const& ripple::SHAMapTreeNode::getNodeHash () const inline
Definition at line 83 of file SHAMapTreeNode.h.
References mHash.
Referenced by addRaw(), ripple::SHAMap::getFetchPack(), ripple::SHAMap::getMissingNodes(), ripple::InboundLedgersImp::gotStaleData(), ripple::SHAMap::hasInnerNode(), ripple::SHAMap::hasLeafNode(), and ripple::SHAMap::peekItem().
     {
         return mHash;
     }
std::uint32_t ripple::SHAMapTreeNode::getSeq () const inline
Definition at line 70 of file SHAMapTreeNode.h.
References mSeq.
     {
         return mSeq;
     }
std::string ripple::SHAMapTreeNode::getString () const virtual
Reimplemented from ripple::SHAMapNode.
Definition at line 419 of file SHAMapTreeNode.cpp.
References ripple::SHAMapNode::getDepth(), ripple::base_uint< BITS >::GetHex(), ripple::SHAMapNode::getNodeID(), getTag(), isEmptyBranch(), isInner(), isLeaf(), mHash, mHashes, mItem, mType, tnACCOUNT_STATE, tnTRANSACTION_MD, and tnTRANSACTION_NM.
 {
     std::string ret = "NodeID(";
     ret += beast::lexicalCastThrow <std::string> (getDepth ());
     ret += ",";
     ret += getNodeID ().GetHex ();
     ret += ")";
     if (isInner ())
     {
         for (int i = 0; i < 16; ++i)
             if (!isEmptyBranch (i))
             {
                 ret += "\nb";
                 ret += beast::lexicalCastThrow <std::string> (i);
                 ret += " = ";
                 ret += mHashes[i].GetHex ();
             }
     }
     if (isLeaf ())
     {
         if (mType == tnTRANSACTION_NM)
             ret += ",txn\n";
         else if (mType == tnTRANSACTION_MD)
             ret += ",txn+md\n";
         else if (mType == tnACCOUNT_STATE)
             ret += ",as\n";
         else
             ret += ",leaf\n";
         ret += "  Tag=";
         ret += getTag ().GetHex ();
         ret += "\n  Hash=";
         ret += mHash.GetHex ();
         ret += "/";
         ret += beast::lexicalCast <std::string> (mItem->peekSerializer ().getDataLength ());
     }
     return ret;
 }
uint256 const& ripple::SHAMapTreeNode::getTag () const inline
Definition at line 148 of file SHAMapTreeNode.h.
References mItem.
Referenced by ripple::SHAMap::compare(), ripple::SHAMap::getFetchPack(), ripple::SHAMap::getPath(), getString(), and ripple::SHAMap::walkToPointer().
     {
         return mItem->getTag ();
     }
TNType ripple::SHAMapTreeNode::getType () const inline
Definition at line 87 of file SHAMapTreeNode.h.
References mType.
Referenced by ripple::SHAMap::peekFirstItem(), ripple::SHAMap::peekItem(), and ripple::SHAMap::peekNextItem().
     {
         return mType;
     }
bool ripple::SHAMapTreeNode::hasItem () const inline
Definition at line 139 of file SHAMapTreeNode.h.
References mItem.
Referenced by ripple::SHAMap::firstBelow(), ripple::SHAMap::lastBelow(), and ripple::SHAMap::onlyBelow().
     {
         return !!mItem;
     }
bool ripple::SHAMapTreeNode::hasMetaData () const inline
Definition at line 110 of file SHAMapTreeNode.h.
References mType, and tnTRANSACTION_MD.
     {
         return mType == tnTRANSACTION_MD;
     }
bool ripple::SHAMapTreeNode::isAccountState () const inline
Definition at line 114 of file SHAMapTreeNode.h.
References mType, and tnACCOUNT_STATE.
     {
         return mType == tnACCOUNT_STATE;
     }
bool ripple::SHAMapTreeNode::isEmpty () const
Definition at line 388 of file SHAMapTreeNode.cpp.
References mIsBranch.
Referenced by addRaw(), and ripple::SHAMap::getNodeFat().
 {
     return mIsBranch == 0;
 }
bool ripple::SHAMapTreeNode::isEmptyBranch (int m) const inline
Definition at line 125 of file SHAMapTreeNode.h.
References mIsBranch.
Referenced by addRaw(), ripple::SHAMap::compare(), ripple::SHAMap::dropBelow(), ripple::SHAMap::firstBelow(), getBranchCount(), ripple::SHAMap::getFetchPack(), ripple::SHAMap::getMissingNodes(), ripple::SHAMap::getNodeFat(), ripple::SHAMap::getNodePointer(), ripple::SHAMap::getPath(), getString(), ripple::SHAMap::hasInnerNode(), ripple::SHAMap::hasLeafNode(), ripple::SHAMap::lastBelow(), ripple::SHAMap::onlyBelow(), ripple::SHAMap::visitLeavesInternal(), ripple::SHAMap::walkBranch(), and ripple::SHAMap::walkToPointer().
     {
         return (mIsBranch & (1 << m)) == 0;
     }
bool ripple::SHAMapTreeNode::isFullBelow (void) const inline
Definition at line 158 of file SHAMapTreeNode.h.
References mFullBelow.
Referenced by ripple::SHAMap::getMissingNodes().
     {
         return mFullBelow;
     }
bool ripple::SHAMapTreeNode::isInner () const inline
Definition at line 98 of file SHAMapTreeNode.h.
References mType, and tnINNER.
Referenced by ripple::SHAMap::compare(), ripple::SHAMap::dropBelow(), getBranchCount(), ripple::SHAMap::getFetchPack(), ripple::SHAMap::getMissingNodes(), ripple::SHAMap::getNodeFat(), getString(), ripple::SHAMap::hasInnerNode(), ripple::SHAMap::hasLeafNode(), ripple::SHAMap::peekNextItem(), and ripple::SHAMap::walkBranch().
     {
         return mType == tnINNER;
     }
bool ripple::SHAMapTreeNode::isInnerNode () const inline
Definition at line 120 of file SHAMapTreeNode.h.
References mItem.
     {
         return !mItem;
     }
bool ripple::SHAMapTreeNode::isLeaf () const inline
Definition at line 93 of file SHAMapTreeNode.h.
References mType, tnACCOUNT_STATE, tnTRANSACTION_MD, and tnTRANSACTION_NM.
Referenced by ripple::SHAMap::compare(), ripple::SHAMap::getNodeFat(), ripple::SHAMap::getNodePointer(), ripple::SHAMap::getPath(), getString(), ripple::SHAMap::onlyBelow(), setItem(), ripple::SHAMap::visitLeavesInternal(), and ripple::SHAMap::walkToPointer().
     {
         return (mType == tnTRANSACTION_NM) || (mType == tnTRANSACTION_MD) ||
                (mType == tnACCOUNT_STATE);
     }
virtual bool ripple::SHAMapTreeNode::isPopulated () const inline virtual
Reimplemented from ripple::SHAMapNode.
Definition at line 64 of file SHAMapTreeNode.h.
     {
         return true;
     }
bool ripple::SHAMapTreeNode::isTransaction () const inline
Definition at line 106 of file SHAMapTreeNode.h.
References mType, tnTRANSACTION_MD, and tnTRANSACTION_NM.
     {
         return (mType == tnTRANSACTION_NM) || (mType == tnTRANSACTION_MD);
     }
bool ripple::SHAMapTreeNode::isValid () const inline
Definition at line 102 of file SHAMapTreeNode.h.
References mType, and tnERROR.
     {
         return mType != tnERROR;
     }
void ripple::SHAMapTreeNode::makeInner ()
Definition at line 405 of file SHAMapTreeNode.cpp.
References mHash, mHashes, mIsBranch, mItem, mType, tnINNER, and ripple::base_uint< BITS >::zero().
 {
     mItem.reset ();
     mIsBranch = 0;
     memset (mHashes, 0, sizeof (mHashes));
     mType = tnINNER;
     mHash.zero ();
 }
SHAMapTreeNode& ripple::SHAMapTreeNode::operator= (const SHAMapTreeNode &) private
Blob const& ripple::SHAMapTreeNode::peekData () inline
Definition at line 152 of file SHAMapTreeNode.h.
References mItem.
Referenced by ripple::SHAMap::compare().
     {
         return mItem->peekData ();
     }
SHAMapItem::ref ripple::SHAMapTreeNode::peekItem () inline
Definition at line 143 of file SHAMapTreeNode.h.
References mItem.
Referenced by ripple::SHAMap::compare(), ripple::SHAMap::onlyBelow(), ripple::SHAMap::peekFirstItem(), ripple::SHAMap::peekItem(), ripple::SHAMap::peekLastItem(), ripple::SHAMap::peekNextItem(), ripple::SHAMap::peekPrevItem(), ripple::SHAMap::visitLeavesInternal(), and ripple::SHAMap::walkBranch().
     { // CAUTION: Do not modify the item
         return mItem;
     }
bool ripple::SHAMapTreeNode::setChildHash (int m, uint256 const & hash)
Definition at line 461 of file SHAMapTreeNode.cpp.
References hash, ripple::base_uint< BITS >::isNonZero(), mHashes, mIsBranch, mSeq, mType, tnINNER, and updateHash().
 {
     assert ((m >= 0) && (m < 16));
     assert (mType == tnINNER);
     assert (mSeq != 0);
     if (mHashes[m] == hash)
         return false;
     mHashes[m] = hash;
     if (hash.isNonZero ())
         mIsBranch |= (1 << m);
     else
         mIsBranch &= ~ (1 << m);
     return updateHash ();
 }
void ripple::SHAMapTreeNode::setFullBelow (void) inline
Definition at line 162 of file SHAMapTreeNode.h.
References mFullBelow.
Referenced by ripple::SHAMap::getMissingNodes().
     {
         mFullBelow = true;
     }
bool ripple::SHAMapTreeNode::setItem (SHAMapItem::ref i, TNType type)
Definition at line 379 of file SHAMapTreeNode.cpp.
References isLeaf(), mItem, mSeq, mType, and updateHash().
 {
     mType = type;
     mItem = i;
     assert (isLeaf ());
     assert (mSeq != 0);
     return updateHash ();
 }
void ripple::SHAMapTreeNode::setSeq (std::uint32_t s) inline
Definition at line 74 of file SHAMapTreeNode.h.
References mAccessSeq, and mSeq.
     {
         mAccessSeq = mSeq = s;
     }
void ripple::SHAMapTreeNode::touch (std::uint32_t s) inline
Definition at line 78 of file SHAMapTreeNode.h.
References mAccessSeq, and mSeq.
Referenced by ripple::SHAMap::getNodePointer().
     {
         if (mSeq != 0)
             mAccessSeq = s;
     }
bool ripple::SHAMapTreeNode::updateHash () private
Definition at line 235 of file SHAMapTreeNode.cpp.
References ripple::Serializer::add256(), ripple::Serializer::add32(), ripple::Serializer::addRaw(), ripple::Serializer::getPrefixHash(), ripple::Serializer::getSHA512Half(), ripple::HashPrefix::innerNode, ripple::HashPrefix::leafNode, mHash, mHashes, mIsBranch, mItem, mType, tnACCOUNT_STATE, tnINNER, tnTRANSACTION_MD, tnTRANSACTION_NM, ripple::HashPrefix::transactionID, ripple::HashPrefix::txNode, and ripple::base_uint< BITS >::zero().
Referenced by setChildHash(), setItem(), and SHAMapTreeNode().
 {
     uint256 nh;
     if (mType == tnINNER)
     {
         if (mIsBranch != 0)
         {
             nh = Serializer::getPrefixHash (HashPrefix::innerNode, reinterpret_cast<unsigned char*> (mHashes), sizeof (mHashes));
 #if RIPPLE_VERIFY_NODEOBJECT_KEYS
             Serializer s;
             s.add32 (HashPrefix::innerNode);
             for (int i = 0; i < 16; ++i)
                 s.add256 (mHashes[i]);
             assert (nh == s.getSHA512Half ());
 #endif
         }
         else
             nh.zero ();
     }
     else if (mType == tnTRANSACTION_NM)
     {
         nh = Serializer::getPrefixHash (HashPrefix::transactionID, mItem->peekData ());
     }
     else if (mType == tnACCOUNT_STATE)
     {
         Serializer s (mItem->peekSerializer ().getDataLength () + (256 + 32) / 8);
         s.add32 (HashPrefix::leafNode);
         s.addRaw (mItem->peekData ());
         s.add256 (mItem->getTag ());
         nh = s.getSHA512Half ();
     }
     else if (mType == tnTRANSACTION_MD)
     {
         Serializer s (mItem->peekSerializer ().getDataLength () + (256 + 32) / 8);
         s.add32 (HashPrefix::txNode);
         s.addRaw (mItem->peekData ());
         s.add256 (mItem->getTag ());
         nh = s.getSHA512Half ();
     }
     else
         assert (false);
     if (nh == mHash)
         return false;
     mHash = nh;
     return true;
 }
Friends And Related Function Documentation
friend class SHAMap friend
Definition at line 176 of file SHAMapTreeNode.h.
Member Data Documentation
std::uint32_t ripple::SHAMapTreeNode::mAccessSeq private
Definition at line 181 of file SHAMapTreeNode.h.
Referenced by setSeq(), and touch().
bool ripple::SHAMapTreeNode::mFullBelow private
Definition at line 184 of file SHAMapTreeNode.h.
Referenced by isFullBelow(), and setFullBelow().
uint256 ripple::SHAMapTreeNode::mHash private
Definition at line 178 of file SHAMapTreeNode.h.
Referenced by getNodeHash(), getString(), makeInner(), SHAMapTreeNode(), and updateHash().
uint256 ripple::SHAMapTreeNode::mHashes[16] private
Definition at line 179 of file SHAMapTreeNode.h.
Referenced by addRaw(), getChildHash(), getString(), makeInner(), setChildHash(), SHAMapTreeNode(), and updateHash().
int ripple::SHAMapTreeNode::mIsBranch private
Definition at line 183 of file SHAMapTreeNode.h.
Referenced by isEmpty(), isEmptyBranch(), makeInner(), setChildHash(), SHAMapTreeNode(), and updateHash().
SHAMapItem::pointer ripple::SHAMapTreeNode::mItem private
Definition at line 180 of file SHAMapTreeNode.h.
Referenced by addRaw(), getString(), getTag(), hasItem(), isInnerNode(), makeInner(), peekData(), peekItem(), setItem(), SHAMapTreeNode(), and updateHash().
std::uint32_t ripple::SHAMapTreeNode::mSeq private
Definition at line 181 of file SHAMapTreeNode.h.
Referenced by getSeq(), setChildHash(), setItem(), setSeq(), and touch().
TNType ripple::SHAMapTreeNode::mType private
Definition at line 182 of file SHAMapTreeNode.h.
Referenced by addRaw(), getChildHash(), getString(), getType(), hasMetaData(), isAccountState(), isInner(), isLeaf(), isTransaction(), isValid(), makeInner(), setChildHash(), setItem(), SHAMapTreeNode(), and updateHash().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/shamap/SHAMapTreeNode.h
rippled/src/ripple_app/shamap/SHAMapTreeNode.cpp