rippled: rocksdb::TestKeyComparator Class Reference
rocksdb::TestKeyComparator Class Reference
Public Member Functions
virtual int Compare (const Slice &a, const Slice &b) const
virtual const char * Name () const override
virtual void FindShortestSeparator (std::string *start, const Slice &limit) const
virtual void FindShortSuccessor (std::string *key) const
Public Member Functions inherited from rocksdb::Comparator
virtual ~Comparator ()
Detailed Description
Definition at line 47 of file prefix_test.cc.
Member Function Documentation
virtual int rocksdb::TestKeyComparator::Compare (const Slice & a, const Slice & b) const inline virtual
Implements rocksdb::Comparator.
Definition at line 52 of file prefix_test.cc.
References ASSERT_TRUE, rocksdb::TestKey::prefix, rocksdb::Slice::size(), rocksdb::SliceToTestKey(), rocksdb::TestKey::sorted, and rocksdb::TestKey().
{
     const TestKey* key_a = SliceToTestKey(a);
     const TestKey* key_b = SliceToTestKey(b);
     if (key_a->prefix != key_b->prefix) {
       if (key_a->prefix < key_b->prefix) return -1;
       if (key_a->prefix > key_b->prefix) return 1;
     } else {
       ASSERT_TRUE(key_a->prefix == key_b->prefix);
       // note, both a and b could be prefix only
       if (a.size() != b.size()) {
         // one of them is prefix
         ASSERT_TRUE(
           (a.size() == sizeof(uint64_t) && b.size() == sizeof(TestKey)) ||
           (b.size() == sizeof(uint64_t) && a.size() == sizeof(TestKey)));
         if (a.size() < b.size()) return -1;
         if (a.size() > b.size()) return 1;
       } else {
         // both a and b are prefix
         if (a.size() == sizeof(uint64_t)) {
           return 0;
         }
         // both a and b are whole key
         ASSERT_TRUE(a.size() == sizeof(TestKey) && b.size() == sizeof(TestKey));
         if (key_a->sorted < key_b->sorted) return -1;
         if (key_a->sorted > key_b->sorted) return 1;
         if (key_a->sorted == key_b->sorted) return 0;
       }
     }
     return 0;
   }
virtual void rocksdb::TestKeyComparator::FindShortestSeparator (std::string * start, const Slice & limit) const inline virtual
Implements rocksdb::Comparator.
Definition at line 88 of file prefix_test.cc.
{
   }
virtual void rocksdb::TestKeyComparator::FindShortSuccessor (std::string * key) const inline virtual
Implements rocksdb::Comparator.
Definition at line 93 of file prefix_test.cc.
 {}
virtual const char* rocksdb::TestKeyComparator::Name () const inline override virtual
Implements rocksdb::Comparator.
Definition at line 84 of file prefix_test.cc.
{
     return "TestKeyComparator";
   }
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/db/prefix_test.cc