rippled: ripple::TaggedCache_test Class Reference
ripple::TaggedCache_test Class Reference
Public Member Functions
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 37 of file TaggedCache.cpp.
Member Function Documentation
void ripple::TaggedCache_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 40 of file TaggedCache.cpp.
References beast::unit_test::suite::expect(), beast::manual_clock< Duration, IsSteady >::set(), and rocksdb::crc32c::Value().
     {
         beast::Journal const j;
         beast::manual_clock <std::chrono::seconds> clock;
         clock.set (0);
         typedef int Key;
         typedef std::string Value;
         typedef TaggedCache <Key, Value> Cache;
         Cache c ("test", 1, 1, clock, j);
         // Insert an item, retrieve it, and age it so it gets purged.
         {
             expect (c.getCacheSize() == 0);
             expect (c.getTrackSize() == 0);
             expect (! c.insert (1, "one"));
             expect (c.getCacheSize() == 1);
             expect (c.getTrackSize() == 1);
             {
                 std::string s;
                 expect (c.retrieve (1, s));
                 expect (s == "one");
             }
             ++clock;
             c.sweep ();
             expect (c.getCacheSize () == 0);
             expect (c.getTrackSize () == 0);
         }
         // Insert an item, maintain a strong pointer, age it, and
         // verify that the entry still exists.
         {
             expect (! c.insert (2, "two"));
             expect (c.getCacheSize() == 1);
             expect (c.getTrackSize() == 1);
             {
                 Cache::mapped_ptr p (c.fetch (2));
                 expect (p != nullptr);
                 ++clock;
                 c.sweep ();
                 expect (c.getCacheSize() == 0);
                 expect (c.getTrackSize() == 1);
             }
             // Make sure its gone now that our reference is gone
             ++clock;
             c.sweep ();
             expect (c.getCacheSize() == 0);
             expect (c.getTrackSize() == 0);
         }
         // Insert the same key/value pair and make sure we get the same result
         {
             expect (! c.insert (3, "three"));
             {
                 Cache::mapped_ptr const p1 (c.fetch (3));
                 Cache::mapped_ptr p2 (boost::make_shared <Value> ("three"));
                 c.canonicalize (3, p2);
                 expect (p1.get() == p2.get());
             }
             ++clock;
             c.sweep ();
             expect (c.getCacheSize() == 0);
             expect (c.getTrackSize() == 0);
         }
         // Put an object in but keep a strong pointer to it, advance the clock a lot,
         // then canonicalize a new object with the same key, make sure you get the
         // original object.
         {
             // Put an object in
             expect (! c.insert (4, "four"));
             expect (c.getCacheSize() == 1);
             expect (c.getTrackSize() == 1);
             {
                 // Keep a strong pointer to it
                 Cache::mapped_ptr p1 (c.fetch (4));
                 expect (p1 != nullptr);
                 expect (c.getCacheSize() == 1);
                 expect (c.getTrackSize() == 1);
                 // Advance the clock a lot
                 ++clock;
                 c.sweep ();
                 expect (c.getCacheSize() == 0);
                 expect (c.getTrackSize() == 1);
                 // Canonicalize a new object with the same key
                 Cache::mapped_ptr p2 (boost::make_shared <std::string> ("four"));
                 expect (c.canonicalize (4, p2, false));
                 expect (c.getCacheSize() == 1);
                 expect (c.getTrackSize() == 1);
                 // Make sure we get the original object
                 expect (p1.get() == p2.get());
             }
             ++clock;
             c.sweep ();
             expect (c.getCacheSize() == 0);
             expect (c.getTrackSize() == 0);
         }
     }
The documentation for this class was generated from the following file:
rippled/src/ripple/common/impl/TaggedCache.cpp