rippled: ripple::NodeStore::Database Class Reference
ripple::NodeStore::Database Class Reference abstract
#include <Database.h>
Public Member Functions
virtual ~Database ()=0
virtual beast::String getName () const =0
virtual NodeObject::pointer fetch (uint256 const &hash)=0
virtual bool asyncFetch (uint256 const &hash, NodeObject::pointer &object)=0
virtual void waitReads ()=0
virtual int getDesiredAsyncReadCount ()=0
virtual void store (NodeObjectType type, std::uint32_t ledgerIndex, Blob &data, uint256 const &hash)=0
virtual void visitAll (VisitCallback &callback)=0
virtual void import (Database &sourceDatabase)=0
virtual int getWriteLoad ()=0
virtual float getCacheHitRate ()=0
virtual void tune (int size, int age)=0
virtual void sweep ()=0
Detailed Description
Persistency layer for NodeObject
A Node is a ledger object which is uniquely identified by a key, which is the 256-bit hash of the body of the node. The payload is a variable length block of serialized data.
All ledger data is stored as node objects and as such, needs to be persisted between launches. Furthermore, since the set of node objects will in general be larger than the amount of available memory, purged node objects which are later accessed must be retrieved from the node store.
See Also
NodeObject
Definition at line 39 of file Database.h.
Constructor & Destructor Documentation
ripple::NodeStore::Database::~Database () pure virtual
Destroy the node store. All pending operations are completed, pending writes flushed, and files closed before this returns.
Definition at line 23 of file Database.cpp.
 {
 }
Member Function Documentation
virtual bool ripple::NodeStore::Database::asyncFetch (uint256 const & hash, NodeObject::pointer & object) pure virtual
Fetch an object without waiting. If I/O is required to determine whether or not the object is present, false is returned. Otherwise, true is returned and object is set to refer to the object, or nullptr if the object is not present. If I/O is required, the I/O is scheduled.
Note
This can be called concurrently.
Parameters
hash The key of the object to retrieve
object The object retrieved
Returns
Whether the operation completed
Implemented in ripple::NodeStore::DatabaseImp.
Referenced by ripple::SHAMap::getNodeAsync().
virtual NodeObject::pointer ripple::NodeStore::Database::fetch (uint256 const & hash) pure virtual
Fetch an object. If the object is known to be not in the database, isn't found in the database during the fetch, or failed to load correctly during the fetch, nullptr is returned.
Note
This can be called concurrently.
Parameters
hash The key of the object to retrieve.
Returns
The object, or nullptr if it couldn't be retrieved.
Implemented in ripple::NodeStore::DatabaseImp.
Referenced by ripple::NodeStore::TestBase::fetchCopyOfBatch(), ripple::PeerImp::recvGetObjectByHash(), and ripple::InboundLedger::tryLocal().
virtual float ripple::NodeStore::Database::getCacheHitRate () pure virtual
Implemented in ripple::NodeStore::DatabaseImp.
Referenced by ripple::RPCHandler::doGetCounts().
virtual int ripple::NodeStore::Database::getDesiredAsyncReadCount () pure virtual
Get the maximum number of async reads the node store prefers.
Returns
The number of async reads preferred.
Implemented in ripple::NodeStore::DatabaseImp.
Referenced by ripple::SHAMap::getMissingNodes().
virtual beast::String ripple::NodeStore::Database::getName () const pure virtual
Retrieve the name associated with this backend. This is used for diagnostics and may not reflect the actual path or paths used by the underlying backend.
Implemented in ripple::NodeStore::DatabaseImp.
Referenced by ripple::ApplicationImp::updateTables().
virtual int ripple::NodeStore::Database::getWriteLoad () pure virtual
Retrieve the estimated number of pending write operations. This is used for diagnostics.
Implemented in ripple::NodeStore::DatabaseImp.
Referenced by ripple::RPCHandler::doGetCounts().
virtual void ripple::NodeStore::Database::import (Database & sourceDatabase) pure virtual
Import objects from another database.
Implemented in ripple::NodeStore::DatabaseImp.
Referenced by ripple::ApplicationImp::updateTables().
virtual void ripple::NodeStore::Database::store (NodeObjectType type, std::uint32_t ledgerIndex, Blob & data, uint256 const & hash) pure virtual
Store the object.
The caller's Blob parameter is overwritten.
Parameters
type The type of object.
ledgerIndex The ledger in which the object appears.
data The payload of the object. The caller's variable is overwritten.
hash The 256-bit hash of the payload data.
Returns
true if the object was stored?
Implemented in ripple::NodeStore::DatabaseImp.
Referenced by ripple::SHAMap::flushDirty(), ripple::AccountStateSF::gotNode(), ripple::TransactionStateSF::gotNode(), ripple::Ledger::saveValidatedLedger(), ripple::NodeStore::TestBase::storeBatch(), ripple::InboundLedger::takeBase(), and ripple::InboundLedger::tryLocal().
virtual void ripple::NodeStore::Database::sweep () pure virtual
Implemented in ripple::NodeStore::DatabaseImp.
Referenced by ripple::ApplicationImp::doSweep().
virtual void ripple::NodeStore::Database::tune (int size, int age) pure virtual
Implemented in ripple::NodeStore::DatabaseImp.
virtual void ripple::NodeStore::Database::visitAll (VisitCallback & callback) pure virtual
Visit every object in the database This is usually called during import.
Note
This routine will not be called concurrently with itself or other methods.
See Also
import
Implemented in ripple::NodeStore::DatabaseImp.
virtual void ripple::NodeStore::Database::waitReads () pure virtual
Wait for all currently pending async reads to complete.
Implemented in ripple::NodeStore::DatabaseImp.
Referenced by ripple::SHAMap::getMissingNodes().
The documentation for this class was generated from the following files:
rippled/src/ripple_core/nodestore/api/Database.h
rippled/src/ripple_core/nodestore/impl/Database.cpp