rippled: rippled/src/ripple/rocksdb/rocksdb/db/merge_test.cc File Reference
merge_test.cc File Reference
#include <assert.h>
#include <memory>
#include <iostream>
#include "rocksdb/cache.h"
#include "rocksdb/comparator.h"
#include "rocksdb/db.h"
#include "rocksdb/env.h"
#include "rocksdb/merge_operator.h"
#include "db/dbformat.h"
#include "db/db_impl.h"
#include "utilities/merge_operators.h"
#include "util/testharness.h"
#include "utilities/utility_db.h"
Classes
class Counters
class MergeBasedCounters
Functions
std::shared_ptr< DB > OpenDb (const string &dbname, const bool ttl=false)
void dumpDb (DB *db)
void testCounters (Counters &counters, DB *db, bool test_compaction)
void runTest (int argc, const string &dbname, const bool use_ttl=false)
int main (int argc, char *argv[])
Function Documentation
void dumpDb (DB * db)
Definition at line 183 of file merge_test.cc.
References rocksdb::DecodeFixed64(), rocksdb::DB::NewIterator(), and value.
Referenced by testCounters().
                     {
   auto it = unique_ptr<Iterator>(db->NewIterator(ReadOptions()));
   for (it->SeekToFirst(); it->Valid(); it->Next()) {
     uint64_t value = DecodeFixed64(it->value().data());
     cout << it->key().ToString() << ": "  << value << endl;
   }
   assert(it->status().ok());  // Check for any errors found during the scan
 }
int main (int argc, char * argv[])
Definition at line 270 of file merge_test.cc.
References runTest(), and rocksdb::test::TmpDir().
{
   //TODO: Make this test like a general rocksdb unit-test
   runTest(argc, test::TmpDir() + "/merge_testdb");
   runTest(argc, test::TmpDir() + "/merge_testdbttl", true); // Run test on TTL database
   return 0;
 }
std::shared_ptr<DB> OpenDb (const string & dbname, const bool ttl = false)
Definition at line 25 of file merge_test.cc.
References rocksdb::Options::create_if_missing, db, rocksdb::DestroyDB(), rocksdb::Options::merge_operator, rocksdb::Status::ok(), and rocksdb::Status::ToString().
Referenced by runTest().
{
   DB* db;
   StackableDB* sdb;
   Options options;
   options.create_if_missing = true;
   options.merge_operator = MergeOperators::CreateUInt64AddOperator();
   Status s;
   DestroyDB(dbname, Options());
   if (ttl) {
     cout << "Opening database with TTL\n";
     s = UtilityDB::OpenTtlDB(options, dbname, &sdb);
     db = sdb;
   } else {
     s = DB::Open(options, dbname, &db);
   }
   if (!s.ok()) {
     cerr << s.ToString() << endl;
     assert(false);
   }
   return std::shared_ptr<DB>(db);
 }
void runTest (int argc, const string & dbname, const bool use_ttl = false)
Definition at line 246 of file merge_test.cc.
References db, rocksdb::DestroyDB(), OpenDb(), and testCounters().
Referenced by main().
{
   auto db = OpenDb(dbname, use_ttl);
   {
     cout << "Test read-modify-write counters... \n";
     Counters counters(db, 0);
     testCounters(counters, db.get(), true);
   }
   bool compact = false;
   if (argc > 1) {
     compact = true;
     cout << "Turn on Compaction\n";
   }
   {
     cout << "Test merge-based counters... \n";
     MergeBasedCounters counters(db, 0);
     testCounters(counters, db.get(), compact);
   }
   DestroyDB(dbname, Options());
 }
void testCounters (Counters & counters, DB * db, bool test_compaction)
Definition at line 192 of file merge_test.cc.
References Counters::assert_add(), Counters::assert_get(), Counters::assert_remove(), Counters::assert_set(), rocksdb::DB::CompactRange(), dumpDb(), rocksdb::DB::Flush(), and rocksdb::FlushOptions::wait.
Referenced by runTest().
{
   FlushOptions o;
   o.wait = true;
   counters.assert_set("a", 1);
   if (test_compaction) db->Flush(o);
   assert(counters.assert_get("a") == 1);
   counters.assert_remove("b");
   // defaut value is 0 if non-existent
   assert(counters.assert_get("b") == 0);
   counters.assert_add("a", 2);
   if (test_compaction) db->Flush(o);
   // 1+2 = 3
   assert(counters.assert_get("a")== 3);
   dumpDb(db);
   std::cout << "1\n";
   // 1+...+49 = ?
   uint64_t sum = 0;
   for (int i = 1; i < 50; i++) {
     counters.assert_add("b", i);
     sum += i;
   }
   assert(counters.assert_get("b") == sum);
   std::cout << "2\n";
   dumpDb(db);
   std::cout << "3\n";
   if (test_compaction) {
     db->Flush(o);
     cout << "Compaction started ...\n";
     db->CompactRange(nullptr, nullptr);
     cout << "Compaction ended\n";
     dumpDb(db);
     assert(counters.assert_get("a")== 3);
     assert(counters.assert_get("b") == sum);
   }
 }