rippled: beast::Debug_test Class Reference
beast::Debug_test Class Reference
Public Member Functions
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Static Public Member Functions
static int envDebug ()
static int beastDebug ()
static int beastForceDebug ()
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 306 of file Debug.cpp.
Member Function Documentation
static int beast::Debug_test::beastDebug () inline static
Definition at line 318 of file Debug.cpp.
Referenced by run().
     {
     #ifdef BEAST_DEBUG
         return BEAST_DEBUG;
     #else
         return 0;
     #endif
     }
static int beast::Debug_test::beastForceDebug () inline static
Definition at line 327 of file Debug.cpp.
References BEAST_FORCE_DEBUG.
Referenced by run().
     {
     #ifdef BEAST_FORCE_DEBUG
         return BEAST_FORCE_DEBUG;
     #else
         return 0;
     #endif
     }
static int beast::Debug_test::envDebug () inline static
Definition at line 309 of file Debug.cpp.
Referenced by run().
     {
     #ifdef _DEBUG
         return 1;
     #else
         return 0;
     #endif
     }
void beast::Debug_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 336 of file Debug.cpp.
References bassertfalse, beastDebug(), beastForceDebug(), envDebug(), beast::unit_test::suite::fail(), beast::String::fromNumber(), beast::SystemStats::getOperatingSystemName(), and beast::unit_test::suite::log.
     {
         log <<
             "operatingSystemName              = '" <<
             SystemStats::getOperatingSystemName () << "'";
         log <<
             "_DEBUG                           = " <<
             String::fromNumber (envDebug ());
         log <<
             "BEAST_DEBUG                      = " <<
             String::fromNumber (beastDebug ());
         log <<
             "BEAST_FORCE_DEBUG                = " <<
             String::fromNumber (beastForceDebug ());
         log <<
             "sizeof(std::size_t)              = " <<
             String::fromNumber (sizeof(std::size_t));
         bassertfalse;
         fail ();
     }
The documentation for this class was generated from the following file:
rippled/src/beast/beast/utility/impl/Debug.cpp