rippled: beast::unsigned_integer< Bits, UInt > Class Template Reference
beast::unsigned_integer< Bits, UInt > Class Template Reference
Public Types
typedef UInt value_type
Public Member Functions
void * data () noexcept
void const * data () const noexcept
Static Public Member Functions
template<class Int >
static unsigned_integer from_number (Int v)
Static Public Attributes
static std::size_t const bits = Bits
static std::size_t const bytes = bits / 8
Private Attributes
std::array< UInt, size > m_vec
Static Private Attributes
static std::size_t const size = Bits/(8*sizeof(UInt))
Friends
template<class Hasher >
void hash_append (Hasher &h, unsigned_integer const &a) noexcept
std::ostream & operator<< (std::ostream &s, unsigned_integer const &v)
Detailed Description
template<std::size_t Bits, class UInt = std::uint64_t>
class beast::unsigned_integer< Bits, UInt >
Definition at line 110 of file hardened_hash.test.cpp.
Member Typedef Documentation
template<std::size_t Bits, class UInt = std::uint64_t> typedef UInt beast::unsigned_integer< Bits, UInt >::value_type
Definition at line 128 of file hardened_hash.test.cpp.
Member Function Documentation
template<std::size_t Bits, class UInt = std::uint64_t> void* beast::unsigned_integer< Bits, UInt >::data () inline noexcept
Definition at line 146 of file hardened_hash.test.cpp.
References beast::unsigned_integer< Bits, UInt >::m_vec.
Referenced by beast::hardened_hash_sha256_test::testSHA256().
     {
         return &m_vec[0];
     }
template<std::size_t Bits, class UInt = std::uint64_t> void const* beast::unsigned_integer< Bits, UInt >::data () const inline noexcept
Definition at line 152 of file hardened_hash.test.cpp.
References beast::unsigned_integer< Bits, UInt >::m_vec.
     {
         return &m_vec[0];
     }
template<std::size_t Bits, class UInt = std::uint64_t> template<class Int > static unsigned_integer beast::unsigned_integer< Bits, UInt >::from_number (Int v) inline static
Definition at line 136 of file hardened_hash.test.cpp.
References beast::unsigned_integer< Bits, UInt >::m_vec, and beast::unsigned_integer< Bits, UInt >::size.
Referenced by beast::hardened_hash_sha256_test::testSHA256().
     {
         unsigned_integer result;
         for (std::size_t i (1); i < size; ++i)
             result.m_vec [i] = 0;
         result.m_vec[0] = v;
         return result;
     }
Friends And Related Function Documentation
template<std::size_t Bits, class UInt = std::uint64_t> template<class Hasher > void hash_append (Hasher & h, unsigned_integer< Bits, UInt > const & a) friend
Definition at line 158 of file hardened_hash.test.cpp.
     {
         using beast::hash_append;
         hash_append (h, a.m_vec);
     }
template<std::size_t Bits, class UInt = std::uint64_t> std::ostream& operator<< (std::ostream & s, unsigned_integer< Bits, UInt > const & v) friend
Definition at line 166 of file hardened_hash.test.cpp.
     {
         for (std::size_t i (0); i < size; ++i)
             s <<
                 std::hex <<
                 std::setfill ('0') <<
                 std::setw (2*sizeof(UInt)) <<
                 v.m_vec[i]
                 ;
         return s;
     }
Member Data Documentation
template<std::size_t Bits, class UInt = std::uint64_t> std::size_t const beast::unsigned_integer< Bits, UInt >::bits = Bits static
Definition at line 130 of file hardened_hash.test.cpp.
template<std::size_t Bits, class UInt = std::uint64_t> std::size_t const beast::unsigned_integer< Bits, UInt >::bytes = bits / 8 static
Definition at line 131 of file hardened_hash.test.cpp.
Referenced by beast::hardened_hash_sha256_test::testSHA256().
template<std::size_t Bits, class UInt = std::uint64_t> std::array<UInt, size> beast::unsigned_integer< Bits, UInt >::m_vec private
Definition at line 125 of file hardened_hash.test.cpp.
Referenced by beast::unsigned_integer< Bits, UInt >::data(), and beast::unsigned_integer< Bits, UInt >::from_number().
template<std::size_t Bits, class UInt = std::uint64_t> std::size_t const beast::unsigned_integer< Bits, UInt >::size = Bits/(8*sizeof(UInt)) static private
Definition at line 123 of file hardened_hash.test.cpp.
Referenced by beast::unsigned_integer< Bits, UInt >::from_number().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/container/tests/hardened_hash.test.cpp