rippled: rocksdb::LDBCommandRunner Class Reference
rocksdb::LDBCommandRunner Class Reference
Static Public Member Functions
static void PrintHelp (const char *exec_name)
static void RunCommand (int argc, char **argv, Options options)
Detailed Description
Definition at line 11 of file ldb_tool.cc.
Member Function Documentation
static void rocksdb::LDBCommandRunner::PrintHelp (const char * exec_name) inline static
Definition at line 14 of file ldb_tool.cc.
References rocksdb::LDBCommand::ARG_AUTO_COMPACTION, rocksdb::LDBCommand::ARG_BLOCK_SIZE, rocksdb::LDBCommand::ARG_BLOOM_BITS, rocksdb::LDBCommand::ARG_COMPRESSION_TYPE, rocksdb::LDBCommand::ARG_DB, rocksdb::LDBCommand::ARG_FILE_SIZE, rocksdb::LDBCommand::ARG_HEX, rocksdb::LDBCommand::ARG_KEY_HEX, rocksdb::LDBCommand::ARG_TTL, rocksdb::LDBCommand::ARG_VALUE_HEX, rocksdb::LDBCommand::ARG_WRITE_BUFFER_SIZE, rocksdb::CompactorCommand::Help(), rocksdb::DBDumperCommand::Help(), rocksdb::InternalDumpCommand::Help(), rocksdb::DBLoaderCommand::Help(), rocksdb::ManifestDumpCommand::Help(), rocksdb::ReduceDBLevelsCommand::Help(), rocksdb::ChangeCompactionStyleCommand::Help(), rocksdb::WALDumperCommand::Help(), rocksdb::GetCommand::Help(), rocksdb::ApproxSizeCommand::Help(), rocksdb::BatchPutCommand::Help(), rocksdb::ScanCommand::Help(), rocksdb::DeleteCommand::Help(), rocksdb::PutCommand::Help(), and rocksdb::DBQuerierCommand::Help().
Referenced by RunCommand().
{
     string ret;
     ret.append("ldb - LevelDB Tool");
     ret.append("\n\n");
     ret.append("commands MUST specify --" + LDBCommand::ARG_DB +
         "=<full_path_to_db_directory> when necessary\n");
     ret.append("\n");
     ret.append("The following optional parameters control if keys/values are "
         "input/output as hex or as plain strings:\n");
     ret.append("  --" + LDBCommand::ARG_KEY_HEX +
         " : Keys are input/output as hex\n");
     ret.append("  --" + LDBCommand::ARG_VALUE_HEX +
         " : Values are input/output as hex\n");
     ret.append("  --" + LDBCommand::ARG_HEX +
         " : Both keys and values are input/output as hex\n");
     ret.append("\n");
     ret.append("The following optional parameters control the database "
         "internals:\n");
     ret.append("  --" + LDBCommand::ARG_TTL +
         " with 'put','get','scan','dump','query','batchput'"
         " : DB supports ttl and value is internally timestamp-suffixed\n");
     ret.append("  --" + LDBCommand::ARG_BLOOM_BITS + "=<int,e.g.:14>\n");
     ret.append("  --" + LDBCommand::ARG_COMPRESSION_TYPE +
         "=<no|snappy|zlib|bzip2>\n");
     ret.append("  --" + LDBCommand::ARG_BLOCK_SIZE +
         "=<block_size_in_bytes>\n");
     ret.append("  --" + LDBCommand::ARG_AUTO_COMPACTION + "=<true|false>\n");
     ret.append("  --" + LDBCommand::ARG_WRITE_BUFFER_SIZE +
         "=<int,e.g.:4194304>\n");
     ret.append("  --" + LDBCommand::ARG_FILE_SIZE + "=<int,e.g.:2097152>\n");
     ret.append("\n\n");
     ret.append("Data Access Commands:\n");
     PutCommand::Help(ret);
     GetCommand::Help(ret);
     BatchPutCommand::Help(ret);
     ScanCommand::Help(ret);
     DeleteCommand::Help(ret);
     DBQuerierCommand::Help(ret);
     ApproxSizeCommand::Help(ret);
     ret.append("\n\n");
     ret.append("Admin Commands:\n");
     WALDumperCommand::Help(ret);
     CompactorCommand::Help(ret);
     ReduceDBLevelsCommand::Help(ret);
     ChangeCompactionStyleCommand::Help(ret);
     DBDumperCommand::Help(ret);
     DBLoaderCommand::Help(ret);
     ManifestDumpCommand::Help(ret);
     InternalDumpCommand::Help(ret);
     fprintf(stderr, "%s\n", ret.c_str());
   }
static void rocksdb::LDBCommandRunner::RunCommand (int argc, char ** argv, Options options) inline static
Definition at line 71 of file ldb_tool.cc.
References rocksdb::LDBCommand::GetExecuteState(), rocksdb::LDBCommand::InitFromCmdLineArgs(), rocksdb::LDBCommandExecuteResult::IsFailed(), PrintHelp(), rocksdb::LDBCommand::Run(), rocksdb::LDBCommandExecuteResult::ToString(), and rocksdb::LDBCommand::ValidateCmdLineOptions().
Referenced by rocksdb::LDBTool::Run().
{
     if (argc <= 2) {
       PrintHelp(argv[0]);
       exit(1);
     }
     LDBCommand* cmdObj = LDBCommand::InitFromCmdLineArgs(argc, argv, options);
     if (cmdObj == nullptr) {
       fprintf(stderr, "Unknown command\n");
       PrintHelp(argv[0]);
       exit(1);
     }
     if (!cmdObj->ValidateCmdLineOptions()) {
       exit(1);
     }
     cmdObj->Run();
     LDBCommandExecuteResult ret = cmdObj->GetExecuteState();
     fprintf(stderr, "%s\n", ret.ToString().c_str());
     delete cmdObj;
     exit(ret.IsFailed());
   }
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/util/ldb_tool.cc