rippled: ripple::HashRouter::Entry Class Reference
ripple::HashRouter::Entry Class Reference
Public Member Functions
Entry ()
std::set< PeerShortID > const & peekPeers () const
void addPeer (PeerShortID peer)
bool hasPeer (PeerShortID peer) const
int getFlags (void) const
bool hasFlag (int mask) const
void setFlag (int flagsToSet)
void clearFlag (int flagsToClear)
void swapSet (std::set< PeerShortID > &other)
Public Member Functions inherited from ripple::CountedObject< Entry >
CountedObject ()
CountedObject (CountedObject const &)
~CountedObject ()
Static Public Member Functions
static char const * getCountedObjectName ()
Private Attributes
int mFlags
std::set< PeerShortID > mPeers
Detailed Description
An entry in the routing table.
Definition at line 28 of file HashRouter.cpp.
Constructor & Destructor Documentation
ripple::HashRouter::Entry::Entry () inline
Definition at line 33 of file HashRouter.cpp.
             : mFlags (0)
         {
         }
Member Function Documentation
void ripple::HashRouter::Entry::addPeer (PeerShortID peer) inline
Definition at line 43 of file HashRouter.cpp.
References mPeers.
Referenced by ripple::HashRouter::addSuppressionPeer().
         {
             if (peer != 0)
                 mPeers.insert (peer);
         }
void ripple::HashRouter::Entry::clearFlag (int flagsToClear) inline
Definition at line 69 of file HashRouter.cpp.
References mFlags.
         {
             mFlags &= ~flagsToClear;
         }
static char const* ripple::HashRouter::Entry::getCountedObjectName () inline static
Definition at line 31 of file HashRouter.cpp.
 { return "HashRouterEntry"; }
int ripple::HashRouter::Entry::getFlags (void) const inline
Definition at line 54 of file HashRouter.cpp.
References mFlags.
Referenced by ripple::HashRouter::addSuppressionPeer(), ripple::HashRouter::getFlags(), ripple::HashRouter::setFlag(), and ripple::HashRouter::swapSet().
         {
             return mFlags;
         }
bool ripple::HashRouter::Entry::hasFlag (int mask) const inline
Definition at line 59 of file HashRouter.cpp.
References mFlags.
         {
             return (mFlags & mask) != 0;
         }
bool ripple::HashRouter::Entry::hasPeer (PeerShortID peer) const inline
Definition at line 49 of file HashRouter.cpp.
References mPeers.
         {
             return mPeers.count (peer) > 0;
         }
std::set<PeerShortID> const& ripple::HashRouter::Entry::peekPeers () const inline
Definition at line 38 of file HashRouter.cpp.
References mPeers.
         {
             return mPeers;
         }
void ripple::HashRouter::Entry::setFlag (int flagsToSet) inline
Definition at line 64 of file HashRouter.cpp.
References mFlags.
Referenced by ripple::HashRouter::addSuppressionFlags(), ripple::HashRouter::setFlag(), and ripple::HashRouter::swapSet().
         {
             mFlags |= flagsToSet;
         }
void ripple::HashRouter::Entry::swapSet (std::set< PeerShortID > & other) inline
Definition at line 74 of file HashRouter.cpp.
References mPeers.
Referenced by ripple::HashRouter::swapSet().
         {
             mPeers.swap (other);
         }
Member Data Documentation
int ripple::HashRouter::Entry::mFlags private
Definition at line 80 of file HashRouter.cpp.
Referenced by clearFlag(), getFlags(), hasFlag(), and setFlag().
std::set<PeerShortID> ripple::HashRouter::Entry::mPeers private
Definition at line 81 of file HashRouter.cpp.
Referenced by addPeer(), hasPeer(), peekPeers(), and swapSet().
The documentation for this class was generated from the following file:
rippled/src/ripple_app/misc/HashRouter.cpp