rippled: beast::BinaryEncoding_test Class Reference
beast::BinaryEncoding_test Class Reference
Public Member Functions
template<std::size_t Bytes>
void testBase16 ()
template<std::size_t Bytes>
void testBase64Bytes (std::string const &vin, std::string const &vout, Base64Conversion c=Base64Conversion())
void testBase64 ()
template<typename Conversion , std::size_t Bytes>
void testEncode (Conversion c=Conversion())
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 285 of file BinaryEncoding.cpp.
Member Function Documentation
void beast::BinaryEncoding_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 384 of file BinaryEncoding.cpp.
References testBase64().
     {
         testBase16 <10> ();
 #if 0
         testEncode <Base16Conversion, 1>  ();
         testEncode <Base16Conversion, 2>  ();
         testEncode <Base16Conversion, 3>  ();
         testEncode <Base16Conversion, 4>  ();
         testEncode <Base16Conversion, 5>  ();
         testEncode <Base16Conversion, 6>  ();
         testEncode <Base16Conversion, 7>  ();
         testEncode <Base16Conversion, 8>  ();
         testEncode <Base16Conversion, 9>  ();
         testEncode <Base16Conversion, 10> ();
         testBase64 ();
         testEncode <Base64Conversion, 20> ();
         testEncode <Base64Conversion, 33> ();
         testEncode <RippleBase58Conversion, 20> ();
         testEncode <RippleBase58Conversion, 33> ();
         testEncode <BitcoinBase58Conversion, 20> ();
         testEncode <BitcoinBase58Conversion, 33> ();
 #endif
     }
template<std::size_t Bytes> void beast::BinaryEncoding_test::testBase16 () inline
Definition at line 290 of file BinaryEncoding.cpp.
References beast::HexEncoding::decode(), beast::BinaryEncoding::encode(), beast::HexEncoding::encode(), beast::unit_test::suite::expect(), beast::Random::fillBitsRandomly(), and beast::unit_test::suite::testcase().
     {
         Random r;
         testcase ("base16");
         for (int i = 0; i < 50; ++i)
         {
             typedef UnsignedInteger <Bytes> UInt;
             UInt v0;
             r.fillBitsRandomly (v0.begin(), UInt::size);
             std::string const good (HexEncoding::encode (v0));
             UInt v1;
             bool const success (HexEncoding::decode (v1, good));
             if (expect (success))
             {
                 expect (v0 == v1);
                 Base16Conversion c;
                 std::string const check (BinaryEncoding::encode (v0, c));
                 expect (good == check,
                     std::string ("expected ") + good + " but got " + check);
             }
         }
     }
void beast::BinaryEncoding_test::testBase64 () inline
Definition at line 337 of file BinaryEncoding.cpp.
References beast::unit_test::suite::testcase().
Referenced by run().
     {
         testcase ("Base64");
         // input (uint)
         std::string const vin [] = {
             "","f","fo","foo","foob","fooba","foobar"
         };
         // output (encoded string)
         std::string const vout [] = {
             "","Zg==","Zm8=","Zm9v","Zm9vYg==","Zm9vYmE=","Zm9vYmFy"
         };
         //testBase64Bytes <0> (vin [0], vout [0]);
         testBase64Bytes <1> (vin [1], vout [1]);
         testBase64Bytes <2> (vin [2], vout [2]);
         testBase64Bytes <3> (vin [3], vout [3]);
         testBase64Bytes <4> (vin [4], vout [4]);
         testBase64Bytes <5> (vin [5], vout [5]);
         testBase64Bytes <6> (vin [6], vout [6]);
     }
template<std::size_t Bytes> void beast::BinaryEncoding_test::testBase64Bytes (std::string const & vin, std::string const & vout, Base64Conversion c = Base64Conversion ()) inline
Definition at line 316 of file BinaryEncoding.cpp.
References beast::BinaryEncoding::decode(), beast::BinaryEncoding::encode(), beast::unit_test::suite::expect(), and beast::unit_test::suite::log.
     {
         typedef UnsignedInteger <Bytes> UInt;
         UInt v1 (vin.c_str());
         std::string const s1 (BinaryEncoding::encode (v1, c));
         log <<
             vout + " to " + s1;
         expect (vout == s1);
         UInt v2;
         bool const success (BinaryEncoding::decode (v2, vout, c));
         if (expect (success))
         {
             std::string const s2 (BinaryEncoding::encode (v2, c));
             log <<
                 vin + " to " + s2;
         }
     }
template<typename Conversion , std::size_t Bytes> void beast::BinaryEncoding_test::testEncode (Conversion c = Conversion()) inline
Definition at line 361 of file BinaryEncoding.cpp.
References beast::BinaryEncoding::decode(), beast::BinaryEncoding::encode(), beast::unit_test::suite::expect(), beast::Random::fillBitsRandomly(), and beast::unit_test::suite::testcase().
     {
         typedef UnsignedInteger <Bytes> UInt;
         std::stringstream ss;
         ss <<
             c.name() << " <" << Bytes << ">";
         testcase (ss.str());
         Random r;
         for (int i = 0; i < 50; ++i)
         {
             UInt v1;
             r.fillBitsRandomly (v1.begin(), UInt::size);
             std::string const s1 (BinaryEncoding::encode (v1, c));
             UInt v2;
             bool success (BinaryEncoding::decode (v2, s1, c));
             if (expect (success))
                 expect (v1 == v2);
         }
     }
The documentation for this class was generated from the following file:
rippled/src/beast/beast/crypto/tests/BinaryEncoding.cpp