rippled: ripple::HTTP::Handler Struct Reference
ripple::HTTP::Handler Struct Reference abstract
#include <Handler.h>
Public Member Functions
virtual void onAccept (Session &session)=0
virtual void onHeaders (Session &session)=0
virtual void onRequest (Session &session)=0
virtual void onClose (Session &session, int errorCode)=0
virtual void onStopped (Server &server)=0
Detailed Description
Processes all sessions. Thread safety: Must be safe to call concurrently from any number of foreign threads.
Definition at line 34 of file Handler.h.
Member Function Documentation
virtual void ripple::HTTP::Handler::onAccept (Session & session) pure virtual
Called when the connection is accepted and we know remoteAddress.
Implemented in ripple::RPCHTTPServerImp.
Referenced by ripple::HTTP::Peer::handle_accept().
virtual void ripple::HTTP::Handler::onClose (Session & session, int errorCode) pure virtual
Called when the session ends. Guaranteed to be called once.
Parameters
errorCode Non zero for a failed connection.
Implemented in ripple::RPCHTTPServerImp.
Referenced by ripple::HTTP::Peer::~Peer().
virtual void ripple::HTTP::Handler::onHeaders (Session & session) pure virtual
Called repeatedly as new HTTP headers are received. Guaranteed to be called at least once.
Implemented in ripple::RPCHTTPServerImp.
Referenced by ripple::HTTP::Peer::handle_headers().
virtual void ripple::HTTP::Handler::onRequest (Session & session) pure virtual
Called when we have the full Content-Body.
Implemented in ripple::RPCHTTPServerImp.
Referenced by ripple::HTTP::Peer::handle_request().
virtual void ripple::HTTP::Handler::onStopped (Server & server) pure virtual
Called when the server has finished its stop.
Implemented in ripple::RPCHTTPServerImp.
Referenced by ripple::HTTP::ServerImpl::run().
The documentation for this struct was generated from the following file:
rippled/src/ripple/http/api/Handler.h