rippled: beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::Buckets Class Reference
beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::Buckets Class Reference
Public Types
typedef std::vector
< bucket_type, typename
std::allocator_traits
< Allocator >::template
rebind_alloc< bucket_type > > vec_type
Public Member Functions
Buckets ()
Buckets (Allocator const &alloc)
operator bucket_traits ()
void clear ()
size_type max_bucket_count () const
float & max_load_factor ()
float const & max_load_factor () const
template<class Container >
void rehash (size_type count, Container &c)
template<class Container >
void resize (size_type n, Container &c)
Private Attributes
float m_max_load_factor
vec_type m_vec
Detailed Description
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>>
class beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::Buckets
Definition at line 479 of file aged_unordered_container.h.
Member Typedef Documentation
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef std::vector< bucket_type, typename std::allocator_traits <Allocator>:: template rebind_alloc <bucket_type> > beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::Buckets::vec_type
Definition at line 485 of file aged_unordered_container.h.
Constructor & Destructor Documentation
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::Buckets::Buckets () inline
Definition at line 487 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::Buckets::m_vec.
             : m_max_load_factor (1.f)
             , m_vec ()
         {
             m_vec.resize (
                 cont_type::suggested_upper_bucket_count (0));
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::Buckets::Buckets (Allocator const & alloc) inline
Definition at line 495 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::Buckets::m_vec.
             : m_max_load_factor (1.f)
             , m_vec (alloc)
         {
             m_vec.resize (
                 cont_type::suggested_upper_bucket_count (0));
         }
Member Function Documentation
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> void beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::Buckets::clear () inline
Definition at line 508 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::Buckets::m_vec.
         {
             m_vec.clear();
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> size_type beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::Buckets::max_bucket_count () const inline
Definition at line 513 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::Buckets::m_vec.
Referenced by beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::max_bucket_count().
         {
             return m_vec.max_size();
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> float& beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::Buckets::max_load_factor () inline
Definition at line 518 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::Buckets::m_max_load_factor.
Referenced by beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::max_load_factor().
         {
             return m_max_load_factor;
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> float const& beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::Buckets::max_load_factor () const inline
Definition at line 523 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::Buckets::m_max_load_factor.
         {
             return m_max_load_factor;
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::Buckets::operator bucket_traits () inline
Definition at line 503 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::Buckets::m_vec.
         {
             return bucket_traits (&m_vec[0], m_vec.size());
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<class Container > void beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::Buckets::rehash (size_type count, Container & c) inline
Definition at line 530 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::Buckets::m_vec, beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::size(), and beast::asio::swap().
Referenced by beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::rehash(), and beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::Buckets::resize().
         {
             size_type const size (m_vec.size());
             if (count == size)
                 return;
             if (count > m_vec.capacity())
             {
                 // Need two vectors otherwise we
                 // will destroy non-empty buckets.
                 vec_type vec (m_vec.get_allocator());
                 std::swap (m_vec, vec);
                 m_vec.resize (count);
                 c.rehash (bucket_traits (
                     &m_vec[0], m_vec.size()));
                 return;
             }
             // Rehash in place.
             if (count > size)
             {
                 // This should not reallocate since
                 // we checked capacity earlier.
                 m_vec.resize (count);
                 c.rehash (bucket_traits (
                     &m_vec[0], count));
                 return;
             }
             // Resize must happen after rehash otherwise
             // we might destroy non-empty buckets.
             c.rehash (bucket_traits (
                 &m_vec[0], count));
             m_vec.resize (count);
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<class Container > void beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::Buckets::resize (size_type n, Container & c) inline
Definition at line 565 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::Buckets::rehash().
Referenced by beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::maybe_rehash().
         {
             size_type const suggested (
                 cont_type::suggested_upper_bucket_count (n));
             rehash (suggested, c);
         }
Member Data Documentation
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> float beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::Buckets::m_max_load_factor private
Definition at line 573 of file aged_unordered_container.h.
Referenced by beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::Buckets::max_load_factor().
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> vec_type beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::Buckets::m_vec private
Definition at line 574 of file aged_unordered_container.h.
Referenced by beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::Buckets::Buckets(), beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::Buckets::clear(), beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::Buckets::max_bucket_count(), beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::Buckets::operator bucket_traits(), and beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::Buckets::rehash().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/container/detail/aged_unordered_container.h