rippled: beast::asio::HandshakeDetectLogicSSL3 Class Reference
beast::asio::HandshakeDetectLogicSSL3 Class Reference
#include <HandshakeDetectLogicSSL3.h>
Public Types
enum { bytesNeeded = 6 }
typedef int arg_type
Public Member Functions
HandshakeDetectLogicSSL3 (arg_type const &)
std::size_t max_needed ()
std::size_t bytes_consumed ()
template<typename ConstBufferSequence >
void analyze (ConstBufferSequence const &buffer)
Public Member Functions inherited from beast::asio::HandshakeDetectLogic
HandshakeDetectLogic ()
bool finished () const noexcept
bool success () const noexcept
Additional Inherited Members
Protected Member Functions inherited from beast::asio::HandshakeDetectLogic
void conclude (bool success=true)
void fail ()
Detailed Description
Definition at line 32 of file HandshakeDetectLogicSSL3.h.
Member Typedef Documentation
typedef int beast::asio::HandshakeDetectLogicSSL3::arg_type
Definition at line 35 of file HandshakeDetectLogicSSL3.h.
Member Enumeration Documentation
anonymous enum
Enumerator
bytesNeeded
Definition at line 41 of file HandshakeDetectLogicSSL3.h.
     {
         bytesNeeded = 6
     };
Constructor & Destructor Documentation
beast::asio::HandshakeDetectLogicSSL3::HandshakeDetectLogicSSL3 (arg_type const &) inline explicit
Definition at line 37 of file HandshakeDetectLogicSSL3.h.
     {
     }
Member Function Documentation
template<typename ConstBufferSequence > void beast::asio::HandshakeDetectLogicSSL3::analyze (ConstBufferSequence const & buffer) inline
Definition at line 57 of file HandshakeDetectLogicSSL3.h.
References beast::asio::HandshakeDetectLogic::conclude(), beast::asio::HandshakeDetectLogic::fail(), beast::fromNetworkByteOrder(), Json::in(), beast::asio::FixedInputBuffer::read(), and version.
     {
         std::uint16_t version;
         FixedInputBufferSize <bytesNeeded> in (buffer);
         std::uint8_t msg_type;
         if (! in.read (&msg_type))
             return;
         // msg_type must be 0x16 = "SSL Handshake"
         //
         if (msg_type != 0x16)
             return fail ();
         if (! in.read (&version))
             return;
         version = fromNetworkByteOrder (version);
         std::uint16_t length;
         if (! in.read (&length))
             return;
         length = fromNetworkByteOrder (length);
         conclude ();
     }
std::size_t beast::asio::HandshakeDetectLogicSSL3::bytes_consumed () inline virtual
How many bytes the handshake consumes. If the detector processes the entire handshake this will be non zero. The SSL detector would return 0, since we want all the existing bytes to be passed on.
Implements beast::asio::HandshakeDetectLogic.
Definition at line 51 of file HandshakeDetectLogicSSL3.h.
     {
         return 0;
     }
std::size_t beast::asio::HandshakeDetectLogicSSL3::max_needed () inline virtual
How many bytes maximum we might need.
This is the largest number of bytes that the detector might need in order to come to a conclusion about whether or not the handshake is a match. Depending on the data, it could come to that conclusion sooner though.
Use read_some instead of read so that the detect logic can reject the handshake sooner if possible.
Implements beast::asio::HandshakeDetectLogic.
Definition at line 46 of file HandshakeDetectLogicSSL3.h.
References bytesNeeded.
     {
         return bytesNeeded;
     }
The documentation for this class was generated from the following file:
rippled/src/beast/modules/beast_asio/protocol/HandshakeDetectLogicSSL3.h