rippled: beast::sqdb::detail::once_temp_type Class Reference
beast::sqdb::detail::once_temp_type Class Reference
#include <once_temp_type.h>
Public Member Functions
once_temp_type (session &s, Error &error)
once_temp_type (once_temp_type const &o)
once_temp_type & operator= (once_temp_type const &o)
~once_temp_type ()
once_temp_type & operator, (into_type_ptr const &i)
once_temp_type & operator, (use_type_ptr const &u)
template<typename T >
once_temp_type & operator<< (T const &t)
Private Attributes
ref_counted_statement * m_rcst
Detailed Description
Definition at line 67 of file once_temp_type.h.
Constructor & Destructor Documentation
beast::sqdb::detail::once_temp_type::once_temp_type (session & s, Error & error)
Definition at line 70 of file once_temp_type.cpp.
References beast::sqdb::session::get_query_stream().
     : m_rcst(new ref_counted_statement(s, error))
 {
     // new query
     s.get_query_stream().str("");
 }
beast::sqdb::detail::once_temp_type::once_temp_type (once_temp_type const & o)
Definition at line 77 of file once_temp_type.cpp.
References beast::sqdb::detail::ref_counted_statement_base::addref(), and m_rcst.
     : m_rcst(o.m_rcst)
 {
     m_rcst->addref();
 }
beast::sqdb::detail::once_temp_type::~once_temp_type ()
Definition at line 91 of file once_temp_type.cpp.
References m_rcst, and beast::sqdb::detail::ref_counted_statement_base::release().
 {
     m_rcst->release();
 }
Member Function Documentation
once_temp_type & beast::sqdb::detail::once_temp_type::operator, (into_type_ptr const & i)
Definition at line 96 of file once_temp_type.cpp.
References beast::sqdb::detail::ref_counted_statement::exchange(), and m_rcst.
 {
     m_rcst->exchange(i);
     return *this;
 }
once_temp_type & beast::sqdb::detail::once_temp_type::operator, (use_type_ptr const & u)
Definition at line 102 of file once_temp_type.cpp.
References beast::sqdb::detail::ref_counted_statement::exchange(), and m_rcst.
 {
     m_rcst->exchange(u);
     return *this;
 }
template<typename T > once_temp_type& beast::sqdb::detail::once_temp_type::operator<< (T const & t) inline
Definition at line 79 of file once_temp_type.h.
References beast::sqdb::detail::ref_counted_statement_base::accumulate(), and m_rcst.
     {
         m_rcst->accumulate(t);
         return *this;
     }
once_temp_type & beast::sqdb::detail::once_temp_type::operator= (once_temp_type const & o)
Definition at line 83 of file once_temp_type.cpp.
References beast::sqdb::detail::ref_counted_statement_base::addref(), m_rcst, and beast::sqdb::detail::ref_counted_statement_base::release().
 {
     o.m_rcst->addref();
     m_rcst->release();
     m_rcst = o.m_rcst;
     return *this;
 }
Member Data Documentation
ref_counted_statement* beast::sqdb::detail::once_temp_type::m_rcst private
Definition at line 86 of file once_temp_type.h.
Referenced by once_temp_type(), operator,(), operator<<(), operator=(), and ~once_temp_type().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_sqdb/detail/once_temp_type.h
rippled/src/beast/modules/beast_sqdb/source/once_temp_type.cpp