rippled: ripple::OrderBookDB Class Reference
ripple::OrderBookDB Class Reference
#include <OrderBookDB.h>
Public Member Functions
OrderBookDB (Stoppable &parent)
void setup (Ledger::ref ledger)
void update (Ledger::pointer ledger)
void invalidate ()
void addOrderBook (const uint160 &takerPaysCurrency, const uint160 &takerGetsCurrency, const uint160 &takerPaysIssuer, const uint160 &takerGetsIssuer)
void getBooksByTakerPays (RippleIssuer const &issuerID, RippleCurrency const &currencyID, std::vector< OrderBook::pointer > &bookRet)
void getBooksByTakerGets (RippleIssuer const &issuerID, RippleCurrency const &currencyID, std::vector< OrderBook::pointer > &bookRet)
bool isBookToXRP (RippleIssuer const &issuerID, RippleCurrency const &currencyID)
BookListeners::pointer getBookListeners (RippleCurrency const &currencyPays, RippleCurrency const &currencyGets, RippleIssuer const &issuerPays, RippleIssuer const &issuerGets)
BookListeners::pointer makeBookListeners (RippleCurrency const &currencyPays, RippleCurrency const &currencyGets, RippleIssuer const &issuerPays, RippleIssuer const &issuerGets)
void processTxn (Ledger::ref ledger, const AcceptedLedgerTx &alTx, Json::Value const &jvObj)
Public Member Functions inherited from beast::Stoppable
Stoppable (char const *name, Stoppable &parent)
virtual ~Stoppable ()
bool isStopping () const
bool isStopped () const
bool areChildrenStopped () const
void stopped ()
virtual void onPrepare ()
virtual void onStart ()
virtual void onStop ()
virtual void onChildrenStopped ()
Private Types
typedef RippleRecursiveMutex LockType
typedef std::lock_guard< LockType > ScopedLockType
typedef ripple::unordered_map
< RippleBook,
BookListeners::pointer > MapType
Private Attributes
ripple::unordered_map
< RippleAsset, std::vector
< OrderBook::pointer > > mSourceMap
ripple::unordered_map
< RippleAsset, std::vector
< OrderBook::pointer > > mDestMap
boost::unordered_set< RippleAsset > mXRPBooks
LockType mLock
MapType mListeners
std::uint32_t mSeq
Additional Inherited Members
Protected Member Functions inherited from beast::Stoppable
Stoppable (char const *name, RootStoppable &root)
Protected Attributes inherited from beast::Stoppable
char const * m_name
RootStoppable & m_root
Child m_child
Atomic< int > m_started
bool volatile m_stopped
bool volatile m_childrenStopped
Children m_children
WaitableEvent m_stoppedEvent
Detailed Description
Definition at line 49 of file OrderBookDB.h.
Member Typedef Documentation
typedef RippleRecursiveMutex ripple::OrderBookDB::LockType private
Definition at line 92 of file OrderBookDB.h.
typedef ripple::unordered_map<RippleBook, BookListeners::pointer> ripple::OrderBookDB::MapType private
Definition at line 96 of file OrderBookDB.h.
typedef std::lock_guard<LockType> ripple::OrderBookDB::ScopedLockType private
Definition at line 93 of file OrderBookDB.h.
Constructor & Destructor Documentation
ripple::OrderBookDB::OrderBookDB (Stoppable & parent) explicit
Definition at line 24 of file OrderBookDB.cpp.
     : Stoppable ("OrderBookDB", parent)
     , mSeq (0)
 {
 }
Member Function Documentation
void ripple::OrderBookDB::addOrderBook (const uint160 & takerPaysCurrency, const uint160 & takerGetsCurrency, const uint160 & takerPaysIssuer, const uint160 & takerGetsIssuer)
Definition at line 133 of file OrderBookDB.cpp.
References ripple::Ledger::getBookBase(), ripple::base_uint< BITS >::isZero(), mDestMap, mLock, mSourceMap, and mXRPBooks.
Referenced by ripple::Ledger::qualityDirDescriber().
 {
     bool toXRP = co.isZero();
     ScopedLockType sl (mLock);
     if (toXRP)
     { // We don't want to search through all the to-XRP or from-XRP order books!
         BOOST_FOREACH(OrderBook::ref ob, mSourceMap[RippleAssetRef(ci, ii)])
         {
             if (ob->getCurrencyOut().isZero ()) // also to XRP
                 return;
         }
     }
     else
     {
         BOOST_FOREACH(OrderBook::ref ob, mDestMap[RippleAssetRef(co, io)])
         {
             if ((ob->getCurrencyIn() == ci) && (ob->getIssuerIn() == ii))
                 return;
         }
     }
     uint256 index = Ledger::getBookBase(ci, ii, co, io);
     OrderBook::pointer book = boost::make_shared<OrderBook> (boost::cref (index),
                               boost::cref (ci), boost::cref (co), boost::cref (ii), boost::cref (io));
     mSourceMap[RippleAssetRef (ci, ii)].push_back (book);
     mDestMap[RippleAssetRef (co, io)].push_back (book);
     if (toXRP)
         mXRPBooks.insert(RippleAssetRef (ci, ii));
 }
BookListeners::pointer ripple::OrderBookDB::getBookListeners (RippleCurrency const & currencyPays, RippleCurrency const & currencyGets, RippleIssuer const & issuerPays, RippleIssuer const & issuerGets)
Definition at line 220 of file OrderBookDB.cpp.
References mListeners, and mLock.
Referenced by makeBookListeners(), processTxn(), and ripple::NetworkOPsImp::unsubBook().
 {
     BookListeners::pointer ret;
     ScopedLockType sl (mLock);
     MapType::iterator it0 (mListeners.find (RippleBookRef (
         RippleAssetRef (currencyPays, issuerPays),
             RippleAssetRef (currencyGets, issuerGets))));
     if (it0 != mListeners.end ())
         ret = it0->second;
     return ret;
 }
void ripple::OrderBookDB::getBooksByTakerGets (RippleIssuer const & issuerID, RippleCurrency const & currencyID, std::vector< OrderBook::pointer > & bookRet)
Definition at line 188 of file OrderBookDB.cpp.
References mDestMap, and mLock.
 {
     ScopedLockType sl (mLock);
     ripple::unordered_map< RippleAsset, std::vector<OrderBook::pointer> >::const_iterator
     it = mDestMap.find (RippleAssetRef (currencyID, issuerID));
     if (it != mDestMap.end ())
         bookRet = it->second;
     else
         bookRet.clear ();
 }
void ripple::OrderBookDB::getBooksByTakerPays (RippleIssuer const & issuerID, RippleCurrency const & currencyID, std::vector< OrderBook::pointer > & bookRet)
Definition at line 167 of file OrderBookDB.cpp.
References mLock, and mSourceMap.
Referenced by ripple::Pathfinder::addLink().
 {
     ScopedLockType sl (mLock);
     ripple::unordered_map< RippleAsset, std::vector<OrderBook::pointer> >::const_iterator
     it = mSourceMap.find (RippleAssetRef (currencyID, issuerID));
     if (it != mSourceMap.end ())
         bookRet = it->second;
     else
         bookRet.clear ();
 }
void ripple::OrderBookDB::invalidate ()
Definition at line 31 of file OrderBookDB.cpp.
References mLock, and mSeq.
 {
     ScopedLockType sl (mLock);
     mSeq = 0;
 }
bool ripple::OrderBookDB::isBookToXRP (RippleIssuer const & issuerID, RippleCurrency const & currencyID)
Definition at line 180 of file OrderBookDB.cpp.
References mLock, and mXRPBooks.
 {
     ScopedLockType sl (mLock);
     return mXRPBooks.count(RippleAssetRef(currencyID, issuerID)) > 0;
 }
BookListeners::pointer ripple::OrderBookDB::makeBookListeners (RippleCurrency const & currencyPays, RippleCurrency const & currencyGets, RippleIssuer const & issuerPays, RippleIssuer const & issuerGets)
Definition at line 201 of file OrderBookDB.cpp.
References getBookListeners(), mListeners, and mLock.
Referenced by ripple::NetworkOPsImp::subBook().
 {
     ScopedLockType sl (mLock);
     BookListeners::pointer ret = getBookListeners (currencyPays, currencyGets, issuerPays, issuerGets);
     if (!ret)
     {
         ret = boost::make_shared<BookListeners> ();
         mListeners [RippleBookRef (
             RippleAssetRef (currencyPays, issuerPays),
             RippleAssetRef (currencyGets, issuerGets))] = ret;
         assert (getBookListeners (currencyPays, currencyGets, issuerPays, issuerGets) == ret);
     }
     return ret;
 }
void ripple::OrderBookDB::processTxn (Ledger::ref ledger, const AcceptedLedgerTx & alTx, Json::Value const & jvObj)
Definition at line 238 of file OrderBookDB.cpp.
References beast::field(), getBookListeners(), ripple::STAmount::getCurrency(), ripple::STObject::getFieldAmount(), ripple::STObject::getFieldU16(), ripple::SerializedType::getFName(), ripple::STAmount::getIssuer(), ripple::AcceptedLedgerTx::getMeta(), ripple::AcceptedLedgerTx::getResult(), ripple::lsINFO, ripple::ltOFFER, mLock, ripple::STObject::peekAtPField(), ripple::tesSUCCESS, and WriteLog.
Referenced by ripple::NetworkOPsImp::pubValidatedTransaction().
 {
     ScopedLockType sl (mLock);
     if (alTx.getResult () == tesSUCCESS)
     {
         // check if this is an offer or an offer cancel or a payment that consumes an offer
         //check to see what the meta looks like
         BOOST_FOREACH (STObject & node, alTx.getMeta ()->getNodes ())
         {
             try
             {
                 if (node.getFieldU16 (sfLedgerEntryType) == ltOFFER)
                 {
                     SField* field = nullptr;
                     // We need a field that contains the TakerGets and TakerPays parameters
                     if (node.getFName () == sfModifiedNode)
                     {
                         field = &sfPreviousFields;
                     }
                     else if (node.getFName () == sfCreatedNode)
                     {
                         field = &sfNewFields;
                     }
                     else if (node.getFName () == sfDeletedNode)
                     {
                         field = &sfFinalFields;
                     }
                     if (field)
                     {
                         const STObject* data = dynamic_cast<const STObject*> (node.peekAtPField (*field));
                         if (data)
{
                             const STAmount& takerGets = data->getFieldAmount (sfTakerGets);
                             RippleCurrency const& currencyGets = takerGets.getCurrency ();
                             RippleIssuer const& issuerGets = takerGets.getIssuer ();
                             const STAmount& takerPays = data->getFieldAmount (sfTakerPays);
                             RippleCurrency const& currencyPays = takerPays.getCurrency ();
                             RippleIssuer const& issuerPays = takerPays.getIssuer ();
                             // determine the OrderBook
                             BookListeners::pointer book =
                                 getBookListeners (currencyPays, currencyGets, issuerPays, issuerGets);
                             if (book)
                                 book->publish (jvObj);
                         }
                     }
                 }
             }
             catch (...)
             {
                 WriteLog (lsINFO, OrderBookDB) << "Fields not found in OrderBookDB::processTxn";
             }
         }
     }
 }
void ripple::OrderBookDB::setup (Ledger::ref ledger)
Definition at line 37 of file OrderBookDB.cpp.
References ripple::JobQueue::addJob(), BIND_TYPE, ripple::getApp(), ripple::getConfig(), ripple::Application::getJobQueue(), ripple::jtUPDATE_PF, ripple::lsDEBUG, mLock, mSeq, update(), and WriteLog.
Referenced by ripple::LedgerMasterImp::checkAccept(), ripple::LedgerMasterImp::findNewLedgersToPublish(), ripple::LedgerMasterImp::setFullLedger(), and ripple::ApplicationImp::setup().
 {
     {
         ScopedLockType sl (mLock);
         // Do a full update every 256 ledgers
         if (mSeq != 0)
         {
             if (ledger->getLedgerSeq () == mSeq)
                 return;
             if ((ledger->getLedgerSeq () > mSeq) && ((ledger->getLedgerSeq () - mSeq) < 256))
                 return;
             if ((ledger->getLedgerSeq () < mSeq) && ((mSeq - ledger->getLedgerSeq ()) < 16))
                 return;
         }
         WriteLog (lsDEBUG, OrderBookDB) << "Advancing from " << mSeq << " to " << ledger->getLedgerSeq();
         mSeq = ledger->getLedgerSeq ();
     }
     if (getConfig().RUN_STANDALONE)
         update(ledger);
     else
         getApp().getJobQueue().addJob(jtUPDATE_PF, "OrderBookDB::update",
             BIND_TYPE(&OrderBookDB::update, this, ledger));
 }
void ripple::OrderBookDB::update (Ledger::pointer ledger)
Definition at line 97 of file OrderBookDB.cpp.
References BIND_TYPE, ripple::getApp(), ripple::Application::getLedgerMaster(), ripple::lsDEBUG, ripple::lsINFO, mDestMap, mLock, mSeq, mSourceMap, mXRPBooks, ripple::LedgerMaster::newOrderBookDB(), P_1, seen, ripple::updateHelper(), and WriteLog.
Referenced by setup().
 {
     boost::unordered_set< uint256 > seen;
     ripple::unordered_map< RippleAsset, std::vector<OrderBook::pointer> > destMap;
     ripple::unordered_map< RippleAsset, std::vector<OrderBook::pointer> > sourceMap;
     boost::unordered_set< RippleAsset > XRPBooks;
     WriteLog (lsDEBUG, OrderBookDB) << "OrderBookDB::update>";
     // walk through the entire ledger looking for orderbook entries
     int books = 0;
     try
     {
         ledger->visitStateItems(BIND_TYPE(&updateHelper, P_1, boost::ref(seen), boost::ref(destMap),
             boost::ref(sourceMap), boost::ref(XRPBooks), boost::ref(books)));
     }
     catch (const SHAMapMissingNode&)
     {
         WriteLog (lsINFO, OrderBookDB) << "OrderBookDB::update encountered a missing node";
         ScopedLockType sl (mLock);
         mSeq = 0;
         return;
     }
     WriteLog (lsDEBUG, OrderBookDB) << "OrderBookDB::update< " << books << " books found";
     {
         ScopedLockType sl (mLock);
         mXRPBooks.swap(XRPBooks);
         mSourceMap.swap(sourceMap);
         mDestMap.swap(destMap);
     }
     getApp().getLedgerMaster().newOrderBookDB();
 }
Member Data Documentation
ripple::unordered_map<RippleAsset, std::vector<OrderBook::pointer> > ripple::OrderBookDB::mDestMap private
Definition at line 87 of file OrderBookDB.h.
Referenced by addOrderBook(), getBooksByTakerGets(), and update().
MapType ripple::OrderBookDB::mListeners private
Definition at line 98 of file OrderBookDB.h.
Referenced by getBookListeners(), and makeBookListeners().
LockType ripple::OrderBookDB::mLock private
Definition at line 94 of file OrderBookDB.h.
Referenced by addOrderBook(), getBookListeners(), getBooksByTakerGets(), getBooksByTakerPays(), invalidate(), isBookToXRP(), makeBookListeners(), processTxn(), setup(), and update().
std::uint32_t ripple::OrderBookDB::mSeq private
Definition at line 100 of file OrderBookDB.h.
Referenced by invalidate(), setup(), and update().
ripple::unordered_map<RippleAsset, std::vector <OrderBook::pointer> > ripple::OrderBookDB::mSourceMap private
Definition at line 83 of file OrderBookDB.h.
Referenced by addOrderBook(), getBooksByTakerPays(), and update().
boost::unordered_set<RippleAsset> ripple::OrderBookDB::mXRPBooks private
Definition at line 90 of file OrderBookDB.h.
Referenced by addOrderBook(), isBookToXRP(), and update().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/ledger/OrderBookDB.h
rippled/src/ripple_app/ledger/OrderBookDB.cpp