rippled: ripple::BuildInfo Struct Reference
ripple::BuildInfo Struct Reference
#include <BuildInfo.h>
Classes
struct Protocol
Static Public Member Functions
static beast::String const & getVersionString ()
static char const * getFullVersionString ()
static Protocol const & getCurrentProtocol ()
static Protocol const & getMinimumProtocol ()
static char const * getRawVersionString ()
Detailed Description
Versioning information for this build.
Definition at line 26 of file BuildInfo.h.
Member Function Documentation
BuildInfo::Protocol const & ripple::BuildInfo::getCurrentProtocol () static
The protocol version we speak and prefer.
Definition at line 46 of file BuildInfo.cpp.
Referenced by ripple::PeerImp::json(), ripple::PeerImp::recvHello(), ripple::PeerImp::sendHello(), and ripple::BuildInfo_test::testValues().
 {
     static Protocol currentProtocol (
     //--------------------------------------------------------------------------
     //
     // The protocol version we speak and prefer (edit this if necessary)
     //
         1,  // major
         2   // minor
     //
     //--------------------------------------------------------------------------
     );
     return currentProtocol;
 }
char const * ripple::BuildInfo::getFullVersionString () static
Full server version string.
This includes the name of the server. It is used in the peer protocol hello message and also the headers of some HTTP replies.
Definition at line 110 of file BuildInfo.cpp.
References getVersionString(), beast::String::toStdString(), and value.
Referenced by ripple::HTTPReply(), and ripple::PeerImp::sendHello().
 {
     struct PrettyPrinter
     {
         PrettyPrinter ()
         {
             beast::String s;
             s << "Ripple-" << getVersionString ();
             fullVersionString = s.toStdString ();
         }
         std::string fullVersionString;
     };
     static PrettyPrinter value;
     return value.fullVersionString.c_str ();
 }
BuildInfo::Protocol const & ripple::BuildInfo::getMinimumProtocol () static
The oldest protocol version we will accept.
Definition at line 63 of file BuildInfo.cpp.
Referenced by ripple::PeerImp::sendHello(), and ripple::BuildInfo_test::testValues().
 {
     static Protocol minimumProtocol (
     //--------------------------------------------------------------------------
     //
     // The oldest protocol version we will accept. (edit this if necessary)
     //
         1,  // major
         2   // minor
     //
     //--------------------------------------------------------------------------
     );
     return minimumProtocol;
 }
char const * ripple::BuildInfo::getRawVersionString () static
Definition at line 26 of file BuildInfo.cpp.
Referenced by getVersionString(), and ripple::BuildInfo_test::testVersion().
 {
     static char const* const rawText =
     //--------------------------------------------------------------------------
     //
     //  The build version number (edit this for each release)
     //
         "0.24.0-rc1"
     //
     //  Must follow the format described here:
     //
     //  http://semver.org/
     //
     //--------------------------------------------------------------------------
     ;
     return rawText;
 }
beast::String const & ripple::BuildInfo::getVersionString () static
Server version.
Follows the Semantic Versioning Specification:
http://semver.org/
Definition at line 86 of file BuildInfo.cpp.
References getRawVersionString(), beast::SemanticVersion::parse(), beast::SemanticVersion::print(), and value.
Referenced by getFullVersionString(), ripple::NetworkOPsImp::getServerInfo(), ripple::run(), and ripple::BuildInfo_test::run().
 {
     struct SanityChecker
     {
         SanityChecker ()
         {
             beast::SemanticVersion v;
             char const* const rawText = getRawVersionString ();
             if (! v.parse (rawText) || v.print () != rawText)
                 beast::FatalError ("Bad server version string", __FILE__, __LINE__);
             versionString = rawText;
         }
         beast::String versionString;
     };
     static SanityChecker value;
     return value.versionString;
 }
The documentation for this struct was generated from the following files:
rippled/src/ripple_data/protocol/BuildInfo.h
rippled/src/ripple_data/protocol/BuildInfo.cpp