rippled: ripple::PeerImp Class Reference
ripple::PeerImp Class Reference
#include <PeerImp.h>
Public Types
enum State {
stateConnecting, stateConnected, stateHandshaked, stateActive,
stateGracefulClose
}
typedef boost::shared_ptr
< PeerImp > ptr
Public Types inherited from ripple::Peer
typedef boost::shared_ptr< Peer > ptr
typedef std::uint32_t ShortId
Public Member Functions
PeerImp (NativeSocketType &&socket, beast::IP::Endpoint remoteAddress, OverlayImpl &overlay, Resource::Manager &resourceManager, PeerFinder::Manager &peerFinder, PeerFinder::Slot::ptr const &slot, boost::asio::ssl::context &ssl_context, MultiSocket::Flag flags)
PeerImp (beast::IP::Endpoint remoteAddress, boost::asio::io_service &io_service, OverlayImpl &overlay, Resource::Manager &resourceManager, PeerFinder::Manager &peerFinder, PeerFinder::Slot::ptr const &slot, boost::asio::ssl::context &ssl_context, MultiSocket::Flag flags)
virtual ~PeerImp ()
PeerImp (PeerImp const &)=delete
PeerImp & operator= (PeerImp const &)=delete
MultiSocket & getStream ()
State state () const
void state (State new_state)
void detach (const char *rsn, bool graceful=true)
void close (bool graceful)
void onConnect (boost::system::error_code ec)
void activate ()
void start ()
std::string getClusterNodeName () const
void sendPacket (const Message::pointer &packet, bool onStrand)
void sendGetPeers ()
void charge (Resource::Charge const &fee)
Json::Value json ()
bool isInCluster () const
uint256 const & getClosedLedgerHash () const
bool hasLedger (uint256 const &hash, std::uint32_t seq) const
void ledgerRange (std::uint32_t &minSeq, std::uint32_t &maxSeq) const
bool hasTxSet (uint256 const &hash) const
Peer::ShortId getShortId () const
const RippleAddress & getNodePublic () const
void cycleStatus ()
bool supportsVersion (int version)
bool hasRange (std::uint32_t uMin, std::uint32_t uMax)
beast::IP::Endpoint getRemoteAddress () const
Static Public Member Functions
static char const * getCountedObjectName ()
static void charge (boost::weak_ptr< Peer > &peer, Resource::Charge const &fee)
Public Attributes
NativeSocketType m_owned_socket
beast::Journal m_journal
ShortId m_shortId
beast::IP::Endpoint m_remoteAddress
Resource::Manager & m_resourceManager
PeerFinder::Manager & m_peerFinder
OverlayImpl & m_overlay
bool m_inbound
std::unique_ptr< MultiSocket > m_socket
boost::asio::io_service::strand m_strand
State m_state
bool m_detaching
bool m_clusterNode
RippleAddress m_nodePublicKey
std::string m_nodeName
uint256 m_secureCookie
LedgerIndex m_minLedger
LedgerIndex m_maxLedger
uint256 m_closedLedgerHash
uint256 m_previousLedgerHash
std::list< uint256 > m_recentLedgers
std::list< uint256 > m_recentTxSets
boost::mutex m_recentLock
boost::asio::deadline_timer m_timer
std::vector< uint8_t > m_readBuffer
std::list< Message::pointer > mSendQ
Message::pointer mSendingPacket
protocol::TMStatusChange mLastStatus
protocol::TMHello mHello
Resource::Consumer m_usage
PeerFinder::Slot::ptr m_slot
bool m_was_canceled
Private Member Functions
void accept ()
void connect ()
void handleShutdown (boost::system::error_code const &ec)
void handleWrite (boost::system::error_code const &ec, size_t bytes)
void handleReadHeader (boost::system::error_code const &ec, std::size_t bytes)
void handleReadBody (boost::system::error_code const &ec, std::size_t bytes)
void handleStart (boost::system::error_code const &ec)
void handleVerifyTimer (boost::system::error_code const &ec)
void processReadBuffer ()
void startReadHeader ()
void startReadBody (unsigned msg_len)
void sendPacketForce (const Message::pointer &packet)
bool hashLatestFinishedMessage (const SSL *sslSession, unsigned char *hash, size_t(*getFinishedMessage)(const SSL *, void *buf, size_t))
bool calculateSessionCookie ()
bool sendHello ()
void recvHello (protocol::TMHello &packet)
void recvCluster (protocol::TMCluster &packet)
void recvTransaction (protocol::TMTransaction &packet)
void recvValidation (const boost::shared_ptr< protocol::TMValidation > &packet)
void recvGetValidation (protocol::TMGetValidations &packet)
void recvContact (protocol::TMContact &packet)
void recvGetContacts (protocol::TMGetContacts &packet)
void recvGetPeers (protocol::TMGetPeers &packet)
void recvPeers (protocol::TMPeers &packet)
void recvEndpoints (protocol::TMEndpoints &packet)
void recvGetObjectByHash (const boost::shared_ptr< protocol::TMGetObjectByHash > &ptr)
void recvPing (protocol::TMPing &packet)
void recvErrorMessage (protocol::TMErrorMsg &packet)
void recvSearchTransaction (protocol::TMSearchTransaction &packet)
void recvGetAccount (protocol::TMGetAccount &packet)
void recvAccount (protocol::TMAccount &packet)
void recvGetLedger (boost::shared_ptr< protocol::TMGetLedger > const &packet)
void recvLedger (boost::shared_ptr< protocol::TMLedgerData > const &packet_ptr)
void recvStatus (protocol::TMStatusChange &packet)
void recvPropose (const boost::shared_ptr< protocol::TMProposeSet > &packet)
void recvHaveTxSet (protocol::TMHaveTransactionSet &packet)
void recvProofWork (protocol::TMProofWork &packet)
void addLedger (uint256 const &hash)
void getLedger (protocol::TMGetLedger &packet)
void addTxSet (uint256 const &hash)
void doFetchPack (const boost::shared_ptr< protocol::TMGetObjectByHash > &packet)
void doProofOfWork (Job &, boost::weak_ptr< Peer > peer, ProofOfWork::pointer pow)
Static Private Member Functions
static void sGetLedger (boost::weak_ptr< PeerImp > wPeer, boost::shared_ptr< protocol::TMGetLedger > packet)
static void checkTransaction (Job &, int flags, SerializedTransaction::pointer stx, boost::weak_ptr< Peer > peer)
static void checkPropose (Job &job, Overlay *pPeers, boost::shared_ptr< protocol::TMProposeSet > packet, LedgerProposal::pointer proposal, uint256 consensusLCL, RippleAddress nodePublic, boost::weak_ptr< Peer > peer, bool fromCluster)
static void checkValidation (Job &, Overlay *pPeers, SerializedValidation::pointer val, bool isTrusted, bool isCluster, boost::shared_ptr< protocol::TMValidation > packet, boost::weak_ptr< Peer > peer)
Static Private Attributes
static const
boost::posix_time::seconds nodeVerifySeconds
static const std::uint32_t clockToleranceDeltaSeconds = 20
static const size_t sslMinimumFinishedLength = 12
Detailed Description
Definition at line 58 of file PeerImp.h.
Member Typedef Documentation
typedef boost::shared_ptr<PeerImp> ripple::PeerImp::ptr
Definition at line 145 of file PeerImp.h.
Member Enumeration Documentation
enum ripple::PeerImp::State
Current state
Enumerator
stateConnecting
An connection is being established (outbound) Connection has been successfully established
stateConnected
Handshake has been received from this peer
stateHandshaked
Running the Ripple protocol actively
stateActive
Gracefully closing
stateGracefulClose
Definition at line 127 of file PeerImp.h.
     {
          stateConnecting
         ,stateConnected
         ,stateHandshaked
         ,stateActive
         ,stateGracefulClose
     };
Constructor & Destructor Documentation
ripple::PeerImp::PeerImp (NativeSocketType && socket, beast::IP::Endpoint remoteAddress, OverlayImpl & overlay, Resource::Manager & resourceManager, PeerFinder::Manager & peerFinder, PeerFinder::Slot::ptr const & slot, boost::asio::ssl::context & ssl_context, MultiSocket::Flag flags) inline
New incoming peer from the specified socket
Definition at line 212 of file PeerImp.h.
             : m_owned_socket (std::move (socket))
             , m_journal (LogPartition::getJournal <Peer> ())
             , m_shortId (0)
             , m_remoteAddress (remoteAddress)
             , m_resourceManager (resourceManager)
             , m_peerFinder (peerFinder)
             , m_overlay (overlay)
             , m_inbound (true)
             , m_socket (MultiSocket::New (
                 m_owned_socket, ssl_context, flags.asBits ()))
             , m_strand (m_owned_socket.get_io_service())
             , m_state (stateConnected)
             , m_detaching (false)
             , m_clusterNode (false)
             , m_minLedger (0)
             , m_maxLedger (0)
             , m_timer (m_owned_socket.get_io_service())
             , m_slot (slot)
             , m_was_canceled (false)
     {
     }
ripple::PeerImp::PeerImp (beast::IP::Endpoint remoteAddress, boost::asio::io_service & io_service, OverlayImpl & overlay, Resource::Manager & resourceManager, PeerFinder::Manager & peerFinder, PeerFinder::Slot::ptr const & slot, boost::asio::ssl::context & ssl_context, MultiSocket::Flag flags) inline
New outgoing peer
Note
Construction of outbound peers is a two step process: a second call is needed (to connect or accept) but we cannot make it from inside the constructor because you cannot call shared_from_this from inside constructors.
Definition at line 249 of file PeerImp.h.
             : m_owned_socket (io_service)
             , m_journal (LogPartition::getJournal <Peer> ())
             , m_shortId (0)
             , m_remoteAddress (remoteAddress)
             , m_resourceManager (resourceManager)
             , m_peerFinder (peerFinder)
             , m_overlay (overlay)
             , m_inbound (false)
             , m_socket (MultiSocket::New (
                 io_service, ssl_context, flags.asBits ()))
             , m_strand (io_service)
             , m_state (stateConnecting)
             , m_detaching (false)
             , m_clusterNode (false)
             , m_minLedger (0)
             , m_maxLedger (0)
             , m_timer (io_service)
             , m_slot (slot)
             , m_was_canceled (false)
     {
     }
virtual ripple::PeerImp::~PeerImp () inline virtual
Definition at line 281 of file PeerImp.h.
References m_overlay, m_slot, and ripple::OverlayImpl::remove().
     {
         m_overlay.remove (m_slot);
     }
ripple::PeerImp::PeerImp (PeerImp const &) delete
Member Function Documentation
void ripple::PeerImp::accept () inline private
We have accepted an inbound connection.
The connection state transitions from stateConnect to stateConnected as stateConnect.
Definition at line 79 of file PeerImp.h.
References handleStart(), beast::Journal::info, m_journal, m_remoteAddress, m_socket, and m_strand.
Referenced by start().
     {
         m_journal.info << "Accepted " << m_remoteAddress;
         m_socket->set_verify_mode (boost::asio::ssl::verify_none);
         m_socket->async_handshake (
             boost::asio::ssl::stream_base::server,
             m_strand.wrap (boost::bind (
                 &PeerImp::handleStart,
                 boost::static_pointer_cast <PeerImp> (shared_from_this ()),
                 boost::asio::placeholders::error)));
     }
void ripple::PeerImp::activate () inline
Indicates that the peer must be activated. A peer is activated after the handshake is completed and if it is not a second connection from a peer that we already have. Once activated the peer transitions to stateActive and begins operating.
Definition at line 430 of file PeerImp.h.
References bassert, m_overlay, m_shortId, m_state, ripple::OverlayImpl::next_id(), ripple::OverlayImpl::onPeerActivated(), stateActive, and stateHandshaked.
     {
         bassert (m_state == stateHandshaked);
         m_state = stateActive;
         bassert(m_shortId == 0);
         m_shortId = m_overlay.next_id();
         m_overlay.onPeerActivated(shared_from_this ());
     }
void ripple::PeerImp::addLedger (uint256 const & hash) inline private
Definition at line 2171 of file PeerImp.h.
References m_recentLedgers, and m_recentLock.
Referenced by recvHello(), and recvStatus().
     {
         boost::mutex::scoped_lock sl(m_recentLock);
         BOOST_FOREACH (uint256 const & ledger, m_recentLedgers)
         if (ledger == hash)
             return;
         if (m_recentLedgers.size () == 128)
             m_recentLedgers.pop_front ();
         m_recentLedgers.push_back (hash);
     }
void ripple::PeerImp::addTxSet (uint256 const & hash) inline private
Definition at line 2523 of file PeerImp.h.
References hash, m_recentLock, and m_recentTxSets.
Referenced by recvHaveTxSet().
     {
         boost::mutex::scoped_lock sl(m_recentLock);
         if(std::find (m_recentTxSets.begin (), m_recentTxSets.end (), hash) != m_recentTxSets.end ())
             return;
         if (m_recentTxSets.size () == 128)
             m_recentTxSets.pop_front ();
         m_recentTxSets.push_back (hash);
     }
bool ripple::PeerImp::calculateSessionCookie () inline private
Generates a secure cookie to protect against man-in-the-middle attacks
This function should never fail under normal circumstances and regular server operation.
A failure prevents the cookie value from being calculated which is an important component of connection security. If this function fails, a secure connection cannot be established and the link MUST be dropped.
Returns
true if the cookie was generated, false otherwise.
Note
failure is an exceptional situation - it should never happen and will almost always indicate an active man-in-the-middle attack is taking place.
Definition at line 1249 of file PeerImp.h.
References beast::Journal::error, ripple::Serializer::getSHA512Half(), hashLatestFinishedMessage(), m_journal, m_secureCookie, and m_socket.
Referenced by sendHello().
     {
         SSL* ssl = m_socket->ssl_handle ();
         if (!ssl)
         {
             m_journal.error << "Cookie generation: No underlying connection";
             return false;
         }
         unsigned char sha1[64];
         unsigned char sha2[64];
         if (!hashLatestFinishedMessage(ssl, sha1, SSL_get_finished))
         {
             m_journal.error << "Cookie generation: local setup not complete";
             return false;
         }
         if (!hashLatestFinishedMessage(ssl, sha2, SSL_get_peer_finished))
         {
             m_journal.error << "Cookie generation: peer setup not complete";
             return false;
         }
         // If both messages hash to the same value (i.e. match) something is
         // wrong. This would cause the resulting cookie to be 0.
         if (memcmp (sha1, sha2, sizeof (sha1)) == 0)
         {
             m_journal.error << "Cookie generation: identical finished messages";
             return false;
         }
         for (size_t i = 0; i < sizeof (sha1); ++i)
             sha1[i] ^= sha2[i];
         // Finally, derive the actual cookie for the values that we have
         // calculated.
         m_secureCookie = Serializer::getSHA512Half (sha1, sizeof(sha1));
         return true;
     }
void ripple::PeerImp::charge (Resource::Charge const & fee) inline virtual
Adjust this peer's load balance based on the type of load imposed.
Implements ripple::Peer.
Definition at line 490 of file PeerImp.h.
References ripple::Resource::Consumer::charge(), detach(), ripple::Resource::Consumer::disconnect(), ripple::Resource::drop, and m_usage.
Referenced by checkPropose(), checkTransaction(), checkValidation(), doFetchPack(), getLedger(), recvCluster(), recvHaveTxSet(), recvLedger(), recvProofWork(), recvPropose(), recvTransaction(), and recvValidation().
     {
          if ((m_usage.charge (fee) == Resource::drop) && m_usage.disconnect ())
              detach ("resource");
     }
static void ripple::PeerImp::charge (boost::weak_ptr< Peer > & peer, Resource::Charge const & fee) inline static
Definition at line 496 of file PeerImp.h.
     {
         Peer::ptr p (peer.lock());
         if (p != nullptr)
             p->charge (fee);
     }
static void ripple::PeerImp::checkPropose (Job & job, Overlay * pPeers, boost::shared_ptr< protocol::TMProposeSet > packet, LedgerProposal::pointer proposal, uint256 consensusLCL, RippleAddress nodePublic, boost::weak_ptr< Peer > peer, bool fromCluster) inline static private
Definition at line 2664 of file PeerImp.h.
References ripple::base_uint< BITS >::begin(), charge(), ripple::Resource::feeInvalidSignature, ripple::Overlay::foreach(), ripple::getApp(), ripple::Application::getOPs(), ripple::Job::getType(), ripple::base_uint< BITS >::isNonZero(), ripple::jtPROPOSAL_t, ripple::lsDEBUG, ripple::lsTRACE, ripple::lsWARNING, ripple::NetworkOPs::processTrustedProposal(), ripple::send_if_not(), SF_RELAYED, and WriteLog.
Referenced by recvPropose().
     {
         bool sigGood = false;
         bool isTrusted = (job.getType () == jtPROPOSAL_t);
         WriteLog (lsTRACE, Peer)  << "Checking " <<
                                      (isTrusted ? "trusted" : "UNTRUSTED") <<
                                      " proposal";
         assert (packet);
         protocol::TMProposeSet& set = *packet;
         uint256 prevLedger;
         if (set.has_previousledger ())
         {
             // proposal includes a previous ledger
             WriteLog(lsTRACE, Peer) << "proposal with previous ledger";
             memcpy (prevLedger.begin (), set.previousledger ().data (), 256 / 8);
             if (!fromCluster && !proposal->checkSign (set.signature ()))
             {
                 Peer::ptr p = peer.lock ();
                 WriteLog(lsWARNING, Peer) << "proposal with previous ledger fails sig check: " <<
                                              *p;
                 charge (peer, Resource::feeInvalidSignature);
                 return;
             }
             else
                 sigGood = true;
         }
         else
         {
             if (consensusLCL.isNonZero () && proposal->checkSign (set.signature ()))
             {
                 prevLedger = consensusLCL;
                 sigGood = true;
             }
             else
             {
                 // Could be mismatched prev ledger
                 WriteLog(lsWARNING, Peer) << "Ledger proposal fails signature check";
                 proposal->setSignature (set.signature ());
             }
         }
         if (isTrusted)
         {
             getApp().getOPs ().processTrustedProposal (proposal, packet, nodePublic, prevLedger, sigGood);
         }
         else if (sigGood && (prevLedger == consensusLCL))
         {
             // relay untrusted proposal
             WriteLog(lsTRACE, Peer) << "relaying UNTRUSTED proposal";
             std::set<Peer::ShortId> peers;
             if (getApp().getHashRouter ().swapSet (
                 proposal->getSuppressionID (), peers, SF_RELAYED))
             {
                 pPeers->foreach (send_if_not (
                     boost::make_shared<Message> (set, protocol::mtPROPOSE_LEDGER),
                     peer_in_set(peers)));
         }
         }
         else
         {
             WriteLog(lsDEBUG, Peer) << "Not relaying UNTRUSTED proposal";
         }
     }
static void ripple::PeerImp::checkTransaction (Job & , int flags, SerializedTransaction::pointer stx, boost::weak_ptr< Peer > peer) inline static private
Definition at line 2621 of file PeerImp.h.
References charge(), ripple::Resource::feeInvalidRequest, ripple::Resource::feeInvalidSignature, ripple::Resource::feeUnwantedData, ripple::getApp(), ripple::Application::getHashRouter(), ripple::Application::getLedgerMaster(), ripple::Application::getOPs(), ripple::LedgerMaster::getValidLedgerIndex(), ripple::INVALID, ripple::is_bit_set(), ripple::NetworkOPs::processTransaction(), ripple::IHashRouter::setFlag(), SF_BAD, SF_SIGGOOD, and SF_TRUSTED.
Referenced by recvTransaction().
     {
     #ifndef TRUST_NETWORK
         try
         {
     #endif
             if (stx->isFieldPresent(sfLastLedgerSequence) &&
                 (stx->getFieldU32 (sfLastLedgerSequence) <
                 getApp().getLedgerMaster().getValidLedgerIndex()))
         { // Transaction has expired
                 getApp().getHashRouter().setFlag(stx->getTransactionID(), SF_BAD);
                 charge (peer, Resource::feeUnwantedData);
                 return;
             }
             bool needCheck = ! is_bit_set (flags, SF_SIGGOOD);
             Transaction::pointer tx =
                 boost::make_shared<Transaction> (stx, needCheck);
             if (tx->getStatus () == INVALID)
             {
                 getApp().getHashRouter ().setFlag (stx->getTransactionID (), SF_BAD);
                 charge (peer, Resource::feeInvalidSignature);
                 return;
             }
             else
                 getApp().getHashRouter ().setFlag (stx->getTransactionID (), SF_SIGGOOD);
             getApp().getOPs ().processTransaction (tx, is_bit_set (flags, SF_TRUSTED), false, false);
     #ifndef TRUST_NETWORK
         }
         catch (...)
         {
             getApp().getHashRouter ().setFlag (stx->getTransactionID (), SF_BAD);
             charge (peer, Resource::feeInvalidRequest);
         }
     #endif
     }
static void ripple::PeerImp::checkValidation (Job & , Overlay * pPeers, SerializedValidation::pointer val, bool isTrusted, bool isCluster, boost::shared_ptr< protocol::TMValidation > packet, boost::weak_ptr< Peer > peer) inline static private
Definition at line 2736 of file PeerImp.h.
References charge(), ripple::Resource::feeInvalidRequest, ripple::Overlay::foreach(), ripple::getApp(), ripple::SerializedValidation::getLedgerHash(), ripple::SerializedValidation::getSignerPublic(), ripple::Application::getValidators(), ripple::Validators::ReceivedValidation::ledgerHash, ripple::lsTRACE, ripple::lsWARNING, ripple::Validators::ReceivedValidation::publicKey, ripple::Validators::Manager::receiveValidation(), recvValidation(), ripple::send_if_not(), SF_RELAYED, ripple::to_string(), and WriteLog.
Referenced by recvValidation().
     {
     #ifndef TRUST_NETWORK
         try
     #endif
         {
             uint256 signingHash = val->getSigningHash();
             if (!isCluster && !val->isValid (signingHash))
             {
                 WriteLog(lsWARNING, Peer) << "Validation is invalid";
                 charge (peer, Resource::feeInvalidRequest);
                 return;
             }
             std::string source;
             Peer::ptr lp = peer.lock ();
             if (lp)
                 source = to_string(*lp);
             else
                 source = "unknown";
             std::set<Peer::ShortId> peers;
             //----------------------------------------------------------------------
             //
             {
                 SerializedValidation const& sv (*val);
                 Validators::ReceivedValidation rv;
                 rv.ledgerHash = sv.getLedgerHash ();
                 rv.publicKey = sv.getSignerPublic();
                 getApp ().getValidators ().receiveValidation (rv);
             }
             //
             //----------------------------------------------------------------------
             if (getApp().getOPs ().recvValidation (val, source) &&
                     getApp().getHashRouter ().swapSet (signingHash, peers, SF_RELAYED))
             {
                 pPeers->foreach (send_if_not (
                     boost::make_shared<Message> (*packet, protocol::mtVALIDATION),
                     peer_in_set(peers)));
             }
         }
     #ifndef TRUST_NETWORK
         catch (...)
         {
             WriteLog(lsTRACE, Peer) << "Exception processing validation";
             charge (peer, Resource::feeInvalidRequest);
         }
     #endif
     }
void ripple::PeerImp::close (bool graceful) inline
Close the connection.
Definition at line 370 of file PeerImp.h.
References detach(), and m_was_canceled.
     {
         m_was_canceled = true;
         detach ("stop", graceful);
     }
void ripple::PeerImp::connect (void) inline private
Attempt an outbound connection.
The connection may fail (for a number of reasons) and we do not know what will happen at this point.
The connection state does not transition with this function and remains as stateConnecting.
Definition at line 100 of file PeerImp.h.
References detach(), beast::Journal::error, handleVerifyTimer(), beast::Journal::info, m_journal, m_remoteAddress, m_socket, m_strand, m_timer, nodeVerifySeconds, onConnect(), and beast::IPAddressConversion::to_asio_endpoint().
Referenced by start().
     {
         m_journal.info << "Connecting to " << m_remoteAddress;
         boost::system::error_code err;
         m_timer.expires_from_now (nodeVerifySeconds, err);
         m_timer.async_wait (m_strand.wrap (boost::bind (
             &PeerImp::handleVerifyTimer,
             shared_from_this (), boost::asio::placeholders::error)));
         if (err)
         {
             m_journal.error << "Failed to set verify timer.";
             detach ("c2");
             return;
         }
         m_socket->next_layer <NativeSocketType>().async_connect (
             beast::IPAddressConversion::to_asio_endpoint (m_remoteAddress),
                 m_strand.wrap (boost::bind (&PeerImp::onConnect,
                     shared_from_this (), boost::asio::placeholders::error)));
     }
void ripple::PeerImp::cycleStatus () inline virtual
Implements ripple::Peer.
Definition at line 629 of file PeerImp.h.
References m_closedLedgerHash, m_previousLedgerHash, and ripple::base_uint< BITS >::zero().
     {
         m_previousLedgerHash = m_closedLedgerHash;
         m_closedLedgerHash.zero ();
     }
void ripple::PeerImp::detach (const char * rsn, bool graceful = true) inline
Disconnect a peer
The peer transitions from its current state into stateGracefulClose
Parameters
rsn a code indicating why the peer was disconnected
onIOStrand true if called on an I/O strand. It if is not, then a callback will be queued up.
Definition at line 317 of file PeerImp.h.
References beast::Journal::active(), BIND_TYPE, ripple::RippleAddress::clear(), handleShutdown(), ripple::RippleAddress::isValid(), m_clusterNode, m_detaching, m_journal, m_nodeName, m_nodePublicKey, m_overlay, m_peerFinder, m_slot, m_socket, m_state, m_strand, m_timer, m_was_canceled, mSendQ, ripple::PeerFinder::Manager::on_cancel(), ripple::PeerFinder::Manager::on_closed(), ripple::OverlayImpl::onPeerDisconnect(), stateActive, stateGracefulClose, and beast::Journal::warning.
Referenced by charge(), close(), connect(), handleReadBody(), handleReadHeader(), handleShutdown(), handleStart(), handleVerifyTimer(), handleWrite(), onConnect(), processReadBuffer(), and recvHello().
     {
         if (! m_strand.running_in_this_thread ())
         {
             m_strand.post (BIND_TYPE (&PeerImp::detach,
                 shared_from_this (), rsn, graceful));
             return;
         }
         if (!m_detaching)
         {
             // NIKB TODO No - a race is NOT ok. This needs to be fixed
             //           to have PeerFinder work reliably.
             m_detaching  = true; // Race is ok.
             if (m_was_canceled)
                 m_peerFinder.on_cancel (m_slot);
             else
                 m_peerFinder.on_closed (m_slot);
             if (m_state == stateActive)
                 m_overlay.onPeerDisconnect (shared_from_this ());
             m_state = stateGracefulClose;
             if (m_clusterNode && m_journal.active(beast::Journal::Severity::kWarning))
                 m_journal.warning << "Cluster peer " << m_nodeName <<
                                      " detached: " << rsn;
             mSendQ.clear ();
             (void) m_timer.cancel ();
             if (graceful)
             {
                 m_socket->async_shutdown (
                     m_strand.wrap ( boost::bind(
                         &PeerImp::handleShutdown,
                         boost::static_pointer_cast <PeerImp> (shared_from_this ()),
                         boost::asio::placeholders::error)));
             }
             else
             {
                 m_socket->cancel ();
             }
             // VFALCO TODO Stop doing this.
             if (m_nodePublicKey.isValid ())
                 m_nodePublicKey.clear ();       // Be idempotent.
         }
     }
void ripple::PeerImp::doFetchPack (const boost::shared_ptr< protocol::TMGetObjectByHash > & packet) inline private
Definition at line 2536 of file PeerImp.h.
References ripple::JobQueue::addJob(), ripple::base_uint< BITS >::begin(), BIND_TYPE, charge(), beast::Journal::debug, ripple::Resource::feeInvalidRequest, ripple::Resource::feeRequestNoReply, ripple::getApp(), ripple::LedgerMaster::getEarliestFetch(), ripple::UptimeTimer::getInstance(), ripple::Application::getJobQueue(), ripple::NetworkOPs::getLedgerByHash(), ripple::Application::getLedgerMaster(), ripple::Application::getOPs(), hash, beast::Journal::info, ripple::jtPACK, m_journal, ripple::NetworkOPs::makeFetchPack(), P_1, and beast::Journal::warning.
Referenced by recvGetObjectByHash().
     {
         // VFALCO TODO Invert this dependency using an observer and shared state object.
         if (getApp().getFeeTrack ().isLoadedLocal ())
         {
             m_journal.info << "Too busy to make fetch pack";
             return;
         }
         if (packet->ledgerhash ().size () != 32)
         {
             m_journal.warning << "FetchPack hash size malformed";
             charge (Resource::feeInvalidRequest);
             return;
         }
         uint256 hash;
         memcpy (hash.begin (), packet->ledgerhash ().data (), 32);
         Ledger::pointer haveLedger = getApp().getOPs ().getLedgerByHash (hash);
         if (!haveLedger)
         {
             m_journal.info << "Peer requests fetch pack for ledger we don't have: " << hash;
             charge (Resource::feeRequestNoReply);
             return;
         }
         if (!haveLedger->isClosed ())
         {
             m_journal.warning << "Peer requests fetch pack from open ledger: " << hash;
             charge (Resource::feeInvalidRequest);
             return;
         }
         if (haveLedger->getLedgerSeq() < getApp().getLedgerMaster().getEarliestFetch())
         {
             m_journal.debug << "Peer requests fetch pack that is too early";
             charge (Resource::feeInvalidRequest);
             return;
         }
         Ledger::pointer wantLedger = getApp().getOPs ().getLedgerByHash (haveLedger->getParentHash ());
         if (!wantLedger)
         {
             m_journal.info << "Peer requests fetch pack for ledger whose predecessor we don't have: " << hash;
             charge (Resource::feeRequestNoReply);
             return;
         }
         getApp().getJobQueue ().addJob (jtPACK, "MakeFetchPack",
                                        BIND_TYPE (&NetworkOPs::makeFetchPack, &getApp().getOPs (), P_1,
                                                boost::weak_ptr<Peer> (shared_from_this ()), packet, wantLedger, haveLedger, UptimeTimer::getInstance ().getElapsedSeconds ()));
     }
void ripple::PeerImp::doProofOfWork (Job & , boost::weak_ptr< Peer > peer, ProofOfWork::pointer pow) inline private
Definition at line 2592 of file PeerImp.h.
References ripple::base_uint< BITS >::begin(), ripple::base_uint< BITS >::isZero(), m_journal, ripple::base_uint< BITS >::size(), and beast::Journal::warning.
Referenced by recvProofWork().
     {
         if (peer.expired ())
             return;
         uint256 solution = pow->solve ();
         if (solution.isZero ())
         {
              m_journal.warning << "Failed to solve proof of work";
         }
         else
         {
             Peer::ptr pptr (peer.lock ());
             if (pptr)
             {
                 protocol::TMProofWork reply;
                 reply.set_token (pow->getToken ());
                 reply.set_response (solution.begin (), solution.size ());
                 pptr->sendPacket (boost::make_shared<Message> (reply, protocol::mtPROOFOFWORK), false);
             }
             else
             {
                 // WRITEME: Save solved proof of work for new connection
             }
         }
     }
uint256 const& ripple::PeerImp::getClosedLedgerHash () const inline virtual
Implements ripple::Peer.
Definition at line 579 of file PeerImp.h.
References m_closedLedgerHash.
     {
         return m_closedLedgerHash;
     }
std::string ripple::PeerImp::getClusterNodeName () const inline virtual
Implements ripple::Peer.
Definition at line 448 of file PeerImp.h.
References m_nodeName.
Referenced by ripple::to_string().
     {
         return m_nodeName;
     }
static char const* ripple::PeerImp::getCountedObjectName () inline static
Definition at line 294 of file PeerImp.h.
 { return "Peer"; }
void ripple::PeerImp::getLedger (protocol::TMGetLedger & packet) inline private
Definition at line 2185 of file PeerImp.h.
References ripple::base_uint< BITS >::begin(), charge(), beast::Journal::debug, ripple::Serializer::erase(), beast::Journal::error, ripple::Resource::feeInvalidRequest, ripple::Overlay::foreach(), ripple::OverlayImpl::getActivePeers(), ripple::getApp(), ripple::LedgerMaster::getClosedLedger(), ripple::LedgerMaster::getCurrentLedger(), ripple::Serializer::getDataPtr(), ripple::LedgerMaster::getEarliestFetch(), ripple::base_uint< BITS >::GetHex(), ripple::LedgerMaster::getLedgerByHash(), ripple::LedgerMaster::getLedgerBySeq(), ripple::Application::getLedgerMaster(), ripple::Serializer::getLength(), ripple::Application::getOPs(), getShortId(), ripple::NetworkOPs::getTXMap(), beast::Journal::info, m_clusterNode, m_journal, m_overlay, rand, sendPacket(), ripple::base_uint< BITS >::size(), ripple::snfWIRE, ripple::to_string(), beast::Journal::trace, and beast::Journal::warning.
     {
             SHAMap::pointer map;
         protocol::TMLedgerData reply;
         bool fatLeaves = true, fatRoot = false;
         if (packet.has_requestcookie ())
             reply.set_requestcookie (packet.requestcookie ());
         std::string logMe;
         if (packet.itype () == protocol::liTS_CANDIDATE)
         {
             // Request is for a transaction candidate set
             m_journal.trace << "Received request for TX candidate set data "
                             << to_string (this);
             if ((!packet.has_ledgerhash () || packet.ledgerhash ().size () != 32))
             {
                 charge (Resource::feeInvalidRequest);
                 m_journal.warning << "invalid request for TX candidate set data";
                 return;
             }
             uint256 txHash;
             memcpy (txHash.begin (), packet.ledgerhash ().data (), 32);
             {
                 Application::ScopedLockType lock (getApp ().getMasterLock ());
                 map = getApp().getOPs ().getTXMap (txHash);
             }
             if (!map)
             {
                 if (packet.has_querytype () && !packet.has_requestcookie ())
                 {
                     m_journal.debug << "Trying to route TX set request";
                     struct get_usable_peers
                     {
                         typedef Overlay::PeerSequence return_type;
                         Overlay::PeerSequence usablePeers;
                         uint256 const& txHash;
                         Peer const* skip;
                         get_usable_peers(uint256 const& hash, Peer const* s)
                             : txHash(hash), skip(s)
                         { }
                         void operator() (Peer::ptr const& peer)
{
                             if (peer->hasTxSet (txHash) && (peer.get () != skip))
                                 usablePeers.push_back (peer);
                         }
                         return_type operator() ()
{
                             return usablePeers;
                         }
                     };
                     Overlay::PeerSequence usablePeers (m_overlay.foreach (
                         get_usable_peers (txHash, this)));
                     if (usablePeers.empty ())
                     {
                         m_journal.info << "Unable to route TX set request";
                         return;
                     }
                     Peer::ptr const& selectedPeer = usablePeers[rand () % usablePeers.size ()];
                     packet.set_requestcookie (getShortId ());
                     selectedPeer->sendPacket (
                         boost::make_shared<Message> (packet, protocol::mtGET_LEDGER),
                         false);
                     return;
                 }
                 m_journal.error << "We do not have the map our peer wants "
                                 << to_string (this);
                 charge (Resource::feeInvalidRequest);
                 return;
             }
             reply.set_ledgerseq (0);
             reply.set_ledgerhash (txHash.begin (), txHash.size ());
             reply.set_type (protocol::liTS_CANDIDATE);
             fatLeaves = false; // We'll already have most transactions
             fatRoot = true; // Save a pass
         }
         else
         {
             if (getApp().getFeeTrack().isLoadedLocal() && !m_clusterNode)
             {
                 m_journal.debug << "Too busy to fetch ledger data";
                 return;
             }
             // Figure out what ledger they want
             m_journal.trace << "Received request for ledger data "
                             << to_string (this);
             Ledger::pointer ledger;
             if (packet.has_ledgerhash ())
             {
                 uint256 ledgerhash;
                 if (packet.ledgerhash ().size () != 32)
                 {
                     charge (Resource::feeInvalidRequest);
                     m_journal.warning << "Invalid request";
                     return;
                 }
                 memcpy (ledgerhash.begin (), packet.ledgerhash ().data (), 32);
                 logMe += "LedgerHash:";
                 logMe += ledgerhash.GetHex ();
                 ledger = getApp().getLedgerMaster ().getLedgerByHash (ledgerhash);
                 if (!ledger && m_journal.trace)
                     m_journal.trace << "Don't have ledger " << ledgerhash;
                 if (!ledger && (packet.has_querytype () && !packet.has_requestcookie ()))
                 {
                     std::uint32_t seq = 0;
                     if (packet.has_ledgerseq ())
                         seq = packet.ledgerseq ();
                     Overlay::PeerSequence peerList = m_overlay.getActivePeers ();
                         Overlay::PeerSequence usablePeers;
                         BOOST_FOREACH (Peer::ptr const& peer, peerList)
{
                             if (peer->hasLedger (ledgerhash, seq) && (peer.get () != this))
                                 usablePeers.push_back (peer);
                         }
                         if (usablePeers.empty ())
{
                             m_journal.trace << "Unable to route ledger request";
                             return;
                         }
                         Peer::ptr const& selectedPeer = usablePeers[rand () % usablePeers.size ()];
                         packet.set_requestcookie (getShortId ());
                         selectedPeer->sendPacket (
                             boost::make_shared<Message> (packet, protocol::mtGET_LEDGER), false);
                         m_journal.debug << "Ledger request routed";
                         return;
                     }
             }
             else if (packet.has_ledgerseq ())
             {
                 if (packet.ledgerseq() < getApp().getLedgerMaster().getEarliestFetch())
                 {
                     m_journal.debug << "Peer requests early ledger";
                     return;
                 }
                 ledger = getApp().getLedgerMaster ().getLedgerBySeq (packet.ledgerseq ());
                 if (!ledger && m_journal.debug)
                     m_journal.debug << "Don't have ledger " << packet.ledgerseq ();
             }
             else if (packet.has_ltype () && (packet.ltype () == protocol::ltCURRENT))
             {
                 ledger = getApp().getLedgerMaster ().getCurrentLedger ();
             }
             else if (packet.has_ltype () && (packet.ltype () == protocol::ltCLOSED) )
             {
                 ledger = getApp().getLedgerMaster ().getClosedLedger ();
                 if (ledger && !ledger->isClosed ())
                     ledger = getApp().getLedgerMaster ().getLedgerBySeq (ledger->getLedgerSeq () - 1);
             }
             else
             {
                 charge (Resource::feeInvalidRequest);
                 m_journal.warning << "Can't figure out what ledger they want";
                 return;
             }
             if ((!ledger) || (packet.has_ledgerseq () && (packet.ledgerseq () != ledger->getLedgerSeq ())))
             {
                 charge (Resource::feeInvalidRequest);
                 if (m_journal.warning && ledger)
                     m_journal.warning << "Ledger has wrong sequence";
                 return;
             }
                 if (!packet.has_ledgerseq() && (ledger->getLedgerSeq() < getApp().getLedgerMaster().getEarliestFetch()))
                 {
                     m_journal.debug << "Peer requests early ledger";
                     return;
                 }
             // Fill out the reply
             uint256 lHash = ledger->getHash ();
             reply.set_ledgerhash (lHash.begin (), lHash.size ());
             reply.set_ledgerseq (ledger->getLedgerSeq ());
             reply.set_type (packet.itype ());
             if (packet.itype () == protocol::liBASE)
             {
                 // they want the ledger base data
                 m_journal.trace << "They want ledger base data";
                 Serializer nData (128);
                 ledger->addRaw (nData);
                 reply.add_nodes ()->set_nodedata (nData.getDataPtr (), nData.getLength ());
                 SHAMap::pointer map = ledger->peekAccountStateMap ();
                 if (map && map->getHash ().isNonZero ())
                 {
                     // return account state root node if possible
                     Serializer rootNode (768);
                     if (map->getRootNode (rootNode, snfWIRE))
                     {
                         reply.add_nodes ()->set_nodedata (rootNode.getDataPtr (), rootNode.getLength ());
                         if (ledger->getTransHash ().isNonZero ())
{
                             map = ledger->peekTransactionMap ();
                             if (map && map->getHash ().isNonZero ())
{
                                 rootNode.erase ();
                                 if (map->getRootNode (rootNode, snfWIRE))
                                     reply.add_nodes ()->set_nodedata (rootNode.getDataPtr (), rootNode.getLength ());
                             }
                         }
                     }
                 }
                 Message::pointer oPacket = boost::make_shared<Message> (reply, protocol::mtLEDGER_DATA);
                 sendPacket (oPacket, false);
                 return;
             }
             if (packet.itype () == protocol::liTX_NODE)
             {
                 map = ledger->peekTransactionMap ();
                 logMe += " TX:";
                 logMe += map->getHash ().GetHex ();
             }
             else if (packet.itype () == protocol::liAS_NODE)
             {
                 map = ledger->peekAccountStateMap ();
                 logMe += " AS:";
                 logMe += map->getHash ().GetHex ();
             }
         }
         if (!map || (packet.nodeids_size () == 0))
         {
             m_journal.warning << "Can't find map or empty request";
             charge (Resource::feeInvalidRequest);
             return;
         }
         m_journal.trace << "Request: " << logMe;
         for (int i = 0; i < packet.nodeids ().size (); ++i)
         {
             SHAMapNode mn (packet.nodeids (i).data (), packet.nodeids (i).size ());
             if (!mn.isValid ())
             {
                 m_journal.warning << "Request for invalid node: " << logMe;
                 charge (Resource::feeInvalidRequest);
                 return;
             }
             std::vector<SHAMapNode> nodeIDs;
             std::list< Blob > rawNodes;
             try
             {
                 if (map->getNodeFat (mn, nodeIDs, rawNodes, fatRoot, fatLeaves))
                 {
                     assert (nodeIDs.size () == rawNodes.size ());
                     m_journal.trace << "getNodeFat got " << rawNodes.size () << " nodes";
                     std::vector<SHAMapNode>::iterator nodeIDIterator;
                     std::list< Blob >::iterator rawNodeIterator;
                     for (nodeIDIterator = nodeIDs.begin (), rawNodeIterator = rawNodes.begin ();
                             nodeIDIterator != nodeIDs.end (); ++nodeIDIterator, ++rawNodeIterator)
                     {
                         Serializer nID (33);
                         nodeIDIterator->addIDRaw (nID);
                         protocol::TMLedgerNode* node = reply.add_nodes ();
                         node->set_nodeid (nID.getDataPtr (), nID.getLength ());
                         node->set_nodedata (&rawNodeIterator->front (), rawNodeIterator->size ());
                     }
                 }
                 else
                     m_journal.warning << "getNodeFat returns false";
             }
             catch (std::exception&)
             {
                 std::string info;
                 if (packet.itype () == protocol::liTS_CANDIDATE)
                     info = "TS candidate";
                 else if (packet.itype () == protocol::liBASE)
                     info = "Ledger base";
                 else if (packet.itype () == protocol::liTX_NODE)
                     info = "TX node";
                 else if (packet.itype () == protocol::liAS_NODE)
                     info = "AS node";
                 if (!packet.has_ledgerhash ())
                     info += ", no hash specified";
                 m_journal.warning << "getNodeFat( " << mn << ") throws exception: " << info;
             }
         }
         Message::pointer oPacket = boost::make_shared<Message> (reply, protocol::mtLEDGER_DATA);
         sendPacket (oPacket, false);
     }
const RippleAddress& ripple::PeerImp::getNodePublic () const inline virtual
Implements ripple::Peer.
Definition at line 624 of file PeerImp.h.
References m_nodePublicKey.
Referenced by sendHello().
     {
         return m_nodePublicKey;
     }
beast::IP::Endpoint ripple::PeerImp::getRemoteAddress () const inline virtual
Implements ripple::Peer.
Definition at line 645 of file PeerImp.h.
References m_remoteAddress.
Referenced by ripple::to_string().
     {
         return m_remoteAddress;
     }
Peer::ShortId ripple::PeerImp::getShortId () const inline virtual
Implements ripple::Peer.
Definition at line 619 of file PeerImp.h.
References m_shortId.
Referenced by getLedger().
     {
         return m_shortId;
     }
MultiSocket& ripple::PeerImp::getStream () inline
Definition at line 289 of file PeerImp.h.
References m_socket.
Referenced by sendPacketForce(), startReadBody(), and startReadHeader().
     {
         return *m_socket;
     }
void ripple::PeerImp::handleReadBody (boost::system::error_code const & ec, std::size_t bytes) inline private
Definition at line 729 of file PeerImp.h.
References detach(), ripple::getApp(), beast::Journal::info, m_detaching, m_journal, processReadBuffer(), and startReadHeader().
Referenced by startReadBody().
     {
         if (m_detaching)
             return;
         if (ec == boost::asio::error::operation_aborted)
             return;
         if (ec)
         {
             m_journal.info << "ReadBody: " << ec.message ();
             {
             Application::ScopedLockType lock (getApp ().getMasterLock ());
             detach ("hrb");
             }
             return;
         }
         processReadBuffer ();
         startReadHeader ();
     }
void ripple::PeerImp::handleReadHeader (boost::system::error_code const & ec, std::size_t bytes) inline private
Definition at line 701 of file PeerImp.h.
References detach(), ripple::Message::getLength(), beast::Journal::info, m_detaching, m_journal, m_readBuffer, and startReadBody().
Referenced by startReadHeader().
     {
         if (m_detaching)
             return;
         if (ec == boost::asio::error::operation_aborted)
             return;
         if (ec)
         {
             m_journal.info << "ReadHeader: " << ec.message ();
             detach ("hrh1");
             return;
         }
         unsigned msg_len = Message::getLength (m_readBuffer);
         // WRITEME: Compare to maximum message length, abort if too large
         if ((msg_len > (32 * 1024 * 1024)) || (msg_len == 0))
         {
             detach ("hrh2");
             return;
         }
         startReadBody (msg_len);
     }
void ripple::PeerImp::handleShutdown (boost::system::error_code const & ec) inline private
Definition at line 651 of file PeerImp.h.
References detach(), beast::Journal::info, m_detaching, and m_journal.
Referenced by detach().
     {
         if (m_detaching)
             return;
         if (ec == boost::asio::error::operation_aborted)
             return;
         if (ec)
         {
             m_journal.info << "Shutdown: " << ec.message ();
             detach ("hsd");
             return;
         }
     }
void ripple::PeerImp::handleStart (boost::system::error_code const & ec) inline private
Definition at line 759 of file PeerImp.h.
References detach(), ripple::Resource::Consumer::disconnect(), beast::Journal::error, beast::Journal::info, m_detaching, m_inbound, m_journal, m_remoteAddress, m_resourceManager, m_usage, ripple::Resource::Manager::newInboundEndpoint(), ripple::Resource::Manager::newOutboundEndpoint(), sendHello(), and startReadHeader().
Referenced by accept(), and onConnect().
     {
         if (m_detaching)
             return;
         if (ec == boost::asio::error::operation_aborted)
             return;
         if (ec)
         {
             m_journal.info << "Handshake: " << ec.message ();
             detach ("hs");
             return;
         }
         if (m_inbound)
             m_usage = m_resourceManager.newInboundEndpoint (m_remoteAddress);
         else
             m_usage = m_resourceManager.newOutboundEndpoint (m_remoteAddress);
         if (m_usage.disconnect ())
         {
             detach ("resource");
             return;
         }
         if(!sendHello ())
         {
             m_journal.error << "Unable to send HELLO to " << m_remoteAddress;
             detach ("hello");
             return;
         }
         startReadHeader ();
     }
void ripple::PeerImp::handleVerifyTimer (boost::system::error_code const & ec) inline private
Definition at line 795 of file PeerImp.h.
References detach(), beast::Journal::info, m_detaching, and m_journal.
Referenced by connect().
     {
         if (m_detaching)
             return;
         if (ec == boost::asio::error::operation_aborted)
         {
             // Timer canceled because deadline no longer needed.
         }
         else if (ec)
         {
             m_journal.info << "Peer verify timer error";
         }
         else
         {
             //  m_journal.info << "Verify: Peer failed to verify in time.";
             detach ("hvt");
         }
     }
void ripple::PeerImp::handleWrite (boost::system::error_code const & ec, size_t bytes) inline private
Definition at line 667 of file PeerImp.h.
References detach(), beast::Journal::info, m_detaching, m_journal, mSendingPacket, mSendQ, and sendPacketForce().
Referenced by sendPacketForce().
     {
         if (m_detaching)
             return;
         // Call on IO strand
         mSendingPacket.reset ();
         if (ec == boost::asio::error::operation_aborted)
             return;
         if (m_detaching)
             return;
         if (ec)
         {
             m_journal.info << "Write: " << ec.message ();
             detach ("hw");
             return;
         }
         if (!mSendQ.empty ())
         {
             Message::pointer packet = mSendQ.front ();
             if (packet)
             {
                 sendPacketForce (packet);
                 mSendQ.pop_front ();
             }
         }
     }
bool ripple::PeerImp::hashLatestFinishedMessage (const SSL * sslSession, unsigned char * hash, size_t(*)(const SSL *, void *buf, size_t) getFinishedMessage) inline private
Hashes the latest finished message from an SSL stream
Parameters
sslSession the session to get the message from.
hash the buffer into which the hash of the retrieved message will be saved. The buffer MUST be at least 64 bytes long.
getMessage a pointer to the function to call to retrieve the finished message. This be either: SSL_get_finished or SSL_get_peer_finished.
Returns
true if successful, false otherwise.
Definition at line 1216 of file PeerImp.h.
References sslMinimumFinishedLength.
Referenced by calculateSessionCookie().
     {
         unsigned char buf[1024];
         // Get our finished message and hash it.
         std::memset(hash, 0, 64);
         size_t len = getFinishedMessage (sslSession, buf, sizeof (buf));
         if(len < sslMinimumFinishedLength)
             return false;
         SHA512 (buf, len, hash);
         return true;
     }
bool ripple::PeerImp::hasLedger (uint256 const & hash, std::uint32_t seq) const inline virtual
Implements ripple::Peer.
Definition at line 584 of file PeerImp.h.
References m_maxLedger, m_minLedger, m_recentLedgers, and m_recentLock.
     {
         boost::mutex::scoped_lock sl(m_recentLock);
         if ((seq != 0) && (seq >= m_minLedger) && (seq <= m_maxLedger))
             return true;
         BOOST_FOREACH (uint256 const & ledger, m_recentLedgers)
         {
             if (ledger == hash)
                 return true;
         }
         return false;
     }
bool ripple::PeerImp::hasRange (std::uint32_t uMin, std::uint32_t uMax) inline virtual
Implements ripple::Peer.
Definition at line 640 of file PeerImp.h.
References m_maxLedger, and m_minLedger.
     {
         return (uMin >= m_minLedger) && (uMax <= m_maxLedger);
     }
bool ripple::PeerImp::hasTxSet (uint256 const & hash) const inline virtual
Implements ripple::Peer.
Definition at line 608 of file PeerImp.h.
References m_recentLock, and m_recentTxSets.
     {
         boost::mutex::scoped_lock sl(m_recentLock);
         BOOST_FOREACH (uint256 const & set, m_recentTxSets)
         if (set == hash)
             return true;
         return false;
     }
bool ripple::PeerImp::isInCluster () const inline virtual
Implements ripple::Peer.
Definition at line 574 of file PeerImp.h.
References m_clusterNode.
Referenced by ripple::to_string().
     {
         return m_clusterNode;
     }
Json::Value ripple::PeerImp::json () inline virtual
Implements ripple::Peer.
Definition at line 504 of file PeerImp.h.
References ripple::BuildInfo::getCurrentProtocol(), ripple::base_uint< BITS >::GetHex(), ledgerRange(), m_closedLedgerHash, m_clusterNode, m_inbound, m_journal, m_nodeName, m_nodePublicKey, m_remoteAddress, mHello, mLastStatus, Json::objectValue, beast::IP::Endpoint::to_string(), ripple::BuildInfo::Protocol::toPacked(), ripple::CBase58Data::ToString(), and beast::Journal::warning.
     {
         Json::Value ret (Json::objectValue);
         ret["public_key"]   = m_nodePublicKey.ToString ();
         ret["address"]      = m_remoteAddress.to_string();
         if (m_inbound)
             ret["inbound"] = true;
         if (m_clusterNode)
         {
             ret["cluster"] = true;
             if (!m_nodeName.empty ())
                 ret["name"] = m_nodeName;
         }
         if (mHello.has_fullversion ())
             ret["version"] = mHello.fullversion ();
         if (mHello.has_protoversion () &&
                 (mHello.protoversion () != BuildInfo::getCurrentProtocol().toPacked ()))
         {
             ret["protocol"] = BuildInfo::Protocol (mHello.protoversion ()).toStdString ();
         }
         std::uint32_t minSeq, maxSeq;
         ledgerRange(minSeq, maxSeq);
         if ((minSeq != 0) || (maxSeq != 0))
             ret["complete_ledgers"] = boost::lexical_cast<std::string>(minSeq) + " - " +
                                       boost::lexical_cast<std::string>(maxSeq);
         if (!!m_closedLedgerHash)
             ret["ledger"] = m_closedLedgerHash.GetHex ();
         if (mLastStatus.has_newstatus ())
         {
             switch (mLastStatus.newstatus ())
             {
             case protocol::nsCONNECTING:
                 ret["status"] = "connecting";
                 break;
             case protocol::nsCONNECTED:
                 ret["status"] = "connected";
                 break;
             case protocol::nsMONITORING:
                 ret["status"] = "monitoring";
                 break;
             case protocol::nsVALIDATING:
                 ret["status"] = "validating";
                 break;
             case protocol::nsSHUTTING:
                 ret["status"] = "shutting";
                 break;
             default:
                 // FIXME: do we really want this?
                 m_journal.warning << "Unknown status: " << mLastStatus.newstatus ();
             }
         }
         return ret;
     }
void ripple::PeerImp::ledgerRange (std::uint32_t & minSeq, std::uint32_t & maxSeq) const inline virtual
Implements ripple::Peer.
Definition at line 600 of file PeerImp.h.
References m_maxLedger, m_minLedger, and m_recentLock.
Referenced by json().
     {
         boost::mutex::scoped_lock sl(m_recentLock);
         minSeq = m_minLedger;
         maxSeq = m_maxLedger;
     }
void ripple::PeerImp::onConnect (boost::system::error_code ec) inline
Outbound connection attempt has completed (not necessarily successfully)
The connection may fail for a number of reasons. Perhaps we do not have a route to the remote endpoint, or there is no server listening at that address.
If the connection succeeded, we transition to the stateConnected state and move on.
If the connection failed, we simply disconnect.
Parameters
ec indicates success or an error code.
Definition at line 389 of file PeerImp.h.
References bassert, detach(), beast::IPAddressConversion::from_asio(), handleStart(), beast::Journal::info, m_detaching, m_journal, m_peerFinder, m_remoteAddress, m_slot, m_socket, m_state, m_strand, ripple::PeerFinder::Manager::on_connected(), stateConnected, and stateConnecting.
Referenced by connect().
     {
         if (m_detaching)
             return;
         NativeSocketType::endpoint_type local_endpoint;
         if (! ec)
             local_endpoint = m_socket->this_layer <
                 NativeSocketType> ().local_endpoint (ec);
         if (ec)
         {
             // VFALCO NOTE This log statement looks like ass
             m_journal.info <<
                 "Connect to " << m_remoteAddress <<
                 " failed: " << ec.message();
             // This should end up calling onPeerClosed()
             detach ("hc");
             return;
         }
         bassert (m_state == stateConnecting);
         m_state = stateConnected;
         m_peerFinder.on_connected (m_slot,
             beast::IPAddressConversion::from_asio (local_endpoint));
         m_socket->set_verify_mode (boost::asio::ssl::verify_none);
         m_socket->async_handshake (
             boost::asio::ssl::stream_base::client,
             m_strand.wrap (boost::bind (&PeerImp::handleStart,
                 boost::static_pointer_cast <PeerImp> (shared_from_this ()),
                     boost::asio::placeholders::error)));
     }
PeerImp& ripple::PeerImp::operator= (PeerImp const &) delete
void ripple::PeerImp::processReadBuffer () inline private
Definition at line 816 of file PeerImp.h.
References detach(), ripple::getApp(), ripple::Message::getType(), ripple::jtPEER, ripple::Message::kHeaderBytes, m_journal, m_readBuffer, m_state, recvAccount(), recvCluster(), recvContact(), recvEndpoints(), recvErrorMessage(), recvGetAccount(), recvGetContacts(), recvGetLedger(), recvGetObjectByHash(), recvGetPeers(), recvHaveTxSet(), recvHello(), recvLedger(), recvPeers(), recvPing(), recvProofWork(), recvPropose(), recvSearchTransaction(), recvStatus(), recvTransaction(), recvValidation(), stateActive, stateHandshaked, ripple::strHex(), and beast::Journal::warning.
Referenced by handleReadBody().
     {
         // must not hold peer lock
         int type = Message::getType (m_readBuffer);
         LoadEvent::autoptr event (
             getApp().getJobQueue ().getLoadEventAP (jtPEER, "Peer::read"));
         {
             // An mtHELLO message must be the first message receiced by a peer
             // and it must be received *exactly* once during a connection; any
             // other scenario constitutes a protocol violation.
             if ((m_state == stateHandshaked) && (type == protocol::mtHELLO))
             {
                 m_journal.warning << "Protocol: HELLO expected!";
                 detach ("prb-hello-expected");
                 return;
             }
             if ((m_state == stateActive) && (type == protocol::mtHELLO))
             {
                 m_journal.warning << "Protocol: HELLO unexpected!";
                 detach ("prb-hello-unexpected");
                 return;
             }
             size_t msgLen (m_readBuffer.size () - Message::kHeaderBytes);
             switch (type)
             {
             case protocol::mtHELLO:
             {
                 event->reName ("Peer::hello");
                 protocol::TMHello msg;
                 if (msg.ParseFromArray (&m_readBuffer[Message::kHeaderBytes],
                                         msgLen))
                     recvHello (msg);
                 else
                     m_journal.warning << "parse error: " << type;
             }
                 break;
             case protocol::mtCLUSTER:
             {
                 event->reName ("Peer::cluster");
                 protocol::TMCluster msg;
                 if (msg.ParseFromArray (&m_readBuffer[Message::kHeaderBytes],
                                         msgLen))
                     recvCluster (msg);
                 else
                     m_journal.warning << "parse error: " << type;
             }
                 break;
             case protocol::mtERROR_MSG:
             {
                 event->reName ("Peer::errormessage");
                 protocol::TMErrorMsg msg;
                 if (msg.ParseFromArray (&m_readBuffer[Message::kHeaderBytes],
                                         msgLen))
                     recvErrorMessage (msg);
                 else
                     m_journal.warning << "parse error: " << type;
             }
                 break;
             case protocol::mtPING:
             {
                 event->reName ("Peer::ping");
                 protocol::TMPing msg;
                 if (msg.ParseFromArray (&m_readBuffer[Message::kHeaderBytes],
                                         msgLen))
                     recvPing (msg);
                 else
                     m_journal.warning << "parse error: " << type;
             }
                 break;
             case protocol::mtGET_CONTACTS:
             {
                 event->reName ("Peer::getcontacts");
                 protocol::TMGetContacts msg;
                 if (msg.ParseFromArray (&m_readBuffer[Message::kHeaderBytes],
                                         msgLen))
                     recvGetContacts (msg);
                 else
                     m_journal.warning << "parse error: " << type;
             }
                 break;
             case protocol::mtCONTACT:
             {
                 event->reName ("Peer::contact");
                 protocol::TMContact msg;
                 if (msg.ParseFromArray (&m_readBuffer[Message::kHeaderBytes],
                                         msgLen))
                     recvContact (msg);
                 else
                     m_journal.warning << "parse error: " << type;
             }
                 break;
             case protocol::mtGET_PEERS:
             {
                 event->reName ("Peer::getpeers");
                 protocol::TMGetPeers msg;
                 if (msg.ParseFromArray (&m_readBuffer[Message::kHeaderBytes],
                                         msgLen))
                     recvGetPeers (msg);
                 else
                     m_journal.warning << "parse error: " << type;
             }
                 break;
             case protocol::mtPEERS:
             {
                 event->reName ("Peer::peers");
                 protocol::TMPeers msg;
                 if (msg.ParseFromArray (&m_readBuffer[Message::kHeaderBytes],
                                         msgLen))
                     recvPeers (msg);
                 else
                     m_journal.warning << "parse error: " << type;
             }
                 break;
             case protocol::mtENDPOINTS:
             {
                 event->reName ("Peer::endpoints");
                 protocol::TMEndpoints msg;
                 if(msg.ParseFromArray (&m_readBuffer[Message::kHeaderBytes],
                                        msgLen))
                     recvEndpoints (msg);
                 else
                     m_journal.warning << "parse error: " << type;;
             }
                 break;
             case protocol::mtSEARCH_TRANSACTION:
             {
                 event->reName ("Peer::searchtransaction");
                 protocol::TMSearchTransaction msg;
                 if (msg.ParseFromArray (&m_readBuffer[Message::kHeaderBytes],
                                         msgLen))
                     recvSearchTransaction (msg);
                 else
                     m_journal.warning << "parse error: " << type;
             }
                 break;
             case protocol::mtGET_ACCOUNT:
             {
                 event->reName ("Peer::getaccount");
                 protocol::TMGetAccount msg;
                 if (msg.ParseFromArray (&m_readBuffer[Message::kHeaderBytes],
                                         msgLen))
                     recvGetAccount (msg);
                 else
                     m_journal.warning << "parse error: " << type;
             }
                 break;
             case protocol::mtACCOUNT:
             {
                 event->reName ("Peer::account");
                 protocol::TMAccount msg;
                 if (msg.ParseFromArray (&m_readBuffer[Message::kHeaderBytes],
                                         msgLen))
                     recvAccount (msg);
                 else
                     m_journal.warning << "parse error: " << type;
             }
                 break;
             case protocol::mtTRANSACTION:
             {
                 event->reName ("Peer::transaction");
                 protocol::TMTransaction msg;
                 if (msg.ParseFromArray (&m_readBuffer[Message::kHeaderBytes],
                                         msgLen))
                     recvTransaction (msg);
                 else
                     m_journal.warning << "parse error: " << type;
             }
                 break;
             case protocol::mtSTATUS_CHANGE:
             {
                 event->reName ("Peer::statuschange");
                 protocol::TMStatusChange msg;
                 if (msg.ParseFromArray (&m_readBuffer[Message::kHeaderBytes],
                                         msgLen))
                     recvStatus (msg);
                 else
                     m_journal.warning << "parse error: " << type;
             }
                 break;
             case protocol::mtPROPOSE_LEDGER:
             {
                 event->reName ("Peer::propose");
                 boost::shared_ptr<protocol::TMProposeSet> msg (
                     boost::make_shared<protocol::TMProposeSet> ());
                 if (msg->ParseFromArray (&m_readBuffer[Message::kHeaderBytes],
                                          msgLen))
                     recvPropose (msg);
                 else
                     m_journal.warning << "parse error: " << type;
             }
                 break;
             case protocol::mtGET_LEDGER:
             {
                 event->reName ("Peer::getledger");
                 boost::shared_ptr<protocol::TMGetLedger> msg (
                     boost::make_shared<protocol::TMGetLedger> ());
                 if (msg->ParseFromArray (&m_readBuffer[Message::kHeaderBytes],
                                         msgLen))
                     recvGetLedger (msg);
                 else
                     m_journal.warning << "parse error: " << type;
             }
                 break;
             case protocol::mtLEDGER_DATA:
             {
                 event->reName ("Peer::ledgerdata");
                 boost::shared_ptr<protocol::TMLedgerData> msg (
                     boost::make_shared<protocol::TMLedgerData> ());
                 if (msg->ParseFromArray (&m_readBuffer[Message::kHeaderBytes],
                                          msgLen))
                     recvLedger (msg);
                 else
                     m_journal.warning << "parse error: " << type;
             }
                 break;
             case protocol::mtHAVE_SET:
             {
                 event->reName ("Peer::haveset");
                 protocol::TMHaveTransactionSet msg;
                 if (msg.ParseFromArray (&m_readBuffer[Message::kHeaderBytes],
                                         msgLen))
                     recvHaveTxSet (msg);
                 else
                     m_journal.warning << "parse error: " << type;
             }
                 break;
             case protocol::mtVALIDATION:
             {
                 event->reName ("Peer::validation");
                 boost::shared_ptr<protocol::TMValidation> msg (
                     boost::make_shared<protocol::TMValidation> ());
                 if (msg->ParseFromArray (&m_readBuffer[Message::kHeaderBytes],
                                          msgLen))
                     recvValidation (msg);
                 else
                     m_journal.warning << "parse error: " << type;
             }
                 break;
 #if 0
             case protocol::mtGET_VALIDATION:
             {
                 protocol::TM msg;
                 if (msg.ParseFromArray (&m_readBuffer[Message::kHeaderBytes], msgLen))
                     recv (msg);
                 else
                     m_journal.warning << "parse error: " << type;
             }
                 break;
 #endif
             case protocol::mtGET_OBJECTS:
             {
                 event->reName ("Peer::getobjects");
                 boost::shared_ptr<protocol::TMGetObjectByHash> msg =
                     boost::make_shared<protocol::TMGetObjectByHash> ();
                 if (msg->ParseFromArray (&m_readBuffer[Message::kHeaderBytes],
                                          msgLen))
                     recvGetObjectByHash (msg);
                 else
                     m_journal.warning << "parse error: " << type;
             }
                 break;
             case protocol::mtPROOFOFWORK:
             {
                 event->reName ("Peer::proofofwork");
                 protocol::TMProofWork msg;
                 if (msg.ParseFromArray (&m_readBuffer[Message::kHeaderBytes],
                                         msgLen))
                     recvProofWork (msg);
                 else
                     m_journal.warning << "parse error: " << type;
             }
                 break;
             default:
                 event->reName ("Peer::unknown");
                 m_journal.warning << "Unknown Msg: " << type;
                 m_journal.warning << strHex (&m_readBuffer[0], m_readBuffer.size ());
             }
         }
     }
void ripple::PeerImp::recvAccount (protocol::TMAccount & packet) inline private
Definition at line 1835 of file PeerImp.h.
Referenced by processReadBuffer().
     {
     }
void ripple::PeerImp::recvCluster (protocol::TMCluster & packet) inline private
Definition at line 1454 of file PeerImp.h.
References ripple::Resource::Gossip::Item::address, ripple::Resource::Gossip::Item::balance, charge(), ripple::Resource::feeUnwantedData, beast::IP::Endpoint::from_string(), ripple::getApp(), ripple::Application::getFeeTrack(), ripple::Application::getUNL(), ripple::Resource::Manager::importConsumers(), ripple::Resource::Gossip::items, m_clusterNode, m_nodeName, m_resourceManager, name, ripple::UniqueNodeList::nodeUpdate(), ripple::LoadFeeTrack::setClusterFee(), and ripple::RippleAddress::setNodePublic().
Referenced by processReadBuffer().
     {
         if (!m_clusterNode)
         {
             charge (Resource::feeUnwantedData);
             return;
         }
         for (int i = 0; i < packet.clusternodes().size(); ++i)
         {
             protocol::TMClusterNode const& node = packet.clusternodes(i);
             std::string name;
             if (node.has_nodename())
                 name = node.nodename();
             ClusterNodeStatus s(name, node.nodeload(), node.reporttime());
             RippleAddress nodePub;
             nodePub.setNodePublic(node.publickey());
             getApp().getUNL().nodeUpdate(nodePub, s);
         }
         int loadSources = packet.loadsources().size();
         if (loadSources != 0)
         {
             Resource::Gossip gossip;
             gossip.items.reserve (loadSources);
             for (int i = 0; i < packet.loadsources().size(); ++i)
             {
                 protocol::TMLoadSource const& node = packet.loadsources (i);
                 Resource::Gossip::Item item;
                 item.address = beast::IP::Endpoint::from_string (node.name());
                 item.balance = node.cost();
                 if (item.address != beast::IP::Endpoint())
                     gossip.items.push_back(item);
             }
             m_resourceManager.importConsumers (m_nodeName, gossip);
         }
         getApp().getFeeTrack().setClusterFee(getApp().getUNL().getClusterFee());
     }
void ripple::PeerImp::recvContact (protocol::TMContact & packet) inline private
Definition at line 1614 of file PeerImp.h.
Referenced by processReadBuffer().
     {
     }
void ripple::PeerImp::recvEndpoints (protocol::TMEndpoints & packet) inline private
Definition at line 1660 of file PeerImp.h.
References ripple::PeerFinder::Endpoint::address, beast::IP::Endpoint::at_port(), ripple::PeerFinder::Endpoint::hops, m_peerFinder, m_remoteAddress, m_slot, and ripple::PeerFinder::Manager::on_endpoints().
Referenced by processReadBuffer().
     {
         std::vector <PeerFinder::Endpoint> endpoints;
         endpoints.reserve (packet.endpoints().size());
         for (int i = 0; i < packet.endpoints ().size (); ++i)
         {
             PeerFinder::Endpoint endpoint;
             protocol::TMEndpoint const& tm (packet.endpoints(i));
             // hops
             endpoint.hops = tm.hops();
             // ipv4
             if (endpoint.hops > 0)
             {
                 in_addr addr;
                 addr.s_addr = tm.ipv4().ipv4();
                 beast::IP::AddressV4 v4 (ntohl (addr.s_addr));
                 endpoint.address = beast::IP::Endpoint (v4, tm.ipv4().ipv4port ());
             }
             else
             {
                 // This Endpoint describes the peer we are connected to.
                 // We will take the remote address seen on the socket and
                 // store that in the IP::Endpoint. If this is the first time,
                 // then we'll verify that their listener can receive incoming
                 // by performing a connectivity test.
                 //
                 endpoint.address = m_remoteAddress.at_port (
                     tm.ipv4().ipv4port ());
             }
             endpoints.push_back (endpoint);
         }
         if (! endpoints.empty())
             m_peerFinder.on_endpoints (m_slot, endpoints);
     }
void ripple::PeerImp::recvErrorMessage (protocol::TMErrorMsg & packet) inline private
Definition at line 1823 of file PeerImp.h.
Referenced by processReadBuffer().
     {
     }
void ripple::PeerImp::recvGetAccount (protocol::TMGetAccount & packet) inline private
Definition at line 1831 of file PeerImp.h.
Referenced by processReadBuffer().
     {
     }
void ripple::PeerImp::recvGetContacts (protocol::TMGetContacts & packet) inline private
Definition at line 1618 of file PeerImp.h.
Referenced by processReadBuffer().
     {
     }
void ripple::PeerImp::recvGetLedger (boost::shared_ptr< protocol::TMGetLedger > const & packet) inline private
Definition at line 1839 of file PeerImp.h.
References ripple::JobQueue::addJob(), ripple::getApp(), ripple::Application::getJobQueue(), ripple::jtPACK, and sGetLedger().
Referenced by processReadBuffer().
     {
         getApp().getJobQueue().addJob (jtPACK, "recvGetLedger",
             std::bind (&sGetLedger, boost::weak_ptr<PeerImp> (shared_from_this ()), packet));
     }
void ripple::PeerImp::recvGetObjectByHash (const boost::shared_ptr< protocol::TMGetObjectByHash > & ptr) inline private
Definition at line 1701 of file PeerImp.h.
References beast::Journal::active(), ripple::NetworkOPs::addFetchPack(), ripple::base_uint< BITS >::begin(), beast::Journal::debug, doFetchPack(), ripple::NodeStore::Database::fetch(), ripple::getApp(), ripple::Application::getNodeStore(), ripple::Application::getOPs(), ripple::NetworkOPs::gotFetchPack(), hash, ripple::NetworkOPs::haveLedger(), rocksdb::if(), m_journal, sendPacket(), ripple::base_uint< BITS >::size(), ripple::to_string(), and beast::Journal::trace.
Referenced by processReadBuffer().
     {
         protocol::TMGetObjectByHash& packet = *ptr;
         if (packet.query ())
         {
             // this is a query
             if (packet.type () == protocol::TMGetObjectByHash::otFETCH_PACK)
             {
                 doFetchPack (ptr);
                 return;
             }
             protocol::TMGetObjectByHash reply;
             reply.set_query (false);
             if (packet.has_seq ())
                 reply.set_seq (packet.seq ());
             reply.set_type (packet.type ());
             if (packet.has_ledgerhash ())
                 reply.set_ledgerhash (packet.ledgerhash ());
             // This is a very minimal implementation
             for (int i = 0; i < packet.objects_size (); ++i)
             {
                 uint256 hash;
                 const protocol::TMIndexedObject& obj = packet.objects (i);
                 if (obj.has_hash () && (obj.hash ().size () == (256 / 8)))
                 {
                     memcpy (hash.begin (), obj.hash ().data (), 256 / 8);
                     NodeObject::pointer hObj = getApp().getNodeStore ().fetch (hash);
                     if (hObj)
                     {
                         protocol::TMIndexedObject& newObj = *reply.add_objects ();
                         newObj.set_hash (hash.begin (), hash.size ());
                         newObj.set_data (&hObj->getData ().front (), hObj->getData ().size ());
                         if (obj.has_nodeid ())
                             newObj.set_index (obj.nodeid ());
                         if (!reply.has_seq () && (hObj->getIndex () != 0))
                             reply.set_seq (hObj->getIndex ());
                     }
                 }
             }
             m_journal.trace << "GetObjByHash had " << reply.objects_size () <<
                                " of " << packet.objects_size () <<
                                " for " << to_string (this);
             sendPacket (
                 boost::make_shared<Message> (reply, protocol::mtGET_OBJECTS),
                 true);
         }
         else
         {
             // this is a reply
             std::uint32_t pLSeq = 0;
             bool pLDo = true;
             bool progress = false;
             for (int i = 0; i < packet.objects_size (); ++i)
             {
                 const protocol::TMIndexedObject& obj = packet.objects (i);
                 if (obj.has_hash () && (obj.hash ().size () == (256 / 8)))
                 {
                     if (obj.has_ledgerseq ())
                     {
                         if (obj.ledgerseq () != pLSeq)
{
                             if ((pLDo && (pLSeq != 0)) &&
                                 m_journal.active(beast::Journal::Severity::kDebug))
                                 m_journal.debug << "Received full fetch pack for " << pLSeq;
                             pLSeq = obj.ledgerseq ();
                             pLDo = !getApp().getOPs ().haveLedger (pLSeq);
                             if (!pLDo)
                                  m_journal.debug << "Got pack for " << pLSeq << " too late";
                             else
                                 progress = true;
                         }
                     }
                     if (pLDo)
                     {
                         uint256 hash;
                         memcpy (hash.begin (), obj.hash ().data (), 256 / 8);
                         boost::shared_ptr< Blob > data (
                             boost::make_shared< Blob > (
                                 obj.data ().begin (), obj.data ().end ()));
                         getApp().getOPs ().addFetchPack (hash, data);
                     }
                 }
             }
             if ((pLDo && (pLSeq != 0)) &&
                 m_journal.active(beast::Journal::Severity::kDebug))
                 m_journal.debug << "Received partial fetch pack for " << pLSeq;
             if (packet.type () == protocol::TMGetObjectByHash::otFETCH_PACK)
                 getApp().getOPs ().gotFetchPack (progress, pLSeq);
         }
     }
void ripple::PeerImp::recvGetPeers (protocol::TMGetPeers & packet) inline private
Definition at line 1624 of file PeerImp.h.
References sendPacket().
Referenced by processReadBuffer().
     {
 #if 0
         protocol::TMPeers peers;
         // CODEME: This is deprecated because of PeerFinder, but populate the
         // response with some data here anyways, and send if non-empty.
         sendPacket (
             boost::make_shared<Message> (peers, protocol::mtPEERS),
             true);
 #endif
     }
void ripple::PeerImp::recvGetValidation (protocol::TMGetValidations & packet) inline private
Definition at line 1610 of file PeerImp.h.
     {
     }
void ripple::PeerImp::recvHaveTxSet (protocol::TMHaveTransactionSet & packet) inline private
Definition at line 2066 of file PeerImp.h.
References addTxSet(), ripple::base_uint< BITS >::begin(), charge(), ripple::Resource::feeInvalidRequest, ripple::Resource::feeUnwantedData, ripple::getApp(), and hash.
Referenced by processReadBuffer().
     {
         uint256 hashes;
         if (packet.hash ().size () != (256 / 8))
         {
             charge (Resource::feeInvalidRequest);
             return;
         }
         uint256 hash;
         // VFALCO TODO There should be no use of memcpy() throughout the program.
         //        TODO Clean up this magic number
         //
         memcpy (hash.begin (), packet.hash ().data (), 32);
         if (packet.status () == protocol::tsHAVE)
             addTxSet (hash);
         {
             Application::ScopedLockType lock (getApp ().getMasterLock ());
             if (!getApp().getOPs ().hasTXSet (shared_from_this (), hash, packet.status ()))
                 charge (Resource::feeUnwantedData);
         }
     }
void ripple::PeerImp::recvHello (protocol::TMHello & packet) inline private
Definition at line 1341 of file PeerImp.h.
References beast::Journal::active(), addLedger(), bassert, ripple::base_uint< BITS >::begin(), ripple::RippleAddress::clear(), clockToleranceDeltaSeconds, beast::Journal::debug, detach(), ripple::getApp(), ripple::BuildInfo::getCurrentProtocol(), ripple::Application::getUNL(), ripple::RippleAddress::humanNodePublic(), beast::Journal::info, m_closedLedgerHash, m_clusterNode, m_journal, m_nodeName, m_nodePublicKey, m_peerFinder, m_previousLedgerHash, m_secureCookie, m_slot, m_state, m_timer, mHello, ripple::UniqueNodeList::nodeInCluster(), ripple::PeerFinder::Manager::on_handshake(), sendGetPeers(), ripple::RippleAddress::setNodePublic(), stateConnected, stateHandshaked, ripple::BuildInfo::Protocol::toPacked(), ripple::RippleAddress::verifyNodePublic(), and ripple::base_uint< BITS >::zero().
Referenced by processReadBuffer().
     {
         bool    bDetach = true;
         (void) m_timer.cancel ();
         std::uint32_t const ourTime (getApp().getOPs ().getNetworkTimeNC ());
         std::uint32_t const minTime (ourTime - clockToleranceDeltaSeconds);
         std::uint32_t const maxTime (ourTime + clockToleranceDeltaSeconds);
     #ifdef BEAST_DEBUG
         if (packet.has_nettime ())
         {
             std::int64_t to = ourTime;
             to -= packet.nettime ();
             m_journal.debug << "Connect: time offset " << to;
         }
     #endif
         BuildInfo::Protocol protocol (packet.protoversion());
         if (packet.has_nettime () &&
             ((packet.nettime () < minTime) || (packet.nettime () > maxTime)))
         {
             if (packet.nettime () > maxTime)
             {
                 m_journal.info << "Hello: Clock for " << *this <<
                                   " is off by +" << packet.nettime () - ourTime;
             }
             else if (packet.nettime () < minTime)
             {
                 m_journal.info << "Hello: Clock for " << *this <<
                                   " is off by -" << ourTime - packet.nettime ();
             }
         }
         else if (packet.protoversionmin () > BuildInfo::getCurrentProtocol().toPacked ())
         {
             std::string reqVersion (
                 protocol.toStdString ());
             std::string curVersion (
                 BuildInfo::getCurrentProtocol().toStdString ());
             m_journal.info << "Hello: Disconnect: Protocol mismatch [" <<
                               "Peer expects " << reqVersion <<
                               " and we run " << curVersion << "]";
         }
         else if (!m_nodePublicKey.setNodePublic (packet.nodepublic ()))
         {
             m_journal.info << "Hello: Disconnect: Bad node public key.";
         }
         else if (!m_nodePublicKey.verifyNodePublic (m_secureCookie, packet.nodeproof (), ECDSA::not_strict))
         {
             // Unable to verify they have private key for claimed public key.
             m_journal.info << "Hello: Disconnect: Failed to verify session.";
         }
         else
         {
             // Successful connection.
             m_journal.info << "Hello: Connect: " << m_nodePublicKey.humanNodePublic ();
             if ((protocol != BuildInfo::getCurrentProtocol()) &&
                 m_journal.active(beast::Journal::Severity::kInfo))
             {
                 m_journal.info << "Peer protocol: " << protocol.toStdString ();
             }
             mHello = packet;
             // Determine if this peer belongs to our cluster and get it's name
             m_clusterNode = getApp().getUNL().nodeInCluster (m_nodePublicKey, m_nodeName);
             if(m_clusterNode)
                 m_journal.info << "Connected to cluster node " << m_nodeName;
             bassert (m_state == stateConnected);
             m_state = stateHandshaked;
             m_peerFinder.on_handshake (m_slot, RipplePublicKey(m_nodePublicKey),
                 m_clusterNode);
             // XXX Set timer: connection is in grace period to be useful.
             // XXX Set timer: connection idle (idle may vary depending on connection type.)
             if ((mHello.has_ledgerclosed ()) && (mHello.ledgerclosed ().size () == (256 / 8)))
             {
                 memcpy (m_closedLedgerHash.begin (), mHello.ledgerclosed ().data (), 256 / 8);
                 if ((mHello.has_ledgerprevious ()) && (mHello.ledgerprevious ().size () == (256 / 8)))
                 {
                     memcpy (m_previousLedgerHash.begin (), mHello.ledgerprevious ().data (), 256 / 8);
                     addLedger (m_previousLedgerHash);
                 }
                 else
                 {
                     m_previousLedgerHash.zero ();
                 }
             }
             bDetach = false;
         }
         if (bDetach)
         {
             m_nodePublicKey.clear ();
             detach ("recvh");
         }
         else
         {
             sendGetPeers ();
         }
     }
void ripple::PeerImp::recvLedger (boost::shared_ptr< protocol::TMLedgerData > const & packet_ptr) inline private
Definition at line 1845 of file PeerImp.h.
References ripple::base_uint< BITS >::begin(), charge(), ripple::Resource::feeInvalidRequest, ripple::Resource::feeUnwantedData, ripple::OverlayImpl::findPeerByShortID(), ripple::getApp(), ripple::Application::getOPs(), ripple::NetworkOPs::gotTXData(), hash, beast::Journal::info, ripple::SHAMapAddNode::isInvalid(), ripple::lsTRACE, m_journal, m_overlay, beast::Journal::warning, and WriteLog.
Referenced by processReadBuffer().
     {
         protocol::TMLedgerData& packet = *packet_ptr;
         if (packet.nodes ().size () <= 0)
         {
             m_journal.warning << "Ledger/TXset data with no nodes";
             return;
         }
         if (packet.has_requestcookie ())
         {
             Peer::ptr target = m_overlay.findPeerByShortID (packet.requestcookie ());
             if (target)
             {
                 packet.clear_requestcookie ();
                 target->sendPacket (boost::make_shared<Message> (packet, protocol::mtLEDGER_DATA), false);
             }
             else
             {
                 m_journal.info << "Unable to route TX/ledger data reply";
                 charge (Resource::feeUnwantedData);
             }
             return;
         }
         uint256 hash;
         if (packet.ledgerhash ().size () != 32)
         {
             m_journal.warning << "TX candidate reply with invalid hash size";
             charge (Resource::feeInvalidRequest);
             return;
         }
         memcpy (hash.begin (), packet.ledgerhash ().data (), 32);
         if (packet.type () == protocol::liTS_CANDIDATE)
         {
             // got data for a candidate transaction set
             std::list<SHAMapNode> nodeIDs;
             std::list< Blob > nodeData;
             for (int i = 0; i < packet.nodes ().size (); ++i)
             {
                 const protocol::TMLedgerNode& node = packet.nodes (i);
                 if (!node.has_nodeid () || !node.has_nodedata () || (node.nodeid ().size () != 33))
                 {
                     m_journal.warning << "LedgerData request with invalid node ID";
                     charge (Resource::feeInvalidRequest);
                     return;
                 }
                 nodeIDs.push_back (SHAMapNode (node.nodeid ().data (), node.nodeid ().size ()));
                 nodeData.push_back (Blob (node.nodedata ().begin (), node.nodedata ().end ()));
             }
             SHAMapAddNode san;
             {
                 Application::ScopedLockType lock (getApp ().getMasterLock ());
                 san =  getApp().getOPs ().gotTXData (shared_from_this (), hash, nodeIDs, nodeData);
             }
             if (san.isInvalid ())
             {
                 charge (Resource::feeUnwantedData);
             }
             return;
         }
         if (!getApp().getInboundLedgers ().gotLedgerData (hash, shared_from_this(), packet_ptr))
         {
             WriteLog (lsTRACE, Peer) << "Got data for unwanted ledger";
             charge (Resource::feeUnwantedData);
         }
     }
void ripple::PeerImp::recvPeers (protocol::TMPeers & packet) inline private
Definition at line 1639 of file PeerImp.h.
References m_peerFinder, and ripple::PeerFinder::Manager::on_legacy_endpoints().
Referenced by processReadBuffer().
     {
         std::vector <beast::IP::Endpoint> list;
         list.reserve (packet.nodes().size());
         for (int i = 0; i < packet.nodes ().size (); ++i)
         {
             in_addr addr;
             addr.s_addr = packet.nodes (i).ipv4 ();
             {
                 beast::IP::AddressV4 v4 (ntohl (addr.s_addr));
                 beast::IP::Endpoint address (v4, packet.nodes (i).ipv4port ());
                 list.push_back (address);
             }
         }
         if (! list.empty())
             m_peerFinder.on_legacy_endpoints (list);
     }
void ripple::PeerImp::recvPing (protocol::TMPing & packet) inline private
Definition at line 1814 of file PeerImp.h.
References sendPacket().
Referenced by processReadBuffer().
     {
         if (packet.type () == protocol::TMPing::ptPING)
         {
             packet.set_type (protocol::TMPing::ptPONG);
             sendPacket (boost::make_shared<Message> (packet, protocol::mtPING), true);
         }
     }
void ripple::PeerImp::recvProofWork (protocol::TMProofWork & packet) inline private
Definition at line 2094 of file PeerImp.h.
References ripple::JobQueue::addJob(), ripple::base_uint< BITS >::begin(), BIND_TYPE, charge(), ripple::ProofOfWorkFactory::checkProof(), doProofOfWork(), ripple::Resource::feeBadProofOfWork, ripple::Resource::feeInvalidRequest, ripple::getApp(), ripple::Application::getJobQueue(), ripple::Application::getProofOfWorkFactory(), ripple::jtPROOFWORK, ripple::lsINFO, P_1, ripple::powOK, ripple::powTOOEASY, and WriteLog.
Referenced by processReadBuffer().
     {
         if (packet.has_response ())
         {
             // this is an answer to a proof of work we requested
             if (packet.response ().size () != (256 / 8))
             {
                 charge (Resource::feeInvalidRequest);
                 return;
             }
             uint256 response;
             memcpy (response.begin (), packet.response ().data (), 256 / 8);
             // VFALCO TODO Use a dependency injection here
             PowResult r = getApp().getProofOfWorkFactory ().checkProof (packet.token (), response);
             if (r == powOK)
             {
                 // credit peer
                 // WRITEME
                 return;
             }
             // return error message
             // WRITEME
             if (r != powTOOEASY)
             {
                 charge (Resource::feeBadProofOfWork);
             }
             return;
         }
         if (packet.has_result ())
         {
             // this is a reply to a proof of work we sent
             // WRITEME
         }
         if (packet.has_target () && packet.has_challenge () && packet.has_iterations ())
         {
             // this is a challenge
             // WRITEME: Reject from inbound connections
             uint256 challenge, target;
             if ((packet.challenge ().size () != (256 / 8)) || (packet.target ().size () != (256 / 8)))
             {
                 charge (Resource::feeInvalidRequest);
                 return;
             }
             memcpy (challenge.begin (), packet.challenge ().data (), 256 / 8);
             memcpy (target.begin (), packet.target ().data (), 256 / 8);
             ProofOfWork::pointer pow = boost::make_shared<ProofOfWork> (packet.token (), packet.iterations (),
                                        challenge, target);
             if (!pow->isValid ())
             {
                 charge (Resource::feeInvalidRequest);
                 return;
             }
     #if 0   // Until proof of work is completed, don't do it
             getApp().getJobQueue ().addJob (
                 jtPROOFWORK,
                 "recvProof->doProof",
                 BIND_TYPE (&PeerImp::doProofOfWork, P_1, boost::weak_ptr <Peer> (shared_from_this ()), pow));
     #endif
             return;
         }
         WriteLog (lsINFO, Peer) << "Received in valid proof of work object from peer";
     }
void ripple::PeerImp::recvPropose (const boost::shared_ptr< protocol::TMProposeSet > & packet) inline private
Definition at line 1991 of file PeerImp.h.
References ripple::JobQueue::addJob(), ripple::base_uint< BITS >::begin(), BIND_TYPE, charge(), checkPropose(), ripple::LedgerProposal::computeSuppressionID(), ripple::RippleAddress::createNodePublic(), beast::Journal::debug, ripple::Resource::feeInvalidRequest, ripple::Resource::feeInvalidSignature, ripple::getApp(), ripple::NetworkOPs::getCloseTimeNC(), ripple::getConfig(), ripple::NetworkOPs::getConsensusLCL(), ripple::Application::getJobQueue(), ripple::Application::getOPs(), ripple::Application::getUNL(), ripple::base_uint< BITS >::isNonZero(), ripple::jtPROPOSAL_t, ripple::jtPROPOSAL_ut, m_clusterNode, m_journal, m_nodePublicKey, m_overlay, m_shortId, ripple::UniqueNodeList::nodeInUNL(), P_1, ripple::strCopy(), beast::Journal::trace, and beast::Journal::warning.
Referenced by processReadBuffer().
     {
         assert (packet);
         protocol::TMProposeSet& set = *packet;
         if ((set.closetime() + 180) < getApp().getOPs().getCloseTimeNC())
             return;
         if ((set.currenttxhash ().size () != 32) || (set.nodepubkey ().size () < 28) ||
                 (set.signature ().size () < 56) || (set.nodepubkey ().size () > 128) || (set.signature ().size () > 128))
         {
             m_journal.warning << "Received proposal is malformed";
             charge (Resource::feeInvalidSignature);
             return;
         }
         if (set.has_previousledger () && (set.previousledger ().size () != 32))
         {
             m_journal.warning << "Received proposal is malformed";
             charge (Resource::feeInvalidRequest);
             return;
         }
         uint256 proposeHash, prevLedger;
         memcpy (proposeHash.begin (), set.currenttxhash ().data (), 32);
         if (set.has_previousledger ())
             memcpy (prevLedger.begin (), set.previousledger ().data (), 32);
         uint256 suppression = LedgerProposal::computeSuppressionID (proposeHash, prevLedger,
             set.proposeseq(), set.closetime (),
             Blob(set.nodepubkey ().begin (), set.nodepubkey ().end ()),
             Blob(set.signature ().begin (), set.signature ().end ()));
         if (! getApp().getHashRouter ().addSuppressionPeer (suppression, m_shortId))
         {
             m_journal.trace << "Received duplicate proposal from peer " << m_shortId;
             return;
         }
         RippleAddress signerPublic = RippleAddress::createNodePublic (strCopy (set.nodepubkey ()));
         if (signerPublic == getConfig ().VALIDATION_PUB)
         {
             m_journal.trace << "Received our own proposal from peer " << m_shortId;
             return;
         }
         bool isTrusted = getApp().getUNL ().nodeInUNL (signerPublic);
         if (!isTrusted && getApp().getFeeTrack ().isLoadedLocal ())
         {
              m_journal.debug << "Dropping UNTRUSTED proposal due to load";
             return;
         }
         m_journal.trace << "Received " << (isTrusted ? "trusted" : "UNTRUSTED") <<
                            " proposal from " << m_shortId;
         uint256 consensusLCL;
         {
             Application::ScopedLockType lock (getApp ().getMasterLock ());
             consensusLCL = getApp().getOPs ().getConsensusLCL ();
         }
         LedgerProposal::pointer proposal = boost::make_shared<LedgerProposal> (
             prevLedger.isNonZero () ? prevLedger : consensusLCL,
             set.proposeseq (), proposeHash, set.closetime (), signerPublic, suppression);
         getApp().getJobQueue ().addJob (isTrusted ? jtPROPOSAL_t : jtPROPOSAL_ut,
             "recvPropose->checkPropose", BIND_TYPE (
                 &PeerImp::checkPropose, P_1, &m_overlay, packet, proposal, consensusLCL,
                 m_nodePublicKey, boost::weak_ptr<Peer> (shared_from_this ()), m_clusterNode));
     }
void ripple::PeerImp::recvSearchTransaction (protocol::TMSearchTransaction & packet) inline private
Definition at line 1827 of file PeerImp.h.
Referenced by processReadBuffer().
     {
     }
void ripple::PeerImp::recvStatus (protocol::TMStatusChange & packet) inline private
Definition at line 1927 of file PeerImp.h.
References addLedger(), ripple::base_uint< BITS >::begin(), ripple::getApp(), ripple::base_uint< BITS >::isZero(), m_closedLedgerHash, m_journal, m_maxLedger, m_minLedger, m_previousLedgerHash, mLastStatus, ripple::to_string(), beast::Journal::trace, and ripple::base_uint< BITS >::zero().
Referenced by processReadBuffer().
     {
         m_journal.trace << "Received status change from peer " <<
                            to_string (this);
         if (!packet.has_networktime ())
             packet.set_networktime (getApp().getOPs ().getNetworkTimeNC ());
         if (!mLastStatus.has_newstatus () || packet.has_newstatus ())
             mLastStatus = packet;
         else
         {
             // preserve old status
             protocol::NodeStatus status = mLastStatus.newstatus ();
             mLastStatus = packet;
             packet.set_newstatus (status);
         }
         if (packet.newevent () == protocol::neLOST_SYNC)
         {
             if (!m_closedLedgerHash.isZero ())
             {
                 m_journal.trace << "peer has lost sync " << to_string (this);
                 m_closedLedgerHash.zero ();
             }
             m_previousLedgerHash.zero ();
             return;
         }
         if (packet.has_ledgerhash () && (packet.ledgerhash ().size () == (256 / 8)))
         {
             // a peer has changed ledgers
             memcpy (m_closedLedgerHash.begin (), packet.ledgerhash ().data (), 256 / 8);
             addLedger (m_closedLedgerHash);
             m_journal.trace << "peer LCL is " << m_closedLedgerHash <<
                                " " << to_string (this);
         }
         else
         {
             m_journal.trace << "peer has no ledger hash" << to_string (this);
             m_closedLedgerHash.zero ();
         }
         if (packet.has_ledgerhashprevious () && packet.ledgerhashprevious ().size () == (256 / 8))
         {
             memcpy (m_previousLedgerHash.begin (), packet.ledgerhashprevious ().data (), 256 / 8);
             addLedger (m_previousLedgerHash);
         }
         else m_previousLedgerHash.zero ();
         if (packet.has_firstseq () && packet.has_lastseq())
         {
             m_minLedger = packet.firstseq ();
             m_maxLedger = packet.lastseq ();
             // Work around some servers that report sequences incorrectly
             if (m_minLedger == 0)
                 m_maxLedger = 0;
             if (m_maxLedger == 0)
                 m_minLedger = 0;
         }
     }
void ripple::PeerImp::recvTransaction (protocol::TMTransaction & packet) inline private
Definition at line 1498 of file PeerImp.h.
References ripple::JobQueue::addJob(), BIND_TYPE, charge(), checkTransaction(), beast::Journal::debug, ripple::Resource::feeInvalidSignature, ripple::getApp(), ripple::Application::getJobQueue(), beast::Journal::info, ripple::is_bit_set(), ripple::jtTRANSACTION, m_clusterNode, m_journal, m_shortId, P_1, SF_BAD, SF_RETRY, SF_SIGGOOD, SF_TRUSTED, beast::Journal::trace, and beast::Journal::warning.
Referenced by processReadBuffer().
     {
         Serializer s (packet.rawtransaction ());
     #ifndef TRUST_NETWORK
         try
         {
     #endif
             SerializerIterator sit (s);
             SerializedTransaction::pointer stx = boost::make_shared<SerializedTransaction> (boost::ref (sit));
             uint256 txID = stx->getTransactionID();
             int flags;
             if (! getApp().getHashRouter ().addSuppressionPeer (txID, m_shortId, flags))
             {
                 // we have seen this transaction recently
                 if (is_bit_set (flags, SF_BAD))
                 {
                     charge (Resource::feeInvalidSignature);
                     return;
                 }
                 if (!is_bit_set (flags, SF_RETRY))
                     return;
             }
              m_journal.debug << "Got transaction from peer " << *this << ": " << txID;
             if (m_clusterNode)
                 flags |= SF_TRUSTED | SF_SIGGOOD;
             if (getApp().getJobQueue().getJobCount(jtTRANSACTION) > 100)
                 m_journal.info << "Transaction queue is full";
             else if (getApp().getLedgerMaster().getValidatedLedgerAge() > 240)
                 m_journal.trace << "No new transactions until synchronized";
             else
                 getApp().getJobQueue ().addJob (jtTRANSACTION,
                     "recvTransaction->checkTransaction",
                     BIND_TYPE (
                         &PeerImp::checkTransaction, P_1, flags, stx,
                         boost::weak_ptr<Peer> (shared_from_this ())));
     #ifndef TRUST_NETWORK
         }
         catch (...)
         {
             m_journal.warning << "Transaction invalid: " <<
                s.getHex();
         }
     #endif
     }
void ripple::PeerImp::recvValidation (const boost::shared_ptr< protocol::TMValidation > & packet) inline private
Definition at line 1552 of file PeerImp.h.
References ripple::JobQueue::addJob(), BIND_TYPE, charge(), checkValidation(), beast::Journal::debug, ripple::Resource::feeInvalidRequest, ripple::Resource::feeUnwantedData, ripple::getApp(), ripple::NetworkOPs::getCloseTimeNC(), ripple::Application::getFeeTrack(), ripple::Application::getJobQueue(), ripple::Application::getOPs(), ripple::Application::getUNL(), ripple::LoadFeeTrack::isLoadedLocal(), ripple::jtVALIDATION_t, ripple::jtVALIDATION_ut, m_clusterNode, m_journal, m_overlay, m_shortId, ripple::UniqueNodeList::nodeInUNL(), P_1, beast::Journal::trace, and beast::Journal::warning.
Referenced by checkValidation(), and processReadBuffer().
     {
         std::uint32_t closeTime = getApp().getOPs().getCloseTimeNC();
         if (packet->validation ().size () < 50)
         {
             m_journal.warning << "Too small validation from peer";
             charge (Resource::feeInvalidRequest);
             return;
         }
     #ifndef TRUST_NETWORK
         try
     #endif
         {
             Serializer s (packet->validation ());
             SerializerIterator sit (s);
             SerializedValidation::pointer val = boost::make_shared<SerializedValidation> (boost::ref (sit), false);
             if (closeTime > (120 + val->getFieldU32(sfSigningTime)))
             {
                 m_journal.trace << "Validation is more than two minutes old";
                 charge (Resource::feeUnwantedData);
                 return;
             }
             if (! getApp().getHashRouter ().addSuppressionPeer (s.getSHA512Half(), m_shortId))
             {
                 m_journal.trace << "Validation is duplicate";
                 return;
             }
             bool isTrusted = getApp().getUNL ().nodeInUNL (val->getSignerPublic ());
             if (isTrusted || !getApp().getFeeTrack ().isLoadedLocal ())
             {
                 getApp().getJobQueue ().addJob (
                     isTrusted ? jtVALIDATION_t : jtVALIDATION_ut,
                     "recvValidation->checkValidation",
                     BIND_TYPE (
                         &PeerImp::checkValidation, P_1, &m_overlay, val,
                         isTrusted, m_clusterNode, packet,
                         boost::weak_ptr<Peer> (shared_from_this ())));
             }
             else
                 m_journal.debug << "Dropping UNTRUSTED validation due to load";
         }
     #ifndef TRUST_NETWORK
         catch (...)
         {
              m_journal.warning << "Exception processing validation";
             charge (Resource::feeInvalidRequest);
         }
     #endif
     }
void ripple::PeerImp::sendGetPeers () inline
Definition at line 477 of file PeerImp.h.
References sendPacket().
Referenced by recvHello().
     {
         // Ask peer for known other peers.
         protocol::TMGetPeers msg;
         msg.set_doweneedthis (1);
         Message::pointer packet = boost::make_shared<Message> (
             msg, protocol::mtGET_PEERS);
         sendPacket (packet, true);
     }
bool ripple::PeerImp::sendHello () inline private
Perform a secure handshake with the peer at the other end.
If this function returns false then we cannot guarantee that there is no active man-in-the-middle attack taking place and the link MUST be disconnected.
Returns
true if successful, false otherwise.
Definition at line 1300 of file PeerImp.h.
References ripple::base_uint< BITS >::begin(), calculateSessionCookie(), ripple::getApp(), ripple::LedgerMaster::getClosedLedger(), ripple::getConfig(), ripple::BuildInfo::getCurrentProtocol(), ripple::BuildInfo::getFullVersionString(), ripple::Application::getLedgerMaster(), ripple::Application::getLocalCredentials(), ripple::BuildInfo::getMinimumProtocol(), ripple::LocalCredentials::getNodePrivate(), getNodePublic(), ripple::base_uint< BITS >::GetSerializeSize(), m_secureCookie, sendPacket(), and ripple::RippleAddress::signNodePrivate().
Referenced by handleStart().
     {
         if (!calculateSessionCookie())
             return false;
         Blob vchSig;
         getApp().getLocalCredentials ().getNodePrivate ().signNodePrivate (m_secureCookie, vchSig);
         protocol::TMHello h;
         h.set_protoversion (BuildInfo::getCurrentProtocol().toPacked ());
         h.set_protoversionmin (BuildInfo::getMinimumProtocol().toPacked ());
         h.set_fullversion (BuildInfo::getFullVersionString ());
         h.set_nettime (getApp().getOPs ().getNetworkTimeNC ());
         h.set_nodepublic (getApp().getLocalCredentials ().getNodePublic ().humanNodePublic ());
         h.set_nodeproof (&vchSig[0], vchSig.size ());
         h.set_ipv4port (getConfig ().peerListeningPort);
         h.set_testnet (false);
         // We always advertise ourselves as private in the HELLO message. This
         // suppresses the old peer advertising code and allows PeerFinder to
         // take over the functionality.
         h.set_nodeprivate (true);
         Ledger::pointer closedLedger = getApp().getLedgerMaster ().getClosedLedger ();
         if (closedLedger && closedLedger->isClosed ())
         {
             uint256 hash = closedLedger->getHash ();
             h.set_ledgerclosed (hash.begin (), hash.GetSerializeSize ());
             hash = closedLedger->getParentHash ();
             h.set_ledgerprevious (hash.begin (), hash.GetSerializeSize ());
         }
         Message::pointer packet = boost::make_shared<Message> (
             h, protocol::mtHELLO);
         sendPacket (packet, true);
         return true;
     }
void ripple::PeerImp::sendPacket (const Message::pointer & packet, bool onStrand) inline virtual
Implements ripple::Peer.
Definition at line 455 of file PeerImp.h.
References BIND_TYPE, m_strand, mSendingPacket, mSendQ, ripple::Peer::sendPacket(), and sendPacketForce().
Referenced by getLedger(), recvGetObjectByHash(), recvGetPeers(), recvPing(), sendGetPeers(), and sendHello().
     {
         if (packet)
         {
             if (!onStrand)
             {
                 m_strand.post (BIND_TYPE (
                     &Peer::sendPacket, shared_from_this (), packet, true));
                 return;
             }
             if (mSendingPacket)
             {
                 mSendQ.push_back (packet);
             }
             else
             {
                 sendPacketForce (packet);
             }
         }
     }
void ripple::PeerImp::sendPacketForce (const Message::pointer & packet) inline private
Definition at line 1185 of file PeerImp.h.
References getStream(), handleWrite(), m_detaching, m_strand, and mSendingPacket.
Referenced by handleWrite(), and sendPacket().
     {
         // must be on IO strand
         if (!m_detaching)
         {
             mSendingPacket = packet;
             boost::asio::async_write (getStream (),
                 boost::asio::buffer (packet->getBuffer ()),
                 m_strand.wrap (boost::bind (
                     &PeerImp::handleWrite,
                     boost::static_pointer_cast <PeerImp> (shared_from_this ()),
                     boost::asio::placeholders::error,
                     boost::asio::placeholders::bytes_transferred)));
         }
     }
static void ripple::PeerImp::sGetLedger (boost::weak_ptr< PeerImp > wPeer, boost::shared_ptr< protocol::TMGetLedger > packet) inline static private
Definition at line 2514 of file PeerImp.h.
Referenced by recvGetLedger().
     {
         boost::shared_ptr<PeerImp> peer = wPeer.lock ();
         if (peer)
             peer->getLedger (*packet);
     }
void ripple::PeerImp::start () inline
Definition at line 439 of file PeerImp.h.
References accept(), connect(), and m_inbound.
     {
         if (m_inbound)
             accept ();
         else
             connect ();
     }
void ripple::PeerImp::startReadBody (unsigned msg_len) inline private
Definition at line 1164 of file PeerImp.h.
References getStream(), handleReadBody(), ripple::Message::kHeaderBytes, m_detaching, m_readBuffer, and m_strand.
Referenced by handleReadHeader().
     {
         // The first Message::kHeaderBytes bytes of m_readbuf already
         // contains the header. Expand it to fit in the body as well, and
         // start async read into the body.
         if (!m_detaching)
         {
             m_readBuffer.resize (Message::kHeaderBytes + msg_len);
             boost::asio::async_read (getStream (),
                 boost::asio::buffer (
                     &m_readBuffer [Message::kHeaderBytes], msg_len),
                 m_strand.wrap (boost::bind (
                     &PeerImp::handleReadBody,
                     boost::static_pointer_cast <PeerImp> (shared_from_this ()),
                     boost::asio::placeholders::error,
                     boost::asio::placeholders::bytes_transferred)));
         }
     }
void ripple::PeerImp::startReadHeader () inline private
Definition at line 1148 of file PeerImp.h.
References getStream(), handleReadHeader(), ripple::Message::kHeaderBytes, m_detaching, m_readBuffer, and m_strand.
Referenced by handleReadBody(), and handleStart().
     {
         if (!m_detaching)
         {
             m_readBuffer.clear ();
             m_readBuffer.resize (Message::kHeaderBytes);
             boost::asio::async_read (getStream (),
                 boost::asio::buffer (m_readBuffer),
                 m_strand.wrap (boost::bind (&PeerImp::handleReadHeader,
                     boost::static_pointer_cast <PeerImp> (shared_from_this ()),
                     boost::asio::placeholders::error,
                     boost::asio::placeholders::bytes_transferred)));
         }
     }
State ripple::PeerImp::state () const inline
Definition at line 298 of file PeerImp.h.
References m_state.
     {
         return m_state;
     }
void ripple::PeerImp::state (State new_state) inline
Definition at line 303 of file PeerImp.h.
References m_state.
     {
         m_state = new_state;
     }
bool ripple::PeerImp::supportsVersion (int version) inline virtual
Implements ripple::Peer.
Definition at line 635 of file PeerImp.h.
References mHello, and version.
     {
         return mHello.has_protoversion () && (mHello.protoversion () >= version);
     }
Member Data Documentation
const std::uint32_t ripple::PeerImp::clockToleranceDeltaSeconds = 20 static private
The clock drift we allow a remote peer to have
Definition at line 68 of file PeerImp.h.
Referenced by recvHello().
uint256 ripple::PeerImp::m_closedLedgerHash
Definition at line 187 of file PeerImp.h.
Referenced by cycleStatus(), getClosedLedgerHash(), json(), recvHello(), and recvStatus().
bool ripple::PeerImp::m_clusterNode
Definition at line 173 of file PeerImp.h.
Referenced by detach(), getLedger(), isInCluster(), json(), recvCluster(), recvHello(), recvPropose(), recvTransaction(), and recvValidation().
bool ripple::PeerImp::m_detaching
Definition at line 172 of file PeerImp.h.
Referenced by detach(), handleReadBody(), handleReadHeader(), handleShutdown(), handleStart(), handleVerifyTimer(), handleWrite(), onConnect(), sendPacketForce(), startReadBody(), and startReadHeader().
bool ripple::PeerImp::m_inbound
Definition at line 166 of file PeerImp.h.
Referenced by handleStart(), json(), and start().
beast::Journal ripple::PeerImp::m_journal
Definition at line 149 of file PeerImp.h.
Referenced by accept(), calculateSessionCookie(), connect(), detach(), doFetchPack(), doProofOfWork(), getLedger(), handleReadBody(), handleReadHeader(), handleShutdown(), handleStart(), handleVerifyTimer(), handleWrite(), json(), onConnect(), processReadBuffer(), recvGetObjectByHash(), recvHello(), recvLedger(), recvPropose(), recvStatus(), recvTransaction(), and recvValidation().
LedgerIndex ripple::PeerImp::m_maxLedger
Definition at line 185 of file PeerImp.h.
Referenced by hasLedger(), hasRange(), ledgerRange(), and recvStatus().
LedgerIndex ripple::PeerImp::m_minLedger
Definition at line 184 of file PeerImp.h.
Referenced by hasLedger(), hasRange(), ledgerRange(), and recvStatus().
std::string ripple::PeerImp::m_nodeName
Definition at line 175 of file PeerImp.h.
Referenced by detach(), getClusterNodeName(), json(), recvCluster(), and recvHello().
RippleAddress ripple::PeerImp::m_nodePublicKey
Definition at line 174 of file PeerImp.h.
Referenced by detach(), getNodePublic(), json(), recvHello(), and recvPropose().
OverlayImpl& ripple::PeerImp::m_overlay
Definition at line 165 of file PeerImp.h.
Referenced by activate(), detach(), getLedger(), recvLedger(), recvPropose(), recvValidation(), and ~PeerImp().
NativeSocketType ripple::PeerImp::m_owned_socket
Definition at line 147 of file PeerImp.h.
PeerFinder::Manager& ripple::PeerImp::m_peerFinder
Definition at line 164 of file PeerImp.h.
Referenced by detach(), onConnect(), recvEndpoints(), recvHello(), and recvPeers().
uint256 ripple::PeerImp::m_previousLedgerHash
Definition at line 188 of file PeerImp.h.
Referenced by cycleStatus(), recvHello(), and recvStatus().
std::vector<uint8_t> ripple::PeerImp::m_readBuffer
Definition at line 196 of file PeerImp.h.
Referenced by handleReadHeader(), processReadBuffer(), startReadBody(), and startReadHeader().
std::list<uint256> ripple::PeerImp::m_recentLedgers
Definition at line 190 of file PeerImp.h.
Referenced by addLedger(), and hasLedger().
boost::mutex ripple::PeerImp::m_recentLock mutable
Definition at line 192 of file PeerImp.h.
Referenced by addLedger(), addTxSet(), hasLedger(), hasTxSet(), and ledgerRange().
std::list<uint256> ripple::PeerImp::m_recentTxSets
Definition at line 191 of file PeerImp.h.
Referenced by addTxSet(), and hasTxSet().
beast::IP::Endpoint ripple::PeerImp::m_remoteAddress
Definition at line 159 of file PeerImp.h.
Referenced by accept(), connect(), getRemoteAddress(), handleStart(), json(), onConnect(), and recvEndpoints().
Resource::Manager& ripple::PeerImp::m_resourceManager
Definition at line 163 of file PeerImp.h.
Referenced by handleStart(), and recvCluster().
uint256 ripple::PeerImp::m_secureCookie
Definition at line 180 of file PeerImp.h.
Referenced by calculateSessionCookie(), recvHello(), and sendHello().
ShortId ripple::PeerImp::m_shortId
Definition at line 154 of file PeerImp.h.
Referenced by activate(), getShortId(), recvPropose(), recvTransaction(), and recvValidation().
PeerFinder::Slot::ptr ripple::PeerImp::m_slot
Definition at line 205 of file PeerImp.h.
Referenced by detach(), onConnect(), recvEndpoints(), recvHello(), and ~PeerImp().
std::unique_ptr<MultiSocket> ripple::PeerImp::m_socket
Definition at line 168 of file PeerImp.h.
Referenced by accept(), calculateSessionCookie(), connect(), detach(), getStream(), and onConnect().
State ripple::PeerImp::m_state
Definition at line 171 of file PeerImp.h.
Referenced by activate(), detach(), onConnect(), processReadBuffer(), recvHello(), and state().
boost::asio::io_service::strand ripple::PeerImp::m_strand
Definition at line 169 of file PeerImp.h.
Referenced by accept(), connect(), detach(), onConnect(), sendPacket(), sendPacketForce(), startReadBody(), and startReadHeader().
boost::asio::deadline_timer ripple::PeerImp::m_timer
Definition at line 194 of file PeerImp.h.
Referenced by connect(), detach(), and recvHello().
Resource::Consumer ripple::PeerImp::m_usage
Definition at line 202 of file PeerImp.h.
Referenced by charge(), and handleStart().
bool ripple::PeerImp::m_was_canceled
Definition at line 208 of file PeerImp.h.
Referenced by close(), and detach().
protocol::TMHello ripple::PeerImp::mHello
Definition at line 200 of file PeerImp.h.
Referenced by json(), recvHello(), and supportsVersion().
protocol::TMStatusChange ripple::PeerImp::mLastStatus
Definition at line 199 of file PeerImp.h.
Referenced by json(), and recvStatus().
Message::pointer ripple::PeerImp::mSendingPacket
Definition at line 198 of file PeerImp.h.
Referenced by handleWrite(), sendPacket(), and sendPacketForce().
std::list<Message::pointer> ripple::PeerImp::mSendQ
Definition at line 197 of file PeerImp.h.
Referenced by detach(), handleWrite(), and sendPacket().
const boost::posix_time::seconds ripple::PeerImp::nodeVerifySeconds static private
Time alloted for a peer to send a HELLO message (DEPRECATED)
Definition at line 65 of file PeerImp.h.
Referenced by connect().
const size_t ripple::PeerImp::sslMinimumFinishedLength = 12 static private
The length of the smallest valid finished message
Definition at line 71 of file PeerImp.h.
Referenced by hashLatestFinishedMessage().
The documentation for this class was generated from the following file:
rippled/src/ripple_overlay/impl/PeerImp.h