rippled: rocksdb::DBTest Class Reference
rocksdb::DBTest Class Reference
Public Types
enum OptionSkip { kNoSkip = 0, kSkipDeletesFilterFirst = 1, kSkipUniversalCompaction = 2, kSkipMergePut = 4 }
Public Member Functions
DBTest ()
~DBTest ()
bool ChangeOptions (int skip_mask=kNoSkip)
bool ChangeCompactOptions (Options *prev_options=nullptr)
Options CurrentOptions ()
DBImpl * dbfull ()
void Reopen (Options *options=nullptr)
void Close ()
void DestroyAndReopen (Options *options=nullptr)
void Destroy (Options *options)
Status PureReopen (Options *options, DB **db)
Status TryReopen (Options *options=nullptr)
Status Put (const Slice &k, const Slice &v, WriteOptions wo=WriteOptions())
Status Delete (const std::string &k)
std::string Get (const std::string &k, const Snapshot *snapshot=nullptr)
std::string Contents ()
std::string AllEntriesFor (const Slice &user_key)
int NumTableFilesAtLevel (int level)
int TotalTableFiles ()
std::string FilesPerLevel ()
int CountFiles ()
int CountLiveFiles ()
uint64_t Size (const Slice &start, const Slice &limit)
void Compact (const Slice &start, const Slice &limit)
void MakeTables (int n, const std::string &small, const std::string &large)
void FillLevels (const std::string &smallest, const std::string &largest)
void DumpFileCounts (const char *label)
std::string DumpSSTableList ()
std::string IterStatus (Iterator *iter)
Options OptionsForLogIterTest ()
std::unique_ptr
< TransactionLogIterator > OpenTransactionLogIter (const SequenceNumber seq)
std::string DummyString (size_t len, char c= 'a')
void VerifyIterLast (std::string expected_key)
Public Attributes
std::string dbname_
SpecialEnv * env_
DB * db_
Options last_options_
Protected Types
enum OptionConfig {
kDefault, kVectorRep, kUnsortedRep, kMergePut,
kFilter, kUncompressed, kNumLevel_3, kDBLogDir,
kWalDir, kManifestFileSize, kCompactOnFlush, kPerfOptions,
kDeletesFilterFirst, kPrefixHashRep, kUniversalCompaction, kCompressedBlockCache,
kEnd
}
Protected Attributes
int option_config_
Private Attributes
const FilterPolicy * filter_policy_
Detailed Description
Definition at line 238 of file db_test.cc.
Member Enumeration Documentation
enum rocksdb::DBTest::OptionConfig protected
Enumerator
kDefault
kVectorRep
kUnsortedRep
kMergePut
kFilter
kUncompressed
kNumLevel_3
kDBLogDir
kWalDir
kManifestFileSize
kCompactOnFlush
kPerfOptions
kDeletesFilterFirst
kPrefixHashRep
kUniversalCompaction
kCompressedBlockCache
kEnd
Definition at line 244 of file db_test.cc.
                     {
     kDefault,
     kVectorRep,
     kUnsortedRep,
     kMergePut,
     kFilter,
     kUncompressed,
     kNumLevel_3,
     kDBLogDir,
     kWalDir,
     kManifestFileSize,
     kCompactOnFlush,
     kPerfOptions,
     kDeletesFilterFirst,
     kPrefixHashRep,
     kUniversalCompaction,
     kCompressedBlockCache,
     kEnd
   };
enum rocksdb::DBTest::OptionSkip
Enumerator
kNoSkip
kSkipDeletesFilterFirst
kSkipUniversalCompaction
kSkipMergePut
Definition at line 274 of file db_test.cc.
                   {
     kNoSkip = 0,
     kSkipDeletesFilterFirst = 1,
     kSkipUniversalCompaction = 2,
     kSkipMergePut = 4
   };
Constructor & Destructor Documentation
rocksdb::DBTest::DBTest () inline
Definition at line 281 of file db_test.cc.
References ASSERT_OK, db_, dbname_, rocksdb::DestroyDB(), filter_policy_, rocksdb::NewBloomFilterPolicy(), Reopen(), and rocksdb::test::TmpDir().
            : option_config_(kDefault),
              env_(new SpecialEnv(Env::Default())) {
     filter_policy_ = NewBloomFilterPolicy(10);
     dbname_ = test::TmpDir() + "/db_test";
     ASSERT_OK(DestroyDB(dbname_, Options()));
     db_ = nullptr;
     Reopen();
   }
rocksdb::DBTest::~DBTest () inline
Definition at line 290 of file db_test.cc.
References ASSERT_OK, db_, dbname_, rocksdb::DestroyDB(), env_, and filter_policy_.
             {
     delete db_;
     ASSERT_OK(DestroyDB(dbname_, Options()));
     delete env_;
     delete filter_policy_;
   }
Member Function Documentation
std::string rocksdb::DBTest::AllEntriesFor (const Slice & user_key) inline
Definition at line 493 of file db_test.cc.
References rocksdb::Options::comparator, rocksdb::Comparator::Compare(), dbfull(), rocksdb::InternalKey::Encode(), beast.util.Iter::first(), rocksdb::Iterator::key(), rocksdb::kMaxSequenceNumber, rocksdb::kTypeDeletion, rocksdb::kTypeLogData, rocksdb::kTypeMerge, rocksdb::kTypeValue, last_options_, rocksdb::Iterator::Next(), rocksdb::Status::ok(), rocksdb::ParseInternalKey(), rocksdb::Iterator::Seek(), rocksdb::Iterator::status(), rocksdb::DBImpl::TEST_NewInternalIterator(), rocksdb::Slice::ToString(), rocksdb::Status::ToString(), rocksdb::ParsedInternalKey::type, rocksdb::ParsedInternalKey::user_key, rocksdb::Iterator::Valid(), and rocksdb::Iterator::value().
{
     Iterator* iter = dbfull()->TEST_NewInternalIterator();
     InternalKey target(user_key, kMaxSequenceNumber, kTypeValue);
     iter->Seek(target.Encode());
     std::string result;
     if (!iter->status().ok()) {
       result = iter->status().ToString();
     } else {
       result = "[ ";
       bool first = true;
       while (iter->Valid()) {
         ParsedInternalKey ikey(Slice(), 0, kTypeValue);
         if (!ParseInternalKey(iter->key(), &ikey)) {
           result += "CORRUPTED";
         } else {
           if (last_options_.comparator->Compare(ikey.user_key, user_key) != 0) {
             break;
           }
           if (!first) {
             result += ", ";
           }
           first = false;
           switch (ikey.type) {
             case kTypeValue:
               result += iter->value().ToString();
               break;
             case kTypeMerge:
               // keep it the same as kTypeValue for testing kMergePut
               result += iter->value().ToString();
               break;
             case kTypeDeletion:
               result += "DEL";
               break;
             case kTypeLogData:
               assert(false);
               break;
           }
         }
         iter->Next();
       }
       if (!first) {
         result += " ";
       }
       result += "]";
     }
     delete iter;
     return result;
   }
bool rocksdb::DBTest::ChangeCompactOptions (Options * prev_options = nullptr) inline
Definition at line 324 of file db_test.cc.
References Destroy(), kDefault, kUniversalCompaction, last_options_, option_config_, and TryReopen().
{
     if (option_config_ == kDefault) {
       option_config_ = kUniversalCompaction;
       if (prev_options == nullptr) {
         prev_options = &last_options_;
       }
       Destroy(prev_options);
       TryReopen();
       return true;
     } else {
       return false;
     }
   }
bool rocksdb::DBTest::ChangeOptions (int skip_mask = kNoSkip) inline
Definition at line 299 of file db_test.cc.
References Destroy(), DestroyAndReopen(), kDeletesFilterFirst, kEnd, kMergePut, kSkipDeletesFilterFirst, kSkipMergePut, kSkipUniversalCompaction, kUniversalCompaction, last_options_, and option_config_.
{
     option_config_++;
     // skip some options
     if (skip_mask & kSkipDeletesFilterFirst &&
         option_config_ == kDeletesFilterFirst) {
       option_config_++;
     }
     if (skip_mask & kSkipUniversalCompaction &&
         option_config_ == kUniversalCompaction) {
       option_config_++;
     }
     if (skip_mask & kSkipMergePut && option_config_ == kMergePut) {
       option_config_++;
     }
     if (option_config_ >= kEnd) {
       Destroy(&last_options_);
       return false;
     } else {
       DestroyAndReopen();
       return true;
     }
   }
void rocksdb::DBTest::Close () inline
Definition at line 404 of file db_test.cc.
References db_.
                {
     delete db_;
     db_ = nullptr;
   }
void rocksdb::DBTest::Compact (const Slice & start, const Slice & limit) inline
Definition at line 601 of file db_test.cc.
References rocksdb::DB::CompactRange(), and db_.
{
     db_->CompactRange(&start, &limit);
   }
std::string rocksdb::DBTest::Contents () inline
Definition at line 468 of file db_test.cc.
References ASSERT_EQ, ASSERT_LT, db_, IterStatus(), rocksdb::DB::NewIterator(), rocksdb::Iterator::Next(), rocksdb::Iterator::Prev(), rocksdb::Iterator::SeekToFirst(), rocksdb::Iterator::SeekToLast(), and rocksdb::Iterator::Valid().
{
     std::vector<std::string> forward;
     std::string result;
     Iterator* iter = db_->NewIterator(ReadOptions());
     for (iter->SeekToFirst(); iter->Valid(); iter->Next()) {
       std::string s = IterStatus(iter);
       result.push_back('(');
       result.append(s);
       result.push_back(')');
       forward.push_back(s);
     }
     // Check reverse iteration results are the reverse of forward results
     unsigned int matched = 0;
     for (iter->SeekToLast(); iter->Valid(); iter->Prev()) {
       ASSERT_LT(matched, forward.size());
       ASSERT_EQ(IterStatus(iter), forward[forward.size() - matched - 1]);
       matched++;
     }
     ASSERT_EQ(matched, forward.size());
     delete iter;
     return result;
   }
int rocksdb::DBTest::CountFiles () inline
Definition at line 575 of file db_test.cc.
References dbname_, env_, rocksdb::EnvWrapper::GetChildren(), last_options_, and rocksdb::Options::wal_dir.
                    {
     std::vector<std::string> files;
     env_->GetChildren(dbname_, &files);
     std::vector<std::string> logfiles;
     if (dbname_ != last_options_.wal_dir) {
       env_->GetChildren(last_options_.wal_dir, &logfiles);
     }
     return static_cast<int>(files.size() + logfiles.size());
   }
int rocksdb::DBTest::CountLiveFiles () inline
Definition at line 587 of file db_test.cc.
References db_, and rocksdb::DB::GetLiveFiles().
{
     std::vector<std::string> files;
     uint64_t manifest_file_size;
     db_->GetLiveFiles(files, &manifest_file_size);
     return files.size();
   }
Options rocksdb::DBTest::CurrentOptions () inline
Definition at line 339 of file db_test.cc.
References rocksdb::Options::block_cache_compressed, rocksdb::Options::compaction_style, rocksdb::Options::compression, rocksdb::MergeOperators::CreatePutOperator(), rocksdb::Options::db_log_dir, rocksdb::Options::filter_deletes, rocksdb::Options::filter_policy, filter_policy_, rocksdb::Options::hard_rate_limit, rocksdb::kCompactionStyleUniversal, kCompactOnFlush, kCompressedBlockCache, kDBLogDir, kDeletesFilterFirst, kFilter, kManifestFileSize, kMergePut, rocksdb::kNoCompression, kNumLevel_3, kPerfOptions, kPrefixHashRep, kUncompressed, kUniversalCompaction, kUnsortedRep, kVectorRep, kWalDir, rocksdb::Options::max_manifest_file_size, rocksdb::Options::memtable_factory, rocksdb::Options::merge_operator, rocksdb::NewFixedPrefixTransform(), rocksdb::NewLRUCache(), rocksdb::Options::num_levels, option_config_, rocksdb::Options::purge_redundant_kvs_while_flush, rocksdb::Options::rate_limit_delay_max_milliseconds, rocksdb::test::TmpDir(), and rocksdb::Options::wal_dir.
Referenced by OptionsForLogIterTest(), and TryReopen().
{
     Options options;
     switch (option_config_) {
       case kPrefixHashRep:
         options.memtable_factory.reset(new
           PrefixHashRepFactory(NewFixedPrefixTransform(1)));
         break;
       case kMergePut:
         options.merge_operator = MergeOperators::CreatePutOperator();
         break;
       case kFilter:
         options.filter_policy = filter_policy_;
         break;
       case kUncompressed:
         options.compression = kNoCompression;
         break;
       case kNumLevel_3:
         options.num_levels = 3;
         break;
       case kDBLogDir:
         options.db_log_dir = test::TmpDir();
         break;
       case kWalDir:
         options.wal_dir = "/tmp/wal";
         break;
       case kManifestFileSize:
         options.max_manifest_file_size = 50; // 50 bytes
       case kCompactOnFlush:
         options.purge_redundant_kvs_while_flush =
           !options.purge_redundant_kvs_while_flush;
         break;
       case kPerfOptions:
         options.hard_rate_limit = 2.0;
         options.rate_limit_delay_max_milliseconds = 2;
         // TODO -- test more options
         break;
       case kDeletesFilterFirst:
         options.filter_deletes = true;
         break;
       case kUnsortedRep:
         options.memtable_factory.reset(new UnsortedRepFactory);
         break;
       case kVectorRep:
         options.memtable_factory.reset(new VectorRepFactory(100));
         break;
       case kUniversalCompaction:
         options.compaction_style = kCompactionStyleUniversal;
         break;
       case kCompressedBlockCache:
         options.block_cache_compressed = NewLRUCache(8*1024*1024);
         break;
       default:
         break;
     }
     return options;
   }
DBImpl* rocksdb::DBTest::dbfull () inline
Definition at line 396 of file db_test.cc.
References db_.
Referenced by AllEntriesFor(), DumpFileCounts(), MakeTables(), OpenTransactionLogIter(), and rocksdb::PrefixScanInit().
                    {
     return reinterpret_cast<DBImpl*>(db_);
   }
Status rocksdb::DBTest::Delete (const std::string & k) inline
Definition at line 448 of file db_test.cc.
References db_, and rocksdb::DB::Delete().
{
     return db_->Delete(WriteOptions(), k);
   }
void rocksdb::DBTest::Destroy (Options * options) inline
Definition at line 415 of file db_test.cc.
References ASSERT_OK, db_, dbname_, and rocksdb::DestroyDB().
Referenced by ChangeCompactOptions(), ChangeOptions(), and DestroyAndReopen().
{
     delete db_;
     db_ = nullptr;
     ASSERT_OK(DestroyDB(dbname_, *options));
   }
void rocksdb::DBTest::DestroyAndReopen (Options * options = nullptr) inline
Definition at line 409 of file db_test.cc.
References ASSERT_OK, Destroy(), last_options_, and TryReopen().
Referenced by ChangeOptions().
{
     //Destroy using last options
     Destroy(&last_options_);
     ASSERT_OK(TryReopen(options));
   }
std::string rocksdb::DBTest::DummyString (size_t len, char c = 'a') inline
Definition at line 666 of file db_test.cc.
{
     return std::string(len, c);
   }
void rocksdb::DBTest::DumpFileCounts (const char * label) inline
Definition at line 621 of file db_test.cc.
References db_, dbfull(), rocksdb::DB::NumberLevels(), and NumTableFilesAtLevel().
{
     fprintf(stderr, "---\n%s:\n", label);
     fprintf(stderr, "maxoverlap: %lld\n",
             static_cast<long long>(
                 dbfull()->TEST_MaxNextLevelOverlappingBytes()));
     for (int level = 0; level < db_->NumberLevels(); level++) {
       int num = NumTableFilesAtLevel(level);
       if (num > 0) {
         fprintf(stderr, "  level %3d : %d files\n", level, num);
       }
     }
   }
std::string rocksdb::DBTest::DumpSSTableList () inline
Definition at line 634 of file db_test.cc.
References db_, and rocksdb::DB::GetProperty().
{
     std::string property;
     db_->GetProperty("rocksdb.sstables", &property);
     return property;
   }
std::string rocksdb::DBTest::FilesPerLevel () inline
Definition at line 559 of file db_test.cc.
References db_, ripple::f, rocksdb::DB::NumberLevels(), and NumTableFilesAtLevel().
{
     std::string result;
     int last_non_zero_offset = 0;
     for (int level = 0; level < db_->NumberLevels(); level++) {
       int f = NumTableFilesAtLevel(level);
       char buf[100];
       snprintf(buf, sizeof(buf), "%s%d", (level ? "," : ""), f);
       result += buf;
       if (f > 0) {
         last_non_zero_offset = result.size();
       }
     }
     result.resize(last_non_zero_offset);
     return result;
   }
void rocksdb::DBTest::FillLevels (const std::string & smallest, const std::string & largest) inline
Definition at line 617 of file db_test.cc.
References db_, MakeTables(), and rocksdb::DB::NumberLevels().
{
     MakeTables(db_->NumberLevels(), smallest, largest);
   }
std::string rocksdb::DBTest::Get (const std::string & k, const Snapshot * snapshot = nullptr) inline
Definition at line 452 of file db_test.cc.
References db_, rocksdb::DB::Get(), rocksdb::Status::IsNotFound(), rocksdb::Status::ok(), rocksdb::ReadOptions::snapshot, rocksdb::Status::ToString(), and rocksdb::ReadOptions::verify_checksums.
{
     ReadOptions options;
     options.verify_checksums = true;
     options.snapshot = snapshot;
     std::string result;
     Status s = db_->Get(options, k, &result);
     if (s.IsNotFound()) {
       result = "NOT_FOUND";
     } else if (!s.ok()) {
       result = s.ToString();
     }
     return result;
   }
std::string rocksdb::DBTest::IterStatus (Iterator * iter) inline
Definition at line 640 of file db_test.cc.
References rocksdb::Iterator::key(), rocksdb::Slice::ToString(), rocksdb::Iterator::Valid(), and rocksdb::Iterator::value().
Referenced by Contents(), and VerifyIterLast().
{
     std::string result;
     if (iter->Valid()) {
       result = iter->key().ToString() + "->" + iter->value().ToString();
     } else {
       result = "(invalid)";
     }
     return result;
   }
void rocksdb::DBTest::MakeTables (int n, const std::string & small, const std::string & large) inline
Definition at line 607 of file db_test.cc.
References dbfull(), Put(), and rocksdb::DBImpl::TEST_FlushMemTable().
Referenced by FillLevels().
{
     for (int i = 0; i < n; i++) {
       Put(small, "begin");
       Put(large, "end");
       dbfull()->TEST_FlushMemTable();
     }
   }
int rocksdb::DBTest::NumTableFilesAtLevel (int level) inline
Definition at line 542 of file db_test.cc.
References ASSERT_TRUE, db_, rocksdb::DB::GetProperty(), and rocksdb::NumberToString().
Referenced by DumpFileCounts(), FilesPerLevel(), and TotalTableFiles().
{
     std::string property;
     ASSERT_TRUE(
         db_->GetProperty("rocksdb.num-files-at-level" + NumberToString(level),
                          &property));
     return atoi(property.c_str());
   }
std::unique_ptr<TransactionLogIterator> rocksdb::DBTest::OpenTransactionLogIter (const SequenceNumber seq) inline
Definition at line 657 of file db_test.cc.
References ASSERT_OK, ASSERT_TRUE, dbfull(), and rocksdb::DBImpl::GetUpdatesSince().
{
     unique_ptr<TransactionLogIterator> iter;
     Status status = dbfull()->GetUpdatesSince(seq, &iter);
     ASSERT_OK(status);
     ASSERT_TRUE(iter->Valid());
     return std::move(iter);
   }
Options rocksdb::DBTest::OptionsForLogIterTest () inline
Definition at line 650 of file db_test.cc.
References rocksdb::Options::create_if_missing, CurrentOptions(), and rocksdb::Options::WAL_ttl_seconds.
{
     Options options = CurrentOptions();
     options.create_if_missing = true;
     options.WAL_ttl_seconds = 1000;
     return options;
   }
Status rocksdb::DBTest::PureReopen (Options * options, DB ** db) inline
Definition at line 421 of file db_test.cc.
References dbname_, and rocksdb::DB::Open().
{
     return DB::Open(*options, dbname_, db);
   }
Status rocksdb::DBTest::Put (const Slice & k, const Slice & v, WriteOptions wo = WriteOptions()) inline
Definition at line 440 of file db_test.cc.
References db_, kMergePut, rocksdb::DB::Merge(), option_config_, and rocksdb::DB::Put().
Referenced by MakeTables(), and rocksdb::PrefixScanInit().
{
     if (kMergePut == option_config_ ) {
       return db_->Merge(wo, k, v);
     } else {
       return db_->Put(wo, k, v);
     }
   }
void rocksdb::DBTest::Reopen (Options * options = nullptr) inline
Definition at line 400 of file db_test.cc.
References ASSERT_OK, and TryReopen().
Referenced by DBTest().
{
     ASSERT_OK(TryReopen(options));
   }
uint64_t rocksdb::DBTest::Size (const Slice & start, const Slice & limit) inline
Definition at line 594 of file db_test.cc.
References db_, and rocksdb::DB::GetApproximateSizes().
{
     Range r(start, limit);
     uint64_t size;
     db_->GetApproximateSizes(&r, 1, &size);
     return size;
   }
int rocksdb::DBTest::TotalTableFiles () inline
Definition at line 550 of file db_test.cc.
References db_, rocksdb::DB::NumberLevels(), and NumTableFilesAtLevel().
{
     int result = 0;
     for (int level = 0; level < db_->NumberLevels(); level++) {
       result += NumTableFilesAtLevel(level);
     }
     return result;
   }
Status rocksdb::DBTest::TryReopen (Options * options = nullptr) inline
Definition at line 425 of file db_test.cc.
References rocksdb::Options::create_if_missing, CurrentOptions(), db_, dbname_, last_options_, and rocksdb::DB::Open().
Referenced by ChangeCompactOptions(), DestroyAndReopen(), and Reopen().
{
     delete db_;
     db_ = nullptr;
     Options opts;
     if (options != nullptr) {
       opts = *options;
     } else {
       opts = CurrentOptions();
       opts.create_if_missing = true;
     }
     last_options_ = opts;
     return DB::Open(opts, dbname_, &db_);
   }
void rocksdb::DBTest::VerifyIterLast (std::string expected_key) inline
Definition at line 670 of file db_test.cc.
References ASSERT_EQ, db_, IterStatus(), rocksdb::DB::NewIterator(), and rocksdb::Iterator::SeekToLast().
{
     Iterator* iter = db_->NewIterator(ReadOptions());
     iter->SeekToLast();
     ASSERT_EQ(IterStatus(iter), expected_key);
     delete iter;
   }
Member Data Documentation
DB* rocksdb::DBTest::db_
Definition at line 268 of file db_test.cc.
Referenced by Close(), Compact(), Contents(), CountLiveFiles(), dbfull(), DBTest(), Delete(), Destroy(), DumpFileCounts(), DumpSSTableList(), FilesPerLevel(), FillLevels(), Get(), NumTableFilesAtLevel(), Put(), Size(), TotalTableFiles(), TryReopen(), VerifyIterLast(), and ~DBTest().
std::string rocksdb::DBTest::dbname_
Definition at line 266 of file db_test.cc.
Referenced by CountFiles(), DBTest(), Destroy(), PureReopen(), TryReopen(), and ~DBTest().
SpecialEnv* rocksdb::DBTest::env_
Definition at line 267 of file db_test.cc.
Referenced by CountFiles(), and ~DBTest().
const FilterPolicy* rocksdb::DBTest::filter_policy_ private
Definition at line 240 of file db_test.cc.
Referenced by CurrentOptions(), DBTest(), and ~DBTest().
Options rocksdb::DBTest::last_options_
Definition at line 270 of file db_test.cc.
Referenced by AllEntriesFor(), ChangeCompactOptions(), ChangeOptions(), CountFiles(), DestroyAndReopen(), and TryReopen().
int rocksdb::DBTest::option_config_ protected
Definition at line 263 of file db_test.cc.
Referenced by ChangeCompactOptions(), ChangeOptions(), CurrentOptions(), and Put().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/db/db_test.cc