rippled: beast::tagged_integer_test Class Reference
beast::tagged_integer_test Class Reference
Classes
struct Tag1
struct Tag2
Public Member Functions
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Private Types
typedef tagged_integer
< std::uint32_t, Tag1 > TagInt1
typedef tagged_integer
< std::uint32_t, Tag2 > TagInt2
typedef tagged_integer
< std::uint64_t, Tag1 > TagInt3
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 31 of file tagged_integer.test.cpp.
Member Typedef Documentation
typedef tagged_integer<std::uint32_t, Tag1> beast::tagged_integer_test::TagInt1 private
Definition at line 38 of file tagged_integer.test.cpp.
typedef tagged_integer<std::uint32_t, Tag2> beast::tagged_integer_test::TagInt2 private
Definition at line 39 of file tagged_integer.test.cpp.
typedef tagged_integer<std::uint64_t, Tag1> beast::tagged_integer_test::TagInt3 private
Definition at line 40 of file tagged_integer.test.cpp.
Member Function Documentation
void beast::tagged_integer_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 106 of file tagged_integer.test.cpp.
References beast::unit_test::suite::expect(), beast::unit_test::suite::testcase(), and beast::unit_test::suite::unexpected().
     {
         TagInt1 const zero (0);
         TagInt1 const one (1);
         testcase ("Comparison Operators");
         expect (zero >= zero, "Should be greater than or equal");
         expect (zero == zero, "Should be equal");
         expect (one > zero, "Should be greater");
         expect (one >= zero, "Should be greater than or equal");
         expect (one != zero, "Should not be equal");
         unexpected (one < zero, "Should be greater");
         unexpected (one <= zero, "Should not be greater than or equal");
         unexpected (one == zero, "Should not be equal");
         testcase ("Arithmetic Operators");
         TagInt1 tmp;
         tmp = zero + 0u;
         expect (tmp == zero, "Should be equal");
         tmp = 1u + zero;
         expect (tmp == one, "Should be equal");
         expect(--tmp == zero, "Should be equal");
         expect(tmp++ == zero, "Should be equal");
         expect(tmp == one, "Should be equal");
         expect(tmp-- == one, "Should be equal");
         expect(tmp == zero, "Should be equal");
         expect(++tmp == one, "Should be equal");
         tmp = zero;
         tmp += 1u;
         expect(tmp == one, "Should be equal");
         tmp -= 1u;
         expect(tmp == zero, "Should be equal");
     }
The documentation for this class was generated from the following file:
rippled/src/beast/beast/utility/tests/tagged_integer.test.cpp