rippled: rocksdb::MemTableRep Class Reference
rocksdb::MemTableRep Class Reference abstract
#include <memtablerep.h>
Classes
class Iterator
class KeyComparator
Public Member Functions
virtual void Insert (const char *key)=0
virtual bool Contains (const char *key) const =0
virtual void MarkReadOnly ()
virtual size_t ApproximateMemoryUsage ()=0
virtual ~MemTableRep ()
virtual std::shared_ptr< Iterator > GetIterator ()=0
virtual std::shared_ptr< Iterator > GetIterator (const Slice &user_key)
virtual std::shared_ptr< Iterator > GetPrefixIterator (const Slice &prefix)
virtual std::shared_ptr< Iterator > GetDynamicPrefixIterator ()
Protected Member Functions
virtual Slice UserKey (const char *key) const
Detailed Description
Definition at line 54 of file memtablerep.h.
Constructor & Destructor Documentation
virtual rocksdb::MemTableRep::~MemTableRep () inline virtual
Definition at line 84 of file memtablerep.h.
 { }
Member Function Documentation
virtual size_t rocksdb::MemTableRep::ApproximateMemoryUsage () pure virtual
virtual bool rocksdb::MemTableRep::Contains (const char * key) const pure virtual
virtual std::shared_ptr<Iterator> rocksdb::MemTableRep::GetDynamicPrefixIterator () inline virtual
Definition at line 140 of file memtablerep.h.
References GetIterator().
Referenced by rocksdb::MemTableIterator::MemTableIterator().
{
     return GetIterator();
   }
virtual std::shared_ptr<Iterator> rocksdb::MemTableRep::GetIterator () pure virtual
Referenced by GetDynamicPrefixIterator(), GetIterator(), GetPrefixIterator(), and rocksdb::MemTableIterator::MemTableIterator().
virtual std::shared_ptr<Iterator> rocksdb::MemTableRep::GetIterator (const Slice & user_key) inline virtual
Definition at line 127 of file memtablerep.h.
References GetIterator().
{
     return GetIterator();
   }
virtual std::shared_ptr<Iterator> rocksdb::MemTableRep::GetPrefixIterator (const Slice & prefix) inline virtual
Definition at line 134 of file memtablerep.h.
References GetIterator().
Referenced by rocksdb::MemTableIterator::MemTableIterator().
{
     return GetIterator();
   }
virtual void rocksdb::MemTableRep::Insert (const char * key) pure virtual
virtual void rocksdb::MemTableRep::MarkReadOnly () inline virtual
Definition at line 78 of file memtablerep.h.
 { }
Slice rocksdb::MemTableRep::UserKey (const char * key) const protected virtual
Definition at line 73 of file memtable.cc.
References rocksdb::Slice::data(), rocksdb::GetLengthPrefixedSlice(), and rocksdb::Slice::size().
{
   Slice slice = GetLengthPrefixedSlice(key);
   return Slice(slice.data(), slice.size() - 8);
 }
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/include/rocksdb/memtablerep.h
rippled/src/ripple/rocksdb/rocksdb/db/memtable.cc