rippled: rocksdb::DBLoaderCommand Class Reference
rocksdb::DBLoaderCommand Class Reference
#include <ldb_cmd.h>
Public Member Functions
DBLoaderCommand (string &db_name, vector< string > &args)
DBLoaderCommand (const vector< string > &params, const map< string, string > &options, const vector< string > &flags)
virtual void DoCommand ()
virtual Options PrepareOptionsForOpenDB ()
Public Member Functions inherited from rocksdb::LDBCommand
bool ValidateCmdLineOptions ()
virtual void SetOptions (Options options)
virtual bool NoDBOpen ()
virtual ~LDBCommand ()
void Run ()
LDBCommandExecuteResult GetExecuteState ()
void ClearPreviousRunState ()
Static Public Member Functions
static string Name ()
static void Help (string &ret)
Static Public Member Functions inherited from rocksdb::LDBCommand
static LDBCommand * InitFromCmdLineArgs (const vector< string > &args, const Options &options=Options())
static LDBCommand * InitFromCmdLineArgs (int argc, char **argv, const Options &options=Options())
static string HexToString (const string &str)
static string StringToHex (const string &str)
Private Attributes
bool create_if_missing_
bool disable_wal_
bool bulk_load_
bool compact_
Static Private Attributes
static const string ARG_DISABLE_WAL = "disable_wal"
static const string ARG_BULK_LOAD = "bulk_load"
static const string ARG_COMPACT = "compact"
Additional Inherited Members
Static Public Attributes inherited from rocksdb::LDBCommand
static const string ARG_DB = "db"
static const string ARG_HEX = "hex"
static const string ARG_KEY_HEX = "key_hex"
static const string ARG_VALUE_HEX = "value_hex"
static const string ARG_TTL = "ttl"
static const string ARG_TTL_START = "start_time"
static const string ARG_TTL_END = "end_time"
static const string ARG_TIMESTAMP = "timestamp"
static const string ARG_FROM = "from"
static const string ARG_TO = "to"
static const string ARG_MAX_KEYS = "max_keys"
static const string ARG_BLOOM_BITS = "bloom_bits"
static const string ARG_COMPRESSION_TYPE = "compression_type"
static const string ARG_BLOCK_SIZE = "block_size"
static const string ARG_AUTO_COMPACTION = "auto_compaction"
static const string ARG_WRITE_BUFFER_SIZE = "write_buffer_size"
static const string ARG_FILE_SIZE = "file_size"
static const string ARG_CREATE_IF_MISSING = "create_if_missing"
static const char * DELIM = " ==> "
Protected Member Functions inherited from rocksdb::LDBCommand
bool ParseKeyValue (const string &line, string *key, string *value, bool is_key_hex, bool is_value_hex)
LDBCommand (const map< string, string > &options, const vector< string > &flags, bool is_read_only, const vector< string > &valid_cmd_line_options)
void OpenDB ()
void CloseDB ()
vector< string > BuildCmdLineOptions (vector< string > options)
bool ParseIntOption (const map< string, string > &options, const string &option, int &value, LDBCommandExecuteResult &exec_state)
bool ParseStringOption (const map< string, string > &options, const string &option, string *value)
Static Protected Member Functions inherited from rocksdb::LDBCommand
static string PrintKeyValue (const string &key, const string &value, bool is_key_hex, bool is_value_hex)
static string PrintKeyValue (const string &key, const string &value, bool is_hex)
static bool IsFlagPresent (const vector< string > &flags, const string &flag)
static string HelpRangeCmdArgs ()
Protected Attributes inherited from rocksdb::LDBCommand
LDBCommandExecuteResult exec_state_
string db_path_
DB * db_
StackableDB * sdb_
bool is_read_only_
bool is_key_hex_
bool is_value_hex_
bool is_db_ttl_
bool timestamp_
const map< string, string > option_map_
const vector< string > flags_
const vector< string > valid_cmd_line_options_
Options options_
Detailed Description
Definition at line 440 of file ldb_cmd.h.
Constructor & Destructor Documentation
rocksdb::DBLoaderCommand::DBLoaderCommand (string & db_name, vector< string > & args)
rocksdb::DBLoaderCommand::DBLoaderCommand (const vector< string > & params, const map< string, string > & options, const vector< string > & flags)
Definition at line 391 of file ldb_cmd.cc.
References ARG_BULK_LOAD, ARG_COMPACT, rocksdb::LDBCommand::ARG_CREATE_IF_MISSING, ARG_DISABLE_WAL, rocksdb::LDBCommand::ARG_FROM, rocksdb::LDBCommand::ARG_HEX, rocksdb::LDBCommand::ARG_KEY_HEX, rocksdb::LDBCommand::ARG_TO, and rocksdb::LDBCommand::ARG_VALUE_HEX.
                                                                        :
     LDBCommand(options, flags, false,
                BuildCmdLineOptions({ARG_HEX, ARG_KEY_HEX, ARG_VALUE_HEX,
                                     ARG_FROM, ARG_TO, ARG_CREATE_IF_MISSING,
                                     ARG_DISABLE_WAL, ARG_BULK_LOAD,
                                     ARG_COMPACT})),
Member Function Documentation
void rocksdb::DBLoaderCommand::DoCommand () virtual
Implements rocksdb::LDBCommand.
Definition at line 426 of file ldb_cmd.cc.
References compact_, rocksdb::DB::CompactRange(), rocksdb::LDBCommand::db_, disable_wal_, rocksdb::WriteOptions::disableWAL, rocksdb::LDBCommand::is_key_hex_, rocksdb::LDBCommand::is_value_hex_, rocksdb::LDBCommand::ParseKeyValue(), rocksdb::DB::Put(), and value.
{
   if (!db_) {
     return;
   }
   WriteOptions write_options;
   if (disable_wal_) {
     write_options.disableWAL = true;
   }
   int bad_lines = 0;
   string line;
   while (getline(cin, line, '\n')) {
     string key;
     string value;
     if (ParseKeyValue(line, &key, &value, is_key_hex_, is_value_hex_)) {
       db_->Put(write_options, Slice(key), Slice(value));
     } else if (0 == line.find("Keys in range:")) {
       // ignore this line
     } else if (0 == line.find("Created bg thread 0x")) {
       // ignore this line
     } else {
       bad_lines ++;
     }
   }
   if (bad_lines > 0) {
     cout << "Warning: " << bad_lines << " bad lines ignored." << endl;
   }
   if (compact_) {
     db_->CompactRange(nullptr, nullptr);
   }
 }
void rocksdb::DBLoaderCommand::Help (string & ret) static
Definition at line 407 of file ldb_cmd.cc.
References ARG_BULK_LOAD, ARG_COMPACT, rocksdb::LDBCommand::ARG_CREATE_IF_MISSING, ARG_DISABLE_WAL, and Name().
Referenced by rocksdb::LDBCommandRunner::PrintHelp().
{
   ret.append("  ");
   ret.append(DBLoaderCommand::Name());
   ret.append(" [--" + ARG_CREATE_IF_MISSING + "]");
   ret.append(" [--" + ARG_DISABLE_WAL + "]");
   ret.append(" [--" + ARG_BULK_LOAD + "]");
   ret.append(" [--" + ARG_COMPACT + "]");
   ret.append("\n");
 }
static string rocksdb::DBLoaderCommand::Name () inline static
Definition at line 442 of file ldb_cmd.h.
Referenced by Help(), and rocksdb::LDBCommand::SelectCommand().
 { return "load"; }
Options rocksdb::DBLoaderCommand::PrepareOptionsForOpenDB () virtual
Reimplemented from rocksdb::LDBCommand.
Definition at line 417 of file ldb_cmd.cc.
References bulk_load_, rocksdb::Options::create_if_missing, create_if_missing_, rocksdb::Options::PrepareForBulkLoad(), and rocksdb::LDBCommand::PrepareOptionsForOpenDB().
{
   Options opt = LDBCommand::PrepareOptionsForOpenDB();
   opt.create_if_missing = create_if_missing_;
   if (bulk_load_) {
     opt.PrepareForBulkLoad();
   }
   return opt;
 }
Member Data Documentation
const string rocksdb::DBLoaderCommand::ARG_BULK_LOAD = "bulk_load" static private
Definition at line 461 of file ldb_cmd.h.
Referenced by DBLoaderCommand(), and Help().
const string rocksdb::DBLoaderCommand::ARG_COMPACT = "compact" static private
Definition at line 462 of file ldb_cmd.h.
Referenced by DBLoaderCommand(), and Help().
const string rocksdb::DBLoaderCommand::ARG_DISABLE_WAL = "disable_wal" static private
Definition at line 460 of file ldb_cmd.h.
Referenced by DBLoaderCommand(), and Help().
bool rocksdb::DBLoaderCommand::bulk_load_ private
Definition at line 457 of file ldb_cmd.h.
Referenced by PrepareOptionsForOpenDB().
bool rocksdb::DBLoaderCommand::compact_ private
Definition at line 458 of file ldb_cmd.h.
Referenced by DoCommand().
bool rocksdb::DBLoaderCommand::create_if_missing_ private
Definition at line 455 of file ldb_cmd.h.
Referenced by PrepareOptionsForOpenDB().
bool rocksdb::DBLoaderCommand::disable_wal_ private
Definition at line 456 of file ldb_cmd.h.
Referenced by DoCommand().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/util/ldb_cmd.h
rippled/src/ripple/rocksdb/rocksdb/util/ldb_cmd.cc