rippled: beast::UnitTestUtilities Namespace Reference
beast::UnitTestUtilities Namespace Reference
Classes
struct Payload
Functions
template<class T >
void repeatableShuffle (int const numberOfItems, T &arrayOfItems, Random &r)
template<class T >
void repeatableShuffle (int const numberOfItems, T &arrayOfItems, std::int64_t seedValue)
Function Documentation
template<class T > void beast::UnitTestUtilities::repeatableShuffle (int const numberOfItems, T & arrayOfItems, Random & r)
Fairly shuffle an array pseudo-randomly.
Definition at line 29 of file UnitTestUtilities.h.
References beast::Random::nextInt(), and beast::asio::swap().
Referenced by beast::RandomAccessFile_test::createRecords(), repeatableShuffle(), ripple::NodeStore::Backend_test::testBackend(), beast::RandomAccessFile_test::testFile(), and ripple::NodeStore::NodeStoreDatabase_test::testNodeStore().
 {
     for (int i = numberOfItems - 1; i > 0; --i)
     {
         int const choice = r.nextInt (i + 1);
         std::swap (arrayOfItems [i], arrayOfItems [choice]);
     }
 }
template<class T > void beast::UnitTestUtilities::repeatableShuffle (int const numberOfItems, T & arrayOfItems, std::int64_t seedValue)
Definition at line 39 of file UnitTestUtilities.h.
References repeatableShuffle().
 {
     Random r (seedValue);
     repeatableShuffle (numberOfItems, arrayOfItems, r);
 }