rippled: rocksdb::port::CondVar Class Reference
rocksdb::port::CondVar Class Reference
#include <port_example.h>
Public Member Functions
CondVar (Mutex *mu)
~CondVar ()
void Wait ()
void Signal ()
void SignallAll ()
CondVar (Mutex *mu)
~CondVar ()
void Wait ()
void Signal ()
void SignalAll ()
Private Attributes
pthread_cond_t cv_
Mutex * mu_
Detailed Description
Definition at line 50 of file port_example.h.
Constructor & Destructor Documentation
rocksdb::port::CondVar::CondVar (Mutex * mu) explicit
Definition at line 52 of file port_posix.cc.
References cv_, and rocksdb::port::PthreadCall().
     : mu_(mu) {
     PthreadCall("init cv", pthread_cond_init(&cv_, NULL));
 }
rocksdb::port::CondVar::~CondVar ()
Definition at line 57 of file port_posix.cc.
References cv_, and rocksdb::port::PthreadCall().
 { PthreadCall("destroy cv", pthread_cond_destroy(&cv_)); }
rocksdb::port::CondVar::CondVar (Mutex * mu) explicit
rocksdb::port::CondVar::~CondVar ()
Member Function Documentation
void rocksdb::port::CondVar::Signal ()
Definition at line 63 of file port_posix.cc.
References cv_, and rocksdb::port::PthreadCall().
Referenced by rocksdb::TestState::Change(), rocksdb::VersionSet::LogAndApply(), and rocksdb::DBImpl::Write().
                      {
   PthreadCall("signal", pthread_cond_signal(&cv_));
 }
void rocksdb::port::CondVar::Signal ()
void rocksdb::port::CondVar::SignalAll ()
Definition at line 67 of file port_posix.cc.
References cv_, and rocksdb::port::PthreadCall().
Referenced by rocksdb::DBImpl::BackgroundCallCompaction(), rocksdb::DBImpl::BackgroundCallFlush(), rocksdb::DBImpl::DoCompactionWork(), rocksdb::DBImpl::LogDBDeployStats(), rocksdb::Benchmark::RunBenchmark(), and rocksdb::Benchmark::ThreadBody().
{
   PthreadCall("broadcast", pthread_cond_broadcast(&cv_));
 }
void rocksdb::port::CondVar::SignallAll ()
void rocksdb::port::CondVar::Wait ()
Definition at line 59 of file port_posix.cc.
References cv_, rocksdb::port::Mutex::mu_, mu_, and rocksdb::port::PthreadCall().
Referenced by rocksdb::VersionSet::LogAndApply(), rocksdb::DBImpl::MakeRoomForWrite(), rocksdb::DBImpl::ReFitLevel(), rocksdb::Benchmark::RunBenchmark(), rocksdb::DBImpl::TEST_CompactRange(), rocksdb::DBImpl::TEST_Destroy_DBImpl(), rocksdb::DBImpl::TEST_WaitForCompact(), rocksdb::Benchmark::ThreadBody(), rocksdb::TestState::Wait(), rocksdb::DBImpl::WaitForFlushMemTable(), rocksdb::DBImpl::Write(), and rocksdb::DBImpl::~DBImpl().
                    {
   PthreadCall("wait", pthread_cond_wait(&cv_, &mu_->mu_));
 }
void rocksdb::port::CondVar::Wait ()
Member Data Documentation
pthread_cond_t rocksdb::port::CondVar::cv_ private
Definition at line 132 of file port_posix.h.
Referenced by CondVar(), Signal(), SignalAll(), Wait(), and ~CondVar().
Mutex* rocksdb::port::CondVar::mu_ private
Definition at line 133 of file port_posix.h.
Referenced by Wait().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/port/port_example.h
rippled/src/ripple/rocksdb/rocksdb/port/port_posix.h
rippled/src/ripple/rocksdb/rocksdb/port/port_posix.cc