rippled: beast::hash_append_tests::prng_hasher< PRNG > Class Template Reference
beast::hash_append_tests::prng_hasher< PRNG > Class Template Reference
Public Member Functions
prng_hasher (std::size_t seed=0)
void append (void const *data, std::size_t bytes) noexcept
operator std::size_t () noexcept
Public Member Functions inherited from beast::block_stream< std::size_t, prng_hasher< PRNG > >
block_stream ()
void operator() (void const *data, std::size_t bytes) noexcept
Private Types
typedef block_stream
< std::size_t, prng_hasher
< PRNG > > base
Private Member Functions
void process_block (std::size_t block)
Private Attributes
std::size_t m_seed
PRNG m_prng
friend base
Additional Inherited Members
Protected Member Functions inherited from beast::block_stream< std::size_t, prng_hasher< PRNG > >
void finish ()
Detailed Description
template<class PRNG = std::conditional_t < sizeof(std::size_t)==sizeof(std::uint64_t), std::mt19937_64, std::mt19937 >>
class beast::hash_append_tests::prng_hasher< PRNG >
Definition at line 239 of file hash_append.test.cpp.
Member Typedef Documentation
template<class PRNG = std::conditional_t < sizeof(std::size_t)==sizeof(std::uint64_t), std::mt19937_64, std::mt19937 >> typedef block_stream<std::size_t, prng_hasher <PRNG> > beast::hash_append_tests::prng_hasher< PRNG >::base private
Definition at line 246 of file hash_append.test.cpp.
Constructor & Destructor Documentation
template<class PRNG = std::conditional_t < sizeof(std::size_t)==sizeof(std::uint64_t), std::mt19937_64, std::mt19937 >> beast::hash_append_tests::prng_hasher< PRNG >::prng_hasher (std::size_t seed = 0) inline
Definition at line 258 of file hash_append.test.cpp.
         : m_seed (seed)
     {
     }
Member Function Documentation
template<class PRNG = std::conditional_t < sizeof(std::size_t)==sizeof(std::uint64_t), std::mt19937_64, std::mt19937 >> void beast::hash_append_tests::prng_hasher< PRNG >::append (void const * data, std::size_t bytes) inline noexcept
Definition at line 264 of file hash_append.test.cpp.
References beast::block_stream< std::size_t, prng_hasher< PRNG > >::operator()().
     {
         base::operator() (data, bytes);
     }
template<class PRNG = std::conditional_t < sizeof(std::size_t)==sizeof(std::uint64_t), std::mt19937_64, std::mt19937 >> beast::hash_append_tests::prng_hasher< PRNG >::operator std::size_t () inline explicit noexcept
Definition at line 270 of file hash_append.test.cpp.
References beast::block_stream< std::size_t, prng_hasher< PRNG > >::finish(), and beast::hash_append_tests::prng_hasher< PRNG >::m_seed.
     {
         base::finish();
         return m_seed;
     }
template<class PRNG = std::conditional_t < sizeof(std::size_t)==sizeof(std::uint64_t), std::mt19937_64, std::mt19937 >> void beast::hash_append_tests::prng_hasher< PRNG >::process_block (std::size_t block) inline private
Definition at line 251 of file hash_append.test.cpp.
References beast::hash_append_tests::prng_hasher< PRNG >::m_prng, and beast::hash_append_tests::prng_hasher< PRNG >::m_seed.
     {
         m_prng.seed (m_seed + block);
         m_seed = m_prng();
     }
Member Data Documentation
template<class PRNG = std::conditional_t < sizeof(std::size_t)==sizeof(std::uint64_t), std::mt19937_64, std::mt19937 >> friend beast::hash_append_tests::prng_hasher< PRNG >::base private
Definition at line 247 of file hash_append.test.cpp.
template<class PRNG = std::conditional_t < sizeof(std::size_t)==sizeof(std::uint64_t), std::mt19937_64, std::mt19937 >> PRNG beast::hash_append_tests::prng_hasher< PRNG >::m_prng private
Definition at line 244 of file hash_append.test.cpp.
Referenced by beast::hash_append_tests::prng_hasher< PRNG >::process_block().
template<class PRNG = std::conditional_t < sizeof(std::size_t)==sizeof(std::uint64_t), std::mt19937_64, std::mt19937 >> std::size_t beast::hash_append_tests::prng_hasher< PRNG >::m_seed private
Definition at line 243 of file hash_append.test.cpp.
Referenced by beast::hash_append_tests::prng_hasher< PRNG >::operator std::size_t(), and beast::hash_append_tests::prng_hasher< PRNG >::process_block().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/container/tests/hash_append.test.cpp