rippled: TestOverlay::PeerType< Config > Class Template Reference
TestOverlay::PeerType< Config > Class Template Reference
#include <PeerType.h>
Public Types
typedef Config::Peer Peer
typedef Config::Payload Payload
typedef Config::PeerLogic PeerLogic
typedef Config::Message Message
typedef Config::Network Network
typedef Config::State State
typedef State::UniqueID UniqueID
typedef ConnectionType< Config > Connection
typedef std::vector< Connection > Connections
typedef boost::unordered_set
< UniqueID > MessageTable
Public Member Functions
PeerType (Network &network)
UniqueID id () const
bool connect_to (Peer &peer)
bool disconnect (Peer &peer)
void send (Peer &peer, Payload const &payload)
bool send (Peer &peer, Message const &m)
void send_all (Payload const &payload)
bool send_all (Message const &m)
template<class Predicate >
void send_all_if (Payload const &payload, Predicate p)
template<class Predicate >
bool send_all_if (Message const &m, Predicate p)
void pre_step ()
void step ()
void post_step ()
Results & results ()
Results const & results () const
Network & network ()
Network const & network () const
Connections & connections ()
Connections const & connections () const
MessageTable & msg_table ()
MessageTable const & msg_table () const
Private Member Functions
bool send_to (Peer &peer, Message const &m)
Private Attributes
Results m_results
Network & m_network
UniqueID const m_id
Connections m_connections
MessageTable m_msg_table
PeerLogic m_logic
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
template<class Config>
class TestOverlay::PeerType< Config >
A peer in the overlay network.
Definition at line 30 of file PeerType.h.
Member Typedef Documentation
template<class Config > typedef ConnectionType<Config> TestOverlay::PeerType< Config >::Connection
Definition at line 42 of file PeerType.h.
template<class Config > typedef std::vector<Connection> TestOverlay::PeerType< Config >::Connections
Definition at line 43 of file PeerType.h.
template<class Config > typedef Config::Message TestOverlay::PeerType< Config >::Message
Definition at line 38 of file PeerType.h.
template<class Config > typedef boost::unordered_set<UniqueID> TestOverlay::PeerType< Config >::MessageTable
Definition at line 45 of file PeerType.h.
template<class Config > typedef Config::Network TestOverlay::PeerType< Config >::Network
Definition at line 39 of file PeerType.h.
template<class Config > typedef Config::Payload TestOverlay::PeerType< Config >::Payload
Definition at line 36 of file PeerType.h.
template<class Config > typedef Config::Peer TestOverlay::PeerType< Config >::Peer
Definition at line 35 of file PeerType.h.
template<class Config > typedef Config::PeerLogic TestOverlay::PeerType< Config >::PeerLogic
Definition at line 37 of file PeerType.h.
template<class Config > typedef Config::State TestOverlay::PeerType< Config >::State
Definition at line 40 of file PeerType.h.
template<class Config > typedef State::UniqueID TestOverlay::PeerType< Config >::UniqueID
Definition at line 41 of file PeerType.h.
Constructor & Destructor Documentation
template<class Config > TestOverlay::PeerType< Config >::PeerType (Network & network) inline explicit
Definition at line 47 of file PeerType.h.
         : m_network (network)
         , m_id (network.state().nextPeerID())
         , m_logic (*this)
     {
     }
Member Function Documentation
template<class Config > bool TestOverlay::PeerType< Config >::connect_to (Peer & peer) inline
Establish an outgoing connection to peer.
Returns
true if the peer is not us and not connected already.
Definition at line 115 of file PeerType.h.
References TestOverlay::PeerType< Config >::connections().
     {
         if (&peer == this)
             return false;
         typename Connections::iterator const iter (std::find_if (
             connections().begin(), connections().end (),
                 typename Connection::IsPeer (peer)));
         if (iter != connections().end())
             return false;
         assert (std::find_if (peer.connections().begin(),
             peer.connections().end(),
                 typename Connection::IsPeer (*this))
                     == peer.connections().end ());
         connections().push_back (Connection (peer, false));
         peer.connections().push_back (Connection (*this, true));
         return true;
     }
template<class Config > Connections& TestOverlay::PeerType< Config >::connections () inline
Return the container holding active connections.
Definition at line 88 of file PeerType.h.
References TestOverlay::PeerType< Config >::m_connections.
Referenced by TestOverlay::PeerType< Config >::connect_to(), TestOverlay::PeerType< Config >::disconnect(), TestOverlay::PeerType< Config >::post_step(), TestOverlay::PeerType< Config >::send_all_if(), and TestOverlay::PeerType< Config >::step().
     {
         return m_connections;
     }
template<class Config > Connections const& TestOverlay::PeerType< Config >::connections () const inline
Definition at line 93 of file PeerType.h.
References TestOverlay::PeerType< Config >::m_connections.
     {
         return m_connections;
     }
template<class Config > bool TestOverlay::PeerType< Config >::disconnect (Peer & peer) inline
Disconnect from a peer.
Returns
true if the peer was found and disconnected.
Definition at line 136 of file PeerType.h.
References TestOverlay::PeerType< Config >::connections().
     {
         if (&peer == this)
             return false;
         typename  Connections::iterator const iter1 (std::find_if (
             connections().begin(), connections().end (),
                 typename Connection::IsPeer (peer)));
         if (iter1 == connections().end())
             return false;
         typename Connections::iterator const iter2 (std::find_if (
             peer.connections().begin(), peer.connections().end (),
                 typename Connection::IsPeer (*this)));
         assert (iter2 != peer.connections().end());
         connections().erase (iter1);
         peer.connections().erase (iter2);
         return true;
     }
template<class Config > UniqueID TestOverlay::PeerType< Config >::id () const inline
Return the unique ID associated with this peer.
Definition at line 68 of file PeerType.h.
References TestOverlay::PeerType< Config >::m_id.
     {
         return m_id;
     }
template<class Config > MessageTable& TestOverlay::PeerType< Config >::msg_table () inline
Return the container holding the message ids seen by this peer.
Definition at line 101 of file PeerType.h.
References TestOverlay::PeerType< Config >::m_msg_table.
Referenced by TestOverlay::PeerType< Config >::send(), TestOverlay::PeerType< Config >::send_all(), TestOverlay::PeerType< Config >::send_all_if(), and TestOverlay::PeerType< Config >::step().
     {
         return m_msg_table;
     }
template<class Config > MessageTable const& TestOverlay::PeerType< Config >::msg_table () const inline
Definition at line 106 of file PeerType.h.
References TestOverlay::PeerType< Config >::m_msg_table.
     {
         return m_msg_table;
     }
template<class Config > Network& TestOverlay::PeerType< Config >::network () inline
Return the network this peer belongs to.
Definition at line 75 of file PeerType.h.
References TestOverlay::PeerType< Config >::m_network.
Referenced by TestOverlay::PeerType< Config >::send(), TestOverlay::PeerType< Config >::send_all(), and TestOverlay::PeerType< Config >::send_all_if().
     {
         return m_network;
     }
template<class Config > Network const& TestOverlay::PeerType< Config >::network () const inline
Definition at line 80 of file PeerType.h.
References TestOverlay::PeerType< Config >::m_network.
     {
         return m_network;
     }
template<class Config > void TestOverlay::PeerType< Config >::post_step () inline
Called once on each Peer object after every iteration.
Definition at line 275 of file PeerType.h.
References TestOverlay::PeerType< Config >::connections(), TestOverlay::PeerType< Config >::m_logic, TestOverlay::ConnectionType< Config >::messages(), and TestOverlay::ConnectionType< Config >::pending().
     {
         // Move pending messages to current messages
         for (typename Connections::iterator iter (connections().begin());
             iter != connections().end(); ++iter)
         {
             Connection& c (*iter);
             c.messages().clear ();
             c.messages().swap (c.pending());
         }
         m_logic.post_step ();
     }
template<class Config > void TestOverlay::PeerType< Config >::pre_step () inline
Called once on each Peer object before every iteration.
Definition at line 248 of file PeerType.h.
References TestOverlay::PeerType< Config >::m_logic.
     {
         m_logic.pre_step ();
     }
template<class Config > Results& TestOverlay::PeerType< Config >::results () inline
Return the pending Results data associated with this peer.
Definition at line 56 of file PeerType.h.
References TestOverlay::PeerType< Config >::m_results.
Referenced by TestOverlay::PeerType< Config >::send_to(), and TestOverlay::PeerType< Config >::step().
     {
         return m_results;
     }
template<class Config > Results const& TestOverlay::PeerType< Config >::results () const inline
Definition at line 61 of file PeerType.h.
References TestOverlay::PeerType< Config >::m_results.
     {
         return m_results;
     }
template<class Config > void TestOverlay::PeerType< Config >::send (Peer & peer, Payload const & payload) inline
Send a new message to a specific connection. A new message with an unused id is created with the given payload.
Definition at line 159 of file PeerType.h.
References TestOverlay::PeerType< Config >::msg_table(), TestOverlay::PeerType< Config >::network(), and TestOverlay::PeerType< Config >::send_to().
     {
         Message const m (network().state().nextMessageID(), payload);
         assert (msg_table().insert (m.id()).second);
         assert (send_to (peer,
             Message (network().state().nextMessageID(),
                 payload)));
     }
template<class Config > bool TestOverlay::PeerType< Config >::send (Peer & peer, Message const & m) inline
Send a message to a specific connection. The message already has an id and associated payload.
Definition at line 171 of file PeerType.h.
References TestOverlay::PeerType< Config >::send_to().
     {
         return send_to (peer, m);
     }
template<class Config > void TestOverlay::PeerType< Config >::send_all (Payload const & payload) inline
Send a new message to all connections. A new message with an unused id is created with the given payload.
Definition at line 179 of file PeerType.h.
References TestOverlay::PeerType< Config >::msg_table(), TestOverlay::PeerType< Config >::network(), and TestOverlay::PeerType< Config >::send_all_if().
     {
         Message const m (network().state().nextMessageID(), payload);
         assert (msg_table().insert (m.id()).second);
         assert (send_all_if (m,
             typename Connection::Any ()));
     };
template<class Config > bool TestOverlay::PeerType< Config >::send_all (Message const & m) inline
Send a message to all connections. The message already has an id and associated payload.
Definition at line 190 of file PeerType.h.
References TestOverlay::PeerType< Config >::send_all_if().
     {
         return send_all_if (m,
             typename Connection::Any ());
     };
template<class Config > template<class Predicate > void TestOverlay::PeerType< Config >::send_all_if (Payload const & payload, Predicate p) inline
Create a new message and send it to each connection that passes the predicate. Predicate is a UnaryPredicate that takes a Connection parameter. A new message with an unused id is created with the given payload.
Definition at line 201 of file PeerType.h.
References TestOverlay::PeerType< Config >::msg_table(), and TestOverlay::PeerType< Config >::network().
Referenced by TestOverlay::PeerType< Config >::send_all().
     {
         Message const m (network().state().nextMessageID(), payload);
         assert (msg_table().insert (m.id()).second);
         assert (send_all_if (m, p));
     }
template<class Config > template<class Predicate > bool TestOverlay::PeerType< Config >::send_all_if (Message const & m, Predicate p) inline
Send an existing message to all connections that pass the predicate.
Returns
true if at least one message was sent.
Definition at line 212 of file PeerType.h.
References TestOverlay::PeerType< Config >::connections(), and TestOverlay::PeerType< Config >::send_to().
     {
         bool sent = false;
         for (typename Connections::iterator iter (connections().begin());
             iter != connections().end(); ++iter)
             if (p (*iter))
                 sent = send_to (iter->peer(), m) || sent;
         return sent;
     }
template<class Config > bool TestOverlay::PeerType< Config >::send_to (Peer & peer, Message const & m) inline private
Definition at line 226 of file PeerType.h.
References TestOverlay::Results::dropped, TestOverlay::PeerType< Config >::results(), and TestOverlay::Results::sent.
Referenced by TestOverlay::PeerType< Config >::send(), and TestOverlay::PeerType< Config >::send_all_if().
     {
         // already seen it?
         if (peer.msg_table().count(m.id()) != 0)
         {
             ++results().dropped;
             return false;
         }
         typename Connections::iterator const iter (std::find_if (
             peer.connections().begin(), peer.connections().end (),
                 typename Connection::IsPeer (*this)));
         assert (iter != peer.connections().end());
         assert (peer.msg_table().insert(m.id()).second);
         iter->pending().push_back (m);
         ++results().sent;
         return true;
     }
template<class Config > void TestOverlay::PeerType< Config >::step () inline
Called once on each Peer object during every iteration.
Definition at line 254 of file PeerType.h.
References TestOverlay::PeerType< Config >::connections(), TestOverlay::PeerType< Config >::m_logic, TestOverlay::ConnectionType< Config >::messages(), TestOverlay::PeerType< Config >::msg_table(), TestOverlay::Results::received, and TestOverlay::PeerType< Config >::results().
     {
         // Call logic with current messages
         for (typename Connections::iterator iter (connections().begin());
             iter != connections().end(); ++iter)
         {
             Connection& c (*iter);
             for (typename Connection::Messages::iterator iter (
                 c.messages().begin()); iter != c.messages().end(); ++iter)
             {
                 Message const& m (*iter);
                 assert (msg_table().count (m.id()) == 1);
                 m_logic.receive (c, m);
                 ++results().received;
             }
         }
         m_logic.step ();
     }
Member Data Documentation
template<class Config > Connections TestOverlay::PeerType< Config >::m_connections private
Definition at line 293 of file PeerType.h.
Referenced by TestOverlay::PeerType< Config >::connections().
template<class Config > UniqueID const TestOverlay::PeerType< Config >::m_id private
Definition at line 292 of file PeerType.h.
Referenced by TestOverlay::PeerType< Config >::id().
template<class Config > PeerLogic TestOverlay::PeerType< Config >::m_logic private
Definition at line 295 of file PeerType.h.
Referenced by TestOverlay::PeerType< Config >::post_step(), TestOverlay::PeerType< Config >::pre_step(), and TestOverlay::PeerType< Config >::step().
template<class Config > MessageTable TestOverlay::PeerType< Config >::m_msg_table private
Definition at line 294 of file PeerType.h.
Referenced by TestOverlay::PeerType< Config >::msg_table().
template<class Config > Network& TestOverlay::PeerType< Config >::m_network private
Definition at line 291 of file PeerType.h.
Referenced by TestOverlay::PeerType< Config >::network().
template<class Config > Results TestOverlay::PeerType< Config >::m_results private
Definition at line 290 of file PeerType.h.
Referenced by TestOverlay::PeerType< Config >::results().
The documentation for this class was generated from the following file:
rippled/src/ripple/testoverlay/api/PeerType.h