rippled: beast::LexicalCastUtilities Struct Reference
beast::LexicalCastUtilities Struct Reference
#include <LexicalCast.h>
Static Public Member Functions
template<class IntType , class InputIterator >
static bool parseSigned (IntType &result, InputIterator begin, InputIterator end)
template<class IntType , class InputIterator >
static bool parseUnsigned (IntType &result, InputIterator begin, InputIterator end)
Static Public Attributes
static unsigned char const s_digitTable [256]
Detailed Description
Definition at line 27 of file LexicalCast.h.
Member Function Documentation
template<class IntType , class InputIterator > static bool beast::LexicalCastUtilities::parseSigned (IntType & result, InputIterator begin, InputIterator end) inline static
Definition at line 33 of file LexicalCast.h.
References ripple::max(), ripple::min(), and s_digitTable.
Referenced by beast::LexicalCast< Out, String >::operator()().
     {
         if (0 == std::distance (begin, end))
             return false;
         std::uint64_t accum = 0;
         InputIterator it = begin;
         // process sign
         bool negative = false;
         if ('+' == *it)
         {
             ++it;
         }
         else if ('-' == *it)
         {
             ++it;
             negative = true;
         }
         if (end == it)
             return false;
         // calc max of abs value
         std::uint64_t max;
         if (negative)
             max = static_cast <std::uint64_t> (
                 -(static_cast <std::int64_t> (std::numeric_limits <IntType>::min ())));
         else
             max = std::numeric_limits <IntType>::max ();
         // process digits
         while (end != it)
         {
             std::uint64_t const digit = static_cast <IntType> (
                 s_digitTable [static_cast <unsigned int> (*it++)]);
             if (0xFF == digit)
                 return false;
             std::uint64_t const overflow = (max - digit) / 10;
             if (accum > overflow)
                 return false;
             accum = (10 * accum) + digit;
         }
         if (negative)
         {
             result = -static_cast <IntType> (accum);
         }
         else
         {
             result = static_cast <IntType> (accum);
         }
         return true;
     }
template<class IntType , class InputIterator > static bool beast::LexicalCastUtilities::parseUnsigned (IntType & result, InputIterator begin, InputIterator end) inline static
Definition at line 93 of file LexicalCast.h.
References ripple::max(), and s_digitTable.
Referenced by beast::LexicalCast< Out, String >::operator()().
     {
         if (0 == std::distance (begin, end))
             return false;
         std::uint64_t accum = 0;
         InputIterator it = begin;
         std::uint64_t const max = std::numeric_limits <IntType>::max ();
         // process digits
         while (end != it)
         {
             std::uint64_t const digit = static_cast <IntType> (
                 s_digitTable [static_cast <unsigned int> (*it++)]);
             if (0xFF == digit)
                 return false;
             std::uint64_t const overflow = (max - digit) / 10;
             if (accum > overflow)
                 return false;
             accum = (10 * accum) + digit;
         }
         result = static_cast <IntType> (accum);
         return true;
     }
Member Data Documentation
unsigned char const beast::LexicalCastUtilities::s_digitTable static
Initial value:
= {
   0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
   0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
   0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
   0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
   0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
   0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
   0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
   0x08, 0x09, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
   0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
   0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
   0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
   0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
   0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
   0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
   0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
   0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
   0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
   0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
   0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
   0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
   0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
   0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
   0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
   0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
   0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
   0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
   0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
   0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
   0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
   0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
   0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
   0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF
}
Definition at line 29 of file LexicalCast.h.
Referenced by parseSigned(), and parseUnsigned().
The documentation for this struct was generated from the following files:
rippled/src/beast/modules/beast_core/text/LexicalCast.h
rippled/src/beast/modules/beast_core/text/LexicalCast.cpp