rippled: ripple::LocalTx Class Reference
ripple::LocalTx Class Reference
Public Member Functions
LocalTx (LedgerIndex index, SerializedTransaction::ref txn)
uint256 const & getID ()
std::uint32_t getSeq ()
bool isExpired (LedgerIndex i)
SerializedTransaction::ref getTX ()
RippleAddress const & getAccount ()
Static Public Attributes
static int const holdLedgers = 5
Private Attributes
SerializedTransaction::pointer m_txn
LedgerIndex m_expire
uint256 m_id
RippleAddress m_account
std::uint32_t m_seq
Detailed Description
Definition at line 49 of file LocalTxs.cpp.
Constructor & Destructor Documentation
ripple::LocalTx::LocalTx (LedgerIndex index, SerializedTransaction::ref txn) inline
Definition at line 58 of file LocalTxs.cpp.
References m_expire, and ripple::min().
         : m_txn (txn)
         , m_expire (index + holdLedgers)
         , m_id (txn->getTransactionID ())
         , m_account (txn->getSourceAccount ())
         , m_seq (txn->getSequence())
     {
         if (txn->isFieldPresent (sfLastLedgerSequence))
         {
            LedgerIndex m_txnexpire = txn->getFieldU32 (sfLastLedgerSequence) + 1;
            m_expire = std::min (m_expire, m_txnexpire);
         }
     }
Member Function Documentation
RippleAddress const& ripple::LocalTx::getAccount () inline
Definition at line 92 of file LocalTxs.cpp.
References m_account.
Referenced by ripple::LocalTxsImp::can_remove().
     {
         return m_account;
     }
uint256 const& ripple::LocalTx::getID () inline
Definition at line 72 of file LocalTxs.cpp.
References m_id.
Referenced by ripple::LocalTxsImp::can_remove().
     {
         return m_id;
     }
std::uint32_t ripple::LocalTx::getSeq () inline
Definition at line 77 of file LocalTxs.cpp.
References m_seq.
Referenced by ripple::LocalTxsImp::can_remove().
     {
         return m_seq;
     }
SerializedTransaction::ref ripple::LocalTx::getTX () inline
Definition at line 87 of file LocalTxs.cpp.
References m_txn.
     {
         return m_txn;
     }
bool ripple::LocalTx::isExpired (LedgerIndex i) inline
Definition at line 82 of file LocalTxs.cpp.
References m_expire.
Referenced by ripple::LocalTxsImp::can_remove().
     {
         return i > m_expire;
     }
Member Data Documentation
int const ripple::LocalTx::holdLedgers = 5 static
Definition at line 56 of file LocalTxs.cpp.
RippleAddress ripple::LocalTx::m_account private
Definition at line 102 of file LocalTxs.cpp.
Referenced by getAccount().
LedgerIndex ripple::LocalTx::m_expire private
Definition at line 100 of file LocalTxs.cpp.
Referenced by isExpired(), and LocalTx().
uint256 ripple::LocalTx::m_id private
Definition at line 101 of file LocalTxs.cpp.
Referenced by getID().
std::uint32_t ripple::LocalTx::m_seq private
Definition at line 103 of file LocalTxs.cpp.
Referenced by getSeq().
SerializedTransaction::pointer ripple::LocalTx::m_txn private
Definition at line 99 of file LocalTxs.cpp.
Referenced by getTX().
The documentation for this class was generated from the following file:
rippled/src/ripple_app/tx/LocalTxs.cpp