rippled: ripple::SqliteStatement Class Reference
ripple::SqliteStatement Class Reference
#include <SqliteDatabase.h>
Public Member Functions
SqliteStatement (SqliteDatabase *db, const char *statement, bool aux=false)
SqliteStatement (SqliteDatabase *db, const std::string &statement, bool aux=false)
~SqliteStatement ()
sqlite3_stmt * peekStatement ()
int bind (int position, const void *data, int length)
int bindStatic (int position, const void *data, int length)
int bindStatic (int position, Blob const &value)
int bind (int position, const std::string &value)
int bindStatic (int position, const std::string &value)
int bind (int position, std::uint32_t value)
int bind (int position)
int size (int column)
const void * peekBlob (int column)
Blob getBlob (int column)
std::string getString (int column)
const char * peekString (int column)
std::uint32_t getUInt32 (int column)
std::int64_t getInt64 (int column)
int step ()
int reset ()
bool isOk (int)
bool isDone (int)
bool isRow (int)
bool isError (int)
std::string getError (int)
Protected Attributes
sqlite3_stmt * statement
Private Member Functions
SqliteStatement (const SqliteStatement &)
SqliteStatement & operator= (const SqliteStatement &)
Detailed Description
Definition at line 99 of file SqliteDatabase.h.
Constructor & Destructor Documentation
ripple::SqliteStatement::SqliteStatement (const SqliteStatement &) private
ripple::SqliteStatement::SqliteStatement (SqliteDatabase * db, const char * statement, bool aux = false)
Definition at line 24 of file SqliteDatabase.cpp.
References sqlite3_prepare_v2, and SQLITE_OK.
 {
     assert (db);
     sqlite3* conn = aux ? db->getAuxConnection () : db->peekConnection ();
     int j = sqlite3_prepare_v2 (conn, sql, strlen (sql) + 1, &statement, nullptr);
     if (j != SQLITE_OK)
         throw j;
 }
ripple::SqliteStatement::SqliteStatement (SqliteDatabase * db, const std::string & statement, bool aux = false)
Definition at line 35 of file SqliteDatabase.cpp.
References ripple::SqliteDatabase::getAuxConnection(), ripple::SqliteDatabase::peekConnection(), sqlite3_prepare_v2, SQLITE_OK, and statement.
 {
     assert (db);
     sqlite3* conn = aux ? db->getAuxConnection () : db->peekConnection ();
     int j = sqlite3_prepare_v2 (conn, sql.c_str (), sql.size () + 1, &statement, nullptr);
     if (j != SQLITE_OK)
         throw j;
 }
ripple::SqliteStatement::~SqliteStatement ()
Definition at line 46 of file SqliteDatabase.cpp.
References sqlite3_finalize, and statement.
 {
     sqlite3_finalize (statement);
 }
Member Function Documentation
int ripple::SqliteStatement::bind (int position, const void * data, int length)
Definition at line 370 of file SqliteDatabase.cpp.
References sqlite3_bind_blob, SQLITE_TRANSIENT, and statement.
Referenced by ripple::SqliteBackend::doBind(), ripple::SqliteBackend::fetch(), ripple::Ledger::getHashesByIndex(), ripple::Ledger::loadByHash(), and ripple::Ledger::loadByIndex().
 {
     return sqlite3_bind_blob (statement, position, data, length, SQLITE_TRANSIENT);
 }
int ripple::SqliteStatement::bind (int position, const std::string & value)
Definition at line 390 of file SqliteDatabase.cpp.
References sqlite3_bind_text, SQLITE_TRANSIENT, and statement.
 {
     return sqlite3_bind_text (statement, position, value.data (), value.size (), SQLITE_TRANSIENT);
 }
int ripple::SqliteStatement::bind (int position, std::uint32_t value)
Definition at line 385 of file SqliteDatabase.cpp.
References sqlite3_bind_int64, and statement.
 {
     return sqlite3_bind_int64 (statement, position, static_cast<sqlite3_int64> (value));
 }
int ripple::SqliteStatement::bind (int position)
Definition at line 400 of file SqliteDatabase.cpp.
References sqlite3_bind_null, and statement.
 {
     return sqlite3_bind_null (statement, position);
 }
int ripple::SqliteStatement::bindStatic (int position, const void * data, int length)
Definition at line 375 of file SqliteDatabase.cpp.
References sqlite3_bind_blob, SQLITE_STATIC, and statement.
Referenced by ripple::SqliteBackend::doBind().
 {
     return sqlite3_bind_blob (statement, position, data, length, SQLITE_STATIC);
 }
int ripple::SqliteStatement::bindStatic (int position, Blob const & value)
Definition at line 380 of file SqliteDatabase.cpp.
References sqlite3_bind_blob, SQLITE_STATIC, and statement.
 {
     return sqlite3_bind_blob (statement, position, &value.front (), value.size (), SQLITE_STATIC);
 }
int ripple::SqliteStatement::bindStatic (int position, const std::string & value)
Definition at line 395 of file SqliteDatabase.cpp.
References sqlite3_bind_text, SQLITE_STATIC, and statement.
 {
     return sqlite3_bind_text (statement, position, value.data (), value.size (), SQLITE_STATIC);
 }
Blob ripple::SqliteStatement::getBlob (int column)
Definition at line 415 of file SqliteDatabase.cpp.
References size(), sqlite3_column_blob, sqlite3_column_bytes, and statement.
 {
     int size = sqlite3_column_bytes (statement, column);
     Blob ret (size);
     memcpy (& (ret.front ()), sqlite3_column_blob (statement, column), size);
     return ret;
 }
std::string ripple::SqliteStatement::getError (int j)
Definition at line 482 of file SqliteDatabase.cpp.
References sqlite3_errstr.
Referenced by ripple::Ledger::getSQL1().
 {
     return sqlite3_errstr (j);
 }
std::int64_t ripple::SqliteStatement::getInt64 (int column)
Definition at line 438 of file SqliteDatabase.cpp.
References sqlite3_column_int64, and statement.
Referenced by ripple::Ledger::getSQL1().
 {
     return sqlite3_column_int64 (statement, column);
 }
std::string ripple::SqliteStatement::getString (int column)
Definition at line 423 of file SqliteDatabase.cpp.
References sqlite3_column_text, and statement.
 {
     return reinterpret_cast<const char*> (sqlite3_column_text (statement, column));
 }
std::uint32_t ripple::SqliteStatement::getUInt32 (int column)
Definition at line 433 of file SqliteDatabase.cpp.
References sqlite3_column_int64, and statement.
Referenced by ripple::Ledger::getSQL1().
 {
     return static_cast<std::uint32_t> (sqlite3_column_int64 (statement, column));
 }
bool ripple::SqliteStatement::isDone (int j)
Definition at line 458 of file SqliteDatabase.cpp.
References SQLITE_DONE.
Referenced by ripple::Ledger::getSQL1().
 {
     return j == SQLITE_DONE;
 }
bool ripple::SqliteStatement::isError (int j)
Definition at line 468 of file SqliteDatabase.cpp.
References SQLITE_DONE, SQLITE_OK, and SQLITE_ROW.
 {
     switch (j)
     {
     case SQLITE_OK:
     case SQLITE_ROW:
     case SQLITE_DONE:
         return false;
     default:
         return true;
     }
 }
bool ripple::SqliteStatement::isOk (int j)
Definition at line 453 of file SqliteDatabase.cpp.
References SQLITE_OK.
 {
     return j == SQLITE_OK;
 }
bool ripple::SqliteStatement::isRow (int j)
Definition at line 463 of file SqliteDatabase.cpp.
References SQLITE_ROW.
Referenced by ripple::Ledger::getSQL1().
 {
     return j == SQLITE_ROW;
 }
SqliteStatement& ripple::SqliteStatement::operator= (const SqliteStatement &) private
const void * ripple::SqliteStatement::peekBlob (int column)
Definition at line 410 of file SqliteDatabase.cpp.
References sqlite3_column_blob, and statement.
 {
     return sqlite3_column_blob (statement, column);
 }
sqlite3_stmt * ripple::SqliteStatement::peekStatement ()
Definition at line 365 of file SqliteDatabase.cpp.
References statement.
 {
     return statement;
 }
const char * ripple::SqliteStatement::peekString (int column)
Definition at line 428 of file SqliteDatabase.cpp.
References sqlite3_column_text, and statement.
Referenced by ripple::Ledger::getSQL1().
 {
     return reinterpret_cast<const char*> (sqlite3_column_text (statement, column));
 }
int ripple::SqliteStatement::reset ()
Definition at line 448 of file SqliteDatabase.cpp.
References sqlite3_reset, and statement.
 {
     return sqlite3_reset (statement);
 }
int ripple::SqliteStatement::size (int column)
Definition at line 405 of file SqliteDatabase.cpp.
References sqlite3_column_bytes, and statement.
Referenced by getBlob().
 {
     return sqlite3_column_bytes (statement, column);
 }
int ripple::SqliteStatement::step ()
Definition at line 443 of file SqliteDatabase.cpp.
References sqlite3_step, and statement.
Referenced by ripple::Ledger::getSQL1(), and ripple::SqliteBackend::storeBatch().
 {
     return sqlite3_step (statement);
 }
Member Data Documentation
sqlite3_stmt* ripple::SqliteStatement::statement protected
Definition at line 106 of file SqliteDatabase.h.
Referenced by bind(), bindStatic(), getBlob(), getInt64(), getString(), getUInt32(), peekBlob(), peekStatement(), peekString(), reset(), size(), SqliteStatement(), step(), and ~SqliteStatement().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/data/SqliteDatabase.h
rippled/src/ripple_app/data/SqliteDatabase.cpp