rippled: beast.util.Boost Namespace Reference
beast.util.Boost Namespace Reference
Functions
def _text
def _raw_boost_path
def _get_version_number
def _validate_version
def _boost_path
Variables
string ROOT_ENV_VARIABLE = 'BOOST_ROOT'
int MINIMUM_VERSION = 1
string VERSION_FILE = 'boost'
string LIBRARY_PATH_SEGMENT = 'stage'
tuple VERSION_MATCHER = re.compile(r'#define\s+BOOST_VERSION\s+(\d+)')
string CANT_OPEN_VERSION_FILE_ERROR
tuple CANT_UNDERSTAND_VERSION_ERROR
tuple VERSION_TOO_OLD_ERROR
tuple CPPPATH = _boost_path()
tuple LIBPATH = os.path.join(CPPPATH, *LIBRARY_PATH_SEGMENT)
Function Documentation
def beast.util.Boost._boost_path () private
Definition at line 55 of file Boost.py.
References beast.util.Boost._get_version_number(), beast.util.Boost._raw_boost_path(), and beast.util.Boost._validate_version().
 def _boost_path():
     path = _raw_boost_path()
     _validate_version(_get_version_number(path))
     return path
def beast.util.Boost._get_version_number (path) private
Definition at line 33 of file Boost.py.
Referenced by beast.util.Boost._boost_path().
 def _get_version_number(path):
     version_file = os.path.join(path, *VERSION_FILE)
     try:
         with open(version_file) as f:
             for line in f:
                 match = VERSION_MATCHER.match(line)
                 if match:
                     version = match.group(1)
                     try:
                         return int(version)
                     except ValueError:
                         raise Exception(CANT_UNDERSTAND_VERSION_ERROR %
                                         (version, version_file))
     except IOError:
         raise Exception(CANT_OPEN_VERSION_FILE_ERROR % (version_file, path))
def beast.util.Boost._raw_boost_path () private
Definition at line 24 of file Boost.py.
Referenced by beast.util.Boost._boost_path().
 def _raw_boost_path():
     try:
       path = os.environ[ROOT_ENV_VARIABLE]
       if path:
         return os.path.normpath(path)
     except KeyError:
         pass
     raise KeyError('%s environment variable is not set.' % ROOT_ENV_VARIABLE)
def beast.util.Boost._text (major, minor, release) private
Definition at line 21 of file Boost.py.
Referenced by beast.util.Boost._validate_version().
 def _text(major, minor, release):
     return '%d.%02d.%02d' % (major, minor, release)
def beast.util.Boost._validate_version (v) private
Definition at line 49 of file Boost.py.
References beast.util.Boost._text().
Referenced by beast.util.Boost._boost_path().
 def _validate_version(v):
     version = v // 100000, (v // 100) % 100, v % 100
     if version < MINIMUM_VERSION:
         raise Exception(VERSION_TOO_OLD_ERROR % (
     _text(*version), _text(*MINIMUM_VERSION)))
Variable Documentation
string beast.util.Boost.CANT_OPEN_VERSION_FILE_ERROR
Initial value:
 = """Unable to open boost version file %s.
 You have set the environment variable BOOST_ROOT to be %s.
 Please check to make sure that this points to a valid installation of boost."""
Definition at line 12 of file Boost.py.
tuple beast.util.Boost.CANT_UNDERSTAND_VERSION_ERROR
Initial value:
 = (
     "Didn't understand version string '%s' from file %s'")
Definition at line 16 of file Boost.py.
tuple beast.util.Boost.CPPPATH = _boost_path()
Definition at line 60 of file Boost.py.
tuple beast.util.Boost.LIBPATH = os.path.join(CPPPATH, *LIBRARY_PATH_SEGMENT)
Definition at line 61 of file Boost.py.
string beast.util.Boost.LIBRARY_PATH_SEGMENT = 'stage'
Definition at line 9 of file Boost.py.
int beast.util.Boost.MINIMUM_VERSION = 1
Definition at line 7 of file Boost.py.
string beast.util.Boost.ROOT_ENV_VARIABLE = 'BOOST_ROOT'
Definition at line 6 of file Boost.py.
string beast.util.Boost.VERSION_FILE = 'boost'
Definition at line 8 of file Boost.py.
tuple beast.util.Boost.VERSION_MATCHER = re.compile(r'#define\s+BOOST_VERSION\s+(\d+)')
Definition at line 10 of file Boost.py.
tuple beast.util.Boost.VERSION_TOO_OLD_ERROR
Initial value:
 = ('Your version of boost, %s, is older than the minimum '
                          'required, %s.')
Definition at line 18 of file Boost.py.