rippled: ripple::RPCCallImp Struct Reference
ripple::RPCCallImp Struct Reference
Static Public Member Functions
static void callRPCHandler (Json::Value *jvOutput, const Json::Value &jvInput)
static bool onResponse (std::function< void(const Json::Value &jvInput)> callbackFuncP, const boost::system::error_code &ecResult, int iStatus, const std::string &strData)
static void onRequest (const std::string &strMethod, const Json::Value &jvParams, const std::map< std::string, std::string > &mHeaders, const std::string &strPath, boost::asio::streambuf &sb, const std::string &strHost)
Detailed Description
Definition at line 888 of file RPCCall.cpp.
Member Function Documentation
static void ripple::RPCCallImp::callRPCHandler (Json::Value * jvOutput, const Json::Value & jvInput) inline static
Definition at line 892 of file RPCCall.cpp.
Referenced by ripple::RPCCall::fromCommandLine().
     {
         (*jvOutput) = jvInput;
     }
static void ripple::RPCCallImp::onRequest (const std::string & strMethod, const Json::Value & jvParams, const std::map< std::string, std::string > & mHeaders, const std::string & strPath, boost::asio::streambuf & sb, const std::string & strHost) inline static
Definition at line 937 of file RPCCall.cpp.
References ripple::createHTTPPost(), ripple::JSONRPCRequest(), ripple::lsDEBUG, and WriteLog.
Referenced by ripple::RPCCall::fromNetwork().
     {
         WriteLog (lsDEBUG, RPCParser) << "requestRPC: strPath='" << strPath << "'";
         std::ostream    osRequest (&sb);
         osRequest <<
                   createHTTPPost (
                       strHost,
                       strPath,
                       JSONRPCRequest (strMethod, jvParams, Json::Value (1)),
                       mHeaders);
     }
static bool ripple::RPCCallImp::onResponse (std::function< void(const Json::Value &jvInput)> callbackFuncP, const boost::system::error_code & ecResult, int iStatus, const std::string & strData) inline static
Definition at line 897 of file RPCCall.cpp.
References Json::Value::isNull(), ripple::lsDEBUG, Json::objectValue, Json::Reader::parse(), ripple::strprintf(), and WriteLog.
Referenced by ripple::RPCCall::fromNetwork().
     {
         if (callbackFuncP)
         {
             // Only care about the result, if we care to deliver it callbackFuncP.
             // Receive reply
             if (iStatus == 401)
                 throw std::runtime_error ("incorrect rpcuser or rpcpassword (authorization failed)");
             else if ((iStatus >= 400) && (iStatus != 400) && (iStatus != 404) && (iStatus != 500)) // ?
                 throw std::runtime_error (strprintf ("server returned HTTP error %d", iStatus));
             else if (strData.empty ())
                 throw std::runtime_error ("no response from server");
             // Parse reply
             WriteLog (lsDEBUG, RPCParser) << "RPC reply: " << strData << std::endl;
             Json::Reader    reader;
             Json::Value     jvReply;
             if (!reader.parse (strData, jvReply))
                 throw std::runtime_error ("couldn't parse reply from server");
             if (jvReply.isNull ())
                 throw std::runtime_error ("expected reply to have result, error and id properties");
             Json::Value     jvResult (Json::objectValue);
             jvResult["result"] = jvReply;
             (callbackFuncP) (jvResult);
         }
         return false;
     }
The documentation for this struct was generated from the following file:
rippled/src/ripple_net/rpc/RPCCall.cpp