rippled: rocksdb::CorruptionTest Class Reference
rocksdb::CorruptionTest Class Reference
Public Member Functions
CorruptionTest ()
~CorruptionTest ()
Status TryReopen (Options *options=nullptr)
void Reopen (Options *options=nullptr)
void RepairDB ()
void Build (int n)
void Check (int min_expected, int max_expected)
void Corrupt (FileType filetype, int offset, int bytes_to_corrupt)
int Property (const std::string &name)
Slice Key (int i, std::string *storage)
Slice Value (int k, std::string *storage)
Public Attributes
test::ErrorEnv env_
std::string dbname_
shared_ptr< Cache > tiny_cache_
Options options_
DB * db_
Detailed Description
Definition at line 32 of file corruption_test.cc.
Constructor & Destructor Documentation
rocksdb::CorruptionTest::CorruptionTest () inline
Definition at line 40 of file corruption_test.cc.
References rocksdb::Options::block_size_deviation, rocksdb::Options::create_if_missing, db_, dbname_, rocksdb::DestroyDB(), rocksdb::Options::env, env_, rocksdb::NewLRUCache(), options_, Reopen(), tiny_cache_, and rocksdb::test::TmpDir().
                    {
     tiny_cache_ = NewLRUCache(100);
     options_.env = &env_;
     dbname_ = test::TmpDir() + "/db_test";
     DestroyDB(dbname_, options_);
     db_ = nullptr;
     options_.create_if_missing = true;
     options_.block_size_deviation = 0; // make unit test pass for now
     Reopen();
     options_.create_if_missing = false;
   }
rocksdb::CorruptionTest::~CorruptionTest () inline
Definition at line 53 of file corruption_test.cc.
References db_, dbname_, and rocksdb::DestroyDB().
                     {
      delete db_;
      DestroyDB(dbname_, Options());
   }
Member Function Documentation
void rocksdb::CorruptionTest::Build (int n) inline
Definition at line 79 of file corruption_test.cc.
References ASSERT_OK, rocksdb::WriteBatch::Clear(), db_, Key(), rocksdb::WriteBatch::Put(), Value(), and rocksdb::DB::Write().
                     {
     std::string key_space, value_space;
     WriteBatch batch;
     for (int i = 0; i < n; i++) {
       //if ((i % 100) == 0) fprintf(stderr, "@ %d of %d\n", i, n);
       Slice key = Key(i, &key_space);
       batch.Clear();
       batch.Put(key, Value(i, &value_space));
       ASSERT_OK(db_->Write(WriteOptions(), &batch));
     }
   }
void rocksdb::CorruptionTest::Check (int min_expected, int max_expected) inline
Definition at line 91 of file corruption_test.cc.
References ASSERT_GE, ASSERT_LE, rocksdb::ConsumeDecimalNumber(), db_, Json::in(), rocksdb::Iterator::key(), rocksdb::DB::NewIterator(), rocksdb::Iterator::Next(), rocksdb::Iterator::SeekToFirst(), rocksdb::Iterator::Valid(), rocksdb::Iterator::value(), and Value().
{
     unsigned int next_expected = 0;
     int missed = 0;
     int bad_keys = 0;
     int bad_values = 0;
     int correct = 0;
     std::string value_space;
     Iterator* iter = db_->NewIterator(ReadOptions());
     for (iter->SeekToFirst(); iter->Valid(); iter->Next()) {
       uint64_t key;
       Slice in(iter->key());
       if (!ConsumeDecimalNumber(&in, &key) ||
           !in.empty() ||
           key < next_expected) {
         bad_keys++;
         continue;
       }
       missed += (key - next_expected);
       next_expected = key + 1;
       if (iter->value() != Value(key, &value_space)) {
         bad_values++;
       } else {
         correct++;
       }
     }
     delete iter;
     fprintf(stderr,
             "expected=%d..%d; got=%d; bad_keys=%d; bad_values=%d; missed=%d\n",
             min_expected, max_expected, correct, bad_keys, bad_values, missed);
     ASSERT_LE(min_expected, correct);
     ASSERT_GE(max_expected, correct);
   }
void rocksdb::CorruptionTest::Corrupt (FileType filetype, int offset, int bytes_to_corrupt) inline
Definition at line 125 of file corruption_test.cc.
References ASSERT_OK, ASSERT_TRUE, dbname_, rocksdb::Env::Default(), env_, rocksdb::EnvWrapper::GetChildren(), rocksdb::Status::ok(), rocksdb::ParseFileName(), rocksdb::ReadFileToString(), rocksdb::Status::ToString(), and rocksdb::WriteStringToFile().
{
     // Pick file to corrupt
     std::vector<std::string> filenames;
     ASSERT_OK(env_.GetChildren(dbname_, &filenames));
     uint64_t number;
     FileType type;
     std::string fname;
     int picked_number = -1;
     for (unsigned int i = 0; i < filenames.size(); i++) {
       if (ParseFileName(filenames[i], &number, &type) &&
           type == filetype &&
           int(number) > picked_number) {  // Pick latest file
         fname = dbname_ + "/" + filenames[i];
         picked_number = number;
       }
     }
     ASSERT_TRUE(!fname.empty()) << filetype;
     struct stat sbuf;
     if (stat(fname.c_str(), &sbuf) != 0) {
       const char* msg = strerror(errno);
       ASSERT_TRUE(false) << fname << ": " << msg;
     }
     if (offset < 0) {
       // Relative to end of file; make it absolute
       if (-offset > sbuf.st_size) {
         offset = 0;
       } else {
         offset = sbuf.st_size + offset;
       }
     }
     if (offset > sbuf.st_size) {
       offset = sbuf.st_size;
     }
     if (offset + bytes_to_corrupt > sbuf.st_size) {
       bytes_to_corrupt = sbuf.st_size - offset;
     }
     // Do it
     std::string contents;
     Status s = ReadFileToString(Env::Default(), fname, &contents);
     ASSERT_TRUE(s.ok()) << s.ToString();
     for (int i = 0; i < bytes_to_corrupt; i++) {
       contents[i + offset] ^= 0x80;
     }
     s = WriteStringToFile(Env::Default(), contents, fname);
     ASSERT_TRUE(s.ok()) << s.ToString();
   }
Slice rocksdb::CorruptionTest::Key (int i, std::string * storage) inline
Definition at line 187 of file corruption_test.cc.
Referenced by Build().
{
     char buf[100];
     snprintf(buf, sizeof(buf), "%016d", i);
     storage->assign(buf, strlen(buf));
     return Slice(*storage);
   }
int rocksdb::CorruptionTest::Property (const std::string & name) inline
Definition at line 175 of file corruption_test.cc.
References db_, and rocksdb::DB::GetProperty().
{
     std::string property;
     int result;
     if (db_->GetProperty(name, &property) &&
         sscanf(property.c_str(), "%d", &result) == 1) {
       return result;
     } else {
       return -1;
     }
   }
void rocksdb::CorruptionTest::Reopen (Options * options = nullptr) inline
Definition at line 69 of file corruption_test.cc.
References ASSERT_OK, and TryReopen().
Referenced by CorruptionTest().
{
     ASSERT_OK(TryReopen(options));
   }
void rocksdb::CorruptionTest::RepairDB () inline
Definition at line 73 of file corruption_test.cc.
References ASSERT_OK, db_, dbname_, options_, and rocksdb::RepairDB().
                   {
     delete db_;
     db_ = nullptr;
     ASSERT_OK(::rocksdb::RepairDB(dbname_, options_));
   }
Status rocksdb::CorruptionTest::TryReopen (Options * options = nullptr) inline
Definition at line 58 of file corruption_test.cc.
References rocksdb::Options::arena_block_size, rocksdb::Options::block_cache, rocksdb::Options::block_size_deviation, db_, dbname_, rocksdb::Options::env, env_, rocksdb::DB::Open(), options_, and tiny_cache_.
Referenced by Reopen().
{
     delete db_;
     db_ = nullptr;
     Options opt = (options ? *options : options_);
     opt.env = &env_;
     opt.block_cache = tiny_cache_;
     opt.block_size_deviation = 0;
     opt.arena_block_size = 4096;
     return DB::Open(opt, dbname_, &db_);
   }
Slice rocksdb::CorruptionTest::Value (int k, std::string * storage) inline
Definition at line 195 of file corruption_test.cc.
References rocksdb::kValueSize, and rocksdb::test::RandomString().
Referenced by Build(), and Check().
{
     Random r(k);
     return test::RandomString(&r, kValueSize, storage);
   }
Member Data Documentation
DB* rocksdb::CorruptionTest::db_
Definition at line 38 of file corruption_test.cc.
Referenced by Build(), Check(), CorruptionTest(), Property(), RepairDB(), TryReopen(), and ~CorruptionTest().
std::string rocksdb::CorruptionTest::dbname_
Definition at line 35 of file corruption_test.cc.
Referenced by Corrupt(), CorruptionTest(), RepairDB(), TryReopen(), and ~CorruptionTest().
test::ErrorEnv rocksdb::CorruptionTest::env_
Definition at line 34 of file corruption_test.cc.
Referenced by Corrupt(), CorruptionTest(), and TryReopen().
Options rocksdb::CorruptionTest::options_
Definition at line 37 of file corruption_test.cc.
Referenced by CorruptionTest(), RepairDB(), and TryReopen().
shared_ptr<Cache> rocksdb::CorruptionTest::tiny_cache_
Definition at line 36 of file corruption_test.cc.
Referenced by CorruptionTest(), and TryReopen().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/db/corruption_test.cc