rippled: rocksdb::StopWatchNano Class Reference
rocksdb::StopWatchNano Class Reference
#include <stop_watch.h>
Public Member Functions
StopWatchNano (Env *const env, bool auto_start=false)
void Start ()
uint64_t ElapsedNanos (bool reset=false)
Private Attributes
Env *const env_
uint64_t start_
Detailed Description
Definition at line 45 of file stop_watch.h.
Constructor & Destructor Documentation
rocksdb::StopWatchNano::StopWatchNano (Env *const env, bool auto_start = false) inline
Definition at line 47 of file stop_watch.h.
References Start().
       : env_(env), start_(0) {
     if (auto_start) {
       Start();
     }
   }
Member Function Documentation
uint64_t rocksdb::StopWatchNano::ElapsedNanos (bool reset = false) inline
Definition at line 56 of file stop_watch.h.
References env_, rocksdb::Env::NowNanos(), and start_.
Referenced by rocksdb::BumpPerfTime(), and rocksdb::TEST().
{
     auto now = env_->NowNanos();
     auto elapsed = now - start_;
     if (reset) {
       start_ = now;
     }
     return elapsed;
   }
void rocksdb::StopWatchNano::Start () inline
Definition at line 54 of file stop_watch.h.
References env_, rocksdb::Env::NowNanos(), and start_.
Referenced by rocksdb::StartPerfTimer(), StopWatchNano(), and rocksdb::TEST().
 { start_ = env_->NowNanos(); }
Member Data Documentation
Env* const rocksdb::StopWatchNano::env_ private
Definition at line 66 of file stop_watch.h.
Referenced by ElapsedNanos(), and Start().
uint64_t rocksdb::StopWatchNano::start_ private
Definition at line 67 of file stop_watch.h.
Referenced by ElapsedNanos(), and Start().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/util/stop_watch.h