rippled: ripple::PeerFinder::SlotImp Class Reference
ripple::PeerFinder::SlotImp Class Reference
#include <SlotImp.h>
Classes
class recent_t
Public Types
typedef std::shared_ptr< SlotImp > ptr
Public Types inherited from ripple::PeerFinder::Slot
enum State {
accept, connect, connected, active,
closing
}
typedef std::shared_ptr< Slot > ptr
Public Member Functions
SlotImp (beast::IP::Endpoint const &local_endpoint, beast::IP::Endpoint const &remote_endpoint, bool fixed, clock_type &clock)
SlotImp (beast::IP::Endpoint const &remote_endpoint, bool fixed, clock_type &clock)
bool inbound () const
bool fixed () const
bool cluster () const
State state () const
beast::IP::Endpoint const & remote_endpoint () const
boost::optional
< beast::IP::Endpoint > const & local_endpoint () const
boost::optional
< RipplePublicKey > const & public_key () const
void local_endpoint (beast::IP::Endpoint const &endpoint)
void remote_endpoint (beast::IP::Endpoint const &endpoint)
void public_key (RipplePublicKey const &key)
void cluster (bool cluster_)
void state (State state_)
void activate (clock_type::time_point const &now)
void expire ()
Public Member Functions inherited from ripple::PeerFinder::Slot
virtual ~Slot ()=0
Public Attributes
class
ripple::PeerFinder::SlotImp::recent_t recent
bool checked
bool canAccept
bool connectivityCheckInProgress
clock_type::time_point whenAcceptEndpoints
Private Types
typedef
beast::aged_unordered_map
< beast::IP::Endpoint, int > recent_type
Private Attributes
bool const m_inbound
bool const m_fixed
bool m_cluster
State m_state
beast::IP::Endpoint m_remote_endpoint
boost::optional
< beast::IP::Endpoint > m_local_endpoint
boost::optional< RipplePublicKey > m_public_key
Detailed Description
Definition at line 33 of file SlotImp.h.
Member Typedef Documentation
typedef std::shared_ptr<SlotImp> ripple::PeerFinder::SlotImp::ptr
Definition at line 39 of file SlotImp.h.
typedef beast::aged_unordered_map<beast::IP::Endpoint, int> ripple::PeerFinder::SlotImp::recent_type private
Definition at line 36 of file SlotImp.h.
Constructor & Destructor Documentation
ripple::PeerFinder::SlotImp::SlotImp (beast::IP::Endpoint const & local_endpoint, beast::IP::Endpoint const & remote_endpoint, bool fixed, clock_type & clock)
Definition at line 25 of file SlotImp.cpp.
     : recent (clock)
     , m_inbound (true)
     , m_fixed (fixed)
     , m_cluster (false)
     , m_state (accept)
     , m_remote_endpoint (remote_endpoint)
     , m_local_endpoint (local_endpoint)
     , checked (false)
     , canAccept (false)
     , connectivityCheckInProgress (false)
 {
 }
ripple::PeerFinder::SlotImp::SlotImp (beast::IP::Endpoint const & remote_endpoint, bool fixed, clock_type & clock)
Definition at line 41 of file SlotImp.cpp.
     : recent (clock)
     , m_inbound (false)
     , m_fixed (fixed)
     , m_cluster (false)
     , m_state (connect)
     , m_remote_endpoint (remote_endpoint)
     , checked (true)
     , canAccept (true)
     , connectivityCheckInProgress (false)
 {
 }
Member Function Documentation
void ripple::PeerFinder::SlotImp::activate (clock_type::time_point const & now)
Definition at line 77 of file SlotImp.cpp.
References ripple::PeerFinder::Slot::accept, ripple::PeerFinder::Slot::active, ripple::PeerFinder::Slot::connected, m_state, and whenAcceptEndpoints.
 {
     // Can only become active from the accept or connected state
     assert (m_state == accept || m_state == connected);
     m_state = active;
     whenAcceptEndpoints = now;
 }
bool ripple::PeerFinder::SlotImp::cluster () const inline virtual
Returns true if this is a cluster connection. This is only known after then handshake completes.
Implements ripple::PeerFinder::Slot.
Definition at line 60 of file SlotImp.h.
References m_cluster.
Referenced by ripple::PeerFinder::Logic::writeSlots().
     {
         return m_cluster;
     }
void ripple::PeerFinder::SlotImp::cluster (bool cluster_) inline
Definition at line 100 of file SlotImp.h.
References m_cluster.
     {
         m_cluster = cluster_;
     }
void ripple::PeerFinder::SlotImp::expire () inline
Definition at line 137 of file SlotImp.h.
References ripple::PeerFinder::SlotImp::recent_t::expire(), and recent.
     {
         recent.expire();
     }
bool ripple::PeerFinder::SlotImp::fixed () const inline virtual
Returns true if this is a fixed connection. A connection is fixed if its remote endpoint is in the list of remote endpoints for fixed connections.
Implements ripple::PeerFinder::Slot.
Definition at line 55 of file SlotImp.h.
References m_fixed.
Referenced by ripple::PeerFinder::Logic::writeSlots().
     {
         return m_fixed;
     }
bool ripple::PeerFinder::SlotImp::inbound () const inline virtual
Returns true if this is an inbound connection.
Implements ripple::PeerFinder::Slot.
Definition at line 50 of file SlotImp.h.
References m_inbound.
Referenced by ripple::PeerFinder::Logic::writeSlots().
     {
         return m_inbound;
     }
boost::optional<beast::IP::Endpoint> const& ripple::PeerFinder::SlotImp::local_endpoint () const inline virtual
The local endpoint of the socket, when known.
Implements ripple::PeerFinder::Slot.
Definition at line 75 of file SlotImp.h.
References m_local_endpoint.
Referenced by ripple::PeerFinder::Logic::writeSlots().
     {
         return m_local_endpoint;
     }
void ripple::PeerFinder::SlotImp::local_endpoint (beast::IP::Endpoint const & endpoint) inline
Definition at line 85 of file SlotImp.h.
References m_local_endpoint.
     {
         m_local_endpoint = endpoint;
     }
boost::optional<RipplePublicKey> const& ripple::PeerFinder::SlotImp::public_key () const inline virtual
The peer's public key, when known. The public key is established when the handshake is complete.
Implements ripple::PeerFinder::Slot.
Definition at line 80 of file SlotImp.h.
References m_public_key.
     {
         return m_public_key;
     }
void ripple::PeerFinder::SlotImp::public_key (RipplePublicKey const & key) inline
Definition at line 95 of file SlotImp.h.
References m_public_key.
     {
         m_public_key = key;
     }
beast::IP::Endpoint const& ripple::PeerFinder::SlotImp::remote_endpoint () const inline virtual
The remote endpoint of socket.
Implements ripple::PeerFinder::Slot.
Definition at line 70 of file SlotImp.h.
References m_remote_endpoint.
Referenced by ripple::PeerFinder::Logic::writeSlots().
     {
         return m_remote_endpoint;
     }
void ripple::PeerFinder::SlotImp::remote_endpoint (beast::IP::Endpoint const & endpoint) inline
Definition at line 90 of file SlotImp.h.
References m_remote_endpoint.
     {
         m_remote_endpoint = endpoint;
     }
State ripple::PeerFinder::SlotImp::state () const inline virtual
Returns the state of the connection.
Implements ripple::PeerFinder::Slot.
Definition at line 65 of file SlotImp.h.
References m_state.
Referenced by ripple::PeerFinder::Logic::writeSlots().
     {
         return m_state;
     }
void ripple::PeerFinder::SlotImp::state (State state_)
Definition at line 56 of file SlotImp.cpp.
References ripple::PeerFinder::Slot::accept, ripple::PeerFinder::Slot::active, ripple::PeerFinder::Slot::closing, ripple::PeerFinder::Slot::connect, ripple::PeerFinder::Slot::connected, m_inbound, and m_state.
 {
     // Must go through activate() to set active state
     assert (state_ != active);
     // The state must be different
     assert (state_ != m_state);
     // You can't transition into the initial states
     assert (state_ != accept && state_ != connect);
     // Can only become connected from outbound connect state
     assert (state_ != connected || (! m_inbound && m_state == connect));
     // Can't gracefully close on an outbound connection attempt
     assert (state_ != closing || m_state != connect);
     m_state = state_;
 }
Member Data Documentation
bool ripple::PeerFinder::SlotImp::canAccept
Definition at line 160 of file SlotImp.h.
bool ripple::PeerFinder::SlotImp::checked
Definition at line 156 of file SlotImp.h.
bool ripple::PeerFinder::SlotImp::connectivityCheckInProgress
Definition at line 164 of file SlotImp.h.
bool ripple::PeerFinder::SlotImp::m_cluster private
Definition at line 145 of file SlotImp.h.
Referenced by cluster().
bool const ripple::PeerFinder::SlotImp::m_fixed private
Definition at line 144 of file SlotImp.h.
Referenced by fixed().
bool const ripple::PeerFinder::SlotImp::m_inbound private
Definition at line 143 of file SlotImp.h.
Referenced by inbound(), and state().
boost::optional<beast::IP::Endpoint> ripple::PeerFinder::SlotImp::m_local_endpoint private
Definition at line 148 of file SlotImp.h.
Referenced by local_endpoint().
boost::optional<RipplePublicKey> ripple::PeerFinder::SlotImp::m_public_key private
Definition at line 149 of file SlotImp.h.
Referenced by public_key().
beast::IP::Endpoint ripple::PeerFinder::SlotImp::m_remote_endpoint private
Definition at line 147 of file SlotImp.h.
Referenced by remote_endpoint().
State ripple::PeerFinder::SlotImp::m_state private
Definition at line 146 of file SlotImp.h.
Referenced by activate(), and state().
class ripple::PeerFinder::SlotImp::recent_t ripple::PeerFinder::SlotImp::recent
Referenced by expire().
clock_type::time_point ripple::PeerFinder::SlotImp::whenAcceptEndpoints
Definition at line 170 of file SlotImp.h.
Referenced by activate().
The documentation for this class was generated from the following files:
rippled/src/ripple/peerfinder/impl/SlotImp.h
rippled/src/ripple/peerfinder/impl/SlotImp.cpp