rippled: Json Namespace Reference
Json Namespace Reference
JSON (JavaScript Object Notation).
Classes
class Features
Configuration passed to reader and writer. This configuration object can be used to force the Reader or Writer to behave in a standard conforming way.
class Reader
Unserialize a JSON document into a Value.
class StaticString
Lightweight wrapper to tag static string.
class Value
Represents a JSON value.
class PathArgument
Experimental and untested: represents an element of the "path" to access a node.
class Path
Experimental and untested: represents a "path" to access a node.
class ValueAllocator
Experimental do not use: Allocator to customize member name and string value memory management done by Value.
class ValueIteratorBase
base class for Value iterators.
class ValueConstIterator
const iterator for object and array value.
class ValueIterator
Iterator for object and array value.
class Writer
Abstract class for writers.
class FastWriter
Outputs a Value in JSON format without formatting (not human friendly).
class StyledWriter
Writes a Value in JSON format in a human friendly way.
class StyledStreamWriter
Writes a Value in JSON format in a human friendly way, to a stream rather than to a string.
class BatchAllocator
class DefaultValueAllocator
struct DummyValueAllocatorInitializer
Typedefs
typedef int Int
typedef unsigned int UInt
Enumerations
enum ValueType {
nullValue = 0, intValue, uintValue, realValue,
stringValue, booleanValue, arrayValue, objectValue
}
Type of the value held by a Value object.
enum CommentPlacement { commentBefore = 0, commentAfterOnSameLine, commentAfter, numberOfCommentPlacement }
Functions
std::istream & operator>> (std::istream &, Value &)
Read from 'sin' into 'root'.
std::string JSON_API valueToString (Int value)
std::string JSON_API valueToString (UInt value)
std::string JSON_API valueToString (double value)
std::string JSON_API valueToString (bool value)
std::string JSON_API valueToQuotedString (const char *value)
std::ostream & operator<< (std::ostream &, const Value &root)
Output using the StyledStreamWriter.
static bool in (Reader::Char c, Reader::Char c1, Reader::Char c2, Reader::Char c3, Reader::Char c4)
static bool in (Reader::Char c, Reader::Char c1, Reader::Char c2, Reader::Char c3, Reader::Char c4, Reader::Char c5)
static bool containsNewLine (Reader::Location begin, Reader::Location end)
static std::string codePointToUTF8 (unsigned int cp)
static ValueAllocator *& valueAllocator ()
static bool isControlCharacter (char ch)
static bool containsControlCharacter (const char *str)
static void uintToString (unsigned int value, char *&current)
Variables
static struct
Json::DummyValueAllocatorInitializer dummyValueAllocatorInitializer
Detailed Description
JSON (JavaScript Object Notation).
Typedef Documentation
typedef int Json::Int
Definition at line 34 of file json_forwards.h.
typedef unsigned int Json::UInt
Definition at line 38 of file json_forwards.h.
Enumeration Type Documentation
enum Json::CommentPlacement
Enumerator
commentBefore
a comment placed on the line before a value
commentAfterOnSameLine
a comment just after a value on the same line
commentAfter
a comment on the line after a value (only make sense for root value)
numberOfCommentPlacement
Definition at line 42 of file json_value.h.
 {
     commentBefore = 0,
     commentAfterOnSameLine,
     commentAfter,
     numberOfCommentPlacement
 };
enum Json::ValueType
Type of the value held by a Value object.
Enumerator
nullValue
'null' value
intValue
signed integer value
uintValue
unsigned integer value
realValue
double value
stringValue
UTF-8 string value.
booleanValue
bool value
arrayValue
array value (ordered list)
objectValue
object value (collection of name/value pairs).
Definition at line 30 of file json_value.h.
 {
     nullValue = 0,
     intValue,
     uintValue,
     realValue,
     stringValue,
     booleanValue,
     arrayValue,
     objectValue
 };
Function Documentation
static std::string Json::codePointToUTF8 (unsigned int cp) static
Definition at line 77 of file json_reader.cpp.
Referenced by Json::Reader::decodeString().
 {
     std::string result;
     // based on description from http://en.wikipedia.org/wiki/UTF-8
     if (cp <= 0x7f)
     {
         result.resize (1);
         result[0] = static_cast<char> (cp);
     }
     else if (cp <= 0x7FF)
     {
         result.resize (2);
         result[1] = static_cast<char> (0x80 | (0x3f & cp));
         result[0] = static_cast<char> (0xC0 | (0x1f & (cp >> 6)));
     }
     else if (cp <= 0xFFFF)
     {
         result.resize (3);
         result[2] = static_cast<char> (0x80 | (0x3f & cp));
         result[1] = 0x80 | static_cast<char> ((0x3f & (cp >> 6)));
         result[0] = 0xE0 | static_cast<char> ((0xf & (cp >> 12)));
     }
     else if (cp <= 0x10FFFF)
     {
         result.resize (4);
         result[3] = static_cast<char> (0x80 | (0x3f & cp));
         result[2] = static_cast<char> (0x80 | (0x3f & (cp >> 6)));
         result[1] = static_cast<char> (0x80 | (0x3f & (cp >> 12)));
         result[0] = static_cast<char> (0xF0 | (0x7 & (cp >> 18)));
     }
     return result;
 }
static bool Json::containsControlCharacter (const char * str) static
Definition at line 28 of file json_writer.cpp.
References isControlCharacter().
Referenced by valueToQuotedString().
 {
     while ( *str )
     {
         if ( isControlCharacter ( * (str++) ) )
             return true;
     }
     return false;
 }
static bool Json::containsNewLine (Reader::Location begin, Reader::Location end) static
Definition at line 67 of file json_reader.cpp.
Referenced by Json::Reader::readComment().
 {
     for ( ; begin < end; ++begin )
         if ( *begin == '\n'  ||  *begin == '\r' )
             return true;
     return false;
 }
static bool Json::in (Reader::Char c, Reader::Char c1, Reader::Char c2, Reader::Char c3, Reader::Char c4) inline static
Definition at line 54 of file json_reader.cpp.
Referenced by beast::asio::HandshakeDetectLogicSSL3::analyze(), beast::asio::HandshakeDetectLogicSSL2::analyze(), beast::asio::HandshakeDetectLogicPROXY::analyze(), rocksdb::BZip2CompressionSupported(), rocksdb::CorruptionTest::Check(), beast::File::copyInternal(), Json::Reader::decodeNumber(), beast::sqdb::type_conversion< T >::from_base(), beast::asio::InputParser::Match< T >::func(), rocksdb::DBImpl::GetProperty(), ripple::Config::load(), beast::File::loadFileAsData(), beast::File::loadFileAsString(), beast::asio::InputParser::match(), ripple::UniqueNodeListImp::nodeLoad(), beast::operator<<(), Json::Path::Path(), beast::asio::InputParser::peek(), ripple::RandomNumbers::platformAddEntropy(), beast::asio::InputParser::read(), Json::Reader::readNumber(), rocksdb::SnappyCompressionSupported(), rocksdb::TestKey(), beast::sqdb::type_conversion< T >::to_base(), and rocksdb::ZlibCompressionSupported().
 {
     return c == c1  ||  c == c2  ||  c == c3  ||  c == c4;
 }
static bool Json::in (Reader::Char c, Reader::Char c1, Reader::Char c2, Reader::Char c3, Reader::Char c4, Reader::Char c5) inline static
Definition at line 60 of file json_reader.cpp.
 {
     return c == c1  ||  c == c2  ||  c == c3  ||  c == c4  ||  c == c5;
 }
static bool Json::isControlCharacter (char ch) static
Definition at line 23 of file json_writer.cpp.
Referenced by containsControlCharacter(), and valueToQuotedString().
 {
     return ch > 0 && ch <= 0x1F;
 }
std::ostream & Json::operator<< (std::ostream & sout, const Value & root)
Output using the StyledStreamWriter.
See Also
Json::operator>>()
Definition at line 902 of file json_writer.cpp.
References Json::StyledStreamWriter::write().
 {
     Json::StyledStreamWriter writer;
     writer.write (sout, root);
     return sout;
 }
std::istream & Json::operator>> (std::istream & sin, Value & root)
Read from 'sin' into 'root'.
Always keep comments from the input JSON.
This can be used to read a file into a particular sub-object. For example:
Json::Value root;
cin >> root["dir"]["file"];
cout << root;
Result:
 {
"dir": {
    "file": {
 // The input stream JSON would be nested here.
    }
}
 }
Exceptions
std::exception on parse error.
See Also
Json::operator<<()
Definition at line 1031 of file json_reader.cpp.
References Json::Reader::getFormatedErrorMessages(), ripple::Resource::ok, and Json::Reader::parse().
 {
     Json::Reader reader;
     bool ok = reader.parse (sin, root, true);
     //JSON_ASSERT( ok );
     if (!ok) throw std::runtime_error (reader.getFormatedErrorMessages ());
     return sin;
 }
static void Json::uintToString (unsigned int value, char *& current) static
Definition at line 38 of file json_writer.cpp.
Referenced by valueToString().
 {
     *--current = 0;
     do
     {
         *--current = (value % 10) + '0';
         value /= 10;
     }
     while ( value != 0 );
 }
static ValueAllocator*& Json::valueAllocator () static
Definition at line 101 of file json_value.cpp.
Referenced by Json::DummyValueAllocatorInitializer::DummyValueAllocatorInitializer(), Json::Value::CommentInfo::setComment(), Json::Value::Value(), Json::Value::CommentInfo::~CommentInfo(), Json::Value::CZString::~CZString(), and Json::Value::~Value().
 {
     static ValueAllocator* valueAllocator = new DefaultValueAllocator;
     return valueAllocator;
 }
std::string Json::valueToQuotedString (const char * value)
Definition at line 100 of file json_writer.cpp.
References containsControlCharacter(), and isControlCharacter().
Referenced by Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), and Json::StyledStreamWriter::writeValue().
 {
     // Not sure how to handle unicode...
     if (strpbrk (value, "\"\\\b\f\n\r\t") == nullptr && !containsControlCharacter ( value ))
         return std::string ("\"") + value + "\"";
     // We have to walk value and escape any special characters.
     // Appending to std::string is not efficient, but this should be rare.
     // (Note: forward slashes are *not* rare, but I am not escaping them.)
     unsigned maxsize = strlen (value) * 2 + 3; // allescaped+quotes+NULL
     std::string result;
     result.reserve (maxsize); // to avoid lots of mallocs
     result += "\"";
     for (const char* c = value; *c != 0; ++c)
     {
         switch (*c)
         {
         case '\"':
             result += "\\\"";
             break;
         case '\\':
             result += "\\\\";
             break;
         case '\b':
             result += "\\b";
             break;
         case '\f':
             result += "\\f";
             break;
         case '\n':
             result += "\\n";
             break;
         case '\r':
             result += "\\r";
             break;
         case '\t':
             result += "\\t";
             break;
             //case '/':
             // Even though \/ is considered a legal escape in JSON, a bare
             // slash is also legal, so I see no reason to escape it.
             // (I hope I am not misunderstanding something.
             // blep notes: actually escaping \/ may be useful in javascript to avoid </
             // sequence.
             // Should add a flag to allow this compatibility mode and prevent this
             // sequence from occurring.
         default:
             if ( isControlCharacter ( *c ) )
             {
                 std::ostringstream oss;
                 oss << "\\u" << std::hex << std::uppercase << std::setfill ('0') << std::setw (4) << static_cast<int> (*c);
                 result += oss.str ();
             }
             else
             {
                 result += *c;
             }
             break;
         }
     }
     result += "\"";
     return result;
 }
std::string Json::valueToString (Int value)
Definition at line 51 of file json_writer.cpp.
References uintToString(), and value.
Referenced by Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), and Json::StyledStreamWriter::writeValue().
 {
     char buffer[32];
     char* current = buffer + sizeof (buffer);
     bool isNegative = value < 0;
     if ( isNegative )
         value = -value;
     uintToString ( UInt (value), current );
     if ( isNegative )
         *--current = '-';
     assert ( current >= buffer );
     return current;
 }
std::string Json::valueToString (UInt value)
Definition at line 70 of file json_writer.cpp.
References uintToString().
 {
     char buffer[32];
     char* current = buffer + sizeof (buffer);
     uintToString ( value, current );
     assert ( current >= buffer );
     return current;
 }
std::string Json::valueToString (double value)
Definition at line 79 of file json_writer.cpp.
 {
     // Allocate a buffer that is more than large enough to store the 16 digits of
     // precision requested below.
     char buffer[32];
     // Print into the buffer. We need not request the alternative representation
     // that always has a decimal point because JSON doesn't distingish the
     // concepts of reals and integers.
 #if defined(_MSC_VER) && defined(__STDC_SECURE_LIB__) // Use secure version with visual studio 2005 to avoid warning.
     sprintf_s(buffer, sizeof(buffer), "%.16g", value);
 #else
     snprintf(buffer, sizeof(buffer), "%.16g", value);
 #endif
     return buffer;
 }
std::string Json::valueToString (bool value)
Definition at line 95 of file json_writer.cpp.
 {
     return value ? "true" : "false";
 }
Variable Documentation
struct Json::DummyValueAllocatorInitializer Json::dummyValueAllocatorInitializer static