rippled: ripple::InfoSub::Source Class Reference
ripple::InfoSub::Source Class Reference abstract
#include <InfoSub.h>
Public Member Functions
virtual void subAccount (ref ispListener, const boost::unordered_set< RippleAddress > &vnaAccountIDs, std::uint32_t uLedgerIndex, bool rt)=0
virtual void unsubAccount (std::uint64_t uListener, const boost::unordered_set< RippleAddress > &vnaAccountIDs, bool rt)=0
virtual bool subLedger (ref ispListener, Json::Value &jvResult)=0
virtual bool unsubLedger (std::uint64_t uListener)=0
virtual bool subServer (ref ispListener, Json::Value &jvResult)=0
virtual bool unsubServer (std::uint64_t uListener)=0
virtual bool subBook (ref ispListener, RippleCurrency const &currencyPays, RippleCurrency const &currencyGets, RippleIssuer const &issuerPays, RippleIssuer const &issuerGets)=0
virtual bool unsubBook (std::uint64_t uListener, RippleCurrency const &currencyPays, RippleCurrency const &currencyGets, RippleIssuer const &issuerPays, RippleIssuer const &issuerGets)=0
virtual bool subTransactions (ref ispListener)=0
virtual bool unsubTransactions (std::uint64_t uListener)=0
virtual bool subRTTransactions (ref ispListener)=0
virtual bool unsubRTTransactions (std::uint64_t uListener)=0
virtual pointer findRpcSub (const std::string &strUrl)=0
virtual pointer addRpcSub (const std::string &strUrl, ref rspEntry)=0
Public Member Functions inherited from beast::Stoppable
Stoppable (char const *name, Stoppable &parent)
virtual ~Stoppable ()
bool isStopping () const
bool isStopped () const
bool areChildrenStopped () const
void stopped ()
virtual void onPrepare ()
virtual void onStart ()
virtual void onStop ()
virtual void onChildrenStopped ()
Protected Member Functions
Source (char const *name, beast::Stoppable &parent)
Protected Member Functions inherited from beast::Stoppable
Stoppable (char const *name, RootStoppable &root)
Additional Inherited Members
Protected Attributes inherited from beast::Stoppable
char const * m_name
RootStoppable & m_root
Child m_child
Atomic< int > m_started
bool volatile m_stopped
bool volatile m_childrenStopped
Children m_children
WaitableEvent m_stoppedEvent
Detailed Description
Abstracts the source of subscription data.
Definition at line 50 of file InfoSub.h.
Constructor & Destructor Documentation
ripple::InfoSub::Source::Source (char const * name, beast::Stoppable & parent) protected
Definition at line 35 of file InfoSub.cpp.
     : Stoppable (name, parent)
 {
 }
Member Function Documentation
virtual pointer ripple::InfoSub::Source::addRpcSub (const std::string & strUrl, ref rspEntry) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doSubscribe().
virtual pointer ripple::InfoSub::Source::findRpcSub (const std::string & strUrl) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doSubscribe(), and ripple::RPCHandler::doUnsubscribe().
virtual void ripple::InfoSub::Source::subAccount (ref ispListener, const boost::unordered_set< RippleAddress > & vnaAccountIDs, std::uint32_t uLedgerIndex, bool rt) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doSubscribe().
virtual bool ripple::InfoSub::Source::subBook (ref ispListener, RippleCurrency const & currencyPays, RippleCurrency const & currencyGets, RippleIssuer const & issuerPays, RippleIssuer const & issuerGets) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doSubscribe().
virtual bool ripple::InfoSub::Source::subLedger (ref ispListener, Json::Value & jvResult) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doSubscribe().
virtual bool ripple::InfoSub::Source::subRTTransactions (ref ispListener) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doSubscribe().
virtual bool ripple::InfoSub::Source::subServer (ref ispListener, Json::Value & jvResult) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doSubscribe().
virtual bool ripple::InfoSub::Source::subTransactions (ref ispListener) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doSubscribe().
virtual void ripple::InfoSub::Source::unsubAccount (std::uint64_t uListener, const boost::unordered_set< RippleAddress > & vnaAccountIDs, bool rt) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doUnsubscribe(), and ripple::InfoSub::~InfoSub().
virtual bool ripple::InfoSub::Source::unsubBook (std::uint64_t uListener, RippleCurrency const & currencyPays, RippleCurrency const & currencyGets, RippleIssuer const & issuerPays, RippleIssuer const & issuerGets) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doUnsubscribe().
virtual bool ripple::InfoSub::Source::unsubLedger (std::uint64_t uListener) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doUnsubscribe(), and ripple::InfoSub::~InfoSub().
virtual bool ripple::InfoSub::Source::unsubRTTransactions (std::uint64_t uListener) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doUnsubscribe(), and ripple::InfoSub::~InfoSub().
virtual bool ripple::InfoSub::Source::unsubServer (std::uint64_t uListener) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doUnsubscribe(), and ripple::InfoSub::~InfoSub().
virtual bool ripple::InfoSub::Source::unsubTransactions (std::uint64_t uListener) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doUnsubscribe(), and ripple::InfoSub::~InfoSub().
The documentation for this class was generated from the following files:
rippled/src/ripple_net/rpc/InfoSub.h
rippled/src/ripple_net/rpc/InfoSub.cpp