rippled: ripple::LedgerHolder Class Reference
ripple::LedgerHolder Class Reference
#include <LedgerHolder.h>
Public Types
typedef RippleMutex LockType
typedef std::lock_guard< LockType > ScopedLockType
Public Member Functions
void set (Ledger::pointer ledger)
Ledger::pointer get ()
Ledger::pointer getMutable ()
bool empty ()
Private Attributes
LockType m_lock
Ledger::pointer m_heldLedger
Detailed Description
Hold a ledger in a thread-safe way.
Definition at line 29 of file LedgerHolder.h.
Member Typedef Documentation
typedef RippleMutex ripple::LedgerHolder::LockType
Definition at line 32 of file LedgerHolder.h.
typedef std::lock_guard<LockType> ripple::LedgerHolder::ScopedLockType
Definition at line 33 of file LedgerHolder.h.
Member Function Documentation
bool ripple::LedgerHolder::empty () inline
Definition at line 65 of file LedgerHolder.h.
References m_heldLedger, and m_lock.
Referenced by ripple::LedgerMasterImp::advanceThread(), ripple::LedgerMasterImp::tryAdvance(), and ripple::LedgerMasterImp::updatePaths().
     {
         ScopedLockType sl (m_lock);
         return m_heldLedger == nullptr;
     }
Ledger::pointer ripple::LedgerHolder::get () inline
Definition at line 50 of file LedgerHolder.h.
References m_heldLedger, and m_lock.
Referenced by ripple::LedgerMasterImp::findNewLedgersToPublish(), ripple::LedgerMasterImp::getClosedLedger(), ripple::LedgerMasterImp::getCurrentLedger(), ripple::LedgerMasterImp::getCurrentLedgerIndex(), ripple::LedgerMasterImp::getLedgerByHash(), ripple::LedgerMasterImp::getLedgerBySeq(), ripple::LedgerMasterImp::getValidatedLedger(), ripple::LedgerMasterImp::updatePaths(), and ripple::LedgerMasterImp::walkHashBySeq().
     {
         ScopedLockType sl (m_lock);
         return m_heldLedger;
     }
Ledger::pointer ripple::LedgerHolder::getMutable () inline
Definition at line 58 of file LedgerHolder.h.
Referenced by ripple::LedgerMasterImp::closeLedger(), and ripple::LedgerMasterImp::pushLedger().
     {
         Ledger::pointer ret = get ();
         return ret ? boost::make_shared <Ledger> (*ret, true) : ret;
     }
void ripple::LedgerHolder::set (Ledger::pointer ledger) inline
Definition at line 36 of file LedgerHolder.h.
References m_heldLedger, and m_lock.
Referenced by ripple::LedgerMasterImp::closeLedger(), ripple::LedgerMasterImp::doTransaction(), ripple::LedgerMasterImp::pushLedger(), ripple::LedgerMasterImp::setValidLedger(), and ripple::LedgerMasterImp::switchLedgers().
     {
         // The held ledger must always be immutable
         if (ledger && !ledger->isImmutable ())
            ledger = boost::make_shared <Ledger> (*ledger, false);
         {
             ScopedLockType sl (m_lock);
             m_heldLedger = ledger;
         }
     }
Member Data Documentation
Ledger::pointer ripple::LedgerHolder::m_heldLedger private
Definition at line 75 of file LedgerHolder.h.
Referenced by empty(), get(), and set().
LockType ripple::LedgerHolder::m_lock private
Definition at line 74 of file LedgerHolder.h.
Referenced by empty(), get(), and set().
The documentation for this class was generated from the following file:
rippled/src/ripple_app/ledger/LedgerHolder.h