rippled: ripple::InboundLedger Class Reference
ripple::InboundLedger Class Reference
#include <InboundLedger.h>
Public Types
enum fcReason {
fcHISTORY, fcGENERIC, fcVALIDATION, fcCURRENT,
fcCONSENSUS
}
typedef boost::shared_ptr
< InboundLedger > pointer
typedef std::pair
< boost::weak_ptr< Peer >
, boost::shared_ptr
< protocol::TMLedgerData > > PeerDataPairType
typedef std::pair
< protocol::TMGetObjectByHash::ObjectType,
uint256 > neededHash_t
Public Types inherited from ripple::PeerSet
typedef beast::abstract_clock
< std::chrono::seconds > clock_type
Public Member Functions
InboundLedger (uint256 const &hash, std::uint32_t seq, fcReason reason, clock_type &clock)
~InboundLedger ()
bool isBase () const
bool isAcctStComplete () const
bool isTransComplete () const
bool isDone () const
Ledger::ref getLedger ()
void abort ()
std::uint32_t getSeq ()
bool addOnComplete (std::function< void(InboundLedger::pointer)>)
void trigger (Peer::ptr const &)
bool tryLocal ()
void addPeers ()
bool checkLocal ()
void init (ScopedLockType &collectionLock)
bool gotData (boost::weak_ptr< Peer >, boost::shared_ptr< protocol::TMLedgerData >)
std::vector< neededHash_t > getNeededHashes ()
void filterNodes (std::vector< SHAMapNode > &nodeIDs, std::vector< uint256 > &nodeHashes, std::set< SHAMapNode > &recentNodes, int max, bool aggressive)
Json::Value getJson (int)
void runData ()
Public Member Functions inherited from ripple::PeerSet
uint256 const & getHash () const
bool isComplete () const
bool isFailed () const
int getTimeouts () const
bool isActive ()
void progress ()
void clearProgress ()
bool isProgress ()
void touch ()
clock_type::time_point getLastAction () const
bool peerHas (Peer::ptr const &)
void peerHasVoid (Peer::ptr const &peer)
void badPeer (Peer::ptr const &)
void setTimer ()
std::size_t takePeerSetFrom (const PeerSet &s)
std::size_t getPeerCount () const
Public Member Functions inherited from ripple::CountedObject< InboundLedger >
CountedObject ()
CountedObject (CountedObject const &)
~CountedObject ()
Static Public Member Functions
static char const * getCountedObjectName ()
Private Member Functions
void done ()
void onTimer (bool progress, ScopedLockType &peerSetLock)
void newPeer (Peer::ptr const &peer)
boost::weak_ptr< PeerSet > pmDowncast ()
int processData (boost::shared_ptr< Peer > peer, protocol::TMLedgerData &data)
bool takeBase (const std::string &data)
bool takeTxNode (const std::list< SHAMapNode > &IDs, const std::list< Blob > &data, SHAMapAddNode &)
bool takeTxRootNode (Blob const &data, SHAMapAddNode &)
bool takeAsNode (const std::list< SHAMapNode > &IDs, const std::list< Blob > &data, SHAMapAddNode &)
bool takeAsRootNode (Blob const &data, SHAMapAddNode &)
Private Attributes
Ledger::pointer mLedger
bool mHaveBase
bool mHaveState
bool mHaveTransactions
bool mAborted
bool mSignaled
bool mByHash
std::uint32_t mSeq
fcReason mReason
std::set< SHAMapNode > mRecentTXNodes
std::set< SHAMapNode > mRecentASNodes
PeerSet::LockType mReceivedDataLock
std::vector< PeerDataPairType > mReceivedData
bool mReceiveDispatched
std::vector< std::function
< void(InboundLedger::pointer)> > mOnComplete
Additional Inherited Members
Protected Types inherited from ripple::PeerSet
typedef RippleRecursiveMutex LockType
typedef std::unique_lock
< LockType > ScopedLockType
typedef Peer::ShortId PeerIdentifier
typedef int ReceivedChunkCount
typedef ripple::unordered_map
< PeerIdentifier,
ReceivedChunkCount > PeerSetMap
Protected Member Functions inherited from ripple::PeerSet
PeerSet (uint256 const &hash, int interval, bool txnData, clock_type &clock, beast::Journal journal)
virtual ~PeerSet ()=0
void setComplete ()
void setFailed ()
void invokeOnTimer ()
void sendRequest (const protocol::TMGetLedger &message)
void sendRequest (const protocol::TMGetLedger &message, Peer::ptr const &peer)
Protected Attributes inherited from ripple::PeerSet
beast::Journal m_journal
clock_type & m_clock
LockType mLock
uint256 mHash
int mTimerInterval
int mTimeouts
bool mComplete
bool mFailed
bool mAggressive
bool mTxnData
clock_type::time_point mLastAction
bool mProgress
boost::asio::deadline_timer mTimer
PeerSetMap mPeers
Detailed Description
Definition at line 27 of file InboundLedger.h.
Member Typedef Documentation
typedef std::pair<protocol::TMGetObjectByHash::ObjectType, uint256> ripple::InboundLedger::neededHash_t
Definition at line 93 of file InboundLedger.h.
typedef std::pair< boost::weak_ptr<Peer>, boost::shared_ptr<protocol::TMLedgerData> > ripple::InboundLedger::PeerDataPairType
Definition at line 36 of file InboundLedger.h.
typedef boost::shared_ptr<InboundLedger> ripple::InboundLedger::pointer
Definition at line 35 of file InboundLedger.h.
Member Enumeration Documentation
enum ripple::InboundLedger::fcReason
Enumerator
fcHISTORY
fcGENERIC
fcVALIDATION
fcCURRENT
fcCONSENSUS
Definition at line 39 of file InboundLedger.h.
     {
         fcHISTORY,      // Acquiring past ledger
         fcGENERIC,      // Generic other reasons
         fcVALIDATION,   // Validations suggest this ledger is important
         fcCURRENT,      // This might be the current ledger
         fcCONSENSUS,    // We believe the consensus round requires this ledger
     };
Constructor & Destructor Documentation
ripple::InboundLedger::InboundLedger (uint256 const & hash, std::uint32_t seq, fcReason reason, clock_type & clock)
Definition at line 39 of file InboundLedger.cpp.
References ripple::PeerSet::m_journal, ripple::PeerSet::mHash, and beast::Journal::trace.
     : PeerSet (hash, ledgerAcquireTimeoutMillis, false, clock,
         LogPartition::getJournal <InboundLedger> ())
     , mHaveBase (false)
     , mHaveState (false)
     , mHaveTransactions (false)
     , mAborted (false)
     , mSignaled (false)
     , mByHash (true)
     , mSeq (seq)
     , mReason (reason)
     , mReceiveDispatched (false)
 {
     if (m_journal.trace) m_journal.trace <<
         "Acquiring ledger " << mHash;
 }
ripple::InboundLedger::~InboundLedger ()
Definition at line 70 of file InboundLedger.cpp.
References ripple::getApp(), ripple::Application::getInboundLedgers(), ripple::InboundLedgers::gotStaleData(), and mReceivedData.
 {
     // Save any received AS data not processed. It could be useful
     // for populating a different ledger
     BOOST_FOREACH (PeerDataPairType& entry, mReceivedData)
     {
         if (entry.second->type () == protocol::liAS_NODE)
             getApp().getInboundLedgers().gotStaleData(entry.second);
     }
 }
Member Function Documentation
void ripple::InboundLedger::abort () inline
Definition at line 73 of file InboundLedger.h.
References mAborted.
     {
         mAborted = true;
     }
bool ripple::InboundLedger::addOnComplete (std::function< void(InboundLedger::pointer)> triggerFunc)
Definition at line 397 of file InboundLedger.cpp.
References isDone(), ripple::PeerSet::mLock, and mOnComplete.
 {
     ScopedLockType sl (mLock);
     if (isDone ())
         return false;
     mOnComplete.push_back (triggerFunc);
     return true;
 }
void ripple::InboundLedger::addPeers ()
Add more peers to the set, if possible
Definition at line 273 of file InboundLedger.cpp.
References beast::Journal::debug, ripple::Overlay::getActivePeers(), ripple::getApp(), ripple::PeerSet::getHash(), ripple::base_uint< BITS >::GetHex(), ripple::lsERROR, ripple::PeerSet::m_journal, mSeq, ripple::Application::overlay(), ripple::PeerSet::peerHas(), rand, and WriteLog.
Referenced by init(), and onTimer().
 {
     Overlay::PeerSequence peerList = getApp().overlay ().getActivePeers ();
     int vSize = peerList.size ();
     if (vSize == 0)
     {
         WriteLog (lsERROR, InboundLedger) <<
             "No peers to add for ledger acquisition";
         return;
     }
     // FIXME-NIKB why are we doing this convoluted thing here instead of simply
     // shuffling this vector and then pulling however many entries we need?
     // We traverse the peer list in random order so as not to favor
     // any particular peer
     //
     // VFALCO Use random_shuffle
     //        http://en.cppreference.com/w/cpp/algorithm/random_shuffle
     //
     int firstPeer = rand () % vSize;
     int found = 0;
     // First look for peers that are likely to have this ledger
     for (int i = 0; i < vSize; ++i)
     {
         Peer::ptr const& peer = peerList[ (i + firstPeer) % vSize];
         if (peer->hasLedger (getHash (), mSeq))
         {
            if (peerHas (peer) && (++found > 6))
                break;
         }
     }
     if (!found)
     { // Oh well, try some random peers
         for (int i = 0; (i < 6) && (i < vSize); ++i)
         {
             if (peerHas (peerList[ (i + firstPeer) % vSize]))
                 ++found;
         }
         if (mSeq != 0)
         {
             if (m_journal.debug) m_journal.debug <<
                 "Chose " << found << " peer(s) for ledger " << mSeq;
         }
         else
         {
             if (m_journal.debug) m_journal.debug <<
                 "Chose " << found << " peer(s) for ledger " <<
                     getHash ().GetHex();
         }
     }
     else if (mSeq != 0)
     {
         if (m_journal.debug) m_journal.debug <<
             "Found " << found << " peer(s) with ledger " << mSeq;
     }
     else
     {
         if (m_journal.debug) m_journal.debug <<
             "Found " << found << " peer(s) with ledger " <<
                 getHash ().GetHex();
     }
 }
bool ripple::InboundLedger::checkLocal ()
Definition at line 58 of file InboundLedger.cpp.
References done(), isDone(), ripple::PeerSet::mLock, and tryLocal().
Referenced by onTimer().
 {
     ScopedLockType sl (mLock);
     if (!isDone () && tryLocal())
     {
         done();
         return true;
     }
     return false;
 }
void ripple::InboundLedger::done () private
Definition at line 364 of file InboundLedger.cpp.
References ripple::JobQueue::addJob(), BIND_TYPE, ripple::getApp(), ripple::Application::getInboundLedgers(), ripple::Application::getJobQueue(), ripple::Application::getLedgerMaster(), ripple::PeerSet::isComplete(), ripple::PeerSet::isFailed(), ripple::jtLEDGER_DATA, ripple::LADispatch(), ripple::InboundLedgers::logFailure(), ripple::PeerSet::m_journal, ripple::PeerSet::mHash, mLedger, ripple::PeerSet::mLock, mOnComplete, mSignaled, P_1, ripple::LedgerMaster::storeLedger(), ripple::PeerSet::touch(), and beast::Journal::trace.
Referenced by checkLocal(), onTimer(), takeAsNode(), takeTxNode(), and trigger().
 {
     if (mSignaled)
         return;
     mSignaled = true;
     touch ();
     if (m_journal.trace) m_journal.trace <<
         "Done acquiring ledger " << mHash;
     assert (isComplete () || isFailed ());
     std::vector< std::function<void (InboundLedger::pointer)> > triggers;
     {
         ScopedLockType sl (mLock);
         triggers.swap (mOnComplete);
     }
     if (isComplete () && !isFailed () && mLedger)
     {
         mLedger->setClosed ();
         mLedger->setImmutable ();
         getApp().getLedgerMaster ().storeLedger (mLedger);
     }
     else
         getApp().getInboundLedgers ().logFailure (mHash);
     // We hold the PeerSet lock, so must dispatch
     getApp().getJobQueue ().addJob (jtLEDGER_DATA, "triggers",
         BIND_TYPE (LADispatch, P_1, shared_from_this (), triggers));
 }
void ripple::InboundLedger::filterNodes (std::vector< SHAMapNode > & nodeIDs, std::vector< uint256 > & nodeHashes, std::set< SHAMapNode > & recentNodes, int max, bool aggressive)
Definition at line 688 of file InboundLedger.cpp.
References ripple::PeerSet::m_journal, ripple::max(), and beast::Journal::trace.
Referenced by trigger().
 {
     // ask for new nodes in preference to ones we've already asked for
     assert (nodeIDs.size () == nodeHashes.size ());
     std::vector<bool> duplicates;
     duplicates.reserve (nodeIDs.size ());
     int dupCount = 0;
     BOOST_FOREACH(SHAMapNode const& nodeID, nodeIDs)
     {
         if (recentNodes.count (nodeID) != 0)
         {
             duplicates.push_back (true);
             ++dupCount;
         }
         else
             duplicates.push_back (false);
     }
     if (dupCount == nodeIDs.size ())
     {
         // all duplicates
         if (!aggressive)
         {
             nodeIDs.clear ();
             nodeHashes.clear ();
             if (m_journal.trace) m_journal.trace <<
                 "filterNodes: all are duplicates";
             return;
         }
     }
     else if (dupCount > 0)
     {
         // some, but not all, duplicates
         int insertPoint = 0;
         for (unsigned int i = 0; i < nodeIDs.size (); ++i)
             if (!duplicates[i])
             {
                 // Keep this node
                 if (insertPoint != i)
                 {
                     nodeIDs[insertPoint] = nodeIDs[i];
                     nodeHashes[insertPoint] = nodeHashes[i];
                 }
                 ++insertPoint;
             }
         if (m_journal.trace) m_journal.trace <<
             "filterNodes " << nodeIDs.size () << " to " << insertPoint;
         nodeIDs.resize (insertPoint);
         nodeHashes.resize (insertPoint);
     }
     if (nodeIDs.size () > max)
     {
         nodeIDs.resize (max);
         nodeHashes.resize (max);
     }
     BOOST_FOREACH (const SHAMapNode & n, nodeIDs)
     {
         recentNodes.insert (n);
     }
 }
static char const* ripple::InboundLedger::getCountedObjectName () inline static
Definition at line 33 of file InboundLedger.h.
 { return "InboundLedger"; }
Json::Value ripple::InboundLedger::getJson (int)
Definition at line 1214 of file InboundLedger.cpp.
References Json::Value::append(), Json::arrayValue, ripple::base_uint< BITS >::GetHex(), ripple::PeerSet::getTimeouts(), mAborted, ripple::PeerSet::mComplete, ripple::PeerSet::mFailed, ripple::PeerSet::mHash, mHaveBase, mHaveState, mHaveTransactions, mLedger, ripple::PeerSet::mLock, ripple::PeerSet::mPeers, and Json::objectValue.
 {
     Json::Value ret (Json::objectValue);
     ScopedLockType sl (mLock);
     ret["hash"] = mHash.GetHex ();
     if (mComplete)
         ret["complete"] = true;
     if (mFailed)
         ret["failed"] = true;
     if (!mComplete && !mFailed)
         ret["peers"] = static_cast<int>(mPeers.size());
     ret["have_base"] = mHaveBase;
     if (mHaveBase)
     {
         ret["have_state"] = mHaveState;
         ret["have_transactions"] = mHaveTransactions;
     }
     if (mAborted)
         ret["aborted"] = true;
     ret["timeouts"] = getTimeouts ();
     if (mHaveBase && !mHaveState)
     {
         Json::Value hv (Json::arrayValue);
         // VFALCO Why 16?
         std::vector<uint256> v = mLedger->getNeededAccountStateHashes (
             16, nullptr);
         BOOST_FOREACH (uint256 const & h, v)
         {
             hv.append (h.GetHex ());
         }
         ret["needed_state_hashes"] = hv;
     }
     if (mHaveBase && !mHaveTransactions)
     {
         Json::Value hv (Json::arrayValue);
         // VFALCO Why 16?
         std::vector<uint256> v = mLedger->getNeededTransactionHashes (
             16, nullptr);
         BOOST_FOREACH (uint256 const & h, v)
         {
             hv.append (h.GetHex ());
         }
         ret["needed_transaction_hashes"] = hv;
     }
     return ret;
 }
Ledger::ref ripple::InboundLedger::getLedger () inline
Definition at line 69 of file InboundLedger.h.
References mLedger.
     {
         return mLedger;
     }
std::vector< InboundLedger::neededHash_t > ripple::InboundLedger::getNeededHashes ()
Definition at line 990 of file InboundLedger.cpp.
References ripple::PeerSet::mHash, mHaveBase, mHaveState, mHaveTransactions, and mLedger.
Referenced by trigger().
 {
     std::vector<neededHash_t> ret;
     if (!mHaveBase)
     {
         ret.push_back (std::make_pair (
             protocol::TMGetObjectByHash::otLEDGER, mHash));
         return ret;
     }
     if (!mHaveState)
     {
         AccountStateSF filter (mLedger->getLedgerSeq ());
         // VFALCO NOTE What's the number 4?
         std::vector<uint256> v = mLedger->getNeededAccountStateHashes (
             4, &filter);
         BOOST_FOREACH (uint256 const & h, v)
         {
             ret.push_back (std::make_pair (
                 protocol::TMGetObjectByHash::otSTATE_NODE, h));
         }
     }
     if (!mHaveTransactions)
     {
         TransactionStateSF filter (mLedger->getLedgerSeq ());
         // VFALCO NOTE What's the number 4?
         std::vector<uint256> v = mLedger->getNeededTransactionHashes (
             4, &filter);
         BOOST_FOREACH (uint256 const & h, v)
         {
             ret.push_back (std::make_pair (
                 protocol::TMGetObjectByHash::otTRANSACTION_NODE, h));
         }
     }
     return ret;
 }
std::uint32_t ripple::InboundLedger::getSeq () inline
Definition at line 77 of file InboundLedger.h.
References mSeq.
     {
         return mSeq;
     }
bool ripple::InboundLedger::gotData (boost::weak_ptr< Peer > peer, boost::shared_ptr< protocol::TMLedgerData > data)
Stash a TMLedgerData received from a peer for later processing Returns 'true' if we need to dispatch
Definition at line 1034 of file InboundLedger.cpp.
References mReceivedData, mReceivedDataLock, and mReceiveDispatched.
 {
     ScopedLockType sl (mReceivedDataLock);
     mReceivedData.push_back (PeerDataPairType (peer, data));
     if (mReceiveDispatched)
         return false;
     mReceiveDispatched = true;
     return true;
 }
void ripple::InboundLedger::init (ScopedLockType & collectionLock)
Definition at line 82 of file InboundLedger.cpp.
References addPeers(), ripple::LedgerMaster::checkAccept(), beast::Journal::debug, fcCONSENSUS, fcCURRENT, fcHISTORY, fcVALIDATION, ripple::getApp(), ripple::PeerSet::getHash(), ripple::Application::getLedgerMaster(), ripple::PeerSet::isFailed(), ripple::PeerSet::m_journal, mLedger, ripple::PeerSet::mLock, mReason, ripple::PeerSet::setTimer(), ripple::LedgerMaster::storeLedger(), trigger(), and tryLocal().
 {
     ScopedLockType sl (mLock);
     collectionLock.unlock ();
     if (!tryLocal ())
     {
         addPeers ();
         setTimer ();
         // For historical nodes, wait a bit since a
         // fetch pack is probably coming
         if (mReason != fcHISTORY)
             trigger (Peer::ptr ());
     }
     else if (!isFailed ())
     {
         if (m_journal.debug) m_journal.debug <<
             "Acquiring ledger we already have locally: " << getHash ();
         mLedger->setClosed ();
         mLedger->setImmutable ();
         getApp ().getLedgerMaster ().storeLedger (mLedger);
         // Check if this could be a newer fully-validated ledger
         if ((mReason == fcVALIDATION) || (mReason == fcCURRENT) || (mReason ==  fcCONSENSUS))
             getApp ().getLedgerMaster ().checkAccept (mLedger);
     }
 }
bool ripple::InboundLedger::isAcctStComplete () const inline
Definition at line 57 of file InboundLedger.h.
References mHaveState.
     {
         return mHaveState;
     }
bool ripple::InboundLedger::isBase () const inline
Definition at line 53 of file InboundLedger.h.
References mHaveBase.
     {
         return mHaveBase;
     }
bool ripple::InboundLedger::isDone () const inline virtual
Reimplemented from ripple::PeerSet.
Definition at line 65 of file InboundLedger.h.
References ripple::PeerSet::isComplete(), ripple::PeerSet::isFailed(), and mAborted.
Referenced by addOnComplete(), checkLocal(), onTimer(), and trigger().
     {
         return mAborted || isComplete () || isFailed ();
     }
bool ripple::InboundLedger::isTransComplete () const inline
Definition at line 61 of file InboundLedger.h.
References mHaveTransactions.
     {
         return mHaveTransactions;
     }
void ripple::InboundLedger::newPeer (Peer::ptr const & peer) inline private virtual
Implements ripple::PeerSet.
Definition at line 109 of file InboundLedger.h.
References trigger().
     {
         trigger (peer);
     }
void ripple::InboundLedger::onTimer (bool wasProgress, ScopedLockType & peerSetLock) private virtual
Called with a lock by the PeerSet when the timer expires
Implements ripple::PeerSet.
Definition at line 225 of file InboundLedger.cpp.
References addPeers(), checkLocal(), done(), ripple::PeerSet::getPeerCount(), ripple::PeerSet::getTimeouts(), beast::Journal::info, isDone(), ripple::ledgerTimeoutRetriesMax, ripple::lsDEBUG, ripple::PeerSet::m_journal, ripple::PeerSet::mAggressive, mByHash, ripple::PeerSet::mHash, mRecentASNodes, mRecentTXNodes, mSeq, ripple::PeerSet::setFailed(), trigger(), beast::Journal::warning, and WriteLog.
 {
     mRecentTXNodes.clear ();
     mRecentASNodes.clear ();
     if (isDone())
     {
         if (m_journal.info) m_journal.info <<
             "Already done " << mHash;
         return;
     }
     if (getTimeouts () > ledgerTimeoutRetriesMax)
     {
         if (mSeq != 0)
         {
             if (m_journal.warning) m_journal.warning <<
                 getTimeouts() << " timeouts for ledger " << mSeq;
         }
         else
         {
             if (m_journal.warning) m_journal.warning <<
                 getTimeouts() << " timeouts for ledger " << mHash;
         }
         setFailed ();
         done ();
         return;
     }
     if (!wasProgress)
     {
         checkLocal();
         mAggressive = true;
         mByHash = true;
         std::size_t pc = getPeerCount ();
         WriteLog (lsDEBUG, InboundLedger) <<
             "No progress(" << pc <<
             ") for ledger " << mHash;
         trigger (Peer::ptr ());
         if (pc < 4)
             addPeers ();
     }
 }
boost::weak_ptr< PeerSet > ripple::InboundLedger::pmDowncast () private virtual
Implements ripple::PeerSet.
Definition at line 343 of file InboundLedger.cpp.
 {
     return boost::dynamic_pointer_cast<PeerSet> (shared_from_this ());
 }
int ripple::InboundLedger::processData (boost::shared_ptr< Peer > peer, protocol::TMLedgerData & packet) private
Process one TMLedgerData Returns the number of useful nodes
Definition at line 1056 of file InboundLedger.cpp.
References beast::Journal::debug, ripple::Resource::feeInvalidRequest, ripple::SHAMapAddNode::get(), ripple::SHAMapAddNode::getGood(), ripple::SHAMapAddNode::incUseful(), beast::Journal::info, ripple::SHAMapAddNode::isInvalid(), ripple::PeerSet::m_journal, mHaveBase, mHaveState, mHaveTransactions, ripple::PeerSet::mLock, ripple::PeerSet::progress(), ripple::strCopy(), takeAsNode(), takeAsRootNode(), takeBase(), takeTxNode(), takeTxRootNode(), and beast::Journal::warning.
Referenced by runData().
 {
     ScopedLockType sl (mLock);
     if (packet.type () == protocol::liBASE)
     {
         if (packet.nodes_size () < 1)
         {
             if (m_journal.warning) m_journal.warning <<
                 "Got empty base data";
             peer->charge (Resource::feeInvalidRequest);
             return -1;
         }
         SHAMapAddNode san;
         if (!mHaveBase)
         {
             if (takeBase (packet.nodes (0).nodedata ()))
                 san.incUseful ();
             else
             {
                 if (m_journal.warning) m_journal.warning <<
                     "Got invalid base data";
                 peer->charge (Resource::feeInvalidRequest);
                 return -1;
             }
         }
         if (!mHaveState && (packet.nodes ().size () > 1) &&
             !takeAsRootNode (strCopy (packet.nodes (1).nodedata ()), san))
         {
             if (m_journal.warning) m_journal.warning <<
                 "Included ASbase invalid";
         }
         if (!mHaveTransactions && (packet.nodes ().size () > 2) &&
             !takeTxRootNode (strCopy (packet.nodes (2).nodedata ()), san))
         {
             if (m_journal.warning) m_journal.warning <<
                 "Included TXbase invalid";
         }
         if (!san.isInvalid ())
             progress ();
         else
             if (m_journal.debug) m_journal.debug <<
                 "Peer sends invalid base data";
         return san.getGood ();
     }
     if ((packet.type () == protocol::liTX_NODE) || (
         packet.type () == protocol::liAS_NODE))
     {
         std::list<SHAMapNode> nodeIDs;
         std::list< Blob > nodeData;
         if (packet.nodes ().size () == 0)
         {
             if (m_journal.info) m_journal.info <<
                 "Got response with no nodes";
             peer->charge (Resource::feeInvalidRequest);
             return -1;
         }
         for (int i = 0; i < packet.nodes ().size (); ++i)
         {
             const protocol::TMLedgerNode& node = packet.nodes (i);
             if (!node.has_nodeid () || !node.has_nodedata ())
             {
                 if (m_journal.warning) m_journal.warning <<
                     "Got bad node";
                 peer->charge (Resource::feeInvalidRequest);
                 return -1;
             }
             nodeIDs.push_back (SHAMapNode (node.nodeid ().data (),
                 node.nodeid ().size ()));
             nodeData.push_back (Blob (node.nodedata ().begin (),
                 node.nodedata ().end ()));
         }
         SHAMapAddNode ret;
         if (packet.type () == protocol::liTX_NODE)
         {
             takeTxNode (nodeIDs, nodeData, ret);
             if (m_journal.debug) m_journal.debug <<
                 "Ledger TX node stats: " << ret.get();
         }
         else
         {
             takeAsNode (nodeIDs, nodeData, ret);
             if (m_journal.debug) m_journal.debug <<
                 "Ledger AS node stats: " << ret.get();
         }
         if (!ret.isInvalid ())
             progress ();
         else
             if (m_journal.debug) m_journal.debug <<
                 "Peer sends invalid node data";
         return ret.getGood ();
     }
     return -1;
 }
void ripple::InboundLedger::runData ()
Process pending TMLedgerData Query the 'best' peer
Definition at line 1172 of file InboundLedger.cpp.
References mReceivedData, mReceivedDataLock, mReceiveDispatched, processData(), and trigger().
 {
     boost::shared_ptr<Peer> chosenPeer;
     int chosenPeerCount = -1;
     std::vector <PeerDataPairType> data;
     do
     {
         data.clear();
         {
             ScopedLockType sl (mReceivedDataLock);
             if (mReceivedData.empty ())
             {
                 mReceiveDispatched = false;
                 break;
             }
             data.swap(mReceivedData);
         }
         // Select the peer that gives us the most nodes that are useful,
         // breaking ties in favor of the peer that responded first.
         BOOST_FOREACH (PeerDataPairType& entry, data)
         {
             Peer::ptr peer = entry.first.lock();
             if (peer)
             {
                 int count = processData (peer, *(entry.second));
                 if (count > chosenPeerCount)
                 {
                     chosenPeer = peer;
                     chosenPeerCount = count;
                 }
             }
         }
     } while (1);
     if (chosenPeer)
         trigger (chosenPeer);
 }
bool ripple::InboundLedger::takeAsNode (const std::list< SHAMapNode > & nodeIDs, const std::list< Blob > & data, SHAMapAddNode & san) private
Process AS data received from a peer Call with a lock
Definition at line 870 of file InboundLedger.cpp.
References done(), ripple::SHAMapAddNode::incDuplicate(), ripple::SHAMapAddNode::incInvalid(), ripple::SHAMapAddNode::isGood(), ripple::PeerSet::m_journal, ripple::PeerSet::mComplete, ripple::PeerSet::mFailed, ripple::PeerSet::mHash, mHaveBase, mHaveState, mHaveTransactions, mLedger, ripple::PeerSet::mLock, ripple::PeerSet::progress(), ripple::snfWIRE, beast::Journal::trace, and beast::Journal::warning.
Referenced by processData().
 {
     if (m_journal.trace) m_journal.trace <<
         "got ASdata (" << nodeIDs.size () << ") acquiring ledger " << mHash;
     if (nodeIDs.size () == 1 && m_journal.trace) m_journal.trace <<
         "got AS node: " << nodeIDs.front ();
     ScopedLockType sl (mLock);
     if (!mHaveBase)
     {
         if (m_journal.warning) m_journal.warning <<
             "Don't have ledger base";
         san.incInvalid();
         return false;
     }
     if (mHaveState || mFailed)
     {
         san.incDuplicate();
         return true;
     }
     std::list<SHAMapNode>::const_iterator nodeIDit = nodeIDs.begin ();
     std::list< Blob >::const_iterator nodeDatait = data.begin ();
     AccountStateSF tFilter (mLedger->getLedgerSeq ());
     while (nodeIDit != nodeIDs.end ())
     {
         if (nodeIDit->isRoot ())
         {
             san += mLedger->peekAccountStateMap ()->addRootNode (
                 mLedger->getAccountHash (), *nodeDatait, snfWIRE, &tFilter);
             if (!san.isGood ())
             {
                 if (m_journal.warning) m_journal.warning <<
                     "Bad ledger base";
                 return false;
             }
         }
         else
         {
             san += mLedger->peekAccountStateMap ()->addKnownNode (
                 *nodeIDit, *nodeDatait, &tFilter);
             if (!san.isGood ())
             {
                 if (m_journal.warning) m_journal.warning <<
                     "Unable to add AS node";
                 return false;
             }
         }
         ++nodeIDit;
         ++nodeDatait;
     }
     if (!mLedger->peekAccountStateMap ()->isSynching ())
     {
         mHaveState = true;
         if (mHaveTransactions)
         {
             mComplete = true;
             done ();
         }
     }
     progress ();
     return true;
 }
bool ripple::InboundLedger::takeAsRootNode (Blob const & data, SHAMapAddNode & san) private
Process AS root node received from a peer Call with a lock
Definition at line 945 of file InboundLedger.cpp.
References ripple::SHAMapAddNode::incDuplicate(), ripple::SHAMapAddNode::incInvalid(), ripple::PeerSet::mFailed, mHaveBase, mHaveState, mLedger, and ripple::snfWIRE.
Referenced by processData().
 {
     if (mFailed || mHaveState)
     {
         san.incDuplicate();
         return true;
     }
     if (!mHaveBase)
     {
         assert(false);
         san.incInvalid();
         return false;
     }
     AccountStateSF tFilter (mLedger->getLedgerSeq ());
     san += mLedger->peekAccountStateMap ()->addRootNode (
         mLedger->getAccountHash (), data, snfWIRE, &tFilter);
     return san.isGood();
 }
bool ripple::InboundLedger::takeBase (const std::string & data) private
Take ledger base data Call with a lock
Definition at line 763 of file InboundLedger.cpp.
References ripple::Serializer::add32(), ripple::getApp(), ripple::Application::getNodeStore(), ripple::hotLEDGER, ripple::HashPrefix::ledgerMaster, ripple::PeerSet::m_journal, ripple::PeerSet::mComplete, ripple::PeerSet::mFailed, ripple::PeerSet::mHash, mHaveBase, mHaveState, mHaveTransactions, mLedger, ripple::PeerSet::progress(), ripple::NodeStore::Database::store(), beast::Journal::trace, and beast::Journal::warning.
Referenced by processData().
 {
     // Return value: true=normal, false=bad data
     if (m_journal.trace) m_journal.trace <<
         "got base acquiring ledger " << mHash;
     if (mComplete || mFailed || mHaveBase)
         return true;
     mLedger = boost::make_shared<Ledger> (data, false);
     if (mLedger->getHash () != mHash)
     {
         if (m_journal.warning) m_journal.warning <<
             "Acquire hash mismatch";
         if (m_journal.warning) m_journal.warning <<
             mLedger->getHash () << "!=" << mHash;
         mLedger.reset ();
 #ifdef TRUST_NETWORK
         assert (false);
 #endif
         return false;
     }
     mHaveBase = true;
     Serializer s (data.size () + 4);
     s.add32 (HashPrefix::ledgerMaster);
     s.addRaw (data);
     getApp().getNodeStore ().store (hotLEDGER,
         mLedger->getLedgerSeq (), s.modData (), mHash);
     progress ();
     if (mLedger->getTransHash ().isZero ())
         mHaveTransactions = true;
     if (mLedger->getAccountHash ().isZero ())
         mHaveState = true;
     mLedger->setAcquiring ();
     return true;
 }
bool ripple::InboundLedger::takeTxNode (const std::list< SHAMapNode > & nodeIDs, const std::list< Blob > & data, SHAMapAddNode & san) private
Process TX data received from a peer Call with a lock
Definition at line 810 of file InboundLedger.cpp.
References done(), ripple::SHAMapAddNode::incDuplicate(), ripple::SHAMapAddNode::incInvalid(), ripple::SHAMapAddNode::isGood(), ripple::PeerSet::m_journal, ripple::PeerSet::mComplete, ripple::PeerSet::mFailed, mHaveBase, mHaveState, mHaveTransactions, mLedger, ripple::PeerSet::progress(), ripple::snfWIRE, and beast::Journal::warning.
Referenced by processData().
 {
     if (!mHaveBase)
     {
         if (m_journal.warning) m_journal.warning <<
             "TX node without base";
         san.incInvalid();
         return false;
     }
     if (mHaveTransactions || mFailed)
     {
         san.incDuplicate();
         return true;
     }
     std::list<SHAMapNode>::const_iterator nodeIDit = nodeIDs.begin ();
     std::list< Blob >::const_iterator nodeDatait = data.begin ();
     TransactionStateSF tFilter (mLedger->getLedgerSeq ());
     while (nodeIDit != nodeIDs.end ())
     {
         if (nodeIDit->isRoot ())
         {
             san += mLedger->peekTransactionMap ()->addRootNode (
                 mLedger->getTransHash (), *nodeDatait, snfWIRE, &tFilter);
             if (!san.isGood())
                 return false;
         }
         else
         {
             san +=  mLedger->peekTransactionMap ()->addKnownNode (
                 *nodeIDit, *nodeDatait, &tFilter);
             if (!san.isGood())
                 return false;
         }
         ++nodeIDit;
         ++nodeDatait;
     }
     if (!mLedger->peekTransactionMap ()->isSynching ())
     {
         mHaveTransactions = true;
         if (mHaveState)
         {
             mComplete = true;
             done ();
         }
     }
     progress ();
     return true;
 }
bool ripple::InboundLedger::takeTxRootNode (Blob const & data, SHAMapAddNode & san) private
Process AS root node received from a peer Call with a lock
Definition at line 969 of file InboundLedger.cpp.
References ripple::SHAMapAddNode::incDuplicate(), ripple::SHAMapAddNode::incInvalid(), ripple::PeerSet::mFailed, mHaveBase, mHaveState, mLedger, and ripple::snfWIRE.
Referenced by processData().
 {
     if (mFailed || mHaveState)
     {
         san.incDuplicate();
         return true;
     }
     if (!mHaveBase)
     {
         assert(false);
         san.incInvalid();
         return false;
     }
     TransactionStateSF tFilter (mLedger->getLedgerSeq ());
     san += mLedger->peekTransactionMap ()->addRootNode (
         mLedger->getTransHash (), data, snfWIRE, &tFilter);
     return san.isGood();
 }
void ripple::InboundLedger::trigger (Peer::ptr const & peer)
Request more nodes, perhaps from a specific peer
Definition at line 411 of file InboundLedger.cpp.
References ripple::base_uint< BITS >::begin(), beast::Journal::debug, done(), filterNodes(), ripple::getApp(), getNeededHashes(), ripple::SHAMapNode::getRawString(), ripple::PeerSet::getTimeouts(), beast::Journal::info, isDone(), ripple::PeerSet::isProgress(), ripple::ledgerBecomeAggressiveThreshold, ripple::PeerSet::m_journal, mAborted, ripple::PeerSet::mAggressive, mByHash, ripple::PeerSet::mComplete, ripple::PeerSet::mFailed, ripple::PeerSet::mHash, mHaveBase, mHaveState, mHaveTransactions, mLedger, ripple::PeerSet::mLock, ripple::PeerSet::mPeers, mRecentASNodes, mRecentTXNodes, mSeq, ripple::PeerSet::sendRequest(), ripple::base_uint< BITS >::size(), beast::Journal::trace, tryLocal(), and beast::Journal::warning.
Referenced by init(), newPeer(), onTimer(), and runData().
 {
     ScopedLockType sl (mLock);
     if (isDone ())
     {
         if (m_journal.debug) m_journal.debug <<
             "Trigger on ledger: " << mHash << (mAborted ? " aborted" : "") <<
                 (mComplete ? " completed" : "") << (mFailed ? " failed" : "");
         return;
     }
     if (m_journal.trace)
     {
         if (peer)
             m_journal.trace <<
                 "Trigger acquiring ledger " << mHash << " from " << peer;
         else
             m_journal.trace <<
                 "Trigger acquiring ledger " << mHash;
         if (mComplete || mFailed)
             m_journal.trace <<
                 "complete=" << mComplete << " failed=" << mFailed;
         else
             m_journal.trace <<
                 "base=" << mHaveBase << " tx=" << mHaveTransactions <<
                     " as=" << mHaveState;
     }
     if (!mHaveBase)
     {
         tryLocal ();
         if (mFailed)
         {
             if (m_journal.warning) m_journal.warning <<
                 " failed local for " << mHash;
             return;
         }
     }
     protocol::TMGetLedger tmGL;
     tmGL.set_ledgerhash (mHash.begin (), mHash.size ());
     if (getTimeouts () != 0)
     { // Be more aggressive if we've timed out at least once
         tmGL.set_querytype (protocol::qtINDIRECT);
         if (!isProgress () && !mFailed && mByHash && (
             getTimeouts () > ledgerBecomeAggressiveThreshold))
         {
             std::vector<neededHash_t> need = getNeededHashes ();
             if (!need.empty ())
             {
                 protocol::TMGetObjectByHash tmBH;
                 tmBH.set_query (true);
                 tmBH.set_ledgerhash (mHash.begin (), mHash.size ());
                 bool typeSet = false;
                 BOOST_FOREACH (neededHash_t & p, need)
                 {
                     if (m_journal.warning) m_journal.warning
                         << "Want: " << p.second;
                     if (!typeSet)
                     {
                         tmBH.set_type (p.first);
                         typeSet = true;
                     }
                     if (p.first == tmBH.type ())
                     {
                         protocol::TMIndexedObject* io = tmBH.add_objects ();
                         io->set_hash (p.second.begin (), p.second.size ());
                     }
                 }
                 Message::pointer packet (boost::make_shared <Message> (
                     tmBH, protocol::mtGET_OBJECTS));
                 {
                     ScopedLockType sl (mLock);
                     for (PeerSetMap::iterator it = mPeers.begin (), end = mPeers.end ();
                             it != end; ++it)
                     {
                         Peer::ptr iPeer (
                             getApp().overlay ().findPeerByShortID (it->first));
                         if (iPeer)
{
                             mByHash = false;
                             iPeer->sendPacket (packet, false);
                         }
                     }
                 }
                 if (m_journal.info) m_journal.info <<
                     "Attempting by hash fetch for ledger " << mHash;
             }
             else
             {
                 if (m_journal.info) m_journal.info <<
                     "getNeededHashes says acquire is complete";
                 mHaveBase = true;
                 mHaveTransactions = true;
                 mHaveState = true;
                 mComplete = true;
             }
         }
     }
     // We can't do much without the base data because we don't know the
     // state or transaction root hashes.
     if (!mHaveBase && !mFailed)
     {
         tmGL.set_itype (protocol::liBASE);
         if (m_journal.trace) m_journal.trace <<
             "Sending base request to " << (peer ? "selected peer" : "all peers");
         sendRequest (tmGL, peer);
         return;
     }
     if (mLedger)
         tmGL.set_ledgerseq (mLedger->getLedgerSeq ());
     // Get the state data first because it's the most likely to be useful
     // if we wind up abandoning this fetch.
     if (mHaveBase && !mHaveState && !mFailed)
     {
         assert (mLedger);
         if (mLedger->peekAccountStateMap ()->getHash ().isZero ())
         {
             // we need the root node
             tmGL.set_itype (protocol::liAS_NODE);
             * (tmGL.add_nodeids ()) = SHAMapNode ().getRawString ();
             if (m_journal.trace) m_journal.trace <<
                 "Sending AS root request to " << (peer ? "selected peer" : "all peers");
             sendRequest (tmGL, peer);
             return;
         }
         else
         {
             std::vector<SHAMapNode> nodeIDs;
             std::vector<uint256> nodeHashes;
             // VFALCO Why 256? Make this a constant
             nodeIDs.reserve (256);
             nodeHashes.reserve (256);
             AccountStateSF filter (mSeq);
             // Release the lock while we process the large state map
             sl.unlock();
             mLedger->peekAccountStateMap ()->getMissingNodes (
                 nodeIDs, nodeHashes, 256, &filter);
             sl.lock();
             // Make sure nothing happened while we released the lock
             if (!mFailed && !mComplete && !mHaveState)
             {
                 if (nodeIDs.empty ())
                 {
                     if (!mLedger->peekAccountStateMap ()->isValid ())
                         mFailed = true;
                     else
                     {
                         mHaveState = true;
                         if (mHaveTransactions)
                             mComplete = true;
                     }
                 }
                 else
                 {
                     // VFALCO Why 128? Make this a constant
                     if (!mAggressive)
                         filterNodes (nodeIDs, nodeHashes, mRecentASNodes,
                             128, !isProgress ());
                     if (!nodeIDs.empty ())
                     {
                         tmGL.set_itype (protocol::liAS_NODE);
                         BOOST_FOREACH (SHAMapNode const& it, nodeIDs)
{
                             * (tmGL.add_nodeids ()) = it.getRawString ();
                         }
                         if (m_journal.trace) m_journal.trace <<
                             "Sending AS node " << nodeIDs.size () <<
                                 " request to " << (
                                     peer ? "selected peer" : "all peers");
                         if (nodeIDs.size () == 1 && m_journal.trace) m_journal.trace <<
                             "AS node: " << nodeIDs[0];
                         sendRequest (tmGL, peer);
                         return;
                     }
                     else
                         if (m_journal.trace) m_journal.trace <<
                             "All AS nodes filtered";
                 }
             }
         }
     }
     if (mHaveBase && !mHaveTransactions && !mFailed)
     {
         assert (mLedger);
         if (mLedger->peekTransactionMap ()->getHash ().isZero ())
         {
             // we need the root node
             tmGL.set_itype (protocol::liTX_NODE);
             * (tmGL.add_nodeids ()) = SHAMapNode ().getRawString ();
             if (m_journal.trace) m_journal.trace <<
                 "Sending TX root request to " << (
                     peer ? "selected peer" : "all peers");
             sendRequest (tmGL, peer);
             return;
         }
         else
         {
             std::vector<SHAMapNode> nodeIDs;
             std::vector<uint256> nodeHashes;
             nodeIDs.reserve (256);
             nodeHashes.reserve (256);
             TransactionStateSF filter (mSeq);
             mLedger->peekTransactionMap ()->getMissingNodes (
                 nodeIDs, nodeHashes, 256, &filter);
             if (nodeIDs.empty ())
             {
                 if (!mLedger->peekTransactionMap ()->isValid ())
                     mFailed = true;
                 else
                 {
                     mHaveTransactions = true;
                     if (mHaveState)
                         mComplete = true;
                 }
             }
             else
             {
                 if (!mAggressive)
                     filterNodes (nodeIDs, nodeHashes, mRecentTXNodes,
                         128, !isProgress ());
                 if (!nodeIDs.empty ())
                 {
                     tmGL.set_itype (protocol::liTX_NODE);
                     BOOST_FOREACH (SHAMapNode const& it, nodeIDs)
                     {
                         * (tmGL.add_nodeids ()) = it.getRawString ();
                     }
                     if (m_journal.trace) m_journal.trace <<
                         "Sending TX node " << nodeIDs.size () <<
                         " request to " << (
                             peer ? "selected peer" : "all peers");
                     sendRequest (tmGL, peer);
                     return;
                 }
                 else
                     if (m_journal.trace) m_journal.trace <<
                         "All TX nodes filtered";
             }
         }
     }
     if (mComplete || mFailed)
     {
         if (m_journal.debug) m_journal.debug <<
             "Done:" << (mComplete ? " complete" : "") <<
                 (mFailed ? " failed " : " ") <<
             mLedger->getLedgerSeq ();
         sl.unlock ();
         done ();
     }
 }
bool ripple::InboundLedger::tryLocal ()
See how much of the ledger data, if any, is in our node store
Definition at line 114 of file InboundLedger.cpp.
References beast::Journal::debug, beast::Journal::fatal, ripple::NodeStore::Database::fetch(), ripple::getApp(), ripple::Application::getNodeStore(), ripple::hotLEDGER, ripple::PeerSet::m_journal, ripple::PeerSet::mComplete, ripple::PeerSet::mFailed, ripple::PeerSet::mHash, mHaveBase, mHaveState, mHaveTransactions, mLedger, ripple::NodeStore::Database::store(), ripple::strCopy(), beast::Journal::trace, and beast::Journal::warning.
Referenced by checkLocal(), init(), and trigger().
 {
     // return value: true = no more work to do
     if (!mHaveBase)
     {
         // Nothing we can do without the ledger base
         NodeObject::pointer node = getApp().getNodeStore ().fetch (mHash);
         if (!node)
         {
             Blob data;
             if (!getApp().getOPs ().getFetchPack (mHash, data))
                 return false;
             if (m_journal.trace) m_journal.trace <<
                 "Ledger base found in fetch pack";
             mLedger = boost::make_shared<Ledger> (data, true);
             getApp().getNodeStore ().store (hotLEDGER,
                 mLedger->getLedgerSeq (), data, mHash);
         }
         else
         {
             mLedger = boost::make_shared<Ledger> (
                 strCopy (node->getData ()), true);
         }
         if (mLedger->getHash () != mHash)
         {
             // We know for a fact the ledger can never be acquired
             if (m_journal.warning) m_journal.warning <<
                 mHash << " cannot be a ledger";
             mFailed = true;
             return true;
         }
         mHaveBase = true;
     }
     if (!mHaveTransactions)
     {
         if (mLedger->getTransHash ().isZero ())
         {
             if (m_journal.trace) m_journal.trace <<
                 "No TXNs to fetch";
             mHaveTransactions = true;
         }
         else
         {
             TransactionStateSF filter (mLedger->getLedgerSeq ());
             if (mLedger->peekTransactionMap ()->fetchRoot (
                 mLedger->getTransHash (), &filter))
             {
                 std::vector<uint256> h (mLedger->getNeededTransactionHashes (
                     1, &filter));
                 if (h.empty ())
                 {
                     if (m_journal.trace) m_journal.trace <<
                         "Had full txn map locally";
                     mHaveTransactions = true;
                 }
             }
         }
     }
     if (!mHaveState)
     {
         if (mLedger->getAccountHash ().isZero ())
         {
             if (m_journal.fatal) m_journal.fatal <<
                 "We are acquiring a ledger with a zero account hash";
             mFailed = true;
             return true;
         }
         else
         {
             AccountStateSF filter (mLedger->getLedgerSeq ());
             if (mLedger->peekAccountStateMap ()->fetchRoot (
                 mLedger->getAccountHash (), &filter))
             {
                 std::vector<uint256> h (mLedger->getNeededAccountStateHashes (
                     1, &filter));
                 if (h.empty ())
                 {
                     if (m_journal.trace) m_journal.trace <<
                         "Had full AS map locally";
                     mHaveState = true;
                 }
             }
         }
     }
     if (mHaveTransactions && mHaveState)
     {
         if (m_journal.debug) m_journal.debug <<
             "Had everything locally";
         mComplete = true;
         mLedger->setClosed ();
         mLedger->setImmutable ();
     }
     return mComplete;
 }
Member Data Documentation
bool ripple::InboundLedger::mAborted private
Definition at line 136 of file InboundLedger.h.
Referenced by abort(), getJson(), isDone(), and trigger().
bool ripple::InboundLedger::mByHash private
Definition at line 138 of file InboundLedger.h.
Referenced by onTimer(), and trigger().
bool ripple::InboundLedger::mHaveBase private
Definition at line 133 of file InboundLedger.h.
Referenced by getJson(), getNeededHashes(), isBase(), processData(), takeAsNode(), takeAsRootNode(), takeBase(), takeTxNode(), takeTxRootNode(), trigger(), and tryLocal().
bool ripple::InboundLedger::mHaveState private
Definition at line 134 of file InboundLedger.h.
Referenced by getJson(), getNeededHashes(), isAcctStComplete(), processData(), takeAsNode(), takeAsRootNode(), takeBase(), takeTxNode(), takeTxRootNode(), trigger(), and tryLocal().
bool ripple::InboundLedger::mHaveTransactions private
Definition at line 135 of file InboundLedger.h.
Referenced by getJson(), getNeededHashes(), isTransComplete(), processData(), takeAsNode(), takeBase(), takeTxNode(), trigger(), and tryLocal().
Ledger::pointer ripple::InboundLedger::mLedger private
Definition at line 132 of file InboundLedger.h.
Referenced by done(), getJson(), getLedger(), getNeededHashes(), init(), takeAsNode(), takeAsRootNode(), takeBase(), takeTxNode(), takeTxRootNode(), trigger(), and tryLocal().
std::vector<std::function <void (InboundLedger::pointer)> > ripple::InboundLedger::mOnComplete private
Definition at line 151 of file InboundLedger.h.
Referenced by addOnComplete(), and done().
fcReason ripple::InboundLedger::mReason private
Definition at line 140 of file InboundLedger.h.
Referenced by init().
std::vector<PeerDataPairType> ripple::InboundLedger::mReceivedData private
Definition at line 148 of file InboundLedger.h.
Referenced by gotData(), runData(), and ~InboundLedger().
PeerSet::LockType ripple::InboundLedger::mReceivedDataLock private
Definition at line 147 of file InboundLedger.h.
Referenced by gotData(), and runData().
bool ripple::InboundLedger::mReceiveDispatched private
Definition at line 149 of file InboundLedger.h.
Referenced by gotData(), and runData().
std::set<SHAMapNode> ripple::InboundLedger::mRecentASNodes private
Definition at line 143 of file InboundLedger.h.
Referenced by onTimer(), and trigger().
std::set<SHAMapNode> ripple::InboundLedger::mRecentTXNodes private
Definition at line 142 of file InboundLedger.h.
Referenced by onTimer(), and trigger().
std::uint32_t ripple::InboundLedger::mSeq private
Definition at line 139 of file InboundLedger.h.
Referenced by addPeers(), getSeq(), onTimer(), and trigger().
bool ripple::InboundLedger::mSignaled private
Definition at line 137 of file InboundLedger.h.
Referenced by done().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/ledger/InboundLedger.h
rippled/src/ripple_app/ledger/InboundLedger.cpp