rippled: ripple::Offer Class Reference
ripple::Offer Class Reference
#include <Offer.h>
Public Member Functions
Offer ()
virtual ~Offer ()
AccountItem::pointer makeItem (const uint160 &, SerializedLedgerEntry::ref ledgerEntry)
LedgerEntryType getType ()
const STAmount & getTakerPays ()
const STAmount & getTakerGets ()
const RippleAddress & getAccount ()
int getSeq ()
Json::Value getJson (int)
Public Member Functions inherited from ripple::AccountItem
AccountItem ()
AccountItem (SerializedLedgerEntry::ref ledger)
virtual ~AccountItem ()
SerializedLedgerEntry::pointer getSLE ()
const SerializedLedgerEntry & peekSLE () const
SerializedLedgerEntry & peekSLE ()
Blob getRaw () const
Private Member Functions
Offer (SerializedLedgerEntry::pointer ledgerEntry)
Private Attributes
RippleAddress mAccount
STAmount mTakerGets
STAmount mTakerPays
int mSeq
Additional Inherited Members
Public Types inherited from ripple::AccountItem
typedef boost::shared_ptr
< AccountItem > pointer
typedef const pointer & ref
Protected Attributes inherited from ripple::AccountItem
SerializedLedgerEntry::pointer mLedgerEntry
Detailed Description
Definition at line 25 of file Offer.h.
Constructor & Destructor Documentation
ripple::Offer::Offer () inline
Definition at line 28 of file Offer.h.
Referenced by makeItem().
 {}
virtual ripple::Offer::~Offer () inline virtual
Definition at line 30 of file Offer.h.
 {}
ripple::Offer::Offer (SerializedLedgerEntry::pointer ledgerEntry) explicit private
Definition at line 30 of file Offer.cpp.
                                                       : AccountItem (ledgerEntry),
     mAccount (mLedgerEntry->getFieldAccount (sfAccount)),
     mTakerGets (mLedgerEntry->getFieldAmount (sfTakerGets)),
     mTakerPays (mLedgerEntry->getFieldAmount (sfTakerPays)),
     mSeq (mLedgerEntry->getFieldU32 (sfSequence))
 {
     ;
 }
Member Function Documentation
const RippleAddress& ripple::Offer::getAccount () inline
Definition at line 47 of file Offer.h.
References mAccount.
     {
         return (mAccount);
     }
Json::Value ripple::Offer::getJson (int) virtual
Implements ripple::AccountItem.
Definition at line 39 of file Offer.cpp.
References ripple::STAmount::getFullText(), getTakerGets(), getTakerPays(), ripple::RippleAddress::humanAccountID(), mAccount, and Json::objectValue.
 {
     Json::Value ret (Json::objectValue);
     ret["account"] = mAccount.humanAccountID ();
     ret["taker_gets"] = getTakerGets ().getFullText ();
     ret["taker_pays"] = getTakerPays ().getFullText ();
     return ret;
 }
int ripple::Offer::getSeq () inline
Definition at line 51 of file Offer.h.
References mSeq.
     {
         return (mSeq);
     }
const STAmount& ripple::Offer::getTakerGets () inline
Definition at line 43 of file Offer.h.
References mTakerGets.
Referenced by getJson().
     {
         return (mTakerGets);
     }
const STAmount& ripple::Offer::getTakerPays () inline
Definition at line 39 of file Offer.h.
References mTakerPays.
Referenced by getJson().
     {
         return (mTakerPays);
     }
LedgerEntryType ripple::Offer::getType () inline virtual
Implements ripple::AccountItem.
Definition at line 34 of file Offer.h.
References ripple::ltOFFER.
     {
         return (ltOFFER);
     }
AccountItem::pointer ripple::Offer::makeItem (const uint160 & , SerializedLedgerEntry::ref ledgerEntry) virtual
Implements ripple::AccountItem.
Definition at line 22 of file Offer.cpp.
References ripple::ltOFFER, and Offer().
 {
     if (!ledgerEntry || ledgerEntry->getType () != ltOFFER) return (AccountItem::pointer ());
     Offer* offer = new Offer (ledgerEntry);
     return (AccountItem::pointer (offer));
 }
Member Data Documentation
RippleAddress ripple::Offer::mAccount private
Definition at line 62 of file Offer.h.
Referenced by getAccount(), and getJson().
int ripple::Offer::mSeq private
Definition at line 65 of file Offer.h.
Referenced by getSeq().
STAmount ripple::Offer::mTakerGets private
Definition at line 63 of file Offer.h.
Referenced by getTakerGets().
STAmount ripple::Offer::mTakerPays private
Definition at line 64 of file Offer.h.
Referenced by getTakerPays().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/misc/Offer.h
rippled/src/ripple_app/misc/Offer.cpp