rippled: ripple::JsonPropertyStream Class Reference
ripple::JsonPropertyStream Class Reference
#include <JsonPropertyStream.h>
Public Member Functions
JsonPropertyStream ()
Json::Value const & top () const
Public Member Functions inherited from beast::PropertyStream
PropertyStream ()
virtual ~PropertyStream ()
Public Attributes
Json::Value m_top
std::vector< Json::Value * > m_stack
Protected Member Functions
void map_begin ()
void map_begin (std::string const &key)
void map_end ()
void add (std::string const &key, short value)
void add (std::string const &key, unsigned short value)
void add (std::string const &key, int value)
void add (std::string const &key, unsigned int value)
void add (std::string const &key, long value)
void add (std::string const &key, float v)
void add (std::string const &key, double v)
void add (std::string const &key, std::string const &v)
void array_begin ()
void array_begin (std::string const &key)
void array_end ()
void add (short value)
void add (unsigned short value)
void add (int value)
void add (unsigned int value)
void add (long value)
void add (float v)
void add (double v)
void add (std::string const &v)
Protected Member Functions inherited from beast::PropertyStream
void add (std::string const &key, char const *value)
template<typename Value >
void lexical_add (std::string const &key, Value value)
virtual void add (std::string const &key, bool value)
virtual void add (std::string const &key, char value)
virtual void add (std::string const &key, signed char value)
virtual void add (std::string const &key, unsigned char value)
virtual void add (std::string const &key, wchar_t value)
virtual void add (std::string const &key, unsigned long value)
virtual void add (std::string const &key, long long value)
virtual void add (std::string const &key, unsigned long long value)
virtual void add (std::string const &key, long double value)
void add (char const *value)
template<typename Value >
void lexical_add (Value value)
virtual void add (bool value)
virtual void add (char value)
virtual void add (signed char value)
virtual void add (unsigned char value)
virtual void add (wchar_t value)
virtual void add (unsigned long value)
virtual void add (long long value)
virtual void add (unsigned long long value)
virtual void add (long double value)
Detailed Description
A PropertyStream::Sink which produces a Json::Value.
Definition at line 28 of file JsonPropertyStream.h.
Constructor & Destructor Documentation
ripple::JsonPropertyStream::JsonPropertyStream ()
Definition at line 22 of file JsonPropertyStream.cpp.
References m_stack, and m_top.
     : m_top (Json::objectValue)
 {
     m_stack.reserve (64);
     m_stack.push_back (&m_top);
 }
Member Function Documentation
void ripple::JsonPropertyStream::add (std::string const & key, short value) protected virtual
Reimplemented from beast::PropertyStream.
Definition at line 55 of file JsonPropertyStream.cpp.
References m_stack.
 {
     (*m_stack.back())[key] = v;
 }
void ripple::JsonPropertyStream::add (std::string const & key, unsigned short value) protected virtual
Reimplemented from beast::PropertyStream.
Definition at line 60 of file JsonPropertyStream.cpp.
References m_stack.
 {
     (*m_stack.back())[key] = v;
 }
void ripple::JsonPropertyStream::add (std::string const & key, int value) protected virtual
Reimplemented from beast::PropertyStream.
Definition at line 65 of file JsonPropertyStream.cpp.
References m_stack.
 {
     (*m_stack.back())[key] = v;
 }
void ripple::JsonPropertyStream::add (std::string const & key, unsigned int value) protected virtual
Reimplemented from beast::PropertyStream.
Definition at line 70 of file JsonPropertyStream.cpp.
References m_stack.
 {
     (*m_stack.back())[key] = v;
 }
void ripple::JsonPropertyStream::add (std::string const & key, long value) protected virtual
Reimplemented from beast::PropertyStream.
Definition at line 75 of file JsonPropertyStream.cpp.
References m_stack.
 {
     (*m_stack.back())[key] = int(v);
 }
void ripple::JsonPropertyStream::add (std::string const & key, float v) protected virtual
Reimplemented from beast::PropertyStream.
Definition at line 80 of file JsonPropertyStream.cpp.
References m_stack.
 {
     (*m_stack.back())[key] = v;
 }
void ripple::JsonPropertyStream::add (std::string const & key, double v) protected virtual
Reimplemented from beast::PropertyStream.
Definition at line 85 of file JsonPropertyStream.cpp.
References m_stack.
 {
     (*m_stack.back())[key] = v;
 }
void ripple::JsonPropertyStream::add (std::string const & key, std::string const & v) protected virtual
Implements beast::PropertyStream.
Definition at line 90 of file JsonPropertyStream.cpp.
References m_stack.
 {
     (*m_stack.back())[key] = v;
 }
void ripple::JsonPropertyStream::add (short value) protected virtual
Reimplemented from beast::PropertyStream.
Definition at line 116 of file JsonPropertyStream.cpp.
References m_stack.
 {
     m_stack.back()->append (v);
 }
void ripple::JsonPropertyStream::add (unsigned short value) protected virtual
Reimplemented from beast::PropertyStream.
Definition at line 121 of file JsonPropertyStream.cpp.
References m_stack.
 {
     m_stack.back()->append (v);
 }
void ripple::JsonPropertyStream::add (int value) protected virtual
Reimplemented from beast::PropertyStream.
Definition at line 126 of file JsonPropertyStream.cpp.
References m_stack.
 {
     m_stack.back()->append (v);
 }
void ripple::JsonPropertyStream::add (unsigned int value) protected virtual
Reimplemented from beast::PropertyStream.
Definition at line 131 of file JsonPropertyStream.cpp.
References m_stack.
 {
     m_stack.back()->append (v);
 }
void ripple::JsonPropertyStream::add (long value) protected virtual
Reimplemented from beast::PropertyStream.
Definition at line 136 of file JsonPropertyStream.cpp.
References m_stack.
 {
     m_stack.back()->append (int (v));
 }
void ripple::JsonPropertyStream::add (float v) protected virtual
Reimplemented from beast::PropertyStream.
Definition at line 141 of file JsonPropertyStream.cpp.
References m_stack.
 {
     m_stack.back()->append (v);
 }
void ripple::JsonPropertyStream::add (double v) protected virtual
Reimplemented from beast::PropertyStream.
Definition at line 146 of file JsonPropertyStream.cpp.
References m_stack.
 {
     m_stack.back()->append (v);
 }
void ripple::JsonPropertyStream::add (std::string const & v) protected virtual
Implements beast::PropertyStream.
Definition at line 151 of file JsonPropertyStream.cpp.
References m_stack.
 {
     m_stack.back()->append (v);
 }
void ripple::JsonPropertyStream::array_begin () protected virtual
Implements beast::PropertyStream.
Definition at line 95 of file JsonPropertyStream.cpp.
References Json::Value::append(), Json::arrayValue, m_stack, and top().
 {
     // top is array
     Json::Value& top (*m_stack.back());
     Json::Value& vec (top.append (Json::arrayValue));
     m_stack.push_back (&vec);
 }
void ripple::JsonPropertyStream::array_begin (std::string const & key) protected virtual
Implements beast::PropertyStream.
Definition at line 103 of file JsonPropertyStream.cpp.
References Json::arrayValue, m_stack, and top().
 {
     // top is a map
     Json::Value& top (*m_stack.back());
     Json::Value& vec (top [key] = Json::arrayValue);
     m_stack.push_back (&vec);
 }
void ripple::JsonPropertyStream::array_end () protected virtual
Implements beast::PropertyStream.
Definition at line 111 of file JsonPropertyStream.cpp.
References m_stack.
 {
     m_stack.pop_back ();
 }
void ripple::JsonPropertyStream::map_begin () protected virtual
Implements beast::PropertyStream.
Definition at line 34 of file JsonPropertyStream.cpp.
References Json::Value::append(), m_stack, Json::objectValue, and top().
 {
     // top is array
     Json::Value& top (*m_stack.back());
     Json::Value& map (top.append (Json::objectValue));
     m_stack.push_back (&map);
 }
void ripple::JsonPropertyStream::map_begin (std::string const & key) protected virtual
Implements beast::PropertyStream.
Definition at line 42 of file JsonPropertyStream.cpp.
References m_stack, Json::objectValue, and top().
 {
     // top is a map
     Json::Value& top (*m_stack.back());
     Json::Value& map (top [key] = Json::objectValue);
     m_stack.push_back (&map);
 }
void ripple::JsonPropertyStream::map_end () protected virtual
Implements beast::PropertyStream.
Definition at line 50 of file JsonPropertyStream.cpp.
References m_stack.
 {
     m_stack.pop_back ();
 }
Json::Value const & ripple::JsonPropertyStream::top () const
Definition at line 29 of file JsonPropertyStream.cpp.
References m_top.
Referenced by array_begin(), ripple::RPCHandler::doPrint(), map_begin(), and ripple::RPC::DoPrint::operator()().
 {
     return m_top;
 }
Member Data Documentation
std::vector<Json::Value*> ripple::JsonPropertyStream::m_stack
Definition at line 32 of file JsonPropertyStream.h.
Referenced by add(), array_begin(), array_end(), JsonPropertyStream(), map_begin(), and map_end().
Json::Value ripple::JsonPropertyStream::m_top
Definition at line 31 of file JsonPropertyStream.h.
Referenced by JsonPropertyStream(), and top().
The documentation for this class was generated from the following files:
rippled/src/ripple/json/api/JsonPropertyStream.h
rippled/src/ripple/json/impl/JsonPropertyStream.cpp