rippled: rippled/src/ripple/rocksdb/rocksdb/utilities/redis/redis_lists_test.cc File Reference
redis_lists_test.cc File Reference
#include <iostream>
#include <cctype>
#include "redis_lists.h"
#include "util/testharness.h"
#include "util/random.h"
Classes
class rocksdb::RedisListsTest
Namespaces
rocksdb
Constant Groups
rocksdb
Functions
void rocksdb::AssertListEq (const std::vector< std::string > &result, const std::vector< std::string > &expected_result)
rocksdb::TEST (RedisListsTest, SimpleTest)
rocksdb::TEST (RedisListsTest, SimpleTest2)
rocksdb::TEST (RedisListsTest, IndexTest)
rocksdb::TEST (RedisListsTest, RangeTest)
rocksdb::TEST (RedisListsTest, InsertTest)
rocksdb::TEST (RedisListsTest, SetTest)
rocksdb::TEST (RedisListsTest, InsertPushSetTest)
rocksdb::TEST (RedisListsTest, TrimPopTest)
rocksdb::TEST (RedisListsTest, RemoveTest)
rocksdb::TEST (RedisListsTest, PersistenceMultiKeyTest)
void rocksdb::MakeUpper (std::string *const s)
int rocksdb::manual_redis_test (bool destructive)
bool found_arg (int argc, char *argv[], const char *want)
int main (int argc, char *argv[])
Function Documentation
bool found_arg (int argc, char * argv[], const char * want)
Definition at line 855 of file redis_lists_test.cc.
Referenced by main().
{
   for(int i=1; i<argc; ++i){
     if (strcmp(argv[i], want) == 0) {
       return true;
     }
   }
   return false;
 }
int main (int argc, char * argv[])
Definition at line 867 of file redis_lists_test.cc.
References found_arg(), rocksdb::manual_redis_test(), and rocksdb::test::RunAllTests().
{
   if (found_arg(argc, argv, "-m")) {
     bool destructive = found_arg(argc, argv, "-d");
     return rocksdb::manual_redis_test(destructive);
   } else {
     return rocksdb::test::RunAllTests();
   }
 }