rippled: rocksdb::UtilityDB Class Reference
rocksdb::UtilityDB Class Reference
#include <utility_db.h>
Static Public Member Functions
static Status OpenTtlDB (const Options &options, const std::string &name, StackableDB **dbptr, int32_t ttl=0, bool read_only=false)
Detailed Description
Definition at line 11 of file utility_db.h.
Member Function Documentation
Status rocksdb::UtilityDB::OpenTtlDB (const Options & options, const std::string & name, StackableDB ** dbptr, int32_t ttl = 0, bool read_only = false) static
Definition at line 49 of file db_ttl.cc.
References rocksdb::Status::ok().
Referenced by rocksdb::StressTest::Open(), rocksdb::LDBCommand::OpenDB(), rocksdb::TtlTest::OpenReadOnlyTtl(), and rocksdb::TtlTest::OpenTtl().
                     {
   Status st;
   *dbptr = new DBWithTTL(ttl, options, dbname, st, read_only);
   if (!st.ok()) {
     delete *dbptr;
   }
   return st;
 }
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/include/utilities/utility_db.h
rippled/src/ripple/rocksdb/rocksdb/utilities/ttl/db_ttl.cc