rippled: ripple::STPathElement Class Reference
ripple::STPathElement Class Reference
#include <SerializedTypes.h>
Public Types
enum {
typeEnd = 0x00, typeAccount = 0x01, typeCurrency = 0x10, typeIssuer = 0x20,
typeBoundary = 0xFF, typeValidBits
}
Public Member Functions
STPathElement (const uint160 &uAccountID, const uint160 &uCurrencyID, const uint160 &uIssuerID, bool forceCurrency=false)
STPathElement (unsigned int uType, const uint160 &uAccountID, const uint160 &uCurrencyID, const uint160 &uIssuerID)
STPathElement ()
int getNodeType () const
bool isOffer () const
bool isAccount () const
const uint160 & getAccountID () const
const uint160 & getCurrency () const
const uint160 & getIssuerID () const
bool operator== (const STPathElement &t) const
Private Attributes
unsigned int mType
uint160 mAccountID
uint160 mCurrencyID
uint160 mIssuerID
Friends
class STPathSet
class STPath
class Pathfinder
Detailed Description
Definition at line 1184 of file SerializedTypes.h.
Member Enumeration Documentation
anonymous enum
Enumerator
typeEnd
typeAccount
typeCurrency
typeIssuer
typeBoundary
typeValidBits
Definition at line 1193 of file SerializedTypes.h.
     {
         typeEnd         = 0x00,
         typeAccount     = 0x01, // Rippling through an account (vs taking an offer).
         typeCurrency    = 0x10, // Currency follows.
         typeIssuer      = 0x20, // Issuer follows.
         typeBoundary    = 0xFF, // Boundary between alternate paths.
         typeValidBits   = (
                               typeAccount
                               | typeCurrency
                               | typeIssuer
                           ),  // Bits that may be non-zero.
     };
Constructor & Destructor Documentation
ripple::STPathElement::STPathElement (const uint160 & uAccountID, const uint160 & uCurrencyID, const uint160 & uIssuerID, bool forceCurrency = false) inline
Definition at line 1208 of file SerializedTypes.h.
References ripple::base_uint< BITS >::isZero(), mType, typeAccount, typeCurrency, and typeIssuer.
         : mAccountID (uAccountID), mCurrencyID (uCurrencyID), mIssuerID (uIssuerID)
     {
         mType   =
             (uAccountID.isZero () ? 0 : STPathElement::typeAccount)
             | ((uCurrencyID.isZero () && !forceCurrency) ? 0 : STPathElement::typeCurrency)
             | (uIssuerID.isZero () ? 0 : STPathElement::typeIssuer);
     }
ripple::STPathElement::STPathElement (unsigned int uType, const uint160 & uAccountID, const uint160 & uCurrencyID, const uint160 & uIssuerID) inline
Definition at line 1218 of file SerializedTypes.h.
         : mType (uType), mAccountID (uAccountID), mCurrencyID (uCurrencyID), mIssuerID (uIssuerID)
     {
         ;
     }
ripple::STPathElement::STPathElement () inline
Definition at line 1224 of file SerializedTypes.h.
         : mType (0)
     {
         ;
     }
Member Function Documentation
const uint160& ripple::STPathElement::getAccountID () const inline
Definition at line 1244 of file SerializedTypes.h.
References mAccountID.
Referenced by ripple::STPathSet::add(), ripple::STPath::hasSeen(), and ripple::PathState::setExpanded().
     {
         return mAccountID;
     }
const uint160& ripple::STPathElement::getCurrency () const inline
Definition at line 1248 of file SerializedTypes.h.
References mCurrencyID.
Referenced by ripple::STPathSet::add(), ripple::STPath::hasSeen(), and ripple::PathState::setExpanded().
     {
         return mCurrencyID;
     }
const uint160& ripple::STPathElement::getIssuerID () const inline
Definition at line 1252 of file SerializedTypes.h.
References mIssuerID.
Referenced by ripple::STPathSet::add(), ripple::STPath::hasSeen(), and ripple::PathState::setExpanded().
     {
         return mIssuerID;
     }
int ripple::STPathElement::getNodeType () const inline
Definition at line 1230 of file SerializedTypes.h.
References mType.
Referenced by ripple::STPathSet::add(), ripple::Pathfinder::isNoRippleOut(), and ripple::PathState::setExpanded().
     {
         return mType;
     }
bool ripple::STPathElement::isAccount () const inline
Definition at line 1238 of file SerializedTypes.h.
References isOffer().
     {
         return !isOffer ();
     }
bool ripple::STPathElement::isOffer () const inline
Definition at line 1234 of file SerializedTypes.h.
References ripple::base_uint< BITS >::isZero(), and mAccountID.
Referenced by isAccount().
     {
         return mAccountID.isZero ();
     }
bool ripple::STPathElement::operator== (const STPathElement & t) const inline
Definition at line 1257 of file SerializedTypes.h.
References mAccountID, mCurrencyID, mIssuerID, mType, and typeAccount.
     {
         return ((mType & typeAccount) == (t.mType & typeAccount)) &&
             (mAccountID == t.mAccountID) && (mCurrencyID == t.mCurrencyID) && (mIssuerID == t.mIssuerID);
     }
Friends And Related Function Documentation
friend class Pathfinder friend
Definition at line 1190 of file SerializedTypes.h.
friend class STPath friend
Definition at line 1189 of file SerializedTypes.h.
friend class STPathSet friend
Definition at line 1188 of file SerializedTypes.h.
Referenced by ripple::STPathSet::duplicate().
Member Data Documentation
uint160 ripple::STPathElement::mAccountID private
Definition at line 1265 of file SerializedTypes.h.
Referenced by ripple::Pathfinder::addLink(), getAccountID(), ripple::Pathfinder::isNoRippleOut(), isOffer(), and operator==().
uint160 ripple::STPathElement::mCurrencyID private
Definition at line 1266 of file SerializedTypes.h.
Referenced by ripple::Pathfinder::addLink(), getCurrency(), ripple::Pathfinder::isNoRippleOut(), and operator==().
uint160 ripple::STPathElement::mIssuerID private
Definition at line 1267 of file SerializedTypes.h.
Referenced by ripple::Pathfinder::addLink(), getIssuerID(), and operator==().
unsigned int ripple::STPathElement::mType private
Definition at line 1264 of file SerializedTypes.h.
Referenced by getNodeType(), operator==(), and STPathElement().
The documentation for this class was generated from the following file:
rippled/src/ripple_data/protocol/SerializedTypes.h