rippled: ripple::NodeStore::NodeStoreTiming_test::Stopwatch Class Reference
ripple::NodeStore::NodeStoreTiming_test::Stopwatch Class Reference
Public Member Functions
Stopwatch ()
void start ()
double getElapsed ()
Private Attributes
std::int64_t m_startTime
Detailed Description
Definition at line 31 of file TimingTests.cpp.
Constructor & Destructor Documentation
ripple::NodeStore::NodeStoreTiming_test::Stopwatch::Stopwatch () inline
Definition at line 34 of file TimingTests.cpp.
         {
         }
Member Function Documentation
double ripple::NodeStore::NodeStoreTiming_test::Stopwatch::getElapsed () inline
Definition at line 43 of file TimingTests.cpp.
References beast::Time::getHighResolutionTicks(), beast::Time::highResolutionTicksToSeconds(), and m_startTime.
         {
             std::int64_t const now = beast::Time::getHighResolutionTicks();
             return beast::Time::highResolutionTicksToSeconds (now - m_startTime);
         }
void ripple::NodeStore::NodeStoreTiming_test::Stopwatch::start () inline
Definition at line 38 of file TimingTests.cpp.
References beast::Time::getHighResolutionTicks(), and m_startTime.
         {
             m_startTime = beast::Time::getHighResolutionTicks ();
         }
Member Data Documentation
std::int64_t ripple::NodeStore::NodeStoreTiming_test::Stopwatch::m_startTime private
Definition at line 51 of file TimingTests.cpp.
Referenced by getElapsed(), and start().
The documentation for this class was generated from the following file:
rippled/src/ripple_core/nodestore/tests/TimingTests.cpp