rippled: rocksdb::MemTableIterator Class Reference
rocksdb::MemTableIterator Class Reference
Public Member Functions
MemTableIterator (MemTableRep *table, const ReadOptions &options)
virtual bool Valid () const
virtual void Seek (const Slice &k)
virtual void SeekToFirst ()
virtual void SeekToLast ()
virtual void Next ()
virtual void Prev ()
virtual Slice key () const
virtual Slice value () const
virtual Status status () const
Public Member Functions inherited from rocksdb::Iterator
Iterator ()
virtual ~Iterator ()
void RegisterCleanup (CleanupFunction function, void *arg1, void *arg2)
Private Member Functions
MemTableIterator (const MemTableIterator &)
void operator= (const MemTableIterator &)
Private Attributes
std::shared_ptr
< MemTableRep::Iterator > iter_
std::string tmp_
Additional Inherited Members
Public Types inherited from rocksdb::Iterator
typedef void(* CleanupFunction)(void *arg1, void *arg2)
Detailed Description
Definition at line 88 of file memtable.cc.
Constructor & Destructor Documentation
rocksdb::MemTableIterator::MemTableIterator (MemTableRep * table, const ReadOptions & options) inline
Definition at line 90 of file memtable.cc.
References rocksdb::MemTableRep::GetDynamicPrefixIterator(), rocksdb::MemTableRep::GetIterator(), rocksdb::MemTableRep::GetPrefixIterator(), iter_, rocksdb::ReadOptions::prefix, and rocksdb::ReadOptions::prefix_seek.
     : iter_() {
     if (options.prefix) {
       iter_ = table->GetPrefixIterator(*options.prefix);
     } else if (options.prefix_seek) {
       iter_ = table->GetDynamicPrefixIterator();
     } else {
       iter_ = table->GetIterator();
     }
   }
rocksdb::MemTableIterator::MemTableIterator (const MemTableIterator &) private
Member Function Documentation
virtual Slice rocksdb::MemTableIterator::key () const inline virtual
Implements rocksdb::Iterator.
Definition at line 107 of file memtable.cc.
References rocksdb::GetLengthPrefixedSlice(), and iter_.
{
     return GetLengthPrefixedSlice(iter_->key());
   }
virtual void rocksdb::MemTableIterator::Next () inline virtual
Implements rocksdb::Iterator.
Definition at line 105 of file memtable.cc.
References iter_.
 { iter_->Next(); }
void rocksdb::MemTableIterator::operator= (const MemTableIterator &) private
virtual void rocksdb::MemTableIterator::Prev () inline virtual
Implements rocksdb::Iterator.
Definition at line 106 of file memtable.cc.
References iter_.
 { iter_->Prev(); }
virtual void rocksdb::MemTableIterator::Seek (const Slice & k) inline virtual
Implements rocksdb::Iterator.
Definition at line 102 of file memtable.cc.
References rocksdb::EncodeKey(), and iter_.
 { iter_->Seek(EncodeKey(&tmp_, k)); }
virtual void rocksdb::MemTableIterator::SeekToFirst () inline virtual
Implements rocksdb::Iterator.
Definition at line 103 of file memtable.cc.
References iter_.
 { iter_->SeekToFirst(); }
virtual void rocksdb::MemTableIterator::SeekToLast () inline virtual
Implements rocksdb::Iterator.
Definition at line 104 of file memtable.cc.
References iter_.
 { iter_->SeekToLast(); }
virtual Status rocksdb::MemTableIterator::status () const inline virtual
Implements rocksdb::Iterator.
Definition at line 115 of file memtable.cc.
References rocksdb::Status::OK().
 { return Status::OK(); }
virtual bool rocksdb::MemTableIterator::Valid () const inline virtual
Implements rocksdb::Iterator.
Definition at line 101 of file memtable.cc.
References iter_.
 { return iter_->Valid(); }
virtual Slice rocksdb::MemTableIterator::value () const inline virtual
Implements rocksdb::Iterator.
Definition at line 110 of file memtable.cc.
References rocksdb::Slice::data(), rocksdb::GetLengthPrefixedSlice(), iter_, and rocksdb::Slice::size().
{
     Slice key_slice = GetLengthPrefixedSlice(iter_->key());
     return GetLengthPrefixedSlice(key_slice.data() + key_slice.size());
   }
Member Data Documentation
std::shared_ptr<MemTableRep::Iterator> rocksdb::MemTableIterator::iter_ private
Definition at line 118 of file memtable.cc.
std::string rocksdb::MemTableIterator::tmp_ private
Definition at line 119 of file memtable.cc.
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/db/memtable.cc