rippled: ripple::RPCServerImp Class Reference
ripple::RPCServerImp Class Reference
#include <RPCServerImp.h>
Public Types
enum { maxQueryBytes = 1024 * 1024 }
typedef boost::shared_ptr
< RPCServerImp > pointer
Public Member Functions
RPCServerImp (boost::asio::io_service &io_service, boost::asio::ssl::context &context, Handler &handler)
void connected ()
void handle_write (const boost::system::error_code &e)
void handle_read_line (const boost::system::error_code &e)
void handle_read_req (const boost::system::error_code &ec)
void handle_shutdown (const boost::system::error_code &ec)
std::string handleRequest (const std::string &request)
AutoSocket & getSocket ()
boost::asio::ip::tcp::socket & getRawSocket ()
boost::asio::ip::tcp::socket::endpoint_type & getRemoteEndpoint ()
Public Member Functions inherited from ripple::RPCServer
virtual ~RPCServer ()
Private Attributes
Handler & m_handler
boost::asio::io_service::strand mStrand
AutoSocket mSocket
AutoSocket::endpoint_type m_remote_endpoint
boost::asio::streambuf mLineBuffer
Blob mQueryVec
std::string mReplyStr
HTTPRequest mHTTPRequest
Detailed Description
Definition at line 24 of file RPCServerImp.h.
Member Typedef Documentation
typedef boost::shared_ptr<RPCServerImp> ripple::RPCServerImp::pointer
Definition at line 30 of file RPCServerImp.h.
Member Enumeration Documentation
anonymous enum
Enumerator
maxQueryBytes
Definition at line 44 of file RPCServerImp.h.
     {
         maxQueryBytes = 1024 * 1024
     };
Constructor & Destructor Documentation
ripple::RPCServerImp::RPCServerImp (boost::asio::io_service & io_service, boost::asio::ssl::context & context, Handler & handler) inline
Definition at line 32 of file RPCServerImp.h.
         : m_handler (handler)
         , mStrand (io_service)
         , mSocket (io_service, context)
     {
     }
Member Function Documentation
void ripple::RPCServerImp::connected () inline virtual
Called when the connection is established.
Implements ripple::RPCServer.
Definition at line 49 of file RPCServerImp.h.
References handle_read_line().
     {
         boost::asio::async_read_until (
             mSocket,
             mLineBuffer,
             "\r\n",
             mStrand.wrap (boost::bind (
                 &RPCServerImp::handle_read_line,
                 boost::static_pointer_cast <RPCServerImp> (shared_from_this ()),
                 boost::asio::placeholders::error)));
     }
boost::asio::ip::tcp::socket& ripple::RPCServerImp::getRawSocket () inline virtual
Implements ripple::RPCServer.
Definition at line 238 of file RPCServerImp.h.
     {
         return mSocket.PlainSocket ();
     }
boost::asio::ip::tcp::socket::endpoint_type& ripple::RPCServerImp::getRemoteEndpoint () inline virtual
Implements ripple::RPCServer.
Definition at line 243 of file RPCServerImp.h.
     {
         return m_remote_endpoint;
     }
AutoSocket& ripple::RPCServerImp::getSocket () inline
Definition at line 231 of file RPCServerImp.h.
     {
         return mSocket;
     }
void ripple::RPCServerImp::handle_read_line (const boost::system::error_code & e) inline
Definition at line 99 of file RPCServerImp.h.
References ripple::HTTPRequest::haDO_REQUEST, handle_read_req(), handle_shutdown(), ripple::HTTPRequest::haREAD_LINE, ripple::HTTPRequest::haREAD_RAW, ripple::lsTRACE, ripple::lsWARNING, and WriteLog.
Referenced by connected(), and handle_write().
     {
         if (! e)
         {
             HTTPRequest::Action action = mHTTPRequest.consume (mLineBuffer);
             if (action == HTTPRequest::haDO_REQUEST)
             {
                 // request with no body
                 WriteLog (lsWARNING, RPCServer) << "RPC HTTP request with no body";
                 mSocket.async_shutdown (mStrand.wrap (boost::bind (
                     &RPCServerImp::handle_shutdown,
                     boost::static_pointer_cast <RPCServerImp> (shared_from_this ()),
                     boost::asio::placeholders::error)));
             }
             else if (action == HTTPRequest::haREAD_LINE)
             {
                 boost::asio::async_read_until (
                     mSocket,
                     mLineBuffer,
                     "\r\n",
                     mStrand.wrap (boost::bind (
                         &RPCServerImp::handle_read_line,
                         boost::static_pointer_cast <RPCServerImp> (shared_from_this ()),
                         boost::asio::placeholders::error)));
             }
             else if (action == HTTPRequest::haREAD_RAW)
             {
                 int rLen = mHTTPRequest.getDataSize ();
                 if ((rLen < 0) || (rLen > maxQueryBytes))
                 {
                     WriteLog (lsWARNING, RPCServer) << "Illegal RPC request length " << rLen;
                     mSocket.async_shutdown (mStrand.wrap (boost::bind (
                         &RPCServerImp::handle_shutdown,
                         boost::static_pointer_cast <RPCServerImp> (shared_from_this ()),
                         boost::asio::placeholders::error)));
                 }
                 else
                 {
                     int alreadyHave = mLineBuffer.size ();
                     if (alreadyHave < rLen)
                     {
                         mQueryVec.resize (rLen - alreadyHave);
                         boost::asio::async_read (
                             mSocket,
                             boost::asio::buffer (mQueryVec),
                             mStrand.wrap (boost::bind (
                                 &RPCServerImp::handle_read_req,
                                 boost::static_pointer_cast <RPCServerImp> (shared_from_this ()),
                                 boost::asio::placeholders::error)));
                         WriteLog (lsTRACE, RPCServer) << "Waiting for completed request: " << rLen;
                     }
                     else
                     {
                         // we have the whole thing
                         mQueryVec.resize (0);
                         handle_read_req (e);
                     }
                 }
             }
             else
             {
                 mSocket.async_shutdown (mStrand.wrap (boost::bind (
                     &RPCServerImp::handle_shutdown,
                     boost::static_pointer_cast <RPCServerImp> (shared_from_this ()),
                     boost::asio::placeholders::error)));
             }
         }
     }
void ripple::RPCServerImp::handle_read_req (const boost::system::error_code & ec) inline
Definition at line 178 of file RPCServerImp.h.
References handle_write(), and ripple::strCopy().
Referenced by handle_read_line().
     {
         std::string req;
         if (mLineBuffer.size ())
         {
             req.assign (boost::asio::buffer_cast <const char*> (mLineBuffer.data ()), mLineBuffer.size ());
             mLineBuffer.consume (mLineBuffer.size ());
         }
         req += strCopy (mQueryVec);
         if (! m_handler.isAuthorized (mHTTPRequest.peekHeaders ()))
         {
             mReplyStr = m_handler.createResponse (403, "Forbidden");
         }
         else
         {
             mReplyStr = handleRequest (req);
         }
         boost::asio::async_write (
             mSocket,
             boost::asio::buffer (mReplyStr),
             mStrand.wrap (boost::bind (
                 &RPCServerImp::handle_write,
                 boost::static_pointer_cast <RPCServerImp> (shared_from_this ()),
                 boost::asio::placeholders::error)));
     }
void ripple::RPCServerImp::handle_shutdown (const boost::system::error_code & ec) inline
Definition at line 211 of file RPCServerImp.h.
Referenced by handle_read_line(), and handle_write().
     {
         // nothing to do, we just keep the object alive
     }
void ripple::RPCServerImp::handle_write (const boost::system::error_code & e) inline
Definition at line 63 of file RPCServerImp.h.
References ripple::HTTPRequest::haCLOSE_CONN, handle_read_line(), and handle_shutdown().
Referenced by handle_read_req().
     {
         if (!e)
         {
             HTTPRequest::Action action = mHTTPRequest.requestDone (false);
             if (action == HTTPRequest::haCLOSE_CONN)
             {
                 mSocket.async_shutdown (mStrand.wrap (boost::bind (
                     &RPCServerImp::handle_shutdown,
                     boost::static_pointer_cast <RPCServerImp> (shared_from_this()),
                     boost::asio::placeholders::error)));
             }
             else
             {
                 boost::asio::async_read_until (
                     mSocket,
                     mLineBuffer,
                     "\r\n",
                     mStrand.wrap (boost::bind (
                         &RPCServerImp::handle_read_line,
                         boost::static_pointer_cast <RPCServerImp> (shared_from_this()),
                         boost::asio::placeholders::error)));
             }
         }
         if (e != boost::asio::error::operation_aborted)
         {
             // VFALCO TODO What is this for? It was commented out.
             //
             //connection_manager_.stop (shared_from_this ());
         }
     }
std::string ripple::RPCServerImp::handleRequest (const std::string & request) inline
Definition at line 220 of file RPCServerImp.h.
References beast::IPAddressConversion::from_asio(), ripple::lsTRACE, and WriteLog.
     {
         WriteLog (lsTRACE, RPCServer) << "handleRequest " << request;
         return m_handler.processRequest (request,
             beast::IPAddressConversion::from_asio (
                 m_remote_endpoint.address()));
     }
Member Data Documentation
Handler& ripple::RPCServerImp::m_handler private
Definition at line 249 of file RPCServerImp.h.
AutoSocket::endpoint_type ripple::RPCServerImp::m_remote_endpoint private
Definition at line 253 of file RPCServerImp.h.
HTTPRequest ripple::RPCServerImp::mHTTPRequest private
Definition at line 259 of file RPCServerImp.h.
boost::asio::streambuf ripple::RPCServerImp::mLineBuffer private
Definition at line 255 of file RPCServerImp.h.
Blob ripple::RPCServerImp::mQueryVec private
Definition at line 256 of file RPCServerImp.h.
std::string ripple::RPCServerImp::mReplyStr private
Definition at line 257 of file RPCServerImp.h.
AutoSocket ripple::RPCServerImp::mSocket private
Definition at line 252 of file RPCServerImp.h.
boost::asio::io_service::strand ripple::RPCServerImp::mStrand private
Definition at line 251 of file RPCServerImp.h.
The documentation for this class was generated from the following file:
rippled/src/ripple_net/basics/impl/RPCServerImp.h