rippled: beast::LockFreeStackIterator< Container, IsConst > Class Template Reference
beast::LockFreeStackIterator< Container, IsConst > Class Template Reference
#include <LockFreeStack.h>
Public Types
typedef Container::value_type value_type
typedef std::conditional
< IsConst, typename
Container::const_pointer,
typename Container::pointer >
::type pointer
typedef std::conditional
< IsConst, typename
Container::const_reference,
typename Container::reference >
::type reference
Public Member Functions
LockFreeStackIterator ()
LockFreeStackIterator (NodePtr node)
template<bool OtherIsConst>
LockFreeStackIterator (LockFreeStackIterator< Container, OtherIsConst > const &other)
LockFreeStackIterator & operator= (NodePtr node)
LockFreeStackIterator & operator++ ()
LockFreeStackIterator operator++ (int)
NodePtr node () const
reference operator* () const
pointer operator-> () const
Protected Types
typedef Container::Node Node
typedef std::conditional
< IsConst, Node const *, Node * >
::type NodePtr
Private Attributes
NodePtr m_node
Detailed Description
template<class Container, bool IsConst>
class beast::LockFreeStackIterator< Container, IsConst >
Definition at line 34 of file LockFreeStack.h.
Member Typedef Documentation
template<class Container, bool IsConst> typedef Container::Node beast::LockFreeStackIterator< Container, IsConst >::Node protected
Definition at line 47 of file LockFreeStack.h.
template<class Container, bool IsConst> typedef std::conditional< IsConst, Node const*, Node*>::type beast::LockFreeStackIterator< Container, IsConst >::NodePtr protected
Definition at line 49 of file LockFreeStack.h.
template<class Container, bool IsConst> typedef std::conditional<IsConst, typename Container::const_pointer, typename Container::pointer>::type beast::LockFreeStackIterator< Container, IsConst >::pointer
Definition at line 55 of file LockFreeStack.h.
template<class Container, bool IsConst> typedef std::conditional<IsConst, typename Container::const_reference, typename Container::reference>::type beast::LockFreeStackIterator< Container, IsConst >::reference
Definition at line 58 of file LockFreeStack.h.
template<class Container, bool IsConst> typedef Container::value_type beast::LockFreeStackIterator< Container, IsConst >::value_type
Definition at line 52 of file LockFreeStack.h.
Constructor & Destructor Documentation
template<class Container, bool IsConst> beast::LockFreeStackIterator< Container, IsConst >::LockFreeStackIterator () inline
Definition at line 60 of file LockFreeStack.h.
         : m_node ()
     {
     }
template<class Container, bool IsConst> beast::LockFreeStackIterator< Container, IsConst >::LockFreeStackIterator (NodePtr node) inline
Definition at line 65 of file LockFreeStack.h.
         : m_node (node)
     {
     }
template<class Container, bool IsConst> template<bool OtherIsConst> beast::LockFreeStackIterator< Container, IsConst >::LockFreeStackIterator (LockFreeStackIterator< Container, OtherIsConst > const & other) inline explicit
Definition at line 71 of file LockFreeStack.h.
         : m_node (other.m_node)
     {
     }
Member Function Documentation
template<class Container, bool IsConst> NodePtr beast::LockFreeStackIterator< Container, IsConst >::node () const inline
Definition at line 95 of file LockFreeStack.h.
References beast::LockFreeStackIterator< Container, IsConst >::m_node.
Referenced by beast::operator!=(), beast::LockFreeStackIterator< Container, IsConst >::operator=(), and beast::operator==().
     {
         return m_node;
     }
template<class Container, bool IsConst> reference beast::LockFreeStackIterator< Container, IsConst >::operator* () const inline
Definition at line 100 of file LockFreeStack.h.
References beast::LockFreeStackIterator< Container, IsConst >::operator->().
     {
         return *this->operator-> ();
     }
template<class Container, bool IsConst> LockFreeStackIterator& beast::LockFreeStackIterator< Container, IsConst >::operator++ () inline
Definition at line 82 of file LockFreeStack.h.
References beast::LockFreeStackIterator< Container, IsConst >::m_node.
     {
         m_node = m_node->m_next.get();
         return static_cast <LockFreeStackIterator&> (*this);
     }
template<class Container, bool IsConst> LockFreeStackIterator beast::LockFreeStackIterator< Container, IsConst >::operator++ (int) inline
Definition at line 88 of file LockFreeStack.h.
References beast::LockFreeStackIterator< Container, IsConst >::m_node.
     {
         LockFreeStackIterator result (*this);
         m_node = m_node->m_next;
         return result;
     }
template<class Container, bool IsConst> pointer beast::LockFreeStackIterator< Container, IsConst >::operator-> () const inline
Definition at line 105 of file LockFreeStack.h.
References beast::LockFreeStackIterator< Container, IsConst >::m_node.
Referenced by beast::LockFreeStackIterator< Container, IsConst >::operator*().
     {
         return static_cast <pointer> (m_node);
     }
template<class Container, bool IsConst> LockFreeStackIterator& beast::LockFreeStackIterator< Container, IsConst >::operator= (NodePtr node) inline
Definition at line 76 of file LockFreeStack.h.
References beast::LockFreeStackIterator< Container, IsConst >::m_node, and beast::LockFreeStackIterator< Container, IsConst >::node().
     {
         m_node = node;
         return static_cast <LockFreeStackIterator&> (*this);
     }
Member Data Documentation
template<class Container, bool IsConst> NodePtr beast::LockFreeStackIterator< Container, IsConst >::m_node private
Definition at line 111 of file LockFreeStack.h.
Referenced by beast::LockFreeStackIterator< Container, IsConst >::node(), beast::LockFreeStackIterator< Container, IsConst >::operator++(), beast::LockFreeStackIterator< Container, IsConst >::operator->(), and beast::LockFreeStackIterator< Container, IsConst >::operator=().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/intrusive/LockFreeStack.h