rippled: leveldb_comparator_t Struct Reference
leveldb_comparator_t Struct Reference
Public Member Functions
virtual ~leveldb_comparator_t ()
virtual int Compare (const Slice &a, const Slice &b) const
virtual const char * Name () const
virtual void FindShortestSeparator (std::string *, const Slice &) const
virtual void FindShortSuccessor (std::string *key) const
Public Member Functions inherited from rocksdb::Comparator
virtual ~Comparator ()
Public Attributes
void * state_
void(* destructor_)(void *)
int(* compare_)(void *, const char *a, size_t alen, const char *b, size_t blen)
const char *(* name_)(void *)
Detailed Description
Definition at line 65 of file c.cc.
Constructor & Destructor Documentation
virtual leveldb_comparator_t::~leveldb_comparator_t () inline virtual
Definition at line 74 of file c.cc.
References state_.
{
     (*destructor_)(state_);
   }
Member Function Documentation
virtual int leveldb_comparator_t::Compare (const Slice & a, const Slice & b) const inline virtual
Implements rocksdb::Comparator.
Definition at line 78 of file c.cc.
References compare_, rocksdb::Slice::data(), rocksdb::Slice::size(), and state_.
{
     return (*compare_)(state_, a.data(), a.size(), b.data(), b.size());
   }
virtual void leveldb_comparator_t::FindShortestSeparator (std::string * , const Slice &) const inline virtual
Implements rocksdb::Comparator.
Definition at line 87 of file c.cc.
 { }
virtual void leveldb_comparator_t::FindShortSuccessor (std::string * key) const inline virtual
Implements rocksdb::Comparator.
Definition at line 88 of file c.cc.
 { }
virtual const char* leveldb_comparator_t::Name () const inline virtual
Implements rocksdb::Comparator.
Definition at line 82 of file c.cc.
References name_, and state_.
{
     return (*name_)(state_);
   }
Member Data Documentation
int(* leveldb_comparator_t::compare_)(void *, const char *a, size_t alen, const char *b, size_t blen)
Definition at line 68 of file c.cc.
Referenced by Compare(), and leveldb_comparator_create().
void(* leveldb_comparator_t::destructor_)(void *)
Definition at line 67 of file c.cc.
Referenced by leveldb_comparator_create().
const char*(* leveldb_comparator_t::name_)(void *)
Definition at line 72 of file c.cc.
Referenced by leveldb_comparator_create(), and Name().
void* leveldb_comparator_t::state_
Definition at line 66 of file c.cc.
Referenced by Compare(), leveldb_comparator_create(), Name(), and ~leveldb_comparator_t().
The documentation for this struct was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/db/c.cc