rippled: beast::SharedPtr< T > Class Template Reference
beast::SharedPtr< T > Class Template Reference
#include <SharedPtr.h>
Public Types
typedef T value_type
typedef T ReferencedType
Public Member Functions
SharedPtr () noexcept
~SharedPtr ()
bool empty () const noexcept
operator T * () const noexcept
T * operator-> () const noexcept
T * get () const noexcept
SharedPtr (T *t) noexcept
template<class U >
SharedPtr (U *u) noexcept
SharedPtr (SharedPtr const &sp) noexcept
template<class U >
SharedPtr (SharedPtr< U > const &sp) noexcept
SharedPtr & operator= (T *t)
template<class U >
SharedPtr & operator= (U *u)
SharedPtr & operator= (SharedPtr const &sp)
template<class U >
SharedPtr & operator= (SharedPtr< U > const &sp)
Private Member Functions
template<class U >
T * swap (U *u)
template<class U >
SharedPtr & assign (U *u)
Static Private Member Functions
template<class U >
static T * acquire (U *u) noexcept
static void release (T *t)
Private Attributes
T * m_p
Detailed Description
template<class T>
class beast::SharedPtr< T >
A smart-pointer container.
Requirement: T must support the SharedObject concept.
The template parameter specifies the class of the object you want to point to - the easiest way to make a class reference-countable is to simply make it inherit from SharedObject, but if you need to, you could roll your own reference-countable class by implementing a pair of methods called incReferenceCount() and decReferenceCount().
When using this class, you'll probably want to create a typedef to abbreviate the full templated name - e.g.
typedef SharedPtr <MyClass> MyClassPtr;
See Also
SharedObject, SharedObjectArray
Definition at line 63 of file SharedPtr.h.
Member Typedef Documentation
template<class T> typedef T beast::SharedPtr< T >::ReferencedType
The class being referenced by this container.
Definition at line 69 of file SharedPtr.h.
template<class T> typedef T beast::SharedPtr< T >::value_type
Definition at line 66 of file SharedPtr.h.
Constructor & Destructor Documentation
template<class T> beast::SharedPtr< T >::SharedPtr () inline noexcept
Construct a container pointing to nothing.
Definition at line 72 of file SharedPtr.h.
         : m_p (nullptr)
     {
     }
template<class T> beast::SharedPtr< T >::SharedPtr (T * t) inline noexcept
Construct a container holding an object. This will increment the object's reference-count if it is non-null. Requirement: U* must be convertible to T*
Definition at line 83 of file SharedPtr.h.
         : m_p (acquire (t))
     {
     }
template<class T> template<class U > beast::SharedPtr< T >::SharedPtr (U * u) inline noexcept
Definition at line 89 of file SharedPtr.h.
         : m_p (acquire (u))
     {
     }
template<class T> beast::SharedPtr< T >::SharedPtr (SharedPtr< T > const & sp) inline noexcept
Construct a container holding an object from another container. This will increment the object's reference-count (if it is non-null). Requirement: U* must be convertible to T*
Definition at line 102 of file SharedPtr.h.
         : m_p (acquire (sp.get ()))
     {
     }
template<class T> template<class U > beast::SharedPtr< T >::SharedPtr (SharedPtr< U > const & sp) inline noexcept
Definition at line 109 of file SharedPtr.h.
         : m_p (acquire (sp.get ()))
     {
     }
template<class T> beast::SharedPtr< T >::~SharedPtr () inline
Destroy the container and release the held reference, if any.
Definition at line 195 of file SharedPtr.h.
     {
         release (m_p);
     }
Member Function Documentation
template<class T> template<class U > static T* beast::SharedPtr< T >::acquire (U * u) inline static private noexcept
Definition at line 228 of file SharedPtr.h.
Referenced by beast::SharedPtr< beast::SharedSingleton< beast::sqdb::session::Sqlite3 > >::assign().
     {
         if (u != nullptr)
             u->incReferenceCount ();
         return u;
     }
template<class T> template<class U > SharedPtr& beast::SharedPtr< T >::assign (U * u) inline private
Definition at line 258 of file SharedPtr.h.
Referenced by beast::SharedPtr< beast::SharedSingleton< beast::sqdb::session::Sqlite3 > >::operator=().
     {
         if (m_p != u)
             release (this->swap (acquire (u)));
         return *this;
     }
template<class T> bool beast::SharedPtr< T >::empty () const inline noexcept
Returns true if the container is not pointing to an object.
Definition at line 201 of file SharedPtr.h.
Referenced by beast::asio::HTTPClient_test::print().
     {
         return m_p == nullptr;
     }
template<class T> T* beast::SharedPtr< T >::get () const inline noexcept
Returns the object that this pointer references if any, else nullptr.
Definition at line 219 of file SharedPtr.h.
Referenced by beast::get_pointer(), beast::Thread::getCurrentThread(), and beast::SharedPtr< beast::SharedSingleton< beast::sqdb::session::Sqlite3 > >::operator=().
     {
         return m_p;
     }
template<class T> beast::SharedPtr< T >::operator T * () const inline noexcept
Returns the object that this pointer references if any, else nullptr.
Definition at line 207 of file SharedPtr.h.
References beast::SharedPtr< T >::m_p.
     {
         return m_p;
     }
template<class T> T* beast::SharedPtr< T >::operator-> () const inline noexcept
Returns the object that this pointer references if any, else nullptr.
Definition at line 213 of file SharedPtr.h.
     {
         return m_p;
     }
template<class T> SharedPtr& beast::SharedPtr< T >::operator= (T * t) inline
Assign a different object to the container. The previous object beind held, if any, loses a reference count and will be destroyed if it is the last reference. Requirement: U* must be convertible to T*
Definition at line 123 of file SharedPtr.h.
     {
         return assign (t);
     }
template<class T> template<class U > SharedPtr& beast::SharedPtr< T >::operator= (U * u) inline
Definition at line 130 of file SharedPtr.h.
     {
         return assign (u);
     }
template<class T> SharedPtr& beast::SharedPtr< T >::operator= (SharedPtr< T > const & sp) inline
Assign an object from another container to this one.
Definition at line 138 of file SharedPtr.h.
     {
         return assign (sp.get ());
     }
template<class T> template<class U > SharedPtr& beast::SharedPtr< T >::operator= (SharedPtr< U > const & sp) inline
Assign an object from another container to this one.
Definition at line 145 of file SharedPtr.h.
     {
         return assign (sp.get ());
     }
template<class T> static void beast::SharedPtr< T >::release (T * t) inline static private
Definition at line 235 of file SharedPtr.h.
Referenced by beast::SharedPtr< beast::SharedSingleton< beast::sqdb::session::Sqlite3 > >::assign(), and beast::SharedPtr< beast::SharedSingleton< beast::sqdb::session::Sqlite3 > >::~SharedPtr().
     {
         if (t != nullptr)
             t->decReferenceCount ();
     }
template<class T> template<class U > T* beast::SharedPtr< T >::swap (U * u) inline private
Definition at line 247 of file SharedPtr.h.
Referenced by beast::SharedPtr< beast::SharedSingleton< beast::sqdb::session::Sqlite3 > >::assign().
     {
         T* const t (m_p);
         m_p = u;
         return t;
     }
Member Data Documentation
template<class T> T* beast::SharedPtr< T >::m_p private
Definition at line 265 of file SharedPtr.h.
Referenced by beast::SharedPtr< beast::SharedSingleton< beast::sqdb::session::Sqlite3 > >::assign(), beast::SharedPtr< beast::SharedSingleton< beast::sqdb::session::Sqlite3 > >::empty(), beast::SharedPtr< beast::SharedSingleton< beast::sqdb::session::Sqlite3 > >::get(), beast::SharedPtr< T >::operator T *(), beast::SharedPtr< beast::SharedSingleton< beast::sqdb::session::Sqlite3 > >::operator->(), beast::SharedPtr< beast::SharedSingleton< beast::sqdb::session::Sqlite3 > >::swap(), and beast::SharedPtr< beast::SharedSingleton< beast::sqdb::session::Sqlite3 > >::~SharedPtr().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/smart_ptr/SharedPtr.h