rippled: rippled/src/beast/beast/chrono/chrono_util.h File Reference
chrono_util.h File Reference
Functions
template<class To , class Rep , class Period >
To floor (std::chrono::duration< Rep, Period > const &d)
template<class To , class Rep , class Period >
To round (std::chrono::duration< Rep, Period > const &d)
template<class To , class Rep , class Period >
To ceil (std::chrono::duration< Rep, Period > const &d)
Function Documentation
template<class To , class Rep , class Period > To ceil (std::chrono::duration< Rep, Period > const & d)
Definition at line 58 of file chrono_util.h.
Referenced by beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::reserve().
 {
     To t = std::chrono::duration_cast<To>(d);
     if (t < d)
         ++t;
     return t;
 }
template<class To , class Rep , class Period > To floor (std::chrono::duration< Rep, Period > const & d)
Definition at line 28 of file chrono_util.h.
Referenced by ripple::detail::cleanElapsed(), beast::String::fromNumber(), and ripple::PeerFinder::Counts::onConfig().
 {
     To t = std::chrono::duration_cast<To>(d);
     if (t > d)
         --t;
     return t;
 }
template<class To , class Rep , class Period > To round (std::chrono::duration< Rep, Period > const & d)
Definition at line 38 of file chrono_util.h.
Referenced by sqlite3RegisterGlobalFunctions().
 {
     To t0 = std::chrono::duration_cast<To>(d);
     To t1 = t0;
     ++t1;
     auto diff0 = d - t0;
     auto diff1 = t1 - d;
     if (diff0 == diff1)
     {
         if (t0.count() & 1)
             return t1;
         return t0;
     }
     else if (diff0 < diff1)
         return t0;
     return t1;
 }