rippled: ripple::SHAMap Class Reference
ripple::SHAMap Class Reference
#include <SHAMap.h>
Classes
struct DefaultMissingNodeHandler
Public Types
enum { STATE_MAP_BUCKETS = 1024 }
typedef boost::shared_ptr< SHAMap > pointer
typedef const
boost::shared_ptr< SHAMap > & ref
typedef std::pair
< SHAMapItem::pointer,
SHAMapItem::pointer > DeltaItem
typedef std::pair
< SHAMapItem::ref,
SHAMapItem::ref > DeltaRef
typedef std::map< uint256,
DeltaItem > Delta
typedef ripple::unordered_map
< SHAMapNode,
SHAMapTreeNode::pointer,
SHAMapNode_hash > NodeMap
typedef boost::shared_mutex LockType
typedef boost::shared_lock
< LockType > ScopedReadLockType
typedef boost::unique_lock
< LockType > ScopedWriteLockType
typedef std::pair< uint256, Blob > fetchPackEntry_t
typedef std::pair< uint256,
SHAMapNode > TNIndex
Public Member Functions
SHAMap (SHAMapType t, FullBelowCache &fullBelowCache, std::uint32_t seq=1, MissingNodeHandler missing_node_handler=DefaultMissingNodeHandler())
SHAMap (SHAMapType t, uint256 const &hash, FullBelowCache &fullBelowCache, MissingNodeHandler missing_node_handler=DefaultMissingNodeHandler())
~SHAMap ()
std::size_t size () const noexcept
SHAMap::pointer snapShot (bool isMutable)
void dropCache ()
void setLedgerSeq (std::uint32_t lseq)
bool hasNode (const SHAMapNode &id)
bool fetchRoot (uint256 const &hash, SHAMapSyncFilter *filter)
bool hasItem (uint256 const &id)
bool delItem (uint256 const &id)
bool addItem (const SHAMapItem &i, bool isTransaction, bool hasMeta)
bool updateItem (const SHAMapItem &i, bool isTransaction, bool hasMeta)
SHAMapItem getItem (uint256 const &id)
uint256 getHash () const
uint256 getHash ()
bool updateGiveItem (SHAMapItem::ref, bool isTransaction, bool hasMeta)
bool addGiveItem (SHAMapItem::ref, bool isTransaction, bool hasMeta)
SHAMapItem::pointer peekItem (uint256 const &id)
SHAMapItem::pointer peekItem (uint256 const &id, uint256 &hash)
SHAMapItem::pointer peekItem (uint256 const &id, SHAMapTreeNode::TNType &type)
SHAMapItem::pointer peekFirstItem ()
SHAMapItem::pointer peekFirstItem (SHAMapTreeNode::TNType &type)
SHAMapItem::pointer peekLastItem ()
SHAMapItem::pointer peekNextItem (uint256 const &)
SHAMapItem::pointer peekNextItem (uint256 const &, SHAMapTreeNode::TNType &type)
SHAMapItem::pointer peekPrevItem (uint256 const &)
void visitLeaves (std::function< void(SHAMapItem::ref)>)
void getMissingNodes (std::vector< SHAMapNode > &nodeIDs, std::vector< uint256 > &hashes, int max, SHAMapSyncFilter *filter)
bool getNodeFat (const SHAMapNode &node, std::vector< SHAMapNode > &nodeIDs, std::list< Blob > &rawNode, bool fatRoot, bool fatLeaves)
bool getRootNode (Serializer &s, SHANodeFormat format)
std::vector< uint256 > getNeededHashes (int max, SHAMapSyncFilter *filter)
SHAMapAddNode addRootNode (uint256 const &hash, Blob const &rootNode, SHANodeFormat format, SHAMapSyncFilter *filter)
SHAMapAddNode addRootNode (Blob const &rootNode, SHANodeFormat format, SHAMapSyncFilter *filter)
SHAMapAddNode addKnownNode (const SHAMapNode &nodeID, Blob const &rawNode, SHAMapSyncFilter *filter)
void setImmutable ()
bool isImmutable ()
bool isSynching () const
void setSynching ()
void setFloating ()
void clearSynching ()
bool isValid ()
bool compare (SHAMap::ref otherMap, Delta &differences, int maxCount)
int armDirty ()
boost::shared_ptr< NodeMap > disarmDirty ()
void setSeq (std::uint32_t seq)
std::uint32_t getSeq ()
SHAMapTreeNode::pointer fetchNodeExternal (const SHAMapNode &id, uint256 const &hash)
SHAMapTreeNode::pointer fetchNodeExternalNT (const SHAMapNode &id, uint256 const &hash)
bool operator== (const SHAMap &s)
std::list< Blob > getTrustedPath (uint256 const &index)
void walkMap (std::vector< SHAMapMissingNode > &missingNodes, int maxMissing)
bool getPath (uint256 const &index, std::vector< Blob > &nodes, SHANodeFormat format)
bool deepCompare (SHAMap &other)
virtual void dump (bool withHashes=false)
std::list< fetchPackEntry_t > getFetchPack (SHAMap *have, bool includeLeaves, int max)
void getFetchPack (SHAMap *have, bool includeLeaves, int max, std::function< void(const uint256 &, const Blob &)>)
void setTXMap ()
Static Public Member Functions
static char const * getCountedObjectName ()
static int flushDirty (NodeMap &dirtyMap, int maxNodes, NodeObjectType t, std::uint32_t seq)
static Blob checkTrustedPath (uint256 const &ledgerHash, uint256 const &leafIndex, const std::list< Blob > &path)
static SHAMapTreeNode::pointer getCache (uint256 const &hash, SHAMapNode const &id)
static void canonicalize (uint256 const &hash, SHAMapTreeNode::pointer &)
static int getTreeNodeSize ()
static void sweep ()
static void setTreeCache (int size, int age)
Private Types
typedef std::function< void(std::uint32_t
refNum)> MissingNodeHandler
Private Member Functions
void dirtyUp (std::stack< SHAMapTreeNode::pointer > &stack, uint256 const &target, uint256 prevHash)
std::stack
< SHAMapTreeNode::pointer > getStack (uint256 const &id, bool include_nonmatching_leaf)
SHAMapTreeNode::pointer walkTo (uint256 const &id, bool modify)
SHAMapTreeNode * walkToPointer (uint256 const &id)
SHAMapTreeNode::pointer checkCacheNode (const SHAMapNode &)
void returnNode (SHAMapTreeNode::pointer &, bool modify)
void trackNewNode (SHAMapTreeNode::pointer &)
SHAMapTreeNode::pointer getNode (const SHAMapNode &id)
SHAMapTreeNode::pointer getNode (const SHAMapNode &id, uint256 const &hash, bool modify)
SHAMapTreeNode * getNodePointer (const SHAMapNode &id)
SHAMapTreeNode * getNodePointer (const SHAMapNode &id, uint256 const &hash)
SHAMapTreeNode * getNodePointerNT (const SHAMapNode &id, uint256 const &hash)
SHAMapTreeNode * getNodePointer (const SHAMapNode &id, uint256 const &hash, SHAMapSyncFilter *filter)
SHAMapTreeNode * getNodePointerNT (const SHAMapNode &id, uint256 const &hash, SHAMapSyncFilter *filter)
SHAMapTreeNode * firstBelow (SHAMapTreeNode *)
SHAMapTreeNode * lastBelow (SHAMapTreeNode *)
SHAMapTreeNode * getNodeAsync (const SHAMapNode &id, uint256 const &hash, SHAMapSyncFilter *filter, bool &pending)
SHAMapItem::pointer onlyBelow (SHAMapTreeNode *)
void eraseChildren (SHAMapTreeNode::pointer)
void dropBelow (SHAMapTreeNode *)
bool hasInnerNode (const SHAMapNode &nodeID, uint256 const &hash)
bool hasLeafNode (uint256 const &tag, uint256 const &hash)
bool walkBranch (SHAMapTreeNode *node, SHAMapItem::ref otherMapItem, bool isFirstMap, Delta &differences, int &maxCount)
void visitLeavesInternal (std::function< void(SHAMapItem::ref item)> &function)
Private Attributes
LockType mLock
FullBelowCache & m_fullBelowCache
std::uint32_t mSeq
std::uint32_t mLedgerSeq
SyncUnorderedMapType
< SHAMapNode,
SHAMapTreeNode::pointer,
SHAMapNode_hash > mTNByID
boost::shared_ptr< NodeMap > mDirtyNodes
SHAMapTreeNode::pointer root
SHAMapState mState
SHAMapType mType
bool mTXMap
MissingNodeHandler m_missing_node_handler
Static Private Attributes
static TaggedCache< uint256,
SHAMapTreeNode > treeNodeCache
Detailed Description
Definition at line 65 of file SHAMap.h.
Member Typedef Documentation
typedef std::map<uint256, DeltaItem> ripple::SHAMap::Delta
Definition at line 91 of file SHAMap.h.
typedef std::pair<SHAMapItem::pointer, SHAMapItem::pointer> ripple::SHAMap::DeltaItem
Definition at line 89 of file SHAMap.h.
typedef std::pair<SHAMapItem::ref, SHAMapItem::ref> ripple::SHAMap::DeltaRef
Definition at line 90 of file SHAMap.h.
typedef std::pair<uint256, Blob> ripple::SHAMap::fetchPackEntry_t
Definition at line 246 of file SHAMap.h.
typedef boost::shared_mutex ripple::SHAMap::LockType
Definition at line 94 of file SHAMap.h.
typedef std::function<void (std::uint32_t refNum)> ripple::SHAMap::MissingNodeHandler private
Function object which handles missing nodes.
Definition at line 70 of file SHAMap.h.
typedef ripple::unordered_map<SHAMapNode, SHAMapTreeNode::pointer, SHAMapNode_hash> ripple::SHAMap::NodeMap
Definition at line 92 of file SHAMap.h.
typedef boost::shared_ptr<SHAMap> ripple::SHAMap::pointer
Definition at line 86 of file SHAMap.h.
typedef const boost::shared_ptr<SHAMap>& ripple::SHAMap::ref
Definition at line 87 of file SHAMap.h.
typedef boost::shared_lock<LockType> ripple::SHAMap::ScopedReadLockType
Definition at line 95 of file SHAMap.h.
typedef boost::unique_lock<LockType> ripple::SHAMap::ScopedWriteLockType
Definition at line 96 of file SHAMap.h.
typedef std::pair<uint256, SHAMapNode> ripple::SHAMap::TNIndex
Definition at line 279 of file SHAMap.h.
Member Enumeration Documentation
anonymous enum
Enumerator
STATE_MAP_BUCKETS
Definition at line 79 of file SHAMap.h.
     {
         STATE_MAP_BUCKETS = 1024
     };
Constructor & Destructor Documentation
ripple::SHAMap::SHAMap (SHAMapType t, FullBelowCache & fullBelowCache, std::uint32_t seq = 1, MissingNodeHandler missing_node_handler = DefaultMissingNodeHandler()) explicit
Definition at line 33 of file SHAMap.cpp.
References mSeq, mTNByID, root, ripple::smtSTATE, and STATE_MAP_BUCKETS.
     : m_fullBelowCache (fullBelowCache)
     , mSeq (seq)
     , mLedgerSeq (0)
     , mState (smsModifying)
     , mType (t)
     , mTXMap (false)
     , m_missing_node_handler (missing_node_handler)
 {
     assert (mSeq != 0);
     if (t == smtSTATE)
         mTNByID.rehash (STATE_MAP_BUCKETS);
     root = boost::make_shared<SHAMapTreeNode> (mSeq, SHAMapNode (0, uint256 ()));
     root->makeInner ();
     mTNByID.replace(*root, root);
 }
ripple::SHAMap::SHAMap (SHAMapType t, uint256 const & hash, FullBelowCache & fullBelowCache, MissingNodeHandler missing_node_handler = DefaultMissingNodeHandler())
Definition at line 52 of file SHAMap.cpp.
References mSeq, mTNByID, root, ripple::smtSTATE, and STATE_MAP_BUCKETS.
     : m_fullBelowCache (fullBelowCache)
     , mSeq (1)
     , mLedgerSeq (0)
     , mState (smsSynching)
     , mType (t)
     , mTXMap (false)
     , m_missing_node_handler (missing_node_handler)
 {
     if (t == smtSTATE)
         mTNByID.rehash (STATE_MAP_BUCKETS);
     root = boost::make_shared<SHAMapTreeNode> (mSeq, SHAMapNode (0, uint256 ()));
     root->makeInner ();
     mTNByID.replace(*root, root);
 }
ripple::SHAMap::~SHAMap ()
Definition at line 75 of file SHAMap.cpp.
References beast::String::fromNumber(), mDirtyNodes, mState, mTNByID, root, and ripple::smsInvalid.
 {
     mState = smsInvalid;
     logTimedDestroy <SHAMap> (mTNByID,
         beast::String ("mTNByID with ") +
             beast::String::fromNumber (mTNByID.size ()) + " items");
     if (mDirtyNodes)
     {
         logTimedDestroy <SHAMap> (mDirtyNodes,
             beast::String ("mDirtyNodes with ") +
                 beast::String::fromNumber (mDirtyNodes->size ()) + " items");
     }
     if (root)
     {
         logTimedDestroy <SHAMap> (root,
             beast::String ("root node"));
     }
 }
Member Function Documentation
bool ripple::SHAMap::addGiveItem (SHAMapItem::ref item, bool isTransaction, bool hasMeta)
Definition at line 758 of file SHAMap.cpp.
References ripple::SHAMapNode::dump(), ripple::lsFATAL, ripple::smsImmutable, ripple::SHAMapTreeNode::tnACCOUNT_STATE, ripple::SHAMapTreeNode::tnTRANSACTION_MD, ripple::SHAMapTreeNode::tnTRANSACTION_NM, and WriteLog.
 {
     // add the specified item, does not update
     uint256 tag = item->getTag ();
     SHAMapTreeNode::TNType type = !isTransaction ? SHAMapTreeNode::tnACCOUNT_STATE :
                                   (hasMeta ? SHAMapTreeNode::tnTRANSACTION_MD : SHAMapTreeNode::tnTRANSACTION_NM);
     ScopedWriteLockType sl (mLock);
     assert (mState != smsImmutable);
     std::stack<SHAMapTreeNode::pointer> stack = getStack (tag, true);
     if (stack.empty ())
         throw (std::runtime_error ("missing node"));
     SHAMapTreeNode::pointer node = stack.top ();
     stack.pop ();
     if (node->isLeaf () && (node->peekItem ()->getTag () == tag))
         return false;
     uint256 prevHash;
     returnNode (node, true);
     if (node->isInner ())
     {
         // easy case, we end on an inner node
         int branch = node->selectBranch (tag);
         assert (node->isEmptyBranch (branch));
         SHAMapTreeNode::pointer newNode =
             boost::make_shared<SHAMapTreeNode> (node->getChildNodeID (branch), item, type, mSeq);
         if (!mTNByID.peekMap().emplace (SHAMapNode (*newNode), newNode).second)
         {
             WriteLog (lsFATAL, SHAMap) << "Node: " << *node;
             WriteLog (lsFATAL, SHAMap) << "NewNode: " << *newNode;
             dump ();
             assert (false);
             throw (std::runtime_error ("invalid inner node"));
         }
         trackNewNode (newNode);
         node->setChildHash (branch, newNode->getNodeHash ());
     }
     else
     {
         // this is a leaf node that has to be made an inner node holding two items
         SHAMapItem::pointer otherItem = node->peekItem ();
         assert (otherItem && (tag != otherItem->getTag ()));
         node->makeInner ();
         int b1, b2;
         while ((b1 = node->selectBranch (tag)) == (b2 = node->selectBranch (otherItem->getTag ())))
         {
             // we need a new inner node, since both go on same branch at this level
             SHAMapTreeNode::pointer newNode =
                 boost::make_shared<SHAMapTreeNode> (mSeq, node->getChildNodeID (b1));
             newNode->makeInner ();
             if (!mTNByID.peekMap().emplace (SHAMapNode (*newNode), newNode).second)
                 assert (false);
             stack.push (node);
             node = newNode;
             trackNewNode (node);
         }
         // we can add the two leaf nodes here
         assert (node->isInner ());
         SHAMapTreeNode::pointer newNode =
             boost::make_shared<SHAMapTreeNode> (node->getChildNodeID (b1), item, type, mSeq);
         assert (newNode->isValid () && newNode->isLeaf ());
         if (!mTNByID.peekMap().emplace (SHAMapNode (*newNode), newNode).second)
             assert (false);
         node->setChildHash (b1, newNode->getNodeHash ()); // OPTIMIZEME hash op not needed
         trackNewNode (newNode);
         newNode = boost::make_shared<SHAMapTreeNode> (node->getChildNodeID (b2), otherItem, type, mSeq);
         assert (newNode->isValid () && newNode->isLeaf ());
         if (!mTNByID.peekMap().emplace (SHAMapNode (*newNode), newNode).second)
             assert (false);
         node->setChildHash (b2, newNode->getNodeHash ());
         trackNewNode (newNode);
     }
     dirtyUp (stack, tag, node->getNodeHash ());
     return true;
 }
bool ripple::SHAMap::addItem (const SHAMapItem & i, bool isTransaction, bool hasMeta)
Definition at line 853 of file SHAMap.cpp.
Referenced by ripple::RadixMap::add_random_items(), ripple::SHAMapSync_test::confuseMap(), ripple::SHAMapSync_test::run(), and ripple::SHAMap_test::run().
 {
     return addGiveItem (boost::make_shared<SHAMapItem> (i), isTransaction, hasMetaData);
 }
SHAMapAddNode ripple::SHAMap::addKnownNode (const SHAMapNode & nodeID, Blob const & rawNode, SHAMapSyncFilter * filter)
Definition at line 419 of file SHAMapSync.cpp.
References ripple::Serializer::addRaw(), canonicalize(), checkCacheNode(), ripple::SHAMapAddNode::duplicate(), ripple::SHAMapNode::getDepth(), ripple::SHAMapNode::getNodeID(), getNodePointerNT(), ripple::SHAMapNode::getParentNodeID(), ripple::SHAMapSyncFilter::gotNode(), ripple::SHAMapAddNode::invalid(), ripple::SHAMapNode::isRoot(), isSynching(), ripple::lsINFO, ripple::lsTRACE, ripple::lsWARNING, m_fullBelowCache, mLock, ripple::Serializer::modData(), mTNByID, root, ripple::snfPREFIX, ripple::snfWIRE, ripple::RadMap::BasicFullBelowCache< Key >::touch_if_exists(), ripple::SHAMapAddNode::useful(), ripple::uZero, and WriteLog.
Referenced by ripple::SHAMapSync_test::run().
 {
     ScopedWriteLockType sl (mLock);
     // return value: true=okay, false=error
     assert (!node.isRoot ());
     if (!isSynching ())
     {
         WriteLog (lsTRACE, SHAMap) << "AddKnownNode while not synching";
         return SHAMapAddNode::duplicate ();
     }
     if (checkCacheNode (node)) // Do we already have this node?
         return SHAMapAddNode::duplicate ();
     SHAMapTreeNode::pointer parent = checkCacheNode(node.getParentNodeID());
     SHAMapTreeNode* iNode = parent ? parent.get() : root.get ();
     while (!iNode->isLeaf () && !iNode->isFullBelow () && (iNode->getDepth () < node.getDepth ()))
     {
         int branch = iNode->selectBranch (node.getNodeID ());
         assert (branch >= 0);
         if (iNode->isEmptyBranch (branch))
         {
             WriteLog (lsWARNING, SHAMap) << "Add known node for empty branch" << node;
             return SHAMapAddNode::invalid ();
         }
         if (m_fullBelowCache.touch_if_exists (iNode->getChildHash (branch)))
             return SHAMapAddNode::duplicate ();
         SHAMapTreeNode *nextNode = getNodePointerNT (iNode->getChildNodeID (branch), iNode->getChildHash (branch), filter);
         if (!nextNode)
         {
             if (iNode->getDepth () != (node.getDepth () - 1))
             {
                 // Either this node is broken or we didn't request it (yet)
                 WriteLog (lsWARNING, SHAMap) << "unable to hook node " << node;
                 WriteLog (lsINFO, SHAMap) << " stuck at " << *iNode;
                 WriteLog (lsINFO, SHAMap) << "got depth=" << node.getDepth () << ", walked to= " << iNode->getDepth ();
                 return SHAMapAddNode::invalid ();
             }
             SHAMapTreeNode::pointer newNode =
                 boost::make_shared<SHAMapTreeNode> (node, rawNode, 0, snfWIRE, uZero, false);
             if (iNode->getChildHash (branch) != newNode->getNodeHash ())
             {
                 WriteLog (lsWARNING, SHAMap) << "Corrupt node received";
                 return SHAMapAddNode::invalid ();
             }
             canonicalize (iNode->getChildHash (branch), newNode);
             if (mTNByID.canonicalize(node, &newNode) && filter)
             {
                 Serializer s;
                 newNode->addRaw (s, snfPREFIX);
                 filter->gotNode (false, node, iNode->getChildHash (branch), s.modData (), newNode->getType ());
             }
             return SHAMapAddNode::useful ();
         }
         iNode = nextNode;
     }
     WriteLog (lsTRACE, SHAMap) << "got node, already had it (late)";
     return SHAMapAddNode::duplicate ();
 }
SHAMapAddNode ripple::SHAMap::addRootNode (uint256 const & hash, Blob const & rootNode, SHANodeFormat format, SHAMapSyncFilter * filter)
Definition at line 383 of file SHAMapSync.cpp.
References clearSynching(), ripple::SHAMapAddNode::duplicate(), ripple::SHAMapSyncFilter::gotNode(), hash, ripple::SHAMapAddNode::invalid(), ripple::lsTRACE, mLock, ripple::Serializer::modData(), mSeq, mTNByID, root, ripple::snfPREFIX, ripple::SHAMapAddNode::useful(), ripple::uZero, and WriteLog.
Referenced by ripple::SHAMapSync_test::run().
 {
     ScopedWriteLockType sl (mLock);
     // we already have a root node
     if (root->getNodeHash ().isNonZero ())
     {
         WriteLog (lsTRACE, SHAMap) << "got root node, already have one";
         assert (root->getNodeHash () == hash);
         return SHAMapAddNode::duplicate ();
     }
     assert (mSeq >= 1);
     SHAMapTreeNode::pointer node =
         boost::make_shared<SHAMapTreeNode> (SHAMapNode (), rootNode, mSeq - 1, format, uZero, false);
     if (!node || node->getNodeHash () != hash)
         return SHAMapAddNode::invalid ();
     root = node;
     mTNByID.replace(*root, root);
     if (root->isLeaf())
         clearSynching ();
     if (filter)
     {
         Serializer s;
         root->addRaw (s, snfPREFIX);
         filter->gotNode (false, *root, root->getNodeHash (), s.modData (), root->getType ());
     }
     return SHAMapAddNode::useful ();
 }
SHAMapAddNode ripple::SHAMap::addRootNode (Blob const & rootNode, SHANodeFormat format, SHAMapSyncFilter * filter)
Definition at line 344 of file SHAMapSync.cpp.
References clearSynching(), ripple::SHAMapAddNode::duplicate(), ripple::SHAMapSyncFilter::gotNode(), ripple::SHAMapAddNode::invalid(), ripple::lsTRACE, mLock, ripple::Serializer::modData(), mSeq, mTNByID, root, ripple::snfPREFIX, ripple::SHAMapAddNode::useful(), ripple::uZero, and WriteLog.
 {
     ScopedWriteLockType sl (mLock);
     // we already have a root node
     if (root->getNodeHash ().isNonZero ())
     {
         WriteLog (lsTRACE, SHAMap) << "got root node, already have one";
         return SHAMapAddNode::duplicate ();
     }
     assert (mSeq >= 1);
     SHAMapTreeNode::pointer node =
         boost::make_shared<SHAMapTreeNode> (SHAMapNode (), rootNode, mSeq - 1, format, uZero, false);
     if (!node)
         return SHAMapAddNode::invalid ();
 #ifdef BEAST_DEBUG
     node->dump ();
 #endif
     root = node;
     mTNByID.replace(*root, root);
     if (root->isLeaf())
         clearSynching ();
     if (filter)
     {
         Serializer s;
         root->addRaw (s, snfPREFIX);
         filter->gotNode (false, *root, root->getNodeHash (), s.modData (), root->getType ());
     }
     return SHAMapAddNode::useful ();
 }
int ripple::SHAMap::armDirty ()
Definition at line 1096 of file SHAMap.cpp.
 {
     // begin saving dirty nodes
     mDirtyNodes = boost::make_shared< ripple::unordered_map<SHAMapNode, SHAMapTreeNode::pointer, SHAMapNode_hash> > ();
     return ++mSeq;
 }
void ripple::SHAMap::canonicalize (uint256 const & hash, SHAMapTreeNode::pointer & node) static
Definition at line 1291 of file SHAMap.cpp.
Referenced by addKnownNode().
 {
     assert (node->getSeq() == 0);
     treeNodeCache.canonicalize (hash, node);
 }
SHAMapTreeNode::pointer ripple::SHAMap::checkCacheNode (const SHAMapNode & iNode) private
Definition at line 222 of file SHAMap.cpp.
Referenced by addKnownNode().
 {
     SHAMapTreeNode::pointer ret = mTNByID.retrieve(iNode);
     if (ret && (ret->getSeq()!= 0))
         ret->touch (mSeq);
     return ret;
 }
static Blob ripple::SHAMap::checkTrustedPath (uint256 const & ledgerHash, uint256 const & leafIndex, const std::list< Blob > & path) static
void ripple::SHAMap::clearSynching () inline
Definition at line 196 of file SHAMap.h.
References mState, and ripple::smsModifying.
Referenced by addRootNode(), getMissingNodes(), and ripple::SHAMapSync_test::run().
     {
         mState = smsModifying;
     }
bool ripple::SHAMap::compare (SHAMap::ref otherMap, Delta & differences, int maxCount)
Definition at line 132 of file SHAMapDelta.cpp.
References ripple::SHAMapTreeNode::getChildHash(), ripple::SHAMapNode::getChildNodeID(), getHash(), getNodePointer(), ripple::SHAMapTreeNode::getTag(), ripple::SHAMapTreeNode::isEmptyBranch(), ripple::SHAMapTreeNode::isInner(), ripple::SHAMapTreeNode::isLeaf(), isValid(), mLock, mType, ripple::SHAMapTreeNode::peekData(), ripple::SHAMapTreeNode::peekItem(), and walkBranch().
 {
     // compare two hash trees, add up to maxCount differences to the difference table
     // return value: true=complete table of differences given, false=too many differences
     // throws on corrupt tables or missing nodes
     // CAUTION: otherMap is not locked and must be immutable
     assert (isValid () && otherMap && otherMap->isValid ());
     std::stack<SHAMapDeltaNode> nodeStack; // track nodes we've pushed
     ScopedReadLockType sl (mLock);
     if (getHash () == otherMap->getHash ())
         return true;
     nodeStack.push (SHAMapDeltaNode (SHAMapNode (), getHash (), otherMap->getHash ()));
     while (!nodeStack.empty ())
     {
         SHAMapDeltaNode dNode (nodeStack.top ());
         nodeStack.pop ();
         SHAMapTreeNode* ourNode = getNodePointer (dNode.mNodeID, dNode.mOurHash);
         SHAMapTreeNode* otherNode = otherMap->getNodePointer (dNode.mNodeID, dNode.mOtherHash);
         if (!ourNode || !otherNode)
         {
             assert (false);
             throw SHAMapMissingNode (mType, dNode.mNodeID, uint256 ());
         }
         if (ourNode->isLeaf () && otherNode->isLeaf ())
         {
             // two leaves
             if (ourNode->getTag () == otherNode->getTag ())
             {
                 if (ourNode->peekData () != otherNode->peekData ())
                 {
                     differences.insert (std::make_pair (ourNode->getTag (),
                                                         DeltaRef (ourNode->peekItem (), otherNode->peekItem ())));
                     if (--maxCount <= 0)
                         return false;
                 }
             }
             else
             {
                 differences.insert (std::make_pair (ourNode->getTag (),
                                                     DeltaRef (ourNode->peekItem (), SHAMapItem::pointer ())));
                 if (--maxCount <= 0)
                     return false;
                 differences.insert (std::make_pair (otherNode->getTag (),
                                                     DeltaRef (SHAMapItem::pointer (), otherNode->peekItem ())));
                 if (--maxCount <= 0)
                     return false;
             }
         }
         else if (ourNode->isInner () && otherNode->isLeaf ())
         {
             if (!walkBranch (ourNode, otherNode->peekItem (), true, differences, maxCount))
                 return false;
         }
         else if (ourNode->isLeaf () && otherNode->isInner ())
         {
             if (!otherMap->walkBranch (otherNode, ourNode->peekItem (), false, differences, maxCount))
                 return false;
         }
         else if (ourNode->isInner () && otherNode->isInner ())
         {
             for (int i = 0; i < 16; ++i)
                 if (ourNode->getChildHash (i) != otherNode->getChildHash (i))
                 {
                     if (otherNode->isEmptyBranch (i))
                     {
                         // We have a branch, the other tree does not
                         SHAMapTreeNode* iNode = getNodePointer (ourNode->getChildNodeID (i), ourNode->getChildHash (i));
                         if (!walkBranch (iNode, SHAMapItem::pointer (), true, differences, maxCount))
                             return false;
                     }
                     else if (ourNode->isEmptyBranch (i))
                     {
                         // The other tree has a branch, we do not
                         SHAMapTreeNode* iNode =
                             otherMap->getNodePointer (otherNode->getChildNodeID (i), otherNode->getChildHash (i));
                         if (!otherMap->walkBranch (iNode, SHAMapItem::pointer (), false, differences, maxCount))
                             return false;
                     }
                     else // The two trees have different non-empty branches
                         nodeStack.push (SHAMapDeltaNode (ourNode->getChildNodeID (i),
                                                          ourNode->getChildHash (i), otherNode->getChildHash (i)));
                 }
         }
         else
             assert (false);
     }
     return true;
 }
bool ripple::SHAMap::deepCompare (SHAMap & other)
Definition at line 491 of file SHAMapSync.cpp.
References getNode(), ripple::lsINFO, ripple::lsWARNING, mLock, next, root, and WriteLog.
Referenced by ripple::SHAMapSync_test::run().
 {
     // Intended for debug/test only
     std::stack<SHAMapTreeNode::pointer> stack;
     ScopedReadLockType sl (mLock);
     stack.push (root);
     while (!stack.empty ())
     {
         SHAMapTreeNode::pointer node = stack.top ();
         stack.pop ();
         SHAMapTreeNode::pointer otherNode;
         if (node->isRoot ()) otherNode = other.root;
         else otherNode = other.getNode (*node, node->getNodeHash (), false);
         if (!otherNode)
         {
             WriteLog (lsINFO, SHAMap) << "unable to fetch node";
             return false;
         }
         else if (otherNode->getNodeHash () != node->getNodeHash ())
         {
             WriteLog (lsWARNING, SHAMap) << "node hash mismatch " << *node;
             return false;
         }
         //      WriteLog (lsTRACE) << "Comparing inner nodes " << *node;
         if (node->getNodeHash () != otherNode->getNodeHash ())
             return false;
         if (node->isLeaf ())
         {
             if (!otherNode->isLeaf ()) return false;
             if (node->peekItem ()->getTag () != otherNode->peekItem ()->getTag ()) return false;
             if (node->peekItem ()->peekData () != otherNode->peekItem ()->peekData ()) return false;
         }
         else if (node->isInner ())
         {
             if (!otherNode->isInner ())
                 return false;
             for (int i = 0; i < 16; ++i)
             {
                 if (node->isEmptyBranch (i))
                 {
                     if (!otherNode->isEmptyBranch (i)) return false;
                 }
                 else
                 {
                     SHAMapTreeNode::pointer next = getNode (node->getChildNodeID (i), node->getChildHash (i), false);
                     if (!next)
                     {
                         WriteLog (lsWARNING, SHAMap) << "unable to fetch inner node";
                         return false;
                     }
                     stack.push (next);
                 }
             }
         }
     }
     return true;
 }
bool ripple::SHAMap::delItem (uint256 const & id)
Definition at line 681 of file SHAMap.cpp.
References id, ripple::base_uint< BITS >::isNonZero(), and ripple::smsImmutable.
Referenced by ripple::SHAMapSync_test::confuseMap(), and ripple::SHAMap_test::run().
 {
     // delete the item with this ID
     ScopedWriteLockType sl (mLock);
     assert (mState != smsImmutable);
     std::stack<SHAMapTreeNode::pointer> stack = getStack (id, true);
     if (stack.empty ())
         throw (std::runtime_error ("missing node"));
     SHAMapTreeNode::pointer leaf = stack.top ();
     stack.pop ();
     if (!leaf || !leaf->hasItem () || (leaf->peekItem ()->getTag () != id))
         return false;
     SHAMapTreeNode::TNType type = leaf->getType ();
     returnNode (leaf, true);
     if (mTNByID.erase (*leaf) == 0)
         assert (false);
     uint256 prevHash;
     while (!stack.empty ())
     {
         SHAMapTreeNode::pointer node = stack.top ();
         stack.pop ();
         returnNode (node, true);
         assert (node->isInner ());
         if (!node->setChildHash (node->selectBranch (id), prevHash))
         {
             assert (false);
             return true;
         }
         if (!node->isRoot ())
         {
             // we may have made this a node with 1 or 0 children
             int bc = node->getBranchCount ();
             if (bc == 0)
             {
                 prevHash = uint256 ();
                 if (!mTNByID.erase (*node))
                     assert (false);
             }
             else if (bc == 1)
             {
                 // pull up on the thread
                 SHAMapItem::pointer item = onlyBelow (node.get ());
                 if (item)
                 {
                     returnNode (node, true);
                     eraseChildren (node);
                     node->setItem (item, type);
                 }
                 prevHash = node->getNodeHash ();
                 assert (prevHash.isNonZero ());
             }
             else
             {
                 prevHash = node->getNodeHash ();
                 assert (prevHash.isNonZero ());
             }
         }
         else assert (stack.empty ());
     }
     return true;
 }
void ripple::SHAMap::dirtyUp (std::stack< SHAMapTreeNode::pointer > & stack, uint256 const & target, uint256 prevHash) private
Definition at line 189 of file SHAMap.cpp.
References ripple::lsFATAL, ripple::lsTRACE, ripple::smsImmutable, ripple::smsSynching, and WriteLog.
 {
     // walk the tree up from through the inner nodes to the root
     // update linking hashes and add nodes to dirty list
     assert ((mState != smsSynching) && (mState != smsImmutable));
     while (!stack.empty ())
     {
         SHAMapTreeNode::pointer node = stack.top ();
         stack.pop ();
         assert (node->isInnerNode ());
         int branch = node->selectBranch (target);
         assert (branch >= 0);
         returnNode (node, true);
         if (!node->setChildHash (branch, prevHash))
         {
             WriteLog (lsFATAL, SHAMap) << "dirtyUp terminates early";
             assert (false);
             return;
         }
 #ifdef ST_DEBUG
         WriteLog (lsTRACE, SHAMap) << "dirtyUp sets branch " << branch << " to " << prevHash;
 #endif
         prevHash = node->getNodeHash ();
         assert (prevHash.isNonZero ());
     }
 }
boost::shared_ptr< SHAMap::NodeMap > ripple::SHAMap::disarmDirty ()
Definition at line 1136 of file SHAMap.cpp.
 {
     // stop saving dirty nodes
     ScopedWriteLockType sl (mLock);
     boost::shared_ptr<NodeMap> ret;
     ret.swap (mDirtyNodes);
     return ret;
 }
void ripple::SHAMap::dropBelow (SHAMapTreeNode * d) private
Definition at line 1248 of file SHAMap.cpp.
References ripple::SHAMapNode::getChildNodeID(), ripple::SHAMapTreeNode::isEmptyBranch(), and ripple::SHAMapTreeNode::isInner().
 {
     if (d->isInner ())
         for (int i = 0 ; i < 16; ++i)
             if (!d->isEmptyBranch (i))
                 mTNByID.erase (d->getChildNodeID (i));
 }
void ripple::SHAMap::dropCache ()
Definition at line 1237 of file SHAMap.cpp.
References ripple::smsImmutable.
 {
     ScopedWriteLockType sl (mLock);
     assert (mState == smsImmutable);
     mTNByID.clear ();
     if (root)
         mTNByID.canonicalize(*root, &root);
 }
void ripple::SHAMap::dump (bool withHashes = false) virtual
Definition at line 1256 of file SHAMap.cpp.
References CondLog, ripple::lsINFO, and WriteLog.
 {
     WriteLog (lsINFO, SHAMap) << " MAP Contains";
     ScopedWriteLockType sl (mLock);
     for (ripple::unordered_map<SHAMapNode, SHAMapTreeNode::pointer, SHAMapNode_hash>::iterator it = mTNByID.peekMap().begin ();
             it != mTNByID.peekMap().end (); ++it)
     {
         WriteLog (lsINFO, SHAMap) << it->second->getString ();
         CondLog (hash, lsINFO, SHAMap) << it->second->getNodeHash ();
     }
 }
void ripple::SHAMap::eraseChildren (SHAMapTreeNode::pointer node) private
Definition at line 474 of file SHAMap.cpp.
 {
     // this node has only one item below it, erase its children
     bool erase = false;
     while (node->isInner ())
     {
         for (int i = 0; i < 16; ++i)
             if (!node->isEmptyBranch (i))
             {
                 SHAMapTreeNode::pointer nextNode = getNode (node->getChildNodeID (i), node->getChildHash (i), false);
                 if (erase)
                 {
                     returnNode (node, true);
                     if (mTNByID.erase (*node))
                         assert (false);
                 }
                 erase = true;
                 node = nextNode;
                 break;
             }
     }
     returnNode (node, true);
     if (mTNByID.erase (*node) == 0)
         assert (false);
     return;
 }
SHAMapTreeNode::pointer ripple::SHAMap::fetchNodeExternal (const SHAMapNode & id, uint256 const & hash)
Definition at line 898 of file SHAMap.cpp.
 {
     SHAMapTreeNode::pointer ret = fetchNodeExternalNT (id, hash);
     if (!ret)
         throw (SHAMapMissingNode (mType, id, hash));
     return ret;
 }
SHAMapTreeNode::pointer ripple::SHAMap::fetchNodeExternalNT (const SHAMapNode & id, uint256 const & hash)
Look at the cache and back end (things external to this SHAMap) to find a tree node. Only a read lock is required because mTNByID has its own, internal synchronization. Every thread calling this function must get a shared pointer to the same underlying node. This function does not throw.
Definition at line 990 of file SHAMap.cpp.
References ripple::getApp(), hash, id, ripple::SHAMapNode::isRoot(), ripple::lsFATAL, ripple::lsWARNING, ripple::snfPREFIX, and WriteLog.
 {
     SHAMapTreeNode::pointer ret;
     if (!getApp().running ())
         return ret;
     // Check the cache of shared, immutable tree nodes
     ret = getCache (hash, id);
     if (ret)
     { // The node was found in the TreeNodeCache
         assert (ret->getSeq() == 0);
         assert (id == *ret);
     }
     else
     { // Check the back end
         NodeObject::pointer obj (getApp ().getNodeStore ().fetch (hash));
         if (!obj)
         {
             if (mLedgerSeq != 0)
             {
                 m_missing_node_handler (mLedgerSeq);
                 mLedgerSeq = 0;
             }
             return ret;
         }
         try
         {
             // We make this node immutable (seq == 0) so that it can be shared
             // CoW is needed if it is modified
             ret = boost::make_shared<SHAMapTreeNode> (id, obj->getData (), 0, snfPREFIX, hash, true);
             if (id != *ret)
             {
                 WriteLog (lsFATAL, SHAMap) << "id:" << id << ", got:" << *ret;
                 assert (false);
                 return SHAMapTreeNode::pointer ();
             }
             if (ret->getNodeHash () != hash)
             {
                 WriteLog (lsFATAL, SHAMap) << "Hashes don't match";
                 assert (false);
                 return SHAMapTreeNode::pointer ();
             }
             // Share this immutable tree node in the TreeNodeCache
             canonicalize (hash, ret);
         }
         catch (...)
         {
             WriteLog (lsWARNING, SHAMap) << "fetchNodeExternal gets an invalid node: " << hash;
             return SHAMapTreeNode::pointer ();
         }
     }
     if (id.isRoot ()) // it is legal to replace an existing root
     {
         mTNByID.replace(id, ret);
         root = ret;
     }
     else // Make sure other threads get pointers to the same underlying object
        mTNByID.canonicalize (id, &ret);
     return ret;
 }
bool ripple::SHAMap::fetchRoot (uint256 const & hash, SHAMapSyncFilter * filter)
Definition at line 1058 of file SHAMap.cpp.
References ripple::SHAMapSyncFilter::gotNode(), hash, ripple::SHAMapSyncFilter::haveNode(), ripple::lsTRACE, ripple::SHAMapNode::SHAMapNode(), ShouldLog, ripple::smtSTATE, ripple::smtTRANSACTION, ripple::snfPREFIX, and WriteLog.
 {
     if (hash == root->getNodeHash ())
         return true;
     if (ShouldLog (lsTRACE, SHAMap))
     {
         if (mType == smtTRANSACTION)
             WriteLog (lsTRACE, SHAMap) << "Fetch root TXN node " << hash;
         else if (mType == smtSTATE)
             WriteLog (lsTRACE, SHAMap) << "Fetch root STATE node " << hash;
         else
             WriteLog (lsTRACE, SHAMap) << "Fetch root SHAMap node " << hash;
     }
     SHAMapTreeNode::pointer newRoot = fetchNodeExternalNT(SHAMapNode(), hash);
     if (newRoot)
     {
         root = newRoot;
     }
     else
     {
         Blob nodeData;
         if (!filter || !filter->haveNode (SHAMapNode (), hash, nodeData))
             return false;
         root = boost::make_shared<SHAMapTreeNode> (SHAMapNode (), nodeData,
                 mSeq - 1, snfPREFIX, hash, true);
         mTNByID.replace(*root, root);
         filter->gotNode (true, SHAMapNode (), hash, nodeData, root->getType ());
     }
     assert (root->getNodeHash () == hash);
     return true;
 }
SHAMapTreeNode * ripple::SHAMap::firstBelow (SHAMapTreeNode * node) private
Definition at line 395 of file SHAMap.cpp.
References ripple::SHAMapTreeNode::getChildHash(), ripple::SHAMapNode::getChildNodeID(), ripple::SHAMapTreeNode::hasItem(), and ripple::SHAMapTreeNode::isEmptyBranch().
 {
     // Return the first item below this node
     do
     {
         // Walk down the tree
         if (node->hasItem ())
             return node;
         bool foundNode = false;
         for (int i = 0; i < 16; ++i)
             if (!node->isEmptyBranch (i))
             {
                 node = getNodePointer (node->getChildNodeID (i), node->getChildHash (i));
                 foundNode = true;
                 break;
             }
         if (!foundNode)
             return nullptr;
     }
     while (true);
 }
int ripple::SHAMap::flushDirty (NodeMap & dirtyMap, int maxNodes, NodeObjectType t, std::uint32_t seq) static
Definition at line 1103 of file SHAMap.cpp.
References ripple::Serializer::erase(), ripple::getApp(), ripple::Serializer::getDataLength(), ripple::Application::getNodeStore(), ripple::Serializer::getSHA512Half(), ripple::lsFATAL, ripple::Serializer::modData(), ripple::snfPREFIX, ripple::NodeStore::Database::store(), and WriteLog.
Referenced by ripple::LedgerConsensusImp::accept(), and ripple::Ledger::Ledger().
 {
     int flushed = 0;
     Serializer s;
     for (NodeMap::iterator it = map.begin (); it != map.end (); it = map.erase (it))
     {
         //      tLog(t == hotTRANSACTION_NODE, lsDEBUG) << "TX node write " << it->first;
         //      tLog(t == hotACCOUNT_NODE, lsDEBUG) << "STATE node write " << it->first;
         s.erase ();
         it->second->addRaw (s, snfPREFIX);
 #ifdef BEAST_DEBUG
         if (s.getSHA512Half () != it->second->getNodeHash ())
         {
             WriteLog (lsFATAL, SHAMap) << * (it->second);
             WriteLog (lsFATAL, SHAMap) << beast::lexicalCast <std::string> (s.getDataLength ());
             WriteLog (lsFATAL, SHAMap) << s.getSHA512Half () << " != " << it->second->getNodeHash ();
             assert (false);
         }
 #endif
         getApp().getNodeStore ().store (t, seq, s.modData (), it->second->getNodeHash ());
         if (flushed++ >= maxNodes)
             return flushed;
     }
     return flushed;
 }
SHAMapTreeNode::pointer ripple::SHAMap::getCache (uint256 const & hash, SHAMapNode const & id) static
Definition at line 1270 of file SHAMap.cpp.
References hash, ripple::lsTRACE, and WriteLog.
 {
     SHAMapTreeNode::pointer ret = treeNodeCache.fetch (hash);
     assert (!ret || !ret->getSeq());
     if (ret && (*ret != id))
     {
         // We have the data, but with a different node ID
         WriteLog (lsTRACE, SHAMap) << "ID mismatch: " << id << " != " << *ret;
         ret = boost::make_shared <SHAMapTreeNode> (*ret, 0);
         ret->set(id);
         // Future fetches are likely to use the "new" ID
         treeNodeCache.canonicalize (hash, ret, true);
         assert (*ret == id);
         assert (ret->getNodeHash() == hash);
     }
     return ret;
 }
static char const* ripple::SHAMap::getCountedObjectName () inline static
Definition at line 84 of file SHAMap.h.
 { return "SHAMap"; }
std::list< SHAMap::fetchPackEntry_t > ripple::SHAMap::getFetchPack (SHAMap * have, bool includeLeaves, int max)
Definition at line 621 of file SHAMapSync.cpp.
References ripple::addFPtoList(), BIND_TYPE, P_1, and P_2.
 {
     std::list<fetchPackEntry_t> ret;
     getFetchPack (have, includeLeaves, max, BIND_TYPE (addFPtoList, boost::ref (ret), P_1, P_2));
     return ret;
 }
void ripple::SHAMap::getFetchPack (SHAMap * have, bool includeLeaves, int max, std::function< void(const uint256 &, const Blob &)> func)
Definition at line 628 of file SHAMapSync.cpp.
References ripple::SHAMapTreeNode::addRaw(), func, ripple::SHAMapTreeNode::getChildHash(), ripple::SHAMapNode::getChildNodeID(), ripple::SHAMapTreeNode::getNodeHash(), getNodePointer(), ripple::SHAMapTreeNode::getTag(), hasInnerNode(), hasLeafNode(), ripple::SHAMapTreeNode::isEmptyBranch(), ripple::SHAMapTreeNode::isInner(), ripple::lsINFO, ripple::max(), mLock, next, ripple::Serializer::peekData(), root, ripple::snfPREFIX, and WriteLog.
 {
     ScopedReadLockType ul1 (mLock);
     std::unique_ptr <ScopedReadLockType> ul2;
     if (have)
     {
         // VFALCO NOTE This looks like a mess. A dynamically allocated scoped lock?
         ul2.reset (new ScopedReadLockType (have->mLock, boost::try_to_lock));
         if (! ul2->owns_lock ())
         {
             WriteLog (lsINFO, SHAMap) << "Unable to create pack due to lock";
             return;
         }
     }
     if (root->getNodeHash ().isZero ())
         return;
     if (have && (root->getNodeHash () == have->root->getNodeHash ()))
         return;
     if (root->isLeaf ())
     {
         if (includeLeaves &&
                 (!have || !have->hasLeafNode (root->getTag (), root->getNodeHash ())))
         {
             Serializer s;
             root->addRaw (s, snfPREFIX);
             func (boost::cref(root->getNodeHash ()), boost::cref(s.peekData ()));
             --max;
         }
         return;
     }
     std::stack<SHAMapTreeNode*> stack; // contains unexplored non-matching inner node entries
     stack.push (root.get());
     while (!stack.empty() && (max > 0))
     {
         SHAMapTreeNode* node = stack.top ();
         stack.pop ();
         // 1) Add this node to the pack
         Serializer s;
         node->addRaw (s, snfPREFIX);
         func (boost::cref(node->getNodeHash ()), boost::cref(s.peekData ()));
         --max;
         // 2) push non-matching child inner nodes
         for (int i = 0; i < 16; ++i)
         {
             if (!node->isEmptyBranch (i))
             {
                 uint256 const& childHash = node->getChildHash (i);
                 SHAMapNode childID = node->getChildNodeID (i);
                 SHAMapTreeNode* next = getNodePointer (childID, childHash);
                 if (next->isInner ())
                 {
                     if (!have || !have->hasInnerNode (*next, childHash))
                         stack.push (next);
                 }
                 else if (includeLeaves && (!have || !have->hasLeafNode (next->getTag(), childHash)))
                 {
                     Serializer s;
                     next->addRaw (s, snfPREFIX);
                     func (boost::cref(childHash), boost::cref(s.peekData ()));
                     --max;
                 }
             }
         }
     }
 }
uint256 ripple::SHAMap::getHash () const inline
Definition at line 133 of file SHAMap.h.
References root.
Referenced by compare(), ripple::SHAMapSync_test::confuseMap(), operator==(), and ripple::SHAMap_test::run().
     {
         return root->getNodeHash ();
     }
uint256 ripple::SHAMap::getHash () inline
Definition at line 137 of file SHAMap.h.
References root.
     {
         return root->getNodeHash ();
     }
SHAMapItem ripple::SHAMap::getItem (uint256 const & id)
void ripple::SHAMap::getMissingNodes (std::vector< SHAMapNode > & nodeIDs, std::vector< uint256 > & hashes, int max, SHAMapSyncFilter * filter)
Get a list of node IDs and hashes for nodes that are part of this SHAMap but not available locally. The filter can hold alternate sources of nodes that are not permanently stored locally
Definition at line 118 of file SHAMapSync.cpp.
References clearSynching(), ripple::GMNEntry::currentChild, ripple::GMNEntry::firstChild, ripple::GMNEntry::fullBelow, ripple::getApp(), ripple::SHAMapTreeNode::getChildHash(), ripple::SHAMapNode::getChildNodeID(), ripple::NodeStore::Database::getDesiredAsyncReadCount(), getNodeAsync(), ripple::SHAMapTreeNode::getNodeHash(), getNodePointerNT(), ripple::Application::getNodeStore(), ripple::RadMap::BasicFullBelowCache< Key >::insert(), ripple::SHAMapTreeNode::isEmptyBranch(), ripple::SHAMapTreeNode::isFullBelow(), ripple::SHAMapTreeNode::isInner(), ripple::lsWARNING, m_fullBelowCache, mLock, mType, next, ripple::GMNEntry::node, rand, root, ripple::SHAMapTreeNode::setFullBelow(), ripple::smtSTATE, ripple::RadMap::BasicFullBelowCache< Key >::touch_if_exists(), ripple::NodeStore::Database::waitReads(), and WriteLog.
Referenced by getNeededHashes(), and ripple::SHAMapSync_test::run().
 {
     ScopedReadLockType sl (mLock);
     assert (root->isValid ());
     assert (root->getNodeHash().isNonZero ());
     if (root->isFullBelow ())
     {
         clearSynching ();
         return;
     }
     if (!root->isInner ())
     {
         WriteLog (lsWARNING, SHAMap) << "synching empty tree";
         return;
     }
     int const maxDefer = getApp().getNodeStore().getDesiredAsyncReadCount ();
     // Track the missing hashes we have found so far
     std::set <uint256> missingHashes;
     while (1)
     {
         std::vector <std::pair <SHAMapNode, uint256>> deferredReads;
         deferredReads.reserve (maxDefer + 16);
         std::stack <GMNEntry> stack;
         // Traverse the map without blocking
         SHAMapTreeNode *node = root.get ();
         int firstChild = rand() % 256;
         int currentChild = 0;
         bool fullBelow = true;
         do
         {
             while (currentChild < 16)
             {
                 int branch = (firstChild + currentChild++) % 16;
                 if (!node->isEmptyBranch (branch))
                 {
                     uint256 const& childHash = node->getChildHash (branch);
                     if (! m_fullBelowCache.touch_if_exists (childHash))
                     {
                         SHAMapNode childID = node->getChildNodeID (branch);
                         bool pending = false;
                         SHAMapTreeNode* d = getNodeAsync (childID, childHash, filter, pending);
                         if (!d)
{
                             if (!pending)
                             { // node is not in the database
                                 if (missingHashes.insert (childHash).second)
{
                                     nodeIDs.push_back (childID);
                                     hashes.push_back (childHash);
                                     if (--max <= 0)
                                         return;
                                 }
                             }
                             else
{
                                 // read is deferred
                                 deferredReads.emplace_back (childID, childHash);
                             }
                             fullBelow = false; // This node is not known full below
                         }
                         else if (d->isInner () && !d->isFullBelow ())
{
                             stack.push (GMNEntry (node, firstChild, currentChild, fullBelow));
                             // Switch to processing the child node
                             node = d;
                             firstChild = rand() % 256;
                             currentChild = 0;
                             fullBelow = true;
                         }
                     }
                 }
             }
             // We are done with this inner node (and thus all of its children)
             if (fullBelow)
             { // No partial node encountered below this node
                 node->setFullBelow ();
                 if (mType == smtSTATE)
                     m_fullBelowCache.insert (node->getNodeHash ());
             }
             if (stack.empty ())
                 node = nullptr; // Finished processing the last node, we are done
             else
             { // Pick up where we left off (above this node)
                 GMNEntry& next = stack.top ();
                 node = next.node;
                 firstChild = next.firstChild;
                 currentChild = next.currentChild;
                 fullBelow = (fullBelow && next.fullBelow); // was and still is
                 stack.pop ();
             }
         }
         while ((node != nullptr) && (deferredReads.size () <= maxDefer));
         // If we didn't defer any reads, we're done
         if (deferredReads.empty ())
             break;
         getApp().getNodeStore().waitReads();
         // Process all deferred reads
         for (auto const& node : deferredReads)
         {
             auto const& nodeID = node.first;
             auto const& nodeHash = node.second;
             SHAMapNode *nodePtr = getNodePointerNT (nodeID, nodeHash, filter);
             if (!nodePtr && missingHashes.insert (nodeHash).second)
             {
                 nodeIDs.push_back (nodeID);
                 hashes.push_back (nodeHash);
                 if (--max <= 0)
                     return;
             }
         }
     }
     if (nodeIDs.empty ())
         clearSynching ();
 }
std::vector< uint256 > ripple::SHAMap::getNeededHashes (int max, SHAMapSyncFilter * filter)
Definition at line 261 of file SHAMapSync.cpp.
References getMissingNodes().
 {
     std::vector<uint256> nodeHashes;
     nodeHashes.reserve(max);
     std::vector<SHAMapNode> nodeIDs;
     nodeIDs.reserve(max);
     getMissingNodes(nodeIDs, nodeHashes, max, filter);
     return nodeHashes;
 }
SHAMapTreeNode::pointer ripple::SHAMap::getNode (const SHAMapNode & id) private
Definition at line 1146 of file SHAMap.cpp.
References ripple::SHAMapNode::getNodeID().
Referenced by deepCompare(), and walkMap().
 {
     SHAMapTreeNode::pointer node = checkCacheNode (nodeID);
     if (node)
         return node;
     node = root;
     while (nodeID != *node)
     {
         int branch = node->selectBranch (nodeID.getNodeID ());
         assert (branch >= 0);
         if ((branch < 0) || node->isEmptyBranch (branch))
             return SHAMapTreeNode::pointer ();
         node = getNode (node->getChildNodeID (branch), node->getChildHash (branch), false);
         assert (node);
     }
     return node;
 }
SHAMapTreeNode::pointer ripple::SHAMap::getNode (const SHAMapNode & id, uint256 const & hash, bool modify) private
Definition at line 281 of file SHAMap.cpp.
References hash, id, ripple::lsFATAL, and WriteLog.
 {
     // retrieve a node whose node hash is known
     SHAMapTreeNode::pointer node = checkCacheNode (id);
     if (node)
     {
 #if BEAST_DEBUG
         if (node->getNodeHash () != hash)
         {
             WriteLog (lsFATAL, SHAMap) << "Attempt to get node, hash not in tree";
             WriteLog (lsFATAL, SHAMap) << "ID: " << id;
             WriteLog (lsFATAL, SHAMap) << "TgtHash " << hash;
             WriteLog (lsFATAL, SHAMap) << "NodHash " << node->getNodeHash ();
             throw std::runtime_error ("invalid node");
         }
 #endif
         returnNode (node, modify);
         return node;
     }
     return fetchNodeExternal (id, hash);
 }
SHAMapTreeNode * ripple::SHAMap::getNodeAsync (const SHAMapNode & id, uint256 const & hash, SHAMapSyncFilter * filter, bool & pending) private
Definition at line 909 of file SHAMap.cpp.
References ripple::NodeStore::Database::asyncFetch(), ripple::getApp(), ripple::Application::getNodeStore(), ripple::SHAMapSyncFilter::gotNode(), hash, ripple::SHAMapSyncFilter::haveNode(), id, ripple::SHAMapNode::isRoot(), and ripple::snfPREFIX.
Referenced by getMissingNodes().
 {
     pending = false;
     // If the node is in mTNByID, return it
     SHAMapTreeNode::pointer ptr = mTNByID.retrieve (id);
     if (ptr)
         return ptr.get ();
     // Try the tree node cache
     ptr = getCache (hash, id);
     if (!ptr)
     {
         // Try the filter
         if (filter)
         {
             Blob nodeData;
             if (filter->haveNode (id, hash, nodeData))
             {
                 ptr = boost::make_shared <SHAMapTreeNode> (
                     boost::cref (id), boost::cref (nodeData), 0, snfPREFIX, boost::cref (hash), true);
                 filter->gotNode (true, id, hash, nodeData, ptr->getType ());
             }
         }
         if (!ptr)
         {
             if (mTXMap)
             {
                 // We don't store proposed transaction nodes in the node store
                 return nullptr;
             }
             NodeObject::pointer obj;
             if (!getApp().getNodeStore().asyncFetch (hash, obj))
             { // We would have to block
                 pending = true;
                 assert (!obj);
                 return nullptr;
             }
             if (!obj)
                 return nullptr;
             ptr = boost::make_shared <SHAMapTreeNode> (id, obj->getData(), 0, snfPREFIX, hash, true);
             if (id != *ptr)
             {
                 assert (false);
                 return nullptr;
             }
         }
         // Put it in the tree node cache
         canonicalize (hash, ptr);
     }
     if (id.isRoot ())
     {
         // It is legal to replace the root
         mTNByID.replace (id, ptr);
         root = ptr;
     }
     else
         mTNByID.canonicalize (id, &ptr);
     return ptr.get ();
 }
bool ripple::SHAMap::getNodeFat (const SHAMapNode & node, std::vector< SHAMapNode > & nodeIDs, std::list< Blob > & rawNode, bool fatRoot, bool fatLeaves)
Definition at line 273 of file SHAMapSync.cpp.
References ripple::SHAMapTreeNode::addRaw(), ripple::SHAMapTreeNode::getChildHash(), ripple::SHAMapNode::getChildNodeID(), getNodePointer(), ripple::SHAMapTreeNode::isEmpty(), ripple::SHAMapTreeNode::isEmptyBranch(), ripple::SHAMapTreeNode::isInner(), ripple::SHAMapTreeNode::isLeaf(), ripple::SHAMapNode::isRoot(), ripple::lsWARNING, mLock, ripple::Serializer::peekData(), ripple::snfWIRE, and WriteLog.
Referenced by ripple::SHAMapSync_test::run().
 {
     // Gets a node and some of its children
     ScopedReadLockType sl (mLock);
     SHAMapTreeNode* node = getNodePointer(wanted);
     if (!node)
     {
         WriteLog (lsWARNING, SHAMap) << "peer requested node that is not in the map: " << wanted;
         throw std::runtime_error ("Peer requested node not in map");
     }
     if (node->isInner () && node->isEmpty ())
     {
         WriteLog (lsWARNING, SHAMap) << "peer requests empty node";
         return false;
     }
     int count;
     bool skipNode = false;
     do
     {
         if (skipNode)
             skipNode = false;
         else
         {
             Serializer s;
             node->addRaw (s, snfWIRE);
             nodeIDs.push_back(*node);
             rawNodes.push_back (s.peekData ());
         }
         if ((!fatRoot && node->isRoot ()) || node->isLeaf ()) // don't get a fat root, can't get a fat leaf
             return true;
         SHAMapTreeNode* nextNode = nullptr;
         count = 0;
         for (int i = 0; i < 16; ++i)
             if (!node->isEmptyBranch (i))
             {
                 nextNode = getNodePointer (node->getChildNodeID (i), node->getChildHash (i));
                 ++count;
                 if (fatLeaves || nextNode->isInner ())
                 {
                     Serializer s;
                     nextNode->addRaw (s, snfWIRE);
                     nodeIDs.push_back (*nextNode);
                     rawNodes.push_back (s.peekData ());
                     skipNode = true; // Don't add this node again if we loop
                 }
             }
         node = nextNode;
     // So long as there's exactly one inner node, we take it
     } while ((count == 1) && node->isInner());
     return true;
 }
SHAMapTreeNode * ripple::SHAMap::getNodePointer (const SHAMapNode & id) private
Definition at line 1173 of file SHAMap.cpp.
References ripple::SHAMapTreeNode::getChildHash(), ripple::SHAMapNode::getChildNodeID(), ripple::SHAMapNode::getNodeID(), ripple::SHAMapTreeNode::isEmptyBranch(), ripple::SHAMapTreeNode::isLeaf(), ripple::SHAMapNode::selectBranch(), and ripple::SHAMapTreeNode::touch().
Referenced by compare(), getFetchPack(), getNodeFat(), hasInnerNode(), hasLeafNode(), visitLeavesInternal(), and walkBranch().
 {
     SHAMapTreeNode::pointer nodeptr = mTNByID.retrieve (nodeID);
     if (nodeptr)
     {
         SHAMapTreeNode* ret = nodeptr.get ();
         ret->touch(mSeq);
         return ret;
     }
     SHAMapTreeNode* node = root.get();
     while (nodeID != *node)
     {
         if (node->isLeaf ())
             return nullptr;
         int branch = node->selectBranch (nodeID.getNodeID ());
         assert (branch >= 0);
         if ((branch < 0) || node->isEmptyBranch (branch))
             return nullptr;
         node = getNodePointer (node->getChildNodeID (branch), node->getChildHash (branch));
         assert (node);
     }
     return node;
 }
SHAMapTreeNode * ripple::SHAMap::getNodePointer (const SHAMapNode & id, uint256 const & hash) private
Definition at line 307 of file SHAMap.cpp.
 {
     // fast, but you do not hold a reference
     SHAMapTreeNode* ret = getNodePointerNT (id, hash);
     if (!ret)
         throw (SHAMapMissingNode (mType, id, hash));
     return ret;
 }
SHAMapTreeNode * ripple::SHAMap::getNodePointer (const SHAMapNode & id, uint256 const & hash, SHAMapSyncFilter * filter) private
Definition at line 326 of file SHAMap.cpp.
 {
     SHAMapTreeNode* ret = getNodePointerNT (id, hash, filter);
     if (!ret)
         throw (SHAMapMissingNode (mType, id, hash));
     return ret;
 }
SHAMapTreeNode * ripple::SHAMap::getNodePointerNT (const SHAMapNode & id, uint256 const & hash) private
Definition at line 318 of file SHAMap.cpp.
Referenced by addKnownNode(), and getMissingNodes().
 {
     SHAMapTreeNode::pointer ret = mTNByID.retrieve (id);
     if (!ret)
         ret = fetchNodeExternalNT (id, hash);
     return ret ? ret.get() : nullptr;
 }
SHAMapTreeNode * ripple::SHAMap::getNodePointerNT (const SHAMapNode & id, uint256 const & hash, SHAMapSyncFilter * filter) private
Definition at line 336 of file SHAMap.cpp.
References ripple::SHAMapSyncFilter::gotNode(), ripple::SHAMapSyncFilter::haveNode(), and ripple::snfPREFIX.
 {
     SHAMapTreeNode* node = getNodePointerNT (id, hash);
     if (!node && filter)
     { // Our regular node store didn't have the node. See if the filter does
         Blob nodeData;
         if (filter->haveNode (id, hash, nodeData))
         {
             SHAMapTreeNode::pointer node = boost::make_shared<SHAMapTreeNode> (
                     boost::cref (id), boost::cref (nodeData), 0, snfPREFIX, boost::cref (hash), true);
             canonicalize (hash, node);
             // Canonicalize the node with mTNByID to make sure all threads gets the same node
             // If the node is new, tell the filter
             if (mTNByID.canonicalize (id, &node))
                 filter->gotNode (true, id, hash, nodeData, node->getType ());
             return node.get ();
         }
     }
     return node;
 }
bool ripple::SHAMap::getPath (uint256 const & index, std::vector< Blob > & nodes, SHANodeFormat format)
Definition at line 1203 of file SHAMap.cpp.
References ripple::SHAMapTreeNode::addRaw(), ripple::SHAMapTreeNode::getChildHash(), ripple::SHAMapNode::getChildNodeID(), ripple::SHAMapTreeNode::getTag(), ripple::SHAMapTreeNode::isEmptyBranch(), ripple::SHAMapTreeNode::isLeaf(), ripple::Serializer::peekData(), and ripple::SHAMapNode::selectBranch().
 {
     // Return the path of nodes to the specified index in the specified format
     // Return value: true = node present, false = node not present
     ScopedReadLockType sl (mLock);
     SHAMapTreeNode* inNode = root.get ();
     while (!inNode->isLeaf ())
     {
         Serializer s;
         inNode->addRaw (s, format);
         nodes.push_back (s.peekData ());
         int branch = inNode->selectBranch (index);
         if (inNode->isEmptyBranch (branch)) // paths leads to empty branch
             return false;
         inNode = getNodePointer (inNode->getChildNodeID (branch), inNode->getChildHash (branch));
         assert (inNode);
     }
     if (inNode->getTag () != index) // path leads to different leaf
         return false;
     // path lead to the requested leaf
     Serializer s;
     inNode->addRaw (s, format);
     nodes.push_back (s.peekData ());
     return true;
 }
bool ripple::SHAMap::getRootNode (Serializer & s, SHANodeFormat format)
Definition at line 337 of file SHAMapSync.cpp.
References mLock, and root.
 {
     ScopedReadLockType sl (mLock);
     root->addRaw (s, format);
     return true;
 }
std::uint32_t ripple::SHAMap::getSeq () inline
Definition at line 219 of file SHAMap.h.
References mSeq.
     {
         return mSeq;
     }
std::stack< SHAMapTreeNode::pointer > ripple::SHAMap::getStack (uint256 const & id, bool include_nonmatching_leaf) private
Definition at line 155 of file SHAMap.cpp.
References id, and ripple::SHAMapMissingNode::setTargetNode().
Referenced by getTrustedPath().
 {
     // Walk the tree as far as possible to the specified identifier
     // produce a stack of nodes along the way, with the terminal node at the top
     std::stack<SHAMapTreeNode::pointer> stack;
     SHAMapTreeNode::pointer node = root;
     while (!node->isLeaf ())
     {
         stack.push (node);
         int branch = node->selectBranch (id);
         assert (branch >= 0);
         if (node->isEmptyBranch (branch))
             return stack;
         try
         {
             node = getNode (node->getChildNodeID (branch), node->getChildHash (branch), false);
         }
         catch (SHAMapMissingNode& mn)
         {
             mn.setTargetNode (id);
             throw;
         }
     }
     if (include_nonmatching_leaf || (node->peekItem ()->getTag () == id))
         stack.push (node);
     return stack;
 }
static int ripple::SHAMap::getTreeNodeSize () inline static
Definition at line 258 of file SHAMap.h.
References treeNodeCache.
Referenced by ripple::RPCHandler::doGetCounts().
     {
         return treeNodeCache.getCacheSize ();
     }
std::list< Blob > ripple::SHAMap::getTrustedPath (uint256 const & index)
Definition at line 709 of file SHAMapSync.cpp.
References ripple::Serializer::erase(), ripple::Serializer::getData(), getStack(), mLock, beast.util.CleanCPPFiles::path, and ripple::snfWIRE.
 {
     ScopedReadLockType sl (mLock);
     std::stack<SHAMapTreeNode::pointer> stack = SHAMap::getStack (index, false);
     if (stack.empty () || !stack.top ()->isLeaf ())
         throw std::runtime_error ("requested leaf not present");
     std::list< Blob > path;
     Serializer s;
     while (!stack.empty ())
     {
         stack.top ()->addRaw (s, snfWIRE);
         path.push_back (s.getData ());
         s.erase ();
         stack.pop ();
     }
     return path;
 }
bool ripple::SHAMap::hasInnerNode (const SHAMapNode & nodeID, uint256 const & nodeHash) private
Does this map have this inner node? You must hold a read lock to call this function
Definition at line 566 of file SHAMapSync.cpp.
References ripple::SHAMapTreeNode::getChildHash(), ripple::SHAMapNode::getChildNodeID(), ripple::SHAMapNode::getDepth(), ripple::SHAMapTreeNode::getNodeHash(), ripple::SHAMapNode::getNodeID(), getNodePointer(), ripple::SHAMapTreeNode::isEmptyBranch(), ripple::SHAMapTreeNode::isInner(), mTNByID, root, and ripple::SHAMapNode::selectBranch().
Referenced by getFetchPack().
 {
     SHAMapTreeNode::pointer ptr = mTNByID.retrieve (nodeID);
     if (ptr)
         return ptr->getNodeHash() == nodeHash;
     SHAMapTreeNode* node = root.get ();
     while (node->isInner () && (node->getDepth () < nodeID.getDepth ()))
     {
         int branch = node->selectBranch (nodeID.getNodeID ());
         if (node->isEmptyBranch (branch))
             return false;
         node = getNodePointer (node->getChildNodeID (branch), node->getChildHash (branch));
     }
     return node->getNodeHash () == nodeHash;
 }
bool ripple::SHAMap::hasItem (uint256 const & id)
Definition at line 672 of file SHAMap.cpp.
 {
     // does the tree have an item with this ID
     ScopedReadLockType sl (mLock);
     SHAMapTreeNode* leaf = walkToPointer (id);
     return (leaf != nullptr);
 }
bool ripple::SHAMap::hasLeafNode (uint256 const & tag, uint256 const & nodeHash) private
Does this map have this leaf node? You must hold a read lock to call this function
Definition at line 590 of file SHAMapSync.cpp.
References ripple::SHAMapTreeNode::getChildHash(), ripple::SHAMapNode::getChildNodeID(), ripple::SHAMapTreeNode::getNodeHash(), getNodePointer(), ripple::SHAMapTreeNode::isEmptyBranch(), ripple::SHAMapTreeNode::isInner(), root, and ripple::SHAMapNode::selectBranch().
Referenced by getFetchPack().
 {
     SHAMapTreeNode* node = root.get ();
     if (!node->isInner()) // only one leaf node in the tree
         return node->getNodeHash() == nodeHash;
     do
     {
         int branch = node->selectBranch (tag);
         if (node->isEmptyBranch (branch)) // Dead end, node must not be here
             return false;
         const uint256& nextHash = node->getChildHash (branch);
         if (nextHash == nodeHash) // Matching leaf, no need to retrieve it
             return true;
         node = getNodePointer (node->getChildNodeID (branch), nextHash);
     }
     while (node->isInner());
     return false; // If this was a matching leaf, we would have caught it already
 }
bool ripple::SHAMap::hasNode (const SHAMapNode & id)
bool ripple::SHAMap::isImmutable () inline
Definition at line 180 of file SHAMap.h.
References mState, and ripple::smsImmutable.
     {
         return mState == smsImmutable;
     }
bool ripple::SHAMap::isSynching () const inline
Definition at line 184 of file SHAMap.h.
References mState, ripple::smsFloating, and ripple::smsSynching.
Referenced by addKnownNode().
     {
         return (mState == smsFloating) || (mState == smsSynching);
     }
bool ripple::SHAMap::isValid () inline
Definition at line 200 of file SHAMap.h.
References mState, and ripple::smsInvalid.
Referenced by compare().
     {
         return mState != smsInvalid;
     }
SHAMapTreeNode * ripple::SHAMap::lastBelow (SHAMapTreeNode * node) private
Definition at line 420 of file SHAMap.cpp.
References ripple::SHAMapTreeNode::getChildHash(), ripple::SHAMapNode::getChildNodeID(), ripple::SHAMapTreeNode::hasItem(), and ripple::SHAMapTreeNode::isEmptyBranch().
 {
     do
     {
         // Walk down the tree
         if (node->hasItem ())
             return node;
         bool foundNode = false;
         for (int i = 15; i >= 0; ++i)
             if (!node->isEmptyBranch (i))
             {
                 node = getNodePointer (node->getChildNodeID (i), node->getChildHash (i));
                 foundNode = true;
                 break;
             }
         if (!foundNode)
             return nullptr;
     }
     while (true);
 }
SHAMapItem::pointer ripple::SHAMap::onlyBelow (SHAMapTreeNode * node) private
Definition at line 444 of file SHAMap.cpp.
References ripple::SHAMapTreeNode::getChildHash(), ripple::SHAMapNode::getChildNodeID(), ripple::SHAMapTreeNode::hasItem(), ripple::SHAMapTreeNode::isEmptyBranch(), ripple::SHAMapTreeNode::isLeaf(), ripple::lsFATAL, ripple::SHAMapTreeNode::peekItem(), and WriteLog.
 {
     // If there is only one item below this node, return it
     while (!node->isLeaf ())
     {
         SHAMapTreeNode* nextNode = nullptr;
         for (int i = 0; i < 16; ++i)
             if (!node->isEmptyBranch (i))
             {
                 if (nextNode)
                     return SHAMapItem::pointer (); // two leaves below
                 nextNode = getNodePointer (node->getChildNodeID (i), node->getChildHash (i));
             }
         if (!nextNode)
         {
             WriteLog (lsFATAL, SHAMap) << *node;
             assert (false);
             return SHAMapItem::pointer ();
         }
         node = nextNode;
     }
     assert (node->hasItem ());
     return node->peekItem ();
 }
bool ripple::SHAMap::operator== (const SHAMap & s) inline
Definition at line 228 of file SHAMap.h.
References getHash().
     {
         return getHash () == s.getHash ();
     }
SHAMapItem::pointer ripple::SHAMap::peekFirstItem ()
Definition at line 510 of file SHAMap.cpp.
References ripple::no_item, and ripple::SHAMapTreeNode::peekItem().
Referenced by ripple::AcceptedLedger::AcceptedLedger(), and ripple::SHAMap_test::run().
 {
     ScopedReadLockType sl (mLock);
     SHAMapTreeNode* node = firstBelow (root.get ());
     if (!node)
         return no_item;
     return node->peekItem ();
 }
SHAMapItem::pointer ripple::SHAMap::peekFirstItem (SHAMapTreeNode::TNType & type)
Definition at line 522 of file SHAMap.cpp.
References ripple::SHAMapTreeNode::getType(), ripple::no_item, and ripple::SHAMapTreeNode::peekItem().
 {
     ScopedReadLockType sl (mLock);
     SHAMapTreeNode* node = firstBelow (root.get ());
     if (!node)
         return no_item;
     type = node->getType ();
     return node->peekItem ();
 }
SHAMapItem::pointer ripple::SHAMap::peekItem (uint256 const & id)
Definition at line 633 of file SHAMap.cpp.
References ripple::no_item, and ripple::SHAMapTreeNode::peekItem().
 {
     ScopedReadLockType sl (mLock);
     SHAMapTreeNode* leaf = walkToPointer (id);
     if (!leaf)
         return no_item;
     return leaf->peekItem ();
 }
SHAMapItem::pointer ripple::SHAMap::peekItem (uint256 const & id, uint256 & hash)
Definition at line 658 of file SHAMap.cpp.
References ripple::SHAMapTreeNode::getNodeHash(), ripple::no_item, and ripple::SHAMapTreeNode::peekItem().
 {
     ScopedReadLockType sl (mLock);
     SHAMapTreeNode* leaf = walkToPointer (id);
     if (!leaf)
         return no_item;
     hash = leaf->getNodeHash ();
     return leaf->peekItem ();
 }
SHAMapItem::pointer ripple::SHAMap::peekItem (uint256 const & id, SHAMapTreeNode::TNType & type)
Definition at line 645 of file SHAMap.cpp.
References ripple::SHAMapTreeNode::getType(), ripple::no_item, and ripple::SHAMapTreeNode::peekItem().
 {
     ScopedReadLockType sl (mLock);
     SHAMapTreeNode* leaf = walkToPointer (id);
     if (!leaf)
         return no_item;
     type = leaf->getType ();
     return leaf->peekItem ();
 }
SHAMapItem::pointer ripple::SHAMap::peekLastItem ()
Definition at line 535 of file SHAMap.cpp.
References ripple::no_item, and ripple::SHAMapTreeNode::peekItem().
 {
     ScopedReadLockType sl (mLock);
     SHAMapTreeNode* node = lastBelow (root.get ());
     if (!node)
         return no_item;
     return node->peekItem ();
 }
SHAMapItem::pointer ripple::SHAMap::peekNextItem (uint256 const & id)
Definition at line 547 of file SHAMap.cpp.
Referenced by ripple::AcceptedLedger::AcceptedLedger(), ripple::RPCHandler::doLedgerData(), and ripple::SHAMap_test::run().
 {
     SHAMapTreeNode::TNType type;
     return peekNextItem (id, type);
 }
SHAMapItem::pointer ripple::SHAMap::peekNextItem (uint256 const & id, SHAMapTreeNode::TNType & type)
Definition at line 554 of file SHAMap.cpp.
References ripple::SHAMapTreeNode::getType(), id, ripple::SHAMapTreeNode::isInner(), ripple::no_item, and ripple::SHAMapTreeNode::peekItem().
 {
     // Get a pointer to the next item in the tree after a given item - item need not be in tree
     ScopedReadLockType sl (mLock);
     std::stack<SHAMapTreeNode::pointer> stack = getStack (id, true);
     while (!stack.empty ())
     {
         SHAMapTreeNode::pointer node = stack.top ();
         stack.pop ();
         if (node->isLeaf ())
         {
             if (node->peekItem ()->getTag () > id)
             {
                 type = node->getType ();
                 return node->peekItem ();
             }
         }
         else
             for (int i = node->selectBranch (id) + 1; i < 16; ++i)
                 if (!node->isEmptyBranch (i))
                 {
                     SHAMapTreeNode* firstNode = getNodePointer (node->getChildNodeID (i), node->getChildHash (i));
                     assert (firstNode);
                     firstNode = firstBelow (firstNode);
                     if (!firstNode || firstNode->isInner ())
                         throw (std::runtime_error ("missing/corrupt node"));
                     type = firstNode->getType ();
                     return firstNode->peekItem ();
                 }
     }
     // must be last item
     return no_item;
 }
SHAMapItem::pointer ripple::SHAMap::peekPrevItem (uint256 const & id)
Definition at line 595 of file SHAMap.cpp.
References id, ripple::no_item, and ripple::SHAMapTreeNode::peekItem().
 {
     ScopedReadLockType sl (mLock);
     std::stack<SHAMapTreeNode::pointer> stack = getStack (id, true);
     while (!stack.empty ())
     {
         SHAMapTreeNode::pointer node = stack.top ();
         stack.pop ();
         if (node->isLeaf ())
         {
             if (node->peekItem ()->getTag () < id)
                 return node->peekItem ();
         }
         else
         {
             for (int i = node->selectBranch (id) - 1; i >= 0; --i)
             {
                 if (!node->isEmptyBranch (i))
                 {
                     node = getNode (node->getChildNodeID (i), node->getChildHash (i), false);
                     SHAMapTreeNode* item = firstBelow (node.get ());
                     if (!item)
                         throw (std::runtime_error ("missing node"));
                     return item->peekItem ();
                 }
             }
         }
     }
     // must be last item
     return no_item;
 }
void ripple::SHAMap::returnNode (SHAMapTreeNode::pointer & node, bool modify) private
Definition at line 363 of file SHAMap.cpp.
References ripple::smsImmutable.
 {
     // make sure the node is suitable for the intended operation (copy on write)
     assert (node->isValid ());
     assert (node->getSeq () <= mSeq);
     if (node && modify && (node->getSeq () != mSeq))
     {
         // have a CoW
         assert (node->getSeq () < mSeq);
         assert (mState != smsImmutable);
         node = boost::make_shared<SHAMapTreeNode> (*node, mSeq); // here's to the new node, same as the old node
         assert (node->isValid ());
         mTNByID.replace (*node, node);
         if (node->isRoot ())
             root = node;
         if (mDirtyNodes)
             (*mDirtyNodes)[*node] = node;
     }
 }
void ripple::SHAMap::setFloating () inline
Definition at line 192 of file SHAMap.h.
References mState, and ripple::smsFloating.
     {
         mState = smsFloating;
     }
void ripple::SHAMap::setImmutable () inline
Definition at line 175 of file SHAMap.h.
References mState, ripple::smsImmutable, and ripple::smsInvalid.
Referenced by ripple::SHAMapSync_test::run().
     {
         assert (mState != smsInvalid);
         mState = smsImmutable;
     }
void ripple::SHAMap::setLedgerSeq (std::uint32_t lseq) inline
Definition at line 119 of file SHAMap.h.
References mLedgerSeq.
     {
         mLedgerSeq = lseq;
     }
void ripple::SHAMap::setSeq (std::uint32_t seq) inline
Definition at line 214 of file SHAMap.h.
References mSeq.
     {
         mSeq = seq;
         assert (seq != 0);
     }
void ripple::SHAMap::setSynching () inline
Definition at line 188 of file SHAMap.h.
References mState, and ripple::smsSynching.
Referenced by ripple::SHAMapSync_test::run().
     {
         mState = smsSynching;
     }
static void ripple::SHAMap::setTreeCache (int size, int age) inline static
Definition at line 268 of file SHAMap.h.
References treeNodeCache.
Referenced by ripple::ApplicationImp::setup().
     {
         treeNodeCache.setTargetSize (size);
         treeNodeCache.setTargetAge (age);
     }
void ripple::SHAMap::setTXMap () inline
Definition at line 274 of file SHAMap.h.
References mTXMap.
     {
         mTXMap = true;
     }
std::size_t ripple::SHAMap::size () const inline noexcept
Definition at line 108 of file SHAMap.h.
References mTNByID.
     {
         return mTNByID.size ();
     }
SHAMap::pointer ripple::SHAMap::snapShot (bool isMutable)
Definition at line 117 of file SHAMap.cpp.
References ripple::smsImmutable.
Referenced by ripple::SHAMap_test::run(), and visitLeaves().
 {
     SHAMap::pointer ret = boost::make_shared<SHAMap> (mType,
         std::ref (m_fullBelowCache));
     SHAMap& newMap = *ret;
     // Return a new SHAMap that is a snapshot of this one
     // Initially most nodes are shared and CoW is forced where needed
     {
         ScopedReadLockType sl (mLock);
         newMap.mSeq = mSeq;
         newMap.mTNByID = mTNByID;
         newMap.root = root;
         if (!isMutable)
             newMap.mState = smsImmutable;
         // If the existing map has any nodes it might modify, unshare ours now
         if (mState != smsImmutable)
         {
             BOOST_FOREACH(NodeMap::value_type& nodeIt, mTNByID.peekMap())
             {
                 if (nodeIt.second->getSeq() == mSeq)
                 { // We might modify this node, so duplicate it in the snapShot
                     SHAMapTreeNode::pointer newNode = boost::make_shared<SHAMapTreeNode> (*nodeIt.second, mSeq);
                     newMap.mTNByID.replace (*newNode, newNode);
                     if (newNode->isRoot ())
                         newMap.root = newNode;
                 }
             }
         }
         else if (isMutable) // Need to unshare on changes to the snapshot
             ++newMap.mSeq;
     }
     return ret;
 }
static void ripple::SHAMap::sweep () inline static
Definition at line 263 of file SHAMap.h.
References treeNodeCache.
Referenced by ripple::ApplicationImp::doSweep().
     {
         treeNodeCache.sweep ();
     }
void ripple::SHAMap::trackNewNode (SHAMapTreeNode::pointer & node) private
Definition at line 388 of file SHAMap.cpp.
 {
     assert (node->getSeq() == mSeq);
     if (mDirtyNodes)
         (*mDirtyNodes)[*node] = node;
 }
bool ripple::SHAMap::updateGiveItem (SHAMapItem::ref item, bool isTransaction, bool hasMeta)
Definition at line 858 of file SHAMap.cpp.
References ripple::lsWARNING, ripple::smsImmutable, ripple::SHAMapTreeNode::tnACCOUNT_STATE, ripple::SHAMapTreeNode::tnTRANSACTION_MD, ripple::SHAMapTreeNode::tnTRANSACTION_NM, and WriteLog.
 {
     // can't change the tag but can change the hash
     uint256 tag = item->getTag ();
     ScopedWriteLockType sl (mLock);
     assert (mState != smsImmutable);
     std::stack<SHAMapTreeNode::pointer> stack = getStack (tag, true);
     if (stack.empty ())
         throw (std::runtime_error ("missing node"));
     SHAMapTreeNode::pointer node = stack.top ();
     stack.pop ();
     if (!node->isLeaf () || (node->peekItem ()->getTag () != tag))
     {
         assert (false);
         return false;
     }
     returnNode (node, true);
     if (!node->setItem (item, !isTransaction ? SHAMapTreeNode::tnACCOUNT_STATE :
                         (hasMeta ? SHAMapTreeNode::tnTRANSACTION_MD : SHAMapTreeNode::tnTRANSACTION_NM)))
     {
         WriteLog (lsWARNING, SHAMap) << "SHAMap setItem, no change";
         return true;
     }
     dirtyUp (stack, tag, node->getNodeHash ());
     return true;
 }
bool ripple::SHAMap::updateItem (const SHAMapItem & i, bool isTransaction, bool hasMeta)
void ripple::SHAMap::visitLeaves (std::function< void(SHAMapItem::ref)>)
Definition at line 28 of file SHAMapSync.cpp.
References snapShot().
 {
     // Make a snapshot of this map so we don't need to hold
     // a lock on the map we're visiting
     snapShot (false)->visitLeavesInternal (function);
 }
void ripple::SHAMap::visitLeavesInternal (std::function< void(SHAMapItem::ref item)> & function) private
Definition at line 35 of file SHAMapSync.cpp.
References ripple::SHAMapTreeNode::getChildHash(), ripple::SHAMapNode::getChildNodeID(), getNodePointer(), ripple::SHAMapTreeNode::isEmptyBranch(), ripple::SHAMapTreeNode::isLeaf(), mTNByID, ripple::SHAMapTreeNode::peekItem(), and root.
 {
     assert (root->isValid ());
     if (!root || root->isEmpty ())
         return;
     if (!root->isInner ())
     {
         function (root->peekItem ());
         return;
     }
     typedef std::pair<int, SHAMapTreeNode*> posPair;
     std::stack<posPair> stack;
     SHAMapTreeNode* node = root.get ();
     int pos = 0;
     while (1)
     {
         while (pos < 16)
         {
             if (node->isEmptyBranch (pos))
             {
                 ++pos; // move to next position
             }
             else
             {
                 SHAMapTreeNode* child = getNodePointer (node->getChildNodeID (pos), node->getChildHash (pos));
                 if (child->isLeaf ())
                 {
                     function (child->peekItem ());
                     mTNByID.erase (*child); // don't need this leaf anymore
                     ++pos;
                 }
                 else
                 {
                     // If there are no more children, don't push this node
                     while ((pos != 15) && (node->isEmptyBranch (pos + 1)))
                            ++pos;
                     if (pos != 15)
                         stack.push (posPair (pos + 1, node)); // save next position to resume at
                     else
                         mTNByID.erase (*node); // don't need this inner node anymore
                     // descend to the child's first position
                     node = child;
                     pos = 0;
                 }
             }
         }
         // We are done with this inner node
         mTNByID.erase (*node);
         if (stack.empty ())
             break;
         pos = stack.top ().first;
         node = stack.top ().second;
         stack.pop ();
     }
 }
bool ripple::SHAMap::walkBranch (SHAMapTreeNode * node, SHAMapItem::ref otherMapItem, bool isFirstMap, Delta & differences, int & maxCount) private
Definition at line 43 of file SHAMapDelta.cpp.
References ripple::SHAMapTreeNode::getChildHash(), ripple::SHAMapNode::getChildNodeID(), getNodePointer(), ripple::SHAMapTreeNode::isEmptyBranch(), ripple::SHAMapTreeNode::isInner(), and ripple::SHAMapTreeNode::peekItem().
Referenced by compare().
 {
     // Walk a branch of a SHAMap that's matched by an empty branch or single item in the other map
     std::stack<SHAMapTreeNode*> nodeStack;
     nodeStack.push (node);
     bool emptyBranch = !otherMapItem;
     while (!nodeStack.empty ())
     {
         SHAMapTreeNode* node = nodeStack.top ();
         nodeStack.pop ();
         if (node->isInner ())
         {
             // This is an inner node, add all non-empty branches
             for (int i = 0; i < 16; ++i)
                 if (!node->isEmptyBranch (i))
                     nodeStack.push (getNodePointer (node->getChildNodeID (i), node->getChildHash (i)));
         }
         else
         {
             // This is a leaf node, process its item
             SHAMapItem::pointer item = node->peekItem ();
             if (!emptyBranch && (otherMapItem->getTag () < item->getTag ()))
             {
                 // this item comes after the item from the other map, so add the other item
                 if (isFirstMap) // this is first map, so other item is from second
                     differences.insert (std::make_pair (otherMapItem->getTag (),
                                                         DeltaRef (SHAMapItem::pointer (), otherMapItem)));
                 else
                     differences.insert (std::make_pair (otherMapItem->getTag (),
                                                         DeltaRef (otherMapItem, SHAMapItem::pointer ())));
                 if (--maxCount <= 0)
                     return false;
                 emptyBranch = true;
             }
             if (emptyBranch || (item->getTag () != otherMapItem->getTag ()))
             {
                 // unmatched
                 if (isFirstMap)
                     differences.insert (std::make_pair (item->getTag (), DeltaRef (item, SHAMapItem::pointer ())));
                 else
                     differences.insert (std::make_pair (item->getTag (), DeltaRef (SHAMapItem::pointer (), item)));
                 if (--maxCount <= 0)
                     return false;
             }
             else
             {
                 if (item->peekData () != otherMapItem->peekData ())
                 {
                     // non-matching items
                     if (isFirstMap)
                         differences.insert (std::make_pair (otherMapItem->getTag (), DeltaRef (item, otherMapItem)));
                     else
                         differences.insert (std::make_pair (otherMapItem->getTag (), DeltaRef (otherMapItem, item)));
                     if (--maxCount <= 0)
                         return false;
                 }
                 emptyBranch = true;
             }
         }
     }
     if (!emptyBranch)
     {
         // otherMapItem was unmatched, must add
         if (isFirstMap) // this is first map, so other item is from second
             differences.insert (std::make_pair (otherMapItem->getTag (),
                                                 DeltaRef (SHAMapItem::pointer (), otherMapItem)));
         else
             differences.insert (std::make_pair (otherMapItem->getTag (),
                                                 DeltaRef (otherMapItem, SHAMapItem::pointer ())));
         if (--maxCount <= 0)
             return false;
     }
     return true;
 }
void ripple::SHAMap::walkMap (std::vector< SHAMapMissingNode > & missingNodes, int maxMissing)
Definition at line 237 of file SHAMapDelta.cpp.
References getNode(), mLock, and root.
 {
     std::stack<SHAMapTreeNode::pointer> nodeStack;
     ScopedReadLockType sl (mLock);
     if (!root->isInner ())  // root is only node, and we have it
         return;
     nodeStack.push (root);
     while (!nodeStack.empty ())
     {
         SHAMapTreeNode::pointer node = nodeStack.top ();
         nodeStack.pop ();
         for (int i = 0; i < 16; ++i)
             if (!node->isEmptyBranch (i))
             {
                 try
                 {
                     SHAMapTreeNode::pointer d = getNode (node->getChildNodeID (i), node->getChildHash (i), false);
                     if (d->isInner ())
                         nodeStack.push (d);
                 }
                 catch (SHAMapMissingNode& n)
                 {
                     missingNodes.push_back (n);
                     if (--maxMissing <= 0)
                         return;
                 }
             }
     }
 }
SHAMapTreeNode::pointer ripple::SHAMap::walkTo (uint256 const & id, bool modify) private
Definition at line 230 of file SHAMap.cpp.
References id, and ripple::SHAMapMissingNode::setTargetNode().
 {
     // walk down to the terminal node for this ID
     SHAMapTreeNode::pointer inNode = root;
     while (!inNode->isLeaf ())
     {
         int branch = inNode->selectBranch (id);
         if (inNode->isEmptyBranch (branch))
             return inNode;
         try
         {
             inNode = getNode (inNode->getChildNodeID (branch), inNode->getChildHash (branch), false);
         }
         catch (SHAMapMissingNode& mn)
         {
             mn.setTargetNode (id);
             throw;
         }
     }
     if (inNode->getTag () != id)
         return SHAMapTreeNode::pointer ();
     if (modify)
         returnNode (inNode, true);
     return inNode;
 }
SHAMapTreeNode * ripple::SHAMap::walkToPointer (uint256 const & id) private
Definition at line 263 of file SHAMap.cpp.
References ripple::SHAMapTreeNode::getChildHash(), ripple::SHAMapNode::getChildNodeID(), ripple::SHAMapTreeNode::getTag(), id, ripple::SHAMapTreeNode::isEmptyBranch(), ripple::SHAMapTreeNode::isLeaf(), and ripple::SHAMapNode::selectBranch().
 {
     SHAMapTreeNode* inNode = root.get ();
     while (!inNode->isLeaf ())
     {
         int branch = inNode->selectBranch (id);
         if (inNode->isEmptyBranch (branch))
             return nullptr;
         inNode = getNodePointer (inNode->getChildNodeID (branch), inNode->getChildHash (branch));
         assert (inNode);
     }
     return (inNode->getTag () == id) ? inNode : nullptr;
 }
Member Data Documentation
FullBelowCache& ripple::SHAMap::m_fullBelowCache private
Definition at line 324 of file SHAMap.h.
Referenced by addKnownNode(), and getMissingNodes().
MissingNodeHandler ripple::SHAMap::m_missing_node_handler private
Definition at line 333 of file SHAMap.h.
boost::shared_ptr<NodeMap> ripple::SHAMap::mDirtyNodes private
Definition at line 328 of file SHAMap.h.
Referenced by ~SHAMap().
std::uint32_t ripple::SHAMap::mLedgerSeq private
Definition at line 326 of file SHAMap.h.
Referenced by setLedgerSeq().
LockType ripple::SHAMap::mLock mutable private
Definition at line 322 of file SHAMap.h.
Referenced by addKnownNode(), addRootNode(), compare(), deepCompare(), getFetchPack(), getMissingNodes(), getNodeFat(), getRootNode(), getTrustedPath(), and walkMap().
std::uint32_t ripple::SHAMap::mSeq private
Definition at line 325 of file SHAMap.h.
Referenced by addRootNode(), getSeq(), setSeq(), and SHAMap().
SHAMapState ripple::SHAMap::mState private
Definition at line 330 of file SHAMap.h.
Referenced by clearSynching(), isImmutable(), isSynching(), isValid(), setFloating(), setImmutable(), setSynching(), and ~SHAMap().
SyncUnorderedMapType< SHAMapNode, SHAMapTreeNode::pointer, SHAMapNode_hash > ripple::SHAMap::mTNByID private
Definition at line 327 of file SHAMap.h.
Referenced by addKnownNode(), addRootNode(), hasInnerNode(), SHAMap(), size(), visitLeavesInternal(), and ~SHAMap().
bool ripple::SHAMap::mTXMap private
Definition at line 332 of file SHAMap.h.
Referenced by setTXMap().
SHAMapType ripple::SHAMap::mType private
Definition at line 331 of file SHAMap.h.
Referenced by compare(), and getMissingNodes().
SHAMapTreeNode::pointer ripple::SHAMap::root private
Definition at line 329 of file SHAMap.h.
Referenced by addKnownNode(), addRootNode(), deepCompare(), getFetchPack(), getHash(), getMissingNodes(), getRootNode(), hasInnerNode(), hasLeafNode(), SHAMap(), visitLeavesInternal(), walkMap(), and ~SHAMap().
TaggedCache< uint256, SHAMapTreeNode > ripple::SHAMap::treeNodeCache static private
Definition at line 282 of file SHAMap.h.
Referenced by getTreeNodeSize(), setTreeCache(), and sweep().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/shamap/SHAMap.h
rippled/src/ripple_app/shamap/SHAMap.cpp
rippled/src/ripple_app/shamap/SHAMapDelta.cpp
rippled/src/ripple_app/shamap/SHAMapSync.cpp