rippled: ripple::STAccount Class Reference
ripple::STAccount Class Reference
#include <SerializedTypes.h>
Public Member Functions
STAccount (Blob const &v)
STAccount (SField::ref n, Blob const &v)
STAccount (SField::ref n, const uint160 &v)
STAccount (SField::ref n)
STAccount ()
SerializedTypeID getSType () const
std::string getText () const
RippleAddress getValueNCA () const
void setValueNCA (const RippleAddress &nca)
void setValueH160 (const uint160 &v)
bool getValueH160 (uint160 &) const
bool isValueH160 () const
Public Member Functions inherited from ripple::STVariableLength
STVariableLength (Blob const &v)
STVariableLength (SField::ref n, Blob const &v)
STVariableLength (SField::ref n)
STVariableLength (SerializerIterator &, SField::ref name=sfGeneric)
STVariableLength ()
void add (Serializer &s) const
Blob const & peekValue () const
Blob & peekValue ()
Blob getValue () const
void setValue (Blob const &v)
operator Blob () const
virtual bool isEquivalent (const SerializedType &t) const
virtual bool isDefault () const
Public Member Functions inherited from ripple::SerializedType
SerializedType ()
SerializedType (SField::ref n)
virtual ~SerializedType ()
void setFName (SField::ref n)
SField::ref getFName () const
std::string getName () const
std::unique_ptr< SerializedType > clone () const
virtual std::string getFullText () const
virtual Json::Value getJson (int) const
void addFieldID (Serializer &s) const
SerializedType & operator= (const SerializedType &t)
bool operator== (const SerializedType &t) const
bool operator!= (const SerializedType &t) const
template<class D >
D & downcast ()
template<class D >
D const & downcast () const
Static Public Member Functions
static std::unique_ptr
< SerializedType > deserialize (SerializerIterator &sit, SField::ref name)
Static Public Member Functions inherited from ripple::STVariableLength
static std::unique_ptr
< SerializedType > deserialize (SerializerIterator &sit, SField::ref name)
Static Public Member Functions inherited from ripple::SerializedType
static std::unique_ptr
< SerializedType > deserialize (SField::ref name)
Private Member Functions
virtual STAccount * duplicate () const
Static Private Member Functions
static STAccount * construct (SerializerIterator &, SField::ref)
Additional Inherited Members
Protected Attributes inherited from ripple::SerializedType
SField::ptr fName
Detailed Description
Definition at line 1136 of file SerializedTypes.h.
Constructor & Destructor Documentation
ripple::STAccount::STAccount (Blob const & v) inline
Definition at line 1139 of file SerializedTypes.h.
                               : STVariableLength (v)
     {
         ;
     }
ripple::STAccount::STAccount (SField::ref n, Blob const & v) inline
Definition at line 1143 of file SerializedTypes.h.
                                            : STVariableLength (n, v)
     {
         ;
     }
ripple::STAccount::STAccount (SField::ref n, const uint160 & v)
Definition at line 380 of file SerializedTypes.cpp.
References ripple::base_uint< BITS >::begin(), ripple::base_uint< BITS >::end(), and ripple::STVariableLength::peekValue().
                                                    : STVariableLength (n)
 {
     peekValue ().insert (peekValue ().end (), v.begin (), v.end ());
 }
ripple::STAccount::STAccount (SField::ref n) inline
Definition at line 1148 of file SerializedTypes.h.
                             : STVariableLength (n)
     {
         ;
     }
ripple::STAccount::STAccount () inline
Definition at line 1152 of file SerializedTypes.h.
Referenced by construct(), and duplicate().
     {
         ;
     }
Member Function Documentation
STAccount * ripple::STAccount::construct (SerializerIterator & u, SField::ref name) static private
Definition at line 320 of file SerializedTypes.cpp.
References ripple::SerializerIterator::getVL(), and STAccount().
Referenced by deserialize().
 {
     return new STAccount (name, u.getVL ());
 }
static std::unique_ptr<SerializedType> ripple::STAccount::deserialize (SerializerIterator & sit, SField::ref name) inline static
Definition at line 1156 of file SerializedTypes.h.
References construct().
Referenced by ripple::STObject::makeDeserializedObject().
     {
         return std::unique_ptr<SerializedType> (construct (sit, name));
     }
virtual STAccount* ripple::STAccount::duplicate () const inline private virtual
Reimplemented from ripple::STVariableLength.
Definition at line 1175 of file SerializedTypes.h.
References STAccount().
     {
         return new STAccount (*this);
     }
SerializedTypeID ripple::STAccount::getSType () const inline virtual
Reimplemented from ripple::STVariableLength.
Definition at line 1161 of file SerializedTypes.h.
     {
         return STI_ACCOUNT;
     }
std::string ripple::STAccount::getText () const virtual
Reimplemented from ripple::STVariableLength.
Definition at line 308 of file SerializedTypes.cpp.
References ripple::STVariableLength::getText(), getValueH160(), ripple::RippleAddress::humanAccountID(), and ripple::RippleAddress::setAccountID().
 {
     uint160 u;
     RippleAddress a;
     if (!getValueH160 (u))
         return STVariableLength::getText ();
     a.setAccountID (u);
     return a.humanAccountID ();
 }
bool ripple::STAccount::getValueH160 (uint160 & v) const
Definition at line 397 of file SerializedTypes.cpp.
References ripple::base_uint< BITS >::begin(), isValueH160(), and ripple::STVariableLength::peekValue().
Referenced by ripple::STObject::getFieldAccount160(), ripple::SerializedLedgerEntry::getOwners(), getText(), and getValueNCA().
 {
     if (!isValueH160 ()) return false;
     memcpy (v.begin (), & (peekValue ().front ()), (160 / 8));
     return true;
 }
RippleAddress ripple::STAccount::getValueNCA () const
Definition at line 405 of file SerializedTypes.cpp.
References getValueH160(), and ripple::RippleAddress::setAccountID().
Referenced by ripple::TransactionMetaSet::getAffectedAccounts(), ripple::STObject::getFieldAccount(), and ripple::SerializedTransaction::getMentionedAccounts().
 {
     RippleAddress a;
     uint160 v;
     if (getValueH160 (v))
         a.setAccountID (v);
     return a;
 }
bool ripple::STAccount::isValueH160 () const
Definition at line 385 of file SerializedTypes.cpp.
References ripple::STVariableLength::peekValue().
Referenced by getValueH160(), and ripple::isAccountFieldOkay().
 {
     return peekValue ().size () == (160 / 8);
 }
void ripple::STAccount::setValueH160 (const uint160 & v)
Definition at line 390 of file SerializedTypes.cpp.
References ripple::base_uint< BITS >::begin(), ripple::base_uint< BITS >::end(), and ripple::STVariableLength::peekValue().
Referenced by ripple::STObject::setFieldAccount(), and setValueNCA().
 {
     peekValue ().clear ();
     peekValue ().insert (peekValue ().end (), v.begin (), v.end ());
     assert (peekValue ().size () == (160 / 8));
 }
void ripple::STAccount::setValueNCA (const RippleAddress & nca)
Definition at line 416 of file SerializedTypes.cpp.
References ripple::RippleAddress::getAccountID(), and setValueH160().
 {
     setValueH160 (nca.getAccountID ());
 }
The documentation for this class was generated from the following files:
rippled/src/ripple_data/protocol/SerializedTypes.h
rippled/src/ripple_data/protocol/SerializedTypes.cpp