rippled: beast::ServiceQueueBase::Waiter Class Reference
beast::ServiceQueueBase::Waiter Class Reference
#include <ServiceQueue.h>
Public Member Functions
Waiter ()
void wait ()
void signal ()
Private Attributes
WaitableEvent m_event
Detailed Description
Definition at line 372 of file ServiceQueue.h.
Constructor & Destructor Documentation
beast::ServiceQueueBase::Waiter::Waiter () inline
Definition at line 375 of file ServiceQueue.h.
             { }
Member Function Documentation
void beast::ServiceQueueBase::Waiter::signal () inline
Definition at line 379 of file ServiceQueue.h.
References m_event, and beast::WaitableEvent::signal().
Referenced by beast::ServiceQueueBase::enqueue(), and beast::ServiceQueueBase::stop().
             { m_event.signal(); }
void beast::ServiceQueueBase::Waiter::wait () inline
Definition at line 377 of file ServiceQueue.h.
References m_event, and beast::WaitableEvent::wait().
Referenced by beast::ServiceQueueBase::wait().
             { m_event.wait(); }
Member Data Documentation
WaitableEvent beast::ServiceQueueBase::Waiter::m_event private
Definition at line 382 of file ServiceQueue.h.
Referenced by signal(), and wait().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/threads/ServiceQueue.h