rippled: ripple::LogSink Class Reference
ripple::LogSink Class Reference
#include <LogSink.h>
Public Types
typedef beast::SharedPtr
< beast::SharedSingleton
< LogSink > > Ptr
Public Member Functions
LogSink ()
~LogSink ()
LogSeverity getMinSeverity ()
void setMinSeverity (LogSeverity, bool all)
void setLogFile (boost::filesystem::path const &pathToLogFile)
std::string rotateLog ()
void format (std::string &output, std::string const &message, LogSeverity severity, std::string const &partitionName)
void write (std::string const &message, LogSeverity severity, std::string const &partitionName)
void write (std::string const &text, LogSeverity severity)
void write (std::string const &text)
void write_console (std::string const &text)
Static Public Member Functions
static std::string replaceFirstSecretWithAsterisks (std::string s)
static Ptr get ()
Private Types
enum { maximumMessageCharacters = 12 * 1024 }
typedef RippleRecursiveMutex LockType
typedef std::lock_guard< LockType > ScopedLockType
Private Member Functions
void write (std::string const &line, bool toStdErr, ScopedLockType &)
Private Attributes
LockType m_mutex
LogFile m_logFile
LogSeverity m_minSeverity
Detailed Description
An endpoint for all logging messages.
Definition at line 29 of file LogSink.h.
Member Typedef Documentation
typedef RippleRecursiveMutex ripple::LogSink::LockType private
Definition at line 84 of file LogSink.h.
typedef beast::SharedPtr<beast::SharedSingleton <LogSink> > ripple::LogSink::Ptr
Returns a pointer to the singleton.
Definition at line 80 of file LogSink.h.
typedef std::lock_guard<LockType> ripple::LogSink::ScopedLockType private
Definition at line 85 of file LogSink.h.
Member Enumeration Documentation
anonymous enum private
Enumerator
maximumMessageCharacters
Maximum line length for log messages. If the message exceeds this length it will be truncated with elipses.
Definition at line 87 of file LogSink.h.
     {
         maximumMessageCharacters = 12 * 1024
     };
Constructor & Destructor Documentation
ripple::LogSink::LogSink ()
Definition at line 24 of file LogSink.cpp.
     : m_minSeverity (lsINFO)
 {
 }
ripple::LogSink::~LogSink ()
Definition at line 29 of file LogSink.cpp.
 {
 }
Member Function Documentation
void ripple::LogSink::format (std::string & output, std::string const & message, LogSeverity severity, std::string const & partitionName)
Format a log message.
Definition at line 76 of file LogSink.cpp.
References bassertfalse, ripple::lsDEBUG, ripple::lsERROR, ripple::lsFATAL, ripple::lsINFO, ripple::lsTRACE, ripple::lsWARNING, maximumMessageCharacters, and replaceFirstSecretWithAsterisks().
Referenced by write().
 {
     output.reserve (message.size() + partitionName.size() + 100);
     output = boost::posix_time::to_simple_string (
         boost::posix_time::second_clock::universal_time ());
     output += " ";
     if (! partitionName.empty ())
         output += partitionName + ":";
     switch (severity)
     {
     case lsTRACE:       output += "TRC "; break;
     case lsDEBUG:       output += "DBG "; break;
     case lsINFO:        output += "NFO "; break;
     case lsWARNING:     output += "WRN "; break;
     case lsERROR:       output += "ERR "; break;
     default:
         bassertfalse;
     case lsFATAL:       output += "FTL ";
         break;
     }
     output += replaceFirstSecretWithAsterisks (message);
     if (output.size() > maximumMessageCharacters)
     {
         output.resize (maximumMessageCharacters - 3);
         output += "...";
     }
 }
LogSink::Ptr ripple::LogSink::get () static
Definition at line 185 of file LogSink.cpp.
Referenced by ripple::RPCHandler::doLogLevel(), ripple::RPCHandler::doLogRotate(), ripple::run(), ripple::ApplicationImp::setup(), ripple::LogPartition::write(), ripple::Log::~Log(), and ripple::Log::out::~out().
 {
     return beast::SharedSingleton <LogSink>::getInstance ();
 }
LogSeverity ripple::LogSink::getMinSeverity ()
Returns the minimum severity required for also writing to stderr.
Definition at line 33 of file LogSink.cpp.
References m_minSeverity, and m_mutex.
Referenced by write().
 {
     ScopedLockType lock (m_mutex);
     return m_minSeverity;
 }
std::string ripple::LogSink::replaceFirstSecretWithAsterisks (std::string s) static
Hides secret keys from log output.
Definition at line 156 of file LogSink.cpp.
References ripple::min().
Referenced by format().
 {
     using namespace std;
     char const* secretToken = "\"secret\"";
     // Look for the first occurrence of "secret" in the string.
     //
     size_t startingPosition = s.find (secretToken);
     if (startingPosition != string::npos)
     {
         // Found it, advance past the token.
         //
         startingPosition += strlen (secretToken);
         // Replace the next 35 characters at most, without overwriting the end.
         //
         size_t endingPosition = std::min (startingPosition + 35, s.size () - 1);
         for (size_t i = startingPosition; i < endingPosition; ++i)
             s [i] = '*';
     }
     return s;
 }
std::string ripple::LogSink::rotateLog ()
Rotate the log file. The log file is closed and reopened. This is for compatibility with log management tools.
Returns
A human readable string describing the result of the operation.
Definition at line 60 of file LogSink.cpp.
References ripple::LogFile::closeAndReopen(), m_logFile, and m_mutex.
 {
     ScopedLockType lock (m_mutex);
     bool const wasOpened = m_logFile.closeAndReopen ();
     if (wasOpened)
     {
         return "The log file was closed and reopened.";
     }
     else
     {
         return "The log file could not be closed and reopened.";
     }
 }
void ripple::LogSink::setLogFile (boost::filesystem::path const & pathToLogFile)
Sets the path to the log file.
Definition at line 50 of file LogSink.cpp.
References rocksdb::Log(), ripple::lsFATAL, m_logFile, ripple::LogFile::open(), and beast.util.CleanCPPFiles::path.
 {
     bool const wasOpened = m_logFile.open (path.c_str ());
     if (! wasOpened)
     {
         Log (lsFATAL) << "Unable to open logfile " << path;
     }
 }
void ripple::LogSink::setMinSeverity (LogSeverity s, bool all)
Sets the minimum severity required for also writing to stderr. If 'all' is true this will set the minimum reporting severity for all partitions.
Definition at line 40 of file LogSink.cpp.
References m_minSeverity, m_mutex, and ripple::LogPartition::setSeverity().
 {
     ScopedLockType lock (m_mutex);
     m_minSeverity = s;
     if (all)
         LogPartition::setSeverity (s);
 }
void ripple::LogSink::write (std::string const & message, LogSeverity severity, std::string const & partitionName)
Write to log output. All logging eventually goes through these functios. The text should not contain a final newline, it will be automatically added as needed.
Note
This acquires a global mutex.
Parameters
text The text to write.
toStdErr true to also write to std::cerr
Definition at line 113 of file LogSink.cpp.
References format().
Referenced by write().
 {
     std::string output;
     format (output, message, severity, partitionName);
     write (output, severity);
 }
void ripple::LogSink::write (std::string const & text, LogSeverity severity)
Definition at line 125 of file LogSink.cpp.
References getMinSeverity(), m_mutex, and write().
 {
     ScopedLockType lock (m_mutex);
     write (output, severity >= getMinSeverity(), lock);
 }
void ripple::LogSink::write (std::string const & text)
Definition at line 131 of file LogSink.cpp.
References m_mutex, and write().
 {
     ScopedLockType lock (m_mutex);
     write (text, true, lock);
 }
void ripple::LogSink::write (std::string const & line, bool toStdErr, ScopedLockType &) private
Definition at line 137 of file LogSink.cpp.
References m_logFile, and ripple::LogFile::writeln().
 {
     // Does nothing if not open.
     m_logFile.writeln (line);
     if (toStdErr)
         std::cerr << line << std::endl;
 }
void ripple::LogSink::write_console (std::string const & text)
Definition at line 146 of file LogSink.cpp.
References beast::beast_isRunningUnderDebugger(), and beast::Logger::outputDebugString().
 {
 #if BEAST_MSVC
     if (beast::beast_isRunningUnderDebugger ())
         beast::Logger::outputDebugString (text.c_str());
 #endif
 }
Member Data Documentation
LogFile ripple::LogSink::m_logFile private
Definition at line 99 of file LogSink.h.
Referenced by rotateLog(), setLogFile(), and write().
LogSeverity ripple::LogSink::m_minSeverity private
Definition at line 100 of file LogSink.h.
Referenced by getMinSeverity(), and setMinSeverity().
LockType ripple::LogSink::m_mutex private
Definition at line 97 of file LogSink.h.
Referenced by getMinSeverity(), rotateLog(), setMinSeverity(), and write().
The documentation for this class was generated from the following files:
rippled/src/ripple_basics/log/LogSink.h
rippled/src/ripple_basics/log/LogSink.cpp