rippled: beast::File Class Reference
beast::File Class Reference
#include <File.h>
Public Types
enum TypesOfFileToFind { findDirectories = 1, findFiles = 2, findFilesAndDirectories = 3, ignoreHiddenFiles = 4 }
enum SpecialLocationType {
userHomeDirectory, userDocumentsDirectory, userDesktopDirectory, userMusicDirectory,
userMoviesDirectory, userPicturesDirectory, userApplicationDataDirectory, commonApplicationDataDirectory,
commonDocumentsDirectory, tempDirectory, currentExecutableFile, currentApplicationFile,
invokedExecutableFile, hostApplicationPath, globalApplicationsDirectory
}
Public Member Functions
File () noexcept
File (const String &absolutePath)
File (const File &)
~File () noexcept
File & operator= (const String &newAbsolutePath)
File & operator= (const File &otherFile)
bool exists () const
bool existsAsFile () const
bool isDirectory () const
std::int64_t getSize () const
const String & getFullPathName () const noexcept
String getFileName () const
String getRelativePathFrom (const File &directoryToBeRelativeTo) const
String getFileExtension () const
bool hasFileExtension (const String &extensionToTest) const
File withFileExtension (const String &newExtension) const
String getFileNameWithoutExtension () const
int hashCode () const
std::int64_t hashCode64 () const
File getChildFile (String relativeOrAbsolutePath) const
File getSiblingFile (const String &siblingFileName) const
File getParentDirectory () const
bool isAChildOf (const File &potentialParentDirectory) const
File getNonexistentChildFile (const String &prefix, const String &suffix, bool putNumbersInBrackets=true) const
File getNonexistentSibling (bool putNumbersInBrackets=true) const
bool operator== (const File &) const
bool operator!= (const File &) const
bool operator< (const File &) const
bool operator> (const File &) const
bool hasWriteAccess () const
bool setReadOnly (bool shouldBeReadOnly, bool applyRecursively=false) const
bool isHidden () const
File getLinkedTarget () const
Time getLastModificationTime () const
Time getLastAccessTime () const
Time getCreationTime () const
bool setLastModificationTime (Time newTime) const
bool setLastAccessTime (Time newTime) const
bool setCreationTime (Time newTime) const
String getVersion () const
Result create () const
Result createDirectory () const
bool deleteFile () const
bool deleteRecursively () const
bool moveToTrash () const
bool moveFileTo (const File &targetLocation) const
bool copyFileTo (const File &targetLocation) const
bool copyDirectoryTo (const File &newDirectory) const
int findChildFiles (Array< File > &results, int whatToLookFor, bool searchRecursively, const String &wildCardPattern="*") const
int getNumberOfChildFiles (int whatToLookFor, const String &wildCardPattern="*") const
bool containsSubDirectories () const
FileInputStream * createInputStream () const
FileOutputStream * createOutputStream (size_t bufferSize=0x8000) const
bool loadFileAsData (MemoryBlock &result) const
String loadFileAsString () const
void readLines (StringArray &destLines) const
bool appendData (const void *dataToAppend, size_t numberOfBytes) const
bool replaceWithData (const void *dataToWrite, size_t numberOfBytes) const
bool appendText (const String &textToAppend, bool asUnicode=false, bool writeUnicodeHeaderBytes=false) const
bool replaceWithText (const String &textToWrite, bool asUnicode=false, bool writeUnicodeHeaderBytes=false) const
bool hasIdenticalContentTo (const File &other) const
String getVolumeLabel () const
int getVolumeSerialNumber () const
std::int64_t getBytesFreeOnVolume () const
std::int64_t getVolumeTotalSize () const
bool isOnCDRomDrive () const
bool isOnHardDisk () const
bool isOnRemovableDrive () const
bool startAsProcess (const String &parameters=String::empty) const
void revealToUser () const
bool setAsCurrentWorkingDirectory () const
Static Public Member Functions
static File const & nonexistent ()
static String descriptionOfSizeInBytes (std::int64_t bytes)
static void findFileSystemRoots (Array< File > &results)
static File getSpecialLocation (const SpecialLocationType type)
static File createTempFile (const String &fileNameEnding)
static File getCurrentWorkingDirectory ()
static String createLegalFileName (const String &fileNameToFix)
static String createLegalPathName (const String &pathNameToFix)
static bool areFileNamesCaseSensitive ()
static bool isAbsolutePath (const String &path)
static File createFileWithoutCheckingPath (const String &absolutePath) noexcept
static String addTrailingSeparator (const String &path)
Static Public Attributes
static const beast_wchar separator = '/'
static const String separatorString
Private Member Functions
String getPathUpToLastSlash () const
Result createDirectoryInternal (const String &) const
bool copyInternal (const File &) const
bool moveInternal (const File &) const
bool setFileTimesInternal (std::int64_t m, std::int64_t a, std::int64_t c) const
void getFileTimesInternal (std::int64_t &m, std::int64_t &a, std::int64_t &c) const
bool setFileReadOnlyInternal (bool) const
Static Private Member Functions
static String parseAbsolutePath (const String &)
Private Attributes
String fullPath
Detailed Description
Represents a local file or directory.
This class encapsulates the absolute pathname of a file or directory, and has methods for finding out about the file and changing its properties.
To read or write to the file, there are methods for returning an input or output stream.
See Also
FileInputStream, FileOutputStream
Definition at line 51 of file File.h.
Member Enumeration Documentation
enum beast::File::SpecialLocationType
A set of types of location that can be passed to the getSpecialLocation() method.
Enumerator
userHomeDirectory
The user's home folder. This is the same as using File ("~").
userDocumentsDirectory
The user's default documents folder. On Windows, this might be the user's "My Documents" folder. On the Mac it'll be their "Documents" folder. Linux doesn't tend to have one of these, so it might just return their home folder.
userDesktopDirectory
The folder that contains the user's desktop objects.
userMusicDirectory
The most likely place where a user might store their music files.
userMoviesDirectory
The most likely place where a user might store their movie files.
userPicturesDirectory
The most likely place where a user might store their picture files.
userApplicationDataDirectory
The folder in which applications store their persistent user-specific settings. On Windows, this might be "\Documents and Settings\username\Application Data". On the Mac, it might be "~/Library". If you're going to store your settings in here, always create your own sub-folder to put them in, to avoid making a mess.
commonApplicationDataDirectory
An equivalent of the userApplicationDataDirectory folder that is shared by all users of the computer, rather than just the current user.
On the Mac it'll be "/Library", on Windows, it could be something like "\Documents and Settings\All Users\Application Data".
Depending on the setup, this folder may be read-only.
commonDocumentsDirectory
A place to put documents which are shared by all users of the machine. On Windows this may be somewhere like "C:\Users\Public\Documents", on OSX it will be something like "/Users/Shared". Other OSes may have no such concept though, so be careful.
tempDirectory
The folder that should be used for temporary files. Always delete them when you're finished, to keep the user's computer tidy!
currentExecutableFile
Returns this application's executable file.
    If running as a plug-in or DLL, this will (where possible) be the DLL rather than the
    host app.
    On the mac this will return the unix binary, not the package folder - see
    currentApplicationFile for that.
    See also invokedExecutableFile, which is similar, but if the exe was launched from a
    file link, invokedExecutableFile will return the name of the link.
currentApplicationFile
Returns this application's location.
    If running as a plug-in or DLL, this will (where possible) be the DLL rather than the
    host app.
    On the mac this will return the package folder (if it's in one), not the unix binary
    that's inside it - compare with currentExecutableFile.
invokedExecutableFile
Returns the file that was invoked to launch this executable. This may differ from currentExecutableFile if the app was started from e.g. a link - this will return the name of the link that was used, whereas currentExecutableFile will return the actual location of the target executable.
hostApplicationPath
In a plugin, this will return the path of the host executable.
globalApplicationsDirectory
The directory in which applications normally get installed. So on windows, this would be something like "c:\program files", on the Mac "/Applications", or "/usr" on linux.
Definition at line 757 of file File.h.
     {
         userHomeDirectory,
         userDocumentsDirectory,
         userDesktopDirectory,
         userMusicDirectory,
         userMoviesDirectory,
         userPicturesDirectory,
         userApplicationDataDirectory,
         commonApplicationDataDirectory,
         commonDocumentsDirectory,
         tempDirectory,
         currentExecutableFile,
         currentApplicationFile,
         invokedExecutableFile,
         hostApplicationPath,
         globalApplicationsDirectory
     };
enum beast::File::TypesOfFileToFind
Used in file searching, to specify whether to return files, directories, or both.
Enumerator
findDirectories
Use this flag to indicate that you want to find directories.
findFiles
Use this flag to indicate that you want to find files.
findFilesAndDirectories
Use this flag to indicate that you want to find both files and directories.
ignoreHiddenFiles
Add this flag to avoid returning any hidden files in the results.
Definition at line 516 of file File.h.
     {
         findDirectories             = 1,
         findFiles                   = 2,
         findFilesAndDirectories     = 3,
         ignoreHiddenFiles           = 4
     };
Constructor & Destructor Documentation
beast::File::File () inline noexcept
Creates an (invalid) file object.
The file is initially set to an empty path, so getFullPath() will return an empty string, and comparing the file to File::nonexistent will return true.
You can use its operator= method to point it at a proper file.
Definition at line 63 of file File.h.
Referenced by getChildFile(), getCurrentWorkingDirectory(), and getSpecialLocation().
 {}
beast::File::File (const String & absolutePath)
Creates a file from an absolute path.
If the path supplied is a relative path, it is taken to be relative to the current working directory (see File::getCurrentWorkingDirectory()), but this isn't a recommended way of creating a file, because you never know what the CWD is going to be.
On the Mac/Linux, the path can include "~" notation for referring to user home directories.
Definition at line 49 of file File.cpp.
     : fullPath (parseAbsolutePath (fullPathName))
 {
 }
beast::File::File (const File & other)
Creates a copy of another file object.
Definition at line 54 of file File.cpp.
     : fullPath (other.fullPath)
 {
 }
beast::File::~File () inline noexcept
Destructor.
Definition at line 81 of file File.h.
 {}
Member Function Documentation
String beast::File::addTrailingSeparator (const String & path) static
Adds a separator character to the end of a path if it doesn't already have one.
Definition at line 187 of file File.cpp.
References beast::String::endsWithChar(), and separator.
Referenced by getChildFile(), getRelativePathFrom(), and parseAbsolutePath().
 {
     return path.endsWithChar (separator) ? path
                                          : path + separator;
 }
bool beast::File::appendData (const void * dataToAppend, size_t numberOfBytes) const
Appends a block of binary data to the end of the file.
This will try to write the given buffer to the end of the file.
Returns
false if it can't write to the file for some reason
Definition at line 694 of file File.cpp.
References bassert, beast::FileOutputStream::openedOk(), and beast::FileOutputStream::write().
Referenced by replaceWithData().
 {
     bassert (((std::ptrdiff_t) numberOfBytes) >= 0);
     if (numberOfBytes == 0)
         return true;
     FileOutputStream out (*this, 8192);
     return out.openedOk() && out.write (dataToAppend, numberOfBytes);
 }
bool beast::File::appendText (const String & textToAppend, bool asUnicode = false, bool writeUnicodeHeaderBytes = false) const
Appends a string to the end of the file.
This will try to append a text string to the file, as either 16-bit unicode or 8-bit characters in the default system encoding.
It can also write the 'ff fe' unicode header bytes before the text to indicate the endianness of the file.
Any single \n characters in the string are replaced with \r\n before it is written.
See Also
replaceWithText
Definition at line 717 of file File.cpp.
References beast::FileOutputStream::failedToOpen(), and beast::OutputStream::writeText().
Referenced by replaceWithText().
 {
     FileOutputStream out (*this);
     if (out.failedToOpen())
         return false;
     out.writeText (text, asUnicode, writeUnicodeHeaderBytes);
     return true;
 }
bool beast::File::areFileNamesCaseSensitive () static
Indicates whether filenames are case-sensitive on the current operating system.
Definition at line 198 of file File.cpp.
Referenced by beast::fileMatches().
 {
    #if NAMES_ARE_CASE_SENSITIVE
     return true;
    #else
     return false;
    #endif
 }
bool beast::File::containsSubDirectories () const
Returns true if this file is a directory that contains one or more subdirectories.
See Also
isDirectory, findChildFiles
Definition at line 542 of file File.cpp.
References findDirectories, isDirectory(), and beast::DirectoryIterator::next().
 {
     if (! isDirectory())
         return false;
     DirectoryIterator di (*this, false, "*", findDirectories);
     return di.next();
 }
bool beast::File::copyDirectoryTo (const File & newDirectory) const
Copies a directory.
Tries to copy an entire directory, recursively.
If this file isn't a directory or if any target files can't be created, this will return false.
Parameters
newDirectory the directory that this one should be copied to. Note that this is the name of the actual directory to create, not the directory into which the new one should be placed, so there must be enough write privileges to create it if it doesn't exist. Any files inside it will be overwritten by similarly named ones that are copied.
Definition at line 278 of file File.cpp.
References beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::clear(), createDirectory(), findChildFiles(), findDirectories, findFiles, getChildFile(), beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getReference(), isDirectory(), and beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
 {
     if (isDirectory() && newDirectory.createDirectory())
     {
         Array<File> subFiles;
         findChildFiles (subFiles, File::findFiles, false);
         for (int i = 0; i < subFiles.size(); ++i)
             if (! subFiles.getReference(i).copyFileTo (newDirectory.getChildFile (subFiles.getReference(i).getFileName())))
                 return false;
         subFiles.clear();
         findChildFiles (subFiles, File::findDirectories, false);
         for (int i = 0; i < subFiles.size(); ++i)
             if (! subFiles.getReference(i).copyDirectoryTo (newDirectory.getChildFile (subFiles.getReference(i).getFileName())))
                 return false;
         return true;
     }
     return false;
 }
bool beast::File::copyFileTo (const File & targetLocation) const
Copies a file.
Tries to copy a file to a different location. If the target file already exists, this will attempt to delete it first, and will fail if this can't be done.
Returns
true if the operation succeeds
Definition at line 272 of file File.cpp.
References copyInternal(), deleteFile(), and exists().
 {
     return (*this == newFile)
             || (exists() && newFile.deleteFile() && copyInternal (newFile));
 }
bool beast::File::copyInternal (const File & dest) const private
Definition at line 36 of file bsd_Files.cpp.
References deleteFile(), beast::FileOutputStream::failedToOpen(), getSize(), Json::in(), and beast::OutputStream::writeFromInputStream().
Referenced by copyFileTo(), and moveInternal().
 {
     FileInputStream in (*this);
     if (dest.deleteFile())
     {
         {
             FileOutputStream out (dest);
             if (out.failedToOpen())
                 return false;
             if (out.writeFromInputStream (in, -1) == getSize())
                 return true;
         }
         dest.deleteFile();
     }
     return false;
 }
Result beast::File::create () const
Creates an empty file if it doesn't already exist.
If the file that this object refers to doesn't exist, this will create a file of zero size.
If it already exists or is a directory, this method will do nothing.
Returns
true if the file has been created (or if it already existed).
See Also
createDirectory
Definition at line 440 of file File.cpp.
References createDirectory(), exists(), beast::Result::fail(), getParentDirectory(), beast::FileOutputStream::getStatus(), and beast::Result::ok().
 {
     if (exists())
         return Result::ok();
     const File parentDir (getParentDirectory());
     if (parentDir == *this)
         return Result::fail ("Cannot create parent directory");
     Result r (parentDir.createDirectory());
     if (r.wasOk())
     {
         FileOutputStream fo (*this, 8);
         r = fo.getStatus();
     }
     return r;
 }
Result beast::File::createDirectory () const
Creates a new directory for this filename.
This will try to create the file as a directory, and fill also create any parent directories it needs in order to complete the operation.
Returns
a result to indicate whether the directory was created successfully, or an error message if it failed.
See Also
create
Definition at line 461 of file File.cpp.
References createDirectory(), createDirectoryInternal(), beast::Result::fail(), fullPath, getParentDirectory(), isDirectory(), beast::Result::ok(), separatorString, and beast::String::trimCharactersAtEnd().
Referenced by copyDirectoryTo(), create(), and createDirectory().
 {
     if (isDirectory())
         return Result::ok();
     const File parentDir (getParentDirectory());
     if (parentDir == *this)
         return Result::fail ("Cannot create parent directory");
     Result r (parentDir.createDirectory());
     if (r.wasOk())
         r = createDirectoryInternal (fullPath.trimCharactersAtEnd (separatorString));
     return r;
 }
Result beast::File::createDirectoryInternal (const String & fileName) const private
Definition at line 275 of file posix_SharedCode.h.
References beast::String::toUTF8().
Referenced by createDirectory().
 {
     return getResultForReturnValue (mkdir (fileName.toUTF8(), 0777));
 }
File beast::File::createFileWithoutCheckingPath (const String & absolutePath) static noexcept
Creates a file that simply contains this string, without doing the sanity-checking that the normal constructors do.
Best to avoid this unless you really know what you're doing.
Definition at line 59 of file File.cpp.
References ripple::f, fullPath, and beast.util.CleanCPPFiles::path.
Referenced by beast::DirectoryIterator::next(), and beast::Process::openDocument().
 {
     File f;
     f.fullPath = path;
     return f;
 }
FileInputStream * beast::File::createInputStream () const
Creates a stream to read from this file.
Returns
a stream that will read from this file (initially positioned at the start of the file), or nullptr if the file can't be opened for some reason
See Also
createOutputStream, loadFileAsData
Definition at line 675 of file File.cpp.
References beast::ScopedPointer< ObjectType >::release().
Referenced by beast::FileInputSource::createInputStream(), and beast::FileInputSource::createInputStreamFor().
 {
     ScopedPointer<FileInputStream> fin (new FileInputStream (*this));
     if (fin->openedOk())
         return fin.release();
     return nullptr;
 }
String beast::File::createLegalFileName (const String & fileNameToFix) static
Returns a version of a filename with any illegal characters removed.
This will return a copy of the given string after removing characters that are not allowed in a legal filename, and possibly shortening the string if it's too long.
Because this will remove slashes, don't use it on an absolute pathname - use createLegalPathName() for that.
See Also
createLegalPathName
Definition at line 789 of file File.cpp.
References beast::bmax(), beast::String::length(), and beast::String::removeCharacters().
 {
     String s (original.removeCharacters ("\"#@,;:<>*^|?\\/"));
     const int maxLength = 128; // only the length of the filename, not the whole path
     const int len = s.length();
     if (len > maxLength)
     {
         const int lastDot = s.lastIndexOfChar ('.');
         if (lastDot > bmax (0, len - 12))
         {
             s = s.substring (0, maxLength - (len - lastDot))
                  + s.substring (lastDot);
         }
         else
         {
             s = s.substring (0, maxLength);
         }
     }
     return s;
 }
String beast::File::createLegalPathName (const String & pathNameToFix) static
Returns a version of a path with any illegal characters removed.
Similar to createLegalFileName(), but this won't remove slashes, so can be used on a complete pathname.
See Also
createLegalFileName
Definition at line 774 of file File.cpp.
References beast::String::removeCharacters(), and beast::String::substring().
 {
     String s (original);
     String start;
     if (s[1] == ':')
     {
         start = s.substring (0, 2);
         s = s.substring (2);
     }
     return start + s.removeCharacters ("\"#@,;:<>*^|?")
                     .substring (0, 1024);
 }
FileOutputStream * beast::File::createOutputStream (size_t bufferSize = 0x8000) const
Creates a stream to write to this file.
If the file exists, the stream that is returned will be positioned ready for writing at the end of the file, so you might want to use deleteFile() first to write to an empty file.
Returns
a stream that will write to this file (initially positioned at the end of the file), or nullptr if the file can't be opened for some reason
See Also
createInputStream, appendData, appendText
Definition at line 685 of file File.cpp.
References beast::ScopedPointer< ObjectType >::release().
 {
     ScopedPointer<FileOutputStream> out (new FileOutputStream (*this, bufferSize));
     return out->failedToOpen() ? nullptr
                                : out.release();
 }
File beast::File::createTempFile (const String & fileNameEnding) static
Returns a temporary file in the system's temp directory. This will try to return the name of a non-existent temp file. To get the temp folder, you can use getSpecialLocation (File::tempDirectory).
Definition at line 894 of file File.cpp.
References exists(), getChildFile(), getSpecialLocation(), beast::Random::getSystemRandom(), tempDirectory, beast::String::toHexString(), and withFileExtension().
Referenced by ripple::NodeStore::Backend_test::testBackend(), ripple::NodeStore::NodeStoreTiming_test::testBackend(), beast::RandomAccessFile_test::testFile(), ripple::NodeStore::NodeStoreDatabase_test::testImport(), and ripple::NodeStore::NodeStoreDatabase_test::testNodeStore().
 {
     const File tempFile (getSpecialLocation (tempDirectory)
                             .getChildFile ("temp_" + String::toHexString (Random::getSystemRandom().nextInt()))
                             .withFileExtension (fileNameEnding));
     if (tempFile.exists())
         return createTempFile (fileNameEnding);
     return tempFile;
 }
bool beast::File::deleteFile () const
Deletes a file.
If this file is actually a directory, it may not be deleted correctly if it contains files. See deleteRecursively() as a better way of deleting directories.
Returns
true if the file has been successfully deleted (or if it didn't exist to begin with).
See Also
deleteRecursively
Definition at line 248 of file posix_SharedCode.h.
References exists(), fullPath, isDirectory(), and beast::String::toUTF8().
Referenced by beast::beast_getOutputFromCommand(), copyFileTo(), copyInternal(), deleteRecursively(), beast::TemporaryFile::deleteTemporaryFile(), moveFileTo(), moveInternal(), and replaceWithData().
 {
     if (! exists())
         return true;
     if (isDirectory())
         return rmdir (fullPath.toUTF8()) == 0;
     return remove (fullPath.toUTF8()) == 0;
 }
bool beast::File::deleteRecursively () const
Deletes a file or directory and all its subdirectories.
If this file is a directory, this will try to delete it and all its subfolders. If it's just a file, it will just try to delete the file.
Returns
true if the file and all its subfolders have been successfully deleted (or if it didn't exist to begin with).
See Also
deleteFile
Definition at line 239 of file File.cpp.
References deleteFile(), findChildFiles(), findFilesAndDirectories, beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getReference(), isDirectory(), and beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
 {
     bool worked = true;
     if (isDirectory())
     {
         Array<File> subFiles;
         findChildFiles (subFiles, File::findFilesAndDirectories, false);
         for (int i = subFiles.size(); --i >= 0;)
             worked = subFiles.getReference(i).deleteRecursively() && worked;
     }
     return deleteFile() && worked;
 }
String beast::File::descriptionOfSizeInBytes (std::int64_t bytes) static
Utility function to convert a file size in bytes to a neat string description.
So for example 100 would return "100 bytes", 2000 would return "2 KB", 2000000 would produce "2 MB", etc.
Definition at line 425 of file File.cpp.
 {
     const char* suffix;
     double divisor = 0;
     if (bytes == 1)                       { suffix = " byte"; }
     else if (bytes < 1024)                { suffix = " bytes"; }
     else if (bytes < 1024 * 1024)         { suffix = " KB"; divisor = 1024.0; }
     else if (bytes < 1024 * 1024 * 1024)  { suffix = " MB"; divisor = 1024.0 * 1024.0; }
     else                                  { suffix = " GB"; divisor = 1024.0 * 1024.0 * 1024.0; }
     return (divisor > 0 ? String (bytes / divisor, 1) : String (bytes)) + suffix;
 }
bool beast::File::exists () const
Checks whether the file actually exists.
Returns
true if the file exists, either as a file or a directory.
See Also
existsAsFile, isDirectory
Definition at line 171 of file posix_SharedCode.h.
References fullPath, beast::String::isNotEmpty(), and beast::String::toUTF8().
Referenced by copyFileTo(), create(), createTempFile(), deleteFile(), existsAsFile(), getNonexistentChildFile(), getNonexistentSibling(), hasWriteAccess(), moveFileTo(), moveToTrash(), beast::RandomAccessFile::nativeOpen(), beast::FileOutputStream::openHandle(), beast::TemporaryFile::overwriteTargetFileWithTemporary(), beast::File_test::run(), and startAsProcess().
 {
     return fullPath.isNotEmpty()
              && access (fullPath.toUTF8(), F_OK) == 0;
 }
bool beast::File::existsAsFile () const
Checks whether the file exists and is a file rather than a directory.
Returns
true only if this is a real file, false if it's a directory or doesn't exist
See Also
exists, isDirectory
Definition at line 177 of file posix_SharedCode.h.
References exists(), and isDirectory().
Referenced by getRelativePathFrom(), hasIdenticalContentTo(), loadFileAsData(), loadFileAsString(), and beast::File_test::run().
 {
     return exists() && ! isDirectory();
 }
int beast::File::findChildFiles (Array< File > & results, int whatToLookFor, bool searchRecursively, const String & wildCardPattern = "*") const
Searches inside a directory for files matching a wildcard pattern.
Assuming that this file is a directory, this method will search it for either files or subdirectories whose names match a filename pattern.
Parameters
results an array to which File objects will be added for the files that the search comes up with
whatToLookFor a value from the TypesOfFileToFind enum, specifying whether to return files, directories, or both. If the ignoreHiddenFiles flag is also added to this value, hidden files won't be returned
searchRecursively if true, all subdirectories will be recursed into to do an exhaustive search
wildCardPattern the filename pattern to search for, e.g. "*.txt"
Returns
the number of results that have been found
See Also
getNumberOfChildFiles, DirectoryIterator
Definition at line 514 of file File.cpp.
References beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::add(), beast::DirectoryIterator::getFile(), and beast::DirectoryIterator::next().
Referenced by copyDirectoryTo(), deleteRecursively(), beast::File_test::run(), and setReadOnly().
 {
     DirectoryIterator di (*this, searchRecursively, wildCardPattern, whatToLookFor);
     int total = 0;
     while (di.next())
     {
         results.add (di.getFile());
         ++total;
     }
     return total;
 }
void beast::File::findFileSystemRoots (Array< File > & results) static
Creates a set of files to represent each file root.
e.g. on Windows this will create files for "c:\", "d:\" etc according to which ones are available. On the Mac/Linux, this will probably just add a single entry for "/".
Definition at line 58 of file bsd_Files.cpp.
References beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::add().
Referenced by beast::File_test::run().
 {
     destArray.add (File ("/"));
 }
std::int64_t beast::File::getBytesFreeOnVolume () const
Returns the number of bytes free on the drive that this file lives on.
Returns
the number of bytes free, or 0 if there's a problem finding this out
See Also
getVolumeTotalSize
Definition at line 630 of file posix_SharedCode.h.
Referenced by beast::File_test::run().
 {
     struct statfs buf;
     if (beast_doStatFS (*this, buf))
         return (std::int64_t) buf.f_bsize * (std::int64_t) buf.f_bavail; // Note: this returns space available to non-super user
     return 0;
 }
File beast::File::getChildFile (String relativeOrAbsolutePath) const
Returns a file that represents a relative (or absolute) sub-path of the current one.
This will find a child file or directory of the current object.
e.g. File ("/moose/fish").getChildFile ("foo.txt") will produce "/moose/fish/foo.txt". File ("/moose/fish").getChildFile ("haddock/foo.txt") will produce "/moose/fish/haddock/foo.txt". File ("/moose/fish").getChildFile ("../foo.txt") will produce "/moose/foo.txt".
If the string is actually an absolute path, it will be treated as such, e.g. File ("/moose/fish").getChildFile ("/foo.txt") will produce "/foo.txt"
See Also
getSiblingFile, getParentDirectory, getRelativePathFrom, isAChildOf
Definition at line 370 of file File.cpp.
References addTrailingSeparator(), File(), fullPath, isAbsolutePath(), beast::String::lastIndexOfChar(), beast.util.CleanCPPFiles::path, beast::String::replaceCharacter(), separator, and beast::String::substring().
Referenced by beast::beast_getExecutableFile(), copyDirectoryTo(), createTempFile(), getNonexistentChildFile(), getSiblingFile(), ripple::Config::getValidatorsFile(), ripple::PeerFinder::ManagerImp::ManagerImp(), ripple::Validators::ManagerImp::ManagerImp(), parseAbsolutePath(), and beast::File_test::run().
 {
     if (isAbsolutePath (relativePath))
         return File (relativePath);
     String path (fullPath);
     // It's relative, so remove any ../ or ./ bits at the start..
     if (relativePath[0] == '.')
     {
        #if BEAST_WINDOWS
         relativePath = relativePath.replaceCharacter ('/', '\\');
        #endif
         while (relativePath[0] == '.')
         {
             const beast_wchar secondChar = relativePath[1];
             if (secondChar == '.')
             {
                 const beast_wchar thirdChar = relativePath[2];
                 if (thirdChar == 0 || thirdChar == separator)
                 {
                     const int lastSlash = path.lastIndexOfChar (separator);
                     if (lastSlash >= 0)
                         path = path.substring (0, lastSlash);
                     relativePath = relativePath.substring (3);
                 }
                 else
                 {
                     break;
                 }
             }
             else if (secondChar == separator)
             {
                 relativePath = relativePath.substring (2);
             }
             else
             {
                 break;
             }
         }
     }
     return File (addTrailingSeparator (path) + relativePath);
 }
Time beast::File::getCreationTime () const
Returns the time that this file was created.
Returns
the time, or an invalid time if the file doesn't exist.
See Also
getLastModificationTime, getLastAccessTime
Definition at line 482 of file File.cpp.
References getFileTimesInternal().
 { std::int64_t m, a, c; getFileTimesInternal (m, a, c); return Time (c); }
File beast::File::getCurrentWorkingDirectory () static
Returns the current working directory.
See Also
setAsCurrentWorkingDirectory
Definition at line 61 of file posix_SharedCode.h.
References File(), and beast::HeapBlock< ElementType, throwOnFailure >::malloc().
Referenced by beast::beast_getExecutableFile(), getSpecialLocation(), parseAbsolutePath(), and beast::File_test::run().
 {
     HeapBlock<char> heapBuffer;
     char localBuffer [1024];
     char* cwd = getcwd (localBuffer, sizeof (localBuffer) - 1);
     size_t bufferSize = 4096;
     while (cwd == nullptr && errno == ERANGE)
     {
         heapBuffer.malloc (bufferSize);
         cwd = getcwd (heapBuffer, bufferSize - 1);
         bufferSize += 1024;
     }
     return File (CharPointer_UTF8 (cwd));
 }
String beast::File::getFileExtension () const
Returns the file's extension.
Returns the file extension of this file, also including the dot.
e.g. "/moose/fish/foo.txt" would return ".txt"
See Also
hasFileExtension, withFileExtension, getFileNameWithoutExtension
Definition at line 612 of file File.cpp.
References beast::String::empty, fullPath, beast::String::lastIndexOfChar(), separator, and beast::String::substring().
Referenced by getNonexistentSibling(), and moveToTrash().
 {
     const int indexOfDot = fullPath.lastIndexOfChar ('.');
     if (indexOfDot > fullPath.lastIndexOfChar (separator))
         return fullPath.substring (indexOfDot);
     return String::empty;
 }
String beast::File::getFileName () const
Returns the last section of the pathname.
Returns just the final part of the path - e.g. if the whole path is "/moose/fish/foo.txt" this will return "foo.txt".
For a directory, it returns the final part of the path - e.g. for the directory "/moose/fish" it'll return "fish".
If the filename begins with a dot, it'll return the whole filename, e.g. for "/moose/.fish", it'll return ".fish"
See Also
getFullPathName, getFileNameWithoutExtension
Definition at line 324 of file File.cpp.
References fullPath, beast::String::lastIndexOfChar(), separator, and beast::String::substring().
Referenced by isHidden(), beast::FileHelpers::isHiddenFile(), and withFileExtension().
 {
     return fullPath.substring (fullPath.lastIndexOfChar (separator) + 1);
 }
String beast::File::getFileNameWithoutExtension () const
Returns the last part of the filename, without its file extension.
e.g. for "/moose/fish/foo.txt" this will return "foo".
See Also
getFileName, getFileExtension, hasFileExtension, withFileExtension
Definition at line 329 of file File.cpp.
References fullPath, beast::String::lastIndexOfChar(), separator, and beast::String::substring().
Referenced by getNonexistentSibling(), and moveToTrash().
 {
     const int lastSlash = fullPath.lastIndexOfChar (separator) + 1;
     const int lastDot   = fullPath.lastIndexOfChar ('.');
     if (lastDot > lastSlash)
         return fullPath.substring (lastSlash, lastDot);
     return fullPath.substring (lastSlash);
 }
void beast::File::getFileTimesInternal (std::int64_t & m, std::int64_t & a, std::int64_t & c) const private
Definition at line 217 of file posix_SharedCode.h.
References fullPath.
Referenced by getCreationTime(), getLastAccessTime(), and getLastModificationTime().
 {
     modificationTime = 0;
     accessTime = 0;
     creationTime = 0;
     beast_statStruct info;
     if (beast_stat (fullPath, info))
     {
         modificationTime = (std::int64_t) info.st_mtime * 1000;
         accessTime = (std::int64_t) info.st_atime * 1000;
         creationTime = (std::int64_t) info.st_ctime * 1000;
     }
 }
const String& beast::File::getFullPathName () const inline noexcept
Returns the complete, absolute path of this file.
This includes the filename and all its parent folders. On Windows it'll also include the drive letter prefix; on Mac or Linux it'll be a complete path starting from the root folder.
If you just want the file's name, you should use getFileName() or getFileNameWithoutExtension().
See Also
getFileName, getRelativePathFrom
Definition at line 156 of file File.h.
References fullPath.
Referenced by beast::FileSearchPath::add(), beast::beast_getOutputFromCommand(), ripple::Validators::SourceFileImp::createParam(), beast::FileOutputStream::flushInternal(), getLinkedTarget(), getRelativePathFrom(), getVolumeLabel(), ripple::PeerFinder::ManagerImp::init(), isOnCDRomDrive(), isOnHardDisk(), moveInternal(), beast::RandomAccessFile::nativeFlush(), beast::RandomAccessFile::nativeOpen(), ripple::Validators::StoreSqdb::open(), ripple::PeerFinder::StoreSqdb::open(), beast::FileInputStream::openHandle(), beast::FileOutputStream::openHandle(), parseAbsolutePath(), setAsCurrentWorkingDirectory(), ripple::NodeStore::Backend_test::testBackend(), ripple::NodeStore::NodeStoreTiming_test::testBackend(), ripple::NodeStore::NodeStoreDatabase_test::testImport(), ripple::NodeStore::NodeStoreDatabase_test::testNodeStore(), ripple::Validators::SourceFileImp::to_string(), and ripple::Validators::SourceFileImp::uniqueID().
 { return fullPath; }
Time beast::File::getLastAccessTime () const
Returns the last time this file was accessed.
Returns
the time, or an invalid time if the file doesn't exist.
See Also
setLastAccessTime, getLastModificationTime, getCreationTime
Definition at line 481 of file File.cpp.
References getFileTimesInternal().
 { std::int64_t m, a, c; getFileTimesInternal (m, a, c); return Time (a); }
Time beast::File::getLastModificationTime () const
Returns the last modification time of this file.
Returns
the time, or an invalid time if the file doesn't exist.
See Also
setLastModificationTime, getLastAccessTime, getCreationTime
Definition at line 480 of file File.cpp.
References getFileTimesInternal().
Referenced by beast::FileInputSource::hashCode().
 { std::int64_t m, a, c; getFileTimesInternal (m, a, c); return Time (m); }
File beast::File::getLinkedTarget () const
If this file is a link, this returns the file that it points to. If this file isn't actually link, it'll just return itself.
Definition at line 127 of file bsd_Files.cpp.
References getFullPathName().
 {
     return beast_readlink (getFullPathName().toUTF8(), *this);
 }
File beast::File::getNonexistentChildFile (const String & prefix, const String & suffix, bool putNumbersInBrackets = true) const
Chooses a filename relative to this one that doesn't already exist.
If this file is a directory, this will return a child file of this directory that doesn't exist, by adding numbers to a prefix and suffix until it finds one that isn't already there.
If the prefix + the suffix doesn't exist, it won't bother adding a number.
e.g. File ("/moose/fish").getNonexistentChildFile ("foo", ".txt", true) might return "/moose/fish/foo(2).txt" if there's already a file called "foo.txt".
Parameters
prefix the string to use for the filename before the number
suffix the string to add to the filename after the number
putNumbersInBrackets if true, this will create filenames in the format "prefix(number)suffix", if false, it will leave the brackets out.
Definition at line 552 of file File.cpp.
References beast::String::containsOnly(), beast::String::endsWithChar(), exists(), ripple::f, getChildFile(), beast::String::getIntValue(), beast::String::getLastCharacter(), beast::CharacterFunctions::isDigit(), beast::String::lastIndexOfChar(), std::chrono::prefix, beast::String::substring(), and beast::String::trim().
Referenced by beast::createTempFile(), getNonexistentSibling(), and moveToTrash().
 {
     File f (getChildFile (suggestedPrefix + suffix));
     if (f.exists())
     {
         int number = 1;
         String prefix (suggestedPrefix);
         // remove any bracketed numbers that may already be on the end..
         if (prefix.trim().endsWithChar (')'))
         {
             putNumbersInBrackets = true;
             const int openBracks  = prefix.lastIndexOfChar ('(');
             const int closeBracks = prefix.lastIndexOfChar (')');
             if (openBracks > 0
                  && closeBracks > openBracks
                  && prefix.substring (openBracks + 1, closeBracks).containsOnly ("0123456789"))
             {
                 number = prefix.substring (openBracks + 1, closeBracks).getIntValue();
                 prefix = prefix.substring (0, openBracks);
             }
         }
         // also use brackets if it ends in a digit.
         putNumbersInBrackets = putNumbersInBrackets
                                  || CharacterFunctions::isDigit (prefix.getLastCharacter());
         do
         {
             String newName (prefix);
             if (putNumbersInBrackets)
                 newName << '(' << ++number << ')';
             else
                 newName << ++number;
             f = getChildFile (newName + suffix);
         } while (f.exists());
     }
     return f;
 }
File beast::File::getNonexistentSibling (bool putNumbersInBrackets = true) const
Chooses a filename for a sibling file to this one that doesn't already exist.
If this file doesn't exist, this will just return itself, otherwise it will return an appropriate sibling that doesn't exist, e.g. if a file "/moose/fish/foo.txt" exists, this might return "/moose/fish/foo(2).txt".
Parameters
putNumbersInBrackets whether to add brackets around the numbers that get appended to the new filename.
Definition at line 601 of file File.cpp.
References exists(), getFileExtension(), getFileNameWithoutExtension(), getNonexistentChildFile(), and getParentDirectory().
 {
     if (! exists())
         return *this;
     return getParentDirectory().getNonexistentChildFile (getFileNameWithoutExtension(),
                                                          getFileExtension(),
                                                          putNumbersInBrackets);
 }
int beast::File::getNumberOfChildFiles (int whatToLookFor, const String & wildCardPattern = "*") const
Searches inside a directory and counts how many files match a wildcard pattern.
Assuming that this file is a directory, this method will search it for either files or subdirectories whose names match a filename pattern, and will return the number of matches found.
This isn't a recursive call, and will only search this directory, not its children.
Parameters
whatToLookFor a value from the TypesOfFileToFind enum, specifying whether to count files, directories, or both. If the ignoreHiddenFiles flag is also added to this value, hidden files won't be counted
wildCardPattern the filename pattern to search for, e.g. "*.txt"
Returns
the number of matches found
See Also
findChildFiles, DirectoryIterator
Definition at line 531 of file File.cpp.
References beast::DirectoryIterator::next().
Referenced by beast::DirectoryIterator::getEstimatedProgress().
 {
     DirectoryIterator di (*this, false, wildCardPattern, whatToLookFor);
     int total = 0;
     while (di.next())
         ++total;
     return total;
 }
File beast::File::getParentDirectory () const
Returns the directory that contains this file or directory.
e.g. for "/moose/fish/foo.txt" this will return "/moose/fish".
Definition at line 316 of file File.cpp.
References ripple::f, fullPath, and getPathUpToLastSlash().
Referenced by create(), createDirectory(), ripple::Config::getConfigDir(), getNonexistentSibling(), getRelativePathFrom(), getSiblingFile(), getVolumeLabel(), hasWriteAccess(), isAChildOf(), and beast::FileSearchPath::isFileInPath().
 {
     File f;
     f.fullPath = getPathUpToLastSlash();
     return f;
 }
String beast::File::getPathUpToLastSlash () const private
Definition at line 303 of file File.cpp.
References fullPath, beast::String::lastIndexOfChar(), separator, separatorString, and beast::String::substring().
Referenced by getParentDirectory(), and isAChildOf().
 {
     const int lastSlash = fullPath.lastIndexOfChar (separator);
     if (lastSlash > 0)
         return fullPath.substring (0, lastSlash);
     if (lastSlash == 0)
         return separatorString;
     return fullPath;
 }
String beast::File::getRelativePathFrom (const File & directoryToBeRelativeTo) const
Creates a relative path that refers to a file relatively to a given directory.
e.g. File ("/moose/foo.txt").getRelativePathFrom (File ("/moose/fish/haddock")) would return "../../foo.txt".
If it's not possible to navigate from one file to the other, an absolute path is returned. If the paths are invalid, an empty string may also be returned.
Parameters
directoryToBeRelativeTo the directory which the resultant string will be relative to. If this is actually a file rather than a directory, its parent directory will be used instead. If it doesn't exist, it's assumed to be a directory.
See Also
getChildFile, isAbsolutePath
Definition at line 833 of file File.cpp.
References addTrailingSeparator(), beast::String::appendCharPointer(), beast::countNumberOfSeparators(), beast::String::dropLastCharacters(), beast::String::endsWithChar(), existsAsFile(), fullPath, beast::CharPointer_UTF8::getAndAdvance(), beast::String::getCharPointer(), getFullPathName(), getParentDirectory(), beast::String::repeatedString(), separator, and beast::CharacterFunctions::toLowerCase().
 {
     String thisPath (fullPath);
     while (thisPath.endsWithChar (separator))
         thisPath = thisPath.dropLastCharacters (1);
     String dirPath (addTrailingSeparator (dir.existsAsFile() ? dir.getParentDirectory().getFullPathName()
                                                              : dir.fullPath));
     int commonBitLength = 0;
     String::CharPointerType thisPathAfterCommon (thisPath.getCharPointer());
     String::CharPointerType dirPathAfterCommon  (dirPath.getCharPointer());
     {
         String::CharPointerType thisPathIter (thisPath.getCharPointer());
         String::CharPointerType dirPathIter  (dirPath.getCharPointer());
         for (int i = 0;;)
         {
             const beast_wchar c1 = thisPathIter.getAndAdvance();
             const beast_wchar c2 = dirPathIter.getAndAdvance();
            #if NAMES_ARE_CASE_SENSITIVE
             if (c1 != c2
            #else
             if ((c1 != c2 && CharacterFunctions::toLowerCase (c1) != CharacterFunctions::toLowerCase (c2))
            #endif
                  || c1 == 0)
                 break;
             ++i;
             if (c1 == separator)
             {
                 thisPathAfterCommon = thisPathIter;
                 dirPathAfterCommon  = dirPathIter;
                 commonBitLength = i;
             }
         }
     }
     // if the only common bit is the root, then just return the full path..
     if (commonBitLength == 0 || (commonBitLength == 1 && thisPath[1] == separator))
         return fullPath;
     const int numUpDirectoriesNeeded = countNumberOfSeparators (dirPathAfterCommon);
     if (numUpDirectoriesNeeded == 0)
         return thisPathAfterCommon;
    #if BEAST_WINDOWS
     String s (String::repeatedString ("..\\", numUpDirectoriesNeeded));
    #else
     String s (String::repeatedString ("../",  numUpDirectoriesNeeded));
    #endif
     s.appendCharPointer (thisPathAfterCommon);
     return s;
 }
File beast::File::getSiblingFile (const String & siblingFileName) const
Returns a file which is in the same directory as this one.
This is equivalent to getParentDirectory().getChildFile (name).
See Also
getChildFile, getParentDirectory
Definition at line 419 of file File.cpp.
References getChildFile(), and getParentDirectory().
Referenced by beast::FileInputSource::createInputStreamFor(), and withFileExtension().
 {
     return getParentDirectory().getChildFile (fileName);
 }
std::int64_t beast::File::getSize () const
Returns the size of the file in bytes.
Returns
the number of bytes in the file, or 0 if it doesn't exist.
Definition at line 182 of file posix_SharedCode.h.
References fullPath.
Referenced by copyInternal(), ripple::Validators::SourceFileImp::fetch(), beast::FileInputStream::getTotalLength(), hasIdenticalContentTo(), and loadFileAsData().
 {
     beast_statStruct info;
     return beast_stat (fullPath, info) ? info.st_size : 0;
 }
File beast::File::getSpecialLocation (const SpecialLocationType type) static
Finds the location of a special type of file or directory, such as a home folder or documents folder.
See Also
SpecialLocationType
Definition at line 160 of file bsd_Files.cpp.
References bassertfalse, beast::beast_argc, beast::beast_argv, beast::beast_getExecutableFile(), commonApplicationDataDirectory, currentApplicationFile, currentExecutableFile, File(), getCurrentWorkingDirectory(), globalApplicationsDirectory, hostApplicationPath, invokedExecutableFile, isDirectory(), nonexistent(), beast::resolveXDGFolder(), tempDirectory, userApplicationDataDirectory, userDesktopDirectory, userDocumentsDirectory, userHomeDirectory, userMoviesDirectory, userMusicDirectory, and userPicturesDirectory.
Referenced by beast::beast_getOutputFromCommand(), createTempFile(), parseAbsolutePath(), beast::File_test::run(), and ripple::Validators::Logic_test::testLogic().
 {
     switch (type)
     {
         case userHomeDirectory:
         {
             const char* homeDir = getenv ("HOME");
             if (homeDir == nullptr)
             {
                 struct passwd* const pw = getpwuid (getuid());
                 if (pw != nullptr)
                     homeDir = pw->pw_dir;
             }
             return File (CharPointer_UTF8 (homeDir));
         }
         case userDocumentsDirectory:          return resolveXDGFolder ("XDG_DOCUMENTS_DIR", "~");
         case userMusicDirectory:              return resolveXDGFolder ("XDG_MUSIC_DIR",     "~");
         case userMoviesDirectory:             return resolveXDGFolder ("XDG_VIDEOS_DIR",    "~");
         case userPicturesDirectory:           return resolveXDGFolder ("XDG_PICTURES_DIR",  "~");
         case userDesktopDirectory:            return resolveXDGFolder ("XDG_DESKTOP_DIR",   "~/Desktop");
         case userApplicationDataDirectory:    return File ("~");
         case commonApplicationDataDirectory:  return File ("/var");
         case globalApplicationsDirectory:     return File ("/usr");
         case tempDirectory:
         {
             File tmp ("/var/tmp");
             if (! tmp.isDirectory())
             {
                 tmp = "/tmp";
                 if (! tmp.isDirectory())
                     tmp = File::getCurrentWorkingDirectory();
             }
             return tmp;
         }
         case invokedExecutableFile:
             if (beast_argv != nullptr && beast_argc > 0)
                 return File (CharPointer_UTF8 (beast_argv[0]));
             // deliberate fall-through...
         case currentExecutableFile:
         case currentApplicationFile:
             return beast_getExecutableFile();
         case hostApplicationPath:
             return beast_readlink ("/proc/self/exe", beast_getExecutableFile());
         default:
             bassertfalse; // unknown type?
             break;
     }
     return File::nonexistent ();
 }
String beast::File::getVersion () const
If possible, this will try to create a version string for the given file.
The OS may be able to look at the file and give a version for it - e.g. with executables, bundles, dlls, etc. If no version is available, this will return an empty string.
Definition at line 223 of file bsd_Files.cpp.
References beast::String::empty.
 {
     return String::empty; // xxx not yet implemented
 }
String beast::File::getVolumeLabel () const
Finds the name of the drive on which this file lives.
Returns
the volume label of the drive, or an empty string if this isn't possible
Definition at line 648 of file posix_SharedCode.h.
References beast::String::empty, ripple::f, beast::String::fromUTF8(), getFullPathName(), getParentDirectory(), beast::String::toUTF8(), and beast::zerostruct().
 {
    #if BEAST_MAC
     struct VolAttrBuf
     {
         u_int32_t       length;
         attrreference_t mountPointRef;
         char            mountPointSpace [MAXPATHLEN];
     } attrBuf;
     struct attrlist attrList;
     zerostruct (attrList); // (can't use "= { 0 }" on this object because it's typedef'ed as a C struct)
     attrList.bitmapcount = ATTR_BIT_MAP_COUNT;
     attrList.volattr = ATTR_VOL_INFO | ATTR_VOL_NAME;
     File f (*this);
     for (;;)
     {
         if (getattrlist (f.getFullPathName().toUTF8(), &attrList, &attrBuf, sizeof (attrBuf), 0) == 0)
             return String::fromUTF8 (((const char*) &attrBuf.mountPointRef) + attrBuf.mountPointRef.attr_dataoffset,
                                      (int) attrBuf.mountPointRef.attr_length);
         const File parent (f.getParentDirectory());
         if (f == parent)
             break;
         f = parent;
     }
    #endif
     return String::empty;
 }
int beast::File::getVolumeSerialNumber () const
Returns the serial number of the volume on which this file lives.
Returns
the serial number, or zero if there's a problem doing this
Definition at line 683 of file posix_SharedCode.h.
 {
     int result = 0;
 /*    int fd = open (getFullPathName().toUTF8(), O_RDONLY | O_NONBLOCK);
     char info [512];
     #ifndef HDIO_GET_IDENTITY
      #define HDIO_GET_IDENTITY 0x030d
     #endif
     if (ioctl (fd, HDIO_GET_IDENTITY, info) == 0)
     {
         DBG (String (info + 20, 20));
         result = String (info + 20, 20).trim().getIntValue();
     }
     close (fd);*/
     return result;
 }
std::int64_t beast::File::getVolumeTotalSize () const
Returns the total size of the drive that contains this file.
Returns
the total number of bytes that the volume can hold
See Also
getBytesFreeOnVolume
Definition at line 639 of file posix_SharedCode.h.
Referenced by beast::File_test::run().
 {
     struct statfs buf;
     if (beast_doStatFS (*this, buf))
         return (std::int64_t) buf.f_bsize * (std::int64_t) buf.f_blocks;
     return 0;
 }
bool beast::File::hasFileExtension (const String & extensionToTest) const
Checks whether the file has a given extension.
Parameters
extensionToTest the extension to look for - it doesn't matter whether or not this string has a dot at the start, so ".wav" and "wav" will have the same effect. To compare with multiple extensions, this parameter can contain multiple strings, separated by semi-colons - so, for example: hasFileExtension (".jpeg;png;gif") would return true if the file has any of those three extensions.
See Also
getFileExtension, withFileExtension, getFileNameWithoutExtension
Definition at line 622 of file File.cpp.
References beast::String::endsWithIgnoreCase(), fullPath, beast::String::indexOfChar(), beast::String::isEmpty(), beast::String::lastIndexOfChar(), beast::String::length(), separator, beast::String::startsWithChar(), beast::String::substring(), beast::String::trimEnd(), and beast::String::trimStart().
 {
     if (possibleSuffix.isEmpty())
         return fullPath.lastIndexOfChar ('.') <= fullPath.lastIndexOfChar (separator);
     const int semicolon = possibleSuffix.indexOfChar (0, ';');
     if (semicolon >= 0)
     {
         return hasFileExtension (possibleSuffix.substring (0, semicolon).trimEnd())
                 || hasFileExtension (possibleSuffix.substring (semicolon + 1).trimStart());
     }
     else
     {
         if (fullPath.endsWithIgnoreCase (possibleSuffix))
         {
             if (possibleSuffix.startsWithChar ('.'))
                 return true;
             const int dotPos = fullPath.length() - possibleSuffix.length() - 1;
             if (dotPos >= 0)
                 return fullPath [dotPos] == '.';
         }
     }
     return false;
 }
int beast::File::hashCode () const
Returns a 32-bit hash-code that identifies this file.
This is based on the filename. Obviously it's possible, although unlikely, that two files will have the same hash-code.
Definition at line 356 of file File.cpp.
References fullPath, and beast::String::hashCode().
Referenced by beast::FileInputSource::hashCode().
 { return fullPath.hashCode(); }
std::int64_t beast::File::hashCode64 () const
Returns a 64-bit hash-code that identifies this file.
This is based on the filename. Obviously it's possible, although unlikely, that two files will have the same hash-code.
Definition at line 357 of file File.cpp.
References fullPath, and beast::String::hashCode64().
 { return fullPath.hashCode64(); }
bool beast::File::hasIdenticalContentTo (const File & other) const
Attempts to scan the contents of this file and compare it to another file, returning true if this is possible and they match byte-for-byte.
Definition at line 739 of file File.cpp.
References existsAsFile(), getSize(), beast::FileInputStream::openedOk(), and beast::FileInputStream::read().
 {
     if (other == *this)
         return true;
     if (getSize() == other.getSize() && existsAsFile() && other.existsAsFile())
     {
         FileInputStream in1 (*this), in2 (other);
         if (in1.openedOk() && in2.openedOk())
         {
             const int bufferSize = 4096;
             HeapBlock <char> buffer1 (bufferSize), buffer2 (bufferSize);
             for (;;)
             {
                 const int num1 = in1.read (buffer1, bufferSize);
                 const int num2 = in2.read (buffer2, bufferSize);
                 if (num1 != num2)
                     break;
                 if (num1 <= 0)
                     return true;
                 if (memcmp (buffer1, buffer2, (size_t) num1) != 0)
                     break;
             }
         }
     }
     return false;
 }
bool beast::File::hasWriteAccess () const
Checks whether a file can be created or written to.
Returns
true if it's possible to create and write to this file. If the file doesn't already exist, this will check its parent directory to see if writing is allowed.
See Also
setReadOnly
Definition at line 189 of file posix_SharedCode.h.
References beast::String::containsChar(), exists(), fullPath, getParentDirectory(), hasWriteAccess(), isDirectory(), separator, and beast::String::toUTF8().
Referenced by hasWriteAccess(), and moveInternal().
 {
     if (exists())
         return access (fullPath.toUTF8(), W_OK) == 0;
     if ((! isDirectory()) && fullPath.containsChar (separator))
         return getParentDirectory().hasWriteAccess();
     return false;
 }
bool beast::File::isAbsolutePath (const String & path) static
Returns true if the string seems to be a fully-specified absolute path.
Definition at line 360 of file File.cpp.
References beast::String::isNotEmpty(), separator, and beast::String::startsWithChar().
Referenced by getChildFile().
 {
     return path.startsWithChar (separator)
            #if BEAST_WINDOWS
             || (path.isNotEmpty() && path[1] == ':');
            #else
             || path.startsWithChar ('~');
            #endif
 }
bool beast::File::isAChildOf (const File & potentialParentDirectory) const
Checks whether a file is somewhere inside a directory.
Returns true if this file is somewhere inside a subdirectory of the directory that is passed in. Neither file actually has to exist, because the function just checks the paths for similarities.
e.g. File ("/moose/fish/foo.txt").isAChildOf ("/moose") is true. File ("/moose/fish/foo.txt").isAChildOf ("/moose/fish") is also true.
Definition at line 340 of file File.cpp.
References beast::compareFilenames(), fullPath, getParentDirectory(), getPathUpToLastSlash(), isAChildOf(), beast::String::length(), and nonexistent().
Referenced by isAChildOf(), beast::FileSearchPath::isFileInPath(), and beast::FileSearchPath::removeRedundantPaths().
 {
     if (potentialParent == File::nonexistent ())
         return false;
     const String ourPath (getPathUpToLastSlash());
     if (compareFilenames (potentialParent.fullPath, ourPath) == 0)
         return true;
     if (potentialParent.fullPath.length() >= ourPath.length())
         return false;
     return getParentDirectory().isAChildOf (potentialParent);
 }
bool beast::File::isDirectory () const
Checks whether the file is a directory that exists.
Returns
true only if the file is a directory which actually exists, so false if it's a file or doesn't exist at all
See Also
exists, existsAsFile
Definition at line 163 of file posix_SharedCode.h.
References fullPath, and beast::String::isEmpty().
Referenced by containsSubDirectories(), copyDirectoryTo(), createDirectory(), deleteFile(), deleteRecursively(), existsAsFile(), getSpecialLocation(), hasWriteAccess(), ripple::PeerFinder::ManagerImp::ManagerImp(), ripple::Validators::ManagerImp::ManagerImp(), moveToTrash(), beast::Process::openDocument(), beast::FileSearchPath::removeNonExistentPaths(), beast::File_test::run(), and setReadOnly().
 {
     beast_statStruct info;
     return fullPath.isEmpty()
             || (beast_stat (fullPath, info) && ((info.st_mode & S_IFDIR) != 0));
 }
bool beast::File::isHidden () const
Returns true if this file is a hidden or system file. The criteria for deciding whether a file is hidden are platform-dependent.
Definition at line 104 of file bsd_Files.cpp.
References getFileName(), and beast::String::startsWithChar().
Referenced by beast::File_test::run().
 {
     return getFileName().startsWithChar ('.');
 }
bool beast::File::isOnCDRomDrive () const
Returns true if this file is on a CD or DVD drive.
Definition at line 64 of file bsd_Files.cpp.
References getFullPathName(), and beast::U_ISOFS_SUPER_MAGIC.
Referenced by beast::File_test::run().
 {
     struct statfs buf;
     return statfs (getFullPathName().toUTF8(), &buf) == 0
              && buf.f_type == (short) U_ISOFS_SUPER_MAGIC;
 }
bool beast::File::isOnHardDisk () const
Returns true if this file is on a hard disk.
This will fail if it's a network drive, but will still be true for removable hard-disks.
Definition at line 72 of file bsd_Files.cpp.
References getFullPathName(), beast::U_ISOFS_SUPER_MAGIC, beast::U_MSDOS_SUPER_MAGIC, beast::U_NFS_SUPER_MAGIC, and beast::U_SMB_SUPER_MAGIC.
Referenced by beast::File_test::run().
 {
     struct statfs buf;
     if (statfs (getFullPathName().toUTF8(), &buf) == 0)
     {
         switch (buf.f_type)
         {
             case U_ISOFS_SUPER_MAGIC:   // CD-ROM
             case U_MSDOS_SUPER_MAGIC:   // Probably floppy (but could be mounted FAT filesystem)
             case U_NFS_SUPER_MAGIC:     // Network NFS
             case U_SMB_SUPER_MAGIC:     // Network Samba
                 return false;
             default:
                 // Assume anything else is a hard-disk (but note it could
                 // be a RAM disk.  There isn't a good way of determining
                 // this for sure)
                 return true;
         }
     }
     // Assume so if this fails for some reason
     return true;
 }
bool beast::File::isOnRemovableDrive () const
Returns true if this file is on a removable disk drive.
This might be a usb-drive, a CD-rom, or maybe a network drive.
Definition at line 98 of file bsd_Files.cpp.
References bassertfalse.
 {
     bassertfalse; // XXX not implemented for FreeBSD!
     return false;
 }
bool beast::File::loadFileAsData (MemoryBlock & result) const
Loads a file's contents into memory as a block of binary data.
Of course, trying to load a very large file into memory will blow up, so it's better to check first.
Parameters
result the data block to which the file's contents should be appended - note that if the memory block might already contain some data, you might want to clear it first
Returns
true if the file could all be read into memory
Definition at line 489 of file File.cpp.
References existsAsFile(), getSize(), Json::in(), beast::FileInputStream::openedOk(), and beast::InputStream::readIntoMemoryBlock().
 {
     if (! existsAsFile())
         return false;
     FileInputStream in (*this);
     return in.openedOk() && getSize() == in.readIntoMemoryBlock (destBlock);
 }
String beast::File::loadFileAsString () const
Reads a file into memory as a string.
Attempts to load the entire file as a zero-terminated string.
This makes use of InputStream::readEntireStreamAsString, which can read either UTF-16 or UTF-8 file formats.
Definition at line 498 of file File.cpp.
References beast::String::empty, existsAsFile(), Json::in(), beast::FileInputStream::openedOk(), and beast::InputStream::readEntireStreamAsString().
Referenced by beast::beast_getOutputFromCommand(), and readLines().
 {
     if (! existsAsFile())
         return String::empty;
     FileInputStream in (*this);
     return in.openedOk() ? in.readEntireStreamAsString()
                          : String::empty;
 }
bool beast::File::moveFileTo (const File & targetLocation) const
Moves or renames a file.
Tries to move a file to a different location. If the target file already exists, this will attempt to delete it first, and will fail if this can't be done.
Note that the destination file isn't the directory to put it in, it's the actual filename that you want the new file to have.
Returns
true if the operation succeeds
Definition at line 255 of file File.cpp.
References deleteFile(), exists(), fullPath, and moveInternal().
Referenced by moveToTrash(), and beast::TemporaryFile::overwriteTargetFileWithTemporary().
 {
     if (newFile.fullPath == fullPath)
         return true;
     if (! exists())
         return false;
    #if ! NAMES_ARE_CASE_SENSITIVE
     if (*this != newFile)
    #endif
         if (! newFile.deleteFile())
             return false;
     return moveInternal (newFile);
 }
bool beast::File::moveInternal (const File & dest) const private
Definition at line 259 of file posix_SharedCode.h.
References copyInternal(), deleteFile(), fullPath, getFullPathName(), hasWriteAccess(), and beast::String::toUTF8().
Referenced by moveFileTo().
 {
     if (rename (fullPath.toUTF8(), dest.getFullPathName().toUTF8()) == 0)
         return true;
     if (hasWriteAccess() && copyInternal (dest))
     {
         if (deleteFile())
             return true;
         dest.deleteFile();
     }
     return false;
 }
bool beast::File::moveToTrash () const
Moves this file or folder to the trash.
Returns
true if the operation succeeded. It could fail if the trash is full, or if the file is write-protected, so you should check the return value and act appropriately.
Definition at line 229 of file bsd_Files.cpp.
References exists(), getFileExtension(), getFileNameWithoutExtension(), getNonexistentChildFile(), isDirectory(), and moveFileTo().
 {
     if (! exists())
         return true;
     File trashCan ("~/.Trash");
     if (! trashCan.isDirectory())
         trashCan = "~/.local/share/Trash/files";
     if (! trashCan.isDirectory())
         return false;
     return moveFileTo (trashCan.getNonexistentChildFile (getFileNameWithoutExtension(),
                                                          getFileExtension()));
 }
File const & beast::File::nonexistent () static
This static constant is used for referring to an 'invalid' file.
Definition at line 42 of file File.cpp.
References beast::NonexistentHolder::file, and beast::NonexistentHolder::getInstance().
Referenced by ripple::Config::getConfigDir(), ripple::Config::getDatabaseDir(), beast::WindowsFileHelpers::getSpecialFolderPath(), getSpecialLocation(), ripple::Config::getValidatorsFile(), isAChildOf(), beast::RandomAccessFile::nativeClose(), beast::TemporaryFile::overwriteTargetFileWithTemporary(), ripple::ApplicationImp::prepareValidators(), beast::File_test::run(), beast::TemporaryFile::TemporaryFile(), and withFileExtension().
 {
     return NonexistentHolder::getInstance ()->file;
 }
bool beast::File::operator!= (const File & other) const
Compares the pathnames for two files.
Definition at line 217 of file File.cpp.
References beast::compareFilenames(), and fullPath.
 { return compareFilenames (fullPath, other.fullPath) != 0; }
bool beast::File::operator< (const File & other) const
Compares the pathnames for two files.
Definition at line 218 of file File.cpp.
References beast::compareFilenames(), and fullPath.
 { return compareFilenames (fullPath, other.fullPath) <  0; }
File & beast::File::operator= (const String & newAbsolutePath)
Sets the file based on an absolute pathname.
If the path supplied is a relative path, it is taken to be relative to the current working directory (see File::getCurrentWorkingDirectory()), but this isn't a recommended way of creating a file, because you never know what the CWD is going to be.
On the Mac/Linux, the path can include "~" notation for referring to user home directories.
Definition at line 66 of file File.cpp.
References fullPath, and parseAbsolutePath().
 {
     fullPath = parseAbsolutePath (newPath);
     return *this;
 }
File & beast::File::operator= (const File & otherFile)
Copies from another file object.
Definition at line 72 of file File.cpp.
References fullPath.
 {
     fullPath = other.fullPath;
     return *this;
 }
bool beast::File::operator== (const File & other) const
Compares the pathnames for two files.
Definition at line 216 of file File.cpp.
References beast::compareFilenames(), and fullPath.
 { return compareFilenames (fullPath, other.fullPath) == 0; }
bool beast::File::operator> (const File & other) const
Compares the pathnames for two files.
Definition at line 219 of file File.cpp.
References beast::compareFilenames(), and fullPath.
 { return compareFilenames (fullPath, other.fullPath) >  0; }
String beast::File::parseAbsolutePath (const String & p) static private
Definition at line 92 of file File.cpp.
References addTrailingSeparator(), bassert, bassertfalse, beast::String::containsChar(), beast::String::dropLastCharacters(), beast::String::empty, beast::String::endsWithChar(), beast::String::fromFirstOccurrenceOf(), getChildFile(), getCurrentWorkingDirectory(), getFullPathName(), getSpecialLocation(), beast::String::indexOfChar(), beast::String::isEmpty(), beast.util.CleanCPPFiles::path, beast::String::replaceCharacter(), separator, separatorString, beast::String::startsWith(), beast::String::startsWithChar(), beast::String::substring(), beast::String::upToFirstOccurrenceOf(), userHomeDirectory, and beast::Logger::writeToLog().
Referenced by operator=().
 {
     if (p.isEmpty())
         return String::empty;
 #if BEAST_WINDOWS
     // Windows..
     String path (p.replaceCharacter ('/', '\\'));
     if (path.startsWithChar (separator))
     {
         if (path[1] != separator)
         {
             /*  When you supply a raw string to the File object constructor, it must be an absolute path.
                 If you're trying to parse a string that may be either a relative path or an absolute path,
                 you MUST provide a context against which the partial path can be evaluated - you can do
                 this by simply using File::getChildFile() instead of the File constructor. E.g. saying
                 "File::getCurrentWorkingDirectory().getChildFile (myUnknownPath)" would return an absolute
                 path if that's what was supplied, or would evaluate a partial path relative to the CWD.
             */
             bassertfalse;
             path = File::getCurrentWorkingDirectory().getFullPathName().substring (0, 2) + path;
         }
     }
     else if (! path.containsChar (':'))
     {
         /*  When you supply a raw string to the File object constructor, it must be an absolute path.
             If you're trying to parse a string that may be either a relative path or an absolute path,
             you MUST provide a context against which the partial path can be evaluated - you can do
             this by simply using File::getChildFile() instead of the File constructor. E.g. saying
             "File::getCurrentWorkingDirectory().getChildFile (myUnknownPath)" would return an absolute
             path if that's what was supplied, or would evaluate a partial path relative to the CWD.
         */
         bassertfalse;
         return File::getCurrentWorkingDirectory().getChildFile (path).getFullPathName();
     }
 #else
     // Mac or Linux..
     // Yes, I know it's legal for a unix pathname to contain a backslash, but this assertion is here
     // to catch anyone who's trying to run code that was written on Windows with hard-coded path names.
     // If that's why you've ended up here, use File::getChildFile() to build your paths instead.
     bassert ((! p.containsChar ('\\')) || (p.indexOfChar ('/') >= 0 && p.indexOfChar ('/') < p.indexOfChar ('\\')));
     String path (p);
     if (path.startsWithChar ('~'))
     {
         if (path[1] == separator || path[1] == 0)
         {
             // expand a name of the form "~/abc"
             path = File::getSpecialLocation (File::userHomeDirectory).getFullPathName()
                     + path.substring (1);
         }
         else
         {
             // expand a name of type "~dave/abc"
             const String userName (path.substring (1).upToFirstOccurrenceOf ("/", false, false));
             if (struct passwd* const pw = getpwnam (userName.toUTF8()))
                 path = addTrailingSeparator (pw->pw_dir) + path.fromFirstOccurrenceOf ("/", false, false);
         }
     }
     else if (! path.startsWithChar (separator))
     {
        #if BEAST_DEBUG || BEAST_LOG_ASSERTIONS
         if (! (path.startsWith ("./") || path.startsWith ("../")))
         {
             /*  When you supply a raw string to the File object constructor, it must be an absolute path.
                 If you're trying to parse a string that may be either a relative path or an absolute path,
                 you MUST provide a context against which the partial path can be evaluated - you can do
                 this by simply using File::getChildFile() instead of the File constructor. E.g. saying
                 "File::getCurrentWorkingDirectory().getChildFile (myUnknownPath)" would return an absolute
                 path if that's what was supplied, or would evaluate a partial path relative to the CWD.
             */
             bassertfalse;
            #if BEAST_LOG_ASSERTIONS
             Logger::writeToLog ("Illegal absolute path: " + path);
            #endif
         }
        #endif
         return File::getCurrentWorkingDirectory().getChildFile (path).getFullPathName();
     }
 #endif
     while (path.endsWithChar (separator) && path != separatorString) // careful not to turn a single "/" into an empty string.
         path = path.dropLastCharacters (1);
     return path;
 }
void beast::File::readLines (StringArray & destLines) const
Reads the contents of this file as text and splits it into lines, which are appended to the given StringArray.
Definition at line 508 of file File.cpp.
References beast::StringArray::addLines(), and loadFileAsString().
Referenced by beast::LinuxStatsHelpers::getCpuInfo(), beast::BSDStatsHelpers::getDmesgInfo(), and beast::resolveXDGFolder().
 {
     destLines.addLines (loadFileAsString());
 }
bool beast::File::replaceWithData (const void * dataToWrite, size_t numberOfBytes) const
Replaces this file's contents with a given block of data.
This will delete the file and replace it with the given data.
A nice feature of this method is that it's safe - instead of deleting the file first and then re-writing it, it creates a new temporary file, writes the data to that, and then moves the new file to replace the existing file. This means that if the power gets pulled out or something crashes, you're a lot less likely to end up with a corrupted or unfinished file..
Returns true if the operation succeeds, or false if it fails.
See Also
appendText
Definition at line 706 of file File.cpp.
References appendData(), deleteFile(), beast::TemporaryFile::getFile(), beast::TemporaryFile::overwriteTargetFileWithTemporary(), and beast::TemporaryFile::useHiddenFile.
 {
     if (numberOfBytes == 0)
         return deleteFile();
     TemporaryFile tempFile (*this, TemporaryFile::useHiddenFile);
     tempFile.getFile().appendData (dataToWrite, numberOfBytes);
     return tempFile.overwriteTargetFileWithTemporary();
 }
bool beast::File::replaceWithText (const String & textToWrite, bool asUnicode = false, bool writeUnicodeHeaderBytes = false) const
Replaces this file's contents with a given text string.
This will delete the file and replace it with the given text.
A nice feature of this method is that it's safe - instead of deleting the file first and then re-writing it, it creates a new temporary file, writes the text to that, and then moves the new file to replace the existing file. This means that if the power gets pulled out or something crashes, you're a lot less likely to end up with an empty file..
For an explanation of the parameters here, see the appendText() method.
Returns true if the operation succeeds, or false if it fails.
See Also
appendText
Definition at line 730 of file File.cpp.
References appendText(), beast::TemporaryFile::getFile(), beast::TemporaryFile::overwriteTargetFileWithTemporary(), and beast::TemporaryFile::useHiddenFile.
 {
     TemporaryFile tempFile (*this, TemporaryFile::useHiddenFile);
     tempFile.getFile().appendText (textToWrite, asUnicode, writeUnicodeHeaderBytes);
     return tempFile.overwriteTargetFileWithTemporary();
 }
void beast::File::revealToUser () const
Opens Finder, Explorer, or whatever the OS uses, to show the user this file's location.
See Also
startAsProcess
Definition at line 366 of file bsd_Files.cpp.
 {
     if (isDirectory())
         startAsProcess();
     else if (getParentDirectory().exists())
         getParentDirectory().startAsProcess();
 }
bool beast::File::setAsCurrentWorkingDirectory () const
Sets the current working directory to be this file.
For this to work the file must point to a valid directory.
Returns
true if the current directory has been changed.
See Also
getCurrentWorkingDirectory
Definition at line 79 of file posix_SharedCode.h.
References getFullPathName().
Referenced by beast::File_test::run().
 {
     return chdir (getFullPathName().toUTF8()) == 0;
 }
bool beast::File::setCreationTime (Time newTime) const
Changes the creation date for this file.
Parameters
newTime the time to apply to the file
Returns
true if it manages to change the file's time.
See Also
getCreationTime, setLastModificationTime, setLastAccessTime
Definition at line 486 of file File.cpp.
References setFileTimesInternal(), and beast::Time::toMilliseconds().
 { return setFileTimesInternal (0, 0, t.toMilliseconds()); }
bool beast::File::setFileReadOnlyInternal (bool shouldBeReadOnly) const private
Definition at line 200 of file posix_SharedCode.h.
References fullPath, and beast::String::toUTF8().
Referenced by setReadOnly().
 {
     beast_statStruct info;
     if (! beast_stat (fullPath, info))
         return false;
     info.st_mode &= 0777;   // Just permissions
     if (shouldBeReadOnly)
         info.st_mode &= ~(S_IWUSR | S_IWGRP | S_IWOTH);
     else
         // Give everybody write permission?
         info.st_mode |= S_IWUSR | S_IWGRP | S_IWOTH;
     return chmod (fullPath.toUTF8(), info.st_mode) == 0;
 }
bool beast::File::setFileTimesInternal (std::int64_t m, std::int64_t a, std::int64_t c) const private
Definition at line 232 of file posix_SharedCode.h.
References fullPath, and beast::String::toUTF8().
Referenced by setCreationTime(), setLastAccessTime(), and setLastModificationTime().
 {
     beast_statStruct info;
     if ((modificationTime != 0 || accessTime != 0) && beast_stat (fullPath, info))
     {
         struct utimbuf times;
         times.actime  = accessTime != 0       ? (time_t) (accessTime / 1000)       : info.st_atime;
         times.modtime = modificationTime != 0 ? (time_t) (modificationTime / 1000) : info.st_mtime;
         return utime (fullPath.toUTF8(), &times) == 0;
     }
     return false;
 }
bool beast::File::setLastAccessTime (Time newTime) const
Changes the last-access time for this file.
Parameters
newTime the time to apply to the file
Returns
true if it manages to change the file's time.
See Also
getLastAccessTime, setLastModificationTime, setCreationTime
Definition at line 485 of file File.cpp.
References setFileTimesInternal(), and beast::Time::toMilliseconds().
 { return setFileTimesInternal (0, t.toMilliseconds(), 0); }
bool beast::File::setLastModificationTime (Time newTime) const
Changes the modification time for this file.
Parameters
newTime the time to apply to the file
Returns
true if it manages to change the file's time.
See Also
getLastModificationTime, setLastAccessTime, setCreationTime
Definition at line 484 of file File.cpp.
References setFileTimesInternal(), and beast::Time::toMilliseconds().
 { return setFileTimesInternal (t.toMilliseconds(), 0, 0); }
bool beast::File::setReadOnly (bool shouldBeReadOnly, bool applyRecursively = false) const
Changes the write-permission of a file or directory.
Parameters
shouldBeReadOnly whether to add or remove write-permission
applyRecursively if the file is a directory and this is true, it will recurse through all the subfolders changing the permissions of all files
Returns
true if it manages to change the file's permissions.
See Also
hasWriteAccess
Definition at line 222 of file File.cpp.
References findChildFiles(), findFilesAndDirectories, beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getReference(), isDirectory(), setFileReadOnlyInternal(), and beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
 {
     bool worked = true;
     if (applyRecursively && isDirectory())
     {
         Array <File> subFiles;
         findChildFiles (subFiles, File::findFilesAndDirectories, false);
         for (int i = subFiles.size(); --i >= 0;)
             worked = subFiles.getReference(i).setReadOnly (shouldBeReadOnly, true) && worked;
     }
     return setFileReadOnlyInternal (shouldBeReadOnly) && worked;
 }
bool beast::File::startAsProcess (const String & parameters = String::empty) const
Launches the file as a process.
if the file is executable, this will run it.
if it's a document of some kind, it will launch the document with its default viewer application.
if it's a folder, it will be opened in Explorer, Finder, or equivalent.
See Also
revealToUser
Definition at line 669 of file File.cpp.
References exists(), fullPath, and beast::Process::openDocument().
 {
     return exists() && Process::openDocument (fullPath, parameters);
 }
File beast::File::withFileExtension (const String & newExtension) const
Returns a version of this file with a different file extension.
e.g. File ("/moose/fish/foo.txt").withFileExtension ("html") returns "/moose/fish/foo.html"
Parameters
newExtension the new extension, either with or without a dot at the start (this doesn't make any difference). To get remove a file's extension altogether, pass an empty string into this function.
See Also
getFileName, getFileExtension, hasFileExtension, getFileNameWithoutExtension
Definition at line 651 of file File.cpp.
References fullPath, getFileName(), getSiblingFile(), beast::String::isEmpty(), beast::String::isNotEmpty(), beast::String::lastIndexOfChar(), nonexistent(), beast::String::startsWithChar(), and beast::String::substring().
Referenced by createTempFile().
 {
     if (fullPath.isEmpty())
         return File::nonexistent ();
     String filePart (getFileName());
     const int i = filePart.lastIndexOfChar ('.');
     if (i >= 0)
         filePart = filePart.substring (0, i);
     if (newExtension.isNotEmpty() && ! newExtension.startsWithChar ('.'))
         filePart << '.';
     return getSiblingFile (filePart + newExtension);
 }
Member Data Documentation
String beast::File::fullPath private
Definition at line 950 of file File.h.
Referenced by createDirectory(), createFileWithoutCheckingPath(), deleteFile(), exists(), getChildFile(), getFileExtension(), getFileName(), getFileNameWithoutExtension(), getFileTimesInternal(), getFullPathName(), getParentDirectory(), getPathUpToLastSlash(), getRelativePathFrom(), getSize(), hasFileExtension(), hashCode(), hashCode64(), hasWriteAccess(), isAChildOf(), isDirectory(), moveFileTo(), moveInternal(), operator!=(), operator<(), operator=(), operator==(), operator>(), setFileReadOnlyInternal(), setFileTimesInternal(), startAsProcess(), and withFileExtension().
const beast_wchar beast::File::separator = '/' static
The system-specific file separator character. On Windows, this will be '\', on Mac/Linux, it'll be '/'
Definition at line 883 of file File.h.
Referenced by addTrailingSeparator(), beast::countNumberOfSeparators(), getChildFile(), getFileExtension(), getFileName(), getFileNameWithoutExtension(), getPathUpToLastSlash(), getRelativePathFrom(), hasFileExtension(), hasWriteAccess(), isAbsolutePath(), and parseAbsolutePath().
const String beast::File::separatorString static
The system-specific file separator character, as a string. On Windows, this will be '\', on Mac/Linux, it'll be '/'
Definition at line 888 of file File.h.
Referenced by createDirectory(), getPathUpToLastSlash(), parseAbsolutePath(), and beast::File_test::run().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_core/files/File.h
rippled/src/beast/modules/beast_core/files/File.cpp
rippled/src/beast/modules/beast_core/native/bsd_Files.cpp
rippled/src/beast/modules/beast_core/native/linux_Files.cpp
rippled/src/beast/modules/beast_core/native/mac_Files.mm
rippled/src/beast/modules/beast_core/native/posix_SharedCode.h
rippled/src/beast/modules/beast_core/native/win32_Files.cpp