rippled: ripple::core::Quality Class Reference
ripple::core::Quality Class Reference
#include <Quality.h>
Public Types
typedef std::uint64_t value_type
Public Member Functions
Quality ()=default
Quality (std::uint64_t value)
Quality (Amounts const &amount)
Amount rate () const
Amounts ceil_in (Amounts const &amount, Amount const &limit) const
Amounts ceil_out (Amounts const &amount, Amount const &limit) const
Quality & operator++ ()
Quality operator++ (int)
Quality & operator-- ()
Quality operator-- (int)
Private Attributes
value_type m_value
Friends
bool operator< (Quality const &lhs, Quality const &rhs) noexcept
bool operator== (Quality const &lhs, Quality const &rhs) noexcept
std::ostream & operator<< (std::ostream &os, Quality const &quality)
Detailed Description
Represents the logical ratio of output currency to input currency. Internally this is stored using a custom floating point representation, as the inverse of the ratio, so that quality will be descending in a sequence of actual values that represent qualities.
Definition at line 39 of file Quality.h.
Member Typedef Documentation
typedef std::uint64_t ripple::core::Quality::value_type
Definition at line 44 of file Quality.h.
Constructor & Destructor Documentation
ripple::core::Quality::Quality () default
ripple::core::Quality::Quality (std::uint64_t value) inline explicit
Definition at line 53 of file Quality.h.
         : m_value (value)
     {
     }
ripple::core::Quality::Quality (Amounts const & amount) inline explicit
Create a quality from the ratio of two amounts.
Definition at line 60 of file Quality.h.
         : m_value (Amount::getRate (amount.out, amount.in))
     {
     }
Member Function Documentation
Amounts ripple::core::Quality::ceil_in (Amounts const & amount, Amount const & limit) const inline
Returns the scaled amount with in capped. Math is avoided if the result is exact. The output is clamped to prevent money creation.
Definition at line 141 of file Quality.h.
References ripple::STAmount::divRound(), ripple::core::Amounts::in, ripple::STAmount::mulRound(), ripple::core::Amounts::out, and rate().
Referenced by ripple::core::Quality_test::ceil_in(), and ripple::core::Taker::fill().
     {
         if (amount.in > limit)
         {
             // VFALCO TODO make mulRound avoid math when v2==one
 #if 0
             Amounts result (limit, Amount::mulRound (
                 limit, rate(), amount.out, true));
 #else
             Amounts result (limit, Amount::divRound (
                 limit, rate(), amount.out, true));
 #endif
             // Clamp out
             if (result.out > amount.out)
                 result.out = amount.out;
             return result;
         }
         return amount;
     }
Amounts ripple::core::Quality::ceil_out (Amounts const & amount, Amount const & limit) const inline
Returns the scaled amount with out capped. Math is avoided if the result is exact. The input is clamped to prevent money creation.
Definition at line 167 of file Quality.h.
References ripple::STAmount::divRound(), ripple::core::Amounts::in, ripple::STAmount::mulRound(), ripple::core::Amounts::out, and rate().
Referenced by ripple::core::Quality_test::ceil_out(), ripple::core::Taker::fill(), and ripple::core::Quality_test::test_raw().
     {
         if (amount.out > limit)
         {
             // VFALCO TODO make divRound avoid math when v2==one
 #if 0
             Amounts result (Amount::divRound (
                 limit, rate(), amount.in, true), limit);
 #else
             Amounts result (Amount::mulRound (
                 limit, rate(), amount.in, true), limit);
 #endif
             // Clamp in
             if (result.in > amount.in)
                 result.in = amount.in;
             return result;
         }
         return amount;
     }
Quality& ripple::core::Quality::operator++ () inline
Advances to the next higher quality level.
Definition at line 68 of file Quality.h.
References m_value.
     {
         assert (m_value > 0);
         --m_value;
         return *this;
     }
Quality ripple::core::Quality::operator++ (int) inline
Definition at line 76 of file Quality.h.
References prev.
     {
         Quality prev (*this);
         --*this;
         return prev;
     }
Quality& ripple::core::Quality::operator-- () inline
Advances to the next lower quality level.
Definition at line 87 of file Quality.h.
References m_value, and ripple::max().
     {
         assert (m_value < std::numeric_limits<value_type>::max());
         ++m_value;
         return *this;
     }
Quality ripple::core::Quality::operator-- (int) inline
Definition at line 95 of file Quality.h.
References prev.
     {
         Quality prev (*this);
         ++*this;
         return prev;
     }
Amount ripple::core::Quality::rate () const inline
Returns the quality as Amount.
Definition at line 131 of file Quality.h.
References m_value, and ripple::STAmount::setRate().
Referenced by ceil_in(), and ceil_out().
     {
         return Amount::setRate (m_value);
     }
Friends And Related Function Documentation
bool operator< (Quality const & lhs, Quality const & rhs) friend
Returns true if lhs is lower quality than rhs. Lower quality means the taker receives a worse deal. Higher quality is better for the taker.
Definition at line 109 of file Quality.h.
     {
         return lhs.m_value > rhs.m_value;
     }
std::ostream& operator<< (std::ostream & os, Quality const & quality) friend
Definition at line 123 of file Quality.h.
     {
         os << quality.m_value;
         return os;
     }
bool operator== (Quality const & lhs, Quality const & rhs) friend
Definition at line 116 of file Quality.h.
     {
         return lhs.m_value == rhs.m_value;
     }
Member Data Documentation
value_type ripple::core::Quality::m_value private
Definition at line 47 of file Quality.h.
Referenced by operator++(), operator--(), and rate().
The documentation for this class was generated from the following file:
rippled/src/ripple_app/book/Quality.h