rippled: beast::unit_test::runner Class Reference
beast::unit_test::runner Class Reference
#include <runner.h>
Classes
class stream_t
Public Member Functions
virtual ~runner ()=default
runner (runner const &)=default
runner & operator= (runner const &)=default
runner ()
bool run (suite_info const &s)
template<class FwdIter >
bool run (FwdIter first, FwdIter last)
template<class FwdIter , class Pred >
bool run_if (FwdIter first, FwdIter last, Pred pred=Pred())
template<class SequenceContainer >
bool run_each (SequenceContainer const &c)
template<class SequenceContainer , class Pred >
bool run_each_if (SequenceContainer const &c, Pred pred=Pred())
Private Member Functions
virtual void on_suite_begin (suite_info const &)
virtual void on_suite_end ()
virtual void on_case_begin (std::string const &)
virtual void on_case_end ()
virtual void on_pass ()
virtual void on_fail (std::string const &)
virtual void on_log (std::string const &)
abstract_ostream & stream ()
void testcase (std::string const &name)
void pass ()
void fail (std::string const &reason)
void log (std::string const &s)
Private Attributes
stream_t m_stream
bool m_default
bool m_failed
bool m_cond
Friends
class suite
Detailed Description
Unit test runner interface. Derived classes can customize the reporting behavior. This interface is injected into the unit_test class to receive the results of the tests.
Definition at line 37 of file runner.h.
Constructor & Destructor Documentation
virtual beast::unit_test::runner::~runner () virtual default
beast::unit_test::runner::runner (runner const &) default
beast::unit_test::runner::runner () inline
Definition at line 72 of file runner.h.
         : m_stream (*this)
         , m_default (false)
         , m_failed (false)
         , m_cond (false)
     {
     }
Member Function Documentation
void beast::unit_test::runner::fail (std::string const & reason) inline private
Definition at line 251 of file runner.h.
References m_cond, m_default, m_failed, on_fail(), and testcase().
Referenced by ldb_test.LDBTestCase::assertRunFAILFull(), and beast::unit_test::suite::fail().
     {
         if (m_default)
             testcase ("");
         on_fail (reason);
         m_failed = true;
         m_cond = true;
     }
void beast::unit_test::runner::log (std::string const & s) inline private
Definition at line 261 of file runner.h.
References m_default, on_log(), and testcase().
Referenced by beast::unit_test::runner::stream_t::write().
     {
         if (m_default)
             testcase ("");
         on_log (s);
     }
virtual void beast::unit_test::runner::on_case_begin (std::string const &) inline private virtual
Called when a new case starts.
Reimplemented in beast::unit_test::reporter, and beast::unit_test::recorder.
Definition at line 185 of file runner.h.
Referenced by testcase().
     {
     }
virtual void beast::unit_test::runner::on_case_end () inline private virtual
Called when a new case ends.
Reimplemented in beast::unit_test::reporter, and beast::unit_test::recorder.
Definition at line 192 of file runner.h.
Referenced by run(), and testcase().
     {
     }
virtual void beast::unit_test::runner::on_fail (std::string const &) inline private virtual
Called for each failing condition.
Reimplemented in beast::unit_test::reporter, and beast::unit_test::recorder.
Definition at line 206 of file runner.h.
Referenced by fail().
     {
     }
virtual void beast::unit_test::runner::on_log (std::string const &) inline private virtual
Called when a test logs output.
Reimplemented in beast::unit_test::reporter, and beast::unit_test::recorder.
Definition at line 213 of file runner.h.
Referenced by log().
     {
     }
virtual void beast::unit_test::runner::on_pass () inline private virtual
Called for each passing condition.
Reimplemented in beast::unit_test::reporter, and beast::unit_test::recorder.
Definition at line 199 of file runner.h.
Referenced by pass().
     {
     }
virtual void beast::unit_test::runner::on_suite_begin (suite_info const &) inline private virtual
Called when a new suite starts.
Reimplemented in beast::unit_test::reporter, and beast::unit_test::recorder.
Definition at line 171 of file runner.h.
Referenced by run().
     {
     }
virtual void beast::unit_test::runner::on_suite_end () inline private virtual
Called when a suite ends.
Reimplemented in beast::unit_test::reporter, and beast::unit_test::recorder.
Definition at line 178 of file runner.h.
Referenced by run().
     {
     }
runner& beast::unit_test::runner::operator= (runner const &) default
void beast::unit_test::runner::pass () inline private
Definition at line 242 of file runner.h.
References m_cond, m_default, on_pass(), and testcase().
Referenced by beast::unit_test::suite::pass().
     {
         if (m_default)
             testcase ("");
         on_pass();
         m_cond = true;
     }
bool beast::unit_test::runner::run (suite_info const & s) inline
Run the specified suite.
Returns
true if any conditions failed.
Definition at line 84 of file runner.h.
References m_cond, m_default, m_failed, on_case_end(), on_suite_begin(), on_suite_end(), and beast::unit_test::suite_info::run().
Referenced by run(), run_each(), run_each_if(), and run_if().
     {
         // Enable 'default' testcase
         m_default = true;
         m_failed = false;
         on_suite_begin (s);
         s.run (*this);
         // Forgot to call pass or fail.
         assert (m_cond);
         on_case_end();
         on_suite_end();
         return m_failed;
     }
template<class FwdIter > bool beast::unit_test::runner::run (FwdIter first, FwdIter last) inline
Run a sequence of suites. The expression FwdIter::value_type must be convertible to suite_info.
Returns
true if any conditions failed.
Definition at line 106 of file runner.h.
References beast.util.Iter::first(), and run().
     {
         bool failed (false);
         for (;first != last; ++first)
             failed = run (*first) || failed;
         return failed;
     }
template<class SequenceContainer > bool beast::unit_test::runner::run_each (SequenceContainer const & c) inline
Run all suites in a container.
Returns
true if any conditions failed.
Definition at line 137 of file runner.h.
References run().
Referenced by main().
     {
         bool failed (false);
         for (auto const& s : c)
             failed = run (s) || failed;
         return failed;
     }
template<class SequenceContainer , class Pred > bool beast::unit_test::runner::run_each_if (SequenceContainer const & c, Pred pred = Pred()) inline
Conditionally run suites in a container. pred will be called as:
bool pred (suite_info const&);
Returns
true if any conditions failed.
Definition at line 154 of file runner.h.
References run().
Referenced by ripple::runUnitTests().
     {
         bool failed (false);
         for (auto const& s : c)
             if (pred (s))
                 failed = run (s) || failed;
         return failed;
     }
template<class FwdIter , class Pred > bool beast::unit_test::runner::run_if (FwdIter first, FwdIter last, Pred pred = Pred()) inline
Conditionally run a sequence of suites. pred will be called as:
bool pred (suite_info const&);
Returns
true if any conditions failed.
Definition at line 123 of file runner.h.
References beast.util.Iter::first(), and run().
     {
         bool failed (false);
         for (;first != last; ++first)
             if (pred (*first))
                 failed = run (*first) || failed;
         return failed;
     }
abstract_ostream& beast::unit_test::runner::stream () inline private
Definition at line 221 of file runner.h.
References m_stream.
Referenced by beast::unit_test::suite::log_t::operator<<(), and beast::unit_test::suite::log_t::stream().
     {
         return m_stream;
     }
void beast::unit_test::runner::testcase (std::string const & name) inline private
Definition at line 228 of file runner.h.
References m_cond, m_default, on_case_begin(), and on_case_end().
Referenced by fail(), log(), pass(), and beast::unit_test::suite::testcase().
     {
         // Name may not be empty
         assert (m_default || ! name.empty());
         // Forgot to call pass or fail
         assert (m_default || m_cond);
         if (! m_default)
             on_case_end();
         m_default = false;
         m_cond = false;
         on_case_begin (name);
     }
Friends And Related Function Documentation
friend class suite friend
Definition at line 218 of file runner.h.
Member Data Documentation
bool beast::unit_test::runner::m_cond private
Definition at line 65 of file runner.h.
Referenced by fail(), pass(), run(), and testcase().
bool beast::unit_test::runner::m_default private
Definition at line 63 of file runner.h.
Referenced by fail(), log(), pass(), run(), and testcase().
bool beast::unit_test::runner::m_failed private
Definition at line 64 of file runner.h.
Referenced by fail(), and run().
stream_t beast::unit_test::runner::m_stream private
Definition at line 62 of file runner.h.
Referenced by stream().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/unit_test/runner.h