rippled: ripple::NodeStore::MemoryBackend Class Reference
ripple::NodeStore::MemoryBackend Class Reference
Public Types
typedef std::map< uint256
const, NodeObject::Ptr > Map
Public Member Functions
MemoryBackend (size_t keyBytes, Parameters const &keyValues, Scheduler &scheduler, beast::Journal journal)
~MemoryBackend ()
std::string getName ()
Status fetch (void const *key, NodeObject::Ptr *pObject)
void store (NodeObject::ref object)
void storeBatch (Batch const &batch)
void visitAll (VisitCallback &callback)
int getWriteLoad ()
Public Member Functions inherited from ripple::NodeStore::Backend
virtual ~Backend ()=0
virtual void store (NodeObject::Ptr const &object)=0
Public Attributes
beast::Journal m_journal
size_t const m_keyBytes
Map m_map
Scheduler & m_scheduler
Detailed Description
Definition at line 23 of file MemoryFactory.cpp.
Member Typedef Documentation
typedef std::map<uint256 const, NodeObject::Ptr> ripple::NodeStore::MemoryBackend::Map
Definition at line 26 of file MemoryFactory.cpp.
Constructor & Destructor Documentation
ripple::NodeStore::MemoryBackend::MemoryBackend (size_t keyBytes, Parameters const & keyValues, Scheduler & scheduler, beast::Journal journal) inline
Definition at line 32 of file MemoryFactory.cpp.
         : m_journal (journal)
         , m_keyBytes (keyBytes)
         , m_scheduler (scheduler)
     {
     }
ripple::NodeStore::MemoryBackend::~MemoryBackend () inline
Definition at line 40 of file MemoryFactory.cpp.
     {
     }
Member Function Documentation
Status ripple::NodeStore::MemoryBackend::fetch (void const * key, NodeObject::Ptr * pObject) inline virtual
Fetch a single object. If the object is not found or an error is encountered, the result will indicate the condition.
Note
This will be called concurrently.
Parameters
key A pointer to the key data.
pObject [out] The created object if successful.
Returns
The result of the operation.
Implements ripple::NodeStore::Backend.
Definition at line 51 of file MemoryFactory.cpp.
References ripple::uint256::fromVoid(), hash, m_map, and ripple::NodeStore::ok.
     {
         uint256 const hash (uint256::fromVoid (key));
         Map::iterator iter = m_map.find (hash);
         if (iter != m_map.end ())
         {
             *pObject = iter->second;
         }
         else
         {
             pObject->reset ();
         }
         return ok;
     }
std::string ripple::NodeStore::MemoryBackend::getName () inline virtual
Get the human-readable name of this backend. This is used for diagnostic output.
Implements ripple::NodeStore::Backend.
Definition at line 44 of file MemoryFactory.cpp.
     {
         return "memory";
     }
int ripple::NodeStore::MemoryBackend::getWriteLoad () inline virtual
Estimate the number of write operations pending.
Implements ripple::NodeStore::Backend.
Definition at line 91 of file MemoryFactory.cpp.
     {
         return 0;
     }
void ripple::NodeStore::MemoryBackend::store (NodeObject::ref object) inline
Definition at line 69 of file MemoryFactory.cpp.
References m_map.
Referenced by storeBatch().
     {
         Map::iterator iter = m_map.find (object->getHash ());
         if (iter == m_map.end ())
         {
             m_map.insert (std::make_pair (object->getHash (), object));
         }
     }
void ripple::NodeStore::MemoryBackend::storeBatch (Batch const & batch) inline virtual
Store a group of objects.
Note
This function will not be called concurrently with itself or store.
Implements ripple::NodeStore::Backend.
Definition at line 79 of file MemoryFactory.cpp.
References store().
     {
         for (std::size_t i = 0; i < batch.size (); ++i)
             store (batch [i]);
     }
void ripple::NodeStore::MemoryBackend::visitAll (VisitCallback & callback) inline virtual
Visit every object in the database This is usually called during import.
Note
This routine will not be called concurrently with itself or other methods.
See Also
import, VisitCallback
Implements ripple::NodeStore::Backend.
Definition at line 85 of file MemoryFactory.cpp.
References m_map, and ripple::NodeStore::VisitCallback::visitObject().
     {
         for (Map::const_iterator iter = m_map.begin (); iter != m_map.end (); ++iter)
             callback.visitObject (iter->second);
     }
Member Data Documentation
beast::Journal ripple::NodeStore::MemoryBackend::m_journal
Definition at line 27 of file MemoryFactory.cpp.
size_t const ripple::NodeStore::MemoryBackend::m_keyBytes
Definition at line 28 of file MemoryFactory.cpp.
Map ripple::NodeStore::MemoryBackend::m_map
Definition at line 29 of file MemoryFactory.cpp.
Referenced by fetch(), store(), and visitAll().
Scheduler& ripple::NodeStore::MemoryBackend::m_scheduler
Definition at line 30 of file MemoryFactory.cpp.
The documentation for this class was generated from the following file:
rippled/src/ripple_core/nodestore/backend/MemoryFactory.cpp