rippled: Json::BatchAllocator< AllocatedType, objectPerAllocation > Class Template Reference
Json::BatchAllocator< AllocatedType, objectPerAllocation > Class Template Reference
#include <json_batchallocator.h>
Classes
struct BatchInfo
Public Types
typedef AllocatedType Type
Public Member Functions
BatchAllocator (unsigned int objectsPerPage=255)
~BatchAllocator ()
AllocatedType * allocate ()
void release (AllocatedType *object)
Private Member Functions
BatchAllocator (const BatchAllocator &)
void operator= (const BatchAllocator &)
Static Private Member Functions
static BatchInfo * allocateBatch (unsigned int objectsPerPage)
Private Attributes
BatchInfo * batches_
BatchInfo * currentBatch_
AllocatedType * freeHead_
Head of a single linked list within the allocated space of freeed object.
unsigned int objectsPerPage_
Detailed Description
template<typename AllocatedType, const unsigned int objectPerAllocation>
class Json::BatchAllocator< AllocatedType, objectPerAllocation >
Definition at line 42 of file json_batchallocator.h.
Member Typedef Documentation
template<typename AllocatedType , const unsigned int objectPerAllocation> typedef AllocatedType Json::BatchAllocator< AllocatedType, objectPerAllocation >::Type
Definition at line 45 of file json_batchallocator.h.
Constructor & Destructor Documentation
template<typename AllocatedType , const unsigned int objectPerAllocation> Json::BatchAllocator< AllocatedType, objectPerAllocation >::BatchAllocator (unsigned int objectsPerPage = 255) inline
Definition at line 47 of file json_batchallocator.h.
References Json::BatchAllocator< AllocatedType, objectPerAllocation >::allocateBatch(), Json::BatchAllocator< AllocatedType, objectPerAllocation >::batches_, and Json::BatchAllocator< AllocatedType, objectPerAllocation >::currentBatch_.
         : freeHead_ ( 0 )
         , objectsPerPage_ ( objectsPerPage )
     {
         //      printf( "Size: %d => %s\n", sizeof(AllocatedType), typeid(AllocatedType).name() );
         assert ( sizeof (AllocatedType) * objectPerAllocation >= sizeof (AllocatedType*) ); // We must be able to store a slist in the object free space.
         assert ( objectsPerPage >= 16 );
         batches_ = allocateBatch ( 0 );  // allocated a dummy page
         currentBatch_ = batches_;
     }
template<typename AllocatedType , const unsigned int objectPerAllocation> Json::BatchAllocator< AllocatedType, objectPerAllocation >::~BatchAllocator () inline
Definition at line 58 of file json_batchallocator.h.
References Json::BatchAllocator< AllocatedType, objectPerAllocation >::batches_, and Json::BatchAllocator< AllocatedType, objectPerAllocation >::BatchInfo::next_.
     {
         for ( BatchInfo* batch = batches_; batch;  )
         {
             BatchInfo* nextBatch = batch->next_;
             free ( batch );
             batch = nextBatch;
         }
     }
template<typename AllocatedType , const unsigned int objectPerAllocation> Json::BatchAllocator< AllocatedType, objectPerAllocation >::BatchAllocator (const BatchAllocator< AllocatedType, objectPerAllocation > &) private
Member Function Documentation
template<typename AllocatedType , const unsigned int objectPerAllocation> AllocatedType* Json::BatchAllocator< AllocatedType, objectPerAllocation >::allocate () inline
allocate space for an array of objectPerAllocation object.
Warning
it is the responsability of the caller to call objects constructors.
Definition at line 70 of file json_batchallocator.h.
References Json::BatchAllocator< AllocatedType, objectPerAllocation >::allocateBatch(), Json::BatchAllocator< AllocatedType, objectPerAllocation >::batches_, Json::BatchAllocator< AllocatedType, objectPerAllocation >::currentBatch_, Json::BatchAllocator< AllocatedType, objectPerAllocation >::BatchInfo::end_, Json::BatchAllocator< AllocatedType, objectPerAllocation >::freeHead_, Json::BatchAllocator< AllocatedType, objectPerAllocation >::BatchInfo::next_, Json::BatchAllocator< AllocatedType, objectPerAllocation >::objectsPerPage_, and Json::BatchAllocator< AllocatedType, objectPerAllocation >::BatchInfo::used_.
     {
         if ( freeHead_ ) // returns node from free list.
         {
             AllocatedType* object = freeHead_;
             freeHead_ = * (AllocatedType**)object;
             return object;
         }
         if ( currentBatch_->used_ == currentBatch_->end_ )
         {
             currentBatch_ = currentBatch_->next_;
             while ( currentBatch_  &&  currentBatch_->used_ == currentBatch_->end_ )
                 currentBatch_ = currentBatch_->next_;
             if ( !currentBatch_  ) // no free batch found, allocate a new one
             {
                 currentBatch_ = allocateBatch ( objectsPerPage_ );
                 currentBatch_->next_ = batches_; // insert at the head of the list
                 batches_ = currentBatch_;
             }
         }
         AllocatedType* allocated = currentBatch_->used_;
         currentBatch_->used_ += objectPerAllocation;
         return allocated;
     }
template<typename AllocatedType , const unsigned int objectPerAllocation> static BatchInfo* Json::BatchAllocator< AllocatedType, objectPerAllocation >::allocateBatch (unsigned int objectsPerPage) inline static private
Definition at line 121 of file json_batchallocator.h.
References Json::BatchAllocator< AllocatedType, objectPerAllocation >::BatchInfo::buffer_, Json::BatchAllocator< AllocatedType, objectPerAllocation >::BatchInfo::end_, Json::BatchAllocator< AllocatedType, objectPerAllocation >::BatchInfo::next_, and Json::BatchAllocator< AllocatedType, objectPerAllocation >::BatchInfo::used_.
Referenced by Json::BatchAllocator< AllocatedType, objectPerAllocation >::allocate(), and Json::BatchAllocator< AllocatedType, objectPerAllocation >::BatchAllocator().
     {
         const unsigned int mallocSize = sizeof (BatchInfo) - sizeof (AllocatedType) * objectPerAllocation
                                         + sizeof (AllocatedType) * objectPerAllocation * objectsPerPage;
         BatchInfo* batch = static_cast<BatchInfo*> ( malloc ( mallocSize ) );
         batch->next_ = 0;
         batch->used_ = batch->buffer_;
         batch->end_ = batch->buffer_ + objectsPerPage;
         return batch;
     }
template<typename AllocatedType , const unsigned int objectPerAllocation> void Json::BatchAllocator< AllocatedType, objectPerAllocation >::operator= (const BatchAllocator< AllocatedType, objectPerAllocation > &) private
template<typename AllocatedType , const unsigned int objectPerAllocation> void Json::BatchAllocator< AllocatedType, objectPerAllocation >::release (AllocatedType * object) inline
Release the object.
Warning
it is the responsability of the caller to actually destruct the object.
Definition at line 101 of file json_batchallocator.h.
References Json::BatchAllocator< AllocatedType, objectPerAllocation >::freeHead_.
     {
         assert ( object != 0 );
         * (AllocatedType**)object = freeHead_;
         freeHead_ = object;
     }
Member Data Documentation
template<typename AllocatedType , const unsigned int objectPerAllocation> BatchInfo* Json::BatchAllocator< AllocatedType, objectPerAllocation >::batches_ private
Definition at line 132 of file json_batchallocator.h.
Referenced by Json::BatchAllocator< AllocatedType, objectPerAllocation >::allocate(), Json::BatchAllocator< AllocatedType, objectPerAllocation >::BatchAllocator(), and Json::BatchAllocator< AllocatedType, objectPerAllocation >::~BatchAllocator().
template<typename AllocatedType , const unsigned int objectPerAllocation> BatchInfo* Json::BatchAllocator< AllocatedType, objectPerAllocation >::currentBatch_ private
Definition at line 133 of file json_batchallocator.h.
Referenced by Json::BatchAllocator< AllocatedType, objectPerAllocation >::allocate(), and Json::BatchAllocator< AllocatedType, objectPerAllocation >::BatchAllocator().
template<typename AllocatedType , const unsigned int objectPerAllocation> AllocatedType* Json::BatchAllocator< AllocatedType, objectPerAllocation >::freeHead_ private
Head of a single linked list within the allocated space of freeed object.
Definition at line 135 of file json_batchallocator.h.
Referenced by Json::BatchAllocator< AllocatedType, objectPerAllocation >::allocate(), and Json::BatchAllocator< AllocatedType, objectPerAllocation >::release().
template<typename AllocatedType , const unsigned int objectPerAllocation> unsigned int Json::BatchAllocator< AllocatedType, objectPerAllocation >::objectsPerPage_ private
Definition at line 136 of file json_batchallocator.h.
Referenced by Json::BatchAllocator< AllocatedType, objectPerAllocation >::allocate().
The documentation for this class was generated from the following file:
rippled/src/ripple/json/impl/json_batchallocator.h