rippled: rocksdb::SkipList< Key, Comparator > Class Template Reference
rocksdb::SkipList< Key, Comparator > Class Template Reference
#include <skiplist.h>
Classes
class Iterator
struct Node
Public Member Functions
SkipList (Comparator cmp, Arena *arena)
void Insert (const Key &key)
bool Contains (const Key &key) const
Private Types
enum { kMaxHeight = 12 }
Private Member Functions
int GetMaxHeight () const
Node * NewNode (const Key &key, int height)
int RandomHeight ()
bool Equal (const Key &a, const Key &b) const
bool KeyIsAfterNode (const Key &key, Node *n) const
Node * FindGreaterOrEqual (const Key &key, Node **prev) const
Node * FindLessThan (const Key &key) const
Node * FindLast () const
SkipList (const SkipList &)
void operator= (const SkipList &)
Private Attributes
Comparator const compare_
Arena *const arena_
Node *const head_
port::AtomicPointer max_height_
Node * prev_ [kMaxHeight]
int prev_height_
Random rnd_
Detailed Description
template<typename Key, class Comparator>
class rocksdb::SkipList< Key, Comparator >
Definition at line 42 of file skiplist.h.
Member Enumeration Documentation
template<typename Key, class Comparator> anonymous enum private
Enumerator
kMaxHeight
Definition at line 104 of file skiplist.h.
 { kMaxHeight = 12 };
Constructor & Destructor Documentation
template<typename Key , class Comparator> rocksdb::SkipList< Key, Comparator >::SkipList (Comparator cmp, Arena * arena) explicit
Definition at line 356 of file skiplist.h.
References rocksdb::SkipList< Key, Comparator >::head_, rocksdb::SkipList< Key, Comparator >::kMaxHeight, rocksdb::SkipList< Key, Comparator >::prev_, and rocksdb::SkipList< Key, Comparator >::Node::SetNext().
     : compare_(cmp),
       arena_(arena),
       head_(NewNode(0 /* any key will do */, kMaxHeight)),
       max_height_(reinterpret_cast<void*>(1)),
       prev_height_(1),
       rnd_(0xdeadbeef) {
   for (int i = 0; i < kMaxHeight; i++) {
     head_->SetNext(i, nullptr);
     prev_[i] = head_;
   }
 }
template<typename Key, class Comparator> rocksdb::SkipList< Key, Comparator >::SkipList (const SkipList< Key, Comparator > &) private
Member Function Documentation
template<typename Key, class Comparator > bool rocksdb::SkipList< Key, Comparator >::Contains (const Key & key) const
Definition at line 407 of file skiplist.h.
References rocksdb::SkipList< Key, Comparator >::Node::key.
Referenced by rocksdb::TEST().
{
   Node* x = FindGreaterOrEqual(key, nullptr);
   if (x != nullptr && Equal(key, x->key)) {
     return true;
   } else {
     return false;
   }
 }
template<typename Key, class Comparator> bool rocksdb::SkipList< Key, Comparator >::Equal (const Key & a, const Key & b) const inline private
Definition at line 130 of file skiplist.h.
 { return (compare_(a, b) == 0); }
template<typename Key, class Comparator > SkipList< Key, Comparator >::Node * rocksdb::SkipList< Key, Comparator >::FindGreaterOrEqual (const Key & key, Node ** prev) const private
Definition at line 277 of file skiplist.h.
References rocksdb::SkipList< Key, Comparator >::GetMaxHeight(), rocksdb::SkipList< Key, Comparator >::head_, rocksdb::SkipList< Key, Comparator >::Node::key, rocksdb::SkipList< Key, Comparator >::KeyIsAfterNode(), next, rocksdb::SkipList< Key, Comparator >::Node::Next(), and rocksdb::SkipList< Key, Comparator >::prev_height_.
           {
   // Use prev as an optimization hint and fallback to slow path
   if (prev && !KeyIsAfterNode(key, prev[0]->Next(0))) {
     Node* x = prev[0];
     Node* next = x->Next(0);
     if ((x == head_) || KeyIsAfterNode(key, x)) {
       // Adjust all relevant insertion points to the previous entry
       for (int i = 1; i < prev_height_; i++) {
         prev[i] = x;
       }
       return next;
     }
   }
   // Normal lookup
   Node* x = head_;
   int level = GetMaxHeight() - 1;
   while (true) {
     Node* next = x->Next(level);
     // Make sure the lists are sorted.
     // If x points to head_ or next points nullptr, it is trivially satisfied.
     assert((x == head_) || (next == nullptr) || KeyIsAfterNode(next->key, x));
     if (KeyIsAfterNode(key, next)) {
       // Keep searching in this list
       x = next;
     } else {
       if (prev != nullptr) prev[level] = x;
       if (level == 0) {
         return next;
       } else {
         // Switch to next list
         level--;
       }
     }
   }
 }
template<typename Key , class Comparator > SkipList< Key, Comparator >::Node * rocksdb::SkipList< Key, Comparator >::FindLast () const private
Definition at line 336 of file skiplist.h.
References rocksdb::SkipList< Key, Comparator >::GetMaxHeight(), rocksdb::SkipList< Key, Comparator >::head_, next, and rocksdb::SkipList< Key, Comparator >::Node::Next().
           {
   Node* x = head_;
   int level = GetMaxHeight() - 1;
   while (true) {
     Node* next = x->Next(level);
     if (next == nullptr) {
       if (level == 0) {
         return x;
       } else {
         // Switch to next list
         level--;
       }
     } else {
       x = next;
     }
   }
 }
template<typename Key, class Comparator > SkipList< Key, Comparator >::Node * rocksdb::SkipList< Key, Comparator >::FindLessThan (const Key & key) const private
Definition at line 316 of file skiplist.h.
References rocksdb::SkipList< Key, Comparator >::compare_, rocksdb::SkipList< Key, Comparator >::GetMaxHeight(), rocksdb::SkipList< Key, Comparator >::head_, rocksdb::SkipList< Key, Comparator >::Node::key, next, and rocksdb::SkipList< Key, Comparator >::Node::Next().
{
   Node* x = head_;
   int level = GetMaxHeight() - 1;
   while (true) {
     assert(x == head_ || compare_(x->key, key) < 0);
     Node* next = x->Next(level);
     if (next == nullptr || compare_(next->key, key) >= 0) {
       if (level == 0) {
         return x;
       } else {
         // Switch to next list
         level--;
       }
     } else {
       x = next;
     }
   }
 }
template<typename Key, class Comparator> int rocksdb::SkipList< Key, Comparator >::GetMaxHeight () const inline private
Definition at line 120 of file skiplist.h.
Referenced by rocksdb::SkipList< Key, Comparator >::FindGreaterOrEqual(), rocksdb::SkipList< Key, Comparator >::FindLast(), and rocksdb::SkipList< Key, Comparator >::FindLessThan().
{
     return static_cast<int>(
         reinterpret_cast<intptr_t>(max_height_.NoBarrier_Load()));
   }
template<typename Key, class Comparator > void rocksdb::SkipList< Key, Comparator >::Insert (const Key & key)
Definition at line 370 of file skiplist.h.
References rocksdb::SkipList< Key, Comparator >::Node::key, and rocksdb::SkipList< Key, Comparator >::Node::NoBarrier_SetNext().
Referenced by rocksdb::TEST().
{
   // TODO(opt): We can use a barrier-free variant of FindGreaterOrEqual()
   // here since Insert() is externally synchronized.
   Node* x = FindGreaterOrEqual(key, prev_);
   // Our data structure does not allow duplicate insertion
   assert(x == nullptr || !Equal(key, x->key));
   int height = RandomHeight();
   if (height > GetMaxHeight()) {
     for (int i = GetMaxHeight(); i < height; i++) {
       prev_[i] = head_;
     }
     //fprintf(stderr, "Change height from %d to %d\n", max_height_, height);
     // It is ok to mutate max_height_ without any synchronization
     // with concurrent readers.  A concurrent reader that observes
     // the new value of max_height_ will see either the old value of
     // new level pointers from head_ (nullptr), or a new value set in
     // the loop below.  In the former case the reader will
     // immediately drop to the next level since nullptr sorts after all
     // keys.  In the latter case the reader will use the new node.
     max_height_.NoBarrier_Store(reinterpret_cast<void*>(height));
   }
   x = NewNode(key, height);
   for (int i = 0; i < height; i++) {
     // NoBarrier_SetNext() suffices since we will add a barrier when
     // we publish a pointer to "x" in prev[i].
     x->NoBarrier_SetNext(i, prev_[i]->NoBarrier_Next(i));
     prev_[i]->SetNext(i, x);
   }
   prev_[0] = x;
   prev_height_ = height;
 }
template<typename Key, class Comparator > bool rocksdb::SkipList< Key, Comparator >::KeyIsAfterNode (const Key & key, Node * n) const private
Definition at line 271 of file skiplist.h.
References rocksdb::SkipList< Key, Comparator >::compare_, and rocksdb::SkipList< Key, Comparator >::Node::key.
Referenced by rocksdb::SkipList< Key, Comparator >::FindGreaterOrEqual().
{
   // nullptr n is considered infinite
   return (n != nullptr) && (compare_(n->key, key) < 0);
 }
template<typename Key, class Comparator > SkipList< Key, Comparator >::Node * rocksdb::SkipList< Key, Comparator >::NewNode (const Key & key, int height) private
Definition at line 194 of file skiplist.h.
References rocksdb::Arena::AllocateAligned(), arena_, and mem.
{
   char* mem = arena_->AllocateAligned(
       sizeof(Node) + sizeof(port::AtomicPointer) * (height - 1));
   return new (mem) Node(key);
 }
template<typename Key, class Comparator> void rocksdb::SkipList< Key, Comparator >::operator= (const SkipList< Key, Comparator > &) private
template<typename Key , class Comparator > int rocksdb::SkipList< Key, Comparator >::RandomHeight () private
Definition at line 258 of file skiplist.h.
References rocksdb::SkipList< Key, Comparator >::kMaxHeight, rocksdb::Random::Next(), and rocksdb::SkipList< Key, Comparator >::rnd_.
{
   // Increase height with probability 1 in kBranching
   static const unsigned int kBranching = 4;
   int height = 1;
   while (height < kMaxHeight && ((rnd_.Next() % kBranching) == 0)) {
     height++;
   }
   assert(height > 0);
   assert(height <= kMaxHeight);
   return height;
 }
Member Data Documentation
template<typename Key, class Comparator> Arena* const rocksdb::SkipList< Key, Comparator >::arena_ private
Definition at line 108 of file skiplist.h.
template<typename Key, class Comparator> Comparator const rocksdb::SkipList< Key, Comparator >::compare_ private
Definition at line 107 of file skiplist.h.
Referenced by rocksdb::SkipList< Key, rocksdb::TestComparator >::Equal(), rocksdb::SkipList< Key, Comparator >::FindLessThan(), and rocksdb::SkipList< Key, Comparator >::KeyIsAfterNode().
template<typename Key, class Comparator> Node* const rocksdb::SkipList< Key, Comparator >::head_ private
Definition at line 110 of file skiplist.h.
Referenced by rocksdb::SkipList< Key, Comparator >::FindGreaterOrEqual(), rocksdb::SkipList< Key, Comparator >::FindLast(), rocksdb::SkipList< Key, Comparator >::FindLessThan(), and rocksdb::SkipList< Key, Comparator >::SkipList().
template<typename Key, class Comparator> port::AtomicPointer rocksdb::SkipList< Key, Comparator >::max_height_ private
Definition at line 114 of file skiplist.h.
Referenced by rocksdb::SkipList< Key, rocksdb::TestComparator >::GetMaxHeight().
template<typename Key, class Comparator> Node* rocksdb::SkipList< Key, Comparator >::prev_[kMaxHeight] private
Definition at line 117 of file skiplist.h.
Referenced by rocksdb::SkipList< Key, Comparator >::SkipList().
template<typename Key, class Comparator> int rocksdb::SkipList< Key, Comparator >::prev_height_ private
Definition at line 118 of file skiplist.h.
Referenced by rocksdb::SkipList< Key, Comparator >::FindGreaterOrEqual().
template<typename Key, class Comparator> Random rocksdb::SkipList< Key, Comparator >::rnd_ private
Definition at line 126 of file skiplist.h.
Referenced by rocksdb::SkipList< Key, Comparator >::RandomHeight().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/db/skiplist.h