rippled: rocksdb::InternalDumpCommand Class Reference
rocksdb::InternalDumpCommand Class Reference
#include <ldb_cmd.h>
Public Member Functions
InternalDumpCommand (const vector< string > &params, const map< string, string > &options, const vector< string > &flags)
virtual void DoCommand ()
Public Member Functions inherited from rocksdb::LDBCommand
bool ValidateCmdLineOptions ()
virtual Options PrepareOptionsForOpenDB ()
virtual void SetOptions (Options options)
virtual bool NoDBOpen ()
virtual ~LDBCommand ()
void Run ()
LDBCommandExecuteResult GetExecuteState ()
void ClearPreviousRunState ()
Static Public Member Functions
static string Name ()
static void Help (string &ret)
Static Public Member Functions inherited from rocksdb::LDBCommand
static LDBCommand * InitFromCmdLineArgs (const vector< string > &args, const Options &options=Options())
static LDBCommand * InitFromCmdLineArgs (int argc, char **argv, const Options &options=Options())
static string HexToString (const string &str)
static string StringToHex (const string &str)
Private Attributes
bool has_from_
string from_
bool has_to_
string to_
int max_keys_
string delim_
bool count_only_
bool count_delim_
bool print_stats_
bool is_input_key_hex_
Static Private Attributes
static const string ARG_DELIM
static const string ARG_COUNT_ONLY = "count_only"
static const string ARG_COUNT_DELIM = "count_delim"
static const string ARG_STATS = "stats"
static const string ARG_INPUT_KEY_HEX = "input_key_hex"
Additional Inherited Members
Static Public Attributes inherited from rocksdb::LDBCommand
static const string ARG_DB = "db"
static const string ARG_HEX = "hex"
static const string ARG_KEY_HEX = "key_hex"
static const string ARG_VALUE_HEX = "value_hex"
static const string ARG_TTL = "ttl"
static const string ARG_TTL_START = "start_time"
static const string ARG_TTL_END = "end_time"
static const string ARG_TIMESTAMP = "timestamp"
static const string ARG_FROM = "from"
static const string ARG_TO = "to"
static const string ARG_MAX_KEYS = "max_keys"
static const string ARG_BLOOM_BITS = "bloom_bits"
static const string ARG_COMPRESSION_TYPE = "compression_type"
static const string ARG_BLOCK_SIZE = "block_size"
static const string ARG_AUTO_COMPACTION = "auto_compaction"
static const string ARG_WRITE_BUFFER_SIZE = "write_buffer_size"
static const string ARG_FILE_SIZE = "file_size"
static const string ARG_CREATE_IF_MISSING = "create_if_missing"
static const char * DELIM = " ==> "
Protected Member Functions inherited from rocksdb::LDBCommand
bool ParseKeyValue (const string &line, string *key, string *value, bool is_key_hex, bool is_value_hex)
LDBCommand (const map< string, string > &options, const vector< string > &flags, bool is_read_only, const vector< string > &valid_cmd_line_options)
void OpenDB ()
void CloseDB ()
vector< string > BuildCmdLineOptions (vector< string > options)
bool ParseIntOption (const map< string, string > &options, const string &option, int &value, LDBCommandExecuteResult &exec_state)
bool ParseStringOption (const map< string, string > &options, const string &option, string *value)
Static Protected Member Functions inherited from rocksdb::LDBCommand
static string PrintKeyValue (const string &key, const string &value, bool is_key_hex, bool is_value_hex)
static string PrintKeyValue (const string &key, const string &value, bool is_hex)
static bool IsFlagPresent (const vector< string > &flags, const string &flag)
static string HelpRangeCmdArgs ()
Protected Attributes inherited from rocksdb::LDBCommand
LDBCommandExecuteResult exec_state_
string db_path_
DB * db_
StackableDB * sdb_
bool is_read_only_
bool is_key_hex_
bool is_value_hex_
bool is_db_ttl_
bool timestamp_
const map< string, string > option_map_
const vector< string > flags_
const vector< string > valid_cmd_line_options_
Options options_
Detailed Description
Definition at line 409 of file ldb_cmd.h.
Constructor & Destructor Documentation
rocksdb::InternalDumpCommand::InternalDumpCommand (const vector< string > & params, const map< string, string > & options, const vector< string > & flags)
Definition at line 592 of file ldb_cmd.cc.
References ARG_COUNT_DELIM, ARG_COUNT_ONLY, rocksdb::LDBCommand::ARG_FROM, rocksdb::LDBCommand::ARG_HEX, ARG_INPUT_KEY_HEX, rocksdb::LDBCommand::ARG_KEY_HEX, rocksdb::LDBCommand::ARG_MAX_KEYS, ARG_STATS, rocksdb::LDBCommand::ARG_TO, and rocksdb::LDBCommand::ARG_VALUE_HEX.
                                                                       :
     LDBCommand(options, flags, true,
                BuildCmdLineOptions({ ARG_HEX, ARG_KEY_HEX, ARG_VALUE_HEX,
                                      ARG_FROM, ARG_TO, ARG_MAX_KEYS,
                                      ARG_COUNT_ONLY, ARG_COUNT_DELIM, ARG_STATS,
                                      ARG_INPUT_KEY_HEX})),
Member Function Documentation
void rocksdb::InternalDumpCommand::DoCommand () virtual
Implements rocksdb::LDBCommand.
Definition at line 649 of file ldb_cmd.cc.
References rocksdb::Options::comparator, rocksdb::Comparator::Compare(), count_delim_, count_only_, rocksdb::LDBCommand::db_, rocksdb::ParsedInternalKey::DebugString(), delim_, rocksdb::InternalKey::Encode(), rocksdb::LDBCommand::exec_state_, rocksdb::LDBCommandExecuteResult::FAILED(), from_, rocksdb::DB::GetProperty(), has_from_, has_to_, rocksdb::LDBCommand::is_key_hex_, rocksdb::LDBCommand::is_value_hex_, rocksdb::kMaxSequenceNumber, rocksdb::kValueTypeForSeek, max_keys_, rocksdb::LDBCommand::options_, rocksdb::ParseInternalKey(), print_stats_, stats, rocksdb::DBImpl::TEST_NewInternalIterator(), to_, rocksdb::ParsedInternalKey::user_key, and value.
{
   if (!db_) {
     return;
   }
   if (print_stats_) {
     string stats;
     if (db_->GetProperty("rocksdb.stats", &stats)) {
       fprintf(stdout, "%s\n", stats.c_str());
     }
   }
   // Cast as DBImpl to get internal iterator
   DBImpl* idb = dynamic_cast<DBImpl*>(db_);
   if (!idb) {
     exec_state_ = LDBCommandExecuteResult::FAILED("DB is not DBImpl");
     return;
   }
   string rtype1,rtype2,row,val;
   rtype2 = "";
   uint64_t c=0;
   uint64_t s1=0,s2=0;
   // Setup internal key iterator
   auto iter = unique_ptr<Iterator>(idb->TEST_NewInternalIterator());
   Status st = iter->status();
   if (!st.ok()) {
     exec_state_ = LDBCommandExecuteResult::FAILED("Iterator error:"
                                                   + st.ToString());
   }
   if (has_from_) {
     InternalKey ikey(from_, kMaxSequenceNumber, kValueTypeForSeek);
     iter->Seek(ikey.Encode());
   } else {
     iter->SeekToFirst();
   }
   long long count = 0;
   for (; iter->Valid(); iter->Next()) {
     ParsedInternalKey ikey;
     if (!ParseInternalKey(iter->key(), &ikey)) {
       fprintf(stderr, "Internal Key [%s] parse error!\n",
               iter->key().ToString(true /* in hex*/).data());
       // TODO: add error counter
       continue;
     }
     // If end marker was specified, we stop before it
     if (has_to_ && options_.comparator->Compare(ikey.user_key, to_) >= 0) {
       break;
     }
     ++count;
     int k;
     if (count_delim_) {
       rtype1 = "";
       s1=0;
       row = iter->key().ToString();
       val = iter->value().ToString();
       for(k=0;row[k]!='\x01' && row[k]!='\0';k++)
         s1++;
       for(k=0;val[k]!='\x01' && val[k]!='\0';k++)
         s1++;
       for(int j=0;row[j]!=delim_[0] && row[j]!='\0' && row[j]!='\x01';j++)
         rtype1+=row[j];
       if(rtype2.compare("") && rtype2.compare(rtype1)!=0) {
         fprintf(stdout,"%s => count:%lld\tsize:%lld\n",rtype2.c_str(),
             (long long)c,(long long)s2);
         c=1;
         s2=s1;
         rtype2 = rtype1;
       } else {
         c++;
         s2+=s1;
         rtype2=rtype1;
     }
   }
     if (!count_only_ && !count_delim_) {
       string key = ikey.DebugString(is_key_hex_);
       string value = iter->value().ToString(is_value_hex_);
       std::cout << key << " => " << value << "\n";
     }
     // Terminate if maximum number of keys have been dumped
     if (max_keys_ > 0 && count >= max_keys_) break;
   }
   if(count_delim_) {
     fprintf(stdout,"%s => count:%lld\tsize:%lld\n", rtype2.c_str(),
         (long long)c,(long long)s2);
   } else
   fprintf(stdout, "Internal keys in range: %lld\n", (long long) count);
 }
void rocksdb::InternalDumpCommand::Help (string & ret) static
Definition at line 637 of file ldb_cmd.cc.
References ARG_COUNT_DELIM, ARG_COUNT_ONLY, ARG_INPUT_KEY_HEX, rocksdb::LDBCommand::ARG_MAX_KEYS, ARG_STATS, rocksdb::LDBCommand::HelpRangeCmdArgs(), and Name().
Referenced by rocksdb::LDBCommandRunner::PrintHelp().
{
   ret.append("  ");
   ret.append(InternalDumpCommand::Name());
   ret.append(HelpRangeCmdArgs());
   ret.append(" [--" + ARG_INPUT_KEY_HEX + "]");
   ret.append(" [--" + ARG_MAX_KEYS + "=<N>]");
   ret.append(" [--" + ARG_COUNT_ONLY + "]");
   ret.append(" [--" + ARG_COUNT_DELIM + "=<char>]");
   ret.append(" [--" + ARG_STATS + "]");
   ret.append("\n");
 }
static string rocksdb::InternalDumpCommand::Name () inline static
Definition at line 411 of file ldb_cmd.h.
Referenced by Help(), and rocksdb::LDBCommand::SelectCommand().
 { return "idump"; }
Member Data Documentation
const string rocksdb::InternalDumpCommand::ARG_COUNT_DELIM = "count_delim" static private
Definition at line 435 of file ldb_cmd.h.
Referenced by Help(), and InternalDumpCommand().
const string rocksdb::InternalDumpCommand::ARG_COUNT_ONLY = "count_only" static private
Definition at line 434 of file ldb_cmd.h.
Referenced by Help(), and InternalDumpCommand().
const string rocksdb::InternalDumpCommand::ARG_DELIM static private
Definition at line 433 of file ldb_cmd.h.
const string rocksdb::InternalDumpCommand::ARG_INPUT_KEY_HEX = "input_key_hex" static private
Definition at line 437 of file ldb_cmd.h.
Referenced by Help(), and InternalDumpCommand().
const string rocksdb::InternalDumpCommand::ARG_STATS = "stats" static private
Definition at line 436 of file ldb_cmd.h.
Referenced by Help(), and InternalDumpCommand().
bool rocksdb::InternalDumpCommand::count_delim_ private
Definition at line 429 of file ldb_cmd.h.
Referenced by DoCommand().
bool rocksdb::InternalDumpCommand::count_only_ private
Definition at line 428 of file ldb_cmd.h.
Referenced by DoCommand().
string rocksdb::InternalDumpCommand::delim_ private
Definition at line 427 of file ldb_cmd.h.
Referenced by DoCommand().
string rocksdb::InternalDumpCommand::from_ private
Definition at line 423 of file ldb_cmd.h.
Referenced by DoCommand().
bool rocksdb::InternalDumpCommand::has_from_ private
Definition at line 422 of file ldb_cmd.h.
Referenced by DoCommand().
bool rocksdb::InternalDumpCommand::has_to_ private
Definition at line 424 of file ldb_cmd.h.
Referenced by DoCommand().
bool rocksdb::InternalDumpCommand::is_input_key_hex_ private
Definition at line 431 of file ldb_cmd.h.
int rocksdb::InternalDumpCommand::max_keys_ private
Definition at line 426 of file ldb_cmd.h.
Referenced by DoCommand().
bool rocksdb::InternalDumpCommand::print_stats_ private
Definition at line 430 of file ldb_cmd.h.
Referenced by DoCommand().
string rocksdb::InternalDumpCommand::to_ private
Definition at line 425 of file ldb_cmd.h.
Referenced by DoCommand().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/util/ldb_cmd.h
rippled/src/ripple/rocksdb/rocksdb/util/ldb_cmd.cc