rippled: beast::FileSearchPath Class Reference
beast::FileSearchPath Class Reference
#include <FileSearchPath.h>
Public Member Functions
FileSearchPath ()
FileSearchPath (const String &path)
FileSearchPath (const FileSearchPath &other)
~FileSearchPath ()
FileSearchPath & operator= (const String &path)
int getNumPaths () const
File operator[] (int index) const
String toString () const
void add (const File &directoryToAdd, int insertIndex=-1)
void addIfNotAlreadyThere (const File &directoryToAdd)
void remove (int indexToRemove)
void addPath (const FileSearchPath &other)
void removeRedundantPaths ()
void removeNonExistentPaths ()
int findChildFiles (Array< File > &results, int whatToLookFor, bool searchRecursively, const String &wildCardPattern="*") const
bool isFileInPath (const File &fileToCheck, bool checkRecursively) const
Private Member Functions
void init (const String &path)
Private Attributes
StringArray directories
Detailed Description
Encapsulates a set of folders that make up a search path.
See Also
File
Definition at line 36 of file FileSearchPath.h.
Constructor & Destructor Documentation
beast::FileSearchPath::FileSearchPath ()
Creates an empty search path.
Definition at line 27 of file FileSearchPath.cpp.
 {
 }
beast::FileSearchPath::FileSearchPath (const String & path)
Creates a search path from a string of pathnames.
The path can be semicolon- or comma-separated, e.g. "/foo/bar;/foo/moose;/fish/moose"
The separate folders are tokenised and added to the search path.
Definition at line 31 of file FileSearchPath.cpp.
References init().
 {
     init (path);
 }
beast::FileSearchPath::FileSearchPath (const FileSearchPath & other)
Creates a copy of another search path.
Definition at line 36 of file FileSearchPath.cpp.
   : directories (other.directories)
 {
 }
beast::FileSearchPath::~FileSearchPath ()
Destructor.
Definition at line 41 of file FileSearchPath.cpp.
 {
 }
Member Function Documentation
void beast::FileSearchPath::add (const File & directoryToAdd, int insertIndex = -1)
Adds a new directory to the search path.
The new directory is added to the end of the list if the insertIndex parameter is less than zero, otherwise it is inserted at the given index.
Definition at line 82 of file FileSearchPath.cpp.
References directories, beast::File::getFullPathName(), and beast::StringArray::insert().
Referenced by addIfNotAlreadyThere().
 {
     directories.insert (insertIndex, dir.getFullPathName());
 }
void beast::FileSearchPath::addIfNotAlreadyThere (const File & directoryToAdd)
Adds a new directory to the search path if it's not already in there.
Definition at line 87 of file FileSearchPath.cpp.
References add(), directories, and beast::StringArray::size().
Referenced by addPath().
 {
     for (int i = 0; i < directories.size(); ++i)
         if (File (directories[i]) == dir)
             return;
     add (dir);
 }
void beast::FileSearchPath::addPath (const FileSearchPath & other)
Merges another search path into this one.
This will remove any duplicate directories.
Definition at line 101 of file FileSearchPath.cpp.
References addIfNotAlreadyThere(), and getNumPaths().
 {
     for (int i = 0; i < other.getNumPaths(); ++i)
         addIfNotAlreadyThere (other[i]);
 }
int beast::FileSearchPath::findChildFiles (Array< File > & results, int whatToLookFor, bool searchRecursively, const String & wildCardPattern = "*") const
Searches the path for a wildcard.
This will search all the directories in the search path in order, adding any matching files to the results array.
Parameters
results an array to append the results to
whatToLookFor a value from the File::TypesOfFileToFind enum, specifying whether to return files, directories, or both.
searchRecursively whether to recursively search the subdirectories too
wildCardPattern a pattern to match against the filenames
Returns
the number of files added to the array
See Also
File::findChildFiles
Definition at line 133 of file FileSearchPath.cpp.
References directories, and beast::StringArray::size().
 {
     int total = 0;
     for (int i = 0; i < directories.size(); ++i)
         total += operator[] (i).findChildFiles (results,
                                                 whatToLookFor,
                                                 searchRecursively,
                                                 wildCardPattern);
     return total;
 }
int beast::FileSearchPath::getNumPaths () const
Returns the number of folders in this search path.
See Also
operator[]
Definition at line 62 of file FileSearchPath.cpp.
References directories, and beast::StringArray::size().
Referenced by addPath().
 {
     return directories.size();
 }
void beast::FileSearchPath::init (const String & path) private
Definition at line 51 of file FileSearchPath.cpp.
References beast::StringArray::addTokens(), beast::StringArray::clear(), directories, beast::StringArray::removeEmptyStrings(), beast::StringArray::set(), beast::StringArray::size(), and beast::StringArray::trim().
Referenced by FileSearchPath(), and operator=().
 {
     directories.clear();
     directories.addTokens (path, ";", "\"");
     directories.trim();
     directories.removeEmptyStrings();
     for (int i = directories.size(); --i >= 0;)
         directories.set (i, directories[i].unquoted());
 }
bool beast::FileSearchPath::isFileInPath (const File & fileToCheck, bool checkRecursively) const
Finds out whether a file is inside one of the path's directories.
This will return true if the specified file is a child of one of the directories specified by this path. Note that this doesn't actually do any searching or check that the files exist - it just looks at the pathnames to work out whether the file would be inside a directory.
Parameters
fileToCheck the file to look for
checkRecursively if true, then this will return true if the file is inside a subfolder of one of the path's directories (at any depth). If false it will only return true if the file is actually a direct child of one of the directories.
See Also
File::isAChildOf
Definition at line 149 of file FileSearchPath.cpp.
References directories, beast::File::getParentDirectory(), beast::File::isAChildOf(), and beast::StringArray::size().
 {
     for (int i = directories.size(); --i >= 0;)
     {
         const File d (directories[i]);
         if (checkRecursively)
         {
             if (fileToCheck.isAChildOf (d))
                 return true;
         }
         else
         {
             if (fileToCheck.getParentDirectory() == d)
                 return true;
         }
     }
     return false;
 }
FileSearchPath & beast::FileSearchPath::operator= (const String & path)
Uses a string containing a list of pathnames to re-initialise this list.
This search path is cleared and the semicolon- or comma-separated folders in this string are added instead. e.g. "/foo/bar;/foo/moose;/fish/moose"
Definition at line 45 of file FileSearchPath.cpp.
References init().
 {
     init (path);
     return *this;
 }
File beast::FileSearchPath::operator[] (int index) const
Returns one of the folders in this search path.
The file returned isn't guaranteed to actually be a valid directory.
See Also
getNumPaths
Definition at line 67 of file FileSearchPath.cpp.
References directories.
 {
     return File (directories [index]);
 }
void beast::FileSearchPath::remove (int indexToRemove)
Removes a directory from the search path.
Definition at line 96 of file FileSearchPath.cpp.
References directories, and beast::StringArray::remove().
 {
     directories.remove (index);
 }
void beast::FileSearchPath::removeNonExistentPaths ()
Removes any directories that don't actually exist.
Definition at line 126 of file FileSearchPath.cpp.
References directories, beast::File::isDirectory(), beast::StringArray::remove(), and beast::StringArray::size().
 {
     for (int i = directories.size(); --i >= 0;)
         if (! File (directories[i]).isDirectory())
             directories.remove (i);
 }
void beast::FileSearchPath::removeRedundantPaths ()
Removes any directories that are actually subdirectories of one of the other directories in the search path.
If the search is intended to be recursive, there's no point having nested folders in the search path, because they'll just get searched twice and you'll get duplicate results.
e.g. if the path is "c:\abc\de;c:\abc", this method will simplify it to "c:\abc"
Definition at line 107 of file FileSearchPath.cpp.
References directories, beast::File::isAChildOf(), beast::StringArray::remove(), and beast::StringArray::size().
 {
     for (int i = directories.size(); --i >= 0;)
     {
         const File d1 (directories[i]);
         for (int j = directories.size(); --j >= 0;)
         {
             const File d2 (directories[j]);
             if ((i != j) && (d1.isAChildOf (d2) || d1 == d2))
             {
                 directories.remove (i);
                 break;
             }
         }
     }
 }
String beast::FileSearchPath::toString () const
Returns the search path as a semicolon-separated list of directories.
Definition at line 72 of file FileSearchPath.cpp.
References directories, beast::StringArray::joinIntoString(), beast::StringArray::set(), and beast::StringArray::size().
 {
     StringArray directories2 (directories);
     for (int i = directories2.size(); --i >= 0;)
         if (directories2[i].containsChar (';'))
             directories2.set (i, directories2[i].quoted());
     return directories2.joinIntoString (";");
 }
Member Data Documentation
StringArray beast::FileSearchPath::directories private
Definition at line 156 of file FileSearchPath.h.
Referenced by add(), addIfNotAlreadyThere(), findChildFiles(), getNumPaths(), init(), isFileInPath(), operator[](), remove(), removeNonExistentPaths(), removeRedundantPaths(), and toString().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_core/files/FileSearchPath.h
rippled/src/beast/modules/beast_core/files/FileSearchPath.cpp