rippled: ripple::Validators::ManagerImp Class Reference
ripple::Validators::ManagerImp Class Reference
Public Types
typedef
beast::ScopedWrapperContext
< beast::RecursiveMutex,
beast::RecursiveMutex::ScopedLockType > Context
Public Types inherited from beast::Thread
typedef void * ThreadID
Public Member Functions
ManagerImp (Stoppable &parent, beast::File const &pathToDbFileOrDirectory, beast::Journal journal)
~ManagerImp ()
void addStrings (beast::String name, std::vector< std::string > const &strings)
void addStrings (beast::String name, beast::StringArray const &stringArray)
void addFile (beast::File const &file)
void addStaticSource (Validators::Source *source)
void addURL (beast::URL const &url)
void addSource (Validators::Source *source)
void receiveValidation (ReceivedValidation const &rv)
void ledgerClosed (RippleLedgerHash const &ledgerHash)
void onPrepare ()
void onStart ()
void onStop ()
void onWrite (beast::PropertyStream::Map &map)
void init ()
void onDeadlineTimer (beast::DeadlineTimer &timer)
void setCheckSources ()
void checkSources ()
void run ()
Public Member Functions inherited from ripple::Validators::Manager
virtual ~Manager ()
Public Member Functions inherited from beast::PropertyStream::Source
Source (std::string const &name)
~Source ()
std::string const & name () const
void add (Source &source)
template<class Derived >
Derived * add (Derived *child)
void remove (Source &child)
void removeAll ()
void write_one (PropertyStream &stream)
void write (PropertyStream &stream)
void write (PropertyStream &stream, std::string const &path)
std::pair< Source *, bool > find (std::string path)
Source * find_one_deep (std::string const &name)
PropertyStream::Source * find_path (std::string path)
PropertyStream::Source * find_one (std::string const &name)
Public Member Functions inherited from beast::Stoppable
Stoppable (char const *name, Stoppable &parent)
virtual ~Stoppable ()
bool isStopping () const
bool isStopped () const
bool areChildrenStopped () const
void stopped ()
virtual void onChildrenStopped ()
Public Member Functions inherited from beast::Thread
Thread (const String &threadName)
virtual ~Thread ()
void startThread ()
void startThread (int priority)
bool stopThread (int timeOutMilliseconds=-1)
void stopThreadAsync ()
bool isThreadRunning () const
void signalThreadShouldExit ()
bool threadShouldExit () const
bool waitForThreadToExit (int timeOutMilliseconds=-1) const
bool setPriority (int priority)
void setAffinityMask (std::uint32_t affinityMask)
bool wait (int timeOutMilliseconds=-1) const
void notify () const
ThreadID getThreadId () const noexcept
const String & getThreadName () const
Public Attributes
beast::Journal m_journal
beast::File m_databaseFile
StoreSqdb m_store
Logic m_logic
beast::DeadlineTimer m_checkTimer
beast::ServiceQueue m_queue
Context m_context
bool m_checkSources
Additional Inherited Members
Static Public Member Functions inherited from ripple::Validators::Manager
static Manager * New (beast::Stoppable &stoppableParent, beast::File const &pathToDbFileOrDirectory, beast::Journal journal)
Static Public Member Functions inherited from beast::Thread
static bool setCurrentThreadPriority (int priority)
static void setCurrentThreadAffinityMask (std::uint32_t affinityMask)
static void sleep (int milliseconds)
static void yield ()
static ThreadID getCurrentThreadId ()
static Thread * getCurrentThread ()
static void setCurrentThreadName (const String &newThreadName)
Protected Member Functions inherited from ripple::Validators::Manager
Manager ()
Protected Member Functions inherited from beast::Stoppable
Stoppable (char const *name, RootStoppable &root)
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Protected Attributes inherited from beast::Stoppable
char const * m_name
RootStoppable & m_root
Child m_child
Atomic< int > m_started
bool volatile m_stopped
bool volatile m_childrenStopped
Children m_children
WaitableEvent m_stoppedEvent
Detailed Description
Definition at line 128 of file Manager.cpp.
Member Typedef Documentation
typedef beast::ScopedWrapperContext< beast::RecursiveMutex, beast::RecursiveMutex::ScopedLockType> ripple::Validators::ManagerImp::Context
Definition at line 144 of file Manager.cpp.
Constructor & Destructor Documentation
ripple::Validators::ManagerImp::ManagerImp (Stoppable & parent, beast::File const & pathToDbFileOrDirectory, beast::Journal journal) inline
Definition at line 153 of file Manager.cpp.
References beast::Journal::debug, beast::File::getChildFile(), beast::Journal::info, beast::File::isDirectory(), m_databaseFile, m_journal, and beast::Journal::trace.
         : Stoppable ("Validators::Manager", parent)
         , Thread ("Validators")
         , m_journal (journal)
         , m_databaseFile (pathToDbFileOrDirectory)
         , m_store (m_journal)
         , m_logic (m_store, m_journal)
         , m_checkTimer (this)
         , m_checkSources (false)
     {
         m_journal.trace <<
             "Validators constructed";
         m_journal.debug <<
             "Validators constructed (debug)";
         m_journal.info <<
             "Validators constructed (info)";
         if (m_databaseFile.isDirectory ())
             m_databaseFile = m_databaseFile.getChildFile("validators.sqlite");
     }
ripple::Validators::ManagerImp::~ManagerImp () inline
Definition at line 179 of file Manager.cpp.
References beast::Thread::stopThread().
     {
         stopThread ();
     }
Member Function Documentation
void ripple::Validators::ManagerImp::addFile (beast::File const & file) inline virtual
Implements ripple::Validators::Manager.
Definition at line 211 of file Manager.cpp.
References addStaticSource(), and ripple::Validators::SourceFile::New().
     {
         addStaticSource (SourceFile::New (file));
     }
void ripple::Validators::ManagerImp::addSource (Validators::Source * source) inline virtual
Add a live source of validators. The caller loses ownership of the object. The fetch is performed asynchronously, this call doesn't block. Thread safety: Can be called from any thread.
Implements ripple::Validators::Manager.
Definition at line 227 of file Manager.cpp.
References ripple::Validators::Logic::add(), beast::ServiceQueueType< Allocator >::dispatch(), m_context, m_logic, m_queue, and beast::ScopedWrapperContext< Context, ScopedType >::wrap().
Referenced by addURL().
     {
         m_queue.dispatch (m_context.wrap (std::bind (
             &Logic::add, &m_logic, source)));
     }
void ripple::Validators::ManagerImp::addStaticSource (Validators::Source * source) inline virtual
Implements ripple::Validators::Manager.
Definition at line 216 of file Manager.cpp.
References ripple::Validators::Logic::addStatic(), beast::ServiceQueueType< Allocator >::dispatch(), m_context, m_logic, m_queue, and beast::ScopedWrapperContext< Context, ScopedType >::wrap().
Referenced by addFile(), and addStrings().
     {
         m_queue.dispatch (m_context.wrap (std::bind (
             &Logic::addStatic, &m_logic, source)));
     }
void ripple::Validators::ManagerImp::addStrings (beast::String name, std::vector< std::string > const & strings) inline virtual
Add a static source of validators. The validators added using these methods will always be chosen when constructing the UNL regardless of statistics. The fetch operation is performed asynchronously, so this call returns immediately. A failed fetch (depending on the source) is not retried. The caller loses ownership of any dynamic objects. Thread safety: Can be called from any thread.
Implements ripple::Validators::Manager.
Definition at line 190 of file Manager.cpp.
References beast::StringArray::add(), and beast::StringArray::ensureStorageAllocated().
     {
         beast::StringArray stringArray;
         stringArray.ensureStorageAllocated (strings.size());
         for (std::size_t i = 0; i < strings.size(); ++i)
             stringArray.add (strings [i]);
         addStrings (name, stringArray);
     }
void ripple::Validators::ManagerImp::addStrings (beast::String name, beast::StringArray const & stringArray) inline virtual
Implements ripple::Validators::Manager.
Definition at line 199 of file Manager.cpp.
References addStaticSource(), beast::Journal::debug, m_journal, ripple::Validators::SourceStrings::New(), and beast::StringArray::size().
     {
         if (stringArray.size() > 0)
         {
             addStaticSource (SourceStrings::New (name, stringArray));
         }
         else
         {
             m_journal.debug << "Static source '" << name << "' is empty.";
         }
     }
void ripple::Validators::ManagerImp::addURL (beast::URL const & url) inline virtual
Add a live source of validators from a trusted URL. The URL will be contacted periodically to update the list. The fetch operation is performed asynchronously, this call doesn't block. Thread safety: Can be called from any thread.
Implements ripple::Validators::Manager.
Definition at line 222 of file Manager.cpp.
References addSource(), and ripple::Validators::SourceURL::New().
     {
         addSource (SourceURL::New (url));
     }
void ripple::Validators::ManagerImp::checkSources () inline
Definition at line 343 of file Manager.cpp.
References ripple::Validators::checkEverySeconds, ripple::Validators::Logic::fetch_one(), m_checkSources, m_checkTimer, m_journal, m_logic, beast::RelativeTime::seconds(), beast::DeadlineTimer::setExpiration(), and beast::Journal::trace.
Referenced by run().
     {
         if (m_checkSources)
         {
             if (m_logic.fetch_one () == 0)
             {
                 m_journal.trace << "All sources checked";
                 // Made it through the list without interruption!
                 // Clear the flag and set the deadline timer again.
                 //
                 m_checkSources = false;
                 m_journal.trace << "Next check timer expires in " <<
                     beast::RelativeTime::seconds (checkEverySeconds);
                 m_checkTimer.setExpiration (checkEverySeconds);
             }
         }
     }
void ripple::Validators::ManagerImp::init () inline
Definition at line 317 of file Manager.cpp.
References ripple::Validators::Logic::load(), m_databaseFile, m_logic, m_store, and ripple::Validators::StoreSqdb::open().
Referenced by run().
     {
         beast::Error error (m_store.open (m_databaseFile));
         if (! error)
         {
             m_logic.load ();
         }
     }
void ripple::Validators::ManagerImp::ledgerClosed (RippleLedgerHash const & ledgerHash) inline virtual
Called when a ledger is closed.
Implements ripple::Validators::Manager.
Definition at line 242 of file Manager.cpp.
References beast::ServiceQueueType< Allocator >::dispatch(), beast::Stoppable::isStopping(), ripple::Validators::Logic::ledgerClosed(), m_context, m_logic, m_queue, and beast::ScopedWrapperContext< Context, ScopedType >::wrap().
     {
         if (! isStopping())
             m_queue.dispatch (m_context.wrap (std::bind (
                 &Logic::ledgerClosed, &m_logic, ledgerHash)));
     }
void ripple::Validators::ManagerImp::onDeadlineTimer (beast::DeadlineTimer & timer) inline virtual
Reimplemented from beast::DeadlineTimer::Listener.
Definition at line 327 of file Manager.cpp.
References beast::ServiceQueueType< Allocator >::dispatch(), m_checkTimer, m_context, m_journal, m_queue, setCheckSources(), beast::Journal::trace, and beast::ScopedWrapperContext< Context, ScopedType >::wrap().
     {
         if (timer == m_checkTimer)
         {
             m_journal.trace << "Check timer expired";
             m_queue.dispatch (m_context.wrap (std::bind (
                 &ManagerImp::setCheckSources, this)));
         }
     }
void ripple::Validators::ManagerImp::onPrepare () inline virtual
Override called during preparation. Since all other Stoppable objects in the tree have already been constructed, this provides an opportunity to perform initialization which depends on calling into other Stoppable objects. This call is made on the same thread that called prepare(). The default implementation does nothing. Guaranteed to only be called once.
Reimplemented from beast::Stoppable.
Definition at line 255 of file Manager.cpp.
     {
     }
void ripple::Validators::ManagerImp::onStart () inline virtual
Override called during start.
Reimplemented from beast::Stoppable.
Definition at line 259 of file Manager.cpp.
References beast::ServiceQueueType< Allocator >::dispatch(), m_context, m_queue, setCheckSources(), beast::Thread::startThread(), and beast::ScopedWrapperContext< Context, ScopedType >::wrap().
     {
         // Do this late so the sources have a chance to be added.
         m_queue.dispatch (m_context.wrap (std::bind (
             &ManagerImp::setCheckSources, this)));
         startThread();
     }
void ripple::Validators::ManagerImp::onStop () inline virtual
Override called when the stop notification is issued.
The call is made on an unspecified, implementation-specific thread. onStop and onChildrenStopped will never be called concurrently, across all Stoppable objects descended from the same root, inclusive of the root.
It is safe to call isStopping, isStopped, and areChildrenStopped from within this function; The values returned will always be valid and never change during the callback.
The default implementation simply calls stopped(). This is applicable when the Stoppable has a trivial stop operation (or no stop operation), and we are merely using the Stoppable API to position it as a dependency of some parent service.
Thread safety: May not block for long periods. Guaranteed only to be called once. Must be safe to call from any thread at any time.
Reimplemented from beast::Stoppable.
Definition at line 268 of file Manager.cpp.
References beast::ServiceQueueType< Allocator >::dispatch(), m_context, m_logic, m_queue, ripple::Validators::Logic::stop(), and beast::ScopedWrapperContext< Context, ScopedType >::wrap().
     {
         m_logic.stop ();
         m_queue.dispatch (m_context.wrap (std::bind (
             &Thread::signalThreadShouldExit, this)));
     }
void ripple::Validators::ManagerImp::onWrite (beast::PropertyStream::Map &) inline virtual
Subclass override. The default version does nothing.
Reimplemented from beast::PropertyStream::Source.
Definition at line 282 of file Manager.cpp.
References beast::PropertyStream::Set::add(), ripple::Validators::Validator::count(), ripple::Validators::Logic::m_chosenList, m_context, m_logic, ripple::Validators::Logic::m_sources, ripple::Validators::Logic::m_validators, ripple::Validators::Count::onWrite(), and ripple::IdentifierType< Traits >::to_string().
     {
         Context::Scope scope (m_context);
         map ["trusted"] = std::uint32_t (
             m_logic.m_chosenList ?
                 m_logic.m_chosenList->size() : 0);
         {
             beast::PropertyStream::Set items ("sources", map);
             for (Logic::SourceTable::const_iterator iter (m_logic.m_sources.begin());
                 iter != m_logic.m_sources.end(); ++iter)
                 items.add (iter->source->to_string());
         }
         {
             beast::PropertyStream::Set items ("validators", map);
             for (Logic::ValidatorTable::iterator iter (m_logic.m_validators.begin());
                 iter != m_logic.m_validators.end(); ++iter)
             {
                 RipplePublicKey const& publicKey (iter->first);
                 Validator const& validator (iter->second);
                 beast::PropertyStream::Map item (items);
                 item["public_key"] = publicKey.to_string();
                 validator.count().onWrite (item);
             }
         }
     }
void ripple::Validators::ManagerImp::receiveValidation (ReceivedValidation const & rv) inline virtual
Called when a validation with a proper signature is received.
Implements ripple::Validators::Manager.
Definition at line 235 of file Manager.cpp.
References beast::ServiceQueueType< Allocator >::dispatch(), beast::Stoppable::isStopping(), m_context, m_logic, m_queue, ripple::Validators::Logic::receiveValidation(), and beast::ScopedWrapperContext< Context, ScopedType >::wrap().
     {
         if (! isStopping())
             m_queue.dispatch (m_context.wrap (std::bind (
                 &Logic::receiveValidation, &m_logic, rv)));
     }
void ripple::Validators::ManagerImp::run () inline virtual
Must be implemented to perform the thread's actual code.
Remember that the thread must regularly check the threadShouldExit() method whilst running, and if this returns true it should return from the run() method as soon as possible to avoid being forcibly killed.
See Also
threadShouldExit, startThread
Implements beast::Thread.
Definition at line 364 of file Manager.cpp.
References checkSources(), init(), m_queue, beast::ServiceQueueType< Allocator >::run_one(), beast::Stoppable::stopped(), and beast::Thread::threadShouldExit().
     {
         init ();
         while (! this->threadShouldExit())
         {
             checkSources ();
             m_queue.run_one();
         }
         stopped();
     }
void ripple::Validators::ManagerImp::setCheckSources () inline
Definition at line 337 of file Manager.cpp.
References m_checkSources, m_journal, and beast::Journal::trace.
Referenced by onDeadlineTimer(), and onStart().
     {
         m_journal.trace << "Checking sources";
         m_checkSources = true;
     }
Member Data Documentation
bool ripple::Validators::ManagerImp::m_checkSources
Definition at line 151 of file Manager.cpp.
Referenced by checkSources(), and setCheckSources().
beast::DeadlineTimer ripple::Validators::ManagerImp::m_checkTimer
Definition at line 140 of file Manager.cpp.
Referenced by checkSources(), and onDeadlineTimer().
Context ripple::Validators::ManagerImp::m_context
Definition at line 146 of file Manager.cpp.
Referenced by addSource(), addStaticSource(), ledgerClosed(), onDeadlineTimer(), onStart(), onStop(), onWrite(), and receiveValidation().
beast::File ripple::Validators::ManagerImp::m_databaseFile
Definition at line 137 of file Manager.cpp.
Referenced by init(), and ManagerImp().
beast::Journal ripple::Validators::ManagerImp::m_journal
Definition at line 136 of file Manager.cpp.
Referenced by addStrings(), checkSources(), ManagerImp(), onDeadlineTimer(), and setCheckSources().
Logic ripple::Validators::ManagerImp::m_logic
Definition at line 139 of file Manager.cpp.
Referenced by addSource(), addStaticSource(), checkSources(), init(), ledgerClosed(), onStop(), onWrite(), and receiveValidation().
beast::ServiceQueue ripple::Validators::ManagerImp::m_queue
Definition at line 141 of file Manager.cpp.
Referenced by addSource(), addStaticSource(), ledgerClosed(), onDeadlineTimer(), onStart(), onStop(), receiveValidation(), and run().
StoreSqdb ripple::Validators::ManagerImp::m_store
Definition at line 138 of file Manager.cpp.
Referenced by init().
The documentation for this class was generated from the following file:
rippled/src/ripple/validators/impl/Manager.cpp