rippled: beast::detail::ListIterator< N > Class Template Reference
beast::detail::ListIterator< N > Class Template Reference
#include <List.h>
Public Types
typedef detail::CopyConst< N,
typename N::value_type >::type value_type
typedef value_type * pointer
typedef value_type & reference
typedef std::size_t size_type
Public Member Functions
ListIterator (N *node=nullptr) noexcept
template<typename M >
ListIterator (ListIterator< M > const &other) noexcept
template<typename M >
bool operator== (ListIterator< M > const &other) const noexcept
template<typename M >
bool operator!= (ListIterator< M > const &other) const noexcept
reference operator* () const noexcept
pointer operator-> () const noexcept
ListIterator & operator++ () noexcept
ListIterator operator++ (int) noexcept
ListIterator & operator-- () noexcept
ListIterator operator-- (int) noexcept
Private Member Functions
reference dereference () const noexcept
void increment () noexcept
void decrement () noexcept
Private Attributes
N * m_node
Detailed Description
template<typename N>
class beast::detail::ListIterator< N >
Definition at line 73 of file List.h.
Member Typedef Documentation
template<typename N> typedef value_type* beast::detail::ListIterator< N >::pointer
Definition at line 79 of file List.h.
template<typename N> typedef value_type& beast::detail::ListIterator< N >::reference
Definition at line 80 of file List.h.
template<typename N> typedef std::size_t beast::detail::ListIterator< N >::size_type
Definition at line 81 of file List.h.
template<typename N> typedef detail::CopyConst< N, typename N::value_type>::type beast::detail::ListIterator< N >::value_type
Definition at line 78 of file List.h.
Constructor & Destructor Documentation
template<typename N> beast::detail::ListIterator< N >::ListIterator (N * node = nullptr) inline noexcept
Definition at line 83 of file List.h.
         : m_node (node)
     {
     }
template<typename N> template<typename M > beast::detail::ListIterator< N >::ListIterator (ListIterator< M > const & other) inline noexcept
Definition at line 89 of file List.h.
         : m_node (other.m_node)
     {
     }
Member Function Documentation
template<typename N> void beast::detail::ListIterator< N >::decrement () inline private noexcept
Definition at line 153 of file List.h.
References beast::detail::ListIterator< N >::m_node.
Referenced by beast::detail::ListIterator< N >::operator--().
     {
         m_node = m_node->m_prev;
     }
template<typename N> reference beast::detail::ListIterator< N >::dereference () const inline private noexcept
Definition at line 143 of file List.h.
Referenced by beast::detail::ListIterator< N >::operator*(), and beast::detail::ListIterator< N >::operator->().
     {
         return static_cast <reference> (*m_node);
     }
template<typename N> void beast::detail::ListIterator< N >::increment () inline private noexcept
Definition at line 148 of file List.h.
References beast::detail::ListIterator< N >::m_node.
Referenced by beast::detail::ListIterator< N >::operator++().
     {
         m_node = m_node->m_next;
     }
template<typename N> template<typename M > bool beast::detail::ListIterator< N >::operator!= (ListIterator< M > const & other) const inline noexcept
Definition at line 101 of file List.h.
     {
         return ! ((*this) == other);
     }
template<typename N> reference beast::detail::ListIterator< N >::operator* () const inline noexcept
Definition at line 106 of file List.h.
References beast::detail::ListIterator< N >::dereference().
     {
         return dereference ();
     }
template<typename N> ListIterator& beast::detail::ListIterator< N >::operator++ () inline noexcept
Definition at line 116 of file List.h.
References beast::detail::ListIterator< N >::increment().
     {
         increment ();
         return *this;
     }
template<typename N> ListIterator beast::detail::ListIterator< N >::operator++ (int) inline noexcept
Definition at line 122 of file List.h.
References beast::detail::ListIterator< N >::increment().
     {
         ListIterator result (*this);
         increment ();
         return result;
     }
template<typename N> ListIterator& beast::detail::ListIterator< N >::operator-- () inline noexcept
Definition at line 129 of file List.h.
References beast::detail::ListIterator< N >::decrement().
     {
         decrement ();
         return *this;
     }
template<typename N> ListIterator beast::detail::ListIterator< N >::operator-- (int) inline noexcept
Definition at line 135 of file List.h.
References beast::detail::ListIterator< N >::decrement().
     {
         ListIterator result (*this);
         decrement ();
         return result;
     }
template<typename N> pointer beast::detail::ListIterator< N >::operator-> () const inline noexcept
Definition at line 111 of file List.h.
References beast::detail::ListIterator< N >::dereference().
     {
         return &dereference ();
     }
template<typename N> template<typename M > bool beast::detail::ListIterator< N >::operator== (ListIterator< M > const & other) const inline noexcept
Definition at line 95 of file List.h.
References beast::detail::ListIterator< N >::m_node.
     {
         return m_node == other.m_node;
     }
Member Data Documentation
template<typename N> N* beast::detail::ListIterator< N >::m_node private
Definition at line 158 of file List.h.
Referenced by beast::detail::ListIterator< N >::decrement(), beast::detail::ListIterator< N >::increment(), and beast::detail::ListIterator< N >::operator==().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/intrusive/List.h