rippled: beast::StringPairArray Class Reference
beast::StringPairArray Class Reference
#include <StringPairArray.h>
Public Member Functions
StringPairArray (bool ignoreCaseWhenComparingKeys=true)
StringPairArray (const StringPairArray &other)
~StringPairArray ()
StringPairArray & operator= (const StringPairArray &other)
void swapWith (StringPairArray &other)
bool operator== (const StringPairArray &other) const
bool operator!= (const StringPairArray &other) const
const String & operator[] (const String &key) const
String getValue (const String &key, const String &defaultReturnValue) const
const StringArray & getAllKeys () const noexcept
const StringArray & getAllValues () const noexcept
int size () const noexcept
void set (const String &key, const String &value)
void addArray (const StringPairArray &other)
void clear ()
void remove (const String &key)
void remove (int index)
void setIgnoresCase (bool shouldIgnoreCase)
String getDescription () const
void minimiseStorageOverheads ()
Private Attributes
StringArray keys
StringArray values
bool ignoreCase
Detailed Description
A container for holding a set of strings which are keyed by another string.
See Also
StringArray
Definition at line 38 of file StringPairArray.h.
Constructor & Destructor Documentation
beast::StringPairArray::StringPairArray (bool ignoreCaseWhenComparingKeys = true)
Creates an empty array
Definition at line 27 of file StringPairArray.cpp.
     : ignoreCase (ignoreCase_)
 {
 }
beast::StringPairArray::StringPairArray (const StringPairArray & other)
Creates a copy of another array
Definition at line 32 of file StringPairArray.cpp.
     : keys (other.keys),
       values (other.values),
       ignoreCase (other.ignoreCase)
 {
 }
beast::StringPairArray::~StringPairArray ()
Destructor.
Definition at line 39 of file StringPairArray.cpp.
 {
 }
Member Function Documentation
void beast::StringPairArray::addArray (const StringPairArray & other)
Adds the items from another array to this one.
This is equivalent to using set() to add each of the pairs from the other array.
Definition at line 101 of file StringPairArray.cpp.
References keys, set(), size(), and values.
 {
     for (int i = 0; i < other.size(); ++i)
         set (other.keys[i], other.values[i]);
 }
void beast::StringPairArray::clear ()
Removes all elements from the array.
Definition at line 107 of file StringPairArray.cpp.
References beast::StringArray::clear(), keys, and values.
 {
     keys.clear();
     values.clear();
 }
const StringArray& beast::StringPairArray::getAllKeys () const inline noexcept
Returns a list of all keys in the array.
Definition at line 94 of file StringPairArray.h.
References keys.
Referenced by beast::HTTPHeaders::at().
 { return keys; }
const StringArray& beast::StringPairArray::getAllValues () const inline noexcept
Returns a list of all values in the array.
Definition at line 97 of file StringPairArray.h.
References values.
Referenced by beast::HTTPHeaders::at().
 { return values; }
String beast::StringPairArray::getDescription () const
Returns a descriptive string containing the items. This is handy for dumping the contents of an array.
Definition at line 129 of file StringPairArray.cpp.
References keys, beast::StringArray::size(), and values.
 {
     String s;
     for (int i = 0; i < keys.size(); ++i)
     {
         s << keys[i] << " = " << values[i];
         if (i < keys.size())
             s << ", ";
     }
     return s;
 }
String beast::StringPairArray::getValue (const String & key, const String & defaultReturnValue) const
Finds the value corresponding to a key string.
If no such key is found, this will just return the value provided as a default.
See Also
operator[]
Definition at line 76 of file StringPairArray.cpp.
References ignoreCase, beast::StringArray::indexOf(), keys, and values.
 {
     const int i = keys.indexOf (key, ignoreCase);
     if (i >= 0)
         return values[i];
     return defaultReturnValue;
 }
void beast::StringPairArray::minimiseStorageOverheads ()
Reduces the amount of storage being used by the array.
Arrays typically allocate slightly more storage than they need, and after removing elements, they may have quite a lot of unused space allocated. This method will reduce the amount of allocated storage to a minimum.
Definition at line 143 of file StringPairArray.cpp.
References keys, beast::StringArray::minimiseStorageOverheads(), and values.
 {
     keys.minimiseStorageOverheads();
     values.minimiseStorageOverheads();
 }
bool beast::StringPairArray::operator!= (const StringPairArray & other) const
Compares two arrays. Comparisons are case-sensitive.
Returns
false if the other array contains exactly the same strings with the same keys
Definition at line 66 of file StringPairArray.cpp.
References operator==().
 {
     return ! operator== (other);
 }
StringPairArray & beast::StringPairArray::operator= (const StringPairArray & other)
Copies the contents of another string array into this one
Definition at line 43 of file StringPairArray.cpp.
References keys, and values.
 {
     keys = other.keys;
     values = other.values;
     return *this;
 }
bool beast::StringPairArray::operator== (const StringPairArray & other) const
Compares two arrays. Comparisons are case-sensitive.
Returns
true only if the other array contains exactly the same strings with the same keys
Definition at line 57 of file StringPairArray.cpp.
References keys, beast::StringArray::size(), and values.
Referenced by operator!=().
 {
     for (int i = keys.size(); --i >= 0;)
         if (other [keys[i]] != values[i])
             return false;
     return true;
 }
const String & beast::StringPairArray::operator[] (const String & key) const
Finds the value corresponding to a key string.
If no such key is found, this will just return an empty string. To check whether a given key actually exists (because it might actually be paired with an empty string), use the getAllKeys() method to obtain a list.
Obviously the reference returned shouldn't be stored for later use, as the string it refers to may disappear when the array changes.
See Also
getValue
Definition at line 71 of file StringPairArray.cpp.
References ignoreCase, beast::StringArray::indexOf(), keys, and values.
 {
     return values [keys.indexOf (key, ignoreCase)];
 }
void beast::StringPairArray::remove (const String & key)
Removes a string from the array based on its key.
If the key isn't found, nothing will happen.
Definition at line 113 of file StringPairArray.cpp.
References ignoreCase, beast::StringArray::indexOf(), and keys.
 {
     remove (keys.indexOf (key, ignoreCase));
 }
void beast::StringPairArray::remove (int index)
Removes a string from the array based on its index.
If the index is out-of-range, no action will be taken.
Definition at line 118 of file StringPairArray.cpp.
References keys, beast::StringArray::remove(), and values.
 {
     keys.remove (index);
     values.remove (index);
 }
void beast::StringPairArray::set (const String & key, const String & value)
Adds or amends a key/value pair.
If a value already exists with this key, its value will be overwritten, otherwise the key/value pair will be added to the array.
Definition at line 86 of file StringPairArray.cpp.
References beast::StringArray::add(), ignoreCase, beast::StringArray::indexOf(), keys, beast::StringArray::set(), and values.
Referenced by addArray(), beast::HTTPParserImpl::addFieldValue(), ripple::parseDelimitedKeyValueString(), ripple::parseKeyValueSection(), ripple::NodeStore::Backend_test::testBackend(), ripple::NodeStore::NodeStoreDatabase_test::testImport(), and ripple::NodeStore::NodeStoreDatabase_test::testNodeStore().
 {
     const int i = keys.indexOf (key, ignoreCase);
     if (i >= 0)
     {
         values.set (i, value);
     }
     else
     {
         keys.add (key);
         values.add (value);
     }
 }
void beast::StringPairArray::setIgnoresCase (bool shouldIgnoreCase)
Indicates whether to use a case-insensitive search when looking up a key string.
Definition at line 124 of file StringPairArray.cpp.
References ignoreCase.
 {
     ignoreCase = shouldIgnoreCase;
 }
int beast::StringPairArray::size () const inline noexcept
Returns the number of strings in the array
Definition at line 100 of file StringPairArray.h.
References keys, and beast::StringArray::size().
Referenced by addArray(), beast::HTTPHeaders::empty(), ripple::HTTP::Peer::handle_read(), ripple::NodeStore::ManagerImp::make_Database(), beast::HTTPHeaders::size(), and beast::HTTPHeaders::toString().
 { return keys.size(); };
void beast::StringPairArray::swapWith (StringPairArray & other)
Swap the contents of this array with another.
Definition at line 50 of file StringPairArray.cpp.
References ignoreCase, keys, beast::asio::swap(), beast::StringArray::swapWith(), and values.
Referenced by beast::HTTPHeaders::HTTPHeaders().
 {
     std::swap (ignoreCase, other.ignoreCase);
     keys.swapWith (other.keys);
     values.swapWith (other.values);
 }
Member Data Documentation
bool beast::StringPairArray::ignoreCase private
Definition at line 157 of file StringPairArray.h.
Referenced by getValue(), operator[](), remove(), set(), setIgnoresCase(), and swapWith().
StringArray beast::StringPairArray::keys private
Definition at line 156 of file StringPairArray.h.
Referenced by addArray(), clear(), getAllKeys(), getDescription(), getValue(), minimiseStorageOverheads(), operator=(), operator==(), operator[](), remove(), set(), size(), and swapWith().
StringArray beast::StringPairArray::values private
Definition at line 156 of file StringPairArray.h.
Referenced by addArray(), clear(), getAllValues(), getDescription(), getValue(), minimiseStorageOverheads(), operator=(), operator==(), operator[](), remove(), set(), and swapWith().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_core/text/StringPairArray.h
rippled/src/beast/modules/beast_core/text/StringPairArray.cpp