rippled: beast::ParsedURL_test Class Reference
beast::ParsedURL_test Class Reference
Public Member Functions
void checkURL (String const &url)
void testURL ()
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 28 of file ParsedURL.cpp.
Member Function Documentation
void beast::ParsedURL_test::checkURL (String const & url) inline
Definition at line 31 of file ParsedURL.cpp.
References beast::ParsedURL::error(), beast::unit_test::suite::expect(), beast::URL::toString(), and beast::ParsedURL::url().
Referenced by testURL().
     {
         ParsedURL result (url);
         expect (result.error () == 0);
         expect (result.url ().toString () == url);
     }
void beast::ParsedURL_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 43 of file ParsedURL.cpp.
References testURL().
     {
         testURL ();
     }
void beast::ParsedURL_test::testURL () inline
Definition at line 38 of file ParsedURL.cpp.
References checkURL().
Referenced by run().
     {
         checkURL ("http://www.boost.org/doc/libs/1_54_0/doc/html/boost_asio/reference.html");
     }
The documentation for this class was generated from the following file:
rippled/src/beast/beast/http/tests/ParsedURL.cpp