rippled: rocksdb::TableBuilder Class Reference
rocksdb::TableBuilder Class Reference abstract
#include <table.h>
Public Member Functions
virtual ~TableBuilder ()
virtual void Add (const Slice &key, const Slice &value)=0
virtual Status status () const =0
virtual Status Finish ()=0
virtual void Abandon ()=0
virtual uint64_t NumEntries () const =0
virtual uint64_t FileSize () const =0
Detailed Description
Definition at line 35 of file table.h.
Constructor & Destructor Documentation
virtual rocksdb::TableBuilder::~TableBuilder () inline virtual
Definition at line 38 of file table.h.
 {}
Member Function Documentation
virtual void rocksdb::TableBuilder::Abandon () pure virtual
Implemented in rocksdb::SimpleTableBuilder, and rocksdb::BlockBasedTableBuilder.
Referenced by rocksdb::BuildTable().
virtual void rocksdb::TableBuilder::Add (const Slice & key, const Slice & value) pure virtual
Implemented in rocksdb::SimpleTableBuilder, and rocksdb::BlockBasedTableBuilder.
Referenced by rocksdb::BuildTable(), rocksdb::TableReaderBenchmark(), and rocksdb::TEST().
virtual uint64_t rocksdb::TableBuilder::FileSize () const pure virtual
Implemented in rocksdb::SimpleTableBuilder, and rocksdb::BlockBasedTableBuilder.
Referenced by rocksdb::BuildTable().
virtual Status rocksdb::TableBuilder::Finish () pure virtual
Implemented in rocksdb::SimpleTableBuilder, and rocksdb::BlockBasedTableBuilder.
Referenced by rocksdb::BuildTable(), rocksdb::TableReaderBenchmark(), and rocksdb::TEST().
virtual uint64_t rocksdb::TableBuilder::NumEntries () const pure virtual
Implemented in rocksdb::SimpleTableBuilder, and rocksdb::BlockBasedTableBuilder.
virtual Status rocksdb::TableBuilder::status () const pure virtual
Implemented in rocksdb::SimpleTableBuilder, and rocksdb::BlockBasedTableBuilder.
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/include/rocksdb/table.h