rippled: beast::PropertyStream_test Class Reference
beast::PropertyStream_test Class Reference
Public Types
typedef PropertyStream::Source Source
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Member Functions
void test_peel_name (std::string s, std::string const &expected, std::string const &expected_remainder)
void test_peel_leading_slash (std::string s, std::string const &expected, bool should_be_found)
void test_peel_trailing_slashstar (std::string s, std::string const &expected_remainder, bool should_be_found)
void test_find_one (Source &root, Source *expected, std::string const &name)
void test_find_path (Source &root, std::string const &path, Source *expected)
void test_find_one_deep (Source &root, std::string const &name, Source *expected)
void test_find (Source &root, std::string path, Source *expected, bool expected_star)
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Additional Inherited Members
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 610 of file PropertyStream.cpp.
Member Typedef Documentation
typedef PropertyStream::Source beast::PropertyStream_test::Source
Definition at line 613 of file PropertyStream.cpp.
Member Function Documentation
void beast::PropertyStream_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 716 of file PropertyStream.cpp.
References beast::PropertyStream::Source::add(), ripple::f, and testcase.
     {
         Source a ("a");
         Source b ("b");
         Source c ("c");
         Source d ("d");
         Source e ("e");
         Source f ("f");
         Source g ("g");
         //
         // a { b { d { f }, e }, c { g } }
         //
         a.add ( b );
         a.add ( c );
         c.add ( g );
         b.add ( d );
         b.add ( e );
         d.add ( f );
         testcase ("peel_name");
         test_peel_name ("a", "a", "");
         test_peel_name ("foo/bar", "foo", "bar");
         test_peel_name ("foo/goo/bar", "foo", "goo/bar");
         test_peel_name ("", "", "");
         testcase ("peel_leading_slash");
         test_peel_leading_slash ("foo/", "foo/", false);
         test_peel_leading_slash ("foo", "foo", false);
         test_peel_leading_slash ("/foo/", "foo/", true);
         test_peel_leading_slash ("/foo", "foo", true);
         testcase ("peel_trailing_slashstar");
         test_peel_trailing_slashstar ("/foo/goo/*", "/foo/goo", true);
         test_peel_trailing_slashstar ("foo/goo/*", "foo/goo", true);
         test_peel_trailing_slashstar ("/foo/goo/", "/foo/goo", false);
         test_peel_trailing_slashstar ("foo/goo", "foo/goo", false);
         test_peel_trailing_slashstar ("", "", false);
         test_peel_trailing_slashstar ("/", "", false);
         test_peel_trailing_slashstar ("/*", "", true);
         test_peel_trailing_slashstar ("//", "/", false);
         test_peel_trailing_slashstar ("**", "*", true);
         test_peel_trailing_slashstar ("*/", "*", false);
         testcase ("find_one");
         test_find_one (a, &b, "b");
         test_find_one (a, nullptr, "d");
         test_find_one (b, &e, "e");
         test_find_one (d, &f, "f");
         testcase ("find_path");
         test_find_path (a, "a", nullptr);
         test_find_path (a, "e", nullptr);
         test_find_path (a, "a/b", nullptr);
         test_find_path (a, "a/b/e", nullptr);
         test_find_path (a, "b/e/g", nullptr);
         test_find_path (a, "b/e/f", nullptr);
         test_find_path (a, "b", &b);
         test_find_path (a, "b/e", &e);
         test_find_path (a, "b/d/f", &f);
         testcase ("find_one_deep");
         test_find_one_deep (a, "z", nullptr);
         test_find_one_deep (a, "g", &g);
         test_find_one_deep (a, "b", &b);
         test_find_one_deep (a, "d", &d);
         test_find_one_deep (a, "f", &f);
         testcase ("find");
         test_find (a, "",     &a, false);
         test_find (a, "*",    &a, true);
         test_find (a, "/b",   &b, false);
         test_find (a, "b",    &b, false);
         test_find (a, "d",    &d, false);
         test_find (a, "/b*",  &b, true);
         test_find (a, "b*",   &b, true);
         test_find (a, "d*",   &d, true);
         test_find (a, "/b/*", &b, true);
         test_find (a, "b/*",  &b, true);
         test_find (a, "d/*",  &d, true);
         test_find (a, "a",    nullptr, false);
         test_find (a, "/d",   nullptr, false);
         test_find (a, "/d*",  nullptr, true);
         test_find (a, "/d/*", nullptr, true);
     }
void beast::PropertyStream_test::test_find (Source & root, std::string path, Source * expected, bool expected_star) inline
Definition at line 701 of file PropertyStream.cpp.
References beast::IP::detail::expect(), and beast::PropertyStream::Source::find().
     {
         try
         {
             auto const result (root.find (path));
             expect (result.first == expected);
             expect (result.second == expected_star);
         }
         catch (...)
         {
             fail ("unhandled exception");;
         }
     }
void beast::PropertyStream_test::test_find_one (Source & root, Source * expected, std::string const & name) inline
Definition at line 660 of file PropertyStream.cpp.
References beast::IP::detail::expect(), and beast::PropertyStream::Source::find_one().
     {
         try
         {
             Source* source (root.find_one (name));
             expect (source == expected);
         }
         catch (...)
         {
             fail ("unhandled exception");;
         }
     }
void beast::PropertyStream_test::test_find_one_deep (Source & root, std::string const & name, Source * expected) inline
Definition at line 687 of file PropertyStream.cpp.
References beast::IP::detail::expect(), and beast::PropertyStream::Source::find_one_deep().
     {
         try
         {
             Source* source (root.find_one_deep (name));
             expect (source == expected);
         }
         catch(...)
         {
             fail ("unhandled exception");;
         }
     }
void beast::PropertyStream_test::test_find_path (Source & root, std::string const & path, Source * expected) inline
Definition at line 673 of file PropertyStream.cpp.
References beast::IP::detail::expect(), and beast::PropertyStream::Source::find_path().
     {
         try
         {
             Source* source (root.find_path (path));
             expect (source == expected);
         }
         catch (...)
         {
             fail ("unhandled exception");;
         }
     }
void beast::PropertyStream_test::test_peel_leading_slash (std::string s, std::string const & expected, bool should_be_found) inline
Definition at line 630 of file PropertyStream.cpp.
References beast::IP::detail::expect(), and beast::PropertyStream::Source::peel_leading_slash().
     {
         try
         {
             bool const found (Source::peel_leading_slash (&s));
             expect (found == should_be_found);
             expect (s == expected);
         }
         catch(...)
         {
             fail ("unhandled exception");;
         }
     }
void beast::PropertyStream_test::test_peel_name (std::string s, std::string const & expected, std::string const & expected_remainder) inline
Definition at line 615 of file PropertyStream.cpp.
References beast::IP::detail::expect(), and beast::PropertyStream::Source::peel_name().
     {
         try
         {
             std::string const peeled_name = Source::peel_name (&s);
             expect (peeled_name == expected);
             expect (s == expected_remainder);
         }
         catch (...)
         {
             fail ("unhandled exception");;
        }
     }
void beast::PropertyStream_test::test_peel_trailing_slashstar (std::string s, std::string const & expected_remainder, bool should_be_found) inline
Definition at line 645 of file PropertyStream.cpp.
References beast::IP::detail::expect(), and beast::PropertyStream::Source::peel_trailing_slashstar().
     {
         try
         {
             bool const found (Source::peel_trailing_slashstar (&s));
             expect (found == should_be_found);
             expect (s == expected_remainder);
         }
         catch (...)
         {
             fail ("unhandled exception");;
         }
     }
The documentation for this class was generated from the following file:
rippled/src/beast/beast/utility/impl/PropertyStream.cpp