rippled: ripple::NodeStore::NodeStoreBasic_test Class Reference
ripple::NodeStore::NodeStoreBasic_test Class Reference
Public Member Functions
void testBatches (std::int64_t const seedValue)
void testBlobs (std::int64_t const seedValue)
void run ()
Public Member Functions inherited from ripple::NodeStore::TestBase
void storeBatch (Backend &backend, Batch const &batch)
void fetchCopyOfBatch (Backend &backend, Batch *pCopy, Batch const &batch)
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Additional Inherited Members
Public Types inherited from ripple::NodeStore::TestBase
enum { maxPayloadBytes = 2000, numObjectsToTest = 2000 }
Static Public Member Functions inherited from ripple::NodeStore::TestBase
static void createPredictableBatch (Batch &batch, int startingIndex, int numObjects, std::int64_t seedValue)
static bool areBatchesEqual (Batch const &lhs, Batch const &rhs)
static void storeBatch (Database &db, Batch const &batch)
static void fetchCopyOfBatch (Database &db, Batch *pCopy, Batch const &batch)
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 25 of file BasicTests.cpp.
Member Function Documentation
void ripple::NodeStore::NodeStoreBasic_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 73 of file BasicTests.cpp.
References testBatches(), and testBlobs().
     {
         std::int64_t const seedValue = 50;
         testBatches (seedValue);
         testBlobs (seedValue);
     }
void ripple::NodeStore::NodeStoreBasic_test::testBatches (std::int64_t const seedValue) inline
Definition at line 29 of file BasicTests.cpp.
References ripple::NodeStore::TestBase::areBatchesEqual(), ripple::NodeStore::TestBase::createPredictableBatch(), beast::unit_test::suite::expect(), ripple::NodeStore::TestBase::numObjectsToTest, and beast::unit_test::suite::testcase().
Referenced by run().
     {
         testcase ("batch");
         Batch batch1;
         createPredictableBatch (batch1, 0, numObjectsToTest, seedValue);
         Batch batch2;
         createPredictableBatch (batch2, 0, numObjectsToTest, seedValue);
         expect (areBatchesEqual (batch1, batch2), "Should be equal");
         Batch batch3;
         createPredictableBatch (batch3, 1, numObjectsToTest, seedValue);
         expect (! areBatchesEqual (batch1, batch3), "Should not be equal");
     }
void ripple::NodeStore::NodeStoreBasic_test::testBlobs (std::int64_t const seedValue) inline
Definition at line 48 of file BasicTests.cpp.
References ripple::NodeStore::TestBase::createPredictableBatch(), beast::unit_test::suite::expect(), ripple::NodeStore::EncodedBlob::getData(), ripple::NodeStore::EncodedBlob::getKey(), ripple::NodeStore::EncodedBlob::getSize(), ripple::NodeStore::TestBase::numObjectsToTest, ripple::NodeStore::EncodedBlob::prepare(), and beast::unit_test::suite::testcase().
Referenced by run().
     {
         testcase ("encoding");
         Batch batch;
         createPredictableBatch (batch, 0, numObjectsToTest, seedValue);
         EncodedBlob encoded;
         for (int i = 0; i < batch.size (); ++i)
         {
             encoded.prepare (batch [i]);
             DecodedBlob decoded (encoded.getKey (), encoded.getData (), encoded.getSize ());
             expect (decoded.wasOk (), "Should be ok");
             if (decoded.wasOk ())
             {
                 NodeObject::Ptr const object (decoded.createObject ());
                 expect (batch [i]->isCloneOf (object), "Should be clones");
             }
         }
     }
The documentation for this class was generated from the following file:
rippled/src/ripple_core/nodestore/tests/BasicTests.cpp