rippled: ripple::Base58::Alphabet Class Reference
ripple::Base58::Alphabet Class Reference
#include <Base58.h>
Public Member Functions
Alphabet (char const *chars)
char const * chars () const
char to_char (int digit) const
char operator[] (int digit) const
int from_char (char c) const
Private Attributes
char const * m_chars
int m_inverse [128]
Detailed Description
Definition at line 46 of file Base58.h.
Constructor & Destructor Documentation
ripple::Base58::Alphabet::Alphabet (char const * chars) inline explicit
Definition at line 50 of file Base58.h.
References m_inverse.
             : m_chars (chars)
         {
             std::fill (m_inverse, m_inverse + 128, -1);
             int i (0);
             for (char const* c (chars); *c; ++c)
                 m_inverse [*c] = i++;
         }
Member Function Documentation
char const* ripple::Base58::Alphabet::chars () const inline
Definition at line 59 of file Base58.h.
References m_chars.
Referenced by ripple::Base58::decode().
             { return m_chars; }
int ripple::Base58::Alphabet::from_char (char c) const inline
Definition at line 68 of file Base58.h.
References m_inverse.
Referenced by ripple::Base58::raw_decode().
             { return m_inverse [c]; }
char ripple::Base58::Alphabet::operator[] (int digit) const inline
Definition at line 65 of file Base58.h.
References to_char().
             { return to_char (digit); }
char ripple::Base58::Alphabet::to_char (int digit) const inline
Definition at line 62 of file Base58.h.
References m_chars.
Referenced by operator[]().
             { return m_chars [digit]; }
Member Data Documentation
char const* ripple::Base58::Alphabet::m_chars private
Definition at line 72 of file Base58.h.
Referenced by chars(), and to_char().
int ripple::Base58::Alphabet::m_inverse[128] private
Definition at line 73 of file Base58.h.
Referenced by Alphabet(), and from_char().
The documentation for this class was generated from the following file:
rippled/src/ripple/types/api/Base58.h