rippled: ripple::Validators::SourceStringsImp Class Reference
ripple::Validators::SourceStringsImp Class Reference
Public Member Functions
SourceStringsImp (beast::String name, beast::StringArray const &strings)
~SourceStringsImp ()
std::string to_string () const
beast::String uniqueID () const
beast::String createParam ()
void fetch (Results &results, beast::Journal journal)
Private Attributes
beast::String m_name
beast::StringArray m_strings
Additional Inherited Members
Static Public Member Functions inherited from ripple::Validators::SourceStrings
static SourceStrings * New (beast::String name, beast::StringArray const &strings)
Protected Member Functions inherited from beast::SharedObject
SharedObject ()
virtual ~SharedObject ()
virtual void destroy () const
void resetReferenceCount () noexcept
Detailed Description
Definition at line 23 of file SourceStrings.cpp.
Constructor & Destructor Documentation
ripple::Validators::SourceStringsImp::SourceStringsImp (beast::String name, beast::StringArray const & strings) inline
Definition at line 28 of file SourceStrings.cpp.
         : m_name (name)
         , m_strings (strings)
     {
     }
ripple::Validators::SourceStringsImp::~SourceStringsImp () inline
Definition at line 35 of file SourceStrings.cpp.
     {
     }
Member Function Documentation
beast::String ripple::Validators::SourceStringsImp::createParam () inline virtual
A string that is used to recreate the source from the database entry.
Implements ripple::Validators::Source.
Definition at line 50 of file SourceStrings.cpp.
References beast::String::empty.
     {
         return beast::String::empty;
     }
void ripple::Validators::SourceStringsImp::fetch (Results & results, beast::Journal journal) inline virtual
Implements ripple::Validators::Source.
Definition at line 55 of file SourceStrings.cpp.
References ripple::Validators::Source::Results::expirationTime, beast::Time::getCurrentTime(), beast::RelativeTime::hours(), ripple::Validators::Source::Results::list, m_strings, ripple::Validators::Utilities::parseResultLine(), beast::StringArray::size(), and ripple::Validators::Source::Results::success.
     {
         results.list.reserve (m_strings.size ());
         for (int i = 0; i < m_strings.size (); ++i)
         {
             std::string const s (m_strings [i].toStdString ());
             Utilities::parseResultLine (results, s);
         }
         results.success = results.list.size () > 0;
         results.expirationTime = beast::Time::getCurrentTime () +
                                  beast::RelativeTime::hours (24);
     }
std::string ripple::Validators::SourceStringsImp::to_string () const inline virtual
The name of the source, used in diagnostic output.
Implements ripple::Validators::Source.
Definition at line 39 of file SourceStrings.cpp.
References m_name, and beast::String::toStdString().
     {
         return m_name.toStdString();
     }
beast::String ripple::Validators::SourceStringsImp::uniqueID () const inline virtual
An identifier that uniquely describes the source. This is used for identification in the database.
Implements ripple::Validators::Source.
Definition at line 44 of file SourceStrings.cpp.
References beast::String::empty.
     {
         // VFALCO TODO This can't be right...?
         return beast::String::empty;
     }
Member Data Documentation
beast::String ripple::Validators::SourceStringsImp::m_name private
Definition at line 71 of file SourceStrings.cpp.
Referenced by to_string().
beast::StringArray ripple::Validators::SourceStringsImp::m_strings private
Definition at line 72 of file SourceStrings.cpp.
Referenced by fetch().
The documentation for this class was generated from the following file:
rippled/src/ripple/validators/impl/SourceStrings.cpp