rippled: ripple::PeerFinder::ConnectHandouts Class Reference
ripple::PeerFinder::ConnectHandouts Class Reference
#include <ConnectHandouts.h>
Public Types
typedef beast::aged_set
< beast::IP::Address > Squelches
typedef std::vector
< beast::IP::Endpoint > list_type
Public Member Functions
ConnectHandouts (std::size_t needed, Squelches &squelches)
bool empty () const
bool full () const
bool try_insert (Endpoint const &endpoint)
list_type & list ()
list_type const & list () const
bool try_insert (beast::IP::Endpoint const &endpoint)
Private Attributes
std::size_t m_needed
Squelches & m_squelches
list_type m_list
Detailed Description
Receives handouts for making automatic connections.
Definition at line 31 of file ConnectHandouts.h.
Member Typedef Documentation
typedef std::vector<beast::IP::Endpoint> ripple::PeerFinder::ConnectHandouts::list_type
Definition at line 38 of file ConnectHandouts.h.
typedef beast::aged_set<beast::IP::Address> ripple::PeerFinder::ConnectHandouts::Squelches
Definition at line 36 of file ConnectHandouts.h.
Constructor & Destructor Documentation
ripple::PeerFinder::ConnectHandouts::ConnectHandouts (std::size_t needed, Squelches & squelches)
Definition at line 25 of file ConnectHandouts.cpp.
References m_list.
     : m_needed (needed)
     , m_squelches (squelches)
 {
     m_list.reserve (needed);
 }
Member Function Documentation
bool ripple::PeerFinder::ConnectHandouts::empty () const inline
Definition at line 48 of file ConnectHandouts.h.
References m_list.
     {
         return m_list.empty();
     }
bool ripple::PeerFinder::ConnectHandouts::full () const inline
Definition at line 53 of file ConnectHandouts.h.
References m_list, and m_needed.
Referenced by ripple::PeerFinder::Logic::autoconnect(), and try_insert().
     {
         return m_list.size() >= m_needed;
     }
list_type& ripple::PeerFinder::ConnectHandouts::list () inline
Definition at line 63 of file ConnectHandouts.h.
References m_list.
Referenced by ripple::PeerFinder::Logic::autoconnect().
     {
         return m_list;
     }
list_type const& ripple::PeerFinder::ConnectHandouts::list () const inline
Definition at line 68 of file ConnectHandouts.h.
References m_list.
     {
         return m_list;
     }
bool ripple::PeerFinder::ConnectHandouts::try_insert (Endpoint const & endpoint) inline
Definition at line 58 of file ConnectHandouts.h.
References ripple::PeerFinder::Endpoint::address.
Referenced by ripple::PeerFinder::Logic::autoconnect().
     {
         return try_insert (endpoint.address);
     }
bool ripple::PeerFinder::ConnectHandouts::try_insert (beast::IP::Endpoint const & endpoint)
Definition at line 34 of file ConnectHandouts.cpp.
References beast::IP::Endpoint::address(), full(), beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::insert(), m_list, and m_squelches.
 {
     if (full ())
         return false;
     // Make sure the address isn't already in our list
     if (std::any_of (m_list.begin(), m_list.end(),
         [&endpoint](beast::IP::Endpoint const& other)
         {
             // Ignore port for security reasons
             return other.address() ==
                 endpoint.address();
         }))
     {
         return false;
     }
     // Add to squelch list so we don't try it too often.
     // If its already there, then make try_insert fail.
     auto const result (m_squelches.insert (
         endpoint.address()));
     if (! result.second)
         return false;
     m_list.push_back (endpoint);
     return true;
 }
Member Data Documentation
list_type ripple::PeerFinder::ConnectHandouts::m_list private
Definition at line 43 of file ConnectHandouts.h.
Referenced by ConnectHandouts(), empty(), full(), list(), and try_insert().
std::size_t ripple::PeerFinder::ConnectHandouts::m_needed private
Definition at line 41 of file ConnectHandouts.h.
Referenced by full().
Squelches& ripple::PeerFinder::ConnectHandouts::m_squelches private
Definition at line 42 of file ConnectHandouts.h.
Referenced by try_insert().
The documentation for this class was generated from the following files:
rippled/src/ripple/peerfinder/impl/ConnectHandouts.h
rippled/src/ripple/peerfinder/impl/ConnectHandouts.cpp