rippled: rocksdb::FilterBlockBuilder Class Reference
rocksdb::FilterBlockBuilder Class Reference
#include <filter_block.h>
Public Member Functions
FilterBlockBuilder (const Options &opt)
void StartBlock (uint64_t block_offset)
void AddKey (const Slice &key)
Slice Finish ()
Private Member Functions
bool SamePrefix (const Slice &key1, const Slice &key2) const
void GenerateFilter ()
FilterBlockBuilder (const FilterBlockBuilder &)
void operator= (const FilterBlockBuilder &)
Private Attributes
const FilterPolicy * policy_
const SliceTransform * prefix_extractor_
bool whole_key_filtering_
const Comparator * comparator_
std::string entries_
std::vector< size_t > start_
std::string result_
std::vector< Slice > tmp_entries_
std::vector< uint32_t > filter_offsets_
Detailed Description
Definition at line 36 of file filter_block.h.
Constructor & Destructor Documentation
rocksdb::FilterBlockBuilder::FilterBlockBuilder (const Options & opt) explicit
Definition at line 24 of file filter_block.cc.
                  : policy_(opt.filter_policy),
                    prefix_extractor_(opt.prefix_extractor),
                    whole_key_filtering_(opt.whole_key_filtering),
                    comparator_(opt.comparator){}
rocksdb::FilterBlockBuilder::FilterBlockBuilder (const FilterBlockBuilder &) private
Member Function Documentation
void rocksdb::FilterBlockBuilder::AddKey (const Slice & key)
Definition at line 52 of file filter_block.cc.
References base, comparator_, rocksdb::Comparator::Compare(), rocksdb::Slice::data(), rocksdb::InternalKey::Encode(), entries_, rocksdb::ExtractUserKey(), rocksdb::SliceTransform::InDomain(), rocksdb::kTypeValue, std::chrono::prefix, prefix_extractor_, prev, SamePrefix(), rocksdb::Slice::size(), start_, rocksdb::SliceTransform::Transform(), user_key, and whole_key_filtering_.
Referenced by rocksdb::BlockBasedTableBuilder::Add(), and rocksdb::TEST().
{
   // get slice for most recently added entry
   Slice prev;
   size_t added_to_start = 0;
   // add key to filter if needed
   if (whole_key_filtering_) {
     start_.push_back(entries_.size());
     ++added_to_start;
     entries_.append(key.data(), key.size());
   }
   if (start_.size() > added_to_start) {
     size_t prev_start = start_[start_.size() - 1 - added_to_start];
     const char* base = entries_.data() + prev_start;
     size_t length = entries_.size() - prev_start;
     prev = Slice(base, length);
   }
   // add prefix to filter if needed
   if (prefix_extractor_ && prefix_extractor_->InDomain(ExtractUserKey(key))) {
     // If prefix_extractor_, this filter_block layer assumes we only
     // operate on internal keys.
     Slice user_key = ExtractUserKey(key);
     // this assumes prefix(prefix(key)) == prefix(key), as the last
     // entry in entries_ may be either a key or prefix, and we use
     // prefix(last entry) to get the prefix of the last key.
     if (prev.size() == 0 ||
         !SamePrefix(user_key, ExtractUserKey(prev))) {
       Slice prefix = prefix_extractor_->Transform(user_key);
       InternalKey internal_prefix_tmp(prefix, 0, kTypeValue);
       Slice internal_prefix = internal_prefix_tmp.Encode();
       assert(comparator_->Compare(internal_prefix, key) <= 0);
       start_.push_back(entries_.size());
       entries_.append(internal_prefix.data(), internal_prefix.size());
     }
   }
 }
Slice rocksdb::FilterBlockBuilder::Finish ()
Definition at line 91 of file filter_block.cc.
References filter_offsets_, GenerateFilter(), rocksdb::kFilterBaseLg, rocksdb::PutFixed32(), result_, and start_.
Referenced by rocksdb::BlockBasedTableBuilder::Finish(), and rocksdb::TEST().
{
   if (!start_.empty()) {
     GenerateFilter();
   }
   // Append array of per-filter offsets
   const uint32_t array_offset = result_.size();
   for (size_t i = 0; i < filter_offsets_.size(); i++) {
     PutFixed32(&result_, filter_offsets_[i]);
   }
   PutFixed32(&result_, array_offset);
   result_.push_back(kFilterBaseLg);  // Save encoding parameter in result
   return Slice(result_);
 }
void rocksdb::FilterBlockBuilder::GenerateFilter () private
Definition at line 107 of file filter_block.cc.
References base, rocksdb::FilterPolicy::CreateFilter(), entries_, filter_offsets_, policy_, result_, start_, and tmp_entries_.
Referenced by Finish(), and StartBlock().
{
   const size_t num_entries = start_.size();
   if (num_entries == 0) {
     // Fast path if there are no keys for this filter
     filter_offsets_.push_back(result_.size());
     return;
   }
   // Make list of keys from flattened key structure
   start_.push_back(entries_.size());  // Simplify length computation
   tmp_entries_.resize(num_entries);
   for (size_t i = 0; i < num_entries; i++) {
     const char* base = entries_.data() + start_[i];
     size_t length = start_[i+1] - start_[i];
     tmp_entries_[i] = Slice(base, length);
   }
   // Generate filter for current set of keys and append to result_.
   filter_offsets_.push_back(result_.size());
   policy_->CreateFilter(&tmp_entries_[0], num_entries, &result_);
   tmp_entries_.clear();
   entries_.clear();
   start_.clear();
 }
void rocksdb::FilterBlockBuilder::operator= (const FilterBlockBuilder &) private
bool rocksdb::FilterBlockBuilder::SamePrefix (const Slice & key1, const Slice & key2) const private
Definition at line 38 of file filter_block.cc.
References rocksdb::SliceTransform::InDomain(), prefix_extractor_, and rocksdb::SliceTransform::Transform().
Referenced by AddKey().
{
   if (!prefix_extractor_->InDomain(key1) &&
       !prefix_extractor_->InDomain(key2)) {
     return true;
   } else if (!prefix_extractor_->InDomain(key1) ||
              !prefix_extractor_->InDomain(key2)) {
     return false;
   } else {
     return (prefix_extractor_->Transform(key1) ==
             prefix_extractor_->Transform(key2));
   }
 }
void rocksdb::FilterBlockBuilder::StartBlock (uint64_t block_offset)
Definition at line 30 of file filter_block.cc.
References filter_offsets_, GenerateFilter(), and rocksdb::kFilterBase.
Referenced by rocksdb::BlockBasedTableBuilder::BlockBasedTableBuilder(), rocksdb::BlockBasedTableBuilder::Flush(), and rocksdb::TEST().
{
   uint64_t filter_index = (block_offset / kFilterBase);
   assert(filter_index >= filter_offsets_.size());
   while (filter_index > filter_offsets_.size()) {
     GenerateFilter();
   }
 }
Member Data Documentation
const Comparator* rocksdb::FilterBlockBuilder::comparator_ private
Definition at line 51 of file filter_block.h.
Referenced by AddKey().
std::string rocksdb::FilterBlockBuilder::entries_ private
Definition at line 53 of file filter_block.h.
Referenced by AddKey(), and GenerateFilter().
std::vector<uint32_t> rocksdb::FilterBlockBuilder::filter_offsets_ private
Definition at line 57 of file filter_block.h.
Referenced by Finish(), GenerateFilter(), and StartBlock().
const FilterPolicy* rocksdb::FilterBlockBuilder::policy_ private
Definition at line 48 of file filter_block.h.
Referenced by GenerateFilter().
const SliceTransform* rocksdb::FilterBlockBuilder::prefix_extractor_ private
Definition at line 49 of file filter_block.h.
Referenced by AddKey(), and SamePrefix().
std::string rocksdb::FilterBlockBuilder::result_ private
Definition at line 55 of file filter_block.h.
Referenced by Finish(), and GenerateFilter().
std::vector<size_t> rocksdb::FilterBlockBuilder::start_ private
Definition at line 54 of file filter_block.h.
Referenced by AddKey(), Finish(), and GenerateFilter().
std::vector<Slice> rocksdb::FilterBlockBuilder::tmp_entries_ private
Definition at line 56 of file filter_block.h.
Referenced by GenerateFilter().
bool rocksdb::FilterBlockBuilder::whole_key_filtering_ private
Definition at line 50 of file filter_block.h.
Referenced by AddKey().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/table/filter_block.h
rippled/src/ripple/rocksdb/rocksdb/table/filter_block.cc