rippled: ripple::ParameterInt Class Reference
ripple::ParameterInt Class Reference
#include <ParameterTable.h>
Public Member Functions
ParameterInt (Parameter::ref parent, const std::string &name, int value)
virtual Json::Value getValue (int) const
virtual bool setValue (const Json::Value &value, Json::Value &error)
Public Member Functions inherited from ripple::Parameter
Parameter (Parameter::ref parent, const std::string &name)
virtual ~Parameter ()
const std::string & getName () const
Parameter::pointer getShared ()
Private Attributes
int mValue
Additional Inherited Members
Public Types inherited from ripple::Parameter
typedef boost::shared_ptr
< Parameter > pointer
typedef const
boost::shared_ptr< Parameter > & ref
Detailed Description
Definition at line 90 of file ParameterTable.h.
Constructor & Destructor Documentation
ripple::ParameterInt::ParameterInt (Parameter::ref parent, const std::string & name, int value)
Definition at line 159 of file ParameterTable.cpp.
     : Parameter (parent, name), mValue (value)
 {
     ;
 }
Member Function Documentation
Json::Value ripple::ParameterInt::getValue (int) const virtual
Implements ripple::Parameter.
Definition at line 165 of file ParameterTable.cpp.
References mValue, and rocksdb::crc32c::Value().
 {
     return Json::Value (mValue);
 }
bool ripple::ParameterInt::setValue (const Json::Value & value, Json::Value & error) virtual
Implements ripple::Parameter.
Definition at line 170 of file ParameterTable.cpp.
References Json::Value::asInt(), Json::Value::asString(), Json::intValue, Json::Value::isConvertibleTo(), mValue, Json::objectValue, Json::stringValue, and value.
 {
     if (value.isConvertibleTo (Json::intValue))
     {
         mValue = value.asInt ();
         return true;
     }
     if (value.isConvertibleTo (Json::stringValue))
     {
         try
         {
             mValue = beast::lexicalCastThrow <int> (value.asString ());
         }
         catch (...)
         {
         }
     }
     error = Json::objectValue;
     error["error"] = "Cannot convert to integer";
     error["value"] = value;
     return false;
 }
Member Data Documentation
int ripple::ParameterInt::mValue private
Definition at line 98 of file ParameterTable.h.
Referenced by getValue(), and setValue().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/main/ParameterTable.h
rippled/src/ripple_app/main/ParameterTable.cpp