rippled: beast::hash_metrics Namespace Reference
beast::hash_metrics Namespace Reference
Namespaces
detail
Functions
template<class FwdIter >
float collision_factor (FwdIter first, FwdIter last)
template<class FwdIter >
float distribution_factor (FwdIter first, FwdIter last)
template<class FwdIter >
double windowed_score (FwdIter first, FwdIter last)
Function Documentation
template<class FwdIter > float beast::hash_metrics::collision_factor (FwdIter first, FwdIter last)
Returns the fraction of duplicate items in the sequence.
Definition at line 41 of file hash_metrics.h.
Referenced by beast::hash_append_test::measure_hashes().
 {
     std::set <typename FwdIter::value_type> s (first, last);
     return 1 - static_cast <float>(s.size()) / std::distance (first, last);
 }
template<class FwdIter > float beast::hash_metrics::distribution_factor (FwdIter first, FwdIter last)
Returns the deviation of the sequence from the ideal distribution.
Definition at line 52 of file hash_metrics.h.
References value.
Referenced by beast::hash_append_test::measure_hashes().
 {
     typedef typename FwdIter::value_type value_type;
     static_assert (std::is_unsigned <value_type>::value, "");
     const unsigned nbits = CHAR_BIT * sizeof(std::size_t);
     const unsigned rows = nbits / 4;
     unsigned counts[rows][16] = {};
     std::for_each (first, last, [&](typename FwdIter::value_type h)
     {
         std::size_t mask = 0xF;
         for (unsigned i = 0; i < rows; ++i, mask <<= 4)
             counts[i][(h & mask) >> 4*i] += 1;
     });
     float mean_rows[rows] = {0};
     float mean_cols[16] = {0};
     for (unsigned i = 0; i < rows; ++i)
     {
         for (unsigned j = 0; j < 16; ++j)
         {
             mean_rows[i] += counts[i][j];
             mean_cols[j] += counts[i][j];
         }
     }
     for (unsigned i = 0; i < rows; ++i)
         mean_rows[i] /= 16;
     for (unsigned j = 0; j < 16; ++j)
         mean_cols[j] /= rows;
     std::pair<float, float> dev[rows][16];
     for (unsigned i = 0; i < rows; ++i)
     {
         for (unsigned j = 0; j < 16; ++j)
         {
             dev[i][j].first = std::abs(counts[i][j] - mean_rows[i]) / mean_rows[i];
             dev[i][j].second = std::abs(counts[i][j] - mean_cols[j]) / mean_cols[j];
         }
     }
     float max_err = 0;
     for (unsigned i = 0; i < rows; ++i)
     {
         for (unsigned j = 0; j < 16; ++j)
         {
             if (max_err < dev[i][j].first)
                 max_err = dev[i][j].first;
             if (max_err < dev[i][j].second)
                 max_err = dev[i][j].second;
         }
     }
     return max_err;
 }
template<class FwdIter > double beast::hash_metrics::windowed_score (FwdIter first, FwdIter last)
Calculated a windowed metric using bins. TODO Need reference (SMHasher?)
Definition at line 163 of file hash_metrics.h.
References beast::hash_metrics::detail::score(), and beast::hash_metrics::detail::window().
Referenced by beast::hash_append_test::measure_hashes().
 {
     auto const size (std::distance (first, last));
     int maxwidth = 20;
     // We need at least 5 keys per bin to reliably test distribution biases
     // down to 1%, so don't bother to test sparser distributions than that
     while (static_cast<double>(size) / (1 << maxwidth) < 5.0)
         maxwidth--;
     double worst = 0;
     int worstStart = -1;
     int worstWidth = -1;
     std::vector <int> bins (1 << maxwidth);
     int const hashbits = sizeof(std::size_t) * CHAR_BIT;
     for (int start = 0; start < hashbits; ++start)
     {
         int width = maxwidth;
         bins.assign (1 << width, 0);
         for (auto iter (first); iter != last; ++iter)
             ++bins[detail::window(&*iter, start, width)];
         // Test the distribution, then fold the bins in half,
         // repeat until we're down to 256 bins
         while (bins.size() >= 256)
         {
             double score (detail::score (
                 bins.data(), bins.size(), size));
             if (score > worst)
             {
                 worst = score;
                 worstStart = start;
                 worstWidth = width;
             }
             if (--width < 8)
                 break;
             for (std::size_t i = 0, j = bins.size() / 2; j < bins.size(); ++i, ++j)
                 bins[i] += bins[j];
             bins.resize(bins.size() / 2);
         }
     }
     return worst;
 }