rippled: rocksdb::Version Class Reference
rocksdb::Version Class Reference
#include <version_set.h>
Classes
struct GetStats
class LevelFileNumIterator
Public Member Functions
void AddIterators (const ReadOptions &, const EnvOptions &soptions, std::vector< Iterator * > *iters)
void Get (const ReadOptions &, const LookupKey &key, std::string *val, Status *status, std::deque< std::string > *operands, GetStats *stats, const Options &db_option, bool *value_found=nullptr)
bool UpdateStats (const GetStats &stats)
void Ref ()
void Unref ()
void GetOverlappingInputs (int level, const InternalKey *begin, const InternalKey *end, std::vector< FileMetaData * > *inputs, int hint_index=-1, int *file_index=nullptr)
void GetOverlappingInputsBinarySearch (int level, const Slice &begin, const Slice &end, std::vector< FileMetaData * > *inputs, int hint_index, int *file_index)
void ExtendOverlappingInputs (int level, const Slice &begin, const Slice &end, std::vector< FileMetaData * > *inputs, unsigned int index)
bool OverlapInLevel (int level, const Slice *smallest_user_key, const Slice *largest_user_key)
bool HasOverlappingUserKey (const std::vector< FileMetaData * > *inputs, int level)
int PickLevelForMemTableOutput (const Slice &smallest_user_key, const Slice &largest_user_key)
int NumFiles (int level) const
std::string DebugString (bool hex=false) const
uint64_t GetVersionNumber ()
Private Member Functions
Iterator * NewConcatenatingIterator (const ReadOptions &, const EnvOptions &soptions, int level) const
bool PrefixMayMatch (const ReadOptions &options, const EnvOptions &soptions, const Slice &internal_prefix, Iterator *level_iter) const
Version (VersionSet *vset, uint64_t version_number=0)
~Version ()
void ResetNextCompactionIndex (int level)
Version (const Version &)
void operator= (const Version &)
Private Attributes
VersionSet * vset_
Version * next_
Version * prev_
int refs_
std::vector< FileMetaData * > * files_
std::vector< std::vector< int > > files_by_size_
std::vector< int > next_file_to_compact_by_size_
FileMetaData * file_to_compact_
int file_to_compact_level_
std::vector< double > compaction_score_
std::vector< int > compaction_level_
double max_compaction_score_
int max_compaction_score_level_
uint64_t offset_manifest_file_
uint64_t version_number_
Static Private Attributes
static const int number_of_files_to_sort_ = 50
Friends
class Compaction
class VersionSet
class DBImpl
Detailed Description
Definition at line 62 of file version_set.h.
Constructor & Destructor Documentation
rocksdb::Version::Version (VersionSet * vset, uint64_t version_number = 0) explicit private
Definition at line 403 of file version_set.cc.
     : vset_(vset), next_(this), prev_(this), refs_(0),
       files_(new std::vector<FileMetaData*>[vset->NumberLevels()]),
       files_by_size_(vset->NumberLevels()),
       next_file_to_compact_by_size_(vset->NumberLevels()),
       file_to_compact_(nullptr),
       file_to_compact_level_(-1),
       compaction_score_(vset->NumberLevels()),
       compaction_level_(vset->NumberLevels()),
       offset_manifest_file_(0),
       version_number_(version_number) {
 }
rocksdb::Version::~Version () private
Definition at line 39 of file version_set.cc.
References ripple::f, files_, next_, rocksdb::VersionSet::NumberLevels(), rocksdb::VersionSet::obsolete_files_, prev_, rocksdb::FileMetaData::refs, refs_, and vset_.
                   {
   assert(refs_ == 0);
   // Remove from linked list
   prev_->next_ = next_;
   next_->prev_ = prev_;
   // Drop references to files
   for (int level = 0; level < vset_->NumberLevels(); level++) {
     for (size_t i = 0; i < files_[level].size(); i++) {
       FileMetaData* f = files_[level][i];
       assert(f->refs > 0);
       f->refs--;
       if (f->refs <= 0) {
         vset_->obsolete_files_.push_back(f);
       }
     }
   }
   delete[] files_;
 }
rocksdb::Version::Version (const Version &) private
Member Function Documentation
void rocksdb::Version::AddIterators (const ReadOptions & options, const EnvOptions & soptions, std::vector< Iterator * > * iters)
Definition at line 254 of file version_set.cc.
References files_, NewConcatenatingIterator(), rocksdb::TableCache::NewIterator(), rocksdb::VersionSet::NumberLevels(), rocksdb::VersionSet::table_cache_, and vset_.
{
   // Merge all level zero files together since they may overlap
   for (const FileMetaData* file : files_[0]) {
     iters->push_back(
         vset_->table_cache_->NewIterator(
             options, soptions, file->number, file->file_size));
   }
   // For levels > 0, we can use a concatenating iterator that sequentially
   // walks through the non-overlapping files in the level, opening them
   // lazily.
   for (int level = 1; level < vset_->NumberLevels(); level++) {
     if (!files_[level].empty()) {
       iters->push_back(NewConcatenatingIterator(options, soptions, level));
     }
   }
 }
std::string rocksdb::Version::DebugString (bool hex = false) const
Definition at line 859 of file version_set.cc.
References rocksdb::AppendNumberTo(), files_, rocksdb::VersionSet::NumberLevels(), version_number_, and vset_.
Referenced by rocksdb::VersionSet::DumpManifest().
{
   std::string r;
   for (int level = 0; level < vset_->NumberLevels(); level++) {
     // E.g.,
     //   --- level 1 ---
     //   17:123['a' .. 'd']
     //   20:43['e' .. 'g']
     r.append("--- level ");
     AppendNumberTo(&r, level);
     r.append(" --- version# ");
     AppendNumberTo(&r, version_number_);
     r.append(" ---\n");
     const std::vector<FileMetaData*>& files = files_[level];
     for (size_t i = 0; i < files.size(); i++) {
       r.push_back(' ');
       AppendNumberTo(&r, files[i]->number);
       r.push_back(':');
       AppendNumberTo(&r, files[i]->file_size);
       r.append("[");
       r.append(files[i]->smallest.DebugString(hex));
       r.append(" .. ");
       r.append(files[i]->largest.DebugString(hex));
       r.append("]\n");
     }
   }
   return r;
 }
void rocksdb::Version::ExtendOverlappingInputs (int level, const Slice & begin, const Slice & end, std::vector< FileMetaData * > * inputs, unsigned int index)
Definition at line 755 of file version_set.cc.
References rocksdb::Comparator::Compare(), ripple::f, files_, rocksdb::VersionSet::icmp_, rocksdb::FileMetaData::largest, rocksdb::FileMetaData::smallest, rocksdb::InternalKeyComparator::user_comparator(), rocksdb::InternalKey::user_key(), and vset_.
Referenced by GetOverlappingInputsBinarySearch().
{
   const Comparator* user_cmp = vset_->icmp_.user_comparator();
 #ifndef NDEBUG
   {
     // assert that the file at midIndex overlaps with the range
     assert(midIndex < files_[level].size());
     FileMetaData* f = files_[level][midIndex];
     const Slice fstart = f->smallest.user_key();
     const Slice flimit = f->largest.user_key();
     if (user_cmp->Compare(fstart, user_begin) >= 0) {
       assert(user_cmp->Compare(fstart, user_end) <= 0);
     } else {
       assert(user_cmp->Compare(flimit, user_begin) >= 0);
     }
   }
 #endif
   int startIndex = midIndex + 1;
   int endIndex = midIndex;
   int count __attribute__((unused)) = 0;
   // check backwards from 'mid' to lower indices
   for (int i = midIndex; i >= 0 ; i--) {
     FileMetaData* f = files_[level][i];
     const Slice file_limit = f->largest.user_key();
     if (user_cmp->Compare(file_limit, user_begin) >= 0) {
       startIndex = i;
       assert((count++, true));
     } else {
       break;
     }
   }
   // check forward from 'mid+1' to higher indices
   for (unsigned int i = midIndex+1; i < files_[level].size(); i++) {
     FileMetaData* f = files_[level][i];
     const Slice file_start = f->smallest.user_key();
     if (user_cmp->Compare(file_start, user_end) <= 0) {
       assert((count++, true));
       endIndex = i;
     } else {
       break;
     }
   }
   assert(count == endIndex - startIndex + 1);
   // insert overlapping files into vector
   for (int i = startIndex; i <= endIndex; i++) {
     FileMetaData* f = files_[level][i];
     inputs->push_back(f);
   }
 }
void rocksdb::Version::Get (const ReadOptions & options, const LookupKey & key, std::string * val, Status * status, std::deque< std::string > * operands, GetStats * stats, const Options & db_option, bool * value_found = nullptr)
Definition at line 416 of file version_set.cc.
References rocksdb::Options::compaction_style, rocksdb::Comparator::Compare(), rocksdb::InternalKeyComparator::Compare(), rocksdb::Status::Corruption(), ripple::f, rocksdb::FileMetaData::file_size, files_, rocksdb::FindFile(), rocksdb::TableCache::Get(), rocksdb::VersionSet::icmp_, rocksdb::Options::info_log, rocksdb::LookupKey::internal_key(), rocksdb::Status::IsMergeInProgress(), rocksdb::kCompactionStyleUniversal, rocksdb::FileMetaData::largest, logger, rocksdb::MarkKeyMayExist(), rocksdb::Options::merge_operator, merge_operator, rocksdb::NewestFirst(), rocksdb::NewestFirstBySeqNo(), rocksdb::Status::NotFound(), rocksdb::FileMetaData::number, rocksdb::NUMBER_MERGE_FAILURES, rocksdb::VersionSet::NumberLevels(), rocksdb::Status::OK(), rocksdb::Status::ok(), rocksdb::VersionSet::options_, rocksdb::RecordTick(), rocksdb::SaveValue(), rocksdb::Version::GetStats::seek_file, rocksdb::Version::GetStats::seek_file_level, rocksdb::FileMetaData::smallest, rocksdb::Options::statistics, rocksdb::VersionSet::table_cache_, ucmp, rocksdb::InternalKeyComparator::user_comparator(), rocksdb::InternalKey::user_key(), rocksdb::LookupKey::user_key(), user_key, value, value_found, and vset_.
Referenced by rocksdb::DBImplReadOnly::Get(), rocksdb::DBImpl::GetImpl(), and rocksdb::DBImpl::MultiGet().
{
   Slice ikey = k.internal_key();
   Slice user_key = k.user_key();
   const Comparator* ucmp = vset_->icmp_.user_comparator();
   auto merge_operator = db_options.merge_operator.get();
   auto logger = db_options.info_log;
   assert(status->ok() || status->IsMergeInProgress());
   Saver saver;
   saver.state = status->ok()? kNotFound : kMerge;
   saver.ucmp = ucmp;
   saver.user_key = user_key;
   saver.value_found = value_found;
   saver.value = value;
   saver.merge_operator = merge_operator;
   saver.merge_operands = operands;
   saver.logger = logger.get();
   saver.didIO = false;
   saver.statistics = db_options.statistics;
   stats->seek_file = nullptr;
   stats->seek_file_level = -1;
   FileMetaData* last_file_read = nullptr;
   int last_file_read_level = -1;
   // We can search level-by-level since entries never hop across
   // levels.  Therefore we are guaranteed that if we find data
   // in an smaller level, later levels are irrelevant (unless we
   // are MergeInProgress).
   std::vector<FileMetaData*> important_files;
   for (int level = 0; level < vset_->NumberLevels(); level++) {
     size_t num_files = files_[level].size();
     if (num_files == 0) continue;
     // Get the list of files to search in this level
     FileMetaData* const* files = &files_[level][0];
     important_files.clear();
     important_files.reserve(num_files);
     // Some files may overlap each other. We find
     // all files that overlap user_key and process them in order from
     // newest to oldest. In the context of merge-operator,
     // this can occur at any level. Otherwise, it only occurs
     // at Level-0 (since Put/Deletes are always compacted into a single entry).
     uint32_t start_index;
     if (level == 0) {
       // On Level-0, we read through all files to check for overlap.
       start_index = 0;
     } else {
       // On Level-n (n>=1), files are sorted.
       // Binary search to find earliest index whose largest key >= ikey.
       // We will also stop when the file no longer overlaps ikey
       start_index = FindFile(vset_->icmp_, files_[level], ikey);
     }
     // Traverse the list, finding all overlapping files.
     for (uint32_t i = start_index; i < num_files; i++) {
       FileMetaData* f = files[i];
       if (ucmp->Compare(user_key, f->smallest.user_key()) >= 0 &&
           ucmp->Compare(user_key, f->largest.user_key()) <= 0) {
         important_files.push_back(f);
       } else if (level > 0) {
         // If on Level-n (n>=1) then the files are sorted.
         // So we can stop looking when we are past the ikey.
         break;
       }
     }
     if (important_files.empty()) continue;
     if (level == 0) {
       if (vset_->options_->compaction_style == kCompactionStyleUniversal) {
         std::sort(important_files.begin(), important_files.end(), NewestFirstBySeqNo);
       } else {
         std::sort(important_files.begin(), important_files.end(), NewestFirst);
       }
     } else {
       // Sanity check to make sure that the files are correctly sorted
 #ifndef NDEBUG
       num_files = important_files.size();
       for (uint32_t i = 1; i < num_files; ++i) {
         FileMetaData* a = important_files[i-1];
         FileMetaData* b = important_files[i];
         int comp_sign = vset_->icmp_.Compare(a->largest, b->smallest);
         assert(comp_sign < 0);
       }
 #endif
     }
     // Traverse each relevant file to find the desired key
     num_files = important_files.size();
     for (uint32_t i = 0; i < num_files; ++i) {
       FileMetaData* f = important_files[i];
       bool tableIO = false;
       *status = vset_->table_cache_->Get(options, f->number, f->file_size,
                                          ikey, &saver, SaveValue, &tableIO,
                                          MarkKeyMayExist);
       // TODO: examine the behavior for corrupted key
       if (!status->ok()) {
         return;
       }
       if (last_file_read != nullptr && stats->seek_file == nullptr) {
         // We have had more than one seek for this read.  Charge the 1st file.
         stats->seek_file = last_file_read;
         stats->seek_file_level = last_file_read_level;
       }
       // If we did any IO as part of the read, then we remember it because
       // it is a possible candidate for seek-based compaction. saver.didIO
       // is true if the block had to be read in from storage and was not
       // pre-exisiting in the block cache. Also, if this file was not pre-
       // existing in the table cache and had to be freshly opened that needed
       // the index blocks to be read-in, then tableIO is true. One thing
       // to note is that the index blocks are not part of the block cache.
       if (saver.didIO || tableIO) {
         last_file_read = f;
         last_file_read_level = level;
       }
       switch (saver.state) {
         case kNotFound:
           break;      // Keep searching in other files
         case kFound:
           return;
         case kDeleted:
           *status = Status::NotFound(Slice());  // Use empty error message for speed
           return;
         case kCorrupt:
           *status = Status::Corruption("corrupted key for ", user_key);
           return;
         case kMerge:
           break;
       }
     }
   }
   if (kMerge == saver.state) {
     // merge_operands are in saver and we hit the beginning of the key history
     // do a final merge of nullptr and operands;
     if (merge_operator->FullMerge(user_key, nullptr, *saver.merge_operands,
                                   value, logger.get())) {
       *status = Status::OK();
     } else {
       RecordTick(db_options.statistics, NUMBER_MERGE_FAILURES);
       *status = Status::Corruption("could not perform end-of-key merge for ",
                                    user_key);
     }
   } else {
     *status = Status::NotFound(Slice()); // Use an empty error message for speed
   }
 }
void rocksdb::Version::GetOverlappingInputs (int level, const InternalKey * begin, const InternalKey * end, std::vector< FileMetaData * > * inputs, int hint_index = -1, int * file_index = nullptr)
Definition at line 646 of file version_set.cc.
References rocksdb::Comparator::Compare(), ripple::f, files_, GetOverlappingInputsBinarySearch(), rocksdb::VersionSet::icmp_, rocksdb::FileMetaData::largest, rocksdb::FileMetaData::smallest, rocksdb::InternalKeyComparator::user_comparator(), rocksdb::InternalKey::user_key(), and vset_.
Referenced by rocksdb::VersionSet::CompactRange(), rocksdb::VersionSet::ExpandWhileOverlapping(), rocksdb::VersionSet::MaxNextLevelOverlappingBytes(), rocksdb::VersionSet::ParentRangeInCompaction(), rocksdb::VersionSet::PickCompaction(), PickLevelForMemTableOutput(), and rocksdb::VersionSet::SetupOtherInputs().
                      {
   inputs->clear();
   Slice user_begin, user_end;
   if (begin != nullptr) {
     user_begin = begin->user_key();
   }
   if (end != nullptr) {
     user_end = end->user_key();
   }
   if (file_index) {
     *file_index = -1;
   }
   const Comparator* user_cmp = vset_->icmp_.user_comparator();
   if (begin != nullptr && end != nullptr && level > 0) {
     GetOverlappingInputsBinarySearch(level, user_begin, user_end, inputs,
       hint_index, file_index);
     return;
   }
   for (size_t i = 0; i < files_[level].size(); ) {
     FileMetaData* f = files_[level][i++];
     const Slice file_start = f->smallest.user_key();
     const Slice file_limit = f->largest.user_key();
     if (begin != nullptr && user_cmp->Compare(file_limit, user_begin) < 0) {
       // "f" is completely before specified range; skip it
     } else if (end != nullptr && user_cmp->Compare(file_start, user_end) > 0) {
       // "f" is completely after specified range; skip it
     } else {
       inputs->push_back(f);
       if (level == 0) {
         // Level-0 files may overlap each other.  So check if the newly
         // added file has expanded the range.  If so, restart search.
         if (begin != nullptr && user_cmp->Compare(file_start, user_begin) < 0) {
           user_begin = file_start;
           inputs->clear();
           i = 0;
         } else if (end != nullptr
             && user_cmp->Compare(file_limit, user_end) > 0) {
           user_end = file_limit;
           inputs->clear();
           i = 0;
         }
       } else if (file_index) {
         *file_index = i-1;
       }
     }
   }
 }
void rocksdb::Version::GetOverlappingInputsBinarySearch (int level, const Slice & begin, const Slice & end, std::vector< FileMetaData * > * inputs, int hint_index, int * file_index)
Definition at line 704 of file version_set.cc.
References rocksdb::Comparator::Compare(), ExtendOverlappingInputs(), ripple::f, files_, rocksdb::VersionSet::icmp_, rocksdb::FileMetaData::largest, ripple::max(), ripple::min(), rocksdb::FileMetaData::smallest, rocksdb::InternalKeyComparator::user_comparator(), rocksdb::InternalKey::user_key(), and vset_.
Referenced by GetOverlappingInputs().
                      {
   assert(level > 0);
   int min = 0;
   int mid = 0;
   int max = files_[level].size() -1;
   bool foundOverlap = false;
   const Comparator* user_cmp = vset_->icmp_.user_comparator();
   // if the caller already knows the index of a file that has overlap,
   // then we can skip the binary search.
   if (hint_index != -1) {
     mid = hint_index;
     foundOverlap = true;
   }
   while (!foundOverlap && min <= max) {
     mid = (min + max)/2;
     FileMetaData* f = files_[level][mid];
     const Slice file_start = f->smallest.user_key();
     const Slice file_limit = f->largest.user_key();
     if (user_cmp->Compare(file_limit, user_begin) < 0) {
       min = mid + 1;
     } else if (user_cmp->Compare(user_end, file_start) < 0) {
       max = mid - 1;
     } else {
       foundOverlap = true;
       break;
     }
   }
   // If there were no overlapping files, return immediately.
   if (!foundOverlap) {
     return;
   }
   // returns the index where an overlap is found
   if (file_index) {
     *file_index = mid;
   }
   ExtendOverlappingInputs(level, user_begin, user_end, inputs, mid);
 }
uint64_t rocksdb::Version::GetVersionNumber () inline
Definition at line 143 of file version_set.h.
References version_number_.
Referenced by rocksdb::VersionSet::LogAndApply(), and rocksdb::Compaction::Summary().
{
     return version_number_;
   }
bool rocksdb::Version::HasOverlappingUserKey (const std::vector< FileMetaData * > * inputs, int level)
Definition at line 816 of file version_set.cc.
References rocksdb::Comparator::Compare(), files_, rocksdb::FindFile(), rocksdb::VersionSet::icmp_, rocksdb::InternalKeyComparator::user_comparator(), and vset_.
Referenced by rocksdb::VersionSet::SetupOtherInputs().
                {
   // If inputs empty, there is no overlap.
   // If level == 0, it is assumed that all needed files were already included.
   if (inputs->empty() || level == 0){
     return false;
   }
   const Comparator* user_cmp = vset_->icmp_.user_comparator();
   const std::vector<FileMetaData*>& files = files_[level];
   const size_t kNumFiles = files.size();
   // Check the last file in inputs against the file after it
   size_t last_file = FindFile(vset_->icmp_, files,
                               inputs->back()->largest.Encode());
   assert(0 <= last_file && last_file < kNumFiles);  // File should exist!
   if (last_file < kNumFiles-1) {                    // If not the last file
     const Slice last_key_in_input = files[last_file]->largest.user_key();
     const Slice first_key_after = files[last_file+1]->smallest.user_key();
     if (user_cmp->Compare(last_key_in_input, first_key_after) == 0) {
       // The last user key in input overlaps with the next file's first key
       return true;
     }
   }
   // Check the first file in inputs against the file just before it
   size_t first_file = FindFile(vset_->icmp_, files,
                                inputs->front()->smallest.Encode());
   assert(0 <= first_file && first_file <= last_file);   // File should exist!
   if (first_file > 0) {                                 // If not first file
     const Slice& first_key_in_input = files[first_file]->smallest.user_key();
     const Slice& last_key_before = files[first_file-1]->largest.user_key();
     if (user_cmp->Compare(first_key_in_input, last_key_before) == 0) {
       // The first user key in input overlaps with the previous file's last key
       return true;
     }
   }
   return false;
 }
Iterator * rocksdb::Version::NewConcatenatingIterator (const ReadOptions & options, const EnvOptions & soptions, int level) const private
Definition at line 237 of file version_set.cc.
References rocksdb::InternalKey::Encode(), files_, rocksdb::GetFileIterator(), rocksdb::VersionSet::icmp_, rocksdb::kTypeValue, rocksdb::NewEmptyIterator(), rocksdb::NewTwoLevelIterator(), rocksdb::ReadOptions::prefix, PrefixMayMatch(), rocksdb::VersionSet::table_cache_, and vset_.
Referenced by AddIterators().
{
   Iterator* level_iter = new LevelFileNumIterator(vset_->icmp_, &files_[level]);
   if (options.prefix) {
     InternalKey internal_prefix(*options.prefix, 0, kTypeValue);
     if (!PrefixMayMatch(options, soptions,
                         internal_prefix.Encode(), level_iter)) {
       delete level_iter;
       // nothing in this level can match the prefix
       return NewEmptyIterator();
     }
   }
   return NewTwoLevelIterator(level_iter, &GetFileIterator,
                              vset_->table_cache_, options, soptions);
 }
int rocksdb::Version::NumFiles (int level) const inline
Definition at line 137 of file version_set.h.
References files_.
 { return files_[level].size(); }
void rocksdb::Version::operator= (const Version &) private
bool rocksdb::Version::OverlapInLevel (int level, const Slice * smallest_user_key, const Slice * largest_user_key)
Definition at line 604 of file version_set.cc.
References files_, rocksdb::VersionSet::icmp_, rocksdb::SomeFileOverlapsRange(), and vset_.
Referenced by rocksdb::DBImpl::CompactRange(), and PickLevelForMemTableOutput().
{
   return SomeFileOverlapsRange(vset_->icmp_, (level > 0), files_[level],
                                smallest_user_key, largest_user_key);
 }
int rocksdb::Version::PickLevelForMemTableOutput (const Slice & smallest_user_key, const Slice & largest_user_key)
Definition at line 611 of file version_set.cc.
References GetOverlappingInputs(), rocksdb::kMaxSequenceNumber, rocksdb::kValueTypeForSeek, rocksdb::Options::max_mem_compaction_level, rocksdb::VersionSet::MaxGrandParentOverlapBytes(), rocksdb::VersionSet::NumberLevels(), rocksdb::VersionSet::options_, OverlapInLevel(), rocksdb::TotalFileSize(), and vset_.
Referenced by rocksdb::DBImpl::WriteLevel0Table().
{
   int level = 0;
   if (!OverlapInLevel(0, &smallest_user_key, &largest_user_key)) {
     // Push to next level if there is no overlap in next level,
     // and the #bytes overlapping in the level after that are limited.
     InternalKey start(smallest_user_key, kMaxSequenceNumber, kValueTypeForSeek);
     InternalKey limit(largest_user_key, 0, static_cast<ValueType>(0));
     std::vector<FileMetaData*> overlaps;
     int max_mem_compact_level = vset_->options_->max_mem_compaction_level;
     while (max_mem_compact_level > 0 && level < max_mem_compact_level) {
       if (OverlapInLevel(level + 1, &smallest_user_key, &largest_user_key)) {
         break;
       }
       if (level + 2 >= vset_->NumberLevels()) {
         level++;
         break;
       }
       GetOverlappingInputs(level + 2, &start, &limit, &overlaps);
       const uint64_t sum = TotalFileSize(overlaps);
       if (sum > vset_->MaxGrandParentOverlapBytes(level)) {
         break;
       }
       level++;
     }
   }
   return level;
 }
bool rocksdb::Version::PrefixMayMatch (const ReadOptions & options, const EnvOptions & soptions, const Slice & internal_prefix, Iterator * level_iter) const private
Definition at line 213 of file version_set.cc.
References rocksdb::Slice::data(), rocksdb::DecodeFixed64(), rocksdb::ExtractUserKey(), rocksdb::Iterator::key(), rocksdb::TableCache::PrefixMayMatch(), rocksdb::Iterator::Seek(), rocksdb::VersionSet::table_cache_, rocksdb::Iterator::Valid(), rocksdb::Iterator::value(), and vset_.
Referenced by NewConcatenatingIterator().
{
   bool may_match = true;
   level_iter->Seek(internal_prefix);
   if (!level_iter->Valid()) {
     // we're past end of level
     may_match = false;
   } else if (ExtractUserKey(level_iter->key()).starts_with(
                                              ExtractUserKey(internal_prefix))) {
     // TODO(tylerharter): do we need this case?  Or are we guaranteed
     // key() will always be the biggest value for this SST?
     may_match = true;
   } else {
     may_match = vset_->table_cache_->PrefixMayMatch(
                            options,
                            DecodeFixed64(level_iter->value().data()),
                            DecodeFixed64(level_iter->value().data() + 8),
                            internal_prefix, nullptr);
   }
   return may_match;
 }
void rocksdb::Version::Ref ()
Definition at line 591 of file version_set.cc.
References refs_.
Referenced by rocksdb::VersionSet::AppendVersion(), rocksdb::VersionSet::Builder::Builder(), rocksdb::VersionSet::CompactRange(), rocksdb::DBImpl::GetImpl(), rocksdb::DBImpl::MultiGet(), rocksdb::VersionSet::PickCompaction(), rocksdb::VersionSet::PickCompactionUniversal(), and rocksdb::DBImpl::WriteLevel0Table().
                   {
   ++refs_;
 }
void rocksdb::Version::ResetNextCompactionIndex (int level) inline private
Definition at line 212 of file version_set.h.
References next_file_to_compact_by_size_.
Referenced by rocksdb::Compaction::ResetNextCompactionIndex().
{
     next_file_to_compact_by_size_[level] = 0;
   }
void rocksdb::Version::Unref ()
Definition at line 595 of file version_set.cc.
References rocksdb::VersionSet::dummy_versions_, refs_, and vset_.
Referenced by rocksdb::VersionSet::AppendVersion(), rocksdb::DBImpl::GetApproximateSizes(), rocksdb::DBImpl::GetImpl(), rocksdb::DBImpl::MultiGet(), rocksdb::Compaction::ReleaseInputs(), rocksdb::DBImpl::WriteLevel0Table(), rocksdb::VersionSet::Builder::~Builder(), rocksdb::Compaction::~Compaction(), and rocksdb::VersionSet::~VersionSet().
                     {
   assert(this != &vset_->dummy_versions_);
   assert(refs_ >= 1);
   --refs_;
   if (refs_ == 0) {
     delete this;
   }
 }
bool rocksdb::Version::UpdateStats (const GetStats & stats)
Definition at line 578 of file version_set.cc.
References rocksdb::FileMetaData::allowed_seeks, ripple::f, file_to_compact_, file_to_compact_level_, rocksdb::Version::GetStats::seek_file, and rocksdb::Version::GetStats::seek_file_level.
Referenced by rocksdb::DBImpl::GetImpl(), and rocksdb::DBImpl::MultiGet().
{
   FileMetaData* f = stats.seek_file;
   if (f != nullptr) {
     f->allowed_seeks--;
     if (f->allowed_seeks <= 0 && file_to_compact_ == nullptr) {
       file_to_compact_ = f;
       file_to_compact_level_ = stats.seek_file_level;
       return true;
     }
   }
   return false;
 }
Friends And Related Function Documentation
friend class Compaction friend
Definition at line 148 of file version_set.h.
friend class DBImpl friend
Definition at line 150 of file version_set.h.
friend class VersionSet friend
Definition at line 149 of file version_set.h.
Member Data Documentation
std::vector<int> rocksdb::Version::compaction_level_ private
Definition at line 195 of file version_set.h.
Referenced by rocksdb::VersionSet::Finalize(), and rocksdb::VersionSet::PickCompaction().
std::vector<double> rocksdb::Version::compaction_score_ private
Definition at line 194 of file version_set.h.
Referenced by rocksdb::VersionSet::Finalize(), rocksdb::VersionSet::NeedsSizeCompaction(), and rocksdb::VersionSet::PickCompaction().
FileMetaData* rocksdb::Version::file_to_compact_ private
Definition at line 186 of file version_set.h.
Referenced by rocksdb::VersionSet::NeedsCompaction(), rocksdb::VersionSet::PickCompaction(), and UpdateStats().
int rocksdb::Version::file_to_compact_level_ private
Definition at line 187 of file version_set.h.
Referenced by rocksdb::VersionSet::PickCompaction(), and UpdateStats().
std::vector<FileMetaData*>* rocksdb::Version::files_ private
Definition at line 166 of file version_set.h.
Referenced by AddIterators(), rocksdb::VersionSet::AddLiveFilesCurrentVersion(), rocksdb::VersionSet::ApproximateOffsetOf(), rocksdb::VersionSet::Builder::CheckConsistency(), rocksdb::VersionSet::Builder::CheckConsistencyForDeletes(), DebugString(), ExtendOverlappingInputs(), rocksdb::VersionSet::Finalize(), Get(), rocksdb::VersionSet::GetLiveFilesMetaData(), rocksdb::VersionSet::GetMetadataForFile(), GetOverlappingInputs(), GetOverlappingInputsBinarySearch(), HasOverlappingUserKey(), rocksdb::Compaction::IsBaseLevelForKey(), rocksdb::VersionSet::LevelFileSummary(), rocksdb::VersionSet::LevelSummary(), rocksdb::VersionSet::MaxNextLevelOverlappingBytes(), rocksdb::VersionSet::Builder::MaybeAddFile(), NewConcatenatingIterator(), NumFiles(), rocksdb::VersionSet::NumLevelBytes(), rocksdb::VersionSet::NumLevelFiles(), OverlapInLevel(), rocksdb::VersionSet::PickCompactionBySize(), rocksdb::VersionSet::PickCompactionUniversal(), rocksdb::VersionSet::PickCompactionUniversalReadAmp(), rocksdb::VersionSet::PickCompactionUniversalSizeAmp(), rocksdb::VersionSet::ReduceNumberOfLevels(), rocksdb::VersionSet::Builder::SaveTo(), rocksdb::VersionSet::UpdateFilesBySize(), rocksdb::VersionSet::VerifyCompactionFileConsistency(), rocksdb::VersionSet::WriteSnapshot(), and ~Version().
std::vector< std::vector<int> > rocksdb::Version::files_by_size_ private
Definition at line 172 of file version_set.h.
Referenced by rocksdb::VersionSet::PickCompactionBySize(), rocksdb::VersionSet::PickCompactionUniversal(), rocksdb::VersionSet::PickCompactionUniversalReadAmp(), rocksdb::VersionSet::PickCompactionUniversalSizeAmp(), and rocksdb::VersionSet::UpdateFilesBySize().
double rocksdb::Version::max_compaction_score_ private
Definition at line 196 of file version_set.h.
Referenced by rocksdb::VersionSet::Finalize(), and rocksdb::VersionSet::MaxCompactionScore().
int rocksdb::Version::max_compaction_score_level_ private
Definition at line 197 of file version_set.h.
Referenced by rocksdb::VersionSet::Finalize(), and rocksdb::VersionSet::MaxCompactionScoreLevel().
Version* rocksdb::Version::next_ private
Definition at line 160 of file version_set.h.
Referenced by rocksdb::VersionSet::AddLiveFiles(), rocksdb::VersionSet::AppendVersion(), ~Version(), and rocksdb::VersionSet::~VersionSet().
std::vector<int> rocksdb::Version::next_file_to_compact_by_size_ private
Definition at line 176 of file version_set.h.
Referenced by rocksdb::VersionSet::PickCompactionBySize(), ResetNextCompactionIndex(), and rocksdb::VersionSet::UpdateFilesBySize().
const int rocksdb::Version::number_of_files_to_sort_ = 50 static private
Definition at line 183 of file version_set.h.
Referenced by rocksdb::VersionSet::PickCompactionBySize(), and rocksdb::VersionSet::UpdateFilesBySize().
uint64_t rocksdb::Version::offset_manifest_file_ private
Definition at line 200 of file version_set.h.
Referenced by rocksdb::VersionSet::LogAndApply(), rocksdb::VersionSet::ManifestFileSize(), and rocksdb::VersionSet::Recover().
Version* rocksdb::Version::prev_ private
Definition at line 161 of file version_set.h.
Referenced by rocksdb::VersionSet::AppendVersion(), and ~Version().
int rocksdb::Version::refs_ private
Definition at line 162 of file version_set.h.
Referenced by rocksdb::VersionSet::AppendVersion(), Ref(), Unref(), and ~Version().
uint64_t rocksdb::Version::version_number_ private
Definition at line 204 of file version_set.h.
Referenced by DebugString(), and GetVersionNumber().
VersionSet* rocksdb::Version::vset_ private
Definition at line 159 of file version_set.h.
Referenced by AddIterators(), DebugString(), ExtendOverlappingInputs(), Get(), GetOverlappingInputs(), GetOverlappingInputsBinarySearch(), HasOverlappingUserKey(), rocksdb::Compaction::IsBaseLevelForKey(), NewConcatenatingIterator(), OverlapInLevel(), rocksdb::VersionSet::PickCompaction(), PickLevelForMemTableOutput(), PrefixMayMatch(), rocksdb::Compaction::SetupBottomMostLevel(), rocksdb::Compaction::ShouldStopBefore(), Unref(), and ~Version().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/db/version_set.h
rippled/src/ripple/rocksdb/rocksdb/db/version_set.cc