rippled: ripple::NetworkOPs Class Reference
ripple::NetworkOPs Class Reference abstract
#include <NetworkOPs.h>
Public Types
enum Fault { IO_ERROR = 1, NO_NETWORK = 2 }
enum OperatingMode {
omDISCONNECTED = 0, omCONNECTED = 1, omSYNCING = 2, omTRACKING = 3,
omFULL = 4
}
typedef beast::abstract_clock
< std::chrono::seconds > clock_type
typedef ripple::unordered_map
< std::uint64_t, InfoSub::wptr > SubMapType
typedef std::function< void(Transaction::pointer,
TER)> stCallback
typedef ripple::unordered_map
< uint160, std::list
< LedgerProposal::pointer > > Proposals
typedef std::vector< std::pair
< Transaction::pointer,
TransactionMetaSet::pointer > > AccountTxs
typedef std::vector< std::pair
< Transaction::pointer,
TransactionMetaSet::pointer > > TxsAccount
typedef std::tuple
< std::string, std::string,
std::uint32_t > txnMetaLedgerType
typedef std::vector
< txnMetaLedgerType > MetaTxsList
Public Member Functions
virtual ~NetworkOPs ()=0
virtual std::uint32_t getNetworkTimeNC ()=0
virtual std::uint32_t getCloseTimeNC ()=0
virtual std::uint32_t getValidationTimeNC ()=0
virtual void closeTimeOffset (int)=0
virtual boost::posix_time::ptime getNetworkTimePT ()=0
virtual std::uint32_t getLedgerID (uint256 const &hash)=0
virtual std::uint32_t getCurrentLedgerID ()=0
virtual OperatingMode getOperatingMode ()=0
virtual std::string strOperatingMode ()=0
virtual Ledger::pointer getClosedLedger ()=0
virtual Ledger::pointer getValidatedLedger ()=0
virtual Ledger::pointer getPublishedLedger ()=0
virtual Ledger::pointer getCurrentLedger ()=0
virtual Ledger::pointer getLedgerByHash (uint256 const &hash)=0
virtual Ledger::pointer getLedgerBySeq (const std::uint32_t seq)=0
virtual void missingNodeInLedger (const std::uint32_t seq)=0
virtual uint256 getClosedLedgerHash ()=0
virtual bool haveLedgerRange (std::uint32_t from, std::uint32_t to)=0
virtual bool haveLedger (std::uint32_t seq)=0
virtual std::uint32_t getValidatedSeq ()=0
virtual bool isValidated (std::uint32_t seq)=0
virtual bool isValidated (std::uint32_t seq, uint256 const &hash)=0
virtual bool isValidated (Ledger::ref l)=0
virtual bool getValidatedRange (std::uint32_t &minVal, std::uint32_t &maxVal)=0
virtual bool getFullValidatedRange (std::uint32_t &minVal, std::uint32_t &maxVal)=0
virtual SerializedValidation::ref getLastValidation ()=0
virtual void setLastValidation (SerializedValidation::ref v)=0
virtual SLE::pointer getSLE (Ledger::pointer lpLedger, uint256 const &uHash)=0
virtual SLE::pointer getSLEi (Ledger::pointer lpLedger, uint256 const &uHash)=0
virtual void submitTransaction (Job &, SerializedTransaction::pointer, stCallback callback=stCallback())=0
virtual Transaction::pointer submitTransactionSync (Transaction::ref tpTrans, bool bAdmin, bool bLocal, bool bFailHard, bool bSubmit)=0
virtual void runTransactionQueue ()=0
virtual Transaction::pointer processTransactionCb (Transaction::pointer, bool bAdmin, bool bLocal, bool bFailHard, stCallback)=0
virtual Transaction::pointer processTransaction (Transaction::pointer transaction, bool bAdmin, bool bLocal, bool bFailHard)=0
virtual Transaction::pointer findTransactionByID (uint256 const &transactionID)=0
virtual int findTransactionsByDestination (std::list< Transaction::pointer > &, const RippleAddress &destinationAccount, std::uint32_t startLedgerSeq, std::uint32_t endLedgerSeq, int maxTransactions)=0
virtual AccountState::pointer getAccountState (Ledger::ref lrLedger, const RippleAddress &accountID)=0
virtual SLE::pointer getGenerator (Ledger::ref lrLedger, uint160 const &uGeneratorID)=0
virtual STVector256 getDirNodeInfo (Ledger::ref lrLedger, uint256 const &uRootIndex, std::uint64_t &uNodePrevious, std::uint64_t &uNodeNext)=0
virtual Json::Value getOwnerInfo (Ledger::pointer lpLedger, const RippleAddress &naAccount)=0
virtual void getBookPage (Ledger::pointer lpLedger, const uint160 &uTakerPaysCurrencyID, const uint160 &uTakerPaysIssuerID, const uint160 &uTakerGetsCurrencyID, const uint160 &uTakerGetsIssuerID, const uint160 &uTakerID, const bool bProof, const unsigned int iLimit, const Json::Value &jvMarker, Json::Value &jvResult)=0
virtual void processTrustedProposal (LedgerProposal::pointer proposal, boost::shared_ptr< protocol::TMProposeSet > set, RippleAddress nodePublic, uint256 checkLedger, bool sigGood)=0
virtual SHAMapAddNode gotTXData (const boost::shared_ptr< Peer > &peer, uint256 const &hash, const std::list< SHAMapNode > &nodeIDs, const std::list< Blob > &nodeData)=0
virtual bool recvValidation (SerializedValidation::ref val, const std::string &source)=0
virtual void takePosition (int seq, SHAMap::ref position)=0
virtual SHAMap::pointer getTXMap (uint256 const &hash)=0
virtual bool hasTXSet (const boost::shared_ptr< Peer > &peer, uint256 const &set, protocol::TxSetStatus status)=0
virtual void mapComplete (uint256 const &hash, SHAMap::ref map)=0
virtual bool stillNeedTXSet (uint256 const &hash)=0
virtual void makeFetchPack (Job &, boost::weak_ptr< Peer > peer, boost::shared_ptr< protocol::TMGetObjectByHash > request, Ledger::pointer wantLedger, Ledger::pointer haveLedger, std::uint32_t uUptime)=0
virtual bool shouldFetchPack (std::uint32_t seq)=0
virtual void gotFetchPack (bool progress, std::uint32_t seq)=0
virtual void addFetchPack (uint256 const &hash, boost::shared_ptr< Blob > &data)=0
virtual bool getFetchPack (uint256 const &hash, Blob &data)=0
virtual int getFetchSize ()=0
virtual void sweepFetchPack ()=0
virtual void endConsensus (bool correctLCL)=0
virtual void setStandAlone ()=0
virtual void setStateTimer ()=0
virtual void newLCL (int proposers, int convergeTime, uint256 const &ledgerHash)=0
virtual void needNetworkLedger ()=0
virtual void clearNeedNetworkLedger ()=0
virtual bool isNeedNetworkLedger ()=0
virtual bool isFull ()=0
virtual void setProposing (bool isProposing, bool isValidating)=0
virtual bool isProposing ()=0
virtual bool isValidating ()=0
virtual bool isFeatureBlocked ()=0
virtual void setFeatureBlocked ()=0
virtual void consensusViewChange ()=0
virtual int getPreviousProposers ()=0
virtual int getPreviousConvergeTime ()=0
virtual std::uint32_t getLastCloseTime ()=0
virtual void setLastCloseTime (std::uint32_t t)=0
virtual Json::Value getConsensusInfo ()=0
virtual Json::Value getServerInfo (bool human, bool admin)=0
virtual void clearLedgerFetch ()=0
virtual Json::Value getLedgerFetchInfo ()=0
virtual std::uint32_t acceptLedger ()=0
virtual Proposals & peekStoredProposals ()=0
virtual void storeProposal (LedgerProposal::ref proposal, const RippleAddress &peerPublic)=0
virtual uint256 getConsensusLCL ()=0
virtual void reportFeeChange ()=0
virtual void updateLocalTx (Ledger::ref newValidLedger)=0
virtual void addLocalTx (Ledger::ref openLedger, SerializedTransaction::ref txn)=0
virtual std::size_t getLocalTxCount ()=0
virtual std::string transactionsSQL (std::string selection, const RippleAddress &account, std::int32_t minLedger, std::int32_t maxLedger, bool descending, std::uint32_t offset, int limit, bool binary, bool count, bool bAdmin)=0
virtual AccountTxs getAccountTxs (const RippleAddress &account, std::int32_t minLedger, std::int32_t maxLedger, bool descending, std::uint32_t offset, int limit, bool bAdmin)=0
virtual TxsAccount getTxsAccount (const RippleAddress &account, std::int32_t minLedger, std::int32_t maxLedger, bool forward, Json::Value &token, int limit, bool bAdmin)=0
virtual MetaTxsList getAccountTxsB (const RippleAddress &account, std::int32_t minLedger, std::int32_t maxLedger, bool descending, std::uint32_t offset, int limit, bool bAdmin)=0
virtual MetaTxsList getTxsAccountB (const RippleAddress &account, std::int32_t minLedger, std::int32_t maxLedger, bool forward, Json::Value &token, int limit, bool bAdmin)=0
virtual std::vector
< RippleAddress > getLedgerAffectedAccounts (std::uint32_t ledgerSeq)=0
virtual void pubLedger (Ledger::ref lpAccepted)=0
virtual void pubProposedTransaction (Ledger::ref lpCurrent, SerializedTransaction::ref stTxn, TER terResult)=0
Public Member Functions inherited from ripple::InfoSub::Source
virtual void subAccount (ref ispListener, const boost::unordered_set< RippleAddress > &vnaAccountIDs, std::uint32_t uLedgerIndex, bool rt)=0
virtual void unsubAccount (std::uint64_t uListener, const boost::unordered_set< RippleAddress > &vnaAccountIDs, bool rt)=0
virtual bool subLedger (ref ispListener, Json::Value &jvResult)=0
virtual bool unsubLedger (std::uint64_t uListener)=0
virtual bool subServer (ref ispListener, Json::Value &jvResult)=0
virtual bool unsubServer (std::uint64_t uListener)=0
virtual bool subBook (ref ispListener, RippleCurrency const &currencyPays, RippleCurrency const &currencyGets, RippleIssuer const &issuerPays, RippleIssuer const &issuerGets)=0
virtual bool unsubBook (std::uint64_t uListener, RippleCurrency const &currencyPays, RippleCurrency const &currencyGets, RippleIssuer const &issuerPays, RippleIssuer const &issuerGets)=0
virtual bool subTransactions (ref ispListener)=0
virtual bool unsubTransactions (std::uint64_t uListener)=0
virtual bool subRTTransactions (ref ispListener)=0
virtual bool unsubRTTransactions (std::uint64_t uListener)=0
virtual pointer findRpcSub (const std::string &strUrl)=0
virtual pointer addRpcSub (const std::string &strUrl, ref rspEntry)=0
Public Member Functions inherited from beast::Stoppable
Stoppable (char const *name, Stoppable &parent)
virtual ~Stoppable ()
bool isStopping () const
bool isStopped () const
bool areChildrenStopped () const
void stopped ()
virtual void onPrepare ()
virtual void onStart ()
virtual void onStop ()
virtual void onChildrenStopped ()
Static Public Member Functions
static NetworkOPs * New (clock_type &clock, LedgerMaster &ledgerMaster, Stoppable &parent, beast::Journal journal)
Protected Member Functions
NetworkOPs (Stoppable &parent)
Protected Member Functions inherited from ripple::InfoSub::Source
Source (char const *name, beast::Stoppable &parent)
Protected Member Functions inherited from beast::Stoppable
Stoppable (char const *name, RootStoppable &root)
Additional Inherited Members
Protected Attributes inherited from beast::Stoppable
char const * m_name
RootStoppable & m_root
Child m_child
Atomic< int > m_started
bool volatile m_stopped
bool volatile m_childrenStopped
Children m_children
WaitableEvent m_stoppedEvent
Detailed Description
Provides server functionality for clients.
Clients include backend applications, local commands, and connected clients. This class acts as a proxy, fulfilling the command with local data if possible, or asking the network and returning the results if needed.
A backend application or local client can trust a local instance of rippled / NetworkOPs. However, client software connecting to non-local instances of rippled will need to be hardened to protect against hostile or unreliable servers.
Definition at line 56 of file NetworkOPs.h.
Member Typedef Documentation
typedef std::vector< std::pair<Transaction::pointer, TransactionMetaSet::pointer> > ripple::NetworkOPs::AccountTxs
Definition at line 289 of file NetworkOPs.h.
typedef beast::abstract_clock<std::chrono::seconds> ripple::NetworkOPs::clock_type
Definition at line 63 of file NetworkOPs.h.
typedef std::vector<txnMetaLedgerType> ripple::NetworkOPs::MetaTxsList
Definition at line 300 of file NetworkOPs.h.
typedef ripple::unordered_map<uint160, std::list<LedgerProposal::pointer> > ripple::NetworkOPs::Proposals
Definition at line 268 of file NetworkOPs.h.
typedef std::function<void (Transaction::pointer, TER)> ripple::NetworkOPs::stCallback
Definition at line 144 of file NetworkOPs.h.
typedef ripple::unordered_map<std::uint64_t, InfoSub::wptr> ripple::NetworkOPs::SubMapType
Definition at line 84 of file NetworkOPs.h.
typedef std::tuple<std::string, std::string, std::uint32_t> ripple::NetworkOPs::txnMetaLedgerType
Definition at line 299 of file NetworkOPs.h.
typedef std::vector< std::pair<Transaction::pointer, TransactionMetaSet::pointer> > ripple::NetworkOPs::TxsAccount
Definition at line 294 of file NetworkOPs.h.
Member Enumeration Documentation
enum ripple::NetworkOPs::Fault
Enumerator
IO_ERROR
NO_NETWORK
Definition at line 65 of file NetworkOPs.h.
     {
         // exceptions these functions can throw
         IO_ERROR    = 1,
         NO_NETWORK  = 2,
     };
enum ripple::NetworkOPs::OperatingMode
Enumerator
omDISCONNECTED
omCONNECTED
omSYNCING
omTRACKING
omFULL
Definition at line 72 of file NetworkOPs.h.
     {
         // how we process transactions or account balance requests
         omDISCONNECTED  = 0,    // not ready to process requests
         omCONNECTED     = 1,    // convinced we are talking to the network
         omSYNCING       = 2,    // fallen slightly behind
         omTRACKING      = 3,    // convinced we agree with the network
         omFULL          = 4     // we have the ledger and can even validate
     };
Constructor & Destructor Documentation
ripple::NetworkOPs::NetworkOPs (Stoppable & parent) explicit protected
Definition at line 3328 of file NetworkOPs.cpp.
     : InfoSub::Source ("NetworkOPs", parent)
 {
 }
ripple::NetworkOPs::~NetworkOPs () pure virtual
Definition at line 3333 of file NetworkOPs.cpp.
 {
 }
Member Function Documentation
virtual std::uint32_t ripple::NetworkOPs::acceptLedger () pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doLedgerAccept().
virtual void ripple::NetworkOPs::addFetchPack (uint256 const & hash, boost::shared_ptr< Blob > & data) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::InboundLedgersImp::gotStaleData(), and ripple::PeerImp::recvGetObjectByHash().
virtual void ripple::NetworkOPs::addLocalTx (Ledger::ref openLedger, SerializedTransaction::ref txn) pure virtual
Implemented in ripple::NetworkOPsImp.
virtual void ripple::NetworkOPs::clearLedgerFetch () pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doFetchInfo().
virtual void ripple::NetworkOPs::clearNeedNetworkLedger () pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::LedgerMasterImp::doAdvance().
virtual void ripple::NetworkOPs::closeTimeOffset (int) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::LedgerConsensusImp::accept().
virtual void ripple::NetworkOPs::consensusViewChange () pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::LedgerConsensusImp::checkLCL().
virtual void ripple::NetworkOPs::endConsensus (bool correctLCL) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::LedgerConsensusImp::endConsensus().
virtual Transaction::pointer ripple::NetworkOPs::findTransactionByID (uint256 const & transactionID) pure virtual
Implemented in ripple::NetworkOPsImp.
virtual int ripple::NetworkOPs::findTransactionsByDestination (std::list< Transaction::pointer > & , const RippleAddress & destinationAccount, std::uint32_t startLedgerSeq, std::uint32_t endLedgerSeq, int maxTransactions) pure virtual
Implemented in ripple::NetworkOPsImp.
virtual AccountState::pointer ripple::NetworkOPs::getAccountState (Ledger::ref lrLedger, const RippleAddress & accountID) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPC::accounts(), ripple::RPC::authorize(), ripple::RPCHandler::doAccountInfo(), ripple::PathRequest::isValid(), and ripple::RPC::transactionSign().
virtual AccountTxs ripple::NetworkOPs::getAccountTxs (const RippleAddress & account, std::int32_t minLedger, std::int32_t maxLedger, bool descending, std::uint32_t offset, int limit, bool bAdmin) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doAccountTxOld().
virtual MetaTxsList ripple::NetworkOPs::getAccountTxsB (const RippleAddress & account, std::int32_t minLedger, std::int32_t maxLedger, bool descending, std::uint32_t offset, int limit, bool bAdmin) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doAccountTxOld().
virtual void ripple::NetworkOPs::getBookPage (Ledger::pointer lpLedger, const uint160 & uTakerPaysCurrencyID, const uint160 & uTakerPaysIssuerID, const uint160 & uTakerGetsCurrencyID, const uint160 & uTakerGetsIssuerID, const uint160 & uTakerID, const bool bProof, const unsigned int iLimit, const Json::Value & jvMarker, Json::Value & jvResult) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doBookOffers(), and ripple::RPCHandler::doSubscribe().
virtual Ledger::pointer ripple::NetworkOPs::getClosedLedger () pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doCommand(), ripple::RPCHandler::doOwnerInfo(), and ripple::RPCHandler::doPathFind().
virtual uint256 ripple::NetworkOPs::getClosedLedgerHash () pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doLedgerClosed().
virtual std::uint32_t ripple::NetworkOPs::getCloseTimeNC () pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::ValidationsImp::addValidation(), ripple::LedgerConsensusImp::closeLedger(), ripple::LedgerMasterImp::getPublishedLedgerAge(), ripple::LedgerMasterImp::getValidatedLedgerAge(), ripple::PeerImp::recvPropose(), ripple::PeerImp::recvValidation(), ripple::LedgerConsensusImp::statePreClose(), and ripple::LedgerMasterImp::updatePaths().
virtual Json::Value ripple::NetworkOPs::getConsensusInfo () pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doConsensusInfo().
virtual uint256 ripple::NetworkOPs::getConsensusLCL () pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::PeerImp::recvPropose().
virtual Ledger::pointer ripple::NetworkOPs::getCurrentLedger () pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doOwnerInfo(), ripple::RPC::lookupLedger(), and ripple::RPC::transactionSign().
virtual std::uint32_t ripple::NetworkOPs::getCurrentLedgerID () pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doLedgerAccept(), and ripple::RPCHandler::doLedgerCurrent().
virtual STVector256 ripple::NetworkOPs::getDirNodeInfo (Ledger::ref lrLedger, uint256 const & uRootIndex, std::uint64_t & uNodePrevious, std::uint64_t & uNodeNext) pure virtual
Implemented in ripple::NetworkOPsImp.
virtual bool ripple::NetworkOPs::getFetchPack (uint256 const & hash, Blob & data) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::AccountStateSF::haveNode(), and ripple::TransactionStateSF::haveNode().
virtual int ripple::NetworkOPs::getFetchSize () pure virtual
Implemented in ripple::NetworkOPsImp.
virtual bool ripple::NetworkOPs::getFullValidatedRange (std::uint32_t & minVal, std::uint32_t & maxVal) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::LedgerConsensusImp::statusChange().
virtual SLE::pointer ripple::NetworkOPs::getGenerator (Ledger::ref lrLedger, uint160 const & uGeneratorID) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPC::accountFromString(), and ripple::RPC::getMasterGenerator().
virtual std::uint32_t ripple::NetworkOPs::getLastCloseTime () pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::LedgerConsensusImp::statePreClose().
virtual SerializedValidation::ref ripple::NetworkOPs::getLastValidation () pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::LedgerConsensusImp::checkOurValidation().
virtual std::vector<RippleAddress> ripple::NetworkOPs::getLedgerAffectedAccounts (std::uint32_t ledgerSeq) pure virtual
Implemented in ripple::NetworkOPsImp.
virtual Ledger::pointer ripple::NetworkOPs::getLedgerByHash (uint256 const & hash) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::PeerImp::doFetchPack(), and ripple::RPC::lookupLedger().
virtual Ledger::pointer ripple::NetworkOPs::getLedgerBySeq (const std::uint32_t seq) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doTx(), and ripple::RPC::lookupLedger().
virtual Json::Value ripple::NetworkOPs::getLedgerFetchInfo () pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doFetchInfo().
virtual std::uint32_t ripple::NetworkOPs::getLedgerID (uint256 const & hash) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doLedgerClosed().
virtual std::size_t ripple::NetworkOPs::getLocalTxCount () pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doGetCounts().
virtual std::uint32_t ripple::NetworkOPs::getNetworkTimeNC () pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::UniqueNodeListImp::addClusterStatus(), ripple::UniqueNodeListImp::getClusterFee(), ripple::ValidationsImp::getCurrentTrustedValidations(), ripple::ValidationsImp::getCurrentValidations(), and ripple::ValidationsImp::getValidationCount().
virtual boost::posix_time::ptime ripple::NetworkOPs::getNetworkTimePT () pure virtual
Implemented in ripple::NetworkOPsImp.
virtual OperatingMode ripple::NetworkOPs::getOperatingMode () pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doCommand(), and ripple::LedgerConsensusImp::LedgerConsensusImp().
virtual Json::Value ripple::NetworkOPs::getOwnerInfo (Ledger::pointer lpLedger, const RippleAddress & naAccount) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doOwnerInfo().
virtual int ripple::NetworkOPs::getPreviousConvergeTime () pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::NetworkOPsImp::getServerInfo(), and ripple::LedgerConsensusImp::LedgerConsensusImp().
virtual int ripple::NetworkOPs::getPreviousProposers () pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::NetworkOPsImp::getServerInfo(), and ripple::LedgerConsensusImp::LedgerConsensusImp().
virtual Ledger::pointer ripple::NetworkOPs::getPublishedLedger () pure virtual
Implemented in ripple::NetworkOPsImp.
virtual Json::Value ripple::NetworkOPs::getServerInfo (bool human, bool admin) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doServerInfo(), and ripple::RPCHandler::doServerState().
virtual SLE::pointer ripple::NetworkOPs::getSLE (Ledger::pointer lpLedger, uint256 const & uHash) pure virtual
Implemented in ripple::NetworkOPsImp.
virtual SLE::pointer ripple::NetworkOPs::getSLEi (Ledger::pointer lpLedger, uint256 const & uHash) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doLedgerEntry(), and ripple::RPC::transactionSign().
virtual SHAMap::pointer ripple::NetworkOPs::getTXMap (uint256 const & hash) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::PeerImp::getLedger().
virtual TxsAccount ripple::NetworkOPs::getTxsAccount (const RippleAddress & account, std::int32_t minLedger, std::int32_t maxLedger, bool forward, Json::Value & token, int limit, bool bAdmin) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doAccountTx().
virtual MetaTxsList ripple::NetworkOPs::getTxsAccountB (const RippleAddress & account, std::int32_t minLedger, std::int32_t maxLedger, bool forward, Json::Value & token, int limit, bool bAdmin) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doAccountTx().
virtual Ledger::pointer ripple::NetworkOPs::getValidatedLedger () pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doRipplePathFind(), and ripple::RPC::lookupLedger().
virtual bool ripple::NetworkOPs::getValidatedRange (std::uint32_t & minVal, std::uint32_t & maxVal) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doAccountTx(), and ripple::RPCHandler::doAccountTxOld().
virtual std::uint32_t ripple::NetworkOPs::getValidatedSeq () pure virtual
Implemented in ripple::NetworkOPsImp.
virtual std::uint32_t ripple::NetworkOPs::getValidationTimeNC () pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::LedgerConsensusImp::accept(), and ripple::LedgerConsensusImp::checkOurValidation().
virtual void ripple::NetworkOPs::gotFetchPack (bool progress, std::uint32_t seq) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::PeerImp::recvGetObjectByHash().
virtual SHAMapAddNode ripple::NetworkOPs::gotTXData (const boost::shared_ptr< Peer > & peer, uint256 const & hash, const std::list< SHAMapNode > & nodeIDs, const std::list< Blob > & nodeData) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::PeerImp::recvLedger().
virtual bool ripple::NetworkOPs::hasTXSet (const boost::shared_ptr< Peer > & peer, uint256 const & set, protocol::TxSetStatus status) pure virtual
Implemented in ripple::NetworkOPsImp.
virtual bool ripple::NetworkOPs::haveLedger (std::uint32_t seq) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::PeerImp::recvGetObjectByHash().
virtual bool ripple::NetworkOPs::haveLedgerRange (std::uint32_t from, std::uint32_t to) pure virtual
Implemented in ripple::NetworkOPsImp.
virtual bool ripple::NetworkOPs::isFeatureBlocked () pure virtual
Implemented in ripple::NetworkOPsImp.
virtual bool ripple::NetworkOPs::isFull () pure virtual
Implemented in ripple::NetworkOPsImp.
virtual bool ripple::NetworkOPs::isNeedNetworkLedger () pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::LedgerConsensusImp::checkOurValidation(), and ripple::LedgerConsensusImp::LedgerConsensusImp().
virtual bool ripple::NetworkOPs::isProposing () pure virtual
Implemented in ripple::NetworkOPsImp.
virtual bool ripple::NetworkOPs::isValidated (std::uint32_t seq) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doTx().
virtual bool ripple::NetworkOPs::isValidated (std::uint32_t seq, uint256 const & hash) pure virtual
Implemented in ripple::NetworkOPsImp.
virtual bool ripple::NetworkOPs::isValidated (Ledger::ref l) pure virtual
Implemented in ripple::NetworkOPsImp.
virtual bool ripple::NetworkOPs::isValidating () pure virtual
Implemented in ripple::NetworkOPsImp.
virtual void ripple::NetworkOPs::makeFetchPack (Job & , boost::weak_ptr< Peer > peer, boost::shared_ptr< protocol::TMGetObjectByHash > request, Ledger::pointer wantLedger, Ledger::pointer haveLedger, std::uint32_t uUptime) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::PeerImp::doFetchPack().
virtual void ripple::NetworkOPs::mapComplete (uint256 const & hash, SHAMap::ref map) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::TACompletionHandler().
virtual void ripple::NetworkOPs::missingNodeInLedger (const std::uint32_t seq) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::SHAMap::DefaultMissingNodeHandler::operator()().
virtual void ripple::NetworkOPs::needNetworkLedger () pure virtual
Implemented in ripple::NetworkOPsImp.
NetworkOPs * ripple::NetworkOPs::New (clock_type & clock, LedgerMaster & ledgerMaster, Stoppable & parent, beast::Journal journal) static
Definition at line 3339 of file NetworkOPs.cpp.
 {
     return new NetworkOPsImp (clock, ledgerMaster, parent, journal);
 }
virtual void ripple::NetworkOPs::newLCL (int proposers, int convergeTime, uint256 const & ledgerHash) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::LedgerConsensusImp::beginAccept().
virtual Proposals& ripple::NetworkOPs::peekStoredProposals () pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::LedgerConsensusImp::accept(), and ripple::LedgerConsensusImp::playbackProposals().
virtual Transaction::pointer ripple::NetworkOPs::processTransaction (Transaction::pointer transaction, bool bAdmin, bool bLocal, bool bFailHard) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::PeerImp::checkTransaction(), and ripple::RPCHandler::doSubmit().
virtual Transaction::pointer ripple::NetworkOPs::processTransactionCb (Transaction::pointer , bool bAdmin, bool bLocal, bool bFailHard, stCallback) pure virtual
Implemented in ripple::NetworkOPsImp.
virtual void ripple::NetworkOPs::processTrustedProposal (LedgerProposal::pointer proposal, boost::shared_ptr< protocol::TMProposeSet > set, RippleAddress nodePublic, uint256 checkLedger, bool sigGood) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::PeerImp::checkPropose().
virtual void ripple::NetworkOPs::pubLedger (Ledger::ref lpAccepted) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::LedgerMasterImp::doAdvance().
virtual void ripple::NetworkOPs::pubProposedTransaction (Ledger::ref lpCurrent, SerializedTransaction::ref stTxn, TER terResult) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::LedgerMasterImp::doTransaction().
virtual bool ripple::NetworkOPs::recvValidation (SerializedValidation::ref val, const std::string & source) pure virtual
Implemented in ripple::NetworkOPsImp.
virtual void ripple::NetworkOPs::reportFeeChange () pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::LoadManagerImp::run().
virtual void ripple::NetworkOPs::runTransactionQueue () pure virtual
Implemented in ripple::NetworkOPsImp.
virtual void ripple::NetworkOPs::setFeatureBlocked () pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::ChangeTransactor::applyFeature().
virtual void ripple::NetworkOPs::setLastCloseTime (std::uint32_t t) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::LedgerConsensusImp::closeLedger().
virtual void ripple::NetworkOPs::setLastValidation (SerializedValidation::ref v) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::LedgerConsensusImp::accept(), and ripple::LedgerConsensusImp::checkOurValidation().
virtual void ripple::NetworkOPs::setProposing (bool isProposing, bool isValidating) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::LedgerConsensusImp::LedgerConsensusImp().
virtual void ripple::NetworkOPs::setStandAlone () pure virtual
Implemented in ripple::NetworkOPsImp.
virtual void ripple::NetworkOPs::setStateTimer () pure virtual
Implemented in ripple::NetworkOPsImp.
virtual bool ripple::NetworkOPs::shouldFetchPack (std::uint32_t seq) pure virtual
Implemented in ripple::NetworkOPsImp.
virtual bool ripple::NetworkOPs::stillNeedTXSet (uint256 const & hash) pure virtual
Implemented in ripple::NetworkOPsImp.
virtual void ripple::NetworkOPs::storeProposal (LedgerProposal::ref proposal, const RippleAddress & peerPublic) pure virtual
Implemented in ripple::NetworkOPsImp.
virtual std::string ripple::NetworkOPs::strOperatingMode () pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPCHandler::doCommand().
virtual void ripple::NetworkOPs::submitTransaction (Job & , SerializedTransaction::pointer , stCallback callback = stCallback()) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::ConsensusTransSetSF::gotNode().
virtual Transaction::pointer ripple::NetworkOPs::submitTransactionSync (Transaction::ref tpTrans, bool bAdmin, bool bLocal, bool bFailHard, bool bSubmit) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::RPC::transactionSign().
virtual void ripple::NetworkOPs::sweepFetchPack () pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::ApplicationImp::doSweep().
virtual void ripple::NetworkOPs::takePosition (int seq, SHAMap::ref position) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::LedgerConsensusImp::accept().
virtual std::string ripple::NetworkOPs::transactionsSQL (std::string selection, const RippleAddress & account, std::int32_t minLedger, std::int32_t maxLedger, bool descending, std::uint32_t offset, int limit, bool binary, bool count, bool bAdmin) pure virtual
Implemented in ripple::NetworkOPsImp.
virtual void ripple::NetworkOPs::updateLocalTx (Ledger::ref newValidLedger) pure virtual
Implemented in ripple::NetworkOPsImp.
Referenced by ripple::LedgerMasterImp::setValidLedger().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/misc/NetworkOPs.h
rippled/src/ripple_app/misc/NetworkOPs.cpp