rippled: rippled/src/ripple/rocksdb/rocksdb/util/signal_test.cc File Reference
signal_test.cc File Reference
#include "stack_trace.h"
#include <assert.h>
Functions
void f0 ()
void f1 ()
void f2 ()
void f3 ()
int main ()
Function Documentation
void f0 ()
Definition at line 9 of file signal_test.cc.
Referenced by f1().
           {
   char *p = nullptr;
   *p = 10;  /* SIGSEGV here!! */
 }
void f1 ()
Definition at line 14 of file signal_test.cc.
References f0().
Referenced by f2(), and sqlite3MemCompare().
           {
   f0();
 }
void f2 ()
Definition at line 18 of file signal_test.cc.
References f1().
Referenced by f3(), and sqlite3MemCompare().
           {
   f1();
 }
void f3 ()
Definition at line 22 of file signal_test.cc.
References f2().
Referenced by main().
           {
   f2();
 }
int main (void)
Definition at line 26 of file signal_test.cc.
References f3(), and rocksdb::InstallStackTraceHandler().
            {
   rocksdb::InstallStackTraceHandler();
   f3();
   return 0;
 }