rippled: ripple::PeerFinder::SlotImp::recent_t Class Reference
ripple::PeerFinder::SlotImp::recent_t Class Reference
#include <SlotImp.h>
Public Member Functions
recent_t (clock_type &clock)
void insert (beast::IP::Endpoint const &ep, int hops)
bool filter (beast::IP::Endpoint const &ep, int hops)
Private Member Functions
void expire ()
Private Attributes
recent_type cache
Friends
class SlotImp
Detailed Description
Definition at line 116 of file SlotImp.h.
Constructor & Destructor Documentation
ripple::PeerFinder::SlotImp::recent_t::recent_t (clock_type & clock) explicit
Definition at line 94 of file SlotImp.cpp.
     : cache (clock)
 {
 }
Member Function Documentation
void ripple::PeerFinder::SlotImp::recent_t::expire () private
Definition at line 127 of file SlotImp.cpp.
References beast::expire(), and ripple::PeerFinder::Tuning::liveCacheSecondsToLive().
Referenced by ripple::PeerFinder::SlotImp::expire().
 {
     beast::expire (cache,
         Tuning::liveCacheSecondsToLive);
 }
bool ripple::PeerFinder::SlotImp::recent_t::filter (beast::IP::Endpoint const & ep, int hops)
Returns true if we should not send endpoint to the slot.
Definition at line 115 of file SlotImp.cpp.
 {
     auto const iter (cache.find (ep));
     if (iter == cache.end())
         return false;
     // We avoid sending an endpoint if we heard it
     // from them recently at the same or lower hop count.
     // NOTE Other logic depends on this <= inequality.
     return iter->second <= hops;
 }
void ripple::PeerFinder::SlotImp::recent_t::insert (beast::IP::Endpoint const & ep, int hops)
Called for each valid endpoint received for a slot. We also insert messages that we send to the slot to prevent sending a slot the same address too frequently.
Definition at line 100 of file SlotImp.cpp.
 {
     auto const result (cache.emplace (ep, hops));
     if (! result.second)
     {
         // NOTE Other logic depends on this <= inequality.
         if (hops <= result.first->second)
         {
             result.first->second = hops;
             cache.touch (result.first);
         }
     }
 }
Friends And Related Function Documentation
friend class SlotImp friend
Definition at line 133 of file SlotImp.h.
Member Data Documentation
recent_type ripple::PeerFinder::SlotImp::recent_t::cache private
Definition at line 134 of file SlotImp.h.
The documentation for this class was generated from the following files:
rippled/src/ripple/peerfinder/impl/SlotImp.h
rippled/src/ripple/peerfinder/impl/SlotImp.cpp