rippled: ripple::SHAMap::DefaultMissingNodeHandler Struct Reference
ripple::SHAMap::DefaultMissingNodeHandler Struct Reference
Public Member Functions
void operator() (std::uint32_t refNUm)
Detailed Description
Default handler which calls NetworkOPs.
Definition at line 73 of file SHAMap.h.
Member Function Documentation
void ripple::SHAMap::DefaultMissingNodeHandler::operator() (std::uint32_t refNUm)
Definition at line 26 of file SHAMap.cpp.
References ripple::getApp(), ripple::Application::getOPs(), and ripple::NetworkOPs::missingNodeInLedger().
 {
     getApp().getOPs ().missingNodeInLedger (refNUm);
 };
The documentation for this struct was generated from the following files:
rippled/src/ripple_app/shamap/SHAMap.h
rippled/src/ripple_app/shamap/SHAMap.cpp