rippled: ripple::SHAMapSyncFilter Class Reference
ripple::SHAMapSyncFilter Class Reference abstract
#include <SHAMapSyncFilter.h>
Public Member Functions
virtual ~SHAMapSyncFilter ()
virtual void gotNode (bool fromFilter, SHAMapNode const &id, uint256 const &nodeHash, Blob &nodeData, SHAMapTreeNode::TNType type)=0
virtual bool haveNode (SHAMapNode const &id, uint256 const &nodeHash, Blob &nodeData)=0
Detailed Description
Definition at line 26 of file SHAMapSyncFilter.h.
Constructor & Destructor Documentation
virtual ripple::SHAMapSyncFilter::~SHAMapSyncFilter () inline virtual
Definition at line 29 of file SHAMapSyncFilter.h.
 { }
Member Function Documentation
virtual void ripple::SHAMapSyncFilter::gotNode (bool fromFilter, SHAMapNode const & id, uint256 const & nodeHash, Blob & nodeData, SHAMapTreeNode::TNType type) pure virtual
Implemented in ripple::TransactionStateSF, ripple::AccountStateSF, ripple::FetchPack_test::TestFilter, and ripple::ConsensusTransSetSF.
Referenced by ripple::SHAMap::addKnownNode(), ripple::SHAMap::addRootNode(), ripple::SHAMap::fetchRoot(), ripple::SHAMap::getNodeAsync(), and ripple::SHAMap::getNodePointerNT().
virtual bool ripple::SHAMapSyncFilter::haveNode (SHAMapNode const & id, uint256 const & nodeHash, Blob & nodeData) pure virtual
Implemented in ripple::TransactionStateSF, ripple::AccountStateSF, ripple::FetchPack_test::TestFilter, and ripple::ConsensusTransSetSF.
Referenced by ripple::SHAMap::fetchRoot(), ripple::SHAMap::getNodeAsync(), and ripple::SHAMap::getNodePointerNT().
The documentation for this class was generated from the following file:
rippled/src/ripple_app/shamap/SHAMapSyncFilter.h