rippled: rocksdb::FlushBlockBySizePolicy Class Reference
rocksdb::FlushBlockBySizePolicy Class Reference
Public Member Functions
FlushBlockBySizePolicy (const uint64_t block_size, const uint64_t block_size_deviation, const BlockBuilder &data_block_builder)
virtual bool Update (const Slice &key, const Slice &value) override
Public Member Functions inherited from rocksdb::FlushBlockPolicy
virtual ~FlushBlockPolicy ()
Private Member Functions
bool BlockAlmostFull (const Slice &key, const Slice &value) const
Private Attributes
const uint64_t block_size_
const uint64_t block_size_deviation_
const BlockBuilder & data_block_builder_
Detailed Description
Definition at line 15 of file flush_block_policy.cc.
Constructor & Destructor Documentation
rocksdb::FlushBlockBySizePolicy::FlushBlockBySizePolicy (const uint64_t block_size, const uint64_t block_size_deviation, const BlockBuilder & data_block_builder) inline
Definition at line 21 of file flush_block_policy.cc.
                                                                  :
       block_size_(block_size),
       block_size_deviation_(block_size_deviation),
       data_block_builder_(data_block_builder) {
   }
Member Function Documentation
bool rocksdb::FlushBlockBySizePolicy::BlockAlmostFull (const Slice & key, const Slice & value) const inline private
Definition at line 47 of file flush_block_policy.cc.
References block_size_, block_size_deviation_, rocksdb::BlockBuilder::CurrentSizeEstimate(), data_block_builder_, and rocksdb::BlockBuilder::EstimateSizeAfterKV().
Referenced by Update().
{
     const auto curr_size = data_block_builder_.CurrentSizeEstimate();
     const auto estimated_size_after =
       data_block_builder_.EstimateSizeAfterKV(key, value);
     return
       estimated_size_after > block_size_ &&
       block_size_deviation_ > 0 &&
       curr_size * 100 > block_size_ * (100 - block_size_deviation_);
   }
virtual bool rocksdb::FlushBlockBySizePolicy::Update (const Slice & key, const Slice & value) inline override virtual
Implements rocksdb::FlushBlockPolicy.
Definition at line 29 of file flush_block_policy.cc.
References block_size_, BlockAlmostFull(), rocksdb::BlockBuilder::CurrentSizeEstimate(), data_block_builder_, and rocksdb::BlockBuilder::empty().
{
     // it makes no sense to flush when the data block is empty
     if (data_block_builder_.empty()) {
       return false;
     }
     auto curr_size = data_block_builder_.CurrentSizeEstimate();
     // Do flush if one of the below two conditions is true:
     // 1) if the current estimated size already exceeds the block size,
     // 2) block_size_deviation is set and the estimated size after appending
     // the kv will exceed the block size and the current size is under the
     // the deviation.
     return curr_size >= block_size_ || BlockAlmostFull(key, value);
   }
Member Data Documentation
const uint64_t rocksdb::FlushBlockBySizePolicy::block_size_ private
Definition at line 58 of file flush_block_policy.cc.
Referenced by BlockAlmostFull(), and Update().
const uint64_t rocksdb::FlushBlockBySizePolicy::block_size_deviation_ private
Definition at line 59 of file flush_block_policy.cc.
Referenced by BlockAlmostFull().
const BlockBuilder& rocksdb::FlushBlockBySizePolicy::data_block_builder_ private
Definition at line 60 of file flush_block_policy.cc.
Referenced by BlockAlmostFull(), and Update().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/table/flush_block_policy.cc