rippled: beast::DirectoryIterator Class Reference
beast::DirectoryIterator Class Reference
#include <DirectoryIterator.h>
Classes
class NativeIterator
Public Member Functions
DirectoryIterator (const File &directory, bool isRecursive, const String &wildCard="*", int whatToLookFor=File::findFiles)
~DirectoryIterator ()
bool next ()
bool next (bool *isDirectory, bool *isHidden, std::int64_t *fileSize, Time *modTime, Time *creationTime, bool *isReadOnly)
const File & getFile () const
float getEstimatedProgress () const
Private Attributes
StringArray wildCards
NativeIterator fileFinder
String wildCard
String path
int index
int totalNumFiles
const int whatToLookFor
const bool isRecursive
bool hasBeenAdvanced
ScopedPointer< DirectoryIterator > subIterator
File currentFile
Friends
class ScopedPointer< NativeIterator::Pimpl >
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
Searches through a the files in a directory, returning each file that is found.
A DirectoryIterator will search through a directory and its subdirectories using a wildcard filepattern match.
If you may be finding a large number of files, this is better than using File::findChildFiles() because it doesn't block while it finds them all, and this is more memory-efficient.
It can also guess how far it's got using a wildly inaccurate algorithm.
Definition at line 43 of file DirectoryIterator.h.
Constructor & Destructor Documentation
beast::DirectoryIterator::DirectoryIterator (const File & directory, bool isRecursive, const String & wildCard = "*", int whatToLookFor = File::findFiles)
Creates a DirectoryIterator for a given directory.
After creating one of these, call its next() method to get the first file - e.g.
DirectoryIterator iter (File ("/animals/mooses"), true, "*.moose");
while (iter.next())
{
    File theFileItFound (iter.getFile());
    ... etc
}
Parameters
directory the directory to search in
isRecursive whether all the subdirectories should also be searched
wildCard the file pattern to match. This may contain multiple patterns separated by a semi-colon or comma, e.g. "*.jpg;*.png"
whatToLookFor a value from the File::TypesOfFileToFind enum, specifying whether to look for files, directories, or both.
Definition at line 45 of file DirectoryIterator.cpp.
References bassert, beast::File::findDirectories, and beast::File::findFiles.
   : wildCards (parseWildcards (pattern)),
     fileFinder (directory, (recursive || wildCards.size() > 1) ? "*" : pattern),
     wildCard (pattern),
     path (File::addTrailingSeparator (directory.getFullPathName())),
     index (-1),
     totalNumFiles (-1),
     whatToLookFor (type),
     isRecursive (recursive),
     hasBeenAdvanced (false)
 {
     // you have to specify the type of files you're looking for!
     bassert ((type & (File::findFiles | File::findDirectories)) != 0);
     bassert (type > 0 && type <= 7);
 }
beast::DirectoryIterator::~DirectoryIterator ()
Destructor.
Definition at line 62 of file DirectoryIterator.cpp.
 {
 }
Member Function Documentation
float beast::DirectoryIterator::getEstimatedProgress () const
Returns a guess of how far through the search the iterator has got.
Returns
a value 0.0 to 1.0 to show the progress, although this won't be very accurate.
Definition at line 145 of file DirectoryIterator.cpp.
References beast::File::findFilesAndDirectories, beast::File::getNumberOfChildFiles(), index, path, subIterator, and totalNumFiles.
 {
     if (totalNumFiles < 0)
         totalNumFiles = File (path).getNumberOfChildFiles (File::findFilesAndDirectories);
     if (totalNumFiles <= 0)
         return 0.0f;
     const float detailedIndex = (subIterator != nullptr) ? index + subIterator->getEstimatedProgress()
                                                          : (float) index;
     return detailedIndex / totalNumFiles;
 }
const File & beast::DirectoryIterator::getFile () const
Returns the file that the iterator is currently pointing at.
The result of this call is only valid after a call to next() has returned true.
Definition at line 134 of file DirectoryIterator.cpp.
References bassert, currentFile, hasBeenAdvanced, and subIterator.
Referenced by beast::File::findChildFiles().
 {
     if (subIterator != nullptr && subIterator->hasBeenAdvanced)
         return subIterator->getFile();
     // You need to call DirectoryIterator::next() before asking it for the file that it found!
     bassert (hasBeenAdvanced);
     return currentFile;
 }
bool beast::DirectoryIterator::next ()
Moves the iterator along to the next file.
Returns
true if a file was found (you can then use getFile() to see what it was) - or false if there are no more matching files.
Definition at line 66 of file DirectoryIterator.cpp.
Referenced by beast::File::containsSubDirectories(), beast::File::findChildFiles(), beast::File::getNumberOfChildFiles(), and next().
 {
     return next (nullptr, nullptr, nullptr, nullptr, nullptr, nullptr);
 }
bool beast::DirectoryIterator::next (bool * isDirectory, bool * isHidden, std::int64_t * fileSize, Time * modTime, Time * creationTime, bool * isReadOnly)
Moves the iterator along to the next file, and returns various properties of that file.
If you need to find out details about the file, it's more efficient to call this method than to call the normal next() method and then find out the details afterwards.
All the parameters are optional, so pass null pointers for any items that you're not interested in.
Returns
true if a file was found (you can then use getFile() to see what it was) - or false if there are no more matching files. If it returns false, then none of the parameters will be filled-in.
Definition at line 71 of file DirectoryIterator.cpp.
References beast::String::containsOnly(), beast::File::createFileWithoutCheckingPath(), currentFile, fileFinder, beast::fileMatches(), filename, beast::File::findDirectories, beast::File::findFiles, hasBeenAdvanced, beast::File::ignoreHiddenFiles, index, isRecursive, next(), beast::DirectoryIterator::NativeIterator::next(), path, beast::StringArray::size(), subIterator, whatToLookFor, wildCard, and wildCards.
 {
     hasBeenAdvanced = true;
     if (subIterator != nullptr)
     {
         if (subIterator->next (isDirResult, isHiddenResult, fileSize, modTime, creationTime, isReadOnly))
             return true;
         subIterator = nullptr;
     }
     String filename;
     bool isDirectory, isHidden = false;
     while (fileFinder.next (filename, &isDirectory,
                             (isHiddenResult != nullptr || (whatToLookFor & File::ignoreHiddenFiles) != 0) ? &isHidden : nullptr,
                             fileSize, modTime, creationTime, isReadOnly))
     {
         ++index;
         if (! filename.containsOnly ("."))
         {
             bool matches = false;
             if (isDirectory)
             {
                 if (isRecursive && ((whatToLookFor & File::ignoreHiddenFiles) == 0 || ! isHidden))
                     subIterator = new DirectoryIterator (File::createFileWithoutCheckingPath (path + filename),
                                                          true, wildCard, whatToLookFor);
                 matches = (whatToLookFor & File::findDirectories) != 0;
             }
             else
             {
                 matches = (whatToLookFor & File::findFiles) != 0;
             }
             // if we're not relying on the OS iterator to do the wildcard match, do it now..
             if (matches && (isRecursive || wildCards.size() > 1))
                 matches = fileMatches (wildCards, filename);
             if (matches && (whatToLookFor & File::ignoreHiddenFiles) != 0)
                 matches = ! isHidden;
             if (matches)
             {
                 currentFile = File::createFileWithoutCheckingPath (path + filename);
                 if (isHiddenResult != nullptr)     *isHiddenResult = isHidden;
                 if (isDirResult != nullptr)        *isDirResult = isDirectory;
                 return true;
             }
             if (subIterator != nullptr)
                 return next (isDirResult, isHiddenResult, fileSize, modTime, creationTime, isReadOnly);
         }
     }
     return false;
 }
Friends And Related Function Documentation
friend class ScopedPointer< NativeIterator::Pimpl > friend
Definition at line 136 of file DirectoryIterator.h.
Member Data Documentation
File beast::DirectoryIterator::currentFile private
Definition at line 146 of file DirectoryIterator.h.
Referenced by getFile(), and next().
NativeIterator beast::DirectoryIterator::fileFinder private
Definition at line 138 of file DirectoryIterator.h.
Referenced by next().
bool beast::DirectoryIterator::hasBeenAdvanced private
Definition at line 144 of file DirectoryIterator.h.
Referenced by getFile(), and next().
int beast::DirectoryIterator::index private
Definition at line 140 of file DirectoryIterator.h.
Referenced by getEstimatedProgress(), and next().
const bool beast::DirectoryIterator::isRecursive private
Definition at line 143 of file DirectoryIterator.h.
Referenced by next().
String beast::DirectoryIterator::path private
Definition at line 139 of file DirectoryIterator.h.
Referenced by getEstimatedProgress(), and next().
ScopedPointer<DirectoryIterator> beast::DirectoryIterator::subIterator private
Definition at line 145 of file DirectoryIterator.h.
Referenced by getEstimatedProgress(), getFile(), and next().
int beast::DirectoryIterator::totalNumFiles mutable private
Definition at line 141 of file DirectoryIterator.h.
Referenced by getEstimatedProgress().
const int beast::DirectoryIterator::whatToLookFor private
Definition at line 142 of file DirectoryIterator.h.
Referenced by next().
String beast::DirectoryIterator::wildCard private
Definition at line 139 of file DirectoryIterator.h.
Referenced by next().
StringArray beast::DirectoryIterator::wildCards private
Definition at line 137 of file DirectoryIterator.h.
Referenced by next().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_core/files/DirectoryIterator.h
rippled/src/beast/modules/beast_core/files/DirectoryIterator.cpp