rippled: ripple::LoadFeeTrack Class Reference
ripple::LoadFeeTrack Class Reference abstract
#include <LoadFeeTrack.h>
Public Member Functions
virtual ~LoadFeeTrack ()
virtual std::uint64_t scaleFeeBase (std::uint64_t fee, std::uint64_t baseFee, std::uint32_t referenceFeeUnits)=0
virtual std::uint64_t scaleFeeLoad (std::uint64_t fee, std::uint64_t baseFee, std::uint32_t referenceFeeUnits, bool bAdmin)=0
virtual void setRemoteFee (std::uint32_t)=0
virtual std::uint32_t getRemoteFee ()=0
virtual std::uint32_t getLocalFee ()=0
virtual std::uint32_t getClusterFee ()=0
virtual std::uint32_t getLoadBase ()=0
virtual std::uint32_t getLoadFactor ()=0
virtual Json::Value getJson (std::uint64_t baseFee, std::uint32_t referenceFeeUnits)=0
virtual void setClusterFee (std::uint32_t)=0
virtual bool raiseLocalFee ()=0
virtual bool lowerLocalFee ()=0
virtual bool isLoadedLocal ()=0
virtual bool isLoadedCluster ()=0
Static Public Member Functions
static LoadFeeTrack * New (beast::Journal journal)
Detailed Description
Manages the current fee schedule.
The "base" fee is the cost to send a reference transaction under no load, expressed in millionths of one XRP.
The "load" fee is how much the local server currently charges to send a reference transaction. This fee fluctuates based on the load of the server.
Definition at line 35 of file LoadFeeTrack.h.
Constructor & Destructor Documentation
virtual ripple::LoadFeeTrack::~LoadFeeTrack () inline virtual
Definition at line 42 of file LoadFeeTrack.h.
 { }
Member Function Documentation
virtual std::uint32_t ripple::LoadFeeTrack::getClusterFee () pure virtual
Implemented in ripple::LoadFeeTrackImp.
Referenced by ripple::NetworkOPsImp::getServerInfo().
virtual Json::Value ripple::LoadFeeTrack::getJson (std::uint64_t baseFee, std::uint32_t referenceFeeUnits) pure virtual
Implemented in ripple::LoadFeeTrackImp.
virtual std::uint32_t ripple::LoadFeeTrack::getLoadBase () pure virtual
Implemented in ripple::LoadFeeTrackImp.
Referenced by ripple::UniqueNodeListImp::addClusterStatus(), ripple::LedgerConsensusImp::addLoad(), ripple::LedgerMasterImp::checkAccept(), ripple::NetworkOPsImp::getServerInfo(), ripple::NetworkOPsImp::pubServer(), and ripple::NetworkOPsImp::subServer().
virtual std::uint32_t ripple::LoadFeeTrack::getLoadFactor () pure virtual
Implemented in ripple::LoadFeeTrackImp.
Referenced by ripple::NetworkOPsImp::getServerInfo(), ripple::NetworkOPsImp::pubServer(), and ripple::NetworkOPsImp::subServer().
virtual std::uint32_t ripple::LoadFeeTrack::getLocalFee () pure virtual
Implemented in ripple::LoadFeeTrackImp.
Referenced by ripple::NetworkOPsImp::getServerInfo().
virtual std::uint32_t ripple::LoadFeeTrack::getRemoteFee () pure virtual
Implemented in ripple::LoadFeeTrackImp.
Referenced by ripple::NetworkOPsImp::getServerInfo().
virtual bool ripple::LoadFeeTrack::isLoadedCluster () pure virtual
Implemented in ripple::LoadFeeTrackImp.
virtual bool ripple::LoadFeeTrack::isLoadedLocal () pure virtual
Implemented in ripple::LoadFeeTrackImp.
Referenced by ripple::LedgerMasterImp::doAdvance(), ripple::PathRequest::doUpdate(), and ripple::PeerImp::recvValidation().
virtual bool ripple::LoadFeeTrack::lowerLocalFee () pure virtual
Implemented in ripple::LoadFeeTrackImp.
Referenced by ripple::LoadManagerImp::run().
LoadFeeTrack * ripple::LoadFeeTrack::New (beast::Journal journal) static
Create a new tracker.
Definition at line 24 of file LoadFeeTrackImp.cpp.
 {
     return new LoadFeeTrackImp (journal);
 }
virtual bool ripple::LoadFeeTrack::raiseLocalFee () pure virtual
Implemented in ripple::LoadFeeTrackImp.
Referenced by ripple::LoadManagerImp::run().
virtual std::uint64_t ripple::LoadFeeTrack::scaleFeeBase (std::uint64_t fee, std::uint64_t baseFee, std::uint32_t referenceFeeUnits) pure virtual
Implemented in ripple::LoadFeeTrackImp.
Referenced by ripple::Ledger::scaleFeeBase().
virtual std::uint64_t ripple::LoadFeeTrack::scaleFeeLoad (std::uint64_t fee, std::uint64_t baseFee, std::uint32_t referenceFeeUnits, bool bAdmin) pure virtual
Implemented in ripple::LoadFeeTrackImp.
Referenced by ripple::Ledger::scaleFeeLoad().
virtual void ripple::LoadFeeTrack::setClusterFee (std::uint32_t) pure virtual
Implemented in ripple::LoadFeeTrackImp.
Referenced by ripple::PeerImp::recvCluster().
virtual void ripple::LoadFeeTrack::setRemoteFee (std::uint32_t) pure virtual
Implemented in ripple::LoadFeeTrackImp.
Referenced by ripple::LedgerMasterImp::checkAccept().
The documentation for this class was generated from the following files:
rippled/src/ripple_core/functional/LoadFeeTrack.h
rippled/src/ripple_core/functional/LoadFeeTrackImp.cpp