rippled: rocksdb::ReduceDBLevelsCommand Class Reference
rocksdb::ReduceDBLevelsCommand Class Reference
#include <ldb_cmd.h>
Public Member Functions
ReduceDBLevelsCommand (const vector< string > &params, const map< string, string > &options, const vector< string > &flags)
virtual Options PrepareOptionsForOpenDB ()
virtual void DoCommand ()
virtual bool NoDBOpen ()
Public Member Functions inherited from rocksdb::LDBCommand
bool ValidateCmdLineOptions ()
virtual void SetOptions (Options options)
virtual ~LDBCommand ()
void Run ()
LDBCommandExecuteResult GetExecuteState ()
void ClearPreviousRunState ()
Static Public Member Functions
static string Name ()
static void Help (string &msg)
static vector< string > PrepareArgs (const string &db_path, int new_levels, bool print_old_level=false)
Static Public Member Functions inherited from rocksdb::LDBCommand
static LDBCommand * InitFromCmdLineArgs (const vector< string > &args, const Options &options=Options())
static LDBCommand * InitFromCmdLineArgs (int argc, char **argv, const Options &options=Options())
static string HexToString (const string &str)
static string StringToHex (const string &str)
Private Member Functions
Status GetOldNumOfLevels (Options &opt, int *levels)
Private Attributes
int old_levels_
int new_levels_
bool print_old_levels_
Static Private Attributes
static const string ARG_NEW_LEVELS = "new_levels"
static const string ARG_PRINT_OLD_LEVELS = "print_old_levels"
Additional Inherited Members
Static Public Attributes inherited from rocksdb::LDBCommand
static const string ARG_DB = "db"
static const string ARG_HEX = "hex"
static const string ARG_KEY_HEX = "key_hex"
static const string ARG_VALUE_HEX = "value_hex"
static const string ARG_TTL = "ttl"
static const string ARG_TTL_START = "start_time"
static const string ARG_TTL_END = "end_time"
static const string ARG_TIMESTAMP = "timestamp"
static const string ARG_FROM = "from"
static const string ARG_TO = "to"
static const string ARG_MAX_KEYS = "max_keys"
static const string ARG_BLOOM_BITS = "bloom_bits"
static const string ARG_COMPRESSION_TYPE = "compression_type"
static const string ARG_BLOCK_SIZE = "block_size"
static const string ARG_AUTO_COMPACTION = "auto_compaction"
static const string ARG_WRITE_BUFFER_SIZE = "write_buffer_size"
static const string ARG_FILE_SIZE = "file_size"
static const string ARG_CREATE_IF_MISSING = "create_if_missing"
static const char * DELIM = " ==> "
Protected Member Functions inherited from rocksdb::LDBCommand
bool ParseKeyValue (const string &line, string *key, string *value, bool is_key_hex, bool is_value_hex)
LDBCommand (const map< string, string > &options, const vector< string > &flags, bool is_read_only, const vector< string > &valid_cmd_line_options)
void OpenDB ()
void CloseDB ()
vector< string > BuildCmdLineOptions (vector< string > options)
bool ParseIntOption (const map< string, string > &options, const string &option, int &value, LDBCommandExecuteResult &exec_state)
bool ParseStringOption (const map< string, string > &options, const string &option, string *value)
Static Protected Member Functions inherited from rocksdb::LDBCommand
static string PrintKeyValue (const string &key, const string &value, bool is_key_hex, bool is_value_hex)
static string PrintKeyValue (const string &key, const string &value, bool is_hex)
static bool IsFlagPresent (const vector< string > &flags, const string &flag)
static string HelpRangeCmdArgs ()
Protected Attributes inherited from rocksdb::LDBCommand
LDBCommandExecuteResult exec_state_
string db_path_
DB * db_
StackableDB * sdb_
bool is_read_only_
bool is_key_hex_
bool is_value_hex_
bool is_db_ttl_
bool timestamp_
const map< string, string > option_map_
const vector< string > flags_
const vector< string > valid_cmd_line_options_
Options options_
Detailed Description
Definition at line 487 of file ldb_cmd.h.
Constructor & Destructor Documentation
rocksdb::ReduceDBLevelsCommand::ReduceDBLevelsCommand (const vector< string > & params, const map< string, string > & options, const vector< string > & flags)
Definition at line 963 of file ldb_cmd.cc.
References ARG_NEW_LEVELS, and ARG_PRINT_OLD_LEVELS.
                                                                        :
     LDBCommand(options, flags, false,
                BuildCmdLineOptions({ARG_NEW_LEVELS, ARG_PRINT_OLD_LEVELS})),
Member Function Documentation
void rocksdb::ReduceDBLevelsCommand::DoCommand () virtual
Implements rocksdb::LDBCommand.
Definition at line 1036 of file ldb_cmd.cc.
References rocksdb::LDBCommand::CloseDB(), rocksdb::DB::CompactRange(), rocksdb::Options::comparator, rocksdb::LDBCommand::db_, rocksdb::LDBCommand::db_path_, rocksdb::LDBCommand::exec_state_, rocksdb::LDBCommandExecuteResult::FAILED(), GetOldNumOfLevels(), rocksdb::port::Mutex::Lock(), mu, new_levels_, rocksdb::Status::ok(), old_levels_, rocksdb::LDBCommand::OpenDB(), PrepareOptionsForOpenDB(), print_old_levels_, rocksdb::VersionSet::Recover(), rocksdb::VersionSet::ReduceNumberOfLevels(), rocksdb::Status::ToString(), and rocksdb::port::Mutex::Unlock().
{
   if (new_levels_ <= 1) {
     exec_state_ = LDBCommandExecuteResult::FAILED(
         "Invalid number of levels.\n");
     return;
   }
   Status st;
   Options opt = PrepareOptionsForOpenDB();
   int old_level_num = -1;
   st = GetOldNumOfLevels(opt, &old_level_num);
   if (!st.ok()) {
     exec_state_ = LDBCommandExecuteResult::FAILED(st.ToString());
     return;
   }
   if (print_old_levels_) {
     fprintf(stdout, "The old number of levels in use is %d\n", old_level_num);
   }
   if (old_level_num <= new_levels_) {
     return;
   }
   old_levels_ = old_level_num;
   OpenDB();
   if (!db_) {
     return;
   }
   // Compact the whole DB to put all files to the highest level.
   fprintf(stdout, "Compacting the db...\n");
   db_->CompactRange(nullptr, nullptr);
   CloseDB();
   EnvOptions soptions;
   TableCache tc(db_path_, &opt, soptions, 10);
   const InternalKeyComparator cmp(opt.comparator);
   VersionSet versions(db_path_, &opt, soptions, &tc, &cmp);
   // We rely the VersionSet::Recover to tell us the internal data structures
   // in the db. And the Recover() should never do any change (like LogAndApply)
   // to the manifest file.
   st = versions.Recover();
   if (!st.ok()) {
     exec_state_ = LDBCommandExecuteResult::FAILED(st.ToString());
     return;
   }
   port::Mutex mu;
   mu.Lock();
   st = versions.ReduceNumberOfLevels(new_levels_, &mu);
   mu.Unlock();
   if (!st.ok()) {
     exec_state_ = LDBCommandExecuteResult::FAILED(st.ToString());
     return;
   }
 }
Status rocksdb::ReduceDBLevelsCommand::GetOldNumOfLevels (Options & opt, int * levels) private
Definition at line 1012 of file ldb_cmd.cc.
References rocksdb::Options::comparator, rocksdb::LDBCommand::db_path_, ripple::max(), rocksdb::VersionSet::NumberLevels(), rocksdb::VersionSet::NumLevelFiles(), rocksdb::Status::ok(), and rocksdb::VersionSet::Recover().
Referenced by DoCommand().
                  {
   EnvOptions soptions;
   TableCache tc(db_path_, &opt, soptions, 10);
   const InternalKeyComparator cmp(opt.comparator);
   VersionSet versions(db_path_, &opt, soptions, &tc, &cmp);
   // We rely the VersionSet::Recover to tell us the internal data structures
   // in the db. And the Recover() should never do any change
   // (like LogAndApply) to the manifest file.
   Status st = versions.Recover();
   if (!st.ok()) {
     return st;
   }
   int max = -1;
   for (int i = 0; i < versions.NumberLevels(); i++) {
     if (versions.NumLevelFiles(i)) {
       max = i;
     }
   }
   *levels = max + 1;
   return st;
 }
void rocksdb::ReduceDBLevelsCommand::Help (string & msg) static
Definition at line 993 of file ldb_cmd.cc.
References ARG_NEW_LEVELS, ARG_PRINT_OLD_LEVELS, and Name().
Referenced by rocksdb::LDBCommandRunner::PrintHelp().
{
   ret.append("  ");
   ret.append(ReduceDBLevelsCommand::Name());
   ret.append(" --" + ARG_NEW_LEVELS + "=<New number of levels>");
   ret.append(" [--" + ARG_PRINT_OLD_LEVELS + "]");
   ret.append("\n");
 }
static string rocksdb::ReduceDBLevelsCommand::Name () inline static
Definition at line 489 of file ldb_cmd.h.
Referenced by Help(), and rocksdb::LDBCommand::SelectCommand().
 { return "reduce_levels"; }
virtual bool rocksdb::ReduceDBLevelsCommand::NoDBOpen () inline virtual
Reimplemented from rocksdb::LDBCommand.
Definition at line 498 of file ldb_cmd.h.
{
     return true;
   }
vector< string > rocksdb::ReduceDBLevelsCommand::PrepareArgs (const string & db_path, int new_levels, bool print_old_level = false) static
Definition at line 981 of file ldb_cmd.cc.
References rocksdb::LDBCommand::ARG_DB, ARG_NEW_LEVELS, ARG_PRINT_OLD_LEVELS, and beast::IP::to_string().
Referenced by rocksdb::ReduceLevelTest::ReduceLevels().
{
   vector<string> ret;
   ret.push_back("reduce_levels");
   ret.push_back("--" + ARG_DB + "=" + db_path);
   ret.push_back("--" + ARG_NEW_LEVELS + "=" + to_string(new_levels));
   if(print_old_level) {
     ret.push_back("--" + ARG_PRINT_OLD_LEVELS);
   }
   return ret;
 }
Options rocksdb::ReduceDBLevelsCommand::PrepareOptionsForOpenDB () virtual
Reimplemented from rocksdb::LDBCommand.
Definition at line 1001 of file ldb_cmd.cc.
References rocksdb::Options::max_bytes_for_level_base, rocksdb::Options::max_bytes_for_level_multiplier, rocksdb::Options::max_bytes_for_level_multiplier_additional, rocksdb::Options::max_mem_compaction_level, rocksdb::Options::num_levels, old_levels_, and rocksdb::LDBCommand::PrepareOptionsForOpenDB().
Referenced by DoCommand().
{
   Options opt = LDBCommand::PrepareOptionsForOpenDB();
   opt.num_levels = old_levels_;
   opt.max_bytes_for_level_multiplier_additional.resize(opt.num_levels, 1);
   // Disable size compaction
   opt.max_bytes_for_level_base = 1UL << 50;
   opt.max_bytes_for_level_multiplier = 1;
   opt.max_mem_compaction_level = 0;
   return opt;
 }
Member Data Documentation
const string rocksdb::ReduceDBLevelsCommand::ARG_NEW_LEVELS = "new_levels" static private
Definition at line 512 of file ldb_cmd.h.
Referenced by Help(), PrepareArgs(), and ReduceDBLevelsCommand().
const string rocksdb::ReduceDBLevelsCommand::ARG_PRINT_OLD_LEVELS = "print_old_levels" static private
Definition at line 513 of file ldb_cmd.h.
Referenced by Help(), PrepareArgs(), and ReduceDBLevelsCommand().
int rocksdb::ReduceDBLevelsCommand::new_levels_ private
Definition at line 509 of file ldb_cmd.h.
Referenced by DoCommand().
int rocksdb::ReduceDBLevelsCommand::old_levels_ private
Definition at line 508 of file ldb_cmd.h.
Referenced by DoCommand(), and PrepareOptionsForOpenDB().
bool rocksdb::ReduceDBLevelsCommand::print_old_levels_ private
Definition at line 510 of file ldb_cmd.h.
Referenced by DoCommand().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/util/ldb_cmd.h
rippled/src/ripple/rocksdb/rocksdb/util/ldb_cmd.cc