rippled: ripple::WSServerHandler< endpoint_type > Class Template Reference
ripple::WSServerHandler< endpoint_type > Class Template Reference
#include <WSConnection.h>
Public Types
enum { crTooSlow = 4000 }
typedef
endpoint_type::handler::connection_ptr connection_ptr
typedef
endpoint_type::handler::message_ptr message_ptr
typedef boost::shared_ptr
< WSConnectionType
< endpoint_type > > wsc_ptr
Public Member Functions
WSServerHandler (Resource::Manager &resourceManager, InfoSub::Source &source, boost::asio::ssl::context &ssl_context, bool bPublic, bool bProxy)
bool getPublic ()
void send (connection_ptr cpClient, message_ptr mpMessage)
void send (connection_ptr cpClient, const std::string &strMessage, bool broadcast)
void send (connection_ptr cpClient, const Json::Value &jvObj, bool broadcast)
void pingTimer (connection_ptr cpClient)
void on_send_empty (connection_ptr cpClient)
void on_open (connection_ptr cpClient)
void on_pong (connection_ptr cpClient, std::string data)
void on_close (connection_ptr cpClient)
void on_fail (connection_ptr cpClient)
void doClose (connection_ptr const &cpClient, char const *reason)
void on_message (connection_ptr cpClient, message_ptr mpMessage)
void do_messages (Job &job, connection_ptr cpClient)
bool do_message (Job &job, const connection_ptr &cpClient, const wsc_ptr &conn, const message_ptr &mpMessage)
boost::asio::ssl::context & get_ssl_context ()
bool get_proxy ()
bool http (connection_ptr cpClient)
Static Public Member Functions
static void ssend (connection_ptr cpClient, message_ptr mpMessage)
static void ssendb (connection_ptr cpClient, const std::string &strMessage, bool broadcast)
Protected Types
typedef RippleMutex LockType
typedef std::lock_guard< LockType > ScopedLockType
typedef ripple::unordered_map
< connection_ptr,
boost::shared_ptr
< WSConnectionType
< endpoint_type > > > MapType
Protected Attributes
LockType mLock
MapType mMap
bool const mPublic
bool const mProxy
Private Attributes
Resource::Manager & m_resourceManager
InfoSub::Source & m_source
boost::asio::ssl::context & m_ssl_context
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
template<typename endpoint_type>
class ripple::WSServerHandler< endpoint_type >
Definition at line 79 of file WSConnection.h.
Member Typedef Documentation
template<typename endpoint_type > typedef endpoint_type::handler::connection_ptr ripple::WSServerHandler< endpoint_type >::connection_ptr
Definition at line 49 of file WSServerHandler.h.
template<typename endpoint_type > typedef RippleMutex ripple::WSServerHandler< endpoint_type >::LockType protected
Definition at line 65 of file WSServerHandler.h.
template<typename endpoint_type > typedef ripple::unordered_map<connection_ptr, boost::shared_ptr <WSConnectionType <endpoint_type> > > ripple::WSServerHandler< endpoint_type >::MapType protected
Definition at line 75 of file WSServerHandler.h.
template<typename endpoint_type > typedef endpoint_type::handler::message_ptr ripple::WSServerHandler< endpoint_type >::message_ptr
Definition at line 50 of file WSServerHandler.h.
template<typename endpoint_type > typedef std::lock_guard<LockType> ripple::WSServerHandler< endpoint_type >::ScopedLockType protected
Definition at line 66 of file WSServerHandler.h.
template<typename endpoint_type > typedef boost::shared_ptr< WSConnectionType <endpoint_type> > ripple::WSServerHandler< endpoint_type >::wsc_ptr
Definition at line 51 of file WSServerHandler.h.
Member Enumeration Documentation
template<typename endpoint_type > anonymous enum
Enumerator
crTooSlow
Definition at line 54 of file WSServerHandler.h.
     {
         crTooSlow   = 4000,     // Client is too slow.
     };
Constructor & Destructor Documentation
template<typename endpoint_type > ripple::WSServerHandler< endpoint_type >::WSServerHandler (Resource::Manager & resourceManager, InfoSub::Source & source, boost::asio::ssl::context & ssl_context, bool bPublic, bool bProxy) inline
Definition at line 81 of file WSServerHandler.h.
         : m_resourceManager (resourceManager)
         , m_source (source)
         , m_ssl_context (ssl_context)
         , mPublic (bPublic)
         , mProxy (bProxy)
     {
     }
Member Function Documentation
template<typename endpoint_type > bool ripple::WSServerHandler< endpoint_type >::do_message (Job & job, const connection_ptr & cpClient, const wsc_ptr & conn, const message_ptr & mpMessage) inline
Definition at line 352 of file WSServerHandler.h.
References Json::Value::asString(), Json::Value::isMember(), Json::Value::isNull(), Json::Value::isObject(), Json::Value::isString(), ripple::lsDEBUG, Json::objectValue, Json::Reader::parse(), ripple::Job::rename(), ripple::WSServerHandler< endpoint_type >::send(), ripple::to_string(), and WriteLog.
Referenced by ripple::WSServerHandler< endpoint_type >::do_messages().
     {
         Json::Value     jvRequest;
         Json::Reader    jrReader;
         try
         {
             WriteLog (lsDEBUG, WSServerHandlerLog) <<
                 "Ws:: Receiving(" << to_string (cpClient->get_socket ().remote_endpoint ()) <<
                 ") '" << mpMessage->get_payload () << "'";
         }
         catch (...)
         {
         }
         if (mpMessage->get_opcode () != websocketpp::frame::opcode::TEXT)
         {
             Json::Value jvResult (Json::objectValue);
             jvResult["type"]    = "error";
             jvResult["error"]   = "wsTextRequired"; // We only accept text messages.
             send (cpClient, jvResult, false);
         }
         else if (!jrReader.parse (mpMessage->get_payload (), jvRequest) || jvRequest.isNull () || !jvRequest.isObject ())
         {
             Json::Value jvResult (Json::objectValue);
             jvResult["type"]    = "error";
             jvResult["error"]   = "jsonInvalid";    // Received invalid json.
             jvResult["value"]   = mpMessage->get_payload ();
             send (cpClient, jvResult, false);
         }
         else
         {
             if (jvRequest.isMember ("command"))
             {
                 Json::Value& jCmd = jvRequest["command"];
                 if (jCmd.isString())
                     job.rename (std::string ("WSClient::") + jCmd.asString());
             }
             send (cpClient, conn->invokeCommand (jvRequest), false);
         }
         return true;
     }
template<typename endpoint_type > void ripple::WSServerHandler< endpoint_type >::do_messages (Job & job, connection_ptr cpClient) inline
Definition at line 316 of file WSServerHandler.h.
References ripple::JobQueue::addJob(), BIND_TYPE, ripple::WSServerHandler< endpoint_type >::do_message(), ripple::getApp(), ripple::Application::getJobQueue(), ripple::jtCLIENT, ripple::WSServerHandler< endpoint_type >::mLock, ripple::WSServerHandler< endpoint_type >::mMap, and P_1.
     {
         wsc_ptr ptr;
         {
             ScopedLockType   sl (mLock);
             typename ripple::unordered_map<connection_ptr, wsc_ptr>::iterator it = mMap.find (cpClient);
             if (it == mMap.end ())
                 return;
             ptr = it->second;
         }
         // This loop prevents a single thread from handling more
         // than 3 operations for the same client, otherwise a client
         // can monopolize resources.
         //
         for (int i = 0; i < 3; ++i)
         {
             message_ptr msg = ptr->getMessage ();
             if (!msg)
                 return;
             if (!do_message (job, cpClient, ptr, msg))
             {
                 ptr->returnMessage(msg);
                 return;
             }
         }
         if (ptr->checkMessage ())
             getApp().getJobQueue ().addJob (jtCLIENT, "WSClient::more",
                                        BIND_TYPE (&WSServerHandler<endpoint_type>::do_messages, this, P_1, cpClient));
     }
template<typename endpoint_type > void ripple::WSServerHandler< endpoint_type >::doClose (connection_ptr const & cpClient, char const * reason) inline
Definition at line 241 of file WSServerHandler.h.
References ripple::JobQueue::addJob(), BIND_TYPE, ripple::getApp(), ripple::Application::getJobQueue(), ripple::jtCLIENT, ripple::lsDEBUG, ripple::WSServerHandler< endpoint_type >::mLock, ripple::WSServerHandler< endpoint_type >::mMap, and WriteLog.
Referenced by ripple::WSServerHandler< endpoint_type >::on_close(), and ripple::WSServerHandler< endpoint_type >::on_fail().
     {
         // we cannot destroy the connection while holding the map lock or we deadlock with pubLedger
         wsc_ptr ptr;
         {
             ScopedLockType   sl (mLock);
             typename ripple::unordered_map<connection_ptr, wsc_ptr>::iterator it = mMap.find (cpClient);
             if (it == mMap.end ())
             {
                 try
                 {
                     WriteLog (lsDEBUG, WSServerHandlerLog) <<
                         "Ws:: " << reason << "(" <<
                            cpClient->get_socket ().remote_endpoint ().to_string () << ") not found";
                 }
                 catch (...)
                 {
                 }
                 return;
             }
             ptr = it->second;       // prevent the WSConnection from being destroyed until we release the lock
             mMap.erase (it);
         }
         ptr->preDestroy (); // Must be done before we return
         try
         {
             WriteLog (lsDEBUG, WSServerHandlerLog) <<
                 "Ws:: " << reason << "(" <<
                    cpClient->get_socket ().remote_endpoint ().to_string () << ") found";
         }
         catch (...)
         {
         }
         // Must be done without holding the websocket send lock
         getApp().getJobQueue ().addJob (jtCLIENT, "WSClient::destroy",
                                        BIND_TYPE (&WSConnectionType <endpoint_type>::destroy, ptr));
     }
template<typename endpoint_type > bool ripple::WSServerHandler< endpoint_type >::get_proxy () inline
Definition at line 405 of file WSServerHandler.h.
References ripple::WSServerHandler< endpoint_type >::mProxy.
     {
         return mProxy;
     }
template<typename endpoint_type > boost::asio::ssl::context& ripple::WSServerHandler< endpoint_type >::get_ssl_context () inline
Definition at line 401 of file WSServerHandler.h.
References ripple::WSServerHandler< endpoint_type >::m_ssl_context.
     {
         return m_ssl_context;
     }
template<typename endpoint_type > bool ripple::WSServerHandler< endpoint_type >::getPublic () inline
Definition at line 91 of file WSServerHandler.h.
References ripple::WSServerHandler< endpoint_type >::mPublic.
     {
         return mPublic;
     };
template<typename endpoint_type > bool ripple::WSServerHandler< endpoint_type >::http (connection_ptr cpClient) inline
Definition at line 411 of file WSServerHandler.h.
References ripple::serverOkay(), and SYSTEM_NAME.
     {
         std::string reason;
         if (!serverOkay (reason))
         {
             cpClient->set_body (std::string ("<HTML><BODY>Server cannot accept clients: ") + reason + "</BODY></HTML>");
             return false;
         }
         cpClient->set_body (
             "<!DOCTYPE html><html><head><title>" SYSTEM_NAME " Test</title></head>"
             "<body><h1>" SYSTEM_NAME " Test</h1><p>This page shows http(s) connectivity is working.</p></body></html>");
         return true;
     }
template<typename endpoint_type > void ripple::WSServerHandler< endpoint_type >::on_close (connection_ptr cpClient) inline
Definition at line 231 of file WSServerHandler.h.
References ripple::WSServerHandler< endpoint_type >::doClose().
     {
         doClose (cpClient, "on_close");
     }
template<typename endpoint_type > void ripple::WSServerHandler< endpoint_type >::on_fail (connection_ptr cpClient) inline
Definition at line 236 of file WSServerHandler.h.
References ripple::WSServerHandler< endpoint_type >::doClose().
     {
         doClose (cpClient, "on_fail");
     }
template<typename endpoint_type > void ripple::WSServerHandler< endpoint_type >::on_message (connection_ptr cpClient, message_ptr mpMessage) inline
Definition at line 282 of file WSServerHandler.h.
References ripple::JobQueue::addJob(), BIND_TYPE, ripple::getApp(), ripple::Application::getJobQueue(), ripple::jtCLIENT, ripple::lsDEBUG, ripple::WSServerHandler< endpoint_type >::mLock, ripple::WSServerHandler< endpoint_type >::mMap, P_1, ripple::to_string(), and WriteLog.
     {
         wsc_ptr ptr;
         {
             ScopedLockType   sl (mLock);
             typename ripple::unordered_map<connection_ptr, wsc_ptr>::iterator it = mMap.find (cpClient);
             if (it == mMap.end ())
                 return;
             ptr = it->second;
         }
         bool bRejected, bRunQ;
         ptr->rcvMessage (mpMessage, bRejected, bRunQ);
         if (bRejected)
         {
             try
             {
                 WriteLog (lsDEBUG, WSServerHandlerLog) <<
                     "Ws:: Rejected(" << to_string (cpClient->get_socket ().remote_endpoint ()) <<
                     ") '" << mpMessage->get_payload () << "'";
             }
             catch (...)
             {
             }
         }
         if (bRunQ)
             getApp().getJobQueue ().addJob (jtCLIENT, "WSClient::command",
                       BIND_TYPE (&WSServerHandler<endpoint_type>::do_messages, this, P_1, cpClient));
     }
template<typename endpoint_type > void ripple::WSServerHandler< endpoint_type >::on_open (connection_ptr cpClient) inline
Definition at line 189 of file WSServerHandler.h.
References ripple::lsDEBUG, ripple::WSServerHandler< endpoint_type >::m_resourceManager, ripple::WSServerHandler< endpoint_type >::m_source, ripple::WSServerHandler< endpoint_type >::mLock, ripple::WSServerHandler< endpoint_type >::mMap, and WriteLog.
     {
         ScopedLockType   sl (mLock);
         try
         {
             std::pair <typename MapType::iterator, bool> const result (
                 mMap.emplace (cpClient,
                     boost::make_shared < WSConnectionType <endpoint_type> > (boost::ref(m_resourceManager),
                     boost::ref (m_source), boost::ref(*this), boost::cref(cpClient))));
             assert (result.second);
             WriteLog (lsDEBUG, WSServerHandlerLog) <<
                 "Ws:: on_open(" << cpClient->get_socket ().remote_endpoint ().to_string () << ")";
         }
         catch (...)
         {
         }
     }
template<typename endpoint_type > void ripple::WSServerHandler< endpoint_type >::on_pong (connection_ptr cpClient, std::string data) inline
Definition at line 208 of file WSServerHandler.h.
References ripple::lsDEBUG, ripple::WSServerHandler< endpoint_type >::mLock, ripple::WSServerHandler< endpoint_type >::mMap, and WriteLog.
     {
         wsc_ptr ptr;
         {
             ScopedLockType   sl (mLock);
             typename ripple::unordered_map<connection_ptr, wsc_ptr>::iterator it = mMap.find (cpClient);
             if (it == mMap.end ())
                 return;
             ptr = it->second;
         }
         try
         {
             WriteLog (lsDEBUG, WSServerHandlerLog) <<
            "Ws:: on_pong(" << cpClient->get_socket ().remote_endpoint ().to_string () << ")";
         }
         catch (...)
         {
         }
         ptr->onPong (data);
     }
template<typename endpoint_type > void ripple::WSServerHandler< endpoint_type >::on_send_empty (connection_ptr cpClient) inline
Definition at line 173 of file WSServerHandler.h.
References ripple::WSServerHandler< endpoint_type >::mLock, and ripple::WSServerHandler< endpoint_type >::mMap.
     {
         wsc_ptr ptr;
         {
             ScopedLockType sl (mLock);
             typename ripple::unordered_map<connection_ptr, wsc_ptr>::iterator it = mMap.find (cpClient);
             if (it == mMap.end ())
                 return;
             ptr = it->second;
         }
         ptr->onSendEmpty ();
     }
template<typename endpoint_type > void ripple::WSServerHandler< endpoint_type >::pingTimer (connection_ptr cpClient) inline
Definition at line 143 of file WSServerHandler.h.
References ripple::lsDEBUG, ripple::WSServerHandler< endpoint_type >::mLock, ripple::WSServerHandler< endpoint_type >::mMap, and WriteLog.
Referenced by ripple::WSConnectionType< endpoint_type >::pingTimer().
     {
         wsc_ptr ptr;
         {
             ScopedLockType sl (mLock);
             typename ripple::unordered_map<connection_ptr, wsc_ptr>::iterator it = mMap.find (cpClient);
             if (it == mMap.end ())
                 return;
             ptr = it->second;
         }
         std::string data ("ping");
         if (ptr->onPingTimer (data))
         {
             cpClient->terminate (false);
             try
             {
                 WriteLog (lsDEBUG, WSServerHandlerLog) <<
                     "Ws:: ping_out(" << cpClient->get_socket ().remote_endpoint ().to_string () << ")";
             }
             catch (...)
             {
             }
         }
         else
             cpClient->ping (data);
     }
template<typename endpoint_type > void ripple::WSServerHandler< endpoint_type >::send (connection_ptr cpClient, message_ptr mpMessage) inline
Definition at line 122 of file WSServerHandler.h.
References BIND_TYPE.
Referenced by ripple::WSServerHandler< endpoint_type >::do_message(), ripple::WSConnectionType< endpoint_type >::send(), and ripple::WSServerHandler< endpoint_type >::send().
     {
         cpClient->get_strand ().post (BIND_TYPE (
                                           &WSServerHandler<endpoint_type>::ssend, cpClient, mpMessage));
     }
template<typename endpoint_type > void ripple::WSServerHandler< endpoint_type >::send (connection_ptr cpClient, const std::string & strMessage, bool broadcast) inline
Definition at line 128 of file WSServerHandler.h.
References BIND_TYPE.
     {
         cpClient->get_strand ().post (BIND_TYPE (
                                           &WSServerHandler<endpoint_type>::ssendb, cpClient, strMessage, broadcast));
     }
template<typename endpoint_type > void ripple::WSServerHandler< endpoint_type >::send (connection_ptr cpClient, const Json::Value & jvObj, bool broadcast) inline
Definition at line 134 of file WSServerHandler.h.
References ripple::WSServerHandler< endpoint_type >::send(), and Json::FastWriter::write().
     {
         Json::FastWriter    jfwWriter;
         // WriteLog (lsDEBUG, WSServerHandlerLog) << "Ws:: Object '" << jfwWriter.write(jvObj) << "'";
         send (cpClient, jfwWriter.write (jvObj), broadcast);
     }
template<typename endpoint_type > static void ripple::WSServerHandler< endpoint_type >::ssend (connection_ptr cpClient, message_ptr mpMessage) inline static
Definition at line 96 of file WSServerHandler.h.
References ripple::WSServerHandler< endpoint_type >::crTooSlow, and value.
     {
         try
         {
             cpClient->send (mpMessage->get_payload (), mpMessage->get_opcode ());
         }
         catch (...)
         {
             cpClient->close (websocketpp::close::status::value (crTooSlow), std::string ("Client is too slow."));
         }
     }
template<typename endpoint_type > static void ripple::WSServerHandler< endpoint_type >::ssendb (connection_ptr cpClient, const std::string & strMessage, bool broadcast) inline static
Definition at line 108 of file WSServerHandler.h.
References ripple::WSServerHandler< endpoint_type >::crTooSlow, ripple::lsDEBUG, ripple::lsTRACE, value, and WriteLog.
     {
         try
         {
             WriteLog (broadcast ? lsTRACE : lsDEBUG, WSServerHandlerLog) << "Ws:: Sending '" << strMessage << "'";
             cpClient->send (strMessage);
         }
         catch (...)
         {
             cpClient->close (websocketpp::close::status::value (crTooSlow), std::string ("Client is too slow."));
         }
     }
Member Data Documentation
template<typename endpoint_type > Resource::Manager& ripple::WSServerHandler< endpoint_type >::m_resourceManager private
Definition at line 60 of file WSServerHandler.h.
Referenced by ripple::WSServerHandler< endpoint_type >::on_open().
template<typename endpoint_type > InfoSub::Source& ripple::WSServerHandler< endpoint_type >::m_source private
Definition at line 61 of file WSServerHandler.h.
Referenced by ripple::WSServerHandler< endpoint_type >::on_open().
template<typename endpoint_type > boost::asio::ssl::context& ripple::WSServerHandler< endpoint_type >::m_ssl_context private
Definition at line 70 of file WSServerHandler.h.
Referenced by ripple::WSServerHandler< endpoint_type >::get_ssl_context().
template<typename endpoint_type > LockType ripple::WSServerHandler< endpoint_type >::mLock protected
Definition at line 67 of file WSServerHandler.h.
Referenced by ripple::WSServerHandler< endpoint_type >::do_messages(), ripple::WSServerHandler< endpoint_type >::doClose(), ripple::WSServerHandler< endpoint_type >::on_message(), ripple::WSServerHandler< endpoint_type >::on_open(), ripple::WSServerHandler< endpoint_type >::on_pong(), ripple::WSServerHandler< endpoint_type >::on_send_empty(), and ripple::WSServerHandler< endpoint_type >::pingTimer().
template<typename endpoint_type > MapType ripple::WSServerHandler< endpoint_type >::mMap protected
Definition at line 76 of file WSServerHandler.h.
Referenced by ripple::WSServerHandler< endpoint_type >::do_messages(), ripple::WSServerHandler< endpoint_type >::doClose(), ripple::WSServerHandler< endpoint_type >::on_message(), ripple::WSServerHandler< endpoint_type >::on_open(), ripple::WSServerHandler< endpoint_type >::on_pong(), ripple::WSServerHandler< endpoint_type >::on_send_empty(), and ripple::WSServerHandler< endpoint_type >::pingTimer().
template<typename endpoint_type > bool const ripple::WSServerHandler< endpoint_type >::mProxy protected
Definition at line 78 of file WSServerHandler.h.
Referenced by ripple::WSServerHandler< endpoint_type >::get_proxy().
template<typename endpoint_type > bool const ripple::WSServerHandler< endpoint_type >::mPublic protected
Definition at line 77 of file WSServerHandler.h.
Referenced by ripple::WSServerHandler< endpoint_type >::getPublic().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/websocket/WSConnection.h
rippled/src/ripple_app/websocket/WSServerHandler.h