rippled: ripple::CanonicalTXSet Class Reference
ripple::CanonicalTXSet Class Reference
#include <CanonicalTXSet.h>
Classes
class Key
Public Types
typedef std::map< Key,
SerializedTransaction::pointer >
::iterator iterator
typedef std::map< Key,
SerializedTransaction::pointer >
::const_iterator const_iterator
Public Member Functions
CanonicalTXSet (LedgerHash const &lastClosedLedgerHash)
void push_back (SerializedTransaction::ref txn)
void reset (LedgerHash const &newLastClosedLedgerHash)
iterator erase (iterator const &it)
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
size_t size () const
bool empty () const
Private Attributes
uint256 mSetHash
std::map< Key,
SerializedTransaction::pointer > mMap
Detailed Description
Holds transactions which were deferred to the next pass of consensus.
"Canonical" refers to the order in which transactions are applied.
Puts transactions from the same account in sequence order
Definition at line 33 of file CanonicalTXSet.h.
Member Typedef Documentation
typedef std::map<Key, SerializedTransaction::pointer>::const_iterator ripple::CanonicalTXSet::const_iterator
Definition at line 72 of file CanonicalTXSet.h.
typedef std::map<Key, SerializedTransaction::pointer>::iterator ripple::CanonicalTXSet::iterator
Definition at line 71 of file CanonicalTXSet.h.
Constructor & Destructor Documentation
ripple::CanonicalTXSet::CanonicalTXSet (LedgerHash const & lastClosedLedgerHash) inline explicit
Definition at line 75 of file CanonicalTXSet.h.
         : mSetHash (lastClosedLedgerHash)
     {
     }
Member Function Documentation
iterator ripple::CanonicalTXSet::begin () inline
Definition at line 92 of file CanonicalTXSet.h.
References mMap.
Referenced by ripple::LedgerConsensusImp::applyTransactions(), and ripple::LedgerMasterImp::closeLedger().
     {
         return mMap.begin ();
     }
const_iterator ripple::CanonicalTXSet::begin () const inline
Definition at line 100 of file CanonicalTXSet.h.
References mMap.
     {
         return mMap.begin ();
     }
bool ripple::CanonicalTXSet::empty () const inline
Definition at line 112 of file CanonicalTXSet.h.
References mMap.
     {
         return mMap.empty ();
     }
iterator ripple::CanonicalTXSet::end () inline
Definition at line 96 of file CanonicalTXSet.h.
References mMap.
Referenced by ripple::LedgerConsensusImp::applyTransactions(), and ripple::LedgerMasterImp::closeLedger().
     {
         return mMap.end ();
     }
const_iterator ripple::CanonicalTXSet::end () const inline
Definition at line 104 of file CanonicalTXSet.h.
References mMap.
     {
         return mMap.end ();
     }
CanonicalTXSet::iterator ripple::CanonicalTXSet::erase (iterator const & it)
Definition at line 85 of file CanonicalTXSet.cpp.
References mMap.
Referenced by ripple::LedgerConsensusImp::applyTransactions().
 {
     iterator tmp = it;
     ++tmp;
     mMap.erase (it);
     return tmp;
 }
void ripple::CanonicalTXSet::push_back (SerializedTransaction::ref txn)
Definition at line 74 of file CanonicalTXSet.cpp.
References mMap, and mSetHash.
Referenced by ripple::LedgerMasterImp::addHeldTransaction(), and ripple::LedgerConsensusImp::applyTransactions().
 {
     uint256 effectiveAccount = mSetHash;
     effectiveAccount ^= txn->getSourceAccount ().getAccountID ().to256 ();
     mMap.insert (std::make_pair (
                      Key (effectiveAccount, txn->getSequence (), txn->getTransactionID ()),
                      txn));
 }
void ripple::CanonicalTXSet::reset (LedgerHash const & newLastClosedLedgerHash) inline
Definition at line 83 of file CanonicalTXSet.h.
References mMap, and mSetHash.
Referenced by ripple::LedgerMasterImp::closeLedger().
     {
         mSetHash = newLastClosedLedgerHash;
         mMap.clear ();
     }
size_t ripple::CanonicalTXSet::size () const inline
Definition at line 108 of file CanonicalTXSet.h.
References mMap.
Referenced by ripple::LedgerConsensusImp::applyTransactions().
     {
         return mMap.size ();
     }
Member Data Documentation
std::map<Key, SerializedTransaction::pointer> ripple::CanonicalTXSet::mMap private
Definition at line 121 of file CanonicalTXSet.h.
Referenced by begin(), empty(), end(), erase(), push_back(), reset(), and size().
uint256 ripple::CanonicalTXSet::mSetHash private
Definition at line 119 of file CanonicalTXSet.h.
Referenced by push_back(), and reset().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/misc/CanonicalTXSet.h
rippled/src/ripple_app/misc/CanonicalTXSet.cpp