rippled: beast::asio::wrap_handler_test Class Reference
beast::asio::wrap_handler_test Class Reference
Classes
struct test_handler
struct test_invokable
struct test_results
Public Member Functions
template<class Handler >
bool async_op (Handler &&handler)
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 122 of file wrap_handler.test.cpp.
Member Function Documentation
template<class Handler > bool beast::asio::wrap_handler_test::async_op (Handler && handler) inline
Definition at line 210 of file wrap_handler.test.cpp.
Referenced by run().
     {
         void* const p (boost_asio_handler_alloc_helpers::allocate (32, handler));
         (handler)();
         boost_asio_handler_alloc_helpers::deallocate (p, 32, handler);
         return boost_asio_handler_cont_helpers::is_continuation (handler);
     }
void beast::asio::wrap_handler_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 218 of file wrap_handler.test.cpp.
References beast::asio::wrap_handler_test::test_results::alloc, async_op(), beast::asio::wrap_handler_test::test_results::call, beast::asio::wrap_handler_test::test_invokable::call, beast::asio::wrap_handler_test::test_results::cont, beast::asio::wrap_handler_test::test_results::dealloc, beast::unit_test::suite::expect(), ripple::f, beast::asio::wrap_handler_test::test_results::invoke, beast::unit_test::suite::unexpected(), and beast::asio::wrap_handler().
     {
         // Hooks called when using the raw handler
         {
             test_results r;
             test_handler h (r);
             async_op (h);
             expect (r.call);
             expect (r.alloc);
             expect (r.dealloc);
             expect (r.cont);
             test_invokable f;
             boost_asio_handler_invoke_helpers::invoke (std::ref (f), h);
             expect (r.invoke);
             expect (f.call);
         }
         // Use of boost::bind shows the hooks not getting called
         {
             test_results r;
             test_handler h (r);
             auto b (std::bind (&test_handler::operator(), &h));
             async_op (b);
             expect (r.call);
             unexpected (r.alloc);
             unexpected (r.dealloc);
             unexpected (r.cont);
             test_invokable f;
             boost_asio_handler_invoke_helpers::invoke (std::ref (f), b);
             unexpected (r.invoke);
             expect (f.call);
         }
         // Make sure the wrapped handler calls the hooks
         {
             test_results r;
             test_handler h (r);
             auto w (wrap_handler (
                 std::bind (&test_handler::operator(), test_handler(r)), h));
             async_op (w);
             expect (r.call);
             expect (r.alloc);
             expect (r.dealloc);
             expect (r.cont);
             test_invokable f;
             boost_asio_handler_invoke_helpers::invoke (std::ref (f), w);
             expect (r.invoke);
             expect (f.call);
         }
     }
The documentation for this class was generated from the following file:
rippled/src/beast/beast/asio/tests/wrap_handler.test.cpp