rippled: ripple::NodeStoreScheduler Class Reference
ripple::NodeStoreScheduler Class Reference
#include <NodeStoreScheduler.h>
Public Member Functions
NodeStoreScheduler (Stoppable &parent)
void setJobQueue (JobQueue &jobQueue)
void onStop ()
void onChildrenStopped ()
void scheduleTask (NodeStore::Task &task)
Public Member Functions inherited from ripple::NodeStore::Scheduler
virtual ~Scheduler ()=0
Public Member Functions inherited from beast::Stoppable
Stoppable (char const *name, Stoppable &parent)
virtual ~Stoppable ()
bool isStopping () const
bool isStopped () const
bool areChildrenStopped () const
void stopped ()
virtual void onPrepare ()
virtual void onStart ()
Private Member Functions
void doTask (NodeStore::Task &task, Job &)
Private Attributes
JobQueue * m_jobQueue
std::atomic< int > m_taskCount
Additional Inherited Members
Protected Member Functions inherited from beast::Stoppable
Stoppable (char const *name, RootStoppable &root)
Protected Attributes inherited from beast::Stoppable
char const * m_name
RootStoppable & m_root
Child m_child
Atomic< int > m_started
bool volatile m_stopped
bool volatile m_childrenStopped
Children m_children
WaitableEvent m_stoppedEvent
Detailed Description
A NodeStore::Scheduler which uses the JobQueue and implements the Stoppable API.
Definition at line 26 of file NodeStoreScheduler.h.
Constructor & Destructor Documentation
ripple::NodeStoreScheduler::NodeStoreScheduler (Stoppable & parent)
Definition at line 22 of file NodeStoreScheduler.cpp.
     : Stoppable ("NodeStoreScheduler", parent)
     , m_jobQueue (nullptr)
     , m_taskCount (0)
 {
 }
Member Function Documentation
void ripple::NodeStoreScheduler::doTask (NodeStore::Task & task, Job &) private
Definition at line 54 of file NodeStoreScheduler.cpp.
References beast::Stoppable::isStopping(), m_taskCount, ripple::NodeStore::Task::performScheduledTask(), and beast::Stoppable::stopped().
Referenced by scheduleTask().
 {
     task.performScheduledTask ();
     if ((--m_taskCount == 0) && isStopping())
         stopped();
 }
void ripple::NodeStoreScheduler::onChildrenStopped () virtual
Override called when all children have stopped.
The call is made on an unspecified, implementation-specific thread. onStop and onChildrenStopped will never be called concurrently, across all Stoppable objects descended from the same root, inclusive of the root.
It is safe to call isStopping, isStopped, and areChildrenStopped from within this function; The values returned will always be valid and never change during the callback.
The default implementation does nothing.
Thread safety: May not block for long periods. Guaranteed only to be called once. Must be safe to call from any thread at any time.
Reimplemented from beast::Stoppable.
Definition at line 38 of file NodeStoreScheduler.cpp.
References bassert, m_taskCount, and beast::Stoppable::stopped().
 {
     bassert (m_taskCount == 0);
     stopped ();
 }
void ripple::NodeStoreScheduler::onStop () virtual
Override called when the stop notification is issued.
The call is made on an unspecified, implementation-specific thread. onStop and onChildrenStopped will never be called concurrently, across all Stoppable objects descended from the same root, inclusive of the root.
It is safe to call isStopping, isStopped, and areChildrenStopped from within this function; The values returned will always be valid and never change during the callback.
The default implementation simply calls stopped(). This is applicable when the Stoppable has a trivial stop operation (or no stop operation), and we are merely using the Stoppable API to position it as a dependency of some parent service.
Thread safety: May not block for long periods. Guaranteed only to be called once. Must be safe to call from any thread at any time.
Reimplemented from beast::Stoppable.
Definition at line 34 of file NodeStoreScheduler.cpp.
 {
 }
void ripple::NodeStoreScheduler::scheduleTask (NodeStore::Task & task) virtual
Schedules a task. Depending on the implementation, the task may be invoked either on the current thread of execution, or an unspecified implementation-defined foreign thread.
Implements ripple::NodeStore::Scheduler.
Definition at line 44 of file NodeStoreScheduler.cpp.
References ripple::JobQueue::addJob(), BIND_TYPE, doTask(), ripple::jtWRITE, m_jobQueue, m_taskCount, and P_1.
 {
     ++m_taskCount;
     m_jobQueue->addJob (
         jtWRITE,
         "NodeObject::store",
         BIND_TYPE (&NodeStoreScheduler::doTask,
             this, boost::ref(task), P_1));
 }
void ripple::NodeStoreScheduler::setJobQueue (JobQueue & jobQueue)
Definition at line 29 of file NodeStoreScheduler.cpp.
References m_jobQueue.
Referenced by ripple::ApplicationImp::ApplicationImp().
 {
     m_jobQueue = &jobQueue;
 }
Member Data Documentation
JobQueue* ripple::NodeStoreScheduler::m_jobQueue private
Definition at line 45 of file NodeStoreScheduler.h.
Referenced by scheduleTask(), and setJobQueue().
std::atomic<int> ripple::NodeStoreScheduler::m_taskCount private
Definition at line 46 of file NodeStoreScheduler.h.
Referenced by doTask(), onChildrenStopped(), and scheduleTask().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/main/NodeStoreScheduler.h
rippled/src/ripple_app/main/NodeStoreScheduler.cpp