rippled: ripple::RPC::JSONRPC_test Class Reference
ripple::RPC::JSONRPC_test Class Reference
Public Member Functions
void testAutoFillFees ()
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 499 of file TransactionSign.cpp.
Member Function Documentation
void ripple::RPC::JSONRPC_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 534 of file TransactionSign.cpp.
References testAutoFillFees().
     {
         testAutoFillFees ();
     }
void ripple::RPC::JSONRPC_test::testAutoFillFees () inline
Definition at line 502 of file TransactionSign.cpp.
References ripple::RPC::autofill_fee(), ripple::RPC::contains_error(), ripple::RippleAddress::createAccountPublic(), ripple::RippleAddress::createGeneratorPublic(), ripple::RippleAddress::createSeedGeneric(), beast::unit_test::suite::expect(), and Json::Reader::parse().
Referenced by run().
     {
         RippleAddress rootSeedMaster      = RippleAddress::createSeedGeneric ("masterpassphrase");
         RippleAddress rootGeneratorMaster = RippleAddress::createGeneratorPublic (rootSeedMaster);
         RippleAddress rootAddress         = RippleAddress::createAccountPublic (rootGeneratorMaster, 0);
         std::uint64_t startAmount (100000);
         Ledger::pointer ledger (boost::make_shared <Ledger> (
             rootAddress, startAmount));
         {
             Json::Value req;
             Json::Value result;
             Json::Reader ().parse (
                 "{ \"fee_mult_max\" : 1, \"tx_json\" : { } } "
                 , req);
             autofill_fee (req, ledger, result, true);
             expect (! contains_error (result));
         }
         {
             Json::Value req;
             Json::Value result;
             Json::Reader ().parse (
                 "{ \"fee_mult_max\" : 0, \"tx_json\" : { } } "
                 , req);
             autofill_fee (req, ledger, result, true);
             expect (contains_error (result));
         }
     }
The documentation for this class was generated from the following file:
rippled/src/ripple_rpc/impl/TransactionSign.cpp