rippled: beast::asio::HandshakeDetectLogicSSL2 Class Reference
beast::asio::HandshakeDetectLogicSSL2 Class Reference
#include <HandshakeDetectLogicSSL2.h>
Public Types
enum { bytesNeeded = 3 }
typedef int arg_type
Public Member Functions
HandshakeDetectLogicSSL2 (arg_type const &)
std::size_t max_needed ()
std::size_t bytes_consumed ()
template<typename ConstBufferSequence >
void analyze (ConstBufferSequence const &buffer)
Public Member Functions inherited from beast::asio::HandshakeDetectLogic
HandshakeDetectLogic ()
bool finished () const noexcept
bool success () const noexcept
Additional Inherited Members
Protected Member Functions inherited from beast::asio::HandshakeDetectLogic
void conclude (bool success=true)
void fail ()
Detailed Description
Definition at line 40 of file HandshakeDetectLogicSSL2.h.
Member Typedef Documentation
typedef int beast::asio::HandshakeDetectLogicSSL2::arg_type
Definition at line 43 of file HandshakeDetectLogicSSL2.h.
Member Enumeration Documentation
anonymous enum
Enumerator
bytesNeeded
Definition at line 49 of file HandshakeDetectLogicSSL2.h.
     {
         bytesNeeded = 3
     };
Constructor & Destructor Documentation
beast::asio::HandshakeDetectLogicSSL2::HandshakeDetectLogicSSL2 (arg_type const &) inline explicit
Definition at line 45 of file HandshakeDetectLogicSSL2.h.
     {
     }
Member Function Documentation
template<typename ConstBufferSequence > void beast::asio::HandshakeDetectLogicSSL2::analyze (ConstBufferSequence const & buffer) inline
Definition at line 65 of file HandshakeDetectLogicSSL2.h.
References beast::asio::HandshakeDetectLogic::conclude(), beast::asio::HandshakeDetectLogic::fail(), Json::in(), beast::asio::FixedInputBuffer::peek(), beast::asio::FixedInputBuffer::read(), and beast::asio::FixedInputBuffer::readNetworkInteger().
     {
         FixedInputBufferSize <bytesNeeded> in (buffer);
         {
             std::uint8_t byte;
             if (! in.peek (&byte))
                 return;
             // First byte must have the high bit set
             //
             if((byte & 0x80) != 0x80)
             return fail ();
         }
         // The remaining bits contain the
         // length of the following data in bytes.
         //
         std::uint16_t msg_length;
         if (! in.readNetworkInteger(&msg_length))
             return;
         // sizeof (msg_type +
         //         Version (ProtcolVersion?) +
         //         cipher_spec_length +
         //         session_id_length +
         //         challenge_length)
         //
         // Should be 9 or greater.
         //
         if (msg_length < 9)
             return fail ();
         std::uint8_t msg_type;
         if (! in.read (&msg_type))
             return;
         // The msg_type must be 0x01 for a version 2 ClientHello
         //
         if (msg_type != 0x01)
             return fail ();
         conclude ();
     }
std::size_t beast::asio::HandshakeDetectLogicSSL2::bytes_consumed () inline virtual
How many bytes the handshake consumes. If the detector processes the entire handshake this will be non zero. The SSL detector would return 0, since we want all the existing bytes to be passed on.
Implements beast::asio::HandshakeDetectLogic.
Definition at line 59 of file HandshakeDetectLogicSSL2.h.
     {
         return 0;
     }
std::size_t beast::asio::HandshakeDetectLogicSSL2::max_needed () inline virtual
How many bytes maximum we might need.
This is the largest number of bytes that the detector might need in order to come to a conclusion about whether or not the handshake is a match. Depending on the data, it could come to that conclusion sooner though.
Use read_some instead of read so that the detect logic can reject the handshake sooner if possible.
Implements beast::asio::HandshakeDetectLogic.
Definition at line 54 of file HandshakeDetectLogicSSL2.h.
References bytesNeeded.
     {
         return bytesNeeded;
     }
The documentation for this class was generated from the following file:
rippled/src/beast/modules/beast_asio/protocol/HandshakeDetectLogicSSL2.h