rippled: ripple::Script::Interpreter Class Reference
ripple::Script::Interpreter Class Reference
#include <Interpreter.h>
Public Types
enum {
INT_OP = 1, FLOAT_OP, UINT160_OP, BOOL_OP,
PATH_OP, ADD_OP, SUB_OP, MUL_OP,
DIV_OP, MOD_OP, GTR_OP, LESS_OP,
EQUAL_OP, NOT_EQUAL_OP, AND_OP, OR_OP,
NOT_OP, JUMP_OP, JUMPIF_OP, STOP_OP,
CANCEL_OP, BLOCK_OP, BLOCK_END_OP, SEND_XRP_OP,
SEND_OP, REMOVE_CONTRACT_OP, FEE_OP, CHANGE_CONTRACT_OWNER_OP,
STOP_REMOVE_OP, SET_DATA_OP, GET_DATA_OP, GET_NUM_DATA_OP,
SET_REGISTER_OP, GET_REGISTER_OP, GET_ISSUER_ID_OP, GET_OWNER_ID_OP,
GET_LEDGER_TIME_OP, GET_LEDGER_NUM_OP, GET_RAND_FLOAT_OP, GET_XRP_ESCROWED_OP,
GET_RIPPLE_ESCROWED_OP, GET_RIPPLE_ESCROWED_CURRENCY_OP, GET_RIPPLE_ESCROWED_ISSUER, GET_ACCEPT_DATA_OP,
GET_ACCEPTOR_ID_OP, GET_CONTRACT_ID_OP, NUM_OF_OPS
}
Public Member Functions
Interpreter ()
TER interpret (Contract *contract, const SerializedTransaction &txn, Blob &code)
void stop ()
bool canSign (const uint160 &signer)
int getInstructionPointer ()
void setInstructionPointer (int n)
Data::pointer popStack ()
void pushStack (Data::pointer data)
bool jumpTo (int offset)
bool startBlock (int offset)
bool endBlock ()
Data::pointer getIntData ()
Data::pointer getFloatData ()
Data::pointer getUint160Data ()
Data::pointer getAcceptData (int index)
Data::pointer getContractData (int index)
Private Attributes
std::vector< Operation * > mFunctionTable
std::vector< Data::pointer > mStack
Contract * mContract
Blob * mCode
unsigned int mInstructionPointer
int mTotalFee
bool mInBlock
int mBlockJump
bool mBlockSuccess
Detailed Description
Definition at line 30 of file Interpreter.h.
Member Enumeration Documentation
anonymous enum
Enumerator
INT_OP
FLOAT_OP
UINT160_OP
BOOL_OP
PATH_OP
ADD_OP
SUB_OP
MUL_OP
DIV_OP
MOD_OP
GTR_OP
LESS_OP
EQUAL_OP
NOT_EQUAL_OP
AND_OP
OR_OP
NOT_OP
JUMP_OP
JUMPIF_OP
STOP_OP
CANCEL_OP
BLOCK_OP
BLOCK_END_OP
SEND_XRP_OP
SEND_OP
REMOVE_CONTRACT_OP
FEE_OP
CHANGE_CONTRACT_OWNER_OP
STOP_REMOVE_OP
SET_DATA_OP
GET_DATA_OP
GET_NUM_DATA_OP
SET_REGISTER_OP
GET_REGISTER_OP
GET_ISSUER_ID_OP
GET_OWNER_ID_OP
GET_LEDGER_TIME_OP
GET_LEDGER_NUM_OP
GET_RAND_FLOAT_OP
GET_XRP_ESCROWED_OP
GET_RIPPLE_ESCROWED_OP
GET_RIPPLE_ESCROWED_CURRENCY_OP
GET_RIPPLE_ESCROWED_ISSUER
GET_ACCEPT_DATA_OP
GET_ACCEPTOR_ID_OP
GET_CONTRACT_ID_OP
NUM_OF_OPS
Definition at line 48 of file Interpreter.h.
          {  INT_OP = 1, FLOAT_OP, UINT160_OP, BOOL_OP, PATH_OP,
             ADD_OP, SUB_OP, MUL_OP, DIV_OP, MOD_OP,
             GTR_OP, LESS_OP, EQUAL_OP, NOT_EQUAL_OP,
             AND_OP, OR_OP, NOT_OP,
             JUMP_OP, JUMPIF_OP,
             STOP_OP, CANCEL_OP,
             BLOCK_OP, BLOCK_END_OP,
             SEND_XRP_OP, SEND_OP, REMOVE_CONTRACT_OP, FEE_OP, CHANGE_CONTRACT_OWNER_OP,
             STOP_REMOVE_OP,
             SET_DATA_OP, GET_DATA_OP, GET_NUM_DATA_OP,
             SET_REGISTER_OP, GET_REGISTER_OP,
             GET_ISSUER_ID_OP, GET_OWNER_ID_OP, GET_LEDGER_TIME_OP,  GET_LEDGER_NUM_OP, GET_RAND_FLOAT_OP,
             GET_XRP_ESCROWED_OP, GET_RIPPLE_ESCROWED_OP, GET_RIPPLE_ESCROWED_CURRENCY_OP, GET_RIPPLE_ESCROWED_ISSUER,
             GET_ACCEPT_DATA_OP, GET_ACCEPTOR_ID_OP, GET_CONTRACT_ID_OP,
             NUM_OF_OPS
          };
Constructor & Destructor Documentation
ripple::Script::Interpreter::Interpreter ()
Definition at line 25 of file Interpreter.cpp.
References ADD_OP, AND_OP, BLOCK_END_OP, BLOCK_OP, BOOL_OP, CANCEL_OP, DIV_OP, EQUAL_OP, FLOAT_OP, GTR_OP, INT_OP, JUMP_OP, JUMPIF_OP, LESS_OP, mBlockJump, mBlockSuccess, mCode, mContract, mFunctionTable, mInBlock, mInstructionPointer, MOD_OP, mTotalFee, MUL_OP, NOT_EQUAL_OP, NOT_OP, NUM_OF_OPS, OR_OP, PATH_OP, SEND_XRP_OP, STOP_OP, SUB_OP, and UINT160_OP.
 {
     mContract = nullptr;
     mCode = nullptr;
     mInstructionPointer = 0;
     mTotalFee = 0;
     mInBlock = false;
     mBlockSuccess = true;
     mBlockJump = 0;
     mFunctionTable.resize (NUM_OF_OPS);
     mFunctionTable[INT_OP] = new IntOp ();
     mFunctionTable[FLOAT_OP] = new FloatOp ();
     mFunctionTable[UINT160_OP] = new Uint160Op ();
     mFunctionTable[BOOL_OP] = new Uint160Op ();
     mFunctionTable[PATH_OP] = new Uint160Op ();
     mFunctionTable[ADD_OP] = new AddOp ();
     mFunctionTable[SUB_OP] = new SubOp ();
     mFunctionTable[MUL_OP] = new MulOp ();
     mFunctionTable[DIV_OP] = new DivOp ();
     mFunctionTable[MOD_OP] = new ModOp ();
     mFunctionTable[GTR_OP] = new GtrOp ();
     mFunctionTable[LESS_OP] = new LessOp ();
     mFunctionTable[EQUAL_OP] = new SubOp ();
     mFunctionTable[NOT_EQUAL_OP] = new SubOp ();
     mFunctionTable[AND_OP] = new SubOp ();
     mFunctionTable[OR_OP] = new SubOp ();
     mFunctionTable[NOT_OP] = new SubOp ();
     mFunctionTable[JUMP_OP] = new SubOp ();
     mFunctionTable[JUMPIF_OP] = new SubOp ();
     mFunctionTable[STOP_OP] = new SubOp ();
     mFunctionTable[CANCEL_OP] = new SubOp ();
     mFunctionTable[BLOCK_OP] = new SubOp ();
     mFunctionTable[BLOCK_END_OP] = new SubOp ();
     mFunctionTable[SEND_XRP_OP] = new SendXRPOp ();
     /*
     mFunctionTable[SEND_OP]=new SendOp();
     mFunctionTable[REMOVE_CONTRACT_OP]=new SubOp();
     mFunctionTable[FEE_OP]=new SubOp();
     mFunctionTable[CHANGE_CONTRACT_OWNER_OP]=new SubOp();
     mFunctionTable[STOP_REMOVE_OP]=new SubOp();
     mFunctionTable[SET_DATA_OP]=new SubOp();
     mFunctionTable[GET_DATA_OP]=new SubOp();
     mFunctionTable[GET_NUM_DATA_OP]=new SubOp();
     mFunctionTable[SET_REGISTER_OP]=new SubOp();
     mFunctionTable[GET_REGISTER_OP]=new SubOp();
     mFunctionTable[GET_ISSUER_ID_OP]=new SubOp();
     mFunctionTable[GET_OWNER_ID_OP]=new SubOp();
     mFunctionTable[GET_LEDGER_TIME_OP]=new SubOp();
     mFunctionTable[GET_LEDGER_NUM_OP]=new SubOp();
     mFunctionTable[GET_RAND_FLOAT_OP]=new SubOp();
     mFunctionTable[GET_XRP_ESCROWED_OP]=new SubOp();
     mFunctionTable[GET_RIPPLE_ESCROWED_OP]=new SubOp();
     mFunctionTable[GET_RIPPLE_ESCROWED_CURRENCY_OP]=new SubOp();
     mFunctionTable[GET_RIPPLE_ESCROWED_ISSUER]=new GetRippleEscrowedIssuerOp();
     mFunctionTable[GET_ACCEPT_DATA_OP]=new AcceptDataOp();
     mFunctionTable[GET_ACCEPTOR_ID_OP]=new GetAcceptorIDOp();
     mFunctionTable[GET_CONTRACT_ID_OP]=new GetContractIDOp();
     */
 }
Member Function Documentation
bool ripple::Script::Interpreter::canSign (const uint160 & signer)
Definition at line 221 of file Interpreter.cpp.
Referenced by ripple::Script::SendXRPOp::work().
 {
     return (true);
 }
bool ripple::Script::Interpreter::endBlock ()
Definition at line 121 of file Interpreter.cpp.
References mBlockJump, mBlockSuccess, mInBlock, and pushStack().
Referenced by ripple::Script::EndBlockOp::work().
 {
     if (!mInBlock) return (false);
     mInBlock = false;
     mBlockJump = 0;
     pushStack (Data::pointer (new BoolData (mBlockSuccess)));
     return (true);
 }
Data::pointer ripple::Script::Interpreter::getAcceptData (int index)
Referenced by ripple::Script::AcceptDataOp::work().
Data::pointer ripple::Script::Interpreter::getContractData (int index)
Definition at line 216 of file Interpreter.cpp.
Referenced by ripple::Script::GetDataOp::work().
 {
     return (Data::pointer (new ErrorData ()));
 }
Data::pointer ripple::Script::Interpreter::getFloatData ()
Definition at line 177 of file Interpreter.cpp.
References mInstructionPointer, and value.
Referenced by ripple::Script::FloatOp::work().
 {
     float value = 0; // TODO
     mInstructionPointer += 4;
     return (Data::pointer (new FloatData (value)));
 }
int ripple::Script::Interpreter::getInstructionPointer () inline
Definition at line 75 of file Interpreter.h.
References mInstructionPointer.
     {
         return (mInstructionPointer);
     }
Data::pointer ripple::Script::Interpreter::getIntData ()
Definition at line 170 of file Interpreter.cpp.
References mInstructionPointer, and value.
Referenced by ripple::Script::IntOp::work(), ripple::Script::StartBlockOp::work(), ripple::Script::JumpIfOp::work(), and ripple::Script::JumpOp::work().
 {
     int value = 0; // TODO
     mInstructionPointer += 4;
     return (Data::pointer (new IntData (value)));
 }
Data::pointer ripple::Script::Interpreter::getUint160Data ()
Definition at line 184 of file Interpreter.cpp.
References mInstructionPointer, and value.
Referenced by ripple::Script::Uint160Op::work().
 {
     uint160 value; // TODO
     mInstructionPointer += 20;
     return (Data::pointer (new Uint160Data (value)));
 }
TER ripple::Script::Interpreter::interpret (Contract * contract, const SerializedTransaction & txn, Blob & code)
Definition at line 131 of file Interpreter.cpp.
References ripple::STAmount::getNValue(), ripple::SerializedTransaction::getTransactionFee(), mCode, mContract, mFunctionTable, mInstructionPointer, mTotalFee, ripple::telINSUF_FEE_P, ripple::temMALFORMED, and ripple::tesSUCCESS.
 {
     mContract = contract;
     mCode = &code;
     mTotalFee = 0;
     mInstructionPointer = 0;
     while (mInstructionPointer < code.size ())
     {
         unsigned int fun = (*mCode)[mInstructionPointer];
         mInstructionPointer++;
         if (fun >= mFunctionTable.size ())
         {
             // TODO: log
             return (temMALFORMED); // TODO: is this actually what we want to do?
         }
         mTotalFee += mFunctionTable[ fun ]->getFee (); // FIXME: You can't use fees this way, there's no consensus
         if (mTotalFee > txn.getTransactionFee ().getNValue ())
         {
             // TODO: log
             return (telINSUF_FEE_P);
         }
         else
         {
             if (!mFunctionTable[ fun ]->work (this))
             {
                 // TODO: log
                 return (temMALFORMED); // TODO: is this actually what we want to do?
             }
         }
     }
     return (tesSUCCESS);
 }
bool ripple::Script::Interpreter::jumpTo (int offset)
Definition at line 193 of file Interpreter.cpp.
References mCode, and mInstructionPointer.
Referenced by ripple::Script::JumpIfOp::work(), and ripple::Script::JumpOp::work().
 {
     if (offset < 0)
     {
         if (-offset > mInstructionPointer)
             return false;
     }
     else
     {
         if (offset > mCode->size () ||
                 mInstructionPointer > mCode->size () - offset)
             return false;
     }
     mInstructionPointer += offset;
     return (true);
 }
Data::pointer ripple::Script::Interpreter::popStack ()
Definition at line 90 of file Interpreter.cpp.
References mStack.
Referenced by ripple::Script::AddOp::work(), ripple::Script::SubOp::work(), ripple::Script::MulOp::work(), ripple::Script::DivOp::work(), ripple::Script::GtrOp::work(), ripple::Script::LessOp::work(), ripple::Script::ModOp::work(), ripple::Script::AcceptDataOp::work(), ripple::Script::JumpIfOp::work(), ripple::Script::SendXRPOp::work(), and ripple::Script::GetDataOp::work().
 {
     if (mStack.size ())
     {
         Data::pointer item = mStack[mStack.size () - 1];
         mStack.pop_back ();
         return (item);
     }
     else
     {
         return (Data::pointer (new ErrorData ()));
     }
 }
void ripple::Script::Interpreter::pushStack (Data::pointer data)
Definition at line 104 of file Interpreter.cpp.
References mStack.
Referenced by endBlock(), ripple::Script::IntOp::work(), ripple::Script::FloatOp::work(), ripple::Script::Uint160Op::work(), ripple::Script::AddOp::work(), ripple::Script::SubOp::work(), ripple::Script::MulOp::work(), ripple::Script::DivOp::work(), ripple::Script::GtrOp::work(), ripple::Script::LessOp::work(), ripple::Script::ModOp::work(), ripple::Script::AcceptDataOp::work(), and ripple::Script::GetDataOp::work().
 {
     mStack.push_back (data);
 }
void ripple::Script::Interpreter::setInstructionPointer (int n) inline
Definition at line 79 of file Interpreter.h.
References mInstructionPointer.
     {
         mInstructionPointer = n;
     }
bool ripple::Script::Interpreter::startBlock (int offset)
Definition at line 111 of file Interpreter.cpp.
References mBlockJump, mBlockSuccess, mInBlock, and mInstructionPointer.
Referenced by ripple::Script::StartBlockOp::work().
 {
     if (mInBlock) return (false); // can't nest blocks
     mBlockSuccess = true;
     mInBlock = true;
     mBlockJump = offset + mInstructionPointer;
     return (true);
 }
void ripple::Script::Interpreter::stop (void)
Definition at line 211 of file Interpreter.cpp.
References mCode, and mInstructionPointer.
Referenced by ripple::Script::StopOp::work().
 {
     mInstructionPointer = mCode->size ();
 }
Member Data Documentation
int ripple::Script::Interpreter::mBlockJump private
Definition at line 42 of file Interpreter.h.
Referenced by endBlock(), Interpreter(), and startBlock().
bool ripple::Script::Interpreter::mBlockSuccess private
Definition at line 43 of file Interpreter.h.
Referenced by endBlock(), Interpreter(), and startBlock().
Blob* ripple::Script::Interpreter::mCode private
Definition at line 37 of file Interpreter.h.
Referenced by interpret(), Interpreter(), jumpTo(), and stop().
Contract* ripple::Script::Interpreter::mContract private
Definition at line 36 of file Interpreter.h.
Referenced by interpret(), and Interpreter().
std::vector<Operation*> ripple::Script::Interpreter::mFunctionTable private
Definition at line 32 of file Interpreter.h.
Referenced by interpret(), and Interpreter().
bool ripple::Script::Interpreter::mInBlock private
Definition at line 41 of file Interpreter.h.
Referenced by endBlock(), Interpreter(), and startBlock().
unsigned int ripple::Script::Interpreter::mInstructionPointer private
Definition at line 38 of file Interpreter.h.
Referenced by getFloatData(), getInstructionPointer(), getIntData(), getUint160Data(), interpret(), Interpreter(), jumpTo(), setInstructionPointer(), startBlock(), and stop().
std::vector<Data::pointer> ripple::Script::Interpreter::mStack private
Definition at line 34 of file Interpreter.h.
Referenced by popStack(), and pushStack().
int ripple::Script::Interpreter::mTotalFee private
Definition at line 39 of file Interpreter.h.
Referenced by interpret(), and Interpreter().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/contracts/Interpreter.h
rippled/src/ripple_app/contracts/Interpreter.cpp