rippled: beast::ServiceQueue_timing_test::Consumer< ServiceType > Struct Template Reference
beast::ServiceQueue_timing_test::Consumer< ServiceType > Struct Template Reference
Public Member Functions
Consumer (int id, std::int64_t seedValue, ServiceType &service)
~Consumer ()
void do_handler ()
void run ()
Public Member Functions inherited from beast::Thread
Thread (const String &threadName)
virtual ~Thread ()
void startThread ()
void startThread (int priority)
bool stopThread (int timeOutMilliseconds=-1)
void stopThreadAsync ()
bool isThreadRunning () const
void signalThreadShouldExit ()
bool threadShouldExit () const
bool waitForThreadToExit (int timeOutMilliseconds=-1) const
bool setPriority (int priority)
void setAffinityMask (std::uint32_t affinityMask)
bool wait (int timeOutMilliseconds=-1) const
void notify () const
ThreadID getThreadId () const noexcept
const String & getThreadName () const
Static Public Member Functions
static Consumer *& thread ()
static void stop_one ()
static void handler ()
Static Public Member Functions inherited from beast::Thread
static bool setCurrentThreadPriority (int priority)
static void setCurrentThreadAffinityMask (std::uint32_t affinityMask)
static void sleep (int milliseconds)
static void yield ()
static ThreadID getCurrentThreadId ()
static Thread * getCurrentThread ()
static void setCurrentThreadName (const String &newThreadName)
Public Attributes
ServiceType & m_service
Random m_random
String m_string
Additional Inherited Members
Public Types inherited from beast::Thread
typedef void * ThreadID
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
template<typename ServiceType>
struct beast::ServiceQueue_timing_test::Consumer< ServiceType >
Definition at line 54 of file ServiceQueue.cpp.
Constructor & Destructor Documentation
template<typename ServiceType > beast::ServiceQueue_timing_test::Consumer< ServiceType >::Consumer (int id, std::int64_t seedValue, ServiceType & service) inline
Definition at line 60 of file ServiceQueue.cpp.
References beast::Thread::startThread().
             : Thread ("C#" + String::fromNumber (id))
             , m_service (service)
             , m_random (seedValue)
             { startThread(); }
template<typename ServiceType > beast::ServiceQueue_timing_test::Consumer< ServiceType >::~Consumer () inline
Definition at line 66 of file ServiceQueue.cpp.
References beast::Thread::stopThread().
             { stopThread(); }
Member Function Documentation
template<typename ServiceType > void beast::ServiceQueue_timing_test::Consumer< ServiceType >::do_handler () inline
Definition at line 81 of file ServiceQueue.cpp.
References beast::String::empty, beast::String::fromNumber(), beast::String::length(), beast::ServiceQueue_timing_test::Consumer< ServiceType >::m_random, beast::ServiceQueue_timing_test::Consumer< ServiceType >::m_string, and beast::Random::nextInt().
Referenced by beast::ServiceQueue_timing_test::Consumer< ServiceType >::handler().
         {
             String const s (String::fromNumber (m_random.nextInt()));
             m_string += s;
             if (m_string.length() > 100)
                 m_string = String::empty;
         }
template<typename ServiceType > static void beast::ServiceQueue_timing_test::Consumer< ServiceType >::handler () inline static
Definition at line 78 of file ServiceQueue.cpp.
References beast::ServiceQueue_timing_test::Consumer< ServiceType >::do_handler(), and beast::ServiceQueue_timing_test::Consumer< ServiceType >::thread().
             { thread()->do_handler(); }
template<typename ServiceType > void beast::ServiceQueue_timing_test::Consumer< ServiceType >::run () inline virtual
Must be implemented to perform the thread's actual code.
Remember that the thread must regularly check the threadShouldExit() method whilst running, and if this returns true it should return from the run() method as soon as possible to avoid being forcibly killed.
See Also
threadShouldExit, startThread
Implements beast::Thread.
Definition at line 89 of file ServiceQueue.cpp.
References beast::ServiceQueue_timing_test::Consumer< ServiceType >::m_service, beast::ServiceQueue_timing_test::Consumer< ServiceType >::thread(), and beast::Thread::threadShouldExit().
         {
             thread() = this;
             while (! threadShouldExit())
                 m_service.run_one();
         }
template<typename ServiceType > static void beast::ServiceQueue_timing_test::Consumer< ServiceType >::stop_one () inline static
Definition at line 75 of file ServiceQueue.cpp.
References beast::Thread::signalThreadShouldExit(), and beast::ServiceQueue_timing_test::Consumer< ServiceType >::thread().
             { thread()->signalThreadShouldExit(); }
template<typename ServiceType > static Consumer*& beast::ServiceQueue_timing_test::Consumer< ServiceType >::thread () inline static
Definition at line 69 of file ServiceQueue.cpp.
References beast::ThreadLocalValue< Type >::get(), and std::chrono::local.
Referenced by beast::ServiceQueue_timing_test::Consumer< ServiceType >::handler(), beast::ServiceQueue_timing_test::Consumer< ServiceType >::run(), and beast::ServiceQueue_timing_test::Consumer< ServiceType >::stop_one().
         {
             static ThreadLocalValue <Consumer*> local;
             return local.get();
         }
Member Data Documentation
template<typename ServiceType > Random beast::ServiceQueue_timing_test::Consumer< ServiceType >::m_random
Definition at line 57 of file ServiceQueue.cpp.
Referenced by beast::ServiceQueue_timing_test::Consumer< ServiceType >::do_handler().
template<typename ServiceType > ServiceType& beast::ServiceQueue_timing_test::Consumer< ServiceType >::m_service
Definition at line 56 of file ServiceQueue.cpp.
Referenced by beast::ServiceQueue_timing_test::Consumer< ServiceType >::run().
template<typename ServiceType > String beast::ServiceQueue_timing_test::Consumer< ServiceType >::m_string
Definition at line 58 of file ServiceQueue.cpp.
Referenced by beast::ServiceQueue_timing_test::Consumer< ServiceType >::do_handler().
The documentation for this struct was generated from the following file:
rippled/src/beast/beast/threads/tests/ServiceQueue.cpp