rippled: beast::Logger Class Reference
beast::Logger Class Reference abstract
#include <Logger.h>
Public Member Functions
virtual ~Logger ()
Static Public Member Functions
static void setCurrentLogger (Logger *newLogger) noexcept
static Logger * getCurrentLogger () noexcept
static void writeToLog (const String &message)
static void outputDebugString (const String &text)
Protected Member Functions
Logger ()
virtual void logMessage (const String &message)=0
Static Private Attributes
static Logger * currentLogger = nullptr
Detailed Description
Acts as an application-wide logging class.
A subclass of Logger can be created and passed into the Logger::setCurrentLogger method and this will then be used by all calls to writeToLog.
The logger class also contains methods for writing messages to the debugger's output stream.
Definition at line 40 of file Logger.h.
Constructor & Destructor Documentation
beast::Logger::~Logger () virtual
Destructor.
Definition at line 29 of file Logger.cpp.
References bassert, and currentLogger.
 {
     // You're deleting this logger while it's still being used!
     // Always call Logger::setCurrentLogger (nullptr) before deleting the active logger.
     bassert (currentLogger != this);
 }
beast::Logger::Logger () protected
Definition at line 27 of file Logger.cpp.
 {}
Member Function Documentation
Logger * beast::Logger::getCurrentLogger () static noexcept
Returns the current logger, or nullptr if none has been set.
Definition at line 39 of file Logger.cpp.
References currentLogger.
 { return currentLogger; }
virtual void beast::Logger::logMessage (const String & message) protected pure virtual
This is overloaded by subclasses to implement custom logging behaviour.
See Also
setCurrentLogger
Referenced by writeToLog().
void beast::Logger::outputDebugString (const String & text) static
Writes a message to the standard error stream.
This can be called directly, or by using the DBG() macro in CompilerConfig.h (which will avoid calling the method in non-debug builds).
Definition at line 184 of file bsd_SystemStats.cpp.
Referenced by beast::insight::detail::StatsDCollectorImp::log(), ripple::LogSink::write_console(), and writeToLog().
 {
     std::cerr << text << std::endl;
 }
void beast::Logger::setCurrentLogger (Logger * newLogger) static noexcept
Sets the current logging class to use.
Note that the object passed in will not be owned or deleted by the logger, so the caller must make sure that it is not deleted while still being used. A null pointer can be passed-in to disable any logging.
Definition at line 38 of file Logger.cpp.
 { currentLogger = newLogger; }
void beast::Logger::writeToLog (const String & message) static
Writes a string to the current logger.
This will pass the string to the logger's logMessage() method if a logger has been set.
See Also
logMessage
Definition at line 41 of file Logger.cpp.
References currentLogger, logMessage(), and outputDebugString().
Referenced by beast::File::parseAbsolutePath().
 {
     if (currentLogger != nullptr)
         currentLogger->logMessage (message);
     else
         outputDebugString (message);
 }
Member Data Documentation
Logger * beast::Logger::currentLogger = nullptr static private
Definition at line 88 of file Logger.h.
Referenced by getCurrentLogger(), writeToLog(), and ~Logger().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_core/logging/Logger.h
rippled/src/beast/modules/beast_core/logging/Logger.cpp
rippled/src/beast/modules/beast_core/native/bsd_SystemStats.cpp
rippled/src/beast/modules/beast_core/native/linux_SystemStats.cpp
rippled/src/beast/modules/beast_core/native/mac_SystemStats.mm
rippled/src/beast/modules/beast_core/native/win32_SystemStats.cpp