rippled: ripple::SerializerIterator Class Reference
ripple::SerializerIterator Class Reference
#include <Serializer.h>
Public Member Functions
SerializerIterator (Serializer &s)
const Serializer & operator* (void)
void reset (void)
void setPos (int p)
int getPos (void)
bool empty ()
int getBytesLeft ()
unsigned char get8 ()
std::uint16_t get16 ()
std::uint32_t get32 ()
std::uint64_t get64 ()
uint128 get128 ()
uint160 get160 ()
uint256 get256 ()
void getFieldID (int &type, int &field)
Blob getRaw (int iLength)
Blob getVL ()
Protected Attributes
const Serializer & mSerializer
int mPos
Detailed Description
Definition at line 254 of file Serializer.h.
Constructor & Destructor Documentation
ripple::SerializerIterator::SerializerIterator (Serializer & s) inline
Definition at line 263 of file Serializer.h.
                                        : mSerializer (s), mPos (0)
     {
         ;
     }
Member Function Documentation
bool ripple::SerializerIterator::empty () inline
Definition at line 285 of file Serializer.h.
References ripple::Serializer::getLength(), mPos, and mSerializer.
Referenced by ripple::STArray::construct(), and ripple::STObject::set().
     {
         return mPos == mSerializer.getLength ();
     }
uint128 ripple::SerializerIterator::get128 ()
Definition at line 640 of file Serializer.cpp.
References ripple::Serializer::get128(), mPos, and mSerializer.
Referenced by ripple::STHash128::construct().
 {
     uint128 val;
     if (!mSerializer.get128 (val, mPos)) throw std::runtime_error ("invalid serializer get128");
     mPos += 128 / 8;
     return val;
 }
std::uint16_t ripple::SerializerIterator::get16 ()
Definition at line 610 of file Serializer.cpp.
References ripple::Serializer::get16(), mPos, and mSerializer.
Referenced by ripple::STUInt16::construct().
 {
     std::uint16_t val;
     if (!mSerializer.get16 (val, mPos)) throw std::runtime_error ("invalid serializer get16");
     mPos += 16 / 8;
     return val;
 }
uint160 ripple::SerializerIterator::get160 ()
Definition at line 650 of file Serializer.cpp.
References ripple::Serializer::get160(), mPos, and mSerializer.
Referenced by ripple::STAmount::construct(), ripple::STHash160::construct(), and ripple::STPathSet::construct().
 {
     uint160 val;
     if (!mSerializer.get160 (val, mPos)) throw std::runtime_error ("invalid serializer get160");
     mPos += 160 / 8;
     return val;
 }
uint256 ripple::SerializerIterator::get256 ()
Definition at line 660 of file Serializer.cpp.
References ripple::Serializer::get256(), mPos, and mSerializer.
Referenced by ripple::STHash256::construct(), and ripple::Ledger::setRaw().
 {
     uint256 val;
     if (!mSerializer.get256 (val, mPos)) throw std::runtime_error ("invalid serializer get256");
     mPos += 256 / 8;
     return val;
 }
std::uint32_t ripple::SerializerIterator::get32 ()
Definition at line 620 of file Serializer.cpp.
References ripple::Serializer::get32(), mPos, and mSerializer.
Referenced by ripple::STUInt32::construct(), and ripple::Ledger::setRaw().
 {
     std::uint32_t val;
     if (!mSerializer.get32 (val, mPos)) throw std::runtime_error ("invalid serializer get32");
     mPos += 32 / 8;
     return val;
 }
std::uint64_t ripple::SerializerIterator::get64 ()
Definition at line 630 of file Serializer.cpp.
References ripple::Serializer::get64(), mPos, and mSerializer.
Referenced by ripple::STUInt64::construct(), ripple::STAmount::construct(), and ripple::Ledger::setRaw().
 {
     std::uint64_t val;
     if (!mSerializer.get64 (val, mPos)) throw std::runtime_error ("invalid serializer get64");
     mPos += 64 / 8;
     return val;
 }
unsigned char ripple::SerializerIterator::get8 ()
Definition at line 600 of file Serializer.cpp.
References ripple::Serializer::get8(), mPos, and mSerializer.
Referenced by ripple::STUInt8::construct(), ripple::STPathSet::construct(), and ripple::Ledger::setRaw().
 {
     int val;
     if (!mSerializer.get8 (val, mPos)) throw std::runtime_error ("invalid serializer get8");
     ++mPos;
     return val;
 }
int ripple::SerializerIterator::getBytesLeft ()
Definition at line 581 of file Serializer.cpp.
References mPos, mSerializer, and ripple::Serializer::size().
Referenced by ripple::SerializedTransaction::SerializedTransaction().
 {
     return mSerializer.size () - mPos;
 }
void ripple::SerializerIterator::getFieldID (int & type, int & field)
Definition at line 586 of file Serializer.cpp.
References ripple::Serializer::getFieldID(), mPos, and mSerializer.
Referenced by ripple::STArray::construct(), and ripple::STObject::set().
 {
     if (!mSerializer.getFieldID (type, field, mPos))
         throw std::runtime_error ("invalid serializer getFieldID");
     ++mPos;
     if (type >= 16)
         ++mPos;
     if (field >= 16)
         ++mPos;
 }
int ripple::SerializerIterator::getPos (void) inline
Definition at line 281 of file Serializer.h.
References mPos.
     {
         return mPos;
     }
Blob ripple::SerializerIterator::getRaw (int iLength)
Definition at line 681 of file Serializer.cpp.
References ripple::Serializer::getRaw(), mPos, and mSerializer.
Referenced by ripple::STAmount::createHumanCurrency().
 {
     int iPos    = mPos;
     mPos        += iLength;
     return mSerializer.getRaw (iPos, iLength);
 }
Blob ripple::SerializerIterator::getVL ()
Definition at line 670 of file Serializer.cpp.
References ripple::Serializer::getVL(), mPos, and mSerializer.
Referenced by ripple::AcceptedLedgerTx::AcceptedLedgerTx(), ripple::STVariableLength::construct(), ripple::STAccount::construct(), ripple::STVector256::construct(), ripple::Ledger::getMetaHex(), ripple::Ledger::getTransactionMeta(), and ripple::STVariableLength::STVariableLength().
 {
     int length;
     Blob vl;
     if (!mSerializer.getVL (vl, mPos, length)) throw std::runtime_error ("invalid serializer getVL");
     mPos += length;
     return vl;
 }
const Serializer& ripple::SerializerIterator::operator* (void) inline
Definition at line 268 of file Serializer.h.
References mSerializer.
     {
         return mSerializer;
     }
void ripple::SerializerIterator::reset (void) inline
Definition at line 272 of file Serializer.h.
References mPos.
Referenced by ripple::Ledger::getSMTransaction().
     {
         mPos = 0;
     }
void ripple::SerializerIterator::setPos (int p) inline
Definition at line 276 of file Serializer.h.
References mPos.
     {
         mPos = p;
     }
Member Data Documentation
int ripple::SerializerIterator::mPos protected
Definition at line 258 of file Serializer.h.
Referenced by empty(), get128(), get16(), get160(), get256(), get32(), get64(), get8(), getBytesLeft(), getFieldID(), getPos(), getRaw(), getVL(), reset(), and setPos().
const Serializer& ripple::SerializerIterator::mSerializer protected
Definition at line 257 of file Serializer.h.
Referenced by empty(), get128(), get16(), get160(), get256(), get32(), get64(), get8(), getBytesLeft(), getFieldID(), getRaw(), getVL(), and operator*().
The documentation for this class was generated from the following files:
rippled/src/ripple_data/protocol/Serializer.h
rippled/src/ripple_data/protocol/Serializer.cpp