rippled: beast::asio::HTTPClient_test::IoServiceThread Class Reference
beast::asio::HTTPClient_test::IoServiceThread Class Reference
Public Member Functions
IoServiceThread (String name="io_service")
~IoServiceThread ()
boost::asio::io_service & get_io_service ()
void start ()
void join ()
Private Member Functions
void run ()
Private Attributes
boost::asio::io_service m_service
Additional Inherited Members
Protected Types inherited from beast::Thread
typedef void * ThreadID
Protected Member Functions inherited from beast::Thread
Thread (const String &threadName)
virtual ~Thread ()
void startThread ()
void startThread (int priority)
bool stopThread (int timeOutMilliseconds=-1)
void stopThreadAsync ()
bool isThreadRunning () const
void signalThreadShouldExit ()
bool threadShouldExit () const
bool waitForThreadToExit (int timeOutMilliseconds=-1) const
bool setPriority (int priority)
void setAffinityMask (std::uint32_t affinityMask)
bool wait (int timeOutMilliseconds=-1) const
void notify () const
ThreadID getThreadId () const noexcept
const String & getThreadName () const
Static Protected Member Functions inherited from beast::Thread
static bool setCurrentThreadPriority (int priority)
static void setCurrentThreadAffinityMask (std::uint32_t affinityMask)
static void sleep (int milliseconds)
static void yield ()
static ThreadID getCurrentThreadId ()
static Thread * getCurrentThread ()
static void setCurrentThreadName (const String &newThreadName)
Detailed Description
Definition at line 559 of file HTTPClientType.cpp.
Constructor & Destructor Documentation
beast::asio::HTTPClient_test::IoServiceThread::IoServiceThread (String name = "io_service") inline explicit
Definition at line 562 of file HTTPClientType.cpp.
             : Thread (name)
         {
         }
beast::asio::HTTPClient_test::IoServiceThread::~IoServiceThread () inline
Definition at line 567 of file HTTPClientType.cpp.
References join().
         {
             join ();
         }
Member Function Documentation
boost::asio::io_service& beast::asio::HTTPClient_test::IoServiceThread::get_io_service () inline
Definition at line 572 of file HTTPClientType.cpp.
References m_service.
Referenced by beast::asio::HTTPClient_test::testAsync().
         {
             return m_service;
         }
void beast::asio::HTTPClient_test::IoServiceThread::join () inline
Definition at line 582 of file HTTPClientType.cpp.
References beast::Thread::waitForThreadToExit().
Referenced by beast::asio::HTTPClient_test::testAsync(), and ~IoServiceThread().
         {
             this->waitForThreadToExit ();
         }
void beast::asio::HTTPClient_test::IoServiceThread::run () inline private virtual
Must be implemented to perform the thread's actual code.
Remember that the thread must regularly check the threadShouldExit() method whilst running, and if this returns true it should return from the run() method as soon as possible to avoid being forcibly killed.
See Also
threadShouldExit, startThread
Implements beast::Thread.
Definition at line 588 of file HTTPClientType.cpp.
References m_service.
         {
             m_service.run ();
         }
void beast::asio::HTTPClient_test::IoServiceThread::start () inline
Definition at line 577 of file HTTPClientType.cpp.
References beast::Thread::startThread().
Referenced by beast::asio::HTTPClient_test::testAsync().
         {
             startThread ();
         }
Member Data Documentation
boost::asio::io_service beast::asio::HTTPClient_test::IoServiceThread::m_service private
Definition at line 594 of file HTTPClientType.cpp.
Referenced by get_io_service(), and run().
The documentation for this class was generated from the following file:
rippled/src/beast/modules/beast_asio/http/HTTPClientType.cpp