rippled: beast::URL Class Reference
beast::URL Class Reference
#include <URL.h>
Public Member Functions
URL ()
URL (String schema_, String host_, std::uint16_t port_, String port_string_, String path_, String query_="", String fragment_="", String userinfo_="")
URL (URL const &other)
URL & operator= (URL const &other)
bool empty () const
String scheme () const
String host () const
std::uint16_t port () const
String port_string () const
String path () const
String query () const
String fragment () const
String userinfo () const
String toString () const
std::string to_string () const
Private Attributes
String m_scheme
String m_host
std::uint16_t m_port
String m_port_string
String m_path
String m_query
String m_fragment
String m_userinfo
Detailed Description
A URL. The accompanying robust parser is hardened against all forms of attack.
Definition at line 32 of file URL.h.
Constructor & Destructor Documentation
beast::URL::URL () explicit
Construct an empty URL.
Definition at line 24 of file URL.cpp.
     : m_port (0)
 {
 }
beast::URL::URL (String schema_, String host_, std::uint16_t port_, String port_string_, String path_, String query_ = "", String fragment_ = "", String userinfo_ = "")
Construct a URL from it's components.
Definition at line 28 of file URL.cpp.
     : m_scheme (scheme_)
     , m_host (host_)
     , m_port (port_)
     , m_port_string (port_string_)
     , m_path (path_)
     , m_query (query_)
     , m_fragment (fragment_)
     , m_userinfo (userinfo_)
 {
 }
beast::URL::URL (URL const & other)
Copy construct a URL.
Definition at line 48 of file URL.cpp.
     : m_scheme (other.m_scheme)
     , m_host (other.m_host)
     , m_port (other.m_port)
     , m_port_string (other.m_port_string)
     , m_path (other.m_path)
     , m_query (other.m_query)
     , m_fragment (other.m_fragment)
     , m_userinfo (other.m_userinfo)
 {
 }
Member Function Documentation
bool beast::URL::empty () const
Returns true if this is an empty URL.
Definition at line 75 of file URL.cpp.
References beast::String::empty, and m_scheme.
 {
     return m_scheme == String::empty;
 }
String beast::URL::fragment () const
Returns the URL fragment, if any.
Definition at line 110 of file URL.cpp.
References m_fragment.
Referenced by toString().
 {
     return m_fragment;
 }
String beast::URL::host () const
Returns the host of the URL. If no host was specified, the string will be empty.
Definition at line 85 of file URL.cpp.
References m_host.
Referenced by beast::asio::HTTPClientType::Session::handle_handshake(), beast::asio::HTTPClientType::queryFromURL(), and toString().
 {
     return m_host;
 }
URL & beast::URL::operator= (URL const & other)
Copy assign a URL.
Definition at line 60 of file URL.cpp.
References m_fragment, m_host, m_path, m_port, m_port_string, m_query, m_scheme, and m_userinfo.
 {
     m_scheme = other.m_scheme;
     m_host = other.m_host;
     m_port = other.m_port;
     m_port_string = other.m_port_string;
     m_path = other.m_path;
     m_query = other.m_query;
     m_fragment = other.m_fragment;
     m_userinfo = other.m_userinfo;
     return *this;
 }
String beast::URL::path () const
Returns the path of the URL. If no path was specified, the string will be empty.
Definition at line 100 of file URL.cpp.
References m_path.
Referenced by beast::asio::HTTPClientType::Session::handle_handshake(), and toString().
 {
     return m_path;
 }
std::uint16_t beast::URL::port () const
Returns the port number as an integer. If no port was specified, the value will be zero.
Definition at line 95 of file URL.cpp.
References m_port.
Referenced by beast::asio::HTTPClientType::queryFromURL(), and toString().
 {
     return m_port;
 }
String beast::URL::port_string () const
Returns the port number as a string. If no port was specified, the string will be empty.
Definition at line 90 of file URL.cpp.
References m_port_string.
Referenced by beast::asio::HTTPClientType::queryFromURL().
 {
     return m_port_string;
 }
String beast::URL::query () const
Returns the query parameters portion of the URL. If no query parameters were present, the string will be empty.
Definition at line 105 of file URL.cpp.
References m_query.
Referenced by toString().
 {
     return m_query;
 }
String beast::URL::scheme () const
Returns the scheme of the URL. If no scheme was specified, the string will be empty.
Definition at line 80 of file URL.cpp.
References m_scheme.
Referenced by beast::asio::HTTPClientType::Session::handle_connect(), beast::asio::HTTPClientType::queryFromURL(), and toString().
 {
     return m_scheme;
 }
std::string beast::URL::to_string () const
Definition at line 156 of file URL.cpp.
References beast::String::toStdString(), and toString().
Referenced by beast::operator<<(), ripple::SiteFiles::Logic::processResponse(), and ripple::Validators::SourceURLImp::to_string().
 {
     return toString().toStdString();
 }
String beast::URL::toString () const
Retrieve the full URL as a single string.
Definition at line 131 of file URL.cpp.
References beast::String::empty, fragment(), beast::String::fromNumber(), host(), path(), port(), query(), scheme(), and userinfo().
Referenced by beast::ParsedURL_test::checkURL(), ripple::Validators::SourceURLImp::createParam(), beast::hash_append(), beast::hash_value(), beast::operator!=(), beast::operator<(), beast::operator<=(), beast::operator==(), beast::operator>(), beast::operator>=(), to_string(), and ripple::Validators::SourceURLImp::uniqueID().
 {
     String s;
     s = scheme () + "://";
     if (userinfo () != String::empty)
         s = userinfo () + "@";
     s = s + host ();
     if (port () != 0)
         s = s + ":" + String::fromNumber (port ());
     s = s + path ();
     if (query () != String::empty)
         s = "?" + query ();
     if (fragment () != String::empty)
         s = "#" + fragment ();
     return s;
 }
String beast::URL::userinfo () const
Returns the user information, if any.
Definition at line 115 of file URL.cpp.
References m_userinfo.
Referenced by toString().
 {
     return m_userinfo;
 }
Member Data Documentation
String beast::URL::m_fragment private
Definition at line 107 of file URL.h.
Referenced by fragment(), and operator=().
String beast::URL::m_host private
Definition at line 102 of file URL.h.
Referenced by host(), and operator=().
String beast::URL::m_path private
Definition at line 105 of file URL.h.
Referenced by operator=(), and path().
std::uint16_t beast::URL::m_port private
Definition at line 103 of file URL.h.
Referenced by operator=(), and port().
String beast::URL::m_port_string private
Definition at line 104 of file URL.h.
Referenced by operator=(), and port_string().
String beast::URL::m_query private
Definition at line 106 of file URL.h.
Referenced by operator=(), and query().
String beast::URL::m_scheme private
Definition at line 101 of file URL.h.
Referenced by empty(), operator=(), and scheme().
String beast::URL::m_userinfo private
Definition at line 108 of file URL.h.
Referenced by operator=(), and userinfo().
The documentation for this class was generated from the following files:
rippled/src/beast/beast/http/URL.h
rippled/src/beast/beast/http/impl/URL.cpp