rippled: rocksdb::Iterator Class Reference
rocksdb::Iterator Class Reference abstract
#include <iterator.h>
Classes
struct Cleanup
Public Types
typedef void(* CleanupFunction)(void *arg1, void *arg2)
Public Member Functions
Iterator ()
virtual ~Iterator ()
virtual bool Valid () const =0
virtual void SeekToFirst ()=0
virtual void SeekToLast ()=0
virtual void Seek (const Slice &target)=0
virtual void Next ()=0
virtual void Prev ()=0
virtual Slice key () const =0
virtual Slice value () const =0
virtual Status status () const =0
void RegisterCleanup (CleanupFunction function, void *arg1, void *arg2)
Private Member Functions
Iterator (const Iterator &)
void operator= (const Iterator &)
Private Attributes
Cleanup cleanup_
Detailed Description
Definition at line 27 of file iterator.h.
Member Typedef Documentation
typedef void(* rocksdb::Iterator::CleanupFunction)(void *arg1, void *arg2)
Definition at line 81 of file iterator.h.
Constructor & Destructor Documentation
rocksdb::Iterator::Iterator ()
Definition at line 14 of file iterator.cc.
References cleanup_, rocksdb::Iterator::Cleanup::function, and rocksdb::Iterator::Cleanup::next.
                    {
   cleanup_.function = nullptr;
   cleanup_.next = nullptr;
 }
rocksdb::Iterator::~Iterator () virtual
Definition at line 19 of file iterator.cc.
References rocksdb::Iterator::Cleanup::arg1, rocksdb::Iterator::Cleanup::arg2, cleanup_, rocksdb::Iterator::Cleanup::function, next, and rocksdb::Iterator::Cleanup::next.
                     {
   if (cleanup_.function != nullptr) {
     (*cleanup_.function)(cleanup_.arg1, cleanup_.arg2);
     for (Cleanup* c = cleanup_.next; c != nullptr; ) {
       (*c->function)(c->arg1, c->arg2);
       Cleanup* next = c->next;
       delete c;
       c = next;
     }
   }
 }
rocksdb::Iterator::Iterator (const Iterator &) private
Member Function Documentation
virtual Slice rocksdb::Iterator::key () const pure virtual
Implemented in rocksdb::ModelDB::ModelIter, rocksdb::KeyConvertingIterator, rocksdb::Version::LevelFileNumIterator, rocksdb::TtlIterator, rocksdb::SimpleTableIterator, rocksdb::Block::Iter, rocksdb::MemTableIterator, and rocksdb::PrefixFilterIterator.
Referenced by rocksdb::DBTest::AllEntriesFor(), rocksdb::BuildTable(), rocksdb::CorruptionTest::Check(), rocksdb::CompareIterators(), rocksdb::DBDumperCommand::DoCommand(), rocksdb::ScanCommand::DoCommand(), rocksdb::DBTest::IterStatus(), rocksdb::SimpleTableDBTest::IterStatus(), rocksdb::PrefixFilterIterator::key(), rocksdb::TtlIterator::key(), rocksdb::KeyConvertingIterator::key(), leveldb_iter_key(), rocksdb::MergeHelper::MergeUntil(), rocksdb::StressTest::OperateDb(), rocksdb::Version::PrefixMayMatch(), rocksdb::Benchmark::PrefixScanRandom(), rocksdb::PrintContents(), rocksdb::Benchmark::ReadReverse(), rocksdb::SstFileReader::ReadSequential(), rocksdb::Benchmark::ReadSequential(), rocksdb::Benchmark::SeekRandom(), rocksdb::TableReaderBenchmark(), rocksdb::TEST(), rocksdb::Harness::ToString(), rocksdb::IteratorWrapper::Update(), and rocksdb::PrefixFilterIterator::Valid().
virtual void rocksdb::Iterator::Next () pure virtual
Implemented in rocksdb::ModelDB::ModelIter, rocksdb::KeyConvertingIterator, rocksdb::Version::LevelFileNumIterator, rocksdb::Block::Iter, rocksdb::TtlIterator, rocksdb::SimpleTableIterator, rocksdb::MemTableIterator, and rocksdb::PrefixFilterIterator.
Referenced by rocksdb::DBTest::AllEntriesFor(), rocksdb::BuildTable(), rocksdb::CorruptionTest::Check(), rocksdb::CompareIterators(), rocksdb::DBTest::Contents(), rocksdb::DBDumperCommand::DoCommand(), rocksdb::ScanCommand::DoCommand(), rocksdb::BlockBasedTable::Get(), leveldb_iter_next(), rocksdb::MergeHelper::MergeUntil(), rocksdb::StressTest::MultiPrefixScan(), rocksdb::IteratorWrapper::Next(), rocksdb::PrefixFilterIterator::Next(), rocksdb::TtlIterator::Next(), rocksdb::KeyConvertingIterator::Next(), rocksdb::StressTest::OperateDb(), rocksdb::Benchmark::PrefixScanRandom(), rocksdb::PrintContents(), rocksdb::Benchmark::ReadRandom(), rocksdb::SstFileReader::ReadSequential(), rocksdb::Benchmark::ReadSequential(), rocksdb::TtlTest::SleepCompactCheckIter(), rocksdb::TableReaderBenchmark(), rocksdb::TEST(), rocksdb::Harness::TestForwardScan(), and rocksdb::Harness::TestRandomAccess().
void rocksdb::Iterator::operator= (const Iterator &) private
virtual void rocksdb::Iterator::Prev () pure virtual
Implemented in rocksdb::ModelDB::ModelIter, rocksdb::KeyConvertingIterator, rocksdb::Version::LevelFileNumIterator, rocksdb::Block::Iter, rocksdb::TtlIterator, rocksdb::SimpleTableIterator, rocksdb::MemTableIterator, and rocksdb::PrefixFilterIterator.
Referenced by rocksdb::DBTest::Contents(), leveldb_iter_prev(), rocksdb::IteratorWrapper::Prev(), rocksdb::PrefixFilterIterator::Prev(), rocksdb::TtlIterator::Prev(), rocksdb::KeyConvertingIterator::Prev(), rocksdb::Benchmark::ReadReverse(), rocksdb::TEST(), rocksdb::Harness::TestBackwardScan(), and rocksdb::Harness::TestRandomAccess().
void rocksdb::Iterator::RegisterCleanup (CleanupFunction function, void * arg1, void * arg2)
Definition at line 31 of file iterator.cc.
References rocksdb::Iterator::Cleanup::arg1, rocksdb::Iterator::Cleanup::arg2, Cleanup(), cleanup_, func, rocksdb::Iterator::Cleanup::function, and rocksdb::Iterator::Cleanup::next.
Referenced by rocksdb::BlockBasedTable::BlockReader(), rocksdb::BlockBasedTable::IndexBlockReader(), rocksdb::DBImpl::NewInternalIterator(), and rocksdb::TableCache::NewIterator().
{
   assert(func != nullptr);
   Cleanup* c;
   if (cleanup_.function == nullptr) {
     c = &cleanup_;
   } else {
     c = new Cleanup;
     c->next = cleanup_.next;
     cleanup_.next = c;
   }
   c->function = func;
   c->arg1 = arg1;
   c->arg2 = arg2;
 }
virtual void rocksdb::Iterator::Seek (const Slice & target) pure virtual
Implemented in rocksdb::ModelDB::ModelIter, rocksdb::KeyConvertingIterator, rocksdb::Block::Iter, rocksdb::Version::LevelFileNumIterator, rocksdb::TtlIterator, rocksdb::SimpleTableIterator, rocksdb::MemTableIterator, and rocksdb::PrefixFilterIterator.
Referenced by rocksdb::DBTest::AllEntriesFor(), rocksdb::BlockBasedTable::ApproximateOffsetOf(), rocksdb::DBDumperCommand::DoCommand(), rocksdb::ScanCommand::DoCommand(), rocksdb::BlockBasedTable::Get(), leveldb_iter_seek(), rocksdb::Version::PrefixMayMatch(), rocksdb::Benchmark::PrefixScanRandom(), rocksdb::Benchmark::ReadRandom(), rocksdb::SstFileReader::ReadSequential(), rocksdb::IteratorWrapper::Seek(), rocksdb::PrefixFilterIterator::Seek(), rocksdb::TtlIterator::Seek(), rocksdb::KeyConvertingIterator::Seek(), rocksdb::Benchmark::SeekRandom(), rocksdb::TtlTest::SleepCompactCheckIter(), rocksdb::TableReaderBenchmark(), rocksdb::TEST(), and rocksdb::Harness::TestRandomAccess().
virtual void rocksdb::Iterator::SeekToFirst () pure virtual
Implemented in rocksdb::ModelDB::ModelIter, rocksdb::KeyConvertingIterator, rocksdb::Block::Iter, rocksdb::Version::LevelFileNumIterator, rocksdb::TtlIterator, rocksdb::SimpleTableIterator, rocksdb::MemTableIterator, and rocksdb::PrefixFilterIterator.
Referenced by rocksdb::BuildTable(), rocksdb::CorruptionTest::Check(), rocksdb::CompareIterators(), rocksdb::DBTest::Contents(), rocksdb::DBDumperCommand::DoCommand(), rocksdb::ScanCommand::DoCommand(), leveldb_iter_seek_to_first(), rocksdb::StressTest::MultiPrefixScan(), rocksdb::StressTest::OperateDb(), rocksdb::PrintContents(), rocksdb::SstFileReader::ReadSequential(), rocksdb::Benchmark::ReadSequential(), rocksdb::IteratorWrapper::SeekToFirst(), rocksdb::TtlIterator::SeekToFirst(), rocksdb::KeyConvertingIterator::SeekToFirst(), rocksdb::TEST(), rocksdb::Harness::TestForwardScan(), and rocksdb::Harness::TestRandomAccess().
virtual void rocksdb::Iterator::SeekToLast () pure virtual
Implemented in rocksdb::ModelDB::ModelIter, rocksdb::KeyConvertingIterator, rocksdb::Block::Iter, rocksdb::Version::LevelFileNumIterator, rocksdb::TtlIterator, rocksdb::SimpleTableIterator, rocksdb::MemTableIterator, and rocksdb::PrefixFilterIterator.
Referenced by rocksdb::DBTest::Contents(), leveldb_iter_seek_to_last(), rocksdb::Benchmark::ReadReverse(), rocksdb::IteratorWrapper::SeekToLast(), rocksdb::TtlIterator::SeekToLast(), rocksdb::KeyConvertingIterator::SeekToLast(), rocksdb::TEST(), rocksdb::Harness::TestBackwardScan(), rocksdb::Harness::TestRandomAccess(), and rocksdb::DBTest::VerifyIterLast().
virtual Status rocksdb::Iterator::status () const pure virtual
Implemented in rocksdb::ModelDB::ModelIter, rocksdb::KeyConvertingIterator, rocksdb::Version::LevelFileNumIterator, rocksdb::TtlIterator, rocksdb::SimpleTableIterator, rocksdb::Block::Iter, rocksdb::MemTableIterator, and rocksdb::PrefixFilterIterator.
Referenced by rocksdb::DBTest::AllEntriesFor(), rocksdb::BuildTable(), rocksdb::DBDumperCommand::DoCommand(), rocksdb::ScanCommand::DoCommand(), rocksdb::DBImpl::FinishCompactionOutputFile(), rocksdb::BlockBasedTable::Get(), leveldb_iter_get_error(), rocksdb::StressTest::OperateDb(), rocksdb::SstFileReader::ReadSequential(), rocksdb::IteratorWrapper::status(), rocksdb::PrefixFilterIterator::status(), rocksdb::TtlIterator::status(), rocksdb::KeyConvertingIterator::status(), and rocksdb::TEST().
virtual bool rocksdb::Iterator::Valid () const pure virtual
Implemented in rocksdb::ModelDB::ModelIter, rocksdb::KeyConvertingIterator, rocksdb::Version::LevelFileNumIterator, rocksdb::Block::Iter, rocksdb::TtlIterator, rocksdb::SimpleTableIterator, rocksdb::MemTableIterator, and rocksdb::PrefixFilterIterator.
Referenced by rocksdb::DBTest::AllEntriesFor(), rocksdb::BlockBasedTable::ApproximateOffsetOf(), rocksdb::BuildTable(), rocksdb::CorruptionTest::Check(), rocksdb::CompareIterators(), rocksdb::DBTest::Contents(), rocksdb::DBDumperCommand::DoCommand(), rocksdb::ScanCommand::DoCommand(), rocksdb::BlockBasedTable::Get(), rocksdb::DBTest::IterStatus(), rocksdb::SimpleTableDBTest::IterStatus(), leveldb_iter_valid(), rocksdb::MergeHelper::MergeUntil(), rocksdb::StressTest::OperateDb(), rocksdb::Version::PrefixMayMatch(), rocksdb::Benchmark::PrefixScanRandom(), rocksdb::PrintContents(), rocksdb::Benchmark::ReadRandom(), rocksdb::Benchmark::ReadReverse(), rocksdb::SstFileReader::ReadSequential(), rocksdb::Benchmark::ReadSequential(), rocksdb::Benchmark::SeekRandom(), rocksdb::TtlTest::SleepCompactCheckIter(), rocksdb::TableReaderBenchmark(), rocksdb::TEST(), rocksdb::Harness::TestBackwardScan(), rocksdb::Harness::TestForwardScan(), rocksdb::Harness::TestRandomAccess(), rocksdb::Harness::ToString(), rocksdb::IteratorWrapper::Update(), rocksdb::PrefixFilterIterator::Valid(), rocksdb::TtlIterator::Valid(), and rocksdb::KeyConvertingIterator::Valid().
virtual Slice rocksdb::Iterator::value () const pure virtual
Implemented in rocksdb::ModelDB::ModelIter, rocksdb::KeyConvertingIterator, rocksdb::Version::LevelFileNumIterator, rocksdb::TtlIterator, rocksdb::Block::Iter, rocksdb::SimpleTableIterator, rocksdb::MemTableIterator, and rocksdb::PrefixFilterIterator.
Referenced by rocksdb::DBTest::AllEntriesFor(), rocksdb::BlockBasedTable::ApproximateOffsetOf(), rocksdb::BuildTable(), rocksdb::CorruptionTest::Check(), rocksdb::CompareIterators(), rocksdb::DBDumperCommand::DoCommand(), rocksdb::ScanCommand::DoCommand(), rocksdb::BlockBasedTable::Get(), rocksdb::DBTest::IterStatus(), rocksdb::SimpleTableDBTest::IterStatus(), leveldb_iter_value(), rocksdb::MergeHelper::MergeUntil(), rocksdb::StressTest::MultiPrefixScan(), rocksdb::Version::PrefixMayMatch(), rocksdb::PrintContents(), rocksdb::Benchmark::ReadReverse(), rocksdb::SstFileReader::ReadSequential(), rocksdb::Benchmark::ReadSequential(), rocksdb::TtlTest::SleepCompactCheckIter(), rocksdb::TEST(), rocksdb::TtlIterator::timestamp(), rocksdb::Harness::ToString(), rocksdb::IteratorWrapper::value(), rocksdb::PrefixFilterIterator::value(), rocksdb::TtlIterator::value(), and rocksdb::KeyConvertingIterator::value().
Member Data Documentation
Cleanup rocksdb::Iterator::cleanup_ private
Definition at line 91 of file iterator.h.
Referenced by Iterator(), RegisterCleanup(), and ~Iterator().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/include/rocksdb/iterator.h
rippled/src/ripple/rocksdb/rocksdb/table/iterator.cc