rippled: rocksdb::BlockBasedTable Class Reference
rocksdb::BlockBasedTable Class Reference
#include <block_based_table_reader.h>
Classes
struct CachableEntry
struct Rep
Public Member Functions
bool PrefixMayMatch (const Slice &internal_prefix) override
Iterator * NewIterator (const ReadOptions &) override
Status Get (const ReadOptions &readOptions, const Slice &key, void *handle_context, bool(*result_handler)(void *handle_context, const Slice &k, const Slice &v, bool didIO), void(*mark_key_may_exist_handler)(void *handle_context)=nullptr) override
uint64_t ApproximateOffsetOf (const Slice &key) override
bool TEST_KeyInCache (const ReadOptions &options, const Slice &key) override
void SetupForCompaction () override
TableProperties & GetTableProperties () override
~BlockBasedTable ()
Public Member Functions inherited from rocksdb::TableReader
virtual ~TableReader ()
Static Public Member Functions
static Status Open (const Options &options, const EnvOptions &soptions, unique_ptr< RandomAccessFile > &&file, uint64_t file_size, unique_ptr< TableReader > *table_reader)
Static Public Attributes
static const std::string kFilterBlockPrefix
static const std::string kPropertiesBlock
Private Member Functions
CachableEntry< FilterBlockReader > GetFilter (bool no_io=false) const
Iterator * IndexBlockReader (const ReadOptions &options) const
void ReadMeta (const Footer &footer)
void ReadFilter (const Slice &filter_handle_value)
BlockBasedTable (Rep *rep)
BlockBasedTable (const TableReader &)=delete
void operator= (const TableReader &)=delete
Static Private Member Functions
static Iterator * BlockReader (void *, const ReadOptions &, const EnvOptions &soptions, const Slice &, bool for_compaction)
static Iterator * BlockReader (void *, const ReadOptions &, const Slice &, bool *didIO, bool for_compaction=false)
static Status GetBlock (const BlockBasedTable *table, const BlockHandle &handle, const ReadOptions &options, bool for_compaction, Tickers block_cache_miss_ticker, Tickers block_cache_hit_ticker, bool *didIO, CachableEntry< Block > *result)
static Status ReadProperties (const Slice &handle_value, Rep *rep)
static Status ReadMetaBlock (Rep *rep, std::unique_ptr< Block > *meta_block, std::unique_ptr< Iterator > *iter)
static FilterBlockReader * ReadFilter (const Slice &filter_handle_value, Rep *rep, size_t *filter_size=nullptr)
static Status ReadProperties (const Slice &handle_value, Rep *rep, TableProperties *properties)
static void SetupCacheKeyPrefix (Rep *rep)
static void GenerateCachePrefix (shared_ptr< Cache > cc, RandomAccessFile *file, char *buffer, size_t *size)
static void GenerateCachePrefix (shared_ptr< Cache > cc, WritableFile *file, char *buffer, size_t *size)
Private Attributes
Rep * rep_
bool compaction_optimized_
Static Private Attributes
static const size_t kMaxCacheKeyPrefixSize = kMaxVarint64Length*3+1
Friends
class TableCache
class BlockBasedTableBuilder
Detailed Description
Definition at line 38 of file block_based_table_reader.h.
Constructor & Destructor Documentation
rocksdb::BlockBasedTable::~BlockBasedTable ()
Definition at line 64 of file block_based_table_reader.cc.
References rep_.
{
   delete rep_;
 }
rocksdb::BlockBasedTable::BlockBasedTable (Rep * rep) inline explicit private
Definition at line 165 of file block_based_table_reader.h.
References rep_.
Referenced by Open().
                                      :
       compaction_optimized_(false) {
     rep_ = rep;
   }
rocksdb::BlockBasedTable::BlockBasedTable (const TableReader &) explicit private delete
Member Function Documentation
uint64_t rocksdb::BlockBasedTable::ApproximateOffsetOf (const Slice & key) override virtual
Implements rocksdb::TableReader.
Definition at line 1067 of file block_based_table_reader.cc.
References rocksdb::BlockHandle::DecodeFrom(), IndexBlockReader(), rocksdb::BlockBasedTable::Rep::metaindex_handle, rocksdb::BlockHandle::offset(), rocksdb::Status::ok(), rep_, rocksdb::Iterator::Seek(), rocksdb::Iterator::Valid(), and rocksdb::Iterator::value().
{
   Iterator* index_iter = IndexBlockReader(ReadOptions());
   index_iter->Seek(key);
   uint64_t result;
   if (index_iter->Valid()) {
     BlockHandle handle;
     Slice input = index_iter->value();
     Status s = handle.DecodeFrom(&input);
     if (s.ok()) {
       result = handle.offset();
     } else {
       // Strange: we can't decode the block handle in the index block.
       // We'll just return the offset of the metaindex block, which is
       // close to the whole file size for this case.
       result = rep_->metaindex_handle.offset();
     }
   } else {
     // key is past the last key in the file.  Approximate the offset
     // by returning the offset of the metaindex block (which is
     // right near the end of the file).
     result = rep_->metaindex_handle.offset();
   }
   delete index_iter;
   return result;
 }
Iterator * rocksdb::BlockBasedTable::BlockReader (void * arg, const ReadOptions & options, const EnvOptions & soptions, const Slice & index_value, bool for_compaction) static private
Definition at line 892 of file block_based_table_reader.cc.
Referenced by Get(), and NewIterator().
{
   return BlockReader(arg, options, index_value, nullptr, for_compaction);
 }
Iterator * rocksdb::BlockBasedTable::BlockReader (void * arg, const ReadOptions & options, const Slice & index_value, bool * didIO, bool for_compaction = false) static private
Definition at line 604 of file block_based_table_reader.cc.
References arg, rocksdb::Options::block_cache, rocksdb::BLOCK_CACHE_ADD, rocksdb::BLOCK_CACHE_COMPRESSED_HIT, rocksdb::BLOCK_CACHE_COMPRESSED_MISS, rocksdb::BLOCK_CACHE_DATA_HIT, rocksdb::BLOCK_CACHE_DATA_MISS, rocksdb::BLOCK_CACHE_HIT, rocksdb::PerfContext::block_cache_hit_count, rocksdb::BLOCK_CACHE_MISS, rocksdb::BumpPerfCount(), rocksdb::BlockBasedTable::Rep::cache_key_prefix, rocksdb::BlockBasedTable::Rep::cache_key_prefix_size, rocksdb::Options::comparator, rocksdb::BlockBasedTable::Rep::compressed_cache_key_prefix, rocksdb::BlockBasedTable::Rep::compressed_cache_key_prefix_size, rocksdb::Block::compressionType(), rocksdb::Block::data(), rocksdb::BlockHandle::DecodeFrom(), rocksdb::DeleteCachedBlock(), didIO, rocksdb::Slice::empty(), rocksdb::Options::env, rocksdb::BlockBasedTable::Rep::file, rocksdb::ReadOptions::fill_cache, rocksdb::Status::Incomplete(), rocksdb::Cache::Insert(), rocksdb::Block::isCachable(), rocksdb::kBlockCacheTier, kMaxCacheKeyPrefixSize, rocksdb::kMaxVarint64Length, rocksdb::kNoCompression, rocksdb::Cache::Lookup(), rocksdb::NewErrorIterator(), rocksdb::Block::NewIterator(), rocksdb::Status::ok(), rocksdb::BlockBasedTable::Rep::options, rocksdb::perf_context, rocksdb::READ_BLOCK_COMPACTION_MICROS, rocksdb::READ_BLOCK_GET_MICROS, rocksdb::ReadOptions::read_tier, rocksdb::RecordTick(), rocksdb::Iterator::RegisterCleanup(), rocksdb::Cache::Release(), rep_, rocksdb::Block::size(), rocksdb::Options::statistics, rocksdb::UncompressBlockContents(), rocksdb::crc32c::Value(), and rocksdb::Cache::Value().
{
   const bool no_io = (options.read_tier == kBlockCacheTier);
   BlockBasedTable* table = reinterpret_cast<BlockBasedTable*>(arg);
   Cache* block_cache = table->rep_->options.block_cache.get();
   Cache* block_cache_compressed = table->rep_->options.
                                     block_cache_compressed.get();
   std::shared_ptr<Statistics> statistics = table->rep_->options.statistics;
   Block* block = nullptr;
   Block* cblock = nullptr;
   Cache::Handle* cache_handle = nullptr;
   Cache::Handle* compressed_cache_handle = nullptr;
   BlockHandle handle;
   Slice input = index_value;
   Status s = handle.DecodeFrom(&input);
   // We intentionally allow extra stuff in index_value so that we
   // can add more features in the future.
   if (!s.ok()) {
     return NewErrorIterator(s);
   }
   if (block_cache != nullptr || block_cache_compressed != nullptr) {
     char cache_key[kMaxCacheKeyPrefixSize + kMaxVarint64Length];
     char compressed_cache_key[kMaxCacheKeyPrefixSize + kMaxVarint64Length];
     Slice key,  /* key to the block cache */
           ckey /* key to the compressed block cache */ ;
     // create key for block cache
     if (block_cache != nullptr) {
       key = GetCacheKey(
           table->rep_->cache_key_prefix,
           table->rep_->cache_key_prefix_size,
           handle,
           cache_key
       );
     }
     if (block_cache_compressed != nullptr) {
       ckey = GetCacheKey(
           table->rep_->compressed_cache_key_prefix,
           table->rep_->compressed_cache_key_prefix_size,
           handle,
           compressed_cache_key
       );
     }
     // Lookup uncompressed cache first
     if (block_cache != nullptr) {
       assert(!key.empty());
       cache_handle = block_cache->Lookup(key);
       if (cache_handle != nullptr) {
         block = reinterpret_cast<Block*>(block_cache->Value(cache_handle));
         RecordTick(statistics, BLOCK_CACHE_HIT);
         RecordTick(statistics, BLOCK_CACHE_DATA_HIT);
       } else {
         RecordTick(statistics, BLOCK_CACHE_MISS);
         RecordTick(statistics, BLOCK_CACHE_DATA_MISS);
       }
     }
     // If not found in uncompressed cache, lookup compressed cache
     if (block == nullptr && block_cache_compressed != nullptr) {
       assert(!ckey.empty());
       compressed_cache_handle = block_cache_compressed->Lookup(ckey);
       // if we found in the compressed cache, then uncompress and
       // insert into uncompressed cache
       if (compressed_cache_handle != nullptr) {
         // found compressed block
         cblock = reinterpret_cast<Block*>(block_cache_compressed->
                         Value(compressed_cache_handle));
         assert(cblock->compressionType() != kNoCompression);
         // Retrieve the uncompressed contents into a new buffer
         BlockContents contents;
         s = UncompressBlockContents(cblock->data(), cblock->size(),
                                     &contents);
         // Insert uncompressed block into block cache
         if (s.ok()) {
           block = new Block(contents); // uncompressed block
           assert(block->compressionType() == kNoCompression);
           if (block_cache != nullptr && block->isCachable() &&
               options.fill_cache) {
             cache_handle = block_cache->Insert(key, block, block->size(),
                                                &rocksdb::DeleteCachedBlock);
             assert(reinterpret_cast<Block*>(block_cache->Value(cache_handle))
                    == block);
           }
         }
         // Release hold on compressed cache entry
         block_cache_compressed->Release(compressed_cache_handle);
         RecordTick(statistics, BLOCK_CACHE_COMPRESSED_HIT);
       }
     }
     if (block != nullptr) {
       BumpPerfCount(&perf_context.block_cache_hit_count);
     } else if (no_io) {
       // Did not find in block_cache and can't do IO
       return NewErrorIterator(Status::Incomplete("no blocking io"));
     } else {
       Histograms histogram = for_compaction ?
         READ_BLOCK_COMPACTION_MICROS : READ_BLOCK_GET_MICROS;
       {  // block for stop watch
         StopWatch sw(table->rep_->options.env, statistics, histogram);
         s = ReadBlockFromFile(
               table->rep_->file.get(),
               options,
               handle,
               &cblock,
               table->rep_->options.env,
               didIO,
               block_cache_compressed == nullptr
             );
       }
       if (s.ok()) {
         assert(cblock->compressionType() == kNoCompression ||
                block_cache_compressed != nullptr);
         // Retrieve the uncompressed contents into a new buffer
         BlockContents contents;
         if (cblock->compressionType() != kNoCompression) {
           s = UncompressBlockContents(cblock->data(), cblock->size(),
                                       &contents);
         }
         if (s.ok()) {
           if (cblock->compressionType() != kNoCompression) {
             block = new Block(contents); // uncompressed block
           } else {
             block = cblock;
             cblock = nullptr;
           }
           if (block->isCachable() && options.fill_cache) {
             // Insert compressed block into compressed block cache.
             // Release the hold on the compressed cache entry immediately.
             if (block_cache_compressed != nullptr && cblock != nullptr) {
               compressed_cache_handle = block_cache_compressed->Insert(
                           ckey, cblock, cblock->size(), &rocksdb::DeleteCachedBlock);
               block_cache_compressed->Release(compressed_cache_handle);
               RecordTick(statistics, BLOCK_CACHE_COMPRESSED_MISS);
               cblock = nullptr;
             }
             // insert into uncompressed block cache
             assert((block->compressionType() == kNoCompression));
             if (block_cache != nullptr) {
               cache_handle = block_cache->Insert(
                 key, block, block->size(), &rocksdb::DeleteCachedBlock);
               RecordTick(statistics, BLOCK_CACHE_ADD);
               assert(reinterpret_cast<Block*>(block_cache->Value(
                      cache_handle))== block);
             }
           }
         }
       }
       if (cblock != nullptr) {
         delete cblock;
       }
     }
   } else if (no_io) {
     // Could not read from block_cache and can't do IO
     return NewErrorIterator(Status::Incomplete("no blocking io"));
   } else {
     s = ReadBlockFromFile(
         table->rep_->file.get(),
         options,
         handle,
         &block,
         table->rep_->options.env,
         didIO
       );
   }
   Iterator* iter;
   if (block != nullptr) {
     iter = block->NewIterator(table->rep_->options.comparator);
     if (cache_handle != nullptr) {
       iter->RegisterCleanup(&ReleaseBlock, block_cache, cache_handle);
     } else {
       iter->RegisterCleanup(&DeleteBlock, block, nullptr);
     }
   } else {
     iter = NewErrorIterator(s);
   }
   return iter;
 }
void rocksdb::BlockBasedTable::GenerateCachePrefix (shared_ptr< Cache > cc, RandomAccessFile * file, char * buffer, size_t * size) static private
Definition at line 109 of file block_based_table_reader.cc.
References rocksdb::EncodeVarint64(), rocksdb::RandomAccessFile::GetUniqueId(), and kMaxCacheKeyPrefixSize.
Referenced by rocksdb::BlockBasedTableBuilder::BlockBasedTableBuilder(), and SetupCacheKeyPrefix().
{
   // generate an id from the file
   *size = file->GetUniqueId(buffer, kMaxCacheKeyPrefixSize);
   // If the prefix wasn't generated or was too long,
   // create one from the cache.
   if (*size == 0) {
     char* end = EncodeVarint64(buffer, cc->NewId());
     *size = static_cast<size_t>(end - buffer);
   }
 }
void rocksdb::BlockBasedTable::GenerateCachePrefix (shared_ptr< Cache > cc, WritableFile * file, char * buffer, size_t * size) static private
Definition at line 123 of file block_based_table_reader.cc.
References rocksdb::EncodeVarint64(), rocksdb::WritableFile::GetUniqueId(), and kMaxCacheKeyPrefixSize.
{
   // generate an id from the file
   *size = file->GetUniqueId(buffer, kMaxCacheKeyPrefixSize);
   // If the prefix wasn't generated or was too long,
   // create one from the cache.
   if (*size == 0) {
     char* end = EncodeVarint64(buffer, cc->NewId());
     *size = static_cast<size_t>(end - buffer);
   }
 }
Status rocksdb::BlockBasedTable::Get (const ReadOptions & readOptions, const Slice & key, void * handle_context, bool(*)(void *handle_context, const Slice &k, const Slice &v, bool didIO) result_handler, void(*)(void *handle_context) mark_key_may_exist_handler = nullptr) override virtual
Implements rocksdb::TableReader.
Definition at line 993 of file block_based_table_reader.cc.
References rocksdb::Options::block_cache, BlockReader(), rocksdb::BLOOM_FILTER_USEFUL, rocksdb::BlockHandle::DecodeFrom(), didIO, GetFilter(), IndexBlockReader(), rocksdb::kBlockCacheTier, rocksdb::FilterBlockReader::KeyMayMatch(), rocksdb::Iterator::Next(), rocksdb::BlockHandle::offset(), rocksdb::Status::ok(), rocksdb::BlockBasedTable::Rep::options, rocksdb::ReadOptions::read_tier, rocksdb::RecordTick(), rep_, rocksdb::Iterator::Seek(), rocksdb::Options::statistics, rocksdb::Iterator::status(), rocksdb::Iterator::Valid(), and rocksdb::Iterator::value().
Referenced by TEST_KeyInCache().
{
   Status s;
   Iterator* iiter = IndexBlockReader(readOptions);
   auto filter_entry = GetFilter(readOptions.read_tier == kBlockCacheTier);
   FilterBlockReader* filter = filter_entry.value;
   bool done = false;
   for (iiter->Seek(key); iiter->Valid() && !done; iiter->Next()) {
     Slice handle_value = iiter->value();
     BlockHandle handle;
     bool may_not_exist_in_filter =
       filter != nullptr &&
       handle.DecodeFrom(&handle_value).ok() &&
       !filter->KeyMayMatch(handle.offset(), key);
     if (may_not_exist_in_filter) {
       // Not found
       // TODO: think about interaction with Merge. If a user key cannot
       // cross one data block, we should be fine.
       RecordTick(rep_->options.statistics, BLOOM_FILTER_USEFUL);
       break;
     } else {
       bool didIO = false;
       unique_ptr<Iterator> block_iter(
         BlockReader(this, readOptions, iiter->value(), &didIO));
       if (readOptions.read_tier && block_iter->status().IsIncomplete()) {
         // couldn't get block from block_cache
         // Update Saver.state to Found because we are only looking for whether
         // we can guarantee the key is not there when "no_io" is set
         (*mark_key_may_exist_handler)(handle_context);
         break;
       }
       // Call the *saver function on each entry/block until it returns false
       for (block_iter->Seek(key); block_iter->Valid(); block_iter->Next()) {
         if (!(*result_handler)(handle_context, block_iter->key(),
                                block_iter->value(), didIO)) {
           done = true;
           break;
         }
       }
       s = block_iter->status();
     }
   }
   filter_entry.Release(rep_->options.block_cache.get());
   if (s.ok()) {
     s = iiter->status();
   }
   delete iiter;
   return s;
 }
Status rocksdb::BlockBasedTable::GetBlock (const BlockBasedTable * table, const BlockHandle & handle, const ReadOptions & options, bool for_compaction, Tickers block_cache_miss_ticker, Tickers block_cache_hit_ticker, bool * didIO, CachableEntry< Block > * result) static private
Definition at line 525 of file block_based_table_reader.cc.
References rocksdb::Options::block_cache, rocksdb::BLOCK_CACHE_ADD, rocksdb::BlockBasedTable::CachableEntry< TValue >::cache_handle, rocksdb::BlockBasedTable::Rep::cache_key_prefix, rocksdb::BlockBasedTable::Rep::cache_key_prefix_size, rocksdb::DeleteCachedBlock(), didIO, rocksdb::Options::env, rocksdb::BlockBasedTable::Rep::file, rocksdb::ReadOptions::fill_cache, rocksdb::Status::Incomplete(), rocksdb::Cache::Insert(), rocksdb::kBlockCacheTier, kMaxCacheKeyPrefixSize, rocksdb::kMaxVarint64Length, rocksdb::Status::ok(), rocksdb::BlockBasedTable::Rep::options, rocksdb::READ_BLOCK_COMPACTION_MICROS, rocksdb::READ_BLOCK_GET_MICROS, rocksdb::ReadOptions::read_tier, rocksdb::RecordTick(), rep_, rocksdb::Options::statistics, rocksdb::BlockBasedTable::CachableEntry< TValue >::value, and rocksdb::Cache::Value().
Referenced by IndexBlockReader().
{
   bool no_io = options.read_tier == kBlockCacheTier;
   Cache* block_cache = table->rep_->options.block_cache.get();
   auto statistics = table->rep_->options.statistics;
   Status s;
   if (block_cache != nullptr) {
     char cache_key[kMaxCacheKeyPrefixSize + kMaxVarint64Length];
     auto key = GetCacheKey(
         table->rep_->cache_key_prefix,
         table->rep_->cache_key_prefix_size,
         handle,
         cache_key
     );
     entry->cache_handle = GetFromBlockCache(
         block_cache,
         key,
         block_cache_miss_ticker,
         block_cache_hit_ticker,
         table->rep_->options.statistics
     );
     if (entry->cache_handle != nullptr) {
       entry->value =
         reinterpret_cast<Block*>(block_cache->Value(entry->cache_handle));
     } else if (no_io) {
       // Did not find in block_cache and can't do IO
       return Status::Incomplete("no blocking io");
     } else {
       Histograms histogram = for_compaction ?
         READ_BLOCK_COMPACTION_MICROS : READ_BLOCK_GET_MICROS;
       {
         // block for stop watch
         StopWatch sw(table->rep_->options.env, statistics, histogram);
         s = ReadBlockFromFile(
               table->rep_->file.get(),
               options,
               handle,
               &entry->value,
               table->rep_->options.env,
               didIO
             );
       }
       if (s.ok()) {
         if (options.fill_cache && entry->value->isCachable()) {
           entry->cache_handle = block_cache->Insert(
             key, entry->value, entry->value->size(), &rocksdb::DeleteCachedBlock);
           RecordTick(statistics, BLOCK_CACHE_ADD);
         }
       }
     }
   } else if (no_io) {
     // Could not read from block_cache and can't do IO
     return Status::Incomplete("no blocking io");
   } else {
     s = ReadBlockFromFile(
         table->rep_->file.get(),
         options,
         handle,
         &entry->value,
         table->rep_->options.env,
         didIO
       );
   }
   return s;
 }
BlockBasedTable::CachableEntry< FilterBlockReader > rocksdb::BlockBasedTable::GetFilter (bool no_io = false) const private
Definition at line 797 of file block_based_table_reader.cc.
References rocksdb::Options::block_cache, rocksdb::BLOCK_CACHE_ADD, rocksdb::BLOCK_CACHE_FILTER_HIT, rocksdb::BLOCK_CACHE_FILTER_MISS, rocksdb::BlockBasedTable::Rep::cache_key_prefix, rocksdb::BlockBasedTable::Rep::cache_key_prefix_size, rocksdb::BlockBasedTable::Rep::filter, rocksdb::Options::filter_policy, rocksdb::Cache::Insert(), kFilterBlockPrefix, kMaxCacheKeyPrefixSize, rocksdb::kMaxVarint64Length, meta, rocksdb::BlockBasedTable::Rep::metaindex_handle, rocksdb::FilterPolicy::Name(), rocksdb::Status::ok(), rocksdb::BlockBasedTable::Rep::options, ReadFilter(), ReadMetaBlock(), rocksdb::RecordTick(), rep_, rocksdb::Options::statistics, and rocksdb::Cache::Value().
Referenced by Get(), and PrefixMayMatch().
{
   if (!rep_->options.filter_policy || !rep_->options.block_cache) {
     return {rep_->filter.get(), nullptr};
   }
   // Fetching from the cache
   Cache* block_cache = rep_->options.block_cache.get();
   char cache_key[kMaxCacheKeyPrefixSize + kMaxVarint64Length];
   auto key = GetCacheKey(
       rep_->cache_key_prefix,
       rep_->cache_key_prefix_size,
       rep_->metaindex_handle,
       cache_key
   );
   auto cache_handle = GetFromBlockCache(
     block_cache,
     key,
     BLOCK_CACHE_FILTER_MISS,
     BLOCK_CACHE_FILTER_HIT,
     rep_->options.statistics
   );
   FilterBlockReader* filter = nullptr;
   if (cache_handle != nullptr) {
      filter = reinterpret_cast<FilterBlockReader*>(
          block_cache->Value(cache_handle));
   } else if (no_io) {
     // Do not invoke any io.
     return CachableEntry<FilterBlockReader>();
   } else {
     size_t filter_size = 0;
     std::unique_ptr<Block> meta;
     std::unique_ptr<Iterator> iter;
     auto s = ReadMetaBlock(rep_, &meta, &iter);
     if (s.ok()) {
       std::string filter_block_key = kFilterBlockPrefix;
       filter_block_key.append(rep_->options.filter_policy->Name());
       iter->Seek(filter_block_key);
       if (iter->Valid() && iter->key() == Slice(filter_block_key)) {
         filter = ReadFilter(iter->value(), rep_, &filter_size);
         assert(filter);
         assert(filter_size > 0);
         cache_handle = block_cache->Insert(
           key, filter, filter_size, &DeleteCachedFilter);
         RecordTick(rep_->options.statistics, BLOCK_CACHE_ADD);
       }
     }
   }
   return { filter, cache_handle };
 }
TableProperties & rocksdb::BlockBasedTable::GetTableProperties () override virtual
Implements rocksdb::TableReader.
Definition at line 370 of file block_based_table_reader.cc.
References rep_, and rocksdb::BlockBasedTable::Rep::table_properties.
{
   return rep_->table_properties;
 }
Iterator * rocksdb::BlockBasedTable::IndexBlockReader (const ReadOptions & options) const private
Definition at line 854 of file block_based_table_reader.cc.
References rocksdb::Options::block_cache, rocksdb::BLOCK_CACHE_INDEX_HIT, rocksdb::BLOCK_CACHE_INDEX_MISS, rocksdb::BlockBasedTable::CachableEntry< TValue >::cache_handle, rocksdb::Options::comparator, didIO, GetBlock(), rocksdb::BlockBasedTable::Rep::index_block, rocksdb::BlockBasedTable::Rep::index_handle, rocksdb::NewErrorIterator(), rocksdb::BlockBasedTable::Rep::options, rocksdb::Iterator::RegisterCleanup(), rep_, and rocksdb::BlockBasedTable::CachableEntry< TValue >::value.
Referenced by ApproximateOffsetOf(), Get(), NewIterator(), and PrefixMayMatch().
{
   if (rep_->index_block) {
     assert (!rep_->options.block_cache);
     return rep_->index_block->NewIterator(rep_->options.comparator);
   }
   // get index block from cache
   assert (rep_->options.block_cache);
   bool didIO = false;
   CachableEntry<Block> entry;
   auto s = GetBlock(
       this,
       rep_->index_handle,
       options,
       false,  /* for compaction */
       BLOCK_CACHE_INDEX_MISS,
       BLOCK_CACHE_INDEX_HIT,
       &didIO,
       &entry
   );
   Iterator* iter;
   if (entry.value != nullptr) {
     iter = entry.value->NewIterator(rep_->options.comparator);
     if (entry.cache_handle) {
       iter->RegisterCleanup(
           &ReleaseBlock, rep_->options.block_cache.get(), entry.cache_handle
       );
     } else {
       iter->RegisterCleanup(&DeleteBlock, entry.value, nullptr);
     }
   } else {
     iter = NewErrorIterator(s);
   }
   return iter;
 }
Iterator * rocksdb::BlockBasedTable::NewIterator (const ReadOptions & options) override virtual
Implements rocksdb::TableReader.
Definition at line 974 of file block_based_table_reader.cc.
References BlockReader(), rocksdb::InternalKey::Encode(), IndexBlockReader(), rocksdb::kTypeValue, rocksdb::NewEmptyIterator(), rocksdb::NewTwoLevelIterator(), rocksdb::ReadOptions::prefix, PrefixMayMatch(), rep_, and rocksdb::BlockBasedTable::Rep::soptions.
{
   if (options.prefix) {
     InternalKey internal_prefix(*options.prefix, 0, kTypeValue);
     if (!PrefixMayMatch(internal_prefix.Encode())) {
       // nothing in this file can match the prefix, so we should not
       // bother doing I/O to this file when iterating.
       return NewEmptyIterator();
     }
   }
   return NewTwoLevelIterator(
            IndexBlockReader(options),
            &BlockBasedTable::BlockReader,
            const_cast<BlockBasedTable*>(this),
            options,
            rep_->soptions
          );
 }
Status rocksdb::BlockBasedTable::Open (const Options & options, const EnvOptions & soptions, unique_ptr< RandomAccessFile > && file, uint64_t file_size, unique_ptr< TableReader > * table_reader) static
Definition at line 241 of file block_based_table_reader.cc.
References rocksdb::Options::block_cache, BlockBasedTable(), rocksdb::Block::compressionType(), rocksdb::Footer::DecodeFrom(), rocksdb::Options::env, rocksdb::BlockBasedTable::Rep::file, rocksdb::BlockBasedTable::Rep::filter, rocksdb::Options::filter_policy, rocksdb::BlockBasedTable::Rep::index_block, rocksdb::BlockBasedTable::Rep::index_handle, rocksdb::Footer::index_handle(), rocksdb::Options::info_log, rocksdb::Status::InvalidArgument(), rocksdb::Footer::kEncodedLength, kFilterBlockPrefix, rocksdb::kNoCompression, kPropertiesBlock, rocksdb::Log(), meta, rocksdb::BlockBasedTable::Rep::metaindex_handle, rocksdb::Footer::metaindex_handle(), rocksdb::FilterPolicy::Name(), rocksdb::Status::ok(), rocksdb::BlockBasedTable::Rep::options, rocksdb::RandomAccessFile::Read(), ReadFilter(), ReadMetaBlock(), ReadProperties(), SetupCacheKeyPrefix(), rocksdb::Slice::size(), rocksdb::BlockBasedTable::Rep::table_properties, and rocksdb::Status::ToString().
Referenced by rocksdb::BlockBasedTableFactory::GetTableReader().
{
   table_reader->reset();
   if (size < Footer::kEncodedLength) {
     return Status::InvalidArgument("file is too short to be an sstable");
   }
   char footer_space[Footer::kEncodedLength];
   Slice footer_input;
   Status s = file->Read(size - Footer::kEncodedLength, Footer::kEncodedLength,
                         &footer_input, footer_space);
   if (!s.ok()) return s;
   // Check that we actually read the whole footer from the file. It may be
   // that size isn't correct.
   if (footer_input.size() != Footer::kEncodedLength) {
     return Status::InvalidArgument("file is too short to be an sstable");
   }
   Footer footer;
   s = footer.DecodeFrom(&footer_input);
   if (!s.ok()) return s;
   // We've successfully read the footer and the index block: we're
   // ready to serve requests.
   Rep* rep = new BlockBasedTable::Rep(soptions);
   rep->options = options;
   rep->file = std::move(file);
   rep->metaindex_handle = footer.metaindex_handle();
   rep->index_handle = footer.index_handle();
   SetupCacheKeyPrefix(rep);
   unique_ptr<BlockBasedTable> new_table(new BlockBasedTable(rep));
   // Read meta index
   std::unique_ptr<Block> meta;
   std::unique_ptr<Iterator> meta_iter;
   s = ReadMetaBlock(rep, &meta, &meta_iter);
   // Read the properties
   meta_iter->Seek(kPropertiesBlock);
   if (meta_iter->Valid() && meta_iter->key() == Slice(kPropertiesBlock)) {
     s = meta_iter->status();
     if (s.ok()) {
       s = ReadProperties(meta_iter->value(), rep, &rep->table_properties);
     }
     if (!s.ok()) {
       auto err_msg =
         "[Warning] Encountered error while reading data from properties "
         "block " + s.ToString();
       Log(rep->options.info_log, "%s", err_msg.c_str());
     }
   }
   // Initialize index/filter blocks. If block cache is not specified,
   // these blocks will be kept in member variables in Rep, which will
   // reside in the memory as long as this table object is alive; otherwise
   // they will be added to block cache.
   if (!options.block_cache) {
     Block* index_block = nullptr;
     // TODO: we never really verify check sum for index block
     s = ReadBlockFromFile(
         rep->file.get(),
         ReadOptions(),
         footer.index_handle(),
         &index_block,
         options.env
     );
     if (s.ok()) {
       assert(index_block->compressionType() == kNoCompression);
       rep->index_block.reset(index_block);
       // Set index block
       if (rep->options.filter_policy) {
         std::string key = kFilterBlockPrefix;
         key.append(rep->options.filter_policy->Name());
         meta_iter->Seek(key);
         if (meta_iter->Valid() && meta_iter->key() == Slice(key)) {
           rep->filter.reset(ReadFilter(meta_iter->value(), rep));
         }
       }
     } else {
       delete index_block;
     }
   } else {
     // Call IndexBlockReader() to implicitly add index to the block_cache
     unique_ptr<Iterator> iter(
         new_table->IndexBlockReader(ReadOptions())
     );
     s = iter->status();
     if (s.ok()) {
       // Call GetFilter() to implicitly add filter to the block_cache
       auto filter_entry = new_table->GetFilter();
       filter_entry.Release(options.block_cache.get());
     }
   }
   if (s.ok()) {
     *table_reader = std::move(new_table);
   }
   return s;
 }
void rocksdb::BlockBasedTable::operator= (const TableReader &) private delete
bool rocksdb::BlockBasedTable::PrefixMayMatch (const Slice & internal_prefix) override virtual
Implements rocksdb::TableReader.
Definition at line 912 of file block_based_table_reader.cc.
References rocksdb::Options::block_cache, rocksdb::BLOOM_FILTER_PREFIX_CHECKED, rocksdb::BLOOM_FILTER_PREFIX_USEFUL, rocksdb::BlockHandle::DecodeFrom(), rocksdb::ExtractUserKey(), rocksdb::Options::filter_policy, GetFilter(), IndexBlockReader(), rocksdb::kBlockCacheTier, rocksdb::BlockHandle::offset(), rocksdb::Status::ok(), rocksdb::BlockBasedTable::Rep::options, rocksdb::ReadOptions::read_tier, rocksdb::RecordTick(), rep_, and rocksdb::Options::statistics.
Referenced by NewIterator().
{
   bool may_match = true;
   Status s;
   if (!rep_->options.filter_policy) {
     return true;
   }
   // To prevent any io operation in this method, we set `read_tier` to make
   // sure we always read index or filter only when they have already been
   // loaded to memory.
   ReadOptions no_io_read_options;
   no_io_read_options.read_tier = kBlockCacheTier;
   unique_ptr<Iterator> iiter(
       IndexBlockReader(no_io_read_options)
   );
   iiter->Seek(internal_prefix);
   if (!iiter->Valid()) {
     // we're past end of file
     // if it's incomplete, it means that we avoided I/O
     // and we're not really sure that we're past the end
     // of the file
     may_match = iiter->status().IsIncomplete();
   } else if (ExtractUserKey(iiter->key()).starts_with(
               ExtractUserKey(internal_prefix))) {
     // we need to check for this subtle case because our only
     // guarantee is that "the key is a string >= last key in that data
     // block" according to the doc/table_format.txt spec.
     //
     // Suppose iiter->key() starts with the desired prefix; it is not
     // necessarily the case that the corresponding data block will
     // contain the prefix, since iiter->key() need not be in the
     // block.  However, the next data block may contain the prefix, so
     // we return true to play it safe.
     may_match = true;
   } else {
     // iiter->key() does NOT start with the desired prefix.  Because
     // Seek() finds the first key that is >= the seek target, this
     // means that iiter->key() > prefix.  Thus, any data blocks coming
     // after the data block corresponding to iiter->key() cannot
     // possibly contain the key.  Thus, the corresponding data block
     // is the only one which could potentially contain the prefix.
     Slice handle_value = iiter->value();
     BlockHandle handle;
     s = handle.DecodeFrom(&handle_value);
     assert(s.ok());
     auto filter_entry = GetFilter(true /* no io */);
     may_match =
       filter_entry.value == nullptr ||
       filter_entry.value->PrefixMayMatch(handle.offset(), internal_prefix);
     filter_entry.Release(rep_->options.block_cache.get());
   }
   RecordTick(rep_->options.statistics, BLOOM_FILTER_PREFIX_CHECKED);
   if (!may_match) {
     RecordTick(rep_->options.statistics, BLOOM_FILTER_PREFIX_USEFUL);
   }
   return may_match;
 }
void rocksdb::BlockBasedTable::ReadFilter (const Slice & filter_handle_value) private
Referenced by GetFilter(), and Open().
FilterBlockReader * rocksdb::BlockBasedTable::ReadFilter (const Slice & filter_handle_value, BlockBasedTable::Rep * rep, size_t * filter_size = nullptr) static private
Definition at line 408 of file block_based_table_reader.cc.
References rocksdb::BlockContents::data, rocksdb::BlockHandle::DecodeFrom(), rocksdb::Options::env, rocksdb::BlockBasedTable::Rep::file, ripple::Resource::ok, rocksdb::Status::ok(), rocksdb::BlockBasedTable::Rep::options, rocksdb::ReadBlockContents(), and rocksdb::Slice::size().
{
   Slice v = filter_handle_value;
   BlockHandle filter_handle;
   if (!filter_handle.DecodeFrom(&v).ok()) {
     return nullptr;
   }
   // TODO: We might want to unify with ReadBlockFromFile() if we start
   // requiring checksum verification in Table::Open.
   ReadOptions opt;
   BlockContents block;
   if (!ReadBlockContents(rep->file.get(), opt, filter_handle, &block,
                         rep->options.env, false).ok()) {
     return nullptr;
   }
   if (filter_size) {
     *filter_size = block.data.size();
   }
   return new FilterBlockReader(
        rep->options, block.data, block.heap_allocated);
 }
void rocksdb::BlockBasedTable::ReadMeta (const Footer & footer) private
Status rocksdb::BlockBasedTable::ReadMetaBlock (Rep * rep, std::unique_ptr< Block > * meta_block, std::unique_ptr< Iterator > * iter) static private
Definition at line 376 of file block_based_table_reader.cc.
References rocksdb::BytewiseComparator(), rocksdb::Options::env, rocksdb::BlockBasedTable::Rep::file, rocksdb::Options::info_log, rocksdb::Log(), meta, rocksdb::BlockBasedTable::Rep::metaindex_handle, rocksdb::Block::NewIterator(), rocksdb::Status::OK(), rocksdb::Status::ok(), rocksdb::BlockBasedTable::Rep::options, and rocksdb::Status::ToString().
Referenced by GetFilter(), and Open().
{
   // TODO(sanjay): Skip this if footer.metaindex_handle() size indicates
   // it is an empty block.
   //  TODO: we never really verify check sum for meta index block
   Block* meta = nullptr;
   Status s = ReadBlockFromFile(
       rep->file.get(),
       ReadOptions(),
       rep->metaindex_handle,
       &meta,
       rep->options.env);
     if (!s.ok()) {
       auto err_msg =
         "[Warning] Encountered error while reading data from properties"
         "block " + s.ToString();
       Log(rep->options.info_log, "%s", err_msg.c_str());
     }
   if (!s.ok()) {
     delete meta;
     return s;
   }
   meta_block->reset(meta);
   // meta block uses bytewise comparator.
   iter->reset(meta->NewIterator(BytewiseComparator()));
   return Status::OK();
 }
static Status rocksdb::BlockBasedTable::ReadProperties (const Slice & handle_value, Rep * rep) static private
Referenced by Open().
Status rocksdb::BlockBasedTable::ReadProperties (const Slice & handle_value, Rep * rep, TableProperties * properties) static private
Definition at line 435 of file block_based_table_reader.cc.
References rocksdb::BytewiseComparator(), rocksdb::Comparator::Compare(), rocksdb::TableProperties::data_size, rocksdb::BlockHandle::DecodeFrom(), rocksdb::Options::env, rocksdb::BlockBasedTable::Rep::file, rocksdb::TableProperties::filter_policy_name, rocksdb::TableProperties::filter_size, rocksdb::GetVarint64(), rocksdb::TableProperties::index_size, rocksdb::Options::info_log, rocksdb::Status::InvalidArgument(), rocksdb::BlockBasedTablePropertiesNames::kDataSize, rocksdb::BlockBasedTablePropertiesNames::kFilterPolicy, rocksdb::BlockBasedTablePropertiesNames::kFilterSize, rocksdb::BlockBasedTablePropertiesNames::kIndexSize, rocksdb::BlockBasedTablePropertiesNames::kNumDataBlocks, rocksdb::BlockBasedTablePropertiesNames::kNumEntries, rocksdb::BlockBasedTablePropertiesNames::kRawKeySize, rocksdb::BlockBasedTablePropertiesNames::kRawValueSize, rocksdb::Log(), rocksdb::Block::NewIterator(), rocksdb::TableProperties::num_data_blocks, rocksdb::TableProperties::num_entries, rocksdb::Status::ok(), rocksdb::BlockBasedTable::Rep::options, rocksdb::TableProperties::raw_key_size, rocksdb::TableProperties::raw_value_size, rocksdb::ReadBlockContents(), rocksdb::Status::ToString(), and rocksdb::TableProperties::user_collected_properties.
{
   assert(table_properties);
   Slice v = handle_value;
   BlockHandle handle;
   if (!handle.DecodeFrom(&v).ok()) {
     return Status::InvalidArgument("Failed to decode properties block handle");
   }
   BlockContents block_contents;
   Status s = ReadBlockContents(
       rep->file.get(),
       ReadOptions(),
       handle,
       &block_contents,
       rep->options.env,
       false
   );
   if (!s.ok()) {
     return s;
   }
   Block properties_block(block_contents);
   std::unique_ptr<Iterator> iter(
       properties_block.NewIterator(BytewiseComparator())
   );
   // All pre-defined properties of type uint64_t
   std::unordered_map<std::string, uint64_t*> predefined_uint64_properties = {
     { BlockBasedTablePropertiesNames::kDataSize,
       &table_properties->data_size },
     { BlockBasedTablePropertiesNames::kIndexSize,
       &table_properties->index_size },
     { BlockBasedTablePropertiesNames::kFilterSize,
       &table_properties->filter_size },
     { BlockBasedTablePropertiesNames::kRawKeySize,
       &table_properties->raw_key_size },
     { BlockBasedTablePropertiesNames::kRawValueSize,
       &table_properties->raw_value_size },
     { BlockBasedTablePropertiesNames::kNumDataBlocks,
       &table_properties->num_data_blocks },
     { BlockBasedTablePropertiesNames::kNumEntries,
       &table_properties->num_entries },
   };
   std::string last_key;
   for (iter->SeekToFirst(); iter->Valid(); iter->Next()) {
     s = iter->status();
     if (!s.ok()) {
       break;
     }
     auto key = iter->key().ToString();
     // properties block is strictly sorted with no duplicate key.
     assert(
         last_key.empty() ||
         BytewiseComparator()->Compare(key, last_key) > 0
     );
     last_key = key;
     auto raw_val = iter->value();
     auto pos = predefined_uint64_properties.find(key);
     if (pos != predefined_uint64_properties.end()) {
       // handle predefined rocksdb properties
       uint64_t val;
       if (!GetVarint64(&raw_val, &val)) {
         // skip malformed value
         auto error_msg =
           "[Warning] detect malformed value in properties meta-block:"
           "\tkey: " + key + "\tval: " + raw_val.ToString();
         Log(rep->options.info_log, "%s", error_msg.c_str());
         continue;
       }
       *(pos->second) = val;
     } else if (key == BlockBasedTablePropertiesNames::kFilterPolicy) {
       table_properties->filter_policy_name = raw_val.ToString();
     } else {
       // handle user-collected
       table_properties->user_collected_properties.insert(
           std::make_pair(key, raw_val.ToString())
       );
     }
   }
   return s;
 }
void rocksdb::BlockBasedTable::SetupCacheKeyPrefix (Rep * rep) static private
Definition at line 93 of file block_based_table_reader.cc.
References rocksdb::Options::block_cache, rocksdb::Options::block_cache_compressed, rocksdb::BlockBasedTable::Rep::cache_key_prefix, rocksdb::BlockBasedTable::Rep::cache_key_prefix_size, rocksdb::BlockBasedTable::Rep::compressed_cache_key_prefix, rocksdb::BlockBasedTable::Rep::compressed_cache_key_prefix_size, rocksdb::BlockBasedTable::Rep::file, GenerateCachePrefix(), kMaxCacheKeyPrefixSize, and rocksdb::BlockBasedTable::Rep::options.
Referenced by Open().
{
   assert(kMaxCacheKeyPrefixSize >= 10);
   rep->cache_key_prefix_size = 0;
   rep->compressed_cache_key_prefix_size = 0;
   if (rep->options.block_cache != nullptr) {
     GenerateCachePrefix(rep->options.block_cache, rep->file.get(),
                         &rep->cache_key_prefix[0],
                         &rep->cache_key_prefix_size);
   }
   if (rep->options.block_cache_compressed != nullptr) {
     GenerateCachePrefix(rep->options.block_cache_compressed, rep->file.get(),
                         &rep->compressed_cache_key_prefix[0],
                         &rep->compressed_cache_key_prefix_size);
   }
 }
void rocksdb::BlockBasedTable::SetupForCompaction () override virtual
Implements rocksdb::TableReader.
Definition at line 351 of file block_based_table_reader.cc.
References rocksdb::Options::access_hint_on_compaction_start, compaction_optimized_, rocksdb::BlockBasedTable::Rep::file, rocksdb::Options::NONE, rocksdb::RandomAccessFile::NORMAL, rocksdb::Options::NORMAL, rocksdb::BlockBasedTable::Rep::options, rep_, rocksdb::RandomAccessFile::SEQUENTIAL, rocksdb::Options::SEQUENTIAL, rocksdb::RandomAccessFile::WILLNEED, and rocksdb::Options::WILLNEED.
{
   switch (rep_->options.access_hint_on_compaction_start) {
     case Options::NONE:
       break;
     case Options::NORMAL:
       rep_->file->Hint(RandomAccessFile::NORMAL);
       break;
     case Options::SEQUENTIAL:
       rep_->file->Hint(RandomAccessFile::SEQUENTIAL);
       break;
     case Options::WILLNEED:
       rep_->file->Hint(RandomAccessFile::WILLNEED);
       break;
     default:
       assert(false);
   }
   compaction_optimized_ = true;
 }
bool rocksdb::BlockBasedTable::TEST_KeyInCache (const ReadOptions & options, const Slice & key) override virtual
Implements rocksdb::TableReader.
Definition at line 1057 of file block_based_table_reader.cc.
References didIO, Get(), rocksdb::Status::ok(), and rocksdb::SaveDidIO().
{
   // We use Get() as it has logic that checks whether we read the
   // block from the disk or not.
   bool didIO = false;
   Status s = Get(options, key, &didIO, SaveDidIO);
   assert(s.ok());
   return !didIO;
 }
Friends And Related Function Documentation
friend class BlockBasedTableBuilder friend
Definition at line 141 of file block_based_table_reader.h.
friend class TableCache friend
Definition at line 140 of file block_based_table_reader.h.
Member Data Documentation
bool rocksdb::BlockBasedTable::compaction_optimized_ private
Definition at line 101 of file block_based_table_reader.h.
Referenced by SetupForCompaction().
const std::string rocksdb::BlockBasedTable::kFilterBlockPrefix static
Initial value:
=
    "filter."
Definition at line 40 of file block_based_table_reader.h.
Referenced by rocksdb::BlockBasedTableBuilder::Finish(), GetFilter(), and Open().
const size_t rocksdb::BlockBasedTable::kMaxCacheKeyPrefixSize = kMaxVarint64Length*3+1 static private
Definition at line 177 of file block_based_table_reader.h.
Referenced by BlockReader(), GenerateCachePrefix(), GetBlock(), GetFilter(), and SetupCacheKeyPrefix().
const std::string rocksdb::BlockBasedTable::kPropertiesBlock static
Initial value:
=
    "rocksdb.properties"
Definition at line 41 of file block_based_table_reader.h.
Referenced by rocksdb::BlockBasedTableBuilder::Finish(), and Open().
Rep* rocksdb::BlockBasedTable::rep_ private
Definition at line 99 of file block_based_table_reader.h.
Referenced by ApproximateOffsetOf(), BlockBasedTable(), BlockReader(), Get(), GetBlock(), GetFilter(), GetTableProperties(), IndexBlockReader(), NewIterator(), PrefixMayMatch(), SetupForCompaction(), and ~BlockBasedTable().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/table/block_based_table_reader.h
rippled/src/ripple/rocksdb/rocksdb/table/block_based_table_reader.cc