rippled: beast::ScopedPointer< ObjectType > Class Template Reference
beast::ScopedPointer< ObjectType > Class Template Reference
#include <ScopedPointer.h>
Public Member Functions
ScopedPointer ()
ScopedPointer (ObjectType *const objectToTakePossessionOf)
ScopedPointer (ScopedPointer &objectToTransferFrom)
~ScopedPointer ()
ScopedPointer & operator= (ScopedPointer &objectToTransferFrom)
ScopedPointer & operator= (ObjectType *const newObjectToTakePossessionOf)
operator ObjectType * () const
ObjectType * get () const
ObjectType & operator* () const
ObjectType * operator-> () const
ObjectType * release ()
void reset (ObjectType *object_)
void swapWith (ScopedPointer< ObjectType > &other)
ObjectType * createCopy () const
Private Member Functions
const ScopedPointer * getAddress () const
Private Attributes
ObjectType * object
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
template<class ObjectType>
class beast::ScopedPointer< ObjectType >
This class holds a pointer which is automatically deleted when this object goes out of scope.
Once a pointer has been passed to a ScopedPointer, it will make sure that the pointer gets deleted when the ScopedPointer is deleted. Using the ScopedPointer on the stack or as member variables is a good way to use RAII to avoid accidentally leaking dynamically created objects.
A ScopedPointer can be used in pretty much the same way that you'd use a normal pointer to an object. If you use the assignment operator to assign a different object to a ScopedPointer, the old one will be automatically deleted.
Important note: The class is designed to hold a pointer to an object, NOT to an array! It calls delete on its payload, not delete[], so do not give it an array to hold! For that kind of purpose, you should be using HeapBlock or Array instead.
A const ScopedPointer is guaranteed not to lose ownership of its object or change the object to which it points during its lifetime. This means that making a copy of a const ScopedPointer is impossible, as that would involve the new copy taking ownership from the old one.
If you need to get a pointer out of a ScopedPointer without it being deleted, you can use the release() method.
Something to note is the main difference between this class and the std::auto_ptr class, which is that ScopedPointer provides a cast-to-object operator, wheras std::auto_ptr requires that you always call get() to retrieve the pointer. The advantages of providing the cast is that you don't need to call get(), so can use the ScopedPointer in pretty much exactly the same way as a raw pointer. The disadvantage is that the compiler is free to use the cast in unexpected and sometimes dangerous ways - in particular, it becomes difficult to return a ScopedPointer as the result of a function. To avoid this causing errors, ScopedPointer contains an overloaded constructor that should cause a syntax error in these circumstances, but it does mean that instead of returning a ScopedPointer from a function, you'd need to return a raw pointer (or use a std::auto_ptr instead).
Definition at line 73 of file ScopedPointer.h.
Constructor & Destructor Documentation
template<class ObjectType> beast::ScopedPointer< ObjectType >::ScopedPointer () inline
Creates a ScopedPointer containing a null pointer.
Definition at line 78 of file ScopedPointer.h.
         : object (nullptr)
     {
     }
template<class ObjectType> beast::ScopedPointer< ObjectType >::ScopedPointer (ObjectType *const objectToTakePossessionOf) inline
Creates a ScopedPointer that owns the specified object.
Definition at line 84 of file ScopedPointer.h.
         : object (objectToTakePossessionOf)
     {
     }
template<class ObjectType> beast::ScopedPointer< ObjectType >::ScopedPointer (ScopedPointer< ObjectType > & objectToTransferFrom) inline
Creates a ScopedPointer that takes its pointer from another ScopedPointer.
Because a pointer can only belong to one ScopedPointer, this transfers the pointer from the other object to this one, and the other object is reset to be a null pointer.
Definition at line 95 of file ScopedPointer.h.
         : object (objectToTransferFrom.object)
     {
         objectToTransferFrom.object = nullptr;
     }
template<class ObjectType> beast::ScopedPointer< ObjectType >::~ScopedPointer () inline
Destructor. This will delete the object that this ScopedPointer currently refers to.
Definition at line 104 of file ScopedPointer.h.
     {
         ContainerDeletePolicy <ObjectType>::destroy (object);
     }
Member Function Documentation
template<class ObjectType> ObjectType* beast::ScopedPointer< ObjectType >::createCopy () const inline
If the pointer is non-null, this will attempt to return a new copy of the object that is pointed to. If the pointer is null, this will safely return a nullptr.
Definition at line 213 of file ScopedPointer.h.
 { return createCopyIfNotNull (object); }
template<class ObjectType> ObjectType* beast::ScopedPointer< ObjectType >::get () const inline
Returns the object that this ScopedPointer refers to.
Definition at line 174 of file ScopedPointer.h.
 { return object; }
template<class ObjectType> const ScopedPointer* beast::ScopedPointer< ObjectType >::getAddress () const inline private
Definition at line 220 of file ScopedPointer.h.
Referenced by beast::ScopedPointer< beast::DirectoryIterator::NativeIterator::Pimpl >::operator=(), and beast::ScopedPointer< beast::DirectoryIterator::NativeIterator::Pimpl >::swapWith().
 { return this; }
template<class ObjectType> beast::ScopedPointer< ObjectType >::operator ObjectType * () const inline
Returns the object that this ScopedPointer refers to.
Definition at line 171 of file ScopedPointer.h.
 { return object; }
template<class ObjectType> ObjectType& beast::ScopedPointer< ObjectType >::operator* () const inline
Returns the object that this ScopedPointer refers to.
Definition at line 177 of file ScopedPointer.h.
 { return *object; }
template<class ObjectType> ObjectType* beast::ScopedPointer< ObjectType >::operator-> () const inline
Lets you access methods and properties of the object that this ScopedPointer refers to.
Definition at line 180 of file ScopedPointer.h.
 { return object; }
template<class ObjectType> ScopedPointer& beast::ScopedPointer< ObjectType >::operator= (ScopedPointer< ObjectType > & objectToTransferFrom) inline
Changes this ScopedPointer to point to a new object.
Because a pointer can only belong to one ScopedPointer, this transfers the pointer from the other object to this one, and the other object is reset to be a null pointer.
If this ScopedPointer already points to an object, that object will first be deleted.
Definition at line 118 of file ScopedPointer.h.
     {
         if (this != objectToTransferFrom.getAddress())
         {
             // Two ScopedPointers should never be able to refer to the same object - if
             // this happens, you must have done something dodgy!
             bassert (object == nullptr || object != objectToTransferFrom.object);
             ObjectType* const oldObject = object;
             object = objectToTransferFrom.object;
             objectToTransferFrom.object = nullptr;
             ContainerDeletePolicy <ObjectType>::destroy (oldObject);
         }
         return *this;
     }
template<class ObjectType> ScopedPointer& beast::ScopedPointer< ObjectType >::operator= (ObjectType *const newObjectToTakePossessionOf) inline
Changes this ScopedPointer to point to a new object.
If this ScopedPointer already points to an object, that object will first be deleted.
The pointer that you pass in may be a nullptr.
Definition at line 142 of file ScopedPointer.h.
     {
         if (object != newObjectToTakePossessionOf)
         {
             ObjectType* const oldObject = object;
             object = newObjectToTakePossessionOf;
             ContainerDeletePolicy <ObjectType>::destroy (oldObject);
         }
         return *this;
     }
template<class ObjectType> ObjectType* beast::ScopedPointer< ObjectType >::release () inline
Removes the current object from this ScopedPointer without deleting it. This will return the current object, and set the ScopedPointer to a null pointer.
Definition at line 186 of file ScopedPointer.h.
Referenced by beast::File::createInputStream(), beast::File::createOutputStream(), and ripple::RPCDoor::New().
 { ObjectType* const o = object; object = nullptr; return o; }
template<class ObjectType> void beast::ScopedPointer< ObjectType >::reset (ObjectType * object_) inline
Definition at line 188 of file ScopedPointer.h.
     {
         if (object != object_)
         {
             ContainerDeletePolicy <ObjectType>::destroy (object);
             object = object_;
         }
     }
template<class ObjectType> void beast::ScopedPointer< ObjectType >::swapWith (ScopedPointer< ObjectType > & other) inline
Swaps this object with that of another ScopedPointer. The two objects simply exchange their pointers.
Definition at line 201 of file ScopedPointer.h.
     {
         // Two ScopedPointers should never be able to refer to the same object - if
         // this happens, you must have done something dodgy!
         bassert (object != other.object || this == other.getAddress());
         std::swap (object, other.object);
     }
Member Data Documentation
template<class ObjectType> ObjectType* beast::ScopedPointer< ObjectType >::object private
Definition at line 217 of file ScopedPointer.h.
Referenced by beast::ScopedPointer< beast::DirectoryIterator::NativeIterator::Pimpl >::get(), beast::ScopedPointer< ripple::RippleSSLContext >::operator ripple::RippleSSLContext *(), beast::ScopedPointer< beast::DirectoryIterator::NativeIterator::Pimpl >::operator*(), beast::ScopedPointer< beast::DirectoryIterator::NativeIterator::Pimpl >::operator->(), beast::ScopedPointer< beast::DirectoryIterator::NativeIterator::Pimpl >::operator=(), beast::ScopedPointer< beast::DirectoryIterator::NativeIterator::Pimpl >::release(), beast::ScopedPointer< beast::DirectoryIterator::NativeIterator::Pimpl >::reset(), beast::ScopedPointer< beast::DirectoryIterator::NativeIterator::Pimpl >::ScopedPointer(), beast::ScopedPointer< beast::DirectoryIterator::NativeIterator::Pimpl >::swapWith(), and beast::ScopedPointer< beast::DirectoryIterator::NativeIterator::Pimpl >::~ScopedPointer().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/smart_ptr/ScopedPointer.h