rippled: beast::FileOutputStream Class Reference
beast::FileOutputStream Class Reference
#include <FileOutputStream.h>
Public Member Functions
FileOutputStream (const File &fileToWriteTo, size_t bufferSizeToUse=16384)
~FileOutputStream ()
const File & getFile () const
const Result & getStatus () const noexcept
bool failedToOpen () const noexcept
bool openedOk () const noexcept
Result truncate ()
void flush () override
std::int64_t getPosition () override
bool setPosition (std::int64_t) override
bool write (const void *, size_t) override
bool writeRepeatedByte (std::uint8_t byte, size_t numTimesToRepeat) override
Public Member Functions inherited from beast::OutputStream
virtual ~OutputStream ()
virtual bool writeByte (char byte)
virtual bool writeBool (bool boolValue)
virtual bool writeShort (short value)
virtual bool writeShortBigEndian (short value)
virtual bool writeInt32 (std::int32_t value)
virtual bool writeInt (int value)
virtual bool writeInt32BigEndian (std::int32_t value)
virtual bool writeIntBigEndian (int value)
virtual bool writeInt64 (std::int64_t value)
virtual bool writeInt64BigEndian (std::int64_t value)
virtual bool writeFloat (float value)
virtual bool writeFloatBigEndian (float value)
virtual bool writeDouble (double value)
virtual bool writeDoubleBigEndian (double value)
template<class T >
bool writeType (T value)
template<class T >
bool writeTypeBigEndian (T value)
virtual bool writeCompressedInt (int value)
virtual bool writeString (const String &text)
virtual bool writeText (const String &text, bool asUTF16, bool writeUTF16ByteOrderMark)
virtual int writeFromInputStream (InputStream &source, std::int64_t maxNumBytesToWrite)
void setNewLineString (const String &newLineString)
const String & getNewLineString () const noexcept
template<>
bool writeType (char v)
template<>
bool writeType (short v)
template<>
bool writeType (unsigned char v)
template<>
bool writeType (unsigned short v)
template<>
bool writeType (float v)
template<>
bool writeType (double v)
template<>
bool writeTypeBigEndian (char v)
template<>
bool writeTypeBigEndian (short v)
template<>
bool writeTypeBigEndian (unsigned char v)
template<>
bool writeTypeBigEndian (unsigned short v)
template<>
bool writeTypeBigEndian (float v)
template<>
bool writeTypeBigEndian (double v)
Private Member Functions
void openHandle ()
void closeHandle ()
void flushInternal ()
bool flushBuffer ()
std::int64_t setPositionInternal (std::int64_t)
std::ptrdiff_t writeInternal (const void *, size_t)
Private Attributes
File file
void * fileHandle
Result status
std::int64_t currentPosition
size_t bufferSize
size_t bytesInBuffer
HeapBlock< char > buffer
Additional Inherited Members
Protected Member Functions inherited from beast::OutputStream
OutputStream ()
Detailed Description
An output stream that writes into a local file.
See Also
OutputStream, FileInputStream, File::createOutputStream
Definition at line 36 of file FileOutputStream.h.
Constructor & Destructor Documentation
beast::FileOutputStream::FileOutputStream (const File & fileToWriteTo, size_t bufferSizeToUse = 16384)
Creates a FileOutputStream.
If the file doesn't exist, it will first be created. If the file can't be created or opened, the failedToOpen() method will return true.
If the file already exists when opened, the stream's write-postion will be set to the end of the file. To overwrite an existing file, use File::deleteFile() before opening the stream, or use setPosition(0) after it's opened (although this won't truncate the file).
See Also
TemporaryFile
Definition at line 30 of file FileOutputStream.cpp.
References openHandle().
     : file (f),
       fileHandle (nullptr),
       status (Result::ok()),
       currentPosition (0),
       bufferSize (bufferSizeToUse),
       bytesInBuffer (0),
       buffer (bmax (bufferSizeToUse, (size_t) 16))
 {
     openHandle();
 }
beast::FileOutputStream::~FileOutputStream ()
Destructor.
Definition at line 42 of file FileOutputStream.cpp.
References closeHandle(), flushBuffer(), and flushInternal().
 {
     flushBuffer();
     flushInternal();
     closeHandle();
 }
Member Function Documentation
void beast::FileOutputStream::closeHandle () private
Definition at line 363 of file posix_SharedCode.h.
References fileHandle.
Referenced by ~FileOutputStream().
 {
     if (fileHandle != 0)
     {
         close (getFD (fileHandle));
         fileHandle = 0;
     }
 }
bool beast::FileOutputStream::failedToOpen () const inline noexcept
Returns true if the stream couldn't be opened for some reason.
See Also
getResult()
Definition at line 75 of file FileOutputStream.h.
References beast::Result::failed(), and status.
Referenced by beast::File::appendText(), and beast::File::copyInternal().
 { return status.failed(); }
void beast::FileOutputStream::flush () override virtual
If the stream is using a buffer, this will ensure it gets written out to the destination.
Implements beast::OutputStream.
Definition at line 78 of file FileOutputStream.cpp.
References flushBuffer(), and flushInternal().
Referenced by truncate().
 {
     flushBuffer();
     flushInternal();
 }
bool beast::FileOutputStream::flushBuffer () private
Definition at line 65 of file FileOutputStream.cpp.
References buffer, bytesInBuffer, ripple::Resource::ok, and writeInternal().
Referenced by flush(), setPosition(), write(), and ~FileOutputStream().
 {
     bool ok = true;
     if (bytesInBuffer > 0)
     {
         ok = (writeInternal (buffer, bytesInBuffer) == (std::ptrdiff_t) bytesInBuffer);
         bytesInBuffer = 0;
     }
     return ok;
 }
void beast::FileOutputStream::flushInternal () private
Definition at line 387 of file posix_SharedCode.h.
References file, fileHandle, beast::File::getFullPathName(), and status.
Referenced by flush(), and ~FileOutputStream().
 {
     if (fileHandle != 0)
     {
         if (fsync (getFD (fileHandle)) == -1)
             status = getResultForErrno();
        #if BEAST_ANDROID
         // This stuff tells the OS to asynchronously update the metadata
         // that the OS has cached aboud the file - this metadata is used
         // when the device is acting as a USB drive, and unless it's explicitly
         // refreshed, it'll get out of step with the real file.
         const LocalRef<jstring> t (javaString (file.getFullPathName()));
         android.activity.callVoidMethod (BeastAppActivity.scanFile, t.get());
        #endif
     }
 }
const File& beast::FileOutputStream::getFile () const inline
Returns the file that this stream is writing to.
Definition at line 64 of file FileOutputStream.h.
References file.
 { return file; }
std::int64_t beast::FileOutputStream::getPosition () override virtual
Returns the stream's current position.
See Also
setPosition
Implements beast::OutputStream.
Definition at line 49 of file FileOutputStream.cpp.
References currentPosition.
 {
     return currentPosition;
 }
const Result& beast::FileOutputStream::getStatus () const inline noexcept
Returns the status of the file stream. The result will be ok if the file opened successfully. If an error occurs while opening or writing to the file, this will contain an error message.
Definition at line 70 of file FileOutputStream.h.
References status.
Referenced by beast::File::create().
 { return status; }
bool beast::FileOutputStream::openedOk () const inline noexcept
Returns true if the stream opened without problems.
See Also
getResult()
Definition at line 80 of file FileOutputStream.h.
References status, and beast::Result::wasOk().
Referenced by beast::File::appendData().
 { return status.wasOk(); }
void beast::FileOutputStream::openHandle () private
Definition at line 327 of file posix_SharedCode.h.
References currentPosition, beast::File::exists(), file, fileHandle, beast::File::getFullPathName(), status, and beast::String::toUTF8().
Referenced by FileOutputStream().
 {
     if (file.exists())
     {
         const int f = open (file.getFullPathName().toUTF8(), O_RDWR, 00644);
         if (f != -1)
         {
             currentPosition = lseek (f, 0, SEEK_END);
             if (currentPosition >= 0)
             {
                 fileHandle = fdToVoidPointer (f);
             }
             else
             {
                 status = getResultForErrno();
                 close (f);
             }
         }
         else
         {
             status = getResultForErrno();
         }
     }
     else
     {
         const int f = open (file.getFullPathName().toUTF8(), O_RDWR + O_CREAT, 00644);
         if (f != -1)
             fileHandle = fdToVoidPointer (f);
         else
             status = getResultForErrno();
     }
 }
bool beast::FileOutputStream::setPosition (std::int64_t newPosition) override virtual
Tries to move the stream's output position.
Not all streams will be able to seek to a new position - this will return false if it fails to work.
See Also
getPosition
Implements beast::OutputStream.
Definition at line 54 of file FileOutputStream.cpp.
References beast::beast_fileSetPosition(), currentPosition, fileHandle, and flushBuffer().
 {
     if (newPosition != currentPosition)
     {
         flushBuffer();
         currentPosition = beast_fileSetPosition (fileHandle, newPosition);
     }
     return newPosition == currentPosition;
 }
std::int64_t beast::FileOutputStream::setPositionInternal (std::int64_t) private
Result beast::FileOutputStream::truncate ()
Attempts to truncate the file to the current write position. To truncate a file to a specific size, first use setPosition() to seek to the appropriate location, and then call this method.
Definition at line 405 of file posix_SharedCode.h.
References currentPosition, fileHandle, flush(), and status.
 {
     if (fileHandle == 0)
         return status;
     flush();
     return getResultForReturnValue (ftruncate (getFD (fileHandle), (off_t) currentPosition));
 }
bool beast::FileOutputStream::write (const void * dataToWrite, size_t numberOfBytes) override virtual
Writes a block of data to the stream.
When creating a subclass of OutputStream, this is the only write method that needs to be overloaded - the base class has methods for writing other types of data which use this to do the work.
Parameters
dataToWrite the target buffer to receive the data. This must not be null.
numberOfBytes the number of bytes to write.
Returns
false if the write operation fails for some reason
Implements beast::OutputStream.
Definition at line 84 of file FileOutputStream.cpp.
References bassert, buffer, bufferSize, bytesInBuffer, currentPosition, flushBuffer(), and writeInternal().
Referenced by beast::File::appendData(), beast::File_test::run(), and writeInternal().
 {
     bassert (src != nullptr && ((std::ptrdiff_t) numBytes) >= 0);
     if (bytesInBuffer + numBytes < bufferSize)
     {
         memcpy (buffer + bytesInBuffer, src, numBytes);
         bytesInBuffer += numBytes;
         currentPosition += numBytes;
     }
     else
     {
         if (! flushBuffer())
             return false;
         if (numBytes < bufferSize)
         {
             memcpy (buffer + bytesInBuffer, src, numBytes);
             bytesInBuffer += numBytes;
             currentPosition += numBytes;
         }
         else
         {
             const std::ptrdiff_t bytesWritten = writeInternal (src, numBytes);
             if (bytesWritten < 0)
                 return false;
             currentPosition += bytesWritten;
             return bytesWritten == (std::ptrdiff_t) numBytes;
         }
     }
     return true;
 }
std::ptrdiff_t beast::FileOutputStream::writeInternal (const void * data, size_t numBytes) private
Definition at line 372 of file posix_SharedCode.h.
References fileHandle, status, and write().
Referenced by flushBuffer(), and write().
 {
     std::ptrdiff_t result = 0;
     if (fileHandle != 0)
     {
         result = ::write (getFD (fileHandle), data, numBytes);
         if (result == -1)
             status = getResultForErrno();
     }
     return result;
 }
bool beast::FileOutputStream::writeRepeatedByte (std::uint8_t byte, size_t numTimesToRepeat) override virtual
Writes a byte to the output stream a given number of times.
Returns
false if the write operation fails for some reason
Reimplemented from beast::OutputStream.
Definition at line 120 of file FileOutputStream.cpp.
References bassert, buffer, bufferSize, bytesInBuffer, currentPosition, and beast::OutputStream::writeRepeatedByte().
 {
     bassert (((std::ptrdiff_t) numBytes) >= 0);
     if (bytesInBuffer + numBytes < bufferSize)
     {
         memset (buffer + bytesInBuffer, byte, numBytes);
         bytesInBuffer += numBytes;
         currentPosition += numBytes;
         return true;
     }
     return OutputStream::writeRepeatedByte (byte, numBytes);
 }
Member Data Documentation
HeapBlock<char> beast::FileOutputStream::buffer private
Definition at line 103 of file FileOutputStream.h.
Referenced by flushBuffer(), write(), and writeRepeatedByte().
size_t beast::FileOutputStream::bufferSize private
Definition at line 102 of file FileOutputStream.h.
Referenced by write(), and writeRepeatedByte().
size_t beast::FileOutputStream::bytesInBuffer private
Definition at line 102 of file FileOutputStream.h.
Referenced by flushBuffer(), write(), and writeRepeatedByte().
std::int64_t beast::FileOutputStream::currentPosition private
Definition at line 101 of file FileOutputStream.h.
Referenced by getPosition(), openHandle(), setPosition(), truncate(), write(), and writeRepeatedByte().
File beast::FileOutputStream::file private
Definition at line 98 of file FileOutputStream.h.
Referenced by flushInternal(), getFile(), and openHandle().
void* beast::FileOutputStream::fileHandle private
Definition at line 99 of file FileOutputStream.h.
Referenced by closeHandle(), flushInternal(), openHandle(), setPosition(), truncate(), and writeInternal().
Result beast::FileOutputStream::status private
Definition at line 100 of file FileOutputStream.h.
Referenced by failedToOpen(), flushInternal(), getStatus(), openedOk(), openHandle(), truncate(), and writeInternal().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_core/files/FileOutputStream.h
rippled/src/beast/modules/beast_core/files/FileOutputStream.cpp
rippled/src/beast/modules/beast_core/native/posix_SharedCode.h
rippled/src/beast/modules/beast_core/native/win32_Files.cpp