rippled: ripple::LocalTxsImp Class Reference
ripple::LocalTxsImp Class Reference
Public Member Functions
LocalTxsImp ()
void push_back (LedgerIndex index, SerializedTransaction::ref txn) override
bool can_remove (LocalTx &txn, Ledger::ref ledger)
void apply (TransactionEngine &engine) override
void sweep (Ledger::ref validLedger) override
std::size_t size () override
Public Member Functions inherited from ripple::LocalTxs
virtual ~LocalTxs ()=default
Private Attributes
std::mutex m_lock
std::list< LocalTx > m_txns
Additional Inherited Members
Static Public Member Functions inherited from ripple::LocalTxs
static std::unique_ptr< LocalTxs > New ()
Detailed Description
Definition at line 106 of file LocalTxs.cpp.
Constructor & Destructor Documentation
ripple::LocalTxsImp::LocalTxsImp () inline
Definition at line 110 of file LocalTxs.cpp.
     { }
Member Function Documentation
void ripple::LocalTxsImp::apply (TransactionEngine & engine) inline override virtual
Implements ripple::LocalTxs.
Definition at line 141 of file LocalTxs.cpp.
References ripple::TransactionEngine::applyTransaction(), m_lock, m_txns, and ripple::tapOPEN_LEDGER.
     {
         CanonicalTXSet tset (uint256 {});
         // Get the set of local transactions as a canonical
         // set (so they apply in a valid order)
         {
             std::lock_guard <std::mutex> lock (m_lock);
             for (auto& it : m_txns)
                 tset.push_back (it.getTX());
         }
         for (auto it : tset)
         {
             try
             {
                 TransactionEngineParams parms = tapOPEN_LEDGER;
                 bool didApply;
                 engine.applyTransaction (*it.second, parms, didApply);
             }
             catch (...)
             {
                 // Nothing special we need to do.
                 // It's possible a cleverly malformed transaction or
                 // corrupt back end database could cause an exception
                 // during transaction processing.
             }
         }
     }
bool ripple::LocalTxsImp::can_remove (LocalTx & txn, Ledger::ref ledger) inline
Definition at line 121 of file LocalTxs.cpp.
References ripple::LocalTx::getAccount(), ripple::LocalTx::getID(), ripple::LocalTx::getSeq(), and ripple::LocalTx::isExpired().
Referenced by sweep().
     {
         if (txn.isExpired (ledger->getLedgerSeq ()))
             return true;
         if (ledger->hasTransaction (txn.getID ()))
             return true;
         SLE::pointer sle = ledger->getAccountRoot (txn.getAccount ());
         if (!sle)
             return false;
         if (sle->getFieldU32 (sfSequence) > txn.getSeq ())
             return true;
         return false;
     }
void ripple::LocalTxsImp::push_back (LedgerIndex index, SerializedTransaction::ref txn) inline override virtual
Implements ripple::LocalTxs.
Definition at line 114 of file LocalTxs.cpp.
References m_lock, and m_txns.
     {
         std::lock_guard <std::mutex> lock (m_lock);
         m_txns.emplace_back (index, txn);
     }
std::size_t ripple::LocalTxsImp::size () inline override virtual
Implements ripple::LocalTxs.
Definition at line 188 of file LocalTxs.cpp.
References m_lock, and m_txns.
     {
         std::lock_guard <std::mutex> lock (m_lock);
         return m_txns.size ();
     }
void ripple::LocalTxsImp::sweep (Ledger::ref validLedger) inline override virtual
Implements ripple::LocalTxs.
Definition at line 175 of file LocalTxs.cpp.
References can_remove(), m_lock, and m_txns.
     {
         std::lock_guard <std::mutex> lock (m_lock);
         for (auto it = m_txns.begin (); it != m_txns.end (); )
         {
             if (can_remove (*it, validLedger))
                 it = m_txns.erase (it);
             else
                 ++it;
         }
     }
Member Data Documentation
std::mutex ripple::LocalTxsImp::m_lock private
Definition at line 197 of file LocalTxs.cpp.
Referenced by apply(), push_back(), size(), and sweep().
std::list<LocalTx> ripple::LocalTxsImp::m_txns private
Definition at line 198 of file LocalTxs.cpp.
Referenced by apply(), push_back(), size(), and sweep().
The documentation for this class was generated from the following file:
rippled/src/ripple_app/tx/LocalTxs.cpp