rippled: ripple::STPath Class Reference
ripple::STPath Class Reference
#include <SerializedTypes.h>
Public Member Functions
STPath ()
STPath (const std::vector< STPathElement > &p)
void printDebug ()
int size () const
void reserve (size_t n)
bool isEmpty () const
const STPathElement & getElement (int offset) const
const STPathElement & getElement (int offset)
void addElement (const STPathElement &e)
void clear ()
bool hasSeen (const uint160 &uAccountId, const uint160 &uCurrencyID, const uint160 &uIssuerID) const
Json::Value getJson (int) const
std::vector< STPathElement >
::iterator begin ()
std::vector< STPathElement >
::iterator end ()
std::vector< STPathElement >
::const_iterator begin () const
std::vector< STPathElement >
::const_iterator end () const
bool operator== (const STPath &t) const
void setCanonical (const STPath &spExpanded)
Private Attributes
std::vector< STPathElement > mPath
Friends
class STPathSet
class Pathfinder
Detailed Description
Definition at line 1272 of file SerializedTypes.h.
Constructor & Destructor Documentation
ripple::STPath::STPath () inline
Definition at line 1275 of file SerializedTypes.h.
     {
         ;
     }
ripple::STPath::STPath (const std::vector< STPathElement > & p) inline
Definition at line 1279 of file SerializedTypes.h.
                                                : mPath (p)
     {
         ;
     }
Member Function Documentation
void ripple::STPath::addElement (const STPathElement & e) inline
Definition at line 1305 of file SerializedTypes.h.
Referenced by ripple::Pathfinder::addLink(), and ripple::STParsedJSON::parse().
     {
         mPath.push_back (e);
     }
std::vector<STPathElement>::iterator ripple::STPath::begin () inline
Definition at line 1320 of file SerializedTypes.h.
Referenced by ripple::range_begin().
     {
         return mPath.begin ();
     }
std::vector<STPathElement>::const_iterator ripple::STPath::begin () const inline
Definition at line 1328 of file SerializedTypes.h.
     {
         return mPath.begin ();
     }
void ripple::STPath::clear () inline
Definition at line 1309 of file SerializedTypes.h.
     {
         mPath.clear ();
     }
std::vector<STPathElement>::iterator ripple::STPath::end () inline
Definition at line 1324 of file SerializedTypes.h.
Referenced by ripple::Pathfinder::isNoRippleOut(), and ripple::range_end().
     {
         return mPath.end ();
     }
std::vector<STPathElement>::const_iterator ripple::STPath::end () const inline
Definition at line 1332 of file SerializedTypes.h.
     {
         return mPath.end ();
     }
const STPathElement& ripple::STPath::getElement (int offset) const inline
Definition at line 1297 of file SerializedTypes.h.
Referenced by hasSeen(), and ripple::PathState::setExpanded().
     {
         return mPath[offset];
     }
const STPathElement& ripple::STPath::getElement (int offset) inline
Definition at line 1301 of file SerializedTypes.h.
     {
         return mPath[offset];
     }
Json::Value ripple::STPath::getJson (int) const
Definition at line 499 of file SerializedTypes.cpp.
References Json::Value::append(), Json::arrayValue, ripple::RippleAddress::createHumanAccountID(), ripple::STAmount::createHumanCurrency(), mPath, Json::objectValue, ripple::strHex(), ripple::STPathElement::typeAccount, ripple::STPathElement::typeCurrency, and ripple::STPathElement::typeIssuer.
Referenced by ripple::Pathfinder::addLink(), ripple::Pathfinder::filterPaths(), and ripple::PathState::setExpanded().
 {
     Json::Value ret (Json::arrayValue);
     BOOST_FOREACH (std::vector<STPathElement>::const_iterator::value_type it, mPath)
     {
         Json::Value elem (Json::objectValue);
         int         iType   = it.getNodeType ();
         elem["type"]        = iType;
         elem["type_hex"]    = strHex (iType);
         if (iType & STPathElement::typeAccount)
             elem["account"]     = RippleAddress::createHumanAccountID (it.getAccountID ());
         if (iType & STPathElement::typeCurrency)
             elem["currency"]    = STAmount::createHumanCurrency (it.getCurrency ());
         if (iType & STPathElement::typeIssuer)
             elem["issuer"]      = RippleAddress::createHumanAccountID (it.getIssuerID ());
         ret.append (elem);
     }
     return ret;
 }
bool ripple::STPath::hasSeen (const uint160 & uAccountId, const uint160 & uCurrencyID, const uint160 & uIssuerID) const
Definition at line 484 of file SerializedTypes.cpp.
References ripple::STPathElement::getAccountID(), ripple::STPathElement::getCurrency(), getElement(), ripple::STPathElement::getIssuerID(), and mPath.
Referenced by ripple::Pathfinder::addLink().
 {
     for (int i = 0; i < mPath.size (); ++i)
     {
         const STPathElement& ele = getElement (i);
         if (ele.getAccountID () == uAccountId
                 && ele.getCurrency () == uCurrencyID
                 && ele.getIssuerID () == uIssuerID)
             return true;
     }
     return false;
 }
bool ripple::STPath::isEmpty () const inline
Definition at line 1293 of file SerializedTypes.h.
Referenced by ripple::Pathfinder::addLink(), and ripple::Pathfinder::findPaths().
     {
         return mPath.empty ();
     }
bool ripple::STPath::operator== (const STPath & t) const inline
Definition at line 1337 of file SerializedTypes.h.
References mPath.
     {
         return mPath == t.mPath;
     }
void ripple::STPath::printDebug ()
Definition at line 71 of file SerializedTypes.cpp.
References ripple::RippleAddress::humanAccountID(), mPath, and ripple::RippleAddress::setAccountID().
 {
     Log::out() << "STPath:";
     for (int i = 0; i < mPath.size (); i++)
     {
         RippleAddress nad;
         nad.setAccountID (mPath[i].mAccountID);
         Log::out() << "   " << i << ": " << nad.humanAccountID ();
     }
 }
void ripple::STPath::reserve (size_t n) inline
Definition at line 1289 of file SerializedTypes.h.
     {
         mPath.reserve(n);
     }
void ripple::STPath::setCanonical (const STPath & spExpanded)
int ripple::STPath::size () const inline
Definition at line 1285 of file SerializedTypes.h.
Referenced by ripple::RPCHandler::doRipplePathFind(), ripple::PathRequest::doUpdate(), ripple::Pathfinder::filterPaths(), ripple::Pathfinder::isNoRippleOut(), and ripple::PathState::setExpanded().
     {
         return mPath.size ();
     }
Friends And Related Function Documentation
friend class Pathfinder friend
Definition at line 1346 of file SerializedTypes.h.
friend class STPathSet friend
Definition at line 1345 of file SerializedTypes.h.
Member Data Documentation
std::vector<STPathElement> ripple::STPath::mPath private
Definition at line 1348 of file SerializedTypes.h.
Referenced by ripple::Pathfinder::addLink(), ripple::STPathSet::assembleAdd(), ripple::Pathfinder::filterPaths(), getJson(), hasSeen(), operator==(), and printDebug().
The documentation for this class was generated from the following files:
rippled/src/ripple_data/protocol/SerializedTypes.h
rippled/src/ripple_data/protocol/SerializedTypes.cpp