rippled: ripple::SqliteDatabase Class Reference
ripple::SqliteDatabase Class Reference
#include <SqliteDatabase.h>
Public Member Functions
SqliteDatabase (char const *host)
~SqliteDatabase ()
void connect ()
void disconnect ()
bool executeSQL (const char *sql, bool fail_okay)
int getNumRowsAffected ()
bool startIterRows (bool finalize)
void endIterRows ()
bool getNextRow (bool finalize)
bool getNull (int colIndex)
char * getStr (int colIndex, std::string &retStr)
std::int32_t getInt (int colIndex)
float getFloat (int colIndex)
bool getBool (int colIndex)
int getBinary (int colIndex, unsigned char *buf, int maxSize)
Blob getBinary (int colIndex)
std::uint64_t getBigInt (int colIndex)
sqlite3 * peekConnection ()
sqlite3 * getAuxConnection ()
virtual bool setupCheckpointing (JobQueue *)
virtual SqliteDatabase * getSqliteDB ()
void doHook (const char *db, int walSize)
int getKBUsedDB ()
int getKBUsedAll ()
Public Member Functions inherited from ripple::Database
Database (const char *host)
virtual ~Database ()
bool executeSQL (std::string strSql, bool fail_okay=false)
bool getNull (const char *colName)
char * getStr (const char *colName, std::string &retStr)
std::string getStrBinary (const std::string &strColName)
std::int32_t getInt (const char *colName)
float getFloat (const char *colName)
bool getBool (const char *colName)
int getBinary (const char *colName, unsigned char *buf, int maxSize)
Blob getBinary (const std::string &strColName)
std::uint64_t getBigInt (const char *colName)
Private Types
typedef RippleMutex LockType
typedef std::lock_guard< LockType > ScopedLockType
Private Types inherited from beast::Thread
typedef void * ThreadID
Private Member Functions
void run ()
void runWal ()
Private Member Functions inherited from beast::Thread
Thread (const String &threadName)
virtual ~Thread ()
void startThread ()
void startThread (int priority)
bool stopThread (int timeOutMilliseconds=-1)
void stopThreadAsync ()
bool isThreadRunning () const
void signalThreadShouldExit ()
bool threadShouldExit () const
bool waitForThreadToExit (int timeOutMilliseconds=-1) const
bool setPriority (int priority)
void setAffinityMask (std::uint32_t affinityMask)
bool wait (int timeOutMilliseconds=-1) const
void notify () const
ThreadID getThreadId () const noexcept
const String & getThreadName () const
Private Attributes
LockType m_walMutex
sqlite3 * mConnection
sqlite3 * mAuxConnection
sqlite3_stmt * mCurrentStmt
bool mMoreRows
JobQueue * mWalQ
bool walRunning
Additional Inherited Members
Protected Member Functions inherited from ripple::Database
bool getColNumber (const char *colName, int *retIndex)
Protected Attributes inherited from ripple::Database
int mNumCol
std::string mHost
std::vector< std::string > mColNameTable
Static Private Member Functions inherited from beast::Thread
static bool setCurrentThreadPriority (int priority)
static void setCurrentThreadAffinityMask (std::uint32_t affinityMask)
static void sleep (int milliseconds)
static void yield ()
static ThreadID getCurrentThreadId ()
static Thread * getCurrentThread ()
static void setCurrentThreadName (const String &newThreadName)
Detailed Description
Definition at line 27 of file SqliteDatabase.h.
Member Typedef Documentation
typedef RippleMutex ripple::SqliteDatabase::LockType private
Definition at line 83 of file SqliteDatabase.h.
typedef std::lock_guard<LockType> ripple::SqliteDatabase::ScopedLockType private
Definition at line 84 of file SqliteDatabase.h.
Constructor & Destructor Documentation
ripple::SqliteDatabase::SqliteDatabase (char const * host) explicit
Definition at line 53 of file SqliteDatabase.cpp.
References mAuxConnection, mConnection, mCurrentStmt, and beast::Thread::startThread().
     : Database (host)
     , Thread ("sqlitedb")
     , mWalQ (nullptr)
     , walRunning (false)
 {
     startThread ();
     mConnection     = nullptr;
     mAuxConnection  = nullptr;
     mCurrentStmt    = nullptr;
 }
ripple::SqliteDatabase::~SqliteDatabase ()
Definition at line 66 of file SqliteDatabase.cpp.
References beast::Thread::stopThread().
 {
     // Blocks until the thread exits in an orderly fashion
     stopThread ();
 }
Member Function Documentation
void ripple::SqliteDatabase::connect (void) virtual
Implements ripple::Database.
Definition at line 72 of file SqliteDatabase.cpp.
References ripple::lsFATAL, mConnection, ripple::Database::mHost, sqlite3_close, sqlite3_open_v2, SQLITE_BUSY, SQLITE_LOCKED, SQLITE_OPEN_CREATE, SQLITE_OPEN_FULLMUTEX, SQLITE_OPEN_READWRITE, and WriteLog.
 {
     int rc = sqlite3_open_v2 (mHost.c_str (), &mConnection,
                 SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE | SQLITE_OPEN_FULLMUTEX, nullptr);
     if (rc)
     {
         WriteLog (lsFATAL, SqliteDatabase) << "Can't open " << mHost << " " << rc;
         sqlite3_close (mConnection);
         assert ((rc != SQLITE_BUSY) && (rc != SQLITE_LOCKED));
     }
 }
void ripple::SqliteDatabase::disconnect () virtual
Implements ripple::Database.
Definition at line 110 of file SqliteDatabase.cpp.
References mAuxConnection, mConnection, mCurrentStmt, sqlite3_close, and sqlite3_finalize.
 {
     sqlite3_finalize (mCurrentStmt);
     sqlite3_close (mConnection);
     if (mAuxConnection != nullptr)
         sqlite3_close (mAuxConnection);
 }
void ripple::SqliteDatabase::doHook (const char * db, int walSize)
Definition at line 306 of file SqliteDatabase.cpp.
References ripple::JobQueue::addJob(), BIND_TYPE, ripple::jtWAL, m_walMutex, ripple::Database::mHost, mWalQ, beast::Thread::notify(), runWal(), and walRunning.
 {
     if (pages < 1000)
         return;
     {
         ScopedLockType sl (m_walMutex);
         if (walRunning)
             return;
         walRunning = true;
     }
     if (mWalQ)
     {
         mWalQ->addJob (jtWAL, std::string ("WAL:") + mHost, BIND_TYPE (&SqliteDatabase::runWal, this));
     }
     else
     {
         notify();
     }
 }
void ripple::SqliteDatabase::endIterRows () virtual
Implements ripple::Database.
Definition at line 199 of file SqliteDatabase.cpp.
References mCurrentStmt, and sqlite3_finalize.
Referenced by executeSQL(), getNextRow(), and startIterRows().
 {
     sqlite3_finalize (mCurrentStmt);
     mCurrentStmt = nullptr;
 }
bool ripple::SqliteDatabase::executeSQL (const char * sql, bool fail_okay) virtual
Implements ripple::Database.
Definition at line 120 of file SqliteDatabase.cpp.
References endIterRows(), ripple::lsFATAL, ripple::lsWARNING, mConnection, mCurrentStmt, ripple::Database::mHost, mMoreRows, sqlite3_errmsg, sqlite3_finalize, sqlite3_prepare_v2, sqlite3_step, SQLITE_BUSY, SQLITE_DONE, SQLITE_LOCKED, SQLITE_OK, SQLITE_ROW, and WriteLog.
 {
 #ifdef DEBUG_HANGING_LOCKS
     assert (fail_ok || (mCurrentStmt == nullptr));
 #endif
     sqlite3_finalize (mCurrentStmt);
     int rc = sqlite3_prepare_v2 (mConnection, sql, -1, &mCurrentStmt, nullptr);
     if (SQLITE_OK != rc)
     {
         if (!fail_ok)
         {
 #ifdef BEAST_DEBUG
             WriteLog (lsWARNING, SqliteDatabase) << "Perror:" << mHost << ": " << rc;
             WriteLog (lsWARNING, SqliteDatabase) << "Statement: " << sql;
             WriteLog (lsWARNING, SqliteDatabase) << "Error: " << sqlite3_errmsg (mConnection);
 #endif
         }
         endIterRows ();
         return false;
     }
     rc = sqlite3_step (mCurrentStmt);
     if (rc == SQLITE_ROW)
     {
         mMoreRows = true;
     }
     else if (rc == SQLITE_DONE)
     {
         endIterRows ();
         mMoreRows = false;
     }
     else
     {
         if ((rc != SQLITE_BUSY) && (rc != SQLITE_LOCKED))
         {
             WriteLog (lsFATAL, SqliteDatabase) << mHost  << " returns error " << rc << ": " << sqlite3_errmsg (mConnection);
             assert (false);
         }
         mMoreRows = false;
         if (!fail_ok)
         {
 #ifdef BEAST_DEBUG
             WriteLog (lsWARNING, SqliteDatabase) << "SQL Serror:" << mHost << ": " << rc;
             WriteLog (lsWARNING, SqliteDatabase) << "Statement: " << sql;
             WriteLog (lsWARNING, SqliteDatabase) << "Error: " << sqlite3_errmsg (mConnection);
 #endif
         }
         endIterRows ();
         return false;
     }
     return true;
 }
sqlite3 * ripple::SqliteDatabase::getAuxConnection ()
Definition at line 85 of file SqliteDatabase.cpp.
References ripple::lsFATAL, m_walMutex, mAuxConnection, mConnection, ripple::Database::mHost, sqlite3_close, sqlite3_open_v2, SQLITE_BUSY, SQLITE_LOCKED, SQLITE_OPEN_CREATE, SQLITE_OPEN_FULLMUTEX, SQLITE_OPEN_READWRITE, and WriteLog.
Referenced by ripple::SqliteStatement::SqliteStatement().
 {
     ScopedLockType sl (m_walMutex);
     if (mAuxConnection == nullptr)
     {
         int rc = sqlite3_open_v2 (mHost.c_str (), &mAuxConnection,
                     SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE | SQLITE_OPEN_FULLMUTEX, nullptr);
         if (rc)
         {
             WriteLog (lsFATAL, SqliteDatabase) << "Can't aux open " << mHost << " " << rc;
             assert ((rc != SQLITE_BUSY) && (rc != SQLITE_LOCKED));
             if (mAuxConnection != nullptr)
             {
                 sqlite3_close (mConnection);
                 mAuxConnection = nullptr;
             }
         }
     }
     return mAuxConnection;
 }
std::uint64_t ripple::SqliteDatabase::getBigInt (int colIndex) virtual
Implements ripple::Database.
Definition at line 276 of file SqliteDatabase.cpp.
References mCurrentStmt, and sqlite3_column_int64.
 {
     return (sqlite3_column_int64 (mCurrentStmt, colIndex));
 }
int ripple::SqliteDatabase::getBinary (int colIndex, unsigned char * buf, int maxSize) virtual
Implements ripple::Database.
Definition at line 253 of file SqliteDatabase.cpp.
References mCurrentStmt, sqlite3_column_blob, and sqlite3_column_bytes.
 {
     const void* blob = sqlite3_column_blob (mCurrentStmt, colIndex);
     int size = sqlite3_column_bytes (mCurrentStmt, colIndex);
     if (size < maxSize) maxSize = size;
     memcpy (buf, blob, maxSize);
     return (size);
 }
Blob ripple::SqliteDatabase::getBinary (int colIndex) virtual
Implements ripple::Database.
Definition at line 264 of file SqliteDatabase.cpp.
References mCurrentStmt, sqlite3_column_blob, and sqlite3_column_bytes.
 {
     const unsigned char*        blob    = reinterpret_cast<const unsigned char*> (sqlite3_column_blob (mCurrentStmt, colIndex));
     size_t                      iSize   = sqlite3_column_bytes (mCurrentStmt, colIndex);
     Blob    vucResult;
     vucResult.resize (iSize);
     std::copy (blob, blob + iSize, vucResult.begin ());
     return vucResult;
 }
bool ripple::SqliteDatabase::getBool (int colIndex) virtual
Implements ripple::Database.
Definition at line 248 of file SqliteDatabase.cpp.
References mCurrentStmt, and sqlite3_column_int.
 {
     return (sqlite3_column_int (mCurrentStmt, colIndex) ? true : false);
 }
float ripple::SqliteDatabase::getFloat (int colIndex) virtual
Implements ripple::Database.
Definition at line 243 of file SqliteDatabase.cpp.
References mCurrentStmt, and sqlite3_column_double.
 {
     return (static_cast <float> (sqlite3_column_double (mCurrentStmt, colIndex)));
 }
std::int32_t ripple::SqliteDatabase::getInt (int colIndex) virtual
Implements ripple::Database.
Definition at line 238 of file SqliteDatabase.cpp.
References mCurrentStmt, and sqlite3_column_int.
 {
     return (sqlite3_column_int (mCurrentStmt, colIndex));
 }
int ripple::SqliteDatabase::getKBUsedAll () virtual
Reimplemented from ripple::Database.
Definition at line 281 of file SqliteDatabase.cpp.
References sqlite3_memory_used.
 {
     return static_cast<int> (sqlite3_memory_used () / 1024);
 }
int ripple::SqliteDatabase::getKBUsedDB () virtual
Reimplemented from ripple::Database.
Definition at line 286 of file SqliteDatabase.cpp.
References mConnection, sqlite3_db_status, and SQLITE_DBSTATUS_CACHE_USED.
 {
     int cur = 0, hiw = 0;
     sqlite3_db_status (mConnection, SQLITE_DBSTATUS_CACHE_USED, &cur, &hiw, 0);
     return cur / 1024;
 }
bool ripple::SqliteDatabase::getNextRow (bool finalize) virtual
Implements ripple::Database.
Definition at line 207 of file SqliteDatabase.cpp.
References CondLog, endIterRows(), ripple::lsWARNING, mCurrentStmt, ripple::Database::mHost, mMoreRows, sqlite3_step, SQLITE_BUSY, SQLITE_DONE, SQLITE_LOCKED, and SQLITE_ROW.
 {
     if (mMoreRows)
     {
         int rc = sqlite3_step (mCurrentStmt);
         if (rc == SQLITE_ROW)
             return (true);
         assert ((rc != SQLITE_BUSY) && (rc != SQLITE_LOCKED));
         CondLog ((rc != SQLITE_DONE), lsWARNING, SqliteDatabase) << "Rerror: " << mHost << ": " << rc;
     }
     if (finalize)
         endIterRows ();
     return false;
 }
bool ripple::SqliteDatabase::getNull (int colIndex) virtual
Implements ripple::Database.
Definition at line 226 of file SqliteDatabase.cpp.
References mCurrentStmt, sqlite3_column_type, and SQLITE_NULL.
 {
     return (SQLITE_NULL == sqlite3_column_type (mCurrentStmt, colIndex));
 }
int ripple::SqliteDatabase::getNumRowsAffected ()
virtual SqliteDatabase* ripple::SqliteDatabase::getSqliteDB () inline virtual
Reimplemented from ripple::Database.
Definition at line 69 of file SqliteDatabase.h.
     {
         return this;
     }
char * ripple::SqliteDatabase::getStr (int colIndex, std::string & retStr) virtual
Implements ripple::Database.
Definition at line 231 of file SqliteDatabase.cpp.
References mCurrentStmt, and sqlite3_column_text.
 {
     const char* text = reinterpret_cast<const char*> (sqlite3_column_text (mCurrentStmt, colIndex));
     retStr = (text == nullptr) ? "" : text;
     return const_cast<char*> (retStr.c_str ());
 }
sqlite3* ripple::SqliteDatabase::peekConnection () inline
Definition at line 63 of file SqliteDatabase.h.
References mConnection.
Referenced by ripple::SqliteStatement::SqliteStatement().
     {
         return mConnection;
     }
void ripple::SqliteDatabase::run () private virtual
Must be implemented to perform the thread's actual code.
Remember that the thread must regularly check the threadShouldExit() method whilst running, and if this returns true it should return from the run() method as soon as possible to avoid being forcibly killed.
See Also
threadShouldExit, startThread
Implements beast::Thread.
Definition at line 330 of file SqliteDatabase.cpp.
References runWal(), beast::Thread::threadShouldExit(), and beast::Thread::wait().
 {
     // Simple thread loop runs Wal every time it wakes up via
     // the call to Thread::notify, unless Thread::threadShouldExit returns
     // true in which case we simply break.
     //
     for (;;)
     {
         wait ();
         if (threadShouldExit())
             break;
         runWal();
     }
 }
void ripple::SqliteDatabase::runWal () private
Definition at line 345 of file SqliteDatabase.cpp.
References ripple::lsTRACE, ripple::lsWARNING, m_walMutex, mConnection, sqlite3_db_filename, sqlite3_wal_checkpoint_v2, SQLITE_CHECKPOINT_PASSIVE, SQLITE_LOCKED, SQLITE_OK, walRunning, and WriteLog.
Referenced by doHook(), and run().
 {
     int log = 0, ckpt = 0;
     int ret = sqlite3_wal_checkpoint_v2 (mConnection, nullptr, SQLITE_CHECKPOINT_PASSIVE, &log, &ckpt);
     if (ret != SQLITE_OK)
     {
         WriteLog ((ret == SQLITE_LOCKED) ? lsTRACE : lsWARNING, SqliteDatabase) << "WAL("
                 << sqlite3_db_filename (mConnection, "main") << "): error " << ret;
     }
     else
         WriteLog (lsTRACE, SqliteDatabase) << "WAL(" << sqlite3_db_filename (mConnection, "main") <<
                                            "): frames=" << log << ", written=" << ckpt;
     {
         ScopedLockType sl (m_walMutex);
         walRunning = false;
     }
 }
bool ripple::SqliteDatabase::setupCheckpointing (JobQueue * q) virtual
Reimplemented from ripple::Database.
Definition at line 299 of file SqliteDatabase.cpp.
References mConnection, mWalQ, sqlite3_wal_hook, and ripple::SqliteWALHook().
 {
     mWalQ = q;
     sqlite3_wal_hook (mConnection, SqliteWALHook, this);
     return true;
 }
bool ripple::SqliteDatabase::startIterRows (bool finalize) virtual
Implements ripple::Database.
Definition at line 183 of file SqliteDatabase.cpp.
References endIterRows(), ripple::Database::mColNameTable, mCurrentStmt, mMoreRows, sqlite3_column_count, and sqlite3_column_name.
 {
     mColNameTable.clear ();
     mColNameTable.resize (sqlite3_column_count (mCurrentStmt));
     for (unsigned n = 0; n < mColNameTable.size (); n++)
     {
         mColNameTable[n] = sqlite3_column_name (mCurrentStmt, n);
     }
     if (!mMoreRows && finalize)
         endIterRows ();
     return (mMoreRows);
 }
Member Data Documentation
LockType ripple::SqliteDatabase::m_walMutex private
Definition at line 85 of file SqliteDatabase.h.
Referenced by doHook(), getAuxConnection(), and runWal().
sqlite3* ripple::SqliteDatabase::mAuxConnection private
Definition at line 89 of file SqliteDatabase.h.
Referenced by disconnect(), getAuxConnection(), and SqliteDatabase().
sqlite3* ripple::SqliteDatabase::mConnection private
Definition at line 87 of file SqliteDatabase.h.
Referenced by connect(), disconnect(), executeSQL(), getAuxConnection(), getKBUsedDB(), peekConnection(), runWal(), setupCheckpointing(), and SqliteDatabase().
sqlite3_stmt* ripple::SqliteDatabase::mCurrentStmt private
Definition at line 90 of file SqliteDatabase.h.
Referenced by disconnect(), endIterRows(), executeSQL(), getBigInt(), getBinary(), getBool(), getFloat(), getInt(), getNextRow(), getNull(), getStr(), SqliteDatabase(), and startIterRows().
bool ripple::SqliteDatabase::mMoreRows private
Definition at line 91 of file SqliteDatabase.h.
Referenced by executeSQL(), getNextRow(), and startIterRows().
JobQueue* ripple::SqliteDatabase::mWalQ private
Definition at line 93 of file SqliteDatabase.h.
Referenced by doHook(), and setupCheckpointing().
bool ripple::SqliteDatabase::walRunning private
Definition at line 94 of file SqliteDatabase.h.
Referenced by doHook(), and runWal().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/data/SqliteDatabase.h
rippled/src/ripple_app/data/SqliteDatabase.cpp