rippled: rocksdb::VersionEdit Class Reference
rocksdb::VersionEdit Class Reference
#include <version_edit.h>
Public Member Functions
VersionEdit (int number_levels)
~VersionEdit ()
void Clear ()
void SetComparatorName (const Slice &name)
void SetLogNumber (uint64_t num)
void SetPrevLogNumber (uint64_t num)
void SetNextFile (uint64_t num)
void SetLastSequence (SequenceNumber seq)
void SetCompactPointer (int level, const InternalKey &key)
void AddFile (int level, uint64_t file, uint64_t file_size, const InternalKey &smallest, const InternalKey &largest, const SequenceNumber &smallest_seqno, const SequenceNumber &largest_seqno)
void DeleteFile (int level, uint64_t file)
int NumEntries ()
void EncodeTo (std::string *dst) const
Status DecodeFrom (const Slice &src)
std::string DebugString (bool hex_key=false) const
Private Types
typedef std::set< std::pair
< int, uint64_t > > DeletedFileSet
Private Member Functions
bool GetLevel (Slice *input, int *level, const char **msg)
Private Attributes
int number_levels_
std::string comparator_
uint64_t log_number_
uint64_t prev_log_number_
uint64_t next_file_number_
SequenceNumber last_sequence_
bool has_comparator_
bool has_log_number_
bool has_prev_log_number_
bool has_next_file_number_
bool has_last_sequence_
std::vector< std::pair< int,
InternalKey > > compact_pointers_
DeletedFileSet deleted_files_
std::vector< std::pair< int,
FileMetaData > > new_files_
Friends
class VersionSet
Detailed Description
Definition at line 35 of file version_edit.h.
Member Typedef Documentation
typedef std::set< std::pair<int, uint64_t> > rocksdb::VersionEdit::DeletedFileSet private
Definition at line 107 of file version_edit.h.
Constructor & Destructor Documentation
rocksdb::VersionEdit::VersionEdit (int number_levels) inline explicit
Definition at line 37 of file version_edit.h.
References Clear().
                                           :
       number_levels_(number_levels) {
     Clear();
   }
rocksdb::VersionEdit::~VersionEdit () inline
Definition at line 41 of file version_edit.h.
 { }
Member Function Documentation
void rocksdb::VersionEdit::AddFile (int level, uint64_t file, uint64_t file_size, const InternalKey & smallest, const InternalKey & largest, const SequenceNumber & smallest_seqno, const SequenceNumber & largest_seqno) inline
Definition at line 72 of file version_edit.h.
References ripple::f, rocksdb::FileMetaData::file_size, rocksdb::FileMetaData::largest, rocksdb::FileMetaData::largest_seqno, new_files_, rocksdb::FileMetaData::number, rocksdb::FileMetaData::smallest, and rocksdb::FileMetaData::smallest_seqno.
Referenced by rocksdb::DBImpl::InstallCompactionResults(), rocksdb::TEST(), rocksdb::DBImpl::WriteLevel0Table(), rocksdb::DBImpl::WriteLevel0TableForRecovery(), and rocksdb::VersionSet::WriteSnapshot().
{
     FileMetaData f;
     f.number = file;
     f.file_size = file_size;
     f.smallest = smallest;
     f.largest = largest;
     f.smallest_seqno = smallest_seqno;
     f.largest_seqno = largest_seqno;
     assert(smallest_seqno <= largest_seqno);
     new_files_.push_back(std::make_pair(level, f));
   }
void rocksdb::VersionEdit::Clear ()
Definition at line 34 of file version_edit.cc.
References comparator_, deleted_files_, has_comparator_, has_last_sequence_, has_log_number_, has_next_file_number_, has_prev_log_number_, last_sequence_, log_number_, new_files_, next_file_number_, and prev_log_number_.
Referenced by DecodeFrom(), rocksdb::MemTableList::InstallMemtableFlushResults(), and VersionEdit().
{
   comparator_.clear();
   log_number_ = 0;
   prev_log_number_ = 0;
   last_sequence_ = 0;
   next_file_number_ = 0;
   has_comparator_ = false;
   has_log_number_ = false;
   has_prev_log_number_ = false;
   has_next_file_number_ = false;
   has_last_sequence_ = false;
   deleted_files_.clear();
   new_files_.clear();
 }
std::string rocksdb::VersionEdit::DebugString (bool hex_key = false) const
Definition at line 247 of file version_edit.cc.
References rocksdb::AppendNumberTo(), compact_pointers_, comparator_, rocksdb::InternalKey::DebugString(), deleted_files_, ripple::f, rocksdb::FileMetaData::file_size, beast.util.Iter::first(), has_comparator_, has_last_sequence_, has_log_number_, has_next_file_number_, has_prev_log_number_, rocksdb::FileMetaData::largest, last_sequence_, log_number_, new_files_, next_file_number_, rocksdb::FileMetaData::number, prev_log_number_, and rocksdb::FileMetaData::smallest.
Referenced by rocksdb::VersionSet::DumpManifest().
{
   std::string r;
   r.append("VersionEdit {");
   if (has_comparator_) {
     r.append("\n  Comparator: ");
     r.append(comparator_);
   }
   if (has_log_number_) {
     r.append("\n  LogNumber: ");
     AppendNumberTo(&r, log_number_);
   }
   if (has_prev_log_number_) {
     r.append("\n  PrevLogNumber: ");
     AppendNumberTo(&r, prev_log_number_);
   }
   if (has_next_file_number_) {
     r.append("\n  NextFile: ");
     AppendNumberTo(&r, next_file_number_);
   }
   if (has_last_sequence_) {
     r.append("\n  LastSeq: ");
     AppendNumberTo(&r, last_sequence_);
   }
   for (size_t i = 0; i < compact_pointers_.size(); i++) {
     r.append("\n  CompactPointer: ");
     AppendNumberTo(&r, compact_pointers_[i].first);
     r.append(" ");
     r.append(compact_pointers_[i].second.DebugString(hex_key));
   }
   for (DeletedFileSet::const_iterator iter = deleted_files_.begin();
        iter != deleted_files_.end();
        ++iter) {
     r.append("\n  DeleteFile: ");
     AppendNumberTo(&r, iter->first);
     r.append(" ");
     AppendNumberTo(&r, iter->second);
   }
   for (size_t i = 0; i < new_files_.size(); i++) {
     const FileMetaData& f = new_files_[i].second;
     r.append("\n  AddFile: ");
     AppendNumberTo(&r, new_files_[i].first);
     r.append(" ");
     AppendNumberTo(&r, f.number);
     r.append(" ");
     AppendNumberTo(&r, f.file_size);
     r.append(" ");
     r.append(f.smallest.DebugString(hex_key));
     r.append(" .. ");
     r.append(f.largest.DebugString(hex_key));
   }
   r.append("\n}\n");
   return r;
 }
Status rocksdb::VersionEdit::DecodeFrom (const Slice & src)
Definition at line 122 of file version_edit.cc.
References Clear(), compact_pointers_, comparator_, rocksdb::Status::Corruption(), deleted_files_, rocksdb::Slice::empty(), ripple::f, rocksdb::FileMetaData::file_size, rocksdb::GetInternalKey(), rocksdb::GetLengthPrefixedSlice(), GetLevel(), rocksdb::GetVarint32(), rocksdb::GetVarint64(), has_comparator_, has_last_sequence_, has_log_number_, has_next_file_number_, has_prev_log_number_, rocksdb::kCompactPointer, rocksdb::kComparator, rocksdb::kDeletedFile, rocksdb::kLastSequence, rocksdb::kLogNumber, rocksdb::kNewFile, rocksdb::kNewFile2, rocksdb::kNextFileNumber, rocksdb::kPrevLogNumber, rocksdb::FileMetaData::largest, rocksdb::FileMetaData::largest_seqno, last_sequence_, log_number_, new_files_, next_file_number_, rocksdb::FileMetaData::number, prev_log_number_, rocksdb::FileMetaData::smallest, rocksdb::FileMetaData::smallest_seqno, and rocksdb::Slice::ToString().
Referenced by rocksdb::VersionSet::DumpManifest(), rocksdb::VersionSet::Recover(), and rocksdb::TestEncodeDecode().
{
   Clear();
   Slice input = src;
   const char* msg = nullptr;
   uint32_t tag;
   // Temporary storage for parsing
   int level;
   uint64_t number;
   FileMetaData f;
   Slice str;
   InternalKey key;
   while (msg == nullptr && GetVarint32(&input, &tag)) {
     switch (tag) {
       case kComparator:
         if (GetLengthPrefixedSlice(&input, &str)) {
           comparator_ = str.ToString();
           has_comparator_ = true;
         } else {
           msg = "comparator name";
         }
         break;
       case kLogNumber:
         if (GetVarint64(&input, &log_number_)) {
           has_log_number_ = true;
         } else {
           msg = "log number";
         }
         break;
       case kPrevLogNumber:
         if (GetVarint64(&input, &prev_log_number_)) {
           has_prev_log_number_ = true;
         } else {
           msg = "previous log number";
         }
         break;
       case kNextFileNumber:
         if (GetVarint64(&input, &next_file_number_)) {
           has_next_file_number_ = true;
         } else {
           msg = "next file number";
         }
         break;
       case kLastSequence:
         if (GetVarint64(&input, &last_sequence_)) {
           has_last_sequence_ = true;
         } else {
           msg = "last sequence number";
         }
         break;
       case kCompactPointer:
         if (GetLevel(&input, &level, &msg) &&
             GetInternalKey(&input, &key)) {
           compact_pointers_.push_back(std::make_pair(level, key));
         } else {
           if (!msg) {
             msg = "compaction pointer";
           }
         }
         break;
       case kDeletedFile:
         if (GetLevel(&input, &level, &msg) &&
             GetVarint64(&input, &number)) {
           deleted_files_.insert(std::make_pair(level, number));
         } else {
           if (!msg) {
             msg = "deleted file";
           }
         }
         break;
       case kNewFile:
         if (GetLevel(&input, &level, &msg) &&
             GetVarint64(&input, &f.number) &&
             GetVarint64(&input, &f.file_size) &&
             GetInternalKey(&input, &f.smallest) &&
             GetInternalKey(&input, &f.largest)) {
           new_files_.push_back(std::make_pair(level, f));
         } else {
           if (!msg) {
             msg = "new-file entry";
           }
         }
         break;
       case kNewFile2:
         if (GetLevel(&input, &level, &msg) &&
             GetVarint64(&input, &f.number) &&
             GetVarint64(&input, &f.file_size) &&
             GetInternalKey(&input, &f.smallest) &&
             GetInternalKey(&input, &f.largest) &&
             GetVarint64(&input, &f.smallest_seqno) &&
             GetVarint64(&input, &f.largest_seqno) ) {
           new_files_.push_back(std::make_pair(level, f));
         } else {
           if (!msg) {
             msg = "new-file2 entry";
           }
         }
         break;
       default:
         msg = "unknown tag";
         break;
     }
   }
   if (msg == nullptr && !input.empty()) {
     msg = "invalid tag";
   }
   Status result;
   if (msg != nullptr) {
     result = Status::Corruption("VersionEdit", msg);
   }
   return result;
 }
void rocksdb::VersionEdit::DeleteFile (int level, uint64_t file) inline
Definition at line 90 of file version_edit.h.
References deleted_files_.
Referenced by rocksdb::Compaction::AddInputDeletions(), rocksdb::BM_LogAndApply(), rocksdb::DBImpl::DeleteFile(), and rocksdb::TEST().
{
     deleted_files_.insert(std::make_pair(level, file));
   }
void rocksdb::VersionEdit::EncodeTo (std::string * dst) const
Definition at line 49 of file version_edit.cc.
References compact_pointers_, comparator_, deleted_files_, rocksdb::InternalKey::Encode(), ripple::f, rocksdb::FileMetaData::file_size, beast.util.Iter::first(), has_comparator_, has_last_sequence_, has_log_number_, has_next_file_number_, has_prev_log_number_, rocksdb::kCompactPointer, rocksdb::kComparator, rocksdb::kDeletedFile, rocksdb::kLastSequence, rocksdb::kLogNumber, rocksdb::kNewFile2, rocksdb::kNextFileNumber, rocksdb::kPrevLogNumber, rocksdb::FileMetaData::largest, rocksdb::FileMetaData::largest_seqno, last_sequence_, log_number_, new_files_, next_file_number_, rocksdb::FileMetaData::number, prev_log_number_, rocksdb::PutLengthPrefixedSlice(), rocksdb::PutVarint32(), rocksdb::PutVarint64(), rocksdb::FileMetaData::smallest, and rocksdb::FileMetaData::smallest_seqno.
Referenced by rocksdb::DBImpl::NewDB(), rocksdb::TestEncodeDecode(), and rocksdb::VersionSet::WriteSnapshot().
{
   if (has_comparator_) {
     PutVarint32(dst, kComparator);
     PutLengthPrefixedSlice(dst, comparator_);
   }
   if (has_log_number_) {
     PutVarint32(dst, kLogNumber);
     PutVarint64(dst, log_number_);
   }
   if (has_prev_log_number_) {
     PutVarint32(dst, kPrevLogNumber);
     PutVarint64(dst, prev_log_number_);
   }
   if (has_next_file_number_) {
     PutVarint32(dst, kNextFileNumber);
     PutVarint64(dst, next_file_number_);
   }
   if (has_last_sequence_) {
     PutVarint32(dst, kLastSequence);
     PutVarint64(dst, last_sequence_);
   }
   for (size_t i = 0; i < compact_pointers_.size(); i++) {
     PutVarint32(dst, kCompactPointer);
     PutVarint32(dst, compact_pointers_[i].first);  // level
     PutLengthPrefixedSlice(dst, compact_pointers_[i].second.Encode());
   }
   for (DeletedFileSet::const_iterator iter = deleted_files_.begin();
        iter != deleted_files_.end();
        ++iter) {
     PutVarint32(dst, kDeletedFile);
     PutVarint32(dst, iter->first);   // level
     PutVarint64(dst, iter->second);  // file number
   }
   for (size_t i = 0; i < new_files_.size(); i++) {
     const FileMetaData& f = new_files_[i].second;
     PutVarint32(dst, kNewFile2);
     PutVarint32(dst, new_files_[i].first);  // level
     PutVarint64(dst, f.number);
     PutVarint64(dst, f.file_size);
     PutLengthPrefixedSlice(dst, f.smallest.Encode());
     PutLengthPrefixedSlice(dst, f.largest.Encode());
     PutVarint64(dst, f.smallest_seqno);
     PutVarint64(dst, f.largest_seqno);
   }
 }
bool rocksdb::VersionEdit::GetLevel (Slice * input, int * level, const char ** msg) private
Definition at line 108 of file version_edit.cc.
References rocksdb::GetVarint32(), and number_levels_.
Referenced by DecodeFrom().
{
   uint32_t v;
   if (GetVarint32(input, &v) &&
       (int)v < number_levels_) {
     *level = v;
     return true;
   } else {
     if ((int)v >= number_levels_) {
       *msg = "db already has more levels than options.num_levels";
     }
     return false;
   }
 }
int rocksdb::VersionEdit::NumEntries () inline
Definition at line 95 of file version_edit.h.
References deleted_files_, and new_files_.
                    {
     return new_files_.size() + deleted_files_.size();
   }
void rocksdb::VersionEdit::SetCompactPointer (int level, const InternalKey & key) inline
Definition at line 65 of file version_edit.h.
References compact_pointers_.
Referenced by rocksdb::VersionSet::SetupOtherInputs(), rocksdb::TEST(), and rocksdb::VersionSet::WriteSnapshot().
{
     compact_pointers_.push_back(std::make_pair(level, key));
   }
void rocksdb::VersionEdit::SetComparatorName (const Slice & name) inline
Definition at line 45 of file version_edit.h.
References comparator_, has_comparator_, and rocksdb::Slice::ToString().
Referenced by rocksdb::DBImpl::NewDB(), rocksdb::TEST(), and rocksdb::VersionSet::WriteSnapshot().
{
     has_comparator_ = true;
     comparator_ = name.ToString();
   }
void rocksdb::VersionEdit::SetLastSequence (SequenceNumber seq) inline
Definition at line 61 of file version_edit.h.
References has_last_sequence_, and last_sequence_.
Referenced by rocksdb::VersionSet::LogAndApplyHelper(), rocksdb::DBImpl::NewDB(), and rocksdb::TEST().
{
     has_last_sequence_ = true;
     last_sequence_ = seq;
   }
void rocksdb::VersionEdit::SetLogNumber (uint64_t num) inline
Definition at line 49 of file version_edit.h.
References has_log_number_, and log_number_.
Referenced by rocksdb::DBImpl::FlushMemTableToOutputFile(), rocksdb::VersionSet::LogAndApplyHelper(), rocksdb::DBImpl::NewDB(), and rocksdb::TEST().
{
     has_log_number_ = true;
     log_number_ = num;
   }
void rocksdb::VersionEdit::SetNextFile (uint64_t num) inline
Definition at line 57 of file version_edit.h.
References has_next_file_number_, and next_file_number_.
Referenced by rocksdb::VersionSet::LogAndApply(), rocksdb::VersionSet::LogAndApplyHelper(), rocksdb::DBImpl::NewDB(), and rocksdb::TEST().
{
     has_next_file_number_ = true;
     next_file_number_ = num;
   }
void rocksdb::VersionEdit::SetPrevLogNumber (uint64_t num) inline
Definition at line 53 of file version_edit.h.
References has_prev_log_number_, and prev_log_number_.
Referenced by rocksdb::DBImpl::FlushMemTableToOutputFile(), and rocksdb::VersionSet::LogAndApplyHelper().
{
     has_prev_log_number_ = true;
     prev_log_number_ = num;
   }
Friends And Related Function Documentation
friend class VersionSet friend
Definition at line 105 of file version_edit.h.
Member Data Documentation
std::vector< std::pair<int, InternalKey> > rocksdb::VersionEdit::compact_pointers_ private
Definition at line 123 of file version_edit.h.
Referenced by rocksdb::VersionSet::Builder::Apply(), DebugString(), DecodeFrom(), EncodeTo(), and SetCompactPointer().
std::string rocksdb::VersionEdit::comparator_ private
Definition at line 112 of file version_edit.h.
Referenced by Clear(), DebugString(), DecodeFrom(), rocksdb::VersionSet::DumpManifest(), EncodeTo(), rocksdb::VersionSet::Recover(), and SetComparatorName().
DeletedFileSet rocksdb::VersionEdit::deleted_files_ private
Definition at line 124 of file version_edit.h.
Referenced by rocksdb::VersionSet::Builder::Apply(), Clear(), DebugString(), DecodeFrom(), DeleteFile(), EncodeTo(), and NumEntries().
bool rocksdb::VersionEdit::has_comparator_ private
Definition at line 117 of file version_edit.h.
Referenced by Clear(), DebugString(), DecodeFrom(), rocksdb::VersionSet::DumpManifest(), EncodeTo(), rocksdb::VersionSet::Recover(), and SetComparatorName().
bool rocksdb::VersionEdit::has_last_sequence_ private
Definition at line 121 of file version_edit.h.
Referenced by Clear(), DebugString(), DecodeFrom(), rocksdb::VersionSet::DumpManifest(), EncodeTo(), rocksdb::VersionSet::Recover(), and SetLastSequence().
bool rocksdb::VersionEdit::has_log_number_ private
Definition at line 118 of file version_edit.h.
Referenced by Clear(), DebugString(), DecodeFrom(), rocksdb::VersionSet::DumpManifest(), EncodeTo(), rocksdb::VersionSet::LogAndApplyHelper(), rocksdb::VersionSet::Recover(), and SetLogNumber().
bool rocksdb::VersionEdit::has_next_file_number_ private
Definition at line 120 of file version_edit.h.
Referenced by Clear(), DebugString(), DecodeFrom(), rocksdb::VersionSet::DumpManifest(), EncodeTo(), rocksdb::VersionSet::Recover(), and SetNextFile().
bool rocksdb::VersionEdit::has_prev_log_number_ private
Definition at line 119 of file version_edit.h.
Referenced by Clear(), DebugString(), DecodeFrom(), rocksdb::VersionSet::DumpManifest(), EncodeTo(), rocksdb::VersionSet::LogAndApplyHelper(), rocksdb::VersionSet::Recover(), and SetPrevLogNumber().
SequenceNumber rocksdb::VersionEdit::last_sequence_ private
Definition at line 116 of file version_edit.h.
Referenced by Clear(), DebugString(), DecodeFrom(), rocksdb::VersionSet::DumpManifest(), EncodeTo(), rocksdb::VersionSet::Recover(), and SetLastSequence().
uint64_t rocksdb::VersionEdit::log_number_ private
Definition at line 113 of file version_edit.h.
Referenced by Clear(), DebugString(), DecodeFrom(), rocksdb::VersionSet::DumpManifest(), EncodeTo(), rocksdb::VersionSet::LogAndApply(), rocksdb::VersionSet::LogAndApplyHelper(), rocksdb::VersionSet::Recover(), and SetLogNumber().
std::vector< std::pair<int, FileMetaData> > rocksdb::VersionEdit::new_files_ private
Definition at line 125 of file version_edit.h.
Referenced by AddFile(), rocksdb::VersionSet::Builder::Apply(), Clear(), DebugString(), DecodeFrom(), EncodeTo(), and NumEntries().
uint64_t rocksdb::VersionEdit::next_file_number_ private
Definition at line 115 of file version_edit.h.
Referenced by Clear(), DebugString(), DecodeFrom(), rocksdb::VersionSet::DumpManifest(), EncodeTo(), rocksdb::VersionSet::Recover(), and SetNextFile().
int rocksdb::VersionEdit::number_levels_ private
Definition at line 111 of file version_edit.h.
Referenced by rocksdb::VersionSet::Builder::CheckConsistencyForDeletes(), and GetLevel().
uint64_t rocksdb::VersionEdit::prev_log_number_ private
Definition at line 114 of file version_edit.h.
Referenced by Clear(), DebugString(), DecodeFrom(), rocksdb::VersionSet::DumpManifest(), EncodeTo(), rocksdb::VersionSet::LogAndApply(), rocksdb::VersionSet::Recover(), and SetPrevLogNumber().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/db/version_edit.h
rippled/src/ripple/rocksdb/rocksdb/db/version_edit.cc