rippled: beast::sqdb Namespace Reference
beast::sqdb Namespace Reference
Namespaces
detail
Classes
class blob
class session
A session for the embedded database.
class statement
class transaction
struct type_conversion
struct type_conversion< Time >
Typedefs
typedef std::int64_t rowid
Enumerations
enum indicator { i_ok, i_null, i_truncated }
Functions
template<typename T >
detail::into_type_ptr into (T &t)
template<typename T >
detail::into_type_ptr into (T &t, indicator &ind)
detail::use_type_ptr use_null ()
template<typename T >
detail::use_type_ptr use (T &t)
template<typename T >
detail::use_type_ptr use (T const &t)
template<typename T >
detail::use_type_ptr use (T &t, indicator &ind)
Typedef Documentation
typedef std::int64_t beast::sqdb::rowid
Definition at line 110 of file backend.h.
Enumeration Type Documentation
enum beast::sqdb::indicator
Enumerator
i_ok
i_null
i_truncated
Definition at line 100 of file backend.h.
 {
     i_ok,
     i_null,
     i_truncated
 };
Function Documentation
template<typename T > detail::into_type_ptr beast::sqdb::into (T & t)
Definition at line 67 of file into.h.
References beast::sqdb::detail::do_into().
Referenced by ripple::PeerFinder::StoreSqdb::load(), ripple::Validators::StoreSqdb::select(), ripple::Validators::StoreSqdb::selectList(), ripple::Validators::StoreSqdb::update(), and ripple::PeerFinder::StoreSqdb::update().
 {
     return detail::do_into(t,
                            typename detail::exchange_traits<T>::type_family());
 }
template<typename T > detail::into_type_ptr beast::sqdb::into (T & t, indicator & ind)
Definition at line 74 of file into.h.
References beast::sqdb::detail::do_into().
 {
     return detail::do_into(t, ind,
                            typename detail::exchange_traits<T>::type_family());
 }
template<typename T > detail::use_type_ptr beast::sqdb::use (T & t)
Definition at line 72 of file use.h.
References beast::sqdb::detail::do_use().
Referenced by ripple::Validators::StoreSqdb::insert(), ripple::PeerFinder::StoreSqdb::save(), ripple::Validators::StoreSqdb::select(), ripple::Validators::StoreSqdb::selectList(), ripple::Validators::StoreSqdb::update(), and ripple::PeerFinder::StoreSqdb::update().
 {
     return detail::do_use(t,
                           typename detail::exchange_traits<T>::type_family());
 }
template<typename T > detail::use_type_ptr beast::sqdb::use (T const & t)
Definition at line 79 of file use.h.
References beast::sqdb::detail::do_use().
 {
     return detail::do_use(t,
                           typename detail::exchange_traits<T>::type_family());
 }
template<typename T > detail::use_type_ptr beast::sqdb::use (T & t, indicator & ind)
Definition at line 86 of file use.h.
References beast::sqdb::detail::do_use().
 {
     return detail::do_use(t, ind,
                           typename detail::exchange_traits<T>::type_family());
 }
detail::use_type_ptr beast::sqdb::use_null () inline
Definition at line 66 of file use.h.
References beast::sqdb::detail::do_use_null().
 {
     return detail::do_use_null();
 }