rippled: ripple::core::OfferStream Class Reference
ripple::core::OfferStream Class Reference
#include <OfferStream.h>
Public Member Functions
OfferStream (LedgerView &view, LedgerView &view_cancel, BookRef book, Clock::time_point when, beast::Journal journal)
LedgerView & view () noexcept
LedgerView & view_cancel () noexcept
Book const & book () const noexcept
uint256 const & dir () const noexcept
Offer const & tip () const
bool step ()
bool fill (Amounts const &remaining_funds)
Protected Member Functions
void erase (LedgerView &view)
Protected Attributes
beast::Journal m_journal
std::reference_wrapper
< LedgerView > m_view
std::reference_wrapper
< LedgerView > m_view_cancel
Book m_book
Clock::time_point m_when
BookTip m_tip
Offer m_offer
Detailed Description
Presents and consumes the offers in an order book.
Two LedgerView objects accumulate changes to the ledger. view is applied when the calling transaction succeeds. If the calling transaction fails, then view_cancel is applied.
Certain invalid offers are automatically removed:
Offers with missing ledger entries
Offers that expired
Offers found unfunded: An offer is found unfunded when the corresponding balance is zero and the caller has not modified the balance. This is accomplished by also looking up the balance in the cancel view.
When an offer is removed, it is removed from both views. This grooms the order book regardless of whether or not the transaction is successful.
TODO: Remove offers belonging to the taker
Definition at line 55 of file OfferStream.h.
Constructor & Destructor Documentation
ripple::core::OfferStream::OfferStream (LedgerView & view, LedgerView & view_cancel, BookRef book, Clock::time_point when, beast::Journal journal) inline
Definition at line 109 of file OfferStream.h.
         : m_journal (journal)
         , m_view (view)
         , m_view_cancel (view_cancel)
         , m_book (book)
         , m_when (when)
         , m_tip (view, book)
     {
     }
Member Function Documentation
Book const& ripple::core::OfferStream::book () const inline noexcept
Definition at line 133 of file OfferStream.h.
References m_book.
     {
         return m_book;
     }
uint256 const& ripple::core::OfferStream::dir () const inline noexcept
Definition at line 139 of file OfferStream.h.
References ripple::core::BookTip::dir(), and m_tip.
 {
     return m_tip.dir();
 }
void ripple::core::OfferStream::erase (LedgerView & view) inline protected
Definition at line 69 of file OfferStream.h.
References ripple::core::BookTip::dir(), ripple::LedgerEntrySet::entryCache(), ripple::LedgerEntrySet::entryModify(), beast::Journal::error, ripple::core::BookTip::index(), ripple::ltDIR_NODE, m_journal, m_tip, and beast::Journal::trace.
Referenced by step().
     {
         // VFALCO NOTE
         //
         //      This should be using LedgerView::dirDelete, which will
         //      correctly remove the directory if its the last entry.
         //      Unfortunately this is a protocol breaking change.
         auto p (view.entryCache (ltDIR_NODE, m_tip.dir()));
         if (p == nullptr)
         {
             if (m_journal.error) m_journal.error <<
                 "Missing directory " << m_tip.dir() <<
                 " for offer " << m_tip.index();
             return;
         }
         auto v (p->getFieldV256 (sfIndexes));
         auto& x (v.peekValue());
         auto it (std::find (x.begin(), x.end(), m_tip.index()));
         if (it == x.end())
         {
             if (m_journal.error) m_journal.error <<
                 "Missing offer " << m_tip.index() <<
                 " for directory " << m_tip.dir();
             return;
         }
         x.erase (it);
         p->setFieldV256 (sfIndexes, v);
         view.entryModify (p);
         if (m_journal.trace) m_journal.trace <<
             "Missing offer " << m_tip.index() <<
             " removed from directory " << m_tip.dir();
     }
bool ripple::core::OfferStream::fill (Amounts const & remaining_funds) inline
Updates the offer to reflect remaining funds. The caller is responsible for following all the rounding rules. The offer will be considered fully consumed if either the in or the out amount is zero.
Returns
true If the offer had no funds remaining.
Definition at line 263 of file OfferStream.h.
     {
         // Erase the offer if it is fully consumed (in==0 || out==0)
         // This is the same as becoming unfunded
         return false;
     }
bool ripple::core::OfferStream::step () inline
Advance to the next valid offer. This automatically removes:
Offers with missing ledger entries
Offers found unfunded
expired offers
Returns
true if there is a valid offer.
Definition at line 162 of file OfferStream.h.
References ripple::core::Offer::account(), ripple::core::Offer::amount(), ripple::core::BookTip::entry(), erase(), m_journal, m_offer, m_tip, m_when, ripple::LedgerEntrySet::offerDelete(), ripple::core::Amounts::out, ripple::core::BookTip::quality(), ripple::core::BookTip::step(), beast::Journal::trace, view(), view_cancel(), and beast::Journal::warning.
     {
         // Modifying the order or logic of these
         // operations causes a protocol breaking change.
         for(;;)
         {
             // BookTip::step deletes the current offer from the view before
             // advancing to the next (unless the ledger entry is missing).
             if (! m_tip.step())
                 return false;
             SLE::pointer const& entry (m_tip.entry());
             // Remove if missing
             if (! entry)
             {
                 erase (view());
                 erase (view_cancel());
                 continue;
             }
             // Remove if expired
             if (entry->isFieldPresent (sfExpiration) &&
                 entry->getFieldU32 (sfExpiration) <= m_when)
             {
                 view_cancel().offerDelete (entry->getIndex());
                 if (m_journal.trace) m_journal.trace <<
                     "Removing expired offer " << entry->getIndex();
                 continue;
             }
             m_offer = Offer (entry, m_tip.quality());
             Amounts const amount (m_offer.amount());
             // Remove if either amount is zero
             if (amount.empty())
             {
                 view_cancel().offerDelete (entry->getIndex());
                 if (m_journal.warning) m_journal.warning <<
                     "Removing bad offer " << entry->getIndex();
                 m_offer = Offer{};
                 continue;
             }
             // Calculate owner funds
             // VFALCO NOTE The calling code also checks the funds,
             //             how expensive is looking up the funds twice?
             Amount const owner_funds (view().accountFunds (
                 m_offer.account(), m_offer.amount().out));
             // Check for unfunded offer
             if (owner_funds <= zero)
             {
                 // If the owner's balance in the pristine view is the same,
                 // we haven't modified the balance and therefore the
                 // offer is "found unfunded" versus "became unfunded"
                 if (view_cancel().accountFunds (m_offer.account(),
                     m_offer.amount().out) == owner_funds)
                 {
                     view_cancel().offerDelete (entry->getIndex());
                     if (m_journal.trace) m_journal.trace <<
                         "Removing unfunded offer " << entry->getIndex();
                 }
                 else
                 {
                     if (m_journal.trace) m_journal.trace <<
                         "Removing became unfunded offer " << entry->getIndex();
                 }
                 m_offer = Offer{};
                 continue;
             }
 #if 0
             // Remove if its our own offer
             //
             // VFALCO NOTE We might not want this for payments
             //
             if (m_account == owner)
             {
                 view_cancel().offerDelete (entry->getIndex());
                 if (m_journal.trace) m_journal.trace <<
                     "Removing self offer " << entry->getIndex();
                 continue;
             }
 #endif
             break;
         }
         return true;
     }
Offer const& ripple::core::OfferStream::tip () const inline
Returns the offer at the tip of the order book. Offers are always presented in decreasing quality. Only valid if step() returned true.
Definition at line 149 of file OfferStream.h.
References m_offer.
     {
         return m_offer;
     }
LedgerView& ripple::core::OfferStream::view () inline noexcept
Definition at line 121 of file OfferStream.h.
References m_view.
Referenced by step().
     {
         return m_view;
     }
LedgerView& ripple::core::OfferStream::view_cancel () inline noexcept
Definition at line 127 of file OfferStream.h.
References m_view_cancel.
Referenced by step().
     {
         return m_view_cancel;
     }
Member Data Documentation
Book ripple::core::OfferStream::m_book protected
Definition at line 61 of file OfferStream.h.
Referenced by book().
beast::Journal ripple::core::OfferStream::m_journal protected
Definition at line 58 of file OfferStream.h.
Referenced by erase(), and step().
Offer ripple::core::OfferStream::m_offer protected
Definition at line 64 of file OfferStream.h.
Referenced by step(), and tip().
BookTip ripple::core::OfferStream::m_tip protected
Definition at line 63 of file OfferStream.h.
Referenced by dir(), erase(), and step().
std::reference_wrapper<LedgerView> ripple::core::OfferStream::m_view protected
Definition at line 59 of file OfferStream.h.
Referenced by view().
std::reference_wrapper<LedgerView> ripple::core::OfferStream::m_view_cancel protected
Definition at line 60 of file OfferStream.h.
Referenced by view_cancel().
Clock::time_point ripple::core::OfferStream::m_when protected
Definition at line 62 of file OfferStream.h.
Referenced by step().
The documentation for this class was generated from the following file:
rippled/src/ripple_app/book/OfferStream.h