rippled: beast::Error Class Reference
beast::Error Class Reference
#include <Error.h>
Public Types
enum Code {
success, general, canceled, exception,
unexpected, platform, noMemory, noMoreData,
invalidData, bufferSpace, badParameter, assertFailed,
fileInUse, fileExists, fileNoPerm, fileIOError,
fileNoSpace, fileNotFound, fileNameInvalid
}
Public Member Functions
Error ()
Error (Error const &other)
Error & operator= (Error const &other)
virtual ~Error () noexcept
Code code () const
bool failed () const
operator bool () const
String const getReasonText () const
String const getSourceFilename () const
int getLineNumber () const
Error & fail (char const *sourceFileName, int lineNumber, String const reasonText, Code errorCode=general)
Error & fail (char const *sourceFileName, int lineNumber, Code errorCode=general)
void reset ()
void willBeReported () const
char const * what () const noexcept
Static Public Member Functions
static String const getReasonTextForCode (Code code)
Private Attributes
Code m_code
String m_reasonText
String m_sourceFileName
int m_lineNumber
bool m_needsToBeChecked
String m_what
char const * m_szWhat
Detailed Description
A concise error report.
This lightweight but flexible class records lets you record the file and line where a recoverable error occurred, along with some optional human readable text.
A recoverable error can be passed along and turned into a non recoverable error by throwing the object: it's derivation from std::exception is fully compliant with the C++ exception interface.
Definition at line 43 of file Error.h.
Member Enumeration Documentation
enum beast::Error::Code
Numeric code.
This enumeration is useful when the caller needs to take different actions depending on the failure. For example, trying again later if a file is locked.
Enumerator
success
"the operation was successful"
general
"a general error occurred"
canceled
"the operation was canceled"
exception
"an exception was thrown"
unexpected
"an unexpected result was encountered"
platform
"a system exception was signaled"
noMemory
"there was not enough memory"
noMoreData
"the end of data was reached"
invalidData
"the data is corrupt or invalid"
bufferSpace
"the buffer is too small"
badParameter
"one or more parameters were invalid"
assertFailed
"an assertion failed"
fileInUse
"the file is in use"
fileExists
"the file exists"
fileNoPerm
"permission was denied" (file attributes conflict)
fileIOError
"an I/O or device error occurred"
fileNoSpace
"there is no space left on the device"
fileNotFound
"the file was not found"
fileNameInvalid
"the file name was illegal or malformed"
Definition at line 53 of file Error.h.
     {
         success,
         general,
         canceled,
         exception,
         unexpected,
         platform,
         noMemory,
         noMoreData,
         invalidData,
         bufferSpace,
         badParameter,
         assertFailed,
         fileInUse,
         fileExists,
         fileNoPerm,
         fileIOError,
         fileNoSpace,
         fileNotFound,
         fileNameInvalid
     };
Constructor & Destructor Documentation
beast::Error::Error ()
Definition at line 33 of file Error.cpp.
     : m_code (success)
     , m_lineNumber (0)
     , m_needsToBeChecked (true)
     , m_szWhat (0)
 {
 }
beast::Error::Error (Error const & other)
Definition at line 41 of file Error.cpp.
References m_needsToBeChecked.
     : m_code (other.m_code)
     , m_reasonText (other.m_reasonText)
     , m_sourceFileName (other.m_sourceFileName)
     , m_lineNumber (other.m_lineNumber)
     , m_needsToBeChecked (true)
     , m_szWhat (0)
 {
     other.m_needsToBeChecked = false;
 }
beast::Error::~Error () virtual noexcept
Definition at line 52 of file Error.cpp.
References bassert, and m_needsToBeChecked.
 {
     /* If this goes off it means an error object was created but never tested */
     bassert (!m_needsToBeChecked);
 }
Member Function Documentation
Error::Code beast::Error::code () const
Definition at line 73 of file Error.cpp.
References m_code, and m_needsToBeChecked.
Referenced by failed(), and operator bool().
 {
     m_needsToBeChecked = false;
     return m_code;
 }
Error & beast::Error::fail (char const * sourceFileName, int lineNumber, String const reasonText, Code errorCode = general)
Definition at line 99 of file Error.cpp.
References bassert, beast::Debug::getFileNameFromPath(), m_code, m_lineNumber, m_needsToBeChecked, m_reasonText, m_sourceFileName, and success.
Referenced by ldb_test.LDBTestCase::assertRunFAILFull(), fail(), beast::sqdb::detail::sqliteError(), and ripple::PeerFinder::StoreSqdb::update().
 {
     bassert (m_code == success);
     bassert (errorCode != success);
     m_code = errorCode;
     m_reasonText = reasonText;
     m_sourceFileName = Debug::getFileNameFromPath (sourceFileName);
     m_lineNumber = lineNumber;
     m_needsToBeChecked = true;
     return *this;
 }
Error & beast::Error::fail (char const * sourceFileName, int lineNumber, Code errorCode = general)
Definition at line 116 of file Error.cpp.
References fail(), and getReasonTextForCode().
Referenced by ldb_test.LDBTestCase::assertRunFAILFull().
 {
     return fail (sourceFileName,
                  lineNumber,
                  getReasonTextForCode (errorCode),
                  errorCode);
 }
bool beast::Error::failed () const
Definition at line 79 of file Error.cpp.
References code(), and success.
 {
     return code () != success;
 }
int beast::Error::getLineNumber () const
Definition at line 94 of file Error.cpp.
References m_lineNumber.
 {
     return m_lineNumber;
 }
String const beast::Error::getReasonText () const
Definition at line 84 of file Error.cpp.
References m_reasonText.
Referenced by ripple::Validators::StoreSqdb::report(), and ripple::PeerFinder::StoreSqdb::report().
 {
     return m_reasonText;
 }
String const beast::Error::getReasonTextForCode (Code code) static
Definition at line 163 of file Error.cpp.
References assertFailed, badParameter, bufferSpace, canceled, exception, fileExists, fileInUse, fileIOError, fileNameInvalid, fileNoPerm, fileNoSpace, fileNotFound, general, invalidData, noMemory, noMoreData, platform, success, TRANS, and unexpected.
Referenced by fail().
 {
     String s;
     switch (code)
     {
     case success:
         s = TRANS ("the operation was successful");
         break;
     case general:
         s = TRANS ("a general error occurred");
         break;
     case canceled:
         s = TRANS ("the operation was canceled");
         break;
     case exception:
         s = TRANS ("an exception was thrown");
         break;
     case unexpected:
         s = TRANS ("an unexpected result was encountered");
         break;
     case platform:
         s = TRANS ("a system exception was signaled");
         break;
     case noMemory:
         s = TRANS ("there was not enough memory");
         break;
     case noMoreData:
         s = TRANS ("the end of data was reached");
         break;
     case invalidData:
         s = TRANS ("the data is corrupt or invalid");
         break;
     case bufferSpace:
         s = TRANS ("the buffer is too small");
         break;
     case badParameter:
         s = TRANS ("one or more parameters were invalid");
         break;
     case assertFailed:
         s = TRANS ("an assertion failed");
         break;
     case fileInUse:
         s = TRANS ("the file is in use");
         break;
     case fileExists:
         s = TRANS ("the file exists");
         break;
     case fileNoPerm:
         s = TRANS ("permission was denied");
         break;
     case fileIOError:
         s = TRANS ("an I/O or device error occurred");
         break;
     case fileNoSpace:
         s = TRANS ("there is no space left on the device");
         break;
     case fileNotFound:
         s = TRANS ("the file was not found");
         break;
     case fileNameInvalid:
         s = TRANS ("the file name was illegal or malformed");
         break;
     default:
         s = TRANS ("an unknown error code was received");
         break;
     }
     return s;
 }
String const beast::Error::getSourceFilename () const
Definition at line 89 of file Error.cpp.
References m_sourceFileName.
 {
     return m_sourceFileName;
 }
beast::Error::operator bool () const inline explicit
Definition at line 89 of file Error.h.
References code(), and success.
     {
         return code () != success;
     }
Error & beast::Error::operator= (Error const & other)
Definition at line 58 of file Error.cpp.
References beast::String::empty, m_code, m_lineNumber, m_needsToBeChecked, m_reasonText, m_sourceFileName, m_szWhat, and m_what.
 {
     m_code = other.m_code;
     m_reasonText = other.m_reasonText;
     m_sourceFileName = other.m_sourceFileName;
     m_lineNumber = other.m_lineNumber;
     m_needsToBeChecked = true;
     m_what = String::empty;
     m_szWhat = 0;
     other.m_needsToBeChecked = false;
     return *this;
 }
void beast::Error::reset ()
Definition at line 126 of file Error.cpp.
References beast::String::empty, m_code, m_lineNumber, m_needsToBeChecked, m_reasonText, m_sourceFileName, m_szWhat, m_what, and success.
 {
     m_code = success;
     m_reasonText = String::empty;
     m_sourceFileName = String::empty;
     m_lineNumber = 0;
     m_needsToBeChecked = true;
     m_what = String::empty;
     m_szWhat = 0;
 }
char const * beast::Error::what () const noexcept
Definition at line 142 of file Error.cpp.
References m_code, m_lineNumber, m_reasonText, m_sourceFileName, m_szWhat, m_what, beast::String::toUTF8(), and TRANS.
Referenced by ripple::Validators::StoreSqdb::open().
 {
     if (! m_szWhat)
     {
         // The application could not be initialized because sqlite was denied access permission
         // The application unexpectedly quit because the exception 'sqlite was denied access permission at file ' was thrown
         m_what <<
                m_reasonText << " " <<
                TRANS ("at file") << " '" <<
                m_sourceFileName << "' " <<
                TRANS ("line") << " " <<
                String (m_lineNumber) << " " <<
                TRANS ("with code") << " = " <<
                String (m_code);
         m_szWhat = (const char*)m_what.toUTF8 ();
     }
     return m_szWhat;
 }
void beast::Error::willBeReported () const
Definition at line 137 of file Error.cpp.
References m_needsToBeChecked.
 {
     m_needsToBeChecked = false;
 }
Member Data Documentation
Code beast::Error::m_code private
Definition at line 123 of file Error.h.
Referenced by code(), fail(), operator=(), reset(), and what().
int beast::Error::m_lineNumber private
Definition at line 126 of file Error.h.
Referenced by fail(), getLineNumber(), operator=(), reset(), and what().
bool beast::Error::m_needsToBeChecked mutable private
Definition at line 127 of file Error.h.
Referenced by code(), Error(), fail(), operator=(), reset(), willBeReported(), and ~Error().
String beast::Error::m_reasonText private
Definition at line 124 of file Error.h.
Referenced by fail(), getReasonText(), operator=(), reset(), and what().
String beast::Error::m_sourceFileName private
Definition at line 125 of file Error.h.
Referenced by fail(), getSourceFilename(), operator=(), reset(), and what().
char const* beast::Error::m_szWhat mutable private
Definition at line 129 of file Error.h.
Referenced by operator=(), reset(), and what().
String beast::Error::m_what mutable private
Definition at line 128 of file Error.h.
Referenced by operator=(), reset(), and what().
The documentation for this class was generated from the following files:
rippled/src/beast/beast/utility/Error.h
rippled/src/beast/beast/utility/impl/Error.cpp