rippled: ripple::SHAMapNode Class Reference
ripple::SHAMapNode Class Reference
#include <SHAMapNode.h>
Public Member Functions
SHAMapNode ()
SHAMapNode (int depth, uint256 const &hash)
int getDepth () const
uint256 const & getNodeID () const
bool isValid () const
bool isRoot () const
size_t getMHash () const
virtual bool isPopulated () const
SHAMapNode getParentNodeID () const
SHAMapNode getChildNodeID (int m) const
int selectBranch (uint256 const &hash) const
bool operator< (const SHAMapNode &) const
bool operator> (const SHAMapNode &) const
bool operator<= (const SHAMapNode &) const
bool operator>= (const SHAMapNode &) const
bool operator== (const SHAMapNode &n) const
bool operator== (uint256 const &n) const
bool operator!= (const SHAMapNode &n) const
bool operator!= (uint256 const &n) const
void set (SHAMapNode const &from)
virtual std::string getString () const
void dump () const
void addIDRaw (Serializer &s) const
std::string getRawString () const
SHAMapNode (const void *ptr, int len)
Static Public Member Functions
static bool ClassInit ()
static uint256 getNodeID (int depth, uint256 const &hash)
static int getRawIDLength (void)
Protected Member Functions
SHAMapNode (int depth, uint256 const &id, bool)
Private Member Functions
void setMHash () const
Private Attributes
uint256 mNodeID
int mDepth
size_t mHash
Static Private Attributes
static uint256 smMasks [65]
Detailed Description
Definition at line 28 of file SHAMapNode.h.
Constructor & Destructor Documentation
ripple::SHAMapNode::SHAMapNode () inline
Definition at line 31 of file SHAMapNode.h.
Referenced by ripple::SHAMap::fetchRoot(), getChildNodeID(), and getParentNodeID().
                   : mDepth (0), mHash (0)
     {
         ;
     }
ripple::SHAMapNode::SHAMapNode (int depth, uint256 const & hash)
Definition at line 25 of file SHAMapNode.cpp.
                                                       : mNodeID (hash), mDepth (depth), mHash (0)
 {
     assert ((depth >= 0) && (depth < 65));
     mNodeID &= smMasks[depth];
 }
ripple::SHAMapNode::SHAMapNode (const void * ptr, int len)
Definition at line 31 of file SHAMapNode.cpp.
References ripple::base_uint< BITS >::begin(), mDepth, and mNodeID.
                                                 : mHash (0)
 {
     if (len < 33)
         mDepth = -1;
     else
     {
         memcpy (mNodeID.begin (), ptr, 32);
         mDepth = * (static_cast<const unsigned char*> (ptr) + 32);
     }
 }
ripple::SHAMapNode::SHAMapNode (int depth, uint256 const & id, bool) inline protected
Definition at line 118 of file SHAMapNode.h.
                                                     : mNodeID (id), mDepth (depth), mHash (0)
     {
         ;
     }
Member Function Documentation
void ripple::SHAMapNode::addIDRaw (Serializer & s) const
Definition at line 119 of file SHAMapNode.cpp.
References ripple::Serializer::add256(), ripple::Serializer::add8(), mDepth, and mNodeID.
Referenced by getRawString().
 {
     s.add256 (mNodeID);
     s.add8 (mDepth);
 }
bool ripple::SHAMapNode::ClassInit () static
Definition at line 59 of file SHAMapNode.cpp.
References ripple::base_uint< BITS >::begin(), and smMasks.
 {
     uint256 selector;
     for (int i = 0; i < 64; i += 2)
     {
         // VFALCO TODO group these statics together in an object
         smMasks[i] = selector;
         * (selector.begin () + (i / 2)) = 0xF0;
         smMasks[i + 1] = selector;
         * (selector.begin () + (i / 2)) = 0xFF;
     }
     smMasks[64] = selector;
     return true;
 }
void ripple::SHAMapNode::dump () const
Definition at line 176 of file SHAMapNode.cpp.
References getString(), ripple::lsDEBUG, and WriteLog.
Referenced by ripple::SHAMap::addGiveItem().
 {
     WriteLog (lsDEBUG, SHAMapNode) << getString ();
 }
SHAMapNode ripple::SHAMapNode::getChildNodeID (int m) const
Definition at line 133 of file SHAMapNode.cpp.
References ripple::base_uint< BITS >::begin(), mDepth, mNodeID, and SHAMapNode().
Referenced by ripple::SHAMap::compare(), ripple::SHAMap::dropBelow(), ripple::SHAMap::firstBelow(), ripple::SHAMap::getFetchPack(), ripple::SHAMap::getMissingNodes(), ripple::SHAMap::getNodeFat(), ripple::SHAMap::getNodePointer(), ripple::SHAMap::getPath(), ripple::SHAMap::hasInnerNode(), ripple::SHAMap::hasLeafNode(), ripple::SHAMap::lastBelow(), ripple::SHAMap::onlyBelow(), ripple::SHAMap::visitLeavesInternal(), ripple::SHAMap::walkBranch(), and ripple::SHAMap::walkToPointer().
 {
     assert ((m >= 0) && (m < 16));
     uint256 child (mNodeID);
     child.begin ()[mDepth / 2] |= (mDepth & 1) ? m : (m << 4);
     return SHAMapNode (mDepth + 1, child, true);
 }
int ripple::SHAMapNode::getDepth () const inline
Definition at line 37 of file SHAMapNode.h.
References mDepth.
Referenced by ripple::SHAMap::addKnownNode(), ripple::SHAMapTreeNode::getString(), and ripple::SHAMap::hasInnerNode().
     {
         return mDepth;
     }
size_t ripple::SHAMapNode::getMHash () const inline
Definition at line 53 of file SHAMapNode.h.
References mHash, and setMHash().
Referenced by ripple::hash_value(), and std::hash< ripple::SHAMapNode >::operator()().
     {
         if (mHash == 0) setMHash ();
         return mHash;
     }
uint256 const& ripple::SHAMapNode::getNodeID () const inline
Definition at line 41 of file SHAMapNode.h.
References mNodeID.
Referenced by ripple::SHAMap::addKnownNode(), ripple::SHAMapTreeNode::dump(), ripple::SHAMap::getNode(), ripple::SHAMap::getNodePointer(), ripple::SHAMapTreeNode::getString(), and ripple::SHAMap::hasInnerNode().
     {
         return mNodeID;
     }
uint256 ripple::SHAMapNode::getNodeID (int depth, uint256 const & hash) static
Definition at line 113 of file SHAMapNode.cpp.
References smMasks.
 {
     assert ((depth >= 0) && (depth <= 64));
     return hash & smMasks[depth];
 }
SHAMapNode ripple::SHAMapNode::getParentNodeID () const inline
Definition at line 65 of file SHAMapNode.h.
References mDepth, mNodeID, and SHAMapNode().
Referenced by ripple::SHAMap::addKnownNode().
     {
         assert (mDepth);
         return SHAMapNode (mDepth - 1, mNodeID);
     }
static int ripple::SHAMapNode::getRawIDLength (void) inline static
Definition at line 111 of file SHAMapNode.h.
     {
         return 33;
     }
std::string ripple::SHAMapNode::getRawString () const
Definition at line 125 of file SHAMapNode.cpp.
References addIDRaw(), and ripple::Serializer::getString().
Referenced by ripple::TransactionAcquire::trigger(), and ripple::InboundLedger::trigger().
 {
     Serializer s (33);
     addIDRaw (s);
     return s.getString ();
 }
std::string ripple::SHAMapNode::getString () const virtual
Reimplemented in ripple::SHAMapTreeNode.
Definition at line 41 of file SHAMapNode.cpp.
References ripple::base_uint< BITS >::GetHex(), ripple::base_uint< BITS >::isZero(), mDepth, and mNodeID.
Referenced by dump(), ripple::operator<<(), and selectBranch().
 {
     static boost::format NodeID ("NodeID(%s,%s)");
     if ((mDepth == 0) && (mNodeID.isZero ()))
         return "NodeID(root)";
     return str (boost::format (NodeID)
                 % beast::lexicalCastThrow <std::string> (mDepth)
                 % mNodeID.GetHex ());
 }
virtual bool ripple::SHAMapNode::isPopulated () const inline virtual
Reimplemented in ripple::SHAMapTreeNode.
Definition at line 60 of file SHAMapNode.h.
     {
         return false;
     }
bool ripple::SHAMapNode::isRoot () const inline
Definition at line 49 of file SHAMapNode.h.
References mDepth.
Referenced by ripple::SHAMap::addKnownNode(), ripple::SHAMap::fetchNodeExternalNT(), ripple::SHAMap::getNodeAsync(), and ripple::SHAMap::getNodeFat().
     {
         return mDepth == 0;
     }
bool ripple::SHAMapNode::isValid () const inline
Definition at line 45 of file SHAMapNode.h.
References mDepth.
     {
         return (mDepth >= 0) && (mDepth < 64);
     }
bool ripple::SHAMapNode::operator!= (const SHAMapNode & n) const inline
Definition at line 87 of file SHAMapNode.h.
References mDepth, and mNodeID.
     {
         return (mDepth != n.mDepth) || (mNodeID != n.mNodeID);
     }
bool ripple::SHAMapNode::operator!= (uint256 const & n) const inline
Definition at line 91 of file SHAMapNode.h.
References mNodeID.
     {
         return n != mNodeID;
     }
bool ripple::SHAMapNode::operator< (const SHAMapNode & s) const
Definition at line 77 of file SHAMapNode.cpp.
References mDepth, and mNodeID.
 {
     if (s.mDepth < mDepth) return true;
     if (s.mDepth > mDepth) return false;
     return mNodeID < s.mNodeID;
 }
bool ripple::SHAMapNode::operator<= (const SHAMapNode & s) const
Definition at line 95 of file SHAMapNode.cpp.
References mDepth, and mNodeID.
 {
     if (s.mDepth < mDepth) return true;
     if (s.mDepth > mDepth) return false;
     return mNodeID <= s.mNodeID;
 }
bool ripple::SHAMapNode::operator== (const SHAMapNode & n) const inline
Definition at line 79 of file SHAMapNode.h.
References mDepth, and mNodeID.
     {
         return (mDepth == n.mDepth) && (mNodeID == n.mNodeID);
     }
bool ripple::SHAMapNode::operator== (uint256 const & n) const inline
Definition at line 83 of file SHAMapNode.h.
References mNodeID.
     {
         return n == mNodeID;
     }
bool ripple::SHAMapNode::operator> (const SHAMapNode & s) const
Definition at line 86 of file SHAMapNode.cpp.
References mDepth, and mNodeID.
 {
     if (s.mDepth < mDepth) return false;
     if (s.mDepth > mDepth) return true;
     return mNodeID > s.mNodeID;
 }
bool ripple::SHAMapNode::operator>= (const SHAMapNode & s) const
Definition at line 104 of file SHAMapNode.cpp.
References mDepth, and mNodeID.
 {
     if (s.mDepth < mDepth) return false;
     if (s.mDepth > mDepth) return true;
     return mNodeID >= s.mNodeID;
 }
int ripple::SHAMapNode::selectBranch (uint256 const & hash) const
Definition at line 144 of file SHAMapNode.cpp.
References ripple::base_uint< BITS >::begin(), getString(), mDepth, mNodeID, and smMasks.
Referenced by ripple::SHAMap::getNodePointer(), ripple::SHAMap::getPath(), ripple::SHAMap::hasInnerNode(), ripple::SHAMap::hasLeafNode(), and ripple::SHAMap::walkToPointer().
 {
 #if RIPPLE_VERIFY_NODEOBJECT_KEYS
     if (mDepth >= 64)
     {
         assert (false);
         return -1;
     }
     if ((hash & smMasks[mDepth]) != mNodeID)
     {
         Log::out() << "selectBranch(" << getString ();
         Log::out() << "  " << hash << " off branch";
         assert (false);
         return -1;  // does not go under this node
     }
 #endif
     int branch = * (hash.begin () + (mDepth / 2));
     if (mDepth & 1)
         branch &= 0xf;
     else
         branch >>= 4;
     assert ((branch >= 0) && (branch < 16));
     return branch;
 }
void ripple::SHAMapNode::set (SHAMapNode const & from) inline
Definition at line 95 of file SHAMapNode.h.
References mDepth, mHash, and mNodeID.
     {
         mNodeID = from.mNodeID;
         mDepth = from.mDepth;
         mHash = from.mHash;
     }
void ripple::SHAMapNode::setMHash () const private
Definition at line 97 of file SHAMap.cpp.
References ripple::base_uint< BITS >::begin(), ripple::HashMaps::getInstance(), ripple::HashMaps::getNonce(), ripple::HashMaps::goldenRatio, mDepth, mHash, and mNodeID.
Referenced by getMHash().
 {
     using namespace std;
     std::size_t h = HashMaps::getInstance ().getNonce <std::size_t> ()
                     + (mDepth * HashMaps::goldenRatio);
     const unsigned int* ptr = reinterpret_cast <const unsigned int*> (mNodeID.begin ());
     for (int i = (mDepth + 7) / 8; i != 0; --i)
         h = (h * HashMaps::goldenRatio) ^ *ptr++;
     mHash = h;
 }
Member Data Documentation
int ripple::SHAMapNode::mDepth private
Definition at line 127 of file SHAMapNode.h.
Referenced by addIDRaw(), getChildNodeID(), getDepth(), getParentNodeID(), getString(), isRoot(), isValid(), operator!=(), operator<(), operator<=(), operator==(), operator>(), operator>=(), selectBranch(), set(), setMHash(), and SHAMapNode().
size_t ripple::SHAMapNode::mHash mutable private
Definition at line 128 of file SHAMapNode.h.
Referenced by getMHash(), set(), and setMHash().
uint256 ripple::SHAMapNode::mNodeID private
Definition at line 126 of file SHAMapNode.h.
Referenced by addIDRaw(), getChildNodeID(), getNodeID(), getParentNodeID(), getString(), operator!=(), operator<(), operator<=(), operator==(), operator>(), operator>=(), selectBranch(), set(), setMHash(), and SHAMapNode().
uint256 ripple::SHAMapNode::smMasks static private
Definition at line 124 of file SHAMapNode.h.
Referenced by ClassInit(), getNodeID(), and selectBranch().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/shamap/SHAMapNode.h
rippled/src/ripple_app/shamap/SHAMap.cpp
rippled/src/ripple_app/shamap/SHAMapNode.cpp