rippled: beast::RegistryKeyWrapper Struct Reference
beast::RegistryKeyWrapper Struct Reference
Public Member Functions
RegistryKeyWrapper (String name, const bool createForWriting, const DWORD wow64Flags)
~RegistryKeyWrapper ()
Static Public Member Functions
static bool setValue (const String &regValuePath, const DWORD type, const void *data, size_t dataSize)
static std::uint32_t getBinaryValue (const String &regValuePath, MemoryBlock &result, DWORD wow64Flags)
static String getValue (const String &regValuePath, const String &defaultValue, DWORD wow64Flags)
static bool valueExists (const String &regValuePath, const DWORD wow64Flags)
Public Attributes
HKEY key
const wchar_t * wideCharValueName
String valueName
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
Definition at line 27 of file win32_Registry.cpp.
Constructor & Destructor Documentation
beast::RegistryKeyWrapper::RegistryKeyWrapper (String name, const bool createForWriting, const DWORD wow64Flags) inline
Definition at line 29 of file win32_Registry.cpp.
References beast::String::indexOfChar(), key, beast::String::lastIndexOfChar(), beast::String::startsWithIgnoreCase(), beast::String::substring(), beast::String::toWideCharPointer(), valueName, and wideCharValueName.
         : key (0), wideCharValueName (nullptr)
     {
         HKEY rootKey = 0;
         if (name.startsWithIgnoreCase ("HKEY_CURRENT_USER\\"))        rootKey = HKEY_CURRENT_USER;
         else if (name.startsWithIgnoreCase ("HKEY_LOCAL_MACHINE\\"))  rootKey = HKEY_LOCAL_MACHINE;
         else if (name.startsWithIgnoreCase ("HKEY_CLASSES_ROOT\\"))   rootKey = HKEY_CLASSES_ROOT;
         if (rootKey != 0)
         {
             name = name.substring (name.indexOfChar ('\\') + 1);
             const int lastSlash = name.lastIndexOfChar ('\\');
             valueName = name.substring (lastSlash + 1);
             wideCharValueName = valueName.toWideCharPointer();
             name = name.substring (0, lastSlash);
             const wchar_t* const wideCharName = name.toWideCharPointer();
             DWORD result;
             if (createForWriting)
                 RegCreateKeyEx (rootKey, wideCharName, 0, 0, REG_OPTION_NON_VOLATILE,
                                 KEY_WRITE | KEY_QUERY_VALUE | wow64Flags, 0, &key, &result);
             else
                 RegOpenKeyEx (rootKey, wideCharName, 0, KEY_READ | wow64Flags, &key);
         }
     }
beast::RegistryKeyWrapper::~RegistryKeyWrapper () inline
Definition at line 58 of file win32_Registry.cpp.
References key.
     {
         if (key != 0)
             RegCloseKey (key);
     }
Member Function Documentation
static std::uint32_t beast::RegistryKeyWrapper::getBinaryValue (const String & regValuePath, MemoryBlock & result, DWORD wow64Flags) inline static
Definition at line 75 of file win32_Registry.cpp.
References beast::MemoryBlock::getData(), key, beast::MemoryBlock::setSize(), and wideCharValueName.
Referenced by getValue().
     {
         const RegistryKeyWrapper key (regValuePath, false, wow64Flags);
         if (key.key != 0)
         {
             for (unsigned long bufferSize = 1024; ; bufferSize *= 2)
             {
                 result.setSize (bufferSize, false);
                 DWORD type = REG_NONE;
                 const LONG err = RegQueryValueEx (key.key, key.wideCharValueName, 0, &type,
                                                   (LPBYTE) result.getData(), &bufferSize);
                 if (err == ERROR_SUCCESS)
                 {
                     result.setSize (bufferSize, false);
                     return type;
                 }
                 if (err != ERROR_MORE_DATA)
                     break;
             }
         }
         return REG_NONE;
     }
static String beast::RegistryKeyWrapper::getValue (const String & regValuePath, const String & defaultValue, DWORD wow64Flags) inline static
Definition at line 103 of file win32_Registry.cpp.
References getBinaryValue(), and beast::MemoryBlock::getData().
     {
         MemoryBlock buffer;
         switch (getBinaryValue (regValuePath, buffer, wow64Flags))
         {
             case REG_SZ:    return static_cast <const WCHAR*> (buffer.getData());
             case REG_DWORD: return String ((int) *reinterpret_cast<const DWORD*> (buffer.getData()));
             default:        break;
         }
         return defaultValue;
     }
static bool beast::RegistryKeyWrapper::setValue (const String & regValuePath, const DWORD type, const void * data, size_t dataSize) inline static
Definition at line 64 of file win32_Registry.cpp.
References key, and wideCharValueName.
     {
         const RegistryKeyWrapper key (regValuePath, true, 0);
         return key.key != 0
                 && RegSetValueEx (key.key, key.wideCharValueName, 0, type,
                                   reinterpret_cast <const BYTE*> (data),
                                   (DWORD) dataSize) == ERROR_SUCCESS;
     }
static bool beast::RegistryKeyWrapper::valueExists (const String & regValuePath, const DWORD wow64Flags) inline static
Definition at line 116 of file win32_Registry.cpp.
References key, and wideCharValueName.
     {
         const RegistryKeyWrapper key (regValuePath, false, wow64Flags);
         if (key.key == 0)
             return false;
         unsigned char buffer [512];
         unsigned long bufferSize = sizeof (buffer);
         DWORD type = 0;
         const LONG result = RegQueryValueEx (key.key, key.wideCharValueName,
                                              0, &type, buffer, &bufferSize);
         return result == ERROR_SUCCESS || result == ERROR_MORE_DATA;
     }
Member Data Documentation
HKEY beast::RegistryKeyWrapper::key
Definition at line 133 of file win32_Registry.cpp.
Referenced by getBinaryValue(), RegistryKeyWrapper(), setValue(), valueExists(), and ~RegistryKeyWrapper().
String beast::RegistryKeyWrapper::valueName
Definition at line 135 of file win32_Registry.cpp.
Referenced by RegistryKeyWrapper().
const wchar_t* beast::RegistryKeyWrapper::wideCharValueName
Definition at line 134 of file win32_Registry.cpp.
Referenced by getBinaryValue(), RegistryKeyWrapper(), setValue(), and valueExists().
The documentation for this struct was generated from the following file:
rippled/src/beast/modules/beast_core/native/win32_Registry.cpp