rippled: ripple::NodeStore::ManagerImp Class Reference
ripple::NodeStore::ManagerImp Class Reference
Public Types
typedef std::vector
< std::unique_ptr< Factory > > List
Public Member Functions
ManagerImp (std::vector< std::unique_ptr< Factory >> factories)
~ManagerImp ()
void add_factory (std::unique_ptr< Factory > factory)
void add_known_factories ()
Factory * find (std::string const &name) const
std::unique_ptr< Backend > make_Backend (Parameters const &parameters, Scheduler &scheduler, beast::Journal journal)
std::unique_ptr< Database > make_Database (std::string const &name, Scheduler &scheduler, beast::Journal journal, int readThreads, Parameters const &backendParameters, Parameters fastBackendParameters)
Public Member Functions inherited from ripple::NodeStore::Manager
virtual ~Manager ()=0
Static Public Member Functions
static void missing_backend ()
Public Attributes
List m_list
Detailed Description
Definition at line 23 of file Manager.cpp.
Member Typedef Documentation
typedef std::vector<std::unique_ptr <Factory> > ripple::NodeStore::ManagerImp::List
Definition at line 26 of file Manager.cpp.
Constructor & Destructor Documentation
ripple::NodeStore::ManagerImp::ManagerImp (std::vector< std::unique_ptr< Factory >> factories) inline explicit
Definition at line 29 of file Manager.cpp.
References add_known_factories(), and m_list.
         : m_list (std::move (factories))
     {
         m_list.reserve (20);
         add_known_factories ();
     }
ripple::NodeStore::ManagerImp::~ManagerImp () inline
Definition at line 37 of file Manager.cpp.
     {
     }
Member Function Documentation
void ripple::NodeStore::ManagerImp::add_factory (std::unique_ptr< Factory > factory) inline virtual
Add the specified factory to the manager. Thread safety: Not thread-safe.
Implements ripple::NodeStore::Manager.
Definition at line 41 of file Manager.cpp.
References m_list.
Referenced by add_known_factories().
     {
         m_list.emplace_back (std::move (factory));
     }
void ripple::NodeStore::ManagerImp::add_known_factories () inline
Definition at line 46 of file Manager.cpp.
References add_factory(), ripple::NodeStore::make_LevelDBFactory(), ripple::NodeStore::make_MemoryFactory(), ripple::NodeStore::make_NullFactory(), and ripple::NodeStore::make_RocksDBFactory().
Referenced by ManagerImp().
     {
         // This is part of the ripple_app module since it has dependencies
         //addFactory (make_SqliteFactory ());
         add_factory (make_LevelDBFactory ());
         add_factory (make_MemoryFactory ());
         add_factory (make_NullFactory ());
     #if RIPPLE_HYPERLEVELDB_AVAILABLE
         add_factory (make_HyperDBFactory ());
     #endif
     #if RIPPLE_ROCKSDB_AVAILABLE
         add_factory (make_RocksDBFactory ());
     #endif
     }
Factory* ripple::NodeStore::ManagerImp::find (std::string const & name) const inline virtual
Return a pointer to the matching factory if it exists.
Parameters
name The name to match, performed case-insensitive.
Returns
nullptr if a match was not found.
Implements ripple::NodeStore::Manager.
Definition at line 65 of file Manager.cpp.
References m_list.
Referenced by make_Backend().
     {
         for (List::const_iterator iter (m_list.begin ());
             iter != m_list.end (); ++iter)
             if ((*iter)->getName().compareIgnoreCase (name) == 0)
                 return iter->get();
         return nullptr;
     }
std::unique_ptr<Backend> ripple::NodeStore::ManagerImp::make_Backend (Parameters const & parameters, Scheduler & scheduler, beast::Journal journal) inline virtual
Create a backend.
Implements ripple::NodeStore::Manager.
Definition at line 82 of file Manager.cpp.
References ripple::NodeStore::Factory::createInstance(), find(), ripple::NodeObject::keyBytes, and missing_backend().
Referenced by make_Database().
     {
         std::unique_ptr <Backend> backend;
         std::string const type (parameters ["type"].toStdString ());
         if (! type.empty ())
         {
             Factory* const factory (find (type));
             if (factory != nullptr)
             {
                 backend = factory->createInstance (
                     NodeObject::keyBytes, parameters, scheduler, journal);
             }
             else
             {
                 missing_backend ();
             }
         }
         else
         {
             missing_backend ();
         }
         return backend;
     }
std::unique_ptr<Database> ripple::NodeStore::ManagerImp::make_Database (std::string const & name, Scheduler & scheduler, beast::Journal journal, int readThreads, Parameters const & backendParameters, Parameters fastBackendParameters) inline virtual
Construct a node store database.
The parameters are key value pairs passed to the backend. The 'type' key must exist, it defines the choice of backend. Most backends also require a 'path' field.
Some choices for 'type' are: HyperLevelDB, LevelDBFactory, SQLite, MDB
If the fastBackendParameter is omitted or empty, no ephemeral database is used. If the scheduler parameter is omited or unspecified, a synchronous scheduler is used which performs all tasks immediately on the caller's thread.
Note
If the database cannot be opened or created, an exception is thrown.
Parameters
name A diagnostic label for the database.
scheduler The scheduler to use for performing asynchronous tasks.
readThreads The number of async read threads to create
backendParameters The parameter string for the persistent backend.
fastBackendParameters [optional] The parameter string for the ephemeral backend.
Returns
The opened database.
Implements ripple::NodeStore::Manager.
Definition at line 111 of file Manager.cpp.
References make_Backend(), name, and beast::StringPairArray::size().
     {
         std::unique_ptr <Backend> backend (make_Backend (
             backendParameters, scheduler, journal));
         std::unique_ptr <Backend> fastBackend (
             (fastBackendParameters.size () > 0)
                 ? make_Backend (fastBackendParameters, scheduler, journal)
                 : nullptr);
         return std::make_unique <DatabaseImp> (name, scheduler, readThreads,
             std::move (backend), std::move (fastBackend), journal);
     }
static void ripple::NodeStore::ManagerImp::missing_backend () inline static
Definition at line 74 of file Manager.cpp.
Referenced by make_Backend().
     {
         throw std::runtime_error (
             "Your rippled.cfg is missing a [node_db] entry, "
             "please see the rippled-example.cfg file!"
             );
     }
Member Data Documentation
List ripple::NodeStore::ManagerImp::m_list
Definition at line 27 of file Manager.cpp.
Referenced by add_factory(), find(), and ManagerImp().
The documentation for this class was generated from the following file:
rippled/src/ripple_core/nodestore/impl/Manager.cpp