rippled: rocksdb::log::Reader Class Reference
rocksdb::log::Reader Class Reference
#include <log_reader.h>
Classes
class Reporter
Public Member Functions
Reader (unique_ptr< SequentialFile > &&file, Reporter *reporter, bool checksum, uint64_t initial_offset)
~Reader ()
bool ReadRecord (Slice *record, std::string *scratch)
uint64_t LastRecordOffset ()
bool IsEOF ()
void UnmarkEOF ()
SequentialFile * file ()
Private Types
enum { kEof = kMaxRecordType + 1, kBadRecord = kMaxRecordType + 2 }
Private Member Functions
bool SkipToInitialBlock ()
unsigned int ReadPhysicalRecord (Slice *result)
void ReportCorruption (size_t bytes, const char *reason)
void ReportDrop (size_t bytes, const Status &reason)
Reader (const Reader &)
void operator= (const Reader &)
Private Attributes
const unique_ptr< SequentialFile > file_
Reporter *const reporter_
bool const checksum_
char *const backing_store_
Slice buffer_
bool eof_
uint64_t last_record_offset_
uint64_t end_of_buffer_offset_
uint64_t const initial_offset_
Detailed Description
Definition at line 25 of file log_reader.h.
Member Enumeration Documentation
anonymous enum private
Enumerator
kEof
kBadRecord
Definition at line 95 of file log_reader.h.
        {
     kEof = kMaxRecordType + 1,
     // Returned whenever we find an invalid physical record.
     // Currently there are three situations in which this happens:
     // * The record has an invalid CRC (ReadPhysicalRecord reports a drop)
     // * The record is a 0-length record (No drop is reported)
     // * The record is below constructor's initial_offset (No drop is reported)
     kBadRecord = kMaxRecordType + 2
   };
Constructor & Destructor Documentation
rocksdb::log::Reader::Reader (unique_ptr< SequentialFile > && file, Reporter * reporter, bool checksum, uint64_t initial_offset)
Definition at line 23 of file log_reader.cc.
     : file_(std::move(file)),
       reporter_(reporter),
       checksum_(checksum),
       backing_store_(new char[kBlockSize]),
       buffer_(),
       eof_(false),
       last_record_offset_(0),
       end_of_buffer_offset_(0),
       initial_offset_(initial_offset) {
 }
rocksdb::log::Reader::~Reader ()
Definition at line 36 of file log_reader.cc.
References backing_store_.
                 {
   delete[] backing_store_;
 }
rocksdb::log::Reader::Reader (const Reader &) private
Member Function Documentation
SequentialFile* rocksdb::log::Reader::file () inline
Definition at line 76 of file log_reader.h.
References file_.
Referenced by rocksdb::log::LogTest::ForceError(), and rocksdb::log::LogTest::reset_source_contents().
 { return file_.get(); }
bool rocksdb::log::Reader::IsEOF () inline
Definition at line 66 of file log_reader.h.
References eof_.
                {
     return eof_;
   }
uint64_t rocksdb::log::Reader::LastRecordOffset ()
Definition at line 169 of file log_reader.cc.
References last_record_offset_.
Referenced by rocksdb::WALDumperCommand::DoCommand().
{
   return last_record_offset_;
 }
void rocksdb::log::Reader::operator= (const Reader &) private
unsigned int rocksdb::log::Reader::ReadPhysicalRecord (Slice * result) private
Definition at line 184 of file log_reader.cc.
References backing_store_, buffer_, checksum_, rocksdb::Slice::clear(), rocksdb::Slice::data(), rocksdb::DecodeFixed32(), end_of_buffer_offset_, eof_, file_, initial_offset_, kBadRecord, rocksdb::log::kBlockSize, kEof, rocksdb::log::kHeaderSize, rocksdb::log::kZeroType, rocksdb::Status::ok(), rocksdb::Slice::remove_prefix(), ReportCorruption(), ReportDrop(), rocksdb::Slice::size(), rocksdb::crc32c::Unmask(), and rocksdb::crc32c::Value().
Referenced by ReadRecord().
{
   while (true) {
     if (buffer_.size() < (size_t)kHeaderSize) {
       if (!eof_) {
         // Last read was a full read, so this is a trailer to skip
         buffer_.clear();
         Status status = file_->Read(kBlockSize, &buffer_, backing_store_);
         end_of_buffer_offset_ += buffer_.size();
         if (!status.ok()) {
           buffer_.clear();
           ReportDrop(kBlockSize, status);
           eof_ = true;
           return kEof;
         } else if (buffer_.size() < (size_t)kBlockSize) {
           eof_ = true;
         }
         continue;
       } else if (buffer_.size() == 0) {
         // End of file
         return kEof;
       } else {
         size_t drop_size = buffer_.size();
         buffer_.clear();
         ReportCorruption(drop_size, "truncated record at end of file");
         return kEof;
       }
     }
     // Parse the header
     const char* header = buffer_.data();
     const uint32_t a = static_cast<uint32_t>(header[4]) & 0xff;
     const uint32_t b = static_cast<uint32_t>(header[5]) & 0xff;
     const unsigned int type = header[6];
     const uint32_t length = a | (b << 8);
     if (kHeaderSize + length > buffer_.size()) {
       size_t drop_size = buffer_.size();
       buffer_.clear();
       ReportCorruption(drop_size, "bad record length");
       return kBadRecord;
     }
     if (type == kZeroType && length == 0) {
       // Skip zero length record without reporting any drops since
       // such records are produced by the mmap based writing code in
       // env_posix.cc that preallocates file regions.
       buffer_.clear();
       return kBadRecord;
     }
     // Check crc
     if (checksum_) {
       uint32_t expected_crc = crc32c::Unmask(DecodeFixed32(header));
       uint32_t actual_crc = crc32c::Value(header + 6, 1 + length);
       if (actual_crc != expected_crc) {
         // Drop the rest of the buffer since "length" itself may have
         // been corrupted and if we trust it, we could find some
         // fragment of a real log record that just happens to look
         // like a valid log record.
         size_t drop_size = buffer_.size();
         buffer_.clear();
         ReportCorruption(drop_size, "checksum mismatch");
         return kBadRecord;
       }
     }
     buffer_.remove_prefix(kHeaderSize + length);
     // Skip physical record that started before initial_offset_
     if (end_of_buffer_offset_ - buffer_.size() - kHeaderSize - length <
         initial_offset_) {
       result->clear();
       return kBadRecord;
     }
     *result = Slice(header + kHeaderSize, length);
     return type;
   }
 }
bool rocksdb::log::Reader::ReadRecord (Slice * record, std::string * scratch)
Definition at line 64 of file log_reader.cc.
References buffer_, rocksdb::Slice::clear(), rocksdb::Slice::data(), end_of_buffer_offset_, initial_offset_, kBadRecord, kEof, rocksdb::log::kFirstType, rocksdb::log::kFullType, rocksdb::log::kLastType, rocksdb::log::kMiddleType, last_record_offset_, ReadPhysicalRecord(), ReportCorruption(), rocksdb::Slice::size(), and SkipToInitialBlock().
Referenced by rocksdb::WALDumperCommand::DoCommand(), rocksdb::VersionSet::DumpManifest(), rocksdb::VersionSet::ManifestContains(), rocksdb::log::LogTest::Read(), rocksdb::DBImpl::ReadFirstLine(), rocksdb::VersionSet::Recover(), and rocksdb::DBImpl::RecoverLogFile().
{
   if (last_record_offset_ < initial_offset_) {
     if (!SkipToInitialBlock()) {
       return false;
     }
   }
   scratch->clear();
   record->clear();
   bool in_fragmented_record = false;
   // Record offset of the logical record that we're reading
   // 0 is a dummy value to make compilers happy
   uint64_t prospective_record_offset = 0;
   Slice fragment;
   while (true) {
     uint64_t physical_record_offset = end_of_buffer_offset_ - buffer_.size();
     const unsigned int record_type = ReadPhysicalRecord(&fragment);
     switch (record_type) {
       case kFullType:
         if (in_fragmented_record) {
           // Handle bug in earlier versions of log::Writer where
           // it could emit an empty kFirstType record at the tail end
           // of a block followed by a kFullType or kFirstType record
           // at the beginning of the next block.
           if (scratch->empty()) {
             in_fragmented_record = false;
           } else {
             ReportCorruption(scratch->size(), "partial record without end(1)");
           }
         }
         prospective_record_offset = physical_record_offset;
         scratch->clear();
         *record = fragment;
         last_record_offset_ = prospective_record_offset;
         return true;
       case kFirstType:
         if (in_fragmented_record) {
           // Handle bug in earlier versions of log::Writer where
           // it could emit an empty kFirstType record at the tail end
           // of a block followed by a kFullType or kFirstType record
           // at the beginning of the next block.
           if (scratch->empty()) {
             in_fragmented_record = false;
           } else {
             ReportCorruption(scratch->size(), "partial record without end(2)");
           }
         }
         prospective_record_offset = physical_record_offset;
         scratch->assign(fragment.data(), fragment.size());
         in_fragmented_record = true;
         break;
       case kMiddleType:
         if (!in_fragmented_record) {
           ReportCorruption(fragment.size(),
                            "missing start of fragmented record(1)");
         } else {
           scratch->append(fragment.data(), fragment.size());
         }
         break;
       case kLastType:
         if (!in_fragmented_record) {
           ReportCorruption(fragment.size(),
                            "missing start of fragmented record(2)");
         } else {
           scratch->append(fragment.data(), fragment.size());
           *record = Slice(*scratch);
           last_record_offset_ = prospective_record_offset;
           return true;
         }
         break;
       case kEof:
         if (in_fragmented_record) {
           ReportCorruption(scratch->size(), "partial record without end(3)");
           scratch->clear();
         }
         return false;
       case kBadRecord:
         if (in_fragmented_record) {
           ReportCorruption(scratch->size(), "error in middle of record");
           in_fragmented_record = false;
           scratch->clear();
         }
         break;
       default: {
         char buf[40];
         snprintf(buf, sizeof(buf), "unknown record type %u", record_type);
         ReportCorruption(
             (fragment.size() + (in_fragmented_record ? scratch->size() : 0)),
             buf);
         in_fragmented_record = false;
         scratch->clear();
         break;
       }
     }
   }
   return false;
 }
void rocksdb::log::Reader::ReportCorruption (size_t bytes, const char * reason) private
Definition at line 173 of file log_reader.cc.
References rocksdb::Status::Corruption(), and ReportDrop().
Referenced by ReadPhysicalRecord(), and ReadRecord().
{
   ReportDrop(bytes, Status::Corruption(reason));
 }
void rocksdb::log::Reader::ReportDrop (size_t bytes, const Status & reason) private
Definition at line 177 of file log_reader.cc.
References buffer_, rocksdb::log::Reader::Reporter::Corruption(), end_of_buffer_offset_, initial_offset_, reporter_, and rocksdb::Slice::size().
Referenced by ReadPhysicalRecord(), ReportCorruption(), and SkipToInitialBlock().
{
   if (reporter_ != nullptr &&
       end_of_buffer_offset_ - buffer_.size() - bytes >= initial_offset_) {
     reporter_->Corruption(bytes, reason);
   }
 }
bool rocksdb::log::Reader::SkipToInitialBlock () private
Definition at line 40 of file log_reader.cc.
References end_of_buffer_offset_, file_, initial_offset_, rocksdb::log::kBlockSize, rocksdb::Status::ok(), and ReportDrop().
Referenced by ReadRecord().
{
   size_t offset_in_block = initial_offset_ % kBlockSize;
   uint64_t block_start_location = initial_offset_ - offset_in_block;
   // Don't search a block if we'd be in the trailer
   if (offset_in_block > kBlockSize - 6) {
     offset_in_block = 0;
     block_start_location += kBlockSize;
   }
   end_of_buffer_offset_ = block_start_location;
   // Skip to start of first block that can contain the initial record
   if (block_start_location > 0) {
     Status skip_status = file_->Skip(block_start_location);
     if (!skip_status.ok()) {
       ReportDrop(block_start_location, skip_status);
       return false;
     }
   }
   return true;
 }
void rocksdb::log::Reader::UnmarkEOF () inline
Definition at line 72 of file log_reader.h.
References eof_.
                    {
     eof_ = false;
   }
Member Data Documentation
char* const rocksdb::log::Reader::backing_store_ private
Definition at line 82 of file log_reader.h.
Referenced by ReadPhysicalRecord(), and ~Reader().
Slice rocksdb::log::Reader::buffer_ private
Definition at line 83 of file log_reader.h.
Referenced by ReadPhysicalRecord(), ReadRecord(), and ReportDrop().
bool const rocksdb::log::Reader::checksum_ private
Definition at line 81 of file log_reader.h.
Referenced by ReadPhysicalRecord().
uint64_t rocksdb::log::Reader::end_of_buffer_offset_ private
Definition at line 89 of file log_reader.h.
Referenced by ReadPhysicalRecord(), ReadRecord(), ReportDrop(), and SkipToInitialBlock().
bool rocksdb::log::Reader::eof_ private
Definition at line 84 of file log_reader.h.
Referenced by IsEOF(), ReadPhysicalRecord(), and UnmarkEOF().
const unique_ptr<SequentialFile> rocksdb::log::Reader::file_ private
Definition at line 79 of file log_reader.h.
Referenced by file(), ReadPhysicalRecord(), and SkipToInitialBlock().
uint64_t const rocksdb::log::Reader::initial_offset_ private
Definition at line 92 of file log_reader.h.
Referenced by ReadPhysicalRecord(), ReadRecord(), ReportDrop(), and SkipToInitialBlock().
uint64_t rocksdb::log::Reader::last_record_offset_ private
Definition at line 87 of file log_reader.h.
Referenced by LastRecordOffset(), and ReadRecord().
Reporter* const rocksdb::log::Reader::reporter_ private
Definition at line 80 of file log_reader.h.
Referenced by ReportDrop().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/db/log_reader.h
rippled/src/ripple/rocksdb/rocksdb/db/log_reader.cc