rippled: beast::Journal::Sink Class Reference
beast::Journal::Sink Class Reference abstract
#include <Journal.h>
Public Member Functions
Sink ()
virtual ~Sink ()=0
virtual bool active (Severity level) const
virtual bool console () const
virtual void console (bool output)
virtual Severity severity () const
virtual void severity (Severity level)
virtual void write (Severity level, std::string const &text)=0
Private Attributes
Severity m_level
bool m_console
Detailed Description
Abstraction for the underlying message destination.
Definition at line 59 of file Journal.h.
Constructor & Destructor Documentation
beast::Journal::Sink::Sink ()
Definition at line 69 of file Journal.cpp.
     : m_level (kAll)
     , m_console (false)
 {
 }
beast::Journal::Sink::~Sink () pure virtual
Definition at line 75 of file Journal.cpp.
 {
 }
Member Function Documentation
bool beast::Journal::Sink::active (Severity level) const virtual
Returns true if text at the passed severity produces output.
Reimplemented in ripple::PeerFinder::WrappedSink, and beast::NullJournalSink.
Definition at line 79 of file Journal.cpp.
References beast::Journal::m_level.
Referenced by ripple::PeerFinder::WrappedSink::active(), beast::Journal::Stream::active(), and beast::Journal::active().
 {
     return level >= m_level;
 }
bool beast::Journal::Sink::console () const virtual
Returns true if a message is also written to the Output Window (MSVC).
Reimplemented in ripple::PeerFinder::WrappedSink, and beast::NullJournalSink.
Definition at line 84 of file Journal.cpp.
Referenced by ripple::PeerFinder::WrappedSink::console(), ripple::LogPartition::setConsoleOutput(), and ripple::LogPartition::write().
 {
     return m_console;
 }
void beast::Journal::Sink::console (bool output) virtual
Set whether messages are also written to the Output Window (MSVC).
Reimplemented in ripple::PeerFinder::WrappedSink, and beast::NullJournalSink.
Definition at line 89 of file Journal.cpp.
 {
     m_console = output;
 }
Journal::Severity beast::Journal::Sink::severity () const virtual
Returns the minimum severity level this sink will report.
Reimplemented in beast::NullJournalSink, and ripple::PeerFinder::WrappedSink.
Definition at line 94 of file Journal.cpp.
References beast::Journal::m_level.
Referenced by ripple::LogPartition::getSeverity(), ripple::LogPartition::LogPartition(), ripple::LogPartition::setMinimumSeverity(), and ripple::PeerFinder::WrappedSink::severity().
 {
     return m_level;
 }
void beast::Journal::Sink::severity (Severity level) virtual
Set the minimum severity this sink will report.
Reimplemented in beast::NullJournalSink, and ripple::PeerFinder::WrappedSink.
Definition at line 99 of file Journal.cpp.
References beast::Journal::m_level.
 {
     m_level = level;
 }
virtual void beast::Journal::Sink::write (Severity level, std::string const & text) pure virtual
Write text to the sink at the specified severity. The caller is responsible for checking the minimum severity level before using this function.
Implemented in beast::NullJournalSink, ripple::PeerFinder::WrappedSink, and ripple::LogPartition.
Referenced by ripple::PeerFinder::WrappedSink::write(), and beast::Journal::ScopedStream::~ScopedStream().
Member Data Documentation
bool beast::Journal::Sink::m_console private
Definition at line 89 of file Journal.h.
Severity beast::Journal::Sink::m_level private
Definition at line 88 of file Journal.h.
The documentation for this class was generated from the following files:
rippled/src/beast/beast/utility/Journal.h
rippled/src/beast/beast/utility/impl/Journal.cpp