rippled: ripple::TransactionAcquire Class Reference
ripple::TransactionAcquire Class Reference
#include <TransactionAcquire.h>
Public Types
typedef boost::shared_ptr
< TransactionAcquire > pointer
Public Types inherited from ripple::PeerSet
typedef beast::abstract_clock
< std::chrono::seconds > clock_type
Public Member Functions
TransactionAcquire (uint256 const &hash, clock_type &clock)
~TransactionAcquire ()
SHAMap::ref getMap ()
SHAMapAddNode takeNodes (const std::list< SHAMapNode > &IDs, const std::list< Blob > &data, Peer::ptr const &)
Public Member Functions inherited from ripple::PeerSet
uint256 const & getHash () const
bool isComplete () const
bool isFailed () const
int getTimeouts () const
bool isActive ()
void progress ()
void clearProgress ()
bool isProgress ()
void touch ()
clock_type::time_point getLastAction () const
bool peerHas (Peer::ptr const &)
void peerHasVoid (Peer::ptr const &peer)
void badPeer (Peer::ptr const &)
void setTimer ()
std::size_t takePeerSetFrom (const PeerSet &s)
std::size_t getPeerCount () const
virtual bool isDone () const
Public Member Functions inherited from ripple::CountedObject< TransactionAcquire >
CountedObject ()
CountedObject (CountedObject const &)
~CountedObject ()
Static Public Member Functions
static char const * getCountedObjectName ()
Private Member Functions
void onTimer (bool progress, ScopedLockType &peerSetLock)
void newPeer (Peer::ptr const &peer)
void done ()
void trigger (Peer::ptr const &)
boost::weak_ptr< PeerSet > pmDowncast ()
Private Attributes
SHAMap::pointer mMap
bool mHaveRoot
Additional Inherited Members
Protected Types inherited from ripple::PeerSet
typedef RippleRecursiveMutex LockType
typedef std::unique_lock
< LockType > ScopedLockType
typedef Peer::ShortId PeerIdentifier
typedef int ReceivedChunkCount
typedef ripple::unordered_map
< PeerIdentifier,
ReceivedChunkCount > PeerSetMap
Protected Member Functions inherited from ripple::PeerSet
PeerSet (uint256 const &hash, int interval, bool txnData, clock_type &clock, beast::Journal journal)
virtual ~PeerSet ()=0
void setComplete ()
void setFailed ()
void invokeOnTimer ()
void sendRequest (const protocol::TMGetLedger &message)
void sendRequest (const protocol::TMGetLedger &message, Peer::ptr const &peer)
Protected Attributes inherited from ripple::PeerSet
beast::Journal m_journal
clock_type & m_clock
LockType mLock
uint256 mHash
int mTimerInterval
int mTimeouts
bool mComplete
bool mFailed
bool mAggressive
bool mTxnData
clock_type::time_point mLastAction
bool mProgress
boost::asio::deadline_timer mTimer
PeerSetMap mPeers
Detailed Description
Definition at line 27 of file TransactionAcquire.h.
Member Typedef Documentation
typedef boost::shared_ptr<TransactionAcquire> ripple::TransactionAcquire::pointer
Definition at line 35 of file TransactionAcquire.h.
Constructor & Destructor Documentation
ripple::TransactionAcquire::TransactionAcquire (uint256 const & hash, clock_type & clock)
Definition at line 37 of file TransactionAcquire.cpp.
References ripple::getApp(), hash, mMap, and ripple::smtTRANSACTION.
     : PeerSet (hash, TX_ACQUIRE_TIMEOUT, true, clock,
         LogPartition::getJournal <TransactionAcquire> ())
     , mHaveRoot (false)
 {
     mMap = boost::make_shared<SHAMap> (smtTRANSACTION, hash,
         std::ref (getApp().getFullBelowCache ()));
     mMap->setTXMap ();
 }
ripple::TransactionAcquire::~TransactionAcquire ()
Definition at line 47 of file TransactionAcquire.cpp.
 {
 }
Member Function Documentation
void ripple::TransactionAcquire::done () private
Definition at line 62 of file TransactionAcquire.cpp.
References ripple::JobQueue::addJob(), BIND_TYPE, ripple::getApp(), ripple::Application::getJobQueue(), ripple::jtTXN_DATA, ripple::lsINFO, ripple::lsWARNING, ripple::PeerSet::mFailed, ripple::PeerSet::mHash, mMap, ripple::TACompletionHandler(), and WriteLog.
Referenced by onTimer(), and trigger().
 {
     // We hold a PeerSet lock and so cannot acquire the master lock here
     SHAMap::pointer map;
     if (mFailed)
     {
         WriteLog (lsWARNING, TransactionAcquire) << "Failed to acquire TX set " << mHash;
     }
     else
     {
         WriteLog (lsINFO, TransactionAcquire) << "Acquired TX set " << mHash;
         mMap->setImmutable ();
         map = mMap;
     }
     getApp().getJobQueue().addJob (jtTXN_DATA, "completeAcquire", BIND_TYPE (&TACompletionHandler, mHash, map));
 }
static char const* ripple::TransactionAcquire::getCountedObjectName () inline static
Definition at line 33 of file TransactionAcquire.h.
 { return "TransactionAcquire"; }
SHAMap::ref ripple::TransactionAcquire::getMap () inline
Definition at line 41 of file TransactionAcquire.h.
References mMap.
     {
         return mMap;
     }
void ripple::TransactionAcquire::newPeer (Peer::ptr const & peer) inline private virtual
Implements ripple::PeerSet.
Definition at line 54 of file TransactionAcquire.h.
References trigger().
     {
         trigger (peer);
     }
void ripple::TransactionAcquire::onTimer (bool progress, ScopedLockType & peerSetLock) private virtual
Implements ripple::PeerSet.
Definition at line 81 of file TransactionAcquire.cpp.
References done(), ripple::Overlay::getActivePeers(), ripple::getApp(), ripple::PeerSet::getHash(), ripple::PeerSet::getPeerCount(), ripple::PeerSet::getTimeouts(), ripple::lsWARNING, ripple::PeerSet::mFailed, ripple::PeerSet::mHash, ripple::PeerSet::mTimeouts, ripple::Application::overlay(), ripple::PeerSet::peerHas(), trigger(), and WriteLog.
 {
     bool aggressive = false;
     if (getTimeouts () > 10)
     {
         WriteLog (lsWARNING, TransactionAcquire) << "Ten timeouts on TX set " << getHash ();
         psl.unlock();
         {
             Application::ScopedLockType lock (getApp().getMasterLock ());
             if (getApp().getOPs ().stillNeedTXSet (mHash))
             {
                 WriteLog (lsWARNING, TransactionAcquire) << "Still need it";
                 mTimeouts = 0;
                 aggressive = true;
             }
         }
         psl.lock();
         if (!aggressive)
         {
             mFailed = true;
             done ();
             return;
         }
     }
     if (aggressive || !getPeerCount ())
     {
         // out of peers
         WriteLog (lsWARNING, TransactionAcquire) << "Out of peers for TX set " << getHash ();
         bool found = false;
         Overlay::PeerSequence peerList = getApp().overlay ().getActivePeers ();
         BOOST_FOREACH (Peer::ptr const& peer, peerList)
         {
             if (peer->hasTxSet (getHash ()))
             {
                 found = true;
                 peerHas (peer);
             }
         }
         if (!found)
         {
             BOOST_FOREACH (Peer::ptr const& peer, peerList)
             peerHas (peer);
         }
     }
     else if (!progress)
         trigger (Peer::ptr ());
 }
boost::weak_ptr< PeerSet > ripple::TransactionAcquire::pmDowncast () private virtual
Implements ripple::PeerSet.
Definition at line 135 of file TransactionAcquire.cpp.
 {
     return boost::dynamic_pointer_cast<PeerSet> (shared_from_this ());
 }
SHAMapAddNode ripple::TransactionAcquire::takeNodes (const std::list< SHAMapNode > & IDs, const std::list< Blob > & data, Peer::ptr const & peer)
Definition at line 200 of file TransactionAcquire.cpp.
References ripple::getApp(), ripple::PeerSet::getHash(), ripple::SHAMapAddNode::invalid(), ripple::lsDEBUG, ripple::lsERROR, ripple::lsTRACE, ripple::lsWARNING, ripple::PeerSet::mComplete, ripple::PeerSet::mFailed, mHaveRoot, mMap, ripple::PeerSet::progress(), ripple::snfWIRE, trigger(), ripple::SHAMapAddNode::useful(), and WriteLog.
 {
     if (mComplete)
     {
         WriteLog (lsTRACE, TransactionAcquire) << "TX set complete";
         return SHAMapAddNode ();
     }
     if (mFailed)
     {
         WriteLog (lsTRACE, TransactionAcquire) << "TX set failed";
         return SHAMapAddNode ();
     }
     try
     {
         if (nodeIDs.empty ())
             return SHAMapAddNode::invalid ();
         std::list<SHAMapNode>::const_iterator nodeIDit = nodeIDs.begin ();
         std::list< Blob >::const_iterator nodeDatait = data.begin ();
         ConsensusTransSetSF sf (getApp().getTempNodeCache ());
         while (nodeIDit != nodeIDs.end ())
         {
             if (nodeIDit->isRoot ())
             {
                 if (mHaveRoot)
                     WriteLog (lsDEBUG, TransactionAcquire) << "Got root TXS node, already have it";
                 else if (!mMap->addRootNode (getHash (), *nodeDatait, snfWIRE, nullptr).isGood())
                 {
                     WriteLog (lsWARNING, TransactionAcquire) << "TX acquire got bad root node";
                 }
                 else
                     mHaveRoot = true;
             }
             else if (!mMap->addKnownNode (*nodeIDit, *nodeDatait, &sf).isGood())
             {
                 WriteLog (lsWARNING, TransactionAcquire) << "TX acquire got bad non-root node";
                 return SHAMapAddNode::invalid ();
             }
             ++nodeIDit;
             ++nodeDatait;
         }
         trigger (peer);
         progress ();
         return SHAMapAddNode::useful ();
     }
     catch (...)
     {
         WriteLog (lsERROR, TransactionAcquire) << "Peer sends us junky transaction node data";
         return SHAMapAddNode::invalid ();
     }
 }
void ripple::TransactionAcquire::trigger (Peer::ptr const & peer) private
Definition at line 140 of file TransactionAcquire.cpp.
References ripple::base_uint< BITS >::begin(), done(), ripple::getApp(), ripple::SHAMapNode::getRawString(), ripple::PeerSet::getTimeouts(), ripple::lsINFO, ripple::lsTRACE, ripple::PeerSet::mComplete, ripple::PeerSet::mFailed, ripple::PeerSet::mHash, mHaveRoot, mMap, ripple::PeerSet::sendRequest(), ripple::base_uint< BITS >::size(), and WriteLog.
Referenced by newPeer(), onTimer(), and takeNodes().
 {
     if (mComplete)
     {
         WriteLog (lsINFO, TransactionAcquire) << "trigger after complete";
         return;
     }
     if (mFailed)
     {
         WriteLog (lsINFO, TransactionAcquire) << "trigger after fail";
         return;
     }
     if (!mHaveRoot)
     {
         WriteLog (lsTRACE, TransactionAcquire) << "TransactionAcquire::trigger " << (peer ? "havePeer" : "noPeer") << " no root";
         protocol::TMGetLedger tmGL;
         tmGL.set_ledgerhash (mHash.begin (), mHash.size ());
         tmGL.set_itype (protocol::liTS_CANDIDATE);
         if (getTimeouts () != 0)
             tmGL.set_querytype (protocol::qtINDIRECT);
         * (tmGL.add_nodeids ()) = SHAMapNode ().getRawString ();
         sendRequest (tmGL, peer);
     }
     else
     {
         std::vector<SHAMapNode> nodeIDs;
         std::vector<uint256> nodeHashes;
         // VFALCO TODO Use a dependency injection on the temp node cache
         ConsensusTransSetSF sf (getApp().getTempNodeCache ());
         mMap->getMissingNodes (nodeIDs, nodeHashes, 256, &sf);
         if (nodeIDs.empty ())
         {
             if (mMap->isValid ())
                 mComplete = true;
             else
                 mFailed = true;
             done ();
             return;
         }
         protocol::TMGetLedger tmGL;
         tmGL.set_ledgerhash (mHash.begin (), mHash.size ());
         tmGL.set_itype (protocol::liTS_CANDIDATE);
         if (getTimeouts () != 0)
             tmGL.set_querytype (protocol::qtINDIRECT);
         BOOST_FOREACH (SHAMapNode & it, nodeIDs)
         {
             * (tmGL.add_nodeids ()) = it.getRawString ();
         }
         sendRequest (tmGL, peer);
     }
 }
Member Data Documentation
bool ripple::TransactionAcquire::mHaveRoot private
Definition at line 51 of file TransactionAcquire.h.
Referenced by takeNodes(), and trigger().
SHAMap::pointer ripple::TransactionAcquire::mMap private
Definition at line 50 of file TransactionAcquire.h.
Referenced by done(), getMap(), takeNodes(), TransactionAcquire(), and trigger().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/tx/TransactionAcquire.h
rippled/src/ripple_app/tx/TransactionAcquire.cpp