rippled: beast::ServiceQueueBase Class Reference
beast::ServiceQueueBase Class Reference abstract
#include <ServiceQueue.h>
Classes
class Item
class ScopedServiceThread
struct State
class Waiter
Public Member Functions
ServiceQueueBase ()
~ServiceQueueBase ()
std::size_t poll ()
std::size_t poll_one ()
std::size_t run ()
std::size_t run_one ()
void stop ()
bool stopped () const
void reset ()
Protected Types
typedef SharedData< State > SharedState
Protected Member Functions
void wait ()
virtual void enqueue (Item *item)
bool empty ()
virtual std::size_t dequeue ()=0
virtual Waiter * new_waiter ()=0
Protected Attributes
SharedState m_state
Atomic< int > m_stopped
Static Protected Attributes
static ThreadLocalValue
< ServiceQueueBase * > s_service
Detailed Description
Definition at line 333 of file ServiceQueue.h.
Member Typedef Documentation
typedef SharedData<State> beast::ServiceQueueBase::SharedState protected
Definition at line 395 of file ServiceQueue.h.
Constructor & Destructor Documentation
beast::ServiceQueueBase::ServiceQueueBase ()
Definition at line 44 of file ServiceQueue.cpp.
 {
 }
beast::ServiceQueueBase::~ServiceQueueBase ()
Definition at line 48 of file ServiceQueue.cpp.
 {
 }
Member Function Documentation
virtual std::size_t beast::ServiceQueueBase::dequeue () protected pure virtual
Implemented in beast::ServiceQueueType< Allocator >.
Referenced by poll(), and poll_one().
bool beast::ServiceQueueBase::empty () protected
Definition at line 174 of file ServiceQueue.cpp.
References m_state.
 {
     SharedState::Access state (m_state);
     return state->handlers.empty();
 }
void beast::ServiceQueueBase::enqueue (Item * item) protected virtual
Definition at line 156 of file ServiceQueue.cpp.
References m_state, and beast::ServiceQueueBase::Waiter::signal().
Referenced by beast::ServiceQueueType< Allocator >::dispatch(), and beast::ServiceQueueType< Allocator >::post().
 {
     Waiter* waiter (nullptr);
     {
         SharedState::Access state (m_state);
         state->handlers.push_back (*item);
         if (! state->waiting.empty ())
         {
             waiter = &state->waiting.front ();
             state->waiting.pop_front ();
         }
     }
     if (waiter != nullptr)
         waiter->signal();
 }
virtual Waiter* beast::ServiceQueueBase::new_waiter () protected pure virtual
Implemented in beast::ServiceQueueType< Allocator >.
Referenced by wait().
std::size_t beast::ServiceQueueBase::poll ()
Definition at line 52 of file ServiceQueue.cpp.
References dequeue().
Referenced by beast::ServiceQueueType< Allocator >::poll(), and run().
 {
     std::size_t total (0);
     ScopedServiceThread thread (this);
     for (;;)
     {
         std::size_t const n (dequeue());
         if (! n)
             break;
         total += n;
     }
     return total;
 }
std::size_t beast::ServiceQueueBase::poll_one ()
Definition at line 66 of file ServiceQueue.cpp.
References dequeue().
Referenced by beast::ServiceQueueType< Allocator >::poll_one(), and run_one().
 {
     ScopedServiceThread thread (this);
     return dequeue();
 }
void beast::ServiceQueueBase::reset ()
Definition at line 110 of file ServiceQueue.cpp.
References bassert, beast::Atomic< Type >::get(), m_stopped, and beast::Atomic< Type >::set().
Referenced by beast::ServiceQueueType< Allocator >::reset().
 {
     // Must be stopped
     bassert (m_stopped.get () != 0);
     m_stopped.set (0);
 }
std::size_t beast::ServiceQueueBase::run ()
Definition at line 72 of file ServiceQueue.cpp.
References poll(), stopped(), and wait().
Referenced by beast::ServiceQueueType< Allocator >::run().
 {
     std::size_t total (0);
     ScopedServiceThread thread (this);
     while (! stopped())
     {
         total += poll ();
         wait ();
     }
     return total;
 }
std::size_t beast::ServiceQueueBase::run_one ()
Definition at line 84 of file ServiceQueue.cpp.
References poll_one(), and wait().
Referenced by beast::ServiceQueueType< Allocator >::run_one().
 {
     std::size_t n;
     ScopedServiceThread (this);
     for (;;)
     {
         n = poll_one();
         if (n != 0)
             break;
         wait();
     }
     return n;
 }
void beast::ServiceQueueBase::stop ()
Definition at line 98 of file ServiceQueue.cpp.
References m_state, m_stopped, beast::Atomic< Type >::set(), and beast::ServiceQueueBase::Waiter::signal().
Referenced by beast::ServiceQueueType< Allocator >::stop().
 {
     SharedState::Access state (m_state);
     m_stopped.set (1);
     while (! state->waiting.empty ())
     {
         Waiter& waiting (state->waiting.front());
         state->waiting.pop_front ();
         waiting.signal ();
     }
 }
bool beast::ServiceQueueBase::stopped () const inline
Definition at line 344 of file ServiceQueue.h.
References beast::Atomic< Type >::get(), and m_stopped.
Referenced by run(), beast::ServiceQueueType< Allocator >::stopped(), and wait().
         { return m_stopped.get() != 0; }
void beast::ServiceQueueBase::wait () protected
Definition at line 120 of file ServiceQueue.cpp.
References m_state, new_waiter(), stopped(), and beast::ServiceQueueBase::Waiter::wait().
Referenced by run(), and run_one().
 {
     Waiter* waiter (nullptr);
     {
         SharedState::Access state (m_state);
         if (stopped ())
             return;
         if (! state->handlers.empty())
             return;
         if (state->unused.empty ())
         {
             waiter = new_waiter();
         }
         else
         {
             waiter = &state->unused.front ();
             state->unused.pop_front ();
         }
         state->waiting.push_front (*waiter);
     }
     waiter->wait();
     // Waiter got taken off the waiting list
     {
         SharedState::Access state (m_state);
         state->unused.push_front (*waiter);
     }
 }
Member Data Documentation
SharedState beast::ServiceQueueBase::m_state protected
Definition at line 396 of file ServiceQueue.h.
Referenced by beast::ServiceQueueType< Allocator >::dequeue(), empty(), enqueue(), beast::ServiceQueueType< Allocator >::ServiceQueueType(), stop(), wait(), and beast::ServiceQueueType< Allocator >::~ServiceQueueType().
Atomic<int> beast::ServiceQueueBase::m_stopped protected
Definition at line 397 of file ServiceQueue.h.
Referenced by reset(), stop(), and stopped().
ThreadLocalValue< ServiceQueueBase * > beast::ServiceQueueBase::s_service static protected
Definition at line 399 of file ServiceQueue.h.
Referenced by beast::ServiceQueueType< Allocator >::is_service_thread(), beast::ServiceQueueBase::ScopedServiceThread::ScopedServiceThread(), and beast::ServiceQueueBase::ScopedServiceThread::~ScopedServiceThread().
The documentation for this class was generated from the following files:
rippled/src/beast/beast/threads/ServiceQueue.h
rippled/src/beast/beast/threads/impl/ServiceQueue.cpp