rippled: rocksdb::DB Class Reference
rocksdb::DB Class Reference abstract
#include <db.h>
Public Member Functions
DB ()
virtual ~DB ()
virtual Status Put (const WriteOptions &options, const Slice &key, const Slice &value)=0
virtual Status Delete (const WriteOptions &options, const Slice &key)=0
virtual Status Merge (const WriteOptions &options, const Slice &key, const Slice &value)=0
virtual Status Write (const WriteOptions &options, WriteBatch *updates)=0
virtual Status Get (const ReadOptions &options, const Slice &key, std::string *value)=0
virtual std::vector< Status > MultiGet (const ReadOptions &options, const std::vector< Slice > &keys, std::vector< std::string > *values)=0
virtual bool KeyMayExist (const ReadOptions &options, const Slice &key, std::string *value, bool *value_found=nullptr)
virtual Iterator * NewIterator (const ReadOptions &options)=0
virtual const Snapshot * GetSnapshot ()=0
virtual void ReleaseSnapshot (const Snapshot *snapshot)=0
virtual bool GetProperty (const Slice &property, std::string *value)=0
virtual void GetApproximateSizes (const Range *range, int n, uint64_t *sizes)=0
virtual void CompactRange (const Slice *begin, const Slice *end, bool reduce_level=false, int target_level=-1)=0
virtual int NumberLevels ()=0
virtual int MaxMemCompactionLevel ()=0
virtual int Level0StopWriteTrigger ()=0
virtual Status Flush (const FlushOptions &options)=0
virtual Status DisableFileDeletions ()=0
virtual Status EnableFileDeletions ()=0
virtual Status GetLiveFiles (std::vector< std::string > &, uint64_t *manifest_file_size, bool flush_memtable=true)=0
virtual Status GetSortedWalFiles (VectorLogPtr &files)=0
virtual SequenceNumber GetLatestSequenceNumber () const =0
virtual Status GetUpdatesSince (SequenceNumber seq_number, unique_ptr< TransactionLogIterator > *iter)=0
virtual Status DeleteFile (std::string name)=0
virtual void GetLiveFilesMetaData (std::vector< LiveFileMetaData > *metadata)
Static Public Member Functions
static Status Open (const Options &options, const std::string &name, DB **dbptr)
static Status OpenForReadOnly (const Options &options, const std::string &name, DB **dbptr, bool error_if_log_file_exist=false)
Private Member Functions
DB (const DB &)
void operator= (const DB &)
Detailed Description
Definition at line 66 of file db.h.
Constructor & Destructor Documentation
rocksdb::DB::DB () inline
Definition at line 85 of file db.h.
 { }
rocksdb::DB::~DB () virtual
Definition at line 3450 of file db_impl.cc.
 { }
rocksdb::DB::DB (const DB &) private
Member Function Documentation
virtual void rocksdb::DB::CompactRange (const Slice * begin, const Slice * end, bool reduce_level = false, int target_level = -1) pure virtual
Implemented in rocksdb::ModelDB, rocksdb::StackableDB, rocksdb::DBImpl, rocksdb::DBWithTTL, and rocksdb::DBImplReadOnly.
Referenced by rocksdb::DBTest::Compact(), rocksdb::Benchmark::Compact(), rocksdb::DBWithTTL::CompactRange(), rocksdb::CompactorCommand::DoCommand(), rocksdb::DBLoaderCommand::DoCommand(), rocksdb::ReduceDBLevelsCommand::DoCommand(), rocksdb::ChangeCompactionStyleCommand::DoCommand(), leveldb_compact_range(), rocksdb::TEST(), and testCounters().
Status rocksdb::DB::Delete (const WriteOptions & options, const Slice & key) pure virtual
Implemented in rocksdb::ModelDB, rocksdb::StackableDB, rocksdb::DBImplReadOnly, rocksdb::DBImpl, and rocksdb::DBWithTTL.
Definition at line 3437 of file db_impl.cc.
References rocksdb::WriteBatch::Delete(), and Write().
Referenced by rocksdb::DBWithTTL::Delete(), rocksdb::DBImpl::Delete(), rocksdb::DBTest::Delete(), rocksdb::SimpleTableDBTest::Delete(), rocksdb::ModelDB::Delete(), leveldb_delete(), and rocksdb::StressTest::OperateDb().
{
   WriteBatch batch;
   batch.Delete(key);
   return Write(opt, &batch);
 }
virtual Status rocksdb::DB::DeleteFile (std::string name) pure virtual
Implemented in rocksdb::ModelDB, rocksdb::StackableDB, rocksdb::DBImpl, and rocksdb::DBWithTTL.
Referenced by rocksdb::DBWithTTL::DeleteFile().
virtual Status rocksdb::DB::DisableFileDeletions () pure virtual
Implemented in rocksdb::ModelDB, rocksdb::StackableDB, rocksdb::DBWithTTL, rocksdb::DBImpl, and rocksdb::DBImplReadOnly.
Referenced by rocksdb::DBWithTTL::DisableFileDeletions(), and rocksdb::TEST().
virtual Status rocksdb::DB::EnableFileDeletions () pure virtual
Implemented in rocksdb::ModelDB, rocksdb::StackableDB, rocksdb::DBWithTTL, rocksdb::DBImpl, and rocksdb::DBImplReadOnly.
Referenced by rocksdb::DBWithTTL::EnableFileDeletions().
virtual Status rocksdb::DB::Flush (const FlushOptions & options) pure virtual
Implemented in rocksdb::ModelDB, rocksdb::StackableDB, rocksdb::DBImpl, rocksdb::DBWithTTL, and rocksdb::DBImplReadOnly.
Referenced by rocksdb::DBWithTTL::Flush(), rocksdb::TableReaderBenchmark(), and testCounters().
virtual Status rocksdb::DB::Get (const ReadOptions & options, const Slice & key, std::string * value) pure virtual
Implemented in rocksdb::ModelDB, rocksdb::StackableDB, rocksdb::DBImpl, rocksdb::DBImplReadOnly, and rocksdb::DBWithTTL.
Referenced by rocksdb::Benchmark::AppendRandom(), rocksdb::GetCommand::DoCommand(), rocksdb::DBWithTTL::Get(), rocksdb::ReduceLevelTest::Get(), rocksdb::DBTest::Get(), rocksdb::SimpleTableDBTest::Get(), rocksdb::Benchmark::GetMany(), leveldb_get(), rocksdb::StressTest::MultiGet(), rocksdb::StressTest::OperateDb(), rocksdb::Benchmark::ReadHot(), rocksdb::Benchmark::ReadMissing(), rocksdb::Benchmark::ReadRandom(), rocksdb::Benchmark::ReadRandomWriteRandom(), rocksdb::TableReaderBenchmark(), rocksdb::TEST(), rocksdb::Benchmark::UpdateRandom(), and rocksdb::StressTest::VerifyDb().
virtual void rocksdb::DB::GetApproximateSizes (const Range * range, int n, uint64_t * sizes) pure virtual
Implemented in rocksdb::ModelDB, rocksdb::StackableDB, rocksdb::DBImpl, and rocksdb::DBWithTTL.
Referenced by rocksdb::Benchmark::AppendRandom(), rocksdb::DBWithTTL::GetApproximateSizes(), leveldb_approximate_sizes(), rocksdb::Benchmark::ReadRandom(), rocksdb::Benchmark::ReadRandomWriteRandom(), rocksdb::DBTest::Size(), and rocksdb::Benchmark::UpdateRandom().
virtual SequenceNumber rocksdb::DB::GetLatestSequenceNumber () const pure virtual
Implemented in rocksdb::ModelDB, rocksdb::StackableDB, rocksdb::DBWithTTL, and rocksdb::DBImpl.
Referenced by rocksdb::DBWithTTL::GetLatestSequenceNumber().
virtual Status rocksdb::DB::GetLiveFiles (std::vector< std::string > & , uint64_t * manifest_file_size, bool flush_memtable = true) pure virtual
Implemented in rocksdb::ModelDB, rocksdb::StackableDB, rocksdb::DBWithTTL, rocksdb::DBImpl, and rocksdb::DBImplReadOnly.
Referenced by rocksdb::DBTest::CountLiveFiles(), and rocksdb::DBWithTTL::GetLiveFiles().
virtual void rocksdb::DB::GetLiveFilesMetaData (std::vector< LiveFileMetaData > * metadata) inline virtual
Reimplemented in rocksdb::DBImpl.
Definition at line 285 of file db.h.
{
   }
virtual bool rocksdb::DB::GetProperty (const Slice & property, std::string * value) pure virtual
Implemented in rocksdb::ModelDB, rocksdb::StackableDB, rocksdb::DBImpl, and rocksdb::DBWithTTL.
Referenced by rocksdb::DBDumperCommand::DoCommand(), rocksdb::InternalDumpCommand::DoCommand(), rocksdb::ChangeCompactionStyleCommand::DoCommand(), rocksdb::DBTest::DumpSSTableList(), rocksdb::ReduceLevelTest::FilesOnLevel(), rocksdb::Stats::FinishedSingleOp(), rocksdb::DBWithTTL::GetProperty(), leveldb_property_value(), rocksdb::DBTest::NumTableFilesAtLevel(), rocksdb::SimpleTableDBTest::NumTableFilesAtLevel(), rocksdb::Benchmark::PrintStats(), and rocksdb::CorruptionTest::Property().
virtual const Snapshot* rocksdb::DB::GetSnapshot () pure virtual
Implemented in rocksdb::ModelDB, rocksdb::StackableDB, rocksdb::DBImpl, and rocksdb::DBWithTTL.
Referenced by rocksdb::Benchmark::AppendRandom(), rocksdb::Benchmark::GetMany(), rocksdb::DBWithTTL::GetSnapshot(), leveldb_create_snapshot(), rocksdb::StressTest::MultiGet(), rocksdb::Benchmark::MultiGetRandom(), rocksdb::StressTest::MultiIterate(), rocksdb::StressTest::MultiPrefixScan(), rocksdb::Benchmark::ReadRandom(), rocksdb::Benchmark::ReadRandomWriteRandom(), and rocksdb::Benchmark::UpdateRandom().
virtual Status rocksdb::DB::GetSortedWalFiles (VectorLogPtr & files) pure virtual
Implemented in rocksdb::ModelDB, rocksdb::StackableDB, rocksdb::DBWithTTL, and rocksdb::DBImpl.
Referenced by rocksdb::DBWithTTL::GetSortedWalFiles().
virtual Status rocksdb::DB::GetUpdatesSince (SequenceNumber seq_number, unique_ptr< TransactionLogIterator > * iter) pure virtual
Implemented in rocksdb::ModelDB, rocksdb::StackableDB, rocksdb::DBWithTTL, and rocksdb::DBImpl.
Referenced by rocksdb::DBWithTTL::GetUpdatesSince(), and ReplicationThreadBody().
virtual bool rocksdb::DB::KeyMayExist (const ReadOptions & options, const Slice & key, std::string * value, bool * value_found = nullptr) inline virtual
Reimplemented in rocksdb::ModelDB, rocksdb::StackableDB, rocksdb::DBImpl, and rocksdb::DBWithTTL.
Definition at line 146 of file db.h.
References value_found.
Referenced by rocksdb::DBWithTTL::KeyMayExist().
{
     if (value_found != nullptr) {
       *value_found = false;
     }
     return true;
   }
virtual int rocksdb::DB::Level0StopWriteTrigger () pure virtual
Implemented in rocksdb::ModelDB, rocksdb::StackableDB, rocksdb::DBImpl, and rocksdb::DBWithTTL.
Referenced by rocksdb::DBWithTTL::Level0StopWriteTrigger().
virtual int rocksdb::DB::MaxMemCompactionLevel () pure virtual
Implemented in rocksdb::ModelDB, rocksdb::StackableDB, rocksdb::DBImpl, and rocksdb::DBWithTTL.
Referenced by rocksdb::DBWithTTL::MaxMemCompactionLevel().
Status rocksdb::DB::Merge (const WriteOptions & options, const Slice & key, const Slice & value) pure virtual
Implemented in rocksdb::ModelDB, rocksdb::StackableDB, rocksdb::DBWithTTL, rocksdb::DBImplReadOnly, and rocksdb::DBImpl.
Definition at line 3443 of file db_impl.cc.
References rocksdb::WriteBatch::Merge(), and Write().
Referenced by rocksdb::DBImpl::Merge(), rocksdb::ModelDB::Merge(), rocksdb::Benchmark::MergeRandom(), rocksdb::StressTest::OperateDb(), and rocksdb::DBTest::Put().
{
   WriteBatch batch;
   batch.Merge(key, value);
   return Write(opt, &batch);
 }
virtual std::vector<Status> rocksdb::DB::MultiGet (const ReadOptions & options, const std::vector< Slice > & keys, std::vector< std::string > * values) pure virtual
Implemented in rocksdb::ModelDB, rocksdb::StackableDB, rocksdb::DBImpl, and rocksdb::DBWithTTL.
Referenced by rocksdb::Benchmark::MultiGetRandom().
virtual Iterator* rocksdb::DB::NewIterator (const ReadOptions & options) pure virtual
Implemented in rocksdb::ModelDB, rocksdb::StackableDB, rocksdb::DBImpl, rocksdb::DBWithTTL, and rocksdb::DBImplReadOnly.
Referenced by rocksdb::CorruptionTest::Check(), rocksdb::CompareIterators(), rocksdb::DBTest::Contents(), rocksdb::DBDumperCommand::DoCommand(), rocksdb::ScanCommand::DoCommand(), dumpDb(), leveldb_create_iterator(), rocksdb::StressTest::MultiIterate(), rocksdb::StressTest::MultiPrefixScan(), rocksdb::DBWithTTL::NewIterator(), rocksdb::DBConstructor::NewIterator(), rocksdb::StressTest::OperateDb(), rocksdb::Benchmark::PrefixScanRandom(), rocksdb::Benchmark::ReadRandom(), rocksdb::Benchmark::ReadReverse(), rocksdb::Benchmark::ReadSequential(), rocksdb::Benchmark::SeekRandom(), rocksdb::TableReaderBenchmark(), rocksdb::TEST(), rocksdb::StressTest::VerifyDb(), and rocksdb::DBTest::VerifyIterLast().
virtual int rocksdb::DB::NumberLevels () pure virtual
Implemented in rocksdb::ModelDB, rocksdb::StackableDB, rocksdb::DBImpl, and rocksdb::DBWithTTL.
Referenced by rocksdb::ChangeCompactionStyleCommand::DoCommand(), rocksdb::DBTest::DumpFileCounts(), rocksdb::DBTest::FilesPerLevel(), rocksdb::SimpleTableDBTest::FilesPerLevel(), rocksdb::DBTest::FillLevels(), rocksdb::DBWithTTL::NumberLevels(), and rocksdb::DBTest::TotalTableFiles().
Status rocksdb::DB::Open (const Options & options, const std::string & name, DB ** dbptr) static
Definition at line 3452 of file db_impl.cc.
References rocksdb::Options::block_cache, rocksdb::Options::compaction_style, rocksdb::DBImpl::CreateArchivalDirectory(), rocksdb::Env::CreateDirIfMissing(), rocksdb::DBImpl::DeleteObsoleteFiles(), rocksdb::Options::env, rocksdb::DBImpl::env_, rocksdb::Status::InvalidArgument(), rocksdb::kCompactionStyleUniversal, rocksdb::port::Mutex::Lock(), rocksdb::DBImpl::log_, rocksdb::DBImpl::logfile_number_, rocksdb::LogFileName(), rocksdb::DBImpl::MaybeScheduleFlushOrCompaction(), rocksdb::DBImpl::MaybeScheduleLogDBDeployStats(), rocksdb::DBImpl::mem_, rocksdb::DBImpl::mutex_, rocksdb::Env::NewWritableFile(), rocksdb::Options::no_block_cache, rocksdb::DBImpl::NumberLevels(), rocksdb::Status::ok(), rocksdb::DBImpl::options_, rocksdb::DBImpl::Recover(), rocksdb::MemTable::SetLogNumber(), rocksdb::port::Mutex::Unlock(), rocksdb::EnvOptions::use_mmap_writes, rocksdb::DBImpl::versions_, rocksdb::Options::wal_dir, and rocksdb::Options::write_buffer_size.
Referenced by rocksdb::BM_LogAndApply(), rocksdb::DBWithTTL::DBWithTTL(), main(), rocksdb::DBConstructor::NewDB(), rocksdb::Benchmark::Open(), rocksdb::StressTest::Open(), rocksdb::ReduceLevelTest::OpenDB(), rocksdb::OpenDb(), rocksdb::PrefixTest::OpenDb(), rocksdb::LDBCommand::OpenDB(), rocksdb::OpenNormalDb(), rocksdb::DBTest::PureReopen(), rocksdb::SimpleTableDBTest::PureReopen(), rocksdb::RedisLists::RedisLists(), rocksdb::DeleteFileTest::ReopenDB(), rocksdb::TableReaderBenchmark(), rocksdb::TEST(), rocksdb::CorruptionTest::TryReopen(), rocksdb::DBTest::TryReopen(), and rocksdb::SimpleTableDBTest::TryReopen().
{
   *dbptr = nullptr;
   EnvOptions soptions;
   if (options.block_cache != nullptr && options.no_block_cache) {
     return Status::InvalidArgument(
         "no_block_cache is true while block_cache is not nullptr");
   }
   DBImpl* impl = new DBImpl(options, dbname);
   Status s = impl->env_->CreateDirIfMissing(impl->options_.wal_dir);
   if (!s.ok()) {
     delete impl;
     return s;
   }
   s = impl->CreateArchivalDirectory();
   if (!s.ok()) {
     delete impl;
     return s;
   }
   impl->mutex_.Lock();
   VersionEdit edit(impl->NumberLevels());
   s = impl->Recover(&edit); // Handles create_if_missing, error_if_exists
   if (s.ok()) {
     uint64_t new_log_number = impl->versions_->NewFileNumber();
     unique_ptr<WritableFile> lfile;
     soptions.use_mmap_writes = false;
     s = options.env->NewWritableFile(
       LogFileName(impl->options_.wal_dir, new_log_number),
       &lfile,
       soptions
     );
     if (s.ok()) {
       lfile->SetPreallocationBlockSize(1.1 * options.write_buffer_size);
       edit.SetLogNumber(new_log_number);
       impl->logfile_number_ = new_log_number;
       impl->log_.reset(new log::Writer(std::move(lfile)));
       s = impl->versions_->LogAndApply(&edit, &impl->mutex_);
     }
     if (s.ok()) {
       impl->mem_->SetLogNumber(impl->logfile_number_);
       impl->DeleteObsoleteFiles();
       impl->MaybeScheduleFlushOrCompaction();
       impl->MaybeScheduleLogDBDeployStats();
     }
   }
   impl->mutex_.Unlock();
   if (options.compaction_style == kCompactionStyleUniversal) {
     int num_files;
     for (int i = 1; i < impl->NumberLevels(); i++) {
       num_files = impl->versions_->NumLevelFiles(i);
       if (num_files > 0) {
         s = Status::InvalidArgument("Not all files are at level 0. Cannot "
           "open with universal compaction style.");
         break;
       }
     }
   }
   if (s.ok()) {
     *dbptr = impl;
   } else {
     delete impl;
   }
   return s;
 }
Status rocksdb::DB::OpenForReadOnly (const Options & options, const std::string & name, DB ** dbptr, bool error_if_log_file_exist = false) static
Definition at line 81 of file db_impl_readonly.cc.
References rocksdb::DBImpl::GetMemTable(), and rocksdb::DBImpl::NumberLevels().
Referenced by rocksdb::DBWithTTL::DBWithTTL(), rocksdb::Benchmark::Open(), and rocksdb::LDBCommand::OpenDB().
{
   *dbptr = nullptr;
   DBImplReadOnly* impl = new DBImplReadOnly(options, dbname);
   impl->mutex_.Lock();
   VersionEdit edit(impl->NumberLevels());
   Status s = impl->Recover(&edit, impl->GetMemTable(),
                            error_if_log_file_exist);
   impl->mutex_.Unlock();
   if (s.ok()) {
     *dbptr = impl;
   } else {
     delete impl;
   }
   return s;
 }
void rocksdb::DB::operator= (const DB &) private
Status rocksdb::DB::Put (const WriteOptions & options, const Slice & key, const Slice & value) pure virtual
Implemented in rocksdb::ModelDB, rocksdb::DBImpl, rocksdb::StackableDB, rocksdb::DBImplReadOnly, and rocksdb::DBWithTTL.
Definition at line 3431 of file db_impl.cc.
References rocksdb::WriteBatch::Put(), and Write().
Referenced by rocksdb::DeleteFileTest::AddKeys(), rocksdb::Benchmark::AppendRandom(), DataPumpThreadBody(), rocksdb::DBLoaderCommand::DoCommand(), leveldb_put(), rocksdb::StressTest::OperateDb(), rocksdb::ReduceLevelTest::Put(), rocksdb::DBImpl::Put(), rocksdb::DBTest::Put(), rocksdb::SimpleTableDBTest::Put(), rocksdb::ModelDB::Put(), rocksdb::Benchmark::ReadRandomWriteRandom(), rocksdb::Benchmark::ReadRandomWriteRandomMultiGet(), rocksdb::Benchmark::ReadWhileWriting(), rocksdb::TableReaderBenchmark(), rocksdb::TEST(), and rocksdb::Benchmark::UpdateRandom().
{
   WriteBatch batch;
   batch.Put(key, value);
   return Write(opt, &batch);
 }
virtual void rocksdb::DB::ReleaseSnapshot (const Snapshot * snapshot) pure virtual
Implemented in rocksdb::ModelDB, rocksdb::StackableDB, rocksdb::DBImpl, and rocksdb::DBWithTTL.
Referenced by rocksdb::Benchmark::AppendRandom(), rocksdb::Benchmark::GetMany(), leveldb_release_snapshot(), rocksdb::StressTest::MultiGet(), rocksdb::Benchmark::MultiGetRandom(), rocksdb::StressTest::MultiIterate(), rocksdb::StressTest::MultiPrefixScan(), rocksdb::Benchmark::ReadRandom(), rocksdb::Benchmark::ReadRandomWriteRandom(), rocksdb::DBWithTTL::ReleaseSnapshot(), and rocksdb::Benchmark::UpdateRandom().
virtual Status rocksdb::DB::Write (const WriteOptions & options, WriteBatch * updates) pure virtual
Implemented in rocksdb::ModelDB, rocksdb::StackableDB, rocksdb::DBImplReadOnly, rocksdb::DBWithTTL, and rocksdb::DBImpl.
Referenced by rocksdb::CorruptionTest::Build(), Delete(), rocksdb::Benchmark::DeleteMany(), rocksdb::Benchmark::DoDelete(), rocksdb::Benchmark::DoWrite(), rocksdb::DBConstructor::FinishImpl(), leveldb_write(), Merge(), rocksdb::StressTest::MultiDelete(), rocksdb::StressTest::MultiPut(), Put(), rocksdb::Benchmark::PutMany(), rocksdb::DBWithTTL::Write(), and rocksdb::Benchmark::writeOrFail().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/include/rocksdb/db.h
rippled/src/ripple/rocksdb/rocksdb/db/db_impl.cc
rippled/src/ripple/rocksdb/rocksdb/db/db_impl_readonly.cc