rippled: ripple::BookDirIterator Class Reference
ripple::BookDirIterator Class Reference
#include <OrderBookIterator.h>
Public Member Functions
BookDirIterator ()
BookDirIterator (uint160 const &uInCurrency, uint160 const &uInIssuer, uint160 const &uOutCurrency, uint160 const &uOutIssuer)
uint256 const & getBookBase () const
uint256 const & getBookEnd () const
uint256 const & getCurrentIndex () const
void setCurrentIndex (uint256 const &index)
STAmount getCurrentRate () const
std::uint64_t getCurrentQuality () const
bool nextDirectory (LedgerEntrySet &)
bool firstDirectory (LedgerEntrySet &)
bool resync (LedgerEntrySet &)
DirectoryEntryIterator getOfferIterator () const
std::uint64_t getRate () const
bool addJson (Json::Value &) const
bool setJson (Json::Value const &)
operator bool () const
bool operator== (BookDirIterator const &other) const
bool operator!= (BookDirIterator const &other) const
Private Attributes
uint256 mBase
uint256 mEnd
uint256 mIndex
SLE::pointer mOfferDir
Detailed Description
An iterator that walks the directories in a book
Definition at line 26 of file OrderBookIterator.h.
Constructor & Destructor Documentation
ripple::BookDirIterator::BookDirIterator () inline
Definition at line 31 of file OrderBookIterator.h.
     {
     }
ripple::BookDirIterator::BookDirIterator (uint160 const & uInCurrency, uint160 const & uInIssuer, uint160 const & uOutCurrency, uint160 const & uOutIssuer)
Iterate through the directories in an order book
Definition at line 23 of file OrderBookIterator.cpp.
References ripple::Ledger::getBookBase(), ripple::Ledger::getQualityNext(), mBase, mEnd, and mIndex.
 {
     mBase = Ledger::getBookBase(uInCurrency, uInIssuer, uOutCurrency, uOutIssuer);
     mEnd = Ledger::getQualityNext(mBase);
     mIndex = mBase;
 }
Member Function Documentation
bool ripple::BookDirIterator::addJson (Json::Value & jv) const
Definition at line 94 of file OrderBookIterator.cpp.
References ripple::base_uint< BITS >::GetHex(), and mIndex.
Referenced by ripple::OrderBookIterator::addJson().
 {
     if (! (*this))
         return false;
     jv["book_index"] = mIndex.GetHex();
     return true;
 }
bool ripple::BookDirIterator::firstDirectory (LedgerEntrySet & les)
Make this iterator refer to the first book
Jump to the beginning
Definition at line 59 of file OrderBookIterator.cpp.
References ripple::base_uint< BITS >::GetHex(), ripple::lsTRACE, mBase, mIndex, nextDirectory(), and WriteLog.
Referenced by ripple::OrderBookIterator::firstOffer().
 {
     WriteLog (lsTRACE, Ledger) << "BookDirIterator(" << mBase.GetHex() << ") firstDirectory";
     mIndex = mBase;
     return nextDirectory (les);
 }
uint256 const& ripple::BookDirIterator::getBookBase () const inline
Definition at line 39 of file OrderBookIterator.h.
References mBase.
     {
         return mBase;
     }
uint256 const& ripple::BookDirIterator::getBookEnd () const inline
Definition at line 44 of file OrderBookIterator.h.
References mEnd.
     {
         return mEnd;
     }
uint256 const& ripple::BookDirIterator::getCurrentIndex () const inline
Definition at line 49 of file OrderBookIterator.h.
References mIndex.
     {
         return mIndex;
     }
std::uint64_t ripple::BookDirIterator::getCurrentQuality () const inline
Get the current quality
Definition at line 68 of file OrderBookIterator.h.
References ripple::Ledger::getQuality(), and mIndex.
Referenced by ripple::OrderBookIterator::getCurrentQuality(), and getCurrentRate().
     {
         return Ledger::getQuality(mIndex);
     }
STAmount ripple::BookDirIterator::getCurrentRate () const inline
Get the current exchange rate
Definition at line 61 of file OrderBookIterator.h.
References getCurrentQuality(), and ripple::STAmount::setRate().
Referenced by ripple::OrderBookIterator::getCurrentRate().
     {
         return STAmount::setRate (getCurrentQuality());
     }
DirectoryEntryIterator ripple::BookDirIterator::getOfferIterator () const
Get an iterator to the offers in this directory
Definition at line 83 of file OrderBookIterator.cpp.
References ripple::base_uint< BITS >::GetHex(), ripple::lsTRACE, mBase, mOfferDir, and WriteLog.
Referenced by ripple::OrderBookIterator::firstOffer(), ripple::OrderBookIterator::nextDir(), ripple::OrderBookIterator::nextOffer(), and ripple::OrderBookIterator::rewind().
 {
     WriteLog (lsTRACE, Ledger) << "BookDirIterator(" << mBase.GetHex() << ") get offer iterator";
     return DirectoryEntryIterator (mOfferDir);
 }
std::uint64_t ripple::BookDirIterator::getRate () const
Definition at line 89 of file OrderBookIterator.cpp.
References ripple::Ledger::getQuality(), and mIndex.
 {
     return Ledger::getQuality(mIndex);
 }
bool ripple::BookDirIterator::nextDirectory (LedgerEntrySet & les)
Make this iterator refer to the next book
Definition at line 31 of file OrderBookIterator.cpp.
References ripple::LedgerEntrySet::entryCache(), ripple::base_uint< BITS >::GetHex(), ripple::LedgerEntrySet::getNextLedgerIndex(), ripple::base_uint< BITS >::isZero(), ripple::lsTRACE, ripple::ltDIR_NODE, mEnd, mIndex, mOfferDir, and WriteLog.
Referenced by firstDirectory(), ripple::OrderBookIterator::nextDir(), ripple::OrderBookIterator::nextOffer(), and resync().
 {
     WriteLog (lsTRACE, Ledger) << "BookDirectoryIterator:: nextDirectory";
     // Are we already at the end?
     if (mIndex.isZero ())
         return false;
     // Get the ledger index of the next directory
     mIndex = les.getNextLedgerIndex (mIndex, mEnd);
     if (mIndex.isZero ())
     {
         // We ran off the end of the book
         WriteLog (lsTRACE, Ledger) << "BookDirectoryIterator:: no next ledger index";
         return false;
     }
     assert (mIndex < mEnd);
     WriteLog (lsTRACE, Ledger) << "BookDirectoryIterator:: index " << mIndex.GetHex();
     // Retrieve the SLE from the LES
     mOfferDir = les.entryCache (ltDIR_NODE, mIndex);
     assert (mOfferDir);
     return !!mOfferDir;
 }
ripple::BookDirIterator::operator bool () const inline explicit
Definition at line 98 of file OrderBookIterator.h.
References mIndex, and mOfferDir.
     {
         return mOfferDir &&  (mOfferDir->getIndex() == mIndex);
     }
bool ripple::BookDirIterator::operator!= (BookDirIterator const & other) const inline
Definition at line 111 of file OrderBookIterator.h.
     {
         return ! (*this == other);
     }
bool ripple::BookDirIterator::operator== (BookDirIterator const & other) const inline
Definition at line 104 of file OrderBookIterator.h.
References ripple::base_uint< BITS >::isZero(), and mIndex.
     {
         assert (! mIndex.isZero() && ! other.mIndex.isZero());
         return mIndex == other.mIndex;
     }
bool ripple::BookDirIterator::resync (LedgerEntrySet & les)
The LES may have changed Resync the iterator
The LES may have changed. Repoint to the current directory if it still exists, Otherwise, go to the next one.
Definition at line 73 of file OrderBookIterator.cpp.
References ripple::base_uint< BITS >::isZero(), mBase, mIndex, and nextDirectory().
Referenced by ripple::OrderBookIterator::rewind().
 {
     if (mIndex.isZero ())
         mIndex = mBase;
     else if (mIndex != mBase)
         --mIndex;
     return nextDirectory (les);
 }
void ripple::BookDirIterator::setCurrentIndex (uint256 const & index) inline
Definition at line 54 of file OrderBookIterator.h.
References mIndex.
     {
         mIndex = index;
     }
bool ripple::BookDirIterator::setJson (Json::Value const & jv)
Definition at line 103 of file OrderBookIterator.cpp.
References Json::Value::asString(), Json::Value::isMember(), Json::Value::isString(), mIndex, and ripple::base_uint< BITS >::SetHexExact().
Referenced by ripple::OrderBookIterator::setJson().
 {
     if (!jv.isMember("book_index"))
         return false;
     const Json::Value& bi = jv["book_index"];
     if (!bi.isString ())
         return false;
     mIndex.SetHexExact(bi.asString());
     return true;
 }
Member Data Documentation
uint256 ripple::BookDirIterator::mBase private
Definition at line 117 of file OrderBookIterator.h.
Referenced by BookDirIterator(), firstDirectory(), getBookBase(), getOfferIterator(), and resync().
uint256 ripple::BookDirIterator::mEnd private
Definition at line 118 of file OrderBookIterator.h.
Referenced by BookDirIterator(), getBookEnd(), and nextDirectory().
uint256 ripple::BookDirIterator::mIndex private
Definition at line 119 of file OrderBookIterator.h.
Referenced by addJson(), BookDirIterator(), firstDirectory(), getCurrentIndex(), getCurrentQuality(), getRate(), nextDirectory(), operator bool(), operator==(), resync(), setCurrentIndex(), and setJson().
SLE::pointer ripple::BookDirIterator::mOfferDir private
Definition at line 120 of file OrderBookIterator.h.
Referenced by getOfferIterator(), nextDirectory(), and operator bool().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/ledger/OrderBookIterator.h
rippled/src/ripple_app/ledger/OrderBookIterator.cpp