rippled: beast::detail::DispatchedHandler< Dispatcher, Handler > Class Template Reference
beast::detail::DispatchedHandler< Dispatcher, Handler > Class Template Reference
#include <DispatchedHandler.h>
Public Types
typedef void result_type
Public Member Functions
DispatchedHandler (Dispatcher dispatcher, Handler &handler)
void operator() ()
void operator() () const
template<class P1 >
void operator() (P1 const &p1)
template<class P1 >
void operator() (P1 const &p1) const
template<class P1 , class P2 >
void operator() (P1 const &p1, P2 const &p2)
template<class P1 , class P2 >
void operator() (P1 const &p1, P2 const &p2) const
template<class P1 , class P2 , class P3 >
void operator() (P1 const &p1, P2 const &p2, P3 const &p3)
template<class P1 , class P2 , class P3 >
void operator() (P1 const &p1, P2 const &p2, P3 const &p3) const
template<class P1 , class P2 , class P3 , class P4 >
void operator() (P1 const &p1, P2 const &p2, P3 const &p3, P4 const &p4)
template<class P1 , class P2 , class P3 , class P4 >
void operator() (P1 const &p1, P2 const &p2, P3 const &p3, P4 const &p4) const
template<class P1 , class P2 , class P3 , class P4 , class P5 >
void operator() (P1 const &p1, P2 const &p2, P3 const &p3, P4 const &p4, P5 const &p5)
template<class P1 , class P2 , class P3 , class P4 , class P5 >
void operator() (P1 const &p1, P2 const &p2, P3 const &p3, P4 const &p4, P5 const &p5) const
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
void operator() (P1 const &p1, P2 const &p2, P3 const &p3, P4 const &p4, P5 const &p5, P6 const &p6)
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
void operator() (P1 const &p1, P2 const &p2, P3 const &p3, P4 const &p4, P5 const &p5, P6 const &p6) const
Private Attributes
Dispatcher m_dispatcher
Handler m_handler
Detailed Description
template<typename Dispatcher, typename Handler>
class beast::detail::DispatchedHandler< Dispatcher, Handler >
A wrapper that packages function call arguments into a dispatch.
Definition at line 30 of file DispatchedHandler.h.
Member Typedef Documentation
template<typename Dispatcher , typename Handler > typedef void beast::detail::DispatchedHandler< Dispatcher, Handler >::result_type
Definition at line 37 of file DispatchedHandler.h.
Constructor & Destructor Documentation
template<typename Dispatcher , typename Handler > beast::detail::DispatchedHandler< Dispatcher, Handler >::DispatchedHandler (Dispatcher dispatcher, Handler & handler) inline
Definition at line 39 of file DispatchedHandler.h.
         : m_dispatcher (dispatcher)
         , m_handler (BEAST_MOVE_CAST(Handler)(handler))
     {
     }
Member Function Documentation
template<typename Dispatcher , typename Handler > void beast::detail::DispatchedHandler< Dispatcher, Handler >::operator() () inline
Definition at line 59 of file DispatchedHandler.h.
References beast::detail::DispatchedHandler< Dispatcher, Handler >::m_dispatcher, and beast::detail::DispatchedHandler< Dispatcher, Handler >::m_handler.
     {
         m_dispatcher.dispatch (m_handler);
     }
template<typename Dispatcher , typename Handler > void beast::detail::DispatchedHandler< Dispatcher, Handler >::operator() () const inline
Definition at line 64 of file DispatchedHandler.h.
References beast::detail::DispatchedHandler< Dispatcher, Handler >::m_dispatcher, and beast::detail::DispatchedHandler< Dispatcher, Handler >::m_handler.
     {
         m_dispatcher.dispatch (m_handler);
     }
template<typename Dispatcher , typename Handler > template<class P1 > void beast::detail::DispatchedHandler< Dispatcher, Handler >::operator() (P1 const & p1) inline
Definition at line 70 of file DispatchedHandler.h.
References beast::detail::bindHandler(), beast::detail::DispatchedHandler< Dispatcher, Handler >::m_dispatcher, and beast::detail::DispatchedHandler< Dispatcher, Handler >::m_handler.
     {
         m_dispatcher.dispatch (
             detail::bindHandler (m_handler,
                 p1));
     }
template<typename Dispatcher , typename Handler > template<class P1 > void beast::detail::DispatchedHandler< Dispatcher, Handler >::operator() (P1 const & p1) const inline
Definition at line 78 of file DispatchedHandler.h.
References beast::detail::bindHandler(), beast::detail::DispatchedHandler< Dispatcher, Handler >::m_dispatcher, and beast::detail::DispatchedHandler< Dispatcher, Handler >::m_handler.
     {
         m_dispatcher.dispatch (
             detail::bindHandler (m_handler,
                 p1));
     }
template<typename Dispatcher , typename Handler > template<class P1 , class P2 > void beast::detail::DispatchedHandler< Dispatcher, Handler >::operator() (P1 const & p1, P2 const & p2) inline
Definition at line 86 of file DispatchedHandler.h.
References beast::detail::bindHandler(), beast::detail::DispatchedHandler< Dispatcher, Handler >::m_dispatcher, and beast::detail::DispatchedHandler< Dispatcher, Handler >::m_handler.
     {
         m_dispatcher.dispatch (
             detail::bindHandler (m_handler,
                 p1, p2));
     }
template<typename Dispatcher , typename Handler > template<class P1 , class P2 > void beast::detail::DispatchedHandler< Dispatcher, Handler >::operator() (P1 const & p1, P2 const & p2) const inline
Definition at line 94 of file DispatchedHandler.h.
References beast::detail::bindHandler(), beast::detail::DispatchedHandler< Dispatcher, Handler >::m_dispatcher, and beast::detail::DispatchedHandler< Dispatcher, Handler >::m_handler.
     {
         m_dispatcher.dispatch (
             detail::bindHandler (m_handler,
                 p1, p2));
     }
template<typename Dispatcher , typename Handler > template<class P1 , class P2 , class P3 > void beast::detail::DispatchedHandler< Dispatcher, Handler >::operator() (P1 const & p1, P2 const & p2, P3 const & p3) inline
Definition at line 102 of file DispatchedHandler.h.
References beast::detail::bindHandler(), beast::detail::DispatchedHandler< Dispatcher, Handler >::m_dispatcher, and beast::detail::DispatchedHandler< Dispatcher, Handler >::m_handler.
     {
         m_dispatcher.dispatch (
             detail::bindHandler (m_handler,
                 p1, p2, p3));
     }
template<typename Dispatcher , typename Handler > template<class P1 , class P2 , class P3 > void beast::detail::DispatchedHandler< Dispatcher, Handler >::operator() (P1 const & p1, P2 const & p2, P3 const & p3) const inline
Definition at line 110 of file DispatchedHandler.h.
References beast::detail::bindHandler(), beast::detail::DispatchedHandler< Dispatcher, Handler >::m_dispatcher, and beast::detail::DispatchedHandler< Dispatcher, Handler >::m_handler.
     {
         m_dispatcher.dispatch (
             detail::bindHandler (m_handler,
                 p1, p2, p3));
     }
template<typename Dispatcher , typename Handler > template<class P1 , class P2 , class P3 , class P4 > void beast::detail::DispatchedHandler< Dispatcher, Handler >::operator() (P1 const & p1, P2 const & p2, P3 const & p3, P4 const & p4) inline
Definition at line 118 of file DispatchedHandler.h.
References beast::detail::bindHandler(), beast::detail::DispatchedHandler< Dispatcher, Handler >::m_dispatcher, and beast::detail::DispatchedHandler< Dispatcher, Handler >::m_handler.
     {
         m_dispatcher.dispatch (
             detail::bindHandler (m_handler,
                 p1, p2, p3, p4));
     }
template<typename Dispatcher , typename Handler > template<class P1 , class P2 , class P3 , class P4 > void beast::detail::DispatchedHandler< Dispatcher, Handler >::operator() (P1 const & p1, P2 const & p2, P3 const & p3, P4 const & p4) const inline
Definition at line 126 of file DispatchedHandler.h.
References beast::detail::bindHandler(), beast::detail::DispatchedHandler< Dispatcher, Handler >::m_dispatcher, and beast::detail::DispatchedHandler< Dispatcher, Handler >::m_handler.
     {
         m_dispatcher.dispatch (
             detail::bindHandler (m_handler,
                 p1, p2, p3, p4));
     }
template<typename Dispatcher , typename Handler > template<class P1 , class P2 , class P3 , class P4 , class P5 > void beast::detail::DispatchedHandler< Dispatcher, Handler >::operator() (P1 const & p1, P2 const & p2, P3 const & p3, P4 const & p4, P5 const & p5) inline
Definition at line 134 of file DispatchedHandler.h.
References beast::detail::bindHandler(), beast::detail::DispatchedHandler< Dispatcher, Handler >::m_dispatcher, and beast::detail::DispatchedHandler< Dispatcher, Handler >::m_handler.
     {
         m_dispatcher.dispatch (
             detail::bindHandler (m_handler,
                 p1, p2, p3, p4, p5));
     }
template<typename Dispatcher , typename Handler > template<class P1 , class P2 , class P3 , class P4 , class P5 > void beast::detail::DispatchedHandler< Dispatcher, Handler >::operator() (P1 const & p1, P2 const & p2, P3 const & p3, P4 const & p4, P5 const & p5) const inline
Definition at line 143 of file DispatchedHandler.h.
References beast::detail::bindHandler(), beast::detail::DispatchedHandler< Dispatcher, Handler >::m_dispatcher, and beast::detail::DispatchedHandler< Dispatcher, Handler >::m_handler.
     {
         m_dispatcher.dispatch (
             detail::bindHandler (m_handler,
                 p1, p2, p3, p4, p5));
     }
template<typename Dispatcher , typename Handler > template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > void beast::detail::DispatchedHandler< Dispatcher, Handler >::operator() (P1 const & p1, P2 const & p2, P3 const & p3, P4 const & p4, P5 const & p5, P6 const & p6) inline
Definition at line 152 of file DispatchedHandler.h.
References beast::detail::bindHandler(), beast::detail::DispatchedHandler< Dispatcher, Handler >::m_dispatcher, and beast::detail::DispatchedHandler< Dispatcher, Handler >::m_handler.
     {
         m_dispatcher.dispatch (
             detail::bindHandler (m_handler,
                 p1, p2, p3, p4, p5, p6));
     }
template<typename Dispatcher , typename Handler > template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > void beast::detail::DispatchedHandler< Dispatcher, Handler >::operator() (P1 const & p1, P2 const & p2, P3 const & p3, P4 const & p4, P5 const & p5, P6 const & p6) const inline
Definition at line 161 of file DispatchedHandler.h.
References beast::detail::bindHandler(), beast::detail::DispatchedHandler< Dispatcher, Handler >::m_dispatcher, and beast::detail::DispatchedHandler< Dispatcher, Handler >::m_handler.
     {
         m_dispatcher.dispatch (
             detail::bindHandler (m_handler,
                 p1, p2, p3, p4, p5, p6));
     }
Member Data Documentation
template<typename Dispatcher , typename Handler > Dispatcher beast::detail::DispatchedHandler< Dispatcher, Handler >::m_dispatcher private
Definition at line 33 of file DispatchedHandler.h.
Referenced by beast::detail::DispatchedHandler< Dispatcher, Handler >::operator()().
template<typename Dispatcher , typename Handler > Handler beast::detail::DispatchedHandler< Dispatcher, Handler >::m_handler private
Definition at line 34 of file DispatchedHandler.h.
Referenced by beast::detail::DispatchedHandler< Dispatcher, Handler >::operator()().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/threads/detail/DispatchedHandler.h