rippled: rocksdb::ChangeCompactionStyleCommand Class Reference
rocksdb::ChangeCompactionStyleCommand Class Reference
#include <ldb_cmd.h>
Public Member Functions
ChangeCompactionStyleCommand (const vector< string > &params, const map< string, string > &options, const vector< string > &flags)
virtual Options PrepareOptionsForOpenDB ()
virtual void DoCommand ()
Public Member Functions inherited from rocksdb::LDBCommand
bool ValidateCmdLineOptions ()
virtual void SetOptions (Options options)
virtual bool NoDBOpen ()
virtual ~LDBCommand ()
void Run ()
LDBCommandExecuteResult GetExecuteState ()
void ClearPreviousRunState ()
Static Public Member Functions
static string Name ()
static void Help (string &msg)
Static Public Member Functions inherited from rocksdb::LDBCommand
static LDBCommand * InitFromCmdLineArgs (const vector< string > &args, const Options &options=Options())
static LDBCommand * InitFromCmdLineArgs (int argc, char **argv, const Options &options=Options())
static string HexToString (const string &str)
static string StringToHex (const string &str)
Private Attributes
int old_compaction_style_
int new_compaction_style_
Static Private Attributes
static const string ARG_OLD_COMPACTION_STYLE
static const string ARG_NEW_COMPACTION_STYLE
Additional Inherited Members
Static Public Attributes inherited from rocksdb::LDBCommand
static const string ARG_DB = "db"
static const string ARG_HEX = "hex"
static const string ARG_KEY_HEX = "key_hex"
static const string ARG_VALUE_HEX = "value_hex"
static const string ARG_TTL = "ttl"
static const string ARG_TTL_START = "start_time"
static const string ARG_TTL_END = "end_time"
static const string ARG_TIMESTAMP = "timestamp"
static const string ARG_FROM = "from"
static const string ARG_TO = "to"
static const string ARG_MAX_KEYS = "max_keys"
static const string ARG_BLOOM_BITS = "bloom_bits"
static const string ARG_COMPRESSION_TYPE = "compression_type"
static const string ARG_BLOCK_SIZE = "block_size"
static const string ARG_AUTO_COMPACTION = "auto_compaction"
static const string ARG_WRITE_BUFFER_SIZE = "write_buffer_size"
static const string ARG_FILE_SIZE = "file_size"
static const string ARG_CREATE_IF_MISSING = "create_if_missing"
static const char * DELIM = " ==> "
Protected Member Functions inherited from rocksdb::LDBCommand
bool ParseKeyValue (const string &line, string *key, string *value, bool is_key_hex, bool is_value_hex)
LDBCommand (const map< string, string > &options, const vector< string > &flags, bool is_read_only, const vector< string > &valid_cmd_line_options)
void OpenDB ()
void CloseDB ()
vector< string > BuildCmdLineOptions (vector< string > options)
bool ParseIntOption (const map< string, string > &options, const string &option, int &value, LDBCommandExecuteResult &exec_state)
bool ParseStringOption (const map< string, string > &options, const string &option, string *value)
Static Protected Member Functions inherited from rocksdb::LDBCommand
static string PrintKeyValue (const string &key, const string &value, bool is_key_hex, bool is_value_hex)
static string PrintKeyValue (const string &key, const string &value, bool is_hex)
static bool IsFlagPresent (const vector< string > &flags, const string &flag)
static string HelpRangeCmdArgs ()
Protected Attributes inherited from rocksdb::LDBCommand
LDBCommandExecuteResult exec_state_
string db_path_
DB * db_
StackableDB * sdb_
bool is_read_only_
bool is_key_hex_
bool is_value_hex_
bool is_db_ttl_
bool timestamp_
const map< string, string > option_map_
const vector< string > flags_
const vector< string > valid_cmd_line_options_
Options options_
Detailed Description
Definition at line 518 of file ldb_cmd.h.
Constructor & Destructor Documentation
rocksdb::ChangeCompactionStyleCommand::ChangeCompactionStyleCommand (const vector< string > & params, const map< string, string > & options, const vector< string > & flags)
Definition at line 1100 of file ldb_cmd.cc.
References ARG_NEW_COMPACTION_STYLE, and ARG_OLD_COMPACTION_STYLE.
                                    :
     LDBCommand(options, flags, false,
                BuildCmdLineOptions({ARG_OLD_COMPACTION_STYLE,
                                     ARG_NEW_COMPACTION_STYLE})),
Member Function Documentation
void rocksdb::ChangeCompactionStyleCommand::DoCommand () virtual
Implements rocksdb::LDBCommand.
Definition at line 1172 of file ldb_cmd.cc.
References rocksdb::DB::CompactRange(), rocksdb::LDBCommand::db_, rocksdb::LDBCommand::exec_state_, rocksdb::LDBCommandExecuteResult::FAILED(), rocksdb::DB::GetProperty(), rocksdb::DB::NumberLevels(), rocksdb::NumberToString(), and beast::IP::to_string().
{
   // print db stats before we have made any change
   std::string property;
   std::string files_per_level;
   for (int i = 0; i < db_->NumberLevels(); i++) {
     db_->GetProperty("rocksdb.num-files-at-level" + NumberToString(i),
                      &property);
     // format print string
     char buf[100];
     snprintf(buf, sizeof(buf), "%s%s", (i ? "," : ""), property.c_str());
     files_per_level += buf;
   }
   fprintf(stdout, "files per level before compaction: %s\n",
           files_per_level.c_str());
   // manual compact into a single file and move the file to level 0
   db_->CompactRange(nullptr, nullptr,
                     true /* reduce level */,
                     0    /* reduce to level 0 */);
   // verify compaction result
   files_per_level = "";
   int num_files = 0;
   for (int i = 0; i < db_->NumberLevels(); i++) {
     db_->GetProperty("rocksdb.num-files-at-level" + NumberToString(i),
                      &property);
     // format print string
     char buf[100];
     snprintf(buf, sizeof(buf), "%s%s", (i ? "," : ""), property.c_str());
     files_per_level += buf;
     num_files = atoi(property.c_str());
     // level 0 should have only 1 file
     if (i == 0 && num_files != 1) {
       exec_state_ = LDBCommandExecuteResult::FAILED("Number of db files at "
         "level 0 after compaction is " + std::to_string(num_files) +
         ", not 1.\n");
       return;
     }
     // other levels should have no file
     if (i > 0 && num_files != 0) {
       exec_state_ = LDBCommandExecuteResult::FAILED("Number of db files at "
         "level " + std::to_string(i) + " after compaction is " +
         std::to_string(num_files) + ", not 0.\n");
       return;
     }
   }
   fprintf(stdout, "files per level after compaction: %s\n",
           files_per_level.c_str());
 }
void rocksdb::ChangeCompactionStyleCommand::Help (string & msg) static
Definition at line 1145 of file ldb_cmd.cc.
References ARG_NEW_COMPACTION_STYLE, ARG_OLD_COMPACTION_STYLE, and Name().
Referenced by rocksdb::LDBCommandRunner::PrintHelp().
{
   ret.append("  ");
   ret.append(ChangeCompactionStyleCommand::Name());
   ret.append(" --" + ARG_OLD_COMPACTION_STYLE + "=<Old compaction style: 0 " +
              "for level compaction, 1 for universal compaction>");
   ret.append(" --" + ARG_NEW_COMPACTION_STYLE + "=<New compaction style: 0 " +
              "for level compaction, 1 for universal compaction>");
   ret.append("\n");
 }
static string rocksdb::ChangeCompactionStyleCommand::Name () inline static
Definition at line 520 of file ldb_cmd.h.
Referenced by Help(), and rocksdb::LDBCommand::SelectCommand().
 { return "change_compaction_style"; }
Options rocksdb::ChangeCompactionStyleCommand::PrepareOptionsForOpenDB () virtual
Reimplemented from rocksdb::LDBCommand.
Definition at line 1155 of file ldb_cmd.cc.
References rocksdb::Options::disable_auto_compactions, rocksdb::kCompactionStyleLevel, rocksdb::kCompactionStyleUniversal, rocksdb::Options::max_bytes_for_level_base, rocksdb::Options::max_bytes_for_level_multiplier, new_compaction_style_, old_compaction_style_, rocksdb::LDBCommand::PrepareOptionsForOpenDB(), rocksdb::Options::target_file_size_base, and rocksdb::Options::target_file_size_multiplier.
{
   Options opt = LDBCommand::PrepareOptionsForOpenDB();
   if (old_compaction_style_ == kCompactionStyleLevel &&
       new_compaction_style_ == kCompactionStyleUniversal) {
     // In order to convert from level compaction to universal compaction, we
     // need to compact all data into a single file and move it to level 0.
     opt.disable_auto_compactions = true;
     opt.target_file_size_base = INT_MAX;
     opt.target_file_size_multiplier = 1;
     opt.max_bytes_for_level_base = INT_MAX;
     opt.max_bytes_for_level_multiplier = 1;
   }
   return opt;
 }
Member Data Documentation
const string rocksdb::ChangeCompactionStyleCommand::ARG_NEW_COMPACTION_STYLE static private
Initial value:
=
  "new_compaction_style"
Definition at line 536 of file ldb_cmd.h.
Referenced by ChangeCompactionStyleCommand(), and Help().
const string rocksdb::ChangeCompactionStyleCommand::ARG_OLD_COMPACTION_STYLE static private
Initial value:
=
  "old_compaction_style"
Definition at line 535 of file ldb_cmd.h.
Referenced by ChangeCompactionStyleCommand(), and Help().
int rocksdb::ChangeCompactionStyleCommand::new_compaction_style_ private
Definition at line 533 of file ldb_cmd.h.
Referenced by PrepareOptionsForOpenDB().
int rocksdb::ChangeCompactionStyleCommand::old_compaction_style_ private
Definition at line 532 of file ldb_cmd.h.
Referenced by PrepareOptionsForOpenDB().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/util/ldb_cmd.h
rippled/src/ripple/rocksdb/rocksdb/util/ldb_cmd.cc