rippled: rocksdb::test Namespace Reference
rocksdb::test Namespace Reference
Classes
class Tester
class ErrorEnv
Functions
bool RegisterTest (const char *base, const char *name, void(*func)())
int RunAllTests ()
std::string TmpDir ()
int RandomSeed ()
Slice RandomString (Random *rnd, int len, std::string *dst)
std::string RandomKey (Random *rnd, int len)
Slice CompressibleString (Random *rnd, double compressed_fraction, int len, std::string *dst)
Function Documentation
Slice rocksdb::test::CompressibleString (Random * rnd, double compressed_fraction, int len, std::string * dst)
Definition at line 39 of file testutil.cc.
References RandomString().
Referenced by rocksdb::Do_Compression_Test(), and rocksdb::RandomGenerator::RandomGenerator().
{
   int raw = static_cast<int>(len * compressed_fraction);
   if (raw < 1) raw = 1;
   std::string raw_data;
   RandomString(rnd, raw, &raw_data);
   // Duplicate the random data until we have filled "len" bytes
   dst->clear();
   while (dst->size() < (unsigned int)len) {
     dst->append(raw_data);
   }
   dst->resize(len);
   return Slice(*dst);
 }
std::string rocksdb::test::RandomKey (Random * rnd, int len)
Definition at line 25 of file testutil.cc.
References rocksdb::Random::Uniform().
Referenced by rocksdb::RandomKey(), and rocksdb::TEST().
{
   // Make sure to generate a wide variety of characters so we
   // test the boundary conditions for short-key optimizations.
   static const char kTestChars[] = {
     '\0', '\1', 'a', 'b', 'c', 'd', 'e', '\xfd', '\xfe', '\xff'
   };
   std::string result;
   for (int i = 0; i < len; i++) {
     result += kTestChars[rnd->Uniform(sizeof(kTestChars))];
   }
   return result;
 }
int rocksdb::test::RandomSeed ()
Definition at line 72 of file testharness.cc.
References env.
Referenced by rocksdb::RunConcurrent(), and rocksdb::TEST().
                  {
   const char* env = getenv("TEST_RANDOM_SEED");
   int result = (env != nullptr ? atoi(env) : 301);
   if (result <= 0) {
     result = 301;
   }
   return result;
 }
Slice rocksdb::test::RandomString (Random * rnd, int len, std::string * dst)
Definition at line 17 of file testutil.cc.
References rocksdb::Random::Uniform().
Referenced by CompressibleString(), RandomString(), rocksdb::RandomString(), rocksdb::TEST(), and rocksdb::CorruptionTest::Value().
{
   dst->resize(len);
   for (int i = 0; i < len; i++) {
     (*dst)[i] = static_cast<char>(' ' + rnd->Uniform(95));   // ' ' .. '~'
   }
   return Slice(*dst);
 }
bool rocksdb::test::RegisterTest (const char * base, const char * name, void(*)() func)
Definition at line 29 of file testharness.cc.
References base, func, and name.
{
   if (tests == nullptr) {
     tests = new std::vector<Test>;
   }
   Test t;
   t.base = base;
   t.name = name;
   t.func = func;
   tests->push_back(t);
   return true;
 }
int rocksdb::test::RunAllTests ()
Definition at line 41 of file testharness.cc.
Referenced by main().
                   {
   const char* matcher = getenv("ROCKSDB_TESTS");
   int num = 0;
   if (tests != nullptr) {
     for (unsigned int i = 0; i < tests->size(); i++) {
       const Test& t = (*tests)[i];
       if (matcher != nullptr) {
         std::string name = t.base;
         name.push_back('.');
         name.append(t.name);
         if (strstr(name.c_str(), matcher) == nullptr) {
           continue;
         }
       }
       fprintf(stderr, "==== Test %s.%s\n", t.base, t.name);
       (*t.func)();
       ++num;
     }
   }
   fprintf(stderr, "==== PASSED %d tests\n", num);
   return 0;
 }
std::string rocksdb::test::TmpDir ()
Definition at line 65 of file testharness.cc.
References ASSERT_TRUE, rocksdb::Env::Default(), rocksdb::Env::GetTestDirectory(), rocksdb::Status::ok(), and rocksdb::Status::ToString().
Referenced by rocksdb::BM_LogAndApply(), rocksdb::CorruptionTest::CorruptionTest(), rocksdb::DBTest::CurrentOptions(), rocksdb::DBTest::DBTest(), rocksdb::DeleteFileTest::DeleteFileTest(), main(), rocksdb::DBConstructor::NewDB(), rocksdb::ReduceLevelTest::ReduceLevelTest(), rocksdb::SimpleTableDBTest::SimpleTableDBTest(), rocksdb::TableReaderBenchmark(), rocksdb::TEST(), and rocksdb::TtlTest::TtlTest().
                    {
   std::string dir;
   Status s = Env::Default()->GetTestDirectory(&dir);
   ASSERT_TRUE(s.ok()) << s.ToString();
   return dir;
 }