rippled: ripple::TestOverlay::Network1_test Class Reference
ripple::TestOverlay::Network1_test Class Reference
Classes
struct Params
class PeerLogic
class SeenState
Public Types
typedef Params::Network Network
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Member Functions
void testCreation ()
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Additional Inherited Members
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 31 of file TestOverlay.cpp.
Member Typedef Documentation
typedef Params::Network ripple::TestOverlay::Network1_test::Network
Definition at line 114 of file TestOverlay.cpp.
Member Function Documentation
void ripple::TestOverlay::Network1_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 142 of file TestOverlay.cpp.
References testCreation().
     {
         testCreation ();
     }
void ripple::TestOverlay::Network1_test::testCreation () inline
Definition at line 118 of file TestOverlay.cpp.
References beast::String::fromNumber(), beast::unit_test::suite::log, beast::unit_test::suite::pass(), ripple::TestOverlay::Results::received, seen, ripple::TestOverlay::NetworkType< ConfigParam >::state(), ripple::TestOverlay::NetworkType< ConfigParam >::step(), ripple::TestOverlay::NetworkType< ConfigParam >::steps(), and ripple::TestOverlay::Results::toString().
Referenced by run().
     {
         Network network;
         Results result;
         for (int i = 0; result.received < 249 && i < 100; ++i)
         {
             using beast::String;
             String s =
                 String ("step #") + String::fromNumber (
                 network.steps()) + " ";
             result += network.step ();
             s << result.toString ();
             log << s.toStdString();
         }
         int const seen (network.state().seen());
         beast::String s = "Seen = " + beast::String::fromNumber (seen);
         log <<
             s.toStdString();
         pass ();
     }
The documentation for this class was generated from the following file:
rippled/src/ripple/testoverlay/impl/TestOverlay.cpp