rippled: beast::RandomAccessFile Class Reference
beast::RandomAccessFile Class Reference
#include <RandomAccessFile.h>
Public Types
enum Mode { readOnly, readWrite }
typedef std::int64_t FileOffset
typedef size_t ByteCount
Public Member Functions
RandomAccessFile () noexcept
~RandomAccessFile ()
bool isOpen () const noexcept
Result open (File const &path, Mode mode)
void close ()
File const & getFile () const noexcept
FileOffset getPosition () const noexcept
Result setPosition (FileOffset newPosition)
Result read (void *buffer, ByteCount numBytes, ByteCount *pActualAmount=0)
Result write (const void *data, ByteCount numBytes, ByteCount *pActualAmount=0)
Result truncate ()
Result flush ()
Private Member Functions
Result nativeOpen (File const &path, Mode mode)
void nativeClose ()
Result nativeSetPosition (FileOffset newPosition)
Result nativeRead (void *buffer, ByteCount numBytes, ByteCount *pActualAmount=0)
Result nativeWrite (const void *data, ByteCount numBytes, ByteCount *pActualAmount=0)
Result nativeTruncate ()
Result nativeFlush ()
Private Attributes
File file
void * fileHandle
FileOffset currentPosition
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
Provides random access reading and writing to an operating system file.
This class wraps the underlying native operating system routines for opening and closing a file for reading and/or writing, seeking within the file, and performing read and write operations. There are also methods provided for obtaining an input or output stream which will work with the file.
Note
All files are opened in binary mode. No text newline conversions are performed.
None of these members are thread safe. The caller is responsible for synchronization.
See Also
FileInputStream, FileOutputStream
Definition at line 42 of file RandomAccessFile.h.
Member Typedef Documentation
typedef size_t beast::RandomAccessFile::ByteCount
The type of a byte count.
This can be useful when writing templates.
Definition at line 55 of file RandomAccessFile.h.
typedef std::int64_t beast::RandomAccessFile::FileOffset
The type of an FileOffset.
This can be useful when writing templates.
Definition at line 49 of file RandomAccessFile.h.
Member Enumeration Documentation
enum beast::RandomAccessFile::Mode
The access mode.
See Also
open
Enumerator
readOnly
readWrite
Definition at line 61 of file RandomAccessFile.h.
     {
         readOnly,
         readWrite
     };
Constructor & Destructor Documentation
beast::RandomAccessFile::RandomAccessFile () noexcept
Creates an unopened file object.
See Also
open, isOpen
Definition at line 24 of file RandomAccessFile.cpp.
     : fileHandle (nullptr)
     , currentPosition (0)
 {
 }
beast::RandomAccessFile::~RandomAccessFile ()
Destroy the file object.
If the operating system file is open it will be closed.
Definition at line 30 of file RandomAccessFile.cpp.
References close().
 {
     close ();
 }
Member Function Documentation
void beast::RandomAccessFile::close ()
Closes the file object.
Any data that needs to be flushed will be written before the file is closed.
Note
If no file is opened, this call does nothing.
Definition at line 42 of file RandomAccessFile.cpp.
References isOpen(), nativeClose(), and nativeFlush().
Referenced by nativeClose(), nativeOpen(), open(), and ~RandomAccessFile().
 {
     if (isOpen ())
     {
         nativeFlush ();
         nativeClose ();
     }
 }
Result beast::RandomAccessFile::flush ()
Flush the output buffers.
This calls the operating system to make sure all data has been written.
Definition at line 98 of file RandomAccessFile.cpp.
References nativeFlush().
Referenced by nativeTruncate(), and truncate().
 {
     return nativeFlush ();
 }
File const& beast::RandomAccessFile::getFile () const inline noexcept
Retrieve the File associated with this object.
Returns
The associated File.
Definition at line 113 of file RandomAccessFile.h.
References file.
 { return file; }
FileOffset beast::RandomAccessFile::getPosition () const inline noexcept
Get the current position.
The next read or write will take place from here.
Returns
The current position, as an absolute byte FileOffset from the begining.
Definition at line 121 of file RandomAccessFile.h.
References currentPosition.
 { return currentPosition; }
bool beast::RandomAccessFile::isOpen () const inline noexcept
Determine if a file is open.
Returns
true if the operating system file is open.
Definition at line 84 of file RandomAccessFile.h.
References fileHandle.
Referenced by close(), nativeClose(), nativeFlush(), nativeOpen(), nativeRead(), nativeSetPosition(), nativeTruncate(), and nativeWrite().
 { return fileHandle != nullptr; }
void beast::RandomAccessFile::nativeClose () private
Definition at line 482 of file posix_SharedCode.h.
References bassert, close(), currentPosition, file, fileHandle, isOpen(), and beast::File::nonexistent().
Referenced by close().
 {
     bassert (isOpen ());
     file = File::nonexistent ();
     ::close (getFD (fileHandle));
     fileHandle = nullptr;
     currentPosition = 0;
 }
Result beast::RandomAccessFile::nativeFlush () private
Definition at line 571 of file posix_SharedCode.h.
References bassert, file, fileHandle, beast::File::getFullPathName(), isOpen(), and beast::Result::ok().
Referenced by close(), and flush().
 {
     bassert (isOpen ());
     Result result (Result::ok ());
     if (fsync (getFD (fileHandle)) == -1)
         result = getResultForErrno();
 #if BEAST_ANDROID
     // This stuff tells the OS to asynchronously update the metadata
     // that the OS has cached aboud the file - this metadata is used
     // when the device is acting as a USB drive, and unless it's explicitly
     // refreshed, it'll get out of step with the real file.
     const LocalRef<jstring> t (javaString (file.getFullPathName()));
     android.activity.callVoidMethod (BeastAppActivity.scanFile, t.get());
 #endif
     return result;
 }
Result beast::RandomAccessFile::nativeOpen (File const & path, Mode mode) private
Definition at line 416 of file posix_SharedCode.h.
References bassert, close(), currentPosition, beast::File::exists(), beast::Result::fail(), file, fileHandle, beast::File::getFullPathName(), isOpen(), O_RDONLY, beast::Result::ok(), open(), beast.util.CleanCPPFiles::path, readOnly, readWrite, and beast::String::toUTF8().
Referenced by open().
 {
     bassert (! isOpen ());
     Result result (Result::ok ());
     if (path.exists())
     {
         int oflag;
         switch (mode)
         {
         case readOnly:
             oflag = O_RDONLY;
             break;
         default:
         case readWrite:
             oflag = O_RDWR;
             break;
         };
         const int f = ::open (path.getFullPathName().toUTF8(), oflag, 00644);
         if (f != -1)
         {
             currentPosition = lseek (f, 0, SEEK_SET);
             if (currentPosition >= 0)
             {
                 file = path;
                 fileHandle = fdToVoidPointer (f);
             }
             else
             {
                 result = getResultForErrno();
                 ::close (f);
             }
         }
         else
         {
             result = getResultForErrno();
         }
     }
     else if (mode == readWrite)
     {
         const int f = ::open (path.getFullPathName().toUTF8(), O_RDWR + O_CREAT, 00644);
         if (f != -1)
         {
             file = path;
             fileHandle = fdToVoidPointer (f);
         }
         else
         {
             result = getResultForErrno();
         }
     }
     else
     {
         // file doesn't exist and we're opening read-only
         Result::fail (String (strerror (ENOENT)));
     }
     return result;
 }
Result beast::RandomAccessFile::nativeRead (void * buffer, ByteCount numBytes, ByteCount * pActualAmount = 0) private
Definition at line 511 of file posix_SharedCode.h.
References bassert, currentPosition, fileHandle, isOpen(), beast::Result::ok(), and read().
Referenced by read().
 {
     bassert (isOpen ());
     std::ptrdiff_t bytesRead = ::read (getFD (fileHandle), buffer, numBytes);
     if (bytesRead < 0)
     {
         if (pActualAmount != nullptr)
             *pActualAmount = 0;
         // VFALCO NOTE I dislike return from the middle but
         //             Result::ok() is showing up in the profile
         //
         return getResultForErrno();
     }
     currentPosition += bytesRead;
     if (pActualAmount != nullptr)
         *pActualAmount = bytesRead;
     return Result::ok();
 }
Result beast::RandomAccessFile::nativeSetPosition (FileOffset newPosition) private
Definition at line 492 of file posix_SharedCode.h.
References bassert, currentPosition, fileHandle, isOpen(), and beast::Result::ok().
Referenced by setPosition().
 {
     bassert (isOpen ());
     off_t const actualPosition = lseek (getFD (fileHandle), newPosition, SEEK_SET);
     currentPosition = actualPosition;
     if (actualPosition != newPosition)
     {
         // VFALCO NOTE I dislike return from the middle but
         //             Result::ok() is showing up in the profile
         //
         return getResultForErrno();
     }
     return Result::ok();
 }
Result beast::RandomAccessFile::nativeTruncate () private
Definition at line 562 of file posix_SharedCode.h.
References bassert, currentPosition, fileHandle, flush(), and isOpen().
Referenced by truncate().
 {
     bassert (isOpen ());
     flush();
     return getResultForReturnValue (ftruncate (getFD (fileHandle), (off_t) currentPosition));
 }
Result beast::RandomAccessFile::nativeWrite (const void * data, ByteCount numBytes, ByteCount * pActualAmount = 0) private
Definition at line 536 of file posix_SharedCode.h.
References bassert, fileHandle, isOpen(), beast::Result::ok(), and write().
Referenced by write().
 {
     bassert (isOpen ());
     std::ptrdiff_t bytesWritten = ::write (getFD (fileHandle), data, numBytes);
     // write(3) says that the actual return will be exactly -1 on
     // error, but we will assume anything negative indicates failure.
     //
     if (bytesWritten < 0)
     {
         if (pActualAmount != nullptr)
             *pActualAmount = 0;
         // VFALCO NOTE I dislike return from the middle but
         //             Result::ok() is showing up in the profile
         //
         return getResultForErrno();
     }
     if (pActualAmount != nullptr)
         *pActualAmount = bytesWritten;
     return Result::ok();
 }
Result beast::RandomAccessFile::open (File const & path, Mode mode)
Opens a file object.
The file is opened with the specified permissions. The initial position is set to the beginning of the file.
Note
If a file is already open, it will be closed first.
Parameters
path The path to the file
mode The access permissions
Returns
An indication of the success of the operation.
See Also
Mode
Definition at line 35 of file RandomAccessFile.cpp.
References close(), and nativeOpen().
Referenced by ripple::Validators::SourceFileImp::fetch(), nativeOpen(), and beast::RandomAccessFile_test::testFile().
 {
     close ();
     return nativeOpen (path, mode);
 }
Result beast::RandomAccessFile::read (void * buffer, ByteCount numBytes, ByteCount * pActualAmount = 0)
Read data at the current position.
The caller is responsible for making sure that the memory pointed to by buffer is at least as large as bytesToRead.
Note
The file must have been opened with read permission.
Parameters
buffer The memory to store the incoming data
numBytes The number of bytes to read.
pActualAmount Pointer to store the actual amount read, or nullptr.
Returns
true if all the bytes were read.
Definition at line 64 of file RandomAccessFile.cpp.
References nativeRead().
Referenced by ripple::Validators::SourceFileImp::fetch(), nativeRead(), and beast::RandomAccessFile_test::readRecords().
 {
     return nativeRead (buffer, numBytes, pActualAmount);
 }
Result beast::RandomAccessFile::setPosition (FileOffset newPosition)
Set the current position.
The next read or write will take place at this location.
Parameters
newPosition The byte FileOffset from the beginning of the file to move to.
Returns
true if the operation was successful.
Definition at line 51 of file RandomAccessFile.cpp.
References currentPosition, nativeSetPosition(), and beast::Result::ok().
Referenced by beast::RandomAccessFile_test::readRecords(), and beast::RandomAccessFile_test::writeRecords().
 {
     if (newPosition != currentPosition)
     {
         // VFALCO NOTE I dislike return from the middle but
         //             Result::ok() is showing up in the profile
         //
         return nativeSetPosition (newPosition);
     }
     return Result::ok ();
 }
Result beast::RandomAccessFile::truncate ()
Truncate the file at the current position.
Definition at line 88 of file RandomAccessFile.cpp.
References flush(), nativeTruncate(), and beast::Result::wasOk().
 {
     Result result = flush ();
     if (result.wasOk ())
         result = nativeTruncate ();
     return result;
 }
Result beast::RandomAccessFile::write (const void * data, ByteCount numBytes, ByteCount * pActualAmount = 0)
Write data at the current position.
The current position is advanced past the data written. If data is written past the end of the file, the file size is increased on disk.
The caller is responsible for making sure that the memory pointed to by buffer is at least as large as bytesToWrite.
Note
The file must have been opened with write permission.
Parameters
data A pointer to the data buffer to write to the file.
numBytes The number of bytes to write.
pActualAmount Pointer to store the actual amount written, or nullptr.
Returns
true if all the data was written.
Definition at line 69 of file RandomAccessFile.cpp.
References bassert, currentPosition, nativeWrite(), beast::Result::ok(), and beast::Result::wasOk().
Referenced by nativeWrite(), and beast::RandomAccessFile_test::writeRecords().
 {
     bassert (data != nullptr && ((std::ptrdiff_t) numBytes) >= 0);
     Result result (Result::ok ());
     ByteCount amountWritten = 0;
     result = nativeWrite (data, numBytes, &amountWritten);
     if (result.wasOk ())
         currentPosition += amountWritten;
     if (pActualAmount != nullptr)
         *pActualAmount = amountWritten;
     return result;
 }
Member Data Documentation
FileOffset beast::RandomAccessFile::currentPosition private
Definition at line 194 of file RandomAccessFile.h.
Referenced by getPosition(), nativeClose(), nativeOpen(), nativeRead(), nativeSetPosition(), nativeTruncate(), setPosition(), and write().
File beast::RandomAccessFile::file private
Definition at line 192 of file RandomAccessFile.h.
Referenced by getFile(), nativeClose(), nativeFlush(), and nativeOpen().
void* beast::RandomAccessFile::fileHandle private
Definition at line 193 of file RandomAccessFile.h.
Referenced by isOpen(), nativeClose(), nativeFlush(), nativeOpen(), nativeRead(), nativeSetPosition(), nativeTruncate(), and nativeWrite().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_core/files/RandomAccessFile.h
rippled/src/beast/modules/beast_core/files/RandomAccessFile.cpp
rippled/src/beast/modules/beast_core/native/posix_SharedCode.h
rippled/src/beast/modules/beast_core/native/win32_Files.cpp