rippled: ripple Namespace Reference
ripple Namespace Reference
Namespaces
core
detail
HTTP
NodeStore
PeerFinder
RadixMap
RadMap
Resource
RPC
Script
SiteFiles
TestOverlay
Validators
version
Classes
class CycledSet
class DecayingSample
class KeyCache_test
class MultiSocket_test
class MultiSocketType
class ResolverAsioImpl
class RippleSSLContextImp
class TaggedCache_test
class KeyCache
class MultiSocket
class Resolver
class ResolverAsio
class RippleSSLContext
class TaggedCache
class JsonPropertyStream
class JsonCpp_test
class bignum_error
class CAutoBN_CTX
class CBigNum
class ECDSACanonical_test
class AgedHistory
class Base58
class base_uint
class CryptoIdentifier
class HashMaps
class IdentifierStorage
class IdentifierType
class RandomNumbers
class RippleAccountIDTraits
class RippleAccountPrivateKeyTraits
class RippleAccountPublicKeyTraits
class RippleAssetType
class RippleBookType
class RippleLedgerHashTraits
class RipplePrivateKeyTraits
class RipplePublicKeyTraits
class RipplePublicKeyHashTraits
class SimpleIdentifier
class uint128
class uint160
class uint256
class RippleAsset_test
class DisputedTx
class LedgerConsensusImp
class LedgerConsensus
class Contract
class Database
class DatabaseCon
class SqliteDatabase
class SqliteStatement
class AcceptedLedger
class AcceptedLedgerTx
class DirectoryEntryIterator
class InboundLedger
class InboundLedgersImp
class InboundLedgers
class Ledger_test
class LedgerBase
class Ledger
class LedgerCleanerImp
class LedgerCleaner
class LedgerEntrySetEntry
class LedgerEntrySet
class LedgerHistory
class LedgerHolder
class LedgerMasterImp
class LedgerMaster
class LedgerProposal
class ContinuousLedgerTiming
class BookListeners
class OrderBookDB
class BookDirIterator
class OrderBookIterator
class SerializedValidation
class ApplicationImpBase
class ApplicationImp
class Application
class CollectorManagerImp
class CollectorManager
class FatalErrorReporter_test
class FatalErrorReporter
class IoServicePool
class LoadManagerImp
class LoadManager
class LocalCredentials
class NodeStoreScheduler
class Parameter
class ParameterNode
class ParameterString
class ParameterInt
class RPCHTTPServerImp
class RPCHTTPServer
class AccountItem
class AccountItems
class AccountState
class CanonicalTXSet
class FeaturesImpl
class FeatureSet
class FeatureState
class FeatureTable
class FeeVote
class FeeVoteImpl
class HashRouter
class IHashRouter
class NetworkOPsImp
class ValidationCount
class NetworkOPs
class NicknameState
class Offer
class OrderBook
class ProofOfWork
class ProofOfWorkFactoryImp
class ProofOfWork_test
class ProofOfWorkFactory
class SerializedLedgerEntry
class SerializedTransaction_test
class SerializedTransaction
class ValidationsImp
class Validations
class SqliteBackend
class SqliteFactory
class Pathfinder
class PathRequest
class PathRequests
class PathState
class RippleCalc
class RippleLineCache
class RippleState
class ClusterNodeStatus
class PeerSet
class UniqueNodeListImp
class UniqueNodeList
class RPCHandler
class RPCInternalHandler
class RPCServerHandler
class FetchPack_test
class SHAMap_test
class SHAMap
class SHAMapAddNode
class SHAMapDeltaNode
class SHAMapItem
class SHAMapMissingNode
class SHAMapNode
class SHAMapNode_hash
class GMNEntry
class SHAMapSync_test
class SHAMapSyncFilter
class ConsensusTransSetSF
class AccountStateSF
class TransactionStateSF
class SHAMapTreeNode
class AccountSetTransactor
class ChangeTransactor
class OfferCancelTransactor
class OfferCreateTransactor
class PaymentTransactor
class RegularKeySetTransactor
class Transactor
class TrustSetTransactor
class WalletAddTransactor
class LocalTx
class LocalTxsImp
class LocalTxs
class Transaction
class TransactionAcquire
class TransactionEngine
class TransactionMaster
class TransactionMetaSet
class TxQueueImp
class TxQueue
class TxQueueEntry
class WSConnection
class WSServerHandler
class WSConnectionType
class WSDoorImp
class WSDoor
struct WSServerHandlerBase
class RangeSet_test
class RangeSet
class SyncUnorderedMap
class SyncUnorderedMapType
class Log
class LogFile
class LogPartition
class LogSink
class CountedObjects
class CountedObject
class StringUtilities_test
class UptimeTimer
struct SizedItem
class Config
struct ConfigSection
class Job
class JobQueueImp
class JobQueue
struct JobTypeData
class JobTypeInfo
class JobTypes
class LoadEvent
class LoadFeeTrack
class LoadFeeTrack_test
class LoadFeeTrackImp
class LoadMonitor
class NodeObject
class CBase58Data
class CKey_test
class key_error
class CKey
class RFC1751
class BuildInfo_test
struct BuildInfo
class SField
class HashPrefix
class KnownFormats
class LedgerFormats
struct Protocol
class RippleAddress_test
class RippleIdentifier_test
class RippleAddress
class RippleSystem
class SerializedObject_test
class STObject
class STArray
class SOElement
class SOTemplate
class SerializedType
class STUInt8
class STUInt16
class STUInt32
class STUInt64
class STAmount
class STHash128
class STHash160
class STHash256
class STVariableLength
class STAccount
class STPathElement
class STPath
class STPathSet
class STVector256
class Serializer_test
class Serializer
class SerializerIterator
class STAmount_test
class STParsedJSON
class TxFlag
class TxFormats
struct UptimeTimerAdapter
class HTTPClientSSLContext
class HTTPClientImp
class HTTPClient
class HTTPRequest
class RPCServerImp
class RPCDoorImp
class RPCDoor
class RPCServer
class SNTPClientImp
class SNTPClient
class InfoSub
class RPCParser
struct RPCCallImp
class RPCCall
class RPCSubImp
class RPCSub
class Message
class Overlay
class Peer
struct send_always
struct send_if_pred
struct send_if_not_pred
struct match_peer
struct peer_in_cluster
struct peer_in_set
class MessageStream
struct static_call
struct get_peer_json
class OverlayImpl
class PeerDoorImp
class PeerDoor
class PeerImp
class LegacyPathFind
Typedefs
typedef beast::buffer_view
< std::uint8_t > byte_view
typedef beast::buffer_view
< std::uint8_t const > const_byte_view
using days = std::chrono::duration< int, std::ratio_multiply< std::chrono::hours::period, std::ratio< 24 >>>
using weeks = std::chrono::duration< int, std::ratio_multiply< days::period, std::ratio< 7 >>>
template<class Key , class Value , class Hash = beast::uhash<>, class Pred = std::equal_to<Key>, class Allocator = std::allocator<std::pair<Key const, Value>>>
using unordered_map = std::unordered_map< Key, Value, Hash, Pred, Allocator >
typedef base_uint< 128 > base_uint128
typedef base_uint< 160 > base_uint160
typedef base_uint< 256 > base_uint256
typedef std::vector< unsigned
char > Blob
typedef IdentifierType
< RippleAccountIDTraits > RippleAccountID
typedef IdentifierType
< RippleAccountPrivateKeyTraits > RippleAccountPrivateKey
typedef IdentifierType
< RippleAccountPublicKeyTraits > RippleAccountPublicKey
typedef uint160 RippleCurrency
typedef uint160 RippleIssuer
typedef RippleAssetType< true > RippleAsset
typedef RippleAssetType< false > RippleAssetRef
typedef RippleBookType< true > RippleBook
typedef RippleBookType< false > RippleBookRef
typedef IdentifierType
< RippleLedgerHashTraits > RippleLedgerHash
typedef uint256 LedgerHash
typedef IdentifierType
< RipplePrivateKeyTraits > RipplePrivateKey
typedef IdentifierType
< RipplePublicKeyTraits > RipplePublicKey
typedef IdentifierType
< RipplePublicKeyHashTraits > RipplePublicKeyHash
typedef std::map< uint256,
DisputedTx::pointer >
::value_type u256_lct_pair
typedef std::map< uint160,
LedgerProposal::pointer >
::value_type u160_prop_pair
typedef TaggedCache< uint256,
Blob > NodeCache
typedef TaggedCache< uint256,
SerializedLedgerEntry > SLECache
typedef
RadMap::BasicFullBelowCache
< uint256 > FullBelowCache
typedef SerializedLedgerEntry SLE
typedef std::map< uint160,
SerializedValidation::pointer >
::value_type u160_val_pair
typedef boost::shared_ptr
< ValidationSet > VSpointer
typedef ripple::unordered_map
< uint160,
SerializedValidation::pointer > ValidationSet
typedef std::pair< int, uint160 > currentValidationCount
typedef std::tuple
< std::uint64_t, int, STAmount,
unsigned int > path_LQ_t
typedef std::pair< int, uint160 > candidate_t
typedef std::tuple< uint160,
uint160, uint160 > aciSource
typedef ripple::unordered_map
< aciSource, unsigned int > curIssuerNode
typedef ripple::unordered_map
< aciSource, unsigned int >
::const_iterator curIssuerNodeConstIterator
typedef std::mutex RippleMutex
typedef boost::recursive_mutex RippleRecursiveMutex
typedef boost::recursive_mutex DeprecatedRecursiveMutex
typedef
DeprecatedRecursiveMutex::scoped_lock DeprecatedScopedLock
typedef std::function< bool(void)> CancelCallback
typedef std::map< const
std::string, std::vector
< std::string > > Section
typedef std::uint32_t LedgerIndex
typedef std::uint32_t LedgerSeq
typedef uint256 TxID
typedef std::uint32_t TxSeq
typedef RippleMutex StaticLockType
typedef std::lock_guard
< StaticLockType > StaticScopedLockType
typedef
boost::asio::ip::tcp::socket NativeSocketType
Enumerations
enum LoadType {
LT_InvalidRequest, LT_RequestNoReply, LT_InvalidSignature, LT_UnwantedData,
LT_BadPoW, LT_BadData, LT_RPCInvalid, LT_RPCReference,
LT_RPCException, LT_RPCBurden, LT_NewTrusted, LT_NewTransaction,
LT_NeededData, LT_RequestData, LT_CheapQuery, LT_MAX
}
enum ECDSA { ECDSA::not_strict = 0, ECDSA::strict }
enum { ledgerAcquireTimeoutMillis = 2500, ledgerTimeoutRetriesMax = 10, ledgerBecomeAggressiveThreshold = 6 }
enum LedgerStateParms {
lepNONE = 0, lepCREATE = 1, lepOKAY = 2, lepMISSING = 4,
lepWRONGTYPE = 8, lepCREATED = 16, lepERROR = 32
}
enum TransactionEngineParams {
tapNONE = 0x00, tapNO_CHECK_SIGN = 0x01, tapOPEN_LEDGER = 0x10, tapRETRY = 0x20,
tapADMIN = 0x400
}
enum LedgerEntryAction {
taaNONE, taaCACHED, taaMODIFY, taaDELETE,
taaCREATE
}
enum { fullBelowTargetSize = 524288, fullBelowExpirationSeconds = 600 }
enum PowResult {
powOK = 0, powREUSED = 1, powBADNONCE = 2, powEXPIRED = 3,
powCORRUPT = 4, powTOOEASY = 5
}
enum SHAMapState {
smsModifying = 0, smsImmutable = 1, smsSynching = 2, smsFloating = 3,
smsInvalid = 4
}
enum SHAMapType { smtTRANSACTION = 1, smtSTATE = 2, smtFREE = 3 }
enum SHANodeFormat { snfPREFIX = 1, snfWIRE = 2, snfHASH = 3 }
enum TransStatus {
NEW = 0, INVALID = 1, INCLUDED = 2, CONFLICTED = 3,
COMMITTED = 4, HELD = 5, REMOVED = 6, OBSOLETE = 7,
INCOMPLETE = 8
}
enum { TX_ACQUIRE_TIMEOUT = 250 }
enum LogSeverity {
lsINVALID = -1, lsTRACE = 0, lsDEBUG = 1, lsINFO = 2,
lsWARNING = 3, lsERROR = 4, lsFATAL = 5
}
enum SizedItemName {
siSweepInterval, siValidationsSize, siValidationsAge, siNodeCacheSize,
siNodeCacheAge, siTreeCacheSize, siTreeCacheAge, siSLECacheSize,
siSLECacheAge, siLedgerSize, siLedgerAge, siLedgerFetch,
siHashNodeDBCache, siTxnDBCache, siLgrDBCache
}
enum JobType {
jtINVALID = -1, jtPACK, jtPUBOLDLEDGER, jtVALIDATION_ut,
jtPROOFWORK, jtTRANSACTION_l, jtPROPOSAL_ut, jtLEDGER_DATA,
jtCLIENT, jtRPC, jtUPDATE_PF, jtTRANSACTION,
jtUNL, jtADVANCE, jtPUBLEDGER, jtTXN_DATA,
jtWAL, jtVALIDATION_t, jtWRITE, jtACCEPT,
jtPROPOSAL_t, jtSWEEP, jtNETOP_CLUSTER, jtNETOP_TIMER,
jtADMIN, jtPEER, jtDISK, jtTXN_PROC,
jtOB_SETUP, jtPATH_FIND, jtHO_READ, jtHO_WRITE,
jtGENERIC
}
enum NodeObjectType {
hotUNKNOWN = 0, hotLEDGER = 1, hotTRANSACTION = 2, hotACCOUNT_NODE = 3,
hotTRANSACTION_NODE = 4
}
enum SerializedTypeID {
STI_UNKNOWN = -2, STI_DONE = -1, STI_NOTPRESENT = 0, FIELD,
FIELD, STI_LEDGERENTRY = 10002, STI_VALIDATION = 10003
}
enum LedgerEntryType {
ltINVALID = -1, ltACCOUNT_ROOT = 'a', ltDIR_NODE = 'd', ltGENERATOR_MAP = 'g',
ltRIPPLE_STATE = 'r', ltNICKNAME = 'n', ltOFFER = 'o', ltCONTRACT = 'c',
ltLEDGER_HASHES = 'h', ltFEATURES = 'f', ltFEE_SETTINGS = 's'
}
enum LedgerNameSpace {
spaceAccount = 'a', spaceDirNode = 'd', spaceGenerator = 'g', spaceNickname = 'n',
spaceRipple = 'r', spaceOffer = 'o', spaceOwnerDir = 'O', spaceBookDir = 'B',
spaceContract = 'c', spaceSkipList = 's', spaceFeature = 'f', spaceFee = 'e'
}
enum LedgerSpecificFlags {
lsfPasswordSpent = 0x00010000, lsfRequireDestTag = 0x00020000, lsfRequireAuth = 0x00040000, lsfDisallowXRP = 0x00080000,
lsfDisableMaster = 0x00100000, lsfPassive = 0x00010000, lsfSell = 0x00020000, lsfLowReserve = 0x00010000,
lsfHighReserve = 0x00020000, lsfLowAuth = 0x00040000, lsfHighAuth = 0x00080000, lsfLowNoRipple = 0x00100000,
lsfHighNoRipple = 0x00200000
}
enum SOE_Flags { SOE_INVALID = -1, SOE_REQUIRED = 0, SOE_OPTIONAL = 1, SOE_DEFAULT = 2 }
enum TER {
telLOCAL_ERROR = -399, telBAD_DOMAIN, telBAD_PATH_COUNT, telBAD_PUBLIC_KEY,
telFAILED_PROCESSING, telINSUF_FEE_P, telNO_DST_PARTIAL, temMALFORMED = -299,
temBAD_AMOUNT, temBAD_AUTH_MASTER, temBAD_CURRENCY, temBAD_FEE,
temBAD_EXPIRATION, temBAD_ISSUER, temBAD_LIMIT, temBAD_OFFER,
temBAD_PATH, temBAD_PATH_LOOP, temBAD_PUBLISH, temBAD_TRANSFER_RATE,
temBAD_SEND_XRP_LIMIT, temBAD_SEND_XRP_MAX, temBAD_SEND_XRP_NO_DIRECT, temBAD_SEND_XRP_PARTIAL,
temBAD_SEND_XRP_PATHS, temBAD_SIGNATURE, temBAD_SRC_ACCOUNT, temBAD_SEQUENCE,
temDST_IS_SRC, temDST_NEEDED, temINVALID, temINVALID_FLAG,
temREDUNDANT, temREDUNDANT_SEND_MAX, temRIPPLE_EMPTY, temUNCERTAIN,
temUNKNOWN, tefFAILURE = -199, tefALREADY, tefBAD_ADD_AUTH,
tefBAD_AUTH, tefBAD_CLAIM_ID, tefBAD_GEN_AUTH, tefBAD_LEDGER,
tefCLAIMED, tefCREATED, tefDST_TAG_NEEDED, tefEXCEPTION,
tefGEN_IN_USE, tefINTERNAL, tefNO_AUTH_REQUIRED, tefPAST_SEQ,
tefWRONG_PRIOR, tefMASTER_DISABLED, tefMAX_LEDGER, terRETRY = -99,
terFUNDS_SPENT, terINSUF_FEE_B, terNO_ACCOUNT, terNO_AUTH,
terNO_LINE, terOWNERS, terPRE_SEQ, terLAST,
terNO_RIPPLE, tesSUCCESS = 0, tecCLAIM = 100, tecPATH_PARTIAL = 101,
tecUNFUNDED_ADD = 102, tecUNFUNDED_OFFER = 103, tecUNFUNDED_PAYMENT = 104, tecFAILED_PROCESSING = 105,
tecDIR_FULL = 121, tecINSUF_RESERVE_LINE = 122, tecINSUF_RESERVE_OFFER = 123, tecNO_DST = 124,
tecNO_DST_INSUF_XRP = 125, tecNO_LINE_INSUF_RESERVE = 126, tecNO_LINE_REDUNDANT = 127, tecPATH_DRY = 128,
tecUNFUNDED = 129, tecMASTER_DISABLED = 130, tecNO_REGULAR_KEY = 131, tecOWNERS = 132,
tecNO_ISSUER = 133, tecNO_AUTH = 134, tecNO_LINE = 135
}
enum TxType {
ttINVALID = -1, ttPAYMENT = 0, ttCLAIM = 1, ttWALLET_ADD = 2,
ttACCOUNT_SET = 3, ttPASSWORD_FUND = 4, ttREGULAR_KEY_SET = 5, ttNICKNAME_SET = 6,
ttOFFER_CREATE = 7, ttOFFER_CANCEL = 8, ttCONTRACT = 9, ttCONTRACT_REMOVE = 10,
ttTRUST_SET = 20, ttFEATURE = 100, ttFEE = 101
}
enum error_code_i {
rpcUNKNOWN = -1, rpcSUCCESS = 0, rpcBAD_SYNTAX, rpcJSON_RPC,
rpcFORBIDDEN, rpcLOAD_FAILED, rpcNO_PERMISSION, rpcNO_EVENTS,
rpcNOT_STANDALONE, rpcTOO_BUSY, rpcSLOW_DOWN, rpcHIGH_FEE,
rpcNO_CLOSED, rpcNO_CURRENT, rpcNO_NETWORK, rpcACT_EXISTS,
rpcACT_NOT_FOUND, rpcINSUF_FUNDS, rpcLGR_NOT_FOUND, rpcMASTER_DISABLED,
rpcNICKNAME_MISSING, rpcNO_ACCOUNT, rpcNO_PATH, rpcPASSWD_CHANGED,
rpcSRC_MISSING, rpcSRC_UNCLAIMED, rpcTXN_NOT_FOUND, rpcWRONG_SEED,
rpcINVALID_PARAMS, rpcUNKNOWN_COMMAND, rpcNO_PF_REQUEST, rpcACT_BITCOIN,
rpcACT_MALFORMED, rpcQUALITY_MALFORMED, rpcBAD_BLOB, rpcBAD_FEATURE,
rpcBAD_ISSUER, rpcBAD_MARKET, rpcBAD_SECRET, rpcBAD_SEED,
rpcCOMMAND_MISSING, rpcDST_ACT_MALFORMED, rpcDST_ACT_MISSING, rpcDST_AMT_MALFORMED,
rpcDST_ISR_MALFORMED, rpcGETS_ACT_MALFORMED, rpcGETS_AMT_MALFORMED, rpcHOST_IP_MALFORMED,
rpcLGR_IDXS_INVALID, rpcLGR_IDX_MALFORMED, rpcNICKNAME_MALFORMED, rpcNICKNAME_PERM,
rpcPAYS_ACT_MALFORMED, rpcPAYS_AMT_MALFORMED, rpcPORT_MALFORMED, rpcPUBLIC_MALFORMED,
rpcSRC_ACT_MALFORMED, rpcSRC_ACT_MISSING, rpcSRC_ACT_NOT_FOUND, rpcSRC_AMT_MALFORMED,
rpcSRC_CUR_MALFORMED, rpcSRC_ISR_MALFORMED, rpcATX_DEPRECATED, rpcINTERNAL,
rpcFAIL_GEN_DECRYPT, rpcNOT_IMPL, rpcNOT_SUPPORTED, rpcNO_GEN_DECRYPT
}
enum { defaultAutoFillFeeMultiplier = 10 }
Functions
BEAST_DEFINE_TESTSUITE (KeyCache, common, ripple)
BEAST_DEFINE_TESTSUITE (MultiSocket, common, ripple)
BEAST_DEFINE_TESTSUITE (TaggedCache, common, ripple)
beast::abstract_clock
< std::chrono::seconds > & get_seconds_clock ()
BEAST_DEFINE_TESTSUITE (JsonCpp, json, ripple)
const CBigNum operator+ (const CBigNum &a, const CBigNum &b)
const CBigNum operator- (const CBigNum &a, const CBigNum &b)
const CBigNum operator- (const CBigNum &a)
const CBigNum operator* (const CBigNum &a, const CBigNum &b)
const CBigNum operator/ (const CBigNum &a, const CBigNum &b)
const CBigNum operator% (const CBigNum &a, const CBigNum &b)
const CBigNum operator<< (const CBigNum &a, unsigned int shift)
const CBigNum operator>> (const CBigNum &a, unsigned int shift)
bool operator== (const CBigNum &a, const CBigNum &b)
bool operator!= (const CBigNum &a, const CBigNum &b)
bool operator<= (const CBigNum &a, const CBigNum &b)
bool operator>= (const CBigNum &a, const CBigNum &b)
bool operator< (const CBigNum &a, const CBigNum &b)
bool operator> (const CBigNum &a, const CBigNum &b)
int BN_add_word64 (BIGNUM *a, std::uint64_t w)
int BN_sub_word64 (BIGNUM *a, std::uint64_t w)
int BN_mul_word64 (BIGNUM *a, std::uint64_t w)
std::uint64_t BN_div_word64 (BIGNUM *a, std::uint64_t w)
DH * DH_der_load (const std::string &strDer)
std::string DH_der_gen (int iKeyLength)
bool isCanonicalECDSASig (void const *signature, size_t sigLen, ECDSA mustBeStrict)
bool isCanonicalECDSASig (Blob const &signature, ECDSA mustBeStrict)
bool makeCanonicalECDSASig (void *signature, size_t &sigLen)
template<typename T1 >
uint256 SHA256Hash (const T1 pbegin, const T1 pend)
template<typename T1 , typename T2 >
uint256 SHA256Hash (const T1 p1begin, const T1 p1end, const T2 p2begin, const T2 p2end)
template<typename T1 , typename T2 , typename T3 >
uint256 SHA256Hash (const T1 p1begin, const T1 p1end, const T2 p2begin, const T2 p2end, const T3 p3begin, const T3 p3end)
uint160 Hash160 (Blob const &vch)
template<class FwdIter , class Container >
void hex_to_binary (FwdIter first, FwdIter last, Container &out)
BEAST_DEFINE_TESTSUITE (ECDSACanonical, sslutil, ripple)
int Testuint256AdHoc (std::vector< std::string > vArg)
template<unsigned int BITS>
std::ostream & operator<< (std::ostream &out, const base_uint< BITS > &u)
template<std::size_t PrePadSize, std::size_t Size, std::size_t PostPadSize>
bool operator== (IdentifierStorage< PrePadSize, Size, PostPadSize > const &lhs, IdentifierStorage< PrePadSize, Size, PostPadSize > const &rhs)
template<std::size_t PrePadSize, std::size_t Size, std::size_t PostPadSize>
bool operator!= (IdentifierStorage< PrePadSize, Size, PostPadSize > const &lhs, IdentifierStorage< PrePadSize, Size, PostPadSize > const &rhs)
template<std::size_t PrePadSize, std::size_t Size, std::size_t PostPadSize>
bool operator< (IdentifierStorage< PrePadSize, Size, PostPadSize > const &lhs, IdentifierStorage< PrePadSize, Size, PostPadSize > const &rhs)
template<std::size_t PrePadSize, std::size_t Size, std::size_t PostPadSize>
bool operator> (IdentifierStorage< PrePadSize, Size, PostPadSize > const &lhs, IdentifierStorage< PrePadSize, Size, PostPadSize > const &rhs)
template<std::size_t PrePadSize, std::size_t Size, std::size_t PostPadSize>
bool operator<= (IdentifierStorage< PrePadSize, Size, PostPadSize > const &lhs, IdentifierStorage< PrePadSize, Size, PostPadSize > const &rhs)
template<std::size_t PrePadSize, std::size_t Size, std::size_t PostPadSize>
bool operator>= (IdentifierStorage< PrePadSize, Size, PostPadSize > const &lhs, IdentifierStorage< PrePadSize, Size, PostPadSize > const &rhs)
template<class Hasher , class Traits >
void hash_append (Hasher &h, IdentifierType< Traits > const &id)
template<class Traits >
bool operator== (IdentifierType< Traits > const &lhs, IdentifierType< Traits > const &rhs)
template<class Traits >
bool operator!= (IdentifierType< Traits > const &lhs, IdentifierType< Traits > const &rhs)
template<class Traits >
bool operator< (IdentifierType< Traits > const &lhs, IdentifierType< Traits > const &rhs)
template<class Traits >
bool operator> (IdentifierType< Traits > const &lhs, IdentifierType< Traits > const &rhs)
template<class Traits >
bool operator<= (IdentifierType< Traits > const &lhs, IdentifierType< Traits > const &rhs)
template<class Traits >
bool operator>= (IdentifierType< Traits > const &lhs, IdentifierType< Traits > const &rhs)
template<class Traits >
std::ostream & operator<< (std::ostream &os, IdentifierType< Traits > const &id)
template<class Traits >
std::istream & operator>> (std::istream &is, IdentifierType< Traits > const &id)
template<bool LhsByValue, bool RhsByValue>
int compare (RippleAssetType< LhsByValue > const &lhs, RippleAssetType< RhsByValue > const &rhs)
RippleAsset make_asset (Json::Value json, std::string const &currency_field, std::string const &issuer_field, Json::Value *result)
RippleAssetRef xrp_asset ()
template<bool LhsByValue, bool RhsByValue>
int compare (RippleBookType< LhsByValue > const &lhs, RippleBookType< RhsByValue > const &rhs)
char charHex (int iDigit)
int charUnHex (char cDigit)
template<class Iterator >
std::string strHex (Iterator first, int iSize)
bool operator== (const uint160 &a, std::uint64_t b)
bool operator!= (const uint160 &a, std::uint64_t b)
const uint160 operator^ (const base_uint160 &a, const base_uint160 &b)
const uint160 operator& (const base_uint160 &a, const base_uint160 &b)
const uint160 operator| (const base_uint160 &a, const base_uint160 &b)
bool operator== (const base_uint160 &a, const uint160 &b)
bool operator!= (const base_uint160 &a, const uint160 &b)
const uint160 operator^ (const base_uint160 &a, const uint160 &b)
const uint160 operator& (const base_uint160 &a, const uint160 &b)
const uint160 operator| (const base_uint160 &a, const uint160 &b)
bool operator== (const uint160 &a, const base_uint160 &b)
bool operator!= (const uint160 &a, const base_uint160 &b)
const uint160 operator^ (const uint160 &a, const base_uint160 &b)
const uint160 operator& (const uint160 &a, const base_uint160 &b)
const uint160 operator| (const uint160 &a, const base_uint160 &b)
bool operator== (const uint160 &a, const uint160 &b)
bool operator!= (const uint160 &a, const uint160 &b)
const uint160 operator^ (const uint160 &a, const uint160 &b)
const uint160 operator& (const uint160 &a, const uint160 &b)
const uint160 operator| (const uint160 &a, const uint160 &b)
const std::string strHex (const uint160 &ui)
std::size_t hash_value (const uint160 &)
bool operator== (uint256 const &a, std::uint64_t b)
bool operator!= (uint256 const &a, std::uint64_t b)
const uint256 operator^ (const base_uint256 &a, const base_uint256 &b)
const uint256 operator& (const base_uint256 &a, const base_uint256 &b)
const uint256 operator| (const base_uint256 &a, const base_uint256 &b)
bool operator== (const base_uint256 &a, uint256 const &b)
bool operator!= (const base_uint256 &a, uint256 const &b)
const uint256 operator^ (const base_uint256 &a, uint256 const &b)
const uint256 operator& (const base_uint256 &a, uint256 const &b)
const uint256 operator| (const base_uint256 &a, uint256 const &b)
bool operator== (uint256 const &a, const base_uint256 &b)
bool operator!= (uint256 const &a, const base_uint256 &b)
const uint256 operator^ (uint256 const &a, const base_uint256 &b)
const uint256 operator& (uint256 const &a, const base_uint256 &b)
const uint256 operator| (uint256 const &a, const base_uint256 &b)
bool operator== (uint256 const &a, uint256 const &b)
bool operator!= (uint256 const &a, uint256 const &b)
const uint256 operator^ (uint256 const &a, uint256 const &b)
const uint256 operator& (uint256 const &a, uint256 const &b)
const uint256 operator| (uint256 const &a, uint256 const &b)
std::size_t hash_value (uint256 const &)
BEAST_DEFINE_TESTSUITE (RippleAsset, types, ripple)
boost::shared_ptr
< LedgerConsensus > make_LedgerConsensus (LedgerConsensus::clock_type &clock, LocalTxs &localtx, LedgerHash const &prevLCLHash, Ledger::ref previousLedger, std::uint32_t closeTime, FeeVote &feeVote)
static int SqliteWALHook (void *s, sqlite3 *dbCon, const char *dbName, int walSize)
static void LADispatch (Job &job, InboundLedger::pointer la, std::vector< std::function< void(InboundLedger::pointer)> > trig)
static void stateItemTagAppender (Json::Value &value, SHAMapItem::ref smi)
static void stateItemFullAppender (Json::Value &value, SLE::ref sle)
static void visitHelper (std::function< void(SLE::ref)> &function, SHAMapItem::ref item)
BEAST_DEFINE_TESTSUITE (Ledger, ripple_app, ripple)
LedgerStateParms operator| (const LedgerStateParms &l1, const LedgerStateParms &l2)
LedgerStateParms operator& (const LedgerStateParms &l1, const LedgerStateParms &l2)
LedgerEntrySet::iterator range_begin (LedgerEntrySet &x)
LedgerEntrySet::iterator range_end (LedgerEntrySet &x)
static void updateHelper (SLE::ref entry, boost::unordered_set< uint256 > &seen, ripple::unordered_map< RippleAsset, std::vector< OrderBook::pointer > > &destMap, ripple::unordered_map< RippleAsset, std::vector< OrderBook::pointer > > &sourceMap, boost::unordered_set< RippleAsset > &XRPBooks, int &books)
static int const MAJORITY_FRACTION (200)
bool serverOkay (std::string &reason)
static std::vector< std::string > getSchema (DatabaseCon *dbc, const std::string &dbName)
static bool schemaHas (DatabaseCon *dbc, const std::string &dbName, int line, const std::string &content)
static void addTxnSeqField ()
std::unique_ptr< Application > make_Application ()
Application & getApp ()
BEAST_DEFINE_TESTSUITE_MANUAL (FatalErrorReporter, ripple_app, ripple)
void setupServer ()
void startServer ()
void printHelp (const po::options_description &desc)
static void setupConfigForUnitTests (Config *config)
static int runUnitTests (std::string pattern, std::string format)
int run (int argc, char **argv)
std::unique_ptr< FeatureTable > make_FeatureTable (std::chrono::seconds majorityTime, int majorityFraction, beast::Journal journal)
std::unique_ptr< FeeVote > make_FeeVote (std::uint64_t targetBaseFee, std::uint32_t targetReserveBase, std::uint32_t targetReserveIncrement, beast::Journal journal)
static void fpAppender (protocol::TMGetObjectByHash *reply, std::uint32_t ledgerSeq, const uint256 &hash, const Blob &blob)
static uint256 getSHA512Half (const std::vector< uint256 > &vec)
BEAST_DEFINE_TESTSUITE_MANUAL (ProofOfWork, ripple_app, ripple)
bool isMemoOkay (STObject const &st)
bool isAccountFieldOkay (STObject const &st)
bool passesLocalChecks (STObject const &st, std::string &reason)
bool passesLocalChecks (STObject const &st)
BEAST_DEFINE_TESTSUITE (SerializedTransaction, ripple_app, ripple)
std::unique_ptr
< NodeStore::Factory > make_SqliteFactory ()
static bool bQualityCmp (const path_LQ_t &a, const path_LQ_t &b)
static bool candCmp (std::uint32_t seq, const candidate_t &first, const candidate_t &second)
boost::unordered_set< uint160 > usAccountSourceCurrencies (const RippleAddress &raAccountID, RippleLineCache::ref lrCache, bool includeXRP)
boost::unordered_set< uint160 > usAccountDestCurrencies (const RippleAddress &raAccountID, RippleLineCache::ref lrCache, bool includeXRP)
static std::string const get_milli_diff (boost::posix_time::ptime const &after, boost::posix_time::ptime const &before)
static std::string const get_milli_diff (boost::posix_time::ptime const &before)
std::size_t hash_value (const aciSource &asValue)
BEAST_DEFINE_TESTSUITE (FetchPack, ripple_app, ripple)
std::size_t hash_value (const SHAMapNode &mn)
BEAST_DEFINE_TESTSUITE (SHAMap, ripple_app, ripple)
std::ostream & operator<< (std::ostream &out, const SHAMapMissingNode &mn)
std::ostream & operator<< (std::ostream &out, const SHAMapNode &node)
static void addFPtoList (std::list< SHAMap::fetchPackEntry_t > &list, const uint256 &hash, const Blob &blob)
BEAST_DEFINE_TESTSUITE (SHAMapSync, ripple_app, ripple)
static void TACompletionHandler (uint256 hash, SHAMap::pointer map)
TransactionEngineParams operator| (const TransactionEngineParams &l1, const TransactionEngineParams &l2)
TransactionEngineParams operator& (const TransactionEngineParams &l1, const TransactionEngineParams &l2)
static void addIfUnique (std::vector< RippleAddress > &vector, const RippleAddress &address)
static bool compare (const STObject &o1, const STObject &o2)
std::uint32_t min (std::uint32_t x, std::uint32_t y)
std::uint32_t max (std::uint32_t x, std::uint32_t y)
BEAST_DEFINE_TESTSUITE (RangeSet, ripple_basics, ripple)
template<typename Object >
double timedDestroy (Object &object)
template<typename PartitionKey , typename Object >
void logTimedDestroy (Object &object, beast::String objectDescription, double thresholdSeconds=1)
template<typename Function >
void logTimedCall (beast::Journal::Stream stream, beast::String description, char const *fileName, int lineNumber, Function f, double thresholdSeconds=1)
Section ParseSection (const std::string &strInput, const bool bTrim)
void SectionEntriesPrint (std::vector< std::string > *vspEntries, const std::string &strSection)
void SectionPrint (Section secInput)
Section::mapped_type * SectionEntries (Section &secSource, const std::string &strSection)
int SectionCount (Section &secSource, const std::string &strSection)
bool SectionSingleB (Section &secSource, const std::string &strSection, std::string &strValue)
beast::StringPairArray parseKeyValueSection (Section &secSource, beast::String const &strSection)
template<typename X , typename Y >
std::enable_if_t
< (std::is_integral< X >
::value||std::is_enum< X >
::value)&&(std::is_integral< Y >
::value||std::is_enum< Y >
::value), bool > is_bit_set (X const x, Y const y)
std::string strprintf (const char *format,...)
int strUnHex (std::string &strDst, const std::string &strSrc)
std::pair< Blob, bool > strUnHex (const std::string &strSrc)
uint64_t uintFromHex (const std::string &strSrc)
Blob strCopy (const std::string &strSrc)
std::string strCopy (Blob const &vucSrc)
std::string urlEncode (const std::string &strSrc)
bool parseIpPort (const std::string &strSource, std::string &strIP, int &iPort)
bool parseUrl (const std::string &strUrl, std::string &strScheme, std::string &strDomain, int &iPort, std::string &strPath)
bool parseQuality (const std::string &strSource, std::uint32_t &uQuality)
beast::StringPairArray parseDelimitedKeyValueString (beast::String parameters, beast::beast_wchar delimiter)
BEAST_DEFINE_TESTSUITE (StringUtilities, ripple_basics, ripple)
template<class Iterator >
std::string strJoin (Iterator first, Iterator last, std::string strSeperator)
const std::string strHex (const std::string &strSrc)
std::string strHex (Blob const &vucData)
std::string strHex (const std::uint64_t uiHost)
static std::string sqlEscape (const std::string &strSrc)
static std::string sqlEscape (Blob const &vecSrc)
std::string strGetEnv (const std::string &strKey)
bool HaveSustain ()
std::string DoSustain (std::string)
std::string StopSustain ()
void setCallingThreadName (const char *)
boost::posix_time::ptime ptEpoch ()
int iToSeconds (boost::posix_time::ptime ptWhen)
boost::posix_time::ptime ptFromSeconds (int iSeconds)
uint64_t utFromSeconds (int iSeconds)
template<class OutputSequence , class InputIterator >
void parseAddresses (OutputSequence &out, InputIterator first, InputIterator last, beast::Journal::Stream stream=beast::Journal::Stream())
Config & getConfig ()
std::unique_ptr< JobQueue > make_JobQueue (beast::insight::Collector::ptr const &collector, beast::Stoppable &parent, beast::Journal journal)
BEAST_DEFINE_TESTSUITE (LoadFeeTrack, ripple_core, ripple)
std::size_t hash_value (const CBase58Data &b58)
BEAST_DEFINE_TESTSUITE (CKey, ripple_data, ripple)
static BIGNUM * makeHash (const RippleAddress &pubGen, int seq, BIGNUM *order)
static ECIES_HMAC_TYPE makeHMAC (const ECIES_HMAC_KEY_TYPE &secret, Blob const &data)
bool checkECIES (void)
BEAST_DEFINE_TESTSUITE (BuildInfo, ripple_data, ripple)
FIELD (FirstLedgerSequence, UINT32, 26) static int initFields()
BEAST_DEFINE_TESTSUITE (RippleAddress, ripple_data, ripple)
BEAST_DEFINE_TESTSUITE (RippleIdentifier, ripple_data, ripple)
BEAST_DEFINE_TESTSUITE (SerializedObject, ripple_data, ripple)
template<typename T , typename U >
static T range_check_cast (const U &value, const T &minimum, const T &maximum)
STObject::iterator range_begin (STObject &x)
STObject::iterator range_end (STObject &x)
STArray::iterator range_begin (STArray &x)
STArray::iterator range_end (STArray &x)
static const uint160 u160_zero (0)
static const uint160 u160_one (1)
static const uint160 & get_u160_zero ()
static const uint160 & get_u160_one ()
SerializedType * new_clone (const SerializedType &s)
void delete_clone (const SerializedType *s)
std::ostream & operator<< (std::ostream &out, const SerializedType &t)
std::vector< STPathElement >
::iterator range_begin (STPath &x)
std::vector< STPathElement >
::iterator range_end (STPath &x)
std::vector< STPathElement >
::const_iterator range_begin (const STPath &x)
std::vector< STPathElement >
::const_iterator range_end (const STPath &x)
std::vector< STPath >::iterator range_begin (STPathSet &x)
std::vector< STPath >::iterator range_end (STPathSet &x)
std::vector< STPath >
::const_iterator range_begin (const STPathSet &x)
std::vector< STPath >
::const_iterator range_end (const STPathSet &x)
BEAST_DEFINE_TESTSUITE (Serializer, ripple_data, ripple)
STAmount operator+ (const STAmount &v1, const STAmount &v2)
STAmount operator- (const STAmount &v1, const STAmount &v2)
BEAST_DEFINE_TESTSUITE (STAmount, ripple_data, ripple)
bool transResultInfo (TER terCode, std::string &strToken, std::string &strHuman)
std::string transToken (TER terCode)
std::string transHuman (TER terCode)
static bool isSwitchChar (char c)
Json::Value rpcError (int iError, Json::Value jvResult)
bool isRpcError (Json::Value jvResult)
Json::Value const & logRPCError (Json::Value const &json)
std::string gFormatStr ("v1")
std::string FormatFullVersion ()
Json::Value JSONRPCError (int code, const std::string &message)
std::string createHTTPPost (std::string const &strHost, std::string const &strPath, std::string const &strMsg, std::map< std::string, std::string > const &mapRequestHeaders)
std::string getHTTPHeaderTimestamp ()
std::string HTTPReply (int nStatus, const std::string &strMsg)
int ReadHTTPStatus (std::basic_istream< char > &stream)
int ReadHTTPHeader (std::basic_istream< char > &stream, std::map< std::string, std::string > &mapHeadersRet)
int ReadHTTP (std::basic_istream< char > &stream, std::map< std::string, std::string > &mapHeadersRet, std::string &strMessageRet)
std::string DecodeBase64 (std::string s)
bool HTTPAuthorized (const std::map< std::string, std::string > &mapHeaders)
std::string JSONRPCRequest (const std::string &strMethod, const Json::Value &params, const Json::Value &id)
std::string JSONRPCReply (const Json::Value &result, const Json::Value &error, const Json::Value &id)
void ErrorReply (std::ostream &stream, const Json::Value &objError, const Json::Value &id)
std::unique_ptr< Overlay > make_Overlay (beast::Stoppable &parent, Resource::Manager &resourceManager, SiteFiles::Manager &siteFiles, beast::File const &pathToDbFileOrDirectory, Resolver &resolver, boost::asio::io_service &io_service, boost::asio::ssl::context &ssl_context)
template<typename Predicate >
send_if_pred< Predicate > send_if (Message::pointer const &m, Predicate const &f)
template<typename Predicate >
send_if_not_pred< Predicate > send_if_not (Message::pointer const &m, Predicate const &f)
std::unique_ptr< PeerDoor > make_PeerDoor (PeerDoor::Kind kind, OverlayImpl &overlay, std::string const &ip, int port, boost::asio::io_service &io_service)
std::string to_string (Peer const &peer)
std::ostream & operator<< (std::ostream &os, Peer const &peer)
std::string to_string (Peer const *peer)
std::ostream & operator<< (std::ostream &os, Peer const *peer)
std::string to_string (PeerImp const &peer)
std::ostream & operator<< (std::ostream &os, PeerImp const &peer)
std::string to_string (PeerImp const *peer)
std::ostream & operator<< (std::ostream &os, PeerImp const *peer)
static void offerAdder (Json::Value &jvLines, SLE::ref offer)
template<class UnsignedInteger >
bool is_xrp (UnsignedInteger const &value)
template<class UnsignedInteger >
bool is_not_xrp (UnsignedInteger const &value)
uint160 const & xrp_issuer ()
uint160 const & xrp_currency ()
uint160 const & neutral_issuer ()
static void textTime (std::string &text, int &seconds, const char *unitName, int unitVal)
template<bool LhsByValue, bool RhsByValue>
bool operator== (RippleAssetType< LhsByValue > const &lhs, RippleAssetType< RhsByValue > const &rhs)
template<bool LhsByValue, bool RhsByValue>
bool operator!= (RippleAssetType< LhsByValue > const &lhs, RippleAssetType< RhsByValue > const &rhs)
template<bool LhsByValue, bool RhsByValue>
bool operator< (RippleAssetType< LhsByValue > const &lhs, RippleAssetType< RhsByValue > const &rhs)
template<bool LhsByValue, bool RhsByValue>
bool operator> (RippleAssetType< LhsByValue > const &lhs, RippleAssetType< RhsByValue > const &rhs)
template<bool LhsByValue, bool RhsByValue>
bool operator>= (RippleAssetType< LhsByValue > const &lhs, RippleAssetType< RhsByValue > const &rhs)
template<bool LhsByValue, bool RhsByValue>
bool operator<= (RippleAssetType< LhsByValue > const &lhs, RippleAssetType< RhsByValue > const &rhs)
template<bool LhsByValue, bool RhsByValue>
bool operator== (RippleBookType< LhsByValue > const &lhs, RippleBookType< RhsByValue > const &rhs)
template<bool LhsByValue, bool RhsByValue>
bool operator!= (RippleBookType< LhsByValue > const &lhs, RippleBookType< RhsByValue > const &rhs)
template<bool LhsByValue, bool RhsByValue>
bool operator< (RippleBookType< LhsByValue > const &lhs, RippleBookType< RhsByValue > const &rhs)
template<bool LhsByValue, bool RhsByValue>
bool operator> (RippleBookType< LhsByValue > const &lhs, RippleBookType< RhsByValue > const &rhs)
template<bool LhsByValue, bool RhsByValue>
bool operator>= (RippleBookType< LhsByValue > const &lhs, RippleBookType< RhsByValue > const &rhs)
template<bool LhsByValue, bool RhsByValue>
bool operator<= (RippleBookType< LhsByValue > const &lhs, RippleBookType< RhsByValue > const &rhs)
Variables
const char * TxnDBInit []
int TxnDBCount = NUMBER (TxnDBInit)
const char * LedgerDBInit []
int LedgerDBCount = NUMBER (LedgerDBInit)
const char * RpcDBInit []
int RpcDBCount = NUMBER (RpcDBInit)
const char * WalletDBInit []
int WalletDBCount = NUMBER (WalletDBInit)
const std::uint32_t vfFullyCanonicalSig = 0x80000000
static bool volatile doShutdown = false
static const char * s_nodeStoreDBInit []
static int s_nodeStoreDBCount = NUMBER (s_nodeStoreDBInit)
static const SHAMapItem::pointer no_item
bool SMN_j = SHAMapNode::ClassInit ()
static const uint256 uZero
const int DOMAIN_BYTES_MAX = 256
const int PUBLIC_BYTES_MAX = 33
const int SYSTEM_PEER_PORT = 6561
const int SYSTEM_WEBSOCKET_PORT = 6562
const int SYSTEM_WEBSOCKET_PUBLIC_PORT = 6563
SField sfInvalid (-1)
SField sfGeneric (0)
SField sfLedgerEntry (STI_LEDGERENTRY, 1,"LedgerEntry")
SField sfTransaction (STI_TRANSACTION, 1,"Transaction")
SField sfValidation (STI_VALIDATION, 1,"Validation")
SField sfHash (STI_HASH256, 257,"hash")
SField sfIndex (STI_HASH256, 258,"index")
static const int f = initFields ()
static StaticLockType s_lock
static ripple::unordered_map
< Blob, std::string > rncMap
const STAmount saZero (CURRENCY_ONE, ACCOUNT_ONE, 0)
const STAmount saOne (CURRENCY_ONE, ACCOUNT_ONE, 1)
const std::uint32_t tfFullyCanonicalSig = 0x80000000
const std::uint32_t tfUniversal = tfFullyCanonicalSig
const std::uint32_t tfUniversalMask = ~ tfUniversal
const std::uint32_t tfOptionalDestTag = 0x00020000
const std::uint32_t tfRequireAuth = 0x00040000
const std::uint32_t tfOptionalAuth = 0x00080000
const std::uint32_t tfDisallowXRP = 0x00100000
const std::uint32_t tfAllowXRP = 0x00200000
const std::uint32_t tfAccountSetMask
const std::uint32_t asfRequireDest = 1
const std::uint32_t asfRequireAuth = 2
const std::uint32_t asfDisallowXRP = 3
const std::uint32_t asfDisableMaster = 4
const std::uint32_t asfAccountTxnID = 5
const std::uint32_t tfPassive = 0x00010000
const std::uint32_t tfImmediateOrCancel = 0x00020000
const std::uint32_t tfFillOrKill = 0x00040000
const std::uint32_t tfSell = 0x00080000
const std::uint32_t tfOfferCreateMask = ~ (tfUniversal | tfPassive | tfImmediateOrCancel | tfFillOrKill | tfSell)
const std::uint32_t tfNoRippleDirect = 0x00010000
const std::uint32_t tfPartialPayment = 0x00020000
const std::uint32_t tfLimitQuality = 0x00040000
const std::uint32_t tfPaymentMask = ~ (tfUniversal | tfPartialPayment | tfLimitQuality | tfNoRippleDirect)
const std::uint32_t tfSetfAuth = 0x00010000
const std::uint32_t tfSetNoRipple = 0x00020000
const std::uint32_t tfClearNoRipple = 0x00040000
const std::uint32_t tfTrustSetMask = ~ (tfUniversal | tfSetfAuth | tfSetNoRipple | tfClearNoRipple)
static uint8_t SNTPQueryData [48]
unsigned int const gMaxHTTPHeaderSize = 0x02000000
Detailed Description
Provides a template based peer to peer network simulator.
A TestOverlay::Network simulates an entire peer to peer network. It provides peer connectivity and message passing services, while allowing domain specific customization through user provided types.
This system is designed to allow business logic to be exercised in unit tests, using a simulated large scale network.
ChosenValidators (formerly known as UNL)
Motivation:
To protect the integrity of the shared ledger data structure, Validators independently sign LedgerHash objects with their RipplePublicKey. These signed Validations are propagated through the peer to peer network so that other nodes may inspect them. Every peer and client on the network gains confidence in a ledger and its associated chain of previous ledgers by maintaining a suitably sized list of Validator public keys that it trusts.
The most important factors in choosing Validators for a ChosenValidators list (the name we will use to designate such a list) are the following:
- That different Validators are not controlled by one entity
- That each Validator participates in a majority of ledgers
- That a Validator does not sign ledgers which fail consensus
This module maintains ChosenValidators list. The list is built from a set of independent Source objects, which may come from the configuration file, a separate file, a URL from some trusted domain, or from the network itself.
In order that rippled administrators may publish their ChosenValidators list at a URL on a trusted domain that they own, this module compiles statistics on ledgers signed by validators and stores them in a database. From this database reports and alerts may be generated so that up-to-date information about the health of the set of ChosenValidators is always availabile.
In addition to the automated statistics provided by the module, it is expected that organizations and meta-organizations will form from stakeholders such as gateways who publish their own lists and provide "best practices" to further refine the quality of validators placed into ChosenValidators list.
Unorganized Notes:
David: Maybe OC should have a URL that you can query to get the latest list of URI's for OC-approved organzations that publish lists of validators. The server and client can ship with that master trust URL and also the list of URI's at the time it's released, in case for some reason it can't pull from OC. That would make the default installation safe even against major changes in the organizations that publish validator lists.
The difference is that if an organization that provides lists of validators goes rogue, administrators don't have to act.
TODO: Write up from end-user perspective on the deployment and administration of this feature, on the wiki. "DRAFT" or "PROPOSE" to mark it as provisional. Template: https://ripple.com/wiki/Federation_protocol
What to do if you're a publisher of ValidatorList
What to do if you're a rippled administrator
Overview of how ChosenValidators works
Goals: Make default configuration of rippled secure. Ship with TrustedUriList Also have a preset RankedValidators Eliminate administrative burden of maintaining Produce the ChosenValidators list. Allow quantitative analysis of network health.
What determines that a validator is good?
Are they present (i.e. sending validations)
Are they on the consensus ledger
What percentage of consensus rounds do they participate in
Are they stalling consensus Measurements of constructive/destructive behavior is calculated in units of percentage of ledgers for which the behavior is measured.
What we want from the unique node list:
Some number of trusted roots (known by domain) probably organizations whose job is to provide a list of validators
We imagine the IRGA for example would establish some group whose job is to maintain a list of validators. There would be a public list of criteria that they would use to vet the validator. Things like: Not anonymous registered business Physical location Agree not to cease operations without notice / arbitrarily Responsive to complaints
Identifiable jurisdiction Homogeneity in the jurisdiction is a business risk If all validators are in the same jurisdiction this is a business risk
OpenCoin sets criteria for the organizations
Rippled will ship with a list of trusted root "certificates" In other words this is a list of trusted domains from which the software can contact each trusted root and retrieve a list of "good" validators and then do something with that information
All the validation information would be public, including the broadcast messages.
The goal is to easily identify bad actors and assess network health Malicious intent Or, just hardware problems (faulty drive or memory)
Callback for filtering SHAMap during sync.
Typedef Documentation
typedef std::tuple<uint160, uint160, uint160> ripple::aciSource
Definition at line 26 of file PathState.h.
typedef base_uint<128> ripple::base_uint128
Definition at line 475 of file base_uint.h.
typedef base_uint<160> ripple::base_uint160
Definition at line 476 of file base_uint.h.
typedef base_uint<256> ripple::base_uint256
Definition at line 477 of file base_uint.h.
typedef std::vector<unsigned char> ripple::Blob
Storage for linear binary data. Blocks of binary data appear often in various idioms and structures.
Definition at line 30 of file Blob.h.
typedef beast::buffer_view<std::uint8_t> ripple::byte_view
Definition at line 29 of file byte_view.h.
typedef std::function<bool(void)> ripple::CancelCallback
A callback used to check for canceling an operation.
Definition at line 37 of file BasicTypes.h.
typedef std::pair<int, uint160> ripple::candidate_t
Definition at line 85 of file Pathfinder.cpp.
typedef beast::buffer_view<std::uint8_t const> ripple::const_byte_view
Definition at line 30 of file byte_view.h.
typedef ripple::unordered_map<aciSource, unsigned int> ripple::curIssuerNode
Definition at line 27 of file PathState.h.
typedef ripple::unordered_map<aciSource, unsigned int>::const_iterator ripple::curIssuerNodeConstIterator
Definition at line 28 of file PathState.h.
typedef std::pair<int, uint160> ripple::currentValidationCount
Definition at line 27 of file Validations.h.
using ripple::days = typedef std::chrono::duration <int, std::ratio_multiply<std::chrono::hours::period, std::ratio<24>>>
Definition at line 31 of file seconds_clock.h.
typedef boost::recursive_mutex ripple::DeprecatedRecursiveMutex
Definition at line 31 of file BasicTypes.h.
typedef DeprecatedRecursiveMutex::scoped_lock ripple::DeprecatedScopedLock
Definition at line 32 of file BasicTypes.h.
typedef RadMap::BasicFullBelowCache<uint256> ripple::FullBelowCache
Definition at line 28 of file FullBelowCache.h.
typedef uint256 ripple::LedgerHash
Definition at line 48 of file RippleLedgerHash.h.
typedef std::uint32_t ripple::LedgerIndex
A ledger index.
Definition at line 51 of file Protocol.h.
typedef std::uint32_t ripple::LedgerSeq
Definition at line 53 of file Protocol.h.
typedef boost::asio::ip::tcp::socket ripple::NativeSocketType
Definition at line 40 of file PeerImp.h.
typedef TaggedCache<uint256, Blob> ripple::NodeCache
Definition at line 53 of file Application.h.
typedef std::tuple<std::uint64_t, int, STAmount, unsigned int> ripple::path_LQ_t
Definition at line 64 of file Pathfinder.cpp.
typedef IdentifierType<RippleAccountIDTraits> ripple::RippleAccountID
Definition at line 61 of file RippleAccountID.h.
typedef IdentifierType<RippleAccountPrivateKeyTraits> ripple::RippleAccountPrivateKey
Definition at line 41 of file RippleAccountPrivateKey.h.
typedef IdentifierType<RippleAccountPublicKeyTraits> ripple::RippleAccountPublicKey
Definition at line 41 of file RippleAccountPublicKey.h.
typedef RippleAssetType<true> ripple::RippleAsset
Definition at line 171 of file RippleAssets.h.
typedef RippleAssetType<false> ripple::RippleAssetRef
Definition at line 172 of file RippleAssets.h.
typedef RippleBookType<true> ripple::RippleBook
Definition at line 314 of file RippleAssets.h.
typedef RippleBookType<false> ripple::RippleBookRef
Definition at line 315 of file RippleAssets.h.
typedef uint160 ripple::RippleCurrency
Identifies a currency in the payment network. Currencies are associated with issuers.
See Also
RippleIssuer
Definition at line 32 of file RippleAssets.h.
typedef uint160 ripple::RippleIssuer
Identifies the account of a currency issuer. Currency IOUs are issued by account holders.
See Also
RippleCurrency
Definition at line 38 of file RippleAssets.h.
typedef IdentifierType<RippleLedgerHashTraits> ripple::RippleLedgerHash
A ledger hash.
Definition at line 45 of file RippleLedgerHash.h.
typedef std::mutex ripple::RippleMutex
Synchronization primitives. This lets us switch between tracked and untracked mutexes.
Definition at line 28 of file BasicTypes.h.
typedef IdentifierType<RipplePrivateKeyTraits> ripple::RipplePrivateKey
Definition at line 41 of file RipplePrivateKey.h.
typedef IdentifierType<RipplePublicKeyTraits> ripple::RipplePublicKey
Definition at line 42 of file RipplePublicKey.h.
typedef IdentifierType<RipplePublicKeyHashTraits> ripple::RipplePublicKeyHash
A container holding the 160-bit hash of the 257-bit public key.
Definition at line 42 of file RipplePublicKeyHash.h.
typedef boost::recursive_mutex ripple::RippleRecursiveMutex
Definition at line 29 of file BasicTypes.h.
typedef std::map<const std::string, std::vector<std::string> > ripple::Section
Definition at line 28 of file IniFile.h.
typedef SerializedLedgerEntry ripple::SLE
Definition at line 121 of file SerializedLedger.h.
typedef TaggedCache<uint256, SerializedLedgerEntry> ripple::SLECache
Definition at line 56 of file Application.h.
typedef RippleMutex ripple::StaticLockType
Definition at line 311 of file RippleAddress.cpp.
typedef std::lock_guard<StaticLockType> ripple::StaticScopedLockType
Definition at line 312 of file RippleAddress.cpp.
typedef uint256 ripple::TxID
A transaction identifier.
Definition at line 58 of file Protocol.h.
typedef std::uint32_t ripple::TxSeq
A transaction index.
Definition at line 62 of file Protocol.h.
typedef std::map< uint160, LedgerProposal::pointer >::value_type ripple::u160_prop_pair
Definition at line 86 of file DisputedTx.h.
typedef std::map<uint160, SerializedValidation::pointer>::value_type ripple::u160_val_pair
Definition at line 22 of file Validations.cpp.
typedef std::map< uint256, DisputedTx::pointer >::value_type ripple::u256_lct_pair
Definition at line 85 of file DisputedTx.h.
template<class Key , class Value , class Hash = beast::uhash<>, class Pred = std::equal_to<Key>, class Allocator = std::allocator<std::pair<Key const, Value>>> using ripple::unordered_map = typedef std::unordered_map <Key, Value, Hash, Pred, Allocator>
Definition at line 33 of file UnorderedMap.h.
typedef ripple::unordered_map<uint160, SerializedValidation::pointer> ripple::ValidationSet
Definition at line 26 of file Validations.h.
typedef boost::shared_ptr<ValidationSet> ripple::VSpointer
Definition at line 27 of file Validations.cpp.
using ripple::weeks = typedef std::chrono::duration <int, std::ratio_multiply<days::period, std::ratio<7>>>
Definition at line 34 of file seconds_clock.h.
Enumeration Type Documentation
anonymous enum
Enumerator
defaultAutoFillFeeMultiplier
Definition at line 78 of file TransactionSign.cpp.
 {
     defaultAutoFillFeeMultiplier        = 10
 };
anonymous enum
Enumerator
ledgerAcquireTimeoutMillis
ledgerTimeoutRetriesMax
ledgerBecomeAggressiveThreshold
Definition at line 27 of file InboundLedger.cpp.
 {
     // millisecond for each ledger timeout
     ledgerAcquireTimeoutMillis = 2500
     // how many timeouts before we giveup
     ,ledgerTimeoutRetriesMax = 10
     // how many timeouts before we get aggressive
     ,ledgerBecomeAggressiveThreshold = 6
 };
anonymous enum
Enumerator
fullBelowTargetSize
fullBelowExpirationSeconds
Definition at line 25 of file Tuning.h.
 {
     fullBelowTargetSize = 524288
     ,fullBelowExpirationSeconds = 600
 };
anonymous enum
Enumerator
TX_ACQUIRE_TIMEOUT
Definition at line 27 of file TransactionAcquire.cpp.
 {
     // VFALCO NOTE This should be a std::chrono::duration constant.
     // TODO Document this. Is it seconds? Milliseconds? WTF?
     TX_ACQUIRE_TIMEOUT = 250
 };
enum ripple::ECDSA strong
Enumerator
not_strict
strict
Definition at line 25 of file ECDSACanonical.h.
 {
     not_strict = 0,
     strict
 };
enum ripple::error_code_i
Enumerator
rpcUNKNOWN
rpcSUCCESS
rpcBAD_SYNTAX
rpcJSON_RPC
rpcFORBIDDEN
rpcLOAD_FAILED
rpcNO_PERMISSION
rpcNO_EVENTS
rpcNOT_STANDALONE
rpcTOO_BUSY
rpcSLOW_DOWN
rpcHIGH_FEE
rpcNO_CLOSED
rpcNO_CURRENT
rpcNO_NETWORK
rpcACT_EXISTS
rpcACT_NOT_FOUND
rpcINSUF_FUNDS
rpcLGR_NOT_FOUND
rpcMASTER_DISABLED
rpcNICKNAME_MISSING
rpcNO_ACCOUNT
rpcNO_PATH
rpcPASSWD_CHANGED
rpcSRC_MISSING
rpcSRC_UNCLAIMED
rpcTXN_NOT_FOUND
rpcWRONG_SEED
rpcINVALID_PARAMS
rpcUNKNOWN_COMMAND
rpcNO_PF_REQUEST
rpcACT_BITCOIN
rpcACT_MALFORMED
rpcQUALITY_MALFORMED
rpcBAD_BLOB
rpcBAD_FEATURE
rpcBAD_ISSUER
rpcBAD_MARKET
rpcBAD_SECRET
rpcBAD_SEED
rpcCOMMAND_MISSING
rpcDST_ACT_MALFORMED
rpcDST_ACT_MISSING
rpcDST_AMT_MALFORMED
rpcDST_ISR_MALFORMED
rpcGETS_ACT_MALFORMED
rpcGETS_AMT_MALFORMED
rpcHOST_IP_MALFORMED
rpcLGR_IDXS_INVALID
rpcLGR_IDX_MALFORMED
rpcNICKNAME_MALFORMED
rpcNICKNAME_PERM
rpcPAYS_ACT_MALFORMED
rpcPAYS_AMT_MALFORMED
rpcPORT_MALFORMED
rpcPUBLIC_MALFORMED
rpcSRC_ACT_MALFORMED
rpcSRC_ACT_MISSING
rpcSRC_ACT_NOT_FOUND
rpcSRC_AMT_MALFORMED
rpcSRC_CUR_MALFORMED
rpcSRC_ISR_MALFORMED
rpcATX_DEPRECATED
rpcINTERNAL
rpcFAIL_GEN_DECRYPT
rpcNOT_IMPL
rpcNOT_SUPPORTED
rpcNO_GEN_DECRYPT
Definition at line 29 of file ErrorCodes.h.
 {
     rpcUNKNOWN = -1,     // Represents codes not listed in this enumeration
     rpcSUCCESS = 0,
     rpcBAD_SYNTAX,  // Must be 1 to print usage to command line.
     rpcJSON_RPC,
     rpcFORBIDDEN,
     // Error numbers beyond this line are not stable between versions.
     // Programs should use error tokens.
     // Misc failure
     rpcLOAD_FAILED,
     rpcNO_PERMISSION,
     rpcNO_EVENTS,
     rpcNOT_STANDALONE,
     rpcTOO_BUSY,
     rpcSLOW_DOWN,
     rpcHIGH_FEE,
     // Networking
     rpcNO_CLOSED,
     rpcNO_CURRENT,
     rpcNO_NETWORK,
     // Ledger state
     rpcACT_EXISTS,
     rpcACT_NOT_FOUND,
     rpcINSUF_FUNDS,
     rpcLGR_NOT_FOUND,
     rpcMASTER_DISABLED,
     rpcNICKNAME_MISSING,
     rpcNO_ACCOUNT,
     rpcNO_PATH,
     rpcPASSWD_CHANGED,
     rpcSRC_MISSING,
     rpcSRC_UNCLAIMED,
     rpcTXN_NOT_FOUND,
     rpcWRONG_SEED,
     // Malformed command
     rpcINVALID_PARAMS,
     rpcUNKNOWN_COMMAND,
     rpcNO_PF_REQUEST,
     // Bad parameter
     rpcACT_BITCOIN,
     rpcACT_MALFORMED,
     rpcQUALITY_MALFORMED,
     rpcBAD_BLOB,
     rpcBAD_FEATURE,
     rpcBAD_ISSUER,
     rpcBAD_MARKET,
     rpcBAD_SECRET,
     rpcBAD_SEED,
     rpcCOMMAND_MISSING,
     rpcDST_ACT_MALFORMED,
     rpcDST_ACT_MISSING,
     rpcDST_AMT_MALFORMED,
     rpcDST_ISR_MALFORMED,
     rpcGETS_ACT_MALFORMED,
     rpcGETS_AMT_MALFORMED,
     rpcHOST_IP_MALFORMED,
     rpcLGR_IDXS_INVALID,
     rpcLGR_IDX_MALFORMED,
     rpcNICKNAME_MALFORMED,
     rpcNICKNAME_PERM,
     rpcPAYS_ACT_MALFORMED,
     rpcPAYS_AMT_MALFORMED,
     rpcPORT_MALFORMED,
     rpcPUBLIC_MALFORMED,
     rpcSRC_ACT_MALFORMED,
     rpcSRC_ACT_MISSING,
     rpcSRC_ACT_NOT_FOUND,
     rpcSRC_AMT_MALFORMED,
     rpcSRC_CUR_MALFORMED,
     rpcSRC_ISR_MALFORMED,
     rpcATX_DEPRECATED,
     // Internal error (should never happen)
     rpcINTERNAL,        // Generic internal error.
     rpcFAIL_GEN_DECRYPT,
     rpcNOT_IMPL,
     rpcNOT_SUPPORTED,
     rpcNO_GEN_DECRYPT,
 };
enum ripple::JobType
Enumerator
jtINVALID
jtPACK
jtPUBOLDLEDGER
jtVALIDATION_ut
jtPROOFWORK
jtTRANSACTION_l
jtPROPOSAL_ut
jtLEDGER_DATA
jtCLIENT
jtRPC
jtUPDATE_PF
jtTRANSACTION
jtUNL
jtADVANCE
jtPUBLEDGER
jtTXN_DATA
jtWAL
jtVALIDATION_t
jtWRITE
jtACCEPT
jtPROPOSAL_t
jtSWEEP
jtNETOP_CLUSTER
jtNETOP_TIMER
jtADMIN
jtPEER
jtDISK
jtTXN_PROC
jtOB_SETUP
jtPATH_FIND
jtHO_READ
jtHO_WRITE
jtGENERIC
Definition at line 28 of file Job.h.
 {
     // Special type indicating an invalid job - will go away soon.
     jtINVALID = -1,
     // Job types - the position in this enum indicates the job priority with
     // earlier jobs having lower priority than later jobs. If you wish to
     // insert a job at a specific priority, simply add it at the right location.
     jtPACK,          // Make a fetch pack for a peer
     jtPUBOLDLEDGER,  // An old ledger has been accepted
     jtVALIDATION_ut, // A validation from an untrusted source
     jtPROOFWORK,     // A proof of work demand from another server
     jtTRANSACTION_l, // A local transaction
     jtPROPOSAL_ut,   // A proposal from an untrusted source
     jtLEDGER_DATA,   // Received data for a ledger we're acquiring
     jtCLIENT,        // A websocket command from the client
     jtRPC,           // A websocket command from the client
     jtUPDATE_PF,     // Update pathfinding requests
     jtTRANSACTION,   // A transaction received from the network
     jtUNL,           // A Score or Fetch of the UNL (DEPRECATED)
     jtADVANCE,       // Advance validated/acquired ledgers
     jtPUBLEDGER,     // Publish a fully-accepted ledger
     jtTXN_DATA,      // Fetch a proposed set
     jtWAL,           // Write-ahead logging
     jtVALIDATION_t,  // A validation from a trusted source
     jtWRITE,         // Write out hashed objects
     jtACCEPT,        // Accept a consensus ledger
     jtPROPOSAL_t,    // A proposal from a trusted source
     jtSWEEP,         // Sweep for stale structures
     jtNETOP_CLUSTER, // NetworkOPs cluster peer report
     jtNETOP_TIMER,   // NetworkOPs net timer processing
     jtADMIN,         // An administrative operation
     // Special job types which are not dispatched by the job pool
     jtPEER          ,
     jtDISK          ,
     jtTXN_PROC      ,
     jtOB_SETUP      ,
     jtPATH_FIND     ,
     jtHO_READ       ,
     jtHO_WRITE      ,
     jtGENERIC       ,   // Used just to measure time
 };
enum ripple::LedgerEntryAction
Enumerator
taaNONE
taaCACHED
taaMODIFY
taaDELETE
taaCREATE
Definition at line 41 of file LedgerEntrySet.h.
 {
     taaNONE,
     taaCACHED,  // Unmodified.
     taaMODIFY,  // Modifed, must have previously been taaCACHED.
     taaDELETE,  // Delete, must have previously been taaDELETE or taaMODIFY.
     taaCREATE,  // Newly created.
 };
enum ripple::LedgerStateParms
Enumerator
lepNONE
lepCREATE
lepOKAY
lepMISSING
lepWRONGTYPE
lepCREATED
lepERROR
Definition at line 27 of file Ledger.h.
 {
     lepNONE         = 0,    // no special flags
     // input flags
     lepCREATE       = 1,    // Create if not present
     // output flags
     lepOKAY         = 2,    // success
     lepMISSING      = 4,    // No node in that slot
     lepWRONGTYPE    = 8,    // Node of different type there
     lepCREATED      = 16,   // Node was created
     lepERROR        = 32,   // error
 };
enum ripple::LoadType
Enumerator
LT_InvalidRequest
LT_RequestNoReply
LT_InvalidSignature
LT_UnwantedData
LT_BadPoW
LT_BadData
LT_RPCInvalid
LT_RPCReference
LT_RPCException
LT_RPCBurden
LT_NewTrusted
LT_NewTransaction
LT_NeededData
LT_RequestData
LT_CheapQuery
LT_MAX
Definition at line 25 of file LegacyFees.h.
 {
     // Bad things
     LT_InvalidRequest,          // A request that we can immediately tell is invalid
     LT_RequestNoReply,          // A request that we cannot satisfy
     LT_InvalidSignature,        // An object whose signature we had to check and it failed
     LT_UnwantedData,            // Data we have no use for
     LT_BadPoW,                  // Proof of work not valid
     LT_BadData,                 // Data we have to verify before rejecting
     // RPC loads
     LT_RPCInvalid,              // An RPC request that we can immediately tell is invalid.
     LT_RPCReference,            // A default "reference" unspecified load
     LT_RPCException,            // An RPC load that causes an exception
     LT_RPCBurden,               // A particularly burdensome RPC load
     // Good things
     LT_NewTrusted,              // A new transaction/validation/proposal we trust
     LT_NewTransaction,          // A new, valid transaction
     LT_NeededData,              // Data we requested
     // Requests
     LT_RequestData,             // A request that is hard to satisfy, disk access
     LT_CheapQuery,              // A query that is trivial, cached data
     LT_MAX                      // MUST BE LAST
 };
enum ripple::LogSeverity
Enumerator
lsINVALID
lsTRACE
lsDEBUG
lsINFO
lsWARNING
lsERROR
lsFATAL
Definition at line 25 of file LogSeverity.h.
 {
     lsINVALID   = -1,   // used to indicate an invalid severity
     lsTRACE     = 0,    // Very low-level progress information, details inside an operation
     lsDEBUG     = 1,    // Function-level progress information, operations
     lsINFO      = 2,    // Server-level progress information, major operations
     lsWARNING   = 3,    // Conditions that warrant human attention, may indicate a problem
     lsERROR     = 4,    // A condition that indicates a problem
     lsFATAL     = 5     // A severe condition that indicates a server problem
 };
enum ripple::NodeObjectType
The types of node objects.
Enumerator
hotUNKNOWN
hotLEDGER
hotTRANSACTION
hotACCOUNT_NODE
hotTRANSACTION_NODE
Definition at line 28 of file NodeObject.h.
 {
     hotUNKNOWN = 0,
     hotLEDGER = 1,
     hotTRANSACTION = 2,
     hotACCOUNT_NODE = 3,
     hotTRANSACTION_NODE = 4
 };
enum ripple::PowResult
Enumerator
powOK
powREUSED
powBADNONCE
powEXPIRED
powCORRUPT
powTOOEASY
Definition at line 25 of file PowResult.h.
 {
     powOK       = 0,
     powREUSED   = 1, // already submitted
     powBADNONCE = 2, // you didn't solve it
     powEXPIRED  = 3, // time is up
     powCORRUPT  = 4,
     powTOOEASY  = 5, // the difficulty increased too much while you solved it
 };
enum ripple::SerializedTypeID
Enumerator
STI_UNKNOWN
STI_DONE
STI_NOTPRESENT
FIELD
FIELD
STI_LEDGERENTRY
STI_VALIDATION
Definition at line 28 of file FieldNames.h.
 {
     // special types
     STI_UNKNOWN     = -2,
     STI_DONE        = -1,
     STI_NOTPRESENT  = 0,
 #define TYPE(name, field, value) STI_##field = value,
 #define FIELD(name, field, value)
 #include "../protocol/SerializeDeclarations.h"
 #undef TYPE
 #undef FIELD
     // high level types
     STI_TRANSACTION = 10001,
     STI_LEDGERENTRY = 10002,
     STI_VALIDATION  = 10003,
 };
enum ripple::SHAMapState
Enumerator
smsModifying
smsImmutable
smsSynching
smsFloating
smsInvalid
Definition at line 56 of file SHAMap.h.
 {
     smsModifying = 0,       // Objects can be added and removed (like an open ledger)
     smsImmutable = 1,       // Map cannot be changed (like a closed ledger)
     smsSynching = 2,        // Map's hash is locked in, valid nodes can be added (like a peer's closing ledger)
     smsFloating = 3,        // Map is free to change hash (like a synching open ledger)
     smsInvalid = 4,         // Map is known not to be valid (usually synching a corrupt ledger)
 };
enum ripple::SHAMapType
Enumerator
smtTRANSACTION
smtSTATE
smtFREE
Definition at line 25 of file SHAMapMissingNode.h.
 {
     smtTRANSACTION  = 1,    // A tree of transactions
     smtSTATE        = 2,    // A tree of state nodes
     smtFREE         = 3,    // A tree not part of a ledger
 };
enum ripple::SHANodeFormat
Enumerator
snfPREFIX
snfWIRE
snfHASH
Definition at line 27 of file SHAMapTreeNode.h.
 {
     snfPREFIX   = 1, // Form that hashes to its official hash
     snfWIRE     = 2, // Compressed form used on the wire
     snfHASH     = 3, // just the hash
 };
enum ripple::SizedItemName
Enumerator
siSweepInterval
siValidationsSize
siValidationsAge
siNodeCacheSize
siNodeCacheAge
siTreeCacheSize
siTreeCacheAge
siSLECacheSize
siSLECacheAge
siLedgerSize
siLedgerAge
siLedgerFetch
siHashNodeDBCache
siTxnDBCache
siLgrDBCache
Definition at line 61 of file Config.h.
 {
     siSweepInterval,
     siValidationsSize,
     siValidationsAge,
     siNodeCacheSize,
     siNodeCacheAge,
     siTreeCacheSize,
     siTreeCacheAge,
     siSLECacheSize,
     siSLECacheAge,
     siLedgerSize,
     siLedgerAge,
     siLedgerFetch,
     siHashNodeDBCache,
     siTxnDBCache,
     siLgrDBCache,
 };
enum ripple::SOE_Flags
Flags for elements in a SerializedObjectTemplate.
Enumerator
SOE_INVALID
SOE_REQUIRED
SOE_OPTIONAL
SOE_DEFAULT
Definition at line 28 of file SerializedObjectTemplate.h.
 {
     SOE_INVALID  = -1,
     SOE_REQUIRED = 0,   // required
     SOE_OPTIONAL = 1,   // optional, may be present with default value
     SOE_DEFAULT  = 2,   // optional, if present, must not have default value
 };
enum ripple::TER
Enumerator
telLOCAL_ERROR
telBAD_DOMAIN
telBAD_PATH_COUNT
telBAD_PUBLIC_KEY
telFAILED_PROCESSING
telINSUF_FEE_P
telNO_DST_PARTIAL
temMALFORMED
temBAD_AMOUNT
temBAD_AUTH_MASTER
temBAD_CURRENCY
temBAD_FEE
temBAD_EXPIRATION
temBAD_ISSUER
temBAD_LIMIT
temBAD_OFFER
temBAD_PATH
temBAD_PATH_LOOP
temBAD_PUBLISH
temBAD_TRANSFER_RATE
temBAD_SEND_XRP_LIMIT
temBAD_SEND_XRP_MAX
temBAD_SEND_XRP_NO_DIRECT
temBAD_SEND_XRP_PARTIAL
temBAD_SEND_XRP_PATHS
temBAD_SIGNATURE
temBAD_SRC_ACCOUNT
temBAD_SEQUENCE
temDST_IS_SRC
temDST_NEEDED
temINVALID
temINVALID_FLAG
temREDUNDANT
temREDUNDANT_SEND_MAX
temRIPPLE_EMPTY
temUNCERTAIN
temUNKNOWN
tefFAILURE
tefALREADY
tefBAD_ADD_AUTH
tefBAD_AUTH
tefBAD_CLAIM_ID
tefBAD_GEN_AUTH
tefBAD_LEDGER
tefCLAIMED
tefCREATED
tefDST_TAG_NEEDED
tefEXCEPTION
tefGEN_IN_USE
tefINTERNAL
tefNO_AUTH_REQUIRED
tefPAST_SEQ
tefWRONG_PRIOR
tefMASTER_DISABLED
tefMAX_LEDGER
terRETRY
terFUNDS_SPENT
terINSUF_FEE_B
terNO_ACCOUNT
terNO_AUTH
terNO_LINE
terOWNERS
terPRE_SEQ
terLAST
terNO_RIPPLE
tesSUCCESS
tecCLAIM
tecPATH_PARTIAL
tecUNFUNDED_ADD
tecUNFUNDED_OFFER
tecUNFUNDED_PAYMENT
tecFAILED_PROCESSING
tecDIR_FULL
tecINSUF_RESERVE_LINE
tecINSUF_RESERVE_OFFER
tecNO_DST
tecNO_DST_INSUF_XRP
tecNO_LINE_INSUF_RESERVE
tecNO_LINE_REDUNDANT
tecPATH_DRY
tecUNFUNDED
tecMASTER_DISABLED
tecNO_REGULAR_KEY
tecOWNERS
tecNO_ISSUER
tecNO_AUTH
tecNO_LINE
Definition at line 31 of file TER.h.
 {
     // Note: Range is stable.  Exact numbers are currently unstable.  Use tokens.
     // -399 .. -300: L Local error (transaction fee inadequate, exceeds local limit)
     // Only valid during non-consensus processing.
     // Implications:
     // - Not forwarded
     // - No fee check
     telLOCAL_ERROR  = -399,
     telBAD_DOMAIN, // VFALCO TODO should read "telBAD_DOMAIN = -398," etc...
     telBAD_PATH_COUNT,
     telBAD_PUBLIC_KEY,
     telFAILED_PROCESSING,
     telINSUF_FEE_P,
     telNO_DST_PARTIAL,
     // -299 .. -200: M Malformed (bad signature)
     // Causes:
     // - Transaction corrupt.
     // Implications:
     // - Not applied
     // - Not forwarded
     // - Reject
     // - Can not succeed in any imagined ledger.
     temMALFORMED    = -299,
     temBAD_AMOUNT,
     temBAD_AUTH_MASTER,
     temBAD_CURRENCY,
     temBAD_FEE,
     temBAD_EXPIRATION,
     temBAD_ISSUER,
     temBAD_LIMIT,
     temBAD_OFFER,
     temBAD_PATH,
     temBAD_PATH_LOOP,
     temBAD_PUBLISH,
     temBAD_TRANSFER_RATE,
     temBAD_SEND_XRP_LIMIT,
     temBAD_SEND_XRP_MAX,
     temBAD_SEND_XRP_NO_DIRECT,
     temBAD_SEND_XRP_PARTIAL,
     temBAD_SEND_XRP_PATHS,
     temBAD_SIGNATURE,
     temBAD_SRC_ACCOUNT,
     temBAD_SEQUENCE,
     temDST_IS_SRC,
     temDST_NEEDED,
     temINVALID,
     temINVALID_FLAG,
     temREDUNDANT,
     temREDUNDANT_SEND_MAX,
     temRIPPLE_EMPTY,
     temUNCERTAIN,       // An intermediate result used internally, should never be returned.
     temUNKNOWN,
     // -199 .. -100: F Failure (sequence number previously used)
     // Causes:
     // - Transaction cannot succeed because of ledger state.
     // - Unexpected ledger state.
     // - C++ exception.
     // Implications:
     // - Not applied
     // - Not forwarded
     // - Could succeed in an imagined ledger.
     tefFAILURE      = -199,
     tefALREADY,
     tefBAD_ADD_AUTH,
     tefBAD_AUTH,
     tefBAD_CLAIM_ID,
     tefBAD_GEN_AUTH,
     tefBAD_LEDGER,
     tefCLAIMED,
     tefCREATED,
     tefDST_TAG_NEEDED,
     tefEXCEPTION,
     tefGEN_IN_USE,
     tefINTERNAL,
     tefNO_AUTH_REQUIRED,    // Can't set auth if auth is not required.
     tefPAST_SEQ,
     tefWRONG_PRIOR,
     tefMASTER_DISABLED,
     tefMAX_LEDGER,
     // -99 .. -1: R Retry (sequence too high, no funds for txn fee, originating account non-existent)
     // Causes:
     // - Prior application of another, possibly non-existant, another transaction could allow this transaction to succeed.
     // Implications:
     // - Not applied
     // - Not forwarded
     // - Might succeed later
     // - Hold
     // - Makes hole in sequence which jams transactions.
     terRETRY        = -99,
     terFUNDS_SPENT,         // This is a free transaction, therefore don't burden network.
     terINSUF_FEE_B,         // Can't pay fee, therefore don't burden network.
     terNO_ACCOUNT,          // Can't pay fee, therefore don't burden network.
     terNO_AUTH,             // Not authorized to hold IOUs.
     terNO_LINE,             // Internal flag.
     terOWNERS,              // Can't succeed with non-zero owner count.
     terPRE_SEQ,             // Can't pay fee, no point in forwarding, therefore don't burden network.
     terLAST,                // Process after all other transactions
     terNO_RIPPLE,           // Rippling not allowed
     // 0: S Success (success)
     // Causes:
     // - Success.
     // Implications:
     // - Applied
     // - Forwarded
     tesSUCCESS      = 0,
     // 100 .. 159 C Claim fee only (ripple transaction with no good paths, pay to non-existent account, no path)
     // Causes:
     // - Success, but does not achieve optimal result.
     // - Invalid transaction or no effect, but claim fee to use the sequence number.
     // Implications:
     // - Applied
     // - Forwarded
     // Only allowed as a return code of appliedTransaction when !tapRetry. Otherwise, treated as terRETRY.
     //
     // DO NOT CHANGE THESE NUMBERS: They appear in ledger meta data.
     tecCLAIM                    = 100,
     tecPATH_PARTIAL             = 101,
     tecUNFUNDED_ADD             = 102,
     tecUNFUNDED_OFFER           = 103,
     tecUNFUNDED_PAYMENT         = 104,
     tecFAILED_PROCESSING        = 105,
     tecDIR_FULL                 = 121,
     tecINSUF_RESERVE_LINE       = 122,
     tecINSUF_RESERVE_OFFER      = 123,
     tecNO_DST                   = 124,
     tecNO_DST_INSUF_XRP         = 125,
     tecNO_LINE_INSUF_RESERVE    = 126,
     tecNO_LINE_REDUNDANT        = 127,
     tecPATH_DRY                 = 128,
     tecUNFUNDED                 = 129,  // Deprecated, old ambiguous unfunded.
     tecMASTER_DISABLED          = 130,
     tecNO_REGULAR_KEY           = 131,
     tecOWNERS                   = 132,
     tecNO_ISSUER                = 133,
     tecNO_AUTH                  = 134,
     tecNO_LINE                  = 135,
 };
enum ripple::TransactionEngineParams
Enumerator
tapNONE
tapNO_CHECK_SIGN
tapOPEN_LEDGER
tapRETRY
tapADMIN
Definition at line 25 of file LedgerEntrySet.h.
 {
     tapNONE             = 0x00,
     tapNO_CHECK_SIGN    = 0x01,     // Signature already checked
     tapOPEN_LEDGER      = 0x10,     // Transaction is running against an open ledger
     // true = failures are not forwarded, check transaction fee
     // false = debit ledger for consumed funds
     tapRETRY            = 0x20,     // This is not the transaction's last pass
     // Transaction can be retried, soft failures allowed
     tapADMIN            = 0x400,    // Transaction came from a privileged source
 };
enum ripple::TransStatus
Enumerator
NEW
INVALID
INCLUDED
CONFLICTED
COMMITTED
HELD
REMOVED
OBSOLETE
INCOMPLETE
Definition at line 31 of file Transaction.h.
 {
     NEW         = 0, // just received / generated
     INVALID     = 1, // no valid signature, insufficient funds
     INCLUDED    = 2, // added to the current ledger
     CONFLICTED  = 3, // losing to a conflicting transaction
     COMMITTED   = 4, // known to be in a ledger
     HELD        = 5, // not valid now, maybe later
     REMOVED     = 6, // taken out of a ledger
     OBSOLETE    = 7, // a compatible transaction has taken precedence
     INCOMPLETE  = 8  // needs more signatures
 };
Function Documentation
static void ripple::addFPtoList (std::list< SHAMap::fetchPackEntry_t > & list, const uint256 & hash, const Blob & blob) static
Definition at line 616 of file SHAMapSync.cpp.
Referenced by ripple::SHAMap::getFetchPack().
 {
     list.push_back (SHAMap::fetchPackEntry_t (hash, blob));
 }
static void ripple::addIfUnique (std::vector< RippleAddress > & vector, const RippleAddress & address) static
Definition at line 78 of file TransactionMeta.cpp.
Referenced by ripple::TransactionMetaSet::getAffectedAccounts().
 {
     BOOST_FOREACH (const RippleAddress & a, vector)
     if (a == address)
         return;
     vector.push_back (address);
 }
static void ripple::addTxnSeqField () static
Definition at line 1259 of file Application.cpp.
References db, ripple::Database::executeSQL(), getApp(), ripple::Database::getBinary(), ripple::DatabaseCon::getDB(), ripple::TransactionMetaSet::getIndex(), ripple::Database::getStr(), ripple::Application::getTxnDB(), rocksdb::Log(), lsINFO, lsWARNING, schemaHas(), ripple::base_uint< BITS >::SetHex(), SQL_FOREACH, and tid.
Referenced by ripple::ApplicationImp::updateTables().
 {
     if (schemaHas (getApp().getTxnDB (), "AccountTransactions", 0, "TxnSeq"))
         return;
     Log (lsWARNING) << "Transaction sequence field is missing";
     Database* db = getApp().getTxnDB ()->getDB ();
     std::vector< std::pair<uint256, int> > txIDs;
     txIDs.reserve (300000);
     Log (lsINFO) << "Parsing transactions";
     int i = 0;
     uint256 transID;
     SQL_FOREACH (db, "SELECT TransID,TxnMeta FROM Transactions;")
     {
         Blob rawMeta;
         int metaSize = 2048;
         rawMeta.resize (metaSize);
         metaSize = db->getBinary ("TxnMeta", &*rawMeta.begin (), rawMeta.size ());
         if (metaSize > static_cast<int> (rawMeta.size ()))
         {
             rawMeta.resize (metaSize);
             db->getBinary ("TxnMeta", &*rawMeta.begin (), rawMeta.size ());
         }
         else rawMeta.resize (metaSize);
         std::string tid;
         db->getStr ("TransID", tid);
         transID.SetHex (tid, true);
         if (rawMeta.size () == 0)
         {
             txIDs.push_back (std::make_pair (transID, -1));
             Log (lsINFO) << "No metadata for " << transID;
         }
         else
         {
             TransactionMetaSet m (transID, 0, rawMeta);
             txIDs.push_back (std::make_pair (transID, m.getIndex ()));
         }
         if ((++i % 1000) == 0)
             Log (lsINFO) << i << " transactions read";
     }
     Log (lsINFO) << "All " << i << " transactions read";
     db->executeSQL ("BEGIN TRANSACTION;");
     Log (lsINFO) << "Dropping old index";
     db->executeSQL ("DROP INDEX AcctTxIndex;");
     Log (lsINFO) << "Altering table";
     db->executeSQL ("ALTER TABLE AccountTransactions ADD COLUMN TxnSeq INTEGER;");
     typedef std::pair<uint256, int> u256_int_pair_t;
     boost::format fmt ("UPDATE AccountTransactions SET TxnSeq = %d WHERE TransID = '%s';");
     i = 0;
     BOOST_FOREACH (u256_int_pair_t & t, txIDs)
     {
         db->executeSQL (boost::str (fmt % t.second % t.first.GetHex ()));
         if ((++i % 1000) == 0)
             Log (lsINFO) << i << " transactions updated";
     }
     Log (lsINFO) << "Building new index";
     db->executeSQL ("CREATE INDEX AcctTxIndex ON AccountTransactions(Account, LedgerSeq, TxnSeq, TransID);");
     db->executeSQL ("END TRANSACTION;");
 }
ripple::BEAST_DEFINE_TESTSUITE (LoadFeeTrack , ripple_core , ripple)
ripple::BEAST_DEFINE_TESTSUITE (CKey , ripple_data , ripple)
ripple::BEAST_DEFINE_TESTSUITE (KeyCache , common , ripple)
ripple::BEAST_DEFINE_TESTSUITE (JsonCpp , json , ripple)
ripple::BEAST_DEFINE_TESTSUITE (FetchPack , ripple_app , ripple)
ripple::BEAST_DEFINE_TESTSUITE (TaggedCache , common , ripple)
ripple::BEAST_DEFINE_TESTSUITE (BuildInfo , ripple_data , ripple)
ripple::BEAST_DEFINE_TESTSUITE (MultiSocket , common , ripple)
ripple::BEAST_DEFINE_TESTSUITE (RangeSet , ripple_basics , ripple)
ripple::BEAST_DEFINE_TESTSUITE (SerializedTransaction , ripple_app , ripple)
ripple::BEAST_DEFINE_TESTSUITE (StringUtilities , ripple_basics , ripple)
ripple::BEAST_DEFINE_TESTSUITE (RippleAsset , types , ripple)
ripple::BEAST_DEFINE_TESTSUITE (ECDSACanonical , sslutil , ripple)
ripple::BEAST_DEFINE_TESTSUITE (Serializer , ripple_data , ripple)
ripple::BEAST_DEFINE_TESTSUITE (SHAMapSync , ripple_app , ripple)
ripple::BEAST_DEFINE_TESTSUITE (RippleAddress , ripple_data , ripple)
ripple::BEAST_DEFINE_TESTSUITE (RippleIdentifier , ripple_data , ripple)
ripple::BEAST_DEFINE_TESTSUITE (SHAMap , ripple_app , ripple)
ripple::BEAST_DEFINE_TESTSUITE (SerializedObject , ripple_data , ripple)
ripple::BEAST_DEFINE_TESTSUITE (STAmount , ripple_data , ripple)
ripple::BEAST_DEFINE_TESTSUITE (Ledger , ripple_app , ripple)
ripple::BEAST_DEFINE_TESTSUITE_MANUAL (FatalErrorReporter , ripple_app , ripple)
ripple::BEAST_DEFINE_TESTSUITE_MANUAL (ProofOfWork , ripple_app , ripple)
int ripple::BN_add_word64 (BIGNUM * a, std::uint64_t w)
Definition at line 644 of file CBigNum.cpp.
Referenced by ripple::STAmount::divide(), ripple::STAmount::divRound(), ripple::STAmount::mulRound(), and ripple::STAmount::multiply().
 {
     CBigNum bn (w);
     return BN_add (a, &bn, a);
 }
std::uint64_t ripple::BN_div_word64 (BIGNUM * a, std::uint64_t w)
Definition at line 663 of file CBigNum.cpp.
Referenced by ripple::STAmount::divide(), ripple::STAmount::divRound(), ripple::STAmount::mulRound(), and ripple::STAmount::multiply().
 {
     CBigNum bn (w);
     CAutoBN_CTX ctx;
     return (BN_div (a, nullptr, a, &bn, ctx) == 1) ? 0 : ((std::uint64_t) - 1);
 }
int ripple::BN_mul_word64 (BIGNUM * a, std::uint64_t w)
Definition at line 656 of file CBigNum.cpp.
Referenced by ripple::STAmount::divide(), ripple::STAmount::divRound(), ripple::STAmount::mulRound(), and ripple::STAmount::multiply().
 {
     CBigNum bn (w);
     CAutoBN_CTX ctx;
     return BN_mul (a, &bn, a, ctx);
 }
int ripple::BN_sub_word64 (BIGNUM * a, std::uint64_t w)
Definition at line 650 of file CBigNum.cpp.
 {
     CBigNum bn (w);
     return BN_sub (a, &bn, a);
 }
static bool ripple::bQualityCmp (const path_LQ_t & a, const path_LQ_t & b) static
Definition at line 67 of file Pathfinder.cpp.
Referenced by ripple::Pathfinder::filterPaths().
 {
     // 1) Higher quality (lower cost) is better
     if (std::get<0> (a) != std::get<0> (b))
         return std::get<0> (a) < std::get<0> (b);
     // 2) More liquidity (higher volume) is better
     if (std::get<2> (a) != std::get<2> (b))
         return std::get<2> (a) > std::get<2> (b);
     // 3) Shorter paths are better
     if (std::get<1> (a) != std::get<1> (b))
         return std::get<1> (a) < std::get<1> (b);
     // 4) Tie breaker
     return std::get<3> (a) > std::get<3> (b);
 }
static bool ripple::candCmp (std::uint32_t seq, const candidate_t & first, const candidate_t & second) static
Definition at line 86 of file Pathfinder.cpp.
Referenced by ripple::Pathfinder::addLink().
 {
     if (first.first < second.first)
         return false;
     if (first.first > second.first)
         return true;
     return (first.first ^ seq) < (second.first ^ seq);
 }
char ripple::charHex (int iDigit)
Converts an integer to the corresponding hex digit
Parameters
iDigit 0-15 inclusive
Returns
a character from '0'-'9' or 'A'-'F' on success; 0 on failure.
Definition at line 22 of file strHex.cpp.
Referenced by sqlEscape(), strHex(), and urlEncode().
 {
     if (iDigit >= 0)
     {
         if(iDigit < 10)
             return '0' + iDigit;
         if(iDigit < 16)
             return 'A' - 10 + iDigit;
     }
     return 0;
 }
int ripple::charUnHex (char cDigit)
Converts a hex digit to the corresponding integer
Parameters
cDigit one of '0'-'9', 'A'-'F' or 'a'-'f'
Returns
an integer from 0 to 15 on success; -1 on failure.
Definition at line 35 of file strHex.cpp.
Referenced by strUnHex(), and uintFromHex().
 {
     struct HexTab
     {
         int hex[256];
         HexTab ()
         {
             std::fill (std::begin (hex), std::end (hex), -1);
             for (int i = 0; i < 10; ++i)
                 hex ['0'+i] = i;
             for (int i = 0; i < 6; ++i)
             {
                 hex ['A'+i] = 10 + i;
                 hex ['a'+i] = 10 + i;
             }
         }
         int operator[] (int i) const
         {
            return hex[i];
         }
     };
     static HexTab xtab;
     return xtab[cDigit];
 }
bool ripple::checkECIES (void)
Definition at line 286 of file CKeyECIES.cpp.
References ripple::CKey::decryptECIES(), ripple::CKey::encryptECIES(), ripple::RandomNumbers::fillBytes(), ripple::RandomNumbers::getInstance(), ripple::CKey::GetPubKey(), ripple::CKey::MakeNewKey(), and ripple::CKey::SetPubKey().
 {
     CKey senderPriv, recipientPriv, senderPub, recipientPub;
     for (int i = 0; i < 30000; ++i)
     {
         if ((i % 100) == 0)
         {
             // generate new keys every 100 times
             //          Log::out() << "new keys";
             senderPriv.MakeNewKey ();
             recipientPriv.MakeNewKey ();
             if (!senderPub.SetPubKey (senderPriv.GetPubKey ()))
                 throw std::runtime_error ("key error");
             if (!recipientPub.SetPubKey (recipientPriv.GetPubKey ()))
                 throw std::runtime_error ("key error");
         }
         // generate message
         Blob message (4096);
         int msglen = i % 3000;
         RandomNumbers::getInstance ().fillBytes (&message.front (), msglen);
         message.resize (msglen);
         // encrypt message with sender's private key and recipient's public key
         Blob ciphertext = senderPriv.encryptECIES (recipientPub, message);
         // decrypt message with recipient's private key and sender's public key
         Blob decrypt = recipientPriv.decryptECIES (senderPub, ciphertext);
         if (decrypt != message)
         {
             assert (false);
             return false;
         }
         //Log::out() << "Msg(" << msglen << ") ok " << ciphertext.size();
     }
     return true;
 }
template<bool LhsByValue, bool RhsByValue> int ripple::compare (RippleAssetType< LhsByValue > const & lhs, RippleAssetType< RhsByValue > const & rhs)
Ordered comparison. The assets are ordered first by currency and then by issuer, if the currency is not XRP.
Definition at line 110 of file RippleAssets.h.
References ripple::RippleAssetType< ByValue >::currency, ripple::RippleAssetType< ByValue >::is_xrp(), and ripple::RippleAssetType< ByValue >::issuer.
Referenced by ripple::TransactionMetaSet::addRaw(), compare(), rocksdb::VectorRepFactory::CreateMemTableRep(), rocksdb::TransformRepFactory::CreateMemTableRep(), rocksdb::PrefixHashRepFactory::CreateMemTableRep(), rocksdb::HashSkipListRepFactory::CreateMemTableRep(), leveldb_comparator_create(), beast::asio::InputParser::match_buffer(), operator<(), operator==(), ripple::STArray::sort(), and rocksdb::TEST().
 {
     int const diff (compare (lhs.currency, rhs.currency));
     if (diff != 0)
         return diff;
     if (lhs.is_xrp ())
         return 0;
     return compare (lhs.issuer, rhs.issuer);
 }
static bool ripple::compare (const STObject & o1, const STObject & o2) static
Definition at line 210 of file TransactionMeta.cpp.
References ripple::STObject::getFieldH256().
 {
     return o1.getFieldH256 (sfLedgerIndex) < o2.getFieldH256 (sfLedgerIndex);
 }
template<bool LhsByValue, bool RhsByValue> int ripple::compare (RippleBookType< LhsByValue > const & lhs, RippleBookType< RhsByValue > const & rhs)
Ordered comparison.
Definition at line 250 of file RippleAssets.h.
References compare(), ripple::RippleBookType< ByValue >::in, and ripple::RippleBookType< ByValue >::out.
 {
     int const diff (compare (lhs.in, rhs.in));
     if (diff != 0)
         return diff;
     return compare (lhs.out, rhs.out);
 }
std::string ripple::createHTTPPost (std::string const & strHost, std::string const & strPath, std::string const & strMsg, std::map< std::string, std::string > const & mapRequestHeaders)
Definition at line 55 of file RPCUtil.cpp.
References FormatFullVersion(), and SYSTEM_NAME.
Referenced by ripple::RPCCallImp::onRequest().
 {
     std::ostringstream s;
     // CHECKME this uses a different version than the replies below use. Is
     //         this by design or an accident or should it be using
     //         BuildInfo::getFullVersionString () as well?
     s << "POST "
       << (strPath.empty () ? "/" : strPath)
       << " HTTP/1.0\r\n"
       << "User-Agent: " SYSTEM_NAME "-json-rpc/" << FormatFullVersion () << "\r\n"
       << "Host: " << strHost << "\r\n"
       << "Content-Type: application/json\r\n"
       << "Content-Length: " << strMsg.size () << "\r\n"
       << "Accept: application/json\r\n";
     for (auto const& item : mapRequestHeaders)
         s << item.first << ": " << item.second << "\r\n";
     s << "\r\n" << strMsg;
     return s.str ();
 }
std::string ripple::DecodeBase64 (std::string s)
Definition at line 249 of file RPCUtil.cpp.
Referenced by HTTPAuthorized().
 {
     // FIXME: This performs badly
     BIO* b64, *bmem;
     char* buffer = static_cast<char*> (calloc (s.size (), sizeof (char)));
     b64 = BIO_new (BIO_f_base64 ());
     BIO_set_flags (b64, BIO_FLAGS_BASE64_NO_NL);
     bmem = BIO_new_mem_buf (const_cast<char*> (s.data ()), s.size ());
     bmem = BIO_push (b64, bmem);
     BIO_read (bmem, buffer, s.size ());
     BIO_free_all (bmem);
     std::string result (buffer);
     free (buffer);
     return result;
 }
void ripple::delete_clone (const SerializedType * s) inline
Definition at line 209 of file SerializedTypes.h.
 {
     boost::checked_delete (s);
 }
std::string ripple::DH_der_gen (int iKeyLength)
Definition at line 22 of file DHUtil.cpp.
References next.
Referenced by ripple::LocalCredentials::nodeIdentityCreate().
 {
     DH*         dh  = 0;
     int         iCodes;
     std::string strDer;
     do
     {
         dh  = DH_generate_parameters (iKeyLength, DH_GENERATOR_5, nullptr, nullptr);
         iCodes  = 0;
         DH_check (dh, &iCodes);
     }
     while (iCodes & (DH_CHECK_P_NOT_PRIME | DH_CHECK_P_NOT_SAFE_PRIME | DH_UNABLE_TO_CHECK_GENERATOR | DH_NOT_SUITABLE_GENERATOR));
     strDer.resize (i2d_DHparams (dh, nullptr));
     unsigned char* next = reinterpret_cast<unsigned char*> (&strDer[0]);
     (void) i2d_DHparams (dh, &next);
     return strDer;
 }
DH * ripple::DH_der_load (const std::string & strDer)
Definition at line 45 of file DHUtil.cpp.
 {
     const unsigned char* pbuf   = reinterpret_cast<const unsigned char*> (&strDer[0]);
     return d2i_DHparams (nullptr, &pbuf, strDer.size ());
 }
std::string ripple::DoSustain (std::string)
Definition at line 103 of file Sustain.cpp.
Referenced by run().
 {
     return std::string ();
 }
void ripple::ErrorReply (std::ostream & stream, const Json::Value & objError, const Json::Value & id)
Definition at line 317 of file RPCUtil.cpp.
References Json::Value::asInt(), HTTPReply(), and JSONRPCReply().
 {
     // Send error reply from json-rpc error object
     int nStatus = 500;
     int code = objError["code"].asInt ();
     if (code == -32600) nStatus = 400;
     else if (code == -32601) nStatus = 404;
     std::string strReply = JSONRPCReply (Json::Value (), objError, id);
     stream << HTTPReply (nStatus, strReply) << std::flush;
 }
ripple::FIELD (FirstLedgerSequence , UINT32 , 26)
Definition at line 89 of file FieldNames.cpp.
References sfInvalid.
     {
         // types we are willing to dynamically extend
 #define FIELD(name, type, index)
 #define TYPE(name, type, index) case STI_##type:
 #include "../protocol/SerializeDeclarations.h"
 #undef FIELD
 #undef TYPE
         break;
     default:
         return sfInvalid;
     }
     return * (new SField (static_cast<SerializedTypeID> (type), field));
 }
 int SField::compare (SField::ref f1, SField::ref f2)
 {
     // -1 = f1 comes before f2, 0 = illegal combination, 1 = f1 comes after f2
     if ((f1.fieldCode <= 0) || (f2.fieldCode <= 0))
         return 0;
     if (f1.fieldCode < f2.fieldCode)
         return -1;
     if (f2.fieldCode < f1.fieldCode)
         return 1;
     return 0;
 }
 std::string SField::getName () const
 {
     if (!fieldName.empty ())
         return fieldName;
     if (fieldValue == 0)
         return "";
     return beast::lexicalCastThrow <std::string> (static_cast<int> (fieldType)) + "/" +
            beast::lexicalCastThrow <std::string> (fieldValue);
 }
 SField::ref SField::getField (const std::string& fieldName)
 {
     // OPTIMIZEME me with a map. CHECKME this is case sensitive
     StaticScopedLockType sl (getMutex ());
     typedef std::map<int, SField::ptr>::value_type int_sfref_pair;
     BOOST_FOREACH (const int_sfref_pair & fieldPair, codeToField)
     {
         if (fieldPair.second->fieldName == fieldName)
             return * (fieldPair.second);
     }
     return sfInvalid;
 }
 SField::~SField ()
 {
     StaticScopedLockType sl (getMutex ());
     std::map<int, ptr>::iterator it = codeToField.find (fieldCode);
     if ((it != codeToField.end ()) && (it->second == this))
         codeToField.erase (it);
 }
 } // ripple
std::string ripple::FormatFullVersion ()
Definition at line 32 of file RPCUtil.cpp.
References gFormatStr().
Referenced by createHTTPPost(), and HTTPReply().
 {
     return (gFormatStr);
 }
static void ripple::fpAppender (protocol::TMGetObjectByHash * reply, std::uint32_t ledgerSeq, const uint256 & hash, const Blob & blob) static
Definition at line 3180 of file NetworkOPs.cpp.
References ripple::base_uint< BITS >::begin().
Referenced by ripple::NetworkOPsImp::makeFetchPack().
 {
     protocol::TMIndexedObject& newObj = * (reply->add_objects ());
     newObj.set_ledgerseq (ledgerSeq);
     newObj.set_hash (hash.begin (), 256 / 8);
     newObj.set_data (&blob[0], blob.size ());
 }
static std::string const ripple::get_milli_diff (boost::posix_time::ptime const & after, boost::posix_time::ptime const & before) static
Definition at line 42 of file PathRequest.cpp.
Referenced by get_milli_diff(), and ripple::PathRequest::~PathRequest().
 {
     return beast::lexicalCastThrow <std::string> (static_cast <unsigned> ((after - before).total_milliseconds()));
 }
static std::string const ripple::get_milli_diff (boost::posix_time::ptime const & before) static
Definition at line 47 of file PathRequest.cpp.
References get_milli_diff().
 {
     return get_milli_diff(boost::posix_time::microsec_clock::universal_time(), before);
 }
beast::abstract_clock<std::chrono::seconds>& ripple::get_seconds_clock () inline
Returns an abstract_clock optimized for counting seconds.
Definition at line 37 of file seconds_clock.h.
Referenced by ripple::FetchPack_test::run(), ripple::SHAMapSync_test::run(), and ripple::SHAMap_test::run().
 {
     typedef beast::basic_seconds_clock <std::chrono::steady_clock> clock_type;
     return beast::get_abstract_clock <clock_type, std::chrono::seconds> ();
 }
static const uint160& ripple::get_u160_one () inline static
Definition at line 58 of file SerializedTypes.h.
References u160_one().
 {
     return u160_one;
 }
static const uint160& ripple::get_u160_zero () inline static
Definition at line 54 of file SerializedTypes.h.
References u160_zero().
 {
     return u160_zero;
 }
Application & ripple::getApp ()
Definition at line 1387 of file Application.cpp.
References ripple::ApplicationImpBase::getInstance().
Referenced by ripple::LedgerConsensusImp::accept(), ripple::UniqueNodeListImp::addClusterStatus(), ripple::LedgerConsensusImp::addDisputedTransaction(), ripple::Pathfinder::addLink(), ripple::LedgerConsensusImp::addLoad(), ripple::InboundLedger::addPeers(), addTxnSeqField(), ripple::ValidationsImp::addValidation(), ripple::ChangeTransactor::applyFeature(), ripple::LedgerConsensusImp::applyTransaction(), ripple::LedgerConsensusImp::beginAccept(), ripple::LedgerMasterImp::checkAccept(), ripple::NetworkOPsImp::checkLastClosedLedger(), ripple::LedgerConsensusImp::checkLCL(), ripple::LedgerConsensusImp::checkOurValidation(), ripple::PeerImp::checkPropose(), ripple::PeerImp::checkTransaction(), ripple::PeerImp::checkValidation(), ripple::NetworkOPsImp::clearLedgerFetch(), ripple::LedgerMasterImp::closeLedger(), ripple::LedgerConsensusImp::closeLedger(), ripple::ValidationsImp::condWrite(), ripple::LedgerMasterImp::consensusBuilt(), ripple::LocalCredentials::dataDelete(), ripple::LocalCredentials::dataFetch(), ripple::LocalCredentials::dataStore(), ripple::WSServerHandler< endpoint_type >::do_messages(), ripple::LedgerMasterImp::doAdvance(), ripple::RPCHandler::doBlackList(), ripple::RPCHandler::doBookOffers(), ripple::LedgerCleanerImp::doClean(), ripple::WSServerHandler< endpoint_type >::doClose(), ripple::RPCHandler::doCommand(), ripple::RPCHandler::doConnect(), ripple::RPCHandler::doFeature(), ripple::PeerImp::doFetchPack(), ripple::RPCHandler::doGetCounts(), ripple::RPCHandler::doLedger(), ripple::LedgerCleanerImp::doLedger(), ripple::RPCHandler::doLedgerCleaner(), ripple::LedgerCleanerImp::doLedgerCleaner(), ripple::TransactionAcquire::done(), ripple::InboundLedger::done(), ripple::RPCHandler::doPathFind(), ripple::RPCHandler::doPeers(), ripple::RPCHandler::doPrint(), ripple::RPCHandler::doProofCreate(), ripple::RPCHandler::doProofVerify(), ripple::RPCHandler::doRipplePathFind(), ripple::RPCHandler::doSMS(), ripple::RPCHandler::doStop(), ripple::RPCHandler::doSubscribe(), ripple::LedgerMasterImp::doTransaction(), ripple::RPCHandler::doTx(), ripple::RPCHandler::doTxHistory(), ripple::RPCHandler::doUnlAdd(), ripple::RPCHandler::doUnlDelete(), ripple::RPCHandler::doUnlList(), ripple::RPCHandler::doUnlLoad(), ripple::RPCHandler::doUnlNetwork(), ripple::RPCHandler::doUnlReset(), ripple::RPCHandler::doUnlScore(), ripple::PathRequest::doUpdate(), ripple::FeaturesImpl::doVoting(), ripple::FeeVoteImpl::doVoting(), ripple::ValidationsImp::doWrite(), ripple::NetworkOPsImp::endConsensus(), ripple::LedgerConsensusImp::endConsensus(), ripple::LedgerMasterImp::failedSave(), ripple::TransactionMaster::fetch(), ripple::UniqueNodeListImp::fetchNext(), ripple::SHAMap::fetchNodeExternalNT(), ripple::UniqueNodeListImp::fetchProcess(), ripple::LedgerMasterImp::findAcquireLedger(), ripple::LedgerMasterImp::findNewLedgersToPublish(), ripple::SHAMap::flushDirty(), ripple::NetworkOPsImp::getAccountTxs(), ripple::NetworkOPsImp::getAccountTxsB(), ripple::UniqueNodeListImp::getClusterFee(), ripple::FeaturesImpl::getCreate(), ripple::ValidationsImp::getCurrentTrustedValidations(), ripple::ValidationsImp::getCurrentValidations(), ripple::LedgerMasterImp::getFetchPack(), ripple::LedgerCleanerImp::getHash(), ripple::Ledger::getHashByIndex(), ripple::Ledger::getHashesByIndex(), ripple::UniqueNodeListImp::getIpsUrl(), ripple::Transaction::getJson(), ripple::PeerImp::getLedger(), ripple::NetworkOPsImp::getLedgerAffectedAccounts(), ripple::NetworkOPsImp::getLedgerFetchInfo(), ripple::LedgerCleanerImp::getLedgerHash(), ripple::SHAMap::getMissingNodes(), ripple::LedgerMasterImp::getNeededValidations(), ripple::NetworkOPsImp::getNetworkTimePT(), ripple::SHAMap::getNodeAsync(), ripple::PeerSet::getPeerCount(), ripple::LedgerMasterImp::getPublishedLedgerAge(), ripple::UniqueNodeListImp::getSeedDomains(), ripple::UniqueNodeListImp::getSeedNodes(), ripple::NetworkOPsImp::getServerInfo(), ripple::Ledger::getSLEi(), ripple::Ledger::getSQL(), ripple::Ledger::getSQL2(), ripple::Ledger::getTransaction(), ripple::LedgerConsensusImp::getTransactionTree(), ripple::NetworkOPsImp::getTxsAccount(), ripple::NetworkOPsImp::getTxsAccountB(), ripple::UniqueNodeListImp::getUnlJson(), ripple::LedgerMasterImp::getValidatedLedgerAge(), ripple::ValidationsImp::getValidationCount(), ripple::UniqueNodeListImp::getValidatorsUrl(), ripple::NetworkOPsImp::gotFetchPack(), ripple::InboundLedgersImp::gotLedgerData(), ripple::ConsensusTransSetSF::gotNode(), ripple::AccountStateSF::gotNode(), ripple::TransactionStateSF::gotNode(), ripple::InboundLedgersImp::gotStaleData(), ripple::LedgerConsensusImp::handleLCL(), ripple::PeerImp::handleReadBody(), ripple::LedgerConsensusImp::haveConsensus(), ripple::NetworkOPsImp::haveConsensusObject(), ripple::ConsensusTransSetSF::haveNode(), ripple::AccountStateSF::haveNode(), ripple::TransactionStateSF::haveNode(), ripple::InboundLedger::init(), ripple::PathRequest::isValid(), LADispatch(), ripple::Ledger::Ledger(), ripple::LedgerConsensusImp::LedgerConsensusImp(), ripple::LegacyPathFind::LegacyPathFind(), ripple::RPC::LegacyPathFind::LegacyPathFind(), ripple::Ledger::loadByHash(), ripple::Ledger::loadByIndex(), ripple::RPC::lookupLedger(), ripple::NetworkOPsImp::makeFetchPack(), ripple::PathRequests::makePathRequest(), ripple::UniqueNodeListImp::miscLoad(), ripple::UniqueNodeListImp::miscSave(), ripple::NetworkOPsImp::missingNodeInLedger(), ripple::LedgerMasterImp::newPFWork(), ripple::UniqueNodeListImp::nodeBootstrap(), ripple::LocalCredentials::nodeIdentityCreate(), ripple::LocalCredentials::nodeIdentityLoad(), ripple::UniqueNodeListImp::nodeNetwork(), ripple::UniqueNodeListImp::nodeRemoveDomain(), ripple::UniqueNodeListImp::nodeRemovePublic(), ripple::UniqueNodeListImp::nodeReset(), ripple::WSServerHandler< endpoint_type >::on_message(), ripple::UniqueNodeListImp::onDeadlineTimer(), ripple::NetworkOPsImp::onDeadlineTimer(), ripple::ApplicationImp::onDeadlineTimer(), ripple::TransactionAcquire::onTimer(), ripple::SHAMap::DefaultMissingNodeHandler::operator()(), ripple::Pathfinder::Pathfinder(), ripple::LedgerConsensusImp::peerHasSet(), ripple::Ledger::pendSaveValidated(), ripple::LedgerConsensusImp::playbackProposals(), ripple::NetworkOPsImp::processClusterTimer(), ripple::NetworkOPsImp::processHeartbeatTimer(), ripple::UniqueNodeListImp::processIps(), ripple::PeerImp::processReadBuffer(), ripple::RPCServerHandler::processRequest(), ripple::RPCHTTPServerImp::processRequest(), ripple::NetworkOPsImp::processTransactionCb(), ripple::NetworkOPsImp::processTrustedProposal(), ripple::UniqueNodeListImp::processValidators(), ripple::LedgerConsensusImp::propose(), ripple::NetworkOPsImp::pubLedger(), ripple::NetworkOPsImp::pubServer(), ripple::NetworkOPsImp::pubValidatedTransaction(), ripple::Ledger::qualityDirDescriber(), ripple::PeerImp::recvCluster(), ripple::PeerImp::recvGetLedger(), ripple::PeerImp::recvGetObjectByHash(), ripple::PeerImp::recvHaveTxSet(), ripple::PeerImp::recvHello(), ripple::PeerImp::recvLedger(), ripple::PeerImp::recvProofWork(), ripple::PeerImp::recvPropose(), ripple::PeerImp::recvStatus(), ripple::PeerImp::recvTransaction(), ripple::NetworkOPsImp::recvValidation(), ripple::PeerImp::recvValidation(), ripple::NetworkOPsImp::reportFeeChange(), ripple::FeaturesImpl::reportValidations(), ripple::LoadManagerImp::run(), ripple::ApplicationImp::run(), ripple::NetworkOPsImp::runTransactionQueue(), ripple::Ledger::saveValidatedLedger(), ripple::Ledger::scaleFeeBase(), ripple::Ledger::scaleFeeLoad(), ripple::UniqueNodeListImp::scoreCompute(), ripple::LedgerConsensusImp::sendHaveTxSet(), ripple::PeerImp::sendHello(), ripple::PeerSet::sendRequest(), serverOkay(), ripple::LedgerMasterImp::setFullLedger(), ripple::NetworkOPsImp::setMode(), ripple::Ledger::setRaw(), ripple::UniqueNodeListImp::setSeedDomains(), ripple::UniqueNodeListImp::setSeedNodes(), ripple::OrderBookDB::setup(), ripple::ApplicationImp::setup(), setupServer(), ripple::LedgerMasterImp::setValidLedger(), ripple::LocalCredentials::start(), ripple::LedgerConsensusImp::startAcquiring(), startServer(), ripple::LedgerConsensusImp::statePreClose(), ripple::LedgerConsensusImp::statusChange(), ripple::NetworkOPsImp::subBook(), ripple::NetworkOPsImp::subLedger(), ripple::NetworkOPsImp::submitTransaction(), ripple::NetworkOPsImp::subServer(), ripple::NetworkOPsImp::switchLastClosedLedger(), TACompletionHandler(), ripple::InboundLedger::takeBase(), ripple::LedgerConsensusImp::takeInitialPosition(), ripple::TransactionAcquire::takeNodes(), ripple::PeerSet::TimerEntry(), ripple::TransactionAcquire::TransactionAcquire(), ripple::Transaction::transactionFromSQL(), ripple::RPC::transactionSign(), ripple::TransactionAcquire::trigger(), ripple::InboundLedger::trigger(), ripple::UniqueNodeListImp::trustedLoad(), ripple::LedgerMasterImp::tryAdvance(), ripple::LedgerMasterImp::tryFill(), ripple::InboundLedger::tryLocal(), ripple::NetworkOPsImp::tryStartConsensus(), ripple::NetworkOPsImp::unsubBook(), ripple::OrderBookDB::update(), ripple::PathRequests::updateAll(), ripple::LedgerMasterImp::updatePaths(), ripple::ApplicationImp::updateTables(), ripple::Ledger::visitStateItems(), and ripple::InboundLedger::~InboundLedger().
 {
     return ApplicationImpBase::getInstance ();
 }
Config & ripple::getConfig ()
Definition at line 647 of file Config.cpp.
Referenced by ripple::RPC::authorize(), ripple::RPC::autofill_fee(), ripple::Transactor::calculateBaseFee(), ripple::DatabaseCon::DatabaseCon(), ripple::LedgerMasterImp::doAdvance(), ripple::RPCHandler::doCommand(), ripple::RPCHandler::doConnect(), ripple::RPCHandler::doLedgerAccept(), ripple::RPCHandler::doRipplePathFind(), ripple::ApplicationImp::doSweep(), ripple::RPCHandler::doUnlLoad(), ripple::PathRequest::doUpdate(), ripple::RPCHandler::doValidationSeed(), ripple::RPCCall::fromCommandLine(), ripple::RPCCall::fromNetwork(), ripple::LedgerMasterImp::getEarliestFetch(), ripple::Script::Operation::getFee(), ripple::LedgerMasterImp::getNeededValidations(), ripple::NetworkOPsImp::getServerInfo(), ripple::LedgerProposal::getSigningHash(), ripple::SerializedTransaction::getSigningHash(), ripple::SerializedValidation::getSigningHash(), ripple::HTTPClientImp::handleConnect(), HTTPAuthorized(), ripple::HTTPClientImp::HTTPClientImp(), ripple::HTTPClientSSLContext::HTTPClientSSLContext(), HTTPReply(), ripple::WSConnection::invokeCommand(), ripple::RPCDoorImp::isClientAllowed(), ripple::NodeStore::LevelDBBackend::LevelDBBackend(), ripple::NodeStore::LevelDBFactory::LevelDBFactory(), ripple::UniqueNodeListImp::nodeBootstrap(), ripple::LocalCredentials::nodeIdentityCreate(), ripple::LocalCredentials::nodeIdentityLoad(), ripple::UniqueNodeListImp::nodeNetwork(), ripple::UniqueNodeListImp::nodeProcess(), ripple::RPCHTTPServerImp::onAccept(), ripple::ApplicationImp::onDeadlineTimer(), ripple::OverlayImpl::onPrepare(), ripple::ApplicationImp::prepareValidators(), ripple::NetworkOPsImp::processHeartbeatTimer(), ripple::RPCServerHandler::processRequest(), ripple::RPCHTTPServerImp::processRequest(), ripple::LedgerMasterImp::pushLedger(), ripple::PeerImp::recvPropose(), ripple::RPCDoorImp::RPCDoorImp(), ripple::RPCHTTPServerImp::RPCHTTPServerImp(), run(), ripple::ApplicationImp::run(), runUnitTests(), ripple::PeerImp::sendHello(), ripple::HTTPClient::sendSMS(), serverOkay(), ripple::WSConnectionType< endpoint_type >::setPingTimer(), ripple::OrderBookDB::setup(), ripple::RPCHTTPServerImp::setup(), ripple::ApplicationImp::setup(), ripple::SqliteBackend::SqliteBackend(), ripple::LocalCredentials::start(), startServer(), ripple::NetworkOPsImp::subServer(), ripple::LedgerConsensusImp::takeInitialPosition(), ripple::RPC::transactionSign(), ripple::UniqueNodeListImp::trustedLoad(), ripple::Ledger::updateFees(), ripple::LedgerMasterImp::updatePaths(), ripple::ApplicationImp::updateTables(), ripple::UniqueNodeListImp::validatorsResponse(), and ripple::RPCDoorImp::~RPCDoorImp().
 {
     static Config config;
     return config;
 }
std::string ripple::getHTTPHeaderTimestamp ()
Definition at line 84 of file RPCUtil.cpp.
Referenced by HTTPReply().
 {
     // CHECKME This is probably called often enough that optimizing it makes
     //         sense. There's no point in doing all this work if this function
     //         gets called multiple times a second.
     char buffer[96];
     time_t now;
     time (&now);
     struct tm* now_gmt = gmtime (&now);
     std::string locale (setlocale (LC_TIME, nullptr));
     setlocale (LC_TIME, "C"); // we want posix (aka "C") weekday/month strings
     strftime (buffer, sizeof (buffer),
         "Date: %a, %d %b %Y %H:%M:%S +0000\r\n",
         now_gmt);
     setlocale (LC_TIME, locale.c_str ());
     return std::string (buffer);
 }
static std::vector<std::string> ripple::getSchema (DatabaseCon * dbc, const std::string & dbName) static
Definition at line 1229 of file Application.cpp.
References ripple::DatabaseCon::getDB(), ripple::Database::getStr(), and SQL_FOREACH.
Referenced by schemaHas().
 {
     std::vector<std::string> schema;
     std::string sql = "SELECT sql FROM sqlite_master WHERE tbl_name='";
     sql += dbName;
     sql += "';";
     SQL_FOREACH (dbc->getDB (), sql)
     {
         dbc->getDB ()->getStr ("sql", sql);
         schema.push_back (sql);
     }
     return schema;
 }
static uint256 ripple::getSHA512Half (const std::vector< uint256 > & vec) static
Definition at line 93 of file ProofOfWork.cpp.
References ripple::Serializer::getSHA512Half().
Referenced by ripple::ProofOfWork::checkSolution(), and ripple::ProofOfWork::solve().
 {
     return Serializer::getSHA512Half (vec.front ().begin (), vec.size () * (256 / 8));
 }
std::string ripple::gFormatStr ("v1")
Referenced by FormatFullVersion().
uint160 ripple::Hash160 (Blob const & vch)
Definition at line 22 of file HashUtilities.cpp.
Referenced by ripple::RippleAddress::getAccountID(), and ripple::RippleAddress::getNodeID().
 {
     uint256 hash1;
     SHA256 (&vch[0], vch.size (), (unsigned char*)&hash1);
     uint160 hash2;
     RIPEMD160 ((unsigned char*)&hash1, sizeof (hash1), (unsigned char*)&hash2);
     return hash2;
 }
template<class Hasher , class Traits > void ripple::hash_append (Hasher & h, IdentifierType< Traits > const & id) inline
Definition at line 172 of file IdentifierType.h.
References beast::hash_append(), and value.
 {
     using beast::hash_append;
     hash_append (h, id.value());
 }
std::size_t ripple::hash_value (const aciSource & asValue)
Definition at line 31 of file PathState.cpp.
 {
     std::size_t const seed = 0;
     return beast::hardened_hash<aciSource>{seed}(asValue);
 }
std::size_t ripple::hash_value (const SHAMapNode & mn)
Definition at line 112 of file SHAMap.cpp.
References ripple::SHAMapNode::getMHash().
 {
     return mn.getMHash ();
 }
std::size_t ripple::hash_value (const CBase58Data & b58)
Definition at line 140 of file Base58Data.cpp.
References ripple::HashMaps::getInstance(), ripple::HashMaps::getNonce(), ripple::HashMaps::goldenRatio, ripple::CBase58Data::nVersion, and ripple::CBase58Data::vchData.
 {
     std::size_t seed = HashMaps::getInstance ().getNonce <size_t> ()
                        + (b58.nVersion * HashMaps::goldenRatio);
     boost::hash_combine (seed, b58.vchData);
     return seed;
 }
std::size_t ripple::hash_value (const uint160 & u)
Definition at line 22 of file UInt128.cpp.
References ripple::HashMaps::getInstance(), and ripple::HashMaps::getNonce().
 {
     std::size_t seed = HashMaps::getInstance ().getNonce <std::size_t> ();
     return beast::hardened_hash<uint160>{seed}(u);
 }
std::size_t ripple::hash_value (uint256 const & u)
Definition at line 22 of file UInt256.cpp.
References ripple::HashMaps::getInstance(), and ripple::HashMaps::getNonce().
 {
     std::size_t seed = HashMaps::getInstance ().getNonce <size_t> ();
     return beast::hardened_hash<uint256>{seed}(u);
 }
bool ripple::HaveSustain ()
Definition at line 99 of file Sustain.cpp.
Referenced by run().
 {
     return false;
 }
template<class FwdIter , class Container > void ripple::hex_to_binary (FwdIter first, FwdIter last, Container & out)
Definition at line 276 of file ECDSACanonical.cpp.
Referenced by ripple::ECDSACanonical_test::loadSignature().
 {
     struct Table
     {
         int val[256];
         Table ()
         {
             std::fill (val, val+256, 0);
             for (int i = 0; i < 10; ++i)
                 val ['0'+i] = i;
             for (int i = 0; i < 6; ++i)
             {
                 val ['A'+i] = 10 + i;
                 val ['a'+i] = 10 + i;
             }
         }
         int operator[] (int i)
         {
            return val[i];
         }
     };
     static Table lut;
     out.reserve (std::distance (first, last) / 2);
     while (first != last)
     {
         auto const hi (lut[(*first++)]);
         auto const lo (lut[(*first++)]);
         out.push_back ((hi*16)+lo);
     }
 }
bool ripple::HTTPAuthorized (const std::map< std::string, std::string > & mapHeaders)
Definition at line 268 of file RPCUtil.cpp.
References DecodeBase64(), getConfig(), ripple::Config::RPC_PASSWORD, and ripple::Config::RPC_USER.
Referenced by ripple::RPCServerHandler::isAuthorized(), and ripple::RPCHTTPServerImp::isAuthorized().
 {
     std::map<std::string, std::string>::const_iterator it = mapHeaders.find ("authorization");
     if ((it == mapHeaders.end ()) || (it->second.substr (0, 6) != "Basic "))
         return getConfig ().RPC_USER.empty () && getConfig ().RPC_PASSWORD.empty ();
     std::string strUserPass64 = it->second.substr (6);
     boost::trim (strUserPass64);
     std::string strUserPass = DecodeBase64 (strUserPass64);
     std::string::size_type nColon = strUserPass.find (":");
     if (nColon == std::string::npos)
         return false;
     std::string strUser = strUserPass.substr (0, nColon);
     std::string strPassword = strUserPass.substr (nColon + 1);
     return (strUser == getConfig ().RPC_USER) && (strPassword == getConfig ().RPC_PASSWORD);
 }
std::string ripple::HTTPReply (int nStatus, const std::string & strMsg)
Definition at line 102 of file RPCUtil.cpp.
References FormatFullVersion(), getConfig(), ripple::BuildInfo::getFullVersionString(), getHTTPHeaderTimestamp(), lsTRACE, ShouldLog, SYSTEM_NAME, beast::IP::to_string(), and WriteLog.
Referenced by ripple::RPCServerHandler::createResponse(), ripple::RPCHTTPServerImp::createResponse(), ErrorReply(), ripple::RPCServerHandler::processRequest(), and ripple::RPCHTTPServerImp::processRequest().
 {
     if (ShouldLog (lsTRACE, RPCLog))
     {
         WriteLog (lsTRACE, RPCLog) << "HTTP Reply " << nStatus << " " << strMsg;
     }
     std::string ret;
     if (nStatus == 401)
     {
         ret.reserve (512);
         ret.append ("HTTP/1.0 401 Authorization Required\r\n");
         ret.append (getHTTPHeaderTimestamp ());
         // CHECKME this returns a different version than the replies below. Is
         //         this by design or an accident or should it be using
         //         BuildInfo::getFullVersionString () as well?
         ret.append ("Server: " SYSTEM_NAME "-json-rpc/");
         ret.append (FormatFullVersion ());
         ret.append ("\r\n");
         // Be careful in modifying this! If you change the contents you MUST
         // update the Content-Length header as well to indicate the correct
         // size of the data.
         ret.append ("WWW-Authenticate: Basic realm=\"jsonrpc\"\r\n"
                     "Content-Type: text/html\r\n"
                     "Content-Length: 296\r\n"
                     "\r\n"
                     "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\r\n"
                     "\"http://www.w3.org/TR/1999/REC-html401-19991224/loose.dtd\">\r\n"
                     "<HTML>\r\n"
                     "<HEAD>\r\n"
                     "<TITLE>Error</TITLE>\r\n"
                     "<META HTTP-EQUIV='Content-Type' CONTENT='text/html; charset=ISO-8859-1'>\r\n"
                     "</HEAD>\r\n"
                     "<BODY><H1>401 Unauthorized.</H1></BODY>\r\n");
         return ret;
     }
     ret.reserve(256 + strMsg.length());
     switch (nStatus)
     {
     case 200: ret.append ("HTTP/1.1 200 OK\r\n"); break;
     case 400: ret.append ("HTTP/1.1 400 Bad Request\r\n"); break;
     case 403: ret.append ("HTTP/1.1 403 Forbidden\r\n"); break;
     case 404: ret.append ("HTTP/1.1 404 Not Found\r\n"); break;
     case 500: ret.append ("HTTP/1.1 500 Internal Server Error\r\n"); break;
     }
     ret.append (getHTTPHeaderTimestamp ());
     ret.append ("Connection: Keep-Alive\r\n");
     if (getConfig ().RPC_ALLOW_REMOTE)
         ret.append ("Access-Control-Allow-Origin: *\r\n");
     ret.append ("Content-Length: ");
     ret.append (std::to_string(strMsg.size () + 2));
     ret.append ("\r\n");
     ret.append ("Content-Type: application/json; charset=UTF-8\r\n");
     ret.append ("Server: " SYSTEM_NAME "-json-rpc/");
     ret.append (BuildInfo::getFullVersionString ());
     ret.append ("\r\n");
     ret.append ("\r\n");
     ret.append (strMsg);
     ret.append ("\r\n");
     return ret;
 }
template<typename X , typename Y > std::enable_if_t< (std::is_integral<X>::value || std::is_enum<X>::value) && (std::is_integral<Y>::value || std::is_enum<Y>::value), bool> ripple::is_bit_set (X const x, Y const y) inline
Definition at line 40 of file PlatformMacros.h.
Referenced by ripple::LedgerEntrySet::accountSend(), ripple::Pathfinder::addLink(), ripple::TransactionEngine::applyTransaction(), ripple::RippleCalc::calcNodeAccountFwd(), ripple::RippleCalc::calcNodeAccountRev(), ripple::RippleCalc::calcNodeFwd(), ripple::RippleCalc::calcNodeRev(), ripple::Transactor::calculateFee(), ripple::PathState::checkNoRipple(), ripple::PeerImp::checkTransaction(), ripple::TrustSetTransactor::doApply(), ripple::AccountSetTransactor::doApply(), ripple::PaymentTransactor::doApply(), ripple::OfferCreateTransactor::doApply(), ripple::RippleState::getAuth(), ripple::RippleState::getAuthPeer(), ripple::PathState::Node::getJson(), ripple::Ledger::getJson(), ripple::RippleState::getNoRipple(), ripple::RippleState::getNoRipplePeer(), ripple::Pathfinder::isNoRipple(), ripple::Pathfinder::isNoRippleOut(), ripple::PathRequest::isValid(), ripple::Transactor::payFee(), ripple::Transactor::preCheck(), ripple::ChangeTransactor::preCheck(), ripple::PathState::pushNode(), ripple::PeerImp::recvTransaction(), ripple::LedgerEntrySet::rippleCredit(), and ripple::PathState::setCanonical().
 {
     return (x & y);
 }
template<class UnsignedInteger > bool ripple::is_not_xrp (UnsignedInteger const & value) inline
Definition at line 29 of file BookOffers.cpp.
References is_xrp().
Referenced by ripple::RPCHandler::doBookOffers().
 {
     return ! is_xrp (value);
 }
template<class UnsignedInteger > bool ripple::is_xrp (UnsignedInteger const & value) inline
Definition at line 23 of file BookOffers.cpp.
Referenced by ripple::RPCHandler::doBookOffers(), and is_not_xrp().
 {
     return value.isZero();
 }
bool ripple::isAccountFieldOkay (STObject const & st)
Definition at line 332 of file SerializedTransaction.cpp.
References ripple::STObject::getCount(), ripple::STAccount::isValueH160(), and ripple::STObject::peekAtPIndex().
Referenced by passesLocalChecks().
 {
     for (int i = 0; i < st.getCount(); ++i)
     {
         const STAccount* t = dynamic_cast<STAccount const*>(st.peekAtPIndex (i));
         if (t&& !t->isValueH160 ())
             return false;
     }
     return true;
 }
bool ripple::isCanonicalECDSASig (void const * vSig, size_t sigLen, ECDSA strict_param)
Checks whether a secp256k1 ECDSA signature is canonical. Return value is true if the signature is canonical. If mustBeStrict is specified, the signature must be strictly canonical (one and only one valid form). The return value for something that is not an ECDSA signature is unspecified. (But the function will not crash.)
Determine whether a signature is canonical. Canonical signatures are important to protect against signature morphing attacks.
Parameters
vSig the signature data
sigLen the length of the signature
strict_param whether to enforce strictly canonical semantics
Note
For more details please see: https://ripple.com/wiki/Transaction_Malleability https://bitcointalk.org/index.php?topic=8392.msg127623#msg127623 https://github.com/sipa/bitcoin/commit/58bc86e37fda1aec270bccb3df6c20fbd2a6591c
Definition at line 161 of file ECDSACanonical.cpp.
References ripple::detail::SignaturePart::getBigNum(), ripple::detail::modulus, ripple::detail::SignaturePart::skip(), and ripple::detail::SignaturePart::valid().
Referenced by ripple::RippleAddress::accountPublicVerify(), ripple::ECDSACanonical_test::convertNonCanonical(), isCanonicalECDSASig(), ripple::ECDSACanonical_test::isStrictlyCanonical(), ripple::ECDSACanonical_test::isValid(), and ripple::RippleAddress::verifyNodePublic().
 {
     // The format of a signature should be:
     // <30> <len> [ <02> <lenR> <R> ] [ <02> <lenS> <S> ]
     unsigned char const* sig = reinterpret_cast<unsigned char const*> (vSig);
     if ((sigLen < 8) || (sigLen > 72))
         return false;
     if ((sig[0] != 0x30) || (sig[1] != (sigLen - 2)))
         return false;
     // The first two bytes are verified. Eat them.
     sig += 2;
     sigLen -= 2;
     // Verify the R signature
     detail::SignaturePart sigR (sig, sigLen);
     if (!sigR.valid ())
         return false;
     // Eat the number of bytes we consumed
     sig += sigR.skip ();
     sigLen -= sigR.skip ();
     // Verify the S signature
     detail::SignaturePart sigS (sig, sigLen);
     if (!sigS.valid ())
         return false;
     // Eat the number of bytes we consumed
     sig += sigS.skip ();
     sigLen -= sigS.skip ();
     // Nothing should remain at this point.
     if (sigLen != 0)
         return false;
     // Check whether R or S are greater than the modulus.
     auto bnR (sigR.getBigNum ());
     auto bnS (sigS.getBigNum ());
     if (BN_cmp (bnR, detail::modulus) != -1)
         return false;
     if (BN_cmp (bnS, detail::modulus) != -1)
         return false;
     // For a given signature, (R,S), the signature (R, N-S) is also valid. For
     // a signature to be fully-canonical, the smaller of these two values must
     // be specified. If operating in strict mode, check that as well.
     if (strict_param == ECDSA::strict)
     {
         detail::BigNum mS;
         if (BN_sub (mS, detail::modulus, bnS) == 0)
             return false;
         if (BN_cmp (bnS, mS) == 1)
             return false;
     }
     return true;
 }
bool ripple::isCanonicalECDSASig (Blob const & signature, ECDSA mustBeStrict) inline
Definition at line 40 of file ECDSACanonical.h.
References isCanonicalECDSASig().
 {
     return signature.empty() ? false : isCanonicalECDSASig (&signature[0], signature.size(), mustBeStrict);
 }
bool ripple::isMemoOkay (STObject const & st)
Definition at line 317 of file SerializedTransaction.cpp.
References ripple::STArray::add(), ripple::Serializer::getDataLength(), ripple::STObject::getFieldArray(), and ripple::STObject::isFieldPresent().
Referenced by passesLocalChecks().
 {
     if (!st.isFieldPresent (sfMemos))
         return true;
     // The number 2048 is a preallocation hint, not a hard limit
     // to avoid allocate/copy/free's
     Serializer s (2048);
     st.getFieldArray (sfMemos).add (s);
     // FIXME move the memo limit into a config tunable
     if (s.getDataLength () > 1024)
         return false;
     return true;
 }
bool ripple::isRpcError (Json::Value jvResult)
Definition at line 34 of file RPCErr.cpp.
References Json::Value::isMember(), and Json::Value::isObject().
Referenced by ripple::RPCParser::parseBookOffers().
 {
     return jvResult.isObject () && jvResult.isMember ("error");
 }
static bool ripple::isSwitchChar (char c) inline static
Definition at line 28 of file RPCCall.cpp.
 {
 #ifdef __WXMSW__
     return c == '-' || c == '/';
 #else
     return c == '-';
 #endif
 }
int ripple::iToSeconds (boost::posix_time::ptime ptWhen)
Definition at line 34 of file Time.cpp.
References ptEpoch().
Referenced by ripple::NetworkOPsImp::getCloseTimeNC(), ripple::NetworkOPsImp::getNetworkTimeNC(), ripple::UniqueNodeListImp::miscSave(), ripple::Ledger::setCloseTime(), ripple::UniqueNodeListImp::setSeedDomains(), and ripple::UniqueNodeListImp::setSeedNodes().
 {
     return ptWhen.is_not_a_date_time ()
            ? -1
            : (ptWhen - ptEpoch ()).total_seconds ();
 }
Json::Value ripple::JSONRPCError (int code, const std::string & message)
Definition at line 38 of file RPCUtil.cpp.
References Json::objectValue, and rocksdb::crc32c::Value().
 {
     Json::Value error (Json::objectValue);
     error["code"]       = Json::Value (code);
     error["message"]    = Json::Value (message);
     return error;
 }
std::string ripple::JSONRPCReply (const Json::Value & result, const Json::Value & error, const Json::Value & id)
Definition at line 307 of file RPCUtil.cpp.
References Json::objectValue, and Json::FastWriter::write().
Referenced by ErrorReply(), ripple::RPCServerHandler::processRequest(), and ripple::RPCHTTPServerImp::processRequest().
 {
     Json::Value reply (Json::objectValue);
     reply["result"] = result;
     //reply["error"]=error;
     //reply["id"]=id;
     Json::FastWriter writer;
     return writer.write (reply) + "\n";
 }
std::string ripple::JSONRPCRequest (const std::string & strMethod, const Json::Value & params, const Json::Value & id)
Definition at line 297 of file RPCUtil.cpp.
References id, and Json::FastWriter::write().
Referenced by ripple::RPCCallImp::onRequest().
 {
     Json::Value request;
     request["method"] = strMethod;
     request["params"] = params;
     request["id"] = id;
     Json::FastWriter writer;
     return writer.write (request) + "\n";
 }
static void ripple::LADispatch (Job & job, InboundLedger::pointer la, std::vector< std::function< void(InboundLedger::pointer)> > trig) static
Dispatch acquire completion
Definition at line 350 of file InboundLedger.cpp.
References ripple::LedgerMaster::checkAccept(), getApp(), ripple::Application::getLedgerMaster(), and ripple::LedgerMaster::tryAdvance().
Referenced by ripple::InboundLedger::done().
 {
     if (la->isComplete() && !la->isFailed())
     {
         getApp().getLedgerMaster().checkAccept(la->getLedger());
         getApp().getLedgerMaster().tryAdvance();
     }
     for (unsigned int i = 0; i < trig.size (); ++i)
         trig[i] (la);
 }
Json::Value const & ripple::logRPCError (Json::Value const & json)
Definition at line 39 of file RPCErr.cpp.
References ripple::RPC::contains_error(), lsDEBUG, and WriteLog.
Referenced by ripple::RPCHandler::doRpcCommand().
 {
     if (RPC::contains_error (json))
     {
         WriteLog (lsDEBUG, RPCErr) <<
             "rpcError: " << json ["error"] <<
             ": " << json ["error_message"];
     }
     return json;
 }
template<typename Function > void ripple::logTimedCall (beast::Journal::Stream stream, beast::String description, char const * fileName, int lineNumber, Function f, double thresholdSeconds = 1)
Log a timed function call if the time exceeds a threshold.
Definition at line 121 of file LoggedTimings.h.
References ripple::detail::cleanElapsed(), beast::Debug::getSourceLocation(), and beast::measureFunctionCallTime().
Referenced by ripple::ApplicationImp::doSweep().
 {
     double const seconds = beast::measureFunctionCallTime (f);
     if (seconds > thresholdSeconds)
     {
         stream <<
             description << " took "<<
                 beast::String (detail::cleanElapsed (seconds)) <<
                 " seconds to execute at " <<
                     beast::Debug::getSourceLocation (fileName, lineNumber);
     }
 }
template<typename PartitionKey , typename Object > void ripple::logTimedDestroy (Object & object, beast::String objectDescription, double thresholdSeconds = 1)
Log the timed destruction of an object if the time exceeds a threshold.
Definition at line 101 of file LoggedTimings.h.
References ripple::detail::cleanElapsed(), rocksdb::Log(), lsWARNING, and timedDestroy().
 {
     double const seconds = timedDestroy (object);
     if (seconds > thresholdSeconds)
     {
         LogSeverity const severity = lsWARNING;
         Log (severity, LogPartition::get <PartitionKey> ()) <<
             objectDescription << " took "<<
             beast::String (detail::cleanElapsed (seconds)) <<
             " seconds to destroy";
     }
 }
static int const ripple::MAJORITY_FRACTION (200) static
std::unique_ptr< Application > ripple::make_Application ()
Create an instance of the Application object. As long as there are legacy calls to getApp it is not safe to create more than one Application object at a time.
Definition at line 1382 of file Application.cpp.
Referenced by run(), and runUnitTests().
 {
     return std::make_unique <ApplicationImp> ();
 }
RippleAsset ripple::make_asset (Json::Value json, std::string const & currency_field, std::string const & issuer_field, Json::Value * result)
Create an asset specifier by parsing the given JSON. Errors, if any, will be returned or injected into the specified result JSON object using the JSON-RPC error specification interface.
Parameters
currency_field The JSON field name of the currency specifier
issuer_field The JSON field name of the issuer specifier
result The JSON in which to store any errors. #return An asset representing the parsed JSON if no errors occurred.
std::unique_ptr< FeatureTable > ripple::make_FeatureTable (std::chrono::seconds majorityTime, int majorityFraction, beast::Journal journal)
Definition at line 575 of file FeaturesImpl.cpp.
 {
     return std::make_unique<FeaturesImpl> (majorityTime, majorityFraction,
         journal);
 }
std::unique_ptr< FeeVote > ripple::make_FeeVote (std::uint64_t targetBaseFee, std::uint32_t targetReserveBase, std::uint32_t targetReserveIncrement, beast::Journal journal)
Definition at line 226 of file FeeVoteImpl.cpp.
 {
     return std::make_unique<FeeVoteImpl> (targetBaseFee, targetReserveBase,
         targetReserveIncrement, journal);
 }
std::unique_ptr< JobQueue > ripple::make_JobQueue (beast::insight::Collector::ptr const & collector, beast::Stoppable & parent, beast::Journal journal)
Definition at line 676 of file JobQueue.cpp.
 {
     return std::make_unique <JobQueueImp> (collector, parent, journal);
 }
boost::shared_ptr< LedgerConsensus > ripple::make_LedgerConsensus (LedgerConsensus::clock_type & clock, LocalTxs & localtx, LedgerHash const & prevLCLHash, Ledger::ref previousLedger, std::uint32_t closeTime, FeeVote & feeVote)
Definition at line 1949 of file LedgerConsensus.cpp.
Referenced by ripple::NetworkOPsImp::beginConsensus().
 {
     return boost::make_shared <LedgerConsensusImp> (clock, localtx,
         prevLCLHash, previousLedger, closeTime, feeVote);
 }
std::unique_ptr< Overlay > ripple::make_Overlay (beast::Stoppable & parent, Resource::Manager & resourceManager, SiteFiles::Manager & siteFiles, beast::File const & pathToDbFileOrDirectory, Resolver & resolver, boost::asio::io_service & io_service, boost::asio::ssl::context & ssl_context)
Creates the implementation of Overlay.
Parameters
parent
resourceManager
siteFiles
pathToDbFileOrDirectory
resolver
io_service
context
Definition at line 585 of file OverlayImpl.cpp.
Referenced by ripple::ApplicationImp::setup().
 {
     return std::make_unique <OverlayImpl> (parent, resourceManager, siteFiles,
         pathToDbFileOrDirectory, resolver, io_service, ssl_context);
 }
std::unique_ptr< PeerDoor > ripple::make_PeerDoor (PeerDoor::Kind kind, OverlayImpl & overlay, std::string const & ip, int port, boost::asio::io_service & io_service)
Definition at line 137 of file PeerDoor.cpp.
References bassert.
Referenced by ripple::OverlayImpl::onPrepare().
 {
     // You have to listen on something!
     bassert(port != 0);
     boost::asio::ip::tcp::endpoint ep(
         boost::asio::ip::address ().from_string (
             ip.empty () ? "0.0.0.0" : ip), port);
     return std::make_unique<PeerDoorImp>(kind, overlay, ep, io_service);
 }
std::unique_ptr< NodeStore::Factory > ripple::make_SqliteFactory ()
Factory to produce SQLite backends for the NodeStore.
See Also
Database
Definition at line 243 of file SqliteFactory.cpp.
Referenced by ripple::ApplicationImp::make_Factories().
 {
     return std::make_unique <SqliteFactory> ();
 }
bool ripple::makeCanonicalECDSASig (void * vSig, size_t & sigLen)
Converts a canonical secp256k1 ECDSA signature to a fully-canonical one. Returns true if the original signature was already fully-canonical. The behavior if something that is not a canonical secp256k1 ECDSA signature is passed is unspecified. The signature buffer must be large enough to accommodate the largest valid fully-canonical secp256k1 ECDSA signature (72 bytes).
Convert a signature into strictly canonical form. Given the signature (R, S) then (R, G-S) is also valid. For a signature to be canonical, the smaller of { S, G-S } must be specified.
Parameters
vSig the signature we wish to convert
sigLen the length of the signature
Returns
true if the signature was already canonical, false otherwise
Definition at line 236 of file ECDSACanonical.cpp.
References ripple::detail::modulus.
Referenced by ripple::ECDSACanonical_test::convertNonCanonical(), and ripple::CKey::Sign().
 {
     unsigned char * sig = reinterpret_cast<unsigned char *> (vSig);
     bool ret = false;
     // Find internals
     int rLen = sig[3];
     int sPos = rLen + 6, sLen = sig[rLen + 5];
     detail::BigNum origS, newS;
     BN_bin2bn (&sig[sPos], sLen, origS);
     BN_sub (newS, detail::modulus, origS);
     if (BN_cmp (origS, newS) == 1)
     { // original signature is not fully canonical
         unsigned char newSbuf [64];
         int newSlen = BN_bn2bin (newS, newSbuf);
         if ((newSbuf[0] & 0x80) == 0)
         { // no extra padding byte is needed
             sig[1] = sig[1] - sLen + newSlen;
             sig[sPos - 1] = newSlen;
             memcpy (&sig[sPos], newSbuf, newSlen);
         }
         else
         { // an extra padding byte is needed
             sig[1] = sig[1] - sLen + newSlen + 1;
             sig[sPos - 1] = newSlen + 1;
             sig[sPos] = 0;
             memcpy (&sig[sPos + 1], newSbuf, newSlen);
         }
         sigLen = sig[1] + 2;
     }
     else
         ret = true;
     return ret;
 }
static BIGNUM* ripple::makeHash (const RippleAddress & pubGen, int seq, BIGNUM * order) static
Definition at line 191 of file CKeyDeterministic.cpp.
References ripple::Serializer::add32(), ripple::Serializer::addRaw(), ripple::RippleAddress::getGenerator(), ripple::Serializer::getSHA512Half(), and ripple::Serializer::secureErase().
Referenced by ripple::CKey::GeneratePrivateDeterministicKey(), and ripple::CKey::GeneratePublicDeterministicKey().
 {
     int subSeq = 0;
     BIGNUM* ret = nullptr;
     do
     {
         Serializer s ((33 * 8 + 32 + 32) / 8);
         s.addRaw (pubGen.getGenerator ());
         s.add32 (seq);
         s.add32 (subSeq++);
         uint256 root = s.getSHA512Half ();
         s.secureErase ();
         ret = BN_bin2bn ((const unsigned char*) &root, sizeof (root), ret);
         if (!ret) return nullptr;
     }
     while (BN_is_zero (ret) || (BN_cmp (ret, order) >= 0));
     return ret;
 }
static ECIES_HMAC_TYPE ripple::makeHMAC (const ECIES_HMAC_KEY_TYPE & secret, Blob const & data) static
Definition at line 97 of file CKeyECIES.cpp.
References ECIES_HMAC_ALGO, ECIES_HMAC_KEY_SIZE, ECIES_HMAC_SIZE, and ECIES_HMAC_TYPE.
Referenced by ripple::CKey::decryptECIES(), and ripple::CKey::encryptECIES().
 {
     HMAC_CTX ctx;
     HMAC_CTX_init (&ctx);
     if (HMAC_Init_ex (&ctx, secret.begin (), ECIES_HMAC_KEY_SIZE, ECIES_HMAC_ALGO, nullptr) != 1)
     {
         HMAC_CTX_cleanup (&ctx);
         throw std::runtime_error ("init hmac");
     }
     if (HMAC_Update (&ctx, & (data.front ()), data.size ()) != 1)
     {
         HMAC_CTX_cleanup (&ctx);
         throw std::runtime_error ("update hmac");
     }
     ECIES_HMAC_TYPE ret;
     unsigned int ml = ECIES_HMAC_SIZE;
     if (HMAC_Final (&ctx, ret.begin (), &ml) != 1)
     {
         HMAC_CTX_cleanup (&ctx);
         throw std::runtime_error ("finalize hmac");
     }
     assert (ml == ECIES_HMAC_SIZE);
     HMAC_CTX_cleanup (&ctx);
     return ret;
 }
std::uint32_t ripple::max (std::uint32_t x, std::uint32_t y) inline
Definition at line 35 of file RangeSet.cpp.
Referenced by ripple::LedgerConsensusImp::addLoad(), ripple::PeerFinder::Sim::breadth_first_traverse(), rocksdb::BuildTable(), ripple::PeerFinder::Config::calcOutPeers(), beast::UnsignedIntegerCalc< UInt >::compare(), parse_gcov_output::display_file_coverage(), beast::insight::detail::StatsDGaugeImpl::do_increment(), ripple::PaymentTransactor::doApply(), rocksdb::DBImpl::DoCompactionWork(), ripple::Validators::SourceFileImp::fetch(), ripple::InboundLedger::filterNodes(), rocksdb::Env::GenerateUniqueId(), rocksdb::GetCompressionType(), getDigits(), ripple::SHAMap::getFetchPack(), ripple::LoadFeeTrackImp::getJson(), ripple::LoadFeeTrackImp::getLoadFactor(), rocksdb::ReduceDBLevelsCommand::GetOldNumOfLevels(), rocksdb::Version::GetOverlappingInputsBinarySearch(), ripple::FeeVoteImpl::VotableInteger< Integer >::getVotes(), ripple::NodeStore::BatchWriter::getWriteLoad(), ripple::JobTypes::JobTypes(), ripple::Config::load(), rocksdb::DBImpl::MakeRoomForWrite(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::max_load_factor(), minmaxStep(), beast::String::operator+=(), ripple::core::Quality::operator--(), std::chrono::operator>>(), beast::SemanticVersion::parse(), beast::LexicalCastUtilities::parseSigned(), beast::LexicalCastUtilities::parseUnsigned(), rocksdb::VersionSet::PickCompactionUniversalReadAmp(), rocksdb::DBImpl::PurgeObsoleteWALFiles(), rocksdb::RandomGenerator::RandomGenerator(), rocksdb::RedisLists::Range(), beast::CharacterFunctions::readDoubleValue(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::rehash(), rocksdb::DBImpl::RetainProbableWalFiles(), beast::DeadlineTimer::Manager::run(), ripple::LoadFeeTrackImp::scaleFeeLoad(), ripple::RangeSet::simplify(), sqlite3RegisterGlobalFunctions(), ripple::LedgerConsensusImp::statePreClose(), beast::String::String(), beast::LexicalCast_test::testIntegers(), rocksdb::RedisLists::Trim(), ValidateUint32Range(), and beast::OutputStream::writeFromInputStream().
 {
     return (x > y) ? x : y;
 }
std::uint32_t ripple::min (std::uint32_t x, std::uint32_t y) inline
Definition at line 31 of file RangeSet.cpp.
Referenced by rocksdb::BlockBuilder::Add(), ripple::OfferCreateTransactor::applyOffer(), rocksdb::BuildTable(), ripple::RippleCalc::calcNodeAccountFwd(), ripple::RippleCalc::calcNodeAccountRev(), ripple::RippleCalc::calcNodeDeliverFwd(), ripple::RippleCalc::calcNodeDeliverRev(), ripple::RippleCalc::calcNodeRipple(), ripple::CryptoIdentifier< Size, Token, Checked >::base::createFromInteger(), beast::UnsignedInteger< Bytes >::createFromInteger(), ContentBodyBuffer::data(), beast::DynamicBuffer::data(), rocksdb::DBImpl::DoCompactionWork(), ripple::PeerFinder::Fixed::failure(), ripple::NetworkOPsImp::getBookPage(), rocksdb::GetCompressionType(), getDigits(), rocksdb::Version::GetOverlappingInputsBinarySearch(), ripple::FeeVoteImpl::VotableInteger< Integer >::getVotes(), ripple::LocalTx::LocalTx(), beast::asio::InputParser::match_buffer(), beast::block_stream< std::size_t, prng_hasher< PRNG > >::operator()(), beast::LexicalCastUtilities::parseSigned(), rocksdb::VersionSet::PickCompactionUniversalReadAmp(), ContentBodyBuffer::prepare(), beast::DynamicBuffer::prepare(), ripple::UniqueNodeListImp::processIps(), ripple::UniqueNodeListImp::processValidators(), rocksdb::BlobStore::Put(), rocksdb::RedisLists::Range(), rocksdb::Benchmark::ReadHot(), rocksdb::Benchmark::ReadMissing(), rocksdb::Benchmark::ReadRandom(), rocksdb::Benchmark::ReadRandomWriteRandomMultiGet(), rocksdb::RedisLists::RemoveLast(), ripple::Log::replaceFirstSecretWithAsterisks(), ripple::LogSink::replaceFirstSecretWithAsterisks(), rocksdb::SanitizeOptions(), sqlite3RegisterGlobalFunctions(), ripple::Validators::Utilities::stringToTime(), ripple::OfferCreateTransactor::takeOffers(), rocksdb::TEST(), beast::LexicalCast_test::testIntegers(), beast::DynamicBuffer::to_string(), ripple::NetworkOPsImp::transactionsSQL(), and rocksdb::RedisLists::Trim().
 {
     return (x < y) ? x : y;
 }
uint160 const& ripple::neutral_issuer () inline
Definition at line 44 of file BookOffers.cpp.
References ACCOUNT_ONE.
Referenced by ripple::RPCHandler::doBookOffers().
 {
     return ACCOUNT_ONE;
 }
SerializedType* ripple::new_clone (const SerializedType & s) inline
Definition at line 202 of file SerializedTypes.h.
References ripple::SerializedType::clone().
 {
     SerializedType* const copy (s.clone ().release ());
     assert (typeid (*copy) == typeid (s));
     return copy;
 }
static void ripple::offerAdder (Json::Value & jvLines, SLE::ref offer) static
Definition at line 23 of file AccountOffers.cpp.
References Json::Value::append(), ltOFFER, and Json::objectValue.
Referenced by ripple::RPCHandler::doAccountOffers().
 {
     if (offer->getType () == ltOFFER)
     {
         Json::Value&    obj = jvLines.append (Json::objectValue);
         offer->getFieldAmount (sfTakerPays).setJson (obj["taker_pays"]);
         offer->getFieldAmount (sfTakerGets).setJson (obj["taker_gets"]);
         obj["seq"] = offer->getFieldU32 (sfSequence);
         obj["flags"] = offer->getFieldU32 (sfFlags);
     }
 }
bool ripple::operator!= (const uint160 & a, std::uint64_t b) inline
Definition at line 92 of file UInt160.h.
 {
     return (base_uint160)a != b;
 }
bool ripple::operator!= (const CBigNum & a, const CBigNum & b)
Definition at line 595 of file CBigNum.cpp.
 {
     return (BN_cmp (&a, &b) != 0);
 }
bool ripple::operator!= (uint256 const & a, std::uint64_t b) inline
Definition at line 107 of file UInt256.h.
 {
     return (base_uint256)a != b;
 }
bool ripple::operator!= (const base_uint160 & a, const uint160 & b) inline
Definition at line 117 of file UInt160.h.
 {
     return (base_uint160)a != (base_uint160)b;
 }
template<bool LhsByValue, bool RhsByValue> bool ripple::operator!= (RippleAssetType< LhsByValue > const & lhs, RippleAssetType< RhsByValue > const & rhs)
Definition at line 131 of file RippleAssets.h.
 {
     return ! (lhs == rhs);
 }
bool ripple::operator!= (const base_uint256 & a, uint256 const & b) inline
Definition at line 132 of file UInt256.h.
 {
     return (base_uint256)a != (base_uint256)b;
 }
bool ripple::operator!= (const uint160 & a, const base_uint160 & b) inline
Definition at line 141 of file UInt160.h.
 {
     return (base_uint160)a != (base_uint160)b;
 }
template<std::size_t PrePadSize, std::size_t Size, std::size_t PostPadSize> bool ripple::operator!= (IdentifierStorage< PrePadSize, Size, PostPadSize > const & lhs, IdentifierStorage< PrePadSize, Size, PostPadSize > const & rhs)
Definition at line 154 of file IdentifierStorage.h.
 {
     return !(lhs==rhs);
 }
bool ripple::operator!= (uint256 const & a, const base_uint256 & b) inline
Definition at line 157 of file UInt256.h.
 {
     return (base_uint256)a != (base_uint256)b;
 }
bool ripple::operator!= (const uint160 & a, const uint160 & b) inline
Definition at line 165 of file UInt160.h.
 {
     return (base_uint160)a != (base_uint160)b;
 }
bool ripple::operator!= (uint256 const & a, uint256 const & b) inline
Definition at line 182 of file UInt256.h.
 {
     return (base_uint256)a != (base_uint256)b;
 }
template<class Traits > bool ripple::operator!= (IdentifierType< Traits > const & lhs, IdentifierType< Traits > const & rhs)
Definition at line 186 of file IdentifierType.h.
References ripple::IdentifierType< Traits >::value().
 { return lhs.value() != rhs.value(); }
template<bool LhsByValue, bool RhsByValue> bool ripple::operator!= (RippleBookType< LhsByValue > const & lhs, RippleBookType< RhsByValue > const & rhs)
Definition at line 270 of file RippleAssets.h.
References ripple::RippleBookType< ByValue >::in, and ripple::RippleBookType< ByValue >::out.
 {
     return (lhs.in != rhs.in) ||
            (lhs.out != rhs.out);
 }
const CBigNum ripple::operator% (const CBigNum & a, const CBigNum & b)
Definition at line 562 of file CBigNum.cpp.
 {
     CAutoBN_CTX pctx;
     CBigNum r;
     if (!BN_mod (&r, &a, &b, pctx))
         throw bignum_error ("CBigNum::operator% : BN_div failed");
     return r;
 }
const uint160 ripple::operator& (const base_uint160 & a, const base_uint160 & b) inline
Definition at line 102 of file UInt160.h.
 {
     return uint160 (a) &= b;
 }
TransactionEngineParams ripple::operator& (const TransactionEngineParams & l1, const TransactionEngineParams & l2) inline
Definition at line 117 of file TransactionEngine.h.
 {
     return static_cast<TransactionEngineParams> (static_cast<int> (l1) & static_cast<int> (l2));
 }
const uint256 ripple::operator& (const base_uint256 & a, const base_uint256 & b) inline
Definition at line 117 of file UInt256.h.
 {
     return uint256 (a) &= b;
 }
const uint160 ripple::operator& (const base_uint160 & a, const uint160 & b) inline
Definition at line 127 of file UInt160.h.
 {
     return (base_uint160)a &  (base_uint160)b;
 }
const uint256 ripple::operator& (const base_uint256 & a, uint256 const & b) inline
Definition at line 142 of file UInt256.h.
 {
     return (base_uint256)a &  (base_uint256)b;
 }
const uint160 ripple::operator& (const uint160 & a, const base_uint160 & b) inline
Definition at line 150 of file UInt160.h.
 {
     return (base_uint160)a &  (base_uint160)b;
 }
const uint256 ripple::operator& (uint256 const & a, const base_uint256 & b) inline
Definition at line 167 of file UInt256.h.
 {
     return uint256 (a) &= b;
 }
const uint160 ripple::operator& (const uint160 & a, const uint160 & b) inline
Definition at line 175 of file UInt160.h.
 {
     return (base_uint160)a &  (base_uint160)b;
 }
const uint256 ripple::operator& (uint256 const & a, uint256 const & b) inline
Definition at line 193 of file UInt256.h.
 {
     return (base_uint256)a &  (base_uint256)b;
 }
LedgerStateParms ripple::operator& (const LedgerStateParms & l1, const LedgerStateParms & l2) inline
Definition at line 524 of file Ledger.h.
 {
     return static_cast<LedgerStateParms> (static_cast<int> (l1) & static_cast<int> (l2));
 }
const CBigNum ripple::operator* (const CBigNum & a, const CBigNum & b)
Definition at line 540 of file CBigNum.cpp.
 {
     CAutoBN_CTX pctx;
     CBigNum r;
     if (!BN_mul (&r, &a, &b, pctx))
         throw bignum_error ("CBigNum::operator* : BN_mul failed");
     return r;
 }
const CBigNum ripple::operator+ (const CBigNum & a, const CBigNum & b)
Definition at line 513 of file CBigNum.cpp.
 {
     CBigNum r;
     if (!BN_add (&r, &a, &b))
         throw bignum_error ("CBigNum::operator+ : BN_add failed");
     return r;
 }
STAmount ripple::operator+ (const STAmount & v1, const STAmount & v2)
Definition at line 829 of file STAmount.cpp.
References ripple::SerializedType::getFName(), ripple::STAmount::getSNValue(), ripple::STAmount::mCurrency, ripple::STAmount::mIsNative, ripple::STAmount::mIsNegative, ripple::STAmount::mIssuer, ripple::STAmount::mOffset, ripple::STAmount::mValue, and ripple::STAmount::throwComparable().
 {
     v1.throwComparable (v2);
     if (v2 == zero)
         return v1;
     if (v1 == zero)
     {
         // Result must be in terms of v1 currency and issuer.
         return STAmount (v1.getFName (), v1.mCurrency, v1.mIssuer, v2.mValue, v2.mOffset, v2.mIsNegative);
     }
     if (v1.mIsNative)
         return STAmount (v1.getFName (), v1.getSNValue () + v2.getSNValue ());
     int ov1 = v1.mOffset, ov2 = v2.mOffset;
     std::int64_t vv1 = static_cast<std::int64_t> (v1.mValue), vv2 = static_cast<std::int64_t> (v2.mValue);
     if (v1.mIsNegative) vv1 = -vv1;
     if (v2.mIsNegative) vv2 = -vv2;
     while (ov1 < ov2)
     {
         vv1 /= 10;
         ++ov1;
     }
     while (ov2 < ov1)
     {
         vv2 /= 10;
         ++ov2;
     }
     // this addition cannot overflow an std::int64_t, it can overflow an STAmount and the constructor will throw
     std::int64_t fv = vv1 + vv2;
     if ((fv >= -10) && (fv <= 10))
         return STAmount (v1.getFName (), v1.mCurrency, v1.mIssuer);
     else if (fv >= 0)
         return STAmount (v1.getFName (), v1.mCurrency, v1.mIssuer, fv, ov1, false);
     else
         return STAmount (v1.getFName (), v1.mCurrency, v1.mIssuer, -fv, ov1, true);
 }
const CBigNum ripple::operator- (const CBigNum & a, const CBigNum & b)
Definition at line 523 of file CBigNum.cpp.
 {
     CBigNum r;
     if (!BN_sub (&r, &a, &b))
         throw bignum_error ("CBigNum::operator- : BN_sub failed");
     return r;
 }
const CBigNum ripple::operator- (const CBigNum & a)
Definition at line 533 of file CBigNum.cpp.
 {
     CBigNum r (a);
     BN_set_negative (&r, !BN_is_negative (&r));
     return r;
 }
STAmount ripple::operator- (const STAmount & v1, const STAmount & v2)
Definition at line 876 of file STAmount.cpp.
References ripple::STAmount::createFromInt64(), ripple::SerializedType::getFName(), ripple::STAmount::getSNValue(), ripple::STAmount::mCurrency, ripple::STAmount::mIsNative, ripple::STAmount::mIsNegative, ripple::STAmount::mIssuer, ripple::STAmount::mOffset, ripple::STAmount::mValue, and ripple::STAmount::throwComparable().
 {
     v1.throwComparable (v2);
     if (v2 == zero)
         return v1;
     if (v2.mIsNative)
     {
         // XXX This could be better, check for overflow and that maximum range is covered.
         return STAmount::createFromInt64 (v1.getFName (), v1.getSNValue () - v2.getSNValue ());
     }
     int ov1 = v1.mOffset, ov2 = v2.mOffset;
     std::int64_t vv1 = static_cast<std::int64_t> (v1.mValue), vv2 = static_cast<std::int64_t> (v2.mValue);
     if (v1.mIsNegative) vv1 = -vv1;
     if (v2.mIsNegative) vv2 = -vv2;
     while (ov1 < ov2)
     {
         vv1 /= 10;
         ++ov1;
     }
     while (ov2 < ov1)
     {
         vv2 /= 10;
         ++ov2;
     }
     // this subtraction cannot overflow an std::int64_t, it can overflow an STAmount and the constructor will throw
     std::int64_t fv = vv1 - vv2;
     if ((fv >= -10) && (fv <= 10))
         return STAmount (v1.getFName (), v1.mCurrency, v1.mIssuer);
     else if (fv >= 0)
         return STAmount (v1.getFName (), v1.mCurrency, v1.mIssuer, fv, ov1, false);
     else
         return STAmount (v1.getFName (), v1.mCurrency, v1.mIssuer, -fv, ov1, true);
 }
const CBigNum ripple::operator/ (const CBigNum & a, const CBigNum & b)
Definition at line 551 of file CBigNum.cpp.
 {
     CAutoBN_CTX pctx;
     CBigNum r;
     if (!BN_div (&r, nullptr, &a, &b, pctx))
         throw bignum_error ("CBigNum::operator/ : BN_div failed");
     return r;
 }
bool ripple::operator< (const CBigNum & a, const CBigNum & b)
Definition at line 610 of file CBigNum.cpp.
 {
     return (BN_cmp (&a, &b) < 0);
 }
template<bool LhsByValue, bool RhsByValue> bool ripple::operator< (RippleAssetType< LhsByValue > const & lhs, RippleAssetType< RhsByValue > const & rhs)
Strict weak ordering.
Definition at line 141 of file RippleAssets.h.
References compare(), and lhs.
 {
     return compare (lhs, rhs) < 0;
 }
template<std::size_t PrePadSize, std::size_t Size, std::size_t PostPadSize> bool ripple::operator< (IdentifierStorage< PrePadSize, Size, PostPadSize > const & lhs, IdentifierStorage< PrePadSize, Size, PostPadSize > const & rhs)
Definition at line 161 of file IdentifierStorage.h.
References lhs.
 {
     return std::lexicographical_compare (lhs.begin(), lhs.end(), rhs.begin(), rhs.end());
 }
template<class Traits > bool ripple::operator< (IdentifierType< Traits > const & lhs, IdentifierType< Traits > const & rhs)
Definition at line 191 of file IdentifierType.h.
References lhs.
 { return lhs.value() < rhs.value(); }
template<bool LhsByValue, bool RhsByValue> bool ripple::operator< (RippleBookType< LhsByValue > const & lhs, RippleBookType< RhsByValue > const & rhs)
Strict weak ordering.
Definition at line 281 of file RippleAssets.h.
References compare(), and lhs.
 {
     int const diff (compare (lhs.in, rhs.in));
     if (diff != 0)
         return diff < 0;
     return lhs.out < rhs.out;
 }
std::ostream & ripple::operator<< (std::ostream & out, const SHAMapMissingNode & mn)
Definition at line 22 of file SHAMapMissingNode.cpp.
References ripple::SHAMapMissingNode::getMapType(), ripple::SHAMapMissingNode::getNodeHash(), ripple::SHAMapMissingNode::getNodeID(), smtFREE, smtSTATE, and smtTRANSACTION.
 {
     switch (mn.getMapType ())
     {
     case smtTRANSACTION:
         out << "Missing/TXN(" << mn.getNodeID () << "/" << mn.getNodeHash () << ")";
         break;
     case smtSTATE:
         out << "Missing/STA(" << mn.getNodeID () << "/" << mn.getNodeHash () << ")";
         break;
     case smtFREE:
     default:
         out << "Missing/" << mn.getNodeID ();
         break;
     };
     return out;
 }
std::ostream & ripple::operator<< (std::ostream & os, Peer const & peer) inline
Definition at line 2843 of file PeerImp.h.
References to_string().
 {
     os << to_string (peer);
     return os;
 }
std::ostream & ripple::operator<< (std::ostream & os, Peer const * peer) inline
Definition at line 2850 of file PeerImp.h.
References to_string().
 {
     os << to_string (peer);
     return os;
 }
std::ostream & ripple::operator<< (std::ostream & os, PeerImp const & peer) inline
Definition at line 2814 of file PeerImp.h.
References to_string().
 {
     os << to_string (peer);
     return os;
 }
std::ostream & ripple::operator<< (std::ostream & os, PeerImp const * peer) inline
Definition at line 2821 of file PeerImp.h.
References to_string().
 {
     os << to_string (peer);
     return os;
 }
const CBigNum ripple::operator<< (const CBigNum & a, unsigned int shift)
Definition at line 573 of file CBigNum.cpp.
 {
     CBigNum r;
     if (!BN_lshift (&r, &a, shift))
         throw bignum_error ("CBigNum:operator<< : BN_lshift failed");
     return r;
 }
std::ostream& ripple::operator<< (std::ostream & out, const SHAMapNode & node) inline
Definition at line 135 of file SHAMapNode.h.
References ripple::SHAMapNode::getString().
 {
     return out << node.getString ();
 }
template<class Traits > std::ostream& ripple::operator<< (std::ostream & os, IdentifierType< Traits > const & id)
Definition at line 213 of file IdentifierType.h.
 {
     os << id.to_string();
     return os;
 }
std::ostream& ripple::operator<< (std::ostream & out, const SerializedType & t) inline
Definition at line 214 of file SerializedTypes.h.
References ripple::SerializedType::getFullText().
 {
     return out << t.getFullText ();
 }
template<unsigned int BITS> std::ostream& ripple::operator<< (std::ostream & out, const base_uint< BITS > & u)
Definition at line 480 of file base_uint.h.
 {
     return out << u.GetHex ();
 }
bool ripple::operator<= (const CBigNum & a, const CBigNum & b)
Definition at line 600 of file CBigNum.cpp.
 {
     return (BN_cmp (&a, &b) <= 0);
 }
template<bool LhsByValue, bool RhsByValue> bool ripple::operator<= (RippleAssetType< LhsByValue > const & lhs, RippleAssetType< RhsByValue > const & rhs)
Definition at line 162 of file RippleAssets.h.
References lhs.
 {
     return ! (rhs < lhs);
 }
template<std::size_t PrePadSize, std::size_t Size, std::size_t PostPadSize> bool ripple::operator<= (IdentifierStorage< PrePadSize, Size, PostPadSize > const & lhs, IdentifierStorage< PrePadSize, Size, PostPadSize > const & rhs)
Definition at line 175 of file IdentifierStorage.h.
References lhs.
 {
     return !(rhs<lhs);
 }
template<class Traits > bool ripple::operator<= (IdentifierType< Traits > const & lhs, IdentifierType< Traits > const & rhs)
Definition at line 201 of file IdentifierType.h.
References lhs.
 { return lhs.value() <= rhs.value(); }
template<bool LhsByValue, bool RhsByValue> bool ripple::operator<= (RippleBookType< LhsByValue > const & lhs, RippleBookType< RhsByValue > const & rhs)
Definition at line 305 of file RippleAssets.h.
References lhs.
 {
     return ! (rhs < lhs);
 }
bool ripple::operator== (const uint160 & a, std::uint64_t b) inline
Definition at line 87 of file UInt160.h.
 {
     return (base_uint160)a == b;
 }
bool ripple::operator== (uint256 const & a, std::uint64_t b) inline
Definition at line 102 of file UInt256.h.
 {
     return (base_uint256)a == b;
 }
bool ripple::operator== (const CBigNum & a, const CBigNum & b)
Definition at line 590 of file CBigNum.cpp.
 {
     return (BN_cmp (&a, &b) == 0);
 }
bool ripple::operator== (const base_uint160 & a, const uint160 & b) inline
Definition at line 112 of file UInt160.h.
 {
     return (base_uint160)a == (base_uint160)b;
 }
template<bool LhsByValue, bool RhsByValue> bool ripple::operator== (RippleAssetType< LhsByValue > const & lhs, RippleAssetType< RhsByValue > const & rhs)
Equality comparison.
Definition at line 124 of file RippleAssets.h.
References compare().
 {
     return compare (lhs, rhs) == 0;
 }
bool ripple::operator== (const base_uint256 & a, uint256 const & b) inline
Definition at line 127 of file UInt256.h.
 {
     return (base_uint256)a == (base_uint256)b;
 }
bool ripple::operator== (const uint160 & a, const base_uint160 & b) inline
Definition at line 137 of file UInt160.h.
 {
     return (base_uint160)a == (base_uint160)b;
 }
template<std::size_t PrePadSize, std::size_t Size, std::size_t PostPadSize> bool ripple::operator== (IdentifierStorage< PrePadSize, Size, PostPadSize > const & lhs, IdentifierStorage< PrePadSize, Size, PostPadSize > const & rhs)
Definition at line 147 of file IdentifierStorage.h.
References ripple::IdentifierStorage< PreSize, Size, PostSize >::begin(), ripple::IdentifierStorage< PreSize, Size, PostSize >::end(), and std::detail::equal().
 {
     return std::equal (lhs.begin(), lhs.end(), rhs.begin());
 }
bool ripple::operator== (uint256 const & a, const base_uint256 & b) inline
Definition at line 152 of file UInt256.h.
 {
     return (base_uint256)a == (base_uint256)b;
 }
bool ripple::operator== (const uint160 & a, const uint160 & b) inline
Definition at line 160 of file UInt160.h.
 {
     return (base_uint160)a == (base_uint160)b;
 }
bool ripple::operator== (uint256 const & a, uint256 const & b) inline
Definition at line 177 of file UInt256.h.
 {
     return (base_uint256)a == (base_uint256)b;
 }
template<class Traits > bool ripple::operator== (IdentifierType< Traits > const & lhs, IdentifierType< Traits > const & rhs)
Definition at line 181 of file IdentifierType.h.
References ripple::IdentifierType< Traits >::value().
 { return lhs.value() == rhs.value(); }
template<bool LhsByValue, bool RhsByValue> bool ripple::operator== (RippleBookType< LhsByValue > const & lhs, RippleBookType< RhsByValue > const & rhs)
Equality comparison.
Definition at line 262 of file RippleAssets.h.
References ripple::RippleBookType< ByValue >::in, and ripple::RippleBookType< ByValue >::out.
 {
     return (lhs.in == rhs.in) &&
            (lhs.out == rhs.out);
 }
bool ripple::operator> (const CBigNum & a, const CBigNum & b)
Definition at line 615 of file CBigNum.cpp.
 {
     return (BN_cmp (&a, &b) > 0);
 }
template<bool LhsByValue, bool RhsByValue> bool ripple::operator> (RippleAssetType< LhsByValue > const & lhs, RippleAssetType< RhsByValue > const & rhs)
Definition at line 148 of file RippleAssets.h.
References lhs.
 {
     return rhs < lhs;
 }
template<std::size_t PrePadSize, std::size_t Size, std::size_t PostPadSize> bool ripple::operator> (IdentifierStorage< PrePadSize, Size, PostPadSize > const & lhs, IdentifierStorage< PrePadSize, Size, PostPadSize > const & rhs)
Definition at line 168 of file IdentifierStorage.h.
References lhs.
 {
     return rhs<lhs;
 }
template<class Traits > bool ripple::operator> (IdentifierType< Traits > const & lhs, IdentifierType< Traits > const & rhs)
Definition at line 196 of file IdentifierType.h.
References ripple::IdentifierType< Traits >::value().
 { return lhs.value() > rhs.value(); }
template<bool LhsByValue, bool RhsByValue> bool ripple::operator> (RippleBookType< LhsByValue > const & lhs, RippleBookType< RhsByValue > const & rhs)
Definition at line 291 of file RippleAssets.h.
References lhs.
 {
     return rhs < lhs;
 }
bool ripple::operator>= (const CBigNum & a, const CBigNum & b)
Definition at line 605 of file CBigNum.cpp.
 {
     return (BN_cmp (&a, &b) >= 0);
 }
template<bool LhsByValue, bool RhsByValue> bool ripple::operator>= (RippleAssetType< LhsByValue > const & lhs, RippleAssetType< RhsByValue > const & rhs)
Definition at line 155 of file RippleAssets.h.
 {
     return ! (lhs < rhs);
 }
template<std::size_t PrePadSize, std::size_t Size, std::size_t PostPadSize> bool ripple::operator>= (IdentifierStorage< PrePadSize, Size, PostPadSize > const & lhs, IdentifierStorage< PrePadSize, Size, PostPadSize > const & rhs)
Definition at line 182 of file IdentifierStorage.h.
 {
     return !(lhs<rhs);
 }
template<class Traits > bool ripple::operator>= (IdentifierType< Traits > const & lhs, IdentifierType< Traits > const & rhs)
Definition at line 206 of file IdentifierType.h.
References ripple::IdentifierType< Traits >::value().
 { return lhs.value() >= rhs.value(); }
template<bool LhsByValue, bool RhsByValue> bool ripple::operator>= (RippleBookType< LhsByValue > const & lhs, RippleBookType< RhsByValue > const & rhs)
Definition at line 298 of file RippleAssets.h.
 {
     return ! (lhs < rhs);
 }
const CBigNum ripple::operator>> (const CBigNum & a, unsigned int shift)
Definition at line 583 of file CBigNum.cpp.
 {
     CBigNum r = a;
     r >>= shift;
     return r;
 }
template<class Traits > std::istream& ripple::operator>> (std::istream & is, IdentifierType< Traits > const & id)
Definition at line 221 of file IdentifierType.h.
 {
     return is;
 }
const uint160 ripple::operator^ (const base_uint160 & a, const base_uint160 & b) inline
Definition at line 97 of file UInt160.h.
 {
     return uint160 (a) ^= b;
 }
const uint256 ripple::operator^ (const base_uint256 & a, const base_uint256 & b) inline
Definition at line 112 of file UInt256.h.
 {
     return uint256 (a) ^= b;
 }
const uint160 ripple::operator^ (const base_uint160 & a, const uint160 & b) inline
Definition at line 122 of file UInt160.h.
 {
     return (base_uint160)a ^  (base_uint160)b;
 }
const uint256 ripple::operator^ (const base_uint256 & a, uint256 const & b) inline
Definition at line 137 of file UInt256.h.
 {
     return (base_uint256)a ^  (base_uint256)b;
 }
const uint160 ripple::operator^ (const uint160 & a, const base_uint160 & b) inline
Definition at line 145 of file UInt160.h.
 {
     return (base_uint160)a ^  (base_uint160)b;
 }
const uint256 ripple::operator^ (uint256 const & a, const base_uint256 & b) inline
Definition at line 162 of file UInt256.h.
 {
     return (base_uint256)a ^  (base_uint256)b;
 }
const uint160 ripple::operator^ (const uint160 & a, const uint160 & b) inline
Definition at line 170 of file UInt160.h.
 {
     return (base_uint160)a ^  (base_uint160)b;
 }
const uint256 ripple::operator^ (uint256 const & a, uint256 const & b) inline
Definition at line 188 of file UInt256.h.
 {
     return (base_uint256)a ^  (base_uint256)b;
 }
const uint160 ripple::operator| (const base_uint160 & a, const base_uint160 & b) inline
Definition at line 107 of file UInt160.h.
 {
     return uint160 (a) |= b;
 }
TransactionEngineParams ripple::operator| (const TransactionEngineParams & l1, const TransactionEngineParams & l2) inline
Definition at line 112 of file TransactionEngine.h.
 {
     return static_cast<TransactionEngineParams> (static_cast<int> (l1) | static_cast<int> (l2));
 }
const uint256 ripple::operator| (const base_uint256 & a, const base_uint256 & b) inline
Definition at line 122 of file UInt256.h.
 {
     return uint256 (a) |= b;
 }
const uint160 ripple::operator| (const base_uint160 & a, const uint160 & b) inline
Definition at line 132 of file UInt160.h.
 {
     return (base_uint160)a |  (base_uint160)b;
 }
const uint256 ripple::operator| (const base_uint256 & a, uint256 const & b) inline
Definition at line 147 of file UInt256.h.
 {
     return (base_uint256)a |  (base_uint256)b;
 }
const uint160 ripple::operator| (const uint160 & a, const base_uint160 & b) inline
Definition at line 155 of file UInt160.h.
 {
     return (base_uint160)a |  (base_uint160)b;
 }
const uint256 ripple::operator| (uint256 const & a, const base_uint256 & b) inline
Definition at line 172 of file UInt256.h.
 {
     return (base_uint256)a |  (base_uint256)b;
 }
const uint160 ripple::operator| (const uint160 & a, const uint160 & b) inline
Definition at line 180 of file UInt160.h.
 {
     return (base_uint160)a |  (base_uint160)b;
 }
const uint256 ripple::operator| (uint256 const & a, uint256 const & b) inline
Definition at line 198 of file UInt256.h.
 {
     return (base_uint256)a |  (base_uint256)b;
 }
LedgerStateParms ripple::operator| (const LedgerStateParms & l1, const LedgerStateParms & l2) inline
Definition at line 519 of file Ledger.h.
 {
     return static_cast<LedgerStateParms> (static_cast<int> (l1) | static_cast<int> (l2));
 }
template<class OutputSequence , class InputIterator > void ripple::parseAddresses (OutputSequence & out, InputIterator first, InputIterator last, beast::Journal::Stream stream = beast::Journal::Stream ())
Parses a set of strings into IP::Endpoint Strings which fail to parse are not included in the output. If a stream is provided, human readable diagnostic error messages are written for each failed parse.
Parameters
out An OutputSequence to store the IP::Endpoint list
first The begining of the string input sequence
last The one-past-the-end of the string input sequence
Definition at line 45 of file Config.cpp.
References beast.util.Iter::first(), beast::IP::Endpoint::from_string(), beast::IP::Endpoint::from_string_altform(), and beast::IP::is_unspecified().
Referenced by ripple::Config::load().
 {
     while (first != last)
     {
         auto const str (*first);
         ++first;
         {
             beast::IP::Endpoint const addr (beast::IP::Endpoint::from_string (str));
             if (! is_unspecified (addr))
             {
                 out.push_back (addr);
                 continue;
             }
         }
         {
             beast::IP::Endpoint const addr (beast::IP::Endpoint::from_string_altform (str));
             if (! is_unspecified (addr))
             {
                 out.push_back (addr);
                 continue;
             }
         }
         if (stream) stream <<
             "Config: \"" << str << "\" is not a valid IP address.";
     }
 }
beast::StringPairArray ripple::parseDelimitedKeyValueString (beast::String s, beast::beast_wchar delimiter = '|')
Create a Parameters from a String.
Parameter strings have the format:
<key>=
['|'<key>=
]
Definition at line 284 of file StringUtilities.cpp.
References beast::String::empty, beast::String::indexOfChar(), beast::String::isNotEmpty(), beast::String::length(), beast::StringPairArray::set(), beast::String::substring(), and value.
Referenced by setupConfigForUnitTests().
 {
     beast::StringPairArray keyValues;
     while (parameters.isNotEmpty ())
     {
         beast::String pair;
         {
             int const delimiterPos = parameters.indexOfChar (delimiter);
             if (delimiterPos != -1)
             {
                 pair = parameters.substring (0, delimiterPos);
                 parameters = parameters.substring (delimiterPos + 1);
             }
             else
             {
                 pair = parameters;
                 parameters = beast::String::empty;
             }
         }
         int const equalPos = pair.indexOfChar ('=');
         if (equalPos != -1)
         {
             beast::String const key = pair.substring (0, equalPos);
             beast::String const value = pair.substring (equalPos + 1, pair.length ());
             keyValues.set (key, value);
         }
     }
     return keyValues;
 }
bool ripple::parseIpPort (const std::string & strSource, std::string & strIP, int & iPort)
Definition at line 208 of file StringUtilities.cpp.
Referenced by ripple::UniqueNodeListImp::processIps().
 {
     boost::smatch   smMatch;
     bool            bValid  = false;
     static boost::regex reEndpoint ("\\`\\s*(\\S+)(?:\\s+(\\d+))?\\s*\\'");
     if (boost::regex_match (strSource, smMatch, reEndpoint))
     {
         boost::system::error_code   err;
         std::string                 strIPRaw    = smMatch[1];
         std::string                 strPortRaw  = smMatch[2];
         boost::asio::ip::address    addrIP      = boost::asio::ip::address::from_string (strIPRaw, err);
         bValid  = !err;
         if (bValid)
         {
             strIP   = addrIP.to_string ();
             iPort   = strPortRaw.empty () ? -1 : beast::lexicalCastThrow <int> (strPortRaw);
         }
     }
     return bValid;
 }
beast::StringPairArray ripple::parseKeyValueSection (Section & secSource, beast::String const & strSection)
Parse a section of lines as a key/value array.
Each line is in the form <key>=
. Spaces are considered part of the key and value.
Definition at line 149 of file IniFile.cpp.
References beast::String::indexOfChar(), SectionEntries(), beast::StringPairArray::set(), beast::String::substring(), beast::String::toStdString(), and value.
Referenced by ripple::Config::load().
 {
     beast::StringPairArray result;
     // yuck.
     std::string const stdStrSection (strSection.toStdString ());
     typedef Section::mapped_type Entries;
     Entries* const entries = SectionEntries (secSource, stdStrSection);
     if (entries != nullptr)
     {
         for (Entries::const_iterator iter = entries->begin (); iter != entries->end (); ++iter)
         {
             beast::String const line (iter->c_str ());
             int const equalPos = line.indexOfChar ('=');
             if (equalPos != -1)
             {
                 beast::String const key = line.substring (0, equalPos);
                 beast::String const value = line.substring (equalPos + 1, line.length ());
                 result.set (key, value);
             }
         }
     }
     return result;
 }
bool ripple::parseQuality (const std::string & strSource, std::uint32_t & uQuality)
Definition at line 269 of file StringUtilities.cpp.
References QUALITY_ONE.
 {
     uQuality    = beast::lexicalCast <std::uint32_t> (strSource);
     if (!uQuality)
     {
         float   fQuality    = beast::lexicalCast <float> (strSource);
         if (fQuality)
             uQuality    = (std::uint32_t) (QUALITY_ONE * fQuality);
     }
     return !!uQuality;
 }
Section ripple::ParseSection (const std::string & strInput, const bool bTrim)
Definition at line 30 of file IniFile.cpp.
References nothing, and SECTION_DEFAULT_NAME.
Referenced by ripple::Config::load(), ripple::UniqueNodeListImp::nodeProcess(), ripple::UniqueNodeListImp::responseFetch(), ripple::UniqueNodeListImp::responseIps(), and ripple::UniqueNodeListImp::responseValidators().
 {
     std::string strData (strInput);
     std::vector<std::string> vLines;
     Section secResult;
     // Convert DOS format to unix.
     boost::algorithm::replace_all (strData, "\r\n", "\n");
     // Convert MacOS format to unix.
     boost::algorithm::replace_all (strData, "\r", "\n");
     boost::algorithm::split (vLines, strData, boost::algorithm::is_any_of ("\n"));
     // Set the default Section name.
     std::string strSection  = SECTION_DEFAULT_NAME;
     // Initialize the default Section.
     secResult[strSection]   = Section::mapped_type ();
     // Parse each line.
     BOOST_FOREACH (std::string & strValue, vLines)
     {
         if (strValue.empty () || strValue[0] == '#')
         {
             // Blank line or comment, do nothing.
             nothing ();
         }
         else if (strValue[0] == '[' && strValue[strValue.length () - 1] == ']')
         {
             // New Section.
             strSection              = strValue.substr (1, strValue.length () - 2);
             secResult[strSection]   = Section::mapped_type ();
         }
         else
         {
             // Another line for Section.
             if (bTrim)
                 boost::algorithm::trim (strValue);
             if (!strValue.empty ())
                 secResult[strSection].push_back (strValue);
         }
     }
     return secResult;
 }
bool ripple::parseUrl (const std::string & strUrl, std::string & strScheme, std::string & strDomain, int & iPort, std::string & strPath)
Definition at line 237 of file StringUtilities.cpp.
Referenced by ripple::UniqueNodeListImp::getIpsUrl(), ripple::UniqueNodeListImp::getValidatorsUrl(), ripple::RPCSubImp::RPCSubImp(), ripple::HTTPClient::sendSMS(), and ripple::StringUtilities_test::testParseUrl().
 {
     // scheme://username:password@hostname:port/rest
     static boost::regex reUrl ("(?i)\\`\\s*([[:alpha:]][-+.[:alpha:][:digit:]]*)://([^:/]+)(?::(\\d+))?(/.*)?\\s*?\\'");
     boost::smatch   smMatch;
     bool    bMatch  = boost::regex_match (strUrl, smMatch, reUrl);          // Match status code.
     if (bMatch)
     {
         std::string strPort;
         strScheme   = smMatch[1];
         strDomain   = smMatch[2];
         strPort     = smMatch[3];
         strPath     = smMatch[4];
         boost::algorithm::to_lower (strScheme);
         iPort   = strPort.empty () ? -1 : beast::lexicalCast <int> (strPort);
         // Log::out() << strUrl << " : " << bMatch << " : '" << strDomain << "' : '" << strPort << "' : " << iPort << " : '" << strPath << "'";
     }
     // Log::out() << strUrl << " : " << bMatch << " : '" << strDomain << "' : '" << strPath << "'";
     return bMatch;
 }
bool ripple::passesLocalChecks (STObject const & st, std::string & reason)
Definition at line 344 of file SerializedTransaction.cpp.
References isAccountFieldOkay(), and isMemoOkay().
Referenced by passesLocalChecks(), ripple::NetworkOPsImp::submitTransaction(), ripple::Transaction::Transaction(), and ripple::RPC::transactionSign().
 {
     if (!isMemoOkay (st))
     {
         reason = "The memo exceeds the maximum allowed size.";
         return false;
     }
     if (!isAccountFieldOkay (st))
     {
         reason = "An account field is invalid.";
         return false;
     }
     return true;
 }
bool ripple::passesLocalChecks (STObject const & st)
Definition at line 360 of file SerializedTransaction.cpp.
References passesLocalChecks().
 {
     std::string reason;
     return passesLocalChecks (st, reason);
 }
void ripple::printHelp (const po::options_description & desc)
Definition at line 72 of file Main.cpp.
References SYSTEM_NAME.
Referenced by run().
 {
     using namespace std;
     cerr << SYSTEM_NAME "d [options] <command> <params>" << endl;
     cerr << desc << endl;
     cerr << "Commands: " << endl;
     cerr << "     account_info <account>|<nickname>|<seed>|<pass_phrase>|<key> [<ledger>] [strict]" << endl;
     cerr << "     account_lines <account> <account>|\"\" [<ledger>]" << endl;
     cerr << "     account_offers <account>|<nickname>|<account_public_key> [<ledger>]" << endl;
     cerr << "     account_tx accountID [ledger_min [ledger_max [limit [offset]]]] [binary] [count] [descending]" << endl;
     cerr << "     book_offers <taker_pays> <taker_gets> [<taker [<ledger> [<limit> [<proof> [<marker>]]]]]" << endl;
     cerr << "     connect <ip> [<port>]" << endl;
     cerr << "     consensus_info" << endl;
     cerr << "     get_counts" << endl;
     cerr << "     json <method> <json>" << endl;
     cerr << "     ledger [<id>|current|closed|validated] [full]" << endl;
     cerr << "     ledger_accept" << endl;
     cerr << "     ledger_closed" << endl;
     cerr << "     ledger_current" << endl;
     cerr << "     ledger_header <ledger>" << endl;
     cerr << "     logrotate " << endl;
     cerr << "     peers" << endl;
     cerr << "     proof_create [<difficulty>] [<secret>]" << endl;
     cerr << "     proof_solve <token>" << endl;
     cerr << "     proof_verify <token> <solution> [<difficulty>] [<secret>]" << endl;
     cerr << "     random" << endl;
     cerr << "     ripple ..." << endl;
     cerr << "     ripple_path_find <json> [<ledger>]" << endl;
     //  cerr << "     send <seed> <paying_account> <account_id> <amount> [<currency>] [<send_max>] [<send_currency>]" << endl;
     cerr << "     stop" << endl;
     cerr << "     tx <id>" << endl;
     cerr << "     unl_add <domain>|<public> [<comment>]" << endl;
     cerr << "     unl_delete <domain>|<public_key>" << endl;
     cerr << "     unl_list" << endl;
     cerr << "     unl_load" << endl;
     cerr << "     unl_network" << endl;
     cerr << "     unl_reset" << endl;
     cerr << "     validation_create [<seed>|<pass_phrase>|<key>]" << endl;
     cerr << "     validation_seed [<seed>|<pass_phrase>|<key>]" << endl;
     cerr << "     wallet_add <regular_seed> <paying_account> <master_seed> [<initial_funds>] [<account_annotation>]" << endl;
     cerr << "     wallet_accounts <seed>" << endl;
     cerr << "     wallet_claim <master_seed> <regular_seed> [<source_tag>] [<account_annotation>]" << endl;
     cerr << "     wallet_seed [<seed>|<passphrase>|<passkey>]" << endl;
     cerr << "     wallet_propose [<passphrase>]" << endl;
     // Transaction helpers (that were removed):
     //  cerr << "     account_domain_set <seed> <paying_account> [<domain>]" << endl;
     //  cerr << "     account_email_set <seed> <paying_account> [<email_address>]" << endl;
     //  cerr << "     account_rate_set <seed> <paying_account> <rate>" << endl;
     //  cerr << "     account_wallet_set <seed> <paying_account> [<wallet_hash>]" << endl;
     //  cerr << "     nickname_info <nickname>" << endl;
     //  cerr << "     nickname_set <seed> <paying_account> <nickname> [<offer_minimum>] [<authorization>]" << endl;
     //  cerr << "     offer_create <seed> <paying_account> <taker_pays_amount> <taker_pays_currency> <taker_pays_issuer> <takers_gets_amount> <takers_gets_currency> <takers_gets_issuer> <expires> [passive]" << endl;
     //  cerr << "     offer_cancel <seed> <paying_account> <sequence>" << endl;
     //  cerr << "     password_fund <seed> <paying_account> [<account>]" << endl;
     //  cerr << "     password_set <master_seed> <regular_seed> [<account>]" << endl;
     //  cerr << "     trust_set <seed> <paying_account> <destination_account> <limit_amount> <currency> [<quality_in>] [<quality_out>]" << endl;
 }
boost::posix_time::ptime ripple::ptEpoch ()
Definition at line 29 of file Time.cpp.
Referenced by iToSeconds(), and ptFromSeconds().
 {
     return boost::posix_time::ptime (boost::gregorian::date (2000, boost::gregorian::Jan, 1));
 }
boost::posix_time::ptime ripple::ptFromSeconds (int iSeconds)
Definition at line 42 of file Time.cpp.
References ptEpoch().
Referenced by ripple::UniqueNodeListImp::fetchNext(), ripple::Ledger::getCloseTime(), ripple::Ledger::getJson(), ripple::UniqueNodeListImp::getSeedDomains(), ripple::UniqueNodeListImp::getSeedNodes(), and ripple::UniqueNodeListImp::miscLoad().
 {
     return iSeconds < 0
            ? boost::posix_time::ptime (boost::posix_time::not_a_date_time)
            : ptEpoch () + boost::posix_time::seconds (iSeconds);
 }
LedgerEntrySet::iterator ripple::range_begin (LedgerEntrySet & x) inline
Definition at line 283 of file LedgerEntrySet.h.
References ripple::LedgerEntrySet::begin().
 {
     return x.begin ();
 }
STObject::iterator ripple::range_begin (STObject & x) inline
Definition at line 327 of file SerializedObject.h.
References ripple::STObject::begin().
 {
     return x.begin ();
 }
STArray::iterator ripple::range_begin (STArray & x) inline
Definition at line 516 of file SerializedObject.h.
References ripple::STArray::begin().
 {
     return x.begin ();
 }
std::vector<STPathElement>::iterator ripple::range_begin (STPath & x) inline
Definition at line 1351 of file SerializedTypes.h.
References ripple::STPath::begin().
 {
     return x.begin ();
 }
std::vector<STPathElement>::const_iterator ripple::range_begin (const STPath & x) inline
Definition at line 1361 of file SerializedTypes.h.
References ripple::STPath::begin().
 {
     return x.begin ();
 }
std::vector<STPath>::iterator ripple::range_begin (STPathSet & x) inline
Definition at line 1513 of file SerializedTypes.h.
References ripple::STPathSet::begin().
 {
     return x.begin ();
 }
std::vector<STPath>::const_iterator ripple::range_begin (const STPathSet & x) inline
Definition at line 1523 of file SerializedTypes.h.
References ripple::STPathSet::begin().
 {
     return x.begin ();
 }
template<typename T , typename U > static T ripple::range_check_cast (const U & value, const T & minimum, const T & maximum) static
Definition at line 319 of file SerializedObject.h.
References T, and value.
 {
     if ((value < minimum) || (value > maximum))
         throw std::runtime_error ("Value out of range");
     return static_cast<T> (value);
 }
LedgerEntrySet::iterator ripple::range_end (LedgerEntrySet & x) inline
Definition at line 287 of file LedgerEntrySet.h.
References ripple::LedgerEntrySet::end().
 {
     return x.end ();
 }
STObject::iterator ripple::range_end (STObject & x) inline
Definition at line 331 of file SerializedObject.h.
References ripple::STObject::end().
 {
     return x.end ();
 }
STArray::iterator ripple::range_end (STArray & x) inline
Definition at line 520 of file SerializedObject.h.
References ripple::STArray::end().
 {
     return x.end ();
 }
std::vector<STPathElement>::iterator ripple::range_end (STPath & x) inline
Definition at line 1356 of file SerializedTypes.h.
References ripple::STPath::end().
 {
     return x.end ();
 }
std::vector<STPathElement>::const_iterator ripple::range_end (const STPath & x) inline
Definition at line 1366 of file SerializedTypes.h.
References ripple::STPath::end().
 {
     return x.end ();
 }
std::vector<STPath>::iterator ripple::range_end (STPathSet & x) inline
Definition at line 1518 of file SerializedTypes.h.
References ripple::STPathSet::end().
 {
     return x.end ();
 }
std::vector<STPath>::const_iterator ripple::range_end (const STPathSet & x) inline
Definition at line 1528 of file SerializedTypes.h.
References ripple::STPathSet::end().
 {
     return x.end ();
 }
int ripple::ReadHTTP (std::basic_istream< char > & stream, std::map< std::string, std::string > & mapHeadersRet, std::string & strMessageRet)
Definition at line 223 of file RPCUtil.cpp.
References gMaxHTTPHeaderSize, ReadHTTPHeader(), and ReadHTTPStatus().
 {
     mapHeadersRet.clear ();
     strMessageRet = "";
     // Read status
     int nStatus = ReadHTTPStatus (stream);
     // Read header
     int nLen = ReadHTTPHeader (stream, mapHeadersRet);
     if (nLen < 0 || nLen > gMaxHTTPHeaderSize)
         return 500;
     // Read message
     if (nLen > 0)
     {
         std::vector<char> vch (nLen);
         stream.read (&vch[0], nLen);
         strMessageRet = std::string (vch.begin (), vch.end ());
     }
     return nStatus;
 }
int ripple::ReadHTTPHeader (std::basic_istream< char > & stream, std::map< std::string, std::string > & mapHeadersRet)
Definition at line 192 of file RPCUtil.cpp.
Referenced by ReadHTTP().
 {
     int nLen = 0;
     for (;;)
     {
         std::string str;
         std::getline (stream, str);
         if (str.empty () || str == "\r")
             break;
         std::string::size_type nColon = str.find (":");
         if (nColon != std::string::npos)
         {
             std::string strHeader = str.substr (0, nColon);
             boost::trim (strHeader);
             boost::to_lower (strHeader);
             std::string strValue = str.substr (nColon + 1);
             boost::trim (strValue);
             mapHeadersRet[strHeader] = strValue;
             if (strHeader == "content-length")
                 nLen = atoi (strValue.c_str ());
         }
     }
     return nLen;
 }
int ripple::ReadHTTPStatus (std::basic_istream< char > & stream)
Definition at line 179 of file RPCUtil.cpp.
Referenced by ReadHTTP().
 {
     std::string str;
     getline (stream, str);
     std::vector<std::string> vWords;
     boost::split (vWords, str, boost::is_any_of (" "));
     if (vWords.size () < 2)
         return 500;
     return atoi (vWords[1].c_str ());
 }
Json::Value ripple::rpcError (int iError, Json::Value jvResult)
Definition at line 27 of file RPCErr.cpp.
References ripple::RPC::inject_error().
Referenced by ripple::RPC::accountFromString(), ripple::RPC::authorize(), ripple::RPCHandler::doAccountInfo(), ripple::RPCHandler::doAccountLines(), ripple::RPCHandler::doAccountOffers(), ripple::RPCHandler::doAccountTx(), ripple::RPCHandler::doAccountTxOld(), ripple::RPCHandler::doBookOffers(), ripple::RPCHandler::doCommand(), ripple::RPCHandler::doConnect(), ripple::RPCHandler::doFeature(), ripple::RPCHandler::doInternal(), ripple::RPCHandler::doLedger(), ripple::RPCHandler::doLogLevel(), ripple::RPCHandler::doPathFind(), ripple::RPCHandler::doRandom(), ripple::RPCHandler::doRipplePathFind(), ripple::RPCHandler::doRpcCommand(), ripple::RPCHandler::doSMS(), ripple::RPCHandler::doSubmit(), ripple::RPCHandler::doSubscribe(), ripple::RPCHandler::doTx(), ripple::RPCHandler::doTxHistory(), ripple::RPCHandler::doUnlDelete(), ripple::RPCHandler::doUnlLoad(), ripple::RPCHandler::doUnsubscribe(), ripple::RPCHandler::doValidationCreate(), ripple::RPCHandler::doValidationSeed(), ripple::RPCHandler::doWalletAccounts(), ripple::RPCHandler::doWalletPropose(), ripple::RPCHandler::doWalletSeed(), ripple::RPCCall::fromCommandLine(), ripple::RPC::getMasterGenerator(), ripple::WSConnection::invokeCommand(), ripple::PathRequest::isValid(), ripple::RPCParser::parseAccountRaw(), ripple::RPCParser::parseAccountTransactions(), ripple::RPCParser::parseCommand(), ripple::RPCParser::parseEvented(), ripple::PathRequest::parseJson(), ripple::RPCParser::parseJson(), ripple::RPCParser::parseRipplePathFind(), ripple::RPCParser::parseSignSubmit(), ripple::RPCParser::parseTxAccount(), ripple::RPCParser::parseUnlAdd(), ripple::RPCInternalHandler::runHandler(), and ripple::RPC::transactionSign().
 {
     RPC::inject_error (iError, jvResult);
     return jvResult;
 }
int ripple::run (int argc, char ** argv)
Definition at line 165 of file Main.cpp.
References ripple::version::checkLibraryVersions(), ripple::Config::doImport, DoSustain(), ripple::Config::FRESH, ripple::RPCCall::fromCommandLine(), ripple::LogSink::get(), getConfig(), ripple::RandomNumbers::getInstance(), ripple::BuildInfo::getVersionString(), HaveSustain(), ripple::ConfigSection::importNodeDatabase(), ripple::Config::LEDGER_HISTORY, ripple::Config::LOAD, lsFATAL, lsINFO, lsTRACE, lsWARNING, make_Application(), ripple::Config::NETWORK, ripple::ConfigSection::nodeDatabase(), nothing, printHelp(), ripple::Config::REPLAY, ripple::Config::RUN_STANDALONE, runUnitTests(), setCallingThreadName(), ripple::Config::setRpcIpAndOptionalPort(), ripple::Config::setRpcPort(), ripple::Config::setup(), setupServer(), ripple::Config::START_LEDGER, ripple::Config::START_UP, startServer(), beast::String::toStdString(), ripple::Config::VALIDATION_QUORUM, and value.
Referenced by main(), and rocksdb::TEST().
 {
     // Make sure that we have the right OpenSSL and Boost libraries.
     version::checkLibraryVersions();
     FatalErrorReporter reporter;
     using namespace std;
     setCallingThreadName ("main");
     int iResult = 0;
     po::variables_map vm;
     beast::String importDescription;
     {
         importDescription <<
             "Import an existing node database (specified in the " <<
             "[" << ConfigSection::importNodeDatabase () << "] configuration file section) "
             "into the current node database (specified in the " <<
             "[" << ConfigSection::nodeDatabase () << "] configuration file section). ";
     }
     // VFALCO TODO Replace boost program options with something from Beast.
     //
     // Set up option parsing.
     //
     po::options_description desc ("General Options");
     desc.add_options ()
     ("help,h", "Display this message.")
     ("conf", po::value<std::string> (), "Specify the configuration file.")
     ("rpc", "Perform rpc command (default).")
     ("rpc_ip", po::value <std::string> (), "Specify the IP address for RPC command. Format: <ip-address>[':'<port-number>]")
     ("rpc_port", po::value <int> (), "Specify the port number for RPC command.")
     ("standalone,a", "Run with no peers.")
     ("unittest,u", po::value <std::string> ()->implicit_value (""), "Perform unit tests.")
     ("unittest-format", po::value <std::string> ()->implicit_value ("text"), "Format unit test output. Choices are 'text', 'junit'")
     ("parameters", po::value< vector<string> > (), "Specify comma separated parameters.")
     ("quiet,q", "Reduce diagnotics.")
     ("verbose,v", "Verbose logging.")
     ("load", "Load the current ledger from the local DB.")
     ("replay","Replay a ledger close.")
     ("ledger", po::value<std::string> (), "Load the specified ledger and start from .")
     ("start", "Start from a fresh Ledger.")
     ("net", "Get the initial ledger from the network.")
     ("fg", "Run in the foreground.")
     ("import", importDescription.toStdString ().c_str ())
     ("version", "Display the build version.")
     ;
     // Interpret positional arguments as --parameters.
     po::positional_options_description p;
     p.add ("parameters", -1);
     if (! RandomNumbers::getInstance ().initialize ())
     {
         Log::out() << "Unable to add system entropy";
         iResult = 2;
     }
     if (iResult)
     {
         nothing ();
     }
     else
     {
         // Parse options, if no error.
         try
         {
             po::store (po::command_line_parser (argc, argv)
                        .options (desc)                                         // Parse options.
                        .positional (p)                                         // Remainder as --parameters.
                        .run (),
                        vm);
             po::notify (vm);                                            // Invoke option notify functions.
         }
         catch (...)
         {
             iResult = 1;
         }
     }
     if (iResult)
     {
         nothing ();
     }
     else if (vm.count ("help"))
     {
         iResult = 1;
     }
     if (vm.count ("version"))
     {
         beast::String const& s (BuildInfo::getVersionString ());
         std::cout << "rippled version " << s.toStdString() << std::endl;
         return 0;
     }
     // Use a watchdog process unless we're invoking a stand alone type of mode
     //
     if (HaveSustain ()
         && !iResult
         && !vm.count ("parameters")
         && !vm.count ("fg")
         && !vm.count ("standalone")
         && !vm.count ("unittest"))
     {
         std::string logMe = DoSustain (getConfig ().DEBUG_LOGFILE.string());
         if (!logMe.empty ())
             Log (lsWARNING) << logMe;
     }
     if (vm.count ("quiet"))
     {
         LogSink::get()->setMinSeverity (lsFATAL, true);
     }
     else if (vm.count ("verbose"))
     {
         LogSink::get()->setMinSeverity (lsTRACE, true);
     }
     else
     {
         LogSink::get()->setMinSeverity (lsINFO, true);
     }
     // Run the unit tests if requested.
     // The unit tests will exit the application with an appropriate return code.
     //
     if (vm.count ("unittest"))
     {
         std::string format;
         if (vm.count ("unittest-format"))
             format = vm ["unittest-format"].as <std::string> ();
         return runUnitTests (vm ["unittest"].as <std::string> (), format);
     }
     if (!iResult)
     {
         getConfig ().setup (
             vm.count ("conf") ? vm["conf"].as<std::string> () : "", // Config file.
             !!vm.count ("quiet"));                                  // Quiet flag.
         if (vm.count ("standalone"))
         {
             getConfig ().RUN_STANDALONE = true;
             getConfig ().LEDGER_HISTORY = 0;
         }
     }
     if (vm.count ("start")) getConfig ().START_UP = Config::FRESH;
     // Handle a one-time import option
     //
     if (vm.count ("import"))
     {
         getConfig ().doImport = true;
     }
     if (vm.count ("ledger"))
     {
         getConfig ().START_LEDGER = vm["ledger"].as<std::string> ();
         if (vm.count("replay"))
             getConfig ().START_UP = Config::REPLAY;
         else
             getConfig ().START_UP = Config::LOAD;
     }
     else if (vm.count ("load"))
     {
         getConfig ().START_UP = Config::LOAD;
     }
     else if (vm.count ("net"))
     {
         getConfig ().START_UP = Config::NETWORK;
         if (getConfig ().VALIDATION_QUORUM < 2)
             getConfig ().VALIDATION_QUORUM = 2;
     }
     if (iResult == 0)
     {
         // These overrides must happen after the config file is loaded.
         // Override the RPC destination IP address
         //
         if (vm.count ("rpc_ip"))
         {
             getConfig ().setRpcIpAndOptionalPort (vm ["rpc_ip"].as <std::string> ());
         }
         // Override the RPC destination port number
         //
         if (vm.count ("rpc_port"))
         {
             // VFALCO TODO This should be a short.
             getConfig ().setRpcPort (vm ["rpc_port"].as <int> ());
         }
     }
     if (iResult == 0)
     {
         if (!vm.count ("parameters"))
         {
             // No arguments. Run server.
             std::unique_ptr <Application> app (make_Application ());
             setupServer ();
             startServer ();
         }
         else
         {
             // Have a RPC command.
             setCallingThreadName ("rpc");
             std::vector<std::string> vCmd   = vm["parameters"].as<std::vector<std::string> > ();
             iResult = RPCCall::fromCommandLine (vCmd);
         }
     }
     if (1 == iResult && !vm.count ("quiet"))
         printHelp (desc);
     return iResult;
 }
static int ripple::runUnitTests (std::string pattern, std::string format) static
Definition at line 147 of file Main.cpp.
References getConfig(), beast::unit_test::detail::global_suites(), make_Application(), beast::unit_test::match_auto(), beast::unit_test::runner::run_each_if(), and setupConfigForUnitTests().
Referenced by run().
 {
     // Config needs to be set up before creating Application
     setupConfigForUnitTests (&getConfig ());
     // VFALCO TODO Remove dependence on constructing Application object
     auto app (make_Application());
     using namespace beast::unit_test;
     beast::debug_ostream stream;
     reporter r (stream);
     bool const failed (r.run_each_if (
         global_suites(), match_auto (pattern)));
     if (failed)
         return EXIT_FAILURE;
     return EXIT_SUCCESS;
 }
static bool ripple::schemaHas (DatabaseCon * dbc, const std::string & dbName, int line, const std::string & content) static
Definition at line 1246 of file Application.cpp.
References getSchema(), rocksdb::Log(), and lsFATAL.
Referenced by addTxnSeqField(), and ripple::ApplicationImp::updateTables().
 {
     std::vector<std::string> schema = getSchema (dbc, dbName);
     if (static_cast<int> (schema.size ()) <= line)
     {
         Log (lsFATAL) << "Schema for " << dbName << " has too few lines";
         throw std::runtime_error ("bad schema");
     }
     return schema[line].find (content) != std::string::npos;
 }
int ripple::SectionCount (Section & secSource, const std::string & strSection)
Definition at line 122 of file IniFile.cpp.
References SectionEntries().
 {
     Section::mapped_type* pmtEntries    = SectionEntries (secSource, strSection);
     return pmtEntries ? pmtEntries->size () : 0;
 }
Section::mapped_type * ripple::SectionEntries (Section & secSource, const std::string & strSection)
Definition at line 101 of file IniFile.cpp.
Referenced by ripple::Config::load(), ripple::UniqueNodeListImp::nodeProcess(), parseKeyValueSection(), ripple::UniqueNodeListImp::processFile(), ripple::UniqueNodeListImp::responseIps(), ripple::UniqueNodeListImp::responseValidators(), SectionCount(), and SectionSingleB().
 {
     Section::iterator       it;
     Section::mapped_type*   smtResult;
     it  = secSource.find (strSection);
     if (it == secSource.end ())
     {
         smtResult   = 0;
     }
     else
     {
         //Section::mapped_type& vecEntries  = it->second;
         smtResult   = & (it->second);
     }
     return smtResult;
 }
void ripple::SectionEntriesPrint (std::vector< std::string > * vspEntries, const std::string & strSection)
Definition at line 80 of file IniFile.cpp.
Referenced by SectionPrint().
 {
     Log::out() << "[" << strSection << "]";
     if (vspEntries)
     {
         BOOST_FOREACH (std::string & strValue, *vspEntries)
         {
             Log::out() << strValue;
         }
     }
 }
void ripple::SectionPrint (Section secInput)
Definition at line 93 of file IniFile.cpp.
References SectionEntriesPrint().
 {
     BOOST_FOREACH (Section::value_type & pairSection, secInput)
     {
         SectionEntriesPrint (&pairSection.second, pairSection.first);
     }
 }
bool ripple::SectionSingleB (Section & secSource, const std::string & strSection, std::string & strValue)
Definition at line 129 of file IniFile.cpp.
References lsWARNING, SectionEntries(), and WriteLog.
Referenced by ripple::UniqueNodeListImp::getIpsUrl(), ripple::UniqueNodeListImp::getValidatorsUrl(), ripple::Config::load(), and ripple::UniqueNodeListImp::responseFetch().
 {
     Section::mapped_type*   pmtEntries  = SectionEntries (secSource, strSection);
     bool                    bSingle     = pmtEntries && 1 == pmtEntries->size ();
     if (bSingle)
     {
         strValue    = (*pmtEntries)[0];
     }
     else if (pmtEntries)
     {
         WriteLog (lsWARNING, ParseSectionLog) << boost::str (boost::format ("Section [%s]: requires 1 line not %d lines.")
                                               % strSection
                                               % pmtEntries->size ());
     }
     return bSingle;
 }
template<typename Predicate > send_if_pred<Predicate> ripple::send_if (Message::pointer const & m, Predicate const & f)
Helper function to aid in type deduction
Definition at line 71 of file predicates.h.
References f.
Referenced by ripple::NetworkOPsImp::processClusterTimer().
 {
     return send_if_pred<Predicate>(m, f);
 }
template<typename Predicate > send_if_not_pred<Predicate> ripple::send_if_not (Message::pointer const & m, Predicate const & f)
Helper function to aid in type deduction
Definition at line 102 of file predicates.h.
References f.
Referenced by ripple::PeerImp::checkPropose(), ripple::PeerImp::checkValidation(), ripple::LedgerConsensusImp::playbackProposals(), ripple::NetworkOPsImp::processTransactionCb(), ripple::NetworkOPsImp::processTrustedProposal(), and ripple::NetworkOPsImp::runTransactionQueue().
 {
     return send_if_not_pred<Predicate>(m, f);
 }
bool ripple::serverOkay (std::string & reason)
Definition at line 1186 of file Application.cpp.
References getApp(), getConfig(), and ripple::NetworkOPs::omSYNCING.
Referenced by ripple::WSServerHandler< endpoint_type >::http().
 {
     if (!getConfig ().ELB_SUPPORT)
         return true;
     if (getApp().isShutdown ())
     {
         reason = "Server is shutting down";
         return false;
     }
     if (getApp().getOPs ().isNeedNetworkLedger ())
     {
         reason = "Not synchronized with network yet";
         return false;
     }
     if (getApp().getOPs ().getOperatingMode () < NetworkOPs::omSYNCING)
     {
         reason = "Not synchronized with network";
         return false;
     }
     if (!getApp().getLedgerMaster().isCaughtUp(reason))
         return false;
     if (getApp().getFeeTrack ().isLoadedLocal ())
     {
         reason = "Too much load";
         return false;
     }
     if (getApp().getOPs ().isFeatureBlocked ())
     {
         reason = "Server version too old";
         return false;
     }
     return true;
 }
void ripple::setCallingThreadName (const char *)
Definition at line 90 of file ThreadName.cpp.
Referenced by run().
 {
     ;
 }
static void ripple::setupConfigForUnitTests (Config * config) static
Definition at line 138 of file Main.cpp.
References ripple::Config::ephemeralNodeDatabase, ripple::Config::importNodeDatabase, ripple::Config::nodeDatabase, and parseDelimitedKeyValueString().
Referenced by runUnitTests().
 {
     config->nodeDatabase = parseDelimitedKeyValueString ("type=memory");
     config->ephemeralNodeDatabase = beast::StringPairArray ();
     config->importNodeDatabase = beast::StringPairArray ();
 }
void ripple::setupServer ()
Definition at line 28 of file Main.cpp.
References getApp(), and ripple::Application::setup().
Referenced by run().
 {
 #ifdef RLIMIT_NOFILE
     struct rlimit rl;
     if (getrlimit(RLIMIT_NOFILE, &rl) == 0)
     {
          if (rl.rlim_cur != rl.rlim_max)
          {
              rl.rlim_cur = rl.rlim_max;
              setrlimit(RLIMIT_NOFILE, &rl);
          }
     }
 #endif
     getApp().setup ();
 }
template<typename T1 > uint256 ripple::SHA256Hash (const T1 pbegin, const T1 pend)
Definition at line 31 of file HashUtilities.h.
Referenced by ripple::Base58::decodeWithCheck(), and ripple::Base58::fourbyte_hash256().
 {
     static unsigned char pblank[1];
     uint256 hash1;
     SHA256 ((pbegin == pend ? pblank : (unsigned char*)&pbegin[0]), (pend - pbegin) * sizeof (pbegin[0]), (unsigned char*)&hash1);
     uint256 hash2;
     SHA256 ((unsigned char*)&hash1, sizeof (hash1), (unsigned char*)&hash2);
     return hash2;
 }
template<typename T1 , typename T2 > uint256 ripple::SHA256Hash (const T1 p1begin, const T1 p1end, const T2 p2begin, const T2 p2end)
Definition at line 42 of file HashUtilities.h.
References SHA256_Final(), SHA256_Init(), and SHA256_Update().
 {
     static unsigned char pblank[1];
     uint256 hash1;
     SHA256_CTX ctx;
     SHA256_Init (&ctx);
     SHA256_Update (&ctx, (p1begin == p1end ? pblank : (unsigned char*)&p1begin[0]), (p1end - p1begin) * sizeof (p1begin[0]));
     SHA256_Update (&ctx, (p2begin == p2end ? pblank : (unsigned char*)&p2begin[0]), (p2end - p2begin) * sizeof (p2begin[0]));
     SHA256_Final ((unsigned char*)&hash1, &ctx);
     uint256 hash2;
     SHA256 ((unsigned char*)&hash1, sizeof (hash1), (unsigned char*)&hash2);
     return hash2;
 }
template<typename T1 , typename T2 , typename T3 > uint256 ripple::SHA256Hash (const T1 p1begin, const T1 p1end, const T2 p2begin, const T2 p2end, const T3 p3begin, const T3 p3end)
Definition at line 58 of file HashUtilities.h.
References SHA256_Final(), SHA256_Init(), and SHA256_Update().
 {
     static unsigned char pblank[1];
     uint256 hash1;
     SHA256_CTX ctx;
     SHA256_Init (&ctx);
     SHA256_Update (&ctx, (p1begin == p1end ? pblank : (unsigned char*)&p1begin[0]), (p1end - p1begin) * sizeof (p1begin[0]));
     SHA256_Update (&ctx, (p2begin == p2end ? pblank : (unsigned char*)&p2begin[0]), (p2end - p2begin) * sizeof (p2begin[0]));
     SHA256_Update (&ctx, (p3begin == p3end ? pblank : (unsigned char*)&p3begin[0]), (p3end - p3begin) * sizeof (p3begin[0]));
     SHA256_Final ((unsigned char*)&hash1, &ctx);
     uint256 hash2;
     SHA256 ((unsigned char*)&hash1, sizeof (hash1), (unsigned char*)&hash2);
     return hash2;
 }
static std::string ripple::sqlEscape (const std::string & strSrc) inline static
Definition at line 72 of file StringUtilities.h.
References f, and strHex().
Referenced by ripple::LocalCredentials::dataDelete(), ripple::LocalCredentials::dataFetch(), ripple::LocalCredentials::dataStore(), ripple::ValidationsImp::doWrite(), ripple::AcceptedLedgerTx::getEscMeta(), ripple::SerializedTransaction::getMetaSQL(), ripple::UniqueNodeListImp::getSeedDomains(), ripple::SerializedTransaction::getSQL(), ripple::LocalCredentials::nodeIdentityCreate(), ripple::UniqueNodeListImp::nodeRemoveDomain(), ripple::UniqueNodeListImp::nodeRemovePublic(), ripple::UniqueNodeListImp::processIps(), ripple::UniqueNodeListImp::processValidators(), ripple::UniqueNodeListImp::scoreCompute(), ripple::UniqueNodeListImp::setSeedDomains(), and ripple::UniqueNodeListImp::setSeedNodes().
 {
     static boost::format f ("X'%s'");
     return str (boost::format (f) % strHex (strSrc));
 }
static std::string ripple::sqlEscape (Blob const & vecSrc) inline static
Definition at line 78 of file StringUtilities.h.
References charHex().
 {
     size_t size = vecSrc.size ();
     if (size == 0)
         return "X''";
     std::string j (size * 2 + 3, 0);
     unsigned char* oPtr = reinterpret_cast<unsigned char*> (&*j.begin ());
     const unsigned char* iPtr = &vecSrc[0];
     *oPtr++ = 'X';
     *oPtr++ = '\'';
     for (int i = size; i != 0; --i)
     {
         unsigned char c = *iPtr++;
         *oPtr++ = charHex (c >> 4);
         *oPtr++ = charHex (c & 15);
     }
     *oPtr++ = '\'';
     return j;
 }
static int ripple::SqliteWALHook (void * s, sqlite3 * dbCon, const char * dbName, int walSize) static
Definition at line 293 of file SqliteDatabase.cpp.
References SQLITE_OK.
Referenced by ripple::SqliteDatabase::setupCheckpointing().
 {
     (reinterpret_cast<SqliteDatabase*> (s))->doHook (dbName, walSize);
     return SQLITE_OK;
 }
void ripple::startServer ()
Definition at line 45 of file Main.cpp.
References ripple::Config::ADMIN, ripple::RPCHandler::doCommand(), ripple::Resource::feeReferenceRPC, getApp(), getConfig(), ripple::Config::RPC_STARTUP, ripple::Application::run(), and Json::Value::size().
Referenced by run().
 {
     //
     // Execute start up rpc commands.
     //
     if (getConfig ().RPC_STARTUP.isArray ())
     {
         for (int i = 0; i != getConfig ().RPC_STARTUP.size (); ++i)
         {
             const Json::Value& jvCommand    = getConfig ().RPC_STARTUP[i];
             if (!getConfig ().QUIET)
                 Log::out() << "Startup RPC: " << jvCommand;
             RPCHandler  rhHandler (&getApp().getOPs ());
             Resource::Charge loadType = Resource::feeReferenceRPC;
             Json::Value jvResult    = rhHandler.doCommand (jvCommand, Config::ADMIN, loadType);
             if (!getConfig ().QUIET)
                 Log::out() << "Result: " << jvResult;
         }
     }
     getApp().run ();                 // Blocks till we get a stop RPC.
 }
static void ripple::stateItemFullAppender (Json::Value & value, SLE::ref sle) static
Definition at line 1016 of file Ledger.cpp.
References Json::Value::append().
Referenced by ripple::Ledger::getJson().
 {
     value.append (sle->getJson (0));
 }
static void ripple::stateItemTagAppender (Json::Value & value, SHAMapItem::ref smi) static
Definition at line 1011 of file Ledger.cpp.
References Json::Value::append().
Referenced by ripple::Ledger::getJson().
 {
     value.append (smi->getTag ().GetHex ());
 }
std::string ripple::StopSustain ()
Definition at line 107 of file Sustain.cpp.
Referenced by ripple::ApplicationImp::doStop(), and ripple::ApplicationImp::updateTables().
 {
     return std::string ();
 }
Blob ripple::strCopy (const std::string & strSrc)
Definition at line 147 of file StringUtilities.cpp.
Referenced by ripple::Database::getStrBinary(), ripple::RPCServerImp::handle_read_req(), ripple::InboundLedger::processData(), ripple::PeerImp::recvPropose(), ripple::RippleAddress_test::run(), strUnHex(), and ripple::InboundLedger::tryLocal().
 {
     Blob vucDst;
     vucDst.resize (strSrc.size ());
     std::copy (strSrc.begin (), strSrc.end (), vucDst.begin ());
     return vucDst;
 }
std::string ripple::strCopy (Blob const & vucSrc)
Definition at line 158 of file StringUtilities.cpp.
 {
     std::string strDst;
     strDst.resize (vucSrc.size ());
     std::copy (vucSrc.begin (), vucSrc.end (), strDst.begin ());
     return strDst;
 }
std::string ripple::strGetEnv (const std::string & strKey) inline
Definition at line 116 of file StringUtilities.h.
Referenced by ripple::Config::setup().
 {
     return getenv (strKey.c_str ()) ? getenv (strKey.c_str ()) : "";
 }
template<class Iterator > std::string ripple::strHex (Iterator first, int iSize)
Definition at line 45 of file strHex.h.
References charHex().
Referenced by ripple::AcceptedLedgerTx::buildJson(), ripple::AccountState::createGravatarUrl(), ripple::LedgerEntrySet::dirAdd(), ripple::LedgerEntrySet::dirDelete(), ripple::RPCHandler::doLedgerData(), ripple::RPCHandler::doLedgerEntry(), ripple::RPCHandler::doLedgerHeader(), ripple::RPCHandler::doSubmit(), ripple::RPCHandler::doWalletPropose(), ripple::NetworkOPsImp::getAccountTxsB(), ripple::NetworkOPsImp::getDirNodeInfo(), ripple::base_uint< BITS >::GetHex(), ripple::SerializedTransaction::getJson(), ripple::STUInt64::getJson(), ripple::STPath::getJson(), ripple::Ledger::getMetaHex(), ripple::STVariableLength::getText(), ripple::NetworkOPsImp::getTxsAccountB(), ripple::PeerImp::processReadBuffer(), ripple::SHAMapTreeNode::SHAMapTreeNode(), sqlEscape(), strHex(), ripple::SimpleIdentifier< 32 >::to_string(), and ripple::RPC::transactionSign().
 {
     std::string strDst;
     strDst.resize (iSize * 2);
     for (int i = 0; i < iSize; i++)
     {
         unsigned char c = *first++;
         strDst[i * 2]     = charHex (c >> 4);
         strDst[i * 2 + 1] = charHex (c & 15);
     }
     return strDst;
 }
const std::string ripple::strHex (const std::string & strSrc) inline
Definition at line 55 of file StringUtilities.h.
References strHex().
 {
     return strHex (strSrc.begin (), strSrc.size ());
 }
std::string ripple::strHex (Blob const & vucData) inline
Definition at line 60 of file StringUtilities.h.
References strHex().
 {
     return strHex (vucData.begin (), vucData.size ());
 }
std::string ripple::strHex (const std::uint64_t uiHost) inline
Definition at line 65 of file StringUtilities.h.
References strHex().
 {
     uint64_t    uBig    = htobe64 (uiHost);
     return strHex ((unsigned char*) &uBig, sizeof (uBig));
 }
const std::string ripple::strHex (const uint160 & ui) inline
Definition at line 185 of file UInt160.h.
References ripple::base_uint< BITS >::begin(), ripple::base_uint< BITS >::size(), and strHex().
 {
     return strHex (ui.begin (), ui.size ());
 }
template<class Iterator > std::string ripple::strJoin (Iterator first, Iterator last, std::string strSeperator)
Definition at line 42 of file StringUtilities.h.
Referenced by ripple::UniqueNodeListImp::processIps(), ripple::UniqueNodeListImp::processValidators(), ripple::UniqueNodeListImp::scoreCompute(), and ripple::UniqueNodeListImp::scoreRound().
 {
     std::ostringstream  ossValues;
     for (Iterator start = first; first != last; first++)
     {
         ossValues << str (boost::format ("%s%s") % (start == first ? "" : strSeperator) % *first);
     }
     return ossValues.str ();
 }
std::string ripple::strprintf (const char * format, ...)
Definition at line 34 of file StringUtilities.cpp.
References _vsnprintf.
Referenced by ripple::RPCCallImp::onResponse().
 {
     char buffer[50000];
     char* p = buffer;
     int limit = sizeof (buffer);
     int ret;
     for (;;)
     {
         va_list arg_ptr;
         va_start (arg_ptr, format);
         ret = _vsnprintf (p, limit, format, arg_ptr);
         va_end (arg_ptr);
         if (ret >= 0 && ret < limit)
             break;
         if (p != buffer)
             delete[] p;
         limit *= 2;
         p = new char[limit];
         if (p == nullptr)
             throw std::bad_alloc ();
     }
     std::string str (p, p + ret);
     if (p != buffer)
         delete[] p;
     return str;
 }
int ripple::strUnHex (std::string & strDst, const std::string & strSrc)
Definition at line 72 of file StringUtilities.cpp.
References charUnHex().
Referenced by ripple::RPCHandler::doSubmit(), ripple::STParsedJSON::parse(), strUnHex(), ripple::StringUtilities_test::testUnHexFailure(), and ripple::StringUtilities_test::testUnHexSuccess().
 {
     std::string tmp;
     tmp.reserve ((strSrc.size () + 1) / 2);
     auto iter = strSrc.cbegin ();
     if (strSrc.size () & 1)
     {
         int c = charUnHex (*iter);
         if (c < 0)
             return -1;
         tmp.push_back(c);
         ++iter;
     }
     while (iter != strSrc.cend ())
     {
         int cHigh = charUnHex (*iter);
         ++iter;
         if (cHigh < 0)
             return -1;
         int cLow = charUnHex (*iter);
         ++iter;
         if (cLow < 0)
             return -1;
         tmp.push_back (static_cast<char>((cHigh << 4) | cLow));
     }
     strDst = std::move(tmp);
     return strDst.size ();
 }
std::pair< Blob, bool > ripple::strUnHex (const std::string & strSrc)
Definition at line 113 of file StringUtilities.cpp.
References strCopy(), and strUnHex().
 {
     std::string strTmp;
     if (strUnHex (strTmp, strSrc) == -1)
         return std::make_pair (Blob (), false);
     return std::make_pair(strCopy (strTmp), true);
 }
static void ripple::TACompletionHandler (uint256 hash, SHAMap::pointer map) static
Definition at line 51 of file TransactionAcquire.cpp.
References ripple::InboundLedgers::dropLedger(), getApp(), ripple::Application::getInboundLedgers(), ripple::Application::getOPs(), and ripple::NetworkOPs::mapComplete().
Referenced by ripple::TransactionAcquire::done().
 {
     {
         Application::ScopedLockType lock (getApp ().getMasterLock ());
         getApp().getOPs ().mapComplete (hash, map);
         getApp().getInboundLedgers ().dropLedger (hash);
     }
 }
int ripple::Testuint256AdHoc (std::vector< std::string > vArg) inline
Definition at line 203 of file UInt256.h.
References ripple::base_uint< BITS >::ToString(), and ripple::base_uint< BITS >::WIDTH.
 {
     uint256 g (std::uint64_t (0));
     printf ("%s\n", g.ToString ().c_str ());
     --g;
     printf ("--g\n");
     printf ("%s\n", g.ToString ().c_str ());
     g--;
     printf ("g--\n");
     printf ("%s\n", g.ToString ().c_str ());
     g++;
     printf ("g++\n");
     printf ("%s\n", g.ToString ().c_str ());
     ++g;
     printf ("++g\n");
     printf ("%s\n", g.ToString ().c_str ());
     g++;
     printf ("g++\n");
     printf ("%s\n", g.ToString ().c_str ());
     ++g;
     printf ("++g\n");
     printf ("%s\n", g.ToString ().c_str ());
     uint256 a (7);
     printf ("a=7\n");
     printf ("%s\n", a.ToString ().c_str ());
     uint256 b;
     printf ("b undefined\n");
     printf ("%s\n", b.ToString ().c_str ());
     int c = 3;
     a = c;
     a.pn[3] = 15;
     printf ("%s\n", a.ToString ().c_str ());
     uint256 k (c);
     a = 5;
     a.pn[3] = 15;
     printf ("%s\n", a.ToString ().c_str ());
     b = 1;
     // b <<= 52;
     a |= b;
     // a ^= 0x500;
     printf ("a %s\n", a.ToString ().c_str ());
     a = a | b | (uint256)0x1000;
     printf ("a %s\n", a.ToString ().c_str ());
     printf ("b %s\n", b.ToString ().c_str ());
     a = 0xfffffffe;
     a.pn[4] = 9;
     printf ("%s\n", a.ToString ().c_str ());
     a++;
     printf ("%s\n", a.ToString ().c_str ());
     a++;
     printf ("%s\n", a.ToString ().c_str ());
     a++;
     printf ("%s\n", a.ToString ().c_str ());
     a++;
     printf ("%s\n", a.ToString ().c_str ());
     a--;
     printf ("%s\n", a.ToString ().c_str ());
     a--;
     printf ("%s\n", a.ToString ().c_str ());
     a--;
     printf ("%s\n", a.ToString ().c_str ());
     uint256 d = a--;
     printf ("%s\n", d.ToString ().c_str ());
     printf ("%s\n", a.ToString ().c_str ());
     a--;
     printf ("%s\n", a.ToString ().c_str ());
     a--;
     printf ("%s\n", a.ToString ().c_str ());
     d = a;
     printf ("%s\n", d.ToString ().c_str ());
     for (int i = uint256::WIDTH - 1; i >= 0; i--) printf ("%08x", d.pn[i]);
     printf ("\n");
     uint256 neg = d;
     neg = ~neg;
     printf ("%s\n", neg.ToString ().c_str ());
     uint256 e = uint256 ("0xABCDEF123abcdef12345678909832180000011111111");
     printf ("\n");
     printf ("%s\n", e.ToString ().c_str ());
     printf ("\n");
     uint256 x1 = uint256 ("0xABCDEF123abcdef12345678909832180000011111111");
     uint256 x2;
     printf ("%s\n", x1.ToString ().c_str ());
     for (int i = 0; i < 270; i += 4)
     {
         // x2 = x1 << i;
         printf ("%s\n", x2.ToString ().c_str ());
     }
     printf ("\n");
     printf ("%s\n", x1.ToString ().c_str ());
     for (int i = 0; i < 270; i += 4)
     {
         x2 = x1;
         // x2 >>= i;
         printf ("%s\n", x2.ToString ().c_str ());
     }
 #if 0
     for (int i = 0; i < 100; i++)
     {
         uint256 k = (~uint256 (0) >> i);
         printf ("%s\n", k.ToString ().c_str ());
     }
     for (int i = 0; i < 100; i++)
     {
         uint256 k = (~uint256 (0) << i);
         printf ("%s\n", k.ToString ().c_str ());
     }
 #endif
     return (0);
 }
static void ripple::textTime (std::string & text, int & seconds, const char * unitName, int unitVal) static
Definition at line 23 of file Feature.cpp.
Referenced by ripple::RPCHandler::doGetCounts().
 {
     int i = seconds / unitVal;
     if (i == 0)
         return;
     seconds -= unitVal * i;
     if (!text.empty ())
         text += ", ";
     text += beast::lexicalCastThrow <std::string> (i);
     text += " ";
     text += unitName;
     if (i > 1)
         text += "s";
 }
template<typename Object > double ripple::timedDestroy (Object & object)
Measure the time required to destroy an object.
Definition at line 88 of file LoggedTimings.h.
References beast::Time::getHighResolutionTicks(), and beast::Time::highResolutionTicksToSeconds().
Referenced by logTimedDestroy().
 {
     std::int64_t const startTime (beast::Time::getHighResolutionTicks ());
     detail::Destroyer <Object>::destroy (object);
     return beast::Time::highResolutionTicksToSeconds (
             beast::Time::getHighResolutionTicks () - startTime);
 }
std::string ripple::to_string (Peer const & peer) inline
Definition at line 2830 of file PeerImp.h.
References ripple::Peer::getClusterNodeName(), ripple::Peer::getRemoteAddress(), ripple::Peer::isInCluster(), and beast::IP::Endpoint::to_string().
Referenced by ripple::PeerImp::checkValidation(), ripple::WSServerHandler< endpoint_type >::do_message(), ripple::PeerImp::getLedger(), ripple::Resource::Logic::newInboundEndpoint(), ripple::Resource::Logic::newOutboundEndpoint(), ripple::WSServerHandler< endpoint_type >::on_message(), ripple::OverlayImpl::onPrepare(), operator<<(), ripple::NetworkOPsImp::processClusterTimer(), ripple::PeerImp::recvGetObjectByHash(), ripple::PeerImp::recvStatus(), ripple::PeerFinder::StoreSqdb::save(), to_string(), ripple::PeerFinder::StoreSqdb::update(), and ripple::PeerFinder::Logic::writeSlots().
 {
     if (peer.isInCluster())
         return peer.getClusterNodeName();
     return peer.getRemoteAddress().to_string();
 }
std::string ripple::to_string (Peer const * peer) inline
Definition at line 2838 of file PeerImp.h.
References to_string().
 {
     return to_string (*peer);
 }
std::string ripple::to_string (PeerImp const & peer) inline
Definition at line 2801 of file PeerImp.h.
References ripple::PeerImp::getClusterNodeName(), ripple::PeerImp::getRemoteAddress(), ripple::PeerImp::isInCluster(), and beast::IP::Endpoint::to_string().
 {
     if (peer.isInCluster())
         return peer.getClusterNodeName();
     return peer.getRemoteAddress().to_string();
 }
std::string ripple::to_string (PeerImp const * peer) inline
Definition at line 2809 of file PeerImp.h.
References to_string().
 {
     return to_string (*peer);
 }
std::string ripple::transHuman (TER terCode)
Definition at line 148 of file TER.cpp.
References transResultInfo().
Referenced by ripple::TransactionEngine::applyTransaction(), ripple::LedgerConsensusImp::applyTransaction(), ripple::AcceptedLedgerTx::buildJson(), ripple::RPCHandler::doRipplePathFind(), and ripple::PathRequest::doUpdate().
 {
     std::string strToken;
     std::string strHuman;
     return transResultInfo (terCode, strToken, strHuman) ? strHuman : "-";
 }
bool ripple::transResultInfo (TER terCode, std::string & strToken, std::string & strHuman)
Definition at line 22 of file TER.cpp.
References NUMBER, tecCLAIM, tecDIR_FULL, tecFAILED_PROCESSING, tecINSUF_RESERVE_LINE, tecINSUF_RESERVE_OFFER, tecMASTER_DISABLED, tecNO_AUTH, tecNO_DST, tecNO_DST_INSUF_XRP, tecNO_ISSUER, tecNO_LINE, tecNO_LINE_INSUF_RESERVE, tecNO_LINE_REDUNDANT, tecNO_REGULAR_KEY, tecOWNERS, tecPATH_DRY, tecPATH_PARTIAL, tecUNFUNDED, tecUNFUNDED_ADD, tecUNFUNDED_OFFER, tecUNFUNDED_PAYMENT, tefALREADY, tefBAD_ADD_AUTH, tefBAD_AUTH, tefBAD_CLAIM_ID, tefBAD_GEN_AUTH, tefBAD_LEDGER, tefCLAIMED, tefCREATED, tefDST_TAG_NEEDED, tefEXCEPTION, tefFAILURE, tefGEN_IN_USE, tefINTERNAL, tefMASTER_DISABLED, tefMAX_LEDGER, tefNO_AUTH_REQUIRED, tefPAST_SEQ, tefWRONG_PRIOR, telBAD_DOMAIN, telBAD_PATH_COUNT, telBAD_PUBLIC_KEY, telFAILED_PROCESSING, telINSUF_FEE_P, telLOCAL_ERROR, telNO_DST_PARTIAL, temBAD_AMOUNT, temBAD_AUTH_MASTER, temBAD_CURRENCY, temBAD_EXPIRATION, temBAD_FEE, temBAD_ISSUER, temBAD_LIMIT, temBAD_OFFER, temBAD_PATH, temBAD_PATH_LOOP, temBAD_PUBLISH, temBAD_SEND_XRP_LIMIT, temBAD_SEND_XRP_MAX, temBAD_SEND_XRP_NO_DIRECT, temBAD_SEND_XRP_PARTIAL, temBAD_SEND_XRP_PATHS, temBAD_SEQUENCE, temBAD_SIGNATURE, temBAD_SRC_ACCOUNT, temBAD_TRANSFER_RATE, temDST_IS_SRC, temDST_NEEDED, temINVALID, temINVALID_FLAG, temMALFORMED, temREDUNDANT, temREDUNDANT_SEND_MAX, temRIPPLE_EMPTY, temUNCERTAIN, temUNKNOWN, terFUNDS_SPENT, terINSUF_FEE_B, terLAST, terNO_ACCOUNT, terNO_AUTH, terNO_LINE, terNO_RIPPLE, terOWNERS, terPRE_SEQ, terRETRY, and tesSUCCESS.
Referenced by ripple::TransactionEngine::applyTransaction(), ripple::PaymentTransactor::doApply(), ripple::RPCHandler::doRipplePathFind(), ripple::RPCHandler::doSubmit(), ripple::STUInt8::getJson(), ripple::STUInt8::getText(), ripple::NetworkOPsImp::processTransactionCb(), ripple::RPC::transactionSign(), transHuman(), ripple::NetworkOPsImp::transJson(), and transToken().
 {
     static struct
     {
         TER             terCode;
         const char*     cpToken;
         const char*     cpHuman;
     } transResultInfoA[] =
     {
         {   tecCLAIM,               "tecCLAIM",                 "Fee claimed. Sequence used. No action."                },
         {   tecDIR_FULL,            "tecDIR_FULL",              "Can not add entry to full directory."                  },
         {   tecFAILED_PROCESSING,   "tecFAILED_PROCESSING",     "Failed to correctly process transaction."              },
         {   tecINSUF_RESERVE_LINE,  "tecINSUF_RESERVE_LINE",    "Insufficient reserve to add trust line."               },
         {   tecINSUF_RESERVE_OFFER, "tecINSUF_RESERVE_OFFER",   "Insufficient reserve to create offer."                 },
         {   tecNO_DST,              "tecNO_DST",                "Destination does not exist. Send XRP to create it."    },
         {   tecNO_DST_INSUF_XRP,    "tecNO_DST_INSUF_XRP",      "Destination does not exist. Too little XRP sent to create it."     },
         {   tecNO_LINE_INSUF_RESERVE,   "tecNO_LINE_INSUF_RESERVE", "No such line. Too little reserve to create it."    },
         {   tecNO_LINE_REDUNDANT,   "tecNO_LINE_REDUNDANT",     "Can't set non-existant line to default."               },
         {   tecPATH_DRY,            "tecPATH_DRY",              "Path could not send partial amount."                   },
         {   tecPATH_PARTIAL,        "tecPATH_PARTIAL",          "Path could not send full amount."                      },
         {   tecMASTER_DISABLED,     "tecMASTER_DISABLED",       "Master key is disabled."                               },
         {   tecNO_REGULAR_KEY,      "tecNO_REGULAR_KEY",        "Regular key is not set."                               },
         {   tecUNFUNDED,            "tecUNFUNDED",              "One of _ADD, _OFFER, or _SEND. Deprecated."            },
         {   tecUNFUNDED_ADD,        "tecUNFUNDED_ADD",          "Insufficient XRP balance for WalletAdd."               },
         {   tecUNFUNDED_OFFER,      "tecUNFUNDED_OFFER",        "Insufficient balance to fund created offer."           },
         {   tecUNFUNDED_PAYMENT,    "tecUNFUNDED_PAYMENT",      "Insufficient XRP balance to send."                     },
         {   tecOWNERS,              "tecOWNERS",                "Non-zero owner count."                                 },
         {   tecNO_ISSUER,           "tecNO_ISSUER",             "Issuer account does not exist."                        },
         {   tecNO_AUTH,             "tecNO_AUTH",               "Not authorized to hold asset."                         },
         {   tecNO_LINE,             "tecNO_LINE",               "No such line."                                         },
         {   tefFAILURE,             "tefFAILURE",               "Failed to apply."                                      },
         {   tefALREADY,             "tefALREADY",               "The exact transaction was already in this ledger."     },
         {   tefBAD_ADD_AUTH,        "tefBAD_ADD_AUTH",          "Not authorized to add account."                        },
         {   tefBAD_AUTH,            "tefBAD_AUTH",              "Transaction's public key is not authorized."           },
         {   tefBAD_CLAIM_ID,        "tefBAD_CLAIM_ID",          "Malformed: Bad claim id."                              },
         {   tefBAD_GEN_AUTH,        "tefBAD_GEN_AUTH",          "Not authorized to claim generator."                    },
         {   tefBAD_LEDGER,          "tefBAD_LEDGER",            "Ledger in unexpected state."                           },
         {   tefCLAIMED,             "tefCLAIMED",               "Can not claim a previously claimed account."           },
         {   tefCREATED,             "tefCREATED",               "Can't add an already created account."                 },
         {   tefDST_TAG_NEEDED,      "tefDST_TAG_NEEDED",        "Destination tag required."                             },
         {   tefEXCEPTION,           "tefEXCEPTION",             "Unexpected program state."                             },
         {   tefGEN_IN_USE,          "tefGEN_IN_USE",            "Generator already in use."                             },
         {   tefINTERNAL,            "tefINTERNAL",              "Internal error."                                       },
         {   tefNO_AUTH_REQUIRED,    "tefNO_AUTH_REQUIRED",      "Auth is not required."                                 },
         {   tefPAST_SEQ,            "tefPAST_SEQ",              "This sequence number has already past."                },
         {   tefWRONG_PRIOR,         "tefWRONG_PRIOR",           "This previous transaction does not match."             },
         {   tefMASTER_DISABLED,     "tefMASTER_DISABLED",       "Master key is disabled."                               },
         {   tefMAX_LEDGER,          "tefMAX_LEDGER",            "Ledger sequence too high."                             },
         {   telLOCAL_ERROR,         "telLOCAL_ERROR",           "Local failure."                                        },
         {   telBAD_DOMAIN,          "telBAD_DOMAIN",            "Domain too long."                                      },
         {   telBAD_PATH_COUNT,      "telBAD_PATH_COUNT",        "Malformed: Too many paths."                            },
         {   telBAD_PUBLIC_KEY,      "telBAD_PUBLIC_KEY",        "Public key too long."                                  },
         {   telFAILED_PROCESSING,   "telFAILED_PROCESSING",     "Failed to correctly process transaction."              },
         {   telINSUF_FEE_P,         "telINSUF_FEE_P",           "Fee insufficient."                                     },
         {   telNO_DST_PARTIAL,      "telNO_DST_PARTIAL",        "Partial payment to create account not allowed."        },
         {   temMALFORMED,           "temMALFORMED",             "Malformed transaction."                                },
         {   temBAD_AMOUNT,          "temBAD_AMOUNT",            "Can only send positive amounts."                       },
         {   temBAD_AUTH_MASTER,     "temBAD_AUTH_MASTER",       "Auth for unclaimed account needs correct master key."  },
         {   temBAD_CURRENCY,        "temBAD_CURRENCY",          "Malformed: Bad currency."                              },
         {   temBAD_FEE,             "temBAD_FEE",               "Invalid fee, negative or not XRP."                     },
         {   temBAD_EXPIRATION,      "temBAD_EXPIRATION",        "Malformed: Bad expiration."                            },
         {   temBAD_ISSUER,          "temBAD_ISSUER",            "Malformed: Bad issuer."                                },
         {   temBAD_LIMIT,           "temBAD_LIMIT",             "Limits must be non-negative."                          },
         {   temBAD_OFFER,           "temBAD_OFFER",             "Malformed: Bad offer."                                 },
         {   temBAD_PATH,            "temBAD_PATH",              "Malformed: Bad path."                                  },
         {   temBAD_PATH_LOOP,       "temBAD_PATH_LOOP",         "Malformed: Loop in path."                              },
         {   temBAD_PUBLISH,         "temBAD_PUBLISH",           "Malformed: Bad publish."                               },
         {   temBAD_SIGNATURE,       "temBAD_SIGNATURE",         "Malformed: Bad signature."                             },
         {   temBAD_SRC_ACCOUNT,     "temBAD_SRC_ACCOUNT",       "Malformed: Bad source account."                        },
         {   temBAD_TRANSFER_RATE,   "temBAD_TRANSFER_RATE",     "Malformed: Transfer rate must be >= 1.0"               },
         {   temBAD_SEQUENCE,        "temBAD_SEQUENCE",          "Malformed: Sequence is not in the past."               },
         {   temBAD_SEND_XRP_LIMIT,      "temBAD_SEND_XRP_LIMIT",        "Malformed: Limit quality is not allowed for XRP to XRP."       },
         {   temBAD_SEND_XRP_MAX,        "temBAD_SEND_XRP_MAX",          "Malformed: Send max is not allowed for XRP to XRP."            },
         {   temBAD_SEND_XRP_NO_DIRECT,  "temBAD_SEND_XRP_NO_DIRECT",    "Malformed: No Ripple direct is not allowed for XRP to XRP."    },
         {   temBAD_SEND_XRP_PARTIAL,    "temBAD_SEND_XRP_PARTIAL",      "Malformed: Partial payment is not allowed for XRP to XRP."     },
         {   temBAD_SEND_XRP_PATHS,      "temBAD_SEND_XRP_PATHS",        "Malformed: Paths are not allowed for XRP to XRP."              },
         {   temDST_IS_SRC,          "temDST_IS_SRC",            "Destination may not be source."                        },
         {   temDST_NEEDED,          "temDST_NEEDED",            "Destination not specified."                            },
         {   temINVALID,             "temINVALID",               "The transaction is ill-formed."                        },
         {   temINVALID_FLAG,        "temINVALID_FLAG",          "The transaction has an invalid flag."                  },
         {   temREDUNDANT,           "temREDUNDANT",             "Sends same currency to self."                          },
         {   temREDUNDANT_SEND_MAX,  "temREDUNDANT_SEND_MAX",    "Send max is redundant."                                },
         {   temRIPPLE_EMPTY,        "temRIPPLE_EMPTY",          "PathSet with no paths."                                },
         {   temUNCERTAIN,           "temUNCERTAIN",             "In process of determining result. Never returned."     },
         {   temUNKNOWN,             "temUNKNOWN",               "The transactions requires logic not implemented yet."  },
         {   terRETRY,               "terRETRY",                 "Retry transaction."                                    },
         {   terFUNDS_SPENT,         "terFUNDS_SPENT",           "Can't set password, password set funds already spent." },
         {   terINSUF_FEE_B,         "terINSUF_FEE_B",           "Account balance can't pay fee."                        },
         {   terLAST,                "terLAST",                  "Process last."                                         },
         {   terNO_RIPPLE,           "terNO_RIPPLE",             "Path does not permit rippling."                        },
         {   terNO_ACCOUNT,          "terNO_ACCOUNT",            "The source account does not exist."                    },
         {   terNO_AUTH,             "terNO_AUTH",               "Not authorized to hold IOUs."                          },
         {   terNO_LINE,             "terNO_LINE",               "No such line."                                         },
         {   terPRE_SEQ,             "terPRE_SEQ",               "Missing/inapplicable prior transaction."               },
         {   terOWNERS,              "terOWNERS",                "Non-zero owner count."                                 },
         {   tesSUCCESS,             "tesSUCCESS",               "The transaction was applied."                          },
     };
     int iIndex  = NUMBER (transResultInfoA);
     while (iIndex-- && transResultInfoA[iIndex].terCode != terCode)
         ;
     if (iIndex >= 0)
     {
         strToken    = transResultInfoA[iIndex].cpToken;
         strHuman    = transResultInfoA[iIndex].cpHuman;
     }
     return iIndex >= 0;
 }
std::string ripple::transToken (TER terCode)
Definition at line 140 of file TER.cpp.
References transResultInfo().
Referenced by ripple::TransactionEngine::applyTransaction(), ripple::RippleCalc::calcNodeAdvance(), ripple::RippleCalc::calcNodeRev(), ripple::OfferCreateTransactor::doApply(), ripple::Pathfinder::filterPaths(), ripple::PathState::pushImply(), ripple::PathState::pushNode(), ripple::RippleCalc::rippleCalc(), and ripple::OfferCreateTransactor::takeOffers().
 {
     std::string strToken;
     std::string strHuman;
     return transResultInfo (terCode, strToken, strHuman) ? strToken : "-";
 }
static const uint160 ripple::u160_one (1)
Referenced by get_u160_one().
static const uint160 ripple::u160_zero (0) static
Referenced by get_u160_zero().
uint64_t ripple::uintFromHex (const std::string & strSrc)
Definition at line 123 of file StringUtilities.cpp.
References charUnHex().
Referenced by ripple::STParsedJSON::parse().
 {
     uint64_t uValue (0);
     if (strSrc.size () > 16)
         throw std::invalid_argument("overlong 64-bit value");
     for (auto c : strSrc)
     {
         int ret = charUnHex (c);
         if (ret == -1)
             throw std::invalid_argument("invalid hex digit");
         uValue = (uValue << 4) | ret;
     }
     return uValue;
 }
static void ripple::updateHelper (SLE::ref entry, boost::unordered_set< uint256 > & seen, ripple::unordered_map< RippleAsset, std::vector< OrderBook::pointer > > & destMap, ripple::unordered_map< RippleAsset, std::vector< OrderBook::pointer > > & sourceMap, boost::unordered_set< RippleAsset > & XRPBooks, int & books) static
Definition at line 65 of file OrderBookDB.cpp.
References ripple::Ledger::getBookBase(), ripple::base_uint< BITS >::isZero(), and ltDIR_NODE.
Referenced by ripple::OrderBookDB::update().
 {
     if ((entry->getType () == ltDIR_NODE) && (entry->isFieldPresent (sfExchangeRate)) &&
             (entry->getFieldH256 (sfRootIndex) == entry->getIndex()))
     {
         const uint160& ci = entry->getFieldH160 (sfTakerPaysCurrency);
         const uint160& co = entry->getFieldH160 (sfTakerGetsCurrency);
         const uint160& ii = entry->getFieldH160 (sfTakerPaysIssuer);
         const uint160& io = entry->getFieldH160 (sfTakerGetsIssuer);
         uint256 index = Ledger::getBookBase (ci, ii, co, io);
         if (seen.insert (index).second)
         {
             // VFALCO TODO Reduce the clunkiness of these parameter wrappers
             OrderBook::pointer book = boost::make_shared<OrderBook> (boost::cref (index),
                                       boost::cref (ci), boost::cref (co), boost::cref (ii), boost::cref (io));
             sourceMap[RippleAssetRef (ci, ii)].push_back (book);
             destMap[RippleAssetRef (co, io)].push_back (book);
             if (co.isZero())
                 XRPBooks.insert(RippleAssetRef (ci, ii));
             ++books;
         }
     }
 }
std::string ripple::urlEncode (const std::string & strSrc)
Definition at line 170 of file StringUtilities.cpp.
References charHex().
Referenced by ripple::HTTPClient::sendSMS().
 {
     std::string strDst;
     int         iOutput = 0;
     int         iSize   = strSrc.length ();
     strDst.resize (iSize * 3);
     for (int iInput = 0; iInput < iSize; iInput++)
     {
         unsigned char c = strSrc[iInput];
         if (c == ' ')
         {
             strDst[iOutput++]   = '+';
         }
         else if (isalnum (c))
         {
             strDst[iOutput++]   = c;
         }
         else
         {
             strDst[iOutput++]   = '%';
             strDst[iOutput++]   = charHex (c >> 4);
             strDst[iOutput++]   = charHex (c & 15);
         }
     }
     strDst.resize (iOutput);
     return strDst;
 }
boost::unordered_set< uint160 > ripple::usAccountDestCurrencies (const RippleAddress & raAccountID, RippleLineCache::ref lrCache, bool includeXRP)
Definition at line 430 of file Pathfinder.cpp.
References CURRENCY_BAD, CURRENCY_XRP, ripple::RippleAddress::getAccountID(), ripple::RippleState::getBalance(), ripple::STAmount::getCurrency(), and ripple::AccountItems::getItems().
Referenced by ripple::RPCHandler::doRipplePathFind(), and ripple::PathRequest::isValid().
 {
     boost::unordered_set<uint160>   usCurrencies;
     if (includeXRP)
         usCurrencies.insert (uint160 (CURRENCY_XRP)); // Even if account doesn't exist
     // List of ripple lines.
     AccountItems& rippleLines (lrCache->getRippleLines (raAccountID.getAccountID ()));
     BOOST_FOREACH (AccountItem::ref item, rippleLines.getItems ())
     {
         RippleState*    rspEntry    = (RippleState*) item.get ();
         const STAmount& saBalance   = rspEntry->getBalance ();
         if (saBalance < rspEntry->getLimit ())                  // Can take more
             usCurrencies.insert (saBalance.getCurrency ());
     }
     usCurrencies.erase (CURRENCY_BAD);
     return usCurrencies;
 }
boost::unordered_set< uint160 > ripple::usAccountSourceCurrencies (const RippleAddress & raAccountID, RippleLineCache::ref lrCache, bool includeXRP)
Definition at line 399 of file Pathfinder.cpp.
References CURRENCY_BAD, CURRENCY_XRP, ripple::RippleAddress::getAccountID(), ripple::RippleState::getBalance(), ripple::STAmount::getCurrency(), ripple::AccountItems::getItems(), and ripple::RippleState::getLimitPeer().
Referenced by ripple::RPCHandler::doRipplePathFind(), and ripple::PathRequest::doUpdate().
 {
     boost::unordered_set<uint160>   usCurrencies;
     // YYY Only bother if they are above reserve
     if (includeXRP)
         usCurrencies.insert (uint160 (CURRENCY_XRP));
     // List of ripple lines.
     AccountItems& rippleLines (lrCache->getRippleLines (raAccountID.getAccountID ()));
     BOOST_FOREACH (AccountItem::ref item, rippleLines.getItems ())
     {
         RippleState*    rspEntry    = (RippleState*) item.get ();
         const STAmount& saBalance   = rspEntry->getBalance ();
         // Filter out non
         if (saBalance > zero                             // Have IOUs to send.
                 || (rspEntry->getLimitPeer ()                       // Peer extends credit.
                     && ((-saBalance) < rspEntry->getLimitPeer ()))) // Credit left.
         {
             usCurrencies.insert (saBalance.getCurrency ());
         }
     }
     usCurrencies.erase (CURRENCY_BAD);
     return usCurrencies;
 }
uint64_t ripple::utFromSeconds (int iSeconds)
Definition at line 50 of file Time.cpp.
Referenced by ripple::NetworkOPsImp::pubBootstrapAccountInfo().
 {
     boost::posix_time::time_duration    tdDelta =
         boost::posix_time::ptime (boost::gregorian::date (2000, boost::gregorian::Jan, 1))
         - boost::posix_time::ptime (boost::gregorian::date (1970, boost::gregorian::Jan, 1))
         + boost::posix_time::seconds (iSeconds)
         ;
     return tdDelta.total_seconds ();
 }
static void ripple::visitHelper (std::function< void(SLE::ref)> & function, SHAMapItem::ref item) static
Definition at line 1250 of file Ledger.cpp.
Referenced by ripple::Ledger::visitStateItems().
 {
     function (boost::make_shared<SLE> (item->peekSerializer (), item->getTag ()));
 }
RippleAssetRef ripple::xrp_asset () inline
Returns an asset specifier that represents XRP.
Definition at line 189 of file RippleAssets.h.
 {
     static RippleAsset asset (RippleCurrency (0), RippleIssuer (0));
     return asset;
 }
uint160 const& ripple::xrp_currency () inline
Definition at line 39 of file BookOffers.cpp.
References CURRENCY_XRP.
 {
     return CURRENCY_XRP;
 }
uint160 const& ripple::xrp_issuer () inline
Definition at line 34 of file BookOffers.cpp.
References ACCOUNT_XRP.
Referenced by ripple::RPCHandler::doBookOffers().
 {
     return ACCOUNT_XRP;
 }
Variable Documentation
const std::uint32_t ripple::asfAccountTxnID = 5
Definition at line 65 of file TxFlags.h.
Referenced by ripple::AccountSetTransactor::doApply().
const std::uint32_t ripple::asfDisableMaster = 4
Definition at line 64 of file TxFlags.h.
Referenced by ripple::AccountSetTransactor::doApply().
const std::uint32_t ripple::asfDisallowXRP = 3
Definition at line 63 of file TxFlags.h.
Referenced by ripple::AccountSetTransactor::doApply().
const std::uint32_t ripple::asfRequireAuth = 2
Definition at line 62 of file TxFlags.h.
Referenced by ripple::AccountSetTransactor::doApply().
const std::uint32_t ripple::asfRequireDest = 1
Definition at line 61 of file TxFlags.h.
Referenced by ripple::AccountSetTransactor::doApply().
const int ripple::DOMAIN_BYTES_MAX = 256
Definition at line 36 of file Config.h.
Referenced by ripple::AccountSetTransactor::doApply().
bool volatile ripple::doShutdown = false static
Definition at line 29 of file Application.cpp.
Referenced by ripple::ApplicationImp::run().
const int ripple::f = initFields () static
Definition at line 226 of file FieldNames.cpp.
Referenced by rocksdb::FindFileTest::Add(), rocksdb::VersionEdit::AddFile(), ripple::FeaturesImpl::addKnown(), rocksdb::VersionSet::AddLiveFiles(), rocksdb::DBImpl::AppendSortedWalsOfType(), rocksdb::VersionSet::Builder::Apply(), rocksdb::DBImpl::BackgroundCompaction(), ripple::PeerFinder::Sim::breadth_first_traverse(), rocksdb::VersionSet::Builder::CheckConsistencyForDeletes(), beast::File::createFileWithoutCheckingPath(), rocksdb::VersionEdit::DebugString(), rocksdb::VersionEdit::DecodeFrom(), rocksdb::VersionEdit::EncodeTo(), rocksdb::Version::ExtendOverlappingInputs(), ripple::Validators::SourceFileImp::fetch(), rocksdb::DBTest::FilesPerLevel(), rocksdb::SimpleTableDBTest::FilesPerLevel(), rocksdb::FindFile(), ripple::Overlay::foreach(), rocksdb::Version::Get(), rocksdb::GetLogDirSize(), beast::File::getNonexistentChildFile(), rocksdb::Version::GetOverlappingInputs(), rocksdb::Version::GetOverlappingInputsBinarySearch(), beast::File::getParentDirectory(), ripple::ProofOfWorkFactoryImp::getProof(), rocksdb::VersionSet::GetRange(), beast::File::getVolumeLabel(), hasHotJournal(), beast::HiResCounterHandler::HiResCounterHandler, ripple::RippleSSLContextImp::initAuthenticated(), beast::asio::detail::shared_handler_wrapper< Signature, Handler >::invoke(), rocksdb::Compaction::IsBaseLevelForKey(), ripple::STObject::isFlag(), rocksdb::VersionSet::LevelFileSummary(), ripple::STObject::makeFieldAbsent(), ripple::STObject::makeFieldPresent(), rocksdb::VersionSet::MaxNextLevelOverlappingBytes(), beast::measureFunctionCallTime(), std::chrono::operator<<(), rocksdb::VersionSet::PickCompaction(), rocksdb::VersionSet::PickCompactionBySize(), rocksdb::VersionSet::PickCompactionUniversal(), rocksdb::VersionSet::PickCompactionUniversalReadAmp(), rocksdb::VersionSet::PickCompactionUniversalSizeAmp(), beast::asio::HTTPClient_test::print(), ripple::Validators::Utilities::processLines(), rocksdb::DBImpl::PurgeObsoleteWALFiles(), rocksdb::DBImpl::ReFitLevel(), beast::resolveXDGFolder(), beast::asio::bind_handler_test::run(), beast::shared_handler_test::run(), beast::asio::wrap_handler_test::run(), beast::PropertyStream_test::run(), rocksdb::EnvWrapper::Schedule(), beast::hash_metrics::detail::score(), send_if(), send_if_not(), ripple::STObject::setFlag(), ripple::LoadFeeTrackImp::setRemoteFee(), SHA256_Transform(), SHA512_Transform(), rocksdb::SomeFileOverlapsRange(), sqlEscape(), sqlite3PagerSharedLock(), sqlite3VdbeMemMakeWriteable(), rocksdb::EnvWrapper::StartThread(), ripple::static_call::static_call(), rocksdb::TEST(), rocksdb::Version::UpdateStats(), rocksdb::VersionSet::VerifyCompactionFileConsistency(), rocksdb::VersionSet::WriteSnapshot(), rocksdb::VersionSet::Builder::~Builder(), and rocksdb::Version::~Version().
unsigned int const ripple::gMaxHTTPHeaderSize = 0x02000000
Definition at line 27 of file RPCUtil.cpp.
Referenced by ReadHTTP().
int ripple::LedgerDBCount = NUMBER (LedgerDBInit)
Definition at line 103 of file DBInit.cpp.
Referenced by ripple::ApplicationImp::initSqliteDb().
const char * ripple::LedgerDBInit
Initial value:
=
{
    "PRAGMA synchronous=NORMAL;",
    "PRAGMA journal_mode=WAL;",
    "PRAGMA journal_size_limit=1582080;",
    "BEGIN TRANSACTION;",
    "CREATE TABLE Ledgers (                         \
        LedgerHash      CHARACTER(64) PRIMARY KEY,  \
        LedgerSeq       BIGINT UNSIGNED,            \
        PrevHash        CHARACTER(64),              \
        TotalCoins      BIGINT UNSIGNED,            \
        ClosingTime     BIGINT UNSIGNED,            \
        PrevClosingTime BIGINT UNSIGNED,            \
        CloseTimeRes    BIGINT UNSIGNED,            \
        CloseFlags      BIGINT UNSIGNED,            \
        AccountSetHash  CHARACTER(64),              \
        TransSetHash    CHARACTER(64)               \
    );",
    "CREATE INDEX SeqLedger ON Ledgers(LedgerSeq);",
    "CREATE TABLE Validations   (                   \
        LedgerHash  CHARACTER(64),                  \
        NodePubKey  CHARACTER(56),                  \
        SignTime    BIGINT UNSIGNED,                \
        RawData     BLOB                            \
    );",
    "CREATE INDEX ValidationsByHash ON              \
        Validations(LedgerHash);",
    "CREATE INDEX ValidationsByTime ON              \
        Validations(SignTime);",
    "END TRANSACTION;"
}
Definition at line 67 of file DBInit.cpp.
Referenced by ripple::ApplicationImp::initSqliteDb().
const SHAMapItem::pointer ripple::no_item static
Definition at line 508 of file SHAMap.cpp.
Referenced by ripple::SHAMap::peekFirstItem(), ripple::SHAMap::peekItem(), ripple::SHAMap::peekLastItem(), ripple::SHAMap::peekNextItem(), and ripple::SHAMap::peekPrevItem().
const int ripple::PUBLIC_BYTES_MAX = 33
Definition at line 37 of file Config.h.
Referenced by ripple::AccountSetTransactor::doApply().
ripple::unordered_map< Blob , std::string > ripple::rncMap static
Definition at line 315 of file RippleAddress.cpp.
Referenced by ripple::RippleAddress::humanAccountID().
int ripple::RpcDBCount = NUMBER (RpcDBInit)
Definition at line 116 of file DBInit.cpp.
Referenced by ripple::ApplicationImp::initSqliteDb().
const char * ripple::RpcDBInit
Initial value:
=
{
    "CREATE TABLE RPCData (                         \
        Key         TEXT PRIMARY Key,               \
        Value       TEXT                            \
    );",
}
Definition at line 106 of file DBInit.cpp.
Referenced by ripple::ApplicationImp::initSqliteDb().
StaticLockType ripple::s_lock static
Definition at line 313 of file RippleAddress.cpp.
Referenced by ripple::RippleAddress::humanAccountID().
int ripple::s_nodeStoreDBCount = NUMBER (s_nodeStoreDBInit) static
Definition at line 44 of file SqliteFactory.cpp.
const char* ripple::s_nodeStoreDBInit[] static
Initial value:
=
{
    "PRAGMA synchronous=NORMAL;",
    "PRAGMA journal_mode=WAL;",
    "PRAGMA journal_size_limit=1582080;",
    "BEGIN TRANSACTION;",
    "CREATE TABLE CommittedObjects (                \
        Hash        CHARACTER(64) PRIMARY KEY,      \
        ObjType     CHAR(1) NOT NULL,               \
        LedgerIndex BIGINT UNSIGNED,                \
        Object      BLOB                            \
    );",
    "END TRANSACTION;"
}
Definition at line 22 of file SqliteFactory.cpp.
const STAmount ripple::saOne
Definition at line 838 of file SerializedTypes.h.
Referenced by ripple::RippleCalc::calcNodeDeliverFwd(), and ripple::RippleCalc::calcNodeDeliverRev().
const STAmount ripple::saZero
Definition at line 837 of file SerializedTypes.h.
Referenced by ripple::PathState::pushNode().
SField ripple::sfGeneric
Definition at line 226 of file FieldNames.h.
Referenced by ripple::STAmount::bSetJson(), ripple::LedgerEntrySet::calcRawMeta(), ripple::STAmount::deserialize(), ripple::STParsedJSON::parse(), ripple::STParsedJSON::STParsedJSON(), and ripple::SerializedObject_test::testSerialization().
SField ripple::sfHash(STI_HASH256, 257,"hash")
SField ripple::sfIndex(STI_HASH256, 258,"index")
SField ripple::sfInvalid
Definition at line 226 of file FieldNames.h.
Referenced by FIELD(), ripple::SField::getField(), and ripple::STParsedJSON::parse().
SField ripple::sfLedgerEntry
Definition at line 226 of file FieldNames.h.
Referenced by ripple::STParsedJSON::parse().
SField ripple::sfTransaction
Definition at line 226 of file FieldNames.h.
Referenced by ripple::STParsedJSON::parse().
SField ripple::sfValidation
Definition at line 226 of file FieldNames.h.
bool ripple::SMN_j = SHAMapNode::ClassInit ()
Definition at line 56 of file SHAMapNode.cpp.
uint8_t ripple::SNTPQueryData[48] static
Initial value:
=
{ 0x1B, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }
Definition at line 26 of file SNTPClient.cpp.
Referenced by ripple::SNTPClientImp::resolveComplete().
const int ripple::SYSTEM_PEER_PORT = 6561
Definition at line 39 of file Config.h.
Referenced by ripple::Config::Config(), and ripple::RPCHandler::doConnect().
const int ripple::SYSTEM_WEBSOCKET_PORT = 6562
Definition at line 40 of file Config.h.
Referenced by ripple::Config::Config().
const int ripple::SYSTEM_WEBSOCKET_PUBLIC_PORT = 6563
Definition at line 41 of file Config.h.
Referenced by ripple::Config::Config().
const std::uint32_t ripple::tfAccountSetMask
Initial value:
= ~ (tfUniversal | TxFlag::requireDestTag | tfOptionalDestTag
                                             | tfRequireAuth | tfOptionalAuth
                                             | tfDisallowXRP | tfAllowXRP)
Definition at line 56 of file TxFlags.h.
Referenced by ripple::AccountSetTransactor::doApply().
const std::uint32_t ripple::tfAllowXRP = 0x00200000
Definition at line 55 of file TxFlags.h.
Referenced by ripple::AccountSetTransactor::doApply().
const std::uint32_t ripple::tfClearNoRipple = 0x00040000
Definition at line 83 of file TxFlags.h.
Referenced by ripple::TrustSetTransactor::doApply().
const std::uint32_t ripple::tfDisallowXRP = 0x00100000
Definition at line 54 of file TxFlags.h.
Referenced by ripple::AccountSetTransactor::doApply().
const std::uint32_t ripple::tfFillOrKill = 0x00040000
Definition at line 70 of file TxFlags.h.
Referenced by ripple::OfferCreateTransactor::doApply().
const std::uint32_t ripple::tfFullyCanonicalSig = 0x80000000
Definition at line 44 of file TxFlags.h.
Referenced by ripple::SerializedTransaction::checkSign(), and ripple::RPC::transactionSign().
const std::uint32_t ripple::tfImmediateOrCancel = 0x00020000
Definition at line 69 of file TxFlags.h.
Referenced by ripple::OfferCreateTransactor::doApply().
const std::uint32_t ripple::tfLimitQuality = 0x00040000
Definition at line 77 of file TxFlags.h.
Referenced by ripple::PaymentTransactor::doApply().
const std::uint32_t ripple::tfNoRippleDirect = 0x00010000
Definition at line 75 of file TxFlags.h.
Referenced by ripple::PaymentTransactor::doApply().
const std::uint32_t ripple::tfOfferCreateMask = ~ (tfUniversal | tfPassive | tfImmediateOrCancel | tfFillOrKill | tfSell)
Definition at line 72 of file TxFlags.h.
Referenced by ripple::OfferCreateTransactor::doApply().
const std::uint32_t ripple::tfOptionalAuth = 0x00080000
Definition at line 53 of file TxFlags.h.
Referenced by ripple::AccountSetTransactor::doApply().
const std::uint32_t ripple::tfOptionalDestTag = 0x00020000
Definition at line 51 of file TxFlags.h.
Referenced by ripple::AccountSetTransactor::doApply().
const std::uint32_t ripple::tfPartialPayment = 0x00020000
Definition at line 76 of file TxFlags.h.
Referenced by ripple::PaymentTransactor::doApply().
const std::uint32_t ripple::tfPassive = 0x00010000
Definition at line 68 of file TxFlags.h.
Referenced by ripple::OfferCreateTransactor::doApply().
const std::uint32_t ripple::tfPaymentMask = ~ (tfUniversal | tfPartialPayment | tfLimitQuality | tfNoRippleDirect)
Definition at line 78 of file TxFlags.h.
Referenced by ripple::PaymentTransactor::doApply().
const std::uint32_t ripple::tfRequireAuth = 0x00040000
Definition at line 52 of file TxFlags.h.
Referenced by ripple::AccountSetTransactor::doApply().
const std::uint32_t ripple::tfSell = 0x00080000
Definition at line 71 of file TxFlags.h.
Referenced by ripple::OfferCreateTransactor::doApply().
const std::uint32_t ripple::tfSetfAuth = 0x00010000
Definition at line 81 of file TxFlags.h.
Referenced by ripple::TrustSetTransactor::doApply().
const std::uint32_t ripple::tfSetNoRipple = 0x00020000
Definition at line 82 of file TxFlags.h.
Referenced by ripple::TrustSetTransactor::doApply().
const std::uint32_t ripple::tfTrustSetMask = ~ (tfUniversal | tfSetfAuth | tfSetNoRipple | tfClearNoRipple)
Definition at line 84 of file TxFlags.h.
Referenced by ripple::TrustSetTransactor::doApply().
const std::uint32_t ripple::tfUniversal = tfFullyCanonicalSig
Definition at line 45 of file TxFlags.h.
const std::uint32_t ripple::tfUniversalMask = ~ tfUniversal
Definition at line 46 of file TxFlags.h.
Referenced by ripple::WalletAddTransactor::doApply(), ripple::OfferCancelTransactor::doApply(), and ripple::RegularKeySetTransactor::doApply().
int ripple::TxnDBCount = NUMBER (TxnDBInit)
Definition at line 64 of file DBInit.cpp.
Referenced by ripple::ApplicationImp::initSqliteDb().
const char * ripple::TxnDBInit
Initial value:
=
{
    "PRAGMA synchronous=NORMAL;",
    "PRAGMA journal_mode=WAL;",
    "PRAGMA journal_size_limit=1582080;",
    "BEGIN TRANSACTION;",
    "CREATE TABLE Transactions (                \
        TransID     CHARACTER(64) PRIMARY KEY,  \
        TransType   CHARACTER(24),              \
        FromAcct    CHARACTER(35),              \
        FromSeq     BIGINT UNSIGNED,            \
        LedgerSeq   BIGINT UNSIGNED,            \
        Status      CHARACTER(1),               \
        RawTxn      BLOB,                       \
        TxnMeta     BLOB                        \
    );",
    "CREATE INDEX TxLgrIndex ON                 \
        Transactions(LedgerSeq);",
    "CREATE TABLE AccountTransactions (         \
        TransID     CHARACTER(64),              \
        Account     CHARACTER(64),              \
        LedgerSeq   BIGINT UNSIGNED,            \
        TxnSeq      INTEGER                     \
    );",
    "CREATE INDEX AcctTxIDIndex ON              \
        AccountTransactions(TransID);",
    "CREATE INDEX AcctTxIndex ON                \
        AccountTransactions(Account, LedgerSeq, TxnSeq, TransID);",
    "CREATE INDEX AcctLgrIndex ON               \
        AccountTransactions(LedgerSeq, Account, TransID);",
    "END TRANSACTION;"
}
Definition at line 23 of file DBInit.cpp.
Referenced by ripple::ApplicationImp::initSqliteDb().
const uint256 ripple::uZero static
Definition at line 26 of file SHAMapSync.cpp.
Referenced by ripple::SHAMap::addKnownNode(), ripple::SHAMap::addRootNode(), and ripple::InboundLedgersImp::gotStaleData().
const std::uint32_t ripple::vfFullyCanonicalSig = 0x80000000
Definition at line 26 of file SerializedValidation.h.
Referenced by ripple::SerializedValidation::isValid(), and ripple::SerializedValidation::sign().
int ripple::WalletDBCount = NUMBER (WalletDBInit)
Definition at line 276 of file DBInit.cpp.
Referenced by ripple::ApplicationImp::initSqliteDb().
const char * ripple::WalletDBInit
Initial value:
=
{
    "BEGIN TRANSACTION;",
    "CREATE TABLE NodeIdentity (                    \
        PublicKey       CHARACTER(53),              \
        PrivateKey      CHARACTER(52),              \
        Dh512           TEXT,                       \
        Dh1024          TEXT                        \
    );",
    "CREATE TABLE Misc (                            \
        Magic           INTEGER UNIQUE NOT NULL,    \
        ScoreUpdated    DATETIME,                   \
        FetchUpdated    DATETIME                    \
    );",
    "CREATE TABLE SeedDomains (                     \
        Domain          TEXT PRIMARY KEY NOT NULL,  \
        PublicKey       CHARACTER(53),              \
        Source          CHARACTER(1) NOT NULL,      \
        Next            DATETIME,                   \
        Scan            DATETIME,                   \
        Fetch           DATETIME,                   \
        Sha256          CHARACTER[64],              \
        Comment         TEXT                        \
    );",
    "CREATE INDEX SeedDomainNext ON SeedDomains (Next);",
    "CREATE TABLE SeedNodes (                       \
        PublicKey       CHARACTER(53) PRIMARY KEY NOT NULL,     \
        Source          CHARACTER(1) NOT NULL,      \
        Next            DATETIME,                   \
        Scan            DATETIME,                   \
        Fetch           DATETIME,                   \
        Sha256          CHARACTER[64],              \
        Comment         TEXT                        \
    );",
    "CREATE INDEX SeedNodeNext ON SeedNodes (Next);",
    "CREATE TABLE TrustedNodes (                            \
        PublicKey       CHARACTER(53) PRIMARY KEY NOT NULL, \
        Score           INTEGER DEFAULT 0 NOT NULL,         \
        Seen            DATETIME,                           \
        Comment         TEXT                                \
    );",
    "CREATE TABLE ValidatorReferrals (              \
        Validator       CHARACTER(53) NOT NULL,     \
        Entry           INTEGER NOT NULL,           \
        Referral        TEXT NOT NULL,              \
        PRIMARY KEY (Validator,Entry)               \
    );",
    "CREATE TABLE IpReferrals (                         \
        Validator       CHARACTER(53) NOT NULL,         \
        Entry           INTEGER NOT NULL,               \
        IP              TEXT NOT NULL,                  \
        Port            INTEGER NOT NULL DEFAULT -1,    \
        PRIMARY KEY (Validator,Entry)                   \
    );",
    "CREATE TABLE Features (                            \
        Hash            CHARACTER(64) PRIMARY KEY,      \
        FirstMajority   BIGINT UNSIGNED,                \
        LastMajority    BIGINT UNSIGNED                 \
    );",
    "DROP TABLE IF EXISTS PeerIps;",
    "DROP INDEX IF EXISTS;",
    "END TRANSACTION;"
}
Definition at line 121 of file DBInit.cpp.
Referenced by ripple::ApplicationImp::initSqliteDb().