rippled: ripple::ChangeTransactor Class Reference
ripple::ChangeTransactor Class Reference
#include <ChangeTransactor.h>
Public Member Functions
ChangeTransactor (SerializedTransaction const &txn, TransactionEngineParams params, TransactionEngine *engine)
TER doApply () override
TER checkSig () override
TER checkSeq () override
TER payFee () override
TER preCheck () override
Public Member Functions inherited from ripple::Transactor
TER apply ()
Private Member Functions
TER applyFeature ()
TER applyFee ()
bool mustHaveValidAccount () override
Additional Inherited Members
Static Public Member Functions inherited from ripple::Transactor
static std::unique_ptr
< Transactor > makeTransactor (SerializedTransaction const &txn, TransactionEngineParams params, TransactionEngine *engine)
Protected Member Functions inherited from ripple::Transactor
void calculateFee ()
virtual std::uint64_t calculateBaseFee ()
Transactor (const SerializedTransaction &txn, TransactionEngineParams params, TransactionEngine *engine, beast::Journal journal=beast::Journal())
Protected Attributes inherited from ripple::Transactor
SerializedTransaction const & mTxn
TransactionEngine * mEngine
TransactionEngineParams mParams
uint160 mTxnAccountID
STAmount mFeeDue
STAmount mPriorBalance
STAmount mSourceBalance
SLE::pointer mTxnAccount
bool mHasAuthKey
bool mSigMaster
RippleAddress mSigningPubKey
beast::Journal m_journal
Detailed Description
Definition at line 34 of file ChangeTransactor.h.
Constructor & Destructor Documentation
ripple::ChangeTransactor::ChangeTransactor (SerializedTransaction const & txn, TransactionEngineParams params, TransactionEngine * engine) inline
Definition at line 38 of file ChangeTransactor.h.
         : Transactor (
             txn,
             params,
             engine,
             LogPartition::getJournal <ChangeTransactorLog> ())
     {
     }
Member Function Documentation
TER ripple::ChangeTransactor::applyFeature () private
Definition at line 92 of file ChangeTransactor.cpp.
References ripple::FeatureTable::enable(), ripple::TransactionEngine::entryCache(), ripple::TransactionEngine::entryCreate(), ripple::TransactionEngine::entryModify(), ripple::getApp(), ripple::Application::getFeatureTable(), ripple::STObject::getFieldH256(), ripple::Ledger::getLedgerFeatureIndex(), ripple::Application::getOPs(), ripple::ltFEATURES, ripple::Transactor::mEngine, ripple::Transactor::mTxn, ripple::NetworkOPs::setFeatureBlocked(), ripple::tefALREADY, and ripple::tesSUCCESS.
Referenced by doApply().
 {
     uint256 feature (mTxn.getFieldH256 (sfFeature));
     SLE::pointer featureObject (mEngine->entryCache (
         ltFEATURES, Ledger::getLedgerFeatureIndex ()));
     if (!featureObject)
         featureObject = mEngine->entryCreate (
             ltFEATURES, Ledger::getLedgerFeatureIndex ());
     STVector256 features (featureObject->getFieldV256 (sfFeatures));
     if (features.hasValue (feature))
         return tefALREADY;
     features.addValue (feature);
     featureObject->setFieldV256 (sfFeatures, features);
     mEngine->entryModify (featureObject);
     getApp().getFeatureTable ().enable (feature);
     if (!getApp().getFeatureTable ().isSupported (feature))
         getApp().getOPs ().setFeatureBlocked ();
     return tesSUCCESS;
 }
TER ripple::ChangeTransactor::applyFee () private
Definition at line 120 of file ChangeTransactor.cpp.
References ripple::TransactionEngine::entryCache(), ripple::TransactionEngine::entryCreate(), ripple::TransactionEngine::entryModify(), ripple::STObject::getFieldU32(), ripple::STObject::getFieldU64(), ripple::Ledger::getLedgerFeeIndex(), ripple::ltFEE_SETTINGS, ripple::Transactor::m_journal, ripple::Transactor::mEngine, ripple::Transactor::mTxn, ripple::tesSUCCESS, beast::Journal::trace, and beast::Journal::warning.
Referenced by doApply().
 {
     SLE::pointer feeObject = mEngine->entryCache (
         ltFEE_SETTINGS, Ledger::getLedgerFeeIndex ());
     if (!feeObject)
         feeObject = mEngine->entryCreate (
             ltFEE_SETTINGS, Ledger::getLedgerFeeIndex ());
     m_journal.trace <<
         "Previous fee object: " << feeObject->getJson (0);
     feeObject->setFieldU64 (
         sfBaseFee, mTxn.getFieldU64 (sfBaseFee));
     feeObject->setFieldU32 (
         sfReferenceFeeUnits, mTxn.getFieldU32 (sfReferenceFeeUnits));
     feeObject->setFieldU32 (
         sfReserveBase, mTxn.getFieldU32 (sfReserveBase));
     feeObject->setFieldU32 (
         sfReserveIncrement, mTxn.getFieldU32 (sfReserveIncrement));
     mEngine->entryModify (feeObject);
     m_journal.trace <<
         "New fee object: " << feeObject->getJson (0);
     m_journal.warning << "Fees have been changed";
     return tesSUCCESS;
 }
TER ripple::ChangeTransactor::checkSeq () override virtual
Reimplemented from ripple::Transactor.
Definition at line 50 of file ChangeTransactor.cpp.
References ripple::SerializedTransaction::getSequence(), ripple::STObject::isFieldPresent(), ripple::Transactor::m_journal, ripple::Transactor::mTxn, ripple::temBAD_SEQUENCE, ripple::tesSUCCESS, and beast::Journal::warning.
 {
     if ((mTxn.getSequence () != 0) || mTxn.isFieldPresent (sfPreviousTxnID))
     {
         m_journal.warning << "Bad sequence";
         return temBAD_SEQUENCE;
     }
     return tesSUCCESS;
 }
TER ripple::ChangeTransactor::checkSig () override virtual
Reimplemented from ripple::Transactor.
Definition at line 33 of file ChangeTransactor.cpp.
References ripple::STObject::getFieldAccount160(), ripple::SerializedTransaction::getSignature(), ripple::SerializedTransaction::getSigningPubKey(), ripple::base_uint< BITS >::isNonZero(), ripple::Transactor::m_journal, ripple::Transactor::mTxn, ripple::temBAD_SIGNATURE, ripple::temBAD_SRC_ACCOUNT, ripple::tesSUCCESS, and beast::Journal::warning.
 {
     if (mTxn.getFieldAccount160 (sfAccount).isNonZero ())
     {
         m_journal.warning << "Bad source account";
         return temBAD_SRC_ACCOUNT;
     }
     if (!mTxn.getSigningPubKey ().empty () || !mTxn.getSignature ().empty ())
     {
         m_journal.warning << "Bad signature";
         return temBAD_SIGNATURE;
     }
     return tesSUCCESS;
 }
TER ripple::ChangeTransactor::doApply () override virtual
Implements ripple::Transactor.
Definition at line 22 of file ChangeTransactor.cpp.
References applyFeature(), applyFee(), ripple::SerializedTransaction::getTxnType(), ripple::Transactor::mTxn, ripple::temUNKNOWN, ripple::ttFEATURE, and ripple::ttFEE.
 {
     if (mTxn.getTxnType () == ttFEATURE)
         return applyFeature ();
     if (mTxn.getTxnType () == ttFEE)
         return applyFee ();
     return temUNKNOWN;
 }
bool ripple::ChangeTransactor::mustHaveValidAccount () inline override private virtual
Reimplemented from ripple::Transactor.
Definition at line 61 of file ChangeTransactor.h.
     {
         return false;
     }
TER ripple::ChangeTransactor::payFee () override virtual
Reimplemented from ripple::Transactor.
Definition at line 61 of file ChangeTransactor.cpp.
References ripple::SerializedTransaction::getTransactionFee(), ripple::Transactor::m_journal, ripple::Transactor::mTxn, ripple::temBAD_FEE, ripple::tesSUCCESS, and beast::Journal::warning.
 {
     if (mTxn.getTransactionFee () != STAmount ())
     {
         m_journal.warning << "Non-zero fee";
         return temBAD_FEE;
     }
     return tesSUCCESS;
 }
TER ripple::ChangeTransactor::preCheck () override virtual
Reimplemented from ripple::Transactor.
Definition at line 72 of file ChangeTransactor.cpp.
References ripple::RippleAddress::getAccountID(), ripple::SerializedTransaction::getSourceAccount(), ripple::is_bit_set(), ripple::base_uint< BITS >::isNonZero(), ripple::Transactor::m_journal, ripple::Transactor::mParams, ripple::Transactor::mTxn, ripple::Transactor::mTxnAccountID, ripple::tapOPEN_LEDGER, ripple::temBAD_SRC_ACCOUNT, ripple::temINVALID, ripple::tesSUCCESS, and beast::Journal::warning.
 {
     mTxnAccountID   = mTxn.getSourceAccount ().getAccountID ();
     if (mTxnAccountID.isNonZero ())
     {
         m_journal.warning << "Bad source id";
         return temBAD_SRC_ACCOUNT;
     }
     if (is_bit_set (mParams, tapOPEN_LEDGER))
     {
         m_journal.warning << "Change transaction against open ledger";
         return temINVALID;
     }
     return tesSUCCESS;
 }
The documentation for this class was generated from the following files:
rippled/src/ripple_app/transactors/ChangeTransactor.h
rippled/src/ripple_app/transactors/ChangeTransactor.cpp