rippled: beast::asio::HTTPClient_test Class Reference
beast::asio::HTTPClient_test Class Reference
Classes
class IoServiceThread
Public Types
typedef boost::system::error_code error_code
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Member Functions
void print (HTTPMessage const &m)
void print (HTTPClientBase::error_type error, HTTPClientBase::value_type const &response)
void handle_get (HTTPClientBase::result_type result)
void testSync (String const &s, double timeoutSeconds)
void testAsync (String const &s, double timeoutSeconds)
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Additional Inherited Members
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 552 of file HTTPClientType.cpp.
Member Typedef Documentation
typedef boost::system::error_code beast::asio::HTTPClient_test::error_code
Definition at line 555 of file HTTPClientType.cpp.
Member Function Documentation
void beast::asio::HTTPClient_test::handle_get (HTTPClientBase::result_type result) inline
Definition at line 636 of file HTTPClientType.cpp.
References print().
Referenced by testAsync().
     {
         print (result.first, result.second);
     }
void beast::asio::HTTPClient_test::print (HTTPMessage const & m) inline
Definition at line 599 of file HTTPClientType.cpp.
References ripple::f, beast::HTTPMessage::headers(), beast::unit_test::suite::log, and beast::HTTPHeaders::size().
Referenced by handle_get(), print(), and testSync().
     {
         for (int i = 0; i < m.headers().size(); ++i)
         {
             HTTPField const f (m.headers()[i]);
             std::stringstream ss;
             log <<
                 "[ '" << f.name() <<
                 "' , '" << f.value() + "' ]";
         }
     }
void beast::asio::HTTPClient_test::print (HTTPClientBase::error_type error, HTTPClientBase::value_type const & response) inline
Definition at line 611 of file HTTPClientType.cpp.
References beast::SharedPtr< T >::empty(), beast::String::fromNumber(), beast::unit_test::suite::log, and print().
     {
         if (error != 0)
         {
             log <<
                 "HTTPClient error: '" + error.message() << "'";
         }
         else if (! response.empty ())
         {
             log <<
                 "Status: " <<
                 String::fromNumber (response->status()).toStdString();
             print (*response);
         }
         else
         {
             log <<
                 "HTTPClient: no response";
         }
     }
void beast::asio::HTTPClient_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 668 of file HTTPClientType.cpp.
References beast::unit_test::suite::pass(), testAsync(), and testSync().
     {
         testSync (
             "http://www.boost.org/doc/libs/1_54_0/doc/html/boost_asio/reference.html",
             5);
         testAsync (
             "http://www.boost.org/doc/libs/1_54_0/doc/html/boost_asio/reference.html",
             5);
         testAsync (
             "https://www.boost.org/doc/libs/1_54_0/doc/html/boost_asio/reference.html",
             5);
         pass ();
     }
void beast::asio::HTTPClient_test::testAsync (String const & s, double timeoutSeconds) inline
Definition at line 652 of file HTTPClientType.cpp.
References beast::asio::HTTPClient_test::IoServiceThread::get_io_service(), handle_get(), beast::asio::HTTPClient_test::IoServiceThread::join(), beast::asio::HTTPClientBase::New(), beast::asio::HTTPClient_test::IoServiceThread::start(), and beast::ParsedURL::url().
Referenced by run().
     {
         IoServiceThread t;
         std::unique_ptr <HTTPClientBase> client (
             HTTPClientBase::New (Journal(), timeoutSeconds));
         client->async_get (t.get_io_service (), ParsedURL (s).url (),
             beast::bind (&HTTPClient_test::handle_get, this,
                 beast::_1));
         t.start ();
         t.join ();
     }
void beast::asio::HTTPClient_test::testSync (String const & s, double timeoutSeconds) inline
Definition at line 641 of file HTTPClientType.cpp.
References beast::asio::HTTPClientBase::New(), and print().
Referenced by run().
     {
         std::unique_ptr <HTTPClientBase> client (
             HTTPClientBase::New (Journal(), timeoutSeconds));
         HTTPClientBase::result_type const& result (
             client->get (ParsedURL (s).url ()));
         print (result.first, result.second);
     }
The documentation for this class was generated from the following file:
rippled/src/beast/modules/beast_asio/http/HTTPClientType.cpp