rippled: beast::ComSmartPtr< ComClass > Class Template Reference
beast::ComSmartPtr< ComClass > Class Template Reference
#include <win32_ComSmartPtr.h>
Public Member Functions
ComSmartPtr () throw ()
ComSmartPtr (ComClass *const obj)
ComSmartPtr (const ComSmartPtr< ComClass > &other)
~ComSmartPtr ()
operator ComClass * () const throw ()
ComClass & operator* () const throw ()
ComClass * operator-> () const throw ()
ComSmartPtr & operator= (ComClass *const newP)
ComSmartPtr & operator= (const ComSmartPtr< ComClass > &newP)
ComClass ** resetAndGetPointerAddress ()
HRESULT CoCreateInstance (REFCLSID classUUID, DWORD dwClsContext=CLSCTX_INPROC_SERVER)
template<class OtherComClass >
HRESULT QueryInterface (REFCLSID classUUID, ComSmartPtr< OtherComClass > &destObject) const
template<class OtherComClass >
HRESULT QueryInterface (ComSmartPtr< OtherComClass > &destObject) const
Private Member Functions
void release ()
ComClass ** operator& () throw ()
Private Attributes
ComClass * p
Detailed Description
template<class ComClass>
class beast::ComSmartPtr< ComClass >
A simple COM smart pointer.
Definition at line 57 of file win32_ComSmartPtr.h.
Constructor & Destructor Documentation
template<class ComClass> beast::ComSmartPtr< ComClass >::ComSmartPtr () throw () inline
Definition at line 60 of file win32_ComSmartPtr.h.
 : p (0)                                  {}
template<class ComClass> beast::ComSmartPtr< ComClass >::ComSmartPtr (ComClass *const obj) inline
Definition at line 61 of file win32_ComSmartPtr.h.
References beast::ComSmartPtr< ComClass >::p.
 : p (obj)                    { if (p) p->AddRef(); }
template<class ComClass> beast::ComSmartPtr< ComClass >::ComSmartPtr (const ComSmartPtr< ComClass > & other) inline
Definition at line 62 of file win32_ComSmartPtr.h.
References beast::ComSmartPtr< ComClass >::p.
 : p (other.p) { if (p) p->AddRef(); }
template<class ComClass> beast::ComSmartPtr< ComClass >::~ComSmartPtr () inline
Definition at line 63 of file win32_ComSmartPtr.h.
References beast::ComSmartPtr< ComClass >::release().
 { release(); }
Member Function Documentation
template<class ComClass> HRESULT beast::ComSmartPtr< ComClass >::CoCreateInstance (REFCLSID classUUID, DWORD dwClsContext = CLSCTX_INPROC_SERVER) inline
Definition at line 87 of file win32_ComSmartPtr.h.
References __uuidof, bassert, and beast::ComSmartPtr< ComClass >::resetAndGetPointerAddress().
     {
         HRESULT hr = ::CoCreateInstance (classUUID, 0, dwClsContext, __uuidof (ComClass), (void**) resetAndGetPointerAddress());
         bassert (hr != CO_E_NOTINITIALIZED); // You haven't called CoInitialize for the current thread!
         return hr;
     }
template<class ComClass> beast::ComSmartPtr< ComClass >::operator ComClass * () const throw () inline
Definition at line 65 of file win32_ComSmartPtr.h.
References beast::ComSmartPtr< ComClass >::p.
 { return p; }
template<class ComClass> ComClass** beast::ComSmartPtr< ComClass >::operator& () throw () private
template<class ComClass> ComClass& beast::ComSmartPtr< ComClass >::operator* () const throw () inline
Definition at line 66 of file win32_ComSmartPtr.h.
References beast::ComSmartPtr< ComClass >::p.
 { return *p; }
template<class ComClass> ComClass* beast::ComSmartPtr< ComClass >::operator-> () const throw () inline
Definition at line 67 of file win32_ComSmartPtr.h.
References beast::ComSmartPtr< ComClass >::p.
 { return p; }
template<class ComClass> ComSmartPtr& beast::ComSmartPtr< ComClass >::operator= (ComClass *const newP) inline
Definition at line 69 of file win32_ComSmartPtr.h.
References beast::ComSmartPtr< ComClass >::p, and beast::ComSmartPtr< ComClass >::release().
Referenced by beast::ComSmartPtr< ComClass >::operator=().
     {
         if (newP != 0)  newP->AddRef();
         release();
         p = newP;
         return *this;
     }
template<class ComClass> ComSmartPtr& beast::ComSmartPtr< ComClass >::operator= (const ComSmartPtr< ComClass > & newP) inline
Definition at line 77 of file win32_ComSmartPtr.h.
References beast::ComSmartPtr< ComClass >::operator=(), and beast::ComSmartPtr< ComClass >::p.
 { return operator= (newP.p); }
template<class ComClass> template<class OtherComClass > HRESULT beast::ComSmartPtr< ComClass >::QueryInterface (REFCLSID classUUID, ComSmartPtr< OtherComClass > & destObject) const inline
Definition at line 95 of file win32_ComSmartPtr.h.
References beast::ComSmartPtr< ComClass >::p, and beast::ComSmartPtr< ComClass >::resetAndGetPointerAddress().
Referenced by beast::ComSmartPtr< ComClass >::QueryInterface().
     {
         if (p == 0)
             return E_POINTER;
         return p->QueryInterface (classUUID, (void**) destObject.resetAndGetPointerAddress());
     }
template<class ComClass> template<class OtherComClass > HRESULT beast::ComSmartPtr< ComClass >::QueryInterface (ComSmartPtr< OtherComClass > & destObject) const inline
Definition at line 104 of file win32_ComSmartPtr.h.
References __uuidof, and beast::ComSmartPtr< ComClass >::QueryInterface().
     {
         return this->QueryInterface (__uuidof (OtherComClass), destObject);
     }
template<class ComClass> void beast::ComSmartPtr< ComClass >::release () inline private
Definition at line 112 of file win32_ComSmartPtr.h.
References beast::ComSmartPtr< ComClass >::p.
Referenced by beast::ComSmartPtr< ComClass >::operator=(), beast::ComSmartPtr< ComClass >::resetAndGetPointerAddress(), and beast::ComSmartPtr< ComClass >::~ComSmartPtr().
 { if (p != 0) p->Release(); }
template<class ComClass> ComClass** beast::ComSmartPtr< ComClass >::resetAndGetPointerAddress () inline
Definition at line 80 of file win32_ComSmartPtr.h.
References beast::ComSmartPtr< ComClass >::p, and beast::ComSmartPtr< ComClass >::release().
Referenced by beast::ComSmartPtr< ComClass >::CoCreateInstance(), and beast::ComSmartPtr< ComClass >::QueryInterface().
     {
         release();
         p = 0;
         return &p;
     }
Member Data Documentation
template<class ComClass> ComClass* beast::ComSmartPtr< ComClass >::p private
Definition at line 110 of file win32_ComSmartPtr.h.
Referenced by beast::ComSmartPtr< ComClass >::ComSmartPtr(), beast::ComSmartPtr< ComClass >::operator ComClass *(), beast::ComSmartPtr< ComClass >::operator*(), beast::ComSmartPtr< ComClass >::operator->(), beast::ComSmartPtr< ComClass >::operator=(), beast::ComSmartPtr< ComClass >::QueryInterface(), beast::ComSmartPtr< ComClass >::release(), and beast::ComSmartPtr< ComClass >::resetAndGetPointerAddress().
The documentation for this class was generated from the following file:
rippled/src/beast/modules/beast_core/native/win32_ComSmartPtr.h