rippled: ripple::ProofOfWorkFactory Class Reference
ripple::ProofOfWorkFactory Class Reference abstract
#include <ProofOfWorkFactory.h>
Public Types
enum { kMaxDifficulty = 30 }
Public Member Functions
virtual ~ProofOfWorkFactory ()
virtual ProofOfWork getProof ()=0
virtual PowResult checkProof (const std::string &token, uint256 const &solution)=0
virtual std::uint64_t getDifficulty ()=0
virtual void setDifficulty (int i)=0
virtual void loadHigh ()=0
virtual void loadLow ()=0
virtual void sweep ()=0
virtual uint256 const & getSecret () const =0
virtual void setSecret (uint256 const &secret)=0
Static Public Member Functions
static ProofOfWorkFactory * New ()
Detailed Description
Definition at line 28 of file ProofOfWorkFactory.h.
Member Enumeration Documentation
anonymous enum
Enumerator
kMaxDifficulty
Definition at line 31 of file ProofOfWorkFactory.h.
     {
         kMaxDifficulty = 30,
     };
Constructor & Destructor Documentation
virtual ripple::ProofOfWorkFactory::~ProofOfWorkFactory () inline virtual
Definition at line 38 of file ProofOfWorkFactory.h.
 { }
Member Function Documentation
virtual PowResult ripple::ProofOfWorkFactory::checkProof (const std::string & token, uint256 const & solution) pure virtual
Implemented in ripple::ProofOfWorkFactoryImp.
Referenced by ripple::RPCHandler::doProofVerify(), and ripple::PeerImp::recvProofWork().
virtual std::uint64_t ripple::ProofOfWorkFactory::getDifficulty () pure virtual
Implemented in ripple::ProofOfWorkFactoryImp.
virtual ProofOfWork ripple::ProofOfWorkFactory::getProof () pure virtual
Implemented in ripple::ProofOfWorkFactoryImp.
Referenced by ripple::RPCHandler::doProofCreate().
virtual uint256 const& ripple::ProofOfWorkFactory::getSecret () const pure virtual
Implemented in ripple::ProofOfWorkFactoryImp.
virtual void ripple::ProofOfWorkFactory::loadHigh () pure virtual
Implemented in ripple::ProofOfWorkFactoryImp.
virtual void ripple::ProofOfWorkFactory::loadLow () pure virtual
Implemented in ripple::ProofOfWorkFactoryImp.
ProofOfWorkFactory * ripple::ProofOfWorkFactory::New () static
Definition at line 355 of file ProofOfWorkFactory.cpp.
Referenced by ripple::RPCHandler::doProofCreate(), and ripple::RPCHandler::doProofVerify().
 {
     return new ProofOfWorkFactoryImp;
 }
virtual void ripple::ProofOfWorkFactory::setDifficulty (int i) pure virtual
Implemented in ripple::ProofOfWorkFactoryImp.
virtual void ripple::ProofOfWorkFactory::setSecret (uint256 const & secret) pure virtual
Implemented in ripple::ProofOfWorkFactoryImp.
virtual void ripple::ProofOfWorkFactory::sweep () pure virtual
Implemented in ripple::ProofOfWorkFactoryImp.
The documentation for this class was generated from the following files:
rippled/src/ripple_app/misc/ProofOfWorkFactory.h
rippled/src/ripple_app/misc/ProofOfWorkFactory.cpp