rippled: beast::unit_test::suite Class Reference
beast::unit_test::suite Class Reference abstract
#include <suite.h>
Inherited by beast::abstract_clock_test, beast::aged_associative_container_test_base, beast::asio::bind_handler_test, beast::asio::boost_bind_test, beast::asio::HTTPClient_test, beast::asio::integer_sequence_test, beast::asio::TestPeer_test, beast::asio::wrap_handler_test, beast::Atomic_test, beast::basic_abstract_ostream_test, beast::basic_seconds_clock_test, beast::bassert_test, beast::BinaryEncoding_test, beast::buffer_view_test, beast::Debug_test, beast::empty_base_optimization_test, beast::enable_wait_for_async_test, beast::FatalError_test, beast::File_test, beast::hardened_hash_sha256_test, beast::hardened_hash_test, beast::hash_append_test, beast::IP::IPEndpoint_test, beast::LexicalCast_test, beast::ParsedURL_test, beast::PropertyStream_test, beast::Random_test, beast::RandomAccessFile_test, beast::SemanticVersion_test, beast::ServiceQueue_test, beast::ServiceQueue_timing_test, beast::shared_handler_test, beast::tagged_integer_test, beast::unit_test::detail::print_test, beast::UnsignedInteger_test, beast::Workers_test, beast::Zero_test, ripple::BuildInfo_test, ripple::CKey_test, ripple::core::OfferStream_test, ripple::core::Quality_test, ripple::ECDSACanonical_test, ripple::FatalErrorReporter_test, ripple::FetchPack_test, ripple::JsonCpp_test, ripple::KeyCache_test, ripple::Ledger_test, ripple::LoadFeeTrack_test, ripple::MultiSocket_test, ripple::NodeStore::TestBase, ripple::PeerFinder::Livecache_test, ripple::ProofOfWork_test, ripple::RangeSet_test, ripple::Resource::Manager_test, ripple::RippleAddress_test, ripple::RippleAsset_test, ripple::RippleIdentifier_test, ripple::RPC::JSONRPC_test, ripple::SerializedObject_test, ripple::SerializedTransaction_test, ripple::Serializer_test, ripple::SHAMap_test, ripple::SHAMapSync_test, ripple::STAmount_test, ripple::StringUtilities_test, ripple::TaggedCache_test, ripple::TestOverlay::Network1_test, ripple::TestOverlay::Network2_test, ripple::Validators::Logic_test, and ripple::version::CheckLibraryVersions_test.
Classes
struct abort_exception
class log_t
Public Types
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Member Functions
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Public Attributes
log_t log
Private Member Functions
virtual void run ()=0
Private Attributes
bool m_abort = false
Detailed Description
A testsuite class. Derived classes execute a series of testcases, where each testcase is a series of pass/fail tests. To provide a unit test using this class, derive from it and use the BEAST_DEFINE_UNIT_TEST macro in a translation unit.
Definition at line 37 of file suite.h.
Member Typedef Documentation
typedef abstract_ostream::scoped_stream_type beast::unit_test::suite::scoped_stream
Type for scoped stream logging. To use this type, declare a local variable of the type on the stack in derived class member function and construct it from log.stream();
scoped_stream ss (log.stream();
ss << "Hello" << std::endl;
ss << "world" << std::endl;
Streams constructed in this fashion will not have the line ending automatically appended.
Thread safety:
The scoped_stream may only be used by one thread.
Multiline output sent to the stream will be atomically
written to the underlying abstract_Ostream
Definition at line 111 of file suite.h.
Member Enumeration Documentation
enum beast::unit_test::suite::abort_t
Enumerator
no_abort_on_fail
abort_on_fail
Definition at line 146 of file suite.h.
     {
         no_abort_on_fail,
         abort_on_fail
     };
Member Function Documentation
template<class Condition > bool beast::unit_test::suite::expect (Condition shouldBeTrue, std::string const & reason = "") inline
Evaluate a test condition. The condition is passed as a template argument instead of bool so that implicit conversion is not required. The reason argument is logged if the condition is false.
Returns
true if the test condition indicates success.
Definition at line 176 of file suite.h.
References fail(), and pass().
Referenced by ripple::core::Quality_test::ceil_in(), ripple::core::Quality_test::ceil_out(), beast::buffer_view_test::check(), beast::aged_associative_container_test_base::checkContentsRefRef(), beast::buffer_view_test::checkEmpty(), beast::SemanticVersion_test::checkLessInternal(), beast::aged_associative_container_test_base::checkMapContents(), beast::SemanticVersion_test::checkPass(), beast::aged_associative_container_test_base::checkUnorderedContentsRefRef(), beast::ParsedURL_test::checkURL(), beast::SemanticVersion_test::checkValues(), ripple::ECDSACanonical_test::convertNonCanonical(), beast::Zero_test::expect_same(), beast::File_test::expectEquals(), ripple::NodeStore::TestBase::fetchCopyOfBatch(), ripple::FetchPack_test::on_fetch(), beast::RandomAccessFile_test::readRecords(), beast::asio::PeerTest::Result::report(), ripple::KeyCache_test::run(), ripple::LoadFeeTrack_test::run(), ripple::TaggedCache_test::run(), beast::asio::integer_sequence_test::run(), beast::Atomic_test::run(), beast::empty_base_optimization_test::run(), beast::tagged_integer_test::run(), beast::Random_test::run(), beast::shared_handler_test::run(), beast::asio::wrap_handler_test::run(), ripple::ProofOfWork_test::run(), ripple::Serializer_test::run(), ripple::RippleAddress_test::run(), beast::File_test::run(), ripple::RippleIdentifier_test::run(), ripple::Ledger_test::run(), beast::IP::IPEndpoint_test::shouldParseV4(), beast::IP::IPEndpoint_test::shouldPass(), beast::UnsignedInteger_test::test(), beast::enable_wait_for_async_test::test(), beast::Zero_test::test_adl(), ripple::JsonCpp_test::test_copy(), ripple::JsonCpp_test::test_move(), ripple::core::Quality_test::test_raw(), beast::IP::IPEndpoint_test::testAddress(), beast::IP::IPEndpoint_test::testAddressV4(), beast::IP::IPEndpoint_test::testAddressV4Proxy(), ripple::RippleAsset_test::testAssetMap(), ripple::RippleAsset_test::testAssetSet(), ripple::RippleAsset_test::testAssetType(), beast::buffer_view_test::testAssign(), ripple::RPC::JSONRPC_test::testAutoFillFees(), ripple::NodeStore::Backend_test::testBackend(), beast::BinaryEncoding_test::testBase16(), beast::BinaryEncoding_test::testBase64Bytes(), ripple::NodeStore::NodeStoreBasic_test::testBatches(), ripple::NodeStore::NodeStoreBasic_test::testBlobs(), ripple::RippleAsset_test::testBook(), ripple::RippleAsset_test::testBookMap(), ripple::RippleAsset_test::testBookSet(), beast::aged_associative_container_test_base::testChronological(), beast::aged_associative_container_test_base::testCompare(), beast::buffer_view_test::testConstruct(), beast::aged_associative_container_test_base::testCopyMove(), ripple::Resource::Manager_test::testDrop(), beast::BinaryEncoding_test::testEncode(), beast::IP::IPEndpoint_test::testEndpoint(), beast::RandomAccessFile_test::testFile(), beast::Atomic_test::testFloat(), ripple::NodeStore::NodeStoreDatabase_test::testImport(), beast::Atomic_test::testInteger(), beast::LexicalCast_test::testInteger(), ripple::Validators::Logic_test::testLogic(), ripple::ECDSACanonical_test::testMalformedSignatures(), ripple::RangeSet_test::testMembership(), ripple::NodeStore::NodeStoreDatabase_test::testNodeStore(), ripple::SerializedObject_test::testParseJSONArray(), ripple::SerializedObject_test::testParseJSONArrayWithInvalidChildrenObjects(), ripple::RangeSet_test::testPrevMissing(), ripple::ECDSACanonical_test::testStrictlyCanonicalSignatures(), ripple::StringUtilities_test::testUnHexFailure(), ripple::StringUtilities_test::testUnHexSuccess(), ripple::RippleAsset_test::testUnsigned(), ripple::ECDSACanonical_test::testValidSignatures(), and beast::RandomAccessFile_test::writeRecords().
     {
         if (shouldBeTrue)
             pass();
         else
             fail (reason);
         return shouldBeTrue;
     }
void beast::unit_test::suite::fail (std::string const & reason = "") inline
Record a failure.
Definition at line 207 of file suite.h.
References beast::unit_test::runner::fail(), log, and m_abort.
Referenced by ldb_test.LDBTestCase::assertRunFAILFull(), beast::buffer_view_test::checkBadIndex(), beast::aged_associative_container_test_base::checkMapContents(), expect(), ripple::STAmount_test::mulTest(), operator()(), ripple::STAmount_test::roundTest(), beast::Debug_test::run(), ripple::SerializedTransaction_test::run(), ripple::SHAMapSync_test::run(), ripple::STAmount_test::testArithmetic(), ripple::STAmount_test::testCustomCurrency(), ripple::Resource::Manager_test::testDrop(), ripple::SerializedObject_test::testParseJSONArray(), ripple::SerializedObject_test::testSerialization(), and unexpected().
     {
         log->fail (reason);
         if (m_abort)
             throw abort_exception();
     }
void beast::unit_test::suite::operator() (runner & r) inline
Invokes the test using the specified runner. Data members are set up here instead of the constructor as a convenience to writing the derived class to avoid repetition of forwarded constructor arguments to the base. Normally this is called by the framework for you.
Definition at line 123 of file suite.h.
References fail(), log, beast::unit_test::suite::log_t::m_runner, and run().
Referenced by beast::enable_wait_for_async_test::test().
     {
         log.m_runner = &r;
         try
         {
             run();
         }
         catch (abort_exception const&)
         {
             // ends the suite
         }
         catch (std::exception const& e)
         {
             fail (std::string ("unhandled exception: ") +
                 std::string (e.what()));
         }
         catch (...)
         {
             fail ("unhandled exception");
         }
     }
void beast::unit_test::suite::pass () inline
Record a successful test condition.
Definition at line 200 of file suite.h.
References log, and beast::unit_test::runner::pass().
Referenced by beast::hardened_hash_test::check(), beast::hardened_hash_test::check_container(), beast::buffer_view_test::checkBadIndex(), expect(), ripple::STAmount_test::mulTest(), beast::hash_append_test::report(), ripple::STAmount_test::roundTest(), beast::bassert_test::run(), beast::basic_seconds_clock_test::run(), beast::asio::bind_handler_test::run(), beast::asio::integer_sequence_test::run(), beast::basic_abstract_ostream_test::run(), beast::unit_test::detail::print_test::run(), beast::abstract_clock_test::run(), ripple::FetchPack_test::run(), beast::asio::boost_bind_test::run(), beast::empty_base_optimization_test::run(), ripple::SerializedTransaction_test::run(), beast::asio::HTTPClient_test::run(), ripple::SHAMapSync_test::run(), ripple::core::OfferStream_test::test(), ripple::TestOverlay::Network2_test::test1(), ripple::JsonCpp_test::test_copy(), ripple::JsonCpp_test::test_move(), ripple::STAmount_test::testArithmetic(), ripple::JsonCpp_test::testBadJson(), ripple::Resource::Manager_test::testCharges(), beast::buffer_view_test::testCoerce(), beast::aged_associative_container_test_base::testConstructInitList(), ripple::TestOverlay::Network1_test::testCreation(), ripple::STAmount_test::testCustomCurrency(), ripple::Resource::Manager_test::testDrop(), ripple::PeerFinder::Livecache_test::testFetch(), ripple::Resource::Manager_test::testImport(), ripple::Resource::Manager_test::testImports(), ripple::Validators::Logic_test::testLogic(), beast::aged_associative_container_test_base::testObservers(), ripple::SerializedObject_test::testSerialization(), beast::hardened_hash_sha256_test::testSHA256(), beast::ServiceQueue_timing_test::testThreads(), beast::ServiceQueue_test::testThreads(), and unexpected().
     {
         log->pass();
     }
virtual void beast::unit_test::suite::run () private pure virtual
Runs the suite.
Implemented in ripple::Ledger_test, ripple::STAmount_test, beast::aged_unordered_multimap_test, beast::aged_unordered_multiset_test, beast::aged_unordered_map_test, beast::aged_unordered_set_test, beast::aged_multimap_test, beast::aged_multiset_test, beast::aged_map_test, beast::aged_set_test, ripple::SHAMap_test, ripple::SerializedObject_test, ripple::RippleIdentifier_test, beast::File_test, ripple::RippleAddress_test, ripple::SHAMapSync_test, beast::PropertyStream_test, ripple::Serializer_test, beast::asio::HTTPClient_test, ripple::ECDSACanonical_test, ripple::TestOverlay::Network2_test, ripple::RPC::JSONRPC_test, beast::SemanticVersion_test, beast::hash_append_test, ripple::RippleAsset_test, ripple::StringUtilities_test, beast::BinaryEncoding_test, ripple::SerializedTransaction_test, ripple::ProofOfWork_test, beast::Debug_test, ripple::RangeSet_test, beast::buffer_view_test, beast::hardened_hash_sha256_test, ripple::MultiSocket_test, beast::Workers_test, beast::ServiceQueue_test, beast::RandomAccessFile_test, beast::hardened_hash_test, beast::IP::IPEndpoint_test, ripple::core::Quality_test, ripple::Resource::Manager_test, ripple::BuildInfo_test, beast::asio::wrap_handler_test, ripple::NodeStore::NodeStoreDatabase_test, ripple::Validators::Logic_test, beast::ServiceQueue_timing_test, beast::shared_handler_test, ripple::TestOverlay::Network1_test, ripple::version::CheckLibraryVersions_test, beast::Zero_test, beast::Random_test, beast::FatalError_test, ripple::NodeStore::NodeStoreTiming_test, beast::LexicalCast_test, beast::tagged_integer_test, beast::enable_wait_for_async_test, beast::empty_base_optimization_test, ripple::NodeStore::Backend_test, beast::asio::boost_bind_test, beast::Atomic_test, ripple::JsonCpp_test, ripple::FetchPack_test, ripple::NodeStore::NodeStoreBasic_test, beast::abstract_clock_test, beast::UnsignedInteger_test, beast::unit_test::detail::print_test, ripple::PeerFinder::Livecache_test, beast::basic_abstract_ostream_test, beast::asio::integer_sequence_test, ripple::FatalErrorReporter_test, beast::ParsedURL_test, beast::asio::bind_handler_test, ripple::TaggedCache_test, ripple::core::OfferStream_test, beast::asio::TestPeer_test, ripple::CKey_test, ripple::LoadFeeTrack_test, beast::basic_seconds_clock_test, beast::bassert_test, and ripple::KeyCache_test.
Referenced by operator()().
void beast::unit_test::suite::testcase (std::string const & name, abort_t abort = no_abort_on_fail) inline
Open a new testcase. A testcase is a series of evaluated test conditions. A test suite may have multiple test cases. A test is associated with the last opened testcase. When the test first runs, a default unnamed case is opened. Tests with only one case may omit the call to testcase.
Parameters
abort If true, the suite will be stopped on first failure.
Definition at line 161 of file suite.h.
References abort_on_fail, log, m_abort, and beast::unit_test::runner::testcase().
Referenced by beast::asio::PeerTest::Results::report(), beast::Atomic_test::run(), beast::tagged_integer_test::run(), ripple::RippleAsset_test::run(), beast::File_test::run(), ripple::RippleIdentifier_test::run(), beast::UnsignedInteger_test::test(), ripple::core::Quality_test::test_ceil_in(), ripple::core::Quality_test::test_ceil_out(), beast::hardened_hash_test::test_containers(), beast::Zero_test::test_lhs_zero(), beast::Zero_test::test_rhs_zero(), beast::hardened_hash_test::test_user_types(), beast::IP::IPEndpoint_test::testAddress(), beast::IP::IPEndpoint_test::testAddressV4(), beast::IP::IPEndpoint_test::testAddressV4Proxy(), ripple::STAmount_test::testArithmetic(), beast::aged_associative_container_test_base::testArrayCreate(), ripple::RippleAsset_test::testAssetMaps(), ripple::RippleAsset_test::testAssetSets(), beast::buffer_view_test::testAssign(), ripple::NodeStore::Backend_test::testBackend(), ripple::NodeStore::NodeStoreTiming_test::testBackend(), beast::BinaryEncoding_test::testBase16(), beast::BinaryEncoding_test::testBase64(), ripple::NodeStore::NodeStoreBasic_test::testBatches(), ripple::NodeStore::NodeStoreBasic_test::testBlobs(), ripple::RippleAsset_test::testBookMaps(), ripple::RippleAsset_test::testBookSets(), ripple::ECDSACanonical_test::testCanonicalConversions(), ripple::Resource::Manager_test::testCharges(), beast::aged_associative_container_test_base::testChronological(), beast::buffer_view_test::testCoerce(), beast::aged_associative_container_test_base::testCompare(), beast::buffer_view_test::testConstruct(), beast::aged_associative_container_test_base::testConstructEmpty(), beast::aged_associative_container_test_base::testConstructInitList(), beast::aged_associative_container_test_base::testConstructRange(), beast::aged_associative_container_test_base::testCopyMove(), ripple::STAmount_test::testCustomCurrency(), ripple::Resource::Manager_test::testDrop(), beast::buffer_view_test::testEmpty(), beast::BinaryEncoding_test::testEncode(), beast::IP::IPEndpoint_test::testEndpoint(), beast::RandomAccessFile_test::testFile(), ripple::NodeStore::NodeStoreDatabase_test::testImport(), ripple::Resource::Manager_test::testImport(), ripple::Resource::Manager_test::testImports(), beast::LexicalCast_test::testIntegers(), ripple::ECDSACanonical_test::testMalformedSignatures(), ripple::RangeSet_test::testMembership(), beast::aged_associative_container_test_base::testModifiers(), ripple::STAmount_test::testNativeCurrency(), ripple::NodeStore::NodeStoreDatabase_test::testNodeStore(), beast::aged_associative_container_test_base::testObservers(), beast::IP::IPEndpoint_test::testParse(), beast::SemanticVersion_test::testParse(), ripple::SerializedObject_test::testParseJSONArray(), ripple::SerializedObject_test::testParseJSONArrayWithInvalidChildrenObjects(), ripple::StringUtilities_test::testParseUrl(), ripple::RangeSet_test::testPrevMissing(), ripple::SerializedObject_test::testSerialization(), ripple::STAmount_test::testSetValue(), beast::hardened_hash_sha256_test::testSHA256(), ripple::ECDSACanonical_test::testStrictlyCanonicalSignatures(), beast::ServiceQueue_timing_test::testThreads(), beast::ServiceQueue_test::testThreads(), ripple::STAmount_test::testUnderflow(), ripple::StringUtilities_test::testUnHex(), and ripple::ECDSACanonical_test::testValidSignatures().
     {
         m_abort = abort == abort_on_fail;
         log->testcase (name);
     }
template<class Condition > bool beast::unit_test::suite::unexpected (Condition shouldBeFalse, std::string const & reason = "") inline
Definition at line 189 of file suite.h.
References fail(), and pass().
Referenced by beast::IP::IPEndpoint_test::failParseV4(), ripple::CKey_test::run(), beast::tagged_integer_test::run(), beast::shared_handler_test::run(), beast::asio::wrap_handler_test::run(), ripple::SerializedTransaction_test::run(), ripple::SHAMapSync_test::run(), beast::IP::IPEndpoint_test::shouldFail(), ripple::version::CheckLibraryVersions_test::test_bad_boost(), ripple::version::CheckLibraryVersions_test::test_bad_ssl(), beast::IP::IPEndpoint_test::testAddressV4(), ripple::STAmount_test::testArithmetic(), beast::aged_associative_container_test_base::testCompare(), beast::aged_associative_container_test_base::testCopyMove(), ripple::STAmount_test::testCustomCurrency(), ripple::STAmount_test::testNativeCurrency(), ripple::SerializedObject_test::testParseJSONArrayWithInvalidChildrenObjects(), ripple::StringUtilities_test::testParseUrl(), and ripple::SerializedObject_test::testSerialization().
     {
         if (! shouldBeFalse)
             pass();
         else
             fail (reason);
         return ! shouldBeFalse;
     }
Member Data Documentation
log_t beast::unit_test::suite::log
Memberspace for logging.
Definition at line 114 of file suite.h.
Referenced by ripple::SHAMapSync_test::confuseMap(), fail(), operator()(), pass(), beast::unit_test::detail::print_test::print(), beast::asio::HTTPClient_test::print(), ripple::version::CheckLibraryVersions_test::print_message(), beast::asio::PeerTest::Result::report(), beast::hash_append_test::report(), beast::unit_test::detail::print_test::run(), beast::abstract_clock_test::run(), beast::asio::boost_bind_test::run(), beast::Debug_test::run(), ripple::SerializedTransaction_test::run(), beast::hash_append_test::run(), beast::abstract_clock_test::test(), ripple::TestOverlay::Network2_test::test1(), beast::abstract_clock_test::test_manual(), ripple::NodeStore::NodeStoreTiming_test::testBackend(), beast::BinaryEncoding_test::testBase64Bytes(), testcase(), ripple::TestOverlay::Network1_test::testCreation(), beast::hardened_hash_sha256_test::testSHA256(), beast::ServiceQueue_timing_test::testThreads(), and beast::basic_abstract_ostream_test::test_stream::write().
bool beast::unit_test::suite::m_abort = false private
Definition at line 85 of file suite.h.
Referenced by fail(), and testcase().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/unit_test/suite.h