rippled: rocksdb::StringSink Class Reference
rocksdb::StringSink Class Reference
Public Member Functions
~StringSink ()
const std::string & contents () const
virtual Status Close ()
virtual Status Flush ()
virtual Status Sync ()
virtual Status Append (const Slice &data)
Public Member Functions inherited from rocksdb::WritableFile
WritableFile ()
virtual ~WritableFile ()
virtual Status Fsync ()
virtual uint64_t GetFileSize ()
void SetPreallocationBlockSize (size_t size)
virtual void GetPreallocationStatus (size_t *block_size, size_t *last_allocated_block)
virtual size_t GetUniqueId (char *id, size_t max_size) const
virtual Status InvalidateCache (size_t offset, size_t length)
Private Attributes
std::string contents_
Additional Inherited Members
Protected Member Functions inherited from rocksdb::WritableFile
void PrepareWrite (size_t offset, size_t len)
virtual Status Allocate (off_t offset, off_t len)
virtual Status RangeSync (off_t offset, off_t nbytes)
Detailed Description
Definition at line 100 of file table_test.cc.
Constructor & Destructor Documentation
rocksdb::StringSink::~StringSink () inline
Definition at line 102 of file table_test.cc.
 { }
Member Function Documentation
virtual Status rocksdb::StringSink::Append (const Slice & data) inline virtual
Implements rocksdb::WritableFile.
Definition at line 110 of file table_test.cc.
References contents_, rocksdb::Slice::data(), rocksdb::Status::OK(), and rocksdb::Slice::size().
{
     contents_.append(data.data(), data.size());
     return Status::OK();
   }
virtual Status rocksdb::StringSink::Close () inline virtual
Implements rocksdb::WritableFile.
Definition at line 106 of file table_test.cc.
References rocksdb::Status::OK().
 { return Status::OK(); }
const std::string& rocksdb::StringSink::contents () const inline
Definition at line 104 of file table_test.cc.
References contents_.
 { return contents_; }
virtual Status rocksdb::StringSink::Flush () inline virtual
Implements rocksdb::WritableFile.
Definition at line 107 of file table_test.cc.
References rocksdb::Status::OK().
 { return Status::OK(); }
virtual Status rocksdb::StringSink::Sync () inline virtual
Implements rocksdb::WritableFile.
Definition at line 108 of file table_test.cc.
References rocksdb::Status::OK().
 { return Status::OK(); }
Member Data Documentation
std::string rocksdb::StringSink::contents_ private
Definition at line 116 of file table_test.cc.
Referenced by Append(), and contents().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/table/table_test.cc