rippled: beast::aged_associative_container_test_base::TestTraitsHelper< IsUnordered, IsMulti, IsMap > Struct Template Reference
beast::aged_associative_container_test_base::TestTraitsHelper< IsUnordered, IsMulti, IsMap > Struct Template Reference
Public Types
typedef std::integral_constant
< bool, IsUnordered > is_unordered
typedef std::integral_constant
< bool, IsMulti > is_multi
typedef std::integral_constant
< bool, IsMap > is_map
typedef std::allocator
< typename Base::Value > Alloc
typedef AllocT< typename
Base::Value > MyAlloc
Public Types inherited from beast::aged_associative_container_test_base::MaybeUnordered< MaybeMulti< MaybeMap< TestTraitsBase, IsMap >, IsMulti >, IsUnordered >
typedef std::less< typename
MaybeMulti< MaybeMap
< TestTraitsBase, IsMap >
, IsMulti >::Key > Comp
typedef CompT< typename
MaybeMulti< MaybeMap
< TestTraitsBase, IsMap >
, IsMulti >::Key > MyComp
Static Public Member Functions
static std::string name ()
Private Types
typedef MaybeUnordered
< MaybeMulti< MaybeMap
< TestTraitsBase, IsMap >
, IsMulti >, IsUnordered > Base
Additional Inherited Members
Static Protected Member Functions inherited from beast::aged_associative_container_test_base::MaybeUnordered< MaybeMulti< MaybeMap< TestTraitsBase, IsMap >, IsMulti >, IsUnordered >
static std::string name_ordered_part ()
Detailed Description
template<bool IsUnordered, bool IsMulti, bool IsMap>
struct beast::aged_associative_container_test_base::TestTraitsHelper< IsUnordered, IsMulti, IsMap >
Definition at line 335 of file aged_associative_container.test.cpp.
Member Typedef Documentation
template<bool IsUnordered, bool IsMulti, bool IsMap> typedef std::allocator<typename Base::Value> beast::aged_associative_container_test_base::TestTraitsHelper< IsUnordered, IsMulti, IsMap >::Alloc
Definition at line 350 of file aged_associative_container.test.cpp.
template<bool IsUnordered, bool IsMulti, bool IsMap> typedef MaybeUnordered<MaybeMulti <MaybeMap < TestTraitsBase, IsMap>, IsMulti>, IsUnordered> beast::aged_associative_container_test_base::TestTraitsHelper< IsUnordered, IsMulti, IsMap >::Base private
Definition at line 341 of file aged_associative_container.test.cpp.
template<bool IsUnordered, bool IsMulti, bool IsMap> typedef std::integral_constant<bool, IsMap> beast::aged_associative_container_test_base::TestTraitsHelper< IsUnordered, IsMulti, IsMap >::is_map
Definition at line 348 of file aged_associative_container.test.cpp.
template<bool IsUnordered, bool IsMulti, bool IsMap> typedef std::integral_constant<bool, IsMulti> beast::aged_associative_container_test_base::TestTraitsHelper< IsUnordered, IsMulti, IsMap >::is_multi
Definition at line 347 of file aged_associative_container.test.cpp.
template<bool IsUnordered, bool IsMulti, bool IsMap> typedef std::integral_constant<bool, IsUnordered> beast::aged_associative_container_test_base::TestTraitsHelper< IsUnordered, IsMulti, IsMap >::is_unordered
Definition at line 346 of file aged_associative_container.test.cpp.
template<bool IsUnordered, bool IsMulti, bool IsMap> typedef AllocT<typename Base::Value> beast::aged_associative_container_test_base::TestTraitsHelper< IsUnordered, IsMulti, IsMap >::MyAlloc
Definition at line 351 of file aged_associative_container.test.cpp.
Member Function Documentation
template<bool IsUnordered, bool IsMulti, bool IsMap> static std::string beast::aged_associative_container_test_base::TestTraitsHelper< IsUnordered, IsMulti, IsMap >::name () inline static
Definition at line 353 of file aged_associative_container.test.cpp.
References beast::aged_associative_container_test_base::MaybeMap< TestTraitsBase, IsMap >::name_map_part(), beast::aged_associative_container_test_base::MaybeMulti< MaybeMap< TestTraitsBase, IsMap >, IsMulti >::name_multi_part(), and beast::aged_associative_container_test_base::MaybeUnordered< MaybeMulti< MaybeMap< TestTraitsBase, IsMap >, IsMulti >, IsUnordered >::name_ordered_part().
         {
             return std::string ("aged_") +
                 Base::name_ordered_part() +
                     Base::name_multi_part() +
                         Base::name_map_part();
         }
The documentation for this struct was generated from the following file:
rippled/src/beast/beast/container/tests/aged_associative_container.test.cpp