rippled: beast::asio::InputParser Namespace Reference
beast::asio::InputParser Namespace Reference
Classes
struct State
struct Get
struct Match
struct Peek
struct Match< char const * >
struct Digit
struct Get< Digit >
struct UInt32Str
struct Get< UInt32Str >
struct UInt16Str
struct Get< UInt16Str >
struct UInt8Str
struct Get< UInt8Str >
struct IPv4Address
struct Get< IPv4Address >
Typedefs
typedef FixedInputBuffer & Input
Functions
static State match_buffer (Input in, void const *buffer, std::size_t bytes)
template<class T >
State match (Input in, T t)
template<class T >
bool match (Input in, T t, State &state)
template<class T >
State peek (Input in, T &t)
template<class T >
bool peek (Input in, T &t, State &state)
template<class T >
State read (Input in, T &t)
template<class T >
bool read (Input in, T &t, State &state)
Typedef Documentation
typedef FixedInputBuffer& beast::asio::InputParser::Input
Definition at line 66 of file InputParser.h.
Function Documentation
template<class T > State beast::asio::InputParser::match (Input in, T t)
Definition at line 138 of file InputParser.h.
References Json::in().
Referenced by beast::asio::HandshakeDetectLogicPROXY::analyze_input(), beast::aged_associative_container_test_base::checkUnorderedContentsRefRef(), rocksdb::ManifestDumpCommand::DoCommand(), beast::asio::InputParser::Get< IPv4Address >::func(), match(), matchQuality(), ripple::STObject::operator==(), ripple::Validators::Utilities::parseInfoLine(), ripple::STObject::setType(), and ripple::UniqueNodeListImp::trustedLoad().
 {
     return Match <T>::func (in, t);
 }
template<class T > bool beast::asio::InputParser::match (Input in, T t, State & state)
Definition at line 145 of file InputParser.h.
References match(), and beast::asio::InputParser::State::passed().
 {
     return (state = match (in, t)).passed ();
 }
static State beast::asio::InputParser::match_buffer (Input in, void const * buffer, std::size_t bytes) static
Definition at line 113 of file InputParser.h.
References bassert, ripple::compare(), beast::asio::FixedInputBuffer::consume(), beast::asio::InputParser::State::fail, ripple::min(), beast::asio::InputParser::State::more, beast::asio::FixedInputBuffer::peek(), and beast::asio::FixedInputBuffer::size().
Referenced by beast::asio::InputParser::Match< char const * >::func().
 {
     bassert (bytes > 0);
     if (in.size () <= 0)
         return State::more;
     std::size_t const have = std::min (in.size (), bytes);
     void const* data = in.peek (have);
     bassert (data != nullptr);
     int const compare = memcmp (data, buffer, have);
     if (compare != 0)
         return State::fail;
     in.consume (have);
     return have == bytes;
 }
template<class T > State beast::asio::InputParser::peek (Input in, T & t)
Definition at line 157 of file InputParser.h.
References Json::in().
Referenced by beast::asio::InputParser::Get< UInt32Str >::func(), and peek().
 {
     return Peek <T>::func (in, t);
 }
template<class T > bool beast::asio::InputParser::peek (Input in, T & t, State & state)
Definition at line 164 of file InputParser.h.
References beast::asio::InputParser::State::passed(), and peek().
 {
     return (state = peek (in, t)).passed ();
 }
template<class T > State beast::asio::InputParser::read (Input in, T & t)
Definition at line 176 of file InputParser.h.
References Json::in().
Referenced by beast::asio::HandshakeDetectLogicPROXY::analyze_input(), beast::asio::InputParser::Get< UInt32Str >::func(), beast::asio::InputParser::Get< UInt16Str >::func(), beast::asio::InputParser::Get< UInt8Str >::func(), beast::asio::InputParser::Get< IPv4Address >::func(), main(), beast::asio::TestPeerLogicSyncClient::on_connect(), read(), rocksdb::TEST(), test_message(), test_message_count_body(), test_multiple3(), and test_scan().
 {
     return Get <T>::func (in, t);
 }
template<class T > bool beast::asio::InputParser::read (Input in, T & t, State & state)
Definition at line 183 of file InputParser.h.
References beast::asio::InputParser::State::passed(), and read().
 {
     return (state = read (in, t)).passed ();
 }