rippled: ShellStateStart Class Reference
ShellStateStart Class Reference
#include <ShellState.h>
Public Member Functions
virtual void run (ShellContext *)
Public Member Functions inherited from ShellState
virtual ~ShellState ()
Static Public Member Functions
static ShellStateStart * getInstance (void)
Private Member Functions
ShellStateStart ()
virtual ~ShellStateStart ()
Detailed Description
Definition at line 24 of file ShellState.h.
Constructor & Destructor Documentation
ShellStateStart::ShellStateStart () inline private
Definition at line 34 of file ShellState.h.
 {}
virtual ShellStateStart::~ShellStateStart () inline private virtual
Definition at line 35 of file ShellState.h.
 {}
Member Function Documentation
static ShellStateStart* ShellStateStart::getInstance (void) inline static
Definition at line 26 of file ShellState.h.
References instance.
{
     static ShellStateStart instance;
     return &instance;
   }
void ShellStateStart::run (ShellContext * c) virtual
Implements ShellState.
Definition at line 17 of file ShellState.cpp.
References ShellContext::changeState(), ShellStateStop::getInstance(), ShellStateConnecting::getInstance(), and ShellContext::ParseInput().
{
   if(!c->ParseInput()) {
     c->changeState(ShellStateStop::getInstance());
   } else {
     c->changeState(ShellStateConnecting::getInstance());
   }
 }
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/tools/shell/ShellState.h
rippled/src/ripple/rocksdb/rocksdb/tools/shell/ShellState.cpp