rippled: beast::sqdb::detail::ref_counted_statement_base Class Reference
beast::sqdb::detail::ref_counted_statement_base Class Reference abstract
#include <ref_counted_statement.h>
Public Member Functions
ref_counted_statement_base (session &s)
virtual ~ref_counted_statement_base ()
virtual void final_action ()=0
void addref ()
void release ()
template<typename T >
void accumulate (T const &t)
std::ostringstream & get_query_stream ()
Public Attributes
Error * m_perror
int m_refs
session & m_session
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
Definition at line 68 of file ref_counted_statement.h.
Constructor & Destructor Documentation
beast::sqdb::detail::ref_counted_statement_base::ref_counted_statement_base (session & s)
Definition at line 64 of file ref_counted_statement.cpp.
     : m_refs(1)
     , m_session(s)
 {
 }
beast::sqdb::detail::ref_counted_statement_base::~ref_counted_statement_base () virtual
Definition at line 70 of file ref_counted_statement.cpp.
 {
 }
Member Function Documentation
template<typename T > void beast::sqdb::detail::ref_counted_statement_base::accumulate (T const & t) inline
Definition at line 79 of file ref_counted_statement.h.
References get_query_stream().
Referenced by beast::sqdb::detail::prepare_temp_type::operator<<(), and beast::sqdb::detail::once_temp_type::operator<<().
     {
         get_query_stream() << t;
     }
void beast::sqdb::detail::ref_counted_statement_base::addref ()
Definition at line 74 of file ref_counted_statement.cpp.
References m_refs.
Referenced by beast::sqdb::detail::once_temp_type::once_temp_type(), beast::sqdb::detail::once_temp_type::operator=(), beast::sqdb::detail::prepare_temp_type::operator=(), and beast::sqdb::detail::prepare_temp_type::prepare_temp_type().
 {
     ++m_refs;
 }
virtual void beast::sqdb::detail::ref_counted_statement_base::final_action () pure virtual
Implemented in beast::sqdb::detail::ref_counted_statement, and beast::sqdb::detail::ref_counted_prepare_info.
Referenced by release().
std::ostringstream & beast::sqdb::detail::ref_counted_statement_base::get_query_stream ()
Definition at line 88 of file ref_counted_statement.cpp.
References beast::sqdb::session::get_query_stream(), and m_session.
Referenced by accumulate().
 {
     return m_session.get_query_stream();
 }
void beast::sqdb::detail::ref_counted_statement_base::release ()
Definition at line 79 of file ref_counted_statement.cpp.
References final_action(), and m_refs.
Referenced by beast::sqdb::detail::once_temp_type::operator=(), beast::sqdb::detail::prepare_temp_type::operator=(), beast::sqdb::detail::once_temp_type::~once_temp_type(), and beast::sqdb::detail::prepare_temp_type::~prepare_temp_type().
 {
     if (--m_refs == 0)
     {
         final_action();
         delete this;
     }
 }
Member Data Documentation
Error* beast::sqdb::detail::ref_counted_statement_base::m_perror
Definition at line 88 of file ref_counted_statement.h.
int beast::sqdb::detail::ref_counted_statement_base::m_refs
Definition at line 89 of file ref_counted_statement.h.
Referenced by addref(), and release().
session& beast::sqdb::detail::ref_counted_statement_base::m_session
Definition at line 90 of file ref_counted_statement.h.
Referenced by beast::sqdb::detail::ref_counted_statement::final_action(), beast::sqdb::detail::ref_counted_prepare_info::get_query(), and get_query_stream().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_sqdb/detail/ref_counted_statement.h
rippled/src/beast/modules/beast_sqdb/source/ref_counted_statement.cpp