rippled: beast::HexConverter< Type > Struct Template Reference
beast::HexConverter< Type > Struct Template Reference
Static Public Member Functions
static String hexToString (Type v)
static Type stringToHex (String::CharPointerType t) noexcept
Detailed Description
template<typename Type>
struct beast::HexConverter< Type >
Definition at line 1734 of file String.cpp.
Member Function Documentation
template<typename Type > static String beast::HexConverter< Type >::hexToString (Type v) inline static
Definition at line 1736 of file String.cpp.
References beast::hexDigits.
     {
         char buffer[32];
         char* const end = buffer + 32;
         char* t = end;
         *--t = 0;
         do
         {
             *--t = hexDigits [(int) (v & 15)];
             v >>= 4;
         } while (v != 0);
         return String (t, (size_t) (end - t) - 1);
     }
template<typename Type > static Type beast::HexConverter< Type >::stringToHex (String::CharPointerType t) inline static noexcept
Definition at line 1753 of file String.cpp.
References beast::CharacterFunctions::getHexDigitValue().
Referenced by beast::String::getHexValue32(), and beast::String::getHexValue64().
     {
         Type result = 0;
         while (! t.isEmpty())
         {
             const int hexValue = CharacterFunctions::getHexDigitValue (t.getAndAdvance());
             if (hexValue >= 0)
                 result = (result << 4) | hexValue;
         }
         return result;
     }
The documentation for this struct was generated from the following file:
rippled/src/beast/beast/strings/impl/String.cpp