rippled: rocksdb::InMemoryHandler Class Reference
rocksdb::InMemoryHandler Class Reference
Public Member Functions
virtual void Put (const Slice &key, const Slice &value)
virtual void Delete (const Slice &key)
virtual ~InMemoryHandler ()
map< string, string > PutMap ()
vector< string > DeleteList ()
Public Member Functions inherited from rocksdb::WriteBatch::Handler
virtual ~Handler ()
virtual void Merge (const Slice &key, const Slice &value)
virtual void LogData (const Slice &blob)
virtual bool Continue ()
Private Attributes
map< string, string > putMap_
vector< string > deleteList_
Detailed Description
Definition at line 1227 of file ldb_cmd.cc.
Constructor & Destructor Documentation
virtual rocksdb::InMemoryHandler::~InMemoryHandler () inline virtual
Definition at line 1236 of file ldb_cmd.cc.
 { };
Member Function Documentation
virtual void rocksdb::InMemoryHandler::Delete (const Slice & key) inline virtual
Implements rocksdb::WriteBatch::Handler.
Definition at line 1233 of file ldb_cmd.cc.
References deleteList_, and rocksdb::Slice::ToString().
{
     deleteList_.push_back(key.ToString(true));
   }
vector<string> rocksdb::InMemoryHandler::DeleteList () inline
Definition at line 1241 of file ldb_cmd.cc.
References deleteList_.
Referenced by rocksdb::WALDumperCommand::DoCommand().
{
     return deleteList_;
   }
virtual void rocksdb::InMemoryHandler::Put (const Slice & key, const Slice & value) inline virtual
Implements rocksdb::WriteBatch::Handler.
Definition at line 1230 of file ldb_cmd.cc.
References putMap_, and rocksdb::Slice::ToString().
{
     putMap_[key.ToString()] = value.ToString();
   }
map<string, string> rocksdb::InMemoryHandler::PutMap () inline
Definition at line 1238 of file ldb_cmd.cc.
References putMap_.
Referenced by rocksdb::WALDumperCommand::DoCommand().
{
     return putMap_;
   }
Member Data Documentation
vector<string> rocksdb::InMemoryHandler::deleteList_ private
Definition at line 1247 of file ldb_cmd.cc.
Referenced by Delete(), and DeleteList().
map<string, string> rocksdb::InMemoryHandler::putMap_ private
Definition at line 1246 of file ldb_cmd.cc.
Referenced by Put(), and PutMap().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/util/ldb_cmd.cc