rippled: ripple::PeerFinder Namespace Reference
ripple::PeerFinder Namespace Reference
Namespaces
detail
Sim
Tuning
Classes
struct Callback
struct Config
struct Endpoint
class Manager
class Slot
class Bootcache
class CheckerImp
class Checker
class CheckerAdapter
class ConnectHandouts
class Counts
class Fixed
class Livecache_test
class Livecache
class Logic
class ManagerImp
class RedirectHandouts
struct Reporting
class SlotHandouts
class SlotImp
class Source
class SourceStringsImp
class SourceStrings
class Store
class StoreSqdb
class WrappedSink
Typedefs
typedef std::vector
< beast::IP::Endpoint > IPAddresses
typedef std::vector< Endpoint > Endpoints
typedef beast::abstract_clock
< std::chrono::seconds > clock_type
typedef
beast::ScopedWrapperContext
< beast::RecursiveMutex,
beast::RecursiveMutex::ScopedLockType > SerializedContext
Enumerations
enum HandshakeAction { doActivate, doRedirect, doClose }
Functions
bool operator< (Endpoint const &lhs, Endpoint const &rhs)
template<class TargetFwdIter , class SeqFwdIter >
void handout (TargetFwdIter first, TargetFwdIter last, SeqFwdIter seq_first, SeqFwdIter seq_last)
BEAST_DEFINE_TESTSUITE (Livecache, peerfinder, ripple)
Typedef Documentation
typedef beast::abstract_clock<std::chrono::seconds> ripple::PeerFinder::clock_type
Definition at line 36 of file Types.h.
typedef std::vector<Endpoint> ripple::PeerFinder::Endpoints
A set of Endpoint used for connecting.
Definition at line 34 of file Types.h.
typedef std::vector<beast::IP::Endpoint> ripple::PeerFinder::IPAddresses
Represents a set of addresses.
Definition at line 31 of file Types.h.
typedef beast::ScopedWrapperContext< beast::RecursiveMutex, beast::RecursiveMutex::ScopedLockType> ripple::PeerFinder::SerializedContext
Definition at line 32 of file CheckerAdapter.h.
Enumeration Type Documentation
enum ripple::PeerFinder::HandshakeAction
Indicates the action the logic will take after a handshake.
Enumerator
doActivate
doRedirect
doClose
Definition at line 27 of file PrivateTypes.h.
 {
     doActivate,
     doRedirect,
     doClose
 };
Function Documentation
ripple::PeerFinder::BEAST_DEFINE_TESTSUITE (Livecache , peerfinder , ripple)
template<class TargetFwdIter , class SeqFwdIter > void ripple::PeerFinder::handout (TargetFwdIter first, TargetFwdIter last, SeqFwdIter seq_first, SeqFwdIter seq_last)
Distributes objects to targets according to business rules. A best effort is made to evenly distribute items in the sequence container list into the target sequence list.
Definition at line 58 of file handout.h.
References ripple::PeerFinder::detail::handout_one().
Referenced by ripple::PeerFinder::Logic::autoconnect(), ripple::PeerFinder::Logic::broadcast(), and ripple::PeerFinder::Logic::redirect().
 {
     for (;;)
     {
         std::size_t n (0);
         for (auto si (seq_first); si != seq_last; ++si)
         {
             auto c (*si);
             bool all_full (true);
             for (auto ti (first); ti != last; ++ti)
             {
                 auto& t (*ti);
                 if (! t.full())
                 {
                     n += detail::handout_one (t, c);
                     all_full = false;
                 }
             }
             if (all_full)
                 return;
         }
         if (! n)
             break;
     }
 }
bool ripple::PeerFinder::operator< (Endpoint const & lhs, Endpoint const & rhs)
Definition at line 36 of file Endpoint.cpp.
References ripple::PeerFinder::Endpoint::address.
 {
     return lhs.address < rhs.address;
 }