rippled: rocksdb::FilterPolicy Class Reference
rocksdb::FilterPolicy Class Reference abstract
#include <filter_policy.h>
Public Member Functions
virtual ~FilterPolicy ()
virtual const char * Name () const =0
virtual void CreateFilter (const Slice *keys, int n, std::string *dst) const =0
virtual bool KeyMayMatch (const Slice &key, const Slice &filter) const =0
Detailed Description
Definition at line 29 of file filter_policy.h.
Constructor & Destructor Documentation
rocksdb::FilterPolicy::~FilterPolicy () virtual
Definition at line 14 of file filter_policy.cc.
 { }
Member Function Documentation
virtual void rocksdb::FilterPolicy::CreateFilter (const Slice * keys, int n, std::string * dst) const pure virtual
Implemented in rocksdb::InternalFilterPolicy, leveldb_filterpolicy_t, and rocksdb::TestHashFilter.
Referenced by rocksdb::BloomTest::Build(), rocksdb::InternalFilterPolicy::CreateFilter(), and rocksdb::FilterBlockBuilder::GenerateFilter().
virtual bool rocksdb::FilterPolicy::KeyMayMatch (const Slice & key, const Slice & filter) const pure virtual
Implemented in leveldb_filterpolicy_t, rocksdb::InternalFilterPolicy, and rocksdb::TestHashFilter.
Referenced by rocksdb::InternalFilterPolicy::KeyMayMatch(), rocksdb::BloomTest::Matches(), and rocksdb::FilterBlockReader::MayMatch().
virtual const char* rocksdb::FilterPolicy::Name () const pure virtual
Implemented in rocksdb::InternalFilterPolicy, leveldb_filterpolicy_t, and rocksdb::TestHashFilter.
Referenced by rocksdb::Options::Dump(), rocksdb::BlockBasedTableBuilder::Finish(), rocksdb::BlockBasedTable::GetFilter(), rocksdb::InternalFilterPolicy::Name(), and rocksdb::BlockBasedTable::Open().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/include/rocksdb/filter_policy.h
rippled/src/ripple/rocksdb/rocksdb/util/filter_policy.cc