rippled: rippled/src/ripple/json/impl/json_internalarray.inl File Reference
json_internalarray.inl File Reference
Classes
class DefaultValueArrayAllocator
struct DummyArrayAllocatorInitializer
Functions
static ValueArrayAllocator *& arrayAllocator ()
Variables
static struct
DummyArrayAllocatorInitializer dummyArrayAllocatorInitializer
Function Documentation
static ValueArrayAllocator*& arrayAllocator () static
Definition at line 169 of file json_internalarray.inl.
Referenced by DummyArrayAllocatorInitializer::DummyArrayAllocatorInitializer(), Json::Value::Value(), and Json::Value::~Value().
 {
     static DefaultValueArrayAllocator defaultAllocator;
     static ValueArrayAllocator* arrayAllocator = &defaultAllocator;
     return arrayAllocator;
 }
Variable Documentation
struct DummyArrayAllocatorInitializer dummyArrayAllocatorInitializer static