rippled: beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator > Class Template Reference
beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator > Class Template Reference
#include <aged_unordered_container.h>
Classes
class Buckets
class chronological_t
class config_t
struct element
class KeyValueEqual
class ValueHash
Public Types
typedef abstract_clock< Duration > clock_type
typedef clock_type::time_point time_point
typedef clock_type::duration duration
typedef Key key_type
typedef T mapped_type
typedef std::conditional
< IsMap, std::pair< Key const,
T >, Key >::type value_type
typedef std::size_t size_type
typedef std::ptrdiff_t difference_type
typedef std::true_type is_unordered
typedef std::integral_constant
< bool, IsMulti > is_multi
typedef std::integral_constant
< bool, IsMap > is_map
typedef Hash hasher
typedef KeyEqual key_equal
typedef Allocator allocator_type
typedef value_type & reference
typedef value_type const & const_reference
typedef std::allocator_traits
< Allocator >::pointer pointer
typedef std::allocator_traits
< Allocator >::const_pointer const_pointer
typedef
detail::aged_container_iterator
< false, typename
cont_type::iterator > iterator
typedef
detail::aged_container_iterator
< true, typename
cont_type::iterator > const_iterator
typedef
detail::aged_container_iterator
< false, typename
cont_type::local_iterator > local_iterator
typedef
detail::aged_container_iterator
< true, typename
cont_type::local_iterator > const_local_iterator
Public Member Functions
aged_unordered_container (clock_type &clock)
aged_unordered_container (clock_type &clock, Hash const &hash)
aged_unordered_container (clock_type &clock, KeyEqual const &key_eq)
aged_unordered_container (clock_type &clock, Allocator const &alloc)
aged_unordered_container (clock_type &clock, Hash const &hash, KeyEqual const &key_eq)
aged_unordered_container (clock_type &clock, Hash const &hash, Allocator const &alloc)
aged_unordered_container (clock_type &clock, KeyEqual const &key_eq, Allocator const &alloc)
aged_unordered_container (clock_type &clock, Hash const &hash, KeyEqual const &key_eq, Allocator const &alloc)
template<class InputIt >
aged_unordered_container (InputIt first, InputIt last, clock_type &clock)
template<class InputIt >
aged_unordered_container (InputIt first, InputIt last, clock_type &clock, Hash const &hash)
template<class InputIt >
aged_unordered_container (InputIt first, InputIt last, clock_type &clock, KeyEqual const &key_eq)
template<class InputIt >
aged_unordered_container (InputIt first, InputIt last, clock_type &clock, Allocator const &alloc)
template<class InputIt >
aged_unordered_container (InputIt first, InputIt last, clock_type &clock, Hash const &hash, KeyEqual const &key_eq)
template<class InputIt >
aged_unordered_container (InputIt first, InputIt last, clock_type &clock, Hash const &hash, Allocator const &alloc)
template<class InputIt >
aged_unordered_container (InputIt first, InputIt last, clock_type &clock, KeyEqual const &key_eq, Allocator const &alloc)
template<class InputIt >
aged_unordered_container (InputIt first, InputIt last, clock_type &clock, Hash const &hash, KeyEqual const &key_eq, Allocator const &alloc)
aged_unordered_container (aged_unordered_container const &other)
aged_unordered_container (aged_unordered_container const &other, Allocator const &alloc)
aged_unordered_container (aged_unordered_container &&other)
aged_unordered_container (aged_unordered_container &&other, Allocator const &alloc)
aged_unordered_container (std::initializer_list< value_type > init, clock_type &clock)
aged_unordered_container (std::initializer_list< value_type > init, clock_type &clock, Hash const &hash)
aged_unordered_container (std::initializer_list< value_type > init, clock_type &clock, KeyEqual const &key_eq)
aged_unordered_container (std::initializer_list< value_type > init, clock_type &clock, Allocator const &alloc)
aged_unordered_container (std::initializer_list< value_type > init, clock_type &clock, Hash const &hash, KeyEqual const &key_eq)
aged_unordered_container (std::initializer_list< value_type > init, clock_type &clock, Hash const &hash, Allocator const &alloc)
aged_unordered_container (std::initializer_list< value_type > init, clock_type &clock, KeyEqual const &key_eq, Allocator const &alloc)
aged_unordered_container (std::initializer_list< value_type > init, clock_type &clock, Hash const &hash, KeyEqual const &key_eq, Allocator const &alloc)
~aged_unordered_container ()
aged_unordered_container & operator= (aged_unordered_container const &other)
aged_unordered_container & operator= (aged_unordered_container &&other)
aged_unordered_container & operator= (std::initializer_list< value_type > init)
allocator_type get_allocator () const
clock_type & clock ()
clock_type const & clock () const
template<class K , bool maybe_multi = IsMulti, bool maybe_map = IsMap, class = typename std::enable_if <maybe_map && ! maybe_multi>::type>
std::conditional< IsMap, T,
void * >::type & at (K const &k)
template<class K , bool maybe_multi = IsMulti, bool maybe_map = IsMap, class = typename std::enable_if <maybe_map && ! maybe_multi>::type>
std::conditional< IsMap, T,
void * >::type const & at (K const &k) const
template<bool maybe_multi = IsMulti, bool maybe_map = IsMap, class = typename std::enable_if <maybe_map && ! maybe_multi>::type>
std::conditional< IsMap, T,
void * >::type & operator[] (Key const &key)
template<bool maybe_multi = IsMulti, bool maybe_map = IsMap, class = typename std::enable_if <maybe_map && ! maybe_multi>::type>
std::conditional< IsMap, T,
void * >::type & operator[] (Key &&key)
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
iterator end ()
const_iterator end () const
const_iterator cend () const
iterator iterator_to (value_type &value)
const_iterator iterator_to (value_type const &value) const
bool empty () const noexcept
size_type size () const noexcept
size_type max_size () const noexcept
void clear ()
template<bool maybe_multi = IsMulti>
auto insert (value_type const &value) -> typename std::enable_if<!maybe_multi, std::pair< iterator, bool >>::type
template<bool maybe_multi = IsMulti>
auto insert (value_type const &value) -> typename std::enable_if< maybe_multi, iterator >::type
template<bool maybe_multi = IsMulti, bool maybe_map = IsMap>
auto insert (value_type &&value) -> typename std::enable_if<!maybe_multi &&!maybe_map, std::pair< iterator, bool >>::type
template<bool maybe_multi = IsMulti, bool maybe_map = IsMap>
auto insert (value_type &&value) -> typename std::enable_if< maybe_multi &&!maybe_map, iterator >::type
template<bool maybe_multi = IsMulti>
std::enable_if<!maybe_multi,
iterator >::type insert (const_iterator, value_type const &value)
template<bool maybe_multi = IsMulti>
std::enable_if< maybe_multi,
iterator >::type insert (const_iterator const &, value_type const &value)
template<bool maybe_multi = IsMulti>
std::enable_if<!maybe_multi,
iterator >::type insert (const_iterator, value_type &&value)
template<bool maybe_multi = IsMulti>
std::enable_if< maybe_multi,
iterator >::type insert (const_iterator const &, value_type &&value)
template<class P , bool maybe_map = IsMap>
std::enable_if< maybe_map
&&std::is_constructible
< value_type, P && >::value,
typename std::conditional
< IsMulti, iterator, std::pair
< iterator, bool > >::type >
::type insert (P &&value)
template<class P , bool maybe_map = IsMap>
std::enable_if< maybe_map
&&std::is_constructible
< value_type, P && >::value,
typename std::conditional
< IsMulti, iterator, std::pair
< iterator, bool > >::type >
::type insert (const_iterator hint, P &&value)
template<class InputIt >
void insert (InputIt first, InputIt const &last)
void insert (std::initializer_list< value_type > init)
template<bool maybe_multi = IsMulti, class... Args>
auto emplace (Args &&...args) -> typename std::enable_if<!maybe_multi, std::pair< iterator, bool >>::type
template<bool maybe_multi = IsMulti, class... Args>
auto emplace (Args &&...args) -> typename std::enable_if< maybe_multi, iterator >::type
template<bool maybe_multi = IsMulti, class... Args>
auto emplace_hint (const_iterator const &, Args &&...args) -> typename std::enable_if<!maybe_multi, std::pair< iterator, bool >>::type
template<bool maybe_multi = IsMulti, class... Args>
std::enable_if< maybe_multi,
iterator >::type emplace_hint (const_iterator const &, Args &&...args)
template<bool is_const, class Iterator , class Base >
detail::aged_container_iterator
< false, Iterator, Base > erase (detail::aged_container_iterator< is_const, Iterator, Base > const &pos)
template<bool is_const, class Iterator , class Base >
detail::aged_container_iterator
< false, Iterator, Base > erase (detail::aged_container_iterator< is_const, Iterator, Base > first, detail::aged_container_iterator< is_const, Iterator, Base > const &last)
template<class K >
auto erase (K const &k) -> size_type
void swap (aged_unordered_container &other) noexcept
template<bool is_const, class Iterator , class Base >
void touch (detail::aged_container_iterator< is_const, Iterator, Base > const &pos)
template<class K >
auto touch (K const &k) -> size_type
template<class K >
size_type count (K const &k) const
template<class K >
iterator find (K const &k)
template<class K >
const_iterator find (K const &k) const
template<class K >
std::pair< iterator, iterator > equal_range (K const &k)
template<class K >
std::pair< const_iterator,
const_iterator > equal_range (K const &k) const
local_iterator begin (size_type n)
const_local_iterator begin (size_type n) const
const_local_iterator cbegin (size_type n) const
local_iterator end (size_type n)
const_local_iterator end (size_type n) const
const_local_iterator cend (size_type n) const
size_type bucket_count () const
size_type max_bucket_count () const
size_type bucket_size (size_type n) const
size_type bucket (Key const &k) const
float load_factor () const
float max_load_factor () const
void max_load_factor (float ml)
void rehash (size_type count)
void reserve (size_type count)
hasher const & hash_function () const
key_equal const & key_eq () const
template<bool OtherIsMap, class OtherKey , class OtherT , class OtherDuration , class OtherHash , class OtherAllocator , bool maybe_multi = IsMulti>
std::enable_if<!maybe_multi,
bool >::type operator== (aged_unordered_container< false, OtherIsMap, OtherKey, OtherT, OtherDuration, OtherHash, KeyEqual, OtherAllocator > const &other) const
template<bool OtherIsMap, class OtherKey , class OtherT , class OtherDuration , class OtherHash , class OtherAllocator , bool maybe_multi = IsMulti>
std::enable_if< maybe_multi,
bool >::type operator== (aged_unordered_container< true, OtherIsMap, OtherKey, OtherT, OtherDuration, OtherHash, KeyEqual, OtherAllocator > const &other) const
template<bool OtherIsMulti, bool OtherIsMap, class OtherKey , class OtherT , class OtherDuration , class OtherHash , class OtherAllocator >
bool operator!= (aged_unordered_container< OtherIsMulti, OtherIsMap, OtherKey, OtherT, OtherDuration, OtherHash, KeyEqual, OtherAllocator > const &other) const
Public Attributes
class
beast::detail::aged_unordered_container::chronological_t chronological
Private Types
typedef
boost::intrusive::make_list
< element,
boost::intrusive::constant_time_size
< false > >::type list_type
typedef std::conditional
< IsMulti, typename
boost::intrusive::make_unordered_multiset
< element,
boost::intrusive::constant_time_size
< true >
, boost::intrusive::hash
< ValueHash >
, boost::intrusive::equal
< KeyValueEqual >
, boost::intrusive::cache_begin
< true > >::type, typename
boost::intrusive::make_unordered_set
< element,
boost::intrusive::constant_time_size
< true >
, boost::intrusive::hash
< ValueHash >
, boost::intrusive::equal
< KeyValueEqual >
, boost::intrusive::cache_begin
< true > >::type >::type cont_type
typedef cont_type::bucket_type bucket_type
typedef cont_type::bucket_traits bucket_traits
typedef std::allocator_traits
< Allocator >::template
rebind_alloc< element > ElementAllocator
using ElementAllocatorTraits = std::allocator_traits< ElementAllocator >
typedef std::allocator_traits
< Allocator >::template
rebind_alloc< element > BucketAllocator
using BucketAllocatorTraits = std::allocator_traits< BucketAllocator >
Private Member Functions
template<class... Args>
element * new_element (Args &&...args)
void delete_element (element *p)
void unlink_and_delete_element (element *p)
bool would_exceed (size_type additional) const
void maybe_rehash (size_type additional)
template<bool maybe_multi = IsMulti>
auto insert_unchecked (value_type const &value) -> typename std::enable_if<!maybe_multi, std::pair< iterator, bool >>::type
template<bool maybe_multi = IsMulti>
auto insert_unchecked (value_type const &value) -> typename std::enable_if< maybe_multi, iterator >::type
template<class InputIt >
void insert_unchecked (InputIt first, InputIt const &last)
template<class InputIt >
void insert (InputIt first, InputIt const &last, std::input_iterator_tag)
template<class InputIt >
void insert (InputIt first, InputIt const &last, std::random_access_iterator_tag)
template<bool is_const, class Iterator , class Base >
void touch (detail::aged_container_iterator< is_const, Iterator, Base > const &pos, typename clock_type::time_point const &now)
template<bool maybe_propagate = std::allocator_traits < Allocator>::propagate_on_container_swap::value>
std::enable_if
< maybe_propagate >::type swap_data (aged_unordered_container &other) noexcept
template<bool maybe_propagate = std::allocator_traits < Allocator>::propagate_on_container_swap::value>
std::enable_if
<!maybe_propagate >::type swap_data (aged_unordered_container &other) noexcept
Static Private Member Functions
static Key const & extract (value_type const &value)
Private Attributes
config_t m_config
Buckets m_buck
cont_type m_cont
Detailed Description
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>>
class beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >
Associative container where each element is also indexed by time.
This container mirrors the interface of the standard library unordered associative containers, with the addition that each element is associated with a when time_point which is obtained from the value of the clock's now. The function touch updates the time for an element to the current time as reported by the clock.
An extra set of iterator types and member functions are provided in the chronological memberspace that allow traversal in temporal or reverse temporal order. This container is useful as a building block for caches whose items expire after a certain amount of time. The chronological iterators allow for fully customizable expiration strategies.
See Also
aged_unordered_set, aged_unordered_multiset
aged_unordered_map, aged_unordered_multimap
Definition at line 91 of file aged_unordered_container.h.
Member Typedef Documentation
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef Allocator beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::allocator_type
Definition at line 604 of file aged_unordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef cont_type::bucket_traits beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::bucket_traits private
Definition at line 280 of file aged_unordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef cont_type::bucket_type beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::bucket_type private
Definition at line 279 of file aged_unordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef std::allocator_traits< Allocator>::template rebind_alloc<element> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::BucketAllocator private
Definition at line 288 of file aged_unordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> using beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::BucketAllocatorTraits = std::allocator_traits <BucketAllocator> private
Definition at line 290 of file aged_unordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef abstract_clock<Duration> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::clock_type
Definition at line 94 of file aged_unordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef detail::aged_container_iterator<true, typename cont_type::iterator> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::const_iterator
Definition at line 615 of file aged_unordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef detail::aged_container_iterator<true, typename cont_type::local_iterator> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::const_local_iterator
Definition at line 620 of file aged_unordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef std::allocator_traits< Allocator>::const_pointer beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::const_pointer
Definition at line 610 of file aged_unordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef value_type const& beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::const_reference
Definition at line 606 of file aged_unordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef std::conditional< IsMulti, typename boost::intrusive::make_unordered_multiset <element, boost::intrusive::constant_time_size <true>, boost::intrusive::hash <ValueHash>, boost::intrusive::equal <KeyValueEqual>, boost::intrusive::cache_begin <true> >::type, typename boost::intrusive::make_unordered_set <element, boost::intrusive::constant_time_size <true>, boost::intrusive::hash <ValueHash>, boost::intrusive::equal <KeyValueEqual>, boost::intrusive::cache_begin <true> >::type >::type beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::cont_type private
Definition at line 277 of file aged_unordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef std::ptrdiff_t beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::difference_type
Definition at line 103 of file aged_unordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef clock_type::duration beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::duration
Definition at line 96 of file aged_unordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef std::allocator_traits< Allocator>::template rebind_alloc<element> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::ElementAllocator private
Definition at line 283 of file aged_unordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> using beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::ElementAllocatorTraits = std::allocator_traits <ElementAllocator> private
Definition at line 285 of file aged_unordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef Hash beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::hasher
Definition at line 602 of file aged_unordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef std::integral_constant<bool, IsMap> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::is_map
Definition at line 108 of file aged_unordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef std::integral_constant<bool, IsMulti> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::is_multi
Definition at line 107 of file aged_unordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef std::true_type beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::is_unordered
Definition at line 106 of file aged_unordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef detail::aged_container_iterator<false, typename cont_type::iterator> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::iterator
Definition at line 613 of file aged_unordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef KeyEqual beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::key_equal
Definition at line 603 of file aged_unordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef Key beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::key_type
Definition at line 97 of file aged_unordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef boost::intrusive::make_list<element, boost::intrusive::constant_time_size <false> >::type beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::list_type private
Definition at line 261 of file aged_unordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef detail::aged_container_iterator<false, typename cont_type::local_iterator> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::local_iterator
Definition at line 618 of file aged_unordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef T beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::mapped_type
Definition at line 98 of file aged_unordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef std::allocator_traits< Allocator>::pointer beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::pointer
Definition at line 608 of file aged_unordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef value_type& beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::reference
Definition at line 605 of file aged_unordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef std::size_t beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::size_type
Definition at line 102 of file aged_unordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef clock_type::time_point beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::time_point
Definition at line 95 of file aged_unordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef std::conditional<IsMap, std::pair <Key const, T>, Key>::type beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::value_type
Definition at line 101 of file aged_unordered_container.h.
Constructor & Destructor Documentation
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash , class KeyEqual , class Allocator > beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::aged_unordered_container (clock_type & clock) explicit
Definition at line 1527 of file aged_unordered_container.h.
     : m_config (clock)
     , m_cont (m_buck,
         std::cref (m_config.value_hash()),
             std::cref (m_config.key_value_equal()))
 {
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash, class KeyEqual , class Allocator > beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::aged_unordered_container (clock_type & clock, Hash const & hash)
Definition at line 1540 of file aged_unordered_container.h.
     : m_config (clock, hash)
     , m_cont (m_buck,
         std::cref (m_config.value_hash()),
             std::cref (m_config.key_value_equal()))
 {
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash, class KeyEqual, class Allocator > beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::aged_unordered_container (clock_type & clock, KeyEqual const & key_eq)
Definition at line 1554 of file aged_unordered_container.h.
     : m_config (clock, key_eq)
     , m_cont (m_buck,
         std::cref (m_config.value_hash()),
             std::cref (m_config.key_value_equal()))
 {
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash, class KeyEqual, class Allocator> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::aged_unordered_container (clock_type & clock, Allocator const & alloc)
Definition at line 1568 of file aged_unordered_container.h.
     : m_config (clock, alloc)
     , m_buck (alloc)
     , m_cont (m_buck,
         std::cref (m_config.value_hash()),
             std::cref (m_config.key_value_equal()))
 {
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash, class KeyEqual, class Allocator> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::aged_unordered_container (clock_type & clock, Hash const & hash, KeyEqual const & key_eq)
Definition at line 1583 of file aged_unordered_container.h.
     : m_config (clock, hash, key_eq)
     , m_cont (m_buck,
         std::cref (m_config.value_hash()),
             std::cref (m_config.key_value_equal()))
 {
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash, class KeyEqual, class Allocator> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::aged_unordered_container (clock_type & clock, Hash const & hash, Allocator const & alloc)
Definition at line 1598 of file aged_unordered_container.h.
     : m_config (clock, hash, alloc)
     , m_buck (alloc)
     , m_cont (m_buck,
         std::cref (m_config.value_hash()),
             std::cref (m_config.key_value_equal()))
 {
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash, class KeyEqual, class Allocator> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::aged_unordered_container (clock_type & clock, KeyEqual const & key_eq, Allocator const & alloc)
Definition at line 1614 of file aged_unordered_container.h.
     : m_config (clock, key_eq, alloc)
     , m_buck (alloc)
     , m_cont (m_buck,
         std::cref (m_config.value_hash()),
             std::cref (m_config.key_value_equal()))
 {
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash, class KeyEqual, class Allocator> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::aged_unordered_container (clock_type & clock, Hash const & hash, KeyEqual const & key_eq, Allocator const & alloc)
Definition at line 1630 of file aged_unordered_container.h.
     : m_config (clock, hash, key_eq, alloc)
     , m_buck (alloc)
     , m_cont (m_buck,
         std::cref (m_config.value_hash()),
             std::cref (m_config.key_value_equal()))
 {
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash , class KeyEqual , class Allocator > template<class InputIt > beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::aged_unordered_container (InputIt first, InputIt last, clock_type & clock)
Definition at line 1648 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::insert().
     : m_config (clock)
     , m_cont (m_buck,
         std::cref (m_config.value_hash()),
             std::cref (m_config.key_value_equal()))
 {
     insert (first, last);
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash, class KeyEqual , class Allocator > template<class InputIt > beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::aged_unordered_container (InputIt first, InputIt last, clock_type & clock, Hash const & hash)
Definition at line 1663 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::insert().
     : m_config (clock, hash)
     , m_cont (m_buck,
         std::cref (m_config.value_hash()),
             std::cref (m_config.key_value_equal()))
 {
     insert (first, last);
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash, class KeyEqual, class Allocator > template<class InputIt > beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::aged_unordered_container (InputIt first, InputIt last, clock_type & clock, KeyEqual const & key_eq)
Definition at line 1679 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::insert().
     : m_config (clock, key_eq)
     , m_cont (m_buck,
         std::cref (m_config.value_hash()),
             std::cref (m_config.key_value_equal()))
 {
     insert (first, last);
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash, class KeyEqual, class Allocator> template<class InputIt > beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::aged_unordered_container (InputIt first, InputIt last, clock_type & clock, Allocator const & alloc)
Definition at line 1695 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::insert().
     : m_config (clock, alloc)
     , m_buck (alloc)
     , m_cont (m_buck,
         std::cref (m_config.value_hash()),
             std::cref (m_config.key_value_equal()))
 {
     insert (first, last);
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash, class KeyEqual, class Allocator> template<class InputIt > beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::aged_unordered_container (InputIt first, InputIt last, clock_type & clock, Hash const & hash, KeyEqual const & key_eq)
Definition at line 1712 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::insert().
     : m_config (clock, hash, key_eq)
     , m_cont (m_buck,
         std::cref (m_config.value_hash()),
             std::cref (m_config.key_value_equal()))
 {
     insert (first, last);
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash, class KeyEqual, class Allocator> template<class InputIt > beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::aged_unordered_container (InputIt first, InputIt last, clock_type & clock, Hash const & hash, Allocator const & alloc)
Definition at line 1729 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::insert().
     : m_config (clock, hash, alloc)
     , m_buck (alloc)
     , m_cont (m_buck,
         std::cref (m_config.value_hash()),
             std::cref (m_config.key_value_equal()))
 {
     insert (first, last);
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash, class KeyEqual, class Allocator> template<class InputIt > beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::aged_unordered_container (InputIt first, InputIt last, clock_type & clock, KeyEqual const & key_eq, Allocator const & alloc)
Definition at line 1747 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::insert().
     : m_config (clock, key_eq, alloc)
     , m_buck (alloc)
     , m_cont (m_buck,
         std::cref (m_config.value_hash()),
             std::cref (m_config.key_value_equal()))
 {
     insert (first, last);
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash, class KeyEqual, class Allocator> template<class InputIt > beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::aged_unordered_container (InputIt first, InputIt last, clock_type & clock, Hash const & hash, KeyEqual const & key_eq, Allocator const & alloc)
Definition at line 1765 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::insert().
     : m_config (clock, hash, key_eq, alloc)
     , m_buck (alloc)
     , m_cont (m_buck,
         std::cref (m_config.value_hash()),
             std::cref (m_config.key_value_equal()))
 {
     insert (first, last);
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash, class KeyEqual, class Allocator> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::aged_unordered_container (aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator > const & other)
Definition at line 1783 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::cbegin(), beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::cend(), and beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::insert().
     : m_config (other.m_config)
     , m_buck (m_config.alloc())
     , m_cont (m_buck,
         std::cref (m_config.value_hash()),
             std::cref (m_config.key_value_equal()))
 {
     insert (other.cbegin(), other.cend());
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash, class KeyEqual, class Allocator> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::aged_unordered_container (aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator > const & other, Allocator const & alloc)
Definition at line 1797 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::cbegin(), beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::cend(), and beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::insert().
     : m_config (other.m_config, alloc)
     , m_buck (alloc)
     , m_cont (m_buck,
         std::cref (m_config.value_hash()),
             std::cref (m_config.key_value_equal()))
 {
     insert (other.cbegin(), other.cend());
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash, class KeyEqual, class Allocator> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::aged_unordered_container (aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator > && other)
Definition at line 1812 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::chronological, and beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::chronological_t::list.
     : m_config (std::move (other.m_config))
     , m_buck (m_config.alloc())
     , m_cont (std::move (other.m_cont))
 {
     chronological.list = std::move (other.chronological.list);
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash, class KeyEqual, class Allocator> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::aged_unordered_container (aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator > && other, Allocator const & alloc)
Definition at line 1824 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::insert().
     : m_config (std::move (other.m_config), alloc)
     , m_buck (alloc)
     , m_cont (m_buck,
         std::cref (m_config.value_hash()),
             std::cref (m_config.key_value_equal()))
 {
     insert (other.cbegin(), other.cend());
     other.clear ();
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash, class KeyEqual, class Allocator> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::aged_unordered_container (std::initializer_list< value_type > init, clock_type & clock)
Definition at line 1840 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::insert().
     : m_config (clock)
     , m_cont (m_buck,
         std::cref (m_config.value_hash()),
             std::cref (m_config.key_value_equal()))
 {
     insert (init.begin(), init.end());
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash, class KeyEqual, class Allocator> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::aged_unordered_container (std::initializer_list< value_type > init, clock_type & clock, Hash const & hash)
Definition at line 1854 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::insert().
     : m_config (clock, hash)
     , m_cont (m_buck,
         std::cref (m_config.value_hash()),
             std::cref (m_config.key_value_equal()))
 {
     insert (init.begin(), init.end());
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash, class KeyEqual, class Allocator> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::aged_unordered_container (std::initializer_list< value_type > init, clock_type & clock, KeyEqual const & key_eq)
Definition at line 1869 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::insert().
     : m_config (clock, key_eq)
     , m_cont (m_buck,
         std::cref (m_config.value_hash()),
             std::cref (m_config.key_value_equal()))
 {
     insert (init.begin(), init.end());
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash, class KeyEqual, class Allocator> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::aged_unordered_container (std::initializer_list< value_type > init, clock_type & clock, Allocator const & alloc)
Definition at line 1884 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::insert().
     : m_config (clock, alloc)
     , m_buck (alloc)
     , m_cont (m_buck,
         std::cref (m_config.value_hash()),
             std::cref (m_config.key_value_equal()))
 {
     insert (init.begin(), init.end());
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash, class KeyEqual, class Allocator> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::aged_unordered_container (std::initializer_list< value_type > init, clock_type & clock, Hash const & hash, KeyEqual const & key_eq)
Definition at line 1900 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::insert().
     : m_config (clock, hash, key_eq)
     , m_cont (m_buck,
         std::cref (m_config.value_hash()),
             std::cref (m_config.key_value_equal()))
 {
     insert (init.begin(), init.end());
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash, class KeyEqual, class Allocator> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::aged_unordered_container (std::initializer_list< value_type > init, clock_type & clock, Hash const & hash, Allocator const & alloc)
Definition at line 1916 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::insert().
     : m_config (clock, hash, alloc)
     , m_buck (alloc)
     , m_cont (m_buck,
         std::cref (m_config.value_hash()),
             std::cref (m_config.key_value_equal()))
 {
     insert (init.begin(), init.end());
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash, class KeyEqual, class Allocator> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::aged_unordered_container (std::initializer_list< value_type > init, clock_type & clock, KeyEqual const & key_eq, Allocator const & alloc)
Definition at line 1933 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::insert().
     : m_config (clock, key_eq, alloc)
     , m_buck (alloc)
     , m_cont (m_buck,
         std::cref (m_config.value_hash()),
             std::cref (m_config.key_value_equal()))
 {
     insert (init.begin(), init.end());
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash, class KeyEqual, class Allocator> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::aged_unordered_container (std::initializer_list< value_type > init, clock_type & clock, Hash const & hash, KeyEqual const & key_eq, Allocator const & alloc)
Definition at line 1950 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::insert().
     : m_config (clock, hash, key_eq, alloc)
     , m_buck (alloc)
     , m_cont (m_buck,
         std::cref (m_config.value_hash()),
             std::cref (m_config.key_value_equal()))
 {
     insert (init.begin(), init.end());
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash , class KeyEqual , class Allocator > beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::~aged_unordered_container ()
Definition at line 1968 of file aged_unordered_container.h.
 {
     clear();
 }
Member Function Documentation
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash , class KeyEqual , class Allocator > template<class K , bool maybe_multi, bool maybe_map, class > std::conditional< IsMap, T, void * >::type & beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::at (K const & k)
Definition at line 2032 of file aged_unordered_container.h.
 {
     auto const iter (m_cont.find (k,
         std::cref (m_config.hash_function()),
             std::cref (m_config.key_value_equal())));
     if (iter == m_cont.end())
         throw std::out_of_range ("key not found");
     return iter->value.second;
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash , class KeyEqual , class Allocator > template<class K , bool maybe_multi, bool maybe_map, class > std::conditional< IsMap, T, void * >::type const & beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::at (K const & k) const
Definition at line 2048 of file aged_unordered_container.h.
 {
     auto const iter (m_cont.find (k,
         std::cref (m_config.hash_function()),
             std::cref (m_config.key_value_equal())));
     if (iter == m_cont.end())
         throw std::out_of_range ("key not found");
     return iter->value.second;
 }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> iterator beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::begin () inline
Definition at line 897 of file aged_unordered_container.h.
     {
         return iterator (m_cont.begin());
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> const_iterator beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::begin () const inline
Definition at line 903 of file aged_unordered_container.h.
     {
         return const_iterator (m_cont.begin ());
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> local_iterator beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::begin (size_type n) inline
Definition at line 1230 of file aged_unordered_container.h.
     {
         return local_iterator (m_cont.begin (n));
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> const_local_iterator beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::begin (size_type n) const inline
Definition at line 1235 of file aged_unordered_container.h.
     {
         return const_local_iterator (m_cont.begin (n));
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> size_type beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::bucket (Key const & k) const inline
Definition at line 1275 of file aged_unordered_container.h.
     {
         assert (bucket_count() != 0);
         return m_cont.bucket (k,
             std::cref (m_config.hash_function()));
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> size_type beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::bucket_count () const inline
Definition at line 1260 of file aged_unordered_container.h.
Referenced by beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::bucket(), and beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::would_exceed().
     {
         return m_cont.bucket_count();
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> size_type beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::bucket_size (size_type n) const inline
Definition at line 1270 of file aged_unordered_container.h.
     {
         return m_cont.bucket_size (n);
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> const_iterator beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::cbegin () const inline
Definition at line 909 of file aged_unordered_container.h.
Referenced by beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::aged_unordered_container(), and beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::operator==().
     {
         return const_iterator (m_cont.begin ());
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> const_local_iterator beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::cbegin (size_type n) const inline
Definition at line 1240 of file aged_unordered_container.h.
     {
         return const_local_iterator (m_cont.begin (n));
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> const_iterator beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::cend () const inline
Definition at line 927 of file aged_unordered_container.h.
Referenced by beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::aged_unordered_container(), and beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::operator==().
     {
         return const_iterator (m_cont.end ());
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> const_local_iterator beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::cend (size_type n) const inline
Definition at line 1255 of file aged_unordered_container.h.
     {
         return const_local_iterator (m_cont.end (n));
     }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash , class KeyEqual , class Allocator > void beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::clear ()
Definition at line 2117 of file aged_unordered_container.h.
 {
     for (auto iter (chronological.list.begin());
         iter != chronological.list.end();)
         unlink_and_delete_element (&*iter++);
     chronological.list.clear();
     m_cont.clear();
     m_buck.clear();
 }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> clock_type& beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::clock () inline
Definition at line 844 of file aged_unordered_container.h.
Referenced by beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::new_element(), and beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::touch().
     {
         return m_config.clock;
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> clock_type const& beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::clock () const inline
Definition at line 849 of file aged_unordered_container.h.
     {
         return m_config.clock;
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<class K > size_type beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::count (K const & k) const inline
Definition at line 1174 of file aged_unordered_container.h.
     {
         return m_cont.count (k, std::cref (m_config.hash_function()),
             std::cref (m_config.key_value_equal()));
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> void beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::delete_element (element * p) inline private
Definition at line 587 of file aged_unordered_container.h.
Referenced by beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::unlink_and_delete_element().
     {
         ElementAllocatorTraits::destroy (m_config.alloc(), p);
         ElementAllocatorTraits::deallocate (m_config.alloc(), p, 1);
     }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash , class KeyEqual , class Allocator > template<bool maybe_multi, class... Args> auto beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::emplace (Args &&... args) -> typename std::enable_if <! maybe_multi, std::pair <iterator, bool>>::type
Definition at line 2222 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::element::value.
Referenced by beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::insert().
 {
     maybe_rehash (1);
     // VFALCO NOTE Its unfortunate that we need to
     //             construct element here
     element* const p (new_element (
         std::forward <Args> (args)...));
     typename cont_type::insert_commit_data d;
     auto const result (m_cont.insert_check (extract (p->value),
         std::cref (m_config.hash_function()),
             std::cref (m_config.key_value_equal()), d));
     if (result.second)
     {
         chronological.list.push_back (*p);
         auto const iter (m_cont.insert_commit (*p, d));
         return std::make_pair (iterator (iter), true);
     }
     delete_element (p);
     return std::make_pair (iterator (result.first), false);
 }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<bool maybe_multi = IsMulti, class... Args> auto beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::emplace (Args &&... args) -> typename std::enable_if< maybe_multi, iterator >::type
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash , class KeyEqual , class Allocator > template<bool maybe_multi, class... Args> auto beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::emplace_hint (const_iterator const & , Args &&... args) -> typename std::enable_if <! maybe_multi, std::pair <iterator, bool>>::type
Definition at line 2271 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::element::value.
Referenced by beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::insert().
 {
     maybe_rehash (1);
     // VFALCO NOTE Its unfortunate that we need to
     //             construct element here
     element* const p (new_element (
         std::forward <Args> (args)...));
     typename cont_type::insert_commit_data d;
     auto const result (m_cont.insert_check (extract (p->value),
         std::cref (m_config.hash_function()),
             std::cref (m_config.key_value_equal()), d));
     if (result.second)
     {
         chronological.list.push_back (*p);
         auto const iter (m_cont.insert_commit (*p, d));
         return std::make_pair (iterator (iter), true);
     }
     delete_element (p);
     return std::make_pair (iterator (result.first), false);
 }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<bool maybe_multi = IsMulti, class... Args> std::enable_if<maybe_multi, iterator>::type beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::emplace_hint (const_iterator const & , Args &&... args) inline
Definition at line 1124 of file aged_unordered_container.h.
     {
         // VFALCO TODO The hint could be used for multi, to let
         //             the client order equal ranges
         return emplace <maybe_multi> (
             std::forward <Args> (args)...);
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> bool beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::empty () const inline noexcept
Definition at line 958 of file aged_unordered_container.h.
     {
         return m_cont.empty();
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> iterator beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::end () inline
Definition at line 915 of file aged_unordered_container.h.
     {
         return iterator (m_cont.end ());
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> const_iterator beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::end () const inline
Definition at line 921 of file aged_unordered_container.h.
     {
         return const_iterator (m_cont.end ());
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> local_iterator beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::end (size_type n) inline
Definition at line 1245 of file aged_unordered_container.h.
     {
         return local_iterator (m_cont.end (n));
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> const_local_iterator beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::end (size_type n) const inline
Definition at line 1250 of file aged_unordered_container.h.
     {
         return const_local_iterator (m_cont.end (n));
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<class K > std::pair<iterator, iterator> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::equal_range (K const & k) inline
Definition at line 1203 of file aged_unordered_container.h.
Referenced by beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::operator==().
     {
         auto const r (m_cont.equal_range (k,
             std::cref (m_config.hash_function()),
                 std::cref (m_config.key_value_equal())));
         return std::make_pair (iterator (r.first),
             iterator (r.second));
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<class K > std::pair<const_iterator, const_iterator> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::equal_range (K const & k) const inline
Definition at line 1215 of file aged_unordered_container.h.
     {
         auto const r (m_cont.equal_range (k,
             std::cref (m_config.hash_function()),
                 std::cref (m_config.key_value_equal())));
         return std::make_pair (const_iterator (r.first),
             const_iterator (r.second));
     }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash , class KeyEqual , class Allocator > template<bool is_const, class Iterator , class Base > detail::aged_container_iterator< false, Iterator, Base > beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::erase (detail::aged_container_iterator< is_const, Iterator, Base > const & pos)
Definition at line 2300 of file aged_unordered_container.h.
 {
     auto iter (pos.iterator());
     auto p (&*iter++);
     unlink_and_delete_element (p);
     return detail::aged_container_iterator <
         false, Iterator, Base> (iter);
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash , class KeyEqual , class Allocator > template<bool is_const, class Iterator , class Base > detail::aged_container_iterator< false, Iterator, Base > beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::erase (detail::aged_container_iterator< is_const, Iterator, Base > first, detail::aged_container_iterator< is_const, Iterator, Base > const & last)
Definition at line 2316 of file aged_unordered_container.h.
References beast.util.Iter::first().
 {
     size_type n (0);
     for (; first != last; ++n)
     {
         auto p (&*first++);
         unlink_and_delete_element (p);
     }
     return detail::aged_container_iterator <
         false, Iterator, Base> (first.iterator());
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash , class KeyEqual , class Allocator > template<class K> auto beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::erase (K const & k) -> size_type
Definition at line 2337 of file aged_unordered_container.h.
 {
     auto iter (m_cont.find (k, std::cref (m_config.hash_function()),
         std::cref (m_config.key_value_equal())));
     if (iter == m_cont.end())
         return 0;
     size_type n (0);
     for (;;)
     {
         auto p (&*iter++);
         bool const done (
             m_config (*p, extract (iter->value)));
         unlink_and_delete_element (p);
         ++n;
         if (done)
             break;
     }
     return n;
 }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> static Key const& beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::extract (value_type const & value) inline static private
Definition at line 114 of file aged_unordered_container.h.
Referenced by beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::ValueHash::operator()(), beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::KeyValueEqual::operator()(), and beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::operator==().
     {
         return aged_associative_container_extract_t <IsMap> () (value);
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<class K > iterator beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::find (K const & k) inline
Definition at line 1183 of file aged_unordered_container.h.
     {
         return iterator (m_cont.find (k,
             std::cref (m_config.hash_function()),
                 std::cref (m_config.key_value_equal())));
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<class K > const_iterator beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::find (K const & k) const inline
Definition at line 1193 of file aged_unordered_container.h.
     {
         return const_iterator (m_cont.find (k,
             std::cref (m_config.hash_function()),
                 std::cref (m_config.key_value_equal())));
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> allocator_type beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::get_allocator () const inline
Definition at line 839 of file aged_unordered_container.h.
     {
         return m_config.alloc();
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> hasher const& beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::hash_function () const inline
Definition at line 1323 of file aged_unordered_container.h.
     {
         return m_config.hash_function();
     }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash , class KeyEqual , class Allocator > template<bool maybe_multi> auto beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::insert (value_type const & value) -> typename std::enable_if <! maybe_multi, std::pair <iterator, bool>>::type
Definition at line 2134 of file aged_unordered_container.h.
References value.
Referenced by beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::aged_unordered_container(), and beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::insert().
 {
     maybe_rehash (1);
     typename cont_type::insert_commit_data d;
     auto const result (m_cont.insert_check (extract (value),
         std::cref (m_config.hash_function()),
             std::cref (m_config.key_value_equal()), d));
     if (result.second)
     {
         element* const p (new_element (value));
         chronological.list.push_back (*p);
         auto const iter (m_cont.insert_commit (*p, d));
         return std::make_pair (iterator (iter), true);
     }
     return std::make_pair (iterator (result.first), false);
 }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<bool maybe_multi = IsMulti> auto beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::insert (value_type const & value) -> typename std::enable_if< maybe_multi, iterator >::type
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash , class KeyEqual , class Allocator > template<bool maybe_multi, bool maybe_map> auto beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::insert (value_type && value) -> typename std::enable_if <! maybe_multi && ! maybe_map, std::pair <iterator, bool>>::type
Definition at line 2178 of file aged_unordered_container.h.
References value.
 {
     maybe_rehash (1);
     typename cont_type::insert_commit_data d;
     auto const result (m_cont.insert_check (extract (value),
         std::cref (m_config.hash_function()),
             std::cref (m_config.key_value_equal()), d));
     if (result.second)
     {
         element* const p (new_element (std::move (value)));
         chronological.list.push_back (*p);
         auto const iter (m_cont.insert_commit (*p, d));
         return std::make_pair (iterator (iter), true);
     }
     return std::make_pair (iterator (result.first), false);
 }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<bool maybe_multi = IsMulti, bool maybe_map = IsMap> auto beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::insert (value_type && value) -> typename std::enable_if< maybe_multi &&!maybe_map, iterator >::type
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<bool maybe_multi = IsMulti> std::enable_if<! maybe_multi, iterator>::type beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::insert (const_iterator , value_type const & value) inline
Definition at line 1013 of file aged_unordered_container.h.
     {
         // Hint is ignored but we provide the interface so
         // callers may use ordered and unordered interchangeably.
         return insert (value).first;
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<bool maybe_multi = IsMulti> std::enable_if<maybe_multi, iterator>::type beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::insert (const_iterator const & , value_type const & value) inline
Definition at line 1024 of file aged_unordered_container.h.
     {
         // VFALCO TODO The hint could be used to let
         //             the client order equal ranges
         return insert (value);
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<bool maybe_multi = IsMulti> std::enable_if<! maybe_multi, iterator>::type beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::insert (const_iterator , value_type && value) inline
Definition at line 1035 of file aged_unordered_container.h.
     {
         // Hint is ignored but we provide the interface so
         // callers may use ordered and unordered interchangeably.
         return insert (std::move (value)).first;
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<bool maybe_multi = IsMulti> std::enable_if<maybe_multi, iterator>::type beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::insert (const_iterator const & , value_type && value) inline
Definition at line 1046 of file aged_unordered_container.h.
     {
         // VFALCO TODO The hint could be used to let
         //             the client order equal ranges
         return insert (std::move (value));
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<class P , bool maybe_map = IsMap> std::enable_if<maybe_map && std::is_constructible <value_type, P&&>::value, typename std::conditional <IsMulti, iterator, std::pair <iterator, bool> >::type >::type beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::insert (P && value) inline
Definition at line 1064 of file aged_unordered_container.h.
     {
         return emplace (std::forward <P> (value));
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<class P , bool maybe_map = IsMap> std::enable_if<maybe_map && std::is_constructible <value_type, P&&>::value, typename std::conditional <IsMulti, iterator, std::pair <iterator, bool> >::type >::type beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::insert (const_iterator hint, P && value) inline
Definition at line 1080 of file aged_unordered_container.h.
     {
         return emplace_hint (hint, std::forward <P> (value));
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<class InputIt > void beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::insert (InputIt first, InputIt const & last) inline
Definition at line 1086 of file aged_unordered_container.h.
     {
         insert (first, last,
             typename std::iterator_traits <
                 InputIt>::iterator_category());
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> void beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::insert (std::initializer_list< value_type > init) inline
Definition at line 1094 of file aged_unordered_container.h.
     {
         insert (init.begin(), init.end());
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<class InputIt > void beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::insert (InputIt first, InputIt const & last, std::input_iterator_tag) inline private
Definition at line 1467 of file aged_unordered_container.h.
     {
         for (; first != last; ++first)
             insert (*first);
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<class InputIt > void beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::insert (InputIt first, InputIt const & last, std::random_access_iterator_tag) inline private
Definition at line 1476 of file aged_unordered_container.h.
     {
         auto const n (std::distance (first, last));
         maybe_rehash (n);
         insert_unchecked (first, last);
     }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash , class KeyEqual , class Allocator > template<bool maybe_multi> auto beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::insert_unchecked (value_type const & value) -> typename std::enable_if <! maybe_multi, std::pair <iterator, bool>>::type private
Definition at line 2399 of file aged_unordered_container.h.
References value.
Referenced by beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::insert(), and beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::insert_unchecked().
 {
     typename cont_type::insert_commit_data d;
     auto const result (m_cont.insert_check (extract (value),
         std::cref (m_config.hash_function()),
             std::cref (m_config.key_value_equal()), d));
     if (result.second)
     {
         element* const p (new_element (value));
         chronological.list.push_back (*p);
         auto const iter (m_cont.insert_commit (*p, d));
         return std::make_pair (iterator (iter), true);
     }
     return std::make_pair (iterator (result.first), false);
 }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<bool maybe_multi = IsMulti> auto beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::insert_unchecked (value_type const & value) -> typename std::enable_if< maybe_multi, iterator >::type private
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<class InputIt > void beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::insert_unchecked (InputIt first, InputIt const & last) inline private
Definition at line 1459 of file aged_unordered_container.h.
     {
         for (; first != last; ++first)
             insert_unchecked (*first);
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> iterator beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::iterator_to (value_type & value) inline
Definition at line 933 of file aged_unordered_container.h.
     {
         static_assert (std::is_standard_layout <element>::value,
             "must be standard layout");
         return m_cont.iterator_to (*reinterpret_cast <element*>(
              reinterpret_cast<uint8_t*>(&value)-((std::size_t)
                 std::addressof(((element*)0)->member))));
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> const_iterator beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::iterator_to (value_type const & value) const inline
Definition at line 943 of file aged_unordered_container.h.
     {
         static_assert (std::is_standard_layout <element>::value,
             "must be standard layout");
         return m_cont.iterator_to (*reinterpret_cast <element const*>(
              reinterpret_cast<uint8_t const*>(&value)-((std::size_t)
                 std::addressof(((element*)0)->member))));
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> key_equal const& beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::key_eq () const inline
Definition at line 1328 of file aged_unordered_container.h.
     {
         return m_config.key_eq();
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> float beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::load_factor () const inline
Definition at line 1288 of file aged_unordered_container.h.
Referenced by beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::maybe_rehash().
     {
         return size() /
             static_cast <float> (m_cont.bucket_count());
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> size_type beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::max_bucket_count () const inline
Definition at line 1265 of file aged_unordered_container.h.
     {
         return m_buck.max_bucket_count();
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> float beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::max_load_factor () const inline
Definition at line 1294 of file aged_unordered_container.h.
Referenced by beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::maybe_rehash(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::rehash(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::reserve(), and beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::would_exceed().
     {
         return m_buck.max_load_factor();
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> void beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::max_load_factor (float ml) inline
Definition at line 1299 of file aged_unordered_container.h.
     {
         m_buck.max_load_factor () =
             std::max (ml, m_buck.max_load_factor());
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> size_type beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::max_size () const inline noexcept
Definition at line 968 of file aged_unordered_container.h.
     {
         return m_config.max_size();
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> void beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::maybe_rehash (size_type additional) inline private
Definition at line 1436 of file aged_unordered_container.h.
Referenced by beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::insert().
     {
         if (would_exceed (additional))
             m_buck.resize (size() + additional, m_cont);
         assert (load_factor() <= max_load_factor());
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<class... Args> element* beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::new_element (Args &&... args) inline private
Definition at line 578 of file aged_unordered_container.h.
     {
         element* const p (
             ElementAllocatorTraits::allocate (m_config.alloc(), 1));
         ElementAllocatorTraits::construct (m_config.alloc(),
             p, clock().now(), std::forward <Args> (args)...);
         return p;
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<bool OtherIsMulti, bool OtherIsMap, class OtherKey , class OtherT , class OtherDuration , class OtherHash , class OtherAllocator > bool beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::operator!= (aged_unordered_container< OtherIsMulti, OtherIsMap, OtherKey, OtherT, OtherDuration, OtherHash, KeyEqual, OtherAllocator > const & other) const inline
Definition at line 1419 of file aged_unordered_container.h.
     {
         return ! (this->operator== (other));
     }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash , class KeyEqual , class Allocator > auto beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::operator= (aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator > const & other)
Definition at line 1978 of file aged_unordered_container.h.
 {
     if (this != &other)
     {
         size_type const n (other.size());
         clear();
         m_config = other.m_config;
         m_buck = Buckets (m_config.alloc());
         maybe_rehash (n);
         insert_unchecked (other.begin(), other.end());
     }
     return *this;
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash , class KeyEqual , class Allocator > auto beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::operator= (aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator > && other)
Definition at line 1998 of file aged_unordered_container.h.
 {
     size_type const n (other.size());
     clear();
     m_config = std::move (other.m_config);
     m_buck = Buckets (m_config.alloc());
     maybe_rehash (n);
     insert_unchecked (other.begin(), other.end());
     other.clear();
     return *this;
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash , class KeyEqual , class Allocator > auto beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::operator= (std::initializer_list< value_type > init)
Definition at line 2016 of file aged_unordered_container.h.
 {
     clear ();
     insert (init);
     return *this;
 }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<bool OtherIsMap, class OtherKey , class OtherT , class OtherDuration , class OtherHash , class OtherAllocator , bool maybe_multi = IsMulti> std::enable_if<! maybe_multi, bool>::type beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::operator== (aged_unordered_container< false, OtherIsMap, OtherKey, OtherT, OtherDuration, OtherHash, KeyEqual, OtherAllocator > const & other) const inline
Definition at line 1354 of file aged_unordered_container.h.
Referenced by beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::operator!=().
     {
         if (size() != other.size())
             return false;
         for (auto iter (cbegin()), last (cend()), olast (other.cend());
             iter != last; ++iter)
         {
             auto oiter (other.find (extract (*iter)));
             if (oiter == olast)
                 return false;
         }
         return true;
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<bool OtherIsMap, class OtherKey , class OtherT , class OtherDuration , class OtherHash , class OtherAllocator , bool maybe_multi = IsMulti> std::enable_if<maybe_multi, bool>::type beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::operator== (aged_unordered_container< true, OtherIsMap, OtherKey, OtherT, OtherDuration, OtherHash, KeyEqual, OtherAllocator > const & other) const inline
Definition at line 1382 of file aged_unordered_container.h.
     {
         if (size() != other.size())
             return false;
         typedef std::pair <const_iterator, const_iterator> EqRng;
         for (auto iter (cbegin()), last (cend()); iter != last;)
         {
             auto const& k (extract (*iter));
             auto const eq (equal_range (k));
             auto const oeq (other.equal_range (k));
 #if BEAST_NO_CXX14_IS_PERMUTATION
             if (std::distance (eq.first, eq.second) !=
                 std::distance (oeq.first, oeq.second) ||
                 ! std::is_permutation (eq.first, eq.second, oeq.first))
                 return false;
 #else
             if (! std::is_permutation (eq.first,
                 eq.second, oeq.first, oeq.second))
                 return false;
 #endif
             iter = eq.second;
         }
         return true;
     }
template<bool IsMulti, bool IsMap, class Key, class T , class Duration , class Hash , class KeyEqual , class Allocator > template<bool maybe_multi, bool maybe_map, class > std::conditional< IsMap, T, void * >::type & beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::operator[] (Key const & key)
Definition at line 2064 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::element::value.
 {
     maybe_rehash (1);
     typename cont_type::insert_commit_data d;
     auto const result (m_cont.insert_check (key,
         std::cref (m_config.hash_function()),
             std::cref (m_config.key_value_equal()), d));
     if (result.second)
     {
         element* const p (new_element (
             std::piecewise_construct,
                 std::forward_as_tuple (key),
                     std::forward_as_tuple ()));
         chronological.list.push_back (*p);
         m_cont.insert_commit (*p, d);
         return p->value.second;
     }
     return result.first->value.second;
 }
template<bool IsMulti, bool IsMap, class Key, class T , class Duration , class Hash , class KeyEqual , class Allocator > template<bool maybe_multi, bool maybe_map, class > std::conditional< IsMap, T, void * >::type & beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::operator[] (Key && key)
Definition at line 2090 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::element::value.
 {
     maybe_rehash (1);
     typename cont_type::insert_commit_data d;
     auto const result (m_cont.insert_check (key,
         std::cref (m_config.hash_function()),
             std::cref (m_config.key_value_equal()), d));
     if (result.second)
     {
         element* const p (new_element (
             std::piecewise_construct,
                 std::forward_as_tuple (std::move (key)),
                     std::forward_as_tuple ()));
         chronological.list.push_back (*p);
         m_cont.insert_commit (*p, d);
         return p->value.second;
     }
     return result.first->value.second;
 }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> void beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::rehash (size_type count) inline
Definition at line 1305 of file aged_unordered_container.h.
Referenced by beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::reserve().
     {
         count = std::max (count,
             size_type (size() / max_load_factor()));
         m_buck.rehash (count, m_cont);
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> void beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::reserve (size_type count) inline
Definition at line 1312 of file aged_unordered_container.h.
     {
         rehash (std::ceil (count / max_load_factor()));
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> size_type beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::size () const inline noexcept
Definition at line 963 of file aged_unordered_container.h.
Referenced by beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::load_factor(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::maybe_rehash(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::operator==(), beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::Buckets::rehash(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::rehash(), and beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::would_exceed().
     {
         return m_cont.size();
     }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash , class KeyEqual , class Allocator > void beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::swap (aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator > & other) noexcept
Definition at line 2363 of file aged_unordered_container.h.
References beast::asio::swap().
 {
     swap_data (other);
     std::swap (chronological, other.chronological);
     std::swap (m_cont, other.m_cont);
 }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<bool maybe_propagate = std::allocator_traits < Allocator>::propagate_on_container_swap::value> std::enable_if<maybe_propagate>::type beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::swap_data (aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator > & other) inline private noexcept
Definition at line 1499 of file aged_unordered_container.h.
     {
         std::swap (m_config.key_compare(), other.m_config.key_compare());
         std::swap (m_config.alloc(), other.m_config.alloc());
         std::swap (m_config.clock, other.m_config.clock);
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<bool maybe_propagate = std::allocator_traits < Allocator>::propagate_on_container_swap::value> std::enable_if<! maybe_propagate>::type beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::swap_data (aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator > & other) inline private noexcept
Definition at line 1509 of file aged_unordered_container.h.
     {
         std::swap (m_config.key_compare(), other.m_config.key_compare());
         std::swap (m_config.clock, other.m_config.clock);
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<bool is_const, class Iterator , class Base > void beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::touch (detail::aged_container_iterator< is_const, Iterator, Base > const & pos) inline
Definition at line 1154 of file aged_unordered_container.h.
Referenced by beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::touch().
     {
         touch (pos, clock().now());
     }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash , class KeyEqual , class Allocator > template<class K> auto beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::touch (K const & k) -> size_type
Definition at line 2376 of file aged_unordered_container.h.
 {
     auto const now (clock().now());
     size_type n (0);
     auto const range (equal_range (k));
     for (auto iter : range)
     {
         touch (iter, now);
         ++n;
     }
     return n;
 }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<bool is_const, class Iterator , class Base > void beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::touch (detail::aged_container_iterator< is_const, Iterator, Base > const & pos, typename clock_type::time_point const & now) inline private
Definition at line 1486 of file aged_unordered_container.h.
     {
         auto& e (*pos.iterator());
         e.when = now;
         chronological.list.erase (chronological.list.iterator_to (e));
         chronological.list.push_back (e);
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> void beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::unlink_and_delete_element (element * p) inline private
Definition at line 593 of file aged_unordered_container.h.
     {
         chronological.list.erase (
             chronological.list.iterator_to (*p));
         m_cont.erase (m_cont.iterator_to (*p));
         delete_element (p);
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> bool beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::would_exceed (size_type additional) const inline private
Definition at line 1429 of file aged_unordered_container.h.
Referenced by beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::maybe_rehash().
     {
         return size() + additional >
             bucket_count() * max_load_factor();
     }
Member Data Documentation
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> class beast::detail::aged_unordered_container::chronological_t beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::chronological
Referenced by beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::aged_unordered_container(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::touch(), and beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::unlink_and_delete_element().
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> Buckets beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::m_buck private
Definition at line 1517 of file aged_unordered_container.h.
Referenced by beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::max_bucket_count(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::max_load_factor(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::maybe_rehash(), and beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::rehash().
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> config_t beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::m_config private
Definition at line 1516 of file aged_unordered_container.h.
Referenced by beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::bucket(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::clock(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::count(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::delete_element(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::equal_range(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::find(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::get_allocator(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::hash_function(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::key_eq(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::max_size(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::new_element(), and beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::swap_data().
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> cont_type beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::m_cont mutable private
Definition at line 1518 of file aged_unordered_container.h.
Referenced by beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::begin(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::bucket(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::bucket_count(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::bucket_size(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::cbegin(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::cend(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::count(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::empty(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::end(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::equal_range(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::find(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::iterator_to(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::load_factor(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::maybe_rehash(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::rehash(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::size(), and beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::unlink_and_delete_element().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/container/detail/aged_unordered_container.h