rippled: rocksdb::RedisLists Class Reference
rocksdb::RedisLists Class Reference
#include <redis_lists.h>
Public Member Functions
RedisLists (const std::string &db_path, Options options, bool destructive=false)
Constructors.
int Length (const std::string &key)
The number of items in (list: key)
bool Index (const std::string &key, int32_t index, std::string *result)
std::vector< std::string > Range (const std::string &key, int32_t first, int32_t last)
void Print (const std::string &key)
Prints the entire (list: key), for debugging.
int InsertBefore (const std::string &key, const std::string &pivot, const std::string &value)
int InsertAfter (const std::string &key, const std::string &pivot, const std::string &value)
int PushLeft (const std::string &key, const std::string &value)
int PushRight (const std::string &key, const std::string &value)
bool Set (const std::string &key, int32_t index, const std::string &value)
bool Trim (const std::string &key, int32_t start, int32_t stop)
Delete / Remove / Pop functions.
bool PopLeft (const std::string &key, std::string *result)
bool PopRight (const std::string &key, std::string *result)
int Remove (const std::string &key, int32_t num, const std::string &value)
int RemoveFirst (const std::string &key, int32_t num, const std::string &value)
int RemoveLast (const std::string &key, int32_t num, const std::string &value)
Private Member Functions
int Insert (const std::string &key, const std::string &pivot, const std::string &value, bool insert_after)
Calls InsertBefore or InsertAfter.
Private Attributes
std::string db_name_
WriteOptions put_option_
ReadOptions get_option_
std::unique_ptr< DB > db_
Detailed Description
The Redis functionality (see http://redis.io/commands#list) All functions may THROW a RedisListException
Definition at line 22 of file redis_lists.h.
Constructor & Destructor Documentation
rocksdb::RedisLists::RedisLists (const std::string & db_path, Options options, bool destructive = false)
Constructors.
Construct a new RedisLists database, with name/path of db. Will clear the database on open iff destructive is true (default false). Otherwise, it will restore saved changes. May throw RedisListException
Definition at line 38 of file redis_lists.cc.
References db, db_, db_name_, rocksdb::DestroyDB(), rocksdb::Status::ok(), rocksdb::DB::Open(), and rocksdb::Status::ToString().
     : put_option_(),
       get_option_() {
   // Store the name of the database
   db_name_ = db_path;
   // If destructive, destroy the DB before re-opening it.
   if (destructive) {
     DestroyDB(db_name_, Options());
   }
   // Now open and deal with the db
   DB* db;
   Status s = DB::Open(options, db_name_, &db);
   if (!s.ok()) {
     std::cerr << "ERROR " << s.ToString() << std::endl;
     assert(false);
   }
   db_ = std::unique_ptr<DB>(db);
 }
Member Function Documentation
bool rocksdb::RedisLists::Index (const std::string & key, int32_t index, std::string * result)
Search the list for the (index)'th item (0-based) in (list:key) A negative index indicates: "from end-of-list" If index is within range: return true, and return the value in *result. If (index < -length OR index>=length), then index is out of range: return false (and *result is left unchanged) May throw RedisListException
Definition at line 80 of file redis_lists.cc.
References db_, rocksdb::RedisListIterator::Done(), get_option_, rocksdb::RedisListIterator::GetCurrent(), Length(), rocksdb::RedisListIterator::Skip(), and rocksdb::Slice::ToString().
Referenced by rocksdb::manual_redis_test(), and rocksdb::TEST().
{
   // Extract the string data representing the list.
   std::string data;
   db_->Get(get_option_, key, &data);
   // Handle REDIS negative indices (from the end); fast iff Length() takes O(1)
   if (index < 0) {
     index = Length(key) - (-index);  //replace (-i) with (N-i).
   }
   // Iterate through the list until the desired index is found.
   int curIndex = 0;
   RedisListIterator it(data);
   while(curIndex < index && !it.Done()) {
     ++curIndex;
     it.Skip();
   }
   // If we actually found the index
   if (curIndex == index && !it.Done()) {
     Slice elem;
     it.GetCurrent(&elem);
     if (result != NULL) {
       *result = elem.ToString();
     }
     return true;
   } else {
     return false;
   }
 }
int rocksdb::RedisLists::Insert (const std::string & key, const std::string & pivot, const std::string & value, bool insert_after) private
Calls InsertBefore or InsertAfter.
Private functions.
Definition at line 512 of file redis_lists.cc.
References db_, rocksdb::RedisListIterator::Done(), get_option_, rocksdb::RedisListIterator::GetCurrent(), rocksdb::RedisListIterator::InsertElement(), rocksdb::RedisListIterator::Length(), rocksdb::RedisListIterator::Push(), put_option_, rocksdb::RedisListIterator::Reserve(), rocksdb::RedisListIterator::Size(), rocksdb::RedisListIterator::SizeOf(), and rocksdb::RedisListIterator::WriteResult().
Referenced by InsertAfter(), and InsertBefore().
{
   // Get the original list data
   std::string data;
   db_->Get(get_option_, key, &data);
   // Construct an iterator to the data and reserve enough space for result.
   RedisListIterator it(data);
   it.Reserve(it.Size() + it.SizeOf(value));
   // Iterate through the list until we find the element we want
   Slice elem;
   bool found = false;
   while(!it.Done() && !found) {
     it.GetCurrent(&elem);
     // When we find the element, insert the element and mark found
     if (elem == pivot) {                // Found it!
       found = true;
       if (insert_after == true) {       // Skip one more, if inserting after it
         it.Push();
       }
       it.InsertElement(value);
     } else {
       it.Push();
     }
   }
   // Put the data (string) into the database
   if (found) {
     db_->Put(put_option_, key, it.WriteResult());
   }
   // Returns the new (possibly unchanged) length of the list
   return it.Length();
 }
int rocksdb::RedisLists::InsertAfter (const std::string & key, const std::string & pivot, const std::string & value)
Definition at line 196 of file redis_lists.cc.
References Insert().
Referenced by rocksdb::manual_redis_test(), and rocksdb::TEST().
{
   return Insert(key, pivot, value, true);
 }
int rocksdb::RedisLists::InsertBefore (const std::string & key, const std::string & pivot, const std::string & value)
Insert value before/after pivot in (list: key). Return the length. May throw RedisListException
Insert/Update Functions Note: The "real" insert function is private. See below.
Definition at line 191 of file redis_lists.cc.
References Insert().
Referenced by rocksdb::manual_redis_test(), and rocksdb::TEST().
{
   return Insert(key, pivot, value, false);
 }
int rocksdb::RedisLists::Length (const std::string & key)
The number of items in (list: key)
Accessors.
Definition at line 67 of file redis_lists.cc.
References db_, get_option_, and rocksdb::RedisListIterator::Length().
Referenced by Index(), rocksdb::manual_redis_test(), Range(), Remove(), Set(), rocksdb::TEST(), and Trim().
{
   // Extract the string data representing the list.
   std::string data;
   db_->Get(get_option_, key, &data);
   // Return the length
   RedisListIterator it(data);
   return it.Length();
 }
bool rocksdb::RedisLists::PopLeft (const std::string & key, std::string * result)
If list is empty, return false and leave *result unchanged. Else, remove the first/last elem, store it in *result, and return true
Definition at line 330 of file redis_lists.cc.
References db_, get_option_, rocksdb::RedisListIterator::GetCurrent(), rocksdb::RedisListIterator::Length(), put_option_, rocksdb::RedisListIterator::Reserve(), rocksdb::RedisListIterator::Size(), rocksdb::RedisListIterator::SizeOf(), rocksdb::RedisListIterator::Skip(), rocksdb::Slice::ToString(), and rocksdb::RedisListIterator::WriteResult().
Referenced by rocksdb::manual_redis_test(), and rocksdb::TEST().
{
   // Get the original list data
   std::string data;
   db_->Get(get_option_, key, &data);
   // Point to first element in the list (if it exists), and get its value/size
   RedisListIterator it(data);
   if (it.Length() > 0) {            // Proceed only if list is non-empty
     Slice elem;
     it.GetCurrent(&elem);           // Store the value of the first element
     it.Reserve(it.Size() - it.SizeOf(elem));
     it.Skip();                      // DROP the first item and move to next
     // Update the db
     db_->Put(put_option_, key, it.WriteResult());
     // Return the value
     if (result != NULL) {
       *result = elem.ToString();
     }
     return true;
   } else {
     return false;
   }
 }
bool rocksdb::RedisLists::PopRight (const std::string & key, std::string * result)
Definition at line 359 of file redis_lists.cc.
References db_, rocksdb::RedisListIterator::Done(), get_option_, rocksdb::RedisListIterator::GetCurrent(), rocksdb::RedisListIterator::Length(), rocksdb::RedisListIterator::Push(), put_option_, rocksdb::RedisListIterator::Reserve(), rocksdb::RedisListIterator::Size(), rocksdb::RedisListIterator::Skip(), and rocksdb::RedisListIterator::WriteResult().
Referenced by rocksdb::manual_redis_test(), and rocksdb::TEST().
{
   // Extract the original list data
   std::string data;
   db_->Get(get_option_, key, &data);
   // Construct an iterator to the data and move to last element
   RedisListIterator it(data);
   it.Reserve(it.Size());
   int len = it.Length();
   int curIndex = 0;
   while(curIndex < (len-1) && !it.Done()) {
     it.Push();
     ++curIndex;
   }
   // Extract and drop/skip the last element
   if (curIndex == len-1) {
     assert(!it.Done());         // Sanity check. Should not have ended here.
     // Extract and pop the element
     Slice elem;
     it.GetCurrent(&elem);       // Save value of element.
     it.Skip();                  // Skip the element
     // Write the result to the database
     db_->Put(put_option_, key, it.WriteResult());
     // Return the value
     if (result != NULL) {
       *result = elem.ToString();
     }
     return true;
   } else {
     // Must have been an empty list
     assert(it.Done() && len==0 && curIndex == 0);
     return false;
   }
 }
void rocksdb::RedisLists::Print (const std::string & key)
Prints the entire (list: key), for debugging.
Definition at line 158 of file redis_lists.cc.
References rocksdb::Slice::data(), db_, rocksdb::RedisListIterator::Done(), get_option_, rocksdb::RedisListIterator::Length(), rocksdb::Slice::size(), rocksdb::RedisListIterator::Size(), rocksdb::Slice::ToString(), and rocksdb::RedisListIterator::WriteResult().
Referenced by rocksdb::manual_redis_test().
{
   // Extract the string data representing the list.
   std::string data;
   db_->Get(get_option_, key, &data);
   // Iterate through the list and print the items
   Slice elem;
   for (RedisListIterator it(data); !it.Done(); it.Skip()) {
     it.GetCurrent(&elem);
     std::cout << "ITEM " << elem.ToString() << std::endl;
   }
   //Now print the byte data
   RedisListIterator it(data);
   std::cout << "==Printing data==" << std::endl;
   std::cout << data.size() << std::endl;
   std::cout << it.Size() << " " << it.Length() << std::endl;
   Slice result = it.WriteResult();
   std::cout << result.data() << std::endl;
   if (true) {
     std::cout << "size: " << result.size() << std::endl;
     const char* val = result.data();
     for(int i=0; i<(int)result.size(); ++i) {
       std::cout << (int)val[i] << " " << (val[i]>=32?val[i]:' ') << std::endl;
     }
     std::cout << std::endl;
   }
 }
int rocksdb::RedisLists::PushLeft (const std::string & key, const std::string & value)
Push / Insert value at beginning/end of the list. Return the length. May throw RedisListException
Definition at line 203 of file redis_lists.cc.
References db_, get_option_, rocksdb::RedisListIterator::InsertElement(), rocksdb::RedisListIterator::Length(), put_option_, rocksdb::RedisListIterator::Reserve(), rocksdb::RedisListIterator::Size(), rocksdb::RedisListIterator::SizeOf(), and rocksdb::RedisListIterator::WriteResult().
Referenced by rocksdb::manual_redis_test(), and rocksdb::TEST().
{
   // Get the original list data
   std::string data;
   db_->Get(get_option_, key, &data);
   // Construct the result
   RedisListIterator it(data);
   it.Reserve(it.Size() + it.SizeOf(value));
   it.InsertElement(value);
   // Push the data back to the db and return the length
   db_->Put(put_option_, key, it.WriteResult());
   return it.Length();
 }
int rocksdb::RedisLists::PushRight (const std::string & key, const std::string & value)
Definition at line 221 of file redis_lists.cc.
References db_, rocksdb::RedisListIterator::Done(), get_option_, rocksdb::RedisListIterator::InsertElement(), rocksdb::RedisListIterator::Length(), rocksdb::RedisListIterator::Push(), put_option_, rocksdb::RedisListIterator::Reserve(), rocksdb::RedisListIterator::Size(), rocksdb::RedisListIterator::SizeOf(), and rocksdb::RedisListIterator::WriteResult().
Referenced by rocksdb::manual_redis_test(), and rocksdb::TEST().
{
   // Get the original list data
   std::string data;
   db_->Get(get_option_, key, &data);
   // Create an iterator to the data and seek to the end.
   RedisListIterator it(data);
   it.Reserve(it.Size() + it.SizeOf(value));
   while (!it.Done()) {
     it.Push();    // Write each element as we go
   }
   // Insert the new element at the current position (the end)
   it.InsertElement(value);
   // Push it back to the db, and return length
   db_->Put(put_option_, key, it.WriteResult());
   return it.Length();
 }
std::vector< std::string > rocksdb::RedisLists::Range (const std::string & key, int32_t first, int32_t last)
Return (list: key)[first..last] (inclusive) May throw RedisListException
Definition at line 118 of file redis_lists.cc.
References rocksdb::Slice::data(), db_, rocksdb::RedisListIterator::Done(), beast.util.Iter::first(), get_option_, Length(), ripple::max(), ripple::min(), and rocksdb::Slice::size().
Referenced by rocksdb::manual_redis_test(), and rocksdb::TEST().
{
   // Extract the string data representing the list.
   std::string data;
   db_->Get(get_option_, key, &data);
   // Handle negative bounds (-1 means last element, etc.)
   int listLen = Length(key);
   if (first < 0) {
     first = listLen - (-first);           // Replace (-x) with (N-x)
   }
   if (last < 0) {
     last = listLen - (-last);
   }
   // Verify bounds (and truncate the range so that it is valid)
   first = std::max(first, 0);
   last = std::min(last, listLen-1);
   int len = std::max(last-first+1, 0);
   // Initialize the resulting list
   std::vector<std::string> result(len);
   // Traverse the list and update the vector
   int curIdx = 0;
   Slice elem;
   for (RedisListIterator it(data); !it.Done() && curIdx<=last; it.Skip()) {
     if (first <= curIdx && curIdx <= last) {
       it.GetCurrent(&elem);
       result[curIdx-first].assign(elem.data(),elem.size());
     }
     ++curIdx;
   }
   // Return the result. Might be empty
   return result;
 }
int rocksdb::RedisLists::Remove (const std::string & key, int32_t num, const std::string & value)
Remove the first (or last) num occurrences of value from the list (key) Return the number of elements removed. May throw RedisListException
Definition at line 400 of file redis_lists.cc.
References Length(), RemoveFirst(), and RemoveLast().
Referenced by rocksdb::manual_redis_test(), and rocksdb::TEST().
{
   // Negative num ==> RemoveLast; Positive num ==> Remove First
   if (num < 0) {
     return RemoveLast(key, -num, value);
   } else if (num > 0) {
     return RemoveFirst(key, num, value);
   } else {
     return RemoveFirst(key, Length(key), value);
   }
 }
int rocksdb::RedisLists::RemoveFirst (const std::string & key, int32_t num, const std::string & value)
Definition at line 414 of file redis_lists.cc.
References db_, rocksdb::RedisListIterator::Done(), get_option_, rocksdb::RedisListIterator::GetCurrent(), rocksdb::RedisListIterator::Push(), put_option_, rocksdb::RedisListIterator::Reserve(), rocksdb::RedisListIterator::Size(), rocksdb::RedisListIterator::Skip(), and rocksdb::RedisListIterator::WriteResult().
Referenced by Remove().
{
   // Ensure that the number is positive
   assert(num >= 0);
   // Extract the original list data
   std::string data;
   db_->Get(get_option_, key, &data);
   // Traverse the list, appending all but the desired occurrences of value
   int numSkipped = 0;         // Keep track of the number of times value is seen
   Slice elem;
   RedisListIterator it(data);
   it.Reserve(it.Size());
   while (!it.Done()) {
     it.GetCurrent(&elem);
     if (elem == value && numSkipped < num) {
       // Drop this item if desired
       it.Skip();
       ++numSkipped;
     } else {
       // Otherwise keep the item and proceed as normal
       it.Push();
     }
   }
   // Put the result back to the database
   db_->Put(put_option_, key, it.WriteResult());
   // Return the number of elements removed
   return numSkipped;
 }
int rocksdb::RedisLists::RemoveLast (const std::string & key, int32_t num, const std::string & value)
Definition at line 452 of file redis_lists.cc.
References db_, rocksdb::RedisListIterator::Done(), get_option_, rocksdb::RedisListIterator::GetCurrent(), ripple::min(), rocksdb::RedisListIterator::Push(), put_option_, rocksdb::RedisListIterator::Reserve(), rocksdb::RedisListIterator::Size(), rocksdb::RedisListIterator::SizeOf(), rocksdb::RedisListIterator::Skip(), and rocksdb::RedisListIterator::WriteResult().
Referenced by Remove().
{
   // Ensure that the number is positive
   assert(num >= 0);
   // Extract the original list data
   std::string data;
   db_->Get(get_option_, key, &data);
   // Temporary variable to hold the "current element" in the blocks below
   Slice elem;
   // Count the total number of occurrences of value
   int totalOccs = 0;
   for (RedisListIterator it(data); !it.Done(); it.Skip()) {
     it.GetCurrent(&elem);
     if (elem == value) {
       ++totalOccs;
     }
   }
   // Construct an iterator to the data. Reserve enough space for the result.
   RedisListIterator it(data);
   int bytesRemoved = std::min(num,totalOccs)*it.SizeOf(value);
   it.Reserve(it.Size() - bytesRemoved);
   // Traverse the list, appending all but the desired occurrences of value.
   // Note: "Drop the last k occurrences" is equivalent to
   //  "keep only the first n-k occurrences", where n is total occurrences.
   int numKept = 0;          // Keep track of the number of times value is kept
   while(!it.Done()) {
     it.GetCurrent(&elem);
     // If we are within the deletion range and equal to value, drop it.
     // Otherwise, append/keep/push it.
     if (elem == value) {
       if (numKept < totalOccs - num) {
         it.Push();
         ++numKept;
       } else {
         it.Skip();
       }
     } else {
       // Always append the others
       it.Push();
     }
   }
   // Put the result back to the database
   db_->Put(put_option_, key, it.WriteResult());
   // Return the number of elements removed
   return totalOccs - numKept;
 }
bool rocksdb::RedisLists::Set (const std::string & key, int32_t index, const std::string & value)
Set (list: key)[idx] = val. Return true on success, false on fail May throw RedisListException
Definition at line 243 of file redis_lists.cc.
References db_, rocksdb::RedisListIterator::Done(), get_option_, rocksdb::RedisListIterator::InsertElement(), Length(), rocksdb::Status::ok(), rocksdb::RedisListIterator::Push(), put_option_, rocksdb::RedisListIterator::Reserve(), rocksdb::RedisListIterator::Size(), rocksdb::RedisListIterator::SizeOf(), rocksdb::RedisListIterator::Skip(), and rocksdb::RedisListIterator::WriteResult().
Referenced by rocksdb::manual_redis_test(), and rocksdb::TEST().
{
   // Get the original list data
   std::string data;
   db_->Get(get_option_, key, &data);
   // Handle negative index for REDIS (meaning -index from end of list)
   if (index < 0) {
     index = Length(key) - (-index);
   }
   // Iterate through the list until we find the element we want
   int curIndex = 0;
   RedisListIterator it(data);
   it.Reserve(it.Size() + it.SizeOf(value));  // Over-estimate is fine
   while(curIndex < index && !it.Done()) {
     it.Push();
     ++curIndex;
   }
   // If not found, return false (this occurs when index was invalid)
   if (it.Done() || curIndex != index) {
     return false;
   }
   // Write the new element value, and drop the previous element value
   it.InsertElement(value);
   it.Skip();
   // Write the data to the database
   // Check status, since it needs to return true/false guarantee
   Status s = db_->Put(put_option_, key, it.WriteResult());
   // Success
   return s.ok();
 }
bool rocksdb::RedisLists::Trim (const std::string & key, int32_t start, int32_t stop)
Delete / Remove / Pop functions.
Trim (list: key) so that it will only contain the indices from start..stop Returns true on success May throw RedisListException
Definition at line 286 of file redis_lists.cc.
References db_, rocksdb::RedisListIterator::Done(), get_option_, Length(), ripple::max(), ripple::min(), rocksdb::Status::ok(), rocksdb::RedisListIterator::Push(), put_option_, rocksdb::RedisListIterator::Reserve(), rocksdb::RedisListIterator::Size(), rocksdb::RedisListIterator::Skip(), stop, and rocksdb::RedisListIterator::WriteResult().
Referenced by rocksdb::manual_redis_test(), and rocksdb::TEST().
{
   // Get the original list data
   std::string data;
   db_->Get(get_option_, key, &data);
   // Handle negative indices in REDIS
   int listLen = Length(key);
   if (start < 0) {
     start = listLen - (-start);
   }
   if (stop < 0) {
     stop = listLen - (-stop);
   }
   // Truncate bounds to only fit in the list
   start = std::max(start, 0);
   stop = std::min(stop, listLen-1);
   // Construct an iterator for the list. Drop all undesired elements.
   int curIndex = 0;
   RedisListIterator it(data);
   it.Reserve(it.Size());          // Over-estimate
   while(!it.Done()) {
     // If not within the range, just skip the item (drop it).
     // Otherwise, continue as usual.
     if (start <= curIndex && curIndex <= stop) {
       it.Push();
     } else {
       it.Skip();
     }
     // Increment the current index
     ++curIndex;
   }
   // Write the (possibly empty) result to the database
   Status s = db_->Put(put_option_, key, it.WriteResult());
   // Return true as long as the write succeeded
   return s.ok();
 }
Member Data Documentation
std::unique_ptr<DB> rocksdb::RedisLists::db_ private
The backend rocksdb database. Map : key –> list where a list is a sequence of elements and an element is a 4-byte integer (n), followed by n bytes of data
Definition at line 103 of file redis_lists.h.
Referenced by Index(), Insert(), Length(), PopLeft(), PopRight(), Print(), PushLeft(), PushRight(), Range(), RedisLists(), RemoveFirst(), RemoveLast(), Set(), and Trim().
std::string rocksdb::RedisLists::db_name_ private
Definition at line 95 of file redis_lists.h.
Referenced by RedisLists().
ReadOptions rocksdb::RedisLists::get_option_ private
Definition at line 97 of file redis_lists.h.
Referenced by Index(), Insert(), Length(), PopLeft(), PopRight(), Print(), PushLeft(), PushRight(), Range(), RemoveFirst(), RemoveLast(), Set(), and Trim().
WriteOptions rocksdb::RedisLists::put_option_ private
Definition at line 96 of file redis_lists.h.
Referenced by Insert(), PopLeft(), PopRight(), PushLeft(), PushRight(), RemoveFirst(), RemoveLast(), Set(), and Trim().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/utilities/redis/redis_lists.h
rippled/src/ripple/rocksdb/rocksdb/utilities/redis/redis_lists.cc