rippled: rocksdb::Status Class Reference
rocksdb::Status Class Reference
#include <status.h>
Public Member Functions
Status ()
~Status ()
Status (const Status &s)
void operator= (const Status &s)
bool ok () const
bool IsNotFound () const
bool IsCorruption () const
bool IsNotSupported () const
bool IsInvalidArgument () const
bool IsIOError () const
bool IsMergeInProgress () const
bool IsIncomplete () const
std::string ToString () const
Code code () const
Static Public Member Functions
static Status OK ()
static Status NotFound (const Slice &msg, const Slice &msg2=Slice())
static Status Corruption (const Slice &msg, const Slice &msg2=Slice())
static Status NotSupported (const Slice &msg, const Slice &msg2=Slice())
static Status InvalidArgument (const Slice &msg, const Slice &msg2=Slice())
static Status IOError (const Slice &msg, const Slice &msg2=Slice())
static Status MergeInProgress (const Slice &msg, const Slice &msg2=Slice())
static Status Incomplete (const Slice &msg, const Slice &msg2=Slice())
Private Types
enum Code {
kOk = 0, kNotFound = 1, kCorruption = 2, kNotSupported = 3,
kInvalidArgument = 4, kIOError = 5, kMergeInProgress = 6, kIncomplete = 7
}
Private Member Functions
Status (Code code, const Slice &msg, const Slice &msg2)
Static Private Member Functions
static const char * CopyState (const char *s)
Private Attributes
const char * state_
Detailed Description
Definition at line 25 of file status.h.
Member Enumeration Documentation
enum rocksdb::Status::Code private
Enumerator
kOk
kNotFound
kCorruption
kNotSupported
kInvalidArgument
kIOError
kMergeInProgress
kIncomplete
Definition at line 97 of file status.h.
             {
     kOk = 0,
     kNotFound = 1,
     kCorruption = 2,
     kNotSupported = 3,
     kInvalidArgument = 4,
     kIOError = 5,
     kMergeInProgress = 6,
     kIncomplete = 7
   };
Constructor & Destructor Documentation
rocksdb::Status::Status () inline
Definition at line 28 of file status.h.
Referenced by Corruption(), Incomplete(), InvalidArgument(), IOError(), MergeInProgress(), NotFound(), NotSupported(), and OK().
 : state_(nullptr) { }
rocksdb::Status::~Status () inline
Definition at line 29 of file status.h.
References state_.
 { delete[] state_; }
rocksdb::Status::Status (const Status & s) inline
Definition at line 118 of file status.h.
References CopyState(), and state_.
{
   state_ = (s.state_ == nullptr) ? nullptr : CopyState(s.state_);
 }
rocksdb::Status::Status (Code code, const Slice & msg, const Slice & msg2) private
Definition at line 24 of file status.cc.
References code(), rocksdb::Slice::data(), kOk, rocksdb::Slice::size(), and state_.
{
   assert(code != kOk);
   const uint32_t len1 = msg.size();
   const uint32_t len2 = msg2.size();
   const uint32_t size = len1 + (len2 ? (2 + len2) : 0);
   char* result = new char[size + 5];
   memcpy(result, &size, sizeof(size));
   result[4] = static_cast<char>(code);
   memcpy(result + 5, msg.data(), len1);
   if (len2) {
     result[5 + len1] = ':';
     result[6 + len1] = ' ';
     memcpy(result + 7 + len1, msg2.data(), len2);
   }
   state_ = result;
 }
Member Function Documentation
Code rocksdb::Status::code () const inline
Definition at line 109 of file status.h.
References kOk, and state_.
Referenced by IsCorruption(), IsIncomplete(), IsInvalidArgument(), IsIOError(), IsMergeInProgress(), IsNotFound(), IsNotSupported(), Status(), and ToString().
                     {
     return (state_ == nullptr) ? kOk : static_cast<Code>(state_[4]);
   }
const char * rocksdb::Status::CopyState (const char * s) static private
Definition at line 16 of file status.cc.
Referenced by operator=(), and Status().
{
   uint32_t size;
   memcpy(&size, state, sizeof(size));
   char* result = new char[size + 5];
   memcpy(result, state, size + 5);
   return result;
 }
static Status rocksdb::Status::Corruption (const Slice & msg, const Slice & msg2 = Slice()) inline static
Definition at line 42 of file status.h.
References kCorruption, and Status().
Referenced by rocksdb::Block::Iter::CorruptionError(), rocksdb::BlockHandle::DecodeFrom(), rocksdb::VersionEdit::DecodeFrom(), rocksdb::WALDumperCommand::DoCommand(), rocksdb::VersionSet::DumpManifest(), rocksdb::Version::Get(), rocksdb::MemTable::Get(), rocksdb::GetFileIterator(), rocksdb::WriteBatch::Iterate(), rocksdb::KeyConvertingIterator::key(), rocksdb::Block::NewIterator(), rocksdb::TransactionLogIteratorImpl::NextImpl(), rocksdb::log::LogTest::StringSource::Read(), rocksdb::ReadBlockContents(), rocksdb::DBImpl::ReadFirstLine(), rocksdb::DBImpl::Recover(), rocksdb::VersionSet::Recover(), rocksdb::DBImpl::RecoverLogFile(), rocksdb::log::Reader::ReportCorruption(), rocksdb::DBWithTTL::SanityCheckTimestamp(), rocksdb::TransactionLogIteratorImpl::SeekToStartSequence(), rocksdb::DBWithTTL::StripTS(), and rocksdb::UncompressBlockContents().
{
     return Status(kCorruption, msg, msg2);
   }
static Status rocksdb::Status::Incomplete (const Slice & msg, const Slice & msg2 = Slice()) inline static
Definition at line 57 of file status.h.
References kIncomplete, and Status().
Referenced by rocksdb::FreeList::Allocate(), rocksdb::BlockBasedTable::BlockReader(), rocksdb::TableCache::FindTable(), and rocksdb::BlockBasedTable::GetBlock().
{
     return Status(kIncomplete, msg, msg2);
   }
static Status rocksdb::Status::InvalidArgument (const Slice & msg, const Slice & msg2 = Slice()) inline static
Definition at line 48 of file status.h.
References kInvalidArgument, and Status().
Referenced by rocksdb::InternalKeyPropertiesCollector::Add(), rocksdb::UserKeyTablePropertiesCollector::Add(), rocksdb::ReduceLevelTest::CompactMemTable(), rocksdb::Footer::DecodeFrom(), rocksdb::DBImpl::DeleteFile(), rocksdb::VersionSet::DumpManifest(), rocksdb::BlockBasedTable::Open(), rocksdb::DB::Open(), rocksdb::PrefixFilterIterator::PrefixFilterIterator(), rocksdb::FakeRandomeAccessFile::Read(), rocksdb::StringSource::Read(), rocksdb::BlockBasedTable::ReadProperties(), rocksdb::DBImpl::Recover(), rocksdb::VersionSet::Recover(), rocksdb::VersionSet::ReduceNumberOfLevels(), and rocksdb::PrefixFilterIterator::Seek().
{
     return Status(kInvalidArgument, msg, msg2);
   }
static Status rocksdb::Status::IOError (const Slice & msg, const Slice & msg2 = Slice()) inline static
Definition at line 51 of file status.h.
References kIOError, and Status().
Referenced by rocksdb::BlobStore::CreateNewBucket(), rocksdb::DBImpl::DoCompactionWork(), rocksdb::DBImpl::FlushMemTableToOutputFile(), rocksdb::BlobStore::Get(), rocksdb::DBImpl::GetUpdatesSince(), rocksdb::DBImpl::InstallCompactionResults(), rocksdb::MemTableList::InstallMemtableFlushResults(), rocksdb::test::ErrorEnv::NewWritableFile(), rocksdb::SpecialEnv::NewWritableFile(), rocksdb::TransactionLogIteratorImpl::NextImpl(), rocksdb::TransactionLogIteratorImpl::OpenLogFile(), rocksdb::BlobStore::Put(), rocksdb::DBImpl::ReadFirstLine(), and rocksdb::DBImpl::ReadFirstRecord().
{
     return Status(kIOError, msg, msg2);
   }
bool rocksdb::Status::IsCorruption () const inline
Definition at line 68 of file status.h.
References code(), and kCorruption.
Referenced by rocksdb::TEST().
 { return code() == kCorruption; }
bool rocksdb::Status::IsIncomplete () const inline
Definition at line 83 of file status.h.
References code(), and kIncomplete.
Referenced by rocksdb::TableCache::Get().
 { return code() == kIncomplete; }
bool rocksdb::Status::IsInvalidArgument () const inline
Definition at line 74 of file status.h.
References code(), and kInvalidArgument.
Referenced by rocksdb::TEST().
 { return code() == kInvalidArgument; }
bool rocksdb::Status::IsIOError () const inline
Definition at line 77 of file status.h.
References code(), and kIOError.
 { return code() == kIOError; }
bool rocksdb::Status::IsMergeInProgress () const inline
Definition at line 80 of file status.h.
References code(), and kMergeInProgress.
Referenced by rocksdb::Version::Get(), and rocksdb::MemTable::Get().
 { return code() == kMergeInProgress; }
bool rocksdb::Status::IsNotFound () const inline
Definition at line 65 of file status.h.
References code(), and kNotFound.
Referenced by rocksdb::ReduceLevelTest::Get(), rocksdb::DBTest::Get(), rocksdb::SimpleTableDBTest::Get(), rocksdb::Benchmark::GetMany(), leveldb_get(), rocksdb::StressTest::MultiGet(), rocksdb::StressTest::OperateDb(), rocksdb::Benchmark::RandomWithVerify(), rocksdb::Benchmark::ReadMissing(), and rocksdb::Benchmark::ReadRandomWriteRandom().
 { return code() == kNotFound; }
bool rocksdb::Status::IsNotSupported () const inline
Definition at line 71 of file status.h.
References code(), and kNotSupported.
 { return code() == kNotSupported; }
static Status rocksdb::Status::MergeInProgress (const Slice & msg, const Slice & msg2 = Slice()) inline static
Definition at line 54 of file status.h.
References kMergeInProgress, and Status().
Referenced by rocksdb::MemTable::Get().
{
     return Status(kMergeInProgress, msg, msg2);
   }
static Status rocksdb::Status::NotFound (const Slice & msg, const Slice & msg2 = Slice()) inline static
Definition at line 39 of file status.h.
References kNotFound, and Status().
Referenced by rocksdb::Version::Get(), rocksdb::MemTable::Get(), rocksdb::VersionSet::GetMetadataForFile(), rocksdb::log::LogTest::StringSource::Skip(), rocksdb::TransactionLogIteratorImpl::UpdateCurrentWriteBatch(), and rocksdb::StressTest::VerifyDb().
{
     return Status(kNotFound, msg, msg2);
   }
static Status rocksdb::Status::NotSupported (const Slice & msg, const Slice & msg2 = Slice()) inline static
Definition at line 45 of file status.h.
References kNotSupported, and Status().
Referenced by rocksdb::DBImplReadOnly::Delete(), rocksdb::DBImpl::DeleteFile(), rocksdb::DBImplReadOnly::DisableFileDeletions(), rocksdb::DBImplReadOnly::EnableFileDeletions(), rocksdb::DBImplReadOnly::Flush(), rocksdb::ModelDB::Get(), rocksdb::DBImplReadOnly::GetLiveFiles(), rocksdb::ModelDB::GetUpdatesSince(), rocksdb::SequentialFile::InvalidateCache(), rocksdb::RandomAccessFile::InvalidateCache(), rocksdb::WritableFile::InvalidateCache(), rocksdb::DBImpl::Merge(), rocksdb::DBImplReadOnly::Merge(), rocksdb::DBWithTTL::MultiGet(), rocksdb::ModelDB::MultiGet(), rocksdb::HdfsEnv::NewSequentialFile(), rocksdb::DBImplReadOnly::Put(), rocksdb::DBImpl::ReadFirstRecord(), rocksdb::PrefixFilterIterator::SeekToLast(), and rocksdb::DBImplReadOnly::Write().
{
     return Status(kNotSupported, msg, msg2);
   }
static Status rocksdb::Status::OK () inline static
Definition at line 36 of file status.h.
References Status().
Referenced by rocksdb::InternalKeyPropertiesCollector::Add(), rocksdb::RegularKeysStartWithA::Add(), rocksdb::FreeList::Allocate(), rocksdb::WritableFile::Allocate(), rocksdb::RandomRWFile::Allocate(), rocksdb::FakeWritableFile::Append(), rocksdb::log::LogTest::StringDest::Append(), rocksdb::StringSink::Append(), rocksdb::FakeWritableFile::Close(), rocksdb::log::LogTest::StringDest::Close(), rocksdb::StringSink::Close(), rocksdb::DBImpl::CreateArchivalDirectory(), rocksdb::BlockHandle::DecodeFrom(), rocksdb::DBImpl::DeleteFile(), rocksdb::ModelDB::DeleteFile(), rocksdb::DestroyDB(), rocksdb::DBImpl::DisableFileDeletions(), rocksdb::ModelDB::DisableFileDeletions(), rocksdb::DBImpl::EnableFileDeletions(), rocksdb::ModelDB::EnableFileDeletions(), rocksdb::InternalKeyPropertiesCollector::Finish(), rocksdb::RegularKeysStartWithA::Finish(), rocksdb::SimpleTableBuilder::Finish(), rocksdb::BlockConstructor::FinishImpl(), rocksdb::MemTableConstructor::FinishImpl(), rocksdb::DBConstructor::FinishImpl(), rocksdb::FakeWritableFile::Flush(), rocksdb::log::LogTest::StringDest::Flush(), rocksdb::StringSink::Flush(), rocksdb::FreeList::Free(), rocksdb::TableCache::Get(), rocksdb::Version::Get(), rocksdb::MemTable::Get(), rocksdb::BlobStore::Get(), rocksdb::DBImpl::GetLiveFiles(), rocksdb::ModelDB::GetLiveFiles(), rocksdb::VersionSet::GetMetadataForFile(), rocksdb::SimpleTableReader::GetOffset(), rocksdb::ModelDB::GetSortedWalFiles(), rocksdb::BlockBasedTableBuilder::InsertBlockInCache(), rocksdb::WriteBatch::Iterate(), rocksdb::VersionSet::LogAndApply(), rocksdb::DBImpl::MaybeIgnoreError(), rocksdb::StressTest::MultiPrefixScan(), rocksdb::NewEmptyIterator(), rocksdb::SpecialEnv::NewWritableFile(), rocksdb::TransactionLogIteratorImpl::NextImpl(), rocksdb::TransactionLogIteratorImpl::OpenLogReader(), rocksdb::BlobStore::Put(), rocksdb::WritableFile::RangeSync(), rocksdb::FakeRandomeAccessFile::Read(), rocksdb::log::LogTest::StringSource::Read(), rocksdb::StringSource::Read(), rocksdb::ReadBlockContents(), rocksdb::DBImpl::ReadFirstLine(), rocksdb::DBImpl::ReadFirstRecord(), rocksdb::BlockBasedTable::ReadMetaBlock(), rocksdb::VersionSet::ReduceNumberOfLevels(), rocksdb::DBImpl::RetainProbableWalFiles(), rocksdb::DBWithTTL::SanityCheckTimestamp(), rocksdb::log::LogTest::StringSource::Skip(), rocksdb::MemTableIterator::status(), rocksdb::Version::LevelFileNumIterator::status(), rocksdb::SimpleTableBuilder::status(), rocksdb::ModelDB::ModelIter::status(), rocksdb::FakeWritableFile::Sync(), rocksdb::log::LogTest::StringDest::Sync(), rocksdb::StringSink::Sync(), rocksdb::BlobStore::Sync(), rocksdb::UncompressBlockContents(), and rocksdb::TransactionLogIteratorImpl::UpdateCurrentWriteBatch().
 { return Status(); }
bool rocksdb::Status::ok () const inline
Definition at line 62 of file status.h.
References state_.
Referenced by rocksdb::BlockBasedTableBuilder::Add(), rocksdb::log::Writer::AddRecord(), rocksdb::DBTest::AllEntriesFor(), rocksdb::BlobStore::Allocate(), rocksdb::Benchmark::AppendRandom(), rocksdb::DBImpl::AppendSortedWalsOfType(), rocksdb::DBWithTTL::AppendTS(), rocksdb::BlockBasedTable::ApproximateOffsetOf(), rocksdb::DBImpl::BackgroundCallCompaction(), rocksdb::DBImpl::BackgroundCallFlush(), rocksdb::DBImpl::BackgroundCompaction(), rocksdb::DBImpl::BackgroundFlush(), rocksdb::BlockBasedTable::BlockReader(), rocksdb::BuildTable(), rocksdb::DBImpl::CheckWalFileExistsAndEmpty(), rocksdb::DBImpl::CleanupCompaction(), rocksdb::CorruptionTest::Corrupt(), rocksdb::CreateLoggerFromOptions(), DataPumpThreadBody(), rocksdb::DBImpl::DBImpl(), rocksdb::Footer::DecodeFrom(), rocksdb::DBImpl::DeleteFile(), rocksdb::DestroyDB(), rocksdb::DBDumperCommand::DoCommand(), rocksdb::ManifestDumpCommand::DoCommand(), rocksdb::ReduceDBLevelsCommand::DoCommand(), rocksdb::WALDumperCommand::DoCommand(), rocksdb::GetCommand::DoCommand(), rocksdb::ScanCommand::DoCommand(), rocksdb::DBImpl::DoCompactionWork(), rocksdb::Benchmark::DoDelete(), rocksdb::Benchmark::DoWrite(), rocksdb::DoWriteStringToFile(), rocksdb::VersionSet::DumpManifest(), rocksdb::log::Writer::EmitPhysicalRecord(), rocksdb::TableCache::FindTable(), rocksdb::BlockBasedTableBuilder::Finish(), rocksdb::Constructor::Finish(), rocksdb::DBImpl::FinishCompactionOutputFile(), rocksdb::BlockBasedTableConstructor::FinishImpl(), rocksdb::DBConstructor::FinishImpl(), rocksdb::DBImpl::FlushMemTable(), rocksdb::DBImpl::FlushMemTableToOutputFile(), rocksdb::Env::GenerateUniqueId(), rocksdb::DBWithTTL::Get(), rocksdb::ReduceLevelTest::Get(), rocksdb::TableCache::Get(), rocksdb::BlockBasedTable::Get(), rocksdb::Version::Get(), rocksdb::BlobStore::Get(), rocksdb::DBTest::Get(), rocksdb::SimpleTableDBTest::Get(), rocksdb::BlockBasedTable::GetBlock(), rocksdb::BlockBasedTable::GetFilter(), rocksdb::DBImpl::GetLiveFiles(), rocksdb::Benchmark::GetMany(), rocksdb::SimpleTableReader::GetOffset(), rocksdb::ReduceDBLevelsCommand::GetOldNumOfLevels(), rocksdb::DBImpl::GetSortedWalFiles(), rocksdb::DBImpl::GetUpdatesSince(), rocksdb::Benchmark::HeapProfile(), rocksdb::MemTableList::InstallMemtableFlushResults(), rocksdb::test::Tester::IsOk(), rocksdb::DBWithTTL::KeyMayExist(), leveldb_get(), rocksdb::VersionSet::LogAndApply(), main(), rocksdb::DBImpl::MakeRoomForWrite(), rocksdb::VersionSet::ManifestContains(), rocksdb::DBImpl::MaybeIgnoreError(), rocksdb::DBImpl::MaybeScheduleLogDBDeployStats(), rocksdb::Benchmark::MergeRandom(), rocksdb::StressTest::MultiDelete(), rocksdb::DBImpl::MultiGet(), rocksdb::StressTest::MultiGet(), rocksdb::StressTest::MultiIterate(), rocksdb::StressTest::MultiPrefixScan(), rocksdb::StressTest::MultiPut(), rocksdb::DBImpl::NewDB(), rocksdb::DBConstructor::NewDB(), rocksdb::TableCache::NewIterator(), rocksdb::SpecialEnv::NewRandomAccessFile(), rocksdb::SpecialEnv::NewWritableFile(), rocksdb::TransactionLogIteratorImpl::NextImpl(), rocksdb::BlockBasedTableBuilder::ok(), rocksdb::BlockBasedTable::Open(), rocksdb::DB::Open(), rocksdb::SimpleTableReader::Open(), rocksdb::Benchmark::Open(), rocksdb::DBImpl::OpenCompactionOutputFile(), rocksdb::ReduceLevelTest::OpenDB(), OpenDb(), rocksdb::LDBCommand::OpenDB(), rocksdb::TransactionLogIteratorImpl::OpenLogReader(), rocksdb::UtilityDB::OpenTtlDB(), rocksdb::StressTest::OperateDb(), rocksdb::TtlMergeOperator::PartialMerge(), rocksdb::TableCache::PrefixMayMatch(), rocksdb::BlockBasedTable::PrefixMayMatch(), rocksdb::PrintContents(), rocksdb::DBImpl::PurgeObsoleteFiles(), rocksdb::DBImpl::PurgeObsoleteWALFiles(), rocksdb::BlobStore::Put(), rocksdb::Benchmark::RandomWithVerify(), rocksdb::ReadBlockContents(), rocksdb::ReadFileToString(), rocksdb::BlockBasedTable::ReadFilter(), rocksdb::DBImpl::ReadFirstLine(), rocksdb::DBImpl::ReadFirstRecord(), rocksdb::BlockBasedTable::ReadMetaBlock(), rocksdb::Benchmark::ReadMissing(), rocksdb::log::Reader::ReadPhysicalRecord(), rocksdb::BlockBasedTable::ReadProperties(), rocksdb::Benchmark::ReadRandomWriteRandom(), rocksdb::Benchmark::ReadRandomWriteRandomMultiGet(), rocksdb::SstFileReader::ReadSequential(), rocksdb::Benchmark::ReadWhileWriting(), rocksdb::DBImpl::Recover(), rocksdb::VersionSet::Recover(), rocksdb::DBImpl::RecoverLogFile(), rocksdb::RedisLists::RedisLists(), rocksdb::VersionSet::ReleaseCompactionFiles(), ReplicationThreadBody(), rocksdb::SanitizeOptions(), SaveError(), rocksdb::SimpleTableIterator::Seek(), rocksdb::TransactionLogIteratorImpl::SeekToStartSequence(), rocksdb::RedisLists::Set(), rocksdb::SetCurrentFile(), rocksdb::SetIdentityFile(), rocksdb::log::Reader::SkipToInitialBlock(), rocksdb::TtlTest::SleepCompactCheck(), rocksdb::PrefixFilterIterator::status(), rocksdb::KeyConvertingIterator::status(), rocksdb::BlobStore::Sync(), rocksdb::TEST(), rocksdb::BlockBasedTable::TEST_KeyInCache(), rocksdb::DBImpl::TEST_WaitForCompact(), rocksdb::TestEncodeDecode(), rocksdb::test::TmpDir(), rocksdb::RedisLists::Trim(), rocksdb::Benchmark::UpdateRandom(), rocksdb::PrefixFilterIterator::Valid(), rocksdb::StressTest::VerifyValue(), rocksdb::DBImpl::WaitForFlushMemTable(), WorkerThreadBody(), rocksdb::DBImpl::Write(), rocksdb::DBWithTTL::Write(), rocksdb::DBImpl::WriteLevel0Table(), rocksdb::DBImpl::WriteLevel0TableForRecovery(), rocksdb::Benchmark::writeOrFail(), and rocksdb::BlockBasedTableBuilder::WriteRawBlock().
 { return (state_ == nullptr); }
void rocksdb::Status::operator= (const Status & s) inline
Definition at line 121 of file status.h.
References CopyState(), and state_.
{
   // The following condition catches both aliasing (when this == &s),
   // and the common case where both s and *this are ok.
   if (state_ != s.state_) {
     delete[] state_;
     state_ = (s.state_ == nullptr) ? nullptr : CopyState(s.state_);
   }
 }
std::string rocksdb::Status::ToString () const
Definition at line 41 of file status.cc.
References code(), kCorruption, kInvalidArgument, kIOError, kMergeInProgress, kNotFound, kNotSupported, kOk, and state_.
Referenced by MergeBasedCounters::add(), rocksdb::DBTest::AllEntriesFor(), rocksdb::StringLists::Append(), rocksdb::Benchmark::AppendRandom(), rocksdb::DBImpl::BackgroundCallCompaction(), rocksdb::DBImpl::BackgroundCallFlush(), rocksdb::DBImpl::BackgroundCompaction(), rocksdb::CorruptionTest::Corrupt(), rocksdb::LogReporter::Corruption(), rocksdb::log::LogTest::ReportCollector::Corruption(), rocksdb::DBDumperCommand::DoCommand(), rocksdb::ManifestDumpCommand::DoCommand(), rocksdb::ReduceDBLevelsCommand::DoCommand(), rocksdb::WALDumperCommand::DoCommand(), rocksdb::GetCommand::DoCommand(), rocksdb::ScanCommand::DoCommand(), rocksdb::DBImpl::DoCompactionWork(), rocksdb::Benchmark::DoDelete(), rocksdb::Benchmark::DoWrite(), rocksdb::Constructor::Finish(), rocksdb::BlockBasedTableConstructor::FinishImpl(), rocksdb::ReduceLevelTest::Get(), rocksdb::StringLists::Get(), rocksdb::DBTest::Get(), rocksdb::SimpleTableDBTest::Get(), rocksdb::DBImpl::GetLiveFiles(), rocksdb::Benchmark::GetMany(), rocksdb::Benchmark::HeapProfile(), rocksdb::test::Tester::IsOk(), rocksdb::VersionSet::LogAndApply(), main(), rocksdb::VersionSet::ManifestContains(), rocksdb::DBImpl::MaybeIgnoreError(), rocksdb::Benchmark::MergeRandom(), rocksdb::StressTest::MultiDelete(), rocksdb::StressTest::MultiGet(), rocksdb::StressTest::MultiPut(), rocksdb::DBConstructor::NewDB(), rocksdb::BlockBasedTable::Open(), rocksdb::Benchmark::Open(), rocksdb::ReduceLevelTest::OpenDB(), OpenDb(), rocksdb::LDBCommand::OpenDB(), rocksdb::PrintContents(), rocksdb::DBImpl::PurgeObsoleteFiles(), rocksdb::DBImpl::PurgeObsoleteWALFiles(), rocksdb::Benchmark::RandomWithVerify(), rocksdb::DBImpl::ReadFirstLine(), rocksdb::BlockBasedTable::ReadMetaBlock(), rocksdb::BlockBasedTable::ReadProperties(), rocksdb::Benchmark::ReadRandomWriteRandom(), rocksdb::Benchmark::ReadRandomWriteRandomMultiGet(), rocksdb::Benchmark::ReadWhileWriting(), rocksdb::DBImpl::RecoverLogFile(), rocksdb::RedisLists::RedisLists(), Counters::remove(), SaveError(), rocksdb::TransactionLogIteratorImpl::SeekToStartSequence(), Counters::set(), rocksdb::TEST(), rocksdb::TestEncodeDecode(), rocksdb::test::TmpDir(), rocksdb::Benchmark::UpdateRandom(), rocksdb::DBImpl::WriteLevel0Table(), rocksdb::DBImpl::WriteLevel0TableForRecovery(), and rocksdb::Benchmark::writeOrFail().
{
   if (state_ == nullptr) {
     return "OK";
   } else {
     char tmp[30];
     const char* type;
     switch (code()) {
       case kOk:
         type = "OK";
         break;
       case kNotFound:
         type = "NotFound: ";
         break;
       case kCorruption:
         type = "Corruption: ";
         break;
       case kNotSupported:
         type = "Not implemented: ";
         break;
       case kInvalidArgument:
         type = "Invalid argument: ";
         break;
       case kIOError:
         type = "IO error: ";
         break;
       case kMergeInProgress:
         type = "Merge In Progress: ";
         break;
       default:
         snprintf(tmp, sizeof(tmp), "Unknown code(%d): ",
                  static_cast<int>(code()));
         type = tmp;
         break;
     }
     std::string result(type);
     uint32_t length;
     memcpy(&length, state_, sizeof(length));
     result.append(state_ + 5, length);
     return result;
   }
 }
Member Data Documentation
const char* rocksdb::Status::state_ private
Definition at line 95 of file status.h.
Referenced by code(), ok(), operator=(), Status(), ToString(), and ~Status().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/include/rocksdb/status.h
rippled/src/ripple/rocksdb/rocksdb/util/status.cc