rippled: beast::joyent Namespace Reference
beast::joyent Namespace Reference
Classes
struct http_parser
struct http_parser_settings
struct http_parser_url
Typedefs
typedef struct http_parser http_parser
typedef struct http_parser_settings http_parser_settings
typedef int(* http_data_cb)(http_parser *, const char *at, size_t length)
typedef int(* http_cb)(http_parser *)
Enumerations
enum http_method
enum http_parser_type { HTTP_REQUEST, HTTP_RESPONSE, HTTP_BOTH }
enum flags {
F_CHUNKED = 1 << 0, F_CONNECTION_KEEP_ALIVE = 1 << 1, F_CONNECTION_CLOSE = 1 << 2, F_TRAILING = 1 << 3,
F_UPGRADE = 1 << 4, F_SKIPBODY = 1 << 5
}
enum http_errno
enum http_parser_url_fields {
UF_SCHEMA = 0, UF_HOST = 1, UF_PORT = 2, UF_PATH = 3,
UF_QUERY = 4, UF_FRAGMENT = 5, UF_USERINFO = 6, UF_MAX = 7
}
enum state {
s_dead = 1, s_start_req_or_res, s_res_or_resp_H, s_start_res,
s_res_H, s_res_HT, s_res_HTT, s_res_HTTP,
s_res_first_http_major, s_res_http_major, s_res_first_http_minor, s_res_http_minor,
s_res_first_status_code, s_res_status_code, s_res_status_start, s_res_status,
s_res_line_almost_done, s_start_req, s_req_method, s_req_spaces_before_url,
s_req_schema, s_req_schema_slash, s_req_schema_slash_slash, s_req_server_start,
s_req_server, s_req_server_with_at, s_req_path, s_req_query_string_start,
s_req_query_string, s_req_fragment_start, s_req_fragment, s_req_http_start,
s_req_http_H, s_req_http_HT, s_req_http_HTT, s_req_http_HTTP,
s_req_first_http_major, s_req_http_major, s_req_first_http_minor, s_req_http_minor,
s_req_line_almost_done, s_header_field_start, s_header_field, s_header_value_start,
s_header_value, s_header_value_lws, s_header_almost_done, s_chunk_size_start,
s_chunk_size, s_chunk_parameters, s_chunk_size_almost_done, s_headers_almost_done,
s_headers_done, s_chunk_data, s_chunk_data_almost_done, s_chunk_data_done,
s_body_identity, s_body_identity_eof, s_message_done
}
enum header_states {
h_general = 0, h_C, h_CO, h_CON,
h_matching_connection, h_matching_proxy_connection, h_matching_content_length, h_matching_transfer_encoding,
h_matching_upgrade, h_connection, h_content_length, h_transfer_encoding,
h_upgrade, h_matching_transfer_encoding_chunked, h_matching_connection_keep_alive, h_matching_connection_close,
h_transfer_encoding_chunked, h_connection_keep_alive, h_connection_close
}
enum http_host_state {
s_http_host_dead = 1, s_http_userinfo_start, s_http_userinfo, s_http_host_start,
s_http_host_v6_start, s_http_host, s_http_host_v6, s_http_host_v6_end,
s_http_host_port_start, s_http_host_port
}
Functions
unsigned long http_parser_version (void)
void http_parser_init (http_parser *parser, enum http_parser_type type)
size_t http_parser_execute (http_parser *parser, const http_parser_settings *settings, const char *data, size_t len)
int http_should_keep_alive (const http_parser *parser)
const char * http_method_str (enum http_method m)
const char * http_errno_name (enum http_errno err)
const char * http_errno_description (enum http_errno err)
int http_parser_parse_url (const char *buf, size_t buflen, int is_connect, struct http_parser_url *u)
void http_parser_pause (http_parser *parser, int paused)
int http_body_is_final (const http_parser *parser)
int http_message_needs_eof (const http_parser *parser)
static enum state parse_url_char (enum state s, const char ch)
static enum http_host_state http_parse_host_char (enum http_host_state s, const char ch)
static int http_parse_host (const char *buf, struct http_parser_url *u, int found_at)
int http_body_is_final (const struct http_parser *parser)
http::method::methodc_t convert_http_method (joyent::http_method m)
boost::system::error_code convert_http_errno (joyent::http_errno err)
Variables
static const char * method_strings []
static const char tokens [256]
static const int8_t unhex [256]
static const uint8_t normal_url_char [32]
struct {
const char * beast::joyent::name
const char * beast::joyent::description
} http_strerror_tab []
Typedef Documentation
typedef int(* beast::joyent::http_cb)(http_parser *)
Definition at line 78 of file joyent_parser.cpp.
typedef int(* beast::joyent::http_data_cb)(http_parser *, const char *at, size_t length)
Definition at line 77 of file joyent_parser.cpp.
typedef struct http_parser beast::joyent::http_parser
Definition at line 60 of file joyent_parser.cpp.
typedef struct http_parser_settings beast::joyent::http_parser_settings
Definition at line 61 of file joyent_parser.cpp.
Enumeration Type Documentation
enum beast::joyent::flags
Enumerator
F_CHUNKED
F_CONNECTION_KEEP_ALIVE
F_CONNECTION_CLOSE
F_TRAILING
F_UPGRADE
F_SKIPBODY
Definition at line 127 of file joyent_parser.cpp.
         {
             return error_condition (ev, *this);
enum beast::joyent::header_states
Enumerator
h_general
h_C
h_CO
h_CON
h_matching_connection
h_matching_proxy_connection
h_matching_content_length
h_matching_transfer_encoding
h_matching_upgrade
h_connection
h_content_length
h_transfer_encoding
h_upgrade
h_matching_transfer_encoding_chunked
h_matching_connection_keep_alive
h_matching_connection_close
h_transfer_encoding_chunked
h_connection_keep_alive
h_connection_close
Definition at line 316 of file joyent_parser.cpp.
enum beast::joyent::http_errno
Definition at line 185 of file joyent_parser.cpp.
enum beast::joyent::http_host_state
Enumerator
s_http_host_dead
s_http_userinfo_start
s_http_userinfo
s_http_host_start
s_http_host_v6_start
s_http_host
s_http_host_v6
s_http_host_v6_end
s_http_host_port_start
s_http_host_port
Definition at line 342 of file joyent_parser.cpp.
enum beast::joyent::http_method
Definition at line 115 of file joyent_parser.cpp.
           :
         char const*
         name() const noexcept override
         {
enum beast::joyent::http_parser_type
Enumerator
HTTP_REQUEST
HTTP_RESPONSE
HTTP_BOTH
Definition at line 123 of file joyent_parser.cpp.
enum beast::joyent::http_parser_url_fields
Enumerator
UF_SCHEMA
UF_HOST
UF_PORT
UF_PATH
UF_QUERY
UF_FRAGMENT
UF_USERINFO
UF_MAX
Definition at line 237 of file joyent_parser.cpp.
enum beast::joyent::state
Enumerator
s_dead
s_start_req_or_res
s_res_or_resp_H
s_start_res
s_res_H
s_res_HT
s_res_HTT
s_res_HTTP
s_res_first_http_major
s_res_http_major
s_res_first_http_minor
s_res_http_minor
s_res_first_status_code
s_res_status_code
s_res_status_start
s_res_status
s_res_line_almost_done
s_start_req
s_req_method
s_req_spaces_before_url
s_req_schema
s_req_schema_slash
s_req_schema_slash_slash
s_req_server_start
s_req_server
s_req_server_with_at
s_req_path
s_req_query_string_start
s_req_query_string
s_req_fragment_start
s_req_fragment
s_req_http_start
s_req_http_H
s_req_http_HT
s_req_http_HTT
s_req_http_HTTP
s_req_first_http_major
s_req_http_major
s_req_first_http_minor
s_req_http_minor
s_req_line_almost_done
s_header_field_start
s_header_field
s_header_value_start
s_header_value
s_header_value_lws
s_header_almost_done
s_chunk_size_start
s_chunk_size
s_chunk_parameters
s_chunk_size_almost_done
s_headers_almost_done
s_headers_done
s_chunk_data
s_chunk_data_almost_done
s_chunk_data_done
s_body_identity
s_body_identity_eof
s_message_done
Definition at line 235 of file joyent_parser.cpp.
Function Documentation
boost::system::error_code beast::joyent::convert_http_errno (joyent::http_errno err)
Definition at line 108 of file joyent_parser.cpp.
 {
     class http_error_category_t
         : public boost::system::error_category
     {
     private:
         typedef boost::system::error_code error_code;
         typedef boost::system::error_condition error_condition;
     public:
         char const*
         name() const noexcept override
         {
             return "http_errno";
         }
         std::string
         message (int ev) const override
         {
             return joyent::http_errno_name (
                 joyent::http_errno (ev));
         }
         error_condition
         default_error_condition (int ev) const noexcept override
         {
             return error_condition (ev, *this);
         }
         bool
         equivalent (int code, error_condition const& condition
             ) const noexcept override
         {
             return default_error_condition (code) == condition;
         }
         bool
         equivalent (error_code const& code, int condition
             ) const noexcept override
         {
             return *this == code.category() &&
                 code.value() == condition;
         }
     };
     static http_error_category_t http_error_category;
     return boost::system::error_code (
         err, http_error_category);
 }
http::method::methodc_t beast::joyent::convert_http_method (joyent::http_method m)
Definition at line 62 of file joyent_parser.cpp.
References beast::http::method::http_connect, beast::http::method::http_delete, beast::http::method::http_get, beast::http::method::http_head, beast::http::method::http_options, beast::http::method::http_post, beast::http::method::http_put, and beast::http::method::http_trace.
 {
     switch (m)
     {
     case HTTP_DELETE:      return http::method::http_delete;
     case HTTP_GET:         return http::method::http_get;
     case HTTP_HEAD:        return http::method::http_head;
     case HTTP_POST:        return http::method::http_post;
     case HTTP_PUT:         return http::method::http_put;
     // pathological
     case HTTP_CONNECT:     return http::method::http_connect;
     case HTTP_OPTIONS:     return http::method::http_options;
     case HTTP_TRACE:       return http::method::http_trace;
     // webdav
     case HTTP_COPY:        return http::method::http_copy;
     case HTTP_LOCK:        return http::method::http_lock;
     case HTTP_MKCOL:       return http::method::http_mkcol;
     case HTTP_MOVE:        return http::method::http_move;
     case HTTP_PROPFIND:    return http::method::http_propfind;
     case HTTP_PROPPATCH:   return http::method::http_proppatch;
     case HTTP_SEARCH:      return http::method::http_search;
     case HTTP_UNLOCK:      return http::method::http_unlock;
     // subversion
     case HTTP_REPORT:      return http::method::http_report;
     case HTTP_MKACTIVITY:  return http::method::http_mkactivity;
     case HTTP_CHECKOUT:    return http::method::http_checkout;
     case HTTP_MERGE:       return http::method::http_merge;
     // upnp
     case HTTP_MSEARCH:     return http::method::http_msearch;
     case HTTP_NOTIFY:      return http::method::http_notify;
     case HTTP_SUBSCRIBE:   return http::method::http_subscribe;
     case HTTP_UNSUBSCRIBE: return http::method::http_unsubscribe;
     // RFC-5789
     case HTTP_PATCH:       return http::method::http_patch;
     case HTTP_PURGE:       return http::method::http_purge;
     };
     return http::method::http_get;
 }
int beast::joyent::http_body_is_final (const http_parser * parser)
Referenced by beast::http::raw_parser::do_body().
int beast::joyent::http_body_is_final (const struct http_parser * parser)
Definition at line 2225 of file joyent_parser.cpp.
const char * beast::joyent::http_errno_description (enum http_errno err)
Definition at line 1968 of file joyent_parser.cpp.
const char * beast::joyent::http_errno_name (enum http_errno err)
Definition at line 1962 of file joyent_parser.cpp.
Referenced by beast::HTTPParserImpl::http_errno_message(), and beast::HTTPParserImpl::message().
int beast::joyent::http_message_needs_eof (const http_parser * parser)
Definition at line 1902 of file joyent_parser.cpp.
const char * beast::joyent::http_method_str (enum http_method m)
Definition at line 1944 of file joyent_parser.cpp.
static int beast::joyent::http_parse_host (const char * buf, struct http_parser_url * u, int found_at) static
Definition at line 2039 of file joyent_parser.cpp.
static enum http_host_state beast::joyent::http_parse_host_char (enum http_host_state s, const char ch) static
Definition at line 1974 of file joyent_parser.cpp.
size_t beast::joyent::http_parser_execute (http_parser * parser, const http_parser_settings * settings, const char * data, size_t len)
Definition at line 573 of file joyent_parser.cpp.
Referenced by beast::HTTPParserImpl::process(), beast::http::raw_parser::process_data(), beast::HTTPParserImpl::process_eof(), and beast::http::raw_parser::process_eof().
void beast::joyent::http_parser_init (http_parser * parser, enum http_parser_type type)
Definition at line 1951 of file joyent_parser.cpp.
Referenced by beast::HTTPParserImpl::HTTPParserImpl().
int beast::joyent::http_parser_parse_url (const char * buf, size_t buflen, int is_connect, struct http_parser_url * u)
Definition at line 2112 of file joyent_parser.cpp.
Referenced by beast::ParsedURL::ParsedURL().
void beast::joyent::http_parser_pause (http_parser * parser, int paused)
Definition at line 2211 of file joyent_parser.cpp.
unsigned long beast::joyent::http_parser_version (void)
Definition at line 2230 of file joyent_parser.cpp.
References HTTP_PARSER_VERSION_MAJOR, HTTP_PARSER_VERSION_MINOR, and HTTP_PARSER_VERSION_PATCH.
int beast::joyent::http_should_keep_alive (const http_parser * parser)
Definition at line 1925 of file joyent_parser.cpp.
Referenced by beast::http::raw_parser::do_headers_done(), and beast::http::raw_parser::do_message_complete().
static enum state beast::joyent::parse_url_char (enum state s, const char ch) static
Definition at line 426 of file joyent_parser.cpp.
Variable Documentation
const char* beast::joyent::description
Definition at line 406 of file joyent_parser.cpp.
struct { ... } beast::joyent::http_strerror_tab[]
Initial value:
= {
}
const char* beast::joyent::method_strings[] static
Initial value:
=
  {
#define XX(num, name, string)
  }
Definition at line 130 of file joyent_parser.cpp.
const char* beast::joyent::name
Definition at line 405 of file joyent_parser.cpp.
const uint8_t beast::joyent::normal_url_char[32] static
Initial value:
= {
        0    |   0    |   0    |   0    |   0    |   0    |   0    |   0,
        0    | T(2)   |   0    |   0    | T(16)  |   0    |   0    |   0,
        0    |   0    |   0    |   0    |   0    |   0    |   0    |   0,
        0    |   0    |   0    |   0    |   0    |   0    |   0    |   0,
        0    |   2    |   4    |   0    |   16   |   32   |   64   |  128,
        1    |   2    |   4    |   8    |   16   |   32   |   64   |  128,
        1    |   2    |   4    |   8    |   16   |   32   |   64   |  128,
        1    |   2    |   4    |   8    |   16   |   32   |   64   |   0,
        1    |   2    |   4    |   8    |   16   |   32   |   64   |  128,
        1    |   2    |   4    |   8    |   16   |   32   |   64   |  128,
        1    |   2    |   4    |   8    |   16   |   32   |   64   |  128,
        1    |   2    |   4    |   8    |   16   |   32   |   64   |  128,
        1    |   2    |   4    |   8    |   16   |   32   |   64   |  128,
        1    |   2    |   4    |   8    |   16   |   32   |   64   |  128,
        1    |   2    |   4    |   8    |   16   |   32   |   64   |  128,
        1    |   2    |   4    |   8    |   16   |   32   |   64   |   0, }
Definition at line 199 of file joyent_parser.cpp.
const char beast::joyent::tokens[256] static
Initial value:
= {
        0,       0,       0,       0,       0,       0,       0,       0,
        0,       0,       0,       0,       0,       0,       0,       0,
        0,       0,       0,       0,       0,       0,       0,       0,
        0,       0,       0,       0,       0,       0,       0,       0,
        0,      '!',      0,      '#',     '$',     '%',     '&',    '\'',
        0,       0,      '*',     '+',      0,      '-',     '.',      0,
       '0',     '1',     '2',     '3',     '4',     '5',     '6',     '7',
       '8',     '9',      0,       0,       0,       0,       0,       0,
        0,      'a',     'b',     'c',     'd',     'e',     'f',     'g',
       'h',     'i',     'j',     'k',     'l',     'm',     'n',     'o',
       'p',     'q',     'r',     's',     't',     'u',     'v',     'w',
       'x',     'y',     'z',      0,       0,       0,      '^',     '_',
       '`',     'a',     'b',     'c',     'd',     'e',     'f',     'g',
       'h',     'i',     'j',     'k',     'l',     'm',     'n',     'o',
       'p',     'q',     'r',     's',     't',     'u',     'v',     'w',
       'x',     'y',     'z',      0,      '|',      0,      '~',       0 }
Definition at line 145 of file joyent_parser.cpp.
const int8_t beast::joyent::unhex[256] static
Initial value:
=
  {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
  ,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
  ,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
  , 0, 1, 2, 3, 4, 5, 6, 7, 8, 9,-1,-1,-1,-1,-1,-1
  ,-1,10,11,12,13,14,15,-1,-1,-1,-1,-1,-1,-1,-1,-1
  ,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
  ,-1,10,11,12,13,14,15,-1,-1,-1,-1,-1,-1,-1,-1,-1
  ,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
  }
Definition at line 180 of file joyent_parser.cpp.