rippled: ripple::version Namespace Reference
ripple::version Namespace Reference
Classes
struct CheckLibraryVersions_test
Typedefs
typedef unsigned long long VersionNumber
Functions
std::string boostVersion (VersionNumber boostVersion=BOOST_VERSION)
std::string openSSLVersion (VersionNumber openSSLVersion=OPENSSL_VERSION_NUMBER)
void checkVersion (std::string name, std::string required, std::string actual)
void checkBoost (std::string version=boostVersion())
void checkOpenSSL (std::string version=openSSLVersion())
void checkLibraryVersions ()
BEAST_DEFINE_TESTSUITE (CheckLibraryVersions, ripple_basics, ripple)
Variables
static const char boostMinimal [] = "1.55.0"
static const char openSSLMinimal [] = "1.0.1-g"
Typedef Documentation
typedef unsigned long long ripple::version::VersionNumber
Both Boost and OpenSSL have integral version numbers.
Definition at line 34 of file CheckLibraryVersions.cpp.
Function Documentation
ripple::version::BEAST_DEFINE_TESTSUITE (CheckLibraryVersions , ripple_basics , ripple)
std::string ripple::version::boostVersion (VersionNumber boostVersion = BOOST_VERSION)
Definition at line 42 of file CheckLibraryVersions.cpp.
Referenced by ripple::version::CheckLibraryVersions_test::print_message(), and ripple::version::CheckLibraryVersions_test::test_bad_boost().
 {
     std::stringstream ss;
     ss << (boostVersion / 100000) << "."
        << (boostVersion / 100 % 1000) << "."
        << (boostVersion % 100);
     return ss.str();
 }
void ripple::version::checkBoost (std::string version = boostVersion())
Definition at line 82 of file CheckLibraryVersions.cpp.
References boostMinimal, checkVersion(), and version.
Referenced by checkLibraryVersions(), and ripple::version::CheckLibraryVersions_test::test_bad_boost().
 {
     checkVersion("Boost", boostMinimal, version);
 }
void ripple::version::checkLibraryVersions ()
Check all library versions against Ripple's version requirements.
Throws std::runtime_error if one or more libraries are out-of-date and do not meet the version requirements.
Definition at line 92 of file CheckLibraryVersions.cpp.
References checkBoost(), and checkOpenSSL().
Referenced by ripple::version::CheckLibraryVersions_test::run(), and ripple::run().
 {
     checkBoost();
     checkOpenSSL();
 }
void ripple::version::checkOpenSSL (std::string version = openSSLVersion())
Definition at line 87 of file CheckLibraryVersions.cpp.
References checkVersion(), openSSLMinimal, and version.
Referenced by checkLibraryVersions(), and ripple::version::CheckLibraryVersions_test::test_bad_ssl().
 {
     checkVersion("OpenSSL", openSSLMinimal, version);
 }
void ripple::version::checkVersion (std::string name, std::string required, std::string actual)
Definition at line 63 of file CheckLibraryVersions.cpp.
References beast::SemanticVersion::parse().
Referenced by checkBoost(), and checkOpenSSL().
 {
     beast::SemanticVersion r, a;
     if (!r.parse(required)) {
         throw std::runtime_error("Didn't understand required version of " +
                                  name + ": " + required);
     }
     if (!a.parse(actual)) {
         throw std::runtime_error("Didn't understand actual version of " +
                                  name + ": " + required);
     }
     if (a < r) {
         throw std::runtime_error("Your " + name + " library is out of date.\n" +
                                  "Your version: " + actual + "\n" +
                                  "Required version: " +  "\n");
     }
 }
std::string ripple::version::openSSLVersion (VersionNumber openSSLVersion = OPENSSL_VERSION_NUMBER)
Definition at line 51 of file CheckLibraryVersions.cpp.
Referenced by ripple::version::CheckLibraryVersions_test::print_message(), and ripple::version::CheckLibraryVersions_test::test_bad_ssl().
 {
     std::stringstream ss;
     ss << (openSSLVersion / 0x10000000L) << "."
        << (openSSLVersion / 0x100000 % 0x100) << "."
        << (openSSLVersion / 0x1000 % 0x100);
     auto patchNo = openSSLVersion % 0x10;
     if (patchNo)
         ss << '-' << char('a' + patchNo - 1);
     return ss.str();
 }
Variable Documentation
const char ripple::version::boostMinimal[] = "1.55.0" static
Minimal required boost version.
Definition at line 37 of file CheckLibraryVersions.cpp.
Referenced by checkBoost(), and ripple::version::CheckLibraryVersions_test::print_message().
const char ripple::version::openSSLMinimal[] = "1.0.1-g" static
Minimal required OpenSSL version.
Definition at line 40 of file CheckLibraryVersions.cpp.
Referenced by checkOpenSSL(), and ripple::version::CheckLibraryVersions_test::print_message().