rippled: ripple::CountedObjects::CounterBase Class Reference
ripple::CountedObjects::CounterBase Class Reference abstract
#include <CountedObject.h>
Public Member Functions
CounterBase ()
virtual ~CounterBase ()
int increment () noexcept
int decrement () noexcept
int getCount () const noexcept
CounterBase * getNext () const noexcept
virtual char const * getName () const =0
Protected Attributes
std::atomic< int > m_count
CounterBase * m_next
Private Member Functions
virtual void checkPureVirtual () const =0
Detailed Description
Implementation for CountedObject.
Definition at line 43 of file CountedObject.h.
Constructor & Destructor Documentation
ripple::CountedObjects::CounterBase::CounterBase ()
Definition at line 71 of file CountedObject.cpp.
References ripple::CountedObjects::getInstance(), instance, ripple::CountedObjects::m_count, ripple::CountedObjects::m_head, and m_next.
     : m_count (0)
 {
     // Insert ourselves at the front of the lock-free linked list
     CountedObjects& instance = CountedObjects::getInstance ();
     CounterBase* head;
     do
     {
         head = instance.m_head.load ();
         m_next = head;
     }
     while (instance.m_head.exchange (this) != head);
     ++instance.m_count;
 }
ripple::CountedObjects::CounterBase::~CounterBase () virtual
Definition at line 89 of file CountedObject.cpp.
 {
     // VFALCO NOTE If the counters are destroyed before the singleton,
     //             undefined behavior will result if the singleton's member
     //             functions are called.
 }
Member Function Documentation
virtual void ripple::CountedObjects::CounterBase::checkPureVirtual () const private pure virtual
Implemented in ripple::CountedObject< Object >::Counter.
int ripple::CountedObjects::CounterBase::decrement () inline noexcept
Definition at line 55 of file CountedObject.h.
References m_count.
Referenced by ripple::CountedObject< STObject >::~CountedObject().
         {
             return --m_count;
         }
int ripple::CountedObjects::CounterBase::getCount () const inline noexcept
Definition at line 60 of file CountedObject.h.
References m_count.
Referenced by ripple::CountedObjects::getCounts().
         {
             return m_count.load ();
         }
virtual char const* ripple::CountedObjects::CounterBase::getName () const pure virtual
Implemented in ripple::CountedObject< Object >::Counter.
Referenced by ripple::CountedObjects::getCounts().
CounterBase* ripple::CountedObjects::CounterBase::getNext () const inline noexcept
Definition at line 65 of file CountedObject.h.
References m_next.
Referenced by ripple::CountedObjects::getCounts().
         {
             return m_next;
         }
int ripple::CountedObjects::CounterBase::increment () inline noexcept
Definition at line 50 of file CountedObject.h.
References m_count.
Referenced by ripple::CountedObject< STObject >::CountedObject().
         {
             return ++m_count;
         }
Member Data Documentation
std::atomic<int> ripple::CountedObjects::CounterBase::m_count protected
Definition at line 76 of file CountedObject.h.
Referenced by decrement(), getCount(), and increment().
CounterBase* ripple::CountedObjects::CounterBase::m_next protected
Definition at line 77 of file CountedObject.h.
Referenced by CounterBase(), and getNext().
The documentation for this class was generated from the following files:
rippled/src/ripple_basics/utility/CountedObject.h
rippled/src/ripple_basics/utility/CountedObject.cpp