rippled: beast::Workers::Worker Class Reference
beast::Workers::Worker Class Reference
Public Member Functions
Worker (Workers &workers, String const &threadName)
~Worker ()
Public Member Functions inherited from beast::LockFreeStack< Element, Tag >::Node
Node ()
Node (Node *next)
Public Member Functions inherited from beast::Thread
Thread (const String &threadName)
virtual ~Thread ()
void startThread ()
void startThread (int priority)
bool stopThread (int timeOutMilliseconds=-1)
void stopThreadAsync ()
bool isThreadRunning () const
void signalThreadShouldExit ()
bool threadShouldExit () const
bool waitForThreadToExit (int timeOutMilliseconds=-1) const
bool setPriority (int priority)
void setAffinityMask (std::uint32_t affinityMask)
bool wait (int timeOutMilliseconds=-1) const
void notify () const
ThreadID getThreadId () const noexcept
const String & getThreadName () const
Private Member Functions
void run ()
Private Attributes
Workers & m_workers
Additional Inherited Members
Public Types inherited from beast::Thread
typedef void * ThreadID
Static Public Member Functions inherited from beast::Thread
static bool setCurrentThreadPriority (int priority)
static void setCurrentThreadAffinityMask (std::uint32_t affinityMask)
static void sleep (int milliseconds)
static void yield ()
static ThreadID getCurrentThreadId ()
static Thread * getCurrentThread ()
static void setCurrentThreadName (const String &newThreadName)
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
Definition at line 114 of file Workers.h.
Constructor & Destructor Documentation
beast::Workers::Worker::Worker (Workers & workers, String const & threadName)
Definition at line 138 of file Workers.cpp.
References beast::Thread::startThread().
     : Thread (threadName)
     , m_workers (workers)
 {
     startThread ();
 }
beast::Workers::Worker::~Worker ()
Definition at line 145 of file Workers.cpp.
 {
     stopThread ();
 }
Member Function Documentation
void beast::Workers::Worker::run () private virtual
Must be implemented to perform the thread's actual code.
Remember that the thread must regularly check the threadShouldExit() method whilst running, and if this returns true it should return from the run() method as soon as possible to avoid being forcibly killed.
See Also
threadShouldExit, startThread
Implements beast::Thread.
Definition at line 150 of file Workers.cpp.
References beast::Thread::getThreadName(), and beast::Thread::setCurrentThreadName().
 {
     while (! threadShouldExit ())
     {
         // Increment the count of active workers, and if
         // we are the first one then reset the "all paused" event
         //
         if (++m_workers.m_activeCount == 1)
             m_workers.m_allPaused.reset ();
         for (;;)
         {
             // Acquire a task or "internal task."
             //
             m_workers.m_semaphore.wait ();
             // See if there's a pause request. This
             // counts as an "internal task."
             //
             int pauseCount = m_workers.m_pauseCount.get ();
             if (pauseCount > 0)
             {
                 // Try to decrement
                 pauseCount = --m_workers.m_pauseCount;
                 if (pauseCount >= 0)
                 {
                     // We got paused
                     break;
                 }
                 else
                 {
                     // Undo our decrement
                     ++m_workers.m_pauseCount;
                 }
             }
             // We couldn't pause so we must have gotten
             // unblocked in order to process a task.
             //
             ++m_workers.m_runningTaskCount;
             m_workers.m_callback.processTask ();
             --m_workers.m_runningTaskCount;
             // Put the name back in case the callback changed it
             Thread::setCurrentThreadName (Thread::getThreadName());
         }
         // Any worker that goes into the paused list must
         // guarantee that it will eventually block on its
         // event object.
         //
         m_workers.m_paused.push_front (this);
         // Decrement the count of active workers, and if we
         // are the last one then signal the "all paused" event.
         //
         if (--m_workers.m_activeCount == 0)
             m_workers.m_allPaused.signal ();
         Thread::setCurrentThreadName ("(" + getThreadName() + ")");
         // [1] We will be here when the paused list is popped
         //
         // We block on our event object, a requirement of being
         // put into the paused list.
         //
         // This will get signaled on either a reactivate or a stopThread()
         //
         wait ();
     }
 }
Member Data Documentation
Workers& beast::Workers::Worker::m_workers private
Definition at line 128 of file Workers.h.
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_core/thread/Workers.h
rippled/src/beast/modules/beast_core/thread/Workers.cpp