rippled: MergeBasedCounters Class Reference
MergeBasedCounters Class Reference
Public Member Functions
MergeBasedCounters (std::shared_ptr< DB > db, uint64_t defaultCount=0)
virtual bool add (const string &key, uint64_t value) override
Public Member Functions inherited from Counters
Counters (std::shared_ptr< DB > db, uint64_t defaultCount=0)
virtual ~Counters ()
bool set (const string &key, uint64_t value)
bool remove (const string &key)
bool get (const string &key, uint64_t *value)
void assert_set (const string &key, uint64_t value)
void assert_remove (const string &key)
uint64_t assert_get (const string &key)
void assert_add (const string &key, uint64_t value)
Private Attributes
WriteOptions merge_option_
Additional Inherited Members
Protected Attributes inherited from Counters
std::shared_ptr< DB > db_
WriteOptions put_option_
ReadOptions get_option_
WriteOptions delete_option_
uint64_t default_
Detailed Description
Definition at line 157 of file merge_test.cc.
Constructor & Destructor Documentation
MergeBasedCounters::MergeBasedCounters (std::shared_ptr< DB > db, uint64_t defaultCount = 0) inline explicit
Definition at line 162 of file merge_test.cc.
       : Counters(db, defaultCount),
         merge_option_() {
   }
Member Function Documentation
virtual bool MergeBasedCounters::add (const string & key, uint64_t value) inline override virtual
Reimplemented from Counters.
Definition at line 168 of file merge_test.cc.
References db_, rocksdb::EncodeFixed64(), rocksdb::DBImpl::Merge(), and rocksdb::Status::ToString().
{
     char encoded[sizeof(uint64_t)];
     EncodeFixed64(encoded, value);
     Slice slice(encoded, sizeof(uint64_t));
     auto s = db_->Merge(merge_option_, key, slice);
     if (s.ok()) {
       return true;
     } else {
       cerr << s.ToString() << endl;
       return false;
     }
   }
Member Data Documentation
WriteOptions MergeBasedCounters::merge_option_ private
Definition at line 159 of file merge_test.cc.
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/db/merge_test.cc