rippled: ripple::PeerDoorImp Class Reference
ripple::PeerDoorImp Class Reference
Public Member Functions
PeerDoorImp (Kind kind, OverlayImpl &overlay, boost::asio::ip::tcp::endpoint const &ep, boost::asio::io_service &io_service)
void stop ()
void async_accept ()
void handleTimer (boost::system::error_code ec)
void handleAccept (boost::system::error_code ec)
Public Member Functions inherited from ripple::PeerDoor
virtual ~PeerDoor ()=default
Private Attributes
OverlayImpl & m_overlay
beast::Journal m_journal
Kind m_kind
boost::asio::ip::tcp::acceptor m_acceptor
boost::asio::deadline_timer m_acceptDelay
NativeSocketType m_socket
Additional Inherited Members
Public Types inherited from ripple::PeerDoor
enum Kind { sslRequired, sslAndPROXYRequired }
Detailed Description
Definition at line 27 of file PeerDoor.cpp.
Constructor & Destructor Documentation
ripple::PeerDoorImp::PeerDoorImp (Kind kind, OverlayImpl & overlay, boost::asio::ip::tcp::endpoint const & ep, boost::asio::io_service & io_service) inline
Definition at line 40 of file PeerDoor.cpp.
References beast::IPAddressConversion::from_asio(), and beast::Journal::info.
         : m_overlay (overlay)
         , m_journal (LogPartition::getJournal <PeerDoor> ())
         , m_kind (kind)
         , m_acceptor (io_service, ep)
         , m_acceptDelay (io_service)
         , m_socket (io_service)
     {
         m_journal.info <<
             "Listening on " <<
             beast::IPAddressConversion::from_asio (
                 m_acceptor.local_endpoint()) <<
             ((m_kind == sslAndPROXYRequired) ? " (proxy)" : "");
         async_accept ();
     }
Member Function Documentation
void ripple::PeerDoorImp::async_accept () inline
Definition at line 77 of file PeerDoor.cpp.
References handleAccept().
     {
         m_acceptor.async_accept (m_socket,
             boost::bind (&PeerDoorImp::handleAccept, this,
                 boost::asio::placeholders::error));
     }
void ripple::PeerDoorImp::handleAccept (boost::system::error_code ec) inline
Definition at line 98 of file PeerDoor.cpp.
References ripple::OverlayImpl::accept(), handleTimer(), and beast::Journal::info.
Referenced by async_accept().
     {
         if (ec == boost::asio::error::operation_aborted)
             return;
         bool delay = false;
         if (! ec)
         {
             bool const proxyHandshake (m_kind == sslAndPROXYRequired);
             m_overlay.accept (proxyHandshake, std::move(m_socket));
         }
         else
         {
             if (ec == boost::system::errc::too_many_files_open)
                 delay = true;
             m_journal.info << "Error " << ec;
         }
         m_socket.close(ec);
         if (delay)
         {
             m_acceptDelay.expires_from_now (boost::posix_time::milliseconds (500));
             m_acceptDelay.async_wait (boost::bind (&PeerDoorImp::handleTimer,
                 this, boost::asio::placeholders::error));
         }
         else
         {
             async_accept ();
         }
     }
void ripple::PeerDoorImp::handleTimer (boost::system::error_code ec) inline
Definition at line 88 of file PeerDoor.cpp.
Referenced by handleAccept().
     {
         if (ec == boost::asio::error::operation_aborted)
             return;
         async_accept ();
     }
void ripple::PeerDoorImp::stop (void) inline virtual
Implements ripple::PeerDoor.
Definition at line 60 of file PeerDoor.cpp.
     {
         {
             boost::system::error_code ec;
             m_acceptDelay.cancel (ec);
         }
         {
             boost::system::error_code ec;
             m_acceptor.cancel (ec);
         }
     }
Member Data Documentation
boost::asio::deadline_timer ripple::PeerDoorImp::m_acceptDelay private
Definition at line 36 of file PeerDoor.cpp.
boost::asio::ip::tcp::acceptor ripple::PeerDoorImp::m_acceptor private
Definition at line 35 of file PeerDoor.cpp.
beast::Journal ripple::PeerDoorImp::m_journal private
Definition at line 33 of file PeerDoor.cpp.
Kind ripple::PeerDoorImp::m_kind private
Definition at line 34 of file PeerDoor.cpp.
OverlayImpl& ripple::PeerDoorImp::m_overlay private
Definition at line 32 of file PeerDoor.cpp.
NativeSocketType ripple::PeerDoorImp::m_socket private
Definition at line 37 of file PeerDoor.cpp.
The documentation for this class was generated from the following file:
rippled/src/ripple_overlay/impl/PeerDoor.cpp