rippled: beast::asio::HTTPClientType::Session Class Reference
beast::asio::HTTPClientType::Session Class Reference
Classes
struct State
Public Types
typedef SharedPtr< Session > Ptr
typedef boost::asio::ip::tcp Protocol
typedef boost::system::error_code error_code
typedef HTTPClientBase::error_type error_type
typedef HTTPClientBase::value_type value_type
typedef HTTPClientBase::result_type result_type
typedef Protocol::resolver resolver
typedef Protocol::socket socket
typedef resolver::query query
typedef resolver::iterator iterator
typedef iterator::value_type resolver_entry
typedef SharedData< State > SharedState
Public Member Functions
Session (HTTPClientType &owner, boost::asio::io_service &io_service, URL const &url, asio::shared_handler< void(result_type)> const &handler, double timeoutSeconds, std::size_t messageLimitBytes, std::size_t bufferSize)
~Session ()
void cancel ()
void cancel_all ()
void failed (error_code ec)
void async_read_some ()
void handle_start ()
void handle_timer (error_code ec)
void handle_resolve (error_code ec, iterator iter)
void handle_connect (error_code ec)
void handle_handshake (error_code ec)
void handle_write (error_code ec, std::size_t)
void handle_read (error_code ec, std::size_t bytes_transferred)
void handle_shutdown (error_code ec)
Public Member Functions inherited from beast::SharedObject
void incReferenceCount () const noexcept
void decReferenceCount () const
int getReferenceCount () const noexcept
Public Attributes
HTTPClientType & m_owner
boost::asio::io_service & m_io_service
boost::asio::io_service::strand m_strand
boost::asio::deadline_timer m_timer
resolver m_resolver
socket m_socket
asio::shared_handler< void(result_type)> m_handler
URL m_url
boost::asio::ssl::context m_context
MemoryBlock m_buffer
HTTPResponseParser m_parser
std::size_t m_messageLimitBytes
std::size_t m_bytesReceived
String m_get_string
WaitableEvent m_done
std::unique_ptr< abstract_socket > m_stream
SharedState m_state
Additional Inherited Members
Protected Member Functions inherited from beast::SharedObject
SharedObject ()
virtual ~SharedObject ()
virtual void destroy () const
void resetReferenceCount () noexcept
Detailed Description
Definition at line 160 of file HTTPClientType.cpp.
Member Typedef Documentation
typedef boost::system::error_code beast::asio::HTTPClientType::Session::error_code
Definition at line 167 of file HTTPClientType.cpp.
typedef HTTPClientBase::error_type beast::asio::HTTPClientType::Session::error_type
Definition at line 168 of file HTTPClientType.cpp.
typedef resolver::iterator beast::asio::HTTPClientType::Session::iterator
Definition at line 175 of file HTTPClientType.cpp.
typedef boost::asio::ip::tcp beast::asio::HTTPClientType::Session::Protocol
Definition at line 166 of file HTTPClientType.cpp.
typedef SharedPtr<Session> beast::asio::HTTPClientType::Session::Ptr
Definition at line 165 of file HTTPClientType.cpp.
typedef resolver::query beast::asio::HTTPClientType::Session::query
Definition at line 174 of file HTTPClientType.cpp.
typedef Protocol::resolver beast::asio::HTTPClientType::Session::resolver
Definition at line 172 of file HTTPClientType.cpp.
typedef iterator::value_type beast::asio::HTTPClientType::Session::resolver_entry
Definition at line 176 of file HTTPClientType.cpp.
typedef HTTPClientBase::result_type beast::asio::HTTPClientType::Session::result_type
Definition at line 170 of file HTTPClientType.cpp.
typedef SharedData<State> beast::asio::HTTPClientType::Session::SharedState
Definition at line 207 of file HTTPClientType.cpp.
typedef Protocol::socket beast::asio::HTTPClientType::Session::socket
Definition at line 173 of file HTTPClientType.cpp.
typedef HTTPClientBase::value_type beast::asio::HTTPClientType::Session::value_type
Definition at line 169 of file HTTPClientType.cpp.
Constructor & Destructor Documentation
beast::asio::HTTPClientType::Session::Session (HTTPClientType & owner, boost::asio::io_service & io_service, URL const & url, asio::shared_handler< void(result_type)> const & handler, double timeoutSeconds, std::size_t messageLimitBytes, std::size_t bufferSize) inline
Definition at line 212 of file HTTPClientType.cpp.
References beast::asio::HTTPClientType::add(), handle_start(), handle_timer(), m_context, m_handler, m_owner, m_strand, m_timer, and beast::asio::wrap_handler().
             : m_owner (owner)
             , m_io_service (io_service)
             , m_strand (io_service)
             , m_timer (io_service)
             , m_resolver (io_service)
             , m_socket (io_service)
             , m_handler (handler)
             , m_url (url)
             , m_context (boost::asio::ssl::context::sslv23)
             , m_buffer (bufferSize)
             , m_messageLimitBytes (messageLimitBytes)
             , m_bytesReceived (0)
         {
             m_owner.add (*this);
             // Configure the SSL context for certificate verification
             m_context.set_default_verify_paths ();
             m_context.set_options (
                 boost::asio::ssl::context::no_sslv2 |
                 boost::asio::ssl::context::single_dh_use |
                 boost::asio::ssl::context::default_workarounds);
             //m_context.set_verify_mode (boost::asio::ssl::verify_peer);
             // Set the timer if a timeout is requested
             if (timeoutSeconds > 0)
             {
                 m_timer.expires_from_now (
                     boost::posix_time::milliseconds (
                         long (timeoutSeconds * 1000)));
                 m_timer.async_wait (m_strand.wrap (asio::wrap_handler (
                     std::bind (&Session::handle_timer, Ptr(this),
                         asio::placeholders::error), m_handler)));
             }
             // Start the operation on an io_service thread
             io_service.dispatch (m_strand.wrap (asio::wrap_handler (
                 std::bind (&Session::handle_start, Ptr(this)), m_handler)));
         }
beast::asio::HTTPClientType::Session::~Session () inline
Definition at line 259 of file HTTPClientType.cpp.
References beast::asio::bind_handler(), beast::asio::HTTPClientType::Session::State::error, m_handler, m_io_service, m_owner, m_state, beast::asio::HTTPClientType::remove(), and beast::asio::HTTPClientType::Session::State::response.
         {
             State result;
             {
                 SharedState::ConstAccess state (m_state);
                 result = *state;
             }
             m_io_service.post (bind_handler (m_handler,
                 std::make_pair (result.error, result.response)));
             m_owner.remove (*this);
         }
Member Function Documentation
void beast::asio::HTTPClientType::Session::async_read_some () inline
Definition at line 316 of file HTTPClientType.cpp.
References beast::MemoryBlock::getData(), beast::MemoryBlock::getSize(), handle_read(), m_buffer, m_handler, m_strand, m_stream, and beast::asio::wrap_handler().
Referenced by handle_handshake(), and handle_read().
         {
             boost::asio::mutable_buffers_1 buf (
                 m_buffer.getData (), m_buffer.getSize ());
             m_stream->async_read_some (buf, m_strand.wrap (
                 asio::wrap_handler (std::bind (&Session::handle_read,
                     Ptr(this), asio::placeholders::error,
                         asio::placeholders::bytes_transferred), m_handler)));
         }
void beast::asio::HTTPClientType::Session::cancel () inline
Definition at line 276 of file HTTPClientType.cpp.
References cancel_all(), and m_state.
         {
             {
                 SharedState::Access state (m_state);
                 if (! state->complete)
                 {
                     state->complete = true;
                     state->error = boost::asio::error::operation_aborted;
                 }
             }
             cancel_all();
         }
void beast::asio::HTTPClientType::Session::cancel_all () inline
Definition at line 291 of file HTTPClientType.cpp.
References m_resolver, m_socket, and m_timer.
Referenced by cancel(), failed(), and handle_shutdown().
         {
             error_code ec;
             m_timer.cancel (ec);
             m_resolver.cancel ();
             m_socket.cancel (ec);
             m_socket.shutdown (socket::shutdown_both, ec);
         }
void beast::asio::HTTPClientType::Session::failed (error_code ec) inline
Definition at line 301 of file HTTPClientType.cpp.
References cancel_all(), and m_state.
Referenced by handle_connect(), handle_handshake(), handle_read(), handle_resolve(), handle_shutdown(), handle_timer(), and handle_write().
         {
             {
                 SharedState::Access state (m_state);
                 if (! state->complete)
                 {
                     state->complete = true;
                     state->error = ec;
                     state->response = nullptr;
                 }
             }
             cancel_all();
         }
void beast::asio::HTTPClientType::Session::handle_connect (error_code ec) inline
Definition at line 378 of file HTTPClientType.cpp.
References failed(), handle_handshake(), m_context, m_handler, m_socket, m_strand, m_stream, m_url, beast::URL::scheme(), and beast::asio::wrap_handler().
Referenced by handle_resolve().
         {
             if (ec == boost::asio::error::operation_aborted)
                 return;
             if (ec != 0)
             {
                 failed (ec);
                 return;
             }
             if (m_url.scheme () == "https")
             {
                 typedef boost::asio::ssl::stream <socket&> ssl_stream;
                 m_stream = std::make_unique <
                     socket_wrapper <ssl_stream>> (m_socket, m_context);
                 /*
                 m_stream->set_verify_mode (
                     boost::asio::ssl::verify_peer |
                     boost::asio::ssl::verify_fail_if_no_peer_cert);
                 */
                 m_stream->async_handshake (abstract_socket::client, m_strand.wrap (
                     asio::wrap_handler (std::bind (&Session::handle_handshake,
                         Ptr(this), asio::placeholders::error), m_handler)));
                 return;
             }
             m_stream = std::make_unique <socket_wrapper <socket&>> (m_socket);
             handle_handshake (ec);
         }
void beast::asio::HTTPClientType::Session::handle_handshake (error_code ec) inline
Definition at line 410 of file HTTPClientType.cpp.
References async_read_some(), failed(), handle_write(), beast::URL::host(), m_get_string, m_handler, m_strand, m_stream, m_url, beast::URL::path(), beast::asio::HTTPClientType::stringBuffer(), and beast::asio::wrap_handler().
Referenced by handle_connect().
         {
             if (ec == boost::asio::error::operation_aborted)
                 return;
             if (ec != 0)
             {
                 failed (ec);
                 return;
             }
             m_get_string =
                 "GET " + m_url.path() + " HTTP/1.1\r\n" +
                 "Host: " + m_url.host() + "\r\n" +
                 "Accept: */*\r\n" +
                 "Connection: close\r\n\r\n";
             boost::asio::async_write (*m_stream, stringBuffer (
                 m_get_string), m_strand.wrap (asio::wrap_handler (
                     std::bind (&Session::handle_write, Ptr(this),
                         asio::placeholders::error,
                             asio::placeholders::bytes_transferred), m_handler)));
             async_read_some ();
         }
void beast::asio::HTTPClientType::Session::handle_read (error_code ec, std::size_t bytes_transferred) inline
Definition at line 452 of file HTTPClientType.cpp.
References async_read_some(), beast::HTTPParser::error(), failed(), beast::HTTPParser::finished(), beast::MemoryBlock::getData(), handle_shutdown(), m_buffer, m_bytesReceived, m_handler, m_messageLimitBytes, m_parser, m_strand, m_stream, beast::HTTPParser::process(), beast::HTTPParser::process_eof(), and beast::asio::wrap_handler().
Referenced by async_read_some().
         {
             if (ec == boost::asio::error::operation_aborted)
                 return;
             if (ec != 0)
             {
                 failed (ec);
                 return;
             }
             m_bytesReceived += bytes_transferred;
             if (m_bytesReceived > m_messageLimitBytes)
             {
                 failed (error_code (
                     boost::system::errc::invalid_argument,
                     boost::system::system_category ()));
                 return;
             }
             std::size_t const bytes_parsed (m_parser.process (
                 m_buffer.getData (), bytes_transferred));
             if (m_parser.error ())
             {
                 failed (error_code (
                     boost::system::errc::invalid_argument,
                     boost::system::system_category ()));
                 return;
             }
             if (bytes_parsed != bytes_transferred)
             {
                 failed (error_code (
                     boost::system::errc::invalid_argument,
                     boost::system::system_category ()));
                 return;
             }
             if (ec == boost::asio::error::eof)
                 m_parser.process_eof ();
             if (m_parser.finished ())
             {
                 if (m_stream->needs_handshake ())
                 {
                     m_stream->async_shutdown (m_strand.wrap (asio::wrap_handler (
                         std::bind (&Session::handle_shutdown,
                             Ptr(this), asio::placeholders::error), m_handler)));
                 }
                 else
                 {
                     handle_shutdown (error_code ());
                 }
                 return;
             }
             async_read_some ();
         }
void beast::asio::HTTPClientType::Session::handle_resolve (error_code ec, iterator iter) inline
Definition at line 360 of file HTTPClientType.cpp.
References failed(), handle_connect(), m_handler, m_socket, m_strand, and beast::asio::wrap_handler().
Referenced by handle_start().
         {
             if (ec == boost::asio::error::operation_aborted)
                 return;
             if (ec != 0)
             {
                 failed (ec);
                 return;
             }
             resolver_entry const entry (*iter);
             m_socket.async_connect (entry.endpoint (), m_strand.wrap (
                 asio::wrap_handler (std::bind (&Session::handle_connect,
                     Ptr(this), asio::placeholders::error), m_handler)));
         }
void beast::asio::HTTPClientType::Session::handle_shutdown (error_code ec) inline
Definition at line 513 of file HTTPClientType.cpp.
References cancel_all(), failed(), m_parser, m_state, and beast::HTTPResponseParser::response().
Referenced by handle_read().
         {
             if (ec == boost::asio::error::operation_aborted)
                 return;
             if (ec == boost::asio::error::eof)
                 ec = error_code();
             if (ec != 0)
             {
                 failed (ec);
                 return;
             }
             {
                 SharedState::Access state (m_state);
                 if (! state->complete)
                 {
                     state->complete = true;
                     state->response = m_parser.response();
                 }
             }
             cancel_all();
         }
void beast::asio::HTTPClientType::Session::handle_start () inline
Definition at line 333 of file HTTPClientType.cpp.
References handle_resolve(), m_handler, m_resolver, m_strand, m_url, and beast::asio::wrap_handler().
Referenced by Session().
         {
             query q (queryFromURL <query> (m_url));
             m_resolver.async_resolve (q, m_strand.wrap (
                 asio::wrap_handler (std::bind (&Session::handle_resolve,
                     Ptr(this), asio::placeholders::error,
                         asio::placeholders::iterator), m_handler)));
         }
void beast::asio::HTTPClientType::Session::handle_timer (error_code ec) inline
Definition at line 344 of file HTTPClientType.cpp.
References failed().
Referenced by Session().
         {
             if (ec == boost::asio::error::operation_aborted)
                 return;
             if (ec != 0)
             {
                 failed (ec);
                 return;
             }
             failed (boost::system::errc::make_error_code (
                 boost::system::errc::timed_out));
         }
void beast::asio::HTTPClientType::Session::handle_write (error_code ec, std::size_t) inline
Definition at line 437 of file HTTPClientType.cpp.
References failed(), m_socket, and m_stream.
Referenced by handle_handshake().
         {
             if (ec == boost::asio::error::operation_aborted)
                 return;
             if (ec != 0)
             {
                 failed (ec);
                 return;
             }
             if (! m_stream->needs_handshake ())
                 m_socket.shutdown (socket::shutdown_send, ec);
         }
Member Data Documentation
MemoryBlock beast::asio::HTTPClientType::Session::m_buffer
Definition at line 188 of file HTTPClientType.cpp.
Referenced by async_read_some(), and handle_read().
std::size_t beast::asio::HTTPClientType::Session::m_bytesReceived
Definition at line 191 of file HTTPClientType.cpp.
Referenced by handle_read().
boost::asio::ssl::context beast::asio::HTTPClientType::Session::m_context
Definition at line 187 of file HTTPClientType.cpp.
Referenced by handle_connect(), and Session().
WaitableEvent beast::asio::HTTPClientType::Session::m_done
Definition at line 194 of file HTTPClientType.cpp.
String beast::asio::HTTPClientType::Session::m_get_string
Definition at line 193 of file HTTPClientType.cpp.
Referenced by handle_handshake().
asio::shared_handler<void (result_type)> beast::asio::HTTPClientType::Session::m_handler
Definition at line 184 of file HTTPClientType.cpp.
Referenced by async_read_some(), handle_connect(), handle_handshake(), handle_read(), handle_resolve(), handle_start(), Session(), and ~Session().
boost::asio::io_service& beast::asio::HTTPClientType::Session::m_io_service
Definition at line 179 of file HTTPClientType.cpp.
Referenced by ~Session().
std::size_t beast::asio::HTTPClientType::Session::m_messageLimitBytes
Definition at line 190 of file HTTPClientType.cpp.
Referenced by handle_read().
HTTPClientType& beast::asio::HTTPClientType::Session::m_owner
Definition at line 178 of file HTTPClientType.cpp.
Referenced by Session(), and ~Session().
HTTPResponseParser beast::asio::HTTPClientType::Session::m_parser
Definition at line 189 of file HTTPClientType.cpp.
Referenced by handle_read(), and handle_shutdown().
resolver beast::asio::HTTPClientType::Session::m_resolver
Definition at line 182 of file HTTPClientType.cpp.
Referenced by cancel_all(), and handle_start().
socket beast::asio::HTTPClientType::Session::m_socket
Definition at line 183 of file HTTPClientType.cpp.
Referenced by cancel_all(), handle_connect(), handle_resolve(), and handle_write().
SharedState beast::asio::HTTPClientType::Session::m_state
Definition at line 208 of file HTTPClientType.cpp.
Referenced by cancel(), failed(), handle_shutdown(), and ~Session().
boost::asio::io_service::strand beast::asio::HTTPClientType::Session::m_strand
Definition at line 180 of file HTTPClientType.cpp.
Referenced by async_read_some(), handle_connect(), handle_handshake(), handle_read(), handle_resolve(), handle_start(), and Session().
std::unique_ptr<abstract_socket> beast::asio::HTTPClientType::Session::m_stream
Definition at line 195 of file HTTPClientType.cpp.
Referenced by async_read_some(), handle_connect(), handle_handshake(), handle_read(), and handle_write().
boost::asio::deadline_timer beast::asio::HTTPClientType::Session::m_timer
Definition at line 181 of file HTTPClientType.cpp.
Referenced by cancel_all(), and Session().
URL beast::asio::HTTPClientType::Session::m_url
Definition at line 186 of file HTTPClientType.cpp.
Referenced by handle_connect(), handle_handshake(), and handle_start().
The documentation for this class was generated from the following file:
rippled/src/beast/modules/beast_asio/http/HTTPClientType.cpp