rippled: beast::unit_test::suite_results Class Reference
beast::unit_test::suite_results Class Reference
#include <results.h>
Public Member Functions
suite_results (std::string const &name="")
std::string const & name () const
std::size_t total () const
std::size_t failed () const
void insert (case_results &&r)
void insert (case_results const &r)
Public Member Functions inherited from beast::const_container< std::vector< case_results > >
bool empty () const
size_type size () const
const_iterator begin () const
const_iterator cbegin () const
const_iterator end () const
const_iterator cend () const
Private Attributes
std::string m_name
std::size_t m_total
std::size_t m_failed
Additional Inherited Members
Public Types inherited from beast::const_container< std::vector< case_results > >
typedef cont_type::value_type value_type
typedef cont_type::size_type size_type
typedef cont_type::difference_type difference_type
typedef cont_type::const_iterator iterator
typedef cont_type::const_iterator const_iterator
Protected Member Functions inherited from beast::const_container< std::vector< case_results > >
cont_type & cont ()
cont_type const & cont () const
Detailed Description
Holds the set of testcase results in a suite.
Definition at line 133 of file results.h.
Constructor & Destructor Documentation
beast::unit_test::suite_results::suite_results (std::string const & name = "") inline explicit
Definition at line 142 of file results.h.
         : m_name (name)
         , m_total (0)
         , m_failed (0)
     {
     }
Member Function Documentation
std::size_t beast::unit_test::suite_results::failed () const inline
Returns the number of failures.
Definition at line 165 of file results.h.
References m_failed.
Referenced by beast::unit_test::results::insert().
     {
         return m_failed;
     }
void beast::unit_test::suite_results::insert (case_results && r) inline
Insert a set of testcase results.
Definition at line 173 of file results.h.
References beast::const_container< std::vector< case_results > >::cont(), m_failed, and m_total.
Referenced by beast::unit_test::recorder::on_case_end().
     {
         cont().emplace_back (std::move (r));
         m_total += r.tests.total();
         m_failed += r.tests.failed();
     }
void beast::unit_test::suite_results::insert (case_results const & r) inline
Definition at line 181 of file results.h.
References beast::const_container< std::vector< case_results > >::cont(), beast::unit_test::case_results::tests_t::failed(), m_failed, m_total, beast::unit_test::case_results::tests, and beast::unit_test::case_results::tests_t::total().
     {
         cont().push_back (r);
         m_total += r.tests.total();
         m_failed += r.tests.failed();
     }
std::string const& beast::unit_test::suite_results::name () const inline
Returns the name of this suite.
Definition at line 151 of file results.h.
References m_name.
     {
         return m_name;
     }
std::size_t beast::unit_test::suite_results::total () const inline
Returns the total number of test conditions.
Definition at line 158 of file results.h.
References m_total.
Referenced by beast::unit_test::results::insert().
     {
         return m_total;
     }
Member Data Documentation
std::size_t beast::unit_test::suite_results::m_failed private
Definition at line 139 of file results.h.
Referenced by failed(), and insert().
std::string beast::unit_test::suite_results::m_name private
Definition at line 137 of file results.h.
Referenced by name().
std::size_t beast::unit_test::suite_results::m_total private
Definition at line 138 of file results.h.
Referenced by insert(), and total().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/unit_test/results.h