rippled: beast::buffer_view< T, Tag > Class Template Reference
beast::buffer_view< T, Tag > Class Template Reference
#include <buffer_view.h>
Public Types
typedef T value_type
typedef std::size_t size_type
typedef std::ptrdiff_t difference_type
typedef T & reference
typedef T const & const_reference
typedef T * pointer
typedef T const * const_pointer
typedef T * iterator
typedef T const * const_iterator
typedef std::reverse_iterator
< iterator > reverse_iterator
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator
Public Member Functions
buffer_view () noexcept
template<class U , class = std::enable_if_t < detail::buffer_view_convertible <T, U>::value>>
buffer_view (buffer_view< U, Tag > v) noexcept
template<class C , class = std::enable_if_t < detail::buffer_view_container_compatible <T, C>::value >>
buffer_view (C &c) noexcept
template<class U , class = std::enable_if_t < detail::buffer_view_convertible <T, U>::value>>
buffer_view (U *first, U *last) noexcept
template<class U , class = std::enable_if_t < detail::buffer_view_convertible <T, U>::value>>
buffer_view (U *u, std::size_t n) noexcept
template<class C , class = std::enable_if_t < detail::buffer_view_container_compatible <T, C>::value >>
buffer_view & operator= (C &c) noexcept
reference at (size_type pos)
const_reference at (size_type pos) const
reference operator[] (size_type pos) noexcept
const_reference operator[] (size_type pos) const noexcept
reference back () noexcept
const_reference back () const noexcept
reference front () noexcept
const_reference front () const noexcept
pointer data () noexcept
const_pointer data () const noexcept
iterator begin () noexcept
const_iterator begin () const noexcept
const_iterator cbegin () const noexcept
iterator end () noexcept
const_iterator end () const noexcept
const_iterator cend () const noexcept
reverse_iterator rbegin () noexcept
const_reverse_iterator rbegin () const noexcept
const_reverse_iterator crbegin () const noexcept
reverse_iterator rend () noexcept
const_reverse_iterator rend () const noexcept
const_reverse_iterator crend () const noexcept
bool empty () const noexcept
size_type size () const noexcept
size_type max_size () const noexcept
size_type capacity () const noexcept
Private Member Functions
template<class Iter >
void assign (Iter first, Iter last) noexcept
Private Attributes
T * m_base
std::size_t m_size
Friends
template<class U , class K >
void swap (buffer_view< U, K > &lhs, buffer_view< U, K > &rhs) noexcept
Detailed Description
template<class T, class Tag = buffer_view_default_tag>
class beast::buffer_view< T, Tag >
A view into a range of contiguous container elements.
The size of the view is determined at the time of construction. This tries to emulate the interface of std::vector as closely as possible, with the constraint that the size of the container cannot be changed.
Template Parameters
T The underlying element type. If T is const, member functions which can modify elements are removed from the interface.
Tag A type used to prevent two views with the same T from being comparable or assignable.
Definition at line 144 of file buffer_view.h.
Member Typedef Documentation
template<class T, class Tag = buffer_view_default_tag> typedef T const* beast::buffer_view< T, Tag >::const_iterator
Definition at line 201 of file buffer_view.h.
template<class T, class Tag = buffer_view_default_tag> typedef T const* beast::buffer_view< T, Tag >::const_pointer
Definition at line 199 of file buffer_view.h.
template<class T, class Tag = buffer_view_default_tag> typedef T const& beast::buffer_view< T, Tag >::const_reference
Definition at line 197 of file buffer_view.h.
template<class T, class Tag = buffer_view_default_tag> typedef std::reverse_iterator<const_iterator> beast::buffer_view< T, Tag >::const_reverse_iterator
Definition at line 203 of file buffer_view.h.
template<class T, class Tag = buffer_view_default_tag> typedef std::ptrdiff_t beast::buffer_view< T, Tag >::difference_type
Definition at line 195 of file buffer_view.h.
template<class T, class Tag = buffer_view_default_tag> typedef T* beast::buffer_view< T, Tag >::iterator
Definition at line 200 of file buffer_view.h.
template<class T, class Tag = buffer_view_default_tag> typedef T* beast::buffer_view< T, Tag >::pointer
Definition at line 198 of file buffer_view.h.
template<class T, class Tag = buffer_view_default_tag> typedef T& beast::buffer_view< T, Tag >::reference
Definition at line 196 of file buffer_view.h.
template<class T, class Tag = buffer_view_default_tag> typedef std::reverse_iterator<iterator> beast::buffer_view< T, Tag >::reverse_iterator
Definition at line 202 of file buffer_view.h.
template<class T, class Tag = buffer_view_default_tag> typedef std::size_t beast::buffer_view< T, Tag >::size_type
Definition at line 194 of file buffer_view.h.
template<class T, class Tag = buffer_view_default_tag> typedef T beast::buffer_view< T, Tag >::value_type
Definition at line 193 of file buffer_view.h.
Constructor & Destructor Documentation
template<class T, class Tag = buffer_view_default_tag> beast::buffer_view< T, Tag >::buffer_view () inline noexcept
Definition at line 206 of file buffer_view.h.
         : m_base (nullptr)
         , m_size (0)
     {
     }
template<class T, class Tag = buffer_view_default_tag> template<class U , class = std::enable_if_t < detail::buffer_view_convertible <T, U>::value>> beast::buffer_view< T, Tag >::buffer_view (buffer_view< U, Tag > v) inline noexcept
Definition at line 217 of file buffer_view.h.
References beast::buffer_view< T, Tag >::assign().
     {
         assign (v.begin(), v.end());
     }
template<class T, class Tag = buffer_view_default_tag> template<class C , class = std::enable_if_t < detail::buffer_view_container_compatible <T, C>::value >> beast::buffer_view< T, Tag >::buffer_view (C & c) inline noexcept
Definition at line 228 of file buffer_view.h.
References beast::buffer_view< T, Tag >::assign().
     {
         assign (c.begin(), c.end());
     }
template<class T, class Tag = buffer_view_default_tag> template<class U , class = std::enable_if_t < detail::buffer_view_convertible <T, U>::value>> beast::buffer_view< T, Tag >::buffer_view (U * first, U * last) inline noexcept
Definition at line 238 of file buffer_view.h.
References beast::buffer_view< T, Tag >::assign(), and beast.util.Iter::first().
     {
         assign (first, last);
     }
template<class T, class Tag = buffer_view_default_tag> template<class U , class = std::enable_if_t < detail::buffer_view_convertible <T, U>::value>> beast::buffer_view< T, Tag >::buffer_view (U * u, std::size_t n) inline noexcept
Definition at line 248 of file buffer_view.h.
         : m_base (u)
         , m_size (n)
     {
     }
Member Function Documentation
template<class T, class Tag = buffer_view_default_tag> template<class Iter > void beast::buffer_view< T, Tag >::assign (Iter first, Iter last) inline private noexcept
Definition at line 162 of file buffer_view.h.
References beast.util.Iter::first(), beast::buffer_view< T, Tag >::m_base, beast::buffer_view< T, Tag >::m_size, and T.
Referenced by beast::buffer_view< T, Tag >::buffer_view(), and beast::buffer_view< T, Tag >::operator=().
     {
         typedef typename std::iterator_traits <Iter>::value_type U;
         static_assert (detail::buffer_view_const_compatible <T, U>::value,
             "Cannot convert from 'U const' to 'T', "
                 "conversion loses const qualifiers");
         static_assert (detail::buffer_view_ptr_compatible <T, U>::value,
             "Cannot convert from 'U*' to 'T*, "
                 "types are incompatible");
         if (first == last)
         {
             m_base = nullptr;
             m_size = 0;
         }
         else
         {
         #if 0
             // fails on gcc
             m_base = reinterpret_cast <T*> (
                 std::addressof (*first));
         #else
             m_base = reinterpret_cast <T*> (&*first);
         #endif
             m_size = std::distance (first, last);
         }
     }
template<class T, class Tag = buffer_view_default_tag> reference beast::buffer_view< T, Tag >::at (size_type pos) inline
Definition at line 272 of file buffer_view.h.
References beast::buffer_view< T, Tag >::m_base, and beast::buffer_view< T, Tag >::size().
     {
         if (! (pos < size()))
             throw std::out_of_range ("bad array index");
         return m_base [pos];
     }
template<class T, class Tag = buffer_view_default_tag> const_reference beast::buffer_view< T, Tag >::at (size_type pos) const inline
Definition at line 280 of file buffer_view.h.
References beast::buffer_view< T, Tag >::m_base, and beast::buffer_view< T, Tag >::size().
     {
         if (! (pos < size()))
             throw std::out_of_range ("bad array index");
         return m_base [pos];
     }
template<class T, class Tag = buffer_view_default_tag> reference beast::buffer_view< T, Tag >::back () inline noexcept
Definition at line 300 of file buffer_view.h.
References beast::buffer_view< T, Tag >::m_base, and beast::buffer_view< T, Tag >::m_size.
Referenced by beast::buffer_view_test::check().
     {
         return m_base [m_size - 1];
     }
template<class T, class Tag = buffer_view_default_tag> const_reference beast::buffer_view< T, Tag >::back () const inline noexcept
Definition at line 306 of file buffer_view.h.
References beast::buffer_view< T, Tag >::m_base, and beast::buffer_view< T, Tag >::m_size.
     {
         return m_base [m_size - 1];
     }
template<class T, class Tag = buffer_view_default_tag> iterator beast::buffer_view< T, Tag >::begin () inline noexcept
Definition at line 340 of file buffer_view.h.
References beast::buffer_view< T, Tag >::m_base.
Referenced by beast::buffer_view_test::check(), and beast::buffer_view< T, Tag >::rend().
     {
         return m_base;
     }
template<class T, class Tag = buffer_view_default_tag> const_iterator beast::buffer_view< T, Tag >::begin () const inline noexcept
Definition at line 346 of file buffer_view.h.
References beast::buffer_view< T, Tag >::m_base.
     {
         return m_base;
     }
template<class T, class Tag = buffer_view_default_tag> size_type beast::buffer_view< T, Tag >::capacity () const inline noexcept
Definition at line 434 of file buffer_view.h.
References beast::buffer_view< T, Tag >::size().
Referenced by beast::buffer_view_test::check().
     {
         return size();
     }
template<class T, class Tag = buffer_view_default_tag> const_iterator beast::buffer_view< T, Tag >::cbegin () const inline noexcept
Definition at line 352 of file buffer_view.h.
References beast::buffer_view< T, Tag >::m_base.
Referenced by beast::buffer_view_test::check(), beast::buffer_view< T, Tag >::crend(), beast::operator==(), and beast::buffer_view< T, Tag >::rend().
     {
         return m_base;
     }
template<class T, class Tag = buffer_view_default_tag> const_iterator beast::buffer_view< T, Tag >::cend () const inline noexcept
Definition at line 370 of file buffer_view.h.
References beast::buffer_view< T, Tag >::m_base, and beast::buffer_view< T, Tag >::m_size.
Referenced by beast::buffer_view_test::check(), beast::buffer_view< T, Tag >::crbegin(), beast::operator==(), and beast::buffer_view< T, Tag >::rbegin().
     {
         return m_base + m_size;
     }
template<class T, class Tag = buffer_view_default_tag> const_reverse_iterator beast::buffer_view< T, Tag >::crbegin () const inline noexcept
Definition at line 388 of file buffer_view.h.
References beast::buffer_view< T, Tag >::cend().
Referenced by beast::buffer_view_test::check().
     {
         return const_reverse_iterator (cend());
     }
template<class T, class Tag = buffer_view_default_tag> const_reverse_iterator beast::buffer_view< T, Tag >::crend () const inline noexcept
Definition at line 406 of file buffer_view.h.
References beast::buffer_view< T, Tag >::cbegin().
Referenced by beast::buffer_view_test::check().
     {
         return const_reverse_iterator (cbegin());
     }
template<class T, class Tag = buffer_view_default_tag> pointer beast::buffer_view< T, Tag >::data () inline noexcept
Definition at line 324 of file buffer_view.h.
References beast::buffer_view< T, Tag >::m_base.
Referenced by ripple::Serializer::getSHA512Half().
     {
         return m_base;
     }
template<class T, class Tag = buffer_view_default_tag> const_pointer beast::buffer_view< T, Tag >::data () const inline noexcept
Definition at line 330 of file buffer_view.h.
References beast::buffer_view< T, Tag >::m_base.
     {
         return m_base;
     }
template<class T, class Tag = buffer_view_default_tag> bool beast::buffer_view< T, Tag >::empty () const inline noexcept
Definition at line 416 of file buffer_view.h.
References beast::buffer_view< T, Tag >::m_size.
Referenced by beast::buffer_view_test::check().
     {
         return m_size == 0;
     }
template<class T, class Tag = buffer_view_default_tag> iterator beast::buffer_view< T, Tag >::end () inline noexcept
Definition at line 358 of file buffer_view.h.
References beast::buffer_view< T, Tag >::m_base, and beast::buffer_view< T, Tag >::m_size.
Referenced by beast::buffer_view_test::check(), and beast::buffer_view< T, Tag >::rbegin().
     {
         return m_base + m_size;
     }
template<class T, class Tag = buffer_view_default_tag> const_iterator beast::buffer_view< T, Tag >::end () const inline noexcept
Definition at line 364 of file buffer_view.h.
References beast::buffer_view< T, Tag >::m_base, and beast::buffer_view< T, Tag >::m_size.
     {
         return m_base + m_size;
     }
template<class T, class Tag = buffer_view_default_tag> reference beast::buffer_view< T, Tag >::front () inline noexcept
Definition at line 312 of file buffer_view.h.
References beast::buffer_view< T, Tag >::m_base.
Referenced by beast::buffer_view_test::check().
     {
         return *m_base;
     }
template<class T, class Tag = buffer_view_default_tag> const_reference beast::buffer_view< T, Tag >::front () const inline noexcept
Definition at line 318 of file buffer_view.h.
References beast::buffer_view< T, Tag >::m_base.
     {
         return *m_base;
     }
template<class T, class Tag = buffer_view_default_tag> size_type beast::buffer_view< T, Tag >::max_size () const inline noexcept
Definition at line 428 of file buffer_view.h.
References beast::buffer_view< T, Tag >::size().
Referenced by beast::buffer_view_test::check().
     {
         return size();
     }
template<class T, class Tag = buffer_view_default_tag> template<class C , class = std::enable_if_t < detail::buffer_view_container_compatible <T, C>::value >> buffer_view& beast::buffer_view< T, Tag >::operator= (C & c) inline noexcept
Definition at line 261 of file buffer_view.h.
References beast::buffer_view< T, Tag >::assign().
     {
         assign (c.begin(), c.end());
         return *this;
     }
template<class T, class Tag = buffer_view_default_tag> reference beast::buffer_view< T, Tag >::operator[] (size_type pos) inline noexcept
Definition at line 288 of file buffer_view.h.
References beast::buffer_view< T, Tag >::m_base.
     {
         return m_base [pos];
     }
template<class T, class Tag = buffer_view_default_tag> const_reference beast::buffer_view< T, Tag >::operator[] (size_type pos) const inline noexcept
Definition at line 294 of file buffer_view.h.
References beast::buffer_view< T, Tag >::m_base.
     {
         return m_base [pos];
     }
template<class T, class Tag = buffer_view_default_tag> reverse_iterator beast::buffer_view< T, Tag >::rbegin () inline noexcept
Definition at line 376 of file buffer_view.h.
References beast::buffer_view< T, Tag >::end().
Referenced by beast::buffer_view_test::check().
     {
         return reverse_iterator (end());
     }
template<class T, class Tag = buffer_view_default_tag> const_reverse_iterator beast::buffer_view< T, Tag >::rbegin () const inline noexcept
Definition at line 382 of file buffer_view.h.
References beast::buffer_view< T, Tag >::cend().
     {
         return const_reverse_iterator (cend());
     }
template<class T, class Tag = buffer_view_default_tag> reverse_iterator beast::buffer_view< T, Tag >::rend () inline noexcept
Definition at line 394 of file buffer_view.h.
References beast::buffer_view< T, Tag >::begin().
Referenced by beast::buffer_view_test::check().
     {
         return reverse_iterator (begin());
     }
template<class T, class Tag = buffer_view_default_tag> const_reverse_iterator beast::buffer_view< T, Tag >::rend () const inline noexcept
Definition at line 400 of file buffer_view.h.
References beast::buffer_view< T, Tag >::cbegin().
     {
         return const_reverse_iterator (cbegin());
     }
template<class T, class Tag = buffer_view_default_tag> size_type beast::buffer_view< T, Tag >::size () const inline noexcept
Definition at line 422 of file buffer_view.h.
References beast::buffer_view< T, Tag >::m_size.
Referenced by beast::buffer_view< T, Tag >::at(), beast::buffer_view< T, Tag >::capacity(), beast::buffer_view_test::check(), ripple::Serializer::getSHA512Half(), and beast::buffer_view< T, Tag >::max_size().
     {
         return m_size;
     }
Friends And Related Function Documentation
template<class T, class Tag = buffer_view_default_tag> template<class U , class K > void swap (buffer_view< U, K > & lhs, buffer_view< U, K > & rhs) friend
Member Data Documentation
template<class T, class Tag = buffer_view_default_tag> T* beast::buffer_view< T, Tag >::m_base private
Definition at line 147 of file buffer_view.h.
Referenced by beast::buffer_view< T, Tag >::assign(), beast::buffer_view< T, Tag >::at(), beast::buffer_view< T, Tag >::back(), beast::buffer_view< T, Tag >::begin(), beast::buffer_view< T, Tag >::cbegin(), beast::buffer_view< T, Tag >::cend(), beast::buffer_view< T, Tag >::data(), beast::buffer_view< T, Tag >::end(), beast::buffer_view< T, Tag >::front(), and beast::buffer_view< T, Tag >::operator[]().
template<class T, class Tag = buffer_view_default_tag> std::size_t beast::buffer_view< T, Tag >::m_size private
Definition at line 148 of file buffer_view.h.
Referenced by beast::buffer_view< T, Tag >::assign(), beast::buffer_view< T, Tag >::back(), beast::buffer_view< T, Tag >::cend(), beast::buffer_view< T, Tag >::empty(), beast::buffer_view< T, Tag >::end(), and beast::buffer_view< T, Tag >::size().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/container/buffer_view.h