rippled: rocksdb::SimpleTableReader Class Reference
rocksdb::SimpleTableReader Class Reference
Classes
struct Rep
Public Member Functions
bool PrefixMayMatch (const Slice &internal_prefix) override
Iterator * NewIterator (const ReadOptions &) override
Status Get (const ReadOptions &, const Slice &key, void *arg, bool(*handle_result)(void *arg, const Slice &k, const Slice &v, bool), void(*mark_key_may_exist)(void *)=nullptr) override
uint64_t ApproximateOffsetOf (const Slice &key) override
bool TEST_KeyInCache (const ReadOptions &options, const Slice &key) override
void SetupForCompaction () override
TableProperties & GetTableProperties () override
~SimpleTableReader ()
Public Member Functions inherited from rocksdb::TableReader
virtual ~TableReader ()
virtual Status Get (const ReadOptions &readOptions, const Slice &key, void *handle_context, bool(*result_handler)(void *handle_context, const Slice &k, const Slice &v, bool didIO), void(*mark_key_may_exist_handler)(void *handle_context)=nullptr)=0
Static Public Member Functions
static Status Open (const Options &options, const EnvOptions &soptions, unique_ptr< RandomAccessFile > &&file, uint64_t file_size, unique_ptr< TableReader > *table_reader)
Private Member Functions
SimpleTableReader (Rep *rep)
Status GetOffset (const Slice &target, uint64_t *offset)
SimpleTableReader (const TableReader &)=delete
void operator= (const TableReader &)=delete
Private Attributes
Rep * rep_
Friends
class TableCache
class SimpleTableIterator
Detailed Description
Definition at line 65 of file simple_table_db_test.cc.
Constructor & Destructor Documentation
rocksdb::SimpleTableReader::~SimpleTableReader ()
Definition at line 185 of file simple_table_db_test.cc.
References rep_.
{
   delete rep_;
 }
rocksdb::SimpleTableReader::SimpleTableReader (Rep * rep) inline explicit private
Definition at line 106 of file simple_table_db_test.cc.
References rep_.
Referenced by Open().
{
     rep_ = rep;
   }
rocksdb::SimpleTableReader::SimpleTableReader (const TableReader &) explicit private delete
Member Function Documentation
uint64_t rocksdb::SimpleTableReader::ApproximateOffsetOf (const Slice & key) override virtual
Implements rocksdb::TableReader.
Definition at line 303 of file simple_table_db_test.cc.
{
   return 0;
 }
Status rocksdb::SimpleTableReader::Get (const ReadOptions & , const Slice & key, void * arg, bool(*)(void *arg, const Slice &k, const Slice &v, bool) handle_result, void(*)(void *) mark_key_may_exist = nullptr) override
Definition at line 282 of file simple_table_db_test.cc.
References arg, rocksdb::SimpleTableIterator::key(), rocksdb::SimpleTableIterator::Next(), rocksdb::SimpleTableIterator::Seek(), SimpleTableIterator, rocksdb::SimpleTableIterator::status(), rocksdb::SimpleTableIterator::Valid(), and rocksdb::SimpleTableIterator::value().
{
   Status s;
   SimpleTableIterator* iter = new SimpleTableIterator(this);
   for (iter->Seek(k); iter->Valid(); iter->Next()) {
     if (!(*saver)(arg, iter->key(), iter->value(), true)) {
       break;
     }
   }
   s = iter->status();
   delete iter;
   return s;
 }
Status rocksdb::SimpleTableReader::GetOffset (const Slice & target, uint64_t * offset) private
Definition at line 229 of file simple_table_db_test.cc.
References rocksdb::Options::comparator, rocksdb::Comparator::Compare(), rocksdb::DecodeFixed64(), rocksdb::SimpleTableReader::Rep::file, rocksdb::SimpleTableReader::Rep::GetInternalKeyLength(), rocksdb::SimpleTableReader::Rep::index_start_offset, rocksdb::SimpleTableReader::Rep::num_entries, rocksdb::SimpleTableReader::Rep::offset_length, rocksdb::Status::OK(), rocksdb::Status::ok(), rocksdb::SimpleTableReader::Rep::options, and rep_.
Referenced by rocksdb::SimpleTableIterator::Seek().
{
   uint32_t left = 0;
   uint32_t right = rep_->num_entries - 1;
   char key_chars[Rep::GetInternalKeyLength()];
   Slice tmp_slice;
   uint32_t target_offset = 0;
   while (left <= right) {
     uint32_t mid = (left + right + 1) / 2;
     uint64_t offset_to_read = rep_->index_start_offset
         + (Rep::GetInternalKeyLength() + Rep::offset_length) * mid;
     Status s = rep_->file->Read(offset_to_read, Rep::GetInternalKeyLength(),
                                 &tmp_slice, key_chars);
     if (!s.ok()) {
       return s;
     }
     int compare_result = rep_->options.comparator->Compare(tmp_slice, target);
     if (compare_result < 0) {
       if (left == right) {
         target_offset = right + 1;
         break;
       }
       left = mid;
     } else {
       if (left == right) {
         target_offset = left;
         break;
       }
       right = mid - 1;
     }
   }
   if (target_offset >= (uint32_t) rep_->num_entries) {
     *offset = rep_->index_start_offset;
     return Status::OK();
   }
   char value_offset_chars[Rep::offset_length];
   int64_t offset_for_value_offset = rep_->index_start_offset
       + (Rep::GetInternalKeyLength() + Rep::offset_length) * target_offset
       + Rep::GetInternalKeyLength();
   Status s = rep_->file->Read(offset_for_value_offset, Rep::offset_length,
                               &tmp_slice, value_offset_chars);
   if (s.ok()) {
     *offset = DecodeFixed64(value_offset_chars);
   }
   return s;
 }
TableProperties & rocksdb::SimpleTableReader::GetTableProperties () override virtual
Implements rocksdb::TableReader.
Definition at line 217 of file simple_table_db_test.cc.
References rep_, and rocksdb::SimpleTableReader::Rep::table_properties.
{
   return rep_->table_properties;
 }
Iterator * rocksdb::SimpleTableReader::NewIterator (const ReadOptions & options) override virtual
Implements rocksdb::TableReader.
Definition at line 225 of file simple_table_db_test.cc.
References SimpleTableIterator.
{
   return new SimpleTableIterator(this);
 }
Status rocksdb::SimpleTableReader::Open (const Options & options, const EnvOptions & soptions, unique_ptr< RandomAccessFile > && file, uint64_t file_size, unique_ptr< TableReader > * table_reader) static
Definition at line 189 of file simple_table_db_test.cc.
References rocksdb::DecodeFixed64(), rocksdb::SimpleTableReader::Rep::file, rocksdb::SimpleTableReader::Rep::GetInternalKeyLength(), rocksdb::SimpleTableReader::Rep::offset_length, rocksdb::Status::ok(), rocksdb::SimpleTableReader::Rep::options, and SimpleTableReader().
Referenced by rocksdb::SimpleTableFactory::GetTableReader().
{
   char footer_space[Rep::offset_length];
   Slice footer_input;
   Status s = file->Read(size - Rep::offset_length, Rep::offset_length,
                         &footer_input, footer_space);
   if (s.ok()) {
     uint64_t index_start_offset = DecodeFixed64(footer_space);
     int num_entries = (size - Rep::offset_length - index_start_offset)
         / (Rep::GetInternalKeyLength() + Rep::offset_length);
     SimpleTableReader::Rep* rep = new SimpleTableReader::Rep(soptions,
                                                              index_start_offset,
                                                              num_entries);
     rep->file = std::move(file);
     rep->options = options;
     table_reader->reset(new SimpleTableReader(rep));
   }
   return s;
 }
void rocksdb::SimpleTableReader::operator= (const TableReader &) private delete
bool rocksdb::SimpleTableReader::PrefixMayMatch (const Slice & internal_prefix) override virtual
Implements rocksdb::TableReader.
Definition at line 221 of file simple_table_db_test.cc.
{
   return true;
 }
void rocksdb::SimpleTableReader::SetupForCompaction () override virtual
Implements rocksdb::TableReader.
Definition at line 214 of file simple_table_db_test.cc.
{
 }
bool rocksdb::SimpleTableReader::TEST_KeyInCache (const ReadOptions & options, const Slice & key) override virtual
Implements rocksdb::TableReader.
Definition at line 298 of file simple_table_db_test.cc.
{
   return false;
 }
Friends And Related Function Documentation
friend class SimpleTableIterator friend
Definition at line 110 of file simple_table_db_test.cc.
Referenced by Get(), and NewIterator().
friend class TableCache friend
Definition at line 109 of file simple_table_db_test.cc.
Member Data Documentation
Rep* rocksdb::SimpleTableReader::rep_ private
Definition at line 103 of file simple_table_db_test.cc.
Referenced by GetOffset(), GetTableProperties(), rocksdb::SimpleTableIterator::key(), rocksdb::SimpleTableIterator::Next(), SimpleTableReader(), rocksdb::SimpleTableIterator::Valid(), and ~SimpleTableReader().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/db/simple_table_db_test.cc