rippled: ripple::JobTypeData Struct Reference
ripple::JobTypeData Struct Reference
#include <JobTypeData.h>
Public Member Functions
JobTypeData (JobTypeInfo const &info_, beast::insight::Collector::ptr const &collector) noexcept
JobTypeData (JobTypeData const &other)=delete
JobTypeData & operator= (JobTypeData const &other)=delete
std::string name () const
JobType type () const
LoadMonitor & load ()
LoadMonitor::Stats stats ()
Public Attributes
JobTypeInfo const & info
int waiting
int running
int deferred
beast::insight::Event dequeue
beast::insight::Event execute
Private Attributes
LoadMonitor m_load
beast::insight::Collector::ptr m_collector
Detailed Description
Definition at line 28 of file JobTypeData.h.
Constructor & Destructor Documentation
ripple::JobTypeData::JobTypeData (JobTypeInfo const & info_, beast::insight::Collector::ptr const & collector) inline explicit noexcept
Definition at line 53 of file JobTypeData.h.
References dequeue, execute, ripple::JobTypeInfo::getAverageLatency(), ripple::JobTypeInfo::getPeakLatency(), info, m_collector, m_load, ripple::JobTypeInfo::name(), ripple::LoadMonitor::setTargetLatency(), and ripple::JobTypeInfo::special().
         : m_collector (collector)
         , info (info_)
         , waiting (0)
         , running (0)
         , deferred (0)
     {
         m_load.setTargetLatency (
             info.getAverageLatency (),
             info.getPeakLatency());
         if (!info.special ())
         {
             dequeue = m_collector->make_event (info.name () + "_q");
             execute = m_collector->make_event (info.name ());
         }
     }
ripple::JobTypeData::JobTypeData (JobTypeData const & other) delete
Member Function Documentation
LoadMonitor& ripple::JobTypeData::load () inline
Definition at line 86 of file JobTypeData.h.
References m_load.
Referenced by ripple::JobQueueImp::addJob().
     {
         return m_load;
     }
std::string ripple::JobTypeData::name () const inline
Definition at line 76 of file JobTypeData.h.
References info, and ripple::JobTypeInfo::name().
Referenced by ripple::JobQueueImp::getJson(), and ripple::JobQueueImp::processTask().
     {
         return info.name ();
     }
JobTypeData& ripple::JobTypeData::operator= (JobTypeData const & other) delete
LoadMonitor::Stats ripple::JobTypeData::stats () inline
Definition at line 91 of file JobTypeData.h.
References ripple::LoadMonitor::getStats(), and m_load.
Referenced by ripple::JobQueueImp::getJson().
     {
         return m_load.getStats ();
     }
JobType ripple::JobTypeData::type () const inline
Definition at line 81 of file JobTypeData.h.
References info, and ripple::JobTypeInfo::type().
Referenced by ripple::JobQueueImp::getNextJob().
     {
         return info.type ();
     }
Member Data Documentation
int ripple::JobTypeData::deferred
Definition at line 47 of file JobTypeData.h.
Referenced by ripple::JobQueueImp::finishJob().
beast::insight::Event ripple::JobTypeData::dequeue
Definition at line 50 of file JobTypeData.h.
Referenced by JobTypeData(), and ripple::JobQueueImp::on_dequeue().
beast::insight::Event ripple::JobTypeData::execute
Definition at line 51 of file JobTypeData.h.
Referenced by JobTypeData(), and ripple::JobQueueImp::on_execute().
JobTypeInfo const& ripple::JobTypeData::info
Definition at line 38 of file JobTypeData.h.
Referenced by JobTypeData(), name(), ripple::JobQueueImp::processTask(), and type().
beast::insight::Collector::ptr ripple::JobTypeData::m_collector private
Definition at line 34 of file JobTypeData.h.
Referenced by JobTypeData().
LoadMonitor ripple::JobTypeData::m_load private
Definition at line 31 of file JobTypeData.h.
Referenced by JobTypeData(), load(), and stats().
int ripple::JobTypeData::running
Definition at line 44 of file JobTypeData.h.
Referenced by ripple::JobQueueImp::finishJob(), ripple::JobQueueImp::getJson(), and ripple::JobQueueImp::getNextJob().
int ripple::JobTypeData::waiting
Definition at line 41 of file JobTypeData.h.
Referenced by ripple::JobQueueImp::finishJob(), ripple::JobQueueImp::getJson(), and ripple::JobQueueImp::getNextJob().
The documentation for this struct was generated from the following file:
rippled/src/ripple_core/functional/JobTypeData.h