rippled: ripple::STHash160 Class Reference
ripple::STHash160 Class Reference
#include <SerializedTypes.h>
Public Member Functions
STHash160 (const uint160 &v)
STHash160 (SField::ref n, const uint160 &v)
STHash160 (SField::ref n, const char *v)
STHash160 (SField::ref n, const std::string &v)
STHash160 (SField::ref n)
STHash160 ()
SerializedTypeID getSType () const
virtual std::string getText () const
void add (Serializer &s) const
const uint160 & getValue () const
void setValue (const uint160 &v)
operator uint160 () const
virtual bool isEquivalent (const SerializedType &t) const
virtual bool isDefault () const
Public Member Functions inherited from ripple::SerializedType
SerializedType ()
SerializedType (SField::ref n)
virtual ~SerializedType ()
void setFName (SField::ref n)
SField::ref getFName () const
std::string getName () const
std::unique_ptr< SerializedType > clone () const
virtual std::string getFullText () const
virtual Json::Value getJson (int) const
void addFieldID (Serializer &s) const
SerializedType & operator= (const SerializedType &t)
bool operator== (const SerializedType &t) const
bool operator!= (const SerializedType &t) const
template<class D >
D & downcast ()
template<class D >
D const & downcast () const
Static Public Member Functions
static std::unique_ptr
< SerializedType > deserialize (SerializerIterator &sit, SField::ref name)
Static Public Member Functions inherited from ripple::SerializedType
static std::unique_ptr
< SerializedType > deserialize (SField::ref name)
Private Member Functions
STHash160 * duplicate () const
Static Private Member Functions
static STHash160 * construct (SerializerIterator &, SField::ref name)
Private Attributes
uint160 value
Additional Inherited Members
Protected Attributes inherited from ripple::SerializedType
SField::ptr fName
Detailed Description
Definition at line 915 of file SerializedTypes.h.
Constructor & Destructor Documentation
ripple::STHash160::STHash160 (const uint160 & v) inline
Definition at line 918 of file SerializedTypes.h.
                                  : value (v)
     {
         ;
     }
ripple::STHash160::STHash160 (SField::ref n, const uint160 & v) inline
Definition at line 922 of file SerializedTypes.h.
                                               : SerializedType (n), value (v)
     {
         ;
     }
ripple::STHash160::STHash160 (SField::ref n, const char * v) inline
Definition at line 926 of file SerializedTypes.h.
References ripple::base_uint< BITS >::SetHex(), and value.
                                            : SerializedType (n)
     {
         value.SetHex (v);
     }
ripple::STHash160::STHash160 (SField::ref n, const std::string & v) inline
Definition at line 930 of file SerializedTypes.h.
References ripple::base_uint< BITS >::SetHex(), and value.
                                                 : SerializedType (n)
     {
         value.SetHex (v);
     }
ripple::STHash160::STHash160 (SField::ref n) inline
Definition at line 934 of file SerializedTypes.h.
                             : SerializedType (n)
     {
         ;
     }
ripple::STHash160::STHash160 () inline
Definition at line 938 of file SerializedTypes.h.
Referenced by construct(), and duplicate().
     {
         ;
     }
Member Function Documentation
void ripple::STHash160::add (Serializer & s) const inline virtual
Reimplemented from ripple::SerializedType.
Definition at line 952 of file SerializedTypes.h.
References ripple::Serializer::add160(), and value.
     {
         s.add160 (value);
     }
STHash160 * ripple::STHash160::construct (SerializerIterator & u, SField::ref name) static private
Definition at line 255 of file SerializedTypes.cpp.
References ripple::SerializerIterator::get160(), and STHash160().
Referenced by deserialize().
 {
     return new STHash160 (name, u.get160 ());
 }
static std::unique_ptr<SerializedType> ripple::STHash160::deserialize (SerializerIterator & sit, SField::ref name) inline static
Definition at line 942 of file SerializedTypes.h.
References construct().
Referenced by ripple::STObject::makeDeserializedObject().
     {
         return std::unique_ptr<SerializedType> (construct (sit, name));
     }
STHash160* ripple::STHash160::duplicate () const inline private virtual
Reimplemented from ripple::SerializedType.
Definition at line 979 of file SerializedTypes.h.
References STHash160().
     {
         return new STHash160 (*this);
     }
SerializedTypeID ripple::STHash160::getSType () const inline virtual
Reimplemented from ripple::SerializedType.
Definition at line 947 of file SerializedTypes.h.
     {
         return STI_HASH160;
     }
std::string ripple::STHash160::getText () const virtual
Reimplemented from ripple::SerializedType.
Definition at line 260 of file SerializedTypes.cpp.
References ripple::base_uint< BITS >::GetHex(), and value.
 {
     return value.GetHex ();
 }
const uint160& ripple::STHash160::getValue () const inline
Definition at line 957 of file SerializedTypes.h.
References value.
Referenced by ripple::STObject::getFieldH160().
     {
         return value;
     }
virtual bool ripple::STHash160::isDefault () const inline virtual
Reimplemented from ripple::SerializedType.
Definition at line 971 of file SerializedTypes.h.
References ripple::base_uint< BITS >::isZero(), and value.
     {
         return value.isZero ();
     }
bool ripple::STHash160::isEquivalent (const SerializedType & t) const virtual
Reimplemented from ripple::SerializedType.
Definition at line 265 of file SerializedTypes.cpp.
References value.
 {
     const STHash160* v = dynamic_cast<const STHash160*> (&t);
     return v && (value == v->value);
 }
ripple::STHash160::operator uint160 () const inline
Definition at line 966 of file SerializedTypes.h.
References value.
     {
         return value;
     }
void ripple::STHash160::setValue (const uint160 & v) inline
Definition at line 961 of file SerializedTypes.h.
References value.
Referenced by ripple::STObject::setFieldH160().
     {
         value = v;
     }
Member Data Documentation
uint160 ripple::STHash160::value private
Definition at line 977 of file SerializedTypes.h.
Referenced by add(), getText(), getValue(), isDefault(), isEquivalent(), operator uint160(), setValue(), and STHash160().
The documentation for this class was generated from the following files:
rippled/src/ripple_data/protocol/SerializedTypes.h
rippled/src/ripple_data/protocol/SerializedTypes.cpp