rippled: ripple::NodeStore::TestBase::PredictableObjectFactory Class Reference
ripple::NodeStore::TestBase::PredictableObjectFactory Class Reference
#include <TestBase.h>
Public Member Functions
PredictableObjectFactory (std::int64_t seedValue)
NodeObject::Ptr createObject (int index)
Private Attributes
std::int64_t const m_seedValue
Detailed Description
Definition at line 43 of file TestBase.h.
Constructor & Destructor Documentation
ripple::NodeStore::TestBase::PredictableObjectFactory::PredictableObjectFactory (std::int64_t seedValue) inline explicit
Definition at line 46 of file TestBase.h.
             : m_seedValue (seedValue)
         {
         }
Member Function Documentation
NodeObject::Ptr ripple::NodeStore::TestBase::PredictableObjectFactory::createObject (int index) inline
Definition at line 51 of file TestBase.h.
References ripple::base_uint< BITS >::begin(), ripple::NodeObject::createObject(), beast::Random::fillBitsRandomly(), hash, ripple::hotACCOUNT_NODE, ripple::hotLEDGER, ripple::hotTRANSACTION, ripple::hotTRANSACTION_NODE, ripple::hotUNKNOWN, m_seedValue, ripple::NodeStore::TestBase::maxPayloadBytes, beast::Random::nextInt(), and ripple::base_uint< BITS >::size().
Referenced by ripple::NodeStore::TestBase::createPredictableBatch().
         {
             beast::Random r (m_seedValue + index);
             NodeObjectType type;
             switch (r.nextInt (4))
             {
             case 0: type = hotLEDGER; break;
             case 1: type = hotTRANSACTION; break;
             case 2: type = hotACCOUNT_NODE; break;
             case 3: type = hotTRANSACTION_NODE; break;
             default:
                 type = hotUNKNOWN;
                 break;
             };
             LedgerIndex ledgerIndex = 1 + r.nextInt (1024 * 1024);
             uint256 hash;
             r.fillBitsRandomly (hash.begin (), hash.size ());
             int const payloadBytes = 1 + r.nextInt (maxPayloadBytes);
             Blob data (payloadBytes);
             r.fillBitsRandomly (data.data (), payloadBytes);
             return NodeObject::createObject (type, ledgerIndex, data, hash);
         }
Member Data Documentation
std::int64_t const ripple::NodeStore::TestBase::PredictableObjectFactory::m_seedValue private
Definition at line 82 of file TestBase.h.
Referenced by createObject().
The documentation for this class was generated from the following file:
rippled/src/ripple_core/nodestore/tests/TestBase.h