rippled: ripple::STArray Class Reference
ripple::STArray Class Reference
#include <SerializedObject.h>
Public Types
typedef boost::ptr_vector
< STObject > vector
typedef boost::ptr_vector
< STObject >::iterator iterator
typedef boost::ptr_vector
< STObject >::const_iterator const_iterator
typedef boost::ptr_vector
< STObject >::reverse_iterator reverse_iterator
typedef boost::ptr_vector
< STObject >
::const_reverse_iterator const_reverse_iterator
typedef boost::ptr_vector
< STObject >::size_type size_type
Public Member Functions
STArray ()
STArray (int n)
STArray (SField::ref f)
STArray (SField::ref f, int n)
STArray (SField::ref f, const vector &v)
STArray (vector &v)
const vector & getValue () const
vector & getValue ()
void push_back (const STObject &object)
STObject & operator[] (int j)
const STObject & operator[] (int j) const
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
size_type size () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
iterator erase (iterator pos)
STObject & front ()
const STObject & front () const
STObject & back ()
const STObject & back () const
void pop_back ()
bool empty () const
void clear ()
void swap (STArray &a)
virtual std::string getFullText () const
virtual std::string getText () const
virtual Json::Value getJson (int) const
virtual void add (Serializer &s) const
void sort (bool(*compare)(const STObject &o1, const STObject &o2))
bool operator== (const STArray &s)
bool operator!= (const STArray &s)
virtual SerializedTypeID getSType () const
virtual bool isEquivalent (const SerializedType &t) const
virtual bool isDefault () const
Public Member Functions inherited from ripple::SerializedType
SerializedType ()
SerializedType (SField::ref n)
virtual ~SerializedType ()
void setFName (SField::ref n)
SField::ref getFName () const
std::string getName () const
std::unique_ptr< SerializedType > clone () const
void addFieldID (Serializer &s) const
SerializedType & operator= (const SerializedType &t)
bool operator== (const SerializedType &t) const
bool operator!= (const SerializedType &t) const
template<class D >
D & downcast ()
template<class D >
D const & downcast () const
Public Member Functions inherited from ripple::CountedObject< STArray >
CountedObject ()
CountedObject (CountedObject const &)
~CountedObject ()
Static Public Member Functions
static char const * getCountedObjectName ()
static std::unique_ptr
< SerializedType > deserialize (SerializerIterator &sit, SField::ref name)
Static Public Member Functions inherited from ripple::SerializedType
static std::unique_ptr
< SerializedType > deserialize (SField::ref name)
Private Member Functions
STArray * duplicate () const
Static Private Member Functions
static STArray * construct (SerializerIterator &, SField::ref)
Private Attributes
vector value
Additional Inherited Members
Protected Attributes inherited from ripple::SerializedType
SField::ptr fName
Detailed Description
Definition at line 338 of file SerializedObject.h.
Member Typedef Documentation
typedef boost::ptr_vector<STObject>::const_iterator ripple::STArray::const_iterator
Definition at line 347 of file SerializedObject.h.
typedef boost::ptr_vector<STObject>::const_reverse_iterator ripple::STArray::const_reverse_iterator
Definition at line 349 of file SerializedObject.h.
typedef boost::ptr_vector<STObject>::iterator ripple::STArray::iterator
Definition at line 346 of file SerializedObject.h.
typedef boost::ptr_vector<STObject>::reverse_iterator ripple::STArray::reverse_iterator
Definition at line 348 of file SerializedObject.h.
typedef boost::ptr_vector<STObject>::size_type ripple::STArray::size_type
Definition at line 350 of file SerializedObject.h.
typedef boost::ptr_vector<STObject> ripple::STArray::vector
Definition at line 345 of file SerializedObject.h.
Constructor & Destructor Documentation
ripple::STArray::STArray () inline
Definition at line 353 of file SerializedObject.h.
Referenced by construct(), and duplicate().
     {
         ;
     }
ripple::STArray::STArray (int n) inline explicit
Definition at line 357 of file SerializedObject.h.
References value.
     {
         value.reserve (n);
     }
ripple::STArray::STArray (SField::ref f) inline explicit
Definition at line 361 of file SerializedObject.h.
                                    : SerializedType (f)
     {
         ;
     }
ripple::STArray::STArray (SField::ref f, int n) inline
Definition at line 365 of file SerializedObject.h.
References value.
                                  : SerializedType (f)
     {
         value.reserve (n);
     }
ripple::STArray::STArray (SField::ref f, const vector & v) inline
Definition at line 369 of file SerializedObject.h.
                                             : SerializedType (f), value (v)
     {
         ;
     }
ripple::STArray::STArray (vector & v) inline explicit
Definition at line 373 of file SerializedObject.h.
                                   : value (v)
     {
         ;
     }
Member Function Documentation
void ripple::STArray::add (Serializer & s) const virtual
Reimplemented from ripple::SerializedType.
Definition at line 1201 of file SerializedObject.cpp.
References ripple::Serializer::addFieldID(), and value.
Referenced by ripple::isMemoOkay().
 {
     BOOST_FOREACH (const STObject & object, value)
     {
         object.addFieldID (s);
         object.add (s);
         s.addFieldID (STI_OBJECT, 1);
     }
 }
STObject& ripple::STArray::back () inline
Definition at line 455 of file SerializedObject.h.
References value.
Referenced by ripple::TransactionMetaSet::getAffectedNode(), and ripple::TransactionMetaSet::setAffectedNode().
     {
         return value.back ();
     }
const STObject& ripple::STArray::back () const inline
Definition at line 459 of file SerializedObject.h.
References value.
     {
         return value.back ();
     }
iterator ripple::STArray::begin () inline
Definition at line 407 of file SerializedObject.h.
References value.
Referenced by ripple::range_begin().
     {
         return value.begin ();
     }
const_iterator ripple::STArray::begin () const inline
Definition at line 411 of file SerializedObject.h.
References value.
     {
         return value.begin ();
     }
void ripple::STArray::clear () inline
Definition at line 471 of file SerializedObject.h.
References value.
Referenced by ripple::TransactionMetaSet::clear().
     {
         value.clear ();
     }
STArray * ripple::STArray::construct (SerializerIterator & sit, SField::ref field) static private
Definition at line 1224 of file SerializedObject.cpp.
References ripple::SerializerIterator::empty(), beast::field(), ripple::SField::getField(), ripple::SerializerIterator::getFieldID(), ripple::SField::isInvalid(), ripple::lsTRACE, STArray(), value, and WriteLog.
Referenced by deserialize().
 {
     vector value;
     while (!sit.empty ())
     {
         int type, field;
         sit.getFieldID (type, field);
         if ((type == STI_ARRAY) && (field == 1))
             break;
         SField::ref fn = SField::getField (type, field);
         if (fn.isInvalid ())
         {
             WriteLog (lsTRACE, STObject) << "Unknown field: " << type << "/" << field;
             throw std::runtime_error ("Unknown field");
         }
         value.push_back (new STObject (fn));
         value.rbegin ()->set (sit, 1);
     }
     return new STArray (field, value);
 }
static std::unique_ptr<SerializedType> ripple::STArray::deserialize (SerializerIterator & sit, SField::ref name) inline static
Definition at line 378 of file SerializedObject.h.
References construct().
Referenced by ripple::STObject::makeDeserializedObject().
     {
         return std::unique_ptr<SerializedType> (construct (sit, name));
     }
STArray* ripple::STArray::duplicate () const inline private virtual
Reimplemented from ripple::SerializedType.
Definition at line 509 of file SerializedObject.h.
References STArray().
     {
         return new STArray (*this);
     }
bool ripple::STArray::empty () const inline
Definition at line 467 of file SerializedObject.h.
References value.
     {
         return value.empty ();
     }
iterator ripple::STArray::end () inline
Definition at line 415 of file SerializedObject.h.
References value.
Referenced by ripple::range_end().
     {
         return value.end ();
     }
const_iterator ripple::STArray::end () const inline
Definition at line 419 of file SerializedObject.h.
References value.
     {
         return value.end ();
     }
iterator ripple::STArray::erase (iterator pos) inline
Definition at line 443 of file SerializedObject.h.
References value.
     {
         return value.erase (pos);
     }
STObject& ripple::STArray::front () inline
Definition at line 447 of file SerializedObject.h.
References value.
     {
         return value.front ();
     }
const STObject& ripple::STArray::front () const inline
Definition at line 451 of file SerializedObject.h.
References value.
     {
         return value.front ();
     }
static char const* ripple::STArray::getCountedObjectName () inline static
Definition at line 343 of file SerializedObject.h.
 { return "STArray"; }
std::string ripple::STArray::getFullText () const virtual
Reimplemented from ripple::SerializedType.
Definition at line 1143 of file SerializedObject.cpp.
References beast.util.Iter::first(), ripple::STObject::getFullText(), and value.
Referenced by isEquivalent().
 {
     std::string r = "[";
     bool first = true;
     BOOST_FOREACH (const STObject & o, value)
     {
         if (!first)
             r += ",";
         r += o.getFullText ();
         first = false;
     }
     r += "]";
     return r;
 }
Json::Value ripple::STArray::getJson (int p) const virtual
Reimplemented from ripple::SerializedType.
Definition at line 1179 of file SerializedObject.cpp.
References Json::Value::append(), Json::arrayValue, ripple::SerializedType::getFName(), getSType(), Json::objectValue, ripple::STI_NOTPRESENT, and value.
 {
     Json::Value v = Json::arrayValue;
     int index = 1;
     BOOST_FOREACH (const STObject & object, value)
     {
         if (object.getSType () != STI_NOTPRESENT)
         {
             Json::Value inner = Json::objectValue;
             if (!object.getFName ().hasName ())
                 inner[beast::lexicalCast <std::string> (index)] = object.getJson (p);
             else
                 inner[object.getName ()] = object.getJson (p);
             v.append (inner);
             index++;
         }
     }
     return v;
 }
virtual SerializedTypeID ripple::STArray::getSType () const inline virtual
Reimplemented from ripple::SerializedType.
Definition at line 496 of file SerializedObject.h.
Referenced by getJson().
     {
         return STI_ARRAY;
     }
std::string ripple::STArray::getText () const virtual
Reimplemented from ripple::SerializedType.
Definition at line 1161 of file SerializedObject.cpp.
References beast.util.Iter::first(), ripple::STObject::getText(), and value.
 {
     std::string r = "[";
     bool first = true;
     BOOST_FOREACH (const STObject & o, value)
     {
         if (!first)
             r += ",";
         r += o.getText ();
         first = false;
     }
     r += "]";
     return r;
 }
const vector& ripple::STArray::getValue () const inline
Definition at line 383 of file SerializedObject.h.
References value.
     {
         return value;
     }
vector& ripple::STArray::getValue () inline
Definition at line 387 of file SerializedObject.h.
References value.
     {
         return value;
     }
virtual bool ripple::STArray::isDefault () const inline virtual
Reimplemented from ripple::SerializedType.
Definition at line 501 of file SerializedObject.h.
References value.
     {
         return value.empty ();
     }
bool ripple::STArray::isEquivalent (const SerializedType & t) const virtual
Reimplemented from ripple::SerializedType.
Definition at line 1211 of file SerializedObject.cpp.
References getFullText(), ripple::lsDEBUG, value, and WriteLog.
 {
     const STArray* v = dynamic_cast<const STArray*> (&t);
     if (!v)
     {
         WriteLog (lsDEBUG, STObject) << "notEquiv " << getFullText() << " not array";
         return false;
     }
     return value == v->value;
 }
bool ripple::STArray::operator!= (const STArray & s) inline
Definition at line 491 of file SerializedObject.h.
References value.
     {
         return value != s.value;
     }
bool ripple::STArray::operator== (const STArray & s) inline
Definition at line 487 of file SerializedObject.h.
References value.
     {
         return value == s.value;
     }
STObject& ripple::STArray::operator[] (int j) inline
Definition at line 399 of file SerializedObject.h.
References value.
     {
         return value[j];
     }
const STObject& ripple::STArray::operator[] (int j) const inline
Definition at line 403 of file SerializedObject.h.
References value.
     {
         return value[j];
     }
void ripple::STArray::pop_back () inline
Definition at line 463 of file SerializedObject.h.
References value.
     {
         value.pop_back ();
     }
void ripple::STArray::push_back (const STObject & object) inline
Definition at line 395 of file SerializedObject.h.
References value.
Referenced by ripple::TransactionMetaSet::getAffectedNode(), ripple::STParsedJSON::parse(), and ripple::TransactionMetaSet::setAffectedNode().
     {
         value.push_back (object.oClone ().release ());
     }
reverse_iterator ripple::STArray::rbegin () inline
Definition at line 427 of file SerializedObject.h.
References value.
     {
         return value.rbegin ();
     }
const_reverse_iterator ripple::STArray::rbegin () const inline
Definition at line 431 of file SerializedObject.h.
References value.
     {
         return value.rbegin ();
     }
reverse_iterator ripple::STArray::rend () inline
Definition at line 435 of file SerializedObject.h.
References value.
     {
         return value.rend ();
     }
const_reverse_iterator ripple::STArray::rend () const inline
Definition at line 439 of file SerializedObject.h.
References value.
     {
         return value.rend ();
     }
size_type ripple::STArray::size () const inline
Definition at line 423 of file SerializedObject.h.
References value.
     {
         return value.size ();
     }
void ripple::STArray::sort (bool(*)(const STObject &o1, const STObject &o2) compare)
Definition at line 1251 of file SerializedObject.cpp.
References ripple::compare(), and value.
Referenced by ripple::TransactionMetaSet::addRaw().
 {
     value.sort (compare);
 }
void ripple::STArray::swap (STArray & a) inline
Definition at line 475 of file SerializedObject.h.
References value.
Referenced by ripple::TransactionMetaSet::swap().
     {
         value.swap (a.value);
     }
Member Data Documentation
vector ripple::STArray::value private
Definition at line 507 of file SerializedObject.h.
Referenced by add(), back(), begin(), clear(), construct(), empty(), end(), erase(), front(), getFullText(), getJson(), getText(), getValue(), isDefault(), isEquivalent(), operator!=(), operator==(), operator[](), pop_back(), push_back(), rbegin(), rend(), size(), sort(), STArray(), and swap().
The documentation for this class was generated from the following files:
rippled/src/ripple_data/protocol/SerializedObject.h
rippled/src/ripple_data/protocol/SerializedObject.cpp