rippled: rocksdb::StopWatch Class Reference
rocksdb::StopWatch Class Reference
#include <stop_watch.h>
Public Member Functions
StopWatch (Env *const env, std::shared_ptr< Statistics > statistics=nullptr, const Histograms histogram_name=DB_GET)
uint64_t ElapsedMicros ()
~StopWatch ()
Private Attributes
Env *const env_
const uint64_t start_time_
std::shared_ptr< Statistics > statistics_
const Histograms histogram_name_
Detailed Description
Definition at line 13 of file stop_watch.h.
Constructor & Destructor Documentation
rocksdb::StopWatch::StopWatch (Env *const env, std::shared_ptr< Statistics > statistics = nullptr, const Histograms histogram_name = DB_GET) inline
Definition at line 15 of file stop_watch.h.
                                               :
       env_(env),
       start_time_(env->NowMicros()),
       statistics_(statistics),
       histogram_name_(histogram_name) {}
rocksdb::StopWatch::~StopWatch () inline
Definition at line 30 of file stop_watch.h.
References ElapsedMicros(), histogram_name_, and statistics_.
                {
     if (statistics_) {
       statistics_->measureTime(histogram_name_, ElapsedMicros());
     }
   }
Member Function Documentation
uint64_t rocksdb::StopWatch::ElapsedMicros () inline
Definition at line 26 of file stop_watch.h.
References env_, rocksdb::Env::NowMicros(), and start_time_.
Referenced by rocksdb::DBImpl::MakeRoomForWrite(), rocksdb::TEST(), and ~StopWatch().
{
     return env_->NowMicros() - start_time_;
   }
Member Data Documentation
Env* const rocksdb::StopWatch::env_ private
Definition at line 37 of file stop_watch.h.
Referenced by ElapsedMicros().
const Histograms rocksdb::StopWatch::histogram_name_ private
Definition at line 40 of file stop_watch.h.
Referenced by ~StopWatch().
const uint64_t rocksdb::StopWatch::start_time_ private
Definition at line 38 of file stop_watch.h.
Referenced by ElapsedMicros().
std::shared_ptr<Statistics> rocksdb::StopWatch::statistics_ private
Definition at line 39 of file stop_watch.h.
Referenced by ~StopWatch().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/util/stop_watch.h