rippled: beast::LinuxStatsHelpers Namespace Reference
beast::LinuxStatsHelpers Namespace Reference
Functions
String getCpuInfo (const char *const key)
Function Documentation
String beast::LinuxStatsHelpers::getCpuInfo (const char *const key)
Definition at line 56 of file linux_SystemStats.cpp.
References beast::String::empty, beast::File::readLines(), beast::StringArray::size(), and beast::StringArray::trim().
     {
         StringArray lines;
         File ("/proc/cpuinfo").readLines (lines);
         for (int i = lines.size(); --i >= 0;) // (NB - it's important that this runs in reverse order)
             if (lines[i].startsWithIgnoreCase (key))
                 return lines[i].fromFirstOccurrenceOf (":", false, false).trim();
         return String::empty;
     }