rippled: ripple::Serializer Class Reference
ripple::Serializer Class Reference
#include <Serializer.h>
Public Types
typedef boost::shared_ptr
< Serializer > pointer
Public Member Functions
Serializer (int n=256)
Serializer (Blob const &data)
Serializer (const std::string &data)
Serializer (Blob::iterator begin, Blob::iterator end)
Serializer (Blob::const_iterator begin, Blob::const_iterator end)
int add8 (unsigned char byte)
int add16 (std::uint16_t)
int add32 (std::uint32_t)
int add64 (std::uint64_t)
int add128 (const uint128 &)
int add160 (const uint160 &)
int add256 (uint256 const &)
int addRaw (Blob const &vector)
int addRaw (const void *ptr, int len)
int addRaw (const Serializer &s)
int addZeros (size_t uBytes)
int addVL (Blob const &vector)
int addVL (const std::string &string)
int addVL (const void *ptr, int len)
bool get8 (int &, int offset) const
bool get8 (unsigned char &, int offset) const
bool get16 (std::uint16_t &, int offset) const
bool get32 (std::uint32_t &, int offset) const
bool get64 (std::uint64_t &, int offset) const
bool get128 (uint128 &, int offset) const
bool get160 (uint160 &, int offset) const
bool get256 (uint256 &, int offset) const
uint256 get256 (int offset) const
bool getRaw (Blob &, int offset, int length) const
Blob getRaw (int offset, int length) const
bool getVL (Blob &objectVL, int offset, int &length) const
bool getVLLength (int &length, int offset) const
bool getFieldID (int &type, int &name, int offset) const
int addFieldID (int type, int name)
int addFieldID (SerializedTypeID type, int name)
uint160 getRIPEMD160 (int size=-1) const
uint256 getSHA256 (int size=-1) const
uint256 getSHA512Half (int size=-1) const
uint256 getPrefixHash (std::uint32_t prefix) const
Blob const & peekData () const
Blob getData () const
Blob & modData ()
int getCapacity () const
int getDataLength () const
const void * getDataPtr () const
void * getDataPtr ()
int getLength () const
std::string getString () const
void secureErase ()
void erase ()
int removeLastByte ()
bool chop (int num)
Blob::iterator begin ()
Blob::iterator end ()
Blob::const_iterator begin () const
Blob::const_iterator end () const
Blob::size_type size () const
void reserve (size_t n)
void resize (size_t n)
size_t capacity () const
bool operator== (Blob const &v)
bool operator!= (Blob const &v)
bool operator== (const Serializer &v)
bool operator!= (const Serializer &v)
std::string getHex () const
Static Public Member Functions
static uint256 getSHA512Half (const_byte_view v)
static uint256 getSHA512Half (const unsigned char *data, int len)
static uint256 getPrefixHash (std::uint32_t prefix, const unsigned char *data, int len)
static uint256 getPrefixHash (std::uint32_t prefix, Blob const &data)
static uint256 getPrefixHash (std::uint32_t prefix, const std::string &strData)
static Blob encodeVL (int length)
static int lengthVL (int length)
static int encodeLengthLength (int length)
static int decodeLengthLength (int b1)
static int decodeVLLength (int b1)
static int decodeVLLength (int b1, int b2)
static int decodeVLLength (int b1, int b2, int b3)
static void TestSerializer ()
Protected Attributes
Blob mData
Detailed Description
Definition at line 29 of file Serializer.h.
Member Typedef Documentation
typedef boost::shared_ptr<Serializer> ripple::Serializer::pointer
Definition at line 32 of file Serializer.h.
Constructor & Destructor Documentation
ripple::Serializer::Serializer (int n = 256) inline
Definition at line 38 of file Serializer.h.
References mData.
     {
         mData.reserve (n);
     }
ripple::Serializer::Serializer (Blob const & data) inline
Definition at line 42 of file Serializer.h.
                                   : mData (data)
     {
         ;
     }
ripple::Serializer::Serializer (const std::string & data) inline
Definition at line 46 of file Serializer.h.
                                        : mData (data.data (), (data.data ()) + data.size ())
     {
         ;
     }
ripple::Serializer::Serializer (Blob::iterator begin, Blob::iterator end) inline
Definition at line 50 of file Serializer.h.
                                                         :
         mData (begin, end)
     {
         ;
     }
ripple::Serializer::Serializer (Blob::const_iterator begin, Blob::const_iterator end) inline
Definition at line 55 of file Serializer.h.
                                                                     :
         mData (begin, end)
     {
         ;
     }
Member Function Documentation
int ripple::Serializer::add128 (const uint128 & i)
Definition at line 68 of file Serializer.cpp.
References ripple::base_uint< BITS >::begin(), ripple::base_uint< BITS >::end(), and mData.
Referenced by ripple::STHash128::add(), and ripple::CKey::GenerateRootDeterministicKey().
 {
     int ret = mData.size ();
     mData.insert (mData.end (), i.begin (), i.end ());
     return ret;
 }
int ripple::Serializer::add16 (std::uint16_t i)
Definition at line 36 of file Serializer.cpp.
References mData.
Referenced by ripple::STUInt16::add(), ripple::Ledger::getAccountRootIndex(), ripple::Ledger::getBookBase(), ripple::Ledger::getDirNodeIndex(), ripple::Ledger::getGeneratorIndex(), ripple::Ledger::getLedgerFeatureIndex(), ripple::Ledger::getLedgerFeeIndex(), ripple::Ledger::getLedgerHashIndex(), ripple::Ledger::getNicknameIndex(), ripple::Ledger::getOfferIndex(), ripple::Ledger::getOwnerDirIndex(), and ripple::Ledger::getRippleStateIndex().
 {
     int ret = mData.size ();
     mData.push_back (static_cast<unsigned char> (i >> 8));
     mData.push_back (static_cast<unsigned char> (i & 0xff));
     return ret;
 }
int ripple::Serializer::add160 (const uint160 & i)
Definition at line 75 of file Serializer.cpp.
References ripple::base_uint< BITS >::begin(), ripple::base_uint< BITS >::end(), and mData.
Referenced by ripple::STAmount::add(), ripple::STHash160::add(), ripple::STPathSet::add(), ripple::STAmount::createHumanCurrency(), ripple::Ledger::getAccountRootIndex(), ripple::Ledger::getBookBase(), ripple::Ledger::getGeneratorIndex(), ripple::Ledger::getOfferIndex(), ripple::Ledger::getOwnerDirIndex(), and ripple::Ledger::getRippleStateIndex().
 {
     int ret = mData.size ();
     mData.insert (mData.end (), i.begin (), i.end ());
     return ret;
 }
int ripple::Serializer::add256 (uint256 const & i)
Definition at line 82 of file Serializer.cpp.
References ripple::base_uint< BITS >::begin(), ripple::base_uint< BITS >::end(), and mData.
Referenced by ripple::STHash256::add(), ripple::SHAMapNode::addIDRaw(), ripple::SHAMapTreeNode::addRaw(), ripple::Ledger::addRaw(), ripple::LedgerProposal::computeSuppressionID(), ripple::Ledger::getDirNodeIndex(), ripple::Ledger::getNicknameIndex(), ripple::LedgerProposal::getSigningHash(), ripple::Serializer_test::run(), and ripple::SHAMapTreeNode::updateHash().
 {
     int ret = mData.size ();
     mData.insert (mData.end (), i.begin (), i.end ());
     return ret;
 }
int ripple::Serializer::add32 (std::uint32_t i)
Definition at line 44 of file Serializer.cpp.
References mData.
Referenced by ripple::STUInt32::add(), ripple::SHAMapTreeNode::addRaw(), ripple::Ledger::addRaw(), ripple::LedgerProposal::computeSuppressionID(), ripple::CKey::GenerateRootDeterministicKey(), ripple::STObject::getHash(), ripple::Ledger::getLedgerHashIndex(), ripple::Ledger::getOfferIndex(), ripple::LedgerProposal::getSigningHash(), ripple::STObject::getSigningHash(), ripple::ConsensusTransSetSF::haveNode(), ripple::RadixMap::make_random_item(), ripple::NetworkOPsImp::makeFetchPack(), ripple::makeHash(), ripple::SHAMapSync_test::makeRandomAS(), ripple::Serializer_test::run(), ripple::Ledger::saveValidatedLedger(), ripple::InboundLedger::takeBase(), ripple::Ledger::updateHash(), and ripple::SHAMapTreeNode::updateHash().
 {
     int ret = mData.size ();
     mData.push_back (static_cast<unsigned char> (i >> 24));
     mData.push_back (static_cast<unsigned char> ((i >> 16) & 0xff));
     mData.push_back (static_cast<unsigned char> ((i >> 8) & 0xff));
     mData.push_back (static_cast<unsigned char> (i & 0xff));
     return ret;
 }
int ripple::Serializer::add64 (std::uint64_t i)
Definition at line 54 of file Serializer.cpp.
References mData.
Referenced by ripple::STUInt64::add(), ripple::STAmount::add(), ripple::Ledger::addRaw(), and ripple::Ledger::getDirNodeIndex().
 {
     int ret = mData.size ();
     mData.push_back (static_cast<unsigned char> (i >> 56));
     mData.push_back (static_cast<unsigned char> ((i >> 48) & 0xff));
     mData.push_back (static_cast<unsigned char> ((i >> 40) & 0xff));
     mData.push_back (static_cast<unsigned char> ((i >> 32) & 0xff));
     mData.push_back (static_cast<unsigned char> ((i >> 24) & 0xff));
     mData.push_back (static_cast<unsigned char> ((i >> 16) & 0xff));
     mData.push_back (static_cast<unsigned char> ((i >> 8) & 0xff));
     mData.push_back (static_cast<unsigned char> (i & 0xff));
     return ret;
 }
int ripple::Serializer::add8 (unsigned char byte)
Definition at line 266 of file Serializer.cpp.
References mData.
Referenced by ripple::STUInt8::add(), ripple::STPathSet::add(), ripple::SHAMapNode::addIDRaw(), ripple::SHAMapTreeNode::addRaw(), and ripple::Ledger::addRaw().
 {
     int ret = mData.size ();
     mData.push_back (byte);
     return ret;
 }
int ripple::Serializer::addFieldID (int type, int name)
Definition at line 193 of file Serializer.cpp.
References mData.
Referenced by ripple::STObject::add(), ripple::STArray::add(), addFieldID(), and ripple::SerializedType::addFieldID().
 {
     int ret = mData.size ();
     assert ((type > 0) && (type < 256) && (name > 0) && (name < 256));
     if (type < 16)
     {
         if (name < 16) // common type, common name
             mData.push_back (static_cast<unsigned char> ((type << 4) | name));
         else
         {
             // common type, uncommon name
             mData.push_back (static_cast<unsigned char> (type << 4));
             mData.push_back (static_cast<unsigned char> (name));
         }
     }
     else if (name < 16)
     {
         // uncommon type, common name
         mData.push_back (static_cast<unsigned char> (name));
         mData.push_back (static_cast<unsigned char> (type));
     }
     else
     {
         // uncommon type, uncommon name
         mData.push_back (static_cast<unsigned char> (0));
         mData.push_back (static_cast<unsigned char> (type));
         mData.push_back (static_cast<unsigned char> (name));
     }
     return ret;
 }
int ripple::Serializer::addFieldID (SerializedTypeID type, int name) inline
Definition at line 96 of file Serializer.h.
References addFieldID().
     {
         return addFieldID (static_cast<int> (type), name);
     }
int ripple::Serializer::addRaw (Blob const & vector)
Definition at line 89 of file Serializer.cpp.
References mData.
Referenced by ripple::SHAMap::addKnownNode(), ripple::SHAMapTreeNode::addRaw(), addVL(), ripple::RPCHandler::doLedgerHeader(), ripple::makeHash(), ripple::CKey::PassPhraseToKey(), ripple::Serializer_test::run(), and ripple::SHAMapTreeNode::updateHash().
 {
     int ret = mData.size ();
     mData.insert (mData.end (), vector.begin (), vector.end ());
     return ret;
 }
int ripple::Serializer::addRaw (const void * ptr, int len)
Definition at line 103 of file Serializer.cpp.
References mData.
 {
     int ret = mData.size ();
     mData.insert (mData.end (), (const char*) ptr, ((const char*)ptr) + len);
     return ret;
 }
int ripple::Serializer::addRaw (const Serializer & s)
Definition at line 96 of file Serializer.cpp.
References begin(), end(), and mData.
 {
     int ret = mData.size ();
     mData.insert (mData.end (), s.begin (), s.end ());
     return ret;
 }
int ripple::Serializer::addVL (Blob const & vector)
Definition at line 387 of file Serializer.cpp.
References addRaw(), encodeLengthLength(), encodeVL(), and mData.
Referenced by ripple::STVariableLength::add(), ripple::STVector256::add(), ripple::Ledger::addTransaction(), and ripple::LedgerProposal::computeSuppressionID().
 {
     int ret = addRaw (encodeVL (vector.size ()));
     addRaw (vector);
     assert (mData.size () == (ret + vector.size () + encodeLengthLength (vector.size ())));
     return ret;
 }
int ripple::Serializer::addVL (const std::string & string)
Definition at line 405 of file Serializer.cpp.
References addRaw(), and size().
 {
     int ret = addRaw (string.size ());
     if (!string.empty ())
         addRaw (string.data (), string.size ());
     return ret;
 }
int ripple::Serializer::addVL (const void * ptr, int len)
Definition at line 395 of file Serializer.cpp.
References addRaw(), and encodeVL().
 {
     int ret = addRaw (encodeVL (len));
     if (len)
         addRaw (ptr, len);
     return ret;
 }
int ripple::Serializer::addZeros (size_t uBytes)
Definition at line 26 of file Serializer.cpp.
References size().
Referenced by ripple::STAmount::currencyFromString().
 {
     int ret = mData.size ();
     while (uBytes--)
         mData.push_back (0);
     return ret;
 }
Blob ::iterator ripple::Serializer::begin () inline
Definition at line 174 of file Serializer.h.
References mData.
Referenced by ripple::SHAMapItem::addRaw(), addRaw(), ripple::NetworkOPsImp::getAccountTxs(), ripple::NetworkOPsImp::getTxsAccount(), ripple::InboundLedgersImp::gotStaleData(), and ripple::Transaction::transactionFromSQL().
     {
         return mData.begin ();
     }
Blob ::const_iterator ripple::Serializer::begin () const inline
Definition at line 182 of file Serializer.h.
References mData.
     {
         return mData.begin ();
     }
size_t ripple::Serializer::capacity () const inline
Definition at line 202 of file Serializer.h.
References mData.
     {
         return mData.capacity ();
     }
bool ripple::Serializer::chop (int num)
Definition at line 281 of file Serializer.cpp.
References mData.
Referenced by ripple::SHAMapTreeNode::SHAMapTreeNode().
 {
     if (bytes > mData.size ()) return false;
     mData.resize (mData.size () - bytes);
     return true;
 }
int ripple::Serializer::decodeLengthLength (int b1) static
Definition at line 536 of file Serializer.cpp.
Referenced by getVL(), and getVLLength().
 {
     if (b1 < 0) throw std::overflow_error ("b1<0");
     if (b1 <= 192) return 1;
     if (b1 <= 240) return 2;
     if (b1 <= 254) return 3;
     throw std::overflow_error ("b1>254");
 }
int ripple::Serializer::decodeVLLength (int b1) static
Definition at line 549 of file Serializer.cpp.
Referenced by getVL(), and getVLLength().
 {
     if (b1 < 0) throw std::overflow_error ("b1<0");
     if (b1 > 254) throw std::overflow_error ("b1>254");
     return b1;
 }
int ripple::Serializer::decodeVLLength (int b1, int b2) static
Definition at line 558 of file Serializer.cpp.
 {
     if (b1 < 193) throw std::overflow_error ("b1<193");
     if (b1 > 240) throw std::overflow_error ("b1>240");
     return 193 + (b1 - 193) * 256 + b2;
 }
int ripple::Serializer::decodeVLLength (int b1, int b2, int b3) static
Definition at line 567 of file Serializer.cpp.
 {
     if (b1 < 241) throw std::overflow_error ("b1<241");
     if (b1 > 254) throw std::overflow_error ("b1>254");
     return 12481 + (b1 - 241) * 65536 + b2 * 256 + b3;
 }
int ripple::Serializer::encodeLengthLength (int length) static
Definition at line 523 of file Serializer.cpp.
Referenced by addVL(), and lengthVL().
 {
     if (length < 0) throw std::overflow_error ("len<0");
     if (length <= 192) return 1;
     if (length <= 12480) return 2;
     if (length <= 918744) return 3;
     throw std::overflow_error ("len>918744");
 }
Blob ripple::Serializer::encodeVL (int length) static
Definition at line 496 of file Serializer.cpp.
Referenced by addVL().
 {
     unsigned char lenBytes[4];
     if (length <= 192)
     {
         lenBytes[0] = static_cast<unsigned char> (length);
         return Blob (&lenBytes[0], &lenBytes[1]);
     }
     else if (length <= 12480)
     {
         length -= 193;
         lenBytes[0] = 193 + static_cast<unsigned char> (length >> 8);
         lenBytes[1] = static_cast<unsigned char> (length & 0xff);
         return Blob (&lenBytes[0], &lenBytes[2]);
     }
     else if (length <= 918744)
     {
         length -= 12481;
         lenBytes[0] = 241 + static_cast<unsigned char> (length >> 16);
         lenBytes[1] = static_cast<unsigned char> ((length >> 8) & 0xff);
         lenBytes[2] = static_cast<unsigned char> (length & 0xff);
         return Blob (&lenBytes[0], &lenBytes[3]);
     }
     else throw std::overflow_error ("lenlen");
 }
Blob ::iterator ripple::Serializer::end () inline
Definition at line 178 of file Serializer.h.
References mData.
Referenced by ripple::SHAMapItem::addRaw(), addRaw(), and ripple::InboundLedgersImp::gotStaleData().
     {
         return mData.end ();
     }
Blob ::const_iterator ripple::Serializer::end () const inline
Definition at line 186 of file Serializer.h.
References mData.
     {
         return mData.end ();
     }
void ripple::Serializer::erase () inline
Definition at line 166 of file Serializer.h.
References mData.
Referenced by ripple::ValidationsImp::doWrite(), ripple::SHAMap::flushDirty(), ripple::PeerImp::getLedger(), ripple::SHAMap::getTrustedPath(), and secureErase().
     {
         mData.clear ();
     }
bool ripple::Serializer::get128 (uint128 & o, int offset) const
Definition at line 159 of file Serializer.cpp.
References ripple::base_uint< BITS >::begin(), and mData.
Referenced by ripple::SerializerIterator::get128().
 {
     if ((offset + (128 / 8)) > mData.size ()) return false;
     memcpy (o.begin (), & (mData.front ()) + offset, (128 / 8));
     return true;
 }
bool ripple::Serializer::get16 (std::uint16_t & o, int offset) const
Definition at line 110 of file Serializer.cpp.
References mData.
Referenced by ripple::SerializerIterator::get16().
 {
     if ((offset + 2) > mData.size ()) return false;
     const unsigned char* ptr = &mData[offset];
     o = *ptr++;
     o <<= 8;
     o |= *ptr;
     return true;
 }
bool ripple::Serializer::get160 (uint160 & o, int offset) const
Definition at line 167 of file Serializer.cpp.
References ripple::base_uint< BITS >::begin(), and mData.
Referenced by ripple::SerializerIterator::get160().
 {
     if ((offset + (160 / 8)) > mData.size ()) return false;
     memcpy (o.begin (), & (mData.front ()) + offset, (160 / 8));
     return true;
 }
bool ripple::Serializer::get256 (uint256 & o, int offset) const
Definition at line 175 of file Serializer.cpp.
References ripple::base_uint< BITS >::begin(), and mData.
Referenced by ripple::SerializerIterator::get256(), and ripple::SHAMapTreeNode::SHAMapTreeNode().
 {
     if ((offset + (256 / 8)) > mData.size ()) return false;
     memcpy (o.begin (), & (mData.front ()) + offset, (256 / 8));
     return true;
 }
uint256 ripple::Serializer::get256 (int offset) const
Definition at line 183 of file Serializer.cpp.
References ripple::base_uint< BITS >::begin(), and mData.
 {
     uint256 ret;
     if ((offset + (256 / 8)) > mData.size ()) return ret;
     memcpy (ret.begin (), & (mData.front ()) + offset, (256 / 8));
     return ret;
 }
bool ripple::Serializer::get32 (std::uint32_t & o, int offset) const
Definition at line 121 of file Serializer.cpp.
References mData.
Referenced by ripple::SerializerIterator::get32().
 {
     if ((offset + 4) > mData.size ()) return false;
     const unsigned char* ptr = &mData[offset];
     o = *ptr++;
     o <<= 8;
     o |= *ptr++;
     o <<= 8;
     o |= *ptr++;
     o <<= 8;
     o |= *ptr;
     return true;
 }
bool ripple::Serializer::get64 (std::uint64_t & o, int offset) const
Definition at line 136 of file Serializer.cpp.
References mData.
Referenced by ripple::SerializerIterator::get64().
 {
     if ((offset + 8) > mData.size ()) return false;
     const unsigned char* ptr = &mData[offset];
     o = *ptr++;
     o <<= 8;
     o |= *ptr++;
     o <<= 8;
     o |= *ptr++;
     o <<= 8;
     o |= *ptr++;
     o <<= 8;
     o |= *ptr++;
     o <<= 8;
     o |= *ptr++;
     o <<= 8;
     o |= *ptr++;
     o <<= 8;
     o |= *ptr;
     return true;
 }
bool ripple::Serializer::get8 (int & byte, int offset) const
Definition at line 273 of file Serializer.cpp.
References mData.
Referenced by ripple::SerializerIterator::get8(), getFieldID(), getVL(), getVLLength(), and ripple::SHAMapTreeNode::SHAMapTreeNode().
 {
     if (offset >= mData.size ()) return false;
     byte = mData[offset];
     return true;
 }
bool ripple::Serializer::get8 (unsigned char & , int offset) const
int ripple::Serializer::getCapacity () const inline
Definition at line 137 of file Serializer.h.
References mData.
     {
         return mData.capacity ();
     }
Blob ripple::Serializer::getData () const inline
Definition at line 129 of file Serializer.h.
References mData.
Referenced by ripple::NetworkOPsImp::getAccountTxs(), ripple::SHAMap::getTrustedPath(), ripple::NetworkOPsImp::getTxsAccount(), ripple::NetworkOPsImp::processTransactionCb(), ripple::NetworkOPsImp::runTransactionQueue(), and ripple::NetworkOPsImp::submitTransactionSync().
     {
         return mData;
     }
int ripple::Serializer::getDataLength () const inline
Definition at line 141 of file Serializer.h.
References mData.
Referenced by ripple::Ledger::addTransaction(), ripple::SHAMap::flushDirty(), and ripple::isMemoOkay().
     {
         return mData.size ();
     }
const void* ripple::Serializer::getDataPtr () const inline
Definition at line 145 of file Serializer.h.
References mData.
Referenced by ripple::PeerImp::getLedger(), getString(), and ripple::NetworkOPsImp::makeFetchPack().
     {
         return &mData.front ();
     }
void* ripple::Serializer::getDataPtr () inline
Definition at line 149 of file Serializer.h.
References mData.
     {
         return &mData.front ();
     }
bool ripple::Serializer::getFieldID (int & type, int & name, int offset) const
Definition at line 226 of file Serializer.cpp.
References get8(), ripple::lsWARNING, name, and WriteLog.
Referenced by ripple::SerializerIterator::getFieldID().
 {
     if (!get8 (type, offset))
     {
         WriteLog (lsWARNING, Serializer) << "gFID: unable to get type";
         return false;
     }
     name = type & 15;
     type >>= 4;
     if (type == 0)
     {
         // uncommon type
         if (!get8 (type, ++offset))
             return false;
         if ((type == 0) || (type < 16))
         {
             WriteLog (lsWARNING, Serializer) << "gFID: uncommon type out of range " << type;
             return false;
         }
     }
     if (name == 0)
     {
         // uncommon name
         if (!get8 (name, ++offset))
             return false;
         if ((name == 0) || (name < 16))
         {
             WriteLog (lsWARNING, Serializer) << "gFID: uncommon name out of range " << name;
             return false;
         }
     }
     return true;
 }
std::string ripple::Serializer::getHex () const inline
Definition at line 224 of file Serializer.h.
References mData.
     {
         std::stringstream h;
         for (unsigned char const& element : mData)
         {
             h <<
                 std::setw (2) <<
                 std::hex <<
                 std::setfill ('0') <<
                 static_cast<unsigned int>(element);
         }
         return h.str ();
     }
int ripple::Serializer::getLength () const inline
Definition at line 153 of file Serializer.h.
References mData.
Referenced by ripple::SerializerIterator::empty(), ripple::NetworkOPsImp::getAccountTxs(), ripple::PeerImp::getLedger(), ripple::NetworkOPsImp::getTxsAccount(), ripple::NetworkOPsImp::makeFetchPack(), ripple::NetworkOPsImp::processTransactionCb(), ripple::NetworkOPsImp::runTransactionQueue(), ripple::SHAMapTreeNode::SHAMapTreeNode(), and ripple::Transaction::transactionFromSQL().
     {
         return mData.size ();
     }
uint256 ripple::Serializer::getPrefixHash (std::uint32_t prefix, const unsigned char * data, int len) static
Definition at line 369 of file Serializer.cpp.
References SHA512_Final(), SHA512_Init(), and SHA512_Update().
Referenced by getPrefixHash(), ripple::Serializer_test::run(), ripple::SHAMapTreeNode::SHAMapTreeNode(), and ripple::SHAMapTreeNode::updateHash().
 {
     char be_prefix[4];
     be_prefix[0] = static_cast<unsigned char> (prefix >> 24);
     be_prefix[1] = static_cast<unsigned char> ((prefix >> 16) & 0xff);
     be_prefix[2] = static_cast<unsigned char> ((prefix >> 8) & 0xff);
     be_prefix[3] = static_cast<unsigned char> (prefix & 0xff);
     uint256 j[2];
     SHA512_CTX ctx;
     SHA512_Init (&ctx);
     SHA512_Update (&ctx, &be_prefix[0], 4);
     SHA512_Update (&ctx, data, len);
     SHA512_Final (reinterpret_cast<unsigned char*> (&j[0]), &ctx);
     return j[0];
 }
uint256 ripple::Serializer::getPrefixHash (std::uint32_t prefix) const inline
Definition at line 111 of file Serializer.h.
References getPrefixHash(), and mData.
     {
         return getPrefixHash (prefix, & (mData.front ()), mData.size ());
     }
static uint256 ripple::Serializer::getPrefixHash (std::uint32_t prefix, Blob const & data) inline static
Definition at line 115 of file Serializer.h.
References getPrefixHash().
     {
         return getPrefixHash (prefix, & (data.front ()), data.size ());
     }
static uint256 ripple::Serializer::getPrefixHash (std::uint32_t prefix, const std::string & strData) inline static
Definition at line 119 of file Serializer.h.
References getPrefixHash().
     {
         return getPrefixHash (prefix, reinterpret_cast<const unsigned char*> (strData.data ()), strData.size ());
     }
bool ripple::Serializer::getRaw (Blob & o, int offset, int length) const
Definition at line 304 of file Serializer.cpp.
References mData.
Referenced by ripple::SerializerIterator::getRaw(), and getVL().
 {
     if ((offset + length) > mData.size ()) return false;
     o.assign (mData.begin () + offset, mData.begin () + offset + length);
     return true;
 }
Blob ripple::Serializer::getRaw (int offset, int length) const
Definition at line 312 of file Serializer.cpp.
References mData.
 {
     Blob o;
     if ((offset + length) > mData.size ()) return o;
     o.assign (mData.begin () + offset, mData.begin () + offset + length);
     return o;
 }
uint160 ripple::Serializer::getRIPEMD160 (int size = -1) const
Definition at line 322 of file Serializer.cpp.
References mData.
Referenced by ripple::RadixMap::make_random_item(), and ripple::SHAMapSync_test::makeRandomAS().
 {
     uint160 ret;
     if ((size < 0) || (size > mData.size ())) size = mData.size ();
     RIPEMD160 (& (mData.front ()), size, (unsigned char*) &ret);
     return ret;
 }
uint256 ripple::Serializer::getSHA256 (int size = -1) const
Definition at line 332 of file Serializer.cpp.
References mData.
Referenced by ripple::Ledger::getNicknameHash().
 {
     uint256 ret;
     if ((size < 0) || (size > mData.size ())) size = mData.size ();
     SHA256 (& (mData.front ()), size, (unsigned char*) &ret);
     return ret;
 }
uint256 ripple::Serializer::getSHA512Half (int size = -1) const
Definition at line 342 of file Serializer.cpp.
References mData, and size().
Referenced by ripple::PeerImp::calculateSessionCookie(), ripple::ProofOfWorkFactoryImp::checkProof(), ripple::LedgerProposal::computeSuppressionID(), ripple::WalletAddTransactor::doApply(), ripple::SHAMap::flushDirty(), ripple::CKey::GenerateRootDeterministicKey(), ripple::Ledger::getAccountRootIndex(), ripple::Ledger::getBookBase(), ripple::Ledger::getDirNodeIndex(), ripple::NetworkOPsImp::getFetchPack(), ripple::Ledger::getGeneratorIndex(), ripple::STObject::getHash(), ripple::Ledger::getLedgerFeatureIndex(), ripple::Ledger::getLedgerFeeIndex(), ripple::Ledger::getLedgerHashIndex(), ripple::Ledger::getNicknameIndex(), ripple::Ledger::getOfferIndex(), ripple::Ledger::getOwnerDirIndex(), ripple::ProofOfWorkFactoryImp::getProof(), ripple::Ledger::getRippleStateIndex(), ripple::getSHA512Half(), ripple::LedgerProposal::getSigningHash(), ripple::STObject::getSigningHash(), ripple::ConsensusTransSetSF::haveNode(), ripple::makeHash(), ripple::FetchPack_test::on_fetch(), ripple::CKey::PassPhraseToKey(), ripple::UniqueNodeListImp::responseFetch(), ripple::Serializer_test::run(), ripple::RippleAddress_test::run(), ripple::SHAMapTreeNode::SHAMapTreeNode(), ripple::NodeStore::DatabaseImp::store(), ripple::Ledger::updateHash(), and ripple::SHAMapTreeNode::updateHash().
 {
     assert (size != 0);
     if (size == 0)
         return uint256();
     if (size < 0 || size > mData.size())
         return getSHA512Half (mData);
     return getSHA512Half (const_byte_view (
         mData.data(), mData.data() + size));
 }
uint256 ripple::Serializer::getSHA512Half (const_byte_view v) static
Definition at line 354 of file Serializer.cpp.
References beast::buffer_view< T, Tag >::data(), and beast::buffer_view< T, Tag >::size().
 {
     uint256 j[2];
     SHA512 (v.data(), v.size(),
         reinterpret_cast<unsigned char*> (j));
     return j[0];
 }
uint256 ripple::Serializer::getSHA512Half (const unsigned char * data, int len) static
Definition at line 362 of file Serializer.cpp.
 {
     uint256 j[2];
     SHA512 (data, len, (unsigned char*) j);
     return j[0];
 }
std::string ripple::Serializer::getString () const inline
Definition at line 157 of file Serializer.h.
References getDataPtr(), and size().
Referenced by ripple::SHAMapNode::getRawString().
     {
         return std::string (static_cast<const char*> (getDataPtr ()), size ());
     }
bool ripple::Serializer::getVL (Blob & objectVL, int offset, int & length) const
Definition at line 415 of file Serializer.cpp.
References decodeLengthLength(), decodeVLLength(), get8(), and getRaw().
Referenced by ripple::TransactionMaster::fetch(), and ripple::SerializerIterator::getVL().
 {
     int b1;
     if (!get8 (b1, offset++)) return false;
     int datLen, lenLen = decodeLengthLength (b1);
     try
     {
         if (lenLen == 1)
             datLen = decodeVLLength (b1);
         else if (lenLen == 2)
         {
             int b2;
             if (!get8 (b2, offset++)) return false;
             datLen = decodeVLLength (b1, b2);
         }
         else if (lenLen == 3)
         {
             int b2, b3;
             if (!get8 (b2, offset++)) return false;
             if (!get8 (b3, offset++)) return false;
             datLen = decodeVLLength (b1, b2, b3);
         }
         else return false;
     }
     catch (...)
     {
         return false;
     }
     length = lenLen + datLen;
     return getRaw (objectVL, offset, datLen);
 }
bool ripple::Serializer::getVLLength (int & length, int offset) const
Definition at line 456 of file Serializer.cpp.
References decodeLengthLength(), decodeVLLength(), and get8().
 {
     int b1;
     if (!get8 (b1, offset++)) return false;
     int lenLen = decodeLengthLength (b1);
     try
     {
         if (lenLen == 1)
             length = decodeVLLength (b1);
         else if (lenLen == 2)
         {
             int b2;
             if (!get8 (b2, offset++)) return false;
             length = decodeVLLength (b1, b2);
         }
         else if (lenLen == 3)
         {
             int b2, b3;
             if (!get8 (b2, offset++)) return false;
             if (!get8 (b3, offset++)) return false;
             length = decodeVLLength (b1, b2, b3);
         }
         else return false;
     }
     catch (...)
     {
         return false;
     }
     return true;
 }
static int ripple::Serializer::lengthVL (int length) inline static
Definition at line 241 of file Serializer.h.
References encodeLengthLength().
     {
         return length + encodeLengthLength (length);
     }
Blob& ripple::Serializer::modData () inline
Definition at line 133 of file Serializer.h.
References mData.
Referenced by ripple::SHAMap::addKnownNode(), ripple::SHAMap::addRootNode(), ripple::TransactionMaster::fetch(), ripple::SHAMap::flushDirty(), and ripple::Ledger::saveValidatedLedger().
     {
         return mData;
     }
bool ripple::Serializer::operator!= (Blob const & v) inline
Definition at line 211 of file Serializer.h.
References mData.
     {
         return v != mData;
     }
bool ripple::Serializer::operator!= (const Serializer & v) inline
Definition at line 219 of file Serializer.h.
References mData.
     {
         return v.mData != mData;
     }
bool ripple::Serializer::operator== (Blob const & v) inline
Definition at line 207 of file Serializer.h.
References mData.
     {
         return v == mData;
     }
bool ripple::Serializer::operator== (const Serializer & v) inline
Definition at line 215 of file Serializer.h.
References mData.
     {
         return v.mData == mData;
     }
Blob const& ripple::Serializer::peekData () const inline
Definition at line 125 of file Serializer.h.
References mData.
Referenced by ripple::Ledger::addTransaction(), ripple::RPCHandler::doLedgerEntry(), ripple::RPCHandler::doLedgerHeader(), ripple::FeaturesImpl::doVoting(), ripple::FeeVoteImpl::doVoting(), ripple::ValidationsImp::doWrite(), ripple::SHAMap::getFetchPack(), ripple::SerializedTransaction::getJson(), ripple::SerializedTransaction::getMetaSQL(), ripple::SHAMap::getNodeFat(), ripple::SHAMap::getPath(), ripple::SerializedValidation::getSigned(), ripple::SerializedTransaction::getSQL(), ripple::ConsensusTransSetSF::haveNode(), ripple::RadixMap::make_random_item(), ripple::SHAMapSync_test::makeRandomAS(), ripple::SHAMapItem::peekData(), ripple::Serializer_test::run(), and ripple::SHAMapTreeNode::SHAMapTreeNode().
     {
         return mData;
     }
int ripple::Serializer::removeLastByte ()
Definition at line 289 of file Serializer.cpp.
References mData, and size().
Referenced by ripple::SHAMapTreeNode::SHAMapTreeNode().
 {
     int size = mData.size () - 1;
     if (size < 0)
     {
         assert (false);
         return -1;
     }
     int ret = mData[size];
     mData.resize (size);
     return ret;
 }
void ripple::Serializer::reserve (size_t n) inline
Definition at line 194 of file Serializer.h.
References mData.
     {
         mData.reserve (n);
     }
void ripple::Serializer::resize (size_t n) inline
Definition at line 198 of file Serializer.h.
References mData.
Referenced by ripple::NetworkOPsImp::getAccountTxs(), ripple::NetworkOPsImp::getTxsAccount(), and ripple::Transaction::transactionFromSQL().
     {
         mData.resize (n);
     }
void ripple::Serializer::secureErase () inline
Definition at line 161 of file Serializer.h.
References erase(), and mData.
Referenced by ripple::CKey::GenerateRootDeterministicKey(), ripple::makeHash(), and ripple::CKey::PassPhraseToKey().
     {
         memset (& (mData.front ()), 0, mData.size ());
         erase ();
     }
Blob ::size_type ripple::Serializer::size () const inline
Definition at line 190 of file Serializer.h.
References mData.
Referenced by addVL(), addZeros(), ripple::SerializerIterator::getBytesLeft(), getSHA512Half(), getString(), and removeLastByte().
     {
         return mData.size ();
     }
void ripple::Serializer::TestSerializer () static
Definition at line 576 of file Serializer.cpp.
 {
     Serializer s (64);
 }
Member Data Documentation
Blob ripple::Serializer::mData protected
Definition at line 35 of file Serializer.h.
Referenced by add128(), add16(), add160(), add256(), add32(), add64(), add8(), addFieldID(), addRaw(), addVL(), begin(), capacity(), chop(), end(), erase(), get128(), get16(), get160(), get256(), get32(), get64(), get8(), getCapacity(), getData(), getDataLength(), getDataPtr(), getHex(), getLength(), getPrefixHash(), getRaw(), getRIPEMD160(), getSHA256(), getSHA512Half(), modData(), operator!=(), operator==(), peekData(), removeLastByte(), reserve(), resize(), secureErase(), Serializer(), and size().
The documentation for this class was generated from the following files:
rippled/src/ripple_data/protocol/Serializer.h
rippled/src/ripple_data/protocol/Serializer.cpp