rippled: ripple::AccountSetTransactor Class Reference
ripple::AccountSetTransactor Class Reference
#include <AccountSetTransactor.h>
Public Member Functions
AccountSetTransactor (SerializedTransaction const &txn, TransactionEngineParams params, TransactionEngine *engine)
TER doApply () override
Public Member Functions inherited from ripple::Transactor
TER apply ()
Additional Inherited Members
Static Public Member Functions inherited from ripple::Transactor
static std::unique_ptr
< Transactor > makeTransactor (SerializedTransaction const &txn, TransactionEngineParams params, TransactionEngine *engine)
Protected Member Functions inherited from ripple::Transactor
virtual TER preCheck ()
virtual TER checkSeq ()
virtual TER payFee ()
void calculateFee ()
virtual std::uint64_t calculateBaseFee ()
virtual TER checkSig ()
Transactor (const SerializedTransaction &txn, TransactionEngineParams params, TransactionEngine *engine, beast::Journal journal=beast::Journal())
virtual bool mustHaveValidAccount ()
Protected Attributes inherited from ripple::Transactor
SerializedTransaction const & mTxn
TransactionEngine * mEngine
TransactionEngineParams mParams
uint160 mTxnAccountID
STAmount mFeeDue
STAmount mPriorBalance
STAmount mSourceBalance
SLE::pointer mTxnAccount
bool mHasAuthKey
bool mSigMaster
RippleAddress mSigningPubKey
beast::Journal m_journal
Detailed Description
Definition at line 34 of file AccountSetTransactor.h.
Constructor & Destructor Documentation
ripple::AccountSetTransactor::AccountSetTransactor (SerializedTransaction const & txn, TransactionEngineParams params, TransactionEngine * engine) inline
Definition at line 38 of file AccountSetTransactor.h.
         : Transactor (
             txn,
             params,
             engine,
             LogPartition::getJournal <AccountSetTransactorLog> ())
     {
     }
Member Function Documentation
TER ripple::AccountSetTransactor::doApply () override virtual
Implements ripple::Transactor.
Definition at line 22 of file AccountSetTransactor.cpp.
References ripple::asfAccountTxnID, ripple::asfDisableMaster, ripple::asfDisallowXRP, ripple::asfRequireAuth, ripple::asfRequireDest, beast::Journal::debug, ripple::LedgerEntrySet::dirIsEmpty(), ripple::DOMAIN_BYTES_MAX, ripple::STObject::getFieldH128(), ripple::STObject::getFieldH256(), ripple::STObject::getFieldU32(), ripple::STObject::getFieldVL(), ripple::STObject::getFlags(), ripple::Ledger::getOwnerDirIndex(), ripple::is_bit_set(), ripple::STObject::isFieldPresent(), ripple::lsfDisableMaster, ripple::lsfDisallowXRP, ripple::lsfRequireAuth, ripple::lsfRequireDestTag, ripple::Transactor::m_journal, ripple::Transactor::mEngine, ripple::Transactor::mParams, ripple::Transactor::mTxn, ripple::Transactor::mTxnAccount, ripple::Transactor::mTxnAccountID, ripple::PUBLIC_BYTES_MAX, QUALITY_ONE, ripple::TxFlag::requireDestTag, ripple::tapRETRY, ripple::tecNO_REGULAR_KEY, ripple::tecOWNERS, ripple::telBAD_DOMAIN, ripple::telBAD_PUBLIC_KEY, ripple::temBAD_TRANSFER_RATE, ripple::temINVALID_FLAG, ripple::terOWNERS, ripple::tesSUCCESS, ripple::tfAccountSetMask, ripple::tfAllowXRP, ripple::tfDisallowXRP, ripple::tfOptionalAuth, ripple::tfOptionalDestTag, ripple::tfRequireAuth, beast::Journal::trace, and ripple::TransactionEngine::view().
 {
     std::uint32_t const uTxFlags = mTxn.getFlags ();
     std::uint32_t const uFlagsIn = mTxnAccount->getFieldU32 (sfFlags);
     std::uint32_t uFlagsOut = uFlagsIn;
     std::uint32_t const uSetFlag = mTxn.getFieldU32 (sfSetFlag);
     std::uint32_t const uClearFlag  = mTxn.getFieldU32 (sfClearFlag);
     // legacy AccountSet flags
     bool bSetRequireDest   = (uTxFlags & TxFlag::requireDestTag) || (uSetFlag == asfRequireDest);
     bool bClearRequireDest = (uTxFlags & tfOptionalDestTag) || (uClearFlag == asfRequireDest);
     bool bSetRequireAuth   = (uTxFlags & tfRequireAuth) || (uSetFlag == asfRequireAuth);
     bool bClearRequireAuth = (uTxFlags & tfOptionalAuth) || (uClearFlag == asfRequireAuth);
     bool bSetDisallowXRP   = (uTxFlags & tfDisallowXRP) || (uSetFlag == asfDisallowXRP);
     bool bClearDisallowXRP = (uTxFlags & tfAllowXRP) || (uClearFlag == asfDisallowXRP);
     if (uTxFlags & tfAccountSetMask)
     {
         m_journal.trace << "Malformed transaction: Invalid flags set.";
         return temINVALID_FLAG;
     }
     //
     // RequireAuth
     //
     if (bSetRequireAuth && bClearRequireAuth)
     {
         m_journal.trace << "Malformed transaction: Contradictory flags set.";
         return temINVALID_FLAG;
     }
     if (bSetRequireAuth && !is_bit_set (uFlagsIn, lsfRequireAuth))
     {
         if (!mEngine->view().dirIsEmpty (Ledger::getOwnerDirIndex (mTxnAccountID)))
         {
             m_journal.trace << "Retry: Owner directory not empty.";
             return is_bit_set(mParams, tapRETRY) ? terOWNERS : tecOWNERS;
         }
         m_journal.trace << "Set RequireAuth.";
         uFlagsOut   |= lsfRequireAuth;
     }
     if (bClearRequireAuth && is_bit_set (uFlagsIn, lsfRequireAuth))
     {
         m_journal.trace << "Clear RequireAuth.";
         uFlagsOut   &= ~lsfRequireAuth;
     }
     //
     // RequireDestTag
     //
     if (bSetRequireDest && bClearRequireDest)
     {
         m_journal.trace << "Malformed transaction: Contradictory flags set.";
         return temINVALID_FLAG;
     }
     if (bSetRequireDest && !is_bit_set (uFlagsIn, lsfRequireDestTag))
     {
         m_journal.trace << "Set lsfRequireDestTag.";
         uFlagsOut   |= lsfRequireDestTag;
     }
     if (bClearRequireDest && is_bit_set (uFlagsIn, lsfRequireDestTag))
     {
         m_journal.trace << "Clear lsfRequireDestTag.";
         uFlagsOut   &= ~lsfRequireDestTag;
     }
     //
     // DisallowXRP
     //
     if (bSetDisallowXRP && bClearDisallowXRP)
     {
         m_journal.trace << "Malformed transaction: Contradictory flags set.";
         return temINVALID_FLAG;
     }
     if (bSetDisallowXRP && !is_bit_set (uFlagsIn, lsfDisallowXRP))
     {
         m_journal.trace << "Set lsfDisallowXRP.";
         uFlagsOut   |= lsfDisallowXRP;
     }
     if (bClearDisallowXRP && is_bit_set (uFlagsIn, lsfDisallowXRP))
     {
         m_journal.trace << "Clear lsfDisallowXRP.";
         uFlagsOut   &= ~lsfDisallowXRP;
     }
     //
     // DisableMaster
     //
     if ((uSetFlag == asfDisableMaster) && (uClearFlag == asfDisableMaster))
     {
         m_journal.trace << "Malformed transaction: Contradictory flags set.";
         return temINVALID_FLAG;
     }
     if ((uSetFlag == asfDisableMaster) && !is_bit_set (uFlagsIn, lsfDisableMaster))
     {
         if (!mTxnAccount->isFieldPresent (sfRegularKey))
             return tecNO_REGULAR_KEY;
         m_journal.trace << "Set lsfDisableMaster.";
         uFlagsOut   |= lsfDisableMaster;
     }
     if ((uClearFlag == asfDisableMaster) && is_bit_set (uFlagsIn, lsfDisableMaster))
     {
         m_journal.trace << "Clear lsfDisableMaster.";
         uFlagsOut   &= ~lsfDisableMaster;
     }
     //
     // Track transaction IDs signed by this account in its root
     //
     if ((uSetFlag == asfAccountTxnID) && (uClearFlag != asfAccountTxnID) && !mTxnAccount->isFieldPresent (sfAccountTxnID))
     {
         m_journal.trace << "Set AccountTxnID";
         mTxnAccount->makeFieldPresent (sfAccountTxnID);
      }
     if ((uClearFlag == asfAccountTxnID) && (uSetFlag != asfAccountTxnID) && mTxnAccount->isFieldPresent (sfAccountTxnID))
     {
         m_journal.trace << "Clear AccountTxnID";
         mTxnAccount->makeFieldAbsent (sfAccountTxnID);
     }
     //
     // EmailHash
     //
     if (mTxn.isFieldPresent (sfEmailHash))
     {
         uint128     uHash   = mTxn.getFieldH128 (sfEmailHash);
         if (!uHash)
         {
             m_journal.trace << "unset email hash";
             mTxnAccount->makeFieldAbsent (sfEmailHash);
         }
         else
         {
             m_journal.trace << "set email hash";
             mTxnAccount->setFieldH128 (sfEmailHash, uHash);
         }
     }
     //
     // WalletLocator
     //
     if (mTxn.isFieldPresent (sfWalletLocator))
     {
         uint256     uHash   = mTxn.getFieldH256 (sfWalletLocator);
         if (!uHash)
         {
             m_journal.trace << "unset wallet locator";
             mTxnAccount->makeFieldAbsent (sfEmailHash);
         }
         else
         {
             m_journal.trace << "set wallet locator";
             mTxnAccount->setFieldH256 (sfWalletLocator, uHash);
         }
     }
     //
     // MessageKey
     //
     if (mTxn.isFieldPresent (sfMessageKey))
     {
         Blob    vucPublic   = mTxn.getFieldVL (sfMessageKey);
         if (vucPublic.empty ())
         {
             m_journal.debug << "set message key";
             mTxnAccount->makeFieldAbsent (sfMessageKey);
         }
         if (vucPublic.size () > PUBLIC_BYTES_MAX)
         {
             m_journal.trace << "message key too long";
             return telBAD_PUBLIC_KEY;
         }
         else
         {
             m_journal.debug << "set message key";
             mTxnAccount->setFieldVL (sfMessageKey, vucPublic);
         }
     }
     //
     // Domain
     //
     if (mTxn.isFieldPresent (sfDomain))
     {
         Blob    vucDomain   = mTxn.getFieldVL (sfDomain);
         if (vucDomain.empty ())
         {
             m_journal.trace << "unset domain";
             mTxnAccount->makeFieldAbsent (sfDomain);
         }
         else if (vucDomain.size () > DOMAIN_BYTES_MAX)
         {
             m_journal.trace << "domain too long";
             return telBAD_DOMAIN;
         }
         else
         {
             m_journal.trace << "set domain";
             mTxnAccount->setFieldVL (sfDomain, vucDomain);
         }
     }
     //
     // TransferRate
     //
     if (mTxn.isFieldPresent (sfTransferRate))
     {
         std::uint32_t      uRate   = mTxn.getFieldU32 (sfTransferRate);
         if (!uRate || uRate == QUALITY_ONE)
         {
             m_journal.trace << "unset transfer rate";
             mTxnAccount->makeFieldAbsent (sfTransferRate);
         }
         else if (uRate > QUALITY_ONE)
         {
             m_journal.trace << "set transfer rate";
             mTxnAccount->setFieldU32 (sfTransferRate, uRate);
         }
         else
         {
             m_journal.trace << "bad transfer rate";
             return temBAD_TRANSFER_RATE;
         }
     }
     if (uFlagsIn != uFlagsOut)
         mTxnAccount->setFieldU32 (sfFlags, uFlagsOut);
     return tesSUCCESS;
 }
The documentation for this class was generated from the following files:
rippled/src/ripple_app/transactors/AccountSetTransactor.h
rippled/src/ripple_app/transactors/AccountSetTransactor.cpp