rippled: beast::FileInputStream Class Reference
beast::FileInputStream Class Reference
#include <FileInputStream.h>
Public Member Functions
FileInputStream (const File &fileToRead)
~FileInputStream ()
const File & getFile () const noexcept
const Result & getStatus () const noexcept
bool failedToOpen () const noexcept
bool openedOk () const noexcept
std::int64_t getTotalLength ()
int read (void *destBuffer, int maxBytesToRead)
bool isExhausted ()
std::int64_t getPosition ()
bool setPosition (std::int64_t pos)
Public Member Functions inherited from beast::InputStream
virtual ~InputStream ()
std::int64_t getNumBytesRemaining ()
virtual char readByte ()
virtual bool readBool ()
virtual short readShort ()
virtual short readShortBigEndian ()
virtual std::int32_t readInt32 ()
virtual int readInt ()
virtual std::int32_t readInt32BigEndian ()
virtual int readIntBigEndian ()
virtual std::int64_t readInt64 ()
virtual std::int64_t readInt64BigEndian ()
virtual float readFloat ()
virtual float readFloatBigEndian ()
virtual double readDouble ()
virtual double readDoubleBigEndian ()
virtual int readCompressedInt ()
template<class T >
T readType ()
template<class T >
bool readTypeInto (T *p)
template<class T >
T readTypeBigEndian ()
template<class T >
bool readTypeBigEndianInto (T *p)
virtual String readNextLine ()
virtual String readString ()
virtual String readEntireStreamAsString ()
virtual int readIntoMemoryBlock (MemoryBlock &destBlock, std::ptrdiff_t maxNumBytesToRead=-1)
virtual void skipNextBytes (std::int64_t numBytesToSkip)
template<>
char readType ()
template<>
short readType ()
template<>
unsigned char readType ()
template<>
unsigned short readType ()
template<>
float readType ()
template<>
double readType ()
template<>
char readTypeBigEndian ()
template<>
short readTypeBigEndian ()
template<>
unsigned char readTypeBigEndian ()
template<>
unsigned short readTypeBigEndian ()
template<>
float readTypeBigEndian ()
template<>
double readTypeBigEndian ()
Private Member Functions
void openHandle ()
void closeHandle ()
size_t readInternal (void *buffer, size_t numBytes)
Private Attributes
File file
void * fileHandle
std::int64_t currentPosition
Result status
bool needToSeek
Additional Inherited Members
Protected Member Functions inherited from beast::InputStream
InputStream () noexcept
Detailed Description
An input stream that reads from a local file.
See Also
InputStream, FileOutputStream, File::createInputStream
Definition at line 36 of file FileInputStream.h.
Constructor & Destructor Documentation
beast::FileInputStream::FileInputStream (const File & fileToRead) explicit
Creates a FileInputStream.
Parameters
fileToRead the file to read from - if the file can't be accessed for some reason, then the stream will just contain no data
Definition at line 30 of file FileInputStream.cpp.
References openHandle().
     : file (f),
       fileHandle (nullptr),
       currentPosition (0),
       status (Result::ok()),
       needToSeek (true)
 {
     openHandle();
 }
beast::FileInputStream::~FileInputStream ()
Destructor.
Definition at line 40 of file FileInputStream.cpp.
References closeHandle().
 {
     closeHandle();
 }
Member Function Documentation
void beast::FileInputStream::closeHandle () private
Definition at line 299 of file posix_SharedCode.h.
References fileHandle.
Referenced by ~FileInputStream().
 {
     if (fileHandle != 0)
     {
         close (getFD (fileHandle));
         fileHandle = 0;
     }
 }
bool beast::FileInputStream::failedToOpen () const inline noexcept
Returns true if the stream couldn't be opened for some reason.
See Also
getResult()
Definition at line 65 of file FileInputStream.h.
References beast::Result::failed(), and status.
 { return status.failed(); }
const File& beast::FileInputStream::getFile () const inline noexcept
Returns the file that this stream is reading from.
Definition at line 54 of file FileInputStream.h.
References file.
 { return file; }
std::int64_t beast::FileInputStream::getPosition () virtual
Returns the offset of the next byte that will be read from the stream.
See Also
setPosition
Implements beast::InputStream.
Definition at line 75 of file FileInputStream.cpp.
References currentPosition.
 {
     return currentPosition;
 }
const Result& beast::FileInputStream::getStatus () const inline noexcept
Returns the status of the file stream. The result will be ok if the file opened successfully. If an error occurs while opening or reading from the file, this will contain an error message.
Definition at line 60 of file FileInputStream.h.
References status.
 { return status; }
std::int64_t beast::FileInputStream::getTotalLength () virtual
Returns the total number of bytes available for reading in this stream.
Note that this is the number of bytes available from the start of the stream, not from the current position.
If the size of the stream isn't actually known, this will return -1.
See Also
getNumBytesRemaining
Implements beast::InputStream.
Definition at line 46 of file FileInputStream.cpp.
References file, and beast::File::getSize().
Referenced by isExhausted(), and setPosition().
 {
     return file.getSize();
 }
bool beast::FileInputStream::isExhausted () virtual
Returns true if the stream has no more data to read.
Implements beast::InputStream.
Definition at line 70 of file FileInputStream.cpp.
References currentPosition, and getTotalLength().
 {
     return currentPosition >= getTotalLength();
 }
bool beast::FileInputStream::openedOk () const inline noexcept
Returns true if the stream opened without problems.
See Also
getResult()
Definition at line 70 of file FileInputStream.h.
References status, and beast::Result::wasOk().
Referenced by beast::File::hasIdenticalContentTo(), beast::File::loadFileAsData(), beast::File::loadFileAsString(), beast::operator<<(), read(), and setPosition().
 { return status.wasOk(); }
void beast::FileInputStream::openHandle () private
Definition at line 289 of file posix_SharedCode.h.
References file, fileHandle, beast::File::getFullPathName(), O_RDONLY, status, and beast::String::toUTF8().
Referenced by FileInputStream().
 {
     const int f = open (file.getFullPathName().toUTF8(), O_RDONLY, 00644);
     if (f != -1)
         fileHandle = fdToVoidPointer (f);
     else
         status = getResultForErrno();
 }
int beast::FileInputStream::read (void * destBuffer, int maxBytesToRead) virtual
Reads some data from the stream into a memory buffer.
This is the only read method that subclasses actually need to implement, as the InputStream base class implements the other read methods in terms of this one (although it's often more efficient for subclasses to implement them directly).
Parameters
destBuffer the destination buffer for the data. This must not be null.
maxBytesToRead the maximum number of bytes to read - make sure the memory block passed in is big enough to contain this many bytes. This value must not be negative.
Returns
the actual number of bytes that were read, which may be less than maxBytesToRead if the stream is exhausted before it gets that far
Implements beast::InputStream.
Definition at line 51 of file FileInputStream.cpp.
References bassert, beast::beast_fileSetPosition(), currentPosition, fileHandle, needToSeek, openedOk(), and readInternal().
Referenced by beast::File::hasIdenticalContentTo(), and readInternal().
 {
     bassert (openedOk());
     bassert (buffer != nullptr && bytesToRead >= 0);
     if (needToSeek)
     {
         if (beast_fileSetPosition (fileHandle, currentPosition) < 0)
             return 0;
         needToSeek = false;
     }
     const size_t num = readInternal (buffer, (size_t) bytesToRead);
     currentPosition += num;
     return (int) num;
 }
size_t beast::FileInputStream::readInternal (void * buffer, size_t numBytes) private
Definition at line 308 of file posix_SharedCode.h.
References fileHandle, read(), and status.
Referenced by read().
 {
     std::ptrdiff_t result = 0;
     if (fileHandle != 0)
     {
         result = ::read (getFD (fileHandle), buffer, numBytes);
         if (result < 0)
         {
             status = getResultForErrno();
             result = 0;
         }
     }
     return (size_t) result;
 }
bool beast::FileInputStream::setPosition (std::int64_t newPosition) virtual
Tries to move the current read position of the stream.
The position is an absolute number of bytes from the stream's start.
Some streams might not be able to do this, in which case they should do nothing and return false. Others might be able to manage it by resetting themselves and skipping to the correct position, although this is obviously a bit slow.
Returns
true if the stream manages to reposition itself correctly
See Also
getPosition
Implements beast::InputStream.
Definition at line 80 of file FileInputStream.cpp.
References bassert, beast::blimit(), currentPosition, getTotalLength(), needToSeek, and openedOk().
 {
     bassert (openedOk());
     if (pos != currentPosition)
     {
         pos = blimit ((std::int64_t) 0, getTotalLength(), pos);
         needToSeek |= (currentPosition != pos);
         currentPosition = pos;
     }
     return true;
 }
Member Data Documentation
std::int64_t beast::FileInputStream::currentPosition private
Definition at line 84 of file FileInputStream.h.
Referenced by getPosition(), isExhausted(), read(), and setPosition().
File beast::FileInputStream::file private
Definition at line 82 of file FileInputStream.h.
Referenced by getFile(), getTotalLength(), and openHandle().
void* beast::FileInputStream::fileHandle private
Definition at line 83 of file FileInputStream.h.
Referenced by closeHandle(), openHandle(), read(), and readInternal().
bool beast::FileInputStream::needToSeek private
Definition at line 86 of file FileInputStream.h.
Referenced by read(), and setPosition().
Result beast::FileInputStream::status private
Definition at line 85 of file FileInputStream.h.
Referenced by failedToOpen(), getStatus(), openedOk(), openHandle(), and readInternal().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_core/files/FileInputStream.h
rippled/src/beast/modules/beast_core/files/FileInputStream.cpp
rippled/src/beast/modules/beast_core/native/posix_SharedCode.h
rippled/src/beast/modules/beast_core/native/win32_Files.cpp