rippled: ripple::CycledSet< Key, Hash, KeyEqual, Allocator > Class Template Reference
ripple::CycledSet< Key, Hash, KeyEqual, Allocator > Class Template Reference
#include <CycledSet.h>
Public Types
typedef ContainerType::key_type key_type
typedef ContainerType::value_type value_type
typedef ContainerType::size_type size_type
typedef
ContainerType::difference_type difference_type
typedef ContainerType::hasher hasher
typedef ContainerType::key_equal key_equal
typedef
ContainerType::allocator_type allocator_type
typedef ContainerType::reference reference
typedef
ContainerType::const_reference const_reference
typedef ContainerType::pointer pointer
typedef
ContainerType::const_pointer const_pointer
Public Member Functions
CycledSet (size_type item_max=0, Hash hash=Hash(), KeyEqual equal=KeyEqual(), Allocator alloc=Allocator())
bool full () const
bool insert (key_type const &key)
void cycle ()
Private Types
typedef boost::unordered_set
< Key, Hash, KeyEqual,
Allocator > ContainerType
typedef ContainerType::iterator iterator
Private Attributes
size_type m_max
hasher m_hash
key_equal m_equal
allocator_type m_alloc
ContainerType m_front
ContainerType m_back
Detailed Description
template<class Key, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator <Key>>
class ripple::CycledSet< Key, Hash, KeyEqual, Allocator >
Cycled set of unique keys. This provides a system of remembering a set of keys, with aging. Two containers are kept. When one container fills, the other is cleared and a swap is performed. A key is considered present if it is in either container.
Definition at line 37 of file CycledSet.h.
Member Typedef Documentation
template<class Key, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator <Key>> typedef ContainerType::allocator_type ripple::CycledSet< Key, Hash, KeyEqual, Allocator >::allocator_type
Definition at line 51 of file CycledSet.h.
template<class Key, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator <Key>> typedef ContainerType::const_pointer ripple::CycledSet< Key, Hash, KeyEqual, Allocator >::const_pointer
Definition at line 55 of file CycledSet.h.
template<class Key, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator <Key>> typedef ContainerType::const_reference ripple::CycledSet< Key, Hash, KeyEqual, Allocator >::const_reference
Definition at line 53 of file CycledSet.h.
template<class Key, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator <Key>> typedef boost::unordered_set< Key, Hash, KeyEqual, Allocator> ripple::CycledSet< Key, Hash, KeyEqual, Allocator >::ContainerType private
Definition at line 41 of file CycledSet.h.
template<class Key, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator <Key>> typedef ContainerType::difference_type ripple::CycledSet< Key, Hash, KeyEqual, Allocator >::difference_type
Definition at line 48 of file CycledSet.h.
template<class Key, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator <Key>> typedef ContainerType::hasher ripple::CycledSet< Key, Hash, KeyEqual, Allocator >::hasher
Definition at line 49 of file CycledSet.h.
template<class Key, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator <Key>> typedef ContainerType::iterator ripple::CycledSet< Key, Hash, KeyEqual, Allocator >::iterator private
Definition at line 42 of file CycledSet.h.
template<class Key, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator <Key>> typedef ContainerType::key_equal ripple::CycledSet< Key, Hash, KeyEqual, Allocator >::key_equal
Definition at line 50 of file CycledSet.h.
template<class Key, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator <Key>> typedef ContainerType::key_type ripple::CycledSet< Key, Hash, KeyEqual, Allocator >::key_type
Definition at line 45 of file CycledSet.h.
template<class Key, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator <Key>> typedef ContainerType::pointer ripple::CycledSet< Key, Hash, KeyEqual, Allocator >::pointer
Definition at line 54 of file CycledSet.h.
template<class Key, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator <Key>> typedef ContainerType::reference ripple::CycledSet< Key, Hash, KeyEqual, Allocator >::reference
Definition at line 52 of file CycledSet.h.
template<class Key, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator <Key>> typedef ContainerType::size_type ripple::CycledSet< Key, Hash, KeyEqual, Allocator >::size_type
Definition at line 47 of file CycledSet.h.
template<class Key, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator <Key>> typedef ContainerType::value_type ripple::CycledSet< Key, Hash, KeyEqual, Allocator >::value_type
Definition at line 46 of file CycledSet.h.
Constructor & Destructor Documentation
template<class Key, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator <Key>> ripple::CycledSet< Key, Hash, KeyEqual, Allocator >::CycledSet (size_type item_max = 0, Hash hash = Hash(), KeyEqual equal = KeyEqual(), Allocator alloc = Allocator()) inline explicit
Definition at line 57 of file CycledSet.h.
         : m_max (item_max)
         , m_hash (hash)
         , m_equal (equal)
         , m_alloc (alloc)
         , m_front (m_max, hash, equal, alloc)
         , m_back (m_max, hash, equal, alloc)
     {
     }
Member Function Documentation
template<class Key, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator <Key>> void ripple::CycledSet< Key, Hash, KeyEqual, Allocator >::cycle () inline
Definition at line 91 of file CycledSet.h.
Referenced by ripple::CycledSet< ReceivedValidation, ReceivedValidationHash, ReceivedValidationKeyEqual >::insert().
     {
         std::swap (m_front, m_back);
         m_front.clear ();
 #if BOOST_VERSION > 105400
         m_front.reserve (m_max);
 #endif
     }
template<class Key, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator <Key>> bool ripple::CycledSet< Key, Hash, KeyEqual, Allocator >::full () const inline
Definition at line 72 of file CycledSet.h.
Referenced by ripple::CycledSet< ReceivedValidation, ReceivedValidationHash, ReceivedValidationKeyEqual >::insert().
     {
         return (m_max != 0) && m_front.size() >= m_max;
     }
template<class Key, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator <Key>> bool ripple::CycledSet< Key, Hash, KeyEqual, Allocator >::insert (key_type const & key) inline
Definition at line 78 of file CycledSet.h.
Referenced by ripple::Validators::Logic::ledgerClosed(), and ripple::Validators::Logic::receiveValidation().
     {
         if (full())
             cycle ();
         if (m_back.find (key) != m_back.end())
             return false;
         std::pair <iterator, bool> result (
             m_front.insert (key));
         if (result.second)
             return true;
         return false;
     }
Member Data Documentation
template<class Key, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator <Key>> allocator_type ripple::CycledSet< Key, Hash, KeyEqual, Allocator >::m_alloc private
Definition at line 105 of file CycledSet.h.
template<class Key, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator <Key>> ContainerType ripple::CycledSet< Key, Hash, KeyEqual, Allocator >::m_back private
Definition at line 107 of file CycledSet.h.
Referenced by ripple::CycledSet< ReceivedValidation, ReceivedValidationHash, ReceivedValidationKeyEqual >::cycle(), and ripple::CycledSet< ReceivedValidation, ReceivedValidationHash, ReceivedValidationKeyEqual >::insert().
template<class Key, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator <Key>> key_equal ripple::CycledSet< Key, Hash, KeyEqual, Allocator >::m_equal private
Definition at line 104 of file CycledSet.h.
template<class Key, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator <Key>> ContainerType ripple::CycledSet< Key, Hash, KeyEqual, Allocator >::m_front private
Definition at line 106 of file CycledSet.h.
Referenced by ripple::CycledSet< ReceivedValidation, ReceivedValidationHash, ReceivedValidationKeyEqual >::cycle(), ripple::CycledSet< ReceivedValidation, ReceivedValidationHash, ReceivedValidationKeyEqual >::full(), and ripple::CycledSet< ReceivedValidation, ReceivedValidationHash, ReceivedValidationKeyEqual >::insert().
template<class Key, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator <Key>> hasher ripple::CycledSet< Key, Hash, KeyEqual, Allocator >::m_hash private
Definition at line 103 of file CycledSet.h.
template<class Key, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator <Key>> size_type ripple::CycledSet< Key, Hash, KeyEqual, Allocator >::m_max private
Definition at line 102 of file CycledSet.h.
Referenced by ripple::CycledSet< ReceivedValidation, ReceivedValidationHash, ReceivedValidationKeyEqual >::cycle(), and ripple::CycledSet< ReceivedValidation, ReceivedValidationHash, ReceivedValidationKeyEqual >::full().
The documentation for this class was generated from the following file:
rippled/src/ripple/algorithm/api/CycledSet.h