rippled: beast::empty_base_optimization_test Class Reference
beast::empty_base_optimization_test Class Reference
Classes
struct Empty
class test1
class test2
Public Member Functions
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Static Public Member Functions
static bool test_one ()
static bool test_two ()
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 30 of file empty_base_optimization.test.cpp.
Member Function Documentation
void beast::empty_base_optimization_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 97 of file empty_base_optimization.test.cpp.
References beast::unit_test::suite::expect(), beast::unit_test::suite::pass(), test_one(), and test_two().
     {
         expect (test_one());
         expect (test_two());
         pass ();
     }
static bool beast::empty_base_optimization_test::test_one () inline static
Definition at line 70 of file empty_base_optimization.test.cpp.
References beast::empty_base_optimization_test::test1< T >::member(), and beast::empty_base_optimization_test::test2< T >::member().
Referenced by run().
     {
         test1<int> t1(1);
         test2<int> t2(2);
         static_assert(sizeof(t1) == sizeof(t2), "don't optimize for int");
         if (t1.member() != 1)
             return false;
         if (t2.member() != 2)
             return false;
         return true;
     }
static bool beast::empty_base_optimization_test::test_two () inline static
Definition at line 84 of file empty_base_optimization.test.cpp.
References beast::empty_base_optimization_test::test1< T >::member(), and beast::empty_base_optimization_test::test2< T >::member().
Referenced by run().
     {
         test1<Empty> t1((Empty()));
         test2<Empty> t2((Empty()));
         static_assert(sizeof(t1) < sizeof(t2), "do optimize for Empty");
         if (t1.member() != true)
             return false;
         if (t2.member() != true)
             return false;
         return true;
     }
The documentation for this class was generated from the following file:
rippled/src/beast/beast/utility/tests/empty_base_optimization.test.cpp