rippled: beast::asio::HandshakeDetectLogicPROXY Class Reference
beast::asio::HandshakeDetectLogicPROXY Class Reference
#include <HandshakeDetectLogicPROXY.h>
Classes
struct ProxyInfo
Public Types
enum { maxBytesNeeded = 107 }
typedef int arg_type
Public Member Functions
HandshakeDetectLogicPROXY (arg_type const &)
ProxyInfo const & getInfo () const noexcept
std::size_t max_needed ()
std::size_t bytes_consumed ()
template<typename ConstBufferSequence >
void analyze (ConstBufferSequence const &buffer)
void analyze_input (FixedInputBuffer &in, InputParser::State &state)
Public Member Functions inherited from beast::asio::HandshakeDetectLogic
HandshakeDetectLogic ()
bool finished () const noexcept
bool success () const noexcept
Private Attributes
std::size_t m_consumed
ProxyInfo m_info
Additional Inherited Members
Protected Member Functions inherited from beast::asio::HandshakeDetectLogic
void conclude (bool success=true)
void fail ()
Detailed Description
Handshake detector for the PROXY protcol
http://haproxy.1wt.eu/download/1.5/doc/proxy-protocol.txt
Definition at line 30 of file HandshakeDetectLogicPROXY.h.
Member Typedef Documentation
typedef int beast::asio::HandshakeDetectLogicPROXY::arg_type
Definition at line 33 of file HandshakeDetectLogicPROXY.h.
Member Enumeration Documentation
anonymous enum
Enumerator
maxBytesNeeded
Definition at line 35 of file HandshakeDetectLogicPROXY.h.
     {
         // This is for version 1. The largest number of bytes
         // that we could possibly need to parse a valid handshake.
         // We will reject it much sooner if there's an illegal value.
         //
         maxBytesNeeded = 107 // including CRLF, no null term
     };
Constructor & Destructor Documentation
beast::asio::HandshakeDetectLogicPROXY::HandshakeDetectLogicPROXY (arg_type const &) inline explicit
Definition at line 57 of file HandshakeDetectLogicPROXY.h.
         : m_consumed (0)
     {
     }
Member Function Documentation
template<typename ConstBufferSequence > void beast::asio::HandshakeDetectLogicPROXY::analyze (ConstBufferSequence const & buffer) inline
Definition at line 78 of file HandshakeDetectLogicPROXY.h.
References analyze_input(), beast::asio::HandshakeDetectLogic::conclude(), beast::asio::InputParser::State::failed(), Json::in(), m_consumed, beast::asio::InputParser::State::passed(), and beast::asio::FixedInputBuffer::used().
     {
         FixedInputBufferSize <maxBytesNeeded> in (buffer);
         InputParser::State state;
         analyze_input (in, state);
         if (state.passed ())
         {
             m_consumed = in.used ();
             conclude (true);
         }
         else if (state.failed ())
         {
             conclude (false);
         }
     }
void beast::asio::HandshakeDetectLogicPROXY::analyze_input (FixedInputBuffer & in, InputParser::State & state) inline
Definition at line 97 of file HandshakeDetectLogicPROXY.h.
References beast::asio::HandshakeDetectLogicPROXY::ProxyInfo::destAddress, beast::asio::HandshakeDetectLogicPROXY::ProxyInfo::destPort, m_info, beast::asio::InputParser::match(), beast::asio::HandshakeDetectLogicPROXY::ProxyInfo::protocol, beast::asio::InputParser::read(), beast::asio::HandshakeDetectLogicPROXY::ProxyInfo::sourceAddress, and beast::asio::HandshakeDetectLogicPROXY::ProxyInfo::sourcePort.
Referenced by analyze().
     {
         using namespace InputParser;
         if (! match (in, "PROXY ", state))
             return;
         if (match (in, "TCP4 "))
         {
             m_info.protocol = "TCP4";
             if (! read (in, m_info.sourceAddress, state))
                 return;
             if (! match (in, " ", state))
                 return;
             if (! read (in, m_info.destAddress, state))
                 return;
             if (! match (in, " ", state))
                 return;
             UInt16Str sourcePort;
             if (! read (in, sourcePort, state))
                 return;
             m_info.sourcePort = sourcePort.value;
             if (! match (in, " ", state))
                 return;
             UInt16Str destPort;
             if (! read (in, destPort, state))
                 return;
             m_info.destPort = destPort.value;
             if (! match (in, "\r\n", state))
                 return;
             state = State::pass;
             return;
         }
         else if (match (in, "TCP6 "))
         {
             m_info.protocol = "TCP6";
             state = State::fail;
             return;
         }
         else if (match (in, "UNKNOWN "))
         {
             m_info.protocol = "UNKNOWN";
             state = State::fail;
             return;
         }
         state = State::fail;
     }
std::size_t beast::asio::HandshakeDetectLogicPROXY::bytes_consumed () inline virtual
How many bytes the handshake consumes. If the detector processes the entire handshake this will be non zero. The SSL detector would return 0, since we want all the existing bytes to be passed on.
Implements beast::asio::HandshakeDetectLogic.
Definition at line 72 of file HandshakeDetectLogicPROXY.h.
References m_consumed.
     {
         return m_consumed;
     }
ProxyInfo const& beast::asio::HandshakeDetectLogicPROXY::getInfo () const inline noexcept
Definition at line 62 of file HandshakeDetectLogicPROXY.h.
References m_info.
Referenced by ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::async_handshake().
     {
         return m_info;
     }
std::size_t beast::asio::HandshakeDetectLogicPROXY::max_needed () inline virtual
How many bytes maximum we might need.
This is the largest number of bytes that the detector might need in order to come to a conclusion about whether or not the handshake is a match. Depending on the data, it could come to that conclusion sooner though.
Use read_some instead of read so that the detect logic can reject the handshake sooner if possible.
Implements beast::asio::HandshakeDetectLogic.
Definition at line 67 of file HandshakeDetectLogicPROXY.h.
References maxBytesNeeded.
     {
         return maxBytesNeeded;
     }
Member Data Documentation
std::size_t beast::asio::HandshakeDetectLogicPROXY::m_consumed private
Definition at line 158 of file HandshakeDetectLogicPROXY.h.
Referenced by analyze(), and bytes_consumed().
ProxyInfo beast::asio::HandshakeDetectLogicPROXY::m_info private
Definition at line 159 of file HandshakeDetectLogicPROXY.h.
Referenced by analyze_input(), and getInfo().
The documentation for this class was generated from the following file:
rippled/src/beast/modules/beast_asio/protocol/HandshakeDetectLogicPROXY.h