rippled: beast::HTTPRequest Class Reference
beast::HTTPRequest Class Reference
#include <HTTPRequest.h>
Public Member Functions
HTTPRequest (HTTPVersion const &version_, StringPairArray &fields, DynamicBuffer &body, unsigned short method_)
unsigned short method () const
String toString () const
Public Member Functions inherited from beast::HTTPMessage
HTTPMessage (HTTPVersion const &version_, StringPairArray &fields, DynamicBuffer &body)
HTTPVersion const & version () const
HTTPHeaders const & headers () const
DynamicBuffer const & body () const
String toString () const
Public Member Functions inherited from beast::SharedObject
void incReferenceCount () const noexcept
void decReferenceCount () const
int getReferenceCount () const noexcept
Private Attributes
unsigned short m_method
Additional Inherited Members
Protected Member Functions inherited from beast::SharedObject
SharedObject ()
virtual ~SharedObject ()
virtual void destroy () const
void resetReferenceCount () noexcept
Detailed Description
Definition at line 25 of file HTTPRequest.h.
Constructor & Destructor Documentation
beast::HTTPRequest::HTTPRequest (HTTPVersion const & version_, StringPairArray & fields, DynamicBuffer & body, unsigned short method_)
Construct a complete response from values. Ownership of the fields and body parameters are transferred from the caller.
Definition at line 22 of file HTTPRequest.cpp.
     : HTTPMessage (version_, fields, body)
     , m_method (method_)
 {
 }
Member Function Documentation
unsigned short beast::HTTPRequest::method () const
Definition at line 32 of file HTTPRequest.cpp.
References m_method.
Referenced by toString().
 {
     return m_method;
 }
String beast::HTTPRequest::toString () const
Convert the request into a string, excluding the body.
Definition at line 37 of file HTTPRequest.cpp.
References beast::String::fromNumber(), method(), beast::newLine, and beast::HTTPMessage::toString().
 {
     String s;
     s << "Method: " << String::fromNumber (method ()) << newLine;
     s << this->HTTPMessage::toString ();
     return s;
 }
Member Data Documentation
unsigned short beast::HTTPRequest::m_method private
Definition at line 44 of file HTTPRequest.h.
Referenced by method().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_asio/http/HTTPRequest.h
rippled/src/beast/modules/beast_asio/http/HTTPRequest.cpp