rippled: beast::CharPointer_ASCII Class Reference
beast::CharPointer_ASCII Class Reference
#include <CharPointer_ASCII.h>
Public Types
typedef char CharType
Public Member Functions
CharPointer_ASCII (const CharType *const rawPointer) noexcept
CharPointer_ASCII (const CharPointer_ASCII &other) noexcept
CharPointer_ASCII operator= (const CharPointer_ASCII other) noexcept
CharPointer_ASCII operator= (const CharType *text) noexcept
bool operator== (CharPointer_ASCII other) const noexcept
bool operator!= (CharPointer_ASCII other) const noexcept
bool operator<= (CharPointer_ASCII other) const noexcept
bool operator< (CharPointer_ASCII other) const noexcept
bool operator>= (CharPointer_ASCII other) const noexcept
bool operator> (CharPointer_ASCII other) const noexcept
CharType * getAddress () const noexcept
operator const CharType * () const noexcept
bool isEmpty () const noexcept
beast_wchar operator* () const noexcept
CharPointer_ASCII operator++ () noexcept
CharPointer_ASCII operator-- () noexcept
beast_wchar getAndAdvance () noexcept
CharPointer_ASCII operator++ (int) noexcept
void operator+= (const int numToSkip) noexcept
void operator-= (const int numToSkip) noexcept
beast_wchar operator[] (const int characterIndex) const noexcept
CharPointer_ASCII operator+ (const int numToSkip) const noexcept
CharPointer_ASCII operator- (const int numToSkip) const noexcept
void write (const beast_wchar charToWrite) noexcept
void replaceChar (const beast_wchar newChar) noexcept
void writeNull () const noexcept
size_t length () const noexcept
size_t lengthUpTo (const size_t maxCharsToCount) const noexcept
size_t lengthUpTo (const CharPointer_ASCII end) const noexcept
size_t sizeInBytes () const noexcept
CharPointer_ASCII findTerminatingNull () const noexcept
template<typename CharPointer >
void writeAll (const CharPointer src) noexcept
void writeAll (const CharPointer_ASCII src) noexcept
template<typename CharPointer >
size_t writeWithDestByteLimit (const CharPointer src, const size_t maxDestBytes) noexcept
template<typename CharPointer >
void writeWithCharLimit (const CharPointer src, const int maxChars) noexcept
template<typename CharPointer >
int compare (const CharPointer other) const noexcept
int compare (const CharPointer_ASCII other) const noexcept
template<typename CharPointer >
int compareUpTo (const CharPointer other, const int maxChars) const noexcept
int compareUpTo (const CharPointer_ASCII other, const int maxChars) const noexcept
template<typename CharPointer >
int compareIgnoreCase (const CharPointer other) const
int compareIgnoreCase (const CharPointer_ASCII other) const
template<typename CharPointer >
int compareIgnoreCaseUpTo (const CharPointer other, const int maxChars) const noexcept
template<typename CharPointer >
int indexOf (const CharPointer stringToFind) const noexcept
int indexOf (const beast_wchar charToFind) const noexcept
int indexOf (const beast_wchar charToFind, const bool ignoreCase) const noexcept
bool isWhitespace () const
bool isDigit () const
bool isLetter () const
bool isLetterOrDigit () const
bool isUpperCase () const
bool isLowerCase () const
beast_wchar toUpperCase () const noexcept
beast_wchar toLowerCase () const noexcept
int getIntValue32 () const noexcept
std::int64_t getIntValue64 () const noexcept
double getDoubleValue () const noexcept
CharPointer_ASCII findEndOfWhitespace () const noexcept
Static Public Member Functions
static size_t getBytesRequiredFor (const beast_wchar) noexcept
template<class CharPointer >
static size_t getBytesRequiredFor (const CharPointer text) noexcept
static bool canRepresent (beast_wchar character) noexcept
static bool isValidString (const CharType *dataToTest, int maxBytesToRead)
Private Attributes
CharType * data
Detailed Description
Wraps a pointer to a null-terminated ASCII character string, and provides various methods to operate on the data.
A valid ASCII string is assumed to not contain any characters above 127.
See Also
CharPointer_UTF8, CharPointer_UTF16, CharPointer_UTF32
Definition at line 45 of file CharPointer_ASCII.h.
Member Typedef Documentation
typedef char beast::CharPointer_ASCII::CharType
Definition at line 48 of file CharPointer_ASCII.h.
Constructor & Destructor Documentation
beast::CharPointer_ASCII::CharPointer_ASCII (const CharType *const rawPointer) inline explicit noexcept
Definition at line 50 of file CharPointer_ASCII.h.
Referenced by findTerminatingNull(), operator+(), and operator-().
         : data (const_cast <CharType*> (rawPointer))
     {
     }
beast::CharPointer_ASCII::CharPointer_ASCII (const CharPointer_ASCII & other) inline noexcept
Definition at line 55 of file CharPointer_ASCII.h.
         : data (other.data)
     {
     }
Member Function Documentation
static bool beast::CharPointer_ASCII::canRepresent (beast_wchar character) inline static noexcept
Returns true if the given unicode character can be represented in this encoding.
Definition at line 366 of file CharPointer_ASCII.h.
     {
         return ((unsigned int) character) < (unsigned int) 128;
     }
template<typename CharPointer > int beast::CharPointer_ASCII::compare (const CharPointer other) const inline noexcept
Compares this string with another one.
Definition at line 249 of file CharPointer_ASCII.h.
References beast::CharacterFunctions::compare().
     {
         return CharacterFunctions::compare (*this, other);
     }
int beast::CharPointer_ASCII::compare (const CharPointer_ASCII other) const inline noexcept
Compares this string with another one.
Definition at line 255 of file CharPointer_ASCII.h.
References data.
     {
         return strcmp (data, other.data);
     }
template<typename CharPointer > int beast::CharPointer_ASCII::compareIgnoreCase (const CharPointer other) const inline
Compares this string with another one.
Definition at line 275 of file CharPointer_ASCII.h.
References beast::CharacterFunctions::compareIgnoreCase().
     {
         return CharacterFunctions::compareIgnoreCase (*this, other);
     }
int beast::CharPointer_ASCII::compareIgnoreCase (const CharPointer_ASCII other) const inline
Definition at line 280 of file CharPointer_ASCII.h.
References data.
     {
        #if BEAST_WINDOWS
         return stricmp (data, other.data);
        #else
         return strcasecmp (data, other.data);
        #endif
     }
template<typename CharPointer > int beast::CharPointer_ASCII::compareIgnoreCaseUpTo (const CharPointer other, const int maxChars) const inline noexcept
Compares this string with another one, up to a specified number of characters.
Definition at line 291 of file CharPointer_ASCII.h.
References beast::CharacterFunctions::compareIgnoreCaseUpTo().
     {
         return CharacterFunctions::compareIgnoreCaseUpTo (*this, other, maxChars);
     }
template<typename CharPointer > int beast::CharPointer_ASCII::compareUpTo (const CharPointer other, const int maxChars) const inline noexcept
Compares this string with another one, up to a specified number of characters.
Definition at line 262 of file CharPointer_ASCII.h.
References beast::CharacterFunctions::compareUpTo().
     {
         return CharacterFunctions::compareUpTo (*this, other, maxChars);
     }
int beast::CharPointer_ASCII::compareUpTo (const CharPointer_ASCII other, const int maxChars) const inline noexcept
Compares this string with another one, up to a specified number of characters.
Definition at line 268 of file CharPointer_ASCII.h.
References data.
     {
         return strncmp (data, other.data, (size_t) maxChars);
     }
CharPointer_ASCII beast::CharPointer_ASCII::findEndOfWhitespace () const inline noexcept
Returns the first non-whitespace character in the string.
Definition at line 363 of file CharPointer_ASCII.h.
References beast::CharacterFunctions::findEndOfWhitespace().
 { return CharacterFunctions::findEndOfWhitespace (*this); }
CharPointer_ASCII beast::CharPointer_ASCII::findTerminatingNull () const inline noexcept
Returns a pointer to the null character that terminates this string.
Definition at line 209 of file CharPointer_ASCII.h.
References CharPointer_ASCII(), data, and length().
     {
         return CharPointer_ASCII (data + length());
     }
CharType* beast::CharPointer_ASCII::getAddress () const inline noexcept
Returns the address that this pointer is pointing to.
Definition at line 81 of file CharPointer_ASCII.h.
References data.
Referenced by beast::String::appendCharPointer().
 { return data; }
beast_wchar beast::CharPointer_ASCII::getAndAdvance () inline noexcept
Returns the character that this pointer is currently pointing to, and then advances the pointer to point to the next character.
Definition at line 108 of file CharPointer_ASCII.h.
References data.
 { return (beast_wchar) (std::uint8_t) *data++; }
static size_t beast::CharPointer_ASCII::getBytesRequiredFor (const beast_wchar) inline static noexcept
Returns the number of bytes that would be needed to represent the given unicode character in this encoding format.
Definition at line 193 of file CharPointer_ASCII.h.
     {
         return 1;
     }
template<class CharPointer > static size_t beast::CharPointer_ASCII::getBytesRequiredFor (const CharPointer text) inline static noexcept
Returns the number of bytes that would be needed to represent the given string in this encoding format. The value returned does NOT include the terminating null character.
Definition at line 203 of file CharPointer_ASCII.h.
     {
         return text.length();
     }
double beast::CharPointer_ASCII::getDoubleValue () const inline noexcept
Parses this string as a floating point double.
Definition at line 360 of file CharPointer_ASCII.h.
References beast::CharacterFunctions::getDoubleValue().
 { return CharacterFunctions::getDoubleValue (*this); }
int beast::CharPointer_ASCII::getIntValue32 () const inline noexcept
Parses this string as a 32-bit integer.
Definition at line 345 of file CharPointer_ASCII.h.
References data.
 { return atoi (data); }
std::int64_t beast::CharPointer_ASCII::getIntValue64 () const inline noexcept
Parses this string as a 64-bit integer.
Definition at line 348 of file CharPointer_ASCII.h.
References data.
     {
        #if BEAST_LINUX || BEAST_ANDROID
         return atoll (data);
        #elif BEAST_WINDOWS
         return _atoi64 (data);
        #else
         return CharacterFunctions::getIntValue <std::int64_t, CharPointer_ASCII> (*this);
        #endif
     }
template<typename CharPointer > int beast::CharPointer_ASCII::indexOf (const CharPointer stringToFind) const inline noexcept
Returns the character index of a substring, or -1 if it isn't found.
Definition at line 298 of file CharPointer_ASCII.h.
References beast::CharacterFunctions::indexOf().
     {
         return CharacterFunctions::indexOf (*this, stringToFind);
     }
int beast::CharPointer_ASCII::indexOf (const beast_wchar charToFind) const inline noexcept
Returns the character index of a unicode character, or -1 if it isn't found.
Definition at line 304 of file CharPointer_ASCII.h.
References data.
     {
         int i = 0;
         while (data[i] != 0)
         {
             if (data[i] == (char) charToFind)
                 return i;
             ++i;
         }
         return -1;
     }
int beast::CharPointer_ASCII::indexOf (const beast_wchar charToFind, const bool ignoreCase) const inline noexcept
Returns the character index of a unicode character, or -1 if it isn't found.
Definition at line 320 of file CharPointer_ASCII.h.
References beast::CharacterFunctions::indexOfChar(), and beast::CharacterFunctions::indexOfCharIgnoreCase().
     {
         return ignoreCase ? CharacterFunctions::indexOfCharIgnoreCase (*this, charToFind)
                           : CharacterFunctions::indexOfChar (*this, charToFind);
     }
bool beast::CharPointer_ASCII::isDigit () const inline
Returns true if the first character of this string is a digit.
Definition at line 329 of file CharPointer_ASCII.h.
References data, and beast::CharacterFunctions::isDigit().
 { return CharacterFunctions::isDigit (*data) != 0; }
bool beast::CharPointer_ASCII::isEmpty () const inline noexcept
Returns true if this pointer is pointing to a null character.
Definition at line 87 of file CharPointer_ASCII.h.
References data.
 { return *data == 0; }
bool beast::CharPointer_ASCII::isLetter () const inline
Returns true if the first character of this string is a letter.
Definition at line 331 of file CharPointer_ASCII.h.
References data, and beast::CharacterFunctions::isLetter().
 { return CharacterFunctions::isLetter (*data) != 0; }
bool beast::CharPointer_ASCII::isLetterOrDigit () const inline
Returns true if the first character of this string is a letter or digit.
Definition at line 333 of file CharPointer_ASCII.h.
References data, and beast::CharacterFunctions::isLetterOrDigit().
 { return CharacterFunctions::isLetterOrDigit (*data) != 0; }
bool beast::CharPointer_ASCII::isLowerCase () const inline
Returns true if the first character of this string is lower-case.
Definition at line 337 of file CharPointer_ASCII.h.
References data, and beast::CharacterFunctions::isLowerCase().
 { return CharacterFunctions::isLowerCase ((beast_wchar) (std::uint8_t) *data) != 0; }
bool beast::CharPointer_ASCII::isUpperCase () const inline
Returns true if the first character of this string is upper-case.
Definition at line 335 of file CharPointer_ASCII.h.
References data, and beast::CharacterFunctions::isUpperCase().
 { return CharacterFunctions::isUpperCase ((beast_wchar) (std::uint8_t) *data) != 0; }
static bool beast::CharPointer_ASCII::isValidString (const CharType * dataToTest, int maxBytesToRead) inline static
Returns true if this data contains a valid string in this encoding.
Definition at line 372 of file CharPointer_ASCII.h.
Referenced by beast::String::operator+=(), and beast::String::String().
     {
         while (--maxBytesToRead >= 0)
         {
             if (((signed char) *dataToTest) <= 0)
                 return *dataToTest == 0;
             ++dataToTest;
         }
         return true;
     }
bool beast::CharPointer_ASCII::isWhitespace () const inline
Returns true if the first character of this string is whitespace.
Definition at line 327 of file CharPointer_ASCII.h.
References data, and beast::CharacterFunctions::isWhitespace().
 { return CharacterFunctions::isWhitespace (*data) != 0; }
size_t beast::CharPointer_ASCII::length () const inline noexcept
Returns the number of characters in this string.
Definition at line 165 of file CharPointer_ASCII.h.
References data.
Referenced by findTerminatingNull(), and sizeInBytes().
     {
         return (size_t) strlen (data);
     }
size_t beast::CharPointer_ASCII::lengthUpTo (const size_t maxCharsToCount) const inline noexcept
Returns the number of characters in this string, or the given value, whichever is lower.
Definition at line 171 of file CharPointer_ASCII.h.
References beast::CharacterFunctions::lengthUpTo().
     {
         return CharacterFunctions::lengthUpTo (*this, maxCharsToCount);
     }
size_t beast::CharPointer_ASCII::lengthUpTo (const CharPointer_ASCII end) const inline noexcept
Returns the number of characters in this string, or up to the given end pointer, whichever is lower.
Definition at line 177 of file CharPointer_ASCII.h.
References beast::CharacterFunctions::lengthUpTo().
     {
         return CharacterFunctions::lengthUpTo (*this, end);
     }
beast::CharPointer_ASCII::operator const CharType * () const inline noexcept
Returns the address that this pointer is pointing to.
Definition at line 84 of file CharPointer_ASCII.h.
References data.
 { return data; }
bool beast::CharPointer_ASCII::operator!= (CharPointer_ASCII other) const inline noexcept
Definition at line 74 of file CharPointer_ASCII.h.
References data.
 { return data != other.data; }
beast_wchar beast::CharPointer_ASCII::operator* () const inline noexcept
Returns the unicode character that this pointer is pointing to.
Definition at line 90 of file CharPointer_ASCII.h.
References data.
 { return (beast_wchar) (std::uint8_t) *data; }
CharPointer_ASCII beast::CharPointer_ASCII::operator+ (const int numToSkip) const inline noexcept
Returns a pointer which is moved forwards from this one by the specified number of characters.
Definition at line 136 of file CharPointer_ASCII.h.
References CharPointer_ASCII(), and data.
     {
         return CharPointer_ASCII (data + numToSkip);
     }
CharPointer_ASCII beast::CharPointer_ASCII::operator++ () inline noexcept
Moves this pointer along to the next character in the string.
Definition at line 93 of file CharPointer_ASCII.h.
References data.
     {
         ++data;
         return *this;
     }
CharPointer_ASCII beast::CharPointer_ASCII::operator++ (int) inline noexcept
Moves this pointer along to the next character in the string.
Definition at line 111 of file CharPointer_ASCII.h.
References data.
     {
         CharPointer_ASCII temp (*this);
         ++data;
         return temp;
     }
void beast::CharPointer_ASCII::operator+= (const int numToSkip) inline noexcept
Moves this pointer forwards by the specified number of characters.
Definition at line 119 of file CharPointer_ASCII.h.
References data.
     {
         data += numToSkip;
     }
CharPointer_ASCII beast::CharPointer_ASCII::operator- (const int numToSkip) const inline noexcept
Returns a pointer which is moved backwards from this one by the specified number of characters.
Definition at line 142 of file CharPointer_ASCII.h.
References CharPointer_ASCII(), and data.
     {
         return CharPointer_ASCII (data - numToSkip);
     }
CharPointer_ASCII beast::CharPointer_ASCII::operator-- () inline noexcept
Moves this pointer to the previous character in the string.
Definition at line 100 of file CharPointer_ASCII.h.
References data.
     {
         --data;
         return *this;
     }
void beast::CharPointer_ASCII::operator-= (const int numToSkip) inline noexcept
Definition at line 124 of file CharPointer_ASCII.h.
References data.
     {
         data -= numToSkip;
     }
bool beast::CharPointer_ASCII::operator< (CharPointer_ASCII other) const inline noexcept
Definition at line 76 of file CharPointer_ASCII.h.
References data.
 { return data <  other.data; }
bool beast::CharPointer_ASCII::operator<= (CharPointer_ASCII other) const inline noexcept
Definition at line 75 of file CharPointer_ASCII.h.
References data.
 { return data <= other.data; }
CharPointer_ASCII beast::CharPointer_ASCII::operator= (const CharPointer_ASCII other) inline noexcept
Definition at line 60 of file CharPointer_ASCII.h.
References data.
     {
         data = other.data;
         return *this;
     }
CharPointer_ASCII beast::CharPointer_ASCII::operator= (const CharType * text) inline noexcept
Definition at line 66 of file CharPointer_ASCII.h.
References data.
     {
         data = const_cast <CharType*> (text);
         return *this;
     }
bool beast::CharPointer_ASCII::operator== (CharPointer_ASCII other) const inline noexcept
This is a pointer comparison, it doesn't compare the actual text.
Definition at line 73 of file CharPointer_ASCII.h.
References data.
 { return data == other.data; }
bool beast::CharPointer_ASCII::operator> (CharPointer_ASCII other) const inline noexcept
Definition at line 78 of file CharPointer_ASCII.h.
References data.
 { return data >  other.data; }
bool beast::CharPointer_ASCII::operator>= (CharPointer_ASCII other) const inline noexcept
Definition at line 77 of file CharPointer_ASCII.h.
References data.
 { return data >= other.data; }
beast_wchar beast::CharPointer_ASCII::operator[] (const int characterIndex) const inline noexcept
Returns the character at a given character index from the start of the string.
Definition at line 130 of file CharPointer_ASCII.h.
References data.
     {
         return (beast_wchar) (unsigned char) data [characterIndex];
     }
void beast::CharPointer_ASCII::replaceChar (const beast_wchar newChar) inline noexcept
Definition at line 153 of file CharPointer_ASCII.h.
References data.
     {
         *data = (char) newChar;
     }
size_t beast::CharPointer_ASCII::sizeInBytes () const inline noexcept
Returns the number of bytes that are used to represent this string. This includes the terminating null character.
Definition at line 185 of file CharPointer_ASCII.h.
References length().
     {
         return length() + 1;
     }
beast_wchar beast::CharPointer_ASCII::toLowerCase () const inline noexcept
Returns a lower-case version of the first character of this string.
Definition at line 342 of file CharPointer_ASCII.h.
References data, and beast::CharacterFunctions::toLowerCase().
 { return CharacterFunctions::toLowerCase ((beast_wchar) (std::uint8_t) *data); }
beast_wchar beast::CharPointer_ASCII::toUpperCase () const inline noexcept
Returns an upper-case version of the first character of this string.
Definition at line 340 of file CharPointer_ASCII.h.
References data, and beast::CharacterFunctions::toUpperCase().
 { return CharacterFunctions::toUpperCase ((beast_wchar) (std::uint8_t) *data); }
void beast::CharPointer_ASCII::write (const beast_wchar charToWrite) inline noexcept
Writes a unicode character to this string, and advances this pointer to point to the next position.
Definition at line 148 of file CharPointer_ASCII.h.
References data.
     {
         *data++ = (char) charToWrite;
     }
template<typename CharPointer > void beast::CharPointer_ASCII::writeAll (const CharPointer src) inline noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
Definition at line 216 of file CharPointer_ASCII.h.
References beast::CharacterFunctions::copyAll().
     {
         CharacterFunctions::copyAll (*this, src);
     }
void beast::CharPointer_ASCII::writeAll (const CharPointer_ASCII src) inline noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
Definition at line 222 of file CharPointer_ASCII.h.
References data.
     {
         strcpy (data, src.data);
     }
void beast::CharPointer_ASCII::writeNull () const inline noexcept
Writes a null character to this string (leaving the pointer's position unchanged).
Definition at line 159 of file CharPointer_ASCII.h.
References data.
     {
         *data = 0;
     }
template<typename CharPointer > void beast::CharPointer_ASCII::writeWithCharLimit (const CharPointer src, const int maxChars) inline noexcept
Copies a source string to this pointer, advancing this pointer as it goes. The maxChars parameter specifies the maximum number of characters that can be written to the destination buffer before stopping (including the terminating null).
Definition at line 242 of file CharPointer_ASCII.h.
References beast::CharacterFunctions::copyWithCharLimit().
     {
         CharacterFunctions::copyWithCharLimit (*this, src, maxChars);
     }
template<typename CharPointer > size_t beast::CharPointer_ASCII::writeWithDestByteLimit (const CharPointer src, const size_t maxDestBytes) inline noexcept
Copies a source string to this pointer, advancing this pointer as it goes. The maxDestBytes parameter specifies the maximum number of bytes that can be written to the destination buffer before stopping.
Definition at line 232 of file CharPointer_ASCII.h.
References beast::CharacterFunctions::copyWithDestByteLimit().
     {
         return CharacterFunctions::copyWithDestByteLimit (*this, src, maxDestBytes);
     }
Member Data Documentation
CharType* beast::CharPointer_ASCII::data private
Definition at line 386 of file CharPointer_ASCII.h.
Referenced by compare(), compareIgnoreCase(), compareUpTo(), findTerminatingNull(), getAddress(), getAndAdvance(), getIntValue32(), getIntValue64(), indexOf(), isDigit(), isEmpty(), isLetter(), isLetterOrDigit(), isLowerCase(), isUpperCase(), isWhitespace(), length(), operator const CharType *(), operator!=(), operator*(), operator+(), operator++(), operator+=(), operator-(), operator--(), operator-=(), operator<(), operator<=(), operator=(), operator==(), operator>(), operator>=(), operator[](), replaceChar(), toLowerCase(), toUpperCase(), write(), writeAll(), and writeNull().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/strings/CharPointer_ASCII.h