rippled: beast::HTTPParserImpl Class Reference
beast::HTTPParserImpl Class Reference
#include <HTTPParserImpl.h>
Public Types
enum { stringReservation = 256 }
Public Member Functions
HTTPParserImpl (enum joyent::http_parser_type type)
~HTTPParserImpl ()
unsigned char error () const
String message () const
std::size_t process (void const *buf, std::size_t bytes)
void process_eof ()
bool finished () const
HTTPVersion version () const
unsigned short status_code () const
unsigned char method () const
unsigned char http_errno () const
String http_errno_message () const
bool upgrade () const
StringPairArray & fields ()
bool headers_complete () const
DynamicBuffer & body ()
Private Member Functions
void addFieldValue ()
int onMessageBegin ()
int onUrl (char const *, std::size_t)
int onStatus ()
int onHeaderField (char const *at, std::size_t length)
int onHeaderValue (char const *at, std::size_t length)
int onHeadersComplete ()
int onBody (char const *at, std::size_t length)
int onMessageComplete ()
Static Private Member Functions
static int on_message_begin (joyent::http_parser *parser)
static int on_url (joyent::http_parser *parser, const char *at, size_t length)
static int on_status (joyent::http_parser *parser, char const *, size_t)
static int on_header_field (joyent::http_parser *parser, const char *at, size_t length)
static int on_header_value (joyent::http_parser *parser, const char *at, size_t length)
static int on_headers_complete (joyent::http_parser *parser)
static int on_body (joyent::http_parser *parser, const char *at, size_t length)
static int on_message_complete (joyent::http_parser *parser)
Private Attributes
bool m_finished
joyent::http_parser_settings m_settings
joyent::http_parser m_parser
StringPairArray m_fields
bool m_was_value
std::string m_field
std::string m_value
bool m_headersComplete
DynamicBuffer m_body
Detailed Description
Definition at line 25 of file HTTPParserImpl.h.
Member Enumeration Documentation
anonymous enum
Enumerator
stringReservation
Definition at line 28 of file HTTPParserImpl.h.
     {
         stringReservation = 256
     };
Constructor & Destructor Documentation
beast::HTTPParserImpl::HTTPParserImpl (enum joyent::http_parser_type type) inline explicit
Definition at line 33 of file HTTPParserImpl.h.
References beast::joyent::http_parser::data, beast::joyent::http_parser_init(), m_field, m_parser, m_settings, m_value, beast::joyent::http_parser_settings::on_body, on_body(), on_header_field(), beast::joyent::http_parser_settings::on_header_field, beast::joyent::http_parser_settings::on_header_value, on_header_value(), beast::joyent::http_parser_settings::on_headers_complete, on_headers_complete(), on_message_begin(), beast::joyent::http_parser_settings::on_message_begin, beast::joyent::http_parser_settings::on_message_complete, on_message_complete(), on_status(), beast::joyent::http_parser_settings::on_status, on_url(), beast::joyent::http_parser_settings::on_url, and stringReservation.
         : m_finished (false)
         , m_was_value (false)
         , m_headersComplete (false)
     {
         m_settings.on_message_begin     = &HTTPParserImpl::on_message_begin;
         m_settings.on_url               = &HTTPParserImpl::on_url;
         m_settings.on_status            = &HTTPParserImpl::on_status;
         m_settings.on_header_field      = &HTTPParserImpl::on_header_field;
         m_settings.on_header_value      = &HTTPParserImpl::on_header_value;
         m_settings.on_headers_complete  = &HTTPParserImpl::on_headers_complete;
         m_settings.on_body              = &HTTPParserImpl::on_body;
         m_settings.on_message_complete  = &HTTPParserImpl::on_message_complete;
         m_field.reserve (stringReservation);
         m_value.reserve (stringReservation);
         joyent::http_parser_init (&m_parser, type);
         m_parser.data = this;
     }
beast::HTTPParserImpl::~HTTPParserImpl () inline
Definition at line 54 of file HTTPParserImpl.h.
     {
     }
Member Function Documentation
void beast::HTTPParserImpl::addFieldValue () inline private
Definition at line 136 of file HTTPParserImpl.h.
References m_field, m_fields, m_value, and beast::StringPairArray::set().
Referenced by onHeaderField(), and onHeadersComplete().
     {
         if (m_field.size () > 0 && m_value.size () > 0)
             m_fields.set (m_field, m_value);
         m_field.resize (0);
         m_value.resize (0);
     }
DynamicBuffer& beast::HTTPParserImpl::body () inline
Definition at line 130 of file HTTPParserImpl.h.
References m_body.
     {
         return m_body;
     }
unsigned char beast::HTTPParserImpl::error () const inline
Definition at line 58 of file HTTPParserImpl.h.
References beast::joyent::http_parser::http_errno, and m_parser.
     {
         return m_parser.http_errno;
     }
StringPairArray& beast::HTTPParserImpl::fields () inline
Definition at line 120 of file HTTPParserImpl.h.
References m_fields.
     {
         return m_fields;
     }
bool beast::HTTPParserImpl::finished () const inline
Definition at line 80 of file HTTPParserImpl.h.
References m_finished.
     {
         return m_finished;
     }
bool beast::HTTPParserImpl::headers_complete () const inline
Definition at line 125 of file HTTPParserImpl.h.
References m_headersComplete.
     {
         return m_headersComplete;
     }
unsigned char beast::HTTPParserImpl::http_errno () const inline
Definition at line 103 of file HTTPParserImpl.h.
References beast::joyent::http_parser::http_errno, and m_parser.
     {
         return m_parser.http_errno;
     }
String beast::HTTPParserImpl::http_errno_message () const inline
Definition at line 108 of file HTTPParserImpl.h.
References beast::joyent::http_parser::http_errno, beast::joyent::http_errno_name(), and m_parser.
     {
         return String (joyent::http_errno_name (
             static_cast <enum joyent::http_errno> (
                 m_parser.http_errno)));
     }
String beast::HTTPParserImpl::message () const inline
Definition at line 63 of file HTTPParserImpl.h.
References beast::joyent::http_parser::http_errno, beast::joyent::http_errno_name(), and m_parser.
     {
         return String (joyent::http_errno_name (static_cast <
             enum joyent::http_errno> (m_parser.http_errno)));
     }
unsigned char beast::HTTPParserImpl::method () const inline
Definition at line 98 of file HTTPParserImpl.h.
References m_parser, and beast::joyent::http_parser::method.
     {
         return m_parser.method;
     }
static int beast::HTTPParserImpl::on_body (joyent::http_parser * parser, const char * at, size_t length) inline static private
Definition at line 246 of file HTTPParserImpl.h.
References beast::joyent::http_parser::data, and onBody().
Referenced by HTTPParserImpl().
     {
         return static_cast <HTTPParserImpl*> (parser->data)->
             onBody (at, length);
     }
static int beast::HTTPParserImpl::on_header_field (joyent::http_parser * parser, const char * at, size_t length) inline static private
Definition at line 226 of file HTTPParserImpl.h.
References beast::joyent::http_parser::data, and onHeaderField().
Referenced by HTTPParserImpl().
     {
         return static_cast <HTTPParserImpl*> (parser->data)->
             onHeaderField (at, length);
     }
static int beast::HTTPParserImpl::on_header_value (joyent::http_parser * parser, const char * at, size_t length) inline static private
Definition at line 233 of file HTTPParserImpl.h.
References beast::joyent::http_parser::data, and onHeaderValue().
Referenced by HTTPParserImpl().
     {
         return static_cast <HTTPParserImpl*> (parser->data)->
             onHeaderValue (at, length);
     }
static int beast::HTTPParserImpl::on_headers_complete (joyent::http_parser * parser) inline static private
Definition at line 240 of file HTTPParserImpl.h.
References beast::joyent::http_parser::data, and onHeadersComplete().
Referenced by HTTPParserImpl().
     {
         return static_cast <HTTPParserImpl*> (parser->data)->
             onHeadersComplete ();
     }
static int beast::HTTPParserImpl::on_message_begin (joyent::http_parser * parser) inline static private
Definition at line 207 of file HTTPParserImpl.h.
References beast::joyent::http_parser::data, and onMessageBegin().
Referenced by HTTPParserImpl().
     {
         return static_cast <HTTPParserImpl*> (parser->data)->
             onMessageBegin ();
     }
static int beast::HTTPParserImpl::on_message_complete (joyent::http_parser * parser) inline static private
Definition at line 253 of file HTTPParserImpl.h.
References beast::joyent::http_parser::data, and onMessageComplete().
Referenced by HTTPParserImpl().
     {
         return static_cast <HTTPParserImpl*> (parser->data)->
             onMessageComplete ();
     }
static int beast::HTTPParserImpl::on_status (joyent::http_parser * parser, char const * , size_t) inline static private
Definition at line 219 of file HTTPParserImpl.h.
References beast::joyent::http_parser::data, and onStatus().
Referenced by HTTPParserImpl().
     {
         return static_cast <HTTPParserImpl*> (parser->data)->
             onStatus ();
     }
static int beast::HTTPParserImpl::on_url (joyent::http_parser * parser, const char * at, size_t length) inline static private
Definition at line 213 of file HTTPParserImpl.h.
References beast::joyent::http_parser::data, and onUrl().
Referenced by HTTPParserImpl().
     {
         return static_cast <HTTPParserImpl*> (parser->data)->
             onUrl (at, length);
     }
int beast::HTTPParserImpl::onBody (char const * at, std::size_t length) inline private
Definition at line 191 of file HTTPParserImpl.h.
References beast::DynamicBuffer::commit(), m_body, and beast::DynamicBuffer::prepare().
Referenced by on_body().
     {
         m_body.commit (boost::asio::buffer_copy (
             m_body.prepare <boost::asio::mutable_buffer> (length),
                 boost::asio::buffer (at, length)));
         return 0;
     }
int beast::HTTPParserImpl::onHeaderField (char const * at, std::size_t length) inline private
Definition at line 163 of file HTTPParserImpl.h.
References addFieldValue(), m_field, and m_was_value.
Referenced by on_header_field().
     {
         int ec (0);
         if (m_was_value)
         {
             addFieldValue ();
             m_was_value = false;
         }
         m_field.append (at, length);
         return ec;
     }
int beast::HTTPParserImpl::onHeadersComplete () inline private
Definition at line 183 of file HTTPParserImpl.h.
References addFieldValue(), and m_headersComplete.
Referenced by on_headers_complete().
     {
         m_headersComplete = true;
         int ec (0);
         addFieldValue ();
         return ec;
     }
int beast::HTTPParserImpl::onHeaderValue (char const * at, std::size_t length) inline private
Definition at line 175 of file HTTPParserImpl.h.
References m_value, and m_was_value.
Referenced by on_header_value().
     {
         int ec (0);
         m_value.append (at, length);
         m_was_value = true;
         return ec;
     }
int beast::HTTPParserImpl::onMessageBegin () inline private
Definition at line 144 of file HTTPParserImpl.h.
Referenced by on_message_begin().
     {
         int ec (0);
         return ec;
     }
int beast::HTTPParserImpl::onMessageComplete () inline private
Definition at line 199 of file HTTPParserImpl.h.
References m_finished.
Referenced by on_message_complete().
     {
         int ec (0);
         m_finished = true;
         return ec;
     }
int beast::HTTPParserImpl::onStatus () inline private
Definition at line 157 of file HTTPParserImpl.h.
Referenced by on_status().
     {
         int ec (0);
         return ec;
     }
int beast::HTTPParserImpl::onUrl (char const * , std::size_t) inline private
Definition at line 150 of file HTTPParserImpl.h.
Referenced by on_url().
     {
         int ec (0);
         // This is for HTTP Request
         return ec;
     }
std::size_t beast::HTTPParserImpl::process (void const * buf, std::size_t bytes) inline
Definition at line 69 of file HTTPParserImpl.h.
References beast::joyent::http_parser_execute(), m_parser, and m_settings.
     {
         return joyent::http_parser_execute (&m_parser,
             &m_settings, static_cast <char const*> (buf), bytes);
     }
void beast::HTTPParserImpl::process_eof () inline
Definition at line 75 of file HTTPParserImpl.h.
References beast::joyent::http_parser_execute(), m_parser, and m_settings.
     {
         joyent::http_parser_execute (&m_parser, &m_settings, nullptr, 0);
     }
unsigned short beast::HTTPParserImpl::status_code () const inline
Definition at line 92 of file HTTPParserImpl.h.
References m_parser, and beast::joyent::http_parser::status_code.
     {
         return m_parser.status_code;
     }
bool beast::HTTPParserImpl::upgrade () const inline
Definition at line 115 of file HTTPParserImpl.h.
References m_parser, and beast::joyent::http_parser::upgrade.
     {
         return m_parser.upgrade != 0;
     }
HTTPVersion beast::HTTPParserImpl::version () const inline
Definition at line 85 of file HTTPParserImpl.h.
References beast::joyent::http_parser::http_major, beast::joyent::http_parser::http_minor, and m_parser.
     {
         return HTTPVersion (
             m_parser.http_major, m_parser.http_minor);
     }
Member Data Documentation
DynamicBuffer beast::HTTPParserImpl::m_body private
Definition at line 268 of file HTTPParserImpl.h.
Referenced by body(), and onBody().
std::string beast::HTTPParserImpl::m_field private
Definition at line 265 of file HTTPParserImpl.h.
Referenced by addFieldValue(), HTTPParserImpl(), and onHeaderField().
StringPairArray beast::HTTPParserImpl::m_fields private
Definition at line 263 of file HTTPParserImpl.h.
Referenced by addFieldValue(), and fields().
bool beast::HTTPParserImpl::m_finished private
Definition at line 260 of file HTTPParserImpl.h.
Referenced by finished(), and onMessageComplete().
bool beast::HTTPParserImpl::m_headersComplete private
Definition at line 267 of file HTTPParserImpl.h.
Referenced by headers_complete(), and onHeadersComplete().
joyent::http_parser beast::HTTPParserImpl::m_parser private
Definition at line 262 of file HTTPParserImpl.h.
Referenced by error(), http_errno(), http_errno_message(), HTTPParserImpl(), message(), method(), process(), process_eof(), status_code(), upgrade(), and version().
joyent::http_parser_settings beast::HTTPParserImpl::m_settings private
Definition at line 261 of file HTTPParserImpl.h.
Referenced by HTTPParserImpl(), process(), and process_eof().
std::string beast::HTTPParserImpl::m_value private
Definition at line 266 of file HTTPParserImpl.h.
Referenced by addFieldValue(), HTTPParserImpl(), and onHeaderValue().
bool beast::HTTPParserImpl::m_was_value private
Definition at line 264 of file HTTPParserImpl.h.
Referenced by onHeaderField(), and onHeaderValue().
The documentation for this class was generated from the following file:
rippled/src/beast/modules/beast_asio/http/HTTPParserImpl.h