rippled: beast::Stoppable Class Reference
beast::Stoppable Class Reference
#include <Stoppable.h>
Classes
struct Child
Public Member Functions
Stoppable (char const *name, Stoppable &parent)
virtual ~Stoppable ()
bool isStopping () const
bool isStopped () const
bool areChildrenStopped () const
void stopped ()
virtual void onPrepare ()
virtual void onStart ()
virtual void onStop ()
virtual void onChildrenStopped ()
Protected Member Functions
Stoppable (char const *name, RootStoppable &root)
Protected Attributes
char const * m_name
RootStoppable & m_root
Child m_child
Atomic< int > m_started
bool volatile m_stopped
bool volatile m_childrenStopped
Children m_children
WaitableEvent m_stoppedEvent
Private Types
typedef LockFreeStack< Child > Children
Private Member Functions
void prepareRecursive ()
void startRecursive ()
void stopAsyncRecursive ()
void stopRecursive (Journal journal)
Friends
class RootStoppable
Detailed Description
Provides an interface for starting and stopping.
A common method of structuring server or peer to peer code is to isolate conceptual portions of functionality into individual classes, aggregated into some larger "application" or "core" object which holds all the parts. Frequently, these components are dependent on each other in unavoidably complex ways. They also often use threads and perform asynchronous i/o operations involving sockets or other operating system objects. The process of starting and stopping such a system can be complex. This interface provides a set of behaviors for ensuring that the start and stop of a composite application-style object is well defined.
Upon the initialization of the composite object these steps are peformed:
Construct sub-components.
These are all typically derived from Stoppable. There can be a deep hierarchy: Stoppable objects may themselves have Stoppable child objects. This captures the relationship of dependencies.
prepare()
Because some components may depend on others, preparatory steps require that all objects be first constructed. The prepare step calls all Stoppable objects in the tree starting from the leaves and working up to the root. In this stage we are guaranteed that all objects have been constructed and are in a well-defined state.
onPrepare()
This override is called for all Stoppable objects in the hierarchy during the prepare stage. Objects are called from the bottom up. It is guaranteed that all child Stoppable objects have already been prepared when this is called.
start()
At this point all sub-components have been constructed and prepared, so it should be safe for them to be started. While some Stoppable objects may do nothing in their start function, others will start threads or call asynchronous i/o initiating functions like timers or sockets.
onStart()
This override is called for all Stoppable objects in the hierarchy during the start stage. Objects are called from the bottom up. It is guaranteed that all child Stoppable objects have already been started when this is called.
This is the sequence of events involved in stopping:
stopAsync() [optional]
This notifies the root Stoppable and all its children that a stop is requested.
stop()
This first calls stopAsync(), and then blocks on each child Stoppable in the in the tree from the bottom up, until the Stoppable indicates it has stopped. This will usually be called from the main thread of execution when some external signal indicates that the process should stop. For example, an RPC 'stop' command, or a SIGINT POSIX signal.
onStop()
This override is called for the root Stoppable and all its children when stopAsync() is called. Derived classes should cancel pending I/O and timers, signal that threads should exit, queue cleanup jobs, and perform any other necessary final actions in preparation for exit.
onChildrenStopped()
This override is called when all the children have stopped. This informs the Stoppable that there should not be any more dependents making calls into its member functions. A Stoppable that has no children will still have this function called.
stopped()
The derived class calls this function to inform the Stoppable API that it has completed the stop. This unblocks the caller of stop().
For stoppables which are only considered stopped when all of their children have stopped, and their own internal logic indicates a stop, it will be necessary to perform special actions in onChildrenStopped(). The funtion areChildrenStopped() can be used after children have stopped, but before the Stoppable logic itself has stopped, to determine if the stoppable's logic is a true stop.
Pseudo code for this process is as follows:
// Returns `true` if derived logic has stopped.
//
// When the logic stops, logicProcessingStop() is no longer called.
// If children are still active we need to wait until we get a
// notification that the children have stopped.
//
bool logicHasStopped ();
// Called when children have stopped
void onChildrenStopped ()
{
    // We have stopped when the derived logic stops and children stop.
    if (logicHasStopped)
        stopped();
}
// derived-specific logic that executes periodically
void logicProcessingStep ()
{
    // process
    // ...
    // now see if we've stopped
    if (logicHasStopped() && areChildrenStopped())
        stopped();
}
Derived class that manage one or more threads should typically notify those threads in onStop that they should exit. In the thread function, when the last thread is about to exit it would call stopped().
Note
A Stoppable may not be restarted.
Definition at line 164 of file Stoppable.h.
Member Typedef Documentation
typedef LockFreeStack<Child> beast::Stoppable::Children private
Definition at line 247 of file Stoppable.h.
Constructor & Destructor Documentation
beast::Stoppable::Stoppable (char const * name, RootStoppable & root) protected
Definition at line 24 of file Stoppable.cpp.
     : m_name (name)
     , m_root (root)
     , m_child (this)
     , m_stopped (false)
     , m_childrenStopped (false)
 {
 }
beast::Stoppable::Stoppable (char const * name, Stoppable & parent)
Create the Stoppable.
Definition at line 33 of file Stoppable.cpp.
References bassert, isStopping(), m_child, m_children, and beast::LockFreeStack< Element, Tag >::push_front().
     : m_name (name)
     , m_root (parent.m_root)
     , m_child (this)
     , m_stopped (false)
     , m_childrenStopped (false)
 {
     // Must not have stopping parent.
     bassert (! parent.isStopping());
     parent.m_children.push_front (&m_child);
 }
beast::Stoppable::~Stoppable () virtual
Destroy the Stoppable.
Definition at line 46 of file Stoppable.cpp.
References bassert, beast::Atomic< Type >::get(), m_childrenStopped, and m_started.
 {
     // Children must be stopped.
     bassert (m_started.get() == 0 || m_childrenStopped);
 }
Member Function Documentation
bool beast::Stoppable::areChildrenStopped () const
Returns true if all children have stopped.
Definition at line 62 of file Stoppable.cpp.
References m_childrenStopped.
Referenced by ripple::JobQueueImp::addJob(), ripple::OverlayImpl::check_stopped(), and ripple::JobQueueImp::checkStopped().
 {
     return m_childrenStopped;
 }
bool beast::Stoppable::isStopped () const
Returns true if the requested stop has completed.
Definition at line 57 of file Stoppable.cpp.
References m_stopped.
Referenced by ripple::JobQueueImp::addJob().
 {
     return m_stopped;
 }
bool beast::Stoppable::isStopping () const
Returns true if the stoppable should stop.
Definition at line 52 of file Stoppable.cpp.
References beast::RootStoppable::isStopping(), and m_root.
Referenced by ripple::JobQueueImp::addJob(), ripple::JobQueueImp::checkStopped(), ripple::OverlayImpl::connect(), ripple::NodeStoreScheduler::doTask(), ripple::InboundLedgersImp::findCreate(), ripple::Validators::ManagerImp::ledgerClosed(), ripple::IoServicePool::onThreadExit(), ripple::JobQueueImp::processTask(), ripple::Validators::ManagerImp::receiveValidation(), and Stoppable().
 {
     return m_root.isStopping();
 }
void beast::Stoppable::onChildrenStopped () virtual
Override called when all children have stopped.
The call is made on an unspecified, implementation-specific thread. onStop and onChildrenStopped will never be called concurrently, across all Stoppable objects descended from the same root, inclusive of the root.
It is safe to call isStopping, isStopped, and areChildrenStopped from within this function; The values returned will always be valid and never change during the callback.
The default implementation does nothing.
Thread safety: May not block for long periods. Guaranteed only to be called once. Must be safe to call from any thread at any time.
Reimplemented in ripple::JobQueueImp, ripple::OverlayImpl, ripple::RPCHTTPServerImp, ripple::NodeStoreScheduler, and ripple::IoServicePool.
Definition at line 85 of file Stoppable.cpp.
Referenced by stopRecursive().
 {
 }
void beast::Stoppable::onPrepare () virtual
Override called during preparation. Since all other Stoppable objects in the tree have already been constructed, this provides an opportunity to perform initialization which depends on calling into other Stoppable objects. This call is made on the same thread that called prepare(). The default implementation does nothing. Guaranteed to only be called once.
Reimplemented in ripple::ApplicationImp, ripple::Validators::ManagerImp, ripple::PeerFinder::ManagerImp, ripple::OverlayImpl, ripple::LoadManagerImp, ripple::LedgerCleanerImp, and ripple::SiteFiles::ManagerImp.
Definition at line 72 of file Stoppable.cpp.
Referenced by prepareRecursive().
 {
 }
void beast::Stoppable::onStart () virtual
Override called during start.
Reimplemented in ripple::ApplicationImp, ripple::Validators::ManagerImp, ripple::PeerFinder::ManagerImp, ripple::OverlayImpl, ripple::LoadManagerImp, ripple::SNTPClientImp, ripple::LedgerCleanerImp, ripple::SiteFiles::ManagerImp, and ripple::IoServicePool.
Definition at line 76 of file Stoppable.cpp.
Referenced by startRecursive().
 {
 }
void beast::Stoppable::onStop () virtual
Override called when the stop notification is issued.
The call is made on an unspecified, implementation-specific thread. onStop and onChildrenStopped will never be called concurrently, across all Stoppable objects descended from the same root, inclusive of the root.
It is safe to call isStopping, isStopped, and areChildrenStopped from within this function; The values returned will always be valid and never change during the callback.
The default implementation simply calls stopped(). This is applicable when the Stoppable has a trivial stop operation (or no stop operation), and we are merely using the Stoppable API to position it as a dependency of some parent service.
Thread safety: May not block for long periods. Guaranteed only to be called once. Must be safe to call from any thread at any time.
Reimplemented in ripple::ApplicationImp, ripple::JobQueueImp, ripple::NetworkOPsImp, ripple::InboundLedgersImp, ripple::Validators::ManagerImp, ripple::PeerFinder::ManagerImp, ripple::OverlayImpl, ripple::UniqueNodeListImp, ripple::WSDoorImp, ripple::LoadManagerImp, ripple::SNTPClientImp, ripple::RPCHTTPServerImp, ripple::LedgerCleanerImp, ripple::SiteFiles::ManagerImp, ripple::NodeStoreScheduler, and ripple::IoServicePool.
Definition at line 80 of file Stoppable.cpp.
References stopped().
Referenced by stopAsyncRecursive().
 {
     stopped();
 }
void beast::Stoppable::prepareRecursive () private
Definition at line 91 of file Stoppable.cpp.
References beast::LockFreeStack< Element, Tag >::cbegin(), beast::LockFreeStack< Element, Tag >::cend(), m_children, and onPrepare().
Referenced by beast::RootStoppable::prepare(), and beast::RootStoppable::start().
 {
     for (Children::const_iterator iter (m_children.cbegin ());
         iter != m_children.cend(); ++iter)
         iter->stoppable->prepareRecursive ();
     onPrepare ();
 }
void beast::Stoppable::startRecursive () private
Definition at line 99 of file Stoppable.cpp.
References beast::LockFreeStack< Element, Tag >::cbegin(), beast::LockFreeStack< Element, Tag >::cend(), m_children, and onStart().
Referenced by beast::RootStoppable::start().
 {
     onStart ();
     for (Children::const_iterator iter (m_children.cbegin ());
         iter != m_children.cend(); ++iter)
         iter->stoppable->startRecursive ();
 }
void beast::Stoppable::stopAsyncRecursive () private
Definition at line 107 of file Stoppable.cpp.
References beast::LockFreeStack< Element, Tag >::cbegin(), beast::LockFreeStack< Element, Tag >::cend(), m_children, and onStop().
Referenced by beast::RootStoppable::stopAsync().
 {
     onStop ();
     for (Children::const_iterator iter (m_children.cbegin ());
         iter != m_children.cend(); ++iter)
         iter->stoppable->stopAsyncRecursive ();
 }
void beast::Stoppable::stopped ()
Called by derived classes to indicate that the stoppable has stopped.
Definition at line 67 of file Stoppable.cpp.
References m_stoppedEvent, and beast::WaitableEvent::signal().
Referenced by ripple::OverlayImpl::check_stopped(), ripple::JobQueueImp::checkStopped(), ripple::NodeStoreScheduler::doTask(), ripple::NodeStoreScheduler::onChildrenStopped(), ripple::LoadManagerImp::onStop(), onStop(), ripple::InboundLedgersImp::onStop(), ripple::NetworkOPsImp::onStop(), ripple::ApplicationImp::onStop(), ripple::RPCHTTPServerImp::onStopped(), ripple::IoServicePool::onThreadExit(), ripple::SNTPClientImp::run(), ripple::SiteFiles::ManagerImp::run(), ripple::LoadManagerImp::run(), ripple::LedgerCleanerImp::run(), ripple::PeerFinder::ManagerImp::run(), and ripple::Validators::ManagerImp::run().
 {
     m_stoppedEvent.signal();
 }
void beast::Stoppable::stopRecursive (Journal journal) private
Definition at line 115 of file Stoppable.cpp.
References beast::LockFreeStack< Element, Tag >::cbegin(), beast::LockFreeStack< Element, Tag >::cend(), m_children, m_childrenStopped, m_name, m_stopped, m_stoppedEvent, beast::memoryBarrier(), onChildrenStopped(), beast::WaitableEvent::wait(), and beast::Journal::warning.
Referenced by beast::RootStoppable::stop().
 {
     // Block on each child from the bottom of the tree up.
     //
     for (Children::const_iterator iter (m_children.cbegin ());
         iter != m_children.cend(); ++iter)
         iter->stoppable->stopRecursive (journal);
     // if we get here then all children have stopped
     //
     memoryBarrier ();
     m_childrenStopped = true;
     onChildrenStopped ();
     // Now block on this Stoppable.
     //
     bool const timedOut (! m_stoppedEvent.wait (1 * 1000)); // milliseconds
     if (timedOut)
     {
         journal.warning << "Waiting for '" << m_name << "' to stop";
         m_stoppedEvent.wait ();
     }
     // once we get here, we know the stoppable has stopped.
     m_stopped = true;
 }
Friends And Related Function Documentation
friend class RootStoppable friend
Definition at line 245 of file Stoppable.h.
Member Data Documentation
Child beast::Stoppable::m_child protected
Definition at line 267 of file Stoppable.h.
Referenced by Stoppable().
Children beast::Stoppable::m_children protected
Definition at line 271 of file Stoppable.h.
Referenced by prepareRecursive(), startRecursive(), stopAsyncRecursive(), Stoppable(), and stopRecursive().
bool volatile beast::Stoppable::m_childrenStopped protected
Definition at line 270 of file Stoppable.h.
Referenced by areChildrenStopped(), stopRecursive(), and ~Stoppable().
char const* beast::Stoppable::m_name protected
Definition at line 265 of file Stoppable.h.
Referenced by stopRecursive().
RootStoppable& beast::Stoppable::m_root protected
Definition at line 266 of file Stoppable.h.
Referenced by isStopping().
Atomic<int> beast::Stoppable::m_started protected
Definition at line 268 of file Stoppable.h.
Referenced by beast::RootStoppable::start(), beast::RootStoppable::stop(), and ~Stoppable().
bool volatile beast::Stoppable::m_stopped protected
Definition at line 269 of file Stoppable.h.
Referenced by isStopped(), and stopRecursive().
WaitableEvent beast::Stoppable::m_stoppedEvent protected
Definition at line 272 of file Stoppable.h.
Referenced by stopped(), and stopRecursive().
The documentation for this class was generated from the following files:
rippled/src/beast/beast/threads/Stoppable.h
rippled/src/beast/beast/threads/impl/Stoppable.cpp