rippled: ripple::Resource::Manager_test Class Reference
ripple::Resource::Manager_test Class Reference
Classes
class TestLogic
Public Types
enum { maxLoopCount = 10000 }
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Member Functions
void createGossip (Gossip &gossip)
void testDrop (beast::Journal j)
void testImports (beast::Journal j)
void testImport (beast::Journal j)
void testCharges (beast::Journal j)
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Additional Inherited Members
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 27 of file Tests.cpp.
Member Enumeration Documentation
anonymous enum
Enumerator
maxLoopCount
Definition at line 76 of file Tests.cpp.
     {
         maxLoopCount = 10000
     };
Member Function Documentation
void ripple::Resource::Manager_test::createGossip (Gossip & gossip) inline
Definition at line 58 of file Tests.cpp.
References ripple::Resource::Gossip::Item::address, ripple::Resource::Gossip::Item::balance, ripple::Resource::Gossip::items, and beast::Random::nextInt().
Referenced by testImports().
     {
         beast::Random r;
         int const v (10 + r.nextInt (10));
         int const n (10 + r.nextInt (10));
         gossip.items.reserve (n);
         for (int i = 0; i < n; ++i)
         {
             Gossip::Item item;
             item.balance = 100 + r.nextInt (500);
             item.address = beast::IP::Endpoint (
                 beast::IP::AddressV4 (207, 127, 82, v + i));
             gossip.items.push_back (item);
         }
     }
void ripple::Resource::Manager_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 228 of file Tests.cpp.
References testCharges(), testDrop(), testImport(), and testImports().
     {
         beast::Journal j;
         testDrop (j);
         testCharges (j);
         testImports (j);
         testImport (j);
     }
void ripple::Resource::Manager_test::testCharges (beast::Journal j) inline
Definition at line 187 of file Tests.cpp.
References ripple::Resource::Manager_test::TestLogic::advance(), ripple::Resource::Manager_test::TestLogic::clock(), beast::IP::Endpoint::from_string(), beast::Journal::info, ripple::Resource::Logic::newInboundEndpoint(), beast::unit_test::suite::pass(), and beast::unit_test::suite::testcase().
Referenced by run().
     {
         testcase ("Charge");
         TestLogic logic (j);
         {
             beast::IP::Endpoint address (beast::IP::Endpoint::from_string ("207.127.82.1"));
             Consumer c (logic.newInboundEndpoint (address));
             Charge fee (1000);
             j.info <<
                 "Charging " << c.to_string() << " " << fee << " per second";
             c.charge (fee);
             for (int i = 0; i < 128; ++i)
             {
                 j.info <<
                     "Time= " << logic.clock().now().time_since_epoch() <<
                     ", Balance = " << c.balance();
                 logic.advance();
             }
         }
         {
             beast::IP::Endpoint address (beast::IP::Endpoint::from_string ("207.127.82.2"));
             Consumer c (logic.newInboundEndpoint (address));
             Charge fee (1000);
             j.info <<
                 "Charging " << c.to_string() << " " << fee << " per second";
             for (int i = 0; i < 128; ++i)
             {
                 c.charge (fee);
                 j.info <<
                     "Time= " << logic.clock().now().time_since_epoch() <<
                     ", Balance = " << c.balance();
                 logic.advance();
             }
         }
         pass();
     }
void ripple::Resource::Manager_test::testDrop (beast::Journal j) inline
Definition at line 81 of file Tests.cpp.
References ripple::Resource::Manager_test::TestLogic::clock(), ripple::Resource::drop, ripple::Resource::dropThreshold, beast::unit_test::suite::expect(), beast::unit_test::suite::fail(), beast::IP::Endpoint::from_string(), maxLoopCount, ripple::Resource::Logic::newInboundEndpoint(), beast::unit_test::suite::pass(), beast::unit_test::suite::testcase(), and ripple::Resource::warn.
Referenced by run().
     {
         testcase ("Warn/drop");
         TestLogic logic (j);
         Charge const fee (dropThreshold + 1);
         beast::IP::Endpoint const addr (
             beast::IP::Endpoint::from_string ("207.127.82.2"));
         {
             Consumer c (logic.newInboundEndpoint (addr));
             // Create load until we get a warning
             for (std::size_t n (maxLoopCount); true; --n)
             {
                 if (n == 0)
                 {
                     fail ("Loop count exceeded without warning");
                     return;
                 }
                 if (c.charge (fee) == warn)
                 {
                     pass ();
                     break;
                 }
                 ++logic.clock ();
             }
             // Create load until we get dropped
             for (std::size_t n (maxLoopCount); true; --n)
             {
                 if (n == 0)
                 {
                     fail ("Loop count exceeded without dropping");
                     return;
                 }
                 if (c.charge (fee) == drop)
                 {
                     pass ();
                     break;
                 }
                 ++logic.clock ();
             }
         }
         {
             Consumer c (logic.newInboundEndpoint (addr));
             expect (c.disconnect ());
         }
         for (std::size_t n (maxLoopCount); true; --n)
         {
             Consumer c (logic.newInboundEndpoint (addr));
             if (n == 0)
             {
                 fail ("Loop count exceeded without expiring black list");
                 return;
             }
             if (c.disposition() != drop)
             {
                 pass ();
                 break;
             }
         }
     }
void ripple::Resource::Manager_test::testImport (beast::Journal j) inline
Definition at line 169 of file Tests.cpp.
References ripple::Resource::Gossip::Item::address, ripple::Resource::Gossip::Item::balance, ripple::Resource::Logic::importConsumers(), ripple::Resource::Gossip::items, beast::unit_test::suite::pass(), and beast::unit_test::suite::testcase().
Referenced by run().
     {
         testcase ("Import");
         TestLogic logic (j);
         Gossip g;
         Gossip::Item item;
         item.balance = 100;
         item.address = beast::IP::Endpoint (
             beast::IP::AddressV4 (207, 127, 82, 1));
         g.items.push_back (item);
         logic.importConsumers ("g", g);
         pass();
     }
void ripple::Resource::Manager_test::testImports (beast::Journal j) inline
Definition at line 152 of file Tests.cpp.
References createGossip(), beast::String::fromNumber(), ripple::Resource::Logic::importConsumers(), beast::unit_test::suite::pass(), beast::unit_test::suite::testcase(), and beast::String::toStdString().
Referenced by run().
     {
         testcase ("Imports");
         TestLogic logic (j);
         Gossip g[5];
         for (int i = 0; i < 5; ++i)
             createGossip (g[i]);
         for (int i = 0; i < 5; ++i)
             logic.importConsumers (beast::String::fromNumber (i).toStdString(), g[i]);
         pass();
     }
The documentation for this class was generated from the following file:
rippled/src/ripple/resource/impl/Tests.cpp