rippled: rocksdb::SkipList< Key, Comparator >::Node Struct Reference
rocksdb::SkipList< Key, Comparator >::Node Struct Reference
#include <skiplist.h>
Public Member Functions
Node (const Key &k)
Node * Next (int n)
void SetNext (int n, Node *x)
Node * NoBarrier_Next (int n)
void NoBarrier_SetNext (int n, Node *x)
Public Attributes
Key const key
Private Attributes
port::AtomicPointer next_ [1]
Detailed Description
template<typename Key, class Comparator>
struct rocksdb::SkipList< Key, Comparator >::Node
Definition at line 157 of file skiplist.h.
Constructor & Destructor Documentation
template<typename Key, class Comparator> rocksdb::SkipList< Key, Comparator >::Node::Node (const Key & k) inline explicit
Definition at line 158 of file skiplist.h.
 : key(k) { }
Member Function Documentation
template<typename Key, class Comparator> Node* rocksdb::SkipList< Key, Comparator >::Node::Next (int n) inline
Definition at line 164 of file skiplist.h.
Referenced by rocksdb::SkipList< Key, Comparator >::FindGreaterOrEqual(), rocksdb::SkipList< Key, Comparator >::FindLast(), and rocksdb::SkipList< Key, Comparator >::FindLessThan().
                     {
     assert(n >= 0);
     // Use an 'acquire load' so that we observe a fully initialized
     // version of the returned Node.
     return reinterpret_cast<Node*>(next_[n].Acquire_Load());
   }
template<typename Key, class Comparator> Node* rocksdb::SkipList< Key, Comparator >::Node::NoBarrier_Next (int n) inline
Definition at line 178 of file skiplist.h.
{
     assert(n >= 0);
     return reinterpret_cast<Node*>(next_[n].NoBarrier_Load());
   }
template<typename Key, class Comparator> void rocksdb::SkipList< Key, Comparator >::Node::NoBarrier_SetNext (int n, Node * x) inline
Definition at line 182 of file skiplist.h.
Referenced by rocksdb::SkipList< Key, Comparator >::Insert().
{
     assert(n >= 0);
     next_[n].NoBarrier_Store(x);
   }
template<typename Key, class Comparator> void rocksdb::SkipList< Key, Comparator >::Node::SetNext (int n, Node * x) inline
Definition at line 170 of file skiplist.h.
Referenced by rocksdb::SkipList< Key, Comparator >::SkipList().
{
     assert(n >= 0);
     // Use a 'release store' so that anybody who reads through this
     // pointer observes a fully initialized version of the inserted node.
     next_[n].Release_Store(x);
   }
Member Data Documentation
template<typename Key, class Comparator> Key const rocksdb::SkipList< Key, Comparator >::Node::key
Definition at line 160 of file skiplist.h.
Referenced by rocksdb::SkipList< Key, Comparator >::Contains(), rocksdb::SkipList< Key, Comparator >::FindGreaterOrEqual(), rocksdb::SkipList< Key, Comparator >::FindLessThan(), rocksdb::SkipList< Key, Comparator >::Insert(), and rocksdb::SkipList< Key, Comparator >::KeyIsAfterNode().
template<typename Key, class Comparator> port::AtomicPointer rocksdb::SkipList< Key, Comparator >::Node::next_[1] private
Definition at line 189 of file skiplist.h.
The documentation for this struct was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/db/skiplist.h