rippled: ripple::NodeStore::EncodedBlob Struct Reference
ripple::NodeStore::EncodedBlob Struct Reference
#include <EncodedBlob.h>
Public Member Functions
void prepare (NodeObject::Ptr const &object)
void const * getKey () const noexcept
size_t getSize () const noexcept
void const * getData () const noexcept
Private Attributes
void const * m_key
beast::MemoryBlock m_data
size_t m_size
Detailed Description
Utility for producing flattened node objects.
Note
This defines the database format of a NodeObject!
Definition at line 30 of file EncodedBlob.h.
Member Function Documentation
void const* ripple::NodeStore::EncodedBlob::getData () const inline noexcept
Definition at line 36 of file EncodedBlob.h.
References beast::MemoryBlock::getData(), and m_data.
Referenced by ripple::NodeStore::LevelDBBackend::storeBatch(), and ripple::NodeStore::NodeStoreBasic_test::testBlobs().
 { return m_data.getData (); }
void const* ripple::NodeStore::EncodedBlob::getKey () const inline noexcept
Definition at line 34 of file EncodedBlob.h.
References m_key.
Referenced by ripple::NodeStore::LevelDBBackend::storeBatch(), and ripple::NodeStore::NodeStoreBasic_test::testBlobs().
 { return m_key; }
size_t ripple::NodeStore::EncodedBlob::getSize () const inline noexcept
Definition at line 35 of file EncodedBlob.h.
References m_size.
Referenced by ripple::NodeStore::LevelDBBackend::storeBatch(), and ripple::NodeStore::NodeStoreBasic_test::testBlobs().
 { return m_size; }
void ripple::NodeStore::EncodedBlob::prepare (NodeObject::Ptr const & object)
Definition at line 23 of file EncodedBlob.cpp.
References beast::MemoryBlock::ensureSize(), beast::MemoryBlock::getData(), m_data, m_key, m_size, static_bassert, and beast::ByteOrder::swapIfLittleEndian().
Referenced by ripple::NodeStore::LevelDBBackend::storeBatch(), and ripple::NodeStore::NodeStoreBasic_test::testBlobs().
 {
     m_key = object->getHash ().begin ();
     // This is how many bytes we need in the flat data
     m_size = object->getData ().size () + 9;
     m_data.ensureSize (m_size);
     // These sizes must be the same!
     static_bassert (sizeof (std::uint32_t) == sizeof (object->getIndex ()));
     {
         std::uint32_t* buf = static_cast <std::uint32_t*> (m_data.getData ());
         buf [0] = beast::ByteOrder::swapIfLittleEndian (object->getIndex ());
         buf [1] = beast::ByteOrder::swapIfLittleEndian (object->getIndex ());
     }
     {
         unsigned char* buf = static_cast <unsigned char*> (m_data.getData ());
         buf [8] = static_cast <unsigned char> (object->getType ());
         memcpy (&buf [9], object->getData ().data (), object->getData ().size ());
     }
 }
Member Data Documentation
beast::MemoryBlock ripple::NodeStore::EncodedBlob::m_data private
Definition at line 40 of file EncodedBlob.h.
Referenced by getData(), and prepare().
void const* ripple::NodeStore::EncodedBlob::m_key private
Definition at line 39 of file EncodedBlob.h.
Referenced by getKey(), and prepare().
size_t ripple::NodeStore::EncodedBlob::m_size private
Definition at line 41 of file EncodedBlob.h.
Referenced by getSize(), and prepare().
The documentation for this struct was generated from the following files:
rippled/src/ripple_core/nodestore/impl/EncodedBlob.h
rippled/src/ripple_core/nodestore/impl/EncodedBlob.cpp