rippled: beast::ByteOrder Class Reference
beast::ByteOrder Class Reference
#include <ByteOrder.h>
Static Public Member Functions
static std::uint16_t swap (std::uint16_t value)
static std::uint32_t swap (std::uint32_t value)
static std::uint64_t swap (std::uint64_t value)
static std::uint16_t swapIfBigEndian (std::uint16_t value)
static std::uint32_t swapIfBigEndian (std::uint32_t value)
static std::uint64_t swapIfBigEndian (std::uint64_t value)
static std::uint16_t swapIfLittleEndian (std::uint16_t value)
static std::uint32_t swapIfLittleEndian (std::uint32_t value)
static std::uint64_t swapIfLittleEndian (std::uint64_t value)
static std::uint16_t littleEndianShort (const void *bytes)
static std::uint32_t littleEndianInt (const void *bytes)
static std::uint64_t littleEndianInt64 (const void *bytes)
static std::uint16_t bigEndianShort (const void *bytes)
static std::uint32_t bigEndianInt (const void *bytes)
static std::uint64_t bigEndianInt64 (const void *bytes)
static int littleEndian24Bit (const char *bytes)
static int bigEndian24Bit (const char *bytes)
static void littleEndian24BitToChars (int value, char *destBytes)
static void bigEndian24BitToChars (int value, char *destBytes)
static bool isBigEndian ()
Private Member Functions
ByteOrder ()
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
Contains static methods for converting the byte order between different endiannesses.
Definition at line 38 of file ByteOrder.h.
Constructor & Destructor Documentation
beast::ByteOrder::ByteOrder () private
Member Function Documentation
int beast::ByteOrder::bigEndian24Bit (const char * bytes) inline static
Converts 3 big-endian bytes into a signed 24-bit value (which is sign-extended to 32 bits).
Definition at line 188 of file ByteOrder.h.
 { return (((int) bytes[0]) << 16) | (((int) (std::uint8_t) bytes[1]) << 8) | ((int) (std::uint8_t) bytes[2]); }
void beast::ByteOrder::bigEndian24BitToChars (int value, char * destBytes) inline static
Copies a 24-bit number to 3 big-endian bytes.
Definition at line 190 of file ByteOrder.h.
 { destBytes[0] = (char)((value >> 16) & 0xff); destBytes[1] = (char)((value >> 8) & 0xff); destBytes[2] = (char)(value & 0xff); }
std::uint32_t beast::ByteOrder::bigEndianInt (const void * bytes) inline static
Turns 4 bytes into a big-endian integer.
Definition at line 182 of file ByteOrder.h.
Referenced by beast::InputStream::readInt32BigEndian(), and beast::InputStream::readIntBigEndian().
 { return *static_cast <const std::uint32_t*> (bytes); }
std::uint64_t beast::ByteOrder::bigEndianInt64 (const void * bytes) inline static
Turns 4 bytes into a big-endian integer.
Definition at line 183 of file ByteOrder.h.
 { return *static_cast <const std::uint64_t*> (bytes); }
std::uint16_t beast::ByteOrder::bigEndianShort (const void * bytes) inline static
Turns 2 bytes into a big-endian integer.
Definition at line 181 of file ByteOrder.h.
Referenced by beast::InputStream::readShortBigEndian().
 { return *static_cast <const std::uint16_t*> (bytes); }
bool beast::ByteOrder::isBigEndian () inline static
Returns true if the current CPU is big-endian.
Definition at line 184 of file ByteOrder.h.
 { return true; }
int beast::ByteOrder::littleEndian24Bit (const char * bytes) inline static
Converts 3 little-endian bytes into a signed 24-bit value (which is sign-extended to 32 bits).
Definition at line 187 of file ByteOrder.h.
 { return (((int) bytes[2]) << 16) | (((int) (std::uint8_t) bytes[1]) << 8) | ((int) (std::uint8_t) bytes[0]); }
void beast::ByteOrder::littleEndian24BitToChars (int value, char * destBytes) inline static
Copies a 24-bit number to 3 little-endian bytes.
Definition at line 189 of file ByteOrder.h.
 { destBytes[0] = (char)(value & 0xff); destBytes[1] = (char)((value >> 8) & 0xff); destBytes[2] = (char)((value >> 16) & 0xff); }
std::uint32_t beast::ByteOrder::littleEndianInt (const void * bytes) inline static
Turns 4 bytes into a little-endian integer.
Definition at line 179 of file ByteOrder.h.
References swap().
Referenced by beast::InputStream::readCompressedInt(), beast::InputStream::readInt(), and beast::InputStream::readInt32().
 { return swap (*static_cast <const std::uint32_t*> (bytes)); }
static std::uint64_t beast::ByteOrder::littleEndianInt64 (const void * bytes) static
Turns 4 bytes into a little-endian integer.
std::uint16_t beast::ByteOrder::littleEndianShort (const void * bytes) inline static
Turns 2 bytes into a little-endian integer.
Definition at line 180 of file ByteOrder.h.
References swap().
Referenced by beast::InputStream::readShort().
 { return swap (*static_cast <const std::uint16_t*> (bytes)); }
std::uint16_t beast::ByteOrder::swap (std::uint16_t value) inline static
Swaps the upper and lower bytes of a 16-bit integer.
Definition at line 115 of file ByteOrder.h.
Referenced by littleEndianInt(), littleEndianShort(), beast::detail::SwapBytes< IntegralType >::operator()(), beast::detail::SwapBytes< std::int16_t >::operator()(), beast::detail::SwapBytes< std::int32_t >::operator()(), beast::detail::SwapBytes< std::int64_t >::operator()(), beast::Atomic_test::run(), swap(), and swapIfBigEndian().
 {
    #if BEAST_USE_INTRINSICSxxx // agh - the MS compiler has an internal error when you try to use this intrinsic!
     return static_cast <std::uint16_t> (_byteswap_ushort (n));
    #else
     return static_cast <std::uint16_t> ((n << 8) | (n >> 8));
    #endif
 }
std::uint32_t beast::ByteOrder::swap (std::uint32_t value) inline static
Reverses the order of the 4 bytes in a 32-bit integer.
Definition at line 124 of file ByteOrder.h.
 {
    #if BEAST_MAC || BEAST_IOS
     return OSSwapInt32 (n);
    #elif BEAST_GCC && BEAST_INTEL && ! BEAST_NO_INLINE_ASM
     asm("bswap %%eax" : "=a"(n) : "a"(n));
     return n;
    #elif BEAST_USE_INTRINSICS
     return _byteswap_ulong (n);
    #elif BEAST_MSVC && ! BEAST_NO_INLINE_ASM
     __asm {
         mov eax, n
         bswap eax
         mov n, eax
     }
     return n;
    #elif BEAST_ANDROID
     return bswap_32 (n);
    #else
     return (n << 24) | (n >> 24) | ((n & 0xff00) << 8) | ((n & 0xff0000) >> 8);
    #endif
 }
std::uint64_t beast::ByteOrder::swap (std::uint64_t value) inline static
Reverses the order of the 8 bytes in a 64-bit integer.
Definition at line 147 of file ByteOrder.h.
References swap().
 {
    #if BEAST_MAC || BEAST_IOS
     return OSSwapInt64 (value);
    #elif BEAST_USE_INTRINSICS
     return _byteswap_uint64 (value);
    #else
     return (((std::int64_t) swap ((std::uint32_t) value)) << 32) | swap ((std::uint32_t) (value >> 32));
    #endif
 }
std::uint16_t beast::ByteOrder::swapIfBigEndian (std::uint16_t value) inline static
Swaps the byte order of a 16-bit int if the CPU is big-endian
Definition at line 173 of file ByteOrder.h.
References swap().
Referenced by beast::String::createStringFromData(), beast::InputStream::readInt64(), beast::OutputStream::writeInt(), beast::OutputStream::writeInt32(), beast::OutputStream::writeInt64(), and beast::OutputStream::writeShort().
 { return swap (v); }
std::uint32_t beast::ByteOrder::swapIfBigEndian (std::uint32_t value) inline static
Swaps the byte order of a 32-bit int if the CPU is big-endian
Definition at line 174 of file ByteOrder.h.
References swap().
 { return swap (v); }
std::uint64_t beast::ByteOrder::swapIfBigEndian (std::uint64_t value) inline static
Swaps the byte order of a 64-bit int if the CPU is big-endian
Definition at line 175 of file ByteOrder.h.
References swap().
 { return swap (v); }
std::uint16_t beast::ByteOrder::swapIfLittleEndian (std::uint16_t value) inline static
Swaps the byte order of a 16-bit int if the CPU is little-endian
Definition at line 176 of file ByteOrder.h.
Referenced by beast::String::createStringFromData(), ripple::NodeStore::DecodedBlob::DecodedBlob(), ripple::NodeStore::EncodedBlob::prepare(), beast::InputStream::readInt64BigEndian(), beast::OutputStream::writeInt32BigEndian(), beast::OutputStream::writeInt64BigEndian(), beast::OutputStream::writeIntBigEndian(), and beast::OutputStream::writeShortBigEndian().
 { return v; }
std::uint32_t beast::ByteOrder::swapIfLittleEndian (std::uint32_t value) inline static
Swaps the byte order of a 32-bit int if the CPU is little-endian
Definition at line 177 of file ByteOrder.h.
 { return v; }
std::uint64_t beast::ByteOrder::swapIfLittleEndian (std::uint64_t value) inline static
Swaps the byte order of a 64-bit int if the CPU is little-endian
Definition at line 178 of file ByteOrder.h.
 { return v; }
The documentation for this class was generated from the following file:
rippled/src/beast/beast/ByteOrder.h