rippled: beast::ServiceQueue_timing_test::Producer< ServiceType > Struct Template Reference
beast::ServiceQueue_timing_test::Producer< ServiceType > Struct Template Reference
Public Member Functions
Producer (int id, std::int64_t seedValue, ServiceType &service)
~Producer ()
void run ()
Public Member Functions inherited from beast::Thread
Thread (const String &threadName)
virtual ~Thread ()
void startThread ()
void startThread (int priority)
bool stopThread (int timeOutMilliseconds=-1)
void stopThreadAsync ()
bool isThreadRunning () const
void signalThreadShouldExit ()
bool threadShouldExit () const
bool waitForThreadToExit (int timeOutMilliseconds=-1) const
bool setPriority (int priority)
void setAffinityMask (std::uint32_t affinityMask)
bool wait (int timeOutMilliseconds=-1) const
void notify () const
ThreadID getThreadId () const noexcept
const String & getThreadName () const
Public Attributes
ServiceType & m_service
Random m_random
String m_string
Additional Inherited Members
Public Types inherited from beast::Thread
typedef void * ThreadID
Static Public Member Functions inherited from beast::Thread
static bool setCurrentThreadPriority (int priority)
static void setCurrentThreadAffinityMask (std::uint32_t affinityMask)
static void sleep (int milliseconds)
static void yield ()
static ThreadID getCurrentThreadId ()
static Thread * getCurrentThread ()
static void setCurrentThreadName (const String &newThreadName)
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
template<typename ServiceType>
struct beast::ServiceQueue_timing_test::Producer< ServiceType >
Definition at line 100 of file ServiceQueue.cpp.
Constructor & Destructor Documentation
template<typename ServiceType > beast::ServiceQueue_timing_test::Producer< ServiceType >::Producer (int id, std::int64_t seedValue, ServiceType & service) inline
Definition at line 106 of file ServiceQueue.cpp.
             : Thread ("P#" + String::fromNumber (id))
             , m_service (service)
             , m_random (seedValue)
             { }
template<typename ServiceType > beast::ServiceQueue_timing_test::Producer< ServiceType >::~Producer () inline
Definition at line 112 of file ServiceQueue.cpp.
References beast::Thread::stopThread().
             { stopThread(); }
Member Function Documentation
template<typename ServiceType > void beast::ServiceQueue_timing_test::Producer< ServiceType >::run () inline virtual
Must be implemented to perform the thread's actual code.
Remember that the thread must regularly check the threadShouldExit() method whilst running, and if this returns true it should return from the run() method as soon as possible to avoid being forcibly killed.
See Also
threadShouldExit, startThread
Implements beast::Thread.
Definition at line 115 of file ServiceQueue.cpp.
References beast::ServiceQueue_timing_test::callsPerThread, beast::String::empty, beast::String::fromNumber(), beast::String::length(), beast::ServiceQueue_timing_test::Producer< ServiceType >::m_random, beast::ServiceQueue_timing_test::Producer< ServiceType >::m_service, beast::ServiceQueue_timing_test::Producer< ServiceType >::m_string, and beast::Random::nextInt().
         {
             for (std::size_t i = 0; i < callsPerThread; ++i)
             {
                 String const s (String::fromNumber (m_random.nextInt()));
                 m_string += s;
                 if (m_string.length() > 100)
                     m_string = String::empty;
                 m_service.dispatch (std::bind (&Consumer<ServiceType>::handler));
             }
         }
Member Data Documentation
template<typename ServiceType > Random beast::ServiceQueue_timing_test::Producer< ServiceType >::m_random
Definition at line 103 of file ServiceQueue.cpp.
Referenced by beast::ServiceQueue_timing_test::Producer< ServiceType >::run().
template<typename ServiceType > ServiceType& beast::ServiceQueue_timing_test::Producer< ServiceType >::m_service
Definition at line 102 of file ServiceQueue.cpp.
Referenced by beast::ServiceQueue_timing_test::Producer< ServiceType >::run().
template<typename ServiceType > String beast::ServiceQueue_timing_test::Producer< ServiceType >::m_string
Definition at line 104 of file ServiceQueue.cpp.
Referenced by beast::ServiceQueue_timing_test::Producer< ServiceType >::run().
The documentation for this struct was generated from the following file:
rippled/src/beast/beast/threads/tests/ServiceQueue.cpp