rippled: beast.env.ReadEnvFile Namespace Reference
beast.env.ReadEnvFile Namespace Reference
Functions
def read_env_file
Variables
tuple ENV_LINE_MATCH
Function Documentation
def beast.env.ReadEnvFile.read_env_file (data, print = print)
Definition at line 12 of file ReadEnvFile.py.
References beast::unit_test.print(), and ripple::Resource.warn.
Referenced by beast.env.AddUserEnv.add_user_env(), beast.env.ReadEnvFile_test.test_ReadEnvFile.test_read_env(), beast.env.ReadEnvFile_test.test_ReadEnvFile.test_read_env_error(), and beast.env.ReadEnvFile_test.test_ReadEnvFile.test_read_json().
 def read_env_file(data, print=print):
     try:
         return json.loads(data)
     except ValueError:
         pass
     bad_lines = []
     results = {}
     for number, raw_line in enumerate(data.splitlines()):
         line = String.remove_comment(raw_line).strip()
         if line:
             match = ENV_LINE_MATCH.match(line)
             if match:
                 name, value = match.groups()
                 results[name.strip()] = String.remove_quotes(value.strip())
             else:
                 bad_lines.append([number, raw_line])
     if bad_lines:
          warn("Didn't understand the following environment file lines:", print)
          for number, line in bad_lines:
              print('%d. >>> %s' % (number + 1, line))
     return results
Variable Documentation
tuple beast.env.ReadEnvFile.ENV_LINE_MATCH
Initial value:
 = re.compile(r'(?: export \s+)? \s* ([^=\s]*) \s* = (.*)',
                             re.VERBOSE)
Definition at line 9 of file ReadEnvFile.py.