rippled: beast::DirectoryIterator::NativeIterator::Pimpl Class Reference
beast::DirectoryIterator::NativeIterator::Pimpl Class Reference
Public Member Functions
Pimpl (const File &directory, const String &wildCard_)
~Pimpl ()
bool next (String &filenameFound, bool *const isDir, bool *const isHidden, std::int64_t *const fileSize, Time *const modTime, Time *const creationTime, bool *const isReadOnly)
Pimpl (const File &directory, const String &wildCard_)
~Pimpl ()
bool next (String &filenameFound, bool *const isDir, bool *const isHidden, std::int64_t *const fileSize, Time *const modTime, Time *const creationTime, bool *const isReadOnly)
Pimpl (const File &directory, const String &wildCard)
~Pimpl ()
bool next (String &filenameFound, bool *const isDir, bool *const isHidden, std::int64_t *const fileSize, Time *const modTime, Time *const creationTime, bool *const isReadOnly)
Private Attributes
String parentDir
String wildCard
DIR * dir
const String directoryWithWildCard
HANDLE handle
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
Definition at line 247 of file bsd_Files.cpp.
Constructor & Destructor Documentation
beast::DirectoryIterator::NativeIterator::Pimpl::Pimpl (const File & directory, const String & wildCard_) inline
Definition at line 250 of file bsd_Files.cpp.
         : parentDir (File::addTrailingSeparator (directory.getFullPathName())),
           wildCard (wildCard_),
           dir (opendir (directory.getFullPathName().toUTF8()))
     {
     }
beast::DirectoryIterator::NativeIterator::Pimpl::~Pimpl () inline
Definition at line 257 of file bsd_Files.cpp.
References dir.
     {
         if (dir != nullptr)
             closedir (dir);
     }
beast::DirectoryIterator::NativeIterator::Pimpl::Pimpl (const File & directory, const String & wildCard_) inline
Definition at line 250 of file linux_Files.cpp.
         : parentDir (File::addTrailingSeparator (directory.getFullPathName())),
           wildCard (wildCard_),
           dir (opendir (directory.getFullPathName().toUTF8()))
     {
     }
beast::DirectoryIterator::NativeIterator::Pimpl::~Pimpl () inline
Definition at line 257 of file linux_Files.cpp.
References dir.
     {
         if (dir != nullptr)
             closedir (dir);
     }
beast::DirectoryIterator::NativeIterator::Pimpl::Pimpl (const File & directory, const String & wildCard) inline
Definition at line 741 of file win32_Files.cpp.
         : directoryWithWildCard (File::addTrailingSeparator (directory.getFullPathName()) + wildCard),
           handle (INVALID_HANDLE_VALUE)
     {
     }
beast::DirectoryIterator::NativeIterator::Pimpl::~Pimpl () inline
Definition at line 747 of file win32_Files.cpp.
     {
         if (handle != INVALID_HANDLE_VALUE)
             FindClose (handle);
     }
Member Function Documentation
bool beast::DirectoryIterator::NativeIterator::Pimpl::next (String & filenameFound, bool *const isDir, bool *const isHidden, std::int64_t *const fileSize, Time *const modTime, Time *const creationTime, bool *const isReadOnly) inline
Definition at line 263 of file bsd_Files.cpp.
References dir, parentDir, beast::String::startsWithChar(), beast::String::toUTF8(), and wildCard.
     {
         if (dir != nullptr)
         {
             const char* wildcardUTF8 = nullptr;
             for (;;)
             {
                 struct dirent* const de = readdir (dir);
                 if (de == nullptr)
                     break;
                 if (wildcardUTF8 == nullptr)
                     wildcardUTF8 = wildCard.toUTF8();
                 if (fnmatch (wildcardUTF8, de->d_name, FNM_CASEFOLD) == 0)
                 {
                     filenameFound = CharPointer_UTF8 (de->d_name);
                     updateStatInfoForFile (parentDir + filenameFound, isDir, fileSize, modTime, creationTime, isReadOnly);
                     if (isHidden != nullptr)
                         *isHidden = filenameFound.startsWithChar ('.');
                     return true;
                 }
             }
         }
         return false;
     }
bool beast::DirectoryIterator::NativeIterator::Pimpl::next (String & filenameFound, bool *const isDir, bool *const isHidden, std::int64_t *const fileSize, Time *const modTime, Time *const creationTime, bool *const isReadOnly) inline
Definition at line 263 of file linux_Files.cpp.
References dir, parentDir, beast::String::startsWithChar(), beast::String::toUTF8(), and wildCard.
     {
         if (dir != nullptr)
         {
             const char* wildcardUTF8 = nullptr;
             for (;;)
             {
                 struct dirent* const de = readdir (dir);
                 if (de == nullptr)
                     break;
                 if (wildcardUTF8 == nullptr)
                     wildcardUTF8 = wildCard.toUTF8();
                 if (fnmatch (wildcardUTF8, de->d_name, FNM_CASEFOLD) == 0)
                 {
                     filenameFound = CharPointer_UTF8 (de->d_name);
                     updateStatInfoForFile (parentDir + filenameFound, isDir, fileSize, modTime, creationTime, isReadOnly);
                     if (isHidden != nullptr)
                         *isHidden = filenameFound.startsWithChar ('.');
                     return true;
                 }
             }
         }
         return false;
     }
bool beast::DirectoryIterator::NativeIterator::Pimpl::next (String & filenameFound, bool *const isDir, bool *const isHidden, std::int64_t *const fileSize, Time *const modTime, Time *const creationTime, bool *const isReadOnly) inline
Definition at line 753 of file win32_Files.cpp.
References beast::WindowsFileHelpers::fileTimeToTime().
     {
         using namespace WindowsFileHelpers;
         WIN32_FIND_DATA findData;
         if (handle == INVALID_HANDLE_VALUE)
         {
             handle = FindFirstFile (directoryWithWildCard.toWideCharPointer(), &findData);
             if (handle == INVALID_HANDLE_VALUE)
                 return false;
         }
         else
         {
             if (FindNextFile (handle, &findData) == 0)
                 return false;
         }
         filenameFound = findData.cFileName;
         if (isDir != nullptr)         *isDir        = ((findData.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) != 0);
         if (isHidden != nullptr)      *isHidden     = ((findData.dwFileAttributes & FILE_ATTRIBUTE_HIDDEN) != 0);
         if (isReadOnly != nullptr)    *isReadOnly   = ((findData.dwFileAttributes & FILE_ATTRIBUTE_READONLY) != 0);
         if (fileSize != nullptr)      *fileSize     = findData.nFileSizeLow + (((std::int64_t) findData.nFileSizeHigh) << 32);
         if (modTime != nullptr)       *modTime      = Time (fileTimeToTime (&findData.ftLastWriteTime));
         if (creationTime != nullptr)  *creationTime = Time (fileTimeToTime (&findData.ftCreationTime));
         return true;
     }
Member Data Documentation
DIR * beast::DirectoryIterator::NativeIterator::Pimpl::dir private
Definition at line 300 of file bsd_Files.cpp.
Referenced by next(), and ~Pimpl().
const String beast::DirectoryIterator::NativeIterator::Pimpl::directoryWithWildCard private
Definition at line 786 of file win32_Files.cpp.
HANDLE beast::DirectoryIterator::NativeIterator::Pimpl::handle private
Definition at line 787 of file win32_Files.cpp.
String beast::DirectoryIterator::NativeIterator::Pimpl::parentDir private
Definition at line 299 of file bsd_Files.cpp.
Referenced by next().
String beast::DirectoryIterator::NativeIterator::Pimpl::wildCard private
Definition at line 299 of file bsd_Files.cpp.
Referenced by next().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_core/native/bsd_Files.cpp
rippled/src/beast/modules/beast_core/native/linux_Files.cpp
rippled/src/beast/modules/beast_core/native/win32_Files.cpp