rippled: ripple::InfoSub Class Reference
ripple::InfoSub Class Reference abstract
#include <InfoSub.h>
Classes
class Source
Public Types
typedef boost::shared_ptr
< InfoSub > pointer
typedef boost::weak_ptr< InfoSub > wptr
typedef const
boost::shared_ptr< InfoSub > & ref
typedef Resource::Consumer Consumer
Public Member Functions
InfoSub (Source &source, Consumer consumer)
virtual ~InfoSub ()
Consumer & getConsumer ()
virtual void send (const Json::Value &jvObj, bool broadcast)=0
virtual void send (const Json::Value &jvObj, const std::string &sObj, bool broadcast)
std::uint64_t getSeq ()
void onSendEmpty ()
void insertSubAccountInfo (RippleAddress addr, std::uint32_t uLedgerIndex)
void clearPathRequest ()
void setPathRequest (const boost::shared_ptr< PathRequest > &req)
boost::shared_ptr< PathRequest >
const & getPathRequest ()
Public Member Functions inherited from ripple::CountedObject< InfoSub >
CountedObject ()
CountedObject (CountedObject const &)
~CountedObject ()
Static Public Member Functions
static char const * getCountedObjectName ()
Protected Types
typedef RippleMutex LockType
typedef std::lock_guard< LockType > ScopedLockType
Protected Attributes
LockType mLock
Private Attributes
Consumer m_consumer
Source & m_source
boost::unordered_set
< RippleAddress > mSubAccountInfo
boost::unordered_set
< RippleAddress > mSubAccountTransaction
boost::shared_ptr< PathRequest > mPathRequest
std::uint64_t mSeq
Detailed Description
Manages a client's subscription to data feeds.
Definition at line 32 of file InfoSub.h.
Member Typedef Documentation
typedef Resource::Consumer ripple::InfoSub::Consumer
Definition at line 45 of file InfoSub.h.
typedef RippleMutex ripple::InfoSub::LockType protected
Definition at line 126 of file InfoSub.h.
typedef boost::shared_ptr<InfoSub> ripple::InfoSub::pointer
Definition at line 38 of file InfoSub.h.
typedef const boost::shared_ptr<InfoSub>& ripple::InfoSub::ref
Definition at line 43 of file InfoSub.h.
typedef std::lock_guard<LockType> ripple::InfoSub::ScopedLockType protected
Definition at line 127 of file InfoSub.h.
typedef boost::weak_ptr<InfoSub> ripple::InfoSub::wptr
Definition at line 41 of file InfoSub.h.
Constructor & Destructor Documentation
ripple::InfoSub::InfoSub (Source & source, Consumer consumer)
Definition at line 42 of file InfoSub.cpp.
References mSeq.
     : m_consumer (consumer)
     , m_source (source)
 {
     static beast::Atomic <int> s_seq_id;
     mSeq = ++s_seq_id;
 }
ripple::InfoSub::~InfoSub () virtual
Definition at line 50 of file InfoSub.cpp.
References m_source, mSeq, mSubAccountInfo, ripple::InfoSub::Source::unsubAccount(), ripple::InfoSub::Source::unsubLedger(), ripple::InfoSub::Source::unsubRTTransactions(), ripple::InfoSub::Source::unsubServer(), and ripple::InfoSub::Source::unsubTransactions().
 {
     m_source.unsubTransactions (mSeq);
     m_source.unsubRTTransactions (mSeq);
     m_source.unsubLedger (mSeq);
     m_source.unsubServer (mSeq);
     m_source.unsubAccount (mSeq, mSubAccountInfo, true);
     m_source.unsubAccount (mSeq, mSubAccountInfo, false);
 }
Member Function Documentation
void ripple::InfoSub::clearPathRequest ()
Definition at line 86 of file InfoSub.cpp.
References mPathRequest.
 {
     mPathRequest.reset ();
 }
Resource::Consumer & ripple::InfoSub::getConsumer ()
Definition at line 60 of file InfoSub.cpp.
References m_consumer.
Referenced by ripple::WSConnection::invokeCommand().
 {
     return m_consumer;
 }
static char const* ripple::InfoSub::getCountedObjectName () inline static
Definition at line 36 of file InfoSub.h.
 { return "InfoSub"; }
const boost::shared_ptr< PathRequest > & ripple::InfoSub::getPathRequest ()
Definition at line 96 of file InfoSub.cpp.
References mPathRequest.
 {
     return mPathRequest;
 }
std::uint64_t ripple::InfoSub::getSeq ()
Definition at line 70 of file InfoSub.cpp.
References mSeq.
 {
     return mSeq;
 }
void ripple::InfoSub::insertSubAccountInfo (RippleAddress addr, std::uint32_t uLedgerIndex)
Definition at line 79 of file InfoSub.cpp.
References mLock, and mSubAccountInfo.
 {
     ScopedLockType sl (mLock);
     mSubAccountInfo.insert (addr);
 }
void ripple::InfoSub::onSendEmpty ()
Definition at line 75 of file InfoSub.cpp.
 {
 }
virtual void ripple::InfoSub::send (const Json::Value & jvObj, bool broadcast) pure virtual
Implemented in ripple::WSConnectionType< endpoint_type >, and ripple::RPCSubImp.
Referenced by send().
void ripple::InfoSub::send (const Json::Value & jvObj, const std::string & sObj, bool broadcast) virtual
Reimplemented in ripple::WSConnectionType< endpoint_type >.
Definition at line 65 of file InfoSub.cpp.
References send().
 {
     send (jvObj, broadcast);
 }
void ripple::InfoSub::setPathRequest (const boost::shared_ptr< PathRequest > & req)
Definition at line 91 of file InfoSub.cpp.
References mPathRequest.
 {
     mPathRequest = req;
 }
Member Data Documentation
Consumer ripple::InfoSub::m_consumer private
Definition at line 131 of file InfoSub.h.
Referenced by getConsumer().
Source& ripple::InfoSub::m_source private
Definition at line 132 of file InfoSub.h.
Referenced by ~InfoSub().
LockType ripple::InfoSub::mLock protected
Definition at line 128 of file InfoSub.h.
Referenced by insertSubAccountInfo().
boost::shared_ptr<PathRequest> ripple::InfoSub::mPathRequest private
Definition at line 135 of file InfoSub.h.
Referenced by clearPathRequest(), getPathRequest(), and setPathRequest().
std::uint64_t ripple::InfoSub::mSeq private
Definition at line 137 of file InfoSub.h.
Referenced by getSeq(), InfoSub(), and ~InfoSub().
boost::unordered_set<RippleAddress> ripple::InfoSub::mSubAccountInfo private
Definition at line 133 of file InfoSub.h.
Referenced by insertSubAccountInfo(), and ~InfoSub().
boost::unordered_set<RippleAddress> ripple::InfoSub::mSubAccountTransaction private
Definition at line 134 of file InfoSub.h.
The documentation for this class was generated from the following files:
rippled/src/ripple_net/rpc/InfoSub.h
rippled/src/ripple_net/rpc/InfoSub.cpp