rippled: ripple::SerializedObject_test Class Reference
ripple::SerializedObject_test Class Reference
Public Member Functions
void run ()
bool parseJSONString (const std::string &json, Json::Value &to)
void testParseJSONArrayWithInvalidChildrenObjects ()
void testParseJSONArray ()
void testSerialization ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 1258 of file SerializedObject.cpp.
Member Function Documentation
bool ripple::SerializedObject_test::parseJSONString (const std::string & json, Json::Value & to) inline
Definition at line 1268 of file SerializedObject.cpp.
References Json::Value::isNull(), Json::Value::isObject(), and Json::Reader::parse().
Referenced by testParseJSONArray(), and testParseJSONArrayWithInvalidChildrenObjects().
     {
         Json::Reader reader;
         return (reader.parse(json, to) &&
                !to.isNull() &&
                 to.isObject());
     }
void ripple::SerializedObject_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 1261 of file SerializedObject.cpp.
References testParseJSONArray(), testParseJSONArrayWithInvalidChildrenObjects(), and testSerialization().
     {
         testSerialization();
         testParseJSONArray();
         testParseJSONArrayWithInvalidChildrenObjects();
     }
void ripple::SerializedObject_test::testParseJSONArray () inline
Definition at line 1314 of file SerializedObject.cpp.
References beast::unit_test::suite::expect(), beast::unit_test::suite::fail(), ripple::STParsedJSON::object, parseJSONString(), beast::unit_test::suite::testcase(), and Json::FastWriter::write().
Referenced by run().
     {
         testcase ("parse json array");
         std::string const json ("{\"Template\":[{\"ModifiedNode\":{\"Sequence\":1}}]}\n");
         Json::Value jsonObject;
         bool parsedOK (parseJSONString(json, jsonObject));
         if (parsedOK)
         {
             STParsedJSON parsed ("test", jsonObject);
             Json::FastWriter writer;
             std::string const& serialized (
                 writer.write (parsed.object->getJson(0)));
             expect (serialized == json, serialized + " should equal: " + json);
         }
         else
         {
             fail ("Couldn't parse json: " + json);
         }
     }
void ripple::SerializedObject_test::testParseJSONArrayWithInvalidChildrenObjects () inline
Definition at line 1276 of file SerializedObject.cpp.
References beast::unit_test::suite::expect(), ripple::STParsedJSON::object, parseJSONString(), beast::unit_test::suite::testcase(), and beast::unit_test::suite::unexpected().
Referenced by run().
     {
         testcase ("parse json array invalid children");
         try
         {
             /*
             STArray/STObject constructs don't really map perfectly to json
             arrays/objects.
             STObject is an associative container, mapping fields to value, but
             an STObject may also have a Field as it's name, stored outside the
             associative structure. The name is important, so to maintain
             fidelity, it will take TWO json objects to represent them.
             */
             std::string faulty ("{\"Template\":[{"
                                     "\"ModifiedNode\":{\"Sequence\":1}, "
                                     "\"DeletedNode\":{\"Sequence\":1}"
                                 "}]}");
             std::unique_ptr<STObject> so;
             Json::Value faultyJson;
             bool parsedOK (parseJSONString(faulty, faultyJson));
             unexpected(!parsedOK, "failed to parse");
             STParsedJSON parsed ("test", faultyJson);
             expect (parsed.object.get() == nullptr,
                 "It should have thrown. "
                   "Immediate children of STArray encoded as json must "
                   "have one key only.");
         }
         catch(std::runtime_error& e)
         {
             std::string what(e.what());
             unexpected (what.find("First level children of `Template`") != 0);
         }
     }
void ripple::SerializedObject_test::testSerialization () inline
Definition at line 1335 of file SerializedObject.cpp.
References ripple::STObject::add(), beast::unit_test::suite::fail(), ripple::STObject::getFieldH256(), ripple::STObject::getFieldVL(), ripple::STObject::getFlags(), ripple::STObject::getJson(), ripple::STObject::getSerializer(), ripple::STObject::isFieldPresent(), ripple::SField::isUseful(), ripple::lsINFO, ripple::STObject::makeFieldAbsent(), ripple::STObject::makeFieldPresent(), beast::unit_test::suite::pass(), ripple::SOTemplate::push_back(), ripple::STObject::setFieldVL(), ripple::sfGeneric, ripple::SOE_OPTIONAL, ripple::SOE_REQUIRED, beast::unit_test::suite::testcase(), beast::unit_test::suite::unexpected(), and WriteLog.
Referenced by run().
     {
         testcase ("serialization");
         unexpected (sfGeneric.isUseful (), "sfGeneric must not be useful");
         SField sfTestVL (STI_VL, 255, "TestVL");
         SField sfTestH256 (STI_HASH256, 255, "TestH256");
         SField sfTestU32 (STI_UINT32, 255, "TestU32");
         SField sfTestObject (STI_OBJECT, 255, "TestObject");
         SOTemplate elements;
         elements.push_back (SOElement (sfFlags, SOE_REQUIRED));
         elements.push_back (SOElement (sfTestVL, SOE_REQUIRED));
         elements.push_back (SOElement (sfTestH256, SOE_OPTIONAL));
         elements.push_back (SOElement (sfTestU32, SOE_REQUIRED));
         STObject object1 (elements, sfTestObject);
         STObject object2 (object1);
         unexpected (object1.getSerializer () != object2.getSerializer (), "STObject error 1");
         unexpected (object1.isFieldPresent (sfTestH256) || !object1.isFieldPresent (sfTestVL),
             "STObject error");
         object1.makeFieldPresent (sfTestH256);
         unexpected (!object1.isFieldPresent (sfTestH256), "STObject Error 2");
         unexpected (object1.getFieldH256 (sfTestH256) != uint256 (), "STObject error 3");
         if (object1.getSerializer () == object2.getSerializer ())
         {
             WriteLog (lsINFO, STObject) << "O1: " << object1.getJson (0);
             WriteLog (lsINFO, STObject) << "O2: " << object2.getJson (0);
             fail ("STObject error 4");
         }
         else
         {
             pass ();
         }
         object1.makeFieldAbsent (sfTestH256);
         unexpected (object1.isFieldPresent (sfTestH256), "STObject error 5");
         unexpected (object1.getFlags () != 0, "STObject error 6");
         unexpected (object1.getSerializer () != object2.getSerializer (), "STObject error 7");
         STObject copy (object1);
         unexpected (object1.isFieldPresent (sfTestH256), "STObject error 8");
         unexpected (copy.isFieldPresent (sfTestH256), "STObject error 9");
         unexpected (object1.getSerializer () != copy.getSerializer (), "STObject error 10");
         copy.setFieldU32 (sfTestU32, 1);
         unexpected (object1.getSerializer () == copy.getSerializer (), "STObject error 11");
         for (int i = 0; i < 1000; i++)
         {
             Blob j (i, 2);
             object1.setFieldVL (sfTestVL, j);
             Serializer s;
             object1.add (s);
             SerializerIterator it (s);
             STObject object3 (elements, it, sfTestObject);
             unexpected (object1.getFieldVL (sfTestVL) != j, "STObject error");
             unexpected (object3.getFieldVL (sfTestVL) != j, "STObject error");
         }
     }
The documentation for this class was generated from the following file:
rippled/src/ripple_data/protocol/SerializedObject.cpp