rippled: ripple::STVector256 Class Reference
ripple::STVector256 Class Reference
#include <SerializedTypes.h>
Public Member Functions
STVector256 ()
STVector256 (SField::ref n)
STVector256 (SField::ref n, const std::vector< uint256 > &v)
STVector256 (const std::vector< uint256 > &vector)
SerializedTypeID getSType () const
void add (Serializer &s) const
const std::vector< uint256 > & peekValue () const
std::vector< uint256 > & peekValue ()
virtual bool isEquivalent (const SerializedType &t) const
virtual bool isDefault () const
std::vector< uint256 > getValue () const
int size () const
bool isEmpty () const
uint256 const & at (int i) const
uint256 & at (int i)
void setValue (const STVector256 &v)
void setValue (const std::vector< uint256 > &v)
void addValue (uint256 const &v)
bool hasValue (uint256 const &v) const
void sort ()
Json::Value getJson (int) const
std::vector< uint256 >
::const_iterator begin () const
std::vector< uint256 >
::const_iterator end () const
Public Member Functions inherited from ripple::SerializedType
SerializedType ()
SerializedType (SField::ref n)
virtual ~SerializedType ()
void setFName (SField::ref n)
SField::ref getFName () const
std::string getName () const
std::unique_ptr< SerializedType > clone () const
virtual std::string getFullText () const
virtual std::string getText () const
void addFieldID (Serializer &s) const
SerializedType & operator= (const SerializedType &t)
bool operator== (const SerializedType &t) const
bool operator!= (const SerializedType &t) const
template<class D >
D & downcast ()
template<class D >
D const & downcast () const
Static Public Member Functions
static std::unique_ptr
< SerializedType > deserialize (SerializerIterator &sit, SField::ref name)
Static Public Member Functions inherited from ripple::SerializedType
static std::unique_ptr
< SerializedType > deserialize (SField::ref name)
Private Member Functions
STVector256 * duplicate () const
Static Private Member Functions
static STVector256 * construct (SerializerIterator &, SField::ref)
Private Attributes
std::vector< uint256 > mValue
Additional Inherited Members
Protected Attributes inherited from ripple::SerializedType
SField::ptr fName
Detailed Description
Definition at line 1535 of file SerializedTypes.h.
Constructor & Destructor Documentation
ripple::STVector256::STVector256 () inline
Definition at line 1538 of file SerializedTypes.h.
     {
         ;
     }
ripple::STVector256::STVector256 (SField::ref n) inline
Definition at line 1542 of file SerializedTypes.h.
                               : SerializedType (n)
     {
         ;
     }
ripple::STVector256::STVector256 (SField::ref n, const std::vector< uint256 > & v) inline
Definition at line 1546 of file SerializedTypes.h.
                                                            : SerializedType (n), mValue (v)
     {
         ;
     }
ripple::STVector256::STVector256 (const std::vector< uint256 > & vector) inline
Definition at line 1550 of file SerializedTypes.h.
                                                    : mValue (vector)
     {
         ;
     }
Member Function Documentation
void ripple::STVector256::add (Serializer & s) const virtual
Reimplemented from ripple::SerializedType.
Definition at line 354 of file SerializedTypes.cpp.
References ripple::Serializer::addVL(), and mValue.
 {
     s.addVL (mValue.empty () ? nullptr : mValue[0].begin (), mValue.size () * (256 / 8));
 }
void ripple::STVector256::addValue (uint256 const & v) inline
Definition at line 1612 of file SerializedTypes.h.
Referenced by ripple::FeaturesImpl::doValidation(), and ripple::STParsedJSON::parse().
     {
         mValue.push_back (v);
     }
uint256 const& ripple::STVector256::at (int i) const inline
Definition at line 1593 of file SerializedTypes.h.
Referenced by ripple::Ledger::getLedgerHash(), and ripple::Ledger::getLedgerHashes().
     {
         assert ((i >= 0) && (i < size ()));
         return mValue.at (i);
     }
uint256& ripple::STVector256::at (int i) inline
Definition at line 1598 of file SerializedTypes.h.
     {
         assert ((i >= 0) && (i < size ()));
         return mValue.at (i);
     }
std::vector<uint256>::const_iterator ripple::STVector256::begin () const inline
Definition at line 1624 of file SerializedTypes.h.
Referenced by construct().
     {
         return mValue.begin ();
     }
STVector256 * ripple::STVector256::construct (SerializerIterator & u, SField::ref name) static private
Definition at line 330 of file SerializedTypes.cpp.
References begin(), and ripple::SerializerIterator::getVL().
 {
     Blob data = u.getVL ();
     Blob ::iterator begin = data.begin ();
     std::unique_ptr<STVector256> vec (new STVector256 (name));
     int count = data.size () / (256 / 8);
     vec->mValue.reserve (count);
     unsigned int    uStart  = 0;
     for (unsigned int i = 0; i != count; i++)
     {
         unsigned int    uEnd    = uStart + (256 / 8);
         // This next line could be optimized to construct a default uint256 in the vector and then copy into it
         vec->mValue.push_back (uint256 (Blob (begin + uStart, begin + uEnd)));
         uStart  = uEnd;
     }
     return vec.release ();
 }
static std::unique_ptr<SerializedType> ripple::STVector256::deserialize (SerializerIterator & sit, SField::ref name) inline static
Definition at line 1561 of file SerializedTypes.h.
Referenced by ripple::STObject::makeDeserializedObject().
     {
         return std::unique_ptr<SerializedType> (construct (sit, name));
     }
STVector256* ripple::STVector256::duplicate () const inline private virtual
Reimplemented from ripple::SerializedType.
Definition at line 1636 of file SerializedTypes.h.
     {
         return new STVector256 (*this);
     }
std::vector<uint256>::const_iterator ripple::STVector256::end () const inline
Definition at line 1628 of file SerializedTypes.h.
     {
         return mValue.end ();
     }
Json::Value ripple::STVector256::getJson (int options) const virtual
Reimplemented from ripple::SerializedType.
Definition at line 1133 of file SerializedObject.cpp.
References Json::Value::append(), Json::arrayValue, and mValue.
 {
     Json::Value ret (Json::arrayValue);
     BOOST_FOREACH (std::vector<uint256>::const_iterator::value_type vEntry, mValue)
     ret.append (vEntry.ToString ());
     return ret;
 }
SerializedTypeID ripple::STVector256::getSType () const inline virtual
Reimplemented from ripple::SerializedType.
Definition at line 1555 of file SerializedTypes.h.
     {
         return STI_VECTOR256;
     }
std::vector<uint256> ripple::STVector256::getValue () const inline
Definition at line 1580 of file SerializedTypes.h.
     {
         return mValue;
     }
bool ripple::STVector256::hasValue (uint256 const & v) const
Definition at line 365 of file SerializedTypes.cpp.
References hash, and mValue.
 {
     BOOST_FOREACH (uint256 const & hash, mValue)
     {
         if (hash == v)
             return true;
     }
     return false;
 }
virtual bool ripple::STVector256::isDefault () const inline virtual
Reimplemented from ripple::SerializedType.
Definition at line 1575 of file SerializedTypes.h.
     {
         return mValue.empty ();
     }
bool ripple::STVector256::isEmpty () const inline
Definition at line 1588 of file SerializedTypes.h.
     {
         return mValue.empty ();
     }
bool ripple::STVector256::isEquivalent (const SerializedType & t) const virtual
Reimplemented from ripple::SerializedType.
Definition at line 359 of file SerializedTypes.cpp.
References mValue.
 {
     const STVector256* v = dynamic_cast<const STVector256*> (&t);
     return v && (mValue == v->mValue);
 }
const std::vector<uint256>& ripple::STVector256::peekValue () const inline
Definition at line 1566 of file SerializedTypes.h.
Referenced by ripple::LedgerEntrySet::dirAdd(), ripple::LedgerEntrySet::dirDelete(), ripple::LedgerEntrySet::dirNext(), ripple::OfferCreateTransactor::doApply(), and ripple::NetworkOPsImp::getOwnerInfo().
     {
         return mValue;
     }
std::vector<uint256>& ripple::STVector256::peekValue () inline
Definition at line 1570 of file SerializedTypes.h.
     {
         return mValue;
     }
void ripple::STVector256::setValue (const STVector256 & v) inline
Definition at line 1604 of file SerializedTypes.h.
References mValue.
Referenced by ripple::STObject::setFieldV256().
     {
         mValue = v.mValue;
     }
void ripple::STVector256::setValue (const std::vector< uint256 > & v) inline
Definition at line 1608 of file SerializedTypes.h.
     {
         mValue = v;
     }
int ripple::STVector256::size () const inline
Definition at line 1584 of file SerializedTypes.h.
Referenced by ripple::Ledger::getLedgerHash(), and ripple::Ledger::getLedgerHashes().
     {
         return mValue.size ();
     }
void ripple::STVector256::sort () inline
Definition at line 1617 of file SerializedTypes.h.
Referenced by ripple::FeaturesImpl::doValidation().
     {
         std::sort (mValue.begin (), mValue.end ());
     }
Member Data Documentation
std::vector<uint256> ripple::STVector256::mValue private
Definition at line 1634 of file SerializedTypes.h.
Referenced by add(), getJson(), hasValue(), isEquivalent(), and setValue().
The documentation for this class was generated from the following files:
rippled/src/ripple_data/protocol/SerializedTypes.h
rippled/src/ripple_data/protocol/SerializedObject.cpp
rippled/src/ripple_data/protocol/SerializedTypes.cpp