rippled: beast::sqdb::detail::ref_counted_statement Class Reference
beast::sqdb::detail::ref_counted_statement Class Reference
#include <ref_counted_statement.h>
Public Member Functions
ref_counted_statement (session &s, Error &error)
void exchange (into_type_ptr const &i)
void exchange (use_type_ptr const &u)
void final_action ()
Public Member Functions inherited from beast::sqdb::detail::ref_counted_statement_base
ref_counted_statement_base (session &s)
virtual ~ref_counted_statement_base ()
void addref ()
void release ()
template<typename T >
void accumulate (T const &t)
std::ostringstream & get_query_stream ()
Private Attributes
Error & m_error
statement m_st
Additional Inherited Members
Public Attributes inherited from beast::sqdb::detail::ref_counted_statement_base
Error * m_perror
int m_refs
session & m_session
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
Definition at line 94 of file ref_counted_statement.h.
Constructor & Destructor Documentation
beast::sqdb::detail::ref_counted_statement::ref_counted_statement (session & s, Error & error)
Definition at line 95 of file ref_counted_statement.cpp.
     : ref_counted_statement_base(s)
     , m_error(error)
     , m_st(s)
 {
 }
Member Function Documentation
void beast::sqdb::detail::ref_counted_statement::exchange (into_type_ptr const & i)
Definition at line 102 of file ref_counted_statement.cpp.
References beast::sqdb::statement::exchange(), and m_st.
Referenced by beast::sqdb::detail::once_temp_type::operator,().
 {
     m_st.exchange(i);
 }
void beast::sqdb::detail::ref_counted_statement::exchange (use_type_ptr const & u)
Definition at line 107 of file ref_counted_statement.cpp.
References beast::sqdb::statement::exchange(), and m_st.
 {
     m_st.exchange(u);
 }
void beast::sqdb::detail::ref_counted_statement::final_action () virtual
Implements beast::sqdb::detail::ref_counted_statement_base.
Definition at line 112 of file ref_counted_statement.cpp.
References beast::sqdb::statement::clean_up(), beast::sqdb::statement::execute_and_fetch(), beast::sqdb::session::get_query_stream(), m_error, beast::sqdb::detail::ref_counted_statement_base::m_session, m_st, and beast::sqdb::statement::prepare().
 {
     m_st.prepare(m_session.get_query_stream().str(), false);
     Error error;
     m_st.execute_and_fetch(error);
     m_error = error;
     m_st.clean_up();
 }
Member Data Documentation
Error& beast::sqdb::detail::ref_counted_statement::m_error private
Definition at line 104 of file ref_counted_statement.h.
Referenced by final_action().
statement beast::sqdb::detail::ref_counted_statement::m_st private
Definition at line 105 of file ref_counted_statement.h.
Referenced by exchange(), and final_action().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_sqdb/detail/ref_counted_statement.h
rippled/src/beast/modules/beast_sqdb/source/ref_counted_statement.cpp