rippled: ripple::PeerFinder::WrappedSink Class Reference
ripple::PeerFinder::WrappedSink Class Reference
#include <WrappedSink.h>
Public Member Functions
WrappedSink (std::string const &prefix, beast::Journal::Sink &sink)
bool active (beast::Journal::Severity level) const
bool console () const
void console (bool output)
beast::Journal::Severity severity () const
void severity (beast::Journal::Severity level)
void write (beast::Journal::Severity level, std::string const &text)
Public Member Functions inherited from beast::Journal::Sink
Sink ()
virtual ~Sink ()=0
Private Attributes
std::string const m_prefix
beast::Journal::Sink & m_sink
Detailed Description
Wraps a Journal::Sink to prefix it's output.
Definition at line 27 of file WrappedSink.h.
Constructor & Destructor Documentation
ripple::PeerFinder::WrappedSink::WrappedSink (std::string const & prefix, beast::Journal::Sink & sink) inline
Definition at line 30 of file WrappedSink.h.
         : m_prefix (prefix)
         , m_sink (sink)
     {
     }
Member Function Documentation
bool ripple::PeerFinder::WrappedSink::active (beast::Journal::Severity level) const inline virtual
Returns true if text at the passed severity produces output.
Reimplemented from beast::Journal::Sink.
Definition at line 36 of file WrappedSink.h.
References beast::Journal::Sink::active(), and m_sink.
         { return m_sink.active (level); }
bool ripple::PeerFinder::WrappedSink::console () const inline virtual
Returns true if a message is also written to the Output Window (MSVC).
Reimplemented from beast::Journal::Sink.
Definition at line 39 of file WrappedSink.h.
References beast::Journal::Sink::console(), and m_sink.
         { return m_sink.console (); }
void ripple::PeerFinder::WrappedSink::console (bool output) inline virtual
Set whether messages are also written to the Output Window (MSVC).
Reimplemented from beast::Journal::Sink.
Definition at line 42 of file WrappedSink.h.
References beast::Journal::Sink::console(), and m_sink.
         { m_sink.console (output); }
beast::Journal::Severity ripple::PeerFinder::WrappedSink::severity () const inline virtual
Returns the minimum severity level this sink will report.
Reimplemented from beast::Journal::Sink.
Definition at line 45 of file WrappedSink.h.
References m_sink, and beast::Journal::Sink::severity().
         { return m_sink.severity(); }
void ripple::PeerFinder::WrappedSink::severity (beast::Journal::Severity level) inline virtual
Set the minimum severity this sink will report.
Reimplemented from beast::Journal::Sink.
Definition at line 48 of file WrappedSink.h.
References m_sink, and beast::Journal::Sink::severity().
         { m_sink.severity (level); }
void ripple::PeerFinder::WrappedSink::write (beast::Journal::Severity level, std::string const & text) inline virtual
Write text to the sink at the specified severity. The caller is responsible for checking the minimum severity level before using this function.
Implements beast::Journal::Sink.
Definition at line 51 of file WrappedSink.h.
References m_prefix, m_sink, and beast::Journal::Sink::write().
     {
         using beast::Journal;
         std::string s (m_prefix);
         switch (level)
         {
         case Journal::kTrace:   s += "Trace: "; break;
         case Journal::kDebug:   s += "Debug: "; break;
         case Journal::kInfo:    s += "Info : "; break;
         case Journal::kWarning: s += "Warn : "; break;
         case Journal::kError:   s += "Error: "; break;
         default:
         case Journal::kFatal:   s += "Fatal: "; break;
         };
         s+= text;
         m_sink.write (level, s);
     }
Member Data Documentation
std::string const ripple::PeerFinder::WrappedSink::m_prefix private
Definition at line 71 of file WrappedSink.h.
Referenced by write().
beast::Journal::Sink& ripple::PeerFinder::WrappedSink::m_sink private
Definition at line 72 of file WrappedSink.h.
Referenced by active(), console(), severity(), and write().
The documentation for this class was generated from the following file:
rippled/src/ripple/peerfinder/sim/WrappedSink.h