rippled: ripple::DatabaseCon Class Reference
ripple::DatabaseCon Class Reference
#include <DatabaseCon.h>
Public Member Functions
DatabaseCon (const std::string &name, const char *initString[], int countInit)
~DatabaseCon ()
Database * getDB ()
DeprecatedRecursiveMutex & getDBLock ()
Private Attributes
Database * mDatabase
DeprecatedRecursiveMutex mLock
Detailed Description
Definition at line 27 of file DatabaseCon.h.
Constructor & Destructor Documentation
ripple::DatabaseCon::DatabaseCon (const std::string & name, const char * initString[], int countInit)
Definition at line 22 of file DatabaseCon.cpp.
References ripple::Database::connect(), ripple::Config::DATA_DIR, ripple::Database::executeSQL(), ripple::getConfig(), ripple::Config::LOAD, mDatabase, beast.util.CleanCPPFiles::path, ripple::Config::REPLAY, ripple::Config::RUN_STANDALONE, and ripple::Config::START_UP.
 {
     // VFALCO TODO remove this dependency on the config by making it the caller's
     //         responsibility to pass in the path. Add a member function to Application
     //         or Config to compute this path.
     //
     boost::filesystem::path pPath   = (getConfig ().RUN_STANDALONE &&
                                           ((getConfig ().START_UP != Config::LOAD) && (getConfig ().START_UP != Config::REPLAY)))
                                       ? ""                                // Use temporary files.
                                       : (getConfig ().DATA_DIR / strName);       // Use regular db files.
     mDatabase = new SqliteDatabase (pPath.string ().c_str ());
     mDatabase->connect ();
     for (int i = 0; i < initCount; ++i)
         mDatabase->executeSQL (initStrings[i], true);
 }
ripple::DatabaseCon::~DatabaseCon ()
Definition at line 40 of file DatabaseCon.cpp.
References ripple::Database::disconnect(), and mDatabase.
 {
     mDatabase->disconnect ();
     delete mDatabase;
 }
Member Function Documentation
Database* ripple::DatabaseCon::getDB () inline
Definition at line 32 of file DatabaseCon.h.
References mDatabase.
Referenced by ripple::addTxnSeqField(), ripple::LocalCredentials::dataDelete(), ripple::LocalCredentials::dataFetch(), ripple::LocalCredentials::dataStore(), ripple::RPCHandler::doGetCounts(), ripple::RPCHandler::doTxHistory(), ripple::ValidationsImp::doWrite(), ripple::UniqueNodeListImp::fetchNext(), ripple::NetworkOPsImp::getAccountTxs(), ripple::NetworkOPsImp::getAccountTxsB(), ripple::FeaturesImpl::getCreate(), ripple::Ledger::getHashByIndex(), ripple::Ledger::getHashesByIndex(), ripple::NetworkOPsImp::getLedgerAffectedAccounts(), ripple::getSchema(), ripple::UniqueNodeListImp::getSeedDomains(), ripple::UniqueNodeListImp::getSeedNodes(), ripple::Ledger::getSQL(), ripple::NetworkOPsImp::getTxsAccount(), ripple::NetworkOPsImp::getTxsAccountB(), ripple::UniqueNodeListImp::getUnlJson(), ripple::Ledger::loadByHash(), ripple::Ledger::loadByIndex(), ripple::UniqueNodeListImp::miscLoad(), ripple::UniqueNodeListImp::miscSave(), ripple::UniqueNodeListImp::nodeBootstrap(), ripple::LocalCredentials::nodeIdentityCreate(), ripple::LocalCredentials::nodeIdentityLoad(), ripple::UniqueNodeListImp::nodeRemoveDomain(), ripple::UniqueNodeListImp::nodeRemovePublic(), ripple::UniqueNodeListImp::nodeReset(), ripple::UniqueNodeListImp::processIps(), ripple::UniqueNodeListImp::processValidators(), ripple::FeaturesImpl::reportValidations(), ripple::Ledger::saveValidatedLedger(), ripple::UniqueNodeListImp::scoreCompute(), ripple::UniqueNodeListImp::setSeedDomains(), ripple::UniqueNodeListImp::setSeedNodes(), ripple::ApplicationImp::setup(), ripple::Transaction::transactionFromSQL(), and ripple::UniqueNodeListImp::trustedLoad().
     {
         return mDatabase;
     }
DeprecatedRecursiveMutex& ripple::DatabaseCon::getDBLock () inline
Definition at line 36 of file DatabaseCon.h.
References mLock.
Referenced by ripple::Ledger::getHashesByIndex().
     {
         return mLock;
     }
Member Data Documentation
Database* ripple::DatabaseCon::mDatabase private
Definition at line 43 of file DatabaseCon.h.
Referenced by DatabaseCon(), getDB(), and ~DatabaseCon().
DeprecatedRecursiveMutex ripple::DatabaseCon::mLock private
Definition at line 44 of file DatabaseCon.h.
Referenced by getDBLock().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/data/DatabaseCon.h
rippled/src/ripple_app/data/DatabaseCon.cpp