rippled: beast::LexicalCast< Out, String > Struct Template Reference
beast::LexicalCast< Out, String > Struct Template Reference
#include <LexicalCast.h>
Public Member Functions
bool operator() (int &out, String const &in) const
bool operator() (short &out, String const &in) const
bool operator() (std::int64_t &out, String const &in) const
bool operator() (unsigned int &out, String const &in) const
bool operator() (unsigned short &out, String const &in) const
bool operator() (std::uint64_t &out, String const &in) const
bool operator() (float &out, String const &in) const
bool operator() (double &out, String const &in) const
bool operator() (bool &out, String const &in) const
Detailed Description
template<class Out>
struct beast::LexicalCast< Out, String >
Definition at line 154 of file LexicalCast.h.
Member Function Documentation
template<class Out > bool beast::LexicalCast< Out, String >::operator() (int & out, String const & in) const inline
Definition at line 156 of file LexicalCast.h.
References beast::LexicalCastUtilities::parseSigned(), and beast::String::toStdString().
 { std::string const& s (in.toStdString ()); return LexicalCastUtilities::parseSigned (out, s.begin (), s.end ()); }
template<class Out > bool beast::LexicalCast< Out, String >::operator() (short & out, String const & in) const inline
Definition at line 157 of file LexicalCast.h.
References beast::LexicalCastUtilities::parseSigned(), and beast::String::toStdString().
 { std::string const& s (in.toStdString ()); return LexicalCastUtilities::parseSigned (out, s.begin (), s.end ()); }
template<class Out > bool beast::LexicalCast< Out, String >::operator() (std::int64_t & out, String const & in) const inline
Definition at line 158 of file LexicalCast.h.
References beast::LexicalCastUtilities::parseSigned(), and beast::String::toStdString().
 { std::string const& s (in.toStdString ()); return LexicalCastUtilities::parseSigned (out, s.begin (), s.end ()); }
template<class Out > bool beast::LexicalCast< Out, String >::operator() (unsigned int & out, String const & in) const inline
Definition at line 159 of file LexicalCast.h.
References beast::LexicalCastUtilities::parseUnsigned(), and beast::String::toStdString().
 { std::string const& s (in.toStdString ()); return LexicalCastUtilities::parseUnsigned (out, s.begin (), s.end ()); }
template<class Out > bool beast::LexicalCast< Out, String >::operator() (unsigned short & out, String const & in) const inline
Definition at line 160 of file LexicalCast.h.
References beast::LexicalCastUtilities::parseUnsigned(), and beast::String::toStdString().
 { std::string const& s (in.toStdString ()); return LexicalCastUtilities::parseUnsigned (out, s.begin (), s.end ()); }
template<class Out > bool beast::LexicalCast< Out, String >::operator() (std::uint64_t & out, String const & in) const inline
Definition at line 161 of file LexicalCast.h.
References beast::LexicalCastUtilities::parseUnsigned(), and beast::String::toStdString().
 { std::string const& s (in.toStdString ()); return LexicalCastUtilities::parseUnsigned (out, s.begin (), s.end ()); }
template<class Out > bool beast::LexicalCast< Out, String >::operator() (float & out, String const & in) const inline
Definition at line 162 of file LexicalCast.h.
References bassertfalse.
 { bassertfalse; return false; /* UNIMPLEMENTED! */ }
template<class Out > bool beast::LexicalCast< Out, String >::operator() (double & out, String const & in) const inline
Definition at line 163 of file LexicalCast.h.
References bassertfalse.
 { bassertfalse; return false; /* UNIMPLEMENTED! */ }
template<class Out > bool beast::LexicalCast< Out, String >::operator() (bool & out, String const & in) const inline
Definition at line 165 of file LexicalCast.h.
     {
         // boost::lexical_cast is very strict, it
         // throws on anything but "1" or "0"
         //
         if (in == "1")
         {
             out = true;
             return true;
         }
         else if (in == "0")
         {
             out = false;
             return true;
         }
         return false;
     }
The documentation for this struct was generated from the following file:
rippled/src/beast/modules/beast_core/text/LexicalCast.h