rippled: beast::ParsedURL Class Reference
beast::ParsedURL Class Reference
#include <ParsedURL.h>
Public Member Functions
ParsedURL ()
ParsedURL (String const &url)
ParsedURL (int error, URL const &url)
ParsedURL (ParsedURL const &other)
ParsedURL & operator= (ParsedURL const &other)
int error () const
URL url () const
Private Attributes
int m_error
URL m_url
Detailed Description
Parses a String containing a URL.
Definition at line 29 of file ParsedURL.h.
Constructor & Destructor Documentation
beast::ParsedURL::ParsedURL ()
Definition at line 29 of file ParsedURL.cpp.
     : m_error (0)
 {
 }
beast::ParsedURL::ParsedURL (String const & url) explicit
Definition at line 34 of file ParsedURL.cpp.
References beast::joyent::http_parser_parse_url(), m_error, m_url, rocksdb::path_(), beast::String::toStdString(), beast::joyent::UF_FRAGMENT, beast::joyent::UF_HOST, beast::joyent::UF_PATH, beast::joyent::UF_PORT, beast::joyent::UF_QUERY, beast::joyent::UF_SCHEMA, and beast::joyent::UF_USERINFO.
 {
     std::string const ss (url.toStdString ());
     std::size_t const buflen (ss.size ());
     char const* const buf (ss.c_str ());
     joyent::http_parser_url u;
     m_error = joyent::http_parser_parse_url (buf, buflen, false, &u);
     String scheme_;
     String host_;
     std::uint16_t port_ (0);
     String port_string_;
     String path_;
     String query_;
     String fragment_;
     String userinfo_;
     if (m_error == 0)
     {
         if ((u.field_set & (1<<joyent::UF_SCHEMA)) != 0)
         {
             scheme_ = String (
                 buf + u.field_data [joyent::UF_SCHEMA].off,
                     u.field_data [joyent::UF_SCHEMA].len);
         }
         if ((u.field_set & (1<<joyent::UF_HOST)) != 0)
         {
             host_ = String (
                 buf + u.field_data [joyent::UF_HOST].off,
                     u.field_data [joyent::UF_HOST].len);
         }
         if ((u.field_set & (1<<joyent::UF_PORT)) != 0)
         {
             port_ = u.port;
             port_string_ = String (
                 buf + u.field_data [joyent::UF_PORT].off,
                     u.field_data [joyent::UF_PORT].len);
         }
         else
         {
             port_ = 0;
         }
         if ((u.field_set & (1<<joyent::UF_PATH)) != 0)
         {
             path_ = String (
                 buf + u.field_data [joyent::UF_PATH].off,
                     u.field_data [joyent::UF_PATH].len);
         }
         if ((u.field_set & (1<<joyent::UF_QUERY)) != 0)
         {
             query_ = String (
                 buf + u.field_data [joyent::UF_QUERY].off,
                     u.field_data [joyent::UF_QUERY].len);
         }
         if ((u.field_set & (1<<joyent::UF_FRAGMENT)) != 0)
         {
             fragment_ = String (
                 buf + u.field_data [joyent::UF_FRAGMENT].off,
                     u.field_data [joyent::UF_FRAGMENT].len);
         }
         if ((u.field_set & (1<<joyent::UF_USERINFO)) != 0)
         {
             userinfo_ = String (
                 buf + u.field_data [joyent::UF_USERINFO].off,
                     u.field_data [joyent::UF_USERINFO].len);
         }
         m_url = URL (
             scheme_,
             host_,
             port_,
             port_string_,
             path_,
             query_,
             fragment_,
             userinfo_);
     }
 }
beast::ParsedURL::ParsedURL (int error, URL const & url)
Definition at line 121 of file ParsedURL.cpp.
     : m_error (error)
     , m_url (url)
 {
 }
beast::ParsedURL::ParsedURL (ParsedURL const & other)
Definition at line 127 of file ParsedURL.cpp.
     : m_error (other.m_error)
     , m_url (other.m_url)
 {
 }
Member Function Documentation
int beast::ParsedURL::error () const
Zero for success, else a non zero value indicating failure.
Definition at line 140 of file ParsedURL.cpp.
References m_error.
Referenced by ripple::SiteFiles::Logic::addURL(), and beast::ParsedURL_test::checkURL().
 {
     return m_error;
 }
ParsedURL & beast::ParsedURL::operator= (ParsedURL const & other)
Definition at line 133 of file ParsedURL.cpp.
References m_error, and m_url.
 {
     m_error = other.m_error;
     m_url = other.m_url;
     return *this;
 }
URL beast::ParsedURL::url () const
The parsed URL if there was no error.
Definition at line 145 of file ParsedURL.cpp.
References m_url.
Referenced by ripple::SiteFiles::Logic::addURL(), beast::ParsedURL_test::checkURL(), ripple::Config::getValidatorsURL(), and beast::asio::HTTPClient_test::testAsync().
 {
     return m_url;
 }
Member Data Documentation
int beast::ParsedURL::m_error private
Definition at line 45 of file ParsedURL.h.
Referenced by error(), operator=(), and ParsedURL().
URL beast::ParsedURL::m_url private
Definition at line 46 of file ParsedURL.h.
Referenced by operator=(), ParsedURL(), and url().
The documentation for this class was generated from the following files:
rippled/src/beast/beast/http/ParsedURL.h
rippled/src/beast/beast/http/impl/ParsedURL.cpp