rippled: beast::IP::IPEndpoint_test Class Reference
beast::IP::IPEndpoint_test Class Reference
Public Member Functions
void shouldParseV4 (std::string const &s, std::uint32_t value)
void failParseV4 (std::string const &s)
void testAddressV4 ()
void testAddressV4Proxy ()
void testAddress ()
void testEndpoint ()
template<typename T >
bool parse (char const *text, T &t)
template<typename T >
void shouldPass (char const *text)
template<typename T >
void shouldFail (char const *text)
template<typename T >
void testParse (char const *name)
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 38 of file IPEndpoint.test.cpp.
Member Function Documentation
void beast::IP::IPEndpoint_test::failParseV4 (std::string const & s) inline
Definition at line 55 of file IPEndpoint.test.cpp.
References beast::IP::AddressV4::from_string(), and beast::unit_test::suite::unexpected().
Referenced by testAddressV4().
     {
         unexpected (AddressV4::from_string (s).second);
     }
template<typename T > bool beast::IP::IPEndpoint_test::parse (char const * text, T & t) inline
Definition at line 205 of file IPEndpoint.test.cpp.
Referenced by shouldFail(), and shouldPass().
     {
         std::string input (text);
         std::istringstream stream (input);
         stream >> t;
         return !stream.fail();
     }
void beast::IP::IPEndpoint_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 246 of file IPEndpoint.test.cpp.
References testAddress(), testAddressV4(), testAddressV4Proxy(), and testEndpoint().
     {
         testAddressV4 ();
         testAddressV4Proxy();
         testAddress ();
         testEndpoint ();
         testParse <Endpoint> ("Parse Endpoint");
     }
template<typename T > void beast::IP::IPEndpoint_test::shouldFail (char const * text) inline
Definition at line 222 of file IPEndpoint.test.cpp.
References parse(), T, and beast::unit_test::suite::unexpected().
     {
         T t;
         unexpected (parse (text, t));
     }
void beast::IP::IPEndpoint_test::shouldParseV4 (std::string const & s, std::uint32_t value) inline
Definition at line 41 of file IPEndpoint.test.cpp.
References beast::unit_test::suite::expect(), beast::IP::AddressV4::from_string(), and beast::IP::to_string().
Referenced by testAddressV4().
     {
         std::pair <AddressV4, bool> const result (
             AddressV4::from_string (s));
         if (expect (result.second))
         {
             if (expect (result.first.value == value))
             {
                 expect (to_string (result.first) == s);
             }
         }
     }
template<typename T > void beast::IP::IPEndpoint_test::shouldPass (char const * text) inline
Definition at line 214 of file IPEndpoint.test.cpp.
References beast::unit_test::suite::expect(), parse(), T, and beast::IP::to_string().
     {
         T t;
         expect (parse (text, t));
         expect (to_string (t) == std::string (text));
     }
void beast::IP::IPEndpoint_test::testAddress () inline
Definition at line 131 of file IPEndpoint.test.cpp.
References beast::unit_test::suite::expect(), beast::IP::Address::from_string(), and beast::unit_test::suite::testcase().
Referenced by run().
     {
         testcase ("Address");
         std::pair <Address, bool> result (
             Address::from_string ("1.2.3.4"));
         expect (result.second);
         if (expect (result.first.is_v4 ()))
             expect (result.first.to_v4() == AddressV4 (1, 2, 3, 4));
     }
void beast::IP::IPEndpoint_test::testAddressV4 () inline
Definition at line 60 of file IPEndpoint.test.cpp.
References beast::unit_test::suite::expect(), failParseV4(), beast::IP::is_unspecified(), shouldParseV4(), beast::unit_test::suite::testcase(), beast::IP::to_string(), beast::unit_test::suite::unexpected(), beast::IP::AddressV4::value, and value.
Referenced by run().
     {
         testcase ("AddressV4");
         expect (AddressV4().value == 0);
         expect (is_unspecified (AddressV4()));
         expect (AddressV4(0x01020304).value == 0x01020304);
         expect (AddressV4(1, 2, 3, 4).value == 0x01020304);
         unexpected (is_unspecified (AddressV4(1, 2, 3, 4)));
         AddressV4 const v1 (1);
         expect (AddressV4(v1).value == 1);
         {
             AddressV4 v;
             v = v1;
             expect (v.value == v1.value);
         }
         {
             AddressV4 v;
             v [0] = 1;
             v [1] = 2;
             v [2] = 3;
             v [3] = 4;
             expect (v.value == 0x01020304);
         }
         expect (to_string (AddressV4(0x01020304)) == "1.2.3.4");
         shouldParseV4 ("1.2.3.4", 0x01020304);
         shouldParseV4 ("255.255.255.255", 0xffffffff);
         shouldParseV4 ("0.0.0.0", 0);
         failParseV4 (".");
         failParseV4 ("..");
         failParseV4 ("...");
         failParseV4 ("....");
         failParseV4 ("1");
         failParseV4 ("1.");
         failParseV4 ("1.2");
         failParseV4 ("1.2.");
         failParseV4 ("1.2.3");
         failParseV4 ("1.2.3.");
         failParseV4 ("256.0.0.0");
         failParseV4 ("-1.2.3.4");
     }
void beast::IP::IPEndpoint_test::testAddressV4Proxy () inline
Definition at line 109 of file IPEndpoint.test.cpp.
References beast::unit_test::suite::expect(), and beast::unit_test::suite::testcase().
Referenced by run().
     {
       testcase ("AddressV4::Proxy");
       AddressV4 v4 (10, 0, 0, 1);
       expect (v4[0]==10);
       expect (v4[1]==0);
       expect (v4[2]==0);
       expect (v4[3]==1);
       expect((!((0xff)<<16)) == 0x00000000);
       expect((~((0xff)<<16)) == 0xff00ffff);
       v4[1] = 10;
       expect (v4[0]==10);
       expect (v4[1]==10);
       expect (v4[2]==0);
       expect (v4[3]==1);
     }
void beast::IP::IPEndpoint_test::testEndpoint () inline
Definition at line 144 of file IPEndpoint.test.cpp.
References beast::unit_test::suite::expect(), beast::IP::Endpoint::from_string_checked(), beast::IP::AddressV4::get_class(), beast::IP::is_loopback(), beast::IP::is_multicast(), beast::IP::is_private(), beast::IP::is_public(), beast::IP::is_unspecified(), beast::unit_test::suite::testcase(), beast::IP::to_string(), and beast::IP::Endpoint::to_v4().
Referenced by run().
     {
         testcase ("Endpoint");
         {
             std::pair <Endpoint, bool> result (
                 Endpoint::from_string_checked ("1.2.3.4"));
             expect (result.second);
             if (expect (result.first.address().is_v4 ()))
             {
                 expect (result.first.address().to_v4() ==
                     AddressV4 (1, 2, 3, 4));
                 expect (result.first.port() == 0);
                 expect (to_string (result.first) == "1.2.3.4");
             }
         }
         {
             std::pair <Endpoint, bool> result (
                 Endpoint::from_string_checked ("1.2.3.4:5"));
             expect (result.second);
             if (expect (result.first.address().is_v4 ()))
             {
                 expect (result.first.address().to_v4() ==
                     AddressV4 (1, 2, 3, 4));
                 expect (result.first.port() == 5);
                 expect (to_string (result.first) == "1.2.3.4:5");
             }
         }
         Endpoint ep;
         ep = Endpoint (AddressV4 (127,0,0,1), 80);
         expect (! is_unspecified (ep));
         expect (! is_public (ep));
         expect (  is_private (ep));
         expect (! is_multicast (ep));
         expect (  is_loopback (ep));
         expect (to_string (ep) == "127.0.0.1:80");
         ep = Endpoint (AddressV4 (10,0,0,1));
         expect (AddressV4::get_class (ep.to_v4()) == 'A');
         expect (! is_unspecified (ep));
         expect (! is_public (ep));
         expect (  is_private (ep));
         expect (! is_multicast (ep));
         expect (! is_loopback (ep));
         expect (to_string (ep) == "10.0.0.1");
         ep = Endpoint (AddressV4 (166,78,151,147));
         expect (! is_unspecified (ep));
         expect (  is_public (ep));
         expect (! is_private (ep));
         expect (! is_multicast (ep));
         expect (! is_loopback (ep));
         expect (to_string (ep) == "166.78.151.147");
     }
template<typename T > void beast::IP::IPEndpoint_test::testParse (char const * name) inline
Definition at line 229 of file IPEndpoint.test.cpp.
References beast::unit_test::suite::testcase().
     {
         testcase (name);
         shouldPass <T> ("0.0.0.0");
         shouldPass <T> ("192.168.0.1");
         shouldPass <T> ("168.127.149.132");
         shouldPass <T> ("168.127.149.132:80");
         shouldPass <T> ("168.127.149.132:54321");
         shouldFail <T> ("");
         shouldFail <T> ("255");
         shouldFail <T> ("512");
         shouldFail <T> ("1.2.3.256");
         shouldFail <T> ("1.2.3:80");
     }
The documentation for this class was generated from the following file:
rippled/src/beast/beast/net/tests/IPEndpoint.test.cpp