rippled: leveldb_filterpolicy_t Struct Reference
leveldb_filterpolicy_t Struct Reference
Public Member Functions
virtual ~leveldb_filterpolicy_t ()
virtual const char * Name () const
virtual void CreateFilter (const Slice *keys, int n, std::string *dst) const
virtual bool KeyMayMatch (const Slice &key, const Slice &filter) const
Public Member Functions inherited from rocksdb::FilterPolicy
virtual ~FilterPolicy ()
Public Attributes
void * state_
void(* destructor_)(void *)
const char *(* name_)(void *)
char *(* create_)(void *, const char *const *key_array, const size_t *key_length_array, int num_keys, size_t *filter_length)
unsigned char(* key_match_)(void *, const char *key, size_t length, const char *filter, size_t filter_length)
Detailed Description
Definition at line 91 of file c.cc.
Constructor & Destructor Documentation
virtual leveldb_filterpolicy_t::~leveldb_filterpolicy_t () inline virtual
Definition at line 105 of file c.cc.
References state_.
{
     (*destructor_)(state_);
   }
Member Function Documentation
virtual void leveldb_filterpolicy_t::CreateFilter (const Slice * keys, int n, std::string * dst) const inline virtual
Implements rocksdb::FilterPolicy.
Definition at line 113 of file c.cc.
References rocksdb::Slice::data(), rocksdb::Slice::size(), and state_.
Referenced by leveldb_filterpolicy_create_bloom().
{
     std::vector<const char*> key_pointers(n);
     std::vector<size_t> key_sizes(n);
     for (int i = 0; i < n; i++) {
       key_pointers[i] = keys[i].data();
       key_sizes[i] = keys[i].size();
     }
     size_t len;
     char* filter = (*create_)(state_, &key_pointers[0], &key_sizes[0], n, &len);
     dst->append(filter, len);
     free(filter);
   }
virtual bool leveldb_filterpolicy_t::KeyMayMatch (const Slice & key, const Slice & filter) const inline virtual
Implements rocksdb::FilterPolicy.
Definition at line 126 of file c.cc.
References rocksdb::Slice::data(), key_match_, rocksdb::Slice::size(), and state_.
Referenced by leveldb_filterpolicy_create_bloom().
{
     return (*key_match_)(state_, key.data(), key.size(),
                          filter.data(), filter.size());
   }
virtual const char* leveldb_filterpolicy_t::Name () const inline virtual
Implements rocksdb::FilterPolicy.
Definition at line 109 of file c.cc.
References name_, and state_.
Referenced by leveldb_filterpolicy_create_bloom().
{
     return (*name_)(state_);
   }
Member Data Documentation
char*(* leveldb_filterpolicy_t::create_)(void *, const char *const *key_array, const size_t *key_length_array, int num_keys, size_t *filter_length)
Definition at line 95 of file c.cc.
Referenced by leveldb_filterpolicy_create().
void(* leveldb_filterpolicy_t::destructor_)(void *)
Definition at line 93 of file c.cc.
Referenced by leveldb_filterpolicy_create().
unsigned char(* leveldb_filterpolicy_t::key_match_)(void *, const char *key, size_t length, const char *filter, size_t filter_length)
Definition at line 100 of file c.cc.
Referenced by KeyMayMatch(), and leveldb_filterpolicy_create().
const char*(* leveldb_filterpolicy_t::name_)(void *)
Definition at line 94 of file c.cc.
Referenced by leveldb_filterpolicy_create(), and Name().
void* leveldb_filterpolicy_t::state_
Definition at line 92 of file c.cc.
Referenced by CreateFilter(), KeyMayMatch(), leveldb_filterpolicy_create(), Name(), and ~leveldb_filterpolicy_t().
The documentation for this struct was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/db/c.cc