rippled: beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t Class Reference
beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t Class Reference
Public Member Functions
config_t (clock_type &clock_)
config_t (clock_type &clock_, Hash const &hash)
config_t (clock_type &clock_, KeyEqual const &keyEqual)
config_t (clock_type &clock_, Allocator const &alloc_)
config_t (clock_type &clock_, Hash const &hash, KeyEqual const &keyEqual)
config_t (clock_type &clock_, Hash const &hash, Allocator const &alloc_)
config_t (clock_type &clock_, KeyEqual const &keyEqual, Allocator const &alloc_)
config_t (clock_type &clock_, Hash const &hash, KeyEqual const &keyEqual, Allocator const &alloc_)
config_t (config_t const &other)
config_t (config_t const &other, Allocator const &alloc)
config_t (config_t &&other)
config_t (config_t &&other, Allocator const &alloc)
config_t & operator= (config_t const &other)
config_t & operator= (config_t &&other)
ValueHash & value_hash ()
ValueHash const & value_hash () const
Hash & hash_function ()
Hash const & hash_function () const
KeyValueEqual & key_value_equal ()
KeyValueEqual const & key_value_equal () const
KeyEqual & key_eq ()
KeyEqual const & key_eq () const
ElementAllocator & alloc ()
ElementAllocator const & alloc () const
Public Attributes
std::reference_wrapper
< clock_type > clock
Additional Inherited Members
Private Member Functions inherited from beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::ValueHash
ValueHash ()
ValueHash (Hash const &hash)
std::size_t operator() (element const &e) const
Hash & hash_function ()
Hash const & hash_function () const
Private Member Functions inherited from beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::KeyValueEqual
KeyValueEqual ()
KeyValueEqual (KeyEqual const &keyEqual)
bool operator() (Key const &k, element const &e) const
bool operator() (element const &e, Key const &k) const
bool operator() (element const &lhs, element const &rhs) const
KeyEqual & key_eq ()
KeyEqual const & key_eq () const
Private Member Functions inherited from beast::empty_base_optimization< ElementAllocator >
empty_base_optimization ()=default
empty_base_optimization (ElementAllocatorconst &t)
empty_base_optimization (ElementAllocator &&t)
ElementAllocator & member () noexcept
ElementAllocatorconst & member () const noexcept
Detailed Description
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>>
class beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t
Definition at line 292 of file aged_unordered_container.h.
Constructor & Destructor Documentation
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::config_t (clock_type & clock_) inline explicit
Definition at line 298 of file aged_unordered_container.h.
             : clock (clock_)
         {
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::config_t (clock_type & clock_, Hash const & hash) inline
Definition at line 304 of file aged_unordered_container.h.
             : ValueHash (hash)
             , clock (clock_)
         {
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::config_t (clock_type & clock_, KeyEqual const & keyEqual) inline
Definition at line 312 of file aged_unordered_container.h.
             : KeyValueEqual (keyEqual)
             , clock (clock_)
         {
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::config_t (clock_type & clock_, Allocator const & alloc_) inline
Definition at line 320 of file aged_unordered_container.h.
             : empty_base_optimization <ElementAllocator> (alloc_)
             , clock (clock_)
         {
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::config_t (clock_type & clock_, Hash const & hash, KeyEqual const & keyEqual) inline
Definition at line 328 of file aged_unordered_container.h.
             : ValueHash (hash)
             , KeyValueEqual (keyEqual)
             , clock (clock_)
         {
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::config_t (clock_type & clock_, Hash const & hash, Allocator const & alloc_) inline
Definition at line 338 of file aged_unordered_container.h.
             : ValueHash (hash)
             , empty_base_optimization <ElementAllocator> (alloc_)
             , clock (clock_)
         {
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::config_t (clock_type & clock_, KeyEqual const & keyEqual, Allocator const & alloc_) inline
Definition at line 348 of file aged_unordered_container.h.
             : KeyValueEqual (keyEqual)
             , empty_base_optimization <ElementAllocator> (alloc_)
             , clock (clock_)
         {
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::config_t (clock_type & clock_, Hash const & hash, KeyEqual const & keyEqual, Allocator const & alloc_) inline
Definition at line 358 of file aged_unordered_container.h.
             : ValueHash (hash)
             , KeyValueEqual (keyEqual)
             , empty_base_optimization <ElementAllocator> (alloc_)
             , clock (clock_)
         {
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::config_t (config_t const & other) inline
Definition at line 370 of file aged_unordered_container.h.
             : ValueHash (other.hash_function())
             , KeyValueEqual (other.key_eq())
             , empty_base_optimization <ElementAllocator> (
                 ElementAllocatorTraits::
                     select_on_container_copy_construction (
                         other.alloc()))
             , clock (other.clock)
         {
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::config_t (config_t const & other, Allocator const & alloc) inline
Definition at line 381 of file aged_unordered_container.h.
             : ValueHash (other.hash_function())
             , KeyValueEqual (other.key_eq())
             , empty_base_optimization <ElementAllocator> (alloc)
             , clock (other.clock)
         {
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::config_t (config_t && other) inline
Definition at line 389 of file aged_unordered_container.h.
             : ValueHash (std::move (other.hash_function()))
             , KeyValueEqual (std::move (other.key_eq()))
             , empty_base_optimization <ElementAllocator> (
                 std::move (other.alloc()))
             , clock (other.clock)
         {
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::config_t (config_t && other, Allocator const & alloc) inline
Definition at line 398 of file aged_unordered_container.h.
             : ValueHash (std::move (other.hash_function()))
             , KeyValueEqual (std::move (other.key_eq()))
             , empty_base_optimization <ElementAllocator> (alloc)
             , clock (other.clock)
         {
         }
Member Function Documentation
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> ElementAllocator& beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::alloc () inline
Definition at line 464 of file aged_unordered_container.h.
References beast::empty_base_optimization< ElementAllocator >::member().
Referenced by beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::delete_element(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::get_allocator(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::new_element(), beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::operator=(), and beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::swap_data().
         {
             return empty_base_optimization <
                 ElementAllocator>::member();
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> ElementAllocator const& beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::alloc () const inline
Definition at line 470 of file aged_unordered_container.h.
References beast::empty_base_optimization< ElementAllocator >::member().
         {
             return empty_base_optimization <
                 ElementAllocator>::member();
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> Hash& beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::hash_function () inline
Definition at line 434 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::ValueHash::hash_function().
Referenced by beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::bucket(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::count(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::equal_range(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::find(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::hash_function(), and beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::operator=().
         {
             return ValueHash::hash_function();
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> Hash const& beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::hash_function () const inline
Definition at line 439 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::ValueHash::hash_function().
         {
             return ValueHash::hash_function();
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> KeyEqual& beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::key_eq () inline
Definition at line 454 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::KeyValueEqual::key_eq(), and beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::key_value_equal().
Referenced by beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::key_eq(), and beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::operator=().
         {
             return key_value_equal().key_eq();
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> KeyEqual const& beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::key_eq () const inline
Definition at line 459 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::KeyValueEqual::key_eq(), and beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::key_value_equal().
         {
             return key_value_equal().key_eq();
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> KeyValueEqual& beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::key_value_equal () inline
Definition at line 444 of file aged_unordered_container.h.
Referenced by beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::count(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::equal_range(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::find(), and beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::key_eq().
         {
             return *this;
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> KeyValueEqual const& beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::key_value_equal () const inline
Definition at line 449 of file aged_unordered_container.h.
         {
             return *this;
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> config_t& beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::operator= (config_t const & other) inline
Definition at line 406 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::alloc(), beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::clock, beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::hash_function(), and beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::key_eq().
         {
             hash_function() = other.hash_function();
             key_eq() = other.key_eq();
             alloc() = other.alloc();
             clock = other.clock;
             return *this;
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> config_t& beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::operator= (config_t && other) inline
Definition at line 415 of file aged_unordered_container.h.
References beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::alloc(), beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::clock, beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::hash_function(), and beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::key_eq().
         {
             hash_function() = std::move (other.hash_function());
             key_eq() = std::move (other.key_eq());
             alloc() = std::move (other.alloc());
             clock = other.clock;
             return *this;
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> ValueHash& beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::value_hash () inline
Definition at line 424 of file aged_unordered_container.h.
         {
             return *this;
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> ValueHash const& beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::value_hash () const inline
Definition at line 429 of file aged_unordered_container.h.
         {
             return *this;
         }
Member Data Documentation
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> std::reference_wrapper<clock_type> beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::clock
Definition at line 476 of file aged_unordered_container.h.
Referenced by beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::clock(), beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::config_t::operator=(), and beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::swap_data().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/container/detail/aged_unordered_container.h