rippled: ripple::STAmount Class Reference
ripple::STAmount Class Reference
#include <SerializedTypes.h>
Public Member Functions
STAmount (std::uint64_t v=0, bool isNeg=false)
STAmount (SField::ref n, std::uint64_t v=0, bool isNeg=false)
STAmount (SField::ref n, std::int64_t v)
STAmount (const uint160 &uCurrencyID, const uint160 &uIssuerID, std::uint64_t uV=0, int iOff=0, bool bNegative=false)
STAmount (const uint160 &uCurrencyID, const uint160 &uIssuerID, std::uint32_t uV, int iOff=0, bool bNegative=false)
STAmount (SField::ref n, const uint160 &currency, const uint160 &issuer, std::uint64_t v=0, int off=0, bool isNeg=false)
STAmount (const uint160 &uCurrencyID, const uint160 &uIssuerID, std::int64_t v, int iOff=0)
STAmount (SField::ref n, const uint160 &currency, const uint160 &issuer, std::int64_t v, int off=0)
STAmount (const uint160 &uCurrencyID, const uint160 &uIssuerID, int v, int iOff=0)
STAmount (SField::ref n, const uint160 &currency, const uint160 &issuer, int v, int off=0)
STAmount (SField::ref, const Json::Value &)
bool bSetJson (const Json::Value &jvSource)
SerializedTypeID getSType () const
std::string getText () const
std::string getRaw () const
std::string getFullText () const
void add (Serializer &s) const
int getExponent () const
std::uint64_t getMantissa () const
int signum () const
std::uint64_t getNValue () const
void setNValue (std::uint64_t v)
std::int64_t getSNValue () const
void setSNValue (std::int64_t)
std::string getHumanCurrency () const
bool isNative () const
bool isLegalNet () const
operator bool () const noexcept
void negate ()
void clear ()
void clear (const STAmount &saTmpl)
void clear (const uint160 &uCurrencyID, const uint160 &uIssuerID)
STAmount & operator= (beast::Zero)
int compare (const STAmount &) const
const uint160 & getIssuer () const
STAmount * setIssuer (const uint160 &uIssuer)
const uint160 & getCurrency () const
bool setValue (const std::string &sAmount)
bool setFullValue (const std::string &sAmount, const std::string &sCurrency="", const std::string &sIssuer="")
void setValue (const STAmount &)
virtual bool isEquivalent (const SerializedType &t) const
virtual bool isDefault () const
bool operator== (const STAmount &) const
bool operator!= (const STAmount &) const
bool operator< (const STAmount &) const
bool operator> (const STAmount &) const
bool operator<= (const STAmount &) const
bool operator>= (const STAmount &) const
bool isComparable (const STAmount &) const
void throwComparable (const STAmount &) const
bool operator< (std::uint64_t) const
bool operator> (std::uint64_t) const
bool operator<= (std::uint64_t) const
bool operator>= (std::uint64_t) const
STAmount operator+ (std::uint64_t) const
STAmount operator- (std::uint64_t) const
STAmount operator- (void) const
STAmount & operator+= (const STAmount &)
STAmount & operator-= (const STAmount &)
STAmount & operator+= (std::uint64_t)
STAmount & operator-= (std::uint64_t)
STAmount & operator= (std::uint64_t)
operator double () const
Json::Value getJson (int) const
void setJson (Json::Value &) const
STAmount getRound () const
void roundSelf ()
Public Member Functions inherited from ripple::SerializedType
SerializedType ()
SerializedType (SField::ref n)
virtual ~SerializedType ()
void setFName (SField::ref n)
SField::ref getFName () const
std::string getName () const
std::unique_ptr< SerializedType > clone () const
void addFieldID (Serializer &s) const
SerializedType & operator= (const SerializedType &t)
bool operator== (const SerializedType &t) const
bool operator!= (const SerializedType &t) const
template<class D >
D & downcast ()
template<class D >
D const & downcast () const
Static Public Member Functions
static STAmount createFromInt64 (SField::ref n, std::int64_t v)
static std::unique_ptr
< SerializedType > deserialize (SerializerIterator &sit, SField::ref name)
static STAmount saFromRate (std::uint64_t uRate=0)
static STAmount divide (const STAmount &v1, const STAmount &v2, const uint160 &uCurrencyID, const uint160 &uIssuerID)
static STAmount divide (const STAmount &v1, const STAmount &v2, const STAmount &saUnit)
static STAmount divide (const STAmount &v1, const STAmount &v2)
static STAmount multiply (const STAmount &v1, const STAmount &v2, const uint160 &uCurrencyID, const uint160 &uIssuerID)
static STAmount multiply (const STAmount &v1, const STAmount &v2, const STAmount &saUnit)
static STAmount multiply (const STAmount &v1, const STAmount &v2)
static STAmount addRound (const STAmount &v1, const STAmount &v2, bool roundUp)
static STAmount subRound (const STAmount &v1, const STAmount &v2, bool roundUp)
static STAmount mulRound (const STAmount &v1, const STAmount &v2, const uint160 &currency, const uint160 &issuer, bool roundUp)
static STAmount divRound (const STAmount &v1, const STAmount &v2, const uint160 &currency, const uint160 &issuer, bool roundUp)
static STAmount mulRound (const STAmount &v1, const STAmount &v2, const STAmount &saUnit, bool roundUp)
static STAmount mulRound (const STAmount &v1, const STAmount &v2, bool roundUp)
static STAmount divRound (const STAmount &v1, const STAmount &v2, const STAmount &saUnit, bool roundUp)
static STAmount divRound (const STAmount &v1, const STAmount &v2, bool roundUp)
static std::uint64_t getRate (const STAmount &offerOut, const STAmount &offerIn)
static STAmount setRate (std::uint64_t rate)
static STAmount getPay (const STAmount &offerOut, const STAmount &offerIn, const STAmount &needed)
static std::string createHumanCurrency (const uint160 &uCurrency)
static Json::Value createJsonCurrency (const uint160 &uCurrency)
static STAmount deserialize (SerializerIterator &)
static bool currencyFromString (uint160 &uDstCurrency, const std::string &sCurrency)
static bool issuerFromString (uint160 &uDstIssuer, const std::string &sIssuer)
static void canonicalizeRound (bool isNative, std::uint64_t &value, int &offset, bool roundUp)
Static Public Member Functions inherited from ripple::SerializedType
static std::unique_ptr
< SerializedType > deserialize (SField::ref name)
Static Public Attributes
static const int cMinOffset = -96
static const int cMaxOffset = 80
static const std::uint64_t cMinValue = 1000000000000000ull
static const std::uint64_t cMaxValue = 9999999999999999ull
static const std::uint64_t cMaxNative = 9000000000000000000ull
static const std::uint64_t cMaxNativeN = 100000000000000000ull
static const std::uint64_t cNotNative = 0x8000000000000000ull
static const std::uint64_t cPosNative = 0x4000000000000000ull
static std::uint64_t uRateOne = STAmount::getRate (STAmount (1), STAmount (1))
Private Member Functions
void canonicalize ()
STAmount * duplicate () const
STAmount (SField::ref name, const uint160 &cur, const uint160 &iss, std::uint64_t val, int off, bool isNat, bool isNeg)
void set (std::int64_t v)
void set (int v)
Static Private Member Functions
static STAmount * construct (SerializerIterator &, SField::ref name)
Private Attributes
uint160 mCurrency
uint160 mIssuer
std::uint64_t mValue
int mOffset
bool mIsNative
bool mIsNegative
Friends
STAmount operator+ (const STAmount &v1, const STAmount &v2)
STAmount operator- (const STAmount &v1, const STAmount &v2)
Additional Inherited Members
Protected Attributes inherited from ripple::SerializedType
SField::ptr fName
Detailed Description
Definition at line 466 of file SerializedTypes.h.
Constructor & Destructor Documentation
ripple::STAmount::STAmount (std::uint64_t v = 0, bool isNeg = false) inline
Definition at line 478 of file SerializedTypes.h.
References mIsNegative.
Referenced by addRound(), construct(), createFromInt64(), divide(), divRound(), duplicate(), getPay(), getRound(), mulRound(), multiply(), operator+(), operator-(), saFromRate(), setRate(), and subRound().
                                                      : mValue (v), mOffset (0), mIsNative (true), mIsNegative (isNeg)
     {
         if (v == 0) mIsNegative = false;
     }
ripple::STAmount::STAmount (SField::ref n, std::uint64_t v = 0, bool isNeg = false) inline
Definition at line 483 of file SerializedTypes.h.
         : SerializedType (n), mValue (v), mOffset (0), mIsNative (true), mIsNegative (isNeg)
     {
         ;
     }
ripple::STAmount::STAmount (SField::ref n, std::int64_t v) inline
Definition at line 489 of file SerializedTypes.h.
References set().
                                          : SerializedType (n), mOffset (0), mIsNative (true)
     {
         set (v);
     }
ripple::STAmount::STAmount (const uint160 & uCurrencyID, const uint160 & uIssuerID, std::uint64_t uV = 0, int iOff = 0, bool bNegative = false) inline
Definition at line 494 of file SerializedTypes.h.
References canonicalize().
         : mCurrency (uCurrencyID), mIssuer (uIssuerID), mValue (uV), mOffset (iOff), mIsNegative (bNegative)
     {
         canonicalize ();
     }
ripple::STAmount::STAmount (const uint160 & uCurrencyID, const uint160 & uIssuerID, std::uint32_t uV, int iOff = 0, bool bNegative = false) inline
Definition at line 501 of file SerializedTypes.h.
References canonicalize().
         : mCurrency (uCurrencyID), mIssuer (uIssuerID), mValue (uV), mOffset (iOff), mIsNegative (bNegative)
     {
         canonicalize ();
     }
ripple::STAmount::STAmount (SField::ref n, const uint160 & currency, const uint160 & issuer, std::uint64_t v = 0, int off = 0, bool isNeg = false) inline
Definition at line 508 of file SerializedTypes.h.
References canonicalize().
                                                                   :
         SerializedType (n), mCurrency (currency), mIssuer (issuer), mValue (v), mOffset (off), mIsNegative (isNeg)
     {
         canonicalize ();
     }
ripple::STAmount::STAmount (const uint160 & uCurrencyID, const uint160 & uIssuerID, std::int64_t v, int iOff = 0) inline
Definition at line 515 of file SerializedTypes.h.
References canonicalize(), and set().
         : mCurrency (uCurrencyID), mIssuer (uIssuerID), mOffset (iOff)
     {
         set (v);
         canonicalize ();
     }
ripple::STAmount::STAmount (SField::ref n, const uint160 & currency, const uint160 & issuer, std::int64_t v, int off = 0) inline
Definition at line 522 of file SerializedTypes.h.
References canonicalize(), and set().
         : SerializedType (n), mCurrency (currency), mIssuer (issuer), mOffset (off)
     {
         set (v);
         canonicalize ();
     }
ripple::STAmount::STAmount (const uint160 & uCurrencyID, const uint160 & uIssuerID, int v, int iOff = 0) inline
Definition at line 529 of file SerializedTypes.h.
References canonicalize(), and set().
         : mCurrency (uCurrencyID), mIssuer (uIssuerID), mOffset (iOff)
     {
         set (v);
         canonicalize ();
     }
ripple::STAmount::STAmount (SField::ref n, const uint160 & currency, const uint160 & issuer, int v, int off = 0) inline
Definition at line 536 of file SerializedTypes.h.
References canonicalize(), and set().
         : SerializedType (n), mCurrency (currency), mIssuer (issuer), mOffset (off)
     {
         set (v);
         canonicalize ();
     }
ripple::STAmount::STAmount (SField::ref n, const Json::Value & v)
Definition at line 113 of file STAmount.cpp.
References Json::Value::asInt(), Json::Value::asString(), Json::Value::asUInt(), canonicalize(), currencyFromString(), Json::Value::get(), Json::Value::isArray(), Json::Value::isInt(), Json::Value::isObject(), Json::Value::isString(), issuerFromString(), Json::Value::isUInt(), ripple::base_uint< BITS >::isZero(), ripple::lsTRACE, mCurrency, mIsNative, mIsNegative, mIssuer, mValue, Json::nullValue, setValue(), SYSTEM_CURRENCY_CODE, value, and WriteLog.
     : SerializedType (n), mValue (0), mOffset (0), mIsNegative (false)
 {
     Json::Value value, currency, issuer;
     if (v.isObject ())
     {
         WriteLog (lsTRACE, STAmount) <<
             "value='" << v["value"].asString () <<
             "', currency='" << v["currency"].asString () <<
             "', issuer='" << v["issuer"].asString () <<
             "')";
         value       = v["value"];
         currency    = v["currency"];
         issuer      = v["issuer"];
     }
     else if (v.isArray ())
     {
         value = v.get (Json::UInt (0), 0);
         currency = v.get (Json::UInt (1), Json::nullValue);
         issuer = v.get (Json::UInt (2), Json::nullValue);
     }
     else if (v.isString ())
     {
         std::string val = v.asString ();
         std::vector<std::string> elements;
         boost::split (elements, val, boost::is_any_of ("\t\n\r ,/"));
         if (elements.size () > 3)
             throw std::runtime_error ("invalid amount string");
         value = elements[0];
         if (elements.size () > 1)
             currency = elements[1];
         if (elements.size () > 2)
             issuer = elements[2];
     }
     else
         value = v;
     mIsNative = !currency.isString () || currency.asString ().empty () || (currency.asString () == SYSTEM_CURRENCY_CODE);
     if (mIsNative)
     {
         if (v.isObject ())
             throw std::runtime_error ("XRP may not be specified as an object");
     }
     else
     {
         // non-XRP
         if (!currencyFromString (mCurrency, currency.asString ()))
             throw std::runtime_error ("invalid currency");
         if (!issuer.isString ()
                 || !issuerFromString (mIssuer, issuer.asString ()))
             throw std::runtime_error ("invalid issuer");
         if (mIssuer.isZero ())
             throw std::runtime_error ("invalid issuer");
     }
     if (value.isInt ())
     {
         if (value.asInt () >= 0)
             mValue = value.asInt ();
         else
         {
             mValue = -value.asInt ();
             mIsNegative = true;
         }
         canonicalize ();
     }
     else if (value.isUInt ())
     {
         mValue = v.asUInt ();
         canonicalize ();
     }
     else if (value.isString ())
     {
         if (mIsNative)
         {
             std::int64_t val = beast::lexicalCastThrow <std::int64_t> (value.asString ());
             if (val >= 0)
                 mValue = val;
             else
             {
                 mValue = -val;
                 mIsNegative = true;
             }
             canonicalize ();
         }
         else
         {
             setValue (value.asString ());
         }
     }
     else
         throw std::runtime_error ("invalid amount type");
 }
ripple::STAmount::STAmount (SField::ref name, const uint160 & cur, const uint160 & iss, std::uint64_t val, int off, bool isNat, bool isNeg) inline private
Definition at line 799 of file SerializedTypes.h.
         : SerializedType (name), mCurrency (cur), mIssuer (iss),  mValue (val), mOffset (off),
           mIsNative (isNat), mIsNegative (isNeg)
     {
         ;
     }
Member Function Documentation
void ripple::STAmount::add (Serializer & s) const virtual
Reimplemented from ripple::SerializedType.
Definition at line 476 of file STAmount.cpp.
References ripple::Serializer::add160(), ripple::Serializer::add64(), cNotNative, cPosNative, mCurrency, mIsNative, mIsNegative, mIssuer, mOffset, and mValue.
Referenced by ripple::STAmount_test::serializeAndDeserialize().
 {
     if (mIsNative)
     {
         assert (mOffset == 0);
         if (!mIsNegative)
             s.add64 (mValue | cPosNative);
         else
             s.add64 (mValue);
     }
     else
     {
         if (*this == zero)
             s.add64 (cNotNative);
         else if (mIsNegative) // 512 = not native
             s.add64 (mValue | (static_cast<std::uint64_t> (mOffset + 512 + 97) << (64 - 10)));
         else // 256 = positive
             s.add64 (mValue | (static_cast<std::uint64_t> (mOffset + 512 + 256 + 97) << (64 - 10)));
         s.add160 (mCurrency);
         s.add160 (mIssuer);
     }
 }
STAmount ripple::STAmount::addRound (const STAmount & v1, const STAmount & v2, bool roundUp) static
Definition at line 63 of file STAmountRound.cpp.
References canonicalizeRound(), ripple::SerializedType::getFName(), getSNValue(), mCurrency, mIsNative, mIsNegative, mIssuer, mOffset, mValue, STAmount(), and throwComparable().
Referenced by ripple::STAmount_test::testRounding().
 {
     v1.throwComparable (v2);
     if (v2.mValue == 0)
         return v1;
     if (v1.mValue == 0)
         return STAmount (v1.getFName (), v1.mCurrency, v1.mIssuer, v2.mValue, v2.mOffset, v2.mIsNegative);
     if (v1.mIsNative)
         return STAmount (v1.getFName (), v1.getSNValue () + v2.getSNValue ());
     int ov1 = v1.mOffset, ov2 = v2.mOffset;
     std::int64_t vv1 = static_cast<std::int64_t> (v1.mValue), vv2 = static_cast<std::uint64_t> (v2.mValue);
     if (v1.mIsNegative)
         vv1 = -vv1;
     if (v2.mIsNegative)
         vv2 = -vv2;
     if (ov1 < ov2)
     {
         while (ov1 < (ov2 - 1))
         {
             vv1 /= 10;
             ++ov1;
         }
         if (roundUp)
             vv1 += 9;
         vv1 /= 10;
         ++ov1;
     }
     if (ov2 < ov1)
     {
         while (ov2 < (ov1 - 1))
         {
             vv2 /= 10;
             ++ov2;
         }
         if (roundUp)
             vv2 += 9;
         vv2 /= 10;
         ++ov2;
     }
     std::int64_t fv = vv1 + vv2;
     if ((fv >= -10) && (fv <= 10))
         return STAmount (v1.getFName (), v1.mCurrency, v1.mIssuer);
     else if (fv >= 0)
     {
         std::uint64_t v = static_cast<std::uint64_t> (fv);
         canonicalizeRound (false, v, ov1, roundUp);
         return STAmount (v1.getFName (), v1.mCurrency, v1.mIssuer, v, ov1, false);
     }
     else
     {
         std::uint64_t v = static_cast<std::uint64_t> (-fv);
         canonicalizeRound (false, v, ov1, !roundUp);
         return STAmount (v1.getFName (), v1.mCurrency, v1.mIssuer, v, ov1, true);
     }
 }
bool ripple::STAmount::bSetJson (const Json::Value & jvSource)
Definition at line 96 of file STAmount.cpp.
References ripple::lsINFO, ripple::sfGeneric, and WriteLog.
Referenced by ripple::RPCHandler::doRipplePathFind(), ripple::PathRequest::parseJson(), and ripple::RPC::transactionSign().
 {
     try
     {
         STAmount    saParsed (sfGeneric, jvSource);
         *this   = saParsed;
         return true;
     }
     catch (const std::exception& e)
     {
         WriteLog (lsINFO, STAmount) << "bSetJson(): caught: " << e.what ();
         return false;
     }
 }
void ripple::STAmount::canonicalize () private
Definition at line 405 of file STAmount.cpp.
References cMaxNative, cMaxOffset, cMaxValue, cMinOffset, cMinValue, ripple::base_uint< BITS >::isZero(), mCurrency, mIsNative, mIsNegative, mOffset, and mValue.
Referenced by operator=(), roundSelf(), setValue(), and STAmount().
 {
     if (mCurrency.isZero ())
     {
         // native currency amounts should always have an offset of zero
         mIsNative = true;
         if (mValue == 0)
         {
             mOffset = 0;
             mIsNegative = false;
             return;
         }
         while (mOffset < 0)
         {
             mValue /= 10;
             ++mOffset;
         }
         while (mOffset > 0)
         {
             mValue *= 10;
             --mOffset;
         }
         if (mValue > cMaxNative)
             throw std::runtime_error ("Native currency amount out of range");
         return;
     }
     mIsNative = false;
     if (mValue == 0)
     {
         mOffset = -100;
         mIsNegative = false;
         return;
     }
     while ((mValue < cMinValue) && (mOffset > cMinOffset))
     {
         mValue *= 10;
         --mOffset;
     }
     while (mValue > cMaxValue)
     {
         if (mOffset >= cMaxOffset)
             throw std::runtime_error ("value overflow");
         mValue /= 10;
         ++mOffset;
     }
     if ((mOffset < cMinOffset) || (mValue < cMinValue))
     {
         mValue = 0;
         mOffset = 0;
         mIsNegative = false;
     }
     if (mOffset > cMaxOffset)
         throw std::runtime_error ("value overflow");
     assert ((mValue == 0) || ((mValue >= cMinValue) && (mValue <= cMaxValue)));
     assert ((mValue == 0) || ((mOffset >= cMinOffset) && (mOffset <= cMaxOffset)));
     assert ((mValue != 0) || (mOffset != -100));
 }
void ripple::STAmount::canonicalizeRound (bool isNative, std::uint64_t & value, int & offset, bool roundUp) static
Definition at line 22 of file STAmountRound.cpp.
References cMaxValue, ripple::lsTRACE, and WriteLog.
Referenced by addRound(), divRound(), mulRound(), subRound(), and ripple::STAmount_test::testRounding().
 {
     if (!roundUp) // canonicalize already rounds down
         return;
     WriteLog (lsTRACE, STAmount) << "canonicalize< " << value << ":" << offset << (roundUp ? " up" : " down");
     if (isNative)
     {
         if (offset < 0)
         {
             int loops = 0;
             while (offset < -1)
             {
                 value /= 10;
                 ++offset;
                 ++loops;
             }
             value += (loops >= 2) ? 9 : 10; // add before last divide
             value /= 10;
             ++offset;
         }
     }
     else if (value > STAmount::cMaxValue)
     {
         while (value > (10 * STAmount::cMaxValue))
         {
             value /= 10;
             ++offset;
         }
         value += 9;     // add before last divide
         value /= 10;
         ++offset;
     }
     WriteLog (lsTRACE, STAmount) << "canonicalize> " << value << ":" << offset << (roundUp ? " up" : " down");
 }
void ripple::STAmount::clear () inline
Definition at line 621 of file SerializedTypes.h.
References mIsNative, mIsNegative, mOffset, and mValue.
Referenced by ripple::LedgerEntrySet::accountHolds(), ripple::RippleCalc::calcNodeAccountFwd(), ripple::RippleCalc::calcNodeAccountRev(), ripple::RippleCalc::calcNodeDeliverFwd(), ripple::RippleCalc::calcNodeDeliverRev(), clear(), ripple::NetworkOPsImp::getBookPage(), operator=(), ripple::RippleCalc::pathNext(), ripple::LedgerEntrySet::rippleHolds(), ripple::LedgerEntrySet::rippleLimit(), and ripple::LedgerEntrySet::rippleOwed().
     {
         // VFALCO: Why -100?
         mOffset = mIsNative ? 0 : -100;
         mValue = 0;
         mIsNegative = false;
     }
void ripple::STAmount::clear (const STAmount & saTmpl) inline
Definition at line 630 of file SerializedTypes.h.
References clear(), mCurrency, mIsNative, and mIssuer.
     {
         mCurrency = saTmpl.mCurrency;
         mIssuer = saTmpl.mIssuer;
         mIsNative = saTmpl.mIsNative;
         clear ();
     }
void ripple::STAmount::clear (const uint160 & uCurrencyID, const uint160 & uIssuerID) inline
Definition at line 637 of file SerializedTypes.h.
References clear(), mCurrency, mIsNative, and mIssuer.
     {
         mCurrency = uCurrencyID;
         mIssuer = uIssuerID;
         mIsNative = !uCurrencyID;
         clear ();
     }
int ripple::STAmount::compare (const STAmount & a) const
Definition at line 518 of file STAmount.cpp.
References mIsNegative, mOffset, and mValue.
Referenced by operator<(), operator<=(), operator>(), and operator>=().
 {
     // Compares the value of a to the value of this STAmount, amounts must be comparable
     if (mIsNegative != a.mIsNegative) return mIsNegative ? -1 : 1;
     if (!mValue)
     {
         if (a.mIsNegative) return 1;
         return a.mValue ? -1 : 0;
     }
     if (!a.mValue) return 1;
     if (mOffset > a.mOffset) return mIsNegative ? -1 : 1;
     if (mOffset < a.mOffset) return mIsNegative ? 1 : -1;
     if (mValue > a.mValue) return mIsNegative ? -1 : 1;
     if (mValue < a.mValue) return mIsNegative ? 1 : -1;
     return 0;
 }
STAmount * ripple::STAmount::construct (SerializerIterator & sit, SField::ref name) static private
Definition at line 543 of file STAmount.cpp.
References cMaxOffset, cMaxValue, cMinOffset, cMinValue, cNotNative, cPosNative, ripple::SerializerIterator::get160(), ripple::SerializerIterator::get64(), STAmount(), and value.
Referenced by deserialize().
 {
     std::uint64_t value = sit.get64 ();
     if ((value & cNotNative) == 0)
     {
         // native
         if ((value & cPosNative) != 0)
             return new STAmount (name, value & ~cPosNative, false); // positive
         else if (value == 0)
             throw std::runtime_error ("negative zero is not canonical");
         return new STAmount (name, value, true); // negative
     }
     uint160 uCurrencyID = sit.get160 ();
     if (!uCurrencyID)
         throw std::runtime_error ("invalid non-native currency");
     uint160 uIssuerID = sit.get160 ();
     int offset = static_cast<int> (value >> (64 - 10)); // 10 bits for the offset, sign and "not native" flag
     value &= ~ (1023ull << (64 - 10));
     if (value)
     {
         bool isNegative = (offset & 256) == 0;
         offset = (offset & 255) - 97; // center the range
         if ((value < cMinValue) || (value > cMaxValue) || (offset < cMinOffset) || (offset > cMaxOffset))
             throw std::runtime_error ("invalid currency value");
         return new STAmount (name, uCurrencyID, uIssuerID, value, offset, isNegative);
     }
     if (offset != 512)
         throw std::runtime_error ("invalid currency value");
     return new STAmount (name, uCurrencyID, uIssuerID);
 }
STAmount ripple::STAmount::createFromInt64 (SField::ref n, std::int64_t v) static
Definition at line 501 of file STAmount.cpp.
References STAmount().
Referenced by ripple::operator-().
 {
     return value >= 0
            ? STAmount (name, static_cast<std::uint64_t> (value), false)
            : STAmount (name, static_cast<std::uint64_t> (-value), true);
 }
std::string ripple::STAmount::createHumanCurrency (const uint160 & uCurrency) static
Definition at line 220 of file STAmount.cpp.
References ripple::Serializer::add160(), CURRENCY_BAD, CURRENCY_ONE, ripple::base_uint< BITS >::GetHex(), ripple::SerializerIterator::getRaw(), ripple::base_uint< BITS >::isZero(), SYSTEM_CURRENCY_CODE, and ripple::base_uint< BITS >::ToString().
Referenced by ripple::RippleCalc::calcNodeAccountRev(), ripple::RippleCalc::calcNodeAdvance(), createJsonCurrency(), ripple::RPCHandler::doAccountCurrencies(), ripple::RPCHandler::doRipplePathFind(), ripple::Pathfinder::findPaths(), ripple::Ledger::getBookBase(), ripple::NetworkOPsImp::getBookPage(), getHumanCurrency(), ripple::PathState::Node::getJson(), ripple::STPath::getJson(), ripple::PathRequest::isValid(), ripple::PathState::pushImply(), ripple::PathState::pushNode(), ripple::LedgerEntrySet::rippleOwed(), ripple::LedgerEntrySet::rippleQualityIn(), ripple::PathState::setCanonical(), ripple::PathState::setExpanded(), ripple::OfferCreateTransactor::takeOffers(), and ripple::STAmount_test::testNativeCurrency().
 {
     static uint160 const sFiatBits("FFFFFFFFFFFFFFFFFFFFFFFF0000000000000000");
     if (uCurrency.isZero ())
     {
         return SYSTEM_CURRENCY_CODE;
     }
     if (CURRENCY_ONE == uCurrency)
     {
         return "1";
     }
     if (CURRENCY_BAD == uCurrency)
     {
         return uCurrency.ToString ();
     }
     if ((uCurrency & sFiatBits).isZero ())
     {
         Serializer s (160 / 8);
         s.add160 (uCurrency);
         SerializerIterator  sit (s);
         Blob const vucZeros    (sit.getRaw (96 / 8));
         Blob const vucIso      (sit.getRaw (24 / 8));
         Blob const vucVersion  (sit.getRaw (16 / 8));
         Blob const vucReserved (sit.getRaw (24 / 8));
         auto is_zero_filled = [](Blob const& blob)
         {
             auto ret = std::find_if (blob.cbegin (), blob.cend (),
                 [](unsigned char c)
                 {
                     return c != 0;
                 });
             return ret == blob.cend ();
         };
         bool bIso = is_zero_filled (vucZeros)        // Leading zeros
                     && is_zero_filled (vucVersion)   // Zero version
                     && is_zero_filled (vucReserved); // Reserved is zero.
         if (bIso)
             return std::string (vucIso.begin (), vucIso.end ());
         return uCurrency.ToString ();
     }
     return uCurrency.GetHex ();
 }
static Json::Value ripple::STAmount::createJsonCurrency (const uint160 & uCurrency) inline static
Definition at line 765 of file SerializedTypes.h.
References createHumanCurrency().
     {
         return createHumanCurrency (uCurrency);
     }
bool ripple::STAmount::currencyFromString (uint160 & uDstCurrency, const std::string & sCurrency) static
Definition at line 52 of file STAmount.cpp.
References ripple::Serializer::addZeros(), ripple::base_uint< BITS >::SetHex(), SYSTEM_CURRENCY_CODE, and ripple::base_uint< BITS >::zero().
Referenced by ripple::RPCHandler::doBookOffers(), ripple::RPCHandler::doLedgerEntry(), ripple::RPCHandler::doRipplePathFind(), ripple::RPCHandler::doSubscribe(), ripple::RPCHandler::doUnsubscribe(), ripple::STParsedJSON::parse(), ripple::PathRequest::parseJson(), setFullValue(), STAmount(), and ripple::STAmount_test::testNativeCurrency().
 {
     bool    bSuccess    = true;
     if (sCurrency.empty () || !sCurrency.compare (SYSTEM_CURRENCY_CODE))
     {
         uDstCurrency.zero ();
     }
     else if (3 == sCurrency.size ())
     {
         Blob    vucIso (3);
         std::transform (sCurrency.begin (), sCurrency.end (), vucIso.begin (), ::toupper);
         // std::string  sIso;
         // sIso.assign(vucIso.begin(), vucIso.end());
         // Log::out() << "currency: " << sIso;
         Serializer  s;
         s.addZeros (96 / 8);
         s.addRaw (vucIso);
         s.addZeros (16 / 8);
         s.addZeros (24 / 8);
         s.get160 (uDstCurrency, 0);
     }
     else if (40 == sCurrency.size ())
     {
         bSuccess    = uDstCurrency.SetHex (sCurrency);
     }
     else
     {
         bSuccess    = false;
     }
     return bSuccess;
 }
static std::unique_ptr<SerializedType> ripple::STAmount::deserialize (SerializerIterator & sit, SField::ref name) inline static
Definition at line 547 of file SerializedTypes.h.
References construct().
Referenced by ripple::STObject::makeDeserializedObject(), and ripple::STAmount_test::serializeAndDeserialize().
     {
         return std::unique_ptr<SerializedType> (construct (sit, name));
     }
STAmount ripple::STAmount::deserialize (SerializerIterator & it) static
Definition at line 1083 of file STAmount.cpp.
References construct(), and ripple::sfGeneric.
 {
     std::unique_ptr<STAmount> s (dynamic_cast<STAmount*> (construct (it, sfGeneric)));
     STAmount ret (*s);
     return ret;
 }
STAmount ripple::STAmount::divide (const STAmount & v1, const STAmount & v2, const uint160 & uCurrencyID, const uint160 & uIssuerID) static
Definition at line 920 of file STAmount.cpp.
References ripple::BN_add_word64(), ripple::BN_div_word64(), ripple::BN_mul_word64(), cMinValue, ripple::CBigNum::getuint64(), mIsNative, mIsNegative, mOffset, mValue, STAmount(), and tenTo17.
Referenced by ripple::OfferCreateTransactor::applyOffer(), divide(), ripple::core::Taker::fill(), ripple::Pathfinder::filterPaths(), ripple::NetworkOPsImp::getBookPage(), getPay(), getRate(), ripple::STAmount_test::roundTest(), ripple::OfferCreateTransactor::takeOffers(), ripple::STAmount_test::testCustomCurrency(), ripple::STAmount_test::testRounding(), and ripple::STAmount_test::testUnderflow().
 {
     if (den == zero)
         throw std::runtime_error ("division by zero");
     if (num == zero)
         return STAmount (uCurrencyID, uIssuerID);
     std::uint64_t numVal = num.mValue, denVal = den.mValue;
     int numOffset = num.mOffset, denOffset = den.mOffset;
     if (num.mIsNative)
         while (numVal < STAmount::cMinValue)
         {
             // Need to bring into range
             numVal *= 10;
             --numOffset;
         }
     if (den.mIsNative)
         while (denVal < STAmount::cMinValue)
         {
             denVal *= 10;
             --denOffset;
         }
     // Compute (numerator * 10^17) / denominator
     CBigNum v;
     if ((BN_add_word64 (&v, numVal) != 1) ||
             (BN_mul_word64 (&v, tenTo17) != 1) ||
             (BN_div_word64 (&v, denVal) == ((std::uint64_t) - 1)))
     {
         throw std::runtime_error ("internal bn error");
     }
     // 10^16 <= quotient <= 10^18
     assert (BN_num_bytes (&v) <= 64);
     return STAmount (uCurrencyID, uIssuerID, v.getuint64 () + 5,
                      numOffset - denOffset - 17, num.mIsNegative != den.mIsNegative);
 }
static STAmount ripple::STAmount::divide (const STAmount & v1, const STAmount & v2, const STAmount & saUnit) inline static
Definition at line 707 of file SerializedTypes.h.
References divide(), getCurrency(), and getIssuer().
     {
         return divide (v1, v2, saUnit.getCurrency (), saUnit.getIssuer ());
     }
static STAmount ripple::STAmount::divide (const STAmount & v1, const STAmount & v2) inline static
Definition at line 711 of file SerializedTypes.h.
References divide().
     {
         return divide (v1, v2, v1);
     }
STAmount ripple::STAmount::divRound (const STAmount & v1, const STAmount & v2, const uint160 & currency, const uint160 & issuer, bool roundUp) static
Definition at line 267 of file STAmountRound.cpp.
References ripple::BN_add_word64(), ripple::BN_div_word64(), ripple::BN_mul_word64(), canonicalizeRound(), cMinValue, ripple::CBigNum::getuint64(), ripple::base_uint< BITS >::isZero(), mIsNative, mIsNegative, mOffset, mValue, STAmount(), and tenTo17.
Referenced by ripple::OfferCreateTransactor::applyOffer(), ripple::RippleCalc::calcNodeDeliverFwd(), ripple::RippleCalc::calcNodeDeliverRev(), ripple::RippleCalc::calcNodeRipple(), ripple::core::Quality::ceil_in(), ripple::core::Quality::ceil_out(), divRound(), and ripple::STAmount_test::testRounding().
 {
     if (den == zero)
         throw std::runtime_error ("division by zero");
     if (num == zero)
         return STAmount (uCurrencyID, uIssuerID);
     std::uint64_t numVal = num.mValue, denVal = den.mValue;
     int numOffset = num.mOffset, denOffset = den.mOffset;
     if (num.mIsNative)
         while (numVal < STAmount::cMinValue)
         {
             // Need to bring into range
             numVal *= 10;
             --numOffset;
         }
     if (den.mIsNative)
         while (denVal < STAmount::cMinValue)
         {
             denVal *= 10;
             --denOffset;
         }
     bool resultNegative = num.mIsNegative != den.mIsNegative;
     // Compute (numerator * 10^17) / denominator
     CBigNum v;
     if ((BN_add_word64 (&v, numVal) != 1) || (BN_mul_word64 (&v, tenTo17) != 1))
         throw std::runtime_error ("internal bn error");
     if (resultNegative != roundUp) // Rounding down is automatic when we divide
         BN_add_word64 (&v, denVal - 1);
     if (BN_div_word64 (&v, denVal) == ((std::uint64_t) - 1))
         throw std::runtime_error ("internal bn error");
     // 10^16 <= quotient <= 10^18
     assert (BN_num_bytes (&v) <= 64);
     std::uint64_t amount = v.getuint64 ();
     int offset = numOffset - denOffset - 17;
     canonicalizeRound (uCurrencyID.isZero (), amount, offset, resultNegative != roundUp);
     return STAmount (uCurrencyID, uIssuerID, amount, offset, resultNegative);
 }
static STAmount ripple::STAmount::divRound (const STAmount & v1, const STAmount & v2, const STAmount & saUnit, bool roundUp) inline static
Definition at line 747 of file SerializedTypes.h.
References divRound(), getCurrency(), and getIssuer().
     {
         return divRound (v1, v2, saUnit.getCurrency (), saUnit.getIssuer (), roundUp);
     }
static STAmount ripple::STAmount::divRound (const STAmount & v1, const STAmount & v2, bool roundUp) inline static
Definition at line 751 of file SerializedTypes.h.
References divRound(), getCurrency(), and getIssuer().
     {
         return divRound (v1, v2, v1.getCurrency (), v1.getIssuer (), roundUp);
     }
STAmount* ripple::STAmount::duplicate () const inline private virtual
Reimplemented from ripple::SerializedType.
Definition at line 793 of file SerializedTypes.h.
References STAmount().
     {
         return new STAmount (*this);
     }
const uint160& ripple::STAmount::getCurrency () const inline
Definition at line 663 of file SerializedTypes.h.
References mCurrency.
Referenced by ripple::LedgerEntrySet::accountFunds(), ripple::Pathfinder::addLink(), ripple::OfferCreateTransactor::applyOffer(), ripple::RippleCalc::calcNodeAccountFwd(), ripple::RippleCalc::calcNodeAccountRev(), ripple::RippleCalc::calcNodeRipple(), ripple::PathState::checkNoRipple(), divide(), divRound(), ripple::RPCHandler::doAccountCurrencies(), ripple::PaymentTransactor::doApply(), ripple::OfferCreateTransactor::doApply(), ripple::RPCHandler::doRipplePathFind(), ripple::PathRequest::doUpdate(), ripple::Pathfinder::findPaths(), ripple::Pathfinder::getPathsOut(), getPay(), mulRound(), multiply(), ripple::PathRequest::parseJson(), ripple::Pathfinder::Pathfinder(), ripple::OrderBookDB::processTxn(), ripple::RippleCalc::rippleCalc(), ripple::LedgerEntrySet::rippleCredit(), ripple::LedgerEntrySet::rippleTransferFee(), ripple::PathState::setCanonical(), ripple::PathState::setExpanded(), ripple::OfferCreateTransactor::takeOffers(), ripple::RPC::transactionSign(), ripple::LedgerEntrySet::trustCreate(), ripple::usAccountDestCurrencies(), and ripple::usAccountSourceCurrencies().
     {
         return mCurrency;
     }
int ripple::STAmount::getExponent () const inline
Definition at line 568 of file SerializedTypes.h.
References mOffset.
Referenced by ripple::PaymentTransactor::doApply(), and getRate().
     {
         return mOffset;
     }
std::string ripple::STAmount::getFullText () const virtual
Reimplemented from ripple::SerializedType.
Definition at line 1090 of file STAmount.cpp.
References ACCOUNT_ONE, ripple::RippleAddress::createHumanAccountID(), getHumanCurrency(), getText(), mIsNative, and mIssuer.
Referenced by ripple::LedgerEntrySet::accountFunds(), ripple::LedgerEntrySet::accountHolds(), ripple::LedgerEntrySet::accountSend(), ripple::OfferCreateTransactor::applyOffer(), ripple::PaymentTransactor::doApply(), ripple::OfferCreateTransactor::doApply(), ripple::PathRequest::doCreate(), ripple::PathRequest::doUpdate(), ripple::Pathfinder::findPaths(), ripple::Offer::getJson(), ripple::OfferCreateTransactor::isValidOffer(), ripple::STAmount_test::mulTest(), ripple::LedgerEntrySet::rippleCredit(), ripple::LedgerEntrySet::rippleSend(), and ripple::OfferCreateTransactor::takeOffers().
 {
     std::string ret;
     ret.reserve(64);
     ret = getText () + "/" + getHumanCurrency ();
     if (!mIsNative)
     {
         ret += "/";
         if (!mIssuer)
             ret += "0";
         else if (mIssuer == ACCOUNT_ONE)
             ret += "1";
         else
             ret += RippleAddress::createHumanAccountID (mIssuer);
     }
     return ret;
 }
std::string ripple::STAmount::getHumanCurrency () const
Definition at line 91 of file STAmount.cpp.
References createHumanCurrency(), and mCurrency.
Referenced by ripple::RPCHandler::doAccountLines(), ripple::OfferCreateTransactor::doApply(), getFullText(), and setJson().
 {
     return createHumanCurrency (mCurrency);
 }
const uint160& ripple::STAmount::getIssuer () const inline
Definition at line 653 of file SerializedTypes.h.
References mIssuer.
Referenced by ripple::LedgerEntrySet::accountFunds(), ripple::OfferCreateTransactor::applyOffer(), ripple::RippleCalc::calcNodeAccountFwd(), ripple::RippleCalc::calcNodeAccountRev(), ripple::RippleCalc::calcNodeRipple(), divide(), divRound(), ripple::OfferCreateTransactor::doApply(), ripple::RPCHandler::doRipplePathFind(), ripple::TransactionMetaSet::getAffectedAccounts(), ripple::SerializedTransaction::getMentionedAccounts(), ripple::SerializedLedgerEntry::getOwners(), getPay(), mulRound(), multiply(), ripple::PathRequest::parseJson(), ripple::OrderBookDB::processTxn(), ripple::RippleCalc::rippleCalc(), ripple::LedgerEntrySet::rippleCredit(), ripple::LedgerEntrySet::rippleSend(), ripple::LedgerEntrySet::rippleTransferFee(), ripple::PathState::setCanonical(), ripple::PathState::setExpanded(), ripple::OfferCreateTransactor::takeOffers(), ripple::RPC::transactionSign(), and ripple::LedgerEntrySet::trustCreate().
     {
         return mIssuer;
     }
Json::Value ripple::STAmount::getJson (int) const virtual
Reimplemented from ripple::SerializedType.
Definition at line 1168 of file STAmount.cpp.
References setJson().
Referenced by ripple::RPCHandler::doRipplePathFind(), ripple::PathRequest::doUpdate(), and ripple::PathState::getJson().
 {
     Json::Value elem;
     setJson (elem);
     return elem;
 }
std::uint64_t ripple::STAmount::getMantissa () const inline
Definition at line 572 of file SerializedTypes.h.
References mValue.
Referenced by ripple::PaymentTransactor::doApply(), and getRate().
     {
         return mValue;
     }
std::uint64_t ripple::STAmount::getNValue () const inline
Definition at line 583 of file SerializedTypes.h.
References mIsNative, and mValue.
Referenced by ripple::TransactionEngine::applyTransaction(), ripple::TrustSetTransactor::doApply(), ripple::PaymentTransactor::doApply(), ripple::OfferCreateTransactor::doApply(), ripple::Script::Interpreter::interpret(), and ripple::STAmount_test::testSetValue().
     {
         if (!mIsNative) throw std::runtime_error ("not native");
         return mValue;
     }
STAmount ripple::STAmount::getPay (const STAmount & offerOut, const STAmount & offerIn, const STAmount & needed) static
Definition at line 1066 of file STAmount.cpp.
References ACCOUNT_ONE, CURRENCY_ONE, divide(), getCurrency(), getIssuer(), multiply(), and STAmount().
 {
     // Someone wants to get (needed) out of the offer, how much should they pay in?
     if (offerOut == zero)
         return STAmount (offerIn.getCurrency (), offerIn.getIssuer ());
     if (needed >= offerOut)
     {
         // They need more than offered, pay full amount.
         return needed;
     }
     STAmount ret = divide (multiply (needed, offerIn, CURRENCY_ONE, ACCOUNT_ONE), offerOut, offerIn.getCurrency (), offerIn.getIssuer ());
     return (ret > offerIn) ? offerIn : ret;
 }
std::uint64_t ripple::STAmount::getRate (const STAmount & offerOut, const STAmount & offerIn) static
Definition at line 1030 of file STAmount.cpp.
References ACCOUNT_ONE, CURRENCY_ONE, divide(), getExponent(), and getMantissa().
Referenced by ripple::RippleCalc::calcNodeRipple(), ripple::OfferCreateTransactor::doApply(), ripple::Pathfinder::filterPaths(), ripple::RippleCalc::pathNext(), ripple::RippleCalc::rippleCalc(), ripple::OfferCreateTransactor::takeOffers(), ripple::STAmount_test::testArithmetic(), ripple::STAmount_test::testCustomCurrency(), and ripple::STAmount_test::testUnderflow().
 {
     if (offerOut == zero)
         return 0;
     try
     {
         STAmount r = divide (offerIn, offerOut, CURRENCY_ONE, ACCOUNT_ONE);
         if (r == zero) // offer is too good
             return 0;
         assert ((r.getExponent () >= -100) && (r.getExponent () <= 155));
         std::uint64_t ret = r.getExponent () + 100;
         return (ret << (64 - 8)) | r.getMantissa ();
     }
     catch (...)
     {
         // overflow -- very bad offer
         return 0;
     }
 }
std::string ripple::STAmount::getRaw () const
Definition at line 611 of file STAmount.cpp.
References ripple::base_uint< BITS >::GetHex(), mCurrency, mIsNative, mIsNegative, mOffset, and mValue.
Referenced by ripple::STAmount_test::testCustomCurrency().
 {
     // show raw internal form
     if (mValue == 0) return "0";
     if (mIsNative)
     {
         if (mIsNegative) return std::string ("-") + beast::lexicalCast <std::string> (mValue);
         else return beast::lexicalCast <std::string> (mValue);
     }
     if (mIsNegative)
         return mCurrency.GetHex () + ": -" +
                beast::lexicalCast <std::string> (mValue) + "e" + beast::lexicalCast <std::string> (mOffset);
     else return mCurrency.GetHex () + ": " +
                     beast::lexicalCast <std::string> (mValue) + "e" + beast::lexicalCast <std::string> (mOffset);
 }
STAmount ripple::STAmount::getRound () const
Definition at line 1112 of file STAmount.cpp.
References mCurrency, mIsNative, mIsNegative, mIssuer, mOffset, mValue, and STAmount().
 {
     if (mIsNative)
         return *this;
     std::uint64_t valueDigits = mValue % 1000000000ull;
     if (valueDigits == 1)
         return STAmount (mCurrency, mIssuer, mValue - 1, mOffset, mIsNegative);
     else if (valueDigits == 999999999ull)
         return STAmount (mCurrency, mIssuer, mValue + 1, mOffset, mIsNegative);
     return *this;
 }
std::int64_t ripple::STAmount::getSNValue () const
Definition at line 585 of file STAmount.cpp.
References mIsNative, mIsNegative, and mValue.
Referenced by addRound(), mulRound(), multiply(), operator+(), ripple::operator+(), operator+=(), operator-(), ripple::operator-(), operator-=(), operator<(), operator<=(), operator>(), operator>=(), and subRound().
 {
     // signed native value
     if (!mIsNative) throw std::runtime_error ("not native");
     if (mIsNegative) return - static_cast<std::int64_t> (mValue);
     return static_cast<std::int64_t> (mValue);
 }
SerializedTypeID ripple::STAmount::getSType () const inline virtual
Reimplemented from ripple::SerializedType.
Definition at line 559 of file SerializedTypes.h.
     {
         return STI_AMOUNT;
     }
std::string ripple::STAmount::getText () const virtual
Reimplemented from ripple::SerializedType.
Definition at line 629 of file STAmount.cpp.
References mIsNative, mIsNegative, mOffset, and mValue.
Referenced by ripple::RPC::authorize(), ripple::RPCHandler::doAccountLines(), ripple::WalletAddTransactor::doApply(), ripple::PaymentTransactor::doApply(), ripple::NetworkOPsImp::getBookPage(), getFullText(), ripple::Transactor::payFee(), ripple::STAmount_test::roundTest(), setJson(), ripple::STAmount_test::testCustomCurrency(), and ripple::STAmount_test::testUnderflow().
 {
     // keep full internal accuracy, but make more human friendly if posible
     if (*this == zero)
         return "0";
     if (mIsNative)
     {
         if (mIsNegative)
             return std::string ("-") +  beast::lexicalCast <std::string> (mValue);
         else return beast::lexicalCast <std::string> (mValue);
     }
     if ((mOffset != 0) && ((mOffset < -25) || (mOffset > -5)))
     {
         if (mIsNegative)
             return std::string ("-") + beast::lexicalCast <std::string> (mValue) +
                    "e" + beast::lexicalCast <std::string> (mOffset);
         else
             return beast::lexicalCast <std::string> (mValue) + "e" + beast::lexicalCast <std::string> (mOffset);
     }
     std::string val = "000000000000000000000000000";
     val += beast::lexicalCast <std::string> (mValue);
     val += "00000000000000000000000";
     std::string pre = val.substr (0, mOffset + 43);
     std::string post = val.substr (mOffset + 43);
     size_t s_pre = pre.find_first_not_of ('0');
     if (s_pre == std::string::npos)
         pre = "0";
     else
         pre = pre.substr (s_pre);
     size_t s_post = post.find_last_not_of ('0');
     if (mIsNegative) pre = std::string ("-") + pre;
     if (s_post == std::string::npos)
         return pre;
     else
         return pre + "." + post.substr (0, s_post + 1);
 }
bool ripple::STAmount::isComparable (const STAmount & t) const
Definition at line 675 of file STAmount.cpp.
References mCurrency, and mIsNative.
Referenced by isEquivalent(), operator!=(), operator==(), and throwComparable().
 {
     // are these two STAmount instances in the same currency
     if (mIsNative) return t.mIsNative;
     if (t.mIsNative) return false;
     return mCurrency == t.mCurrency;
 }
virtual bool ripple::STAmount::isDefault () const inline virtual
Reimplemented from ripple::SerializedType.
Definition at line 672 of file SerializedTypes.h.
References ripple::base_uint< BITS >::isZero(), mCurrency, mIssuer, and mValue.
     {
         return (mValue == 0) && mIssuer.isZero () && mCurrency.isZero ();
     }
bool ripple::STAmount::isEquivalent (const SerializedType & t) const virtual
Reimplemented from ripple::SerializedType.
Definition at line 685 of file STAmount.cpp.
References isComparable(), mIsNegative, mOffset, and mValue.
 {
     const STAmount* v = dynamic_cast<const STAmount*> (&t);
     if (!v) return false;
     return isComparable (*v) && (mIsNegative == v->mIsNegative) && (mValue == v->mValue) && (mOffset == v->mOffset);
 }
bool ripple::STAmount::isLegalNet () const inline
Definition at line 604 of file SerializedTypes.h.
References cMaxNativeN, mIsNative, and mValue.
Referenced by ripple::PaymentTransactor::doApply(), ripple::OfferCreateTransactor::doApply(), and ripple::Transactor::payFee().
     {
         return !mIsNative || (mValue <= cMaxNativeN);
     }
bool ripple::STAmount::isNative () const inline
Definition at line 600 of file SerializedTypes.h.
References mIsNative.
Referenced by ripple::LedgerEntrySet::accountFunds(), ripple::LedgerEntrySet::accountSend(), ripple::Pathfinder::addLink(), ripple::PaymentTransactor::doApply(), ripple::OfferCreateTransactor::doApply(), ripple::PathRequest::isValid(), ripple::STAmount_test::mulTest(), ripple::Transactor::payFee(), ripple::STAmount_test::roundTest(), ripple::OfferCreateTransactor::takeOffers(), ripple::STAmount_test::testCustomCurrency(), ripple::STAmount_test::testNativeCurrency(), and ripple::RPC::transactionSign().
     {
         return mIsNative;
     }
bool ripple::STAmount::issuerFromString (uint160 & uDstIssuer, const std::string & sIssuer) static
Definition at line 26 of file STAmount.cpp.
References ripple::RippleAddress::getAccountID(), and ripple::RippleAddress::setAccountID().
Referenced by ripple::RPCHandler::doBookOffers(), ripple::RPCHandler::doRipplePathFind(), ripple::RPCHandler::doSubscribe(), ripple::RPCHandler::doUnsubscribe(), ripple::PathRequest::parseJson(), and STAmount().
 {
     bool    bSuccess    = true;
     if (sIssuer.size () == (160 / 4))
     {
         uDstIssuer.SetHex (sIssuer);
     }
     else
     {
         RippleAddress raIssuer;
         if (raIssuer.setAccountID (sIssuer))
         {
             uDstIssuer  = raIssuer.getAccountID ();
         }
         else
         {
             bSuccess    = false;
         }
     }
     return bSuccess;
 }
STAmount ripple::STAmount::mulRound (const STAmount & v1, const STAmount & v2, const uint160 & currency, const uint160 & issuer, bool roundUp) static
Definition at line 203 of file STAmountRound.cpp.
References ripple::BN_add_word64(), ripple::BN_div_word64(), ripple::BN_mul_word64(), canonicalizeRound(), cMinValue, ripple::SerializedType::getFName(), getSNValue(), ripple::CBigNum::getuint64(), ripple::base_uint< BITS >::isZero(), mIsNative, mIsNegative, mOffset, mValue, STAmount(), tenTo14, and tenTo14m1.
Referenced by ripple::OfferCreateTransactor::applyOffer(), ripple::RippleCalc::calcNodeAccountFwd(), ripple::RippleCalc::calcNodeDeliverFwd(), ripple::RippleCalc::calcNodeDeliverRev(), ripple::RippleCalc::calcNodeRipple(), ripple::core::Quality::ceil_in(), ripple::core::Quality::ceil_out(), mulRound(), and ripple::STAmount_test::testRounding().
 {
     if (v1 == zero || v2 == zero)
         return STAmount (uCurrencyID, uIssuerID);
     if (v1.mIsNative && v2.mIsNative && uCurrencyID.isZero ())
     {
         std::uint64_t minV = (v1.getSNValue () < v2.getSNValue ()) ? v1.getSNValue () : v2.getSNValue ();
         std::uint64_t maxV = (v1.getSNValue () < v2.getSNValue ()) ? v2.getSNValue () : v1.getSNValue ();
         if (minV > 3000000000ull) // sqrt(cMaxNative)
             throw std::runtime_error ("Native value overflow");
         if (((maxV >> 32) * minV) > 2095475792ull) // cMaxNative / 2^32
             throw std::runtime_error ("Native value overflow");
         return STAmount (v1.getFName (), minV * maxV);
     }
     std::uint64_t value1 = v1.mValue, value2 = v2.mValue;
     int offset1 = v1.mOffset, offset2 = v2.mOffset;
     if (v1.mIsNative)
     {
         while (value1 < STAmount::cMinValue)
         {
             value1 *= 10;
             --offset1;
         }
     }
     if (v2.mIsNative)
     {
         while (value2 < STAmount::cMinValue)
         {
             value2 *= 10;
             --offset2;
         }
     }
     bool resultNegative = v1.mIsNegative != v2.mIsNegative;
     // Compute (numerator * denominator) / 10^14 with rounding
     // 10^16 <= result <= 10^18
     CBigNum v;
     if ((BN_add_word64 (&v, value1) != 1) || (BN_mul_word64 (&v, value2) != 1))
         throw std::runtime_error ("internal bn error");
     if (resultNegative != roundUp) // rounding down is automatic when we divide
         BN_add_word64 (&v, tenTo14m1);
     if  (BN_div_word64 (&v, tenTo14) == ((std::uint64_t) - 1))
         throw std::runtime_error ("internal bn error");
     // 10^16 <= product <= 10^18
     assert (BN_num_bytes (&v) <= 64);
     std::uint64_t amount = v.getuint64 ();
     int offset = offset1 + offset2 + 14;
     canonicalizeRound (uCurrencyID.isZero (), amount, offset, resultNegative != roundUp);
     return STAmount (uCurrencyID, uIssuerID, amount, offset, resultNegative);
 }
static STAmount ripple::STAmount::mulRound (const STAmount & v1, const STAmount & v2, const STAmount & saUnit, bool roundUp) inline static
Definition at line 739 of file SerializedTypes.h.
References getCurrency(), getIssuer(), and mulRound().
     {
         return mulRound (v1, v2, saUnit.getCurrency (), saUnit.getIssuer (), roundUp);
     }
static STAmount ripple::STAmount::mulRound (const STAmount & v1, const STAmount & v2, bool roundUp) inline static
Definition at line 743 of file SerializedTypes.h.
References getCurrency(), getIssuer(), and mulRound().
     {
         return mulRound (v1, v2, v1.getCurrency (), v1.getIssuer (), roundUp);
     }
STAmount ripple::STAmount::multiply (const STAmount & v1, const STAmount & v2, const uint160 & uCurrencyID, const uint160 & uIssuerID) static
Definition at line 963 of file STAmount.cpp.
References ripple::BN_add_word64(), ripple::BN_div_word64(), ripple::BN_mul_word64(), cMinValue, ripple::SerializedType::getFName(), getSNValue(), ripple::CBigNum::getuint64(), ripple::base_uint< BITS >::isZero(), mIsNative, mIsNegative, mOffset, mValue, STAmount(), and tenTo14.
Referenced by ripple::NetworkOPsImp::getBookPage(), getPay(), ripple::STAmount_test::mulTest(), multiply(), ripple::LedgerEntrySet::rippleTransferFee(), ripple::STAmount_test::roundTest(), ripple::OfferCreateTransactor::takeOffers(), ripple::STAmount_test::testCustomCurrency(), ripple::STAmount_test::testRounding(), and ripple::STAmount_test::testUnderflow().
 {
     if (v1 == zero || v2 == zero)
         return STAmount (uCurrencyID, uIssuerID);
     if (v1.mIsNative && v2.mIsNative && uCurrencyID.isZero ())
     {
         std::uint64_t minV = (v1.getSNValue () < v2.getSNValue ()) ? v1.getSNValue () : v2.getSNValue ();
         std::uint64_t maxV = (v1.getSNValue () < v2.getSNValue ()) ? v2.getSNValue () : v1.getSNValue ();
         if (minV > 3000000000ull) // sqrt(cMaxNative)
             throw std::runtime_error ("Native value overflow");
         if (((maxV >> 32) * minV) > 2095475792ull) // cMaxNative / 2^32
             throw std::runtime_error ("Native value overflow");
         return STAmount (v1.getFName (), minV * maxV);
     }
     std::uint64_t value1 = v1.mValue, value2 = v2.mValue;
     int offset1 = v1.mOffset, offset2 = v2.mOffset;
     if (v1.mIsNative)
     {
         while (value1 < STAmount::cMinValue)
         {
             value1 *= 10;
             --offset1;
         }
     }
     if (v2.mIsNative)
     {
         while (value2 < STAmount::cMinValue)
         {
             value2 *= 10;
             --offset2;
         }
     }
     // Compute (numerator * denominator) / 10^14 with rounding
     // 10^16 <= result <= 10^18
     CBigNum v;
     if ((BN_add_word64 (&v, value1) != 1) ||
             (BN_mul_word64 (&v, value2) != 1) ||
             (BN_div_word64 (&v, tenTo14) == ((std::uint64_t) - 1)))
     {
         throw std::runtime_error ("internal bn error");
     }
     // 10^16 <= product <= 10^18
     assert (BN_num_bytes (&v) <= 64);
     return STAmount (uCurrencyID, uIssuerID, v.getuint64 () + 7, offset1 + offset2 + 14,
                      v1.mIsNegative != v2.mIsNegative);
 }
static STAmount ripple::STAmount::multiply (const STAmount & v1, const STAmount & v2, const STAmount & saUnit) inline static
Definition at line 717 of file SerializedTypes.h.
References getCurrency(), getIssuer(), and multiply().
     {
         return multiply (v1, v2, saUnit.getCurrency (), saUnit.getIssuer ());
     }
static STAmount ripple::STAmount::multiply (const STAmount & v1, const STAmount & v2) inline static
Definition at line 721 of file SerializedTypes.h.
References multiply().
     {
         return multiply (v1, v2, v1);
     }
void ripple::STAmount::negate () inline
Definition at line 615 of file SerializedTypes.h.
References mIsNegative.
Referenced by ripple::RPCHandler::doRipplePathFind(), ripple::PathRequest::doUpdate(), ripple::LedgerEntrySet::rippleCredit(), ripple::LedgerEntrySet::rippleHolds(), ripple::LedgerEntrySet::rippleOwed(), and ripple::RippleState::setViewAccount().
     {
         if (*this != zero)
             mIsNegative = !mIsNegative;
     }
ripple::STAmount::operator bool () const inline explicit noexcept
Definition at line 610 of file SerializedTypes.h.
     {
         return *this != zero;
     }
ripple::STAmount::operator double () const
Definition at line 818 of file STAmount.cpp.
 {
     // Does not keep the precise value. Not recommended
     if (!mValue)
         return 0.0;
     if (mIsNegative) return -1.0 * static_cast<double> (mValue) * pow (10.0, mOffset);
     return static_cast<double> (mValue) * pow (10.0, mOffset);
 }
bool ripple::STAmount::operator!= (const STAmount & a) const
Definition at line 706 of file STAmount.cpp.
References isComparable(), mIsNegative, mOffset, and mValue.
 {
     return (mOffset != a.mOffset) || (mValue != a.mValue) || (mIsNegative != a.mIsNegative) || !isComparable (a);
 }
STAmount ripple::STAmount::operator+ (std::uint64_t v) const
Definition at line 808 of file STAmount.cpp.
References ripple::SerializedType::getFName(), getSNValue(), and STAmount().
 {
     return STAmount (getFName (), getSNValue () + static_cast<std::int64_t> (v));
 }
STAmount & ripple::STAmount::operator+= (const STAmount & a)
Definition at line 735 of file STAmount.cpp.
 {
     *this = *this + a;
     return *this;
 }
STAmount & ripple::STAmount::operator+= (std::uint64_t v)
Definition at line 766 of file STAmount.cpp.
References getSNValue(), mIsNative, and setSNValue().
 {
     assert (mIsNative);
     if (!mIsNative)
         throw std::runtime_error ("not native");
     setSNValue (getSNValue () + static_cast<std::int64_t> (v));
     return *this;
 }
STAmount ripple::STAmount::operator- (std::uint64_t v) const
Definition at line 813 of file STAmount.cpp.
References ripple::SerializedType::getFName(), getSNValue(), and STAmount().
 {
     return STAmount (getFName (), getSNValue () - static_cast<std::int64_t> (v));
 }
STAmount ripple::STAmount::operator- (void) const
Definition at line 747 of file STAmount.cpp.
References ripple::SerializedType::getFName(), mCurrency, mIsNative, mIsNegative, mIssuer, mOffset, mValue, and STAmount().
 {
     if (mValue == 0) return *this;
     return STAmount (getFName (), mCurrency, mIssuer, mValue, mOffset, mIsNative, !mIsNegative);
 }
STAmount & ripple::STAmount::operator-= (const STAmount & a)
Definition at line 741 of file STAmount.cpp.
 {
     *this = *this - a;
     return *this;
 }
STAmount & ripple::STAmount::operator-= (std::uint64_t v)
Definition at line 777 of file STAmount.cpp.
References getSNValue(), mIsNative, and setSNValue().
 {
     assert (mIsNative);
     if (!mIsNative)
         throw std::runtime_error ("not native");
     setSNValue (getSNValue () - static_cast<std::int64_t> (v));
     return *this;
 }
bool ripple::STAmount::operator< (const STAmount & a) const
Definition at line 711 of file STAmount.cpp.
References compare(), and throwComparable().
 {
     throwComparable (a);
     return compare (a) < 0;
 }
bool ripple::STAmount::operator< (std::uint64_t v) const
Definition at line 788 of file STAmount.cpp.
References getSNValue().
 {
     return getSNValue () < static_cast<std::int64_t> (v);
 }
bool ripple::STAmount::operator<= (const STAmount & a) const
Definition at line 723 of file STAmount.cpp.
References compare(), and throwComparable().
 {
     throwComparable (a);
     return compare (a) <= 0;
 }
bool ripple::STAmount::operator<= (std::uint64_t v) const
Definition at line 798 of file STAmount.cpp.
References getSNValue().
 {
     return getSNValue () <= static_cast<std::int64_t> (v);
 }
STAmount& ripple::STAmount::operator= (beast::Zero) inline
Definition at line 645 of file SerializedTypes.h.
References clear().
     {
         clear ();
         return *this;
     }
STAmount & ripple::STAmount::operator= (std::uint64_t v)
Definition at line 754 of file STAmount.cpp.
References canonicalize(), mIsNative, mIsNegative, mOffset, and mValue.
 {
     // does not copy name, does not change currency type
     mOffset = 0;
     mValue = v;
     mIsNegative = false;
     if (!mIsNative) canonicalize ();
     return *this;
 }
bool ripple::STAmount::operator== (const STAmount & a) const
Definition at line 701 of file STAmount.cpp.
References isComparable(), mIsNegative, mOffset, and mValue.
 {
     return isComparable (a) && (mIsNegative == a.mIsNegative) && (mOffset == a.mOffset) && (mValue == a.mValue);
 }
bool ripple::STAmount::operator> (const STAmount & a) const
Definition at line 717 of file STAmount.cpp.
References compare(), and throwComparable().
 {
     throwComparable (a);
     return compare (a) > 0;
 }
bool ripple::STAmount::operator> (std::uint64_t v) const
Definition at line 793 of file STAmount.cpp.
References getSNValue().
 {
     return getSNValue () > static_cast<std::int64_t> (v);
 }
bool ripple::STAmount::operator>= (const STAmount & a) const
Definition at line 729 of file STAmount.cpp.
References compare(), and throwComparable().
 {
     throwComparable (a);
     return compare (a) >= 0;
 }
bool ripple::STAmount::operator>= (std::uint64_t v) const
Definition at line 803 of file STAmount.cpp.
References getSNValue().
 {
     return getSNValue () >= static_cast<std::int64_t> (v);
 }
void ripple::STAmount::roundSelf ()
Definition at line 1127 of file STAmount.cpp.
References canonicalize(), cMaxValue, cMinValue, mIsNative, and mValue.
Referenced by ripple::STAmount_test::roundTest().
 {
     if (mIsNative)
         return;
     std::uint64_t valueDigits = mValue % 1000000000ull;
     if (valueDigits == 1)
     {
         mValue -= 1;
         if (mValue < cMinValue)
             canonicalize ();
     }
     else if (valueDigits == 999999999ull)
     {
         mValue += 1;
         if (mValue > cMaxValue)
             canonicalize ();
     }
 }
static STAmount ripple::STAmount::saFromRate (std::uint64_t uRate = 0) inline static
Definition at line 554 of file SerializedTypes.h.
References ACCOUNT_ONE, CURRENCY_ONE, and STAmount().
Referenced by ripple::RippleCalc::calcNodeAccountRev(), ripple::RippleCalc::calcNodeRev(), ripple::core::Taker::fill(), and ripple::RippleCalc::rippleCalc().
     {
         return STAmount (CURRENCY_ONE, ACCOUNT_ONE, uRate, -9, false);
     }
void ripple::STAmount::set (std::int64_t v) inline private
Definition at line 807 of file SerializedTypes.h.
References mIsNegative, and mValue.
Referenced by STAmount().
     {
         if (v < 0)
         {
             mIsNegative = true;
             mValue = static_cast<std::uint64_t> (-v);
         }
         else
         {
             mIsNegative = false;
             mValue = static_cast<std::uint64_t> (v);
         }
     }
void ripple::STAmount::set (int v) inline private
Definition at line 821 of file SerializedTypes.h.
References mIsNegative, and mValue.
     {
         if (v < 0)
         {
             mIsNegative = true;
             mValue = static_cast<std::uint64_t> (-v);
         }
         else
         {
             mIsNegative = false;
             mValue = static_cast<std::uint64_t> (v);
         }
     }
bool ripple::STAmount::setFullValue (const std::string & sAmount, const std::string & sCurrency = "", const std::string & sIssuer = "")
Definition at line 360 of file STAmount.cpp.
References currencyFromString(), ripple::RippleAddress::getAccountID(), ripple::base_uint< BITS >::isZero(), ripple::lsINFO, mCurrency, mIsNative, mIssuer, ripple::RippleAddress::setAccountID(), setValue(), and WriteLog.
Referenced by ripple::STAmount_test::testSetValue().
 {
     //
     // Figure out the currency.
     //
     if (!currencyFromString (mCurrency, sCurrency))
     {
         WriteLog (lsINFO, STAmount) << "Currency malformed: " << sCurrency;
         return false;
     }
     mIsNative   = !mCurrency;
     //
     // Figure out the issuer.
     //
     RippleAddress   naIssuerID;
     // Issuer must be "" or a valid account string.
     if (!naIssuerID.setAccountID (sIssuer))
     {
         WriteLog (lsINFO, STAmount) << "Issuer malformed: " << sIssuer;
         return false;
     }
     mIssuer = naIssuerID.getAccountID ();
     // Stamps not must have an issuer.
     if (mIsNative && !mIssuer.isZero ())
     {
         WriteLog (lsINFO, STAmount) << "Issuer specified for XRP: " << sIssuer;
         return false;
     }
     return setValue (sAmount);
 }
STAmount* ripple::STAmount::setIssuer (const uint160 & uIssuer) inline
Definition at line 657 of file SerializedTypes.h.
References mIssuer.
Referenced by ripple::TrustSetTransactor::doApply(), ripple::LedgerEntrySet::rippleCredit(), ripple::LedgerEntrySet::rippleHolds(), ripple::LedgerEntrySet::rippleLimit(), ripple::LedgerEntrySet::rippleOwed(), ripple::LedgerEntrySet::rippleSend(), and ripple::RPC::transactionSign().
     {
         mIssuer   = uIssuer;
         return this;
     }
void ripple::STAmount::setJson (Json::Value & elem) const
Definition at line 1150 of file STAmount.cpp.
References ripple::RippleAddress::createHumanAccountID(), getHumanCurrency(), getText(), mIsNative, mIssuer, and Json::objectValue.
Referenced by ripple::NetworkOPsImp::getBookPage(), and getJson().
 {
     elem = Json::objectValue;
     if (!mIsNative)
     {
         // It is an error for currency or issuer not to be specified for valid json.
         elem["value"]       = getText ();
         elem["currency"]    = getHumanCurrency ();
         elem["issuer"]      = RippleAddress::createHumanAccountID (mIssuer);
     }
     else
     {
         elem = getText ();
     }
 }
void ripple::STAmount::setNValue (std::uint64_t v) inline
Definition at line 589 of file SerializedTypes.h.
References mIsNative, and mValue.
     {
         if (!mIsNative) throw std::runtime_error ("not native");
         mValue = v;
     }
STAmount ripple::STAmount::setRate (std::uint64_t rate) static
Definition at line 1055 of file STAmount.cpp.
References ACCOUNT_ONE, CURRENCY_ONE, and STAmount().
Referenced by ripple::RippleCalc::calcNodeAdvance(), ripple::NetworkOPsImp::getBookPage(), ripple::BookDirIterator::getCurrentRate(), ripple::core::Quality::rate(), ripple::OfferCreateTransactor::takeOffers(), and ripple::STAmount_test::testCustomCurrency().
 {
     if (rate == 0)
         return STAmount (CURRENCY_ONE, ACCOUNT_ONE);
     std::uint64_t mantissa = rate & ~ (255ull << (64 - 8));
     int exponent = static_cast<int> (rate >> (64 - 8)) - 100;
     return STAmount (CURRENCY_ONE, ACCOUNT_ONE, mantissa, exponent);
 }
void ripple::STAmount::setSNValue (std::int64_t v)
Definition at line 595 of file STAmount.cpp.
References mIsNative, mIsNegative, and mValue.
Referenced by operator+=(), and operator-=().
 {
     if (!mIsNative) throw std::runtime_error ("not native");
     if (v > 0)
     {
         mIsNegative = false;
         mValue = static_cast<std::uint64_t> (v);
     }
     else
     {
         mIsNegative = true;
         mValue = static_cast<std::uint64_t> (-v);
     }
 }
bool ripple::STAmount::setValue (const std::string & sAmount)
Definition at line 276 of file STAmount.cpp.
References canonicalize(), ripple::lsTRACE, ripple::lsWARNING, mIsNative, mIsNegative, mOffset, mValue, SYSTEM_CURRENCY_PRECISION, and WriteLog.
Referenced by setFullValue(), and STAmount().
 {
     // Note: mIsNative and mCurrency must be set already!
     static boost::regex reNumber ("\\`([+-]?)(\\d*)(\\.(\\d*))?([eE]([+-]?)(\\d+))?\\'");
     boost::smatch smMatch;
     if (!boost::regex_match (sAmount, smMatch, reNumber))
     {
         WriteLog (lsWARNING, STAmount) << "Number not valid: \"" << sAmount << "\"";
         return false;
     }
     // Match fields: 0 = whole input, 1 = sign, 2 = integer portion, 3 = whole fraction (with '.')
     // 4 = fraction (without '.'), 5 = whole exponent (with 'e'), 6 = exponent sign, 7 = exponent number
     try
     {
         if ((smMatch[2].length () + smMatch[4].length ()) > 32)
         {
             WriteLog (lsWARNING, STAmount) << "Overlong number: " << sAmount;
             return false;
         }
         mIsNegative = (smMatch[1].matched && (smMatch[1] == "-"));
         if (!smMatch[4].matched) // integer only
         {
             mValue = beast::lexicalCast <std::uint64_t> (std::string (smMatch[2]));
             mOffset = 0;
         }
         else
         {
             // integer and fraction
             mValue = beast::lexicalCast <std::uint64_t> (smMatch[2] + smMatch[4]);
             mOffset = - (smMatch[4].length ());
         }
         if (smMatch[5].matched)
         {
             // we have an exponent
             if (smMatch[6].matched && (smMatch[6] == "-"))
                 mOffset -= beast::lexicalCast <int> (std::string (smMatch[7]));
             else
                 mOffset += beast::lexicalCast <int> (std::string (smMatch[7]));
         }
     }
     catch (...)
     {
         WriteLog (lsWARNING, STAmount) << "Number not parsed: \"" << sAmount << "\"";
         return false;
     }
     WriteLog (lsTRACE, STAmount) << "Float \"" << sAmount << "\" parsed to " << mValue << " : " << mOffset;
     if (mIsNative)
     {
         if (smMatch[3].matched)
             mOffset -= SYSTEM_CURRENCY_PRECISION;
         while (mOffset > 0)
         {
             mValue  *= 10;
             --mOffset;
         }
         while (mOffset < 0)
         {
             mValue  /= 10;
             ++mOffset;
         }
     }
     else
         canonicalize ();
     return true;
 }
void ripple::STAmount::setValue (const STAmount & a)
Definition at line 508 of file STAmount.cpp.
References mCurrency, mIsNative, mIsNegative, mIssuer, mOffset, and mValue.
 {
     mCurrency   = a.mCurrency;
     mIssuer     = a.mIssuer;
     mValue      = a.mValue;
     mOffset     = a.mOffset;
     mIsNative   = a.mIsNative;
     mIsNegative = a.mIsNegative;
 }
int ripple::STAmount::signum () const inline
Definition at line 577 of file SerializedTypes.h.
References mIsNegative, and mValue.
     {
         return mValue ? (mIsNegative ? -1 : 1) : 0;
     }
STAmount ripple::STAmount::subRound (const STAmount & v1, const STAmount & v2, bool roundUp) static
Definition at line 133 of file STAmountRound.cpp.
References canonicalizeRound(), ripple::SerializedType::getFName(), getSNValue(), mCurrency, mIsNative, mIsNegative, mIssuer, mOffset, mValue, STAmount(), and throwComparable().
 {
     v1.throwComparable (v2);
     if (v2.mValue == 0)
         return v1;
     if (v1.mValue == 0)
         return STAmount (v1.getFName (), v1.mCurrency, v1.mIssuer, v2.mValue, v2.mOffset, !v2.mIsNegative);
     if (v1.mIsNative)
         return STAmount (v1.getFName (), v1.getSNValue () - v2.getSNValue ());
     int ov1 = v1.mOffset, ov2 = v2.mOffset;
     std::int64_t vv1 = static_cast<std::int64_t> (v1.mValue), vv2 = static_cast<std::uint64_t> (v2.mValue);
     if (v1.mIsNegative)
         vv1 = -vv1;
     if (!v2.mIsNegative)
         vv2 = -vv2;
     if (ov1 < ov2)
     {
         while (ov1 < (ov2 - 1))
         {
             vv1 /= 10;
             ++ov1;
         }
         if (roundUp)
             vv1 += 9;
         vv1 /= 10;
         ++ov1;
     }
     if (ov2 < ov1)
     {
         while (ov2 < (ov1 - 1))
         {
             vv2 /= 10;
             ++ov2;
         }
         if (roundUp)
             vv2 += 9;
         vv2 /= 10;
         ++ov2;
     }
     std::int64_t fv = vv1 + vv2;
     if ((fv >= -10) && (fv <= 10))
         return STAmount (v1.getFName (), v1.mCurrency, v1.mIssuer);
     else if (fv >= 0)
     {
         std::uint64_t v = static_cast<std::uint64_t> (fv);
         canonicalizeRound (false, v, ov1, roundUp);
         return STAmount (v1.getFName (), v1.mCurrency, v1.mIssuer, v, ov1, false);
     }
     else
     {
         std::uint64_t v = static_cast<std::uint64_t> (-fv);
         canonicalizeRound (false, v, ov1, !roundUp);
         return STAmount (v1.getFName (), v1.mCurrency, v1.mIssuer, v, ov1, true);
     }
 }
void ripple::STAmount::throwComparable (const STAmount & t) const
Definition at line 694 of file STAmount.cpp.
References isComparable().
Referenced by addRound(), ripple::OfferCreateTransactor::applyOffer(), ripple::operator+(), ripple::operator-(), operator<(), operator<=(), operator>(), operator>=(), ripple::STAmount_test::roundTest(), and subRound().
 {
     // throw an exception if these two STAmount instances are incomparable
     if (!isComparable (t))
         throw std::runtime_error ("amounts are not comparable");
 }
Friends And Related Function Documentation
STAmount operator+ (const STAmount & v1, const STAmount & v2) friend
Definition at line 829 of file STAmount.cpp.
 {
     v1.throwComparable (v2);
     if (v2 == zero)
         return v1;
     if (v1 == zero)
     {
         // Result must be in terms of v1 currency and issuer.
         return STAmount (v1.getFName (), v1.mCurrency, v1.mIssuer, v2.mValue, v2.mOffset, v2.mIsNegative);
     }
     if (v1.mIsNative)
         return STAmount (v1.getFName (), v1.getSNValue () + v2.getSNValue ());
     int ov1 = v1.mOffset, ov2 = v2.mOffset;
     std::int64_t vv1 = static_cast<std::int64_t> (v1.mValue), vv2 = static_cast<std::int64_t> (v2.mValue);
     if (v1.mIsNegative) vv1 = -vv1;
     if (v2.mIsNegative) vv2 = -vv2;
     while (ov1 < ov2)
     {
         vv1 /= 10;
         ++ov1;
     }
     while (ov2 < ov1)
     {
         vv2 /= 10;
         ++ov2;
     }
     // this addition cannot overflow an std::int64_t, it can overflow an STAmount and the constructor will throw
     std::int64_t fv = vv1 + vv2;
     if ((fv >= -10) && (fv <= 10))
         return STAmount (v1.getFName (), v1.mCurrency, v1.mIssuer);
     else if (fv >= 0)
         return STAmount (v1.getFName (), v1.mCurrency, v1.mIssuer, fv, ov1, false);
     else
         return STAmount (v1.getFName (), v1.mCurrency, v1.mIssuer, -fv, ov1, true);
 }
STAmount operator- (const STAmount & v1, const STAmount & v2) friend
Definition at line 876 of file STAmount.cpp.
 {
     v1.throwComparable (v2);
     if (v2 == zero)
         return v1;
     if (v2.mIsNative)
     {
         // XXX This could be better, check for overflow and that maximum range is covered.
         return STAmount::createFromInt64 (v1.getFName (), v1.getSNValue () - v2.getSNValue ());
     }
     int ov1 = v1.mOffset, ov2 = v2.mOffset;
     std::int64_t vv1 = static_cast<std::int64_t> (v1.mValue), vv2 = static_cast<std::int64_t> (v2.mValue);
     if (v1.mIsNegative) vv1 = -vv1;
     if (v2.mIsNegative) vv2 = -vv2;
     while (ov1 < ov2)
     {
         vv1 /= 10;
         ++ov1;
     }
     while (ov2 < ov1)
     {
         vv2 /= 10;
         ++ov2;
     }
     // this subtraction cannot overflow an std::int64_t, it can overflow an STAmount and the constructor will throw
     std::int64_t fv = vv1 - vv2;
     if ((fv >= -10) && (fv <= 10))
         return STAmount (v1.getFName (), v1.mCurrency, v1.mIssuer);
     else if (fv >= 0)
         return STAmount (v1.getFName (), v1.mCurrency, v1.mIssuer, fv, ov1, false);
     else
         return STAmount (v1.getFName (), v1.mCurrency, v1.mIssuer, -fv, ov1, true);
 }
Member Data Documentation
const std::uint64_t ripple::STAmount::cMaxNative = 9000000000000000000ull static
Definition at line 471 of file SerializedTypes.h.
Referenced by canonicalize(), and ripple::STAmount_test::testUnderflow().
const std::uint64_t ripple::STAmount::cMaxNativeN = 100000000000000000ull static
Definition at line 472 of file SerializedTypes.h.
Referenced by isLegalNet().
const int ripple::STAmount::cMaxOffset = 80 static
Definition at line 469 of file SerializedTypes.h.
Referenced by canonicalize(), construct(), and ripple::STAmount_test::testUnderflow().
const std::uint64_t ripple::STAmount::cMaxValue = 9999999999999999ull static
Definition at line 470 of file SerializedTypes.h.
Referenced by canonicalize(), canonicalizeRound(), construct(), roundSelf(), and ripple::STAmount_test::testUnderflow().
const int ripple::STAmount::cMinOffset = -96 static
Definition at line 469 of file SerializedTypes.h.
Referenced by canonicalize(), construct(), and ripple::STAmount_test::testUnderflow().
const std::uint64_t ripple::STAmount::cMinValue = 1000000000000000ull static
Definition at line 470 of file SerializedTypes.h.
Referenced by canonicalize(), construct(), divide(), divRound(), mulRound(), multiply(), roundSelf(), and ripple::STAmount_test::testUnderflow().
const std::uint64_t ripple::STAmount::cNotNative = 0x8000000000000000ull static
Definition at line 473 of file SerializedTypes.h.
Referenced by add(), and construct().
const std::uint64_t ripple::STAmount::cPosNative = 0x4000000000000000ull static
Definition at line 474 of file SerializedTypes.h.
Referenced by add(), and construct().
uint160 ripple::STAmount::mCurrency private
Definition at line 784 of file SerializedTypes.h.
Referenced by add(), addRound(), canonicalize(), clear(), getCurrency(), getHumanCurrency(), getRaw(), getRound(), isComparable(), isDefault(), ripple::operator+(), operator-(), ripple::operator-(), setFullValue(), setValue(), STAmount(), and subRound().
bool ripple::STAmount::mIsNative private
Definition at line 789 of file SerializedTypes.h.
Referenced by add(), addRound(), canonicalize(), clear(), divide(), divRound(), getFullText(), getNValue(), getRaw(), getRound(), getSNValue(), getText(), isComparable(), isLegalNet(), isNative(), mulRound(), multiply(), ripple::operator+(), operator+=(), operator-(), ripple::operator-(), operator-=(), operator=(), roundSelf(), setFullValue(), setJson(), setNValue(), setSNValue(), setValue(), STAmount(), and subRound().
bool ripple::STAmount::mIsNegative private
Definition at line 790 of file SerializedTypes.h.
Referenced by add(), addRound(), canonicalize(), clear(), compare(), divide(), divRound(), getRaw(), getRound(), getSNValue(), getText(), isEquivalent(), mulRound(), multiply(), negate(), operator!=(), ripple::operator+(), operator-(), ripple::operator-(), operator=(), operator==(), set(), setSNValue(), setValue(), signum(), STAmount(), and subRound().
uint160 ripple::STAmount::mIssuer private
Definition at line 785 of file SerializedTypes.h.
Referenced by add(), addRound(), clear(), getFullText(), getIssuer(), getRound(), isDefault(), ripple::operator+(), operator-(), ripple::operator-(), setFullValue(), setIssuer(), setJson(), setValue(), STAmount(), and subRound().
int ripple::STAmount::mOffset private
Definition at line 788 of file SerializedTypes.h.
Referenced by add(), addRound(), canonicalize(), clear(), compare(), divide(), divRound(), getExponent(), getRaw(), getRound(), getText(), isEquivalent(), mulRound(), multiply(), operator!=(), ripple::operator+(), operator-(), ripple::operator-(), operator=(), operator==(), setValue(), and subRound().
std::uint64_t ripple::STAmount::mValue private
Definition at line 787 of file SerializedTypes.h.
Referenced by add(), addRound(), canonicalize(), clear(), compare(), divide(), divRound(), getMantissa(), getNValue(), getRaw(), getRound(), getSNValue(), getText(), isDefault(), isEquivalent(), isLegalNet(), mulRound(), multiply(), operator!=(), ripple::operator+(), operator-(), ripple::operator-(), operator=(), operator==(), roundSelf(), set(), setNValue(), setSNValue(), setValue(), signum(), STAmount(), and subRound().
std::uint64_t ripple::STAmount::uRateOne = STAmount::getRate (STAmount (1), STAmount (1)) static
Definition at line 476 of file SerializedTypes.h.
Referenced by ripple::RippleCalc::calcNodeAccountRev(), and ripple::RippleCalc::calcNodeRipple().
The documentation for this class was generated from the following files:
rippled/src/ripple_data/protocol/SerializedTypes.h
rippled/src/ripple_data/protocol/STAmount.cpp
rippled/src/ripple_data/protocol/STAmountRound.cpp