rippled: beast::sqdb::transaction Class Reference
beast::sqdb::transaction Class Reference
#include <transaction.h>
Public Member Functions
transaction (session &s)
~transaction ()
transaction & operator= (transaction const &)=delete
Error commit ()
void rollback ()
Private Attributes
session & m_session
bool m_bHandled
Detailed Description
Definition at line 68 of file transaction.h.
Constructor & Destructor Documentation
beast::sqdb::transaction::transaction (session & s) explicit
Definition at line 65 of file transaction.cpp.
References beast::sqdb::session::begin(), and m_session.
     : m_session(s), m_bHandled(false)
 {
     m_session.begin();
 }
beast::sqdb::transaction::~transaction ()
Definition at line 71 of file transaction.cpp.
References m_bHandled, and rollback().
 {
     if (!m_bHandled)
         rollback();
 }
Member Function Documentation
Error beast::sqdb::transaction::commit ()
Definition at line 77 of file transaction.cpp.
References beast::sqdb::session::commit(), m_bHandled, and m_session.
Referenced by ripple::Validators::StoreSqdb::init(), ripple::PeerFinder::StoreSqdb::init(), ripple::Validators::StoreSqdb::insert(), ripple::PeerFinder::StoreSqdb::save(), ripple::Validators::StoreSqdb::update(), and ripple::PeerFinder::StoreSqdb::update().
 {
     Error error;
     // already handled
     assert (!m_bHandled);
     // if commit() throws, m_bHandled will remain false
     // and the destructor will attempt a rollback.
     m_bHandled = true;
     error = m_session.commit();
     return error;
 }
transaction& beast::sqdb::transaction::operator= (transaction const &) delete
void beast::sqdb::transaction::rollback ()
Definition at line 94 of file transaction.cpp.
References m_bHandled, m_session, and beast::sqdb::session::rollback().
Referenced by ripple::Validators::StoreSqdb::init(), ripple::PeerFinder::StoreSqdb::init(), ripple::Validators::StoreSqdb::insert(), ripple::PeerFinder::StoreSqdb::save(), ripple::Validators::StoreSqdb::update(), ripple::PeerFinder::StoreSqdb::update(), and ~transaction().
 {
     // already handled
     assert (!m_bHandled);
     m_session.rollback();
     m_bHandled = true;
 }
Member Data Documentation
bool beast::sqdb::transaction::m_bHandled private
Definition at line 79 of file transaction.h.
Referenced by commit(), rollback(), and ~transaction().
session& beast::sqdb::transaction::m_session private
Definition at line 78 of file transaction.h.
Referenced by commit(), rollback(), and transaction().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_sqdb/api/transaction.h
rippled/src/beast/modules/beast_sqdb/source/transaction.cpp