rippled: ripple::STHash128 Class Reference
ripple::STHash128 Class Reference
#include <SerializedTypes.h>
Public Member Functions
STHash128 (const uint128 &v)
STHash128 (SField::ref n, const uint128 &v)
STHash128 (SField::ref n, const char *v)
STHash128 (SField::ref n, const std::string &v)
STHash128 (SField::ref n)
STHash128 ()
SerializedTypeID getSType () const
virtual std::string getText () const
void add (Serializer &s) const
const uint128 & getValue () const
void setValue (const uint128 &v)
operator uint128 () const
virtual bool isEquivalent (const SerializedType &t) const
virtual bool isDefault () const
Public Member Functions inherited from ripple::SerializedType
SerializedType ()
SerializedType (SField::ref n)
virtual ~SerializedType ()
void setFName (SField::ref n)
SField::ref getFName () const
std::string getName () const
std::unique_ptr< SerializedType > clone () const
virtual std::string getFullText () const
virtual Json::Value getJson (int) const
void addFieldID (Serializer &s) const
SerializedType & operator= (const SerializedType &t)
bool operator== (const SerializedType &t) const
bool operator!= (const SerializedType &t) const
template<class D >
D & downcast ()
template<class D >
D const & downcast () const
Static Public Member Functions
static std::unique_ptr
< SerializedType > deserialize (SerializerIterator &sit, SField::ref name)
Static Public Member Functions inherited from ripple::SerializedType
static std::unique_ptr
< SerializedType > deserialize (SField::ref name)
Private Member Functions
STHash128 * duplicate () const
Static Private Member Functions
static STHash128 * construct (SerializerIterator &, SField::ref name)
Private Attributes
uint128 value
Additional Inherited Members
Protected Attributes inherited from ripple::SerializedType
SField::ptr fName
Detailed Description
Definition at line 842 of file SerializedTypes.h.
Constructor & Destructor Documentation
ripple::STHash128::STHash128 (const uint128 & v) inline
Definition at line 845 of file SerializedTypes.h.
                                  : value (v)
     {
         ;
     }
ripple::STHash128::STHash128 (SField::ref n, const uint128 & v) inline
Definition at line 849 of file SerializedTypes.h.
                                               : SerializedType (n), value (v)
     {
         ;
     }
ripple::STHash128::STHash128 (SField::ref n, const char * v) inline
Definition at line 853 of file SerializedTypes.h.
References ripple::base_uint< BITS >::SetHex(), and value.
                                            : SerializedType (n)
     {
         value.SetHex (v);
     }
ripple::STHash128::STHash128 (SField::ref n, const std::string & v) inline
Definition at line 857 of file SerializedTypes.h.
References ripple::base_uint< BITS >::SetHex(), and value.
                                                 : SerializedType (n)
     {
         value.SetHex (v);
     }
ripple::STHash128::STHash128 (SField::ref n) inline
Definition at line 861 of file SerializedTypes.h.
                             : SerializedType (n)
     {
         ;
     }
ripple::STHash128::STHash128 () inline
Definition at line 865 of file SerializedTypes.h.
Referenced by construct(), and duplicate().
     {
         ;
     }
Member Function Documentation
void ripple::STHash128::add (Serializer & s) const inline virtual
Reimplemented from ripple::SerializedType.
Definition at line 879 of file SerializedTypes.h.
References ripple::Serializer::add128(), and value.
     {
         s.add128 (value);
     }
STHash128 * ripple::STHash128::construct (SerializerIterator & u, SField::ref name) static private
Definition at line 239 of file SerializedTypes.cpp.
References ripple::SerializerIterator::get128(), and STHash128().
Referenced by deserialize().
 {
     return new STHash128 (name, u.get128 ());
 }
static std::unique_ptr<SerializedType> ripple::STHash128::deserialize (SerializerIterator & sit, SField::ref name) inline static
Definition at line 869 of file SerializedTypes.h.
References construct().
Referenced by ripple::STObject::makeDeserializedObject().
     {
         return std::unique_ptr<SerializedType> (construct (sit, name));
     }
STHash128* ripple::STHash128::duplicate () const inline private virtual
Reimplemented from ripple::SerializedType.
Definition at line 906 of file SerializedTypes.h.
References STHash128().
     {
         return new STHash128 (*this);
     }
SerializedTypeID ripple::STHash128::getSType () const inline virtual
Reimplemented from ripple::SerializedType.
Definition at line 874 of file SerializedTypes.h.
     {
         return STI_HASH128;
     }
std::string ripple::STHash128::getText () const virtual
Reimplemented from ripple::SerializedType.
Definition at line 244 of file SerializedTypes.cpp.
References ripple::base_uint< BITS >::GetHex(), and value.
 {
     return value.GetHex ();
 }
const uint128& ripple::STHash128::getValue () const inline
Definition at line 884 of file SerializedTypes.h.
References value.
Referenced by ripple::STObject::getFieldH128().
     {
         return value;
     }
virtual bool ripple::STHash128::isDefault () const inline virtual
Reimplemented from ripple::SerializedType.
Definition at line 898 of file SerializedTypes.h.
References ripple::base_uint< BITS >::isZero(), and value.
     {
         return value.isZero ();
     }
bool ripple::STHash128::isEquivalent (const SerializedType & t) const virtual
Reimplemented from ripple::SerializedType.
Definition at line 249 of file SerializedTypes.cpp.
References value.
 {
     const STHash128* v = dynamic_cast<const STHash128*> (&t);
     return v && (value == v->value);
 }
ripple::STHash128::operator uint128 () const inline
Definition at line 893 of file SerializedTypes.h.
References value.
     {
         return value;
     }
void ripple::STHash128::setValue (const uint128 & v) inline
Definition at line 888 of file SerializedTypes.h.
References value.
Referenced by ripple::STObject::setFieldH128().
     {
         value = v;
     }
Member Data Documentation
uint128 ripple::STHash128::value private
Definition at line 904 of file SerializedTypes.h.
Referenced by add(), getText(), getValue(), isDefault(), isEquivalent(), operator uint128(), setValue(), and STHash128().
The documentation for this class was generated from the following files:
rippled/src/ripple_data/protocol/SerializedTypes.h
rippled/src/ripple_data/protocol/SerializedTypes.cpp