rippled: beast::unit_test::results Class Reference
beast::unit_test::results Class Reference
#include <results.h>
Public Member Functions
results ()
std::size_t cases () const
std::size_t total () const
std::size_t failed () const
void insert (suite_results &&r)
void insert (suite_results const &r)
Public Member Functions inherited from beast::const_container< std::vector< suite_results > >
bool empty () const
size_type size () const
const_iterator begin () const
const_iterator cbegin () const
const_iterator end () const
const_iterator cend () const
Private Attributes
std::size_t m_cases
std::size_t m_total
std::size_t m_failed
Additional Inherited Members
Public Types inherited from beast::const_container< std::vector< suite_results > >
typedef cont_type::value_type value_type
typedef cont_type::size_type size_type
typedef cont_type::difference_type difference_type
typedef cont_type::const_iterator iterator
typedef cont_type::const_iterator const_iterator
Protected Member Functions inherited from beast::const_container< std::vector< suite_results > >
cont_type & cont ()
cont_type const & cont () const
Detailed Description
Holds the results of running a set of testsuites.
Definition at line 194 of file results.h.
Constructor & Destructor Documentation
beast::unit_test::results::results () inline
Definition at line 203 of file results.h.
         : m_cases (0)
         , m_total (0)
         , m_failed (0)
     {
     }
Member Function Documentation
std::size_t beast::unit_test::results::cases () const inline
Returns the total number of test cases.
Definition at line 212 of file results.h.
References m_cases.
     {
         return m_cases;
     }
std::size_t beast::unit_test::results::failed () const inline
Returns the number of failures.
Definition at line 226 of file results.h.
References m_failed.
     {
         return m_failed;
     }
void beast::unit_test::results::insert (suite_results && r) inline
Insert a set of suite results.
Definition at line 234 of file results.h.
References beast::const_container< std::vector< suite_results > >::cont(), m_cases, m_failed, and m_total.
Referenced by beast::unit_test::recorder::on_suite_end().
     {
         m_cases += r.size();
         m_total += r.total();
         m_failed += r.failed();
         cont().emplace_back (std::move (r));
     }
void beast::unit_test::results::insert (suite_results const & r) inline
Definition at line 243 of file results.h.
References beast::const_container< std::vector< suite_results > >::cont(), beast::unit_test::suite_results::failed(), m_cases, m_failed, m_total, beast::const_container< Container >::size(), and beast::unit_test::suite_results::total().
     {
         m_cases += r.size();
         m_total += r.total();
         m_failed += r.failed();
         cont().push_back (r);
     }
std::size_t beast::unit_test::results::total () const inline
Returns the total number of test conditions.
Definition at line 219 of file results.h.
References m_total.
     {
         return m_total;
     }
Member Data Documentation
std::size_t beast::unit_test::results::m_cases private
Definition at line 198 of file results.h.
Referenced by cases(), and insert().
std::size_t beast::unit_test::results::m_failed private
Definition at line 200 of file results.h.
Referenced by failed(), and insert().
std::size_t beast::unit_test::results::m_total private
Definition at line 199 of file results.h.
Referenced by insert(), and total().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/unit_test/results.h