rippled: ripple::RandomNumbers Class Reference
ripple::RandomNumbers Class Reference
#include <RandomNumbers.h>
Public Member Functions
bool initialize (beast::Journal::Stream stream=beast::Journal::Stream())
void fillBytes (void *destinationBuffer, int numberOfBytes)
template<class T >
void fill (T *object)
Static Public Member Functions
static RandomNumbers & getInstance ()
Private Member Functions
RandomNumbers ()
~RandomNumbers ()
bool platformAddEntropy (beast::Journal::Stream stream)
void platformAddPerformanceMonitorEntropy ()
Private Attributes
bool m_initialized
Detailed Description
Cryptographically secure random number source.
Definition at line 29 of file RandomNumbers.h.
Constructor & Destructor Documentation
ripple::RandomNumbers::RandomNumbers () private
Definition at line 41 of file RandomNumbers.cpp.
     : m_initialized (false)
 {
 }
ripple::RandomNumbers::~RandomNumbers () private
Definition at line 46 of file RandomNumbers.cpp.
 {
 }
Member Function Documentation
template<class T > void ripple::RandomNumbers::fill (T * object) inline
Generate secure random numbers.
The generated data is suitable for cryptography.
Fills the memory for the object with random numbers. This is a type-safe alternative to the function above.
Parameters
object A pointer to the object to fill.
Template Parameters
T The type of object
Note
Undefined behavior results if T is not a POD type.
Definition at line 72 of file RandomNumbers.h.
References fillBytes(), and T.
Referenced by ripple::HashMaps::NonceHolder< T >::NonceHolder(), ripple::SNTPClientImp::resolveComplete(), and ripple::ProofOfWork::solve().
     {
         fillBytes (object, sizeof (T));
     }
void ripple::RandomNumbers::fillBytes (void * destinationBuffer, int numberOfBytes)
Generate secure random numbers.
The generated data is suitable for cryptography.
Invariant
The destination buffer must be large enough or undefined behavior results.
Parameters
destinationBuffer The place to store the bytes.
numberOfBytes The number of bytes to generate.
Definition at line 62 of file RandomNumbers.cpp.
References initialize(), and m_initialized.
Referenced by ripple::checkECIES(), ripple::RPCHandler::doRandom(), ripple::CKey::encryptECIES(), fill(), ripple::ProofOfWorkFactoryImp::getProof(), ripple::ProofOfWorkFactoryImp::ProofOfWorkFactoryImp(), ripple::RippleAddress::setSeedRandom(), and ripple::NetworkOPsImp::subServer().
 {
     // VFALCO NOTE this assert is here to remind us that the code is not yet
     //         thread safe.
     assert (m_initialized);
     // VFALCO NOTE When a spinlock is available in beast, use it here.
     if (! m_initialized)
     {
         if (! initialize ())
         {
             char const* message = "Unable to add system entropy";
             throw std::runtime_error (message);
         }
     }
 #ifdef PURIFY
     memset (destinationBuffer, 0, numberOfBytes);
 #endif
     if (RAND_bytes (reinterpret_cast <unsigned char*> (destinationBuffer), numberOfBytes) != 1)
     {
         assert (false);
         throw std::runtime_error ("Entropy pool not seeded");
     }
 }
RandomNumbers & ripple::RandomNumbers::getInstance (void) static
Retrieve the instance of the generator.
Definition at line 90 of file RandomNumbers.cpp.
References instance.
Referenced by ripple::checkECIES(), ripple::RPCHandler::doRandom(), ripple::CKey::encryptECIES(), ripple::ProofOfWorkFactoryImp::getProof(), ripple::HashMaps::NonceHolder< T >::NonceHolder(), ripple::ProofOfWorkFactoryImp::ProofOfWorkFactoryImp(), ripple::SNTPClientImp::resolveComplete(), ripple::run(), ripple::RippleAddress::setSeedRandom(), ripple::ProofOfWork::solve(), and ripple::NetworkOPsImp::subServer().
 {
     static RandomNumbers instance;
     return instance;
 }
bool ripple::RandomNumbers::initialize (beast::Journal::Stream stream = beast::Journal::Stream())
Initialize the generator.
If the generator is not manually initialized, it will be automatically initialized on first use. If automatic initialization fails, an exception is thrown.
Returns
true if enough entropy could be retrieved.
Definition at line 50 of file RandomNumbers.cpp.
References m_initialized, and platformAddEntropy().
Referenced by fillBytes().
 {
     assert (!m_initialized);
     bool success = platformAddEntropy (stream);
     if (success)
         m_initialized = true;
     return success;
 }
bool ripple::RandomNumbers::platformAddEntropy (beast::Journal::Stream stream) private
Definition at line 135 of file RandomNumbers.cpp.
References Json::in().
Referenced by initialize().
 {
     char rand[128];
     std::ifstream reader;
     reader.open ("/dev/urandom", std::ios::in | std::ios::binary);
     if (!reader.is_open ())
     {
 #ifdef BEAST_DEBUG
         stream << "Unable to open random source";
 #endif
         return false;
     }
     reader.read (rand, 128);
     int bytesRead = reader.gcount ();
     if (bytesRead == 0)
     {
 #ifdef BEAST_DEBUG
         stream << "Unable to read from random source";
 #endif
         return false;
     }
     RAND_seed (rand, bytesRead);
     return bytesRead >= 64;
 }
void ripple::RandomNumbers::platformAddPerformanceMonitorEntropy () private
Definition at line 178 of file RandomNumbers.cpp.
 {
     // VFALCO TODO Remove all this fancy stuff
     struct
     {
         std::int64_t operator () () const
         {
             return time (nullptr);
         }
     } GetTime;
     struct
     {
         void operator () ()
         {
             struct
             {
                 // VFALCO TODO clean this up
                 std::int64_t operator () () const
                 {
                     std::int64_t nCounter = 0;
 #if BEAST_WIN32
                     QueryPerformanceCounter ((LARGE_INTEGER*)&nCounter);
 #else
                     timeval t;
                     gettimeofday (&t, nullptr);
                     nCounter = t.tv_sec * 1000000 + t.tv_usec;
 #endif
                     return nCounter;
                 }
             } GetPerformanceCounter;
             // Seed with CPU performance counter
             std::int64_t nCounter = GetPerformanceCounter ();
             RAND_add (&nCounter, sizeof (nCounter), 1.5);
             memset (&nCounter, 0, sizeof (nCounter));
         }
     } RandAddSeed;
     RandAddSeed ();
     // This can take up to 2 seconds, so only do it every 10 minutes
     static std::int64_t nLastPerfmon;
     if (GetTime () < nLastPerfmon + 10 * 60)
         return;
     nLastPerfmon = GetTime ();
 #if BEAST_WIN32
     // Don't need this on Linux, OpenSSL automatically uses /dev/urandom
     // Seed with the entire set of perfmon data
     unsigned char pdata[250000];
     memset (pdata, 0, sizeof (pdata));
     unsigned long nSize = sizeof (pdata);
     long ret = RegQueryValueExA (HKEY_PERFORMANCE_DATA, "Global", nullptr, nullptr, pdata, &nSize);
     RegCloseKey (HKEY_PERFORMANCE_DATA);
     if (ret == ERROR_SUCCESS)
     {
         RAND_add (pdata, nSize, nSize / 100.0);
         memset (pdata, 0, nSize);
         //printf("%s RandAddSeed() %d bytes\n", DateTimeStrFormat("%x %H:%M", GetTime()).c_str(), nSize);
     }
 #endif
 }
Member Data Documentation
bool ripple::RandomNumbers::m_initialized private
Definition at line 87 of file RandomNumbers.h.
Referenced by fillBytes(), and initialize().
The documentation for this class was generated from the following files:
rippled/src/ripple/types/api/RandomNumbers.h
rippled/src/ripple/types/impl/RandomNumbers.cpp