rippled: ripple::NodeStore::BatchWriter Class Reference
ripple::NodeStore::BatchWriter Class Reference
#include <BatchWriter.h>
Classes
struct Callback
Public Member Functions
BatchWriter (Callback &callback, Scheduler &scheduler)
~BatchWriter ()
void store (NodeObject::Ptr const &object)
int getWriteLoad ()
Private Types
typedef std::recursive_mutex LockType
typedef std::condition_variable_any CondvarType
Private Member Functions
void performScheduledTask ()
void writeBatch ()
void waitForWriting ()
Private Member Functions inherited from ripple::NodeStore::Task
virtual ~Task ()=0
Private Attributes
Callback & m_callback
Scheduler & m_scheduler
LockType mWriteMutex
CondvarType mWriteCondition
int mWriteLoad
bool mWritePending
Batch mWriteSet
Detailed Description
Batch-writing assist logic.
The batch writes are performed with a scheduled task. Use of the class it not required. A backend can implement its own write batching, or skip write batching if doing so yields a performance benefit.
See Also
Scheduler
Definition at line 41 of file BatchWriter.h.
Member Typedef Documentation
typedef std::condition_variable_any ripple::NodeStore::BatchWriter::CondvarType private
Definition at line 76 of file BatchWriter.h.
typedef std::recursive_mutex ripple::NodeStore::BatchWriter::LockType private
Definition at line 75 of file BatchWriter.h.
Constructor & Destructor Documentation
ripple::NodeStore::BatchWriter::BatchWriter (Callback & callback, Scheduler & scheduler)
Create a batch writer.
Definition at line 23 of file BatchWriter.cpp.
References ripple::NodeStore::batchWritePreallocationSize, and mWriteSet.
     : m_callback (callback)
     , m_scheduler (scheduler)
     , mWriteLoad (0)
     , mWritePending (false)
 {
     mWriteSet.reserve (batchWritePreallocationSize);
 }
ripple::NodeStore::BatchWriter::~BatchWriter ()
Destroy a batch writer.
Anything pending in the batch is written out before this returns.
Definition at line 32 of file BatchWriter.cpp.
References waitForWriting().
 {
     waitForWriting ();
 }
Member Function Documentation
int ripple::NodeStore::BatchWriter::getWriteLoad ()
Get an estimate of the amount of writing I/O pending.
Definition at line 51 of file BatchWriter.cpp.
References ripple::max(), mWriteLoad, mWriteMutex, and mWriteSet.
Referenced by ripple::NodeStore::LevelDBBackend::getWriteLoad().
 {
     std::lock_guard<decltype(mWriteMutex)> sl (mWriteMutex);
     return std::max (mWriteLoad, static_cast<int> (mWriteSet.size ()));
 }
void ripple::NodeStore::BatchWriter::performScheduledTask () private virtual
Performs the task. The call may take place on a foreign thread.
Implements ripple::NodeStore::Task.
Definition at line 58 of file BatchWriter.cpp.
References writeBatch().
 {
     writeBatch ();
 }
void ripple::NodeStore::BatchWriter::store (NodeObject::Ptr const & object)
Store the object.
This will add to the batch and initiate a scheduled task to write the batch out.
Definition at line 37 of file BatchWriter.cpp.
References m_scheduler, mWriteMutex, mWritePending, mWriteSet, and ripple::NodeStore::Scheduler::scheduleTask().
Referenced by ripple::NodeStore::LevelDBBackend::store().
 {
     std::lock_guard<decltype(mWriteMutex)> sl (mWriteMutex);
     mWriteSet.push_back (object);
     if (! mWritePending)
     {
         mWritePending = true;
         m_scheduler.scheduleTask (*this);
     }
 }
void ripple::NodeStore::BatchWriter::waitForWriting () private
Definition at line 93 of file BatchWriter.cpp.
References mWriteCondition, mWriteMutex, and mWritePending.
Referenced by ~BatchWriter().
 {
     std::unique_lock <decltype(mWriteMutex)> sl (mWriteMutex);
     while (mWritePending)
         mWriteCondition.wait (sl);
 }
void ripple::NodeStore::BatchWriter::writeBatch () private
Definition at line 63 of file BatchWriter.cpp.
References ripple::NodeStore::batchWritePreallocationSize, m_callback, mWriteCondition, mWriteLoad, mWriteMutex, mWritePending, mWriteSet, and ripple::NodeStore::BatchWriter::Callback::writeBatch().
Referenced by performScheduledTask().
 {
     for (;;)
     {
         std::vector< boost::shared_ptr<NodeObject> > set;
         set.reserve (batchWritePreallocationSize);
         {
             std::lock_guard<decltype(mWriteMutex)> sl (mWriteMutex);
             mWriteSet.swap (set);
             assert (mWriteSet.empty ());
             mWriteLoad = set.size ();
             if (set.empty ())
             {
                 mWritePending = false;
                 mWriteCondition.notify_all ();
                 // VFALCO NOTE Fix this function to not return from the middle
                 return;
             }
         }
         m_callback.writeBatch (set);
     }
 }
Member Data Documentation
Callback& ripple::NodeStore::BatchWriter::m_callback private
Definition at line 78 of file BatchWriter.h.
Referenced by writeBatch().
Scheduler& ripple::NodeStore::BatchWriter::m_scheduler private
Definition at line 79 of file BatchWriter.h.
Referenced by store().
CondvarType ripple::NodeStore::BatchWriter::mWriteCondition private
Definition at line 81 of file BatchWriter.h.
Referenced by waitForWriting(), and writeBatch().
int ripple::NodeStore::BatchWriter::mWriteLoad private
Definition at line 82 of file BatchWriter.h.
Referenced by getWriteLoad(), and writeBatch().
LockType ripple::NodeStore::BatchWriter::mWriteMutex private
Definition at line 80 of file BatchWriter.h.
Referenced by getWriteLoad(), store(), waitForWriting(), and writeBatch().
bool ripple::NodeStore::BatchWriter::mWritePending private
Definition at line 83 of file BatchWriter.h.
Referenced by store(), waitForWriting(), and writeBatch().
Batch ripple::NodeStore::BatchWriter::mWriteSet private
Definition at line 84 of file BatchWriter.h.
Referenced by BatchWriter(), getWriteLoad(), store(), and writeBatch().
The documentation for this class was generated from the following files:
rippled/src/ripple_core/nodestore/impl/BatchWriter.h
rippled/src/ripple_core/nodestore/impl/BatchWriter.cpp