rippled: rocksdb::SstFileReader Class Reference
rocksdb::SstFileReader Class Reference
Public Member Functions
SstFileReader (const std::string &file_name, bool verify_checksum, bool output_hex)
Status ReadSequential (bool print_kv, uint64_t read_num, bool has_from, const std::string &from_key, bool has_to, const std::string &to_key)
uint64_t GetReadNumber ()
Private Attributes
std::string file_name_
uint64_t read_num_
bool verify_checksum_
bool output_hex_
EnvOptions soptions_
Detailed Description
Definition at line 28 of file sst_dump.cc.
Constructor & Destructor Documentation
rocksdb::SstFileReader::SstFileReader (const std::string & file_name, bool verify_checksum, bool output_hex) explicit
Definition at line 51 of file sst_dump.cc.
  :file_name_(file_path), read_num_(0), verify_checksum_(verify_checksum),
   output_hex_(output_hex) {
   std::cout << "Process " << file_path << "\n";
 }
Member Function Documentation
uint64_t rocksdb::SstFileReader::GetReadNumber () inline
Definition at line 41 of file sst_dump.cc.
References read_num_.
Referenced by main().
 { return read_num_; }
Status rocksdb::SstFileReader::ReadSequential (bool print_kv, uint64_t read_num, bool has_from, const std::string & from_key, bool has_to, const std::string & to_key)
Definition at line 59 of file sst_dump.cc.
References rocksdb::BytewiseComparator(), rocksdb::Options::comparator, rocksdb::ParsedInternalKey::DebugString(), rocksdb::InternalKey::Encode(), rocksdb::Options::env, file_name_, rocksdb::Env::GetFileSize(), rocksdb::Iterator::key(), rocksdb::kMaxSequenceNumber, rocksdb::kValueTypeForSeek, rocksdb::Env::NewRandomAccessFile(), rocksdb::Iterator::Next(), rocksdb::Status::ok(), output_hex_, rocksdb::ParseInternalKey(), read_num_, rocksdb::Iterator::Seek(), rocksdb::Iterator::SeekToFirst(), soptions_, rocksdb::Iterator::status(), rocksdb::Options::table_factory, rocksdb::Slice::ToString(), rocksdb::ParsedInternalKey::user_key, rocksdb::Iterator::Valid(), rocksdb::Iterator::value(), value, and verify_checksum_.
Referenced by main().
 {
   unique_ptr<TableReader> table_reader;
   InternalKeyComparator internal_comparator_(BytewiseComparator());
   Options table_options;
   table_options.comparator = &internal_comparator_;
   unique_ptr<RandomAccessFile> file;
   Status s = table_options.env->NewRandomAccessFile(file_name_, &file,
                                                     soptions_);
   if(!s.ok()) {
    return s;
   }
   uint64_t file_size;
   table_options.env->GetFileSize(file_name_, &file_size);
   unique_ptr<TableFactory> table_factory;
   s = table_options.table_factory->GetTableReader(table_options, soptions_,
                                                   std::move(file), file_size,
                                                   &table_reader);
   if(!s.ok()) {
    return s;
   }
   Iterator* iter = table_reader->NewIterator(ReadOptions(verify_checksum_,
                                                          false));
   uint64_t i = 0;
   if (has_from) {
     InternalKey ikey(from_key, kMaxSequenceNumber, kValueTypeForSeek);
     iter->Seek(ikey.Encode());
   } else {
     iter->SeekToFirst();
   }
   for (; iter->Valid(); iter->Next()) {
     Slice key = iter->key();
     Slice value = iter->value();
     ++i;
     if (read_num > 0 && i > read_num)
       break;
     ParsedInternalKey ikey;
     if (!ParseInternalKey(key, &ikey)) {
       std::cerr << "Internal Key ["
                 << key.ToString(true /* in hex*/)
                 << "] parse error!\n";
       continue;
     }
     // If end marker was specified, we stop before it
     if (has_to && BytewiseComparator()->Compare(ikey.user_key, to_key) >= 0) {
       break;
     }
     if (print_kv) {
       std::cout << ikey.DebugString(output_hex_)
                 << " => "
                 << value.ToString(output_hex_) << "\n";
     }
    }
    read_num_ += i;
    Status ret = iter->status();
    delete iter;
    return ret;
 }
Member Data Documentation
std::string rocksdb::SstFileReader::file_name_ private
Definition at line 44 of file sst_dump.cc.
Referenced by ReadSequential().
bool rocksdb::SstFileReader::output_hex_ private
Definition at line 47 of file sst_dump.cc.
Referenced by ReadSequential().
uint64_t rocksdb::SstFileReader::read_num_ private
Definition at line 45 of file sst_dump.cc.
Referenced by GetReadNumber(), and ReadSequential().
EnvOptions rocksdb::SstFileReader::soptions_ private
Definition at line 48 of file sst_dump.cc.
Referenced by ReadSequential().
bool rocksdb::SstFileReader::verify_checksum_ private
Definition at line 46 of file sst_dump.cc.
Referenced by ReadSequential().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/tools/sst_dump.cc