rippled: ripple::Resource::Manager Class Reference
ripple::Resource::Manager Class Reference abstract
#include <Manager.h>
Public Member Functions
virtual ~Manager ()=0
virtual Consumer newInboundEndpoint (beast::IP::Endpoint const &address)=0
virtual Consumer newOutboundEndpoint (beast::IP::Endpoint const &address)=0
virtual Consumer newAdminEndpoint (std::string const &name)=0
virtual Gossip exportConsumers ()=0
virtual Json::Value getJson ()=0
virtual Json::Value getJson (int threshold)=0
virtual void importConsumers (std::string const &origin, Gossip const &gossip)=0
Public Member Functions inherited from beast::PropertyStream::Source
Source (std::string const &name)
~Source ()
std::string const & name () const
void add (Source &source)
template<class Derived >
Derived * add (Derived *child)
void remove (Source &child)
void removeAll ()
void write_one (PropertyStream &stream)
void write (PropertyStream &stream)
void write (PropertyStream &stream, std::string const &path)
std::pair< Source *, bool > find (std::string path)
Source * find_one_deep (std::string const &name)
PropertyStream::Source * find_path (std::string path)
PropertyStream::Source * find_one (std::string const &name)
virtual void onWrite (Map &)
Protected Member Functions
Manager ()
Additional Inherited Members
Static Public Member Functions inherited from beast::PropertyStream::Source
static bool peel_leading_slash (std::string *path)
static bool peel_trailing_slashstar (std::string *path)
static std::string peel_name (std::string *path)
Detailed Description
Tracks load and resource consumption.
Definition at line 34 of file Manager.h.
Constructor & Destructor Documentation
ripple::Resource::Manager::Manager () protected
Definition at line 106 of file Manager.cpp.
     : beast::PropertyStream::Source ("resource")
 {
 }
ripple::Resource::Manager::~Manager () pure virtual
Definition at line 111 of file Manager.cpp.
 {
 }
Member Function Documentation
virtual Gossip ripple::Resource::Manager::exportConsumers () pure virtual
Extract packaged consumer information for export.
Implemented in ripple::Resource::ManagerImp.
Referenced by ripple::NetworkOPsImp::processClusterTimer().
virtual Json::Value ripple::Resource::Manager::getJson () pure virtual
Extract consumer information for reporting.
Implemented in ripple::Resource::ManagerImp.
Referenced by ripple::RPCHandler::doBlackList().
virtual Json::Value ripple::Resource::Manager::getJson (int threshold) pure virtual
Implemented in ripple::Resource::ManagerImp.
virtual void ripple::Resource::Manager::importConsumers (std::string const & origin, Gossip const & gossip) pure virtual
Import packaged consumer information.
Parameters
origin An identifier that unique labels the origin.
Implemented in ripple::Resource::ManagerImp.
Referenced by ripple::PeerImp::recvCluster().
virtual Consumer ripple::Resource::Manager::newAdminEndpoint (std::string const & name) pure virtual
Create a new endpoint keyed by name.
Implemented in ripple::Resource::ManagerImp.
Referenced by ripple::RPCServerHandler::processRequest(), and ripple::RPCHTTPServerImp::processRequest().
virtual Consumer ripple::Resource::Manager::newInboundEndpoint (beast::IP::Endpoint const & address) pure virtual
Create a new endpoint keyed by inbound IP address.
Implemented in ripple::Resource::ManagerImp.
Referenced by ripple::PeerImp::handleStart(), ripple::RPCServerHandler::processRequest(), and ripple::RPCHTTPServerImp::processRequest().
virtual Consumer ripple::Resource::Manager::newOutboundEndpoint (beast::IP::Endpoint const & address) pure virtual
Create a new endpoint keyed by outbound IP address and port.
Implemented in ripple::Resource::ManagerImp.
Referenced by ripple::PeerImp::handleStart().
The documentation for this class was generated from the following files:
rippled/src/ripple/resource/api/Manager.h
rippled/src/ripple/resource/impl/Manager.cpp