rippled: ripple::ProofOfWork_test Class Reference
ripple::ProofOfWork_test Class Reference
Public Member Functions
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 362 of file ProofOfWorkFactory.cpp.
Member Function Documentation
void ripple::ProofOfWork_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 365 of file ProofOfWorkFactory.cpp.
References beast::unit_test::suite::expect(), ripple::ProofOfWork::getDifficulty(), ripple::ProofOfWork::getToken(), ripple::base_uint< BITS >::isZero(), ripple::lsINFO, ripple::powBADNONCE, ripple::powOK, ripple::powREUSED, ripple::ProofOfWork::solve(), and WriteLog.
     {
         using namespace ripple;
         ProofOfWorkFactoryImp gen;
         ProofOfWork pow = gen.getProof ();
         beast::String s;
         s << "solve difficulty " << beast::String (pow.getDifficulty ());
         uint256 solution = pow.solve (16777216);
         expect (! solution.isZero (), "Should be solved");
         expect (pow.checkSolution (solution), "Should be checked");
         // Why is this emitted?
         //WriteLog (lsDEBUG, ProofOfWork) << "A bad nonce error is expected";
         PowResult r = gen.checkProof (pow.getToken (), uint256 ());
         expect (r == powBADNONCE, "Should show bad nonce for empty solution");
         expect (gen.checkProof (pow.getToken (), solution) == powOK, "Solution should check with issuer");
         //WriteLog (lsDEBUG, ProofOfWork) << "A reused nonce error is expected";
         expect (gen.checkProof (pow.getToken (), solution) == powREUSED, "Reuse solution should be detected");
     #ifdef SOLVE_POWS
         for (int i = 0; i < 12; ++i)
         {
             gen.setDifficulty (i);
             ProofOfWork pow = gen.getProof ();
             WriteLog (lsINFO, ProofOfWork) << "Level: " << i << ", Estimated difficulty: " << pow.getDifficulty ();
             uint256 solution = pow.solve (131072);
             if (solution.isZero ())
             {
                 //WriteLog (lsINFO, ProofOfWork) << "Giving up";
             }
             else
             {
                 //WriteLog (lsINFO, ProofOfWork) << "Solution found";
                 if (gen.checkProof (pow.getToken (), solution) != powOK)
                 {
                     //WriteLog (lsFATAL, ProofOfWork) << "Solution fails";
                 }
             }
         }
     #endif
     }
The documentation for this class was generated from the following file:
rippled/src/ripple_app/misc/ProofOfWorkFactory.cpp