rippled: ripple::RPC::LegacyPathFind Class Reference
ripple::RPC::LegacyPathFind Class Reference
#include <LegacyPathFind.h>
Public Member Functions
LegacyPathFind (bool isAdmin)
~LegacyPathFind ()
bool isOkay () const
Private Attributes
bool m_isOkay
Static Private Attributes
static std::atomic< int > inProgress
static int maxInProgress
Detailed Description
Definition at line 26 of file LegacyPathFind.h.
Constructor & Destructor Documentation
ripple::RPC::LegacyPathFind::LegacyPathFind (bool isAdmin)
Definition at line 25 of file LegacyPathFind.cpp.
References ripple::getApp(), inProgress, ripple::jtCLIENT, m_isOkay, and maxInProgress.
                                             : m_isOkay (false)
 {
     if (isAdmin)
         ++inProgress;
     else
     {
         if ((getApp().getJobQueue ().getJobCountGE (jtCLIENT) > 50) ||
                 getApp().getFeeTrack().isLoadedLocal ())
         return;
         do
         {
             int prevVal = inProgress.load();
             if (prevVal >= maxInProgress)
                 return;
             if (inProgress.compare_exchange_strong (prevVal, prevVal + 1,
                 std::memory_order_release, std::memory_order_relaxed))
             break;
         }
         while (1);
     }
     m_isOkay = true;
 }
ripple::RPC::LegacyPathFind::~LegacyPathFind ()
Definition at line 51 of file LegacyPathFind.cpp.
References inProgress, and m_isOkay.
 {
     if (m_isOkay)
         --inProgress;
 }
Member Function Documentation
bool ripple::RPC::LegacyPathFind::isOkay () const inline
Definition at line 32 of file LegacyPathFind.h.
References m_isOkay.
Referenced by ripple::RPCHandler::doRipplePathFind(), and ripple::RPC::transactionSign().
     {
         return m_isOkay;
     }
Member Data Documentation
std::atomic< int > ripple::RPC::LegacyPathFind::inProgress static private
Definition at line 38 of file LegacyPathFind.h.
Referenced by LegacyPathFind(), and ~LegacyPathFind().
bool ripple::RPC::LegacyPathFind::m_isOkay private
Definition at line 41 of file LegacyPathFind.h.
Referenced by isOkay(), LegacyPathFind(), and ~LegacyPathFind().
int ripple::RPC::LegacyPathFind::maxInProgress static private
Definition at line 39 of file LegacyPathFind.h.
Referenced by LegacyPathFind().
The documentation for this class was generated from the following files:
rippled/src/ripple_rpc/impl/LegacyPathFind.h
rippled/src/ripple_rpc/impl/LegacyPathFind.cpp