rippled: ripple::PeerFinder::Bootcache Class Reference
ripple::PeerFinder::Bootcache Class Reference
#include <Bootcache.h>
Classes
class Entry
struct Transform
Public Types
typedef
boost::transform_iterator
< Transform,
map_type::right_map::const_iterator > iterator
typedef iterator const_iterator
Public Member Functions
Bootcache (Store &store, clock_type &clock, beast::Journal journal)
~Bootcache ()
bool empty () const
map_type::size_type size () const
void load ()
bool insert (beast::IP::Endpoint const &endpoint)
void on_success (beast::IP::Endpoint const &endpoint)
void on_failure (beast::IP::Endpoint const &endpoint)
void periodicActivity ()
void onWrite (beast::PropertyStream::Map &map)
const_iterator begin () const
const_iterator cbegin () const
const_iterator end () const
const_iterator cend () const
void clear ()
Private Types
typedef
boost::bimaps::unordered_set_of
< beast::IP::Endpoint > left_t
typedef
boost::bimaps::multiset_of
< Entry > right_t
typedef boost::bimap< left_t,
right_t > map_type
typedef map_type::value_type value_type
Private Member Functions
void prune ()
void update ()
void checkUpdate ()
void flagForUpdate ()
Private Attributes
map_type m_map
Store & m_store
clock_type & m_clock
beast::Journal m_journal
clock_type::time_point m_whenUpdate
bool m_needsUpdate
Detailed Description
Stores IP addresses useful for gaining initial connections.
This is one of the caches that is consulted when additional outgoing connections are needed. Along with the address, each entry has this additional metadata:
Valence A signed integer which represents the number of successful consecutive connection attempts when positive, and the number of failed consecutive connection attempts when negative.
When choosing addresses from the boot cache for the purpose of establishing outgoing connections, addresses are ranked in decreasing order of high uptime, with valence as the tie breaker.
Definition at line 45 of file Bootcache.h.
Member Typedef Documentation
typedef iterator ripple::PeerFinder::Bootcache::const_iterator
Definition at line 111 of file Bootcache.h.
typedef boost::transform_iterator<Transform, map_type::right_map::const_iterator> ripple::PeerFinder::Bootcache::iterator
Definition at line 109 of file Bootcache.h.
typedef boost::bimaps::unordered_set_of<beast::IP::Endpoint> ripple::PeerFinder::Bootcache::left_t private
Definition at line 77 of file Bootcache.h.
typedef boost::bimap<left_t, right_t> ripple::PeerFinder::Bootcache::map_type private
Definition at line 79 of file Bootcache.h.
typedef boost::bimaps::multiset_of<Entry> ripple::PeerFinder::Bootcache::right_t private
Definition at line 78 of file Bootcache.h.
typedef map_type::value_type ripple::PeerFinder::Bootcache::value_type private
Definition at line 80 of file Bootcache.h.
Constructor & Destructor Documentation
ripple::PeerFinder::Bootcache::Bootcache (Store & store, clock_type & clock, beast::Journal journal)
Definition at line 25 of file Bootcache.cpp.
     : m_store (store)
     , m_clock (clock)
     , m_journal (journal)
     , m_whenUpdate (m_clock.now ())
 {
 }
ripple::PeerFinder::Bootcache::~Bootcache ()
Definition at line 36 of file Bootcache.cpp.
References update().
 {
     update();
 }
Member Function Documentation
Bootcache::const_iterator ripple::PeerFinder::Bootcache::begin () const
IP::Endpoint iterators that traverse in decreasing valence.
Definition at line 54 of file Bootcache.cpp.
References m_map.
 {
     return const_iterator (m_map.right.begin());
 }
Bootcache::const_iterator ripple::PeerFinder::Bootcache::cbegin () const
Definition at line 60 of file Bootcache.cpp.
References m_map.
 {
     return const_iterator (m_map.right.begin());
 }
Bootcache::const_iterator ripple::PeerFinder::Bootcache::cend () const
Definition at line 72 of file Bootcache.cpp.
References m_map.
 {
     return const_iterator (m_map.right.end());
 }
void ripple::PeerFinder::Bootcache::checkUpdate () private
Definition at line 252 of file Bootcache.cpp.
 {
     if (m_needsUpdate && m_whenUpdate < m_clock.now())
         update ();
 }
void ripple::PeerFinder::Bootcache::clear ()
Definition at line 78 of file Bootcache.cpp.
References m_map, and m_needsUpdate.
Referenced by load().
 {
     m_map.clear();
     m_needsUpdate = true;
 }
bool ripple::PeerFinder::Bootcache::empty () const
Returns true if the cache is empty.
Definition at line 42 of file Bootcache.cpp.
References m_map.
 {
     return m_map.empty();
 }
Bootcache::const_iterator ripple::PeerFinder::Bootcache::end () const
Definition at line 66 of file Bootcache.cpp.
References m_map.
 {
     return const_iterator (m_map.right.end());
 }
void ripple::PeerFinder::Bootcache::flagForUpdate () private
Definition at line 260 of file Bootcache.cpp.
 {
     m_needsUpdate = true;
     checkUpdate ();
 }
bool ripple::PeerFinder::Bootcache::insert (beast::IP::Endpoint const & endpoint)
Add the address to the cache.
Definition at line 113 of file Bootcache.cpp.
 {
     auto const result (m_map.insert (
         value_type (endpoint, 0)));
     if (result.second)
     {
         if (m_journal.trace) m_journal.trace << beast::leftw (18) <<
             "Bootcache insert " << endpoint;
         prune ();
         flagForUpdate();
     }
     return result.second;
 }
void ripple::PeerFinder::Bootcache::load ()
Load the persisted data from the Store into the container.
Definition at line 87 of file Bootcache.cpp.
References clear(), beast::Journal::error, ripple::PeerFinder::Store::load(), m_journal, m_map, and m_store.
 {
     clear();
     auto const n (m_store.load (
         [this](beast::IP::Endpoint const& endpoint, int valence)
         {
             auto const result (this->m_map.insert (
                 value_type (endpoint, valence)));
             if (! result.second)
             {
                 if (this->m_journal.error)
                     this->m_journal.error << beast::leftw (18) <<
                     "Bootcache discard " << endpoint;
             }
         }));
     if (n > 0)
     {
         if (m_journal.info) m_journal.info << beast::leftw (18) <<
             "Bootcache loaded " << n <<
                 ((n > 1) ? " addresses" : " address");
         prune ();
     }
 }
void ripple::PeerFinder::Bootcache::on_failure (beast::IP::Endpoint const & endpoint)
Called when an outbound connection attempt fails to handshake.
Definition at line 156 of file Bootcache.cpp.
References ripple::PeerFinder::Bootcache::Entry::valence().
 {
     auto result (m_map.insert (
         value_type (endpoint, -1)));
     if (result.second)
     {
         prune();
     }
     else
     {
         Entry entry (result.first->right);
         if (entry.valence() > 0)
             entry.valence() = 0;
         --entry.valence();
         m_map.erase (result.first);
         result = m_map.insert (
             value_type (endpoint, entry));
         assert (result.second);
     }
     Entry const& entry (result.first->right);
     auto const n (std::abs (entry.valence()));
     if (m_journal.debug) m_journal.debug << beast::leftw (18) <<
         "Bootcache failed " << endpoint <<
         " with " << n <<
         ((n > 1) ? " attempts" : " attempt");
     flagForUpdate();
 }
void ripple::PeerFinder::Bootcache::on_success (beast::IP::Endpoint const & endpoint)
Called when an outbound connection handshake completes.
Definition at line 128 of file Bootcache.cpp.
References ripple::PeerFinder::Bootcache::Entry::valence().
 {
     auto result (m_map.insert (
         value_type (endpoint, 1)));
     if (result.second)
     {
         prune ();
     }
     else
     {
         Entry entry (result.first->right);
         if (entry.valence() < 0)
             entry.valence() = 0;
         ++entry.valence();
         m_map.erase (result.first);
         result = m_map.insert (
             value_type (endpoint, entry));
         assert (result.second);
     }
     Entry const& entry (result.first->right);
     if (m_journal.info) m_journal.info << beast::leftw (18) <<
         "Bootcache connect " << endpoint <<
         " with " << entry.valence() <<
         ((entry.valence() > 1) ? " successes" : " success");
     flagForUpdate();
 }
void ripple::PeerFinder::Bootcache::onWrite (beast::PropertyStream::Map & map)
Write the cache state to the property stream.
Definition at line 193 of file Bootcache.cpp.
 {
     map ["entries"] = std::uint32_t (m_map.size());
 }
void ripple::PeerFinder::Bootcache::periodicActivity ()
Stores the cache in the persistent database on a timer.
Definition at line 185 of file Bootcache.cpp.
 {
     checkUpdate();
 }
void ripple::PeerFinder::Bootcache::prune () private
Definition at line 200 of file Bootcache.cpp.
References ripple::PeerFinder::Tuning::bootcachePrunePercent, and ripple::PeerFinder::Tuning::bootcacheSize.
 {
     if (size() <= Tuning::bootcacheSize)
         return;
     // Calculate the amount to remove
     auto count ((size() *
         Tuning::bootcachePrunePercent) / 100);
     decltype(count) pruned (0);
     // Work backwards because bimap doesn't handle
     // erasing using a reverse iterator very well.
     //
     for (auto iter (m_map.right.end());
         count-- > 0 && iter != m_map.right.begin(); ++pruned)
     {
         --iter;
         beast::IP::Endpoint const& endpoint (iter->get_left());
         Entry const& entry (iter->get_right());
         if (m_journal.trace) m_journal.trace << beast::leftw (18) <<
             "Bootcache pruned" << endpoint <<
             " at valence " << entry.valence();
         iter = m_map.right.erase (iter);
     }
     if (m_journal.debug) m_journal.debug << beast::leftw (18) <<
         "Bootcache pruned " << pruned << " entries total";
 }
Bootcache::map_type::size_type ripple::PeerFinder::Bootcache::size () const
Returns the number of entries in the cache.
Definition at line 48 of file Bootcache.cpp.
References m_map.
 {
     return m_map.size();
 }
void ripple::PeerFinder::Bootcache::update () private
Definition at line 231 of file Bootcache.cpp.
References ripple::PeerFinder::Tuning::bootcacheCooldownTime(), ripple::PeerFinder::Store::Entry::endpoint, and ripple::PeerFinder::Store::Entry::valence.
Referenced by ~Bootcache().
 {
     if (! m_needsUpdate)
         return;
     std::vector <Store::Entry> list;
     list.reserve (m_map.size());
     for (auto const& e : m_map)
     {
         Store::Entry se;
         se.endpoint = e.get_left();
         se.valence = e.get_right().valence();
         list.push_back (se);
     }
     m_store.save (list);
     // Reset the flag and cooldown timer
     m_needsUpdate = false;
     m_whenUpdate = m_clock.now() + Tuning::bootcacheCooldownTime;
 }
Member Data Documentation
clock_type& ripple::PeerFinder::Bootcache::m_clock private
Definition at line 98 of file Bootcache.h.
beast::Journal ripple::PeerFinder::Bootcache::m_journal private
Definition at line 99 of file Bootcache.h.
Referenced by load().
map_type ripple::PeerFinder::Bootcache::m_map private
Definition at line 95 of file Bootcache.h.
Referenced by begin(), cbegin(), cend(), clear(), empty(), end(), load(), and size().
bool ripple::PeerFinder::Bootcache::m_needsUpdate private
Definition at line 105 of file Bootcache.h.
Referenced by clear().
Store& ripple::PeerFinder::Bootcache::m_store private
Definition at line 97 of file Bootcache.h.
Referenced by load().
clock_type::time_point ripple::PeerFinder::Bootcache::m_whenUpdate private
Definition at line 102 of file Bootcache.h.
The documentation for this class was generated from the following files:
rippled/src/ripple/peerfinder/impl/Bootcache.h
rippled/src/ripple/peerfinder/impl/Bootcache.cpp