rippled: rocksdb::LogFileImpl Class Reference
rocksdb::LogFileImpl Class Reference
#include <transaction_log_impl.h>
Public Member Functions
LogFileImpl (uint64_t logNum, WalFileType logType, SequenceNumber startSeq, uint64_t sizeBytes)
std::string PathName () const
uint64_t LogNumber () const
WalFileType Type () const
SequenceNumber StartSequence () const
uint64_t SizeFileBytes () const
bool operator< (const LogFile &that) const
Public Member Functions inherited from rocksdb::LogFile
LogFile ()
virtual ~LogFile ()
Private Attributes
uint64_t logNumber_
WalFileType type_
SequenceNumber startSequence_
uint64_t sizeFileBytes_
Detailed Description
Definition at line 30 of file transaction_log_impl.h.
Constructor & Destructor Documentation
rocksdb::LogFileImpl::LogFileImpl (uint64_t logNum, WalFileType logType, SequenceNumber startSeq, uint64_t sizeBytes) inline
Definition at line 32 of file transaction_log_impl.h.
                                   :
     logNumber_(logNum),
     type_(logType),
     startSequence_(startSeq),
     sizeFileBytes_(sizeBytes) {
   }
Member Function Documentation
uint64_t rocksdb::LogFileImpl::LogNumber () const inline virtual
Implements rocksdb::LogFile.
Definition at line 47 of file transaction_log_impl.h.
References logNumber_.
Referenced by operator<().
 { return logNumber_; }
bool rocksdb::LogFileImpl::operator< (const LogFile & that) const inline
Definition at line 55 of file transaction_log_impl.h.
References rocksdb::LogFile::LogNumber(), and LogNumber().
{
     return LogNumber() < that.LogNumber();
   }
std::string rocksdb::LogFileImpl::PathName () const inline virtual
Implements rocksdb::LogFile.
Definition at line 40 of file transaction_log_impl.h.
References rocksdb::ArchivedLogFileName(), rocksdb::kArchivedLogFile, rocksdb::LogFileName(), logNumber_, and type_.
{
     if (type_ == kArchivedLogFile) {
       return ArchivedLogFileName("", logNumber_);
     }
     return LogFileName("", logNumber_);
   }
uint64_t rocksdb::LogFileImpl::SizeFileBytes () const inline virtual
Implements rocksdb::LogFile.
Definition at line 53 of file transaction_log_impl.h.
References sizeFileBytes_.
 { return sizeFileBytes_; }
SequenceNumber rocksdb::LogFileImpl::StartSequence () const inline virtual
Implements rocksdb::LogFile.
Definition at line 51 of file transaction_log_impl.h.
References startSequence_.
 { return startSequence_; }
WalFileType rocksdb::LogFileImpl::Type () const inline virtual
Implements rocksdb::LogFile.
Definition at line 49 of file transaction_log_impl.h.
References type_.
 { return type_; }
Member Data Documentation
uint64_t rocksdb::LogFileImpl::logNumber_ private
Definition at line 60 of file transaction_log_impl.h.
Referenced by LogNumber(), and PathName().
uint64_t rocksdb::LogFileImpl::sizeFileBytes_ private
Definition at line 63 of file transaction_log_impl.h.
Referenced by SizeFileBytes().
SequenceNumber rocksdb::LogFileImpl::startSequence_ private
Definition at line 62 of file transaction_log_impl.h.
Referenced by StartSequence().
WalFileType rocksdb::LogFileImpl::type_ private
Definition at line 61 of file transaction_log_impl.h.
Referenced by PathName(), and Type().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/db/transaction_log_impl.h