rippled: ripple::Validators::SourceFileImp Class Reference
ripple::Validators::SourceFileImp Class Reference
Public Member Functions
SourceFileImp (beast::File const &file)
~SourceFileImp ()
std::string to_string () const
beast::String uniqueID () const
beast::String createParam ()
void fetch (Results &results, beast::Journal journal)
Private Attributes
beast::File m_file
Additional Inherited Members
Static Public Member Functions inherited from ripple::Validators::SourceFile
static SourceFile * New (beast::File const &path)
Protected Member Functions inherited from beast::SharedObject
SharedObject ()
virtual ~SharedObject ()
virtual void destroy () const
void resetReferenceCount () noexcept
Detailed Description
Definition at line 23 of file SourceFile.cpp.
Constructor & Destructor Documentation
ripple::Validators::SourceFileImp::SourceFileImp (beast::File const & file) inline
Definition at line 28 of file SourceFile.cpp.
         : m_file (file)
     {
     }
ripple::Validators::SourceFileImp::~SourceFileImp () inline
Definition at line 33 of file SourceFile.cpp.
     {
     }
Member Function Documentation
beast::String ripple::Validators::SourceFileImp::createParam () inline virtual
A string that is used to recreate the source from the database entry.
Implements ripple::Validators::Source.
Definition at line 50 of file SourceFile.cpp.
References beast::File::getFullPathName(), and m_file.
     {
         return m_file.getFullPathName ();
     }
void ripple::Validators::SourceFileImp::fetch (Results & results, beast::Journal journal) inline virtual
Implements ripple::Validators::Source.
Definition at line 55 of file SourceFile.cpp.
References beast::MemoryBlock::begin(), beast::MemoryBlock::end(), ripple::f, beast::File::getSize(), m_file, ripple::max(), beast::RandomAccessFile::open(), ripple::Validators::Utilities::processLines(), beast::RandomAccessFile::read(), and beast::RandomAccessFile::readOnly.
     {
         std::int64_t const fileSize (m_file.getSize ());
         if (fileSize != 0)
         {
             if (fileSize < std::numeric_limits<std::int32_t>::max())
             {
                 beast::MemoryBlock buffer (fileSize);
                 beast::RandomAccessFile f;
                 beast::RandomAccessFile::ByteCount amountRead;
                 f.open (m_file, beast::RandomAccessFile::readOnly);
                 f.read (buffer.begin(), fileSize, &amountRead);
                 if (amountRead == fileSize)
                 {
                     Utilities::ParseResultLine lineFunction (results, journal);
                     Utilities::processLines (buffer.begin(), buffer.end(), lineFunction);
                 }
             }
             else
             {
                 // too big!
             }
         }
         else
         {
             // file doesn't exist
         }
     }
std::string ripple::Validators::SourceFileImp::to_string () const inline virtual
The name of the source, used in diagnostic output.
Implements ripple::Validators::Source.
Definition at line 37 of file SourceFile.cpp.
References beast::File::getFullPathName(), m_file, and beast::String::toStdString().
     {
         std::stringstream ss;
         ss <<
             "File: '" << m_file.getFullPathName().toStdString() + "'";
         return ss.str();
     }
beast::String ripple::Validators::SourceFileImp::uniqueID () const inline virtual
An identifier that uniquely describes the source. This is used for identification in the database.
Implements ripple::Validators::Source.
Definition at line 45 of file SourceFile.cpp.
References beast::File::getFullPathName(), and m_file.
     {
         return "File," + m_file.getFullPathName ();
     }
Member Data Documentation
beast::File ripple::Validators::SourceFileImp::m_file private
Definition at line 88 of file SourceFile.cpp.
Referenced by createParam(), fetch(), to_string(), and uniqueID().
The documentation for this class was generated from the following file:
rippled/src/ripple/validators/impl/SourceFile.cpp