rippled: ripple::IdentifierStorage< PreSize, Size, PostSize > Class Template Reference
ripple::IdentifierStorage< PreSize, Size, PostSize > Class Template Reference
#include <IdentifierStorage.h>
Classes
class key_equal
Public Types
typedef std::size_t size_type
typedef std::ptrdiff_t difference_type
typedef std::uint8_t value_type
typedef value_type * iterator
typedef value_type const * const_iterator
typedef value_type & reference
typedef value_type const & const_reference
typedef std::array
< std::uint8_t, storage_size > storage_type
typedef beast::hardened_hash
< IdentifierStorage > hasher
typedef std::reverse_iterator
< iterator > reverse_iterator
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator
Public Member Functions
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
iterator end ()
const_iterator end () const
const_iterator cend () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
const_reverse_iterator crbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
const_reverse_iterator crend () const
reference operator[] (size_type i)
const_reference operator[] (size_type i) const
reference front ()
reference back ()
const_reference front () const
const_reference back () const
value_type const * data () const
value_type * data ()
value_type * c_array ()
void assign (value_type value)
void fill (value_type value)
void clear ()
storage_type & storage ()
storage_type const & storage () const
void rangecheck (size_type i)
bool isZero () const
bool isNotZero () const
Static Public Attributes
static size_type const pre_size = PreSize
static size_type const size = Size
static size_type const post_size = PostSize
static size_type const storage_size = pre_size + size + post_size
Private Attributes
storage_type m_storage
Friends
template<class Hasher >
void hash_append (Hasher &h, IdentifierStorage const &a) noexcept
Detailed Description
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize>
class ripple::IdentifierStorage< PreSize, Size, PostSize >
A padded std::array used with IdentifierType traits.
Definition at line 32 of file IdentifierStorage.h.
Member Typedef Documentation
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> typedef value_type const* ripple::IdentifierStorage< PreSize, Size, PostSize >::const_iterator
Definition at line 39 of file IdentifierStorage.h.
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> typedef value_type const& ripple::IdentifierStorage< PreSize, Size, PostSize >::const_reference
Definition at line 41 of file IdentifierStorage.h.
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> typedef std::reverse_iterator<const_iterator> ripple::IdentifierStorage< PreSize, Size, PostSize >::const_reverse_iterator
Definition at line 76 of file IdentifierStorage.h.
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> typedef std::ptrdiff_t ripple::IdentifierStorage< PreSize, Size, PostSize >::difference_type
Definition at line 36 of file IdentifierStorage.h.
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> typedef beast::hardened_hash<IdentifierStorage> ripple::IdentifierStorage< PreSize, Size, PostSize >::hasher
Value hashing function. The seed prevents crafted inputs from causing degenarate parent containers.
Definition at line 54 of file IdentifierStorage.h.
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> typedef value_type* ripple::IdentifierStorage< PreSize, Size, PostSize >::iterator
Definition at line 38 of file IdentifierStorage.h.
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> typedef value_type& ripple::IdentifierStorage< PreSize, Size, PostSize >::reference
Definition at line 40 of file IdentifierStorage.h.
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> typedef std::reverse_iterator<iterator> ripple::IdentifierStorage< PreSize, Size, PostSize >::reverse_iterator
Definition at line 75 of file IdentifierStorage.h.
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> typedef std::size_t ripple::IdentifierStorage< PreSize, Size, PostSize >::size_type
Definition at line 35 of file IdentifierStorage.h.
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> typedef std::array< std::uint8_t, storage_size> ripple::IdentifierStorage< PreSize, Size, PostSize >::storage_type
Definition at line 49 of file IdentifierStorage.h.
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> typedef std::uint8_t ripple::IdentifierStorage< PreSize, Size, PostSize >::value_type
Definition at line 37 of file IdentifierStorage.h.
Member Function Documentation
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> void ripple::IdentifierStorage< PreSize, Size, PostSize >::assign (value_type value) inline
Definition at line 106 of file IdentifierStorage.h.
References ripple::IdentifierStorage< PreSize, Size, PostSize >::fill().
 { fill (value); }
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> reference ripple::IdentifierStorage< PreSize, Size, PostSize >::back () inline
Definition at line 98 of file IdentifierStorage.h.
References ripple::IdentifierStorage< PreSize, Size, PostSize >::m_storage, ripple::IdentifierStorage< PreSize, Size, PostSize >::post_size, and ripple::IdentifierStorage< PreSize, Size, PostSize >::storage_size.
 { return m_storage[storage_size-post_size-1]; }
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> const_reference ripple::IdentifierStorage< PreSize, Size, PostSize >::back () const inline
Definition at line 100 of file IdentifierStorage.h.
References ripple::IdentifierStorage< PreSize, Size, PostSize >::m_storage, ripple::IdentifierStorage< PreSize, Size, PostSize >::post_size, and ripple::IdentifierStorage< PreSize, Size, PostSize >::storage_size.
 { return m_storage[storage_size-post_size-1]; }
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> iterator ripple::IdentifierStorage< PreSize, Size, PostSize >::begin () inline
Definition at line 68 of file IdentifierStorage.h.
References ripple::IdentifierStorage< PreSize, Size, PostSize >::m_storage, and ripple::IdentifierStorage< PreSize, Size, PostSize >::pre_size.
Referenced by ripple::CryptoIdentifier< 33, 35, true >::construct(), ripple::IdentifierStorage< PreSize, Size, PostSize >::crend(), ripple::IdentifierStorage< PreSize, Size, PostSize >::fill(), ripple::IdentifierStorage< PreSize, Size, PostSize >::isZero(), ripple::operator==(), and ripple::IdentifierStorage< PreSize, Size, PostSize >::rend().
 { return &m_storage[pre_size]; }
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> const_iterator ripple::IdentifierStorage< PreSize, Size, PostSize >::begin () const inline
Definition at line 69 of file IdentifierStorage.h.
References ripple::IdentifierStorage< PreSize, Size, PostSize >::m_storage, and ripple::IdentifierStorage< PreSize, Size, PostSize >::pre_size.
 { return &m_storage[pre_size]; }
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> value_type* ripple::IdentifierStorage< PreSize, Size, PostSize >::c_array () inline
Definition at line 104 of file IdentifierStorage.h.
References ripple::IdentifierStorage< PreSize, Size, PostSize >::m_storage, and ripple::IdentifierStorage< PreSize, Size, PostSize >::pre_size.
 { return &m_storage[pre_size]; }
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> const_iterator ripple::IdentifierStorage< PreSize, Size, PostSize >::cbegin () const inline
Definition at line 70 of file IdentifierStorage.h.
References ripple::IdentifierStorage< PreSize, Size, PostSize >::m_storage, and ripple::IdentifierStorage< PreSize, Size, PostSize >::pre_size.
 { return &m_storage[pre_size]; }
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> const_iterator ripple::IdentifierStorage< PreSize, Size, PostSize >::cend () const inline
Definition at line 73 of file IdentifierStorage.h.
References ripple::IdentifierStorage< PreSize, Size, PostSize >::m_storage, ripple::IdentifierStorage< PreSize, Size, PostSize >::post_size, and ripple::IdentifierStorage< PreSize, Size, PostSize >::storage_size.
 { return &m_storage[storage_size-post_size]; }
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> void ripple::IdentifierStorage< PreSize, Size, PostSize >::clear () inline
Definition at line 108 of file IdentifierStorage.h.
References ripple::IdentifierStorage< PreSize, Size, PostSize >::fill().
 { fill (value_type ()); }
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> const_reverse_iterator ripple::IdentifierStorage< PreSize, Size, PostSize >::crbegin () const inline
Definition at line 80 of file IdentifierStorage.h.
References ripple::IdentifierStorage< PreSize, Size, PostSize >::end().
 { return const_reverse_iterator(end()); }
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> const_reverse_iterator ripple::IdentifierStorage< PreSize, Size, PostSize >::crend () const inline
Definition at line 83 of file IdentifierStorage.h.
References ripple::IdentifierStorage< PreSize, Size, PostSize >::begin().
 { return const_reverse_iterator(begin()); }
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> value_type const* ripple::IdentifierStorage< PreSize, Size, PostSize >::data () const inline
Definition at line 102 of file IdentifierStorage.h.
References ripple::IdentifierStorage< PreSize, Size, PostSize >::m_storage, and ripple::IdentifierStorage< PreSize, Size, PostSize >::pre_size.
 { return &m_storage[pre_size]; }
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> value_type* ripple::IdentifierStorage< PreSize, Size, PostSize >::data () inline
Definition at line 103 of file IdentifierStorage.h.
References ripple::IdentifierStorage< PreSize, Size, PostSize >::m_storage, and ripple::IdentifierStorage< PreSize, Size, PostSize >::pre_size.
 { return &m_storage[pre_size]; }
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> iterator ripple::IdentifierStorage< PreSize, Size, PostSize >::end () inline
Definition at line 71 of file IdentifierStorage.h.
References ripple::IdentifierStorage< PreSize, Size, PostSize >::m_storage, ripple::IdentifierStorage< PreSize, Size, PostSize >::post_size, and ripple::IdentifierStorage< PreSize, Size, PostSize >::storage_size.
Referenced by ripple::CryptoIdentifier< 33, 35, true >::construct(), ripple::IdentifierStorage< PreSize, Size, PostSize >::crbegin(), ripple::IdentifierStorage< PreSize, Size, PostSize >::isZero(), ripple::operator==(), and ripple::IdentifierStorage< PreSize, Size, PostSize >::rbegin().
 { return &m_storage[storage_size-post_size]; }
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> const_iterator ripple::IdentifierStorage< PreSize, Size, PostSize >::end () const inline
Definition at line 72 of file IdentifierStorage.h.
References ripple::IdentifierStorage< PreSize, Size, PostSize >::m_storage, ripple::IdentifierStorage< PreSize, Size, PostSize >::post_size, and ripple::IdentifierStorage< PreSize, Size, PostSize >::storage_size.
 { return &m_storage[storage_size-post_size]; }
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> void ripple::IdentifierStorage< PreSize, Size, PostSize >::fill (value_type value) inline
Definition at line 107 of file IdentifierStorage.h.
References ripple::IdentifierStorage< PreSize, Size, PostSize >::begin(), and ripple::IdentifierStorage< PreSize, Size, PostSize >::size.
Referenced by ripple::IdentifierStorage< PreSize, Size, PostSize >::assign(), and ripple::IdentifierStorage< PreSize, Size, PostSize >::clear().
 { std::fill_n (begin(), size, value); }
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> reference ripple::IdentifierStorage< PreSize, Size, PostSize >::front () inline
Definition at line 97 of file IdentifierStorage.h.
References ripple::IdentifierStorage< PreSize, Size, PostSize >::m_storage, and ripple::IdentifierStorage< PreSize, Size, PostSize >::pre_size.
 { return m_storage[pre_size]; }
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> const_reference ripple::IdentifierStorage< PreSize, Size, PostSize >::front () const inline
Definition at line 99 of file IdentifierStorage.h.
References ripple::IdentifierStorage< PreSize, Size, PostSize >::m_storage, and ripple::IdentifierStorage< PreSize, Size, PostSize >::pre_size.
 { return m_storage[pre_size]; }
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> bool ripple::IdentifierStorage< PreSize, Size, PostSize >::isNotZero () const inline
Definition at line 128 of file IdentifierStorage.h.
References ripple::IdentifierStorage< PreSize, Size, PostSize >::isZero().
     {
         return !isZero();
     }
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> bool ripple::IdentifierStorage< PreSize, Size, PostSize >::isZero () const inline
Definition at line 120 of file IdentifierStorage.h.
References ripple::IdentifierStorage< PreSize, Size, PostSize >::begin(), and ripple::IdentifierStorage< PreSize, Size, PostSize >::end().
Referenced by ripple::IdentifierStorage< PreSize, Size, PostSize >::isNotZero().
     {
         for (const_iterator iter(begin()); iter != end(); ++iter)
             if ((*iter)!=0)
                 return false;
         return true;
     }
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> reference ripple::IdentifierStorage< PreSize, Size, PostSize >::operator[] (size_type i) inline
Definition at line 85 of file IdentifierStorage.h.
References bassert, ripple::IdentifierStorage< PreSize, Size, PostSize >::m_storage, ripple::IdentifierStorage< PreSize, Size, PostSize >::pre_size, and ripple::IdentifierStorage< PreSize, Size, PostSize >::size.
     {
         bassert (i < size);
         return m_storage[pre_size+i];
     }
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> const_reference ripple::IdentifierStorage< PreSize, Size, PostSize >::operator[] (size_type i) const inline
Definition at line 91 of file IdentifierStorage.h.
References bassert, ripple::IdentifierStorage< PreSize, Size, PostSize >::m_storage, ripple::IdentifierStorage< PreSize, Size, PostSize >::pre_size, and ripple::IdentifierStorage< PreSize, Size, PostSize >::size.
     {
         bassert (i < size);
         return m_storage[pre_size+i];
     }
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> void ripple::IdentifierStorage< PreSize, Size, PostSize >::rangecheck (size_type i) inline
Definition at line 114 of file IdentifierStorage.h.
References ripple::IdentifierStorage< PreSize, Size, PostSize >::size.
     {
         if (i >= size)
             throw std::out_of_range ("IdentifierStorage<>: index out of range");
     }
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> reverse_iterator ripple::IdentifierStorage< PreSize, Size, PostSize >::rbegin () inline
Definition at line 78 of file IdentifierStorage.h.
References ripple::IdentifierStorage< PreSize, Size, PostSize >::end().
 { return reverse_iterator(end()); }
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> const_reverse_iterator ripple::IdentifierStorage< PreSize, Size, PostSize >::rbegin () const inline
Definition at line 79 of file IdentifierStorage.h.
References ripple::IdentifierStorage< PreSize, Size, PostSize >::end().
 { return const_reverse_iterator(end()); }
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> reverse_iterator ripple::IdentifierStorage< PreSize, Size, PostSize >::rend () inline
Definition at line 81 of file IdentifierStorage.h.
References ripple::IdentifierStorage< PreSize, Size, PostSize >::begin().
 { return reverse_iterator(begin()); }
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> const_reverse_iterator ripple::IdentifierStorage< PreSize, Size, PostSize >::rend () const inline
Definition at line 82 of file IdentifierStorage.h.
References ripple::IdentifierStorage< PreSize, Size, PostSize >::begin().
 { return const_reverse_iterator(begin()); }
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> storage_type& ripple::IdentifierStorage< PreSize, Size, PostSize >::storage () inline
Definition at line 111 of file IdentifierStorage.h.
References ripple::IdentifierStorage< PreSize, Size, PostSize >::m_storage.
Referenced by ripple::CryptoIdentifier< 33, 35, true >::construct(), ripple::CryptoIdentifier< 33, 35, true >::from_string(), ripple::RippleAccountIDTraits::to_string(), and ripple::CryptoIdentifier< 33, 35, true >::to_string().
 { return m_storage; }
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> storage_type const& ripple::IdentifierStorage< PreSize, Size, PostSize >::storage () const inline
Definition at line 112 of file IdentifierStorage.h.
References ripple::IdentifierStorage< PreSize, Size, PostSize >::m_storage.
 { return m_storage; }
Friends And Related Function Documentation
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> template<class Hasher > void hash_append (Hasher & h, IdentifierStorage< PreSize, Size, PostSize > const & a) friend
Definition at line 134 of file IdentifierStorage.h.
     {
         using beast::hash_append;
         hash_append (h, a.m_storage);
     }
Member Data Documentation
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> storage_type ripple::IdentifierStorage< PreSize, Size, PostSize >::m_storage private
Definition at line 141 of file IdentifierStorage.h.
Referenced by ripple::IdentifierStorage< PreSize, Size, PostSize >::back(), ripple::IdentifierStorage< PreSize, Size, PostSize >::begin(), ripple::IdentifierStorage< PreSize, Size, PostSize >::c_array(), ripple::IdentifierStorage< PreSize, Size, PostSize >::cbegin(), ripple::IdentifierStorage< PreSize, Size, PostSize >::cend(), ripple::IdentifierStorage< PreSize, Size, PostSize >::data(), ripple::IdentifierStorage< PreSize, Size, PostSize >::end(), ripple::IdentifierStorage< PreSize, Size, PostSize >::front(), ripple::IdentifierStorage< PreSize, Size, PostSize >::operator[](), and ripple::IdentifierStorage< PreSize, Size, PostSize >::storage().
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> size_type const ripple::IdentifierStorage< PreSize, Size, PostSize >::post_size = PostSize static
Definition at line 45 of file IdentifierStorage.h.
Referenced by ripple::IdentifierStorage< PreSize, Size, PostSize >::back(), ripple::IdentifierStorage< PreSize, Size, PostSize >::cend(), and ripple::IdentifierStorage< PreSize, Size, PostSize >::end().
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> size_type const ripple::IdentifierStorage< PreSize, Size, PostSize >::pre_size = PreSize static
Definition at line 43 of file IdentifierStorage.h.
Referenced by ripple::IdentifierStorage< PreSize, Size, PostSize >::begin(), ripple::IdentifierStorage< PreSize, Size, PostSize >::c_array(), ripple::IdentifierStorage< PreSize, Size, PostSize >::cbegin(), ripple::IdentifierStorage< PreSize, Size, PostSize >::data(), ripple::IdentifierStorage< PreSize, Size, PostSize >::front(), and ripple::IdentifierStorage< PreSize, Size, PostSize >::operator[]().
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> size_type const ripple::IdentifierStorage< PreSize, Size, PostSize >::size = Size static
Definition at line 44 of file IdentifierStorage.h.
Referenced by ripple::IdentifierStorage< PreSize, Size, PostSize >::fill(), ripple::IdentifierStorage< PreSize, Size, PostSize >::operator[](), and ripple::IdentifierStorage< PreSize, Size, PostSize >::rangecheck().
template<std::size_t PreSize, std::size_t Size, std::size_t PostSize> size_type const ripple::IdentifierStorage< PreSize, Size, PostSize >::storage_size = pre_size + size + post_size static
Definition at line 46 of file IdentifierStorage.h.
Referenced by ripple::IdentifierStorage< PreSize, Size, PostSize >::back(), ripple::IdentifierStorage< PreSize, Size, PostSize >::cend(), ripple::IdentifierStorage< PreSize, Size, PostSize >::end(), and ripple::CryptoIdentifier< 33, 35, true >::from_string().
The documentation for this class was generated from the following file:
rippled/src/ripple/types/api/IdentifierStorage.h