rippled: ripple::NodeObject Class Reference
ripple::NodeObject Class Reference
#include <NodeObject.h>
Classes
struct LessThan
struct PrivateAccess
Public Types
enum { keyBytes = 32 }
typedef boost::shared_ptr
< NodeObject > Ptr
typedef boost::shared_ptr
< NodeObject > pointer
typedef pointer const & ref
Public Member Functions
NodeObject (NodeObjectType type, LedgerIndex ledgerIndex, Blob &data, uint256 const &hash, PrivateAccess)
NodeObjectType getType () const
uint256 const & getHash () const
LedgerIndex getIndex () const
Blob const & getData () const
bool isCloneOf (NodeObject::Ptr const &other) const
Public Member Functions inherited from ripple::CountedObject< NodeObject >
CountedObject ()
CountedObject (CountedObject const &)
~CountedObject ()
Static Public Member Functions
static char const * getCountedObjectName ()
static Ptr createObject (NodeObjectType type, LedgerIndex ledgerIndex, Blob &data, uint256 const &hash)
Private Attributes
NodeObjectType mType
uint256 mHash
LedgerIndex mLedgerIndex
Blob mData
Detailed Description
A blob of data with associated metadata, referenced by hash.
The metadata includes the following:
Type of the blob
The ledger index in which it appears
The SHA 256 hash
Note
No checking is performed to make sure the hash matches the data.
See Also
SHAMap
Definition at line 48 of file NodeObject.h.
Member Typedef Documentation
typedef boost::shared_ptr<NodeObject> ripple::NodeObject::pointer
Definition at line 68 of file NodeObject.h.
typedef boost::shared_ptr<NodeObject> ripple::NodeObject::Ptr
Definition at line 65 of file NodeObject.h.
typedef pointer const& ripple::NodeObject::ref
Definition at line 69 of file NodeObject.h.
Member Enumeration Documentation
anonymous enum
Enumerator
keyBytes
Size of the fixed keys, in bytes.
    We use a 256-bit hash for the keys.
See Also
NodeObject
Definition at line 53 of file NodeObject.h.
     {
         keyBytes = 32,
     };
Constructor & Destructor Documentation
ripple::NodeObject::NodeObject (NodeObjectType type, LedgerIndex ledgerIndex, Blob & data, uint256 const & hash, PrivateAccess)
Definition at line 26 of file NodeObject.cpp.
     : mType (type)
     , mHash (hash)
     , mLedgerIndex (ledgerIndex)
 {
     // Take over the caller's buffer
     mData.swap (data);
 }
Member Function Documentation
NodeObject::Ptr ripple::NodeObject::createObject (NodeObjectType type, LedgerIndex ledgerIndex, Blob & data, uint256 const & hash) static
Create an object from fields.
The caller's variable is modified during this call. The underlying storage for the Blob is taken over by the NodeObject.
Parameters
type The type of object.
ledgerIndex The ledger in which this object appears.
data A buffer containing the payload. The caller's variable is overwritten.
hash The 256-bit hash of the payload data.
Definition at line 40 of file NodeObject.cpp.
References hash.
Referenced by ripple::NodeStore::DecodedBlob::createObject(), ripple::NodeStore::TestBase::PredictableObjectFactory::createObject(), ripple::SqliteBackend::fetch(), ripple::NodeStore::DatabaseImp::store(), and ripple::SqliteBackend::visitAll().
 {
     // The boost::ref is important or
     // else it will be passed by  value!
     return boost::make_shared <NodeObject> (
         type, ledgerIndex, boost::ref (data), hash, PrivateAccess ());
 }
static char const* ripple::NodeObject::getCountedObjectName () inline static
Definition at line 51 of file NodeObject.h.
 { return "NodeObject"; }
Blob const & ripple::NodeObject::getData () const
Retrieve the binary data.
Definition at line 67 of file NodeObject.cpp.
References mData.
 {
     return mData;
 }
uint256 const & ripple::NodeObject::getHash () const
Retrieve the hash metadata.
Definition at line 57 of file NodeObject.cpp.
References mHash.
 {
     return mHash;
 }
LedgerIndex ripple::NodeObject::getIndex () const
Retrieve the ledger index in which this object appears.
Definition at line 62 of file NodeObject.cpp.
References mLedgerIndex.
 {
     return mLedgerIndex;
 }
NodeObjectType ripple::NodeObject::getType () const
Retrieve the type of this object.
Definition at line 52 of file NodeObject.cpp.
References mType.
 {
     return mType;
 }
bool ripple::NodeObject::isCloneOf (NodeObject::Ptr const & other) const
See if this object has the same data as another object.
Definition at line 72 of file NodeObject.cpp.
References mData, mHash, mLedgerIndex, and mType.
 {
     if (mType != other->mType)
         return false;
     if (mHash != other->mHash)
         return false;
     if (mLedgerIndex != other->mLedgerIndex)
         return false;
     if (mData != other->mData)
         return false;
     return true;
 }
Member Data Documentation
Blob ripple::NodeObject::mData private
Definition at line 140 of file NodeObject.h.
Referenced by getData(), and isCloneOf().
uint256 ripple::NodeObject::mHash private
Definition at line 138 of file NodeObject.h.
Referenced by getHash(), and isCloneOf().
LedgerIndex ripple::NodeObject::mLedgerIndex private
Definition at line 139 of file NodeObject.h.
Referenced by getIndex(), and isCloneOf().
NodeObjectType ripple::NodeObject::mType private
Definition at line 137 of file NodeObject.h.
Referenced by getType(), and isCloneOf().
The documentation for this class was generated from the following files:
rippled/src/ripple_core/nodestore/api/NodeObject.h
rippled/src/ripple_core/nodestore/impl/NodeObject.cpp