rippled: ripple::BuildInfo::Protocol Struct Reference
ripple::BuildInfo::Protocol Struct Reference
#include <BuildInfo.h>
Public Types
typedef std::uint32_t PackedFormat
Public Member Functions
Protocol ()
Protocol (unsigned short vmajor, unsigned short vminor)
Protocol (PackedFormat packedVersion)
PackedFormat toPacked () const noexcept
std::string toStdString () const noexcept
bool operator== (Protocol const &other) const noexcept
bool operator!= (Protocol const &other) const noexcept
bool operator>= (Protocol const &other) const noexcept
bool operator<= (Protocol const &other) const noexcept
bool operator> (Protocol const &other) const noexcept
bool operator< (Protocol const &other) const noexcept
Public Attributes
unsigned short vmajor
unsigned short vminor
Detailed Description
The wire protocol version.
The version consists of two unsigned 16 bit integers representing major and minor version numbers. All values are permissible.
Definition at line 50 of file BuildInfo.h.
Member Typedef Documentation
typedef std::uint32_t ripple::BuildInfo::Protocol::PackedFormat
The serialized format of the protocol version.
Definition at line 58 of file BuildInfo.h.
Constructor & Destructor Documentation
ripple::BuildInfo::Protocol::Protocol ()
Definition at line 133 of file BuildInfo.cpp.
     : vmajor (0)
     , vminor (0)
 {
 }
ripple::BuildInfo::Protocol::Protocol (unsigned short vmajor, unsigned short vminor)
Definition at line 139 of file BuildInfo.cpp.
     : vmajor (major_)
     , vminor (minor_)
 {
 }
ripple::BuildInfo::Protocol::Protocol (PackedFormat packedVersion) explicit
Definition at line 145 of file BuildInfo.cpp.
 {
     vmajor = (packedVersion >> 16) & 0xffff;
     vminor = (packedVersion & 0xffff);
 }
Member Function Documentation
bool ripple::BuildInfo::Protocol::operator!= (Protocol const & other) const inline noexcept
Definition at line 69 of file BuildInfo.h.
References toPacked().
 { return toPacked () != other.toPacked (); }
bool ripple::BuildInfo::Protocol::operator< (Protocol const & other) const inline noexcept
Definition at line 73 of file BuildInfo.h.
References toPacked().
 { return toPacked () <  other.toPacked (); }
bool ripple::BuildInfo::Protocol::operator<= (Protocol const & other) const inline noexcept
Definition at line 71 of file BuildInfo.h.
References toPacked().
 { return toPacked () <= other.toPacked (); }
bool ripple::BuildInfo::Protocol::operator== (Protocol const & other) const inline noexcept
Definition at line 68 of file BuildInfo.h.
References toPacked().
 { return toPacked () == other.toPacked (); }
bool ripple::BuildInfo::Protocol::operator> (Protocol const & other) const inline noexcept
Definition at line 72 of file BuildInfo.h.
References toPacked().
 { return toPacked () >  other.toPacked (); }
bool ripple::BuildInfo::Protocol::operator>= (Protocol const & other) const inline noexcept
Definition at line 70 of file BuildInfo.h.
References toPacked().
 { return toPacked () >= other.toPacked (); }
BuildInfo::Protocol::PackedFormat ripple::BuildInfo::Protocol::toPacked () const noexcept
Definition at line 151 of file BuildInfo.cpp.
Referenced by ripple::PeerImp::json(), operator!=(), operator<(), operator<=(), operator==(), operator>(), operator>=(), and ripple::PeerImp::recvHello().
 {
     return ((vmajor << 16) & 0xffff0000) | (vminor & 0xffff);
 }
std::string ripple::BuildInfo::Protocol::toStdString () const noexcept
Definition at line 156 of file BuildInfo.cpp.
References beast::String::toStdString().
 {
     beast::String s;
     s << beast::String (vmajor) << "." << beast::String (vminor);
     return s.toStdString ();
 }
Member Data Documentation
unsigned short ripple::BuildInfo::Protocol::vmajor
Definition at line 52 of file BuildInfo.h.
unsigned short ripple::BuildInfo::Protocol::vminor
Definition at line 53 of file BuildInfo.h.
The documentation for this struct was generated from the following files:
rippled/src/ripple_data/protocol/BuildInfo.h
rippled/src/ripple_data/protocol/BuildInfo.cpp