rippled: ripple::STHash256 Class Reference
ripple::STHash256 Class Reference
#include <SerializedTypes.h>
Public Member Functions
STHash256 (uint256 const &v)
STHash256 (SField::ref n, uint256 const &v)
STHash256 (SField::ref n, const char *v)
STHash256 (SField::ref n, const std::string &v)
STHash256 (SField::ref n)
STHash256 ()
SerializedTypeID getSType () const
std::string getText () const
void add (Serializer &s) const
uint256 const & getValue () const
void setValue (uint256 const &v)
operator uint256 () const
virtual bool isEquivalent (const SerializedType &t) const
virtual bool isDefault () const
Public Member Functions inherited from ripple::SerializedType
SerializedType ()
SerializedType (SField::ref n)
virtual ~SerializedType ()
void setFName (SField::ref n)
SField::ref getFName () const
std::string getName () const
std::unique_ptr< SerializedType > clone () const
virtual std::string getFullText () const
virtual Json::Value getJson (int) const
void addFieldID (Serializer &s) const
SerializedType & operator= (const SerializedType &t)
bool operator== (const SerializedType &t) const
bool operator!= (const SerializedType &t) const
template<class D >
D & downcast ()
template<class D >
D const & downcast () const
Static Public Member Functions
static std::unique_ptr
< SerializedType > deserialize (SerializerIterator &sit, SField::ref name)
Static Public Member Functions inherited from ripple::SerializedType
static std::unique_ptr
< SerializedType > deserialize (SField::ref name)
Private Member Functions
STHash256 * duplicate () const
Static Private Member Functions
static STHash256 * construct (SerializerIterator &, SField::ref)
Private Attributes
uint256 value
Additional Inherited Members
Protected Attributes inherited from ripple::SerializedType
SField::ptr fName
Detailed Description
Definition at line 988 of file SerializedTypes.h.
Constructor & Destructor Documentation
ripple::STHash256::STHash256 (uint256 const & v) inline
Definition at line 991 of file SerializedTypes.h.
                                  : value (v)
     {
         ;
     }
ripple::STHash256::STHash256 (SField::ref n, uint256 const & v) inline
Definition at line 995 of file SerializedTypes.h.
                                               : SerializedType (n), value (v)
     {
         ;
     }
ripple::STHash256::STHash256 (SField::ref n, const char * v) inline
Definition at line 999 of file SerializedTypes.h.
References ripple::base_uint< BITS >::SetHex(), and value.
                                            : SerializedType (n)
     {
         value.SetHex (v);
     }
ripple::STHash256::STHash256 (SField::ref n, const std::string & v) inline
Definition at line 1003 of file SerializedTypes.h.
References ripple::base_uint< BITS >::SetHex(), and value.
                                                 : SerializedType (n)
     {
         value.SetHex (v);
     }
ripple::STHash256::STHash256 (SField::ref n) inline
Definition at line 1007 of file SerializedTypes.h.
                             : SerializedType (n)
     {
         ;
     }
ripple::STHash256::STHash256 () inline
Definition at line 1011 of file SerializedTypes.h.
Referenced by construct(), and duplicate().
     {
         ;
     }
Member Function Documentation
void ripple::STHash256::add (Serializer & s) const inline virtual
Reimplemented from ripple::SerializedType.
Definition at line 1025 of file SerializedTypes.h.
References ripple::Serializer::add256(), and value.
     {
         s.add256 (value);
     }
STHash256 * ripple::STHash256::construct (SerializerIterator & u, SField::ref name) static private
Definition at line 271 of file SerializedTypes.cpp.
References ripple::SerializerIterator::get256(), and STHash256().
Referenced by deserialize().
 {
     return new STHash256 (name, u.get256 ());
 }
static std::unique_ptr<SerializedType> ripple::STHash256::deserialize (SerializerIterator & sit, SField::ref name) inline static
Definition at line 1015 of file SerializedTypes.h.
References construct().
Referenced by ripple::STObject::makeDeserializedObject().
     {
         return std::unique_ptr<SerializedType> (construct (sit, name));
     }
STHash256* ripple::STHash256::duplicate () const inline private virtual
Reimplemented from ripple::SerializedType.
Definition at line 1052 of file SerializedTypes.h.
References STHash256().
     {
         return new STHash256 (*this);
     }
SerializedTypeID ripple::STHash256::getSType () const inline virtual
Reimplemented from ripple::SerializedType.
Definition at line 1020 of file SerializedTypes.h.
     {
         return STI_HASH256;
     }
std::string ripple::STHash256::getText () const virtual
Reimplemented from ripple::SerializedType.
Definition at line 276 of file SerializedTypes.cpp.
References ripple::base_uint< BITS >::GetHex(), and value.
 {
     return value.GetHex ();
 }
uint256 const& ripple::STHash256::getValue () const inline
Definition at line 1030 of file SerializedTypes.h.
References value.
Referenced by ripple::STObject::getFieldH256().
     {
         return value;
     }
virtual bool ripple::STHash256::isDefault () const inline virtual
Reimplemented from ripple::SerializedType.
Definition at line 1044 of file SerializedTypes.h.
References ripple::base_uint< BITS >::isZero(), and value.
     {
         return value.isZero ();
     }
bool ripple::STHash256::isEquivalent (const SerializedType & t) const virtual
Reimplemented from ripple::SerializedType.
Definition at line 281 of file SerializedTypes.cpp.
References value.
 {
     const STHash256* v = dynamic_cast<const STHash256*> (&t);
     return v && (value == v->value);
 }
ripple::STHash256::operator uint256 () const inline
Definition at line 1039 of file SerializedTypes.h.
References value.
     {
         return value;
     }
void ripple::STHash256::setValue (uint256 const & v) inline
Definition at line 1034 of file SerializedTypes.h.
References value.
Referenced by ripple::STObject::setFieldH256().
     {
         value = v;
     }
Member Data Documentation
uint256 ripple::STHash256::value private
Definition at line 1050 of file SerializedTypes.h.
Referenced by add(), getText(), getValue(), isDefault(), isEquivalent(), operator uint256(), setValue(), and STHash256().
The documentation for this class was generated from the following files:
rippled/src/ripple_data/protocol/SerializedTypes.h
rippled/src/ripple_data/protocol/SerializedTypes.cpp