rippled: beast::hash_append_test Class Reference
beast::hash_append_test Class Reference
Classes
struct results_t
Public Types
typedef hash_append_tests::SlowKey SlowKey
typedef hash_append_tests::FastKey FastKey
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Member Functions
template<class Key >
std::set< Key > make_keys (std::size_t count)
template<class Hasher , class Keys >
std::vector< std::size_t > make_hashes (Keys const &keys)
template<class Hasher , class Hashes >
void measure_hashes (results_t &results, Hashes const &hashes)
template<class Hasher , class Keys >
void measure_keys (results_t &results, Keys const &keys)
template<class Hasher , class Key >
void test_hasher (std::string const &name, std::size_t n)
void report (std::string const &name, results_t const &results)
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Additional Inherited Members
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 359 of file hash_append.test.cpp.
Member Typedef Documentation
typedef hash_append_tests::FastKey beast::hash_append_test::FastKey
Definition at line 363 of file hash_append.test.cpp.
typedef hash_append_tests::SlowKey beast::hash_append_test::SlowKey
Definition at line 362 of file hash_append.test.cpp.
Member Function Documentation
template<class Hasher , class Keys > std::vector<std::size_t> beast::hash_append_test::make_hashes (Keys const & keys) inline
Definition at line 394 of file hash_append.test.cpp.
References beast::hash_append().
     {
         std::vector <std::size_t> hashes;
         hashes.reserve (keys.size());
         for (auto const& key : keys)
         {
             Hasher h;
             hash_append (h, key);
             hashes.push_back (static_cast <std::size_t> (h));
         }
         return hashes;
     }
template<class Key > std::set<Key> beast::hash_append_test::make_keys (std::size_t count) inline
Definition at line 383 of file hash_append.test.cpp.
     {
         std::set <Key> keys;
         while (count--)
             keys.emplace();
         return keys;
     }
template<class Hasher , class Hashes > void beast::hash_append_test::measure_hashes (results_t & results, Hashes const & hashes) inline
Definition at line 409 of file hash_append.test.cpp.
References beast::hash_metrics::collision_factor(), beast::hash_append_test::results_t::collision_factor, beast::hash_metrics::distribution_factor(), beast::hash_append_test::results_t::distribution_factor, beast::hash_metrics::windowed_score(), and beast::hash_append_test::results_t::windowed_score.
     {
         results.collision_factor =
             hash_metrics::collision_factor (
                 hashes.begin(), hashes.end());
         results.distribution_factor =
             hash_metrics::distribution_factor (
                 hashes.begin(), hashes.end());
         results.windowed_score =
             hash_metrics::windowed_score (
                 hashes.begin(), hashes.end());
     }
template<class Hasher , class Keys > void beast::hash_append_test::measure_keys (results_t & results, Keys const & keys) inline
Definition at line 426 of file hash_append.test.cpp.
References beast::hash_append_test::results_t::elapsed.
     {
         auto const start (
             std::chrono::high_resolution_clock::now());
         auto const hashes (make_hashes <Hasher> (keys));
         results.elapsed = std::chrono::duration_cast <std::chrono::milliseconds> (
             std::chrono::high_resolution_clock::now() - start);
         measure_hashes <Hasher> (results, hashes);
     }
void beast::hash_append_test::report (std::string const & name, results_t const & results) inline
Definition at line 450 of file hash_append.test.cpp.
References beast::hash_append_test::results_t::collision_factor, beast::hash_append_test::results_t::distribution_factor, beast::hash_append_test::results_t::elapsed, beast::unit_test::suite::log, beast::unit_test::suite::pass(), and beast::hash_append_test::results_t::windowed_score.
Referenced by test_hasher().
     {
         log <<
             std::left <<
             std::setw (39) << name << " | " <<
             std::right <<
             std::setw (13) << std::setprecision (5) <<
                 results.collision_factor << " | " <<
             std::setw (13) << std::setprecision (5) <<
                 results.distribution_factor << " | " <<
             std::setw (13) << std::setprecision (5) <<
                 results.windowed_score << " | " <<
             std::left <<
             results.elapsed.count();
         pass ();
     }
void beast::hash_append_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 468 of file hash_append.test.cpp.
References beast::unit_test::suite::log.
     {
         log <<
             "name                                    |     collision |  distribution |   windowed    | time (milliseconds)" << std::endl <<
             "----------------------------------------+---------------+---------------+---------------+--------------------";
         //test_hasher <hash_append_tests::prng_hasher<>, SlowKey> ("prng_hasher <SlowKey>", 10000);
         //test_hasher <hash_append_tests::prng_hasher<>, FastKey> ("prng_hasher <FastKey>", 100000);
         test_hasher <hash_append_tests::jenkins1, SlowKey>      ("jenkins1 <SlowKey>",  1000000);
         test_hasher <hash_append_tests::spooky, SlowKey>        ("spooky <SlowKey>",    1000000);
         test_hasher <hash_append_tests::fnv1a, SlowKey>         ("fnv1a <SlowKey>",     1000000);
         test_hasher <hash_append_tests::jenkins1, FastKey>      ("jenkins1 <FastKey>",  1000000);
         test_hasher <hash_append_tests::spooky, FastKey>        ("spooky <FastKey>",    1000000);
         test_hasher <hash_append_tests::fnv1a, FastKey>         ("fnv1a <FastKey>",     1000000);
     }
template<class Hasher , class Key > void beast::hash_append_test::test_hasher (std::string const & name, std::size_t n) inline
Definition at line 441 of file hash_append.test.cpp.
References report().
     {
         results_t results;
         auto const keys (make_keys <Key> (n));
         measure_keys <Hasher> (results, keys);
         report (name, results);
     }
The documentation for this class was generated from the following file:
rippled/src/beast/beast/container/tests/hash_append.test.cpp