rippled: rocksdb::TtlMergeOperator Class Reference
rocksdb::TtlMergeOperator Class Reference
#include <db_ttl.h>
Public Member Functions
TtlMergeOperator (const std::shared_ptr< MergeOperator > merge_op)
virtual bool FullMerge (const Slice &key, const Slice *existing_value, const std::deque< std::string > &operands, std::string *new_value, Logger *logger) const override
virtual bool PartialMerge (const Slice &key, const Slice &left_operand, const Slice &right_operand, std::string *new_value, Logger *logger) const override
virtual const char * Name () const override
Public Member Functions inherited from rocksdb::MergeOperator
virtual ~MergeOperator ()
Private Attributes
std::shared_ptr< MergeOperator > user_merge_op_
Detailed Description
Definition at line 258 of file db_ttl.h.
Constructor & Destructor Documentation
rocksdb::TtlMergeOperator::TtlMergeOperator (const std::shared_ptr< MergeOperator > merge_op) inline explicit
Definition at line 261 of file db_ttl.h.
     : user_merge_op_(merge_op) {
     assert(merge_op);
   }
Member Function Documentation
virtual bool rocksdb::TtlMergeOperator::FullMerge (const Slice & key, const Slice * existing_value, const std::deque< std::string > & operands, std::string * new_value, Logger * logger) const inline override virtual
Implements rocksdb::MergeOperator.
Definition at line 266 of file db_ttl.h.
References rocksdb::Slice::data(), rocksdb::EncodeFixed32(), rocksdb::DBWithTTL::GetCurrentTime(), rocksdb::DBWithTTL::kTSLength, rocksdb::Log(), ripple::Resource::ok, rocksdb::Slice::size(), and user_merge_op_.
{
     const uint32_t ts_len = DBWithTTL::kTSLength;
     if (existing_value && existing_value->size() < ts_len) {
       Log(logger, "Error: Could not remove timestamp from existing value.");
       return false;
     }
     // Extract time-stamp from each operand to be passed to user_merge_op_
     std::deque<std::string> operands_without_ts;
     for (const auto &operand : operands) {
       if (operand.size() < ts_len) {
         Log(logger, "Error: Could not remove timestamp from operand value.");
         return false;
       }
       operands_without_ts.push_back(operand.substr(0, operand.size() - ts_len));
     }
     // Apply the user merge operator (store result in *new_value)
     bool good = true;
     if (existing_value) {
       Slice existing_value_without_ts(existing_value->data(),
                                       existing_value->size() - ts_len);
       good = user_merge_op_->FullMerge(key, &existing_value_without_ts,
                                        operands_without_ts, new_value, logger);
     } else {
       good = user_merge_op_->FullMerge(key, nullptr, operands_without_ts,
                                        new_value, logger);
     }
     // Return false if the user merge operator returned false
     if (!good) {
       return false;
     }
     // Augment the *new_value with the ttl time-stamp
     int64_t curtime;
     if (!DBWithTTL::GetCurrentTime(curtime).ok()) {
       Log(logger, "Error: Could not get current time to be attached internally "
                   "to the new value.");
       return false;
     } else {
       char ts_string[ts_len];
       EncodeFixed32(ts_string, (int32_t)curtime);
       new_value->append(ts_string, ts_len);
       return true;
     }
   }
virtual const char* rocksdb::TtlMergeOperator::Name () const inline override virtual
Implements rocksdb::MergeOperator.
Definition at line 354 of file db_ttl.h.
{
     return "Merge By TTL";
   }
virtual bool rocksdb::TtlMergeOperator::PartialMerge (const Slice & key, const Slice & left_operand, const Slice & right_operand, std::string * new_value, Logger * logger) const inline override virtual
Implements rocksdb::MergeOperator.
Definition at line 318 of file db_ttl.h.
References rocksdb::Slice::data(), rocksdb::EncodeFixed32(), rocksdb::DBWithTTL::GetCurrentTime(), rocksdb::DBWithTTL::kTSLength, rocksdb::Log(), rocksdb::Status::ok(), rocksdb::Slice::size(), and user_merge_op_.
{
     const uint32_t ts_len = DBWithTTL::kTSLength;
     if (left_operand.size() < ts_len || right_operand.size() < ts_len) {
       Log(logger, "Error: Could not remove timestamp from value.");
       return false;
     }
     // Apply the user partial-merge operator (store result in *new_value)
     assert(new_value);
     Slice left_without_ts(left_operand.data(), left_operand.size() - ts_len);
     Slice right_without_ts(right_operand.data(), right_operand.size() - ts_len);
     if (!user_merge_op_->PartialMerge(key, left_without_ts, right_without_ts,
                                       new_value, logger)) {
       return false;
     }
     // Augment the *new_value with the ttl time-stamp
     int64_t curtime;
     if (!DBWithTTL::GetCurrentTime(curtime).ok()) {
       Log(logger, "Error: Could not get current time to be attached internally "
                   "to the new value.");
       return false;
     } else {
       char ts_string[ts_len];
       EncodeFixed32(ts_string, (int32_t)curtime);
       new_value->append(ts_string, ts_len);
       return true;
     }
   }
Member Data Documentation
std::shared_ptr<MergeOperator> rocksdb::TtlMergeOperator::user_merge_op_ private
Definition at line 359 of file db_ttl.h.
Referenced by FullMerge(), and PartialMerge().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/utilities/ttl/db_ttl.h