rippled: beast::asio::TestPeerLogicSyncServer Class Reference
beast::asio::TestPeerLogicSyncServer Class Reference
#include <TestPeerLogicSyncServer.h>
Public Member Functions
TestPeerLogicSyncServer (abstract_socket &socket)
PeerRole get_role () const noexcept
Model get_model () const noexcept
void on_connect ()
Public Member Functions inherited from beast::asio::TestPeerLogic
TestPeerLogic (abstract_socket &socket)
error_code & error () noexcept
error_code const & error () const noexcept
error_code const & error (error_code const &ec) noexcept
abstract_socket & socket () noexcept
virtual void on_connect_async (error_code const &)
virtual void finished ()
Additional Inherited Members
Public Types inherited from beast::asio::TestPeerLogic
typedef boost::system::error_code error_code
Static Public Member Functions inherited from beast::asio::TestPeerLogic
static void pure_virtual ()
Detailed Description
Definition at line 26 of file TestPeerLogicSyncServer.h.
Constructor & Destructor Documentation
beast::asio::TestPeerLogicSyncServer::TestPeerLogicSyncServer (abstract_socket & socket) explicit
Definition at line 23 of file TestPeerLogicSyncServer.cpp.
     : TestPeerLogic (socket)
 {
 }
Member Function Documentation
TestPeerBasics::Model beast::asio::TestPeerLogicSyncServer::get_model () const virtual noexcept
Implements beast::asio::TestPeerLogic.
Definition at line 33 of file TestPeerLogicSyncServer.cpp.
References beast::asio::TestPeerBasics::Model::sync.
 {
     return Model::sync;
 }
PeerRole beast::asio::TestPeerLogicSyncServer::get_role () const virtual noexcept
Implements beast::asio::TestPeerLogic.
Definition at line 28 of file TestPeerLogicSyncServer.cpp.
References beast::asio::PeerRole::server.
Referenced by on_connect().
 {
     return PeerRole::server;
 }
void beast::asio::TestPeerLogicSyncServer::on_connect () virtual
Reimplemented from beast::asio::TestPeerLogic.
Definition at line 38 of file TestPeerLogicSyncServer.cpp.
References beast::asio::TestPeerLogic::error(), beast::asio::TestPeerBasics::failure(), get_role(), beast::asio::TestPeerLogic::socket(), beast::asio::TestPeerBasics::to_handshake_type(), and beast::asio::TestPeerBasics::unexpected().
 {
     if (socket ().needs_handshake ())
     {
         if (failure (socket ().handshake (to_handshake_type (get_role ()), error ())))
             return;
     }
     {
         boost::asio::streambuf buf (5);
         std::size_t const amount = boost::asio::read_until (
             socket (), buf, "hello", error ());
         if (failure (error ()))
             return;
         if (unexpected (amount == 5, error ()))
             return;
         if (unexpected (buf.size () == 5, error ()))
             return;
     }
     {
         std::size_t const amount = boost::asio::write (
             socket (), boost::asio::buffer ("goodbye", 7), error ());
         if (failure (error ()))
             return;
         if (unexpected (amount == 7, error ()))
             return;
     }
     if (socket ().needs_handshake ())
     {
         if (failure (socket ().shutdown (error ()), true))
             return;
     }
     if (failure (socket ().shutdown (abstract_socket::shutdown_send, error ())))
         return;
     if (failure (socket ().close (error ())))
         return;
 }
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_asio/tests/TestPeerLogicSyncServer.h
rippled/src/beast/modules/beast_asio/tests/TestPeerLogicSyncServer.cpp