rippled: beast::TemporaryFile Class Reference
beast::TemporaryFile Class Reference
#include <TemporaryFile.h>
Public Types
enum OptionFlags { useHiddenFile = 1, putNumbersInBrackets = 2 }
Public Member Functions
TemporaryFile (const String &suffix=String::empty, int optionFlags=0)
TemporaryFile (const File &targetFile, int optionFlags=0)
TemporaryFile (const File &targetFile, const File &temporaryFile)
~TemporaryFile ()
const File & getFile () const noexcept
const File & getTargetFile () const noexcept
bool overwriteTargetFileWithTemporary () const
bool deleteTemporaryFile () const
Private Attributes
const File temporaryFile
const File targetFile
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
Manages a temporary file, which will be deleted when this object is deleted.
This object is intended to be used as a stack based object, using its scope to make sure the temporary file isn't left lying around.
For example:
{
    File myTargetFile ("~/myfile.txt");
    // this will choose a file called something like "~/myfile_temp239348.txt"
    // which definitely doesn't exist at the time the constructor is called.
    TemporaryFile temp (myTargetFile);
    // create a stream to the temporary file, and write some data to it...
    ScopedPointer <FileOutputStream> out (temp.getFile().createOutputStream());
    if (out != nullptr)
    {
        out->write ( ...etc )
        out = nullptr; // (deletes the stream)
        // ..now we've finished writing, this will rename the temp file to
        // make it replace the target file we specified above.
        bool succeeded = temp.overwriteTargetFileWithTemporary();
    }
    // ..and even if something went wrong and our overwrite failed,
    // as the TemporaryFile object goes out of scope here, it'll make sure
    // that the temp file gets deleted.
}
See Also
File, FileOutputStream
Definition at line 68 of file TemporaryFile.h.
Member Enumeration Documentation
enum beast::TemporaryFile::OptionFlags
Enumerator
useHiddenFile
Indicates that the temporary file should be hidden - i.e. its name should start with a dot.
putNumbersInBrackets
Indicates that when numbers are appended to make sure the file is unique, they should go in brackets rather than just being appended (see File::getNonexistentSibling())
Definition at line 72 of file TemporaryFile.h.
     {
         useHiddenFile = 1,
         putNumbersInBrackets = 2
     };
Constructor & Destructor Documentation
beast::TemporaryFile::TemporaryFile (const String & suffix = String::empty, int optionFlags = 0)
Creates a randomly-named temporary file in the default temp directory.
Parameters
suffix a file suffix to use for the file
optionFlags a combination of the values listed in the OptionFlags enum The file will not be created until you write to it. And remember that when this object is deleted, the file will also be deleted!
Definition at line 36 of file TemporaryFile.cpp.
     : temporaryFile (createTempFile (File::getSpecialLocation (File::tempDirectory),
                                      "temp_" + String::toHexString (Random::getSystemRandom().nextInt()),
                                      suffix, optionFlags))
 {
 }
beast::TemporaryFile::TemporaryFile (const File & targetFile, int optionFlags = 0)
Creates a temporary file in the same directory as a specified file.
This is useful if you have a file that you want to overwrite, but don't want to harm the original file if the write operation fails. You can use this to create a temporary file next to the target file, then write to the temporary file, and finally use overwriteTargetFileWithTemporary() to replace the target file with the one you've just written.
This class won't create any files until you actually write to them. And remember that when this object is deleted, the temporary file will also be deleted!
Parameters
targetFile the file that you intend to overwrite - the temporary file will be created in the same directory as this
optionFlags a combination of the values listed in the OptionFlags enum
Definition at line 43 of file TemporaryFile.cpp.
References bassert, beast::File::nonexistent(), and targetFile.
     : temporaryFile (createTempFile (target.getParentDirectory(),
                                      target.getFileNameWithoutExtension()
                                        + "_temp" + String::toHexString (Random::getSystemRandom().nextInt()),
                                      target.getFileExtension(), optionFlags)),
       targetFile (target)
 {
     // If you use this constructor, you need to give it a valid target file!
     bassert (targetFile != File::nonexistent ());
 }
beast::TemporaryFile::TemporaryFile (const File & targetFile, const File & temporaryFile)
Creates a temporary file using an explicit filename. The other constructors are a better choice than this one, unless for some reason you need to explicitly specify the temporary file you want to use.
Parameters
targetFile the file that you intend to overwrite
temporaryFile the temporary file to be used
Definition at line 54 of file TemporaryFile.cpp.
     : temporaryFile (temporary), targetFile (target)
 {
 }
beast::TemporaryFile::~TemporaryFile ()
Destructor.
When this object is deleted it will make sure that its temporary file is also deleted! If the operation fails, it'll throw an assertion in debug mode.
Definition at line 59 of file TemporaryFile.cpp.
References bassertfalse, and deleteTemporaryFile().
 {
     if (! deleteTemporaryFile())
     {
         /* Failed to delete our temporary file! The most likely reason for this would be
            that you've not closed an output stream that was being used to write to file.
            If you find that something beyond your control is changing permissions on
            your temporary files and preventing them from being deleted, you may want to
            call TemporaryFile::deleteTemporaryFile() to detect those error cases and
            handle them appropriately.
         */
         bassertfalse;
     }
 }
Member Function Documentation
bool beast::TemporaryFile::deleteTemporaryFile () const
Attempts to delete the temporary file, if it exists.
Returns
true if the file is successfully deleted (or if it didn't exist).
Definition at line 103 of file TemporaryFile.cpp.
References beast::File::deleteFile(), beast::Thread::sleep(), and temporaryFile.
Referenced by ~TemporaryFile().
 {
     // Have a few attempts at deleting the file before giving up..
     for (int i = 5; --i >= 0;)
     {
         if (temporaryFile.deleteFile())
             return true;
         Thread::sleep (50);
     }
     return false;
 }
const File& beast::TemporaryFile::getFile () const inline noexcept
Returns the temporary file.
Definition at line 130 of file TemporaryFile.h.
References temporaryFile.
Referenced by beast::File::replaceWithData(), and beast::File::replaceWithText().
 { return temporaryFile; }
const File& beast::TemporaryFile::getTargetFile () const inline noexcept
Returns the target file that was specified in the constructor.
Definition at line 133 of file TemporaryFile.h.
References targetFile.
 { return targetFile; }
bool beast::TemporaryFile::overwriteTargetFileWithTemporary () const
Tries to move the temporary file to overwrite the target file that was specified in the constructor.
If you used the constructor that specified a target file, this will attempt to replace that file with the temporary one.
Before calling this, make sure:
that you've actually written to the temporary file
that you've closed any open streams that you were using to write to it
and that you don't have any streams open to the target file, which would prevent it being overwritten
If the file move succeeds, this returns false, and the temporary file will have disappeared. If it fails, the temporary file will probably still exist, but will be deleted when this object is destroyed.
Definition at line 76 of file TemporaryFile.cpp.
References bassert, bassertfalse, beast::File::exists(), beast::File::moveFileTo(), beast::File::nonexistent(), beast::Thread::sleep(), targetFile, and temporaryFile.
Referenced by beast::File::replaceWithData(), and beast::File::replaceWithText().
 {
     // This method only works if you created this object with the constructor
     // that takes a target file!
     bassert (targetFile != File::nonexistent ());
     if (temporaryFile.exists())
     {
         // Have a few attempts at overwriting the file before giving up..
         for (int i = 5; --i >= 0;)
         {
             if (temporaryFile.moveFileTo (targetFile))
                 return true;
             Thread::sleep (100);
         }
     }
     else
     {
         // There's no temporary file to use. If your write failed, you should
         // probably check, and not bother calling this method.
         bassertfalse;
     }
     return false;
 }
Member Data Documentation
const File beast::TemporaryFile::targetFile private
Definition at line 161 of file TemporaryFile.h.
Referenced by getTargetFile(), overwriteTargetFileWithTemporary(), and TemporaryFile().
const File beast::TemporaryFile::temporaryFile private
Definition at line 161 of file TemporaryFile.h.
Referenced by deleteTemporaryFile(), getFile(), and overwriteTargetFileWithTemporary().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_core/files/TemporaryFile.h
rippled/src/beast/modules/beast_core/files/TemporaryFile.cpp