rippled: ripple::NodeStore::NodeStoreDatabase_test Class Reference
ripple::NodeStore::NodeStoreDatabase_test Class Reference
Public Member Functions
void testImport (beast::String destBackendType, beast::String srcBackendType, std::int64_t seedValue)
void testNodeStore (beast::String type, bool const useEphemeralDatabase, bool const testPersistence, std::int64_t const seedValue, int numObjectsToTest=2000)
void runBackendTests (bool useEphemeralDatabase, std::int64_t const seedValue)
void runImportTests (std::int64_t const seedValue)
void run ()
Public Member Functions inherited from ripple::NodeStore::TestBase
void storeBatch (Backend &backend, Batch const &batch)
void fetchCopyOfBatch (Backend &backend, Batch *pCopy, Batch const &batch)
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Additional Inherited Members
Public Types inherited from ripple::NodeStore::TestBase
enum { maxPayloadBytes = 2000, numObjectsToTest = 2000 }
Static Public Member Functions inherited from ripple::NodeStore::TestBase
static void createPredictableBatch (Batch &batch, int startingIndex, int numObjects, std::int64_t seedValue)
static bool areBatchesEqual (Batch const &lhs, Batch const &rhs)
static void storeBatch (Database &db, Batch const &batch)
static void fetchCopyOfBatch (Database &db, Batch *pCopy, Batch const &batch)
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 23 of file DatabaseTests.cpp.
Member Function Documentation
void ripple::NodeStore::NodeStoreDatabase_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 218 of file DatabaseTests.cpp.
References runBackendTests(), runImportTests(), and testNodeStore().
     {
         std::int64_t const seedValue = 50;
         testNodeStore ("memory", false, false, seedValue);
         runBackendTests (false, seedValue);
         runBackendTests (true, seedValue);
         runImportTests (seedValue);
     }
void ripple::NodeStore::NodeStoreDatabase_test::runBackendTests (bool useEphemeralDatabase, std::int64_t const seedValue) inline
Definition at line 180 of file DatabaseTests.cpp.
References testNodeStore().
Referenced by run().
     {
         testNodeStore ("leveldb", useEphemeralDatabase, true, seedValue);
     #if RIPPLE_HYPERLEVELDB_AVAILABLE
         testNodeStore ("hyperleveldb", useEphemeralDatabase, true, seedValue);
     #endif
     #if RIPPLE_ROCKSDB_AVAILABLE
         testNodeStore ("rocksdb", useEphemeralDatabase, true, seedValue);
     #endif
     #if RIPPLE_ENABLE_SQLITE_BACKEND_TESTS
         testNodeStore ("sqlite", useEphemeralDatabase, true, seedValue);
     #endif
     }
void ripple::NodeStore::NodeStoreDatabase_test::runImportTests (std::int64_t const seedValue) inline
Definition at line 199 of file DatabaseTests.cpp.
References testImport().
Referenced by run().
     {
         testImport ("leveldb", "leveldb", seedValue);
     #if RIPPLE_ROCKSDB_AVAILABLE
         testImport ("rocksdb", "rocksdb", seedValue);
     #endif
     #if RIPPLE_HYPERLEVELDB_AVAILABLE
         testImport ("hyperleveldb", "hyperleveldb", seedValue);
     #endif
     #if RIPPLE_ENABLE_SQLITE_BACKEND_TESTS
         testImport ("sqlite", "sqlite", seedValue);
     #endif
     }
void ripple::NodeStore::NodeStoreDatabase_test::testImport (beast::String destBackendType, beast::String srcBackendType, std::int64_t seedValue) inline
Definition at line 26 of file DatabaseTests.cpp.
References ripple::NodeStore::TestBase::areBatchesEqual(), ripple::NodeStore::TestBase::createPredictableBatch(), beast::File::createTempFile(), beast::unit_test::suite::expect(), ripple::NodeStore::TestBase::fetchCopyOfBatch(), beast::File::getFullPathName(), ripple::NodeStore::make_Manager(), ripple::NodeStore::TestBase::numObjectsToTest, beast::StringPairArray::set(), ripple::NodeStore::TestBase::storeBatch(), and beast::unit_test::suite::testcase().
Referenced by runImportTests().
     {
         std::unique_ptr <Manager> manager (make_Manager ());
         DummyScheduler scheduler;
         beast::File const node_db (beast::File::createTempFile ("node_db"));
         beast::StringPairArray srcParams;
         srcParams.set ("type", srcBackendType);
         srcParams.set ("path", node_db.getFullPathName ());
         // Create a batch
         Batch batch;
         createPredictableBatch (batch, 0, numObjectsToTest, seedValue);
         beast::Journal j;
         // Write to source db
         {
             std::unique_ptr <Database> src (manager->make_Database (
                 "test", scheduler, j, 2, srcParams));
             storeBatch (*src, batch);
         }
         Batch copy;
         {
             // Re-open the db
             std::unique_ptr <Database> src (manager->make_Database (
                 "test", scheduler, j, 2, srcParams));
             // Set up the destination database
             beast::File const dest_db (beast::File::createTempFile ("dest_db"));
             beast::StringPairArray destParams;
             destParams.set ("type", destBackendType);
             destParams.set ("path", dest_db.getFullPathName ());
             std::unique_ptr <Database> dest (manager->make_Database (
                 "test", scheduler, j, 2, destParams));
             testcase ((beast::String ("import into '") + destBackendType + "' from '" + srcBackendType + "'").toStdString());
             // Do the import
             dest->import (*src);
             // Get the results of the import
             fetchCopyOfBatch (*dest, &copy, batch);
         }
         // Canonicalize the source and destination batches
         std::sort (batch.begin (), batch.end (), NodeObject::LessThan ());
         std::sort (copy.begin (), copy.end (), NodeObject::LessThan ());
         expect (areBatchesEqual (batch, copy), "Should be equal");
     }
void ripple::NodeStore::NodeStoreDatabase_test::testNodeStore (beast::String type, bool const useEphemeralDatabase, bool const testPersistence, std::int64_t const seedValue, int numObjectsToTest = 2000) inline
Definition at line 83 of file DatabaseTests.cpp.
References ripple::NodeStore::TestBase::areBatchesEqual(), ripple::NodeStore::TestBase::createPredictableBatch(), beast::File::createTempFile(), db, beast::unit_test::suite::expect(), ripple::NodeStore::TestBase::fetchCopyOfBatch(), beast::File::getFullPathName(), ripple::NodeStore::make_Manager(), ripple::NodeStore::TestBase::numObjectsToTest, beast::UnitTestUtilities::repeatableShuffle(), beast::StringPairArray::set(), ripple::NodeStore::TestBase::storeBatch(), beast::unit_test::suite::testcase(), and beast::String::toStdString().
Referenced by run(), and runBackendTests().
     {
         std::unique_ptr <Manager> manager (make_Manager ());
         DummyScheduler scheduler;
         beast::String s;
         s << beast::String ("NodeStore backend '") + type + "'";
         if (useEphemeralDatabase)
             s << " (with ephemeral database)";
         testcase (s.toStdString());
         beast::File const node_db (beast::File::createTempFile ("node_db"));
         beast::StringPairArray nodeParams;
         nodeParams.set ("type", type);
         nodeParams.set ("path", node_db.getFullPathName ());
         beast::File const temp_db  (beast::File::createTempFile ("temp_db"));
         beast::StringPairArray tempParams;
         if (useEphemeralDatabase)
         {
             tempParams.set ("type", type);
             tempParams.set ("path", temp_db.getFullPathName ());
         }
         // Create a batch
         Batch batch;
         createPredictableBatch (batch, 0, numObjectsToTest, seedValue);
         beast::Journal j;
         {
             // Open the database
             std::unique_ptr <Database> db (manager->make_Database ("test", scheduler,
                 j, 2, nodeParams, tempParams));
             // Write the batch
             storeBatch (*db, batch);
             {
                 // Read it back in
                 Batch copy;
                 fetchCopyOfBatch (*db, &copy, batch);
                 expect (areBatchesEqual (batch, copy), "Should be equal");
             }
             {
                 // Reorder and read the copy again
                 Batch copy;
                 beast::UnitTestUtilities::repeatableShuffle (batch.size (), batch, seedValue);
                 fetchCopyOfBatch (*db, &copy, batch);
                 expect (areBatchesEqual (batch, copy), "Should be equal");
             }
         }
         if (testPersistence)
         {
             {
                 // Re-open the database without the ephemeral DB
                 std::unique_ptr <Database> db (manager->make_Database (
                     "test", scheduler, j, 2, nodeParams));
                 // Read it back in
                 Batch copy;
                 fetchCopyOfBatch (*db, &copy, batch);
                 // Canonicalize the source and destination batches
                 std::sort (batch.begin (), batch.end (), NodeObject::LessThan ());
                 std::sort (copy.begin (), copy.end (), NodeObject::LessThan ());
                 expect (areBatchesEqual (batch, copy), "Should be equal");
             }
             if (useEphemeralDatabase)
             {
                 // Verify the ephemeral db
                 std::unique_ptr <Database> db (manager->make_Database ("test",
                     scheduler, j, 2, tempParams, beast::StringPairArray ()));
                 // Read it back in
                 Batch copy;
                 fetchCopyOfBatch (*db, &copy, batch);
                 // Canonicalize the source and destination batches
                 std::sort (batch.begin (), batch.end (), NodeObject::LessThan ());
                 std::sort (copy.begin (), copy.end (), NodeObject::LessThan ());
                 expect (areBatchesEqual (batch, copy), "Should be equal");
             }
         }
     }
The documentation for this class was generated from the following file:
rippled/src/ripple_core/nodestore/tests/DatabaseTests.cpp