rippled: ripple::STObject Class Reference
ripple::STObject Class Reference
#include <SerializedObject.h>
Public Types
typedef boost::ptr_vector
< SerializedType >::iterator iterator
typedef boost::ptr_vector
< SerializedType >
::const_iterator const_iterator
Public Member Functions
STObject ()
STObject (SField::ref name)
STObject (const SOTemplate &type, SField::ref name)
STObject (const SOTemplate &type, SerializerIterator &sit, SField::ref name)
STObject (SField::ref name, boost::ptr_vector< SerializedType > &data)
std::unique_ptr< STObject > oClone () const
virtual ~STObject ()
bool setType (const SOTemplate &type)
bool isValidForType ()
bool isFieldAllowed (SField::ref)
bool isFree () const
void set (const SOTemplate &)
bool set (SerializerIterator &u, int depth=0)
virtual SerializedTypeID getSType () const
virtual bool isEquivalent (const SerializedType &t) const
virtual bool isDefault () const
virtual void add (Serializer &s) const
void add (Serializer &s, bool withSignature) const
Serializer getSerializer () const
std::string getFullText () const
std::string getText () const
virtual Json::Value getJson (int options) const
int addObject (const SerializedType &t)
int giveObject (std::unique_ptr< SerializedType > t)
int giveObject (SerializedType *t)
const boost::ptr_vector
< SerializedType > & peekData () const
boost::ptr_vector
< SerializedType > & peekData ()
SerializedType & front ()
const SerializedType & front () const
SerializedType & back ()
const SerializedType & back () const
int getCount () const
bool setFlag (std::uint32_t)
bool clearFlag (std::uint32_t)
bool isFlag (std::uint32_t) const
std::uint32_t getFlags () const
uint256 getHash (std::uint32_t prefix) const
uint256 getSigningHash (std::uint32_t prefix) const
const SerializedType & peekAtIndex (int offset) const
SerializedType & getIndex (int offset)
const SerializedType * peekAtPIndex (int offset) const
SerializedType * getPIndex (int offset)
int getFieldIndex (SField::ref field) const
SField::ref getFieldSType (int index) const
const SerializedType & peekAtField (SField::ref field) const
SerializedType & getField (SField::ref field)
const SerializedType * peekAtPField (SField::ref field) const
SerializedType * getPField (SField::ref field, bool createOkay=false)
std::string getFieldString (SField::ref field) const
unsigned char getFieldU8 (SField::ref field) const
std::uint16_t getFieldU16 (SField::ref field) const
std::uint32_t getFieldU32 (SField::ref field) const
std::uint64_t getFieldU64 (SField::ref field) const
uint128 getFieldH128 (SField::ref field) const
uint160 getFieldH160 (SField::ref field) const
uint256 getFieldH256 (SField::ref field) const
RippleAddress getFieldAccount (SField::ref field) const
uint160 getFieldAccount160 (SField::ref field) const
Blob getFieldVL (SField::ref field) const
const STAmount & getFieldAmount (SField::ref field) const
const STPathSet & getFieldPathSet (SField::ref field) const
const STVector256 & getFieldV256 (SField::ref field) const
const STArray & getFieldArray (SField::ref field) const
void setFieldU8 (SField::ref field, unsigned char)
void setFieldU16 (SField::ref field, std::uint16_t)
void setFieldU32 (SField::ref field, std::uint32_t)
void setFieldU64 (SField::ref field, std::uint64_t)
void setFieldH128 (SField::ref field, const uint128 &)
void setFieldH160 (SField::ref field, const uint160 &)
void setFieldH256 (SField::ref field, uint256 const &)
void setFieldVL (SField::ref field, Blob const &)
void setFieldAccount (SField::ref field, const uint160 &)
void setFieldAccount (SField::ref field, const RippleAddress &addr)
void setFieldAmount (SField::ref field, const STAmount &)
void setFieldPathSet (SField::ref field, const STPathSet &)
void setFieldV256 (SField::ref field, const STVector256 &v)
STObject & peekFieldObject (SField::ref field)
bool isFieldPresent (SField::ref field) const
SerializedType * makeFieldPresent (SField::ref field)
void makeFieldAbsent (SField::ref field)
bool delField (SField::ref field)
void delField (int index)
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
bool empty () const
bool hasMatchingEntry (const SerializedType &)
bool operator== (const STObject &o) const
bool operator!= (const STObject &o) const
Public Member Functions inherited from ripple::SerializedType
SerializedType ()
SerializedType (SField::ref n)
virtual ~SerializedType ()
void setFName (SField::ref n)
SField::ref getFName () const
std::string getName () const
std::unique_ptr< SerializedType > clone () const
void addFieldID (Serializer &s) const
SerializedType & operator= (const SerializedType &t)
bool operator== (const SerializedType &t) const
bool operator!= (const SerializedType &t) const
template<class D >
D & downcast ()
template<class D >
D const & downcast () const
Public Member Functions inherited from ripple::CountedObject< STObject >
CountedObject ()
CountedObject (CountedObject const &)
~CountedObject ()
Static Public Member Functions
static char const * getCountedObjectName ()
static std::unique_ptr
< SerializedType > deserialize (SerializerIterator &sit, SField::ref name)
static std::unique_ptr
< SerializedType > makeDefaultObject (SerializedTypeID id, SField::ref name)
static std::unique_ptr
< SerializedType > makeDeserializedObject (SerializedTypeID id, SField::ref name, SerializerIterator &, int depth)
static std::unique_ptr
< SerializedType > makeNonPresentObject (SField::ref name)
static std::unique_ptr
< SerializedType > makeDefaultObject (SField::ref name)
Static Public Member Functions inherited from ripple::SerializedType
static std::unique_ptr
< SerializedType > deserialize (SField::ref name)
Private Member Functions
STObject * duplicate () const
Private Attributes
boost::ptr_vector< SerializedType > mData
const SOTemplate * mType
Additional Inherited Members
Protected Attributes inherited from ripple::SerializedType
SField::ptr fName
Detailed Description
Definition at line 29 of file SerializedObject.h.
Member Typedef Documentation
typedef boost::ptr_vector<SerializedType>::const_iterator ripple::STObject::const_iterator
Definition at line 254 of file SerializedObject.h.
typedef boost::ptr_vector<SerializedType>::iterator ripple::STObject::iterator
Definition at line 253 of file SerializedObject.h.
Constructor & Destructor Documentation
ripple::STObject::STObject () inline
Definition at line 36 of file SerializedObject.h.
Referenced by duplicate(), and oClone().
                 : mType (nullptr)
     {
         ;
     }
ripple::STObject::STObject (SField::ref name) inline explicit
Definition at line 41 of file SerializedObject.h.
                                        : SerializedType (name), mType (nullptr)
     {
         ;
     }
ripple::STObject::STObject (const SOTemplate & type, SField::ref name) inline
Definition at line 46 of file SerializedObject.h.
References set().
                                                        : SerializedType (name)
     {
         set (type);
     }
ripple::STObject::STObject (const SOTemplate & type, SerializerIterator & sit, SField::ref name) inline
Definition at line 51 of file SerializedObject.h.
References set(), and setType().
                                                                                  : SerializedType (name)
     {
         set (sit);
         setType (type);
     }
ripple::STObject::STObject (SField::ref name, boost::ptr_vector< SerializedType > & data) inline
Definition at line 57 of file SerializedObject.h.
References mData.
                                                                      : SerializedType (name), mType (nullptr)
     {
         mData.swap (data);
     }
virtual ripple::STObject::~STObject () inline virtual
Definition at line 67 of file SerializedObject.h.
 { }
Member Function Documentation
virtual void ripple::STObject::add (Serializer & s) const inline virtual
Reimplemented from ripple::SerializedType.
Definition at line 92 of file SerializedObject.h.
Referenced by ripple::TransactionMetaSet::addRaw(), ripple::TransactionEngine::applyTransaction(), ripple::FeaturesImpl::doVoting(), ripple::FeeVoteImpl::doVoting(), getHash(), ripple::SerializedTransaction::getMetaSQL(), getSerializer(), ripple::SerializedValidation::getSigned(), getSigningHash(), ripple::SerializedTransaction::getSQL(), ripple::SerializedTransaction_test::run(), and ripple::SerializedObject_test::testSerialization().
     {
         add (s, true);    // just inner elements
     }
void ripple::STObject::add (Serializer & s, bool withSignature) const
Definition at line 346 of file SerializedObject.cpp.
References ripple::SerializedType::add(), ripple::Serializer::addFieldID(), ripple::SerializedType::addFieldID(), beast::field(), ripple::SField::fieldCode, ripple::SerializedType::getFName(), ripple::SerializedType::getSType(), mData, ripple::SField::shouldInclude(), and ripple::STI_NOTPRESENT.
 {
     std::map<int, const SerializedType*> fields;
     BOOST_FOREACH (const SerializedType & it, mData)
     {
         // pick out the fields and sort them
         if ((it.getSType () != STI_NOTPRESENT) && it.getFName ().shouldInclude (withSigningFields))
             fields.insert (std::make_pair (it.getFName ().fieldCode, &it));
     }
     typedef std::map<int, const SerializedType*>::value_type field_iterator;
     BOOST_FOREACH (field_iterator & it, fields)
     {
         // insert them in sorted order
         const SerializedType* field = it.second;
         field->addFieldID (s);
         field->add (s);
         if (dynamic_cast<const STArray*> (field) != nullptr)
             s.addFieldID (STI_ARRAY, 1);
         else if (dynamic_cast<const STObject*> (field) != nullptr)
             s.addFieldID (STI_OBJECT, 1);
     }
 }
int ripple::STObject::addObject (const SerializedType & t) inline
Definition at line 112 of file SerializedObject.h.
References ripple::SerializedType::clone(), and mData.
Referenced by ripple::LedgerEntrySet::calcRawMeta(), and ripple::TransactionMetaSet::getAsObject().
     {
         mData.push_back (t.clone ().release ());
         return mData.size () - 1;
     }
SerializedType& ripple::STObject::back () inline
Definition at line 143 of file SerializedObject.h.
References mData.
     {
         return mData.back ();
     }
const SerializedType& ripple::STObject::back () const inline
Definition at line 147 of file SerializedObject.h.
References mData.
     {
         return mData.back ();
     }
iterator ripple::STObject::begin () inline
Definition at line 255 of file SerializedObject.h.
References mData.
Referenced by ripple::range_begin().
     {
         return mData.begin ();
     }
const_iterator ripple::STObject::begin () const inline
Definition at line 263 of file SerializedObject.h.
References mData.
     {
         return mData.begin ();
     }
bool ripple::STObject::clearFlag (std::uint32_t f)
Definition at line 550 of file SerializedObject.cpp.
References getPField(), ripple::STUInt32::getValue(), and ripple::STUInt32::setValue().
 {
     STUInt32* t = dynamic_cast<STUInt32*> (getPField (sfFlags));
     if (!t)
         return false;
     t->setValue (t->getValue () & ~f);
     return true;
 }
bool ripple::STObject::delField (SField::ref field)
Definition at line 612 of file SerializedObject.cpp.
References getFieldIndex().
 {
     int index = getFieldIndex (field);
     if (index == -1)
         return false;
     delField (index);
     return true;
 }
void ripple::STObject::delField (int index)
Definition at line 623 of file SerializedObject.cpp.
References mData.
 {
     mData.erase (mData.begin () + index);
 }
std::unique_ptr< SerializedType > ripple::STObject::deserialize (SerializerIterator & sit, SField::ref name) static
Definition at line 302 of file SerializedObject.cpp.
References set().
Referenced by makeDeserializedObject(), and ripple::TransactionMetaSet::TransactionMetaSet().
 {
     STObject* o;
     std::unique_ptr<SerializedType> object (o = new STObject (name));
     o->set (sit, 1);
     return object;
 }
STObject* ripple::STObject::duplicate () const inline private virtual
Returns a value or throws if out of range.
This will throw if the source value cannot be represented within the destination type.
Reimplemented from ripple::SerializedType.
Definition at line 305 of file SerializedObject.h.
References STObject().
     {
         return new STObject (*this);
     }
bool ripple::STObject::empty () const inline
Definition at line 271 of file SerializedObject.h.
References mData.
Referenced by ripple::LedgerEntrySet::calcRawMeta(), getFieldAmount(), getFieldArray(), getFieldPathSet(), and getFieldV256().
     {
         return mData.empty ();
     }
iterator ripple::STObject::end () inline
Definition at line 259 of file SerializedObject.h.
References mData.
Referenced by ripple::range_end().
     {
         return mData.end ();
     }
const_iterator ripple::STObject::end () const inline
Definition at line 267 of file SerializedObject.h.
References mData.
     {
         return mData.end ();
     }
SerializedType& ripple::STObject::front () inline
Definition at line 135 of file SerializedObject.h.
References mData.
     {
         return mData.front ();
     }
const SerializedType& ripple::STObject::front () const inline
Definition at line 139 of file SerializedObject.h.
References mData.
     {
         return mData.front ();
     }
int ripple::STObject::getCount () const inline
Definition at line 152 of file SerializedObject.h.
References mData.
Referenced by ripple::SerializedLedgerEntry::getOwners(), and ripple::isAccountFieldOkay().
     {
         return mData.size ();
     }
static char const* ripple::STObject::getCountedObjectName () inline static
Definition at line 34 of file SerializedObject.h.
 { return "STObject"; }
SerializedType & ripple::STObject::getField (SField::ref field)
Definition at line 471 of file SerializedObject.cpp.
References getFieldIndex(), and getIndex().
Referenced by ripple::TransactionMetaSet::TransactionMetaSet().
 {
     int index = getFieldIndex (field);
     if (index == -1)
         throw std::runtime_error ("Field not found");
     return getIndex (index);
 }
RippleAddress ripple::STObject::getFieldAccount (SField::ref field) const
Definition at line 757 of file SerializedObject.cpp.
References ripple::SerializedType::getSType(), ripple::STAccount::getValueNCA(), peekAtPField(), and ripple::STI_NOTPRESENT.
Referenced by ripple::SerializedLedgerEntry::getOwner(), and ripple::SerializedTransaction::getSourceAccount().
 {
     const SerializedType* rf = peekAtPField (field);
     if (!rf)
         throw std::runtime_error ("Field not found");
     SerializedTypeID id = rf->getSType ();
     if (id == STI_NOTPRESENT) return RippleAddress (); // optional field not present
     const STAccount* cf = dynamic_cast<const STAccount*> (rf);
     if (!cf)
         throw std::runtime_error ("Wrong field type");
     return cf->getValueNCA ();
 }
uint160 ripple::STObject::getFieldAccount160 (SField::ref field) const
Definition at line 776 of file SerializedObject.cpp.
References ripple::SerializedType::getSType(), ripple::STAccount::getValueH160(), peekAtPField(), and ripple::STI_NOTPRESENT.
Referenced by ripple::ChangeTransactor::checkSig(), ripple::WalletAddTransactor::doApply(), ripple::RegularKeySetTransactor::doApply(), and ripple::PaymentTransactor::doApply().
 {
     uint160 a;
     const SerializedType* rf = peekAtPField (field);
     if (!rf)
         throw std::runtime_error ("Field not found");
     SerializedTypeID id = rf->getSType ();
     if (id != STI_NOTPRESENT)
     {
         const STAccount* cf = dynamic_cast<const STAccount*> (rf);
         if (!cf)
             throw std::runtime_error ("Wrong field type");
         cf->getValueH160 (a);
     }
     return a;
 }
const STAmount & ripple::STObject::getFieldAmount (SField::ref field) const
Definition at line 816 of file SerializedObject.cpp.
References empty(), ripple::SerializedType::getSType(), peekAtPField(), and ripple::STI_NOTPRESENT.
Referenced by ripple::TrustSetTransactor::doApply(), ripple::WalletAddTransactor::doApply(), ripple::PaymentTransactor::doApply(), ripple::OfferCreateTransactor::doApply(), ripple::SerializedLedgerEntry::getFirstOwner(), ripple::SerializedLedgerEntry::getSecondOwner(), ripple::SerializedTransaction::getTransactionFee(), ripple::OrderBookDB::processTxn(), and ripple::TransactionMetaSet::TransactionMetaSet().
 {
     static STAmount empty;
     const SerializedType* rf = peekAtPField (field);
     if (!rf)
         throw std::runtime_error ("Field not found");
     SerializedTypeID id = rf->getSType ();
     if (id == STI_NOTPRESENT)
         return empty; // optional field not present
     const STAmount* cf = dynamic_cast<const STAmount*> (rf);
     if (!cf)
         throw std::runtime_error ("Wrong field type");
     return *cf;
 }
const STArray & ripple::STObject::getFieldArray (SField::ref field) const
Definition at line 837 of file SerializedObject.cpp.
References empty(), ripple::SerializedType::getSType(), peekAtPField(), and ripple::STI_NOTPRESENT.
Referenced by ripple::isMemoOkay().
 {
     static STArray empty;
     const SerializedType* rf = peekAtPField (field);
     if (!rf) throw std::runtime_error ("Field not found");
     SerializedTypeID id = rf->getSType ();
     if (id == STI_NOTPRESENT) return empty;
     const STArray* cf = dynamic_cast<const STArray*> (rf);
     if (!cf)
         throw std::runtime_error ("Wrong field type");
     return *cf;
 }
uint128 ripple::STObject::getFieldH128 (SField::ref field) const
Definition at line 705 of file SerializedObject.cpp.
References ripple::SerializedType::getSType(), ripple::STHash128::getValue(), peekAtPField(), and ripple::STI_NOTPRESENT.
Referenced by ripple::AccountSetTransactor::doApply().
 {
     const SerializedType* rf = peekAtPField (field);
     if (!rf) throw std::runtime_error ("Field not found");
     SerializedTypeID id = rf->getSType ();
     if (id == STI_NOTPRESENT) return uint128 (); // optional field not present
     const STHash128* cf = dynamic_cast<const STHash128*> (rf);
     if (!cf) throw std::runtime_error ("Wrong field type");
     return cf->getValue ();
 }
uint160 ripple::STObject::getFieldH160 (SField::ref field) const
Definition at line 722 of file SerializedObject.cpp.
References ripple::SerializedType::getSType(), ripple::STHash160::getValue(), peekAtPField(), and ripple::STI_NOTPRESENT.
 {
     const SerializedType* rf = peekAtPField (field);
     if (!rf) throw std::runtime_error ("Field not found");
     SerializedTypeID id = rf->getSType ();
     if (id == STI_NOTPRESENT) return uint160 (); // optional field not present
     const STHash160* cf = dynamic_cast<const STHash160*> (rf);
     if (!cf) throw std::runtime_error ("Wrong field type");
     return cf->getValue ();
 }
uint256 ripple::STObject::getFieldH256 (SField::ref field) const
Definition at line 739 of file SerializedObject.cpp.
References ripple::SerializedType::getSType(), ripple::STHash256::getValue(), peekAtPField(), and ripple::STI_NOTPRESENT.
Referenced by ripple::ChangeTransactor::applyFeature(), ripple::Transactor::checkSeq(), ripple::compare(), ripple::AccountSetTransactor::doApply(), ripple::TransactionMetaSet::getAffectedNode(), ripple::SerializedValidation::getLedgerHash(), ripple::SerializedLedgerEntry::getThreadedTransaction(), ripple::TransactionMetaSet::isNodeAffected(), ripple::TransactionMetaSet::peekAffectedNode(), ripple::TransactionMetaSet::setAffectedNode(), ripple::SerializedObject_test::testSerialization(), ripple::SerializedLedgerEntry::thread(), and ripple::TransactionMetaSet::thread().
 {
     const SerializedType* rf = peekAtPField (field);
     if (!rf)
         throw std::runtime_error ("Field not found");
     SerializedTypeID id = rf->getSType ();
     if (id == STI_NOTPRESENT) return uint256 (); // optional field not present
     const STHash256* cf = dynamic_cast<const STHash256*> (rf);
     if (!cf) throw std::runtime_error ("Wrong field type");
     return cf->getValue ();
 }
int ripple::STObject::getFieldIndex (SField::ref field) const
Definition at line 445 of file SerializedObject.cpp.
References beast::field(), ripple::SerializedType::getFName(), ripple::SOTemplate::getIndex(), mData, and mType.
Referenced by delField(), ripple::TransactionMetaSet::getAffectedAccounts(), getField(), getPField(), ripple::SerializedLedgerEntry::hasOneOwner(), isFieldPresent(), ripple::SerializedLedgerEntry::isThreadedType(), makeFieldAbsent(), makeFieldPresent(), peekAtField(), peekAtPField(), and ripple::TransactionMetaSet::thread().
 {
     if (mType != nullptr)
         return mType->getIndex (field);
     int i = 0;
     BOOST_FOREACH (const SerializedType & elem, mData)
     {
         if (elem.getFName () == field)
             return i;
         ++i;
     }
     return -1;
 }
const STPathSet & ripple::STObject::getFieldPathSet (SField::ref field) const
Definition at line 856 of file SerializedObject.cpp.
References empty(), ripple::SerializedType::getSType(), peekAtPField(), and ripple::STI_NOTPRESENT.
Referenced by ripple::PaymentTransactor::doApply().
 {
     static STPathSet empty;
     const SerializedType* rf = peekAtPField (field);
     if (!rf) throw std::runtime_error ("Field not found");
     SerializedTypeID id = rf->getSType ();
     if (id == STI_NOTPRESENT) return empty; // optional field not present
     const STPathSet* cf = dynamic_cast<const STPathSet*> (rf);
     if (!cf) throw std::runtime_error ("Wrong field type");
     return *cf;
 }
std::string ripple::STObject::getFieldString (SField::ref field) const
Definition at line 628 of file SerializedObject.cpp.
References ripple::SerializedType::getText(), and peekAtPField().
 {
     const SerializedType* rf = peekAtPField (field);
     if (!rf) throw std::runtime_error ("Field not found");
     return rf->getText ();
 }
SField::ref ripple::STObject::getFieldSType (int index) const
Definition at line 481 of file SerializedObject.cpp.
References mData.
Referenced by ripple::SerializedLedgerEntry::getOwners().
 {
     return mData[index].getFName ();
 }
std::uint16_t ripple::STObject::getFieldU16 (SField::ref field) const
Definition at line 654 of file SerializedObject.cpp.
References ripple::SerializedType::getSType(), ripple::STUInt16::getValue(), peekAtPField(), and ripple::STI_NOTPRESENT.
Referenced by ripple::SerializedLedgerEntry::getVersion(), ripple::OrderBookDB::processTxn(), ripple::SerializedLedgerEntry::SerializedLedgerEntry(), and ripple::SerializedTransaction::SerializedTransaction().
 {
     const SerializedType* rf = peekAtPField (field);
     if (!rf) throw std::runtime_error ("Field not found");
     SerializedTypeID id = rf->getSType ();
     if (id == STI_NOTPRESENT) return 0; // optional field not present
     const STUInt16* cf = dynamic_cast<const STUInt16*> (rf);
     if (!cf) throw std::runtime_error ("Wrong field type");
     return cf->getValue ();
 }
std::uint32_t ripple::STObject::getFieldU32 (SField::ref field) const
Definition at line 671 of file SerializedObject.cpp.
References ripple::SerializedType::getSType(), ripple::STUInt32::getValue(), peekAtPField(), and ripple::STI_NOTPRESENT.
Referenced by ripple::ChangeTransactor::applyFee(), ripple::Transactor::checkSeq(), ripple::TrustSetTransactor::doApply(), ripple::OfferCancelTransactor::doApply(), ripple::AccountSetTransactor::doApply(), ripple::OfferCreateTransactor::doApply(), ripple::FeeVoteImpl::doVoting(), ripple::SerializedValidation::getFlags(), ripple::SerializedTransaction::getSequence(), ripple::SerializedValidation::getSignTime(), ripple::SerializedLedgerEntry::getThreadedLedger(), ripple::SerializedLedgerEntry::thread(), ripple::TransactionMetaSet::thread(), and ripple::TransactionMetaSet::TransactionMetaSet().
 {
     const SerializedType* rf = peekAtPField (field);
     if (!rf) throw std::runtime_error ("Field not found");
     SerializedTypeID id = rf->getSType ();
     if (id == STI_NOTPRESENT) return 0; // optional field not present
     const STUInt32* cf = dynamic_cast<const STUInt32*> (rf);
     if (!cf) throw std::runtime_error ("Wrong field type");
     return cf->getValue ();
 }
std::uint64_t ripple::STObject::getFieldU64 (SField::ref field) const
Definition at line 688 of file SerializedObject.cpp.
References ripple::SerializedType::getSType(), ripple::STUInt64::getValue(), peekAtPField(), and ripple::STI_NOTPRESENT.
Referenced by ripple::ChangeTransactor::applyFee(), and ripple::FeeVoteImpl::doVoting().
 {
     const SerializedType* rf = peekAtPField (field);
     if (!rf) throw std::runtime_error ("Field not found");
     SerializedTypeID id = rf->getSType ();
     if (id == STI_NOTPRESENT) return 0; // optional field not present
     const STUInt64* cf = dynamic_cast<const STUInt64*> (rf);
     if (!cf) throw std::runtime_error ("Wrong field type");
     return cf->getValue ();
 }
unsigned char ripple::STObject::getFieldU8 (SField::ref field) const
Definition at line 637 of file SerializedObject.cpp.
References ripple::SerializedType::getSType(), ripple::STUInt8::getValue(), peekAtPField(), and ripple::STI_NOTPRESENT.
Referenced by ripple::TransactionMetaSet::TransactionMetaSet().
 {
     const SerializedType* rf = peekAtPField (field);
     if (!rf) throw std::runtime_error ("Field not found");
     SerializedTypeID id = rf->getSType ();
     if (id == STI_NOTPRESENT) return 0; // optional field not present
     const STUInt8* cf = dynamic_cast<const STUInt8*> (rf);
     if (!cf) throw std::runtime_error ("Wrong field type");
     return cf->getValue ();
 }
const STVector256 & ripple::STObject::getFieldV256 (SField::ref field) const
Definition at line 874 of file SerializedObject.cpp.
References empty(), ripple::SerializedType::getSType(), peekAtPField(), and ripple::STI_NOTPRESENT.
 {
     static STVector256 empty;
     const SerializedType* rf = peekAtPField (field);
     if (!rf) throw std::runtime_error ("Field not found");
     SerializedTypeID id = rf->getSType ();
     if (id == STI_NOTPRESENT) return empty; // optional field not present
     const STVector256* cf = dynamic_cast<const STVector256*> (rf);
     if (!cf) throw std::runtime_error ("Wrong field type");
     return *cf;
 }
Blob ripple::STObject::getFieldVL (SField::ref field) const
Definition at line 799 of file SerializedObject.cpp.
References ripple::SerializedType::getSType(), ripple::STVariableLength::getValue(), peekAtPField(), and ripple::STI_NOTPRESENT.
Referenced by ripple::SerializedTransaction::checkSign(), ripple::WalletAddTransactor::doApply(), ripple::AccountSetTransactor::doApply(), ripple::SerializedTransaction::getSignature(), ripple::SerializedValidation::getSignature(), ripple::SerializedValidation::getSignerPublic(), ripple::SerializedTransaction::getSigningPubKey(), ripple::SerializedValidation::isValid(), ripple::SerializedValidation::SerializedValidation(), and ripple::SerializedObject_test::testSerialization().
 {
     const SerializedType* rf = peekAtPField (field);
     if (!rf) throw std::runtime_error ("Field not found");
     SerializedTypeID id = rf->getSType ();
     if (id == STI_NOTPRESENT) return Blob (); // optional field not present
     const STVariableLength* cf = dynamic_cast<const STVariableLength*> (rf);
     if (!cf) throw std::runtime_error ("Wrong field type");
     return cf->getValue ();
 }
std::uint32_t ripple::STObject::getFlags (void) const
Definition at line 566 of file SerializedObject.cpp.
References ripple::STUInt32::getValue(), and peekAtPField().
Referenced by ripple::SerializedTransaction::checkSign(), ripple::WalletAddTransactor::doApply(), ripple::TrustSetTransactor::doApply(), ripple::AccountSetTransactor::doApply(), ripple::OfferCancelTransactor::doApply(), ripple::PaymentTransactor::doApply(), ripple::RegularKeySetTransactor::doApply(), ripple::OfferCreateTransactor::doApply(), isFlag(), and ripple::SerializedObject_test::testSerialization().
 {
     const STUInt32* t = dynamic_cast<const STUInt32*> (peekAtPField (sfFlags));
     if (!t)
         return 0;
     return t->getValue ();
 }
std::string ripple::STObject::getFullText () const virtual
Reimplemented from ripple::SerializedType.
Definition at line 320 of file SerializedObject.cpp.
References beast.util.Iter::first(), ripple::SerializedType::fName, ripple::SerializedType::getFullText(), ripple::SerializedType::getSType(), mData, and ripple::STI_NOTPRESENT.
Referenced by ripple::SerializedTransaction::getFullText(), ripple::SerializedLedgerEntry::getFullText(), ripple::STArray::getFullText(), and isEquivalent().
 {
     std::string ret;
     bool first = true;
     if (fName->hasName ())
     {
         ret = fName->getName ();
         ret += " = {";
     }
     else ret = "{";
     BOOST_FOREACH (const SerializedType & it, mData)
     if (it.getSType () != STI_NOTPRESENT)
     {
         if (!first) ret += ", ";
         else first = false;
         ret += it.getFullText ();
     }
     ret += "}";
     return ret;
 }
uint256 ripple::STObject::getHash (std::uint32_t prefix) const
Definition at line 429 of file SerializedObject.cpp.
References add(), ripple::Serializer::add32(), and ripple::Serializer::getSHA512Half().
Referenced by ripple::SerializedTransaction::getTransactionID().
 {
     Serializer s;
     s.add32 (prefix);
     add (s, true);
     return s.getSHA512Half ();
 }
SerializedType& ripple::STObject::getIndex (int offset) inline
Definition at line 169 of file SerializedObject.h.
References mData.
Referenced by getField().
     {
         return mData[offset];
     }
Json::Value ripple::STObject::getJson (int options) const virtual
Reimplemented from ripple::SerializedType.
Reimplemented in ripple::SerializedTransaction, and ripple::SerializedLedgerEntry.
Definition at line 1072 of file SerializedObject.cpp.
References ripple::SerializedType::getFName(), ripple::SerializedType::getJson(), ripple::SerializedType::getName(), ripple::SerializedType::getSType(), ripple::SField::hasName(), mData, Json::objectValue, and ripple::STI_NOTPRESENT.
Referenced by ripple::SerializedLedgerEntry::getJson(), ripple::TransactionMetaSet::getJson(), ripple::SerializedTransaction::getJson(), ripple::SerializedValidation::SerializedValidation(), and ripple::SerializedObject_test::testSerialization().
 {
     Json::Value ret (Json::objectValue);
     int index = 1;
     BOOST_FOREACH (const SerializedType & it, mData)
     {
         if (it.getSType () != STI_NOTPRESENT)
         {
             if (!it.getFName ().hasName ())
                 ret[beast::lexicalCast <std::string> (index)] = it.getJson (options);
             else
                 ret[it.getName ()] = it.getJson (options);
         }
     }
     return ret;
 }
SerializedType * ripple::STObject::getPField (SField::ref field, bool createOkay = false)
Definition at line 496 of file SerializedObject.cpp.
References getFieldIndex(), getPIndex(), giveObject(), isFree(), and makeDefaultObject().
Referenced by clearFlag(), peekFieldObject(), setFieldAccount(), setFieldAmount(), setFieldH128(), setFieldH160(), setFieldH256(), setFieldPathSet(), setFieldU16(), setFieldU32(), setFieldU64(), setFieldU8(), setFieldV256(), setFieldVL(), and setFlag().
 {
     int index = getFieldIndex (field);
     if (index == -1)
     {
         if (createOkay && isFree ())
             return getPIndex (giveObject (makeDefaultObject (field)));
         return nullptr;
     }
     return getPIndex (index);
 }
SerializedType* ripple::STObject::getPIndex (int offset) inline
Definition at line 177 of file SerializedObject.h.
References mData.
Referenced by getPField(), and makeFieldPresent().
     {
         return & (mData[offset]);
     }
Serializer ripple::STObject::getSerializer () const inline
Definition at line 101 of file SerializedObject.h.
References add().
Referenced by ripple::SerializedTransaction::getJson(), and ripple::SerializedObject_test::testSerialization().
     {
         Serializer s;
         add (s);
         return s;
     }
uint256 ripple::STObject::getSigningHash (std::uint32_t prefix) const
Definition at line 437 of file SerializedObject.cpp.
References add(), ripple::Serializer::add32(), and ripple::Serializer::getSHA512Half().
Referenced by ripple::SerializedTransaction::getSigningHash(), and ripple::SerializedValidation::getSigningHash().
 {
     Serializer s;
     s.add32 (prefix);
     add (s, false);
     return s.getSHA512Half ();
 }
virtual SerializedTypeID ripple::STObject::getSType () const inline virtual
Reimplemented from ripple::SerializedType.
Reimplemented in ripple::SerializedLedgerEntry, and ripple::SerializedTransaction.
Definition at line 82 of file SerializedObject.h.
     {
         return STI_OBJECT;
     }
std::string ripple::STObject::getText () const virtual
Reimplemented from ripple::SerializedType.
Definition at line 374 of file SerializedObject.cpp.
References beast.util.Iter::first(), ripple::SerializedType::getText(), and mData.
Referenced by ripple::SerializedTransaction::getText(), ripple::SerializedLedgerEntry::getText(), and ripple::STArray::getText().
 {
     std::string ret = "{";
     bool first = false;
     BOOST_FOREACH (const SerializedType & it, mData)
     {
         if (!first)
         {
             ret += ", ";
             first = false;
         }
         ret += it.getText ();
     }
     ret += "}";
     return ret;
 }
int ripple::STObject::giveObject (std::unique_ptr< SerializedType > t) inline
Definition at line 117 of file SerializedObject.h.
References mData.
Referenced by getPField(), makeFieldPresent(), and set().
     {
         mData.push_back (t.release ());
         return mData.size () - 1;
     }
int ripple::STObject::giveObject (SerializedType * t) inline
Definition at line 122 of file SerializedObject.h.
References mData.
     {
         mData.push_back (t);
         return mData.size () - 1;
     }
bool ripple::STObject::hasMatchingEntry (const SerializedType & t)
Definition at line 310 of file SerializedObject.cpp.
References ripple::SerializedType::getFName(), and peekAtPField().
 {
     const SerializedType* o = peekAtPField (t.getFName ());
     if (!o)
         return false;
     return t == *o;
 }
virtual bool ripple::STObject::isDefault () const inline virtual
Reimplemented from ripple::SerializedType.
Definition at line 87 of file SerializedObject.h.
References mData.
     {
         return mData.empty ();
     }
bool ripple::STObject::isEquivalent (const SerializedType & t) const virtual
Reimplemented from ripple::SerializedType.
Definition at line 392 of file SerializedObject.cpp.
References getFullText(), ripple::lsDEBUG, mData, and WriteLog.
Referenced by ripple::TransactionEngine::applyTransaction().
 {
     const STObject* v = dynamic_cast<const STObject*> (&t);
     if (!v)
     {
         WriteLog (lsDEBUG, STObject) << "notEquiv " << getFullText() << " not object";
         return false;
     }
     boost::ptr_vector<SerializedType>::const_iterator it1 = mData.begin (), end1 = mData.end ();
     boost::ptr_vector<SerializedType>::const_iterator it2 = v->mData.begin (), end2 = v->mData.end ();
     while ((it1 != end1) && (it2 != end2))
     {
         if ((it1->getSType () != it2->getSType ()) || !it1->isEquivalent (*it2))
         {
             if (it1->getSType () != it2->getSType ())
             {
                 WriteLog (lsDEBUG, STObject) << "notEquiv type " << it1->getFullText() << " != "
                     <<  it2->getFullText();
             }
             else
             {
                 WriteLog (lsDEBUG, STObject) << "notEquiv " << it1->getFullText() << " != "
                     <<  it2->getFullText();
             }
             return false;
         }
         ++it1;
         ++it2;
     }
     return (it1 == end1) && (it2 == end2);
 }
bool ripple::STObject::isFieldAllowed (SField::ref field)
Definition at line 227 of file SerializedObject.cpp.
References ripple::SOTemplate::getIndex(), and mType.
 {
     if (mType == nullptr)
         return true;
     return mType->getIndex (field) != -1;
 }
bool ripple::STObject::isFieldPresent (SField::ref field) const
Definition at line 511 of file SerializedObject.cpp.
References getFieldIndex(), ripple::SerializedType::getSType(), peekAtIndex(), and ripple::STI_NOTPRESENT.
Referenced by ripple::ChangeTransactor::checkSeq(), ripple::Transactor::checkSeq(), ripple::TrustSetTransactor::doApply(), ripple::AccountSetTransactor::doApply(), ripple::RegularKeySetTransactor::doApply(), ripple::PaymentTransactor::doApply(), ripple::OfferCreateTransactor::doApply(), ripple::FeeVoteImpl::doVoting(), ripple::isMemoOkay(), ripple::SerializedLedgerEntry::isThreaded(), ripple::SerializedObject_test::testSerialization(), and ripple::TransactionMetaSet::TransactionMetaSet().
 {
     int index = getFieldIndex (field);
     if (index == -1)
         return false;
     return peekAtIndex (index).getSType () != STI_NOTPRESENT;
 }
bool ripple::STObject::isFlag (std::uint32_t f) const
Definition at line 561 of file SerializedObject.cpp.
References ripple::f, and getFlags().
 {
     return (getFlags () & f) == f;
 }
bool ripple::STObject::isFree () const inline
Definition at line 74 of file SerializedObject.h.
References mType.
Referenced by getPField(), and makeFieldPresent().
     {
         return mType == nullptr;
     }
bool ripple::STObject::isValidForType ()
Definition at line 209 of file SerializedObject.cpp.
References mData, mType, and ripple::SOTemplate::peek().
 {
     boost::ptr_vector<SerializedType>::iterator it = mData.begin ();
     for (SOTemplate::value_type const& elem : mType->peek ())
     {
         if (it == mData.end ())
             return false;
         if (elem->e_field != it->getFName ())
             return false;
         ++it;
     }
     return true;
 }
std::unique_ptr< SerializedType > ripple::STObject::makeDefaultObject (SerializedTypeID id, SField::ref name) static
Definition at line 24 of file SerializedObject.cpp.
References id, ripple::lsFATAL, ripple::STI_NOTPRESENT, and WriteLog.
Referenced by getPField(), makeDefaultObject(), makeFieldPresent(), makeNonPresentObject(), and set().
 {
     assert ((id == STI_NOTPRESENT) || (id == name.fieldType));
     switch (id)
     {
     case STI_NOTPRESENT:
         return std::unique_ptr<SerializedType> (new SerializedType (name));
     case STI_UINT8:
         return std::unique_ptr<SerializedType> (new STUInt8 (name));
     case STI_UINT16:
         return std::unique_ptr<SerializedType> (new STUInt16 (name));
     case STI_UINT32:
         return std::unique_ptr<SerializedType> (new STUInt32 (name));
     case STI_UINT64:
         return std::unique_ptr<SerializedType> (new STUInt64 (name));
     case STI_AMOUNT:
         return std::unique_ptr<SerializedType> (new STAmount (name));
     case STI_HASH128:
         return std::unique_ptr<SerializedType> (new STHash128 (name));
     case STI_HASH160:
         return std::unique_ptr<SerializedType> (new STHash160 (name));
     case STI_HASH256:
         return std::unique_ptr<SerializedType> (new STHash256 (name));
     case STI_VECTOR256:
         return std::unique_ptr<SerializedType> (new STVector256 (name));
     case STI_VL:
         return std::unique_ptr<SerializedType> (new STVariableLength (name));
     case STI_ACCOUNT:
         return std::unique_ptr<SerializedType> (new STAccount (name));
     case STI_PATHSET:
         return std::unique_ptr<SerializedType> (new STPathSet (name));
     case STI_OBJECT:
         return std::unique_ptr<SerializedType> (new STObject (name));
     case STI_ARRAY:
         return std::unique_ptr<SerializedType> (new STArray (name));
     default:
         WriteLog (lsFATAL, STObject) << "Object type: " << beast::lexicalCast <std::string> (id);
         assert (false);
         throw std::runtime_error ("Unknown object type");
     }
 }
static std::unique_ptr<SerializedType> ripple::STObject::makeDefaultObject (SField::ref name) inline static
Definition at line 247 of file SerializedObject.h.
References ripple::SField::fieldType, and makeDefaultObject().
     {
         return makeDefaultObject (name.fieldType, name);
     }
std::unique_ptr< SerializedType > ripple::STObject::makeDeserializedObject (SerializedTypeID id, SField::ref name, SerializerIterator & sit, int depth) static
Definition at line 83 of file SerializedObject.cpp.
References deserialize(), ripple::SerializedType::deserialize(), ripple::STUInt8::deserialize(), ripple::STUInt16::deserialize(), ripple::STUInt32::deserialize(), ripple::STArray::deserialize(), ripple::STUInt64::deserialize(), ripple::STAmount::deserialize(), ripple::STHash128::deserialize(), ripple::STHash160::deserialize(), ripple::STHash256::deserialize(), ripple::STVariableLength::deserialize(), ripple::STAccount::deserialize(), ripple::STPathSet::deserialize(), ripple::STVector256::deserialize(), and ripple::STI_NOTPRESENT.
Referenced by set().
 {
     switch (id)
     {
     case STI_NOTPRESENT:
         return SerializedType::deserialize (name);
     case STI_UINT8:
         return STUInt8::deserialize (sit, name);
     case STI_UINT16:
         return STUInt16::deserialize (sit, name);
     case STI_UINT32:
         return STUInt32::deserialize (sit, name);
     case STI_UINT64:
         return STUInt64::deserialize (sit, name);
     case STI_AMOUNT:
         return STAmount::deserialize (sit, name);
     case STI_HASH128:
         return STHash128::deserialize (sit, name);
     case STI_HASH160:
         return STHash160::deserialize (sit, name);
     case STI_HASH256:
         return STHash256::deserialize (sit, name);
     case STI_VECTOR256:
         return STVector256::deserialize (sit, name);
     case STI_VL:
         return STVariableLength::deserialize (sit, name);
     case STI_ACCOUNT:
         return STAccount::deserialize (sit, name);
     case STI_PATHSET:
         return STPathSet::deserialize (sit, name);
     case STI_ARRAY:
         return STArray::deserialize (sit, name);
     case STI_OBJECT:
         return STObject::deserialize (sit, name);
     default:
         throw std::runtime_error ("Unknown object type");
     }
 }
void ripple::STObject::makeFieldAbsent (SField::ref field)
Definition at line 597 of file SerializedObject.cpp.
References ripple::f, getFieldIndex(), ripple::SerializedType::getFName(), ripple::SerializedType::getSType(), makeNonPresentObject(), mData, peekAtIndex(), and ripple::STI_NOTPRESENT.
Referenced by ripple::SerializedObject_test::testSerialization().
 {
     int index = getFieldIndex (field);
     if (index == -1)
         throw std::runtime_error ("Field not found");
     const SerializedType& f = peekAtIndex (index);
     if (f.getSType () == STI_NOTPRESENT)
         return;
     mData.replace (index, makeNonPresentObject (f.getFName ()).release ());
 }
SerializedType * ripple::STObject::makeFieldPresent (SField::ref field)
Definition at line 576 of file SerializedObject.cpp.
References ripple::f, getFieldIndex(), ripple::SerializedType::getFName(), getPIndex(), ripple::SerializedType::getSType(), giveObject(), isFree(), makeDefaultObject(), makeNonPresentObject(), mData, and ripple::STI_NOTPRESENT.
Referenced by peekFieldObject(), setFieldAccount(), setFieldAmount(), setFieldH128(), setFieldH160(), setFieldH256(), setFieldPathSet(), setFieldU16(), setFieldU32(), setFieldU64(), setFieldU8(), setFieldV256(), setFieldVL(), and ripple::SerializedObject_test::testSerialization().
 {
     int index = getFieldIndex (field);
     if (index == -1)
     {
         if (!isFree ())
             throw std::runtime_error ("Field not found");
         return getPIndex (giveObject (makeNonPresentObject (field)));
     }
     SerializedType* f = getPIndex (index);
     if (f->getSType () != STI_NOTPRESENT)
         return f;
     mData.replace (index, makeDefaultObject (f->getFName ()).release ());
     return getPIndex (index);
 }
static std::unique_ptr<SerializedType> ripple::STObject::makeNonPresentObject (SField::ref name) inline static
Definition at line 242 of file SerializedObject.h.
References makeDefaultObject(), and ripple::STI_NOTPRESENT.
Referenced by makeFieldAbsent(), makeFieldPresent(), set(), and setType().
     {
         return makeDefaultObject (STI_NOTPRESENT, name);
     }
std::unique_ptr<STObject> ripple::STObject::oClone () const inline
Definition at line 62 of file SerializedObject.h.
References STObject().
     {
         return std::unique_ptr<STObject> (new STObject (*this));
     }
bool ripple::STObject::operator!= (const STObject & o) const inline
Definition at line 279 of file SerializedObject.h.
     {
         return ! (*this == o);
     }
bool ripple::STObject::operator== (const STObject & o) const
Definition at line 1089 of file SerializedObject.cpp.
References ripple::SerializedType::getFName(), ripple::SField::getName(), ripple::SerializedType::getSType(), ripple::SField::isBinary(), rocksdb::Log(), ripple::lsTRACE, beast::asio::InputParser::match(), mData, and ripple::STI_NOTPRESENT.
 {
     // This is not particularly efficient, and only compares data elements with binary representations
     int matches = 0;
     BOOST_FOREACH (const SerializedType & t, mData)
     if ((t.getSType () != STI_NOTPRESENT) && t.getFName ().isBinary ())
     {
         // each present field must have a matching field
         bool match = false;
         BOOST_FOREACH (const SerializedType & t2, obj.mData)
         if (t.getFName () == t2.getFName ())
         {
             if (t2 != t)
                 return false;
             match = true;
             ++matches;
             break;
         }
         if (!match)
         {
             Log (lsTRACE) << "STObject::operator==: no match for " << t.getFName ().getName ();
             return false;
         }
     }
     int fields = 0;
     BOOST_FOREACH (const SerializedType & t2, obj.mData)
     if ((t2.getSType () != STI_NOTPRESENT) && t2.getFName ().isBinary ())
         ++fields;
     if (fields != matches)
     {
         Log (lsTRACE) << "STObject::operator==: " << fields << " fields, " << matches << " matches";
         return false;
     }
     return true;
 }
const SerializedType & ripple::STObject::peekAtField (SField::ref field) const
Definition at line 461 of file SerializedObject.cpp.
References getFieldIndex(), and peekAtIndex().
 {
     int index = getFieldIndex (field);
     if (index == -1)
         throw std::runtime_error ("Field not found");
     return peekAtIndex (index);
 }
const SerializedType& ripple::STObject::peekAtIndex (int offset) const inline
Definition at line 165 of file SerializedObject.h.
References mData.
Referenced by ripple::TransactionMetaSet::getAffectedAccounts(), isFieldPresent(), makeFieldAbsent(), and peekAtField().
     {
         return mData[offset];
     }
const SerializedType * ripple::STObject::peekAtPField (SField::ref field) const
Definition at line 486 of file SerializedObject.cpp.
References getFieldIndex(), and peekAtPIndex().
Referenced by getFieldAccount(), getFieldAccount160(), getFieldAmount(), getFieldArray(), getFieldH128(), getFieldH160(), getFieldH256(), getFieldPathSet(), getFieldString(), getFieldU16(), getFieldU32(), getFieldU64(), getFieldU8(), getFieldV256(), getFieldVL(), getFlags(), hasMatchingEntry(), and ripple::OrderBookDB::processTxn().
 {
     int index = getFieldIndex (field);
     if (index == -1)
         return nullptr;
     return peekAtPIndex (index);
 }
const SerializedType* ripple::STObject::peekAtPIndex (int offset) const inline
Definition at line 173 of file SerializedObject.h.
References mData.
Referenced by ripple::SerializedLedgerEntry::getOwners(), ripple::isAccountFieldOkay(), and peekAtPField().
     {
         return & (mData[offset]);
     }
const boost::ptr_vector<SerializedType>& ripple::STObject::peekData () const inline
Definition at line 127 of file SerializedObject.h.
References mData.
Referenced by ripple::TransactionMetaSet::getAffectedAccounts(), and ripple::SerializedTransaction::getMentionedAccounts().
     {
         return mData;
     }
boost::ptr_vector<SerializedType>& ripple::STObject::peekData () inline
Definition at line 131 of file SerializedObject.h.
References mData.
     {
         return mData;
     }
STObject & ripple::STObject::peekFieldObject (SField::ref field)
Definition at line 521 of file SerializedObject.cpp.
References getPField(), ripple::SerializedType::getSType(), makeFieldPresent(), and ripple::STI_NOTPRESENT.
 {
     SerializedType* rf = getPField (field, true);
     if (!rf)
         throw std::runtime_error ("Field not found");
     if (rf->getSType () == STI_NOTPRESENT)
         rf = makeFieldPresent (field);
     STObject* cf = dynamic_cast<STObject*> (rf);
     if (!cf)
         throw std::runtime_error ("Wrong field type");
     return *cf;
 }
void ripple::STObject::set (const SOTemplate & type)
Definition at line 138 of file SerializedObject.cpp.
References giveObject(), makeDefaultObject(), makeNonPresentObject(), mData, mType, ripple::SOTemplate::peek(), and ripple::SOE_REQUIRED.
Referenced by deserialize(), ripple::SerializedLedgerEntry::SerializedLedgerEntry(), ripple::SerializedTransaction::SerializedTransaction(), and STObject().
 {
     mData.clear ();
     mType = &type;
     for (SOTemplate::value_type const& elem : type.peek ())
     {
         if (elem->flags != SOE_REQUIRED)
             giveObject (makeNonPresentObject (elem->e_field));
         else
             giveObject (makeDefaultObject (elem->e_field));
     }
 }
bool ripple::STObject::set (SerializerIterator & u, int depth = 0)
Definition at line 259 of file SerializedObject.cpp.
References ripple::SerializerIterator::empty(), beast::field(), ripple::SField::fieldType, ripple::SField::getField(), ripple::SerializerIterator::getFieldID(), giveObject(), ripple::SField::isInvalid(), ripple::lsWARNING, makeDeserializedObject(), mData, and WriteLog.
 {
     bool reachedEndOfObject = false;
     // Empty the destination buffer
     //
     mData.clear ();
     // Consume data in the pipe until we run out or reach the end
     //
     while (!reachedEndOfObject && !sit.empty ())
     {
         int type;
         int field;
         // Get the metadata for the next field
         //
         sit.getFieldID (type, field);
         reachedEndOfObject = (type == STI_OBJECT) && (field == 1);
         if (!reachedEndOfObject)
         {
             // Figure out the field
             //
             SField::ref fn = SField::getField (type, field);
             if (fn.isInvalid ())
             {
                 WriteLog (lsWARNING, STObject) << "Unknown field: field_type=" << type << ", field_name=" << field;
                 throw std::runtime_error ("Unknown field");
             }
             // Unflatten the field
             //
             giveObject (makeDeserializedObject (fn.fieldType, fn, sit, depth + 1));
         }
     }
     return reachedEndOfObject;
 }
void ripple::STObject::setFieldAccount (SField::ref field, const uint160 & v)
Definition at line 1012 of file SerializedObject.cpp.
References getPField(), ripple::SerializedType::getSType(), makeFieldPresent(), ripple::STAccount::setValueH160(), and ripple::STI_NOTPRESENT.
Referenced by ripple::FeaturesImpl::doVoting(), ripple::FeeVoteImpl::doVoting(), setFieldAccount(), and ripple::SerializedTransaction::setSourceAccount().
 {
     SerializedType* rf = getPField (field, true);
     if (!rf) throw std::runtime_error ("Field not found");
     if (rf->getSType () == STI_NOTPRESENT) rf = makeFieldPresent (field);
     STAccount* cf = dynamic_cast<STAccount*> (rf);
     if (!cf) throw std::runtime_error ("Wrong field type");
     cf->setValueH160 (v);
 }
void ripple::STObject::setFieldAccount (SField::ref field, const RippleAddress & addr) inline
Definition at line 217 of file SerializedObject.h.
References ripple::RippleAddress::getAccountID(), and setFieldAccount().
     {
         setFieldAccount (field, addr.getAccountID ());
     }
void ripple::STObject::setFieldAmount (SField::ref field, const STAmount & v)
Definition at line 1042 of file SerializedObject.cpp.
References getPField(), ripple::SerializedType::getSType(), makeFieldPresent(), and ripple::STI_NOTPRESENT.
Referenced by ripple::TransactionMetaSet::getAsObject(), and ripple::SerializedTransaction::setTransactionFee().
 {
     SerializedType* rf = getPField (field, true);
     if (!rf) throw std::runtime_error ("Field not found");
     if (rf->getSType () == STI_NOTPRESENT) rf = makeFieldPresent (field);
     STAmount* cf = dynamic_cast<STAmount*> (rf);
     if (!cf) throw std::runtime_error ("Wrong field type");
     (*cf) = v;
 }
void ripple::STObject::setFieldH128 (SField::ref field, const uint128 & v)
Definition at line 952 of file SerializedObject.cpp.
References getPField(), ripple::SerializedType::getSType(), makeFieldPresent(), ripple::STHash128::setValue(), and ripple::STI_NOTPRESENT.
 {
     SerializedType* rf = getPField (field, true);
     if (!rf) throw std::runtime_error ("Field not found");
     if (rf->getSType () == STI_NOTPRESENT) rf = makeFieldPresent (field);
     STHash128* cf = dynamic_cast<STHash128*> (rf);
     if (!cf) throw std::runtime_error ("Wrong field type");
     cf->setValue (v);
 }
void ripple::STObject::setFieldH160 (SField::ref field, const uint160 & v)
Definition at line 967 of file SerializedObject.cpp.
References getPField(), ripple::SerializedType::getSType(), makeFieldPresent(), ripple::STHash160::setValue(), and ripple::STI_NOTPRESENT.
 {
     SerializedType* rf = getPField (field, true);
     if (!rf) throw std::runtime_error ("Field not found");
     if (rf->getSType () == STI_NOTPRESENT) rf = makeFieldPresent (field);
     STHash160* cf = dynamic_cast<STHash160*> (rf);
     if (!cf) throw std::runtime_error ("Wrong field type");
     cf->setValue (v);
 }
void ripple::STObject::setFieldH256 (SField::ref field, uint256 const & v)
Definition at line 982 of file SerializedObject.cpp.
References getPField(), ripple::SerializedType::getSType(), makeFieldPresent(), ripple::STHash256::setValue(), and ripple::STI_NOTPRESENT.
Referenced by ripple::FeaturesImpl::doVoting(), ripple::TransactionMetaSet::getAffectedNode(), ripple::SerializedValidation::SerializedValidation(), ripple::TransactionMetaSet::setAffectedNode(), ripple::SerializedLedgerEntry::thread(), and ripple::TransactionMetaSet::thread().
 {
     SerializedType* rf = getPField (field, true);
     if (!rf) throw std::runtime_error ("Field not found");
     if (rf->getSType () == STI_NOTPRESENT) rf = makeFieldPresent (field);
     STHash256* cf = dynamic_cast<STHash256*> (rf);
     if (!cf) throw std::runtime_error ("Wrong field type");
     cf->setValue (v);
 }
void ripple::STObject::setFieldPathSet (SField::ref field, const STPathSet & v)
Definition at line 1057 of file SerializedObject.cpp.
References getPField(), ripple::SerializedType::getSType(), makeFieldPresent(), and ripple::STI_NOTPRESENT.
 {
     SerializedType* rf = getPField (field, true);
     if (!rf) throw std::runtime_error ("Field not found");
     if (rf->getSType () == STI_NOTPRESENT) rf = makeFieldPresent (field);
     STPathSet* cf = dynamic_cast<STPathSet*> (rf);
     if (!cf) throw std::runtime_error ("Wrong field type");
     (*cf) = v;
 }
void ripple::STObject::setFieldU16 (SField::ref field, std::uint16_t v)
Definition at line 907 of file SerializedObject.cpp.
References getPField(), ripple::SerializedType::getSType(), makeFieldPresent(), ripple::STUInt16::setValue(), and ripple::STI_NOTPRESENT.
Referenced by ripple::TransactionMetaSet::getAffectedNode(), ripple::SerializedLedgerEntry::SerializedLedgerEntry(), and ripple::TransactionMetaSet::setAffectedNode().
 {
     SerializedType* rf = getPField (field, true);
     if (!rf) throw std::runtime_error ("Field not found");
     if (rf->getSType () == STI_NOTPRESENT) rf = makeFieldPresent (field);
     STUInt16* cf = dynamic_cast<STUInt16*> (rf);
     if (!cf) throw std::runtime_error ("Wrong field type");
     cf->setValue (v);
 }
void ripple::STObject::setFieldU32 (SField::ref field, std::uint32_t v)
Definition at line 922 of file SerializedObject.cpp.
References getPField(), ripple::SerializedType::getSType(), makeFieldPresent(), ripple::STUInt32::setValue(), and ripple::STI_NOTPRESENT.
Referenced by ripple::FeeVoteImpl::doValidation(), ripple::FeeVoteImpl::doVoting(), ripple::TransactionMetaSet::getAsObject(), ripple::SerializedValidation::SerializedValidation(), ripple::SerializedTransaction::setSequence(), ripple::SerializedLedgerEntry::thread(), and ripple::TransactionMetaSet::thread().
 {
     SerializedType* rf = getPField (field, true);
     if (!rf) throw std::runtime_error ("Field not found");
     if (rf->getSType () == STI_NOTPRESENT) rf = makeFieldPresent (field);
     STUInt32* cf = dynamic_cast<STUInt32*> (rf);
     if (!cf) throw std::runtime_error ("Wrong field type");
     cf->setValue (v);
 }
void ripple::STObject::setFieldU64 (SField::ref field, std::uint64_t v)
Definition at line 937 of file SerializedObject.cpp.
References getPField(), ripple::SerializedType::getSType(), makeFieldPresent(), ripple::STUInt64::setValue(), and ripple::STI_NOTPRESENT.
Referenced by ripple::FeeVoteImpl::doValidation(), and ripple::FeeVoteImpl::doVoting().
 {
     SerializedType* rf = getPField (field, true);
     if (!rf) throw std::runtime_error ("Field not found");
     if (rf->getSType () == STI_NOTPRESENT) rf = makeFieldPresent (field);
     STUInt64* cf = dynamic_cast<STUInt64*> (rf);
     if (!cf) throw std::runtime_error ("Wrong field type");
     cf->setValue (v);
 }
void ripple::STObject::setFieldU8 (SField::ref field, unsigned char v)
Definition at line 892 of file SerializedObject.cpp.
References getPField(), ripple::SerializedType::getSType(), makeFieldPresent(), ripple::STUInt8::setValue(), and ripple::STI_NOTPRESENT.
Referenced by ripple::TransactionMetaSet::getAsObject().
 {
     SerializedType* rf = getPField (field, true);
     if (!rf) throw std::runtime_error ("Field not found");
     if (rf->getSType () == STI_NOTPRESENT) rf = makeFieldPresent (field);
     STUInt8* cf = dynamic_cast<STUInt8*> (rf);
     if (!cf) throw std::runtime_error ("Wrong field type");
     cf->setValue (v);
 }
void ripple::STObject::setFieldV256 (SField::ref field, const STVector256 & v)
Definition at line 997 of file SerializedObject.cpp.
References getPField(), ripple::SerializedType::getSType(), makeFieldPresent(), ripple::STVector256::setValue(), and ripple::STI_NOTPRESENT.
Referenced by ripple::FeaturesImpl::doValidation().
 {
     SerializedType* rf = getPField (field, true);
     if (!rf) throw std::runtime_error ("Field not found");
     if (rf->getSType () == STI_NOTPRESENT) rf = makeFieldPresent (field);
     STVector256* cf = dynamic_cast<STVector256*> (rf);
     if (!cf) throw std::runtime_error ("Wrong field type");
     cf->setValue (v);
 }
void ripple::STObject::setFieldVL (SField::ref field, Blob const & v)
Definition at line 1027 of file SerializedObject.cpp.
References getPField(), ripple::SerializedType::getSType(), makeFieldPresent(), ripple::STVariableLength::setValue(), and ripple::STI_NOTPRESENT.
Referenced by ripple::SerializedTransaction_test::run(), ripple::SerializedValidation::SerializedValidation(), ripple::SerializedTransaction::setSignature(), ripple::SerializedTransaction::setSigningPubKey(), ripple::SerializedValidation::sign(), ripple::SerializedTransaction::sign(), and ripple::SerializedObject_test::testSerialization().
 {
     SerializedType* rf = getPField (field, true);
     if (!rf) throw std::runtime_error ("Field not found");
     if (rf->getSType () == STI_NOTPRESENT) rf = makeFieldPresent (field);
     STVariableLength* cf = dynamic_cast<STVariableLength*> (rf);
     if (!cf) throw std::runtime_error ("Wrong field type");
     cf->setValue (v);
 }
bool ripple::STObject::setFlag (std::uint32_t f)
Definition at line 539 of file SerializedObject.cpp.
References ripple::f, getPField(), ripple::STUInt32::getValue(), and ripple::STUInt32::setValue().
Referenced by ripple::SerializedValidation::SerializedValidation(), and ripple::SerializedValidation::sign().
 {
     STUInt32* t = dynamic_cast<STUInt32*> (getPField (sfFlags, true));
     if (!t)
         return false;
     t->setValue (t->getValue () | f);
     return true;
 }
bool ripple::STObject::setType (const SOTemplate & type)
Definition at line 152 of file SerializedObject.cpp.
References ripple::SerializedType::getFName(), ripple::SField::getName(), ripple::SField::isDiscardable(), ripple::lsWARNING, makeNonPresentObject(), beast::asio::InputParser::match(), mData, mType, ripple::SOTemplate::peek(), ripple::SOE_DEFAULT, ripple::SOE_REQUIRED, and WriteLog.
Referenced by ripple::SerializedLedgerEntry::SerializedLedgerEntry(), ripple::SerializedTransaction::SerializedTransaction(), and STObject().
 {
     boost::ptr_vector<SerializedType> newData (type.peek ().size ());
     bool valid = true;
     mType = &type;
     for (SOTemplate::value_type const& elem : type.peek ())
     {
         bool match = false;
         for (boost::ptr_vector<SerializedType>::iterator it = mData.begin (); it != mData.end (); ++it)
             if (it->getFName () == elem->e_field)
             {
                 // matching entry, move to new vector
                 match = true;
                 if ((elem->flags == SOE_DEFAULT) && it->isDefault ())
                 {
                     WriteLog (lsWARNING, STObject) << "setType( " << getFName ().getName () << ") invalid default "
                                                    << elem->e_field.fieldName;
                     valid = false;
                 }
                 newData.push_back (mData.release (it).release ()); // CAUTION: This renders 'it' invalid
                 break;
             }
         if (!match)
         {
             // no match found
             if (elem->flags == SOE_REQUIRED)
             {
                 WriteLog (lsWARNING, STObject) << "setType( " << getFName ().getName () << ") invalid missing "
                                                << elem->e_field.fieldName;
                 valid = false;
             }
             newData.push_back (makeNonPresentObject (elem->e_field).release ());
         }
     }
     BOOST_FOREACH (const SerializedType & t, mData)
     {
         // Anything left over must be discardable
         if (!t.getFName ().isDiscardable ())
         {
             WriteLog (lsWARNING, STObject) << "setType( " << getFName ().getName () << ") invalid leftover "
                                            << t.getFName ().getName ();
             valid = false;
         }
     }
     mData.swap (newData);
     return valid;
 }
Member Data Documentation
boost::ptr_vector<SerializedType> ripple::STObject::mData private
Definition at line 311 of file SerializedObject.h.
Referenced by add(), addObject(), back(), begin(), delField(), empty(), end(), front(), getCount(), getFieldIndex(), getFieldSType(), getFullText(), getIndex(), getJson(), getPIndex(), getText(), giveObject(), isDefault(), isEquivalent(), isValidForType(), makeFieldAbsent(), makeFieldPresent(), operator==(), peekAtIndex(), peekAtPIndex(), peekData(), set(), setType(), and STObject().
const SOTemplate* ripple::STObject::mType private
Definition at line 312 of file SerializedObject.h.
Referenced by getFieldIndex(), isFieldAllowed(), isFree(), isValidForType(), set(), and setType().
The documentation for this class was generated from the following files:
rippled/src/ripple_data/protocol/SerializedObject.h
rippled/src/ripple_data/protocol/SerializedObject.cpp