rippled: ripple::HTTP::Door Class Reference
ripple::HTTP::Door Class Reference
#include <Door.h>
Public Types
typedef beast::SharedPtr< Door > Ptr
Public Member Functions
Door (ServerImpl &impl, Port const &port)
~Door ()
Port const & port () const
void cancel ()
void failed (error_code ec)
void asyncHandlersComplete ()
void async_accept ()
void handle_accept (error_code ec, Peer::Ptr peer, CompletionCounter)
Public Member Functions inherited from beast::SharedObject
void incReferenceCount () const noexcept
void decReferenceCount () const
int getReferenceCount () const noexcept
Public Member Functions inherited from beast::asio::AsyncObject< Door >
~AsyncObject ()
void addReference ()
void removeReference ()
Public Attributes
ServerImpl & m_impl
acceptor m_acceptor
Port m_port
Additional Inherited Members
Protected Member Functions inherited from beast::SharedObject
SharedObject ()
virtual ~SharedObject ()
virtual void destroy () const
void resetReferenceCount () noexcept
Detailed Description
A listening socket.
Definition at line 27 of file Door.h.
Member Typedef Documentation
typedef beast::SharedPtr<Door> ripple::HTTP::Door::Ptr
Definition at line 34 of file Door.h.
Constructor & Destructor Documentation
ripple::HTTP::Door::Door (ServerImpl & impl, Port const & port) inline
Definition at line 40 of file Door.h.
References ripple::HTTP::ServerImpl::add(), async_accept(), beast::Journal::error, beast::Journal::info, ripple::HTTP::ServerImpl::journal(), m_acceptor, m_impl, and ripple::HTTP::to_string().
         : m_impl (impl)
         , m_acceptor (m_impl.get_io_service(), to_asio (port))
         , m_port (port)
     {
         m_impl.add (*this);
         error_code ec;
         m_acceptor.set_option (acceptor::reuse_address (true), ec);
         if (ec)
         {
             m_impl.journal().error <<
                 "Error setting acceptor socket option: " << ec.message();
         }
         if (! ec)
         {
             m_impl.journal().info << "Bound to endpoint " <<
                 to_string (m_acceptor.local_endpoint());
             async_accept();
         }
         else
         {
             m_impl.journal().error << "Error binding to endpoint " <<
                 to_string (m_acceptor.local_endpoint()) <<
                 ", '" << ec.message() << "'";
         }
     }
ripple::HTTP::Door::~Door () inline
Definition at line 71 of file Door.h.
References m_impl, and ripple::HTTP::ServerImpl::remove().
     {
         m_impl.remove (*this);
     }
Member Function Documentation
void ripple::HTTP::Door::async_accept () inline
Definition at line 94 of file Door.h.
References ripple::HTTP::Peer::get_socket(), handle_accept(), m_acceptor, m_impl, and m_port.
Referenced by Door(), and handle_accept().
     {
         Peer* peer (new Peer (m_impl, m_port));
         m_acceptor.async_accept (peer->get_socket(), boost::bind (
             &Door::handle_accept, Ptr(this),
                 boost::asio::placeholders::error,
                     Peer::Ptr (peer), CompletionCounter (this)));
     }
void ripple::HTTP::Door::asyncHandlersComplete () inline
Definition at line 90 of file Door.h.
     {
     }
void ripple::HTTP::Door::cancel () inline
Definition at line 81 of file Door.h.
References m_acceptor.
     {
         m_acceptor.cancel();
     }
void ripple::HTTP::Door::failed (error_code ec) inline
Definition at line 86 of file Door.h.
     {
     }
void ripple::HTTP::Door::handle_accept (error_code ec, Peer::Ptr peer, CompletionCounter) inline
Definition at line 103 of file Door.h.
References async_accept(), beast::Journal::error, ripple::HTTP::ServerImpl::journal(), and m_impl.
Referenced by async_accept().
     {
         if (ec == boost::asio::error::operation_aborted)
             return;
         if (ec)
         {
             m_impl.journal().error << "Accept failed: " << ec.message();
             return;
         }
         async_accept();
         peer->handle_accept();
     }
Port const& ripple::HTTP::Door::port () const inline
Definition at line 76 of file Door.h.
References m_port.
     {
         return m_port;
     }
Member Data Documentation
acceptor ripple::HTTP::Door::m_acceptor
Definition at line 37 of file Door.h.
Referenced by async_accept(), cancel(), and Door().
ServerImpl& ripple::HTTP::Door::m_impl
Definition at line 36 of file Door.h.
Referenced by async_accept(), Door(), handle_accept(), and ~Door().
Port ripple::HTTP::Door::m_port
Definition at line 38 of file Door.h.
Referenced by async_accept(), and port().
The documentation for this class was generated from the following file:
rippled/src/ripple/http/impl/Door.h