rippled: rocksdb::BlockBasedTableBuilder Class Reference
rocksdb::BlockBasedTableBuilder Class Reference
#include <block_based_table_builder.h>
Classes
struct Rep
Public Member Functions
BlockBasedTableBuilder (const Options &options, WritableFile *file, FlushBlockPolicyFactory *flush_block_policy_factory, CompressionType compression_type)
~BlockBasedTableBuilder ()
void Add (const Slice &key, const Slice &value) override
Status status () const override
Status Finish () override
void Abandon () override
uint64_t NumEntries () const override
uint64_t FileSize () const override
Public Member Functions inherited from rocksdb::TableBuilder
virtual ~TableBuilder ()
Private Member Functions
bool ok () const
void WriteBlock (BlockBuilder *block, BlockHandle *handle)
void WriteRawBlock (const Slice &data, CompressionType, BlockHandle *handle)
Status InsertBlockInCache (const Slice &block_contents, const CompressionType type, const BlockHandle *handle)
void Flush ()
BlockBasedTableBuilder (const BlockBasedTableBuilder &)=delete
void operator= (const BlockBasedTableBuilder &)=delete
Private Attributes
Rep * rep_
Detailed Description
Definition at line 24 of file block_based_table_builder.h.
Constructor & Destructor Documentation
rocksdb::BlockBasedTableBuilder::BlockBasedTableBuilder (const Options & options, WritableFile * file, FlushBlockPolicyFactory * flush_block_policy_factory, CompressionType compression_type)
Definition at line 119 of file block_based_table_builder.cc.
References rocksdb::Options::block_cache_compressed, rocksdb::BlockBasedTableBuilder::Rep::compressed_cache_key_prefix, rocksdb::BlockBasedTableBuilder::Rep::compressed_cache_key_prefix_size, rocksdb::BlockBasedTableBuilder::Rep::filter_block, rocksdb::BlockBasedTable::GenerateCachePrefix(), rep_, and rocksdb::FilterBlockBuilder::StartBlock().
     : rep_(new Rep(options,
                    file, flush_block_policy_factory, compression_type)) {
   if (rep_->filter_block != nullptr) {
     rep_->filter_block->StartBlock(0);
   }
   if (options.block_cache_compressed.get() != nullptr) {
     BlockBasedTable::GenerateCachePrefix(options.block_cache_compressed, file,
                                &rep_->compressed_cache_key_prefix[0],
                                &rep_->compressed_cache_key_prefix_size);
   }
 }
rocksdb::BlockBasedTableBuilder::~BlockBasedTableBuilder ()
Definition at line 136 of file block_based_table_builder.cc.
References rocksdb::BlockBasedTableBuilder::Rep::closed, rocksdb::BlockBasedTableBuilder::Rep::filter_block, and rep_.
{
   assert(rep_->closed);  // Catch errors where caller forgot to call Finish()
   delete rep_->filter_block;
   delete rep_;
 }
rocksdb::BlockBasedTableBuilder::BlockBasedTableBuilder (const BlockBasedTableBuilder &) private delete
Member Function Documentation
void rocksdb::BlockBasedTableBuilder::Abandon () override virtual
Implements rocksdb::TableBuilder.
Definition at line 552 of file block_based_table_builder.cc.
References rocksdb::BlockBasedTableBuilder::Rep::closed, and rep_.
{
   Rep* r = rep_;
   assert(!r->closed);
   r->closed = true;
 }
void rocksdb::BlockBasedTableBuilder::Add (const Slice & key, const Slice & value) override virtual
Implements rocksdb::TableBuilder.
Definition at line 142 of file block_based_table_builder.cc.
References rocksdb::BlockBuilder::Add(), rocksdb::FilterBlockBuilder::AddKey(), rocksdb::BlockBasedTableBuilder::Rep::closed, rocksdb::Options::comparator, rocksdb::Comparator::Compare(), rocksdb::Slice::data(), rocksdb::BlockBasedTableBuilder::Rep::data_block, rocksdb::BlockBuilder::empty(), rocksdb::BlockHandle::EncodeTo(), rocksdb::BlockBasedTableBuilder::Rep::filter_block, rocksdb::Comparator::FindShortestSeparator(), Flush(), rocksdb::BlockBasedTableBuilder::Rep::flush_block_policy, rocksdb::BlockBasedTableBuilder::Rep::index_block, rocksdb::Options::info_log, rocksdb::BlockBasedTableBuilder::Rep::last_key, rocksdb::TableProperties::num_entries, rocksdb::Status::ok(), ok(), rocksdb::BlockBasedTableBuilder::Rep::options, rocksdb::BlockBasedTableBuilder::Rep::pending_handle, rocksdb::BlockBasedTableBuilder::Rep::props, rocksdb::TableProperties::raw_key_size, rocksdb::TableProperties::raw_value_size, rep_, rocksdb::Slice::size(), and rocksdb::Options::table_properties_collectors.
Referenced by rocksdb::BlockBasedTableConstructor::FinishImpl().
{
   Rep* r = rep_;
   assert(!r->closed);
   if (!ok()) return;
   if (r->props.num_entries > 0) {
     assert(r->options.comparator->Compare(key, Slice(r->last_key)) > 0);
   }
   auto should_flush = r->flush_block_policy->Update(key, value);
   if (should_flush) {
     assert(!r->data_block.empty());
     Flush();
     // Add item to index block.
     // We do not emit the index entry for a block until we have seen the
     // first key for the next data block.  This allows us to use shorter
     // keys in the index block.  For example, consider a block boundary
     // between the keys "the quick brown fox" and "the who".  We can use
     // "the r" as the key for the index block entry since it is >= all
     // entries in the first block and < all entries in subsequent
     // blocks.
     if (ok()) {
       r->options.comparator->FindShortestSeparator(&r->last_key, key);
       std::string handle_encoding;
       r->pending_handle.EncodeTo(&handle_encoding);
       r->index_block.Add(r->last_key, Slice(handle_encoding));
     }
   }
   if (r->filter_block != nullptr) {
     r->filter_block->AddKey(key);
   }
   r->last_key.assign(key.data(), key.size());
   r->data_block.Add(key, value);
   r->props.num_entries++;
   r->props.raw_key_size += key.size();
   r->props.raw_value_size += value.size();
   for (auto collector : r->options.table_properties_collectors) {
     Status s = collector->Add(key, value);
     if (!s.ok()) {
       LogPropertiesCollectionError(
           r->options.info_log.get(),
           "Add", /* method */
           collector->Name()
       );
     }
   }
 }
uint64_t rocksdb::BlockBasedTableBuilder::FileSize () const override virtual
Implements rocksdb::TableBuilder.
Definition at line 562 of file block_based_table_builder.cc.
References rocksdb::BlockBasedTableBuilder::Rep::offset, and rep_.
{
   return rep_->offset;
 }
Status rocksdb::BlockBasedTableBuilder::Finish () override virtual
Implements rocksdb::TableBuilder.
Definition at line 358 of file block_based_table_builder.cc.
References rocksdb::BlockBuilder::Add(), rocksdb::WritableFile::Append(), rocksdb::Options::block_restart_interval, rocksdb::BytewiseComparator(), rocksdb::BlockBasedTableBuilder::Rep::closed, rocksdb::Options::comparator, rocksdb::BlockBuilder::CurrentSizeEstimate(), rocksdb::BlockBasedTableBuilder::Rep::data_block, rocksdb::TableProperties::data_size, rocksdb::BlockBuilder::empty(), rocksdb::BlockHandle::EncodeTo(), rocksdb::Footer::EncodeTo(), rocksdb::BlockBasedTableBuilder::Rep::file, rocksdb::BlockBasedTableBuilder::Rep::filter_block, rocksdb::Options::filter_policy, rocksdb::TableProperties::filter_size, rocksdb::Comparator::FindShortSuccessor(), rocksdb::FilterBlockBuilder::Finish(), Flush(), rocksdb::BlockBasedTableBuilder::Rep::index_block, rocksdb::TableProperties::index_size, rocksdb::Options::info_log, rocksdb::kBlockTrailerSize, rocksdb::BlockBasedTablePropertiesNames::kDataSize, rocksdb::BlockBasedTable::kFilterBlockPrefix, rocksdb::BlockBasedTablePropertiesNames::kFilterPolicy, rocksdb::BlockBasedTablePropertiesNames::kFilterSize, rocksdb::BlockBasedTablePropertiesNames::kIndexSize, rocksdb::kNoCompression, rocksdb::BlockBasedTablePropertiesNames::kNumDataBlocks, rocksdb::BlockBasedTablePropertiesNames::kNumEntries, rocksdb::BlockBasedTable::kPropertiesBlock, rocksdb::BlockBasedTablePropertiesNames::kRawKeySize, rocksdb::BlockBasedTablePropertiesNames::kRawValueSize, rocksdb::BlockBasedTableBuilder::Rep::last_key, rocksdb::Log(), rocksdb::FilterPolicy::Name(), rocksdb::TableProperties::num_data_blocks, rocksdb::TableProperties::num_entries, rocksdb::BlockBasedTableBuilder::Rep::offset, rocksdb::Status::ok(), ok(), rocksdb::BlockBasedTableBuilder::Rep::options, rocksdb::BlockBasedTableBuilder::Rep::pending_handle, rocksdb::BlockBasedTableBuilder::Rep::props, rocksdb::TableProperties::raw_key_size, rocksdb::TableProperties::raw_value_size, rep_, rocksdb::Footer::set_index_handle(), rocksdb::Footer::set_metaindex_handle(), rocksdb::BlockBasedTableBuilder::Rep::status, rocksdb::Options::table_properties_collectors, rocksdb::TableProperties::ToString(), WriteBlock(), and WriteRawBlock().
{
   Rep* r = rep_;
   bool empty_data_block = r->data_block.empty();
   Flush();
   assert(!r->closed);
   r->closed = true;
   BlockHandle filter_block_handle,
               metaindex_block_handle,
               index_block_handle;
   // Write filter block
   if (ok() && r->filter_block != nullptr) {
     auto filter_contents = r->filter_block->Finish();
     r->props.filter_size = filter_contents.size();
     WriteRawBlock(filter_contents, kNoCompression, &filter_block_handle);
   }
   // To make sure properties block is able to keep the accurate size of index
   // block, we will finish writing all index entries here and flush them
   // to storage after metaindex block is written.
   if (ok() && !empty_data_block) {
     r->options.comparator->FindShortSuccessor(&r->last_key);
     std::string handle_encoding;
     r->pending_handle.EncodeTo(&handle_encoding);
     r->index_block.Add(r->last_key, handle_encoding);
   }
   // Write meta blocks and metaindex block with the following order.
   //    1. [meta block: filter]
   //    2. [meta block: properties]
   //    3. [metaindex block]
   if (ok()) {
     // We use `BytewiseComparator` as the comparator for meta block.
     BlockBuilder meta_index_block(
         r->options.block_restart_interval,
         BytewiseComparator()
     );
     // Key: meta block name
     // Value: block handle to that meta block
     BytewiseSortedMap meta_block_handles;
     // Write filter block.
     if (r->filter_block != nullptr) {
       // Add mapping from "<filter_block_prefix>.Name" to location
       // of filter data.
       std::string key = BlockBasedTable::kFilterBlockPrefix;
       key.append(r->options.filter_policy->Name());
       std::string handle_encoding;
       filter_block_handle.EncodeTo(&handle_encoding);
       meta_block_handles.insert(
           std::make_pair(key, handle_encoding)
       );
     }
     // Write properties block.
     {
       BlockBuilder properties_block(
           r->options.block_restart_interval,
           BytewiseComparator()
       );
       BytewiseSortedMap properties;
       // Add basic properties
       AddProperties(
           properties,
           BlockBasedTablePropertiesNames::kRawKeySize,
           r->props.raw_key_size
       );
       AddProperties(
           properties,
           BlockBasedTablePropertiesNames::kRawValueSize,
           r->props.raw_value_size
       );
       AddProperties(
           properties,
           BlockBasedTablePropertiesNames::kDataSize,
           r->props.data_size
       );
       r->props.index_size =
         r->index_block.CurrentSizeEstimate() + kBlockTrailerSize;
       AddProperties(
           properties,
           BlockBasedTablePropertiesNames::kIndexSize,
           r->props.index_size
       );
       AddProperties(
           properties,
           BlockBasedTablePropertiesNames::kNumEntries,
           r->props.num_entries
       );
       AddProperties(
           properties,
           BlockBasedTablePropertiesNames::kNumDataBlocks,
           r->props.num_data_blocks);
       if (r->filter_block != nullptr) {
         properties.insert({
               BlockBasedTablePropertiesNames::kFilterPolicy,
               r->options.filter_policy->Name()
         });
       }
       AddProperties(
           properties,
           BlockBasedTablePropertiesNames::kFilterSize,
           r->props.filter_size
       );
       for (auto collector : r->options.table_properties_collectors) {
         TableProperties::UserCollectedProperties user_collected_properties;
         Status s =
           collector->Finish(&user_collected_properties);
         if (!s.ok()) {
           LogPropertiesCollectionError(
               r->options.info_log.get(),
               "Finish", /* method */
               collector->Name()
           );
         } else {
           properties.insert(
               user_collected_properties.begin(),
               user_collected_properties.end()
           );
         }
       }
       for (const auto& stat : properties) {
         properties_block.Add(stat.first, stat.second);
       }
       BlockHandle properties_block_handle;
       WriteBlock(&properties_block, &properties_block_handle);
       std::string handle_encoding;
       properties_block_handle.EncodeTo(&handle_encoding);
       meta_block_handles.insert(
           { BlockBasedTable::kPropertiesBlock, handle_encoding }
       );
     }  // end of properties block writing
     for (const auto& metablock : meta_block_handles) {
       meta_index_block.Add(metablock.first, metablock.second);
     }
     WriteBlock(&meta_index_block, &metaindex_block_handle);
   }  // meta blocks and metaindex block.
   // Write index block
   if (ok()) {
     WriteBlock(&r->index_block, &index_block_handle);
   }
   // Write footer
   if (ok()) {
     Footer footer;
     footer.set_metaindex_handle(metaindex_block_handle);
     footer.set_index_handle(index_block_handle);
     std::string footer_encoding;
     footer.EncodeTo(&footer_encoding);
     r->status = r->file->Append(footer_encoding);
     if (r->status.ok()) {
       r->offset += footer_encoding.size();
     }
   }
   // Print out the table stats
   if (ok()) {
     // user collected properties
     std::string user_collected;
     user_collected.reserve(1024);
     for (auto collector : r->options.table_properties_collectors) {
       for (const auto& prop : collector->GetReadableProperties()) {
         user_collected.append(prop.first);
         user_collected.append("=");
         user_collected.append(prop.second);
         user_collected.append("; ");
       }
     }
     Log(
         r->options.info_log,
         "Table was constructed:\n"
         "  basic properties: %s\n"
         "  user collected properties: %s",
         r->props.ToString().c_str(),
         user_collected.c_str()
     );
   }
   return r->status;
 }
void rocksdb::BlockBasedTableBuilder::Flush () private
Definition at line 193 of file block_based_table_builder.cc.
References rocksdb::BlockBasedTableBuilder::Rep::closed, rocksdb::BlockBasedTableBuilder::Rep::data_block, rocksdb::TableProperties::data_size, rocksdb::BlockBuilder::empty(), rocksdb::BlockBasedTableBuilder::Rep::file, rocksdb::BlockBasedTableBuilder::Rep::filter_block, rocksdb::WritableFile::Flush(), rocksdb::TableProperties::num_data_blocks, rocksdb::BlockBasedTableBuilder::Rep::offset, ok(), rocksdb::BlockBasedTableBuilder::Rep::pending_handle, rocksdb::BlockBasedTableBuilder::Rep::props, rep_, rocksdb::FilterBlockBuilder::StartBlock(), rocksdb::BlockBasedTableBuilder::Rep::status, and WriteBlock().
Referenced by Add(), and Finish().
{
   Rep* r = rep_;
   assert(!r->closed);
   if (!ok()) return;
   if (r->data_block.empty()) return;
   WriteBlock(&r->data_block, &r->pending_handle);
   if (ok()) {
     r->status = r->file->Flush();
   }
   if (r->filter_block != nullptr) {
     r->filter_block->StartBlock(r->offset);
   }
   r->props.data_size = r->offset;
   ++r->props.num_data_blocks;
 }
Status rocksdb::BlockBasedTableBuilder::InsertBlockInCache (const Slice & block_contents, const CompressionType type, const BlockHandle * handle) private
Definition at line 316 of file block_based_table_builder.cc.
References rocksdb::Options::block_cache_compressed, rocksdb::BlockBasedTableBuilder::Rep::compressed_cache_key_prefix, rocksdb::BlockBasedTableBuilder::Rep::compressed_cache_key_prefix_size, rocksdb::Slice::data(), rocksdb::DeleteCachedBlock(), rocksdb::EncodeVarint64(), rocksdb::BlockBasedTableBuilder::Rep::file, rocksdb::Cache::Insert(), rocksdb::WritableFile::InvalidateCache(), rocksdb::kNoCompression, rocksdb::BlockHandle::offset(), rocksdb::BlockBasedTableBuilder::Rep::offset, rocksdb::Status::OK(), rocksdb::BlockBasedTableBuilder::Rep::options, rocksdb::Cache::Release(), rep_, rocksdb::Block::size(), and rocksdb::Slice::size().
Referenced by WriteRawBlock().
{
   Rep* r = rep_;
   Cache* block_cache_compressed = r->options.block_cache_compressed.get();
   if (type != kNoCompression && block_cache_compressed != nullptr) {
     Cache::Handle* cache_handle = nullptr;
     size_t size = block_contents.size();
     char* ubuf = new char[size];             // make a new copy
     memcpy(ubuf, block_contents.data(), size);
     BlockContents results;
     Slice sl(ubuf, size);
     results.data = sl;
     results.cachable = true; // XXX
     results.heap_allocated = true;
     results.compression_type = type;
     Block* block = new Block(results);
     // make cache key by appending the file offset to the cache prefix id
     char* end = EncodeVarint64(
                   r->compressed_cache_key_prefix +
                   r->compressed_cache_key_prefix_size,
                   handle->offset());
     Slice key(r->compressed_cache_key_prefix, static_cast<size_t>
               (end - r->compressed_cache_key_prefix));
     // Insert into compressed block cache.
     cache_handle = block_cache_compressed->Insert(key, block, block->size(),
                                                   &DeleteCachedBlock);
     block_cache_compressed->Release(cache_handle);
     // Invalidate OS cache.
     r->file->InvalidateCache(r->offset, size);
   }
   return Status::OK();
 }
uint64_t rocksdb::BlockBasedTableBuilder::NumEntries () const override virtual
Implements rocksdb::TableBuilder.
Definition at line 558 of file block_based_table_builder.cc.
References rocksdb::TableProperties::num_entries, rocksdb::BlockBasedTableBuilder::Rep::props, and rep_.
{
   return rep_->props.num_entries;
 }
bool rocksdb::BlockBasedTableBuilder::ok () const inline private
Definition at line 65 of file block_based_table_builder.h.
References rocksdb::Status::ok(), and status().
Referenced by Add(), Finish(), Flush(), and WriteBlock().
 { return status().ok(); }
void rocksdb::BlockBasedTableBuilder::operator= (const BlockBasedTableBuilder &) private delete
Status rocksdb::BlockBasedTableBuilder::status () const override virtual
Implements rocksdb::TableBuilder.
Definition at line 295 of file block_based_table_builder.cc.
References rep_, and rocksdb::BlockBasedTableBuilder::Rep::status.
Referenced by ok().
{
   return rep_->status;
 }
void rocksdb::BlockBasedTableBuilder::WriteBlock (BlockBuilder * block, BlockHandle * handle) private
Definition at line 209 of file block_based_table_builder.cc.
References rocksdb::port::BZip2_Compress(), rocksdb::BlockBasedTableBuilder::Rep::compressed_output, rocksdb::Options::compression_opts, rocksdb::BlockBasedTableBuilder::Rep::compression_type, rocksdb::Slice::data(), rocksdb::BlockBuilder::Finish(), rocksdb::kBZip2Compression, rocksdb::kNoCompression, rocksdb::kSnappyCompression, rocksdb::kZlibCompression, ok(), rocksdb::BlockBasedTableBuilder::Rep::options, rep_, rocksdb::BlockBuilder::Reset(), rocksdb::Slice::size(), rocksdb::port::Snappy_Compress(), WriteRawBlock(), and rocksdb::port::Zlib_Compress().
Referenced by Finish(), and Flush().
{
   // File format contains a sequence of blocks where each block has:
   //    block_data: uint8[n]
   //    type: uint8
   //    crc: uint32
   assert(ok());
   Rep* r = rep_;
   Slice raw = block->Finish();
   Slice block_contents;
   std::string* compressed = &r->compressed_output;
   CompressionType type = r->compression_type;
   switch (type) {
     case kNoCompression:
       block_contents = raw;
       break;
     case kSnappyCompression: {
       std::string* compressed = &r->compressed_output;
       if (port::Snappy_Compress(r->options.compression_opts, raw.data(),
                                 raw.size(), compressed) &&
           GoodCompressionRatio(compressed->size(), raw.size())) {
         block_contents = *compressed;
       } else {
         // Snappy not supported, or not good compression ratio, so just
         // store uncompressed form
         block_contents = raw;
         type = kNoCompression;
       }
       break;
     }
     case kZlibCompression:
       if (port::Zlib_Compress(r->options.compression_opts, raw.data(),
                               raw.size(), compressed) &&
           GoodCompressionRatio(compressed->size(), raw.size())) {
         block_contents = *compressed;
       } else {
         // Zlib not supported, or not good compression ratio, so just
         // store uncompressed form
         block_contents = raw;
         type = kNoCompression;
       }
       break;
     case kBZip2Compression:
       if (port::BZip2_Compress(r->options.compression_opts, raw.data(),
                                raw.size(), compressed) &&
           GoodCompressionRatio(compressed->size(), raw.size())) {
         block_contents = *compressed;
       } else {
         // BZip not supported, or not good compression ratio, so just
         // store uncompressed form
         block_contents = raw;
         type = kNoCompression;
       }
       break;
   }
   WriteRawBlock(block_contents, type, handle);
   r->compressed_output.clear();
   block->Reset();
 }
void rocksdb::BlockBasedTableBuilder::WriteRawBlock (const Slice & data, CompressionType type, BlockHandle * handle) private
Definition at line 271 of file block_based_table_builder.cc.
References rocksdb::WritableFile::Append(), rocksdb::Slice::data(), rocksdb::EncodeFixed32(), rocksdb::Options::env, rocksdb::crc32c::Extend(), rocksdb::BlockBasedTableBuilder::Rep::file, InsertBlockInCache(), rocksdb::kBlockTrailerSize, rocksdb::crc32c::Mask(), rocksdb::BlockBasedTableBuilder::Rep::offset, rocksdb::Status::ok(), rocksdb::BlockBasedTableBuilder::Rep::options, rep_, rocksdb::BlockHandle::set_offset(), rocksdb::BlockHandle::set_size(), rocksdb::Slice::size(), rocksdb::Options::statistics, rocksdb::BlockBasedTableBuilder::Rep::status, rocksdb::crc32c::Value(), and rocksdb::WRITE_RAW_BLOCK_MICROS.
Referenced by Finish(), and WriteBlock().
{
   Rep* r = rep_;
   StopWatch sw(r->options.env, r->options.statistics, WRITE_RAW_BLOCK_MICROS);
   handle->set_offset(r->offset);
   handle->set_size(block_contents.size());
   r->status = r->file->Append(block_contents);
   if (r->status.ok()) {
     char trailer[kBlockTrailerSize];
     trailer[0] = type;
     uint32_t crc = crc32c::Value(block_contents.data(), block_contents.size());
     crc = crc32c::Extend(crc, trailer, 1);  // Extend crc to cover block type
     EncodeFixed32(trailer+1, crc32c::Mask(crc));
     r->status = r->file->Append(Slice(trailer, kBlockTrailerSize));
     if (r->status.ok()) {
       r->status = InsertBlockInCache(block_contents, type, handle);
     }
     if (r->status.ok()) {
       r->offset += block_contents.size() + kBlockTrailerSize;
     }
   }
 }
Member Data Documentation
Rep* rocksdb::BlockBasedTableBuilder::rep_ private
Definition at line 70 of file block_based_table_builder.h.
Referenced by Abandon(), Add(), BlockBasedTableBuilder(), FileSize(), Finish(), Flush(), InsertBlockInCache(), NumEntries(), status(), WriteBlock(), WriteRawBlock(), and ~BlockBasedTableBuilder().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/table/block_based_table_builder.h
rippled/src/ripple/rocksdb/rocksdb/table/block_based_table_builder.cc