rippled: rocksdb::ConcurrentTest Class Reference
rocksdb::ConcurrentTest Class Reference
Classes
struct State
Public Member Functions
ConcurrentTest ()
void WriteStep (Random *rnd)
void ReadStep (Random *rnd)
Static Private Member Functions
static uint64_t key (Key key)
static uint64_t gen (Key key)
static uint64_t hash (Key key)
static uint64_t HashNumbers (uint64_t k, uint64_t g)
static Key MakeKey (uint64_t k, uint64_t g)
static bool IsValidKey (Key k)
static Key RandomTarget (Random *rnd)
Private Attributes
State current_
ArenaImpl arena_impl_
SkipList< Key, TestComparator > list_
Static Private Attributes
static const uint32_t K = 4
Detailed Description
Definition at line 154 of file skiplist_test.cc.
Constructor & Destructor Documentation
rocksdb::ConcurrentTest::ConcurrentTest () inline
Definition at line 219 of file skiplist_test.cc.
 : list_(TestComparator(), &arena_impl_) { }
Member Function Documentation
static uint64_t rocksdb::ConcurrentTest::gen (Key key) inline static private
Definition at line 159 of file skiplist_test.cc.
Referenced by IsValidKey(), and ReadStep().
 { return (key >> 8) & 0xffffffffu; }
static uint64_t rocksdb::ConcurrentTest::hash (Key key) inline static private
Definition at line 160 of file skiplist_test.cc.
Referenced by IsValidKey().
 { return key & 0xff; }
static uint64_t rocksdb::ConcurrentTest::HashNumbers (uint64_t k, uint64_t g) inline static private
Definition at line 162 of file skiplist_test.cc.
References rocksdb::Hash().
Referenced by IsValidKey(), and MakeKey().
{
     uint64_t data[2] = { k, g };
     return Hash(reinterpret_cast<char*>(data), sizeof(data), 0);
   }
static bool rocksdb::ConcurrentTest::IsValidKey (Key k) inline static private
Definition at line 174 of file skiplist_test.cc.
References gen(), hash(), HashNumbers(), and key().
Referenced by ReadStep().
{
     return hash(k) == (HashNumbers(key(k), gen(k)) & 0xff);
   }
static uint64_t rocksdb::ConcurrentTest::key (Key key) inline static private
Definition at line 158 of file skiplist_test.cc.
Referenced by IsValidKey(), ReadStep(), and WriteStep().
 { return (key >> 40); }
static Key rocksdb::ConcurrentTest::MakeKey (uint64_t k, uint64_t g) inline static private
Definition at line 167 of file skiplist_test.cc.
References HashNumbers(), and K.
Referenced by RandomTarget(), ReadStep(), and WriteStep().
{
     assert(sizeof(Key) == sizeof(uint64_t));
     assert(k <= K);  // We sometimes pass K to seek to the end of the skiplist
     assert(g <= 0xffffffffu);
     return ((k << 40) | (g << 8) | (HashNumbers(k, g) & 0xff));
   }
static Key rocksdb::ConcurrentTest::RandomTarget (Random * rnd) inline static private
Definition at line 178 of file skiplist_test.cc.
References K, MakeKey(), and rocksdb::Random::Next().
Referenced by ReadStep().
{
     switch (rnd->Next() % 10) {
       case 0:
         // Seek to beginning
         return MakeKey(0, 0);
       case 1:
         // Seek to end
         return MakeKey(K, 0);
       default:
         // Seek to middle
         return MakeKey(rnd->Next() % K, 0);
     }
   }
void rocksdb::ConcurrentTest::ReadStep (Random * rnd) inline
Definition at line 230 of file skiplist_test.cc.
References ASSERT_LE, ASSERT_LT, ASSERT_TRUE, current_, gen(), rocksdb::ConcurrentTest::State::Get(), IsValidKey(), K, rocksdb::SkipList< Key, Comparator >::Iterator::key(), key(), list_, MakeKey(), rocksdb::Random::Next(), rocksdb::SkipList< Key, Comparator >::Iterator::Next(), RandomTarget(), rocksdb::SkipList< Key, Comparator >::Iterator::Seek(), rocksdb::ConcurrentTest::State::Set(), and rocksdb::SkipList< Key, Comparator >::Iterator::Valid().
Referenced by rocksdb::ConcurrentReader(), and rocksdb::TEST().
{
     // Remember the initial committed state of the skiplist.
     State initial_state;
     for (unsigned int k = 0; k < K; k++) {
       initial_state.Set(k, current_.Get(k));
     }
     Key pos = RandomTarget(rnd);
     SkipList<Key, TestComparator>::Iterator iter(&list_);
     iter.Seek(pos);
     while (true) {
       Key current;
       if (!iter.Valid()) {
         current = MakeKey(K, 0);
       } else {
         current = iter.key();
         ASSERT_TRUE(IsValidKey(current)) << current;
       }
       ASSERT_LE(pos, current) << "should not go backwards";
       // Verify that everything in [pos,current) was not present in
       // initial_state.
       while (pos < current) {
         ASSERT_LT(key(pos), K) << pos;
         // Note that generation 0 is never inserted, so it is ok if
         // <*,0,*> is missing.
         ASSERT_TRUE((gen(pos) == 0U) ||
                     (gen(pos) > (uint64_t)initial_state.Get(key(pos)))
                     ) << "key: " << key(pos)
                       << "; gen: " << gen(pos)
                       << "; initgen: "
                       << initial_state.Get(key(pos));
         // Advance to next key in the valid key space
         if (key(pos) < key(current)) {
           pos = MakeKey(key(pos) + 1, 0);
         } else {
           pos = MakeKey(key(pos), gen(pos) + 1);
         }
       }
       if (!iter.Valid()) {
         break;
       }
       if (rnd->Next() % 2) {
         iter.Next();
         pos = MakeKey(key(pos), gen(pos) + 1);
       } else {
         Key new_target = RandomTarget(rnd);
         if (new_target > pos) {
           pos = new_target;
           iter.Seek(new_target);
         }
       }
     }
   }
void rocksdb::ConcurrentTest::WriteStep (Random * rnd) inline
Definition at line 222 of file skiplist_test.cc.
References current_, rocksdb::ConcurrentTest::State::Get(), K, key(), list_, MakeKey(), rocksdb::Random::Next(), and rocksdb::ConcurrentTest::State::Set().
Referenced by rocksdb::RunConcurrent(), and rocksdb::TEST().
{
     const uint32_t k = rnd->Next() % K;
     const intptr_t g = current_.Get(k) + 1;
     const Key key = MakeKey(k, g);
     list_.Insert(key);
     current_.Set(k, g);
   }
Member Data Documentation
ArenaImpl rocksdb::ConcurrentTest::arena_impl_ private
Definition at line 212 of file skiplist_test.cc.
State rocksdb::ConcurrentTest::current_ private
Definition at line 210 of file skiplist_test.cc.
Referenced by ReadStep(), and WriteStep().
const uint32_t rocksdb::ConcurrentTest::K = 4 static private
Definition at line 156 of file skiplist_test.cc.
Referenced by MakeKey(), RandomTarget(), ReadStep(), rocksdb::ConcurrentTest::State::State(), and WriteStep().
SkipList<Key, TestComparator> rocksdb::ConcurrentTest::list_ private
Definition at line 216 of file skiplist_test.cc.
Referenced by ReadStep(), and WriteStep().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/db/skiplist_test.cc