rippled: beast.env.Print Namespace Reference
beast.env.Print Namespace Reference
Functions
def print_build_vars
def print_cmd_line
def print_build_config
Variables
int FIELD_WIDTH = 10
int LINE_WIDTH = 69
string EMPTY_NAME = ' '
tuple TEXT_WRAPPER
DISPLAY_EMPTY_ENVS = True
Function Documentation
def beast.env.Print.print_build_config (env, original, print = print)
Definition at line 33 of file Print.py.
References beast::unit_test.print(), and beast.env.Print.print_build_vars().
 def print_build_config(env, original, print=print):
     print('\nConfiguration:')
     for name, value in env.items():
         if value or DISPLAY_EMPTY_ENVS:
             same = (value == original[name])
             if not same:
                 print('"%s" != "%s"' % (value, original[name]))
             print_build_vars(name, value, same, print=print)
     print()
def beast.env.Print.print_build_vars (name, value, same, print = print)
Pretty-print values as a build configuration.
Definition at line 21 of file Print.py.
References beast::unit_test.print().
Referenced by beast.env.Print.print_build_config().
 def print_build_vars(name, value, same, print=print):
     """Pretty-print values as a build configuration."""
     name = '%s' % name.rjust(FIELD_WIDTH)
     color = Terminal.blue if same else Terminal.green
     for line in TEXT_WRAPPER.wrap(String.stringify(value, ' ')):
         print(' '.join([name, color(line)]))
         name = EMPTY_NAME
def beast.env.Print.print_cmd_line (s, target, source, env)
Definition at line 30 of file Print.py.
References beast::unit_test.print().
 def print_cmd_line(s, target, source, env):
     print(EMPTY_NAME + Terminal.blue(String.stringify(target)))
Variable Documentation
beast.env.Print.DISPLAY_EMPTY_ENVS = True
Definition at line 19 of file Print.py.
string beast.env.Print.EMPTY_NAME = ' '
Definition at line 11 of file Print.py.
int beast.env.Print.FIELD_WIDTH = 10
Definition at line 8 of file Print.py.
int beast.env.Print.LINE_WIDTH = 69
Definition at line 9 of file Print.py.
tuple beast.env.Print.TEXT_WRAPPER
Initial value:
 = textwrap.TextWrapper(
     break_long_words=False,
     break_on_hyphens=False,
     width=LINE_WIDTH,
 )
Definition at line 13 of file Print.py.