rippled: beast.env.ReadEnvFile_test.test_ReadEnvFile Class Reference
beast.env.ReadEnvFile_test.test_ReadEnvFile Class Reference
Public Member Functions
def test_read_json
def test_read_env
def test_read_env_error
Detailed Description
Definition at line 38 of file ReadEnvFile_test.py.
Member Function Documentation
def beast.env.ReadEnvFile_test.test_ReadEnvFile.test_read_env (self)
Definition at line 42 of file ReadEnvFile_test.py.
References beast.env.ReadEnvFile.read_env_file().
   def test_read_env(self):
     self.assertEqual(read_env_file(ENV), RESULT)
def beast.env.ReadEnvFile_test.test_ReadEnvFile.test_read_env_error (self)
Definition at line 45 of file ReadEnvFile_test.py.
References beast.env.ReadEnvFile.read_env_file().
   def test_read_env_error(self):
     errors = []
     self.assertEqual(read_env_file(BAD_ENV, errors.append), RESULT)
     self.assertEqual(errors, [
         "WARNING: Didn't understand the following environment file lines:",
         "11. >>> This line isn't right.",
         '12. >>> NO SPACES IN NAMES="valid value"'])
def beast.env.ReadEnvFile_test.test_ReadEnvFile.test_read_json (self)
Definition at line 39 of file ReadEnvFile_test.py.
References beast.env.ReadEnvFile.read_env_file().
   def test_read_json(self):
     self.assertEqual(read_env_file(JSON), RESULT)
The documentation for this class was generated from the following file:
rippled/src/beast/python/beast/env/ReadEnvFile_test.py