rippled: beast::CharPointer_UTF16 Class Reference
beast::CharPointer_UTF16 Class Reference
#include <CharPointer_UTF16.h>
Public Types
enum { byteOrderMarkBE1 = 0xfe, byteOrderMarkBE2 = 0xff, byteOrderMarkLE1 = 0xff, byteOrderMarkLE2 = 0xfe }
typedef std::int16_t CharType
Public Member Functions
CharPointer_UTF16 (const CharType *const rawPointer) noexcept
CharPointer_UTF16 (const CharPointer_UTF16 &other) noexcept
CharPointer_UTF16 operator= (CharPointer_UTF16 other) noexcept
CharPointer_UTF16 operator= (const CharType *text) noexcept
bool operator== (CharPointer_UTF16 other) const noexcept
bool operator!= (CharPointer_UTF16 other) const noexcept
bool operator<= (CharPointer_UTF16 other) const noexcept
bool operator< (CharPointer_UTF16 other) const noexcept
bool operator>= (CharPointer_UTF16 other) const noexcept
bool operator> (CharPointer_UTF16 other) const noexcept
CharType * getAddress () const noexcept
operator const CharType * () const noexcept
bool isEmpty () const noexcept
beast_wchar operator* () const noexcept
CharPointer_UTF16 operator++ () noexcept
CharPointer_UTF16 operator-- () noexcept
beast_wchar getAndAdvance () noexcept
CharPointer_UTF16 operator++ (int) noexcept
void operator+= (int numToSkip) noexcept
void operator-= (int numToSkip) noexcept
beast_wchar operator[] (const int characterIndex) const noexcept
CharPointer_UTF16 operator+ (const int numToSkip) const noexcept
CharPointer_UTF16 operator- (const int numToSkip) const noexcept
void write (beast_wchar charToWrite) noexcept
void writeNull () const noexcept
size_t length () const noexcept
size_t lengthUpTo (const size_t maxCharsToCount) const noexcept
size_t lengthUpTo (const CharPointer_UTF16 end) const noexcept
size_t sizeInBytes () const noexcept
CharPointer_UTF16 findTerminatingNull () const noexcept
template<typename CharPointer >
void writeAll (const CharPointer src) noexcept
void writeAll (const CharPointer_UTF16 src) noexcept
template<typename CharPointer >
size_t writeWithDestByteLimit (const CharPointer src, const size_t maxDestBytes) noexcept
template<typename CharPointer >
void writeWithCharLimit (const CharPointer src, const int maxChars) noexcept
template<typename CharPointer >
int compare (const CharPointer other) const noexcept
template<typename CharPointer >
int compareUpTo (const CharPointer other, const int maxChars) const noexcept
template<typename CharPointer >
int compareIgnoreCase (const CharPointer other) const noexcept
template<typename CharPointer >
int compareIgnoreCaseUpTo (const CharPointer other, const int maxChars) const noexcept
template<typename CharPointer >
int indexOf (const CharPointer stringToFind) const noexcept
int indexOf (const beast_wchar charToFind) const noexcept
int indexOf (const beast_wchar charToFind, const bool ignoreCase) const noexcept
bool isWhitespace () const noexcept
bool isDigit () const noexcept
bool isLetter () const noexcept
bool isLetterOrDigit () const noexcept
bool isUpperCase () const noexcept
bool isLowerCase () const noexcept
beast_wchar toUpperCase () const noexcept
beast_wchar toLowerCase () const noexcept
int getIntValue32 () const noexcept
std::int64_t getIntValue64 () const noexcept
double getDoubleValue () const noexcept
CharPointer_UTF16 findEndOfWhitespace () const noexcept
CharPointer_UTF16 atomicSwap (const CharPointer_UTF16 newValue)
Static Public Member Functions
static size_t getBytesRequiredFor (const beast_wchar charToWrite) noexcept
template<class CharPointer >
static size_t getBytesRequiredFor (CharPointer text) noexcept
static bool canRepresent (beast_wchar character) noexcept
static bool isValidString (const CharType *dataToTest, int maxBytesToRead)
static bool isByteOrderMarkBigEndian (const void *possibleByteOrder) noexcept
static bool isByteOrderMarkLittleEndian (const void *possibleByteOrder) noexcept
Static Private Member Functions
static unsigned int findNullIndex (const CharType *const t) noexcept
Private Attributes
CharType * data
Detailed Description
Wraps a pointer to a null-terminated UTF-16 character string, and provides various methods to operate on the data.
See Also
CharPointer_UTF8, CharPointer_UTF32
Definition at line 42 of file CharPointer_UTF16.h.
Member Typedef Documentation
typedef std::int16_t beast::CharPointer_UTF16::CharType
Definition at line 48 of file CharPointer_UTF16.h.
Member Enumeration Documentation
anonymous enum
These values are the byte-order-mark (BOM) values for a UTF-16 stream.
Enumerator
byteOrderMarkBE1
byteOrderMarkBE2
byteOrderMarkLE1
byteOrderMarkLE2
Definition at line 481 of file CharPointer_UTF16.h.
     {
         byteOrderMarkBE1 = 0xfe,
         byteOrderMarkBE2 = 0xff,
         byteOrderMarkLE1 = 0xff,
         byteOrderMarkLE2 = 0xfe
     };
Constructor & Destructor Documentation
beast::CharPointer_UTF16::CharPointer_UTF16 (const CharType *const rawPointer) inline explicit noexcept
Definition at line 51 of file CharPointer_UTF16.h.
Referenced by atomicSwap(), and findTerminatingNull().
         : data (const_cast <CharType*> (rawPointer))
     {
     }
beast::CharPointer_UTF16::CharPointer_UTF16 (const CharPointer_UTF16 & other) inline noexcept
Definition at line 56 of file CharPointer_UTF16.h.
         : data (other.data)
     {
     }
Member Function Documentation
CharPointer_UTF16 beast::CharPointer_UTF16::atomicSwap (const CharPointer_UTF16 newValue) inline
Atomically swaps this pointer for a new value, returning the previous value.
Definition at line 475 of file CharPointer_UTF16.h.
References CharPointer_UTF16(), and data.
     {
         return CharPointer_UTF16 (reinterpret_cast <Atomic<CharType*>&> (data).exchange (newValue.data));
     }
static bool beast::CharPointer_UTF16::canRepresent (beast_wchar character) inline static noexcept
Returns true if the given unicode character can be represented in this encoding.
Definition at line 438 of file CharPointer_UTF16.h.
     {
         return ((unsigned int) character) < (unsigned int) 0x10ffff
                  && (((unsigned int) character) < 0xd800 || ((unsigned int) character) > 0xdfff);
     }
template<typename CharPointer > int beast::CharPointer_UTF16::compare (const CharPointer other) const inline noexcept
Compares this string with another one.
Definition at line 329 of file CharPointer_UTF16.h.
References beast::CharacterFunctions::compare().
     {
         return CharacterFunctions::compare (*this, other);
     }
template<typename CharPointer > int beast::CharPointer_UTF16::compareIgnoreCase (const CharPointer other) const inline noexcept
Compares this string with another one.
Definition at line 343 of file CharPointer_UTF16.h.
References beast::CharacterFunctions::compareIgnoreCase().
     {
         return CharacterFunctions::compareIgnoreCase (*this, other);
     }
template<typename CharPointer > int beast::CharPointer_UTF16::compareIgnoreCaseUpTo (const CharPointer other, const int maxChars) const inline noexcept
Compares this string with another one, up to a specified number of characters.
Definition at line 350 of file CharPointer_UTF16.h.
References beast::CharacterFunctions::compareIgnoreCaseUpTo().
     {
         return CharacterFunctions::compareIgnoreCaseUpTo (*this, other, maxChars);
     }
template<typename CharPointer > int beast::CharPointer_UTF16::compareUpTo (const CharPointer other, const int maxChars) const inline noexcept
Compares this string with another one, up to a specified number of characters.
Definition at line 336 of file CharPointer_UTF16.h.
References beast::CharacterFunctions::compareUpTo().
     {
         return CharacterFunctions::compareUpTo (*this, other, maxChars);
     }
CharPointer_UTF16 beast::CharPointer_UTF16::findEndOfWhitespace () const inline noexcept
Returns the first non-whitespace character in the string.
Definition at line 435 of file CharPointer_UTF16.h.
References beast::CharacterFunctions::findEndOfWhitespace().
 { return CharacterFunctions::findEndOfWhitespace (*this); }
static unsigned int beast::CharPointer_UTF16::findNullIndex (const CharType *const t) inline static private noexcept
Definition at line 516 of file CharPointer_UTF16.h.
Referenced by sizeInBytes().
     {
         unsigned int n = 0;
         while (t[n] != 0)
             ++n;
         return n;
     }
CharPointer_UTF16 beast::CharPointer_UTF16::findTerminatingNull () const inline noexcept
Returns a pointer to the null character that terminates this string.
Definition at line 278 of file CharPointer_UTF16.h.
References CharPointer_UTF16(), and data.
     {
         const CharType* t = data;
         while (*t != 0)
             ++t;
         return CharPointer_UTF16 (t);
     }
CharType* beast::CharPointer_UTF16::getAddress () const inline noexcept
Returns the address that this pointer is pointing to.
Definition at line 82 of file CharPointer_UTF16.h.
References data.
 { return data; }
beast_wchar beast::CharPointer_UTF16::getAndAdvance () inline noexcept
Returns the character that this pointer is currently pointing to, and then advances the pointer to point to the next character.
Definition at line 125 of file CharPointer_UTF16.h.
References data.
     {
         std::uint32_t n = (std::uint32_t) (std::uint16_t) *data++;
         if (n >= 0xd800 && n <= 0xdfff && ((std::uint32_t) (std::uint16_t) *data) >= 0xdc00)
             n = 0x10000 + ((((n - 0xd800) << 10) | (((std::uint32_t) (std::uint16_t) *data++) - 0xdc00)));
         return (beast_wchar) n;
     }
static size_t beast::CharPointer_UTF16::getBytesRequiredFor (const beast_wchar charToWrite) inline static noexcept
Returns the number of bytes that would be needed to represent the given unicode character in this encoding format.
Definition at line 256 of file CharPointer_UTF16.h.
Referenced by getBytesRequiredFor(), and beast::WindowsFileHelpers::getDriveFromPath().
     {
         return (charToWrite >= 0x10000) ? (sizeof (CharType) * 2) : sizeof (CharType);
     }
template<class CharPointer > static size_t beast::CharPointer_UTF16::getBytesRequiredFor (CharPointer text) inline static noexcept
Returns the number of bytes that would be needed to represent the given string in this encoding format. The value returned does NOT include the terminating null character.
Definition at line 266 of file CharPointer_UTF16.h.
References getBytesRequiredFor().
     {
         size_t count = 0;
         beast_wchar n;
         while ((n = text.getAndAdvance()) != 0)
             count += getBytesRequiredFor (n);
         return count;
     }
double beast::CharPointer_UTF16::getDoubleValue () const inline noexcept
Parses this string as a floating point double.
Definition at line 432 of file CharPointer_UTF16.h.
References beast::CharacterFunctions::getDoubleValue().
 { return CharacterFunctions::getDoubleValue (*this); }
int beast::CharPointer_UTF16::getIntValue32 () const inline noexcept
Parses this string as a 32-bit integer.
Definition at line 412 of file CharPointer_UTF16.h.
References data.
     {
        #if BEAST_WINDOWS
         return _wtoi (data);
        #else
         return CharacterFunctions::getIntValue <int, CharPointer_UTF16> (*this);
        #endif
     }
std::int64_t beast::CharPointer_UTF16::getIntValue64 () const inline noexcept
Parses this string as a 64-bit integer.
Definition at line 422 of file CharPointer_UTF16.h.
References data.
     {
        #if BEAST_WINDOWS
         return _wtoi64 (data);
        #else
         return CharacterFunctions::getIntValue <std::int64_t, CharPointer_UTF16> (*this);
        #endif
     }
template<typename CharPointer > int beast::CharPointer_UTF16::indexOf (const CharPointer stringToFind) const inline noexcept
Returns the character index of a substring, or -1 if it isn't found.
Definition at line 375 of file CharPointer_UTF16.h.
References beast::CharacterFunctions::indexOf().
     {
         return CharacterFunctions::indexOf (*this, stringToFind);
     }
int beast::CharPointer_UTF16::indexOf (const beast_wchar charToFind) const inline noexcept
Returns the character index of a unicode character, or -1 if it isn't found.
Definition at line 381 of file CharPointer_UTF16.h.
References beast::CharacterFunctions::indexOfChar().
     {
         return CharacterFunctions::indexOfChar (*this, charToFind);
     }
int beast::CharPointer_UTF16::indexOf (const beast_wchar charToFind, const bool ignoreCase) const inline noexcept
Returns the character index of a unicode character, or -1 if it isn't found.
Definition at line 387 of file CharPointer_UTF16.h.
References beast::CharacterFunctions::indexOfChar(), and beast::CharacterFunctions::indexOfCharIgnoreCase().
     {
         return ignoreCase ? CharacterFunctions::indexOfCharIgnoreCase (*this, charToFind)
                           : CharacterFunctions::indexOfChar (*this, charToFind);
     }
static bool beast::CharPointer_UTF16::isByteOrderMarkBigEndian (const void * possibleByteOrder) inline static noexcept
Returns true if the first pair of bytes in this pointer are the UTF16 byte-order mark (big endian). The pointer must not be null, and must contain at least two valid bytes.
Definition at line 492 of file CharPointer_UTF16.h.
References bassert, byteOrderMarkBE1, and byteOrderMarkBE2.
Referenced by beast::String::createStringFromData().
     {
         bassert (possibleByteOrder != nullptr);
         const std::uint8_t* const c = static_cast<const std::uint8_t*> (possibleByteOrder);
         return c[0] == (std::uint8_t) byteOrderMarkBE1
             && c[1] == (std::uint8_t) byteOrderMarkBE2;
     }
static bool beast::CharPointer_UTF16::isByteOrderMarkLittleEndian (const void * possibleByteOrder) inline static noexcept
Returns true if the first pair of bytes in this pointer are the UTF16 byte-order mark (little endian). The pointer must not be null, and must contain at least two valid bytes.
Definition at line 504 of file CharPointer_UTF16.h.
References bassert, byteOrderMarkLE1, and byteOrderMarkLE2.
Referenced by beast::String::createStringFromData().
     {
         bassert (possibleByteOrder != nullptr);
         const std::uint8_t* const c = static_cast<const std::uint8_t*> (possibleByteOrder);
         return c[0] == (std::uint8_t) byteOrderMarkLE1
             && c[1] == (std::uint8_t) byteOrderMarkLE2;
     }
bool beast::CharPointer_UTF16::isDigit () const inline noexcept
Returns true if the first character of this string is a digit.
Definition at line 396 of file CharPointer_UTF16.h.
References beast::CharacterFunctions::isDigit().
 { return CharacterFunctions::isDigit (operator*()) != 0; }
bool beast::CharPointer_UTF16::isEmpty () const inline noexcept
Returns true if this pointer is pointing to a null character.
Definition at line 88 of file CharPointer_UTF16.h.
References data.
 { return *data == 0; }
bool beast::CharPointer_UTF16::isLetter () const inline noexcept
Returns true if the first character of this string is a letter.
Definition at line 398 of file CharPointer_UTF16.h.
References beast::CharacterFunctions::isLetter().
 { return CharacterFunctions::isLetter (operator*()) != 0; }
bool beast::CharPointer_UTF16::isLetterOrDigit () const inline noexcept
Returns true if the first character of this string is a letter or digit.
Definition at line 400 of file CharPointer_UTF16.h.
References beast::CharacterFunctions::isLetterOrDigit().
 { return CharacterFunctions::isLetterOrDigit (operator*()) != 0; }
bool beast::CharPointer_UTF16::isLowerCase () const inline noexcept
Returns true if the first character of this string is lower-case.
Definition at line 404 of file CharPointer_UTF16.h.
References beast::CharacterFunctions::isLowerCase().
 { return CharacterFunctions::isLowerCase (operator*()) != 0; }
bool beast::CharPointer_UTF16::isUpperCase () const inline noexcept
Returns true if the first character of this string is upper-case.
Definition at line 402 of file CharPointer_UTF16.h.
References beast::CharacterFunctions::isUpperCase().
 { return CharacterFunctions::isUpperCase (operator*()) != 0; }
static bool beast::CharPointer_UTF16::isValidString (const CharType * dataToTest, int maxBytesToRead) inline static
Returns true if this data contains a valid string in this encoding.
Definition at line 445 of file CharPointer_UTF16.h.
     {
         maxBytesToRead /= sizeof (CharType);
         while (--maxBytesToRead >= 0 && *dataToTest != 0)
         {
             const std::uint32_t n = (std::uint32_t) (std::uint16_t) *dataToTest++;
             if (n >= 0xd800)
             {
                 if (n > 0x10ffff)
                     return false;
                 if (n <= 0xdfff)
                 {
                     if (n > 0xdc00)
                         return false;
                     const std::uint32_t nextChar = (std::uint32_t) (std::uint16_t) *dataToTest++;
                     if (nextChar < 0xdc00 || nextChar > 0xdfff)
                         return false;
                 }
             }
         }
         return true;
     }
bool beast::CharPointer_UTF16::isWhitespace () const inline noexcept
Returns true if the first character of this string is whitespace.
Definition at line 394 of file CharPointer_UTF16.h.
References beast::CharacterFunctions::isWhitespace().
 { return CharacterFunctions::isWhitespace (operator*()) != 0; }
size_t beast::CharPointer_UTF16::length () const inline noexcept
Returns the number of characters in this string.
Definition at line 210 of file CharPointer_UTF16.h.
References data.
     {
         const CharType* d = data;
         size_t count = 0;
         for (;;)
         {
             const int n = *d++;
             if (n >= 0xd800 && n <= 0xdfff)
             {
                 if (*d++ == 0)
                     break;
             }
             else if (n == 0)
                 break;
             ++count;
         }
         return count;
     }
size_t beast::CharPointer_UTF16::lengthUpTo (const size_t maxCharsToCount) const inline noexcept
Returns the number of characters in this string, or the given value, whichever is lower.
Definition at line 234 of file CharPointer_UTF16.h.
References beast::CharacterFunctions::lengthUpTo().
     {
         return CharacterFunctions::lengthUpTo (*this, maxCharsToCount);
     }
size_t beast::CharPointer_UTF16::lengthUpTo (const CharPointer_UTF16 end) const inline noexcept
Returns the number of characters in this string, or up to the given end pointer, whichever is lower.
Definition at line 240 of file CharPointer_UTF16.h.
References beast::CharacterFunctions::lengthUpTo().
     {
         return CharacterFunctions::lengthUpTo (*this, end);
     }
beast::CharPointer_UTF16::operator const CharType * () const inline noexcept
Returns the address that this pointer is pointing to.
Definition at line 85 of file CharPointer_UTF16.h.
References data.
 { return data; }
bool beast::CharPointer_UTF16::operator!= (CharPointer_UTF16 other) const inline noexcept
Definition at line 75 of file CharPointer_UTF16.h.
References data.
 { return data != other.data; }
beast_wchar beast::CharPointer_UTF16::operator* () const inline noexcept
Returns the unicode character that this pointer is pointing to.
Definition at line 91 of file CharPointer_UTF16.h.
References data.
     {
         std::uint32_t n = (std::uint32_t) (std::uint16_t) *data;
         if (n >= 0xd800 && n <= 0xdfff && ((std::uint32_t) (std::uint16_t) data[1]) >= 0xdc00)
             n = 0x10000 + (((n - 0xd800) << 10) | (((std::uint32_t) (std::uint16_t) data[1]) - 0xdc00));
         return (beast_wchar) n;
     }
CharPointer_UTF16 beast::CharPointer_UTF16::operator+ (const int numToSkip) const inline noexcept
Returns a pointer which is moved forwards from this one by the specified number of characters.
Definition at line 173 of file CharPointer_UTF16.h.
     {
         CharPointer_UTF16 p (*this);
         p += numToSkip;
         return p;
     }
CharPointer_UTF16 beast::CharPointer_UTF16::operator++ () inline noexcept
Moves this pointer along to the next character in the string.
Definition at line 102 of file CharPointer_UTF16.h.
References data.
     {
         const beast_wchar n = *data++;
         if (n >= 0xd800 && n <= 0xdfff && ((std::uint32_t) (std::uint16_t) *data) >= 0xdc00)
             ++data;
         return *this;
     }
CharPointer_UTF16 beast::CharPointer_UTF16::operator++ (int) inline noexcept
Moves this pointer along to the next character in the string.
Definition at line 136 of file CharPointer_UTF16.h.
     {
         CharPointer_UTF16 temp (*this);
         ++*this;
         return temp;
     }
void beast::CharPointer_UTF16::operator+= (int numToSkip) inline noexcept
Moves this pointer forwards by the specified number of characters.
Definition at line 144 of file CharPointer_UTF16.h.
Referenced by operator-=().
     {
         if (numToSkip < 0)
         {
             while (++numToSkip <= 0)
                 --*this;
         }
         else
         {
             while (--numToSkip >= 0)
                 ++*this;
         }
     }
CharPointer_UTF16 beast::CharPointer_UTF16::operator- (const int numToSkip) const inline noexcept
Returns a pointer which is moved backwards from this one by the specified number of characters.
Definition at line 181 of file CharPointer_UTF16.h.
     {
         CharPointer_UTF16 p (*this);
         p += -numToSkip;
         return p;
     }
CharPointer_UTF16 beast::CharPointer_UTF16::operator-- () inline noexcept
Moves this pointer back to the previous character in the string.
Definition at line 113 of file CharPointer_UTF16.h.
References data.
     {
         const beast_wchar n = *--data;
         if (n >= 0xdc00 && n <= 0xdfff)
             --data;
         return *this;
     }
void beast::CharPointer_UTF16::operator-= (int numToSkip) inline noexcept
Moves this pointer backwards by the specified number of characters.
Definition at line 159 of file CharPointer_UTF16.h.
References operator+=().
     {
         operator+= (-numToSkip);
     }
bool beast::CharPointer_UTF16::operator< (CharPointer_UTF16 other) const inline noexcept
Definition at line 77 of file CharPointer_UTF16.h.
References data.
 { return data <  other.data; }
bool beast::CharPointer_UTF16::operator<= (CharPointer_UTF16 other) const inline noexcept
Definition at line 76 of file CharPointer_UTF16.h.
References data.
 { return data <= other.data; }
CharPointer_UTF16 beast::CharPointer_UTF16::operator= (CharPointer_UTF16 other) inline noexcept
Definition at line 61 of file CharPointer_UTF16.h.
References data.
     {
         data = other.data;
         return *this;
     }
CharPointer_UTF16 beast::CharPointer_UTF16::operator= (const CharType * text) inline noexcept
Definition at line 67 of file CharPointer_UTF16.h.
References data.
     {
         data = const_cast <CharType*> (text);
         return *this;
     }
bool beast::CharPointer_UTF16::operator== (CharPointer_UTF16 other) const inline noexcept
This is a pointer comparison, it doesn't compare the actual text.
Definition at line 74 of file CharPointer_UTF16.h.
References data.
 { return data == other.data; }
bool beast::CharPointer_UTF16::operator> (CharPointer_UTF16 other) const inline noexcept
Definition at line 79 of file CharPointer_UTF16.h.
References data.
 { return data >  other.data; }
bool beast::CharPointer_UTF16::operator>= (CharPointer_UTF16 other) const inline noexcept
Definition at line 78 of file CharPointer_UTF16.h.
References data.
 { return data >= other.data; }
beast_wchar beast::CharPointer_UTF16::operator[] (const int characterIndex) const inline noexcept
Returns the character at a given character index from the start of the string.
Definition at line 165 of file CharPointer_UTF16.h.
     {
         CharPointer_UTF16 p (*this);
         p += characterIndex;
         return *p;
     }
size_t beast::CharPointer_UTF16::sizeInBytes () const inline noexcept
Returns the number of bytes that are used to represent this string. This includes the terminating null character.
Definition at line 248 of file CharPointer_UTF16.h.
References data, and findNullIndex().
     {
         return sizeof (CharType) * (findNullIndex (data) + 1);
     }
beast_wchar beast::CharPointer_UTF16::toLowerCase () const inline noexcept
Returns a lower-case version of the first character of this string.
Definition at line 409 of file CharPointer_UTF16.h.
References beast::CharacterFunctions::toLowerCase().
 { return CharacterFunctions::toLowerCase (operator*()); }
beast_wchar beast::CharPointer_UTF16::toUpperCase () const inline noexcept
Returns an upper-case version of the first character of this string.
Definition at line 407 of file CharPointer_UTF16.h.
References beast::CharacterFunctions::toUpperCase().
 { return CharacterFunctions::toUpperCase (operator*()); }
void beast::CharPointer_UTF16::write (beast_wchar charToWrite) inline noexcept
Writes a unicode character to this string, and advances this pointer to point to the next position.
Definition at line 189 of file CharPointer_UTF16.h.
References data.
     {
         if (charToWrite >= 0x10000)
         {
             charToWrite -= 0x10000;
             *data++ = (CharType) (0xd800 + (charToWrite >> 10));
             *data++ = (CharType) (0xdc00 + (charToWrite & 0x3ff));
         }
         else
         {
             *data++ = (CharType) charToWrite;
         }
     }
template<typename CharPointer > void beast::CharPointer_UTF16::writeAll (const CharPointer src) inline noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
Definition at line 290 of file CharPointer_UTF16.h.
References beast::CharacterFunctions::copyAll().
     {
         CharacterFunctions::copyAll (*this, src);
     }
void beast::CharPointer_UTF16::writeAll (const CharPointer_UTF16 src) inline noexcept
Copies a source string to this pointer, advancing this pointer as it goes.
Definition at line 296 of file CharPointer_UTF16.h.
References data.
     {
         const CharType* s = src.data;
         while ((*data = *s) != 0)
         {
             ++data;
             ++s;
         }
     }
void beast::CharPointer_UTF16::writeNull () const inline noexcept
Writes a null character to this string (leaving the pointer's position unchanged).
Definition at line 204 of file CharPointer_UTF16.h.
References data.
     {
         *data = 0;
     }
template<typename CharPointer > void beast::CharPointer_UTF16::writeWithCharLimit (const CharPointer src, const int maxChars) inline noexcept
Copies a source string to this pointer, advancing this pointer as it goes. The maxChars parameter specifies the maximum number of characters that can be written to the destination buffer before stopping (including the terminating null).
Definition at line 322 of file CharPointer_UTF16.h.
References beast::CharacterFunctions::copyWithCharLimit().
     {
         CharacterFunctions::copyWithCharLimit (*this, src, maxChars);
     }
template<typename CharPointer > size_t beast::CharPointer_UTF16::writeWithDestByteLimit (const CharPointer src, const size_t maxDestBytes) inline noexcept
Copies a source string to this pointer, advancing this pointer as it goes. The maxDestBytes parameter specifies the maximum number of bytes that can be written to the destination buffer before stopping.
Definition at line 312 of file CharPointer_UTF16.h.
References beast::CharacterFunctions::copyWithDestByteLimit().
     {
         return CharacterFunctions::copyWithDestByteLimit (*this, src, maxDestBytes);
     }
Member Data Documentation
CharType* beast::CharPointer_UTF16::data private
Definition at line 514 of file CharPointer_UTF16.h.
Referenced by atomicSwap(), findTerminatingNull(), getAddress(), getAndAdvance(), getIntValue32(), getIntValue64(), isEmpty(), length(), operator const CharType *(), operator!=(), operator*(), operator++(), operator--(), operator<(), operator<=(), operator=(), operator==(), operator>(), operator>=(), sizeInBytes(), write(), writeAll(), and writeNull().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/strings/CharPointer_UTF16.h