rippled: ripple::BuildInfo_test Class Reference
ripple::BuildInfo_test Class Reference
Public Member Functions
void testVersion ()
void checkProtcol (unsigned short vmajor, unsigned short vminor)
void testProtocol ()
void testValues ()
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 167 of file BuildInfo.cpp.
Member Function Documentation
void ripple::BuildInfo_test::checkProtcol (unsigned short vmajor, unsigned short vminor) inline
Definition at line 179 of file BuildInfo.cpp.
References beast::IP::detail::expect().
     {
         typedef BuildInfo::Protocol P;
         expect (P (P (vmajor, vminor).toPacked ()) == P (vmajor, vminor));
     }
void ripple::BuildInfo_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 222 of file BuildInfo.cpp.
References ripple::BuildInfo::getVersionString(), and beast::String::toStdString().
     {
         testVersion ();
         testProtocol ();
         testValues ();
         log <<
             "  Ripple version: " <<
             BuildInfo::getVersionString().toStdString();
     }
void ripple::BuildInfo_test::testProtocol () inline
Definition at line 186 of file BuildInfo.cpp.
References beast::IP::detail::expect(), and testcase.
     {
         typedef BuildInfo::Protocol P;
         testcase ("protocol");
         expect (P (0, 0).toPacked () == 0);
         expect (P (0, 1).toPacked () == 1);
         expect (P (0, 65535).toPacked () == 65535);
         checkProtcol (0, 0);
         checkProtcol (0, 1);
         checkProtcol (0, 255);
         checkProtcol (0, 65535);
         checkProtcol (1, 0);
         checkProtcol (1, 65535);
         checkProtcol (65535, 65535);
     }
void ripple::BuildInfo_test::testValues () inline
Definition at line 205 of file BuildInfo.cpp.
References beast::IP::detail::expect(), ripple::BuildInfo::getCurrentProtocol(), ripple::BuildInfo::getMinimumProtocol(), and testcase.
     {
         testcase ("comparison");
         typedef BuildInfo::Protocol P;
         expect (P(1,2) == P(1,2));
         expect (P(3,4) >= P(3,4));
         expect (P(5,6) <= P(5,6));
         expect (P(7,8) >  P(6,7));
         expect (P(7,8) <  P(8,9));
         expect (P(65535,0) <  P(65535,65535));
         expect (P(65535,65535) >= P(65535,65535));
         expect (BuildInfo::getCurrentProtocol () >= BuildInfo::getMinimumProtocol ());
     }
void ripple::BuildInfo_test::testVersion () inline
Definition at line 170 of file BuildInfo.cpp.
References beast::IP::detail::expect(), ripple::BuildInfo::getRawVersionString(), beast::SemanticVersion::parse(), and testcase.
     {
         testcase ("version");
         beast::SemanticVersion v;
         expect (v.parse (BuildInfo::getRawVersionString ()));
     }
The documentation for this class was generated from the following file:
rippled/src/ripple_data/protocol/BuildInfo.cpp