rippled: rocksdb::BitSet Class Reference
rocksdb::BitSet Class Reference
#include <bit_set.h>
Public Member Functions
BitSet (size_t numBits, bool initial=false)
void set (size_t b)
void reset (size_t b)
bool test (int b) const
size_t size () const
Private Member Functions
size_t numWords () const
Static Private Member Functions
static size_t word (int b)
static int wordOffset (int b)
static unsigned long wordOffsetMask (int b)
Private Attributes
size_t numBits_
std::vector< unsigned long > data_
Detailed Description
Definition at line 11 of file bit_set.h.
Constructor & Destructor Documentation
rocksdb::BitSet::BitSet (size_t numBits, bool initial = false) inline explicit
Create a bit set of numBits, with the bits set to either true or false.
Definition at line 16 of file bit_set.h.
     : numBits_(numBits),
       data_(numWords(), initial ? ~0UL : 0UL) {
   }
Member Function Documentation
size_t rocksdb::BitSet::numWords () const inline private
Definition at line 53 of file bit_set.h.
References numBits_.
{
     if (numBits_ == 0) return 0;
     return 1 + (numBits_-1) / (8*sizeof(unsigned long));
   }
void rocksdb::BitSet::reset (size_t b) inline
Set bit b to 0;
Definition at line 32 of file bit_set.h.
References data_, numBits_, word(), and wordOffsetMask().
{
     assert(b >= 0 && b < numBits_);
     data_[word(b)] &= ~wordOffsetMask(b);
   }
void rocksdb::BitSet::set (size_t b) inline
Set bit b to 1.
Definition at line 24 of file bit_set.h.
References data_, numBits_, word(), and wordOffsetMask().
                      {
     assert(b >= 0 && b < numBits_);
     data_[word(b)] |= wordOffsetMask(b);
   }
size_t rocksdb::BitSet::size () const inline
Return the size of the BitSet, in bits.
Definition at line 47 of file bit_set.h.
References numBits_.
                       {
     return numBits_;
   }
bool rocksdb::BitSet::test (int b) const inline
Get a bit.
Definition at line 40 of file bit_set.h.
References data_, word(), and wordOffsetMask().
{
     return data_[word(b)] & wordOffsetMask(b);
   }
static size_t rocksdb::BitSet::word (int b) inline static private
Definition at line 57 of file bit_set.h.
Referenced by reset(), set(), and test().
{
     return b / (8*sizeof(unsigned long));
   }
static int rocksdb::BitSet::wordOffset (int b) inline static private
Definition at line 60 of file bit_set.h.
Referenced by wordOffsetMask().
{
     return b % (8*sizeof(unsigned long));
   }
static unsigned long rocksdb::BitSet::wordOffsetMask (int b) inline static private
Definition at line 63 of file bit_set.h.
References wordOffset().
Referenced by reset(), set(), and test().
{
     return 1UL << wordOffset(b);
   }
Member Data Documentation
std::vector<unsigned long> rocksdb::BitSet::data_ private
Definition at line 68 of file bit_set.h.
Referenced by reset(), set(), and test().
size_t rocksdb::BitSet::numBits_ private
Definition at line 67 of file bit_set.h.
Referenced by numWords(), reset(), set(), and size().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/util/bit_set.h