rippled: beast::shared_handler_test Class Reference
beast::shared_handler_test Class Reference
Classes
struct test_handler
struct test_invokable
struct test_results
Public Member Functions
template<class Handler >
bool async_op (Handler &&handler)
void virtual_async_op (asio::shared_handler< void(void)> handler)
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 40 of file shared_handler.test.cpp.
Member Function Documentation
template<class Handler > bool beast::shared_handler_test::async_op (Handler && handler) inline
Definition at line 129 of file shared_handler.test.cpp.
Referenced by run(), and virtual_async_op().
     {
         void* const p (boost_asio_handler_alloc_helpers::allocate (32, handler));
         handler();
         boost_asio_handler_alloc_helpers::deallocate (p, 32, handler);
         return boost_asio_handler_cont_helpers::is_continuation (handler);
     }
void beast::shared_handler_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 142 of file shared_handler.test.cpp.
References beast::shared_handler_test::test_results::alloc, async_op(), beast::shared_handler_test::test_results::call, beast::shared_handler_test::test_invokable::call, beast::shared_handler_test::test_results::cont, beast::shared_handler_test::test_results::dealloc, beast::unit_test::suite::expect(), ripple::f, function, beast::shared_handler_test::test_results::invoke, beast::unit_test::suite::unexpected(), value, and virtual_async_op().
     {
     #if ! BEAST_NO_STD_FUNCTION_CONSTRUCTIBLE
         static_assert (! std::is_constructible <
             std::function <void(void)>, int&&>::value,
                 "Cannot construct std::function from int&&");
         static_assert (! std::is_constructible <
             std::function <void(void)>, int>::value,
                 "Cannot construct std::function from int");
         static_assert (! std::is_constructible <
             asio::shared_handler <void(void)>, int>::value,
                 "Cannot construct shared_handler from int");
     #endif
         static_assert (std::is_constructible <
             asio::shared_handler <void(int)>,
                 asio::shared_handler <void(int)>>::value,
                     "Should construct <void(int)> from <void(int)>");
         static_assert (! std::is_constructible <
             asio::shared_handler <void(int)>,
                 asio::shared_handler <void(void)>>::value,
                     "Can't construct <void(int)> from <void(void)>");
         // Hooks called when using the raw handler
         {
             test_results r;
             test_handler h (r);
             async_op (h);
             expect (r.call);
             expect (r.alloc);
             expect (r.dealloc);
             expect (r.cont);
             test_invokable f;
             boost_asio_handler_invoke_helpers::invoke (std::ref (f), h);
             expect (r.invoke);
             expect (f.call);
         }
         // Use of std::function shows the hooks not getting called
         {
             test_results r;
             std::function <void(void)> fh ((test_handler) (r));
             async_op (fh);
             expect (r.call);
             unexpected (r.alloc);
             unexpected (r.dealloc);
             unexpected (r.cont);
             test_invokable f;
             boost_asio_handler_invoke_helpers::invoke (std::ref (f), fh);
             unexpected (r.invoke);
             expect (f.call);
         }
         // Make sure shared_handler calls the hooks
         {
             test_results r;
             asio::shared_handler <void(void)> sh ((test_handler)(r));
             async_op (sh);
             expect (r.call);
             expect (r.alloc);
             expect (r.dealloc);
             expect (r.cont);
             test_invokable f;
             boost_asio_handler_invoke_helpers::invoke (std::ref (f), sh);
             expect (r.invoke);
             expect (f.call);
         }
         // Make sure shared_handler via implicit conversion calls hooks
         {
             test_results r;
             test_handler h (r);
             virtual_async_op ((test_handler) (r));
             expect (r.call);
             expect (r.alloc);
             expect (r.dealloc);
             expect (r.cont);
         }
     }
void beast::shared_handler_test::virtual_async_op (asio::shared_handler< void(void)> handler) inline
Definition at line 137 of file shared_handler.test.cpp.
References async_op().
Referenced by run().
     {
         async_op (handler);
     }
The documentation for this class was generated from the following file:
rippled/src/beast/beast/asio/tests/shared_handler.test.cpp