rippled: beast::OutputStream Class Reference
beast::OutputStream Class Reference abstract
#include <OutputStream.h>
Public Member Functions
virtual ~OutputStream ()
virtual void flush ()=0
virtual bool setPosition (std::int64_t newPosition)=0
virtual std::int64_t getPosition ()=0
virtual bool write (const void *dataToWrite, size_t numberOfBytes)=0
virtual bool writeByte (char byte)
virtual bool writeBool (bool boolValue)
virtual bool writeShort (short value)
virtual bool writeShortBigEndian (short value)
virtual bool writeInt32 (std::int32_t value)
virtual bool writeInt (int value)
virtual bool writeInt32BigEndian (std::int32_t value)
virtual bool writeIntBigEndian (int value)
virtual bool writeInt64 (std::int64_t value)
virtual bool writeInt64BigEndian (std::int64_t value)
virtual bool writeFloat (float value)
virtual bool writeFloatBigEndian (float value)
virtual bool writeDouble (double value)
virtual bool writeDoubleBigEndian (double value)
template<class T >
bool writeType (T value)
template<class T >
bool writeTypeBigEndian (T value)
virtual bool writeRepeatedByte (std::uint8_t byte, size_t numTimesToRepeat)
virtual bool writeCompressedInt (int value)
virtual bool writeString (const String &text)
virtual bool writeText (const String &text, bool asUTF16, bool writeUTF16ByteOrderMark)
virtual int writeFromInputStream (InputStream &source, std::int64_t maxNumBytesToWrite)
void setNewLineString (const String &newLineString)
const String & getNewLineString () const noexcept
template<>
bool writeType (char v)
template<>
bool writeType (short v)
template<>
bool writeType (unsigned char v)
template<>
bool writeType (unsigned short v)
template<>
bool writeType (float v)
template<>
bool writeType (double v)
template<>
bool writeTypeBigEndian (char v)
template<>
bool writeTypeBigEndian (short v)
template<>
bool writeTypeBigEndian (unsigned char v)
template<>
bool writeTypeBigEndian (unsigned short v)
template<>
bool writeTypeBigEndian (float v)
template<>
bool writeTypeBigEndian (double v)
Protected Member Functions
OutputStream ()
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Private Attributes
String newLineString
Detailed Description
The base class for streams that write data to some kind of destination.
Input and output streams are used throughout the library - subclasses can override some or all of the virtual functions to implement their behaviour.
See Also
InputStream, MemoryOutputStream, FileOutputStream
Definition at line 43 of file OutputStream.h.
Constructor & Destructor Documentation
beast::OutputStream::OutputStream () protected
Definition at line 51 of file OutputStream.cpp.
     : newLineString (NewLine::getDefault())
 {
    #if BEAST_DEBUG
     danglingStreamChecker.activeStreams.add (this);
    #endif
 }
beast::OutputStream::~OutputStream () virtual
Destructor.
Some subclasses might want to do things like call flush() during their destructors.
Definition at line 59 of file OutputStream.cpp.
 {
    #if BEAST_DEBUG
     danglingStreamChecker.activeStreams.removeFirstMatchingValue (this);
    #endif
 }
Member Function Documentation
virtual void beast::OutputStream::flush () pure virtual
If the stream is using a buffer, this will ensure it gets written out to the destination.
Implemented in beast::MemoryOutputStream, and beast::FileOutputStream.
const String& beast::OutputStream::getNewLineString () const inline noexcept
Returns the current new-line string that was set by setNewLineString().
Definition at line 258 of file OutputStream.h.
References newLineString.
Referenced by beast::operator<<().
 { return newLineString; }
virtual std::int64_t beast::OutputStream::getPosition () pure virtual
Returns the stream's current position.
See Also
setPosition
Implemented in beast::MemoryOutputStream, and beast::FileOutputStream.
void beast::OutputStream::setNewLineString (const String & newLineString)
Sets the string that will be written to the stream when the writeNewLine() method is called. By default this will be set the the value of NewLine::getDefault().
Definition at line 292 of file OutputStream.cpp.
References newLineString.
 {
     newLineString = newLineString_;
 }
virtual bool beast::OutputStream::setPosition (std::int64_t newPosition) pure virtual
Tries to move the stream's output position.
Not all streams will be able to seek to a new position - this will return false if it fails to work.
See Also
getPosition
Implemented in beast::MemoryOutputStream, and beast::FileOutputStream.
virtual bool beast::OutputStream::write (const void * dataToWrite, size_t numberOfBytes) pure virtual
Writes a block of data to the stream.
When creating a subclass of OutputStream, this is the only write method that needs to be overloaded - the base class has methods for writing other types of data which use this to do the work.
Parameters
dataToWrite the target buffer to receive the data. This must not be null.
numberOfBytes the number of bytes to write.
Returns
false if the write operation fails for some reason
Implemented in beast::MemoryOutputStream, and beast::FileOutputStream.
Referenced by beast::operator<<(), writeByte(), writeCompressedInt(), writeFromInputStream(), writeInt(), writeInt32(), writeInt32BigEndian(), writeInt64(), writeInt64BigEndian(), writeIntBigEndian(), writeShort(), writeShortBigEndian(), writeString(), and writeText().
bool beast::OutputStream::writeBool (bool boolValue) virtual
Writes a boolean to the stream as a single byte. This is encoded as a binary byte (not as text) with a value of 1 or 0.
Returns
false if the write operation fails for some reason
See Also
InputStream::readBool
Definition at line 67 of file OutputStream.cpp.
References writeByte().
 {
     return writeByte (b ? (char) 1
                         : (char) 0);
 }
bool beast::OutputStream::writeByte (char byte) virtual
Writes a single byte to the stream.
Returns
false if the write operation fails for some reason
See Also
InputStream::readByte
Definition at line 73 of file OutputStream.cpp.
References write().
Referenced by beast::operator<<(), writeBool(), and writeRepeatedByte().
 {
     return write (&byte, 1);
 }
bool beast::OutputStream::writeCompressedInt (int value) virtual
Writes a condensed binary encoding of a 32-bit integer.
If you're storing a lot of integers which are unlikely to have very large values, this can save a lot of space, because values under 0xff will only take up 2 bytes, under 0xffff only 3 bytes, etc.
The format used is: number of significant bytes + up to 4 bytes in little-endian order.
Returns
false if the write operation fails for some reason
See Also
InputStream::readCompressedInt
Definition at line 129 of file OutputStream.cpp.
References write().
 {
     unsigned int un = (value < 0) ? (unsigned int) -value
                                   : (unsigned int) value;
     std::uint8_t data[5];
     int num = 0;
     while (un > 0)
     {
         data[++num] = (std::uint8_t) un;
         un >>= 8;
     }
     data[0] = (std::uint8_t) num;
     if (value < 0)
         data[0] |= 0x80;
     return write (data, (size_t) num + 1);
 }
bool beast::OutputStream::writeDouble (double value) virtual
Writes a 64-bit floating point value to the stream in a binary format. The eight raw bytes of the double value are written out as a little-endian 64-bit int.
Returns
false if the write operation fails for some reason
See Also
InputStream::readDouble
Definition at line 177 of file OutputStream.cpp.
References value, and writeInt64().
 {
     union { std::int64_t asInt; double asDouble; } n;
     n.asDouble = value;
     return writeInt64 (n.asInt);
 }
bool beast::OutputStream::writeDoubleBigEndian (double value) virtual
Writes a 64-bit floating point value to the stream in a binary format. The eight raw bytes of the double value are written out as a big-endian 64-bit int.
See Also
InputStream::readDoubleBigEndian
Returns
false if the write operation fails for some reason
Definition at line 184 of file OutputStream.cpp.
References value, and writeInt64BigEndian().
 {
     union { std::int64_t asInt; double asDouble; } n;
     n.asDouble = value;
     return writeInt64BigEndian (n.asInt);
 }
bool beast::OutputStream::writeFloat (float value) virtual
Writes a 32-bit floating point value to the stream in a binary format. The binary 32-bit encoding of the float is written as a little-endian int.
Returns
false if the write operation fails for some reason
See Also
InputStream::readFloat
Definition at line 163 of file OutputStream.cpp.
References value, and writeInt().
 {
     union { int asInt; float asFloat; } n;
     n.asFloat = value;
     return writeInt (n.asInt);
 }
bool beast::OutputStream::writeFloatBigEndian (float value) virtual
Writes a 32-bit floating point value to the stream in a binary format. The binary 32-bit encoding of the float is written as a big-endian int.
Returns
false if the write operation fails for some reason
See Also
InputStream::readFloatBigEndian
Definition at line 170 of file OutputStream.cpp.
References value, and writeIntBigEndian().
 {
     union { int asInt; float asFloat; } n;
     n.asFloat = value;
     return writeIntBigEndian (n.asInt);
 }
int beast::OutputStream::writeFromInputStream (InputStream & source, std::int64_t maxNumBytesToWrite) virtual
Reads data from an input stream and writes it to this stream.
Parameters
source the stream to read from
maxNumBytesToWrite the number of bytes to read from the stream (if this is less than zero, it will keep reading until the input is exhausted)
Returns
the number of bytes written
Reimplemented in beast::MemoryOutputStream.
Definition at line 267 of file OutputStream.cpp.
References beast::bmin(), ripple::max(), beast::InputStream::read(), and write().
Referenced by beast::File::copyInternal(), beast::operator<<(), and beast::MemoryOutputStream::writeFromInputStream().
 {
     if (numBytesToWrite < 0)
         numBytesToWrite = std::numeric_limits<std::int64_t>::max();
     int numWritten = 0;
     while (numBytesToWrite > 0)
     {
         char buffer [8192];
         const int num = source.read (buffer, (int) bmin (numBytesToWrite, (std::int64_t) sizeof (buffer)));
         if (num <= 0)
             break;
         write (buffer, (size_t) num);
         numBytesToWrite -= num;
         numWritten += num;
     }
     return numWritten;
 }
bool beast::OutputStream::writeInt (int value) virtual
Definition at line 107 of file OutputStream.cpp.
References static_bassert, beast::ByteOrder::swapIfBigEndian(), and write().
Referenced by writeFloat().
 {
     static_bassert (sizeof (int) == 4);
     const unsigned int v = ByteOrder::swapIfBigEndian ((unsigned int) value);
     return write (&v, 4);
 }
bool beast::OutputStream::writeInt32 (std::int32_t value) virtual
Writes a 32-bit integer to the stream in a little-endian byte order.
Returns
false if the write operation fails for some reason
See Also
InputStream::readInt
Definition at line 99 of file OutputStream.cpp.
References static_bassert, beast::ByteOrder::swapIfBigEndian(), and write().
 {
     static_bassert (sizeof (std::int32_t) == 4);
     const unsigned int v = ByteOrder::swapIfBigEndian ((std::uint32_t) value);
     return write (&v, 4);
 }
bool beast::OutputStream::writeInt32BigEndian (std::int32_t value) virtual
Writes a 32-bit integer to the stream in a big-endian byte order.
Returns
false if the write operation fails for some reason
See Also
InputStream::readIntBigEndian
Definition at line 115 of file OutputStream.cpp.
References static_bassert, beast::ByteOrder::swapIfLittleEndian(), and write().
 {
     static_bassert (sizeof (std::int32_t) == 4);
     const std::uint32_t v = ByteOrder::swapIfLittleEndian ((std::uint32_t) value);
     return write (&v, 4);
 }
bool beast::OutputStream::writeInt64 (std::int64_t value) virtual
Writes a 64-bit integer to the stream in a little-endian byte order.
Returns
false if the write operation fails for some reason
See Also
InputStream::readInt64
Definition at line 151 of file OutputStream.cpp.
References beast::ByteOrder::swapIfBigEndian(), and write().
Referenced by writeDouble().
 {
     const std::uint64_t v = ByteOrder::swapIfBigEndian ((std::uint64_t) value);
     return write (&v, 8);
 }
bool beast::OutputStream::writeInt64BigEndian (std::int64_t value) virtual
Writes a 64-bit integer to the stream in a big-endian byte order.
Returns
false if the write operation fails for some reason
See Also
InputStream::readInt64BigEndian
Definition at line 157 of file OutputStream.cpp.
References beast::ByteOrder::swapIfLittleEndian(), and write().
Referenced by writeDoubleBigEndian().
 {
     const std::uint64_t v = ByteOrder::swapIfLittleEndian ((std::uint64_t) value);
     return write (&v, 8);
 }
bool beast::OutputStream::writeIntBigEndian (int value) virtual
Definition at line 122 of file OutputStream.cpp.
References static_bassert, beast::ByteOrder::swapIfLittleEndian(), and write().
Referenced by writeFloatBigEndian().
 {
     static_bassert (sizeof (int) == 4);
     const unsigned int v = ByteOrder::swapIfLittleEndian ((unsigned int) value);
     return write (&v, 4);
 }
bool beast::OutputStream::writeRepeatedByte (std::uint8_t byte, size_t numTimesToRepeat) virtual
Writes a byte to the output stream a given number of times.
Returns
false if the write operation fails for some reason
Reimplemented in beast::MemoryOutputStream, and beast::FileOutputStream.
Definition at line 78 of file OutputStream.cpp.
References writeByte().
Referenced by beast::FileOutputStream::writeRepeatedByte().
 {
     for (size_t i = 0; i < numTimesToRepeat; ++i)
         if (! writeByte ((char) byte))
             return false;
     return true;
 }
bool beast::OutputStream::writeShort (short value) virtual
Writes a 16-bit integer to the stream in a little-endian byte order. This will write two bytes to the stream: (value & 0xff), then (value >> 8).
Returns
false if the write operation fails for some reason
See Also
InputStream::readShort
Definition at line 87 of file OutputStream.cpp.
References beast::ByteOrder::swapIfBigEndian(), and write().
Referenced by writeText().
 {
     const unsigned short v = ByteOrder::swapIfBigEndian ((unsigned short) value);
     return write (&v, 2);
 }
bool beast::OutputStream::writeShortBigEndian (short value) virtual
Writes a 16-bit integer to the stream in a big-endian byte order. This will write two bytes to the stream: (value >> 8), then (value & 0xff).
Returns
false if the write operation fails for some reason
See Also
InputStream::readShortBigEndian
Definition at line 93 of file OutputStream.cpp.
References beast::ByteOrder::swapIfLittleEndian(), and write().
 {
     const unsigned short v = ByteOrder::swapIfLittleEndian ((unsigned short) value);
     return write (&v, 2);
 }
bool beast::OutputStream::writeString (const String & text) virtual
Stores a string in the stream in a binary format.
This isn't the method to use if you're trying to append text to the end of a text-file! It's intended for storing a string so that it can be retrieved later by InputStream::readString().
It writes the string to the stream as UTF8, including the null termination character.
For appending text to a file, instead use writeText, or operator<<
Returns
false if the write operation fails for some reason
See Also
InputStream::readString, writeText, operator<<
Definition at line 191 of file OutputStream.cpp.
References beast::String::copyToUTF8(), beast::String::getNumBytesAsUTF8(), and write().
 {
     // (This avoids using toUTF8() to prevent the memory bloat that it would leave behind
     // if lots of large, persistent strings were to be written to streams).
     const size_t numBytes = text.getNumBytesAsUTF8() + 1;
     HeapBlock<char> temp (numBytes);
     text.copyToUTF8 (temp, numBytes);
     return write (temp, numBytes);
 }
bool beast::OutputStream::writeText (const String & text, bool asUTF16, bool writeUTF16ByteOrderMark) virtual
Writes a string of text to the stream.
It can either write the text as UTF-8 or UTF-16, and can also add the UTF-16 byte-order-mark bytes (0xff, 0xfe) to indicate the endianness (these should only be used at the start of a file).
The method also replaces '\n' characters in the text with '\r\n'.
Returns
false if the write operation fails for some reason
Definition at line 201 of file OutputStream.cpp.
References beast::CharPointer_UTF8::getAndAdvance(), beast::String::getCharPointer(), beast::String::toUTF8(), write(), and writeShort().
Referenced by beast::File::appendText().
 {
     if (asUTF16)
     {
         if (writeUTF16ByteOrderMark)
             write ("\x0ff\x0fe", 2);
         String::CharPointerType src (text.getCharPointer());
         bool lastCharWasReturn = false;
         for (;;)
         {
             const beast_wchar c = src.getAndAdvance();
             if (c == 0)
                 break;
             if (c == '\n' && ! lastCharWasReturn)
                 writeShort ((short) '\r');
             lastCharWasReturn = (c == L'\r');
             if (! writeShort ((short) c))
                 return false;
         }
     }
     else
     {
         const char* src = text.toUTF8();
         const char* t = src;
         for (;;)
         {
             if (*t == '\n')
             {
                 if (t > src)
                     if (! write (src, (size_t) (t - src)))
                         return false;
                 if (! write ("\r\n", 2))
                     return false;
                 src = t + 1;
             }
             else if (*t == '\r')
             {
                 if (t[1] == '\n')
                     ++t;
             }
             else if (*t == 0)
             {
                 if (t > src)
                     if (! write (src, (size_t) (t - src)))
                         return false;
                 break;
             }
             ++t;
         }
     }
     return true;
 }
template<class T > bool beast::OutputStream::writeType (T value)
Write a type using a template specialization.
This is useful when doing template meta-programming.
template<> bool beast::OutputStream::writeType (char v)
Definition at line 360 of file OutputStream.cpp.
 { return writeByte (v); }
template<> bool beast::OutputStream::writeType (short v)
Definition at line 363 of file OutputStream.cpp.
 { return writeShort (v); }
template<> bool beast::OutputStream::writeType (unsigned char v)
Definition at line 372 of file OutputStream.cpp.
 { return writeByte (static_cast <char> (v)); }
template<> bool beast::OutputStream::writeType (unsigned short v)
Definition at line 375 of file OutputStream.cpp.
 { return writeShort (static_cast <short> (v)); }
template<> bool beast::OutputStream::writeType (float v)
Definition at line 384 of file OutputStream.cpp.
 { return writeFloat (v); }
template<> bool beast::OutputStream::writeType (double v)
Definition at line 387 of file OutputStream.cpp.
 { return writeDouble (v); }
template<class T > bool beast::OutputStream::writeTypeBigEndian (T value)
Write a type using a template specialization.
The raw encoding of the type is written to the stream as a big-endian value where applicable.
This is useful when doing template meta-programming.
template<> bool beast::OutputStream::writeTypeBigEndian (char v)
Definition at line 392 of file OutputStream.cpp.
 { return writeByte (v); }
template<> bool beast::OutputStream::writeTypeBigEndian (short v)
Definition at line 395 of file OutputStream.cpp.
 { return writeShortBigEndian (v); }
template<> bool beast::OutputStream::writeTypeBigEndian (unsigned char v)
Definition at line 404 of file OutputStream.cpp.
 { return writeByte (static_cast <char> (v)); }
template<> bool beast::OutputStream::writeTypeBigEndian (unsigned short v)
Definition at line 407 of file OutputStream.cpp.
 { return writeShortBigEndian (static_cast <short> (v)); }
template<> bool beast::OutputStream::writeTypeBigEndian (float v)
Definition at line 416 of file OutputStream.cpp.
 { return writeFloatBigEndian (v); }
template<> bool beast::OutputStream::writeTypeBigEndian (double v)
Definition at line 419 of file OutputStream.cpp.
 { return writeDoubleBigEndian (v); }
Member Data Documentation
String beast::OutputStream::newLineString private
Definition at line 262 of file OutputStream.h.
Referenced by getNewLineString(), and setNewLineString().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_core/streams/OutputStream.h
rippled/src/beast/modules/beast_core/streams/OutputStream.cpp