rippled: rocksdb::MemTable Class Reference
rocksdb::MemTable Class Reference
#include <memtable.h>
Classes
struct KeyComparator
Public Member Functions
MemTable (const InternalKeyComparator &comparator, std::shared_ptr< MemTableRepFactory > table_factory, int numlevel=7, const Options &options=Options())
void Ref ()
void Unref ()
size_t ApproximateMemoryUsage ()
Iterator * NewIterator (const ReadOptions &options=ReadOptions())
void Add (SequenceNumber seq, ValueType type, const Slice &key, const Slice &value)
bool Get (const LookupKey &key, std::string *value, Status *s, std::deque< std::string > *operands, const Options &options)
bool Update (SequenceNumber seq, ValueType type, const Slice &key, const Slice &value)
VersionEdit * GetEdits ()
SequenceNumber GetFirstSequenceNumber ()
uint64_t GetNextLogNumber ()
void SetNextLogNumber (uint64_t num)
uint64_t GetLogNumber ()
void SetLogNumber (uint64_t num)
void MarkImmutable ()
Private Member Functions
~MemTable ()
MemTable (const MemTable &)
void operator= (const MemTable &)
port::RWMutex * GetLock (const Slice &key)
Private Attributes
KeyComparator comparator_
int refs_
ArenaImpl arena_impl_
shared_ptr< MemTableRep > table_
bool flush_in_progress_
bool flush_completed_
uint64_t file_number_
VersionEdit edit_
SequenceNumber first_seqno_
uint64_t mem_next_logfile_number_
uint64_t mem_logfile_number_
std::vector< port::RWMutex > locks_
Friends
class MemTableIterator
class MemTableBackwardIterator
class MemTableList
Detailed Description
Definition at line 26 of file memtable.h.
Constructor & Destructor Documentation
rocksdb::MemTable::MemTable (const InternalKeyComparator & comparator, std::shared_ptr< MemTableRepFactory > table_factory, int numlevel = 7, const Options & options = Options()) explicit
Definition at line 37 of file memtable.cc.
     : comparator_(cmp),
       refs_(0),
       arena_impl_(options.arena_block_size),
       table_(table_factory->CreateMemTableRep(comparator_, &arena_impl_)),
       flush_in_progress_(false),
       flush_completed_(false),
       file_number_(0),
       edit_(numlevel),
       first_seqno_(0),
       mem_next_logfile_number_(0),
       mem_logfile_number_(0),
       locks_(options.inplace_update_support
              ? options.inplace_update_num_locks
              : 0) { }
rocksdb::MemTable::~MemTable () private
Definition at line 56 of file memtable.cc.
References refs_.
                     {
   assert(refs_ == 0);
 }
rocksdb::MemTable::MemTable (const MemTable &) private
Member Function Documentation
void rocksdb::MemTable::Add (SequenceNumber seq, ValueType type, const Slice & key, const Slice & value)
Definition at line 134 of file memtable.cc.
References rocksdb::ArenaImpl::Allocate(), arena_impl_, rocksdb::Slice::data(), rocksdb::EncodeFixed64(), rocksdb::EncodeVarint32(), first_seqno_, rocksdb::Slice::size(), table_, and rocksdb::VarintLength().
Referenced by rocksdb::MemTableConstructor::FinishImpl().
{
   // Format of an entry is concatenation of:
   //  key_size     : varint32 of internal_key.size()
   //  key bytes    : char[internal_key.size()]
   //  value_size   : varint32 of value.size()
   //  value bytes  : char[value.size()]
   size_t key_size = key.size();
   size_t val_size = value.size();
   size_t internal_key_size = key_size + 8;
   const size_t encoded_len =
       VarintLength(internal_key_size) + internal_key_size +
       VarintLength(val_size) + val_size;
   char* buf = arena_impl_.Allocate(encoded_len);
   char* p = EncodeVarint32(buf, internal_key_size);
   memcpy(p, key.data(), key_size);
   p += key_size;
   EncodeFixed64(p, (s << 8) | type);
   p += 8;
   p = EncodeVarint32(p, val_size);
   memcpy(p, value.data(), val_size);
   assert((p + val_size) - buf == (unsigned)encoded_len);
   table_->Insert(buf);
   // The first sequence number inserted into the memtable
   assert(first_seqno_ == 0 || s > first_seqno_);
   if (first_seqno_ == 0) {
     first_seqno_ = s;
   }
 }
size_t rocksdb::MemTable::ApproximateMemoryUsage ()
Definition at line 60 of file memtable.cc.
References rocksdb::ArenaImpl::ApproximateMemoryUsage(), arena_impl_, and table_.
Referenced by rocksdb::DBImpl::MakeRoomForWrite(), and rocksdb::DBImpl::RecoverLogFile().
{
   return arena_impl_.ApproximateMemoryUsage() +
     table_->ApproximateMemoryUsage();
 }
bool rocksdb::MemTable::Get (const LookupKey & key, std::string * value, Status * s, std::deque< std::string > * operands, const Options & options)
Definition at line 166 of file memtable.cc.
References rocksdb::MemTable::KeyComparator::comparator, comparator_, rocksdb::Comparator::Compare(), rocksdb::Status::Corruption(), rocksdb::Slice::data(), rocksdb::DecodeFixed64(), rocksdb::GetLengthPrefixedSlice(), GetLock(), rocksdb::GetVarint32Ptr(), rocksdb::Options::info_log, rocksdb::Options::inplace_update_support, rocksdb::Status::IsMergeInProgress(), key_length, rocksdb::kTypeDeletion, rocksdb::kTypeLogData, rocksdb::kTypeMerge, rocksdb::kTypeValue, logger, rocksdb::LookupKey::memtable_key(), rocksdb::Options::merge_operator, merge_operator, rocksdb::Status::MergeInProgress(), rocksdb::Status::NotFound(), rocksdb::NUMBER_MERGE_FAILURES, rocksdb::Status::OK(), rocksdb::RecordTick(), rocksdb::Slice::size(), rocksdb::Options::statistics, beast::asio::swap(), table_, rocksdb::Slice::ToString(), rocksdb::InternalKeyComparator::user_comparator(), rocksdb::LookupKey::user_key(), and value.
Referenced by rocksdb::DBImplReadOnly::Get(), rocksdb::DBImpl::GetImpl(), and rocksdb::DBImpl::MultiGet().
{
   Slice memkey = key.memtable_key();
   std::shared_ptr<MemTableRep::Iterator> iter(
     table_->GetIterator(key.user_key()));
   iter->Seek(memkey.data());
   // It is the caller's responsibility to allocate/delete operands list
   assert(operands != nullptr);
   bool merge_in_progress = s->IsMergeInProgress();
   auto merge_operator = options.merge_operator.get();
   auto logger = options.info_log;
   std::string merge_result;
   for (; iter->Valid(); iter->Next()) {
     // entry format is:
     //    klength  varint32
     //    userkey  char[klength-8]
     //    tag      uint64
     //    vlength  varint32
     //    value    char[vlength]
     // Check that it belongs to same user key.  We do not check the
     // sequence number since the Seek() call above should have skipped
     // all entries with overly large sequence numbers.
     const char* entry = iter->key();
     uint32_t key_length;
     const char* key_ptr = GetVarint32Ptr(entry, entry + 5, &key_length);
     if (comparator_.comparator.user_comparator()->Compare(
         Slice(key_ptr, key_length - 8), key.user_key()) == 0) {
       // Correct user key
       const uint64_t tag = DecodeFixed64(key_ptr + key_length - 8);
       switch (static_cast<ValueType>(tag & 0xff)) {
         case kTypeValue: {
           if (options.inplace_update_support) {
             GetLock(key.user_key())->ReadLock();
           }
           Slice v = GetLengthPrefixedSlice(key_ptr + key_length);
           *s = Status::OK();
           if (merge_in_progress) {
             assert(merge_operator);
             if (!merge_operator->FullMerge(key.user_key(), &v, *operands,
                                            value, logger.get())) {
               RecordTick(options.statistics, NUMBER_MERGE_FAILURES);
               *s = Status::Corruption("Error: Could not perform merge.");
             }
           } else {
             value->assign(v.data(), v.size());
           }
           if (options.inplace_update_support) {
             GetLock(key.user_key())->Unlock();
           }
           return true;
         }
         case kTypeDeletion: {
           if (merge_in_progress) {
             assert(merge_operator);
             *s = Status::OK();
             if (!merge_operator->FullMerge(key.user_key(), nullptr, *operands,
                                            value, logger.get())) {
               RecordTick(options.statistics, NUMBER_MERGE_FAILURES);
               *s = Status::Corruption("Error: Could not perform merge.");
             }
           } else {
             *s = Status::NotFound(Slice());
           }
           return true;
         }
         case kTypeMerge: {
           Slice v = GetLengthPrefixedSlice(key_ptr + key_length);
           merge_in_progress = true;
           operands->push_front(v.ToString());
           while(operands->size() >= 2) {
             // Attempt to associative merge. (Returns true if successful)
             if (merge_operator->PartialMerge(key.user_key(),
                                              Slice((*operands)[0]),
                                              Slice((*operands)[1]),
                                              &merge_result,
                                              logger.get())) {
               operands->pop_front();
               swap(operands->front(), merge_result);
             } else {
               // Stack them because user can't associative merge
               break;
             }
           }
           break;
         }
         case kTypeLogData:
           assert(false);
           break;
       }
     } else {
       // exit loop if user key does not match
       break;
     }
   }
   // No change to value, since we have not yet found a Put/Delete
   if (merge_in_progress) {
     *s = Status::MergeInProgress("");
   }
   return false;
 }
VersionEdit* rocksdb::MemTable::GetEdits () inline
Definition at line 106 of file memtable.h.
References edit_.
Referenced by rocksdb::DBImpl::FlushMemTableToOutputFile().
 { return &edit_; }
SequenceNumber rocksdb::MemTable::GetFirstSequenceNumber () inline
Definition at line 110 of file memtable.h.
References first_seqno_.
Referenced by rocksdb::DBImpl::WriteLevel0TableForRecovery(), and rocksdb::DBImpl::~DBImpl().
 { return first_seqno_; }
port::RWMutex * rocksdb::MemTable::GetLock (const Slice & key) private
Definition at line 130 of file memtable.cc.
References locks_.
Referenced by Get(), and Update().
{
   return &locks_[std::hash<Slice>()(key) % locks_.size()];
 }
uint64_t rocksdb::MemTable::GetLogNumber () inline
Definition at line 122 of file memtable.h.
References mem_logfile_number_.
 { return mem_logfile_number_; }
uint64_t rocksdb::MemTable::GetNextLogNumber () inline
Definition at line 114 of file memtable.h.
References mem_next_logfile_number_.
 { return mem_next_logfile_number_; }
void rocksdb::MemTable::MarkImmutable () inline
Definition at line 129 of file memtable.h.
References table_.
Referenced by rocksdb::MemTableList::Add().
 { table_->MarkReadOnly(); }
Iterator * rocksdb::MemTable::NewIterator (const ReadOptions & options = ReadOptions())
Definition at line 126 of file memtable.cc.
References MemTableIterator, and table_.
Referenced by rocksdb::DBImpl::NewInternalIterator(), rocksdb::MemTableConstructor::NewIterator(), and rocksdb::DBImpl::WriteLevel0TableForRecovery().
{
   return new MemTableIterator(table_.get(), options);
 }
void rocksdb::MemTable::operator= (const MemTable &) private
void rocksdb::MemTable::Ref () inline
Definition at line 43 of file memtable.h.
References refs_.
Referenced by rocksdb::DBImpl::DBImpl(), rocksdb::MemTableConstructor::FinishImpl(), rocksdb::DBImpl::GetImpl(), rocksdb::DBImpl::MakeRoomForWrite(), rocksdb::MemTableConstructor::MemTableConstructor(), rocksdb::DBImpl::MultiGet(), rocksdb::DBImpl::NewInternalIterator(), and rocksdb::DBImpl::RecoverLogFile().
 { ++refs_; }
void rocksdb::MemTable::SetLogNumber (uint64_t num) inline
Definition at line 126 of file memtable.h.
References mem_logfile_number_.
Referenced by rocksdb::DBImpl::MakeRoomForWrite(), and rocksdb::DB::Open().
 { mem_logfile_number_ = num; }
void rocksdb::MemTable::SetNextLogNumber (uint64_t num) inline
Definition at line 118 of file memtable.h.
References mem_next_logfile_number_.
Referenced by rocksdb::DBImpl::MakeRoomForWrite().
 { mem_next_logfile_number_ = num; }
void rocksdb::MemTable::Unref () inline
Definition at line 46 of file memtable.h.
References refs_.
Referenced by rocksdb::MemTableConstructor::FinishImpl(), rocksdb::DBImpl::GetImpl(), rocksdb::MemTableList::InstallMemtableFlushResults(), rocksdb::DBImpl::MultiGet(), rocksdb::DBImpl::RecoverLogFile(), rocksdb::DBImpl::~DBImpl(), and rocksdb::MemTableConstructor::~MemTableConstructor().
                {
     --refs_;
     assert(refs_ >= 0);
     if (refs_ <= 0) {
       delete this;
     }
   }
bool rocksdb::MemTable::Update (SequenceNumber seq, ValueType type, const Slice & key, const Slice & value)
Definition at line 272 of file memtable.cc.
References rocksdb::MemTable::KeyComparator::comparator, comparator_, rocksdb::Comparator::Compare(), rocksdb::Slice::data(), rocksdb::DecodeFixed64(), rocksdb::EncodeVarint32(), GetLock(), rocksdb::GetVarint32Ptr(), key_length, rocksdb::kTypeValue, rocksdb::LookupKey::memtable_key(), rocksdb::Slice::size(), table_, rocksdb::InternalKeyComparator::user_comparator(), rocksdb::LookupKey::user_key(), and rocksdb::VarintLength().
{
   LookupKey lkey(key, seq);
   Slice memkey = lkey.memtable_key();
   std::shared_ptr<MemTableRep::Iterator> iter(
     table_.get()->GetIterator(lkey.user_key()));
   iter->Seek(memkey.data());
   if (iter->Valid()) {
     // entry format is:
     //    klength  varint32
     //    userkey  char[klength-8]
     //    tag      uint64
     //    vlength  varint32
     //    value    char[vlength]
     // Check that it belongs to same user key.  We do not check the
     // sequence number since the Seek() call above should have skipped
     // all entries with overly large sequence numbers.
     const char* entry = iter->key();
     uint32_t key_length;
     const char* key_ptr = GetVarint32Ptr(entry, entry + 5, &key_length);
     if (comparator_.comparator.user_comparator()->Compare(
         Slice(key_ptr, key_length - 8), lkey.user_key()) == 0) {
       // Correct user key
       const uint64_t tag = DecodeFixed64(key_ptr + key_length - 8);
       switch (static_cast<ValueType>(tag & 0xff)) {
         case kTypeValue: {
           uint32_t vlength;
           GetVarint32Ptr(key_ptr + key_length,
                          key_ptr + key_length+5, &vlength);
           // Update value, if newValue size  <= curValue size
           if (value.size() <= vlength) {
             char* p = EncodeVarint32(const_cast<char*>(key_ptr) + key_length,
                                      value.size());
             WriteLock wl(GetLock(lkey.user_key()));
             memcpy(p, value.data(), value.size());
             assert(
               (p + value.size()) - entry ==
               (unsigned) (VarintLength(key_length) +
                           key_length +
                           VarintLength(value.size()) +
                           value.size())
             );
             return true;
           }
         }
         default:
           // If the latest value is kTypeDeletion, kTypeMerge or kTypeLogData
           // then we probably don't have enough space to update in-place
           // Maybe do something later
           // Return false, and do normal Add()
           return false;
       }
     }
   }
   // Key doesn't exist
   return false;
 }
Friends And Related Function Documentation
friend class MemTableBackwardIterator friend
Definition at line 134 of file memtable.h.
friend class MemTableIterator friend
Definition at line 133 of file memtable.h.
Referenced by NewIterator().
friend class MemTableList friend
Definition at line 135 of file memtable.h.
Member Data Documentation
ArenaImpl rocksdb::MemTable::arena_impl_ private
Definition at line 139 of file memtable.h.
Referenced by Add(), and ApproximateMemoryUsage().
KeyComparator rocksdb::MemTable::comparator_ private
Definition at line 137 of file memtable.h.
Referenced by Get(), and Update().
VersionEdit rocksdb::MemTable::edit_ private
Definition at line 149 of file memtable.h.
Referenced by GetEdits(), and rocksdb::MemTableList::InstallMemtableFlushResults().
uint64_t rocksdb::MemTable::file_number_ private
Definition at line 145 of file memtable.h.
Referenced by rocksdb::MemTableList::InstallMemtableFlushResults().
SequenceNumber rocksdb::MemTable::first_seqno_ private
Definition at line 152 of file memtable.h.
Referenced by Add(), and GetFirstSequenceNumber().
bool rocksdb::MemTable::flush_completed_ private
Definition at line 144 of file memtable.h.
Referenced by rocksdb::MemTableList::InstallMemtableFlushResults(), and rocksdb::MemTableList::PickMemtablesToFlush().
bool rocksdb::MemTable::flush_in_progress_ private
Definition at line 143 of file memtable.h.
Referenced by rocksdb::MemTableList::InstallMemtableFlushResults(), and rocksdb::MemTableList::PickMemtablesToFlush().
std::vector<port::RWMutex> rocksdb::MemTable::locks_ private
Definition at line 162 of file memtable.h.
Referenced by GetLock().
uint64_t rocksdb::MemTable::mem_logfile_number_ private
Definition at line 159 of file memtable.h.
Referenced by GetLogNumber(), and SetLogNumber().
uint64_t rocksdb::MemTable::mem_next_logfile_number_ private
Definition at line 155 of file memtable.h.
Referenced by GetNextLogNumber(), and SetNextLogNumber().
int rocksdb::MemTable::refs_ private
Definition at line 138 of file memtable.h.
Referenced by Ref(), Unref(), and ~MemTable().
shared_ptr<MemTableRep> rocksdb::MemTable::table_ private
Definition at line 140 of file memtable.h.
Referenced by Add(), ApproximateMemoryUsage(), Get(), MarkImmutable(), NewIterator(), and Update().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/db/memtable.h
rippled/src/ripple/rocksdb/rocksdb/db/memtable.cc