rippled: rocksdb::log::Writer Class Reference
rocksdb::log::Writer Class Reference
#include <log_writer.h>
Public Member Functions
Writer (unique_ptr< WritableFile > &&dest)
~Writer ()
Status AddRecord (const Slice &slice)
WritableFile * file ()
const WritableFile * file () const
Private Member Functions
Status EmitPhysicalRecord (RecordType type, const char *ptr, size_t length)
Writer (const Writer &)
void operator= (const Writer &)
Private Attributes
unique_ptr< WritableFile > dest_
int block_offset_
uint32_t type_crc_ [kMaxRecordType+1]
Detailed Description
Definition at line 25 of file log_writer.h.
Constructor & Destructor Documentation
rocksdb::log::Writer::Writer (unique_ptr< WritableFile > && dest) explicit
Definition at line 20 of file log_writer.cc.
References rocksdb::log::kMaxRecordType, type_crc_, and rocksdb::crc32c::Value().
     : dest_(std::move(dest)),
       block_offset_(0) {
   for (int i = 0; i <= kMaxRecordType; i++) {
     char t = static_cast<char>(i);
     type_crc_[i] = crc32c::Value(&t, 1);
   }
 }
rocksdb::log::Writer::~Writer ()
Definition at line 29 of file log_writer.cc.
                 {
 }
rocksdb::log::Writer::Writer (const Writer &) private
Member Function Documentation
Status rocksdb::log::Writer::AddRecord (const Slice & slice)
Definition at line 32 of file log_writer.cc.
References block_offset_, rocksdb::Slice::data(), dest_, EmitPhysicalRecord(), rocksdb::log::kBlockSize, rocksdb::log::kFirstType, rocksdb::log::kFullType, rocksdb::log::kHeaderSize, rocksdb::log::kLastType, rocksdb::log::kMiddleType, rocksdb::Status::ok(), and rocksdb::Slice::size().
Referenced by rocksdb::DBImpl::NewDB(), rocksdb::log::LogTest::Write(), and rocksdb::VersionSet::WriteSnapshot().
{
   const char* ptr = slice.data();
   size_t left = slice.size();
   // Fragment the record if necessary and emit it.  Note that if slice
   // is empty, we still want to iterate once to emit a single
   // zero-length record
   Status s;
   bool begin = true;
   do {
     const int leftover = kBlockSize - block_offset_;
     assert(leftover >= 0);
     if (leftover < kHeaderSize) {
       // Switch to a new block
       if (leftover > 0) {
         // Fill the trailer (literal below relies on kHeaderSize being 7)
         assert(kHeaderSize == 7);
         dest_->Append(Slice("\x00\x00\x00\x00\x00\x00", leftover));
       }
       block_offset_ = 0;
     }
     // Invariant: we never leave < kHeaderSize bytes in a block.
     assert(kBlockSize - block_offset_ - kHeaderSize >= 0);
     const size_t avail = kBlockSize - block_offset_ - kHeaderSize;
     const size_t fragment_length = (left < avail) ? left : avail;
     RecordType type;
     const bool end = (left == fragment_length);
     if (begin && end) {
       type = kFullType;
     } else if (begin) {
       type = kFirstType;
     } else if (end) {
       type = kLastType;
     } else {
       type = kMiddleType;
     }
     s = EmitPhysicalRecord(type, ptr, fragment_length);
     ptr += fragment_length;
     left -= fragment_length;
     begin = false;
   } while (s.ok() && left > 0);
   return s;
 }
Status rocksdb::log::Writer::EmitPhysicalRecord (RecordType type, const char * ptr, size_t length) private
Definition at line 80 of file log_writer.cc.
References block_offset_, dest_, rocksdb::EncodeFixed32(), rocksdb::crc32c::Extend(), rocksdb::log::kBlockSize, rocksdb::log::kHeaderSize, rocksdb::crc32c::Mask(), rocksdb::Status::ok(), and type_crc_.
Referenced by AddRecord().
{
   assert(n <= 0xffff);  // Must fit in two bytes
   assert(block_offset_ + kHeaderSize + n <= kBlockSize);
   // Format the header
   char buf[kHeaderSize];
   buf[4] = static_cast<char>(n & 0xff);
   buf[5] = static_cast<char>(n >> 8);
   buf[6] = static_cast<char>(t);
   // Compute the crc of the record type and the payload.
   uint32_t crc = crc32c::Extend(type_crc_[t], ptr, n);
   crc = crc32c::Mask(crc);                 // Adjust for storage
   EncodeFixed32(buf, crc);
   // Write the header and the payload
   Status s = dest_->Append(Slice(buf, kHeaderSize));
   if (s.ok()) {
     s = dest_->Append(Slice(ptr, n));
     if (s.ok()) {
       s = dest_->Flush();
     }
   }
   block_offset_ += kHeaderSize + n;
   return s;
 }
WritableFile* rocksdb::log::Writer::file () inline
Definition at line 35 of file log_writer.h.
References dest_.
Referenced by rocksdb::log::LogTest::dest_contents().
 { return dest_.get(); }
const WritableFile* rocksdb::log::Writer::file () const inline
Definition at line 36 of file log_writer.h.
References dest_.
 { return dest_.get(); }
void rocksdb::log::Writer::operator= (const Writer &) private
Member Data Documentation
int rocksdb::log::Writer::block_offset_ private
Definition at line 40 of file log_writer.h.
Referenced by AddRecord(), and EmitPhysicalRecord().
unique_ptr<WritableFile> rocksdb::log::Writer::dest_ private
Definition at line 39 of file log_writer.h.
Referenced by AddRecord(), EmitPhysicalRecord(), and file().
uint32_t rocksdb::log::Writer::type_crc_[kMaxRecordType+1] private
Definition at line 45 of file log_writer.h.
Referenced by EmitPhysicalRecord(), and Writer().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/db/log_writer.h
rippled/src/ripple/rocksdb/rocksdb/db/log_writer.cc