rippled: beast.util.Dict_test.test_Dict Class Reference
beast.util.Dict_test.test_Dict Class Reference
Public Member Functions
def computeMapValue
def assertMapValue
def testDefault1
def testDefault2
def testPrefix1
def testPrefix2
def testPrefix3
def testPrefix4
def testFailure1
def testFailure2
def testFailure2
Detailed Description
Definition at line 24 of file Dict_test.py.
Member Function Documentation
def beast.util.Dict_test.test_Dict.assertMapValue (self, config, key, result)
Definition at line 28 of file Dict_test.py.
References beast.util.Dict_test.test_Dict.computeMapValue().
Referenced by beast.util.Dict_test.test_Dict.testDefault1(), beast.util.Dict_test.test_Dict.testDefault2(), beast.util.Dict_test.test_Dict.testPrefix1(), beast.util.Dict_test.test_Dict.testPrefix2(), beast.util.Dict_test.test_Dict.testPrefix3(), and beast.util.Dict_test.test_Dict.testPrefix4().
     def assertMapValue(self, config, key, result):
         self.assertEquals(self.computeMapValue(config, key), result)
def beast.util.Dict_test.test_Dict.computeMapValue (self, config, key)
Definition at line 25 of file Dict_test.py.
Referenced by beast.util.Dict_test.test_Dict.assertMapValue(), beast.util.Dict_test.test_Dict.testFailure1(), and beast.util.Dict_test.test_Dict.testFailure2().
     def computeMapValue(self, config, key):
         return Dict.compose(*Dict.get_items_with_prefix(config, DICT))[key]
def beast.util.Dict_test.test_Dict.testDefault1 (self)
Definition at line 31 of file Dict_test.py.
References beast.util.Dict_test.test_Dict.assertMapValue().
     def testDefault1(self):
         self.assertMapValue('', 'foo', 'foo-default')
def beast.util.Dict_test.test_Dict.testDefault2 (self)
Definition at line 34 of file Dict_test.py.
References beast.util.Dict_test.test_Dict.assertMapValue().
     def testDefault2(self):
         self.assertMapValue('Darwin.10.8', 'bar', 'bar-default')
def beast.util.Dict_test.test_Dict.testFailure1 (self)
Definition at line 49 of file Dict_test.py.
References beast.util.Dict_test.test_Dict.computeMapValue().
     def testFailure1(self):
         self.assertRaises(KeyError, self.computeMapValue, '', 'baz')
def beast.util.Dict_test.test_Dict.testFailure2 (self)
Definition at line 52 of file Dict_test.py.
References beast.util.Dict_test.test_Dict.computeMapValue().
Referenced by beast.util.Dict_test.test_Dict.testFailure2().
     def testFailure2(self):
         self.assertRaises(KeyError, self.computeMapValue, '', 'bing')
def beast.util.Dict_test.test_Dict.testFailure2 (self)
Definition at line 55 of file Dict_test.py.
References beast.util.Dict_test.test_Dict.computeMapValue(), and beast.util.Dict_test.test_Dict.testFailure2().
     def testFailure2(self):
         self.assertRaises(KeyError, self.computeMapValue, 'Darwin', 'bing')
def beast.util.Dict_test.test_Dict.testPrefix1 (self)
Definition at line 37 of file Dict_test.py.
References beast.util.Dict_test.test_Dict.assertMapValue().
     def testPrefix1(self):
         self.assertMapValue('Darwin', 'foo', 'foo-darwin')
def beast.util.Dict_test.test_Dict.testPrefix2 (self)
Definition at line 40 of file Dict_test.py.
References beast.util.Dict_test.test_Dict.assertMapValue().
     def testPrefix2(self):
         self.assertMapValue('Darwin.10.8', 'foo', 'foo-darwin-10.8')
def beast.util.Dict_test.test_Dict.testPrefix3 (self)
Definition at line 43 of file Dict_test.py.
References beast.util.Dict_test.test_Dict.assertMapValue().
     def testPrefix3(self):
         self.assertMapValue('Darwin', 'baz', 'baz-darwin')
def beast.util.Dict_test.test_Dict.testPrefix4 (self)
Definition at line 46 of file Dict_test.py.
References beast.util.Dict_test.test_Dict.assertMapValue().
     def testPrefix4(self):
         self.assertMapValue('Darwin.10.8', 'bing', 'bing-darwin-10.8')
The documentation for this class was generated from the following file:
rippled/src/beast/python/beast/util/Dict_test.py