rippled: rocksdb::LogFile Class Reference
rocksdb::LogFile Class Reference abstract
#include <transaction_log.h>
Public Member Functions
LogFile ()
virtual ~LogFile ()
virtual std::string PathName () const =0
virtual uint64_t LogNumber () const =0
virtual WalFileType Type () const =0
virtual SequenceNumber StartSequence () const =0
virtual uint64_t SizeFileBytes () const =0
Detailed Description
Definition at line 33 of file transaction_log.h.
Constructor & Destructor Documentation
rocksdb::LogFile::LogFile () inline
Definition at line 35 of file transaction_log.h.
 {}
virtual rocksdb::LogFile::~LogFile () inline virtual
Definition at line 36 of file transaction_log.h.
 {}
Member Function Documentation
virtual uint64_t rocksdb::LogFile::LogNumber () const pure virtual
Implemented in rocksdb::LogFileImpl.
Referenced by rocksdb::TransactionLogIteratorImpl::OpenLogFile(), and rocksdb::LogFileImpl::operator<().
virtual std::string rocksdb::LogFile::PathName () const pure virtual
Implemented in rocksdb::LogFileImpl.
virtual uint64_t rocksdb::LogFile::SizeFileBytes () const pure virtual
Implemented in rocksdb::LogFileImpl.
virtual SequenceNumber rocksdb::LogFile::StartSequence () const pure virtual
Implemented in rocksdb::LogFileImpl.
virtual WalFileType rocksdb::LogFile::Type () const pure virtual
Implemented in rocksdb::LogFileImpl.
Referenced by rocksdb::TransactionLogIteratorImpl::OpenLogFile().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/include/rocksdb/transaction_log.h