rippled: Json::FastWriter Class Reference
Json::FastWriter Class Reference
Outputs a Value in JSON format without formatting (not human friendly).
#include <json_writer.h>
Public Member Functions
FastWriter ()
virtual ~FastWriter ()
void enableYAMLCompatibility ()
virtual std::string write (const Value &root)
Public Member Functions inherited from Json::Writer
virtual ~Writer ()
Private Member Functions
void writeValue (const Value &value)
Private Attributes
std::string document_
bool yamlCompatiblityEnabled_
Detailed Description
Outputs a Value in JSON format without formatting (not human friendly).
The JSON document is written in a single line. It is not intended for 'human' consumption, but may be usefull to support feature such as RPC where bandwith is limited.
See Also
Reader, Value
Definition at line 44 of file json_writer.h.
Constructor & Destructor Documentation
Json::FastWriter::FastWriter ()
Definition at line 184 of file json_writer.cpp.
     : yamlCompatiblityEnabled_ ( false )
 {
 }
virtual Json::FastWriter::~FastWriter () inline virtual
Definition at line 48 of file json_writer.h.
 {}
Member Function Documentation
void Json::FastWriter::enableYAMLCompatibility ()
Definition at line 191 of file json_writer.cpp.
References yamlCompatiblityEnabled_.
 {
     yamlCompatiblityEnabled_ = true;
 }
std::string Json::FastWriter::write (const Value & root) virtual
Implements Json::Writer.
Definition at line 198 of file json_writer.cpp.
References document_, and writeValue().
Referenced by ripple::JSONRPCReply(), ripple::JSONRPCRequest(), ripple::NetworkOPsImp::pubAccountTransaction(), ripple::BookListeners::publish(), ripple::NetworkOPsImp::pubServer(), ripple::NetworkOPsImp::pubValidatedTransaction(), ripple::WSServerHandler< endpoint_type >::send(), and ripple::SerializedObject_test::testParseJSONArray().
 {
     document_ = "";
     writeValue ( root );
     document_ += "\n";
     return document_;
 }
void Json::FastWriter::writeValue (const Value & value) private
Definition at line 208 of file json_writer.cpp.
References Json::arrayValue, Json::Value::asBool(), Json::Value::asCString(), Json::Value::asDouble(), Json::Value::asInt(), Json::Value::asUInt(), Json::booleanValue, document_, Json::Value::getMemberNames(), Json::intValue, name, Json::nullValue, Json::objectValue, Json::realValue, Json::Value::size(), Json::stringValue, Json::Value::type(), Json::uintValue, Json::valueToQuotedString(), Json::valueToString(), and yamlCompatiblityEnabled_.
Referenced by write().
 {
     switch ( value.type () )
     {
     case nullValue:
         document_ += "null";
         break;
     case intValue:
         document_ += valueToString ( value.asInt () );
         break;
     case uintValue:
         document_ += valueToString ( value.asUInt () );
         break;
     case realValue:
         document_ += valueToString ( value.asDouble () );
         break;
     case stringValue:
         document_ += valueToQuotedString ( value.asCString () );
         break;
     case booleanValue:
         document_ += valueToString ( value.asBool () );
         break;
     case arrayValue:
     {
         document_ += "[";
         int size = value.size ();
         for ( int index = 0; index < size; ++index )
         {
             if ( index > 0 )
                 document_ += ",";
             writeValue ( value[index] );
         }
         document_ += "]";
     }
     break;
     case objectValue:
     {
         Value::Members members ( value.getMemberNames () );
         document_ += "{";
         for ( Value::Members::iterator it = members.begin ();
                 it != members.end ();
                 ++it )
         {
             const std::string& name = *it;
             if ( it != members.begin () )
                 document_ += ",";
             document_ += valueToQuotedString ( name.c_str () );
             document_ += yamlCompatiblityEnabled_ ? ": "
                          : ":";
             writeValue ( value[name] );
         }
         document_ += "}";
     }
     break;
     }
 }
Member Data Documentation
std::string Json::FastWriter::document_ private
Definition at line 58 of file json_writer.h.
Referenced by write(), and writeValue().
bool Json::FastWriter::yamlCompatiblityEnabled_ private
Definition at line 59 of file json_writer.h.
Referenced by enableYAMLCompatibility(), and writeValue().
The documentation for this class was generated from the following files:
rippled/src/ripple/json/api/json_writer.h
rippled/src/ripple/json/impl/json_writer.cpp