rippled: beast::FatalError::Reporter Struct Reference
beast::FatalError::Reporter Struct Reference
#include <FatalError.h>
Public Member Functions
virtual ~Reporter ()
virtual void onFatalError (char const *message, char const *stackBacktrace, char const *filePath, int lineNumber)
virtual void reportMessage (String &formattedMessage)
Protected Member Functions
virtual String formatMessage (char const *message, char const *stackBacktrace, char const *filePath, int lineNumber)
virtual String formatFilePath (char const *filePath)
Detailed Description
Definition at line 40 of file FatalError.h.
Constructor & Destructor Documentation
virtual beast::FatalError::Reporter::~Reporter () inline virtual
Definition at line 42 of file FatalError.h.
 { }
Member Function Documentation
String beast::FatalError::Reporter::formatFilePath (char const * filePath) protected virtual
Call to reformat the file path.
Usually the file is a full path, which we really don't care to see and can also be a security hole.
The default implementation removes most of the useless directory components from the front.
You can override this to do a custom format on the file path.
Definition at line 66 of file FatalError.cpp.
 {
     return filePath;
 }
String beast::FatalError::Reporter::formatMessage (char const * message, char const * stackBacktrace, char const * filePath, int lineNumber) protected virtual
Called to format the message.
The default implementation calls formatFilePath to produce a formatted file name, and then creates a suitable string containing all of the information.
You can override this function to format your own messages.
Parameters
message The message from the report.
stackBacktrace The stack backtrace from the report.
filePath The file path from the report.
lineNumber The line number from the report
Definition at line 41 of file FatalError.cpp.
References beast::newLine, and beast::String::preallocateBytes().
Referenced by onFatalError().
 {
     String formattedMessage;
     formattedMessage.preallocateBytes (16 * 1024);
     formattedMessage << message;
     if (filePath != nullptr && filePath [0] != 0)
     {
         formattedMessage << ", in " << formatFilePath (filePath)
                          << " line " << String (lineNumber);
     }
     formattedMessage << newLine;
     if (stackBacktrace != nullptr && stackBacktrace [0] != 0)
     {
         formattedMessage << "Stack:" << newLine;
         formattedMessage << stackBacktrace;
     }
     return formattedMessage;
 }
void beast::FatalError::Reporter::onFatalError (char const * message, char const * stackBacktrace, char const * filePath, int lineNumber) virtual
Called when a fatal error is raised.
Because the program is likely in an inconsistent state, it is a good idea to do as little as possible from within this function. It will be called from the thread that raised the fatal error.
The default implementation of this function first calls formatMessage to produce the string, then calls reportMessage to report the results.
You can override this to perform custom formatting.
Note
filePath may be a zero length string if identifying information was stripped from the executable for security.
stackBacktrace will be a string with zero characters for platforms for which which don't support stack crawls, or when symbolic information is missing from the executable.
Parameters
message The error message.
stackBackTrace The stack of the thread that raised the error.
filePath A full or partial path to the source file that raised the error.
lineNumber The line number in the source file.
Definition at line 27 of file FatalError.cpp.
References formatMessage(), and reportMessage().
Referenced by beast::FatalError::FatalError().
 {
     String formattedMessage = formatMessage (
         message, stackBacktrace, filePath, lineNumber);
     reportMessage (formattedMessage);
 }
void beast::FatalError::Reporter::reportMessage (String & formattedMessage) virtual
Called to report the message.
The default implementation simply writes this to standard error. You can override this to perform additional things like logging to a file or sending the message to another process.
Parameters
formattedMessage The message to report.
Reimplemented in ripple::FatalErrorReporter.
Definition at line 36 of file FatalError.cpp.
References beast::String::toRawUTF8().
Referenced by onFatalError().
 {
     std::cerr << formattedMessage.toRawUTF8 ();
 }
The documentation for this struct was generated from the following files:
rippled/src/beast/modules/beast_core/diagnostic/FatalError.h
rippled/src/beast/modules/beast_core/diagnostic/FatalError.cpp