rippled: rocksdb::InternalKey Class Reference
rocksdb::InternalKey Class Reference
#include <dbformat.h>
Public Member Functions
InternalKey ()
InternalKey (const Slice &user_key, SequenceNumber s, ValueType t)
void DecodeFrom (const Slice &s)
Slice Encode () const
Slice user_key () const
void SetFrom (const ParsedInternalKey &p)
void Clear ()
std::string DebugString (bool hex=false) const
Private Attributes
std::string rep_
Detailed Description
Definition at line 126 of file dbformat.h.
Constructor & Destructor Documentation
rocksdb::InternalKey::InternalKey () inline
Definition at line 130 of file dbformat.h.
 { }   // Leave rep_ as empty to indicate it is invalid
rocksdb::InternalKey::InternalKey (const Slice & user_key, SequenceNumber s, ValueType t) inline
Definition at line 131 of file dbformat.h.
References rocksdb::AppendInternalKey(), and rep_.
{
     AppendInternalKey(&rep_, ParsedInternalKey(user_key, s, t));
   }
Member Function Documentation
void rocksdb::InternalKey::Clear () inline
Definition at line 148 of file dbformat.h.
References rep_.
Referenced by rocksdb::VersionSet::GetRange(), and rocksdb::DBImpl::OpenCompactionOutputFile().
 { rep_.clear(); }
std::string rocksdb::InternalKey::DebugString (bool hex = false) const
Definition at line 40 of file dbformat.cc.
References rocksdb::ParsedInternalKey::DebugString(), rocksdb::EscapeString(), rocksdb::ParseInternalKey(), and rep_.
Referenced by rocksdb::DBImpl::BackgroundCompaction(), rocksdb::VersionSet::Builder::CheckConsistency(), rocksdb::VersionEdit::DebugString(), and rocksdb::VersionSet::SetupOtherInputs().
{
   std::string result;
   ParsedInternalKey parsed;
   if (ParseInternalKey(rep_, &parsed)) {
     result = parsed.DebugString(hex);
   } else {
     result = "(bad)";
     result.append(EscapeString(rep_));
   }
   return result;
 }
void rocksdb::InternalKey::DecodeFrom (const Slice & s) inline
Definition at line 135 of file dbformat.h.
References rocksdb::Slice::data(), rep_, and rocksdb::Slice::size().
Referenced by rocksdb::BuildTable(), rocksdb::DBImpl::DoCompactionWork(), rocksdb::GetInternalKey(), and rocksdb::VersionSet::WriteSnapshot().
 { rep_.assign(s.data(), s.size()); }
Slice rocksdb::InternalKey::Encode () const inline
Definition at line 136 of file dbformat.h.
References rep_.
Referenced by rocksdb::FilterBlockBuilder::AddKey(), rocksdb::DBTest::AllEntriesFor(), rocksdb::VersionSet::ApproximateOffsetOf(), rocksdb::InternalKeyComparator::Compare(), rocksdb::InternalDumpCommand::DoCommand(), rocksdb::VersionEdit::EncodeTo(), rocksdb::FindFileTest::Find(), rocksdb::FindFile(), rocksdb::MakeKey(), rocksdb::Version::NewConcatenatingIterator(), rocksdb::BlockBasedTable::NewIterator(), rocksdb::SstFileReader::ReadSequential(), rocksdb::VersionSet::SetupOtherInputs(), rocksdb::SomeFileOverlapsRange(), and rocksdb::TEST().
{
     assert(!rep_.empty());
     return rep_;
   }
void rocksdb::InternalKey::SetFrom (const ParsedInternalKey & p) inline
Definition at line 143 of file dbformat.h.
References rocksdb::AppendInternalKey(), and rep_.
{
     rep_.clear();
     AppendInternalKey(&rep_, p);
   }
Slice rocksdb::InternalKey::user_key () const inline
Definition at line 141 of file dbformat.h.
References rocksdb::ExtractUserKey(), and rep_.
Referenced by rocksdb::AfterFile(), rocksdb::BeforeFile(), rocksdb::Version::ExtendOverlappingInputs(), rocksdb::Version::Get(), rocksdb::Version::GetOverlappingInputs(), rocksdb::Version::GetOverlappingInputsBinarySearch(), rocksdb::Compaction::IsBaseLevelForKey(), and rocksdb::DBImpl::WriteLevel0Table().
 { return ExtractUserKey(rep_); }
Member Data Documentation
std::string rocksdb::InternalKey::rep_ private
Definition at line 128 of file dbformat.h.
Referenced by Clear(), DebugString(), DecodeFrom(), Encode(), InternalKey(), SetFrom(), and user_key().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/db/dbformat.h
rippled/src/ripple/rocksdb/rocksdb/db/dbformat.cc