rippled: ripple::Overlay Class Reference
ripple::Overlay Class Reference abstract
#include <Overlay.h>
Public Types
typedef std::vector< Peer::ptr > PeerSequence
Public Member Functions
virtual ~Overlay ()=default
virtual void connect (beast::IP::Endpoint const &address)=0
virtual void onPeerActivated (Peer::ptr const &peer)=0
virtual void onPeerDisconnect (Peer::ptr const &peer)=0
virtual std::size_t size ()=0
virtual Json::Value json ()=0
virtual PeerSequence getActivePeers ()=0
virtual Peer::ptr findPeerByShortID (Peer::ShortId const &id)=0
template<typename Function >
std::enable_if_t
< !std::is_void< typename
Function::return_type >::value,
typename Function::return_type > foreach (Function f)
template<class Function >
std::enable_if_t< std::is_void
< typename
Function::return_type >::value,
typename Function::return_type > foreach (Function f)
virtual void remove (PeerFinder::Slot::ptr const &slot)=0
Public Member Functions inherited from beast::Stoppable
Stoppable (char const *name, Stoppable &parent)
virtual ~Stoppable ()
bool isStopping () const
bool isStopped () const
bool areChildrenStopped () const
void stopped ()
virtual void onPrepare ()
virtual void onStart ()
virtual void onStop ()
virtual void onChildrenStopped ()
Public Member Functions inherited from beast::PropertyStream::Source
Source (std::string const &name)
~Source ()
std::string const & name () const
void add (Source &source)
template<class Derived >
Derived * add (Derived *child)
void remove (Source &child)
void removeAll ()
void write_one (PropertyStream &stream)
void write (PropertyStream &stream)
void write (PropertyStream &stream, std::string const &path)
std::pair< Source *, bool > find (std::string path)
Source * find_one_deep (std::string const &name)
PropertyStream::Source * find_path (std::string path)
PropertyStream::Source * find_one (std::string const &name)
virtual void onWrite (Map &)
Protected Member Functions
Overlay (Stoppable &parent)
Protected Member Functions inherited from beast::Stoppable
Stoppable (char const *name, RootStoppable &root)
Additional Inherited Members
Static Public Member Functions inherited from beast::PropertyStream::Source
static bool peel_leading_slash (std::string *path)
static bool peel_trailing_slashstar (std::string *path)
static std::string peel_name (std::string *path)
Protected Attributes inherited from beast::Stoppable
char const * m_name
RootStoppable & m_root
Child m_child
Atomic< int > m_started
bool volatile m_stopped
bool volatile m_childrenStopped
Children m_children
WaitableEvent m_stoppedEvent
Detailed Description
Manages the set of connected peers.
Definition at line 36 of file Overlay.h.
Member Typedef Documentation
typedef std::vector<Peer::ptr> ripple::Overlay::PeerSequence
Definition at line 53 of file Overlay.h.
Constructor & Destructor Documentation
ripple::Overlay::Overlay (Stoppable & parent) inline protected
Definition at line 45 of file Overlay.h.
         : Stoppable ("Overlay", parent)
         , beast::PropertyStream::Source ("peers")
     {
     }
virtual ripple::Overlay::~Overlay () virtual default
Member Function Documentation
virtual void ripple::Overlay::connect (beast::IP::Endpoint const & address) pure virtual
Implemented in ripple::OverlayImpl.
Referenced by ripple::RPCHandler::doConnect().
virtual Peer::ptr ripple::Overlay::findPeerByShortID (Peer::ShortId const & id) pure virtual
Implemented in ripple::OverlayImpl.
template<typename Function > std::enable_if_t< ! std::is_void <typename Function::return_type>::value, typename Function::return_type > ripple::Overlay::foreach (Function f) inline
Visit every active peer and return a value The functor must:
Be callable as: void operator()(Peer::ptr const& peer);
Must have the following typedef: typedef void return_type;
Be callable as: Function::return_type operator()() const;
Parameters
f the functor to call with every peer
Returns
f()
Note
The functor is passed by value!
Definition at line 96 of file Overlay.h.
References ripple::f, and getActivePeers().
Referenced by ripple::LedgerConsensusImp::accept(), ripple::LedgerConsensusImp::addDisputedTransaction(), ripple::PeerImp::checkPropose(), ripple::PeerImp::checkValidation(), ripple::PeerImp::getLedger(), ripple::LedgerConsensusImp::playbackProposals(), ripple::NetworkOPsImp::processClusterTimer(), ripple::NetworkOPsImp::processTransactionCb(), ripple::NetworkOPsImp::processTrustedProposal(), ripple::LedgerConsensusImp::propose(), ripple::NetworkOPsImp::runTransactionQueue(), ripple::LedgerConsensusImp::sendHaveTxSet(), ripple::LedgerConsensusImp::startAcquiring(), ripple::LedgerConsensusImp::statusChange(), and ripple::NetworkOPsImp::switchLastClosedLedger().
     {
         PeerSequence peers (getActivePeers());
         for(PeerSequence::const_iterator i = peers.begin(); i != peers.end(); ++i)
             f (*i);
         return f();
     }
template<class Function > std::enable_if_t< std::is_void <typename Function::return_type>::value, typename Function::return_type > ripple::Overlay::foreach (Function f) inline
Visit every active peer The visitor functor must:
Be callable as: void operator()(Peer::ptr const& peer);
Must have the following typedef: typedef void return_type;
Parameters
f the functor to call with every peer
Definition at line 120 of file Overlay.h.
References getActivePeers().
     {
         PeerSequence peers (getActivePeers());
         for(PeerSequence::const_iterator i = peers.begin(); i != peers.end(); ++i)
             f (*i);
     }
virtual PeerSequence ripple::Overlay::getActivePeers () pure virtual
Implemented in ripple::OverlayImpl.
Referenced by ripple::InboundLedger::addPeers(), ripple::NetworkOPsImp::endConsensus(), foreach(), ripple::LedgerMasterImp::getFetchPack(), ripple::NetworkOPsImp::haveConsensusObject(), and ripple::TransactionAcquire::onTimer().
virtual Json::Value ripple::Overlay::json () pure virtual
Implemented in ripple::OverlayImpl.
Referenced by ripple::RPCHandler::doPeers().
virtual void ripple::Overlay::onPeerActivated (Peer::ptr const & peer) pure virtual
Implemented in ripple::OverlayImpl.
virtual void ripple::Overlay::onPeerDisconnect (Peer::ptr const & peer) pure virtual
Implemented in ripple::OverlayImpl.
virtual void ripple::Overlay::remove (PeerFinder::Slot::ptr const & slot) pure virtual
Implemented in ripple::OverlayImpl.
virtual std::size_t ripple::Overlay::size () pure virtual
Implemented in ripple::OverlayImpl.
Referenced by ripple::NetworkOPsImp::processHeartbeatTimer().
The documentation for this class was generated from the following file:
rippled/src/ripple_overlay/api/Overlay.h