rippled: ripple::ConsensusTransSetSF Class Reference
ripple::ConsensusTransSetSF Class Reference
#include <SHAMapSyncFilters.h>
Public Types
typedef TaggedCache< uint256,
Blob > NodeCache
Public Member Functions
ConsensusTransSetSF (NodeCache &nodeCache)
void gotNode (bool fromFilter, SHAMapNode const &id, uint256 const &nodeHash, Blob &nodeData, SHAMapTreeNode::TNType)
bool haveNode (SHAMapNode const &id, uint256 const &nodeHash, Blob &nodeData)
Public Member Functions inherited from ripple::SHAMapSyncFilter
virtual ~SHAMapSyncFilter ()
Private Attributes
NodeCache & m_nodeCache
Detailed Description
Definition at line 30 of file SHAMapSyncFilters.h.
Member Typedef Documentation
typedef TaggedCache<uint256, Blob> ripple::ConsensusTransSetSF::NodeCache
Definition at line 33 of file SHAMapSyncFilters.h.
Constructor & Destructor Documentation
ripple::ConsensusTransSetSF::ConsensusTransSetSF (NodeCache & nodeCache)
Definition at line 22 of file SHAMapSyncFilters.cpp.
     : m_nodeCache (nodeCache)
 {
 }
Member Function Documentation
void ripple::ConsensusTransSetSF::gotNode (bool fromFilter, SHAMapNode const & id, uint256 const & nodeHash, Blob & nodeData, SHAMapTreeNode::TNType type) virtual
Implements ripple::SHAMapSyncFilter.
Definition at line 27 of file SHAMapSyncFilters.cpp.
References ripple::JobQueue::addJob(), BIND_TYPE, ripple::getApp(), ripple::Application::getJobQueue(), ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::insert(), ripple::jtTRANSACTION, ripple::lsDEBUG, ripple::lsWARNING, m_nodeCache, P_1, ripple::NetworkOPs::submitTransaction(), ripple::SHAMapTreeNode::tnTRANSACTION_NM, and WriteLog.
 {
     if (fromFilter)
         return;
     m_nodeCache.insert (nodeHash, nodeData);
     if ((type == SHAMapTreeNode::tnTRANSACTION_NM) && (nodeData.size () > 16))
     {
         // this is a transaction, and we didn't have it
         WriteLog (lsDEBUG, TransactionAcquire) << "Node on our acquiring TX set is TXN we may not have";
         try
         {
             Serializer s (nodeData.begin () + 4, nodeData.end ()); // skip prefix
             SerializerIterator sit (s);
             SerializedTransaction::pointer stx = boost::make_shared<SerializedTransaction> (boost::ref (sit));
             assert (stx->getTransactionID () == nodeHash);
             getApp().getJobQueue ().addJob (jtTRANSACTION, "TXS->TXN",
                                            BIND_TYPE (&NetworkOPs::submitTransaction, &getApp().getOPs (), P_1, stx, NetworkOPs::stCallback ()));
         }
         catch (...)
         {
             WriteLog (lsWARNING, TransactionAcquire) << "Fetched invalid transaction in proposed set";
         }
     }
 }
bool ripple::ConsensusTransSetSF::haveNode (SHAMapNode const & id, uint256 const & nodeHash, Blob & nodeData) virtual
Implements ripple::SHAMapSyncFilter.
Definition at line 56 of file SHAMapSyncFilters.cpp.
References ripple::Serializer::add32(), ripple::TransactionMaster::fetch(), ripple::getApp(), ripple::Application::getMasterTransaction(), ripple::Serializer::getSHA512Half(), ripple::lsDEBUG, m_nodeCache, ripple::Serializer::peekData(), ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::retrieve(), ripple::HashPrefix::transactionID, and WriteLog.
 {
     if (m_nodeCache.retrieve (nodeHash, nodeData))
         return true;
     // VFALCO TODO Use a dependency injection here
     Transaction::pointer txn = getApp().getMasterTransaction().fetch(nodeHash, false);
     if (txn)
     {
         // this is a transaction, and we have it
         WriteLog (lsDEBUG, TransactionAcquire) << "Node in our acquiring TX set is TXN we have";
         Serializer s;
         s.add32 (HashPrefix::transactionID);
         txn->getSTransaction ()->add (s, true);
         assert (s.getSHA512Half () == nodeHash);
         nodeData = s.peekData ();
         return true;
     }
     return false;
 }
Member Data Documentation
NodeCache& ripple::ConsensusTransSetSF::m_nodeCache private
Definition at line 50 of file SHAMapSyncFilters.h.
Referenced by gotNode(), and haveNode().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/shamap/SHAMapSyncFilters.h
rippled/src/ripple_app/shamap/SHAMapSyncFilters.cpp