rippled: beast::detail::UntrackedScopedTryLock< Mutex > Class Template Reference
beast::detail::UntrackedScopedTryLock< Mutex > Class Template Reference
#include <ScopedLock.h>
Public Member Functions
UntrackedScopedTryLock (Mutex const &mutex, char const *, int) noexcept
~UntrackedScopedTryLock () noexcept
bool owns_lock () const noexcept
bool try_lock () noexcept
bool try_lock (char const *, int) noexcept
void unlock () noexcept
Private Attributes
Mutex const & m_mutex
int m_lock_count
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
template<typename Mutex>
class beast::detail::UntrackedScopedTryLock< Mutex >
Definition at line 181 of file ScopedLock.h.
Constructor & Destructor Documentation
template<typename Mutex > beast::detail::UntrackedScopedTryLock< Mutex >::UntrackedScopedTryLock (Mutex const & mutex, char const * , int) inline explicit noexcept
Definition at line 184 of file ScopedLock.h.
References beast::detail::UntrackedScopedTryLock< Mutex >::try_lock().
         : m_mutex (mutex)
         , m_lock_count (0)
     {
         try_lock ();
     }
template<typename Mutex > beast::detail::UntrackedScopedTryLock< Mutex >::~UntrackedScopedTryLock () inline noexcept
Definition at line 192 of file ScopedLock.h.
References beast::detail::UntrackedScopedTryLock< Mutex >::m_lock_count, and beast::detail::UntrackedScopedTryLock< Mutex >::unlock().
     {
         if (m_lock_count > 0)
         unlock ();
     }
Member Function Documentation
template<typename Mutex > bool beast::detail::UntrackedScopedTryLock< Mutex >::owns_lock () const inline noexcept
Definition at line 198 of file ScopedLock.h.
References beast::detail::UntrackedScopedTryLock< Mutex >::m_lock_count.
     {
         return m_lock_count > 0;
     }
template<typename Mutex > bool beast::detail::UntrackedScopedTryLock< Mutex >::try_lock () inline noexcept
Definition at line 203 of file ScopedLock.h.
References beast::detail::UntrackedScopedTryLock< Mutex >::m_lock_count, and beast::detail::UntrackedScopedTryLock< Mutex >::m_mutex.
Referenced by beast::detail::UntrackedScopedTryLock< Mutex >::try_lock(), and beast::detail::UntrackedScopedTryLock< Mutex >::UntrackedScopedTryLock().
     {
         bool const success = m_mutex.try_lock ();
         if (success)
             ++m_lock_count;
         return success;
     }
template<typename Mutex > bool beast::detail::UntrackedScopedTryLock< Mutex >::try_lock (char const * , int) inline noexcept
Definition at line 211 of file ScopedLock.h.
References beast::detail::UntrackedScopedTryLock< Mutex >::try_lock().
     {
         return try_lock ();
     }
template<typename Mutex > void beast::detail::UntrackedScopedTryLock< Mutex >::unlock () inline noexcept
Definition at line 216 of file ScopedLock.h.
References beast::detail::UntrackedScopedTryLock< Mutex >::m_lock_count, and beast::detail::UntrackedScopedTryLock< Mutex >::m_mutex.
Referenced by beast::detail::UntrackedScopedTryLock< Mutex >::~UntrackedScopedTryLock().
     {
         m_mutex.unlock ();
         --m_lock_count;
     }
Member Data Documentation
template<typename Mutex > int beast::detail::UntrackedScopedTryLock< Mutex >::m_lock_count private
Definition at line 224 of file ScopedLock.h.
Referenced by beast::detail::UntrackedScopedTryLock< Mutex >::owns_lock(), beast::detail::UntrackedScopedTryLock< Mutex >::try_lock(), beast::detail::UntrackedScopedTryLock< Mutex >::unlock(), and beast::detail::UntrackedScopedTryLock< Mutex >::~UntrackedScopedTryLock().
template<typename Mutex > Mutex const& beast::detail::UntrackedScopedTryLock< Mutex >::m_mutex private
Definition at line 223 of file ScopedLock.h.
Referenced by beast::detail::UntrackedScopedTryLock< Mutex >::try_lock(), and beast::detail::UntrackedScopedTryLock< Mutex >::unlock().
The documentation for this class was generated from the following file:
rippled/src/beast/modules/beast_core/thread/detail/ScopedLock.h