rippled: ripple::Peer Class Reference
ripple::Peer Class Reference abstract
#include <Peer.h>
Public Types
typedef boost::shared_ptr< Peer > ptr
typedef std::uint32_t ShortId
Public Member Functions
virtual void sendPacket (const Message::pointer &packet, bool onStrand)=0
virtual beast::IP::Endpoint getRemoteAddress () const =0
virtual void charge (Resource::Charge const &fee)=0
virtual ShortId getShortId () const =0
virtual const RippleAddress & getNodePublic () const =0
virtual Json::Value json ()=0
virtual bool isInCluster () const =0
virtual std::string getClusterNodeName () const =0
virtual uint256 const & getClosedLedgerHash () const =0
virtual bool hasLedger (uint256 const &hash, std::uint32_t seq) const =0
virtual void ledgerRange (std::uint32_t &minSeq, std::uint32_t &maxSeq) const =0
virtual bool hasTxSet (uint256 const &hash) const =0
virtual void cycleStatus ()=0
virtual bool supportsVersion (int version)=0
virtual bool hasRange (std::uint32_t uMin, std::uint32_t uMax)=0
Detailed Description
Represents a peer connection in the overlay.
Definition at line 38 of file Peer.h.
Member Typedef Documentation
typedef boost::shared_ptr<Peer> ripple::Peer::ptr
Definition at line 41 of file Peer.h.
typedef std::uint32_t ripple::Peer::ShortId
Uniquely identifies a particular connection of a peer.
Definition at line 44 of file Peer.h.
Member Function Documentation
virtual void ripple::Peer::charge (Resource::Charge const & fee) pure virtual
Adjust this peer's load balance based on the type of load imposed.
Implemented in ripple::PeerImp.
virtual void ripple::Peer::cycleStatus () pure virtual
Implemented in ripple::PeerImp.
virtual uint256 const& ripple::Peer::getClosedLedgerHash () const pure virtual
Implemented in ripple::PeerImp.
virtual std::string ripple::Peer::getClusterNodeName () const pure virtual
Implemented in ripple::PeerImp.
Referenced by ripple::to_string().
virtual const RippleAddress& ripple::Peer::getNodePublic () const pure virtual
Implemented in ripple::PeerImp.
virtual beast::IP::Endpoint ripple::Peer::getRemoteAddress () const pure virtual
Implemented in ripple::PeerImp.
Referenced by ripple::to_string().
virtual ShortId ripple::Peer::getShortId () const pure virtual
Implemented in ripple::PeerImp.
virtual bool ripple::Peer::hasLedger (uint256 const & hash, std::uint32_t seq) const pure virtual
Implemented in ripple::PeerImp.
virtual bool ripple::Peer::hasRange (std::uint32_t uMin, std::uint32_t uMax) pure virtual
Implemented in ripple::PeerImp.
virtual bool ripple::Peer::hasTxSet (uint256 const & hash) const pure virtual
Implemented in ripple::PeerImp.
virtual bool ripple::Peer::isInCluster () const pure virtual
Implemented in ripple::PeerImp.
Referenced by ripple::to_string().
virtual Json::Value ripple::Peer::json () pure virtual
Implemented in ripple::PeerImp.
virtual void ripple::Peer::ledgerRange (std::uint32_t & minSeq, std::uint32_t & maxSeq) const pure virtual
Implemented in ripple::PeerImp.
virtual void ripple::Peer::sendPacket (const Message::pointer & packet, bool onStrand) pure virtual
Implemented in ripple::PeerImp.
Referenced by ripple::PeerImp::sendPacket().
virtual bool ripple::Peer::supportsVersion (int version) pure virtual
Implemented in ripple::PeerImp.
The documentation for this class was generated from the following file:
rippled/src/ripple_overlay/api/Peer.h