rippled: rocksdb::DBWithTTL Class Reference
rocksdb::DBWithTTL Class Reference
#include <db_ttl.h>
Public Member Functions
DBWithTTL (const int32_t ttl, const Options &options, const std::string &dbname, Status &st, bool read_only)
virtual ~DBWithTTL ()
virtual Status Put (const WriteOptions &o, const Slice &key, const Slice &val)
virtual Status Get (const ReadOptions &options, const Slice &key, std::string *value)
virtual std::vector< Status > MultiGet (const ReadOptions &options, const std::vector< Slice > &keys, std::vector< std::string > *values)
virtual bool KeyMayExist (const ReadOptions &options, const Slice &key, std::string *value, bool *value_found=nullptr) override
virtual Status Delete (const WriteOptions &wopts, const Slice &key)
virtual Status Merge (const WriteOptions &options, const Slice &key, const Slice &value)
virtual Status Write (const WriteOptions &opts, WriteBatch *updates)
virtual Iterator * NewIterator (const ReadOptions &opts)
virtual const Snapshot * GetSnapshot ()
virtual void ReleaseSnapshot (const Snapshot *snapshot)
virtual bool GetProperty (const Slice &property, std::string *value)
virtual void GetApproximateSizes (const Range *r, int n, uint64_t *sizes)
virtual void CompactRange (const Slice *begin, const Slice *end, bool reduce_level=false, int target_level=-1)
virtual int NumberLevels ()
virtual int MaxMemCompactionLevel ()
virtual int Level0StopWriteTrigger ()
virtual Status Flush (const FlushOptions &fopts)
virtual Status DisableFileDeletions ()
virtual Status EnableFileDeletions ()
virtual Status GetLiveFiles (std::vector< std::string > &vec, uint64_t *mfs, bool flush_memtable=true)
virtual Status GetSortedWalFiles (VectorLogPtr &files)
virtual Status DeleteFile (std::string name)
virtual SequenceNumber GetLatestSequenceNumber () const
virtual Status GetUpdatesSince (SequenceNumber seq_number, unique_ptr< TransactionLogIterator > *iter)
void TEST_Destroy_DBWithTtl ()
virtual DB * GetRawDB ()
Public Member Functions inherited from rocksdb::StackableDB
StackableDB (StackableDB *sdb)
Public Member Functions inherited from rocksdb::DB
DB ()
virtual ~DB ()
virtual void GetLiveFilesMetaData (std::vector< LiveFileMetaData > *metadata)
Static Public Member Functions
static bool IsStale (const Slice &value, int32_t ttl)
static Status AppendTS (const Slice &val, std::string &val_with_ts)
static Status SanityCheckTimestamp (const Slice &str)
static Status StripTS (std::string *str)
static Status GetCurrentTime (int64_t &curtime)
Static Public Member Functions inherited from rocksdb::StackableDB
static StackableDB * DBToStackableDB (DB *db)
Static Public Member Functions inherited from rocksdb::DB
static Status Open (const Options &options, const std::string &name, DB **dbptr)
static Status OpenForReadOnly (const Options &options, const std::string &name, DB **dbptr, bool error_if_log_file_exist=false)
Static Public Attributes
static const uint32_t kTSLength = sizeof(int32_t)
static const int32_t kMinTimestamp = 1368146402
static const int32_t kMaxTimestamp = 2147483647
Private Attributes
DB * db_
unique_ptr< CompactionFilter > ttl_comp_filter_
Additional Inherited Members
Protected Attributes inherited from rocksdb::StackableDB
StackableDB * sdb_
Detailed Description
Definition at line 15 of file db_ttl.h.
Constructor & Destructor Documentation
rocksdb::DBWithTTL::DBWithTTL (const int32_t ttl, const Options & options, const std::string & dbname, Status & st, bool read_only)
Definition at line 14 of file db_ttl.cc.
References rocksdb::Options::compaction_filter, rocksdb::Options::compaction_filter_factory, db_, rocksdb::Options::merge_operator, rocksdb::DB::Open(), rocksdb::DB::OpenForReadOnly(), and ttl_comp_filter_.
     : StackableDB(nullptr) {
   Options options_to_open = options;
   if (options.compaction_filter) {
     ttl_comp_filter_.reset(
         new TtlCompactionFilter(ttl, options.compaction_filter));
     options_to_open.compaction_filter = ttl_comp_filter_.get();
   } else {
     options_to_open.compaction_filter_factory =
       std::shared_ptr<CompactionFilterFactory>(
           new TtlCompactionFilterFactory(
             ttl, options.compaction_filter_factory));
   }
   if (options.merge_operator) {
     options_to_open.merge_operator.reset(
       new TtlMergeOperator(options.merge_operator));
   }
   if (read_only) {
     st = DB::OpenForReadOnly(options_to_open, dbname, &db_);
   } else {
     st = DB::Open(options_to_open, dbname, &db_);
   }
 }
rocksdb::DBWithTTL::~DBWithTTL () virtual
Definition at line 45 of file db_ttl.cc.
References db_.
                       {
   delete db_;
 }
Member Function Documentation
Status rocksdb::DBWithTTL::AppendTS (const Slice & val, std::string & val_with_ts) static
Definition at line 70 of file db_ttl.cc.
References rocksdb::Slice::data(), rocksdb::EncodeFixed32(), GetCurrentTime(), kTSLength, rocksdb::Status::ok(), and rocksdb::Slice::size().
Referenced by Write().
{
   val_with_ts.reserve(kTSLength + val.size());
   char ts_string[kTSLength];
   int64_t curtime;
   Status st = GetCurrentTime(curtime);
   if (!st.ok()) {
     return st;
   }
   EncodeFixed32(ts_string, (int32_t)curtime);
   val_with_ts.append(val.data(), val.size());
   val_with_ts.append(ts_string, kTSLength);
   return st;
 }
void rocksdb::DBWithTTL::CompactRange (const Slice * begin, const Slice * end, bool reduce_level = false, int target_level = -1) virtual
Reimplemented from rocksdb::StackableDB.
Definition at line 240 of file db_ttl.cc.
References rocksdb::DB::CompactRange(), and db_.
{
   db_->CompactRange(begin, end, reduce_level, target_level);
 }
Status rocksdb::DBWithTTL::Delete (const WriteOptions & wopts, const Slice & key) virtual
Reimplemented from rocksdb::StackableDB.
Definition at line 169 of file db_ttl.cc.
References db_, and rocksdb::DB::Delete().
Referenced by Write().
{
   return db_->Delete(wopts, key);
 }
Status rocksdb::DBWithTTL::DeleteFile (std::string name) virtual
Reimplemented from rocksdb::StackableDB.
Definition at line 282 of file db_ttl.cc.
References db_, and rocksdb::DB::DeleteFile().
{
   return db_->DeleteFile(name);
 }
Status rocksdb::DBWithTTL::DisableFileDeletions () virtual
Reimplemented from rocksdb::StackableDB.
Definition at line 261 of file db_ttl.cc.
References db_, and rocksdb::DB::DisableFileDeletions().
{
   return db_->DisableFileDeletions();
 }
Status rocksdb::DBWithTTL::EnableFileDeletions () virtual
Reimplemented from rocksdb::StackableDB.
Definition at line 265 of file db_ttl.cc.
References db_, and rocksdb::DB::EnableFileDeletions().
{
   return db_->EnableFileDeletions();
 }
Status rocksdb::DBWithTTL::Flush (const FlushOptions & fopts) virtual
Reimplemented from rocksdb::StackableDB.
Definition at line 257 of file db_ttl.cc.
References db_, and rocksdb::DB::Flush().
{
   return db_->Flush(fopts);
 }
Status rocksdb::DBWithTTL::Get (const ReadOptions & options, const Slice & key, std::string * value) virtual
Reimplemented from rocksdb::StackableDB.
Definition at line 134 of file db_ttl.cc.
References db_, rocksdb::DB::Get(), rocksdb::Status::ok(), SanityCheckTimestamp(), and StripTS().
{
   Status st = db_->Get(options, key, value);
   if (!st.ok()) {
     return st;
   }
   st = SanityCheckTimestamp(*value);
   if (!st.ok()) {
     return st;
   }
   return StripTS(value);
 }
void rocksdb::DBWithTTL::GetApproximateSizes (const Range * r, int n, uint64_t * sizes) virtual
Reimplemented from rocksdb::StackableDB.
Definition at line 236 of file db_ttl.cc.
References db_, and rocksdb::DB::GetApproximateSizes().
{
   db_->GetApproximateSizes(r, n, sizes);
 }
Status rocksdb::DBWithTTL::GetCurrentTime (int64_t & curtime) static
Definition at line 64 of file db_ttl.cc.
References rocksdb::Env::Default(), and rocksdb::Env::GetCurrentTime().
Referenced by AppendTS(), rocksdb::TtlMergeOperator::FullMerge(), IsStale(), and rocksdb::TtlMergeOperator::PartialMerge().
{
   return Env::Default()->GetCurrentTime(&curtime);
 }
SequenceNumber rocksdb::DBWithTTL::GetLatestSequenceNumber () const virtual
Reimplemented from rocksdb::StackableDB.
Definition at line 274 of file db_ttl.cc.
References db_, and rocksdb::DB::GetLatestSequenceNumber().
{
   return db_->GetLatestSequenceNumber();
 }
Status rocksdb::DBWithTTL::GetLiveFiles (std::vector< std::string > & vec, uint64_t * mfs, bool flush_memtable = true) virtual
Reimplemented from rocksdb::StackableDB.
Definition at line 269 of file db_ttl.cc.
References db_, and rocksdb::DB::GetLiveFiles().
{
   return db_->GetLiveFiles(vec, mfs, flush_memtable);
 }
bool rocksdb::DBWithTTL::GetProperty (const Slice & property, std::string * value) virtual
Reimplemented from rocksdb::StackableDB.
Definition at line 232 of file db_ttl.cc.
References db_, and rocksdb::DB::GetProperty().
{
   return db_->GetProperty(property, value);
 }
virtual DB* rocksdb::DBWithTTL::GetRawDB () inline virtual
Reimplemented from rocksdb::StackableDB.
Definition at line 91 of file db_ttl.h.
References db_.
{
     return db_;
   }
const Snapshot * rocksdb::DBWithTTL::GetSnapshot () virtual
Reimplemented from rocksdb::StackableDB.
Definition at line 224 of file db_ttl.cc.
References db_, and rocksdb::DB::GetSnapshot().
{
   return db_->GetSnapshot();
 }
Status rocksdb::DBWithTTL::GetSortedWalFiles (VectorLogPtr & files) virtual
Reimplemented from rocksdb::StackableDB.
Definition at line 278 of file db_ttl.cc.
References db_, and rocksdb::DB::GetSortedWalFiles().
{
   return db_->GetSortedWalFiles(files);
 }
Status rocksdb::DBWithTTL::GetUpdatesSince (SequenceNumber seq_number, unique_ptr< TransactionLogIterator > * iter) virtual
Reimplemented from rocksdb::StackableDB.
Definition at line 286 of file db_ttl.cc.
References db_, and rocksdb::DB::GetUpdatesSince().
{
   return db_->GetUpdatesSince(seq_number, iter);
 }
bool rocksdb::DBWithTTL::IsStale (const Slice & value, int32_t ttl) static
Definition at line 101 of file db_ttl.cc.
References rocksdb::Slice::data(), rocksdb::DecodeFixed32(), GetCurrentTime(), kTSLength, ripple::Resource::ok, and rocksdb::Slice::size().
Referenced by rocksdb::TtlCompactionFilter::Filter().
{
   if (ttl <= 0) { // Data is fresh if TTL is non-positive
     return false;
   }
   int64_t curtime;
   if (!GetCurrentTime(curtime).ok()) {
     return false; // Treat the data as fresh if could not get current time
   }
   int32_t timestamp_value =
     DecodeFixed32(value.data() + value.size() - kTSLength);
   return (timestamp_value + ttl) < curtime;
 }
bool rocksdb::DBWithTTL::KeyMayExist (const ReadOptions & options, const Slice & key, std::string * value, bool * value_found = nullptr) override virtual
Reimplemented from rocksdb::StackableDB.
Definition at line 156 of file db_ttl.cc.
References db_, rocksdb::DB::KeyMayExist(), rocksdb::Status::ok(), SanityCheckTimestamp(), and StripTS().
{
   bool ret = db_->KeyMayExist(options, key, value, value_found);
   if (ret && value != nullptr && value_found != nullptr && *value_found) {
     if (!SanityCheckTimestamp(*value).ok() || !StripTS(value).ok()) {
       return false;
     }
   }
   return ret;
 }
int rocksdb::DBWithTTL::Level0StopWriteTrigger () virtual
Reimplemented from rocksdb::StackableDB.
Definition at line 253 of file db_ttl.cc.
References db_, and rocksdb::DB::Level0StopWriteTrigger().
{
   return db_->Level0StopWriteTrigger();
 }
int rocksdb::DBWithTTL::MaxMemCompactionLevel () virtual
Reimplemented from rocksdb::StackableDB.
Definition at line 249 of file db_ttl.cc.
References db_, and rocksdb::DB::MaxMemCompactionLevel().
{
   return db_->MaxMemCompactionLevel();
 }
Status rocksdb::DBWithTTL::Merge (const WriteOptions & options, const Slice & key, const Slice & value) virtual
Reimplemented from rocksdb::StackableDB.
Definition at line 173 of file db_ttl.cc.
References rocksdb::WriteBatch::Merge(), and Write().
Referenced by Write().
{
   WriteBatch batch;
   batch.Merge(key, value);
   return Write(opt, &batch);
 }
std::vector< Status > rocksdb::DBWithTTL::MultiGet (const ReadOptions & options, const std::vector< Slice > & keys, std::vector< std::string > * values) virtual
Reimplemented from rocksdb::StackableDB.
Definition at line 148 of file db_ttl.cc.
References rocksdb::Status::NotSupported().
{
   return std::vector<Status>(keys.size(),
                              Status::NotSupported("MultiGet not\
                                supported with TTL"));
 }
Iterator * rocksdb::DBWithTTL::NewIterator (const ReadOptions & opts) virtual
Reimplemented from rocksdb::StackableDB.
Definition at line 220 of file db_ttl.cc.
References db_, and rocksdb::DB::NewIterator().
{
   return new TtlIterator(db_->NewIterator(opts));
 }
int rocksdb::DBWithTTL::NumberLevels () virtual
Reimplemented from rocksdb::StackableDB.
Definition at line 245 of file db_ttl.cc.
References db_, and rocksdb::DB::NumberLevels().
{
   return db_->NumberLevels();
 }
Status rocksdb::DBWithTTL::Put (const WriteOptions & o, const Slice & key, const Slice & val) virtual
Reimplemented from rocksdb::StackableDB.
Definition at line 125 of file db_ttl.cc.
References rocksdb::WriteBatch::Put(), and Write().
Referenced by Write().
                       {
   WriteBatch batch;
   batch.Put(key, val);
   return Write(opt, &batch);
 }
void rocksdb::DBWithTTL::ReleaseSnapshot (const Snapshot * snapshot) virtual
Reimplemented from rocksdb::StackableDB.
Definition at line 228 of file db_ttl.cc.
References db_, and rocksdb::DB::ReleaseSnapshot().
{
   db_->ReleaseSnapshot(snapshot);
 }
Status rocksdb::DBWithTTL::SanityCheckTimestamp (const Slice & str) static
Definition at line 86 of file db_ttl.cc.
References rocksdb::Status::Corruption(), rocksdb::Slice::data(), rocksdb::DecodeFixed32(), kMinTimestamp, kTSLength, rocksdb::Status::OK(), and rocksdb::Slice::size().
Referenced by Get(), KeyMayExist(), and rocksdb::TtlIterator::value().
{
   if (str.size() < kTSLength) {
     return Status::Corruption("Error: value's length less than timestamp's\n");
   }
   // Checks that TS is not lesser than kMinTimestamp
   // Gaurds against corruption & normal database opened incorrectly in ttl mode
   int32_t timestamp_value =
     DecodeFixed32(str.data() + str.size() - kTSLength);
   if (timestamp_value < kMinTimestamp){
     return Status::Corruption("Error: Timestamp < ttl feature release time!\n");
   }
   return Status::OK();
 }
Status rocksdb::DBWithTTL::StripTS (std::string * str) static
Definition at line 115 of file db_ttl.cc.
References rocksdb::Status::Corruption(), and kTSLength.
Referenced by Get(), and KeyMayExist().
{
   Status st;
   if (str->length() < kTSLength) {
     return Status::Corruption("Bad timestamp in key-value");
   }
   // Erasing characters which hold the TS
   str->erase(str->length() - kTSLength, kTSLength);
   return st;
 }
void rocksdb::DBWithTTL::TEST_Destroy_DBWithTtl ()
Definition at line 292 of file db_ttl.cc.
References db_.
{
   ((DBImpl*) db_)->TEST_Destroy_DBImpl();
 }
Status rocksdb::DBWithTTL::Write (const WriteOptions & opts, WriteBatch * updates) virtual
Reimplemented from rocksdb::StackableDB.
Definition at line 181 of file db_ttl.cc.
References AppendTS(), db_, Delete(), rocksdb::WriteBatch::Iterate(), Merge(), rocksdb::Status::ok(), Put(), value, and rocksdb::DB::Write().
Referenced by Merge(), and Put().
{
   class Handler : public WriteBatch::Handler {
    public:
     WriteBatch updates_ttl;
     Status batch_rewrite_status;
     virtual void Put(const Slice& key, const Slice& value) {
       std::string value_with_ts;
       Status st = AppendTS(value, value_with_ts);
       if (!st.ok()) {
         batch_rewrite_status = st;
       } else {
         updates_ttl.Put(key, value_with_ts);
       }
     }
     virtual void Merge(const Slice& key, const Slice& value) {
       std::string value_with_ts;
       Status st = AppendTS(value, value_with_ts);
       if (!st.ok()) {
         batch_rewrite_status = st;
       } else {
         updates_ttl.Merge(key, value_with_ts);
       }
     }
     virtual void Delete(const Slice& key) {
       updates_ttl.Delete(key);
     }
     virtual void LogData(const Slice& blob) {
       updates_ttl.PutLogData(blob);
     }
   };
   Handler handler;
   updates->Iterate(&handler);
   if (!handler.batch_rewrite_status.ok()) {
     return handler.batch_rewrite_status;
   } else {
     return db_->Write(opts, &(handler.updates_ttl));
   }
 }
Member Data Documentation
DB* rocksdb::DBWithTTL::db_ private
Definition at line 112 of file db_ttl.h.
Referenced by CompactRange(), DBWithTTL(), Delete(), DeleteFile(), DisableFileDeletions(), EnableFileDeletions(), Flush(), Get(), GetApproximateSizes(), GetLatestSequenceNumber(), GetLiveFiles(), GetProperty(), GetRawDB(), GetSnapshot(), GetSortedWalFiles(), GetUpdatesSince(), KeyMayExist(), Level0StopWriteTrigger(), MaxMemCompactionLevel(), NewIterator(), NumberLevels(), ReleaseSnapshot(), TEST_Destroy_DBWithTtl(), Write(), and ~DBWithTTL().
const int32_t rocksdb::DBWithTTL::kMaxTimestamp = 2147483647 static
Definition at line 109 of file db_ttl.h.
Referenced by rocksdb::DBDumperCommand::DoCommand(), and rocksdb::ScanCommand::DoCommand().
const int32_t rocksdb::DBWithTTL::kMinTimestamp = 1368146402 static
Definition at line 107 of file db_ttl.h.
Referenced by rocksdb::DBDumperCommand::DoCommand(), rocksdb::ScanCommand::DoCommand(), and SanityCheckTimestamp().
const uint32_t rocksdb::DBWithTTL::kTSLength = sizeof(int32_t) static
Definition at line 105 of file db_ttl.h.
Referenced by AppendTS(), rocksdb::TtlCompactionFilter::Filter(), rocksdb::TtlMergeOperator::FullMerge(), IsStale(), rocksdb::TtlMergeOperator::PartialMerge(), SanityCheckTimestamp(), StripTS(), rocksdb::TtlIterator::timestamp(), and rocksdb::TtlIterator::value().
unique_ptr<CompactionFilter> rocksdb::DBWithTTL::ttl_comp_filter_ private
Definition at line 113 of file db_ttl.h.
Referenced by DBWithTTL().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/utilities/ttl/db_ttl.h
rippled/src/ripple/rocksdb/rocksdb/utilities/ttl/db_ttl.cc