rippled: beast::asio::InputParser::Get< UInt32Str > Struct Template Reference
beast::asio::InputParser::Get< UInt32Str > Struct Template Reference
#include <InputParser.h>
Static Public Member Functions
static State func (Input in, UInt32Str &t)
Detailed Description
template<>
struct beast::asio::InputParser::Get< UInt32Str >
Definition at line 237 of file InputParser.h.
Member Function Documentation
static State beast::asio::InputParser::Get< UInt32Str >::func (Input in, UInt32Str & t) inline static
Definition at line 239 of file InputParser.h.
References beast::asio::InputParser::State::eof(), beast::asio::InputParser::State::fail, beast::asio::InputParser::State::failed(), rocksdb::if(), beast::asio::InputParser::State::pass, beast::asio::InputParser::peek(), beast::asio::InputParser::read(), beast::asio::InputParser::Digit::value, beast::asio::InputParser::UInt32Str::value, and value.
     {
         State state;
         std::uint32_t value (0);
         Digit digit;
         // have to have at least one digit
         if (! read (in, digit, state))
             return state;
         value = digit.value;
         for (;;)
         {
             state = peek (in, digit);
             if (state.failed ())
             {
                 t.value = value;
                 return State::pass;
             }
             else if (state.eof ())
             {
                 t.value = value;
                 return state;
             }
             // can't have a digit following a zero
             if (value == 0)
                 return State::fail;
             std::uint32_t newValue = (value * 10) + digit.value;
             // overflow
             if (newValue < value)
                 return State::fail;
             value = newValue;
         }
         return State::fail;
     }
The documentation for this struct was generated from the following file:
rippled/src/beast/modules/beast_asio/protocol/InputParser.h