rippled: rocksdb::FreeList Class Reference
rocksdb::FreeList Class Reference
#include <blob_store.h>
Public Member Functions
FreeList ()
~FreeList ()
Status Allocate (uint32_t blocks, Blob *blob)
Status Free (const Blob &blob)
bool Overlap (const Blob &blob) const
Private Attributes
std::deque< BlobChunk > fifo_free_chunks_
uint32_t free_blocks_
port::Mutex mutex_
Detailed Description
Definition at line 72 of file blob_store.h.
Constructor & Destructor Documentation
rocksdb::FreeList::FreeList () inline
Definition at line 74 of file blob_store.h.
              :
     free_blocks_(0) {}
rocksdb::FreeList::~FreeList () inline
Definition at line 76 of file blob_store.h.
 {}
Member Function Documentation
Status rocksdb::FreeList::Allocate (uint32_t blocks, Blob * blob)
Definition at line 65 of file blob_store.cc.
References rocksdb::Blob::chunks, rocksdb::Status::Incomplete(), and rocksdb::Status::OK().
Referenced by rocksdb::BlobStore::Allocate().
{
   if (free_blocks_ < blocks) {
     return Status::Incomplete("");
   }
   blob->chunks.clear();
   free_blocks_ -= blocks;
   while (blocks > 0) {
     assert(fifo_free_chunks_.size() > 0);
     auto& front = fifo_free_chunks_.front();
     if (front.size > blocks) {
       blob->chunks.push_back(BlobChunk(front.bucket_id, front.offset, blocks));
       front.offset += blocks;
       front.size -= blocks;
       blocks = 0;
     } else {
       blob->chunks.push_back(front);
       blocks -= front.size;
       fifo_free_chunks_.pop_front();
     }
   }
   assert(blocks == 0);
   return Status::OK();
 }
Status rocksdb::FreeList::Free (const Blob & blob)
Definition at line 50 of file blob_store.cc.
References rocksdb::Blob::chunks, and rocksdb::Status::OK().
Referenced by rocksdb::BlobStore::CreateNewBucket(), and rocksdb::BlobStore::Delete().
{
   // add it back to the free list
   for (auto chunk : blob.chunks) {
     free_blocks_ += chunk.size;
     if (fifo_free_chunks_.size() &&
         fifo_free_chunks_.back().ImmediatelyBefore(chunk)) {
       fifo_free_chunks_.back().size += chunk.size;
     } else {
       fifo_free_chunks_.push_back(chunk);
     }
   }
   return Status::OK();
 }
bool rocksdb::FreeList::Overlap (const Blob & blob) const
Definition at line 92 of file blob_store.cc.
References rocksdb::Blob::chunks.
Referenced by rocksdb::BlobStore::Get().
{
   for (auto chunk : blob.chunks) {
     for (auto itr = fifo_free_chunks_.begin();
          itr != fifo_free_chunks_.end();
          ++itr) {
       if (itr->Overlap(chunk)) {
         return true;
       }
     }
   }
   return false;
 }
Member Data Documentation
std::deque<BlobChunk> rocksdb::FreeList::fifo_free_chunks_ private
Definition at line 90 of file blob_store.h.
uint32_t rocksdb::FreeList::free_blocks_ private
Definition at line 91 of file blob_store.h.
port::Mutex rocksdb::FreeList::mutex_ mutable private
Definition at line 92 of file blob_store.h.
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/util/blob_store.h
rippled/src/ripple/rocksdb/rocksdb/util/blob_store.cc