rippled: ripple::PeerFinder::Counts Class Reference
ripple::PeerFinder::Counts Class Reference
#include <Counts.h>
Public Member Functions
Counts ()
void add (Slot const &s)
void remove (Slot const &s)
bool can_activate (Slot const &s) const
std::size_t attempts_needed () const
std::size_t attempts () const
int out_max () const
int out_active () const
std::size_t fixed () const
std::size_t fixed_active () const
void onConfig (Config const &config)
int acceptCount () const
int connectCount () const
int closingCount () const
int inboundSlots () const
int inboundActive () const
int totalActive () const
int inboundSlotsFree () const
int outboundSlotsFree () const
bool isConnectedToNetwork () const
void onWrite (beast::PropertyStream::Map &map)
std::string state_string () const
Private Member Functions
void adjust (Slot const &s, int const n)
Private Attributes
int m_attempts
std::size_t m_active
std::size_t m_in_max
std::size_t m_in_active
std::size_t m_out_max
std::size_t m_out_active
std::size_t m_fixed
std::size_t m_fixed_active
std::size_t m_cluster
int m_acceptCount
int m_closingCount
double m_roundingThreshold
Detailed Description
Manages the count of available connections for the various slots.
Definition at line 29 of file Counts.h.
Constructor & Destructor Documentation
ripple::PeerFinder::Counts::Counts () inline
Definition at line 32 of file Counts.h.
References m_roundingThreshold.
         : m_attempts (0)
         , m_active (0)
         , m_in_max (0)
         , m_in_active (0)
         , m_out_max (0)
         , m_out_active (0)
         , m_fixed (0)
         , m_fixed_active (0)
         , m_cluster (0)
         , m_acceptCount (0)
         , m_closingCount (0)
     {
 #if 1
         std::random_device rd;
         std::mt19937 gen (rd());
         m_roundingThreshold =
             std::generate_canonical <double, 10> (gen);
 #else
         m_roundingThreshold = Random::getSystemRandom().nextDouble();
 #endif
     }
Member Function Documentation
int ripple::PeerFinder::Counts::acceptCount () const inline
Returns the number of accepted connections that haven't handshaked.
Definition at line 155 of file Counts.h.
References m_acceptCount.
Referenced by onWrite().
     {
         return m_acceptCount;
     }
void ripple::PeerFinder::Counts::add (Slot const & s) inline
Adds the slot state and properties to the slot counts.
Definition at line 59 of file Counts.h.
References adjust().
     {
         adjust (s, 1);
     }
void ripple::PeerFinder::Counts::adjust (Slot const & s, int const n) inline private
Definition at line 256 of file Counts.h.
References ripple::PeerFinder::Slot::accept, ripple::PeerFinder::Slot::active, ripple::PeerFinder::Slot::closing, ripple::PeerFinder::Slot::cluster(), ripple::PeerFinder::Slot::connect, ripple::PeerFinder::Slot::connected, ripple::PeerFinder::Slot::fixed(), ripple::PeerFinder::Slot::inbound(), m_acceptCount, m_active, m_attempts, m_closingCount, m_cluster, m_fixed, m_fixed_active, m_in_active, m_out_active, and ripple::PeerFinder::Slot::state().
Referenced by add(), and remove().
     {
         if (s.fixed ())
             m_fixed += n;
         if (s.cluster ())
             m_cluster += n;
         switch (s.state ())
         {
         case Slot::accept:
             assert (s.inbound ());
             m_acceptCount += n;
             break;
         case Slot::connect:
         case Slot::connected:
             assert (! s.inbound ());
             m_attempts += n;
             break;
         case Slot::active:
             if (s.fixed ())
                 m_fixed_active += n;
             if (! s.fixed () && ! s.cluster ())
             {
                 if (s.inbound ())
                     m_in_active += n;
                 else
                     m_out_active += n;
             }
             m_active += n;
             break;
         case Slot::closing:
             m_closingCount += n;
             break;
         default:
             assert (false);
             break;
         };
     }
std::size_t ripple::PeerFinder::Counts::attempts () const inline
Returns the number of outbound connection attempts.
Definition at line 94 of file Counts.h.
References m_attempts.
     {
         return m_attempts;
     };
std::size_t ripple::PeerFinder::Counts::attempts_needed () const inline
Returns the number of attempts needed to bring us to the max.
Definition at line 86 of file Counts.h.
References m_attempts, and ripple::PeerFinder::Tuning::maxConnectAttempts.
     {
         if (m_attempts >= Tuning::maxConnectAttempts)
             return 0;
         return Tuning::maxConnectAttempts - m_attempts;
     }
bool ripple::PeerFinder::Counts::can_activate (Slot const & s) const inline
Returns true if the slot can become active.
Definition at line 71 of file Counts.h.
References ripple::PeerFinder::Slot::accept, ripple::PeerFinder::Slot::cluster(), ripple::PeerFinder::Slot::connected, ripple::PeerFinder::Slot::fixed(), ripple::PeerFinder::Slot::inbound(), m_in_active, m_in_max, m_out_active, m_out_max, and ripple::PeerFinder::Slot::state().
     {
         // Must be handshaked and in the right state
         assert (s.state() == Slot::connected || s.state() == Slot::accept);
         if (s.fixed () || s.cluster ())
             return true;
         if (s.inbound ())
             return m_in_active < m_in_max;
         return m_out_active < m_out_max;
     }
int ripple::PeerFinder::Counts::closingCount () const inline
Returns the number of connections that are gracefully closing.
Definition at line 167 of file Counts.h.
References m_closingCount.
Referenced by onWrite(), and state_string().
     {
         return m_closingCount;
     }
int ripple::PeerFinder::Counts::connectCount () const inline
Returns the number of connection attempts currently active.
Definition at line 161 of file Counts.h.
References m_attempts.
Referenced by onWrite(), and state_string().
     {
         return m_attempts;
     }
std::size_t ripple::PeerFinder::Counts::fixed () const inline
Returns the number of fixed connections.
Definition at line 114 of file Counts.h.
References m_fixed.
     {
         return m_fixed;
     }
std::size_t ripple::PeerFinder::Counts::fixed_active () const inline
Returns the number of active fixed connections.
Definition at line 120 of file Counts.h.
References m_fixed_active.
     {
         return m_fixed_active;
     }
int ripple::PeerFinder::Counts::inboundActive () const inline
Returns the number of inbound peers assigned an open slot.
Definition at line 179 of file Counts.h.
References m_in_active.
     {
         return m_in_active;
     }
int ripple::PeerFinder::Counts::inboundSlots () const inline
Returns the total number of inbound slots.
Definition at line 173 of file Counts.h.
References m_in_max.
     {
         return m_in_max;
     }
int ripple::PeerFinder::Counts::inboundSlotsFree () const inline
Returns the number of unused inbound slots. Fixed peers do not deduct from inbound slots or count towards totals.
Definition at line 193 of file Counts.h.
References m_in_active, and m_in_max.
     {
         if (m_in_active < m_in_max)
             return m_in_max - m_in_active;
         return 0;
     }
bool ripple::PeerFinder::Counts::isConnectedToNetwork () const inline
Returns true if the slot logic considers us "connected" to the network.
Definition at line 213 of file Counts.h.
References m_out_max.
     {
         // We will consider ourselves connected if we have reached
         // the number of outgoing connections desired, or if connect
         // automatically is false.
         //
         // Fixed peers do not count towards the active outgoing total.
         if (m_out_max > 0)
             return false;
         return true;
     }
void ripple::PeerFinder::Counts::onConfig (Config const & config) inline
Called when the config is set or changed.
Definition at line 128 of file Counts.h.
References floor(), m_in_max, m_out_max, m_roundingThreshold, ripple::PeerFinder::Config::maxPeers, ripple::PeerFinder::Config::outPeers, and ripple::PeerFinder::Config::wantIncoming.
     {
         // Calculate the number of outbound peers we want. If we dont want or can't
         // accept incoming, this will simply be equal to maxPeers. Otherwise
         // we calculate a fractional amount based on percentages and pseudo-randomly
         // round up or down.
         //
         if (config.wantIncoming)
         {
             // Round outPeers upwards using a Bernoulli distribution
             m_out_max = std::floor (config.outPeers);
             if (m_roundingThreshold < (config.outPeers - m_out_max))
                 ++m_out_max;
         }
         else
         {
             m_out_max = config.maxPeers;
         }
         // Calculate the largest number of inbound connections we could take.
         if (config.maxPeers >= m_out_max)
             m_in_max = config.maxPeers - m_out_max;
         else
             m_in_max = 0;
     }
void ripple::PeerFinder::Counts::onWrite (beast::PropertyStream::Map & map) inline
Output statistics.
Definition at line 228 of file Counts.h.
References acceptCount(), closingCount(), connectCount(), m_active, m_cluster, m_fixed_active, m_in_active, m_in_max, m_out_active, and m_out_max.
     {
         map ["accept"]  = acceptCount ();
         map ["connect"] = connectCount ();
         map ["close"]   = closingCount ();
         map ["in"]      << m_in_active << "/" << m_in_max;
         map ["out"]     << m_out_active << "/" << m_out_max;
         map ["fixed"]   = m_fixed_active;
         map ["cluster"] = m_cluster;
         map ["total"]   = m_active;
     }
int ripple::PeerFinder::Counts::out_active () const inline
Returns the number of outbound peers assigned an open slot. Fixed peers do not count towards outbound slots used.
Definition at line 108 of file Counts.h.
References m_out_active.
     {
         return m_out_active;
     }
int ripple::PeerFinder::Counts::out_max () const inline
Returns the total number of outbound slots.
Definition at line 100 of file Counts.h.
References m_out_max.
     {
         return m_out_max;
     }
int ripple::PeerFinder::Counts::outboundSlotsFree () const inline
Returns the number of unused outbound slots. Fixed peers do not deduct from outbound slots or count towards totals.
Definition at line 203 of file Counts.h.
References m_out_active, and m_out_max.
     {
         if (m_out_active < m_out_max)
             return m_out_max - m_out_active;
         return 0;
     }
void ripple::PeerFinder::Counts::remove (Slot const & s) inline
Removes the slot state and properties from the slot counts.
Definition at line 65 of file Counts.h.
References adjust().
     {
         adjust (s, -1);
     }
std::string ripple::PeerFinder::Counts::state_string () const inline
Records the state for diagnostics.
Definition at line 241 of file Counts.h.
References closingCount(), connectCount(), m_in_active, m_in_max, m_out_active, and m_out_max.
     {
         std::stringstream ss;
         ss <<
             m_out_active << "/" << m_out_max << " out, " <<
             m_in_active << "/" << m_in_max << " in, " <<
             connectCount() << " connecting, " <<
             closingCount() << " closing"
             ;
         return ss.str();
     }
int ripple::PeerFinder::Counts::totalActive () const inline
Returns the total number of active peers excluding fixed peers.
Definition at line 185 of file Counts.h.
References m_in_active, and m_out_active.
     {
         return m_in_active + m_out_active;
     }
Member Data Documentation
int ripple::PeerFinder::Counts::m_acceptCount private
Definition at line 333 of file Counts.h.
Referenced by acceptCount(), and adjust().
std::size_t ripple::PeerFinder::Counts::m_active private
Active connections, including fixed and cluster.
Definition at line 305 of file Counts.h.
Referenced by adjust(), and onWrite().
int ripple::PeerFinder::Counts::m_attempts private
Outbound connection attempts.
Definition at line 302 of file Counts.h.
Referenced by adjust(), attempts(), attempts_needed(), and connectCount().
int ripple::PeerFinder::Counts::m_closingCount private
Definition at line 336 of file Counts.h.
Referenced by adjust(), and closingCount().
std::size_t ripple::PeerFinder::Counts::m_cluster private
Cluster connections.
Definition at line 326 of file Counts.h.
Referenced by adjust(), and onWrite().
std::size_t ripple::PeerFinder::Counts::m_fixed private
Fixed connections.
Definition at line 320 of file Counts.h.
Referenced by adjust(), and fixed().
std::size_t ripple::PeerFinder::Counts::m_fixed_active private
Active fixed connections.
Definition at line 323 of file Counts.h.
Referenced by adjust(), fixed_active(), and onWrite().
std::size_t ripple::PeerFinder::Counts::m_in_active private
Number of inbound slots assigned to active peers.
Definition at line 311 of file Counts.h.
Referenced by adjust(), can_activate(), inboundActive(), inboundSlotsFree(), onWrite(), state_string(), and totalActive().
std::size_t ripple::PeerFinder::Counts::m_in_max private
Total number of inbound slots.
Definition at line 308 of file Counts.h.
Referenced by can_activate(), inboundSlots(), inboundSlotsFree(), onConfig(), onWrite(), and state_string().
std::size_t ripple::PeerFinder::Counts::m_out_active private
Active outbound slots.
Definition at line 317 of file Counts.h.
Referenced by adjust(), can_activate(), onWrite(), out_active(), outboundSlotsFree(), state_string(), and totalActive().
std::size_t ripple::PeerFinder::Counts::m_out_max private
Maximum desired outbound slots.
Definition at line 314 of file Counts.h.
Referenced by can_activate(), isConnectedToNetwork(), onConfig(), onWrite(), out_max(), outboundSlotsFree(), and state_string().
double ripple::PeerFinder::Counts::m_roundingThreshold private
Fractional threshold below which we round down. This is used to round the value of Config::outPeers up or down in such a way that the network-wide average number of outgoing connections approximates the recommended, fractional value.
Definition at line 343 of file Counts.h.
Referenced by Counts(), and onConfig().
The documentation for this class was generated from the following file:
rippled/src/ripple/peerfinder/impl/Counts.h