rippled: rocksdb::TtlTest Class Reference
rocksdb::TtlTest Class Reference
Classes
class TestFilter
class TestFilterFactory
Public Member Functions
TtlTest ()
~TtlTest ()
void OpenTtl ()
void OpenTtl (int32_t ttl)
void OpenTtlWithTestCompaction (int32_t ttl)
void OpenReadOnlyTtl (int32_t ttl)
void CloseTtl ()
void MakeKVMap (int64_t num_entries)
void MakePutWriteBatch (const BatchOperation *batch_ops, int num_ops)
void PutValues (int start_pos_map, int num_entries, bool flush=true)
void ManualCompact ()
void SimpleKeyMayExistCheck ()
void SleepCompactCheck (int slp_tim, int st_pos, int span, bool check=true, bool test_compaction_change=false)
void SleepCompactCheckIter (int slp, int st_pos, int span, bool check=true)
Public Attributes
const int64_t kSampleSize_ = 100
Private Attributes
std::string dbname_
StackableDB * db_ttl_
Options options_
KVMap kvmap_
KVMap::iterator kv_it_
const std::string kNewValue_ = "new_value"
unique_ptr< CompactionFilter > test_comp_filter_
Detailed Description
Definition at line 26 of file ttl_test.cc.
Constructor & Destructor Documentation
rocksdb::TtlTest::TtlTest () inline
Definition at line 28 of file ttl_test.cc.
References rocksdb::Options::create_if_missing, db_ttl_, dbname_, rocksdb::DestroyDB(), rocksdb::Options::max_grandparent_overlap_factor, rocksdb::Options::max_mem_compaction_level, options_, and rocksdb::test::TmpDir().
             {
     dbname_ = test::TmpDir() + "/db_ttl";
     options_.create_if_missing = true;
     // ensure that compaction is kicked in to always strip timestamp from kvs
     options_.max_grandparent_overlap_factor = 0;
     // compaction should take place always from level0 for determinism
     options_.max_mem_compaction_level = 0;
     db_ttl_ = nullptr;
     DestroyDB(dbname_, Options());
   }
rocksdb::TtlTest::~TtlTest () inline
Definition at line 39 of file ttl_test.cc.
References CloseTtl(), dbname_, and rocksdb::DestroyDB().
              {
     CloseTtl();
     DestroyDB(dbname_, Options());
   }
Member Function Documentation
void rocksdb::TtlTest::CloseTtl () inline
Definition at line 70 of file ttl_test.cc.
References db_ttl_.
Referenced by ~TtlTest().
                   {
     delete db_ttl_;
     db_ttl_ = nullptr;
   }
void rocksdb::TtlTest::MakeKVMap (int64_t num_entries) inline
Definition at line 76 of file ttl_test.cc.
References rocksdb::AppendNumberTo(), ASSERT_EQ, kvmap_, and value.
{
     kvmap_.clear();
     int digits = 1;
     for (int dummy = num_entries; dummy /= 10 ; ++digits);
     int digits_in_i = 1;
     for (int64_t i = 0; i < num_entries; i++) {
       std::string key = "key";
       std::string value = "value";
       if (i % 10 == 0) {
         digits_in_i++;
       }
       for(int j = digits_in_i; j < digits; j++) {
         key.append("0");
         value.append("0");
       }
       AppendNumberTo(&key, i);
       AppendNumberTo(&value, i);
       kvmap_[key] = value;
     }
     ASSERT_EQ((int)kvmap_.size(), num_entries);//check all insertions done
   }
void rocksdb::TtlTest::MakePutWriteBatch (const BatchOperation * batch_ops, int num_ops) inline
Definition at line 99 of file ttl_test.cc.
References db_ttl_, rocksdb::WriteBatch::Delete(), rocksdb::StackableDB::Flush(), kv_it_, kvmap_, rocksdb::WriteBatch::Put(), and rocksdb::StackableDB::Write().
{
     assert(num_ops <= (int)kvmap_.size());
     static WriteOptions wopts;
     static FlushOptions flush_opts;
     WriteBatch batch;
     kv_it_ = kvmap_.begin();
     for (int i = 0; i < num_ops && kv_it_ != kvmap_.end(); i++, kv_it_++) {
       switch (batch_ops[i]) {
         case PUT:
           batch.Put(kv_it_->first, kv_it_->second);
           break;
         case DELETE:
           batch.Delete(kv_it_->first);
           break;
         default:
           assert(false);
       }
     }
     db_ttl_->Write(wopts, &batch);
     db_ttl_->Flush(flush_opts);
   }
void rocksdb::TtlTest::ManualCompact () inline
Definition at line 140 of file ttl_test.cc.
References rocksdb::StackableDB::CompactRange(), and db_ttl_.
Referenced by SleepCompactCheck(), and SleepCompactCheckIter().
{
     db_ttl_->CompactRange(nullptr, nullptr);
   }
void rocksdb::TtlTest::OpenReadOnlyTtl (int32_t ttl) inline
Definition at line 65 of file ttl_test.cc.
References ASSERT_OK, db_ttl_, dbname_, rocksdb::UtilityDB::OpenTtlDB(), and options_.
{
     assert(db_ttl_ == nullptr);
     ASSERT_OK(UtilityDB::OpenTtlDB(options_, dbname_, &db_ttl_, ttl, true));
   }
void rocksdb::TtlTest::OpenTtl () inline
Definition at line 45 of file ttl_test.cc.
References ASSERT_OK, db_ttl_, dbname_, rocksdb::UtilityDB::OpenTtlDB(), and options_.
Referenced by OpenTtlWithTestCompaction().
                  {
     assert(db_ttl_ == nullptr); //  db should be closed before opening again
     ASSERT_OK(UtilityDB::OpenTtlDB(options_, dbname_, &db_ttl_));
   }
void rocksdb::TtlTest::OpenTtl (int32_t ttl) inline
Definition at line 51 of file ttl_test.cc.
References ASSERT_OK, db_ttl_, dbname_, rocksdb::UtilityDB::OpenTtlDB(), and options_.
{
     assert(db_ttl_ == nullptr);
     ASSERT_OK(UtilityDB::OpenTtlDB(options_, dbname_, &db_ttl_, ttl));
   }
void rocksdb::TtlTest::OpenTtlWithTestCompaction (int32_t ttl) inline
Definition at line 57 of file ttl_test.cc.
References rocksdb::Options::compaction_filter_factory, kNewValue_, kSampleSize_, OpenTtl(), and options_.
{
     options_.compaction_filter_factory =
       std::shared_ptr<CompactionFilterFactory>(
           new TestFilterFactory(kSampleSize_, kNewValue_));
     OpenTtl(ttl);
   }
void rocksdb::TtlTest::PutValues (int start_pos_map, int num_entries, bool flush = true) inline
Definition at line 122 of file ttl_test.cc.
References ASSERT_LE, ASSERT_OK, db_ttl_, rocksdb::StackableDB::Flush(), kv_it_, kvmap_, and rocksdb::StackableDB::Put().
{
     assert(db_ttl_);
     ASSERT_LE(start_pos_map + num_entries, (int)kvmap_.size());
     static WriteOptions wopts;
     static FlushOptions flush_opts;
     kv_it_ = kvmap_.begin();
     advance(kv_it_, start_pos_map);
     for (int i = 0; kv_it_ != kvmap_.end() && i < num_entries; i++, kv_it_++) {
       ASSERT_OK(db_ttl_->Put(wopts, kv_it_->first, kv_it_->second));
     }
     // Put a mock kv at the end because CompactionFilter doesn't delete last key
     ASSERT_OK(db_ttl_->Put(wopts, "keymock", "valuemock"));
     if (flush) {
       db_ttl_->Flush(flush_opts);
     }
   }
void rocksdb::TtlTest::SimpleKeyMayExistCheck () inline
Definition at line 145 of file ttl_test.cc.
References db_ttl_, rocksdb::StackableDB::KeyMayExist(), kvmap_, and value_found.
{
     static ReadOptions ropts;
     bool value_found;
     std::string val;
     for(auto &kv : kvmap_) {
       bool ret = db_ttl_->KeyMayExist(ropts, kv.first, &val, &value_found);
       if (ret == false || value_found == false) {
         fprintf(stderr, "KeyMayExist could not find key=%s in the database but"
                         " should have\n", kv.first.c_str());
         assert(false);
       } else if (val.compare(kv.second) != 0) {
         fprintf(stderr, " value for key=%s present in database is %s but"
                         " should be %s\n", kv.first.c_str(), val.c_str(),
                         kv.second.c_str());
         assert(false);
       }
     }
   }
void rocksdb::TtlTest::SleepCompactCheck (int slp_tim, int st_pos, int span, bool check = true, bool test_compaction_change = false) inline
Definition at line 169 of file ttl_test.cc.
References db_ttl_, rocksdb::StackableDB::Get(), kNewValue_, kv_it_, kvmap_, ManualCompact(), and rocksdb::Status::ok().
{
     assert(db_ttl_);
     sleep(slp_tim);
     ManualCompact();
     static ReadOptions ropts;
     kv_it_ = kvmap_.begin();
     advance(kv_it_, st_pos);
     std::string v;
     for (int i = 0; kv_it_ != kvmap_.end() && i < span; i++, kv_it_++) {
       Status s = db_ttl_->Get(ropts, kv_it_->first, &v);
       if (s.ok() != check) {
         fprintf(stderr, "key=%s ", kv_it_->first.c_str());
         if (!s.ok()) {
           fprintf(stderr, "is absent from db but was expected to be present\n");
         } else {
           fprintf(stderr, "is present in db but was expected to be absent\n");
         }
         assert(false);
       } else if (s.ok()) {
           if (test_compaction_change && v.compare(kNewValue_) != 0) {
             fprintf(stderr, " value for key=%s present in database is %s but "
                             " should be %s\n", kv_it_->first.c_str(), v.c_str(),
                             kNewValue_.c_str());
             assert(false);
           } else if (!test_compaction_change && v.compare(kv_it_->second) !=0) {
             fprintf(stderr, " value for key=%s present in database is %s but "
                             " should be %s\n", kv_it_->first.c_str(), v.c_str(),
                             kv_it_->second.c_str());
             assert(false);
           }
       }
     }
   }
void rocksdb::TtlTest::SleepCompactCheckIter (int slp, int st_pos, int span, bool check = true) inline
Definition at line 205 of file ttl_test.cc.
References ASSERT_EQ, ASSERT_NE, ASSERT_TRUE, rocksdb::Slice::compare(), db_ttl_, kv_it_, kvmap_, ManualCompact(), rocksdb::StackableDB::NewIterator(), rocksdb::Iterator::Next(), rocksdb::Iterator::Seek(), rocksdb::Iterator::Valid(), and rocksdb::Iterator::value().
{
     assert(db_ttl_);
     sleep(slp);
     ManualCompact();
     static ReadOptions ropts;
     Iterator *dbiter = db_ttl_->NewIterator(ropts);
     kv_it_ = kvmap_.begin();
     advance(kv_it_, st_pos);
     dbiter->Seek(kv_it_->first);
     if (!check) {
       if (dbiter->Valid()) {
         ASSERT_NE(dbiter->value().compare(kv_it_->second), 0);
       }
     } else {  // dbiter should have found out kvmap_[st_pos]
       for (int i = st_pos;
            kv_it_ != kvmap_.end() && i < st_pos + span;
            i++, kv_it_++)  {
         ASSERT_TRUE(dbiter->Valid());
         ASSERT_EQ(dbiter->value().compare(kv_it_->second), 0);
         dbiter->Next();
       }
     }
     delete dbiter;
   }
Member Data Documentation
StackableDB* rocksdb::TtlTest::db_ttl_ private
Definition at line 308 of file ttl_test.cc.
Referenced by CloseTtl(), MakePutWriteBatch(), ManualCompact(), OpenReadOnlyTtl(), OpenTtl(), PutValues(), SimpleKeyMayExistCheck(), SleepCompactCheck(), SleepCompactCheckIter(), and TtlTest().
std::string rocksdb::TtlTest::dbname_ private
Definition at line 307 of file ttl_test.cc.
Referenced by OpenReadOnlyTtl(), OpenTtl(), TtlTest(), and ~TtlTest().
const std::string rocksdb::TtlTest::kNewValue_ = "new_value" private
Definition at line 312 of file ttl_test.cc.
Referenced by OpenTtlWithTestCompaction(), and SleepCompactCheck().
const int64_t rocksdb::TtlTest::kSampleSize_ = 100
Definition at line 304 of file ttl_test.cc.
Referenced by OpenTtlWithTestCompaction().
KVMap::iterator rocksdb::TtlTest::kv_it_ private
Definition at line 311 of file ttl_test.cc.
Referenced by MakePutWriteBatch(), PutValues(), SleepCompactCheck(), and SleepCompactCheckIter().
KVMap rocksdb::TtlTest::kvmap_ private
Definition at line 310 of file ttl_test.cc.
Referenced by MakeKVMap(), MakePutWriteBatch(), PutValues(), SimpleKeyMayExistCheck(), SleepCompactCheck(), and SleepCompactCheckIter().
Options rocksdb::TtlTest::options_ private
Definition at line 309 of file ttl_test.cc.
Referenced by OpenReadOnlyTtl(), OpenTtl(), OpenTtlWithTestCompaction(), and TtlTest().
unique_ptr<CompactionFilter> rocksdb::TtlTest::test_comp_filter_ private
Definition at line 313 of file ttl_test.cc.
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/utilities/ttl/ttl_test.cc