rippled: beast::IP::detail Namespace Reference
beast::IP::detail Namespace Reference
Classes
struct integer_holder
Functions
template<typename InputStream >
bool expect (InputStream &is, char v)
template<typename InputStream >
InputStream & operator>> (InputStream &is, integer_holder< std::uint8_t > const &i)
template<typename IntType >
integer_holder< IntType > integer (IntType &i)
Function Documentation
template<typename InputStream > bool beast::IP::detail::expect (InputStream & is, char v)
Require and consume the specified character from the input.
Returns
true if the character matched.
Definition at line 35 of file Parse.h.
Referenced by ripple::BuildInfo_test::checkProtcol(), ripple::STAmount_test::expect(), beast::Workers_test::expectEquals(), beast::IP::Endpoint::from_string_altform(), beast::IP::operator>>(), beast::PropertyStream_test::test_find(), beast::PropertyStream_test::test_find_one(), beast::PropertyStream_test::test_find_one_deep(), beast::PropertyStream_test::test_find_path(), beast::PropertyStream_test::test_peel_leading_slash(), beast::PropertyStream_test::test_peel_name(), beast::PropertyStream_test::test_peel_trailing_slashstar(), ripple::BuildInfo_test::testProtocol(), beast::Workers_test::testThreads(), ripple::BuildInfo_test::testValues(), and ripple::BuildInfo_test::testVersion().
 {
     char c;
     if (is.get(c) && v == c)
         return true;
     is.unget();
     is.setstate (std::ios_base::failbit);
     return false;
 }
template<typename IntType > integer_holder<IntType> beast::IP::detail::integer (IntType & i)
Free function for template argument deduction.
Definition at line 79 of file Parse.h.
Referenced by beast::IP::operator>>().
 {
     return integer_holder <IntType> (i);
 }
template<typename InputStream > InputStream& beast::IP::detail::operator>> (InputStream & is, integer_holder< std::uint8_t > const & i)
Parse 8-bit unsigned integer.
Definition at line 64 of file Parse.h.
 {
     std::uint16_t v;
     is >> v;
     if (! (v>=0 && v<=255))
     {
         is.setstate (std::ios_base::failbit);
         return is;
     }
     i = std::uint8_t(v);
     return is;
 }