rippled: ripple::Application Class Reference
ripple::Application Class Reference abstract
#include <Application.h>
Public Types
typedef RippleRecursiveMutex LockType
typedef std::unique_lock
< LockType > ScopedLockType
Public Member Functions
virtual LockType & getMasterLock ()=0
Application ()
virtual ~Application ()
virtual boost::asio::io_service & getIOService ()=0
virtual CollectorManager & getCollectorManager ()=0
virtual FullBelowCache & getFullBelowCache ()=0
virtual JobQueue & getJobQueue ()=0
virtual RPC::Manager & getRPCManager ()=0
virtual SiteFiles::Manager & getSiteFiles ()=0
virtual NodeCache & getTempNodeCache ()=0
virtual SLECache & getSLECache ()=0
virtual Validators::Manager & getValidators ()=0
virtual FeatureTable & getFeatureTable ()=0
virtual IHashRouter & getHashRouter ()=0
virtual LoadFeeTrack & getFeeTrack ()=0
virtual LoadManager & getLoadManager ()=0
virtual Overlay & overlay ()=0
virtual ProofOfWorkFactory & getProofOfWorkFactory ()=0
virtual UniqueNodeList & getUNL ()=0
virtual Validations & getValidations ()=0
virtual NodeStore::Database & getNodeStore ()=0
virtual InboundLedgers & getInboundLedgers ()=0
virtual LedgerMaster & getLedgerMaster ()=0
virtual NetworkOPs & getOPs ()=0
virtual OrderBookDB & getOrderBookDB ()=0
virtual TransactionMaster & getMasterTransaction ()=0
virtual TxQueue & getTxQueue ()=0
virtual LocalCredentials & getLocalCredentials ()=0
virtual Resource::Manager & getResourceManager ()=0
virtual PathRequests & getPathRequests ()=0
virtual DatabaseCon * getRpcDB ()=0
virtual DatabaseCon * getTxnDB ()=0
virtual DatabaseCon * getLedgerDB ()=0
virtual DatabaseCon * getWalletDB ()=0
virtual bool getSystemTimeOffset (int &offset)=0
virtual bool isShutdown ()=0
virtual bool running ()=0
virtual void setup ()=0
virtual void run ()=0
virtual void signalStop ()=0
Public Member Functions inherited from beast::PropertyStream::Source
Source (std::string const &name)
~Source ()
std::string const & name () const
void add (Source &source)
template<class Derived >
Derived * add (Derived *child)
void remove (Source &child)
void removeAll ()
void write_one (PropertyStream &stream)
void write (PropertyStream &stream)
void write (PropertyStream &stream, std::string const &path)
std::pair< Source *, bool > find (std::string path)
Source * find_one_deep (std::string const &name)
PropertyStream::Source * find_path (std::string path)
PropertyStream::Source * find_one (std::string const &name)
virtual void onWrite (Map &)
Additional Inherited Members
Static Public Member Functions inherited from beast::PropertyStream::Source
static bool peel_leading_slash (std::string *path)
static bool peel_trailing_slashstar (std::string *path)
static std::string peel_name (std::string *path)
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
Definition at line 58 of file Application.h.
Member Typedef Documentation
typedef RippleRecursiveMutex ripple::Application::LockType
Definition at line 72 of file Application.h.
typedef std::unique_lock<LockType> ripple::Application::ScopedLockType
Definition at line 73 of file Application.h.
Constructor & Destructor Documentation
ripple::Application::Application ()
Definition at line 1377 of file Application.cpp.
     : beast::PropertyStream::Source ("app")
 {
 }
virtual ripple::Application::~Application () inline virtual
Definition at line 80 of file Application.h.
 { }
Member Function Documentation
virtual CollectorManager& ripple::Application::getCollectorManager () pure virtual
Implemented in ripple::ApplicationImp.
virtual FeatureTable& ripple::Application::getFeatureTable () pure virtual
Implemented in ripple::ApplicationImp.
Referenced by ripple::LedgerConsensusImp::accept(), ripple::ChangeTransactor::applyFeature(), ripple::RPCHandler::doFeature(), and ripple::LedgerConsensusImp::takeInitialPosition().
virtual LoadFeeTrack& ripple::Application::getFeeTrack () pure virtual
Implemented in ripple::ApplicationImp.
Referenced by ripple::UniqueNodeListImp::addClusterStatus(), ripple::LedgerConsensusImp::addLoad(), ripple::LedgerMasterImp::checkAccept(), ripple::LedgerMasterImp::doAdvance(), ripple::PathRequest::doUpdate(), ripple::NetworkOPsImp::getServerInfo(), ripple::NetworkOPsImp::pubServer(), ripple::PeerImp::recvCluster(), ripple::PeerImp::recvValidation(), ripple::LoadManagerImp::run(), ripple::Ledger::scaleFeeBase(), ripple::Ledger::scaleFeeLoad(), and ripple::NetworkOPsImp::subServer().
virtual FullBelowCache& ripple::Application::getFullBelowCache () pure virtual
Implemented in ripple::ApplicationImp.
virtual IHashRouter& ripple::Application::getHashRouter () pure virtual
Implemented in ripple::ApplicationImp.
Referenced by ripple::LedgerConsensusImp::accept(), ripple::LedgerConsensusImp::addDisputedTransaction(), ripple::LedgerConsensusImp::applyTransaction(), ripple::LedgerConsensusImp::checkOurValidation(), ripple::PeerImp::checkTransaction(), ripple::LedgerMasterImp::closeLedger(), ripple::NetworkOPsImp::processTransactionCb(), ripple::NetworkOPsImp::runTransactionQueue(), and ripple::NetworkOPsImp::submitTransaction().
virtual InboundLedgers& ripple::Application::getInboundLedgers () pure virtual
Implemented in ripple::ApplicationImp.
Referenced by ripple::LedgerMasterImp::checkAccept(), ripple::NetworkOPsImp::checkLastClosedLedger(), ripple::NetworkOPsImp::clearLedgerFetch(), ripple::LedgerMasterImp::doAdvance(), ripple::LedgerCleanerImp::doLedger(), ripple::InboundLedger::done(), ripple::LedgerMasterImp::failedSave(), ripple::LedgerMasterImp::findAcquireLedger(), ripple::LedgerMasterImp::findNewLedgersToPublish(), ripple::NetworkOPsImp::getLedgerFetchInfo(), ripple::LedgerCleanerImp::getLedgerHash(), ripple::NetworkOPsImp::missingNodeInLedger(), ripple::TACompletionHandler(), ripple::LedgerMasterImp::updatePaths(), ripple::Ledger::visitStateItems(), and ripple::InboundLedger::~InboundLedger().
virtual boost::asio::io_service& ripple::Application::getIOService () pure virtual
Implemented in ripple::ApplicationImp.
Referenced by ripple::NetworkOPsImp::runTransactionQueue().
virtual JobQueue& ripple::Application::getJobQueue () pure virtual
Implemented in ripple::ApplicationImp.
Referenced by ripple::LedgerConsensusImp::beginAccept(), ripple::ValidationsImp::condWrite(), ripple::WSServerHandler< endpoint_type >::do_messages(), ripple::LedgerMasterImp::doAdvance(), ripple::WSServerHandler< endpoint_type >::doClose(), ripple::RPCHandler::doCommand(), ripple::PeerImp::doFetchPack(), ripple::TransactionAcquire::done(), ripple::InboundLedger::done(), ripple::NetworkOPsImp::getServerInfo(), ripple::NetworkOPsImp::gotFetchPack(), ripple::InboundLedgersImp::gotLedgerData(), ripple::ConsensusTransSetSF::gotNode(), ripple::LedgerConsensusImp::handleLCL(), ripple::LedgerMasterImp::newPFWork(), ripple::WSServerHandler< endpoint_type >::on_message(), ripple::UniqueNodeListImp::onDeadlineTimer(), ripple::NetworkOPsImp::onDeadlineTimer(), ripple::Pathfinder::Pathfinder(), ripple::LedgerConsensusImp::peerHasSet(), ripple::Ledger::pendSaveValidated(), ripple::NetworkOPsImp::processTransactionCb(), ripple::PeerImp::recvGetLedger(), ripple::PeerImp::recvProofWork(), ripple::PeerImp::recvPropose(), ripple::PeerImp::recvTransaction(), ripple::PeerImp::recvValidation(), ripple::NetworkOPsImp::reportFeeChange(), ripple::LoadManagerImp::run(), ripple::NetworkOPsImp::runTransactionQueue(), ripple::OrderBookDB::setup(), ripple::NetworkOPsImp::submitTransaction(), ripple::PeerSet::TimerEntry(), and ripple::LedgerMasterImp::tryAdvance().
virtual DatabaseCon* ripple::Application::getLedgerDB () pure virtual
Implemented in ripple::ApplicationImp.
Referenced by ripple::RPCHandler::doGetCounts(), ripple::ValidationsImp::doWrite(), ripple::Ledger::getHashByIndex(), ripple::Ledger::getHashesByIndex(), ripple::Ledger::getSQL(), ripple::Ledger::loadByHash(), ripple::Ledger::loadByIndex(), ripple::Ledger::saveValidatedLedger(), and ripple::ApplicationImp::setup().
virtual LedgerMaster& ripple::Application::getLedgerMaster () pure virtual
Implemented in ripple::ApplicationImp.
Referenced by ripple::LedgerConsensusImp::accept(), ripple::ValidationsImp::addValidation(), ripple::PeerImp::checkTransaction(), ripple::LedgerConsensusImp::closeLedger(), ripple::LedgerMasterImp::doAdvance(), ripple::LedgerCleanerImp::doClean(), ripple::PeerImp::doFetchPack(), ripple::RPCHandler::doGetCounts(), ripple::RPCHandler::doLedger(), ripple::LedgerCleanerImp::doLedger(), ripple::RPCHandler::doLedgerCleaner(), ripple::InboundLedger::done(), ripple::RPCHandler::doSubscribe(), ripple::LedgerCleanerImp::getHash(), ripple::Transaction::getJson(), ripple::PeerImp::getLedger(), ripple::NetworkOPsImp::getServerInfo(), ripple::LedgerConsensusImp::getTransactionTree(), ripple::LedgerConsensusImp::handleLCL(), ripple::InboundLedger::init(), ripple::LADispatch(), ripple::RPC::lookupLedger(), ripple::PathRequests::makePathRequest(), ripple::NetworkOPsImp::missingNodeInLedger(), ripple::NetworkOPsImp::pubLedger(), ripple::Ledger::saveValidatedLedger(), ripple::PeerImp::sendHello(), ripple::LedgerConsensusImp::statePreClose(), ripple::LedgerConsensusImp::statusChange(), ripple::NetworkOPsImp::subLedger(), ripple::LedgerConsensusImp::takeInitialPosition(), ripple::RPC::transactionSign(), ripple::OrderBookDB::update(), and ripple::PathRequests::updateAll().
virtual LoadManager& ripple::Application::getLoadManager () pure virtual
Implemented in ripple::ApplicationImp.
Referenced by ripple::NetworkOPsImp::processHeartbeatTimer(), and ripple::ApplicationImp::run().
virtual LocalCredentials& ripple::Application::getLocalCredentials () pure virtual
Implemented in ripple::ApplicationImp.
Referenced by ripple::UniqueNodeListImp::addClusterStatus(), ripple::NetworkOPsImp::checkLastClosedLedger(), ripple::NetworkOPsImp::getServerInfo(), and ripple::PeerImp::sendHello().
virtual LockType& ripple::Application::getMasterLock () pure virtual
Implemented in ripple::ApplicationImp.
virtual TransactionMaster& ripple::Application::getMasterTransaction () pure virtual
Implemented in ripple::ApplicationImp.
Referenced by ripple::RPCHandler::doTx(), ripple::TransactionMaster::fetch(), ripple::Ledger::getTransaction(), ripple::ConsensusTransSetSF::haveNode(), ripple::NetworkOPsImp::processTransactionCb(), ripple::NetworkOPsImp::runTransactionQueue(), and ripple::Ledger::saveValidatedLedger().
virtual NodeStore::Database& ripple::Application::getNodeStore () pure virtual
Implemented in ripple::ApplicationImp.
Referenced by ripple::RPCHandler::doGetCounts(), ripple::SHAMap::flushDirty(), ripple::SHAMap::getMissingNodes(), ripple::SHAMap::getNodeAsync(), ripple::AccountStateSF::gotNode(), ripple::TransactionStateSF::gotNode(), ripple::PeerImp::recvGetObjectByHash(), ripple::Ledger::saveValidatedLedger(), ripple::InboundLedger::takeBase(), ripple::InboundLedger::tryLocal(), and ripple::ApplicationImp::updateTables().
virtual NetworkOPs& ripple::Application::getOPs () pure virtual
Implemented in ripple::ApplicationImp.
Referenced by ripple::LedgerConsensusImp::accept(), ripple::UniqueNodeListImp::addClusterStatus(), ripple::ValidationsImp::addValidation(), ripple::ChangeTransactor::applyFeature(), ripple::LedgerConsensusImp::beginAccept(), ripple::LedgerConsensusImp::checkLCL(), ripple::LedgerConsensusImp::checkOurValidation(), ripple::PeerImp::checkPropose(), ripple::PeerImp::checkTransaction(), ripple::LedgerConsensusImp::closeLedger(), ripple::LedgerMasterImp::doAdvance(), ripple::PeerImp::doFetchPack(), ripple::RPCHandler::doGetCounts(), ripple::LedgerMasterImp::doTransaction(), ripple::LedgerConsensusImp::endConsensus(), ripple::UniqueNodeListImp::getClusterFee(), ripple::ValidationsImp::getCurrentTrustedValidations(), ripple::ValidationsImp::getCurrentValidations(), ripple::PeerImp::getLedger(), ripple::LedgerMasterImp::getPublishedLedgerAge(), ripple::NetworkOPsImp::getServerInfo(), ripple::LedgerMasterImp::getValidatedLedgerAge(), ripple::ValidationsImp::getValidationCount(), ripple::InboundLedgersImp::gotStaleData(), ripple::AccountStateSF::haveNode(), ripple::TransactionStateSF::haveNode(), ripple::PathRequest::isValid(), ripple::LedgerConsensusImp::LedgerConsensusImp(), ripple::SHAMap::DefaultMissingNodeHandler::operator()(), ripple::LedgerConsensusImp::playbackProposals(), ripple::PeerImp::recvGetObjectByHash(), ripple::PeerImp::recvLedger(), ripple::PeerImp::recvPropose(), ripple::PeerImp::recvValidation(), ripple::LoadManagerImp::run(), ripple::LedgerMasterImp::setValidLedger(), ripple::LedgerConsensusImp::statePreClose(), ripple::LedgerConsensusImp::statusChange(), ripple::TACompletionHandler(), and ripple::LedgerMasterImp::updatePaths().
virtual OrderBookDB& ripple::Application::getOrderBookDB () pure virtual
Implemented in ripple::ApplicationImp.
Referenced by ripple::Pathfinder::addLink(), ripple::LedgerMasterImp::checkAccept(), ripple::LedgerMasterImp::findNewLedgersToPublish(), ripple::NetworkOPsImp::pubValidatedTransaction(), ripple::Ledger::qualityDirDescriber(), ripple::LedgerMasterImp::setFullLedger(), ripple::NetworkOPsImp::subBook(), and ripple::NetworkOPsImp::unsubBook().
virtual PathRequests& ripple::Application::getPathRequests () pure virtual
Implemented in ripple::ApplicationImp.
Referenced by ripple::RPCHandler::doPathFind(), ripple::RPCHandler::doRipplePathFind(), and ripple::LedgerMasterImp::updatePaths().
virtual ProofOfWorkFactory& ripple::Application::getProofOfWorkFactory () pure virtual
Implemented in ripple::ApplicationImp.
Referenced by ripple::RPCHandler::doProofCreate(), ripple::RPCHandler::doProofVerify(), and ripple::PeerImp::recvProofWork().
virtual Resource::Manager& ripple::Application::getResourceManager () pure virtual
Implemented in ripple::ApplicationImp.
Referenced by ripple::RPCHandler::doBlackList(), and ripple::NetworkOPsImp::processClusterTimer().
virtual DatabaseCon* ripple::Application::getRpcDB () pure virtual
Implemented in ripple::ApplicationImp.
Referenced by ripple::LocalCredentials::dataDelete(), ripple::LocalCredentials::dataFetch(), and ripple::LocalCredentials::dataStore().
virtual RPC::Manager& ripple::Application::getRPCManager () pure virtual
Implemented in ripple::ApplicationImp.
virtual SiteFiles::Manager& ripple::Application::getSiteFiles () pure virtual
Implemented in ripple::ApplicationImp.
virtual SLECache& ripple::Application::getSLECache () pure virtual
Implemented in ripple::ApplicationImp.
Referenced by ripple::RPCHandler::doGetCounts(), and ripple::Ledger::getSLEi().
virtual bool ripple::Application::getSystemTimeOffset (int & offset) pure virtual
Implemented in ripple::ApplicationImp.
Referenced by ripple::NetworkOPsImp::getNetworkTimePT().
virtual NodeCache& ripple::Application::getTempNodeCache () pure virtual
Implemented in ripple::ApplicationImp.
virtual DatabaseCon* ripple::Application::getTxnDB () pure virtual
Implemented in ripple::ApplicationImp.
Referenced by ripple::addTxnSeqField(), ripple::RPCHandler::doGetCounts(), ripple::RPCHandler::doTxHistory(), ripple::NetworkOPsImp::getAccountTxs(), ripple::NetworkOPsImp::getAccountTxsB(), ripple::NetworkOPsImp::getLedgerAffectedAccounts(), ripple::NetworkOPsImp::getTxsAccount(), ripple::NetworkOPsImp::getTxsAccountB(), ripple::Ledger::saveValidatedLedger(), ripple::ApplicationImp::setup(), and ripple::Transaction::transactionFromSQL().
virtual TxQueue& ripple::Application::getTxQueue () pure virtual
Implemented in ripple::ApplicationImp.
Referenced by ripple::NetworkOPsImp::runTransactionQueue().
virtual UniqueNodeList& ripple::Application::getUNL () pure virtual
Implemented in ripple::ApplicationImp.
Referenced by ripple::ValidationsImp::addValidation(), ripple::RPCHandler::doPeers(), ripple::RPCHandler::doUnlAdd(), ripple::RPCHandler::doUnlDelete(), ripple::RPCHandler::doUnlList(), ripple::RPCHandler::doUnlLoad(), ripple::RPCHandler::doUnlNetwork(), ripple::RPCHandler::doUnlReset(), ripple::RPCHandler::doUnlScore(), ripple::NetworkOPsImp::processClusterTimer(), ripple::PeerImp::recvCluster(), ripple::PeerImp::recvHello(), ripple::PeerImp::recvPropose(), ripple::PeerImp::recvValidation(), and ripple::LocalCredentials::start().
virtual Validations& ripple::Application::getValidations () pure virtual
Implemented in ripple::ApplicationImp.
Referenced by ripple::LedgerConsensusImp::accept(), ripple::LedgerMasterImp::checkAccept(), ripple::NetworkOPsImp::checkLastClosedLedger(), ripple::LedgerConsensusImp::checkLCL(), ripple::LedgerConsensusImp::checkOurValidation(), ripple::LedgerMasterImp::consensusBuilt(), ripple::FeaturesImpl::doVoting(), ripple::FeeVoteImpl::doVoting(), ripple::LedgerMasterImp::getNeededValidations(), ripple::LedgerConsensusImp::haveConsensus(), ripple::NetworkOPsImp::recvValidation(), and ripple::LedgerConsensusImp::statePreClose().
virtual Validators::Manager& ripple::Application::getValidators () pure virtual
Implemented in ripple::ApplicationImp.
Referenced by ripple::PeerImp::checkValidation(), and ripple::LedgerMasterImp::setFullLedger().
virtual DatabaseCon* ripple::Application::getWalletDB () pure virtual
Retrieve the "wallet database"
It looks like this is used to store the unique node list.
Implemented in ripple::ApplicationImp.
Referenced by ripple::UniqueNodeListImp::fetchNext(), ripple::FeaturesImpl::getCreate(), ripple::UniqueNodeListImp::getSeedDomains(), ripple::UniqueNodeListImp::getSeedNodes(), ripple::UniqueNodeListImp::getUnlJson(), ripple::UniqueNodeListImp::miscLoad(), ripple::UniqueNodeListImp::miscSave(), ripple::UniqueNodeListImp::nodeBootstrap(), ripple::LocalCredentials::nodeIdentityCreate(), ripple::LocalCredentials::nodeIdentityLoad(), ripple::UniqueNodeListImp::nodeRemoveDomain(), ripple::UniqueNodeListImp::nodeRemovePublic(), ripple::UniqueNodeListImp::nodeReset(), ripple::UniqueNodeListImp::processIps(), ripple::UniqueNodeListImp::processValidators(), ripple::FeaturesImpl::reportValidations(), ripple::UniqueNodeListImp::scoreCompute(), ripple::UniqueNodeListImp::setSeedDomains(), ripple::UniqueNodeListImp::setSeedNodes(), and ripple::UniqueNodeListImp::trustedLoad().
virtual bool ripple::Application::isShutdown () pure virtual
Implemented in ripple::ApplicationImp.
Referenced by ripple::LedgerMasterImp::tryFill().
virtual Overlay& ripple::Application::overlay () pure virtual
Implemented in ripple::ApplicationImp.
Referenced by ripple::LedgerConsensusImp::accept(), ripple::LedgerConsensusImp::addDisputedTransaction(), ripple::InboundLedger::addPeers(), ripple::LedgerConsensusImp::checkOurValidation(), ripple::RPCHandler::doConnect(), ripple::RPCHandler::doPeers(), ripple::NetworkOPsImp::endConsensus(), ripple::LedgerMasterImp::getFetchPack(), ripple::NetworkOPsImp::haveConsensusObject(), ripple::TransactionAcquire::onTimer(), ripple::LedgerConsensusImp::playbackProposals(), ripple::NetworkOPsImp::processClusterTimer(), ripple::NetworkOPsImp::processHeartbeatTimer(), ripple::NetworkOPsImp::processTransactionCb(), ripple::NetworkOPsImp::processTrustedProposal(), ripple::LedgerConsensusImp::propose(), ripple::NetworkOPsImp::runTransactionQueue(), ripple::LedgerConsensusImp::sendHaveTxSet(), ripple::LedgerConsensusImp::startAcquiring(), ripple::LedgerConsensusImp::statusChange(), and ripple::NetworkOPsImp::switchLastClosedLedger().
virtual void ripple::Application::run () pure virtual
Implemented in ripple::ApplicationImp.
Referenced by ripple::startServer().
virtual bool ripple::Application::running () pure virtual
Implemented in ripple::ApplicationImp.
virtual void ripple::Application::setup () pure virtual
Implemented in ripple::ApplicationImp.
Referenced by ripple::setupServer().
virtual void ripple::Application::signalStop () pure virtual
Implemented in ripple::ApplicationImp.
Referenced by ripple::RPCHandler::doStop(), ripple::ApplicationImp::onDeadlineTimer(), and ripple::ApplicationImp::setup().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/main/Application.h
rippled/src/ripple_app/main/Application.cpp