rippled: rocksdb::StressTest Class Reference
rocksdb::StressTest Class Reference
Public Member Functions
StressTest ()
~StressTest ()
void Run ()
Private Member Functions
Status MultiPut (ThreadState *thread, const WriteOptions &writeoptions, const Slice &key, const Slice &value, size_t sz)
Status MultiDelete (ThreadState *thread, const WriteOptions &writeoptions, const Slice &key)
Status MultiGet (ThreadState *thread, const ReadOptions &readoptions, const Slice &key, std::string *value)
Status MultiPrefixScan (ThreadState *thread, const ReadOptions &readoptions, const Slice &prefix)
Status MultiIterate (ThreadState *thread, const ReadOptions &readoptions, const Slice &key)
void OperateDb (ThreadState *thread)
void VerifyDb (ThreadState *thread) const
void VerificationAbort (std::string msg, long key) const
void VerifyValue (long key, const ReadOptions &opts, const SharedState &shared, const std::string &value_from_db, Status s, bool strict=false) const
void PrintEnv () const
void Open ()
void Reopen ()
void PrintStatistics ()
Static Private Member Functions
static void ThreadBody (void *v)
static void PrintKeyValue (uint32_t key, const char *value, size_t sz)
static size_t GenerateValue (uint32_t rand, char *v, size_t max_sz)
Private Attributes
shared_ptr< Cache > cache_
shared_ptr< Cache > compressed_cache_
const FilterPolicy * filter_policy_
const SliceTransform * prefix_extractor_
DB * db_
StackableDB * sdb_
int num_times_reopened_
Detailed Description
Definition at line 678 of file db_stress.cc.
Constructor & Destructor Documentation
rocksdb::StressTest::StressTest () inline
Definition at line 680 of file db_stress.cc.
References rocksdb::Env::DeleteFile(), rocksdb::DestroyDB(), rocksdb::Env::GetChildren(), and rocksdb::Slice::starts_with().
       : cache_(NewLRUCache(FLAGS_cache_size)),
         compressed_cache_(FLAGS_compressed_cache_size >= 0 ?
                           NewLRUCache(FLAGS_compressed_cache_size) :
                           nullptr),
         filter_policy_(FLAGS_bloom_bits >= 0
                        ? NewBloomFilterPolicy(FLAGS_bloom_bits)
                        : nullptr),
         prefix_extractor_(NewFixedPrefixTransform(
                           FLAGS_test_batches_snapshots ?
                           sizeof(long) : sizeof(long)-1)),
         db_(nullptr),
         num_times_reopened_(0) {
     if (FLAGS_destroy_db_initially) {
       std::vector<std::string> files;
       FLAGS_env->GetChildren(FLAGS_db, &files);
       for (unsigned int i = 0; i < files.size(); i++) {
         if (Slice(files[i]).starts_with("heap-")) {
           FLAGS_env->DeleteFile(FLAGS_db + "/" + files[i]);
         }
       }
       DestroyDB(FLAGS_db, Options());
     }
   }
rocksdb::StressTest::~StressTest () inline
Definition at line 705 of file db_stress.cc.
References db_, filter_policy_, and prefix_extractor_.
                 {
     delete db_;
     delete filter_policy_;
     delete prefix_extractor_;
   }
Member Function Documentation
static size_t rocksdb::StressTest::GenerateValue (uint32_t rand, char * v, size_t max_sz) inline static private
Definition at line 1271 of file db_stress.cc.
References rand.
Referenced by OperateDb(), and VerifyValue().
{
     size_t value_sz = ((rand % 3) + 1) * FLAGS_value_size_mult;
     assert(value_sz <= max_sz && value_sz >= sizeof(uint32_t));
     *((uint32_t*)v) = rand;
     for (size_t i=sizeof(uint32_t); i < value_sz; i++) {
       v[i] = (char)(rand ^ i);
     }
     v[value_sz] = '\0';
     return value_sz; // the size of the value set.
   }
Status rocksdb::StressTest::MultiDelete (ThreadState * thread, const WriteOptions & writeoptions, const Slice & key) inline private
Definition at line 856 of file db_stress.cc.
References db_, rocksdb::WriteBatch::Delete(), rocksdb::Status::ok(), rocksdb::Slice::ToString(), rocksdb::Status::ToString(), and rocksdb::DB::Write().
Referenced by OperateDb().
{
     std::string keys[10] = {"9", "7", "5", "3", "1",
                             "8", "6", "4", "2", "0"};
     WriteBatch batch;
     Status s;
     for (int i = 0; i < 10; i++) {
       keys[i] += key.ToString();
       batch.Delete(keys[i]);
     }
     s = db_->Write(writeoptions, &batch);
     if (!s.ok()) {
       fprintf(stderr, "multidelete error: %s\n", s.ToString().c_str());
       thread->stats.AddErrors(1);
     } else {
       thread->stats.AddDeletes(10);
     }
     return s;
   }
Status rocksdb::StressTest::MultiGet (ThreadState * thread, const ReadOptions & readoptions, const Slice & key, std::string * value) inline private
Definition at line 884 of file db_stress.cc.
References db_, rocksdb::DB::Get(), rocksdb::DB::GetSnapshot(), rocksdb::Status::IsNotFound(), rocksdb::Status::ok(), rocksdb::DB::ReleaseSnapshot(), rocksdb::ReadOptions::snapshot, rocksdb::Slice::ToString(), rocksdb::Status::ToString(), and value.
Referenced by OperateDb().
{
     std::string keys[10] = {"0", "1", "2", "3", "4", "5", "6", "7", "8", "9"};
     Slice key_slices[10];
     std::string values[10];
     ReadOptions readoptionscopy = readoptions;
     readoptionscopy.snapshot = db_->GetSnapshot();
     Status s;
     for (int i = 0; i < 10; i++) {
       keys[i] += key.ToString();
       key_slices[i] = keys[i];
       s = db_->Get(readoptionscopy, key_slices[i], value);
       if (!s.ok() && !s.IsNotFound()) {
         fprintf(stderr, "get error: %s\n", s.ToString().c_str());
         values[i] = "";
         thread->stats.AddErrors(1);
         // we continue after error rather than exiting so that we can
         // find more errors if any
       } else if (s.IsNotFound()) {
         values[i] = "";
         thread->stats.AddGets(1, 0);
       } else {
         values[i] = *value;
         char expected_prefix = (keys[i])[0];
         char actual_prefix = (values[i])[0];
         if (actual_prefix != expected_prefix) {
           fprintf(stderr, "error expected prefix = %c actual = %c\n",
                   expected_prefix, actual_prefix);
         }
         (values[i])[0] = ' '; // blank out the differing character
         thread->stats.AddGets(1, 1);
       }
     }
     db_->ReleaseSnapshot(readoptionscopy.snapshot);
     // Now that we retrieved all values, check that they all match
     for (int i = 1; i < 10; i++) {
       if (values[i] != values[0]) {
         fprintf(stderr, "error : inconsistent values for key %s: %s, %s\n",
                 key.ToString().c_str(), values[0].c_str(),
                 values[i].c_str());
       // we continue after error rather than exiting so that we can
       // find more errors if any
       }
     }
     return s;
   }
Status rocksdb::StressTest::MultiIterate (ThreadState * thread, const ReadOptions & readoptions, const Slice & key) inline private
Definition at line 1013 of file db_stress.cc.
References db_, rocksdb::DB::GetSnapshot(), rocksdb::DB::NewIterator(), rocksdb::Status::ok(), rocksdb::DB::ReleaseSnapshot(), and rocksdb::ReadOptions::snapshot.
Referenced by OperateDb().
{
     Status s;
     const Snapshot* snapshot = db_->GetSnapshot();
     ReadOptions readoptionscopy = readoptions;
     readoptionscopy.snapshot = snapshot;
     unique_ptr<Iterator> iter(db_->NewIterator(readoptionscopy));
     iter->Seek(key);
     for (uint64_t i = 0; i < FLAGS_num_iterations && iter->Valid(); i++) {
       if (thread->rand.OneIn(2)) {
         iter->Next();
       } else {
         iter->Prev();
       }
     }
     if (s.ok()) {
       thread->stats.AddIterations(1);
     } else {
       thread->stats.AddErrors(1);
     }
     db_->ReleaseSnapshot(snapshot);
     return s;
   }
Status rocksdb::StressTest::MultiPrefixScan (ThreadState * thread, const ReadOptions & readoptions, const Slice & prefix) inline private
Definition at line 941 of file db_stress.cc.
References db_, rocksdb::DB::GetSnapshot(), rocksdb::DB::NewIterator(), rocksdb::Iterator::Next(), ripple::Resource::ok, rocksdb::Status::OK(), rocksdb::Status::ok(), rocksdb::ReadOptions::prefix, rocksdb::DB::ReleaseSnapshot(), rocksdb::Iterator::SeekToFirst(), rocksdb::ReadOptions::snapshot, rocksdb::Slice::ToString(), and rocksdb::Iterator::value().
Referenced by OperateDb().
{
     std::string prefixes[10] = {"0", "1", "2", "3", "4",
                                 "5", "6", "7", "8", "9"};
     Slice prefix_slices[10];
     ReadOptions readoptionscopy[10];
     const Snapshot* snapshot = db_->GetSnapshot();
     Iterator* iters[10];
     Status s = Status::OK();
     for (int i = 0; i < 10; i++) {
       prefixes[i] += prefix.ToString();
       prefix_slices[i] = prefixes[i];
       readoptionscopy[i] = readoptions;
       readoptionscopy[i].prefix = &prefix_slices[i];
       readoptionscopy[i].snapshot = snapshot;
       iters[i] = db_->NewIterator(readoptionscopy[i]);
       iters[i]->SeekToFirst();
     }
     int count = 0;
     while (iters[0]->Valid()) {
       count++;
       std::string values[10];
       // get list of all values for this iteration
       for (int i = 0; i < 10; i++) {
         // no iterator should finish before the first one
         assert(iters[i]->Valid());
         values[i] = iters[i]->value().ToString();
         char expected_first = (prefixes[i])[0];
         char actual_first = (values[i])[0];
         if (actual_first != expected_first) {
           fprintf(stderr, "error expected first = %c actual = %c\n",
                   expected_first, actual_first);
         }
         (values[i])[0] = ' '; // blank out the differing character
       }
       // make sure all values are equivalent
       for (int i = 0; i < 10; i++) {
         if (values[i] != values[0]) {
           fprintf(stderr, "error : inconsistent values for prefix %s: %s, %s\n",
                   prefix.ToString().c_str(), values[0].c_str(),
                   values[i].c_str());
           // we continue after error rather than exiting so that we can
           // find more errors if any
         }
         iters[i]->Next();
       }
     }
     // cleanup iterators and snapshot
     for (int i = 0; i < 10; i++) {
       // if the first iterator finished, they should have all finished
       assert(!iters[i]->Valid());
       assert(iters[i]->status().ok());
       delete iters[i];
     }
     db_->ReleaseSnapshot(snapshot);
     if (s.ok()) {
       thread->stats.AddPrefixes(1, count);
     } else {
       thread->stats.AddErrors(1);
     }
     return s;
   }
Status rocksdb::StressTest::MultiPut (ThreadState * thread, const WriteOptions & writeoptions, const Slice & key, const Slice & value, size_t sz) inline private
Definition at line 821 of file db_stress.cc.
References db_, rocksdb::WriteBatch::Merge(), rocksdb::Status::ok(), rocksdb::WriteBatch::Put(), rocksdb::Slice::ToString(), rocksdb::Status::ToString(), and rocksdb::DB::Write().
Referenced by OperateDb().
{
     std::string keys[10] = {"9", "8", "7", "6", "5",
                             "4", "3", "2", "1", "0"};
     std::string values[10] = {"9", "8", "7", "6", "5",
                               "4", "3", "2", "1", "0"};
     Slice value_slices[10];
     WriteBatch batch;
     Status s;
     for (int i = 0; i < 10; i++) {
       keys[i] += key.ToString();
       values[i] += value.ToString();
       value_slices[i] = values[i];
       if (FLAGS_use_merge) {
         batch.Merge(keys[i], value_slices[i]);
       } else {
         batch.Put(keys[i], value_slices[i]);
       }
     }
     s = db_->Write(writeoptions, &batch);
     if (!s.ok()) {
       fprintf(stderr, "multiput error: %s\n", s.ToString().c_str());
       thread->stats.AddErrors(1);
     } else {
       // we did 10 writes each of size sz + 1
       thread->stats.AddBytesForWrites(10, (sz + 1) * 10);
     }
     return s;
   }
void rocksdb::StressTest::Open () inline private
Definition at line 1357 of file db_stress.cc.
References rocksdb::Options::allow_mmap_reads, rocksdb::Options::block_cache, rocksdb::Options::block_cache_compressed, rocksdb::Options::block_size, cache_, rocksdb::Options::compaction_options_universal, rocksdb::Options::compaction_style, compressed_cache_, rocksdb::Options::compression, rocksdb::Options::create_if_missing, rocksdb::MergeOperators::CreatePutOperator(), db_, dbstats, rocksdb::Options::delete_obsolete_files_period_micros, rocksdb::Options::disable_seek_compaction, rocksdb::Options::disableDataSync, rocksdb::Options::env, rocksdb::Options::filter_deletes, rocksdb::Options::filter_policy, filter_policy_, FLAGS_compression_type_e, FLAGS_env, FLAGS_max_write_buffer_number, FLAGS_min_write_buffer_number_to_merge, FLAGS_write_buffer_size, kPrefixHash, kSkipList, kUnsorted, kVectorRep, rocksdb::Options::level0_file_num_compaction_trigger, rocksdb::Options::level0_slowdown_writes_trigger, rocksdb::Options::level0_stop_writes_trigger, rocksdb::Options::max_background_compactions, rocksdb::Options::max_bytes_for_level_base, rocksdb::Options::max_bytes_for_level_multiplier, rocksdb::Options::max_manifest_file_size, rocksdb::CompactionOptionsUniversal::max_merge_width, rocksdb::Options::max_open_files, rocksdb::CompactionOptionsUniversal::max_size_amplification_percent, rocksdb::Options::max_write_buffer_number, rocksdb::Options::memtable_factory, rocksdb::Options::merge_operator, rocksdb::CompactionOptionsUniversal::min_merge_width, rocksdb::Options::min_write_buffer_number_to_merge, rocksdb::NewFixedPrefixTransform(), rocksdb::DB::Open(), rocksdb::UtilityDB::OpenTtlDB(), rocksdb::Options::prefix_extractor, prefix_extractor_, rocksdb::Options::purge_redundant_kvs_while_flush, sdb_, rocksdb::CompactionOptionsUniversal::size_ratio, rocksdb::Options::statistics, rocksdb::Options::target_file_size_base, rocksdb::Options::target_file_size_multiplier, rocksdb::Random::Uniform(), rocksdb::Options::use_fsync, and rocksdb::Options::write_buffer_size.
Referenced by Reopen(), and Run().
               {
     assert(db_ == nullptr);
     Options options;
     options.block_cache = cache_;
     options.block_cache_compressed = compressed_cache_;
     options.write_buffer_size = FLAGS_write_buffer_size;
     options.max_write_buffer_number = FLAGS_max_write_buffer_number;
     options.min_write_buffer_number_to_merge =
       FLAGS_min_write_buffer_number_to_merge;
     options.max_background_compactions = FLAGS_max_background_compactions;
     options.compaction_style =
       static_cast<rocksdb::CompactionStyle>(FLAGS_compaction_style);
     options.block_size = FLAGS_block_size;
     options.filter_policy = filter_policy_;
     options.prefix_extractor = prefix_extractor_;
     options.max_open_files = FLAGS_open_files;
     options.statistics = dbstats;
     options.env = FLAGS_env;
     options.disableDataSync = FLAGS_disable_data_sync;
     options.use_fsync = FLAGS_use_fsync;
     options.allow_mmap_reads = FLAGS_mmap_read;
     rocksdb_kill_odds = FLAGS_kill_random_test;
     options.target_file_size_base = FLAGS_target_file_size_base;
     options.target_file_size_multiplier = FLAGS_target_file_size_multiplier;
     options.max_bytes_for_level_base = FLAGS_max_bytes_for_level_base;
     options.max_bytes_for_level_multiplier =
         FLAGS_max_bytes_for_level_multiplier;
     options.level0_stop_writes_trigger = FLAGS_level0_stop_writes_trigger;
     options.level0_slowdown_writes_trigger =
       FLAGS_level0_slowdown_writes_trigger;
     options.level0_file_num_compaction_trigger =
       FLAGS_level0_file_num_compaction_trigger;
     options.compression = FLAGS_compression_type_e;
     options.create_if_missing = true;
     options.disable_seek_compaction = FLAGS_disable_seek_compaction;
     options.delete_obsolete_files_period_micros =
       FLAGS_delete_obsolete_files_period_micros;
     options.max_manifest_file_size = 1024;
     options.filter_deletes = FLAGS_filter_deletes;
     if ((FLAGS_prefix_size == 0) == (FLAGS_rep_factory == kPrefixHash)) {
       fprintf(stderr,
             "prefix_size should be non-zero iff memtablerep == prefix_hash\n");
       exit(1);
     }
     switch (FLAGS_rep_factory) {
       case kPrefixHash:
         options.memtable_factory.reset(
           new PrefixHashRepFactory(NewFixedPrefixTransform(FLAGS_prefix_size))
         );
         break;
       case kUnsorted:
         options.memtable_factory.reset(
           new UnsortedRepFactory()
         );
         break;
       case kSkipList:
         // no need to do anything
         break;
       case kVectorRep:
         options.memtable_factory.reset(
           new VectorRepFactory()
         );
         break;
     }
     static Random purge_percent(1000); // no benefit from non-determinism here
     if (static_cast<int32_t>(purge_percent.Uniform(100)) <
         FLAGS_purge_redundant_percent - 1) {
       options.purge_redundant_kvs_while_flush = false;
     }
     if (FLAGS_use_merge) {
       options.merge_operator = MergeOperators::CreatePutOperator();
     }
     // set universal style compaction configurations, if applicable
     if (FLAGS_universal_size_ratio != 0) {
       options.compaction_options_universal.size_ratio =
         FLAGS_universal_size_ratio;
     }
     if (FLAGS_universal_min_merge_width != 0) {
       options.compaction_options_universal.min_merge_width =
         FLAGS_universal_min_merge_width;
     }
     if (FLAGS_universal_max_merge_width != 0) {
       options.compaction_options_universal.max_merge_width =
         FLAGS_universal_max_merge_width;
     }
     if (FLAGS_universal_max_size_amplification_percent != 0) {
       options.compaction_options_universal.max_size_amplification_percent =
         FLAGS_universal_max_size_amplification_percent;
     }
     fprintf(stdout, "DB path: [%s]\n", FLAGS_db.c_str());
     Status s;
     if (FLAGS_ttl == -1) {
       s = DB::Open(options, FLAGS_db, &db_);
     } else {
       s = UtilityDB::OpenTtlDB(options, FLAGS_db, &sdb_, FLAGS_ttl);
       db_ = sdb_;
     }
     if (!s.ok()) {
       fprintf(stderr, "open error: %s\n", s.ToString().c_str());
       exit(1);
     }
   }
void rocksdb::StressTest::OperateDb (ThreadState * thread) inline private
Definition at line 1042 of file db_stress.cc.
References rocksdb::Slice::data(), db_, rocksdb::DB::Delete(), rocksdb::WriteOptions::disableWAL, GenerateValue(), rocksdb::DB::Get(), rocksdb::Status::IsNotFound(), rocksdb::Iterator::key(), rocksdb::DB::Merge(), MultiDelete(), MultiGet(), MultiIterate(), MultiPrefixScan(), MultiPut(), rocksdb::DB::NewIterator(), rocksdb::Iterator::Next(), rocksdb::Status::ok(), std::chrono::prefix, rocksdb::ReadOptions::prefix, PrintKeyValue(), rocksdb::DB::Put(), rocksdb::Iterator::SeekToFirst(), rocksdb::Slice::size(), rocksdb::Slice::starts_with(), rocksdb::Iterator::status(), rocksdb::WriteOptions::sync, rocksdb::Iterator::Valid(), value, and VerifyValue().
{
     ReadOptions read_opts(FLAGS_verify_checksum, true);
     WriteOptions write_opts;
     char value[100];
     long max_key = thread->shared->GetMaxKey();
     std::string from_db;
     if (FLAGS_sync) {
       write_opts.sync = true;
     }
     write_opts.disableWAL = FLAGS_disable_wal;
     const int prefixBound = (int)FLAGS_readpercent + (int)FLAGS_prefixpercent;
     const int writeBound = prefixBound + (int)FLAGS_writepercent;
     const int delBound = writeBound + (int)FLAGS_delpercent;
     thread->stats.Start();
     for (uint64_t i = 0; i < FLAGS_ops_per_thread; i++) {
       if(i != 0 && (i % (FLAGS_ops_per_thread / (FLAGS_reopen + 1))) == 0) {
         {
           thread->stats.FinishedSingleOp();
           MutexLock l(thread->shared->GetMutex());
           thread->shared->IncVotedReopen();
           if (thread->shared->AllVotedReopen()) {
             thread->shared->GetStressTest()->Reopen();
             thread->shared->GetCondVar()->SignalAll();
           }
           else {
             thread->shared->GetCondVar()->Wait();
           }
           // Commenting this out as we don't want to reset stats on each open.
           // thread->stats.Start();
         }
       }
       long rand_key = thread->rand.Next() % max_key;
       std::string keystr = Key(rand_key);
       Slice key = keystr;
       int prob_op = thread->rand.Uniform(100);
       if (prob_op >= 0 && prob_op < (int)FLAGS_readpercent) {
         // OPERATION read
         if (!FLAGS_test_batches_snapshots) {
           Status s = db_->Get(read_opts, key, &from_db);
           if (s.ok()) {
             // found case
             thread->stats.AddGets(1, 1);
           } else if (s.IsNotFound()) {
             // not found case
             thread->stats.AddGets(1, 0);
           } else {
             // errors case
             thread->stats.AddErrors(1);
           }
         } else {
           MultiGet(thread, read_opts, key, &from_db);
         }
       } else if ((int)FLAGS_readpercent <= prob_op && prob_op < prefixBound) {
         // OPERATION prefix scan
         // keys are longs (e.g., 8 bytes), so we let prefixes be
         // everything except the last byte.  So there will be 2^8=256
         // keys per prefix.
         Slice prefix = Slice(key.data(), key.size() - 1);
         if (!FLAGS_test_batches_snapshots) {
           read_opts.prefix = &prefix;
           Iterator* iter = db_->NewIterator(read_opts);
           int count = 0;
           for (iter->SeekToFirst(); iter->Valid(); iter->Next()) {
             assert(iter->key().starts_with(prefix));
             count++;
           }
           assert(count <= 256);
           if (iter->status().ok()) {
             thread->stats.AddPrefixes(1, count);
           } else {
             thread->stats.AddErrors(1);
           }
           delete iter;
         } else {
           MultiPrefixScan(thread, read_opts, prefix);
         }
         read_opts.prefix = nullptr;
       } else if (prefixBound <= prob_op && prob_op < writeBound) {
         // OPERATION write
         uint32_t value_base = thread->rand.Next();
         size_t sz = GenerateValue(value_base, value, sizeof(value));
         Slice v(value, sz);
         if (!FLAGS_test_batches_snapshots) {
           MutexLock l(thread->shared->GetMutexForKey(rand_key));
           if (FLAGS_verify_before_write) {
             std::string keystr2 = Key(rand_key);
             Slice k = keystr2;
             Status s = db_->Get(read_opts, k, &from_db);
             VerifyValue(rand_key,
                         read_opts,
                         *(thread->shared),
                         from_db,
                         s,
                         true);
           }
           thread->shared->Put(rand_key, value_base);
           if (FLAGS_use_merge) {
             db_->Merge(write_opts, key, v);
           } else {
             db_->Put(write_opts, key, v);
           }
           thread->stats.AddBytesForWrites(1, sz);
         } else {
           MultiPut(thread, write_opts, key, v, sz);
         }
         PrintKeyValue(rand_key, value, sz);
       } else if (writeBound <= prob_op && prob_op < delBound) {
         // OPERATION delete
         if (!FLAGS_test_batches_snapshots) {
           MutexLock l(thread->shared->GetMutexForKey(rand_key));
           thread->shared->Delete(rand_key);
           db_->Delete(write_opts, key);
           thread->stats.AddDeletes(1);
         } else {
           MultiDelete(thread, write_opts, key);
         }
       } else {
         // OPERATION iterate
         MultiIterate(thread, read_opts, key);
       }
       thread->stats.FinishedSingleOp();
     }
     thread->stats.Stop();
   }
void rocksdb::StressTest::PrintEnv () const inline private
Definition at line 1282 of file db_stress.cc.
References FLAGS_write_buffer_size, rocksdb::kBZip2Compression, rocksdb::kMajorVersion, rocksdb::kMinorVersion, rocksdb::kNoCompression, kPrefixHash, kSkipList, rocksdb::kSnappyCompression, kUnsorted, kVectorRep, rocksdb::kZlibCompression, and rocksdb::NumberToString().
Referenced by Run().
{
     fprintf(stdout, "LevelDB version     : %d.%d\n",
             kMajorVersion, kMinorVersion);
     fprintf(stdout, "Number of threads   : %d\n", FLAGS_threads);
     fprintf(stdout,
             "Ops per thread      : %lu\n",
             (unsigned long)FLAGS_ops_per_thread);
     std::string ttl_state("unused");
     if (FLAGS_ttl > 0) {
       ttl_state = NumberToString(FLAGS_ttl);
     }
     fprintf(stdout, "Time to live(sec)   : %s\n", ttl_state.c_str());
     fprintf(stdout, "Read percentage     : %d%%\n", FLAGS_readpercent);
     fprintf(stdout, "Prefix percentage   : %d%%\n", FLAGS_prefixpercent);
     fprintf(stdout, "Write percentage    : %d%%\n", FLAGS_writepercent);
     fprintf(stdout, "Delete percentage   : %d%%\n", FLAGS_delpercent);
     fprintf(stdout, "Iterate percentage  : %d%%\n", FLAGS_iterpercent);
     fprintf(stdout, "Write-buffer-size   : %d\n", FLAGS_write_buffer_size);
     fprintf(stdout,
             "Iterations          : %lu\n",
             (unsigned long)FLAGS_num_iterations);
     fprintf(stdout,
             "Max key             : %lu\n",
             (unsigned long)FLAGS_max_key);
     fprintf(stdout, "Ratio #ops/#keys    : %f\n",
             (1.0 * FLAGS_ops_per_thread * FLAGS_threads)/FLAGS_max_key);
     fprintf(stdout, "Num times DB reopens: %d\n", FLAGS_reopen);
     fprintf(stdout, "Batches/snapshots   : %d\n",
             FLAGS_test_batches_snapshots);
     fprintf(stdout, "Purge redundant %%   : %d\n",
             FLAGS_purge_redundant_percent);
     fprintf(stdout, "Deletes use filter  : %d\n",
             FLAGS_filter_deletes);
     fprintf(stdout, "Num keys per lock   : %d\n",
             1 << FLAGS_log2_keys_per_lock);
     const char* compression = "";
     switch (FLAGS_compression_type_e) {
       case rocksdb::kNoCompression:
         compression = "none";
         break;
       case rocksdb::kSnappyCompression:
         compression = "snappy";
         break;
       case rocksdb::kZlibCompression:
         compression = "zlib";
         break;
       case rocksdb::kBZip2Compression:
         compression = "bzip2";
         break;
     }
     fprintf(stdout, "Compression         : %s\n", compression);
     const char* memtablerep = "";
     switch (FLAGS_rep_factory) {
       case kSkipList:
         memtablerep = "skip_list";
         break;
       case kPrefixHash:
         memtablerep = "prefix_hash";
         break;
       case kUnsorted:
         memtablerep = "unsorted";
         break;
       case kVectorRep:
         memtablerep = "vector";
         break;
     }
     fprintf(stdout, "Memtablerep         : %s\n", memtablerep);
     fprintf(stdout, "------------------------------------------------\n");
   }
static void rocksdb::StressTest::PrintKeyValue (uint32_t key, const char * value, size_t sz) inline static private
Definition at line 1262 of file db_stress.cc.
Referenced by OperateDb(), and VerifyDb().
{
     if (!FLAGS_verbose) return;
     fprintf(stdout, "%u ==> (%u) ", key, (unsigned int)sz);
     for (size_t i=0; i<sz; i++) {
       fprintf(stdout, "%X", value[i]);
     }
     fprintf(stdout, "\n");
   }
void rocksdb::StressTest::PrintStatistics () inline private
Definition at line 1482 of file db_stress.cc.
Referenced by Run().
{
     if (dbstats) {
       fprintf(stdout, "STATISTICS:\n%s\n", dbstats->ToString().c_str());
     }
   }
void rocksdb::StressTest::Reopen () inline private
Definition at line 1464 of file db_stress.cc.
References db_, rocksdb::Env::NowMicros(), num_times_reopened_, Open(), and rocksdb::Env::TimeToString().
                 {
     // do not close the db. Just delete the lock file. This
     // simulates a crash-recovery kind of situation.
     if (FLAGS_ttl != -1) {
       ((DBWithTTL*) db_)->TEST_Destroy_DBWithTtl();
     } else {
       ((DBImpl*) db_)->TEST_Destroy_DBImpl();
     }
     db_ = nullptr;
     num_times_reopened_++;
     double now = FLAGS_env->NowMicros();
     fprintf(stdout, "%s Reopening database for the %dth time\n",
             FLAGS_env->TimeToString((uint64_t) now/1000000).c_str(),
             num_times_reopened_);
     Open();
   }
void rocksdb::StressTest::Run () inline
Definition at line 711 of file db_stress.cc.
References rocksdb::Env::NowMicros(), Open(), PrintEnv(), PrintStatistics(), shared, rocksdb::Env::StartThread(), stats, ThreadBody(), and rocksdb::Env::TimeToString().
Referenced by main().
              {
     PrintEnv();
     Open();
     SharedState shared(this);
     uint32_t n = shared.GetNumThreads();
     std::vector<ThreadState*> threads(n);
     for (uint32_t i = 0; i < n; i++) {
       threads[i] = new ThreadState(i, &shared);
       FLAGS_env->StartThread(ThreadBody, threads[i]);
     }
     // Each thread goes through the following states:
     // initializing -> wait for others to init -> read/populate/depopulate
     // wait for others to operate -> verify -> done
     {
       MutexLock l(shared.GetMutex());
       while (!shared.AllInitialized()) {
         shared.GetCondVar()->Wait();
       }
       double now = FLAGS_env->NowMicros();
       fprintf(stdout, "%s Starting database operations\n",
               FLAGS_env->TimeToString((uint64_t) now/1000000).c_str());
       shared.SetStart();
       shared.GetCondVar()->SignalAll();
       while (!shared.AllOperated()) {
         shared.GetCondVar()->Wait();
       }
       now = FLAGS_env->NowMicros();
       if (FLAGS_test_batches_snapshots) {
         fprintf(stdout, "%s Limited verification already done during gets\n",
                 FLAGS_env->TimeToString((uint64_t) now/1000000).c_str());
       } else {
         fprintf(stdout, "%s Starting verification\n",
                 FLAGS_env->TimeToString((uint64_t) now/1000000).c_str());
       }
       shared.SetStartVerify();
       shared.GetCondVar()->SignalAll();
       while (!shared.AllDone()) {
         shared.GetCondVar()->Wait();
       }
     }
     for (unsigned int i = 1; i < n; i++) {
       threads[0]->stats.Merge(threads[i]->stats);
     }
     threads[0]->stats.Report("Stress Test");
     for (unsigned int i = 0; i < n; i++) {
       delete threads[i];
       threads[i] = nullptr;
     }
     double now = FLAGS_env->NowMicros();
     if (!FLAGS_test_batches_snapshots) {
       fprintf(stdout, "%s Verification successful\n",
               FLAGS_env->TimeToString((uint64_t) now/1000000).c_str());
     }
     PrintStatistics();
   }
static void rocksdb::StressTest::ThreadBody (void * v) inline static private
Definition at line 777 of file db_stress.cc.
References shared.
Referenced by Run().
{
     ThreadState* thread = reinterpret_cast<ThreadState*>(v);
     SharedState* shared = thread->shared;
     {
       MutexLock l(shared->GetMutex());
       shared->IncInitialized();
       if (shared->AllInitialized()) {
         shared->GetCondVar()->SignalAll();
       }
       while (!shared->Started()) {
         shared->GetCondVar()->Wait();
       }
     }
     thread->shared->GetStressTest()->OperateDb(thread);
     {
       MutexLock l(shared->GetMutex());
       shared->IncOperated();
       if (shared->AllOperated()) {
         shared->GetCondVar()->SignalAll();
       }
       while (!shared->VerifyStarted()) {
         shared->GetCondVar()->Wait();
       }
     }
     if (!FLAGS_test_batches_snapshots) {
       thread->shared->GetStressTest()->VerifyDb(thread);
     }
     {
       MutexLock l(shared->GetMutex());
       shared->IncDone();
       if (shared->AllDone()) {
         shared->GetCondVar()->SignalAll();
       }
     }
   }
void rocksdb::StressTest::VerificationAbort (std::string msg, long key) const inline private
Definition at line 1225 of file db_stress.cc.
Referenced by VerifyDb(), and VerifyValue().
{
     fprintf(stderr, "Verification failed for key %ld: %s\n",
             key, msg.c_str());
     exit(1);
   }
void rocksdb::StressTest::VerifyDb (ThreadState * thread) const inline private
Definition at line 1171 of file db_stress.cc.
References db_, rocksdb::DB::Get(), rocksdb::DB::NewIterator(), rocksdb::Status::NotFound(), PrintKeyValue(), shared, VerificationAbort(), and VerifyValue().
{
     ReadOptions options(FLAGS_verify_checksum, true);
     const SharedState& shared = *(thread->shared);
     static const long max_key = shared.GetMaxKey();
     static const long keys_per_thread = max_key / shared.GetNumThreads();
     long start = keys_per_thread * thread->tid;
     long end = start + keys_per_thread;
     if (thread->tid == shared.GetNumThreads() - 1) {
       end = max_key;
     }
     if (!thread->rand.OneIn(2)) {
       // Use iterator to verify this range
       unique_ptr<Iterator> iter(db_->NewIterator(options));
       iter->Seek(Key(start));
       for (long i = start; i < end; i++) {
         std::string from_db;
         std::string keystr = Key(i);
         Slice k = keystr;
         Status s = iter->status();
         if (iter->Valid()) {
           if (iter->key().compare(k) > 0) {
             s = Status::NotFound(Slice());
           } else if (iter->key().compare(k) == 0) {
             from_db = iter->value().ToString();
             iter->Next();
           } else if (iter->key().compare(k) < 0) {
             VerificationAbort("An out of range key was found", i);
           }
         } else {
           // The iterator found no value for the key in question, so do not
           // move to the next item in the iterator
           s = Status::NotFound(Slice());
         }
         VerifyValue(i, options, shared, from_db, s, true);
         if (from_db.length()) {
           PrintKeyValue(i, from_db.data(), from_db.length());
         }
       }
     }
     else {
       // Use Get to verify this range
       for (long i = start; i < end; i++) {
         std::string from_db;
         std::string keystr = Key(i);
         Slice k = keystr;
         Status s = db_->Get(options, k, &from_db);
         VerifyValue(i, options, shared, from_db, s, true);
         if (from_db.length()) {
           PrintKeyValue(i, from_db.data(), from_db.length());
         }
       }
     }
   }
void rocksdb::StressTest::VerifyValue (long key, const ReadOptions & opts, const SharedState & shared, const std::string & value_from_db, Status s, bool strict = false) const inline private
Definition at line 1231 of file db_stress.cc.
References GenerateValue(), rocksdb::Status::ok(), SENTINEL, value, and VerificationAbort().
Referenced by OperateDb(), and VerifyDb().
{
     // compare value_from_db with the value in the shared state
     char value[100];
     uint32_t value_base = shared.Get(key);
     if (value_base == SharedState::SENTINEL && !strict) {
       return;
     }
     if (s.ok()) {
       if (value_base == SharedState::SENTINEL) {
         VerificationAbort("Unexpected value found", key);
       }
       size_t sz = GenerateValue(value_base, value, sizeof(value));
       if (value_from_db.length() != sz) {
         VerificationAbort("Length of value read is not equal", key);
       }
       if (memcmp(value_from_db.data(), value, sz) != 0) {
         VerificationAbort("Contents of value read don't match", key);
       }
     } else {
       if (value_base != SharedState::SENTINEL) {
         VerificationAbort("Value not found", key);
       }
     }
   }
Member Data Documentation
shared_ptr<Cache> rocksdb::StressTest::cache_ private
Definition at line 1489 of file db_stress.cc.
Referenced by Open().
shared_ptr<Cache> rocksdb::StressTest::compressed_cache_ private
Definition at line 1490 of file db_stress.cc.
Referenced by Open().
DB* rocksdb::StressTest::db_ private
Definition at line 1493 of file db_stress.cc.
Referenced by MultiDelete(), MultiGet(), MultiIterate(), MultiPrefixScan(), MultiPut(), Open(), OperateDb(), Reopen(), VerifyDb(), and ~StressTest().
const FilterPolicy* rocksdb::StressTest::filter_policy_ private
Definition at line 1491 of file db_stress.cc.
Referenced by Open(), and ~StressTest().
int rocksdb::StressTest::num_times_reopened_ private
Definition at line 1495 of file db_stress.cc.
Referenced by Reopen().
const SliceTransform* rocksdb::StressTest::prefix_extractor_ private
Definition at line 1492 of file db_stress.cc.
Referenced by Open(), and ~StressTest().
StackableDB* rocksdb::StressTest::sdb_ private
Definition at line 1494 of file db_stress.cc.
Referenced by Open().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/tools/db_stress.cc