rippled: ripple::RippleSSLContext Class Reference
ripple::RippleSSLContext Class Reference
#include <RippleSSLContext.h>
Static Public Member Functions
static std::string getRawDHParams (int keySize)
static RippleSSLContext * createBare ()
static RippleSSLContext * createWebSocket ()
static RippleSSLContext * createAnonymous (std::string const &cipherList)
static RippleSSLContext * createAuthenticated (std::string key_file, std::string cert_file, std::string chain_file)
Protected Member Functions
RippleSSLContext (ContextType &context)
Protected Member Functions inherited from beast::asio::SSLContext
SSLContext (ContextType &context)
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Additional Inherited Members
Public Types inherited from beast::asio::SSLContext
typedef boost::asio::ssl::context ContextType
Public Member Functions inherited from beast::asio::SSLContext
virtual ~SSLContext ()
ContextType & get () noexcept
ContextType const & get () const noexcept
operator ContextType & () noexcept
operator ContextType const & () const noexcept
Protected Attributes inherited from beast::asio::SSLContext
ContextType & m_context
Detailed Description
The SSL contexts used by Ripple.
This is what Ripple uses for its secure connections. The ECDSA curve parameters are predefined and verified to be secure. The context is set to sslv23, Transport Layer Security / General. This is primarily used for peer to peer servers that don't care about certificates or identity verification.
Definition at line 36 of file RippleSSLContext.h.
Constructor & Destructor Documentation
ripple::RippleSSLContext::RippleSSLContext (ContextType & context) explicit protected
Definition at line 288 of file RippleSSLContext.cpp.
     : SSLContext (context)
 {
 }
Member Function Documentation
RippleSSLContext * ripple::RippleSSLContext::createAnonymous (std::string const & cipherList) static
Create a context that allows anonymous connections. No certificates are required. Peers use this context. If the cipher list is invalid, a fatal error is raised.
Definition at line 306 of file RippleSSLContext.cpp.
Referenced by ripple::MultiSocket_test::MultiSocketDetails::getSSLContext(), and ripple::ApplicationImp::setup().
 {
     std::unique_ptr <RippleSSLContextImp> context (new RippleSSLContextImp ());
     context->initAnonymous (cipherList);
     return context.release ();
 }
RippleSSLContext * ripple::RippleSSLContext::createAuthenticated (std::string key_file, std::string cert_file, std::string chain_file) static
Create a context with authentication requirements. This is used for WebSocket connections. The authentication credentials are loaded from the files with the specified names. If an error occurs, a fatal error is raised.
Definition at line 313 of file RippleSSLContext.cpp.
Referenced by ripple::RPCHTTPServerImp::RPCHTTPServerImp(), and ripple::ApplicationImp::setup().
 {
     std::unique_ptr <RippleSSLContextImp> context (new RippleSSLContextImp ());
     context->initAuthenticated (key_file, cert_file, chain_file);
     return context.release ();
 }
RippleSSLContext * ripple::RippleSSLContext::createBare () static
Creates a bare SSL context with just sslv23 set. This is used for RPC connections.
Definition at line 293 of file RippleSSLContext.cpp.
Referenced by ripple::RPCHTTPServerImp::RPCHTTPServerImp().
 {
     std::unique_ptr <RippleSSLContextImp> context (new RippleSSLContextImp ());
     return context.release ();
 }
RippleSSLContext * ripple::RippleSSLContext::createWebSocket () static
Creates a suitable for WebSocket without authentication. This is for WebSocket connections that don't use certificates.
Definition at line 299 of file RippleSSLContext.cpp.
Referenced by ripple::ApplicationImp::setup().
 {
     std::unique_ptr <RippleSSLContextImp> context (new RippleSSLContextImp ());
     context->initCommon ();
     return context.release ();
 }
std::string ripple::RippleSSLContext::getRawDHParams (int keySize) static
Retrieve raw DH parameters. This is in the format expected by the OpenSSL function d2i_DHparams. The vector is binary. An empty vector means the key size is unsupported.
Note
The string may contain nulls in the middle. Use size() to determine the actual size.
Definition at line 321 of file RippleSSLContext.cpp.
References ripple::RippleSSLContextImp::getRawDHParams().
Referenced by ripple::LocalCredentials::nodeIdentityCreate().
 {
     return RippleSSLContextImp::getRawDHParams (keySize);
 }
The documentation for this class was generated from the following files:
rippled/src/ripple/common/RippleSSLContext.h
rippled/src/ripple/common/impl/RippleSSLContext.cpp