rippled: beast::http::raw_parser Class Reference
beast::http::raw_parser Class Reference
#include <raw_parser.h>
Classes
struct callback
struct hooks_t
struct state_t
Public Types
enum message_type { request, response }
Public Member Functions
raw_parser (callback &cb)
~raw_parser ()
void reset (message_type type)
std::pair< error_code,
std::size_t > process_data (void const *in, std::size_t bytes)
error_code process_eof ()
Private Types
typedef boost::system::error_code error_code
typedef int(* data_cb_t)(state_t *, const char *at, size_t length)
typedef int(* cb_t)(state_t *)
Private Member Functions
int do_message_start ()
int do_url (char const *in, std::size_t bytes)
int do_status (char const *in, std::size_t bytes)
int do_header_field (char const *in, std::size_t bytes)
int do_header_value (char const *in, std::size_t bytes)
int do_headers_done ()
int do_body (char const *in, std::size_t bytes)
int do_message_complete ()
Static Private Member Functions
static int on_message_start (joyent::http_parser *)
static int on_url (joyent::http_parser *, char const *, std::size_t)
static int on_status (joyent::http_parser *, char const *, std::size_t)
static int on_header_field (joyent::http_parser *, char const *, std::size_t)
static int on_header_value (joyent::http_parser *, char const *, std::size_t)
static int on_headers_done (joyent::http_parser *)
static int on_body (joyent::http_parser *, char const *, std::size_t)
static int on_message_complete (joyent::http_parser *)
Private Attributes
std::reference_wrapper< callback > m_cb
error_code m_ec
char m_state [sizeof(state_t)]
char m_hooks [sizeof(hooks_t)]
Detailed Description
Raw HTTP message parser. This is implemented using a zero-allocation state machine. The caller is responsible for all buffer management.
Definition at line 43 of file raw_parser.h.
Member Typedef Documentation
typedef int(* beast::http::raw_parser::cb_t)(state_t *) private
Definition at line 179 of file raw_parser.h.
typedef int(* beast::http::raw_parser::data_cb_t)(state_t *, const char *at, size_t length) private
Definition at line 177 of file raw_parser.h.
typedef boost::system::error_code beast::http::raw_parser::error_code private
Definition at line 46 of file raw_parser.h.
Member Enumeration Documentation
enum beast::http::raw_parser::message_type
Enumerator
request
response
Definition at line 49 of file raw_parser.h.
     {
         request,
         response
     };
Constructor & Destructor Documentation
beast::http::raw_parser::raw_parser (callback & cb) explicit
Definition at line 29 of file raw_parser.cpp.
References m_hooks, m_state, on_body(), on_header_field(), on_header_value(), on_headers_done(), on_message_complete(), on_message_start(), on_status(), and on_url().
     : m_cb (cb)
 {
     static_assert (sizeof(joyent::http_parser) == sizeof(state_t),
         "state_t size must match http_parser size");
     static_assert (sizeof(joyent::http_parser_settings) == sizeof(hooks_t),
         "hooks_t size must match http_parser_settings size");
     auto s (reinterpret_cast <joyent::http_parser*> (&m_state));
     s->data = this;
     auto h (reinterpret_cast <joyent::http_parser_settings*> (&m_hooks));
     h->on_message_begin = &raw_parser::on_message_start;
     h->on_url = &raw_parser::on_url;
     h->on_status = &raw_parser::on_status;
     h->on_header_field = &raw_parser::on_header_field;
     h->on_header_value = &raw_parser::on_header_value;
     h->on_headers_complete = &raw_parser::on_headers_done;
     h->on_body = &raw_parser::on_body;
     h->on_message_complete = &raw_parser::on_message_complete;
 }
beast::http::raw_parser::~raw_parser ()
Definition at line 52 of file raw_parser.cpp.
 {
 }
Member Function Documentation
int beast::http::raw_parser::do_body (char const * in, std::size_t bytes) private
Definition at line 137 of file raw_parser.cpp.
References beast::joyent::http_body_is_final(), m_cb, m_ec, and m_state.
Referenced by on_body().
 {
     auto const p (reinterpret_cast <joyent::http_parser const*> (&m_state));
     bool const is_final (
         joyent::http_body_is_final (p) != 0);
     m_ec = m_cb.get().on_body (is_final, in, bytes);
     return m_ec ? 1 : 0;
 }
int beast::http::raw_parser::do_header_field (char const * in, std::size_t bytes) private
Definition at line 114 of file raw_parser.cpp.
References m_cb, and m_ec.
Referenced by on_header_field().
 {
     m_ec = m_cb.get().on_header_field (in, bytes);
     return m_ec ? 1 : 0;
 }
int beast::http::raw_parser::do_header_value (char const * in, std::size_t bytes) private
Definition at line 121 of file raw_parser.cpp.
References m_cb, and m_ec.
Referenced by on_header_value().
 {
     m_ec = m_cb.get().on_header_value (in, bytes);
     return m_ec ? 1 : 0;
 }
int beast::http::raw_parser::do_headers_done () private
Definition at line 128 of file raw_parser.cpp.
References beast::joyent::http_should_keep_alive(), m_cb, m_ec, and m_state.
Referenced by on_headers_done().
 {
     auto const p (reinterpret_cast <joyent::http_parser const*> (&m_state));
     bool const keep_alive (joyent::http_should_keep_alive (p) != 0);
     m_ec = m_cb.get().on_headers_done (keep_alive);
     return m_ec ? 1 : 0;
 }
int beast::http::raw_parser::do_message_complete () private
Definition at line 147 of file raw_parser.cpp.
References beast::joyent::http_should_keep_alive(), m_cb, m_ec, and m_state.
Referenced by on_message_complete().
 {
     auto const p (reinterpret_cast <joyent::http_parser const*> (&m_state));
     bool const keep_alive (joyent::http_should_keep_alive (p) != 0);
     m_ec = m_cb.get().on_message_complete (keep_alive);
     return m_ec ? 1 : 0;
 }
int beast::http::raw_parser::do_message_start () private
Definition at line 88 of file raw_parser.cpp.
References beast::joyent::HTTP_REQUEST, beast::joyent::HTTP_RESPONSE, m_cb, m_ec, and m_state.
Referenced by on_message_start().
 {
     auto const p (reinterpret_cast <joyent::http_parser const*> (&m_state));
     if (p->type == joyent::HTTP_REQUEST)
         m_ec = m_cb.get().on_request ();
     else if (p->type == joyent::HTTP_RESPONSE)
         m_ec = m_cb.get().on_response ();
     return m_ec ? 1 : 0;
 }
int beast::http::raw_parser::do_status (char const * in, std::size_t bytes) private
Definition at line 106 of file raw_parser.cpp.
References m_cb, m_ec, and m_state.
Referenced by on_status().
 {
     auto const p (reinterpret_cast <joyent::http_parser const*> (&m_state));
     m_ec = m_cb.get().on_status (p->status_code, in, bytes);
     return m_ec ? 1 : 0;
 }
int beast::http::raw_parser::do_url (char const * in, std::size_t bytes) private
Definition at line 99 of file raw_parser.cpp.
References m_cb, and m_ec.
Referenced by on_url().
 {
     m_ec = m_cb.get().on_url (in, bytes);
     return m_ec ? 1 : 0;
 }
int beast::http::raw_parser::on_body (joyent::http_parser * p, char const * in, std::size_t bytes) static private
Definition at line 204 of file raw_parser.cpp.
References beast::joyent::http_parser::data, and do_body().
Referenced by raw_parser().
 {
     return reinterpret_cast <raw_parser*> (
         p->data)->do_body (
             in, bytes);
 }
int beast::http::raw_parser::on_header_field (joyent::http_parser * p, char const * in, std::size_t bytes) static private
Definition at line 181 of file raw_parser.cpp.
References beast::joyent::http_parser::data, and do_header_field().
Referenced by raw_parser().
 {
     return reinterpret_cast <raw_parser*> (
         p->data)->do_header_field (in, bytes);
 }
int beast::http::raw_parser::on_header_value (joyent::http_parser * p, char const * in, std::size_t bytes) static private
Definition at line 189 of file raw_parser.cpp.
References beast::joyent::http_parser::data, and do_header_value().
Referenced by raw_parser().
 {
     return reinterpret_cast <raw_parser*> (
         p->data)->do_header_value (in, bytes);
 }
int beast::http::raw_parser::on_headers_done (joyent::http_parser * p) static private
Definition at line 197 of file raw_parser.cpp.
References beast::joyent::http_parser::data, and do_headers_done().
Referenced by raw_parser().
 {
     return reinterpret_cast <raw_parser*> (
         p->data)->do_headers_done();
 }
int beast::http::raw_parser::on_message_complete (joyent::http_parser * p) static private
Definition at line 213 of file raw_parser.cpp.
References beast::joyent::http_parser::data, and do_message_complete().
Referenced by raw_parser().
 {
     return reinterpret_cast <raw_parser*> (
         p->data)->do_message_complete();
 }
int beast::http::raw_parser::on_message_start (joyent::http_parser * p) static private
Definition at line 158 of file raw_parser.cpp.
References beast::joyent::http_parser::data, and do_message_start().
Referenced by raw_parser().
 {
     return reinterpret_cast <raw_parser*> (
         p->data)->do_message_start();
 }
int beast::http::raw_parser::on_status (joyent::http_parser * p, char const * in, std::size_t bytes) static private
Definition at line 173 of file raw_parser.cpp.
References beast::joyent::http_parser::data, and do_status().
Referenced by raw_parser().
 {
     return reinterpret_cast <raw_parser*> (
         p->data)->do_status (in, bytes);
 }
int beast::http::raw_parser::on_url (joyent::http_parser * p, char const * in, std::size_t bytes) static private
Definition at line 165 of file raw_parser.cpp.
References beast::joyent::http_parser::data, and do_url().
Referenced by raw_parser().
 {
     return reinterpret_cast <raw_parser*> (
         p->data)->do_url (in, bytes);
 }
auto beast::http::raw_parser::process_data (void const * in, std::size_t bytes)
Processs message data. The return value includes the error code if any, and the number of bytes consumed in the input sequence.
Definition at line 65 of file raw_parser.cpp.
References beast::joyent::http_parser_execute().
 {
     auto s (reinterpret_cast <joyent::http_parser*> (&m_state));
     auto h (reinterpret_cast <joyent::http_parser_settings const*> (&m_hooks));
     std::size_t const bytes_used (joyent::http_parser_execute (s, h,
         static_cast <const char*> (buf), bytes));
     return std::make_pair (m_ec, bytes_used);;
 }
auto beast::http::raw_parser::process_eof ()
Notify the parser the end of the data is reached. Normally this will be called in response to the remote end closing down its half of the connection.
Definition at line 76 of file raw_parser.cpp.
References beast::joyent::http_parser_execute().
 {
     auto s (reinterpret_cast <joyent::http_parser*> (&m_state));
     auto h (reinterpret_cast <joyent::http_parser_settings const*> (&m_hooks));
     joyent::http_parser_execute (s, h, nullptr, 0);
     return m_ec;
 }
void beast::http::raw_parser::reset (message_type type)
Prepare to parse a new message. The previous state information, if any, is discarded.
Definition at line 57 of file raw_parser.cpp.
References http_parser_init(), beast::joyent::HTTP_REQUEST, beast::joyent::HTTP_RESPONSE, m_state, and request.
 {
     auto s (reinterpret_cast <joyent::http_parser*> (&m_state));
     http_parser_init (s, (type == request)
         ? joyent::HTTP_REQUEST : joyent::HTTP_RESPONSE);
 }
Member Data Documentation
std::reference_wrapper<callback> beast::http::raw_parser::m_cb private
Definition at line 193 of file raw_parser.h.
Referenced by do_body(), do_header_field(), do_header_value(), do_headers_done(), do_message_complete(), do_message_start(), do_status(), and do_url().
error_code beast::http::raw_parser::m_ec private
Definition at line 194 of file raw_parser.h.
Referenced by do_body(), do_header_field(), do_header_value(), do_headers_done(), do_message_complete(), do_message_start(), do_status(), and do_url().
char beast::http::raw_parser::m_hooks[sizeof(hooks_t)] private
Definition at line 196 of file raw_parser.h.
Referenced by raw_parser().
char beast::http::raw_parser::m_state[sizeof(state_t)] private
Definition at line 195 of file raw_parser.h.
Referenced by do_body(), do_headers_done(), do_message_complete(), do_message_start(), do_status(), raw_parser(), and reset().
The documentation for this class was generated from the following files:
rippled/src/beast/beast/http/raw_parser.h
rippled/src/beast/beast/http/impl/raw_parser.cpp