rippled: ripple::DecayingSample< Window, Value, Elapsed > Class Template Reference
ripple::DecayingSample< Window, Value, Elapsed > Class Template Reference
#include <DecayingSample.h>
Public Types
typedef Value value_type
typedef Elapsed elapsed_type
Public Member Functions
DecayingSample ()
Value add (value_type value, elapsed_type now)
Value value (elapsed_type now)
Private Member Functions
void decay (elapsed_type now)
Private Attributes
value_type m_value
elapsed_type m_when
Detailed Description
template<int Window, typename Value = int, typename Elapsed = int>
class ripple::DecayingSample< Window, Value, Elapsed >
Sampling function using exponential decay to provide a continuous value.
Definition at line 29 of file DecayingSample.h.
Member Typedef Documentation
template<int Window, typename Value = int, typename Elapsed = int> typedef Elapsed ripple::DecayingSample< Window, Value, Elapsed >::elapsed_type
Definition at line 33 of file DecayingSample.h.
template<int Window, typename Value = int, typename Elapsed = int> typedef Value ripple::DecayingSample< Window, Value, Elapsed >::value_type
Definition at line 32 of file DecayingSample.h.
Constructor & Destructor Documentation
template<int Window, typename Value = int, typename Elapsed = int> ripple::DecayingSample< Window, Value, Elapsed >::DecayingSample () inline
Create a default constructed sample.
Definition at line 36 of file DecayingSample.h.
         : m_value (value_type())
         , m_when (elapsed_type())
     {
     }
Member Function Documentation
template<int Window, typename Value = int, typename Elapsed = int> Value ripple::DecayingSample< Window, Value, Elapsed >::add (value_type value, elapsed_type now) inline
Add a new sample. The value is first aged according to the specified time.
Definition at line 45 of file DecayingSample.h.
Referenced by ripple::Resource::Entry::add().
     {
         decay (now);
         m_value += value;
         return m_value / Window;
     }
template<int Window, typename Value = int, typename Elapsed = int> void ripple::DecayingSample< Window, Value, Elapsed >::decay (elapsed_type now) inline private
Definition at line 63 of file DecayingSample.h.
Referenced by ripple::DecayingSample< decayWindowSeconds >::add(), and ripple::DecayingSample< decayWindowSeconds >::value().
     {
         if (now == m_when)
             return;
         if (m_value != value_type())
         {
             elapsed_type n (now - m_when);
             // A span larger than four times the window decays the
             // value to an insignificant amount so just reset it.
             //
             if (n > 4 * Window)
                 m_value = value_type();
             else
             {
                 while (n--)
                     m_value -= (m_value + Window - 1) / Window;
             }
         }
         m_when = now;
     }
template<int Window, typename Value = int, typename Elapsed = int> Value ripple::DecayingSample< Window, Value, Elapsed >::value (elapsed_type now) inline
Retrieve the current value in normalized units. The samples are first aged according to the specified time.
Definition at line 55 of file DecayingSample.h.
Referenced by ripple::DecayingSample< decayWindowSeconds >::add(), and ripple::Resource::Entry::balance().
     {
         decay (now);
         return m_value / Window;
     }
Member Data Documentation
template<int Window, typename Value = int, typename Elapsed = int> value_type ripple::DecayingSample< Window, Value, Elapsed >::m_value private
Definition at line 88 of file DecayingSample.h.
Referenced by ripple::DecayingSample< decayWindowSeconds >::add(), ripple::DecayingSample< decayWindowSeconds >::decay(), and ripple::DecayingSample< decayWindowSeconds >::value().
template<int Window, typename Value = int, typename Elapsed = int> elapsed_type ripple::DecayingSample< Window, Value, Elapsed >::m_when private
Definition at line 91 of file DecayingSample.h.
Referenced by ripple::DecayingSample< decayWindowSeconds >::decay().
The documentation for this class was generated from the following file:
rippled/src/ripple/algorithm/api/DecayingSample.h