rippled: beast::insight::detail::StatsDGaugeImpl Class Reference
beast::insight::detail::StatsDGaugeImpl Class Reference
Public Member Functions
StatsDGaugeImpl (std::string const &name, std::shared_ptr< StatsDCollectorImp > const &impl)
~StatsDGaugeImpl ()
void set (GaugeImpl::value_type value)
void increment (GaugeImpl::difference_type amount)
void flush ()
void do_set (GaugeImpl::value_type value)
void do_increment (GaugeImpl::difference_type amount)
void do_process ()
Public Member Functions inherited from beast::insight::GaugeImpl
virtual ~GaugeImpl ()=0
Public Member Functions inherited from beast::insight::BaseImpl
virtual ~BaseImpl ()=0
Private Member Functions
StatsDGaugeImpl & operator= (StatsDGaugeImpl const &)
Private Attributes
std::shared_ptr
< StatsDCollectorImp > m_impl
std::string m_name
GaugeImpl::value_type m_last_value
GaugeImpl::value_type m_value
bool m_dirty
Additional Inherited Members
Public Types inherited from beast::insight::GaugeImpl
typedef std::uint64_t value_type
typedef std::int64_t difference_type
Detailed Description
Definition at line 129 of file StatsDCollector.cpp.
Constructor & Destructor Documentation
beast::insight::detail::StatsDGaugeImpl::StatsDGaugeImpl (std::string const & name, std::shared_ptr< StatsDCollectorImp > const & impl)
Definition at line 559 of file StatsDCollector.cpp.
References m_impl.
     : m_impl (impl)
     , m_name (name)
     , m_last_value (0)
     , m_value (0)
     , m_dirty (false)
 {
     m_impl->add (*this);
 }
beast::insight::detail::StatsDGaugeImpl::~StatsDGaugeImpl ()
Definition at line 570 of file StatsDCollector.cpp.
References m_impl.
 {
     m_impl->remove (*this);
 }
Member Function Documentation
void beast::insight::detail::StatsDGaugeImpl::do_increment (GaugeImpl::difference_type amount)
Definition at line 617 of file StatsDCollector.cpp.
References do_set(), m_value, ripple::max(), and value.
Referenced by increment().
 {
     GaugeImpl::value_type value (m_value);
     if (amount > 0)
     {
         GaugeImpl::value_type const d (
             static_cast <GaugeImpl::value_type> (amount));
         value +=
             (d >= std::numeric_limits <GaugeImpl::value_type>::max() - m_value)
             ? std::numeric_limits <GaugeImpl::value_type>::max() - m_value
             : d;
     }
     else if (amount < 0)
     {
         GaugeImpl::value_type const d (
             static_cast <GaugeImpl::value_type> (-amount));
         value = (d >= value) ? 0 : value - d;
     }
     do_set (value);
 }
void beast::insight::detail::StatsDGaugeImpl::do_process () virtual
Implements beast::insight::detail::StatsDMetricBase.
Definition at line 640 of file StatsDCollector.cpp.
References flush().
 {
     flush ();
 }
void beast::insight::detail::StatsDGaugeImpl::do_set (GaugeImpl::value_type value)
Definition at line 606 of file StatsDCollector.cpp.
References m_dirty, m_last_value, m_value, and value.
Referenced by do_increment(), and set().
 {
     m_value = value;
     if (m_value != m_last_value)
     {
         m_last_value = m_value;
         m_dirty = true;
     }
 }
void beast::insight::detail::StatsDGaugeImpl::flush ()
Definition at line 591 of file StatsDCollector.cpp.
References m_dirty, m_impl, m_name, and m_value.
Referenced by do_process().
 {
     if (m_dirty)
     {
         m_dirty = false;
         std::stringstream ss;
         ss <<
             m_impl->prefix() << "." <<
             m_name << ":" <<
             m_value << "|c" <<
             "\n";
         m_impl->post_buffer (ss.str ());
     }
 }
void beast::insight::detail::StatsDGaugeImpl::increment (GaugeImpl::difference_type amount) virtual
Implements beast::insight::GaugeImpl.
Definition at line 583 of file StatsDCollector.cpp.
References do_increment(), and m_impl.
 {
     m_impl->get_io_service().dispatch (std::bind (
         &StatsDGaugeImpl::do_increment,
             std::static_pointer_cast <StatsDGaugeImpl> (
                 shared_from_this ()), amount));
 }
StatsDGaugeImpl& beast::insight::detail::StatsDGaugeImpl::operator= (StatsDGaugeImpl const &) private
void beast::insight::detail::StatsDGaugeImpl::set (GaugeImpl::value_type value) virtual
Implements beast::insight::GaugeImpl.
Definition at line 575 of file StatsDCollector.cpp.
References do_set(), and m_impl.
 {
     m_impl->get_io_service().dispatch (std::bind (
         &StatsDGaugeImpl::do_set,
             std::static_pointer_cast <StatsDGaugeImpl> (
                 shared_from_this ()), value));
 }
Member Data Documentation
bool beast::insight::detail::StatsDGaugeImpl::m_dirty private
Definition at line 154 of file StatsDCollector.cpp.
Referenced by do_set(), and flush().
std::shared_ptr<StatsDCollectorImp> beast::insight::detail::StatsDGaugeImpl::m_impl private
Definition at line 150 of file StatsDCollector.cpp.
Referenced by flush(), increment(), set(), StatsDGaugeImpl(), and ~StatsDGaugeImpl().
GaugeImpl::value_type beast::insight::detail::StatsDGaugeImpl::m_last_value private
Definition at line 152 of file StatsDCollector.cpp.
Referenced by do_set().
std::string beast::insight::detail::StatsDGaugeImpl::m_name private
Definition at line 151 of file StatsDCollector.cpp.
Referenced by flush().
GaugeImpl::value_type beast::insight::detail::StatsDGaugeImpl::m_value private
Definition at line 153 of file StatsDCollector.cpp.
Referenced by do_increment(), do_set(), and flush().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/insight/impl/StatsDCollector.cpp