rippled: rippled/src/beast/beast/crypto/impl/sha2/sha2.c File Reference
sha2.c File Reference
#include <string.h>
#include <assert.h>
#include "sha2.h"
Macros
#define SHA256_SHORT_BLOCK_LENGTH (Sha256::blockLength - 8)
#define SHA384_SHORT_BLOCK_LENGTH (SHA384_BLOCK_LENGTH - 16)
#define SHA512_SHORT_BLOCK_LENGTH (SHA512_BLOCK_LENGTH - 16)
#define REVERSE32(w, x)
#define REVERSE64(w, x)
#define ADDINC128(w, n)
#define SHA2_USE_MEMSET_MEMCPY 1
#define MEMSET_BZERO(p, l) memset((p), 0, (l))
#define MEMCPY_BCOPY(d, s, l) memcpy((d), (s), (l))
#define R(b, x) ((x) >> (b))
#define S32(b, x) (((x) >> (b)) | ((x) << (32 - (b))))
#define S64(b, x) (((x) >> (b)) | ((x) << (64 - (b))))
#define Ch(x, y, z) (((x) & (y)) ^ ((~(x)) & (z)))
#define Maj(x, y, z) (((x) & (y)) ^ ((x) & (z)) ^ ((y) & (z)))
#define Sigma0_256(x) (S32(2, (x)) ^ S32(13, (x)) ^ S32(22, (x)))
#define Sigma1_256(x) (S32(6, (x)) ^ S32(11, (x)) ^ S32(25, (x)))
#define sigma0_256(x) (S32(7, (x)) ^ S32(18, (x)) ^ R(3 , (x)))
#define sigma1_256(x) (S32(17, (x)) ^ S32(19, (x)) ^ R(10, (x)))
#define Sigma0_512(x) (S64(28, (x)) ^ S64(34, (x)) ^ S64(39, (x)))
#define Sigma1_512(x) (S64(14, (x)) ^ S64(18, (x)) ^ S64(41, (x)))
#define sigma0_512(x) (S64(1, (x)) ^ S64(8, (x)) ^ R(7, (x)))
#define sigma1_512(x) (S64(19, (x)) ^ S64(61, (x)) ^ R(6, (x)))
#define SHA256_SHORT_BLOCK_LENGTH (Sha256::blockLength - 8)
#define SHA384_SHORT_BLOCK_LENGTH (SHA384_BLOCK_LENGTH - 16)
#define SHA512_SHORT_BLOCK_LENGTH (SHA512_BLOCK_LENGTH - 16)
#define REVERSE32(w, x)
#define REVERSE64(w, x)
#define ADDINC128(w, n)
#define MEMSET_BZERO(p, l) memset((p), 0, (l))
#define MEMCPY_BCOPY(d, s, l) memcpy((d), (s), (l))
#define R(b, x) ((x) >> (b))
#define S32(b, x) (((x) >> (b)) | ((x) << (32 - (b))))
#define S64(b, x) (((x) >> (b)) | ((x) << (64 - (b))))
#define Ch(x, y, z) (((x) & (y)) ^ ((~(x)) & (z)))
#define Maj(x, y, z) (((x) & (y)) ^ ((x) & (z)) ^ ((y) & (z)))
#define Sigma0_256(x) (S32(2, (x)) ^ S32(13, (x)) ^ S32(22, (x)))
#define Sigma1_256(x) (S32(6, (x)) ^ S32(11, (x)) ^ S32(25, (x)))
#define sigma0_256(x) (S32(7, (x)) ^ S32(18, (x)) ^ R(3 , (x)))
#define sigma1_256(x) (S32(17, (x)) ^ S32(19, (x)) ^ R(10, (x)))
#define Sigma0_512(x) (S64(28, (x)) ^ S64(34, (x)) ^ S64(39, (x)))
#define Sigma1_512(x) (S64(14, (x)) ^ S64(18, (x)) ^ S64(41, (x)))
#define sigma0_512(x) (S64(1, (x)) ^ S64(8, (x)) ^ R(7, (x)))
#define sigma1_512(x) (S64(19, (x)) ^ S64(61, (x)) ^ R(6, (x)))
Typedefs
typedef std::uint8_t sha2_byte
typedef std::uint32_t sha2_word32
typedef std::uint64_t sha2_word64
Functions
void SHA512_Last (SHA512_CTX *)
void SHA256_Transform (Sha256::detail::Context *, const sha2_word32 *)
void SHA512_Transform (SHA512_CTX *, const sha2_word64 *)
void SHA256_Init (Sha256::detail::Context *context)
void SHA256_Update (Sha256::detail::Context *context, const sha2_byte *data, size_t len)
void SHA256_Final (sha2_byte digest[], Sha256::detail::Context *context)
char * SHA256_End (Sha256::detail::Context *context, char buffer[])
char * SHA256_Data (const sha2_byte *data, size_t len, char digest[SHA256_DIGEST_STRING_LENGTH])
void SHA512_Init (SHA512_CTX *context)
void SHA512_Update (SHA512_CTX *context, const sha2_byte *data, size_t len)
void SHA512_Final (sha2_byte digest[], SHA512_CTX *context)
char * SHA512_End (SHA512_CTX *context, char buffer[])
char * SHA512_Data (const sha2_byte *data, size_t len, char digest[SHA512_DIGEST_STRING_LENGTH])
void SHA384_Init (SHA384_CTX *context)
void SHA384_Update (SHA384_CTX *context, const sha2_byte *data, size_t len)
void SHA384_Final (sha2_byte digest[], SHA384_CTX *context)
char * SHA384_End (SHA384_CTX *context, char buffer[])
char * SHA384_Data (const sha2_byte *data, size_t len, char digest[SHA384_DIGEST_STRING_LENGTH])
Variables
static const sha2_word32 K256 [64]
static const sha2_word32 sha256_initial_hash_value [8]
static const sha2_word64 K512 [80]
static const sha2_word64 sha384_initial_hash_value [8]
static const sha2_word64 sha512_initial_hash_value [8]
static const char * sha2_hex_digits = "0123456789abcdef"
Macro Definition Documentation
#define ADDINC128 (w, n)
Value:
{ \
    (w)[0] += (sha2_word64)(n); \
    if ((w)[0] < (n)) { \
        (w)[1]++; \
    } \
}
Definition at line 138 of file Sha256.cpp.
Referenced by SHA512_Update().
#define ADDINC128 (w, n)
Value:
{ \
    (w)[0] += (sha2_word64)(n); \
    if ((w)[0] < (n)) { \
        (w)[1]++; \
    } \
}
#define Ch (x, y, z) (((x) & (y)) ^ ((~(x)) & (z)))
#define Ch (x, y, z) (((x) & (y)) ^ ((~(x)) & (z)))
Definition at line 191 of file Sha256.cpp.
Referenced by SHA256_Transform(), and SHA512_Transform().
#define Maj (x, y, z) (((x) & (y)) ^ ((x) & (z)) ^ ((y) & (z)))
#define Maj (x, y, z) (((x) & (y)) ^ ((x) & (z)) ^ ((y) & (z)))
Definition at line 192 of file Sha256.cpp.
Referenced by SHA256_Transform(), and SHA512_Transform().
#define MEMCPY_BCOPY (d, s, l) memcpy((d), (s), (l))
Definition at line 165 of file Sha256.cpp.
Referenced by SHA256_Final(), SHA256_Init(), SHA256_Update(), SHA384_Final(), SHA384_Init(), SHA512_Final(), SHA512_Init(), and SHA512_Update().
#define MEMCPY_BCOPY (d, s, l) memcpy((d), (s), (l))
#define MEMSET_BZERO (p, l) memset((p), 0, (l))
Definition at line 164 of file Sha256.cpp.
Referenced by SHA256_End(), SHA256_Final(), SHA256_Init(), SHA384_End(), SHA384_Final(), SHA384_Init(), SHA512_End(), SHA512_Final(), SHA512_Init(), and SHA512_Last().
#define MEMSET_BZERO (p, l) memset((p), 0, (l))
#define R (b, x) ((x) >> (b))
Definition at line 183 of file Sha256.cpp.
Referenced by rocksdb::TEST().
#define R (b, x) ((x) >> (b))
#define REVERSE32 (w, x)
Value:
{ \
    sha2_word32 tmp = (w); \
    tmp = (tmp >> 16) | (tmp << 16); \
    (x) = ((tmp & 0xff00ff00UL) >> 8) | ((tmp & 0x00ff00ffUL) << 8); \
}
Definition at line 118 of file Sha256.cpp.
Referenced by SHA256_Final(), and SHA256_Transform().
#define REVERSE32 (w, x)
Value:
{ \
    sha2_word32 tmp = (w); \
    tmp = (tmp >> 16) | (tmp << 16); \
    (x) = ((tmp & 0xff00ff00UL) >> 8) | ((tmp & 0x00ff00ffUL) << 8); \
}
#define REVERSE64 (w, x)
Value:
{ \
    sha2_word64 tmp = (w); \
    tmp = (tmp >> 32) | (tmp << 32); \
    tmp = ((tmp & 0xff00ff00ff00ff00ULL) >> 8) | \
          ((tmp & 0x00ff00ff00ff00ffULL) << 8); \
    (x) = ((tmp & 0xffff0000ffff0000ULL) >> 16) | \
          ((tmp & 0x0000ffff0000ffffULL) << 16); \
}
Definition at line 123 of file Sha256.cpp.
Referenced by SHA256_Final(), SHA384_Final(), SHA512_Final(), SHA512_Last(), and SHA512_Transform().
#define REVERSE64 (w, x)
Value:
{ \
    sha2_word64 tmp = (w); \
    tmp = (tmp >> 32) | (tmp << 32); \
    tmp = ((tmp & 0xff00ff00ff00ff00ULL) >> 8) | \
          ((tmp & 0x00ff00ff00ff00ffULL) << 8); \
    (x) = ((tmp & 0xffff0000ffff0000ULL) >> 16) | \
          ((tmp & 0x0000ffff0000ffffULL) << 16); \
}
#define S32 (b, x) (((x) >> (b)) | ((x) << (32 - (b))))
#define S32 (b, x) (((x) >> (b)) | ((x) << (32 - (b))))
Definition at line 186 of file Sha256.cpp.
#define S64 (b, x) (((x) >> (b)) | ((x) << (64 - (b))))
#define S64 (b, x) (((x) >> (b)) | ((x) << (64 - (b))))
Definition at line 188 of file Sha256.cpp.
#define SHA256_SHORT_BLOCK_LENGTH (Sha256::blockLength - 8)
Definition at line 112 of file Sha256.cpp.
Referenced by SHA256_Final().
#define SHA256_SHORT_BLOCK_LENGTH (Sha256::blockLength - 8)
#define SHA2_USE_MEMSET_MEMCPY 1
Definition at line 156 of file sha2.c.
#define SHA384_SHORT_BLOCK_LENGTH (SHA384_BLOCK_LENGTH - 16)
Definition at line 113 of file Sha256.cpp.
#define SHA384_SHORT_BLOCK_LENGTH (SHA384_BLOCK_LENGTH - 16)
#define SHA512_SHORT_BLOCK_LENGTH (SHA512_BLOCK_LENGTH - 16)
Definition at line 114 of file Sha256.cpp.
Referenced by SHA512_Last().
#define SHA512_SHORT_BLOCK_LENGTH (SHA512_BLOCK_LENGTH - 16)
#define Sigma0_256 (x) (S32(2, (x)) ^ S32(13, (x)) ^ S32(22, (x)))
#define Sigma0_256 (x) (S32(2, (x)) ^ S32(13, (x)) ^ S32(22, (x)))
Definition at line 195 of file Sha256.cpp.
Referenced by SHA256_Transform().
#define sigma0_256 (x) (S32(7, (x)) ^ S32(18, (x)) ^ R(3 , (x)))
Definition at line 197 of file Sha256.cpp.
#define sigma0_256 (x) (S32(7, (x)) ^ S32(18, (x)) ^ R(3 , (x)))
#define Sigma0_512 (x) (S64(28, (x)) ^ S64(34, (x)) ^ S64(39, (x)))
#define Sigma0_512 (x) (S64(28, (x)) ^ S64(34, (x)) ^ S64(39, (x)))
Definition at line 201 of file Sha256.cpp.
Referenced by SHA512_Transform().
#define sigma0_512 (x) (S64(1, (x)) ^ S64(8, (x)) ^ R(7, (x)))
Definition at line 203 of file Sha256.cpp.
#define sigma0_512 (x) (S64(1, (x)) ^ S64(8, (x)) ^ R(7, (x)))
#define Sigma1_256 (x) (S32(6, (x)) ^ S32(11, (x)) ^ S32(25, (x)))
#define Sigma1_256 (x) (S32(6, (x)) ^ S32(11, (x)) ^ S32(25, (x)))
Definition at line 196 of file Sha256.cpp.
Referenced by SHA256_Transform().
#define sigma1_256 (x) (S32(17, (x)) ^ S32(19, (x)) ^ R(10, (x)))
Definition at line 198 of file Sha256.cpp.
#define sigma1_256 (x) (S32(17, (x)) ^ S32(19, (x)) ^ R(10, (x)))
#define Sigma1_512 (x) (S64(14, (x)) ^ S64(18, (x)) ^ S64(41, (x)))
Definition at line 202 of file Sha256.cpp.
Referenced by SHA512_Transform().
#define Sigma1_512 (x) (S64(14, (x)) ^ S64(18, (x)) ^ S64(41, (x)))
#define sigma1_512 (x) (S64(19, (x)) ^ S64(61, (x)) ^ R(6, (x)))
#define sigma1_512 (x) (S64(19, (x)) ^ S64(61, (x)) ^ R(6, (x)))
Definition at line 204 of file Sha256.cpp.
Typedef Documentation
typedef std::uint8_t sha2_byte
Definition at line 106 of file sha2.c.
typedef std::uint32_t sha2_word32
Definition at line 107 of file sha2.c.
typedef std::uint64_t sha2_word64
Definition at line 108 of file sha2.c.
Function Documentation
char* SHA256_Data (const sha2_byte * data, size_t len, char digest[SHA256_DIGEST_STRING_LENGTH])
Definition at line 643 of file sha2.c.
{
     Sha256::detail::Context context;
     SHA256_Init(&context);
     SHA256_Update(&context, data, len);
     return SHA256_End(&context, digest);
 }
char* SHA256_End (Sha256::detail::Context * context, char buffer[])
Definition at line 620 of file sha2.c.
References beast::Sha256::digestLength, MEMSET_BZERO, SHA256_Final(), and sha2_hex_digits.
Referenced by main(), and SHA256_Data().
{
     sha2_byte   digest[Sha256::digestLength], *d = digest;
     int     i;
     /* Sanity check: */
     assert(context != (Sha256::detail::Context*)0);
     if (buffer != (char*)0) {
         SHA256_Final(digest, context);
         for (i = 0; i < Sha256::digestLength; i++) {
             *buffer++ = sha2_hex_digits[(*d & 0xf0) >> 4];
             *buffer++ = sha2_hex_digits[*d & 0x0f];
             d++;
         }
         *buffer = (char)0;
     } else {
         MEMSET_BZERO(context, sizeof(Sha256::detail::Context));
     }
     MEMSET_BZERO(digest, Sha256::digestLength);
     return buffer;
 }
void SHA256_Final (sha2_byte digest[], Sha256::detail::Context * context)
Definition at line 557 of file sha2.c.
References beast::Sha256::blockLength, beast::Sha256::digestLength, MEMCPY_BCOPY, MEMSET_BZERO, REVERSE32, REVERSE64, SHA256_SHORT_BLOCK_LENGTH, and SHA256_Transform().
Referenced by SHA256_End(), and ripple::SHA256Hash().
{
     sha2_word32 *d = (sha2_word32*)digest;
     unsigned int    usedspace;
     /* Sanity check: */
     assert(context != (Sha256::detail::Context*)0);
     /* If no digest buffer is passed, we don't bother doing this: */
     if (digest != (sha2_byte*)0) {
         usedspace = (context->bitcount >> 3) % Sha256::blockLength;
 #if BYTE_ORDER == LITTLE_ENDIAN
         /* Convert FROM host byte order */
         REVERSE64(context->bitcount,context->bitcount);
 #endif
         if (usedspace > 0) {
             /* Begin padding with a 1 bit: */
             context->buffer[usedspace++] = 0x80;
             if (usedspace <= SHA256_SHORT_BLOCK_LENGTH) {
                 /* Set-up for the last transform: */
                 MEMSET_BZERO(&context->buffer[usedspace], SHA256_SHORT_BLOCK_LENGTH - usedspace);
             } else {
                 if (usedspace < Sha256::blockLength) {
                     MEMSET_BZERO(&context->buffer[usedspace], Sha256::blockLength - usedspace);
                 }
                 /* Do second-to-last transform: */
                 SHA256_Transform(context, (sha2_word32*)context->buffer);
                 /* And set-up for the last transform: */
                 MEMSET_BZERO(context->buffer, SHA256_SHORT_BLOCK_LENGTH);
             }
         } else {
             /* Set-up for the last transform: */
             MEMSET_BZERO(context->buffer, SHA256_SHORT_BLOCK_LENGTH);
             /* Begin padding with a 1 bit: */
             *context->buffer = 0x80;
         }
         /* Set the bit count: */
         *(sha2_word64*)&context->buffer[SHA256_SHORT_BLOCK_LENGTH] = context->bitcount;
         /* Final transform: */
         SHA256_Transform(context, (sha2_word32*)context->buffer);
 #if BYTE_ORDER == LITTLE_ENDIAN
         {
             /* Convert TO host byte order */
             int j;
             for (j = 0; j < 8; j++) {
                 REVERSE32(context->state[j],context->state[j]);
                 *d++ = context->state[j];
             }
         }
 #else
         MEMCPY_BCOPY(d, context->state, Sha256::digestLength);
 #endif
     }
     /* Clean up state data: */
     MEMSET_BZERO(context, sizeof(Sha256::detail::Context));
     usedspace = 0;
 }
void SHA256_Init (Sha256::detail::Context * context)
Definition at line 325 of file sha2.c.
References beast::Sha256::blockLength, beast::Sha256::digestLength, MEMCPY_BCOPY, MEMSET_BZERO, and sha256_initial_hash_value.
Referenced by main(), SHA256_Data(), and ripple::SHA256Hash().
{
     if (context == (Sha256::detail::Context*)0) {
         return;
     }
     MEMCPY_BCOPY(context->state, sha256_initial_hash_value, Sha256::digestLength);
     MEMSET_BZERO(context->buffer, Sha256::blockLength);
     context->bitcount = 0;
 }
void SHA256_Transform (Sha256::detail::Context * context, const sha2_word32 * data)
Definition at line 429 of file sha2.c.
References BYTE_ORDER, Ch, ripple::f, K256, LITTLE_ENDIAN, Maj, REVERSE32, Sigma0_256, and Sigma1_256.
Referenced by SHA256_Final(), and SHA256_Update().
{
     sha2_word32 a, b, c, d, e, f, g, h, s0, s1;
     sha2_word32 T1, T2, *W256;
     int     j;
     W256 = (sha2_word32*)context->buffer;
     /* Initialize registers with the prev. intermediate value */
     a = context->state[0];
     b = context->state[1];
     c = context->state[2];
     d = context->state[3];
     e = context->state[4];
     f = context->state[5];
     g = context->state[6];
     h = context->state[7];
     j = 0;
     do {
 #if BYTE_ORDER == LITTLE_ENDIAN
         /* Copy data while converting to host byte order */
         REVERSE32(*data++,W256[j]);
         /* Apply the SHA-256 compression function to update a..h */
         T1 = h + Sigma1_256(e) + Ch(e, f, g) + K256[j] + W256[j];
 #else /* BYTE_ORDER == LITTLE_ENDIAN */
         /* Apply the SHA-256 compression function to update a..h with copy */
         T1 = h + Sigma1_256(e) + Ch(e, f, g) + K256[j] + (W256[j] = *data++);
 #endif /* BYTE_ORDER == LITTLE_ENDIAN */
         T2 = Sigma0_256(a) + Maj(a, b, c);
         h = g;
         g = f;
         f = e;
         e = d + T1;
         d = c;
         c = b;
         b = a;
         a = T1 + T2;
         j++;
     } while (j < 16);
     do {
         /* Part of the message block expansion: */
         s0 = W256[(j+1)&0x0f];
         s0 = sigma0_256(s0);
         s1 = W256[(j+14)&0x0f];
         s1 = sigma1_256(s1);
         /* Apply the SHA-256 compression function to update a..h */
         T1 = h + Sigma1_256(e) + Ch(e, f, g) + K256[j] +
              (W256[j&0x0f] += s1 + W256[(j+9)&0x0f] + s0);
         T2 = Sigma0_256(a) + Maj(a, b, c);
         h = g;
         g = f;
         f = e;
         e = d + T1;
         d = c;
         c = b;
         b = a;
         a = T1 + T2;
         j++;
     } while (j < 64);
     /* Compute the current intermediate hash value */
     context->state[0] += a;
     context->state[1] += b;
     context->state[2] += c;
     context->state[3] += d;
     context->state[4] += e;
     context->state[5] += f;
     context->state[6] += g;
     context->state[7] += h;
     /* Clean up */
     a = b = c = d = e = f = g = h = T1 = T2 = 0;
 }
void SHA256_Update (Sha256::detail::Context * context, const sha2_byte * data, size_t len)
Definition at line 509 of file sha2.c.
References beast::Sha256::blockLength, MEMCPY_BCOPY, and SHA256_Transform().
Referenced by main(), SHA256_Data(), and ripple::SHA256Hash().
{
     unsigned int    freespace, usedspace;
     if (len == 0) {
         /* Calling with no data is valid - we do nothing */
         return;
     }
     /* Sanity check: */
     assert(context != (Sha256::detail::Context*)0 && data != (sha2_byte*)0);
     usedspace = (context->bitcount >> 3) % Sha256::blockLength;
     if (usedspace > 0) {
         /* Calculate how much free space is available in the buffer */
         freespace = Sha256::blockLength - usedspace;
         if (len >= freespace) {
             /* Fill the buffer completely and process it */
             MEMCPY_BCOPY(&context->buffer[usedspace], data, freespace);
             context->bitcount += freespace << 3;
             len -= freespace;
             data += freespace;
             SHA256_Transform(context, (sha2_word32*)context->buffer);
         } else {
             /* The buffer is not yet full */
             MEMCPY_BCOPY(&context->buffer[usedspace], data, len);
             context->bitcount += len << 3;
             /* Clean up: */
             usedspace = freespace = 0;
             return;
         }
     }
     while (len >= Sha256::blockLength) {
         /* Process as many complete blocks as we can */
         SHA256_Transform(context, (sha2_word32*)data);
         context->bitcount += Sha256::blockLength << 3;
         len -= Sha256::blockLength;
         data += Sha256::blockLength;
     }
     if (len > 0) {
         /* There's left-overs, so save 'em */
         MEMCPY_BCOPY(context->buffer, data, len);
         context->bitcount += len << 3;
     }
     /* Clean up: */
     usedspace = freespace = 0;
 }
char* SHA384_Data (const sha2_byte * data, size_t len, char digest[SHA384_DIGEST_STRING_LENGTH])
Definition at line 1047 of file sha2.c.
{
     SHA384_CTX  context;
     SHA384_Init(&context);
     SHA384_Update(&context, data, len);
     return SHA384_End(&context, digest);
 }
char* SHA384_End (SHA384_CTX * context, char buffer[])
Definition at line 1024 of file sha2.c.
References MEMSET_BZERO, sha2_hex_digits, SHA384_DIGEST_LENGTH, and SHA384_Final().
Referenced by main(), and SHA384_Data().
{
     sha2_byte   digest[SHA384_DIGEST_LENGTH], *d = digest;
     int     i;
     /* Sanity check: */
     assert(context != (SHA384_CTX*)0);
     if (buffer != (char*)0) {
         SHA384_Final(digest, context);
         for (i = 0; i < SHA384_DIGEST_LENGTH; i++) {
             *buffer++ = sha2_hex_digits[(*d & 0xf0) >> 4];
             *buffer++ = sha2_hex_digits[*d & 0x0f];
             d++;
         }
         *buffer = (char)0;
     } else {
         MEMSET_BZERO(context, sizeof(SHA384_CTX));
     }
     MEMSET_BZERO(digest, SHA384_DIGEST_LENGTH);
     return buffer;
 }
void SHA384_Final (sha2_byte digest[], SHA384_CTX * context)
Definition at line 995 of file sha2.c.
References MEMCPY_BCOPY, MEMSET_BZERO, REVERSE64, SHA384_DIGEST_LENGTH, SHA512_Last(), and _SHA512_CTX::state.
Referenced by SHA384_End().
{
     sha2_word64 *d = (sha2_word64*)digest;
     /* Sanity check: */
     assert(context != (SHA384_CTX*)0);
     /* If no digest buffer is passed, we don't bother doing this: */
     if (digest != (sha2_byte*)0) {
         SHA512_Last((SHA512_CTX*)context);
         /* Save the hash data for output: */
 #if BYTE_ORDER == LITTLE_ENDIAN
         {
             /* Convert TO host byte order */
             int j;
             for (j = 0; j < 6; j++) {
                 REVERSE64(context->state[j],context->state[j]);
                 *d++ = context->state[j];
             }
         }
 #else
         MEMCPY_BCOPY(d, context->state, SHA384_DIGEST_LENGTH);
 #endif
     }
     /* Zero out state data */
     MEMSET_BZERO(context, sizeof(SHA384_CTX));
 }
void SHA384_Init (SHA384_CTX * context)
Definition at line 982 of file sha2.c.
References _SHA512_CTX::bitcount, _SHA512_CTX::buffer, MEMCPY_BCOPY, MEMSET_BZERO, SHA384_BLOCK_LENGTH, sha384_initial_hash_value, SHA512_DIGEST_LENGTH, and _SHA512_CTX::state.
Referenced by main(), and SHA384_Data().
{
     if (context == (SHA384_CTX*)0) {
         return;
     }
     MEMCPY_BCOPY(context->state, sha384_initial_hash_value, SHA512_DIGEST_LENGTH);
     MEMSET_BZERO(context->buffer, SHA384_BLOCK_LENGTH);
     context->bitcount[0] = context->bitcount[1] = 0;
 }
void SHA384_Update (SHA384_CTX * context, const sha2_byte * data, size_t len)
Definition at line 991 of file sha2.c.
References SHA512_Update().
Referenced by main(), and SHA384_Data().
{
     SHA512_Update((SHA512_CTX*)context, data, len);
 }
char* SHA512_Data (const sha2_byte * data, size_t len, char digest[SHA512_DIGEST_STRING_LENGTH])
Definition at line 972 of file sha2.c.
{
     SHA512_CTX  context;
     SHA512_Init(&context);
     SHA512_Update(&context, data, len);
     return SHA512_End(&context, digest);
 }
char* SHA512_End (SHA512_CTX * context, char buffer[])
Definition at line 949 of file sha2.c.
References MEMSET_BZERO, sha2_hex_digits, SHA512_DIGEST_LENGTH, and SHA512_Final().
Referenced by main(), and SHA512_Data().
{
     sha2_byte   digest[SHA512_DIGEST_LENGTH], *d = digest;
     int     i;
     /* Sanity check: */
     assert(context != (SHA512_CTX*)0);
     if (buffer != (char*)0) {
         SHA512_Final(digest, context);
         for (i = 0; i < SHA512_DIGEST_LENGTH; i++) {
             *buffer++ = sha2_hex_digits[(*d & 0xf0) >> 4];
             *buffer++ = sha2_hex_digits[*d & 0x0f];
             d++;
         }
         *buffer = (char)0;
     } else {
         MEMSET_BZERO(context, sizeof(SHA512_CTX));
     }
     MEMSET_BZERO(digest, SHA512_DIGEST_LENGTH);
     return buffer;
 }
void SHA512_Final (sha2_byte digest[], SHA512_CTX * context)
Definition at line 920 of file sha2.c.
References MEMCPY_BCOPY, MEMSET_BZERO, REVERSE64, SHA512_DIGEST_LENGTH, SHA512_Last(), and _SHA512_CTX::state.
Referenced by ripple::Serializer::getPrefixHash(), and SHA512_End().
{
     sha2_word64 *d = (sha2_word64*)digest;
     /* Sanity check: */
     assert(context != (SHA512_CTX*)0);
     /* If no digest buffer is passed, we don't bother doing this: */
     if (digest != (sha2_byte*)0) {
         SHA512_Last(context);
         /* Save the hash data for output: */
 #if BYTE_ORDER == LITTLE_ENDIAN
         {
             /* Convert TO host byte order */
             int j;
             for (j = 0; j < 8; j++) {
                 REVERSE64(context->state[j],context->state[j]);
                 *d++ = context->state[j];
             }
         }
 #else
         MEMCPY_BCOPY(d, context->state, SHA512_DIGEST_LENGTH);
 #endif
     }
     /* Zero out state data */
     MEMSET_BZERO(context, sizeof(SHA512_CTX));
 }
void SHA512_Init (SHA512_CTX * context)
Definition at line 653 of file sha2.c.
References _SHA512_CTX::bitcount, _SHA512_CTX::buffer, MEMCPY_BCOPY, MEMSET_BZERO, SHA512_BLOCK_LENGTH, SHA512_DIGEST_LENGTH, sha512_initial_hash_value, and _SHA512_CTX::state.
Referenced by ripple::Serializer::getPrefixHash(), main(), and SHA512_Data().
{
     if (context == (SHA512_CTX*)0) {
         return;
     }
     MEMCPY_BCOPY(context->state, sha512_initial_hash_value, SHA512_DIGEST_LENGTH);
     MEMSET_BZERO(context->buffer, SHA512_BLOCK_LENGTH);
     context->bitcount[0] = context->bitcount[1] =  0;
 }
void SHA512_Last (SHA512_CTX * context)
Definition at line 879 of file sha2.c.
References _SHA512_CTX::bitcount, _SHA512_CTX::buffer, MEMSET_BZERO, REVERSE64, SHA512_BLOCK_LENGTH, SHA512_SHORT_BLOCK_LENGTH, and SHA512_Transform().
Referenced by SHA384_Final(), and SHA512_Final().
{
     unsigned int    usedspace;
     usedspace = (context->bitcount[0] >> 3) % SHA512_BLOCK_LENGTH;
 #if BYTE_ORDER == LITTLE_ENDIAN
     /* Convert FROM host byte order */
     REVERSE64(context->bitcount[0],context->bitcount[0]);
     REVERSE64(context->bitcount[1],context->bitcount[1]);
 #endif
     if (usedspace > 0) {
         /* Begin padding with a 1 bit: */
         context->buffer[usedspace++] = 0x80;
         if (usedspace <= SHA512_SHORT_BLOCK_LENGTH) {
             /* Set-up for the last transform: */
             MEMSET_BZERO(&context->buffer[usedspace], SHA512_SHORT_BLOCK_LENGTH - usedspace);
         } else {
             if (usedspace < SHA512_BLOCK_LENGTH) {
                 MEMSET_BZERO(&context->buffer[usedspace], SHA512_BLOCK_LENGTH - usedspace);
             }
             /* Do second-to-last transform: */
             SHA512_Transform(context, (sha2_word64*)context->buffer);
             /* And set-up for the last transform: */
             MEMSET_BZERO(context->buffer, SHA512_BLOCK_LENGTH - 2);
         }
     } else {
         /* Prepare for final transform: */
         MEMSET_BZERO(context->buffer, SHA512_SHORT_BLOCK_LENGTH);
         /* Begin padding with a 1 bit: */
         *context->buffer = 0x80;
     }
     /* Store the length of input data (in bits): */
     *(sha2_word64*)&context->buffer[SHA512_SHORT_BLOCK_LENGTH] = context->bitcount[1];
     *(sha2_word64*)&context->buffer[SHA512_SHORT_BLOCK_LENGTH+8] = context->bitcount[0];
     /* Final transform: */
     SHA512_Transform(context, (sha2_word64*)context->buffer);
 }
void SHA512_Transform (SHA512_CTX * context, const sha2_word64 * data)
Definition at line 753 of file sha2.c.
References _SHA512_CTX::buffer, BYTE_ORDER, Ch, ripple::f, K512, LITTLE_ENDIAN, Maj, REVERSE64, Sigma0_512, Sigma1_512, and _SHA512_CTX::state.
Referenced by SHA512_Last(), and SHA512_Update().
{
     sha2_word64 a, b, c, d, e, f, g, h, s0, s1;
     sha2_word64 T1, T2, *W512 = (sha2_word64*)context->buffer;
     int     j;
     /* Initialize registers with the prev. intermediate value */
     a = context->state[0];
     b = context->state[1];
     c = context->state[2];
     d = context->state[3];
     e = context->state[4];
     f = context->state[5];
     g = context->state[6];
     h = context->state[7];
     j = 0;
     do {
 #if BYTE_ORDER == LITTLE_ENDIAN
         /* Convert TO host byte order */
         REVERSE64(*data++, W512[j]);
         /* Apply the SHA-512 compression function to update a..h */
         T1 = h + Sigma1_512(e) + Ch(e, f, g) + K512[j] + W512[j];
 #else /* BYTE_ORDER == LITTLE_ENDIAN */
         /* Apply the SHA-512 compression function to update a..h with copy */
         T1 = h + Sigma1_512(e) + Ch(e, f, g) + K512[j] + (W512[j] = *data++);
 #endif /* BYTE_ORDER == LITTLE_ENDIAN */
         T2 = Sigma0_512(a) + Maj(a, b, c);
         h = g;
         g = f;
         f = e;
         e = d + T1;
         d = c;
         c = b;
         b = a;
         a = T1 + T2;
         j++;
     } while (j < 16);
     do {
         /* Part of the message block expansion: */
         s0 = W512[(j+1)&0x0f];
         s0 = sigma0_512(s0);
         s1 = W512[(j+14)&0x0f];
         s1 =  sigma1_512(s1);
         /* Apply the SHA-512 compression function to update a..h */
         T1 = h + Sigma1_512(e) + Ch(e, f, g) + K512[j] +
              (W512[j&0x0f] += s1 + W512[(j+9)&0x0f] + s0);
         T2 = Sigma0_512(a) + Maj(a, b, c);
         h = g;
         g = f;
         f = e;
         e = d + T1;
         d = c;
         c = b;
         b = a;
         a = T1 + T2;
         j++;
     } while (j < 80);
     /* Compute the current intermediate hash value */
     context->state[0] += a;
     context->state[1] += b;
     context->state[2] += c;
     context->state[3] += d;
     context->state[4] += e;
     context->state[5] += f;
     context->state[6] += g;
     context->state[7] += h;
     /* Clean up */
     a = b = c = d = e = f = g = h = T1 = T2 = 0;
 }
void SHA512_Update (SHA512_CTX * context, const sha2_byte * data, size_t len)
Definition at line 831 of file sha2.c.
References ADDINC128, _SHA512_CTX::bitcount, _SHA512_CTX::buffer, MEMCPY_BCOPY, SHA512_BLOCK_LENGTH, and SHA512_Transform().
Referenced by ripple::Serializer::getPrefixHash(), main(), SHA384_Update(), and SHA512_Data().
{
     unsigned int    freespace, usedspace;
     if (len == 0) {
         /* Calling with no data is valid - we do nothing */
         return;
     }
     /* Sanity check: */
     assert(context != (SHA512_CTX*)0 && data != (sha2_byte*)0);
     usedspace = (context->bitcount[0] >> 3) % SHA512_BLOCK_LENGTH;
     if (usedspace > 0) {
         /* Calculate how much free space is available in the buffer */
         freespace = SHA512_BLOCK_LENGTH - usedspace;
         if (len >= freespace) {
             /* Fill the buffer completely and process it */
             MEMCPY_BCOPY(&context->buffer[usedspace], data, freespace);
             ADDINC128(context->bitcount, freespace << 3);
             len -= freespace;
             data += freespace;
             SHA512_Transform(context, (sha2_word64*)context->buffer);
         } else {
             /* The buffer is not yet full */
             MEMCPY_BCOPY(&context->buffer[usedspace], data, len);
             ADDINC128(context->bitcount, len << 3);
             /* Clean up: */
             usedspace = freespace = 0;
             return;
         }
     }
     while (len >= SHA512_BLOCK_LENGTH) {
         /* Process as many complete blocks as we can */
         SHA512_Transform(context, (sha2_word64*)data);
         ADDINC128(context->bitcount, SHA512_BLOCK_LENGTH << 3);
         len -= SHA512_BLOCK_LENGTH;
         data += SHA512_BLOCK_LENGTH;
     }
     if (len > 0) {
         /* There's left-overs, so save 'em */
         MEMCPY_BCOPY(context->buffer, data, len);
         ADDINC128(context->bitcount, len << 3);
     }
     /* Clean up: */
     usedspace = freespace = 0;
 }
Variable Documentation
const sha2_word32 K256[64] static
Initial value:
= {
    0x428a2f98UL, 0x71374491UL, 0xb5c0fbcfUL, 0xe9b5dba5UL,
    0x3956c25bUL, 0x59f111f1UL, 0x923f82a4UL, 0xab1c5ed5UL,
    0xd807aa98UL, 0x12835b01UL, 0x243185beUL, 0x550c7dc3UL,
    0x72be5d74UL, 0x80deb1feUL, 0x9bdc06a7UL, 0xc19bf174UL,
    0xe49b69c1UL, 0xefbe4786UL, 0x0fc19dc6UL, 0x240ca1ccUL,
    0x2de92c6fUL, 0x4a7484aaUL, 0x5cb0a9dcUL, 0x76f988daUL,
    0x983e5152UL, 0xa831c66dUL, 0xb00327c8UL, 0xbf597fc7UL,
    0xc6e00bf3UL, 0xd5a79147UL, 0x06ca6351UL, 0x14292967UL,
    0x27b70a85UL, 0x2e1b2138UL, 0x4d2c6dfcUL, 0x53380d13UL,
    0x650a7354UL, 0x766a0abbUL, 0x81c2c92eUL, 0x92722c85UL,
    0xa2bfe8a1UL, 0xa81a664bUL, 0xc24b8b70UL, 0xc76c51a3UL,
    0xd192e819UL, 0xd6990624UL, 0xf40e3585UL, 0x106aa070UL,
    0x19a4c116UL, 0x1e376c08UL, 0x2748774cUL, 0x34b0bcb5UL,
    0x391c0cb3UL, 0x4ed8aa4aUL, 0x5b9cca4fUL, 0x682e6ff3UL,
    0x748f82eeUL, 0x78a5636fUL, 0x84c87814UL, 0x8cc70208UL,
    0x90befffaUL, 0xa4506cebUL, 0xbef9a3f7UL, 0xc67178f2UL
}
Definition at line 218 of file sha2.c.
Referenced by SHA256_Transform().
const sha2_word64 K512[80] static
Initial value:
= {
    0x428a2f98d728ae22ULL, 0x7137449123ef65cdULL,
    0xb5c0fbcfec4d3b2fULL, 0xe9b5dba58189dbbcULL,
    0x3956c25bf348b538ULL, 0x59f111f1b605d019ULL,
    0x923f82a4af194f9bULL, 0xab1c5ed5da6d8118ULL,
    0xd807aa98a3030242ULL, 0x12835b0145706fbeULL,
    0x243185be4ee4b28cULL, 0x550c7dc3d5ffb4e2ULL,
    0x72be5d74f27b896fULL, 0x80deb1fe3b1696b1ULL,
    0x9bdc06a725c71235ULL, 0xc19bf174cf692694ULL,
    0xe49b69c19ef14ad2ULL, 0xefbe4786384f25e3ULL,
    0x0fc19dc68b8cd5b5ULL, 0x240ca1cc77ac9c65ULL,
    0x2de92c6f592b0275ULL, 0x4a7484aa6ea6e483ULL,
    0x5cb0a9dcbd41fbd4ULL, 0x76f988da831153b5ULL,
    0x983e5152ee66dfabULL, 0xa831c66d2db43210ULL,
    0xb00327c898fb213fULL, 0xbf597fc7beef0ee4ULL,
    0xc6e00bf33da88fc2ULL, 0xd5a79147930aa725ULL,
    0x06ca6351e003826fULL, 0x142929670a0e6e70ULL,
    0x27b70a8546d22ffcULL, 0x2e1b21385c26c926ULL,
    0x4d2c6dfc5ac42aedULL, 0x53380d139d95b3dfULL,
    0x650a73548baf63deULL, 0x766a0abb3c77b2a8ULL,
    0x81c2c92e47edaee6ULL, 0x92722c851482353bULL,
    0xa2bfe8a14cf10364ULL, 0xa81a664bbc423001ULL,
    0xc24b8b70d0f89791ULL, 0xc76c51a30654be30ULL,
    0xd192e819d6ef5218ULL, 0xd69906245565a910ULL,
    0xf40e35855771202aULL, 0x106aa07032bbd1b8ULL,
    0x19a4c116b8d2d0c8ULL, 0x1e376c085141ab53ULL,
    0x2748774cdf8eeb99ULL, 0x34b0bcb5e19b48a8ULL,
    0x391c0cb3c5c95a63ULL, 0x4ed8aa4ae3418acbULL,
    0x5b9cca4f7763e373ULL, 0x682e6ff3d6b2b8a3ULL,
    0x748f82ee5defb2fcULL, 0x78a5636f43172f60ULL,
    0x84c87814a1f0ab72ULL, 0x8cc702081a6439ecULL,
    0x90befffa23631e28ULL, 0xa4506cebde82bde9ULL,
    0xbef9a3f7b2c67915ULL, 0xc67178f2e372532bULL,
    0xca273eceea26619cULL, 0xd186b8c721c0c207ULL,
    0xeada7dd6cde0eb1eULL, 0xf57d4f7fee6ed178ULL,
    0x06f067aa72176fbaULL, 0x0a637dc5a2c898a6ULL,
    0x113f9804bef90daeULL, 0x1b710b35131c471bULL,
    0x28db77f523047d84ULL, 0x32caab7b40c72493ULL,
    0x3c9ebe0a15c9bebcULL, 0x431d67c49c100d4cULL,
    0x4cc5d4becb3e42b6ULL, 0x597f299cfc657e2aULL,
    0x5fcb6fab3ad6faecULL, 0x6c44198c4a475817ULL
}
Definition at line 250 of file sha2.c.
Referenced by SHA512_Transform().
const sha2_word32 sha256_initial_hash_value[8] static
Initial value:
= {
    0x6a09e667UL,
    0xbb67ae85UL,
    0x3c6ef372UL,
    0xa54ff53aUL,
    0x510e527fUL,
    0x9b05688cUL,
    0x1f83d9abUL,
    0x5be0cd19UL
}
Definition at line 238 of file sha2.c.
Referenced by SHA256_Init().
const char* sha2_hex_digits = "0123456789abcdef" static
Definition at line 321 of file sha2.c.
Referenced by SHA256_End(), SHA384_End(), and SHA512_End().
const sha2_word64 sha384_initial_hash_value[8] static
Initial value:
= {
    0xcbbb9d5dc1059ed8ULL,
    0x629a292a367cd507ULL,
    0x9159015a3070dd17ULL,
    0x152fecd8f70e5939ULL,
    0x67332667ffc00b31ULL,
    0x8eb44a8768581511ULL,
    0xdb0c2e0d64f98fa7ULL,
    0x47b5481dbefa4fa4ULL
}
Definition at line 294 of file sha2.c.
Referenced by SHA384_Init().
const sha2_word64 sha512_initial_hash_value[8] static
Initial value:
= {
    0x6a09e667f3bcc908ULL,
    0xbb67ae8584caa73bULL,
    0x3c6ef372fe94f82bULL,
    0xa54ff53a5f1d36f1ULL,
    0x510e527fade682d1ULL,
    0x9b05688c2b3e6c1fULL,
    0x1f83d9abfb41bd6bULL,
    0x5be0cd19137e2179ULL
}
Definition at line 306 of file sha2.c.
Referenced by SHA512_Init().