rippled: ripple::RPCHandler Class Reference
ripple::RPCHandler Class Reference
#include <RPCHandler.h>
Public Member Functions
RPCHandler (NetworkOPs *netOps)
RPCHandler (NetworkOPs *netOps, InfoSub::pointer infoSub)
Json::Value doCommand (const Json::Value &jvRequest, int role, Resource::Charge &loadType)
Json::Value doRpcCommand (const std::string &strCommand, Json::Value const &jvParams, int iRole, Resource::Charge &loadType)
Private Types
enum { optNone = 0, optNetwork = 1, optCurrent = 2 + optNetwork, optClosed = 4 + optNetwork }
typedef Json::Value(RPCHandler::* doFuncPtr)(Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &MasterLockHolder)
Private Member Functions
Json::Value doAccountCurrencies (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doAccountInfo (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doAccountLines (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doAccountOffers (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doAccountTx (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doAccountTxSwitch (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doAccountTxOld (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doBookOffers (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doBlackList (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doConnect (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doConsensusInfo (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doFeature (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doFetchInfo (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doGetCounts (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doInternal (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doLedger (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doLedgerAccept (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doLedgerCleaner (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doLedgerClosed (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doLedgerCurrent (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doLedgerData (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doLedgerEntry (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doLedgerHeader (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doLogLevel (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doLogRotate (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doNicknameInfo (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doOwnerInfo (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doPathFind (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doPeers (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doPing (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doPrint (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doProfile (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doProofCreate (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doProofSolve (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doProofVerify (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doRandom (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doRipplePathFind (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doSMS (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doServerInfo (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doServerState (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doSessionClose (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doSessionOpen (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doSign (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doStop (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doSubmit (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doSubscribe (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doTransactionEntry (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doTx (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doTxHistory (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doUnlAdd (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doUnlDelete (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doUnlFetch (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doUnlList (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doUnlLoad (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doUnlNetwork (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doUnlReset (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doUnlScore (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doUnsubscribe (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doValidationCreate (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doValidationSeed (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doWalletAccounts (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doWalletLock (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doWalletPropose (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doWalletSeed (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doWalletUnlock (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Json::Value doWalletVerify (Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &mlh)
Private Attributes
NetworkOPs * mNetOps
InfoSub::pointer mInfoSub
int mRole
Detailed Description
Definition at line 40 of file RPCHandler.h.
Member Typedef Documentation
typedef Json::Value(RPCHandler::* ripple::RPCHandler::doFuncPtr)(Json::Value params, Resource::Charge &loadType, Application::ScopedLockType &MasterLockHolder) private
Definition at line 52 of file RPCHandler.h.
Member Enumeration Documentation
anonymous enum private
Enumerator
optNone
optNetwork
optCurrent
optClosed
Definition at line 58 of file RPCHandler.h.
     {
         optNone     = 0,
         optNetwork  = 1,                // Need network
         optCurrent  = 2 + optNetwork,   // Need current ledger
         optClosed   = 4 + optNetwork,   // Need closed ledger
     };
Constructor & Destructor Documentation
ripple::RPCHandler::RPCHandler (NetworkOPs * netOps) explicit
Definition at line 30 of file RPCHandler.cpp.
     : mNetOps (netOps)
     , mRole (Config::FORBID)
 {
 }
ripple::RPCHandler::RPCHandler (NetworkOPs * netOps, InfoSub::pointer infoSub)
Definition at line 36 of file RPCHandler.cpp.
     : mNetOps (netOps)
     , mInfoSub (infoSub)
     , mRole (Config::FORBID)
 {
 }
Member Function Documentation
Json::Value ripple::RPCHandler::doAccountCurrencies (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 22 of file AccountCurrencies.cpp.
References ripple::RPC::accountFromString(), Json::Value::append(), Json::arrayValue, Json::Value::asBool(), Json::Value::asString(), Json::Value::asUInt(), ripple::STAmount::createHumanCurrency(), CURRENCY_BAD, Json::Value::empty(), ripple::RippleAddress::getAccountID(), ripple::RippleState::getBalance(), ripple::STAmount::getCurrency(), ripple::RippleState::getLimitPeer(), Json::Value::isMember(), ripple::RPC::lookupLedger(), ripple::RPC::missing_field_error(), and mNetOps.
Referenced by doCommand().
 {
     masterLockHolder.unlock ();
     // Get the current ledger
     Ledger::pointer lpLedger;
     Json::Value jvResult (RPC::lookupLedger (params, lpLedger, *mNetOps));
     if (!lpLedger)
         return jvResult;
     if (! params.isMember ("account") && ! params.isMember ("ident"))
         return RPC::missing_field_error ("account");
     std::string const strIdent (params.isMember ("account")
         ? params["account"].asString ()
         : params["ident"].asString ());
     int const iIndex (params.isMember ("account_index")
         ? params["account_index"].asUInt ()
         : 0);
     bool const bStrict (params.isMember ("strict") && params["strict"].asBool ());
     // Get info on account.
     bool bIndex; // out param
     RippleAddress naAccount; // out param
     Json::Value jvAccepted (RPC::accountFromString (
         lpLedger, naAccount, bIndex, strIdent, iIndex, bStrict, *mNetOps));
     if (!jvAccepted.empty ())
         return jvAccepted;
     std::set<uint160> send, receive;
     AccountItems rippleLines (naAccount.getAccountID (), lpLedger, AccountItem::pointer (new RippleState ()));
     BOOST_FOREACH(AccountItem::ref item, rippleLines.getItems ())
     {
         RippleState* rspEntry = (RippleState*) item.get ();
         const STAmount& saBalance = rspEntry->getBalance ();
         if (saBalance < rspEntry->getLimit ())
             receive.insert (saBalance.getCurrency ());
         if ((-saBalance) < rspEntry->getLimitPeer ())
             send.insert (saBalance.getCurrency ());
     }
     send.erase (CURRENCY_BAD);
     receive.erase (CURRENCY_BAD);
     Json::Value& sendCurrencies = (jvResult["send_currencies"] = Json::arrayValue);
     BOOST_FOREACH(uint160 const& c, send)
     {
         sendCurrencies.append (STAmount::createHumanCurrency (c));
     }
     Json::Value& recvCurrencies = (jvResult["receive_currencies"] = Json::arrayValue);
     BOOST_FOREACH(uint160 const& c, receive)
     {
         recvCurrencies.append (STAmount::createHumanCurrency (c));
     }
     return jvResult;
 }
Json::Value ripple::RPCHandler::doAccountInfo (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 29 of file AccountInfo.cpp.
References ripple::RPC::accountFromString(), Json::Value::asBool(), Json::Value::asString(), Json::Value::asUInt(), Json::Value::empty(), ripple::NetworkOPs::getAccountState(), ripple::RippleAddress::humanAccountID(), Json::Value::isMember(), ripple::RPC::lookupLedger(), ripple::RPC::missing_field_error(), mNetOps, ripple::rpcACT_NOT_FOUND, and ripple::rpcError().
Referenced by doCommand().
 {
     masterLockHolder.unlock ();
     Ledger::pointer     lpLedger;
     Json::Value         jvResult    = RPC::lookupLedger (params, lpLedger, *mNetOps);
     if (!lpLedger)
         return jvResult;
     if (!params.isMember ("account") && !params.isMember ("ident"))
         return RPC::missing_field_error ("account");
     std::string     strIdent    = params.isMember ("account") ? params["account"].asString () : params["ident"].asString ();
     bool            bIndex;
     int             iIndex      = params.isMember ("account_index") ? params["account_index"].asUInt () : 0;
     bool            bStrict     = params.isMember ("strict") && params["strict"].asBool ();
     RippleAddress   naAccount;
     // Get info on account.
     Json::Value     jvAccepted      = RPC::accountFromString (lpLedger, naAccount, bIndex, strIdent, iIndex, bStrict, *mNetOps);
     if (!jvAccepted.empty ())
         return jvAccepted;
     AccountState::pointer asAccepted    = mNetOps->getAccountState (lpLedger, naAccount);
     if (asAccepted)
     {
         asAccepted->addJson (jvAccepted);
         jvResult["account_data"]    = jvAccepted;
     }
     else
     {
         jvResult["account"] = naAccount.humanAccountID ();
         jvResult            = rpcError (rpcACT_NOT_FOUND, jvResult);
     }
     return jvResult;
 }
Json::Value ripple::RPCHandler::doAccountLines (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 29 of file AccountLines.cpp.
References ripple::RPC::accountFromString(), Json::Value::append(), Json::arrayValue, Json::Value::asString(), Json::Value::asUInt(), ripple::RippleAddress::createHumanAccountID(), Json::Value::empty(), ripple::Resource::feeMediumBurdenRPC, ripple::RippleAddress::getAccountID(), ripple::RippleState::getAccountIDPeer(), ripple::RippleState::getAuth(), ripple::RippleState::getAuthPeer(), ripple::RippleState::getBalance(), ripple::STAmount::getHumanCurrency(), ripple::RippleState::getLimit(), ripple::RippleState::getLimitPeer(), ripple::RippleState::getNoRipple(), ripple::RippleState::getNoRipplePeer(), ripple::RippleState::getQualityIn(), ripple::RippleState::getQualityOut(), ripple::STAmount::getText(), ripple::RippleAddress::humanAccountID(), Json::Value::isMember(), ripple::RippleAddress::isValid(), ripple::RPC::lookupLedger(), ripple::RPC::missing_field_error(), mNetOps, Json::objectValue, ripple::rpcACT_NOT_FOUND, and ripple::rpcError().
Referenced by doCommand().
 {
     masterLockHolder.unlock ();
     Ledger::pointer     lpLedger;
     Json::Value         jvResult    = RPC::lookupLedger (params, lpLedger, *mNetOps);
     if (!lpLedger)
         return jvResult;
     if (!params.isMember ("account"))
         return RPC::missing_field_error ("account");
     std::string     strIdent    = params["account"].asString ();
     bool            bIndex      = params.isMember ("account_index");
     int             iIndex      = bIndex ? params["account_index"].asUInt () : 0;
     RippleAddress   raAccount;
     jvResult    = RPC::accountFromString (lpLedger, raAccount, bIndex, strIdent, iIndex, false, *mNetOps);
     if (!jvResult.empty ())
         return jvResult;
     std::string     strPeer     = params.isMember ("peer") ? params["peer"].asString () : "";
     bool            bPeerIndex      = params.isMember ("peer_index");
     int             iPeerIndex      = bIndex ? params["peer_index"].asUInt () : 0;
     RippleAddress   raPeer;
     if (!strPeer.empty ())
     {
         jvResult["peer"]    = raAccount.humanAccountID ();
         if (bPeerIndex)
             jvResult["peer_index"]  = iPeerIndex;
         jvResult    = RPC::accountFromString (lpLedger, raPeer, bPeerIndex, strPeer, iPeerIndex, false, *mNetOps);
         if (!jvResult.empty ())
             return jvResult;
     }
     if (lpLedger->hasAccount (raAccount))
     {
         AccountItems rippleLines (raAccount.getAccountID (), lpLedger, AccountItem::pointer (new RippleState ()));
         jvResult["account"] = raAccount.humanAccountID ();
         Json::Value& jsonLines = (jvResult["lines"] = Json::arrayValue);
         BOOST_FOREACH (AccountItem::ref item, rippleLines.getItems ())
         {
             RippleState* line = (RippleState*)item.get ();
             if (!raPeer.isValid () || raPeer.getAccountID () == line->getAccountIDPeer ())
             {
                 const STAmount&     saBalance   = line->getBalance ();
                 const STAmount&     saLimit     = line->getLimit ();
                 const STAmount&     saLimitPeer = line->getLimitPeer ();
                 Json::Value&    jPeer   = jsonLines.append (Json::objectValue);
                 jPeer["account"]        = RippleAddress::createHumanAccountID (line->getAccountIDPeer ());
                 // Amount reported is positive if current account holds other account's IOUs.
                 // Amount reported is negative if other account holds current account's IOUs.
                 jPeer["balance"]        = saBalance.getText ();
                 jPeer["currency"]       = saBalance.getHumanCurrency ();
                 jPeer["limit"]          = saLimit.getText ();
                 jPeer["limit_peer"]     = saLimitPeer.getText ();
                 jPeer["quality_in"]     = static_cast<Json::UInt> (line->getQualityIn ());
                 jPeer["quality_out"]    = static_cast<Json::UInt> (line->getQualityOut ());
                 if (line->getAuth())
                     jPeer["authorized"] = true;
                 if (line->getAuthPeer())
                     jPeer["peer_authorized"] = true;
                 if (line->getNoRipple())
                     jPeer["no_ripple"]  = true;
                 if (line->getNoRipplePeer())
                     jPeer["no_ripple_peer"] = true;
             }
         }
         loadType = Resource::feeMediumBurdenRPC;
     }
     else
     {
         jvResult    = rpcError (rpcACT_NOT_FOUND);
     }
     return jvResult;
 }
Json::Value ripple::RPCHandler::doAccountOffers (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 41 of file AccountOffers.cpp.
References ripple::RPC::accountFromString(), Json::arrayValue, Json::Value::asString(), Json::Value::asUInt(), BIND_TYPE, Json::Value::empty(), ripple::Resource::feeMediumBurdenRPC, ripple::RippleAddress::getAccountID(), ripple::RippleAddress::humanAccountID(), Json::Value::isMember(), ripple::RPC::lookupLedger(), ripple::RPC::missing_field_error(), mNetOps, ripple::offerAdder(), P_1, ripple::rpcACT_NOT_FOUND, and ripple::rpcError().
Referenced by doCommand().
 {
     masterLockHolder.unlock ();
     Ledger::pointer     lpLedger;
     Json::Value         jvResult    = RPC::lookupLedger (params, lpLedger, *mNetOps);
     if (!lpLedger)
         return jvResult;
     if (!params.isMember ("account"))
         return RPC::missing_field_error ("account");
     std::string     strIdent    = params["account"].asString ();
     bool            bIndex      = params.isMember ("account_index");
     int             iIndex      = bIndex ? params["account_index"].asUInt () : 0;
     RippleAddress   raAccount;
     jvResult    = RPC::accountFromString (lpLedger, raAccount, bIndex, strIdent, iIndex, false, *mNetOps);
     if (!jvResult.empty ())
         return jvResult;
     // Get info on account.
     jvResult["account"] = raAccount.humanAccountID ();
     if (bIndex)
         jvResult["account_index"]   = iIndex;
     if (!lpLedger->hasAccount (raAccount))
         return rpcError (rpcACT_NOT_FOUND);
     Json::Value& jvsOffers = (jvResult["offers"] = Json::arrayValue);
     lpLedger->visitAccountItems (raAccount.getAccountID (), BIND_TYPE (&offerAdder, boost::ref (jvsOffers), P_1));
     loadType = Resource::feeMediumBurdenRPC;
     return jvResult;
 }
Json::Value ripple::RPCHandler::doAccountTx (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 32 of file AccountTx.cpp.
References ripple::Config::ADMIN, Json::Value::append(), Json::arrayValue, Json::Value::asBool(), Json::Value::asInt(), Json::Value::asString(), Json::Value::asUInt(), ripple::Resource::feeMediumBurdenRPC, ripple::NetworkOPs::getTxsAccount(), ripple::NetworkOPs::getTxsAccountB(), ripple::NetworkOPs::getValidatedRange(), ripple::RippleAddress::humanAccountID(), Json::Value::isMember(), Json::Value::isNull(), ripple::RPC::lookupLedger(), mNetOps, mRole, Json::objectValue, ripple::rpcACT_MALFORMED, ripple::rpcError(), ripple::rpcINTERNAL, ripple::rpcINVALID_PARAMS, ripple::rpcLGR_IDXS_INVALID, and ripple::RippleAddress::setAccountID().
Referenced by doAccountTxSwitch().
 {
     masterLockHolder.unlock ();
     RippleAddress   raAccount;
     int             limit       = params.isMember ("limit") ? params["limit"].asUInt () : -1;
     bool            bBinary     = params.isMember ("binary") && params["binary"].asBool ();
     bool            bForward    = params.isMember ("forward") && params["forward"].asBool ();
     std::uint32_t   uLedgerMin;
     std::uint32_t   uLedgerMax;
     std::uint32_t   uValidatedMin;
     std::uint32_t   uValidatedMax;
     bool            bValidated  = mNetOps->getValidatedRange (uValidatedMin, uValidatedMax);
     if (!bValidated)
     {
         // Don't have a validated ledger range.
         return rpcError (rpcLGR_IDXS_INVALID);
     }
     if (!params.isMember ("account"))
         return rpcError (rpcINVALID_PARAMS);
     if (!raAccount.setAccountID (params["account"].asString ()))
         return rpcError (rpcACT_MALFORMED);
     loadType = Resource::feeMediumBurdenRPC;
     if (params.isMember ("ledger_index_min") || params.isMember ("ledger_index_max"))
     {
         std::int64_t iLedgerMin  = params.isMember ("ledger_index_min") ? params["ledger_index_min"].asInt () : -1;
         std::int64_t iLedgerMax  = params.isMember ("ledger_index_max") ? params["ledger_index_max"].asInt () : -1;
         uLedgerMin  = iLedgerMin == -1 ? uValidatedMin : iLedgerMin;
         uLedgerMax  = iLedgerMax == -1 ? uValidatedMax : iLedgerMax;
         if (uLedgerMax < uLedgerMin)
         {
             return rpcError (rpcLGR_IDXS_INVALID);
         }
     }
     else
     {
         Ledger::pointer l;
         Json::Value ret = RPC::lookupLedger (params, l, *mNetOps);
         if (!l)
             return ret;
         uLedgerMin = uLedgerMax = l->getLedgerSeq ();
     }
     Json::Value resumeToken;
     if (params.isMember("marker"))
     {
          resumeToken = params["marker"];
     }
 #ifndef BEAST_DEBUG
     try
     {
 #endif
         Json::Value ret (Json::objectValue);
         ret["account"] = raAccount.humanAccountID ();
         Json::Value& jvTxns = (ret["transactions"] = Json::arrayValue);
         if (bBinary)
         {
             std::vector<NetworkOPs::txnMetaLedgerType> txns =
                 mNetOps->getTxsAccountB (raAccount, uLedgerMin, uLedgerMax, bForward, resumeToken, limit, mRole == Config::ADMIN);
             for (std::vector<NetworkOPs::txnMetaLedgerType>::const_iterator it = txns.begin (), end = txns.end ();
                     it != end; ++it)
             {
                 Json::Value& jvObj = jvTxns.append (Json::objectValue);
                 std::uint32_t uLedgerIndex = std::get<2> (*it);
                 jvObj["tx_blob"]           = std::get<0> (*it);
                 jvObj["meta"]              = std::get<1> (*it);
                 jvObj["ledger_index"]      = uLedgerIndex;
                 jvObj["validated"]         = bValidated && uValidatedMin <= uLedgerIndex && uValidatedMax >= uLedgerIndex;
             }
         }
         else
         {
             std::vector< std::pair<Transaction::pointer, TransactionMetaSet::pointer> > txns =
                  mNetOps->getTxsAccount (raAccount, uLedgerMin, uLedgerMax, bForward, resumeToken, limit, mRole == Config::ADMIN);
             for (std::vector< std::pair<Transaction::pointer, TransactionMetaSet::pointer> >::iterator it = txns.begin (), end = txns.end (); it != end; ++it)
             {
                 Json::Value&    jvObj = jvTxns.append (Json::objectValue);
                 if (it->first)
                     jvObj["tx"]             = it->first->getJson (1);
                 if (it->second)
                 {
                     std::uint32_t uLedgerIndex = it->second->getLgrSeq ();
                     jvObj["meta"]           = it->second->getJson (0);
                     jvObj["validated"]      = bValidated && uValidatedMin <= uLedgerIndex && uValidatedMax >= uLedgerIndex;
                 }
             }
         }
         //Add information about the original query
         ret["ledger_index_min"] = uLedgerMin;
         ret["ledger_index_max"] = uLedgerMax;
         if (params.isMember ("limit"))
             ret["limit"]        = limit;
         if (!resumeToken.isNull())
             ret["marker"] = resumeToken;
         return ret;
 #ifndef BEAST_DEBUG
     }
     catch (...)
     {
         return rpcError (rpcINTERNAL);
     }
 #endif
 }
Json::Value ripple::RPCHandler::doAccountTxOld (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 33 of file AccountTxOld.cpp.
References ripple::Config::ADMIN, Json::Value::append(), Json::arrayValue, Json::Value::asBool(), Json::Value::asInt(), Json::Value::asString(), Json::Value::asUInt(), ripple::Resource::feeHighBurdenRPC, ripple::NetworkOPs::getAccountTxs(), ripple::NetworkOPs::getAccountTxsB(), ripple::NetworkOPs::getValidatedRange(), ripple::RippleAddress::humanAccountID(), Json::Value::isMember(), ripple::RPC::lookupLedger(), mNetOps, mRole, Json::objectValue, ripple::rpcACT_MALFORMED, ripple::rpcATX_DEPRECATED, ripple::rpcError(), ripple::rpcINTERNAL, ripple::rpcINVALID_PARAMS, ripple::rpcLGR_IDXS_INVALID, and ripple::RippleAddress::setAccountID().
Referenced by doAccountTxSwitch().
 {
     masterLockHolder.unlock ();
     RippleAddress   raAccount;
     std::uint32_t   offset      = params.isMember ("offset") ? params["offset"].asUInt () : 0;
     int             limit       = params.isMember ("limit") ? params["limit"].asUInt () : -1;
     bool            bBinary     = params.isMember ("binary") && params["binary"].asBool ();
     bool            bDescending = params.isMember ("descending") && params["descending"].asBool ();
     bool            bCount      = params.isMember ("count") && params["count"].asBool ();
     std::uint32_t   uLedgerMin;
     std::uint32_t   uLedgerMax;
     std::uint32_t   uValidatedMin;
     std::uint32_t   uValidatedMax;
     bool            bValidated  = mNetOps->getValidatedRange (uValidatedMin, uValidatedMax);
     if (!params.isMember ("account"))
         return rpcError (rpcINVALID_PARAMS);
     if (!raAccount.setAccountID (params["account"].asString ()))
         return rpcError (rpcACT_MALFORMED);
     if (offset > 3000)
         return rpcError (rpcATX_DEPRECATED);
     loadType = Resource::feeHighBurdenRPC;
     // DEPRECATED
     if (params.isMember ("ledger_min"))
     {
         params["ledger_index_min"]   = params["ledger_min"];
         bDescending = true;
     }
     // DEPRECATED
     if (params.isMember ("ledger_max"))
     {
         params["ledger_index_max"]   = params["ledger_max"];
         bDescending = true;
     }
     if (params.isMember ("ledger_index_min") || params.isMember ("ledger_index_max"))
     {
         std::int64_t iLedgerMin  = params.isMember ("ledger_index_min") ? params["ledger_index_min"].asInt () : -1;
         std::int64_t iLedgerMax  = params.isMember ("ledger_index_max") ? params["ledger_index_max"].asInt () : -1;
         if (!bValidated && (iLedgerMin == -1 || iLedgerMax == -1))
         {
             // Don't have a validated ledger range.
             return rpcError (rpcLGR_IDXS_INVALID);
         }
         uLedgerMin  = iLedgerMin == -1 ? uValidatedMin : iLedgerMin;
         uLedgerMax  = iLedgerMax == -1 ? uValidatedMax : iLedgerMax;
         if (uLedgerMax < uLedgerMin)
         {
             return rpcError (rpcLGR_IDXS_INVALID);
         }
     }
     else
     {
         Ledger::pointer l;
         Json::Value ret = RPC::lookupLedger (params, l, *mNetOps);
         if (!l)
             return ret;
         uLedgerMin = uLedgerMax = l->getLedgerSeq ();
     }
     int count = 0;
 #ifndef BEAST_DEBUG
     try
     {
 #endif
         Json::Value ret (Json::objectValue);
         ret["account"] = raAccount.humanAccountID ();
         Json::Value& jvTxns = (ret["transactions"] = Json::arrayValue);
         if (bBinary)
         {
             std::vector<NetworkOPs::txnMetaLedgerType> txns =
                 mNetOps->getAccountTxsB (raAccount, uLedgerMin, uLedgerMax, bDescending, offset, limit, mRole == Config::ADMIN);
             for (std::vector<NetworkOPs::txnMetaLedgerType>::const_iterator it = txns.begin (), end = txns.end ();
                     it != end; ++it)
             {
                 ++count;
                 Json::Value& jvObj = jvTxns.append (Json::objectValue);
                 std::uint32_t  uLedgerIndex = std::get<2> (*it);
                 jvObj["tx_blob"]            = std::get<0> (*it);
                 jvObj["meta"]               = std::get<1> (*it);
                 jvObj["ledger_index"]       = uLedgerIndex;
                 jvObj["validated"]          = bValidated && uValidatedMin <= uLedgerIndex && uValidatedMax >= uLedgerIndex;
             }
         }
         else
         {
             std::vector< std::pair<Transaction::pointer, TransactionMetaSet::pointer> > txns = mNetOps->getAccountTxs (raAccount, uLedgerMin, uLedgerMax, bDescending, offset, limit, mRole == Config::ADMIN);
             for (std::vector< std::pair<Transaction::pointer, TransactionMetaSet::pointer> >::iterator it = txns.begin (), end = txns.end (); it != end; ++it)
             {
                 ++count;
                 Json::Value&    jvObj = jvTxns.append (Json::objectValue);
                 if (it->first)
                     jvObj["tx"]             = it->first->getJson (1);
                 if (it->second)
                 {
                     std::uint32_t uLedgerIndex = it->second->getLgrSeq ();
                     jvObj["meta"]           = it->second->getJson (0);
                     jvObj["validated"]      = bValidated && uValidatedMin <= uLedgerIndex && uValidatedMax >= uLedgerIndex;
                 }
             }
         }
         //Add information about the original query
         ret["ledger_index_min"] = uLedgerMin;
         ret["ledger_index_max"] = uLedgerMax;
         ret["validated"]        = bValidated && uValidatedMin <= uLedgerMin && uValidatedMax >= uLedgerMax;
         ret["offset"]           = offset;
         // We no longer return the full count but only the count of returned transactions
         // Computing this count was two expensive and this API is deprecated anyway
         if (bCount)
             ret["count"]        = count;
         if (params.isMember ("limit"))
             ret["limit"]        = limit;
         return ret;
 #ifndef BEAST_DEBUG
     }
     catch (...)
     {
         return rpcError (rpcINTERNAL);
     }
 #endif
 }
Json::Value ripple::RPCHandler::doAccountTxSwitch (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 23 of file AccountTxSwitch.cpp.
References doAccountTx(), doAccountTxOld(), and Json::Value::isMember().
Referenced by doCommand().
 {
     if (params.isMember("offset") || params.isMember("count") || params.isMember("descending") ||
             params.isMember("ledger_max") || params.isMember("ledger_min"))
         return doAccountTxOld(params, loadType, masterLockHolder);
     return doAccountTx(params, loadType, masterLockHolder);
 }
Json::Value ripple::RPCHandler::doBlackList (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 23 of file BlackList.cpp.
References ripple::getApp(), ripple::Resource::Manager::getJson(), ripple::Application::getResourceManager(), and Json::Value::isMember().
Referenced by doCommand().
 {
     masterLockHolder.unlock();
     if (params.isMember("threshold"))
         return getApp().getResourceManager().getJson(params["threshold"].asInt());
     else
         return getApp().getResourceManager().getJson();
 }
Json::Value ripple::RPCHandler::doBookOffers (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 49 of file BookOffers.cpp.
References ACCOUNT_ONE, Json::Value::asString(), Json::Value::asUInt(), ripple::STAmount::currencyFromString(), ripple::RPC::expected_field_error(), ripple::Resource::feeMediumBurdenRPC, ripple::RippleAddress::getAccountID(), ripple::getApp(), ripple::NetworkOPs::getBookPage(), ripple::RPC::invalid_field_error(), ripple::is_not_xrp(), ripple::is_xrp(), Json::Value::isIntegral(), Json::Value::isMember(), ripple::STAmount::issuerFromString(), ripple::jtCLIENT, ripple::RPC::lookupLedger(), ripple::lsINFO, ripple::RPC::make_error(), ripple::RPC::missing_field_error(), mNetOps, ripple::neutral_issuer(), Json::nullValue, ripple::RPC::object_field_error(), ripple::rpcBAD_MARKET, ripple::rpcDST_AMT_MALFORMED, ripple::rpcDST_ISR_MALFORMED, ripple::rpcError(), ripple::rpcSRC_CUR_MALFORMED, ripple::rpcSRC_ISR_MALFORMED, ripple::rpcTOO_BUSY, ripple::RippleAddress::setAccountID(), rocksdb::crc32c::Value(), WriteLog, and ripple::xrp_issuer().
Referenced by doCommand().
 {
     masterLockHolder.unlock ();
     // VFALCO TODO Here is a terrible place for this kind of business
     //             logic. It needs to be moved elsewhere and documented,
     //             and encapsulated into a function.
     if (getApp().getJobQueue ().getJobCountGE (jtCLIENT) > 200)
         return rpcError (rpcTOO_BUSY);
     Ledger::pointer lpLedger;
     Json::Value jvResult (RPC::lookupLedger (params, lpLedger, *mNetOps));
     if (!lpLedger)
         return jvResult;
     if (!params.isMember ("taker_pays"))
         return RPC::missing_field_error ("taker_pays");
     if (!params.isMember ("taker_gets"))
         return RPC::missing_field_error ("taker_gets");
     if (!params["taker_pays"].isObject ())
         return RPC::object_field_error ("taker_pays");
     if (!params["taker_gets"].isObject ())
         return RPC::object_field_error ("taker_gets");
     Json::Value const& taker_pays (params["taker_pays"]);
     if (!taker_pays.isMember ("currency"))
         return RPC::missing_field_error ("taker_pays.currency");
     if (! taker_pays ["currency"].isString ())
         return RPC::expected_field_error ("taker_pays.currency", "string");
     Json::Value const& taker_gets = params["taker_gets"];
     if (! taker_gets.isMember ("currency"))
         return RPC::missing_field_error ("taker_gets.currency");
     if (! taker_gets ["currency"].isString ())
         return RPC::expected_field_error ("taker_gets.currency", "string");
     uint160 pay_currency;
     if (! STAmount::currencyFromString (
         pay_currency, taker_pays ["currency"].asString ()))
     {
         WriteLog (lsINFO, RPCHandler) << "Bad taker_pays currency.";
         return RPC::make_error (rpcSRC_CUR_MALFORMED,
             "Invalid field 'taker_pays.currency', bad currency.");
     }
     uint160 get_currency;
     if (! STAmount::currencyFromString (
         get_currency, taker_gets ["currency"].asString ()))
     {
         WriteLog (lsINFO, RPCHandler) << "Bad taker_gets currency.";
         return RPC::make_error (rpcDST_AMT_MALFORMED,
             "Invalid field 'taker_gets.currency', bad currency.");
     }
     uint160 pay_issuer;
     if (taker_pays.isMember ("issuer"))
     {
         if (! taker_pays ["issuer"].isString())
             return RPC::expected_field_error ("taker_pays.issuer", "string");
         if (! STAmount::issuerFromString (
             pay_issuer, taker_pays ["issuer"].asString ()))
             return RPC::make_error (rpcSRC_ISR_MALFORMED,
                 "Invalid field 'taker_pays.issuer', bad issuer.");
         if (pay_issuer == neutral_issuer ())
             return RPC::make_error (rpcSRC_ISR_MALFORMED,
                 "Invalid field 'taker_pays.issuer', bad issuer account one.");
     }
     else
     {
         pay_issuer = xrp_issuer ();
     }
     if (is_xrp (pay_currency) && ! is_xrp (pay_issuer))
         return RPC::make_error (rpcSRC_ISR_MALFORMED,
             "Unneeded field 'taker_pays.issuer' for XRP currency specification.");
     if (is_not_xrp (pay_currency) && is_xrp (pay_issuer))
         return RPC::make_error (rpcSRC_ISR_MALFORMED,
             "Invalid field 'taker_pays.issuer', expected non-XRP issuer.");
     uint160 get_issuer;
     if (taker_gets.isMember ("issuer"))
     {
         if (! taker_gets ["issuer"].isString())
             return RPC::expected_field_error ("taker_gets.issuer", "string");
         if (! STAmount::issuerFromString (
             get_issuer, taker_gets ["issuer"].asString ()))
             return RPC::make_error (rpcDST_ISR_MALFORMED,
                 "Invalid field 'taker_gets.issuer', bad issuer.");
         if (get_issuer == neutral_issuer ())
             return RPC::make_error (rpcDST_ISR_MALFORMED,
                 "Invalid field 'taker_gets.issuer', bad issuer account one.");
     }
     else
     {
         get_issuer = xrp_issuer ();
     }
     if (is_xrp (get_currency) && ! is_xrp (get_issuer))
         return RPC::make_error (rpcDST_ISR_MALFORMED,
             "Unneeded field 'taker_gets.issuer' for XRP currency specification.");
     if (is_not_xrp (get_currency) && is_xrp (get_issuer))
         return RPC::make_error (rpcDST_ISR_MALFORMED,
             "Invalid field 'taker_gets.issuer', expected non-XRP issuer.");
     RippleAddress raTakerID;
     if (params.isMember ("taker"))
     {
         if (! params ["taker"].isString ())
             return RPC::expected_field_error ("taker", "string");
         if (! raTakerID.setAccountID (params ["taker"].asString ()))
             return RPC::invalid_field_error ("taker");
     }
     else
     {
         raTakerID.setAccountID (ACCOUNT_ONE);
     }
     if (pay_currency == get_currency && pay_issuer == get_issuer)
     {
         WriteLog (lsINFO, RPCHandler) << "taker_gets same as taker_pays.";
         return RPC::make_error (rpcBAD_MARKET);
     }
     if (params.isMember ("limit") && ! params ["limit"].isIntegral())
         return RPC::expected_field_error (
         "limit", "integer");
     unsigned int const iLimit (params.isMember ("limit")
         ? params ["limit"].asUInt ()
         : 0);
     bool const bProof (params.isMember ("proof"));
     Json::Value const jvMarker (params.isMember ("marker")
         ? params["marker"]
         : Json::Value (Json::nullValue));
     mNetOps->getBookPage (lpLedger, pay_currency, pay_issuer,
         get_currency, get_issuer, raTakerID.getAccountID (),
             bProof, iLimit, jvMarker, jvResult);
     loadType = Resource::feeMediumBurdenRPC;
     return jvResult;
 }
Json::Value ripple::RPCHandler::doCommand (const Json::Value & jvRequest, int role, Resource::Charge & loadType)
Definition at line 88 of file RPCHandler.cpp.
References ripple::Config::ADMIN, Json::Value::asString(), doAccountCurrencies(), doAccountInfo(), doAccountLines(), doAccountOffers(), doAccountTxSwitch(), doBlackList(), doBookOffers(), doConnect(), doConsensusInfo(), doFeature(), doFetchInfo(), doGetCounts(), doInternal(), doLedger(), doLedgerAccept(), doLedgerCleaner(), doLedgerClosed(), doLedgerCurrent(), doLedgerData(), doLedgerEntry(), doLedgerHeader(), doLogLevel(), doLogRotate(), doOwnerInfo(), doPathFind(), doPeers(), doPing(), doPrint(), doProofCreate(), doProofSolve(), doProofVerify(), doRandom(), doRipplePathFind(), doServerInfo(), doServerState(), doSign(), doSMS(), doStop(), doSubmit(), doSubscribe(), doTransactionEntry(), doTx(), doTxHistory(), doUnlAdd(), doUnlDelete(), doUnlList(), doUnlLoad(), doUnlNetwork(), doUnlReset(), doUnlScore(), doUnsubscribe(), doValidationCreate(), doValidationSeed(), doWalletAccounts(), doWalletPropose(), doWalletSeed(), ripple::Resource::feeExceptionRPC, ripple::Resource::feeReferenceRPC, ripple::getApp(), ripple::NetworkOPs::getClosedLedger(), ripple::getConfig(), ripple::JobQueue::getJobCountGE(), ripple::Application::getJobQueue(), ripple::JobQueue::getLoadEventAP(), ripple::NetworkOPs::getOperatingMode(), Json::Value::isMember(), Json::Value::isObject(), ripple::jtCLIENT, ripple::jtGENERIC, ripple::lsDEBUG, ripple::lsINFO, ripple::lsTRACE, mNetOps, mRole, NUMBER, Json::objectValue, ripple::NetworkOPs::omSYNCING, optClosed, optCurrent, optNetwork, optNone, ripple::rpcCOMMAND_MISSING, ripple::rpcError(), ripple::rpcINTERNAL, ripple::rpcNO_CLOSED, ripple::rpcNO_CURRENT, ripple::rpcNO_NETWORK, ripple::rpcNO_PERMISSION, ripple::rpcTOO_BUSY, ripple::rpcUNKNOWN_COMMAND, ripple::NetworkOPs::strOperatingMode(), and WriteLog.
Referenced by doRpcCommand(), ripple::WSConnection::invokeCommand(), and ripple::startServer().
 {
     if (iRole != Config::ADMIN)
     {
         // VFALCO NOTE Should we also add up the jtRPC jobs?
         //
         int jc = getApp().getJobQueue ().getJobCountGE (jtCLIENT);
         if (jc > 500)
         {
             WriteLog (lsDEBUG, RPCHandler) << "Too busy for command: " << jc;
             return rpcError (rpcTOO_BUSY);
         }
     }
     if (!params.isMember ("command"))
         return rpcError (rpcCOMMAND_MISSING);
     std::string     strCommand  = params["command"].asString ();
     WriteLog (lsTRACE, RPCHandler) << "COMMAND:" << strCommand;
     WriteLog (lsTRACE, RPCHandler) << "REQUEST:" << params;
     mRole   = iRole;
     static struct
     {
         const char*     pCommand;
         doFuncPtr       dfpFunc;
         bool            bAdminRequired;
         unsigned int    iOptions;
     } commandsA[] =
     {
         // Request-response methods
         {   "account_info",         &RPCHandler::doAccountInfo,         false,  optCurrent  },
         {   "account_currencies",   &RPCHandler::doAccountCurrencies,   false,  optCurrent  },
         {   "account_lines",        &RPCHandler::doAccountLines,        false,  optCurrent  },
         {   "account_offers",       &RPCHandler::doAccountOffers,       false,  optCurrent  },
         {   "account_tx",           &RPCHandler::doAccountTxSwitch,     false,  optNetwork  },
         {   "blacklist",            &RPCHandler::doBlackList,           true,   optNone     },
         {   "book_offers",          &RPCHandler::doBookOffers,          false,  optCurrent  },
         {   "connect",              &RPCHandler::doConnect,             true,   optNone     },
         {   "consensus_info",       &RPCHandler::doConsensusInfo,       true,   optNone     },
         {   "get_counts",           &RPCHandler::doGetCounts,           true,   optNone     },
         {   "internal",             &RPCHandler::doInternal,            true,   optNone     },
         {   "feature",              &RPCHandler::doFeature,             true,   optNone     },
         {   "fetch_info",           &RPCHandler::doFetchInfo,           true,   optNone     },
         {   "ledger",               &RPCHandler::doLedger,              false,  optNetwork  },
         {   "ledger_accept",        &RPCHandler::doLedgerAccept,        true,   optCurrent  },
         {   "ledger_cleaner",       &RPCHandler::doLedgerCleaner,       true,   optNetwork  },
         {   "ledger_closed",        &RPCHandler::doLedgerClosed,        false,  optClosed   },
         {   "ledger_current",       &RPCHandler::doLedgerCurrent,       false,  optCurrent  },
         {   "ledger_data",          &RPCHandler::doLedgerData,          false,  optCurrent  },
         {   "ledger_entry",         &RPCHandler::doLedgerEntry,         false,  optCurrent  },
         {   "ledger_header",        &RPCHandler::doLedgerHeader,        false,  optCurrent  },
         {   "log_level",            &RPCHandler::doLogLevel,            true,   optNone     },
         {   "logrotate",            &RPCHandler::doLogRotate,           true,   optNone     },
 //      {   "nickname_info",        &RPCHandler::doNicknameInfo,        false,  optCurrent  },
         {   "owner_info",           &RPCHandler::doOwnerInfo,           false,  optCurrent  },
         {   "peers",                &RPCHandler::doPeers,               true,   optNone     },
         {   "path_find",            &RPCHandler::doPathFind,            false,  optCurrent  },
         {   "ping",                 &RPCHandler::doPing,                false,  optNone     },
         {   "print",                &RPCHandler::doPrint,               true,   optNone     },
 //      {   "profile",              &RPCHandler::doProfile,             false,  optCurrent  },
         {   "proof_create",         &RPCHandler::doProofCreate,         true,   optNone     },
         {   "proof_solve",          &RPCHandler::doProofSolve,          true,   optNone     },
         {   "proof_verify",         &RPCHandler::doProofVerify,         true,   optNone     },
         {   "random",               &RPCHandler::doRandom,              false,  optNone     },
         {   "ripple_path_find",     &RPCHandler::doRipplePathFind,      false,  optCurrent  },
         {   "sign",                 &RPCHandler::doSign,                false,  optNone     },
         {   "submit",               &RPCHandler::doSubmit,              false,  optCurrent  },
         {   "server_info",          &RPCHandler::doServerInfo,          false,  optNone     },
         {   "server_state",         &RPCHandler::doServerState,         false,  optNone     },
         {   "sms",                  &RPCHandler::doSMS,                 true,   optNone     },
         {   "stop",                 &RPCHandler::doStop,                true,   optNone     },
         {   "transaction_entry",    &RPCHandler::doTransactionEntry,    false,  optCurrent  },
         {   "tx",                   &RPCHandler::doTx,                  false,  optNetwork  },
         {   "tx_history",           &RPCHandler::doTxHistory,           false,  optNone     },
         {   "unl_add",              &RPCHandler::doUnlAdd,              true,   optNone     },
         {   "unl_delete",           &RPCHandler::doUnlDelete,           true,   optNone     },
         {   "unl_list",             &RPCHandler::doUnlList,             true,   optNone     },
         {   "unl_load",             &RPCHandler::doUnlLoad,             true,   optNone     },
         {   "unl_network",          &RPCHandler::doUnlNetwork,          true,   optNone     },
         {   "unl_reset",            &RPCHandler::doUnlReset,            true,   optNone     },
         {   "unl_score",            &RPCHandler::doUnlScore,            true,   optNone     },
         {   "validation_create",    &RPCHandler::doValidationCreate,    true,   optNone     },
         {   "validation_seed",      &RPCHandler::doValidationSeed,      true,   optNone     },
         {   "wallet_accounts",      &RPCHandler::doWalletAccounts,      false,  optCurrent  },
         {   "wallet_propose",       &RPCHandler::doWalletPropose,       true,   optNone     },
         {   "wallet_seed",          &RPCHandler::doWalletSeed,          true,   optNone     },
         // Evented methods
         {   "subscribe",            &RPCHandler::doSubscribe,           false,  optNone     },
         {   "unsubscribe",          &RPCHandler::doUnsubscribe,         false,  optNone     },
     };
     int     i = NUMBER (commandsA);
     while (i-- && strCommand != commandsA[i].pCommand)
         ;
     if (i < 0)
     {
         return rpcError (rpcUNKNOWN_COMMAND);
     }
     else if (commandsA[i].bAdminRequired && mRole != Config::ADMIN)
     {
         return rpcError (rpcNO_PERMISSION);
     }
     {
         Application::ScopedLockType lock (getApp().getMasterLock ());
         if ((commandsA[i].iOptions & optNetwork) && (mNetOps->getOperatingMode () < NetworkOPs::omSYNCING))
         {
             WriteLog (lsINFO, RPCHandler) << "Insufficient network mode for RPC: " << mNetOps->strOperatingMode ();
             return rpcError (rpcNO_NETWORK);
         }
         if (!getConfig ().RUN_STANDALONE && (commandsA[i].iOptions & optCurrent) && (getApp().getLedgerMaster().getValidatedLedgerAge() > 120))
         {
             return rpcError (rpcNO_CURRENT);
         }
         else if ((commandsA[i].iOptions & optClosed) && !mNetOps->getClosedLedger ())
         {
             return rpcError (rpcNO_CLOSED);
         }
         else
         {
             try
             {
                 LoadEvent::autoptr ev   = getApp().getJobQueue().getLoadEventAP(
                     jtGENERIC, std::string("cmd:") + strCommand);
                 Json::Value jvRaw       = (this->* (commandsA[i].dfpFunc)) (params, loadType, lock);
                 // Regularize result.
                 if (jvRaw.isObject ())
                 {
                     // Got an object.
                     return jvRaw;
                 }
                 else
                 {
                     // Probably got a string.
                     Json::Value jvResult (Json::objectValue);
                     jvResult["message"] = jvRaw;
                     return jvResult;
                 }
             }
             catch (std::exception& e)
             {
                 WriteLog (lsINFO, RPCHandler) << "Caught throw: " << e.what ();
                 if (loadType == Resource::feeReferenceRPC)
                     loadType = Resource::feeExceptionRPC;
                 return rpcError (rpcINTERNAL);
             }
         }
     }
 }
Json::Value ripple::RPCHandler::doConnect (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 29 of file Connect.cpp.
References beast::IP::Endpoint::at_port(), ripple::Overlay::connect(), beast::IP::Endpoint::from_string(), ripple::getApp(), ripple::getConfig(), Json::intValue, beast::IP::is_unspecified(), Json::Value::isConvertibleTo(), Json::Value::isMember(), ripple::RPC::missing_field_error(), ripple::Application::overlay(), ripple::rpcError(), ripple::rpcINVALID_PARAMS, and ripple::SYSTEM_PEER_PORT.
Referenced by doCommand().
 {
     if (getConfig ().RUN_STANDALONE)
         return "cannot connect in standalone mode";
     if (!params.isMember ("ip"))
         return RPC::missing_field_error ("ip");
     if (params.isMember ("port") && !params["port"].isConvertibleTo (Json::intValue))
         return rpcError (rpcINVALID_PARAMS);
     int iPort;
     if(params.isMember ("port"))
         iPort = params["port"].asInt ();
     else
         iPort = SYSTEM_PEER_PORT;
     beast::IP::Endpoint ip (beast::IP::Endpoint::from_string(params["ip"].asString ()));
     if (! is_unspecified (ip))
         getApp().overlay ().connect (ip.at_port(iPort));
     return "connecting";
 }
Json::Value ripple::RPCHandler::doConsensusInfo (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 22 of file ConsensusInfo.cpp.
References ripple::NetworkOPs::getConsensusInfo(), mNetOps, and Json::objectValue.
Referenced by doCommand().
 {
     Json::Value ret (Json::objectValue);
     ret["info"] = mNetOps->getConsensusInfo ();
     return ret;
 }
Json::Value ripple::RPCHandler::doFeature (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 43 of file Feature.cpp.
References ripple::FeatureTable::get(), ripple::getApp(), ripple::Application::getFeatureTable(), ripple::FeatureTable::getJson(), Json::Value::isMember(), ripple::base_uint< BITS >::isZero(), Json::objectValue, ripple::rpcBAD_FEATURE, ripple::rpcError(), ripple::rpcNOT_SUPPORTED, and ripple::base_uint< BITS >::SetHex().
Referenced by doCommand().
 {
     if (!params.isMember ("feature"))
     {
         Json::Value jvReply = Json::objectValue;
         jvReply["features"] = getApp().getFeatureTable ().getJson (0);
         return jvReply;
     }
     uint256 uFeature = getApp().getFeatureTable ().get (params["feature"].asString ());
     if (uFeature.isZero ())
     {
         uFeature.SetHex (params["feature"].asString ());
         if (uFeature.isZero ())
             return rpcError (rpcBAD_FEATURE);
     }
     if (!params.isMember ("vote"))
         return getApp().getFeatureTable ().getJson (uFeature);
     // WRITEME
     return rpcError (rpcNOT_SUPPORTED);
 }
Json::Value ripple::RPCHandler::doFetchInfo (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 23 of file FetchInfo.cpp.
References Json::Value::asBool(), ripple::NetworkOPs::clearLedgerFetch(), ripple::NetworkOPs::getLedgerFetchInfo(), Json::Value::isMember(), mNetOps, and Json::objectValue.
Referenced by doCommand().
 {
     masterLockHolder.unlock ();
     Json::Value ret (Json::objectValue);
     if (jvParams.isMember("clear") && jvParams["clear"].asBool())
     {
         mNetOps->clearLedgerFetch();
         ret["clear"] = true;
     }
     ret["info"] = mNetOps->getLedgerFetchInfo();
     return ret;
 }
Json::Value ripple::RPCHandler::doGetCounts (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 26 of file GetCounts.cpp.
References ripple::getApp(), ripple::AcceptedLedger::getCacheHitRate(), ripple::NodeStore::Database::getCacheHitRate(), ripple::LedgerMaster::getCacheHitRate(), ripple::CountedObjects::getCounts(), ripple::DatabaseCon::getDB(), ripple::UptimeTimer::getElapsedSeconds(), ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::getHitRate(), ripple::CountedObjects::getInstance(), ripple::UptimeTimer::getInstance(), ripple::Database::getKBUsedAll(), ripple::Database::getKBUsedDB(), ripple::Application::getLedgerDB(), ripple::Application::getLedgerMaster(), ripple::NetworkOPs::getLocalTxCount(), ripple::Application::getNodeStore(), ripple::Application::getOPs(), ripple::Application::getSLECache(), ripple::SHAMap::getTreeNodeSize(), ripple::Application::getTxnDB(), ripple::NodeStore::Database::getWriteLoad(), Json::Value::isMember(), Json::objectValue, and ripple::textTime().
Referenced by doCommand().
 {
     int minCount = 10;
     if (params.isMember ("min_count"))
         minCount = params["min_count"].asUInt ();
     CountedObjects::List objectCounts = CountedObjects::getInstance ().getCounts (minCount);
     Json::Value ret (Json::objectValue);
     BOOST_FOREACH (CountedObjects::Entry& it, objectCounts)
     {
         ret [it.first] = it.second;
     }
     int dbKB = getApp().getLedgerDB ()->getDB ()->getKBUsedAll ();
     if (dbKB > 0)
         ret["dbKBTotal"] = dbKB;
     dbKB = getApp().getLedgerDB ()->getDB ()->getKBUsedDB ();
     if (dbKB > 0)
         ret["dbKBLedger"] = dbKB;
     dbKB = getApp().getTxnDB ()->getDB ()->getKBUsedDB ();
     if (dbKB > 0)
         ret["dbKBTransaction"] = dbKB;
     {
         std::size_t c = getApp().getOPs().getLocalTxCount ();
         if (c > 0)
             ret["local_txs"] = static_cast<Json::UInt> (c);
     }
     ret["write_load"] = getApp().getNodeStore ().getWriteLoad ();
     ret["SLE_hit_rate"] = getApp().getSLECache ().getHitRate ();
     ret["node_hit_rate"] = getApp().getNodeStore ().getCacheHitRate ();
     ret["ledger_hit_rate"] = getApp().getLedgerMaster ().getCacheHitRate ();
     ret["AL_hit_rate"] = AcceptedLedger::getCacheHitRate ();
     ret["fullbelow_size"] = int(getApp().getFullBelowCache().size());
     ret["treenode_size"] = SHAMap::getTreeNodeSize ();
     std::string uptime;
     int s = UptimeTimer::getInstance ().getElapsedSeconds ();
     textTime (uptime, s, "year", 365 * 24 * 60 * 60);
     textTime (uptime, s, "day", 24 * 60 * 60);
     textTime (uptime, s, "hour", 60 * 60);
     textTime (uptime, s, "minute", 60);
     textTime (uptime, s, "second", 1);
     ret["uptime"] = uptime;
     return ret;
 }
Json::Value ripple::RPCHandler::doInternal (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 79 of file RPCHandler.cpp.
References Json::Value::isMember(), ripple::rpcError(), ripple::rpcINVALID_PARAMS, and ripple::RPCInternalHandler::runHandler().
Referenced by doCommand().
 {
     // Used for debug or special-purpose RPC commands
     if (!params.isMember ("internal_command"))
         return rpcError (rpcINVALID_PARAMS);
     return RPCInternalHandler::runHandler (params["internal_command"].asString (), params["params"]);
 }
Json::Value ripple::RPCHandler::doLedger (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 28 of file Ledger.cpp.
References ripple::Config::ADMIN, Json::Value::asBool(), ripple::Resource::feeHighBurdenRPC, ripple::getApp(), ripple::LedgerMaster::getClosedLedger(), ripple::LedgerMaster::getCurrentLedger(), ripple::Application::getLedgerMaster(), Json::Value::isMember(), LEDGER_JSON_DUMP_STATE, LEDGER_JSON_DUMP_TXRP, LEDGER_JSON_EXPAND, LEDGER_JSON_FULL, ripple::RPC::lookupLedger(), ripple::lsDEBUG, mNetOps, mRole, Json::objectValue, ripple::rpcError(), ripple::rpcNO_PERMISSION, ripple::rpcTOO_BUSY, and WriteLog.
Referenced by doCommand().
 {
     masterLockHolder.unlock ();
     if (!params.isMember ("ledger") && !params.isMember ("ledger_hash") && !params.isMember ("ledger_index"))
     {
         Json::Value ret (Json::objectValue), current (Json::objectValue), closed (Json::objectValue);
         getApp().getLedgerMaster ().getCurrentLedger ()->addJson (current, 0);
         getApp().getLedgerMaster ().getClosedLedger ()->addJson (closed, 0);
         ret["open"] = current;
         ret["closed"] = closed;
         return ret;
     }
     Ledger::pointer     lpLedger;
     Json::Value         jvResult    = RPC::lookupLedger (params, lpLedger, *mNetOps);
     if (!lpLedger)
         return jvResult;
     bool    bFull           = params.isMember ("full") && params["full"].asBool ();
     bool    bTransactions   = params.isMember ("transactions") && params["transactions"].asBool ();
     bool    bAccounts       = params.isMember ("accounts") && params["accounts"].asBool ();
     bool    bExpand         = params.isMember ("expand") && params["expand"].asBool ();
     int     iOptions        = (bFull ? LEDGER_JSON_FULL : 0)
                               | (bExpand ? LEDGER_JSON_EXPAND : 0)
                               | (bTransactions ? LEDGER_JSON_DUMP_TXRP : 0)
                               | (bAccounts ? LEDGER_JSON_DUMP_STATE : 0);
     if (bFull || bAccounts)
     {
         if (mRole != Config::ADMIN)
         {
             // Until some sane way to get full ledgers has been implemented, disallow
             // retrieving all state nodes
             return rpcError (rpcNO_PERMISSION);
         }
         if (getApp().getFeeTrack().isLoadedLocal() && (mRole != Config::ADMIN))
         {
             WriteLog (lsDEBUG, Peer) << "Too busy to give full ledger";
             return rpcError(rpcTOO_BUSY);
         }
         loadType = Resource::feeHighBurdenRPC;
     }
     Json::Value ret (Json::objectValue);
     lpLedger->addJson (ret, iOptions);
     return ret;
 }
Json::Value ripple::RPCHandler::doLedgerAccept (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 23 of file LedgerAccept.cpp.
References ripple::NetworkOPs::acceptLedger(), ripple::getConfig(), ripple::NetworkOPs::getCurrentLedgerID(), and mNetOps.
Referenced by doCommand().
 {
     Json::Value jvResult;
     if (!getConfig ().RUN_STANDALONE)
     {
         jvResult["error"]   = "notStandAlone";
     }
     else
     {
         mNetOps->acceptLedger ();
         jvResult["ledger_current_index"]    = mNetOps->getCurrentLedgerID ();
     }
     return jvResult;
 }
Json::Value ripple::RPCHandler::doLedgerCleaner (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 23 of file LedgerCleaner.cpp.
References ripple::LedgerMaster::doLedgerCleaner(), ripple::getApp(), and ripple::Application::getLedgerMaster().
Referenced by doCommand().
 {
     masterLockHolder.unlock();
     getApp().getLedgerMaster().doLedgerCleaner (parameters);
     return "Cleaner configured";
 }
Json::Value ripple::RPCHandler::doLedgerClosed (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 23 of file LedgerClosed.cpp.
References ripple::NetworkOPs::getClosedLedgerHash(), ripple::NetworkOPs::getLedgerID(), mNetOps, and ripple::base_uint< BITS >::ToString().
Referenced by doCommand().
 {
     masterLockHolder.unlock ();
     Json::Value jvResult;
     uint256 uLedger = mNetOps->getClosedLedgerHash ();
     jvResult["ledger_index"]        = mNetOps->getLedgerID (uLedger);
     jvResult["ledger_hash"]         = uLedger.ToString ();
     //jvResult["ledger_time"]       = uLedger.
     return jvResult;
 }
Json::Value ripple::RPCHandler::doLedgerCurrent (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 23 of file LedgerCurrent.cpp.
References ripple::NetworkOPs::getCurrentLedgerID(), and mNetOps.
Referenced by doCommand().
 {
     masterLockHolder.unlock ();
     Json::Value jvResult;
     jvResult["ledger_current_index"]    = mNetOps->getCurrentLedgerID ();
     return jvResult;
 }
Json::Value ripple::RPCHandler::doLedgerData (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 33 of file LedgerData.cpp.
References ripple::Config::ADMIN, Json::Value::append(), Json::arrayValue, Json::Value::asBool(), Json::Value::asInt(), Json::Value::asString(), ripple::RPC::expected_field_error(), ripple::base_uint< BITS >::GetHex(), Json::Value::isBool(), Json::Value::isIntegral(), Json::Value::isMember(), Json::Value::isString(), ripple::RPC::lookupLedger(), mNetOps, mRole, Json::objectValue, ripple::SHAMap::peekNextItem(), ripple::base_uint< BITS >::SetHex(), and ripple::strHex().
Referenced by doCommand().
 {
     masterLockHolder.unlock ();
     int const BINARY_PAGE_LENGTH = 256;
     int const JSON_PAGE_LENGTH = 2048;
     Ledger::pointer lpLedger;
     Json::Value jvResult = RPC::lookupLedger (params, lpLedger, *mNetOps);
     if (!lpLedger)
         return jvResult;
     uint256 resumePoint;
     if (params.isMember ("marker"))
     {
         Json::Value const& jMarker = params["marker"];
         if (!jMarker.isString ())
             return RPC::expected_field_error ("marker", "valid");
         if (!resumePoint.SetHex (jMarker.asString ()))
             return RPC::expected_field_error ("marker", "valid");
     }
     bool isBinary = false;
     if (params.isMember ("binary"))
     {
         Json::Value const& jBinary = params["binary"];
         if (!jBinary.isBool ())
             return RPC::expected_field_error ("binary", "bool");
         isBinary = jBinary.asBool ();
     }
     int limit = -1;
     int maxLimit = isBinary ? BINARY_PAGE_LENGTH : JSON_PAGE_LENGTH;
     if (params.isMember ("limit"))
     {
         Json::Value const& jLimit = params["limit"];
         if (!jLimit.isIntegral ())
             return RPC::expected_field_error ("limit", "integer");
         limit = jLimit.asInt ();
     }
     if ((limit < 0) || ((limit > maxLimit) && (mRole != Config::ADMIN)))
         limit = maxLimit;
     Json::Value jvReply = Json::objectValue;
     jvReply["ledger_hash"] = lpLedger->getHash().GetHex ();
     jvReply["ledger_index"] = beast::lexicalCastThrow <std::string> (lpLedger->getLedgerSeq ());
     Json::Value& nodes = (jvReply["state"] = Json::arrayValue);
     SHAMap& map = *(lpLedger->peekAccountStateMap ());
     for (;;)
     {
        SHAMapItem::pointer item = map.peekNextItem (resumePoint);
        if (!item)
            break;
        resumePoint = item->getTag();
        if (limit-- <= 0)
        {
            --resumePoint;
            jvReply["marker"] = resumePoint.GetHex ();
            break;
        }
        if (isBinary)
        {
            Json::Value& entry = nodes.append (Json::objectValue);
            entry["data"] = strHex (item->peekData().begin(), item->peekData().size());
            entry["index"] = item->getTag ().GetHex ();
        }
        else
        {
            SLE sle (item->peekSerializer(), item->getTag ());
            Json::Value& entry = nodes.append (sle.getJson (0));
            entry["index"] = item->getTag ().GetHex ();
        }
     }
     return jvReply;
 }
Json::Value ripple::RPCHandler::doLedgerEntry (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 28 of file LedgerEntry.cpp.
References Json::Value::asString(), Json::Value::asUInt(), ripple::RippleAddress::createGeneratorPublic(), ripple::STAmount::currencyFromString(), ripple::RippleAddress::getAccountID(), ripple::Ledger::getAccountRootIndex(), ripple::Ledger::getDirNodeIndex(), ripple::Ledger::getGeneratorIndex(), ripple::Ledger::getOfferIndex(), ripple::Ledger::getOwnerDirIndex(), ripple::Ledger::getRippleStateIndex(), ripple::NetworkOPs::getSLEi(), Json::Value::isArray(), Json::Value::isMember(), ripple::base_uint< BITS >::isNonZero(), Json::Value::isObject(), Json::Value::isString(), ripple::RPC::lookupLedger(), mNetOps, ripple::Serializer::peekData(), ripple::RippleAddress::setAccountID(), ripple::RippleAddress::setAccountPublic(), ripple::base_uint< BITS >::SetHex(), ripple::RippleAddress::setSeedGeneric(), Json::Value::size(), ripple::strHex(), and ripple::base_uint< BITS >::ToString().
Referenced by doCommand().
 {
     masterLockHolder.unlock ();
     Ledger::pointer     lpLedger;
     Json::Value         jvResult    = RPC::lookupLedger (params, lpLedger, *mNetOps);
     if (!lpLedger)
         return jvResult;
     uint256     uNodeIndex;
     bool        bNodeBinary = false;
     if (params.isMember ("index"))
     {
         // XXX Needs to provide proof.
         uNodeIndex.SetHex (params["index"].asString ());
         bNodeBinary = true;
     }
     else if (params.isMember ("account_root"))
     {
         RippleAddress   naAccount;
         if (!naAccount.setAccountID (params["account_root"].asString ())
                 || !naAccount.getAccountID ())
         {
             jvResult["error"]   = "malformedAddress";
         }
         else
         {
             uNodeIndex = Ledger::getAccountRootIndex (naAccount.getAccountID ());
         }
     }
     else if (params.isMember ("directory"))
     {
         if (!params["directory"].isObject ())
         {
             uNodeIndex.SetHex (params["directory"].asString ());
         }
         else if (params["directory"].isMember ("sub_index")
                  && !params["directory"]["sub_index"].isIntegral ())
         {
             jvResult["error"]   = "malformedRequest";
         }
         else
         {
             std::uint64_t  uSubIndex = params["directory"].isMember ("sub_index")
                                 ? params["directory"]["sub_index"].asUInt ()
                                 : 0;
             if (params["directory"].isMember ("dir_root"))
             {
                 uint256 uDirRoot;
                 uDirRoot.SetHex (params["dir_root"].asString ());
                 uNodeIndex  = Ledger::getDirNodeIndex (uDirRoot, uSubIndex);
             }
             else if (params["directory"].isMember ("owner"))
             {
                 RippleAddress   naOwnerID;
                 if (!naOwnerID.setAccountID (params["directory"]["owner"].asString ()))
                 {
                     jvResult["error"]   = "malformedAddress";
                 }
                 else
                 {
                     uint256 uDirRoot    = Ledger::getOwnerDirIndex (naOwnerID.getAccountID ());
                     uNodeIndex  = Ledger::getDirNodeIndex (uDirRoot, uSubIndex);
                 }
             }
             else
             {
                 jvResult["error"]   = "malformedRequest";
             }
         }
     }
     else if (params.isMember ("generator"))
     {
         RippleAddress   naGeneratorID;
         if (!params["generator"].isObject ())
         {
             uNodeIndex.SetHex (params["generator"].asString ());
         }
         else if (!params["generator"].isMember ("regular_seed"))
         {
             jvResult["error"]   = "malformedRequest";
         }
         else if (!naGeneratorID.setSeedGeneric (params["generator"]["regular_seed"].asString ()))
         {
             jvResult["error"]   = "malformedAddress";
         }
         else
         {
             RippleAddress       na0Public;      // To find the generator's index.
             RippleAddress       naGenerator = RippleAddress::createGeneratorPublic (naGeneratorID);
             na0Public.setAccountPublic (naGenerator, 0);
             uNodeIndex  = Ledger::getGeneratorIndex (na0Public.getAccountID ());
         }
     }
     else if (params.isMember ("offer"))
     {
         RippleAddress   naAccountID;
         if (!params["offer"].isObject ())
         {
             uNodeIndex.SetHex (params["offer"].asString ());
         }
         else if (!params["offer"].isMember ("account")
                  || !params["offer"].isMember ("seq")
                  || !params["offer"]["seq"].isIntegral ())
         {
             jvResult["error"]   = "malformedRequest";
         }
         else if (!naAccountID.setAccountID (params["offer"]["account"].asString ()))
         {
             jvResult["error"]   = "malformedAddress";
         }
         else
         {
             std::uint32_t      uSequence   = params["offer"]["seq"].asUInt ();
             uNodeIndex  = Ledger::getOfferIndex (naAccountID.getAccountID (), uSequence);
         }
     }
     else if (params.isMember ("ripple_state"))
     {
         RippleAddress   naA;
         RippleAddress   naB;
         uint160         uCurrency;
         Json::Value     jvRippleState   = params["ripple_state"];
         if (!jvRippleState.isObject ()
                 || !jvRippleState.isMember ("currency")
                 || !jvRippleState.isMember ("accounts")
                 || !jvRippleState["accounts"].isArray ()
                 || 2 != jvRippleState["accounts"].size ()
                 || !jvRippleState["accounts"][0u].isString ()
                 || !jvRippleState["accounts"][1u].isString ()
                 || jvRippleState["accounts"][0u].asString () == jvRippleState["accounts"][1u].asString ()
            )
         {
             jvResult["error"]   = "malformedRequest";
         }
         else if (!naA.setAccountID (jvRippleState["accounts"][0u].asString ())
                  || !naB.setAccountID (jvRippleState["accounts"][1u].asString ()))
         {
             jvResult["error"]   = "malformedAddress";
         }
         else if (!STAmount::currencyFromString (uCurrency, jvRippleState["currency"].asString ()))
         {
             jvResult["error"]   = "malformedCurrency";
         }
         else
         {
             uNodeIndex  = Ledger::getRippleStateIndex (naA, naB, uCurrency);
         }
     }
     else
     {
         jvResult["error"]   = "unknownOption";
     }
     if (uNodeIndex.isNonZero ())
     {
         SLE::pointer    sleNode = mNetOps->getSLEi (lpLedger, uNodeIndex);
         if (params.isMember("binary"))
             bNodeBinary = params["binary"].asBool();
         if (!sleNode)
         {
             // Not found.
             // XXX Should also provide proof.
             jvResult["error"]       = "entryNotFound";
         }
         else if (bNodeBinary)
         {
             // XXX Should also provide proof.
             Serializer s;
             sleNode->add (s);
             jvResult["node_binary"] = strHex (s.peekData ());
             jvResult["index"]       = uNodeIndex.ToString ();
         }
         else
         {
             jvResult["node"]        = sleNode->getJson (0);
             jvResult["index"]       = uNodeIndex.ToString ();
         }
     }
     return jvResult;
 }
Json::Value ripple::RPCHandler::doLedgerHeader (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 27 of file LedgerHeader.cpp.
References ripple::Serializer::addRaw(), ripple::RPC::lookupLedger(), mNetOps, ripple::Serializer::peekData(), and ripple::strHex().
Referenced by doCommand().
 {
     masterLockHolder.unlock ();
     Ledger::pointer     lpLedger;
     Json::Value         jvResult    = RPC::lookupLedger (params, lpLedger, *mNetOps);
     if (!lpLedger)
         return jvResult;
     Serializer  s;
     lpLedger->addRaw (s);
     jvResult["ledger_data"] = strHex (s.peekData ());
     // This information isn't verified, they should only use it if they trust us.
     lpLedger->addJson (jvResult, 0);
     return jvResult;
 }
Json::Value ripple::RPCHandler::doLogLevel (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 23 of file LogLevel.cpp.
References ripple::LogSink::get(), ripple::LogPartition::getSeverities(), Json::Value::isMember(), ripple::lsINVALID, Json::objectValue, ripple::rpcError(), ripple::rpcINVALID_PARAMS, ripple::LogPartition::setSeverity(), ripple::Log::severityToString(), and ripple::Log::stringToSeverity().
Referenced by doCommand().
 {
     // log_level
     if (!params.isMember ("severity"))
     {
         // get log severities
         Json::Value ret (Json::objectValue);
         Json::Value lev (Json::objectValue);
         lev["base"] = Log::severityToString (LogSink::get()->getMinSeverity ());
         std::vector< std::pair<std::string, std::string> > logTable = LogPartition::getSeverities ();
         typedef std::map<std::string, std::string>::value_type stringPair;
         BOOST_FOREACH (const stringPair & it, logTable)
         lev[it.first] = it.second;
         ret["levels"] = lev;
         return ret;
     }
     LogSeverity sv = Log::stringToSeverity (params["severity"].asString ());
     if (sv == lsINVALID)
         return rpcError (rpcINVALID_PARAMS);
     // log_level severity
     if (!params.isMember ("partition"))
     {
         // set base log severity
         LogSink::get()->setMinSeverity (sv, true);
         return Json::objectValue;
     }
     // log_level partition severity base?
     if (params.isMember ("partition"))
     {
         // set partition severity
         std::string partition (params["partition"].asString ());
         if (boost::iequals (partition, "base"))
             LogSink::get()->setMinSeverity (sv, false);
         else if (!LogPartition::setSeverity (partition, sv))
             return rpcError (rpcINVALID_PARAMS);
         return Json::objectValue;
     }
     return rpcError (rpcINVALID_PARAMS);
 }
Json::Value ripple::RPCHandler::doLogRotate (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 23 of file LogRotate.cpp.
References ripple::LogSink::get().
Referenced by doCommand().
 {
     masterLockHolder.unlock ();
     return LogSink::get()->rotateLog ();
 }
Json::Value ripple::RPCHandler::doNicknameInfo (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Json::Value ripple::RPCHandler::doOwnerInfo (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 28 of file OwnerInfo.cpp.
References ripple::RPC::accountFromString(), Json::Value::asString(), Json::Value::asUInt(), Json::Value::empty(), ripple::NetworkOPs::getClosedLedger(), ripple::NetworkOPs::getCurrentLedger(), ripple::NetworkOPs::getOwnerInfo(), Json::Value::isMember(), ripple::RPC::missing_field_error(), and mNetOps.
Referenced by doCommand().
 {
     if (!params.isMember ("account") && !params.isMember ("ident"))
         return RPC::missing_field_error ("account");
     std::string     strIdent    = params.isMember ("account") ? params["account"].asString () : params["ident"].asString ();
     bool            bIndex;
     int             iIndex      = params.isMember ("account_index") ? params["account_index"].asUInt () : 0;
     RippleAddress   raAccount;
     Json::Value     ret;
     // Get info on account.
     Json::Value     jAccepted   = RPC::accountFromString (mNetOps->getClosedLedger (), raAccount, bIndex, strIdent, iIndex, false, *mNetOps);
     ret["accepted"] = jAccepted.empty () ? mNetOps->getOwnerInfo (mNetOps->getClosedLedger (), raAccount) : jAccepted;
     Json::Value     jCurrent    = RPC::accountFromString (mNetOps->getCurrentLedger (), raAccount, bIndex, strIdent, iIndex, false, *mNetOps);
     ret["current"]  = jCurrent.empty () ? mNetOps->getOwnerInfo (mNetOps->getCurrentLedger (), raAccount) : jCurrent;
     return ret;
 }
Json::Value ripple::RPCHandler::doPathFind (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 23 of file PathFind.cpp.
References Json::Value::asString(), ripple::Resource::feeHighBurdenRPC, ripple::getApp(), ripple::NetworkOPs::getClosedLedger(), ripple::Application::getPathRequests(), Json::Value::isMember(), Json::Value::isString(), ripple::PathRequests::makePathRequest(), mInfoSub, mNetOps, ripple::rpcError(), ripple::rpcINVALID_PARAMS, ripple::rpcNO_EVENTS, and ripple::rpcNO_PF_REQUEST.
Referenced by doCommand().
 {
     Ledger::pointer lpLedger = mNetOps->getClosedLedger();
     masterLockHolder.unlock();
     if (!params.isMember ("subcommand") || !params["subcommand"].isString ())
         return rpcError (rpcINVALID_PARAMS);
     if (!mInfoSub)
         return rpcError (rpcNO_EVENTS);
     std::string sSubCommand = params["subcommand"].asString ();
     if (sSubCommand == "create")
     {
         loadType = Resource::feeHighBurdenRPC;
         mInfoSub->clearPathRequest ();
         return getApp().getPathRequests().makePathRequest (mInfoSub, lpLedger, params);
     }
     if (sSubCommand == "close")
     {
         PathRequest::pointer request = mInfoSub->getPathRequest ();
         if (!request)
             return rpcError (rpcNO_PF_REQUEST);
         mInfoSub->clearPathRequest ();
         return request->doClose (params);
     }
     if (sSubCommand == "status")
     {
         PathRequest::pointer request = mInfoSub->getPathRequest ();
         if (!request)
             return rpcNO_PF_REQUEST;
         return request->doStatus (params);
     }
     return rpcError (rpcINVALID_PARAMS);
 }
Json::Value ripple::RPCHandler::doPeers (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 24 of file Peers.cpp.
References ripple::UniqueNodeList::addClusterStatus(), ripple::getApp(), ripple::Application::getUNL(), ripple::Overlay::json(), Json::objectValue, and ripple::Application::overlay().
Referenced by doCommand().
 {
     Json::Value jvResult (Json::objectValue);
     jvResult["peers"]   = getApp().overlay ().json ();
     getApp().getUNL().addClusterStatus(jvResult);
     return jvResult;
 }
Json::Value ripple::RPCHandler::doPing (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 23 of file Ping.cpp.
References Json::objectValue, and rocksdb::crc32c::Value().
Referenced by doCommand().
 {
     return Json::Value (Json::objectValue);
 }
Json::Value ripple::RPCHandler::doPrint (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 23 of file Print.cpp.
References ripple::getApp(), Json::Value::isArray(), Json::Value::isObject(), Json::Value::isString(), ripple::JsonPropertyStream::top(), and beast::PropertyStream::Source::write().
Referenced by doCommand().
 {
     masterLockHolder.unlock ();
     JsonPropertyStream stream;
     if (params.isObject() && params["params"].isArray() && params["params"][0u].isString ())
         getApp().write (stream, params["params"][0u].asString());
     else
         getApp().write (stream);
     return stream.top();
 }
Json::Value ripple::RPCHandler::doProfile (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 28 of file Profile.cpp.
References Json::objectValue.
 {
     /* need to fix now that sharedOfferCreate is gone
     int             iArgs   = params.size();
     RippleAddress   naSeedA;
     RippleAddress   naAccountA;
     uint160         uCurrencyOfferA;
     RippleAddress   naSeedB;
     RippleAddress   naAccountB;
     uint160         uCurrencyOfferB;
     uint32          iCount  = 100;
     bool            bSubmit = false;
     if (iArgs < 6 || "offers" != params[0u].asString())
     {
         return rpcError(rpcINVALID_PARAMS);
     }
     if (!naSeedA.setSeedGeneric(params[1u].asString()))                          // <pass_a>
         return rpcError(rpcINVALID_PARAMS);
     naAccountA.setAccountID(params[2u].asString());                              // <account_a>
     if (!STAmount::currencyFromString(uCurrencyOfferA, params[3u].asString()))   // <currency_offer_a>
         return rpcError(rpcINVALID_PARAMS);
     naAccountB.setAccountID(params[4u].asString());                              // <account_b>
     if (!STAmount::currencyFromString(uCurrencyOfferB, params[5u].asString()))   // <currency_offer_b>
         return rpcError(rpcINVALID_PARAMS);
     iCount  = lexicalCast <uint32>(params[6u].asString());
     if (iArgs >= 8 && "false" != params[7u].asString())
         bSubmit = true;
     LogSink::get()->setMinSeverity(lsFATAL,true);
     boost::posix_time::ptime            ptStart(boost::posix_time::microsec_clock::local_time());
     for(unsigned int n=0; n<iCount; n++)
     {
         RippleAddress           naMasterGeneratorA;
         RippleAddress           naAccountPublicA;
         RippleAddress           naAccountPrivateA;
         AccountState::pointer   asSrcA;
         STAmount                saSrcBalanceA;
         Json::Value             jvObjA      = authorize(uint256(0), naSeedA, naAccountA, naAccountPublicA, naAccountPrivateA,
             saSrcBalanceA, getConfig ().FEE_DEFAULT, asSrcA, naMasterGeneratorA);
         if (!jvObjA.empty())
             return jvObjA;
         Transaction::pointer    tpOfferA    = Transaction::sharedOfferCreate(
             naAccountPublicA, naAccountPrivateA,
             naAccountA,                                                 // naSourceAccount,
             asSrcA->getSeq(),                                           // uSeq
             getConfig ().FEE_DEFAULT,
             0,                                                          // uSourceTag,
             false,                                                      // bPassive
             STAmount(uCurrencyOfferA, naAccountA.getAccountID(), 1),    // saTakerPays
             STAmount(uCurrencyOfferB, naAccountB.getAccountID(), 1+n),  // saTakerGets
             0);                                                         // uExpiration
         if (bSubmit)
             tpOfferA    = mNetOps->submitTransactionSync(tpOfferA); // FIXME: Don't use synch interface
     }
     boost::posix_time::ptime            ptEnd(boost::posix_time::microsec_clock::local_time());
     boost::posix_time::time_duration    tdInterval      = ptEnd-ptStart;
     long                                lMicroseconds   = tdInterval.total_microseconds();
     int                                 iTransactions   = iCount;
     float                               fRate           = lMicroseconds ? iTransactions/(lMicroseconds/1000000.0) : 0.0;
     Json::Value obj(Json::objectValue);
     obj["transactions"]     = iTransactions;
     obj["submit"]           = bSubmit;
     obj["start"]            = boost::posix_time::to_simple_string(ptStart);
     obj["end"]              = boost::posix_time::to_simple_string(ptEnd);
     obj["interval"]         = boost::posix_time::to_simple_string(tdInterval);
     obj["rate_per_second"]  = fRate;
     */
     Json::Value obj (Json::objectValue);
     return obj;
 }
Json::Value ripple::RPCHandler::doProofCreate (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 29 of file ProofCreate.cpp.
References ripple::getApp(), ripple::ProofOfWorkFactory::getProof(), ripple::Application::getProofOfWorkFactory(), ripple::ProofOfWork::getToken(), ripple::RPC::invalid_field_error(), Json::Value::isMember(), ripple::ProofOfWorkFactory::kMaxDifficulty, ripple::ProofOfWorkFactory::New(), and Json::objectValue.
Referenced by doCommand().
 {
     masterLockHolder.unlock ();
     // XXX: Add ability to create proof with arbitrary time
     Json::Value     jvResult (Json::objectValue);
     if (params.isMember ("difficulty") || params.isMember ("secret"))
     {
         // VFALCO TODO why aren't we using the app's factory?
         std::unique_ptr <ProofOfWorkFactory> pgGen (ProofOfWorkFactory::New ());
         if (params.isMember ("difficulty"))
         {
             if (!params["difficulty"].isIntegral ())
                 return RPC::invalid_field_error ("difficulty");
             int const iDifficulty (params["difficulty"].asInt ());
             if (iDifficulty < 0 || iDifficulty > ProofOfWorkFactory::kMaxDifficulty)
                 return RPC::invalid_field_error ("difficulty");
             pgGen->setDifficulty (iDifficulty);
         }
         if (params.isMember ("secret"))
         {
             uint256     uSecret (params["secret"].asString ());
             pgGen->setSecret (uSecret);
         }
         jvResult["token"]   = pgGen->getProof ().getToken ();
         jvResult["secret"]  = pgGen->getSecret ().GetHex ();
     }
     else
     {
         jvResult["token"]   = getApp().getProofOfWorkFactory ().getProof ().getToken ();
     }
     return jvResult;
 }
Json::Value ripple::RPCHandler::doProofSolve (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 26 of file ProofSolve.cpp.
References Json::Value::asString(), ripple::base_uint< BITS >::GetHex(), ripple::RPC::invalid_field_error(), Json::Value::isMember(), ripple::RPC::missing_field_error(), ripple::ProofOfWork::solve(), and ripple::ProofOfWork::validateToken().
Referenced by doCommand().
 {
     masterLockHolder.unlock ();
     Json::Value         jvResult;
     if (!params.isMember ("token"))
         return RPC::missing_field_error ("token");
     std::string         strToken        = params["token"].asString ();
     if (!ProofOfWork::validateToken (strToken))
         return RPC::invalid_field_error ("token");
     ProofOfWork         powProof (strToken);
     uint256             uSolution       = powProof.solve ();
     jvResult["solution"]                = uSolution.GetHex ();
     return jvResult;
 }
Json::Value ripple::RPCHandler::doProofVerify (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 30 of file ProofVerify.cpp.
References Json::Value::asInt(), Json::Value::asString(), ripple::ProofOfWork::calcResultInfo(), ripple::ProofOfWorkFactory::checkProof(), ripple::getApp(), ripple::Application::getProofOfWorkFactory(), ripple::RPC::invalid_field_error(), Json::Value::isMember(), ripple::ProofOfWorkFactory::kMaxDifficulty, ripple::RPC::missing_field_error(), and ripple::ProofOfWorkFactory::New().
Referenced by doCommand().
 {
     masterLockHolder.unlock ();
     // XXX Add ability to check proof against arbitrary time
     Json::Value         jvResult;
     if (!params.isMember ("token"))
         return RPC::missing_field_error ("token");
     if (!params.isMember ("solution"))
         return RPC::missing_field_error ("solution");
     std::string     strToken    = params["token"].asString ();
     uint256         uSolution (params["solution"].asString ());
     PowResult       prResult;
     if (params.isMember ("difficulty") || params.isMember ("secret"))
     {
         // VFALCO TODO why aren't we using the app's factory?
         std::unique_ptr <ProofOfWorkFactory> pgGen (ProofOfWorkFactory::New ());
         if (params.isMember ("difficulty"))
         {
             if (!params["difficulty"].isIntegral ())
                 return RPC::invalid_field_error ("difficulty");
             int iDifficulty = params["difficulty"].asInt ();
             if (iDifficulty < 0 || iDifficulty > ProofOfWorkFactory::kMaxDifficulty)
                 return RPC::missing_field_error ("difficulty");
             pgGen->setDifficulty (iDifficulty);
         }
         if (params.isMember ("secret"))
         {
             uint256     uSecret (params["secret"].asString ());
             pgGen->setSecret (uSecret);
         }
         prResult                = pgGen->checkProof (strToken, uSolution);
         jvResult["secret"]      = pgGen->getSecret ().GetHex ();
     }
     else
     {
         // XXX Proof should not be marked as used from this
         prResult = getApp().getProofOfWorkFactory ().checkProof (strToken, uSolution);
     }
     std::string sToken;
     std::string sHuman;
     ProofOfWork::calcResultInfo (prResult, sToken, sHuman);
     jvResult["proof_result"]            = sToken;
     jvResult["proof_result_code"]       = prResult;
     jvResult["proof_result_message"]    = sHuman;
     return jvResult;
 }
Json::Value ripple::RPCHandler::doRandom (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 27 of file Random.cpp.
References ripple::base_uint< BITS >::begin(), ripple::RandomNumbers::fillBytes(), ripple::RandomNumbers::getInstance(), ripple::rpcError(), ripple::rpcINTERNAL, ripple::base_uint< BITS >::size(), and ripple::base_uint< BITS >::ToString().
Referenced by doCommand().
 {
     masterLockHolder.unlock ();
     uint256         uRandom;
     try
     {
         RandomNumbers::getInstance ().fillBytes (uRandom.begin (), uRandom.size ());
         Json::Value jvResult;
         jvResult["random"]  = uRandom.ToString ();
         return jvResult;
     }
     catch (...)
     {
         return rpcError (rpcINTERNAL);
     }
 }
Json::Value ripple::RPCHandler::doRipplePathFind (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 25 of file RipplePathFind.cpp.
References ACCOUNT_ONE, ACCOUNT_XRP, ripple::STPathSet::addPath(), ripple::Config::ADMIN, Json::Value::append(), Json::arrayValue, Json::Value::asInt(), Json::Value::asString(), ripple::STAmount::bSetJson(), ripple::LedgerEntrySet::clear(), ripple::STAmount::createHumanCurrency(), ripple::STAmount::currencyFromString(), ripple::STParsedJSON::error, ripple::Resource::feeHighBurdenRPC, ripple::Pathfinder::findPaths(), ripple::RippleAddress::getAccountID(), ripple::getApp(), ripple::getConfig(), ripple::STAmount::getCurrency(), ripple::STAmount::getIssuer(), ripple::STAmount::getJson(), ripple::STPathSet::getJson(), ripple::PathRequests::getLineCache(), ripple::Application::getPathRequests(), ripple::NetworkOPs::getValidatedLedger(), ripple::RippleAddress::humanAccountID(), Json::Value::isArray(), Json::Value::isIntegral(), Json::Value::isMember(), ripple::base_uint< BITS >::isNonZero(), Json::Value::isObject(), ripple::RPC::LegacyPathFind::isOkay(), Json::Value::isString(), ripple::STAmount::issuerFromString(), ripple::base_uint< BITS >::isZero(), ripple::RPC::lookupLedger(), ripple::lsDEBUG, ripple::lsINFO, ripple::lsWARNING, mNetOps, mRole, ripple::STAmount::negate(), ripple::STParsedJSON::object, Json::objectValue, ripple::Config::PATH_SEARCH_OLD, ripple::RippleCalc::rippleCalc(), ripple::rpcDST_ACT_MALFORMED, ripple::rpcDST_ACT_MISSING, ripple::rpcError(), ripple::rpcINVALID_PARAMS, ripple::rpcSRC_ACT_MALFORMED, ripple::rpcSRC_ACT_MISSING, ripple::rpcSRC_CUR_MALFORMED, ripple::rpcSRC_ISR_MALFORMED, ripple::rpcTOO_BUSY, ripple::Config::RUN_STANDALONE, ripple::RippleAddress::setAccountID(), Json::Value::size(), ripple::STPath::size(), ripple::tapNONE, ripple::tecPATH_PARTIAL, ripple::terNO_LINE, ripple::tesSUCCESS, ripple::transHuman(), ripple::transResultInfo(), ripple::usAccountDestCurrencies(), ripple::usAccountSourceCurrencies(), rocksdb::crc32c::Value(), and WriteLog.
Referenced by doCommand().
 {
     masterLockHolder.unlock ();
     RPC::LegacyPathFind lpf (mRole == Config::ADMIN);
     if (!lpf.isOkay ())
         return rpcError (rpcTOO_BUSY);
     loadType = Resource::feeHighBurdenRPC;
     RippleAddress   raSrc;
     RippleAddress   raDst;
     STAmount        saDstAmount;
     Ledger::pointer lpLedger;
     Json::Value     jvResult;
     if (getConfig().RUN_STANDALONE || params.isMember("ledger") || params.isMember("ledger_index") || params.isMember("ledger_hash"))
     { // The caller specified a ledger
         jvResult = RPC::lookupLedger (params, lpLedger, *mNetOps);
         if (!lpLedger)
             return jvResult;
     }
     if (!params.isMember ("source_account"))
     {
         jvResult    = rpcError (rpcSRC_ACT_MISSING);
     }
     else if (!params["source_account"].isString ()
              || !raSrc.setAccountID (params["source_account"].asString ()))
     {
         jvResult    = rpcError (rpcSRC_ACT_MALFORMED);
     }
     else if (!params.isMember ("destination_account"))
     {
         jvResult    = rpcError (rpcDST_ACT_MISSING);
     }
     else if (!params["destination_account"].isString ()
              || !raDst.setAccountID (params["destination_account"].asString ()))
     {
         jvResult    = rpcError (rpcDST_ACT_MALFORMED);
     }
     else if (
         // Parse saDstAmount.
         !params.isMember ("destination_amount")
         || !saDstAmount.bSetJson (params["destination_amount"])
         || saDstAmount <= zero
         || (!!saDstAmount.getCurrency () && (!saDstAmount.getIssuer () || ACCOUNT_ONE == saDstAmount.getIssuer ())))
     {
         WriteLog (lsINFO, RPCHandler) << "Bad destination_amount.";
         jvResult    = rpcError (rpcINVALID_PARAMS);
     }
     else if (
         // Checks on source_currencies.
         params.isMember ("source_currencies")
         && (!params["source_currencies"].isArray ()
             || !params["source_currencies"].size ()) // Don't allow empty currencies.
     )
     {
         WriteLog (lsINFO, RPCHandler) << "Bad source_currencies.";
         jvResult    = rpcError (rpcINVALID_PARAMS);
     }
     else
     {
         loadType = Resource::feeHighBurdenRPC;
         RippleLineCache::pointer cache;
         if (lpLedger)
         { // The caller specified a ledger
             lpLedger = boost::make_shared<Ledger> (boost::ref (*lpLedger), false);
             cache = boost::make_shared<RippleLineCache>(lpLedger);
         }
         else
         { // Use the default ledger and cache
             lpLedger = mNetOps->getValidatedLedger();
             cache = getApp().getPathRequests().getLineCache(lpLedger, false);
         }
         Json::Value     jvSrcCurrencies;
         if (params.isMember ("source_currencies"))
         {
             jvSrcCurrencies = params["source_currencies"];
         }
         else
         {
             boost::unordered_set<uint160>   usCurrencies    = usAccountSourceCurrencies (raSrc, cache, true);
             jvSrcCurrencies             = Json::Value (Json::arrayValue);
             BOOST_FOREACH (const uint160 & uCurrency, usCurrencies)
             {
                 Json::Value jvCurrency (Json::objectValue);
                 jvCurrency["currency"]  = STAmount::createHumanCurrency (uCurrency);
                 jvSrcCurrencies.append (jvCurrency);
             }
         }
         // Fill in currencies destination will accept
         Json::Value jvDestCur (Json::arrayValue);
         boost::unordered_set<uint160> usDestCurrID = usAccountDestCurrencies (raDst, cache, true);
         BOOST_FOREACH (const uint160 & uCurrency, usDestCurrID)
         jvDestCur.append (STAmount::createHumanCurrency (uCurrency));
         jvResult["destination_currencies"] = jvDestCur;
         jvResult["destination_account"] = raDst.humanAccountID ();
         Json::Value jvArray (Json::arrayValue);
         for (unsigned int i = 0; i != jvSrcCurrencies.size (); ++i)
         {
             Json::Value jvSource        = jvSrcCurrencies[i];
             uint160     uSrcCurrencyID;
             uint160     uSrcIssuerID;
             if (!jvSource.isObject ())
                 return rpcError (rpcINVALID_PARAMS);
             // Parse mandatory currency.
             if (!jvSource.isMember ("currency")
                     || !STAmount::currencyFromString (uSrcCurrencyID, jvSource["currency"].asString ()))
             {
                 WriteLog (lsINFO, RPCHandler) << "Bad currency.";
                 return rpcError (rpcSRC_CUR_MALFORMED);
             }
             if (uSrcCurrencyID.isNonZero ())
                 uSrcIssuerID = raSrc.getAccountID ();
             // Parse optional issuer.
             if (jvSource.isMember ("issuer") &&
                     ((!jvSource["issuer"].isString () ||
                       !STAmount::issuerFromString (uSrcIssuerID, jvSource["issuer"].asString ())) ||
                      (uSrcIssuerID.isZero () != uSrcCurrencyID.isZero ()) ||
                      (ACCOUNT_ONE == uSrcIssuerID)))
             {
                 WriteLog (lsINFO, RPCHandler) << "Bad issuer.";
                 return rpcError (rpcSRC_ISR_MALFORMED);
             }
             STPathSet   spsComputed;
             bool        bValid;
             Pathfinder  pf (cache, raSrc, raDst, uSrcCurrencyID, uSrcIssuerID, saDstAmount, bValid);
             int level = getConfig().PATH_SEARCH_OLD;
             if ((getConfig().PATH_SEARCH_MAX > level) && !getApp().getFeeTrack().isLoadedLocal())
                 ++level;
             if (params.isMember("depth") && params["depth"].isIntegral())
             {
                 int rLev = params["search_depth"].asInt ();
                 if ((rLev < level) || (mRole == Config::ADMIN))
                     level = rLev;
             }
             if (params.isMember("paths"))
             {
                 STParsedJSON paths ("paths", params["paths"]);
                 if (paths.object.get() == nullptr)
                     return paths.error;
                 else
                     spsComputed = paths.object.get()->downcast<STPathSet> ();
             }
             STPath extraPath;
             if (!bValid || !pf.findPaths (level, 4, spsComputed, extraPath))
             {
                 WriteLog (lsWARNING, RPCHandler) << "ripple_path_find: No paths found.";
             }
             else
             {
                 std::vector<PathState::pointer> vpsExpanded;
                 STAmount                        saMaxAmountAct;
                 STAmount                        saDstAmountAct;
                 STAmount                        saMaxAmount (
                     uSrcCurrencyID,
                     !!uSrcIssuerID
                     ? uSrcIssuerID      // Use specifed issuer.
                     : !!uSrcCurrencyID  // Default to source account.
                     ? raSrc.getAccountID ()
                     : ACCOUNT_XRP,
                     1);
                 saMaxAmount.negate ();
                 LedgerEntrySet  lesSandbox (lpLedger, tapNONE);
                 TER terResult   =
                     RippleCalc::rippleCalc (
                         lesSandbox,
                         saMaxAmountAct,         // <--
                         saDstAmountAct,         // <--
                         vpsExpanded,            // <--
                         saMaxAmount,            // --> Amount to send is unlimited to get an estimate.
                         saDstAmount,            // --> Amount to deliver.
                         raDst.getAccountID (),  // --> Account to deliver to.
                         raSrc.getAccountID (),  // --> Account sending from.
                         spsComputed,            // --> Path set.
                         false,                  // --> Don't allow partial payment. This is for normal fill or kill payments.
                         // Must achieve delivery goal.
                         false,                  // --> Don't limit quality. Average quality is wanted for normal payments.
                         false,                  // --> Allow direct ripple to be added to path set. to path set.
                         true);                  // --> Stand alone mode, no point in deleting unfundeds.
                 // WriteLog (lsDEBUG, RPCHandler) << "ripple_path_find: PATHS IN: " << spsComputed.size() << " : " << spsComputed.getJson(0);
                 // WriteLog (lsDEBUG, RPCHandler) << "ripple_path_find: PATHS EXP: " << vpsExpanded.size();
                 WriteLog (lsWARNING, RPCHandler)
                         << boost::str (boost::format ("ripple_path_find: saMaxAmount=%s saDstAmount=%s saMaxAmountAct=%s saDstAmountAct=%s")
                                        % saMaxAmount
                                        % saDstAmount
                                        % saMaxAmountAct
                                        % saDstAmountAct);
                 if ((extraPath.size() > 0) && ((terResult == terNO_LINE) || (terResult == tecPATH_PARTIAL)))
                 {
                     WriteLog (lsDEBUG, PathRequest) << "Trying with an extra path element";
                     spsComputed.addPath(extraPath);
                     vpsExpanded.clear ();
                     lesSandbox.clear ();
                     terResult = RippleCalc::rippleCalc (lesSandbox, saMaxAmountAct, saDstAmountAct,
                                                         vpsExpanded, saMaxAmount, saDstAmount,
                                                         raDst.getAccountID (), raSrc.getAccountID (),
                                                         spsComputed, false, false, false, true);
                     WriteLog (lsDEBUG, PathRequest) << "Extra path element gives " << transHuman (terResult);
                 }
                 if (tesSUCCESS == terResult)
                 {
                     Json::Value jvEntry (Json::objectValue);
                     STPathSet   spsCanonical;
                     // Reuse the expanded as it would need to be calcuated anyway to produce the canonical.
                     // (At least unless we make a direct canonical.)
                     // RippleCalc::setCanonical(spsCanonical, vpsExpanded, false);
                     jvEntry["source_amount"]    = saMaxAmountAct.getJson (0);
                     //                  jvEntry["paths_expanded"]   = vpsExpanded.getJson(0);
                     jvEntry["paths_canonical"]  = Json::arrayValue; // spsCanonical.getJson(0);
                     jvEntry["paths_computed"]   = spsComputed.getJson (0);
                     jvArray.append (jvEntry);
                 }
                 else
                 {
                     std::string strToken;
                     std::string strHuman;
                     transResultInfo (terResult, strToken, strHuman);
                     WriteLog (lsDEBUG, RPCHandler)
                             << boost::str (boost::format ("ripple_path_find: %s %s %s")
                                            % strToken
                                            % strHuman
                                            % spsComputed.getJson (0));
                 }
             }
         }
         // Each alternative differs by source currency.
         jvResult["alternatives"] = jvArray;
     }
     WriteLog (lsDEBUG, RPCHandler)
             << boost::str (boost::format ("ripple_path_find< %s")
                            % jvResult);
     return jvResult;
 }
Json::Value ripple::RPCHandler::doRpcCommand (const std::string & strCommand, Json::Value const & jvParams, int iRole, Resource::Charge & loadType)
Definition at line 47 of file RPCHandler.cpp.
References doCommand(), Json::Value::isMember(), Json::Value::isObject(), ripple::logRPCError(), ripple::lsTRACE, Json::objectValue, ripple::rpcError(), ripple::rpcINVALID_PARAMS, Json::Value::size(), rocksdb::crc32c::Value(), and WriteLog.
Referenced by ripple::RPCServerHandler::processRequest(), and ripple::RPCHTTPServerImp::processRequest().
 {
     WriteLog (lsTRACE, RPCHandler) << "doRpcCommand:" << strMethod << ":" << jvParams;
     if (!jvParams.isArray () || jvParams.size () > 1)
         return logRPCError (rpcError (rpcINVALID_PARAMS));
     Json::Value params   = jvParams.size () ? jvParams[0u] : Json::Value (Json::objectValue);
     if (!params.isObject ())
         return logRPCError (rpcError (rpcINVALID_PARAMS));
     // Provide the JSON-RPC method as the field "command" in the request.
     params["command"]    = strMethod;
     Json::Value jvResult = doCommand (params, iRole, loadType);
     // Always report "status".  On an error report the request as received.
     if (jvResult.isMember ("error"))
     {
         jvResult["status"]  = "error";
         jvResult["request"] = params;
     }
     else
     {
         jvResult["status"]  = "success";
     }
     return logRPCError (jvResult);
 }
Json::Value ripple::RPCHandler::doServerInfo (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 23 of file ServerInfo.cpp.
References ripple::Config::ADMIN, ripple::NetworkOPs::getServerInfo(), mNetOps, mRole, and Json::objectValue.
Referenced by doCommand().
 {
     Json::Value ret (Json::objectValue);
     ret["info"] = mNetOps->getServerInfo (true, mRole == Config::ADMIN);
     return ret;
 }
Json::Value ripple::RPCHandler::doServerState (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 23 of file ServerState.cpp.
References ripple::Config::ADMIN, ripple::NetworkOPs::getServerInfo(), mNetOps, mRole, and Json::objectValue.
Referenced by doCommand().
 {
     Json::Value ret (Json::objectValue);
     ret["state"]    = mNetOps->getServerInfo (false, mRole == Config::ADMIN);
     return ret;
 }
Json::Value ripple::RPCHandler::doSessionClose (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Json::Value ripple::RPCHandler::doSessionOpen (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Json::Value ripple::RPCHandler::doSign (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 27 of file Sign.cpp.
References Json::Value::asBool(), ripple::Resource::feeHighBurdenRPC, Json::Value::isMember(), mNetOps, mRole, and ripple::RPC::transactionSign().
Referenced by doCommand().
 {
     masterLockHolder.unlock ();
     loadType = Resource::feeHighBurdenRPC;
     bool bFailHard = params.isMember ("fail_hard") && params["fail_hard"].asBool ();
     return RPC::transactionSign (params, false, bFailHard, masterLockHolder, *mNetOps, mRole);
 }
Json::Value ripple::RPCHandler::doSMS (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 23 of file SMS.cpp.
References ripple::getApp(), Json::Value::isMember(), ripple::rpcError(), ripple::rpcINVALID_PARAMS, and ripple::HTTPClient::sendSMS().
Referenced by doCommand().
 {
     masterLockHolder.unlock ();
     if (!params.isMember ("text"))
         return rpcError (rpcINVALID_PARAMS);
     HTTPClient::sendSMS (getApp().getIOService (), params["text"].asString ());
     return "sms dispatched";
 }
Json::Value ripple::RPCHandler::doStop (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 23 of file Stop.cpp.
References ripple::getApp(), ripple::Application::signalStop(), and SYSTEM_NAME.
Referenced by doCommand().
 {
     getApp().signalStop ();
     return SYSTEM_NAME " server stopping";
 }
Json::Value ripple::RPCHandler::doSubmit (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 27 of file Submit.cpp.
References ripple::Config::ADMIN, Json::Value::asBool(), ripple::Resource::feeMediumBurdenRPC, Json::Value::isMember(), mNetOps, mRole, ripple::NetworkOPs::processTransaction(), ripple::rpcError(), ripple::rpcINVALID_PARAMS, ripple::strHex(), ripple::strUnHex(), ripple::temUNCERTAIN, ripple::RPC::transactionSign(), and ripple::transResultInfo().
Referenced by doCommand().
 {
     masterLockHolder.unlock ();
     loadType = Resource::feeMediumBurdenRPC;
     if (!params.isMember ("tx_blob"))
     {
         bool bFailHard = params.isMember ("fail_hard") && params["fail_hard"].asBool ();
         return RPC::transactionSign (params, true, bFailHard, masterLockHolder, *mNetOps, mRole);
     }
     Json::Value                 jvResult;
     std::pair<Blob, bool> ret(strUnHex (params["tx_blob"].asString ()));
     if (!ret.second || !ret.first.size ())
         return rpcError (rpcINVALID_PARAMS);
     Serializer                  sTrans (ret.first);
     SerializerIterator          sitTrans (sTrans);
     SerializedTransaction::pointer stpTrans;
     try
     {
         stpTrans = boost::make_shared<SerializedTransaction> (boost::ref (sitTrans));
     }
     catch (std::exception& e)
     {
         jvResult["error"]           = "invalidTransaction";
         jvResult["error_exception"] = e.what ();
         return jvResult;
     }
     Transaction::pointer            tpTrans;
     try
     {
         tpTrans     = boost::make_shared<Transaction> (stpTrans, false);
     }
     catch (std::exception& e)
     {
         jvResult["error"]           = "internalTransaction";
         jvResult["error_exception"] = e.what ();
         return jvResult;
     }
     try
     {
         (void) mNetOps->processTransaction (tpTrans, mRole == Config::ADMIN, true,
             params.isMember ("fail_hard") && params["fail_hard"].asBool ());
     }
     catch (std::exception& e)
     {
         jvResult["error"]           = "internalSubmit";
         jvResult["error_exception"] = e.what ();
         return jvResult;
     }
     try
     {
         jvResult["tx_json"]     = tpTrans->getJson (0);
         jvResult["tx_blob"]     = strHex (tpTrans->getSTransaction ()->getSerializer ().peekData ());
         if (temUNCERTAIN != tpTrans->getResult ())
         {
             std::string sToken;
             std::string sHuman;
             transResultInfo (tpTrans->getResult (), sToken, sHuman);
             jvResult["engine_result"]           = sToken;
             jvResult["engine_result_code"]      = tpTrans->getResult ();
             jvResult["engine_result_message"]   = sHuman;
         }
         return jvResult;
     }
     catch (std::exception& e)
     {
         jvResult["error"]           = "internalJson";
         jvResult["error_exception"] = e.what ();
         return jvResult;
     }
 }
Json::Value ripple::RPCHandler::doSubscribe (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 23 of file Subscribe.cpp.
References ACCOUNT_ONE, ripple::InfoSub::Source::addRpcSub(), ripple::Config::ADMIN, Json::Value::asBool(), Json::Value::asString(), Json::Value::asUInt(), ripple::STAmount::currencyFromString(), Json::Value::end(), ripple::Resource::feeMediumBurdenRPC, ripple::InfoSub::Source::findRpcSub(), ripple::RippleAddress::getAccountID(), ripple::getApp(), ripple::NetworkOPs::getBookPage(), ripple::Application::getLedgerMaster(), ripple::LedgerMaster::getPublishedLedger(), Json::Value::isMember(), Json::Value::isNumeric(), Json::Value::isObject(), ripple::STAmount::issuerFromString(), ripple::Ledger::isValidBook(), ripple::lsDEBUG, ripple::lsINFO, ripple::lsTRACE, ripple::lsWARNING, mInfoSub, mNetOps, mRole, ripple::RPCSub::New(), nothing, Json::nullValue, Json::objectValue, ripple::RPC::parseAccountIds(), ripple::rpcBAD_ISSUER, ripple::rpcBAD_MARKET, ripple::rpcDST_ISR_MALFORMED, ripple::rpcError(), ripple::rpcINVALID_PARAMS, ripple::rpcNO_PERMISSION, ripple::rpcSRC_CUR_MALFORMED, ripple::rpcSRC_ISR_MALFORMED, ripple::RippleAddress::setAccountID(), ripple::InfoSub::Source::subAccount(), ripple::InfoSub::Source::subBook(), ripple::InfoSub::Source::subLedger(), ripple::InfoSub::Source::subRTTransactions(), ripple::InfoSub::Source::subServer(), ripple::InfoSub::Source::subTransactions(), rocksdb::crc32c::Value(), and WriteLog.
Referenced by doCommand().
 {
     // FIXME: This needs to release the master lock immediately
     // Subscriptions need to be protected by their own lock
     InfoSub::pointer ispSub;
     Json::Value jvResult (Json::objectValue);
     std::uint32_t uLedgerIndex = params.isMember ("ledger_index") && params["ledger_index"].isNumeric ()
                                ? params["ledger_index"].asUInt ()
                                : 0;
     if (!mInfoSub && !params.isMember ("url"))
     {
         // Must be a JSON-RPC call.
         WriteLog (lsINFO, RPCHandler) << boost::str (boost::format ("doSubscribe: RPC subscribe requires a url"));
         return rpcError (rpcINVALID_PARAMS);
     }
     if (params.isMember ("url"))
     {
         if (mRole != Config::ADMIN)
             return rpcError (rpcNO_PERMISSION);
         std::string strUrl      = params["url"].asString ();
         std::string strUsername = params.isMember ("url_username") ? params["url_username"].asString () : "";
         std::string strPassword = params.isMember ("url_password") ? params["url_password"].asString () : "";
         // DEPRECATED
         if (params.isMember ("username"))
             strUsername = params["username"].asString ();
         // DEPRECATED
         if (params.isMember ("password"))
             strPassword = params["password"].asString ();
         ispSub  = mNetOps->findRpcSub (strUrl);
         if (!ispSub)
         {
             WriteLog (lsDEBUG, RPCHandler) << boost::str (boost::format ("doSubscribe: building: %s") % strUrl);
             RPCSub::pointer rspSub = RPCSub::New (getApp ().getOPs (),
                 getApp ().getIOService (), getApp ().getJobQueue (),
                     strUrl, strUsername, strPassword);
             ispSub  = mNetOps->addRpcSub (strUrl, boost::dynamic_pointer_cast<InfoSub> (rspSub));
         }
         else
         {
             WriteLog (lsTRACE, RPCHandler) << boost::str (boost::format ("doSubscribe: reusing: %s") % strUrl);
             if (params.isMember ("username"))
                 dynamic_cast<RPCSub*> (&*ispSub)->setUsername (strUsername);
             if (params.isMember ("password"))
                 dynamic_cast<RPCSub*> (&*ispSub)->setPassword (strPassword);
         }
     }
     else
     {
         ispSub  = mInfoSub;
     }
     if (!params.isMember ("streams"))
     {
         nothing ();
     }
     else if (!params["streams"].isArray ())
     {
         WriteLog (lsINFO, RPCHandler) << boost::str (boost::format ("doSubscribe: streams requires an array."));
         return rpcError (rpcINVALID_PARAMS);
     }
     else
     {
         for (Json::Value::iterator it = params["streams"].begin (); it != params["streams"].end (); it++)
         {
             if ((*it).isString ())
             {
                 std::string streamName = (*it).asString ();
                 if (streamName == "server")
                 {
                     mNetOps->subServer (ispSub, jvResult);
                 }
                 else if (streamName == "ledger")
                 {
                     mNetOps->subLedger (ispSub, jvResult);
                 }
                 else if (streamName == "transactions")
                 {
                     mNetOps->subTransactions (ispSub);
                 }
                 else if (streamName == "transactions_proposed"
                          || streamName == "rt_transactions") // DEPRECATED
                 {
                     mNetOps->subRTTransactions (ispSub);
                 }
                 else
                 {
                     jvResult["error"]   = "unknownStream";
                 }
             }
             else
             {
                 jvResult["error"]   = "malformedStream";
             }
         }
     }
     std::string strAccountsProposed = params.isMember ("accounts_proposed")
                                       ? "accounts_proposed"
                                       : "rt_accounts";                                    // DEPRECATED
     if (!params.isMember (strAccountsProposed))
     {
         nothing ();
     }
     else if (!params[strAccountsProposed].isArray ())
     {
         return rpcError (rpcINVALID_PARAMS);
     }
     else
     {
         boost::unordered_set<RippleAddress> usnaAccoundIds  = RPC::parseAccountIds (params[strAccountsProposed]);
         if (usnaAccoundIds.empty ())
         {
             jvResult["error"]   = "malformedAccount";
         }
         else
         {
             mNetOps->subAccount (ispSub, usnaAccoundIds, uLedgerIndex, true);
         }
     }
     if (!params.isMember ("accounts"))
     {
         nothing ();
     }
     else if (!params["accounts"].isArray ())
     {
         return rpcError (rpcINVALID_PARAMS);
     }
     else
     {
         boost::unordered_set<RippleAddress> usnaAccoundIds  = RPC::parseAccountIds (params["accounts"]);
         if (usnaAccoundIds.empty ())
         {
             jvResult["error"]   = "malformedAccount";
         }
         else
         {
             mNetOps->subAccount (ispSub, usnaAccoundIds, uLedgerIndex, false);
             WriteLog (lsDEBUG, RPCHandler) << boost::str (boost::format ("doSubscribe: accounts: %d") % usnaAccoundIds.size ());
         }
     }
     bool bHaveMasterLock = true;
     if (!params.isMember ("books"))
     {
         nothing ();
     }
     else if (!params["books"].isArray ())
     {
         return rpcError (rpcINVALID_PARAMS);
     }
     else
     {
         for (Json::Value::iterator it = params["books"].begin (); it != params["books"].end (); it++)
         {
             Json::Value&    jvSubRequest    = *it;
             if (!jvSubRequest.isObject ()
                     || !jvSubRequest.isMember ("taker_pays")
                     || !jvSubRequest.isMember ("taker_gets")
                     || !jvSubRequest["taker_pays"].isObject ()
                     || !jvSubRequest["taker_gets"].isObject ())
                 return rpcError (rpcINVALID_PARAMS);
             // VFALCO TODO Use RippleAsset here
             RippleCurrency pay_currency;
             RippleIssuer   pay_issuer;
             RippleCurrency get_currency;
             RippleIssuer   get_issuer;
             bool            bBoth           = (jvSubRequest.isMember ("both") && jvSubRequest["both"].asBool ())
                                               || (jvSubRequest.isMember ("both_sides") && jvSubRequest["both_sides"].asBool ());  // DEPRECATED
             bool            bSnapshot       = (jvSubRequest.isMember ("snapshot") && jvSubRequest["snapshot"].asBool ())
                                               || (jvSubRequest.isMember ("state_now") && jvSubRequest["state_now"].asBool ());    // DEPRECATED
             Json::Value     taker_pays     = jvSubRequest["taker_pays"];
             Json::Value     taker_gets     = jvSubRequest["taker_gets"];
             // Parse mandatory currency.
             if (!taker_pays.isMember ("currency")
                     || !STAmount::currencyFromString (pay_currency, taker_pays["currency"].asString ()))
             {
                 WriteLog (lsINFO, RPCHandler) << "Bad taker_pays currency.";
                 return rpcError (rpcSRC_CUR_MALFORMED);
             }
             // Parse optional issuer.
             else if (((taker_pays.isMember ("issuer"))
                       && (!taker_pays["issuer"].isString ()
                           || !STAmount::issuerFromString (pay_issuer, taker_pays["issuer"].asString ())))
                      // Don't allow illegal issuers.
                      || (!pay_currency != !pay_issuer)
                      || ACCOUNT_ONE == pay_issuer)
             {
                 WriteLog (lsINFO, RPCHandler) << "Bad taker_pays issuer.";
                 return rpcError (rpcSRC_ISR_MALFORMED);
             }
             // Parse mandatory currency.
             if (!taker_gets.isMember ("currency")
                     || !STAmount::currencyFromString (get_currency, taker_gets["currency"].asString ()))
             {
                 WriteLog (lsINFO, RPCHandler) << "Bad taker_pays currency.";
                 return rpcError (rpcSRC_CUR_MALFORMED);
             }
             // Parse optional issuer.
             else if (((taker_gets.isMember ("issuer"))
                       && (!taker_gets["issuer"].isString ()
                           || !STAmount::issuerFromString (get_issuer, taker_gets["issuer"].asString ())))
                      // Don't allow illegal issuers.
                      || (!get_currency != !get_issuer)
                      || ACCOUNT_ONE == get_issuer)
             {
                 WriteLog (lsINFO, RPCHandler) << "Bad taker_gets issuer.";
                 return rpcError (rpcDST_ISR_MALFORMED);
             }
             if (pay_currency == get_currency
                     && pay_issuer == get_issuer)
             {
                 WriteLog (lsINFO, RPCHandler) << "taker_gets same as taker_pays.";
                 return rpcError (rpcBAD_MARKET);
             }
             RippleAddress   raTakerID;
             if (!jvSubRequest.isMember ("taker"))
             {
                 raTakerID.setAccountID (ACCOUNT_ONE);
             }
             else if (!raTakerID.setAccountID (jvSubRequest["taker"].asString ()))
             {
                 return rpcError (rpcBAD_ISSUER);
             }
             if (!Ledger::isValidBook (pay_currency, pay_issuer, get_currency, get_issuer))
             {
                 WriteLog (lsWARNING, RPCHandler) << "Bad market: " <<
                                                  pay_currency << ":" << pay_issuer << " -> " <<
                                                  get_currency << ":" << get_issuer;
                 return rpcError (rpcBAD_MARKET);
             }
             mNetOps->subBook (ispSub, pay_currency, get_currency, pay_issuer, get_issuer);
             if (bBoth) mNetOps->subBook (ispSub, get_currency, pay_currency, get_issuer, pay_issuer);
             if (bSnapshot)
             {
                 if (bHaveMasterLock)
                 {
                     masterLockHolder.unlock ();
                     bHaveMasterLock = false;
                 }
                 loadType = Resource::feeMediumBurdenRPC;
                 Ledger::pointer     lpLedger = getApp().getLedgerMaster ().getPublishedLedger ();
                 if (lpLedger)
                 {
                     const Json::Value   jvMarker = Json::Value (Json::nullValue);
                     if (bBoth)
                     {
                         Json::Value jvBids (Json::objectValue);
                         Json::Value jvAsks (Json::objectValue);
                         mNetOps->getBookPage (lpLedger, pay_currency, pay_issuer, get_currency, get_issuer, raTakerID.getAccountID (), false, 0, jvMarker, jvBids);
                         if (jvBids.isMember ("offers")) jvResult["bids"] = jvBids["offers"];
                         mNetOps->getBookPage (lpLedger, get_currency, get_issuer, pay_currency, pay_issuer, raTakerID.getAccountID (), false, 0, jvMarker, jvAsks);
                         if (jvAsks.isMember ("offers")) jvResult["asks"] = jvAsks["offers"];
                     }
                     else
                     {
                         mNetOps->getBookPage (lpLedger, pay_currency, pay_issuer, get_currency, get_issuer, raTakerID.getAccountID (), false, 0, jvMarker, jvResult);
                     }
                 }
             }
         }
     }
     return jvResult;
 }
Json::Value ripple::RPCHandler::doTransactionEntry (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 28 of file TransactionEntry.cpp.
References Json::Value::isMember(), ripple::RPC::lookupLedger(), mNetOps, and ripple::base_uint< BITS >::SetHex().
Referenced by doCommand().
 {
     masterLockHolder.unlock ();
     Ledger::pointer     lpLedger;
     Json::Value         jvResult    = RPC::lookupLedger (params, lpLedger, *mNetOps);
     if (!lpLedger)
         return jvResult;
     if (!params.isMember ("tx_hash"))
     {
         jvResult["error"]   = "fieldNotFoundTransaction";
     }
     else if (!params.isMember ("ledger_hash") && !params.isMember ("ledger_index"))
     {
         // We don't work on ledger current.
         jvResult["error"]   = "notYetImplemented";  // XXX We don't support any transaction yet.
     }
     else
     {
         uint256                     uTransID;
         // XXX Relying on trusted WSS client. Would be better to have a strict routine, returning success or failure.
         uTransID.SetHex (params["tx_hash"].asString ());
         if (!lpLedger)
         {
             jvResult["error"]   = "ledgerNotFound";
         }
         else
         {
             Transaction::pointer        tpTrans;
             TransactionMetaSet::pointer tmTrans;
             if (!lpLedger->getTransaction (uTransID, tpTrans, tmTrans))
             {
                 jvResult["error"]   = "transactionNotFound";
             }
             else
             {
                 jvResult["tx_json"]     = tpTrans->getJson (0);
                 if (tmTrans)
                     jvResult["metadata"]    = tmTrans->getJson (0);
                 // 'accounts'
                 // 'engine_...'
                 // 'ledger_...'
             }
         }
     }
     return jvResult;
 }
Json::Value ripple::RPCHandler::doTx (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 26 of file Tx.cpp.
References Json::Value::asBool(), Json::Value::asString(), ripple::TransactionMaster::fetch(), ripple::getApp(), ripple::NetworkOPs::getLedgerBySeq(), ripple::Application::getMasterTransaction(), ripple::Transaction::isHexTxID(), Json::Value::isMember(), ripple::NetworkOPs::isValidated(), meta, mNetOps, ripple::rpcError(), ripple::rpcINVALID_PARAMS, ripple::rpcNOT_IMPL, and ripple::rpcTXN_NOT_FOUND.
Referenced by doCommand().
 {
     masterLockHolder.unlock ();
     if (!params.isMember ("transaction"))
         return rpcError (rpcINVALID_PARAMS);
     bool binary = params.isMember ("binary") && params["binary"].asBool ();
     std::string strTransaction  = params["transaction"].asString ();
     if (Transaction::isHexTxID (strTransaction))
     {
         // transaction by ID
         uint256 txid (strTransaction);
         Transaction::pointer txn = getApp().getMasterTransaction ().fetch (txid, true);
         if (!txn)
             return rpcError (rpcTXN_NOT_FOUND);
 #ifdef READY_FOR_NEW_TX_FORMAT
         Json::Value ret;
         ret["transaction"] = txn->getJson (0, binary);
 #else
         Json::Value ret = txn->getJson (0, binary);
 #endif
         if (txn->getLedger () != 0)
         {
             Ledger::pointer lgr = mNetOps->getLedgerBySeq (txn->getLedger ());
             if (lgr)
             {
                 bool okay = false;
                 if (binary)
                 {
                     std::string meta;
                     if (lgr->getMetaHex (txid, meta))
                     {
                         ret["meta"] = meta;
                         okay = true;
                     }
                 }
                 else
                 {
                     TransactionMetaSet::pointer set;
                     if (lgr->getTransactionMeta (txid, set))
                     {
                         okay = true;
                         ret["meta"] = set->getJson (0);
                     }
                 }
                 if (okay)
                     ret["validated"] = mNetOps->isValidated (lgr);
             }
         }
         return ret;
     }
     return rpcError (rpcNOT_IMPL);
 }
Json::Value ripple::RPCHandler::doTxHistory (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 26 of file TxHistory.cpp.
References ripple::Config::ADMIN, Json::Value::append(), Json::Value::asUInt(), db, ripple::Resource::feeMediumBurdenRPC, ripple::getApp(), ripple::DatabaseCon::getDB(), ripple::Application::getTxnDB(), Json::Value::isMember(), mRole, ripple::rpcError(), ripple::rpcINVALID_PARAMS, ripple::rpcNO_PERMISSION, SQL_FOREACH, and ripple::Transaction::transactionFromSQL().
Referenced by doCommand().
 {
     masterLockHolder.unlock ();
     loadType = Resource::feeMediumBurdenRPC;
     if (!params.isMember ("start"))
         return rpcError (rpcINVALID_PARAMS);
     unsigned int startIndex = params["start"].asUInt ();
     if ((startIndex > 10000) &&  (mRole != Config::ADMIN))
         return rpcError (rpcNO_PERMISSION);
     Json::Value obj;
     Json::Value txs;
     obj["index"] = startIndex;
     std::string sql =
         boost::str (boost::format ("SELECT * FROM Transactions ORDER BY LedgerSeq desc LIMIT %u,20")
                     % startIndex);
     {
         Database* db = getApp().getTxnDB ()->getDB ();
         DeprecatedScopedLock sl (getApp().getTxnDB ()->getDBLock ());
         SQL_FOREACH (db, sql)
         {
             Transaction::pointer trans = Transaction::transactionFromSQL (db, false);
             if (trans) txs.append (trans->getJson (0));
         }
     }
     obj["txs"] = txs;
     return obj;
 }
Json::Value ripple::RPCHandler::doUnlAdd (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 27 of file UnlAdd.cpp.
References Json::Value::asString(), ripple::getApp(), ripple::Application::getUNL(), Json::Value::isMember(), ripple::UniqueNodeList::nodeAddDomain(), ripple::UniqueNodeList::nodeAddPublic(), ripple::RippleAddress::setNodePublic(), and ripple::UniqueNodeList::vsManual.
Referenced by doCommand().
 {
     std::string strNode     = params.isMember ("node") ? params["node"].asString () : "";
     std::string strComment  = params.isMember ("comment") ? params["comment"].asString () : "";
     RippleAddress   raNodePublic;
     if (raNodePublic.setNodePublic (strNode))
     {
         getApp().getUNL ().nodeAddPublic (raNodePublic, UniqueNodeList::vsManual, strComment);
         return "adding node by public key";
     }
     else
     {
         getApp().getUNL ().nodeAddDomain (strNode, UniqueNodeList::vsManual, strComment);
         return "adding node by domain";
     }
 }
Json::Value ripple::RPCHandler::doUnlDelete (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 26 of file UnlDelete.cpp.
References Json::Value::asString(), ripple::getApp(), ripple::Application::getUNL(), Json::Value::isMember(), ripple::UniqueNodeList::nodeRemoveDomain(), ripple::UniqueNodeList::nodeRemovePublic(), ripple::rpcError(), ripple::rpcINVALID_PARAMS, and ripple::RippleAddress::setNodePublic().
Referenced by doCommand().
 {
     if (!params.isMember ("node"))
         return rpcError (rpcINVALID_PARAMS);
     std::string strNode     = params["node"].asString ();
     RippleAddress   raNodePublic;
     if (raNodePublic.setNodePublic (strNode))
     {
         getApp().getUNL ().nodeRemovePublic (raNodePublic);
         return "removing node by public key";
     }
     else
     {
         getApp().getUNL ().nodeRemoveDomain (strNode);
         return "removing node by domain";
     }
 }
Json::Value ripple::RPCHandler::doUnlFetch (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Json::Value ripple::RPCHandler::doUnlList (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 23 of file UnlList.cpp.
References ripple::getApp(), ripple::Application::getUNL(), ripple::UniqueNodeList::getUnlJson(), and Json::objectValue.
Referenced by doCommand().
 {
     Json::Value obj (Json::objectValue);
     obj["unl"] = getApp().getUNL ().getUnlJson ();
     return obj;
 }
Json::Value ripple::RPCHandler::doUnlLoad (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 24 of file UnlLoad.cpp.
References ripple::getApp(), ripple::getConfig(), ripple::Application::getUNL(), ripple::UniqueNodeList::nodeLoad(), ripple::rpcError(), and ripple::rpcLOAD_FAILED.
Referenced by doCommand().
 {
     if (getConfig ().VALIDATORS_FILE.empty () || !getApp().getUNL ().nodeLoad (getConfig ().VALIDATORS_FILE))
     {
         return rpcError (rpcLOAD_FAILED);
     }
     return "loading";
 }
Json::Value ripple::RPCHandler::doUnlNetwork (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 24 of file UnlNetwork.cpp.
References ripple::getApp(), ripple::Application::getUNL(), and ripple::UniqueNodeList::nodeNetwork().
Referenced by doCommand().
 {
     getApp().getUNL ().nodeNetwork ();
     return "fetching";
 }
Json::Value ripple::RPCHandler::doUnlReset (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 23 of file UnlReset.cpp.
References ripple::getApp(), ripple::Application::getUNL(), and ripple::UniqueNodeList::nodeReset().
Referenced by doCommand().
 {
     getApp().getUNL ().nodeReset ();
     return "removing nodes";
 }
Json::Value ripple::RPCHandler::doUnlScore (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 24 of file UnlScore.cpp.
References ripple::getApp(), ripple::Application::getUNL(), and ripple::UniqueNodeList::nodeScore().
Referenced by doCommand().
 {
     getApp().getUNL ().nodeScore ();
     return "scoring requested";
 }
Json::Value ripple::RPCHandler::doUnsubscribe (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 24 of file Unsubscribe.cpp.
References ACCOUNT_ONE, ripple::Config::ADMIN, Json::Value::asBool(), Json::Value::asString(), ripple::STAmount::currencyFromString(), Json::Value::end(), ripple::InfoSub::Source::findRpcSub(), Json::Value::isMember(), Json::Value::isObject(), ripple::STAmount::issuerFromString(), ripple::lsINFO, mInfoSub, mNetOps, mRole, nothing, Json::objectValue, ripple::RPC::parseAccountIds(), ripple::rpcBAD_MARKET, ripple::rpcDST_ISR_MALFORMED, ripple::rpcError(), ripple::rpcINVALID_PARAMS, ripple::rpcNO_PERMISSION, ripple::rpcSRC_CUR_MALFORMED, ripple::rpcSRC_ISR_MALFORMED, ripple::InfoSub::Source::unsubAccount(), ripple::InfoSub::Source::unsubBook(), ripple::InfoSub::Source::unsubLedger(), ripple::InfoSub::Source::unsubRTTransactions(), ripple::InfoSub::Source::unsubServer(), ripple::InfoSub::Source::unsubTransactions(), and WriteLog.
Referenced by doCommand().
 {
     InfoSub::pointer ispSub;
     Json::Value jvResult (Json::objectValue);
     if (!mInfoSub && !params.isMember ("url"))
     {
         // Must be a JSON-RPC call.
         return rpcError (rpcINVALID_PARAMS);
     }
     if (params.isMember ("url"))
     {
         if (mRole != Config::ADMIN)
             return rpcError (rpcNO_PERMISSION);
         std::string strUrl  = params["url"].asString ();
         ispSub  = mNetOps->findRpcSub (strUrl);
         if (!ispSub)
             return jvResult;
     }
     else
     {
         ispSub  = mInfoSub;
     }
     if (params.isMember ("streams"))
     {
         for (Json::Value::iterator it = params["streams"].begin (); it != params["streams"].end (); it++)
         {
             if ((*it).isString ())
             {
                 std::string streamName = (*it).asString ();
                 if (streamName == "server")
                 {
                     mNetOps->unsubServer (ispSub->getSeq ());
                 }
                 else if (streamName == "ledger")
                 {
                     mNetOps->unsubLedger (ispSub->getSeq ());
                 }
                 else if (streamName == "transactions")
                 {
                     mNetOps->unsubTransactions (ispSub->getSeq ());
                 }
                 else if (streamName == "transactions_proposed"
                          || streamName == "rt_transactions")         // DEPRECATED
                 {
                     mNetOps->unsubRTTransactions (ispSub->getSeq ());
                 }
                 else
                 {
                     jvResult["error"]   = str (boost::format ("Unknown stream: %s") % streamName);
                 }
             }
             else
             {
                 jvResult["error"]   = "malformedSteam";
             }
         }
     }
     if (params.isMember ("accounts_proposed") || params.isMember ("rt_accounts"))
     {
         boost::unordered_set<RippleAddress> usnaAccoundIds  = RPC::parseAccountIds (
                     params.isMember ("accounts_proposed")
                     ? params["accounts_proposed"]
                     : params["rt_accounts"]);                    // DEPRECATED
         if (usnaAccoundIds.empty ())
         {
             jvResult["error"]   = "malformedAccount";
         }
         else
         {
             mNetOps->unsubAccount (ispSub->getSeq (), usnaAccoundIds, true);
         }
     }
     if (params.isMember ("accounts"))
     {
         boost::unordered_set<RippleAddress> usnaAccoundIds  = RPC::parseAccountIds (params["accounts"]);
         if (usnaAccoundIds.empty ())
         {
             jvResult["error"]   = "malformedAccount";
         }
         else
         {
             mNetOps->unsubAccount (ispSub->getSeq (), usnaAccoundIds, false);
         }
     }
     if (!params.isMember ("books"))
     {
         nothing ();
     }
     else if (!params["books"].isArray ())
     {
         return rpcError (rpcINVALID_PARAMS);
     }
     else
     {
         for (Json::Value::iterator it = params["books"].begin (); it != params["books"].end (); it++)
         {
             Json::Value&    jvSubRequest    = *it;
             if (!jvSubRequest.isObject ()
                     || !jvSubRequest.isMember ("taker_pays")
                     || !jvSubRequest.isMember ("taker_gets")
                     || !jvSubRequest["taker_pays"].isObject ()
                     || !jvSubRequest["taker_gets"].isObject ())
                 return rpcError (rpcINVALID_PARAMS);
             uint160         pay_currency;
             uint160         pay_issuer;
             uint160         get_currency;
             uint160         get_issuer;
             bool            bBoth           = (jvSubRequest.isMember ("both") && jvSubRequest["both"].asBool ())
                                               || (jvSubRequest.isMember ("both_sides") && jvSubRequest["both_sides"].asBool ());  // DEPRECATED
             Json::Value     taker_pays     = jvSubRequest["taker_pays"];
             Json::Value     taker_gets     = jvSubRequest["taker_gets"];
             // Parse mandatory currency.
             if (!taker_pays.isMember ("currency")
                     || !STAmount::currencyFromString (pay_currency, taker_pays["currency"].asString ()))
             {
                 WriteLog (lsINFO, RPCHandler) << "Bad taker_pays currency.";
                 return rpcError (rpcSRC_CUR_MALFORMED);
             }
             // Parse optional issuer.
             else if (((taker_pays.isMember ("issuer"))
                       && (!taker_pays["issuer"].isString ()
                           || !STAmount::issuerFromString (pay_issuer, taker_pays["issuer"].asString ())))
                      // Don't allow illegal issuers.
                      || (!pay_currency != !pay_issuer)
                      || ACCOUNT_ONE == pay_issuer)
             {
                 WriteLog (lsINFO, RPCHandler) << "Bad taker_pays issuer.";
                 return rpcError (rpcSRC_ISR_MALFORMED);
             }
             // Parse mandatory currency.
             if (!taker_gets.isMember ("currency")
                     || !STAmount::currencyFromString (get_currency, taker_gets["currency"].asString ()))
             {
                 WriteLog (lsINFO, RPCHandler) << "Bad taker_pays currency.";
                 return rpcError (rpcSRC_CUR_MALFORMED);
             }
             // Parse optional issuer.
             else if (((taker_gets.isMember ("issuer"))
                       && (!taker_gets["issuer"].isString ()
                           || !STAmount::issuerFromString (get_issuer, taker_gets["issuer"].asString ())))
                      // Don't allow illegal issuers.
                      || (!get_currency != !get_issuer)
                      || ACCOUNT_ONE == get_issuer)
             {
                 WriteLog (lsINFO, RPCHandler) << "Bad taker_gets issuer.";
                 return rpcError (rpcDST_ISR_MALFORMED);
             }
             if (pay_currency == get_currency
                     && pay_issuer == get_issuer)
             {
                 WriteLog (lsINFO, RPCHandler) << "taker_gets same as taker_pays.";
                 return rpcError (rpcBAD_MARKET);
             }
             mNetOps->unsubBook (ispSub->getSeq (), pay_currency, get_currency, pay_issuer, get_issuer);
             if (bBoth) mNetOps->unsubBook (ispSub->getSeq (), get_currency, pay_currency, get_issuer, pay_issuer);
         }
     }
     return jvResult;
 }
Json::Value ripple::RPCHandler::doValidationCreate (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 28 of file ValidationCreate.cpp.
References Json::Value::asString(), ripple::RippleAddress::createNodePublic(), ripple::RippleAddress::humanNodePublic(), ripple::RippleAddress::humanSeed(), ripple::RippleAddress::humanSeed1751(), Json::Value::isMember(), ripple::lsDEBUG, Json::objectValue, ripple::rpcBAD_SEED, ripple::rpcError(), ripple::RippleAddress::setSeedGeneric(), ripple::RippleAddress::setSeedRandom(), and WriteLog.
Referenced by doCommand().
 {
     RippleAddress   raSeed;
     Json::Value     obj (Json::objectValue);
     if (!params.isMember ("secret"))
     {
         WriteLog (lsDEBUG, RPCHandler) << "Creating random validation seed.";
         raSeed.setSeedRandom ();                // Get a random seed.
     }
     else if (!raSeed.setSeedGeneric (params["secret"].asString ()))
     {
         return rpcError (rpcBAD_SEED);
     }
     obj["validation_public_key"]    = RippleAddress::createNodePublic (raSeed).humanNodePublic ();
     obj["validation_seed"]          = raSeed.humanSeed ();
     obj["validation_key"]           = raSeed.humanSeed1751 ();
     return obj;
 }
Json::Value ripple::RPCHandler::doValidationSeed (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 26 of file ValidationSeed.cpp.
References Json::Value::asString(), ripple::RippleAddress::clear(), ripple::RippleAddress::createNodePrivate(), ripple::RippleAddress::createNodePublic(), ripple::getConfig(), ripple::RippleAddress::humanNodePublic(), ripple::RippleAddress::humanSeed(), ripple::RippleAddress::humanSeed1751(), Json::Value::isMember(), Json::objectValue, ripple::rpcBAD_SEED, ripple::rpcError(), ripple::Config::VALIDATION_PRIV, ripple::Config::VALIDATION_PUB, and ripple::Config::VALIDATION_SEED.
Referenced by doCommand().
 {
     Json::Value obj (Json::objectValue);
     if (!params.isMember ("secret"))
     {
         Log::out() << "Unset validation seed.";
         getConfig ().VALIDATION_SEED.clear ();
         getConfig ().VALIDATION_PUB.clear ();
         getConfig ().VALIDATION_PRIV.clear ();
     }
     else if (!getConfig ().VALIDATION_SEED.setSeedGeneric (params["secret"].asString ()))
     {
         getConfig ().VALIDATION_PUB.clear ();
         getConfig ().VALIDATION_PRIV.clear ();
         return rpcError (rpcBAD_SEED);
     }
     else
     {
         getConfig ().VALIDATION_PUB = RippleAddress::createNodePublic (getConfig ().VALIDATION_SEED);
         getConfig ().VALIDATION_PRIV = RippleAddress::createNodePrivate (getConfig ().VALIDATION_SEED);
         obj["validation_public_key"]    = getConfig ().VALIDATION_PUB.humanNodePublic ();
         obj["validation_seed"]          = getConfig ().VALIDATION_SEED.humanSeed ();
         obj["validation_key"]           = getConfig ().VALIDATION_SEED.humanSeed1751 ();
     }
     return obj;
 }
Json::Value ripple::RPCHandler::doWalletAccounts (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 28 of file WalletAccounts.cpp.
References ripple::RPC::accounts(), ripple::RippleAddress::createGeneratorPublic(), Json::Value::empty(), ripple::RPC::getMasterGenerator(), Json::Value::isMember(), ripple::RPC::lookupLedger(), mNetOps, Json::objectValue, ripple::rpcBAD_SEED, ripple::rpcError(), and ripple::RippleAddress::setSeedGeneric().
Referenced by doCommand().
 {
     Ledger::pointer     lpLedger;
     Json::Value         jvResult    = RPC::lookupLedger (params, lpLedger, *mNetOps);
     if (!lpLedger)
         return jvResult;
     RippleAddress   naSeed;
     if (!params.isMember ("seed") || !naSeed.setSeedGeneric (params["seed"].asString ()))
     {
         return rpcError (rpcBAD_SEED);
     }
     // Try the seed as a master seed.
     RippleAddress   naMasterGenerator   = RippleAddress::createGeneratorPublic (naSeed);
     Json::Value jsonAccounts    = RPC::accounts (lpLedger, naMasterGenerator, *mNetOps);
     if (jsonAccounts.empty ())
     {
         // No account via seed as master, try seed a regular.
         Json::Value ret = RPC::getMasterGenerator (lpLedger, naSeed, naMasterGenerator, *mNetOps);
         if (!ret.empty ())
             return ret;
         ret["accounts"] = RPC::accounts (lpLedger, naMasterGenerator, *mNetOps);
         return ret;
     }
     else
     {
         // Had accounts via seed as master, return them.
         Json::Value ret (Json::objectValue);
         ret["accounts"] = jsonAccounts;
         return ret;
     }
 }
Json::Value ripple::RPCHandler::doWalletLock (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Json::Value ripple::RPCHandler::doWalletPropose (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 26 of file WalletPropose.cpp.
References Json::Value::asString(), ripple::RippleAddress::createGeneratorPublic(), ripple::RippleAddress::getAccountPublic(), ripple::RippleAddress::getSeed(), ripple::RippleAddress::humanAccountID(), ripple::RippleAddress::humanAccountPublic(), ripple::RippleAddress::humanSeed(), ripple::RippleAddress::humanSeed1751(), Json::Value::isMember(), Json::objectValue, ripple::rpcBAD_SEED, ripple::rpcError(), ripple::RippleAddress::setAccountPublic(), ripple::RippleAddress::setSeedGeneric(), ripple::RippleAddress::setSeedRandom(), ripple::strHex(), and ripple::base_uint< BITS >::ToString().
Referenced by doCommand().
 {
     masterLockHolder.unlock ();
     RippleAddress   naSeed;
     RippleAddress   naAccount;
     if (!params.isMember ("passphrase"))
         naSeed.setSeedRandom ();
     else if (!naSeed.setSeedGeneric (params["passphrase"].asString ()))
         return rpcError(rpcBAD_SEED);
     RippleAddress naGenerator = RippleAddress::createGeneratorPublic (naSeed);
     naAccount.setAccountPublic (naGenerator, 0);
     Json::Value obj (Json::objectValue);
     obj["master_seed"]      = naSeed.humanSeed ();
     obj["master_seed_hex"]  = naSeed.getSeed ().ToString ();
     obj["master_key"]     = naSeed.humanSeed1751();
     obj["account_id"]       = naAccount.humanAccountID ();
     obj["public_key"] = naAccount.humanAccountPublic();
     auto acct = naAccount.getAccountPublic();
     obj["public_key_hex"] = strHex(acct.begin(), acct.size());
     return obj;
 }
Json::Value ripple::RPCHandler::doWalletSeed (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Definition at line 25 of file WalletSeed.cpp.
References Json::Value::asString(), ripple::RippleAddress::createGeneratorPublic(), ripple::RippleAddress::humanSeed(), ripple::RippleAddress::humanSeed1751(), Json::Value::isMember(), Json::objectValue, ripple::rpcBAD_SEED, ripple::rpcError(), ripple::RippleAddress::setAccountPublic(), ripple::RippleAddress::setSeedGeneric(), and ripple::RippleAddress::setSeedRandom().
Referenced by doCommand().
 {
     RippleAddress   raSeed;
     bool            bSecret = params.isMember ("secret");
     if (bSecret && !raSeed.setSeedGeneric (params["secret"].asString ()))
     {
         return rpcError (rpcBAD_SEED);
     }
     else
     {
         RippleAddress   raAccount;
         if (!bSecret)
         {
             raSeed.setSeedRandom ();
         }
         RippleAddress   raGenerator = RippleAddress::createGeneratorPublic (raSeed);
         raAccount.setAccountPublic (raGenerator, 0);
         Json::Value obj (Json::objectValue);
         obj["seed"]     = raSeed.humanSeed ();
         obj["key"]      = raSeed.humanSeed1751 ();
         obj["deprecated"] = "Use wallet_propose instead";
         return obj;
     }
 }
Json::Value ripple::RPCHandler::doWalletUnlock (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Json::Value ripple::RPCHandler::doWalletVerify (Json::Value params, Resource::Charge & loadType, Application::ScopedLockType & mlh) private
Member Data Documentation
InfoSub::pointer ripple::RPCHandler::mInfoSub private
Definition at line 137 of file RPCHandler.h.
Referenced by doPathFind(), doSubscribe(), and doUnsubscribe().
NetworkOPs* ripple::RPCHandler::mNetOps private
Definition at line 136 of file RPCHandler.h.
Referenced by doAccountCurrencies(), doAccountInfo(), doAccountLines(), doAccountOffers(), doAccountTx(), doAccountTxOld(), doBookOffers(), doCommand(), doConsensusInfo(), doFetchInfo(), doLedger(), doLedgerAccept(), doLedgerClosed(), doLedgerCurrent(), doLedgerData(), doLedgerEntry(), doLedgerHeader(), doOwnerInfo(), doPathFind(), doRipplePathFind(), doServerInfo(), doServerState(), doSign(), doSubmit(), doSubscribe(), doTransactionEntry(), doTx(), doUnsubscribe(), and doWalletAccounts().
int ripple::RPCHandler::mRole private
Definition at line 140 of file RPCHandler.h.
Referenced by doAccountTx(), doAccountTxOld(), doCommand(), doLedger(), doLedgerData(), doRipplePathFind(), doServerInfo(), doServerState(), doSign(), doSubmit(), doSubscribe(), doTxHistory(), and doUnsubscribe().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/rpc/RPCHandler.h
rippled/src/ripple_app/rpc/RPCHandler.cpp
rippled/src/ripple_rpc/handlers/AccountCurrencies.cpp
rippled/src/ripple_rpc/handlers/AccountInfo.cpp
rippled/src/ripple_rpc/handlers/AccountLines.cpp
rippled/src/ripple_rpc/handlers/AccountOffers.cpp
rippled/src/ripple_rpc/handlers/AccountTx.cpp
rippled/src/ripple_rpc/handlers/AccountTxOld.cpp
rippled/src/ripple_rpc/handlers/AccountTxSwitch.cpp
rippled/src/ripple_rpc/handlers/BlackList.cpp
rippled/src/ripple_rpc/handlers/BookOffers.cpp
rippled/src/ripple_rpc/handlers/Connect.cpp
rippled/src/ripple_rpc/handlers/ConsensusInfo.cpp
rippled/src/ripple_rpc/handlers/Feature.cpp
rippled/src/ripple_rpc/handlers/FetchInfo.cpp
rippled/src/ripple_rpc/handlers/GetCounts.cpp
rippled/src/ripple_rpc/handlers/Ledger.cpp
rippled/src/ripple_rpc/handlers/LedgerAccept.cpp
rippled/src/ripple_rpc/handlers/LedgerCleaner.cpp
rippled/src/ripple_rpc/handlers/LedgerClosed.cpp
rippled/src/ripple_rpc/handlers/LedgerCurrent.cpp
rippled/src/ripple_rpc/handlers/LedgerData.cpp
rippled/src/ripple_rpc/handlers/LedgerEntry.cpp
rippled/src/ripple_rpc/handlers/LedgerHeader.cpp
rippled/src/ripple_rpc/handlers/LogLevel.cpp
rippled/src/ripple_rpc/handlers/LogRotate.cpp
rippled/src/ripple_rpc/handlers/OwnerInfo.cpp
rippled/src/ripple_rpc/handlers/PathFind.cpp
rippled/src/ripple_rpc/handlers/Peers.cpp
rippled/src/ripple_rpc/handlers/Ping.cpp
rippled/src/ripple_rpc/handlers/Print.cpp
rippled/src/ripple_rpc/handlers/Profile.cpp
rippled/src/ripple_rpc/handlers/ProofCreate.cpp
rippled/src/ripple_rpc/handlers/ProofSolve.cpp
rippled/src/ripple_rpc/handlers/ProofVerify.cpp
rippled/src/ripple_rpc/handlers/Random.cpp
rippled/src/ripple_rpc/handlers/RipplePathFind.cpp
rippled/src/ripple_rpc/handlers/ServerInfo.cpp
rippled/src/ripple_rpc/handlers/ServerState.cpp
rippled/src/ripple_rpc/handlers/Sign.cpp
rippled/src/ripple_rpc/handlers/SMS.cpp
rippled/src/ripple_rpc/handlers/Stop.cpp
rippled/src/ripple_rpc/handlers/Submit.cpp
rippled/src/ripple_rpc/handlers/Subscribe.cpp
rippled/src/ripple_rpc/handlers/TransactionEntry.cpp
rippled/src/ripple_rpc/handlers/Tx.cpp
rippled/src/ripple_rpc/handlers/TxHistory.cpp
rippled/src/ripple_rpc/handlers/UnlAdd.cpp
rippled/src/ripple_rpc/handlers/UnlDelete.cpp
rippled/src/ripple_rpc/handlers/UnlList.cpp
rippled/src/ripple_rpc/handlers/UnlLoad.cpp
rippled/src/ripple_rpc/handlers/UnlNetwork.cpp
rippled/src/ripple_rpc/handlers/UnlReset.cpp
rippled/src/ripple_rpc/handlers/UnlScore.cpp
rippled/src/ripple_rpc/handlers/Unsubscribe.cpp
rippled/src/ripple_rpc/handlers/ValidationCreate.cpp
rippled/src/ripple_rpc/handlers/ValidationSeed.cpp
rippled/src/ripple_rpc/handlers/WalletAccounts.cpp
rippled/src/ripple_rpc/handlers/WalletPropose.cpp
rippled/src/ripple_rpc/handlers/WalletSeed.cpp