rippled: beast::block_stream< Block, Derived > Class Template Reference
beast::block_stream< Block, Derived > Class Template Reference
Public Member Functions
block_stream ()
void operator() (void const *data, std::size_t bytes) noexcept
Protected Member Functions
void finish ()
Private Member Functions
std::size_t needed () const noexcept
void * tail () noexcept
Private Attributes
Block m_block
std::size_t m_size
Detailed Description
template<class Block, class Derived>
class beast::block_stream< Block, Derived >
Definition at line 46 of file hash_append.test.cpp.
Constructor & Destructor Documentation
template<class Block, class Derived> beast::block_stream< Block, Derived >::block_stream () inline
Definition at line 77 of file hash_append.test.cpp.
         : m_size(0)
     {
     }
Member Function Documentation
template<class Block, class Derived> void beast::block_stream< Block, Derived >::finish () inline protected
Definition at line 66 of file hash_append.test.cpp.
     {
         if (m_size > 0)
         {
             // zero-pad
             memset (tail(), 0, needed());
             static_cast <Derived*> (this)->process_block (m_block);
         }
     }
template<class Block, class Derived> std::size_t beast::block_stream< Block, Derived >::needed () const inline private noexcept
Definition at line 53 of file hash_append.test.cpp.
Referenced by beast::block_stream< std::size_t, prng_hasher< PRNG > >::finish(), and beast::block_stream< std::size_t, prng_hasher< PRNG > >::operator()().
     {
         return sizeof(Block) - m_size;
     }
template<class Block, class Derived> void beast::block_stream< Block, Derived >::operator() (void const * data, std::size_t bytes) inline noexcept
Definition at line 83 of file hash_append.test.cpp.
     {
         // handle leftovers
         if (m_size > 0)
         {
             std::size_t const n (std::min (needed(), bytes));
             std::memcpy (tail(), data, n);
             data = ((char const*)data) + n;
             bytes -= n;
             m_size += n;
             if (m_size < sizeof(Block))
                 return;
             static_cast <Derived*> (this)->process_block (m_block);
         }
         // loop over complete blocks
         while (bytes >= sizeof(Block))
         {
             m_block = *((Block const*)data);
             static_cast <Derived*> (this)->process_block (m_block);
             data = ((char const*)data) + sizeof(m_block);
             bytes -= sizeof(m_block);
         }
         // save leftovers
         if (bytes > 0)
         {
             memcpy (tail(), data, bytes);
             m_size += bytes;
         }
     }
template<class Block, class Derived> void* beast::block_stream< Block, Derived >::tail () inline private noexcept
Definition at line 59 of file hash_append.test.cpp.
Referenced by beast::block_stream< std::size_t, prng_hasher< PRNG > >::finish(), and beast::block_stream< std::size_t, prng_hasher< PRNG > >::operator()().
     {
         return ((char *)&m_block) + m_size;
     }
Member Data Documentation
template<class Block, class Derived> Block beast::block_stream< Block, Derived >::m_block private
Definition at line 49 of file hash_append.test.cpp.
Referenced by beast::block_stream< std::size_t, prng_hasher< PRNG > >::finish(), beast::block_stream< std::size_t, prng_hasher< PRNG > >::operator()(), and beast::block_stream< std::size_t, prng_hasher< PRNG > >::tail().
template<class Block, class Derived> std::size_t beast::block_stream< Block, Derived >::m_size private
Definition at line 50 of file hash_append.test.cpp.
Referenced by beast::block_stream< std::size_t, prng_hasher< PRNG > >::finish(), beast::block_stream< std::size_t, prng_hasher< PRNG > >::needed(), beast::block_stream< std::size_t, prng_hasher< PRNG > >::operator()(), and beast::block_stream< std::size_t, prng_hasher< PRNG > >::tail().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/container/tests/hash_append.test.cpp