rippled: beast::insight::Gauge Class Reference
beast::insight::Gauge Class Reference
#include <Gauge.h>
Public Types
typedef GaugeImpl::value_type value_type
typedef GaugeImpl::difference_type difference_type
Public Member Functions
Gauge ()
Gauge (std::shared_ptr< GaugeImpl > const &impl)
std::shared_ptr< GaugeImpl >
const & impl () const
void set (value_type value) const
Gauge const & operator= (value_type value) const
void increment (difference_type amount) const
Gauge const & operator+= (difference_type amount) const
Gauge const & operator-= (difference_type amount) const
Gauge const & operator++ () const
Gauge const & operator++ (int) const
Gauge const & operator-- () const
Gauge const & operator-- (int) const
Public Member Functions inherited from beast::insight::Base
virtual ~Base ()=0
Private Attributes
std::shared_ptr< GaugeImpl > m_impl
Detailed Description
A metric for measuring an integral value.
A gauge is an instantaneous measurement of a value, like the gas gauge in a car. The caller directly sets the value, or adjusts it by a specified amount. The value is kept in the client rather than the collector.
This is a lightweight reference wrapper which is cheap to copy and assign. When the last reference goes away, the metric is no longer collected.
Definition at line 40 of file Gauge.h.
Member Typedef Documentation
typedef GaugeImpl::difference_type beast::insight::Gauge::difference_type
Definition at line 44 of file Gauge.h.
typedef GaugeImpl::value_type beast::insight::Gauge::value_type
Definition at line 43 of file Gauge.h.
Constructor & Destructor Documentation
beast::insight::Gauge::Gauge () inline
Create a null metric. A null metric reports no information.
Definition at line 49 of file Gauge.h.
     {
     }
beast::insight::Gauge::Gauge (std::shared_ptr< GaugeImpl > const & impl) inline explicit
Create the metric reference the specified implementation. Normally this won't be called directly. Instead, call the appropriate factory function in the Collector interface.
See Also
Collector.
Definition at line 58 of file Gauge.h.
         : m_impl (impl)
     {
     }
Member Function Documentation
std::shared_ptr<GaugeImpl> const& beast::insight::Gauge::impl () const inline
Definition at line 131 of file Gauge.h.
References m_impl.
     {
         return m_impl;
     }
void beast::insight::Gauge::increment (difference_type amount) const inline
Adjust the value of the gauge.
Definition at line 81 of file Gauge.h.
References m_impl.
Referenced by operator++(), operator+=(), operator--(), and operator-=().
     {
         if (m_impl)
             m_impl->increment (amount);
     }
Gauge const& beast::insight::Gauge::operator++ () const inline
Definition at line 102 of file Gauge.h.
References increment().
     {
         increment (1);
         return *this;
     }
Gauge const& beast::insight::Gauge::operator++ (int) const inline
Definition at line 109 of file Gauge.h.
References increment().
     {
         increment (1);
         return *this;
     }
Gauge const& beast::insight::Gauge::operator+= (difference_type amount) const inline
Definition at line 88 of file Gauge.h.
References increment().
     {
         increment (amount);
         return *this;
     }
Gauge const& beast::insight::Gauge::operator-- () const inline
Definition at line 116 of file Gauge.h.
References increment().
     {
         increment (-1);
         return *this;
     }
Gauge const& beast::insight::Gauge::operator-- (int) const inline
Definition at line 123 of file Gauge.h.
References increment().
     {
         increment (-1);
         return *this;
     }
Gauge const& beast::insight::Gauge::operator-= (difference_type amount) const inline
Definition at line 95 of file Gauge.h.
References increment().
     {
         increment (-amount);
         return *this;
     }
Gauge const& beast::insight::Gauge::operator= (value_type value) const inline
Definition at line 75 of file Gauge.h.
References set().
         { set (value); return *this; }
void beast::insight::Gauge::set (value_type value) const inline
Set the value on the gauge. A Collector implementation should combine multiple calls to value changes into a single change if the calls occur within a single collection interval.
Definition at line 69 of file Gauge.h.
References m_impl.
Referenced by ripple::KeyCache< Key >::collect_metrics(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::collect_metrics(), and operator=().
     {
         if (m_impl)
             m_impl->set (value);
     }
Member Data Documentation
std::shared_ptr<GaugeImpl> beast::insight::Gauge::m_impl private
Definition at line 137 of file Gauge.h.
Referenced by impl(), increment(), and set().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/insight/Gauge.h