rippled: rocksdb::StringAppendOperatorTest Class Reference
rocksdb::StringAppendOperatorTest Class Reference
Public Types
typedef std::shared_ptr< DB >(* OpenFuncPtr)(char)
Public Member Functions
StringAppendOperatorTest ()
Static Public Member Functions
static void SetOpenDbFunction (OpenFuncPtr func)
Static Protected Attributes
static OpenFuncPtr OpenDb = nullptr
Detailed Description
Definition at line 108 of file stringappend_test.cc.
Member Typedef Documentation
typedef std::shared_ptr<DB>(* rocksdb::StringAppendOperatorTest::OpenFuncPtr)(char)
Definition at line 114 of file stringappend_test.cc.
Constructor & Destructor Documentation
rocksdb::StringAppendOperatorTest::StringAppendOperatorTest () inline
Definition at line 110 of file stringappend_test.cc.
References rocksdb::DestroyDB(), and rocksdb::kDbName.
{
     DestroyDB(kDbName, Options());    // Start each test with a fresh DB
   }
Member Function Documentation
static void rocksdb::StringAppendOperatorTest::SetOpenDbFunction (OpenFuncPtr func) inline static
Definition at line 118 of file stringappend_test.cc.
References func, and rocksdb::OpenDb().
Referenced by main().
{
     OpenDb = func;
   }
Member Data Documentation
StringAppendOperatorTest::OpenFuncPtr rocksdb::StringAppendOperatorTest::OpenDb = nullptr static protected
Definition at line 123 of file stringappend_test.cc.
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/utilities/merge_operators/string_append/stringappend_test.cc