rippled: beast::IP::Endpoint Class Reference
beast::IP::Endpoint Class Reference
#include <IPEndpoint.h>
Public Member Functions
Endpoint ()
Endpoint (Address const &addr, Port port=0)
std::string to_string () const
Port port () const
Endpoint at_port (Port port) const
Address const & address () const
bool is_v4 () const
bool is_v6 () const
AddressV4 const & to_v4 () const
AddressV6 const & to_v6 () const
Static Public Member Functions
static std::pair< Endpoint, bool > from_string_checked (std::string const &s)
static Endpoint from_string (std::string const &s)
static Endpoint from_string_altform (std::string const &s)
Private Attributes
Address m_addr
Port m_port
Friends
template<class Hasher >
void hash_append (Hasher &h, Endpoint const &endpoint)
bool operator== (Endpoint const &lhs, Endpoint const &rhs)
bool operator< (Endpoint const &lhs, Endpoint const &rhs)
bool operator!= (Endpoint const &lhs, Endpoint const &rhs)
bool operator> (Endpoint const &lhs, Endpoint const &rhs)
bool operator<= (Endpoint const &lhs, Endpoint const &rhs)
bool operator>= (Endpoint const &lhs, Endpoint const &rhs)
Detailed Description
A version-independent IP address and port combination.
Definition at line 36 of file IPEndpoint.h.
Constructor & Destructor Documentation
beast::IP::Endpoint::Endpoint ()
Create an unspecified endpoint.
Definition at line 30 of file IPEndpoint.cpp.
Referenced by at_port(), from_string(), and from_string_altform().
     : m_port (0)
 {
 }
beast::IP::Endpoint::Endpoint (Address const & addr, Port port = 0) explicit
Create an endpoint from the address and optional port.
Definition at line 35 of file IPEndpoint.cpp.
     : m_addr (addr)
     , m_port (port)
 {
 }
Member Function Documentation
Address const& beast::IP::Endpoint::address () const inline
Returns the address portion of this endpoint.
Definition at line 65 of file IPEndpoint.h.
References m_addr.
Referenced by ripple::Resource::Logic::exportConsumers(), beast::IP::hash_value(), beast::IP::is_loopback(), beast::IP::is_multicast(), beast::IP::is_private(), beast::IP::is_public(), beast::IP::is_unspecified(), ripple::PeerFinder::Logic::new_inbound_slot(), beast::IP::operator<(), beast::IP::operator==(), ripple::PeerFinder::Logic::preprocess(), beast::IP::to_asio_address(), to_string(), ripple::PeerFinder::RedirectHandouts::try_insert(), ripple::PeerFinder::SlotHandouts::try_insert(), and ripple::PeerFinder::ConnectHandouts::try_insert().
         { return m_addr; }
Endpoint beast::IP::Endpoint::at_port (Port port) const inline
Returns a new Endpoint with a different port.
Definition at line 61 of file IPEndpoint.h.
References Endpoint(), and m_addr.
Referenced by ripple::PeerFinder::Logic::broadcast(), ripple::RPCHandler::doConnect(), from_string_altform(), ripple::Config::getAdminRole(), ripple::PeerFinder::Logic::new_inbound_slot(), ripple::PeerFinder::Logic::new_outbound_slot(), ripple::Resource::Logic::newInboundEndpoint(), ripple::PeerFinder::Logic::preprocess(), ripple::RPCHTTPServerImp::processSession(), ripple::PeerImp::recvEndpoints(), and ripple::RPCHTTPServerImp::setup().
         { return Endpoint (m_addr, port); }
Endpoint beast::IP::Endpoint::from_string (std::string const & s) static
Definition at line 51 of file IPEndpoint.cpp.
References Endpoint(), and from_string_checked().
Referenced by ripple::CollectorManagerImp::CollectorManagerImp(), ripple::Config::Config(), ripple::RPCHandler::doConnect(), ripple::PeerFinder::SourceStringsImp::fetch(), from_string_altform(), ripple::PeerFinder::StoreSqdb::load(), ripple::parseAddresses(), ripple::PeerFinder::ManagerImp::parseBootstrapIPs(), ripple::PeerFinder::ManagerImp::parseFixedIPs(), ripple::PeerImp::recvCluster(), ripple::RPCHTTPServerImp::setup(), ripple::Resource::Manager_test::testCharges(), ripple::Resource::Manager_test::testDrop(), and ripple::PeerFinder::StoreSqdb::update().
 {
     std::pair <Endpoint, bool> const result (
         from_string_checked (s));
     if (result.second)
         return result.first;
     return Endpoint();
 }
Endpoint beast::IP::Endpoint::from_string_altform (std::string const & s) static
Definition at line 62 of file IPEndpoint.cpp.
References at_port(), Endpoint(), beast::IP::detail::expect(), from_string(), beast::IP::is_unspecified(), and port().
Referenced by ripple::PeerFinder::SourceStringsImp::fetch(), ripple::parseAddresses(), ripple::PeerFinder::ManagerImp::parseBootstrapIPs(), and ripple::PeerFinder::ManagerImp::parseFixedIPs().
 {
     // Accept the regular form if it parses
     {
         Endpoint ep (Endpoint::from_string (s));
         if (! is_unspecified (ep))
             return ep;
     }
     // Now try the alt form
     std::stringstream is (s);
     AddressV4 v4;
     is >> v4;
     if (! is.fail())
     {
         Endpoint ep (v4);
         if (is.rdbuf()->in_avail()>0)
         {
             if (! IP::detail::expect (is, ' '))
                 return Endpoint();
             while (is.rdbuf()->in_avail()>0)
             {
                 char c;
                 is.get(c);
                 if (c != ' ')
                 {
                     is.unget();
                     break;
                 }
             }
             Port port;
             is >> port;
             if (is.fail())
                 return Endpoint();
             return ep.at_port (port);
         }
         else
         {
             // Just an address with no port
             return ep;
         }
     }
     // Could be V6 here...
     return Endpoint();
 }
std::pair< Endpoint, bool > beast::IP::Endpoint::from_string_checked (std::string const & s) static
Create an Endpoint from a string. If the port is omitted, the endpoint will have a zero port.
Returns
A pair with the endpoint, and bool set to true on success.
Definition at line 41 of file IPEndpoint.cpp.
Referenced by from_string(), and beast::IP::IPEndpoint_test::testEndpoint().
 {
     std::stringstream is (s);
     Endpoint endpoint;
     is >> endpoint;
     if (! is.fail() && is.rdbuf()->in_avail() == 0)
         return std::make_pair (endpoint, true);
     return std::make_pair (Endpoint (), false);
 }
bool beast::IP::Endpoint::is_v4 () const inline
Convenience accessors for the address part.
Definition at line 70 of file IPEndpoint.h.
References beast::IP::Address::is_v4(), and m_addr.
Referenced by ripple::OverlayImpl::send(), ripple::HTTP::to_asio(), and beast::insight::detail::StatsDCollectorImp::to_endpoint().
         { return m_addr.is_v4(); }
bool beast::IP::Endpoint::is_v6 () const inline
Definition at line 72 of file IPEndpoint.h.
References beast::IP::Address::is_v6(), and m_addr.
         { return m_addr.is_v6(); }
Port beast::IP::Endpoint::port () const inline
Returns the port number on the endpoint.
Definition at line 57 of file IPEndpoint.h.
References m_port.
Referenced by from_string_altform(), beast::IP::hash_value(), ripple::PeerFinder::Logic::is_valid_address(), beast::IP::operator<(), beast::IP::operator==(), ripple::PeerFinder::Logic::preprocess(), ripple::OverlayImpl::send(), ripple::RPCHTTPServerImp::setup(), beast::IP::to_asio_endpoint(), beast::insight::detail::StatsDCollectorImp::to_endpoint(), and to_string().
         { return m_port; }
std::string beast::IP::Endpoint::to_string () const
Returns a string representing the endpoint.
Definition at line 115 of file IPEndpoint.cpp.
References address(), port(), and beast::IP::to_string().
Referenced by ripple::PeerImp::json(), ripple::RPCServerHandler::processRequest(), ripple::RPCHTTPServerImp::processRequest(), ripple::Resource::Entry::to_string(), ripple::to_string(), and beast::IP::to_string().
 {
     std::string s (address ().to_string ());
     if (port() != 0)
         s = s + ":" + std::to_string (port());
     return s;
 }
AddressV4 const& beast::IP::Endpoint::to_v4 () const inline
Definition at line 74 of file IPEndpoint.h.
References m_addr, and beast::IP::Address::to_v4().
Referenced by ripple::OverlayImpl::send(), beast::IP::IPEndpoint_test::testEndpoint(), ripple::HTTP::to_asio(), and beast::insight::detail::StatsDCollectorImp::to_endpoint().
         { return m_addr.to_v4 (); }
AddressV6 const& beast::IP::Endpoint::to_v6 () const inline
Definition at line 76 of file IPEndpoint.h.
References m_addr, and beast::IP::Address::to_v6().
         { return m_addr.to_v6 (); }
Friends And Related Function Documentation
template<class Hasher > void hash_append (Hasher & h, Endpoint const & endpoint) friend
Definition at line 98 of file IPEndpoint.h.
     {
         using beast::hash_append;
         hash_append(h, endpoint.m_addr, endpoint.m_port);
     }
bool operator!= (Endpoint const & lhs, Endpoint const & rhs) friend
Definition at line 85 of file IPEndpoint.h.
         { return ! (lhs == rhs); }
bool operator< (Endpoint const & lhs, Endpoint const & rhs) friend
Definition at line 129 of file IPEndpoint.cpp.
 {
     if (lhs.address() < rhs.address())
         return true;
     if (lhs.address() > rhs.address())
         return false;
     return lhs.port() < rhs.port();
 }
bool operator<= (Endpoint const & lhs, Endpoint const & rhs) friend
Definition at line 89 of file IPEndpoint.h.
         { return ! (lhs > rhs); }
bool operator== (Endpoint const & lhs, Endpoint const & rhs) friend
Arithmetic comparison.
Definition at line 123 of file IPEndpoint.cpp.
 {
     return lhs.address() == rhs.address() &&
            lhs.port() == rhs.port();
 }
bool operator> (Endpoint const & lhs, Endpoint const & rhs) friend
Definition at line 87 of file IPEndpoint.h.
         { return rhs < lhs; }
bool operator>= (Endpoint const & lhs, Endpoint const & rhs) friend
Definition at line 91 of file IPEndpoint.h.
         { return ! (rhs > lhs); }
Member Data Documentation
Address beast::IP::Endpoint::m_addr private
Definition at line 105 of file IPEndpoint.h.
Referenced by address(), at_port(), is_v4(), is_v6(), to_v4(), and to_v6().
Port beast::IP::Endpoint::m_port private
Definition at line 106 of file IPEndpoint.h.
Referenced by port().
The documentation for this class was generated from the following files:
rippled/src/beast/beast/net/IPEndpoint.h
rippled/src/beast/beast/net/impl/IPEndpoint.cpp