rippled: beast::HeapBlock< ElementType, throwOnFailure > Class Template Reference
beast::HeapBlock< ElementType, throwOnFailure > Class Template Reference
#include <HeapBlock.h>
Public Types
typedef ElementType Type
Public Member Functions
HeapBlock () noexcept
HeapBlock (HeapBlock &other)
HeapBlock (const size_t numElements)
HeapBlock (const size_t numElements, const bool initialiseToZero)
~HeapBlock ()
operator ElementType * () const noexcept
ElementType * getData () const noexcept
operator void * () const noexcept
operator const void * () const noexcept
ElementType * operator-> () const noexcept
template<typename IndexType >
ElementType & operator[] (IndexType index) const noexcept
template<typename IndexType >
ElementType * operator+ (IndexType index) const noexcept
bool operator== (const ElementType *const otherPointer) const noexcept
bool operator!= (const ElementType *const otherPointer) const noexcept
void malloc (const size_t newNumElements, const size_t elementSize=sizeof(ElementType))
void calloc (const size_t newNumElements, const size_t elementSize=sizeof(ElementType))
void allocate (const size_t newNumElements, bool initialiseToZero)
void reallocate (const size_t newNumElements, const size_t elementSize=sizeof(ElementType))
void free_up ()
template<bool otherBlockThrows>
void swapWith (HeapBlock< ElementType, otherBlockThrows > &other) noexcept
void clear (size_t numElements) noexcept
Private Member Functions
void throwOnAllocationFailure () const
Private Attributes
ElementType * data
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
template<class ElementType, bool throwOnFailure = false>
class beast::HeapBlock< ElementType, throwOnFailure >
Very simple container class to hold a pointer to some data on the heap.
When you need to allocate some heap storage for something, always try to use this class instead of allocating the memory directly using malloc/free.
A HeapBlock<char> object can be treated in pretty much exactly the same way as an char*, but as long as you allocate it on the stack or as a class member, it's almost impossible for it to leak memory.
It also makes your code much more concise and readable than doing the same thing using direct allocations,
E.g. instead of this:
int* temp = (int*) malloc (1024 * sizeof (int));
memcpy (temp, xyz, 1024 * sizeof (int));
free (temp);
temp = (int*) calloc (2048 * sizeof (int));
temp[0] = 1234;
memcpy (foobar, temp, 2048 * sizeof (int));
free (temp);
..you could just write this:
HeapBlock <int> temp (1024);
memcpy (temp, xyz, 1024 * sizeof (int));
temp.calloc (2048);
temp[0] = 1234;
memcpy (foobar, temp, 2048 * sizeof (int));
The class is extremely lightweight, containing only a pointer to the data, and exposes malloc/realloc/calloc/free methods that do the same jobs as their less object-oriented counterparts. Despite adding safety, you probably won't sacrifice any performance by using this in place of normal pointers.
The throwOnFailure template parameter can be set to true if you'd like the class to throw a std::bad_alloc exception when an allocation fails. If this is false, then a failed allocation will just leave the heapblock with a null pointer (assuming that the system's malloc() function doesn't throw).
See Also
Array, MemoryBlock
Definition at line 125 of file HeapBlock.h.
Member Typedef Documentation
template<class ElementType, bool throwOnFailure = false> typedef ElementType beast::HeapBlock< ElementType, throwOnFailure >::Type
This typedef can be used to get the type of the heapblock's elements.
Definition at line 332 of file HeapBlock.h.
Constructor & Destructor Documentation
template<class ElementType, bool throwOnFailure = false> beast::HeapBlock< ElementType, throwOnFailure >::HeapBlock () inline noexcept
Creates a HeapBlock which is initially just a null pointer.
After creation, you can resize the array using the malloc(), calloc(), or realloc() methods.
Definition at line 134 of file HeapBlock.h.
         : data (nullptr)
     {
     }
template<class ElementType, bool throwOnFailure = false> beast::HeapBlock< ElementType, throwOnFailure >::HeapBlock (HeapBlock< ElementType, throwOnFailure > & other) inline
Definition at line 139 of file HeapBlock.h.
     {
         data = other.data;
         other.data = nullptr;
     }
template<class ElementType, bool throwOnFailure = false> beast::HeapBlock< ElementType, throwOnFailure >::HeapBlock (const size_t numElements) inline explicit
Creates a HeapBlock containing a number of elements.
The contents of the block are undefined, as it will have been created by a malloc call.
If you want an array of zero values, you can use the calloc() method or the other constructor that takes an InitialisationState parameter.
Definition at line 153 of file HeapBlock.h.
         : data (static_cast <ElementType*> (std::malloc (numElements * sizeof (ElementType))))
     {
         throwOnAllocationFailure();
     }
template<class ElementType, bool throwOnFailure = false> beast::HeapBlock< ElementType, throwOnFailure >::HeapBlock (const size_t numElements, const bool initialiseToZero) inline
Creates a HeapBlock containing a number of elements.
The initialiseToZero parameter determines whether the new memory should be cleared, or left uninitialised.
Definition at line 164 of file HeapBlock.h.
         : data (static_cast <ElementType*> (initialiseToZero
                                                ? std::calloc (numElements, sizeof (ElementType))
                                                : std::malloc (numElements * sizeof (ElementType))))
     {
         throwOnAllocationFailure();
     }
template<class ElementType, bool throwOnFailure = false> beast::HeapBlock< ElementType, throwOnFailure >::~HeapBlock () inline
Destructor. This will free the data, if any has been allocated.
Definition at line 175 of file HeapBlock.h.
     {
         std::free (data);
     }
Member Function Documentation
template<class ElementType, bool throwOnFailure = false> void beast::HeapBlock< ElementType, throwOnFailure >::allocate (const size_t newNumElements, bool initialiseToZero) inline
Allocates a specified amount of memory and optionally clears it. This does the same job as either malloc() or calloc(), depending on the initialiseToZero parameter.
Definition at line 283 of file HeapBlock.h.
Referenced by beast::MemoryBlock::MemoryBlock(), and beast::MemoryBlock::setSize().
     {
         std::free (data);
         data = static_cast <ElementType*> (initialiseToZero
                                              ? std::calloc (newNumElements, sizeof (ElementType))
                                              : std::malloc (newNumElements * sizeof (ElementType)));
         throwOnAllocationFailure();
     }
template<class ElementType, bool throwOnFailure = false> void beast::HeapBlock< ElementType, throwOnFailure >::calloc (const size_t newNumElements, const size_t elementSize = sizeof (ElementType)) inline
Allocates a specified amount of memory and clears it. This does the same job as the malloc() method, but clears the memory that it allocates.
Definition at line 272 of file HeapBlock.h.
Referenced by beast::WindowsFileHelpers::getDriveFromPath(), and beast::SystemStats::getStackBacktrace().
     {
         std::free (data);
         data = static_cast <ElementType*> (std::calloc (newNumElements, elementSize));
         throwOnAllocationFailure();
     }
template<class ElementType, bool throwOnFailure = false> void beast::HeapBlock< ElementType, throwOnFailure >::clear (size_t numElements) inline noexcept
This fills the block with zeros, up to the number of elements specified. Since the block has no way of knowing its own size, you must make sure that the number of elements you specify doesn't exceed the allocated size.
Definition at line 326 of file HeapBlock.h.
     {
         zeromem (data, sizeof (ElementType) * numElements);
     }
template<class ElementType, bool throwOnFailure = false> void beast::HeapBlock< ElementType, throwOnFailure >::free_up () inline
Frees any currently-allocated data. This will free the data and reset this object to be a null pointer.
Definition at line 307 of file HeapBlock.h.
Referenced by beast::ArrayAllocationBase< beast::String, DummyCriticalSection >::setAllocatedSize(), and beast::MemoryBlock::setSize().
     {
         std::free (data);
         data = nullptr;
     }
template<class ElementType, bool throwOnFailure = false> ElementType* beast::HeapBlock< ElementType, throwOnFailure >::getData () const inline noexcept
Returns a raw pointer to the allocated data. This may be a null pointer if the data hasn't yet been allocated, or if it has been freed by calling the free() method.
Definition at line 205 of file HeapBlock.h.
Referenced by beast::String::formatted(), and beast::UnitTestUtilities::Payload::operator==().
 { return data; }
template<class ElementType, bool throwOnFailure = false> void beast::HeapBlock< ElementType, throwOnFailure >::malloc (const size_t newNumElements, const size_t elementSize = sizeof (ElementType)) inline
Allocates a specified amount of memory.
This uses the normal malloc to allocate an amount of memory for this object. Any previously allocated memory will be freed by this method.
The number of bytes allocated will be (newNumElements * elementSize). Normally you wouldn't need to specify the second parameter, but it can be handy if you need to allocate a size in bytes rather than in terms of the number of elements.
The data that is allocated will be freed when this object is deleted, or when you call free() or any of the allocation methods.
Definition at line 262 of file HeapBlock.h.
Referenced by beast::RandomAccessFile_test::createRecords(), beast::File::getCurrentWorkingDirectory(), and beast::MemoryBlock::MemoryBlock().
     {
         std::free (data);
         data = static_cast <ElementType*> (std::malloc (newNumElements * elementSize));
         throwOnAllocationFailure();
     }
template<class ElementType, bool throwOnFailure = false> beast::HeapBlock< ElementType, throwOnFailure >::operator const void * () const inline noexcept
Returns a void pointer to the allocated data. This may be a null pointer if the data hasn't yet been allocated, or if it has been freed by calling the free() method.
Definition at line 217 of file HeapBlock.h.
 { return static_cast <const void*> (data); }
template<class ElementType, bool throwOnFailure = false> beast::HeapBlock< ElementType, throwOnFailure >::operator ElementType * () const inline noexcept
Returns a raw pointer to the allocated data. This may be a null pointer if the data hasn't yet been allocated, or if it has been freed by calling the free() method.
Definition at line 199 of file HeapBlock.h.
 { return data; }
template<class ElementType, bool throwOnFailure = false> beast::HeapBlock< ElementType, throwOnFailure >::operator void * () const inline noexcept
Returns a void pointer to the allocated data. This may be a null pointer if the data hasn't yet been allocated, or if it has been freed by calling the free() method.
Definition at line 211 of file HeapBlock.h.
 { return static_cast <void*> (data); }
template<class ElementType, bool throwOnFailure = false> bool beast::HeapBlock< ElementType, throwOnFailure >::operator!= (const ElementType *const otherPointer) const inline noexcept
Compares the pointer with another pointer. This can be handy for checking whether this is a null pointer.
Definition at line 247 of file HeapBlock.h.
 { return otherPointer != data; }
template<class ElementType, bool throwOnFailure = false> template<typename IndexType > ElementType* beast::HeapBlock< ElementType, throwOnFailure >::operator+ (IndexType index) const inline noexcept
Returns a pointer to a data element at an offset from the start of the array. This is the same as doing pointer arithmetic on the raw pointer itself.
Definition at line 236 of file HeapBlock.h.
 { return data + index; }
template<class ElementType, bool throwOnFailure = false> ElementType* beast::HeapBlock< ElementType, throwOnFailure >::operator-> () const inline noexcept
Lets you use indirect calls to the first element in the array. Obviously this will cause problems if the array hasn't been initialised, because it'll be referencing a null pointer.
Definition at line 223 of file HeapBlock.h.
 { return data; }
template<class ElementType, bool throwOnFailure = false> bool beast::HeapBlock< ElementType, throwOnFailure >::operator== (const ElementType *const otherPointer) const inline noexcept
Compares the pointer with another pointer. This can be handy for checking whether this is a null pointer.
Definition at line 242 of file HeapBlock.h.
 { return otherPointer == data; }
template<class ElementType, bool throwOnFailure = false> template<typename IndexType > ElementType& beast::HeapBlock< ElementType, throwOnFailure >::operator[] (IndexType index) const inline noexcept
Returns a reference to one of the data elements. Obviously there's no bounds-checking here, as this object is just a dumb pointer and has no idea of the size it currently has allocated.
Definition at line 230 of file HeapBlock.h.
 { return data [index]; }
template<class ElementType, bool throwOnFailure = false> void beast::HeapBlock< ElementType, throwOnFailure >::reallocate (const size_t newNumElements, const size_t elementSize = sizeof (ElementType)) inline
Re-allocates a specified amount of memory.
The semantics of this method are the same as malloc() and calloc(), but it uses realloc() to keep as much of the existing data as possible.
Definition at line 297 of file HeapBlock.h.
Referenced by beast::ArrayAllocationBase< beast::String, DummyCriticalSection >::setAllocatedSize(), and beast::MemoryBlock::setSize().
     {
         data = static_cast <ElementType*> (data == nullptr ? std::malloc (newNumElements * elementSize)
                                                            : std::realloc (data, newNumElements * elementSize));
         throwOnAllocationFailure();
     }
template<class ElementType, bool throwOnFailure = false> template<bool otherBlockThrows> void beast::HeapBlock< ElementType, throwOnFailure >::swapWith (HeapBlock< ElementType, otherBlockThrows > & other) inline noexcept
Swaps this object's data with the data of another HeapBlock. The two objects simply exchange their data pointers.
Definition at line 317 of file HeapBlock.h.
Referenced by beast::ArrayAllocationBase< beast::String, DummyCriticalSection >::swapWith().
     {
         std::swap (data, other.data);
     }
template<class ElementType, bool throwOnFailure = false> void beast::HeapBlock< ElementType, throwOnFailure >::throwOnAllocationFailure () const inline private
Definition at line 338 of file HeapBlock.h.
Referenced by beast::HeapBlock< ElementType >::allocate(), beast::HeapBlock< ElementType >::calloc(), beast::HeapBlock< ElementType >::HeapBlock(), beast::HeapBlock< ElementType >::malloc(), and beast::HeapBlock< ElementType >::reallocate().
     {
         HeapBlockHelper::ThrowOnFail<throwOnFailure>::check (data);
     }
Member Data Documentation
template<class ElementType, bool throwOnFailure = false> ElementType* beast::HeapBlock< ElementType, throwOnFailure >::data private
Definition at line 336 of file HeapBlock.h.
Referenced by beast::HeapBlock< ElementType >::allocate(), beast::HeapBlock< ElementType >::calloc(), beast::HeapBlock< ElementType >::clear(), beast::HeapBlock< ElementType >::free_up(), beast::HeapBlock< ElementType >::getData(), beast::HeapBlock< ElementType >::HeapBlock(), beast::HeapBlock< ElementType >::malloc(), beast::HeapBlock< ElementType >::operator const void *(), beast::HeapBlock< ElementType >::operator ElementType *(), beast::HeapBlock< ElementType >::operator void *(), beast::HeapBlock< ElementType >::operator!=(), beast::HeapBlock< ElementType >::operator+(), beast::HeapBlock< ElementType >::operator->(), beast::HeapBlock< ElementType >::operator==(), beast::HeapBlock< ElementType >::operator[](), beast::HeapBlock< ElementType >::reallocate(), beast::HeapBlock< ElementType >::swapWith(), beast::HeapBlock< ElementType >::throwOnAllocationFailure(), and beast::HeapBlock< ElementType >::~HeapBlock().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/HeapBlock.h