rippled: rocksdb::port::AtomicPointer Class Reference
rocksdb::port::AtomicPointer Class Reference
#include <port_example.h>
Public Member Functions
AtomicPointer ()
AtomicPointer (void *v)
void * Acquire_Load () const
void Release_Store (void *v)
void * NoBarrier_Load () const
void NoBarrier_Store (void *v)
Private Attributes
intptr_t rep_
Detailed Description
Definition at line 80 of file port_example.h.
Constructor & Destructor Documentation
rocksdb::port::AtomicPointer::AtomicPointer ()
rocksdb::port::AtomicPointer::AtomicPointer (void * v) inline explicit
Definition at line 88 of file port_example.h.
 : rep_(v) { }
Member Function Documentation
void* rocksdb::port::AtomicPointer::Acquire_Load () const
Referenced by rocksdb::Benchmark::AcquireLoad(), rocksdb::DBImpl::BackgroundCallCompaction(), rocksdb::DBImpl::BackgroundCallFlush(), rocksdb::DBImpl::BackgroundCompaction(), rocksdb::ConcurrentReader(), rocksdb::DBImpl::DoCompactionWork(), rocksdb::DBImpl::FlushMemTableToOutputFile(), rocksdb::ConcurrentTest::State::Get(), rocksdb::DBImpl::LogDBDeployStats(), rocksdb::DBImpl::MaybeScheduleFlushOrCompaction(), rocksdb::DBImpl::MaybeScheduleLogDBDeployStats(), rocksdb::SpecialEnv::NewWritableFile(), ReplicationThreadBody(), and rocksdb::TEST().
void* rocksdb::port::AtomicPointer::NoBarrier_Load () const
Referenced by rocksdb::DBImpl::DoCompactionWork(), rocksdb::SkipList< Key, rocksdb::TestComparator >::GetMaxHeight(), rocksdb::MemTableList::IsFlushPending(), and rocksdb::TEST().
void rocksdb::port::AtomicPointer::NoBarrier_Store (void * v)
void rocksdb::port::AtomicPointer::Release_Store (void * v)
Referenced by rocksdb::MemTableList::Add(), rocksdb::MemTableList::InstallMemtableFlushResults(), main(), rocksdb::MemTableList::MemTableList(), rocksdb::MemTableList::PickMemtablesToFlush(), rocksdb::RunConcurrent(), rocksdb::ConcurrentTest::State::Set(), rocksdb::SpecialEnv::SpecialEnv(), rocksdb::TEST(), and rocksdb::DBImpl::~DBImpl().
Member Data Documentation
intptr_t rocksdb::port::AtomicPointer::rep_ private
Definition at line 82 of file port_example.h.
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/port/port_example.h