rippled: rocksdb::Benchmark Class Reference
rocksdb::Benchmark Class Reference
Classes
struct ThreadArg
Public Member Functions
Benchmark ()
~Benchmark ()
void ConstructStrFormatForKey (char *str, int keySize)
unique_ptr< char[]> GenerateKeyFromInt (long long v, const char *suffix="")
void Run ()
Private Types
enum WriteMode { RANDOM, SEQUENTIAL, UNIQUE_RANDOM }
Private Member Functions
void PrintHeader ()
void PrintWarnings ()
void PrintEnvironment ()
void RunBenchmark (int n, Slice name, void(Benchmark::*method)(ThreadState *))
void Crc32c (ThreadState *thread)
void AcquireLoad (ThreadState *thread)
void SnappyCompress (ThreadState *thread)
void SnappyUncompress (ThreadState *thread)
void Open ()
void WriteSeq (ThreadState *thread)
void WriteRandom (ThreadState *thread)
void WriteUniqueRandom (ThreadState *thread)
void writeOrFail (WriteBatch &batch)
void WriteFromStdin (ThreadState *thread)
void DoWrite (ThreadState *thread, WriteMode write_mode)
void ReadSequential (ThreadState *thread)
void ReadReverse (ThreadState *thread)
long MultiGetRandom (ReadOptions &options, int num_keys, Random64 &rand, long long range, const char *suffix)
void ReadRandom (ThreadState *thread)
void PrefixScanRandom (ThreadState *thread)
void ReadMissing (ThreadState *thread)
void ReadHot (ThreadState *thread)
void SeekRandom (ThreadState *thread)
void DoDelete (ThreadState *thread, bool seq)
void DeleteSeq (ThreadState *thread)
void DeleteRandom (ThreadState *thread)
void ReadWhileWriting (ThreadState *thread)
Status PutMany (const WriteOptions &writeoptions, const Slice &key, const Slice &value)
Status DeleteMany (const WriteOptions &writeoptions, const Slice &key)
Status GetMany (const ReadOptions &readoptions, const Slice &key, std::string *value)
void RandomWithVerify (ThreadState *thread)
void ReadRandomWriteRandom (ThreadState *thread)
void ReadRandomWriteRandomMultiGet (ThreadState *thread)
void UpdateRandom (ThreadState *thread)
void AppendRandom (ThreadState *thread)
void MergeRandom (ThreadState *thread)
void Compact (ThreadState *thread)
void PrintStats (const char *key)
void HeapProfile ()
Static Private Member Functions
static void ThreadBody (void *v)
static void WriteToFile (void *arg, const char *buf, int n)
Private Attributes
shared_ptr< Cache > cache_
shared_ptr< Cache > compressed_cache_
const FilterPolicy * filter_policy_
const SliceTransform * prefix_extractor_
DB * db_
long long num_
int value_size_
int key_size_
int entries_per_batch_
WriteOptions write_options_
long long reads_
long long writes_
long long readwrites_
int heap_counter_
char keyFormat_ [100]
Detailed Description
Definition at line 752 of file db_bench.cc.
Member Enumeration Documentation
enum rocksdb::Benchmark::WriteMode private
Enumerator
RANDOM
SEQUENTIAL
UNIQUE_RANDOM
Definition at line 1442 of file db_bench.cc.
                  {
     RANDOM, SEQUENTIAL, UNIQUE_RANDOM
   };
Constructor & Destructor Documentation
rocksdb::Benchmark::Benchmark () inline
Definition at line 920 of file db_bench.cc.
References rocksdb::Env::DeleteFile(), rocksdb::DestroyDB(), rocksdb::Env::GetChildren(), and rocksdb::Slice::starts_with().
   : cache_(FLAGS_cache_size >= 0 ?
            (FLAGS_cache_numshardbits >= 1 ?
             NewLRUCache(FLAGS_cache_size, FLAGS_cache_numshardbits,
                         FLAGS_cache_remove_scan_count_limit) :
             NewLRUCache(FLAGS_cache_size)) : nullptr),
     compressed_cache_(FLAGS_compressed_cache_size >= 0 ?
            (FLAGS_cache_numshardbits >= 1 ?
             NewLRUCache(FLAGS_compressed_cache_size, FLAGS_cache_numshardbits) :
             NewLRUCache(FLAGS_compressed_cache_size)) : nullptr),
     filter_policy_(FLAGS_bloom_bits >= 0
                    ? NewBloomFilterPolicy(FLAGS_bloom_bits)
                    : nullptr),
     prefix_extractor_(NewFixedPrefixTransform(FLAGS_key_size-1)),
     db_(nullptr),
     num_(FLAGS_num),
     value_size_(FLAGS_value_size),
     key_size_(FLAGS_key_size),
     entries_per_batch_(1),
     reads_(FLAGS_reads < 0 ? FLAGS_num : FLAGS_reads),
     writes_(FLAGS_writes < 0 ? FLAGS_num : FLAGS_writes),
     readwrites_((FLAGS_writes < 0  && FLAGS_reads < 0)? FLAGS_num :
                 ((FLAGS_writes > FLAGS_reads) ? FLAGS_writes : FLAGS_reads)
                ),
     heap_counter_(0) {
     std::vector<std::string> files;
     FLAGS_env->GetChildren(FLAGS_db, &files);
     for (unsigned int i = 0; i < files.size(); i++) {
       if (Slice(files[i]).starts_with("heap-")) {
         FLAGS_env->DeleteFile(FLAGS_db + "/" + files[i]);
       }
     }
     if (!FLAGS_use_existing_db) {
       DestroyDB(FLAGS_db, Options());
     }
   }
rocksdb::Benchmark::~Benchmark () inline
Definition at line 957 of file db_bench.cc.
References db_, filter_policy_, and prefix_extractor_.
                {
     delete db_;
     delete filter_policy_;
     delete prefix_extractor_;
   }
Member Function Documentation
void rocksdb::Benchmark::AcquireLoad (ThreadState * thread) inline private
Definition at line 1228 of file db_bench.cc.
References rocksdb::port::AtomicPointer::Acquire_Load(), rocksdb::Stats::AddMessage(), rocksdb::Stats::FinishedSingleOp(), and rocksdb::ThreadState::stats.
Referenced by Run().
{
     int dummy;
     port::AtomicPointer ap(&dummy);
     int count = 0;
     void *ptr = nullptr;
     thread->stats.AddMessage("(each op is 1000 loads)");
     while (count < 100000) {
       for (int i = 0; i < 1000; i++) {
         ptr = ap.Acquire_Load();
       }
       count++;
       thread->stats.FinishedSingleOp(nullptr);
     }
     if (ptr == nullptr) exit(1); // Disable unused variable warning.
   }
void rocksdb::Benchmark::AppendRandom (ThreadState * thread) inline private
Definition at line 2292 of file db_bench.cc.
References rocksdb::Stats::AddMessage(), rocksdb::Slice::data(), db_, rocksdb::Duration::Done(), rocksdb::Stats::FinishedSingleOp(), rocksdb::RandomGenerator::Generate(), GenerateKeyFromInt(), rocksdb::DB::Get(), rocksdb::DB::GetApproximateSizes(), rocksdb::DB::GetSnapshot(), rocksdb::Random64::Next(), ripple::Resource::ok, rocksdb::Status::ok(), rocksdb::DB::Put(), rocksdb::ThreadState::rand, readwrites_, rocksdb::DB::ReleaseSnapshot(), rocksdb::Slice::size(), rocksdb::ReadOptions::snapshot, rocksdb::ThreadState::stats, rocksdb::Status::ToString(), value, value_size_, and write_options_.
Referenced by Run().
{
     ReadOptions options(FLAGS_verify_checksum, true);
     RandomGenerator gen;
     std::string value;
     long found = 0;
     // The number of iterations is the larger of read_ or write_
     Duration duration(FLAGS_duration, readwrites_);
     while (!duration.Done(1)) {
       const long long k = thread->rand.Next() % FLAGS_num;
       unique_ptr<char []> key = GenerateKeyFromInt(k);
       if (FLAGS_use_snapshot) {
         options.snapshot = db_->GetSnapshot();
       }
       if (FLAGS_get_approx) {
         char key2[100];
         snprintf(key2, sizeof(key2), "%016lld", k + 1);
         Slice skey2(key2);
         Slice skey(key2);
         Range range(skey, skey2);
         uint64_t sizes;
         db_->GetApproximateSizes(&range, 1, &sizes);
       }
       // Get the existing value
       if (db_->Get(options, key.get(), &value).ok()) {
         found++;
       } else {
         // If not existing, then just assume an empty string of data
         value.clear();
       }
       if (FLAGS_use_snapshot) {
         db_->ReleaseSnapshot(options.snapshot);
       }
       // Update the value (by appending data)
       Slice operand = gen.Generate(value_size_);
       if (value.size() > 0) {
         // Use a delimeter to match the semantics for StringAppendOperator
         value.append(1,',');
       }
       value.append(operand.data(), operand.size());
       // Write back to the database
       Status s = db_->Put(write_options_, key.get(), value);
       if (!s.ok()) {
         fprintf(stderr, "put error: %s\n", s.ToString().c_str());
         exit(1);
       }
       thread->stats.FinishedSingleOp(db_);
     }
     char msg[100];
     snprintf(msg, sizeof(msg), "( updates:%lld found:%ld)", readwrites_, found);
     thread->stats.AddMessage(msg);
   }
void rocksdb::Benchmark::Compact (ThreadState * thread) inline private
Definition at line 2383 of file db_bench.cc.
References rocksdb::DB::CompactRange(), and db_.
Referenced by Run().
{
     db_->CompactRange(nullptr, nullptr);
   }
void rocksdb::Benchmark::ConstructStrFormatForKey (char * str, int keySize) inline
Definition at line 964 of file db_bench.cc.
Referenced by Run().
{
     str[0] = '%';
     str[1] = '0';
     sprintf(str+2, "%dlld%s", keySize, "%s");
   }
void rocksdb::Benchmark::Crc32c (ThreadState * thread) inline private
Definition at line 1209 of file db_bench.cc.
References rocksdb::Stats::AddBytes(), rocksdb::Stats::AddMessage(), rocksdb::Stats::FinishedSingleOp(), rocksdb::ThreadState::stats, and rocksdb::crc32c::Value().
Referenced by Run().
{
     // Checksum about 500MB of data total
     const int size = 4096;
     const char* label = "(4K per op)";
     std::string data(size, 'x');
     int64_t bytes = 0;
     uint32_t crc = 0;
     while (bytes < 500 * 1048576) {
       crc = crc32c::Value(data.data(), size);
       thread->stats.FinishedSingleOp(nullptr);
       bytes += size;
     }
     // Print so result is not dead
     fprintf(stderr, "... crc=0x%x\r", static_cast<unsigned int>(crc));
     thread->stats.AddBytes(bytes);
     thread->stats.AddMessage(label);
   }
Status rocksdb::Benchmark::DeleteMany (const WriteOptions & writeoptions, const Slice & key) inline private
Definition at line 1956 of file db_bench.cc.
References db_, rocksdb::WriteBatch::Delete(), rocksdb::Slice::ToString(), and rocksdb::DB::Write().
Referenced by RandomWithVerify().
{
     std::string suffixes[3] = {"1", "2", "0"};
     std::string keys[3];
     WriteBatch batch;
     Status s;
     for (int i = 0; i < 3; i++) {
       keys[i] = key.ToString() + suffixes[i];
       batch.Delete(keys[i]);
     }
     s = db_->Write(writeoptions, &batch);
     return s;
   }
void rocksdb::Benchmark::DeleteRandom (ThreadState * thread) inline private
Definition at line 1876 of file db_bench.cc.
References DoDelete().
Referenced by Run().
{
     DoDelete(thread, false);
   }
void rocksdb::Benchmark::DeleteSeq (ThreadState * thread) inline private
Definition at line 1872 of file db_bench.cc.
References DoDelete().
Referenced by Run().
{
     DoDelete(thread, true);
   }
void rocksdb::Benchmark::DoDelete (ThreadState * thread, bool seq) inline private
Definition at line 1850 of file db_bench.cc.
References rocksdb::WriteBatch::Clear(), db_, rocksdb::WriteBatch::Delete(), rocksdb::Duration::Done(), entries_per_batch_, rocksdb::Stats::FinishedSingleOp(), GenerateKeyFromInt(), rocksdb::Random64::Next(), num_, rocksdb::Status::ok(), rocksdb::ThreadState::rand, rocksdb::ThreadState::stats, rocksdb::Status::ToString(), rocksdb::DB::Write(), and write_options_.
Referenced by DeleteRandom(), and DeleteSeq().
{
     WriteBatch batch;
     Status s;
     Duration duration(seq ? 0 : FLAGS_duration, num_);
     long i = 0;
     while (!duration.Done(entries_per_batch_)) {
       batch.Clear();
       for (int j = 0; j < entries_per_batch_; j++) {
         const long long k = seq ? i+j : (thread->rand.Next() % FLAGS_num);
         unique_ptr<char []> key = GenerateKeyFromInt(k);
         batch.Delete(key.get());
         thread->stats.FinishedSingleOp(db_);
       }
       s = db_->Write(write_options_, &batch);
       if (!s.ok()) {
         fprintf(stderr, "del error: %s\n", s.ToString().c_str());
         exit(1);
       }
       ++i;
     }
   }
void rocksdb::Benchmark::DoWrite (ThreadState * thread, WriteMode write_mode) inline private
Definition at line 1506 of file db_bench.cc.
References rocksdb::Stats::AddBytes(), rocksdb::Stats::AddMessage(), rocksdb::WriteBatch::Clear(), db_, rocksdb::Duration::Done(), entries_per_batch_, rocksdb::Stats::FinishedSingleOp(), rocksdb::RandomGenerator::Generate(), GenerateKeyFromInt(), rocksdb::Random64::Next(), num_, rocksdb::Status::ok(), rocksdb::WriteBatch::Put(), rocksdb::ThreadState::rand, RANDOM, SEQUENTIAL, rocksdb::ThreadState::stats, rocksdb::Status::ToString(), UNIQUE_RANDOM, value_size_, rocksdb::DB::Write(), write_options_, and writes_.
Referenced by WriteRandom(), WriteSeq(), and WriteUniqueRandom().
{
     const int test_duration = write_mode == RANDOM ? FLAGS_duration : 0;
     const int num_ops = writes_ == 0 ? num_ : writes_ ;
     Duration duration(test_duration, num_ops);
     unique_ptr<BitSet> bit_set;
     if (write_mode == UNIQUE_RANDOM) {
       bit_set.reset(new BitSet(num_ops));
     }
     if (num_ != FLAGS_num) {
       char msg[100];
       snprintf(msg, sizeof(msg), "(%lld ops)", num_);
       thread->stats.AddMessage(msg);
     }
     RandomGenerator gen;
     WriteBatch batch;
     Status s;
     int64_t bytes = 0;
     int i = 0;
     while (!duration.Done(entries_per_batch_)) {
       batch.Clear();
       for (int j = 0; j < entries_per_batch_; j++) {
         long long k = 0;
         switch(write_mode) {
           case SEQUENTIAL:
             k = i +j;
             break;
           case RANDOM:
             k = thread->rand.Next() % FLAGS_num;
             break;
           case UNIQUE_RANDOM:
             {
               const long long t = thread->rand.Next() % FLAGS_num;
               if (!bit_set->test(t)) {
                 // best case
                 k = t;
               } else {
                 bool found = false;
                 // look forward
                 for (size_t i = t + 1; i < bit_set->size(); ++i) {
                   if (!bit_set->test(i)) {
                     found = true;
                     k = i;
                     break;
                   }
                 }
                 if (!found) {
                   for (size_t i = t; i-- > 0;) {
                     if (!bit_set->test(i)) {
                       found = true;
                       k = i;
                       break;
                     }
                   }
                 }
               }
               bit_set->set(k);
               break;
             }
         };
         unique_ptr<char []> key = GenerateKeyFromInt(k);
         batch.Put(key.get(), gen.Generate(value_size_));
         bytes += value_size_ + strlen(key.get());
         thread->stats.FinishedSingleOp(db_);
       }
       s = db_->Write(write_options_, &batch);
       if (!s.ok()) {
         fprintf(stderr, "put error: %s\n", s.ToString().c_str());
         exit(1);
       }
       i += entries_per_batch_;
     }
     thread->stats.AddBytes(bytes);
   }
unique_ptr<char []> rocksdb::Benchmark::GenerateKeyFromInt (long long v, const char * suffix = "") inline
Definition at line 970 of file db_bench.cc.
References keyFormat_, and kMaxKeySize.
Referenced by AppendRandom(), DoDelete(), DoWrite(), MergeRandom(), MultiGetRandom(), PrefixScanRandom(), RandomWithVerify(), ReadHot(), ReadMissing(), ReadRandom(), ReadRandomWriteRandom(), ReadRandomWriteRandomMultiGet(), ReadWhileWriting(), SeekRandom(), and UpdateRandom().
{
     unique_ptr<char []> keyInStr(new char[kMaxKeySize]);
     snprintf(keyInStr.get(), kMaxKeySize, keyFormat_, v, suffix);
     return keyInStr;
   }
Status rocksdb::Benchmark::GetMany (const ReadOptions & readoptions, const Slice & key, std::string * value) inline private
Definition at line 1975 of file db_bench.cc.
References db_, rocksdb::DB::Get(), rocksdb::DB::GetSnapshot(), rocksdb::Status::IsNotFound(), rocksdb::Status::ok(), rocksdb::DB::ReleaseSnapshot(), rocksdb::ReadOptions::snapshot, rocksdb::Slice::ToString(), rocksdb::Status::ToString(), and value.
Referenced by RandomWithVerify().
{
     std::string suffixes[3] = {"0", "1", "2"};
     std::string keys[3];
     Slice key_slices[3];
     std::string values[3];
     ReadOptions readoptionscopy = readoptions;
     readoptionscopy.snapshot = db_->GetSnapshot();
     Status s;
     for (int i = 0; i < 3; i++) {
       keys[i] = key.ToString() + suffixes[i];
       key_slices[i] = keys[i];
       s = db_->Get(readoptionscopy, key_slices[i], value);
       if (!s.ok() && !s.IsNotFound()) {
         fprintf(stderr, "get error: %s\n", s.ToString().c_str());
         values[i] = "";
         // we continue after error rather than exiting so that we can
         // find more errors if any
       } else if (s.IsNotFound()) {
         values[i] = "";
       } else {
         values[i] = *value;
       }
     }
     db_->ReleaseSnapshot(readoptionscopy.snapshot);
     if ((values[0] != values[1]) || (values[1] != values[2])) {
       fprintf(stderr, "inconsistent values for key %s: %s, %s, %s\n",
               key.ToString().c_str(), values[0].c_str(), values[1].c_str(),
               values[2].c_str());
       // we continue after error rather than exiting so that we can
       // find more errors if any
     }
     return s;
   }
void rocksdb::Benchmark::HeapProfile () inline private
Definition at line 2399 of file db_bench.cc.
References rocksdb::Env::DeleteFile(), rocksdb::port::GetHeapProfile(), heap_counter_, rocksdb::Env::NewWritableFile(), ripple::Resource::ok, rocksdb::Status::ok(), rocksdb::Status::ToString(), and WriteToFile().
Referenced by Run().
                      {
     char fname[100];
     EnvOptions soptions;
     snprintf(fname, sizeof(fname), "%s/heap-%04d", FLAGS_db.c_str(),
              ++heap_counter_);
     unique_ptr<WritableFile> file;
     Status s = FLAGS_env->NewWritableFile(fname, &file, soptions);
     if (!s.ok()) {
       fprintf(stderr, "%s\n", s.ToString().c_str());
       return;
     }
     bool ok = port::GetHeapProfile(WriteToFile, file.get());
     if (!ok) {
       fprintf(stderr, "heap profiling not supported\n");
       FLAGS_env->DeleteFile(fname);
     }
   }
void rocksdb::Benchmark::MergeRandom (ThreadState * thread) inline private
Definition at line 2358 of file db_bench.cc.
References rocksdb::Stats::AddMessage(), db_, rocksdb::Duration::Done(), rocksdb::Stats::FinishedSingleOp(), rocksdb::RandomGenerator::Generate(), GenerateKeyFromInt(), rocksdb::DB::Merge(), rocksdb::Random64::Next(), rocksdb::Status::ok(), rocksdb::ThreadState::rand, readwrites_, rocksdb::ThreadState::stats, rocksdb::Status::ToString(), value_size_, and write_options_.
Referenced by Run().
{
     RandomGenerator gen;
     // The number of iterations is the larger of read_ or write_
     Duration duration(FLAGS_duration, readwrites_);
     while (!duration.Done(1)) {
       const long long k = thread->rand.Next() % FLAGS_num;
       unique_ptr<char []> key = GenerateKeyFromInt(k);
       Status s = db_->Merge(write_options_, key.get(),
                             gen.Generate(value_size_));
       if (!s.ok()) {
         fprintf(stderr, "merge error: %s\n", s.ToString().c_str());
         exit(1);
       }
       thread->stats.FinishedSingleOp(db_);
     }
     // Print some statistics
     char msg[100];
     snprintf(msg, sizeof(msg), "( updates:%lld)", readwrites_);
     thread->stats.AddMessage(msg);
   }
long rocksdb::Benchmark::MultiGetRandom (ReadOptions & options, int num_keys, Random64 & rand, long long range, const char * suffix) inline private
Definition at line 1611 of file db_bench.cc.
References db_, GenerateKeyFromInt(), rocksdb::DB::GetSnapshot(), rocksdb::DB::MultiGet(), rocksdb::Random64::Next(), ripple::Resource::ok, rocksdb::DB::ReleaseSnapshot(), and rocksdb::ReadOptions::snapshot.
Referenced by ReadHot(), ReadMissing(), ReadRandom(), and ReadRandomWriteRandomMultiGet().
{
     assert(num_keys > 0);
     std::vector<Slice> keys(num_keys);
     std::vector<std::string> values(num_keys);
     std::vector<unique_ptr<char []> > gen_keys(num_keys);
     int i;
     long long k;
     // Fill the keys vector
     for(i=0; i<num_keys; ++i) {
       k = rand.Next() % range;
       gen_keys[i] = GenerateKeyFromInt(k,suffix);
       keys[i] = gen_keys[i].get();
     }
     if (FLAGS_use_snapshot) {
       options.snapshot = db_->GetSnapshot();
     }
     // Apply the operation
     std::vector<Status> statuses = db_->MultiGet(options, keys, &values);
     assert((long)statuses.size() == num_keys);
     assert((long)keys.size() == num_keys);  // Should always be the case.
     assert((long)values.size() == num_keys);
     if (FLAGS_use_snapshot) {
       db_->ReleaseSnapshot(options.snapshot);
       options.snapshot = nullptr;
     }
     // Count number found
     long found = 0;
     for(i=0; i<num_keys; ++i) {
       if (statuses[i].ok()){
         ++found;
       } else if (FLAGS_warn_missing_keys == true) {
         // Key not found, or error.
         fprintf(stderr, "get error: %s\n", statuses[i].ToString().c_str());
       }
     }
     return found;
   }
void rocksdb::Benchmark::Open () inline private
Definition at line 1293 of file db_bench.cc.
References rocksdb::Options::access_hint_on_compaction_start, rocksdb::Options::advise_random_on_open, rocksdb::Options::allow_mmap_reads, rocksdb::Options::allow_mmap_writes, rocksdb::Options::allow_os_buffer, rocksdb::Options::block_cache, rocksdb::Options::block_cache_compressed, rocksdb::Options::block_size, rocksdb::Options::bytes_per_sync, cache_, rocksdb::Options::compaction_options_universal, rocksdb::Options::compaction_style, compressed_cache_, rocksdb::Options::compression, rocksdb::Options::compression_per_level, rocksdb::Options::create_if_missing, rocksdb::MergeOperators::CreateFromStringId(), db_, dbstats, rocksdb::Options::delete_obsolete_files_period_micros, rocksdb::Options::disable_auto_compactions, rocksdb::Options::disable_seek_compaction, rocksdb::Options::disableDataSync, rocksdb::Options::env, rocksdb::Options::filter_deletes, rocksdb::Options::filter_policy, filter_policy_, FLAGS_compaction_fadvice_e, FLAGS_compaction_style_e, FLAGS_compression_type_e, FLAGS_env, FLAGS_max_bytes_for_level_multiplier_additional_v, FLAGS_max_write_buffer_number, FLAGS_min_write_buffer_number_to_merge, FLAGS_write_buffer_size, rocksdb::Options::hard_rate_limit, rocksdb::kNoCompression, kPrefixHash, kSkipList, kUnsorted, kVectorRep, rocksdb::Options::level0_file_num_compaction_trigger, rocksdb::Options::level0_slowdown_writes_trigger, rocksdb::Options::level0_stop_writes_trigger, rocksdb::Options::max_background_compactions, rocksdb::Options::max_bytes_for_level_base, rocksdb::Options::max_bytes_for_level_multiplier, rocksdb::Options::max_bytes_for_level_multiplier_additional, rocksdb::Options::max_grandparent_overlap_factor, rocksdb::CompactionOptionsUniversal::max_merge_width, rocksdb::Options::max_open_files, rocksdb::CompactionOptionsUniversal::max_size_amplification_percent, rocksdb::Options::max_write_buffer_number, rocksdb::Options::memtable_factory, rocksdb::Options::merge_operator, rocksdb::CompactionOptionsUniversal::min_merge_width, rocksdb::Options::min_write_buffer_number_to_merge, rocksdb::NewFixedPrefixTransform(), rocksdb::Options::no_block_cache, rocksdb::Options::num_levels, rocksdb::Status::ok(), rocksdb::DB::Open(), rocksdb::DB::OpenForReadOnly(), rocksdb::Options::prefix_extractor, prefix_extractor_, rocksdb::Options::rate_limit_delay_max_milliseconds, rocksdb::CompactionOptionsUniversal::size_ratio, rocksdb::Options::soft_rate_limit, rocksdb::Options::source_compaction_factor, rocksdb::Options::statistics, rocksdb::Options::table_cache_numshardbits, rocksdb::Options::target_file_size_base, rocksdb::Options::target_file_size_multiplier, rocksdb::Status::ToString(), rocksdb::Options::use_adaptive_mutex, rocksdb::Options::use_fsync, rocksdb::Options::WAL_size_limit_MB, rocksdb::Options::WAL_ttl_seconds, and rocksdb::Options::write_buffer_size.
Referenced by Run().
               {
     assert(db_ == nullptr);
     Options options;
     options.create_if_missing = !FLAGS_use_existing_db;
     options.block_cache = cache_;
     options.block_cache_compressed = compressed_cache_;
     if (cache_ == nullptr) {
       options.no_block_cache = true;
     }
     options.write_buffer_size = FLAGS_write_buffer_size;
     options.max_write_buffer_number = FLAGS_max_write_buffer_number;
     options.min_write_buffer_number_to_merge =
       FLAGS_min_write_buffer_number_to_merge;
     options.max_background_compactions = FLAGS_max_background_compactions;
     options.compaction_style = FLAGS_compaction_style_e;
     options.block_size = FLAGS_block_size;
     options.filter_policy = filter_policy_;
     options.prefix_extractor = FLAGS_use_prefix_blooms ? prefix_extractor_
                                                        : nullptr;
     options.max_open_files = FLAGS_open_files;
     options.statistics = dbstats;
     options.env = FLAGS_env;
     options.disableDataSync = FLAGS_disable_data_sync;
     options.use_fsync = FLAGS_use_fsync;
     options.num_levels = FLAGS_num_levels;
     options.target_file_size_base = FLAGS_target_file_size_base;
     options.target_file_size_multiplier = FLAGS_target_file_size_multiplier;
     options.max_bytes_for_level_base = FLAGS_max_bytes_for_level_base;
     options.max_bytes_for_level_multiplier =
         FLAGS_max_bytes_for_level_multiplier;
     options.filter_deletes = FLAGS_filter_deletes;
     if ((FLAGS_prefix_size == 0) == (FLAGS_rep_factory == kPrefixHash)) {
       fprintf(stderr,
             "prefix_size should be non-zero iff memtablerep == prefix_hash\n");
       exit(1);
     }
     switch (FLAGS_rep_factory) {
       case kPrefixHash:
         options.memtable_factory.reset(
           new PrefixHashRepFactory(NewFixedPrefixTransform(FLAGS_prefix_size))
         );
         break;
       case kUnsorted:
         options.memtable_factory.reset(
           new UnsortedRepFactory
         );
         break;
       case kSkipList:
         // no need to do anything
         break;
       case kVectorRep:
         options.memtable_factory.reset(
           new VectorRepFactory
         );
         break;
     }
     if (FLAGS_max_bytes_for_level_multiplier_additional_v.size() > 0) {
       if (FLAGS_max_bytes_for_level_multiplier_additional_v.size() !=
           (unsigned int)FLAGS_num_levels) {
         fprintf(stderr, "Insufficient number of fanouts specified %d\n",
                 (int)FLAGS_max_bytes_for_level_multiplier_additional_v.size());
         exit(1);
       }
       options.max_bytes_for_level_multiplier_additional =
         FLAGS_max_bytes_for_level_multiplier_additional_v;
     }
     options.level0_stop_writes_trigger = FLAGS_level0_stop_writes_trigger;
     options.level0_file_num_compaction_trigger =
         FLAGS_level0_file_num_compaction_trigger;
     options.level0_slowdown_writes_trigger =
       FLAGS_level0_slowdown_writes_trigger;
     options.compression = FLAGS_compression_type_e;
     options.WAL_ttl_seconds = FLAGS_wal_ttl_seconds;
     options.WAL_size_limit_MB = FLAGS_wal_size_limit_MB;
     if (FLAGS_min_level_to_compress >= 0) {
       assert(FLAGS_min_level_to_compress <= FLAGS_num_levels);
       options.compression_per_level.resize(FLAGS_num_levels);
       for (int i = 0; i < FLAGS_min_level_to_compress; i++) {
         options.compression_per_level[i] = kNoCompression;
       }
       for (int i = FLAGS_min_level_to_compress;
            i < FLAGS_num_levels; i++) {
         options.compression_per_level[i] = FLAGS_compression_type_e;
       }
     }
     options.disable_seek_compaction = FLAGS_disable_seek_compaction;
     options.delete_obsolete_files_period_micros =
       FLAGS_delete_obsolete_files_period_micros;
     options.soft_rate_limit = FLAGS_soft_rate_limit;
     options.hard_rate_limit = FLAGS_hard_rate_limit;
     options.rate_limit_delay_max_milliseconds =
       FLAGS_rate_limit_delay_max_milliseconds;
     options.table_cache_numshardbits = FLAGS_table_cache_numshardbits;
     options.max_grandparent_overlap_factor =
       FLAGS_max_grandparent_overlap_factor;
     options.disable_auto_compactions = FLAGS_disable_auto_compactions;
     options.source_compaction_factor = FLAGS_source_compaction_factor;
     // fill storage options
     options.allow_os_buffer = FLAGS_bufferedio;
     options.allow_mmap_reads = FLAGS_mmap_read;
     options.allow_mmap_writes = FLAGS_mmap_write;
     options.advise_random_on_open = FLAGS_advise_random_on_open;
     options.access_hint_on_compaction_start = FLAGS_compaction_fadvice_e;
     options.use_adaptive_mutex = FLAGS_use_adaptive_mutex;
     options.bytes_per_sync = FLAGS_bytes_per_sync;
     // merge operator options
     options.merge_operator = MergeOperators::CreateFromStringId(
         FLAGS_merge_operator);
     if (options.merge_operator == nullptr && !FLAGS_merge_operator.empty()) {
       fprintf(stderr, "invalid merge operator: %s\n",
               FLAGS_merge_operator.c_str());
       exit(1);
     }
     // set universal style compaction configurations, if applicable
     if (FLAGS_universal_size_ratio != 0) {
       options.compaction_options_universal.size_ratio =
         FLAGS_universal_size_ratio;
     }
     if (FLAGS_universal_min_merge_width != 0) {
       options.compaction_options_universal.min_merge_width =
         FLAGS_universal_min_merge_width;
     }
     if (FLAGS_universal_max_merge_width != 0) {
       options.compaction_options_universal.max_merge_width =
         FLAGS_universal_max_merge_width;
     }
     if (FLAGS_universal_max_size_amplification_percent != 0) {
       options.compaction_options_universal.max_size_amplification_percent =
         FLAGS_universal_max_size_amplification_percent;
     }
     Status s;
     if(FLAGS_readonly) {
       s = DB::OpenForReadOnly(options, FLAGS_db, &db_);
     } else {
       s = DB::Open(options, FLAGS_db, &db_);
     }
     if (!s.ok()) {
       fprintf(stderr, "open error: %s\n", s.ToString().c_str());
       exit(1);
     }
     if (FLAGS_min_level_to_compress >= 0) {
       options.compression_per_level.clear();
     }
   }
void rocksdb::Benchmark::PrefixScanRandom (ThreadState * thread) inline private
Definition at line 1724 of file db_bench.cc.
References rocksdb::Stats::AddMessage(), db_, rocksdb::Duration::Done(), rocksdb::Stats::FinishedSingleOp(), GenerateKeyFromInt(), rocksdb::Iterator::key(), rocksdb::DB::NewIterator(), rocksdb::Iterator::Next(), rocksdb::Random64::Next(), std::chrono::prefix, rocksdb::ReadOptions::prefix, prefix_extractor_, rocksdb::ThreadState::rand, reads_, rocksdb::Iterator::Seek(), rocksdb::Slice::starts_with(), rocksdb::ThreadState::stats, rocksdb::SliceTransform::Transform(), rocksdb::Iterator::Valid(), and value.
Referenced by Run().
{
     if (FLAGS_use_prefix_api) {
       assert(FLAGS_use_prefix_blooms);
       assert(FLAGS_bloom_bits >= 1);
     }
     ReadOptions options(FLAGS_verify_checksum, true);
     Duration duration(FLAGS_duration, reads_);
     long long found = 0;
     while (!duration.Done(1)) {
       std::string value;
       const int k = thread->rand.Next() % FLAGS_num;
       unique_ptr<char []> key = GenerateKeyFromInt(k);
       Slice skey(key.get());
       Slice prefix = prefix_extractor_->Transform(skey);
       options.prefix = FLAGS_use_prefix_api ? &prefix : nullptr;
       Iterator* iter = db_->NewIterator(options);
       for (iter->Seek(skey);
            iter->Valid() && iter->key().starts_with(prefix);
            iter->Next()) {
         found++;
       }
       delete iter;
       thread->stats.FinishedSingleOp(db_);
     }
     char msg[100];
     snprintf(msg, sizeof(msg), "(%lld of %lld found)", found, reads_);
     thread->stats.AddMessage(msg);
   }
void rocksdb::Benchmark::PrintEnvironment () inline private
Definition at line 884 of file db_bench.cc.
References rocksdb::kMajorVersion, rocksdb::kMinorVersion, and rocksdb::Slice::ToString().
Referenced by PrintHeader().
{
     fprintf(stderr, "LevelDB:    version %d.%d\n",
             kMajorVersion, kMinorVersion);
 #if defined(__linux)
     time_t now = time(nullptr);
     fprintf(stderr, "Date:       %s", ctime(&now));  // ctime() adds newline
     FILE* cpuinfo = fopen("/proc/cpuinfo", "r");
     if (cpuinfo != nullptr) {
       char line[1000];
       int num_cpus = 0;
       std::string cpu_type;
       std::string cache_size;
       while (fgets(line, sizeof(line), cpuinfo) != nullptr) {
         const char* sep = strchr(line, ':');
         if (sep == nullptr) {
           continue;
         }
         Slice key = TrimSpace(Slice(line, sep - 1 - line));
         Slice val = TrimSpace(Slice(sep + 1));
         if (key == "model name") {
           ++num_cpus;
           cpu_type = val.ToString();
         } else if (key == "cache size") {
           cache_size = val.ToString();
         }
       }
       fclose(cpuinfo);
       fprintf(stderr, "CPU:        %d * %s\n", num_cpus, cpu_type.c_str());
       fprintf(stderr, "CPUCache:   %s\n", cache_size.c_str());
     }
 #endif
   }
void rocksdb::Benchmark::PrintHeader () inline private
Definition at line 769 of file db_bench.cc.
References rocksdb::kBZip2Compression, rocksdb::kNoCompression, kPrefixHash, kSkipList, rocksdb::kSnappyCompression, kUnsorted, kVectorRep, rocksdb::kZlibCompression, num_, PrintEnvironment(), and PrintWarnings().
Referenced by Run().
                      {
     PrintEnvironment();
     fprintf(stdout, "Keys:       %d bytes each\n", FLAGS_key_size);
     fprintf(stdout, "Values:     %d bytes each (%d bytes after compression)\n",
             FLAGS_value_size,
             static_cast<int>(FLAGS_value_size * FLAGS_compression_ratio + 0.5));
     fprintf(stdout, "Entries:    %lld\n", num_);
     fprintf(stdout, "RawSize:    %.1f MB (estimated)\n",
             ((static_cast<int64_t>(FLAGS_key_size + FLAGS_value_size) * num_)
              / 1048576.0));
     fprintf(stdout, "FileSize:   %.1f MB (estimated)\n",
             (((FLAGS_key_size + FLAGS_value_size * FLAGS_compression_ratio)
               * num_)
              / 1048576.0));
     fprintf(stdout, "Write rate limit: %d\n", FLAGS_writes_per_second);
     switch (FLAGS_compression_type_e) {
       case rocksdb::kNoCompression:
         fprintf(stdout, "Compression: none\n");
         break;
       case rocksdb::kSnappyCompression:
         fprintf(stdout, "Compression: snappy\n");
         break;
       case rocksdb::kZlibCompression:
         fprintf(stdout, "Compression: zlib\n");
         break;
       case rocksdb::kBZip2Compression:
         fprintf(stdout, "Compression: bzip2\n");
         break;
     }
     switch (FLAGS_rep_factory) {
       case kPrefixHash:
         fprintf(stdout, "Memtablerep: prefix_hash\n");
         break;
       case kSkipList:
         fprintf(stdout, "Memtablerep: skip_list\n");
         break;
       case kUnsorted:
         fprintf(stdout, "Memtablerep: unsorted\n");
         break;
       case kVectorRep:
         fprintf(stdout, "Memtablerep: vector\n");
         break;
     }
     PrintWarnings();
     fprintf(stdout, "------------------------------------------------\n");
   }
void rocksdb::Benchmark::PrintStats (const char * key) inline private
Definition at line 2387 of file db_bench.cc.
References db_, rocksdb::DB::GetProperty(), and stats.
Referenced by Run().
{
     std::string stats;
     if (!db_->GetProperty(key, &stats)) {
       stats = "(failed)";
     }
     fprintf(stdout, "\n%s\n", stats.c_str());
   }
void rocksdb::Benchmark::PrintWarnings () inline private
Definition at line 818 of file db_bench.cc.
References rocksdb::port::BZip2_Compress(), rocksdb::kBZip2Compression, rocksdb::kNoCompression, rocksdb::kSnappyCompression, rocksdb::kZlibCompression, name, rocksdb::port::Snappy_Compress(), and rocksdb::port::Zlib_Compress().
Referenced by PrintHeader().
{
 #if defined(__GNUC__) && !defined(__OPTIMIZE__)
     fprintf(stdout,
             "WARNING: Optimization is disabled: benchmarks unnecessarily slow\n"
             );
 #endif
 #ifndef NDEBUG
     fprintf(stdout,
             "WARNING: Assertions are enabled; benchmarks unnecessarily slow\n");
 #endif
     if (FLAGS_compression_type_e != rocksdb::kNoCompression) {
       // The test string should not be too small.
       const int len = FLAGS_block_size;
       char* text = (char*) malloc(len+1);
       bool result = true;
       const char* name = nullptr;
       std::string compressed;
       memset(text, (int) 'y', len);
       text[len] = '\0';
       switch (FLAGS_compression_type_e) {
         case kSnappyCompression:
           result = port::Snappy_Compress(Options().compression_opts, text,
                                          strlen(text), &compressed);
           name = "Snappy";
           break;
         case kZlibCompression:
           result = port::Zlib_Compress(Options().compression_opts, text,
                                        strlen(text), &compressed);
           name = "Zlib";
           break;
         case kBZip2Compression:
           result = port::BZip2_Compress(Options().compression_opts, text,
                                         strlen(text), &compressed);
           name = "BZip2";
           break;
         case kNoCompression:
           assert(false); // cannot happen
           break;
       }
       if (!result) {
         fprintf(stdout, "WARNING: %s compression is not enabled\n", name);
       } else if (name && compressed.size() >= strlen(text)) {
         fprintf(stdout, "WARNING: %s compression is not effective\n", name);
       }
       free(text);
     }
   }
Status rocksdb::Benchmark::PutMany (const WriteOptions & writeoptions, const Slice & key, const Slice & value) inline private
Definition at line 1937 of file db_bench.cc.
References db_, rocksdb::WriteBatch::Put(), rocksdb::Slice::ToString(), and rocksdb::DB::Write().
Referenced by RandomWithVerify().
{
     std::string suffixes[3] = {"2", "1", "0"};
     std::string keys[3];
     WriteBatch batch;
     Status s;
     for (int i = 0; i < 3; i++) {
       keys[i] = key.ToString() + suffixes[i];
       batch.Put(keys[i], value);
     }
     s = db_->Write(writeoptions, &batch);
     return s;
   }
void rocksdb::Benchmark::RandomWithVerify (ThreadState * thread) inline private
Definition at line 2019 of file db_bench.cc.
References rocksdb::Stats::AddMessage(), db_, DeleteMany(), rocksdb::Stats::FinishedSingleOp(), rocksdb::RandomGenerator::Generate(), GenerateKeyFromInt(), GetMany(), rocksdb::Status::IsNotFound(), rocksdb::Random64::Next(), rocksdb::Status::ok(), PutMany(), rocksdb::ThreadState::rand, readwrites_, rocksdb::ThreadState::stats, rocksdb::Status::ToString(), value, value_size_, and write_options_.
Referenced by Run().
{
     ReadOptions options(FLAGS_verify_checksum, true);
     RandomGenerator gen;
     std::string value;
     long long found = 0;
     int get_weight = 0;
     int put_weight = 0;
     int delete_weight = 0;
     long long gets_done = 0;
     long long puts_done = 0;
     long long deletes_done = 0;
     // the number of iterations is the larger of read_ or write_
     for (long long i = 0; i < readwrites_; i++) {
       const long long k = thread->rand.Next() % (FLAGS_numdistinct);
       unique_ptr<char []> key = GenerateKeyFromInt(k);
       if (get_weight == 0 && put_weight == 0 && delete_weight == 0) {
         // one batch completed, reinitialize for next batch
         get_weight = FLAGS_readwritepercent;
         delete_weight = FLAGS_deletepercent;
         put_weight = 100 - get_weight - delete_weight;
       }
       if (get_weight > 0) {
         // do all the gets first
         Status s = GetMany(options, key.get(), &value);
         if (!s.ok() && !s.IsNotFound()) {
           fprintf(stderr, "getmany error: %s\n", s.ToString().c_str());
           // we continue after error rather than exiting so that we can
           // find more errors if any
         } else if (!s.IsNotFound()) {
           found++;
         }
         get_weight--;
         gets_done++;
       } else if (put_weight > 0) {
         // then do all the corresponding number of puts
         // for all the gets we have done earlier
         Status s = PutMany(write_options_, key.get(),
                            gen.Generate(value_size_));
         if (!s.ok()) {
           fprintf(stderr, "putmany error: %s\n", s.ToString().c_str());
           exit(1);
         }
         put_weight--;
         puts_done++;
       } else if (delete_weight > 0) {
         Status s = DeleteMany(write_options_, key.get());
         if (!s.ok()) {
           fprintf(stderr, "deletemany error: %s\n", s.ToString().c_str());
           exit(1);
         }
         delete_weight--;
         deletes_done++;
       }
       thread->stats.FinishedSingleOp(db_);
     }
     char msg[100];
     snprintf(msg, sizeof(msg),
              "( get:%lld put:%lld del:%lld total:%lld found:%lld)",
              gets_done, puts_done, deletes_done, readwrites_, found);
     thread->stats.AddMessage(msg);
   }
void rocksdb::Benchmark::ReadHot (ThreadState * thread) inline private
Definition at line 1797 of file db_bench.cc.
References rocksdb::Stats::AddMessage(), db_, rocksdb::Duration::Done(), rocksdb::Stats::FinishedSingleOp(), GenerateKeyFromInt(), rocksdb::DB::Get(), ripple::min(), MultiGetRandom(), rocksdb::Random64::Next(), ripple::Resource::ok, rocksdb::ThreadState::rand, reads_, rocksdb::ThreadState::stats, and value.
Referenced by Run().
{
     Duration duration(FLAGS_duration, reads_);
     ReadOptions options(FLAGS_verify_checksum, true);
     const long long range = (FLAGS_num + 99) / 100;
     long long found = 0;
     if (FLAGS_use_multiget) {
       const long long kpg = FLAGS_keys_per_multiget;  // keys per multiget group
       long long keys_left = reads_;
       // Recalculate number of keys per group, and call MultiGet until done
       long num_keys;
       while(num_keys = std::min(keys_left, kpg), !duration.Done(num_keys)) {
         found += MultiGetRandom(options, num_keys, thread->rand, range, "");
         thread->stats.FinishedSingleOp(db_);
         keys_left -= num_keys;
       }
     } else {
       std::string value;
       while (!duration.Done(1)) {
         const long long k = thread->rand.Next() % range;
         unique_ptr<char []> key = GenerateKeyFromInt(k);
         if (db_->Get(options, key.get(), &value).ok()){
           ++found;
         }
         thread->stats.FinishedSingleOp(db_);
       }
     }
     char msg[100];
     snprintf(msg, sizeof(msg), "(%lld of %lld found)", found, reads_);
     thread->stats.AddMessage(msg);
   }
void rocksdb::Benchmark::ReadMissing (ThreadState * thread) inline private
Definition at line 1759 of file db_bench.cc.
References db_, rocksdb::Duration::Done(), rocksdb::Stats::FinishedSingleOp(), GenerateKeyFromInt(), rocksdb::DB::Get(), rocksdb::Status::IsNotFound(), ripple::min(), MultiGetRandom(), rocksdb::Random64::Next(), rocksdb::Status::ok(), rocksdb::ThreadState::rand, reads_, rocksdb::ThreadState::stats, and value.
Referenced by Run().
{
     FLAGS_warn_missing_keys = false;    // Never warn about missing keys
     Duration duration(FLAGS_duration, reads_);
     ReadOptions options(FLAGS_verify_checksum, true);
     if (FLAGS_use_multiget) {
       const long& kpg = FLAGS_keys_per_multiget;  // keys per multiget group
       long keys_left = reads_;
       // Recalculate number of keys per group, and call MultiGet until done
       long num_keys;
       long found;
       while(num_keys = std::min(keys_left, kpg), !duration.Done(num_keys)) {
         found = MultiGetRandom(options, num_keys, thread->rand, FLAGS_num, ".");
         // We should not find any key since the key we try to get has a
         // different suffix
         if (found) {
           assert(false);
         }
         thread->stats.FinishedSingleOp(db_);
         keys_left -= num_keys;
       }
     } else {  // Regular case (not MultiGet)
       std::string value;
       Status s;
       while (!duration.Done(1)) {
         const long long k = thread->rand.Next() % FLAGS_num;
         unique_ptr<char []> key = GenerateKeyFromInt(k, ".");
         s = db_->Get(options, key.get(), &value);
         assert(!s.ok() && s.IsNotFound());
         thread->stats.FinishedSingleOp(db_);
       }
     }
   }
void rocksdb::Benchmark::ReadRandom (ThreadState * thread) inline private
Definition at line 1657 of file db_bench.cc.
References rocksdb::Stats::AddMessage(), db_, rocksdb::Duration::Done(), rocksdb::Stats::FinishedSingleOp(), GenerateKeyFromInt(), rocksdb::DB::Get(), rocksdb::DB::GetApproximateSizes(), rocksdb::DB::GetSnapshot(), ripple::min(), MultiGetRandom(), rocksdb::DB::NewIterator(), rocksdb::Iterator::Next(), rocksdb::Random64::Next(), ripple::Resource::ok, rocksdb::ThreadState::rand, reads_, rocksdb::DB::ReleaseSnapshot(), rocksdb::Iterator::Seek(), rocksdb::ReadOptions::snapshot, rocksdb::ThreadState::stats, rocksdb::Iterator::Valid(), and value.
Referenced by ReadWhileWriting(), and Run().
{
     ReadOptions options(FLAGS_verify_checksum, true);
     Duration duration(FLAGS_duration, reads_);
     long long found = 0;
     if (FLAGS_use_multiget) {   // MultiGet
       const long& kpg = FLAGS_keys_per_multiget;  // keys per multiget group
       long keys_left = reads_;
       // Recalculate number of keys per group, and call MultiGet until done
       long num_keys;
       while(num_keys = std::min(keys_left, kpg), !duration.Done(num_keys)) {
         found += MultiGetRandom(options, num_keys, thread->rand, FLAGS_num, "");
         thread->stats.FinishedSingleOp(db_);
         keys_left -= num_keys;
       }
     } else {    // Regular case. Do one "get" at a time Get
       Iterator* iter = db_->NewIterator(options);
       std::string value;
       while (!duration.Done(1)) {
         const long long k = thread->rand.Next() % FLAGS_num;
         unique_ptr<char []> key = GenerateKeyFromInt(k);
         if (FLAGS_use_snapshot) {
           options.snapshot = db_->GetSnapshot();
         }
         if (FLAGS_read_range < 2) {
           if (db_->Get(options, key.get(), &value).ok()) {
             found++;
           }
         } else {
           Slice skey(key.get());
           int count = 1;
           if (FLAGS_get_approx) {
             unique_ptr<char []> key2 =
                 GenerateKeyFromInt(k + (int) FLAGS_read_range);
             Slice skey2(key2.get());
             Range range(skey, skey2);
             uint64_t sizes;
             db_->GetApproximateSizes(&range, 1, &sizes);
           }
           for (iter->Seek(skey);
                iter->Valid() && count <= FLAGS_read_range;
                ++count, iter->Next()) {
             found++;
           }
         }
         if (FLAGS_use_snapshot) {
           db_->ReleaseSnapshot(options.snapshot);
           options.snapshot = nullptr;
         }
         thread->stats.FinishedSingleOp(db_);
       }
       delete iter;
     }
     char msg[100];
     snprintf(msg, sizeof(msg), "(%lld of %lld found)", found, reads_);
     thread->stats.AddMessage(msg);
   }
void rocksdb::Benchmark::ReadRandomWriteRandom (ThreadState * thread) inline private
Definition at line 2085 of file db_bench.cc.
References rocksdb::Stats::AddMessage(), db_, rocksdb::Duration::Done(), rocksdb::Stats::FinishedSingleOp(), rocksdb::RandomGenerator::Generate(), GenerateKeyFromInt(), rocksdb::DB::Get(), rocksdb::DB::GetApproximateSizes(), rocksdb::DB::GetSnapshot(), rocksdb::Status::IsNotFound(), rocksdb::Random64::Next(), rocksdb::Status::ok(), rocksdb::DB::Put(), rocksdb::ThreadState::rand, ReadRandomWriteRandomMultiGet(), readwrites_, rocksdb::DB::ReleaseSnapshot(), rocksdb::ReadOptions::snapshot, rocksdb::ThreadState::stats, rocksdb::Status::ToString(), value, value_size_, and write_options_.
Referenced by Run().
{
     if (FLAGS_use_multiget){
       // Separate function for multiget (for ease of reading)
       ReadRandomWriteRandomMultiGet(thread);
       return;
     }
     ReadOptions options(FLAGS_verify_checksum, true);
     RandomGenerator gen;
     std::string value;
     long long found = 0;
     int get_weight = 0;
     int put_weight = 0;
     long long reads_done = 0;
     long long writes_done = 0;
     Duration duration(FLAGS_duration, readwrites_);
     // the number of iterations is the larger of read_ or write_
     while (!duration.Done(1)) {
       const long long k = thread->rand.Next() % FLAGS_num;
       unique_ptr<char []> key = GenerateKeyFromInt(k);
       if (get_weight == 0 && put_weight == 0) {
         // one batch completed, reinitialize for next batch
         get_weight = FLAGS_readwritepercent;
         put_weight = 100 - get_weight;
       }
       if (get_weight > 0) {
         if (FLAGS_use_snapshot) {
           options.snapshot = db_->GetSnapshot();
         }
         if (FLAGS_get_approx) {
           char key2[100];
           snprintf(key2, sizeof(key2), "%016lld", k + 1);
           Slice skey2(key2);
           Slice skey(key2);
           Range range(skey, skey2);
           uint64_t sizes;
           db_->GetApproximateSizes(&range, 1, &sizes);
         }
         // do all the gets first
         Status s = db_->Get(options, key.get(), &value);
         if (!s.ok() && !s.IsNotFound()) {
           fprintf(stderr, "get error: %s\n", s.ToString().c_str());
           // we continue after error rather than exiting so that we can
           // find more errors if any
         } else if (!s.IsNotFound()) {
           found++;
         }
         get_weight--;
         reads_done++;
         if (FLAGS_use_snapshot) {
           db_->ReleaseSnapshot(options.snapshot);
         }
       } else  if (put_weight > 0) {
         // then do all the corresponding number of puts
         // for all the gets we have done earlier
         Status s = db_->Put(write_options_, key.get(),
                             gen.Generate(value_size_));
         if (!s.ok()) {
           fprintf(stderr, "put error: %s\n", s.ToString().c_str());
           exit(1);
         }
         put_weight--;
         writes_done++;
       }
       thread->stats.FinishedSingleOp(db_);
     }
     char msg[100];
     snprintf(msg, sizeof(msg),
              "( reads:%lld writes:%lld total:%lld found:%lld)",
              reads_done, writes_done, readwrites_, found);
     thread->stats.AddMessage(msg);
   }
void rocksdb::Benchmark::ReadRandomWriteRandomMultiGet (ThreadState * thread) inline private
Definition at line 2172 of file db_bench.cc.
References rocksdb::Stats::AddMessage(), db_, rocksdb::Duration::Done(), rocksdb::Stats::FinishedSingleOp(), rocksdb::RandomGenerator::Generate(), GenerateKeyFromInt(), ripple::min(), MultiGetRandom(), rocksdb::Random64::Next(), rocksdb::Status::ok(), rocksdb::DB::Put(), rocksdb::ThreadState::rand, readwrites_, rocksdb::ThreadState::stats, rocksdb::Status::ToString(), value_size_, and write_options_.
Referenced by ReadRandomWriteRandom().
{
     ReadOptions options(FLAGS_verify_checksum, true);
     RandomGenerator gen;
     // For multiget
     const long& kpg = FLAGS_keys_per_multiget;  // keys per multiget group
     long keys_left = readwrites_;  // number of keys still left to read
     long num_keys;                  // number of keys to read in current group
     long num_put_keys;              // number of keys to put in current group
     long found = 0;
     long reads_done = 0;
     long writes_done = 0;
     long multigets_done = 0;
     // the number of iterations is the larger of read_ or write_
     Duration duration(FLAGS_duration, readwrites_);
     while(true) {
       // Read num_keys keys, then write num_put_keys keys.
       // The ratio of num_keys to num_put_keys is always FLAGS_readwritepercent
       // And num_keys is set to be FLAGS_keys_per_multiget (kpg)
       // num_put_keys is calculated accordingly (to maintain the ratio)
       // Note: On the final iteration, num_keys and num_put_keys will be smaller
       num_keys = std::min(keys_left*(FLAGS_readwritepercent + 99)/100, kpg);
       num_put_keys = num_keys * (100-FLAGS_readwritepercent)
                      / FLAGS_readwritepercent;
       // This will break the loop when duration is complete
       if (duration.Done(num_keys + num_put_keys)) {
         break;
       }
       // A quick check to make sure our formula doesn't break on edge cases
       assert(num_keys >= 1);
       assert(num_keys + num_put_keys <= keys_left);
       // Apply the MultiGet operations
       found += MultiGetRandom(options, num_keys, thread->rand, FLAGS_num, "");
       ++multigets_done;
       reads_done+=num_keys;
       thread->stats.FinishedSingleOp(db_);
       // Now do the puts
       int i;
       long long k;
       for(i=0; i<num_put_keys; ++i) {
         k = thread->rand.Next() % FLAGS_num;
         unique_ptr<char []> key = GenerateKeyFromInt(k);
         Status s = db_->Put(write_options_, key.get(),
                             gen.Generate(value_size_));
         if (!s.ok()) {
           fprintf(stderr, "put error: %s\n", s.ToString().c_str());
           exit(1);
         }
         writes_done++;
         thread->stats.FinishedSingleOp(db_);
       }
       keys_left -= (num_keys + num_put_keys);
     }
     char msg[100];
     snprintf(msg, sizeof(msg),
              "( reads:%ld writes:%ld total:%lld multiget_ops:%ld found:%ld)",
              reads_done, writes_done, readwrites_, multigets_done, found);
     thread->stats.AddMessage(msg);
   }
void rocksdb::Benchmark::ReadReverse (ThreadState * thread) inline private
Definition at line 1596 of file db_bench.cc.
References rocksdb::Stats::AddBytes(), db_, rocksdb::Stats::FinishedSingleOp(), rocksdb::Iterator::key(), rocksdb::DB::NewIterator(), rocksdb::Iterator::Prev(), reads_, rocksdb::Iterator::SeekToLast(), rocksdb::Slice::size(), rocksdb::ThreadState::stats, rocksdb::Iterator::Valid(), and rocksdb::Iterator::value().
Referenced by Run().
{
     Iterator* iter = db_->NewIterator(ReadOptions(FLAGS_verify_checksum, true));
     long long i = 0;
     int64_t bytes = 0;
     for (iter->SeekToLast(); i < reads_ && iter->Valid(); iter->Prev()) {
       bytes += iter->key().size() + iter->value().size();
       thread->stats.FinishedSingleOp(db_);
       ++i;
     }
     delete iter;
     thread->stats.AddBytes(bytes);
   }
void rocksdb::Benchmark::ReadSequential (ThreadState * thread) inline private
Definition at line 1583 of file db_bench.cc.
References rocksdb::Stats::AddBytes(), db_, rocksdb::Stats::FinishedSingleOp(), rocksdb::Iterator::key(), rocksdb::DB::NewIterator(), rocksdb::Iterator::Next(), reads_, rocksdb::Iterator::SeekToFirst(), rocksdb::Slice::size(), rocksdb::ThreadState::stats, rocksdb::Iterator::Valid(), and rocksdb::Iterator::value().
Referenced by Run().
{
     Iterator* iter = db_->NewIterator(ReadOptions(FLAGS_verify_checksum, true));
     long long i = 0;
     int64_t bytes = 0;
     for (iter->SeekToFirst(); i < reads_ && iter->Valid(); iter->Next()) {
       bytes += iter->key().size() + iter->value().size();
       thread->stats.FinishedSingleOp(db_);
       ++i;
     }
     delete iter;
     thread->stats.AddBytes(bytes);
   }
void rocksdb::Benchmark::ReadWhileWriting (ThreadState * thread) inline private
Definition at line 1880 of file db_bench.cc.
References db_, rocksdb::Stats::FinishedSingleOp(), rocksdb::RandomGenerator::Generate(), GenerateKeyFromInt(), rocksdb::SharedState::mu, rocksdb::Random64::Next(), rocksdb::Env::NowMicros(), rocksdb::SharedState::num_done, rocksdb::SharedState::num_initialized, rocksdb::Status::ok(), rocksdb::DB::Put(), rocksdb::ThreadState::rand, ReadRandom(), rocksdb::Stats::SetExcludeFromMerge(), rocksdb::ThreadState::shared, rocksdb::Env::SleepForMicroseconds(), rocksdb::ThreadState::stats, rocksdb::ThreadState::tid, rocksdb::Status::ToString(), value_size_, and write_options_.
Referenced by Run().
{
     if (thread->tid > 0) {
       ReadRandom(thread);
     } else {
       // Special thread that keeps writing until other threads are done.
       RandomGenerator gen;
       double last = FLAGS_env->NowMicros();
       int writes_per_second_by_10 = 0;
       int num_writes = 0;
       // --writes_per_second rate limit is enforced per 100 milliseconds
       // intervals to avoid a burst of writes at the start of each second.
       if (FLAGS_writes_per_second > 0)
         writes_per_second_by_10 = FLAGS_writes_per_second / 10;
       // Don't merge stats from this thread with the readers.
       thread->stats.SetExcludeFromMerge();
       while (true) {
         {
           MutexLock l(&thread->shared->mu);
           if (thread->shared->num_done + 1 >= thread->shared->num_initialized) {
             // Other threads have finished
             break;
           }
         }
         const long long k = thread->rand.Next() % FLAGS_num;
         unique_ptr<char []> key = GenerateKeyFromInt(k);
         Status s = db_->Put(write_options_, key.get(),
                             gen.Generate(value_size_));
         if (!s.ok()) {
           fprintf(stderr, "put error: %s\n", s.ToString().c_str());
           exit(1);
         }
         thread->stats.FinishedSingleOp(db_);
         ++num_writes;
         if (writes_per_second_by_10 && num_writes >= writes_per_second_by_10) {
           double now = FLAGS_env->NowMicros();
           double usecs_since_last = now - last;
           num_writes = 0;
           last = now;
           if (usecs_since_last < 100000.0) {
             FLAGS_env->SleepForMicroseconds(100000.0 - usecs_since_last);
             last = FLAGS_env->NowMicros();
           }
         }
       }
     }
   }
void rocksdb::Benchmark::Run () inline
Definition at line 976 of file db_bench.cc.
References AcquireLoad(), AppendRandom(), Compact(), ConstructStrFormatForKey(), Crc32c(), db_, dbstats, DeleteRandom(), DeleteSeq(), rocksdb::DestroyDB(), rocksdb::WriteOptions::disableWAL, entries_per_batch_, HeapProfile(), key_size_, keyFormat_, MergeRandom(), name, num_, Open(), PrefixScanRandom(), PrintHeader(), PrintStats(), RandomWithVerify(), ReadHot(), ReadMissing(), ReadRandom(), ReadRandomWriteRandom(), ReadReverse(), reads_, ReadSequential(), ReadWhileWriting(), RunBenchmark(), SeekRandom(), SnappyCompress(), SnappyUncompress(), rocksdb::WriteOptions::sync, rocksdb::Slice::ToString(), UpdateRandom(), value_size_, write_options_, WriteFromStdin(), WriteRandom(), writes_, WriteSeq(), and WriteUniqueRandom().
Referenced by main().
              {
     PrintHeader();
     Open();
     const char* benchmarks = FLAGS_benchmarks.c_str();
     while (benchmarks != nullptr) {
       const char* sep = strchr(benchmarks, ',');
       Slice name;
       if (sep == nullptr) {
         name = benchmarks;
         benchmarks = nullptr;
       } else {
         name = Slice(benchmarks, sep - benchmarks);
         benchmarks = sep + 1;
       }
       // Sanitize parameters
       num_ = FLAGS_num;
       reads_ = (FLAGS_reads < 0 ? FLAGS_num : FLAGS_reads);
       writes_ = (FLAGS_writes < 0 ? FLAGS_num : FLAGS_writes);
       value_size_ = FLAGS_value_size;
       key_size_ = FLAGS_key_size;
       ConstructStrFormatForKey(keyFormat_, key_size_);
       entries_per_batch_ = 1;
       write_options_ = WriteOptions();
       if (FLAGS_sync) {
         write_options_.sync = true;
       }
       write_options_.disableWAL = FLAGS_disable_wal;
       void (Benchmark::*method)(ThreadState*) = nullptr;
       bool fresh_db = false;
       int num_threads = FLAGS_threads;
       if (name == Slice("fillseq")) {
         fresh_db = true;
         method = &Benchmark::WriteSeq;
       } else if (name == Slice("fillbatch")) {
         fresh_db = true;
         entries_per_batch_ = 1000;
         method = &Benchmark::WriteSeq;
       } else if (name == Slice("fillrandom")) {
         fresh_db = true;
         method = &Benchmark::WriteRandom;
       } else if (name == Slice("fillfromstdin")) {
         fresh_db = true;
         method = &Benchmark::WriteFromStdin;
       } else if (name == Slice("filluniquerandom")) {
         fresh_db = true;
         if (num_threads > 1) {
           fprintf(stderr, "filluniquerandom multithreaded not supported"
                            " set --threads=1");
           exit(1);
         }
         method = &Benchmark::WriteUniqueRandom;
       } else if (name == Slice("overwrite")) {
         fresh_db = false;
         method = &Benchmark::WriteRandom;
       } else if (name == Slice("fillsync")) {
         fresh_db = true;
         num_ /= 1000;
         write_options_.sync = true;
         method = &Benchmark::WriteRandom;
       } else if (name == Slice("fill100K")) {
         fresh_db = true;
         num_ /= 1000;
         value_size_ = 100 * 1000;
         method = &Benchmark::WriteRandom;
       } else if (name == Slice("readseq")) {
         method = &Benchmark::ReadSequential;
       } else if (name == Slice("readreverse")) {
         method = &Benchmark::ReadReverse;
       } else if (name == Slice("readrandom")) {
         method = &Benchmark::ReadRandom;
       } else if (name == Slice("readmissing")) {
         method = &Benchmark::ReadMissing;
       } else if (name == Slice("seekrandom")) {
         method = &Benchmark::SeekRandom;
       } else if (name == Slice("readhot")) {
         method = &Benchmark::ReadHot;
       } else if (name == Slice("readrandomsmall")) {
         reads_ /= 1000;
         method = &Benchmark::ReadRandom;
       } else if (name == Slice("prefixscanrandom")) {
         method = &Benchmark::PrefixScanRandom;
       } else if (name == Slice("deleteseq")) {
         method = &Benchmark::DeleteSeq;
       } else if (name == Slice("deleterandom")) {
         method = &Benchmark::DeleteRandom;
       } else if (name == Slice("readwhilewriting")) {
         num_threads++;  // Add extra thread for writing
         method = &Benchmark::ReadWhileWriting;
       } else if (name == Slice("readrandomwriterandom")) {
         method = &Benchmark::ReadRandomWriteRandom;
       } else if (name == Slice("updaterandom")) {
         method = &Benchmark::UpdateRandom;
       } else if (name == Slice("appendrandom")) {
         method = &Benchmark::AppendRandom;
       } else if (name == Slice("mergerandom")) {
         if (FLAGS_merge_operator.empty()) {
           fprintf(stdout, "%-12s : skipped (--merge_operator is unknown)\n",
                   name.ToString().c_str());
           method = nullptr;
         } else {
           method = &Benchmark::MergeRandom;
         }
       } else if (name == Slice("randomwithverify")) {
         method = &Benchmark::RandomWithVerify;
       } else if (name == Slice("compact")) {
         method = &Benchmark::Compact;
       } else if (name == Slice("crc32c")) {
         method = &Benchmark::Crc32c;
       } else if (name == Slice("acquireload")) {
         method = &Benchmark::AcquireLoad;
       } else if (name == Slice("snappycomp")) {
         method = &Benchmark::SnappyCompress;
       } else if (name == Slice("snappyuncomp")) {
         method = &Benchmark::SnappyUncompress;
       } else if (name == Slice("heapprofile")) {
         HeapProfile();
       } else if (name == Slice("stats")) {
         PrintStats("rocksdb.stats");
       } else if (name == Slice("levelstats")) {
         PrintStats("rocksdb.levelstats");
       } else if (name == Slice("sstables")) {
         PrintStats("rocksdb.sstables");
       } else {
         if (name != Slice()) {  // No error message for empty name
           fprintf(stderr, "unknown benchmark '%s'\n", name.ToString().c_str());
         }
       }
       if (fresh_db) {
         if (FLAGS_use_existing_db) {
           fprintf(stdout, "%-12s : skipped (--use_existing_db is true)\n",
                   name.ToString().c_str());
           method = nullptr;
         } else {
           delete db_;
           db_ = nullptr;
           DestroyDB(FLAGS_db, Options());
           Open();
         }
       }
       if (method != nullptr) {
         fprintf(stdout, "DB path: [%s]\n", FLAGS_db.c_str());
         RunBenchmark(num_threads, name, method);
       }
     }
     if (FLAGS_statistics) {
      fprintf(stdout, "STATISTICS:\n%s\n", dbstats->ToString().c_str());
     }
   }
void rocksdb::Benchmark::RunBenchmark (int n, Slice name, void(Benchmark::*)(ThreadState *) method) inline private
Definition at line 1166 of file db_bench.cc.
References arg, rocksdb::Benchmark::ThreadArg::bm, rocksdb::SharedState::cv, rocksdb::port::Mutex::Lock(), rocksdb::Stats::Merge(), rocksdb::Benchmark::ThreadArg::method, rocksdb::SharedState::mu, rocksdb::SharedState::num_done, rocksdb::SharedState::num_initialized, rocksdb::Stats::Report(), shared, rocksdb::ThreadState::shared, rocksdb::Benchmark::ThreadArg::shared, rocksdb::port::CondVar::SignalAll(), rocksdb::SharedState::start, rocksdb::Env::StartThread(), rocksdb::Benchmark::ThreadArg::thread, ThreadBody(), rocksdb::SharedState::total, rocksdb::port::Mutex::Unlock(), and rocksdb::port::CondVar::Wait().
Referenced by Run().
{
     SharedState shared;
     shared.total = n;
     shared.num_initialized = 0;
     shared.num_done = 0;
     shared.start = false;
     ThreadArg* arg = new ThreadArg[n];
     for (int i = 0; i < n; i++) {
       arg[i].bm = this;
       arg[i].method = method;
       arg[i].shared = &shared;
       arg[i].thread = new ThreadState(i);
       arg[i].thread->shared = &shared;
       FLAGS_env->StartThread(ThreadBody, &arg[i]);
     }
     shared.mu.Lock();
     while (shared.num_initialized < n) {
       shared.cv.Wait();
     }
     shared.start = true;
     shared.cv.SignalAll();
     while (shared.num_done < n) {
       shared.cv.Wait();
     }
     shared.mu.Unlock();
     // Stats for some threads can be excluded.
     Stats merge_stats;
     for (int i = 0; i < n; i++) {
       merge_stats.Merge(arg[i].thread->stats);
     }
     merge_stats.Report(name);
     for (int i = 0; i < n; i++) {
       delete arg[i].thread;
     }
     delete[] arg;
   }
void rocksdb::Benchmark::SeekRandom (ThreadState * thread) inline private
Definition at line 1831 of file db_bench.cc.
References rocksdb::Stats::AddMessage(), db_, rocksdb::Duration::Done(), rocksdb::Stats::FinishedSingleOp(), GenerateKeyFromInt(), rocksdb::Iterator::key(), rocksdb::DB::NewIterator(), rocksdb::Random64::Next(), num_, rocksdb::ThreadState::rand, reads_, rocksdb::Iterator::Seek(), rocksdb::ThreadState::stats, rocksdb::Iterator::Valid(), and value.
Referenced by Run().
{
     Duration duration(FLAGS_duration, reads_);
     ReadOptions options(FLAGS_verify_checksum, true);
     std::string value;
     long long found = 0;
     while (!duration.Done(1)) {
       Iterator* iter = db_->NewIterator(options);
       const long long k = thread->rand.Next() % FLAGS_num;
       unique_ptr<char []> key = GenerateKeyFromInt(k);
       iter->Seek(key.get());
       if (iter->Valid() && iter->key() == key.get()) found++;
       delete iter;
       thread->stats.FinishedSingleOp(db_);
     }
     char msg[100];
     snprintf(msg, sizeof(msg), "(%lld of %lld found)", found, num_);
     thread->stats.AddMessage(msg);
   }
void rocksdb::Benchmark::SnappyCompress (ThreadState * thread) inline private
Definition at line 1244 of file db_bench.cc.
References rocksdb::Stats::AddBytes(), rocksdb::Stats::AddMessage(), rocksdb::Slice::data(), rocksdb::Stats::FinishedSingleOp(), rocksdb::RandomGenerator::Generate(), ripple::Resource::ok, rocksdb::Slice::size(), rocksdb::port::Snappy_Compress(), and rocksdb::ThreadState::stats.
Referenced by Run().
{
     RandomGenerator gen;
     Slice input = gen.Generate(Options().block_size);
     int64_t bytes = 0;
     int64_t produced = 0;
     bool ok = true;
     std::string compressed;
     while (ok && bytes < 1024 * 1048576) {  // Compress 1G
       ok = port::Snappy_Compress(Options().compression_opts, input.data(),
                                  input.size(), &compressed);
       produced += compressed.size();
       bytes += input.size();
       thread->stats.FinishedSingleOp(nullptr);
     }
     if (!ok) {
       thread->stats.AddMessage("(snappy failure)");
     } else {
       char buf[100];
       snprintf(buf, sizeof(buf), "(output: %.1f%%)",
                (produced * 100.0) / bytes);
       thread->stats.AddMessage(buf);
       thread->stats.AddBytes(bytes);
     }
   }
void rocksdb::Benchmark::SnappyUncompress (ThreadState * thread) inline private
Definition at line 1270 of file db_bench.cc.
References rocksdb::Stats::AddBytes(), rocksdb::Stats::AddMessage(), rocksdb::Slice::data(), rocksdb::Stats::FinishedSingleOp(), rocksdb::RandomGenerator::Generate(), ripple::Resource::ok, rocksdb::Slice::size(), rocksdb::port::Snappy_Compress(), rocksdb::port::Snappy_Uncompress(), and rocksdb::ThreadState::stats.
Referenced by Run().
{
     RandomGenerator gen;
     Slice input = gen.Generate(Options().block_size);
     std::string compressed;
     bool ok = port::Snappy_Compress(Options().compression_opts, input.data(),
                                     input.size(), &compressed);
     int64_t bytes = 0;
     char* uncompressed = new char[input.size()];
     while (ok && bytes < 1024 * 1048576) {  // Compress 1G
       ok =  port::Snappy_Uncompress(compressed.data(), compressed.size(),
                                     uncompressed);
       bytes += input.size();
       thread->stats.FinishedSingleOp(nullptr);
     }
     delete[] uncompressed;
     if (!ok) {
       thread->stats.AddMessage("(snappy failure)");
     } else {
       thread->stats.AddBytes(bytes);
     }
   }
static void rocksdb::Benchmark::ThreadBody (void * v) inline static private
Definition at line 1138 of file db_bench.cc.
References arg, rocksdb::Benchmark::ThreadArg::bm, rocksdb::SharedState::cv, rocksdb::Benchmark::ThreadArg::method, rocksdb::SharedState::mu, rocksdb::SharedState::num_done, rocksdb::SharedState::num_initialized, shared, rocksdb::Benchmark::ThreadArg::shared, rocksdb::port::CondVar::SignalAll(), rocksdb::Stats::Start(), rocksdb::SharedState::start, rocksdb::ThreadState::stats, rocksdb::Stats::Stop(), rocksdb::Benchmark::ThreadArg::thread, rocksdb::ThreadState::tid, rocksdb::SharedState::total, and rocksdb::port::CondVar::Wait().
Referenced by RunBenchmark().
{
     ThreadArg* arg = reinterpret_cast<ThreadArg*>(v);
     SharedState* shared = arg->shared;
     ThreadState* thread = arg->thread;
     {
       MutexLock l(&shared->mu);
       shared->num_initialized++;
       if (shared->num_initialized >= shared->total) {
         shared->cv.SignalAll();
       }
       while (!shared->start) {
         shared->cv.Wait();
       }
     }
     thread->stats.Start(thread->tid);
     (arg->bm->*(arg->method))(thread);
     thread->stats.Stop();
     {
       MutexLock l(&shared->mu);
       shared->num_done++;
       if (shared->num_done >= shared->total) {
         shared->cv.SignalAll();
       }
     }
   }
void rocksdb::Benchmark::UpdateRandom (ThreadState * thread) inline private
Definition at line 2242 of file db_bench.cc.
References rocksdb::Stats::AddMessage(), db_, rocksdb::Duration::Done(), rocksdb::Stats::FinishedSingleOp(), rocksdb::RandomGenerator::Generate(), GenerateKeyFromInt(), rocksdb::DB::Get(), rocksdb::DB::GetApproximateSizes(), rocksdb::DB::GetSnapshot(), rocksdb::Random64::Next(), ripple::Resource::ok, rocksdb::Status::ok(), rocksdb::DB::Put(), rocksdb::ThreadState::rand, readwrites_, rocksdb::DB::ReleaseSnapshot(), rocksdb::ReadOptions::snapshot, rocksdb::ThreadState::stats, rocksdb::Status::ToString(), value, value_size_, and write_options_.
Referenced by Run().
{
     ReadOptions options(FLAGS_verify_checksum, true);
     RandomGenerator gen;
     std::string value;
     long long found = 0;
     Duration duration(FLAGS_duration, readwrites_);
     // the number of iterations is the larger of read_ or write_
     while (!duration.Done(1)) {
       const long long k = thread->rand.Next() % FLAGS_num;
       unique_ptr<char []> key = GenerateKeyFromInt(k);
       if (FLAGS_use_snapshot) {
         options.snapshot = db_->GetSnapshot();
       }
       if (FLAGS_get_approx) {
         char key2[100];
         snprintf(key2, sizeof(key2), "%016lld", k + 1);
         Slice skey2(key2);
         Slice skey(key2);
         Range range(skey, skey2);
         uint64_t sizes;
         db_->GetApproximateSizes(&range, 1, &sizes);
       }
       if (db_->Get(options, key.get(), &value).ok()) {
         found++;
       }
       if (FLAGS_use_snapshot) {
         db_->ReleaseSnapshot(options.snapshot);
       }
       Status s = db_->Put(write_options_, key.get(), gen.Generate(value_size_));
       if (!s.ok()) {
         fprintf(stderr, "put error: %s\n", s.ToString().c_str());
         exit(1);
       }
       thread->stats.FinishedSingleOp(db_);
     }
     char msg[100];
     snprintf(msg, sizeof(msg),
              "( updates:%lld found:%lld)", readwrites_, found);
     thread->stats.AddMessage(msg);
   }
void rocksdb::Benchmark::WriteFromStdin (ThreadState * thread) inline private
Definition at line 1466 of file db_bench.cc.
References rocksdb::Stats::AddBytes(), rocksdb::WriteBatch::Clear(), rocksdb::WriteBatch::Count(), db_, rocksdb::Stats::FinishedSingleOp(), rocksdb::WriteBatch::Put(), rocksdb::ThreadState::stats, value, and writeOrFail().
Referenced by Run().
{
     size_t count = 0;
     WriteBatch batch;
     const size_t bufferLen = 32 << 20;
     unique_ptr<char[]> line = unique_ptr<char[]>(new char[bufferLen]);
     char* linep = line.get();
     const int batchSize = 100 << 10;
     const char columnSeparator = '\t';
     const char lineSeparator = '\n';
     while (fgets(linep, bufferLen, stdin) != nullptr) {
       ++count;
       char* tab = std::find(linep, linep + bufferLen, columnSeparator);
       if (tab == linep + bufferLen) {
         fprintf(stderr, "[Error] No Key delimiter TAB at line %ld\n", count);
         continue;
       }
       Slice key(linep, tab - linep);
       tab++;
       char* endLine = std::find(tab, linep + bufferLen, lineSeparator);
       if (endLine  == linep + bufferLen) {
         fprintf(stderr, "[Error] No ENTER at end of line # %ld\n", count);
         continue;
       }
       Slice value(tab, endLine - tab);
       thread->stats.FinishedSingleOp(db_);
       thread->stats.AddBytes(endLine - linep - 1);
       if (batch.Count() < batchSize) {
         batch.Put(key, value);
         continue;
       }
       writeOrFail(batch);
       batch.Clear();
     }
     if (batch.Count() > 0) {
       writeOrFail(batch);
     }
   }
void rocksdb::Benchmark::writeOrFail (WriteBatch & batch) inline private
Definition at line 1458 of file db_bench.cc.
References db_, rocksdb::Status::ok(), rocksdb::Status::ToString(), rocksdb::DB::Write(), and write_options_.
Referenced by WriteFromStdin().
{
     Status s = db_->Write(write_options_, &batch);
     if (!s.ok()) {
       fprintf(stderr, "put error: %s\n", s.ToString().c_str());
       exit(1);
     }
   }
void rocksdb::Benchmark::WriteRandom (ThreadState * thread) inline private
Definition at line 1450 of file db_bench.cc.
References DoWrite(), and RANDOM.
Referenced by Run().
{
     DoWrite(thread, RANDOM);
   }
void rocksdb::Benchmark::WriteSeq (ThreadState * thread) inline private
Definition at line 1446 of file db_bench.cc.
References DoWrite(), and SEQUENTIAL.
Referenced by Run().
{
     DoWrite(thread, SEQUENTIAL);
   }
static void rocksdb::Benchmark::WriteToFile (void * arg, const char * buf, int n) inline static private
Definition at line 2395 of file db_bench.cc.
References arg.
Referenced by HeapProfile().
{
     reinterpret_cast<WritableFile*>(arg)->Append(Slice(buf, n));
   }
void rocksdb::Benchmark::WriteUniqueRandom (ThreadState * thread) inline private
Definition at line 1454 of file db_bench.cc.
References DoWrite(), and UNIQUE_RANDOM.
Referenced by Run().
{
     DoWrite(thread, UNIQUE_RANDOM);
   }
Member Data Documentation
shared_ptr<Cache> rocksdb::Benchmark::cache_ private
Definition at line 754 of file db_bench.cc.
Referenced by Open().
shared_ptr<Cache> rocksdb::Benchmark::compressed_cache_ private
Definition at line 755 of file db_bench.cc.
Referenced by Open().
DB* rocksdb::Benchmark::db_ private
Definition at line 758 of file db_bench.cc.
Referenced by AppendRandom(), Compact(), DeleteMany(), DoDelete(), DoWrite(), GetMany(), MergeRandom(), MultiGetRandom(), Open(), PrefixScanRandom(), PrintStats(), PutMany(), RandomWithVerify(), ReadHot(), ReadMissing(), ReadRandom(), ReadRandomWriteRandom(), ReadRandomWriteRandomMultiGet(), ReadReverse(), ReadSequential(), ReadWhileWriting(), Run(), SeekRandom(), UpdateRandom(), WriteFromStdin(), writeOrFail(), and ~Benchmark().
int rocksdb::Benchmark::entries_per_batch_ private
Definition at line 762 of file db_bench.cc.
Referenced by DoDelete(), DoWrite(), and Run().
const FilterPolicy* rocksdb::Benchmark::filter_policy_ private
Definition at line 756 of file db_bench.cc.
Referenced by Open(), and ~Benchmark().
int rocksdb::Benchmark::heap_counter_ private
Definition at line 767 of file db_bench.cc.
Referenced by HeapProfile().
int rocksdb::Benchmark::key_size_ private
Definition at line 761 of file db_bench.cc.
Referenced by Run().
char rocksdb::Benchmark::keyFormat_[100] private
Definition at line 768 of file db_bench.cc.
Referenced by GenerateKeyFromInt(), and Run().
long long rocksdb::Benchmark::num_ private
Definition at line 759 of file db_bench.cc.
Referenced by DoDelete(), DoWrite(), PrintHeader(), Run(), and SeekRandom().
const SliceTransform* rocksdb::Benchmark::prefix_extractor_ private
Definition at line 757 of file db_bench.cc.
Referenced by Open(), PrefixScanRandom(), and ~Benchmark().
long long rocksdb::Benchmark::reads_ private
Definition at line 764 of file db_bench.cc.
Referenced by PrefixScanRandom(), ReadHot(), ReadMissing(), ReadRandom(), ReadReverse(), ReadSequential(), Run(), and SeekRandom().
long long rocksdb::Benchmark::readwrites_ private
Definition at line 766 of file db_bench.cc.
Referenced by AppendRandom(), MergeRandom(), RandomWithVerify(), ReadRandomWriteRandom(), ReadRandomWriteRandomMultiGet(), and UpdateRandom().
int rocksdb::Benchmark::value_size_ private
Definition at line 760 of file db_bench.cc.
Referenced by AppendRandom(), DoWrite(), MergeRandom(), RandomWithVerify(), ReadRandomWriteRandom(), ReadRandomWriteRandomMultiGet(), ReadWhileWriting(), Run(), and UpdateRandom().
WriteOptions rocksdb::Benchmark::write_options_ private
Definition at line 763 of file db_bench.cc.
Referenced by AppendRandom(), DoDelete(), DoWrite(), MergeRandom(), RandomWithVerify(), ReadRandomWriteRandom(), ReadRandomWriteRandomMultiGet(), ReadWhileWriting(), Run(), UpdateRandom(), and writeOrFail().
long long rocksdb::Benchmark::writes_ private
Definition at line 765 of file db_bench.cc.
Referenced by DoWrite(), and Run().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/db/db_bench.cc