rippled: ripple::UniqueNodeListImp Class Reference
ripple::UniqueNodeListImp Class Reference
Classes
struct scoreNode
struct seedDomain
struct seedNode
Public Member Functions
UniqueNodeListImp (Stoppable &parent)
void onStop ()
void doScore ()
void doFetch ()
void onDeadlineTimer (beast::DeadlineTimer &timer)
void start ()
void nodeAddPublic (const RippleAddress &naNodePublic, ValidatorSource vsWhy, const std::string &strComment)
void nodeAddDomain (std::string strDomain, ValidatorSource vsWhy, const std::string &strComment)
void nodeRemovePublic (const RippleAddress &naNodePublic)
void nodeRemoveDomain (std::string strDomain)
void nodeReset ()
void nodeScore ()
bool nodeInUNL (const RippleAddress &naNodePublic)
bool nodeInCluster (const RippleAddress &naNodePublic)
bool nodeInCluster (const RippleAddress &naNodePublic, std::string &name)
bool nodeUpdate (const RippleAddress &naNodePublic, ClusterNodeStatus const &cnsStatus)
std::map< RippleAddress,
ClusterNodeStatus > getClusterStatus ()
std::uint32_t getClusterFee ()
void addClusterStatus (Json::Value &obj)
void nodeBootstrap ()
bool nodeLoad (boost::filesystem::path pConfig)
void nodeNetwork ()
Json::Value getUnlJson ()
int iSourceScore (ValidatorSource vsWhy)
Public Member Functions inherited from ripple::UniqueNodeList
virtual ~UniqueNodeList ()
Public Member Functions inherited from beast::Stoppable
Stoppable (char const *name, Stoppable &parent)
virtual ~Stoppable ()
bool isStopping () const
bool isStopped () const
bool areChildrenStopped () const
void stopped ()
virtual void onPrepare ()
virtual void onStart ()
virtual void onChildrenStopped ()
Private Types
typedef ripple::unordered_map
< std::string, int > strIndex
typedef std::pair< std::string,
int > IPAndPortNumber
typedef ripple::unordered_map
< std::pair< std::string, int >
, score > epScore
typedef RippleMutex FetchLockType
typedef std::lock_guard
< FetchLockType > ScopedFetchLockType
typedef RippleRecursiveMutex UNLLockType
typedef std::lock_guard
< UNLLockType > ScopedUNLLockType
Private Member Functions
bool miscLoad ()
bool miscSave ()
void trustedLoad ()
bool scoreRound (std::vector< scoreNode > &vsnNodes)
void scoreCompute ()
void scoreNext (bool bNow)
bool responseFetch (const std::string &strDomain, const boost::system::error_code &err, int iStatus, const std::string &strSiteFile)
void fetchNext ()
void fetchDirty ()
void fetchFinish ()
void fetchProcess (std::string strDomain)
void fetchTimerHandler (const boost::system::error_code &err)
void getValidatorsUrl (const RippleAddress &naNodePublic, Section secSite)
void getIpsUrl (const RippleAddress &naNodePublic, Section secSite)
bool responseIps (const std::string &strSite, const RippleAddress &naNodePublic, const boost::system::error_code &err, int iStatus, const std::string &strIpsFile)
bool responseValidators (const std::string &strValidatorsUrl, const RippleAddress &naNodePublic, Section secSite, const std::string &strSite, const boost::system::error_code &err, int iStatus, const std::string &strValidatorsFile)
void processIps (const std::string &strSite, const RippleAddress &naNodePublic, Section::mapped_type *pmtVecStrIps)
int processValidators (const std::string &strSite, const std::string &strValidatorsSrc, const RippleAddress &naNodePublic, ValidatorSource vsWhy, Section::mapped_type *pmtVecStrValidators)
void processFile (const std::string &strDomain, const RippleAddress &naNodePublic, Section secSite)
bool getSeedDomains (const std::string &strDomain, seedDomain &dstSeedDomain)
void setSeedDomains (const seedDomain &sdSource, bool bNext)
bool getSeedNodes (const RippleAddress &naNodePublic, seedNode &dstSeedNode)
void setSeedNodes (const seedNode &snSource, bool bNext)
bool validatorsResponse (const boost::system::error_code &err, int iStatus, std::string strResponse)
void nodeProcess (const std::string &strSite, const std::string &strValidators, const std::string &strSource)
Private Attributes
FetchLockType mFetchLock
UNLLockType mUNLLock
boost::posix_time::ptime mtpScoreUpdated
boost::posix_time::ptime mtpFetchUpdated
boost::unordered_set< std::string > mUNL
boost::posix_time::ptime mtpScoreNext
boost::posix_time::ptime mtpScoreStart
beast::DeadlineTimer m_scoreTimer
int mFetchActive
boost::posix_time::ptime mtpFetchNext
beast::DeadlineTimer m_fetchTimer
std::map< RippleAddress,
ClusterNodeStatus > m_clusterNodes
Additional Inherited Members
Public Types inherited from ripple::UniqueNodeList
enum ValidatorSource {
vsConfig = 'C', vsInbound = 'I', vsManual = 'M', vsReferral = 'R',
vsTold = 'T', vsValidator = 'V', vsWeb = 'W'
}
typedef long score
Static Public Member Functions inherited from ripple::UniqueNodeList
static UniqueNodeList * New (Stoppable &parent)
Protected Member Functions inherited from ripple::UniqueNodeList
UniqueNodeList (Stoppable &parent)
Protected Attributes inherited from beast::Stoppable
char const * m_name
RootStoppable & m_root
Child m_child
Atomic< int > m_started
bool volatile m_stopped
bool volatile m_childrenStopped
Children m_children
WaitableEvent m_stoppedEvent
Detailed Description
Definition at line 65 of file UniqueNodeList.cpp.
Member Typedef Documentation
typedef ripple::unordered_map<std::pair< std::string, int>, score> ripple::UniqueNodeListImp::epScore private
Definition at line 109 of file UniqueNodeList.cpp.
typedef RippleMutex ripple::UniqueNodeListImp::FetchLockType private
Definition at line 2008 of file UniqueNodeList.cpp.
typedef std::pair<std::string, int> ripple::UniqueNodeListImp::IPAndPortNumber private
Definition at line 108 of file UniqueNodeList.cpp.
typedef std::lock_guard<FetchLockType> ripple::UniqueNodeListImp::ScopedFetchLockType private
Definition at line 2009 of file UniqueNodeList.cpp.
typedef std::lock_guard<UNLLockType> ripple::UniqueNodeListImp::ScopedUNLLockType private
Definition at line 2013 of file UniqueNodeList.cpp.
typedef ripple::unordered_map<std::string, int> ripple::UniqueNodeListImp::strIndex private
Definition at line 107 of file UniqueNodeList.cpp.
typedef RippleRecursiveMutex ripple::UniqueNodeListImp::UNLLockType private
Definition at line 2012 of file UniqueNodeList.cpp.
Constructor & Destructor Documentation
ripple::UniqueNodeListImp::UniqueNodeListImp (Stoppable & parent) inline explicit
Definition at line 112 of file UniqueNodeList.cpp.
         : UniqueNodeList (parent)
         , m_scoreTimer (this)
         , mFetchActive (0)
         , m_fetchTimer (this)
     {
     }
Member Function Documentation
void ripple::UniqueNodeListImp::addClusterStatus (Json::Value & obj) inline virtual
Implements ripple::UniqueNodeList.
Definition at line 410 of file UniqueNodeList.cpp.
References ripple::getApp(), ripple::Application::getFeeTrack(), ripple::LoadFeeTrack::getLoadBase(), ripple::Application::getLocalCredentials(), ripple::NetworkOPs::getNetworkTimeNC(), ripple::LocalCredentials::getNodePublic(), ripple::Application::getOPs(), and Json::objectValue.
     {
         ScopedUNLLockType sl (mUNLLock);
         if (m_clusterNodes.size() > 1) // nodes other than us
         {
             int          now   = getApp().getOPs().getNetworkTimeNC();
             std::uint32_t ref   = getApp().getFeeTrack().getLoadBase();
             Json::Value& nodes = (obj["cluster"] = Json::objectValue);
             for (std::map<RippleAddress, ClusterNodeStatus>::iterator it = m_clusterNodes.begin(),
                 end = m_clusterNodes.end(); it != end; ++it)
             {
                 if (it->first != getApp().getLocalCredentials().getNodePublic())
                 {
                     Json::Value& node = nodes[it->first.humanNodePublic()];
                     if (!it->second.getName().empty())
                         node["tag"] = it->second.getName();
                     if ((it->second.getLoadFee() != ref) && (it->second.getLoadFee() != 0))
                         node["fee"] = static_cast<double>(it->second.getLoadFee()) / ref;
                     if (it->second.getReportTime() != 0)
                         node["age"] = (it->second.getReportTime() >= now) ? 0 : (now - it->second.getReportTime());
                 }
             }
         }
     }
void ripple::UniqueNodeListImp::doFetch () inline
Definition at line 153 of file UniqueNodeList.cpp.
References ripple::lsTRACE, and WriteLog.
Referenced by onDeadlineTimer().
     {
         // Time to check for another fetch.
         WriteLog (lsTRACE, UniqueNodeList) << "fetchTimerHandler";
         fetchNext ();
     }
void ripple::UniqueNodeListImp::doScore () inline
Definition at line 132 of file UniqueNodeList.cpp.
References ripple::lsTRACE, and WriteLog.
Referenced by onDeadlineTimer().
     {
         mtpScoreNext    = boost::posix_time::ptime (boost::posix_time::not_a_date_time); // Timer not set.
         mtpScoreStart   = boost::posix_time::second_clock::universal_time ();           // Scoring.
         WriteLog (lsTRACE, UniqueNodeList) << "Scoring: Start";
         scoreCompute ();
         WriteLog (lsTRACE, UniqueNodeList) << "Scoring: End";
         // Save update time.
         mtpScoreUpdated = mtpScoreStart;
         miscSave ();
         mtpScoreStart   = boost::posix_time::ptime (boost::posix_time::not_a_date_time); // Not scoring.
         // Score again if needed.
         scoreNext (false);
     }
void ripple::UniqueNodeListImp::fetchDirty () inline private
Definition at line 1369 of file UniqueNodeList.cpp.
     {
         // Note update.
         mtpFetchUpdated = boost::posix_time::second_clock::universal_time ();
         miscSave ();
         // Update scores.
         scoreNext (false);
     }
void ripple::UniqueNodeListImp::fetchFinish () inline private
Definition at line 1382 of file UniqueNodeList.cpp.
     {
         {
             ScopedFetchLockType sl (mFetchLock);
             mFetchActive--;
         }
         fetchNext ();
     }
void ripple::UniqueNodeListImp::fetchNext () inline private
Definition at line 1275 of file UniqueNodeList.cpp.
References db, ripple::Database::endIterRows(), ripple::Database::executeSQL(), ripple::getApp(), ripple::DatabaseCon::getDB(), ripple::Database::getInt(), ripple::Database::getStrBinary(), ripple::Application::getWalletDB(), ripple::lsTRACE, NODE_FETCH_JOBS, NODE_FILE_NAME, ripple::ptFromSeconds(), ripple::Database::startIterRows(), ripple::UniqueNodeListImp::seedDomain::tpNext, ripple::UniqueNodeListImp::seedDomain::tpScan, and WriteLog.
     {
         bool    bFull;
         {
             ScopedFetchLockType sl (mFetchLock);
             bFull = (mFetchActive == NODE_FETCH_JOBS);
         }
         if (!bFull)
         {
             // Determine next scan.
             std::string strDomain;
             boost::posix_time::ptime tpNext (boost::posix_time::min_date_time);
             boost::posix_time::ptime tpNow (boost::posix_time::second_clock::universal_time ());
             DeprecatedScopedLock sl (getApp().getWalletDB ()->getDBLock ());
             Database* db = getApp().getWalletDB ()->getDB ();
             if (db->executeSQL ("SELECT Domain,Next FROM SeedDomains INDEXED BY SeedDomainNext ORDER BY Next LIMIT 1;")
                     && db->startIterRows ())
             {
                 int iNext (db->getInt ("Next"));
                 tpNext  = ptFromSeconds (iNext);
                 WriteLog (lsTRACE, UniqueNodeList) << str (boost::format ("fetchNext: iNext=%s tpNext=%s tpNow=%s") % iNext % tpNext % tpNow);
                 strDomain = db->getStrBinary ("Domain");
                 db->endIterRows ();
             }
             if (!strDomain.empty ())
             {
                 ScopedFetchLockType sl (mFetchLock);
                 bFull = (mFetchActive == NODE_FETCH_JOBS);
                 if (!bFull && tpNext <= tpNow)
                 {
                     mFetchActive++;
                 }
             }
             if (strDomain.empty () || bFull)
             {
                 WriteLog (lsTRACE, UniqueNodeList) << str (boost::format ("fetchNext: strDomain=%s bFull=%d") % strDomain % bFull);
             }
             else if (tpNext > tpNow)
             {
                 WriteLog (lsTRACE, UniqueNodeList) << str (boost::format ("fetchNext: set timer : strDomain=%s") % strDomain);
                 // Fetch needs to happen in the future.  Set a timer to wake us.
                 mtpFetchNext    = tpNext;
                 double seconds = (tpNext - tpNow).seconds ();
                 // VFALCO check this.
                 if (seconds == 0)
                     seconds = 1;
                 m_fetchTimer.setExpiration (seconds);
             }
             else
             {
                 WriteLog (lsTRACE, UniqueNodeList) << str (boost::format ("fetchNext: fetch now: strDomain=%s tpNext=%s tpNow=%s") % strDomain % tpNext % tpNow);
                 // Fetch needs to happen now.
                 mtpFetchNext    = boost::posix_time::ptime (boost::posix_time::not_a_date_time);
                 seedDomain  sdCurrent;
                 bool        bFound  = getSeedDomains (strDomain, sdCurrent);
                 assert (bFound);
                 // Update time of next fetch and this scan attempt.
                 sdCurrent.tpScan        = tpNow;
                 // XXX Use a longer duration if we have lots of validators.
                 sdCurrent.tpNext        = sdCurrent.tpScan + boost::posix_time::hours (7 * 24);
                 setSeedDomains (sdCurrent, false);
                 WriteLog (lsTRACE, UniqueNodeList) << "Validator: '" << strDomain << "' fetching " NODE_FILE_NAME ".";
                 fetchProcess (strDomain);   // Go get it.
                 fetchNext ();               // Look for more.
             }
         }
     }
void ripple::UniqueNodeListImp::fetchProcess (std::string strDomain) inline private
Definition at line 1395 of file UniqueNodeList.cpp.
References BIND_TYPE, ripple::HTTPClient::get(), ripple::getApp(), ripple::lsTRACE, NODE_FETCH_SECONDS, NODE_FILE_BYTES_MAX, NODE_FILE_NAME, NODE_FILE_PATH, P_1, P_2, P_3, responseFetch(), SYSTEM_NAME, and WriteLog.
     {
         WriteLog (lsTRACE, UniqueNodeList) << "Fetching '" NODE_FILE_NAME "' from '" << strDomain << "'.";
         std::deque<std::string> deqSites;
         // Order searching from most specifically for purpose to generic.
         // This order allows the client to take the most burden rather than the servers.
         deqSites.push_back (str (boost::format (SYSTEM_NAME ".%s") % strDomain));
         deqSites.push_back (str (boost::format ("www.%s") % strDomain));
         deqSites.push_back (strDomain);
         HTTPClient::get (
             true,
             getApp().getIOService (),
             deqSites,
             443,
             NODE_FILE_PATH,
             NODE_FILE_BYTES_MAX,
             boost::posix_time::seconds (NODE_FETCH_SECONDS),
             BIND_TYPE (&UniqueNodeListImp::responseFetch, this, strDomain, P_1, P_2, P_3));
     }
void ripple::UniqueNodeListImp::fetchTimerHandler (const boost::system::error_code & err) inline private
Definition at line 1420 of file UniqueNodeList.cpp.
     {
         if (!err)
         {
             onDeadlineTimer (m_fetchTimer);
         }
     }
std::uint32_t ripple::UniqueNodeListImp::getClusterFee () inline virtual
Implements ripple::UniqueNodeList.
Definition at line 385 of file UniqueNodeList.cpp.
References ripple::getApp(), ripple::NetworkOPs::getNetworkTimeNC(), and ripple::Application::getOPs().
     {
         int thresh = getApp().getOPs().getNetworkTimeNC() - 90;
         std::vector<std::uint32_t> fees;
         {
             ScopedUNLLockType sl (mUNLLock);
             {
                 for (std::map<RippleAddress, ClusterNodeStatus>::iterator it = m_clusterNodes.begin(),
                     end = m_clusterNodes.end(); it != end; ++it)
                 {
                     if (it->second.getReportTime() >= thresh)
                         fees.push_back(it->second.getLoadFee());
                 }
             }
         }
         if (fees.empty())
             return 0;
         std::sort (fees.begin(), fees.end());
         return fees[fees.size() / 2];
     }
std::map<RippleAddress, ClusterNodeStatus> ripple::UniqueNodeListImp::getClusterStatus () inline virtual
Implements ripple::UniqueNodeList.
Definition at line 373 of file UniqueNodeList.cpp.
     {
         std::map<RippleAddress, ClusterNodeStatus> ret;
         {
             ScopedUNLLockType sl (mUNLLock);
             ret = m_clusterNodes;
         }
         return ret;
     }
void ripple::UniqueNodeListImp::getIpsUrl (const RippleAddress & naNodePublic, Section secSite) inline private
Definition at line 1466 of file UniqueNodeList.cpp.
References BIND_TYPE, ripple::HTTPClient::get(), ripple::getApp(), NODE_FETCH_SECONDS, NODE_FILE_BYTES_MAX, P_1, P_2, P_3, ripple::parseUrl(), responseIps(), SECTION_IPS_URL, and ripple::SectionSingleB().
     {
         std::string strIpsUrl;
         std::string strScheme;
         std::string strDomain;
         int         iPort;
         std::string strPath;
         if (SectionSingleB (secSite, SECTION_IPS_URL, strIpsUrl)
                 && !strIpsUrl.empty ()
                 && parseUrl (strIpsUrl, strScheme, strDomain, iPort, strPath)
                 && -1 == iPort
                 && strScheme == "https")
         {
             HTTPClient::get (
                 true,
                 getApp().getIOService (),
                 strDomain,
                 443,
                 strPath,
                 NODE_FILE_BYTES_MAX,
                 boost::posix_time::seconds (NODE_FETCH_SECONDS),
                 BIND_TYPE (&UniqueNodeListImp::responseIps, this, strDomain, naNodePublic, P_1, P_2, P_3));
         }
         else
         {
             fetchFinish ();
         }
     }
bool ripple::UniqueNodeListImp::getSeedDomains (const std::string & strDomain, seedDomain & dstSeedDomain) inline private
Definition at line 1746 of file UniqueNodeList.cpp.
References ripple::RippleAddress::clear(), db, ripple::Database::endIterRows(), ripple::Database::executeSQL(), ripple::getApp(), ripple::DatabaseCon::getDB(), ripple::Database::getInt(), ripple::Database::getNull(), ripple::Database::getStr(), ripple::Database::getStrBinary(), ripple::Application::getWalletDB(), ripple::UniqueNodeListImp::seedDomain::iSha256, ripple::UniqueNodeListImp::seedDomain::naPublicKey, ripple::ptFromSeconds(), ripple::base_uint< BITS >::SetHex(), ripple::RippleAddress::setNodePublic(), ripple::sqlEscape(), ripple::Database::startIterRows(), ripple::UniqueNodeListImp::seedDomain::strComment, ripple::UniqueNodeListImp::seedDomain::strDomain, ripple::UniqueNodeListImp::seedDomain::tpFetch, ripple::UniqueNodeListImp::seedDomain::tpNext, ripple::UniqueNodeListImp::seedDomain::tpScan, ripple::UniqueNodeListImp::seedDomain::vsSource, and ripple::base_uint< BITS >::zero().
     {
         bool        bResult;
         Database*   db = getApp().getWalletDB ()->getDB ();
         std::string strSql  = boost::str (boost::format ("SELECT * FROM SeedDomains WHERE Domain=%s;")
                                           % sqlEscape (strDomain));
         DeprecatedScopedLock sl (getApp().getWalletDB ()->getDBLock ());
         bResult = db->executeSQL (strSql) && db->startIterRows ();
         if (bResult)
         {
             std::string     strPublicKey;
             int             iNext;
             int             iScan;
             int             iFetch;
             std::string     strSha256;
             dstSeedDomain.strDomain = db->getStrBinary ("Domain");
             if (!db->getNull ("PublicKey") && db->getStr ("PublicKey", strPublicKey))
             {
                 dstSeedDomain.naPublicKey.setNodePublic (strPublicKey);
             }
             else
             {
                 dstSeedDomain.naPublicKey.clear ();
             }
             std::string     strSource   = db->getStrBinary ("Source");
             dstSeedDomain.vsSource  = static_cast<ValidatorSource> (strSource[0]);
             iNext   = db->getInt ("Next");
             dstSeedDomain.tpNext    = ptFromSeconds (iNext);
             iScan   = db->getInt ("Scan");
             dstSeedDomain.tpScan    = ptFromSeconds (iScan);
             iFetch  = db->getInt ("Fetch");
             dstSeedDomain.tpFetch   = ptFromSeconds (iFetch);
             if (!db->getNull ("Sha256") && db->getStr ("Sha256", strSha256))
             {
                 dstSeedDomain.iSha256.SetHex (strSha256);
             }
             else
             {
                 dstSeedDomain.iSha256.zero ();
             }
             dstSeedDomain.strComment    = db->getStrBinary ("Comment");
             db->endIterRows ();
         }
         return bResult;
     }
bool ripple::UniqueNodeListImp::getSeedNodes (const RippleAddress & naNodePublic, seedNode & dstSeedNode) inline private
Definition at line 1847 of file UniqueNodeList.cpp.
References ripple::RippleAddress::clear(), db, ripple::Database::endIterRows(), ripple::Database::executeSQL(), ripple::getApp(), ripple::DatabaseCon::getDB(), ripple::Database::getInt(), ripple::Database::getNull(), ripple::Database::getStr(), ripple::Database::getStrBinary(), ripple::Application::getWalletDB(), ripple::RippleAddress::humanNodePublic(), ripple::UniqueNodeListImp::seedNode::iSha256, ripple::UniqueNodeListImp::seedNode::naPublicKey, ripple::ptFromSeconds(), ripple::base_uint< BITS >::SetHex(), ripple::RippleAddress::setNodePublic(), ripple::Database::startIterRows(), ripple::UniqueNodeListImp::seedNode::strComment, ripple::UniqueNodeListImp::seedNode::tpFetch, ripple::UniqueNodeListImp::seedNode::tpNext, ripple::UniqueNodeListImp::seedNode::tpScan, ripple::UniqueNodeListImp::seedNode::vsSource, and ripple::base_uint< BITS >::zero().
     {
         bool        bResult;
         Database*   db = getApp().getWalletDB ()->getDB ();
         std::string strSql  = str (boost::format ("SELECT * FROM SeedNodes WHERE PublicKey='%s';")
                                    % naNodePublic.humanNodePublic ());
         DeprecatedScopedLock sl (getApp().getWalletDB ()->getDBLock ());
         bResult = db->executeSQL (strSql) && db->startIterRows ();
         if (bResult)
         {
             std::string     strPublicKey;
             std::string     strSource;
             int             iNext;
             int             iScan;
             int             iFetch;
             std::string     strSha256;
             if (!db->getNull ("PublicKey") && db->getStr ("PublicKey", strPublicKey))
             {
                 dstSeedNode.naPublicKey.setNodePublic (strPublicKey);
             }
             else
             {
                 dstSeedNode.naPublicKey.clear ();
             }
             strSource   = db->getStrBinary ("Source");
             dstSeedNode.vsSource    = static_cast<ValidatorSource> (strSource[0]);
             iNext   = db->getInt ("Next");
             dstSeedNode.tpNext  = ptFromSeconds (iNext);
             iScan   = db->getInt ("Scan");
             dstSeedNode.tpScan  = ptFromSeconds (iScan);
             iFetch  = db->getInt ("Fetch");
             dstSeedNode.tpFetch = ptFromSeconds (iFetch);
             if (!db->getNull ("Sha256") && db->getStr ("Sha256", strSha256))
             {
                 dstSeedNode.iSha256.SetHex (strSha256);
             }
             else
             {
                 dstSeedNode.iSha256.zero ();
             }
             dstSeedNode.strComment  = db->getStrBinary ("Comment");
             db->endIterRows ();
         }
         return bResult;
     }
Json::Value ripple::UniqueNodeListImp::getUnlJson () inline virtual
Implements ripple::UniqueNodeList.
Definition at line 581 of file UniqueNodeList.cpp.
References Json::Value::append(), Json::arrayValue, db, ripple::getApp(), ripple::DatabaseCon::getDB(), ripple::Database::getStrBinary(), ripple::Application::getWalletDB(), Json::objectValue, and SQL_FOREACH.
     {
         Database* db = getApp().getWalletDB ()->getDB ();
         Json::Value ret (Json::arrayValue);
         DeprecatedScopedLock sl (getApp().getWalletDB ()->getDBLock ());
         SQL_FOREACH (db, "SELECT * FROM TrustedNodes;")
         {
             Json::Value node (Json::objectValue);
             node["publicKey"]   = db->getStrBinary ("PublicKey");
             node["comment"]     = db->getStrBinary ("Comment");
             ret.append (node);
         }
         return ret;
     }
void ripple::UniqueNodeListImp::getValidatorsUrl (const RippleAddress & naNodePublic, Section secSite) inline private
Definition at line 1432 of file UniqueNodeList.cpp.
References BIND_TYPE, ripple::HTTPClient::get(), ripple::getApp(), NODE_FETCH_SECONDS, NODE_FILE_BYTES_MAX, P_1, P_2, P_3, ripple::parseUrl(), responseValidators(), SECTION_VALIDATORS_URL, and ripple::SectionSingleB().
     {
         std::string strValidatorsUrl;
         std::string strScheme;
         std::string strDomain;
         int         iPort;
         std::string strPath;
         if (SectionSingleB (secSite, SECTION_VALIDATORS_URL, strValidatorsUrl)
                 && !strValidatorsUrl.empty ()
                 && parseUrl (strValidatorsUrl, strScheme, strDomain, iPort, strPath)
                 && -1 == iPort
                 && strScheme == "https")
         {
             HTTPClient::get (
                 true,
                 getApp().getIOService (),
                 strDomain,
                 443,
                 strPath,
                 NODE_FILE_BYTES_MAX,
                 boost::posix_time::seconds (NODE_FETCH_SECONDS),
                 BIND_TYPE (&UniqueNodeListImp::responseValidators, this, strValidatorsUrl, naNodePublic, secSite, strDomain, P_1, P_2, P_3));
         }
         else
         {
             getIpsUrl (naNodePublic, secSite);
         }
     }
int ripple::UniqueNodeListImp::iSourceScore (ValidatorSource vsWhy) inline virtual
Implements ripple::UniqueNodeList.
Definition at line 604 of file UniqueNodeList.cpp.
     {
         int     iScore  = 0;
         switch (vsWhy)
         {
         case vsConfig:
             iScore  = 1500;
             break;
         case vsInbound:
             iScore  =    0;
             break;
         case vsManual:
             iScore  = 1500;
             break;
         case vsReferral:
             iScore  =    0;
             break;
         case vsTold:
             iScore  =    0;
             break;
         case vsValidator:
             iScore  = 1000;
             break;
         case vsWeb:
             iScore  =  200;
             break;
         default:
             throw std::runtime_error ("Internal error: bad ValidatorSource.");
         }
         return iScore;
     }
bool ripple::UniqueNodeListImp::miscLoad () inline private
Definition at line 648 of file UniqueNodeList.cpp.
References db, ripple::Database::endIterRows(), ripple::Database::executeSQL(), ripple::getApp(), ripple::DatabaseCon::getDB(), ripple::Database::getInt(), ripple::Application::getWalletDB(), ripple::ptFromSeconds(), and ripple::Database::startIterRows().
     {
         DeprecatedScopedLock sl (getApp().getWalletDB ()->getDBLock ());
         Database* db = getApp().getWalletDB ()->getDB ();
         if (!db->executeSQL ("SELECT * FROM Misc WHERE Magic=1;")) return false;
         bool    bAvail  = !!db->startIterRows ();
         mtpFetchUpdated = ptFromSeconds (bAvail ? db->getInt ("FetchUpdated") : -1);
         mtpScoreUpdated = ptFromSeconds (bAvail ? db->getInt ("ScoreUpdated") : -1);
         db->endIterRows ();
         trustedLoad ();
         return true;
     }
bool ripple::UniqueNodeListImp::miscSave () inline private
Definition at line 670 of file UniqueNodeList.cpp.
References db, ripple::Database::executeSQL(), ripple::getApp(), ripple::DatabaseCon::getDB(), ripple::Application::getWalletDB(), and ripple::iToSeconds().
     {
         Database*   db = getApp().getWalletDB ()->getDB ();
         DeprecatedScopedLock sl (getApp().getWalletDB ()->getDBLock ());
         db->executeSQL (str (boost::format ("REPLACE INTO Misc (Magic,FetchUpdated,ScoreUpdated) VALUES (1,%d,%d);")
                              % iToSeconds (mtpFetchUpdated)
                              % iToSeconds (mtpScoreUpdated)));
         return true;
     }
void ripple::UniqueNodeListImp::nodeAddDomain (std::string strDomain, ValidatorSource vsWhy, const std::string & strComment) inline virtual
Implements ripple::UniqueNodeList.
Definition at line 229 of file UniqueNodeList.cpp.
References ripple::UniqueNodeListImp::seedDomain::strComment, ripple::UniqueNodeListImp::seedDomain::strDomain, ripple::UniqueNodeListImp::seedDomain::tpNext, and ripple::UniqueNodeListImp::seedDomain::vsSource.
     {
         boost::trim (strDomain);
         boost::to_lower (strDomain);
         // YYY Would be best to verify strDomain is a valid domain.
         // WriteLog (lsTRACE) << str(boost::format("nodeAddDomain: '%s' %c '%s'")
         //  % strDomain
         //  % vsWhy
         //  % strComment);
         seedDomain  sdCurrent;
         bool        bFound      = getSeedDomains (strDomain, sdCurrent);
         bool        bChanged    = false;
         if (!bFound)
         {
             sdCurrent.strDomain     = strDomain;
             sdCurrent.tpNext        = boost::posix_time::second_clock::universal_time ();
         }
         // Promote source, if needed.
         if (!bFound || iSourceScore (vsWhy) >= iSourceScore (sdCurrent.vsSource))
         {
             sdCurrent.vsSource      = vsWhy;
             sdCurrent.strComment    = strComment;
             bChanged                = true;
         }
         if (vsManual == vsWhy)
         {
             // A manual add forces immediate scan.
             sdCurrent.tpNext        = boost::posix_time::second_clock::universal_time ();
             bChanged                = true;
         }
         if (bChanged)
             setSeedDomains (sdCurrent, true);
     }
void ripple::UniqueNodeListImp::nodeAddPublic (const RippleAddress & naNodePublic, ValidatorSource vsWhy, const std::string & strComment) inline virtual
Implements ripple::UniqueNodeList.
Definition at line 192 of file UniqueNodeList.cpp.
References ripple::UniqueNodeListImp::seedNode::naPublicKey, ripple::UniqueNodeListImp::seedNode::strComment, ripple::UniqueNodeListImp::seedNode::tpNext, and ripple::UniqueNodeListImp::seedNode::vsSource.
     {
         seedNode    snCurrent;
         bool        bFound      = getSeedNodes (naNodePublic, snCurrent);
         bool        bChanged    = false;
         if (!bFound)
         {
             snCurrent.naPublicKey   = naNodePublic;
             snCurrent.tpNext        = boost::posix_time::second_clock::universal_time ();
         }
         // Promote source, if needed.
         if (!bFound /*|| iSourceScore (vsWhy) >= iSourceScore (snCurrent.vsSource)*/)
         {
             snCurrent.vsSource      = vsWhy;
             snCurrent.strComment    = strComment;
             bChanged                = true;
         }
         if (vsManual == vsWhy)
         {
             // A manual add forces immediate scan.
             snCurrent.tpNext        = boost::posix_time::second_clock::universal_time ();
             bChanged                = true;
         }
         if (bChanged)
             setSeedNodes (snCurrent, true);
     }
void ripple::UniqueNodeListImp::nodeBootstrap () inline virtual
Implements ripple::UniqueNodeList.
Definition at line 441 of file UniqueNodeList.cpp.
References db, ripple::Database::endIterRows(), ripple::Database::executeSQL(), ripple::getApp(), ripple::getConfig(), ripple::DatabaseCon::getDB(), ripple::Database::getInt(), ripple::Application::getWalletDB(), ripple::lsINFO, ripple::Database::startIterRows(), ripple::Config::validators, and WriteLog.
     {
         int         iDomains    = 0;
         int         iNodes      = 0;
 #if 0
         {
             DeprecatedScopedLock sl (getApp().getWalletDB ()->getDBLock ());
             Database* db = getApp().getWalletDB ()->getDB ();
             if (db->executeSQL (str (boost::format ("SELECT COUNT(*) AS Count FROM SeedDomains WHERE Source='%s' OR Source='%c';") % vsManual % vsValidator)) && db->startIterRows ())
                 iDomains    = db->getInt ("Count");
             db->endIterRows ();
             if (db->executeSQL (str (boost::format ("SELECT COUNT(*) AS Count FROM SeedNodes WHERE Source='%s' OR Source='%c';") % vsManual % vsValidator)) && db->startIterRows ())
                 iNodes      = db->getInt ("Count");
             db->endIterRows ();
         }
 #endif
         bool    bLoaded = iDomains || iNodes;
         // Always merge in the file specified in the config.
         if (!getConfig ().VALIDATORS_FILE.empty ())
         {
             WriteLog (lsINFO, UniqueNodeList) << "Bootstrapping UNL: loading from unl_default.";
             bLoaded = nodeLoad (getConfig ().VALIDATORS_FILE);
         }
         // If never loaded anything try the current directory.
         if (!bLoaded && getConfig ().VALIDATORS_FILE.empty ())
         {
             WriteLog (lsINFO, UniqueNodeList) << boost::str (boost::format ("Bootstrapping UNL: loading from '%s'.")
                                               % getConfig ().VALIDATORS_BASE);
             bLoaded = nodeLoad (getConfig ().VALIDATORS_BASE);
         }
         // Always load from rippled.cfg
         if (!getConfig ().validators.empty ())
         {
             RippleAddress   naInvalid;  // Don't want a referrer on added entries.
             WriteLog (lsINFO, UniqueNodeList) << boost::str (boost::format ("Bootstrapping UNL: loading from '%s'.")
                                               % getConfig ().CONFIG_FILE);
             if (processValidators ("local", getConfig ().CONFIG_FILE.string (), naInvalid, vsConfig, &getConfig ().validators))
                 bLoaded = true;
         }
         if (!bLoaded)
         {
             WriteLog (lsINFO, UniqueNodeList) << boost::str (boost::format ("Bootstrapping UNL: loading from '%s'.")
                                               % getConfig ().VALIDATORS_SITE);
             nodeNetwork ();
         }
     }
bool ripple::UniqueNodeListImp::nodeInCluster (const RippleAddress & naNodePublic) inline virtual
Implements ripple::UniqueNodeList.
Definition at line 343 of file UniqueNodeList.cpp.
     {
         ScopedUNLLockType sl (mUNLLock);
         return m_clusterNodes.end () != m_clusterNodes.find (naNodePublic);
     }
bool ripple::UniqueNodeListImp::nodeInCluster (const RippleAddress & naNodePublic, std::string & name) inline virtual
Implements ripple::UniqueNodeList.
Definition at line 351 of file UniqueNodeList.cpp.
     {
         ScopedUNLLockType sl (mUNLLock);
         std::map<RippleAddress, ClusterNodeStatus>::iterator it = m_clusterNodes.find (naNodePublic);
         if (it == m_clusterNodes.end ())
             return false;
         name = it->second.getName();
         return true;
     }
bool ripple::UniqueNodeListImp::nodeInUNL (const RippleAddress & naNodePublic) inline virtual
Implements ripple::UniqueNodeList.
Definition at line 334 of file UniqueNodeList.cpp.
References ripple::RippleAddress::humanNodePublic().
     {
         ScopedUNLLockType sl (mUNLLock);
         return mUNL.end () != mUNL.find (naNodePublic.humanNodePublic ());
     }
bool ripple::UniqueNodeListImp::nodeLoad (boost::filesystem::path pConfig) inline virtual
Implements ripple::UniqueNodeList.
Definition at line 505 of file UniqueNodeList.cpp.
References ripple::Config::Helpers::getValidatorsFileName(), Json::in(), ripple::lsFATAL, ripple::lsINFO, ripple::lsTRACE, ripple::lsWARNING, and WriteLog.
     {
         if (pConfig.empty ())
         {
             WriteLog (lsINFO, UniqueNodeList) << Config::Helpers::getValidatorsFileName() <<
                 " path not specified.";
             return false;
         }
         if (!boost::filesystem::exists (pConfig))
         {
             WriteLog (lsWARNING, UniqueNodeList) << Config::Helpers::getValidatorsFileName() <<
                 " not found: " << pConfig;
             return false;
         }
         if (!boost::filesystem::is_regular_file (pConfig))
         {
             WriteLog (lsWARNING, UniqueNodeList) << Config::Helpers::getValidatorsFileName() <<
                 " not regular file: " << pConfig;
             return false;
         }
         std::ifstream   ifsDefault (pConfig.native ().c_str (), std::ios::in);
         if (!ifsDefault)
         {
             WriteLog (lsFATAL, UniqueNodeList) << Config::Helpers::getValidatorsFileName() <<
                 " failed to open: " << pConfig;
             return false;
         }
         std::string     strValidators;
         strValidators.assign ((std::istreambuf_iterator<char> (ifsDefault)),
                               std::istreambuf_iterator<char> ());
         if (ifsDefault.bad ())
         {
             WriteLog (lsFATAL, UniqueNodeList) << Config::Helpers::getValidatorsFileName() <<
             "Failed to read: " << pConfig;
             return false;
         }
         nodeProcess ("local", strValidators, pConfig.string ());
         WriteLog (lsTRACE, UniqueNodeList) << str (boost::format ("Processing: %s") % pConfig);
         return true;
     }
void ripple::UniqueNodeListImp::nodeNetwork () inline virtual
Implements ripple::UniqueNodeList.
Definition at line 563 of file UniqueNodeList.cpp.
References BIND_TYPE, ripple::HTTPClient::get(), ripple::getApp(), ripple::getConfig(), P_1, P_2, P_3, VALIDATORS_FETCH_SECONDS, VALIDATORS_FILE_BYTES_MAX, and validatorsResponse().
     {
         if (!getConfig ().VALIDATORS_SITE.empty ())
         {
             HTTPClient::get (
                 true,
                 getApp().getIOService (),
                 getConfig ().VALIDATORS_SITE,
                 443,
                 getConfig ().VALIDATORS_URI,
                 VALIDATORS_FILE_BYTES_MAX,
                 boost::posix_time::seconds (VALIDATORS_FETCH_SECONDS),
                 BIND_TYPE (&UniqueNodeListImp::validatorsResponse, this, P_1, P_2, P_3));
         }
     }
void ripple::UniqueNodeListImp::nodeProcess (const std::string & strSite, const std::string & strValidators, const std::string & strSource) inline private
Definition at line 1988 of file UniqueNodeList.cpp.
References ripple::getConfig(), ripple::lsWARNING, ripple::ParseSection(), SECTION_VALIDATORS, ripple::SectionEntries(), and WriteLog.
     {
         Section secValidators   = ParseSection (strValidators, true);
         Section::mapped_type*   pmtEntries  = SectionEntries (secValidators, SECTION_VALIDATORS);
         if (pmtEntries)
         {
             RippleAddress   naInvalid;  // Don't want a referrer on added entries.
             // YYY Unspecified might be bootstrap or rpc command
             processValidators (strSite, strSource, naInvalid, vsValidator, pmtEntries);
         }
         else
         {
             WriteLog (lsWARNING, UniqueNodeList) << boost::str (boost::format ("'%s' missing [" SECTION_VALIDATORS "].")
                                                  % getConfig ().VALIDATORS_BASE);
         }
     }
void ripple::UniqueNodeListImp::nodeRemoveDomain (std::string strDomain) inline virtual
Implements ripple::UniqueNodeList.
Definition at line 291 of file UniqueNodeList.cpp.
References db, ripple::Database::executeSQL(), ripple::getApp(), ripple::DatabaseCon::getDB(), ripple::Application::getWalletDB(), and ripple::sqlEscape().
     {
         boost::trim (strDomain);
         boost::to_lower (strDomain);
         {
             Database* db = getApp().getWalletDB ()->getDB ();
             DeprecatedScopedLock sl (getApp().getWalletDB ()->getDBLock ());
             db->executeSQL (str (boost::format ("DELETE FROM SeedDomains WHERE Domain=%s") % sqlEscape (strDomain)));
         }
         // YYY Only dirty on successful delete.
         fetchDirty ();
     }
void ripple::UniqueNodeListImp::nodeRemovePublic (const RippleAddress & naNodePublic) inline virtual
Implements ripple::UniqueNodeList.
Definition at line 272 of file UniqueNodeList.cpp.
References db, ripple::Database::executeSQL(), ripple::getApp(), ripple::DatabaseCon::getDB(), ripple::Application::getWalletDB(), ripple::RippleAddress::humanNodePublic(), and ripple::sqlEscape().
     {
         {
             Database* db = getApp().getWalletDB ()->getDB ();
             DeprecatedScopedLock sl (getApp().getWalletDB ()->getDBLock ());
             db->executeSQL (str (boost::format ("DELETE FROM SeedNodes WHERE PublicKey=%s") % sqlEscape (naNodePublic.humanNodePublic ())));
             db->executeSQL (str (boost::format ("DELETE FROM TrustedNodes WHERE PublicKey=%s") % sqlEscape (naNodePublic.humanNodePublic ())));
         }
         // YYY Only dirty on successful delete.
         fetchDirty ();
         ScopedUNLLockType sl (mUNLLock);
         mUNL.erase (naNodePublic.humanNodePublic ());
     }
void ripple::UniqueNodeListImp::nodeReset () inline virtual
Implements ripple::UniqueNodeList.
Definition at line 309 of file UniqueNodeList.cpp.
References db, ripple::Database::executeSQL(), ripple::getApp(), ripple::DatabaseCon::getDB(), and ripple::Application::getWalletDB().
     {
         {
             Database* db = getApp().getWalletDB ()->getDB ();
             DeprecatedScopedLock sl (getApp().getWalletDB ()->getDBLock ());
             // XXX Check results.
             db->executeSQL ("DELETE FROM SeedDomains");
             db->executeSQL ("DELETE FROM SeedNodes");
         }
         fetchDirty ();
     }
void ripple::UniqueNodeListImp::nodeScore () inline virtual
Implements ripple::UniqueNodeList.
Definition at line 327 of file UniqueNodeList.cpp.
     {
         scoreNext (true);
     }
bool ripple::UniqueNodeListImp::nodeUpdate (const RippleAddress & naNodePublic, ClusterNodeStatus const & cnsStatus) inline virtual
Implements ripple::UniqueNodeList.
Definition at line 365 of file UniqueNodeList.cpp.
     {
         ScopedUNLLockType sl (mUNLLock);
         return m_clusterNodes[naNodePublic].update(cnsStatus);
     }
void ripple::UniqueNodeListImp::onDeadlineTimer (beast::DeadlineTimer & timer) inline virtual
Reimplemented from beast::DeadlineTimer::Listener.
Definition at line 160 of file UniqueNodeList.cpp.
References ripple::JobQueue::addJob(), BIND_TYPE, doFetch(), doScore(), ripple::getApp(), ripple::Application::getJobQueue(), and ripple::jtUNL.
     {
         if (timer == m_scoreTimer)
         {
             getApp().getJobQueue ().addJob (jtUNL, "UNL.score",
                 BIND_TYPE (&UniqueNodeListImp::doScore, this));
         }
         else if (timer == m_fetchTimer)
         {
             getApp().getJobQueue ().addJob (jtUNL, "UNL.fetch",
                 BIND_TYPE (&UniqueNodeListImp::doFetch, this));
         }
     }
void ripple::UniqueNodeListImp::onStop () inline virtual
Override called when the stop notification is issued.
The call is made on an unspecified, implementation-specific thread. onStop and onChildrenStopped will never be called concurrently, across all Stoppable objects descended from the same root, inclusive of the root.
It is safe to call isStopping, isStopped, and areChildrenStopped from within this function; The values returned will always be valid and never change during the callback.
The default implementation simply calls stopped(). This is applicable when the Stoppable has a trivial stop operation (or no stop operation), and we are merely using the Stoppable API to position it as a dependency of some parent service.
Thread safety: May not block for long periods. Guaranteed only to be called once. Must be safe to call from any thread at any time.
Reimplemented from beast::Stoppable.
Definition at line 122 of file UniqueNodeList.cpp.
     {
         m_fetchTimer.cancel ();
         m_scoreTimer.cancel ();
         stopped ();
     }
void ripple::UniqueNodeListImp::processFile (const std::string & strDomain, const RippleAddress & naNodePublic, Section secSite) inline private
Definition at line 1717 of file UniqueNodeList.cpp.
References ripple::lsWARNING, NODE_FILE_NAME, SECTION_CURRENCIES, SECTION_IPS, SECTION_VALIDATORS, ripple::SectionEntries(), and WriteLog.
     {
         //
         // Process Validators
         //
         processValidators (strDomain, NODE_FILE_NAME, naNodePublic, vsReferral, SectionEntries (secSite, SECTION_VALIDATORS));
         //
         // Process ips
         //
         processIps (strDomain, naNodePublic, SectionEntries (secSite, SECTION_IPS));
         //
         // Process currencies
         //
         Section::mapped_type*   pvCurrencies;
         if ((pvCurrencies = SectionEntries (secSite, SECTION_CURRENCIES)) && pvCurrencies->size ())
         {
             // XXX Process currencies.
             WriteLog (lsWARNING, UniqueNodeList) << "Ignoring currencies: not implemented.";
         }
         getValidatorsUrl (naNodePublic, secSite);
     }
void ripple::UniqueNodeListImp::processIps (const std::string & strSite, const RippleAddress & naNodePublic, Section::mapped_type * pmtVecStrIps) inline private
Definition at line 1545 of file UniqueNodeList.cpp.
References db, ripple::Database::executeSQL(), ripple::getApp(), ripple::DatabaseCon::getDB(), ripple::Application::getWalletDB(), ripple::RippleAddress::humanNodePublic(), ripple::lsDEBUG, ripple::lsTRACE, ripple::min(), ripple::parseIpPort(), REFERRAL_IPS_MAX, REFERRAL_VALIDATORS_MAX, SECTION_IPS, ripple::sqlEscape(), ripple::strJoin(), and WriteLog.
     {
         Database*   db = getApp().getWalletDB ()->getDB ();
         std::string strEscNodePublic    = sqlEscape (naNodePublic.humanNodePublic ());
         WriteLog (lsDEBUG, UniqueNodeList)
                 << str (boost::format ("Validator: '%s' processing %d ips.")
                         % strSite % ( pmtVecStrIps ? pmtVecStrIps->size () : 0));
         // Remove all current Validator's entries in IpReferrals
         {
             DeprecatedScopedLock sl (getApp().getWalletDB ()->getDBLock ());
             db->executeSQL (str (boost::format ("DELETE FROM IpReferrals WHERE Validator=%s;") % strEscNodePublic));
             // XXX Check result.
         }
         // Add new referral entries.
         if (pmtVecStrIps && !pmtVecStrIps->empty ())
         {
             std::vector<std::string>    vstrValues;
             vstrValues.resize (std::min ((int) pmtVecStrIps->size (), REFERRAL_IPS_MAX));
             int iValues = 0;
             BOOST_FOREACH (const std::string & strReferral, *pmtVecStrIps)
             {
                 if (iValues == REFERRAL_VALIDATORS_MAX)
                     break;
                 std::string     strIP;
                 int             iPort;
                 bool            bValid  = parseIpPort (strReferral, strIP, iPort);
                 // XXX Filter out private network ips.
                 // XXX http://en.wikipedia.org/wiki/Private_network
                 if (bValid)
                 {
                     vstrValues[iValues] = str (boost::format ("(%s,%d,%s,%d)")
                                                % strEscNodePublic % iValues % sqlEscape (strIP) % iPort);
                     iValues++;
                 }
                 else
                 {
                     WriteLog (lsTRACE, UniqueNodeList)
                             << str (boost::format ("Validator: '%s' [" SECTION_IPS "]: rejecting '%s'")
                                     % strSite % strReferral);
                 }
             }
             if (iValues)
             {
                 vstrValues.resize (iValues);
                 DeprecatedScopedLock sl (getApp().getWalletDB ()->getDBLock ());
                 db->executeSQL (str (boost::format ("INSERT INTO IpReferrals (Validator,Entry,IP,Port) VALUES %s;")
                                      % strJoin (vstrValues.begin (), vstrValues.end (), ",")));
                 // XXX Check result.
             }
         }
         fetchDirty ();
     }
int ripple::UniqueNodeListImp::processValidators (const std::string & strSite, const std::string & strValidatorsSrc, const RippleAddress & naNodePublic, ValidatorSource vsWhy, Section::mapped_type * pmtVecStrValidators) inline private
Definition at line 1617 of file UniqueNodeList.cpp.
References db, ripple::Database::executeSQL(), ripple::getApp(), ripple::DatabaseCon::getDB(), ripple::Application::getWalletDB(), ripple::RippleAddress::humanNodePublic(), ripple::RippleAddress::isValid(), ripple::lsINFO, ripple::lsTRACE, ripple::lsWARNING, ripple::min(), REFERRAL_VALIDATORS_MAX, ripple::RippleAddress::setNodePublic(), ripple::RippleAddress::setSeedGeneric(), ripple::sqlEscape(), ripple::strJoin(), and WriteLog.
     {
         Database*   db              = getApp().getWalletDB ()->getDB ();
         std::string strNodePublic   = naNodePublic.isValid () ? naNodePublic.humanNodePublic () : strValidatorsSrc;
         int         iValues         = 0;
         WriteLog (lsTRACE, UniqueNodeList)
                 << str (boost::format ("Validator: '%s' : '%s' : processing %d validators.")
                         % strSite
                         % strValidatorsSrc
                         % ( pmtVecStrValidators ? pmtVecStrValidators->size () : 0));
         // Remove all current Validator's entries in ValidatorReferrals
         {
             DeprecatedScopedLock sl (getApp().getWalletDB ()->getDBLock ());
             db->executeSQL (str (boost::format ("DELETE FROM ValidatorReferrals WHERE Validator='%s';") % strNodePublic));
             // XXX Check result.
         }
         // Add new referral entries.
         if (pmtVecStrValidators && pmtVecStrValidators->size ())
         {
             std::vector<std::string> vstrValues;
             vstrValues.reserve (std::min ((int) pmtVecStrValidators->size (), REFERRAL_VALIDATORS_MAX));
             BOOST_FOREACH (const std::string & strReferral, *pmtVecStrValidators)
             {
                 if (iValues == REFERRAL_VALIDATORS_MAX)
                     break;
                 boost::smatch   smMatch;
                 // domain comment?
                 // public_key comment?
                 static boost::regex reReferral ("\\`\\s*(\\S+)(?:\\s+(.+))?\\s*\\'");
                 if (!boost::regex_match (strReferral, smMatch, reReferral))
                 {
                     WriteLog (lsWARNING, UniqueNodeList) << str (boost::format ("Bad validator: syntax error: %s: %s") % strSite % strReferral);
                 }
                 else
                 {
                     std::string     strRefered  = smMatch[1];
                     std::string     strComment  = smMatch[2];
                     RippleAddress   naValidator;
                     if (naValidator.setSeedGeneric (strRefered))
                     {
                         WriteLog (lsWARNING, UniqueNodeList) << str (boost::format ("Bad validator: domain or public key required: %s %s") % strRefered % strComment);
                     }
                     else if (naValidator.setNodePublic (strRefered))
                     {
                         // A public key.
                         // XXX Schedule for CAS lookup.
                         nodeAddPublic (naValidator, vsWhy, strComment);
                         WriteLog (lsINFO, UniqueNodeList) << str (boost::format ("Node Public: %s %s") % strRefered % strComment);
                         if (naNodePublic.isValid ())
                             vstrValues.push_back (str (boost::format ("('%s',%d,'%s')") % strNodePublic % iValues % naValidator.humanNodePublic ()));
                         iValues++;
                     }
                     else
                     {
                         // A domain: need to look it up.
                         nodeAddDomain (strRefered, vsWhy, strComment);
                         WriteLog (lsINFO, UniqueNodeList) << str (boost::format ("Node Domain: %s %s") % strRefered % strComment);
                         if (naNodePublic.isValid ())
                             vstrValues.push_back (str (boost::format ("('%s',%d,%s)") % strNodePublic % iValues % sqlEscape (strRefered)));
                         iValues++;
                     }
                 }
             }
             if (!vstrValues.empty ())
             {
                 std::string strSql  = str (boost::format ("INSERT INTO ValidatorReferrals (Validator,Entry,Referral) VALUES %s;")
                                            % strJoin (vstrValues.begin (), vstrValues.end (), ","));
                 DeprecatedScopedLock sl (getApp().getWalletDB ()->getDBLock ());
                 db->executeSQL (strSql);
                 // XXX Check result.
             }
         }
         fetchDirty ();
         return iValues;
     }
bool ripple::UniqueNodeListImp::responseFetch (const std::string & strDomain, const boost::system::error_code & err, int iStatus, const std::string & strSiteFile) inline private
Definition at line 1151 of file UniqueNodeList.cpp.
References ripple::Serializer::getSHA512Half(), ripple::UniqueNodeListImp::seedDomain::iSha256, ripple::lsTRACE, ripple::UniqueNodeListImp::seedDomain::naPublicKey, NODE_FILE_NAME, ripple::ParseSection(), SECTION_DOMAIN, SECTION_PUBLIC_KEY, ripple::SectionSingleB(), ripple::RippleAddress::setNodePublic(), ripple::UniqueNodeListImp::seedDomain::strDomain, ripple::UniqueNodeListImp::seedDomain::tpFetch, and WriteLog.
Referenced by fetchProcess().
     {
         bool    bReject = !err && iStatus != 200;
         if (!bReject)
         {
             Section             secSite = ParseSection (strSiteFile, true);
             bool                bGood   = !err;
             if (bGood)
             {
                 WriteLog (lsTRACE, UniqueNodeList) << boost::format ("Validator: '%s' received " NODE_FILE_NAME ".") % strDomain;
             }
             else
             {
                 WriteLog (lsTRACE, UniqueNodeList)
                         << boost::format ("Validator: '%s' unable to retrieve " NODE_FILE_NAME ": %s")
                         % strDomain
                         % err.message ();
             }
             //
             // Verify file domain
             //
             std::string strSite;
             if (bGood && !SectionSingleB (secSite, SECTION_DOMAIN, strSite))
             {
                 bGood   = false;
                 WriteLog (lsTRACE, UniqueNodeList)
                         << boost::format ("Validator: '%s' bad " NODE_FILE_NAME " missing single entry for " SECTION_DOMAIN ".")
                         % strDomain;
             }
             if (bGood && strSite != strDomain)
             {
                 bGood   = false;
                 WriteLog (lsTRACE, UniqueNodeList)
                         << boost::format ("Validator: '%s' bad " NODE_FILE_NAME " " SECTION_DOMAIN " does not match: %s")
                         % strDomain
                         % strSite;
             }
             //
             // Process public key
             //
             std::string     strNodePublicKey;
             if (bGood && !SectionSingleB (secSite, SECTION_PUBLIC_KEY, strNodePublicKey))
             {
                 // Bad [validation_public_key] Section.
                 bGood   = false;
                 WriteLog (lsTRACE, UniqueNodeList)
                         << boost::format ("Validator: '%s' bad " NODE_FILE_NAME " " SECTION_PUBLIC_KEY " does not have single entry.")
                         % strDomain;
             }
             RippleAddress   naNodePublic;
             if (bGood && !naNodePublic.setNodePublic (strNodePublicKey))
             {
                 // Bad public key.
                 bGood   = false;
                 WriteLog (lsTRACE, UniqueNodeList)
                         << boost::format ("Validator: '%s' bad " NODE_FILE_NAME " " SECTION_PUBLIC_KEY " is bad: ")
                         % strDomain
                         % strNodePublicKey;
             }
             if (bGood)
             {
                 // WriteLog (lsTRACE, UniqueNodeList) << boost::format("naNodePublic: '%s'") % naNodePublic.humanNodePublic();
                 seedDomain  sdCurrent;
                 bool        bFound      = getSeedDomains (strDomain, sdCurrent);
                 assert (bFound);
                 uint256     iSha256     = Serializer::getSHA512Half (strSiteFile);
                 bool        bChangedB   = sdCurrent.iSha256 != iSha256;
                 sdCurrent.strDomain     = strDomain;
                 // XXX If the node public key is changing, delete old public key information?
                 // XXX Only if no other refs to keep it arround, other wise we have an attack vector.
                 sdCurrent.naPublicKey   = naNodePublic;
                 // WriteLog (lsTRACE, UniqueNodeList) << boost::format("sdCurrent.naPublicKey: '%s'") % sdCurrent.naPublicKey.humanNodePublic();
                 sdCurrent.tpFetch       = boost::posix_time::second_clock::universal_time ();
                 sdCurrent.iSha256       = iSha256;
                 setSeedDomains (sdCurrent, true);
                 if (bChangedB)
                 {
                     WriteLog (lsTRACE, UniqueNodeList) << boost::format ("Validator: '%s' processing new " NODE_FILE_NAME ".") % strDomain;
                     processFile (strDomain, naNodePublic, secSite);
                 }
                 else
                 {
                     WriteLog (lsTRACE, UniqueNodeList) << boost::format ("Validator: '%s' no change for " NODE_FILE_NAME ".") % strDomain;
                     fetchFinish ();
                 }
             }
             else
             {
                 // Failed: Update
                 // XXX If we have public key, perhaps try look up in CAS?
                 fetchFinish ();
             }
         }
         return bReject;
     }
bool ripple::UniqueNodeListImp::responseIps (const std::string & strSite, const RippleAddress & naNodePublic, const boost::system::error_code & err, int iStatus, const std::string & strIpsFile) inline private
Definition at line 1500 of file UniqueNodeList.cpp.
References ripple::ParseSection(), SECTION_IPS, and ripple::SectionEntries().
Referenced by getIpsUrl().
     {
         bool    bReject = !err && iStatus != 200;
         if (!bReject)
         {
             if (!err)
             {
                 Section         secFile     = ParseSection (strIpsFile, true);
                 processIps (strSite, naNodePublic, SectionEntries (secFile, SECTION_IPS));
             }
             fetchFinish ();
         }
         return bReject;
     }
bool ripple::UniqueNodeListImp::responseValidators (const std::string & strValidatorsUrl, const RippleAddress & naNodePublic, Section secSite, const std::string & strSite, const boost::system::error_code & err, int iStatus, const std::string & strValidatorsFile) inline private
Definition at line 1520 of file UniqueNodeList.cpp.
References ripple::ParseSection(), SECTION_VALIDATORS, and ripple::SectionEntries().
Referenced by getValidatorsUrl().
     {
         bool    bReject = !err && iStatus != 200;
         if (!bReject)
         {
             if (!err)
             {
                 Section     secFile     = ParseSection (strValidatorsFile, true);
                 processValidators (strSite, strValidatorsUrl, naNodePublic, vsValidator, SectionEntries (secFile, SECTION_VALIDATORS));
             }
             getIpsUrl (naNodePublic, secSite);
         }
         return bReject;
     }
void ripple::UniqueNodeListImp::scoreCompute () inline private
Definition at line 793 of file UniqueNodeList.cpp.
References db, ripple::Database::executeSQL(), ripple::getApp(), ripple::DatabaseCon::getDB(), ripple::Database::getInt(), ripple::Database::getNull(), ripple::Database::getStrBinary(), ripple::Application::getWalletDB(), ripple::UniqueNodeListImp::scoreNode::iRoundScore, ripple::UniqueNodeListImp::scoreNode::iRoundSeed, ripple::UniqueNodeListImp::scoreNode::iScore, ripple::UniqueNodeListImp::scoreNode::iSeen, ripple::lsTRACE, nothing, SCORE_ROUNDS, ripple::RippleAddress::setNodePublic(), ShouldLog, SQL_FOREACH, ripple::sqlEscape(), ripple::strJoin(), ripple::UniqueNodeListImp::scoreNode::strValidator, ripple::UniqueNodeListImp::scoreNode::viReferrals, and WriteLog.
     {
         strIndex                umPulicIdx;     // Map of public key to index.
         strIndex                umDomainIdx;    // Map of domain to index.
         std::vector<scoreNode>  vsnNodes;       // Index to scoring node.
         Database*   db = getApp().getWalletDB ()->getDB ();
         // For each entry in SeedDomains with a PublicKey:
         // - Add an entry in umPulicIdx, umDomainIdx, and vsnNodes.
         {
             DeprecatedScopedLock sl (getApp().getWalletDB ()->getDBLock ());
             SQL_FOREACH (db, "SELECT Domain,PublicKey,Source FROM SeedDomains;")
             {
                 if (db->getNull ("PublicKey"))
                 {
                     nothing (); // We ignore entries we don't have public keys for.
                 }
                 else
                 {
                     std::string strDomain       = db->getStrBinary ("Domain");
                     std::string strPublicKey    = db->getStrBinary ("PublicKey");
                     std::string strSource       = db->getStrBinary ("Source");
                     int         iScore          = iSourceScore (static_cast<ValidatorSource> (strSource[0]));
                     strIndex::iterator  siOld   = umPulicIdx.find (strPublicKey);
                     if (siOld == umPulicIdx.end ())
                     {
                         // New node
                         int         iNode       = vsnNodes.size ();
                         umPulicIdx[strPublicKey]    = iNode;
                         umDomainIdx[strDomain]      = iNode;
                         scoreNode   snCurrent;
                         snCurrent.strValidator  = strPublicKey;
                         snCurrent.iScore        = iScore;
                         snCurrent.iRoundSeed    = snCurrent.iScore;
                         snCurrent.iRoundScore   = 0;
                         snCurrent.iSeen         = -1;
                         vsnNodes.push_back (snCurrent);
                     }
                     else
                     {
                         scoreNode&  snOld   = vsnNodes[siOld->second];
                         if (snOld.iScore < iScore)
{
                             // Update old node
                             snOld.iScore        = iScore;
                             snOld.iRoundSeed    = snOld.iScore;
                         }
                     }
                 }
             }
         }
         // For each entry in SeedNodes:
         // - Add an entry in umPulicIdx, umDomainIdx, and vsnNodes.
         {
             DeprecatedScopedLock sl (getApp().getWalletDB ()->getDBLock ());
             SQL_FOREACH (db, "SELECT PublicKey,Source FROM SeedNodes;")
             {
                 std::string strPublicKey    = db->getStrBinary ("PublicKey");
                 std::string strSource       = db->getStrBinary ("Source");
                 int         iScore          = iSourceScore (static_cast<ValidatorSource> (strSource[0]));
                 strIndex::iterator  siOld   = umPulicIdx.find (strPublicKey);
                 if (siOld == umPulicIdx.end ())
                 {
                     // New node
                     int         iNode       = vsnNodes.size ();
                     umPulicIdx[strPublicKey]    = iNode;
                     scoreNode   snCurrent;
                     snCurrent.strValidator  = strPublicKey;
                     snCurrent.iScore        = iScore;
                     snCurrent.iRoundSeed    = snCurrent.iScore;
                     snCurrent.iRoundScore   = 0;
                     snCurrent.iSeen         = -1;
                     vsnNodes.push_back (snCurrent);
                 }
                 else
                 {
                     scoreNode&  snOld   = vsnNodes[siOld->second];
                     if (snOld.iScore < iScore)
                     {
                         // Update old node
                         snOld.iScore        = iScore;
                         snOld.iRoundSeed    = snOld.iScore;
                     }
                 }
             }
         }
         // For debugging, print out initial scores.
         if (ShouldLog (lsTRACE, UniqueNodeList))
         {
             BOOST_FOREACH (scoreNode & sn, vsnNodes)
             {
                 WriteLog (lsTRACE, UniqueNodeList) << str (boost::format ("%s| %d, %d, %d")
                                                    % sn.strValidator
                                                    % sn.iScore
                                                    % sn.iRoundScore
                                                    % sn.iRoundSeed);
             }
         }
         // WriteLog (lsTRACE, UniqueNodeList) << str(boost::format("vsnNodes.size=%d") % vsnNodes.size());
         // Step through growing list of nodes adding each validation list.
         // - Each validator may have provided referals.  Add those referals as validators.
         for (int iNode = 0; iNode != vsnNodes.size (); ++iNode)
         {
             scoreNode&          sn              = vsnNodes[iNode];
             std::string&        strValidator    = sn.strValidator;
             std::vector<int>&   viReferrals     = sn.viReferrals;
             DeprecatedScopedLock sl (getApp().getWalletDB ()->getDBLock ());
             SQL_FOREACH (db, boost::str (boost::format ("SELECT Referral FROM ValidatorReferrals WHERE Validator=%s ORDER BY Entry;")
                                          % sqlEscape (strValidator)))
             {
                 std::string strReferral = db->getStrBinary ("Referral");
                 int         iReferral;
                 strIndex::iterator  itEntry;
                 RippleAddress       na;
                 if (na.setNodePublic (strReferral))
                 {
                     // Referring a public key.
                     itEntry     = umPulicIdx.find (strReferral);
                     if (itEntry == umPulicIdx.end ())
                     {
                         // Not found add public key to list of nodes.
                         iReferral               = vsnNodes.size ();
                         umPulicIdx[strReferral] = iReferral;
                         scoreNode   snCurrent;
                         snCurrent.strValidator  = strReferral;
                         snCurrent.iScore        = iSourceScore (vsReferral);
                         snCurrent.iRoundSeed    = snCurrent.iScore;
                         snCurrent.iRoundScore   = 0;
                         snCurrent.iSeen         = -1;
                         vsnNodes.push_back (snCurrent);
                     }
                     else
                     {
                         iReferral   =  itEntry->second;
                     }
                     // WriteLog (lsTRACE, UniqueNodeList) << str(boost::format("%s: Public=%s iReferral=%d") % strValidator % strReferral % iReferral);
                 }
                 else
                 {
                     // Referring a domain.
                     itEntry     = umDomainIdx.find (strReferral);
                     iReferral   = itEntry == umDomainIdx.end ()
                                   ? -1            // We ignore domains we can't find entires for.
                                   : itEntry->second;
                     // WriteLog (lsTRACE, UniqueNodeList) << str(boost::format("%s: Domain=%s iReferral=%d") % strValidator % strReferral % iReferral);
                 }
                 if (iReferral >= 0 && iNode != iReferral)
                     viReferrals.push_back (iReferral);
             }
         }
         //
         // Distribute the points from the seeds.
         //
         bool    bDist   = true;
         for (int i = SCORE_ROUNDS; bDist && i--;)
             bDist   = scoreRound (vsnNodes);
         if (ShouldLog (lsTRACE, UniqueNodeList))
         {
             WriteLog (lsTRACE, UniqueNodeList) << "Scored:";
             BOOST_FOREACH (scoreNode & sn, vsnNodes)
             {
                 WriteLog (lsTRACE, UniqueNodeList) << str (boost::format ("%s| %d, %d, %d: [%s]")
                                                    % sn.strValidator
                                                    % sn.iScore
                                                    % sn.iRoundScore
                                                    % sn.iRoundSeed
                                                    % strJoin (sn.viReferrals.begin (), sn.viReferrals.end (), ","));
             }
         }
         // Persist validator scores.
         DeprecatedScopedLock sl (getApp().getWalletDB ()->getDBLock ());
         db->executeSQL ("BEGIN;");
         db->executeSQL ("UPDATE TrustedNodes SET Score = 0 WHERE Score != 0;");
         if (!vsnNodes.empty ())
         {
             // Load existing Seens from DB.
             std::vector<std::string>    vstrPublicKeys;
             vstrPublicKeys.resize (vsnNodes.size ());
             for (int iNode = vsnNodes.size (); iNode--;)
             {
                 vstrPublicKeys[iNode]   = sqlEscape (vsnNodes[iNode].strValidator);
             }
             SQL_FOREACH (db, str (boost::format ("SELECT PublicKey,Seen FROM TrustedNodes WHERE PublicKey IN (%s);")
                                   % strJoin (vstrPublicKeys.begin (), vstrPublicKeys.end (), ",")))
             {
                 vsnNodes[umPulicIdx[db->getStrBinary ("PublicKey")]].iSeen   = db->getNull ("Seen") ? -1 : db->getInt ("Seen");
             }
         }
         boost::unordered_set<std::string>   usUNL;
         if (!vsnNodes.empty ())
         {
             // Update the score old entries and add new entries as needed.
             std::vector<std::string>    vstrValues;
             vstrValues.resize (vsnNodes.size ());
             for (int iNode = vsnNodes.size (); iNode--;)
             {
                 scoreNode&  sn      = vsnNodes[iNode];
                 std::string strSeen = sn.iSeen >= 0 ? str (boost::format ("%d") % sn.iSeen) : "NULL";
                 vstrValues[iNode]   = str (boost::format ("(%s,%s,%s)")
                                            % sqlEscape (sn.strValidator)
                                            % sn.iScore
                                            % strSeen);
                 usUNL.insert (sn.strValidator);
             }
             db->executeSQL (str (boost::format ("REPLACE INTO TrustedNodes (PublicKey,Score,Seen) VALUES %s;")
                                  % strJoin (vstrValues.begin (), vstrValues.end (), ",")));
         }
         {
             ScopedUNLLockType sl (mUNLLock);
             // XXX Should limit to scores above a certain minimum and limit to a certain number.
             mUNL.swap (usUNL);
         }
         ripple::unordered_map<std::string, int>  umValidators;
         if (!vsnNodes.empty ())
         {
             std::vector<std::string> vstrPublicKeys;
             // For every IpReferral add a score for the IP and PORT.
             SQL_FOREACH (db, "SELECT Validator,COUNT(*) AS Count FROM IpReferrals GROUP BY Validator;")
             {
                 umValidators[db->getStrBinary ("Validator")] = db->getInt ("Count");
                 // WriteLog (lsTRACE, UniqueNodeList) << strValidator << ":" << db->getInt("Count");
             }
         }
         // For each validator, get each referral and add its score to ip's score.
         // map of pair<IP,Port> :: score
         epScore umScore;
         typedef ripple::unordered_map<std::string, int>::value_type vcType;
         BOOST_FOREACH (vcType & vc, umValidators)
         {
             std::string strValidator    = vc.first;
             strIndex::iterator  itIndex = umPulicIdx.find (strValidator);
             if (itIndex != umPulicIdx.end ())
             {
                 int         iSeed           = vsnNodes[itIndex->second].iScore;
                 int         iEntries        = vc.second;
                 score       iTotal          = (iEntries + 1) * iEntries / 2;
                 score       iBase           = iSeed * iEntries / iTotal;
                 int         iEntry          = 0;
                 SQL_FOREACH (db, str (boost::format ("SELECT IP,Port FROM IpReferrals WHERE Validator=%s ORDER BY Entry;")
                                       % sqlEscape (strValidator)))
                 {
                     score       iPoints = iBase * (iEntries - iEntry) / iEntries;
                     int         iPort;
                     iPort       = db->getNull ("Port") ? -1 : db->getInt ("Port");
                     std::pair< std::string, int>    ep  = std::make_pair (db->getStrBinary ("IP"), iPort);
                     epScore::iterator   itEp    = umScore.find (ep);
                     umScore[ep] = itEp == umScore.end () ? iPoints :  itEp->second + iPoints;
                     iEntry++;
                 }
             }
         }
         db->executeSQL ("COMMIT;");
     }
void ripple::UniqueNodeListImp::scoreNext (bool bNow) inline private
Definition at line 1118 of file UniqueNodeList.cpp.
References nothing, and SCORE_DELAY_SECONDS.
     {
         // WriteLog (lsTRACE, UniqueNodeList) << str(boost::format("scoreNext: mtpFetchUpdated=%s mtpScoreStart=%s mtpScoreUpdated=%s mtpScoreNext=%s") % mtpFetchUpdated % mtpScoreStart % mtpScoreUpdated % mtpScoreNext);
         bool    bCanScore   = mtpScoreStart.is_not_a_date_time ()                           // Not scoring.
                               && !mtpFetchUpdated.is_not_a_date_time ();                  // Something to score.
         bool    bDirty  =
             (mtpScoreUpdated.is_not_a_date_time () || mtpScoreUpdated <= mtpFetchUpdated)   // Not already scored.
             && (mtpScoreNext.is_not_a_date_time ()                                          // Timer is not fine.
                 || mtpScoreNext < mtpFetchUpdated + boost::posix_time::seconds (SCORE_DELAY_SECONDS));
         if (!bCanScore)
         {
             nothing ();
         }
         else if (bNow || bDirty)
         {
             // Need to update or set timer.
             double const secondsFromNow = bNow ? 0 : SCORE_DELAY_SECONDS;
             mtpScoreNext = boost::posix_time::second_clock::universal_time ()                   // Past now too.
                            + boost::posix_time::seconds (secondsFromNow);
             // WriteLog (lsTRACE, UniqueNodeList) << str(boost::format("scoreNext: @%s") % mtpScoreNext);
             m_scoreTimer.setExpiration (secondsFromNow);
         }
     }
bool ripple::UniqueNodeListImp::scoreRound (std::vector< scoreNode > & vsnNodes) inline private
Definition at line 720 of file UniqueNodeList.cpp.
References ripple::UniqueNodeListImp::scoreNode::iRoundScore, ripple::UniqueNodeListImp::scoreNode::iRoundSeed, ripple::UniqueNodeListImp::scoreNode::iScore, ripple::lsTRACE, ShouldLog, ripple::strJoin(), ripple::UniqueNodeListImp::scoreNode::strValidator, ripple::UniqueNodeListImp::scoreNode::viReferrals, and WriteLog.
     {
         bool    bDist   = false;
         // For each node, distribute roundSeed to roundScores.
         BOOST_FOREACH (scoreNode & sn, vsnNodes)
         {
             int     iEntries    = sn.viReferrals.size ();
             if (sn.iRoundSeed && iEntries)
             {
                 score   iTotal  = (iEntries + 1) * iEntries / 2;
                 score   iBase   = sn.iRoundSeed * iEntries / iTotal;
                 // Distribute the current entires' seed score to validators prioritized by mention order.
                 for (int i = 0; i != iEntries; i++)
                 {
                     score   iPoints = iBase * (iEntries - i) / iEntries;
                     vsnNodes[sn.viReferrals[i]].iRoundScore += iPoints;
                 }
             }
         }
         if (ShouldLog (lsTRACE, UniqueNodeList))
         {
             WriteLog (lsTRACE, UniqueNodeList) << "midway: ";
             BOOST_FOREACH (scoreNode & sn, vsnNodes)
             {
                 WriteLog (lsTRACE, UniqueNodeList) << str (boost::format ("%s| %d, %d, %d: [%s]")
                                                    % sn.strValidator
                                                    % sn.iScore
                                                    % sn.iRoundScore
                                                    % sn.iRoundSeed
                                                    % strJoin (sn.viReferrals.begin (), sn.viReferrals.end (), ","));
             }
         }
         // Add roundScore to score.
         // Make roundScore new roundSeed.
         BOOST_FOREACH (scoreNode & sn, vsnNodes)
         {
             if (!bDist && sn.iRoundScore)
                 bDist   = true;
             sn.iScore       += sn.iRoundScore;
             sn.iRoundSeed   = sn.iRoundScore;
             sn.iRoundScore  = 0;
         }
         if (ShouldLog (lsTRACE, UniqueNodeList))
         {
             WriteLog (lsTRACE, UniqueNodeList) << "finish: ";
             BOOST_FOREACH (scoreNode & sn, vsnNodes)
             {
                 WriteLog (lsTRACE, UniqueNodeList) << str (boost::format ("%s| %d, %d, %d: [%s]")
                                                    % sn.strValidator
                                                    % sn.iScore
                                                    % sn.iRoundScore
                                                    % sn.iRoundSeed
                                                    % strJoin (sn.viReferrals.begin (), sn.viReferrals.end (), ","));
             }
         }
         return bDist;
     }
void ripple::UniqueNodeListImp::setSeedDomains (const seedDomain & sdSource, bool bNext) inline private
Definition at line 1807 of file UniqueNodeList.cpp.
References db, ripple::Database::executeSQL(), ripple::getApp(), ripple::DatabaseCon::getDB(), ripple::base_uint< BITS >::GetHex(), ripple::Application::getWalletDB(), ripple::RippleAddress::humanNodePublic(), ripple::UniqueNodeListImp::seedDomain::iSha256, ripple::RippleAddress::isValid(), ripple::iToSeconds(), ripple::lsWARNING, ripple::UniqueNodeListImp::seedDomain::naPublicKey, ripple::sqlEscape(), ripple::UniqueNodeListImp::seedDomain::strComment, ripple::UniqueNodeListImp::seedDomain::strDomain, ripple::UniqueNodeListImp::seedDomain::tpFetch, ripple::UniqueNodeListImp::seedDomain::tpNext, ripple::UniqueNodeListImp::seedDomain::tpScan, ripple::UniqueNodeListImp::seedDomain::vsSource, and WriteLog.
     {
         Database*   db = getApp().getWalletDB ()->getDB ();
         int     iNext   = iToSeconds (sdSource.tpNext);
         int     iScan   = iToSeconds (sdSource.tpScan);
         int     iFetch  = iToSeconds (sdSource.tpFetch);
         // WriteLog (lsTRACE) << str(boost::format("setSeedDomains: iNext=%s tpNext=%s") % iNext % sdSource.tpNext);
         std::string strSql  = boost::str (boost::format ("REPLACE INTO SeedDomains (Domain,PublicKey,Source,Next,Scan,Fetch,Sha256,Comment) VALUES (%s, %s, %s, %d, %d, %d, '%s', %s);")
                                           % sqlEscape (sdSource.strDomain)
                                           % (sdSource.naPublicKey.isValid () ? sqlEscape (sdSource.naPublicKey.humanNodePublic ()) : "NULL")
                                           % sqlEscape (std::string (1, static_cast<char> (sdSource.vsSource)))
                                           % iNext
                                           % iScan
                                           % iFetch
                                           % sdSource.iSha256.GetHex ()
                                           % sqlEscape (sdSource.strComment)
                                          );
         DeprecatedScopedLock sl (getApp().getWalletDB ()->getDBLock ());
         if (!db->executeSQL (strSql))
         {
             // XXX Check result.
             WriteLog (lsWARNING, UniqueNodeList) << "setSeedDomains: failed.";
         }
         if (bNext && (mtpFetchNext.is_not_a_date_time () || mtpFetchNext > sdSource.tpNext))
         {
             // Schedule earlier wake up.
             fetchNext ();
         }
     }
void ripple::UniqueNodeListImp::setSeedNodes (const seedNode & snSource, bool bNext) inline private
Definition at line 1908 of file UniqueNodeList.cpp.
References db, ripple::Database::executeSQL(), ripple::getApp(), ripple::DatabaseCon::getDB(), ripple::base_uint< BITS >::GetHex(), ripple::Application::getWalletDB(), ripple::RippleAddress::humanNodePublic(), ripple::UniqueNodeListImp::seedNode::iSha256, ripple::RippleAddress::isValid(), ripple::iToSeconds(), ripple::lsTRACE, ripple::UniqueNodeListImp::seedNode::naPublicKey, ripple::sqlEscape(), ripple::UniqueNodeListImp::seedNode::strComment, ripple::UniqueNodeListImp::seedNode::tpFetch, ripple::UniqueNodeListImp::seedNode::tpNext, ripple::UniqueNodeListImp::seedNode::tpScan, ripple::UniqueNodeListImp::seedNode::vsSource, and WriteLog.
     {
         Database*   db = getApp().getWalletDB ()->getDB ();
         int     iNext   = iToSeconds (snSource.tpNext);
         int     iScan   = iToSeconds (snSource.tpScan);
         int     iFetch  = iToSeconds (snSource.tpFetch);
         // WriteLog (lsTRACE) << str(boost::format("setSeedNodes: iNext=%s tpNext=%s") % iNext % sdSource.tpNext);
         assert (snSource.naPublicKey.isValid ());
         std::string strSql  = str (boost::format ("REPLACE INTO SeedNodes (PublicKey,Source,Next,Scan,Fetch,Sha256,Comment) VALUES ('%s', '%c', %d, %d, %d, '%s', %s);")
                                    % snSource.naPublicKey.humanNodePublic ()
                                    % static_cast<char> (snSource.vsSource)
                                    % iNext
                                    % iScan
                                    % iFetch
                                    % snSource.iSha256.GetHex ()
                                    % sqlEscape (snSource.strComment)
                                   );
         {
             DeprecatedScopedLock sl (getApp().getWalletDB ()->getDBLock ());
             if (!db->executeSQL (strSql))
             {
                 // XXX Check result.
                 WriteLog (lsTRACE, UniqueNodeList) << "setSeedNodes: failed.";
             }
         }
     #if 0
         // YYY When we have a cas schedule lookups similar to this.
         if (bNext && (mtpFetchNext.is_not_a_date_time () || mtpFetchNext > snSource.tpNext))
         {
             // Schedule earlier wake up.
             fetchNext ();
         }
     #else
         fetchDirty ();
     #endif
     }
void ripple::UniqueNodeListImp::start () inline virtual
Implements ripple::UniqueNodeList.
Definition at line 178 of file UniqueNodeList.cpp.
References ripple::lsDEBUG, and WriteLog.
     {
         miscLoad ();
         WriteLog (lsDEBUG, UniqueNodeList) << "Validator fetch updated: " << mtpFetchUpdated;
         WriteLog (lsDEBUG, UniqueNodeList) << "Validator score updated: " << mtpScoreUpdated;
         fetchNext ();           // Start fetching.
         scoreNext (false);      // Start scoring.
     }
void ripple::UniqueNodeListImp::trustedLoad () inline private
Definition at line 684 of file UniqueNodeList.cpp.
References ripple::RippleAddress::createNodePublic(), db, ripple::getApp(), ripple::getConfig(), ripple::DatabaseCon::getDB(), ripple::Database::getStrBinary(), ripple::Application::getWalletDB(), ripple::RippleAddress::isValid(), ripple::lsWARNING, beast::asio::InputParser::match(), SQL_FOREACH, and WriteLog.
     {
         boost::regex rNode ("\\`\\s*(\\S+)[\\s]*(.*)\\'");
         BOOST_FOREACH (const std::string & c, getConfig ().CLUSTER_NODES)
         {
             boost::smatch match;
             if (boost::regex_match (c, match, rNode))
             {
                 RippleAddress a = RippleAddress::createNodePublic (match[1]);
                 if (a.isValid ())
                     m_clusterNodes.insert (std::make_pair (a, ClusterNodeStatus(match[2])));
             }
             else
                 WriteLog (lsWARNING, UniqueNodeList) << "Entry in cluster list invalid: '" << c << "'";
         }
         Database*   db = getApp().getWalletDB ()->getDB ();
         DeprecatedScopedLock sl (getApp().getWalletDB ()->getDBLock ());
         ScopedUNLLockType slUNL (mUNLLock);
         mUNL.clear ();
         // XXX Needs to limit by quanity and quality.
         SQL_FOREACH (db, "SELECT PublicKey FROM TrustedNodes WHERE Score != 0;")
         {
             mUNL.insert (db->getStrBinary ("PublicKey"));
         }
     }
bool ripple::UniqueNodeListImp::validatorsResponse (const boost::system::error_code & err, int iStatus, std::string strResponse) inline private
Definition at line 1956 of file UniqueNodeList.cpp.
References ripple::getConfig(), ripple::Config::Helpers::getValidatorsFileName(), ripple::lsTRACE, ripple::lsWARNING, and WriteLog.
Referenced by nodeNetwork().
     {
         bool    bReject = !err && iStatus != 200;
         if (!bReject)
         {
             WriteLog (lsTRACE, UniqueNodeList) <<
                 "Fetch '" <<
                 Config::Helpers::getValidatorsFileName () <<
                 "' complete.";
             if (!err)
             {
                 nodeProcess ("network", strResponse, getConfig ().VALIDATORS_SITE);
             }
             else
             {
                 WriteLog (lsWARNING, UniqueNodeList) << "Error: " << err.message ();
             }
         }
         return bReject;
     }
Member Data Documentation
std::map<RippleAddress, ClusterNodeStatus> ripple::UniqueNodeListImp::m_clusterNodes private
Definition at line 2034 of file UniqueNodeList.cpp.
beast::DeadlineTimer ripple::UniqueNodeListImp::m_fetchTimer private
Definition at line 2032 of file UniqueNodeList.cpp.
beast::DeadlineTimer ripple::UniqueNodeListImp::m_scoreTimer private
Definition at line 2027 of file UniqueNodeList.cpp.
int ripple::UniqueNodeListImp::mFetchActive private
Definition at line 2029 of file UniqueNodeList.cpp.
FetchLockType ripple::UniqueNodeListImp::mFetchLock private
Definition at line 2010 of file UniqueNodeList.cpp.
boost::posix_time::ptime ripple::UniqueNodeListImp::mtpFetchNext private
Definition at line 2031 of file UniqueNodeList.cpp.
boost::posix_time::ptime ripple::UniqueNodeListImp::mtpFetchUpdated private
Definition at line 2019 of file UniqueNodeList.cpp.
boost::posix_time::ptime ripple::UniqueNodeListImp::mtpScoreNext private
Definition at line 2025 of file UniqueNodeList.cpp.
boost::posix_time::ptime ripple::UniqueNodeListImp::mtpScoreStart private
Definition at line 2026 of file UniqueNodeList.cpp.
boost::posix_time::ptime ripple::UniqueNodeListImp::mtpScoreUpdated private
Definition at line 2018 of file UniqueNodeList.cpp.
boost::unordered_set<std::string> ripple::UniqueNodeListImp::mUNL private
Definition at line 2023 of file UniqueNodeList.cpp.
UNLLockType ripple::UniqueNodeListImp::mUNLLock private
Definition at line 2014 of file UniqueNodeList.cpp.
The documentation for this class was generated from the following file:
rippled/src/ripple_app/peers/UniqueNodeList.cpp