rippled: ripple::PeerFinder::Callback Struct Reference
ripple::PeerFinder::Callback Struct Reference abstract
#include <Callback.h>
Public Member Functions
virtual void connect (IPAddresses const &addresses)=0
virtual void activate (Slot::ptr const &slot)=0
virtual void send (Slot::ptr const &slot, Endpoints const &endpoints)=0
virtual void disconnect (Slot::ptr const &slot, bool graceful)=0
Detailed Description
The Callback receives PeerFinder notifications. The notifications are sent on a thread owned by the PeerFinder, so it is best not to do too much work in here. Just post functor to another worker thread or job queue and return.
Definition at line 33 of file Callback.h.
Member Function Documentation
virtual void ripple::PeerFinder::Callback::activate (Slot::ptr const & slot) pure virtual
Activate the handshaked peer with the specified address.
Implemented in ripple::OverlayImpl.
Referenced by ripple::PeerFinder::Logic::on_handshake().
virtual void ripple::PeerFinder::Callback::connect (IPAddresses const & addresses) pure virtual
Initiate outgoing Peer connections to the specified set of endpoints.
Implemented in ripple::OverlayImpl.
Referenced by ripple::PeerFinder::Logic::autoconnect().
virtual void ripple::PeerFinder::Callback::disconnect (Slot::ptr const & slot, bool graceful) pure virtual
Disconnect the handshaked peer with the specified address.
Parameters
graceful true to wait for send buffers to drain before closing.
Implemented in ripple::OverlayImpl.
Referenced by ripple::PeerFinder::Logic::on_connected(), and ripple::PeerFinder::Logic::on_handshake().
virtual void ripple::PeerFinder::Callback::send (Slot::ptr const & slot, Endpoints const & endpoints) pure virtual
Sends a set of Endpoint records to the specified peer.
Referenced by ripple::PeerFinder::Logic::broadcast(), and ripple::PeerFinder::Logic::redirect().
The documentation for this struct was generated from the following file:
rippled/src/ripple/peerfinder/api/Callback.h