rippled: rocksdb::port::RWMutex Class Reference
rocksdb::port::RWMutex Class Reference
#include <port_posix.h>
Public Member Functions
RWMutex ()
~RWMutex ()
void ReadLock ()
void WriteLock ()
void Unlock ()
void AssertHeld ()
Private Member Functions
RWMutex (const RWMutex &)
void operator= (const RWMutex &)
Private Attributes
pthread_rwlock_t mu_
Detailed Description
Definition at line 106 of file port_posix.h.
Constructor & Destructor Documentation
rocksdb::port::RWMutex::RWMutex ()
Definition at line 71 of file port_posix.cc.
References mu_, and rocksdb::port::PthreadCall().
 { PthreadCall("init mutex", pthread_rwlock_init(&mu_, NULL)); }
rocksdb::port::RWMutex::~RWMutex ()
Definition at line 73 of file port_posix.cc.
References mu_, and rocksdb::port::PthreadCall().
 { PthreadCall("destroy mutex", pthread_rwlock_destroy(&mu_)); }
rocksdb::port::RWMutex::RWMutex (const RWMutex &) private
Member Function Documentation
void rocksdb::port::RWMutex::AssertHeld () inline
Definition at line 114 of file port_posix.h.
 { }
void rocksdb::port::RWMutex::operator= (const RWMutex &) private
void rocksdb::port::RWMutex::ReadLock ()
Definition at line 75 of file port_posix.cc.
References mu_, and rocksdb::port::PthreadCall().
Referenced by rocksdb::ReadLock::ReadLock().
 { PthreadCall("read lock", pthread_rwlock_rdlock(&mu_)); }
void rocksdb::port::RWMutex::Unlock ()
Definition at line 79 of file port_posix.cc.
References mu_, and rocksdb::port::PthreadCall().
Referenced by rocksdb::ReadLock::~ReadLock(), and rocksdb::WriteLock::~WriteLock().
 { PthreadCall("unlock", pthread_rwlock_unlock(&mu_)); }
void rocksdb::port::RWMutex::WriteLock ()
Definition at line 77 of file port_posix.cc.
References mu_, and rocksdb::port::PthreadCall().
Referenced by rocksdb::WriteLock::WriteLock().
 { PthreadCall("write lock", pthread_rwlock_wrlock(&mu_)); }
Member Data Documentation
pthread_rwlock_t rocksdb::port::RWMutex::mu_ private
Definition at line 117 of file port_posix.h.
Referenced by ReadLock(), RWMutex(), Unlock(), WriteLock(), and ~RWMutex().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/port/port_posix.h
rippled/src/ripple/rocksdb/rocksdb/port/port_posix.cc