rippled: std::hash< rocksdb::Slice > Struct Template Reference
std::hash< rocksdb::Slice > Struct Template Reference
Public Member Functions
size_t operator() (const rocksdb::Slice &slice) const
size_t operator() (const rocksdb::Slice &slice) const
Detailed Description
template<>
struct std::hash< rocksdb::Slice >
Definition at line 27 of file memtable.cc.
Member Function Documentation
size_t std::hash< rocksdb::Slice >::operator() (const rocksdb::Slice & slice) const inline
Definition at line 26 of file transformrep.cc.
References rocksdb::Slice::data(), MurmurHash, and rocksdb::Slice::size().
{
     return MurmurHash(slice.data(), slice.size(), 0);
   }
size_t std::hash< rocksdb::Slice >::operator() (const rocksdb::Slice & slice) const inline
Definition at line 28 of file memtable.cc.
References rocksdb::Slice::data(), MurmurHash, and rocksdb::Slice::size().
{
     return MurmurHash(slice.data(), slice.size(), 0);
   }
The documentation for this struct was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/db/memtable.cc
rippled/src/ripple/rocksdb/rocksdb/util/transformrep.cc