rippled: beast::hash_metrics::detail Namespace Reference
beast::hash_metrics::detail Namespace Reference
Functions
template<class T >
T sqr (T t)
double score (int const *bins, std::size_t const bincount, double const k)
template<class T >
std::uint32_t window (T *blob, int start, int count)
Function Documentation
double beast::hash_metrics::detail::score (int const * bins, std::size_t const bincount, double const k)
Definition at line 116 of file hash_metrics.h.
References ripple::f, and sqr().
Referenced by rocksdb::VersionSet::Finalize(), rocksdb::DBImpl::MakeRoomForWrite(), rocksdb::VersionSet::PickCompactionBySize(), rocksdb::VersionSet::PickCompactionUniversalReadAmp(), rocksdb::VersionSet::PickCompactionUniversalSizeAmp(), sqlite3FindFunction(), and beast::hash_metrics::windowed_score().
 {
     double const n = bincount;
     // compute rms^2 value
     double rms_sq = 0;
     for(std::size_t i = 0; i < bincount; ++i)
         rms_sq += sqr(bins[i]);;
     rms_sq /= n;
     // compute fill factor
     double const f = (sqr(k) - 1) / (n*rms_sq - k);
     // rescale to (0,1) with 0 = good, 1 = bad
     return 1 - (f / n);
 }
template<class T > T beast::hash_metrics::detail::sqr (T t) inline
Definition at line 110 of file hash_metrics.h.
Referenced by score().
 {
     return t*t;
 }
template<class T > std::uint32_t beast::hash_metrics::detail::window (T * blob, int start, int count)
Definition at line 132 of file hash_metrics.h.
References T.
Referenced by beast::hash_metrics::windowed_score().
 {
     std::size_t const len = sizeof(T);
     static_assert((len & 3) == 0, "");
     if(count == 0)
         return 0;
     int const nbits = len * CHAR_BIT;
     start %= nbits;
     int ndwords = len / 4;
     std::uint32_t const* k = static_cast <
         std::uint32_t const*>(static_cast<void const*>(blob));
     int c = start & (32-1);
     int d = start / 32;
     if(c == 0)
         return (k[d] & ((1 << count) - 1));
     int ia = (d + 1) % ndwords;
     int ib = (d + 0) % ndwords;
     std::uint32_t a = k[ia];
     std::uint32_t b = k[ib];
     std::uint32_t t = (a << (32-c)) | (b >> c);
     t &= ((1 << count)-1);
     return t;
 }