rippled: beast::Debug Namespace Reference
beast::Debug Namespace Reference
Functions
void breakPoint ()
String getSourceLocation (char const *fileName, int lineNumber, int numberOfParents=0)
String getFileNameFromPath (const char *sourceFileName, int numberOfParents=0)
String stringToCommandLine (const String &s)
String commandLineToString (const String &commandLine)
void setAlwaysCheckHeap (bool bAlwaysCheck)
void setHeapDelayedFree (bool bDelayedFree)
void setHeapReportLeaks (bool bReportLeaks)
void reportLeaks ()
void checkHeap ()
static const String withEscapedQuotes (String const &string)
static const String withUnescapedQuotes (String const &string)
Function Documentation
void beast::Debug::breakPoint ()
Break to debugger if a debugger is attached to a debug build.
Does nothing if no debugger is attached, or the build is not a debug build.
Definition at line 28 of file Debug.cpp.
References bassertfalse, beast_breakDebugger, and beast::beast_isRunningUnderDebugger().
 {
 #if BEAST_DEBUG
     if (beast_isRunningUnderDebugger ())
         beast_breakDebugger;
 #else
     bassertfalse;
 #endif
 }
void beast::Debug::checkHeap ()
Confirms the integrity of the memory blocks allocated in the debug heap (debug version only.
Definition at line 118 of file Debug.cpp.
 {
 }
String beast::Debug::commandLineToString (const String & commandLine)
Definition at line 259 of file Debug.cpp.
References beast::String::length(), beast::String::substring(), and withUnescapedQuotes().
 {
     String string;
     bool quoting = false;
     int i0 = 0;
     int i;
     for (i = 0; i < commandLine.length (); i++)
     {
         beast_wchar c = commandLine[i];
         if (c == '\\')
         {
             // peek
             if (commandLine.length () > i && commandLine[i + 1] == '\"')
             {
                 i++;
             }
         }
         else if (c == '"')
         {
             if (!quoting)
             {
                 i0 = i + 1;
                 quoting = true;
             }
             else
             {
                 if (!string.isEmpty ())
                     string << '\n';
                 string << withUnescapedQuotes (commandLine.substring (i0, i));
                 quoting = false;
             }
         }
     }
     return string;
 }
String beast::Debug::getFileNameFromPath (const char * sourceFileName, int numberOfParents = 0)
Retrieve the file name from a full path. The nubmer of parents can be chosen
Definition at line 133 of file Debug.cpp.
References beast::String::lastIndexOfChar(), beast.util.CleanCPPFiles::path, beast::String::replaceCharacter(), and beast::String::substring().
Referenced by beast::Error::fail(), and getSourceLocation().
 {
     String fullPath (sourceFileName);
 #if BEAST_WINDOWS
     // Convert everything to forward slash
     fullPath = fullPath.replaceCharacter ('\\', '/');
 #endif
     String path;
     int chopPoint = fullPath.lastIndexOfChar ('/');
     path = fullPath.substring (chopPoint + 1);
     while (chopPoint >= 0 && numberOfParents > 0)
     {
         --numberOfParents;
         fullPath = fullPath.substring (0, chopPoint);
         chopPoint = fullPath.lastIndexOfChar ('/');
         path = fullPath.substring (chopPoint + 1) + '/' + path;
     }
     return path;
 }
String beast::Debug::getSourceLocation (char const * fileName, int lineNumber, int numberOfParents = 0)
Given a file and line number this formats a suitable string. Usually you will pass FILE and LINE here.
Definition at line 126 of file Debug.cpp.
References beast::String::fromNumber(), and getFileNameFromPath().
Referenced by ripple::logTimedCall(), ripple::Validators::StoreSqdb::report(), and ripple::PeerFinder::StoreSqdb::report().
 {
     return getFileNameFromPath (fileName, numberOfParents) +
         "(" + String::fromNumber (lineNumber) + ")";
 }
void beast::Debug::reportLeaks ()
Report all memory blocks which have not been freed.
Definition at line 114 of file Debug.cpp.
 {
 }
void beast::Debug::setAlwaysCheckHeap (bool bAlwaysCheck)
Calls checkHeap() at every allocation and deallocation.
Definition at line 102 of file Debug.cpp.
 {
 }
void beast::Debug::setHeapDelayedFree (bool bDelayedFree)
Keep freed memory blocks in the heap's linked list, assign them the _FREE_BLOCK type, and fill them with the byte value 0xDD.
Definition at line 106 of file Debug.cpp.
 {
 }
void beast::Debug::setHeapReportLeaks (bool bReportLeaks)
Perform automatic leak checking at program exit through a call to dumpMemoryLeaks() and generate an error report if the application failed to free all the memory it allocated.
Definition at line 110 of file Debug.cpp.
Referenced by main().
 {
 }
String beast::Debug::stringToCommandLine (const String & s)
Definition at line 224 of file Debug.cpp.
References withEscapedQuotes().
 {
     String commandLine;
     int i0 = 0;
     int i;
     for (i = 0; i < string.length (); i++)
     {
         beast_wchar c = string[i];
         if (c == '\n')
         {
             if (i0 != 0)
                 commandLine << ' ';
             commandLine << '"' << withEscapedQuotes (string.substring (i0, i)) << '"';
             i0 = i + 1;
         }
     }
     if (i0 < i)
     {
         if (i0 != 0)
             commandLine << ' ';
         commandLine << '"' << withEscapedQuotes (string.substring (i0, i)) << '"';
     }
     return commandLine;
 }
static const String beast::Debug::withEscapedQuotes (String const & string) static
Definition at line 159 of file Debug.cpp.
References beast::String::indexOfChar(), and beast::String::substring().
Referenced by stringToCommandLine().
 {
     String escaped;
     int i0 = 0;
     int i;
     do
     {
         i = string.indexOfChar (i0, '"');
         if (i == -1)
         {
             escaped << string.substring (i0, string.length ());
         }
         else
         {
             escaped << string.substring (i0, i) << "\\\"";
             i0 = i + 1;
         }
     }
     while (i != -1);
     return escaped;
 }
static const String beast::Debug::withUnescapedQuotes (String const & string) static
Definition at line 186 of file Debug.cpp.
References beast::String::indexOfChar(), and beast::String::substring().
Referenced by commandLineToString().
 {
     String unescaped;
     int i0 = 0;
     int i;
     do
     {
         i = string.indexOfChar (i0, '\\');
         if (i == -1)
         {
             unescaped << string.substring (i0, string.length ());
         }
         else
         {
             // peek
             if (string.length () > i && string[i + 1] == '\"')
             {
                 unescaped << string.substring (i0, i) << '"';
                 i0 = i + 2;
             }
             else
             {
                 unescaped << string.substring (i0, i + 1);
                 i0 = i + 1;
             }
         }
     }
     while (i != -1);
     return unescaped;
 }