rippled: ripple::PeerFinder::Livecache_test Class Reference
ripple::PeerFinder::Livecache_test Class Reference
Public Member Functions
template<class C >
void add (std::uint32_t index, std::uint16_t port, C &c)
void testFetch ()
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Public Attributes
beast::manual_clock
< clock_type::duration > m_clock
Public Attributes inherited from beast::unit_test::suite
log_t log
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Detailed Description
Definition at line 26 of file Livecache.cpp.
Member Function Documentation
template<class C > void ripple::PeerFinder::Livecache_test::add (std::uint32_t index, std::uint16_t port, C & c) inline
Definition at line 33 of file Livecache.cpp.
References ripple::PeerFinder::Endpoint::address, and ripple::PeerFinder::Endpoint::hops.
Referenced by testFetch().
     {
         Endpoint ep;
         ep.hops = 0;
         ep.address = beast::IP::Endpoint (
             beast::IP::AddressV4 (index), port);
         c.insert (ep);
     }
void ripple::PeerFinder::Livecache_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 62 of file Livecache.cpp.
References testFetch().
     {
         testFetch ();
     }
void ripple::PeerFinder::Livecache_test::testFetch () inline
Definition at line 42 of file Livecache.cpp.
References add(), m_clock, and beast::unit_test::suite::pass().
Referenced by run().
     {
         Livecache <> c (m_clock, beast::Journal());
         add (1, 1, c);
         add (2, 1, c);
         add (3, 1, c);
         add (4, 1, c);
         add (4, 2, c);
         add (4, 3, c);
         add (5, 1, c);
         add (6, 1, c);
         add (6, 2, c);
         add (7, 1, c);
         // VFALCO TODO!!!
         pass();
     }
Member Data Documentation
beast::manual_clock<clock_type::duration> ripple::PeerFinder::Livecache_test::m_clock
Definition at line 29 of file Livecache.cpp.
Referenced by testFetch().
The documentation for this class was generated from the following file:
rippled/src/ripple/peerfinder/impl/Livecache.cpp