rippled: rocksdb::SpecialEnv Class Reference
rocksdb::SpecialEnv Class Reference
Public Member Functions
SpecialEnv (Env *base)
Status NewWritableFile (const std::string &f, unique_ptr< WritableFile > *r, const EnvOptions &soptions)
Status NewRandomAccessFile (const std::string &f, unique_ptr< RandomAccessFile > *r, const EnvOptions &soptions)
virtual void SleepForMicroseconds (int micros)
Public Member Functions inherited from rocksdb::EnvWrapper
EnvWrapper (Env *t)
virtual ~EnvWrapper ()
Env * target () const
Status NewSequentialFile (const std::string &f, unique_ptr< SequentialFile > *r, const EnvOptions &options)
Status NewRandomAccessFile (const std::string &f, unique_ptr< RandomAccessFile > *r, const EnvOptions &options)
Status NewWritableFile (const std::string &f, unique_ptr< WritableFile > *r, const EnvOptions &options)
Status NewRandomRWFile (const std::string &f, unique_ptr< RandomRWFile > *r, const EnvOptions &options)
bool FileExists (const std::string &f)
Status GetChildren (const std::string &dir, std::vector< std::string > *r)
Status DeleteFile (const std::string &f)
Status CreateDir (const std::string &d)
Status CreateDirIfMissing (const std::string &d)
Status DeleteDir (const std::string &d)
Status GetFileSize (const std::string &f, uint64_t *s)
Status GetFileModificationTime (const std::string &fname, uint64_t *file_mtime)
Status RenameFile (const std::string &s, const std::string &t)
Status LockFile (const std::string &f, FileLock **l)
Status UnlockFile (FileLock *l)
void Schedule (void(*f)(void *), void *a, Priority pri)
void StartThread (void(*f)(void *), void *a)
virtual Status GetTestDirectory (std::string *path)
virtual Status NewLogger (const std::string &fname, shared_ptr< Logger > *result)
uint64_t NowMicros ()
void SleepForMicroseconds (int micros)
Status GetHostName (char *name, uint64_t len)
Status GetCurrentTime (int64_t *unix_time)
Status GetAbsolutePath (const std::string &db_path, std::string *output_path)
void SetBackgroundThreads (int num, Priority pri)
std::string TimeToString (uint64_t time)
Public Member Functions inherited from rocksdb::Env
Env ()
virtual ~Env ()
virtual void Schedule (void(*function)(void *arg), void *arg, Priority pri=LOW)=0
virtual void StartThread (void(*function)(void *arg), void *arg)=0
virtual uint64_t NowNanos ()
virtual std::string GenerateUniqueId ()
Public Attributes
port::AtomicPointer delay_sstable_sync_
port::AtomicPointer no_space_
port::AtomicPointer non_writable_
port::AtomicPointer manifest_sync_error_
port::AtomicPointer manifest_write_error_
port::AtomicPointer log_write_error_
bool count_random_reads_
anon::AtomicCounter random_read_counter_
anon::AtomicCounter sleep_counter_
Additional Inherited Members
Public Types inherited from rocksdb::Env
enum Priority { LOW, HIGH, TOTAL }
Static Public Member Functions inherited from rocksdb::Env
static Env * Default ()
Detailed Description
Definition at line 82 of file db_test.cc.
Constructor & Destructor Documentation
rocksdb::SpecialEnv::SpecialEnv (Env * base) inline explicit
Definition at line 107 of file db_test.cc.
References count_random_reads_, delay_sstable_sync_, log_write_error_, manifest_sync_error_, manifest_write_error_, no_space_, non_writable_, and rocksdb::port::AtomicPointer::Release_Store().
                                  : EnvWrapper(base) {
     delay_sstable_sync_.Release_Store(nullptr);
     no_space_.Release_Store(nullptr);
     non_writable_.Release_Store(nullptr);
     count_random_reads_ = false;
     manifest_sync_error_.Release_Store(nullptr);
     manifest_write_error_.Release_Store(nullptr);
     log_write_error_.Release_Store(nullptr);
    }
Member Function Documentation
Status rocksdb::SpecialEnv::NewRandomAccessFile (const std::string & f, unique_ptr< RandomAccessFile > * r, const EnvOptions & soptions) inline virtual
Implements rocksdb::Env.
Definition at line 206 of file db_test.cc.
References count_random_reads_, counter, rocksdb::Env::NewRandomAccessFile(), rocksdb::Status::ok(), random_read_counter_, rocksdb::EnvWrapper::target(), and rocksdb::EnvWrapper::target_.
{
     class CountingFile : public RandomAccessFile {
      private:
       unique_ptr<RandomAccessFile> target_;
       anon::AtomicCounter* counter_;
      public:
       CountingFile(unique_ptr<RandomAccessFile>&& target,
                    anon::AtomicCounter* counter)
           : target_(std::move(target)), counter_(counter) {
       }
       virtual Status Read(uint64_t offset, size_t n, Slice* result,
                           char* scratch) const {
         counter_->Increment();
         return target_->Read(offset, n, result, scratch);
       }
     };
     Status s = target()->NewRandomAccessFile(f, r, soptions);
     if (s.ok() && count_random_reads_) {
       r->reset(new CountingFile(std::move(*r), &random_read_counter_));
     }
     return s;
   }
Status rocksdb::SpecialEnv::NewWritableFile (const std::string & f, unique_ptr< WritableFile > * r, const EnvOptions & soptions) inline virtual
Implements rocksdb::Env.
Definition at line 117 of file db_test.cc.
References rocksdb::port::AtomicPointer::Acquire_Load(), base, base_, env, env_, rocksdb::Status::IOError(), rocksdb::Env::NewWritableFile(), non_writable_, rocksdb::Status::OK(), rocksdb::Status::ok(), and rocksdb::EnvWrapper::target().
{
     class SSTableFile : public WritableFile {
      private:
       SpecialEnv* env_;
       unique_ptr<WritableFile> base_;
      public:
       SSTableFile(SpecialEnv* env, unique_ptr<WritableFile>&& base)
           : env_(env),
             base_(std::move(base)) {
       }
       Status Append(const Slice& data) {
         if (env_->no_space_.Acquire_Load() != nullptr) {
           // Drop writes on the floor
           return Status::OK();
         } else {
           return base_->Append(data);
         }
       }
       Status Close() { return base_->Close(); }
       Status Flush() { return base_->Flush(); }
       Status Sync() {
         while (env_->delay_sstable_sync_.Acquire_Load() != nullptr) {
           env_->SleepForMicroseconds(100000);
         }
         return base_->Sync();
       }
     };
     class ManifestFile : public WritableFile {
      private:
       SpecialEnv* env_;
       unique_ptr<WritableFile> base_;
      public:
       ManifestFile(SpecialEnv* env, unique_ptr<WritableFile>&& b)
           : env_(env), base_(std::move(b)) { }
       Status Append(const Slice& data) {
         if (env_->manifest_write_error_.Acquire_Load() != nullptr) {
           return Status::IOError("simulated writer error");
         } else {
           return base_->Append(data);
         }
       }
       Status Close() { return base_->Close(); }
       Status Flush() { return base_->Flush(); }
       Status Sync() {
         if (env_->manifest_sync_error_.Acquire_Load() != nullptr) {
           return Status::IOError("simulated sync error");
         } else {
           return base_->Sync();
         }
       }
     };
     class LogFile : public WritableFile {
      private:
       SpecialEnv* env_;
       unique_ptr<WritableFile> base_;
      public:
       LogFile(SpecialEnv* env, unique_ptr<WritableFile>&& b)
           : env_(env), base_(std::move(b)) { }
       Status Append(const Slice& data) {
         if (env_->log_write_error_.Acquire_Load() != nullptr) {
           return Status::IOError("simulated writer error");
         } else {
           return base_->Append(data);
         }
       }
       Status Close() { return base_->Close(); }
       Status Flush() { return base_->Flush(); }
       Status Sync() { return base_->Sync(); }
     };
     if (non_writable_.Acquire_Load() != nullptr) {
       return Status::IOError("simulated write error");
     }
     Status s = target()->NewWritableFile(f, r, soptions);
     if (s.ok()) {
       if (strstr(f.c_str(), ".sst") != nullptr) {
         r->reset(new SSTableFile(this, std::move(*r)));
       } else if (strstr(f.c_str(), "MANIFEST") != nullptr) {
         r->reset(new ManifestFile(this, std::move(*r)));
       } else if (strstr(f.c_str(), "log") != nullptr) {
         r->reset(new LogFile(this, std::move(*r)));
       }
     }
     return s;
   }
virtual void rocksdb::SpecialEnv::SleepForMicroseconds (int micros) inline virtual
Implements rocksdb::Env.
Definition at line 232 of file db_test.cc.
References rocksdb::anon::AtomicCounter::Increment(), sleep_counter_, rocksdb::Env::SleepForMicroseconds(), and rocksdb::EnvWrapper::target().
{
     sleep_counter_.Increment();
     target()->SleepForMicroseconds(micros);
   }
Member Data Documentation
bool rocksdb::SpecialEnv::count_random_reads_
Definition at line 102 of file db_test.cc.
Referenced by NewRandomAccessFile(), and SpecialEnv().
port::AtomicPointer rocksdb::SpecialEnv::delay_sstable_sync_
Definition at line 85 of file db_test.cc.
Referenced by SpecialEnv().
port::AtomicPointer rocksdb::SpecialEnv::log_write_error_
Definition at line 100 of file db_test.cc.
Referenced by SpecialEnv().
port::AtomicPointer rocksdb::SpecialEnv::manifest_sync_error_
Definition at line 94 of file db_test.cc.
Referenced by SpecialEnv().
port::AtomicPointer rocksdb::SpecialEnv::manifest_write_error_
Definition at line 97 of file db_test.cc.
Referenced by SpecialEnv().
port::AtomicPointer rocksdb::SpecialEnv::no_space_
Definition at line 88 of file db_test.cc.
Referenced by SpecialEnv().
port::AtomicPointer rocksdb::SpecialEnv::non_writable_
Definition at line 91 of file db_test.cc.
Referenced by NewWritableFile(), and SpecialEnv().
anon::AtomicCounter rocksdb::SpecialEnv::random_read_counter_
Definition at line 103 of file db_test.cc.
Referenced by NewRandomAccessFile().
anon::AtomicCounter rocksdb::SpecialEnv::sleep_counter_
Definition at line 105 of file db_test.cc.
Referenced by SleepForMicroseconds().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/db/db_test.cc