rippled: ripple::Validators::Logic_test::TestSource Struct Reference
ripple::Validators::Logic_test::TestSource Struct Reference
Public Member Functions
TestSource (beast::String const &name, std::uint32_t start, std::uint32_t end)
std::string to_string () const
beast::String uniqueID () const
beast::String createParam ()
void fetch (Results &results, beast::Journal)
Public Member Functions inherited from ripple::Validators::Source
virtual ~Source ()
virtual void cancel ()
Public Member Functions inherited from beast::SharedObject
void incReferenceCount () const noexcept
void decReferenceCount () const
int getReferenceCount () const noexcept
Public Attributes
beast::String m_name
std::size_t m_start
std::size_t m_end
Additional Inherited Members
Protected Member Functions inherited from beast::SharedObject
SharedObject ()
virtual ~SharedObject ()
virtual void destroy () const
void resetReferenceCount () noexcept
Detailed Description
Definition at line 100 of file Tests.cpp.
Constructor & Destructor Documentation
ripple::Validators::Logic_test::TestSource::TestSource (beast::String const & name, std::uint32_t start, std::uint32_t end) inline
Definition at line 102 of file Tests.cpp.
             : m_name (name)
             , m_start (start)
             , m_end (end)
         {
         }
Member Function Documentation
beast::String ripple::Validators::Logic_test::TestSource::createParam () inline virtual
A string that is used to recreate the source from the database entry.
Implements ripple::Validators::Source.
Definition at line 122 of file Tests.cpp.
References beast::String::empty.
         {
             return beast::String::empty;
         }
void ripple::Validators::Logic_test::TestSource::fetch (Results & results, beast::Journal) inline virtual
Implements ripple::Validators::Source.
Definition at line 127 of file Tests.cpp.
References beast::String::empty, beast::String::fromNumber(), ripple::Validators::Source::Item::label, ripple::Validators::Source::Results::list, m_end, m_start, ripple::Validators::Source::Results::message, ripple::Validators::Logic_test::numberOfTestValidators, ripple::Validators::Source::Item::publicKey, and ripple::Validators::Source::Results::success.
         {
             results.success = true;
             results.message = beast::String::empty;
             results.list.reserve (numberOfTestValidators);
             for (std::uint32_t i = m_start ; i < m_end; ++i)
             {
                 Item item;;
                 item.publicKey = RipplePublicKey::createFromInteger (i);
                 item.label = beast::String::fromNumber (i);
                 results.list.push_back (item);
             }
         }
std::string ripple::Validators::Logic_test::TestSource::to_string () const inline virtual
The name of the source, used in diagnostic output.
Implements ripple::Validators::Source.
Definition at line 109 of file Tests.cpp.
References beast::String::toStdString(), and uniqueID().
         {
             return uniqueID().toStdString();
         }
beast::String ripple::Validators::Logic_test::TestSource::uniqueID () const inline virtual
An identifier that uniquely describes the source. This is used for identification in the database.
Implements ripple::Validators::Source.
Definition at line 114 of file Tests.cpp.
References m_end, m_name, and m_start.
Referenced by to_string().
         {
             using beast::String;
             return String ("Test,") + m_name + "," +
                 String::fromNumber (m_start) + "," +
                 String::fromNumber (m_end);
         }
Member Data Documentation
std::size_t ripple::Validators::Logic_test::TestSource::m_end
Definition at line 144 of file Tests.cpp.
Referenced by fetch(), and uniqueID().
beast::String ripple::Validators::Logic_test::TestSource::m_name
Definition at line 142 of file Tests.cpp.
Referenced by uniqueID().
std::size_t ripple::Validators::Logic_test::TestSource::m_start
Definition at line 143 of file Tests.cpp.
Referenced by fetch(), and uniqueID().
The documentation for this struct was generated from the following file:
rippled/src/ripple/validators/impl/Tests.cpp