rippled: rocksdb::DBConstructor Class Reference
rocksdb::DBConstructor Class Reference
Public Member Functions
DBConstructor (const Comparator *cmp)
~DBConstructor ()
virtual Status FinishImpl (const Options &options, const KVMap &data)
virtual Iterator * NewIterator () const
virtual DB * db () const
Public Member Functions inherited from rocksdb::Constructor
Constructor (const Comparator *cmp)
virtual ~Constructor ()
void Add (const std::string &key, const Slice &value)
void Finish (const Options &options, std::vector< std::string > *keys, KVMap *kvmap)
virtual const KVMap & data ()
Private Member Functions
void NewDB ()
Private Attributes
const Comparator * comparator_
DB * db_
Detailed Description
Definition at line 402 of file table_test.cc.
Constructor & Destructor Documentation
rocksdb::DBConstructor::DBConstructor (const Comparator * cmp) inline explicit
Definition at line 404 of file table_test.cc.
References db_, and NewDB().
       : Constructor(cmp),
         comparator_(cmp) {
     db_ = nullptr;
     NewDB();
   }
rocksdb::DBConstructor::~DBConstructor () inline
Definition at line 410 of file table_test.cc.
References db_.
                    {
     delete db_;
   }
Member Function Documentation
virtual DB* rocksdb::DBConstructor::db () const inline virtual
Reimplemented from rocksdb::Constructor.
Definition at line 430 of file table_test.cc.
References db_.
 { return db_; }
virtual Status rocksdb::DBConstructor::FinishImpl (const Options & options, const KVMap & data) inline virtual
Implements rocksdb::Constructor.
Definition at line 413 of file table_test.cc.
References ASSERT_TRUE, db_, NewDB(), rocksdb::Status::OK(), rocksdb::Status::ok(), rocksdb::WriteBatch::Put(), and rocksdb::DB::Write().
{
     delete db_;
     db_ = nullptr;
     NewDB();
     for (KVMap::const_iterator it = data.begin();
          it != data.end();
          ++it) {
       WriteBatch batch;
       batch.Put(it->first, it->second);
       ASSERT_TRUE(db_->Write(WriteOptions(), &batch).ok());
     }
     return Status::OK();
   }
void rocksdb::DBConstructor::NewDB () inline private
Definition at line 433 of file table_test.cc.
References ASSERT_TRUE, rocksdb::Options::comparator, comparator_, rocksdb::Options::create_if_missing, db_, rocksdb::DestroyDB(), rocksdb::Options::error_if_exists, name, rocksdb::Status::ok(), rocksdb::DB::Open(), rocksdb::test::TmpDir(), rocksdb::Status::ToString(), and rocksdb::Options::write_buffer_size.
Referenced by DBConstructor(), and FinishImpl().
                {
     std::string name = test::TmpDir() + "/table_testdb";
     Options options;
     options.comparator = comparator_;
     Status status = DestroyDB(name, options);
     ASSERT_TRUE(status.ok()) << status.ToString();
     options.create_if_missing = true;
     options.error_if_exists = true;
     options.write_buffer_size = 10000;  // Something small to force merging
     status = DB::Open(options, name, &db_);
     ASSERT_TRUE(status.ok()) << status.ToString();
   }
virtual Iterator* rocksdb::DBConstructor::NewIterator () const inline virtual
Implements rocksdb::Constructor.
Definition at line 426 of file table_test.cc.
References db_, and rocksdb::DB::NewIterator().
{
     return db_->NewIterator(ReadOptions());
   }
Member Data Documentation
const Comparator* rocksdb::DBConstructor::comparator_ private
Definition at line 448 of file table_test.cc.
Referenced by NewDB().
DB* rocksdb::DBConstructor::db_ private
Definition at line 449 of file table_test.cc.
Referenced by db(), DBConstructor(), FinishImpl(), NewDB(), NewIterator(), and ~DBConstructor().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/table/table_test.cc