rippled: rocksdb::TableCache Class Reference
rocksdb::TableCache Class Reference
#include <table_cache.h>
Public Member Functions
TableCache (const std::string &dbname, const Options *options, const EnvOptions &storage_options, int entries)
~TableCache ()
Iterator * NewIterator (const ReadOptions &options, const EnvOptions &toptions, uint64_t file_number, uint64_t file_size, TableReader **table_reader_ptr=nullptr, bool for_compaction=false)
Status Get (const ReadOptions &options, uint64_t file_number, uint64_t file_size, const Slice &k, void *arg, bool(*handle_result)(void *, const Slice &, const Slice &, bool), bool *table_io, void(*mark_key_may_exist)(void *)=nullptr)
bool PrefixMayMatch (const ReadOptions &options, uint64_t file_number, uint64_t file_size, const Slice &internal_prefix, bool *table_io)
void Evict (uint64_t file_number)
Private Member Functions
Status FindTable (const EnvOptions &toptions, uint64_t file_number, uint64_t file_size, Cache::Handle **, bool *table_io=nullptr, const bool no_io=false)
Private Attributes
Env *const env_
const std::string dbname_
const Options * options_
const EnvOptions & storage_options_
std::shared_ptr< Cache > cache_
Detailed Description
Definition at line 25 of file table_cache.h.
Constructor & Destructor Documentation
rocksdb::TableCache::TableCache (const std::string & dbname, const Options * options, const EnvOptions & storage_options, int entries)
Definition at line 32 of file table_cache.cc.
     : env_(options->env),
       dbname_(dbname),
       options_(options),
       storage_options_(storage_options),
       cache_(
         NewLRUCache(entries, options->table_cache_numshardbits,
                     options->table_cache_remove_scan_count_limit)) {
 }
rocksdb::TableCache::~TableCache ()
Definition at line 45 of file table_cache.cc.
{
 }
Member Function Documentation
void rocksdb::TableCache::Evict (uint64_t file_number)
Definition at line 167 of file table_cache.cc.
References cache_, and rocksdb::EncodeFixed64().
{
   char buf[sizeof(file_number)];
   EncodeFixed64(buf, file_number);
   cache_->Erase(Slice(buf, sizeof(buf)));
 }
Status rocksdb::TableCache::FindTable (const EnvOptions & toptions, uint64_t file_number, uint64_t file_size, Cache::Handle ** handle, bool * table_io = nullptr, const bool no_io = false) private
Definition at line 48 of file table_cache.cc.
References rocksdb::Options::advise_random_on_open, cache_, dbname_, rocksdb::DeleteEntry(), rocksdb::EncodeFixed64(), env_, rocksdb::Status::Incomplete(), rocksdb::Env::NewRandomAccessFile(), rocksdb::NO_FILE_ERRORS, rocksdb::NO_FILE_OPENS, rocksdb::Status::ok(), options_, rocksdb::RandomAccessFile::RANDOM, rocksdb::RecordTick(), rocksdb::Options::statistics, rocksdb::Options::table_factory, rocksdb::TABLE_OPEN_IO_MICROS, and rocksdb::TableFileName().
Referenced by Get(), NewIterator(), and PrefixMayMatch().
{
   Status s;
   char buf[sizeof(file_number)];
   EncodeFixed64(buf, file_number);
   Slice key(buf, sizeof(buf));
   *handle = cache_->Lookup(key);
   if (*handle == nullptr) {
     if (no_io) { // Dont do IO and return a not-found status
       return Status::Incomplete("Table not found in table_cache, no_io is set");
     }
     if (table_io != nullptr) {
       *table_io = true;    // we had to do IO from storage
     }
     std::string fname = TableFileName(dbname_, file_number);
     unique_ptr<RandomAccessFile> file;
     unique_ptr<TableReader> table_reader;
     s = env_->NewRandomAccessFile(fname, &file, toptions);
     RecordTick(options_->statistics, NO_FILE_OPENS);
     if (s.ok()) {
       if (options_->advise_random_on_open) {
         file->Hint(RandomAccessFile::RANDOM);
       }
       StopWatch sw(env_, options_->statistics, TABLE_OPEN_IO_MICROS);
       s = options_->table_factory->GetTableReader(*options_, toptions,
                                                   std::move(file), file_size,
                                                   &table_reader);
     }
     if (!s.ok()) {
       assert(table_reader == nullptr);
       RecordTick(options_->statistics, NO_FILE_ERRORS);
       // We do not cache error results so that if the error is transient,
       // or somebody repairs the file, we recover automatically.
     } else {
       assert(file.get() == nullptr);
       *handle = cache_->Insert(key, table_reader.release(), 1, &DeleteEntry);
     }
   }
   return s;
 }
Status rocksdb::TableCache::Get (const ReadOptions & options, uint64_t file_number, uint64_t file_size, const Slice & k, void * arg, bool(*)(void *, const Slice &, const Slice &, bool) handle_result, bool * table_io, void(*)(void *) mark_key_may_exist = nullptr)
Definition at line 124 of file table_cache.cc.
References arg, cache_, FindTable(), rocksdb::TableReader::Get(), rocksdb::Status::IsIncomplete(), rocksdb::kBlockCacheTier, rocksdb::Status::OK(), rocksdb::Status::ok(), rocksdb::ReadOptions::read_tier, and storage_options_.
Referenced by rocksdb::Version::Get().
{
   Cache::Handle* handle = nullptr;
   Status s = FindTable(storage_options_, file_number, file_size,
                        &handle, table_io,
                        options.read_tier == kBlockCacheTier);
   if (s.ok()) {
     TableReader* t =
       reinterpret_cast<TableReader*>(cache_->Value(handle));
     s = t->Get(options, k, arg, saver, mark_key_may_exist);
     cache_->Release(handle);
   } else if (options.read_tier && s.IsIncomplete()) {
     // Couldnt find Table in cache but treat as kFound if no_io set
     (*mark_key_may_exist)(arg);
     return Status::OK();
   }
   return s;
 }
Iterator * rocksdb::TableCache::NewIterator (const ReadOptions & options, const EnvOptions & toptions, uint64_t file_number, uint64_t file_size, TableReader ** table_reader_ptr = nullptr, bool for_compaction = false)
Definition at line 92 of file table_cache.cc.
References cache_, FindTable(), rocksdb::kBlockCacheTier, rocksdb::NewErrorIterator(), rocksdb::TableReader::NewIterator(), rocksdb::Status::ok(), rocksdb::ReadOptions::read_tier, rocksdb::Iterator::RegisterCleanup(), rocksdb::TableReader::SetupForCompaction(), and rocksdb::UnrefEntry().
Referenced by rocksdb::Version::AddIterators(), rocksdb::VersionSet::ApproximateOffsetOf(), rocksdb::BuildTable(), rocksdb::GetFileIterator(), and rocksdb::VersionSet::MakeInputIterator().
{
   if (table_reader_ptr != nullptr) {
     *table_reader_ptr = nullptr;
   }
   Cache::Handle* handle = nullptr;
   Status s = FindTable(toptions, file_number, file_size, &handle,
                        nullptr, options.read_tier == kBlockCacheTier);
   if (!s.ok()) {
     return NewErrorIterator(s);
   }
   TableReader* table_reader =
     reinterpret_cast<TableReader*>(cache_->Value(handle));
   Iterator* result = table_reader->NewIterator(options);
   result->RegisterCleanup(&UnrefEntry, cache_.get(), handle);
   if (table_reader_ptr != nullptr) {
     *table_reader_ptr = table_reader;
   }
   if (for_compaction) {
     table_reader->SetupForCompaction();
   }
   return result;
 }
bool rocksdb::TableCache::PrefixMayMatch (const ReadOptions & options, uint64_t file_number, uint64_t file_size, const Slice & internal_prefix, bool * table_io)
Definition at line 149 of file table_cache.cc.
References cache_, FindTable(), rocksdb::Status::ok(), rocksdb::TableReader::PrefixMayMatch(), and storage_options_.
Referenced by rocksdb::Version::PrefixMayMatch().
{
   Cache::Handle* handle = nullptr;
   Status s = FindTable(storage_options_, file_number,
                        file_size, &handle, table_io);
   bool may_match = true;
   if (s.ok()) {
     TableReader* t =
       reinterpret_cast<TableReader*>(cache_->Value(handle));
     may_match = t->PrefixMayMatch(internal_prefix);
     cache_->Release(handle);
   }
   return may_match;
 }
Member Data Documentation
std::shared_ptr<Cache> rocksdb::TableCache::cache_ private
Definition at line 71 of file table_cache.h.
Referenced by Evict(), FindTable(), Get(), NewIterator(), and PrefixMayMatch().
const std::string rocksdb::TableCache::dbname_ private
Definition at line 68 of file table_cache.h.
Referenced by FindTable().
Env* const rocksdb::TableCache::env_ private
Definition at line 67 of file table_cache.h.
Referenced by FindTable().
const Options* rocksdb::TableCache::options_ private
Definition at line 69 of file table_cache.h.
Referenced by FindTable().
const EnvOptions& rocksdb::TableCache::storage_options_ private
Definition at line 70 of file table_cache.h.
Referenced by Get(), and PrefixMayMatch().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/db/table_cache.h
rippled/src/ripple/rocksdb/rocksdb/db/table_cache.cc