rippled: rocksdb::DeleteFileTest Class Reference
rocksdb::DeleteFileTest Class Reference
Public Member Functions
DeleteFileTest ()
Status ReopenDB (bool create)
void CloseDB ()
void AddKeys (int numkeys, int startkey=0)
int numKeysInLevels (std::vector< LiveFileMetaData > &metadata, std::vector< int > *keysperlevel=nullptr)
void CreateTwoLevels ()
void CheckFileTypeCounts (std::string &dir, int required_log, int required_sst, int required_manifest)
Public Attributes
std::string dbname_
Options options_
DB * db_
Env * env_
int numlevels_
Detailed Description
Definition at line 26 of file deletefile_test.cc.
Constructor & Destructor Documentation
rocksdb::DeleteFileTest::DeleteFileTest () inline
Definition at line 34 of file deletefile_test.cc.
References ASSERT_OK, db_, dbname_, rocksdb::Env::Default(), rocksdb::Env::DeleteFile(), rocksdb::DestroyDB(), env_, rocksdb::Env::GetChildren(), rocksdb::Options::max_bytes_for_level_base, numlevels_, options_, ReopenDB(), rocksdb::Options::target_file_size_base, rocksdb::test::TmpDir(), rocksdb::Options::wal_dir, rocksdb::Options::WAL_size_limit_MB, rocksdb::Options::WAL_ttl_seconds, and rocksdb::Options::write_buffer_size.
                    {
     db_ = nullptr;
     env_ = Env::Default();
     options_.write_buffer_size = 1024*1024*1000;
     options_.target_file_size_base = 1024*1024*1000;
     options_.max_bytes_for_level_base = 1024*1024*1000;
     options_.WAL_ttl_seconds = 300; // Used to test log files
     options_.WAL_size_limit_MB = 1024; // Used to test log files
     dbname_ = test::TmpDir() + "/deletefile_test";
     options_.wal_dir = dbname_ + "/wal_files";
     // clean up all the files that might have been there before
     std::vector<std::string> old_files;
     env_->GetChildren(dbname_, &old_files);
     for (auto file : old_files) {
       env_->DeleteFile(dbname_ + "/" + file);
     }
     env_->GetChildren(options_.wal_dir, &old_files);
     for (auto file : old_files) {
       env_->DeleteFile(options_.wal_dir + "/" + file);
     }
     DestroyDB(dbname_, options_);
     numlevels_ = 7;
     ASSERT_OK(ReopenDB(true));
   }
Member Function Documentation
void rocksdb::DeleteFileTest::AddKeys (int numkeys, int startkey = 0) inline
Definition at line 75 of file deletefile_test.cc.
References ASSERT_OK, db_, rocksdb::DB::Put(), rocksdb::WriteOptions::sync, beast::IP::to_string(), and value.
Referenced by CreateTwoLevels().
{
     WriteOptions options;
     options.sync = false;
     ReadOptions roptions;
     for (int i = startkey; i < (numkeys + startkey) ; i++) {
       std::string temp = std::to_string(i);
       Slice key(temp);
       Slice value(temp);
       ASSERT_OK(db_->Put(options, key, value));
     }
   }
void rocksdb::DeleteFileTest::CheckFileTypeCounts (std::string & dir, int required_log, int required_sst, int required_manifest) inline
Definition at line 123 of file deletefile_test.cc.
References ASSERT_EQ, env_, rocksdb::Env::GetChildren(), rocksdb::kDescriptorFile, rocksdb::kLogFile, rocksdb::kTableFile, and rocksdb::ParseFileName().
{
     std::vector<std::string> filenames;
     env_->GetChildren(dir, &filenames);
     int log_cnt = 0, sst_cnt = 0, manifest_cnt = 0;
     for (auto file : filenames) {
       uint64_t number;
       FileType type;
       if (ParseFileName(file, &number, &type)) {
         log_cnt += (type == kLogFile);
         sst_cnt += (type == kTableFile);
         manifest_cnt += (type == kDescriptorFile);
       }
     }
     ASSERT_EQ(required_log, log_cnt);
     ASSERT_EQ(required_sst, sst_cnt);
     ASSERT_EQ(required_manifest, manifest_cnt);
   }
void rocksdb::DeleteFileTest::CloseDB () inline
Definition at line 71 of file deletefile_test.cc.
References db_.
                  {
     delete db_;
   }
void rocksdb::DeleteFileTest::CreateTwoLevels () inline
Definition at line 112 of file deletefile_test.cc.
References AddKeys(), ASSERT_OK, db_, rocksdb::DBImpl::TEST_FlushMemTable(), and rocksdb::DBImpl::TEST_WaitForFlushMemTable().
{
     AddKeys(50000, 10000);
     DBImpl* dbi = reinterpret_cast<DBImpl*>(db_);
     ASSERT_OK(dbi->TEST_FlushMemTable());
     ASSERT_OK(dbi->TEST_WaitForFlushMemTable());
     AddKeys(50000, 10000);
     ASSERT_OK(dbi->TEST_FlushMemTable());
     ASSERT_OK(dbi->TEST_WaitForFlushMemTable());
   }
int rocksdb::DeleteFileTest::numKeysInLevels (std::vector< LiveFileMetaData > & metadata, std::vector< int > * keysperlevel = nullptr) inline
Definition at line 87 of file deletefile_test.cc.
References name, and numlevels_.
{
     if (keysperlevel != nullptr) {
       keysperlevel->resize(numlevels_);
     }
     int numKeys = 0;
     for (size_t i = 0; i < metadata.size(); i++) {
       int startkey = atoi(metadata[i].smallestkey.c_str());
       int endkey = atoi(metadata[i].largestkey.c_str());
       int numkeysinfile = (endkey - startkey + 1);
       numKeys += numkeysinfile;
       if (keysperlevel != nullptr) {
         (*keysperlevel)[(int)metadata[i].level] += numkeysinfile;
       }
       fprintf(stderr, "level %d name %s smallest %s largest %s\n",
               metadata[i].level, metadata[i].name.c_str(),
               metadata[i].smallestkey.c_str(),
               metadata[i].largestkey.c_str());
     }
     return numKeys;
   }
Status rocksdb::DeleteFileTest::ReopenDB (bool create) inline
Definition at line 61 of file deletefile_test.cc.
References rocksdb::Options::create_if_missing, db_, dbname_, rocksdb::DestroyDB(), rocksdb::DB::Open(), and options_.
Referenced by DeleteFileTest().
{
     delete db_;
     if (create) {
       DestroyDB(dbname_, options_);
     }
     db_ = nullptr;
     options_.create_if_missing = create;
     return DB::Open(options_, dbname_, &db_);
   }
Member Data Documentation
DB* rocksdb::DeleteFileTest::db_
Definition at line 30 of file deletefile_test.cc.
Referenced by AddKeys(), CloseDB(), CreateTwoLevels(), DeleteFileTest(), and ReopenDB().
std::string rocksdb::DeleteFileTest::dbname_
Definition at line 28 of file deletefile_test.cc.
Referenced by DeleteFileTest(), and ReopenDB().
Env* rocksdb::DeleteFileTest::env_
Definition at line 31 of file deletefile_test.cc.
Referenced by CheckFileTypeCounts(), and DeleteFileTest().
int rocksdb::DeleteFileTest::numlevels_
Definition at line 32 of file deletefile_test.cc.
Referenced by DeleteFileTest(), and numKeysInLevels().
Options rocksdb::DeleteFileTest::options_
Definition at line 29 of file deletefile_test.cc.
Referenced by DeleteFileTest(), and ReopenDB().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/db/deletefile_test.cc