rippled: ripple::STPathSet Class Reference
ripple::STPathSet Class Reference
#include <SerializedTypes.h>
Public Member Functions
STPathSet ()
STPathSet (SField::ref n)
STPathSet (const std::vector< STPath > &v)
STPathSet (SField::ref n, const std::vector< STPath > &v)
void add (Serializer &s) const
virtual Json::Value getJson (int) const
SerializedTypeID getSType () const
int size () const
void reserve (size_t n)
const STPath & getPath (int off) const
STPath & peekPath (int off)
bool isEmpty () const
void clear ()
void addPath (const STPath &e)
void addUniquePath (const STPath &e)
bool assembleAdd (STPath const &base, STPathElement const &tail)
virtual bool isEquivalent (const SerializedType &t) const
virtual bool isDefault () const
void printDebug ()
STPath & operator[] (size_t n)
STPath const & operator[] (size_t n) const
std::vector< STPath >::iterator begin ()
std::vector< STPath >::iterator end ()
std::vector< STPath >
::const_iterator begin () const
std::vector< STPath >
::const_iterator end () const
Public Member Functions inherited from ripple::SerializedType
SerializedType ()
SerializedType (SField::ref n)
virtual ~SerializedType ()
void setFName (SField::ref n)
SField::ref getFName () const
std::string getName () const
std::unique_ptr< SerializedType > clone () const
virtual std::string getFullText () const
virtual std::string getText () const
void addFieldID (Serializer &s) const
SerializedType & operator= (const SerializedType &t)
bool operator== (const SerializedType &t) const
bool operator!= (const SerializedType &t) const
template<class D >
D & downcast ()
template<class D >
D const & downcast () const
Static Public Member Functions
static std::unique_ptr
< SerializedType > deserialize (SerializerIterator &sit, SField::ref name)
Static Public Member Functions inherited from ripple::SerializedType
static std::unique_ptr
< SerializedType > deserialize (SField::ref name)
Private Member Functions
STPathSet * duplicate () const
Static Private Member Functions
static STPathSet * construct (SerializerIterator &, SField::ref)
Private Attributes
std::vector< STPath > value
Additional Inherited Members
Protected Attributes inherited from ripple::SerializedType
SField::ptr fName
Detailed Description
Definition at line 1374 of file SerializedTypes.h.
Constructor & Destructor Documentation
ripple::STPathSet::STPathSet () inline
Definition at line 1377 of file SerializedTypes.h.
Referenced by construct().
     {
         ;
     }
ripple::STPathSet::STPathSet (SField::ref n) inline explicit
Definition at line 1382 of file SerializedTypes.h.
                                      : SerializedType (n)
     {
         ;
     }
ripple::STPathSet::STPathSet (const std::vector< STPath > & v) inline explicit
Definition at line 1387 of file SerializedTypes.h.
                                                     : value (v)
     {
         ;
     }
ripple::STPathSet::STPathSet (SField::ref n, const std::vector< STPath > & v) inline
Definition at line 1392 of file SerializedTypes.h.
                                                         : SerializedType (n), value (v)
     {
         ;
     }
Member Function Documentation
void ripple::STPathSet::add (Serializer & s) const virtual
Reimplemented from ripple::SerializedType.
Definition at line 593 of file SerializedTypes.cpp.
References ripple::Serializer::add160(), ripple::Serializer::add8(), ripple::STPathElement::getAccountID(), ripple::STPathElement::getCurrency(), ripple::STPathElement::getIssuerID(), ripple::STPathElement::getNodeType(), ripple::STPathElement::typeAccount, ripple::STPathElement::typeBoundary, ripple::STPathElement::typeCurrency, ripple::STPathElement::typeEnd, ripple::STPathElement::typeIssuer, and value.
 {
     bool bFirst = true;
     BOOST_FOREACH (const STPath & spPath, value)
     {
         if (!bFirst)
         {
             s.add8 (STPathElement::typeBoundary);
         }
         BOOST_FOREACH (const STPathElement & speElement, spPath)
         {
             int     iType   = speElement.getNodeType ();
             s.add8 (iType);
             if (iType & STPathElement::typeAccount)
                 s.add160 (speElement.getAccountID ());
             if (iType & STPathElement::typeCurrency)
                 s.add160 (speElement.getCurrency ());
             if (iType & STPathElement::typeIssuer)
                 s.add160 (speElement.getIssuerID ());
         }
         bFirst = false;
     }
     s.add8 (STPathElement::typeEnd);
 }
void ripple::STPathSet::addPath (const STPath & e) inline
Definition at line 1434 of file SerializedTypes.h.
References value.
Referenced by ripple::Pathfinder::addLink(), ripple::RPCHandler::doRipplePathFind(), ripple::PathRequest::doUpdate(), ripple::Pathfinder::filterPaths(), ripple::Pathfinder::findPaths(), ripple::Pathfinder::getPaths(), and ripple::STParsedJSON::parse().
     {
         value.push_back (e);
     }
void ripple::STPathSet::addUniquePath (const STPath & e) inline
Definition at line 1438 of file SerializedTypes.h.
References value.
Referenced by ripple::Pathfinder::addLink().
     {
         BOOST_FOREACH(const STPath& p, value)
         {
             if (p == e)
                 return;
         }
         value.push_back (e);
     }
bool ripple::STPathSet::assembleAdd (STPath const & base, STPathElement const & tail) inline
Definition at line 1448 of file SerializedTypes.h.
References ripple::STPath::mPath, and value.
Referenced by ripple::Pathfinder::addLink().
     { // assemble base+tail and add it to the set if it's not a duplicate
         value.push_back (base);
         std::vector<STPath>::reverse_iterator it = value.rbegin ();
         STPath& newPath = *it;
         newPath.mPath.push_back (tail);
         while (++it != value.rend ())
         {
             if (it->mPath == newPath.mPath)
             {
                 value.pop_back ();
                 return false;
             }
         }
         return true;
     }
std::vector<STPath>::iterator ripple::STPathSet::begin () inline
Definition at line 1486 of file SerializedTypes.h.
References value.
Referenced by ripple::range_begin().
     {
         return value.begin ();
     }
std::vector<STPath>::const_iterator ripple::STPathSet::begin () const inline
Definition at line 1494 of file SerializedTypes.h.
References value.
     {
         return value.begin ();
     }
void ripple::STPathSet::clear () inline
Definition at line 1430 of file SerializedTypes.h.
References value.
     {
         value.clear ();
     }
STPathSet * ripple::STPathSet::construct (SerializerIterator & s, SField::ref name) static private
Definition at line 421 of file SerializedTypes.cpp.
References ripple::SerializerIterator::get160(), ripple::SerializerIterator::get8(), ripple::lsINFO, beast.util.CleanCPPFiles::path, STPathSet(), ripple::STPathElement::typeAccount, ripple::STPathElement::typeBoundary, ripple::STPathElement::typeCurrency, ripple::STPathElement::typeEnd, ripple::STPathElement::typeIssuer, ripple::STPathElement::typeValidBits, and WriteLog.
 {
     std::vector<STPath> paths;
     std::vector<STPathElement> path;
     do
     {
         int iType   = s.get8 ();
         if (iType == STPathElement::typeEnd || iType == STPathElement::typeBoundary)
         {
             if (path.empty ())
             {
                 WriteLog (lsINFO, SerializedType) << "STPathSet: Empty path.";
                 throw std::runtime_error ("empty path");
             }
             paths.push_back (path);
             path.clear ();
             if (iType == STPathElement::typeEnd)
             {
                 return new STPathSet (name, paths);
             }
         }
         else if (iType & ~STPathElement::typeValidBits)
         {
             WriteLog (lsINFO, SerializedType) << "STPathSet: Bad path element: " << iType;
             throw std::runtime_error ("bad path element");
         }
         else
         {
             const bool  bAccount    = !! (iType & STPathElement::typeAccount);
             const bool  bCurrency   = !! (iType & STPathElement::typeCurrency);
             const bool  bIssuer     = !! (iType & STPathElement::typeIssuer);
             uint160 uAccountID;
             uint160 uCurrency;
             uint160 uIssuerID;
             if (bAccount)
                 uAccountID  = s.get160 ();
             if (bCurrency)
                 uCurrency   = s.get160 ();
             if (bIssuer)
                 uIssuerID   = s.get160 ();
             path.push_back (STPathElement (uAccountID, uCurrency, uIssuerID, bCurrency));
         }
     }
     while (1);
 }
static std::unique_ptr<SerializedType> ripple::STPathSet::deserialize (SerializerIterator & sit, SField::ref name) inline static
Definition at line 1397 of file SerializedTypes.h.
Referenced by ripple::STObject::makeDeserializedObject().
     {
         return std::unique_ptr<SerializedType> (construct (sit, name));
     }
STPathSet* ripple::STPathSet::duplicate () const inline private virtual
Reimplemented from ripple::SerializedType.
Definition at line 1506 of file SerializedTypes.h.
References ripple::STPathElement::STPathSet.
     {
         return new STPathSet (*this);
     }
std::vector<STPath>::iterator ripple::STPathSet::end () inline
Definition at line 1490 of file SerializedTypes.h.
References value.
Referenced by ripple::range_end().
     {
         return value.end ();
     }
std::vector<STPath>::const_iterator ripple::STPathSet::end () const inline
Definition at line 1498 of file SerializedTypes.h.
References value.
     {
         return value.end ();
     }
Json::Value ripple::STPathSet::getJson (int options) const virtual
Reimplemented from ripple::SerializedType.
Definition at line 526 of file SerializedTypes.cpp.
References Json::Value::append(), Json::arrayValue, and value.
Referenced by ripple::RPCHandler::doRipplePathFind(), ripple::PathRequest::doUpdate(), ripple::Pathfinder::filterPaths(), and ripple::RPC::transactionSign().
 {
     Json::Value ret (Json::arrayValue);
     BOOST_FOREACH (std::vector<STPath>::const_iterator::value_type it, value)
     ret.append (it.getJson (options));
     return ret;
 }
const STPath& ripple::STPathSet::getPath (int off) const inline
Definition at line 1418 of file SerializedTypes.h.
References value.
     {
         return value[off];
     }
SerializedTypeID ripple::STPathSet::getSType () const inline virtual
Reimplemented from ripple::SerializedType.
Definition at line 1406 of file SerializedTypes.h.
     {
         return STI_PATHSET;
     }
virtual bool ripple::STPathSet::isDefault () const inline virtual
Reimplemented from ripple::SerializedType.
Definition at line 1470 of file SerializedTypes.h.
References value.
     {
         return value.empty ();
     }
bool ripple::STPathSet::isEmpty () const inline
Definition at line 1426 of file SerializedTypes.h.
References value.
Referenced by ripple::Pathfinder::getPaths(), ripple::RippleCalc::rippleCalc(), and ripple::RPC::transactionSign().
     {
         return value.empty ();
     }
bool ripple::STPathSet::isEquivalent (const SerializedType & t) const virtual
Reimplemented from ripple::SerializedType.
Definition at line 478 of file SerializedTypes.cpp.
References value.
 {
     const STPathSet* v = dynamic_cast<const STPathSet*> (&t);
     return v && (value == v->value);
 }
STPath& ripple::STPathSet::operator[] (size_t n) inline
Definition at line 1477 of file SerializedTypes.h.
References value.
     {
         return value[n];
     }
STPath const& ripple::STPathSet::operator[] (size_t n) const inline
Definition at line 1481 of file SerializedTypes.h.
References value.
     {
         return value[n];
     }
STPath& ripple::STPathSet::peekPath (int off) inline
Definition at line 1422 of file SerializedTypes.h.
References value.
     {
         return value[off];
     }
void ripple::STPathSet::printDebug ()
Definition at line 49 of file SerializedTypes.cpp.
References ripple::RippleAddress::humanAccountID(), ripple::RippleAddress::setAccountID(), and value.
 {
     // VFALCO NOTE Can't use Log::out() because of std::endl
     //
     for (int i = 0; i < value.size (); i++)
     {
         std::cerr << i << ": ";
         for (int j = 0; j < value[i].mPath.size (); j++)
         {
             //STPathElement pe = value[i].mPath[j];
             RippleAddress nad;
             nad.setAccountID (value[i].mPath[j].mAccountID);
             std::cerr << "    " << nad.humanAccountID ();
             //std::cerr << "    " << pe.mAccountID.GetHex();
         }
         std::cerr << std::endl;
     }
 }
void ripple::STPathSet::reserve (size_t n) inline
Definition at line 1414 of file SerializedTypes.h.
References value.
     {
         value.reserve(n);
     }
int ripple::STPathSet::size () const inline
Definition at line 1410 of file SerializedTypes.h.
References value.
Referenced by ripple::Pathfinder::addLink(), ripple::PaymentTransactor::doApply(), ripple::Pathfinder::filterPaths(), ripple::Pathfinder::findPaths(), ripple::Pathfinder::getPaths(), and ripple::RippleCalc::rippleCalc().
     {
         return value.size ();
     }
Member Data Documentation
std::vector<STPath> ripple::STPathSet::value private
Definition at line 1504 of file SerializedTypes.h.
Referenced by add(), getJson(), isEquivalent(), and printDebug().
The documentation for this class was generated from the following files:
rippled/src/ripple_data/protocol/SerializedTypes.h
rippled/src/ripple_data/protocol/SerializedTypes.cpp