rippled: ripple::SerializedTransaction Class Reference
ripple::SerializedTransaction Class Reference
#include <SerializedTransaction.h>
Public Types
typedef boost::shared_ptr
< SerializedTransaction > pointer
typedef const
boost::shared_ptr
< SerializedTransaction > & ref
Public Types inherited from ripple::STObject
typedef boost::ptr_vector
< SerializedType >::iterator iterator
typedef boost::ptr_vector
< SerializedType >
::const_iterator const_iterator
Public Member Functions
SerializedTransaction (SerializerIterator &sit)
SerializedTransaction (TxType type)
SerializedTransaction (const STObject &object)
SerializedTypeID getSType () const
std::string getFullText () const
std::string getText () const
Blob getSignature () const
void setSignature (Blob const &s)
uint256 getSigningHash () const
TxType getTxnType () const
STAmount getTransactionFee () const
void setTransactionFee (const STAmount &fee)
RippleAddress getSourceAccount () const
Blob getSigningPubKey () const
void setSigningPubKey (const RippleAddress &naSignPubKey)
void setSourceAccount (const RippleAddress &naSource)
std::string getTransactionType () const
std::uint32_t getSequence () const
void setSequence (std::uint32_t seq)
std::vector< RippleAddress > getMentionedAccounts () const
uint256 getTransactionID () const
virtual Json::Value getJson (int options) const
virtual Json::Value getJson (int options, bool binary) const
void sign (const RippleAddress &naAccountPrivate)
bool checkSign (const RippleAddress &naAccountPublic) const
bool checkSign () const
bool isKnownGood () const
bool isKnownBad () const
void setGood () const
void setBad () const
std::string getSQL (std::string &sql, std::uint32_t inLedger, char status) const
std::string getSQL (std::uint32_t inLedger, char status) const
std::string getSQL (Serializer rawTxn, std::uint32_t inLedger, char status) const
std::string getMetaSQL (std::uint32_t inLedger, const std::string &escapedMetaData) const
std::string getMetaSQL (Serializer rawTxn, std::uint32_t inLedger, char status, const std::string &escapedMetaData) const
Public Member Functions inherited from ripple::STObject
STObject ()
STObject (SField::ref name)
STObject (const SOTemplate &type, SField::ref name)
STObject (const SOTemplate &type, SerializerIterator &sit, SField::ref name)
STObject (SField::ref name, boost::ptr_vector< SerializedType > &data)
std::unique_ptr< STObject > oClone () const
virtual ~STObject ()
bool setType (const SOTemplate &type)
bool isValidForType ()
bool isFieldAllowed (SField::ref)
bool isFree () const
void set (const SOTemplate &)
bool set (SerializerIterator &u, int depth=0)
virtual bool isEquivalent (const SerializedType &t) const
virtual bool isDefault () const
virtual void add (Serializer &s) const
void add (Serializer &s, bool withSignature) const
Serializer getSerializer () const
std::string getFullText () const
std::string getText () const
int addObject (const SerializedType &t)
int giveObject (std::unique_ptr< SerializedType > t)
int giveObject (SerializedType *t)
const boost::ptr_vector
< SerializedType > & peekData () const
boost::ptr_vector
< SerializedType > & peekData ()
SerializedType & front ()
const SerializedType & front () const
SerializedType & back ()
const SerializedType & back () const
int getCount () const
bool setFlag (std::uint32_t)
bool clearFlag (std::uint32_t)
bool isFlag (std::uint32_t) const
std::uint32_t getFlags () const
uint256 getHash (std::uint32_t prefix) const
uint256 getSigningHash (std::uint32_t prefix) const
const SerializedType & peekAtIndex (int offset) const
SerializedType & getIndex (int offset)
const SerializedType * peekAtPIndex (int offset) const
SerializedType * getPIndex (int offset)
int getFieldIndex (SField::ref field) const
SField::ref getFieldSType (int index) const
const SerializedType & peekAtField (SField::ref field) const
SerializedType & getField (SField::ref field)
const SerializedType * peekAtPField (SField::ref field) const
SerializedType * getPField (SField::ref field, bool createOkay=false)
std::string getFieldString (SField::ref field) const
unsigned char getFieldU8 (SField::ref field) const
std::uint16_t getFieldU16 (SField::ref field) const
std::uint32_t getFieldU32 (SField::ref field) const
std::uint64_t getFieldU64 (SField::ref field) const
uint128 getFieldH128 (SField::ref field) const
uint160 getFieldH160 (SField::ref field) const
uint256 getFieldH256 (SField::ref field) const
RippleAddress getFieldAccount (SField::ref field) const
uint160 getFieldAccount160 (SField::ref field) const
Blob getFieldVL (SField::ref field) const
const STAmount & getFieldAmount (SField::ref field) const
const STPathSet & getFieldPathSet (SField::ref field) const
const STVector256 & getFieldV256 (SField::ref field) const
const STArray & getFieldArray (SField::ref field) const
void setFieldU8 (SField::ref field, unsigned char)
void setFieldU16 (SField::ref field, std::uint16_t)
void setFieldU32 (SField::ref field, std::uint32_t)
void setFieldU64 (SField::ref field, std::uint64_t)
void setFieldH128 (SField::ref field, const uint128 &)
void setFieldH160 (SField::ref field, const uint160 &)
void setFieldH256 (SField::ref field, uint256 const &)
void setFieldVL (SField::ref field, Blob const &)
void setFieldAccount (SField::ref field, const uint160 &)
void setFieldAccount (SField::ref field, const RippleAddress &addr)
void setFieldAmount (SField::ref field, const STAmount &)
void setFieldPathSet (SField::ref field, const STPathSet &)
void setFieldV256 (SField::ref field, const STVector256 &v)
STObject & peekFieldObject (SField::ref field)
bool isFieldPresent (SField::ref field) const
SerializedType * makeFieldPresent (SField::ref field)
void makeFieldAbsent (SField::ref field)
bool delField (SField::ref field)
void delField (int index)
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
bool empty () const
bool hasMatchingEntry (const SerializedType &)
bool operator== (const STObject &o) const
bool operator!= (const STObject &o) const
Public Member Functions inherited from ripple::SerializedType
SerializedType ()
SerializedType (SField::ref n)
virtual ~SerializedType ()
void setFName (SField::ref n)
SField::ref getFName () const
std::string getName () const
std::unique_ptr< SerializedType > clone () const
void addFieldID (Serializer &s) const
SerializedType & operator= (const SerializedType &t)
bool operator== (const SerializedType &t) const
bool operator!= (const SerializedType &t) const
template<class D >
D & downcast ()
template<class D >
D const & downcast () const
Public Member Functions inherited from ripple::CountedObject< STObject >
CountedObject ()
CountedObject (CountedObject const &)
~CountedObject ()
Public Member Functions inherited from ripple::CountedObject< SerializedTransaction >
CountedObject ()
CountedObject (CountedObject const &)
~CountedObject ()
Static Public Member Functions
static char const * getCountedObjectName ()
static std::string getSQLValueHeader ()
static std::string getSQLInsertHeader ()
static std::string getSQLInsertIgnoreHeader ()
static std::string getMetaSQLValueHeader ()
static std::string getMetaSQLInsertReplaceHeader ()
Static Public Member Functions inherited from ripple::STObject
static char const * getCountedObjectName ()
static std::unique_ptr
< SerializedType > deserialize (SerializerIterator &sit, SField::ref name)
static std::unique_ptr
< SerializedType > makeDefaultObject (SerializedTypeID id, SField::ref name)
static std::unique_ptr
< SerializedType > makeDeserializedObject (SerializedTypeID id, SField::ref name, SerializerIterator &, int depth)
static std::unique_ptr
< SerializedType > makeNonPresentObject (SField::ref name)
static std::unique_ptr
< SerializedType > makeDefaultObject (SField::ref name)
Static Public Member Functions inherited from ripple::SerializedType
static std::unique_ptr
< SerializedType > deserialize (SField::ref name)
Private Member Functions
SerializedTransaction * duplicate () const
Private Attributes
TxType mType
TxFormats::Item const * mFormat
bool mSigGood
bool mSigBad
Additional Inherited Members
Protected Attributes inherited from ripple::SerializedType
SField::ptr fName
Detailed Description
Definition at line 34 of file SerializedTransaction.h.
Member Typedef Documentation
typedef boost::shared_ptr<SerializedTransaction> ripple::SerializedTransaction::pointer
Definition at line 41 of file SerializedTransaction.h.
typedef const boost::shared_ptr<SerializedTransaction>& ripple::SerializedTransaction::ref
Definition at line 42 of file SerializedTransaction.h.
Constructor & Destructor Documentation
ripple::SerializedTransaction::SerializedTransaction (SerializerIterator & sit)
Definition at line 65 of file SerializedTransaction.cpp.
References ripple::KnownFormats< KeyType >::findByType(), ripple::SerializerIterator::getBytesLeft(), ripple::STObject::getFieldU16(), ripple::TxFormats::getInstance(), rocksdb::Log(), ripple::lsERROR, ripple::lsWARNING, mFormat, mType, ripple::STObject::set(), ripple::STObject::setType(), ripple::Protocol::txMaxSizeBytes, ripple::Protocol::txMinSizeBytes, and WriteLog.
Referenced by duplicate().
                                                                      : STObject (sfTransaction),
     mSigGood (false), mSigBad (false)
 {
     int length = sit.getBytesLeft ();
     if ((length < Protocol::txMinSizeBytes) || (length > Protocol::txMaxSizeBytes))
     {
         Log (lsERROR) << "Transaction has invalid length: " << length;
         throw std::runtime_error ("Transaction length invalid");
     }
     set (sit);
     mType = static_cast<TxType> (getFieldU16 (sfTransactionType));
     mFormat = TxFormats::getInstance()->findByType (mType);
     if (!mFormat)
     {
         WriteLog (lsWARNING, SerializedTransaction) << "Transaction type: " << mType;
         throw std::runtime_error ("invalid transaction type");
     }
     if (!setType (mFormat->elements))
     {
         WriteLog (lsWARNING, SerializedTransaction) << "Transaction not legal for format";
         throw std::runtime_error ("transaction not valid");
     }
 }
ripple::SerializedTransaction::SerializedTransaction (TxType type)
Definition at line 26 of file SerializedTransaction.cpp.
References ripple::KnownFormats< KeyType >::findByType(), ripple::TxFormats::getInstance(), ripple::lsWARNING, and WriteLog.
     : STObject (sfTransaction)
     , mType (type)
     , mSigGood (false)
     , mSigBad (false)
 {
     mFormat = TxFormats::getInstance()->findByType (type);
     if (mFormat == nullptr)
     {
         WriteLog (lsWARNING, SerializedTransaction) << "Transaction type: " << type;
         throw std::runtime_error ("invalid transaction type");
     }
     set (mFormat->elements);
     setFieldU16 (sfTransactionType, mFormat->getType ());
 }
ripple::SerializedTransaction::SerializedTransaction (const STObject & object)
Definition at line 44 of file SerializedTransaction.cpp.
References ripple::KnownFormats< KeyType >::findByType(), ripple::STObject::getFieldU16(), ripple::TxFormats::getInstance(), ripple::lsWARNING, mFormat, mType, ripple::STObject::setType(), and WriteLog.
     : STObject (object)
     , mSigGood (false)
     , mSigBad (false)
 {
     mType = static_cast <TxType> (getFieldU16 (sfTransactionType));
     mFormat = TxFormats::getInstance()->findByType (mType);
     if (!mFormat)
     {
         WriteLog (lsWARNING, SerializedTransaction) << "Transaction type: " << mType;
         throw std::runtime_error ("invalid transaction type");
     }
     if (!setType (mFormat->elements))
     {
         throw std::runtime_error ("transaction not valid");
     }
 }
Member Function Documentation
bool ripple::SerializedTransaction::checkSign (const RippleAddress & naAccountPublic) const
Definition at line 220 of file SerializedTransaction.cpp.
References ripple::RippleAddress::accountPublicVerify(), ripple::STObject::getFieldVL(), ripple::STObject::getFlags(), getSigningHash(), and ripple::tfFullyCanonicalSig.
Referenced by ripple::Transactor::preCheck(), and ripple::SerializedTransaction_test::run().
 {
     try
     {
         const ECDSA fullyCanonical = (getFlags() & tfFullyCanonicalSig) ?
                                               ECDSA::strict : ECDSA::not_strict;
         return naAccountPublic.accountPublicVerify (getSigningHash (), getFieldVL (sfTxnSignature), fullyCanonical);
     }
     catch (...)
     {
         return false;
     }
 }
bool ripple::SerializedTransaction::checkSign () const
Definition at line 192 of file SerializedTransaction.cpp.
References ripple::STObject::getFieldVL(), mSigBad, mSigGood, and ripple::RippleAddress::setAccountPublic().
 {
     if (mSigGood)
         return true;
     if (mSigBad)
         return false;
     try
     {
         RippleAddress n;
         n.setAccountPublic (getFieldVL (sfSigningPubKey));
         if (checkSign (n))
         {
             mSigGood = true;
             return true;
         }
     }
     catch (...)
     {
         ;
     }
     mSigBad = true;
     return false;
 }
SerializedTransaction* ripple::SerializedTransaction::duplicate () const inline private virtual
Reimplemented from ripple::SerializedType.
Definition at line 147 of file SerializedTransaction.h.
References SerializedTransaction().
     {
         return new SerializedTransaction (*this);
     }
static char const* ripple::SerializedTransaction::getCountedObjectName () inline static
Definition at line 39 of file SerializedTransaction.h.
 { return "SerializedTransaction"; }
std::string ripple::SerializedTransaction::getFullText () const virtual
Reimplemented from ripple::SerializedType.
Definition at line 94 of file SerializedTransaction.cpp.
References ripple::STObject::getFullText(), ripple::base_uint< BITS >::GetHex(), and getTransactionID().
 {
     std::string ret = "\"";
     ret += getTransactionID ().GetHex ();
     ret += "\" = {";
     ret += STObject::getFullText ();
     ret += "}";
     return ret;
 }
Json::Value ripple::SerializedTransaction::getJson (int options) const virtual
Reimplemented from ripple::STObject.
Definition at line 244 of file SerializedTransaction.cpp.
References ripple::base_uint< BITS >::GetHex(), ripple::STObject::getJson(), and getTransactionID().
Referenced by ripple::TransactionEngine::applyTransaction(), ripple::OfferCreateTransactor::doApply(), getJson(), ripple::Ledger::getJson(), ripple::SerializedTransaction_test::run(), and ripple::NetworkOPsImp::transJson().
 {
     Json::Value ret = STObject::getJson (0);
     ret["hash"] = getTransactionID ().GetHex ();
     return ret;
 }
Json::Value ripple::SerializedTransaction::getJson (int options, bool binary) const virtual
Definition at line 251 of file SerializedTransaction.cpp.
References ripple::base_uint< BITS >::GetHex(), getJson(), ripple::STObject::getSerializer(), getTransactionID(), ripple::Serializer::peekData(), and ripple::strHex().
 {
     if (binary)
     {
         Json::Value ret;
         Serializer s = STObject::getSerializer ();
         ret["tx"] = strHex (s.peekData ());
         ret["hash"] = getTransactionID ().GetHex ();
         return ret;
     }
     return getJson(options);
 }
std::vector< RippleAddress > ripple::SerializedTransaction::getMentionedAccounts () const
Definition at line 109 of file SerializedTransaction.cpp.
References ripple::RPC::accounts(), ripple::STAmount::getIssuer(), ripple::STAccount::getValueNCA(), ripple::base_uint< BITS >::isNonZero(), ripple::STObject::peekData(), and ripple::RippleAddress::setAccountID().
 {
     std::vector<RippleAddress> accounts;
     BOOST_FOREACH (const SerializedType & it, peekData ())
     {
         const STAccount* sa = dynamic_cast<const STAccount*> (&it);
         if (sa != nullptr)
         {
             bool found = false;
             RippleAddress na = sa->getValueNCA ();
             BOOST_FOREACH (const RippleAddress & it, accounts)
             {
                 if (it == na)
                 {
                     found = true;
                     break;
                 }
             }
             if (!found)
                 accounts.push_back (na);
         }
         const STAmount* sam = dynamic_cast<const STAmount*> (&it);
         if (sam)
         {
             uint160 issuer = sam->getIssuer ();
             if (issuer.isNonZero ())
             {
                 RippleAddress na;
                 na.setAccountID (issuer);
                 bool found = false;
                 BOOST_FOREACH (const RippleAddress & it, accounts)
                 {
                     if (it == na)
                     {
                         found = true;
                         break;
                     }
                 }
                 if (!found)
                     accounts.push_back (na);
             }
         }
     }
     return accounts;
 }
std::string ripple::SerializedTransaction::getMetaSQL (std::uint32_t inLedger, const std::string & escapedMetaData) const
Definition at line 286 of file SerializedTransaction.cpp.
References ripple::STObject::add(), and TXN_SQL_VALIDATED.
 {
     Serializer s;
     add (s);
     return getMetaSQL (s, inLedger, TXN_SQL_VALIDATED, escapedMetaData);
 }
std::string ripple::SerializedTransaction::getMetaSQL (Serializer rawTxn, std::uint32_t inLedger, char status, const std::string & escapedMetaData) const
Definition at line 304 of file SerializedTransaction.cpp.
References getSequence(), getSourceAccount(), getTransactionID(), getTransactionType(), ripple::Serializer::peekData(), and ripple::sqlEscape().
 {
     static boost::format bfTrans ("('%s', '%s', '%s', '%d', '%d', '%c', %s, %s)");
     std::string rTxn    = sqlEscape (rawTxn.peekData ());
     return str (boost::format (bfTrans)
                 % getTransactionID ().GetHex () % getTransactionType () % getSourceAccount ().humanAccountID ()
                 % getSequence () % inLedger % status % rTxn % escapedMetaData);
 }
std::string ripple::SerializedTransaction::getMetaSQLInsertReplaceHeader () static
Definition at line 274 of file SerializedTransaction.cpp.
References getMetaSQLValueHeader().
Referenced by ripple::Ledger::saveValidatedLedger().
 {
     return "INSERT OR REPLACE INTO Transactions " + getMetaSQLValueHeader () + " VALUES ";
 }
std::string ripple::SerializedTransaction::getMetaSQLValueHeader () static
Definition at line 269 of file SerializedTransaction.cpp.
Referenced by getMetaSQLInsertReplaceHeader().
 {
     return "(TransID, TransType, FromAcct, FromSeq, LedgerSeq, Status, RawTxn, TxnMeta)";
 }
std::uint32_t ripple::SerializedTransaction::getSequence () const inline
Definition at line 93 of file SerializedTransaction.h.
References ripple::STObject::getFieldU32().
Referenced by ripple::TransactionEngine::applyTransaction(), ripple::Transactor::checkSeq(), ripple::ChangeTransactor::checkSeq(), ripple::OfferCreateTransactor::doApply(), getMetaSQL(), and getSQL().
     {
         return getFieldU32 (sfSequence);
     }
Blob ripple::SerializedTransaction::getSignature () const
Definition at line 173 of file SerializedTransaction.cpp.
References ripple::STObject::getFieldVL().
Referenced by ripple::ChangeTransactor::checkSig().
 {
     try
     {
         return getFieldVL (sfTxnSignature);
     }
     catch (...)
     {
         return Blob ();
     }
 }
uint256 ripple::SerializedTransaction::getSigningHash () const
Definition at line 162 of file SerializedTransaction.cpp.
References ripple::getConfig(), and ripple::STObject::getSigningHash().
Referenced by checkSign(), and sign().
 {
     return STObject::getSigningHash (getConfig ().SIGN_TRANSACTION);
 }
Blob ripple::SerializedTransaction::getSigningPubKey () const inline
Definition at line 82 of file SerializedTransaction.h.
References ripple::STObject::getFieldVL().
Referenced by ripple::ChangeTransactor::checkSig(), and ripple::Transactor::preCheck().
     {
         return getFieldVL (sfSigningPubKey);
     }
RippleAddress ripple::SerializedTransaction::getSourceAccount () const inline
Definition at line 78 of file SerializedTransaction.h.
References ripple::STObject::getFieldAccount().
Referenced by ripple::Transactor::apply(), ripple::TransactionEngine::applyTransaction(), getMetaSQL(), getSQL(), ripple::Transactor::preCheck(), and ripple::ChangeTransactor::preCheck().
     {
         return getFieldAccount (sfAccount);
     }
std::string ripple::SerializedTransaction::getSQL (std::string & sql, std::uint32_t inLedger, char status) const
Referenced by getSQL().
std::string ripple::SerializedTransaction::getSQL (std::uint32_t inLedger, char status) const
Definition at line 279 of file SerializedTransaction.cpp.
References ripple::STObject::add(), and getSQL().
 {
     Serializer s;
     add (s);
     return getSQL (s, inLedger, status);
 }
std::string ripple::SerializedTransaction::getSQL (Serializer rawTxn, std::uint32_t inLedger, char status) const
Definition at line 294 of file SerializedTransaction.cpp.
References getSequence(), getSourceAccount(), getTransactionID(), getTransactionType(), ripple::Serializer::peekData(), and ripple::sqlEscape().
 {
     static boost::format bfTrans ("('%s', '%s', '%s', '%d', '%d', '%c', %s)");
     std::string rTxn    = sqlEscape (rawTxn.peekData ());
     return str (boost::format (bfTrans)
                 % getTransactionID ().GetHex () % getTransactionType () % getSourceAccount ().humanAccountID ()
                 % getSequence () % inLedger % status % rTxn);
 }
static std::string ripple::SerializedTransaction::getSQLInsertHeader () static
static std::string ripple::SerializedTransaction::getSQLInsertIgnoreHeader () static
std::string ripple::SerializedTransaction::getSQLValueHeader () static
Definition at line 264 of file SerializedTransaction.cpp.
 {
     return "(TransID, TransType, FromAcct, FromSeq, LedgerSeq, Status, RawTxn)";
 }
SerializedTypeID ripple::SerializedTransaction::getSType () const inline virtual
Reimplemented from ripple::STObject.
Definition at line 50 of file SerializedTransaction.h.
     {
         return STI_TRANSACTION;
     }
std::string ripple::SerializedTransaction::getText () const virtual
Reimplemented from ripple::SerializedType.
Definition at line 104 of file SerializedTransaction.cpp.
References ripple::STObject::getText().
 {
     return STObject::getText ();
 }
STAmount ripple::SerializedTransaction::getTransactionFee () const inline
Definition at line 69 of file SerializedTransaction.h.
References ripple::STObject::getFieldAmount().
Referenced by ripple::TransactionEngine::applyTransaction(), ripple::WalletAddTransactor::doApply(), ripple::PaymentTransactor::doApply(), ripple::Script::Interpreter::interpret(), ripple::Transactor::payFee(), and ripple::ChangeTransactor::payFee().
     {
         return getFieldAmount (sfFee);
     }
uint256 ripple::SerializedTransaction::getTransactionID () const
Definition at line 167 of file SerializedTransaction.cpp.
References ripple::STObject::getHash(), and ripple::HashPrefix::transactionID.
Referenced by ripple::TransactionEngine::applyTransaction(), ripple::Transactor::checkSeq(), ripple::FeaturesImpl::doVoting(), ripple::FeeVoteImpl::doVoting(), getFullText(), getJson(), getMetaSQL(), and getSQL().
 {
     // perhaps we should cache this
     return getHash (HashPrefix::transactionID);
 }
std::string ripple::SerializedTransaction::getTransactionType () const inline
Definition at line 88 of file SerializedTransaction.h.
References mFormat.
Referenced by getMetaSQL(), and getSQL().
     {
         return mFormat->getName ();
     }
TxType ripple::SerializedTransaction::getTxnType () const inline
Definition at line 65 of file SerializedTransaction.h.
References mType.
Referenced by ripple::ChangeTransactor::doApply(), and ripple::Transactor::makeTransactor().
     {
         return mType;
     }
bool ripple::SerializedTransaction::isKnownBad () const inline
Definition at line 116 of file SerializedTransaction.h.
References mSigBad.
Referenced by ripple::Transactor::preCheck().
     {
         return mSigBad;
     }
bool ripple::SerializedTransaction::isKnownGood () const inline
Definition at line 112 of file SerializedTransaction.h.
References mSigGood.
Referenced by ripple::Transactor::preCheck().
     {
         return mSigGood;
     }
void ripple::SerializedTransaction::setBad () const inline
Definition at line 124 of file SerializedTransaction.h.
References mSigBad.
Referenced by ripple::Transactor::preCheck().
     {
         mSigBad = true;
     }
void ripple::SerializedTransaction::setGood () const inline
Definition at line 120 of file SerializedTransaction.h.
References mSigGood.
Referenced by ripple::Transactor::preCheck().
     {
         mSigGood = true;
     }
void ripple::SerializedTransaction::setSequence (std::uint32_t seq) inline
Definition at line 97 of file SerializedTransaction.h.
References ripple::STObject::setFieldU32().
     {
         return setFieldU32 (sfSequence, seq);
     }
void ripple::SerializedTransaction::setSignature (Blob const & s) inline
Definition at line 59 of file SerializedTransaction.h.
References ripple::STObject::setFieldVL().
     {
         setFieldVL (sfTxnSignature, s);
     }
void ripple::SerializedTransaction::setSigningPubKey (const RippleAddress & naSignPubKey)
Definition at line 234 of file SerializedTransaction.cpp.
References ripple::RippleAddress::getAccountPublic(), and ripple::STObject::setFieldVL().
Referenced by ripple::SerializedTransaction_test::run().
 {
     setFieldVL (sfSigningPubKey, naSignPubKey.getAccountPublic ());
 }
void ripple::SerializedTransaction::setSourceAccount (const RippleAddress & naSource)
Definition at line 239 of file SerializedTransaction.cpp.
References ripple::STObject::setFieldAccount().
Referenced by ripple::SerializedTransaction_test::run().
 {
     setFieldAccount (sfAccount, naSource);
 }
void ripple::SerializedTransaction::setTransactionFee (const STAmount & fee) inline
Definition at line 73 of file SerializedTransaction.h.
References ripple::STObject::setFieldAmount().
     {
         setFieldAmount (sfFee, fee);
     }
void ripple::SerializedTransaction::sign (const RippleAddress & naAccountPrivate)
Definition at line 185 of file SerializedTransaction.cpp.
References ripple::RippleAddress::accountPrivateSign(), getSigningHash(), and ripple::STObject::setFieldVL().
Referenced by ripple::SerializedTransaction_test::run().
 {
     Blob signature;
     naAccountPrivate.accountPrivateSign (getSigningHash (), signature);
     setFieldVL (sfTxnSignature, signature);
 }
Member Data Documentation
TxFormats::Item const* ripple::SerializedTransaction::mFormat private
Definition at line 145 of file SerializedTransaction.h.
Referenced by getTransactionType(), and SerializedTransaction().
bool ripple::SerializedTransaction::mSigBad mutable private
Definition at line 153 of file SerializedTransaction.h.
Referenced by checkSign(), isKnownBad(), and setBad().
bool ripple::SerializedTransaction::mSigGood mutable private
Definition at line 152 of file SerializedTransaction.h.
Referenced by checkSign(), isKnownGood(), and setGood().
TxType ripple::SerializedTransaction::mType private
Definition at line 144 of file SerializedTransaction.h.
Referenced by getTxnType(), and SerializedTransaction().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/misc/SerializedTransaction.h
rippled/src/ripple_app/misc/SerializedTransaction.cpp