rippled: rippled/src/ripple/rocksdb/rocksdb/tools/blob_store_bench.cc File Reference
blob_store_bench.cc File Reference
#include <cstdio>
#include <vector>
#include <atomic>
#include "rocksdb/env.h"
#include "util/blob_store.h"
#include "util/testutil.h"
Classes
struct Result
struct WorkerThread
Macros
#define KB 1024LL
#define MB 1024*1024LL
#define NDEBUG
Functions
static std::string RandomString (Random *rnd, uint64_t len)
Result operator+ (const Result &a, const Result &b)
static void WorkerThreadBody (void *arg)
Result StartBenchmark (vector< WorkerThread * > &config)
vector< WorkerThread * > SetupBenchmarkBalanced ()
vector< WorkerThread * > SetupBenchmarkWriteHeavy ()
vector< WorkerThread * > SetupBenchmarkReadHeavy ()
int main (int argc, const char **argv)
Variables
uint64_t timeout_sec
Env * env
BlobStore * bs
Macro Definition Documentation
#define KB 1024LL
Definition at line 9 of file blob_store_bench.cc.
Referenced by SetupBenchmarkBalanced(), SetupBenchmarkReadHeavy(), and SetupBenchmarkWriteHeavy().
#define MB 1024*1024LL
Definition at line 10 of file blob_store_bench.cc.
Referenced by SetupBenchmarkBalanced(), SetupBenchmarkReadHeavy(), and SetupBenchmarkWriteHeavy().
#define NDEBUG
Definition at line 15 of file blob_store_bench.cc.
Function Documentation
int main (int argc, const char ** argv)
Definition at line 245 of file blob_store_bench.cc.
References rocksdb::Env::Default(), env, Result::print(), SetupBenchmarkBalanced(), SetupBenchmarkReadHeavy(), SetupBenchmarkWriteHeavy(), and StartBenchmark().
{
   srand(33);
   env = Env::Default();
   {
     printf("--- Balanced read/write benchmark ---\n");
     vector <WorkerThread*> config = SetupBenchmarkBalanced();
     Result r = StartBenchmark(config);
     r.print();
   }
   {
     printf("--- Write heavy benchmark ---\n");
     vector <WorkerThread*> config = SetupBenchmarkWriteHeavy();
     Result r = StartBenchmark(config);
     r.print();
   }
   {
     printf("--- Read heavy benchmark ---\n");
     vector <WorkerThread*> config = SetupBenchmarkReadHeavy();
     Result r = StartBenchmark(config);
     r.print();
   }
   return 0;
 }
Result operator+ (const Result & a, const Result & b)
Definition at line 62 of file blob_store_bench.cc.
References Result::data_read, Result::data_written, Result::deletes, Result::reads, and Result::writes.
{
   return Result(a.writes + b.writes, a.reads + b.reads,
                 a.deletes + b.deletes, a.data_written + b.data_written,
                 a.data_read + b.data_read);
 }
static std::string RandomString (Random * rnd, uint64_t len) static
Definition at line 26 of file blob_store_bench.cc.
References rocksdb::test::RandomString().
{
   std::string r;
   test::RandomString(rnd, len, &r);
   return r;
 }
vector<WorkerThread*> SetupBenchmarkBalanced ()
Definition at line 155 of file blob_store_bench.cc.
References bs, env, rocksdb::Env::GetTestDirectory(), KB, MB, and timeout_sec.
Referenced by main().
{
   string test_path;
   env->GetTestDirectory(&test_path);
   test_path.append("/blob_store");
   // config start
   uint32_t block_size = 16*KB;
   uint32_t file_size = 1*MB;
   double read_write_ratio = 0.5;
   uint64_t data_read_from = 16*KB;
   uint64_t data_read_to = 32*KB;
   int number_of_threads = 10;
   uint64_t working_set_size = 5*MB;
   timeout_sec = 5;
   // config end
   bs = new BlobStore(test_path, block_size, file_size / block_size, 10000, env);
   vector <WorkerThread*> config;
   for (int i = 0; i < number_of_threads; ++i) {
     config.push_back(new WorkerThread(data_read_from,
                                       data_read_to,
                                       read_write_ratio,
                                       working_set_size));
   };
   return config;
 }
vector<WorkerThread*> SetupBenchmarkReadHeavy ()
Definition at line 215 of file blob_store_bench.cc.
References bs, env, rocksdb::Env::GetTestDirectory(), KB, MB, and timeout_sec.
Referenced by main().
{
   string test_path;
   env->GetTestDirectory(&test_path);
   test_path.append("/blob_store");
   // config start
   uint32_t block_size = 16*KB;
   uint32_t file_size = 1*MB;
   double read_write_ratio = 0.9;
   uint64_t data_read_from = 16*KB;
   uint64_t data_read_to = 32*KB;
   int number_of_threads = 10;
   uint64_t working_set_size = 5*MB;
   timeout_sec = 5;
   // config end
   bs = new BlobStore(test_path, block_size, file_size / block_size, 10000, env);
   vector <WorkerThread*> config;
   for (int i = 0; i < number_of_threads; ++i) {
     config.push_back(new WorkerThread(data_read_from,
                                       data_read_to,
                                       read_write_ratio,
                                       working_set_size));
   };
   return config;
 }
vector<WorkerThread*> SetupBenchmarkWriteHeavy ()
Definition at line 185 of file blob_store_bench.cc.
References bs, env, rocksdb::Env::GetTestDirectory(), KB, MB, and timeout_sec.
Referenced by main().
{
   string test_path;
   env->GetTestDirectory(&test_path);
   test_path.append("/blob_store");
   // config start
   uint32_t block_size = 16*KB;
   uint32_t file_size = 1*MB;
   double read_write_ratio = 0.1;
   uint64_t data_read_from = 16*KB;
   uint64_t data_read_to = 32*KB;
   int number_of_threads = 10;
   uint64_t working_set_size = 5*MB;
   timeout_sec = 5;
   // config end
   bs = new BlobStore(test_path, block_size, file_size / block_size, 10000, env);
   vector <WorkerThread*> config;
   for (int i = 0; i < number_of_threads; ++i) {
     config.push_back(new WorkerThread(data_read_from,
                                       data_read_to,
                                       read_write_ratio,
                                       working_set_size));
   };
   return config;
 }
Result StartBenchmark (vector< WorkerThread * > & config)
Definition at line 134 of file blob_store_bench.cc.
References bs, env, rocksdb::Env::StartThread(), and WorkerThreadBody().
Referenced by main().
{
   for (auto w : config) {
     env->StartThread(WorkerThreadBody, w);
   }
   Result result;
   for (auto w : config) {
     while (!w->stopped.load());
     result = result + w->result;
   }
   for (auto w : config) {
     delete w;
   }
   delete bs;
   return result;
 }
static void WorkerThreadBody (void * arg) static
Definition at line 87 of file blob_store_bench.cc.
References arg, bs, Result::data_read, WorkerThread::data_size_from, WorkerThread::data_size_to, Result::data_written, rocksdb::BlobStore::Delete(), Result::deletes, env, beast.util.Iter::first(), rocksdb::BlobStore::Get(), rocksdb::Env::NowMicros(), rocksdb::Status::ok(), rocksdb::BlobStore::Put(), rand, rocksdb::RandomString(), WorkerThread::read_ratio, Result::reads, WorkerThread::result, WorkerThread::stopped, timeout_sec, WorkerThread::working_set_size, and Result::writes.
Referenced by StartBenchmark().
{
   WorkerThread* t = reinterpret_cast<WorkerThread*>(arg);
   Random rnd(5);
   string buf;
   vector<pair<Blob, uint64_t>> blobs;
   vector<string> random_strings;
   for (int i = 0; i < 10; ++i) {
     random_strings.push_back(RandomString(&rnd, t->data_size_to));
   }
   uint64_t total_size = 0;
   uint64_t start_micros = env->NowMicros();
   while (env->NowMicros() - start_micros < timeout_sec * 1000 * 1000) {
     if (blobs.size() && rand() < RAND_MAX * t->read_ratio) {
       // read
       int bi = rand() % blobs.size();
       Status s = bs->Get(blobs[bi].first, &buf);
       assert(s.ok());
       t->result.data_read += buf.size();
       t->result.reads++;
     } else {
       // write
       uint64_t size = rand() % (t->data_size_to - t->data_size_from) +
         t->data_size_from;
       total_size += size;
       string put_str = random_strings[rand() % random_strings.size()];
       blobs.push_back(make_pair(Blob(), size));
       Status s = bs->Put(Slice(put_str.data(), size), &blobs.back().first);
       assert(s.ok());
       t->result.data_written += size;
       t->result.writes++;
     }
     while (total_size >= t->working_set_size) {
       // delete random
       int bi = rand() % blobs.size();
       total_size -= blobs[bi].second;
       bs->Delete(blobs[bi].first);
       blobs.erase(blobs.begin() + bi);
       t->result.deletes++;
     }
   }
   t->stopped.store(true);
 }
Variable Documentation
BlobStore* bs
Definition at line 24 of file blob_store_bench.cc.
Referenced by SetupBenchmarkBalanced(), SetupBenchmarkReadHeavy(), SetupBenchmarkWriteHeavy(), StartBenchmark(), and WorkerThreadBody().
Env* env
Definition at line 23 of file blob_store_bench.cc.
Referenced by rocksdb::BM_LogAndApply(), rocksdb::DestroyDB(), leveldb_env_destroy(), main(), rocksdb::SpecialEnv::NewWritableFile(), rocksdb::TransactionLogIteratorImpl::OpenLogFile(), rocksdb::test::RandomSeed(), rocksdb::DBImpl::ReadFirstLine(), rocksdb::DBImpl::RecoverLogFile(), rocksdb::AutoRollLoggerTest::RollLogFileByTimeTest(), SetupBenchmarkBalanced(), SetupBenchmarkReadHeavy(), SetupBenchmarkWriteHeavy(), StartBenchmark(), rocksdb::TableReaderBenchmark(), rocksdb::TEST(), and WorkerThreadBody().
uint64_t timeout_sec
Definition at line 22 of file blob_store_bench.cc.
Referenced by Result::print(), SetupBenchmarkBalanced(), SetupBenchmarkReadHeavy(), SetupBenchmarkWriteHeavy(), and WorkerThreadBody().