rippled: ripple::LedgerEntrySet Class Reference
ripple::LedgerEntrySet Class Reference
#include <LedgerEntrySet.h>
Public Types
typedef std::map< uint256,
LedgerEntrySetEntry >
::iterator iterator
typedef std::map< uint256,
LedgerEntrySetEntry >
::const_iterator const_iterator
Public Member Functions
LedgerEntrySet (Ledger::ref ledger, TransactionEngineParams tep, bool immutable=false)
LedgerEntrySet ()
void setImmutable ()
bool isImmutable () const
LedgerEntrySet duplicate () const
void setTo (const LedgerEntrySet &)
void swapWith (LedgerEntrySet &)
void invalidate ()
bool isValid () const
int getSeq () const
TransactionEngineParams getParams () const
void bumpSeq ()
void init (Ledger::ref ledger, uint256 const &transactionID, std::uint32_t ledgerID, TransactionEngineParams params)
void clear ()
Ledger::pointer & getLedger ()
Ledger::ref getLedgerRef () const
SLE::pointer getEntry (uint256 const &index, LedgerEntryAction &)
LedgerEntryAction hasEntry (uint256 const &index) const
void entryCache (SLE::ref)
void entryCreate (SLE::ref)
void entryDelete (SLE::ref)
void entryModify (SLE::ref)
bool hasChanges ()
SLE::pointer entryCreate (LedgerEntryType letType, uint256 const &uIndex)
SLE::pointer entryCache (LedgerEntryType letType, uint256 const &uIndex)
TER dirAdd (std::uint64_t &uNodeDir, uint256 const &uRootIndex, uint256 const &uLedgerIndex, std::function< void(SLE::ref, bool)> fDescriber)
TER dirDelete (const bool bKeepRoot, const std::uint64_t &uNodeDir, uint256 const &uRootIndex, uint256 const &uLedgerIndex, const bool bStable, const bool bSoft)
bool dirFirst (uint256 const &uRootIndex, SLE::pointer &sleNode, unsigned int &uDirEntry, uint256 &uEntryIndex)
bool dirNext (uint256 const &uRootIndex, SLE::pointer &sleNode, unsigned int &uDirEntry, uint256 &uEntryIndex)
bool dirIsEmpty (uint256 const &uDirIndex)
TER dirCount (uint256 const &uDirIndex, std::uint32_t &uCount)
uint256 getNextLedgerIndex (uint256 const &uHash)
uint256 getNextLedgerIndex (uint256 const &uHash, uint256 const &uEnd)
void ownerCountAdjust (const uint160 &uOwnerID, int iAmount, SLE::ref sleAccountRoot=SLE::pointer())
TER offerDelete (uint256 const &uOfferIndex)
TER offerDelete (SLE::pointer sleOffer)
std::uint32_t rippleTransferRate (const uint160 &uIssuerID)
std::uint32_t rippleTransferRate (const uint160 &uSenderID, const uint160 &uReceiverID, const uint160 &uIssuerID)
STAmount rippleOwed (const uint160 &uToAccountID, const uint160 &uFromAccountID, const uint160 &uCurrencyID)
STAmount rippleLimit (const uint160 &uToAccountID, const uint160 &uFromAccountID, const uint160 &uCurrencyID)
std::uint32_t rippleQualityIn (const uint160 &uToAccountID, const uint160 &uFromAccountID, const uint160 &uCurrencyID, SField::ref sfLow=sfLowQualityIn, SField::ref sfHigh=sfHighQualityIn)
std::uint32_t rippleQualityOut (const uint160 &uToAccountID, const uint160 &uFromAccountID, const uint160 &uCurrencyID)
STAmount rippleHolds (const uint160 &uAccountID, const uint160 &uCurrencyID, const uint160 &uIssuerID)
STAmount rippleTransferFee (const uint160 &uSenderID, const uint160 &uReceiverID, const uint160 &uIssuerID, const STAmount &saAmount)
TER rippleCredit (const uint160 &uSenderID, const uint160 &uReceiverID, const STAmount &saAmount, bool bCheckIssuer=true)
TER rippleSend (const uint160 &uSenderID, const uint160 &uReceiverID, const STAmount &saAmount, STAmount &saActual)
STAmount accountHolds (const uint160 &uAccountID, const uint160 &uCurrencyID, const uint160 &uIssuerID)
STAmount accountFunds (const uint160 &uAccountID, const STAmount &saDefault)
TER accountSend (const uint160 &uSenderID, const uint160 &uReceiverID, const STAmount &saAmount)
TER trustCreate (const bool bSrcHigh, const uint160 &uSrcAccountID, const uint160 &uDstAccountID, uint256 const &uIndex, SLE::ref sleAccount, const bool bAuth, const bool bNoRipple, const STAmount &saSrcBalance, const STAmount &saSrcLimit, const std::uint32_t uSrcQualityIn=0, const std::uint32_t uSrcQualityOut=0)
TER trustDelete (SLE::ref sleRippleState, const uint160 &uLowAccountID, const uint160 &uHighAccountID)
Json::Value getJson (int) const
void calcRawMeta (Serializer &, TER result, std::uint32_t index)
bool isEmpty () const
std::map< uint256,
LedgerEntrySetEntry >
::const_iterator begin () const
std::map< uint256,
LedgerEntrySetEntry >
::const_iterator end () const
std::map< uint256,
LedgerEntrySetEntry >
::iterator begin ()
std::map< uint256,
LedgerEntrySetEntry >
::iterator end ()
void setDeliveredAmount (STAmount const &amt)
Public Member Functions inherited from ripple::CountedObject< LedgerEntrySet >
CountedObject ()
CountedObject (CountedObject const &)
~CountedObject ()
Static Public Member Functions
static char const * getCountedObjectName ()
Private Member Functions
LedgerEntrySet (Ledger::ref ledger, const std::map< uint256, LedgerEntrySetEntry > &e, const TransactionMetaSet &s, int m)
SLE::pointer getForMod (uint256 const &node, Ledger::ref ledger, ripple::unordered_map< uint256, SLE::pointer > &newMods)
bool threadTx (const RippleAddress &threadTo, Ledger::ref ledger, ripple::unordered_map< uint256, SLE::pointer > &newMods)
bool threadTx (SLE::ref threadTo, Ledger::ref ledger, ripple::unordered_map< uint256, SLE::pointer > &newMods)
bool threadOwners (SLE::ref node, Ledger::ref ledger, ripple::unordered_map< uint256, SLE::pointer > &newMods)
Private Attributes
Ledger::pointer mLedger
std::map< uint256,
LedgerEntrySetEntry > mEntries
TransactionMetaSet mSet
TransactionEngineParams mParams
int mSeq
bool mImmutable
Detailed Description
An LES is a LedgerEntrySet.
It's a view into a ledger used while a transaction is processing. The transaction manipulates the LES rather than the ledger (because it's cheaper, can be checkpointed, and so on). When the transaction finishes, the LES is committed into the ledger to make the modifications. The transaction metadata is built from the LES too.
Definition at line 76 of file LedgerEntrySet.h.
Member Typedef Documentation
typedef std::map<uint256, LedgerEntrySetEntry>::const_iterator ripple::LedgerEntrySet::const_iterator
Definition at line 230 of file LedgerEntrySet.h.
typedef std::map<uint256, LedgerEntrySetEntry>::iterator ripple::LedgerEntrySet::iterator
Definition at line 229 of file LedgerEntrySet.h.
Constructor & Destructor Documentation
ripple::LedgerEntrySet::LedgerEntrySet (Ledger::ref ledger, TransactionEngineParams tep, bool immutable = false) inline
Definition at line 82 of file LedgerEntrySet.h.
                                                                                            :
         mLedger (ledger), mParams (tep), mSeq (0), mImmutable (immutable)
     {
     }
ripple::LedgerEntrySet::LedgerEntrySet () inline
Definition at line 87 of file LedgerEntrySet.h.
Referenced by duplicate().
                       : mParams (tapNONE), mSeq (0), mImmutable (false)
     {
     }
ripple::LedgerEntrySet::LedgerEntrySet (Ledger::ref ledger, const std::map< uint256, LedgerEntrySetEntry > & e, const TransactionMetaSet & s, int m) inline private
Definition at line 265 of file LedgerEntrySet.h.
                                                          :
         mLedger (ledger), mEntries (e), mSet (s), mParams (tapNONE), mSeq (m), mImmutable (false)
     {
         ;
     }
Member Function Documentation
STAmount ripple::LedgerEntrySet::accountFunds (const uint160 & uAccountID, const STAmount & saDefault)
Definition at line 1323 of file LedgerEntrySet.cpp.
References accountHolds(), ripple::RippleAddress::createHumanAccountID(), ripple::STAmount::getCurrency(), ripple::STAmount::getFullText(), ripple::STAmount::getIssuer(), ripple::STAmount::isNative(), ripple::lsTRACE, and WriteLog.
Referenced by ripple::OfferCreateTransactor::doApply(), ripple::core::Taker::funds(), ripple::OfferCreateTransactor::isValidOffer(), and ripple::OfferCreateTransactor::takeOffers().
 {
     STAmount    saFunds;
     if (!saDefault.isNative () && saDefault.getIssuer () == uAccountID)
     {
         saFunds = saDefault;
         WriteLog (lsTRACE, LedgerEntrySet) << "accountFunds:" <<
             " uAccountID=" << RippleAddress::createHumanAccountID (uAccountID) <<
             " saDefault=" << saDefault.getFullText () <<
             " SELF-FUNDED";
     }
     else
     {
         saFunds = accountHolds (uAccountID, saDefault.getCurrency (), saDefault.getIssuer ());
         WriteLog (lsTRACE, LedgerEntrySet) << "accountFunds:" <<
             " uAccountID=" << RippleAddress::createHumanAccountID (uAccountID) <<
             " saDefault=" << saDefault.getFullText () <<
             " saFunds=" << saFunds.getFullText ();
     }
     return saFunds;
 }
STAmount ripple::LedgerEntrySet::accountHolds (const uint160 & uAccountID, const uint160 & uCurrencyID, const uint160 & uIssuerID)
Definition at line 1278 of file LedgerEntrySet.cpp.
References ripple::STAmount::clear(), ripple::RippleAddress::createHumanAccountID(), entryCache(), ripple::Ledger::getAccountRootIndex(), ripple::STAmount::getFullText(), ripple::lsTRACE, ripple::ltACCOUNT_ROOT, mLedger, rippleHolds(), and WriteLog.
Referenced by accountFunds(), ripple::RippleCalc::calcNodeAccountFwd(), and ripple::NetworkOPsImp::getBookPage().
 {
     STAmount    saAmount;
     if (!uCurrencyID)
     {
         SLE::pointer sleAccount = entryCache (ltACCOUNT_ROOT,
             Ledger::getAccountRootIndex (uAccountID));
         std::uint64_t uReserve = mLedger->getReserve (sleAccount->getFieldU32 (sfOwnerCount));
         STAmount saBalance   = sleAccount->getFieldAmount (sfBalance);
         if (saBalance < uReserve)
         {
             saAmount.clear ();
         }
         else
         {
             saAmount = saBalance - uReserve;
         }
         WriteLog (lsTRACE, LedgerEntrySet) << "accountHolds:" <<
             " uAccountID=" << RippleAddress::createHumanAccountID (uAccountID) <<
             " saAmount=" << saAmount.getFullText () <<
             " saBalance=" << saBalance.getFullText () <<
             " uReserve=" << uReserve;
     }
     else
     {
         saAmount    = rippleHolds (uAccountID, uCurrencyID, uIssuerID);
         WriteLog (lsTRACE, LedgerEntrySet) << "accountHolds:" <<
             " uAccountID=" << RippleAddress::createHumanAccountID (uAccountID) <<
             " saAmount=" << saAmount.getFullText ();
     }
     return saAmount;
 }
TER ripple::LedgerEntrySet::accountSend (const uint160 & uSenderID, const uint160 & uReceiverID, const STAmount & saAmount)
Definition at line 1636 of file LedgerEntrySet.cpp.
References ripple::RippleAddress::createHumanAccountID(), entryCache(), entryModify(), ripple::Ledger::getAccountRootIndex(), ripple::STAmount::getFullText(), ripple::is_bit_set(), ripple::STAmount::isNative(), ripple::lsTRACE, ripple::ltACCOUNT_ROOT, mParams, nothing, rippleSend(), ripple::tapOPEN_LEDGER, ripple::tecFAILED_PROCESSING, ripple::telFAILED_PROCESSING, ripple::tesSUCCESS, and WriteLog.
Referenced by ripple::RippleCalc::calcNodeAccountFwd(), ripple::RippleCalc::calcNodeDeliverFwd(), ripple::RippleCalc::calcNodeDeliverRev(), ripple::core::Taker::process(), and ripple::OfferCreateTransactor::takeOffers().
 {
     TER terResult   = tesSUCCESS;
     assert (saAmount >= zero);
     if (!saAmount || (uSenderID == uReceiverID))
     {
         nothing ();
     }
     else if (saAmount.isNative ())
     {
         // XRP send which does not check reserve and can do pure adjustment.
         SLE::pointer sleSender = !!uSenderID
             ? entryCache (ltACCOUNT_ROOT, Ledger::getAccountRootIndex (uSenderID))
             : SLE::pointer ();
         SLE::pointer sleReceiver = !!uReceiverID
             ? entryCache (ltACCOUNT_ROOT, Ledger::getAccountRootIndex (uReceiverID))
             : SLE::pointer ();
         auto get_balance = [](SLE::pointer acct)
         {
             std::string ret ("-");
             if (acct)
                 ret = acct->getFieldAmount (sfBalance).getFullText ();
             return ret;
         };
         WriteLog (lsTRACE, LedgerEntrySet) << "accountSend> " <<
             RippleAddress::createHumanAccountID (uSenderID) <<
             " (" << get_balance(sleSender) <<
             ") -> " << RippleAddress::createHumanAccountID (uReceiverID) <<
             " (" << get_balance(sleReceiver) <<
             ") : " << saAmount.getFullText ();
         if (sleSender)
         {
             if (sleSender->getFieldAmount (sfBalance) < saAmount)
             {
                 terResult = is_bit_set (mParams, tapOPEN_LEDGER)
                     ? telFAILED_PROCESSING
                     : tecFAILED_PROCESSING;
             }
             else
             {
                 // Decrement XRP balance.
                 sleSender->setFieldAmount (sfBalance,
                     sleSender->getFieldAmount (sfBalance) - saAmount);
                 entryModify (sleSender);
             }
         }
         if (tesSUCCESS == terResult && sleReceiver)
         {
             // Increment XRP balance.
             sleReceiver->setFieldAmount (sfBalance,
                 sleReceiver->getFieldAmount (sfBalance) + saAmount);
             entryModify (sleReceiver);
         }
         WriteLog (lsTRACE, LedgerEntrySet) << "accountSend< " <<
             RippleAddress::createHumanAccountID (uSenderID) <<
             " (" << get_balance(sleSender) <<
             ") -> " << RippleAddress::createHumanAccountID (uReceiverID) <<
             " (" << get_balance(sleReceiver) <<
             ") : " << saAmount.getFullText ();
     }
     else
     {
         STAmount    saActual;
         WriteLog (lsTRACE, LedgerEntrySet) << "accountSend: " <<
             RippleAddress::createHumanAccountID (uSenderID) <<
             " -> " << RippleAddress::createHumanAccountID (uReceiverID) <<
             " : " << saAmount.getFullText ();
         terResult   = rippleSend (uSenderID, uReceiverID, saAmount, saActual);
     }
     return terResult;
 }
std::map<uint256, LedgerEntrySetEntry>::const_iterator ripple::LedgerEntrySet::begin () const inline
Definition at line 235 of file LedgerEntrySet.h.
References mEntries.
Referenced by ripple::range_begin().
     {
         return mEntries.begin ();
     }
std::map<uint256, LedgerEntrySetEntry>::iterator ripple::LedgerEntrySet::begin () inline
Definition at line 243 of file LedgerEntrySet.h.
References mEntries.
     {
         return mEntries.begin ();
     }
void ripple::LedgerEntrySet::bumpSeq () inline
Definition at line 128 of file LedgerEntrySet.h.
References mSeq.
Referenced by ripple::OfferCreateTransactor::doApply().
     {
         ++mSeq;
     }
void ripple::LedgerEntrySet::calcRawMeta (Serializer & s, TER result, std::uint32_t index)
Definition at line 464 of file LedgerEntrySet.cpp.
References ripple::STObject::addObject(), ripple::TransactionMetaSet::addRaw(), ripple::STObject::empty(), entryModify(), ripple::TransactionMetaSet::getAffectedNode(), ripple::SerializedType::getFName(), ripple::TransactionMetaSet::getJson(), ripple::SerializedType::isDefault(), ripple::lsTRACE, mEntries, mLedger, mSet, ripple::TransactionMetaSet::setAffectedNode(), ripple::sfGeneric, ripple::SField::shouldMeta(), ripple::SField::sMD_Always, ripple::SField::sMD_ChangeNew, ripple::SField::sMD_ChangeOrig, ripple::SField::sMD_Create, ripple::SField::sMD_DeleteFinal, ripple::taaCREATE, ripple::taaDELETE, ripple::taaMODIFY, threadOwners(), threadTx(), and WriteLog.
Referenced by ripple::TransactionEngine::applyTransaction().
 {
     // calculate the raw meta data and return it. This must be called before the set is committed
     // Entries modified only as a result of building the transaction metadata
     ripple::unordered_map<uint256, SLE::pointer> newMod;
     typedef std::map<uint256, LedgerEntrySetEntry>::value_type u256_LES_pair;
     BOOST_FOREACH (u256_LES_pair & it, mEntries)
     {
         SField::ptr type = &sfGeneric;
         switch (it.second.mAction)
         {
         case taaMODIFY:
 #ifdef META_DEBUG
             WriteLog (lsTRACE, LedgerEntrySet) << "Modified Node " << it.first;
 #endif
             type = &sfModifiedNode;
             break;
         case taaDELETE:
 #ifdef META_DEBUG
             WriteLog (lsTRACE, LedgerEntrySet) << "Deleted Node " << it.first;
 #endif
             type = &sfDeletedNode;
             break;
         case taaCREATE:
 #ifdef META_DEBUG
             WriteLog (lsTRACE, LedgerEntrySet) << "Created Node " << it.first;
 #endif
             type = &sfCreatedNode;
             break;
         default: // ignore these
             break;
         }
         if (type == &sfGeneric)
             continue;
         SLE::pointer origNode = mLedger->getSLEi (it.first);
         SLE::pointer curNode = it.second.mEntry;
         if ((type == &sfModifiedNode) && (*curNode == *origNode))
             continue;
         std::uint16_t nodeType = curNode ? curNode->getFieldU16 (sfLedgerEntryType)
                                          : origNode->getFieldU16 (sfLedgerEntryType);
         mSet.setAffectedNode (it.first, *type, nodeType);
         if (type == &sfDeletedNode)
         {
             assert (origNode && curNode);
             threadOwners (origNode, mLedger, newMod); // thread transaction to owners
             STObject prevs (sfPreviousFields);
             BOOST_FOREACH (const SerializedType & obj, *origNode)
             {
                 // go through the original node for modified fields saved on modification
                 if (obj.getFName ().shouldMeta (SField::sMD_ChangeOrig) && !curNode->hasMatchingEntry (obj))
                     prevs.addObject (obj);
             }
             if (!prevs.empty ())
                 mSet.getAffectedNode (it.first).addObject (prevs);
             STObject finals (sfFinalFields);
             BOOST_FOREACH (const SerializedType & obj, *curNode)
             {
                 // go through the final node for final fields
                 if (obj.getFName ().shouldMeta (SField::sMD_Always | SField::sMD_DeleteFinal))
                     finals.addObject (obj);
             }
             if (!finals.empty ())
                 mSet.getAffectedNode (it.first).addObject (finals);
         }
         else if (type == &sfModifiedNode)
         {
             assert (curNode && origNode);
             if (curNode->isThreadedType ()) // thread transaction to node it modified
                 threadTx (curNode, mLedger, newMod);
             STObject prevs (sfPreviousFields);
             BOOST_FOREACH (const SerializedType & obj, *origNode)
             {
                 // search the original node for values saved on modify
                 if (obj.getFName ().shouldMeta (SField::sMD_ChangeOrig) && !curNode->hasMatchingEntry (obj))
                     prevs.addObject (obj);
             }
             if (!prevs.empty ())
                 mSet.getAffectedNode (it.first).addObject (prevs);
             STObject finals (sfFinalFields);
             BOOST_FOREACH (const SerializedType & obj, *curNode)
             {
                 // search the final node for values saved always
                 if (obj.getFName ().shouldMeta (SField::sMD_Always | SField::sMD_ChangeNew))
                     finals.addObject (obj);
             }
             if (!finals.empty ())
                 mSet.getAffectedNode (it.first).addObject (finals);
         }
         else if (type == &sfCreatedNode) // if created, thread to owner(s)
         {
             assert (curNode && !origNode);
             threadOwners (curNode, mLedger, newMod);
             if (curNode->isThreadedType ()) // always thread to self
                 threadTx (curNode, mLedger, newMod);
             STObject news (sfNewFields);
             BOOST_FOREACH (const SerializedType & obj, *curNode)
             {
                 // save non-default values
                 if (!obj.isDefault () && obj.getFName ().shouldMeta (SField::sMD_Create | SField::sMD_Always))
                     news.addObject (obj);
             }
             if (!news.empty ())
                 mSet.getAffectedNode (it.first).addObject (news);
         }
         else assert (false);
     }
     // add any new modified nodes to the modification set
     typedef std::map<uint256, SLE::pointer>::value_type u256_sle_pair;
     BOOST_FOREACH (u256_sle_pair & it, newMod)
         entryModify (it.second);
     mSet.addRaw (s, result, index);
     WriteLog (lsTRACE, LedgerEntrySet) << "Metadata:" << mSet.getJson (0);
 }
void ripple::LedgerEntrySet::clear ()
Definition at line 41 of file LedgerEntrySet.cpp.
References ripple::TransactionMetaSet::clear(), mEntries, and mSet.
Referenced by ripple::TransactionEngine::applyTransaction(), and ripple::RPCHandler::doRipplePathFind().
 {
     mEntries.clear ();
     mSet.clear ();
 }
TER ripple::LedgerEntrySet::dirAdd (std::uint64_t & uNodeDir, uint256 const & uRootIndex, uint256 const & uLedgerIndex, std::function< void(SLE::ref, bool)> fDescriber)
Definition at line 655 of file LedgerEntrySet.cpp.
References DIR_NODE_MAX, entryCache(), entryCreate(), entryModify(), ripple::Ledger::getDirNodeIndex(), ripple::lsTRACE, ripple::ltDIR_NODE, ripple::STVector256::peekValue(), ripple::strHex(), ripple::tecDIR_FULL, ripple::tesSUCCESS, ripple::base_uint< BITS >::ToString(), and WriteLog.
Referenced by ripple::OfferCreateTransactor::doApply(), and trustCreate().
 {
     WriteLog (lsTRACE, LedgerEntrySet) << "dirAdd:" <<
         " uRootIndex=" << uRootIndex.ToString () <<
         " uLedgerIndex=" << uLedgerIndex.ToString ();
     SLE::pointer        sleNode;
     STVector256         svIndexes;
     SLE::pointer        sleRoot     = entryCache (ltDIR_NODE, uRootIndex);
     if (!sleRoot)
     {
         // No root, make it.
         sleRoot     = entryCreate (ltDIR_NODE, uRootIndex);
         sleRoot->setFieldH256 (sfRootIndex, uRootIndex);
         fDescriber (sleRoot, true);
         sleNode     = sleRoot;
         uNodeDir    = 0;
     }
     else
     {
         uNodeDir    = sleRoot->getFieldU64 (sfIndexPrevious);       // Get index to last directory node.
         if (uNodeDir)
         {
             // Try adding to last node.
             sleNode     = entryCache (ltDIR_NODE, Ledger::getDirNodeIndex (uRootIndex, uNodeDir));
             assert (sleNode);
         }
         else
         {
             // Try adding to root.  Didn't have a previous set to the last node.
             sleNode     = sleRoot;
         }
         svIndexes   = sleNode->getFieldV256 (sfIndexes);
         if (DIR_NODE_MAX != svIndexes.peekValue ().size ())
         {
             // Add to current node.
             entryModify (sleNode);
         }
         // Add to new node.
         else if (!++uNodeDir)
         {
             return tecDIR_FULL;
         }
         else
         {
             // Have old last point to new node
             sleNode->setFieldU64 (sfIndexNext, uNodeDir);
             entryModify (sleNode);
             // Have root point to new node.
             sleRoot->setFieldU64 (sfIndexPrevious, uNodeDir);
             entryModify (sleRoot);
             // Create the new node.
             sleNode     = entryCreate (ltDIR_NODE, Ledger::getDirNodeIndex (uRootIndex, uNodeDir));
             sleNode->setFieldH256 (sfRootIndex, uRootIndex);
             if (uNodeDir != 1)
                 sleNode->setFieldU64 (sfIndexPrevious, uNodeDir - 1);
             fDescriber (sleNode, false);
             svIndexes   = STVector256 ();
         }
     }
     svIndexes.peekValue ().push_back (uLedgerIndex); // Append entry.
     sleNode->setFieldV256 (sfIndexes, svIndexes);   // Save entry.
     WriteLog (lsTRACE, LedgerEntrySet) <<
         "dirAdd:   creating: root: " << uRootIndex.ToString ();
     WriteLog (lsTRACE, LedgerEntrySet) <<
         "dirAdd:  appending: Entry: " << uLedgerIndex.ToString ();
     WriteLog (lsTRACE, LedgerEntrySet) <<
         "dirAdd:  appending: Node: " << strHex (uNodeDir);
     // WriteLog (lsINFO, LedgerEntrySet) << "dirAdd:  appending: PREV: " << svIndexes.peekValue()[0].ToString();
     return tesSUCCESS;
 }
TER ripple::LedgerEntrySet::dirCount (uint256 const & uDirIndex, std::uint32_t & uCount)
Definition at line 604 of file LedgerEntrySet.cpp.
References entryCache(), ripple::Ledger::getDirNodeIndex(), ripple::lsWARNING, ripple::ltDIR_NODE, ripple::tefBAD_LEDGER, ripple::tesSUCCESS, and WriteLog.
 {
     std::uint64_t  uNodeDir    = 0;
     uCount  = 0;
     do
     {
         SLE::pointer    sleNode = entryCache (ltDIR_NODE, Ledger::getDirNodeIndex (uRootIndex, uNodeDir));
         if (sleNode)
         {
             uCount      += sleNode->getFieldV256 (sfIndexes).peekValue ().size ();
             uNodeDir    = sleNode->getFieldU64 (sfIndexNext);       // Get next node.
         }
         else if (uNodeDir)
         {
             WriteLog (lsWARNING, LedgerEntrySet) << "dirCount: no such node";
             assert (false);
             return tefBAD_LEDGER;
         }
     }
     while (uNodeDir);
     return tesSUCCESS;
 }
TER ripple::LedgerEntrySet::dirDelete (const bool bKeepRoot, const std::uint64_t & uNodeDir, uint256 const & uRootIndex, uint256 const & uLedgerIndex, const bool bStable, const bool bSoft)
Definition at line 746 of file LedgerEntrySet.cpp.
References entryCache(), entryDelete(), entryModify(), ripple::Ledger::getDirNodeIndex(), ripple::lsWARNING, ripple::ltDIR_NODE, nothing, ripple::STVector256::peekValue(), ripple::strHex(), ripple::tefBAD_LEDGER, ripple::tesSUCCESS, ripple::base_uint< BITS >::ToString(), and WriteLog.
Referenced by offerDelete(), and trustDelete().
 {
     std::uint64_t       uNodeCur    = uNodeDir;
     SLE::pointer        sleNode     = entryCache (ltDIR_NODE, Ledger::getDirNodeIndex (uRootIndex, uNodeCur));
     if (!sleNode)
     {
         WriteLog (lsWARNING, LedgerEntrySet) << "dirDelete: no such node:" <<
             " uRootIndex=" << uRootIndex.ToString () <<
             " uNodeDir=" << strHex (uNodeDir) <<
             " uLedgerIndex=" << uLedgerIndex.ToString ();
         if (!bSoft)
         {
             assert (false);
             return tefBAD_LEDGER;
         }
         else if (uNodeDir < 20)
         {
             // Go the extra mile. Even if node doesn't exist, try the next node.
             return dirDelete (bKeepRoot, uNodeDir + 1, uRootIndex, uLedgerIndex, bStable, true);
         }
         else
         {
             return tefBAD_LEDGER;
         }
     }
     STVector256                     svIndexes   = sleNode->getFieldV256 (sfIndexes);
     std::vector<uint256>&           vuiIndexes  = svIndexes.peekValue ();
     std::vector<uint256>::iterator  it;
     it = std::find (vuiIndexes.begin (), vuiIndexes.end (), uLedgerIndex);
     if (vuiIndexes.end () == it)
     {
         if (!bSoft)
         {
             assert (false);
             WriteLog (lsWARNING, LedgerEntrySet) << "dirDelete: no such entry";
             return tefBAD_LEDGER;
         }
         else if (uNodeDir < 20)
         {
             // Go the extra mile. Even if entry not in node, try the next node.
             return dirDelete (bKeepRoot, uNodeDir + 1, uRootIndex, uLedgerIndex, bStable, true);
         }
         else
         {
             return tefBAD_LEDGER;
         }
     }
     // Remove the element.
     if (vuiIndexes.size () > 1)
     {
         if (bStable)
         {
             vuiIndexes.erase (it);
         }
         else
         {
             *it = vuiIndexes[vuiIndexes.size () - 1];
             vuiIndexes.resize (vuiIndexes.size () - 1);
         }
     }
     else
     {
         vuiIndexes.clear ();
     }
     sleNode->setFieldV256 (sfIndexes, svIndexes);
     entryModify (sleNode);
     if (vuiIndexes.empty ())
     {
         // May be able to delete nodes.
         std::uint64_t       uNodePrevious   = sleNode->getFieldU64 (sfIndexPrevious);
         std::uint64_t       uNodeNext       = sleNode->getFieldU64 (sfIndexNext);
         if (!uNodeCur)
         {
             // Just emptied root node.
             if (!uNodePrevious)
             {
                 // Never overflowed the root node.  Delete it.
                 entryDelete (sleNode);
             }
             // Root overflowed.
             else if (bKeepRoot)
             {
                 // If root overflowed and not allowed to delete overflowed root node.
                 nothing ();
             }
             else if (uNodePrevious != uNodeNext)
             {
                 // Have more than 2 nodes.  Can't delete root node.
                 nothing ();
             }
             else
             {
                 // Have only a root node and a last node.
                 SLE::pointer        sleLast = entryCache (ltDIR_NODE, Ledger::getDirNodeIndex (uRootIndex, uNodeNext));
                 assert (sleLast);
                 if (sleLast->getFieldV256 (sfIndexes).peekValue ().empty ())
                 {
                     // Both nodes are empty.
                     entryDelete (sleNode);  // Delete root.
                     entryDelete (sleLast);  // Delete last.
                 }
                 else
                 {
                     // Have an entry, can't delete root node.
                     nothing ();
                 }
             }
         }
         // Just emptied a non-root node.
         else if (uNodeNext)
         {
             // Not root and not last node. Can delete node.
             SLE::pointer        slePrevious = entryCache (ltDIR_NODE, Ledger::getDirNodeIndex (uRootIndex, uNodePrevious));
             assert (slePrevious);
             SLE::pointer        sleNext     = entryCache (ltDIR_NODE, Ledger::getDirNodeIndex (uRootIndex, uNodeNext));
             assert (slePrevious);
             assert (sleNext);
             if (!slePrevious)
             {
                 WriteLog (lsWARNING, LedgerEntrySet) << "dirDelete: previous node is missing";
                 return tefBAD_LEDGER;
             }
             if (!sleNext)
             {
                 WriteLog (lsWARNING, LedgerEntrySet) << "dirDelete: next node is missing";
                 return tefBAD_LEDGER;
             }
             // Fix previous to point to its new next.
             slePrevious->setFieldU64 (sfIndexNext, uNodeNext);
             entryModify (slePrevious);
             // Fix next to point to its new previous.
             sleNext->setFieldU64 (sfIndexPrevious, uNodePrevious);
             entryModify (sleNext);
             entryDelete(sleNode);
         }
         // Last node.
         else if (bKeepRoot || uNodePrevious)
         {
             // Not allowed to delete last node as root was overflowed.
             // Or, have pervious entries preventing complete delete.
             nothing ();
         }
         else
         {
             // Last and only node besides the root.
             SLE::pointer            sleRoot = entryCache (ltDIR_NODE, uRootIndex);
             assert (sleRoot);
             if (sleRoot->getFieldV256 (sfIndexes).peekValue ().empty ())
             {
                 // Both nodes are empty.
                 entryDelete (sleRoot);  // Delete root.
                 entryDelete (sleNode);  // Delete last.
             }
             else
             {
                 // Root has an entry, can't delete.
                 nothing ();
             }
         }
     }
     return tesSUCCESS;
 }
bool ripple::LedgerEntrySet::dirFirst (uint256 const & uRootIndex, SLE::pointer & sleNode, unsigned int & uDirEntry, uint256 & uEntryIndex)
Definition at line 954 of file LedgerEntrySet.cpp.
References dirNext(), entryCache(), and ripple::ltDIR_NODE.
Referenced by ripple::NetworkOPsImp::getBookPage().
 {
     sleNode     = entryCache (ltDIR_NODE, uRootIndex);
     uDirEntry   = 0;
     assert (sleNode);           // Never probe for directories.
     return LedgerEntrySet::dirNext (uRootIndex, sleNode, uDirEntry, uEntryIndex);
 }
bool ripple::LedgerEntrySet::dirIsEmpty (uint256 const & uDirIndex)
Definition at line 634 of file LedgerEntrySet.cpp.
References entryCache(), ripple::Ledger::getDirNodeIndex(), and ripple::ltDIR_NODE.
Referenced by ripple::AccountSetTransactor::doApply().
 {
     std::uint64_t  uNodeDir = 0;
     SLE::pointer sleNode = entryCache (ltDIR_NODE, Ledger::getDirNodeIndex (uRootIndex, uNodeDir));
     if (!sleNode)
         return true;
     if (!sleNode->getFieldV256 (sfIndexes).peekValue ().empty ())
         return false;
     // If there's another page, it must be non-empty
     return sleNode->getFieldU64 (sfIndexNext) == 0;
 }
bool ripple::LedgerEntrySet::dirNext (uint256 const & uRootIndex, SLE::pointer & sleNode, unsigned int & uDirEntry, uint256 & uEntryIndex)
Definition at line 970 of file LedgerEntrySet.cpp.
References entryCache(), ripple::Ledger::getDirNodeIndex(), ripple::lsFATAL, ripple::lsTRACE, ripple::ltDIR_NODE, ripple::STVector256::peekValue(), WriteLog, and ripple::base_uint< BITS >::zero().
Referenced by dirFirst(), ripple::NetworkOPsImp::getBookPage(), and ripple::DirectoryEntryIterator::nextEntry().
 {
     STVector256             svIndexes   = sleNode->getFieldV256 (sfIndexes);
     std::vector<uint256>&   vuiIndexes  = svIndexes.peekValue ();
     assert (uDirEntry <= vuiIndexes.size ());
     if (uDirEntry >= vuiIndexes.size ())
     {
         std::uint64_t         uNodeNext   = sleNode->getFieldU64 (sfIndexNext);
         if (!uNodeNext)
         {
             uEntryIndex.zero ();
             return false;
         }
         else
         {
             SLE::pointer sleNext = entryCache (ltDIR_NODE, Ledger::getDirNodeIndex (uRootIndex, uNodeNext));
             uDirEntry   = 0;
             if (!sleNext)
             { // This should never happen
                 WriteLog (lsFATAL, LedgerEntrySet) << "Corrupt directory: index:" << uRootIndex << " next:" << uNodeNext;
                 return false;
             }
             sleNode = sleNext;
             return dirNext (uRootIndex, sleNode, uDirEntry, uEntryIndex);
         }
     }
     uEntryIndex = vuiIndexes[uDirEntry++];
     WriteLog (lsTRACE, LedgerEntrySet) << "dirNext:" <<
         " uDirEntry=" << uDirEntry <<
         " uEntryIndex=" << uEntryIndex;
     return true;
 }
LedgerEntrySet ripple::LedgerEntrySet::duplicate () const
Definition at line 47 of file LedgerEntrySet.cpp.
References LedgerEntrySet(), mEntries, mLedger, mSeq, and mSet.
Referenced by ripple::RippleCalc::pathNext(), and ripple::PathState::setExpanded().
 {
     return LedgerEntrySet (mLedger, mEntries, mSet, mSeq + 1);
 }
std::map<uint256, LedgerEntrySetEntry>::const_iterator ripple::LedgerEntrySet::end () const inline
Definition at line 239 of file LedgerEntrySet.h.
References mEntries.
Referenced by getJson(), and ripple::range_end().
     {
         return mEntries.end ();
     }
std::map<uint256, LedgerEntrySetEntry>::iterator ripple::LedgerEntrySet::end () inline
Definition at line 247 of file LedgerEntrySet.h.
References mEntries.
     {
         return mEntries.end ();
     }
void ripple::LedgerEntrySet::entryCache (SLE::ref sle)
Definition at line 136 of file LedgerEntrySet.cpp.
References mEntries, mImmutable, mLedger, mSeq, and ripple::taaCACHED.
Referenced by accountHolds(), accountSend(), ripple::PathState::checkNoRipple(), dirAdd(), dirCount(), dirDelete(), dirFirst(), dirIsEmpty(), dirNext(), ripple::OfferCreateTransactor::doApply(), ripple::TransactionEngine::entryCache(), entryCache(), ripple::core::OfferStream::erase(), ripple::NetworkOPsImp::getBookPage(), ripple::DirectoryEntryIterator::getEntry(), ripple::BookDirIterator::nextDirectory(), ripple::DirectoryEntryIterator::nextEntry(), offerDelete(), ownerCountAdjust(), ripple::PathState::pushNode(), rippleCredit(), rippleHolds(), rippleLimit(), rippleOwed(), rippleQualityIn(), rippleTransferRate(), and ripple::core::BookTip::step().
 {
     assert (mLedger);
     assert (sle->isMutable () || mImmutable); // Don't put an immutable SLE in a mutable LES
     std::map<uint256, LedgerEntrySetEntry>::iterator it = mEntries.find (sle->getIndex ());
     if (it == mEntries.end ())
     {
         mEntries.insert (std::make_pair (sle->getIndex (), LedgerEntrySetEntry (sle, taaCACHED, mSeq)));
         return;
     }
     switch (it->second.mAction)
     {
     case taaCACHED:
         assert (sle == it->second.mEntry);
         it->second.mSeq     = mSeq;
         it->second.mEntry   = sle;
         return;
     default:
         throw std::runtime_error ("Cache after modify/delete/create");
     }
 }
SLE::pointer ripple::LedgerEntrySet::entryCache (LedgerEntryType letType, uint256 const & uIndex)
Definition at line 101 of file LedgerEntrySet.cpp.
References entryCache(), getEntry(), ripple::base_uint< BITS >::isNonZero(), mImmutable, mLedger, and ripple::taaDELETE.
 {
     assert (mLedger);
     SLE::pointer sleEntry;
     if (index.isNonZero ())
     {
         LedgerEntryAction action;
         sleEntry = getEntry (index, action);
         if (!sleEntry)
         {
             assert (action != taaDELETE);
             sleEntry = mImmutable ? mLedger->getSLEi (index) : mLedger->getSLE (index);
             if (sleEntry)
                 entryCache (sleEntry);
         }
         else if (action == taaDELETE)
             sleEntry.reset ();
     }
     return sleEntry;
 }
void ripple::LedgerEntrySet::entryCreate (SLE::ref sle)
Definition at line 161 of file LedgerEntrySet.cpp.
References ripple::lsDEBUG, mEntries, mImmutable, mLedger, mSeq, ripple::taaCACHED, ripple::taaCREATE, ripple::taaDELETE, ripple::taaMODIFY, and WriteLog.
Referenced by dirAdd(), ripple::TransactionEngine::entryCreate(), entryCreate(), and trustCreate().
 {
     assert (mLedger && !mImmutable);
     assert (sle->isMutable ());
     std::map<uint256, LedgerEntrySetEntry>::iterator it = mEntries.find (sle->getIndex ());
     if (it == mEntries.end ())
     {
         mEntries.insert (std::make_pair (sle->getIndex (), LedgerEntrySetEntry (sle, taaCREATE, mSeq)));
         return;
     }
     switch (it->second.mAction)
     {
     case taaDELETE:
         WriteLog (lsDEBUG, LedgerEntrySet) << "Create after Delete = Modify";
         it->second.mEntry = sle;
         it->second.mAction = taaMODIFY;
         it->second.mSeq = mSeq;
         break;
     case taaMODIFY:
         throw std::runtime_error ("Create after modify");
     case taaCREATE:
         throw std::runtime_error ("Create after create"); // This could be made to work
     case taaCACHED:
         throw std::runtime_error ("Create after cache");
     default:
         throw std::runtime_error ("Unknown taa");
     }
     assert (it->second.mSeq == mSeq);
 }
SLE::pointer ripple::LedgerEntrySet::entryCreate (LedgerEntryType letType, uint256 const & uIndex)
Definition at line 93 of file LedgerEntrySet.cpp.
References entryCreate(), and ripple::base_uint< BITS >::isNonZero().
 {
     assert (index.isNonZero ());
     SLE::pointer sleNew = boost::make_shared<SLE> (letType, index);
     entryCreate (sleNew);
     return sleNew;
 }
void ripple::LedgerEntrySet::entryDelete (SLE::ref sle)
Definition at line 235 of file LedgerEntrySet.cpp.
References mEntries, mImmutable, mLedger, mSeq, ripple::taaCACHED, ripple::taaCREATE, ripple::taaDELETE, and ripple::taaMODIFY.
Referenced by dirDelete(), ripple::TransactionEngine::entryDelete(), offerDelete(), and trustDelete().
 {
     assert (sle->isMutable () && !mImmutable);
     assert (mLedger);
     std::map<uint256, LedgerEntrySetEntry>::iterator it = mEntries.find (sle->getIndex ());
     if (it == mEntries.end ())
     {
         assert (false); // deleting an entry not cached?
         mEntries.insert (std::make_pair (sle->getIndex (), LedgerEntrySetEntry (sle, taaDELETE, mSeq)));
         return;
     }
     assert (it->second.mSeq == mSeq);
     assert (it->second.mEntry == sle);
     switch (it->second.mAction)
     {
     case taaCACHED:
     case taaMODIFY:
         it->second.mSeq     = mSeq;
         it->second.mEntry   = sle;
         it->second.mAction  = taaDELETE;
         break;
     case taaCREATE:
         mEntries.erase (it);
         break;
     case taaDELETE:
         break;
     default:
         throw std::runtime_error ("Unknown taa");
     }
 }
void ripple::LedgerEntrySet::entryModify (SLE::ref sle)
Definition at line 199 of file LedgerEntrySet.cpp.
References mEntries, mImmutable, mLedger, mSeq, ripple::taaCACHED, ripple::taaCREATE, ripple::taaDELETE, and ripple::taaMODIFY.
Referenced by accountSend(), ripple::RippleCalc::calcNodeDeliverFwd(), ripple::RippleCalc::calcNodeDeliverRev(), calcRawMeta(), dirAdd(), dirDelete(), ripple::OfferCreateTransactor::doApply(), ripple::TransactionEngine::entryModify(), ripple::core::OfferStream::erase(), ownerCountAdjust(), ripple::core::Taker::process(), and rippleCredit().
 {
     assert (sle->isMutable () && !mImmutable);
     assert (mLedger);
     std::map<uint256, LedgerEntrySetEntry>::iterator it = mEntries.find (sle->getIndex ());
     if (it == mEntries.end ())
     {
         mEntries.insert (std::make_pair (sle->getIndex (), LedgerEntrySetEntry (sle, taaMODIFY, mSeq)));
         return;
     }
     assert (it->second.mSeq == mSeq);
     assert (it->second.mEntry == sle);
     switch (it->second.mAction)
     {
     case taaCACHED:
         it->second.mAction  = taaMODIFY;
         // Fall through
     case taaCREATE:
     case taaMODIFY:
         it->second.mSeq     = mSeq;
         it->second.mEntry   = sle;
         break;
     case taaDELETE:
         throw std::runtime_error ("Modify after delete");
     default:
         throw std::runtime_error ("Unknown taa");
     }
 }
static char const* ripple::LedgerEntrySet::getCountedObjectName () inline static
Definition at line 80 of file LedgerEntrySet.h.
 { return "LedgerEntrySet"; }
SLE::pointer ripple::LedgerEntrySet::getEntry (uint256 const & index, LedgerEntryAction & action)
Definition at line 72 of file LedgerEntrySet.cpp.
References mEntries, mSeq, and ripple::taaNONE.
Referenced by entryCache().
 {
     std::map<uint256, LedgerEntrySetEntry>::iterator it = mEntries.find (index);
     if (it == mEntries.end ())
     {
         action = taaNONE;
         return SLE::pointer ();
     }
     if (it->second.mSeq != mSeq)
     {
         assert (it->second.mSeq < mSeq);
         it->second.mEntry = boost::make_shared<SerializedLedgerEntry> (*it->second.mEntry);
         it->second.mSeq = mSeq;
     }
     action = it->second.mAction;
     return it->second.mEntry;
 }
SLE::pointer ripple::LedgerEntrySet::getForMod (uint256 const & node, Ledger::ref ledger, ripple::unordered_map< uint256, SLE::pointer > & newMods) private
Definition at line 361 of file LedgerEntrySet.cpp.
References ripple::lsFATAL, mEntries, mSeq, ripple::taaCACHED, ripple::taaDELETE, ripple::taaMODIFY, and WriteLog.
Referenced by threadTx().
 {
     std::map<uint256, LedgerEntrySetEntry>::iterator it = mEntries.find (node);
     if (it != mEntries.end ())
     {
         if (it->second.mAction == taaDELETE)
         {
             WriteLog (lsFATAL, LedgerEntrySet) << "Trying to thread to deleted node";
             return SLE::pointer ();
         }
         if (it->second.mAction == taaCACHED)
             it->second.mAction = taaMODIFY;
         if (it->second.mSeq != mSeq)
         {
             it->second.mEntry = boost::make_shared<SerializedLedgerEntry> (*it->second.mEntry);
             it->second.mSeq = mSeq;
         }
         return it->second.mEntry;
     }
     ripple::unordered_map<uint256, SLE::pointer>::iterator me = newMods.find (node);
     if (me != newMods.end ())
     {
         assert (me->second);
         return me->second;
     }
     SLE::pointer ret = ledger->getSLE (node);
     if (ret)
         newMods.insert (std::make_pair (node, ret));
     return ret;
 }
Json::Value ripple::LedgerEntrySet::getJson (int) const
Definition at line 283 of file LedgerEntrySet.cpp.
References Json::Value::append(), Json::arrayValue, end(), ripple::TransactionMetaSet::getJson(), ripple::ltACCOUNT_ROOT, ripple::ltDIR_NODE, ripple::ltGENERATOR_MAP, ripple::ltINVALID, ripple::ltNICKNAME, ripple::ltOFFER, ripple::ltRIPPLE_STATE, mEntries, mSet, Json::objectValue, ripple::taaCACHED, ripple::taaCREATE, ripple::taaDELETE, and ripple::taaMODIFY.
Referenced by ripple::TransactionEngine::applyTransaction().
 {
     Json::Value ret (Json::objectValue);
     Json::Value nodes (Json::arrayValue);
     for (std::map<uint256, LedgerEntrySetEntry>::const_iterator it = mEntries.begin (),
             end = mEntries.end (); it != end; ++it)
     {
         Json::Value entry (Json::objectValue);
         entry["node"] = it->first.GetHex ();
         switch (it->second.mEntry->getType ())
         {
         case ltINVALID:
             entry["type"] = "invalid";
             break;
         case ltACCOUNT_ROOT:
             entry["type"] = "acccount_root";
             break;
         case ltDIR_NODE:
             entry["type"] = "dir_node";
             break;
         case ltGENERATOR_MAP:
             entry["type"] = "generator_map";
             break;
         case ltRIPPLE_STATE:
             entry["type"] = "ripple_state";
             break;
         case ltNICKNAME:
             entry["type"] = "nickname";
             break;
         case ltOFFER:
             entry["type"] = "offer";
             break;
         default:
             assert (false);
         }
         switch (it->second.mAction)
         {
         case taaCACHED:
             entry["action"] = "cache";
             break;
         case taaMODIFY:
             entry["action"] = "modify";
             break;
         case taaDELETE:
             entry["action"] = "delete";
             break;
         case taaCREATE:
             entry["action"] = "create";
             break;
         default:
             assert (false);
         }
         nodes.append (entry);
     }
     ret["nodes" ] = nodes;
     ret["metaData"] = mSet.getJson (0);
     return ret;
 }
Ledger::pointer& ripple::LedgerEntrySet::getLedger () inline
Definition at line 138 of file LedgerEntrySet.h.
References mLedger.
     {
         return mLedger;
     }
Ledger::ref ripple::LedgerEntrySet::getLedgerRef () const inline
Definition at line 143 of file LedgerEntrySet.h.
References mLedger.
     {
         return mLedger;
     }
uint256 ripple::LedgerEntrySet::getNextLedgerIndex (uint256 const & uHash)
Definition at line 1016 of file LedgerEntrySet.cpp.
References ripple::base_uint< BITS >::isNonZero(), mEntries, mLedger, and ripple::taaDELETE.
Referenced by getNextLedgerIndex(), and ripple::BookDirIterator::nextDirectory().
 {
     // find next node in ledger that isn't deleted by LES
     uint256 ledgerNext = uHash;
     std::map<uint256, LedgerEntrySetEntry>::const_iterator it;
     do
     {
         ledgerNext = mLedger->getNextLedgerIndex (ledgerNext);
         it  = mEntries.find (ledgerNext);
     }
     while ((it != mEntries.end ()) && (it->second.mAction == taaDELETE));
     // find next node in LES that isn't deleted
     for (it = mEntries.upper_bound (uHash); it != mEntries.end (); ++it)
     {
         // node found in LES, node found in ledger, return earliest
         if (it->second.mAction != taaDELETE)
             return (ledgerNext.isNonZero () && (ledgerNext < it->first)) ? ledgerNext : it->first;
     }
     // nothing next in LES, return next ledger node
     return ledgerNext;
 }
uint256 ripple::LedgerEntrySet::getNextLedgerIndex (uint256 const & uHash, uint256 const & uEnd)
Definition at line 1041 of file LedgerEntrySet.cpp.
References getNextLedgerIndex(), and next.
 {
     uint256 next = getNextLedgerIndex (uHash);
     if (next > uEnd)
         return uint256 ();
     return next;
 }
TransactionEngineParams ripple::LedgerEntrySet::getParams () const inline
Definition at line 123 of file LedgerEntrySet.h.
References mParams.
     {
         return mParams;
     }
int ripple::LedgerEntrySet::getSeq () const inline
Definition at line 118 of file LedgerEntrySet.h.
References mSeq.
     {
         return mSeq;
     }
bool ripple::LedgerEntrySet::hasChanges ()
Definition at line 272 of file LedgerEntrySet.cpp.
References mEntries, and ripple::taaCACHED.
 {
     typedef std::map<uint256, LedgerEntrySetEntry>::value_type u256_LES_pair;
     BOOST_FOREACH (u256_LES_pair & it, mEntries)
     if (it.second.mAction != taaCACHED)
         return true;
     return false;
 }
LedgerEntryAction ripple::LedgerEntrySet::hasEntry (uint256 const & index) const
Definition at line 126 of file LedgerEntrySet.cpp.
References mEntries, and ripple::taaNONE.
 {
     std::map<uint256, LedgerEntrySetEntry>::const_iterator it = mEntries.find (index);
     if (it == mEntries.end ())
         return taaNONE;
     return it->second.mAction;
 }
void ripple::LedgerEntrySet::init (Ledger::ref ledger, uint256 const & transactionID, std::uint32_t ledgerID, TransactionEngineParams params)
Definition at line 31 of file LedgerEntrySet.cpp.
References ripple::TransactionMetaSet::init(), mEntries, mLedger, mParams, mSeq, and mSet.
Referenced by ripple::TransactionEngine::applyTransaction().
 {
     mEntries.clear ();
     mLedger = ledger;
     mSet.init (transactionID, ledgerID);
     mParams = params;
     mSeq    = 0;
 }
void ripple::LedgerEntrySet::invalidate () inline
Definition at line 108 of file LedgerEntrySet.h.
References mLedger.
Referenced by ripple::RippleCalc::rippleCalc().
     {
         mLedger.reset ();
     }
bool ripple::LedgerEntrySet::isEmpty () const inline
Definition at line 231 of file LedgerEntrySet.h.
References mEntries.
     {
         return mEntries.empty ();
     }
bool ripple::LedgerEntrySet::isImmutable () const inline
Definition at line 97 of file LedgerEntrySet.h.
References mImmutable.
     {
         return mImmutable;
     }
bool ripple::LedgerEntrySet::isValid () const inline
Definition at line 113 of file LedgerEntrySet.h.
References mLedger.
Referenced by ripple::RippleCalc::rippleCalc().
     {
         return mLedger != nullptr;
     }
TER ripple::LedgerEntrySet::offerDelete (uint256 const & uOfferIndex)
Definition at line 1096 of file LedgerEntrySet.cpp.
References entryCache(), ripple::ltOFFER, and ripple::tesSUCCESS.
Referenced by ripple::OfferCancelTransactor::doApply(), ripple::OfferCreateTransactor::doApply(), ripple::RippleCalc::rippleCalc(), ripple::core::BookTip::step(), ripple::core::OfferStream::step(), and ripple::OfferCreateTransactor::takeOffers().
 {
     SLE::pointer    sleOffer    = entryCache (ltOFFER, uOfferIndex);
     if (!sleOffer)
         return tesSUCCESS;
     return offerDelete (sleOffer);
 }
TER ripple::LedgerEntrySet::offerDelete (SLE::pointer sleOffer)
Definition at line 1075 of file LedgerEntrySet.cpp.
References dirDelete(), entryDelete(), ripple::Ledger::getOwnerDirIndex(), ownerCountAdjust(), and ripple::tesSUCCESS.
 {
     uint256 offerIndex = sleOffer->getIndex ();
     uint160 uOwnerID   = sleOffer->getFieldAccount160 (sfAccount);
     bool    bOwnerNode = sleOffer->isFieldPresent (sfOwnerNode);   // Detect legacy dirs.
     std::uint64_t uOwnerNode = sleOffer->getFieldU64 (sfOwnerNode);
     uint256 uDirectory = sleOffer->getFieldH256 (sfBookDirectory);
     std::uint64_t uBookNode  = sleOffer->getFieldU64 (sfBookNode);
     TER     terResult  = dirDelete (false, uOwnerNode, Ledger::getOwnerDirIndex (uOwnerID), offerIndex, false, !bOwnerNode);
     TER     terResult2 = dirDelete (false, uBookNode, uDirectory, offerIndex, true, false);
     if (tesSUCCESS == terResult)
         ownerCountAdjust (uOwnerID, -1);
     entryDelete (sleOffer);
     return (terResult == tesSUCCESS) ? terResult2 : terResult;
 }
void ripple::LedgerEntrySet::ownerCountAdjust (const uint160 & uOwnerID, int iAmount, SLE::ref sleAccountRoot = SLE::pointer ())
Definition at line 1052 of file LedgerEntrySet.cpp.
References entryCache(), entryModify(), ripple::Ledger::getAccountRootIndex(), and ripple::ltACCOUNT_ROOT.
Referenced by ripple::TrustSetTransactor::doApply(), ripple::OfferCreateTransactor::doApply(), offerDelete(), rippleCredit(), and trustCreate().
 {
     SLE::pointer    sleHold = sleAccountRoot
                               ? SLE::pointer ()
                               : entryCache (ltACCOUNT_ROOT, Ledger::getAccountRootIndex (uOwnerID));
     SLE::ref        sleRoot = sleAccountRoot
                               ? sleAccountRoot
                               : sleHold;
     const std::uint32_t uOwnerCount = sleRoot->getFieldU32 (sfOwnerCount);
     const std::uint32_t uNew        = iAmount + int (uOwnerCount) > 0
                                       ? uOwnerCount + iAmount
                                       : 0;
     if (uOwnerCount != uNew)
     {
         sleRoot->setFieldU32 (sfOwnerCount, uOwnerCount + iAmount);
         entryModify (sleRoot);
     }
 }
TER ripple::LedgerEntrySet::rippleCredit (const uint160 & uSenderID, const uint160 & uReceiverID, const STAmount & saAmount, bool bCheckIssuer = true)
Definition at line 1483 of file LedgerEntrySet.cpp.
References ACCOUNT_ONE, ripple::RippleAddress::createHumanAccountID(), entryCache(), entryModify(), ripple::Ledger::getAccountRootIndex(), ripple::STAmount::getCurrency(), ripple::STAmount::getFullText(), ripple::STAmount::getIssuer(), ripple::Ledger::getRippleStateIndex(), ripple::is_bit_set(), ripple::lsDEBUG, ripple::lsfHighNoRipple, ripple::lsfHighReserve, ripple::lsfLowNoRipple, ripple::lsfLowReserve, ripple::lsTRACE, ripple::ltACCOUNT_ROOT, ripple::ltRIPPLE_STATE, ripple::STAmount::negate(), ownerCountAdjust(), ripple::STAmount::setIssuer(), ripple::tesSUCCESS, trustCreate(), trustDelete(), and WriteLog.
Referenced by ripple::RippleCalc::calcNodeAccountFwd(), and rippleSend().
 {
     uint160             uIssuerID       = saAmount.getIssuer ();
     uint160             uCurrencyID     = saAmount.getCurrency ();
     // Make sure issuer is involved.
     assert (!bCheckIssuer || uSenderID == uIssuerID || uReceiverID == uIssuerID);
     // Disallow sending to self.
     assert (uSenderID != uReceiverID);
     bool                bSenderHigh     = uSenderID > uReceiverID;
     uint256             uIndex          = Ledger::getRippleStateIndex (uSenderID, uReceiverID, saAmount.getCurrency ());
     SLE::pointer        sleRippleState  = entryCache (ltRIPPLE_STATE, uIndex);
     TER                 terResult;
     assert (!!uSenderID && uSenderID != ACCOUNT_ONE);
     assert (!!uReceiverID && uReceiverID != ACCOUNT_ONE);
     if (!sleRippleState)
     {
         STAmount    saReceiverLimit = STAmount (uCurrencyID, uReceiverID);
         STAmount    saBalance       = saAmount;
         saBalance.setIssuer (ACCOUNT_ONE);
         WriteLog (lsDEBUG, LedgerEntrySet) << "rippleCredit: "
             "create line: " << RippleAddress::createHumanAccountID (uSenderID) <<
             " -> " << RippleAddress::createHumanAccountID (uReceiverID) <<
             " : " << saAmount.getFullText ();
         terResult = trustCreate (
             bSenderHigh,
             uSenderID,
             uReceiverID,
             uIndex,
             entryCache (ltACCOUNT_ROOT, Ledger::getAccountRootIndex (uReceiverID)),
             false,
             false,
             saBalance,
             saReceiverLimit);
     }
     else
     {
         STAmount    saBalance   = sleRippleState->getFieldAmount (sfBalance);
         if (bSenderHigh)
             saBalance.negate ();    // Put balance in sender terms.
         STAmount    saBefore    = saBalance;
         saBalance   -= saAmount;
         WriteLog (lsTRACE, LedgerEntrySet) << "rippleCredit: " <<
             RippleAddress::createHumanAccountID (uSenderID) <<
             " -> " << RippleAddress::createHumanAccountID (uReceiverID) <<
             " : before=" << saBefore.getFullText () <<
             " amount=" << saAmount.getFullText () <<
             " after=" << saBalance.getFullText ();
         bool    bDelete = false;
         std::uint32_t  uFlags;
         // YYY Could skip this if rippling in reverse.
         if (saBefore > zero                                                                              // Sender balance was positive.
                 && saBalance <= zero                                                                         // Sender is zero or negative.
                 && is_bit_set ((uFlags = sleRippleState->getFieldU32 (sfFlags)), !bSenderHigh ? lsfLowReserve : lsfHighReserve) // Sender reserve is set.
                 && !is_bit_set (uFlags, !bSenderHigh ? lsfLowNoRipple : lsfHighNoRipple)
                 && !sleRippleState->getFieldAmount (!bSenderHigh ? sfLowLimit : sfHighLimit)                        // Sender trust limit is 0.
                 && !sleRippleState->getFieldU32 (!bSenderHigh ? sfLowQualityIn : sfHighQualityIn)                   // Sender quality in is 0.
                 && !sleRippleState->getFieldU32 (!bSenderHigh ? sfLowQualityOut : sfHighQualityOut))                // Sender quality out is 0.
         {
             // Clear the reserve of the sender, possibly delete the line!
             SLE::pointer    sleSender   = entryCache (ltACCOUNT_ROOT, Ledger::getAccountRootIndex (uSenderID));
             ownerCountAdjust (uSenderID, -1, sleSender);
             sleRippleState->setFieldU32 (sfFlags, uFlags & (!bSenderHigh ? ~lsfLowReserve : ~lsfHighReserve));  // Clear reserve flag.
             bDelete = !saBalance        // Balance is zero.
                       && !is_bit_set (uFlags, bSenderHigh ? lsfLowReserve : lsfHighReserve); // Receiver reserve is clear.
         }
         if (bSenderHigh)
             saBalance.negate ();
         // Want to reflect balance to zero even if we are deleting line.
         sleRippleState->setFieldAmount (sfBalance, saBalance);  // ONLY: Adjust ripple balance.
         if (bDelete)
         {
             terResult   = trustDelete (sleRippleState,
                                        bSenderHigh ? uReceiverID : uSenderID,
                                        !bSenderHigh ? uReceiverID : uSenderID);
         }
         else
         {
             entryModify (sleRippleState);
             terResult   = tesSUCCESS;
         }
     }
     return terResult;
 }
STAmount ripple::LedgerEntrySet::rippleHolds (const uint160 & uAccountID, const uint160 & uCurrencyID, const uint160 & uIssuerID)
Definition at line 1248 of file LedgerEntrySet.cpp.
References ripple::STAmount::clear(), entryCache(), ripple::Ledger::getRippleStateIndex(), ripple::ltRIPPLE_STATE, ripple::STAmount::negate(), and ripple::STAmount::setIssuer().
Referenced by accountHolds().
 {
     STAmount saBalance;
     SLE::pointer sleRippleState = entryCache (ltRIPPLE_STATE,
         Ledger::getRippleStateIndex (uAccountID, uIssuerID, uCurrencyID));
     if (!sleRippleState)
     {
         saBalance.clear (uCurrencyID, uIssuerID);
     }
     else if (uAccountID > uIssuerID)
     {
         saBalance   = sleRippleState->getFieldAmount (sfBalance);
         saBalance.negate ();    // Put balance in uAccountID terms.
         saBalance.setIssuer (uIssuerID);
     }
     else
     {
         saBalance   = sleRippleState->getFieldAmount (sfBalance);
         saBalance.setIssuer (uIssuerID);
     }
     return saBalance;
 }
STAmount ripple::LedgerEntrySet::rippleLimit (const uint160 & uToAccountID, const uint160 & uFromAccountID, const uint160 & uCurrencyID)
Definition at line 1143 of file LedgerEntrySet.cpp.
References ripple::STAmount::clear(), entryCache(), ripple::Ledger::getRippleStateIndex(), ripple::ltRIPPLE_STATE, and ripple::STAmount::setIssuer().
Referenced by ripple::RippleCalc::calcNodeAccountRev(), and ripple::PathState::pushNode().
 {
     STAmount        saLimit;
     SLE::pointer    sleRippleState  = entryCache (ltRIPPLE_STATE, Ledger::getRippleStateIndex (uToAccountID, uFromAccountID, uCurrencyID));
     if (sleRippleState)
     {
         saLimit = sleRippleState->getFieldAmount (uToAccountID < uFromAccountID ? sfLowLimit : sfHighLimit);
         saLimit.setIssuer (uToAccountID);
     }
     else
     {
         saLimit.clear (uCurrencyID, uToAccountID);
 #if 0
         // We could cut off coming here if we test for no line sooner.
         assert (false);
 #endif
     }
     return saLimit;
 }
STAmount ripple::LedgerEntrySet::rippleOwed (const uint160 & uToAccountID, const uint160 & uFromAccountID, const uint160 & uCurrencyID)
Definition at line 1108 of file LedgerEntrySet.cpp.
References ripple::STAmount::clear(), ripple::RippleAddress::createHumanAccountID(), ripple::STAmount::createHumanCurrency(), entryCache(), ripple::Ledger::getRippleStateIndex(), ripple::lsDEBUG, ripple::ltRIPPLE_STATE, ripple::STAmount::negate(), ripple::STAmount::setIssuer(), and WriteLog.
Referenced by ripple::RippleCalc::calcNodeAccountRev(), and ripple::PathState::pushNode().
 {
     STAmount        saBalance;
     SLE::pointer    sleRippleState  = entryCache (ltRIPPLE_STATE, Ledger::getRippleStateIndex (uToAccountID, uFromAccountID, uCurrencyID));
     if (sleRippleState)
     {
         saBalance   = sleRippleState->getFieldAmount (sfBalance);
         if (uToAccountID < uFromAccountID)
             saBalance.negate ();
         saBalance.setIssuer (uToAccountID);
     }
     else
     {
         saBalance.clear (uCurrencyID, uToAccountID);
         WriteLog (lsDEBUG, LedgerEntrySet) << "rippleOwed:" <<
             " No credit line between " <<
             RippleAddress::createHumanAccountID (uFromAccountID) <<
             " and " << RippleAddress::createHumanAccountID (uToAccountID) <<
             " for " << STAmount::createHumanCurrency (uCurrencyID);
 #if 0
         // We could cut off coming here if we test for no line sooner.
         assert (false);
 #endif
     }
     return saBalance;
 }
std::uint32_t ripple::LedgerEntrySet::rippleQualityIn (const uint160 & uToAccountID, const uint160 & uFromAccountID, const uint160 & uCurrencyID, SField::ref sfLow = sfLowQualityIn, SField::ref sfHigh = sfHighQualityIn)
Definition at line 1198 of file LedgerEntrySet.cpp.
References ripple::RippleAddress::createHumanAccountID(), ripple::STAmount::createHumanCurrency(), entryCache(), ripple::Ledger::getRippleStateIndex(), ripple::lsTRACE, ripple::ltRIPPLE_STATE, nothing, QUALITY_ONE, and WriteLog.
Referenced by ripple::RippleCalc::calcNodeAccountFwd(), ripple::RippleCalc::calcNodeAccountRev(), and rippleQualityOut().
 {
     std::uint32_t   uQuality        = QUALITY_ONE;
     SLE::pointer    sleRippleState;
     if (uToAccountID == uFromAccountID)
     {
         nothing ();
     }
     else
     {
         sleRippleState = entryCache (ltRIPPLE_STATE,
             Ledger::getRippleStateIndex (uToAccountID, uFromAccountID, uCurrencyID));
         if (sleRippleState)
         {
             SField::ref sfField = uToAccountID < uFromAccountID ? sfLow : sfHigh;
             uQuality    = sleRippleState->isFieldPresent (sfField)
                           ? sleRippleState->getFieldU32 (sfField)
                           : QUALITY_ONE;
             if (!uQuality)
                 uQuality    = 1;    // Avoid divide by zero.
         }
         else
         {
             // XXX Ideally, catch no before this. So we can assert to be stricter.
             uQuality    = QUALITY_ONE;
         }
     }
     WriteLog (lsTRACE, LedgerEntrySet) << "rippleQuality: " <<
         (sfLow == sfLowQualityIn ? "in" : "out") <<
         " uToAccountID=" << RippleAddress::createHumanAccountID (uToAccountID) <<
         " uFromAccountID=" << RippleAddress::createHumanAccountID (uFromAccountID) <<
         " uCurrencyID=" << STAmount::createHumanCurrency (uCurrencyID) <<
         " bLine=" << std::boolalpha << !!sleRippleState <<
         " uQuality=" << (uQuality / 1000000000.0);
     //  assert(uToAccountID == uFromAccountID || !!sleRippleState);
     return uQuality;
 }
std::uint32_t ripple::LedgerEntrySet::rippleQualityOut (const uint160 & uToAccountID, const uint160 & uFromAccountID, const uint160 & uCurrencyID) inline
Definition at line 197 of file LedgerEntrySet.h.
References rippleQualityIn().
Referenced by ripple::RippleCalc::calcNodeAccountFwd(), and ripple::RippleCalc::calcNodeAccountRev().
     {
         return rippleQualityIn (uToAccountID, uFromAccountID, uCurrencyID, sfLowQualityOut, sfHighQualityOut);
     }
TER ripple::LedgerEntrySet::rippleSend (const uint160 & uSenderID, const uint160 & uReceiverID, const STAmount & saAmount, STAmount & saActual)
Definition at line 1593 of file LedgerEntrySet.cpp.
References ACCOUNT_ONE, ripple::RippleAddress::createHumanAccountID(), ripple::STAmount::getFullText(), ripple::STAmount::getIssuer(), ripple::lsDEBUG, rippleCredit(), rippleTransferFee(), ripple::STAmount::setIssuer(), ripple::tesSUCCESS, and WriteLog.
Referenced by accountSend().
 {
     const uint160   uIssuerID   = saAmount.getIssuer ();
     TER             terResult;
     assert (!!uSenderID && !!uReceiverID);
     assert (uSenderID != uReceiverID);
     if (uSenderID == uIssuerID || uReceiverID == uIssuerID || uIssuerID == ACCOUNT_ONE)
     {
         // Direct send: redeeming IOUs and/or sending own IOUs.
         terResult   = rippleCredit (uSenderID, uReceiverID, saAmount, false);
         saActual    = saAmount;
         terResult   = tesSUCCESS;
     }
     else
     {
         // Sending 3rd party IOUs: transit.
         STAmount        saTransitFee    = rippleTransferFee (uSenderID, uReceiverID, uIssuerID, saAmount);
         saActual    = !saTransitFee ? saAmount : saAmount + saTransitFee;
         saActual.setIssuer (uIssuerID); // XXX Make sure this done in + above.
         WriteLog (lsDEBUG, LedgerEntrySet) << "rippleSend> " <<
             RippleAddress::createHumanAccountID (uSenderID) <<
             " - > " << RippleAddress::createHumanAccountID (uReceiverID) <<
             " : deliver=" << saAmount.getFullText () <<
             " fee=" << saTransitFee.getFullText () <<
             " cost=" << saActual.getFullText ();
         terResult   = rippleCredit (uIssuerID, uReceiverID, saAmount);
         if (tesSUCCESS == terResult)
             terResult   = rippleCredit (uSenderID, uIssuerID, saActual);
     }
     return terResult;
 }
STAmount ripple::LedgerEntrySet::rippleTransferFee (const uint160 & uSenderID, const uint160 & uReceiverID, const uint160 & uIssuerID, const STAmount & saAmount)
Definition at line 1350 of file LedgerEntrySet.cpp.
References ACCOUNT_ONE, CURRENCY_ONE, ripple::STAmount::getCurrency(), ripple::STAmount::getIssuer(), ripple::lsDEBUG, ripple::STAmount::multiply(), QUALITY_ONE, rippleTransferRate(), and WriteLog.
Referenced by rippleSend().
 {
     if (uSenderID != uIssuerID && uReceiverID != uIssuerID)
     {
         std::uint32_t uTransitRate = rippleTransferRate (uIssuerID);
         if (QUALITY_ONE != uTransitRate)
         {
             // NIKB use STAmount::saFromRate
             STAmount saTransitRate (
                 CURRENCY_ONE, ACCOUNT_ONE,
                 static_cast<std::uint64_t> (uTransitRate), -9);
             STAmount saTransferTotal = STAmount::multiply (
                 saAmount, saTransitRate,
                 saAmount.getCurrency (), saAmount.getIssuer ());
             STAmount saTransferFee = saTransferTotal - saAmount;
             WriteLog (lsDEBUG, LedgerEntrySet) << "rippleTransferFee:" <<
                 " saTransferFee=" << saTransferFee.getFullText ();
             return saTransferFee;
         }
     }
     return STAmount (saAmount.getCurrency (), saAmount.getIssuer ());
 }
std::uint32_t ripple::LedgerEntrySet::rippleTransferRate (const uint160 & uIssuerID)
Definition at line 1166 of file LedgerEntrySet.cpp.
References ripple::RippleAddress::createHumanAccountID(), entryCache(), ripple::Ledger::getAccountRootIndex(), ripple::lsTRACE, ripple::ltACCOUNT_ROOT, QUALITY_ONE, and WriteLog.
Referenced by ripple::RippleCalc::calcNodeAccountFwd(), ripple::RippleCalc::calcNodeAccountRev(), ripple::RippleCalc::calcNodeRev(), ripple::NetworkOPsImp::getBookPage(), rippleTransferFee(), rippleTransferRate(), and ripple::OfferCreateTransactor::takeOffers().
 {
     SLE::pointer sleAccount (entryCache (
         ltACCOUNT_ROOT, Ledger::getAccountRootIndex (uIssuerID)));
     std::uint32_t uQuality =
         sleAccount && sleAccount->isFieldPresent (sfTransferRate)
             ? sleAccount->getFieldU32 (sfTransferRate)
             : QUALITY_ONE;
     WriteLog (lsTRACE, LedgerEntrySet) << "rippleTransferRate:" <<
         " uIssuerID=" << RippleAddress::createHumanAccountID (uIssuerID) <<
         " account_exists=" << std::boolalpha << !!sleAccount <<
         " transfer_rate=" << (uQuality / 1000000000.0);
     return uQuality;
 }
std::uint32_t ripple::LedgerEntrySet::rippleTransferRate (const uint160 & uSenderID, const uint160 & uReceiverID, const uint160 & uIssuerID)
Definition at line 1185 of file LedgerEntrySet.cpp.
References QUALITY_ONE, and rippleTransferRate().
 {
     // If calculating the transfer rate from or to the issuer of the currency
     // no fees are assessed.
     return uSenderID == uIssuerID || uReceiverID == uIssuerID
            ? QUALITY_ONE
            : rippleTransferRate (uIssuerID);
 }
void ripple::LedgerEntrySet::setDeliveredAmount (STAmount const & amt) inline
Definition at line 252 of file LedgerEntrySet.h.
References mSet, and ripple::TransactionMetaSet::setDeliveredAmount().
Referenced by ripple::PaymentTransactor::doApply().
     {
         mSet.setDeliveredAmount (amt);
     }
void ripple::LedgerEntrySet::setImmutable () inline
Definition at line 92 of file LedgerEntrySet.h.
References mImmutable.
     {
         mImmutable = true;
     }
void ripple::LedgerEntrySet::setTo (const LedgerEntrySet & e)
Definition at line 52 of file LedgerEntrySet.cpp.
References mEntries, mLedger, mParams, mSeq, and mSet.
 {
     mLedger = e.mLedger;
     mEntries = e.mEntries;
     mSet = e.mSet;
     mParams = e.mParams;
     mSeq = e.mSeq;
 }
void ripple::LedgerEntrySet::swapWith (LedgerEntrySet & e)
Definition at line 61 of file LedgerEntrySet.cpp.
References mEntries, mLedger, mParams, mSeq, mSet, ripple::TransactionMetaSet::swap(), and beast::asio::swap().
Referenced by ripple::OfferCreateTransactor::doApply(), and ripple::RippleCalc::rippleCalc().
 {
     std::swap (mLedger, e.mLedger);
     mEntries.swap (e.mEntries);
     mSet.swap (e.mSet);
     std::swap (mParams, e.mParams);
     std::swap (mSeq, e.mSeq);
 }
bool ripple::LedgerEntrySet::threadOwners (SLE::ref node, Ledger::ref ledger, ripple::unordered_map< uint256, SLE::pointer > & newMods) private
Definition at line 440 of file LedgerEntrySet.cpp.
References ripple::lsTRACE, threadTx(), and WriteLog.
Referenced by calcRawMeta().
 {
     // thread new or modified node to owner or owners
     if (node->hasOneOwner ()) // thread to owner's account
     {
 #ifdef META_DEBUG
         WriteLog (lsTRACE, LedgerEntrySet) << "Thread to single owner";
 #endif
         return threadTx (node->getOwner (), ledger, newMods);
     }
     else if (node->hasTwoOwners ()) // thread to owner's accounts
     {
 #ifdef META_DEBUG
         WriteLog (lsTRACE, LedgerEntrySet) << "Thread to two owners";
 #endif
         return
             threadTx (node->getFirstOwner (), ledger, newMods) &&
             threadTx (node->getSecondOwner (), ledger, newMods);
     }
     else
         return false;
 }
bool ripple::LedgerEntrySet::threadTx (const RippleAddress & threadTo, Ledger::ref ledger, ripple::unordered_map< uint256, SLE::pointer > & newMods) private
Definition at line 403 of file LedgerEntrySet.cpp.
References ripple::RippleAddress::getAccountID(), ripple::Ledger::getAccountRootIndex(), getForMod(), ripple::RippleAddress::humanAccountID(), ripple::lsFATAL, ripple::lsTRACE, and WriteLog.
Referenced by calcRawMeta(), and threadOwners().
 {
 #ifdef META_DEBUG
     WriteLog (lsTRACE, LedgerEntrySet) << "Thread to " << threadTo.getAccountID ();
 #endif
     SLE::pointer sle = getForMod (Ledger::getAccountRootIndex (threadTo.getAccountID ()), ledger, newMods);
     if (!sle)
     {
         WriteLog (lsFATAL, LedgerEntrySet) << "Threading to non-existent account: " << threadTo.humanAccountID ();
         assert (false);
         return false;
     }
     return threadTx (sle, ledger, newMods);
 }
bool ripple::LedgerEntrySet::threadTx (SLE::ref threadTo, Ledger::ref ledger, ripple::unordered_map< uint256, SLE::pointer > & newMods) private
Definition at line 421 of file LedgerEntrySet.cpp.
References ripple::TransactionMetaSet::getAffectedNode(), ripple::TransactionMetaSet::getLgrSeq(), ripple::TransactionMetaSet::getTxID(), ripple::base_uint< BITS >::isZero(), mSet, and ripple::TransactionMetaSet::thread().
 {
     // node = the node that was modified/deleted/created
     // threadTo = the node that needs to know
     uint256 prevTxID;
     std::uint32_t prevLgrID;
     if (!threadTo->thread (mSet.getTxID (), mSet.getLgrSeq (), prevTxID, prevLgrID))
         return false;
     if (prevTxID.isZero () ||
             TransactionMetaSet::thread (mSet.getAffectedNode (threadTo, sfModifiedNode), prevTxID, prevLgrID))
         return true;
     assert (false);
     return false;
 }
TER ripple::LedgerEntrySet::trustCreate (const bool bSrcHigh, const uint160 & uSrcAccountID, const uint160 & uDstAccountID, uint256 const & uIndex, SLE::ref sleAccount, const bool bAuth, const bool bNoRipple, const STAmount & saSrcBalance, const STAmount & saSrcLimit, const std::uint32_t uSrcQualityIn = 0, const std::uint32_t uSrcQualityOut = 0)
Definition at line 1382 of file LedgerEntrySet.cpp.
References BIND_TYPE, dirAdd(), entryCreate(), ripple::STAmount::getCurrency(), ripple::STAmount::getIssuer(), ripple::Ledger::getOwnerDirIndex(), ripple::lsfHighAuth, ripple::lsfHighNoRipple, ripple::lsfHighReserve, ripple::lsfLowAuth, ripple::lsfLowNoRipple, ripple::lsfLowReserve, ripple::ltRIPPLE_STATE, ownerCountAdjust(), ripple::Ledger::ownerDirDescriber(), P_1, P_2, and ripple::tesSUCCESS.
Referenced by ripple::TrustSetTransactor::doApply(), and rippleCredit().
 {
     const uint160&  uLowAccountID   = !bSrcHigh ? uSrcAccountID : uDstAccountID;
     const uint160&  uHighAccountID  =  bSrcHigh ? uSrcAccountID : uDstAccountID;
     SLE::pointer    sleRippleState  = entryCreate (ltRIPPLE_STATE, uIndex);
     std::uint64_t   uLowNode;
     std::uint64_t   uHighNode;
     TER terResult   = dirAdd (
                           uLowNode,
                           Ledger::getOwnerDirIndex (uLowAccountID),
                           sleRippleState->getIndex (),
                           BIND_TYPE (&Ledger::ownerDirDescriber, P_1, P_2, uLowAccountID));
     if (tesSUCCESS == terResult)
     {
         terResult   = dirAdd (
                           uHighNode,
                           Ledger::getOwnerDirIndex (uHighAccountID),
                           sleRippleState->getIndex (),
                           BIND_TYPE (&Ledger::ownerDirDescriber, P_1, P_2, uHighAccountID));
     }
     if (tesSUCCESS == terResult)
     {
         const bool  bSetDst     = saLimit.getIssuer () == uDstAccountID;
         const bool  bSetHigh    = bSrcHigh ^ bSetDst;
         sleRippleState->setFieldU64 (sfLowNode, uLowNode);  // Remember deletion hints.
         sleRippleState->setFieldU64 (sfHighNode, uHighNode);
         sleRippleState->setFieldAmount (!bSetHigh ? sfLowLimit : sfHighLimit, saLimit);
         sleRippleState->setFieldAmount ( bSetHigh ? sfLowLimit : sfHighLimit, STAmount (saBalance.getCurrency (), bSetDst ? uSrcAccountID : uDstAccountID));
         if (uQualityIn)
             sleRippleState->setFieldU32 (!bSetHigh ? sfLowQualityIn : sfHighQualityIn, uQualityIn);
         if (uQualityOut)
             sleRippleState->setFieldU32 (!bSetHigh ? sfLowQualityOut : sfHighQualityOut, uQualityOut);
         std::uint32_t  uFlags  = !bSetHigh ? lsfLowReserve : lsfHighReserve;
         if (bAuth)
         {
             uFlags      |= (!bSetHigh ? lsfLowAuth : lsfHighAuth);
         }
         if (bNoRipple)
         {
             uFlags      |= (!bSetHigh ? lsfLowNoRipple : lsfHighNoRipple);
         }
         sleRippleState->setFieldU32 (sfFlags, uFlags);
         ownerCountAdjust (!bSetDst ? uSrcAccountID : uDstAccountID, 1, sleAccount);
         sleRippleState->setFieldAmount (sfBalance, bSetHigh ? -saBalance : saBalance);  // ONLY: Create ripple balance.
     }
     return terResult;
 }
TER ripple::LedgerEntrySet::trustDelete (SLE::ref sleRippleState, const uint160 & uLowAccountID, const uint160 & uHighAccountID)
Definition at line 1456 of file LedgerEntrySet.cpp.
References dirDelete(), entryDelete(), ripple::Ledger::getOwnerDirIndex(), ripple::lsTRACE, ripple::tesSUCCESS, and WriteLog.
Referenced by ripple::TrustSetTransactor::doApply(), and rippleCredit().
 {
     bool        bLowNode    = sleRippleState->isFieldPresent (sfLowNode);   // Detect legacy dirs.
     bool        bHighNode   = sleRippleState->isFieldPresent (sfHighNode);
     std::uint64_t uLowNode    = sleRippleState->getFieldU64 (sfLowNode);
     std::uint64_t uHighNode   = sleRippleState->getFieldU64 (sfHighNode);
     TER         terResult;
     WriteLog (lsTRACE, LedgerEntrySet) << "trustDelete: Deleting ripple line: low";
     terResult   = dirDelete (false, uLowNode, Ledger::getOwnerDirIndex (uLowAccountID), sleRippleState->getIndex (), false, !bLowNode);
     if (tesSUCCESS == terResult)
     {
         WriteLog (lsTRACE, LedgerEntrySet) << "trustDelete: Deleting ripple line: high";
         terResult   = dirDelete (false, uHighNode, Ledger::getOwnerDirIndex (uHighAccountID), sleRippleState->getIndex (), false, !bHighNode);
     }
     WriteLog (lsTRACE, LedgerEntrySet) << "trustDelete: Deleting ripple line: state";
     entryDelete (sleRippleState);
     return terResult;
 }
Member Data Documentation
std::map<uint256, LedgerEntrySetEntry> ripple::LedgerEntrySet::mEntries private
Definition at line 259 of file LedgerEntrySet.h.
Referenced by begin(), calcRawMeta(), clear(), duplicate(), end(), entryCache(), entryCreate(), entryDelete(), entryModify(), getEntry(), getForMod(), getJson(), getNextLedgerIndex(), hasChanges(), hasEntry(), init(), isEmpty(), setTo(), and swapWith().
bool ripple::LedgerEntrySet::mImmutable private
Definition at line 263 of file LedgerEntrySet.h.
Referenced by entryCache(), entryCreate(), entryDelete(), entryModify(), isImmutable(), and setImmutable().
Ledger::pointer ripple::LedgerEntrySet::mLedger private
Definition at line 258 of file LedgerEntrySet.h.
Referenced by accountHolds(), calcRawMeta(), duplicate(), entryCache(), entryCreate(), entryDelete(), entryModify(), getLedger(), getLedgerRef(), getNextLedgerIndex(), init(), invalidate(), isValid(), setTo(), and swapWith().
TransactionEngineParams ripple::LedgerEntrySet::mParams private
Definition at line 261 of file LedgerEntrySet.h.
Referenced by accountSend(), getParams(), init(), setTo(), and swapWith().
int ripple::LedgerEntrySet::mSeq private
Definition at line 262 of file LedgerEntrySet.h.
Referenced by bumpSeq(), duplicate(), entryCache(), entryCreate(), entryDelete(), entryModify(), getEntry(), getForMod(), getSeq(), init(), setTo(), and swapWith().
TransactionMetaSet ripple::LedgerEntrySet::mSet private
Definition at line 260 of file LedgerEntrySet.h.
Referenced by calcRawMeta(), clear(), duplicate(), getJson(), init(), setDeliveredAmount(), setTo(), swapWith(), and threadTx().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/ledger/LedgerEntrySet.h
rippled/src/ripple_app/ledger/LedgerEntrySet.cpp