rippled: CollSeq Struct Reference
CollSeq Struct Reference
Public Attributes
char * zName
u8 enc
void * pUser
int(* xCmp)(void *, int, const void *, int, const void *)
void(* xDel)(void *)
Detailed Description
Definition at line 10680 of file sqlite3.c.
Member Data Documentation
u8 CollSeq::enc
Definition at line 10682 of file sqlite3.c.
Referenced by createCollation(), findCollSeqEntry(), and vdbeCompareMemString().
void* CollSeq::pUser
Definition at line 10683 of file sqlite3.c.
Referenced by createCollation(), and vdbeCompareMemString().
int(* CollSeq::xCmp)(void *, int, const void *, int, const void *)
Definition at line 10684 of file sqlite3.c.
Referenced by createCollation(), sqlite3GetCollSeq(), sqlite3LocateCollSeq(), sqlite3MemCompare(), synthCollSeq(), and vdbeCompareMemString().
void(* CollSeq::xDel)(void *)
Definition at line 10685 of file sqlite3.c.
Referenced by createCollation(), sqlite3LeaveMutexAndCloseZombie(), and synthCollSeq().
char* CollSeq::zName
Definition at line 10681 of file sqlite3.c.
Referenced by constructAutomaticIndex(), displayP4(), exprTableRegister(), findCollSeqEntry(), findIndexCol(), multiSelectOrderByKeyInfo(), selectAddColumnTypeAndCollation(), sqlite3CheckCollSeq(), sqlite3Pragma(), synthCollSeq(), wherePathSatisfiesOrderBy(), and whereScanNext().
The documentation for this struct was generated from the following file:
rippled/src/beast/modules/beast_sqlite/sqlite/sqlite3.c