rippled: ripple::JsonCpp_test Class Reference
ripple::JsonCpp_test Class Reference
Public Member Functions
void testBadJson ()
void test_copy ()
void test_move ()
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 25 of file Tests.cpp.
Member Function Documentation
void ripple::JsonCpp_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 87 of file Tests.cpp.
References test_copy(), test_move(), and testBadJson().
     {
         testBadJson ();
         test_copy ();
         test_move ();
     }
void ripple::JsonCpp_test::test_copy () inline
Definition at line 42 of file Tests.cpp.
References Json::Value::asDouble(), beast::unit_test::suite::expect(), Json::Value::isDouble(), and beast::unit_test::suite::pass().
Referenced by run().
     {
         Json::Value v1{2.5};
         expect (v1.isDouble ());
         expect (v1.asDouble () == 2.5);
         Json::Value v2 = v1;
         expect (v1.isDouble ());
         expect (v1.asDouble () == 2.5);
         expect (v2.isDouble ());
         expect (v2.asDouble () == 2.5);
         expect (v1 == v2);
         v1 = v2;
         expect (v1.isDouble ());
         expect (v1.asDouble () == 2.5);
         expect (v2.isDouble ());
         expect (v2.asDouble () == 2.5);
         expect (v1 == v2);
         pass ();
     }
void ripple::JsonCpp_test::test_move () inline
Definition at line 66 of file Tests.cpp.
References Json::Value::asDouble(), beast::unit_test::suite::expect(), Json::Value::isDouble(), Json::Value::isNull(), and beast::unit_test::suite::pass().
Referenced by run().
     {
         Json::Value v1{2.5};
         expect (v1.isDouble ());
         expect (v1.asDouble () == 2.5);
         Json::Value v2 = std::move(v1);
         expect (v1.isNull ());
         expect (v2.isDouble ());
         expect (v2.asDouble () == 2.5);
         expect (v1 != v2);
         v1 = std::move(v2);
         expect (v1.isDouble ());
         expect (v1.asDouble () == 2.5);
         expect (v2.isNull ());
         expect (v1 != v2);
         pass ();
     }
void ripple::JsonCpp_test::testBadJson () inline
Definition at line 28 of file Tests.cpp.
References Json::Reader::parse(), and beast::unit_test::suite::pass().
Referenced by run().
     {
         char const* s (
             "{\"method\":\"ledger\",\"params\":[{\"ledger_index\":1e300}]}"
             );
         Json::Value j;
         Json::Reader r;
         r.parse (s, j);
         pass ();
     }
The documentation for this class was generated from the following file:
rippled/src/ripple/json/impl/Tests.cpp