rippled: rocksdb::TestState Class Reference
rocksdb::TestState Class Reference
Public Types
enum ReaderState { STARTING, RUNNING, DONE }
Public Member Functions
TestState (int s)
void Wait (ReaderState s)
void Change (ReaderState s)
Public Attributes
ConcurrentTest t_
int seed_
port::AtomicPointer quit_flag_
Private Attributes
port::Mutex mu_
ReaderState state_
port::CondVar state_cv_
Detailed Description
Definition at line 302 of file skiplist_test.cc.
Member Enumeration Documentation
enum rocksdb::TestState::ReaderState
Enumerator
STARTING
RUNNING
DONE
Definition at line 308 of file skiplist_test.cc.
                    {
     STARTING,
     RUNNING,
     DONE
   };
Constructor & Destructor Documentation
rocksdb::TestState::TestState (int s) inline explicit
Definition at line 314 of file skiplist_test.cc.
       : seed_(s),
         quit_flag_(nullptr),
         state_(STARTING),
         state_cv_(&mu_) {}
Member Function Documentation
void rocksdb::TestState::Change (ReaderState s) inline
Definition at line 328 of file skiplist_test.cc.
References rocksdb::port::Mutex::Lock(), mu_, rocksdb::port::CondVar::Signal(), state_, state_cv_, and rocksdb::port::Mutex::Unlock().
Referenced by rocksdb::ConcurrentReader().
{
     mu_.Lock();
     state_ = s;
     state_cv_.Signal();
     mu_.Unlock();
   }
void rocksdb::TestState::Wait (ReaderState s) inline
Definition at line 320 of file skiplist_test.cc.
References rocksdb::port::Mutex::Lock(), mu_, state_, state_cv_, rocksdb::port::Mutex::Unlock(), and rocksdb::port::CondVar::Wait().
Referenced by rocksdb::RunConcurrent().
{
     mu_.Lock();
     while (state_ != s) {
       state_cv_.Wait();
     }
     mu_.Unlock();
   }
Member Data Documentation
port::Mutex rocksdb::TestState::mu_ private
Definition at line 336 of file skiplist_test.cc.
Referenced by Change(), and Wait().
port::AtomicPointer rocksdb::TestState::quit_flag_
Definition at line 306 of file skiplist_test.cc.
Referenced by rocksdb::ConcurrentReader(), and rocksdb::RunConcurrent().
int rocksdb::TestState::seed_
Definition at line 305 of file skiplist_test.cc.
Referenced by rocksdb::ConcurrentReader().
ReaderState rocksdb::TestState::state_ private
Definition at line 337 of file skiplist_test.cc.
Referenced by Change(), and Wait().
port::CondVar rocksdb::TestState::state_cv_ private
Definition at line 338 of file skiplist_test.cc.
Referenced by Change(), and Wait().
ConcurrentTest rocksdb::TestState::t_
Definition at line 304 of file skiplist_test.cc.
Referenced by rocksdb::ConcurrentReader(), and rocksdb::RunConcurrent().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/db/skiplist_test.cc