rippled: ripple::RangeSet_test Class Reference
ripple::RangeSet_test Class Reference
Public Member Functions
RangeSet createPredefinedSet ()
void testMembership ()
void testPrevMissing ()
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 265 of file RangeSet.cpp.
Member Function Documentation
RangeSet ripple::RangeSet_test::createPredefinedSet () inline
Definition at line 268 of file RangeSet.cpp.
References ripple::RangeSet::setRange().
Referenced by testPrevMissing().
     {
         RangeSet set;
         // Set will include:
         // [ 0, 5]
         // [10,15]
         // [20,25]
         // etc...
         for (int i = 0; i < 10; ++i)
             set.setRange (10 * i, 10 * i + 5);
         return set;
     }
void ripple::RangeSet_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 320 of file RangeSet.cpp.
References testMembership(), and testPrevMissing().
     {
         testMembership ();
         testPrevMissing ();
         // TODO: Traverse functions must be tested
     }
void ripple::RangeSet_test::testMembership () inline
Definition at line 284 of file RangeSet.cpp.
References ripple::RangeSet::clearValue(), beast::unit_test::suite::expect(), ripple::RangeSet::hasValue(), ripple::RangeSet::setRange(), and beast::unit_test::suite::testcase().
Referenced by run().
     {
         testcase ("membership");
         RangeSet r1, r2;
         r1.setRange (1, 10);
         r1.clearValue (5);
         r1.setRange (11, 20);
         r2.setRange (1, 4);
         r2.setRange (6, 10);
         r2.setRange (10, 20);
         expect (!r1.hasValue (5));
         expect (r2.hasValue (9));
     }
void ripple::RangeSet_test::testPrevMissing () inline
Definition at line 303 of file RangeSet.cpp.
References createPredefinedSet(), beast::unit_test::suite::expect(), ripple::RangeSet::prevMissing(), and beast::unit_test::suite::testcase().
Referenced by run().
     {
         testcase ("prevMissing");
         RangeSet const set = createPredefinedSet ();
         for (int i = 0; i < 100; ++i)
         {
             int const oneBelowRange = (10*(i/10))-1;
             int const expectedPrevMissing =
                 ((i % 10) > 6) ? (i-1) : oneBelowRange;
             expect (set.prevMissing (i) == expectedPrevMissing);
         }
     }
The documentation for this class was generated from the following file:
rippled/src/ripple_basics/containers/RangeSet.cpp