rippled: ripple::SHAMap_test Class Reference
ripple::SHAMap_test Class Reference
Public Member Functions
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Static Public Member Functions
static Blob IntToVUC (int v)
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 1299 of file SHAMap.cpp.
Member Function Documentation
static Blob ripple::SHAMap_test::IntToVUC (int v) inline static
Definition at line 1304 of file SHAMap.cpp.
     {
         Blob vuc;
         for (int i = 0; i < 32; ++i)
             vuc.push_back (static_cast<unsigned char> (v));
         return vuc;
     }
void ripple::SHAMap_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 1314 of file SHAMap.cpp.
References ripple::SHAMap::addItem(), ripple::SHAMap::delItem(), ripple::get_seconds_clock(), ripple::SHAMap::getHash(), ripple::SHAMap::peekFirstItem(), ripple::SHAMap::peekNextItem(), ripple::base_uint< BITS >::SetHex(), ripple::smtFREE, ripple::SHAMap::snapShot(), and testcase.
     {
         testcase ("add/traverse");
         FullBelowCache fullBelowCache ("test.full_below",
             get_seconds_clock ());
         // h3 and h4 differ only in the leaf, same terminal node (level 19)
         uint256 h1, h2, h3, h4, h5;
         h1.SetHex ("092891fe4ef6cee585fdc6fda0e09eb4d386363158ec3321b8123e5a772c6ca7");
         h2.SetHex ("436ccbac3347baa1f1e53baeef1f43334da88f1f6d70d963b833afd6dfa289fe");
         h3.SetHex ("b92891fe4ef6cee585fdc6fda1e09eb4d386363158ec3321b8123e5a772c6ca8");
         h4.SetHex ("b92891fe4ef6cee585fdc6fda2e09eb4d386363158ec3321b8123e5a772c6ca8");
         h5.SetHex ("a92891fe4ef6cee585fdc6fda0e09eb4d386363158ec3321b8123e5a772c6ca7");
         SHAMap sMap (smtFREE, fullBelowCache);
         SHAMapItem i1 (h1, IntToVUC (1)), i2 (h2, IntToVUC (2)), i3 (h3, IntToVUC (3)), i4 (h4, IntToVUC (4)), i5 (h5, IntToVUC (5));
         unexpected (!sMap.addItem (i2, true, false), "no add");
         unexpected (!sMap.addItem (i1, true, false), "no add");
         SHAMapItem::pointer i;
         i = sMap.peekFirstItem ();
         unexpected (!i || (*i != i1), "bad traverse");
         i = sMap.peekNextItem (i->getTag ());
         unexpected (!i || (*i != i2), "bad traverse");
         i = sMap.peekNextItem (i->getTag ());
         unexpected (!!i, "bad traverse");
         sMap.addItem (i4, true, false);
         sMap.delItem (i2.getTag ());
         sMap.addItem (i3, true, false);
         i = sMap.peekFirstItem ();
         unexpected (!i || (*i != i1), "bad traverse");
         i = sMap.peekNextItem (i->getTag ());
         unexpected (!i || (*i != i3), "bad traverse");
         i = sMap.peekNextItem (i->getTag ());
         unexpected (!i || (*i != i4), "bad traverse");
         i = sMap.peekNextItem (i->getTag ());
         unexpected (!!i, "bad traverse");
         testcase ("snapshot");
         uint256 mapHash = sMap.getHash ();
         SHAMap::pointer map2 = sMap.snapShot (false);
         unexpected (sMap.getHash () != mapHash, "bad snapshot");
         unexpected (map2->getHash () != mapHash, "bad snapshot");
         unexpected (!sMap.delItem (sMap.peekFirstItem ()->getTag ()), "bad mod");
         unexpected (sMap.getHash () == mapHash, "bad snapshot");
         unexpected (map2->getHash () != mapHash, "bad snapshot");
     }
The documentation for this class was generated from the following file:
rippled/src/ripple_app/shamap/SHAMap.cpp