rippled: ripple::uint256 Class Reference
ripple::uint256 Class Reference
#include <UInt256.h>
Public Types
typedef base_uint256 basetype
Public Types inherited from ripple::base_uint< BITS >
typedef std::size_t size_type
typedef std::ptrdiff_t difference_type
typedef unsigned char value_type
typedef value_type * pointer
typedef value_type & reference
typedef value_type const * const_pointer
typedef value_type const & const_reference
typedef pointer iterator
typedef const_pointer const_iterator
typedef std::reverse_iterator
< iterator > reverse_iterator
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator
typedef beast::hardened_hash
< base_uint > hasher
Public Member Functions
uint256 ()
uint256 (const basetype &b)
uint256 & operator= (const basetype &b)
uint256 (std::uint64_t b)
uint256 & operator= (std::uint64_t uHost)
uint256 (const std::string &str)
uint256 (Blob const &vch)
Public Member Functions inherited from ripple::base_uint< BITS >
base_uint ()
pointer data ()
const_pointer data () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
const_iterator cbegin () const
const_iterator cend () const
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
bool isZero () const
bool isNonZero () const
bool operator! () const
const base_uint operator~ () const
base_uint & operator= (std::uint64_t uHost)
base_uint & operator^= (const base_uint &b)
base_uint & operator&= (const base_uint &b)
base_uint & operator|= (const base_uint &b)
base_uint & operator++ ()
const base_uint operator++ (int)
base_uint & operator-- ()
const base_uint operator-- (int)
base_uint & operator+= (const base_uint &b)
std::string GetHex () const
void SetHexExact (const char *psz)
bool SetHex (const char *psz, bool bStrict=false)
bool SetHex (const std::string &str, bool bStrict=false)
void SetHexExact (const std::string &str)
std::string ToString () const
unsigned int size () const
void zero ()
unsigned int GetSerializeSize (int nType=0) const
template<typename Stream >
void Serialize (Stream &s, int nType=0) const
template<typename Stream >
void Unserialize (Stream &s, int nType=0)
Static Public Member Functions
static uint256 fromVoid (void const *data)
Private Member Functions
uint256 (void const *data, FromVoid)
Additional Inherited Members
Static Public Attributes inherited from ripple::base_uint< BITS >
static std::size_t const bytes = (BITS/8)
Protected Types inherited from ripple::base_uint< BITS >
enum { WIDTH = BITS / 32 }
Protected Member Functions inherited from ripple::base_uint< BITS >
base_uint (void const *data, FromVoid)
Protected Attributes inherited from ripple::base_uint< BITS >
unsigned int pn [WIDTH]
Detailed Description
Definition at line 36 of file UInt256.h.
Member Typedef Documentation
typedef base_uint256 ripple::uint256::basetype
Definition at line 39 of file UInt256.h.
Constructor & Destructor Documentation
ripple::uint256::uint256 () inline
Definition at line 41 of file UInt256.h.
References ripple::base_uint< BITS >::zero().
Referenced by fromVoid().
     {
         zero ();
     }
ripple::uint256::uint256 (const basetype & b) inline
Definition at line 46 of file UInt256.h.
     {
         *this   = b;
     }
ripple::uint256::uint256 (std::uint64_t b) inline explicit
Definition at line 59 of file UInt256.h.
     {
         *this = b;
     }
ripple::uint256::uint256 (void const * data, FromVoid) inline private
Definition at line 65 of file UInt256.h.
         : base_uint256 (data, FromVoid ())
     {
     }
ripple::uint256::uint256 (const std::string & str) inline explicit
Definition at line 85 of file UInt256.h.
References ripple::base_uint< BITS >::SetHex().
     {
         SetHex (str);
     }
ripple::uint256::uint256 (Blob const & vch) inline explicit
Definition at line 90 of file UInt256.h.
References ripple::base_uint< BITS >::pn, and ripple::base_uint< BITS >::zero().
     {
         if (vch.size () == sizeof (pn))
             memcpy (pn, &vch[0], sizeof (pn));
         else
         {
             assert (false);
             zero ();
         }
     }
Member Function Documentation
static uint256 ripple::uint256::fromVoid (void const * data) inline static
Definition at line 70 of file UInt256.h.
References uint256().
Referenced by ripple::NodeStore::DecodedBlob::createObject(), ripple::NodeStore::MemoryBackend::fetch(), and ripple::SqliteBackend::fetch().
     {
         return uint256 (data, FromVoid ());
     }
uint256& ripple::uint256::operator= (const basetype & b) inline
Definition at line 51 of file UInt256.h.
References ripple::base_uint< BITS >::pn.
     {
         if (pn != b.pn)
             memcpy (pn, b.pn, sizeof (pn));
         return *this;
     }
uint256& ripple::uint256::operator= (std::uint64_t uHost) inline
Definition at line 75 of file UInt256.h.
References ripple::base_uint< BITS >::end(), and ripple::base_uint< BITS >::zero().
     {
         zero ();
         // Put in least significant bits.
         ((std::uint64_t*) end ())[-1]   = htobe64 (uHost);
         return *this;
     }
The documentation for this class was generated from the following file:
rippled/src/ripple/types/api/UInt256.h