rippled: ripple::Config::Helpers Struct Reference
ripple::Config::Helpers Struct Reference
#include <Config.h>
Static Public Member Functions
static char const * getConfigFileName ()
static char const * getDatabaseDirName ()
static char const * getValidatorsFileName ()
Detailed Description
Definition at line 103 of file Config.h.
Member Function Documentation
static char const* ripple::Config::Helpers::getConfigFileName () inline static
Definition at line 106 of file Config.h.
Referenced by ripple::Config::setup().
         {
             return "rippled.cfg";
         }
static char const* ripple::Config::Helpers::getDatabaseDirName () inline static
Definition at line 111 of file Config.h.
Referenced by ripple::Config::setup().
         {
             return "db";
         }
static char const* ripple::Config::Helpers::getValidatorsFileName () inline static
Definition at line 116 of file Config.h.
Referenced by ripple::UniqueNodeListImp::nodeLoad(), ripple::Config::setup(), and ripple::UniqueNodeListImp::validatorsResponse().
         {
             return "validators.txt";
         }
The documentation for this struct was generated from the following file:
rippled/src/ripple_core/functional/Config.h