rippled: ripple::DirectoryEntryIterator Class Reference
ripple::DirectoryEntryIterator Class Reference
#include <DirectoryEntryIterator.h>
Public Member Functions
DirectoryEntryIterator ()
DirectoryEntryIterator (uint256 const &index)
DirectoryEntryIterator (SLE::ref directory)
SLE::pointer getEntry (LedgerEntrySet &les, LedgerEntryType type)
bool firstEntry (LedgerEntrySet &)
bool nextEntry (LedgerEntrySet &)
bool addJson (Json::Value &) const
bool setJson (Json::Value const &, LedgerEntrySet &les)
uint256 const & getEntryLedgerIndex () const
uint256 getDirectory () const
bool operator== (DirectoryEntryIterator const &other) const
bool operator!= (DirectoryEntryIterator const &other) const
Private Attributes
uint256 mRootIndex
uint256 mDirIndex
unsigned int mEntry
uint256 mEntryIndex
SLE::pointer mDirNode
Detailed Description
An iterator that walks the ledger entries in a single directory
Definition at line 26 of file DirectoryEntryIterator.h.
Constructor & Destructor Documentation
ripple::DirectoryEntryIterator::DirectoryEntryIterator () inline
Definition at line 30 of file DirectoryEntryIterator.h.
         : mEntry(0)
     {
     }
ripple::DirectoryEntryIterator::DirectoryEntryIterator (uint256 const & index) inline
Definition at line 35 of file DirectoryEntryIterator.h.
         : mRootIndex(index), mEntry(0)
     {
     }
ripple::DirectoryEntryIterator::DirectoryEntryIterator (SLE::ref directory) inline
Construct from a reference to the root directory
Definition at line 42 of file DirectoryEntryIterator.h.
References mDirNode, and mRootIndex.
                                               : mEntry (0), mDirNode (directory)
     {
         if (mDirNode)
             mRootIndex = mDirNode->getIndex();
     }
Member Function Documentation
bool ripple::DirectoryEntryIterator::addJson (Json::Value & j) const
Add this iterator's position to a JSON object
Definition at line 76 of file DirectoryEntryIterator.cpp.
References ripple::base_uint< BITS >::GetHex(), mDirIndex, mDirNode, mEntry, and mRootIndex.
Referenced by ripple::OrderBookIterator::addJson().
 {
     if (mDirNode && (mEntry != 0))
     {
         j["dir_root"] = mRootIndex.GetHex();
         j["dir_entry"] = static_cast<Json::UInt> (mEntry);
         if (mDirNode)
             j["dir_index"] = mDirIndex.GetHex();
         return true;
     }
     return false;
 }
bool ripple::DirectoryEntryIterator::firstEntry (LedgerEntrySet & les)
Make this iterator point to the first offer
Position the iterator at the first entry
Definition at line 30 of file DirectoryEntryIterator.cpp.
References ripple::base_uint< BITS >::GetHex(), ripple::lsTRACE, mDirNode, mEntry, mRootIndex, nextEntry(), and WriteLog.
 {
     WriteLog (lsTRACE, Ledger) << "DirectoryEntryIterator::firstEntry(" << mRootIndex.GetHex() << ")";
     mEntry = 0;
     mDirNode.reset ();
     return nextEntry (les);
 }
uint256 ripple::DirectoryEntryIterator::getDirectory () const inline
Definition at line 68 of file DirectoryEntryIterator.h.
References mDirNode.
Referenced by ripple::OrderBookIterator::getCurrentDirectory().
     {
         return mDirNode ? mDirNode->getIndex () : uint256();
     }
SLE::pointer ripple::DirectoryEntryIterator::getEntry (LedgerEntrySet & les, LedgerEntryType type)
Get the SLE this iterator currently references
Get the current ledger entry
Definition at line 23 of file DirectoryEntryIterator.cpp.
References ripple::LedgerEntrySet::entryCache(), and mEntryIndex.
Referenced by ripple::OrderBookIterator::getCurrentOffer().
 {
     return les.entryCache (type, mEntryIndex);
 }
uint256 const& ripple::DirectoryEntryIterator::getEntryLedgerIndex () const inline
Definition at line 63 of file DirectoryEntryIterator.h.
References mEntryIndex.
Referenced by ripple::OrderBookIterator::getCurrentIndex().
     {
         return mEntryIndex;
     }
bool ripple::DirectoryEntryIterator::nextEntry (LedgerEntrySet & les)
Make this iterator point to the next offer
Advance the iterator to the next entry
Definition at line 41 of file DirectoryEntryIterator.cpp.
References ripple::LedgerEntrySet::dirNext(), ripple::LedgerEntrySet::entryCache(), ripple::base_uint< BITS >::GetHex(), ripple::base_uint< BITS >::isZero(), ripple::lsTRACE, ripple::ltDIR_NODE, mDirIndex, mDirNode, mEntry, mEntryIndex, mRootIndex, WriteLog, and ripple::base_uint< BITS >::zero().
Referenced by firstEntry(), ripple::OrderBookIterator::nextOffer(), and ripple::OrderBookIterator::nextOfferInDir().
 {
     if (!mDirNode)
     {
         WriteLog (lsTRACE, Ledger) << "DirectoryEntryIterator::nextEntry(" << mRootIndex.GetHex() << ") need dir node";
         // Are we already at the end
         if (mDirIndex.isZero())
         {
             WriteLog (lsTRACE, Ledger) << "DirectoryEntryIterator::nextEntry(" << mRootIndex.GetHex() << ") at end";
             return false;
         }
         // Fetch the current directory
         mDirNode = les.entryCache (ltDIR_NODE, mRootIndex);
         if (!mDirNode)
         {
             WriteLog (lsTRACE, Ledger) << "DirectoryEntryIterator::nextEntry(" << mRootIndex.GetHex() << ") no dir node";
             mEntryIndex.zero();
             return false;
         }
     }
    if (!les.dirNext (mRootIndex, mDirNode, mEntry, mEntryIndex))
    {
        mDirIndex.zero();
        mDirNode.reset();
        WriteLog (lsTRACE, Ledger) << "DirectoryEntryIterator::nextEntry(" << mRootIndex.GetHex() << ") now at end";
        return false;
    }
    WriteLog (lsTRACE, Ledger) << "DirectoryEntryIterator::nextEntry(" << mRootIndex.GetHex() << ") now at " << mEntry;
    return true;
 }
bool ripple::DirectoryEntryIterator::operator!= (DirectoryEntryIterator const & other) const inline
Definition at line 80 of file DirectoryEntryIterator.h.
     {
         return ! (*this == other);
     }
bool ripple::DirectoryEntryIterator::operator== (DirectoryEntryIterator const & other) const inline
Definition at line 74 of file DirectoryEntryIterator.h.
References mDirIndex, and mEntry.
     {
         return mEntry == other.mEntry && mDirIndex == other.mDirIndex;
     }
bool ripple::DirectoryEntryIterator::setJson (Json::Value const & j, LedgerEntrySet & les)
Set this iterator's position from a JSON object
Definition at line 91 of file DirectoryEntryIterator.cpp.
References Json::Value::asString(), Json::Value::asUInt(), Json::Value::isMember(), mDirIndex, mEntry, and ripple::base_uint< BITS >::SetHex().
Referenced by ripple::OrderBookIterator::setJson().
 {
     if (!j.isMember("dir_root") || !j.isMember("dir_index") || !j.isMember("dir_entry"))
         return false;
 #if 0 // WRITEME
     Json::Value const& dirRoot = j["dir_root"];
     Json::Value const& dirIndex = j["dir_index"];
     Json::Value const& dirEntry = j["dir_entry"];
     assert(false); // CAUTION: This function is incomplete
     mEntry = j["dir_entry"].asUInt ();
     if (!mDirIndex.SetHex(j["dir_index"].asString()))
         return false;
 #endif
     return true;
 }
Member Data Documentation
uint256 ripple::DirectoryEntryIterator::mDirIndex private
Definition at line 87 of file DirectoryEntryIterator.h.
Referenced by addJson(), nextEntry(), operator==(), and setJson().
SLE::pointer ripple::DirectoryEntryIterator::mDirNode private
Definition at line 90 of file DirectoryEntryIterator.h.
Referenced by addJson(), DirectoryEntryIterator(), firstEntry(), getDirectory(), and nextEntry().
unsigned int ripple::DirectoryEntryIterator::mEntry private
Definition at line 88 of file DirectoryEntryIterator.h.
Referenced by addJson(), firstEntry(), nextEntry(), operator==(), and setJson().
uint256 ripple::DirectoryEntryIterator::mEntryIndex private
Definition at line 89 of file DirectoryEntryIterator.h.
Referenced by getEntry(), getEntryLedgerIndex(), and nextEntry().
uint256 ripple::DirectoryEntryIterator::mRootIndex private
Definition at line 86 of file DirectoryEntryIterator.h.
Referenced by addJson(), DirectoryEntryIterator(), firstEntry(), and nextEntry().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/ledger/DirectoryEntryIterator.h
rippled/src/ripple_app/ledger/DirectoryEntryIterator.cpp