rippled: beast::sqdb::detail::statement_imp Class Reference
beast::sqdb::detail::statement_imp Class Reference
#include <statement_imp.h>
Public Types
typedef std::vector
< detail::into_type_base * > intos_t
typedef std::vector
< detail::use_type_base * > uses_t
Public Member Functions
statement_imp (session &s)
statement_imp (prepare_temp_type const &prep)
~statement_imp ()
void erase_bindings ()
void exchange (detail::into_type_ptr const &i)
void exchange (detail::use_type_ptr const &u)
void clean_up ()
void prepare (std::string const &query, bool bRepeatable=true)
Error execute ()
bool fetch (Error &error)
bool got_data () const
void do_intos ()
void pre_use ()
void do_uses ()
void post_use ()
void release_resources ()
rowid last_insert_rowid ()
Public Member Functions inherited from beast::SharedObject
void incReferenceCount () const noexcept
void decReferenceCount () const
int getReferenceCount () const noexcept
Public Attributes
session & m_session
sqlite3_stmt * m_stmt
std::string m_query
bool m_bReady
bool m_bGotData
bool m_bFirstTime
rowid m_last_insert_rowid
intos_t m_intos
uses_t m_uses
Additional Inherited Members
Protected Member Functions inherited from beast::SharedObject
SharedObject ()
virtual ~SharedObject ()
virtual void destroy () const
void resetReferenceCount () noexcept
Detailed Description
Definition at line 68 of file statement_imp.h.
Member Typedef Documentation
typedef std::vector<detail::into_type_base*> beast::sqdb::detail::statement_imp::intos_t
Definition at line 102 of file statement_imp.h.
typedef std::vector<detail::use_type_base*> beast::sqdb::detail::statement_imp::uses_t
Definition at line 103 of file statement_imp.h.
Constructor & Destructor Documentation
beast::sqdb::detail::statement_imp::statement_imp (session & s) explicit
Definition at line 85 of file statement_imp.cpp.
     : m_session(s)
     , m_stmt(0)
     , m_bReady(false)
     , m_bGotData(false)
     , m_last_insert_rowid(0)
 {
 }
beast::sqdb::detail::statement_imp::statement_imp (prepare_temp_type const & prep) explicit
Definition at line 94 of file statement_imp.cpp.
References beast::sqdb::detail::prepare_temp_type::get_prepare_info(), beast::sqdb::detail::ref_counted_prepare_info::get_query(), beast::sqdb::detail::ref_counted_prepare_info::m_intos, m_intos, beast::sqdb::detail::ref_counted_prepare_info::m_uses, m_uses, and prepare().
     : m_session(prep.get_prepare_info().m_session)
     , m_stmt(0)
     , m_bReady(false)
     , m_bGotData(false)
 {
     ref_counted_prepare_info& rcpi = prep.get_prepare_info();
     m_intos.swap(rcpi.m_intos);
     m_uses.swap(rcpi.m_uses);
     prepare(rcpi.get_query());
 }
beast::sqdb::detail::statement_imp::~statement_imp ()
Definition at line 108 of file statement_imp.cpp.
References clean_up().
 {
     clean_up();
 }
Member Function Documentation
void beast::sqdb::detail::statement_imp::clean_up ()
Definition at line 145 of file statement_imp.cpp.
References erase_bindings(), and release_resources().
Referenced by ~statement_imp().
 {
     erase_bindings();
     release_resources();
 }
void beast::sqdb::detail::statement_imp::do_intos ()
Definition at line 264 of file statement_imp.cpp.
References m_intos.
Referenced by fetch().
 {
     for (intos_t::iterator iter = m_intos.begin(); iter != m_intos.end(); ++iter)
         (*iter)->do_into();
 }
void beast::sqdb::detail::statement_imp::do_uses ()
Definition at line 270 of file statement_imp.cpp.
References m_stmt, m_uses, sqlite3_clear_bindings, and beast::sqdb::detail::sqliteError().
Referenced by execute().
 {
     Error error = detail::sqliteError(__FILE__, __LINE__,
                                       sqlite3_clear_bindings(m_stmt));
     if (error)
         throw error;
     for (uses_t::iterator iter = m_uses.begin(); iter != m_uses.end(); ++iter)
         (*iter)->do_use();
 }
void beast::sqdb::detail::statement_imp::erase_bindings ()
Definition at line 113 of file statement_imp.cpp.
References beast::sqdb::detail::use_type_base::clean_up(), m_intos, and m_uses.
Referenced by clean_up().
 {
     // delete intos
     for (std::size_t i = m_intos.size(); i != 0; --i)
     {
         into_type_base* p = m_intos[i - 1];
         delete p;
         m_intos.resize(i - 1);
     }
     // delete uses
     for (std::size_t i = m_uses.size(); i != 0; --i)
     {
         use_type_base* p = m_uses[i - 1];
         p->clean_up();
         delete p;
         m_uses.resize(i - 1);
     }
 }
void beast::sqdb::detail::statement_imp::exchange (detail::into_type_ptr const & i)
Definition at line 133 of file statement_imp.cpp.
References beast::sqdb::detail::type_ptr< T >::get(), m_intos, and beast::sqdb::detail::type_ptr< T >::release().
 {
     m_intos.push_back(i.get());
     i.release();
 }
void beast::sqdb::detail::statement_imp::exchange (detail::use_type_ptr const & u)
Definition at line 139 of file statement_imp.cpp.
References beast::sqdb::detail::type_ptr< T >::get(), m_uses, and beast::sqdb::detail::type_ptr< T >::release().
 {
     m_uses.push_back(u.get());
     u.release();
 }
Error beast::sqdb::detail::statement_imp::execute ()
Definition at line 177 of file statement_imp.cpp.
References do_uses(), m_bFirstTime, m_bGotData, m_bReady, m_intos, m_session, m_stmt, m_uses, beast::sqdb::session::set_got_data(), sqlite3_reset, and beast::sqdb::detail::sqliteError().
 {
     Error error;
     assert (m_stmt != nullptr);
     // ???
     m_bGotData = false;
     m_session.set_got_data(m_bGotData);
     // binds
     int iCol = 0;
     for (intos_t::iterator iter = m_intos.begin(); iter != m_intos.end(); ++iter)
         (*iter)->bind(*this, iCol);
     int iParam = 1;
     for (uses_t::iterator iter = m_uses.begin(); iter != m_uses.end(); ++iter)
         (*iter)->bind(*this, iParam);
     // reset
     error = detail::sqliteError(__FILE__, __LINE__, sqlite3_reset(m_stmt));
     if (!error)
     {
         // set input variables
         do_uses();
         m_bReady = true;
         m_bFirstTime = true;
     }
     return error;
 }
bool beast::sqdb::detail::statement_imp::fetch (Error & error)
Definition at line 214 of file statement_imp.cpp.
References do_intos(), beast::sqdb::session::last_insert_rowid(), m_bFirstTime, m_bGotData, m_bReady, m_last_insert_rowid, m_session, m_stmt, beast::sqdb::session::set_got_data(), sqlite3_step, SQLITE_DONE, SQLITE_OK, SQLITE_ROW, and beast::sqdb::detail::sqliteError().
 {
     int result = sqlite3_step(m_stmt);
     if (result == SQLITE_ROW ||
             result == SQLITE_DONE)
     {
         if (m_bFirstTime)
         {
             m_last_insert_rowid = m_session.last_insert_rowid();
             m_bFirstTime = false;
         }
         if (result == SQLITE_ROW)
         {
             m_bGotData = true;
             m_session.set_got_data(m_bGotData);
             do_intos();
         }
         else
         {
             m_bGotData = false;
             m_session.set_got_data(m_bGotData);
             if (result == SQLITE_DONE)
             {
                 m_bReady = false;
             }
         }
     }
     else if (result != SQLITE_OK)
     {
         m_bGotData = false;
         error = detail::sqliteError(__FILE__, __LINE__, result);
     }
     else
     {
         // should never get SQLITE_OK here
         throw std::invalid_argument ("invalid result");
     }
     return m_bGotData;
 }
bool beast::sqdb::detail::statement_imp::got_data () const
Definition at line 259 of file statement_imp.cpp.
References m_bGotData.
 {
     return m_bGotData;
 }
rowid beast::sqdb::detail::statement_imp::last_insert_rowid ()
Definition at line 301 of file statement_imp.cpp.
References m_last_insert_rowid.
 {
     return m_last_insert_rowid;
 }
void beast::sqdb::detail::statement_imp::post_use ()
Definition at line 282 of file statement_imp.cpp.
References m_uses.
 {
     // reverse order
     for (uses_t::reverse_iterator iter = m_uses.rbegin(); iter != m_uses.rend(); ++iter)
         (*iter)->post_use();
 }
void beast::sqdb::detail::statement_imp::pre_use ()
void beast::sqdb::detail::statement_imp::prepare (std::string const & query, bool bRepeatable = true)
Definition at line 151 of file statement_imp.cpp.
References beast::sqdb::session::get_connection(), beast::sqdb::session::log_query(), m_bReady, m_last_insert_rowid, m_query, m_session, m_stmt, release_resources(), sqlite3_prepare_v2, SQLITE_OK, and beast::sqdb::detail::sqliteError().
Referenced by statement_imp().
 {
     m_query = query;
     m_session.log_query(query);
     m_last_insert_rowid = 0;
     release_resources();
     char const* tail = 0;
     int result = sqlite3_prepare_v2(
                      m_session.get_connection(),
                      query.c_str(),
                      static_cast<int>(query.size()),
                      &m_stmt,
                      &tail);
     if (result == SQLITE_OK)
     {
         m_bReady = true;
     }
     else
     {
         throw detail::sqliteError(__FILE__, __LINE__, result);
     }
 }
void beast::sqdb::detail::statement_imp::release_resources ()
Definition at line 289 of file statement_imp.cpp.
References m_bGotData, m_bReady, m_stmt, and sqlite3_finalize.
Referenced by clean_up(), and prepare().
 {
     if (m_stmt)
     {
         sqlite3_finalize(m_stmt);
         m_stmt = 0;
     }
     m_bReady = false;
     m_bGotData = false;
 }
Member Data Documentation
bool beast::sqdb::detail::statement_imp::m_bFirstTime
Definition at line 99 of file statement_imp.h.
Referenced by execute(), and fetch().
bool beast::sqdb::detail::statement_imp::m_bGotData
Definition at line 98 of file statement_imp.h.
Referenced by execute(), fetch(), got_data(), and release_resources().
bool beast::sqdb::detail::statement_imp::m_bReady
Definition at line 97 of file statement_imp.h.
Referenced by execute(), fetch(), prepare(), and release_resources().
intos_t beast::sqdb::detail::statement_imp::m_intos
Definition at line 105 of file statement_imp.h.
Referenced by do_intos(), erase_bindings(), exchange(), execute(), and statement_imp().
rowid beast::sqdb::detail::statement_imp::m_last_insert_rowid
Definition at line 100 of file statement_imp.h.
Referenced by fetch(), last_insert_rowid(), and prepare().
std::string beast::sqdb::detail::statement_imp::m_query
Definition at line 96 of file statement_imp.h.
Referenced by prepare().
session& beast::sqdb::detail::statement_imp::m_session
Definition at line 94 of file statement_imp.h.
Referenced by execute(), fetch(), and prepare().
sqlite3_stmt* beast::sqdb::detail::statement_imp::m_stmt
Definition at line 95 of file statement_imp.h.
Referenced by beast::sqdb::detail::standard_into_type::do_into(), beast::sqdb::detail::standard_use_type::do_use(), do_uses(), execute(), fetch(), prepare(), and release_resources().
uses_t beast::sqdb::detail::statement_imp::m_uses
Definition at line 106 of file statement_imp.h.
Referenced by do_uses(), erase_bindings(), exchange(), execute(), post_use(), and statement_imp().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_sqdb/detail/statement_imp.h
rippled/src/beast/modules/beast_sqdb/source/statement_imp.cpp