rippled: rocksdb::RegularKeysStartWithA Class Reference
rocksdb::RegularKeysStartWithA Class Reference
Public Member Functions
const char * Name () const
Status Finish (TableProperties::UserCollectedProperties *properties)
Status Add (const Slice &user_key, const Slice &value)
virtual
TableProperties::UserCollectedProperties GetReadableProperties () const
Public Member Functions inherited from rocksdb::TablePropertiesCollector
virtual ~TablePropertiesCollector ()
Private Attributes
uint32_t count_ = 0
Detailed Description
Definition at line 113 of file table_properties_collector_test.cc.
Member Function Documentation
Status rocksdb::RegularKeysStartWithA::Add (const Slice & user_key, const Slice & value) inline virtual
Implements rocksdb::TablePropertiesCollector.
Definition at line 127 of file table_properties_collector_test.cc.
References count_, rocksdb::Slice::data(), and rocksdb::Status::OK().
{
      // simply asssume all user keys are not empty.
      if (user_key.data()[0] == 'A') {
        ++count_;
      }
      return Status::OK();
    }
Status rocksdb::RegularKeysStartWithA::Finish (TableProperties::UserCollectedProperties * properties) inline virtual
Implements rocksdb::TablePropertiesCollector.
Definition at line 117 of file table_properties_collector_test.cc.
References count_, rocksdb::Status::OK(), and rocksdb::PutVarint32().
{
      std::string encoded;
      PutVarint32(&encoded, count_);
      *properties = TableProperties::UserCollectedProperties {
        { "TablePropertiesTest", "Rocksdb" },
        { "Count", encoded }
      };
      return Status::OK();
    }
virtual TableProperties::UserCollectedProperties rocksdb::RegularKeysStartWithA::GetReadableProperties () const inline virtual
Implements rocksdb::TablePropertiesCollector.
Definition at line 136 of file table_properties_collector_test.cc.
{
       return {};
   }
const char* rocksdb::RegularKeysStartWithA::Name () const inline virtual
Implements rocksdb::TablePropertiesCollector.
Definition at line 115 of file table_properties_collector_test.cc.
 { return "RegularKeysStartWithA"; }
Member Data Documentation
uint32_t rocksdb::RegularKeysStartWithA::count_ = 0 private
Definition at line 142 of file table_properties_collector_test.cc.
Referenced by Add(), and Finish().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/db/table_properties_collector_test.cc