rippled: rocksdb::DBDumperCommand Class Reference
rocksdb::DBDumperCommand Class Reference
#include <ldb_cmd.h>
Public Member Functions
DBDumperCommand (const vector< string > &params, const map< string, string > &options, const vector< string > &flags)
virtual void DoCommand ()
Public Member Functions inherited from rocksdb::LDBCommand
bool ValidateCmdLineOptions ()
virtual Options PrepareOptionsForOpenDB ()
virtual void SetOptions (Options options)
virtual bool NoDBOpen ()
virtual ~LDBCommand ()
void Run ()
LDBCommandExecuteResult GetExecuteState ()
void ClearPreviousRunState ()
Static Public Member Functions
static string Name ()
static void Help (string &ret)
Static Public Member Functions inherited from rocksdb::LDBCommand
static LDBCommand * InitFromCmdLineArgs (const vector< string > &args, const Options &options=Options())
static LDBCommand * InitFromCmdLineArgs (int argc, char **argv, const Options &options=Options())
static string HexToString (const string &str)
static string StringToHex (const string &str)
Private Attributes
bool null_from_
string from_
bool null_to_
string to_
int max_keys_
string delim_
bool count_only_
bool count_delim_
bool print_stats_
Static Private Attributes
static const string ARG_COUNT_ONLY = "count_only"
static const string ARG_COUNT_DELIM = "count_delim"
static const string ARG_STATS = "stats"
static const string ARG_TTL_BUCKET = "bucket"
Additional Inherited Members
Static Public Attributes inherited from rocksdb::LDBCommand
static const string ARG_DB = "db"
static const string ARG_HEX = "hex"
static const string ARG_KEY_HEX = "key_hex"
static const string ARG_VALUE_HEX = "value_hex"
static const string ARG_TTL = "ttl"
static const string ARG_TTL_START = "start_time"
static const string ARG_TTL_END = "end_time"
static const string ARG_TIMESTAMP = "timestamp"
static const string ARG_FROM = "from"
static const string ARG_TO = "to"
static const string ARG_MAX_KEYS = "max_keys"
static const string ARG_BLOOM_BITS = "bloom_bits"
static const string ARG_COMPRESSION_TYPE = "compression_type"
static const string ARG_BLOCK_SIZE = "block_size"
static const string ARG_AUTO_COMPACTION = "auto_compaction"
static const string ARG_WRITE_BUFFER_SIZE = "write_buffer_size"
static const string ARG_FILE_SIZE = "file_size"
static const string ARG_CREATE_IF_MISSING = "create_if_missing"
static const char * DELIM = " ==> "
Protected Member Functions inherited from rocksdb::LDBCommand
bool ParseKeyValue (const string &line, string *key, string *value, bool is_key_hex, bool is_value_hex)
LDBCommand (const map< string, string > &options, const vector< string > &flags, bool is_read_only, const vector< string > &valid_cmd_line_options)
void OpenDB ()
void CloseDB ()
vector< string > BuildCmdLineOptions (vector< string > options)
bool ParseIntOption (const map< string, string > &options, const string &option, int &value, LDBCommandExecuteResult &exec_state)
bool ParseStringOption (const map< string, string > &options, const string &option, string *value)
Static Protected Member Functions inherited from rocksdb::LDBCommand
static string PrintKeyValue (const string &key, const string &value, bool is_key_hex, bool is_value_hex)
static string PrintKeyValue (const string &key, const string &value, bool is_hex)
static bool IsFlagPresent (const vector< string > &flags, const string &flag)
static string HelpRangeCmdArgs ()
Protected Attributes inherited from rocksdb::LDBCommand
LDBCommandExecuteResult exec_state_
string db_path_
DB * db_
StackableDB * sdb_
bool is_read_only_
bool is_key_hex_
bool is_value_hex_
bool is_db_ttl_
bool timestamp_
const map< string, string > option_map_
const vector< string > flags_
const vector< string > valid_cmd_line_options_
Options options_
Detailed Description
Definition at line 381 of file ldb_cmd.h.
Constructor & Destructor Documentation
rocksdb::DBDumperCommand::DBDumperCommand (const vector< string > & params, const map< string, string > & options, const vector< string > & flags)
Definition at line 749 of file ldb_cmd.cc.
References ARG_COUNT_DELIM, ARG_COUNT_ONLY, rocksdb::LDBCommand::ARG_FROM, rocksdb::LDBCommand::ARG_HEX, rocksdb::LDBCommand::ARG_KEY_HEX, rocksdb::LDBCommand::ARG_MAX_KEYS, ARG_STATS, rocksdb::LDBCommand::ARG_TIMESTAMP, rocksdb::LDBCommand::ARG_TO, rocksdb::LDBCommand::ARG_TTL, ARG_TTL_BUCKET, rocksdb::LDBCommand::ARG_TTL_END, rocksdb::LDBCommand::ARG_TTL_START, and rocksdb::LDBCommand::ARG_VALUE_HEX.
                                                                        :
     LDBCommand(options, flags, true,
                BuildCmdLineOptions({ARG_TTL, ARG_HEX, ARG_KEY_HEX,
                                     ARG_VALUE_HEX, ARG_FROM, ARG_TO,
                                     ARG_MAX_KEYS, ARG_COUNT_ONLY,
                                     ARG_COUNT_DELIM, ARG_STATS, ARG_TTL_START,
                                     ARG_TTL_END, ARG_TTL_BUCKET,
                                     ARG_TIMESTAMP})),
Member Function Documentation
void rocksdb::DBDumperCommand::DoCommand () virtual
Implements rocksdb::LDBCommand.
Definition at line 827 of file ldb_cmd.cc.
References ARG_TTL_BUCKET, rocksdb::LDBCommand::ARG_TTL_END, rocksdb::LDBCommand::ARG_TTL_START, count_delim_, count_only_, rocksdb::LDBCommand::db_, delim_, rocksdb::LDBCommand::exec_state_, rocksdb::LDBCommandExecuteResult::FAILED(), from_, rocksdb::DB::GetProperty(), rocksdb::IncBucketCounts(), rocksdb::LDBCommand::is_db_ttl_, rocksdb::LDBCommand::is_key_hex_, rocksdb::LDBCommand::is_value_hex_, rocksdb::Iterator::key(), rocksdb::DBWithTTL::kMaxTimestamp, rocksdb::DBWithTTL::kMinTimestamp, max_keys_, rocksdb::DB::NewIterator(), rocksdb::Iterator::Next(), null_from_, null_to_, rocksdb::Status::ok(), rocksdb::LDBCommand::option_map_, rocksdb::LDBCommand::ParseIntOption(), print_stats_, rocksdb::PrintBucketCounts(), rocksdb::LDBCommand::PrintKeyValue(), rocksdb::ReadableTime(), rocksdb::Iterator::Seek(), rocksdb::Iterator::SeekToFirst(), stats, rocksdb::Iterator::status(), rocksdb::TtlIterator::timestamp(), rocksdb::LDBCommand::timestamp_, to_, rocksdb::Slice::ToString(), rocksdb::Status::ToString(), rocksdb::Iterator::Valid(), and rocksdb::Iterator::value().
{
   if (!db_) {
     return;
   }
   // Parse command line args
   uint64_t count = 0;
   if (print_stats_) {
     string stats;
     if (db_->GetProperty("rocksdb.stats", &stats)) {
       fprintf(stdout, "%s\n", stats.c_str());
     }
   }
   // Setup key iterator
   Iterator* iter = db_->NewIterator(ReadOptions());
   Status st = iter->status();
   if (!st.ok()) {
     exec_state_ = LDBCommandExecuteResult::FAILED("Iterator error."
         + st.ToString());
   }
   if (!null_from_) {
     iter->Seek(from_);
   } else {
     iter->SeekToFirst();
   }
   int max_keys = max_keys_;
   int ttl_start;
   if (!ParseIntOption(option_map_, ARG_TTL_START, ttl_start, exec_state_)) {
     ttl_start = DBWithTTL::kMinTimestamp; // TTL introduction time
   }
   int ttl_end;
   if (!ParseIntOption(option_map_, ARG_TTL_END, ttl_end, exec_state_)) {
     ttl_end = DBWithTTL::kMaxTimestamp; // Max time allowed by TTL feature
   }
   if (ttl_end < ttl_start) {
     fprintf(stderr, "Error: End time can't be less than start time\n");
     delete iter;
     return;
   }
   int time_range = ttl_end - ttl_start;
   int bucket_size;
   if (!ParseIntOption(option_map_, ARG_TTL_BUCKET, bucket_size, exec_state_) ||
       bucket_size <= 0) {
     bucket_size = time_range; // Will have just 1 bucket by default
   }
   //cretaing variables for row count of each type
   string rtype1,rtype2,row,val;
   rtype2 = "";
   uint64_t c=0;
   uint64_t s1=0,s2=0;
   // At this point, bucket_size=0 => time_range=0
   uint64_t num_buckets = (bucket_size >= time_range) ? 1 :
     ((time_range + bucket_size - 1) / bucket_size);
   vector<uint64_t> bucket_counts(num_buckets, 0);
   if (is_db_ttl_ && !count_only_ && timestamp_ && !count_delim_) {
     fprintf(stdout, "Dumping key-values from %s to %s\n",
             ReadableTime(ttl_start).c_str(), ReadableTime(ttl_end).c_str());
   }
   for (; iter->Valid(); iter->Next()) {
     int rawtime = 0;
     // If end marker was specified, we stop before it
     if (!null_to_ && (iter->key().ToString() >= to_))
       break;
     // Terminate if maximum number of keys have been dumped
     if (max_keys == 0)
       break;
     if (is_db_ttl_) {
       TtlIterator* it_ttl = dynamic_cast<TtlIterator*>(iter);
       assert(it_ttl);
       rawtime = it_ttl->timestamp();
       if (rawtime < ttl_start || rawtime >= ttl_end) {
         continue;
       }
     }
     if (max_keys > 0) {
       --max_keys;
     }
     if (is_db_ttl_ && num_buckets > 1) {
       IncBucketCounts(bucket_counts, ttl_start, time_range, bucket_size,
                       rawtime, num_buckets);
     }
     ++count;
     if (count_delim_) {
       rtype1 = "";
       row = iter->key().ToString();
       val = iter->value().ToString();
       s1 = row.size()+val.size();
       for(int j=0;row[j]!=delim_[0] && row[j]!='\0';j++)
         rtype1+=row[j];
       if(rtype2.compare("") && rtype2.compare(rtype1)!=0) {
         fprintf(stdout,"%s => count:%lld\tsize:%lld\n",rtype2.c_str(),
             (long long )c,(long long)s2);
         c=1;
         s2=s1;
         rtype2 = rtype1;
       } else {
           c++;
           s2+=s1;
           rtype2=rtype1;
       }
     }
     if (!count_only_ && !count_delim_) {
       if (is_db_ttl_ && timestamp_) {
         fprintf(stdout, "%s ", ReadableTime(rawtime).c_str());
       }
       string str = PrintKeyValue(iter->key().ToString(),
                                  iter->value().ToString(), is_key_hex_,
                                  is_value_hex_);
       fprintf(stdout, "%s\n", str.c_str());
     }
   }
   if (num_buckets > 1 && is_db_ttl_) {
     PrintBucketCounts(bucket_counts, ttl_start, ttl_end, bucket_size,
                       num_buckets);
   } else if(count_delim_) {
     fprintf(stdout,"%s => count:%lld\tsize:%lld\n",rtype2.c_str(),
         (long long )c,(long long)s2);
   } else {
     fprintf(stdout, "Keys in range: %lld\n", (long long) count);
   }
   // Clean up
   delete iter;
 }
void rocksdb::DBDumperCommand::Help (string & ret) static
Definition at line 811 of file ldb_cmd.cc.
References ARG_COUNT_DELIM, ARG_COUNT_ONLY, rocksdb::LDBCommand::ARG_MAX_KEYS, ARG_STATS, rocksdb::LDBCommand::ARG_TIMESTAMP, rocksdb::LDBCommand::ARG_TTL, ARG_TTL_BUCKET, rocksdb::LDBCommand::ARG_TTL_END, rocksdb::LDBCommand::ARG_TTL_START, rocksdb::LDBCommand::HelpRangeCmdArgs(), and Name().
Referenced by rocksdb::LDBCommandRunner::PrintHelp().
{
   ret.append("  ");
   ret.append(DBDumperCommand::Name());
   ret.append(HelpRangeCmdArgs());
   ret.append(" [--" + ARG_TTL + "]");
   ret.append(" [--" + ARG_MAX_KEYS + "=<N>]");
   ret.append(" [--" + ARG_TIMESTAMP + "]");
   ret.append(" [--" + ARG_COUNT_ONLY + "]");
   ret.append(" [--" + ARG_COUNT_DELIM + "=<char>]");
   ret.append(" [--" + ARG_STATS + "]");
   ret.append(" [--" + ARG_TTL_BUCKET + "=<N>]");
   ret.append(" [--" + ARG_TTL_START + "=<N>:- is inclusive]");
   ret.append(" [--" + ARG_TTL_END + "=<N>:- is exclusive]");
   ret.append("\n");
 }
static string rocksdb::DBDumperCommand::Name () inline static
Definition at line 383 of file ldb_cmd.h.
Referenced by Help(), and rocksdb::LDBCommand::SelectCommand().
 { return "dump"; }
Member Data Documentation
const string rocksdb::DBDumperCommand::ARG_COUNT_DELIM = "count_delim" static private
Definition at line 404 of file ldb_cmd.h.
Referenced by DBDumperCommand(), and Help().
const string rocksdb::DBDumperCommand::ARG_COUNT_ONLY = "count_only" static private
Definition at line 403 of file ldb_cmd.h.
Referenced by DBDumperCommand(), and Help().
const string rocksdb::DBDumperCommand::ARG_STATS = "stats" static private
Definition at line 405 of file ldb_cmd.h.
Referenced by DBDumperCommand(), and Help().
const string rocksdb::DBDumperCommand::ARG_TTL_BUCKET = "bucket" static private
Definition at line 406 of file ldb_cmd.h.
Referenced by DBDumperCommand(), DoCommand(), and Help().
bool rocksdb::DBDumperCommand::count_delim_ private
Definition at line 400 of file ldb_cmd.h.
Referenced by DoCommand().
bool rocksdb::DBDumperCommand::count_only_ private
Definition at line 399 of file ldb_cmd.h.
Referenced by DoCommand().
string rocksdb::DBDumperCommand::delim_ private
Definition at line 398 of file ldb_cmd.h.
Referenced by DoCommand().
string rocksdb::DBDumperCommand::from_ private
Definition at line 394 of file ldb_cmd.h.
Referenced by DoCommand().
int rocksdb::DBDumperCommand::max_keys_ private
Definition at line 397 of file ldb_cmd.h.
Referenced by DoCommand().
bool rocksdb::DBDumperCommand::null_from_ private
Definition at line 393 of file ldb_cmd.h.
Referenced by DoCommand().
bool rocksdb::DBDumperCommand::null_to_ private
Definition at line 395 of file ldb_cmd.h.
Referenced by DoCommand().
bool rocksdb::DBDumperCommand::print_stats_ private
Definition at line 401 of file ldb_cmd.h.
Referenced by DoCommand().
string rocksdb::DBDumperCommand::to_ private
Definition at line 396 of file ldb_cmd.h.
Referenced by DoCommand().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/util/ldb_cmd.h
rippled/src/ripple/rocksdb/rocksdb/util/ldb_cmd.cc