rippled: ripple::core::Quality_test Class Reference
ripple::core::Quality_test Class Reference
Public Member Functions
template<class In1 , class Out1 , class Int , class In2 , class Out2 >
void ceil_in (Quality const &q, In1 in, Out1 out, Int limit, In2 in_expected, Out2 out_expected)
template<class In1 , class Out1 , class Int , class In2 , class Out2 >
void ceil_out (Quality const &q, In1 in, Out1 out, Int limit, In2 in_expected, Out2 out_expected)
void test_ceil_in ()
void test_ceil_out ()
void test_raw ()
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Static Public Member Functions
static Amount raw (std::uint64_t mantissa, int exponent)
template<class Integer >
static Amount amount (Integer integer, std::enable_if_t< std::is_signed< Integer >::value > *=0)
template<class Integer >
static Amount amount (Integer integer, std::enable_if_t<!std::is_signed< Integer >::value > *=0)
template<class In , class Out >
static Amounts amounts (In in, Out out)
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 28 of file Quality.test.cpp.
Member Function Documentation
template<class Integer > static Amount ripple::core::Quality_test::amount (Integer integer, std::enable_if_t< std::is_signed< Integer >::value > * = 0) inline static
Definition at line 41 of file Quality.test.cpp.
References value.
Referenced by amounts(), ceil_in(), ceil_out(), test_ceil_in(), test_ceil_out(), and test_raw().
     {
         static_assert (std::is_integral <Integer>::value, "");
         return Amount (integer, false);
     }
template<class Integer > static Amount ripple::core::Quality_test::amount (Integer integer, std::enable_if_t<!std::is_signed< Integer >::value > * = 0) inline static
Definition at line 51 of file Quality.test.cpp.
References value.
     {
         static_assert (std::is_integral <Integer>::value, "");
         if (integer < 0)
             return Amount (-integer, true);
         return Amount (integer, false);
     }
template<class In , class Out > static Amounts ripple::core::Quality_test::amounts (In in, Out out) inline static
Definition at line 63 of file Quality.test.cpp.
References amount().
Referenced by ceil_in(), and ceil_out().
     {
         return Amounts (amount(in), amount(out));
     }
template<class In1 , class Out1 , class Int , class In2 , class Out2 > void ripple::core::Quality_test::ceil_in (Quality const & q, In1 in, Out1 out, Int limit, In2 in_expected, Out2 out_expected) inline
Definition at line 70 of file Quality.test.cpp.
References amount(), amounts(), ripple::core::Quality::ceil_in(), and beast::unit_test::suite::expect().
Referenced by test_ceil_in().
     {
         auto expect_result (amounts (in_expected, out_expected));
         auto actual_result (q.ceil_in (amounts(in, out), amount(limit)));
         expect (actual_result == expect_result);
     }
template<class In1 , class Out1 , class Int , class In2 , class Out2 > void ripple::core::Quality_test::ceil_out (Quality const & q, In1 in, Out1 out, Int limit, In2 in_expected, Out2 out_expected) inline
Definition at line 81 of file Quality.test.cpp.
References amount(), amounts(), ripple::core::Quality::ceil_out(), and beast::unit_test::suite::expect().
Referenced by test_ceil_out().
     {
         auto const expect_result (amounts (in_expected, out_expected));
         auto const actual_result (q.ceil_out (amounts(in, out), amount(limit)));
         expect (actual_result == expect_result);
     }
static Amount ripple::core::Quality_test::raw (std::uint64_t mantissa, int exponent) inline static
Definition at line 33 of file Quality.test.cpp.
Referenced by test_raw().
     {
         return Amount (uint160(3), uint160(3), mantissa, exponent);
     }
void ripple::core::Quality_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 238 of file Quality.test.cpp.
References test_ceil_in(), test_ceil_out(), and test_raw().
     {
         test_ceil_in ();
         test_ceil_out ();
         test_raw();
     }
void ripple::core::Quality_test::test_ceil_in () inline
Definition at line 91 of file Quality.test.cpp.
References amount(), ceil_in(), and beast::unit_test::suite::testcase().
Referenced by run().
     {
         testcase ("ceil_in");
         {
             // 1 in, 1 out:
             Quality q (Amounts (amount(1), amount(1)));
             ceil_in (q,
                 1,  1,   // 1 in, 1 out
                 1,       // limit: 1
                 1,  1);  // 1 in, 1 out
             ceil_in (q,
                 10, 10, // 10 in, 10 out
                 5,      // limit: 5
                 5, 5);  // 5 in, 5 out
             ceil_in (q,
                 5, 5,   // 5 in, 5 out
                 10,     // limit: 10
                 5, 5);  // 5 in, 5 out
         }
         {
             // 1 in, 2 out:
             Quality q (Amounts (amount(1), amount(2)));
             ceil_in (q,
                 40, 80,   // 40 in, 80 out
                 40,       // limit: 40
                 40, 80);  // 40 in, 20 out
             ceil_in (q,
                 40, 80,   // 40 in, 80 out
                 20,       // limit: 20
                 20, 40);  // 20 in, 40 out
             ceil_in (q,
                 40, 80,   // 40 in, 80 out
                 60,       // limit: 60
                 40, 80);  // 40 in, 80 out
         }
         {
             // 2 in, 1 out:
             Quality q (Amounts (amount(2), amount(1)));
             ceil_in (q,
                 40, 20,   // 40 in, 20 out
                 20,       // limit: 20
                 20, 10);  // 20 in, 10 out
             ceil_in (q,
                 40, 20,   // 40 in, 20 out
                 40,       // limit: 40
                 40, 20);  // 40 in, 20 out
             ceil_in (q,
                 40, 20,   // 40 in, 20 out
                 50,       // limit: 40
                 40, 20);  // 40 in, 20 out
         }
     }
void ripple::core::Quality_test::test_ceil_out () inline
Definition at line 157 of file Quality.test.cpp.
References amount(), ceil_out(), and beast::unit_test::suite::testcase().
Referenced by run().
     {
         testcase ("ceil_out");
         {
             // 1 in, 1 out:
             Quality q (Amounts (amount(1),amount(1)));
             ceil_out (q,
                 1,  1,    // 1 in, 1 out
                 1,        // limit 1
                 1,  1);   // 1 in, 1 out
             ceil_out (q,
                 10, 10,   // 10 in, 10 out
                 5,        // limit 5
                 5, 5);    // 5 in, 5 out
             ceil_out (q,
                 10, 10,   // 10 in, 10 out
                 20,       // limit 20
                 10, 10);  // 10 in, 10 out
         }
         {
             // 1 in, 2 out:
             Quality q (Amounts (amount(1),amount(2)));
             ceil_out (q,
                 40, 80,    // 40 in, 80 out
                 40,        // limit 40
                 20, 40);   // 20 in, 40 out
             ceil_out (q,
                 40, 80,    // 40 in, 80 out
                 80,        // limit 80
                 40, 80);   // 40 in, 80 out
             ceil_out (q,
                 40, 80,    // 40 in, 80 out
                 100,       // limit 100
                 40, 80);   // 40 in, 80 out
         }
         {
             // 2 in, 1 out:
             Quality q (Amounts (amount(2),amount(1)));
             ceil_out (q,
                 40, 20,    // 40 in, 20 out
                 20,        // limit 20
                 40, 20);   // 40 in, 20 out
             ceil_out (q,
                 40, 20,    // 40 in, 20 out
                 40,        // limit 40
                 40, 20);   // 40 in, 20 out
             ceil_out (q,
                 40, 20,    // 40 in, 20 out
                 10,        // limit 10
                 20, 10);   // 20 in, 10 out
         }
     }
void ripple::core::Quality_test::test_raw () inline
Definition at line 223 of file Quality.test.cpp.
References amount(), ripple::core::Quality::ceil_out(), beast::unit_test::suite::expect(), raw(), and value.
Referenced by run().
     {
         {
             Quality q (0x5d048191fb9130daull);      // 126836389.7680090
             Amounts const value (
                 amount(349469768),                  // 349.469768 XRP
                 raw (2755280000000000ull, -15));    // 2.75528
             Amount const limit (
                 raw (4131113916555555, -16));       // .4131113916555555
             Amounts const result (q.ceil_out (value, limit));
             expect (result.in != zero);
         }
     }
The documentation for this class was generated from the following file:
rippled/src/ripple_app/book/tests/Quality.test.cpp