rippled: ripple::Resource::Manager_test::TestLogic Class Reference
ripple::Resource::Manager_test::TestLogic Class Reference
Public Member Functions
TestLogic (beast::Journal journal)
void advance ()
beast::manual_clock
< std::chrono::seconds > & clock ()
Public Member Functions inherited from ripple::Resource::Logic
Logic (beast::insight::Collector::ptr const &collector, clock_type &clock, beast::Journal journal)
~Logic ()
Consumer newInboundEndpoint (beast::IP::Endpoint const &address)
Consumer newOutboundEndpoint (beast::IP::Endpoint const &address)
Consumer newAdminEndpoint (std::string const &name)
Entry & elevateToAdminEndpoint (Entry &prior, std::string const &name)
Json::Value getJson ()
Json::Value getJson (int threshold)
Gossip exportConsumers ()
void importConsumers (std::string const &origin, Gossip const &gossip)
bool isWhitelisted (beast::IP::Endpoint const &address)
void periodicActivity ()
void acquire (Entry &entry, SharedState::Access &state)
void release (Entry &entry, SharedState::Access &state)
void erase (Table::iterator iter, SharedState::Access &state)
Disposition charge (Entry &entry, Charge const &fee, SharedState::Access &state)
bool warn (Entry &entry, SharedState::Access &state)
bool disconnect (Entry &entry, SharedState::Access &state)
int balance (Entry &entry, SharedState::Access &state)
void acquire (Entry &entry)
void release (Entry &entry)
Disposition charge (Entry &entry, Charge const &fee)
bool warn (Entry &entry)
bool disconnect (Entry &entry)
int balance (Entry &entry)
void writeList (clock_type::rep const now, beast::PropertyStream::Set &items, beast::List< Entry > &list)
void onWrite (beast::PropertyStream::Map &map)
Private Types
typedef
boost::base_from_member
< beast::manual_clock
< std::chrono::seconds > > clock_type
Additional Inherited Members
Public Types inherited from ripple::Resource::Logic
typedef beast::abstract_clock
< std::chrono::seconds > clock_type
typedef ripple::unordered_map
< std::string, Import > Imports
typedef ripple::unordered_map
< Key, Entry, Key::hasher,
Key::key_equal > Table
typedef beast::SharedData< State > SharedState
Static Public Member Functions inherited from ripple::Resource::Logic
static Disposition disposition (int balance)
Public Attributes inherited from ripple::Resource::Logic
SharedState m_state
Stats m_stats
beast::abstract_clock
< std::chrono::seconds > & m_clock
beast::Journal m_journal
Detailed Description
Definition at line 30 of file Tests.cpp.
Member Typedef Documentation
typedef boost::base_from_member< beast::manual_clock <std::chrono::seconds> > ripple::Resource::Manager_test::TestLogic::clock_type private
Definition at line 37 of file Tests.cpp.
Constructor & Destructor Documentation
ripple::Resource::Manager_test::TestLogic::TestLogic (beast::Journal journal) inline explicit
Definition at line 40 of file Tests.cpp.
             : Logic (beast::insight::NullCollector::New(), member, journal)
         {
         }
Member Function Documentation
void ripple::Resource::Manager_test::TestLogic::advance () inline
Definition at line 45 of file Tests.cpp.
Referenced by ripple::Resource::Manager_test::testCharges().
         {
             ++member;
         }
beast::manual_clock<std::chrono::seconds>& ripple::Resource::Manager_test::TestLogic::clock () inline
Definition at line 50 of file Tests.cpp.
Referenced by ripple::Resource::Manager_test::testCharges(), and ripple::Resource::Manager_test::testDrop().
         {
             return member;
         }
The documentation for this class was generated from the following file:
rippled/src/ripple/resource/impl/Tests.cpp