rippled: ripple::RippleAccountIDTraits Class Reference
ripple::RippleAccountIDTraits Class Reference
#include <RippleAccountID.h>
Classes
struct assign
struct assign< RippleAddress >
Static Public Member Functions
static std::string to_string (value_type const &value)
Static Public Member Functions inherited from ripple::CryptoIdentifier< 20, 0, true >
static void construct (std::uint8_t const *begin, std::uint8_t const *end, value_type &value)
static std::string to_string (value_type const &value)
static std::pair< value_type,
bool > from_string (std::string const &s)
Additional Inherited Members
Public Types inherited from ripple::CryptoIdentifier< 20, 0, true >
typedef std::size_t size_type
typedef IdentifierStorage
< pre_size, size, post_size > value_type
typedef value_type::hasher hasher
typedef value_type::key_equal key_equal
Static Public Attributes inherited from ripple::CryptoIdentifier< 20, 0, true >
static std::size_t const pre_size
static size_type const size
static std::size_t const post_size
static std::uint8_t const token
static bool const checked
Detailed Description
Definition at line 30 of file RippleAccountID.h.
Member Function Documentation
static std::string ripple::RippleAccountIDTraits::to_string (value_type const & value) inline static
Convert to std::string.
Definition at line 48 of file RippleAccountID.h.
References ripple::CryptoIdentifier< 20, 0, true >::checked, ripple::Base58::getRippleAlphabet(), ripple::Base58::raw_encode(), and ripple::IdentifierStorage< PreSize, Size, PostSize >::storage().
     {
         value_type::storage_type const& storage (value.storage());
         // We will convert to little endian with an extra pad byte
         std::array <std::uint8_t, value_type::storage_size + 1> le;
         std::reverse_copy (storage.begin(), storage.end(), le.begin());
         // Set pad byte zero to make BIGNUM always positive
         le.back() = 0;
         return Base58::raw_encode (le.data(), le.data() + le.size(),
             Base58::getRippleAlphabet(), checked);
     }
The documentation for this class was generated from the following file:
rippled/src/ripple/types/api/RippleAccountID.h