rippled: beast::CharacterFunctions Class Reference
beast::CharacterFunctions Class Reference
#include <CharacterFunctions.h>
Static Public Member Functions
static beast_wchar toUpperCase (beast_wchar character) noexcept
static beast_wchar toLowerCase (beast_wchar character) noexcept
static bool isUpperCase (beast_wchar character) noexcept
static bool isLowerCase (beast_wchar character) noexcept
static bool isWhitespace (char character) noexcept
static bool isWhitespace (beast_wchar character) noexcept
static bool isDigit (char character) noexcept
static bool isDigit (beast_wchar character) noexcept
static bool isLetter (char character) noexcept
static bool isLetter (beast_wchar character) noexcept
static bool isLetterOrDigit (char character) noexcept
static bool isLetterOrDigit (beast_wchar character) noexcept
static int getHexDigitValue (beast_wchar digit) noexcept
template<typename CharPointerType >
static double readDoubleValue (CharPointerType &text) noexcept
template<typename CharPointerType >
static double getDoubleValue (CharPointerType text) noexcept
template<typename IntType , typename CharPointerType >
static IntType getIntValue (const CharPointerType text) noexcept
template<typename CharPointerType >
static size_t lengthUpTo (CharPointerType text, const size_t maxCharsToCount) noexcept
template<typename CharPointerType >
static size_t lengthUpTo (CharPointerType start, const CharPointerType end) noexcept
template<typename DestCharPointerType , typename SrcCharPointerType >
static void copyAll (DestCharPointerType &dest, SrcCharPointerType src) noexcept
template<typename DestCharPointerType , typename SrcCharPointerType >
static size_t copyWithDestByteLimit (DestCharPointerType &dest, SrcCharPointerType src, size_t maxBytesToWrite) noexcept
template<typename DestCharPointerType , typename SrcCharPointerType >
static void copyWithCharLimit (DestCharPointerType &dest, SrcCharPointerType src, int maxChars) noexcept
template<typename CharPointerType1 , typename CharPointerType2 >
static int compare (CharPointerType1 s1, CharPointerType2 s2) noexcept
template<typename CharPointerType1 , typename CharPointerType2 >
static int compareUpTo (CharPointerType1 s1, CharPointerType2 s2, int maxChars) noexcept
template<typename CharPointerType1 , typename CharPointerType2 >
static int compareIgnoreCase (CharPointerType1 s1, CharPointerType2 s2) noexcept
template<typename CharPointerType1 , typename CharPointerType2 >
static int compareIgnoreCaseUpTo (CharPointerType1 s1, CharPointerType2 s2, int maxChars) noexcept
template<typename CharPointerType1 , typename CharPointerType2 >
static int indexOf (CharPointerType1 textToSearch, const CharPointerType2 substringToLookFor) noexcept
template<typename CharPointerType1 , typename CharPointerType2 >
static CharPointerType1 find (CharPointerType1 textToSearch, const CharPointerType2 substringToLookFor) noexcept
template<typename CharPointerType1 , typename CharPointerType2 >
static int indexOfIgnoreCase (CharPointerType1 haystack, const CharPointerType2 needle) noexcept
template<typename Type >
static int indexOfChar (Type text, const beast_wchar charToFind) noexcept
template<typename Type >
static int indexOfCharIgnoreCase (Type text, beast_wchar charToFind) noexcept
template<typename Type >
static Type findEndOfWhitespace (const Type &text) noexcept
template<typename Type >
static Type findEndOfToken (const Type &text, const Type &breakCharacters, const Type &quoteCharacters)
Static Private Member Functions
static double mulexp10 (const double value, int exponent) noexcept
Detailed Description
A collection of functions for manipulating characters and character strings.
Most of these methods are designed for internal use by the String and CharPointer classes, but some of them may be useful to call directly.
See Also
String, CharPointer_UTF8, CharPointer_UTF16, CharPointer_UTF32
Definition at line 82 of file CharacterFunctions.h.
Member Function Documentation
template<typename CharPointerType1 , typename CharPointerType2 > static int beast::CharacterFunctions::compare (CharPointerType1 s1, CharPointerType2 s2) inline static noexcept
Compares two null-terminated character strings.
Definition at line 379 of file CharacterFunctions.h.
Referenced by beast::CharPointer_ASCII::compare(), beast::CharPointer_UTF32::compare(), beast::CharPointer_UTF16::compare(), and beast::CharPointer_UTF8::compare().
     {
         for (;;)
         {
             const int c1 = (int) s1.getAndAdvance();
             const int c2 = (int) s2.getAndAdvance();
             const int diff = c1 - c2;
             if (diff != 0)  return diff < 0 ? -1 : 1;
             if (c1 == 0)    break;
         }
         return 0;
     }
template<typename CharPointerType1 , typename CharPointerType2 > static int beast::CharacterFunctions::compareIgnoreCase (CharPointerType1 s1, CharPointerType2 s2) inline static noexcept
Compares two null-terminated character strings, using a case-independant match.
Definition at line 413 of file CharacterFunctions.h.
Referenced by beast::CharPointer_ASCII::compareIgnoreCase(), beast::CharPointer_UTF32::compareIgnoreCase(), beast::CharPointer_UTF16::compareIgnoreCase(), and beast::CharPointer_UTF8::compareIgnoreCase().
     {
         for (;;)
         {
             const int c1 = (int) s1.toUpperCase(); ++s1;
             const int c2 = (int) s2.toUpperCase(); ++s2;
             const int diff = c1 - c2;
             if (diff != 0)  return diff < 0 ? -1 : 1;
             if (c1 == 0)    break;
         }
         return 0;
     }
template<typename CharPointerType1 , typename CharPointerType2 > static int beast::CharacterFunctions::compareIgnoreCaseUpTo (CharPointerType1 s1, CharPointerType2 s2, int maxChars) inline static noexcept
Compares two null-terminated character strings, using a case-independent match.
Definition at line 430 of file CharacterFunctions.h.
Referenced by beast::CharPointer_UTF32::compareIgnoreCaseUpTo(), beast::CharPointer_ASCII::compareIgnoreCaseUpTo(), beast::CharPointer_UTF16::compareIgnoreCaseUpTo(), and beast::CharPointer_UTF8::compareIgnoreCaseUpTo().
     {
         while (--maxChars >= 0)
         {
             const int c1 = (int) s1.toUpperCase(); ++s1;
             const int c2 = (int) s2.toUpperCase(); ++s2;
             const int diff = c1 - c2;
             if (diff != 0)  return diff < 0 ? -1 : 1;
             if (c1 == 0)    break;
         }
         return 0;
     }
template<typename CharPointerType1 , typename CharPointerType2 > static int beast::CharacterFunctions::compareUpTo (CharPointerType1 s1, CharPointerType2 s2, int maxChars) inline static noexcept
Compares two null-terminated character strings, up to a given number of characters.
Definition at line 396 of file CharacterFunctions.h.
Referenced by beast::CharPointer_ASCII::compareUpTo(), beast::CharPointer_UTF32::compareUpTo(), beast::CharPointer_UTF16::compareUpTo(), and beast::CharPointer_UTF8::compareUpTo().
     {
         while (--maxChars >= 0)
         {
             const int c1 = (int) s1.getAndAdvance();
             const int c2 = (int) s2.getAndAdvance();
             const int diff = c1 - c2;
             if (diff != 0)  return diff < 0 ? -1 : 1;
             if (c1 == 0)    break;
         }
         return 0;
     }
template<typename DestCharPointerType , typename SrcCharPointerType > static void beast::CharacterFunctions::copyAll (DestCharPointerType & dest, SrcCharPointerType src) inline static noexcept
Copies null-terminated characters from one string to another.
Definition at line 315 of file CharacterFunctions.h.
Referenced by beast::CharPointer_ASCII::writeAll(), beast::CharPointer_UTF32::writeAll(), beast::CharPointer_UTF16::writeAll(), and beast::CharPointer_UTF8::writeAll().
     {
         for (;;)
         {
             const beast_wchar c = src.getAndAdvance();
             if (c == 0)
                 break;
             dest.write (c);
         }
         dest.writeNull();
     }
template<typename DestCharPointerType , typename SrcCharPointerType > static void beast::CharacterFunctions::copyWithCharLimit (DestCharPointerType & dest, SrcCharPointerType src, int maxChars) inline static noexcept
Copies characters from one string to another, up to a null terminator or a given maximum number of characters.
Definition at line 363 of file CharacterFunctions.h.
Referenced by beast::CharPointer_ASCII::writeWithCharLimit(), beast::CharPointer_UTF32::writeWithCharLimit(), beast::CharPointer_UTF16::writeWithCharLimit(), and beast::CharPointer_UTF8::writeWithCharLimit().
     {
         while (--maxChars > 0)
         {
             const beast_wchar c = src.getAndAdvance();
             if (c == 0)
                 break;
             dest.write (c);
         }
         dest.writeNull();
     }
template<typename DestCharPointerType , typename SrcCharPointerType > static size_t beast::CharacterFunctions::copyWithDestByteLimit (DestCharPointerType & dest, SrcCharPointerType src, size_t maxBytesToWrite) inline static noexcept
Copies characters from one string to another, up to a null terminator or a given byte size limit.
Definition at line 333 of file CharacterFunctions.h.
References beast::getAddressDifference().
Referenced by beast::CharPointer_ASCII::writeWithDestByteLimit(), beast::CharPointer_UTF32::writeWithDestByteLimit(), beast::CharPointer_UTF16::writeWithDestByteLimit(), and beast::CharPointer_UTF8::writeWithDestByteLimit().
     {
         typename DestCharPointerType::CharType const* const startAddress = dest.getAddress();
         size_t maxBytes = maxBytesToWrite;
         if (maxBytes >= sizeof (typename DestCharPointerType::CharType))
             maxBytes -= sizeof (typename DestCharPointerType::CharType); // (allow for a terminating null)
         else
             maxBytes = 0;
         for (;;)
         {
             const beast_wchar c = src.getAndAdvance();
             const size_t bytesNeeded = DestCharPointerType::getBytesRequiredFor (c);
             if (c == 0 || maxBytes < bytesNeeded)
                 break;
             maxBytes -= bytesNeeded;
             dest.write (c);
         }
         dest.writeNull();
         return (size_t) getAddressDifference (dest.getAddress(), startAddress)
                  + sizeof (typename DestCharPointerType::CharType);
     }
template<typename CharPointerType1 , typename CharPointerType2 > static CharPointerType1 beast::CharacterFunctions::find (CharPointerType1 textToSearch, const CharPointerType2 substringToLookFor) inline static noexcept
Returns a pointer to the first occurrence of a substring in a string. If the substring is not found, this will return a pointer to the string's null terminator.
Definition at line 471 of file CharacterFunctions.h.
     {
         const int substringLength = (int) substringToLookFor.length();
         while (textToSearch.compareUpTo (substringToLookFor, substringLength) != 0
                  && ! textToSearch.isEmpty())
             ++textToSearch;
         return textToSearch;
     }
template<typename Type > static Type beast::CharacterFunctions::findEndOfToken (const Type & text, const Type & breakCharacters, const Type & quoteCharacters) inline static
Returns a pointer to the first character in the string which is found in the breakCharacters string.
Definition at line 564 of file CharacterFunctions.h.
Referenced by beast::StringArray::addTokens().
     {
         Type t (text);
         beast_wchar currentQuoteChar = 0;
         while (! t.isEmpty())
         {
             const beast_wchar c = t.getAndAdvance();
             if (currentQuoteChar == 0 && breakCharacters.indexOf (c) >= 0)
             {
                 --t;
                 break;
             }
             if (quoteCharacters.indexOf (c) >= 0)
             {
                 if (currentQuoteChar == 0)
                     currentQuoteChar = c;
                 else if (currentQuoteChar == c)
                     currentQuoteChar = 0;
             }
         }
         return t;
     }
template<typename Type > static Type beast::CharacterFunctions::findEndOfWhitespace (const Type & text) inline static noexcept
Returns a pointer to the first non-whitespace character in a string. If the string contains only whitespace, this will return a pointer to its null terminator.
Definition at line 550 of file CharacterFunctions.h.
Referenced by beast::CharPointer_UTF32::findEndOfWhitespace(), beast::CharPointer_ASCII::findEndOfWhitespace(), beast::CharPointer_UTF16::findEndOfWhitespace(), and beast::CharPointer_UTF8::findEndOfWhitespace().
     {
         Type p (text);
         while (p.isWhitespace())
             ++p;
         return p;
     }
template<typename CharPointerType > static double beast::CharacterFunctions::getDoubleValue (CharPointerType text) inline static noexcept
Parses a character string, to read a floating-point value.
Definition at line 256 of file CharacterFunctions.h.
References readDoubleValue().
Referenced by beast::CharPointer_UTF32::getDoubleValue(), beast::CharPointer_ASCII::getDoubleValue(), beast::CharPointer_UTF16::getDoubleValue(), and beast::CharPointer_UTF8::getDoubleValue().
     {
         return readDoubleValue (text);
     }
int beast::CharacterFunctions::getHexDigitValue (beast_wchar digit) static noexcept
Returns 0 to 16 for '0' to 'F", or -1 for characters that aren't a legal hex digit.
Definition at line 116 of file CharacterFunctions.cpp.
Referenced by beast::HexConverter< Type >::stringToHex().
 {
     unsigned int d = (unsigned int) digit - '0';
     if (d < (unsigned int) 10)
         return (int) d;
     d += (unsigned int) ('0' - 'a');
     if (d < (unsigned int) 6)
         return (int) d + 10;
     d += (unsigned int) ('a' - 'A');
     if (d < (unsigned int) 6)
         return (int) d + 10;
     return -1;
 }
template<typename IntType , typename CharPointerType > static IntType beast::CharacterFunctions::getIntValue (const CharPointerType text) inline static noexcept
Parses a character string, to read an integer value.
Definition at line 264 of file CharacterFunctions.h.
     {
         IntType v = 0;
         CharPointerType s (text.findEndOfWhitespace());
         const bool isNeg = *s == '-';
         if (isNeg)
             ++s;
         for (;;)
         {
             const beast_wchar c = s.getAndAdvance();
             if (c >= '0' && c <= '9')
                 v = v * 10 + (IntType) (c - '0');
             else
                 break;
         }
         return isNeg ? -v : v;
     }
template<typename CharPointerType1 , typename CharPointerType2 > static int beast::CharacterFunctions::indexOf (CharPointerType1 textToSearch, const CharPointerType2 substringToLookFor) inline static noexcept
Finds the character index of a given substring in another string. Returns -1 if the substring is not found.
Definition at line 449 of file CharacterFunctions.h.
Referenced by beast::CharPointer_UTF32::indexOf(), beast::CharPointer_ASCII::indexOf(), beast::CharPointer_UTF16::indexOf(), and beast::CharPointer_UTF8::indexOf().
     {
         int index = 0;
         const int substringLength = (int) substringToLookFor.length();
         for (;;)
         {
             if (textToSearch.compareUpTo (substringToLookFor, substringLength) == 0)
                 return index;
             if (textToSearch.getAndAdvance() == 0)
                 return -1;
             ++index;
         }
     }
template<typename Type > static int beast::CharacterFunctions::indexOfChar (Type text, const beast_wchar charToFind) inline static noexcept
Finds the character index of a given character in another string. Returns -1 if the character is not found.
Definition at line 508 of file CharacterFunctions.h.
Referenced by beast::CharPointer_UTF32::indexOf(), beast::CharPointer_ASCII::indexOf(), beast::CharPointer_UTF16::indexOf(), and beast::CharPointer_UTF8::indexOf().
     {
         int i = 0;
         while (! text.isEmpty())
         {
             if (text.getAndAdvance() == charToFind)
                 return i;
             ++i;
         }
         return -1;
     }
template<typename Type > static int beast::CharacterFunctions::indexOfCharIgnoreCase (Type text, beast_wchar charToFind) inline static noexcept
Finds the character index of a given character in another string, using a case-independent match. Returns -1 if the character is not found.
Definition at line 528 of file CharacterFunctions.h.
References toLowerCase().
Referenced by beast::CharPointer_UTF32::indexOf(), beast::CharPointer_ASCII::indexOf(), beast::CharPointer_UTF16::indexOf(), and beast::CharPointer_UTF8::indexOf().
     {
         charToFind = CharacterFunctions::toLowerCase (charToFind);
         int i = 0;
         while (! text.isEmpty())
         {
             if (text.toLowerCase() == charToFind)
                 return i;
             ++text;
             ++i;
         }
         return -1;
     }
template<typename CharPointerType1 , typename CharPointerType2 > static int beast::CharacterFunctions::indexOfIgnoreCase (CharPointerType1 haystack, const CharPointerType2 needle) inline static noexcept
Finds the character index of a given substring in another string, using a case-independent match. Returns -1 if the substring is not found.
Definition at line 487 of file CharacterFunctions.h.
Referenced by beast::String::indexOfIgnoreCase().
     {
         int index = 0;
         const int needleLength = (int) needle.length();
         for (;;)
         {
             if (haystack.compareIgnoreCaseUpTo (needle, needleLength) == 0)
                 return index;
             if (haystack.getAndAdvance() == 0)
                 return -1;
             ++index;
         }
     }
bool beast::CharacterFunctions::isDigit (char character) static noexcept
Checks whether a character is a digit.
Definition at line 83 of file CharacterFunctions.cpp.
Referenced by beast::SemanticVersion::chopUInt(), beast::File::getNonexistentChildFile(), beast::CharPointer_UTF32::isDigit(), beast::CharPointer_ASCII::isDigit(), and beast::CharPointer_UTF16::isDigit().
 {
     return (character >= '0' && character <= '9');
 }
bool beast::CharacterFunctions::isDigit (beast_wchar character) static noexcept
Checks whether a character is a digit.
Definition at line 88 of file CharacterFunctions.cpp.
 {
     return iswdigit ((wchar_t) character) != 0;
 }
bool beast::CharacterFunctions::isLetter (char character) static noexcept
Checks whether a character is alphabetic.
Definition at line 93 of file CharacterFunctions.cpp.
Referenced by beast::CharPointer_UTF32::isLetter(), beast::CharPointer_ASCII::isLetter(), beast::CharPointer_UTF16::isLetter(), and beast::CharPointer_UTF8::isLetter().
 {
     return (character >= 'a' && character <= 'z')
         || (character >= 'A' && character <= 'Z');
 }
bool beast::CharacterFunctions::isLetter (beast_wchar character) static noexcept
Checks whether a character is alphabetic.
Definition at line 99 of file CharacterFunctions.cpp.
 {
     return iswalpha ((wchar_t) character) != 0;
 }
bool beast::CharacterFunctions::isLetterOrDigit (char character) static noexcept
Checks whether a character is alphabetic or numeric.
Definition at line 104 of file CharacterFunctions.cpp.
Referenced by beast::CharPointer_UTF32::isLetterOrDigit(), beast::CharPointer_ASCII::isLetterOrDigit(), beast::CharPointer_UTF16::isLetterOrDigit(), and beast::CharPointer_UTF8::isLetterOrDigit().
 {
     return (character >= 'a' && character <= 'z')
         || (character >= 'A' && character <= 'Z')
         || (character >= '0' && character <= '9');
 }
bool beast::CharacterFunctions::isLetterOrDigit (beast_wchar character) static noexcept
Checks whether a character is alphabetic or numeric.
Definition at line 111 of file CharacterFunctions.cpp.
 {
     return iswalnum ((wchar_t) character) != 0;
 }
bool beast::CharacterFunctions::isLowerCase (beast_wchar character) static noexcept
Checks whether a unicode character is lower-case.
Definition at line 59 of file CharacterFunctions.cpp.
Referenced by beast::CharPointer_UTF32::isLowerCase(), beast::CharPointer_ASCII::isLowerCase(), beast::CharPointer_UTF16::isLowerCase(), and beast::CharPointer_UTF8::isLowerCase().
 {
    #if BEAST_WINDOWS
     return iswlower ((wchar_t) character) != 0;
    #else
     return toUpperCase (character) != character;
    #endif
 }
bool beast::CharacterFunctions::isUpperCase (beast_wchar character) static noexcept
Checks whether a unicode character is upper-case.
Definition at line 50 of file CharacterFunctions.cpp.
Referenced by beast::CharPointer_UTF32::isUpperCase(), beast::CharPointer_ASCII::isUpperCase(), beast::CharPointer_UTF16::isUpperCase(), and beast::CharPointer_UTF8::isUpperCase().
 {
    #if BEAST_WINDOWS
     return iswupper ((wchar_t) character) != 0;
    #else
     return toLowerCase (character) != character;
    #endif
 }
bool beast::CharacterFunctions::isWhitespace (char character) static noexcept
Checks whether a character is whitespace.
Definition at line 73 of file CharacterFunctions.cpp.
Referenced by beast::CharPointer_UTF32::isWhitespace(), beast::CharPointer_ASCII::isWhitespace(), and beast::CharPointer_UTF16::isWhitespace().
 {
     return character == ' ' || (character <= 13 && character >= 9);
 }
bool beast::CharacterFunctions::isWhitespace (beast_wchar character) static noexcept
Checks whether a character is whitespace.
Definition at line 78 of file CharacterFunctions.cpp.
 {
     return iswspace ((wchar_t) character) != 0;
 }
template<typename CharPointerType > static size_t beast::CharacterFunctions::lengthUpTo (CharPointerType text, const size_t maxCharsToCount) inline static noexcept
Counts the number of characters in a given string, stopping if the count exceeds a specified limit.
Definition at line 290 of file CharacterFunctions.h.
Referenced by beast::CharPointer_ASCII::lengthUpTo(), beast::CharPointer_UTF32::lengthUpTo(), beast::CharPointer_UTF16::lengthUpTo(), and beast::CharPointer_UTF8::lengthUpTo().
     {
         size_t len = 0;
         while (len < maxCharsToCount && text.getAndAdvance() != 0)
             ++len;
         return len;
     }
template<typename CharPointerType > static size_t beast::CharacterFunctions::lengthUpTo (CharPointerType start, const CharPointerType end) inline static noexcept
Counts the number of characters in a given string, stopping if the count exceeds a specified end-pointer.
Definition at line 303 of file CharacterFunctions.h.
     {
         size_t len = 0;
         while (start < end && start.getAndAdvance() != 0)
             ++len;
         return len;
     }
double beast::CharacterFunctions::mulexp10 (const double value, int exponent) static private noexcept
Definition at line 133 of file CharacterFunctions.cpp.
References value.
Referenced by readDoubleValue().
 {
     if (exponent == 0)
         return value;
     if (value == 0)
         return 0;
     const bool negative = (exponent < 0);
     if (negative)
         exponent = -exponent;
     double result = 1.0, power = 10.0;
     for (int bit = 1; exponent != 0; bit <<= 1)
     {
         if ((exponent & bit) != 0)
         {
             exponent ^= bit;
             result *= power;
             if (exponent == 0)
                 break;
         }
         power *= power;
     }
     return negative ? (value / result) : (value * result);
 }
template<typename CharPointerType > static double beast::CharacterFunctions::readDoubleValue (CharPointerType & text) inline static noexcept
Parses a character string to read a floating-point number. Note that this will advance the pointer that is passed in, leaving it at the end of the number.
Definition at line 125 of file CharacterFunctions.h.
References ripple::max(), and mulexp10().
Referenced by getDoubleValue().
     {
         double result[3] = { 0 }, accumulator[2] = { 0 };
         int exponentAdjustment[2] = { 0 }, exponentAccumulator[2] = { -1, -1 };
         int exponent = 0, decPointIndex = 0, digit = 0;
         int lastDigit = 0, numSignificantDigits = 0;
         bool isNegative = false, digitsFound = false;
         const int maxSignificantDigits = 15 + 2;
         text = text.findEndOfWhitespace();
         beast_wchar c = *text;
         switch (c)
         {
             case '-':   isNegative = true; // fall-through..
             case '+':   c = *++text;
         }
         switch (c)
         {
             case 'n':
             case 'N':
                 if ((text[1] == 'a' || text[1] == 'A') && (text[2] == 'n' || text[2] == 'N'))
                     return std::numeric_limits<double>::quiet_NaN();
                 break;
             case 'i':
             case 'I':
                 if ((text[1] == 'n' || text[1] == 'N') && (text[2] == 'f' || text[2] == 'F'))
                     return std::numeric_limits<double>::infinity();
                 break;
         }
         for (;;)
         {
             if (text.isDigit())
             {
                 lastDigit = digit;
                 digit = (int) text.getAndAdvance() - '0';
                 digitsFound = true;
                 if (decPointIndex != 0)
                     exponentAdjustment[1]++;
                 if (numSignificantDigits == 0 && digit == 0)
                     continue;
                 if (++numSignificantDigits > maxSignificantDigits)
                 {
                     if (digit > 5)
                         ++accumulator [decPointIndex];
                     else if (digit == 5 && (lastDigit & 1) != 0)
                         ++accumulator [decPointIndex];
                     if (decPointIndex > 0)
                         exponentAdjustment[1]--;
                     else
                         exponentAdjustment[0]++;
                     while (text.isDigit())
                     {
                         ++text;
                         if (decPointIndex == 0)
                             exponentAdjustment[0]++;
                     }
                 }
                 else
                 {
                     const double maxAccumulatorValue = (double) ((std::numeric_limits<unsigned int>::max() - 9) / 10);
                     if (accumulator [decPointIndex] > maxAccumulatorValue)
                     {
                         result [decPointIndex] = mulexp10 (result [decPointIndex], exponentAccumulator [decPointIndex])
                                                     + accumulator [decPointIndex];
                         accumulator [decPointIndex] = 0;
                         exponentAccumulator [decPointIndex] = 0;
                     }
                     accumulator [decPointIndex] = accumulator[decPointIndex] * 10 + digit;
                     exponentAccumulator [decPointIndex]++;
                 }
             }
             else if (decPointIndex == 0 && *text == '.')
             {
                 ++text;
                 decPointIndex = 1;
                 if (numSignificantDigits > maxSignificantDigits)
                 {
                     while (text.isDigit())
                         ++text;
                     break;
                 }
             }
             else
             {
                 break;
             }
         }
         result[0] = mulexp10 (result[0], exponentAccumulator[0]) + accumulator[0];
         if (decPointIndex != 0)
             result[1] = mulexp10 (result[1], exponentAccumulator[1]) + accumulator[1];
         c = *text;
         if ((c == 'e' || c == 'E') && digitsFound)
         {
             bool negativeExponent = false;
             switch (*++text)
             {
                 case '-':   negativeExponent = true; // fall-through..
                 case '+':   ++text;
             }
             while (text.isDigit())
                 exponent = (exponent * 10) + ((int) text.getAndAdvance() - '0');
             if (negativeExponent)
                 exponent = -exponent;
         }
         double r = mulexp10 (result[0], exponent + exponentAdjustment[0]);
         if (decPointIndex != 0)
             r += mulexp10 (result[1], exponent - exponentAdjustment[1]);
         return isNegative ? -r : r;
     }
beast_wchar beast::CharacterFunctions::toLowerCase (beast_wchar character) static noexcept
Converts a character to lower-case.
Definition at line 45 of file CharacterFunctions.cpp.
Referenced by beast::WildCardMatcher< CharPointer >::characterMatches(), beast::File::getRelativePathFrom(), indexOfCharIgnoreCase(), beast::CharPointer_UTF32::toLowerCase(), beast::CharPointer_ASCII::toLowerCase(), beast::CharPointer_UTF16::toLowerCase(), and beast::CharPointer_UTF8::toLowerCase().
 {
     return towlower ((wchar_t) character);
 }
beast_wchar beast::CharacterFunctions::toUpperCase (beast_wchar character) static noexcept
Converts a character to upper-case.
Definition at line 40 of file CharacterFunctions.cpp.
Referenced by beast::CharPointer_UTF32::toUpperCase(), beast::CharPointer_ASCII::toUpperCase(), beast::CharPointer_UTF16::toUpperCase(), and beast::CharPointer_UTF8::toUpperCase().
 {
     return towupper ((wchar_t) character);
 }
The documentation for this class was generated from the following files:
rippled/src/beast/beast/strings/CharacterFunctions.h
rippled/src/beast/beast/strings/impl/CharacterFunctions.cpp