rippled: rocksdb::InternalKeyPropertiesCollector Class Reference
rocksdb::InternalKeyPropertiesCollector Class Reference
#include <table_properties_collector.h>
Public Member Functions
virtual Status Add (const Slice &key, const Slice &value) override
virtual Status Finish (TableProperties::UserCollectedProperties *properties) override
virtual const char * Name () const override
TableProperties::UserCollectedProperties GetReadableProperties () const override
Public Member Functions inherited from rocksdb::TablePropertiesCollector
virtual ~TablePropertiesCollector ()
Private Attributes
uint64_t deleted_keys_ = 0
Detailed Description
Definition at line 23 of file table_properties_collector.h.
Member Function Documentation
Status rocksdb::InternalKeyPropertiesCollector::Add (const Slice & key, const Slice & value) override virtual
Implements rocksdb::TablePropertiesCollector.
Definition at line 94 of file table_properties_collector.cc.
References deleted_keys_, rocksdb::Status::InvalidArgument(), rocksdb::kTypeDeletion, rocksdb::Status::OK(), rocksdb::ParseInternalKey(), and rocksdb::ParsedInternalKey::type.
{
   ParsedInternalKey ikey;
   if (!ParseInternalKey(key, &ikey)) {
     return Status::InvalidArgument("Invalid internal key");
   }
   if (ikey.type == ValueType::kTypeDeletion) {
     ++deleted_keys_;
   }
   return Status::OK();
 }
Status rocksdb::InternalKeyPropertiesCollector::Finish (TableProperties::UserCollectedProperties * properties) override virtual
Implements rocksdb::TablePropertiesCollector.
Definition at line 108 of file table_properties_collector.cc.
References deleted_keys_, rocksdb::InternalKeyTablePropertiesNames::kDeletedKeys, rocksdb::Status::OK(), and rocksdb::PutVarint64().
{
   assert(properties);
   assert(properties->find(
         InternalKeyTablePropertiesNames::kDeletedKeys) == properties->end());
   std::string val;
   PutVarint64(&val, deleted_keys_);
   properties->insert({ InternalKeyTablePropertiesNames::kDeletedKeys, val });
   return Status::OK();
 }
TableProperties::UserCollectedProperties rocksdb::InternalKeyPropertiesCollector::GetReadableProperties () const override virtual
Implements rocksdb::TablePropertiesCollector.
Definition at line 122 of file table_properties_collector.cc.
References deleted_keys_, and beast::IP::to_string().
{
   return {
     { "kDeletedKeys", std::to_string(deleted_keys_) }
   };
 }
virtual const char* rocksdb::InternalKeyPropertiesCollector::Name () const inline override virtual
Implements rocksdb::TablePropertiesCollector.
Definition at line 30 of file table_properties_collector.h.
{
     return "InternalKeyPropertiesCollector";
   }
Member Data Documentation
uint64_t rocksdb::InternalKeyPropertiesCollector::deleted_keys_ = 0 private
Definition at line 38 of file table_properties_collector.h.
Referenced by Add(), Finish(), and GetReadableProperties().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/db/table_properties_collector.h
rippled/src/ripple/rocksdb/rocksdb/db/table_properties_collector.cc