rippled: beast::DeadlineTimer::Manager Class Reference
beast::DeadlineTimer::Manager Class Reference
Public Member Functions
Manager ()
~Manager ()
void activate (DeadlineTimer &timer, double secondsRecurring, RelativeTime const &when)
void deactivate (DeadlineTimer &timer)
void run ()
void insertSorted (DeadlineTimer &timer)
Private Types
typedef CriticalSection LockType
typedef List< DeadlineTimer > Items
Private Attributes
CriticalSection m_mutex
Items m_items
Additional Inherited Members
Protected Types inherited from beast::Thread
typedef void * ThreadID
Protected Member Functions inherited from beast::Thread
Thread (const String &threadName)
virtual ~Thread ()
void startThread ()
void startThread (int priority)
bool stopThread (int timeOutMilliseconds=-1)
void stopThreadAsync ()
bool isThreadRunning () const
void signalThreadShouldExit ()
bool threadShouldExit () const
bool waitForThreadToExit (int timeOutMilliseconds=-1) const
bool setPriority (int priority)
void setAffinityMask (std::uint32_t affinityMask)
bool wait (int timeOutMilliseconds=-1) const
void notify () const
ThreadID getThreadId () const noexcept
const String & getThreadName () const
Static Protected Member Functions inherited from beast::Thread
static bool setCurrentThreadPriority (int priority)
static void setCurrentThreadAffinityMask (std::uint32_t affinityMask)
static void sleep (int milliseconds)
static void yield ()
static ThreadID getCurrentThreadId ()
static Thread * getCurrentThread ()
static void setCurrentThreadName (const String &newThreadName)
Detailed Description
Definition at line 23 of file DeadlineTimer.cpp.
Member Typedef Documentation
typedef List<DeadlineTimer> beast::DeadlineTimer::Manager::Items private
Definition at line 29 of file DeadlineTimer.cpp.
typedef CriticalSection beast::DeadlineTimer::Manager::LockType private
Definition at line 28 of file DeadlineTimer.cpp.
Constructor & Destructor Documentation
beast::DeadlineTimer::Manager::Manager () inline
Definition at line 32 of file DeadlineTimer.cpp.
References beast::Thread::startThread().
                : Thread ("DeadlineTimer::Manager")
     {
         startThread ();
     }
beast::DeadlineTimer::Manager::~Manager () inline
Definition at line 37 of file DeadlineTimer.cpp.
References bassert, beast::List< typename, typename >::empty(), m_items, beast::Thread::notify(), beast::Thread::signalThreadShouldExit(), and beast::Thread::waitForThreadToExit().
     {
         signalThreadShouldExit ();
         notify ();
         waitForThreadToExit ();
         bassert (m_items.empty ());
     }
Member Function Documentation
void beast::DeadlineTimer::Manager::activate (DeadlineTimer & timer, double secondsRecurring, RelativeTime const & when) inline
Definition at line 48 of file DeadlineTimer.cpp.
References bassert, beast::List< typename, typename >::erase(), insertSorted(), beast::List< typename, typename >::iterator_to(), beast::DeadlineTimer::m_isActive, m_items, m_mutex, beast::DeadlineTimer::m_notificationTime, beast::DeadlineTimer::m_secondsRecurring, and beast::Thread::notify().
     {
         bassert (secondsRecurring >= 0);
         std::lock_guard <LockType> lock (m_mutex);
         if (timer.m_isActive)
         {
             m_items.erase (m_items.iterator_to (timer));
             timer.m_isActive = false;
         }
         timer.m_secondsRecurring = secondsRecurring;
         timer.m_notificationTime = when;
         insertSorted (timer);
         timer.m_isActive = true;
         notify ();
     }
void beast::DeadlineTimer::Manager::deactivate (DeadlineTimer & timer) inline
Definition at line 74 of file DeadlineTimer.cpp.
References beast::List< typename, typename >::erase(), beast::List< typename, typename >::iterator_to(), beast::DeadlineTimer::m_isActive, m_items, m_mutex, and beast::Thread::notify().
     {
         std::lock_guard <LockType> lock (m_mutex);
         if (timer.m_isActive)
         {
             m_items.erase (m_items.iterator_to (timer));
             timer.m_isActive = false;
             notify ();
         }
     }
void beast::DeadlineTimer::Manager::insertSorted (DeadlineTimer & timer) inline
Definition at line 175 of file DeadlineTimer.cpp.
References beast::List< typename, typename >::begin(), beast::List< typename, typename >::empty(), beast::List< typename, typename >::end(), beast::List< typename, typename >::insert(), m_items, beast::DeadlineTimer::m_notificationTime, and beast::List< typename, typename >::push_back().
Referenced by activate(), and run().
     {
         if (! m_items.empty ())
         {
             Items::iterator before = m_items.begin ();
             for (;;)
             {
                 if (before->m_notificationTime >= timer.m_notificationTime)
                 {
                     m_items.insert (before, timer);
                     break;
                 }
                 ++before;
                 if (before == m_items.end ())
                 {
                     m_items.push_back (timer);
                     break;
                 }
             }
         }
         else
         {
             m_items.push_back (timer);
         }
     }
void beast::DeadlineTimer::Manager::run () inline virtual
Must be implemented to perform the thread's actual code.
Remember that the thread must regularly check the threadShouldExit() method whilst running, and if this returns true it should return from the run() method as soon as possible to avoid being forcibly killed.
See Also
threadShouldExit, startThread
Implements beast::Thread.
Definition at line 88 of file DeadlineTimer.cpp.
References bassert, beast::List< typename, typename >::empty(), beast::RelativeTime::fromStartup(), beast::List< typename, typename >::front(), insertSorted(), beast::DeadlineTimer::m_isActive, m_items, beast::DeadlineTimer::m_listener, m_mutex, beast::DeadlineTimer::m_notificationTime, beast::DeadlineTimer::m_secondsRecurring, ripple::max(), beast::DeadlineTimer::Listener::onDeadlineTimer(), beast::List< typename, typename >::pop_front(), beast::Thread::threadShouldExit(), and beast::Thread::wait().
     {
         while (! threadShouldExit ())
         {
             RelativeTime const currentTime (
                 RelativeTime::fromStartup ());
             double seconds (0);
             DeadlineTimer* timer (nullptr);
             {
                 std::lock_guard <LockType> lock (m_mutex);
                 // See if a timer expired
                 if (! m_items.empty ())
                 {
                     timer = &m_items.front ();
                     // Has this timer expired?
                     if (timer->m_notificationTime <= currentTime)
                     {
                         // Expired, remove it from the list.
                         bassert (timer->m_isActive);
                         m_items.pop_front ();
                         // Is the timer recurring?
                         if (timer->m_secondsRecurring > 0)
{
                             // Yes so set the timer again.
                             timer->m_notificationTime =
                                 currentTime + timer->m_secondsRecurring;
                             // Put it back into the list as active
                             insertSorted (*timer);
                         }
                         else
{
                             // Not a recurring timer, deactivate it.
                             timer->m_isActive = false;
                         }
                         timer->m_listener->onDeadlineTimer (*timer);
                         // re-loop
                         seconds = -1;
                     }
                     else
                     {
                         seconds = (
                             timer->m_notificationTime - currentTime).inSeconds ();
                         // Can't be zero and come into the else clause.
                         bassert (seconds != 0);
                         // Don't call the listener
                         timer = nullptr;
                     }
                 }
             }
             // Note that we have released the lock here.
             if (seconds > 0)
             {
                 // Wait until interrupt or next timer.
                 //
                 int const milliSeconds (std::max (
                     static_cast <int> (seconds * 1000 + 0.5), 1));
                 bassert (milliSeconds > 0);
                 wait (milliSeconds);
             }
             else if (seconds == 0)
             {
                 // Wait until interrupt
                 //
                 wait ();
             }
             else
             {
                 // Do not wait. This can happen if the recurring timer duration
                 // is extremely short, or if a listener wastes too much time in
                 // their callback.
             }
         }
     }
Member Data Documentation
Items beast::DeadlineTimer::Manager::m_items private
Definition at line 206 of file DeadlineTimer.cpp.
Referenced by activate(), deactivate(), insertSorted(), run(), and ~Manager().
CriticalSection beast::DeadlineTimer::Manager::m_mutex private
Definition at line 205 of file DeadlineTimer.cpp.
Referenced by activate(), deactivate(), and run().
The documentation for this class was generated from the following file:
rippled/src/beast/modules/beast_core/thread/DeadlineTimer.cpp