rippled: ripple::RPC Namespace Reference
ripple::RPC Namespace Reference
Namespaces
detail
Classes
struct ErrorInfo
class Manager
struct Request
class Command
class DoPrint
class LegacyPathFind
class ManagerImp
class JSONRPC_test
Functions
ErrorInfo const & get_error_info (error_code_i code)
bool contains_error (Json::Value const &json)
std::unique_ptr< Manager > make_Manager (beast::Journal journal)
Json::Value accountFromString (Ledger::ref lrLedger, RippleAddress &naAccount, bool &bIndex, const std::string &strIdent, const int iIndex, const bool bStrict, NetworkOPs &netOps)
Json::Value accounts (Ledger::ref lrLedger, const RippleAddress &naMasterGenerator, NetworkOPs &netOps)
Json::Value authorize (Ledger::ref lrLedger, const RippleAddress &naRegularSeed, const RippleAddress &naSrcAccountID, RippleAddress &naAccountPublic, RippleAddress &naAccountPrivate, STAmount &saSrcBalance, const STAmount &saFee, AccountState::pointer &asSrc, const RippleAddress &naVerifyGenerator, NetworkOPs &netOps)
Json::Value getMasterGenerator (Ledger::ref lrLedger, const RippleAddress &naRegularSeed, RippleAddress &naMasterGenerator, NetworkOPs &netOps)
Json::Value lookupLedger (Json::Value const &params, Ledger::pointer &lpLedger, NetworkOPs &netOps)
boost::unordered_set
< RippleAddress > parseAccountIds (const Json::Value &jvArray)
static void autofill_fee (Json::Value &request, Ledger::pointer ledger, Json::Value &result, bool admin)
Json::Value transactionSign (Json::Value params, bool bSubmit, bool bFailHard, Application::ScopedLockType &mlh, NetworkOPs &netOps, int role)
BEAST_DEFINE_TESTSUITE (JSONRPC, ripple_app, ripple)
void inject_error (error_code_i code, Json::Value &json)
void inject_error (int code, Json::Value &json)
void inject_error (error_code_i code, std::string const &message, Json::Value &json)
Json::Value make_error (error_code_i code)
Json::Value make_error (error_code_i code, std::string const &message)
Json::Value make_param_error (std::string const &message)
std::string missing_field_message (std::string const &name)
Json::Value missing_field_error (std::string const &name)
std::string object_field_message (std::string const &name)
Json::Value object_field_error (std::string const &name)
std::string invalid_field_message (std::string const &name)
Json::Value invalid_field_error (std::string const &name)
std::string expected_field_message (std::string const &name, std::string const &type)
Json::Value expected_field_error (std::string const &name, std::string const &type)
Variables
static const int LEDGER_CURRENT = -1
static const int LEDGER_CLOSED = -2
static const int LEDGER_VALIDATED = -3
Function Documentation
Json::Value ripple::RPC::accountFromString (Ledger::ref lrLedger, RippleAddress & naAccount, bool & bIndex, const std::string & strIdent, const int iIndex, const bool bStrict, NetworkOPs & netOps)
Definition at line 28 of file AccountFromString.cpp.
References ripple::RippleAddress::accountPrivateDecrypt(), ripple::RippleAddress::createGeneratorPublic(), ripple::RippleAddress::getAccountID(), ripple::Base58::getBitcoinAlphabet(), ripple::NetworkOPs::getGenerator(), nothing, Json::objectValue, ripple::rpcACT_BITCOIN, ripple::rpcACT_MALFORMED, ripple::rpcBAD_SEED, ripple::rpcError(), ripple::rpcNO_GEN_DECRYPT, ripple::RippleAddress::setAccountID(), ripple::RippleAddress::setAccountPrivate(), ripple::RippleAddress::setAccountPublic(), ripple::RippleAddress::setGenerator(), ripple::RippleAddress::setSeedGeneric(), and rocksdb::crc32c::Value().
Referenced by ripple::RPCHandler::doAccountCurrencies(), ripple::RPCHandler::doAccountInfo(), ripple::RPCHandler::doAccountLines(), ripple::RPCHandler::doAccountOffers(), and ripple::RPCHandler::doOwnerInfo().
 {
     RippleAddress   naSeed;
     if (naAccount.setAccountPublic (strIdent) || naAccount.setAccountID (strIdent))
     {
         // Got the account.
         bIndex  = false;
     }
     else if (bStrict)
     {
         return naAccount.setAccountID (strIdent, Base58::getBitcoinAlphabet ())
                ? rpcError (rpcACT_BITCOIN)
                : rpcError (rpcACT_MALFORMED);
     }
     // Must be a seed.
     else if (!naSeed.setSeedGeneric (strIdent))
     {
         return rpcError (rpcBAD_SEED);
     }
     else
     {
         // We allow the use of the seeds to access #0.
         // This is poor practice and merely for debuging convenience.
         RippleAddress       naRegular0Public;
         RippleAddress       naRegular0Private;
         RippleAddress       naGenerator     = RippleAddress::createGeneratorPublic (naSeed);
         naRegular0Public.setAccountPublic (naGenerator, 0);
         naRegular0Private.setAccountPrivate (naGenerator, naSeed, 0);
         //      uint160             uGeneratorID    = naRegular0Public.getAccountID();
         SLE::pointer        sleGen          = netOps.getGenerator (lrLedger, naRegular0Public.getAccountID ());
         if (!sleGen)
         {
             // Didn't find a generator map, assume it is a master generator.
             nothing ();
         }
         else
         {
             // Found master public key.
             Blob    vucCipher               = sleGen->getFieldVL (sfGenerator);
             Blob    vucMasterGenerator      = naRegular0Private.accountPrivateDecrypt (naRegular0Public, vucCipher);
             if (vucMasterGenerator.empty ())
             {
                 rpcError (rpcNO_GEN_DECRYPT);
             }
             naGenerator.setGenerator (vucMasterGenerator);
         }
         bIndex  = !iIndex;
         naAccount.setAccountPublic (naGenerator, iIndex);
     }
     return Json::Value (Json::objectValue);
 }
Json::Value ripple::RPC::accounts (Ledger::ref lrLedger, const RippleAddress & naMasterGenerator, NetworkOPs & netOps)
Definition at line 25 of file Accounts.cpp.
References Json::Value::append(), Json::arrayValue, ripple::NetworkOPs::getAccountState(), Json::objectValue, and ripple::RippleAddress::setAccountPublic().
Referenced by ripple::RPCHandler::doWalletAccounts(), ripple::TransactionMetaSet::getAffectedAccounts(), ripple::NetworkOPsImp::getLedgerAffectedAccounts(), and ripple::SerializedTransaction::getMentionedAccounts().
 {
     Json::Value jsonAccounts (Json::arrayValue);
     // YYY Don't want to leak to thin server that these accounts are related.
     // YYY Would be best to alternate requests to servers and to cache results.
     unsigned int    uIndex  = 0;
     do
     {
         RippleAddress       naAccount;
         naAccount.setAccountPublic (naMasterGenerator, uIndex++);
         AccountState::pointer as    = netOps.getAccountState (lrLedger, naAccount);
         if (as)
         {
             Json::Value jsonAccount (Json::objectValue);
             as->addJson (jsonAccount);
             jsonAccounts.append (jsonAccount);
         }
         else
         {
             uIndex  = 0;
         }
     }
     while (uIndex);
     return jsonAccounts;
 }
Json::Value ripple::RPC::authorize (Ledger::ref lrLedger, const RippleAddress & naRegularSeed, const RippleAddress & naSrcAccountID, RippleAddress & naAccountPublic, RippleAddress & naAccountPrivate, STAmount & saSrcBalance, const STAmount & saFee, AccountState::pointer & asSrc, const RippleAddress & naVerifyGenerator, NetworkOPs & netOps)
Definition at line 34 of file Authorize.cpp.
References ripple::RippleAddress::createGeneratorPublic(), Json::Value::empty(), ripple::RippleAddress::getAccountID(), ripple::NetworkOPs::getAccountState(), ripple::getConfig(), getMasterGenerator(), ripple::STAmount::getText(), ripple::RippleAddress::humanAccountID(), ripple::RippleAddress::isValid(), ripple::lsDEBUG, ripple::lsINFO, ripple::rpcACT_NOT_FOUND, ripple::rpcError(), ripple::rpcINSUF_FUNDS, ripple::rpcPASSWD_CHANGED, ripple::rpcSRC_ACT_NOT_FOUND, ripple::rpcWRONG_SEED, ripple::RippleAddress::setAccountPrivate(), ripple::RippleAddress::setAccountPublic(), rocksdb::crc32c::Value(), and WriteLog.
 {
     // Source/paying account must exist.
     asSrc   = netOps.getAccountState (lrLedger, naSrcAccountID);
     if (!asSrc)
     {
         return rpcError (rpcSRC_ACT_NOT_FOUND);
     }
     RippleAddress   naMasterGenerator;
     if (asSrc->haveAuthorizedKey ())
     {
         Json::Value obj = getMasterGenerator (lrLedger, naRegularSeed, naMasterGenerator, netOps);
         if (!obj.empty ())
             return obj;
     }
     else
     {
         // Try the seed as a master seed.
         naMasterGenerator   = RippleAddress::createGeneratorPublic (naRegularSeed);
     }
     // If naVerifyGenerator is provided, make sure it is the master generator.
     if (naVerifyGenerator.isValid () && naMasterGenerator != naVerifyGenerator)
     {
         return rpcError (rpcWRONG_SEED);
     }
     // Find the index of the account from the master generator, so we can generate the public and private keys.
     RippleAddress       naMasterAccountPublic;
     unsigned int        iIndex  = 0;
     bool                bFound  = false;
     // Don't look at ledger entries to determine if the account exists.  Don't want to leak to thin server that these accounts are
     // related.
     while (!bFound && iIndex != getConfig ().ACCOUNT_PROBE_MAX)
     {
         naMasterAccountPublic.setAccountPublic (naMasterGenerator, iIndex);
         WriteLog (lsDEBUG, RPCHandler) << "authorize: " << iIndex << " : " << naMasterAccountPublic.humanAccountID () << " : " << naSrcAccountID.humanAccountID ();
         bFound  = naSrcAccountID.getAccountID () == naMasterAccountPublic.getAccountID ();
         if (!bFound)
             ++iIndex;
     }
     if (!bFound)
     {
         return rpcError (rpcACT_NOT_FOUND);
     }
     // Use the regular generator to determine the associated public and private keys.
     RippleAddress       naGenerator = RippleAddress::createGeneratorPublic (naRegularSeed);
     naAccountPublic.setAccountPublic (naGenerator, iIndex);
     naAccountPrivate.setAccountPrivate (naGenerator, naRegularSeed, iIndex);
     if (asSrc->haveAuthorizedKey () && (asSrc->getAuthorizedKey ().getAccountID () != naAccountPublic.getAccountID ()))
     {
         // Log::out() << "iIndex: " << iIndex;
         // Log::out() << "sfAuthorizedKey: " << strHex(asSrc->getAuthorizedKey().getAccountID());
         // Log::out() << "naAccountPublic: " << strHex(naAccountPublic.getAccountID());
         return rpcError (rpcPASSWD_CHANGED);
     }
     saSrcBalance    = asSrc->getBalance ();
     if (saSrcBalance < saFee)
     {
         WriteLog (lsINFO, RPCHandler) << "authorize: Insufficient funds for fees: fee=" << saFee.getText () << " balance=" << saSrcBalance.getText ();
         return rpcError (rpcINSUF_FUNDS);
     }
     else
     {
         saSrcBalance -= saFee;
     }
     return Json::Value ();
 }
static void ripple::RPC::autofill_fee (Json::Value & request, Ledger::pointer ledger, Json::Value & result, bool admin) static
Fill in the fee on behalf of the client. This is called when the client does not explicitly specify the fee. The client may also put a ceiling on the amount of the fee. This ceiling is expressed as a multiplier based on the current ledger's fee schedule.
JSON fields
"Fee" The fee paid by the transaction. Omitted when the client wants the fee filled in.
"fee_mult_max" A multiplier applied to the current ledger's transaction fee that caps the maximum the fee server should auto fill. If this optional field is not specified, then a default multiplier is used.
Parameters
tx The JSON corresponding to the transaction to fill in
ledger A ledger for retrieving the current fee schedule
result A JSON object for injecting error results, if any
admin true if this is called by an administrative endpoint.
Definition at line 105 of file TransactionSign.cpp.
References Json::Value::asInt(), ripple::defaultAutoFillFeeMultiplier, expected_field_message(), ripple::getConfig(), inject_error(), Json::Value::isMember(), and ripple::rpcHIGH_FEE.
Referenced by ripple::RPC::JSONRPC_test::testAutoFillFees(), and transactionSign().
 {
     Json::Value& tx (request["tx_json"]);
     if (tx.isMember ("Fee"))
         return;
     int mult (defaultAutoFillFeeMultiplier);
     if (request.isMember ("fee_mult_max"))
     {
         if (request["fee_mult_max"].isNumeric ())
         {
             mult = request["fee_mult_max"].asInt();
         }
         else
         {
             RPC::inject_error (rpcHIGH_FEE, RPC::expected_field_message (
                 "fee_mult_max", "a number"), result);
             return;
         }
     }
     // Administrative endpoints are exempt from local fees
     std::uint64_t fee = ledger->scaleFeeLoad (
         getConfig().FEE_DEFAULT, admin);
     std::uint64_t const limit (mult * getConfig().FEE_DEFAULT);
     if (fee > limit)
     {
         std::stringstream ss;
         ss <<
             "Fee of " << fee <<
             " exceeds the requested tx limit of " << limit;
         RPC::inject_error (rpcHIGH_FEE, ss.str(), result);
         return;
     }
     tx ["Fee"] = (int) fee;
 }
ripple::RPC::BEAST_DEFINE_TESTSUITE (JSONRPC , ripple_app , ripple)
bool ripple::RPC::contains_error (Json::Value const & json)
Returns true if the json contains an rpc error specification.
Definition at line 181 of file ErrorCodes.cpp.
References Json::Value::isMember(), and Json::Value::isObject().
Referenced by ripple::logRPCError(), ripple::RPC::JSONRPC_test::testAutoFillFees(), and transactionSign().
 {
     if (json.isObject() && json.isMember ("error"))
         return true;
     return false;
 }
Json::Value ripple::RPC::expected_field_error (std::string const & name, std::string const & type) inline
Definition at line 197 of file ErrorCodes.h.
References expected_field_message(), and make_param_error().
Referenced by ripple::RPCHandler::doBookOffers(), and ripple::RPCHandler::doLedgerData().
 {
     return make_param_error (expected_field_message (name, type));
 }
std::string ripple::RPC::expected_field_message (std::string const & name, std::string const & type) inline
Definition at line 191 of file ErrorCodes.h.
Referenced by autofill_fee(), and expected_field_error().
 {
     return "Invalid field '" + name + "', not " + type + ".";
 }
ErrorInfo const & ripple::RPC::get_error_info (error_code_i code)
Returns an ErrorInfo that reflects the error code.
Definition at line 145 of file ErrorCodes.cpp.
References ripple::RPC::detail::ErrorCategory::get().
Referenced by inject_error().
 {
     static detail::ErrorCategory category;
     return category.get (code);
 }
Json::Value ripple::RPC::getMasterGenerator (Ledger::ref lrLedger, const RippleAddress & naRegularSeed, RippleAddress & naMasterGenerator, NetworkOPs & netOps)
Definition at line 28 of file GetMasterGenerator.cpp.
References ripple::RippleAddress::accountPrivateDecrypt(), ripple::RippleAddress::createGeneratorPublic(), ripple::RippleAddress::getAccountID(), ripple::NetworkOPs::getGenerator(), Json::objectValue, ripple::rpcError(), ripple::rpcFAIL_GEN_DECRYPT, ripple::rpcNO_ACCOUNT, ripple::RippleAddress::setAccountPrivate(), ripple::RippleAddress::setAccountPublic(), ripple::RippleAddress::setGenerator(), and rocksdb::crc32c::Value().
Referenced by authorize(), and ripple::RPCHandler::doWalletAccounts().
 {
     RippleAddress       na0Public;      // To find the generator's index.
     RippleAddress       na0Private;     // To decrypt the master generator's cipher.
     RippleAddress       naGenerator = RippleAddress::createGeneratorPublic (naRegularSeed);
     na0Public.setAccountPublic (naGenerator, 0);
     na0Private.setAccountPrivate (naGenerator, naRegularSeed, 0);
     SLE::pointer        sleGen          = netOps.getGenerator (lrLedger, na0Public.getAccountID ());
     if (!sleGen)
     {
         // No account has been claimed or has had it password set for seed.
         return rpcError (rpcNO_ACCOUNT);
     }
     Blob    vucCipher           = sleGen->getFieldVL (sfGenerator);
     Blob    vucMasterGenerator  = na0Private.accountPrivateDecrypt (na0Public, vucCipher);
     if (vucMasterGenerator.empty ())
     {
         return rpcError (rpcFAIL_GEN_DECRYPT);
     }
     naMasterGenerator.setGenerator (vucMasterGenerator);
     return Json::Value (Json::objectValue);
 }
void ripple::RPC::inject_error (error_code_i code, Json::Value & json)
Add or update the json update to reflect the error code.
Definition at line 151 of file ErrorCodes.cpp.
References ripple::RPC::ErrorInfo::code, get_error_info(), ripple::RPC::ErrorInfo::message, and ripple::RPC::ErrorInfo::token.
Referenced by autofill_fee(), inject_error(), make_error(), and ripple::rpcError().
 {
     ErrorInfo const& info (get_error_info (code));
     json ["error"] = info.token;
     json ["error_code"] = info.code;
     json ["error_message"] = info.message;
 }
void ripple::RPC::inject_error (int code, Json::Value & json) inline
Definition at line 143 of file ErrorCodes.h.
References inject_error().
     { inject_error (error_code_i (code), json); }
void ripple::RPC::inject_error (error_code_i code, std::string const & message, Json::Value & json)
Definition at line 159 of file ErrorCodes.cpp.
References ripple::RPC::ErrorInfo::code, get_error_info(), and ripple::RPC::ErrorInfo::token.
 {
     ErrorInfo const& info (get_error_info (code));
     json ["error"] = info.token;
     json ["error_code"] = info.code;
     json ["error_message"] = message;
 }
Json::Value ripple::RPC::invalid_field_error (std::string const & name) inline
Definition at line 186 of file ErrorCodes.h.
References make_param_error(), and object_field_message().
Referenced by ripple::RPCHandler::doBookOffers(), ripple::RPCHandler::doProofCreate(), ripple::RPCHandler::doProofSolve(), ripple::RPCHandler::doProofVerify(), and transactionSign().
 {
     return make_param_error (object_field_message (name));
 }
std::string ripple::RPC::invalid_field_message (std::string const & name) inline
Definition at line 181 of file ErrorCodes.h.
Referenced by transactionSign().
 {
     return "Invalid field '" + name + "'.";
 }
Json::Value ripple::RPC::lookupLedger (Json::Value const & params, Ledger::pointer & lpLedger, NetworkOPs & netOps)
Definition at line 43 of file LookupLedger.cpp.
References Json::Value::asInt(), Json::Value::asString(), Json::Value::get(), ripple::getApp(), ripple::LedgerMaster::getClosedLedger(), ripple::NetworkOPs::getCurrentLedger(), ripple::NetworkOPs::getLedgerByHash(), ripple::NetworkOPs::getLedgerBySeq(), ripple::Application::getLedgerMaster(), ripple::NetworkOPs::getValidatedLedger(), Json::Value::isMember(), Json::Value::isNumeric(), Json::Value::isString(), LEDGER_CLOSED, LEDGER_CURRENT, LEDGER_VALIDATED, ripple::base_uint< BITS >::SetHex(), Json::Value::size(), ripple::base_uint< BITS >::ToString(), and rocksdb::crc32c::Value().
Referenced by ripple::RPCHandler::doAccountCurrencies(), ripple::RPCHandler::doAccountInfo(), ripple::RPCHandler::doAccountLines(), ripple::RPCHandler::doAccountOffers(), ripple::RPCHandler::doAccountTx(), ripple::RPCHandler::doAccountTxOld(), ripple::RPCHandler::doBookOffers(), ripple::RPCHandler::doLedger(), ripple::RPCHandler::doLedgerData(), ripple::RPCHandler::doLedgerEntry(), ripple::RPCHandler::doLedgerHeader(), ripple::RPCHandler::doRipplePathFind(), ripple::RPCHandler::doTransactionEntry(), and ripple::RPCHandler::doWalletAccounts().
 {
     Json::Value jvResult;
     Json::Value ledger_hash = params.get ("ledger_hash", Json::Value ("0"));
     Json::Value ledger_index = params.get ("ledger_index", Json::Value ("current"));
     // Support for DEPRECATED "ledger" - attempt to deduce our input
     if (params.isMember ("ledger"))
     {
         if (params["ledger"].asString ().size () > 12)
         {
             ledger_hash = params["ledger"];
             ledger_index = Json::Value ("");
         }
         else if (params["ledger"].isNumeric ())
         {
             ledger_index = params["ledger"];
             ledger_hash = Json::Value ("0");
         }
         else
         {
             ledger_index = params["ledger"];
             ledger_hash = Json::Value ("0");
         }
     }
     uint256 uLedger (0);
     if (!ledger_hash.isString() || !uLedger.SetHex (ledger_hash.asString ()))
     {
         jvResult["error"] = "ledgerHashMalformed";
         return jvResult;
     }
     std::int32_t iLedgerIndex = LEDGER_CURRENT;
     // We only try to parse a ledger index if we have not already
     // determined that we have a ledger hash.
     if (!uLedger)
     {
         if (ledger_index.isNumeric ())
             iLedgerIndex = ledger_index.asInt ();
         else
         {
             std::string strLedger = ledger_index.asString ();
             if (strLedger == "current")
             {
                 iLedgerIndex = LEDGER_CURRENT;
             }
             else if (strLedger == "closed")
             {
                 iLedgerIndex = LEDGER_CLOSED;
             }
             else if (strLedger == "validated")
             {
                 iLedgerIndex = LEDGER_VALIDATED;
             }
             else
             {
                 jvResult["error"] = "ledgerIndexMalformed";
                 return jvResult;
             }
         }
     }
     // The ledger was directly specified by hash.
     if (!!uLedger)
     {
         lpLedger = netOps.getLedgerByHash (uLedger);
         if (!lpLedger)
         {
             jvResult["error"] = "ledgerNotFound";
             return jvResult;
         }
         iLedgerIndex = lpLedger->getLedgerSeq ();
     }
     switch (iLedgerIndex)
     {
     case LEDGER_CURRENT:
         lpLedger = netOps.getCurrentLedger ();
         iLedgerIndex = lpLedger->getLedgerSeq ();
         assert (lpLedger->isImmutable () && !lpLedger->isClosed ());
         break;
     case LEDGER_CLOSED:
         lpLedger = getApp().getLedgerMaster ().getClosedLedger ();
         iLedgerIndex = lpLedger->getLedgerSeq ();
         assert (lpLedger->isImmutable () && lpLedger->isClosed ());
         break;
     case LEDGER_VALIDATED:
         lpLedger = netOps.getValidatedLedger ();
         iLedgerIndex = lpLedger->getLedgerSeq ();
         assert (lpLedger->isImmutable () && lpLedger->isClosed ());
         break;
     }
     if (iLedgerIndex <= 0)
     {
         jvResult["error"] = "ledgerIndexMalformed";
         return jvResult;
     }
     if (!lpLedger)
     {
         lpLedger = netOps.getLedgerBySeq (iLedgerIndex);
         if (!lpLedger)
         {
             jvResult["error"] = "ledgerNotFound"; // ledger_index from future?
             return jvResult;
         }
     }
     if (lpLedger->isClosed ())
     {
         if (!!uLedger)
             jvResult["ledger_hash"] = uLedger.ToString ();
         jvResult["ledger_index"] = iLedgerIndex;
     }
     else
     {
         // CHECKME - What is this supposed to signify?
         jvResult["ledger_current_index"] = iLedgerIndex;
     }
     return jvResult;
 }
Json::Value ripple::RPC::make_error (error_code_i code)
Returns a new json object that reflects the error code.
Definition at line 167 of file ErrorCodes.cpp.
References inject_error().
Referenced by ripple::STParsedJSON::array_expected(), ripple::STParsedJSON::bad_type(), ripple::RPCHandler::doBookOffers(), ripple::STParsedJSON::invalid_data(), make_param_error(), ripple::STParsedJSON::not_an_object(), ripple::STParsedJSON::out_of_range(), ripple::STParsedJSON::singleton_expected(), ripple::STParsedJSON::string_expected(), ripple::STParsedJSON::too_deep(), transactionSign(), and ripple::STParsedJSON::unknown_field().
 {
     Json::Value json;
     inject_error (code, json);
     return json;
 }
Json::Value ripple::RPC::make_error (error_code_i code, std::string const & message)
Definition at line 174 of file ErrorCodes.cpp.
References inject_error().
 {
     Json::Value json;
     inject_error (code, message, json);
     return json;
 }
std::unique_ptr< Manager > ripple::RPC::make_Manager (beast::Journal journal)
Definition at line 64 of file Manager.cpp.
References ripple::RPC::Manager::add().
 {
     std::unique_ptr <Manager> m (std::make_unique <ManagerImp> (journal));
     m->add <DoPrint> ("print");
     return m;
 }
Json::Value ripple::RPC::make_param_error (std::string const & message) inline
Returns a new json object that indicates invalid parameters.
Definition at line 156 of file ErrorCodes.h.
References make_error(), and ripple::rpcINVALID_PARAMS.
Referenced by expected_field_error(), invalid_field_error(), ripple::RPCParser::jvParseCurrencyIssuer(), missing_field_error(), and object_field_error().
 {
     return make_error (rpcINVALID_PARAMS, message);
 }
Json::Value ripple::RPC::missing_field_error (std::string const & name) inline
Definition at line 166 of file ErrorCodes.h.
References make_param_error(), and missing_field_message().
Referenced by ripple::RPCHandler::doAccountCurrencies(), ripple::RPCHandler::doAccountInfo(), ripple::RPCHandler::doAccountLines(), ripple::RPCHandler::doAccountOffers(), ripple::RPCHandler::doBookOffers(), ripple::RPCHandler::doConnect(), ripple::RPCHandler::doOwnerInfo(), ripple::RPCHandler::doProofSolve(), ripple::RPCHandler::doProofVerify(), and transactionSign().
 {
     return make_param_error (missing_field_message (name));
 }
std::string ripple::RPC::missing_field_message (std::string const & name) inline
Definition at line 161 of file ErrorCodes.h.
Referenced by missing_field_error(), and transactionSign().
 {
     return "Missing field '" + name + "'.";
 }
Json::Value ripple::RPC::object_field_error (std::string const & name) inline
Definition at line 176 of file ErrorCodes.h.
References make_param_error(), and object_field_message().
Referenced by ripple::RPCHandler::doBookOffers(), and transactionSign().
 {
     return make_param_error (object_field_message (name));
 }
std::string ripple::RPC::object_field_message (std::string const & name) inline
Definition at line 171 of file ErrorCodes.h.
Referenced by invalid_field_error(), and object_field_error().
 {
     return "Invalid field '" + name + "', not object.";
 }
boost::unordered_set< RippleAddress > ripple::RPC::parseAccountIds (const Json::Value & jvArray)
Definition at line 25 of file ParseAccountIds.cpp.
References Json::Value::begin(), ripple::RippleAddress::clear(), Json::Value::end(), and ripple::RippleAddress::setAccountID().
Referenced by ripple::RPCHandler::doSubscribe(), and ripple::RPCHandler::doUnsubscribe().
 {
     boost::unordered_set<RippleAddress> usnaResult;
     for (Json::Value::const_iterator it = jvArray.begin (); it != jvArray.end (); it++)
     {
         RippleAddress   naString;
         if (! (*it).isString () || !naString.setAccountID ((*it).asString ()))
         {
             usnaResult.clear ();
             break;
         }
         else
         {
             (void) usnaResult.insert (naString);
         }
     }
     return usnaResult;
 }
Json::Value ripple::RPC::transactionSign (Json::Value params, bool bSubmit, bool bFailHard, Application::ScopedLockType & mlh, NetworkOPs & netOps, int role)
Definition at line 152 of file TransactionSign.cpp.
References ripple::Config::ADMIN, Json::Value::asBool(), Json::Value::asString(), autofill_fee(), ripple::STAmount::bSetJson(), contains_error(), ripple::RippleAddress::createAccountPrivate(), ripple::RippleAddress::createAccountPublic(), ripple::RippleAddress::createGeneratorPublic(), ripple::RippleAddress::createSeedGeneric(), ripple::STParsedJSON::error, ripple::Config::FEE_DEFAULT, ripple::RippleAddress::getAccountID(), ripple::RippleAddress::getAccountPublic(), ripple::Ledger::getAccountRootIndex(), ripple::NetworkOPs::getAccountState(), ripple::getApp(), ripple::getConfig(), ripple::STAmount::getCurrency(), ripple::NetworkOPs::getCurrentLedger(), ripple::STAmount::getIssuer(), ripple::STPathSet::getJson(), ripple::Application::getLedgerMaster(), ripple::NetworkOPs::getSLEi(), ripple::LedgerMaster::getValidatedLedgerAge(), ripple::RippleAddress::humanAccountID(), invalid_field_error(), invalid_field_message(), ripple::STPathSet::isEmpty(), Json::Value::isMember(), ripple::STAmount::isNative(), Json::Value::isObject(), ripple::RPC::LegacyPathFind::isOkay(), ripple::lsDEBUG, ripple::lsfDisableMaster, ripple::lsWARNING, make_error(), missing_field_error(), missing_field_message(), ripple::STParsedJSON::object, object_field_error(), ripple::passesLocalChecks(), ripple::rpcBAD_SECRET, ripple::rpcBAD_SEED, ripple::rpcError(), ripple::rpcINTERNAL, ripple::rpcINVALID_PARAMS, ripple::rpcMASTER_DISABLED, ripple::rpcNO_CURRENT, ripple::rpcNO_PATH, ripple::rpcSRC_ACT_MALFORMED, ripple::rpcSRC_ACT_MISSING, ripple::rpcSRC_ACT_NOT_FOUND, ripple::rpcTOO_BUSY, ripple::Config::RUN_STANDALONE, ripple::RippleAddress::setAccountID(), ripple::STAmount::setIssuer(), ripple::RippleAddress::setSeedGeneric(), ripple::strHex(), ripple::NetworkOPs::submitTransactionSync(), ripple::temUNCERTAIN, ripple::tfFullyCanonicalSig, ripple::transResultInfo(), and WriteLog.
Referenced by ripple::RPCHandler::doSign(), and ripple::RPCHandler::doSubmit().
 {
     Json::Value jvResult;
     WriteLog (lsDEBUG, RPCHandler) << boost::str (boost::format ("transactionSign: %s") % params);
     if (! params.isMember ("secret"))
         return RPC::missing_field_error ("secret");
     if (! params.isMember ("tx_json"))
         return RPC::missing_field_error ("tx_json");
     RippleAddress naSeed;
     if (! naSeed.setSeedGeneric (params["secret"].asString ()))
         return RPC::make_error (rpcBAD_SEED,
             RPC::invalid_field_message ("secret"));
     Json::Value& tx_json (params ["tx_json"]);
     if (! tx_json.isObject ())
         return RPC::object_field_error ("tx_json");
     if (! tx_json.isMember ("TransactionType"))
         return RPC::missing_field_error ("tx_json.TransactionType");
     std::string const sType = tx_json ["TransactionType"].asString ();
     if (! tx_json.isMember ("Account"))
         return RPC::make_error (rpcSRC_ACT_MISSING,
             RPC::missing_field_message ("tx_json.Account"));
     RippleAddress raSrcAddressID;
     if (! raSrcAddressID.setAccountID (tx_json["Account"].asString ()))
         return RPC::make_error (rpcSRC_ACT_MALFORMED,
             RPC::invalid_field_message ("tx_json.Account"));
     bool const verify = !(
         params.isMember ("offline") && params["offline"].asBool ());
     if (!tx_json.isMember ("Sequence") && !verify)
         return RPC::missing_field_error ("tx_json.Sequence");
     // Check for current ledger
     if (verify && !getConfig ().RUN_STANDALONE &&
         (getApp().getLedgerMaster().getValidatedLedgerAge() > 120))
         return rpcError (rpcNO_CURRENT);
     // Check for load
     if (getApp().getFeeTrack().isLoadedCluster() && (role != Config::ADMIN))
         return rpcError(rpcTOO_BUSY);
     Ledger::pointer lSnapshot = netOps.getCurrentLedger ();
     AccountState::pointer asSrc = !verify
                                   ? AccountState::pointer ()                              // Don't look up address if offline.
                                   : netOps.getAccountState (lSnapshot, raSrcAddressID);
     if (verify && !asSrc)
     {
         // If not offline and did not find account, error.
         WriteLog (lsDEBUG, RPCHandler) << boost::str (boost::format ("transactionSign: Failed to find source account in current ledger: %s")
                                        % raSrcAddressID.humanAccountID ());
         return rpcError (rpcSRC_ACT_NOT_FOUND);
     }
     autofill_fee (params, lSnapshot, jvResult, role == Config::ADMIN);
     if (RPC::contains_error (jvResult))
         return jvResult;
     if ("Payment" == sType)
     {
         RippleAddress dstAccountID;
         if (! tx_json.isMember ("Amount"))
             return RPC::missing_field_error ("tx_json.Amount");
         STAmount amount;
         if (! amount.bSetJson (tx_json ["Amount"]))
             return RPC::invalid_field_error ("tx_json.Amount");
         if (!tx_json.isMember ("Destination"))
             return RPC::missing_field_error ("tx_json.Destination");
         if (!dstAccountID.setAccountID (tx_json["Destination"].asString ()))
             return RPC::invalid_field_error ("tx_json.Destination");
         if (tx_json.isMember ("Paths") && params.isMember ("build_path"))
             return RPC::make_error (rpcINVALID_PARAMS,
                 "Cannot specify both 'tx_json.Paths' and 'tx_json.build_path'");
         if (!tx_json.isMember ("Paths") && tx_json.isMember ("Amount") && params.isMember ("build_path"))
         {
             // Need a ripple path.
             STPathSet   spsPaths;
             uint160     uSrcCurrencyID;
             uint160     uSrcIssuerID;
             STAmount    saSendMax;
             if (tx_json.isMember ("SendMax"))
             {
                 if (!saSendMax.bSetJson (tx_json ["SendMax"]))
                     return RPC::invalid_field_error ("tx_json.SendMax");
             }
             else
             {
                 // If no SendMax, default to Amount with sender as issuer.
                 saSendMax       = amount;
                 saSendMax.setIssuer (raSrcAddressID.getAccountID ());
             }
             if (saSendMax.isNative () && amount.isNative ())
                 return RPC::make_error (rpcINVALID_PARAMS,
                     "Cannot build XRP to XRP paths.");
             {
                 LegacyPathFind lpf (role == Config::ADMIN);
                 if (!lpf.isOkay ())
                     return rpcError (rpcTOO_BUSY);
                 bool bValid;
                 RippleLineCache::pointer cache = boost::make_shared<RippleLineCache> (lSnapshot);
                 Pathfinder pf (cache, raSrcAddressID, dstAccountID,
                                saSendMax.getCurrency (), saSendMax.getIssuer (), amount, bValid);
                 STPath extraPath;
                 if (!bValid || !pf.findPaths (getConfig ().PATH_SEARCH_OLD, 4, spsPaths, extraPath))
                 {
                     WriteLog (lsDEBUG, RPCHandler) << "transactionSign: build_path: No paths found.";
                     return rpcError (rpcNO_PATH);
                 }
                 else
                 {
                     WriteLog (lsDEBUG, RPCHandler) << "transactionSign: build_path: " << spsPaths.getJson (0);
                 }
                 if (!spsPaths.isEmpty ())
                 {
                     tx_json["Paths"] = spsPaths.getJson (0);
                 }
             }
         }
     }
     if (!tx_json.isMember ("Fee")
             && (
                 "AccountSet" == tx_json["TransactionType"].asString ()
                 || "OfferCreate" == tx_json["TransactionType"].asString ()
                 || "OfferCancel" == tx_json["TransactionType"].asString ()
                 || "TrustSet" == tx_json["TransactionType"].asString ()))
     {
         tx_json["Fee"] = (int) getConfig ().FEE_DEFAULT;
     }
     if (!tx_json.isMember ("Sequence"))
     {
         if (!verify)
         {
             // If offline, Sequence is mandatory.
             // TODO: duplicates logic above.
             return rpcError (rpcINVALID_PARAMS);
         }
         else
         {
             tx_json["Sequence"] = asSrc->getSeq ();
         }
     }
     if (!tx_json.isMember ("Flags")) tx_json["Flags"] = tfFullyCanonicalSig;
     if (verify)
     {
         SLE::pointer sleAccountRoot = netOps.getSLEi (lSnapshot,
             Ledger::getAccountRootIndex (raSrcAddressID.getAccountID ()));
         if (!sleAccountRoot)
         {
             // XXX Ignore transactions for accounts not created.
             return rpcError (rpcSRC_ACT_NOT_FOUND);
         }
     }
     bool            bHaveAuthKey    = false;
     RippleAddress   naAuthorizedPublic;
     RippleAddress   naSecret = RippleAddress::createSeedGeneric (
         params["secret"].asString ());
     RippleAddress   naMasterGenerator = RippleAddress::createGeneratorPublic (
         naSecret);
     if (verify)
     {
         auto masterAccountPublic = RippleAddress::createAccountPublic (
             naMasterGenerator, 0);
         auto account = masterAccountPublic.getAccountID();
         auto const& sle = asSrc->peekSLE();
         WriteLog (lsWARNING, RPCHandler) <<
                 "verify: " << masterAccountPublic.humanAccountID () <<
                 " : " << raSrcAddressID.humanAccountID ();
         if (raSrcAddressID.getAccountID () == account)
         {
             if (sle.isFlag(lsfDisableMaster))
                 return rpcError (rpcMASTER_DISABLED);
         }
         else if (!sle.isFieldPresent(sfRegularKey) ||
                  account != sle.getFieldAccount160 (sfRegularKey))
         {
             return rpcError (rpcBAD_SECRET);
         }
     }
     // Use the generator to determine the associated public and private keys.
     RippleAddress naGenerator = RippleAddress::createGeneratorPublic (
         naSecret);
     RippleAddress naAccountPublic = RippleAddress::createAccountPublic (
         naGenerator, 0);
     RippleAddress naAccountPrivate = RippleAddress::createAccountPrivate (
         naGenerator, naSecret, 0);
     if (bHaveAuthKey
             // The generated pair must match authorized...
             && naAuthorizedPublic.getAccountID () != naAccountPublic.getAccountID ()
             // ... or the master key must have been used.
             && raSrcAddressID.getAccountID () != naAccountPublic.getAccountID ())
     {
         // TODO: we can't ever get here!
         // Log::out() << "iIndex: " << iIndex;
         // Log::out() << "sfAuthorizedKey: " << strHex(asSrc->getAuthorizedKey().getAccountID());
         // Log::out() << "naAccountPublic: " << strHex(naAccountPublic.getAccountID());
         return rpcError (rpcSRC_ACT_NOT_FOUND);
     }
     std::unique_ptr<STObject> sopTrans;
     {
         STParsedJSON parsed ("tx_json", tx_json);
         if (parsed.object.get() != nullptr)
         {
             // VFALCO NOTE No idea why this doesn't compile.
             //sopTrans = parsed.object;
             sopTrans.reset (parsed.object.release());
         }
         else
         {
             jvResult ["error"] = parsed.error ["error"];
             jvResult ["error_code"] = parsed.error ["error_code"];
             jvResult ["error_message"] = parsed.error ["error_message"];
             return jvResult;
         }
     }
     sopTrans->setFieldVL (sfSigningPubKey, naAccountPublic.getAccountPublic ());
     SerializedTransaction::pointer stpTrans;
     try
     {
         stpTrans = boost::make_shared<SerializedTransaction> (*sopTrans);
     }
     catch (std::exception&)
     {
         return RPC::make_error (rpcINTERNAL,
             "Exception occurred during transaction");
     }
     std::string reason;
     if (!passesLocalChecks (*stpTrans, reason))
     {
         return RPC::make_error (rpcINVALID_PARAMS,
             reason);
     }
     if (params.isMember ("debug_signing"))
     {
         jvResult["tx_unsigned"] = strHex (
             stpTrans->getSerializer ().peekData ());
         jvResult["tx_signing_hash"] = stpTrans->getSigningHash ().ToString ();
     }
     // FIXME: For performance, transactions should not be signed in this code path.
     stpTrans->sign (naAccountPrivate);
     Transaction::pointer tpTrans;
     try
     {
         tpTrans     = boost::make_shared<Transaction> (stpTrans, false);
     }
     catch (std::exception&)
     {
         return RPC::make_error (rpcINTERNAL,
             "Exception occurred during transaction");
     }
     try
     {
         // FIXME: For performance, should use asynch interface
         tpTrans = netOps.submitTransactionSync (tpTrans,
             role == Config::ADMIN, true, bFailHard, bSubmit);
         if (!tpTrans)
         {
             return RPC::make_error (rpcINTERNAL,
                 "Unable to sterilize transaction.");
         }
     }
     catch (std::exception&)
     {
         return RPC::make_error (rpcINTERNAL,
             "Exception occurred during transaction submission.");
     }
     try
     {
         jvResult["tx_json"] = tpTrans->getJson (0);
         jvResult["tx_blob"] = strHex (
             tpTrans->getSTransaction ()->getSerializer ().peekData ());
         if (temUNCERTAIN != tpTrans->getResult ())
         {
             std::string sToken;
             std::string sHuman;
             transResultInfo (tpTrans->getResult (), sToken, sHuman);
             jvResult["engine_result"]           = sToken;
             jvResult["engine_result_code"]      = tpTrans->getResult ();
             jvResult["engine_result_message"]   = sHuman;
         }
         return jvResult;
     }
     catch (std::exception&)
     {
         return RPC::make_error (rpcINTERNAL,
             "Exception occurred during JSON handling.");
     }
 }
Variable Documentation
const int ripple::RPC::LEDGER_CLOSED = -2 static
Definition at line 26 of file LookupLedger.cpp.
Referenced by lookupLedger().
const int ripple::RPC::LEDGER_CURRENT = -1 static
Definition at line 25 of file LookupLedger.cpp.
Referenced by lookupLedger().
const int ripple::RPC::LEDGER_VALIDATED = -3 static
Definition at line 27 of file LookupLedger.cpp.
Referenced by lookupLedger().