rippled: beast::Zero_test Class Reference
beast::Zero_test Class Reference
Classes
struct IntegerWrapper
Public Member Functions
void expect_same (bool result, bool correct, char const *message)
void test_lhs_zero (IntegerWrapper x)
void test_lhs_zero ()
void test_rhs_zero (IntegerWrapper x)
void test_rhs_zero ()
void test_adl ()
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 45 of file Zero.test.cpp.
Member Function Documentation
void beast::Zero_test::expect_same (bool result, bool correct, char const * message) inline
Definition at line 64 of file Zero.test.cpp.
References beast::unit_test::suite::expect().
Referenced by test_lhs_zero(), and test_rhs_zero().
     {
         expect(result == correct, message);
     }
void beast::Zero_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 131 of file Zero.test.cpp.
References test_adl(), test_lhs_zero(), and test_rhs_zero().
     {
         test_lhs_zero ();
         test_rhs_zero ();
         test_adl ();
     }
void beast::Zero_test::test_adl () inline
Definition at line 124 of file Zero.test.cpp.
References beast::unit_test::suite::expect().
Referenced by run().
     {
       expect (adl_tester{} == zero, "ADL failure!");
       expect (detail::adl_tester2{} == zero, "ADL failure!");
     }
void beast::Zero_test::test_lhs_zero (IntegerWrapper x) inline
Definition at line 70 of file Zero.test.cpp.
References expect_same(), and beast::Zero_test::IntegerWrapper::signum().
     {
         expect_same (x >= zero, x.signum () >= 0,
             "lhs greater-than-or-equal-to");
         expect_same (x > zero, x.signum () > 0,
             "lhs greater than");
         expect_same (x == zero, x.signum () == 0,
             "lhs equal to");
         expect_same (x != zero, x.signum () != 0,
             "lhs not equal to");
         expect_same (x < zero, x.signum () < 0,
             "lhs less than");
         expect_same (x <= zero, x.signum () <= 0,
             "lhs less-than-or-equal-to");
     }
void beast::Zero_test::test_lhs_zero () inline
Definition at line 87 of file Zero.test.cpp.
References beast::unit_test::suite::testcase().
Referenced by run().
     {
         testcase ("lhs zero");
         test_lhs_zero(-7);
         test_lhs_zero(0);
         test_lhs_zero(32);
     }
void beast::Zero_test::test_rhs_zero (IntegerWrapper x) inline
Definition at line 97 of file Zero.test.cpp.
References expect_same(), and beast::Zero_test::IntegerWrapper::signum().
     {
         expect_same (zero >= x, 0 >= x.signum (),
             "rhs greater-than-or-equal-to");
         expect_same (zero > x, 0 > x.signum (),
             "rhs greater than");
         expect_same (zero == x, 0 == x.signum (),
             "rhs equal to");
         expect_same (zero != x, 0 != x.signum (),
             "rhs not equal to");
         expect_same (zero < x, 0 < x.signum (),
             "rhs less than");
         expect_same (zero <= x, 0 <= x.signum (),
             "rhs less-than-or-equal-to");
     }
void beast::Zero_test::test_rhs_zero () inline
Definition at line 114 of file Zero.test.cpp.
References beast::unit_test::suite::testcase().
Referenced by run().
     {
         testcase ("rhs zero");
         test_rhs_zero(-4);
         test_rhs_zero(0);
         test_rhs_zero(64);
     }
The documentation for this class was generated from the following file:
rippled/src/beast/beast/utility/tests/Zero.test.cpp