rippled: ripple::LoadEvent Class Reference
ripple::LoadEvent Class Reference
#include <LoadEvent.h>
Public Types
typedef boost::shared_ptr
< LoadEvent > pointer
typedef std::unique_ptr
< LoadEvent > autoptr
Public Member Functions
LoadEvent (LoadMonitor &monitor, const std::string &name, bool shouldStart)
~LoadEvent ()
std::string const & name () const
double getSecondsWaiting () const
double getSecondsRunning () const
double getSecondsTotal () const
void reName (const std::string &name)
void start ()
void stop ()
Private Attributes
LoadMonitor & m_loadMonitor
bool m_isRunning
std::string m_name
beast::RelativeTime m_timeStopped
beast::RelativeTime m_timeStarted
double m_secondsWaiting
double m_secondsRunning
Detailed Description
Definition at line 34 of file LoadEvent.h.
Member Typedef Documentation
typedef std::unique_ptr<LoadEvent> ripple::LoadEvent::autoptr
Definition at line 44 of file LoadEvent.h.
typedef boost::shared_ptr<LoadEvent> ripple::LoadEvent::pointer
Definition at line 43 of file LoadEvent.h.
Constructor & Destructor Documentation
ripple::LoadEvent::LoadEvent (LoadMonitor & monitor, const std::string & name, bool shouldStart)
Definition at line 22 of file LoadEvent.cpp.
References start().
     : m_loadMonitor (monitor)
     , m_isRunning (false)
     , m_name (name)
     , m_timeStopped (beast::RelativeTime::fromStartup())
     , m_secondsWaiting (0)
     , m_secondsRunning (0)
 {
     if (shouldStart)
         start ();
 }
ripple::LoadEvent::~LoadEvent ()
Definition at line 34 of file LoadEvent.cpp.
References m_isRunning, and stop().
 {
     if (m_isRunning)
         stop ();
 }
Member Function Documentation
double ripple::LoadEvent::getSecondsRunning () const
Definition at line 50 of file LoadEvent.cpp.
References m_secondsRunning.
Referenced by ripple::LoadMonitor::addLoadSample().
 {
     return m_secondsRunning;
 }
double ripple::LoadEvent::getSecondsTotal () const
Definition at line 55 of file LoadEvent.cpp.
References m_secondsRunning, and m_secondsWaiting.
Referenced by ripple::LoadMonitor::addLoadSample().
 {
     return m_secondsWaiting + m_secondsRunning;
 }
double ripple::LoadEvent::getSecondsWaiting () const
Definition at line 45 of file LoadEvent.cpp.
References m_secondsWaiting.
Referenced by ripple::LoadMonitor::addLoadSample().
 {
     return m_secondsWaiting;
 }
std::string const & ripple::LoadEvent::name () const
Definition at line 40 of file LoadEvent.cpp.
References m_name.
Referenced by ripple::LoadMonitor::addLoadSample(), and reName().
 {
     return m_name;
 }
void ripple::LoadEvent::reName (const std::string & name)
Definition at line 60 of file LoadEvent.cpp.
References m_name, and name().
 {
     m_name = name;
 }
void ripple::LoadEvent::start ()
Definition at line 65 of file LoadEvent.cpp.
References beast::RelativeTime::fromStartup(), m_isRunning, m_secondsWaiting, m_timeStarted, and m_timeStopped.
Referenced by LoadEvent().
 {
     beast::RelativeTime const currentTime (beast::RelativeTime::fromStartup());
     // If we already called start, this call will replace the previous one.
     if (m_isRunning)
     {
         m_secondsWaiting += (currentTime - m_timeStarted).inSeconds();
     }
     else
     {
         m_secondsWaiting += (currentTime - m_timeStopped).inSeconds();
         m_isRunning = true;
     }
     m_timeStarted = currentTime;
 }
void ripple::LoadEvent::stop (void)
Definition at line 83 of file LoadEvent.cpp.
References ripple::LoadMonitor::addLoadSample(), bassert, beast::RelativeTime::fromStartup(), m_isRunning, m_loadMonitor, m_secondsRunning, m_timeStarted, and m_timeStopped.
Referenced by ~LoadEvent().
 {
     bassert (m_isRunning);
     m_timeStopped = beast::RelativeTime::fromStartup();
     m_secondsRunning += (m_timeStopped - m_timeStarted).inSeconds();
     m_isRunning = false;
     m_loadMonitor.addLoadSample (*this);
 }
Member Data Documentation
bool ripple::LoadEvent::m_isRunning private
Definition at line 75 of file LoadEvent.h.
Referenced by start(), stop(), and ~LoadEvent().
LoadMonitor& ripple::LoadEvent::m_loadMonitor private
Definition at line 74 of file LoadEvent.h.
Referenced by stop().
std::string ripple::LoadEvent::m_name private
Definition at line 76 of file LoadEvent.h.
Referenced by name(), and reName().
double ripple::LoadEvent::m_secondsRunning private
Definition at line 81 of file LoadEvent.h.
Referenced by getSecondsRunning(), getSecondsTotal(), and stop().
double ripple::LoadEvent::m_secondsWaiting private
Definition at line 80 of file LoadEvent.h.
Referenced by getSecondsTotal(), getSecondsWaiting(), and start().
beast::RelativeTime ripple::LoadEvent::m_timeStarted private
Definition at line 79 of file LoadEvent.h.
Referenced by start(), and stop().
beast::RelativeTime ripple::LoadEvent::m_timeStopped private
Definition at line 78 of file LoadEvent.h.
Referenced by start(), and stop().
The documentation for this class was generated from the following files:
rippled/src/ripple_core/functional/LoadEvent.h
rippled/src/ripple_core/functional/LoadEvent.cpp