rippled: ripple::RegularKeySetTransactor Class Reference
ripple::RegularKeySetTransactor Class Reference
#include <RegularKeySetTransactor.h>
Public Member Functions
RegularKeySetTransactor (SerializedTransaction const &txn, TransactionEngineParams params, TransactionEngine *engine)
TER checkFee ()
TER doApply ()
Public Member Functions inherited from ripple::Transactor
TER apply ()
Private Member Functions
std::uint64_t calculateBaseFee ()
Additional Inherited Members
Static Public Member Functions inherited from ripple::Transactor
static std::unique_ptr
< Transactor > makeTransactor (SerializedTransaction const &txn, TransactionEngineParams params, TransactionEngine *engine)
Protected Member Functions inherited from ripple::Transactor
virtual TER preCheck ()
virtual TER checkSeq ()
virtual TER payFee ()
void calculateFee ()
virtual TER checkSig ()
Transactor (const SerializedTransaction &txn, TransactionEngineParams params, TransactionEngine *engine, beast::Journal journal=beast::Journal())
virtual bool mustHaveValidAccount ()
Protected Attributes inherited from ripple::Transactor
SerializedTransaction const & mTxn
TransactionEngine * mEngine
TransactionEngineParams mParams
uint160 mTxnAccountID
STAmount mFeeDue
STAmount mPriorBalance
STAmount mSourceBalance
SLE::pointer mTxnAccount
bool mHasAuthKey
bool mSigMaster
RippleAddress mSigningPubKey
beast::Journal m_journal
Detailed Description
Definition at line 34 of file RegularKeySetTransactor.h.
Constructor & Destructor Documentation
ripple::RegularKeySetTransactor::RegularKeySetTransactor (SerializedTransaction const & txn, TransactionEngineParams params, TransactionEngine * engine) inline
Definition at line 40 of file RegularKeySetTransactor.h.
         : Transactor (
             txn,
             params,
             engine,
             LogPartition::getJournal <RegularKeySetTransactorLog> ())
     {
     }
Member Function Documentation
std::uint64_t ripple::RegularKeySetTransactor::calculateBaseFee () private virtual
Reimplemented from ripple::Transactor.
Definition at line 22 of file RegularKeySetTransactor.cpp.
References ripple::Transactor::calculateBaseFee(), ripple::RippleAddress::getAccountID(), ripple::lsfPasswordSpent, ripple::Transactor::mSigningPubKey, ripple::Transactor::mTxnAccount, and ripple::Transactor::mTxnAccountID.
 {
     if ( mTxnAccount
             && (! (mTxnAccount->getFlags () & lsfPasswordSpent))
             && (mSigningPubKey.getAccountID () == mTxnAccountID))
     {
         // flag is armed and they signed with the right account
         return 0;
     }
     return Transactor::calculateBaseFee ();
 }
TER ripple::RegularKeySetTransactor::checkFee ()
TER ripple::RegularKeySetTransactor::doApply () virtual
Implements ripple::Transactor.
Definition at line 36 of file RegularKeySetTransactor.cpp.
References ripple::STObject::getFieldAccount160(), ripple::STObject::getFlags(), ripple::STObject::isFieldPresent(), ripple::lsfDisableMaster, ripple::lsfPasswordSpent, ripple::Transactor::m_journal, ripple::Transactor::mFeeDue, ripple::Transactor::mTxn, ripple::Transactor::mTxnAccount, ripple::tecMASTER_DISABLED, ripple::temINVALID_FLAG, ripple::tesSUCCESS, ripple::tfUniversalMask, and beast::Journal::trace.
 {
     std::uint32_t const uTxFlags = mTxn.getFlags ();
     if (uTxFlags & tfUniversalMask)
     {
         m_journal.trace <<
             "Malformed transaction: Invalid flags set.";
         return temINVALID_FLAG;
     }
     if (mFeeDue == zero)
     {
         mTxnAccount->setFlag (lsfPasswordSpent);
     }
     if (mTxn.isFieldPresent (sfRegularKey))
     {
         uint160 uAuthKeyID = mTxn.getFieldAccount160 (sfRegularKey);
         mTxnAccount->setFieldAccount (sfRegularKey, uAuthKeyID);
     }
     else
     {
         if (mTxnAccount->isFlag (lsfDisableMaster))
             return tecMASTER_DISABLED;
         mTxnAccount->makeFieldAbsent (sfRegularKey);
     }
     return tesSUCCESS;
 }
The documentation for this class was generated from the following files:
rippled/src/ripple_app/transactors/RegularKeySetTransactor.h
rippled/src/ripple_app/transactors/RegularKeySetTransactor.cpp