rippled: rocksdb::StringAppendTESTOperator Class Reference
rocksdb::StringAppendTESTOperator Class Reference
#include <stringappend2.h>
Public Member Functions
StringAppendTESTOperator (char delim_char)
virtual bool FullMerge (const Slice &key, const Slice *existing_value, const std::deque< std::string > &operand_sequence, std::string *new_value, Logger *logger) const override
Constructor with delimiter.
virtual bool PartialMerge (const Slice &key, const Slice &left_operand, const Slice &right_operand, std::string *new_value, Logger *logger) const override
virtual const char * Name () const override
Public Member Functions inherited from rocksdb::MergeOperator
virtual ~MergeOperator ()
Private Member Functions
bool _AssocPartialMerge (const Slice &key, const Slice &left_operand, const Slice &right_operand, std::string *new_value, Logger *logger) const
Private Attributes
char delim_
Detailed Description
Definition at line 19 of file stringappend2.h.
Constructor & Destructor Documentation
rocksdb::StringAppendTESTOperator::StringAppendTESTOperator (char delim_char)
Definition at line 18 of file stringappend2.cc.
     : delim_(delim_char) {
 }
Member Function Documentation
bool rocksdb::StringAppendTESTOperator::_AssocPartialMerge (const Slice & key, const Slice & left_operand, const Slice & right_operand, std::string * new_value, Logger * logger) const private
Definition at line 74 of file stringappend2.cc.
References rocksdb::Slice::data(), delim_, and rocksdb::Slice::size().
{
   // Clear the *new_value for writing.
   assert(new_value);
   new_value->clear();
   // Generic append
   // Reserve correct size for *new_value, and apply concatenation.
   new_value->reserve(left_operand.size() + 1 + right_operand.size());
   new_value->assign(left_operand.data(), left_operand.size());
   new_value->append(1,delim_);
   new_value->append(right_operand.data(), right_operand.size());
   return true;
 }
bool rocksdb::StringAppendTESTOperator::FullMerge (const Slice & key, const Slice * existing_value, const std::deque< std::string > & operand_sequence, std::string * new_value, Logger * logger) const override virtual
Constructor with delimiter.
Implements rocksdb::MergeOperator.
Definition at line 23 of file stringappend2.cc.
References rocksdb::Slice::data(), delim_, and rocksdb::Slice::size().
{
   // Clear the *new_value for writing.
   assert(new_value);
   new_value->clear();
   // Compute the space needed for the final result.
   int numBytes = 0;
   for(auto it = operands.begin(); it != operands.end(); ++it) {
     numBytes += it->size() + 1;   // Plus 1 for the delimiter
   }
   // Only print the delimiter after the first entry has been printed
   bool printDelim = false;
   // Prepend the *existing_value if one exists.
   if (existing_value) {
     new_value->reserve(numBytes + existing_value->size());
     new_value->append(existing_value->data(), existing_value->size());
     printDelim = true;
   } else if (numBytes) {
     new_value->reserve(numBytes-1); // Minus 1 since we have one less delimiter
   }
   // Concatenate the sequence of strings (and add a delimiter between each)
   for(auto it = operands.begin(); it != operands.end(); ++it) {
     if (printDelim) {
       new_value->append(1,delim_);
     }
     new_value->append(*it);
     printDelim = true;
   }
   return true;
 }
const char * rocksdb::StringAppendTESTOperator::Name () const override virtual
Implements rocksdb::MergeOperator.
Definition at line 93 of file stringappend2.cc.
{
   return "StringAppendTESTOperator";
 }
bool rocksdb::StringAppendTESTOperator::PartialMerge (const Slice & key, const Slice & left_operand, const Slice & right_operand, std::string * new_value, Logger * logger) const override virtual
Implements rocksdb::MergeOperator.
Definition at line 64 of file stringappend2.cc.
{
   return false;
 }
Member Data Documentation
char rocksdb::StringAppendTESTOperator::delim_ private
Definition at line 47 of file stringappend2.h.
Referenced by _AssocPartialMerge(), and FullMerge().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/utilities/merge_operators/string_append/stringappend2.h
rippled/src/ripple/rocksdb/rocksdb/utilities/merge_operators/string_append/stringappend2.cc