rippled: beast::asio::TestPeerLogicSyncClient Class Reference
beast::asio::TestPeerLogicSyncClient Class Reference
#include <TestPeerLogicSyncClient.h>
Public Member Functions
TestPeerLogicSyncClient (abstract_socket &socket)
PeerRole get_role () const noexcept
Model get_model () const noexcept
void on_connect ()
virtual void on_pre_handshake ()
Public Member Functions inherited from beast::asio::TestPeerLogic
TestPeerLogic (abstract_socket &socket)
error_code & error () noexcept
error_code const & error () const noexcept
error_code const & error (error_code const &ec) noexcept
abstract_socket & socket () noexcept
virtual void on_connect_async (error_code const &)
virtual void finished ()
Additional Inherited Members
Public Types inherited from beast::asio::TestPeerLogic
typedef boost::system::error_code error_code
Static Public Member Functions inherited from beast::asio::TestPeerLogic
static void pure_virtual ()
Detailed Description
Definition at line 26 of file TestPeerLogicSyncClient.h.
Constructor & Destructor Documentation
beast::asio::TestPeerLogicSyncClient::TestPeerLogicSyncClient (abstract_socket & socket) explicit
Definition at line 23 of file TestPeerLogicSyncClient.cpp.
     : TestPeerLogic (socket)
 {
 }
Member Function Documentation
TestPeerBasics::Model beast::asio::TestPeerLogicSyncClient::get_model () const virtual noexcept
Implements beast::asio::TestPeerLogic.
Definition at line 33 of file TestPeerLogicSyncClient.cpp.
References beast::asio::TestPeerBasics::Model::sync.
 {
     return Model::sync;
 }
PeerRole beast::asio::TestPeerLogicSyncClient::get_role () const virtual noexcept
Implements beast::asio::TestPeerLogic.
Definition at line 28 of file TestPeerLogicSyncClient.cpp.
References beast::asio::PeerRole::client.
Referenced by on_connect().
 {
     return PeerRole::client;
 }
void beast::asio::TestPeerLogicSyncClient::on_connect () virtual
Reimplemented from beast::asio::TestPeerLogic.
Definition at line 38 of file TestPeerLogicSyncClient.cpp.
References beast::asio::TestPeerLogic::error(), beast::asio::TestPeerBasics::failure(), get_role(), on_pre_handshake(), beast::asio::InputParser::read(), beast::asio::TestPeerLogic::socket(), beast::asio::TestPeerBasics::to_handshake_type(), and beast::asio::TestPeerBasics::unexpected().
 {
     {
         // pre-handshake hook is optional
         on_pre_handshake ();
         if (failure (error ()))
             return ;
     }
     if (socket ().needs_handshake ())
     {
         if (failure (socket ().handshake (to_handshake_type (get_role ()), error ())))
             return;
     }
     {
         std::size_t const amount = boost::asio::write (
             socket (), boost::asio::buffer ("hello", 5), error ());
         if (failure (error ()))
             return;
         if (unexpected (amount == 5, error ()))
             return;
     }
     {
         char data [7];
         size_t const amount = boost::asio::read (
             socket (), boost::asio::buffer (data, 7), error ());
         if (failure (error ()))
             return;
         if (unexpected (amount == 7, error ()))
             return;
         if (unexpected (memcmp (&data, "goodbye", 7) == 0, error ()))
             return;
     }
     // Wait for 1 byte which should never come. Instead,
     // the server should close its end and we will get eof
     {
         char data [1];
         boost::asio::read (socket (), boost::asio::buffer (data, 1), error ());
         if (error () == boost::asio::error::eof)
         {
             error () = error_code ();
         }
         else if (unexpected (failure (error ()), error ()))
         {
             return;
         }
     }
     if (socket ().needs_handshake ())
     {
         if (failure (socket ().shutdown (error ()), true))
             return;
         error () = error_code ();
     }
     if (failure (socket ().shutdown (abstract_socket::shutdown_send, error ())))
         return;
     if (failure (socket ().close (error ())))
         return;
 }
void beast::asio::TestPeerLogicSyncClient::on_pre_handshake () virtual
Reimplemented in beast::asio::TestPeerLogicProxyClient.
Definition at line 110 of file TestPeerLogicSyncClient.cpp.
Referenced by on_connect().
 {
 }
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_asio/tests/TestPeerLogicSyncClient.h
rippled/src/beast/modules/beast_asio/tests/TestPeerLogicSyncClient.cpp