rippled: rocksdb::StringSource Class Reference
rocksdb::StringSource Class Reference
Public Member Functions
StringSource (const Slice &contents, uint64_t uniq_id)
virtual ~StringSource ()
uint64_t Size () const
virtual Status Read (uint64_t offset, size_t n, Slice *result, char *scratch) const
virtual size_t GetUniqueId (char *id, size_t max_size) const
Public Member Functions inherited from rocksdb::RandomAccessFile
RandomAccessFile ()
virtual ~RandomAccessFile ()
virtual void Hint (AccessPattern pattern)
virtual Status InvalidateCache (size_t offset, size_t length)
Private Attributes
std::string contents_
uint64_t uniq_id_
Additional Inherited Members
Public Types inherited from rocksdb::RandomAccessFile
enum AccessPattern {
NORMAL, RANDOM, SEQUENTIAL, WILLNEED,
DONTNEED
}
Detailed Description
Definition at line 120 of file table_test.cc.
Constructor & Destructor Documentation
rocksdb::StringSource::StringSource (const Slice & contents, uint64_t uniq_id) inline
Definition at line 122 of file table_test.cc.
       : contents_(contents.data(), contents.size()), uniq_id_(uniq_id) {
   }
virtual rocksdb::StringSource::~StringSource () inline virtual
Definition at line 126 of file table_test.cc.
 { }
Member Function Documentation
virtual size_t rocksdb::StringSource::GetUniqueId (char * id, size_t max_size) const inline virtual
Reimplemented from rocksdb::RandomAccessFile.
Definition at line 143 of file table_test.cc.
References rocksdb::EncodeVarint64(), id, and uniq_id_.
{
     if (max_size < 20) {
       return 0;
     }
     char* rid = id;
     rid = EncodeVarint64(rid, uniq_id_);
     rid = EncodeVarint64(rid, 0);
     return static_cast<size_t>(rid-id);
   }
virtual Status rocksdb::StringSource::Read (uint64_t offset, size_t n, Slice * result, char * scratch) const inline virtual
Implements rocksdb::RandomAccessFile.
Definition at line 130 of file table_test.cc.
References contents_, rocksdb::Status::InvalidArgument(), and rocksdb::Status::OK().
{
     if (offset > contents_.size()) {
       return Status::InvalidArgument("invalid Read offset");
     }
     if (offset + n > contents_.size()) {
       n = contents_.size() - offset;
     }
     memcpy(scratch, &contents_[offset], n);
     *result = Slice(scratch, n);
     return Status::OK();
   }
uint64_t rocksdb::StringSource::Size () const inline
Definition at line 128 of file table_test.cc.
References contents_.
 { return contents_.size(); }
Member Data Documentation
std::string rocksdb::StringSource::contents_ private
Definition at line 155 of file table_test.cc.
Referenced by Read(), and Size().
uint64_t rocksdb::StringSource::uniq_id_ private
Definition at line 156 of file table_test.cc.
Referenced by GetUniqueId().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/table/table_test.cc