rippled: beast::basic_scoped_ostream< CharT, Traits, Allocator > Class Template Reference
beast::basic_scoped_ostream< CharT, Traits, Allocator > Class Template Reference
#include <basic_scoped_ostream.h>
Public Types
typedef std::basic_string
< CharT, Traits > string_type
Public Member Functions
basic_scoped_ostream (basic_scoped_ostream const &)=delete
basic_scoped_ostream & operator= (basic_scoped_ostream const)=delete
template<class Handler >
basic_scoped_ostream (Handler &&handler)
template<class T , class Handler >
basic_scoped_ostream (T const &t, Handler &&handler)
basic_scoped_ostream (basic_abstract_ostream< CharT, Traits > &ostream)
m_ss (std::move(other.m_ss))
~basic_scoped_ostream ()
basic_scoped_ostream & operator<< (std::ostream &manip(std::ostream &))
template<class T >
basic_scoped_ostream & operator<< (T const &t)
Private Types
typedef std::function< void(std::basic_string
< CharT, Traits, Allocator >
const &)> handler_t
typedef
std::basic_ostringstream
< CharT, Traits, Allocator > stream_type
Private Member Functions
stream_type & stream ()
Private Attributes
handler_t m_handler
stream_type m_ss
Detailed Description
template<class CharT, class Traits = std::char_traits <CharT>, class Allocator = std::allocator <CharT>>
class beast::basic_scoped_ostream< CharT, Traits, Allocator >
Scoped output stream that forwards to a functor upon destruction.
Definition at line 54 of file basic_scoped_ostream.h.
Member Typedef Documentation
template<class CharT , class Traits = std::char_traits <CharT>, class Allocator = std::allocator <CharT>> typedef std::function<void (std::basic_string <CharT, Traits, Allocator> const&)> beast::basic_scoped_ostream< CharT, Traits, Allocator >::handler_t private
Definition at line 58 of file basic_scoped_ostream.h.
template<class CharT , class Traits = std::char_traits <CharT>, class Allocator = std::allocator <CharT>> typedef std::basic_ostringstream< CharT, Traits, Allocator> beast::basic_scoped_ostream< CharT, Traits, Allocator >::stream_type private
Definition at line 61 of file basic_scoped_ostream.h.
template<class CharT , class Traits = std::char_traits <CharT>, class Allocator = std::allocator <CharT>> typedef std::basic_string<CharT, Traits> beast::basic_scoped_ostream< CharT, Traits, Allocator >::string_type
Definition at line 84 of file basic_scoped_ostream.h.
Constructor & Destructor Documentation
template<class CharT , class Traits = std::char_traits <CharT>, class Allocator = std::allocator <CharT>> beast::basic_scoped_ostream< CharT, Traits, Allocator >::basic_scoped_ostream (basic_scoped_ostream< CharT, Traits, Allocator > const &) delete
template<class CharT , class Traits = std::char_traits <CharT>, class Allocator = std::allocator <CharT>> template<class Handler > beast::basic_scoped_ostream< CharT, Traits, Allocator >::basic_scoped_ostream (Handler && handler) inline explicit
Definition at line 91 of file basic_scoped_ostream.h.
         : m_handler (std::forward <Handler> (handler))
     #if BEAST_NO_STDLIB_STREAM_MOVE
         , m_ss (std::make_unique <stream_type>())
     #endif
     {
     }
template<class CharT , class Traits = std::char_traits <CharT>, class Allocator = std::allocator <CharT>> template<class T , class Handler > beast::basic_scoped_ostream< CharT, Traits, Allocator >::basic_scoped_ostream (T const & t, Handler && handler) inline
Definition at line 100 of file basic_scoped_ostream.h.
References beast::basic_scoped_ostream< CharT, Traits, Allocator >::stream().
         : m_handler (std::forward <Handler> (handler))
     #if BEAST_NO_STDLIB_STREAM_MOVE
         , m_ss (std::make_unique <stream_type>())
     #endif
     {
         stream() << t;
     }
template<class CharT , class Traits = std::char_traits <CharT>, class Allocator = std::allocator <CharT>> beast::basic_scoped_ostream< CharT, Traits, Allocator >::basic_scoped_ostream (basic_abstract_ostream< CharT, Traits > & ostream) inline
Definition at line 109 of file basic_scoped_ostream.h.
         : m_handler (
             [&](string_type const& s)
             {
                 ostream.write (s);
             })
template<class CharT , class Traits = std::char_traits <CharT>, class Allocator = std::allocator <CharT>> beast::basic_scoped_ostream< CharT, Traits, Allocator >::~basic_scoped_ostream () inline
Definition at line 125 of file basic_scoped_ostream.h.
References beast::basic_scoped_ostream< CharT, Traits, Allocator >::m_handler, and beast::basic_scoped_ostream< CharT, Traits, Allocator >::stream().
     {
         auto const& s (stream().str());
         if (! s.empty())
             m_handler (s);
     }
Member Function Documentation
template<class CharT , class Traits = std::char_traits <CharT>, class Allocator = std::allocator <CharT>> beast::basic_scoped_ostream< CharT, Traits, Allocator >::m_ss (std:: moveother.m_ss) inline
Definition at line 121 of file basic_scoped_ostream.h.
     {
     }
template<class CharT , class Traits = std::char_traits <CharT>, class Allocator = std::allocator <CharT>> basic_scoped_ostream& beast::basic_scoped_ostream< CharT, Traits, Allocator >::operator<< (std::ostream & manipstd::ostream &) inline
Definition at line 133 of file basic_scoped_ostream.h.
References beast::basic_scoped_ostream< CharT, Traits, Allocator >::stream().
     {
         stream() << manip;
         return *this;
     }
template<class CharT , class Traits = std::char_traits <CharT>, class Allocator = std::allocator <CharT>> template<class T > basic_scoped_ostream& beast::basic_scoped_ostream< CharT, Traits, Allocator >::operator<< (T const & t) inline
Definition at line 141 of file basic_scoped_ostream.h.
References beast::basic_scoped_ostream< CharT, Traits, Allocator >::stream().
     {
         stream() << t;
         return *this;
     }
template<class CharT , class Traits = std::char_traits <CharT>, class Allocator = std::allocator <CharT>> basic_scoped_ostream& beast::basic_scoped_ostream< CharT, Traits, Allocator >::operator= (basic_scoped_ostream< CharT, Traits, Allocator > const) delete
template<class CharT , class Traits = std::char_traits <CharT>, class Allocator = std::allocator <CharT>> stream_type& beast::basic_scoped_ostream< CharT, Traits, Allocator >::stream () inline private
Definition at line 76 of file basic_scoped_ostream.h.
References beast::basic_scoped_ostream< CharT, Traits, Allocator >::m_ss.
Referenced by beast::basic_scoped_ostream< CharT, Traits, Allocator >::basic_scoped_ostream(), beast::basic_scoped_ostream< CharT, Traits, Allocator >::operator<<(), and beast::basic_scoped_ostream< CharT, Traits, Allocator >::~basic_scoped_ostream().
     {
         return m_ss;
     }
Member Data Documentation
template<class CharT , class Traits = std::char_traits <CharT>, class Allocator = std::allocator <CharT>> handler_t beast::basic_scoped_ostream< CharT, Traits, Allocator >::m_handler private
Definition at line 63 of file basic_scoped_ostream.h.
Referenced by beast::basic_scoped_ostream< CharT, Traits, Allocator >::~basic_scoped_ostream().
template<class CharT , class Traits = std::char_traits <CharT>, class Allocator = std::allocator <CharT>> stream_type beast::basic_scoped_ostream< CharT, Traits, Allocator >::m_ss private
Definition at line 74 of file basic_scoped_ostream.h.
Referenced by beast::basic_scoped_ostream< CharT, Traits, Allocator >::stream().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/streams/basic_scoped_ostream.h