rippled: beast::detail::UntrackedScopedLock< Mutex > Class Template Reference
beast::detail::UntrackedScopedLock< Mutex > Class Template Reference
#include <ScopedLock.h>
Public Member Functions
UntrackedScopedLock (Mutex const &mutex, char const *, int) noexcept
~UntrackedScopedLock () noexcept
void lock () noexcept
void lock (char const *, int) noexcept
void unlock () noexcept
Private Attributes
Mutex const & m_mutex
int m_lock_count
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
template<typename Mutex>
class beast::detail::UntrackedScopedLock< Mutex >
Definition at line 139 of file ScopedLock.h.
Constructor & Destructor Documentation
template<typename Mutex > beast::detail::UntrackedScopedLock< Mutex >::UntrackedScopedLock (Mutex const & mutex, char const * , int) inline explicit noexcept
Definition at line 142 of file ScopedLock.h.
References beast::detail::UntrackedScopedLock< Mutex >::lock().
         : m_mutex (mutex)
         , m_lock_count (0)
     {
         lock ();
     }
template<typename Mutex > beast::detail::UntrackedScopedLock< Mutex >::~UntrackedScopedLock () inline noexcept
Definition at line 150 of file ScopedLock.h.
References beast::detail::UntrackedScopedLock< Mutex >::m_lock_count, and beast::detail::UntrackedScopedLock< Mutex >::unlock().
     {
         if (m_lock_count > 0)
             unlock ();
     }
Member Function Documentation
template<typename Mutex > void beast::detail::UntrackedScopedLock< Mutex >::lock () inline noexcept
Definition at line 156 of file ScopedLock.h.
References beast::detail::UntrackedScopedLock< Mutex >::m_lock_count, and beast::detail::UntrackedScopedLock< Mutex >::m_mutex.
Referenced by beast::detail::UntrackedScopedLock< Mutex >::lock(), and beast::detail::UntrackedScopedLock< Mutex >::UntrackedScopedLock().
     {
         ++m_lock_count;
         m_mutex.lock ();
     }
template<typename Mutex > void beast::detail::UntrackedScopedLock< Mutex >::lock (char const * , int) inline noexcept
Definition at line 162 of file ScopedLock.h.
References beast::detail::UntrackedScopedLock< Mutex >::lock().
     {
         lock ();
     }
template<typename Mutex > void beast::detail::UntrackedScopedLock< Mutex >::unlock () inline noexcept
Definition at line 167 of file ScopedLock.h.
References beast::detail::UntrackedScopedLock< Mutex >::m_lock_count, and beast::detail::UntrackedScopedLock< Mutex >::m_mutex.
Referenced by beast::detail::UntrackedScopedLock< Mutex >::~UntrackedScopedLock().
     {
         m_mutex.unlock ();
         --m_lock_count;
     }
Member Data Documentation
template<typename Mutex > int beast::detail::UntrackedScopedLock< Mutex >::m_lock_count private
Definition at line 175 of file ScopedLock.h.
Referenced by beast::detail::UntrackedScopedLock< Mutex >::lock(), beast::detail::UntrackedScopedLock< Mutex >::unlock(), and beast::detail::UntrackedScopedLock< Mutex >::~UntrackedScopedLock().
template<typename Mutex > Mutex const& beast::detail::UntrackedScopedLock< Mutex >::m_mutex private
Definition at line 174 of file ScopedLock.h.
Referenced by beast::detail::UntrackedScopedLock< Mutex >::lock(), and beast::detail::UntrackedScopedLock< Mutex >::unlock().
The documentation for this class was generated from the following file:
rippled/src/beast/modules/beast_core/thread/detail/ScopedLock.h