rippled: beast::Random Class Reference
beast::Random Class Reference
#include <Random.h>
Public Member Functions
Random (std::int64_t seedValue) noexcept
Random ()
~Random () noexcept
int nextInt () noexcept
int nextInt (int maxValue) noexcept
std::int64_t nextInt64 () noexcept
float nextFloat () noexcept
double nextDouble () noexcept
bool nextBool () noexcept
void fillBitsRandomly (void *bufferToFill, size_t sizeInBytes)
void setSeed (std::int64_t newSeed) noexcept
void combineSeed (std::int64_t seedValue) noexcept
void setSeedRandomly ()
Static Public Member Functions
static Random & getSystemRandom () noexcept
Private Attributes
std::int64_t seed
Detailed Description
A random number generator.
You can create a Random object and use it to generate a sequence of random numbers.
Definition at line 36 of file Random.h.
Constructor & Destructor Documentation
beast::Random::Random (std::int64_t seedValue) explicit noexcept
Creates a Random object based on a seed value.
For a given seed value, the subsequent numbers generated by this object will be predictable, so a good idea is to set this value based on the time, e.g.
new Random (Time::currentTimeMillis())
Definition at line 28 of file Random.cpp.
     : seed (seedValue)
 {
     nextInt (); // fixes a bug where the first int is always 0
 }
beast::Random::Random ()
Creates a Random object using a random seed value. Internally, this calls setSeedRandomly() to randomise the seed.
Definition at line 34 of file Random.cpp.
References setSeedRandomly().
     : seed (1)
 {
     setSeedRandomly();
 }
beast::Random::~Random () noexcept
Destructor.
Definition at line 40 of file Random.cpp.
 {
 }
Member Function Documentation
void beast::Random::combineSeed (std::int64_t seedValue) noexcept
Merges this object's seed with another value. This sets the seed to be a value created by combining the current seed and this new value.
Definition at line 51 of file Random.cpp.
Referenced by setSeedRandomly().
 {
     seed ^= nextInt64() ^ seedValue;
 }
void beast::Random::fillBitsRandomly (void * bufferToFill, size_t sizeInBytes)
Fills a block of memory with random values.
Definition at line 110 of file Random.cpp.
References nextInt().
Referenced by ripple::NodeStore::TestBase::PredictableObjectFactory::createObject(), beast::BinaryEncoding_test::testBase16(), and beast::BinaryEncoding_test::testEncode().
 {
     int* d = static_cast<int*> (buffer);
     for (; bytes >= sizeof (int); bytes -= sizeof (int))
         *d++ = nextInt();
     if (bytes > 0)
     {
         const int lastBytes = nextInt();
         memcpy (d, &lastBytes, bytes);
     }
 }
Random & beast::Random::getSystemRandom () static noexcept
The overhead of creating a new Random object is fairly small, but if you want to avoid it, you can call this method to get a global shared Random object.
It's not thread-safe though, so threads should use their own Random object, otherwise you run the risk of your random numbers becoming.. erm.. randomly corrupted..
Definition at line 70 of file Random.cpp.
Referenced by beast::beast_getOutputFromCommand(), beast::File::createTempFile(), and beast::ObjCClass< SuperclassType >::getRandomisedName().
 {
     static Random sysRand;
     return sysRand;
 }
bool beast::Random::nextBool () noexcept
Returns the next random boolean value.
Definition at line 95 of file Random.cpp.
References nextInt().
 {
     return (nextInt() & 0x40000000) != 0;
 }
double beast::Random::nextDouble () noexcept
Returns the next random floating-point number.
Returns
a random value in the range 0 to 1.0
Definition at line 105 of file Random.cpp.
References nextInt().
Referenced by beast::Random_test::run().
 {
     return static_cast <std::uint32_t> (nextInt()) / (double) 0xffffffff;
 }
float beast::Random::nextFloat () noexcept
Returns the next random floating-point number.
Returns
a random value in the range 0 to 1.0
Definition at line 100 of file Random.cpp.
References nextInt().
Referenced by beast::Random_test::run().
 {
     return static_cast <std::uint32_t> (nextInt()) / (float) 0xffffffff;
 }
int beast::Random::nextInt () noexcept
Returns the next random 32 bit integer.
Returns
a random integer from the full range 0x80000000 to 0x7fffffff
Definition at line 77 of file Random.cpp.
References seed.
Referenced by ripple::Validators::Logic_test::addSources(), ripple::Resource::Manager_test::createGossip(), ripple::NodeStore::TestBase::PredictableObjectFactory::createObject(), beast::RandomAccessFile_test::createRecords(), beast::ServiceQueue_timing_test::Consumer< ServiceType >::do_handler(), beast::ServiceQueue_test::ServiceThread::do_handler(), fillBitsRandomly(), ripple::RadixMap::make_random_item(), nextBool(), nextDouble(), nextFloat(), nextInt64(), beast::UnitTestUtilities::Payload::repeatableRandomFill(), beast::UnitTestUtilities::repeatableShuffle(), beast::ServiceQueue_timing_test::Producer< ServiceType >::run(), beast::Random_test::run(), and setSeedRandomly().
 {
     seed = (seed * 0x5deece66dLL + 11) & 0xffffffffffffULL;
     return (int) (seed >> 16);
 }
int beast::Random::nextInt (int maxValue) noexcept
Returns the next random number, limited to a given range. The maxValue parameter may not be negative, or zero.
Returns
a random integer between 0 (inclusive) and maxValue (exclusive).
Definition at line 84 of file Random.cpp.
References bassert.
 {
     bassert (maxValue > 0);
     return (int) ((((unsigned int) nextInt()) * (std::uint64_t) maxValue) >> 32);
 }
std::int64_t beast::Random::nextInt64 () noexcept
Returns the next 64-bit random number.
Returns
a random integer from the full range 0x8000000000000000 to 0x7fffffffffffffff
Definition at line 90 of file Random.cpp.
References nextInt().
Referenced by beast::LexicalCast_test::nextRandomInt(), and beast::ServiceQueue_timing_test::testThreads().
 {
     return (((std::int64_t) nextInt()) << 32) | (std::int64_t) (std::uint64_t) (std::uint32_t) nextInt();
 }
void beast::Random::setSeed (std::int64_t newSeed) noexcept
Resets this Random object to a given seed value.
Definition at line 44 of file Random.cpp.
 {
     seed = newSeed;
     nextInt (); // fixes a bug where the first int is always 0
 }
void beast::Random::setSeedRandomly ()
Reseeds this generator using a value generated from various semi-random system properties like the current time, etc.
Because this function convolves the time with the last seed value, calling it repeatedly will increase the randomness of the final result.
Definition at line 56 of file Random.cpp.
References combineSeed(), beast::Time::currentTimeMillis(), beast::Time::getHighResolutionTicks(), beast::Time::getHighResolutionTicksPerSecond(), beast::Time::getMillisecondCounter(), nextInt(), and seed.
Referenced by Random(), and beast::Random_test::run().
 {
     static std::int64_t globalSeed = 0;
     combineSeed (globalSeed ^ (std::int64_t) (std::intptr_t) this);
     combineSeed (Time::getMillisecondCounter());
     combineSeed (Time::getHighResolutionTicks());
     combineSeed (Time::getHighResolutionTicksPerSecond());
     combineSeed (Time::currentTimeMillis());
     globalSeed ^= seed;
     nextInt (); // fixes a bug where the first int is always 0
 }
Member Data Documentation
std::int64_t beast::Random::seed private
Definition at line 123 of file Random.h.
Referenced by nextInt(), and setSeedRandomly().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_core/maths/Random.h
rippled/src/beast/modules/beast_core/maths/Random.cpp