rippled: ripple::LoadManagerImp Class Reference
ripple::LoadManagerImp Class Reference
Classes
class Cost
Public Types
typedef RippleMutex LockType
typedef std::lock_guard< LockType > ScopedLockType
Public Types inherited from beast::Thread
typedef void * ThreadID
Public Member Functions
LoadManagerImp (Stoppable &parent, beast::Journal journal)
~LoadManagerImp ()
void onPrepare ()
void onStart ()
void onStop ()
void resetDeadlockDetector ()
void activateDeadlockDetector ()
void logDeadlock (int dlTime)
void run ()
Public Member Functions inherited from ripple::LoadManager
virtual ~LoadManager ()
Public Member Functions inherited from beast::Stoppable
Stoppable (char const *name, Stoppable &parent)
virtual ~Stoppable ()
bool isStopping () const
bool isStopped () const
bool areChildrenStopped () const
void stopped ()
virtual void onChildrenStopped ()
Public Member Functions inherited from beast::Thread
Thread (const String &threadName)
virtual ~Thread ()
void startThread ()
void startThread (int priority)
bool stopThread (int timeOutMilliseconds=-1)
void stopThreadAsync ()
bool isThreadRunning () const
void signalThreadShouldExit ()
bool threadShouldExit () const
bool waitForThreadToExit (int timeOutMilliseconds=-1) const
bool setPriority (int priority)
void setAffinityMask (std::uint32_t affinityMask)
bool wait (int timeOutMilliseconds=-1) const
void notify () const
ThreadID getThreadId () const noexcept
const String & getThreadName () const
Public Attributes
beast::Journal m_journal
LockType mLock
bool mArmed
int mDeadLock
std::vector< Cost > mCosts
Additional Inherited Members
Static Public Member Functions inherited from ripple::LoadManager
static LoadManager * New (Stoppable &parent, beast::Journal journal)
Static Public Member Functions inherited from beast::Thread
static bool setCurrentThreadPriority (int priority)
static void setCurrentThreadAffinityMask (std::uint32_t affinityMask)
static void sleep (int milliseconds)
static void yield ()
static ThreadID getCurrentThreadId ()
static Thread * getCurrentThread ()
static void setCurrentThreadName (const String &newThreadName)
Protected Member Functions inherited from ripple::LoadManager
LoadManager (Stoppable &parent)
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Protected Attributes inherited from beast::Stoppable
char const * m_name
RootStoppable & m_root
Child m_child
Atomic< int > m_started
bool volatile m_stopped
bool volatile m_childrenStopped
Children m_children
WaitableEvent m_stoppedEvent
Detailed Description
Definition at line 22 of file LoadManager.cpp.
Member Typedef Documentation
typedef RippleMutex ripple::LoadManagerImp::LockType
Definition at line 75 of file LoadManager.cpp.
typedef std::lock_guard<LockType> ripple::LoadManagerImp::ScopedLockType
Definition at line 76 of file LoadManager.cpp.
Constructor & Destructor Documentation
ripple::LoadManagerImp::LoadManagerImp (Stoppable & parent, beast::Journal journal) inline
Definition at line 87 of file LoadManager.cpp.
References ripple::UptimeTimer::beginManualUpdates(), and ripple::UptimeTimer::getInstance().
         : LoadManager (parent)
         , Thread ("loadmgr")
         , m_journal (journal)
         , mArmed (false)
         , mDeadLock (0)
         , mCosts (LT_MAX)
     {
         UptimeTimer::getInstance ().beginManualUpdates ();
     }
ripple::LoadManagerImp::~LoadManagerImp () inline
Definition at line 98 of file LoadManager.cpp.
References ripple::UptimeTimer::endManualUpdates(), ripple::UptimeTimer::getInstance(), and beast::Thread::stopThread().
     {
         UptimeTimer::getInstance ().endManualUpdates ();
         stopThread ();
     }
Member Function Documentation
void ripple::LoadManagerImp::activateDeadlockDetector () inline virtual
Turn on deadlock detection.
The deadlock detector begins in a disabled state. After this function is called, it will report deadlocks using a separate thread whenever the reset function is not called at least once per 10 seconds.
See Also
resetDeadlockDetector
Implements ripple::LoadManager.
Definition at line 142 of file LoadManager.cpp.
References mArmed.
     {
         mArmed = true;
     }
void ripple::LoadManagerImp::logDeadlock (int dlTime) inline
Definition at line 147 of file LoadManager.cpp.
References m_journal, beast::unit_test::print(), and beast::Journal::warning.
Referenced by run().
     {
         m_journal.warning << "Server stalled for " << dlTime << " seconds.";
 #if RIPPLE_TRACK_MUTEXES
         StringArray report;
         TrackedMutex::generateGlobalBlockedReport (report);
         if (report.size () > 0)
         {
             report.insert (0, String::empty);
             report.insert (-1, String::empty);
             Log::print (report);
         }
 #endif
     }
void ripple::LoadManagerImp::onPrepare () inline virtual
Override called during preparation. Since all other Stoppable objects in the tree have already been constructed, this provides an opportunity to perform initialization which depends on calling into other Stoppable objects. This call is made on the same thread that called prepare(). The default implementation does nothing. Guaranteed to only be called once.
Reimplemented from beast::Stoppable.
Definition at line 111 of file LoadManager.cpp.
     {
     }
void ripple::LoadManagerImp::onStart () inline virtual
Override called during start.
Reimplemented from beast::Stoppable.
Definition at line 115 of file LoadManager.cpp.
References beast::Journal::debug, m_journal, and beast::Thread::startThread().
     {
         m_journal.debug << "Starting";
         startThread ();
     }
void ripple::LoadManagerImp::onStop () inline virtual
Override called when the stop notification is issued.
The call is made on an unspecified, implementation-specific thread. onStop and onChildrenStopped will never be called concurrently, across all Stoppable objects descended from the same root, inclusive of the root.
It is safe to call isStopping, isStopped, and areChildrenStopped from within this function; The values returned will always be valid and never change during the callback.
The default implementation simply calls stopped(). This is applicable when the Stoppable has a trivial stop operation (or no stop operation), and we are merely using the Stoppable API to position it as a dependency of some parent service.
Thread safety: May not block for long periods. Guaranteed only to be called once. Must be safe to call from any thread at any time.
Reimplemented from beast::Stoppable.
Definition at line 121 of file LoadManager.cpp.
References beast::Journal::debug, beast::Thread::isThreadRunning(), m_journal, beast::Stoppable::stopped(), and beast::Thread::stopThreadAsync().
     {
         if (isThreadRunning ())
         {
             m_journal.debug << "Stopping";
             stopThreadAsync ();
         }
         else
         {
             stopped ();
         }
     }
void ripple::LoadManagerImp::resetDeadlockDetector () inline virtual
Reset the deadlock detection timer.
A dedicated thread monitors the deadlock timer, and if too much time passes it will produce log warnings.
Implements ripple::LoadManager.
Definition at line 136 of file LoadManager.cpp.
References ripple::UptimeTimer::getElapsedSeconds(), ripple::UptimeTimer::getInstance(), mDeadLock, and mLock.
     {
         ScopedLockType sl (mLock);
         mDeadLock = UptimeTimer::getInstance ().getElapsedSeconds ();
     }
void ripple::LoadManagerImp::run () inline virtual
Must be implemented to perform the thread's actual code.
Remember that the thread must regularly check the threadShouldExit() method whilst running, and if this returns true it should return from the run() method as soon as possible to avoid being forcibly killed.
See Also
threadShouldExit, startThread
Implements beast::Thread.
Definition at line 165 of file LoadManager.cpp.
References ripple::getApp(), ripple::UptimeTimer::getElapsedSeconds(), ripple::Application::getFeeTrack(), ripple::UptimeTimer::getInstance(), ripple::Application::getJobQueue(), ripple::JobQueue::getJson(), ripple::Application::getOPs(), ripple::UptimeTimer::incrementElapsedTime(), beast::Journal::info, logDeadlock(), ripple::LoadFeeTrack::lowerLocalFee(), m_journal, mArmed, mDeadLock, mLock, ripple::LoadFeeTrack::raiseLocalFee(), ripple::NetworkOPs::reportFeeChange(), beast::Stoppable::stopped(), beast::Thread::threadShouldExit(), and beast::Journal::warning.
     {
         // VFALCO TODO replace this with a beast Time object?
         //
         // Initialize the clock to the current time.
         boost::posix_time::ptime t = boost::posix_time::microsec_clock::universal_time ();
         while (! threadShouldExit ())
         {
             {
                 // VFALCO NOTE What is this lock protecting?
                 ScopedLockType sl (mLock);
                 // VFALCO NOTE I think this is to reduce calls to the operating system
                 //             for retrieving the current time.
                 //
                 //        TODO Instead of incrementing can't we just retrieve the current
                 //             time again?
                 //
                 // Manually update the timer.
                 UptimeTimer::getInstance ().incrementElapsedTime ();
                 // Measure the amount of time we have been deadlocked, in seconds.
                 //
                 // VFALCO NOTE mDeadLock is a canary for detecting the condition.
                 int const timeSpentDeadlocked = UptimeTimer::getInstance ().getElapsedSeconds () - mDeadLock;
                 // VFALCO NOTE I think that "armed" refers to the deadlock detector
                 //
                 int const reportingIntervalSeconds = 10;
                 if (mArmed && (timeSpentDeadlocked >= reportingIntervalSeconds))
                 {
                     // Report the deadlocked condition every 10 seconds
                     if ((timeSpentDeadlocked % reportingIntervalSeconds) == 0)
                     {
                         logDeadlock (timeSpentDeadlocked);
                     }
                     // If we go over 500 seconds spent deadlocked, it means that the
                     // deadlock resolution code has failed, which qualifies as undefined
                     // behavior.
                     //
                     assert (timeSpentDeadlocked < 500);
                 }
             }
             bool change;
             // VFALCO TODO Eliminate the dependence on the Application object.
             //             Choices include constructing with the job queue / feetracker.
             //             Another option is using an observer pattern to invert the dependency.
             if (getApp().getJobQueue ().isOverloaded ())
             {
                 m_journal.info << getApp().getJobQueue ().getJson (0);
                 change = getApp().getFeeTrack ().raiseLocalFee ();
             }
             else
             {
                 change = getApp().getFeeTrack ().lowerLocalFee ();
             }
             if (change)
             {
                 // VFALCO TODO replace this with a Listener / observer and subscribe in NetworkOPs or Application
                 getApp().getOPs ().reportFeeChange ();
             }
             t += boost::posix_time::seconds (1);
             boost::posix_time::time_duration when = t - boost::posix_time::microsec_clock::universal_time ();
             if ((when.is_negative ()) || (when.total_seconds () > 1))
             {
                 m_journal.warning << "time jump";
                 t = boost::posix_time::microsec_clock::universal_time ();
             }
             else
             {
                 boost::this_thread::sleep (when);
             }
         }
         stopped ();
     }
Member Data Documentation
beast::Journal ripple::LoadManagerImp::m_journal
Definition at line 74 of file LoadManager.cpp.
Referenced by logDeadlock(), onStart(), onStop(), and run().
bool ripple::LoadManagerImp::mArmed
Definition at line 79 of file LoadManager.cpp.
Referenced by activateDeadlockDetector(), and run().
std::vector<Cost> ripple::LoadManagerImp::mCosts
Definition at line 83 of file LoadManager.cpp.
int ripple::LoadManagerImp::mDeadLock
Definition at line 81 of file LoadManager.cpp.
Referenced by resetDeadlockDetector(), and run().
LockType ripple::LoadManagerImp::mLock
Definition at line 77 of file LoadManager.cpp.
Referenced by resetDeadlockDetector(), and run().
The documentation for this class was generated from the following file:
rippled/src/ripple_app/main/LoadManager.cpp