rippled: beast::hardened_hash_sha256_test Class Reference
beast::hardened_hash_sha256_test Class Reference
Public Member Functions
void testSHA256 ()
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 271 of file hardened_hash.test.cpp.
Member Function Documentation
void beast::hardened_hash_sha256_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 304 of file hardened_hash.test.cpp.
References testSHA256().
     {
         testSHA256();
     }
void beast::hardened_hash_sha256_test::testSHA256 () inline
Definition at line 276 of file hardened_hash.test.cpp.
References beast::unsigned_integer< Bits, UInt >::bytes, beast::unsigned_integer< Bits, UInt >::data(), beast::unsigned_integer< Bits, UInt >::from_number(), beast::Sha256::hash(), beast::unit_test::suite::log, beast::unit_test::suite::pass(), and beast::unit_test::suite::testcase().
Referenced by run().
     {
         testcase ("sha256");
         log <<
             "sizeof(std::size_t) == " << sizeof(std::size_t);
         hardened_hash <sha256_t> h;
         for (int i = 0; i < 100; ++i)
         {
             sha256_t v (sha256_t::from_number (i));
             Sha256::digest_type d;
             Sha256::hash (v.data(), sha256_t::bytes, d);
             sha256_t d_;
             memcpy (d_.data(), d.data(), sha256_t::bytes);
             std::size_t result (h (d_));
             log <<
                 "i=" << std::setw(2) << i << " " <<
                 "sha256=0x" << d_ << " " <<
                 "hash=0x" <<
                     std::setfill ('0') <<
                     std::setw (2*sizeof(std::size_t)) << result
                 ;
             pass();
         }
     }
The documentation for this class was generated from the following file:
rippled/src/beast/beast/container/tests/hardened_hash.test.cpp