rippled: ripple::NetworkOPsImp Class Reference
ripple::NetworkOPsImp Class Reference
Public Types
enum Fault { IO_ERROR = 1, NO_NETWORK = 2 }
typedef std::function< void(Transaction::pointer,
TER)> stCallback
typedef std::tuple
< std::string, std::string,
std::uint32_t > txnMetaLedgerType
Public Types inherited from ripple::NetworkOPs
enum Fault { IO_ERROR = 1, NO_NETWORK = 2 }
enum OperatingMode {
omDISCONNECTED = 0, omCONNECTED = 1, omSYNCING = 2, omTRACKING = 3,
omFULL = 4
}
typedef beast::abstract_clock
< std::chrono::seconds > clock_type
typedef ripple::unordered_map
< std::uint64_t, InfoSub::wptr > SubMapType
typedef std::function< void(Transaction::pointer,
TER)> stCallback
typedef ripple::unordered_map
< uint160, std::list
< LedgerProposal::pointer > > Proposals
typedef std::vector< std::pair
< Transaction::pointer,
TransactionMetaSet::pointer > > AccountTxs
typedef std::vector< std::pair
< Transaction::pointer,
TransactionMetaSet::pointer > > TxsAccount
typedef std::tuple
< std::string, std::string,
std::uint32_t > txnMetaLedgerType
typedef std::vector
< txnMetaLedgerType > MetaTxsList
Public Member Functions
NetworkOPsImp (clock_type &clock, LedgerMaster &ledgerMaster, Stoppable &parent, beast::Journal journal)
~NetworkOPsImp ()
std::uint32_t getNetworkTimeNC ()
std::uint32_t getCloseTimeNC ()
std::uint32_t getValidationTimeNC ()
void closeTimeOffset (int)
boost::posix_time::ptime getNetworkTimePT ()
std::uint32_t getLedgerID (uint256 const &hash)
std::uint32_t getCurrentLedgerID ()
OperatingMode getOperatingMode ()
std::string strOperatingMode ()
Ledger::pointer getClosedLedger ()
Ledger::pointer getValidatedLedger ()
Ledger::pointer getPublishedLedger ()
Ledger::pointer getCurrentLedger ()
Ledger::pointer getLedgerByHash (uint256 const &hash)
Ledger::pointer getLedgerBySeq (const std::uint32_t seq)
void missingNodeInLedger (const std::uint32_t seq)
uint256 getClosedLedgerHash ()
bool haveLedgerRange (std::uint32_t from, std::uint32_t to)
bool haveLedger (std::uint32_t seq)
std::uint32_t getValidatedSeq ()
bool isValidated (std::uint32_t seq)
bool isValidated (std::uint32_t seq, uint256 const &hash)
bool isValidated (Ledger::ref l)
bool getValidatedRange (std::uint32_t &minVal, std::uint32_t &maxVal)
bool getFullValidatedRange (std::uint32_t &minVal, std::uint32_t &maxVal)
SerializedValidation::ref getLastValidation ()
void setLastValidation (SerializedValidation::ref v)
SLE::pointer getSLE (Ledger::pointer lpLedger, uint256 const &uHash)
SLE::pointer getSLEi (Ledger::pointer lpLedger, uint256 const &uHash)
void submitTransaction (Job &, SerializedTransaction::pointer, stCallback callback=stCallback())
Transaction::pointer submitTransactionSync (Transaction::ref tpTrans, bool bAdmin, bool bLocal, bool bFailHard, bool bSubmit)
void runTransactionQueue ()
Transaction::pointer processTransactionCb (Transaction::pointer, bool bAdmin, bool bLocal, bool bFailHard, stCallback)
Transaction::pointer processTransaction (Transaction::pointer transaction, bool bAdmin, bool bLocal, bool bFailHard)
void processTransactionCbVoid (Transaction::pointer p, bool bAdmin, bool bLocal, bool bFailHard, stCallback cb)
Transaction::pointer findTransactionByID (uint256 const &transactionID)
int findTransactionsByDestination (std::list< Transaction::pointer > &, const RippleAddress &destinationAccount, std::uint32_t startLedgerSeq, std::uint32_t endLedgerSeq, int maxTransactions)
AccountState::pointer getAccountState (Ledger::ref lrLedger, const RippleAddress &accountID)
SLE::pointer getGenerator (Ledger::ref lrLedger, const uint160 &uGeneratorID)
STVector256 getDirNodeInfo (Ledger::ref lrLedger, uint256 const &uRootIndex, std::uint64_t &uNodePrevious, std::uint64_t &uNodeNext)
Json::Value getOwnerInfo (Ledger::pointer lpLedger, const RippleAddress &naAccount)
void getBookPage (Ledger::pointer lpLedger, const uint160 &uTakerPaysCurrencyID, const uint160 &uTakerPaysIssuerID, const uint160 &uTakerGetsCurrencyID, const uint160 &uTakerGetsIssuerID, const uint160 &uTakerID, const bool bProof, const unsigned int iLimit, const Json::Value &jvMarker, Json::Value &jvResult)
void processTrustedProposal (LedgerProposal::pointer proposal, boost::shared_ptr< protocol::TMProposeSet > set, RippleAddress nodePublic, uint256 checkLedger, bool sigGood)
SHAMapAddNode gotTXData (const boost::shared_ptr< Peer > &peer, uint256 const &hash, const std::list< SHAMapNode > &nodeIDs, const std::list< Blob > &nodeData)
bool recvValidation (SerializedValidation::ref val, const std::string &source)
void takePosition (int seq, SHAMap::ref position)
SHAMap::pointer getTXMap (uint256 const &hash)
bool hasTXSet (const boost::shared_ptr< Peer > &peer, uint256 const &set, protocol::TxSetStatus status)
void mapComplete (uint256 const &hash, SHAMap::ref map)
bool stillNeedTXSet (uint256 const &hash)
void makeFetchPack (Job &, boost::weak_ptr< Peer > peer, boost::shared_ptr< protocol::TMGetObjectByHash > request, Ledger::pointer wantLedger, Ledger::pointer haveLedger, std::uint32_t uUptime)
bool shouldFetchPack (std::uint32_t seq)
void gotFetchPack (bool progress, std::uint32_t seq)
void addFetchPack (uint256 const &hash, boost::shared_ptr< Blob > &data)
bool getFetchPack (uint256 const &hash, Blob &data)
int getFetchSize ()
void sweepFetchPack ()
void switchLastClosedLedger (Ledger::pointer newLedger, bool duringConsensus)
bool checkLastClosedLedger (const Overlay::PeerSequence &, uint256 &networkClosed)
int beginConsensus (uint256 const &networkClosed, Ledger::pointer closingLedger)
void tryStartConsensus ()
void endConsensus (bool correctLCL)
void setStandAlone ()
void setStateTimer ()
void newLCL (int proposers, int convergeTime, uint256 const &ledgerHash)
void needNetworkLedger ()
void clearNeedNetworkLedger ()
bool isNeedNetworkLedger ()
bool isFull ()
void setProposing (bool p, bool v)
bool isProposing ()
bool isValidating ()
bool isFeatureBlocked ()
void setFeatureBlocked ()
void consensusViewChange ()
int getPreviousProposers ()
int getPreviousConvergeTime ()
std::uint32_t getLastCloseTime ()
void setLastCloseTime (std::uint32_t t)
Json::Value getConsensusInfo ()
Json::Value getServerInfo (bool human, bool admin)
void clearLedgerFetch ()
Json::Value getLedgerFetchInfo ()
std::uint32_t acceptLedger ()
ripple::unordered_map< uint160,
std::list
< LedgerProposal::pointer > > & peekStoredProposals ()
void storeProposal (LedgerProposal::ref proposal, const RippleAddress &peerPublic)
uint256 getConsensusLCL ()
void reportFeeChange ()
void updateLocalTx (Ledger::ref newValidLedger) override
void addLocalTx (Ledger::ref openLedger, SerializedTransaction::ref txn) override
std::size_t getLocalTxCount () override
std::string transactionsSQL (std::string selection, const RippleAddress &account, std::int32_t minLedger, std::int32_t maxLedger, bool descending, std::uint32_t offset, int limit, bool binary, bool count, bool bAdmin)
std::vector< std::pair
< Transaction::pointer,
TransactionMetaSet::pointer > > getAccountTxs (const RippleAddress &account, std::int32_t minLedger, std::int32_t maxLedger, bool descending, std::uint32_t offset, int limit, bool bAdmin)
std::vector< std::pair
< Transaction::pointer,
TransactionMetaSet::pointer > > getTxsAccount (const RippleAddress &account, std::int32_t minLedger, std::int32_t maxLedger, bool forward, Json::Value &token, int limit, bool bAdmin)
std::vector< txnMetaLedgerType > getAccountTxsB (const RippleAddress &account, std::int32_t minLedger, std::int32_t maxLedger, bool descending, std::uint32_t offset, int limit, bool bAdmin)
std::vector< txnMetaLedgerType > getTxsAccountB (const RippleAddress &account, std::int32_t minLedger, std::int32_t maxLedger, bool forward, Json::Value &token, int limit, bool bAdmin)
std::vector< RippleAddress > getLedgerAffectedAccounts (std::uint32_t ledgerSeq)
void pubLedger (Ledger::ref lpAccepted)
void pubProposedTransaction (Ledger::ref lpCurrent, SerializedTransaction::ref stTxn, TER terResult)
void subAccount (InfoSub::ref ispListener, const boost::unordered_set< RippleAddress > &vnaAccountIDs, std::uint32_t uLedgerIndex, bool rt)
void unsubAccount (std::uint64_t uListener, const boost::unordered_set< RippleAddress > &vnaAccountIDs, bool rt)
bool subLedger (InfoSub::ref ispListener, Json::Value &jvResult)
bool unsubLedger (std::uint64_t uListener)
bool subServer (InfoSub::ref ispListener, Json::Value &jvResult)
bool unsubServer (std::uint64_t uListener)
bool subBook (InfoSub::ref ispListener, RippleCurrency const &currencyPays, RippleCurrency const &currencyGets, RippleIssuer const &issuerPays, RippleIssuer const &issuerGets)
bool unsubBook (std::uint64_t uListener, RippleCurrency const &currencyPays, RippleCurrency const &currencyGets, RippleIssuer const &issuerPays, RippleIssuer const &issuerGets)
bool subTransactions (InfoSub::ref ispListener)
bool unsubTransactions (std::uint64_t uListener)
bool subRTTransactions (InfoSub::ref ispListener)
bool unsubRTTransactions (std::uint64_t uListener)
InfoSub::pointer findRpcSub (const std::string &strUrl)
InfoSub::pointer addRpcSub (const std::string &strUrl, InfoSub::ref rspEntry)
void onStop ()
Public Member Functions inherited from ripple::NetworkOPs
virtual ~NetworkOPs ()=0
Private Types
typedef ripple::unordered_map
< uint160, SubMapType > SubInfoMapType
typedef ripple::unordered_map
< uint160, SubMapType >
::iterator SubInfoMapIterator
typedef ripple::unordered_map
< std::string,
InfoSub::pointer > subRpcMapType
typedef RippleRecursiveMutex LockType
typedef std::lock_guard< LockType > ScopedLockType
Private Member Functions
void setHeartbeatTimer ()
void setClusterTimer ()
void onDeadlineTimer (beast::DeadlineTimer &timer)
void processHeartbeatTimer ()
void processClusterTimer ()
void setMode (OperatingMode)
Json::Value transJson (const SerializedTransaction &stTxn, TER terResult, bool bValidated, Ledger::ref lpCurrent)
bool haveConsensusObject ()
Json::Value pubBootstrapAccountInfo (Ledger::ref lpAccepted, const RippleAddress &naAccountID)
void pubValidatedTransaction (Ledger::ref alAccepted, const AcceptedLedgerTx &alTransaction)
void pubAccountTransaction (Ledger::ref lpCurrent, const AcceptedLedgerTx &alTransaction, bool isAccepted)
void pubServer ()
Private Attributes
clock_type & m_clock
beast::Journal m_journal
std::unique_ptr< LocalTxs > m_localTX
std::unique_ptr< FeeVote > m_feeVote
LockType mLock
OperatingMode mMode
bool mNeedNetworkLedger
bool mProposing
bool mValidating
bool mFeatureBlocked
boost::posix_time::ptime mConnectTime
beast::DeadlineTimer m_heartbeatTimer
beast::DeadlineTimer m_clusterTimer
boost::shared_ptr
< LedgerConsensus > mConsensus
ripple::unordered_map< uint160,
std::list
< LedgerProposal::pointer > > mStoredProposals
LedgerMaster & m_ledgerMaster
InboundLedger::pointer mAcquiringLedger
int mCloseTimeOffset
int mLastCloseProposers
int mLastCloseConvergeTime
uint256 mLastCloseHash
std::uint32_t mLastCloseTime
std::uint32_t mLastValidationTime
SerializedValidation::pointer mLastValidation
std::map< uint256, std::pair
< int, SHAMap::pointer > > mRecentPositions
SubInfoMapType mSubAccount
SubInfoMapType mSubRTAccount
subRpcMapType mRpcSubMap
SubMapType mSubLedger
SubMapType mSubServer
SubMapType mSubTransactions
SubMapType mSubRTTransactions
TaggedCache< uint256, Blob > mFetchPack
std::uint32_t mFetchSeq
std::uint32_t mLastLoadBase
std::uint32_t mLastLoadFactor
Additional Inherited Members
Static Public Member Functions inherited from ripple::NetworkOPs
static NetworkOPs * New (clock_type &clock, LedgerMaster &ledgerMaster, Stoppable &parent, beast::Journal journal)
Protected Member Functions inherited from ripple::NetworkOPs
NetworkOPs (Stoppable &parent)
Protected Attributes inherited from beast::Stoppable
char const * m_name
RootStoppable & m_root
Child m_child
Atomic< int > m_started
bool volatile m_stopped
bool volatile m_childrenStopped
Children m_children
WaitableEvent m_stoppedEvent
Detailed Description
Definition at line 33 of file NetworkOPs.cpp.
Member Typedef Documentation
typedef RippleRecursiveMutex ripple::NetworkOPsImp::LockType private
Definition at line 458 of file NetworkOPs.cpp.
typedef std::lock_guard<LockType> ripple::NetworkOPsImp::ScopedLockType private
Definition at line 459 of file NetworkOPs.cpp.
typedef std::function<void (Transaction::pointer, TER)> ripple::NetworkOPsImp::stCallback
Definition at line 164 of file NetworkOPs.cpp.
typedef ripple::unordered_map<uint160, SubMapType>::iterator ripple::NetworkOPsImp::SubInfoMapIterator private
Definition at line 453 of file NetworkOPs.cpp.
typedef ripple::unordered_map<uint160, SubMapType> ripple::NetworkOPsImp::SubInfoMapType private
Definition at line 452 of file NetworkOPs.cpp.
typedef ripple::unordered_map<std::string, InfoSub::pointer> ripple::NetworkOPsImp::subRpcMapType private
Definition at line 455 of file NetworkOPs.cpp.
typedef std::tuple<std::string, std::string, std::uint32_t> ripple::NetworkOPsImp::txnMetaLedgerType
Definition at line 367 of file NetworkOPs.cpp.
Member Enumeration Documentation
enum ripple::NetworkOPsImp::Fault
Enumerator
IO_ERROR
NO_NETWORK
Definition at line 39 of file NetworkOPs.cpp.
     {
         // exceptions these functions can throw
         IO_ERROR    = 1,
         NO_NETWORK  = 2,
     };
Constructor & Destructor Documentation
ripple::NetworkOPsImp::NetworkOPsImp (clock_type & clock, LedgerMaster & ledgerMaster, Stoppable & parent, beast::Journal journal) inline
Definition at line 49 of file NetworkOPs.cpp.
         : NetworkOPs (parent)
         , m_clock (clock)
         , m_journal (journal)
         , m_localTX (LocalTxs::New ())
         , m_feeVote (make_FeeVote(10, 20 * SYSTEM_CURRENCY_PARTS,
             5 * SYSTEM_CURRENCY_PARTS, LogPartition::getJournal <FeeVoteLog>()))
         , mMode (omDISCONNECTED)
         , mNeedNetworkLedger (false)
         , mProposing (false)
         , mValidating (false)
         , mFeatureBlocked (false)
         , m_heartbeatTimer (this)
         , m_clusterTimer (this)
         , m_ledgerMaster (ledgerMaster)
         , mCloseTimeOffset (0)
         , mLastCloseProposers (0)
         , mLastCloseConvergeTime (1000 * LEDGER_IDLE_INTERVAL)
         , mLastCloseTime (0)
         , mLastValidationTime (0)
         , mFetchPack ("FetchPack", 65536, 45, clock,
             LogPartition::getJournal <TaggedCacheLog> ())
         , mFetchSeq (0)
         , mLastLoadBase (256)
         , mLastLoadFactor (256)
     {
     }
ripple::NetworkOPsImp::~NetworkOPsImp () inline
Definition at line 78 of file NetworkOPs.cpp.
     {
     }
Member Function Documentation
std::uint32_t ripple::NetworkOPsImp::acceptLedger () virtual
Implements ripple::NetworkOPs.
Definition at line 2717 of file NetworkOPs.cpp.
References beginConsensus(), ripple::LedgerMaster::getClosedLedger(), ripple::LedgerMaster::getCurrentLedger(), m_ledgerMaster, and mConsensus.
 {
     // accept the current transaction tree, return the new ledger's sequence
     beginConsensus (m_ledgerMaster.getClosedLedger ()->getHash (), m_ledgerMaster.getCurrentLedger ());
     mConsensus->simulate ();
     return m_ledgerMaster.getCurrentLedger ()->getLedgerSeq ();
 }
void ripple::NetworkOPsImp::addFetchPack (uint256 const & hash, boost::shared_ptr< Blob > & data) virtual
Implements ripple::NetworkOPs.
Definition at line 3265 of file NetworkOPs.cpp.
References ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::canonicalize(), and mFetchPack.
 {
     mFetchPack.canonicalize (hash, data);
 }
void ripple::NetworkOPsImp::addLocalTx (Ledger::ref openLedger, SerializedTransaction::ref txn) inline override virtual
Implements ripple::NetworkOPs.
Definition at line 342 of file NetworkOPs.cpp.
References m_localTX.
Referenced by processTransactionCb().
     {
         m_localTX->push_back (openLedger->getLedgerSeq(), txn);
     }
InfoSub::pointer ripple::NetworkOPsImp::addRpcSub (const std::string & strUrl, InfoSub::ref rspEntry) virtual
Implements ripple::InfoSub::Source.
Definition at line 2841 of file NetworkOPs.cpp.
References mLock, and mRpcSubMap.
 {
     ScopedLockType sl (mLock);
     mRpcSubMap.emplace (strUrl, rspEntry);
     return rspEntry;
 }
int ripple::NetworkOPsImp::beginConsensus (uint256 const & networkClosed, Ledger::pointer closingLedger)
Definition at line 1449 of file NetworkOPs.cpp.
References beast::Journal::debug, ripple::LedgerMaster::getClosedLedger(), ripple::LedgerMaster::getCurrentLedger(), ripple::LedgerMaster::getLedgerByHash(), beast::Journal::info, m_clock, m_feeVote, m_journal, m_ledgerMaster, m_localTX, ripple::make_LedgerConsensus(), mConsensus, mMode, ripple::NetworkOPs::omFULL, ripple::NetworkOPs::omTRACKING, setMode(), and beast::Journal::warning.
Referenced by acceptLedger(), haveConsensusObject(), and tryStartConsensus().
 {
     m_journal.info << "Consensus time for ledger " << closingLedger->getLedgerSeq ();
     m_journal.info << " LCL is " << closingLedger->getParentHash ();
     Ledger::pointer prevLedger = m_ledgerMaster.getLedgerByHash (closingLedger->getParentHash ());
     if (!prevLedger)
     {
         // this shouldn't happen unless we jump ledgers
         if (mMode == omFULL)
         {
             m_journal.warning << "Don't have LCL, going to tracking";
             setMode (omTRACKING);
         }
         return 3;
     }
     assert (prevLedger->getHash () == closingLedger->getParentHash ());
     assert (closingLedger->getParentHash () == m_ledgerMaster.getClosedLedger ()->getHash ());
     // Create a consensus object to get consensus on this ledger
     assert (!mConsensus);
     prevLedger->setImmutable ();
     mConsensus = make_LedgerConsensus (m_clock, *m_localTX, networkClosed,
         prevLedger, m_ledgerMaster.getCurrentLedger ()->getCloseTimeNC (),
             *m_feeVote);
     m_journal.debug << "Initiating consensus engine";
     return mConsensus->startup ();
 }
bool ripple::NetworkOPsImp::checkLastClosedLedger (const Overlay::PeerSequence & peerList, uint256 & networkClosed)
Definition at line 1268 of file NetworkOPs.cpp.
References clearNeedNetworkLedger(), beast::Journal::debug, ripple::InboundLedgers::dropLedger(), beast::Journal::error, ripple::InboundLedger::fcCONSENSUS, ripple::InboundLedgers::findCreate(), ripple::getApp(), ripple::LedgerMaster::getClosedLedger(), ripple::Validations::getCurrentValidations(), ripple::Application::getInboundLedgers(), ripple::LedgerMaster::getLedgerByHash(), ripple::Application::getLocalCredentials(), ripple::RippleAddress::getNodeID(), ripple::LocalCredentials::getNodePublic(), ripple::Application::getValidations(), ripple::ValidationCount::highNodeUsing, ripple::ValidationCount::highValidation, beast::Journal::info, ripple::base_uint< BITS >::isNonZero(), m_journal, m_ledgerMaster, mAcquiringLedger, mMode, ripple::ValidationCount::nodesUsing, ripple::NetworkOPs::omCONNECTED, ripple::NetworkOPs::omFULL, ripple::NetworkOPs::omTRACKING, setMode(), switchLastClosedLedger(), beast::Journal::trace, ripple::ValidationCount::trustedValidations, and beast::Journal::warning.
Referenced by haveConsensusObject(), and tryStartConsensus().
 {
     // Returns true if there's an *abnormal* ledger issue, normal changing in TRACKING mode should return false
     // Do we have sufficient validations for our last closed ledger? Or do sufficient nodes
     // agree? And do we have no better ledger available?
     // If so, we are either tracking or full.
     m_journal.trace << "NetworkOPsImp::checkLastClosedLedger";
     Ledger::pointer ourClosed = m_ledgerMaster.getClosedLedger ();
     if (!ourClosed)
         return false;
     uint256 closedLedger = ourClosed->getHash ();
     uint256 prevClosedLedger = ourClosed->getParentHash ();
     m_journal.trace << "OurClosed:  " << closedLedger;
     m_journal.trace << "PrevClosed: " << prevClosedLedger;
     ripple::unordered_map<uint256, ValidationCount> ledgers;
     {
         ripple::unordered_map<uint256, currentValidationCount> current =
             getApp().getValidations ().getCurrentValidations (closedLedger, prevClosedLedger);
         typedef std::map<uint256, currentValidationCount>::value_type u256_cvc_pair;
         BOOST_FOREACH (const u256_cvc_pair & it, current)
         {
             ValidationCount& vc = ledgers[it.first];
             vc.trustedValidations += it.second.first;
             if (it.second.second > vc.highValidation)
                 vc.highValidation = it.second.second;
         }
     }
     ValidationCount& ourVC = ledgers[closedLedger];
     if (mMode >= omTRACKING)
     {
         ++ourVC.nodesUsing;
         uint160 ourAddress = getApp().getLocalCredentials ().getNodePublic ().getNodeID ();
         if (ourAddress > ourVC.highNodeUsing)
             ourVC.highNodeUsing = ourAddress;
     }
     BOOST_FOREACH (Peer::ptr const& peer, peerList)
     {
         uint256 peerLedger = peer->getClosedLedgerHash ();
         if (peerLedger.isNonZero ())
         {
             try
             {
                 ValidationCount& vc = ledgers[peerLedger];
                 if ((vc.nodesUsing == 0) || (peer->getNodePublic ().getNodeID () > vc.highNodeUsing))
                     vc.highNodeUsing = peer->getNodePublic ().getNodeID ();
                 ++vc.nodesUsing;
         }
         catch (...)
         {
             // Peer is likely not connected anymore
         }
         }
     }
     ValidationCount bestVC = ledgers[closedLedger];
     // 3) Is there a network ledger we'd like to switch to? If so, do we have it?
     bool switchLedgers = false;
     for (ripple::unordered_map<uint256, ValidationCount>::iterator it = ledgers.begin (), end = ledgers.end ();
             it != end; ++it)
     {
         m_journal.debug << "L: " << it->first << " t=" << it->second.trustedValidations <<
                                        ", n=" << it->second.nodesUsing;
         // Temporary logging to make sure tiebreaking isn't broken
         if (it->second.trustedValidations > 0)
             m_journal.trace << "  TieBreakTV: " << it->second.highValidation;
         else
         {
             if (it->second.nodesUsing > 0)
                 m_journal.trace << "  TieBreakNU: " << it->second.highNodeUsing;
         }
         if (it->second > bestVC)
         {
             bestVC = it->second;
             closedLedger = it->first;
             switchLedgers = true;
         }
     }
     if (switchLedgers && (closedLedger == prevClosedLedger))
     {
         // don't switch to our own previous ledger
         m_journal.info << "We won't switch to our own previous ledger";
         networkClosed = ourClosed->getHash ();
         switchLedgers = false;
     }
     else
         networkClosed = closedLedger;
     if (!switchLedgers)
     {
         if (mAcquiringLedger)
         {
             mAcquiringLedger->abort ();
             getApp().getInboundLedgers ().dropLedger (mAcquiringLedger->getHash ());
             mAcquiringLedger.reset ();
         }
         return false;
     }
     m_journal.warning << "We are not running on the consensus ledger";
     m_journal.info << "Our LCL: " << ourClosed->getJson (0);
     m_journal.info << "Net LCL " << closedLedger;
     if ((mMode == omTRACKING) || (mMode == omFULL))
         setMode (omCONNECTED);
     Ledger::pointer consensus = m_ledgerMaster.getLedgerByHash (closedLedger);
     if (!consensus)
     {
         m_journal.info << "Acquiring consensus ledger " << closedLedger;
         if (!mAcquiringLedger || (mAcquiringLedger->getHash () != closedLedger))
             mAcquiringLedger = getApp().getInboundLedgers ().findCreate (closedLedger, 0, InboundLedger::fcCONSENSUS);
         if (!mAcquiringLedger || mAcquiringLedger->isFailed ())
         {
             getApp().getInboundLedgers ().dropLedger (closedLedger);
             m_journal.error << "Network ledger cannot be acquired";
             return true;
         }
         if (!mAcquiringLedger->isComplete ())
             return true;
         clearNeedNetworkLedger ();
         consensus = mAcquiringLedger->getLedger ();
     }
     // FIXME: If this rewinds the ledger sequence, or has the same sequence, we should update the status on
     // any stored transactions in the invalidated ledgers.
     switchLastClosedLedger (consensus, false);
     return true;
 }
void ripple::NetworkOPsImp::clearLedgerFetch () virtual
Implements ripple::NetworkOPs.
Definition at line 2321 of file NetworkOPs.cpp.
References ripple::InboundLedgers::clearFailures(), ripple::getApp(), and ripple::Application::getInboundLedgers().
 {
     getApp().getInboundLedgers().clearFailures();
 }
void ripple::NetworkOPsImp::clearNeedNetworkLedger () inline virtual
Implements ripple::NetworkOPs.
Definition at line 277 of file NetworkOPs.cpp.
References mNeedNetworkLedger.
Referenced by checkLastClosedLedger(), and switchLastClosedLedger().
     {
         mNeedNetworkLedger = false;
     }
void ripple::NetworkOPsImp::closeTimeOffset (int offset) virtual
Implements ripple::NetworkOPs.
Definition at line 692 of file NetworkOPs.cpp.
References beast::Journal::info, m_journal, and mCloseTimeOffset.
 {
     // take large offsets, ignore small offsets, push towards our wall time
     if (offset > 1)
         mCloseTimeOffset += (offset + 3) / 4;
     else if (offset < -1)
         mCloseTimeOffset += (offset - 3) / 4;
     else
         mCloseTimeOffset = (mCloseTimeOffset * 3) / 4;
     if (mCloseTimeOffset != 0)
         m_journal.info << "Close time offset now " << mCloseTimeOffset;
 }
void ripple::NetworkOPsImp::consensusViewChange () virtual
Implements ripple::NetworkOPs.
Definition at line 1669 of file NetworkOPs.cpp.
References mMode, ripple::NetworkOPs::omCONNECTED, ripple::NetworkOPs::omFULL, ripple::NetworkOPs::omTRACKING, and setMode().
 {
     if ((mMode == omFULL) || (mMode == omTRACKING))
         setMode (omCONNECTED);
 }
void ripple::NetworkOPsImp::endConsensus (bool correctLCL) virtual
Implements ripple::NetworkOPs.
Definition at line 1651 of file NetworkOPs.cpp.
References ripple::Overlay::getActivePeers(), ripple::getApp(), ripple::LedgerMaster::getClosedLedger(), m_journal, m_ledgerMaster, mConsensus, ripple::Application::overlay(), and beast::Journal::trace.
 {
     uint256 deadLedger = m_ledgerMaster.getClosedLedger ()->getParentHash ();
     std::vector <Peer::ptr> peerList = getApp().overlay ().getActivePeers ();
     BOOST_FOREACH (Peer::ptr const& it, peerList)
     {
         if (it && (it->getClosedLedgerHash () == deadLedger))
         {
             m_journal.trace << "Killing obsolete peer status";
             it->cycleStatus ();
         }
     }
     mConsensus = boost::shared_ptr<LedgerConsensus> ();
 }
InfoSub::pointer ripple::NetworkOPsImp::findRpcSub (const std::string & strUrl) virtual
Implements ripple::InfoSub::Source.
Definition at line 2829 of file NetworkOPs.cpp.
References mLock, and mRpcSubMap.
 {
     ScopedLockType sl (mLock);
     subRpcMapType::iterator it = mRpcSubMap.find (strUrl);
     if (it != mRpcSubMap.end ())
         return it->second;
     return InfoSub::pointer ();
 }
Transaction::pointer ripple::NetworkOPsImp::findTransactionByID (uint256 const & transactionID) virtual
Implements ripple::NetworkOPs.
Definition at line 1045 of file NetworkOPs.cpp.
References ripple::Transaction::load().
 {
     return Transaction::load (transactionID);
 }
int ripple::NetworkOPsImp::findTransactionsByDestination (std::list< Transaction::pointer > & txns, const RippleAddress & destinationAccount, std::uint32_t startLedgerSeq, std::uint32_t endLedgerSeq, int maxTransactions) virtual
Implements ripple::NetworkOPs.
Definition at line 1050 of file NetworkOPs.cpp.
 {
     // WRITEME
     return 0;
 }
AccountState::pointer ripple::NetworkOPsImp::getAccountState (Ledger::ref lrLedger, const RippleAddress & accountID) virtual
Implements ripple::NetworkOPs.
Definition at line 1062 of file NetworkOPs.cpp.
 {
     return lrLedger->getAccountState (accountID);
 }
std::vector< std::pair< Transaction::pointer, TransactionMetaSet::pointer > > ripple::NetworkOPsImp::getAccountTxs (const RippleAddress & account, std::int32_t minLedger, std::int32_t maxLedger, bool descending, std::uint32_t offset, int limit, bool bAdmin) virtual
Implements ripple::NetworkOPs.
Definition at line 1811 of file NetworkOPs.cpp.
References ripple::Serializer::begin(), db, ripple::getApp(), ripple::Database::getBigInt(), ripple::Database::getBinary(), ripple::Serializer::getData(), ripple::DatabaseCon::getDB(), getLedgerBySeq(), ripple::Serializer::getLength(), ripple::Application::getTxnDB(), m_journal, meta, ripple::Serializer::resize(), SQL_FOREACH, ripple::Transaction::transactionFromSQL(), transactionsSQL(), and beast::Journal::warning.
 {
     // can be called with no locks
     std::vector< std::pair<Transaction::pointer, TransactionMetaSet::pointer> > ret;
     std::string sql = NetworkOPsImp::transactionsSQL ("AccountTransactions.LedgerSeq,Status,RawTxn,TxnMeta", account,
                       minLedger, maxLedger, descending, offset, limit, false, false, bAdmin);
     {
         Database* db = getApp().getTxnDB ()->getDB ();
         DeprecatedScopedLock sl (getApp().getTxnDB ()->getDBLock ());
         SQL_FOREACH (db, sql)
         {
             Transaction::pointer txn = Transaction::transactionFromSQL (db, false);
             Serializer rawMeta;
             int metaSize = 2048;
             rawMeta.resize (metaSize);
             metaSize = db->getBinary ("TxnMeta", &*rawMeta.begin (), rawMeta.getLength ());
             if (metaSize > rawMeta.getLength ())
             {
                 rawMeta.resize (metaSize);
                 db->getBinary ("TxnMeta", &*rawMeta.begin (), rawMeta.getLength ());
             }
             else
                 rawMeta.resize (metaSize);
             if (rawMeta.getLength() == 0)
             { // Work around a bug that could leave the metadata missing
                 std::uint32_t seq = static_cast<std::uint32_t>(db->getBigInt("LedgerSeq"));
                 m_journal.warning << "Recovering ledger " << seq << ", txn " << txn->getID();
                 Ledger::pointer ledger = getLedgerBySeq(seq);
                 if (ledger)
                     ledger->pendSaveValidated(false, false);
             }
             TransactionMetaSet::pointer meta = boost::make_shared<TransactionMetaSet> (txn->getID (), txn->getLedger (), rawMeta.getData ());
             // VFALCO NOTE Use emplace instead.
             ret.push_back (std::pair<Transaction::ref, TransactionMetaSet::ref> (txn, meta));
         }
     }
     return ret;
 }
std::vector< NetworkOPsImp::txnMetaLedgerType > ripple::NetworkOPsImp::getAccountTxsB (const RippleAddress & account, std::int32_t minLedger, std::int32_t maxLedger, bool descending, std::uint32_t offset, int limit, bool bAdmin) virtual
Implements ripple::NetworkOPs.
Definition at line 1861 of file NetworkOPs.cpp.
References db, ripple::getApp(), ripple::Database::getBinary(), ripple::DatabaseCon::getDB(), ripple::Database::getInt(), ripple::Application::getTxnDB(), SQL_FOREACH, ripple::strHex(), and transactionsSQL().
 {
     // can be called with no locks
     std::vector< txnMetaLedgerType> ret;
     std::string sql = NetworkOPsImp::transactionsSQL ("AccountTransactions.LedgerSeq,Status,RawTxn,TxnMeta", account,
                       minLedger, maxLedger, descending, offset, limit, true/*binary*/, false, bAdmin);
     {
         Database* db = getApp().getTxnDB ()->getDB ();
         DeprecatedScopedLock sl (getApp().getTxnDB ()->getDBLock ());
         SQL_FOREACH (db, sql)
         {
             int txnSize = 2048;
             Blob rawTxn (txnSize);
             txnSize = db->getBinary ("RawTxn", &rawTxn[0], rawTxn.size ());
             if (txnSize > rawTxn.size ())
             {
                 rawTxn.resize (txnSize);
                 db->getBinary ("RawTxn", &*rawTxn.begin (), rawTxn.size ());
             }
             else
                 rawTxn.resize (txnSize);
             int metaSize = 2048;
             Blob rawMeta (metaSize);
             metaSize = db->getBinary ("TxnMeta", &rawMeta[0], rawMeta.size ());
             if (metaSize > rawMeta.size ())
             {
                 rawMeta.resize (metaSize);
                 db->getBinary ("TxnMeta", &*rawMeta.begin (), rawMeta.size ());
             }
             else
                 rawMeta.resize (metaSize);
             // VFALCO TODO Change the container's type to be std::tuple so
             //             we can use std::forward_as_tuple here
             //
             ret.push_back (std::make_tuple (
                 strHex (rawTxn), strHex (rawMeta), db->getInt ("LedgerSeq")));
         }
     }
     return ret;
 }
void ripple::NetworkOPsImp::getBookPage (Ledger::pointer lpLedger, const uint160 & uTakerPaysCurrencyID, const uint160 & uTakerPaysIssuerID, const uint160 & uTakerGetsCurrencyID, const uint160 & uTakerGetsIssuerID, const uint160 & uTakerID, const bool bProof, const unsigned int iLimit, const Json::Value & jvMarker, Json::Value & jvResult) virtual
Implements ripple::NetworkOPs.
Definition at line 2855 of file NetworkOPs.cpp.
References ACCOUNT_ONE, ripple::LedgerEntrySet::accountHolds(), Json::Value::append(), Json::arrayValue, ripple::STAmount::clear(), ripple::RippleAddress::createHumanAccountID(), ripple::STAmount::createHumanCurrency(), CURRENCY_ONE, ripple::LedgerEntrySet::dirFirst(), ripple::LedgerEntrySet::dirNext(), ripple::STAmount::divide(), ripple::LedgerEntrySet::entryCache(), ripple::Ledger::getBookBase(), ripple::Ledger::getQuality(), ripple::Ledger::getQualityNext(), ripple::STAmount::getText(), ripple::ltDIR_NODE, ripple::ltOFFER, m_journal, ripple::min(), ripple::STAmount::multiply(), QUALITY_ONE, ripple::LedgerEntrySet::rippleTransferRate(), ripple::STAmount::setJson(), ripple::STAmount::setRate(), ripple::tapNONE, beast::Journal::trace, rocksdb::crc32c::Value(), and beast::Journal::warning.
 { // CAUTION: This is the old get book page logic
     Json::Value&    jvOffers    = (jvResult["offers"] = Json::Value (Json::arrayValue));
     std::map<uint160, STAmount> umBalance;
     const uint256   uBookBase   = Ledger::getBookBase (uTakerPaysCurrencyID, uTakerPaysIssuerID, uTakerGetsCurrencyID, uTakerGetsIssuerID);
     const uint256   uBookEnd    = Ledger::getQualityNext (uBookBase);
     uint256         uTipIndex   = uBookBase;
     if (m_journal.trace)
     {
         m_journal.trace << "getBookPage:" <<
             " uTakerPaysCurrencyID=" <<
                 STAmount::createHumanCurrency (uTakerPaysCurrencyID) <<
             " uTakerPaysIssuerID=" <<
                 RippleAddress::createHumanAccountID (uTakerPaysIssuerID);
         m_journal.trace << "getBookPage:" <<
             " uTakerGetsCurrencyID=" <<
                 STAmount::createHumanCurrency (uTakerGetsCurrencyID) <<
             " uTakerGetsIssuerID=" <<
                 RippleAddress::createHumanAccountID (uTakerGetsIssuerID);
         m_journal.trace << "getBookPage: uBookBase=" << uBookBase;
         m_journal.trace << "getBookPage: uBookEnd=" << uBookEnd;
         m_journal.trace << "getBookPage: uTipIndex=" << uTipIndex;
     }
     LedgerEntrySet  lesActive (lpLedger, tapNONE, true);
     bool            bDone           = false;
     bool            bDirectAdvance  = true;
     SLE::pointer    sleOfferDir;
     uint256         uOfferIndex;
     unsigned int    uBookEntry;
     STAmount        saDirRate;
     unsigned int    iLeft           = iLimit;
     if ((iLeft == 0) || (iLeft > 300))
         iLeft = 300;
     std::uint32_t  uTransferRate   = lesActive.rippleTransferRate (uTakerGetsIssuerID);
     while (!bDone && (--iLeft > 0))
     {
         if (bDirectAdvance)
         {
             bDirectAdvance  = false;
             m_journal.trace << "getBookPage: bDirectAdvance";
             sleOfferDir     = lesActive.entryCache (ltDIR_NODE, lpLedger->getNextLedgerIndex (uTipIndex, uBookEnd));
             if (!sleOfferDir)
             {
                 m_journal.trace << "getBookPage: bDone";
                 bDone           = true;
             }
             else
             {
                 uTipIndex       = sleOfferDir->getIndex ();
                 saDirRate       = STAmount::setRate (Ledger::getQuality (uTipIndex));
                 lesActive.dirFirst (uTipIndex, sleOfferDir, uBookEntry, uOfferIndex);
                 m_journal.trace << "getBookPage:   uTipIndex=" << uTipIndex;
                 m_journal.trace << "getBookPage: uOfferIndex=" << uOfferIndex;
             }
         }
         if (!bDone)
         {
             SLE::pointer    sleOffer        = lesActive.entryCache (ltOFFER, uOfferIndex);
             if (sleOffer)
             {
                 const uint160   uOfferOwnerID   = sleOffer->getFieldAccount160 (sfAccount);
                 const STAmount& saTakerGets     = sleOffer->getFieldAmount (sfTakerGets);
                 const STAmount& saTakerPays     = sleOffer->getFieldAmount (sfTakerPays);
                 STAmount        saOwnerFunds;
                 if (uTakerGetsIssuerID == uOfferOwnerID)
                 {
                     // If offer is selling issuer's own IOUs, it is fully funded.
                     saOwnerFunds    = saTakerGets;
                 }
                 else
                 {
                     std::map<uint160, STAmount>::const_iterator umBalanceEntry  = umBalance.find (uOfferOwnerID);
                     if (umBalanceEntry != umBalance.end ())
                     {
                         // Found in running balance table.
                         saOwnerFunds    = umBalanceEntry->second;
                         // m_journal.info << boost::str(boost::format("getBookPage: saOwnerFunds=%s (cached)") % saOwnerFunds.getFullText());
                     }
                     else
                     {
                         // Did not find balance in table.
                         saOwnerFunds    = lesActive.accountHolds (uOfferOwnerID, uTakerGetsCurrencyID, uTakerGetsIssuerID);
                         // m_journal.info << boost::str(boost::format("getBookPage: saOwnerFunds=%s (new)") % saOwnerFunds.getFullText());
                         if (saOwnerFunds < zero)
{
                             // Treat negative funds as zero.
                             saOwnerFunds.clear ();
                         }
                     }
                 }
                 Json::Value jvOffer = sleOffer->getJson (0);
                 STAmount    saTakerGetsFunded;
                 STAmount    saOwnerFundsLimit;
                 std::uint32_t uOfferRate;
                 if (uTransferRate != QUALITY_ONE                // Have a tranfer fee.
                         && uTakerID != uTakerGetsIssuerID           // Not taking offers of own IOUs.
                         && uTakerGetsIssuerID != uOfferOwnerID)     // Offer owner not issuing ownfunds
                 {
                     // Need to charge a transfer fee to offer owner.
                     uOfferRate          = uTransferRate;
                     saOwnerFundsLimit   = STAmount::divide (saOwnerFunds, STAmount (CURRENCY_ONE, ACCOUNT_ONE, uOfferRate, -9));
                 }
                 else
                 {
                     uOfferRate          = QUALITY_ONE;
                     saOwnerFundsLimit   = saOwnerFunds;
                 }
                 if (saOwnerFundsLimit >= saTakerGets)
                 {
                     // Sufficient funds no shenanigans.
                     saTakerGetsFunded   = saTakerGets;
                 }
                 else
                 {
                     // m_journal.info << boost::str(boost::format("getBookPage:  saTakerGets=%s") % saTakerGets.getFullText());
                     // m_journal.info << boost::str(boost::format("getBookPage:  saTakerPays=%s") % saTakerPays.getFullText());
                     // m_journal.info << boost::str(boost::format("getBookPage: saOwnerFunds=%s") % saOwnerFunds.getFullText());
                     // m_journal.info << boost::str(boost::format("getBookPage:    saDirRate=%s") % saDirRate.getText());
                     // m_journal.info << boost::str(boost::format("getBookPage:     multiply=%s") % STAmount::multiply(saTakerGetsFunded, saDirRate).getFullText());
                     // m_journal.info << boost::str(boost::format("getBookPage:     multiply=%s") % STAmount::multiply(saTakerGetsFunded, saDirRate, saTakerPays).getFullText());
                     // Only provide, if not fully funded.
                     saTakerGetsFunded   = saOwnerFundsLimit;
                     saTakerGetsFunded.setJson (jvOffer["taker_gets_funded"]);
                     std::min (saTakerPays, STAmount::multiply (saTakerGetsFunded, saDirRate, saTakerPays)).setJson (jvOffer["taker_pays_funded"]);
                 }
                 STAmount saOwnerPays = (QUALITY_ONE == uOfferRate)
                     ? saTakerGetsFunded
                     : std::min (
                         saOwnerFunds,
                         STAmount::multiply (
                             saTakerGetsFunded,
                             STAmount (CURRENCY_ONE, ACCOUNT_ONE, uOfferRate, -9)));
                 umBalance[uOfferOwnerID]    = saOwnerFunds - saOwnerPays;
                 if (saOwnerFunds != zero || uOfferOwnerID == uTakerID)
                 {
                     // Only provide funded offers and offers of the taker.
                     Json::Value& jvOf   = jvOffers.append (jvOffer);
                     jvOf["quality"]     = saDirRate.getText ();
                 }
             }
             else
             {
                 m_journal.warning << "Missing offer";
         }
             if (!lesActive.dirNext (uTipIndex, sleOfferDir, uBookEntry, uOfferIndex))
             {
                 bDirectAdvance  = true;
             }
             else
             {
                 m_journal.trace << "getBookPage: uOfferIndex=" << uOfferIndex;
             }
         }
     }
     //  jvResult["marker"]  = Json::Value(Json::arrayValue);
     //  jvResult["nodes"]   = Json::Value(Json::arrayValue);
 }
Ledger::pointer ripple::NetworkOPsImp::getClosedLedger () inline virtual
Implements ripple::NetworkOPs.
Definition at line 96 of file NetworkOPs.cpp.
References ripple::LedgerMaster::getClosedLedger(), and m_ledgerMaster.
Referenced by getServerInfo().
     {
         return m_ledgerMaster.getClosedLedger ();
     }
uint256 ripple::NetworkOPsImp::getClosedLedgerHash () inline virtual
Implements ripple::NetworkOPs.
Definition at line 119 of file NetworkOPs.cpp.
References ripple::LedgerMaster::getClosedLedger(), and m_ledgerMaster.
     {
         return m_ledgerMaster.getClosedLedger ()->getHash ();
     }
std::uint32_t ripple::NetworkOPsImp::getCloseTimeNC () virtual
Implements ripple::NetworkOPs.
Definition at line 676 of file NetworkOPs.cpp.
References getNetworkTimePT(), ripple::iToSeconds(), and mCloseTimeOffset.
Referenced by getServerInfo().
 {
     return iToSeconds (getNetworkTimePT () + boost::posix_time::seconds (mCloseTimeOffset));
 }
Json::Value ripple::NetworkOPsImp::getConsensusInfo () virtual
Implements ripple::NetworkOPs.
Definition at line 2157 of file NetworkOPs.cpp.
References mConsensus, and Json::objectValue.
 {
     if (mConsensus)
         return mConsensus->getJson (true);
     Json::Value info = Json::objectValue;
     info["consensus"] = "none";
     return info;
 }
uint256 ripple::NetworkOPsImp::getConsensusLCL () virtual
Implements ripple::NetworkOPs.
Definition at line 1512 of file NetworkOPs.cpp.
References haveConsensusObject(), and mConsensus.
 {
     if (!haveConsensusObject ())
         return uint256 ();
     return mConsensus->getLCL ();
 }
Ledger::pointer ripple::NetworkOPsImp::getCurrentLedger () inline virtual
Implements ripple::NetworkOPs.
Definition at line 108 of file NetworkOPs.cpp.
References ripple::LedgerMaster::getCurrentLedger(), and m_ledgerMaster.
     {
         return m_ledgerMaster.getCurrentLedger ();
     }
std::uint32_t ripple::NetworkOPsImp::getCurrentLedgerID () virtual
Implements ripple::NetworkOPs.
Definition at line 718 of file NetworkOPs.cpp.
References ripple::LedgerMaster::getCurrentLedger(), and m_ledgerMaster.
 {
     return m_ledgerMaster.getCurrentLedger ()->getLedgerSeq ();
 }
STVector256 ripple::NetworkOPsImp::getDirNodeInfo (Ledger::ref lrLedger, uint256 const & uRootIndex, std::uint64_t & uNodePrevious, std::uint64_t & uNodeNext) virtual
Implements ripple::NetworkOPs.
Definition at line 1080 of file NetworkOPs.cpp.
References beast::Journal::debug, beast::Journal::info, m_journal, ripple::strHex(), ripple::base_uint< BITS >::ToString(), and beast::Journal::trace.
 {
     STVector256         svIndexes;
     SLE::pointer        sleNode     = lrLedger->getDirNode (uNodeIndex);
     if (sleNode)
     {
         m_journal.debug << "getDirNodeInfo: node index: " << uNodeIndex.ToString ();
         m_journal.trace << "getDirNodeInfo: first: " << strHex (sleNode->getFieldU64 (sfIndexPrevious));
         m_journal.trace << "getDirNodeInfo:  last: " << strHex (sleNode->getFieldU64 (sfIndexNext));
         uNodePrevious   = sleNode->getFieldU64 (sfIndexPrevious);
         uNodeNext       = sleNode->getFieldU64 (sfIndexNext);
         svIndexes       = sleNode->getFieldV256 (sfIndexes);
         m_journal.trace << "getDirNodeInfo: first: " << strHex (uNodePrevious);
         m_journal.trace << "getDirNodeInfo:  last: " << strHex (uNodeNext);
     }
     else
     {
         m_journal.info << "getDirNodeInfo: node index: NOT FOUND: " << uNodeIndex.ToString ();
         uNodePrevious   = 0;
         uNodeNext       = 0;
     }
     return svIndexes;
 }
bool ripple::NetworkOPsImp::getFetchPack (uint256 const & hash, Blob & data) virtual
Implements ripple::NetworkOPs.
Definition at line 3270 of file NetworkOPs.cpp.
References ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::del(), ripple::Serializer::getSHA512Half(), m_journal, mFetchPack, ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::retrieve(), and beast::Journal::warning.
 {
     bool ret = mFetchPack.retrieve (hash, data);
     if (!ret)
         return false;
     mFetchPack.del (hash, false);
     if (hash != Serializer::getSHA512Half (data))
     {
         m_journal.warning << "Bad entry in fetch pack";
         return false;
     }
     return true;
 }
int ripple::NetworkOPsImp::getFetchSize () virtual
Implements ripple::NetworkOPs.
Definition at line 3296 of file NetworkOPs.cpp.
References ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::getCacheSize(), and mFetchPack.
 {
     return mFetchPack.getCacheSize ();
 }
bool ripple::NetworkOPsImp::getFullValidatedRange (std::uint32_t & minVal, std::uint32_t & maxVal) inline virtual
Implements ripple::NetworkOPs.
Definition at line 138 of file NetworkOPs.cpp.
References ripple::LedgerMaster::getFullValidatedRange(), and m_ledgerMaster.
     {
         return m_ledgerMaster.getFullValidatedRange (minVal, maxVal);
     }
SLE::pointer ripple::NetworkOPsImp::getGenerator (Ledger::ref lrLedger, const uint160 & uGeneratorID) virtual
Implements ripple::NetworkOPs.
Definition at line 1067 of file NetworkOPs.cpp.
 {
     if (!lrLedger)
         return SLE::pointer ();
     return lrLedger->getGenerator (uGeneratorID);
 }
std::uint32_t ripple::NetworkOPsImp::getLastCloseTime () inline virtual
Implements ripple::NetworkOPs.
Definition at line 316 of file NetworkOPs.cpp.
References mLastCloseTime.
     {
         return mLastCloseTime;
     }
SerializedValidation::ref ripple::NetworkOPsImp::getLastValidation () inline virtual
Implements ripple::NetworkOPs.
Definition at line 143 of file NetworkOPs.cpp.
References mLastValidation.
     {
         return mLastValidation;
     }
std::vector< RippleAddress > ripple::NetworkOPsImp::getLedgerAffectedAccounts (std::uint32_t ledgerSeq) virtual
Implements ripple::NetworkOPs.
Definition at line 2132 of file NetworkOPs.cpp.
References ripple::RPC::accounts(), db, ripple::getApp(), ripple::DatabaseCon::getDB(), ripple::Database::getStrBinary(), ripple::Application::getTxnDB(), ripple::RippleAddress::setAccountID(), and SQL_FOREACH.
 {
     std::vector<RippleAddress> accounts;
     std::string sql = str (boost::format
                            ("SELECT DISTINCT Account FROM AccountTransactions INDEXED BY AcctLgrIndex WHERE LedgerSeq = '%u';")
                            % ledgerSeq);
     RippleAddress acct;
     {
         Database* db = getApp().getTxnDB ()->getDB ();
         DeprecatedScopedLock sl (getApp().getTxnDB ()->getDBLock ());
         SQL_FOREACH (db, sql)
         {
             if (acct.setAccountID (db->getStrBinary ("Account")))
                 accounts.push_back (acct);
         }
     }
     return accounts;
 }
Ledger::pointer ripple::NetworkOPsImp::getLedgerByHash (uint256 const & hash) inline virtual
Implements ripple::NetworkOPs.
Definition at line 112 of file NetworkOPs.cpp.
References ripple::LedgerMaster::getLedgerByHash(), and m_ledgerMaster.
Referenced by makeFetchPack().
     {
         return m_ledgerMaster.getLedgerByHash (hash);
     }
Ledger::pointer ripple::NetworkOPsImp::getLedgerBySeq (const std::uint32_t seq) virtual
Implements ripple::NetworkOPs.
Definition at line 713 of file NetworkOPs.cpp.
References ripple::LedgerMaster::getLedgerBySeq(), and m_ledgerMaster.
Referenced by getAccountTxs(), and getTxsAccount().
 {
     return m_ledgerMaster.getLedgerBySeq (seq);
 }
Json::Value ripple::NetworkOPsImp::getLedgerFetchInfo () virtual
Implements ripple::NetworkOPs.
Definition at line 2326 of file NetworkOPs.cpp.
References ripple::getApp(), ripple::Application::getInboundLedgers(), and ripple::InboundLedgers::getInfo().
 {
     return getApp().getInboundLedgers().getInfo();
 }
std::uint32_t ripple::NetworkOPsImp::getLedgerID (uint256 const & hash) virtual
Implements ripple::NetworkOPs.
Definition at line 706 of file NetworkOPs.cpp.
References ripple::LedgerMaster::getLedgerByHash(), and m_ledgerMaster.
 {
     Ledger::pointer  lrLedger   = m_ledgerMaster.getLedgerByHash (hash);
     return lrLedger ? lrLedger->getLedgerSeq () : 0;
 }
std::size_t ripple::NetworkOPsImp::getLocalTxCount () inline override virtual
Implements ripple::NetworkOPs.
Definition at line 346 of file NetworkOPs.cpp.
References m_localTX.
     {
         return m_localTX->size ();
     }
std::uint32_t ripple::NetworkOPsImp::getNetworkTimeNC () virtual
Implements ripple::NetworkOPs.
Definition at line 671 of file NetworkOPs.cpp.
References getNetworkTimePT(), and ripple::iToSeconds().
Referenced by getValidationTimeNC(), processClusterTimer(), processTransactionCb(), runTransactionQueue(), switchLastClosedLedger(), and tryStartConsensus().
 {
     return iToSeconds (getNetworkTimePT ());
 }
boost::posix_time::ptime ripple::NetworkOPsImp::getNetworkTimePT () virtual
Implements ripple::NetworkOPs.
Definition at line 661 of file NetworkOPs.cpp.
References ripple::getApp(), and ripple::Application::getSystemTimeOffset().
Referenced by getCloseTimeNC(), and getNetworkTimeNC().
 {
     int offset = 0;
     getApp().getSystemTimeOffset (offset);
     // VFALCO TODO Replace this with a beast call
     return boost::posix_time::microsec_clock::universal_time () + boost::posix_time::seconds (offset);
 }
OperatingMode ripple::NetworkOPsImp::getOperatingMode () inline virtual
Implements ripple::NetworkOPs.
Definition at line 90 of file NetworkOPs.cpp.
References mMode.
     {
         return mMode;
     }
Json::Value ripple::NetworkOPsImp::getOwnerInfo (Ledger::pointer lpLedger, const RippleAddress & naAccount) virtual
Implements ripple::NetworkOPs.
Definition at line 1129 of file NetworkOPs.cpp.
References Json::Value::append(), Json::arrayValue, ripple::RippleAddress::getAccountID(), ripple::Ledger::getDirNodeIndex(), Json::Value::isMember(), ripple::ltACCOUNT_ROOT, ripple::ltDIR_NODE, ripple::ltGENERATOR_MAP, ripple::ltNICKNAME, ripple::ltOFFER, ripple::ltRIPPLE_STATE, Json::objectValue, and ripple::STVector256::peekValue().
Referenced by pubBootstrapAccountInfo().
 {
     Json::Value jvObjects (Json::objectValue);
     uint256             uRootIndex  = lpLedger->getOwnerDirIndex (naAccount.getAccountID ());
     SLE::pointer        sleNode     = lpLedger->getDirNode (uRootIndex);
     if (sleNode)
     {
         std::uint64_t  uNodeDir;
         do
         {
             STVector256                 svIndexes   = sleNode->getFieldV256 (sfIndexes);
             const std::vector<uint256>& vuiIndexes  = svIndexes.peekValue ();
             BOOST_FOREACH (uint256 const & uDirEntry, vuiIndexes)
             {
                 SLE::pointer        sleCur      = lpLedger->getSLEi (uDirEntry);
                 switch (sleCur->getType ())
                 {
                 case ltOFFER:
                     if (!jvObjects.isMember ("offers"))
                         jvObjects["offers"]         = Json::Value (Json::arrayValue);
                     jvObjects["offers"].append (sleCur->getJson (0));
                     break;
                 case ltRIPPLE_STATE:
                     if (!jvObjects.isMember ("ripple_lines"))
                         jvObjects["ripple_lines"]   = Json::Value (Json::arrayValue);
                     jvObjects["ripple_lines"].append (sleCur->getJson (0));
                     break;
                 case ltACCOUNT_ROOT:
                 case ltDIR_NODE:
                 case ltGENERATOR_MAP:
                 case ltNICKNAME:
                 default:
                     assert (false);
                     break;
                 }
             }
             uNodeDir        = sleNode->getFieldU64 (sfIndexNext);
             if (uNodeDir)
             {
                 sleNode = lpLedger->getDirNode (Ledger::getDirNodeIndex (uRootIndex, uNodeDir));
                 assert (sleNode);
             }
         }
         while (uNodeDir);
     }
     return jvObjects;
 }
int ripple::NetworkOPsImp::getPreviousConvergeTime () inline virtual
Implements ripple::NetworkOPs.
Definition at line 312 of file NetworkOPs.cpp.
References mLastCloseConvergeTime.
Referenced by getServerInfo().
     {
         return mLastCloseConvergeTime;
     }
int ripple::NetworkOPsImp::getPreviousProposers () inline virtual
Implements ripple::NetworkOPs.
Definition at line 308 of file NetworkOPs.cpp.
References mLastCloseProposers.
Referenced by haveConsensusObject().
     {
         return mLastCloseProposers;
     }
Ledger::pointer ripple::NetworkOPsImp::getPublishedLedger () inline virtual
Implements ripple::NetworkOPs.
Definition at line 104 of file NetworkOPs.cpp.
References ripple::LedgerMaster::getPublishedLedger(), and m_ledgerMaster.
Referenced by getServerInfo().
     {
         return m_ledgerMaster.getPublishedLedger ();
     }
Json::Value ripple::NetworkOPsImp::getServerInfo (bool human, bool admin) virtual
Implements ripple::NetworkOPs.
Definition at line 2168 of file NetworkOPs.cpp.
References base, ripple::getApp(), ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::getCacheSize(), getClosedLedger(), getCloseTimeNC(), ripple::LoadFeeTrack::getClusterFee(), ripple::LedgerMaster::getCompleteLedgers(), beast::SystemStats::getComputerName(), ripple::getConfig(), ripple::Application::getFeeTrack(), ripple::Application::getJobQueue(), ripple::JobQueue::getJson(), ripple::Application::getLedgerMaster(), ripple::LoadFeeTrack::getLoadBase(), ripple::LoadFeeTrack::getLoadFactor(), ripple::Application::getLocalCredentials(), ripple::LoadFeeTrack::getLocalFee(), ripple::LedgerMaster::getMinValidations(), ripple::LocalCredentials::getNodePublic(), ripple::Application::getOPs(), ripple::NetworkOPs::getPreviousConvergeTime(), getPreviousConvergeTime(), ripple::NetworkOPs::getPreviousProposers(), getPublishedLedger(), ripple::LoadFeeTrack::getRemoteFee(), getValidatedLedger(), ripple::BuildInfo::getVersionString(), ripple::RFC1751::getWordFromBlob(), ripple::RippleAddress::humanNodePublic(), m_ledgerMaster, mFeatureBlocked, mFetchPack, mNeedNetworkLedger, Json::objectValue, strOperatingMode(), SYSTEM_CURRENCY_PARTS, and ripple::Config::VALIDATION_PUB.
 {
     Json::Value info = Json::objectValue;
     // hostid: unique string describing the machine
     if (human)
     {
         if (! admin)
         {
             // For a non admin connection, hash the node ID into a single RFC1751 word
             Blob const& addr (getApp().getLocalCredentials ().getNodePublic ().getNodePublic ());
             info ["hostid"] = RFC1751::getWordFromBlob (addr.data (), addr.size ());
         }
         else
         {
             // Only admins get the hostname for security reasons
             info ["hostid"] = beast::SystemStats::getComputerName();
         }
     }
     info ["build_version"] = BuildInfo::getVersionString ();
     info["server_state"] = strOperatingMode ();
     if (mNeedNetworkLedger)
         info["network_ledger"] = "waiting";
     info["validation_quorum"] = m_ledgerMaster.getMinValidations ();
     if (admin)
     {
         if (getConfig ().VALIDATION_PUB.isValid ())
             info["pubkey_validator"] = getConfig ().VALIDATION_PUB.humanNodePublic ();
         else
             info["pubkey_validator"] = "none";
     }
     info["pubkey_node"] = getApp().getLocalCredentials ().getNodePublic ().humanNodePublic ();
     info["complete_ledgers"] = getApp().getLedgerMaster ().getCompleteLedgers ();
     if (mFeatureBlocked)
         info["feature_blocked"] = true;
     size_t fp = mFetchPack.getCacheSize ();
     if (fp != 0)
         info["fetch_pack"] = Json::UInt (fp);
     info["peers"] = Json::UInt (getApp ().overlay ().size ());
     Json::Value lastClose = Json::objectValue;
     lastClose["proposers"] = getApp().getOPs ().getPreviousProposers ();
     if (human)
         lastClose["converge_time_s"] = static_cast<double> (getApp().getOPs ().getPreviousConvergeTime ()) / 1000.0;
     else
         lastClose["converge_time"] = Json::Int (getApp().getOPs ().getPreviousConvergeTime ());
     info["last_close"] = lastClose;
     //  if (mConsensus)
     //      info["consensus"] = mConsensus->getJson();
     if (admin)
         info["load"] = getApp().getJobQueue ().getJson ();
     if (!human)
     {
         info["load_base"] = getApp().getFeeTrack ().getLoadBase ();
         info["load_factor"] = getApp().getFeeTrack ().getLoadFactor ();
     }
     else
     {
         info["load_factor"] =
             static_cast<double> (getApp().getFeeTrack ().getLoadFactor ()) / getApp().getFeeTrack ().getLoadBase ();
         if (admin)
         {
             std::uint32_t base = getApp().getFeeTrack().getLoadBase();
             std::uint32_t fee = getApp().getFeeTrack().getLocalFee();
             if (fee != base)
                 info["load_factor_local"] =
                     static_cast<double> (fee) / base;
             fee = getApp().getFeeTrack ().getRemoteFee();
             if (fee != base)
                 info["load_factor_net"] =
                     static_cast<double> (fee) / base;
             fee = getApp().getFeeTrack().getClusterFee();
             if (fee != base)
                 info["load_factor_cluster"] =
                     static_cast<double> (fee) / base;
         }
     }
     bool valid = false;
     Ledger::pointer lpClosed    = getValidatedLedger ();
     if (lpClosed)
         valid = true;
     else
         lpClosed                = getClosedLedger ();
     if (lpClosed)
     {
         std::uint64_t baseFee = lpClosed->getBaseFee ();
         std::uint64_t baseRef = lpClosed->getReferenceFeeUnits ();
         Json::Value l (Json::objectValue);
         l["seq"]                = Json::UInt (lpClosed->getLedgerSeq ());
         l["hash"]               = lpClosed->getHash ().GetHex ();
         if (!human)
         {
             l["base_fee"]       = Json::Value::UInt (baseFee);
             l["reserve_base"]   = Json::Value::UInt (lpClosed->getReserve (0));
             l["reserve_inc"]    = Json::Value::UInt (lpClosed->getReserveInc ());
             l["close_time"]     = Json::Value::UInt (lpClosed->getCloseTimeNC ());
         }
         else
         {
             l["base_fee_xrp"]       = static_cast<double> (baseFee) / SYSTEM_CURRENCY_PARTS;
             l["reserve_base_xrp"]   =
                 static_cast<double> (Json::UInt (lpClosed->getReserve (0) * baseFee / baseRef)) / SYSTEM_CURRENCY_PARTS;
             l["reserve_inc_xrp"]    =
                 static_cast<double> (Json::UInt (lpClosed->getReserveInc () * baseFee / baseRef)) / SYSTEM_CURRENCY_PARTS;
             std::uint32_t closeTime = getCloseTimeNC ();
             std::uint32_t lCloseTime = lpClosed->getCloseTimeNC ();
             if (lCloseTime <= closeTime)
             {
                 std::uint32_t age = closeTime - lCloseTime;
                 if (age < 1000000)
                     l["age"]            = Json::UInt (age);
             }
         }
         if (valid)
             info["validated_ledger"] = l;
         else
             info["closed_ledger"] = l;
         Ledger::pointer lpPublished = getPublishedLedger ();
         if (!lpPublished)
             info["published_ledger"] = "none";
         else if (lpPublished->getLedgerSeq() != lpClosed->getLedgerSeq())
             info["published_ledger"] = lpPublished->getLedgerSeq();
     }
     return info;
 }
SLE::pointer ripple::NetworkOPsImp::getSLE (Ledger::pointer lpLedger, uint256 const & uHash) inline virtual
Implements ripple::NetworkOPs.
Definition at line 152 of file NetworkOPs.cpp.
     {
         return lpLedger->getSLE (uHash);
     }
SLE::pointer ripple::NetworkOPsImp::getSLEi (Ledger::pointer lpLedger, uint256 const & uHash) inline virtual
Implements ripple::NetworkOPs.
Definition at line 156 of file NetworkOPs.cpp.
     {
         return lpLedger->getSLEi (uHash);
     }
SHAMap::pointer ripple::NetworkOPsImp::getTXMap (uint256 const & hash) virtual
Implements ripple::NetworkOPs.
Definition at line 1577 of file NetworkOPs.cpp.
References haveConsensusObject(), rocksdb::if(), mConsensus, and mRecentPositions.
 {
     std::map<uint256, std::pair<int, SHAMap::pointer> >::iterator it = mRecentPositions.find (hash);
     if (it != mRecentPositions.end ())
         return it->second.second;
     if (!haveConsensusObject ())
         return SHAMap::pointer ();
     return mConsensus->getTransactionTree (hash, false);
 }
std::vector< std::pair< Transaction::pointer, TransactionMetaSet::pointer > > ripple::NetworkOPsImp::getTxsAccount (const RippleAddress & account, std::int32_t minLedger, std::int32_t maxLedger, bool forward, Json::Value & token, int limit, bool bAdmin) virtual
Implements ripple::NetworkOPs.
Definition at line 1914 of file NetworkOPs.cpp.
References Json::Value::asInt(), ripple::Serializer::begin(), db, ripple::getApp(), ripple::Database::getBigInt(), ripple::Database::getBinary(), ripple::Serializer::getData(), ripple::DatabaseCon::getDB(), ripple::Database::getInt(), getLedgerBySeq(), ripple::Serializer::getLength(), ripple::Application::getTxnDB(), ripple::RippleAddress::humanAccountID(), Json::Value::isMember(), Json::Value::isNull(), Json::Value::isObject(), m_journal, meta, Json::nullValue, Json::objectValue, ripple::Serializer::resize(), SQL_FOREACH, ripple::Transaction::transactionFromSQL(), and beast::Journal::warning.
 {
     std::vector< std::pair<Transaction::pointer, TransactionMetaSet::pointer> > ret;
     std::uint32_t NONBINARY_PAGE_LENGTH = 200;
     std::uint32_t EXTRA_LENGTH = 20;
     bool foundResume = token.isNull() || !token.isObject();
     std::uint32_t numberOfResults, queryLimit;
     if (limit <= 0)
         numberOfResults = NONBINARY_PAGE_LENGTH;
     else if (!bAdmin && (limit > NONBINARY_PAGE_LENGTH))
         numberOfResults = NONBINARY_PAGE_LENGTH;
     else
         numberOfResults = limit;
     queryLimit = numberOfResults + 1 + (foundResume ? 0 : EXTRA_LENGTH);
     std::uint32_t findLedger = 0, findSeq = 0;
     if (!foundResume)
     {
         try
         {
             if (!token.isMember("ledger") || !token.isMember("seq"))
                 return ret;
             findLedger = token["ledger"].asInt();
             findSeq = token["seq"].asInt();
         }
         catch (...)
         {
             return ret;
         }
     }
     // ST NOTE We're using the token reference both for passing inputs and
     //         outputs, so we need to clear it in between.
     token = Json::nullValue;
     std::string sql = boost::str (boost::format
         ("SELECT AccountTransactions.LedgerSeq,AccountTransactions.TxnSeq,Status,RawTxn,TxnMeta "
          "FROM AccountTransactions INNER JOIN Transactions ON Transactions.TransID = AccountTransactions.TransID "
          "WHERE AccountTransactions.Account = '%s' AND AccountTransactions.LedgerSeq BETWEEN '%u' AND '%u' "
          "ORDER BY AccountTransactions.LedgerSeq %s, AccountTransactions.TxnSeq %s, AccountTransactions.TransID %s "
          "LIMIT %u;")
              % account.humanAccountID()
              % ((forward && (findLedger != 0)) ? findLedger : minLedger)
              % ((!forward && (findLedger != 0)) ? findLedger: maxLedger)
              % (forward ? "ASC" : "DESC")
              % (forward ? "ASC" : "DESC")
              % (forward ? "ASC" : "DESC")
              % queryLimit);
     {
         Database* db = getApp().getTxnDB ()->getDB ();
         DeprecatedScopedLock sl (getApp().getTxnDB ()->getDBLock ());
         SQL_FOREACH (db, sql)
         {
             if (!foundResume)
             {
                 if ((findLedger == db->getInt("LedgerSeq")) && (findSeq == db->getInt("TxnSeq")))
                     foundResume = true;
             }
             else if (numberOfResults == 0)
             {
                 token = Json::objectValue;
                 token["ledger"] = db->getInt("LedgerSeq");
                 token["seq"] = db->getInt("TxnSeq");
                 break;
             }
             if (foundResume)
             {
                 Transaction::pointer txn = Transaction::transactionFromSQL (db, false);
                 Serializer rawMeta;
                 int metaSize = 2048;
                 rawMeta.resize (metaSize);
                 metaSize = db->getBinary ("TxnMeta", &*rawMeta.begin (), rawMeta.getLength ());
                 if (metaSize > rawMeta.getLength ())
                 {
                     rawMeta.resize (metaSize);
                     db->getBinary ("TxnMeta", &*rawMeta.begin (), rawMeta.getLength ());
                 }
                 else
                     rawMeta.resize (metaSize);
                 if (rawMeta.getLength() == 0)
                 { // Work around a bug that could leave the metadata missing
                     std::uint32_t seq = static_cast<std::uint32_t>(db->getBigInt("LedgerSeq"));
                     m_journal.warning << "Recovering ledger " << seq << ", txn " << txn->getID();
                     Ledger::pointer ledger = getLedgerBySeq(seq);
                     if (ledger)
                         ledger->pendSaveValidated(false, false);
                 }
                 --numberOfResults;
                 TransactionMetaSet::pointer meta = boost::make_shared<TransactionMetaSet> (txn->getID (), txn->getLedger (), rawMeta.getData ());
                 ret.push_back (std::pair<Transaction::ref, TransactionMetaSet::ref> (txn, meta));
             }
         }
     }
     return ret;
 }
std::vector< NetworkOPsImp::txnMetaLedgerType > ripple::NetworkOPsImp::getTxsAccountB (const RippleAddress & account, std::int32_t minLedger, std::int32_t maxLedger, bool forward, Json::Value & token, int limit, bool bAdmin) virtual
Implements ripple::NetworkOPs.
Definition at line 2024 of file NetworkOPs.cpp.
References Json::Value::asInt(), db, ripple::getApp(), ripple::Database::getBinary(), ripple::DatabaseCon::getDB(), ripple::Database::getInt(), ripple::Application::getTxnDB(), ripple::RippleAddress::humanAccountID(), Json::Value::isMember(), Json::Value::isNull(), Json::Value::isObject(), Json::nullValue, Json::objectValue, SQL_FOREACH, and ripple::strHex().
 {
     std::vector<txnMetaLedgerType> ret;
     std::uint32_t BINARY_PAGE_LENGTH = 500;
     std::uint32_t EXTRA_LENGTH = 20;
     bool foundResume = token.isNull() || !token.isObject();
     std::uint32_t numberOfResults, queryLimit;
     if (limit <= 0)
         numberOfResults = BINARY_PAGE_LENGTH;
     else if (!bAdmin && (limit > BINARY_PAGE_LENGTH))
         numberOfResults = BINARY_PAGE_LENGTH;
     else
         numberOfResults = limit;
     queryLimit = numberOfResults + 1 + (foundResume ? 0 : EXTRA_LENGTH);
     std::uint32_t findLedger = 0, findSeq = 0;
     if (!foundResume)
     {
         try
         {
             if (!token.isMember("ledger") || !token.isMember("seq"))
                 return ret;
             findLedger = token["ledger"].asInt();
             findSeq = token["seq"].asInt();
         }
         catch (...)
         {
             return ret;
         }
     }
     token = Json::nullValue;
     std::string sql = boost::str (boost::format
         ("SELECT AccountTransactions.LedgerSeq,AccountTransactions.TxnSeq,Status,RawTxn,TxnMeta "
          "FROM AccountTransactions INNER JOIN Transactions ON Transactions.TransID = AccountTransactions.TransID "
          "WHERE AccountTransactions.Account = '%s' AND AccountTransactions.LedgerSeq BETWEEN '%u' AND '%u' "
          "ORDER BY AccountTransactions.LedgerSeq %s, AccountTransactions.TxnSeq %s, AccountTransactions.TransID %s "
          "LIMIT %u;")
              % account.humanAccountID()
              % ((forward && (findLedger != 0)) ? findLedger : minLedger)
              % ((!forward && (findLedger != 0)) ? findLedger: maxLedger)
              % (forward ? "ASC" : "DESC")
              % (forward ? "ASC" : "DESC")
              % (forward ? "ASC" : "DESC")
              % queryLimit);
     {
         Database* db = getApp().getTxnDB ()->getDB ();
         DeprecatedScopedLock sl (getApp().getTxnDB ()->getDBLock ());
         SQL_FOREACH (db, sql)
         {
             if (!foundResume)
             {
                 if ((findLedger == db->getInt("LedgerSeq")) && (findSeq == db->getInt("TxnSeq")))
                     foundResume = true;
             }
             else if (numberOfResults == 0)
             {
                 token = Json::objectValue;
                 token["ledger"] = db->getInt("LedgerSeq");
                 token["seq"] = db->getInt("TxnSeq");
                 break;
             }
             if (foundResume)
             {
                 int txnSize = 2048;
                 Blob rawTxn (txnSize);
                 txnSize = db->getBinary ("RawTxn", &rawTxn[0], rawTxn.size ());
                 if (txnSize > rawTxn.size ())
                 {
                     rawTxn.resize (txnSize);
                     db->getBinary ("RawTxn", &*rawTxn.begin (), rawTxn.size ());
                 }
                 else
                     rawTxn.resize (txnSize);
                 int metaSize = 2048;
                 Blob rawMeta (metaSize);
                 metaSize = db->getBinary ("TxnMeta", &rawMeta[0], rawMeta.size ());
                 if (metaSize > rawMeta.size ())
                 {
                     rawMeta.resize (metaSize);
                     db->getBinary ("TxnMeta", &*rawMeta.begin (), rawMeta.size ());
                 }
                 else
                     rawMeta.resize (metaSize);
                 ret.push_back (std::make_tuple (
                     strHex (rawTxn), strHex (rawMeta), db->getInt ("LedgerSeq")));
                 --numberOfResults;
             }
         }
     }
     return ret;
 }
Ledger::pointer ripple::NetworkOPsImp::getValidatedLedger () inline virtual
Implements ripple::NetworkOPs.
Definition at line 100 of file NetworkOPs.cpp.
References ripple::LedgerMaster::getValidatedLedger(), and m_ledgerMaster.
Referenced by getServerInfo(), and subLedger().
     {
         return m_ledgerMaster.getValidatedLedger ();
     }
bool ripple::NetworkOPsImp::getValidatedRange (std::uint32_t & minVal, std::uint32_t & maxVal) inline virtual
Implements ripple::NetworkOPs.
Definition at line 134 of file NetworkOPs.cpp.
References ripple::LedgerMaster::getValidatedRange(), and m_ledgerMaster.
     {
         return m_ledgerMaster.getValidatedRange (minVal, maxVal);
     }
std::uint32_t ripple::NetworkOPsImp::getValidatedSeq () virtual
Implements ripple::NetworkOPs.
Definition at line 733 of file NetworkOPs.cpp.
References ripple::LedgerMaster::getValidatedLedger(), and m_ledgerMaster.
 {
     return m_ledgerMaster.getValidatedLedger ()->getLedgerSeq ();
 }
std::uint32_t ripple::NetworkOPsImp::getValidationTimeNC () virtual
Implements ripple::NetworkOPs.
Definition at line 681 of file NetworkOPs.cpp.
References getNetworkTimeNC(), and mLastValidationTime.
 {
     std::uint32_t vt = getNetworkTimeNC ();
     if (vt <= mLastValidationTime)
         vt = mLastValidationTime + 1;
     mLastValidationTime = vt;
     return vt;
 }
void ripple::NetworkOPsImp::gotFetchPack (bool progress, std::uint32_t seq) virtual
Implements ripple::NetworkOPs.
Definition at line 3301 of file NetworkOPs.cpp.
References ripple::JobQueue::addJob(), BIND_TYPE, ripple::getApp(), ripple::Application::getJobQueue(), ripple::InboundLedgers::gotFetchPack(), ripple::jtLEDGER_DATA, and P_1.
 {
     // FIXME: Calling this function more than once will result in
     // InboundLedgers::gotFetchPack being called more than once
     // which is expensive. A flag should track whether we've already dispatched
     getApp().getJobQueue ().addJob (jtLEDGER_DATA, "gotFetchPack",
                                    BIND_TYPE (&InboundLedgers::gotFetchPack, &getApp().getInboundLedgers (), P_1));
 }
SHAMapAddNode ripple::NetworkOPsImp::gotTXData (const boost::shared_ptr< Peer > & peer, uint256 const & hash, const std::list< SHAMapNode > & nodeIDs, const std::list< Blob > & nodeData) virtual
Implements ripple::NetworkOPs.
Definition at line 1613 of file NetworkOPs.cpp.
References m_journal, mConsensus, and beast::Journal::warning.
 {
     if (!mConsensus)
     {
         m_journal.warning << "Got TX data with no consensus object";
         return SHAMapAddNode ();
     }
     return mConsensus->peerGaveNodes (peer, hash, nodeIDs, nodeData);
 }
bool ripple::NetworkOPsImp::hasTXSet (const boost::shared_ptr< Peer > & peer, uint256 const & set, protocol::TxSetStatus status) virtual
Implements ripple::NetworkOPs.
Definition at line 1626 of file NetworkOPs.cpp.
References beast::Journal::info, m_journal, and mConsensus.
 {
     if (mConsensus == nullptr)
     {
         m_journal.info << "Peer has TX set, not during consensus";
         return false;
     }
     return mConsensus->peerHasSet (peer, set, status);
 }
bool ripple::NetworkOPsImp::haveConsensusObject () private
Definition at line 1483 of file NetworkOPs.cpp.
References beginConsensus(), checkLastClosedLedger(), ripple::Overlay::getActivePeers(), ripple::getApp(), ripple::LedgerMaster::getCurrentLedger(), ripple::LedgerMaster::getMinValidations(), getPreviousProposers(), beast::Journal::info, m_journal, m_ledgerMaster, mConsensus, mMode, ripple::NetworkOPs::omFULL, ripple::NetworkOPs::omSYNCING, ripple::NetworkOPs::omTRACKING, ripple::Application::overlay(), setMode(), and tryStartConsensus().
Referenced by getConsensusLCL(), getTXMap(), mapComplete(), and processTrustedProposal().
 {
     if (mConsensus != nullptr)
         return true;
     if ((mMode == omFULL) || (mMode == omTRACKING))
     {
         tryStartConsensus ();
     }
     else
     {
         // we need to get into the consensus process
         uint256 networkClosed;
         Overlay::PeerSequence peerList = getApp().overlay ().getActivePeers ();
         bool ledgerChange = checkLastClosedLedger (peerList, networkClosed);
         if (!ledgerChange)
         {
             m_journal.info << "Beginning consensus due to peer action";
             if ( ((mMode == omTRACKING) || (mMode == omSYNCING)) &&
                  (getPreviousProposers() >= m_ledgerMaster.getMinValidations()) )
                 setMode (omFULL);
             beginConsensus (networkClosed, m_ledgerMaster.getCurrentLedger ());
         }
     }
     return mConsensus != nullptr;
 }
bool ripple::NetworkOPsImp::haveLedger (std::uint32_t seq) virtual
Implements ripple::NetworkOPs.
Definition at line 728 of file NetworkOPs.cpp.
References ripple::LedgerMaster::haveLedger(), and m_ledgerMaster.
Referenced by isValidated().
 {
     return m_ledgerMaster.haveLedger (seq);
 }
bool ripple::NetworkOPsImp::haveLedgerRange (std::uint32_t from, std::uint32_t to) virtual
Implements ripple::NetworkOPs.
Definition at line 723 of file NetworkOPs.cpp.
References ripple::LedgerMaster::haveLedgerRange(), and m_ledgerMaster.
 {
     return m_ledgerMaster.haveLedgerRange (from, to);
 }
bool ripple::NetworkOPsImp::isFeatureBlocked () inline virtual
Implements ripple::NetworkOPs.
Definition at line 302 of file NetworkOPs.cpp.
References mFeatureBlocked.
     {
         return mFeatureBlocked;
     }
bool ripple::NetworkOPsImp::isFull () inline virtual
Implements ripple::NetworkOPs.
Definition at line 285 of file NetworkOPs.cpp.
References mMode, mNeedNetworkLedger, and ripple::NetworkOPs::omFULL.
     {
         return !mNeedNetworkLedger && (mMode == omFULL);
     }
bool ripple::NetworkOPsImp::isNeedNetworkLedger () inline virtual
Implements ripple::NetworkOPs.
Definition at line 281 of file NetworkOPs.cpp.
References mNeedNetworkLedger.
Referenced by subLedger().
     {
         return mNeedNetworkLedger;
     }
bool ripple::NetworkOPsImp::isProposing () inline virtual
Implements ripple::NetworkOPs.
Definition at line 294 of file NetworkOPs.cpp.
References mProposing.
     {
         return mProposing;
     }
bool ripple::NetworkOPsImp::isValidated (std::uint32_t seq) virtual
Implements ripple::NetworkOPs.
Definition at line 746 of file NetworkOPs.cpp.
References ripple::LedgerMaster::getValidatedLedger(), haveLedger(), and m_ledgerMaster.
Referenced by isValidated().
 {
     // use when ledger was retrieved by seq
     return haveLedger (seq) && (seq <= m_ledgerMaster.getValidatedLedger ()->getLedgerSeq ());
 }
bool ripple::NetworkOPsImp::isValidated (std::uint32_t seq, uint256 const & hash) virtual
Implements ripple::NetworkOPs.
Definition at line 738 of file NetworkOPs.cpp.
References ripple::LedgerMaster::getHashBySeq(), hash, isValidated(), and m_ledgerMaster.
 {
     if (!isValidated (seq))
         return false;
     return m_ledgerMaster.getHashBySeq (seq) == hash;
 }
bool ripple::NetworkOPsImp::isValidated (Ledger::ref l) inline virtual
Implements ripple::NetworkOPs.
Definition at line 130 of file NetworkOPs.cpp.
References isValidated().
     {
         return isValidated (l->getLedgerSeq (), l->getHash ());
     }
bool ripple::NetworkOPsImp::isValidating () inline virtual
Implements ripple::NetworkOPs.
Definition at line 298 of file NetworkOPs.cpp.
References mValidating.
     {
         return mValidating;
     }
void ripple::NetworkOPsImp::makeFetchPack (Job & , boost::weak_ptr< Peer > peer, boost::shared_ptr< protocol::TMGetObjectByHash > request, Ledger::pointer wantLedger, Ledger::pointer haveLedger, std::uint32_t uUptime) virtual
Implements ripple::NetworkOPs.
Definition at line 3189 of file NetworkOPs.cpp.
References ripple::Serializer::add32(), BIND_TYPE, ripple::fpAppender(), ripple::getApp(), ripple::Serializer::getDataPtr(), ripple::UptimeTimer::getInstance(), getLedgerByHash(), ripple::Serializer::getLength(), beast::Journal::info, ripple::HashPrefix::ledgerMaster, m_journal, P_1, P_2, and beast::Journal::warning.
 {
     if (UptimeTimer::getInstance ().getElapsedSeconds () > (uUptime + 1))
     {
         m_journal.info << "Fetch pack request got stale";
         return;
     }
     if (getApp().getFeeTrack ().isLoadedLocal ())
     {
         m_journal.info << "Too busy to make fetch pack";
         return;
     }
     try
     {
         Peer::ptr peer = wPeer.lock ();
         if (!peer)
             return;
         protocol::TMGetObjectByHash reply;
         reply.set_query (false);
         if (request->has_seq ())
             reply.set_seq (request->seq ());
         reply.set_ledgerhash (request->ledgerhash ());
         reply.set_type (protocol::TMGetObjectByHash::otFETCH_PACK);
         do
         {
             std::uint32_t lSeq = wantLedger->getLedgerSeq ();
             protocol::TMIndexedObject& newObj = *reply.add_objects ();
             newObj.set_hash (wantLedger->getHash ().begin (), 256 / 8);
             Serializer s (256);
             s.add32 (HashPrefix::ledgerMaster);
             wantLedger->addRaw (s);
             newObj.set_data (s.getDataPtr (), s.getLength ());
             newObj.set_ledgerseq (lSeq);
             wantLedger->peekAccountStateMap ()->getFetchPack (haveLedger->peekAccountStateMap ().get (), true, 1024,
                     BIND_TYPE (fpAppender, &reply, lSeq, P_1, P_2));
             if (wantLedger->getTransHash ().isNonZero ())
                 wantLedger->peekTransactionMap ()->getFetchPack (nullptr, true, 256,
                         BIND_TYPE (fpAppender, &reply, lSeq, P_1, P_2));
             if (reply.objects ().size () >= 256)
                 break;
             // VFALCO NOTE Why use move?
             haveLedger = std::move (wantLedger);
             wantLedger = getLedgerByHash (haveLedger->getParentHash ());
         }
         while (wantLedger && (UptimeTimer::getInstance ().getElapsedSeconds () <= (uUptime + 1)));
         m_journal.info << "Built fetch pack with " << reply.objects ().size () << " nodes";
         Message::pointer msg = boost::make_shared<Message> (reply, protocol::mtGET_OBJECTS);
         peer->sendPacket (msg, false);
     }
     catch (...)
     {
         m_journal.warning << "Exception building fetch pach";
     }
 }
void ripple::NetworkOPsImp::mapComplete (uint256 const & hash, SHAMap::ref map) virtual
Implements ripple::NetworkOPs.
Definition at line 1645 of file NetworkOPs.cpp.
References haveConsensusObject(), and mConsensus.
 {
     if (haveConsensusObject ())
         mConsensus->mapComplete (hash, map, true);
 }
void ripple::NetworkOPsImp::missingNodeInLedger (const std::uint32_t seq) virtual
Implements ripple::NetworkOPs.
Definition at line 3312 of file NetworkOPs.cpp.
References ripple::InboundLedger::fcGENERIC, ripple::InboundLedgers::findCreate(), ripple::getApp(), ripple::LedgerMaster::getHashBySeq(), ripple::Application::getInboundLedgers(), ripple::Application::getLedgerMaster(), hash, ripple::base_uint< BITS >::isZero(), m_journal, and beast::Journal::warning.
 {
     uint256 hash = getApp().getLedgerMaster ().getHashBySeq (seq);
     if (hash.isZero())
     {
         m_journal.warning << "Missing a node in ledger " << seq << " cannot fetch";
     }
     else
     {
         m_journal.warning << "Missing a node in ledger " << seq << " fetching";
         getApp().getInboundLedgers ().findCreate (hash, seq, InboundLedger::fcGENERIC);
     }
 }
void ripple::NetworkOPsImp::needNetworkLedger () inline virtual
Implements ripple::NetworkOPs.
Definition at line 273 of file NetworkOPs.cpp.
References mNeedNetworkLedger.
     {
         mNeedNetworkLedger = true;
     }
void ripple::NetworkOPsImp::newLCL (int proposers, int convergeTime, uint256 const & ledgerHash) virtual
Implements ripple::NetworkOPs.
Definition at line 2709 of file NetworkOPs.cpp.
References mLastCloseConvergeTime, mLastCloseHash, and mLastCloseProposers.
 {
     assert (convergeTime);
     mLastCloseProposers = proposers;
     mLastCloseConvergeTime = convergeTime;
     mLastCloseHash = ledgerHash;
 }
void ripple::NetworkOPsImp::onDeadlineTimer (beast::DeadlineTimer & timer) private virtual
Reimplemented from beast::DeadlineTimer::Listener.
Definition at line 530 of file NetworkOPs.cpp.
References ripple::JobQueue::addJob(), BIND_TYPE, ripple::getApp(), ripple::Application::getJobQueue(), ripple::jtNETOP_CLUSTER, ripple::jtNETOP_TIMER, m_clusterTimer, m_heartbeatTimer, processClusterTimer(), and processHeartbeatTimer().
 {
     if (timer == m_heartbeatTimer)
     {
         getApp().getJobQueue ().addJob (jtNETOP_TIMER, "NetOPs.heartbeat",
             BIND_TYPE (&NetworkOPsImp::processHeartbeatTimer, this));
     }
     else if (timer == m_clusterTimer)
     {
         getApp().getJobQueue ().addJob (jtNETOP_CLUSTER, "NetOPs.cluster",
             BIND_TYPE (&NetworkOPsImp::processClusterTimer, this));
     }
 }
void ripple::NetworkOPsImp::onStop () inline virtual
Override called when the stop notification is issued.
The call is made on an unspecified, implementation-specific thread. onStop and onChildrenStopped will never be called concurrently, across all Stoppable objects descended from the same root, inclusive of the root.
It is safe to call isStopping, isStopped, and areChildrenStopped from within this function; The values returned will always be valid and never change during the callback.
The default implementation simply calls stopped(). This is applicable when the Stoppable has a trivial stop operation (or no stop operation), and we are merely using the Stoppable API to position it as a dependency of some parent service.
Thread safety: May not block for long periods. Guaranteed only to be called once. Must be safe to call from any thread at any time.
Reimplemented from beast::Stoppable.
Definition at line 422 of file NetworkOPs.cpp.
References beast::DeadlineTimer::cancel(), m_clusterTimer, m_heartbeatTimer, and beast::Stoppable::stopped().
     {
         m_heartbeatTimer.cancel();
         m_clusterTimer.cancel();
         stopped ();
     }
ripple::unordered_map< uint160, std::list<LedgerProposal::pointer> >& ripple::NetworkOPsImp::peekStoredProposals () inline virtual
Implements ripple::NetworkOPs.
Definition at line 330 of file NetworkOPs.cpp.
References mStoredProposals.
     {
         return mStoredProposals;
     }
void ripple::NetworkOPsImp::processClusterTimer () private
Definition at line 598 of file NetworkOPs.cpp.
References ripple::Resource::Gossip::Item::address, ripple::Resource::Gossip::Item::balance, beast::Journal::debug, ripple::Resource::Manager::exportConsumers(), ripple::Overlay::foreach(), ripple::getApp(), ripple::UniqueNodeList::getClusterStatus(), getNetworkTimeNC(), ripple::Application::getResourceManager(), ripple::Application::getUNL(), ripple::LedgerMaster::getValidatedLedgerAge(), ripple::Resource::Gossip::items, m_journal, m_ledgerMaster, ripple::Application::overlay(), ripple::send_if(), setClusterTimer(), and ripple::to_string().
Referenced by onDeadlineTimer().
 {
     bool synced = (m_ledgerMaster.getValidatedLedgerAge() <= 240);
     ClusterNodeStatus us("", synced ? getApp().getFeeTrack().getLocalFee() : 0, getNetworkTimeNC());
     if (!getApp().getUNL().nodeUpdate(getApp().getLocalCredentials().getNodePublic(), us))
     {
         m_journal.debug << "To soon to send cluster update";
         return;
     }
     std::map<RippleAddress, ClusterNodeStatus> nodes = getApp().getUNL().getClusterStatus();
     protocol::TMCluster cluster;
     for (std::map<RippleAddress, ClusterNodeStatus>::iterator it = nodes.begin(),
             end = nodes.end(); it != end; ++it)
     {
         protocol::TMClusterNode& node = *cluster.add_clusternodes();
         node.set_publickey(it->first.humanNodePublic());
         node.set_reporttime(it->second.getReportTime());
         node.set_nodeload(it->second.getLoadFee());
         if (!it->second.getName().empty())
             node.set_nodename(it->second.getName());
     }
     Resource::Gossip gossip = getApp().getResourceManager().exportConsumers();
     BOOST_FOREACH (Resource::Gossip::Item const& item, gossip.items)
     {
         protocol::TMLoadSource& node = *cluster.add_loadsources();
         node.set_name (to_string (item.address));
         node.set_cost (item.balance);
     }
     getApp ().overlay ().foreach (send_if (
         boost::make_shared<Message>(cluster, protocol::mtCLUSTER),
         peer_in_cluster ()));
     setClusterTimer ();
 }
void ripple::NetworkOPsImp::processHeartbeatTimer () private
Definition at line 544 of file NetworkOPs.cpp.
References ripple::getApp(), ripple::getConfig(), ripple::Application::getLoadManager(), beast::Journal::info, m_journal, mConsensus, mMode, ripple::Config::NETWORK_QUORUM, ripple::NetworkOPs::omCONNECTED, ripple::NetworkOPs::omDISCONNECTED, ripple::NetworkOPs::omSYNCING, ripple::Application::overlay(), ripple::LoadManager::resetDeadlockDetector(), setHeartbeatTimer(), setMode(), ripple::Overlay::size(), tryStartConsensus(), and beast::Journal::warning.
Referenced by onDeadlineTimer().
 {
     {
         Application::ScopedLockType lock (getApp().getMasterLock ());
         // VFALCO NOTE This is for diagnosing a crash on exit
         Application& app (getApp ());
         LoadManager& mgr (app.getLoadManager ());
         mgr.resetDeadlockDetector ();
         std::size_t const numPeers = getApp().overlay ().size ();
         // do we have sufficient peers? If not, we are disconnected.
         if (numPeers < getConfig ().NETWORK_QUORUM)
         {
             if (mMode != omDISCONNECTED)
             {
                 setMode (omDISCONNECTED);
                 m_journal.warning
                     << "Node count (" << numPeers << ") "
                     << "has fallen below quorum (" << getConfig ().NETWORK_QUORUM << ").";
             }
             setHeartbeatTimer ();
             return;
         }
         if (mMode == omDISCONNECTED)
         {
             setMode (omCONNECTED);
             m_journal.info << "Node count (" << numPeers << ") is sufficient.";
         }
         // Check if the last validated ledger forces a change between these states
         if (mMode == omSYNCING)
         {
             setMode (omSYNCING);
         }
         else if (mMode == omCONNECTED)
         {
             setMode (omCONNECTED);
         }
         if (!mConsensus)
             tryStartConsensus ();
         if (mConsensus)
             mConsensus->timerEntry ();
     }
     setHeartbeatTimer ();
 }
Transaction::pointer ripple::NetworkOPsImp::processTransaction (Transaction::pointer transaction, bool bAdmin, bool bLocal, bool bFailHard) inline virtual
Implements ripple::NetworkOPs.
Definition at line 170 of file NetworkOPs.cpp.
References processTransactionCb().
Referenced by submitTransactionSync().
     {
         return processTransactionCb (transaction, bAdmin, bLocal, bFailHard, stCallback ());
     }
Transaction::pointer ripple::NetworkOPsImp::processTransactionCb (Transaction::pointer trans, bool bAdmin, bool bLocal, bool bFailHard, stCallback callback) virtual
Implements ripple::NetworkOPs.
Definition at line 921 of file NetworkOPs.cpp.
References ripple::LedgerMaster::addHeldTransaction(), addLocalTx(), ripple::TransactionMaster::canonicalize(), beast::Journal::debug, ripple::LedgerMaster::doTransaction(), ripple::Overlay::foreach(), ripple::getApp(), ripple::LedgerMaster::getCurrentLedger(), ripple::Serializer::getData(), ripple::IHashRouter::getFlags(), ripple::Application::getHashRouter(), ripple::Application::getJobQueue(), ripple::Serializer::getLength(), ripple::JobQueue::getLoadEventAP(), ripple::Application::getMasterTransaction(), getNetworkTimeNC(), ripple::HELD, ripple::INCLUDED, beast::Journal::info, ripple::INVALID, IO_ERROR, isTemMalformed, isTerRetry, ripple::jtTXN_PROC, m_journal, m_ledgerMaster, mMode, ripple::OBSOLETE, ripple::NetworkOPs::omFULL, ripple::Application::overlay(), ripple::send_if_not(), ripple::IHashRouter::setFlag(), SF_BAD, SF_RELAYED, SF_SIGGOOD, ripple::IHashRouter::swapSet(), ripple::tapADMIN, ripple::tapNO_CHECK_SIGN, ripple::tapOPEN_LEDGER, ripple::tefFAILURE, ripple::tefPAST_SEQ, ripple::temBAD_SIGNATURE, ripple::tesSUCCESS, and ripple::transResultInfo().
Referenced by processTransaction(), and processTransactionCbVoid().
 {
     LoadEvent::autoptr ev = getApp().getJobQueue ().getLoadEventAP (jtTXN_PROC, "ProcessTXN");
     int newFlags = getApp().getHashRouter ().getFlags (trans->getID ());
     if ((newFlags & SF_BAD) != 0)
     {
         // cached bad
         trans->setStatus (INVALID);
         trans->setResult (temBAD_SIGNATURE);
         return trans;
     }
     if ((newFlags & SF_SIGGOOD) == 0)
     {
         // signature not checked
         if (!trans->checkSign ())
         {
             m_journal.info << "Transaction has bad signature";
             trans->setStatus (INVALID);
             trans->setResult (temBAD_SIGNATURE);
             getApp().getHashRouter ().setFlag (trans->getID (), SF_BAD);
             return trans;
         }
         getApp().getHashRouter ().setFlag (trans->getID (), SF_SIGGOOD);
     }
     {
         Application::ScopedLockType lock (getApp().getMasterLock ());
         bool didApply;
         TER r = m_ledgerMaster.doTransaction (trans->getSTransaction (),
                                               bAdmin ? (tapOPEN_LEDGER | tapNO_CHECK_SIGN | tapADMIN) : (tapOPEN_LEDGER | tapNO_CHECK_SIGN), didApply);
         trans->setResult (r);
         if (isTemMalformed (r)) // malformed, cache bad
             getApp().getHashRouter ().setFlag (trans->getID (), SF_BAD);
     //    else if (isTelLocal (r) || isTerRetry (r)) // can be retried
     //        getApp().getHashRouter ().setFlag (trans->getID (), SF_RETRY);
 #ifdef BEAST_DEBUG
         if (r != tesSUCCESS)
         {
             std::string token, human;
             if (transResultInfo (r, token, human))
                 m_journal.info << "TransactionResult: " << token << ": " << human;
         }
 #endif
         if (callback)
             callback (trans, r);
         if (r == tefFAILURE)
         {
             // VFALCO TODO All callers use a try block so this should be changed to
             //             a return value.
             throw Fault (IO_ERROR);
         }
         bool addLocal = bLocal;
         if (r == tesSUCCESS)
         {
             m_journal.info << "Transaction is now included in open ledger";
             trans->setStatus (INCLUDED);
             // VFALCO NOTE The value of trans can be changed here!!
             getApp().getMasterTransaction ().canonicalize (&trans);
         }
         else if (r == tefPAST_SEQ)
         {
             // duplicate or conflict
             m_journal.info << "Transaction is obsolete";
             trans->setStatus (OBSOLETE);
         }
         else if (isTerRetry (r))
         {
             if (bFailHard)
                 addLocal = false;
             else
             {
                 // transaction should be held
                 m_journal.debug << "Transaction should be held: " << r;
                 trans->setStatus (HELD);
                 getApp().getMasterTransaction ().canonicalize (&trans);
                 m_ledgerMaster.addHeldTransaction (trans);
             }
         }
         else
         {
             m_journal.debug << "Status other than success " << r;
             trans->setStatus (INVALID);
         }
         if (addLocal)
             addLocalTx (m_ledgerMaster.getCurrentLedger (), trans->getSTransaction ());
         if (didApply || ((mMode != omFULL) && !bFailHard && bLocal))
         {
             std::set<Peer::ShortId> peers;
             if (getApp().getHashRouter ().swapSet (trans->getID (), peers, SF_RELAYED))
             {
                 protocol::TMTransaction tx;
                 Serializer s;
                 trans->getSTransaction ()->add (s);
                 tx.set_rawtransaction (&s.getData ().front (), s.getLength ());
                 tx.set_status (protocol::tsCURRENT);
                 tx.set_receivetimestamp (getNetworkTimeNC ()); // FIXME: This should be when we received it
                 getApp ().overlay ().foreach (send_if_not (
                     boost::make_shared<Message> (tx, protocol::mtTRANSACTION),
                     peer_in_set(peers)));
             }
         }
     }
     return trans;
 }
void ripple::NetworkOPsImp::processTransactionCbVoid (Transaction::pointer p, bool bAdmin, bool bLocal, bool bFailHard, stCallback cb) inline
Definition at line 177 of file NetworkOPs.cpp.
References processTransactionCb().
Referenced by submitTransaction().
     {
         processTransactionCb (p, bAdmin, bLocal, bFailHard, cb);
     }
void ripple::NetworkOPsImp::processTrustedProposal (LedgerProposal::pointer proposal, boost::shared_ptr< protocol::TMProposeSet > set, RippleAddress nodePublic, uint256 checkLedger, bool sigGood) virtual
Implements ripple::NetworkOPs.
Definition at line 1520 of file NetworkOPs.cpp.
References ripple::Overlay::foreach(), ripple::getApp(), haveConsensusObject(), beast::Journal::info, m_journal, mConsensus, mMode, ripple::NetworkOPs::omFULL, ripple::Application::overlay(), ripple::send_if_not(), SF_RELAYED, storeProposal(), beast::Journal::trace, and beast::Journal::warning.
 {
     {
         Application::ScopedLockType lock (getApp().getMasterLock ());
         bool relay = true;
         if (!haveConsensusObject ())
         {
             m_journal.info << "Received proposal outside consensus window";
             if (mMode == omFULL)
                 relay = false;
         }
         else
         {
             storeProposal (proposal, nodePublic);
             uint256 consensusLCL = mConsensus->getLCL ();
             if (!set->has_previousledger () && (checkLedger != consensusLCL))
             {
                 m_journal.warning << "Have to re-check proposal signature due to consensus view change";
                 assert (proposal->hasSignature ());
                 proposal->setPrevLedger (consensusLCL);
                 if (proposal->checkSign ())
                     sigGood = true;
             }
             if (sigGood && (consensusLCL == proposal->getPrevLedger ()))
             {
                 relay = mConsensus->peerPosition (proposal);
                 m_journal.trace << "Proposal processing finished, relay=" << relay;
             }
         }
         if (relay)
         {
             std::set<Peer::ShortId> peers;
             if (getApp().getHashRouter ().swapSet (
                 proposal->getSuppressionID (), peers, SF_RELAYED))
         {
                 getApp ().overlay ().foreach (send_if_not (
                     boost::make_shared<Message> (*set, protocol::mtPROPOSE_LEDGER),
                     peer_in_set(peers)));
         }
         }
         else
         {
             m_journal.info << "Not relaying trusted proposal";
         }
     }
 }
void ripple::NetworkOPsImp::pubAccountTransaction (Ledger::ref lpCurrent, const AcceptedLedgerTx & alTransaction, bool isAccepted) private
Definition at line 2521 of file NetworkOPs.cpp.
References ripple::RippleAddress::getAccountID(), ripple::AcceptedLedgerTx::getAffected(), ripple::AcceptedLedgerTx::getMeta(), ripple::AcceptedLedgerTx::getResult(), ripple::AcceptedLedgerTx::getTxn(), beast::Journal::info, ripple::AcceptedLedgerTx::isApplied(), m_journal, mLock, mSubAccount, mSubRTAccount, transJson(), and Json::FastWriter::write().
Referenced by pubProposedTransaction(), and pubValidatedTransaction().
 {
     boost::unordered_set<InfoSub::pointer>  notify;
     int                             iProposed   = 0;
     int                             iAccepted   = 0;
     {
         ScopedLockType sl (mLock);
         if (!bAccepted && mSubRTAccount.empty ()) return;
         if (!mSubAccount.empty () || (!mSubRTAccount.empty ()) )
         {
             BOOST_FOREACH (const RippleAddress & affectedAccount, alTx.getAffected ())
             {
                 SubInfoMapIterator  simiIt  = mSubRTAccount.find (affectedAccount.getAccountID ());
                 if (simiIt != mSubRTAccount.end ())
                 {
                     NetworkOPsImp::SubMapType::const_iterator it = simiIt->second.begin ();
                     while (it != simiIt->second.end ())
                     {
                         InfoSub::pointer p = it->second.lock ();
                         if (p)
{
                             notify.insert (p);
                             ++it;
                             ++iProposed;
                         }
                         else
                             it = simiIt->second.erase (it);
                     }
                 }
                 if (bAccepted)
                 {
                     simiIt  = mSubAccount.find (affectedAccount.getAccountID ());
                     if (simiIt != mSubAccount.end ())
                     {
                         NetworkOPsImp::SubMapType::const_iterator it = simiIt->second.begin ();
                         while (it != simiIt->second.end ())
{
                             InfoSub::pointer p = it->second.lock ();
                             if (p)
{
                                 notify.insert (p);
                                 ++it;
                                 ++iAccepted;
                             }
                             else
                                 it = simiIt->second.erase (it);
                         }
                     }
                 }
             }
         }
     }
     m_journal.info << "pubAccountTransaction:" <<
         " iProposed=" << iProposed <<
         " iAccepted=" << iAccepted;
     if (!notify.empty ())
     {
         Json::Value jvObj = transJson (
             *alTx.getTxn (), alTx.getResult (), bAccepted, lpCurrent);
         if (alTx.isApplied ())
             jvObj["meta"] = alTx.getMeta ()->getJson (0);
         Json::FastWriter w;
         std::string sObj = w.write (jvObj);
         BOOST_FOREACH (InfoSub::ref isrListener, notify)
         {
             isrListener->send (jvObj, sObj, true);
         }
     }
 }
Json::Value ripple::NetworkOPsImp::pubBootstrapAccountInfo (Ledger::ref lpAccepted, const RippleAddress & naAccountID) private
Definition at line 2335 of file NetworkOPs.cpp.
References getOwnerInfo(), ripple::RippleAddress::humanAccountID(), Json::objectValue, and ripple::utFromSeconds().
 {
     Json::Value         jvObj (Json::objectValue);
     jvObj["type"]           = "accountInfoBootstrap";
     jvObj["account"]        = naAccountID.humanAccountID ();
     jvObj["owner"]          = getOwnerInfo (lpAccepted, naAccountID);
     jvObj["ledger_index"]   = lpAccepted->getLedgerSeq ();
     jvObj["ledger_hash"]    = lpAccepted->getHash ().ToString ();
     jvObj["ledger_time"]    = Json::Value::UInt (utFromSeconds (lpAccepted->getCloseTimeNC ()));
     return jvObj;
 }
void ripple::NetworkOPsImp::pubLedger (Ledger::ref lpAccepted) virtual
Implements ripple::NetworkOPs.
Definition at line 2375 of file NetworkOPs.cpp.
References ripple::getApp(), ripple::LedgerMaster::getCompleteLedgers(), ripple::Application::getLedgerMaster(), m_journal, ripple::AcceptedLedger::makeAcceptedLedger(), mLock, mMode, mSubLedger, Json::objectValue, ripple::NetworkOPs::omSYNCING, pubValidatedTransaction(), and beast::Journal::trace.
 {
     // Ledgers are published only when they acquire sufficient validations
     // Holes are filled across connection loss or other catastrophe
     AcceptedLedger::pointer alpAccepted = AcceptedLedger::makeAcceptedLedger (accepted);
     Ledger::ref lpAccepted = alpAccepted->getLedger ();
     {
         ScopedLockType sl (mLock);
         if (!mSubLedger.empty ())
         {
             Json::Value jvObj (Json::objectValue);
             jvObj["type"]           = "ledgerClosed";
             jvObj["ledger_index"]   = lpAccepted->getLedgerSeq ();
             jvObj["ledger_hash"]    = lpAccepted->getHash ().ToString ();
             jvObj["ledger_time"]    = Json::Value::UInt (lpAccepted->getCloseTimeNC ());
             jvObj["fee_ref"]        = Json::UInt (lpAccepted->getReferenceFeeUnits ());
             jvObj["fee_base"]       = Json::UInt (lpAccepted->getBaseFee ());
             jvObj["reserve_base"]   = Json::UInt (lpAccepted->getReserve (0));
             jvObj["reserve_inc"]    = Json::UInt (lpAccepted->getReserveInc ());
             jvObj["txn_count"]      = Json::UInt (alpAccepted->getTxnCount ());
             if (mMode >= omSYNCING)
                 jvObj["validated_ledgers"]  = getApp().getLedgerMaster ().getCompleteLedgers ();
             NetworkOPsImp::SubMapType::const_iterator it = mSubLedger.begin ();
             while (it != mSubLedger.end ())
             {
                 InfoSub::pointer p = it->second.lock ();
                 if (p)
                 {
                     p->send (jvObj, true);
                     ++it;
                 }
                 else
                     it = mSubLedger.erase (it);
             }
         }
     }
     // Don't lock since pubAcceptedTransaction is locking.
     BOOST_FOREACH (const AcceptedLedger::value_type & vt, alpAccepted->getMap ())
     {
         m_journal.trace << "pubAccepted: " << vt.second->getJson ();
         pubValidatedTransaction (lpAccepted, *vt.second);
     }
 }
void ripple::NetworkOPsImp::pubProposedTransaction (Ledger::ref lpCurrent, SerializedTransaction::ref stTxn, TER terResult) virtual
Implements ripple::NetworkOPs.
Definition at line 2349 of file NetworkOPs.cpp.
References ripple::AcceptedLedgerTx::getJson(), m_journal, mLock, mSubRTTransactions, pubAccountTransaction(), beast::Journal::trace, and transJson().
 {
     Json::Value jvObj   = transJson (*stTxn, terResult, false, lpCurrent);
     {
         ScopedLockType sl (mLock);
         NetworkOPsImp::SubMapType::const_iterator it = mSubRTTransactions.begin ();
         while (it != mSubRTTransactions.end ())
         {
             InfoSub::pointer p = it->second.lock ();
             if (p)
             {
                 p->send (jvObj, true);
                 ++it;
             }
             else
                 it = mSubRTTransactions.erase (it);
         }
     }
     AcceptedLedgerTx alt (stTxn, terResult);
     m_journal.trace << "pubProposed: " << alt.getJson ();
     pubAccountTransaction (lpCurrent, alt, false);
 }
void ripple::NetworkOPsImp::pubServer () private
Definition at line 1675 of file NetworkOPs.cpp.
References ripple::getApp(), ripple::Application::getFeeTrack(), ripple::LoadFeeTrack::getLoadBase(), ripple::LoadFeeTrack::getLoadFactor(), mLastLoadBase, mLastLoadFactor, mLock, mSubServer, Json::objectValue, strOperatingMode(), and Json::FastWriter::write().
Referenced by reportFeeChange(), and setMode().
 {
     // VFALCO TODO Don't hold the lock across calls to send...make a copy of the
     //             list into a local array while holding the lock then release the
     //             lock and call send on everyone.
     //
     ScopedLockType sl (mLock);
     if (!mSubServer.empty ())
     {
         Json::Value jvObj (Json::objectValue);
         jvObj ["type"]          = "serverStatus";
         jvObj ["server_status"] = strOperatingMode ();
         jvObj ["load_base"]     = (mLastLoadBase = getApp().getFeeTrack ().getLoadBase ());
         jvObj ["load_factor"]   = (mLastLoadFactor = getApp().getFeeTrack ().getLoadFactor ());
         Json::FastWriter w;
         std::string sObj = w.write (jvObj);
         NetworkOPsImp::SubMapType::const_iterator it = mSubServer.begin ();
         while (it != mSubServer.end ())
         {
             InfoSub::pointer p = it->second.lock ();
             // VFALCO TODO research the possibility of using thread queues and linearizing
             //             the deletion of subscribers with the sending of JSON data.
             if (p)
             {
                 p->send (jvObj, sObj, true);
                 ++it;
             }
             else
             {
                 it = mSubServer.erase (it);
             }
         }
     }
 }
void ripple::NetworkOPsImp::pubValidatedTransaction (Ledger::ref alAccepted, const AcceptedLedgerTx & alTransaction) private
Definition at line 2476 of file NetworkOPs.cpp.
References ripple::getApp(), ripple::AcceptedLedgerTx::getMeta(), ripple::Application::getOrderBookDB(), ripple::AcceptedLedgerTx::getResult(), ripple::AcceptedLedgerTx::getTxn(), mLock, mSubRTTransactions, mSubTransactions, ripple::OrderBookDB::processTxn(), pubAccountTransaction(), transJson(), and Json::FastWriter::write().
Referenced by pubLedger().
 {
     Json::Value jvObj   = transJson (*alTx.getTxn (), alTx.getResult (), true, alAccepted);
     jvObj["meta"] = alTx.getMeta ()->getJson (0);
     Json::FastWriter w;
     std::string sObj = w.write (jvObj);
     {
         ScopedLockType sl (mLock);
         NetworkOPsImp::SubMapType::const_iterator it = mSubTransactions.begin ();
         while (it != mSubTransactions.end ())
         {
             InfoSub::pointer p = it->second.lock ();
             if (p)
             {
                 p->send (jvObj, sObj, true);
                 ++it;
             }
             else
                 it = mSubTransactions.erase (it);
         }
         it = mSubRTTransactions.begin ();
         while (it != mSubRTTransactions.end ())
         {
             InfoSub::pointer p = it->second.lock ();
             if (p)
             {
                 p->send (jvObj, sObj, true);
                 ++it;
             }
             else
                 it = mSubRTTransactions.erase (it);
         }
     }
     getApp().getOrderBookDB ().processTxn (alAccepted, alTx, jvObj);
     pubAccountTransaction (alAccepted, alTx, true);
 }
bool ripple::NetworkOPsImp::recvValidation (SerializedValidation::ref val, const std::string & source) virtual
Implements ripple::NetworkOPs.
Definition at line 2151 of file NetworkOPs.cpp.
References ripple::Validations::addValidation(), beast::Journal::debug, ripple::getApp(), ripple::Application::getValidations(), and m_journal.
 {
     m_journal.debug << "recvValidation " << val->getLedgerHash () << " from " << source;
     return getApp().getValidations ().addValidation (val, source);
 }
void ripple::NetworkOPsImp::reportFeeChange () virtual
Implements ripple::NetworkOPs.
Definition at line 2430 of file NetworkOPs.cpp.
References ripple::JobQueue::addJob(), BIND_TYPE, ripple::getApp(), ripple::Application::getJobQueue(), ripple::jtCLIENT, mLastLoadBase, mLastLoadFactor, and pubServer().
 {
     if ((getApp().getFeeTrack ().getLoadBase () == mLastLoadBase) &&
             (getApp().getFeeTrack ().getLoadFactor () == mLastLoadFactor))
         return;
     getApp().getJobQueue ().addJob (jtCLIENT, "reportFeeChange->pubServer", BIND_TYPE (&NetworkOPsImp::pubServer, this));
 }
void ripple::NetworkOPsImp::runTransactionQueue () virtual
Implements ripple::NetworkOPs.
Definition at line 834 of file NetworkOPs.cpp.
References ripple::LedgerMaster::addHeldTransaction(), BIND_TYPE, ripple::TransactionMaster::canonicalize(), beast::Journal::debug, ripple::LedgerMaster::doTransaction(), ripple::TransactionMaster::fetch(), ripple::Overlay::foreach(), ripple::getApp(), ripple::Serializer::getData(), ripple::Application::getHashRouter(), ripple::Application::getIOService(), ripple::TxQueue::getJob(), ripple::Application::getJobQueue(), ripple::Serializer::getLength(), ripple::JobQueue::getLoadEventAP(), ripple::Application::getMasterTransaction(), getNetworkTimeNC(), ripple::Application::getTxQueue(), ripple::HELD, ripple::INCLUDED, beast::Journal::info, ripple::INVALID, isTemMalformed, isTerRetry, ripple::jtTXN_PROC, m_journal, m_ledgerMaster, ripple::OBSOLETE, ripple::Application::overlay(), ripple::send_if_not(), ripple::IHashRouter::setFlag(), SF_BAD, SF_RELAYED, ripple::tapNO_CHECK_SIGN, ripple::tapOPEN_LEDGER, ripple::tefPAST_SEQ, and ripple::tesSUCCESS.
 {
     TxQueueEntry::pointer txn;
     for (int i = 0; i < 10; ++i)
     {
         getApp().getTxQueue ().getJob (txn);
         if (!txn)
             return;
         {
             LoadEvent::autoptr ev = getApp().getJobQueue ().getLoadEventAP (jtTXN_PROC, "runTxnQ");
             {
                 Application::ScopedLockType lock (getApp().getMasterLock ());
                 Transaction::pointer dbtx = getApp().getMasterTransaction ().fetch (txn->getID (), true);
                 assert (dbtx);
                 bool didApply;
                 TER r = m_ledgerMaster.doTransaction (dbtx->getSTransaction (),
                                                       tapOPEN_LEDGER | tapNO_CHECK_SIGN, didApply);
                 dbtx->setResult (r);
                 if (isTemMalformed (r)) // malformed, cache bad
                     getApp().getHashRouter ().setFlag (txn->getID (), SF_BAD);
     //            else if (isTelLocal (r) || isTerRetry (r)) // can be retried
     //                getApp().getHashRouter ().setFlag (txn->getID (), SF_RETRY);
                 if (isTerRetry (r))
                 {
                     // transaction should be held
                     m_journal.debug << "QTransaction should be held: " << r;
                     dbtx->setStatus (HELD);
                     getApp().getMasterTransaction ().canonicalize (&dbtx);
                     m_ledgerMaster.addHeldTransaction (dbtx);
                 }
                 else if (r == tefPAST_SEQ)
                 {
                     // duplicate or conflict
                     m_journal.info << "QTransaction is obsolete";
                     dbtx->setStatus (OBSOLETE);
                 }
                 else if (r == tesSUCCESS)
                 {
                     m_journal.info << "QTransaction is now included in open ledger";
                     dbtx->setStatus (INCLUDED);
                     getApp().getMasterTransaction ().canonicalize (&dbtx);
                 }
                 else
                 {
                     m_journal.debug << "QStatus other than success " << r;
                     dbtx->setStatus (INVALID);
                 }
                 if (didApply /*|| (mMode != omFULL)*/ )
                 {
                     std::set <Peer::ShortId> peers;
                     if (getApp().getHashRouter ().swapSet (txn->getID (), peers, SF_RELAYED))
                     {
                         m_journal.debug << "relaying";
                         protocol::TMTransaction tx;
                         Serializer s;
                         dbtx->getSTransaction ()->add (s);
                         tx.set_rawtransaction (&s.getData ().front (), s.getLength ());
                         tx.set_status (protocol::tsCURRENT);
                         tx.set_receivetimestamp (getNetworkTimeNC ()); // FIXME: This should be when we received it
                         getApp ().overlay ().foreach (send_if_not (
                             boost::make_shared<Message> (tx, protocol::mtTRANSACTION),
                             peer_in_set(peers)));
                     }
                     else
                         m_journal.debug << "recently relayed";
                 }
                 txn->doCallbacks (r);
             }
         }
     }
     if (getApp().getTxQueue ().stopProcessing (txn))
         getApp().getIOService ().post (BIND_TYPE (&NetworkOPsImp::runTransactionQueue, this));
 }
void ripple::NetworkOPsImp::setClusterTimer () private
Definition at line 525 of file NetworkOPs.cpp.
References m_clusterTimer, and beast::DeadlineTimer::setExpiration().
Referenced by processClusterTimer(), and setStateTimer().
 {
     m_clusterTimer.setExpiration (10.0);
 }
void ripple::NetworkOPsImp::setFeatureBlocked () virtual
Implements ripple::NetworkOPs.
Definition at line 1194 of file NetworkOPs.cpp.
References mFeatureBlocked, ripple::NetworkOPs::omTRACKING, and setMode().
 {
     mFeatureBlocked = true;
     setMode (omTRACKING);
 }
void ripple::NetworkOPsImp::setHeartbeatTimer () private
Definition at line 520 of file NetworkOPs.cpp.
References LEDGER_GRANULARITY, m_heartbeatTimer, and beast::DeadlineTimer::setExpiration().
Referenced by processHeartbeatTimer(), and setStateTimer().
 {
     m_heartbeatTimer.setExpiration (LEDGER_GRANULARITY / 1000.0);
 }
void ripple::NetworkOPsImp::setLastCloseTime (std::uint32_t t) inline virtual
Implements ripple::NetworkOPs.
Definition at line 320 of file NetworkOPs.cpp.
References mLastCloseTime.
     {
         mLastCloseTime = t;
     }
void ripple::NetworkOPsImp::setLastValidation (SerializedValidation::ref v) inline virtual
Implements ripple::NetworkOPs.
Definition at line 147 of file NetworkOPs.cpp.
References mLastValidation.
     {
         mLastValidation = v;
     }
void ripple::NetworkOPsImp::setMode (OperatingMode om) private
Definition at line 1717 of file NetworkOPs.cpp.
References ripple::getApp(), rocksdb::Log(), ripple::lsINFO, ripple::lsWARNING, mConnectTime, mFeatureBlocked, mMode, ripple::NetworkOPs::omCONNECTED, ripple::NetworkOPs::omDISCONNECTED, ripple::NetworkOPs::omSYNCING, ripple::NetworkOPs::omTRACKING, pubServer(), and strOperatingMode().
Referenced by beginConsensus(), checkLastClosedLedger(), consensusViewChange(), haveConsensusObject(), processHeartbeatTimer(), setFeatureBlocked(), setStandAlone(), and tryStartConsensus().
 {
     if (om == omCONNECTED)
     {
         if (getApp().getLedgerMaster ().getValidatedLedgerAge () < 60)
             om = omSYNCING;
     }
     else if (om == omSYNCING)
     {
         if (getApp().getLedgerMaster ().getValidatedLedgerAge () >= 60)
             om = omCONNECTED;
     }
     if ((om > omTRACKING) && mFeatureBlocked)
         om = omTRACKING;
     if (mMode == om)
         return;
     if ((om >= omCONNECTED) && (mMode == omDISCONNECTED))
         mConnectTime = boost::posix_time::second_clock::universal_time ();
     mMode = om;
     Log ((om < mMode) ? lsWARNING : lsINFO) << "STATE->" << strOperatingMode ();
     pubServer ();
 }
void ripple::NetworkOPsImp::setProposing (bool p, bool v) inline virtual
Implements ripple::NetworkOPs.
Definition at line 289 of file NetworkOPs.cpp.
References mProposing, and mValidating.
     {
         mProposing = p;
         mValidating = v;
     }
void ripple::NetworkOPsImp::setStandAlone () inline virtual
Implements ripple::NetworkOPs.
Definition at line 262 of file NetworkOPs.cpp.
References ripple::NetworkOPs::omFULL, and setMode().
     {
         setMode (omFULL);
     }
void ripple::NetworkOPsImp::setStateTimer () virtual
Called to initially start our timers. Not called for stand-alone mode.
Implements ripple::NetworkOPs.
Definition at line 514 of file NetworkOPs.cpp.
References setClusterTimer(), and setHeartbeatTimer().
 {
     setHeartbeatTimer ();
     setClusterTimer ();
 }
bool ripple::NetworkOPsImp::shouldFetchPack (std::uint32_t seq) virtual
Implements ripple::NetworkOPs.
Definition at line 3288 of file NetworkOPs.cpp.
References mFetchSeq.
 {
     if (mFetchSeq == seq)
         return false;
     mFetchSeq = seq;
     return true;
 }
bool ripple::NetworkOPsImp::stillNeedTXSet (uint256 const & hash) virtual
Implements ripple::NetworkOPs.
Definition at line 1637 of file NetworkOPs.cpp.
References mConsensus.
 {
     if (!mConsensus)
         return false;
     return mConsensus->stillNeedTXSet (hash);
 }
void ripple::NetworkOPsImp::storeProposal (LedgerProposal::ref proposal, const RippleAddress & peerPublic) virtual
Implements ripple::NetworkOPs.
Definition at line 2725 of file NetworkOPs.cpp.
References ripple::RippleAddress::getNodeID(), mLastCloseProposers, and mStoredProposals.
Referenced by processTrustedProposal().
 {
     std::list<LedgerProposal::pointer>& props = mStoredProposals[peerPublic.getNodeID ()];
     if (props.size () >= (unsigned) (mLastCloseProposers + 10))
         props.pop_front ();
     props.push_back (proposal);
 }
std::string ripple::NetworkOPsImp::strOperatingMode () virtual
Implements ripple::NetworkOPs.
Definition at line 638 of file NetworkOPs.cpp.
References mMode, mProposing, mValidating, and ripple::NetworkOPs::omFULL.
Referenced by getServerInfo(), pubServer(), setMode(), and subServer().
 {
     static const char* paStatusToken [] =
     {
         "disconnected",
         "connected",
         "syncing",
         "tracking",
         "full"
     };
     if (mMode == omFULL)
     {
         if (mProposing)
             return "proposing";
         if (mValidating)
             return "validating";
     }
     return paStatusToken[mMode];
 }
void ripple::NetworkOPsImp::subAccount (InfoSub::ref ispListener, const boost::unordered_set< RippleAddress > & vnaAccountIDs, std::uint32_t uLedgerIndex, bool rt) virtual
Implements ripple::InfoSub::Source.
Definition at line 2609 of file NetworkOPs.cpp.
References ripple::RippleAddress::getAccountID(), ripple::RippleAddress::humanAccountID(), m_journal, mLock, mSubAccount, mSubRTAccount, and beast::Journal::trace.
 {
     SubInfoMapType& subMap = rt ? mSubRTAccount : mSubAccount;
     // For the connection, monitor each account.
     BOOST_FOREACH (const RippleAddress & naAccountID, vnaAccountIDs)
     {
         m_journal.trace << "subAccount:"
             " account: " << naAccountID.humanAccountID ();
         isrListener->insertSubAccountInfo (naAccountID, uLedgerIndex);
     }
     ScopedLockType sl (mLock);
     BOOST_FOREACH (const RippleAddress & naAccountID, vnaAccountIDs)
     {
         SubInfoMapType::iterator    simIterator = subMap.find (naAccountID.getAccountID ());
         if (simIterator == subMap.end ())
         {
             // Not found, note that account has a new single listner.
             SubMapType  usisElement;
             usisElement[isrListener->getSeq ()] = isrListener;
             subMap.insert (simIterator, make_pair (naAccountID.getAccountID (), usisElement));
         }
         else
         {
             // Found, note that the account has another listener.
             simIterator->second[isrListener->getSeq ()] = isrListener;
         }
     }
 }
bool ripple::NetworkOPsImp::subBook (InfoSub::ref ispListener, RippleCurrency const & currencyPays, RippleCurrency const & currencyGets, RippleIssuer const & issuerPays, RippleIssuer const & issuerGets) virtual
Implements ripple::InfoSub::Source.
Definition at line 2684 of file NetworkOPs.cpp.
References ripple::getApp(), ripple::Application::getOrderBookDB(), and ripple::OrderBookDB::makeBookListeners().
 {
     BookListeners::pointer listeners =
         getApp().getOrderBookDB ().makeBookListeners (currencyPays, currencyGets, issuerPays, issuerGets);
     assert (listeners);
     if (listeners)
         listeners->addSubscriber (isrListener);
     return true;
 }
bool ripple::NetworkOPsImp::subLedger (InfoSub::ref ispListener, Json::Value & jvResult) virtual
Implements ripple::InfoSub::Source.
Definition at line 2746 of file NetworkOPs.cpp.
References ripple::getApp(), ripple::LedgerMaster::getCompleteLedgers(), ripple::Application::getLedgerMaster(), getValidatedLedger(), isNeedNetworkLedger(), mLock, mMode, mSubLedger, and ripple::NetworkOPs::omSYNCING.
 {
     Ledger::pointer lpClosed    = getValidatedLedger ();
     if (lpClosed)
     {
         jvResult["ledger_index"]    = lpClosed->getLedgerSeq ();
         jvResult["ledger_hash"]     = lpClosed->getHash ().ToString ();
         jvResult["ledger_time"]     = Json::Value::UInt (lpClosed->getCloseTimeNC ());
         jvResult["fee_ref"]         = Json::UInt (lpClosed->getReferenceFeeUnits ());
         jvResult["fee_base"]        = Json::UInt (lpClosed->getBaseFee ());
         jvResult["reserve_base"]    = Json::UInt (lpClosed->getReserve (0));
         jvResult["reserve_inc"]     = Json::UInt (lpClosed->getReserveInc ());
     }
     if ((mMode >= omSYNCING) && !isNeedNetworkLedger ())
         jvResult["validated_ledgers"]   = getApp().getLedgerMaster ().getCompleteLedgers ();
     ScopedLockType sl (mLock);
     return mSubLedger.emplace (isrListener->getSeq (), isrListener).second;
 }
void ripple::NetworkOPsImp::submitTransaction (Job & , SerializedTransaction::pointer iTrans, stCallback callback = stCallback ()) virtual
Implements ripple::NetworkOPs.
Definition at line 752 of file NetworkOPs.cpp.
References ripple::JobQueue::addJob(), ripple::getApp(), ripple::Application::getHashRouter(), ripple::Application::getJobQueue(), ripple::jtTRANSACTION, m_journal, ripple::passesLocalChecks(), processTransactionCbVoid(), ripple::IHashRouter::setFlag(), SF_BAD, SF_RETRY, SF_SIGGOOD, and beast::Journal::warning.
 {
     // this is an asynchronous interface
     Serializer s;
     iTrans->add (s);
     SerializerIterator sit (s);
     SerializedTransaction::pointer trans = boost::make_shared<SerializedTransaction> (boost::ref (sit));
     uint256 suppress = trans->getTransactionID ();
     int flags;
     if (getApp().getHashRouter ().addSuppressionPeer (suppress, 0, flags) && ((flags & SF_RETRY) != 0))
     {
         m_journal.warning << "Redundant transactions submitted";
         return;
     }
     if ((flags & SF_BAD) != 0)
     {
         m_journal.warning << "Submitted transaction cached bad";
         return;
     }
     if ((flags & SF_SIGGOOD) == 0)
     {
         try
         {
             if (!passesLocalChecks (*trans) || !trans->checkSign ())
             {
                 m_journal.warning << "Submitted transaction has bad signature";
                 getApp().getHashRouter ().setFlag (suppress, SF_BAD);
                 return;
             }
             getApp().getHashRouter ().setFlag (suppress, SF_SIGGOOD);
         }
         catch (...)
         {
             m_journal.warning << "Exception checking transaction " << suppress;
             return;
         }
     }
     getApp().getJobQueue().addJob (jtTRANSACTION, "submitTxn",
         std::bind (&NetworkOPsImp::processTransactionCbVoid, this,
             boost::make_shared<Transaction> (trans, false), false, false, false, callback));
 }
Transaction::pointer ripple::NetworkOPsImp::submitTransactionSync (Transaction::ref tpTrans, bool bAdmin, bool bLocal, bool bFailHard, bool bSubmit) virtual
Implements ripple::NetworkOPs.
Definition at line 803 of file NetworkOPs.cpp.
References beast::Journal::fatal, ripple::Serializer::getData(), m_journal, nothing, processTransaction(), and ripple::Transaction::sharedTransaction().
 {
     Serializer s;
     tpTrans->getSTransaction ()->add (s);
     Transaction::pointer    tpTransNew  = Transaction::sharedTransaction (s.getData (), true);
     if (!tpTransNew)
     {
         // Could not construct transaction.
         nothing ();
     }
     else if (tpTransNew->getSTransaction ()->isEquivalent (*tpTrans->getSTransaction ()))
     {
         if (bSubmit)
             (void) NetworkOPsImp::processTransaction (tpTransNew, bAdmin, bLocal, bFailHard);
     }
     else
     {
         m_journal.fatal << "Transaction reconstruction failure";
         m_journal.fatal << tpTransNew->getSTransaction ()->getJson (0);
         m_journal.fatal << tpTrans->getSTransaction ()->getJson (0);
         // assert (false); "1e-95" as amount can trigger this
         tpTransNew.reset ();
     }
     return tpTransNew;
 }
bool ripple::NetworkOPsImp::subRTTransactions (InfoSub::ref ispListener) virtual
Implements ripple::InfoSub::Source.
Definition at line 2816 of file NetworkOPs.cpp.
References mLock, and mSubRTTransactions.
 {
     ScopedLockType sl (mLock);
     return mSubRTTransactions.emplace (isrListener->getSeq (), isrListener).second;
 }
bool ripple::NetworkOPsImp::subServer (InfoSub::ref ispListener, Json::Value & jvResult) virtual
Implements ripple::InfoSub::Source.
Definition at line 2777 of file NetworkOPs.cpp.
References ripple::base_uint< BITS >::begin(), ripple::RandomNumbers::fillBytes(), ripple::getApp(), ripple::getConfig(), ripple::Application::getFeeTrack(), ripple::RandomNumbers::getInstance(), ripple::LoadFeeTrack::getLoadBase(), ripple::LoadFeeTrack::getLoadFactor(), mLock, mSubServer, ripple::Config::RUN_STANDALONE, ripple::base_uint< BITS >::size(), strOperatingMode(), and ripple::base_uint< BITS >::ToString().
 {
     uint256         uRandom;
     if (getConfig ().RUN_STANDALONE)
         jvResult["stand_alone"] = getConfig ().RUN_STANDALONE;
     RandomNumbers::getInstance ().fillBytes (uRandom.begin (), uRandom.size ());
     jvResult["random"]          = uRandom.ToString ();
     jvResult["server_status"]   = strOperatingMode ();
     jvResult["load_base"]       = getApp().getFeeTrack ().getLoadBase ();
     jvResult["load_factor"]     = getApp().getFeeTrack ().getLoadFactor ();
     ScopedLockType sl (mLock);
     return mSubServer.emplace (isrListener->getSeq (), isrListener).second;
 }
bool ripple::NetworkOPsImp::subTransactions (InfoSub::ref ispListener) virtual
Implements ripple::InfoSub::Source.
Definition at line 2802 of file NetworkOPs.cpp.
References mLock, and mSubTransactions.
 {
     ScopedLockType sl (mLock);
     return mSubTransactions.emplace (isrListener->getSeq (), isrListener).second;
 }
void ripple::NetworkOPsImp::sweepFetchPack () virtual
Implements ripple::NetworkOPs.
Definition at line 3260 of file NetworkOPs.cpp.
References mFetchPack, and ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::sweep().
 {
     mFetchPack.sweep ();
 }
void ripple::NetworkOPsImp::switchLastClosedLedger (Ledger::pointer newLedger, bool duringConsensus)
Definition at line 1422 of file NetworkOPs.cpp.
References ripple::base_uint< BITS >::begin(), clearNeedNetworkLedger(), beast::Journal::error, ripple::Overlay::foreach(), ripple::getApp(), getNetworkTimeNC(), hash, m_journal, m_ledgerMaster, ripple::Application::overlay(), ripple::base_uint< BITS >::size(), and ripple::LedgerMaster::switchLedgers().
Referenced by checkLastClosedLedger().
 {
     // set the newledger as our last closed ledger -- this is abnormal code
     if (duringConsensus)
         m_journal.error << "JUMPdc last closed ledger to " << newLedger->getHash ();
     else
         m_journal.error << "JUMP last closed ledger to " << newLedger->getHash ();
     clearNeedNetworkLedger ();
     newLedger->setClosed ();
     Ledger::pointer openLedger = boost::make_shared<Ledger> (false, boost::ref (*newLedger));
     m_ledgerMaster.switchLedgers (newLedger, openLedger);
     protocol::TMStatusChange s;
     s.set_newevent (protocol::neSWITCHED_LEDGER);
     s.set_ledgerseq (newLedger->getLedgerSeq ());
     s.set_networktime (getApp().getOPs ().getNetworkTimeNC ());
     uint256 hash = newLedger->getParentHash ();
     s.set_ledgerhashprevious (hash.begin (), hash.size ());
     hash = newLedger->getHash ();
     s.set_ledgerhash (hash.begin (), hash.size ());
     getApp ().overlay ().foreach (send_always (
         boost::make_shared<Message> (s, protocol::mtSTATUS_CHANGE)));
 }
void ripple::NetworkOPsImp::takePosition (int seq, SHAMap::ref position) virtual
Implements ripple::NetworkOPs.
Definition at line 1591 of file NetworkOPs.cpp.
References mRecentPositions.
 {
     mRecentPositions[position->getHash ()] = std::make_pair (seq, position);
     if (mRecentPositions.size () > 4)
     {
         std::map<uint256, std::pair<int, SHAMap::pointer> >::iterator it = mRecentPositions.begin ();
         while (it != mRecentPositions.end ())
         {
             if (it->second.first < (seq - 2))
             {
                 mRecentPositions.erase (it);
                 return;
             }
             ++it;
         }
     }
 }
std::string ripple::NetworkOPsImp::transactionsSQL (std::string selection, const RippleAddress & account, std::int32_t minLedger, std::int32_t maxLedger, bool descending, std::uint32_t offset, int limit, bool binary, bool count, bool bAdmin) virtual
Implements ripple::NetworkOPs.
Definition at line 1748 of file NetworkOPs.cpp.
References ripple::RippleAddress::humanAccountID(), m_journal, ripple::min(), and beast::Journal::trace.
Referenced by getAccountTxs(), and getAccountTxsB().
 {
     std::uint32_t NONBINARY_PAGE_LENGTH = 200;
     std::uint32_t BINARY_PAGE_LENGTH = 500;
     std::uint32_t numberOfResults;
     if (count)
         numberOfResults = 1000000000;
     else if (limit < 0)
         numberOfResults = binary ? BINARY_PAGE_LENGTH : NONBINARY_PAGE_LENGTH;
     else if (!bAdmin)
         numberOfResults = std::min (binary ? BINARY_PAGE_LENGTH
                                            : NONBINARY_PAGE_LENGTH, static_cast<std::uint32_t> (limit));
     else
         numberOfResults = limit;
     std::string maxClause = "";
     std::string minClause = "";
     if (maxLedger != -1)
         maxClause = boost::str (boost::format ("AND AccountTransactions.LedgerSeq <= '%u'") % maxLedger);
     if (minLedger != -1)
         minClause = boost::str (boost::format ("AND AccountTransactions.LedgerSeq >= '%u'") % minLedger);
     std::string sql;
     if (count)
         sql =
             boost::str (boost::format ("SELECT %s FROM AccountTransactions WHERE Account = '%s' %s %s LIMIT %u, %u;")
             % selection
             % account.humanAccountID ()
             % maxClause
             % minClause
             % beast::lexicalCastThrow <std::string> (offset)
             % beast::lexicalCastThrow <std::string> (numberOfResults)
         );
     else
         sql =
             boost::str (boost::format ("SELECT %s FROM "
                                        "AccountTransactions INNER JOIN Transactions ON Transactions.TransID = AccountTransactions.TransID "
                                        "WHERE Account = '%s' %s %s "
                                        "ORDER BY AccountTransactions.LedgerSeq %s, AccountTransactions.TxnSeq %s, AccountTransactions.TransID %s "
                                        "LIMIT %u, %u;")
                     % selection
                     % account.humanAccountID ()
                     % maxClause
                     % minClause
                     % (descending ? "DESC" : "ASC")
                     % (descending ? "DESC" : "ASC")
                     % (descending ? "DESC" : "ASC")
                     % beast::lexicalCastThrow <std::string> (offset)
                     % beast::lexicalCastThrow <std::string> (numberOfResults)
                    );
     m_journal.trace << "txSQL query: " << sql;
     return sql;
 }
Json::Value ripple::NetworkOPsImp::transJson (const SerializedTransaction & stTxn, TER terResult, bool bValidated, Ledger::ref lpCurrent) private
Definition at line 2439 of file NetworkOPs.cpp.
References ripple::SerializedTransaction::getJson(), Json::objectValue, and ripple::transResultInfo().
Referenced by pubAccountTransaction(), pubProposedTransaction(), and pubValidatedTransaction().
 {
     // This routine should only be used to publish accepted or validated transactions
     Json::Value jvObj (Json::objectValue);
     std::string sToken;
     std::string sHuman;
     transResultInfo (terResult, sToken, sHuman);
     jvObj["type"]           = "transaction";
     jvObj["transaction"]    = stTxn.getJson (0);
     if (bValidated)
     {
         jvObj["ledger_index"]           = lpCurrent->getLedgerSeq ();
         jvObj["ledger_hash"]            = lpCurrent->getHash ().ToString ();
         jvObj["transaction"]["date"]    = lpCurrent->getCloseTimeNC ();
         jvObj["validated"]              = true;
         // WRITEME: Put the account next seq here
     }
     else
     {
         jvObj["validated"]              = false;
         jvObj["ledger_current_index"]   = lpCurrent->getLedgerSeq ();
     }
     jvObj["status"]                 = bValidated ? "closed" : "proposed";
     jvObj["engine_result"]          = sToken;
     jvObj["engine_result_code"]     = terResult;
     jvObj["engine_result_message"]  = sHuman;
     return jvObj;
 }
void ripple::NetworkOPsImp::tryStartConsensus ()
Definition at line 1233 of file NetworkOPs.cpp.
References beginConsensus(), checkLastClosedLedger(), ripple::getApp(), ripple::LedgerMaster::getCurrentLedger(), getNetworkTimeNC(), ripple::base_uint< BITS >::isZero(), m_ledgerMaster, mConsensus, mMode, mNeedNetworkLedger, ripple::NetworkOPs::omCONNECTED, ripple::NetworkOPs::omDISCONNECTED, ripple::NetworkOPs::omFULL, ripple::NetworkOPs::omSYNCING, ripple::NetworkOPs::omTRACKING, and setMode().
Referenced by haveConsensusObject(), and processHeartbeatTimer().
 {
     uint256 networkClosed;
     bool ledgerChange = checkLastClosedLedger (getApp().overlay ().getActivePeers (), networkClosed);
     if (networkClosed.isZero ())
         return;
     // WRITEME: Unless we are in omFULL and in the process of doing a consensus,
     // we must count how many nodes share our LCL, how many nodes disagree with our LCL,
     // and how many validations our LCL has. We also want to check timing to make sure
     // there shouldn't be a newer LCL. We need this information to do the next three
     // tests.
     if (((mMode == omCONNECTED) || (mMode == omSYNCING)) && !ledgerChange)
     {
         // count number of peers that agree with us and UNL nodes whose validations we have for LCL
         // if the ledger is good enough, go to omTRACKING - TODO
         if (!mNeedNetworkLedger)
             setMode (omTRACKING);
     }
     if (((mMode == omCONNECTED) || (mMode == omTRACKING)) && !ledgerChange)
     {
         // check if the ledger is good enough to go to omFULL
         // Note: Do not go to omFULL if we don't have the previous ledger
         // check if the ledger is bad enough to go to omCONNECTED -- TODO
         if (getApp().getOPs ().getNetworkTimeNC () < m_ledgerMaster.getCurrentLedger ()->getCloseTimeNC ())
             setMode (omFULL);
     }
     if ((!mConsensus) && (mMode != omDISCONNECTED))
         beginConsensus (networkClosed, m_ledgerMaster.getCurrentLedger ());
 }
void ripple::NetworkOPsImp::unsubAccount (std::uint64_t uListener, const boost::unordered_set< RippleAddress > & vnaAccountIDs, bool rt) virtual
Implements ripple::InfoSub::Source.
Definition at line 2645 of file NetworkOPs.cpp.
References ripple::RippleAddress::getAccountID(), mLock, mSubAccount, mSubRTAccount, and nothing.
 {
     SubInfoMapType& subMap = rt ? mSubRTAccount : mSubAccount;
     // For the connection, unmonitor each account.
     // FIXME: Don't we need to unsub?
     // BOOST_FOREACH(const RippleAddress& naAccountID, vnaAccountIDs)
     // {
     //  isrListener->deleteSubAccountInfo(naAccountID);
     // }
     ScopedLockType sl (mLock);
     BOOST_FOREACH (const RippleAddress & naAccountID, vnaAccountIDs)
     {
         SubInfoMapType::iterator    simIterator = subMap.find (naAccountID.getAccountID ());
         if (simIterator == subMap.end ())
         {
             // Not found.  Done.
             nothing ();
         }
         else
         {
             // Found
             simIterator->second.erase (uSeq);
             if (simIterator->second.empty ())
             {
                 // Don't need hash entry.
                 subMap.erase (simIterator);
             }
         }
     }
 }
bool ripple::NetworkOPsImp::unsubBook (std::uint64_t uListener, RippleCurrency const & currencyPays, RippleCurrency const & currencyGets, RippleIssuer const & issuerPays, RippleIssuer const & issuerGets) virtual
Implements ripple::InfoSub::Source.
Definition at line 2697 of file NetworkOPs.cpp.
References ripple::getApp(), ripple::OrderBookDB::getBookListeners(), and ripple::Application::getOrderBookDB().
 {
     BookListeners::pointer listeners =
         getApp().getOrderBookDB ().getBookListeners (currencyPays, currencyGets, issuerPays, issuerGets);
     if (listeners)
         listeners->removeSubscriber (uSeq);
     return true;
 }
bool ripple::NetworkOPsImp::unsubLedger (std::uint64_t uListener) virtual
Implements ripple::InfoSub::Source.
Definition at line 2770 of file NetworkOPs.cpp.
References mLock, and mSubLedger.
 {
     ScopedLockType sl (mLock);
     return !!mSubLedger.erase (uSeq);
 }
bool ripple::NetworkOPsImp::unsubRTTransactions (std::uint64_t uListener) virtual
Implements ripple::InfoSub::Source.
Definition at line 2823 of file NetworkOPs.cpp.
References mLock, and mSubRTTransactions.
 {
     ScopedLockType sl (mLock);
     return !!mSubRTTransactions.erase (uSeq);
 }
bool ripple::NetworkOPsImp::unsubServer (std::uint64_t uListener) virtual
Implements ripple::InfoSub::Source.
Definition at line 2795 of file NetworkOPs.cpp.
References mLock, and mSubServer.
 {
     ScopedLockType sl (mLock);
     return !!mSubServer.erase (uSeq);
 }
bool ripple::NetworkOPsImp::unsubTransactions (std::uint64_t uListener) virtual
Implements ripple::InfoSub::Source.
Definition at line 2809 of file NetworkOPs.cpp.
References mLock, and mSubTransactions.
 {
     ScopedLockType sl (mLock);
     return !!mSubTransactions.erase (uSeq);
 }
void ripple::NetworkOPsImp::updateLocalTx (Ledger::ref newValidLedger) inline override virtual
Implements ripple::NetworkOPs.
Definition at line 338 of file NetworkOPs.cpp.
References m_localTX.
     {
         m_localTX->sweep (newValidLedger);
     }
Member Data Documentation
clock_type& ripple::NetworkOPsImp::m_clock private
Definition at line 450 of file NetworkOPs.cpp.
Referenced by beginConsensus().
beast::DeadlineTimer ripple::NetworkOPsImp::m_clusterTimer private
Definition at line 475 of file NetworkOPs.cpp.
Referenced by onDeadlineTimer(), onStop(), and setClusterTimer().
std::unique_ptr<FeeVote> ripple::NetworkOPsImp::m_feeVote private
Definition at line 465 of file NetworkOPs.cpp.
Referenced by beginConsensus().
beast::DeadlineTimer ripple::NetworkOPsImp::m_heartbeatTimer private
Definition at line 474 of file NetworkOPs.cpp.
Referenced by onDeadlineTimer(), onStop(), and setHeartbeatTimer().
beast::Journal ripple::NetworkOPsImp::m_journal private
Definition at line 461 of file NetworkOPs.cpp.
Referenced by beginConsensus(), checkLastClosedLedger(), closeTimeOffset(), endConsensus(), getAccountTxs(), getBookPage(), getDirNodeInfo(), getFetchPack(), getTxsAccount(), gotTXData(), hasTXSet(), haveConsensusObject(), makeFetchPack(), missingNodeInLedger(), processClusterTimer(), processHeartbeatTimer(), processTransactionCb(), processTrustedProposal(), pubAccountTransaction(), pubLedger(), pubProposedTransaction(), recvValidation(), runTransactionQueue(), subAccount(), submitTransaction(), submitTransactionSync(), switchLastClosedLedger(), and transactionsSQL().
LedgerMaster& ripple::NetworkOPsImp::m_ledgerMaster private
Definition at line 480 of file NetworkOPs.cpp.
Referenced by acceptLedger(), beginConsensus(), checkLastClosedLedger(), endConsensus(), getClosedLedger(), getClosedLedgerHash(), getCurrentLedger(), getCurrentLedgerID(), getFullValidatedRange(), getLedgerByHash(), getLedgerBySeq(), getLedgerID(), getPublishedLedger(), getServerInfo(), getValidatedLedger(), getValidatedRange(), getValidatedSeq(), haveConsensusObject(), haveLedger(), haveLedgerRange(), isValidated(), processClusterTimer(), processTransactionCb(), runTransactionQueue(), switchLastClosedLedger(), and tryStartConsensus().
std::unique_ptr<LocalTxs> ripple::NetworkOPsImp::m_localTX private
Definition at line 463 of file NetworkOPs.cpp.
Referenced by addLocalTx(), beginConsensus(), getLocalTxCount(), and updateLocalTx().
InboundLedger::pointer ripple::NetworkOPsImp::mAcquiringLedger private
Definition at line 481 of file NetworkOPs.cpp.
Referenced by checkLastClosedLedger().
int ripple::NetworkOPsImp::mCloseTimeOffset private
Definition at line 483 of file NetworkOPs.cpp.
Referenced by closeTimeOffset(), and getCloseTimeNC().
boost::posix_time::ptime ripple::NetworkOPsImp::mConnectTime private
Definition at line 473 of file NetworkOPs.cpp.
Referenced by setMode().
boost::shared_ptr<LedgerConsensus> ripple::NetworkOPsImp::mConsensus private
Definition at line 476 of file NetworkOPs.cpp.
Referenced by acceptLedger(), beginConsensus(), endConsensus(), getConsensusInfo(), getConsensusLCL(), getTXMap(), gotTXData(), hasTXSet(), haveConsensusObject(), mapComplete(), processHeartbeatTimer(), processTrustedProposal(), stillNeedTXSet(), and tryStartConsensus().
bool ripple::NetworkOPsImp::mFeatureBlocked private
Definition at line 472 of file NetworkOPs.cpp.
Referenced by getServerInfo(), isFeatureBlocked(), setFeatureBlocked(), and setMode().
TaggedCache< uint256, Blob> ripple::NetworkOPsImp::mFetchPack private
Definition at line 505 of file NetworkOPs.cpp.
Referenced by addFetchPack(), getFetchPack(), getFetchSize(), getServerInfo(), and sweepFetchPack().
std::uint32_t ripple::NetworkOPsImp::mFetchSeq private
Definition at line 506 of file NetworkOPs.cpp.
Referenced by shouldFetchPack().
int ripple::NetworkOPsImp::mLastCloseConvergeTime private
Definition at line 486 of file NetworkOPs.cpp.
Referenced by getPreviousConvergeTime(), and newLCL().
uint256 ripple::NetworkOPsImp::mLastCloseHash private
Definition at line 487 of file NetworkOPs.cpp.
Referenced by newLCL().
int ripple::NetworkOPsImp::mLastCloseProposers private
Definition at line 486 of file NetworkOPs.cpp.
Referenced by getPreviousProposers(), newLCL(), and storeProposal().
std::uint32_t ripple::NetworkOPsImp::mLastCloseTime private
Definition at line 488 of file NetworkOPs.cpp.
Referenced by getLastCloseTime(), and setLastCloseTime().
std::uint32_t ripple::NetworkOPsImp::mLastLoadBase private
Definition at line 508 of file NetworkOPs.cpp.
Referenced by pubServer(), and reportFeeChange().
std::uint32_t ripple::NetworkOPsImp::mLastLoadFactor private
Definition at line 509 of file NetworkOPs.cpp.
Referenced by pubServer(), and reportFeeChange().
SerializedValidation::pointer ripple::NetworkOPsImp::mLastValidation private
Definition at line 490 of file NetworkOPs.cpp.
Referenced by getLastValidation(), and setLastValidation().
std::uint32_t ripple::NetworkOPsImp::mLastValidationTime private
Definition at line 489 of file NetworkOPs.cpp.
Referenced by getValidationTimeNC().
LockType ripple::NetworkOPsImp::mLock private
Definition at line 467 of file NetworkOPs.cpp.
Referenced by addRpcSub(), findRpcSub(), pubAccountTransaction(), pubLedger(), pubProposedTransaction(), pubServer(), pubValidatedTransaction(), subAccount(), subLedger(), subRTTransactions(), subServer(), subTransactions(), unsubAccount(), unsubLedger(), unsubRTTransactions(), unsubServer(), and unsubTransactions().
OperatingMode ripple::NetworkOPsImp::mMode private
Definition at line 469 of file NetworkOPs.cpp.
Referenced by beginConsensus(), checkLastClosedLedger(), consensusViewChange(), getOperatingMode(), haveConsensusObject(), isFull(), processHeartbeatTimer(), processTransactionCb(), processTrustedProposal(), pubLedger(), setMode(), strOperatingMode(), subLedger(), and tryStartConsensus().
bool ripple::NetworkOPsImp::mNeedNetworkLedger private
Definition at line 470 of file NetworkOPs.cpp.
Referenced by clearNeedNetworkLedger(), getServerInfo(), isFull(), isNeedNetworkLedger(), needNetworkLedger(), and tryStartConsensus().
bool ripple::NetworkOPsImp::mProposing private
Definition at line 471 of file NetworkOPs.cpp.
Referenced by isProposing(), setProposing(), and strOperatingMode().
std::map<uint256, std::pair<int, SHAMap::pointer> > ripple::NetworkOPsImp::mRecentPositions private
Definition at line 493 of file NetworkOPs.cpp.
Referenced by getTXMap(), and takePosition().
subRpcMapType ripple::NetworkOPsImp::mRpcSubMap private
Definition at line 498 of file NetworkOPs.cpp.
Referenced by addRpcSub(), and findRpcSub().
ripple::unordered_map< uint160, std::list<LedgerProposal::pointer> > ripple::NetworkOPsImp::mStoredProposals private
Definition at line 478 of file NetworkOPs.cpp.
Referenced by peekStoredProposals(), and storeProposal().
SubInfoMapType ripple::NetworkOPsImp::mSubAccount private
Definition at line 495 of file NetworkOPs.cpp.
Referenced by pubAccountTransaction(), subAccount(), and unsubAccount().
SubMapType ripple::NetworkOPsImp::mSubLedger private
Definition at line 500 of file NetworkOPs.cpp.
Referenced by pubLedger(), subLedger(), and unsubLedger().
SubInfoMapType ripple::NetworkOPsImp::mSubRTAccount private
Definition at line 496 of file NetworkOPs.cpp.
Referenced by pubAccountTransaction(), subAccount(), and unsubAccount().
SubMapType ripple::NetworkOPsImp::mSubRTTransactions private
Definition at line 503 of file NetworkOPs.cpp.
Referenced by pubProposedTransaction(), pubValidatedTransaction(), subRTTransactions(), and unsubRTTransactions().
SubMapType ripple::NetworkOPsImp::mSubServer private
Definition at line 501 of file NetworkOPs.cpp.
Referenced by pubServer(), subServer(), and unsubServer().
SubMapType ripple::NetworkOPsImp::mSubTransactions private
Definition at line 502 of file NetworkOPs.cpp.
Referenced by pubValidatedTransaction(), subTransactions(), and unsubTransactions().
bool ripple::NetworkOPsImp::mValidating private
Definition at line 471 of file NetworkOPs.cpp.
Referenced by isValidating(), setProposing(), and strOperatingMode().
The documentation for this class was generated from the following file:
rippled/src/ripple_app/misc/NetworkOPs.cpp