rippled: ripple::MultiSocket::Flag Struct Reference
ripple::MultiSocket::Flag Struct Reference
#include <MultiSocket.h>
Public Types
enum Bit {
peer = 0, client_role = 1, server_role = 2, proxy = 4,
ssl = 8, ssl_required = 16
}
Public Member Functions
Flag (int flags=0) noexcept
Flag & operator= (int mask) noexcept
bool operator== (Flag const &other) const noexcept
bool set (int mask) const noexcept
bool any_set (int mask) const noexcept
Flag with (int mask) const noexcept
Flag without (int mask) const noexcept
int asBits () const noexcept
Private Attributes
int m_flags
Detailed Description
Definition at line 33 of file MultiSocket.h.
Member Enumeration Documentation
enum ripple::MultiSocket::Flag::Bit
Enumerator
peer
client_role
server_role
proxy
ssl
ssl_required
Definition at line 35 of file MultiSocket.h.
         {
             peer = 0,           // no handshaking. remaining flags ignored.
             client_role = 1,    // operate in client role
             server_role = 2,    // operate in server role
             proxy = 4,          // client: will send PROXY handshake
                                 // server: PROXY handshake required
             ssl = 8,            // client: will use ssl
                                 // server: will allow, but not require ssl
             ssl_required = 16   // client: ignored
                                 // server: will require ssl (ignores ssl flag)
         };
Constructor & Destructor Documentation
ripple::MultiSocket::Flag::Flag (int flags = 0) inline noexcept
Definition at line 51 of file MultiSocket.h.
Referenced by with(), and without().
             : m_flags (flags)
         {
         }
Member Function Documentation
bool ripple::MultiSocket::Flag::any_set (int mask) const inline noexcept
Definition at line 72 of file MultiSocket.h.
References m_flags.
Referenced by ripple::MultiSocketType< socket_type & >::initHandshake().
         {
             return (m_flags & mask) != 0;
         }
int ripple::MultiSocket::Flag::asBits () const inline noexcept
Definition at line 87 of file MultiSocket.h.
References m_flags.
         {
             return m_flags;
         }
Flag& ripple::MultiSocket::Flag::operator= (int mask) inline noexcept
Definition at line 56 of file MultiSocket.h.
References m_flags.
         {
             m_flags = mask;
             return *this;
         }
bool ripple::MultiSocket::Flag::operator== (Flag const & other) const inline noexcept
Definition at line 62 of file MultiSocket.h.
References m_flags.
         {
             return m_flags == other.m_flags;
         }
bool ripple::MultiSocket::Flag::set (int mask) const inline noexcept
Definition at line 67 of file MultiSocket.h.
References m_flags.
Referenced by ripple::MultiSocketType< socket_type & >::initHandshake(), ripple::MultiSocketType< socket_type & >::initState(), ripple::MultiSocketType< socket_type & >::is_client(), and ripple::MultiSocketType< socket_type & >::is_server().
         {
             return (m_flags & mask) == mask;
         }
Flag ripple::MultiSocket::Flag::with (int mask) const inline noexcept
Definition at line 77 of file MultiSocket.h.
References Flag(), and m_flags.
Referenced by ripple::OverlayImpl::accept(), ripple::MultiSocketType< socket_type & >::do_handshake(), and ripple::MultiSocketType< socket_type & >::initHandshake().
         {
             return Flag (m_flags | mask);
         }
Flag ripple::MultiSocket::Flag::without (int mask) const inline noexcept
Definition at line 82 of file MultiSocket.h.
References Flag(), and m_flags.
Referenced by ripple::MultiSocketType< socket_type & >::cleaned_flags(), ripple::MultiSocketType< socket_type & >::do_handshake(), ripple::MultiSocketType< socket_type & >::initHandshake(), and ripple::MultiSocketType< socket_type & >::initState().
         {
             return Flag (m_flags & ~mask);
         }
Member Data Documentation
int ripple::MultiSocket::Flag::m_flags private
Definition at line 93 of file MultiSocket.h.
Referenced by any_set(), asBits(), operator=(), operator==(), set(), with(), and without().
The documentation for this struct was generated from the following file:
rippled/src/ripple/common/MultiSocket.h