rippled: beast::NumberToStringConverters Class Reference
beast::NumberToStringConverters Class Reference
#include <StringFromNumber.h>
Classes
struct StackArrayStream
Public Types
enum { charsNeededForInt = 32, charsNeededForDouble = 48 }
Static Public Member Functions
template<typename Type >
static char * printDigits (char *t, Type v) noexcept
template<typename IntegerType >
static char * numberToString (char *t, IntegerType const n) noexcept
static char * doubleToString (char *buffer, const int numChars, double n, int numDecPlaces, size_t &len) noexcept
static StringCharPointerType createFromFixedLength (const char *const src, const size_t numChars)
template<typename IntegerType >
static StringCharPointerType createFromInteger (const IntegerType number)
static StringCharPointerType createFromDouble (const double number, const int numberOfDecimalPlaces)
Detailed Description
Definition at line 40 of file StringFromNumber.h.
Member Enumeration Documentation
anonymous enum
Enumerator
charsNeededForInt
charsNeededForDouble
Definition at line 43 of file StringFromNumber.h.
     {
         charsNeededForInt = 32,
         charsNeededForDouble = 48
     };
Member Function Documentation
static StringCharPointerType beast::NumberToStringConverters::createFromDouble (const double number, const int numberOfDecimalPlaces) inline static
Definition at line 165 of file StringFromNumber.h.
References charsNeededForDouble, createFromFixedLength(), doubleToString(), and beast::numElementsInArray().
Referenced by beast::String::fromNumber().
     {
         char buffer [charsNeededForDouble];
         size_t len;
         char* const start = doubleToString (buffer, numElementsInArray (buffer), (double) number, numberOfDecimalPlaces, len);
         return createFromFixedLength (start, len);
     }
StringCharPointerType beast::NumberToStringConverters::createFromFixedLength (const char *const src, const size_t numChars) static
Definition at line 249 of file String.cpp.
References beast::StringHolder::createFromFixedLength().
Referenced by createFromDouble(), and createFromInteger().
 {
     return StringHolder::createFromFixedLength (src, numChars);
 }
template<typename IntegerType > static StringCharPointerType beast::NumberToStringConverters::createFromInteger (const IntegerType number) inline static
Definition at line 157 of file StringFromNumber.h.
References charsNeededForInt, createFromFixedLength(), numberToString(), and beast::numElementsInArray().
Referenced by beast::String::fromNumber().
     {
         char buffer [charsNeededForInt];
         char* const end = buffer + numElementsInArray (buffer);
         char* const start = numberToString (end, number);
         return createFromFixedLength (start, (size_t) (end - start - 1));
     }
static char* beast::NumberToStringConverters::doubleToString (char * buffer, const int numChars, double n, int numDecPlaces, size_t & len) inline static noexcept
Definition at line 119 of file StringFromNumber.h.
References bassert, charsNeededForDouble, and beast::NumberToStringConverters::StackArrayStream::writeDouble().
Referenced by createFromDouble().
     {
         if (numDecPlaces > 0 && numDecPlaces < 7 && n > -1.0e20 && n < 1.0e20)
         {
             char* const end = buffer + numChars;
             char* t = end;
             std::int64_t v = (std::int64_t) (pow (10.0, numDecPlaces) * std::abs (n) + 0.5);
             *--t = (char) 0;
             while (numDecPlaces >= 0 || v > 0)
             {
                 if (numDecPlaces == 0)
                     *--t = '.';
                 *--t = (char) ('0' + (v % 10));
                 v /= 10;
                 --numDecPlaces;
             }
             if (n < 0)
                 *--t = '-';
             len = (size_t) (end - t - 1);
             return t;
         }
         StackArrayStream strm (buffer);
         len = strm.writeDouble (n, numDecPlaces);
         bassert (len <= charsNeededForDouble);
         return buffer;
     }
template<typename IntegerType > static char* beast::NumberToStringConverters::numberToString (char * t, IntegerType const n) inline static noexcept
Definition at line 73 of file StringFromNumber.h.
References printDigits().
Referenced by createFromInteger(), and beast::String::operator+=().
     {
         if (std::numeric_limits <IntegerType>::is_signed)
         {
             if (n >= 0)
                 return printDigits (t, static_cast <std::uint64_t> (n));
             // NB: this needs to be careful not to call
             // -std::numeric_limits<std::int64_t>::min(),
             // which has undefined behaviour
             //
             t = printDigits (t, static_cast <std::uint64_t> (-(n + 1)) + 1);
             *--t = '-';
             return t;
         }
         return printDigits (t, n);
     }
template<typename Type > static char* beast::NumberToStringConverters::printDigits (char * t, Type v) inline static noexcept
Definition at line 51 of file StringFromNumber.h.
Referenced by numberToString().
     {
         *--t = 0;
         do
         {
             *--t = '0' + (char) (v % 10);
             v /= 10;
         }
         while (v > 0);
         return t;
     }
The documentation for this class was generated from the following files:
rippled/src/beast/beast/strings/StringFromNumber.h
rippled/src/beast/beast/strings/impl/String.cpp