rippled: rocksdb::RandomRWFile Class Reference
rocksdb::RandomRWFile Class Reference abstract
#include <env.h>
Public Member Functions
RandomRWFile ()
virtual ~RandomRWFile ()
virtual Status Write (uint64_t offset, const Slice &data)=0
virtual Status Read (uint64_t offset, size_t n, Slice *result, char *scratch) const =0
virtual Status Close ()=0
virtual Status Sync ()=0
virtual Status Fsync ()
virtual Status Allocate (off_t offset, off_t len)
Private Member Functions
RandomRWFile (const RandomRWFile &)
void operator= (const RandomRWFile &)
Detailed Description
Definition at line 443 of file env.h.
Constructor & Destructor Documentation
rocksdb::RandomRWFile::RandomRWFile () inline
Definition at line 445 of file env.h.
 {}
virtual rocksdb::RandomRWFile::~RandomRWFile () inline virtual
Definition at line 446 of file env.h.
 {}
rocksdb::RandomRWFile::RandomRWFile (const RandomRWFile &) private
Member Function Documentation
virtual Status rocksdb::RandomRWFile::Allocate (off_t offset, off_t len) inline virtual
Definition at line 481 of file env.h.
References rocksdb::Status::OK().
Referenced by rocksdb::TEST().
{
     return Status::OK();
   }
virtual Status rocksdb::RandomRWFile::Close () pure virtual
Referenced by rocksdb::TEST().
virtual Status rocksdb::RandomRWFile::Fsync () inline virtual
Definition at line 474 of file env.h.
References Sync().
Referenced by rocksdb::TEST().
{
     return Sync();
   }
void rocksdb::RandomRWFile::operator= (const RandomRWFile &) private
virtual Status rocksdb::RandomRWFile::Read (uint64_t offset, size_t n, Slice * result, char * scratch) const pure virtual
Referenced by rocksdb::TEST().
virtual Status rocksdb::RandomRWFile::Sync () pure virtual
Referenced by Fsync(), and rocksdb::TEST().
virtual Status rocksdb::RandomRWFile::Write (uint64_t offset, const Slice & data) pure virtual
Referenced by rocksdb::TEST().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/include/rocksdb/env.h