rippled: ripple::LogFile Class Reference
ripple::LogFile Class Reference
#include <LogFile.h>
Public Member Functions
LogFile ()
~LogFile ()
bool isOpen () const noexcept
bool open (boost::filesystem::path const &path)
bool closeAndReopen ()
void close ()
void write (char const *text)
void writeln (char const *text)
void write (std::string const &str)
void writeln (std::string const &str)
Private Attributes
std::unique_ptr< std::ofstream > m_stream
boost::filesystem::path m_path
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
Manages a system file containing logged output.
The system file remains open during program execution. Interfaces are provided for interoperating with standard log management tools like logrotate(8):
http://linuxcommand.org/man_pages/logrotate8.html
Note
None of the listed interfaces are thread-safe.
Definition at line 35 of file LogFile.h.
Constructor & Destructor Documentation
ripple::LogFile::LogFile ()
Construct with no associated system file.
A system file may be associated later with open.
See Also
open
Definition at line 24 of file LogFile.cpp.
     : m_stream (nullptr)
 {
 }
ripple::LogFile::~LogFile ()
Destroy the object.
If a system file is associated, it will be flushed and closed.
Definition at line 29 of file LogFile.cpp.
 {
 }
Member Function Documentation
void ripple::LogFile::close ()
Close the system file if it is open.
Definition at line 67 of file LogFile.cpp.
References m_stream.
Referenced by closeAndReopen(), and open().
 {
     m_stream = nullptr;
 }
bool ripple::LogFile::closeAndReopen ()
Close and re-open the system file associated with the log
This assists in interoperating with external log management tools.
Returns
true if the file was opened.
Definition at line 60 of file LogFile.cpp.
References close(), m_path, and open().
Referenced by ripple::LogSink::rotateLog().
 {
     close ();
     return open (m_path);
 }
bool ripple::LogFile::isOpen () const noexcept
Determine if a system file is associated with the log.
Returns
true if a system file is associated and opened for writing.
Definition at line 33 of file LogFile.cpp.
References m_stream.
 {
     return m_stream != nullptr;
 }
bool ripple::LogFile::open (boost::filesystem::path const & path)
Associate a system file with the log.
If the file does not exist an attempt is made to create it and open it for writing. If the file already exists an attempt is made to open it for appending.
If a system file is already associated with the log, it is closed first.
Returns
true if the file was opened.
Definition at line 38 of file LogFile.cpp.
References close(), m_path, m_stream, and beast.util.CleanCPPFiles::path.
Referenced by closeAndReopen(), and ripple::LogSink::setLogFile().
 {
     close ();
     bool wasOpened = false;
     // VFALCO TODO Make this work with Unicode file paths
     std::unique_ptr <std::ofstream> stream (
         new std::ofstream (path.c_str (), std::fstream::app));
     if (stream->good ())
     {
         m_path = path;
         m_stream = std::move (stream);
         wasOpened = true;
     }
     return wasOpened;
 }
void ripple::LogFile::write (char const * text)
write to the log file.
Does nothing if there is no associated system file.
Definition at line 72 of file LogFile.cpp.
References m_stream.
 {
     if (m_stream != nullptr)
         (*m_stream) << text;
 }
void ripple::LogFile::write (std::string const & str) inline
Write to the log file using std::string.
Definition at line 100 of file LogFile.h.
References write().
Referenced by write().
 { write (str.c_str ()); }
void ripple::LogFile::writeln (char const * text)
write to the log file and append an end of line marker.
Does nothing if there is no associated system file.
Definition at line 78 of file LogFile.cpp.
References m_stream.
Referenced by ripple::LogSink::write().
 {
     if (m_stream != nullptr)
     {
         (*m_stream) << text;
         (*m_stream) << std::endl;
     }
 }
void ripple::LogFile::writeln (std::string const & str) inline
Definition at line 101 of file LogFile.h.
References writeln().
Referenced by writeln().
 { writeln (str.c_str ()); }
Member Data Documentation
boost::filesystem::path ripple::LogFile::m_path private
Definition at line 105 of file LogFile.h.
Referenced by closeAndReopen(), and open().
std::unique_ptr<std::ofstream> ripple::LogFile::m_stream private
Definition at line 104 of file LogFile.h.
Referenced by close(), isOpen(), open(), write(), and writeln().
The documentation for this class was generated from the following files:
rippled/src/ripple_basics/log/LogFile.h
rippled/src/ripple_basics/log/LogFile.cpp