rippled: beast::ObjCClass< SuperclassType > Struct Template Reference
beast::ObjCClass< SuperclassType > Struct Template Reference
#include <osx_ObjCHelpers.h>
Public Member Functions
ObjCClass (const char *nameRoot)
~ObjCClass ()
void registerClass ()
SuperclassType * createInstance () const
template<typename Type >
void addIvar (const char *name)
template<typename FunctionType >
void addMethod (SEL selector, FunctionType callbackFn, const char *signature)
template<typename FunctionType >
void addMethod (SEL selector, FunctionType callbackFn, const char *sig1, const char *sig2)
template<typename FunctionType >
void addMethod (SEL selector, FunctionType callbackFn, const char *sig1, const char *sig2, const char *sig3)
template<typename FunctionType >
void addMethod (SEL selector, FunctionType callbackFn, const char *sig1, const char *sig2, const char *sig3, const char *sig4)
void addProtocol (Protocol *protocol)
Static Public Member Functions
static id sendSuperclassMessage (id self, SEL selector)
template<typename Type >
static Type getIvar (id self, const char *name)
Public Attributes
Class cls
Static Private Member Functions
static String getRandomisedName (const char *root)
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
template<typename SuperclassType>
struct beast::ObjCClass< SuperclassType >
Definition at line 69 of file osx_ObjCHelpers.h.
Constructor & Destructor Documentation
template<typename SuperclassType > beast::ObjCClass< SuperclassType >::ObjCClass (const char * nameRoot) inline
Definition at line 71 of file osx_ObjCHelpers.h.
         : cls (objc_allocateClassPair ([SuperclassType class], getRandomisedName (nameRoot).toUTF8(), 0))
     {
     }
template<typename SuperclassType > beast::ObjCClass< SuperclassType >::~ObjCClass () inline
Definition at line 76 of file osx_ObjCHelpers.h.
References beast::ObjCClass< SuperclassType >::cls.
     {
         objc_disposeClassPair (cls);
     }
Member Function Documentation
template<typename SuperclassType > template<typename Type > void beast::ObjCClass< SuperclassType >::addIvar (const char * name) inline
Definition at line 92 of file osx_ObjCHelpers.h.
References bassert, and beast::ObjCClass< SuperclassType >::cls.
     {
         BOOL b = class_addIvar (cls, name, sizeof (Type), (uint8_t) rint (log2 (sizeof (Type))), @encode (Type));
         bassert (b); (void) b;
     }
template<typename SuperclassType > template<typename FunctionType > void beast::ObjCClass< SuperclassType >::addMethod (SEL selector, FunctionType callbackFn, const char * signature) inline
Definition at line 99 of file osx_ObjCHelpers.h.
References bassert, and beast::ObjCClass< SuperclassType >::cls.
Referenced by beast::ObjCClass< SuperclassType >::addMethod().
     {
         BOOL b = class_addMethod (cls, selector, (IMP) callbackFn, signature);
         bassert (b); (void) b;
     }
template<typename SuperclassType > template<typename FunctionType > void beast::ObjCClass< SuperclassType >::addMethod (SEL selector, FunctionType callbackFn, const char * sig1, const char * sig2) inline
Definition at line 106 of file osx_ObjCHelpers.h.
References beast::ObjCClass< SuperclassType >::addMethod().
     {
         addMethod (selector, callbackFn, (String (sig1) + sig2).toUTF8());
     }
template<typename SuperclassType > template<typename FunctionType > void beast::ObjCClass< SuperclassType >::addMethod (SEL selector, FunctionType callbackFn, const char * sig1, const char * sig2, const char * sig3) inline
Definition at line 112 of file osx_ObjCHelpers.h.
References beast::ObjCClass< SuperclassType >::addMethod().
     {
         addMethod (selector, callbackFn, (String (sig1) + sig2 + sig3).toUTF8());
     }
template<typename SuperclassType > template<typename FunctionType > void beast::ObjCClass< SuperclassType >::addMethod (SEL selector, FunctionType callbackFn, const char * sig1, const char * sig2, const char * sig3, const char * sig4) inline
Definition at line 118 of file osx_ObjCHelpers.h.
References beast::ObjCClass< SuperclassType >::addMethod().
     {
         addMethod (selector, callbackFn, (String (sig1) + sig2 + sig3 + sig4).toUTF8());
     }
template<typename SuperclassType > void beast::ObjCClass< SuperclassType >::addProtocol (Protocol * protocol) inline
Definition at line 123 of file osx_ObjCHelpers.h.
References bassert, and beast::ObjCClass< SuperclassType >::cls.
     {
         BOOL b = class_addProtocol (cls, protocol);
         bassert (b); (void) b;
     }
template<typename SuperclassType > SuperclassType* beast::ObjCClass< SuperclassType >::createInstance () const inline
Definition at line 86 of file osx_ObjCHelpers.h.
References beast::ObjCClass< SuperclassType >::cls.
     {
         return class_createInstance (cls, 0);
     }
template<typename SuperclassType > template<typename Type > static Type beast::ObjCClass< SuperclassType >::getIvar (id self, const char * name) inline static
Definition at line 136 of file osx_ObjCHelpers.h.
     {
         void* v = nullptr;
         object_getInstanceVariable (self, name, &v);
         return static_cast <Type> (v);
     }
template<typename SuperclassType > static String beast::ObjCClass< SuperclassType >::getRandomisedName (const char * root) inline static private
Definition at line 146 of file osx_ObjCHelpers.h.
References beast::Random::getSystemRandom(), and beast::String::toHexString().
     {
         return root + String::toHexString (beast::Random::getSystemRandom().nextInt64());
     }
template<typename SuperclassType > void beast::ObjCClass< SuperclassType >::registerClass () inline
Definition at line 81 of file osx_ObjCHelpers.h.
References beast::ObjCClass< SuperclassType >::cls.
     {
         objc_registerClassPair (cls);
     }
template<typename SuperclassType > static id beast::ObjCClass< SuperclassType >::sendSuperclassMessage (id self, SEL selector) inline static
Definition at line 129 of file osx_ObjCHelpers.h.
     {
         objc_super s = { self, [SuperclassType class] };
         return objc_msgSendSuper (&s, selector);
     }
Member Data Documentation
template<typename SuperclassType > Class beast::ObjCClass< SuperclassType >::cls
Definition at line 143 of file osx_ObjCHelpers.h.
Referenced by beast::ObjCClass< SuperclassType >::addIvar(), beast::ObjCClass< SuperclassType >::addMethod(), beast::ObjCClass< SuperclassType >::addProtocol(), beast::ObjCClass< SuperclassType >::createInstance(), beast::ObjCClass< SuperclassType >::registerClass(), and beast::ObjCClass< SuperclassType >::~ObjCClass().
The documentation for this struct was generated from the following file:
rippled/src/beast/modules/beast_core/native/osx_ObjCHelpers.h