rippled: ripple::UniqueNodeList Class Reference
ripple::UniqueNodeList Class Reference abstract
#include <UniqueNodeList.h>
Public Types
enum ValidatorSource {
vsConfig = 'C', vsInbound = 'I', vsManual = 'M', vsReferral = 'R',
vsTold = 'T', vsValidator = 'V', vsWeb = 'W'
}
typedef long score
Public Member Functions
virtual ~UniqueNodeList ()
virtual void start ()=0
virtual void nodeAddPublic (const RippleAddress &naNodePublic, ValidatorSource vsWhy, const std::string &strComment)=0
virtual void nodeAddDomain (std::string strDomain, ValidatorSource vsWhy, const std::string &strComment="")=0
virtual void nodeRemovePublic (const RippleAddress &naNodePublic)=0
virtual void nodeRemoveDomain (std::string strDomain)=0
virtual void nodeReset ()=0
virtual void nodeScore ()=0
virtual bool nodeInUNL (const RippleAddress &naNodePublic)=0
virtual bool nodeInCluster (const RippleAddress &naNodePublic)=0
virtual bool nodeInCluster (const RippleAddress &naNodePublic, std::string &name)=0
virtual bool nodeUpdate (const RippleAddress &naNodePublic, ClusterNodeStatus const &cnsStatus)=0
virtual std::map
< RippleAddress,
ClusterNodeStatus > getClusterStatus ()=0
virtual std::uint32_t getClusterFee ()=0
virtual void addClusterStatus (Json::Value &)=0
virtual void nodeBootstrap ()=0
virtual bool nodeLoad (boost::filesystem::path pConfig)=0
virtual void nodeNetwork ()=0
virtual Json::Value getUnlJson ()=0
virtual int iSourceScore (ValidatorSource vsWhy)=0
Public Member Functions inherited from beast::Stoppable
Stoppable (char const *name, Stoppable &parent)
virtual ~Stoppable ()
bool isStopping () const
bool isStopped () const
bool areChildrenStopped () const
void stopped ()
virtual void onPrepare ()
virtual void onStart ()
virtual void onStop ()
virtual void onChildrenStopped ()
Static Public Member Functions
static UniqueNodeList * New (Stoppable &parent)
Protected Member Functions
UniqueNodeList (Stoppable &parent)
Protected Member Functions inherited from beast::Stoppable
Stoppable (char const *name, RootStoppable &root)
Additional Inherited Members
Protected Attributes inherited from beast::Stoppable
char const * m_name
RootStoppable & m_root
Child m_child
Atomic< int > m_started
bool volatile m_stopped
bool volatile m_childrenStopped
Children m_children
WaitableEvent m_stoppedEvent
Detailed Description
Definition at line 25 of file UniqueNodeList.h.
Member Typedef Documentation
typedef long ripple::UniqueNodeList::score
Definition at line 43 of file UniqueNodeList.h.
Member Enumeration Documentation
enum ripple::UniqueNodeList::ValidatorSource
Enumerator
vsConfig
vsInbound
vsManual
vsReferral
vsTold
vsValidator
vsWeb
Definition at line 31 of file UniqueNodeList.h.
     {
         vsConfig    = 'C',  // rippled.cfg
         vsInbound   = 'I',
         vsManual    = 'M',
         vsReferral  = 'R',
         vsTold      = 'T',
         vsValidator = 'V',  // validators.txt
         vsWeb       = 'W',
     };
Constructor & Destructor Documentation
ripple::UniqueNodeList::UniqueNodeList (Stoppable & parent) explicit protected
Definition at line 2039 of file UniqueNodeList.cpp.
     : Stoppable ("UniqueNodeList", parent)
 {
 }
virtual ripple::UniqueNodeList::~UniqueNodeList () inline virtual
Definition at line 49 of file UniqueNodeList.h.
 { }
Member Function Documentation
virtual void ripple::UniqueNodeList::addClusterStatus (Json::Value &) pure virtual
Implemented in ripple::UniqueNodeListImp.
Referenced by ripple::RPCHandler::doPeers().
virtual std::uint32_t ripple::UniqueNodeList::getClusterFee () pure virtual
Implemented in ripple::UniqueNodeListImp.
virtual std::map<RippleAddress, ClusterNodeStatus> ripple::UniqueNodeList::getClusterStatus () pure virtual
Implemented in ripple::UniqueNodeListImp.
Referenced by ripple::NetworkOPsImp::processClusterTimer().
virtual Json::Value ripple::UniqueNodeList::getUnlJson () pure virtual
Implemented in ripple::UniqueNodeListImp.
Referenced by ripple::RPCHandler::doUnlList().
virtual int ripple::UniqueNodeList::iSourceScore (ValidatorSource vsWhy) pure virtual
Implemented in ripple::UniqueNodeListImp.
UniqueNodeList * ripple::UniqueNodeList::New (Stoppable & parent) static
Definition at line 2046 of file UniqueNodeList.cpp.
 {
     return new UniqueNodeListImp (parent);
 }
virtual void ripple::UniqueNodeList::nodeAddDomain (std::string strDomain, ValidatorSource vsWhy, const std::string & strComment = "") pure virtual
Implemented in ripple::UniqueNodeListImp.
Referenced by ripple::RPCHandler::doUnlAdd().
virtual void ripple::UniqueNodeList::nodeAddPublic (const RippleAddress & naNodePublic, ValidatorSource vsWhy, const std::string & strComment) pure virtual
Implemented in ripple::UniqueNodeListImp.
Referenced by ripple::RPCHandler::doUnlAdd().
virtual void ripple::UniqueNodeList::nodeBootstrap () pure virtual
Implemented in ripple::UniqueNodeListImp.
Referenced by ripple::ApplicationImp::setup().
virtual bool ripple::UniqueNodeList::nodeInCluster (const RippleAddress & naNodePublic) pure virtual
Implemented in ripple::UniqueNodeListImp.
Referenced by ripple::PeerImp::recvHello().
virtual bool ripple::UniqueNodeList::nodeInCluster (const RippleAddress & naNodePublic, std::string & name) pure virtual
Implemented in ripple::UniqueNodeListImp.
virtual bool ripple::UniqueNodeList::nodeInUNL (const RippleAddress & naNodePublic) pure virtual
Implemented in ripple::UniqueNodeListImp.
Referenced by ripple::ValidationsImp::addValidation(), ripple::PeerImp::recvPropose(), and ripple::PeerImp::recvValidation().
virtual bool ripple::UniqueNodeList::nodeLoad (boost::filesystem::path pConfig) pure virtual
Implemented in ripple::UniqueNodeListImp.
Referenced by ripple::RPCHandler::doUnlLoad().
virtual void ripple::UniqueNodeList::nodeNetwork () pure virtual
Implemented in ripple::UniqueNodeListImp.
Referenced by ripple::RPCHandler::doUnlNetwork().
virtual void ripple::UniqueNodeList::nodeRemoveDomain (std::string strDomain) pure virtual
Implemented in ripple::UniqueNodeListImp.
Referenced by ripple::RPCHandler::doUnlDelete().
virtual void ripple::UniqueNodeList::nodeRemovePublic (const RippleAddress & naNodePublic) pure virtual
Implemented in ripple::UniqueNodeListImp.
Referenced by ripple::RPCHandler::doUnlDelete().
virtual void ripple::UniqueNodeList::nodeReset () pure virtual
Implemented in ripple::UniqueNodeListImp.
Referenced by ripple::RPCHandler::doUnlReset().
virtual void ripple::UniqueNodeList::nodeScore () pure virtual
Implemented in ripple::UniqueNodeListImp.
Referenced by ripple::RPCHandler::doUnlScore().
virtual bool ripple::UniqueNodeList::nodeUpdate (const RippleAddress & naNodePublic, ClusterNodeStatus const & cnsStatus) pure virtual
Implemented in ripple::UniqueNodeListImp.
Referenced by ripple::PeerImp::recvCluster().
virtual void ripple::UniqueNodeList::start () pure virtual
Implemented in ripple::UniqueNodeListImp.
Referenced by ripple::LocalCredentials::start().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/peers/UniqueNodeList.h
rippled/src/ripple_app/peers/UniqueNodeList.cpp