rippled: rocksdb::ManifestDumpCommand Class Reference
rocksdb::ManifestDumpCommand Class Reference
#include <ldb_cmd.h>
Public Member Functions
ManifestDumpCommand (const vector< string > &params, const map< string, string > &options, const vector< string > &flags)
virtual void DoCommand ()
virtual bool NoDBOpen ()
Public Member Functions inherited from rocksdb::LDBCommand
bool ValidateCmdLineOptions ()
virtual Options PrepareOptionsForOpenDB ()
virtual void SetOptions (Options options)
virtual ~LDBCommand ()
void Run ()
LDBCommandExecuteResult GetExecuteState ()
void ClearPreviousRunState ()
Static Public Member Functions
static string Name ()
static void Help (string &ret)
Static Public Member Functions inherited from rocksdb::LDBCommand
static LDBCommand * InitFromCmdLineArgs (const vector< string > &args, const Options &options=Options())
static LDBCommand * InitFromCmdLineArgs (int argc, char **argv, const Options &options=Options())
static string HexToString (const string &str)
static string StringToHex (const string &str)
Private Attributes
bool verbose_
string path_
Static Private Attributes
static const string ARG_VERBOSE = "verbose"
static const string ARG_PATH = "path"
Additional Inherited Members
Static Public Attributes inherited from rocksdb::LDBCommand
static const string ARG_DB = "db"
static const string ARG_HEX = "hex"
static const string ARG_KEY_HEX = "key_hex"
static const string ARG_VALUE_HEX = "value_hex"
static const string ARG_TTL = "ttl"
static const string ARG_TTL_START = "start_time"
static const string ARG_TTL_END = "end_time"
static const string ARG_TIMESTAMP = "timestamp"
static const string ARG_FROM = "from"
static const string ARG_TO = "to"
static const string ARG_MAX_KEYS = "max_keys"
static const string ARG_BLOOM_BITS = "bloom_bits"
static const string ARG_COMPRESSION_TYPE = "compression_type"
static const string ARG_BLOCK_SIZE = "block_size"
static const string ARG_AUTO_COMPACTION = "auto_compaction"
static const string ARG_WRITE_BUFFER_SIZE = "write_buffer_size"
static const string ARG_FILE_SIZE = "file_size"
static const string ARG_CREATE_IF_MISSING = "create_if_missing"
static const char * DELIM = " ==> "
Protected Member Functions inherited from rocksdb::LDBCommand
bool ParseKeyValue (const string &line, string *key, string *value, bool is_key_hex, bool is_value_hex)
LDBCommand (const map< string, string > &options, const vector< string > &flags, bool is_read_only, const vector< string > &valid_cmd_line_options)
void OpenDB ()
void CloseDB ()
vector< string > BuildCmdLineOptions (vector< string > options)
bool ParseIntOption (const map< string, string > &options, const string &option, int &value, LDBCommandExecuteResult &exec_state)
bool ParseStringOption (const map< string, string > &options, const string &option, string *value)
Static Protected Member Functions inherited from rocksdb::LDBCommand
static string PrintKeyValue (const string &key, const string &value, bool is_key_hex, bool is_value_hex)
static string PrintKeyValue (const string &key, const string &value, bool is_hex)
static bool IsFlagPresent (const vector< string > &flags, const string &flag)
static string HelpRangeCmdArgs ()
Protected Attributes inherited from rocksdb::LDBCommand
LDBCommandExecuteResult exec_state_
string db_path_
DB * db_
StackableDB * sdb_
bool is_read_only_
bool is_key_hex_
bool is_value_hex_
bool is_db_ttl_
bool timestamp_
const map< string, string > option_map_
const vector< string > flags_
const vector< string > valid_cmd_line_options_
Options options_
Detailed Description
Definition at line 465 of file ldb_cmd.h.
Constructor & Destructor Documentation
rocksdb::ManifestDumpCommand::ManifestDumpCommand (const vector< string > & params, const map< string, string > & options, const vector< string > & flags)
Definition at line 473 of file ldb_cmd.cc.
References rocksdb::LDBCommand::ARG_HEX, ARG_PATH, and ARG_VERBOSE.
                                                                        :
     LDBCommand(options, flags, false,
                BuildCmdLineOptions({ARG_VERBOSE, ARG_PATH, ARG_HEX})),
Member Function Documentation
void rocksdb::ManifestDumpCommand::DoCommand () virtual
Implements rocksdb::LDBCommand.
Definition at line 491 of file ldb_cmd.cc.
References rocksdb::Options::comparator, rocksdb::LDBCommand::db_path_, dbname, rocksdb::VersionSet::DumpManifest(), rocksdb::LDBCommand::exec_state_, rocksdb::LDBCommandExecuteResult::FAILED(), rocksdb::LDBCommand::is_key_hex_, beast::asio::InputParser::match(), rocksdb::Status::ok(), path_, rocksdb::Status::ToString(), and verbose_.
{
   std::string manifestfile;
   if (!path_.empty()) {
     manifestfile = path_;
   } else {
     bool found = false;
     // We need to find the manifest file by searching the directory
     // containing the db for files of the form MANIFEST_[0-9]+
     DIR* d = opendir(db_path_.c_str());
     if (d == nullptr) {
       exec_state_ = LDBCommandExecuteResult::FAILED(
         db_path_ + " is not a directory");
       return;
     }
     struct dirent* entry;
     while ((entry = readdir(d)) != nullptr) {
       unsigned int match;
       unsigned long long num;
       if (sscanf(entry->d_name,
                  "MANIFEST-%ln%ln",
                  (unsigned long*)&num,
                  (unsigned long*)&match)
           && match == strlen(entry->d_name)) {
         if (!found) {
           manifestfile = db_path_ + "/" + std::string(entry->d_name);
           found = true;
         } else {
           exec_state_ = LDBCommandExecuteResult::FAILED(
             "Multiple MANIFEST files found; use --path to select one");
           return;
         }
       }
     }
     closedir(d);
   }
   if (verbose_) {
     printf("Processing Manifest file %s\n", manifestfile.c_str());
   }
   Options options;
   EnvOptions sopt;
   std::string file(manifestfile);
   std::string dbname("dummy");
   TableCache* tc = new TableCache(dbname, &options, sopt, 10);
   const InternalKeyComparator* cmp =
     new InternalKeyComparator(options.comparator);
   VersionSet* versions = new VersionSet(dbname, &options, sopt, tc, cmp);
   Status s = versions->DumpManifest(options, file, verbose_, is_key_hex_);
   if (!s.ok()) {
     printf("Error in processing file %s %s\n", manifestfile.c_str(),
            s.ToString().c_str());
   }
   if (verbose_) {
     printf("Processing Manifest file %s done\n", manifestfile.c_str());
   }
 }
void rocksdb::ManifestDumpCommand::Help (string & ret) static
Definition at line 465 of file ldb_cmd.cc.
References ARG_PATH, ARG_VERBOSE, and Name().
Referenced by rocksdb::LDBCommandRunner::PrintHelp().
{
   ret.append("  ");
   ret.append(ManifestDumpCommand::Name());
   ret.append(" [--" + ARG_VERBOSE + "]");
   ret.append(" [--" + ARG_PATH + "=<path_to_manifest_file>]");
   ret.append("\n");
 }
static string rocksdb::ManifestDumpCommand::Name () inline static
Definition at line 467 of file ldb_cmd.h.
Referenced by Help(), and rocksdb::LDBCommand::SelectCommand().
 { return "manifest_dump"; }
virtual bool rocksdb::ManifestDumpCommand::NoDBOpen () inline virtual
Reimplemented from rocksdb::LDBCommand.
Definition at line 475 of file ldb_cmd.h.
{
     return true;
   }
Member Data Documentation
const string rocksdb::ManifestDumpCommand::ARG_PATH = "path" static private
Definition at line 484 of file ldb_cmd.h.
Referenced by Help(), and ManifestDumpCommand().
const string rocksdb::ManifestDumpCommand::ARG_VERBOSE = "verbose" static private
Definition at line 483 of file ldb_cmd.h.
Referenced by Help(), and ManifestDumpCommand().
string rocksdb::ManifestDumpCommand::path_ private
Definition at line 481 of file ldb_cmd.h.
Referenced by DoCommand().
bool rocksdb::ManifestDumpCommand::verbose_ private
Definition at line 480 of file ldb_cmd.h.
Referenced by DoCommand().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/util/ldb_cmd.h
rippled/src/ripple/rocksdb/rocksdb/util/ldb_cmd.cc