rippled: beast::MemoryBlock Class Reference
beast::MemoryBlock Class Reference
#include <MemoryBlock.h>
Public Types
typedef char * iterator
typedef char const * const_iterator
Public Member Functions
MemoryBlock () noexcept
MemoryBlock (const size_t initialSize, bool initialiseToZero=false)
MemoryBlock (const MemoryBlock &other)
MemoryBlock (const void *dataToInitialiseFrom, size_t sizeInBytes)
~MemoryBlock () noexcept
MemoryBlock & operator= (const MemoryBlock &other)
iterator begin () noexcept
iterator end () noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
bool operator== (const MemoryBlock &other) const noexcept
bool operator!= (const MemoryBlock &other) const noexcept
bool matches (const void *data, size_t dataSize) const noexcept
void * getData () const noexcept
void const * getConstData () const noexcept
template<typename Type >
char & operator[] (const Type offset) const noexcept
size_t getSize () const noexcept
void setSize (const size_t newSize, bool initialiseNewSpaceToZero=false)
void ensureSize (const size_t minimumSize, bool initialiseNewSpaceToZero=false)
void fillWith (std::uint8_t valueToUse) noexcept
void append (const void *data, size_t numBytes)
void replaceWith (const void *data, size_t numBytes)
void insert (const void *dataToInsert, size_t numBytesToInsert, size_t insertPosition)
void removeSection (size_t startByte, size_t numBytesToRemove)
void copyFrom (const void *srcData, int destinationOffset, size_t numBytes) noexcept
void copyTo (void *destData, int sourceOffset, size_t numBytes) const noexcept
void swapWith (MemoryBlock &other) noexcept
String toString () const
void loadFromHexString (const String &sourceHexString)
void setBitRange (size_t bitRangeStart, size_t numBits, int binaryNumberToApply) noexcept
int getBitRange (size_t bitRangeStart, size_t numBitsToRead) const noexcept
String toBase64Encoding () const
bool fromBase64Encoding (const String &encodedString)
Private Attributes
HeapBlock< char > data
size_t size
Detailed Description
A class to hold a resizable block of raw data.
Definition at line 36 of file MemoryBlock.h.
Member Typedef Documentation
typedef char const* beast::MemoryBlock::const_iterator
Definition at line 77 of file MemoryBlock.h.
typedef char* beast::MemoryBlock::iterator
Definition at line 76 of file MemoryBlock.h.
Constructor & Destructor Documentation
beast::MemoryBlock::MemoryBlock () noexcept
Create an uninitialised block with 0 size.
Definition at line 27 of file MemoryBlock.cpp.
     : size (0)
 {
 }
beast::MemoryBlock::MemoryBlock (const size_t initialSize, bool initialiseToZero = false)
Creates a memory block with a given initial size.
Parameters
initialSize the size of block to create
initialiseToZero whether to clear the memory or just leave it uninitialised
Definition at line 32 of file MemoryBlock.cpp.
References beast::HeapBlock< ElementType, throwOnFailure >::allocate(), data, and size.
 {
     if (initialSize > 0)
     {
         size = initialSize;
         data.allocate (initialSize, initialiseToZero);
     }
     else
     {
         size = 0;
     }
 }
beast::MemoryBlock::MemoryBlock (const MemoryBlock & other)
Creates a copy of another memory block.
Definition at line 45 of file MemoryBlock.cpp.
References bassert, data, beast::HeapBlock< ElementType, throwOnFailure >::malloc(), and size.
     : size (other.size)
 {
     if (size > 0)
     {
         bassert (other.data != nullptr);
         data.malloc (size);
         memcpy (data, other.data, size);
     }
 }
beast::MemoryBlock::MemoryBlock (const void * dataToInitialiseFrom, size_t sizeInBytes)
Creates a memory block using a copy of a block of data.
Parameters
dataToInitialiseFrom some data to copy into this block
sizeInBytes how much space to use
Definition at line 56 of file MemoryBlock.cpp.
References bassert, data, beast::HeapBlock< ElementType, throwOnFailure >::malloc(), and size.
     : size (sizeInBytes)
 {
     bassert (((std::ptrdiff_t) sizeInBytes) >= 0);
     if (size > 0)
     {
         bassert (dataToInitialiseFrom != nullptr); // non-zero size, but a zero pointer passed-in?
         data.malloc (size);
         if (dataToInitialiseFrom != nullptr)
             memcpy (data, dataToInitialiseFrom, size);
     }
 }
beast::MemoryBlock::~MemoryBlock () noexcept
Destructor.
Definition at line 72 of file MemoryBlock.cpp.
 {
 }
Member Function Documentation
void beast::MemoryBlock::append (const void * data, size_t numBytes)
Adds another block of data to the end of this one. The data pointer must not be null. This block's size will be increased accordingly.
Definition at line 168 of file MemoryBlock.cpp.
References bassert, data, setSize(), and size.
 {
     if (numBytes > 0)
     {
         bassert (srcData != nullptr); // this must not be null!
         const size_t oldSize = size;
         setSize (size + numBytes);
         memcpy (data + oldSize, srcData, numBytes);
     }
 }
iterator beast::MemoryBlock::begin () inline noexcept
Definition at line 78 of file MemoryBlock.h.
References getData().
Referenced by end(), and ripple::Validators::SourceFileImp::fetch().
 { return static_cast <iterator> (getData ()); }
const_iterator beast::MemoryBlock::cbegin () const inline noexcept
Definition at line 80 of file MemoryBlock.h.
References getConstData().
Referenced by cend().
 { return static_cast <const_iterator> (getConstData ()); }
const_iterator beast::MemoryBlock::cend () const inline noexcept
Definition at line 81 of file MemoryBlock.h.
References beast::addBytesToPointer(), cbegin(), and size.
 { return addBytesToPointer (cbegin (), size); }
void beast::MemoryBlock::copyFrom (const void * srcData, int destinationOffset, size_t numBytes) noexcept
Copies data into this MemoryBlock from a memory address.
Parameters
srcData the memory location of the data to copy into this block
destinationOffset the offset in this block at which the data being copied should begin
numBytes how much to copy in (if this goes beyond the size of the memory block, it will be clipped so not to do anything nasty)
Definition at line 223 of file MemoryBlock.cpp.
 {
     const char* d = static_cast<const char*> (src);
     if (offset < 0)
     {
         d -= offset;
         num += (size_t) -offset;
         offset = 0;
     }
     if ((size_t) offset + num > size)
         num = size - (size_t) offset;
     if (num > 0)
         memcpy (data + offset, d, num);
 }
void beast::MemoryBlock::copyTo (void * destData, int sourceOffset, size_t numBytes) const noexcept
Copies data from this MemoryBlock to a memory address.
Parameters
destData the memory location to write to
sourceOffset the offset within this block from which the copied data will be read
numBytes how much to copy (if this extends beyond the limits of the memory block, zeros will be used for that portion of the data)
Definition at line 241 of file MemoryBlock.cpp.
References beast::zeromem().
 {
     char* d = static_cast<char*> (dst);
     if (offset < 0)
     {
         zeromem (d, (size_t) -offset);
         d -= offset;
         num -= (size_t) -offset;
         offset = 0;
     }
     if ((size_t) offset + num > size)
     {
         const size_t newNum = size - (size_t) offset;
         zeromem (d + newNum, num - newNum);
         num = newNum;
     }
     if (num > 0)
         memcpy (d, data + offset, num);
 }
iterator beast::MemoryBlock::end () inline noexcept
Definition at line 79 of file MemoryBlock.h.
References beast::addBytesToPointer(), begin(), and size.
Referenced by ripple::Validators::SourceFileImp::fetch().
 { return addBytesToPointer (begin (), size); }
void beast::MemoryBlock::ensureSize (const size_t minimumSize, bool initialiseNewSpaceToZero = false)
Increases the block's size only if it's smaller than a given size.
Parameters
minimumSize if the block is already bigger than this size, no action will be taken; otherwise it will be increased to this size
initialiseNewSpaceToZero if the block gets enlarged, this determines whether to clear the new section or just leave it uninitialised
See Also
setSize
Definition at line 150 of file MemoryBlock.cpp.
References setSize(), and size.
Referenced by loadFromHexString(), beast::MemoryOutputStream::preallocate(), ripple::NodeStore::EncodedBlob::prepare(), and beast::MemoryOutputStream::prepareToWrite().
 {
     if (size < minimumSize)
         setSize (minimumSize, initialiseToZero);
 }
void beast::MemoryBlock::fillWith (std::uint8_t valueToUse) noexcept
Fills the entire memory block with a repeated byte value.
This is handy for clearing a block of memory to zero.
Definition at line 163 of file MemoryBlock.cpp.
References value.
 {
     memset (data, (int) value, size);
 }
bool beast::MemoryBlock::fromBase64Encoding (const String & encodedString)
Takes a string of encoded characters and turns it into binary data.
The string passed in must have been created by to64BitEncoding(), and this block will be resized to recreate the original data block.
See Also
toBase64Encoding
Definition at line 375 of file MemoryBlock.cpp.
References beast::base64EncodingTable, beast::CharPointer_UTF8::getAndAdvance(), beast::String::getCharPointer(), beast::String::getIntValue(), beast::String::indexOfChar(), beast::String::length(), setBitRange(), setSize(), and beast::String::substring().
 {
     const int startPos = s.indexOfChar ('.') + 1;
     if (startPos <= 0)
         return false;
     const int numBytesNeeded = s.substring (0, startPos - 1).getIntValue();
     setSize ((size_t) numBytesNeeded, true);
     const int numChars = s.length() - startPos;
     String::CharPointerType srcChars (s.getCharPointer());
     srcChars += startPos;
     int pos = 0;
     for (int i = 0; i < numChars; ++i)
     {
         const char c = (char) srcChars.getAndAdvance();
         for (int j = 0; j < 64; ++j)
         {
             if (base64EncodingTable[j] == c)
             {
                 setBitRange ((size_t) pos, 6, j);
                 pos += 6;
                 break;
             }
         }
     }
     return true;
 }
int beast::MemoryBlock::getBitRange (size_t bitRangeStart, size_t numBitsToRead) const noexcept
Reads a number of bits from the memory block, treating it as one long binary sequence
Definition at line 270 of file MemoryBlock.cpp.
References beast::bmin().
Referenced by toBase64Encoding().
 {
     int res = 0;
     size_t byte = bitRangeStart >> 3;
     size_t offsetInByte = bitRangeStart & 7;
     size_t bitsSoFar = 0;
     while (numBits > 0 && (size_t) byte < size)
     {
         const size_t bitsThisTime = bmin (numBits, 8 - offsetInByte);
         const int mask = (0xff >> (8 - bitsThisTime)) << offsetInByte;
         res |= (((data[byte] & mask) >> offsetInByte) << bitsSoFar);
         bitsSoFar += bitsThisTime;
         numBits -= bitsThisTime;
         ++byte;
         offsetInByte = 0;
     }
     return res;
 }
void const* beast::MemoryBlock::getConstData () const inline noexcept
Returns a void pointer to data as unmodifiable.
Note that the pointer returned will probably become invalid when the block is resized.
Definition at line 116 of file MemoryBlock.h.
References data.
Referenced by cbegin().
     {
         return data;
     }
void* beast::MemoryBlock::getData () const inline noexcept
Returns a void pointer to the data.
Note that the pointer returned will probably become invalid when the block is resized.
Definition at line 106 of file MemoryBlock.h.
References data.
Referenced by beast::asio::HTTPClientType::Session::async_read_some(), ripple::HTTP::Peer::async_read_some(), begin(), beast::RegistryKeyWrapper::getBinaryValue(), ripple::NodeStore::EncodedBlob::getData(), beast::MemoryOutputStream::getData(), beast::RegistryKeyWrapper::getValue(), ripple::HTTP::Peer::handle_read(), beast::asio::HTTPClientType::Session::handle_read(), beast::operator<<(), ripple::NodeStore::EncodedBlob::prepare(), beast::MemoryOutputStream::prepareToWrite(), beast::InputStream::readNextLine(), and beast::InputStream::readString().
     {
         return data;
     }
size_t beast::MemoryBlock::getSize () const inline noexcept
Returns the block's current allocated size, in bytes.
Definition at line 130 of file MemoryBlock.h.
References size.
Referenced by beast::asio::HTTPClientType::Session::async_read_some(), ripple::HTTP::Peer::async_read_some(), beast::MemoryOutputStream::getData(), beast::MemoryOutputStream::MemoryOutputStream(), beast::operator<<(), beast::MemoryOutputStream::prepareToWrite(), beast::InputStream::readNextLine(), beast::InputStream::readString(), beast::File_test::run(), and beast::MemoryOutputStream::writeFromInputStream().
 { return size; }
void beast::MemoryBlock::insert (const void * dataToInsert, size_t numBytesToInsert, size_t insertPosition)
Inserts some data into the block. The dataToInsert pointer must not be null. This block's size will be increased accordingly. If the insert position lies outside the valid range of the block, it will be clipped to within the range before being used.
Definition at line 189 of file MemoryBlock.cpp.
References bassert, beast::bmin(), data, setSize(), and size.
 {
     if (numBytes > 0)
     {
         bassert (srcData != nullptr); // this must not be null!
         insertPosition = bmin (size, insertPosition);
         const size_t trailingDataSize = size - insertPosition;
         setSize (size + numBytes, false);
         if (trailingDataSize > 0)
             memmove (data + insertPosition + numBytes,
                      data + insertPosition,
                      trailingDataSize);
         memcpy (data + insertPosition, srcData, numBytes);
     }
 }
void beast::MemoryBlock::loadFromHexString (const String & sourceHexString)
Parses a string of hexadecimal numbers and writes this data into the memory block.
The block will be resized to the number of valid bytes read from the string. Non-hex characters in the string will be ignored.
See Also
String::toHexString()
Definition at line 318 of file MemoryBlock.cpp.
References data, ensureSize(), beast::CharPointer_UTF8::getAndAdvance(), beast::String::getCharPointer(), beast::String::length(), and setSize().
 {
     ensureSize ((size_t) hex.length() >> 1);
     char* dest = data;
     String::CharPointerType t (hex.getCharPointer());
     for (;;)
     {
         int byte = 0;
         for (int loop = 2; --loop >= 0;)
         {
             byte <<= 4;
             for (;;)
             {
                 const beast_wchar c = t.getAndAdvance();
                 if (c >= '0' && c <= '9') { byte |= c - '0'; break; }
                 if (c >= 'a' && c <= 'z') { byte |= c - ('a' - 10); break; }
                 if (c >= 'A' && c <= 'Z') { byte |= c - ('A' - 10); break; }
                 if (c == 0)
                 {
                     setSize (static_cast <size_t> (dest - data));
                     return;
                 }
             }
         }
         *dest++ = (char) byte;
     }
 }
bool beast::MemoryBlock::matches (const void * data, size_t dataSize) const noexcept
Returns true if the data in this MemoryBlock matches the raw bytes passed-in.
Definition at line 114 of file MemoryBlock.cpp.
 {
     return size == dataSize
             && memcmp (data, dataToCompare, size) == 0;
 }
bool beast::MemoryBlock::operator!= (const MemoryBlock & other) const noexcept
Compares two memory blocks.
Returns
true if the two blocks are different sizes or have different contents.
Definition at line 109 of file MemoryBlock.cpp.
References beast::operator==().
 {
     return ! operator== (other);
 }
MemoryBlock & beast::MemoryBlock::operator= (const MemoryBlock & other)
Copies another memory block onto this one.
This block will be resized and copied to exactly match the other one.
Definition at line 76 of file MemoryBlock.cpp.
References data, setSize(), and size.
 {
     if (this != &other)
     {
         setSize (other.size, false);
         memcpy (data, other.data, size);
     }
     return *this;
 }
bool beast::MemoryBlock::operator== (const MemoryBlock & other) const noexcept
Compares two memory blocks.
Returns
true only if the two blocks are the same size and have identical contents.
Definition at line 104 of file MemoryBlock.cpp.
 {
     return matches (other.data, other.size);
 }
template<typename Type > char& beast::MemoryBlock::operator[] (const Type offset) const inline noexcept
Returns a byte from the memory block.
This returns a reference, so you can also use it to set a byte.
Definition at line 126 of file MemoryBlock.h.
References data.
 { return data [offset]; }
void beast::MemoryBlock::removeSection (size_t startByte, size_t numBytesToRemove)
Chops out a section of the block.
This will remove a section of the memory block and close the gap around it, shifting any subsequent data downwards and reducing the size of the block.
If the range specified goes beyond the size of the block, it will be clipped.
Definition at line 207 of file MemoryBlock.cpp.
References data, setSize(), and size.
 {
     if (startByte + numBytesToRemove >= size)
     {
         setSize (startByte);
     }
     else if (numBytesToRemove > 0)
     {
         memmove (data + startByte,
                  data + startByte + numBytesToRemove,
                  size - (startByte + numBytesToRemove));
         setSize (size - numBytesToRemove);
     }
 }
void beast::MemoryBlock::replaceWith (const void * data, size_t numBytes)
Resizes this block to the given size and fills its contents from the supplied buffer. The data pointer must not be null.
Definition at line 179 of file MemoryBlock.cpp.
References bassert, data, and setSize().
 {
     if (numBytes > 0)
     {
         bassert (srcData != nullptr); // this must not be null!
         setSize (numBytes);
         memcpy (data, srcData, numBytes);
     }
 }
void beast::MemoryBlock::setBitRange (size_t bitRangeStart, size_t numBits, int binaryNumberToApply) noexcept
Sets a number of bits in the memory block, treating it as a long binary sequence.
Definition at line 294 of file MemoryBlock.cpp.
References beast::bmin().
Referenced by fromBase64Encoding().
 {
     size_t byte = bitRangeStart >> 3;
     size_t offsetInByte = bitRangeStart & 7;
     std::uint32_t mask = ~((((std::uint32_t) 0xffffffff) << (32 - numBits)) >> (32 - numBits));
     while (numBits > 0 && (size_t) byte < size)
     {
         const size_t bitsThisTime = bmin (numBits, 8 - offsetInByte);
         const std::uint32_t tempMask = (mask << offsetInByte) | ~((((std::uint32_t) 0xffffffff) >> offsetInByte) << offsetInByte);
         const std::uint32_t tempBits = (std::uint32_t) bitsToSet << offsetInByte;
         data[byte] = (char) (((std::uint32_t) data[byte] & tempMask) | tempBits);
         ++byte;
         numBits -= bitsThisTime;
         bitsToSet >>= bitsThisTime;
         mask >>= bitsThisTime;
         offsetInByte = 0;
     }
 }
void beast::MemoryBlock::setSize (const size_t newSize, bool initialiseNewSpaceToZero = false)
Resizes the memory block.
This will try to keep as much of the block's current content as it can, and can optionally be made to clear any new space that gets allocated at the end of the block.
Parameters
newSize the new desired size for the block
initialiseNewSpaceToZero if the block gets enlarged, this determines whether to clear the new section or just leave it uninitialised
See Also
ensureSize
Definition at line 122 of file MemoryBlock.cpp.
References beast::HeapBlock< ElementType, throwOnFailure >::allocate(), data, beast::HeapBlock< ElementType, throwOnFailure >::free_up(), beast::HeapBlock< ElementType, throwOnFailure >::reallocate(), size, and beast::zeromem().
Referenced by append(), ensureSize(), fromBase64Encoding(), beast::RegistryKeyWrapper::getBinaryValue(), insert(), loadFromHexString(), beast::MemoryOutputStream::MemoryOutputStream(), operator=(), beast::InputStream::readNextLine(), beast::InputStream::readString(), removeSection(), replaceWith(), and beast::MemoryOutputStream::trimExternalBlockSize().
 {
     if (size != newSize)
     {
         if (newSize <= 0)
         {
             data.free_up();
             size = 0;
         }
         else
         {
             if (data != nullptr)
             {
                 data.reallocate (newSize);
                 if (initialiseToZero && (newSize > size))
                     zeromem (data + size, newSize - size);
             }
             else
             {
                 data.allocate (newSize, initialiseToZero);
             }
             size = newSize;
         }
     }
 }
void beast::MemoryBlock::swapWith (MemoryBlock & other) noexcept
Exchanges the contents of this and another memory block. No actual copying is required for this, so it's very fast.
Definition at line 156 of file MemoryBlock.cpp.
References beast::asio::swap().
 {
     std::swap (size, other.size);
     data.swapWith (other.data);
 }
String beast::MemoryBlock::toBase64Encoding () const
Returns a string of characters that represent the binary contents of this block.
Uses a 64-bit encoding system to allow binary data to be turned into a string of simple non-extended characters, e.g. for storage in XML.
See Also
fromBase64Encoding
Definition at line 356 of file MemoryBlock.cpp.
References beast::base64EncodingTable, getBitRange(), beast::String::getCharPointer(), beast::String::length(), beast::String::preallocateBytes(), size, and beast::CharPointer_UTF8::write().
 {
     const size_t numChars = ((size << 3) + 5) / 6;
     String destString ((unsigned int) size); // store the length, followed by a '.', and then the data.
     const int initialLen = destString.length();
     destString.preallocateBytes (sizeof (String::CharPointerType::CharType) * (size_t) initialLen + 2 + numChars);
     String::CharPointerType d (destString.getCharPointer());
     d += initialLen;
     d.write ('.');
     for (size_t i = 0; i < numChars; ++i)
         d.write ((beast_wchar) (std::uint8_t) base64EncodingTable [getBitRange (i * 6, 6)]);
     d.writeNull();
     return destString;
 }
String beast::MemoryBlock::toString () const
Attempts to parse the contents of the block as a zero-terminated UTF8 string.
Definition at line 264 of file MemoryBlock.cpp.
References data, and size.
 {
     return String (CharPointer_UTF8 (data), size);
 }
Member Data Documentation
HeapBlock<char> beast::MemoryBlock::data private
Definition at line 267 of file MemoryBlock.h.
Referenced by append(), getConstData(), getData(), insert(), loadFromHexString(), MemoryBlock(), operator=(), operator[](), removeSection(), replaceWith(), setSize(), and toString().
size_t beast::MemoryBlock::size private
Definition at line 268 of file MemoryBlock.h.
Referenced by append(), cend(), end(), ensureSize(), getSize(), insert(), MemoryBlock(), operator=(), removeSection(), setSize(), toBase64Encoding(), and toString().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_core/memory/MemoryBlock.h
rippled/src/beast/modules/beast_core/memory/MemoryBlock.cpp