rippled: rocksdb::WALDumperCommand Class Reference
rocksdb::WALDumperCommand Class Reference
#include <ldb_cmd.h>
Public Member Functions
WALDumperCommand (const vector< string > &params, const map< string, string > &options, const vector< string > &flags)
virtual bool NoDBOpen ()
virtual void DoCommand ()
Public Member Functions inherited from rocksdb::LDBCommand
bool ValidateCmdLineOptions ()
virtual Options PrepareOptionsForOpenDB ()
virtual void SetOptions (Options options)
virtual ~LDBCommand ()
void Run ()
LDBCommandExecuteResult GetExecuteState ()
void ClearPreviousRunState ()
Static Public Member Functions
static string Name ()
static void Help (string &ret)
Static Public Member Functions inherited from rocksdb::LDBCommand
static LDBCommand * InitFromCmdLineArgs (const vector< string > &args, const Options &options=Options())
static LDBCommand * InitFromCmdLineArgs (int argc, char **argv, const Options &options=Options())
static string HexToString (const string &str)
static string StringToHex (const string &str)
Private Attributes
bool print_header_
string wal_file_
bool print_values_
Static Private Attributes
static const string ARG_WAL_FILE = "walfile"
static const string ARG_PRINT_HEADER = "header"
static const string ARG_PRINT_VALUE = "print_value"
Additional Inherited Members
Static Public Attributes inherited from rocksdb::LDBCommand
static const string ARG_DB = "db"
static const string ARG_HEX = "hex"
static const string ARG_KEY_HEX = "key_hex"
static const string ARG_VALUE_HEX = "value_hex"
static const string ARG_TTL = "ttl"
static const string ARG_TTL_START = "start_time"
static const string ARG_TTL_END = "end_time"
static const string ARG_TIMESTAMP = "timestamp"
static const string ARG_FROM = "from"
static const string ARG_TO = "to"
static const string ARG_MAX_KEYS = "max_keys"
static const string ARG_BLOOM_BITS = "bloom_bits"
static const string ARG_COMPRESSION_TYPE = "compression_type"
static const string ARG_BLOCK_SIZE = "block_size"
static const string ARG_AUTO_COMPACTION = "auto_compaction"
static const string ARG_WRITE_BUFFER_SIZE = "write_buffer_size"
static const string ARG_FILE_SIZE = "file_size"
static const string ARG_CREATE_IF_MISSING = "create_if_missing"
static const char * DELIM = " ==> "
Protected Member Functions inherited from rocksdb::LDBCommand
bool ParseKeyValue (const string &line, string *key, string *value, bool is_key_hex, bool is_value_hex)
LDBCommand (const map< string, string > &options, const vector< string > &flags, bool is_read_only, const vector< string > &valid_cmd_line_options)
void OpenDB ()
void CloseDB ()
vector< string > BuildCmdLineOptions (vector< string > options)
bool ParseIntOption (const map< string, string > &options, const string &option, int &value, LDBCommandExecuteResult &exec_state)
bool ParseStringOption (const map< string, string > &options, const string &option, string *value)
Static Protected Member Functions inherited from rocksdb::LDBCommand
static string PrintKeyValue (const string &key, const string &value, bool is_key_hex, bool is_value_hex)
static string PrintKeyValue (const string &key, const string &value, bool is_hex)
static bool IsFlagPresent (const vector< string > &flags, const string &flag)
static string HelpRangeCmdArgs ()
Protected Attributes inherited from rocksdb::LDBCommand
LDBCommandExecuteResult exec_state_
string db_path_
DB * db_
StackableDB * sdb_
bool is_read_only_
bool is_key_hex_
bool is_value_hex_
bool is_db_ttl_
bool timestamp_
const map< string, string > option_map_
const vector< string > flags_
const vector< string > valid_cmd_line_options_
Options options_
Detailed Description
Definition at line 539 of file ldb_cmd.h.
Constructor & Destructor Documentation
rocksdb::WALDumperCommand::WALDumperCommand (const vector< string > & params, const map< string, string > & options, const vector< string > & flags)
Definition at line 1254 of file ldb_cmd.cc.
References ARG_PRINT_HEADER, ARG_PRINT_VALUE, and ARG_WAL_FILE.
                                                                        :
     LDBCommand(options, flags, true,
                BuildCmdLineOptions(
                 {ARG_WAL_FILE, ARG_PRINT_HEADER, ARG_PRINT_VALUE})),
Member Function Documentation
void rocksdb::WALDumperCommand::DoCommand () virtual
Implements rocksdb::LDBCommand.
Definition at line 1286 of file ldb_cmd.cc.
References rocksdb::WriteBatchInternal::ByteSize(), rocksdb::Status::Corruption(), rocksdb::WriteBatchInternal::Count(), rocksdb::Env::Default(), rocksdb::InMemoryHandler::DeleteList(), env_, rocksdb::LDBCommand::exec_state_, rocksdb::LDBCommandExecuteResult::FAILED(), rocksdb::WriteBatch::Iterate(), rocksdb::log::Reader::LastRecordOffset(), rocksdb::Env::NewSequentialFile(), rocksdb::Status::ok(), print_header_, print_values_, rocksdb::InMemoryHandler::PutMap(), rocksdb::log::Reader::ReadRecord(), rocksdb::WriteBatchInternal::Sequence(), rocksdb::WriteBatchInternal::SetContents(), rocksdb::Slice::size(), rocksdb::LDBCommand::StringToHex(), rocksdb::Status::ToString(), and wal_file_.
{
   struct StdErrReporter : public log::Reader::Reporter {
     virtual void Corruption(size_t bytes, const Status& s) {
       cerr<<"Corruption detected in log file "<<s.ToString()<<"\n";
     }
   };
   unique_ptr<SequentialFile> file;
   Env* env_ = Env::Default();
   EnvOptions soptions;
   Status status = env_->NewSequentialFile(wal_file_, &file, soptions);
   if (!status.ok()) {
     exec_state_ = LDBCommandExecuteResult::FAILED("Failed to open WAL file " +
       status.ToString());
   } else {
     StdErrReporter reporter;
     log::Reader reader(move(file), &reporter, true, 0);
     string scratch;
     WriteBatch batch;
     Slice record;
     stringstream row;
     if (print_header_) {
       cout<<"Sequence,Count,ByteSize,Physical Offset,Key(s)";
       if (print_values_) {
         cout << " : value ";
       }
       cout << "\n";
     }
     while(reader.ReadRecord(&record, &scratch)) {
       row.str("");
       if (record.size() < 12) {
         reporter.Corruption(
             record.size(), Status::Corruption("log record too small"));
       } else {
         WriteBatchInternal::SetContents(&batch, record);
         row<<WriteBatchInternal::Sequence(&batch)<<",";
         row<<WriteBatchInternal::Count(&batch)<<",";
         row<<WriteBatchInternal::ByteSize(&batch)<<",";
         row<<reader.LastRecordOffset()<<",";
         InMemoryHandler handler;
         batch.Iterate(&handler);
         row << "PUT : ";
         if (print_values_) {
           for (auto& kv : handler.PutMap()) {
             string k = StringToHex(kv.first);
             string v = StringToHex(kv.second);
             row << k << " : ";
             row << v << " ";
           }
         }
         else {
           for(auto& kv : handler.PutMap()) {
             row << StringToHex(kv.first) << " ";
           }
         }
         row<<",DELETE : ";
         for(string& s : handler.DeleteList()) {
           row << StringToHex(s) << " ";
         }
         row<<"\n";
       }
       cout<<row.str();
     }
   }
 }
void rocksdb::WALDumperCommand::Help (string & ret) static
Definition at line 1277 of file ldb_cmd.cc.
References ARG_PRINT_HEADER, ARG_PRINT_VALUE, ARG_WAL_FILE, and Name().
Referenced by rocksdb::LDBCommandRunner::PrintHelp().
{
   ret.append("  ");
   ret.append(WALDumperCommand::Name());
   ret.append(" --" + ARG_WAL_FILE + "=<write_ahead_log_file_path>");
   ret.append(" [--" + ARG_PRINT_HEADER + "] ");
   ret.append(" [--" + ARG_PRINT_VALUE + "] ");
   ret.append("\n");
 }
static string rocksdb::WALDumperCommand::Name () inline static
Definition at line 541 of file ldb_cmd.h.
Referenced by Help(), and rocksdb::LDBCommand::SelectCommand().
 { return "dump_wal"; }
virtual bool rocksdb::WALDumperCommand::NoDBOpen () inline virtual
Reimplemented from rocksdb::LDBCommand.
Definition at line 546 of file ldb_cmd.h.
{
     return true;
   }
Member Data Documentation
const string rocksdb::WALDumperCommand::ARG_PRINT_HEADER = "header" static private
Definition at line 559 of file ldb_cmd.h.
Referenced by Help(), and WALDumperCommand().
const string rocksdb::WALDumperCommand::ARG_PRINT_VALUE = "print_value" static private
Definition at line 560 of file ldb_cmd.h.
Referenced by Help(), and WALDumperCommand().
const string rocksdb::WALDumperCommand::ARG_WAL_FILE = "walfile" static private
Definition at line 558 of file ldb_cmd.h.
Referenced by Help(), and WALDumperCommand().
bool rocksdb::WALDumperCommand::print_header_ private
Definition at line 554 of file ldb_cmd.h.
Referenced by DoCommand().
bool rocksdb::WALDumperCommand::print_values_ private
Definition at line 556 of file ldb_cmd.h.
Referenced by DoCommand().
string rocksdb::WALDumperCommand::wal_file_ private
Definition at line 555 of file ldb_cmd.h.
Referenced by DoCommand().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/util/ldb_cmd.h
rippled/src/ripple/rocksdb/rocksdb/util/ldb_cmd.cc