rippled: ripple::TestOverlay::Network2_test Class Reference
ripple::TestOverlay::Network2_test Class Reference
Classes
class Message
class Peer
struct PeerLogic
Public Member Functions
template<typename PeerContainer >
void make_peers (PeerContainer &s, typename PeerContainer::size_type n, int *count)
template<typename RandomType , typename PeerContainer >
void make_connections (PeerContainer &s, typename PeerContainer::size_type outDegree, RandomType r=RandomType())
void test1 ()
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 435 of file TestOverlay.cpp.
Member Function Documentation
template<typename RandomType , typename PeerContainer > void ripple::TestOverlay::Network2_test::make_connections (PeerContainer & s, typename PeerContainer::size_type outDegree, RandomType r = RandomType()) inline
Definition at line 485 of file TestOverlay.cpp.
References ripple::TestOverlay::is_connected().
Referenced by test1().
     {
         // Turn the PeerContainer into a PeerSequence
         typedef typename PeerContainer::pointer pointer;
         typedef std::vector <pointer> PeerSequence;
         PeerSequence v;
         v.reserve (s.size());
         for (typename PeerContainer::iterator iter (s.begin());
             iter != s.end(); ++iter)
             v.push_back (&(*iter));
         // Make random connections
         typedef typename PeerSequence::size_type size_type;
         size_type const n (v.size());
         for (typename PeerSequence::iterator iter (v.begin());
             iter != v.end(); ++iter)
         {
             for (size_type i (0); i < outDegree; ++i)
             {
                 for(;;)
                 {
                     size_type const j (r.nextInt (n));
                     // prohibit self connection
                     if (*iter == v[j])
                         continue;
                     // prohibit duplicate connection
                     if (is_connected (**iter, *v[j]))
                         continue;
                     (*iter)->connect (*v [j]);
                     break;
                 }
             }
         }
     }
template<typename PeerContainer > void ripple::TestOverlay::Network2_test::make_peers (PeerContainer & s, typename PeerContainer::size_type n, int * count) inline
Definition at line 476 of file TestOverlay.cpp.
Referenced by test1().
     {
         while (n--)
             s.emplace_back(count);
     }
void ripple::TestOverlay::Network2_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 542 of file TestOverlay.cpp.
References test1().
     {
         test1 ();
     }
void ripple::TestOverlay::Network2_test::test1 () inline
Definition at line 526 of file TestOverlay.cpp.
References ripple::TestOverlay::iterate(), beast::unit_test::suite::log, make_connections(), make_peers(), and beast::unit_test::suite::pass().
Referenced by run().
     {
         int count (0);
         std::vector <Peer> peers;
         make_peers (peers, 10000, &count);
         make_connections (peers, 3, beast::Random());
         peers[0].send (Message ());
         for (int i = 0; i < 10; ++i)
         {
             iterate (peers);
             log <<
                 "count = " << count;
         }
         pass();
     }
The documentation for this class was generated from the following file:
rippled/src/ripple/testoverlay/impl/TestOverlay.cpp