rippled: beast::unit_test Namespace Reference
beast::unit_test Namespace Reference
Namespaces
detail
Classes
class amount
class selector
class recorder
class reporter
class case_results
class suite_results
class results
class runner
class suite
class suite_info
class suite_list
Functions
suite_list const & global_suites ()
selector match_auto (std::string const &name)
selector match_all ()
selector match_suite (std::string const &name)
selector match_library (std::string const &name)
bool operator< (suite_info const &lhs, suite_info const &rhs)
template<class Suite >
suite_info make_suite_info (char const *name, char const *module, char const *library, bool manual)
void print (results const &r, abstract_ostream &stream)
void print (results const &r, std::ostream &stream=std::cout)
Function Documentation
suite_list const& beast::unit_test::global_suites () inline
Holds suites registered during static initialization.
Definition at line 56 of file global_suites.h.
References beast::unit_test::detail::global_suites().
Referenced by main().
 {
     return detail::global_suites();
 }
template<class Suite > suite_info beast::unit_test::make_suite_info (char const * name, char const * module, char const * library, bool manual)
Convenience for producing suite_info for a given test type.
Definition at line 111 of file suite_info.h.
References test.
 {
     return suite_info (name, module, library, manual,
         [](runner& r)
         {
             Suite test;
             return test (r);
         });
 }
selector beast::unit_test::match_all () inline
Return a predicate that matches all suites not marked manual.
Definition at line 149 of file match.h.
References beast::unit_test::selector::all.
 {
     return selector (selector::all);
 }
selector beast::unit_test::match_auto (std::string const & name) inline
Returns a predicate that implements a smart matching rule. The predicate checks the suite, module, and library fields of the suite_info in that order. When it finds a match, it changes modes depending on what was found:
If a suite is matched first, then only the suite is selected. The
suite may be marked manual.
If a module is matched first, then only suites from that module
and library not marked manual are selected from then on.
If a library is matched first, then only suites from that library
not marked manual are selected from then on.
Definition at line 141 of file match.h.
References beast::unit_test::selector::automatch.
Referenced by ripple::runUnitTests().
 {
     return selector (selector::automatch, name);
 }
selector beast::unit_test::match_library (std::string const & name) inline
Returns a predicate that matches all suites in a library.
Definition at line 165 of file match.h.
References beast::unit_test::selector::library.
 {
     return selector (selector::library, name);
 }
selector beast::unit_test::match_suite (std::string const & name) inline
Returns a predicate that matches a specific suite.
Definition at line 157 of file match.h.
References beast::unit_test::selector::suite.
 {
     return selector (selector::suite, name);
 }
bool beast::unit_test::operator< (suite_info const & lhs, suite_info const & rhs) inline
Definition at line 104 of file suite_info.h.
References beast::unit_test::suite_info::full_name().
 {
     return lhs.full_name() < rhs.full_name();
 }
void beast::unit_test::print (results const & r, abstract_ostream & stream) inline
Write test results to the specified output stream.
Definition at line 39 of file print.h.
Referenced by beast.util.CleanCPPFiles::clean_line_endings(), ripple::LoadManagerImp::logDeadlock(), db_crashtest::main(), print(), beast.env.Print::print_build_config(), beast.env.Print::print_build_vars(), beast.env.Print::print_cmd_line(), print_error(), beast.env.ReadEnvFile::read_env_file(), beast.util.String::remove_quotes(), beast.util.String::single_line(), beast.util.CleanCPPFiles::walk_and_process(), and beast.util.Terminal::warn().
 {
     for (auto const& s : r)
     {
         for (auto const& c : s)
         {
             stream <<
                 s.name() <<
                 (c.name().empty() ? "" : ("." + c.name()));
             std::size_t i (1);
             for (auto const& t : c.tests)
             {
                 if (! t.pass)
                     stream <<
                         "#" << i <<
                         " failed: " << t.reason;
                 ++i;
             }
         }
     }
     stream <<
         amount (r.size(), "suite") << ", " <<
         amount (r.cases(), "case") << ", " <<
         amount (r.total(), "test") << " total, " <<
         amount (r.failed(), "failure")
         ;
 }
void beast::unit_test::print (results const & r, std::ostream & stream = std::cout) inline
Definition at line 71 of file print.h.
References beast::make_std_ostream(), and print().
 {
     auto s (make_std_ostream (stream));
     print (r, s);
 }