rippled: rocksdb::Block Class Reference
rocksdb::Block Class Reference
#include <block.h>
Classes
class Iter
Public Member Functions
Block (const BlockContents &contents)
~Block ()
size_t size () const
bool isCachable () const
CompressionType compressionType () const
Iterator * NewIterator (const Comparator *comparator)
const char * data ()
Private Member Functions
uint32_t NumRestarts () const
Block (const Block &)
void operator= (const Block &)
Private Attributes
const char * data_
size_t size_
uint32_t restart_offset_
bool owned_
bool cachable_
CompressionType compression_type_
Detailed Description
Definition at line 21 of file block.h.
Constructor & Destructor Documentation
rocksdb::Block::Block (const BlockContents & contents) explicit
Definition at line 28 of file block.cc.
References NumRestarts(), restart_offset_, and size_.
     : data_(contents.data.data()),
       size_(contents.data.size()),
       owned_(contents.heap_allocated),
       cachable_(contents.cachable),
       compression_type_(contents.compression_type) {
   if (size_ < sizeof(uint32_t)) {
     size_ = 0;  // Error marker
   } else {
     restart_offset_ = size_ - (1 + NumRestarts()) * sizeof(uint32_t);
     if (restart_offset_ > size_ - sizeof(uint32_t)) {
       // The size is too small for NumRestarts() and therefore
       // restart_offset_ wrapped around.
       size_ = 0;
     }
   }
 }
rocksdb::Block::~Block ()
Definition at line 46 of file block.cc.
References data_, and owned_.
               {
   if (owned_) {
     delete[] data_;
   }
 }
rocksdb::Block::Block (const Block &) private
Member Function Documentation
CompressionType rocksdb::Block::compressionType () const inline
Definition at line 30 of file block.h.
References compression_type_.
Referenced by rocksdb::BlockBasedTable::BlockReader(), and rocksdb::BlockBasedTable::Open().
 { return compression_type_; }
const char* rocksdb::Block::data () inline
Definition at line 32 of file block.h.
References data_.
Referenced by rocksdb::BlockBasedTable::BlockReader().
 { return data_; }
bool rocksdb::Block::isCachable () const inline
Definition at line 29 of file block.h.
References cachable_.
Referenced by rocksdb::BlockBasedTable::BlockReader().
 { return cachable_; }
Iterator * rocksdb::Block::NewIterator (const Comparator * comparator)
Definition at line 262 of file block.cc.
References rocksdb::Status::Corruption(), data_, rocksdb::NewEmptyIterator(), rocksdb::NewErrorIterator(), NumRestarts(), restart_offset_, and size_.
Referenced by rocksdb::BlockBasedTable::BlockReader(), rocksdb::BlockConstructor::NewIterator(), rocksdb::BlockBasedTable::ReadMetaBlock(), rocksdb::BlockBasedTable::ReadProperties(), and rocksdb::TEST().
{
   if (size_ < 2*sizeof(uint32_t)) {
     return NewErrorIterator(Status::Corruption("bad block contents"));
   }
   const uint32_t num_restarts = NumRestarts();
   if (num_restarts == 0) {
     return NewEmptyIterator();
   } else {
     return new Iter(cmp, data_, restart_offset_, num_restarts);
   }
 }
uint32_t rocksdb::Block::NumRestarts () const inline private
Definition at line 23 of file block.cc.
References data_, rocksdb::DecodeFixed32(), and size_.
Referenced by Block(), and NewIterator().
{
   assert(size_ >= 2*sizeof(uint32_t));
   return DecodeFixed32(data_ + size_ - sizeof(uint32_t));
 }
void rocksdb::Block::operator= (const Block &) private
size_t rocksdb::Block::size () const inline
Definition at line 28 of file block.h.
References size_.
Referenced by rocksdb::BlockBasedTable::BlockReader(), and rocksdb::BlockBasedTableBuilder::InsertBlockInCache().
 { return size_; }
Member Data Documentation
bool rocksdb::Block::cachable_ private
Definition at line 41 of file block.h.
Referenced by isCachable().
CompressionType rocksdb::Block::compression_type_ private
Definition at line 42 of file block.h.
Referenced by compressionType().
const char* rocksdb::Block::data_ private
Definition at line 37 of file block.h.
Referenced by data(), NewIterator(), NumRestarts(), and ~Block().
bool rocksdb::Block::owned_ private
Definition at line 40 of file block.h.
Referenced by ~Block().
uint32_t rocksdb::Block::restart_offset_ private
Definition at line 39 of file block.h.
Referenced by Block(), and NewIterator().
size_t rocksdb::Block::size_ private
Definition at line 38 of file block.h.
Referenced by Block(), NewIterator(), NumRestarts(), and size().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/table/block.h
rippled/src/ripple/rocksdb/rocksdb/table/block.cc