rippled: rocksdb::BlockBuilder Class Reference
rocksdb::BlockBuilder Class Reference
#include <block_builder.h>
Public Member Functions
BlockBuilder (int block_builder, const Comparator *comparator)
BlockBuilder (const Options &options)
void Reset ()
void Add (const Slice &key, const Slice &value)
Slice Finish ()
size_t CurrentSizeEstimate () const
size_t EstimateSizeAfterKV (const Slice &key, const Slice &value) const
bool empty () const
Private Member Functions
BlockBuilder (const BlockBuilder &)
void operator= (const BlockBuilder &)
Private Attributes
const int block_restart_interval_
const Comparator * comparator_
std::string buffer_
std::vector< uint32_t > restarts_
int counter_
bool finished_
std::string last_key_
Detailed Description
Definition at line 21 of file block_builder.h.
Constructor & Destructor Documentation
rocksdb::BlockBuilder::BlockBuilder (int block_builder, const Comparator * comparator)
Definition at line 43 of file block_builder.cc.
References block_restart_interval_, and restarts_.
     : block_restart_interval_(block_restart_interval),
       comparator_(comparator),
       restarts_(),
       counter_(0),
       finished_(false) {
   assert(block_restart_interval_ >= 1);
   restarts_.push_back(0);       // First restart point is at offset 0
 }
rocksdb::BlockBuilder::BlockBuilder (const Options & options) explicit
Definition at line 54 of file block_builder.cc.
     : BlockBuilder(options.block_restart_interval, options.comparator) {
 }
rocksdb::BlockBuilder::BlockBuilder (const BlockBuilder &) private
Member Function Documentation
void rocksdb::BlockBuilder::Add (const Slice & key, const Slice & value)
Definition at line 98 of file block_builder.cc.
References block_restart_interval_, buffer_, comparator_, rocksdb::Comparator::Compare(), counter_, rocksdb::Slice::data(), finished_, last_key_, ripple::min(), rocksdb::PutVarint32(), restarts_, shared, and rocksdb::Slice::size().
Referenced by rocksdb::BlockBasedTableBuilder::Add(), rocksdb::BlockBasedTableBuilder::Finish(), rocksdb::BlockConstructor::FinishImpl(), and rocksdb::TEST().
{
   Slice last_key_piece(last_key_);
   assert(!finished_);
   assert(counter_ <= block_restart_interval_);
   assert(buffer_.empty() // No values yet?
          || comparator_->Compare(key, last_key_piece) > 0);
   size_t shared = 0;
   if (counter_ < block_restart_interval_) {
     // See how much sharing to do with previous string
     const size_t min_length = std::min(last_key_piece.size(), key.size());
     while ((shared < min_length) && (last_key_piece[shared] == key[shared])) {
       shared++;
     }
   } else {
     // Restart compression
     restarts_.push_back(buffer_.size());
     counter_ = 0;
   }
   const size_t non_shared = key.size() - shared;
   // Add "<shared><non_shared><value_size>" to buffer_
   PutVarint32(&buffer_, shared);
   PutVarint32(&buffer_, non_shared);
   PutVarint32(&buffer_, value.size());
   // Add string delta to buffer_ followed by value
   buffer_.append(key.data() + shared, non_shared);
   buffer_.append(value.data(), value.size());
   // Update state
   last_key_.resize(shared);
   last_key_.append(key.data() + shared, non_shared);
   assert(Slice(last_key_) == key);
   counter_++;
 }
size_t rocksdb::BlockBuilder::CurrentSizeEstimate () const
Definition at line 67 of file block_builder.cc.
References buffer_, and restarts_.
Referenced by rocksdb::FlushBlockBySizePolicy::BlockAlmostFull(), EstimateSizeAfterKV(), rocksdb::BlockBasedTableBuilder::Finish(), and rocksdb::FlushBlockBySizePolicy::Update().
{
   return (buffer_.size() +                        // Raw data buffer
           restarts_.size() * sizeof(uint32_t) +   // Restart array
           sizeof(uint32_t));                      // Restart array length
 }
bool rocksdb::BlockBuilder::empty () const inline
Definition at line 46 of file block_builder.h.
References buffer_.
Referenced by rocksdb::BlockBasedTableBuilder::Add(), rocksdb::BlockBasedTableBuilder::Finish(), rocksdb::BlockBasedTableBuilder::Flush(), and rocksdb::FlushBlockBySizePolicy::Update().
                      {
     return buffer_.empty();
   }
size_t rocksdb::BlockBuilder::EstimateSizeAfterKV (const Slice & key, const Slice & value) const
Definition at line 73 of file block_builder.cc.
References block_restart_interval_, counter_, CurrentSizeEstimate(), rocksdb::Slice::size(), and rocksdb::VarintLength().
Referenced by rocksdb::FlushBlockBySizePolicy::BlockAlmostFull().
         {
   size_t estimate = CurrentSizeEstimate();
   estimate += key.size() + value.size();
   if (counter_ >= block_restart_interval_) {
     estimate += sizeof(uint32_t); // a new restart entry.
   }
   estimate += sizeof(int32_t); // varint for shared prefix length.
   estimate += VarintLength(key.size()); // varint for key length.
   estimate += VarintLength(value.size()); // varint for value length.
   return estimate;
 }
Slice rocksdb::BlockBuilder::Finish ()
Definition at line 88 of file block_builder.cc.
References buffer_, finished_, rocksdb::PutFixed32(), and restarts_.
Referenced by rocksdb::BlockConstructor::FinishImpl(), rocksdb::TEST(), and rocksdb::BlockBasedTableBuilder::WriteBlock().
{
   // Append restart array
   for (size_t i = 0; i < restarts_.size(); i++) {
     PutFixed32(&buffer_, restarts_[i]);
   }
   PutFixed32(&buffer_, restarts_.size());
   finished_ = true;
   return Slice(buffer_);
 }
void rocksdb::BlockBuilder::operator= (const BlockBuilder &) private
void rocksdb::BlockBuilder::Reset ()
Definition at line 58 of file block_builder.cc.
References buffer_, counter_, finished_, last_key_, and restarts_.
Referenced by rocksdb::BlockBasedTableBuilder::WriteBlock().
{
   buffer_.clear();
   restarts_.clear();
   restarts_.push_back(0);       // First restart point is at offset 0
   counter_ = 0;
   finished_ = false;
   last_key_.clear();
 }
Member Data Documentation
const int rocksdb::BlockBuilder::block_restart_interval_ private
Definition at line 51 of file block_builder.h.
Referenced by Add(), BlockBuilder(), and EstimateSizeAfterKV().
std::string rocksdb::BlockBuilder::buffer_ private
Definition at line 54 of file block_builder.h.
Referenced by Add(), CurrentSizeEstimate(), empty(), Finish(), and Reset().
const Comparator* rocksdb::BlockBuilder::comparator_ private
Definition at line 52 of file block_builder.h.
Referenced by Add().
int rocksdb::BlockBuilder::counter_ private
Definition at line 56 of file block_builder.h.
Referenced by Add(), EstimateSizeAfterKV(), and Reset().
bool rocksdb::BlockBuilder::finished_ private
Definition at line 57 of file block_builder.h.
Referenced by Add(), Finish(), and Reset().
std::string rocksdb::BlockBuilder::last_key_ private
Definition at line 58 of file block_builder.h.
Referenced by Add(), and Reset().
std::vector<uint32_t> rocksdb::BlockBuilder::restarts_ private
Definition at line 55 of file block_builder.h.
Referenced by Add(), BlockBuilder(), CurrentSizeEstimate(), Finish(), and Reset().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/table/block_builder.h
rippled/src/ripple/rocksdb/rocksdb/table/block_builder.cc