rippled: ripple::PeerFinder::RedirectHandouts Class Reference
ripple::PeerFinder::RedirectHandouts Class Reference
#include <RedirectHandouts.h>
Public Member Functions
RedirectHandouts (SlotImp::ptr const &slot)
bool full () const
SlotImp::ptr const & slot () const
std::vector< Endpoint > const & list () const
bool try_insert (Endpoint const &ep)
Private Attributes
SlotImp::ptr m_slot
std::vector< Endpoint > m_list
Detailed Description
Receives handouts for redirecting a connection. An incoming connection request is redirected when we are full on slots.
Definition at line 32 of file RedirectHandouts.h.
Constructor & Destructor Documentation
ripple::PeerFinder::RedirectHandouts::RedirectHandouts (SlotImp::ptr const & slot)
Definition at line 25 of file RedirectHandouts.cpp.
References m_list, and ripple::PeerFinder::Tuning::redirectEndpointCount.
     : m_slot (slot)
 {
     m_list.reserve (Tuning::redirectEndpointCount);
 }
Member Function Documentation
bool ripple::PeerFinder::RedirectHandouts::full () const inline
Definition at line 37 of file RedirectHandouts.h.
References m_list, and ripple::PeerFinder::Tuning::redirectEndpointCount.
Referenced by try_insert().
     {
         return m_list.size() >= Tuning::redirectEndpointCount;
     }
std::vector<Endpoint> const& ripple::PeerFinder::RedirectHandouts::list () const inline
Definition at line 47 of file RedirectHandouts.h.
References m_list.
Referenced by ripple::PeerFinder::Logic::redirect().
     {
         return m_list;
     }
SlotImp::ptr const& ripple::PeerFinder::RedirectHandouts::slot () const inline
Definition at line 42 of file RedirectHandouts.h.
References m_slot.
     {
         return m_slot;
     }
bool ripple::PeerFinder::RedirectHandouts::try_insert (Endpoint const & ep)
Definition at line 32 of file RedirectHandouts.cpp.
References ripple::PeerFinder::Endpoint::address, beast::IP::Endpoint::address(), full(), ripple::PeerFinder::Endpoint::hops, m_list, m_slot, and ripple::PeerFinder::Tuning::maxHops.
 {
     if (full ())
         return false;
     // VFALCO NOTE This check can be removed when we provide the
     //             addresses in a peer HTTP handshake instead of
     //             the tmENDPOINTS message.
     //
     if (ep.hops > Tuning::maxHops)
         return false;
     // Don't send them our address
     if (ep.hops == 0)
         return false;
     // Don't send them their own address
     if (m_slot->remote_endpoint().address() ==
         ep.address.address())
         return false;
     // Make sure the address isn't already in our list
     if (std::any_of (m_list.begin(), m_list.end(),
         [&ep](Endpoint const& other)
         {
             // Ignore port for security reasons
             return other.address.address() == ep.address.address();
         }))
     {
         return false;
     }
     m_list.emplace_back (ep.address, ep.hops);
     return true;
 }
Member Data Documentation
std::vector<Endpoint> ripple::PeerFinder::RedirectHandouts::m_list private
Definition at line 56 of file RedirectHandouts.h.
Referenced by full(), list(), RedirectHandouts(), and try_insert().
SlotImp::ptr ripple::PeerFinder::RedirectHandouts::m_slot private
Definition at line 55 of file RedirectHandouts.h.
Referenced by slot(), and try_insert().
The documentation for this class was generated from the following files:
rippled/src/ripple/peerfinder/impl/RedirectHandouts.h
rippled/src/ripple/peerfinder/impl/RedirectHandouts.cpp