rippled: rocksdb::LDBCommand Class Reference
rocksdb::LDBCommand Class Reference abstract
#include <ldb_cmd.h>
Public Member Functions
bool ValidateCmdLineOptions ()
virtual Options PrepareOptionsForOpenDB ()
virtual void SetOptions (Options options)
virtual bool NoDBOpen ()
virtual ~LDBCommand ()
void Run ()
virtual void DoCommand ()=0
LDBCommandExecuteResult GetExecuteState ()
void ClearPreviousRunState ()
Static Public Member Functions
static LDBCommand * InitFromCmdLineArgs (const vector< string > &args, const Options &options=Options())
static LDBCommand * InitFromCmdLineArgs (int argc, char **argv, const Options &options=Options())
static string HexToString (const string &str)
static string StringToHex (const string &str)
Static Public Attributes
static const string ARG_DB = "db"
static const string ARG_HEX = "hex"
static const string ARG_KEY_HEX = "key_hex"
static const string ARG_VALUE_HEX = "value_hex"
static const string ARG_TTL = "ttl"
static const string ARG_TTL_START = "start_time"
static const string ARG_TTL_END = "end_time"
static const string ARG_TIMESTAMP = "timestamp"
static const string ARG_FROM = "from"
static const string ARG_TO = "to"
static const string ARG_MAX_KEYS = "max_keys"
static const string ARG_BLOOM_BITS = "bloom_bits"
static const string ARG_COMPRESSION_TYPE = "compression_type"
static const string ARG_BLOCK_SIZE = "block_size"
static const string ARG_AUTO_COMPACTION = "auto_compaction"
static const string ARG_WRITE_BUFFER_SIZE = "write_buffer_size"
static const string ARG_FILE_SIZE = "file_size"
static const string ARG_CREATE_IF_MISSING = "create_if_missing"
static const char * DELIM = " ==> "
Protected Member Functions
bool ParseKeyValue (const string &line, string *key, string *value, bool is_key_hex, bool is_value_hex)
LDBCommand (const map< string, string > &options, const vector< string > &flags, bool is_read_only, const vector< string > &valid_cmd_line_options)
void OpenDB ()
void CloseDB ()
vector< string > BuildCmdLineOptions (vector< string > options)
bool ParseIntOption (const map< string, string > &options, const string &option, int &value, LDBCommandExecuteResult &exec_state)
bool ParseStringOption (const map< string, string > &options, const string &option, string *value)
Static Protected Member Functions
static string PrintKeyValue (const string &key, const string &value, bool is_key_hex, bool is_value_hex)
static string PrintKeyValue (const string &key, const string &value, bool is_hex)
static bool IsFlagPresent (const vector< string > &flags, const string &flag)
static string HelpRangeCmdArgs ()
Protected Attributes
LDBCommandExecuteResult exec_state_
string db_path_
DB * db_
StackableDB * sdb_
bool is_read_only_
bool is_key_hex_
bool is_value_hex_
bool is_db_ttl_
bool timestamp_
const map< string, string > option_map_
const vector< string > flags_
const vector< string > valid_cmd_line_options_
Options options_
Private Member Functions
bool IsKeyHex (const map< string, string > &options, const vector< string > &flags)
bool IsValueHex (const map< string, string > &options, const vector< string > &flags)
bool ParseBooleanOption (const map< string, string > &options, const string &option, bool default_val)
bool StringToBool (string val)
Static Private Member Functions
static LDBCommand * SelectCommand (const string &cmd, const vector< string > &cmdParams, const map< string, string > &option_map, const vector< string > &flags)
Detailed Description
Definition at line 32 of file ldb_cmd.h.
Constructor & Destructor Documentation
virtual rocksdb::LDBCommand::~LDBCommand () inline virtual
Definition at line 78 of file ldb_cmd.h.
References db_.
{
     if (db_ != nullptr) {
       delete db_;
       db_ = nullptr;
     }
   }
rocksdb::LDBCommand::LDBCommand (const map< string, string > & options, const vector< string > & flags, bool is_read_only, const vector< string > & valid_cmd_line_options) inline protected
Definition at line 188 of file ldb_cmd.h.
References ARG_DB, ARG_TIMESTAMP, ARG_TTL, db_path_, is_db_ttl_, is_key_hex_, is_value_hex_, IsFlagPresent(), IsKeyHex(), IsValueHex(), and timestamp_.
                                                                               :
       db_(nullptr),
       is_read_only_(is_read_only),
       is_key_hex_(false),
       is_value_hex_(false),
       is_db_ttl_(false),
       timestamp_(false),
       option_map_(options),
       flags_(flags),
       valid_cmd_line_options_(valid_cmd_line_options) {
     map<string, string>::const_iterator itr = options.find(ARG_DB);
     if (itr != options.end()) {
       db_path_ = itr->second;
     }
     is_key_hex_ = IsKeyHex(options, flags);
     is_value_hex_ = IsValueHex(options, flags);
     is_db_ttl_ = IsFlagPresent(flags, ARG_TTL);
     timestamp_ = IsFlagPresent(flags, ARG_TIMESTAMP);
   }
Member Function Documentation
vector<string> rocksdb::LDBCommand::BuildCmdLineOptions (vector< string > options) inline protected
A helper function that returns a list of command line options used by this command. It includes the common options and the ones passed in.
Definition at line 279 of file ldb_cmd.h.
References ARG_AUTO_COMPACTION, ARG_BLOCK_SIZE, ARG_BLOOM_BITS, ARG_COMPRESSION_TYPE, ARG_DB, ARG_FILE_SIZE, and ARG_WRITE_BUFFER_SIZE.
{
     vector<string> ret = {ARG_DB, ARG_BLOOM_BITS, ARG_BLOCK_SIZE,
                           ARG_AUTO_COMPACTION, ARG_COMPRESSION_TYPE,
                           ARG_WRITE_BUFFER_SIZE, ARG_FILE_SIZE};
     ret.insert(ret.end(), options.begin(), options.end());
     return ret;
   }
void rocksdb::LDBCommand::ClearPreviousRunState () inline
Definition at line 114 of file ldb_cmd.h.
References exec_state_, and rocksdb::LDBCommandExecuteResult::Reset().
{
     exec_state_.Reset();
   }
void rocksdb::LDBCommand::CloseDB () inline protected
Definition at line 238 of file ldb_cmd.h.
References db_.
Referenced by rocksdb::ReduceDBLevelsCommand::DoCommand(), and Run().
                   {
     if (db_ != nullptr) {
       delete db_;
       db_ = nullptr;
     }
   }
virtual void rocksdb::LDBCommand::DoCommand () pure virtual
Implemented in rocksdb::DBQuerierCommand, rocksdb::PutCommand, rocksdb::DeleteCommand, rocksdb::ScanCommand, rocksdb::BatchPutCommand, rocksdb::ApproxSizeCommand, rocksdb::GetCommand, rocksdb::WALDumperCommand, rocksdb::ChangeCompactionStyleCommand, rocksdb::ReduceDBLevelsCommand, rocksdb::ManifestDumpCommand, rocksdb::DBLoaderCommand, rocksdb::InternalDumpCommand, rocksdb::DBDumperCommand, and rocksdb::CompactorCommand.
Referenced by Run().
LDBCommandExecuteResult rocksdb::LDBCommand::GetExecuteState () inline
Definition at line 110 of file ldb_cmd.h.
References exec_state_.
Referenced by rocksdb::ReduceLevelTest::ReduceLevels(), and rocksdb::LDBCommandRunner::RunCommand().
{
     return exec_state_;
   }
static string rocksdb::LDBCommand::HelpRangeCmdArgs () inline static protected
Definition at line 266 of file ldb_cmd.h.
References ARG_FROM, and ARG_TO.
Referenced by rocksdb::CompactorCommand::Help(), rocksdb::DBDumperCommand::Help(), rocksdb::InternalDumpCommand::Help(), and rocksdb::ScanCommand::Help().
{
     ostringstream str_stream;
     str_stream << " ";
     str_stream << "[--" << ARG_FROM << "] ";
     str_stream << "[--" << ARG_TO << "] ";
     return str_stream.str();
   }
static string rocksdb::LDBCommand::HexToString (const string & str) inline static
Definition at line 118 of file ldb_cmd.h.
Referenced by rocksdb::if().
{
     string parsed;
     if (str[0] != '0' || str[1] != 'x') {
       fprintf(stderr, "Invalid hex input %s.  Must start with 0x\n",
               str.c_str());
       throw "Invalid hex input";
     }
     for (unsigned int i = 2; i < str.length();) {
       int c;
       sscanf(str.c_str() + i, "%2X", &c);
       parsed.push_back(c);
       i += 2;
     }
     return parsed;
   }
LDBCommand * rocksdb::LDBCommand::InitFromCmdLineArgs (const vector< string > & args, const Options & options = Options()) static
Parse the command-line arguments and create the appropriate LDBCommand2 instance. The command line arguments must be in the following format: ./ldb –db=PATH_TO_DB [–commonOpt1=commonOpt1Val] .. COMMAND <PARAM1> <PARAM2> ... [-cmdSpecificOpt1=cmdSpecificOpt1Val] .. This is similar to the command line format used by HBaseClientTool. Command name is not included in args. Returns nullptr if the command-line cannot be parsed.
Definition at line 69 of file ldb_cmd.cc.
References arg, SelectCommand(), and rocksdb::stringSplit().
Referenced by rocksdb::ReduceLevelTest::ReduceLevels(), and rocksdb::LDBCommandRunner::RunCommand().
   {
   // --x=y command line arguments are added as x->y map entries.
   map<string, string> option_map;
   // Command-line arguments of the form --hex end up in this array as hex
   vector<string> flags;
   // Everything other than option_map and flags. Represents commands
   // and their parameters.  For eg: put key1 value1 go into this vector.
   vector<string> cmdTokens;
   const string OPTION_PREFIX = "--";
   for (const auto& arg : args) {
     if (arg[0] == '-' && arg[1] == '-'){
       vector<string> splits = stringSplit(arg, '=');
       if (splits.size() == 2) {
         string optionKey = splits[0].substr(OPTION_PREFIX.size());
         option_map[optionKey] = splits[1];
       } else {
         string optionKey = splits[0].substr(OPTION_PREFIX.size());
         flags.push_back(optionKey);
       }
     } else {
       cmdTokens.push_back(arg);
     }
   }
   if (cmdTokens.size() < 1) {
     fprintf(stderr, "Command not specified!");
     return nullptr;
   }
   string cmd = cmdTokens[0];
   vector<string> cmdParams(cmdTokens.begin()+1, cmdTokens.end());
   LDBCommand* command = LDBCommand::SelectCommand(
     cmd,
     cmdParams,
     option_map,
     flags
   );
   if (command) {
     command->SetOptions(options);
   }
   return command;
 }
LDBCommand * rocksdb::LDBCommand::InitFromCmdLineArgs (int argc, char ** argv, const Options & options = Options()) static
Definition at line 47 of file ldb_cmd.cc.
   {
   vector<string> args;
   for (int i = 1; i < argc; i++) {
     args.push_back(argv[i]);
   }
   return InitFromCmdLineArgs(args, options);
 }
static bool rocksdb::LDBCommand::IsFlagPresent (const vector< string > & flags, const string & flag) inline static protected
Return true if the specified flag is present in the specified flags vector
Definition at line 262 of file ldb_cmd.h.
Referenced by IsKeyHex(), IsValueHex(), and LDBCommand().
{
     return (std::find(flags.begin(), flags.end(), flag) != flags.end());
   }
bool rocksdb::LDBCommand::IsKeyHex (const map< string, string > & options, const vector< string > & flags) inline private
Interpret command line options and flags to determine if the key should be input/output in hex.
Definition at line 301 of file ldb_cmd.h.
References ARG_HEX, ARG_KEY_HEX, IsFlagPresent(), and ParseBooleanOption().
Referenced by LDBCommand().
{
     return (IsFlagPresent(flags, ARG_HEX) ||
         IsFlagPresent(flags, ARG_KEY_HEX) ||
         ParseBooleanOption(options, ARG_HEX, false) ||
         ParseBooleanOption(options, ARG_KEY_HEX, false));
   }
bool rocksdb::LDBCommand::IsValueHex (const map< string, string > & options, const vector< string > & flags) inline private
Interpret command line options and flags to determine if the value should be input/output in hex.
Definition at line 313 of file ldb_cmd.h.
References ARG_HEX, ARG_VALUE_HEX, IsFlagPresent(), and ParseBooleanOption().
Referenced by LDBCommand().
{
     return (IsFlagPresent(flags, ARG_HEX) ||
           IsFlagPresent(flags, ARG_VALUE_HEX) ||
           ParseBooleanOption(options, ARG_HEX, false) ||
           ParseBooleanOption(options, ARG_VALUE_HEX, false));
   }
virtual bool rocksdb::LDBCommand::NoDBOpen () inline virtual
Reimplemented in rocksdb::WALDumperCommand, rocksdb::ReduceDBLevelsCommand, and rocksdb::ManifestDumpCommand.
Definition at line 74 of file ldb_cmd.h.
Referenced by Run().
{
     return false;
   }
void rocksdb::LDBCommand::OpenDB () inline protected
Definition at line 211 of file ldb_cmd.h.
References db_, db_path_, exec_state_, rocksdb::LDBCommandExecuteResult::FAILED(), is_db_ttl_, is_read_only_, rocksdb::LDBCommandExecuteResult::IsNotStarted(), rocksdb::Status::ok(), rocksdb::DB::Open(), rocksdb::DB::OpenForReadOnly(), rocksdb::UtilityDB::OpenTtlDB(), options_, PrepareOptionsForOpenDB(), sdb_, and rocksdb::Status::ToString().
Referenced by rocksdb::ReduceDBLevelsCommand::DoCommand(), and Run().
                 {
     Options opt = PrepareOptionsForOpenDB();
     if (!exec_state_.IsNotStarted()) {
       return;
     }
     // Open the DB.
     Status st;
     if (is_db_ttl_) {
       if (is_read_only_) {
         st = UtilityDB::OpenTtlDB(opt, db_path_, &sdb_, 0, true);
       } else {
         st = UtilityDB::OpenTtlDB(opt, db_path_, &sdb_);
       }
       db_ = sdb_;
     } else if (is_read_only_) {
       st = DB::OpenForReadOnly(opt, db_path_, &db_);
     } else {
       st = DB::Open(opt, db_path_, &db_);
     }
     if (!st.ok()) {
       string msg = st.ToString();
       exec_state_ = LDBCommandExecuteResult::FAILED(msg);
     }
     options_ = opt;
   }
bool rocksdb::LDBCommand::ParseBooleanOption (const map< string, string > & options, const string & option, bool default_val) inline private
Returns the value of the specified option as a boolean. default_val is used if the option is not found in options. Throws an exception if the value of the option is not "true" or "false" (case insensitive).
Definition at line 327 of file ldb_cmd.h.
References StringToBool().
Referenced by IsKeyHex(), and IsValueHex().
{
     map<string, string>::const_iterator itr = options.find(option);
     if (itr != options.end()) {
       string option_val = itr->second;
       return StringToBool(itr->second);
     }
     return default_val;
   }
bool rocksdb::LDBCommand::ParseIntOption (const map< string, string > & options, const string & option, int & value, LDBCommandExecuteResult & exec_state) protected
Parses the specific integer option and fills in the value. Returns true if the option is found. Returns false if the option is not found or if there is an error parsing the value. If there is an error, the specified exec_state is also updated.
Definition at line 169 of file ldb_cmd.cc.
References rocksdb::LDBCommandExecuteResult::FAILED().
Referenced by rocksdb::DBDumperCommand::DoCommand(), and rocksdb::ScanCommand::DoCommand().
{
   map<string, string>::const_iterator itr = option_map_.find(option);
   if (itr != option_map_.end()) {
     try {
       value = stoi(itr->second);
       return true;
     } catch(const invalid_argument&) {
       exec_state = LDBCommandExecuteResult::FAILED(option +
                       " has an invalid value.");
     } catch(const out_of_range&) {
       exec_state = LDBCommandExecuteResult::FAILED(option +
                       " has a value out-of-range.");
     }
   }
   return false;
 }
bool rocksdb::LDBCommand::ParseKeyValue (const string & line, string * key, string * value, bool is_key_hex, bool is_value_hex) protected
Definition at line 278 of file ldb_cmd.cc.
References HexToString().
Referenced by rocksdb::DBLoaderCommand::DoCommand().
{
   size_t pos = line.find(DELIM);
   if (pos != string::npos) {
     *key = line.substr(0, pos);
     *value = line.substr(pos + strlen(DELIM));
     if (is_key_hex) {
       *key = HexToString(*key);
     }
     if (is_value_hex) {
       *value = HexToString(*value);
     }
     return true;
   } else {
     return false;
   }
 }
bool rocksdb::LDBCommand::ParseStringOption (const map< string, string > & options, const string & option, string * value) protected
Parses the specified option and fills in the value. Returns true if the option is found. Returns false otherwise.
Definition at line 194 of file ldb_cmd.cc.
{
   auto itr = option_map_.find(option);
   if (itr != option_map_.end()) {
     *value = itr->second;
     return true;
   }
   return false;
 }
Options rocksdb::LDBCommand::PrepareOptionsForOpenDB () virtual
Reimplemented in rocksdb::PutCommand, rocksdb::BatchPutCommand, rocksdb::ChangeCompactionStyleCommand, rocksdb::ReduceDBLevelsCommand, and rocksdb::DBLoaderCommand.
Definition at line 204 of file ldb_cmd.cc.
References rocksdb::Options::block_size, rocksdb::Options::compression, rocksdb::Options::create_if_missing, rocksdb::Options::disable_auto_compactions, rocksdb::LDBCommandExecuteResult::FAILED(), rocksdb::Options::filter_policy, rocksdb::kBZip2Compression, rocksdb::kNoCompression, rocksdb::kSnappyCompression, rocksdb::kZlibCompression, rocksdb::NewBloomFilterPolicy(), options_, rocksdb::Options::target_file_size_base, and rocksdb::Options::write_buffer_size.
Referenced by OpenDB(), rocksdb::DBLoaderCommand::PrepareOptionsForOpenDB(), rocksdb::ReduceDBLevelsCommand::PrepareOptionsForOpenDB(), and rocksdb::ChangeCompactionStyleCommand::PrepareOptionsForOpenDB().
{
   Options opt = options_;
   opt.create_if_missing = false;
   map<string, string>::const_iterator itr;
   int bits;
   if (ParseIntOption(option_map_, ARG_BLOOM_BITS, bits, exec_state_)) {
     if (bits > 0) {
       opt.filter_policy = NewBloomFilterPolicy(bits);
     } else {
       exec_state_ = LDBCommandExecuteResult::FAILED(ARG_BLOOM_BITS +
                       " must be > 0.");
     }
   }
   int block_size;
   if (ParseIntOption(option_map_, ARG_BLOCK_SIZE, block_size, exec_state_)) {
     if (block_size > 0) {
       opt.block_size = block_size;
     } else {
       exec_state_ = LDBCommandExecuteResult::FAILED(ARG_BLOCK_SIZE +
                       " must be > 0.");
     }
   }
   itr = option_map_.find(ARG_AUTO_COMPACTION);
   if (itr != option_map_.end()) {
     opt.disable_auto_compactions = ! StringToBool(itr->second);
   }
   itr = option_map_.find(ARG_COMPRESSION_TYPE);
   if (itr != option_map_.end()) {
     string comp = itr->second;
     if (comp == "no") {
       opt.compression = kNoCompression;
     } else if (comp == "snappy") {
       opt.compression = kSnappyCompression;
     } else if (comp == "zlib") {
       opt.compression = kZlibCompression;
     } else if (comp == "bzip2") {
       opt.compression = kBZip2Compression;
     } else {
       // Unknown compression.
       exec_state_ = LDBCommandExecuteResult::FAILED(
                       "Unknown compression level: " + comp);
     }
   }
   int write_buffer_size;
   if (ParseIntOption(option_map_, ARG_WRITE_BUFFER_SIZE, write_buffer_size,
         exec_state_)) {
     if (write_buffer_size > 0) {
       opt.write_buffer_size = write_buffer_size;
     } else {
       exec_state_ = LDBCommandExecuteResult::FAILED(ARG_WRITE_BUFFER_SIZE +
                       " must be > 0.");
     }
   }
   int file_size;
   if (ParseIntOption(option_map_, ARG_FILE_SIZE, file_size, exec_state_)) {
     if (file_size > 0) {
       opt.target_file_size_base = file_size;
     } else {
       exec_state_ = LDBCommandExecuteResult::FAILED(ARG_FILE_SIZE +
                       " must be > 0.");
     }
   }
   return opt;
 }
static string rocksdb::LDBCommand::PrintKeyValue (const string & key, const string & value, bool is_key_hex, bool is_value_hex) inline static protected
Definition at line 245 of file ldb_cmd.h.
References DELIM, and StringToHex().
Referenced by rocksdb::DBDumperCommand::DoCommand(), and PrintKeyValue().
{
     string result;
     result.append(is_key_hex ? StringToHex(key) : key);
     result.append(DELIM);
     result.append(is_value_hex ? StringToHex(value) : value);
     return result;
   }
static string rocksdb::LDBCommand::PrintKeyValue (const string & key, const string & value, bool is_hex) inline static protected
Definition at line 254 of file ldb_cmd.h.
References PrintKeyValue().
                      {
     return PrintKeyValue(key, value, is_hex, is_hex);
   }
void rocksdb::LDBCommand::Run () inline
Definition at line 86 of file ldb_cmd.h.
References CloseDB(), db_, DoCommand(), exec_state_, rocksdb::LDBCommandExecuteResult::IsNotStarted(), NoDBOpen(), OpenDB(), and rocksdb::LDBCommandExecuteResult::SUCCEED().
Referenced by rocksdb::ReduceLevelTest::ReduceLevels(), and rocksdb::LDBCommandRunner::RunCommand().
              {
     if (!exec_state_.IsNotStarted()) {
       return;
     }
     if (db_ == nullptr && !NoDBOpen()) {
       OpenDB();
       if (!exec_state_.IsNotStarted()) {
         return;
       }
     }
     DoCommand();
     if (exec_state_.IsNotStarted()) {
       exec_state_ = LDBCommandExecuteResult::SUCCEED("");
     }
     if (db_ != nullptr) {
       CloseDB ();
     }
   }
LDBCommand * rocksdb::LDBCommand::SelectCommand (const string & cmd, const vector< string > & cmdParams, const map< string, string > & option_map, const vector< string > & flags) static private
Definition at line 120 of file ldb_cmd.cc.
References rocksdb::CompactorCommand::Name(), rocksdb::DBDumperCommand::Name(), rocksdb::InternalDumpCommand::Name(), rocksdb::DBLoaderCommand::Name(), rocksdb::ManifestDumpCommand::Name(), rocksdb::ReduceDBLevelsCommand::Name(), rocksdb::ChangeCompactionStyleCommand::Name(), rocksdb::WALDumperCommand::Name(), rocksdb::GetCommand::Name(), rocksdb::ApproxSizeCommand::Name(), rocksdb::BatchPutCommand::Name(), rocksdb::ScanCommand::Name(), rocksdb::DeleteCommand::Name(), rocksdb::PutCommand::Name(), and rocksdb::DBQuerierCommand::Name().
Referenced by InitFromCmdLineArgs().
     {
   if (cmd == GetCommand::Name()) {
     return new GetCommand(cmdParams, option_map, flags);
   } else if (cmd == PutCommand::Name()) {
     return new PutCommand(cmdParams, option_map, flags);
   } else if (cmd == BatchPutCommand::Name()) {
     return new BatchPutCommand(cmdParams, option_map, flags);
   } else if (cmd == ScanCommand::Name()) {
     return new ScanCommand(cmdParams, option_map, flags);
   } else if (cmd == DeleteCommand::Name()) {
     return new DeleteCommand(cmdParams, option_map, flags);
   } else if (cmd == ApproxSizeCommand::Name()) {
     return new ApproxSizeCommand(cmdParams, option_map, flags);
   } else if (cmd == DBQuerierCommand::Name()) {
     return new DBQuerierCommand(cmdParams, option_map, flags);
   } else if (cmd == CompactorCommand::Name()) {
     return new CompactorCommand(cmdParams, option_map, flags);
   } else if (cmd == WALDumperCommand::Name()) {
     return new WALDumperCommand(cmdParams, option_map, flags);
   } else if (cmd == ReduceDBLevelsCommand::Name()) {
     return new ReduceDBLevelsCommand(cmdParams, option_map, flags);
   } else if (cmd == ChangeCompactionStyleCommand::Name()) {
     return new ChangeCompactionStyleCommand(cmdParams, option_map, flags);
   } else if (cmd == DBDumperCommand::Name()) {
     return new DBDumperCommand(cmdParams, option_map, flags);
   } else if (cmd == DBLoaderCommand::Name()) {
     return new DBLoaderCommand(cmdParams, option_map, flags);
   } else if (cmd == ManifestDumpCommand::Name()) {
     return new ManifestDumpCommand(cmdParams, option_map, flags);
   } else if (cmd == InternalDumpCommand::Name()) {
     return new InternalDumpCommand(cmdParams, option_map, flags);
   }
   return nullptr;
 }
virtual void rocksdb::LDBCommand::SetOptions (Options options) inline virtual
Definition at line 70 of file ldb_cmd.h.
References options_.
{
     options_ = options;
   }
bool rocksdb::LDBCommand::StringToBool (string val) inline private
Converts val to a boolean. val must be either true or false (case insensitive). Otherwise an exception is thrown.
Definition at line 343 of file ldb_cmd.h.
Referenced by ParseBooleanOption().
{
     std::transform(val.begin(), val.end(), val.begin(), ::tolower);
     if (val == "true") {
       return true;
     } else if (val == "false") {
       return false;
     } else {
       throw "Invalid value for boolean argument";
     }
   }
static string rocksdb::LDBCommand::StringToHex (const string & str) inline static
Definition at line 135 of file ldb_cmd.h.
Referenced by rocksdb::WALDumperCommand::DoCommand(), rocksdb::GetCommand::DoCommand(), rocksdb::ScanCommand::DoCommand(), and PrintKeyValue().
{
     string result = "0x";
     char buf[10];
     for (size_t i = 0; i < str.length(); i++) {
       snprintf(buf, 10, "%02X", (unsigned char)str[i]);
       result += buf;
     }
     return result;
   }
bool rocksdb::LDBCommand::ValidateCmdLineOptions ()
Make sure that ONLY the command-line options and flags expected by this command are specified on the command-line. Extraneous options are usually the result of user error. Returns true if all checks pass. Else returns false, and prints an appropriate error msg to stderr.
Definition at line 303 of file ldb_cmd.cc.
Referenced by rocksdb::LDBCommandRunner::RunCommand().
{
   for (map<string, string>::const_iterator itr = option_map_.begin();
         itr != option_map_.end(); itr++) {
     if (find(valid_cmd_line_options_.begin(),
           valid_cmd_line_options_.end(), itr->first) ==
           valid_cmd_line_options_.end()) {
       fprintf(stderr, "Invalid command-line option %s\n", itr->first.c_str());
       return false;
     }
   }
   for (vector<string>::const_iterator itr = flags_.begin();
         itr != flags_.end(); itr++) {
     if (find(valid_cmd_line_options_.begin(),
           valid_cmd_line_options_.end(), *itr) ==
           valid_cmd_line_options_.end()) {
       fprintf(stderr, "Invalid command-line flag %s\n", itr->c_str());
       return false;
     }
   }
   if (!NoDBOpen() && option_map_.find(ARG_DB) == option_map_.end()) {
     fprintf(stderr, "%s must be specified\n", ARG_DB.c_str());
     return false;
   }
   return true;
 }
Member Data Documentation
const string rocksdb::LDBCommand::ARG_AUTO_COMPACTION = "auto_compaction" static
Definition at line 50 of file ldb_cmd.h.
Referenced by BuildCmdLineOptions(), and rocksdb::LDBCommandRunner::PrintHelp().
const string rocksdb::LDBCommand::ARG_BLOCK_SIZE = "block_size" static
Definition at line 49 of file ldb_cmd.h.
Referenced by BuildCmdLineOptions(), and rocksdb::LDBCommandRunner::PrintHelp().
const string rocksdb::LDBCommand::ARG_BLOOM_BITS = "bloom_bits" static
Definition at line 47 of file ldb_cmd.h.
Referenced by BuildCmdLineOptions(), and rocksdb::LDBCommandRunner::PrintHelp().
const string rocksdb::LDBCommand::ARG_COMPRESSION_TYPE = "compression_type" static
Definition at line 48 of file ldb_cmd.h.
Referenced by BuildCmdLineOptions(), and rocksdb::LDBCommandRunner::PrintHelp().
const string rocksdb::LDBCommand::ARG_CREATE_IF_MISSING = "create_if_missing" static
Definition at line 53 of file ldb_cmd.h.
Referenced by rocksdb::DBLoaderCommand::DBLoaderCommand(), and rocksdb::DBLoaderCommand::Help().
const string rocksdb::LDBCommand::ARG_DB = "db" static
Definition at line 36 of file ldb_cmd.h.
Referenced by BuildCmdLineOptions(), LDBCommand(), rocksdb::ReduceDBLevelsCommand::PrepareArgs(), and rocksdb::LDBCommandRunner::PrintHelp().
const string rocksdb::LDBCommand::ARG_FILE_SIZE = "file_size" static
Definition at line 52 of file ldb_cmd.h.
Referenced by BuildCmdLineOptions(), and rocksdb::LDBCommandRunner::PrintHelp().
const string rocksdb::LDBCommand::ARG_FROM = "from" static
Definition at line 44 of file ldb_cmd.h.
Referenced by rocksdb::ApproxSizeCommand::ApproxSizeCommand(), rocksdb::CompactorCommand::CompactorCommand(), rocksdb::DBDumperCommand::DBDumperCommand(), rocksdb::DBLoaderCommand::DBLoaderCommand(), HelpRangeCmdArgs(), and rocksdb::InternalDumpCommand::InternalDumpCommand().
const string rocksdb::LDBCommand::ARG_HEX = "hex" static
Definition at line 37 of file ldb_cmd.h.
Referenced by rocksdb::ApproxSizeCommand::ApproxSizeCommand(), rocksdb::CompactorCommand::CompactorCommand(), rocksdb::DBDumperCommand::DBDumperCommand(), rocksdb::DBLoaderCommand::DBLoaderCommand(), rocksdb::DBQuerierCommand::DBQuerierCommand(), rocksdb::DeleteCommand::DeleteCommand(), rocksdb::GetCommand::GetCommand(), rocksdb::InternalDumpCommand::InternalDumpCommand(), IsKeyHex(), IsValueHex(), rocksdb::ManifestDumpCommand::ManifestDumpCommand(), and rocksdb::LDBCommandRunner::PrintHelp().
const string rocksdb::LDBCommand::ARG_KEY_HEX = "key_hex" static
Definition at line 38 of file ldb_cmd.h.
Referenced by rocksdb::ApproxSizeCommand::ApproxSizeCommand(), rocksdb::CompactorCommand::CompactorCommand(), rocksdb::DBDumperCommand::DBDumperCommand(), rocksdb::DBLoaderCommand::DBLoaderCommand(), rocksdb::DBQuerierCommand::DBQuerierCommand(), rocksdb::DeleteCommand::DeleteCommand(), rocksdb::GetCommand::GetCommand(), rocksdb::InternalDumpCommand::InternalDumpCommand(), IsKeyHex(), and rocksdb::LDBCommandRunner::PrintHelp().
const string rocksdb::LDBCommand::ARG_MAX_KEYS = "max_keys" static
Definition at line 46 of file ldb_cmd.h.
Referenced by rocksdb::DBDumperCommand::DBDumperCommand(), rocksdb::DBDumperCommand::Help(), rocksdb::InternalDumpCommand::Help(), rocksdb::ScanCommand::Help(), and rocksdb::InternalDumpCommand::InternalDumpCommand().
const string rocksdb::LDBCommand::ARG_TIMESTAMP = "timestamp" static
Definition at line 43 of file ldb_cmd.h.
Referenced by rocksdb::DBDumperCommand::DBDumperCommand(), rocksdb::DBDumperCommand::Help(), rocksdb::ScanCommand::Help(), and LDBCommand().
const string rocksdb::LDBCommand::ARG_TO = "to" static
Definition at line 45 of file ldb_cmd.h.
Referenced by rocksdb::ApproxSizeCommand::ApproxSizeCommand(), rocksdb::CompactorCommand::CompactorCommand(), rocksdb::DBDumperCommand::DBDumperCommand(), rocksdb::DBLoaderCommand::DBLoaderCommand(), HelpRangeCmdArgs(), and rocksdb::InternalDumpCommand::InternalDumpCommand().
const string rocksdb::LDBCommand::ARG_TTL = "ttl" static
Definition at line 40 of file ldb_cmd.h.
Referenced by rocksdb::CompactorCommand::CompactorCommand(), rocksdb::DBDumperCommand::DBDumperCommand(), rocksdb::DBQuerierCommand::DBQuerierCommand(), rocksdb::GetCommand::GetCommand(), rocksdb::DBDumperCommand::Help(), rocksdb::GetCommand::Help(), rocksdb::ScanCommand::Help(), LDBCommand(), and rocksdb::LDBCommandRunner::PrintHelp().
const string rocksdb::LDBCommand::ARG_TTL_END = "end_time" static
Definition at line 42 of file ldb_cmd.h.
Referenced by rocksdb::DBDumperCommand::DBDumperCommand(), rocksdb::DBDumperCommand::DoCommand(), rocksdb::ScanCommand::DoCommand(), rocksdb::DBDumperCommand::Help(), and rocksdb::ScanCommand::Help().
const string rocksdb::LDBCommand::ARG_TTL_START = "start_time" static
Definition at line 41 of file ldb_cmd.h.
Referenced by rocksdb::DBDumperCommand::DBDumperCommand(), rocksdb::DBDumperCommand::DoCommand(), rocksdb::ScanCommand::DoCommand(), rocksdb::DBDumperCommand::Help(), and rocksdb::ScanCommand::Help().
const string rocksdb::LDBCommand::ARG_VALUE_HEX = "value_hex" static
Definition at line 39 of file ldb_cmd.h.
Referenced by rocksdb::ApproxSizeCommand::ApproxSizeCommand(), rocksdb::CompactorCommand::CompactorCommand(), rocksdb::DBDumperCommand::DBDumperCommand(), rocksdb::DBLoaderCommand::DBLoaderCommand(), rocksdb::DBQuerierCommand::DBQuerierCommand(), rocksdb::DeleteCommand::DeleteCommand(), rocksdb::GetCommand::GetCommand(), rocksdb::InternalDumpCommand::InternalDumpCommand(), IsValueHex(), and rocksdb::LDBCommandRunner::PrintHelp().
const string rocksdb::LDBCommand::ARG_WRITE_BUFFER_SIZE = "write_buffer_size" static
Definition at line 51 of file ldb_cmd.h.
Referenced by BuildCmdLineOptions(), and rocksdb::LDBCommandRunner::PrintHelp().
DB* rocksdb::LDBCommand::db_ protected
Definition at line 151 of file ldb_cmd.h.
Referenced by CloseDB(), rocksdb::CompactorCommand::DoCommand(), rocksdb::DBDumperCommand::DoCommand(), rocksdb::InternalDumpCommand::DoCommand(), rocksdb::DBLoaderCommand::DoCommand(), rocksdb::ReduceDBLevelsCommand::DoCommand(), rocksdb::ChangeCompactionStyleCommand::DoCommand(), rocksdb::GetCommand::DoCommand(), rocksdb::ScanCommand::DoCommand(), OpenDB(), Run(), and ~LDBCommand().
string rocksdb::LDBCommand::db_path_ protected
Definition at line 150 of file ldb_cmd.h.
Referenced by rocksdb::ManifestDumpCommand::DoCommand(), rocksdb::ReduceDBLevelsCommand::DoCommand(), rocksdb::ReduceDBLevelsCommand::GetOldNumOfLevels(), LDBCommand(), and OpenDB().
const char * rocksdb::LDBCommand::DELIM = " ==> " static
Definition at line 145 of file ldb_cmd.h.
Referenced by PrintKeyValue().
LDBCommandExecuteResult rocksdb::LDBCommand::exec_state_ protected
Definition at line 149 of file ldb_cmd.h.
Referenced by ClearPreviousRunState(), rocksdb::CompactorCommand::DoCommand(), rocksdb::DBDumperCommand::DoCommand(), rocksdb::InternalDumpCommand::DoCommand(), rocksdb::ManifestDumpCommand::DoCommand(), rocksdb::ReduceDBLevelsCommand::DoCommand(), rocksdb::ChangeCompactionStyleCommand::DoCommand(), rocksdb::WALDumperCommand::DoCommand(), rocksdb::GetCommand::DoCommand(), rocksdb::ScanCommand::DoCommand(), GetExecuteState(), rocksdb::if(), OpenDB(), and Run().
const vector<string> rocksdb::LDBCommand::flags_ protected
Flags passed on the command-line.
Definition at line 180 of file ldb_cmd.h.
bool rocksdb::LDBCommand::is_db_ttl_ protected
If true, the value is treated as timestamp suffixed
Definition at line 167 of file ldb_cmd.h.
Referenced by rocksdb::DBDumperCommand::DoCommand(), rocksdb::ScanCommand::DoCommand(), LDBCommand(), and OpenDB().
bool rocksdb::LDBCommand::is_key_hex_ protected
If true, the key is input/output as hex in get/put/scan/delete etc.
Definition at line 161 of file ldb_cmd.h.
Referenced by rocksdb::DBDumperCommand::DoCommand(), rocksdb::InternalDumpCommand::DoCommand(), rocksdb::DBLoaderCommand::DoCommand(), rocksdb::ManifestDumpCommand::DoCommand(), rocksdb::ScanCommand::DoCommand(), and LDBCommand().
bool rocksdb::LDBCommand::is_read_only_ protected
true implies that this command can work if the db is opened in read-only mode.
Definition at line 158 of file ldb_cmd.h.
Referenced by OpenDB().
bool rocksdb::LDBCommand::is_value_hex_ protected
If true, the value is input/output as hex in get/put/scan/delete etc.
Definition at line 164 of file ldb_cmd.h.
Referenced by rocksdb::DBDumperCommand::DoCommand(), rocksdb::InternalDumpCommand::DoCommand(), rocksdb::DBLoaderCommand::DoCommand(), rocksdb::GetCommand::DoCommand(), rocksdb::ScanCommand::DoCommand(), and LDBCommand().
const map<string, string> rocksdb::LDBCommand::option_map_ protected
Map of options passed on the command-line.
Definition at line 175 of file ldb_cmd.h.
Referenced by rocksdb::DBDumperCommand::DoCommand(), and rocksdb::ScanCommand::DoCommand().
Options rocksdb::LDBCommand::options_ protected
Definition at line 293 of file ldb_cmd.h.
Referenced by rocksdb::InternalDumpCommand::DoCommand(), OpenDB(), and SetOptions().
StackableDB* rocksdb::LDBCommand::sdb_ protected
Definition at line 152 of file ldb_cmd.h.
Referenced by OpenDB().
bool rocksdb::LDBCommand::timestamp_ protected
Definition at line 170 of file ldb_cmd.h.
Referenced by rocksdb::DBDumperCommand::DoCommand(), rocksdb::ScanCommand::DoCommand(), and LDBCommand().
const vector<string> rocksdb::LDBCommand::valid_cmd_line_options_ protected
List of command-line options valid for this command
Definition at line 183 of file ldb_cmd.h.
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/util/ldb_cmd.h
rippled/src/ripple/rocksdb/rocksdb/util/ldb_cmd.cc