rippled: beast::StringEncodingConverter< CharPointerType_Src, CharPointerType_Dest > Struct Template Reference
beast::StringEncodingConverter< CharPointerType_Src, CharPointerType_Dest > Struct Template Reference
Static Public Member Functions
static CharPointerType_Dest convert (const String &s)
Detailed Description
template<class CharPointerType_Src, class CharPointerType_Dest>
struct beast::StringEncodingConverter< CharPointerType_Src, CharPointerType_Dest >
Definition at line 1863 of file String.cpp.
Member Function Documentation
template<class CharPointerType_Src, class CharPointerType_Dest> static CharPointerType_Dest beast::StringEncodingConverter< CharPointerType_Src, CharPointerType_Dest >::convert (const String & s) inline static
Definition at line 1865 of file String.cpp.
References beast::addBytesToPointer(), beast::bmin(), beast::emptyChar, beast::String::getCharPointer(), beast::String::isEmpty(), beast::String::preallocateBytes(), and beast::zeromem().
     {
         String& source = const_cast <String&> (s);
         typedef typename CharPointerType_Dest::CharType DestChar;
         if (source.isEmpty())
             return CharPointerType_Dest (reinterpret_cast <const DestChar*> (&emptyChar));
         CharPointerType_Src text (source.getCharPointer());
         const size_t extraBytesNeeded = CharPointerType_Dest::getBytesRequiredFor (text);
         const size_t endOffset = (text.sizeInBytes() + 3) & ~3u; // the new string must be word-aligned or many Windows
                                                                 // functions will fail to read it correctly!
         source.preallocateBytes (endOffset + extraBytesNeeded);
         text = source.getCharPointer();
         void* const newSpace = addBytesToPointer (text.getAddress(), (int) endOffset);
         const CharPointerType_Dest extraSpace (static_cast <DestChar*> (newSpace));
        #if BEAST_DEBUG // (This just avoids spurious warnings from valgrind about the uninitialised bytes at the end of the buffer..)
         const size_t bytesToClear = (size_t) bmin ((int) extraBytesNeeded, 4);
         zeromem (addBytesToPointer (newSpace, extraBytesNeeded - bytesToClear), bytesToClear);
        #endif
         CharPointerType_Dest (extraSpace).writeAll (text);
         return extraSpace;
     }
The documentation for this struct was generated from the following file:
rippled/src/beast/beast/strings/impl/String.cpp