rippled: ripple::HashMaps Class Reference
ripple::HashMaps Class Reference
#include <HashMaps.h>
Classes
class NonceHolder
Public Member Functions
template<class T >
void initializeNonce () const
template<class T >
T getNonce () const
Static Public Member Functions
static HashMaps const & getInstance ()
Static Public Attributes
static std::size_t const goldenRatio = 0x9e3779b9
Private Member Functions
HashMaps ()
~HashMaps ()
template<class T >
NonceHolder< T > const & getNonceHolder () const
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
Management helper of hash functions used in hash map containers.
The nonce is used to prevent attackers from feeding carefully crafted inputs in order to cause denegerate hash map data structures. This is done by seeding the hashing function with a random number generated at program startup.
Definition at line 32 of file HashMaps.h.
Constructor & Destructor Documentation
ripple::HashMaps::HashMaps () inline private
Definition at line 92 of file HashMaps.h.
     {
     }
ripple::HashMaps::~HashMaps () inline private
Definition at line 96 of file HashMaps.h.
     {
     }
Member Function Documentation
static HashMaps const& ripple::HashMaps::getInstance (void) inline static
Retrieve the singleton.
Returns
The global instance of the singleton.
Definition at line 61 of file HashMaps.h.
References instance.
Referenced by ripple::ApplicationImp::ApplicationImp(), ripple::hash_value(), and ripple::SHAMapNode::setMHash().
     {
         static HashMaps instance;
         return instance;
     }
template<class T > T ripple::HashMaps::getNonce () const inline
Get the nonce for a type.
The nonces are generated when they are first used. This code is thread safe.
Definition at line 86 of file HashMaps.h.
Referenced by ripple::hash_value(), and ripple::SHAMapNode::setMHash().
     {
         return getNonceHolder <T> ().getNonce ();
     }
template<class T > NonceHolder<T> const& ripple::HashMaps::getNonceHolder () const inline private
Retrieve the nonce holder for a type.
Note
This routine will be called concurrently.
Definition at line 126 of file HashMaps.h.
     {
         static NonceHolder <T> nonceHolder;
         return nonceHolder;
     }
template<class T > void ripple::HashMaps::initializeNonce () const inline
Instantiate a nonce for a type.
Note
This may be used during program initialization to avoid concurrency issues. Only C++11 provides thread safety guarantees for function-local static objects.
Definition at line 75 of file HashMaps.h.
Referenced by ripple::ApplicationImp::ApplicationImp().
     {
         getNonceHolder <T> ();
     }
Member Data Documentation
std::size_t const ripple::HashMaps::goldenRatio = 0x9e3779b9 static
Golden ratio constant used in hashing functions.
The magic number is supposed to be 32 random bits, where each is equally likely to be 0 or 1, and with no simple correlation between the bits. A common way to find a string of such bits is to use the binary expansion of an irrational number; in this case, that number is the reciprocal of the golden ratio:
phi = (1 + sqrt(5)) / 2
2^32 / phi = 0x9e3779b9
References:
http://stackoverflow.com/questions/4948780/magic-number-in-boosthash-combine
http://burtleburtle.net/bob/hash/doobs.html
Definition at line 55 of file HashMaps.h.
Referenced by ripple::hash_value(), and ripple::SHAMapNode::setMHash().
The documentation for this class was generated from the following file:
rippled/src/ripple/types/api/HashMaps.h