rippled: ripple::TransactionEngine Class Reference
ripple::TransactionEngine Class Reference
#include <TransactionEngine.h>
Public Types
typedef boost::shared_ptr
< TransactionEngine > pointer
Public Member Functions
TransactionEngine ()
TransactionEngine (Ledger::ref ledger)
LedgerEntrySet & view ()
Ledger::ref getLedger ()
void setLedger (Ledger::ref ledger)
SLE::pointer entryCreate (LedgerEntryType type, uint256 const &index)
SLE::pointer entryCache (LedgerEntryType type, uint256 const &index)
void entryDelete (SLE::ref sleEntry)
void entryModify (SLE::ref sleEntry)
TER applyTransaction (const SerializedTransaction &, TransactionEngineParams, bool &didApply)
bool checkInvariants (TER result, const SerializedTransaction &txn, TransactionEngineParams params)
Public Member Functions inherited from ripple::CountedObject< TransactionEngine >
CountedObject ()
CountedObject (CountedObject const &)
~CountedObject ()
Static Public Member Functions
static char const * getCountedObjectName ()
Protected Member Functions
void txnWrite ()
Protected Attributes
Ledger::pointer mLedger
int mTxnSeq
uint160 mTxnAccountID
SLE::pointer mTxnAccount
Private Member Functions
TER setAuthorized (const SerializedTransaction &txn, bool bMustSetGenerator)
TER checkSig (const SerializedTransaction &txn)
TER takeOffers (bool bPassive, uint256 const &uBookBase, const uint160 &uTakerAccountID, SLE::ref sleTakerAccount, const STAmount &saTakerPays, const STAmount &saTakerGets, STAmount &saTakerPaid, STAmount &saTakerGot)
Private Attributes
LedgerEntrySet mNodes
Detailed Description
Definition at line 30 of file TransactionEngine.h.
Member Typedef Documentation
typedef boost::shared_ptr<TransactionEngine> ripple::TransactionEngine::pointer
Definition at line 62 of file TransactionEngine.h.
Constructor & Destructor Documentation
ripple::TransactionEngine::TransactionEngine () inline
Definition at line 64 of file TransactionEngine.h.
                          : mTxnSeq (0)
     {
         ;
     }
ripple::TransactionEngine::TransactionEngine (Ledger::ref ledger) inline
Definition at line 68 of file TransactionEngine.h.
References mLedger.
                                          : mLedger (ledger), mTxnSeq (0)
     {
         assert (mLedger);
     }
Member Function Documentation
TER ripple::TransactionEngine::applyTransaction (const SerializedTransaction & txn, TransactionEngineParams params, bool & didApply)
Definition at line 75 of file TransactionEngine.cpp.
References ripple::STObject::add(), balance(), ripple::LedgerEntrySet::calcRawMeta(), checkInvariants(), ripple::LedgerEntrySet::clear(), entryCache(), entryModify(), ripple::Ledger::getAccountRootIndex(), ripple::SerializedTransaction::getJson(), ripple::LedgerEntrySet::getJson(), ripple::STAmount::getNValue(), ripple::SerializedTransaction::getSequence(), ripple::SerializedTransaction::getSourceAccount(), ripple::SerializedTransaction::getTransactionFee(), ripple::SerializedTransaction::getTransactionID(), ripple::LedgerEntrySet::init(), ripple::is_bit_set(), ripple::STObject::isEquivalent(), isTecClaim, isTemMalformed, isTesSuccess, ripple::lsDEBUG, ripple::lsFATAL, ripple::lsINFO, ripple::lsTRACE, ripple::lsWARNING, ripple::ltACCOUNT_ROOT, ripple::Transactor::makeTransactor(), mLedger, mNodes, mTxnAccount, mTxnSeq, ripple::tapOPEN_LEDGER, ripple::tapRETRY, ripple::tefINTERNAL, ripple::tefPAST_SEQ, ripple::temINVALID, ripple::temUNKNOWN, ripple::terINSUF_FEE_B, ripple::terNO_ACCOUNT, ripple::terPRE_SEQ, ripple::transHuman(), ripple::transResultInfo(), ripple::transToken(), txnWrite(), and WriteLog.
Referenced by ripple::LocalTxsImp::apply(), ripple::LedgerConsensusImp::applyTransaction(), ripple::LedgerMasterImp::closeLedger(), and ripple::LedgerMasterImp::doTransaction().
 {
     WriteLog (lsTRACE, TransactionEngine) << "applyTransaction>";
     didApply = false;
     assert (mLedger);
     mNodes.init (mLedger, txn.getTransactionID (), mLedger->getLedgerSeq (), params);
 #ifdef BEAST_DEBUG
     if (1)
     {
         Serializer ser;
         txn.add (ser);
         SerializerIterator sit (ser);
         SerializedTransaction s2 (sit);
         if (!s2.isEquivalent (txn))
         {
             WriteLog (lsFATAL, TransactionEngine) << "Transaction serdes mismatch";
             Json::StyledStreamWriter ssw;
             WriteLog (lsINFO, TransactionEngine) << txn.getJson (0);
             WriteLog (lsFATAL, TransactionEngine) << s2.getJson (0);
             assert (false);
         }
     }
 #endif
     uint256 txID = txn.getTransactionID ();
     if (!txID)
     {
         WriteLog (lsWARNING, TransactionEngine) << "applyTransaction: invalid transaction id";
         return temINVALID;
     }
     std::unique_ptr<Transactor> transactor = Transactor::makeTransactor (txn, params, this);
     if (transactor.get () == nullptr)
     {
         WriteLog (lsWARNING, TransactionEngine) << "applyTransaction: Invalid transaction: unknown transaction type";
         return temUNKNOWN;
     }
     TER terResult = transactor->apply ();
     std::string strToken;
     std::string strHuman;
     transResultInfo (terResult, strToken, strHuman);
     WriteLog (lsINFO, TransactionEngine) << "applyTransaction: terResult=" << strToken << " : " << terResult << " : " << strHuman;
     if (isTesSuccess (terResult))
         didApply = true;
     else if (isTecClaim (terResult) && !is_bit_set (params, tapRETRY))
     {
         // only claim the transaction fee
         WriteLog (lsDEBUG, TransactionEngine) << "Reprocessing to only claim fee";
         mNodes.clear ();
         SLE::pointer txnAcct = entryCache (ltACCOUNT_ROOT, Ledger::getAccountRootIndex (txn.getSourceAccount ()));
         if (!txnAcct)
             terResult = terNO_ACCOUNT;
         else
         {
             std::uint32_t t_seq = txn.getSequence ();
             std::uint32_t a_seq = txnAcct->getFieldU32 (sfSequence);
             if (a_seq < t_seq)
                 terResult = terPRE_SEQ;
             else if (a_seq > t_seq)
                 terResult = tefPAST_SEQ;
             else
             {
                 STAmount fee        = txn.getTransactionFee ();
                 STAmount balance    = txnAcct->getFieldAmount (sfBalance);
                 if (balance < fee)
                     terResult = terINSUF_FEE_B;
                 else
                 {
                     txnAcct->setFieldAmount (sfBalance, balance - fee);
                     txnAcct->setFieldU32 (sfSequence, t_seq + 1);
                     entryModify (txnAcct);
                     didApply = true;
                 }
             }
         }
     }
     else
         WriteLog (lsDEBUG, TransactionEngine) << "Not applying transaction " << txID;
     if (didApply)
     {
         if (!checkInvariants (terResult, txn, params))
         {
             WriteLog (lsFATAL, TransactionEngine) << "Transaction violates invariants";
             WriteLog (lsFATAL, TransactionEngine) << txn.getJson (0);
             WriteLog (lsFATAL, TransactionEngine) << transToken (terResult) << ": " << transHuman (terResult);
             WriteLog (lsFATAL, TransactionEngine) << mNodes.getJson (0);
             didApply = false;
             terResult = tefINTERNAL;
         }
         else
         {
             // Transaction succeeded fully or (retries are not allowed and the transaction could claim a fee)
             Serializer m;
             mNodes.calcRawMeta (m, terResult, mTxnSeq++);
             txnWrite ();
             Serializer s;
             txn.add (s);
             if (is_bit_set (params, tapOPEN_LEDGER))
             {
                 if (!mLedger->addTransaction (txID, s))
                 {
                     WriteLog (lsFATAL, TransactionEngine) << "Tried to add transaction to open ledger that already had it";
                     assert (false);
                     throw std::runtime_error ("Duplicate transaction applied");
                 }
             }
             else
             {
                 if (!mLedger->addTransaction (txID, s, m))
                 {
                     WriteLog (lsFATAL, TransactionEngine) << "Tried to add transaction to ledger that already had it";
                     assert (false);
                     throw std::runtime_error ("Duplicate transaction applied to closed ledger");
                 }
                 // Charge whatever fee they specified.
                 STAmount saPaid = txn.getTransactionFee ();
                 mLedger->destroyCoins (saPaid.getNValue ());
             }
         }
     }
     mTxnAccount.reset ();
     mNodes.clear ();
     if (!is_bit_set (params, tapOPEN_LEDGER) && isTemMalformed (terResult))
     {
         // XXX Malformed or failed transaction in closed ledger must bow out.
     }
     return terResult;
 }
bool ripple::TransactionEngine::checkInvariants (TER result, const SerializedTransaction & txn, TransactionEngineParams params)
Definition at line 26 of file TransactionCheck.cpp.
Referenced by applyTransaction().
 {
     // VFALCO I deleted a bunch of code that was wrapped in #if 0.
     //        If you need it, check the commit log.
     return true;
 }
TER ripple::TransactionEngine::checkSig (const SerializedTransaction & txn) private
SLE::pointer ripple::TransactionEngine::entryCache (LedgerEntryType type, uint256 const & index) inline
Definition at line 93 of file TransactionEngine.h.
References ripple::LedgerEntrySet::entryCache(), and mNodes.
Referenced by ripple::Transactor::apply(), ripple::ChangeTransactor::applyFeature(), ripple::ChangeTransactor::applyFee(), applyTransaction(), ripple::TrustSetTransactor::doApply(), ripple::WalletAddTransactor::doApply(), ripple::OfferCancelTransactor::doApply(), ripple::PaymentTransactor::doApply(), and ripple::OfferCreateTransactor::doApply().
     {
         return mNodes.entryCache (type, index);
     }
SLE::pointer ripple::TransactionEngine::entryCreate (LedgerEntryType type, uint256 const & index) inline
Definition at line 88 of file TransactionEngine.h.
References ripple::LedgerEntrySet::entryCreate(), and mNodes.
Referenced by ripple::ChangeTransactor::applyFeature(), ripple::ChangeTransactor::applyFee(), ripple::WalletAddTransactor::doApply(), ripple::PaymentTransactor::doApply(), and ripple::OfferCreateTransactor::doApply().
     {
         return mNodes.entryCreate (type, index);
     }
void ripple::TransactionEngine::entryDelete (SLE::ref sleEntry) inline
Definition at line 98 of file TransactionEngine.h.
References ripple::LedgerEntrySet::entryDelete(), and mNodes.
     {
         mNodes.entryDelete (sleEntry);
     }
void ripple::TransactionEngine::entryModify (SLE::ref sleEntry) inline
Definition at line 103 of file TransactionEngine.h.
References ripple::LedgerEntrySet::entryModify(), and mNodes.
Referenced by ripple::Transactor::apply(), ripple::ChangeTransactor::applyFeature(), ripple::ChangeTransactor::applyFee(), applyTransaction(), ripple::TrustSetTransactor::doApply(), ripple::PaymentTransactor::doApply(), and ripple::OfferCreateTransactor::takeOffers().
     {
         mNodes.entryModify (sleEntry);
     }
static char const* ripple::TransactionEngine::getCountedObjectName () inline static
Definition at line 34 of file TransactionEngine.h.
 { return "TransactionEngine"; }
Ledger::ref ripple::TransactionEngine::getLedger () inline
Definition at line 77 of file TransactionEngine.h.
References mLedger.
Referenced by ripple::Transactor::apply(), ripple::Transactor::calculateFee(), ripple::Transactor::checkSeq(), ripple::TrustSetTransactor::doApply(), ripple::WalletAddTransactor::doApply(), ripple::PaymentTransactor::doApply(), ripple::OfferCreateTransactor::doApply(), ripple::LedgerMasterImp::doTransaction(), and ripple::OfferCreateTransactor::isValidOffer().
     {
         return mLedger;
     }
TER ripple::TransactionEngine::setAuthorized (const SerializedTransaction & txn, bool bMustSetGenerator) private
void ripple::TransactionEngine::setLedger (Ledger::ref ledger) inline
Definition at line 81 of file TransactionEngine.h.
References mLedger.
Referenced by ripple::LedgerMasterImp::closeLedger(), ripple::LedgerMasterImp::pushLedger(), and ripple::LedgerMasterImp::switchLedgers().
     {
         assert (ledger);
         mLedger = ledger;
     }
TER ripple::TransactionEngine::takeOffers (bool bPassive, uint256 const & uBookBase, const uint160 & uTakerAccountID, SLE::ref sleTakerAccount, const STAmount & saTakerPays, const STAmount & saTakerGets, STAmount & saTakerPaid, STAmount & saTakerGot) private
void ripple::TransactionEngine::txnWrite () protected
Definition at line 28 of file TransactionEngine.cpp.
References ripple::lepCREATE, ripple::lepERROR, ripple::lepNONE, ripple::lsINFO, ripple::taaCACHED, ripple::taaCREATE, ripple::taaDELETE, ripple::taaMODIFY, ripple::taaNONE, and WriteLog.
Referenced by applyTransaction().
 {
     // Write back the account states
     typedef std::map<uint256, LedgerEntrySetEntry>::value_type u256_LES_pair;
     BOOST_FOREACH (u256_LES_pair & it, mNodes)
     {
         SLE::ref    sleEntry    = it.second.mEntry;
         switch (it.second.mAction)
         {
         case taaNONE:
             assert (false);
             break;
         case taaCACHED:
             break;
         case taaCREATE:
         {
             WriteLog (lsINFO, TransactionEngine) << "applyTransaction: taaCREATE: " << sleEntry->getText ();
             if (mLedger->writeBack (lepCREATE, sleEntry) & lepERROR)
                 assert (false);
         }
         break;
         case taaMODIFY:
         {
             WriteLog (lsINFO, TransactionEngine) << "applyTransaction: taaMODIFY: " << sleEntry->getText ();
             if (mLedger->writeBack (lepNONE, sleEntry) & lepERROR)
                 assert (false);
         }
         break;
         case taaDELETE:
         {
             WriteLog (lsINFO, TransactionEngine) << "applyTransaction: taaDELETE: " << sleEntry->getText ();
             if (!mLedger->peekAccountStateMap ()->delItem (it.first))
                 assert (false);
         }
         break;
         }
     }
 }
LedgerEntrySet& ripple::TransactionEngine::view () inline
Definition at line 73 of file TransactionEngine.h.
References mNodes.
Referenced by ripple::TrustSetTransactor::doApply(), ripple::OfferCancelTransactor::doApply(), ripple::AccountSetTransactor::doApply(), ripple::PaymentTransactor::doApply(), ripple::OfferCreateTransactor::doApply(), ripple::OfferCreateTransactor::isValidOffer(), and ripple::OfferCreateTransactor::takeOffers().
     {
         return mNodes;
     }
Member Data Documentation
Ledger::pointer ripple::TransactionEngine::mLedger protected
Definition at line 53 of file TransactionEngine.h.
Referenced by applyTransaction(), getLedger(), setLedger(), and TransactionEngine().
LedgerEntrySet ripple::TransactionEngine::mNodes private
Definition at line 37 of file TransactionEngine.h.
Referenced by applyTransaction(), entryCache(), entryCreate(), entryDelete(), entryModify(), and view().
SLE::pointer ripple::TransactionEngine::mTxnAccount protected
Definition at line 57 of file TransactionEngine.h.
Referenced by applyTransaction().
uint160 ripple::TransactionEngine::mTxnAccountID protected
Definition at line 56 of file TransactionEngine.h.
int ripple::TransactionEngine::mTxnSeq protected
Definition at line 54 of file TransactionEngine.h.
Referenced by applyTransaction().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/tx/TransactionEngine.h
rippled/src/ripple_app/tx/TransactionCheck.cpp
rippled/src/ripple_app/tx/TransactionEngine.cpp