rippled: rocksdb::RandomAccessFile Class Reference
rocksdb::RandomAccessFile Class Reference abstract
#include <env.h>
Public Types
enum AccessPattern {
NORMAL, RANDOM, SEQUENTIAL, WILLNEED,
DONTNEED
}
Public Member Functions
RandomAccessFile ()
virtual ~RandomAccessFile ()
virtual Status Read (uint64_t offset, size_t n, Slice *result, char *scratch) const =0
virtual size_t GetUniqueId (char *id, size_t max_size) const
virtual void Hint (AccessPattern pattern)
virtual Status InvalidateCache (size_t offset, size_t length)
Detailed Description
Definition at line 282 of file env.h.
Member Enumeration Documentation
enum rocksdb::RandomAccessFile::AccessPattern
Enumerator
NORMAL
RANDOM
SEQUENTIAL
WILLNEED
DONTNEED
Definition at line 320 of file env.h.
 { NORMAL, RANDOM, SEQUENTIAL, WILLNEED, DONTNEED };
Constructor & Destructor Documentation
rocksdb::RandomAccessFile::RandomAccessFile () inline
Definition at line 284 of file env.h.
 { }
rocksdb::RandomAccessFile::~RandomAccessFile () virtual
Definition at line 21 of file env.cc.
{
 }
Member Function Documentation
virtual size_t rocksdb::RandomAccessFile::GetUniqueId (char * id, size_t max_size) const inline virtual
Reimplemented in rocksdb::StringSource.
Definition at line 314 of file env.h.
Referenced by rocksdb::BlockBasedTable::GenerateCachePrefix().
{
     return 0; // Default implementation to prevent issues with backwards
               // compatibility.
   };
virtual void rocksdb::RandomAccessFile::Hint (AccessPattern pattern) inline virtual
Definition at line 322 of file env.h.
 {}
virtual Status rocksdb::RandomAccessFile::InvalidateCache (size_t offset, size_t length) inline virtual
Definition at line 327 of file env.h.
References rocksdb::Status::NotSupported().
{
     return Status::NotSupported("InvalidateCache not supported.");
   }
virtual Status rocksdb::RandomAccessFile::Read (uint64_t offset, size_t n, Slice * result, char * scratch) const pure virtual
Implemented in rocksdb::StringSource, and rocksdb::FakeRandomeAccessFile.
Referenced by rocksdb::BlockBasedTable::Open(), rocksdb::ReadBlockContents(), and rocksdb::TEST().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/include/rocksdb/env.h
rippled/src/ripple/rocksdb/rocksdb/util/env.cc