rippled: beast::BinaryEncoding Class Reference
beast::BinaryEncoding Class Reference
Static Public Member Functions
template<typename Conversion , std::size_t Bytes>
static std::string encode (UnsignedInteger< Bytes > v, Conversion c=Conversion())
template<typename Conversion , std::size_t Bytes>
static bool decode (UnsignedInteger< Bytes > &rv, std::string const &s, Conversion c=Conversion())
Detailed Description
Generic algorithms for base encoding and decoding.
Definition at line 33 of file BinaryEncoding.cpp.
Member Function Documentation
template<typename Conversion , std::size_t Bytes> static bool beast::BinaryEncoding::decode (UnsignedInteger< Bytes > & rv, std::string const & s, Conversion c = Conversion ()) inline static
Decode the string into an unsigned integer. The size must match exactly
Returns
true on success.
Definition at line 74 of file BinaryEncoding.cpp.
References beast::UnsignedInteger< Bytes >::toCalcType().
Referenced by beast::BinaryEncoding_test::testBase64Bytes(), and beast::BinaryEncoding_test::testEncode().
     {
         typename UnsignedInteger <Bytes>::CalcType bi (rv.toCalcType (false));
         std::size_t const radix (Conversion::radix);
         bi.clear ();
         for (std::string::const_iterator iter (s.begin()); iter != s.end(); ++iter)
         {
             int const v (c.invert (*iter));
             if (v == -1)
                 return false;
             bi *= radix;
             bi += v;
         }
         bi.toCanonical();
         return true;
     }
template<typename Conversion , std::size_t Bytes> static std::string beast::BinaryEncoding::encode (UnsignedInteger< Bytes > v, Conversion c = Conversion ()) inline static
Concept: Conversion
X denotes a Conversion class, a is a value of type X, i is an integral type.
Requirements:
Expression      Type            Notes/Contracts
-------------   -----------     ------------------
X a;
X::radix        size_type       constexpr
a.map (i)       char            maps base numeral to a char
Encode the unsigned integer into a string using the specified conversion.
Definition at line 52 of file BinaryEncoding.cpp.
References beast::UnsignedInteger< Bytes >::toCalcType().
Referenced by beast::BinaryEncoding_test::testBase16(), beast::BinaryEncoding_test::testBase64Bytes(), and beast::BinaryEncoding_test::testEncode().
     {
         // bi is destroyed in this process
         typename UnsignedInteger <Bytes>::CalcType bi (v.toCalcType ());
         std::size_t const radix (Conversion::radix);
         std::string s;
         s.reserve (bi.size() * 3); // guess
         while (bi.isNotZero ())
         {
             std::size_t const m (bi % radix);
             bi /= radix;
             s.push_back (c.map (m));
         }
         std::reverse (s.begin(), s.end());
         return s;
     }
The documentation for this class was generated from the following file:
rippled/src/beast/beast/crypto/tests/BinaryEncoding.cpp