rippled: beast::detail::LeakChecked< Object > Class Template Reference
beast::detail::LeakChecked< Object > Class Template Reference
#include <LeakChecked.h>
Classes
class LeakCounter
Protected Member Functions
LeakChecked () noexcept
LeakChecked (LeakChecked const &) noexcept
~LeakChecked ()
Static Private Member Functions
static const char * getLeakCheckedName ()
static LeakCounter & getCounter () noexcept
Static Private Member Functions inherited from beast::detail::LeakCheckedBase
static void checkForLeaks ()
static void reportDanglingPointer (char const *objectName)
Detailed Description
template<class Object>
class beast::detail::LeakChecked< Object >
Detects leaks at program exit.
To use this, derive your class from this template using CRTP (curiously recurring template pattern).
Definition at line 80 of file LeakChecked.h.
Constructor & Destructor Documentation
template<class Object > beast::detail::LeakChecked< Object >::LeakChecked () inline protected noexcept
Definition at line 83 of file LeakChecked.h.
References beast::detail::LeakChecked< Object >::getCounter(), and beast::detail::LeakCheckedBase::LeakCounterBase::increment().
     {
         getCounter ().increment ();
     }
template<class Object > beast::detail::LeakChecked< Object >::LeakChecked (LeakChecked< Object > const &) inline protected noexcept
Definition at line 88 of file LeakChecked.h.
References beast::detail::LeakChecked< Object >::getCounter(), and beast::detail::LeakCheckedBase::LeakCounterBase::increment().
     {
         getCounter ().increment ();
     }
template<class Object > beast::detail::LeakChecked< Object >::~LeakChecked () inline protected
Definition at line 93 of file LeakChecked.h.
References beast::detail::LeakChecked< Object >::getCounter(), beast::detail::LeakChecked< Object >::getLeakCheckedName(), and beast::detail::LeakCheckedBase::reportDanglingPointer().
     {
         if (getCounter ().decrement () < 0)
         {
             reportDanglingPointer (getLeakCheckedName ());
         }
     }
Member Function Documentation
template<class Object > static LeakCounter& beast::detail::LeakChecked< Object >::getCounter () inline static private noexcept
Definition at line 132 of file LeakChecked.h.
Referenced by beast::detail::LeakChecked< Object >::LeakChecked(), and beast::detail::LeakChecked< Object >::~LeakChecked().
     {
         return StaticObject <LeakCounter>::get();
     }
template<class Object > static const char* beast::detail::LeakChecked< Object >::getLeakCheckedName () inline static private
Definition at line 125 of file LeakChecked.h.
References name.
Referenced by beast::detail::LeakChecked< Object >::LeakCounter::getClassName(), and beast::detail::LeakChecked< Object >::~LeakChecked().
     {
         return typeid (Object).name ();
     }
The documentation for this class was generated from the following file:
rippled/src/beast/beast/utility/LeakChecked.h