rippled: rocksdb::Env Class Reference
rocksdb::Env Class Reference abstract
#include <env.h>
Public Types
enum Priority { LOW, HIGH, TOTAL }
Public Member Functions
Env ()
virtual ~Env ()
virtual Status NewSequentialFile (const std::string &fname, unique_ptr< SequentialFile > *result, const EnvOptions &options)=0
virtual Status NewRandomAccessFile (const std::string &fname, unique_ptr< RandomAccessFile > *result, const EnvOptions &options)=0
virtual Status NewWritableFile (const std::string &fname, unique_ptr< WritableFile > *result, const EnvOptions &options)=0
virtual Status NewRandomRWFile (const std::string &fname, unique_ptr< RandomRWFile > *result, const EnvOptions &options)=0
virtual bool FileExists (const std::string &fname)=0
virtual Status GetChildren (const std::string &dir, std::vector< std::string > *result)=0
virtual Status DeleteFile (const std::string &fname)=0
virtual Status CreateDir (const std::string &dirname)=0
virtual Status CreateDirIfMissing (const std::string &dirname)=0
virtual Status DeleteDir (const std::string &dirname)=0
virtual Status GetFileSize (const std::string &fname, uint64_t *file_size)=0
virtual Status GetFileModificationTime (const std::string &fname, uint64_t *file_mtime)=0
virtual Status RenameFile (const std::string &src, const std::string &target)=0
virtual Status LockFile (const std::string &fname, FileLock **lock)=0
virtual Status UnlockFile (FileLock *lock)=0
virtual void Schedule (void(*function)(void *arg), void *arg, Priority pri=LOW)=0
virtual void StartThread (void(*function)(void *arg), void *arg)=0
virtual Status GetTestDirectory (std::string *path)=0
virtual Status NewLogger (const std::string &fname, shared_ptr< Logger > *result)=0
virtual uint64_t NowMicros ()=0
virtual uint64_t NowNanos ()
virtual void SleepForMicroseconds (int micros)=0
virtual Status GetHostName (char *name, uint64_t len)=0
virtual Status GetCurrentTime (int64_t *unix_time)=0
virtual Status GetAbsolutePath (const std::string &db_path, std::string *output_path)=0
virtual void SetBackgroundThreads (int number, Priority pri=LOW)=0
virtual std::string TimeToString (uint64_t time)=0
virtual std::string GenerateUniqueId ()
Static Public Member Functions
static Env * Default ()
Private Member Functions
Env (const Env &)
void operator= (const Env &)
Detailed Description
Definition at line 70 of file env.h.
Member Enumeration Documentation
enum rocksdb::Env::Priority
Enumerator
LOW
HIGH
TOTAL
Definition at line 178 of file env.h.
 { LOW, HIGH, TOTAL };
Constructor & Destructor Documentation
rocksdb::Env::Env () inline
Definition at line 72 of file env.h.
 { }
rocksdb::Env::~Env () virtual
Definition at line 15 of file env.cc.
           {
 }
rocksdb::Env::Env (const Env &) private
Member Function Documentation
virtual Status rocksdb::Env::CreateDir (const std::string & dirname) pure virtual
Implemented in rocksdb::EnvWrapper, and rocksdb::HdfsEnv.
Referenced by rocksdb::EnvWrapper::CreateDir(), rocksdb::CreateLoggerFromOptions(), and rocksdb::TEST().
virtual Status rocksdb::Env::CreateDirIfMissing (const std::string & dirname) pure virtual
Implemented in rocksdb::EnvWrapper, and rocksdb::HdfsEnv.
Referenced by rocksdb::BlobStore::BlobStore(), rocksdb::DBImpl::CreateArchivalDirectory(), rocksdb::EnvWrapper::CreateDirIfMissing(), rocksdb::DB::Open(), and rocksdb::DBImpl::Recover().
Env * rocksdb::Env::Default () static
Definition at line 1506 of file env_posix.cc.
Referenced by rocksdb::BM_LogAndApply(), rocksdb::CorruptionTest::Corrupt(), rocksdb::DeleteFileTest::DeleteFileTest(), rocksdb::WALDumperCommand::DoCommand(), rocksdb::DBWithTTL::GetCurrentTime(), main(), rocksdb::RunConcurrent(), rocksdb::TableReaderBenchmark(), rocksdb::TEST(), and rocksdb::test::TmpDir().
                   {
   static PosixEnv default_env;
   return &default_env;
 }
virtual Status rocksdb::Env::DeleteDir (const std::string & dirname) pure virtual
Implemented in rocksdb::EnvWrapper, and rocksdb::HdfsEnv.
Referenced by rocksdb::EnvWrapper::DeleteDir(), rocksdb::DestroyDB(), and rocksdb::TEST().
virtual Status rocksdb::Env::DeleteFile (const std::string & fname) pure virtual
Implemented in rocksdb::EnvWrapper, and rocksdb::HdfsEnv.
Referenced by rocksdb::Benchmark::Benchmark(), rocksdb::BuildTable(), rocksdb::DBImpl::DeleteFile(), rocksdb::EnvWrapper::DeleteFile(), rocksdb::DeleteFileTest::DeleteFileTest(), rocksdb::DestroyDB(), rocksdb::DoWriteStringToFile(), rocksdb::Benchmark::HeapProfile(), rocksdb::VersionSet::LogAndApply(), rocksdb::DBImpl::NewDB(), rocksdb::DBImpl::PurgeObsoleteFiles(), rocksdb::DBImpl::PurgeObsoleteWALFiles(), rocksdb::SetCurrentFile(), rocksdb::SetIdentityFile(), rocksdb::StressTest::StressTest(), rocksdb::TableReaderBenchmark(), and rocksdb::TEST().
virtual bool rocksdb::Env::FileExists (const std::string & fname) pure virtual
Implemented in rocksdb::EnvWrapper, and rocksdb::HdfsEnv.
Referenced by rocksdb::EnvWrapper::FileExists(), rocksdb::DBImpl::GetSortedWalFiles(), rocksdb::DBImpl::Recover(), and rocksdb::TEST().
std::string rocksdb::Env::GenerateUniqueId () virtual
Definition at line 1483 of file env_posix.cc.
References ripple::max(), rocksdb::Status::ok(), rocksdb::ReadFileToString(), and rocksdb::Random64::Uniform().
Referenced by rocksdb::SetIdentityFile().
{
   std::string uuid_file = "/proc/sys/kernel/random/uuid";
   if (FileExists(uuid_file)) {
     std::string uuid;
     Status s = ReadFileToString(this, uuid_file, &uuid);
     if (s.ok()) {
       return uuid;
     }
   }
   // Could not read uuid_file - generate uuid using "nanos-random"
   Random64 r(time(nullptr));
   uint64_t random_uuid_portion =
     r.Uniform(std::numeric_limits<uint64_t>::max());
   uint64_t nanos_uuid_portion = NowNanos();
   char uuid2[200];
   snprintf(uuid2,
            200,
            "%lx-%lx",
            (unsigned long)nanos_uuid_portion,
            (unsigned long)random_uuid_portion);
   return uuid2;
 }
virtual Status rocksdb::Env::GetAbsolutePath (const std::string & db_path, std::string * output_path) pure virtual
Implemented in rocksdb::EnvWrapper, and rocksdb::HdfsEnv.
Referenced by rocksdb::AutoRollLogger::AutoRollLogger(), rocksdb::CreateLoggerFromOptions(), rocksdb::DBImpl::DBImpl(), and rocksdb::EnvWrapper::GetAbsolutePath().
virtual Status rocksdb::Env::GetChildren (const std::string & dir, std::vector< std::string > * result) pure virtual
Implemented in rocksdb::EnvWrapper, and rocksdb::HdfsEnv.
Referenced by rocksdb::DBImpl::AppendSortedWalsOfType(), rocksdb::Benchmark::Benchmark(), rocksdb::DeleteFileTest::CheckFileTypeCounts(), rocksdb::DeleteFileTest::DeleteFileTest(), rocksdb::DestroyDB(), rocksdb::DBImpl::FindObsoleteFiles(), rocksdb::EnvWrapper::GetChildren(), rocksdb::ListLogFiles(), main(), rocksdb::DBImpl::PurgeObsoleteWALFiles(), rocksdb::DBImpl::Recover(), rocksdb::StressTest::StressTest(), and rocksdb::TEST().
virtual Status rocksdb::Env::GetCurrentTime (int64_t * unix_time) pure virtual
Implemented in rocksdb::EnvWrapper, and rocksdb::HdfsEnv.
Referenced by rocksdb::DBWithTTL::GetCurrentTime(), rocksdb::EnvWrapper::GetCurrentTime(), rocksdb::DBImpl::LogDBDeployStats(), rocksdb::DBImpl::MaybeScheduleLogDBDeployStats(), and rocksdb::DBImpl::PurgeObsoleteWALFiles().
virtual Status rocksdb::Env::GetFileModificationTime (const std::string & fname, uint64_t * file_mtime) pure virtual
Implemented in rocksdb::EnvWrapper, and rocksdb::HdfsEnv.
Referenced by rocksdb::EnvWrapper::GetFileModificationTime(), and rocksdb::DBImpl::PurgeObsoleteWALFiles().
virtual Status rocksdb::Env::GetFileSize (const std::string & fname, uint64_t * file_size) pure virtual
Implemented in rocksdb::EnvWrapper, and rocksdb::HdfsEnv.
Referenced by rocksdb::DBImpl::AppendSortedWalsOfType(), rocksdb::DBImpl::CheckWalFileExistsAndEmpty(), rocksdb::EnvWrapper::GetFileSize(), rocksdb::DBImpl::PurgeObsoleteWALFiles(), rocksdb::SstFileReader::ReadSequential(), rocksdb::VersionSet::Recover(), rocksdb::TableReaderBenchmark(), and rocksdb::TEST().
virtual Status rocksdb::Env::GetHostName (char * name, uint64_t len) pure virtual
Implemented in rocksdb::EnvWrapper, and rocksdb::HdfsEnv.
Referenced by rocksdb::DBImpl::DBImpl(), and rocksdb::EnvWrapper::GetHostName().
virtual Status rocksdb::Env::GetTestDirectory (std::string * path) pure virtual
Implemented in rocksdb::EnvWrapper, and rocksdb::HdfsEnv.
Referenced by rocksdb::EnvWrapper::GetTestDirectory(), main(), SetupBenchmarkBalanced(), SetupBenchmarkReadHeavy(), SetupBenchmarkWriteHeavy(), rocksdb::TEST(), and rocksdb::test::TmpDir().
virtual Status rocksdb::Env::LockFile (const std::string & fname, FileLock ** lock) pure virtual
Implemented in rocksdb::EnvWrapper, and rocksdb::HdfsEnv.
Referenced by rocksdb::DestroyDB(), rocksdb::LockTest::LockFile(), rocksdb::EnvWrapper::LockFile(), rocksdb::DBImpl::Recover(), and rocksdb::TEST().
virtual Status rocksdb::Env::NewLogger (const std::string & fname, shared_ptr< Logger > * result) pure virtual
Implemented in rocksdb::EnvWrapper, and rocksdb::HdfsEnv.
Referenced by rocksdb::CreateLoggerFromOptions(), and rocksdb::EnvWrapper::NewLogger().
virtual Status rocksdb::Env::NewRandomAccessFile (const std::string & fname, unique_ptr< RandomAccessFile > * result, const EnvOptions & options) pure virtual
Implemented in rocksdb::EnvWrapper, rocksdb::HdfsEnv, and rocksdb::SpecialEnv.
Referenced by rocksdb::TableCache::FindTable(), rocksdb::SpecialEnv::NewRandomAccessFile(), rocksdb::EnvWrapper::NewRandomAccessFile(), rocksdb::SstFileReader::ReadSequential(), rocksdb::TableReaderBenchmark(), and rocksdb::TEST().
virtual Status rocksdb::Env::NewRandomRWFile (const std::string & fname, unique_ptr< RandomRWFile > * result, const EnvOptions & options) pure virtual
Implemented in rocksdb::EnvWrapper, and rocksdb::HdfsEnv.
Referenced by rocksdb::BlobStore::CreateNewBucket(), rocksdb::EnvWrapper::NewRandomRWFile(), and rocksdb::TEST().
virtual Status rocksdb::Env::NewSequentialFile (const std::string & fname, unique_ptr< SequentialFile > * result, const EnvOptions & options) pure virtual
Implemented in rocksdb::EnvWrapper, and rocksdb::HdfsEnv.
Referenced by rocksdb::WALDumperCommand::DoCommand(), rocksdb::VersionSet::DumpManifest(), rocksdb::VersionSet::ManifestContains(), rocksdb::EnvWrapper::NewSequentialFile(), rocksdb::TransactionLogIteratorImpl::OpenLogFile(), rocksdb::ReadFileToString(), rocksdb::DBImpl::ReadFirstLine(), rocksdb::VersionSet::Recover(), rocksdb::DBImpl::RecoverLogFile(), and rocksdb::TEST().
virtual Status rocksdb::Env::NewWritableFile (const std::string & fname, unique_ptr< WritableFile > * result, const EnvOptions & options) pure virtual
Implemented in rocksdb::EnvWrapper, rocksdb::HdfsEnv, rocksdb::SpecialEnv, and rocksdb::test::ErrorEnv.
Referenced by rocksdb::BuildTable(), rocksdb::DoWriteStringToFile(), rocksdb::Benchmark::HeapProfile(), rocksdb::VersionSet::LogAndApply(), rocksdb::DBImpl::MakeRoomForWrite(), rocksdb::DBImpl::NewDB(), rocksdb::test::ErrorEnv::NewWritableFile(), rocksdb::SpecialEnv::NewWritableFile(), rocksdb::EnvWrapper::NewWritableFile(), rocksdb::DB::Open(), rocksdb::DBImpl::OpenCompactionOutputFile(), rocksdb::TableReaderBenchmark(), and rocksdb::TEST().
virtual uint64_t rocksdb::Env::NowMicros () pure virtual
Implemented in rocksdb::EnvWrapper, and rocksdb::HdfsEnv.
Referenced by rocksdb::BM_LogAndApply(), rocksdb::CreateLoggerFromOptions(), rocksdb::DBImpl::DoCompactionWork(), rocksdb::Duration::Done(), rocksdb::Duration::Duration(), rocksdb::StopWatch::ElapsedMicros(), rocksdb::DBImpl::FindObsoleteFiles(), rocksdb::Stats::FinishedSingleOp(), rocksdb::PosixLogger::Flush(), rocksdb::DBImpl::GetProperty(), rocksdb::DBImpl::MaybeDumpStats(), rocksdb::EnvWrapper::NowMicros(), NowNanos(), rocksdb::Benchmark::ReadWhileWriting(), rocksdb::StressTest::Reopen(), rocksdb::StressTest::Run(), rocksdb::Stats::Start(), rocksdb::Stats::Stop(), rocksdb::TableReaderBenchmark(), WorkerThreadBody(), rocksdb::DBImpl::WriteLevel0Table(), and rocksdb::DBImpl::WriteLevel0TableForRecovery().
virtual uint64_t rocksdb::Env::NowNanos () inline virtual
Definition at line 214 of file env.h.
References NowMicros().
Referenced by rocksdb::StopWatchNano::ElapsedNanos(), and rocksdb::StopWatchNano::Start().
{
     return NowMicros() * 1000;
   }
void rocksdb::Env::operator= (const Env &) private
virtual Status rocksdb::Env::RenameFile (const std::string & src, const std::string & target) pure virtual
Implemented in rocksdb::EnvWrapper, and rocksdb::HdfsEnv.
Referenced by rocksdb::CreateLoggerFromOptions(), rocksdb::DBImpl::PurgeObsoleteFiles(), rocksdb::EnvWrapper::RenameFile(), rocksdb::SetCurrentFile(), rocksdb::SetIdentityFile(), and rocksdb::TEST().
virtual void rocksdb::Env::Schedule (void(*)(void *arg) function, void * arg, Priority pri = LOW) pure virtual
Implemented in rocksdb::HdfsEnv.
Referenced by rocksdb::DBImpl::MaybeScheduleFlushOrCompaction(), rocksdb::DBImpl::MaybeScheduleLogDBDeployStats(), rocksdb::RunConcurrent(), rocksdb::EnvWrapper::Schedule(), and rocksdb::TEST().
virtual void rocksdb::Env::SetBackgroundThreads (int number, Priority pri = LOW) pure virtual
Implemented in rocksdb::EnvWrapper, and rocksdb::HdfsEnv.
Referenced by main(), rocksdb::EnvWrapper::SetBackgroundThreads(), and rocksdb::TEST().
virtual void rocksdb::Env::SleepForMicroseconds (int micros) pure virtual
Implemented in rocksdb::EnvWrapper, rocksdb::HdfsEnv, and rocksdb::SpecialEnv.
Referenced by rocksdb::DBImpl::BackgroundCallCompaction(), rocksdb::DBImpl::BackgroundCallFlush(), rocksdb::DBImpl::MakeRoomForWrite(), rocksdb::Benchmark::ReadWhileWriting(), rocksdb::SpecialEnv::SleepForMicroseconds(), rocksdb::EnvWrapper::SleepForMicroseconds(), and rocksdb::TEST().
virtual void rocksdb::Env::StartThread (void(*)(void *arg) function, void * arg) pure virtual
Implemented in rocksdb::HdfsEnv.
Referenced by main(), rocksdb::StressTest::Run(), rocksdb::Benchmark::RunBenchmark(), StartBenchmark(), rocksdb::EnvWrapper::StartThread(), and rocksdb::TEST().
virtual std::string rocksdb::Env::TimeToString (uint64_t time) pure virtual
Implemented in rocksdb::EnvWrapper, and rocksdb::HdfsEnv.
Referenced by rocksdb::Stats::FinishedSingleOp(), rocksdb::StressTest::Reopen(), rocksdb::StressTest::Run(), and rocksdb::EnvWrapper::TimeToString().
virtual Status rocksdb::Env::UnlockFile (FileLock * lock) pure virtual
Implemented in rocksdb::EnvWrapper, and rocksdb::HdfsEnv.
Referenced by rocksdb::DestroyDB(), rocksdb::TEST(), rocksdb::DBImpl::TEST_Destroy_DBImpl(), rocksdb::LockTest::UnlockFile(), rocksdb::EnvWrapper::UnlockFile(), and rocksdb::DBImpl::~DBImpl().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/include/rocksdb/env.h
rippled/src/ripple/rocksdb/rocksdb/util/env.cc
rippled/src/ripple/rocksdb/rocksdb/util/env_posix.cc