rippled: rocksdb::Version::LevelFileNumIterator Class Reference
rocksdb::Version::LevelFileNumIterator Class Reference
Public Member Functions
LevelFileNumIterator (const InternalKeyComparator &icmp, const std::vector< FileMetaData * > *flist)
virtual bool Valid () const
virtual void Seek (const Slice &target)
virtual void SeekToFirst ()
virtual void SeekToLast ()
virtual void Next ()
virtual void Prev ()
Slice key () const
Slice value () const
virtual Status status () const
Public Member Functions inherited from rocksdb::Iterator
Iterator ()
virtual ~Iterator ()
void RegisterCleanup (CleanupFunction function, void *arg1, void *arg2)
Private Attributes
const InternalKeyComparator icmp_
const std::vector
< FileMetaData * > *const flist_
uint32_t index_
char value_buf_ [16]
Additional Inherited Members
Public Types inherited from rocksdb::Iterator
typedef void(* CleanupFunction)(void *arg1, void *arg2)
Detailed Description
Definition at line 137 of file version_set.cc.
Constructor & Destructor Documentation
rocksdb::Version::LevelFileNumIterator::LevelFileNumIterator (const InternalKeyComparator & icmp, const std::vector< FileMetaData * > * flist) inline
Definition at line 139 of file version_set.cc.
       : icmp_(icmp),
         flist_(flist),
         index_(flist->size()) {        // Marks as invalid
   }
Member Function Documentation
Slice rocksdb::Version::LevelFileNumIterator::key () const inline virtual
Implements rocksdb::Iterator.
Definition at line 167 of file version_set.cc.
References flist_, index_, and Valid().
                     {
     assert(Valid());
     return (*flist_)[index_]->largest.Encode();
   }
virtual void rocksdb::Version::LevelFileNumIterator::Next () inline virtual
Implements rocksdb::Iterator.
Definition at line 155 of file version_set.cc.
References index_, and Valid().
                       {
     assert(Valid());
     index_++;
   }
virtual void rocksdb::Version::LevelFileNumIterator::Prev () inline virtual
Implements rocksdb::Iterator.
Definition at line 159 of file version_set.cc.
References flist_, index_, and Valid().
                       {
     assert(Valid());
     if (index_ == 0) {
       index_ = flist_->size();  // Marks as invalid
     } else {
       index_--;
     }
   }
virtual void rocksdb::Version::LevelFileNumIterator::Seek (const Slice & target) inline virtual
Implements rocksdb::Iterator.
Definition at line 148 of file version_set.cc.
References rocksdb::FindFile(), flist_, icmp_, and index_.
{
     index_ = FindFile(icmp_, *flist_, target);
   }
virtual void rocksdb::Version::LevelFileNumIterator::SeekToFirst () inline virtual
Implements rocksdb::Iterator.
Definition at line 151 of file version_set.cc.
References index_.
 { index_ = 0; }
virtual void rocksdb::Version::LevelFileNumIterator::SeekToLast () inline virtual
Implements rocksdb::Iterator.
Definition at line 152 of file version_set.cc.
References flist_, and index_.
{
     index_ = flist_->empty() ? 0 : flist_->size() - 1;
   }
virtual Status rocksdb::Version::LevelFileNumIterator::status () const inline virtual
Implements rocksdb::Iterator.
Definition at line 177 of file version_set.cc.
References rocksdb::Status::OK().
 { return Status::OK(); }
virtual bool rocksdb::Version::LevelFileNumIterator::Valid () const inline virtual
Implements rocksdb::Iterator.
Definition at line 145 of file version_set.cc.
References flist_, and index_.
Referenced by key(), Next(), Prev(), and value().
{
     return index_ < flist_->size();
   }
Slice rocksdb::Version::LevelFileNumIterator::value () const inline virtual
Implements rocksdb::Iterator.
Definition at line 171 of file version_set.cc.
References rocksdb::EncodeFixed64(), flist_, index_, Valid(), and value_buf_.
                       {
     assert(Valid());
     EncodeFixed64(value_buf_, (*flist_)[index_]->number);
     EncodeFixed64(value_buf_+8, (*flist_)[index_]->file_size);
     return Slice(value_buf_, sizeof(value_buf_));
   }
Member Data Documentation
const std::vector<FileMetaData*>* const rocksdb::Version::LevelFileNumIterator::flist_ private
Definition at line 180 of file version_set.cc.
Referenced by key(), Prev(), Seek(), SeekToLast(), Valid(), and value().
const InternalKeyComparator rocksdb::Version::LevelFileNumIterator::icmp_ private
Definition at line 179 of file version_set.cc.
Referenced by Seek().
uint32_t rocksdb::Version::LevelFileNumIterator::index_ private
Definition at line 181 of file version_set.cc.
Referenced by key(), Next(), Prev(), Seek(), SeekToFirst(), SeekToLast(), Valid(), and value().
char rocksdb::Version::LevelFileNumIterator::value_buf_[16] mutable private
Definition at line 184 of file version_set.cc.
Referenced by value().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/db/version_set.cc