rippled: beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator > Class Template Reference
beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator > Class Template Reference
#include <aged_ordered_container.h>
Classes
class chronological_t
class config_t
struct element
class KeyValueCompare
class pair_value_compare
Public Types
typedef abstract_clock< Duration > clock_type
typedef clock_type::time_point time_point
typedef clock_type::duration duration
typedef Key key_type
typedef T mapped_type
typedef std::conditional
< IsMap, std::pair< Key const,
T >, Key >::type value_type
typedef std::size_t size_type
typedef std::ptrdiff_t difference_type
typedef std::false_type is_unordered
typedef std::integral_constant
< bool, IsMulti > is_multi
typedef std::integral_constant
< bool, IsMap > is_map
typedef Compare key_compare
typedef std::conditional
< IsMap, pair_value_compare,
Compare >::type value_compare
typedef Allocator allocator_type
typedef value_type & reference
typedef value_type const & const_reference
typedef std::allocator_traits
< Allocator >::pointer pointer
typedef std::allocator_traits
< Allocator >::const_pointer const_pointer
typedef
detail::aged_container_iterator
< false, typename
cont_type::iterator > iterator
typedef
detail::aged_container_iterator
< true, typename
cont_type::iterator > const_iterator
typedef
detail::aged_container_iterator
< false, typename
cont_type::reverse_iterator > reverse_iterator
typedef
detail::aged_container_iterator
< true, typename
cont_type::reverse_iterator > const_reverse_iterator
Public Member Functions
aged_ordered_container (clock_type &clock)
aged_ordered_container (clock_type &clock, Compare const &comp)
aged_ordered_container (clock_type &clock, Allocator const &alloc)
aged_ordered_container (clock_type &clock, Compare const &comp, Allocator const &alloc)
template<class InputIt >
aged_ordered_container (InputIt first, InputIt last, clock_type &clock)
template<class InputIt >
aged_ordered_container (InputIt first, InputIt last, clock_type &clock, Compare const &comp)
template<class InputIt >
aged_ordered_container (InputIt first, InputIt last, clock_type &clock, Allocator const &alloc)
template<class InputIt >
aged_ordered_container (InputIt first, InputIt last, clock_type &clock, Compare const &comp, Allocator const &alloc)
aged_ordered_container (aged_ordered_container const &other)
aged_ordered_container (aged_ordered_container const &other, Allocator const &alloc)
aged_ordered_container (aged_ordered_container &&other)
aged_ordered_container (aged_ordered_container &&other, Allocator const &alloc)
aged_ordered_container (std::initializer_list< value_type > init, clock_type &clock)
aged_ordered_container (std::initializer_list< value_type > init, clock_type &clock, Compare const &comp)
aged_ordered_container (std::initializer_list< value_type > init, clock_type &clock, Allocator const &alloc)
aged_ordered_container (std::initializer_list< value_type > init, clock_type &clock, Compare const &comp, Allocator const &alloc)
~aged_ordered_container ()
aged_ordered_container & operator= (aged_ordered_container const &other)
aged_ordered_container & operator= (aged_ordered_container &&other)
aged_ordered_container & operator= (std::initializer_list< value_type > init)
allocator_type get_allocator () const
clock_type & clock ()
clock_type const & clock () const
template<class K , bool maybe_multi = IsMulti, bool maybe_map = IsMap, class = typename std::enable_if <maybe_map && ! maybe_multi>::type>
std::conditional< IsMap, T,
void * >::type & at (K const &k)
template<class K , bool maybe_multi = IsMulti, bool maybe_map = IsMap, class = typename std::enable_if <maybe_map && ! maybe_multi>::type>
std::conditional< IsMap, T,
void * >::type const & at (K const &k) const
template<bool maybe_multi = IsMulti, bool maybe_map = IsMap, class = typename std::enable_if <maybe_map && ! maybe_multi>::type>
std::conditional< IsMap, T,
void * >::type & operator[] (Key const &key)
template<bool maybe_multi = IsMulti, bool maybe_map = IsMap, class = typename std::enable_if <maybe_map && ! maybe_multi>::type>
std::conditional< IsMap, T,
void * >::type & operator[] (Key &&key)
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
iterator end ()
const_iterator end () const
const_iterator cend () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
const_reverse_iterator crbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
const_reverse_iterator crend () const
iterator iterator_to (value_type &value)
const_iterator iterator_to (value_type const &value) const
bool empty () const noexcept
size_type size () const noexcept
size_type max_size () const noexcept
void clear ()
template<bool maybe_multi = IsMulti>
auto insert (value_type const &value) -> typename std::enable_if<!maybe_multi, std::pair< iterator, bool >>::type
template<bool maybe_multi = IsMulti>
auto insert (value_type const &value) -> typename std::enable_if< maybe_multi, iterator >::type
template<bool maybe_multi = IsMulti, bool maybe_map = IsMap>
auto insert (value_type &&value) -> typename std::enable_if<!maybe_multi &&!maybe_map, std::pair< iterator, bool >>::type
template<bool maybe_multi = IsMulti, bool maybe_map = IsMap>
auto insert (value_type &&value) -> typename std::enable_if< maybe_multi &&!maybe_map, iterator >::type
template<bool maybe_multi = IsMulti>
auto insert (const_iterator hint, value_type const &value) -> typename std::enable_if<!maybe_multi, iterator >::type
template<bool maybe_multi = IsMulti>
std::enable_if< maybe_multi,
iterator >::type insert (const_iterator const &, value_type const &value)
template<bool maybe_multi = IsMulti>
auto insert (const_iterator hint, value_type &&value) -> typename std::enable_if<!maybe_multi, iterator >::type
template<bool maybe_multi = IsMulti>
std::enable_if< maybe_multi,
iterator >::type insert (const_iterator const &, value_type &&value)
template<class P , bool maybe_map = IsMap>
std::enable_if< maybe_map
&&std::is_constructible
< value_type, P && >::value,
typename std::conditional
< IsMulti, iterator, std::pair
< iterator, bool > >::type >
::type insert (P &&value)
template<class P , bool maybe_map = IsMap>
std::enable_if< maybe_map
&&std::is_constructible
< value_type, P && >::value,
typename std::conditional
< IsMulti, iterator, std::pair
< iterator, bool > >::type >
::type insert (const_iterator hint, P &&value)
template<class InputIt >
void insert (InputIt first, InputIt const &last)
void insert (std::initializer_list< value_type > init)
template<bool maybe_multi = IsMulti, class... Args>
auto emplace (Args &&...args) -> typename std::enable_if<!maybe_multi, std::pair< iterator, bool >>::type
template<bool maybe_multi = IsMulti, class... Args>
auto emplace (Args &&...args) -> typename std::enable_if< maybe_multi, iterator >::type
template<bool maybe_multi = IsMulti, class... Args>
auto emplace_hint (const_iterator const &hint, Args &&...args) -> typename std::enable_if<!maybe_multi, std::pair< iterator, bool >>::type
template<bool maybe_multi = IsMulti, class... Args>
std::enable_if< maybe_multi,
iterator >::type emplace_hint (const_iterator const &, Args &&...args)
template<bool is_const, class Iterator , class Base >
detail::aged_container_iterator
< false, Iterator, Base > erase (detail::aged_container_iterator< is_const, Iterator, Base > const &pos)
template<bool is_const, class Iterator , class Base >
detail::aged_container_iterator
< false, Iterator, Base > erase (detail::aged_container_iterator< is_const, Iterator, Base > first, detail::aged_container_iterator< is_const, Iterator, Base > const &last)
template<class K >
auto erase (K const &k) -> size_type
void swap (aged_ordered_container &other) noexcept
template<bool is_const, class Iterator , class Base >
void touch (detail::aged_container_iterator< is_const, Iterator, Base > const &pos)
template<class K >
size_type touch (K const &k)
template<class K >
size_type count (K const &k) const
template<class K >
iterator find (K const &k)
template<class K >
const_iterator find (K const &k) const
template<class K >
std::pair< iterator, iterator > equal_range (K const &k)
template<class K >
std::pair< const_iterator,
const_iterator > equal_range (K const &k) const
template<class K >
iterator lower_bound (K const &k)
template<class K >
const_iterator lower_bound (K const &k) const
template<class K >
iterator upper_bound (K const &k)
template<class K >
const_iterator upper_bound (K const &k) const
key_compare key_comp () const
value_compare value_comp () const
template<bool OtherIsMulti, bool OtherIsMap, class OtherT , class OtherDuration , class OtherAllocator >
bool operator== (aged_ordered_container< OtherIsMulti, OtherIsMap, Key, OtherT, OtherDuration, Compare, OtherAllocator > const &other) const
template<bool OtherIsMulti, bool OtherIsMap, class OtherT , class OtherDuration , class OtherAllocator >
bool operator!= (aged_ordered_container< OtherIsMulti, OtherIsMap, Key, OtherT, OtherDuration, Compare, OtherAllocator > const &other) const
template<bool OtherIsMulti, bool OtherIsMap, class OtherT , class OtherDuration , class OtherAllocator >
bool operator< (aged_ordered_container< OtherIsMulti, OtherIsMap, Key, OtherT, OtherDuration, Compare, OtherAllocator > const &other) const
template<bool OtherIsMulti, bool OtherIsMap, class OtherT , class OtherDuration , class OtherAllocator >
bool operator<= (aged_ordered_container< OtherIsMulti, OtherIsMap, Key, OtherT, OtherDuration, Compare, OtherAllocator > const &other) const
template<bool OtherIsMulti, bool OtherIsMap, class OtherT , class OtherDuration , class OtherAllocator >
bool operator> (aged_ordered_container< OtherIsMulti, OtherIsMap, Key, OtherT, OtherDuration, Compare, OtherAllocator > const &other) const
template<bool OtherIsMulti, bool OtherIsMap, class OtherT , class OtherDuration , class OtherAllocator >
bool operator>= (aged_ordered_container< OtherIsMulti, OtherIsMap, Key, OtherT, OtherDuration, Compare, OtherAllocator > const &other) const
template<bool is_const, class Iterator , class Base >
auto erase (detail::aged_container_iterator< is_const, Iterator, Base > const &pos) -> detail::aged_container_iterator< false, Iterator, Base >
template<bool is_const, class Iterator , class Base >
auto erase (detail::aged_container_iterator< is_const, Iterator, Base > first, detail::aged_container_iterator< is_const, Iterator, Base > const &last) -> detail::aged_container_iterator< false, Iterator, Base >
template<class K>
auto touch (K const &k) -> size_type
Public Attributes
class
beast::detail::aged_ordered_container::chronological_t chronological
Private Types
typedef
boost::intrusive::make_list
< element,
boost::intrusive::constant_time_size
< false > >::type list_type
typedef std::conditional
< IsMulti, typename
boost::intrusive::make_multiset
< element,
boost::intrusive::constant_time_size
< true > >::type, typename
boost::intrusive::make_set
< element,
boost::intrusive::constant_time_size
< true > >::type >::type cont_type
typedef std::allocator_traits
< Allocator >::template
rebind_alloc< element > ElementAllocator
using ElementAllocatorTraits = std::allocator_traits< ElementAllocator >
Private Member Functions
template<class... Args>
element * new_element (Args &&...args)
void delete_element (element *p)
void unlink_and_delete_element (element *p)
template<bool is_const, class Iterator , class Base >
void touch (detail::aged_container_iterator< is_const, Iterator, Base > const &pos, typename clock_type::time_point const &now)
template<bool maybe_propagate = std::allocator_traits < Allocator>::propagate_on_container_swap::value>
std::enable_if
< maybe_propagate >::type swap_data (aged_ordered_container &other) noexcept
template<bool maybe_propagate = std::allocator_traits < Allocator>::propagate_on_container_swap::value>
std::enable_if
<!maybe_propagate >::type swap_data (aged_ordered_container &other) noexcept
Static Private Member Functions
static Key const & extract (value_type const &value)
Private Attributes
config_t m_config
cont_type m_cont
Detailed Description
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>>
class beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >
Associative container where each element is also indexed by time.
This container mirrors the interface of the standard library ordered associative containers, with the addition that each element is associated with a when time_point which is obtained from the value of the clock's now. The function touch updates the time for an element to the current time as reported by the clock.
An extra set of iterator types and member functions are provided in the chronological memberspace that allow traversal in temporal or reverse temporal order. This container is useful as a building block for caches whose items expire after a certain amount of time. The chronological iterators allow for fully customizable expiration strategies.
See Also
aged_set, aged_multiset, aged_map, aged_multimap
Definition at line 73 of file aged_ordered_container.h.
Member Typedef Documentation
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef Allocator beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::allocator_type
Definition at line 407 of file aged_ordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef abstract_clock<Duration> beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::clock_type
Definition at line 76 of file aged_ordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef detail::aged_container_iterator<true, typename cont_type::iterator> beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::const_iterator
Definition at line 418 of file aged_ordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef std::allocator_traits< Allocator>::const_pointer beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::const_pointer
Definition at line 413 of file aged_ordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef value_type const& beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::const_reference
Definition at line 409 of file aged_ordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef detail::aged_container_iterator<true, typename cont_type::reverse_iterator> beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::const_reverse_iterator
Definition at line 422 of file aged_ordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef std::conditional< IsMulti, typename boost::intrusive::make_multiset <element, boost::intrusive::constant_time_size <true> >::type, typename boost::intrusive::make_set <element, boost::intrusive::constant_time_size <true> >::type >::type beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::cont_type private
Definition at line 247 of file aged_ordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef std::ptrdiff_t beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::difference_type
Definition at line 86 of file aged_ordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef clock_type::duration beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::duration
Definition at line 78 of file aged_ordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef std::allocator_traits< Allocator>::template rebind_alloc<element> beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::ElementAllocator private
Definition at line 250 of file aged_ordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> using beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::ElementAllocatorTraits = std::allocator_traits <ElementAllocator> private
Definition at line 252 of file aged_ordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef std::integral_constant<bool, IsMap> beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::is_map
Definition at line 91 of file aged_ordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef std::integral_constant<bool, IsMulti> beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::is_multi
Definition at line 90 of file aged_ordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef std::false_type beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::is_unordered
Definition at line 89 of file aged_ordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef detail::aged_container_iterator<false, typename cont_type::iterator> beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::iterator
Definition at line 416 of file aged_ordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef Compare beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::key_compare
Definition at line 402 of file aged_ordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef Key beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::key_type
Definition at line 79 of file aged_ordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef boost::intrusive::make_list<element, boost::intrusive::constant_time_size <false> >::type beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::list_type private
Definition at line 237 of file aged_ordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef T beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::mapped_type
Definition at line 80 of file aged_ordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef std::allocator_traits< Allocator>::pointer beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::pointer
Definition at line 411 of file aged_ordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef value_type& beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::reference
Definition at line 408 of file aged_ordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef detail::aged_container_iterator<false, typename cont_type::reverse_iterator> beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::reverse_iterator
Definition at line 420 of file aged_ordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef std::size_t beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::size_type
Definition at line 85 of file aged_ordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef clock_type::time_point beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::time_point
Definition at line 77 of file aged_ordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef std::conditional< IsMap, pair_value_compare, Compare>::type beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::value_compare
Definition at line 406 of file aged_ordered_container.h.
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> typedef std::conditional< IsMap, std::pair <Key const, T>, Key>::type beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::value_type
Definition at line 84 of file aged_ordered_container.h.
Constructor & Destructor Documentation
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare , class Allocator > beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::aged_ordered_container (clock_type & clock) explicit
Definition at line 1205 of file aged_ordered_container.h.
     : m_config (clock)
 {
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare, class Allocator > beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::aged_ordered_container (clock_type & clock, Compare const & comp)
Definition at line 1214 of file aged_ordered_container.h.
     : m_config (clock, comp)
 {
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare, class Allocator> beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::aged_ordered_container (clock_type & clock, Allocator const & alloc)
Definition at line 1224 of file aged_ordered_container.h.
     : m_config (clock, alloc)
 {
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare, class Allocator> beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::aged_ordered_container (clock_type & clock, Compare const & comp, Allocator const & alloc)
Definition at line 1234 of file aged_ordered_container.h.
     : m_config (clock, comp, alloc)
 {
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare , class Allocator > template<class InputIt > beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::aged_ordered_container (InputIt first, InputIt last, clock_type & clock)
Definition at line 1246 of file aged_ordered_container.h.
References beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::insert().
     : m_config (clock)
 {
     insert (first, last);
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare, class Allocator > template<class InputIt > beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::aged_ordered_container (InputIt first, InputIt last, clock_type & clock, Compare const & comp)
Definition at line 1257 of file aged_ordered_container.h.
References beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::insert().
     : m_config (clock, comp)
 {
     insert (first, last);
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare, class Allocator> template<class InputIt > beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::aged_ordered_container (InputIt first, InputIt last, clock_type & clock, Allocator const & alloc)
Definition at line 1269 of file aged_ordered_container.h.
References beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::insert().
     : m_config (clock, alloc)
 {
     insert (first, last);
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare, class Allocator> template<class InputIt > beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::aged_ordered_container (InputIt first, InputIt last, clock_type & clock, Compare const & comp, Allocator const & alloc)
Definition at line 1281 of file aged_ordered_container.h.
References beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::insert().
     : m_config (clock, comp, alloc)
 {
     insert (first, last);
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare, class Allocator> beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::aged_ordered_container (aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator > const & other)
Definition at line 1293 of file aged_ordered_container.h.
References beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::cbegin(), beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::cend(), and beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::insert().
     : m_config (other.m_config)
 {
     insert (other.cbegin(), other.cend());
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare, class Allocator> beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::aged_ordered_container (aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator > const & other, Allocator const & alloc)
Definition at line 1302 of file aged_ordered_container.h.
References beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::cbegin(), beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::cend(), and beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::insert().
     : m_config (other.m_config, alloc)
 {
     insert (other.cbegin(), other.cend());
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare, class Allocator> beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::aged_ordered_container (aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator > && other)
Definition at line 1312 of file aged_ordered_container.h.
References beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::chronological, and beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::chronological_t::list.
     : m_config (std::move (other.m_config))
     , m_cont (std::move (other.m_cont))
 {
     chronological.list = std::move (other.chronological.list);
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare, class Allocator> beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::aged_ordered_container (aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator > && other, Allocator const & alloc)
Definition at line 1322 of file aged_ordered_container.h.
References beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::insert().
     : m_config (std::move (other.m_config), alloc)
 {
     insert (other.cbegin(), other.cend());
     other.clear ();
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare, class Allocator> beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::aged_ordered_container (std::initializer_list< value_type > init, clock_type & clock)
Definition at line 1333 of file aged_ordered_container.h.
References beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::insert().
     : m_config (clock)
 {
     insert (init.begin(), init.end());
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare, class Allocator> beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::aged_ordered_container (std::initializer_list< value_type > init, clock_type & clock, Compare const & comp)
Definition at line 1343 of file aged_ordered_container.h.
References beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::insert().
     : m_config (clock, comp)
 {
     insert (init.begin(), init.end());
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare, class Allocator> beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::aged_ordered_container (std::initializer_list< value_type > init, clock_type & clock, Allocator const & alloc)
Definition at line 1354 of file aged_ordered_container.h.
References beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::insert().
     : m_config (clock, alloc)
 {
     insert (init.begin(), init.end());
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare, class Allocator> beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::aged_ordered_container (std::initializer_list< value_type > init, clock_type & clock, Compare const & comp, Allocator const & alloc)
Definition at line 1365 of file aged_ordered_container.h.
References beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::insert().
     : m_config (clock, comp, alloc)
 {
     insert (init.begin(), init.end());
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare , class Allocator > beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::~aged_ordered_container ()
Definition at line 1377 of file aged_ordered_container.h.
 {
     clear();
 }
Member Function Documentation
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare , class Allocator > template<class K , bool maybe_multi, bool maybe_map, class > std::conditional< IsMap, T, void * >::type & beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::at (K const & k)
Definition at line 1431 of file aged_ordered_container.h.
 {
     auto const iter (m_cont.find (k,
         std::cref (m_config.key_compare())));
     if (iter == m_cont.end())
         throw std::out_of_range ("key not found");
     return iter->value.second;
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare , class Allocator > template<class K , bool maybe_multi, bool maybe_map, class > std::conditional< IsMap, T, void * >::type const & beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::at (K const & k) const
Definition at line 1445 of file aged_ordered_container.h.
 {
     auto const iter (m_cont.find (k,
         std::cref (m_config.key_compare())));
     if (iter == m_cont.end())
         throw std::out_of_range ("key not found");
     return iter->value.second;
 }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> iterator beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::begin () inline
Definition at line 661 of file aged_ordered_container.h.
     {
         return iterator (m_cont.begin());
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> const_iterator beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::begin () const inline
Definition at line 667 of file aged_ordered_container.h.
     {
         return const_iterator (m_cont.begin ());
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> const_iterator beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::cbegin () const inline
Definition at line 673 of file aged_ordered_container.h.
Referenced by beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::aged_ordered_container(), and beast::detail::aged_ordered_container< beast::IP::Address >::operator<().
     {
         return const_iterator (m_cont.begin ());
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> const_iterator beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::cend () const inline
Definition at line 691 of file aged_ordered_container.h.
Referenced by beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::aged_ordered_container(), beast::detail::aged_ordered_container< beast::IP::Address >::insert(), and beast::detail::aged_ordered_container< beast::IP::Address >::operator<().
     {
         return const_iterator (m_cont.end ());
     }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare , class Allocator > void beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::clear ()
Definition at line 1505 of file aged_ordered_container.h.
References beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::clear().
Referenced by beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::clear().
 {
     for (auto iter (chronological.list.begin());
         iter != chronological.list.end();)
         delete_element (&*iter++);
     chronological.list.clear();
     m_cont.clear();
 }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> clock_type& beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::clock () inline
Definition at line 607 of file aged_ordered_container.h.
Referenced by beast::detail::aged_ordered_container< beast::IP::Address >::new_element(), and beast::detail::aged_ordered_container< beast::IP::Address >::touch().
     {
         return m_config.clock;
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> clock_type const& beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::clock () const inline
Definition at line 613 of file aged_ordered_container.h.
     {
         return m_config.clock;
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<class K > size_type beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::count (K const & k) const inline
Definition at line 972 of file aged_ordered_container.h.
     {
         return m_cont.count (k,
             std::cref (m_config.key_compare()));
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> const_reverse_iterator beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::crbegin () const inline
Definition at line 709 of file aged_ordered_container.h.
     {
         return const_reverse_iterator (m_cont.rbegin ());
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> const_reverse_iterator beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::crend () const inline
Definition at line 727 of file aged_ordered_container.h.
     {
         return const_reverse_iterator (m_cont.rend ());
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> void beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::delete_element (element * p) inline private
Definition at line 387 of file aged_ordered_container.h.
Referenced by beast::detail::aged_ordered_container< beast::IP::Address >::unlink_and_delete_element().
     {
         ElementAllocatorTraits::destroy (m_config.alloc(), p);
         ElementAllocatorTraits::deallocate (m_config.alloc(), p, 1);
     }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare , class Allocator > template<bool maybe_multi, class... Args> auto beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::emplace (Args &&... args) -> typename std::enable_if <! maybe_multi, std::pair <iterator, bool>>::type
Definition at line 1650 of file aged_ordered_container.h.
References beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::element::value.
Referenced by beast::detail::aged_ordered_container< beast::IP::Address >::insert().
 {
     // VFALCO NOTE Its unfortunate that we need to
     //             construct element here
     element* const p (new_element (
         std::forward <Args> (args)...));
     typename cont_type::insert_commit_data d;
     auto const result (m_cont.insert_check (extract (p->value),
         std::cref (m_config.key_compare()), d));
     if (result.second)
     {
         chronological.list.push_back (*p);
         auto const iter (m_cont.insert_commit (*p, d));
         return std::make_pair (iterator (iter), true);
     }
     delete_element (p);
     return std::make_pair (iterator (result.first), false);
 }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<bool maybe_multi = IsMulti, class... Args> auto beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::emplace (Args &&... args) -> typename std::enable_if< maybe_multi, iterator >::type
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare , class Allocator > template<bool maybe_multi, class... Args> auto beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::emplace_hint (const_iterator const & hint, Args &&... args) -> typename std::enable_if <! maybe_multi, std::pair <iterator, bool>>::type
Definition at line 1696 of file aged_ordered_container.h.
References beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::element::value.
Referenced by beast::detail::aged_ordered_container< beast::IP::Address >::insert().
 {
     // VFALCO NOTE Its unfortunate that we need to
     //             construct element here
     element* const p (new_element (
         std::forward <Args> (args)...));
     typename cont_type::insert_commit_data d;
     auto const result (m_cont.insert_check (hint.iterator(),
         extract (p->value), std::cref (m_config.key_compare()), d));
     if (result.second)
     {
         chronological.list.push_back (*p);
         auto const iter (m_cont.insert_commit (*p, d));
         return std::make_pair (iterator (iter), true);
     }
     delete_element (p);
     return std::make_pair (iterator (result.first), false);
 }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<bool maybe_multi = IsMulti, class... Args> std::enable_if<maybe_multi, iterator>::type beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::emplace_hint (const_iterator const & , Args &&... args) inline
Definition at line 922 of file aged_ordered_container.h.
     {
         // VFALCO TODO Figure out how to utilize 'hint'
         return emplace <maybe_multi> (
             std::forward <Args> (args)...);
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> bool beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::empty () const inline noexcept
Definition at line 759 of file aged_ordered_container.h.
Referenced by ripple::PeerFinder::Livecache< class >::empty().
     {
         return m_cont.empty();
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> iterator beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::end () inline
Definition at line 679 of file aged_ordered_container.h.
     {
         return iterator (m_cont.end ());
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> const_iterator beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::end () const inline
Definition at line 685 of file aged_ordered_container.h.
     {
         return const_iterator (m_cont.end ());
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<class K > std::pair<iterator, iterator> beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::equal_range (K const & k) inline
Definition at line 999 of file aged_ordered_container.h.
     {
         auto const r (m_cont.equal_range (k,
             std::cref (m_config.key_compare())));
         return std::make_pair (iterator (r.first),
             iterator (r.second));
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<class K > std::pair<const_iterator, const_iterator> beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::equal_range (K const & k) const inline
Definition at line 1010 of file aged_ordered_container.h.
     {
         auto const r (m_cont.equal_range (k,
             std::cref (m_config.key_compare())));
         return std::make_pair (const_iterator (r.first),
             const_iterator (r.second));
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<bool is_const, class Iterator , class Base > detail::aged_container_iterator<false, Iterator, Base> beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::erase (detail::aged_container_iterator< is_const, Iterator, Base > const & pos)
Referenced by beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::touch().
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<bool is_const, class Iterator , class Base > detail::aged_container_iterator<false, Iterator, Base> beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::erase (detail::aged_container_iterator< is_const, Iterator, Base > first, detail::aged_container_iterator< is_const, Iterator, Base > const & last)
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare , class Allocator > template<class K> auto beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::erase (K const & k) -> size_type
Definition at line 1758 of file aged_ordered_container.h.
 {
     auto iter (m_cont.find (k,
         std::cref (m_config.key_compare())));
     if (iter == m_cont.end())
         return 0;
     size_type n (0);
     for (;;)
     {
         auto p (&*iter++);
         bool const done (
             m_config (*p, extract (iter->value)));
         unlink_and_delete_element (p);
         ++n;
         if (done)
             break;
     }
     return n;
 }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<bool is_const, class Iterator , class Base > auto beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::erase (detail::aged_container_iterator< is_const, Iterator, Base > const & pos) -> detail::aged_container_iterator <false, Iterator, Base>
Definition at line 1722 of file aged_ordered_container.h.
 {
     auto iter (pos.iterator());
     auto p (&*iter++);
     unlink_and_delete_element (p);
     return detail::aged_container_iterator <
         false, Iterator, Base> (iter);
 }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<bool is_const, class Iterator , class Base > auto beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::erase (detail::aged_container_iterator< is_const, Iterator, Base > first, detail::aged_container_iterator< is_const, Iterator, Base > const & last) -> detail::aged_container_iterator <false, Iterator, Base>
Definition at line 1738 of file aged_ordered_container.h.
References beast.util.Iter::first().
 {
     for (; first != last;)
     {
         auto p (&*first++);
         unlink_and_delete_element (p);
     }
     return detail::aged_container_iterator <
         false, Iterator, Base> (first.iterator());
 }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> static Key const& beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::extract (value_type const & value) inline static private
Definition at line 97 of file aged_ordered_container.h.
Referenced by beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::KeyValueCompare::operator()().
     {
         return aged_associative_container_extract_t <IsMap> () (value);
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<class K > iterator beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::find (K const & k) inline
Definition at line 981 of file aged_ordered_container.h.
     {
         return iterator (m_cont.find (k,
             std::cref (m_config.key_compare())));
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<class K > const_iterator beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::find (K const & k) const inline
Definition at line 990 of file aged_ordered_container.h.
     {
         return const_iterator (m_cont.find (k,
             std::cref (m_config.key_compare())));
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> allocator_type beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::get_allocator () const inline
Definition at line 601 of file aged_ordered_container.h.
     {
         return m_config.alloc();
     }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare , class Allocator > template<bool maybe_multi> auto beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::insert (value_type const & value) -> typename std::enable_if <! maybe_multi, std::pair <iterator, bool>>::type
Definition at line 1520 of file aged_ordered_container.h.
References value.
Referenced by beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::aged_ordered_container(), beast::detail::aged_ordered_container< beast::IP::Address >::insert(), ripple::PeerFinder::Logic::squelch_slots(), and ripple::PeerFinder::ConnectHandouts::try_insert().
 {
     typename cont_type::insert_commit_data d;
     auto const result (m_cont.insert_check (extract (value),
         std::cref (m_config.key_compare()), d));
     if (result.second)
     {
         element* const p (new_element (value));
         chronological.list.push_back (*p);
         auto const iter (m_cont.insert_commit (*p, d));
         return std::make_pair (iterator (iter), true);
     }
     return std::make_pair (iterator (result.first), false);
 }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<bool maybe_multi = IsMulti> auto beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::insert (value_type const & value) -> typename std::enable_if< maybe_multi, iterator >::type
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare , class Allocator > template<bool maybe_multi, bool maybe_map> auto beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::insert (value_type && value) -> typename std::enable_if <! maybe_multi && ! maybe_map, std::pair <iterator, bool>>::type
Definition at line 1561 of file aged_ordered_container.h.
References value.
 {
     typename cont_type::insert_commit_data d;
     auto const result (m_cont.insert_check (extract (value),
         std::cref (m_config.key_compare()), d));
     if (result.second)
     {
         element* const p (new_element (std::move (value)));
         chronological.list.push_back (*p);
         auto const iter (m_cont.insert_commit (*p, d));
         return std::make_pair (iterator (iter), true);
     }
     return std::make_pair (iterator (result.first), false);
 }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<bool maybe_multi = IsMulti, bool maybe_map = IsMap> auto beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::insert (value_type && value) -> typename std::enable_if< maybe_multi &&!maybe_map, iterator >::type
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare , class Allocator > template<bool maybe_multi> auto beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::insert (const_iterator hint, value_type const & value) -> typename std::enable_if <! maybe_multi, iterator>::type
Definition at line 1604 of file aged_ordered_container.h.
References value.
 {
     typename cont_type::insert_commit_data d;
     auto const result (m_cont.insert_check (hint.iterator(),
         extract (value), std::cref (m_config.key_compare()), d));
     if (result.second)
     {
         element* const p (new_element (value));
         chronological.list.push_back (*p);
         auto const iter (m_cont.insert_commit (*p, d));
         return iterator (iter);
     }
     return iterator (result.first);
 }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<bool maybe_multi = IsMulti> std::enable_if<maybe_multi, iterator>::type beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::insert (const_iterator const & , value_type const & value) inline
Definition at line 826 of file aged_ordered_container.h.
     {
         // VFALCO TODO Figure out how to utilize 'hint'
         return insert (value);
     }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare , class Allocator > template<bool maybe_multi> auto beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::insert (const_iterator hint, value_type && value) -> typename std::enable_if <! maybe_multi, iterator>::type
Definition at line 1627 of file aged_ordered_container.h.
References value.
 {
     typename cont_type::insert_commit_data d;
     auto const result (m_cont.insert_check (hint.iterator(),
         extract (value), std::cref (m_config.key_compare()), d));
     if (result.second)
     {
         element* const p (new_element (std::move (value)));
         chronological.list.push_back (*p);
         auto const iter (m_cont.insert_commit (*p, d));
         return iterator (iter);
     }
     return iterator (result.first);
 }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<bool maybe_multi = IsMulti> std::enable_if<maybe_multi, iterator>::type beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::insert (const_iterator const & , value_type && value) inline
Definition at line 843 of file aged_ordered_container.h.
     {
         // VFALCO TODO Figure out how to utilize 'hint'
         return insert (std::move (value));
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<class P , bool maybe_map = IsMap> std::enable_if<maybe_map && std::is_constructible <value_type, P&&>::value, typename std::conditional <IsMulti, iterator, std::pair <iterator, bool> >::type >::type beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::insert (P && value) inline
Definition at line 861 of file aged_ordered_container.h.
     {
         return emplace (std::forward <P> (value));
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<class P , bool maybe_map = IsMap> std::enable_if<maybe_map && std::is_constructible <value_type, P&&>::value, typename std::conditional <IsMulti, iterator, std::pair <iterator, bool> >::type >::type beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::insert (const_iterator hint, P && value) inline
Definition at line 878 of file aged_ordered_container.h.
     {
         return emplace_hint (hint, std::forward <P> (value));
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<class InputIt > void beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::insert (InputIt first, InputIt const & last) inline
Definition at line 885 of file aged_ordered_container.h.
     {
         for (; first != last; ++first)
             insert (cend(), *first);
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> void beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::insert (std::initializer_list< value_type > init) inline
Definition at line 892 of file aged_ordered_container.h.
     {
         insert (init.begin(), init.end());
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> iterator beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::iterator_to (value_type & value) inline
Definition at line 733 of file aged_ordered_container.h.
     {
         static_assert (std::is_standard_layout <element>::value,
             "must be standard layout");
         return m_cont.iterator_to (*reinterpret_cast <element*>(
              reinterpret_cast<uint8_t*>(&value)-((std::size_t)
                 std::addressof(((element*)0)->member))));
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> const_iterator beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::iterator_to (value_type const & value) const inline
Definition at line 743 of file aged_ordered_container.h.
     {
         static_assert (std::is_standard_layout <element>::value,
             "must be standard layout");
         return m_cont.iterator_to (*reinterpret_cast <element const*>(
              reinterpret_cast<uint8_t const*>(&value)-((std::size_t)
                 std::addressof(((element*)0)->member))));
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> key_compare beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::key_comp () const inline
Definition at line 1061 of file aged_ordered_container.h.
     {
         return m_config.compare();
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<class K > iterator beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::lower_bound (K const & k) inline
Definition at line 1021 of file aged_ordered_container.h.
     {
         return iterator (m_cont.lower_bound (k,
             std::cref (m_config.key_compare())));
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<class K > const_iterator beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::lower_bound (K const & k) const inline
Definition at line 1030 of file aged_ordered_container.h.
     {
         return const_iterator (m_cont.lower_bound (k,
             std::cref (m_config.key_compare())));
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> size_type beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::max_size () const inline noexcept
Definition at line 771 of file aged_ordered_container.h.
     {
         return m_config.max_size();
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<class... Args> element* beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::new_element (Args &&... args) inline private
Definition at line 378 of file aged_ordered_container.h.
     {
         element* const p (
             ElementAllocatorTraits::allocate (m_config.alloc(), 1));
         ElementAllocatorTraits::construct (m_config.alloc(),
             p, clock().now(), std::forward <Args> (args)...);
         return p;
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<bool OtherIsMulti, bool OtherIsMap, class OtherT , class OtherDuration , class OtherAllocator > bool beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::operator!= (aged_ordered_container< OtherIsMulti, OtherIsMap, Key, OtherT, OtherDuration, Compare, OtherAllocator > const & other) const inline
Definition at line 1104 of file aged_ordered_container.h.
     {
         return ! (this->operator== (other));
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<bool OtherIsMulti, bool OtherIsMap, class OtherT , class OtherDuration , class OtherAllocator > bool beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::operator< (aged_ordered_container< OtherIsMulti, OtherIsMap, Key, OtherT, OtherDuration, Compare, OtherAllocator > const & other) const inline
Definition at line 1120 of file aged_ordered_container.h.
     {
         value_compare const comp (value_comp ());
         return std::lexicographical_compare (
             cbegin(), cend(), other.cbegin(), other.cend(), comp);
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<bool OtherIsMulti, bool OtherIsMap, class OtherT , class OtherDuration , class OtherAllocator > bool beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::operator<= (aged_ordered_container< OtherIsMulti, OtherIsMap, Key, OtherT, OtherDuration, Compare, OtherAllocator > const & other) const inline
Definition at line 1138 of file aged_ordered_container.h.
     {
         return ! (other < *this);
     }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare , class Allocator > auto beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::operator= (aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator > const & other)
Definition at line 1386 of file aged_ordered_container.h.
 {
     if (this != &other)
     {
         clear();
         this->m_config = other.m_config;
         insert (other.begin(), other.end());
     }
     return *this;
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare , class Allocator > auto beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::operator= (aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator > && other)
Definition at line 1402 of file aged_ordered_container.h.
 {
     clear();
     this->m_config = std::move (other.m_config);
     insert (other.begin(), other.end());
     other.clear();
     return *this;
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare , class Allocator > auto beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::operator= (std::initializer_list< value_type > init)
Definition at line 1416 of file aged_ordered_container.h.
 {
     clear ();
     insert (init);
     return *this;
 }
template<bool IsMulti, bool IsMap, class Key, class T , class Duration , class Compare, class Allocator > template<bool OtherIsMulti, bool OtherIsMap, class OtherT , class OtherDuration , class OtherAllocator > bool beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::operator== (aged_ordered_container< OtherIsMulti, OtherIsMap, Key, OtherT, OtherDuration, Compare, OtherAllocator > const & other) const
Definition at line 1819 of file aged_ordered_container.h.
References std::detail::equal(), and lhs.
Referenced by beast::detail::aged_ordered_container< beast::IP::Address >::operator!=().
 {
     typedef aged_ordered_container <OtherIsMulti, OtherIsMap,
         Key, OtherT, OtherDuration, Compare,
             OtherAllocator> Other;
     if (size() != other.size())
         return false;
     std::equal_to <void> eq;
     return std::equal (cbegin(), cend(), other.cbegin(), other.cend(),
         [&eq, &other](value_type const& lhs,
             typename Other::value_type const& rhs)
         {
             return eq (extract (lhs), other.extract (rhs));
         });
 }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<bool OtherIsMulti, bool OtherIsMap, class OtherT , class OtherDuration , class OtherAllocator > bool beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::operator> (aged_ordered_container< OtherIsMulti, OtherIsMap, Key, OtherT, OtherDuration, Compare, OtherAllocator > const & other) const inline
Definition at line 1154 of file aged_ordered_container.h.
     {
         return other < *this;
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<bool OtherIsMulti, bool OtherIsMap, class OtherT , class OtherDuration , class OtherAllocator > bool beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::operator>= (aged_ordered_container< OtherIsMulti, OtherIsMap, Key, OtherT, OtherDuration, Compare, OtherAllocator > const & other) const inline
Definition at line 1170 of file aged_ordered_container.h.
     {
         return ! (*this < other);
     }
template<bool IsMulti, bool IsMap, class Key, class T , class Duration , class Compare , class Allocator > template<bool maybe_multi, bool maybe_map, class > std::conditional< IsMap, T, void * >::type & beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::operator[] (Key const & key)
Definition at line 1459 of file aged_ordered_container.h.
References beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::element::value.
 {
     typename cont_type::insert_commit_data d;
     auto const result (m_cont.insert_check (key,
         std::cref (m_config.key_compare()), d));
     if (result.second)
     {
         element* const p (new_element (
             std::piecewise_construct, std::forward_as_tuple (key),
                 std::forward_as_tuple ()));
         chronological.list.push_back (*p);
         m_cont.insert_commit (*p, d);
         return p->value.second;
     }
     return result.first->value.second;
 }
template<bool IsMulti, bool IsMap, class Key, class T , class Duration , class Compare , class Allocator > template<bool maybe_multi, bool maybe_map, class > std::conditional< IsMap, T, void * >::type & beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::operator[] (Key && key)
Definition at line 1481 of file aged_ordered_container.h.
References beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::element::value.
 {
     typename cont_type::insert_commit_data d;
     auto const result (m_cont.insert_check (key,
         std::cref (m_config.key_compare()), d));
     if (result.second)
     {
         element* const p (new_element (
             std::piecewise_construct,
                 std::forward_as_tuple (std::move (key)),
                     std::forward_as_tuple ()));
         chronological.list.push_back (*p);
         m_cont.insert_commit (*p, d);
         return p->value.second;
     }
     return result.first->value.second;
 }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> reverse_iterator beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::rbegin () inline
Definition at line 697 of file aged_ordered_container.h.
     {
         return reverse_iterator (m_cont.rbegin());
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> const_reverse_iterator beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::rbegin () const inline
Definition at line 703 of file aged_ordered_container.h.
     {
         return const_reverse_iterator (m_cont.rbegin ());
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> reverse_iterator beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::rend () inline
Definition at line 715 of file aged_ordered_container.h.
     {
         return reverse_iterator (m_cont.rend ());
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> const_reverse_iterator beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::rend () const inline
Definition at line 721 of file aged_ordered_container.h.
     {
         return const_reverse_iterator (m_cont.rend ());
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> size_type beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::size () const inline noexcept
Definition at line 765 of file aged_ordered_container.h.
Referenced by ripple::PeerFinder::Livecache< class >::size().
     {
         return m_cont.size();
     }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare , class Allocator > void beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::swap (aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator > & other) noexcept
Definition at line 1783 of file aged_ordered_container.h.
References beast::asio::swap().
 {
     swap_data (other);
     std::swap (chronological, other.chronological);
     std::swap (m_cont, other.m_cont);
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare , class Allocator > template<bool maybe_propagate> std::enable_if< maybe_propagate >::type beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::swap_data (aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator > & other) private noexcept
Definition at line 1860 of file aged_ordered_container.h.
References beast::asio::swap().
 {
     std::swap (m_config.key_compare(), other.m_config.key_compare());
     std::swap (m_config.alloc(), other.m_config.alloc());
     std::swap (m_config.clock, other.m_config.clock);
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare , class Allocator > template<bool maybe_propagate> std::enable_if<!maybe_propagate >::type beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::swap_data (aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator > & other) private noexcept
Definition at line 1872 of file aged_ordered_container.h.
References beast::asio::swap().
 {
     std::swap (m_config.key_compare(), other.m_config.key_compare());
     std::swap (m_config.clock, other.m_config.clock);
 }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<bool is_const, class Iterator , class Base > void beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::touch (detail::aged_container_iterator< is_const, Iterator, Base > const & pos) inline
Definition at line 953 of file aged_ordered_container.h.
Referenced by ripple::PeerFinder::Logic::squelch_slots(), and beast::detail::aged_ordered_container< beast::IP::Address >::touch().
     {
         touch (pos, clock().now());
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<class K > size_type beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::touch (K const & k)
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare , class Allocator > template<bool is_const, class Iterator , class Base > void beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::touch (detail::aged_container_iterator< is_const, Iterator, Base > const & pos, typename clock_type::time_point const & now) private
Definition at line 1845 of file aged_ordered_container.h.
References beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::erase().
 {
     auto& e (*pos.iterator());
     e.when = now;
     chronological.list.erase (chronological.list.iterator_to (e));
     chronological.list.push_back (e);
 }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<class K> auto beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::touch (K const & k) -> size_type
Definition at line 1797 of file aged_ordered_container.h.
 {
     auto const now (clock().now());
     size_type n (0);
     auto const range (equal_range (k));
     for (auto iter : range)
     {
         touch (iter, now);
         ++n;
     }
     return n;
 }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> void beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::unlink_and_delete_element (element * p) inline private
Definition at line 393 of file aged_ordered_container.h.
     {
         chronological.list.erase (
             chronological.list.iterator_to (*p));
         m_cont.erase (m_cont.iterator_to (*p));
         delete_element (p);
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<class K > iterator beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::upper_bound (K const & k) inline
Definition at line 1039 of file aged_ordered_container.h.
     {
         return iterator (m_cont.upper_bound (k,
             std::cref (m_config.key_compare())));
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> template<class K > const_iterator beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::upper_bound (K const & k) const inline
Definition at line 1048 of file aged_ordered_container.h.
     {
         return const_iterator (m_cont.upper_bound (k,
             std::cref (m_config.key_compare())));
     }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> value_compare beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::value_comp () const inline
Definition at line 1068 of file aged_ordered_container.h.
Referenced by beast::detail::aged_ordered_container< beast::IP::Address >::operator<().
     {
         return value_compare (m_config.compare());
     }
Member Data Documentation
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> class beast::detail::aged_ordered_container::chronological_t beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::chronological
Referenced by beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::aged_ordered_container(), and beast::detail::aged_ordered_container< beast::IP::Address >::unlink_and_delete_element().
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> config_t beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::m_config private
Definition at line 1196 of file aged_ordered_container.h.
Referenced by beast::detail::aged_ordered_container< beast::IP::Address >::clock(), beast::detail::aged_ordered_container< beast::IP::Address >::count(), beast::detail::aged_ordered_container< beast::IP::Address >::delete_element(), beast::detail::aged_ordered_container< beast::IP::Address >::equal_range(), beast::detail::aged_ordered_container< beast::IP::Address >::find(), beast::detail::aged_ordered_container< beast::IP::Address >::get_allocator(), beast::detail::aged_ordered_container< beast::IP::Address >::key_comp(), beast::detail::aged_ordered_container< beast::IP::Address >::lower_bound(), beast::detail::aged_ordered_container< beast::IP::Address >::max_size(), beast::detail::aged_ordered_container< beast::IP::Address >::new_element(), beast::detail::aged_ordered_container< beast::IP::Address >::upper_bound(), and beast::detail::aged_ordered_container< beast::IP::Address >::value_comp().
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> cont_type beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::m_cont mutable private
Definition at line 1197 of file aged_ordered_container.h.
Referenced by beast::detail::aged_ordered_container< beast::IP::Address >::begin(), beast::detail::aged_ordered_container< beast::IP::Address >::cbegin(), beast::detail::aged_ordered_container< beast::IP::Address >::cend(), beast::detail::aged_ordered_container< beast::IP::Address >::count(), beast::detail::aged_ordered_container< beast::IP::Address >::crbegin(), beast::detail::aged_ordered_container< beast::IP::Address >::crend(), beast::detail::aged_ordered_container< beast::IP::Address >::empty(), beast::detail::aged_ordered_container< beast::IP::Address >::end(), beast::detail::aged_ordered_container< beast::IP::Address >::equal_range(), beast::detail::aged_ordered_container< beast::IP::Address >::find(), beast::detail::aged_ordered_container< beast::IP::Address >::iterator_to(), beast::detail::aged_ordered_container< beast::IP::Address >::lower_bound(), beast::detail::aged_ordered_container< beast::IP::Address >::rbegin(), beast::detail::aged_ordered_container< beast::IP::Address >::rend(), beast::detail::aged_ordered_container< beast::IP::Address >::size(), beast::detail::aged_ordered_container< beast::IP::Address >::unlink_and_delete_element(), and beast::detail::aged_ordered_container< beast::IP::Address >::upper_bound().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/container/detail/aged_ordered_container.h