rippled: ripple::CKey Class Reference
ripple::CKey Class Reference
#include <CKey.h>
Public Types
typedef boost::shared_ptr< CKey > pointer
Public Member Functions
CKey ()
CKey (const CKey &b)
CKey & operator= (const CKey &b)
~CKey ()
CKey (const uint128 &passPhrase)
CKey (const RippleAddress &generator, int n)
CKey (const RippleAddress &base, const BIGNUM *rootPrivKey, int n)
CKey (uint256 const &privateKey)
bool IsNull () const
void MakeNewKey ()
BIGNUM * GetSecretBN () const
void GetPrivateKeyU (uint256 &privKey)
bool SetPrivateKeyU (uint256 const &key, bool bThrow=false)
bool SetPubKey (const void *ptr, size_t len)
bool SetPubKey (Blob const &vchPubKey)
bool SetPubKey (const std::string &pubKey)
Blob GetPubKey () const
bool Sign (uint256 const &hash, Blob &vchSig)
bool Verify (uint256 const &hash, const void *sig, size_t sigLen) const
bool Verify (uint256 const &hash, Blob const &vchSig) const
bool Verify (uint256 const &hash, const std::string &sig) const
void getECIESSecret (CKey &otherKey, uint256 &enc_key, uint256 &hmac_key)
Blob encryptECIES (CKey &otherKey, Blob const &plaintext)
Blob decryptECIES (CKey &otherKey, Blob const &ciphertext)
Static Public Member Functions
static uint128 PassPhraseToKey (const std::string &passPhrase)
static EC_KEY * GenerateRootDeterministicKey (const uint128 &passPhrase)
static EC_KEY * GenerateRootPubKey (BIGNUM *pubGenerator)
static EC_KEY * GeneratePublicDeterministicKey (const RippleAddress &generator, int n)
static EC_KEY * GeneratePrivateDeterministicKey (const RippleAddress &family, const BIGNUM *rootPriv, int n)
static EC_KEY * GeneratePrivateDeterministicKey (const RippleAddress &family, uint256 const &rootPriv, int n)
Protected Attributes
EC_KEY * pkey
bool fSet
Detailed Description
Definition at line 85 of file CKey.h.
Member Typedef Documentation
typedef boost::shared_ptr<CKey> ripple::CKey::pointer
Definition at line 93 of file CKey.h.
Constructor & Destructor Documentation
ripple::CKey::CKey () inline
Definition at line 95 of file CKey.h.
References fSet, and pkey.
     {
         pkey = EC_KEY_new_by_curve_name (NID_secp256k1);
         if (pkey == nullptr)
             throw key_error ("CKey::CKey() : EC_KEY_new_by_curve_name failed");
         EC_KEY_set_conv_form (pkey, POINT_CONVERSION_COMPRESSED);
         fSet = false;
     }
ripple::CKey::CKey (const CKey & b) inline
Definition at line 107 of file CKey.h.
References fSet, and pkey.
     {
         pkey = EC_KEY_dup (b.pkey);
         if (pkey == nullptr)
             throw key_error ("CKey::CKey(const CKey&) : EC_KEY_dup failed");
         EC_KEY_set_conv_form (pkey, POINT_CONVERSION_COMPRESSED);
         fSet = b.fSet;
     }
ripple::CKey::~CKey () inline
Definition at line 129 of file CKey.h.
References pkey.
     {
         EC_KEY_free (pkey);
     }
ripple::CKey::CKey (const uint128 & passPhrase) inline
Definition at line 142 of file CKey.h.
References fSet, GenerateRootDeterministicKey(), and pkey.
                                      : fSet (false)
     {
         pkey = GenerateRootDeterministicKey (passPhrase);
         fSet = true;
         assert (pkey);
     }
ripple::CKey::CKey (const RippleAddress & generator, int n) inline
Definition at line 149 of file CKey.h.
References fSet, GeneratePublicDeterministicKey(), and pkey.
                                                  : fSet (false)
     {
         // public deterministic key
         pkey = GeneratePublicDeterministicKey (generator, n);
         fSet = true;
         assert (pkey);
     }
ripple::CKey::CKey (const RippleAddress & base, const BIGNUM * rootPrivKey, int n) inline
Definition at line 157 of file CKey.h.
References fSet, GeneratePrivateDeterministicKey(), and pkey.
                                                                        : fSet (false)
     {
         // private deterministic key
         pkey = GeneratePrivateDeterministicKey (base, rootPrivKey, n);
         fSet = true;
         assert (pkey);
     }
ripple::CKey::CKey (uint256 const & privateKey) inline
Definition at line 165 of file CKey.h.
References SetPrivateKeyU().
                                      : pkey (nullptr), fSet (false)
     {
         // XXX Broken pkey is null.
         SetPrivateKeyU (privateKey);
     }
Member Function Documentation
Blob ripple::CKey::decryptECIES (CKey & otherKey, Blob const & ciphertext)
Definition at line 204 of file CKeyECIES.cpp.
References ECIES_ENC_ALGO, ECIES_ENC_BLK_SIZE, ECIES_ENC_IV_TYPE, ECIES_ENC_KEY_TYPE, ECIES_HMAC_KEY_TYPE, ECIES_HMAC_SIZE, ECIES_HMAC_TYPE, getECIESSecret(), and ripple::makeHMAC().
Referenced by ripple::RippleAddress::accountPrivateDecrypt(), and ripple::checkECIES().
 {
     // minimum ciphertext = IV + HMAC + 1 block
     if (ciphertext.size () < ((2 * ECIES_ENC_BLK_SIZE) + ECIES_HMAC_SIZE) )
         throw std::runtime_error ("ciphertext too short");
     // extract IV
     ECIES_ENC_IV_TYPE iv;
     memcpy (iv.begin (), & (ciphertext.front ()), ECIES_ENC_BLK_SIZE);
     // begin decrypting
     EVP_CIPHER_CTX ctx;
     EVP_CIPHER_CTX_init (&ctx);
     ECIES_ENC_KEY_TYPE secret;
     ECIES_HMAC_KEY_TYPE hmacKey;
     getECIESSecret (otherKey, secret, hmacKey);
     if (EVP_DecryptInit_ex (&ctx, ECIES_ENC_ALGO, nullptr, secret.begin (), iv.begin ()) != 1)
     {
         secret.zero ();
         hmacKey.zero ();
         EVP_CIPHER_CTX_cleanup (&ctx);
         throw std::runtime_error ("unable to init cipher");
     }
     // decrypt mac
     ECIES_HMAC_TYPE hmac;
     int outlen = ECIES_HMAC_SIZE;
     if ( (EVP_DecryptUpdate (&ctx, hmac.begin (), &outlen,
                              & (ciphertext.front ()) + ECIES_ENC_BLK_SIZE, ECIES_HMAC_SIZE + 1) != 1) || (outlen != ECIES_HMAC_SIZE) )
     {
         secret.zero ();
         hmacKey.zero ();
         EVP_CIPHER_CTX_cleanup (&ctx);
         throw std::runtime_error ("unable to extract hmac");
     }
     // decrypt plaintext (after IV and encrypted mac)
     Blob plaintext (ciphertext.size () - ECIES_HMAC_SIZE - ECIES_ENC_BLK_SIZE);
     outlen = plaintext.size ();
     if (EVP_DecryptUpdate (&ctx, & (plaintext.front ()), &outlen,
                            & (ciphertext.front ()) + ECIES_ENC_BLK_SIZE + ECIES_HMAC_SIZE + 1,
                            ciphertext.size () - ECIES_ENC_BLK_SIZE - ECIES_HMAC_SIZE - 1) != 1)
     {
         secret.zero ();
         hmacKey.zero ();
         EVP_CIPHER_CTX_cleanup (&ctx);
         throw std::runtime_error ("unable to extract plaintext");
     }
     // decrypt padding
     int flen = 0;
     if (EVP_DecryptFinal (&ctx, & (plaintext.front ()) + outlen, &flen) != 1)
     {
         secret.zero ();
         hmacKey.zero ();
         EVP_CIPHER_CTX_cleanup (&ctx);
         throw std::runtime_error ("plaintext had bad padding");
     }
     plaintext.resize (flen + outlen);
     // verify integrity
     if (hmac != makeHMAC (hmacKey, plaintext))
     {
         secret.zero ();
         hmacKey.zero ();
         EVP_CIPHER_CTX_cleanup (&ctx);
         throw std::runtime_error ("plaintext had bad hmac");
     }
     secret.zero ();
     hmacKey.zero ();
     EVP_CIPHER_CTX_cleanup (&ctx);
     return plaintext;
 }
Blob ripple::CKey::encryptECIES (CKey & otherKey, Blob const & plaintext)
Definition at line 129 of file CKeyECIES.cpp.
References ECIES_ENC_ALGO, ECIES_ENC_BLK_SIZE, ECIES_ENC_IV_TYPE, ECIES_ENC_KEY_SIZE, ECIES_ENC_KEY_TYPE, ECIES_HMAC_KEY_TYPE, ECIES_HMAC_SIZE, ECIES_HMAC_TYPE, ripple::RandomNumbers::fillBytes(), getECIESSecret(), ripple::RandomNumbers::getInstance(), and ripple::makeHMAC().
Referenced by ripple::RippleAddress::accountPrivateEncrypt(), and ripple::checkECIES().
 {
     ECIES_ENC_IV_TYPE iv;
     RandomNumbers::getInstance ().fillBytes (iv.begin (), ECIES_ENC_BLK_SIZE);
     ECIES_ENC_KEY_TYPE secret;
     ECIES_HMAC_KEY_TYPE hmacKey;
     getECIESSecret (otherKey, secret, hmacKey);
     ECIES_HMAC_TYPE hmac = makeHMAC (hmacKey, plaintext);
     hmacKey.zero ();
     EVP_CIPHER_CTX ctx;
     EVP_CIPHER_CTX_init (&ctx);
     if (EVP_EncryptInit_ex (&ctx, ECIES_ENC_ALGO, nullptr, secret.begin (), iv.begin ()) != 1)
     {
         EVP_CIPHER_CTX_cleanup (&ctx);
         secret.zero ();
         throw std::runtime_error ("init cipher ctx");
     }
     secret.zero ();
     Blob out (plaintext.size () + ECIES_HMAC_SIZE + ECIES_ENC_KEY_SIZE + ECIES_ENC_BLK_SIZE, 0);
     int len = 0, bytesWritten;
     // output IV
     memcpy (& (out.front ()), iv.begin (), ECIES_ENC_BLK_SIZE);
     len = ECIES_ENC_BLK_SIZE;
     // Encrypt/output HMAC
     bytesWritten = out.capacity () - len;
     assert (bytesWritten > 0);
     if (EVP_EncryptUpdate (&ctx, & (out.front ()) + len, &bytesWritten, hmac.begin (), ECIES_HMAC_SIZE) < 0)
     {
         EVP_CIPHER_CTX_cleanup (&ctx);
         throw std::runtime_error ("");
     }
     len += bytesWritten;
     // encrypt/output plaintext
     bytesWritten = out.capacity () - len;
     assert (bytesWritten > 0);
     if (EVP_EncryptUpdate (&ctx, & (out.front ()) + len, &bytesWritten, & (plaintext.front ()), plaintext.size ()) < 0)
     {
         EVP_CIPHER_CTX_cleanup (&ctx);
         throw std::runtime_error ("");
     }
     len += bytesWritten;
     // finalize
     bytesWritten = out.capacity () - len;
     if (EVP_EncryptFinal_ex (&ctx, & (out.front ()) + len, &bytesWritten) < 0)
     {
         EVP_CIPHER_CTX_cleanup (&ctx);
         throw std::runtime_error ("encryption error");
     }
     len += bytesWritten;
     // Output contains: IV, encrypted HMAC, encrypted data, encrypted padding
     assert (len <= (plaintext.size () + ECIES_HMAC_SIZE + (2 * ECIES_ENC_BLK_SIZE)));
     assert (len >= (plaintext.size () + ECIES_HMAC_SIZE + ECIES_ENC_BLK_SIZE)); // IV, HMAC, data
     out.resize (len);
     EVP_CIPHER_CTX_cleanup (&ctx);
     return out;
 }
EC_KEY * ripple::CKey::GeneratePrivateDeterministicKey (const RippleAddress & family, const BIGNUM * rootPriv, int n) static
Definition at line 286 of file CKeyDeterministic.cpp.
References ripple::makeHash(), and pkey.
Referenced by CKey(), and GeneratePrivateDeterministicKey().
 {
     // privateKey(n) = (rootPrivateKey + Hash(pubHash|seq)) % order
     BN_CTX* ctx = BN_CTX_new ();
     if (ctx == nullptr) return nullptr;
     EC_KEY* pkey = EC_KEY_new_by_curve_name (NID_secp256k1);
     if (pkey == nullptr)
     {
         BN_CTX_free (ctx);
         return nullptr;
     }
     EC_KEY_set_conv_form (pkey, POINT_CONVERSION_COMPRESSED);
     BIGNUM* order = BN_new ();
     if (order == nullptr)
     {
         BN_CTX_free (ctx);
         EC_KEY_free (pkey);
         return nullptr;
     }
     if (!EC_GROUP_get_order (EC_KEY_get0_group (pkey), order, ctx))
     {
         BN_free (order);
         BN_CTX_free (ctx);
         EC_KEY_free (pkey);
         return nullptr;
     }
     // calculate the private additional key
     BIGNUM* privKey = makeHash (pubGen, seq, order);
     if (privKey == nullptr)
     {
         BN_free (order);
         BN_CTX_free (ctx);
         EC_KEY_free (pkey);
         return nullptr;
     }
     // calculate the final private key
     BN_mod_add (privKey, privKey, rootPrivKey, order, ctx);
     BN_free (order);
     EC_KEY_set_private_key (pkey, privKey);
     // compute the corresponding public key
     EC_POINT* pubKey = EC_POINT_new (EC_KEY_get0_group (pkey));
     if (!pubKey)
     {
         BN_clear_free (privKey);
         BN_CTX_free (ctx);
         EC_KEY_free (pkey);
         return nullptr;
     }
     if (EC_POINT_mul (EC_KEY_get0_group (pkey), pubKey, privKey, nullptr, nullptr, ctx) == 0)
     {
         BN_clear_free (privKey);
         EC_POINT_free (pubKey);
         EC_KEY_free (pkey);
         BN_CTX_free (ctx);
         return nullptr;
     }
     BN_clear_free (privKey);
     EC_KEY_set_public_key (pkey, pubKey);
     EC_POINT_free (pubKey);
     BN_CTX_free (ctx);
     return pkey;
 }
EC_KEY * ripple::CKey::GeneratePrivateDeterministicKey (const RippleAddress & family, uint256 const & rootPriv, int n) static
Definition at line 279 of file CKeyDeterministic.cpp.
References GeneratePrivateDeterministicKey().
 {
     CBigNum bn (u);
     return GeneratePrivateDeterministicKey (pubGen, static_cast<BIGNUM*> (&bn), seq);
 }
EC_KEY * ripple::CKey::GeneratePublicDeterministicKey (const RippleAddress & generator, int n) static
Definition at line 214 of file CKeyDeterministic.cpp.
References GenerateRootPubKey(), ripple::RippleAddress::getGeneratorBN(), hash, ripple::makeHash(), and pkey.
Referenced by CKey().
 {
     // publicKey(n) = rootPublicKey EC_POINT_+ Hash(pubHash|seq)*point
     EC_KEY*         rootKey     = CKey::GenerateRootPubKey (pubGen.getGeneratorBN ());
     const EC_POINT* rootPubKey  = EC_KEY_get0_public_key (rootKey);
     BN_CTX*         ctx         = BN_CTX_new ();
     EC_KEY*         pkey        = EC_KEY_new_by_curve_name (NID_secp256k1);
     EC_POINT*       newPoint    = 0;
     BIGNUM*         order       = 0;
     BIGNUM*         hash        = 0;
     bool            success     = true;
     if (!ctx || !pkey)  success = false;
     if (success)
         EC_KEY_set_conv_form (pkey, POINT_CONVERSION_COMPRESSED);
     if (success)
     {
         newPoint    = EC_POINT_new (EC_KEY_get0_group (pkey));
         if (!newPoint)   success = false;
     }
     if (success)
     {
         order       = BN_new ();
         if (!order || !EC_GROUP_get_order (EC_KEY_get0_group (pkey), order, ctx))
             success = false;
     }
     // Calculate the private additional key.
     if (success)
     {
         hash        = makeHash (pubGen, seq, order);
         if (!hash)   success = false;
     }
     if (success)
     {
         // Calculate the corresponding public key.
         EC_POINT_mul (EC_KEY_get0_group (pkey), newPoint, hash, nullptr, nullptr, ctx);
         // Add the master public key and set.
         EC_POINT_add (EC_KEY_get0_group (pkey), newPoint, newPoint, rootPubKey, ctx);
         EC_KEY_set_public_key (pkey, newPoint);
     }
     if (order)              BN_free (order);
     if (hash)               BN_free (hash);
     if (newPoint)           EC_POINT_free (newPoint);
     if (ctx)                BN_CTX_free (ctx);
     if (rootKey)            EC_KEY_free (rootKey);
     if (pkey && !success)   EC_KEY_free (pkey);
     return success ? pkey : nullptr;
 }
EC_KEY * ripple::CKey::GenerateRootDeterministicKey (const uint128 & passPhrase) static
Definition at line 42 of file CKeyDeterministic.cpp.
References ripple::Serializer::add128(), ripple::Serializer::add32(), ripple::Serializer::getSHA512Half(), pkey, ripple::Serializer::secureErase(), and ripple::base_uint< BITS >::zero().
Referenced by CKey().
 {
     BN_CTX* ctx = BN_CTX_new ();
     if (!ctx) return nullptr;
     EC_KEY* pkey = EC_KEY_new_by_curve_name (NID_secp256k1);
     if (!pkey)
     {
         BN_CTX_free (ctx);
         return nullptr;
     }
     EC_KEY_set_conv_form (pkey, POINT_CONVERSION_COMPRESSED);
     BIGNUM* order = BN_new ();
     if (!order)
     {
         BN_CTX_free (ctx);
         EC_KEY_free (pkey);
         return nullptr;
     }
     if (!EC_GROUP_get_order (EC_KEY_get0_group (pkey), order, ctx))
     {
         assert (false);
         BN_free (order);
         EC_KEY_free (pkey);
         BN_CTX_free (ctx);
         return nullptr;
     }
     BIGNUM* privKey = nullptr;
     int seq = 0;
     do
     {
         // private key must be non-zero and less than the curve's order
         Serializer s ((128 + 32) / 8);
         s.add128 (seed);
         s.add32 (seq++);
         uint256 root = s.getSHA512Half ();
         s.secureErase ();
         privKey = BN_bin2bn ((const unsigned char*) &root, sizeof (root), privKey);
         if (privKey == nullptr)
         {
             EC_KEY_free (pkey);
             BN_free (order);
             BN_CTX_free (ctx);
         }
         root.zero ();
     }
     while (BN_is_zero (privKey) || (BN_cmp (privKey, order) >= 0));
     BN_free (order);
     if (!EC_KEY_set_private_key (pkey, privKey))
     {
         // set the random point as the private key
         assert (false);
         EC_KEY_free (pkey);
         BN_clear_free (privKey);
         BN_CTX_free (ctx);
         return nullptr;
     }
     EC_POINT* pubKey = EC_POINT_new (EC_KEY_get0_group (pkey));
     if (!EC_POINT_mul (EC_KEY_get0_group (pkey), pubKey, privKey, nullptr, nullptr, ctx))
     {
         // compute the corresponding public key point
         assert (false);
         BN_clear_free (privKey);
         EC_POINT_free (pubKey);
         EC_KEY_free (pkey);
         BN_CTX_free (ctx);
         return nullptr;
     }
     BN_clear_free (privKey);
     if (!EC_KEY_set_public_key (pkey, pubKey))
     {
         assert (false);
         EC_POINT_free (pubKey);
         EC_KEY_free (pkey);
         BN_CTX_free (ctx);
         return nullptr;
     }
     EC_POINT_free (pubKey);
     BN_CTX_free (ctx);
 #ifdef EC_DEBUG
     assert (EC_KEY_check_key (pkey) == 1); // CAUTION: This check is *very* expensive
 #endif
     return pkey;
 }
EC_KEY * ripple::CKey::GenerateRootPubKey (BIGNUM * pubGenerator) static
Definition at line 149 of file CKeyDeterministic.cpp.
References pkey.
Referenced by GeneratePublicDeterministicKey().
 {
     if (pubGenerator == nullptr)
     {
         assert (false);
         return nullptr;
     }
     EC_KEY* pkey = EC_KEY_new_by_curve_name (NID_secp256k1);
     if (!pkey)
     {
         BN_free (pubGenerator);
         return nullptr;
     }
     EC_KEY_set_conv_form (pkey, POINT_CONVERSION_COMPRESSED);
     EC_POINT* pubPoint = EC_POINT_bn2point (EC_KEY_get0_group (pkey), pubGenerator, nullptr, nullptr);
     BN_free (pubGenerator);
     if (!pubPoint)
     {
         assert (false);
         EC_KEY_free (pkey);
         return nullptr;
     }
     if (!EC_KEY_set_public_key (pkey, pubPoint))
     {
         assert (false);
         EC_POINT_free (pubPoint);
         EC_KEY_free (pkey);
         return nullptr;
     }
     EC_POINT_free (pubPoint);
     return pkey;
 }
void ripple::CKey::getECIESSecret (CKey & otherKey, uint256 & enc_key, uint256 & hmac_key)
Definition at line 61 of file CKeyECIES.cpp.
References ECIES_ENC_KEY_SIZE, ECIES_HMAC_KEY_SIZE, ECIES_KEY_HASH, ECIES_KEY_LENGTH, ECIES_MIN_SEC, and pkey.
Referenced by decryptECIES(), and encryptECIES().
 {
     // Retrieve a secret generated from an EC key pair. At least one private key must be known.
     if (!pkey || !otherKey.pkey)
         throw std::runtime_error ("missing key");
     EC_KEY* pubkey, *privkey;
     if (EC_KEY_get0_private_key (pkey))
     {
         privkey = pkey;
         pubkey = otherKey.pkey;
     }
     else if (EC_KEY_get0_private_key (otherKey.pkey))
     {
         privkey = otherKey.pkey;
         pubkey = pkey;
     }
     else throw std::runtime_error ("no private key");
     unsigned char rawbuf[512];
     int buflen = ECDH_compute_key (rawbuf, 512, EC_KEY_get0_public_key (pubkey), privkey, nullptr);
     if (buflen < ECIES_MIN_SEC)
         throw std::runtime_error ("ecdh key failed");
     unsigned char hbuf[ECIES_KEY_LENGTH];
     ECIES_KEY_HASH (rawbuf, buflen, hbuf);
     memset (rawbuf, 0, ECIES_HMAC_KEY_SIZE);
     assert ((ECIES_ENC_KEY_SIZE + ECIES_HMAC_KEY_SIZE) >= ECIES_KEY_LENGTH);
     memcpy (enc_key.begin (), hbuf, ECIES_ENC_KEY_SIZE);
     memcpy (hmac_key.begin (), hbuf + ECIES_ENC_KEY_SIZE, ECIES_HMAC_KEY_SIZE);
     memset (hbuf, 0, ECIES_KEY_LENGTH);
 }
void ripple::CKey::GetPrivateKeyU (uint256 & privKey) inline
Definition at line 204 of file CKey.h.
References ripple::base_uint< BITS >::begin(), pkey, ripple::base_uint< BITS >::size(), and ripple::base_uint< BITS >::zero().
Referenced by ripple::RippleAddress::createNodePrivate(), and ripple::CKey_test::run().
     {
         const BIGNUM* bn = EC_KEY_get0_private_key (pkey);
         if (bn == nullptr)
             throw key_error ("CKey::GetPrivateKeyU: EC_KEY_get0_private_key failed");
         privKey.zero ();
         BN_bn2bin (bn, privKey.begin () + (privKey.size () - BN_num_bytes (bn)));
     }
Blob ripple::CKey::GetPubKey () const inline
Definition at line 257 of file CKey.h.
References pkey.
Referenced by ripple::checkECIES(), ripple::RippleAddress::createAccountPublic(), and ripple::RippleAddress::setAccountPublic().
     {
         unsigned int nSize = i2o_ECPublicKey (pkey, nullptr);
         assert (nSize <= 33);
         if (!nSize)
             throw key_error ("CKey::GetPubKey() : i2o_ECPublicKey failed");
         Blob vchPubKey (33, 0);
         unsigned char* pbegin = &vchPubKey[0];
         if (i2o_ECPublicKey (pkey, &pbegin) != nSize)
             throw key_error ("CKey::GetPubKey() : i2o_ECPublicKey returned unexpected size");
         assert (vchPubKey.size () <= 33);
         return vchPubKey;
     }
BIGNUM* ripple::CKey::GetSecretBN () const inline
Definition at line 198 of file CKey.h.
References pkey.
Referenced by ripple::RippleAddress::setAccountPrivate().
     {
         // DEPRECATED
         return BN_dup (EC_KEY_get0_private_key (pkey));
     }
bool ripple::CKey::IsNull () const inline
Definition at line 183 of file CKey.h.
References fSet.
     {
         return !fSet;
     }
void ripple::CKey::MakeNewKey () inline
Definition at line 188 of file CKey.h.
References fSet, and pkey.
Referenced by ripple::checkECIES().
     {
         if (!EC_KEY_generate_key (pkey))
             throw key_error ("CKey::MakeNewKey() : EC_KEY_generate_key failed");
         EC_KEY_set_conv_form (pkey, POINT_CONVERSION_COMPRESSED);
         fSet = true;
     }
CKey& ripple::CKey::operator= (const CKey & b) inline
Definition at line 119 of file CKey.h.
References fSet, and pkey.
     {
         if (!EC_KEY_copy (pkey, b.pkey))
             throw key_error ("CKey::operator=(const CKey&) : EC_KEY_copy failed");
         fSet = b.fSet;
         return (*this);
     }
uint128 ripple::CKey::PassPhraseToKey (const std::string & passPhrase) static
Definition at line 27 of file CKeyDeterministic.cpp.
References ripple::Serializer::addRaw(), ripple::Serializer::getSHA512Half(), ripple::uint128::low128(), and ripple::Serializer::secureErase().
Referenced by ripple::RippleAddress::setSeedGeneric().
 {
     Serializer s;
     s.addRaw (passPhrase);
     uint256 hash256 = s.getSHA512Half ();
     uint128 ret (uint128::low128(hash256));
     s.secureErase ();
     return ret;
 }
bool ripple::CKey::SetPrivateKeyU (uint256 const & key, bool bThrow = false) inline
Definition at line 215 of file CKey.h.
References ripple::base_uint< BITS >::begin(), fSet, pkey, and ripple::base_uint< BITS >::size().
Referenced by ripple::RippleAddress::accountPrivateDecrypt(), ripple::RippleAddress::accountPrivateEncrypt(), ripple::RippleAddress::accountPrivateSign(), CKey(), and ripple::RippleAddress::signNodePrivate().
     {
         // XXX Broken if pkey is not set.
         BIGNUM* bn          = BN_bin2bn (key.begin (), key.size (), nullptr);
         bool    bSuccess    = !!EC_KEY_set_private_key (pkey, bn);
         BN_clear_free (bn);
         if (bSuccess)
         {
             fSet = true;
         }
         else if (bThrow)
         {
             throw key_error ("CKey::SetPrivateKeyU: EC_KEY_set_private_key failed");
         }
         return bSuccess;
     }
bool ripple::CKey::SetPubKey (const void * ptr, size_t len) inline
Definition at line 235 of file CKey.h.
References fSet, and pkey.
Referenced by ripple::RippleAddress::accountPrivateDecrypt(), ripple::RippleAddress::accountPrivateEncrypt(), ripple::RippleAddress::accountPublicVerify(), ripple::checkECIES(), SetPubKey(), and ripple::RippleAddress::verifyNodePublic().
     {
         const unsigned char* pbegin = static_cast<const unsigned char*> (ptr);
         if (!o2i_ECPublicKey (&pkey, &pbegin, len))
             return false;
         EC_KEY_set_conv_form (pkey, POINT_CONVERSION_COMPRESSED);
         fSet = true;
         return true;
     }
bool ripple::CKey::SetPubKey (Blob const & vchPubKey) inline
Definition at line 247 of file CKey.h.
References SetPubKey().
     {
         return SetPubKey (&vchPubKey[0], vchPubKey.size ());
     }
bool ripple::CKey::SetPubKey (const std::string & pubKey) inline
Definition at line 252 of file CKey.h.
References SetPubKey().
     {
         return SetPubKey (pubKey.data (), pubKey.size ());
     }
bool ripple::CKey::Sign (uint256 const & hash, Blob & vchSig) inline
Definition at line 275 of file CKey.h.
References ripple::base_uint< BITS >::begin(), ripple::makeCanonicalECDSASig(), pkey, and ripple::base_uint< BITS >::size().
Referenced by ripple::RippleAddress::accountPrivateSign(), and ripple::RippleAddress::signNodePrivate().
     {
         unsigned char pchSig[128];
         unsigned int nSize = sizeof(pchSig)/sizeof(pchSig[0]) - 1;
         if (!ECDSA_sign (0, (unsigned char*)hash.begin (), hash.size (), pchSig, &nSize, pkey))
             return false;
         size_t len = nSize;
         makeCanonicalECDSASig (pchSig, len);
         vchSig.resize (len);
         memcpy (&vchSig[0], pchSig, len);
         return true;
     }
bool ripple::CKey::Verify (uint256 const & hash, const void * sig, size_t sigLen) const inline
Definition at line 291 of file CKey.h.
References ripple::base_uint< BITS >::begin(), pkey, and ripple::base_uint< BITS >::size().
Referenced by ripple::RippleAddress::accountPublicVerify(), Verify(), and ripple::RippleAddress::verifyNodePublic().
     {
         // -1 = error, 0 = bad sig, 1 = good
         if (ECDSA_verify (0, hash.begin (), hash.size (), (const unsigned char*) sig, sigLen, pkey) != 1)
             return false;
         return true;
     }
bool ripple::CKey::Verify (uint256 const & hash, Blob const & vchSig) const inline
Definition at line 300 of file CKey.h.
References ripple::base_uint< BITS >::size(), and Verify().
     {
         return Verify (hash, &vchSig[0], vchSig.size ());
     }
bool ripple::CKey::Verify (uint256 const & hash, const std::string & sig) const inline
Definition at line 305 of file CKey.h.
References ripple::base_uint< BITS >::data(), and Verify().
     {
         return Verify (hash, sig.data (), sig.size ());
     }
Member Data Documentation
bool ripple::CKey::fSet protected
Definition at line 89 of file CKey.h.
Referenced by CKey(), IsNull(), MakeNewKey(), operator=(), SetPrivateKeyU(), and SetPubKey().
EC_KEY* ripple::CKey::pkey protected
Definition at line 88 of file CKey.h.
Referenced by CKey(), GeneratePrivateDeterministicKey(), GeneratePublicDeterministicKey(), GenerateRootDeterministicKey(), GenerateRootPubKey(), getECIESSecret(), GetPrivateKeyU(), GetPubKey(), GetSecretBN(), MakeNewKey(), operator=(), SetPrivateKeyU(), SetPubKey(), Sign(), Verify(), and ~CKey().
The documentation for this class was generated from the following files:
rippled/src/ripple_data/crypto/CKey.h
rippled/src/ripple_data/crypto/CKeyDeterministic.cpp
rippled/src/ripple_data/crypto/CKeyECIES.cpp