rippled: rocksdb::Block::Iter Class Reference
rocksdb::Block::Iter Class Reference
Public Member Functions
Iter (const Comparator *comparator, const char *data, uint32_t restarts, uint32_t num_restarts)
virtual bool Valid () const
virtual Status status () const
virtual Slice key () const
virtual Slice value () const
virtual void Next ()
virtual void Prev ()
virtual void Seek (const Slice &target)
virtual void SeekToFirst ()
virtual void SeekToLast ()
Public Member Functions inherited from rocksdb::Iterator
Iterator ()
virtual ~Iterator ()
void RegisterCleanup (CleanupFunction function, void *arg1, void *arg2)
Private Member Functions
int Compare (const Slice &a, const Slice &b) const
uint32_t NextEntryOffset () const
uint32_t GetRestartPoint (uint32_t index)
void SeekToRestartPoint (uint32_t index)
void CorruptionError ()
bool ParseNextKey ()
Private Attributes
const Comparator *const comparator_
const char *const data_
uint32_t const restarts_
uint32_t const num_restarts_
uint32_t current_
uint32_t restart_index_
std::string key_
Slice value_
Status status_
Additional Inherited Members
Public Types inherited from rocksdb::Iterator
typedef void(* CleanupFunction)(void *arg1, void *arg2)
Detailed Description
Definition at line 82 of file block.cc.
Constructor & Destructor Documentation
rocksdb::Block::Iter::Iter (const Comparator * comparator, const char * data, uint32_t restarts, uint32_t num_restarts) inline
Definition at line 121 of file block.cc.
References num_restarts_.
       : comparator_(comparator),
         data_(data),
         restarts_(restarts),
         num_restarts_(num_restarts),
         current_(restarts_),
         restart_index_(num_restarts_) {
     assert(num_restarts_ > 0);
   }
Member Function Documentation
int rocksdb::Block::Iter::Compare (const Slice & a, const Slice & b) const inline private
Definition at line 96 of file block.cc.
References comparator_, and rocksdb::Comparator::Compare().
Referenced by Seek().
{
     return comparator_->Compare(a, b);
   }
void rocksdb::Block::Iter::CorruptionError () inline private
Definition at line 224 of file block.cc.
References rocksdb::Slice::clear(), rocksdb::Status::Corruption(), current_, key_, num_restarts_, restart_index_, restarts_, status_, and value_.
Referenced by ParseNextKey(), and Seek().
{
     current_ = restarts_;
     restart_index_ = num_restarts_;
     status_ = Status::Corruption("bad entry in block");
     key_.clear();
     value_.clear();
   }
uint32_t rocksdb::Block::Iter::GetRestartPoint (uint32_t index) inline private
Definition at line 105 of file block.cc.
References data_, rocksdb::DecodeFixed32(), num_restarts_, and restarts_.
Referenced by ParseNextKey(), Prev(), Seek(), and SeekToRestartPoint().
{
     assert(index < num_restarts_);
     return DecodeFixed32(data_ + restarts_ + index * sizeof(uint32_t));
   }
virtual Slice rocksdb::Block::Iter::key () const inline virtual
Implements rocksdb::Iterator.
Definition at line 136 of file block.cc.
References key_, and Valid().
{
     assert(Valid());
     return key_;
   }
virtual void rocksdb::Block::Iter::Next () inline virtual
Implements rocksdb::Iterator.
Definition at line 145 of file block.cc.
References ParseNextKey(), and Valid().
                       {
     assert(Valid());
     ParseNextKey();
   }
uint32_t rocksdb::Block::Iter::NextEntryOffset () const inline private
Definition at line 101 of file block.cc.
References rocksdb::Slice::data(), data_, rocksdb::Slice::size(), and value_.
Referenced by ParseNextKey(), Prev(), and SeekToLast().
{
     return (value_.data() + value_.size()) - data_;
   }
bool rocksdb::Block::Iter::ParseNextKey () inline private
Definition at line 232 of file block.cc.
References CorruptionError(), current_, data_, rocksdb::DecodeEntry(), GetRestartPoint(), key_, NextEntryOffset(), num_restarts_, restart_index_, restarts_, shared, and value_.
Referenced by Next(), Prev(), Seek(), SeekToFirst(), and SeekToLast().
                       {
     current_ = NextEntryOffset();
     const char* p = data_ + current_;
     const char* limit = data_ + restarts_;  // Restarts come right after data
     if (p >= limit) {
       // No more entries to return.  Mark as invalid.
       current_ = restarts_;
       restart_index_ = num_restarts_;
       return false;
     }
     // Decode next entry
     uint32_t shared, non_shared, value_length;
     p = DecodeEntry(p, limit, &shared, &non_shared, &value_length);
     if (p == nullptr || key_.size() < shared) {
       CorruptionError();
       return false;
     } else {
       key_.resize(shared);
       key_.append(p, non_shared);
       value_ = Slice(p + non_shared, value_length);
       while (restart_index_ + 1 < num_restarts_ &&
              GetRestartPoint(restart_index_ + 1) < current_) {
         ++restart_index_;
       }
       return true;
     }
   }
virtual void rocksdb::Block::Iter::Prev () inline virtual
Implements rocksdb::Iterator.
Definition at line 150 of file block.cc.
References current_, GetRestartPoint(), NextEntryOffset(), num_restarts_, ParseNextKey(), restart_index_, restarts_, SeekToRestartPoint(), and Valid().
                       {
     assert(Valid());
     // Scan backwards to a restart point before current_
     const uint32_t original = current_;
     while (GetRestartPoint(restart_index_) >= original) {
       if (restart_index_ == 0) {
         // No more entries
         current_ = restarts_;
         restart_index_ = num_restarts_;
         return;
       }
       restart_index_--;
     }
     SeekToRestartPoint(restart_index_);
     do {
       // Loop until end of current entry hits the start of original entry
     } while (ParseNextKey() && NextEntryOffset() < original);
   }
virtual void rocksdb::Block::Iter::Seek (const Slice & target) inline virtual
Implements rocksdb::Iterator.
Definition at line 171 of file block.cc.
References Compare(), CorruptionError(), data_, rocksdb::DecodeEntry(), GetRestartPoint(), key_, num_restarts_, ParseNextKey(), restarts_, SeekToRestartPoint(), and shared.
{
     // Binary search in restart array to find the first restart point
     // with a key >= target
     uint32_t left = 0;
     uint32_t right = num_restarts_ - 1;
     while (left < right) {
       uint32_t mid = (left + right + 1) / 2;
       uint32_t region_offset = GetRestartPoint(mid);
       uint32_t shared, non_shared, value_length;
       const char* key_ptr = DecodeEntry(data_ + region_offset,
                                         data_ + restarts_,
                                         &shared, &non_shared, &value_length);
       if (key_ptr == nullptr || (shared != 0)) {
         CorruptionError();
         return;
       }
       Slice mid_key(key_ptr, non_shared);
       if (Compare(mid_key, target) < 0) {
         // Key at "mid" is smaller than "target".  Therefore all
         // blocks before "mid" are uninteresting.
         left = mid;
       } else {
         // Key at "mid" is >= "target".  Therefore all blocks at or
         // after "mid" are uninteresting.
         right = mid - 1;
       }
     }
     // Linear search (within restart block) for first key >= target
     SeekToRestartPoint(left);
     while (true) {
       if (!ParseNextKey()) {
         return;
       }
       if (Compare(key_, target) >= 0) {
         return;
       }
     }
   }
virtual void rocksdb::Block::Iter::SeekToFirst () inline virtual
Implements rocksdb::Iterator.
Definition at line 211 of file block.cc.
References ParseNextKey(), and SeekToRestartPoint().
{
     SeekToRestartPoint(0);
     ParseNextKey();
   }
virtual void rocksdb::Block::Iter::SeekToLast () inline virtual
Implements rocksdb::Iterator.
Definition at line 216 of file block.cc.
References NextEntryOffset(), num_restarts_, ParseNextKey(), restarts_, and SeekToRestartPoint().
{
     SeekToRestartPoint(num_restarts_ - 1);
     while (ParseNextKey() && NextEntryOffset() < restarts_) {
       // Keep skipping
     }
   }
void rocksdb::Block::Iter::SeekToRestartPoint (uint32_t index) inline private
Definition at line 110 of file block.cc.
References data_, GetRestartPoint(), key_, restart_index_, and value_.
Referenced by Prev(), Seek(), SeekToFirst(), and SeekToLast().
{
     key_.clear();
     restart_index_ = index;
     // current_ will be fixed by ParseNextKey();
     // ParseNextKey() starts at the end of value_, so set value_ accordingly
     uint32_t offset = GetRestartPoint(index);
     value_ = Slice(data_ + offset, 0);
   }
virtual Status rocksdb::Block::Iter::status () const inline virtual
Implements rocksdb::Iterator.
Definition at line 135 of file block.cc.
References status_.
 { return status_; }
virtual bool rocksdb::Block::Iter::Valid () const inline virtual
Implements rocksdb::Iterator.
Definition at line 134 of file block.cc.
References current_, and restarts_.
Referenced by key(), Next(), Prev(), and value().
 { return current_ < restarts_; }
virtual Slice rocksdb::Block::Iter::value () const inline virtual
Implements rocksdb::Iterator.
Definition at line 140 of file block.cc.
References Valid(), and value_.
{
     assert(Valid());
     return value_;
   }
Member Data Documentation
const Comparator* const rocksdb::Block::Iter::comparator_ private
Definition at line 84 of file block.cc.
Referenced by Compare().
uint32_t rocksdb::Block::Iter::current_ private
Definition at line 90 of file block.cc.
Referenced by CorruptionError(), ParseNextKey(), Prev(), and Valid().
const char* const rocksdb::Block::Iter::data_ private
Definition at line 85 of file block.cc.
Referenced by GetRestartPoint(), NextEntryOffset(), ParseNextKey(), Seek(), and SeekToRestartPoint().
std::string rocksdb::Block::Iter::key_ private
Definition at line 92 of file block.cc.
Referenced by CorruptionError(), key(), ParseNextKey(), Seek(), and SeekToRestartPoint().
uint32_t const rocksdb::Block::Iter::num_restarts_ private
Definition at line 87 of file block.cc.
Referenced by CorruptionError(), GetRestartPoint(), Iter(), ParseNextKey(), Prev(), Seek(), and SeekToLast().
uint32_t rocksdb::Block::Iter::restart_index_ private
Definition at line 91 of file block.cc.
Referenced by CorruptionError(), ParseNextKey(), Prev(), and SeekToRestartPoint().
uint32_t const rocksdb::Block::Iter::restarts_ private
Definition at line 86 of file block.cc.
Referenced by CorruptionError(), GetRestartPoint(), ParseNextKey(), Prev(), Seek(), SeekToLast(), and Valid().
Status rocksdb::Block::Iter::status_ private
Definition at line 94 of file block.cc.
Referenced by CorruptionError(), and status().
Slice rocksdb::Block::Iter::value_ private
Definition at line 93 of file block.cc.
Referenced by CorruptionError(), NextEntryOffset(), ParseNextKey(), SeekToRestartPoint(), and value().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/table/block.cc