rippled: beast::asio::HandshakeDetectorType< Stream, Logic >::AsyncOp< Allocator > Class Template Reference
beast::asio::HandshakeDetectorType< Stream, Logic >::AsyncOp< Allocator > Class Template Reference
Public Types
typedef
boost::asio::basic_streambuf
< Allocator > BuffersType
Public Member Functions
AsyncOp (HandshakeDetectLogicType< Logic > &logic, Stream &stream, BuffersType &buffer, asio::shared_handler< void(error_code)> const &handler)
~AsyncOp ()
void start ()
void on_read (error_code ec, size_t bytes_transferred)
void async_read_some (error_code ec, size_t bytes_transferred)
Private Attributes
HandshakeDetectLogicType< Logic > & m_logic
Stream & m_stream
BuffersType & m_buffer
asio::shared_handler< void(error_code)> m_handler
bool m_continuation
Detailed Description
template<typename Stream, typename Logic>
template<typename Allocator>
class beast::asio::HandshakeDetectorType< Stream, Logic >::AsyncOp< Allocator >
Definition at line 126 of file HandshakeDetector.h.
Member Typedef Documentation
template<typename Stream, typename Logic> template<typename Allocator > typedef boost::asio::basic_streambuf<Allocator> beast::asio::HandshakeDetectorType< Stream, Logic >::AsyncOp< Allocator >::BuffersType
Definition at line 130 of file HandshakeDetector.h.
Constructor & Destructor Documentation
template<typename Stream, typename Logic> template<typename Allocator > beast::asio::HandshakeDetectorType< Stream, Logic >::AsyncOp< Allocator >::AsyncOp (HandshakeDetectLogicType< Logic > & logic, Stream & stream, BuffersType & buffer, asio::shared_handler< void(error_code)> const & handler) inline
Definition at line 132 of file HandshakeDetector.h.
             : m_logic (logic)
             , m_stream (stream)
             , m_buffer (buffer)
             , m_handler (handler)
             , m_continuation (false)
         {
         }
template<typename Stream, typename Logic> template<typename Allocator > beast::asio::HandshakeDetectorType< Stream, Logic >::AsyncOp< Allocator >::~AsyncOp () inline
Definition at line 144 of file HandshakeDetector.h.
         {
         }
Member Function Documentation
template<typename Stream, typename Logic> template<typename Allocator > void beast::asio::HandshakeDetectorType< Stream, Logic >::AsyncOp< Allocator >::async_read_some (error_code ec, size_t bytes_transferred) inline
Definition at line 159 of file HandshakeDetector.h.
References beast::asio::bind_handler(), beast::asio::HandshakeDetectorType< Stream, Logic >::AsyncOp< Allocator >::m_buffer, beast::asio::HandshakeDetectorType< Stream, Logic >::AsyncOp< Allocator >::m_continuation, beast::asio::HandshakeDetectorType< Stream, Logic >::AsyncOp< Allocator >::m_handler, beast::asio::HandshakeDetectorType< Stream, Logic >::AsyncOp< Allocator >::m_logic, beast::asio::HandshakeDetectorType< Stream, Logic >::AsyncOp< Allocator >::m_stream, meets_postcondition, and beast::asio::wrap_handler().
Referenced by beast::asio::HandshakeDetectorType< Stream, Logic >::AsyncOp< Allocator >::on_read(), and beast::asio::HandshakeDetectorType< Stream, Logic >::AsyncOp< Allocator >::start().
         {
             if (! ec)
             {
                 m_buffer.commit (bytes_transferred);
                 m_logic.analyze (m_buffer.data ());
                 if (!m_logic.finished ())
                 {
                     std::size_t const available = m_buffer.size ();
                     std::size_t const needed = m_logic.max_needed ();
                     // If postcondition fails, loop will never end
                     if (meets_postcondition (available < needed))
                     {
                         typename BuffersType::mutable_buffers_type buffers (
                             m_buffer.prepare (needed - available));
                         m_stream.async_read_some (buffers, asio::wrap_handler (
                             std::bind (&AsyncOp <Allocator>::on_read,
                                 this->shared_from_this(), asio::placeholders::error,
                                     asio::placeholders::bytes_transferred),
                                         m_handler, m_continuation));
                     }
                     return;
                 }
                 std::size_t const consumed = m_logic.bytes_consumed ();
                 m_buffer.consume (consumed);
             }
             // Finalize with a call to the original handler.
             if (m_continuation)
             {
                 m_handler (ec);
                 return;
             }
             // Post, otherwise we would call the
             // handler from the initiating function.
             m_stream.get_io_service ().post (asio::bind_handler (
                 m_handler, ec));
         }
template<typename Stream, typename Logic> template<typename Allocator > void beast::asio::HandshakeDetectorType< Stream, Logic >::AsyncOp< Allocator >::on_read (error_code ec, size_t bytes_transferred) inline
Definition at line 153 of file HandshakeDetector.h.
References beast::asio::HandshakeDetectorType< Stream, Logic >::AsyncOp< Allocator >::async_read_some(), and beast::asio::HandshakeDetectorType< Stream, Logic >::AsyncOp< Allocator >::m_continuation.
         {
             m_continuation = true;
             async_read_some (ec, bytes_transferred);
         }
template<typename Stream, typename Logic> template<typename Allocator > void beast::asio::HandshakeDetectorType< Stream, Logic >::AsyncOp< Allocator >::start () inline
Definition at line 148 of file HandshakeDetector.h.
References beast::asio::HandshakeDetectorType< Stream, Logic >::AsyncOp< Allocator >::async_read_some().
         {
             async_read_some (error_code(), 0);
         }
Member Data Documentation
template<typename Stream, typename Logic> template<typename Allocator > BuffersType& beast::asio::HandshakeDetectorType< Stream, Logic >::AsyncOp< Allocator >::m_buffer private
Definition at line 207 of file HandshakeDetector.h.
Referenced by beast::asio::HandshakeDetectorType< Stream, Logic >::AsyncOp< Allocator >::async_read_some().
template<typename Stream, typename Logic> template<typename Allocator > bool beast::asio::HandshakeDetectorType< Stream, Logic >::AsyncOp< Allocator >::m_continuation private
Definition at line 209 of file HandshakeDetector.h.
Referenced by beast::asio::HandshakeDetectorType< Stream, Logic >::AsyncOp< Allocator >::async_read_some(), and beast::asio::HandshakeDetectorType< Stream, Logic >::AsyncOp< Allocator >::on_read().
template<typename Stream, typename Logic> template<typename Allocator > asio::shared_handler<void(error_code)> beast::asio::HandshakeDetectorType< Stream, Logic >::AsyncOp< Allocator >::m_handler private
Definition at line 208 of file HandshakeDetector.h.
Referenced by beast::asio::HandshakeDetectorType< Stream, Logic >::AsyncOp< Allocator >::async_read_some().
template<typename Stream, typename Logic> template<typename Allocator > HandshakeDetectLogicType<Logic>& beast::asio::HandshakeDetectorType< Stream, Logic >::AsyncOp< Allocator >::m_logic private
Definition at line 205 of file HandshakeDetector.h.
Referenced by beast::asio::HandshakeDetectorType< Stream, Logic >::AsyncOp< Allocator >::async_read_some().
template<typename Stream, typename Logic> template<typename Allocator > Stream& beast::asio::HandshakeDetectorType< Stream, Logic >::AsyncOp< Allocator >::m_stream private
Definition at line 206 of file HandshakeDetector.h.
Referenced by beast::asio::HandshakeDetectorType< Stream, Logic >::AsyncOp< Allocator >::async_read_some().
The documentation for this class was generated from the following file:
rippled/src/beast/modules/beast_asio/protocol/HandshakeDetector.h