rippled: beast::String Class Reference
beast::String Class Reference
#include <String.h>
Classes
struct FromNumber
struct PreallocationBytes
Public Types
typedef StringCharPointerType CharPointerType
Public Member Functions
String () noexcept
String (const String &other) noexcept
String (const char *text)
String (const char *text, size_t maxChars)
String (const wchar_t *text)
String (const wchar_t *text, size_t maxChars)
String (const CharPointer_UTF8 text)
String (const CharPointer_UTF8 text, size_t maxChars)
String (const CharPointer_UTF8 start, const CharPointer_UTF8 end)
String (const CharPointer_UTF16 text)
String (const CharPointer_UTF16 text, size_t maxChars)
String (const CharPointer_UTF16 start, const CharPointer_UTF16 end)
String (const CharPointer_UTF32 text)
String (const CharPointer_UTF32 text, size_t maxChars)
String (const CharPointer_UTF32 start, const CharPointer_UTF32 end)
String (const CharPointer_ASCII text)
String (const std::string &)
~String () noexcept
int hashCode () const noexcept
std::int64_t hashCode64 () const noexcept
std::size_t hash () const noexcept
int length () const noexcept
String & operator= (const String &other) noexcept
String & operator+= (const String &stringToAppend)
String & operator+= (const char *textToAppend)
String & operator+= (const wchar_t *textToAppend)
String & operator+= (int numberToAppend)
String & operator+= (char characterToAppend)
String & operator+= (wchar_t characterToAppend)
void append (const String &textToAppend, size_t maxCharsToTake)
void appendCharPointer (const CharPointerType startOfTextToAppend, const CharPointerType endOfTextToAppend)
void appendCharPointer (const CharPointerType textToAppend)
template<class CharPointer >
void appendCharPointer (const CharPointer textToAppend, size_t maxCharsToTake)
template<class CharPointer >
void appendCharPointer (const CharPointer textToAppend)
bool isEmpty () const noexcept
bool isNotEmpty () const noexcept
bool equalsIgnoreCase (const String &other) const noexcept
bool equalsIgnoreCase (const wchar_t *other) const noexcept
bool equalsIgnoreCase (const char *other) const noexcept
int compare (const String &other) const noexcept
int compare (const char *other) const noexcept
int compare (const wchar_t *other) const noexcept
int compareIgnoreCase (const String &other) const noexcept
int compareLexicographically (const String &other) const noexcept
bool startsWith (const String &text) const noexcept
bool startsWithChar (beast_wchar character) const noexcept
bool startsWithIgnoreCase (const String &text) const noexcept
bool endsWith (const String &text) const noexcept
bool endsWithChar (beast_wchar character) const noexcept
bool endsWithIgnoreCase (const String &text) const noexcept
bool contains (const String &text) const noexcept
bool containsChar (beast_wchar character) const noexcept
bool containsIgnoreCase (const String &text) const noexcept
bool containsWholeWord (const String &wordToLookFor) const noexcept
bool containsWholeWordIgnoreCase (const String &wordToLookFor) const noexcept
int indexOfWholeWord (const String &wordToLookFor) const noexcept
int indexOfWholeWordIgnoreCase (const String &wordToLookFor) const noexcept
bool containsAnyOf (const String &charactersItMightContain) const noexcept
bool containsOnly (const String &charactersItMightContain) const noexcept
bool containsNonWhitespaceChars () const noexcept
bool matchesWildcard (const String &wildcard, bool ignoreCase) const noexcept
int indexOfChar (beast_wchar characterToLookFor) const noexcept
int indexOfChar (int startIndex, beast_wchar characterToLookFor) const noexcept
int indexOfAnyOf (const String &charactersToLookFor, int startIndex=0, bool ignoreCase=false) const noexcept
int indexOf (const String &textToLookFor) const noexcept
int indexOf (int startIndex, const String &textToLookFor) const noexcept
int indexOfIgnoreCase (const String &textToLookFor) const noexcept
int indexOfIgnoreCase (int startIndex, const String &textToLookFor) const noexcept
int lastIndexOfChar (beast_wchar character) const noexcept
int lastIndexOf (const String &textToLookFor) const noexcept
int lastIndexOfIgnoreCase (const String &textToLookFor) const noexcept
int lastIndexOfAnyOf (const String &charactersToLookFor, bool ignoreCase=false) const noexcept
beast_wchar operator[] (int index) const noexcept
beast_wchar getLastCharacter () const noexcept
String substring (int startIndex, int endIndex) const
String substring (int startIndex) const
String dropLastCharacters (int numberToDrop) const
String getLastCharacters (int numCharacters) const
String fromFirstOccurrenceOf (const String &substringToStartFrom, bool includeSubStringInResult, bool ignoreCase) const
String fromLastOccurrenceOf (const String &substringToFind, bool includeSubStringInResult, bool ignoreCase) const
String upToFirstOccurrenceOf (const String &substringToEndWith, bool includeSubStringInResult, bool ignoreCase) const
String upToLastOccurrenceOf (const String &substringToFind, bool includeSubStringInResult, bool ignoreCase) const
String trim () const
String trimStart () const
String trimEnd () const
String trimCharactersAtStart (const String &charactersToTrim) const
String trimCharactersAtEnd (const String &charactersToTrim) const
String toUpperCase () const
String toLowerCase () const
String replaceSection (int startIndex, int numCharactersToReplace, const String &stringToInsert) const
String replace (const String &stringToReplace, const String &stringToInsertInstead, bool ignoreCase=false) const
String replaceCharacter (beast_wchar characterToReplace, beast_wchar characterToInsertInstead) const
String replaceCharacters (const String &charactersToReplace, const String &charactersToInsertInstead) const
String retainCharacters (const String &charactersToRetain) const
String removeCharacters (const String &charactersToRemove) const
String initialSectionContainingOnly (const String &permittedCharacters) const
String initialSectionNotContaining (const String &charactersToStopAt) const
bool isQuotedString () const
String unquoted () const
String quoted (beast_wchar quoteCharacter= '"') const
String paddedLeft (beast_wchar padCharacter, int minimumLength) const
String paddedRight (beast_wchar padCharacter, int minimumLength) const
String (int decimalInteger)
String (unsigned int decimalInteger)
String (short decimalInteger)
String (unsigned short decimalInteger)
String (long largeIntegerValue)
String (unsigned long largeIntegerValue)
String (long long largeIntegerValue)
String (unsigned long long largeIntegerValue)
String (float floatValue)
String (double doubleValue)
String (float floatValue, int numberOfDecimalPlaces)
String (double doubleValue, int numberOfDecimalPlaces)
int getIntValue () const noexcept
std::int64_t getLargeIntValue () const noexcept
int getTrailingIntValue () const noexcept
float getFloatValue () const noexcept
double getDoubleValue () const noexcept
int getHexValue32 () const noexcept
std::int64_t getHexValue64 () const noexcept
CharPointerType getCharPointer () const noexcept
CharPointer_UTF8 toUTF8 () const
const char * toRawUTF8 () const
CharPointer_UTF16 toUTF16 () const
CharPointer_UTF32 toUTF32 () const
const wchar_t * toWideCharPointer () const
std::string toStdString () const
size_t getNumBytesAsUTF8 () const noexcept
size_t copyToUTF8 (CharPointer_UTF8::CharType *destBuffer, size_t maxBufferSizeBytes) const noexcept
size_t copyToUTF16 (CharPointer_UTF16::CharType *destBuffer, size_t maxBufferSizeBytes) const noexcept
size_t copyToUTF32 (CharPointer_UTF32::CharType *destBuffer, size_t maxBufferSizeBytes) const noexcept
void preallocateBytes (size_t numBytesNeeded)
void swapWith (String &other) noexcept
template<typename Number >
String fromNumber (Number number, int)
template<>
String fromNumber (float number, int numberOfDecimalPlaces)
template<>
String fromNumber (double number, int numberOfDecimalPlaces)
Static Public Member Functions
static String charToString (beast_wchar character)
template<typename Number >
static String fromNumber (Number number, int numberOfDecimalPlaces=-1)
static String repeatedString (const String &stringToRepeat, int numberOfTimesToRepeat)
static String createStringFromData (const void *data, int size)
static String formatted (const String formatString,...)
static String toHexString (int number)
static String toHexString (std::int64_t number)
static String toHexString (short number)
static String toHexString (const void *data, int size, int groupSize=1)
static String fromUTF8 (const char *utf8buffer, int bufferSizeBytes=-1)
Static Public Attributes
static const String empty
Private Member Functions
String (CharPointerType text_, FromNumber)
String (const PreallocationBytes &)
void appendFixedLength (const char *text, int numExtraChars)
size_t getByteOffsetOfEnd () const noexcept
BEAST_DEPRECATED (String(const String &, size_t))
operator bool () const noexcept
Private Attributes
CharPointerType text
Friends
template<class Hasher >
void hash_append (Hasher &h, String const &s)
Detailed Description
The BEAST String class!
Using a reference-counted internal representation, these strings are fast and efficient, and there are methods to do just about any operation you'll ever dream of.
See Also
StringArray, StringPairArray
Definition at line 69 of file String.h.
Member Typedef Documentation
typedef StringCharPointerType beast::String::CharPointerType
This is the character encoding type used internally to store the string.
Definition at line 189 of file String.h.
Constructor & Destructor Documentation
beast::String::String () noexcept
Creates an empty string.
See Also
empty
Definition at line 265 of file String.cpp.
Referenced by fromNumber().
                          : text (StringHolder::getEmpty())
 {
 }
beast::String::String (const String & other) noexcept
Creates a copy of another string.
Definition at line 274 of file String.cpp.
References beast::StringHolder::retain().
     : text (other.text)
 {
     StringHolder::retain (text);
 }
beast::String::String (const char * text)
Creates a string from a zero-terminated ascii text string.
The string passed-in must not contain any characters with a value above 127, because these can't be converted to unicode without knowing the original encoding that was used to create the string. If you attempt to pass-in values above 127, you'll get an assertion.
To create strings with extended characters from UTF-8, you should explicitly call String (CharPointer_UTF8 ("my utf8 string..")). It's highly recommended that you use UTF-8 with escape characters in your source code to represent extended characters, because there's no other way to represent unicode strings in a way that isn't dependent on the compiler, source code editor and platform.
Definition at line 314 of file String.cpp.
References bassert, beast::CharPointer_ASCII::isValidString(), and ripple::max().
     : text (StringHolder::createFromCharPointer (CharPointer_ASCII (t)))
 {
     /*  If you get an assertion here, then you're trying to create a string from 8-bit data
         that contains values greater than 127. These can NOT be correctly converted to unicode
         because there's no way for the String class to know what encoding was used to
         create them. The source data could be UTF-8, ASCII or one of many local code-pages.
         To get around this problem, you must be more explicit when you pass an ambiguous 8-bit
         string to the String class - so for example if your source data is actually UTF-8,
         you'd call String (CharPointer_UTF8 ("my utf8 string..")), and it would be able to
         correctly convert the multi-byte characters to unicode. It's *highly* recommended that
         you use UTF-8 with escape characters in your source code to represent extended characters,
         because there's no other way to represent these strings in a way that isn't dependent on
         the compiler, source code editor and platform.
     */
     bassert (t == nullptr || CharPointer_ASCII::isValidString (t, std::numeric_limits<int>::max()));
 }
beast::String::String (const char * text, size_t maxChars)
Creates a string from a string of 8-bit ascii characters.
The string passed-in must not contain any characters with a value above 127, because these can't be converted to unicode without knowing the original encoding that was used to create the string. If you attempt to pass-in values above 127, you'll get an assertion.
To create strings with extended characters from UTF-8, you should explicitly call String (CharPointer_UTF8 ("my utf8 string..")). It's highly recommended that you use UTF-8 with escape characters in your source code to represent extended characters, because there's no other way to represent unicode strings in a way that isn't dependent on the compiler, source code editor and platform.
This will use up the the first maxChars characters of the string (or less if the string is actually shorter).
Definition at line 333 of file String.cpp.
References bassert, and beast::CharPointer_ASCII::isValidString().
     : text (StringHolder::createFromCharPointer (CharPointer_ASCII (t), maxChars))
 {
     /*  If you get an assertion here, then you're trying to create a string from 8-bit data
         that contains values greater than 127. These can NOT be correctly converted to unicode
         because there's no way for the String class to know what encoding was used to
         create them. The source data could be UTF-8, ASCII or one of many local code-pages.
         To get around this problem, you must be more explicit when you pass an ambiguous 8-bit
         string to the String class - so for example if your source data is actually UTF-8,
         you'd call String (CharPointer_UTF8 ("my utf8 string..")), and it would be able to
         correctly convert the multi-byte characters to unicode. It's *highly* recommended that
         you use UTF-8 with escape characters in your source code to represent extended characters,
         because there's no other way to represent these strings in a way that isn't dependent on
         the compiler, source code editor and platform.
     */
     bassert (t == nullptr || CharPointer_ASCII::isValidString (t, (int) maxChars));
 }
beast::String::String (const wchar_t * text)
Creates a string from a whcar_t character string. Depending on the platform, this may be treated as either UTF-32 or UTF-16.
Definition at line 352 of file String.cpp.
 : text (StringHolder::createFromCharPointer (castToCharPointer_wchar_t (t))) {}
beast::String::String (const wchar_t * text, size_t maxChars)
Creates a string from a whcar_t character string. Depending on the platform, this may be treated as either UTF-32 or UTF-16.
Definition at line 361 of file String.cpp.
 : text (StringHolder::createFromCharPointer (castToCharPointer_wchar_t (t), maxChars)) {}
beast::String::String (const CharPointer_UTF8 text)
Creates a string from a UTF-8 character string
Definition at line 353 of file String.cpp.
 : text (StringHolder::createFromCharPointer (t)) {}
beast::String::String (const CharPointer_UTF8 text, size_t maxChars)
Creates a string from a UTF-8 character string
Definition at line 358 of file String.cpp.
 : text (StringHolder::createFromCharPointer (t, maxChars)) {}
beast::String::String (const CharPointer_UTF8 start, const CharPointer_UTF8 end)
Creates a string from a UTF-8 character string
Definition at line 363 of file String.cpp.
 : text (StringHolder::createFromCharPointer (start, end)) {}
beast::String::String (const CharPointer_UTF16 text)
Creates a string from a UTF-16 character string
Definition at line 354 of file String.cpp.
 : text (StringHolder::createFromCharPointer (t)) {}
beast::String::String (const CharPointer_UTF16 text, size_t maxChars)
Creates a string from a UTF-16 character string
Definition at line 359 of file String.cpp.
 : text (StringHolder::createFromCharPointer (t, maxChars)) {}
beast::String::String (const CharPointer_UTF16 start, const CharPointer_UTF16 end)
Creates a string from a UTF-16 character string
Definition at line 364 of file String.cpp.
 : text (StringHolder::createFromCharPointer (start, end)) {}
beast::String::String (const CharPointer_UTF32 text)
Creates a string from a UTF-32 character string
Definition at line 355 of file String.cpp.
 : text (StringHolder::createFromCharPointer (t)) {}
beast::String::String (const CharPointer_UTF32 text, size_t maxChars)
Creates a string from a UTF-32 character string
Definition at line 360 of file String.cpp.
 : text (StringHolder::createFromCharPointer (t, maxChars)) {}
beast::String::String (const CharPointer_UTF32 start, const CharPointer_UTF32 end)
Creates a string from a UTF-32 character string
Definition at line 365 of file String.cpp.
 : text (StringHolder::createFromCharPointer (start, end)) {}
beast::String::String (const CharPointer_ASCII text)
Creates a string from an ASCII character string
Definition at line 356 of file String.cpp.
 : text (StringHolder::createFromCharPointer (t)) {}
beast::String::String (const std::string & s)
Creates a string from a UTF-8 encoded std::string.
Definition at line 367 of file String.cpp.
 : text (StringHolder::createFromFixedLength (s.data(), s.size())) {}
beast::String::~String () noexcept
Destructor.
Definition at line 269 of file String.cpp.
References beast::StringHolder::release(), and text.
 {
     StringHolder::release (text);
 }
beast::String::String (int decimalInteger) explicit
Creates a string containing this signed 32-bit integer as a decimal number.
See Also
getIntValue, getFloatValue, getDoubleValue, toHexString
Definition at line 380 of file String.cpp.
 : text (NumberToStringConverters::createFromInteger (number)) {}
beast::String::String (unsigned int decimalInteger) explicit
Creates a string containing this unsigned 32-bit integer as a decimal number.
See Also
getIntValue, getFloatValue, getDoubleValue, toHexString
Definition at line 381 of file String.cpp.
 : text (NumberToStringConverters::createFromInteger (number)) {}
beast::String::String (short decimalInteger) explicit
Creates a string containing this signed 16-bit integer as a decimal number.
See Also
getIntValue, getFloatValue, getDoubleValue, toHexString
Definition at line 382 of file String.cpp.
 : text (NumberToStringConverters::createFromInteger ((int) number)) {}
beast::String::String (unsigned short decimalInteger) explicit
Creates a string containing this unsigned 16-bit integer as a decimal number.
See Also
getIntValue, getFloatValue, getDoubleValue, toHexString
Definition at line 383 of file String.cpp.
 : text (NumberToStringConverters::createFromInteger ((unsigned int) number)) {}
beast::String::String (long largeIntegerValue) explicit
Definition at line 384 of file String.cpp.
 : text (NumberToStringConverters::createFromInteger (number)) {}
beast::String::String (unsigned long largeIntegerValue) explicit
Definition at line 385 of file String.cpp.
 : text (NumberToStringConverters::createFromInteger (number)) {}
beast::String::String (long long largeIntegerValue) explicit
Definition at line 386 of file String.cpp.
 : text (NumberToStringConverters::createFromInteger (number)) {}
beast::String::String (unsigned long long largeIntegerValue) explicit
Definition at line 387 of file String.cpp.
 : text (NumberToStringConverters::createFromInteger (number)) {}
beast::String::String (float floatValue) explicit
Creates a string representing this floating-point number.
Parameters
floatValue the value to convert to a string
See Also
getDoubleValue, getIntValue
Definition at line 389 of file String.cpp.
 : text (NumberToStringConverters::createFromDouble ((double) number, 0)) {}
beast::String::String (double doubleValue) explicit
Creates a string representing this floating-point number.
Parameters
doubleValue the value to convert to a string
See Also
getFloatValue, getIntValue
Definition at line 390 of file String.cpp.
 : text (NumberToStringConverters::createFromDouble (number, 0)) {}
beast::String::String (float floatValue, int numberOfDecimalPlaces)
Creates a string representing this floating-point number.
Parameters
floatValue the value to convert to a string
numberOfDecimalPlaces if this is > 0, it will format the number using that many decimal places, and will not use exponent notation. If 0 or less, it will use exponent notation if necessary.
See Also
getDoubleValue, getIntValue
Definition at line 391 of file String.cpp.
 : text (NumberToStringConverters::createFromDouble ((double) number, numberOfDecimalPlaces)) {}
beast::String::String (double doubleValue, int numberOfDecimalPlaces)
Creates a string representing this floating-point number.
Parameters
doubleValue the value to convert to a string
numberOfDecimalPlaces if this is > 0, it will format the number using that many decimal places, and will not use exponent notation. If 0 or less, it will use exponent notation if necessary.
See Also
getFloatValue, getIntValue
Definition at line 392 of file String.cpp.
 : text (NumberToStringConverters::createFromDouble (number, numberOfDecimalPlaces)) {}
beast::String::String (CharPointerType text_, FromNumber) inline private
Definition at line 1229 of file String.h.
 : text (text_) { }
beast::String::String (const PreallocationBytes & preallocationSize) explicit private
Definition at line 308 of file String.cpp.
     : text (StringHolder::createUninitialisedBytes (preallocationSize.numBytes + sizeof (CharPointerType::CharType)))
 {
 }
Member Function Documentation
void beast::String::append (const String & textToAppend, size_t maxCharsToTake)
Appends a string to the end of this one.
Parameters
textToAppend the string to add
maxCharsToTake the maximum number of characters to take from the string passed in
Definition at line 506 of file String.cpp.
References text.
 {
     appendCharPointer (textToAppend.text, maxCharsToTake);
 }
void beast::String::appendCharPointer (const CharPointerType startOfTextToAppend, const CharPointerType endOfTextToAppend)
Appends a string to the end of this one.
Parameters
startOfTextToAppend the start of the string to add. This must not be a nullptr
endOfTextToAppend the end of the string to add. This must not be a nullptr
Definition at line 516 of file String.cpp.
References beast::addBytesToPointer(), bassert, beast::CharPointer_UTF8::getAddress(), beast::getAddressDifference(), and beast::CharPointer_UTF8::writeNull().
Referenced by beast::File::getRelativePathFrom().
 {
     bassert (startOfTextToAppend.getAddress() != nullptr && endOfTextToAppend.getAddress() != nullptr);
     const int extraBytesNeeded = getAddressDifference (endOfTextToAppend.getAddress(),
                                                        startOfTextToAppend.getAddress());
     bassert (extraBytesNeeded >= 0);
     if (extraBytesNeeded > 0)
     {
         const size_t byteOffsetOfNull = getByteOffsetOfEnd();
         preallocateBytes (byteOffsetOfNull + (size_t) extraBytesNeeded);
         CharPointerType::CharType* const newStringStart = addBytesToPointer (text.getAddress(), (int) byteOffsetOfNull);
         memcpy (newStringStart, startOfTextToAppend.getAddress(), extraBytesNeeded);
         CharPointerType (addBytesToPointer (newStringStart, extraBytesNeeded)).writeNull();
     }
 }
void beast::String::appendCharPointer (const CharPointerType textToAppend)
Appends a string to the end of this one.
Definition at line 511 of file String.cpp.
References beast::CharPointer_UTF8::findTerminatingNull().
 {
     appendCharPointer (textToAppend, textToAppend.findTerminatingNull());
 }
template<class CharPointer > void beast::String::appendCharPointer (const CharPointer textToAppend, size_t maxCharsToTake) inline
Appends a string to the end of this one.
Parameters
textToAppend the string to add
maxCharsToTake the maximum number of characters to take from the string passed in
Definition at line 255 of file String.h.
References beast::addBytesToPointer(), beast::CharPointer_ASCII::getAddress(), getByteOffsetOfEnd(), beast::CharPointer_UTF8::getBytesRequiredFor(), and preallocateBytes().
     {
         if (textToAppend.getAddress() != nullptr)
         {
             size_t extraBytesNeeded = 0;
             size_t numChars = 0;
             for (CharPointer t (textToAppend); numChars < maxCharsToTake && ! t.isEmpty();)
             {
                 extraBytesNeeded += CharPointerType::getBytesRequiredFor (t.getAndAdvance());
                 ++numChars;
             }
             if (numChars > 0)
             {
                 const size_t byteOffsetOfNull = getByteOffsetOfEnd();
                 preallocateBytes (byteOffsetOfNull + extraBytesNeeded);
                 CharPointerType (addBytesToPointer (text.getAddress(), (int) byteOffsetOfNull)).writeWithCharLimit (textToAppend, (int) (numChars + 1));
             }
         }
     }
template<class CharPointer > void beast::String::appendCharPointer (const CharPointer textToAppend) inline
Appends a string to the end of this one.
Definition at line 280 of file String.h.
References beast::addBytesToPointer(), beast::CharPointer_ASCII::getAddress(), getByteOffsetOfEnd(), beast::CharPointer_UTF8::getBytesRequiredFor(), and preallocateBytes().
     {
         if (textToAppend.getAddress() != nullptr)
         {
             size_t extraBytesNeeded = 0;
             for (CharPointer t (textToAppend); ! t.isEmpty();)
                 extraBytesNeeded += CharPointerType::getBytesRequiredFor (t.getAndAdvance());
             if (extraBytesNeeded > 0)
             {
                 const size_t byteOffsetOfNull = getByteOffsetOfEnd();
                 preallocateBytes (byteOffsetOfNull + extraBytesNeeded);
                 CharPointerType (addBytesToPointer (text.getAddress(), (int) byteOffsetOfNull)).writeAll (textToAppend);
             }
         }
     }
void beast::String::appendFixedLength (const char * text, int numExtraChars) private
beast::String::BEAST_DEPRECATED (String(const String &, size_t)) private
String beast::String::charToString (beast_wchar character) static
Creates a string from a single character.
Definition at line 369 of file String.cpp.
References beast::CharPointer_UTF8::getBytesRequiredFor(), text, beast::CharPointer_UTF8::write(), and beast::CharPointer_UTF8::writeNull().
Referenced by beast::SemanticVersion::chopIdentifier(), and beast::operator+().
 {
     String result (PreallocationBytes (CharPointerType::getBytesRequiredFor (character)));
     CharPointerType t (result.text);
     t.write (character);
     t.writeNull();
     return result;
 }
int beast::String::compare (const String & other) const noexcept
Case-sensitive comparison with another string.
Returns
0 if the two strings are identical; negative if this string comes before the other one alphabetically, or positive if it comes after it.
Definition at line 485 of file String.cpp.
Referenced by beast::InternalStringArrayComparator_CaseSensitive::compareElements().
 { return (text == other.text) ? 0 : text.compare (other.text); }
int beast::String::compare (const char * other) const noexcept
Case-sensitive comparison with another string.
Returns
0 if the two strings are identical; negative if this string comes before the other one alphabetically, or positive if it comes after it.
Definition at line 486 of file String.cpp.
 { return text.compare (CharPointer_UTF8 (other)); }
int beast::String::compare (const wchar_t * other) const noexcept
Case-sensitive comparison with another string.
Returns
0 if the two strings are identical; negative if this string comes before the other one alphabetically, or positive if it comes after it.
Definition at line 487 of file String.cpp.
References beast::castToCharPointer_wchar_t().
 { return text.compare (castToCharPointer_wchar_t (other)); }
int beast::String::compareIgnoreCase (const String & other) const noexcept
Case-insensitive comparison with another string.
Returns
0 if the two strings are identical; negative if this string comes before the other one alphabetically, or positive if it comes after it.
Definition at line 488 of file String.cpp.
Referenced by beast::InternalStringArrayComparator_CaseInsensitive::compareElements().
 { return (text == other.text) ? 0 : text.compareIgnoreCase (other.text); }
int beast::String::compareLexicographically (const String & other) const noexcept
Lexicographic comparison with another string.
The comparison used here is case-insensitive and ignores leading non-alphanumeric characters, making it good for sorting human-readable strings.
Returns
0 if the two strings are identical; negative if this string comes before the other one alphabetically, or positive if it comes after it.
Definition at line 490 of file String.cpp.
References beast::CharPointer_UTF8::compareIgnoreCase(), beast::CharPointer_UTF8::isEmpty(), and beast::CharPointer_UTF8::isLetterOrDigit().
Referenced by beast::SemanticVersion::compare().
 {
     CharPointerType s1 (text);
     while (! (s1.isEmpty() || s1.isLetterOrDigit()))
         ++s1;
     CharPointerType s2 (other.text);
     while (! (s2.isEmpty() || s2.isLetterOrDigit()))
         ++s2;
     return s1.compareIgnoreCase (s2);
 }
bool beast::String::contains (const String & text) const noexcept
Tests whether the string contains another substring. If the parameter is an empty string, this will always return true. Uses a case-sensitive comparison.
Definition at line 839 of file String.cpp.
Referenced by beast::SemanticVersion::chopIdentifier(), beast::Time::getTimeZone(), and beast::CPUInformation::initialise().
 {
     return indexOf (other) >= 0;
 }
bool beast::String::containsAnyOf (const String & charactersItMightContain) const noexcept
Looks for any of a set of characters in the string. Uses a case-sensitive comparison.
Returns
true if the string contains any of the characters from the string that is passed in.
Definition at line 1626 of file String.cpp.
References beast::CharPointer_UTF8::getAndAdvance(), and beast::CharPointer_UTF8::isEmpty().
 {
     CharPointerType t (text);
     while (! t.isEmpty())
         if (chars.containsChar (t.getAndAdvance()))
             return true;
     return false;
 }
bool beast::String::containsChar (beast_wchar character) const noexcept
Tests whether the string contains a particular character. Uses a case-sensitive comparison.
Definition at line 844 of file String.cpp.
Referenced by beast::File::hasWriteAccess(), initialSectionContainingOnly(), initialSectionNotContaining(), beast::File::parseAbsolutePath(), removeCharacters(), retainCharacters(), trimCharactersAtEnd(), and trimCharactersAtStart().
 {
     return text.indexOf (character) >= 0;
 }
bool beast::String::containsIgnoreCase (const String & text) const noexcept
Tests whether the string contains another substring. Uses a case-insensitive comparison.
Definition at line 849 of file String.cpp.
Referenced by beast::Time::getTimeZone().
 {
     return indexOfIgnoreCase (t) >= 0;
 }
bool beast::String::containsNonWhitespaceChars () const noexcept
Returns true if this string contains any non-whitespace characters.
This will return false if the string contains only whitespace characters, or if it's empty.
It is equivalent to calling "myString.trim().isNotEmpty()".
Definition at line 1637 of file String.cpp.
References beast::CharPointer_UTF8::isEmpty(), and beast::CharPointer_UTF8::isWhitespace().
 {
     CharPointerType t (text);
     while (! t.isEmpty())
     {
         if (! t.isWhitespace())
             return true;
         ++t;
     }
     return false;
 }
bool beast::String::containsOnly (const String & charactersItMightContain) const noexcept
Looks for a set of characters in the string. Uses a case-sensitive comparison.
Returns
Returns false if any of the characters in this string do not occur in the parameter string. If this string is empty, the return value will always be true.
Definition at line 1615 of file String.cpp.
References beast::CharPointer_UTF8::getAndAdvance(), and beast::CharPointer_UTF8::isEmpty().
Referenced by beast::File::getNonexistentChildFile(), and beast::DirectoryIterator::next().
 {
     CharPointerType t (text);
     while (! t.isEmpty())
         if (! chars.containsChar (t.getAndAdvance()))
             return false;
     return true;
 }
bool beast::String::containsWholeWord (const String & wordToLookFor) const noexcept
Tests whether the string contains another substring as a distinct word.
Returns
true if the string contains this word, surrounded by non-alphanumeric characters
See Also
indexOfWholeWord, containsWholeWordIgnoreCase
Definition at line 898 of file String.cpp.
 {
     return indexOfWholeWord (wordToLookFor) >= 0;
 }
bool beast::String::containsWholeWordIgnoreCase (const String & wordToLookFor) const noexcept
Tests whether the string contains another substring as a distinct word.
Returns
true if the string contains this word, surrounded by non-alphanumeric characters
See Also
indexOfWholeWordIgnoreCase, containsWholeWord
Definition at line 903 of file String.cpp.
 {
     return indexOfWholeWordIgnoreCase (wordToLookFor) >= 0;
 }
size_t beast::String::copyToUTF16 (CharPointer_UTF16::CharType * destBuffer, size_t maxBufferSizeBytes) const noexcept
Copies the string to a buffer as UTF-16 characters.
Returns the number of bytes copied to the buffer, including the terminating null character.
To find out how many bytes you need to store this string as UTF-16, you can call CharPointer_UTF16::getBytesRequiredFor (myString.getCharPointer())
Parameters
destBuffer the place to copy it to; if this is a null pointer, the method just returns the number of bytes required (including the terminating null character).
maxBufferSizeBytes the size of the destination buffer, in bytes. If the string won't fit, it'll put in as many as it can while still allowing for a terminating null char at the end, and will return the number of bytes that were actually used.
See Also
CharPointer_UTF16::writeWithDestByteLimit
Definition at line 1951 of file String.cpp.
Referenced by beast::WindowsFileHelpers::getDriveFromPath().
 {
     return StringCopier <CharPointerType, CharPointer_UTF16>::copyToBuffer (text, buffer, maxBufferSizeBytes);
 }
size_t beast::String::copyToUTF32 (CharPointer_UTF32::CharType * destBuffer, size_t maxBufferSizeBytes) const noexcept
Copies the string to a buffer as UTF-32 characters.
Returns the number of bytes copied to the buffer, including the terminating null character.
To find out how many bytes you need to store this string as UTF-32, you can call CharPointer_UTF32::getBytesRequiredFor (myString.getCharPointer())
Parameters
destBuffer the place to copy it to; if this is a null pointer, the method just returns the number of bytes required (including the terminating null character).
maxBufferSizeBytes the size of the destination buffer, in bytes. If the string won't fit, it'll put in as many as it can while still allowing for a terminating null char at the end, and will return the number of bytes that were actually used.
See Also
CharPointer_UTF32::writeWithDestByteLimit
Definition at line 1956 of file String.cpp.
 {
     return StringCopier <CharPointerType, CharPointer_UTF32>::copyToBuffer (text, buffer, maxBufferSizeBytes);
 }
size_t beast::String::copyToUTF8 (CharPointer_UTF8::CharType * destBuffer, size_t maxBufferSizeBytes) const noexcept
Copies the string to a buffer as UTF-8 characters.
Returns the number of bytes copied to the buffer, including the terminating null character.
To find out how many bytes you need to store this string as UTF-8, you can call CharPointer_UTF8::getBytesRequiredFor (myString.getCharPointer())
Parameters
destBuffer the place to copy it to; if this is a null pointer, the method just returns the number of bytes required (including the terminating null character).
maxBufferSizeBytes the size of the destination buffer, in bytes. If the string won't fit, it'll put in as many as it can while still allowing for a terminating null char at the end, and will return the number of bytes that were actually used.
See Also
CharPointer_UTF8::writeWithDestByteLimit
Definition at line 1946 of file String.cpp.
Referenced by beast::OutputStream::writeString().
 {
     return StringCopier <CharPointerType, CharPointer_UTF8>::copyToBuffer (text, buffer, maxBufferSizeBytes);
 }
String beast::String::createStringFromData (const void * data, int size) static
Creates a string from data in an unknown format.
This looks at some binary data and tries to guess whether it's Unicode or 8-bit characters, then returns a string that represents it correctly.
Should be able to handle Unicode endianness correctly, by looking at the first two bytes.
Definition at line 1816 of file String.cpp.
References beast::CharPointer_UTF8::isByteOrderMark(), beast::CharPointer_UTF16::isByteOrderMarkBigEndian(), beast::CharPointer_UTF16::isByteOrderMarkLittleEndian(), beast::StringCreationHelper::result, beast::ByteOrder::swapIfBigEndian(), beast::ByteOrder::swapIfLittleEndian(), and beast::StringCreationHelper::write().
Referenced by beast::MemoryOutputStream::toString().
 {
     const std::uint8_t* const data = static_cast<const std::uint8_t*> (unknownData);
     if (size <= 0 || data == nullptr)
         return empty;
     if (size == 1)
         return charToString ((beast_wchar) data[0]);
     if (CharPointer_UTF16::isByteOrderMarkBigEndian (data)
          || CharPointer_UTF16::isByteOrderMarkLittleEndian (data))
     {
         const int numChars = size / 2 - 1;
         StringCreationHelper builder ((size_t) numChars);
         const std::uint16_t* const src = (const std::uint16_t*) (data + 2);
         if (CharPointer_UTF16::isByteOrderMarkBigEndian (data))
         {
             for (int i = 0; i < numChars; ++i)
                 builder.write ((beast_wchar) ByteOrder::swapIfLittleEndian (src[i]));
         }
         else
         {
             for (int i = 0; i < numChars; ++i)
                 builder.write ((beast_wchar) ByteOrder::swapIfBigEndian (src[i]));
         }
         builder.write (0);
         return builder.result;
     }
     const std::uint8_t* start = data;
     if (size >= 3 && CharPointer_UTF8::isByteOrderMark (data))
         start += 3;
     return String (CharPointer_UTF8 ((const char*) start),
                    CharPointer_UTF8 ((const char*) (data + size)));
 }
String beast::String::dropLastCharacters (int numberToDrop) const
Returns a version of this string with a number of characters removed from the end.
Parameters
numberToDrop the number of characters to drop from the end of the string. If this is greater than the length of the string, an empty string will be returned. If zero or less, the original string will be returned.
See Also
substring, fromFirstOccurrenceOf, upToFirstOccurrenceOf, fromLastOccurrenceOf, getLastCharacter
Definition at line 1350 of file String.cpp.
References beast::bmax().
Referenced by beast::File::getRelativePathFrom(), and beast::File::parseAbsolutePath().
 {
     return String (text, (size_t) bmax (0, length() - numberToDrop));
 }
bool beast::String::endsWith (const String & text) const noexcept
Tests whether the string ends with another string. If the parameter is an empty string, this will always return true. Uses a case-sensitive comparison.
Definition at line 1219 of file String.cpp.
 {
     CharPointerType end (text.findTerminatingNull());
     CharPointerType otherEnd (other.text.findTerminatingNull());
     while (end > text && otherEnd > other.text)
     {
         --end;
         --otherEnd;
         if (*end != *otherEnd)
             return false;
     }
     return otherEnd == other.text;
 }
bool beast::String::endsWithChar (beast_wchar character) const noexcept
Tests whether the string ends with a particular character. If the character is 0, this will always return false. Uses a case-sensitive comparison.
Definition at line 1208 of file String.cpp.
References bassert.
Referenced by beast::File::addTrailingSeparator(), beast::File::getNonexistentChildFile(), beast::File::getRelativePathFrom(), beast::File::parseAbsolutePath(), and quoted().
 {
     bassert (character != 0); // strings can't contain a null character!
     if (text.isEmpty())
         return false;
     CharPointerType t (text.findTerminatingNull());
     return *--t == character;
 }
bool beast::String::endsWithIgnoreCase (const String & text) const noexcept
Tests whether the string ends with another string. If the parameter is an empty string, this will always return true. Uses a case-insensitive comparison.
Definition at line 1236 of file String.cpp.
Referenced by beast::File::hasFileExtension().
 {
     CharPointerType end (text.findTerminatingNull());
     CharPointerType otherEnd (other.text.findTerminatingNull());
     while (end > text && otherEnd > other.text)
     {
         --end;
         --otherEnd;
         if (end.toLowerCase() != otherEnd.toLowerCase())
             return false;
     }
     return otherEnd == other.text;
 }
bool beast::String::equalsIgnoreCase (const String & other) const noexcept
Case-insensitive comparison with another string.
Definition at line 479 of file String.cpp.
Referenced by beast::FileHelpers::isFileOnDriveType().
 {
     return text == other.text
             || text.compareIgnoreCase (other.text) == 0;
 }
bool beast::String::equalsIgnoreCase (const wchar_t * other) const noexcept
Case-insensitive comparison with another string.
Definition at line 467 of file String.cpp.
References beast::castToCharPointer_wchar_t().
 {
     return t != nullptr ? text.compareIgnoreCase (castToCharPointer_wchar_t (t)) == 0
                         : isEmpty();
 }
bool beast::String::equalsIgnoreCase (const char * other) const noexcept
Case-insensitive comparison with another string.
Definition at line 473 of file String.cpp.
 {
     return t != nullptr ? text.compareIgnoreCase (CharPointer_UTF8 (t)) == 0
                         : isEmpty();
 }
String beast::String::formatted (const String formatString, ...) static
Creates a String from a printf-style parameter list.
I don't like this method. I don't use it myself, and I recommend avoiding it and using the operator<< methods or pretty much anything else instead. It's only provided here because of the popular unrest that was stirred-up when I tried to remove it...
If you're really determined to use it, at least make sure that you never, ever, pass any String objects to it as parameters. And bear in mind that internally, depending on the platform, it may be using wchar_t or char character types, so that even string literals can't be safely used as parameters if you're writing portable code.
Definition at line 1653 of file String.cpp.
References beast::HeapBlock< ElementType, throwOnFailure >::getData(), toUTF8(), and toWideCharPointer().
 {
     size_t bufferSize = 256;
     for (;;)
     {
         va_list args;
         va_start (args, pf);
        #if BEAST_WINDOWS
         HeapBlock <wchar_t> temp (bufferSize);
         const int num = (int) _vsnwprintf (temp.getData(), bufferSize - 1, pf.toWideCharPointer(), args);
        #elif BEAST_ANDROID
         HeapBlock <char> temp (bufferSize);
         const int num = (int) vsnprintf (temp.getData(), bufferSize - 1, pf.toUTF8(), args);
        #else
         HeapBlock <wchar_t> temp (bufferSize);
         const int num = (int) vswprintf (temp.getData(), bufferSize - 1, pf.toWideCharPointer(), args);
        #endif
         va_end (args);
         if (num > 0)
             return String (temp);
         bufferSize += 256;
         if (num == 0 || bufferSize > 65536) // the upper limit is a sanity check to avoid situations where vprintf repeatedly
             break;                          // returns -1 because of an error rather than because it needs more space.
     }
     return empty;
 }
String beast::String::fromFirstOccurrenceOf (const String & substringToStartFrom, bool includeSubStringInResult, bool ignoreCase) const
Returns a section of the string starting from a given substring.
This will search for the first occurrence of the given substring, and return the section of the string starting from the point where this is found (optionally not including the substring itself).
e.g. for the string "123456", fromFirstOccurrenceOf ("34", true) would return "3456", and fromFirstOccurrenceOf ("34", false) would return "56".
If the substring isn't found, the method will return an empty string.
If ignoreCase is true, the comparison will be case-insensitive.
See Also
upToFirstOccurrenceOf, fromLastOccurrenceOf
Definition at line 1360 of file String.cpp.
References length().
Referenced by beast::File::parseAbsolutePath(), and beast::resolveXDGFolder().
 {
     const int i = ignoreCase ? indexOfIgnoreCase (sub)
                              : indexOf (sub);
     if (i < 0)
         return empty;
     return substring (includeSubString ? i : i + sub.length());
 }
String beast::String::fromLastOccurrenceOf (const String & substringToFind, bool includeSubStringInResult, bool ignoreCase) const
Returns a section of the string starting from the last occurrence of a given substring.
Similar to fromFirstOccurrenceOf(), but using the last occurrence of the substring, and unlike fromFirstOccurrenceOf(), if the substring isn't found, this method will return the whole of the original string.
See Also
fromFirstOccurrenceOf, upToLastOccurrenceOf
Definition at line 1372 of file String.cpp.
References length().
 {
     const int i = ignoreCase ? lastIndexOfIgnoreCase (sub)
                              : lastIndexOf (sub);
     if (i < 0)
         return *this;
     return substring (includeSubString ? i : i + sub.length());
 }
template<typename Number > static String beast::String::fromNumber (Number number, int numberOfDecimalPlaces = -1) static
Create a string from a specific number type (integer or floating point) If numberOfDecimalPlaces is specified and number is a floating point type, the resulting string will have that many decimal places. A value below 0 means use exponent notation if necessary.
Referenced by ripple::Validators::Logic_test::addSources(), ripple::Validators::Logic::buildChosen(), beast::ServiceQueue_timing_test::Consumer< ServiceType >::do_handler(), beast::ServiceQueue_test::ServiceThread::do_handler(), ripple::Validators::Logic_test::TestSource::fetch(), beast::Debug::getSourceLocation(), ripple::Validators::Utilities::itos(), beast::asio::HTTPClient_test::print(), beast::ServiceQueue_timing_test::Producer< ServiceType >::run(), beast::Debug_test::run(), ripple::TestOverlay::Network1_test::testCreation(), ripple::Resource::Manager_test::testImports(), beast::HTTPVersion::toString(), beast::HTTPRequest::toString(), beast::HTTPResponse::toString(), beast::URL::toString(), ripple::Ledger::~Ledger(), and ripple::SHAMap::~SHAMap().
template<typename Number > String beast::String::fromNumber (Number number, int) inline
Definition at line 1254 of file String.h.
References beast::NumberToStringConverters::createFromInteger(), and String().
 {
     return String (NumberToStringConverters::createFromInteger
         <Number> (number), FromNumber ());
 }
template<> String beast::String::fromNumber (float number, int numberOfDecimalPlaces) inline
Definition at line 1261 of file String.h.
References beast::NumberToStringConverters::createFromDouble(), and floor().
 {
     if (numberOfDecimalPlaces == 0)
         number = std::floor (number);
     return String (NumberToStringConverters::createFromDouble (
         number, numberOfDecimalPlaces));
 }
template<> String beast::String::fromNumber (double number, int numberOfDecimalPlaces) inline
Definition at line 1270 of file String.h.
References beast::NumberToStringConverters::createFromDouble(), and floor().
 {
     if (numberOfDecimalPlaces == 0)
         number = std::floor (number);
     return String (NumberToStringConverters::createFromDouble (
         number, numberOfDecimalPlaces));
 }
String beast::String::fromUTF8 (const char * utf8buffer, int bufferSizeBytes = -1) static
Creates a String from a UTF-8 encoded buffer. If the size is < 0, it'll keep reading until it hits a zero.
Definition at line 1967 of file String.cpp.
References empty.
Referenced by beast::SystemStats::getEnvironmentVariable(), beast::File::getVolumeLabel(), and beast::InputStream::readNextLine().
 {
     if (buffer != nullptr)
     {
         if (bufferSizeBytes < 0) return String (CharPointer_UTF8 (buffer));
         if (bufferSizeBytes > 0) return String (CharPointer_UTF8 (buffer),
                                                 CharPointer_UTF8 (buffer + bufferSizeBytes));
     }
     return String::empty;
 }
size_t beast::String::getByteOffsetOfEnd () const private noexcept
Definition at line 400 of file String.cpp.
References beast::CharPointer_UTF8::findTerminatingNull(), beast::CharPointer_UTF8::getAddress(), and text.
Referenced by appendCharPointer(), repeatedString(), and replaceSection().
 {
     return (size_t) (((char*) text.findTerminatingNull().getAddress()) - (char*) text.getAddress());
 }
CharPointerType beast::String::getCharPointer () const inline noexcept
Returns the character pointer currently being used to store this string.
Because it returns a reference to the string's internal data, the pointer that is returned must not be stored anywhere, as it can be deleted whenever the string changes.
Definition at line 1048 of file String.h.
References text.
Referenced by beast::StringArray::addLines(), beast::StringArray::addTokens(), beast::StringEncodingConverter< CharPointerType_Src, CharPointerType_Dest >::convert(), beast::MemoryBlock::fromBase64Encoding(), beast::WindowsFileHelpers::getDriveFromPath(), beast::File::getRelativePathFrom(), beast::StringArray::joinIntoString(), beast::MemoryBlock::loadFromHexString(), beast::operator<<(), beast::asio::HTTPClientType::stringBuffer(), beast::MemoryBlock::toBase64Encoding(), and beast::OutputStream::writeText().
 { return text; }
double beast::String::getDoubleValue () const noexcept
Parses this string as a floating point number.
Returns
the value of the string as a 64-bit floating point value.
See Also
getFloatValue
Definition at line 1726 of file String.cpp.
 {
     return text.getDoubleValue();
 }
float beast::String::getFloatValue () const noexcept
Parses this string as a floating point number.
Returns
the value of the string as a 32-bit floating point value.
See Also
getDoubleValue
Definition at line 1721 of file String.cpp.
 {
     return (float) getDoubleValue();
 }
int beast::String::getHexValue32 () const noexcept
Parses the string as a hexadecimal number.
Non-hexadecimal characters in the string are ignored.
If the string contains too many characters, then the lowest significant digits are returned, e.g. "ffff12345678" would produce 0x12345678.
Returns
a 32-bit number which is the value of the string in hex.
Definition at line 1812 of file String.cpp.
References beast::HexConverter< Type >::stringToHex().
 { return HexConverter<int>  ::stringToHex (text); }
std::int64_t beast::String::getHexValue64 () const noexcept
Parses the string as a hexadecimal number.
Non-hexadecimal characters in the string are ignored.
If the string contains too many characters, then the lowest significant digits are returned, e.g. "ffff1234567812345678" would produce 0x1234567812345678.
Returns
a 64-bit number which is the value of the string in hex.
Definition at line 1813 of file String.cpp.
References beast::HexConverter< Type >::stringToHex().
 { return HexConverter<std::int64_t>::stringToHex (text); }
int beast::String::getIntValue () const noexcept
Reads the value of the string as a decimal number (up to 32 bits in size).
Returns
the value of the string as a 32 bit signed base-10 integer.
See Also
getTrailingIntValue, getHexValue32, getHexValue64
Definition at line 1688 of file String.cpp.
Referenced by beast::SemanticVersion::chopUInt(), beast::SemanticVersion::compare(), beast::MemoryBlock::fromBase64Encoding(), beast::File::getNonexistentChildFile(), beast::SemanticVersion::isNumeric(), and ripple::Config::setRpcIpAndOptionalPort().
 {
     return text.getIntValue32();
 }
std::int64_t beast::String::getLargeIntValue () const noexcept
Reads the value of the string as a decimal number (up to 64 bits in size).
Returns
the value of the string as a 64 bit signed base-10 integer.
Definition at line 1716 of file String.cpp.
 {
     return text.getIntValue64();
 }
beast_wchar beast::String::getLastCharacter () const noexcept
Returns the final character of the string. If the string is empty this will return 0.
Definition at line 1289 of file String.cpp.
Referenced by beast::File::getNonexistentChildFile().
 {
     return isEmpty() ? beast_wchar() : text [length() - 1];
 }
String beast::String::getLastCharacters (int numCharacters) const
Returns a number of characters from the end of the string.
This returns the last numCharacters characters from the end of the string. If the string is shorter than numCharacters, the whole string is returned.
See Also
substring, dropLastCharacters, getLastCharacter
Definition at line 1355 of file String.cpp.
References beast::bmax().
 {
     return String (text + bmax (0, length() - bmax (0, numCharacters)));
 }
size_t beast::String::getNumBytesAsUTF8 () const noexcept
Returns the number of bytes required to represent this string as UTF8. The number returned does NOT include the trailing zero.
See Also
toUTF8, copyToUTF8
Definition at line 1962 of file String.cpp.
References beast::CharPointer_UTF8::getBytesRequiredFor().
Referenced by beast::operator<<(), and beast::OutputStream::writeString().
 {
     return CharPointer_UTF8::getBytesRequiredFor (text);
 }
int beast::String::getTrailingIntValue () const noexcept
Parses a decimal number from the end of the string.
This will look for a value at the end of the string. e.g. for "321 xyz654" it will return 654; for "2 3 4" it'll return 4.
Negative numbers are not handled, so "xyz-5" returns 5.
See Also
getIntValue
Definition at line 1693 of file String.cpp.
 {
     int n = 0;
     int mult = 1;
     CharPointerType t (text.findTerminatingNull());
     while (--t >= text)
     {
         if (! t.isDigit())
         {
             if (*t == '-')
                 n = -n;
             break;
         }
         n += mult * (*t - '0');
         mult *= 10;
     }
     return n;
 }
std::size_t beast::String::hash () const noexcept
Returns a hash value suitable for use with std::hash.
Definition at line 444 of file String.cpp.
References beast::detail::HashGenerator< Type >::calculate().
Referenced by beast::hash_value().
 {
     return detail::HashGenerator<std::size_t>::calculate (text);
 }
int beast::String::hashCode () const noexcept
Generates a probably-unique 32-bit hashcode from this string.
Definition at line 434 of file String.cpp.
References beast::detail::HashGenerator< Type >::calculate().
Referenced by beast::File::hashCode().
 {
     return detail::HashGenerator<int> ::calculate (text);
 }
std::int64_t beast::String::hashCode64 () const noexcept
Generates a probably-unique 64-bit hashcode from this string.
Definition at line 439 of file String.cpp.
References beast::detail::HashGenerator< Type >::calculate().
Referenced by beast::File::hashCode64().
 {
     return detail::HashGenerator<std::int64_t> ::calculate (text);
 }
int beast::String::indexOf (const String & textToLookFor) const noexcept
Searches for a substring within this string. Uses a case-sensitive comparison.
Returns
the index of the first occurrence of this substring, or -1 if it's not found. If textToLookFor is an empty string, this will always return 0.
Definition at line 725 of file String.cpp.
Referenced by replace().
 {
     return other.isEmpty() ? 0 : text.indexOf (other.text);
 }
int beast::String::indexOf (int startIndex, const String & textToLookFor) const noexcept
Searches for a substring within this string. Uses a case-sensitive comparison.
Parameters
startIndex the index from which the search should proceed
textToLookFor the string to search for
Returns
the index of the first occurrence of this substring, or -1 if it's not found. If textToLookFor is an empty string, this will always return -1.
Definition at line 735 of file String.cpp.
References beast::CharPointer_UTF8::indexOf(), and beast::CharPointer_UTF8::isEmpty().
 {
     if (other.isEmpty())
         return -1;
     CharPointerType t (text);
     for (int i = startIndex; --i >= 0;)
     {
         if (t.isEmpty())
             return -1;
         ++t;
     }
     int found = t.indexOf (other.text);
     if (found >= 0)
         found += startIndex;
     return found;
 }
int beast::String::indexOfAnyOf (const String & charactersToLookFor, int startIndex = 0, bool ignoreCase = false) const noexcept
Returns the index of the first character that matches one of the characters passed-in to this method.
This scans the string, beginning from the startIndex supplied, and if it finds a character that appears in the string charactersToLookFor, it returns its index.
If none of these characters are found, it returns -1.
If ignoreCase is true, the comparison will be case-insensitive.
See Also
indexOfChar, lastIndexOfAnyOf
Definition at line 705 of file String.cpp.
References beast::CharPointer_UTF8::getAndAdvance(), and beast::CharPointer_UTF8::isEmpty().
 {
     CharPointerType t (text);
     for (int i = 0; ! t.isEmpty(); ++i)
     {
         if (i >= startIndex)
         {
             if (charactersToLookFor.text.indexOf (t.getAndAdvance(), ignoreCase) >= 0)
                 return i;
         }
         else
         {
             ++t;
         }
     }
     return -1;
 }
int beast::String::indexOfChar (beast_wchar characterToLookFor) const noexcept
Searches for a character inside this string. Uses a case-sensitive comparison.
Returns
the index of the first occurrence of the character in this string, or -1 if it's not found.
Definition at line 668 of file String.cpp.
Referenced by beast::MemoryBlock::fromBase64Encoding(), beast::File::hasFileExtension(), beast::File::parseAbsolutePath(), ripple::parseDelimitedKeyValueString(), ripple::parseKeyValueSection(), beast::RegistryKeyWrapper::RegistryKeyWrapper(), replaceCharacters(), beast::Debug::withEscapedQuotes(), and beast::Debug::withUnescapedQuotes().
 {
     return text.indexOf (character);
 }
int beast::String::indexOfChar (int startIndex, beast_wchar characterToLookFor) const noexcept
Searches for a character inside this string. Uses a case-sensitive comparison.
Parameters
startIndex the index from which the search should proceed
characterToLookFor the character to look for
Returns
the index of the first occurrence of the character in this string, or -1 if it's not found.
Definition at line 673 of file String.cpp.
References beast::CharPointer_UTF8::getAndAdvance(), and beast::CharPointer_UTF8::isEmpty().
 {
     CharPointerType t (text);
     for (int i = 0; ! t.isEmpty(); ++i)
     {
         if (i >= startIndex)
         {
             if (t.getAndAdvance() == character)
                 return i;
         }
         else
         {
             ++t;
         }
     }
     return -1;
 }
int beast::String::indexOfIgnoreCase (const String & textToLookFor) const noexcept
Searches for a substring within this string. Uses a case-insensitive comparison.
Returns
the index of the first occurrence of this substring, or -1 if it's not found. If textToLookFor is an empty string, this will always return 0.
Definition at line 730 of file String.cpp.
References beast::CharacterFunctions::indexOfIgnoreCase().
Referenced by replace().
 {
     return other.isEmpty() ? 0 : CharacterFunctions::indexOfIgnoreCase (text, other.text);
 }
int beast::String::indexOfIgnoreCase (int startIndex, const String & textToLookFor) const noexcept
Searches for a substring within this string. Uses a case-insensitive comparison.
Parameters
startIndex the index from which the search should proceed
textToLookFor the string to search for
Returns
the index of the first occurrence of this substring, or -1 if it's not found. If textToLookFor is an empty string, this will always return -1.
Definition at line 756 of file String.cpp.
References beast::CharacterFunctions::indexOfIgnoreCase(), and beast::CharPointer_UTF8::isEmpty().
 {
     if (other.isEmpty())
         return -1;
     CharPointerType t (text);
     for (int i = startIndex; --i >= 0;)
     {
         if (t.isEmpty())
             return -1;
         ++t;
     }
     int found = CharacterFunctions::indexOfIgnoreCase (t, other.text);
     if (found >= 0)
         found += startIndex;
     return found;
 }
int beast::String::indexOfWholeWord (const String & wordToLookFor) const noexcept
Finds an instance of another substring if it exists as a distinct word.
Returns
if the string contains this word, surrounded by non-alphanumeric characters, then this will return the index of the start of the substring. If it isn't found, then it will return -1
See Also
indexOfWholeWordIgnoreCase, containsWholeWord
Definition at line 854 of file String.cpp.
References beast::CharPointer_UTF8::compareUpTo(), and beast::CharPointer_UTF8::length().
 {
     if (word.isNotEmpty())
     {
         CharPointerType t (text);
         const int wordLen = word.length();
         const int end = (int) t.length() - wordLen;
         for (int i = 0; i <= end; ++i)
         {
             if (t.compareUpTo (word.text, wordLen) == 0
                   && (i == 0 || ! (t - 1).isLetterOrDigit())
                   && ! (t + wordLen).isLetterOrDigit())
                 return i;
             ++t;
         }
     }
     return -1;
 }
int beast::String::indexOfWholeWordIgnoreCase (const String & wordToLookFor) const noexcept
Finds an instance of another substring if it exists as a distinct word.
Returns
if the string contains this word, surrounded by non-alphanumeric characters, then this will return the index of the start of the substring. If it isn't found, then it will return -1
See Also
indexOfWholeWord, containsWholeWordIgnoreCase
Definition at line 876 of file String.cpp.
References beast::CharPointer_UTF8::compareIgnoreCaseUpTo(), and beast::CharPointer_UTF8::length().
 {
     if (word.isNotEmpty())
     {
         CharPointerType t (text);
         const int wordLen = word.length();
         const int end = (int) t.length() - wordLen;
         for (int i = 0; i <= end; ++i)
         {
             if (t.compareIgnoreCaseUpTo (word.text, wordLen) == 0
                   && (i == 0 || ! (t - 1).isLetterOrDigit())
                   && ! (t + wordLen).isLetterOrDigit())
                 return i;
             ++t;
         }
     }
     return -1;
 }
String beast::String::initialSectionContainingOnly (const String & permittedCharacters) const
Returns a section from the start of the string that only contains a certain set of characters.
This returns the leftmost section of the string, up to (and not including) the first character that doesn't appear in the string passed in.
Definition at line 1585 of file String.cpp.
References containsChar(), and beast::CharPointer_UTF8::isEmpty().
 {
     CharPointerType t (text);
     while (! t.isEmpty())
     {
         if (! permittedCharacters.containsChar (*t))
             return String (text, t);
         ++t;
     }
     return *this;
 }
String beast::String::initialSectionNotContaining (const String & charactersToStopAt) const
Returns a section from the start of the string that only contains a certain set of characters.
This returns the leftmost section of the string, up to (and not including) the first character that occurs in the string passed in. (If none of the specified characters are found in the string, the return value will just be the original string).
Definition at line 1600 of file String.cpp.
References containsChar(), and beast::CharPointer_UTF8::isEmpty().
 {
     CharPointerType t (text);
     while (! t.isEmpty())
     {
         if (charactersToStopAt.containsChar (*t))
             return String (text, t);
         ++t;
     }
     return *this;
 }
bool beast::String::isEmpty () const inline noexcept
Returns true if the string contains no characters. Note that there's also an isNotEmpty() method to help write readable code.
See Also
containsNonWhitespaceChars()
Definition at line 306 of file String.h.
Referenced by beast::StringEncodingConverter< CharPointerType_Src, CharPointerType_Dest >::convert(), beast::File::hasFileExtension(), beast::File::isDirectory(), beast::StringArray::joinIntoString(), beast::DynamicLibrary::open(), beast::File::parseAbsolutePath(), beast::Result::wasOk(), and beast::File::withFileExtension().
 { return text[0] == 0; }
bool beast::String::isNotEmpty () const inline noexcept
Returns true if the string contains at least one character. Note that there's also an isEmpty() method to help write readable code.
See Also
containsNonWhitespaceChars()
Definition at line 312 of file String.h.
Referenced by beast::File::exists(), beast::Result::failed(), beast::WindowsFileHelpers::getDriveFromPath(), beast::File::isAbsolutePath(), beast::Result::operator!(), ripple::parseDelimitedKeyValueString(), ripple::Validators::Utilities::stringToTime(), beast::Thread::threadEntryPoint(), and beast::File::withFileExtension().
 { return text[0] != 0; }
bool beast::String::isQuotedString () const
Checks whether the string might be in quotation marks.
Returns
true if the string begins with a quote character (either a double or single quote). It is also true if there is whitespace before the quote, but it doesn't check the end of the string.
See Also
unquoted, quoted
Definition at line 1408 of file String.cpp.
 {
     const String trimmed (trimStart());
     return trimmed[0] == '"'
         || trimmed[0] == '\'';
 }
int beast::String::lastIndexOf (const String & textToLookFor) const noexcept
Searches for a substring inside this string (working backwards from the end of the string). Uses a case-sensitive comparison.
Returns
the index of the start of the last occurrence of the substring within this string, or -1 if it's not found. If textToLookFor is an empty string, this will always return -1.
Definition at line 777 of file String.cpp.
References beast::CharPointer_UTF8::compareUpTo().
 {
     if (other.isNotEmpty())
     {
         const int len = other.length();
         int i = length() - len;
         if (i >= 0)
         {
             CharPointerType n (text + i);
             while (i >= 0)
             {
                 if (n.compareUpTo (other.text, len) == 0)
                     return i;
                 --n;
                 --i;
             }
         }
     }
     return -1;
 }
int beast::String::lastIndexOfAnyOf (const String & charactersToLookFor, bool ignoreCase = false) const noexcept
Returns the index of the last character in this string that matches one of the characters passed-in to this method.
This scans the string backwards, starting from its end, and if it finds a character that appears in the string charactersToLookFor, it returns its index.
If none of these characters are found, it returns -1.
If ignoreCase is true, the comparison will be case-insensitive.
See Also
lastIndexOf, indexOfAnyOf
Definition at line 827 of file String.cpp.
References beast::CharPointer_UTF8::getAndAdvance(), and beast::CharPointer_UTF8::isEmpty().
 {
     CharPointerType t (text);
     int last = -1;
     for (int i = 0; ! t.isEmpty(); ++i)
         if (charactersToLookFor.text.indexOf (t.getAndAdvance(), ignoreCase) >= 0)
             last = i;
     return last;
 }
int beast::String::lastIndexOfChar (beast_wchar character) const noexcept
Searches for a character inside this string (working backwards from the end of the string). Uses a case-sensitive comparison.
Returns
the index of the last occurrence of the character in this string, or -1 if it's not found.
Definition at line 693 of file String.cpp.
References beast::CharPointer_UTF8::getAndAdvance(), and beast::CharPointer_UTF8::isEmpty().
Referenced by beast::File::getChildFile(), beast::File::getFileExtension(), beast::File::getFileName(), beast::Debug::getFileNameFromPath(), beast::File::getFileNameWithoutExtension(), beast::File::getNonexistentChildFile(), beast::File::getPathUpToLastSlash(), beast::File::hasFileExtension(), beast::RegistryKeyWrapper::RegistryKeyWrapper(), ripple::Config::setRpcIpAndOptionalPort(), and beast::File::withFileExtension().
 {
     CharPointerType t (text);
     int last = -1;
     for (int i = 0; ! t.isEmpty(); ++i)
         if (t.getAndAdvance() == character)
             last = i;
     return last;
 }
int beast::String::lastIndexOfIgnoreCase (const String & textToLookFor) const noexcept
Searches for a substring inside this string (working backwards from the end of the string). Uses a case-insensitive comparison.
Returns
the index of the start of the last occurrence of the substring within this string, or -1 if it's not found. If textToLookFor is an empty string, this will always return -1.
Definition at line 802 of file String.cpp.
References beast::CharPointer_UTF8::compareIgnoreCaseUpTo().
 {
     if (other.isNotEmpty())
     {
         const int len = other.length();
         int i = length() - len;
         if (i >= 0)
         {
             CharPointerType n (text + i);
             while (i >= 0)
             {
                 if (n.compareIgnoreCaseUpTo (other.text, len) == 0)
                     return i;
                 --n;
                 --i;
             }
         }
     }
     return -1;
 }
int beast::String::length () const noexcept
Returns the number of characters in the string.
Definition at line 395 of file String.cpp.
References beast::CharPointer_UTF8::length(), and text.
Referenced by beast::SemanticVersion::chop(), beast::SemanticVersion::chopIdentifier(), beast::SemanticVersion::chopIdentifiers(), beast::SemanticVersion::chopUInt(), beast::Debug::commandLineToString(), beast::File::createLegalFileName(), beast::ServiceQueue_timing_test::Consumer< ServiceType >::do_handler(), beast::ServiceQueue_test::ServiceThread::do_handler(), beast::MemoryBlock::fromBase64Encoding(), fromFirstOccurrenceOf(), fromLastOccurrenceOf(), ripple::MultiSocket_test::MultiSocketDetails::getArgName(), beast::File::hasFileExtension(), beast::File::isAChildOf(), beast::MemoryBlock::loadFromHexString(), beast::SemanticVersion::parse(), ripple::parseDelimitedKeyValueString(), replace(), beast::ServiceQueue_timing_test::Producer< ServiceType >::run(), beast::asio::HTTPClientType::stringBuffer(), beast::MemoryBlock::toBase64Encoding(), upToFirstOccurrenceOf(), upToLastOccurrenceOf(), and Json::Value::Value().
 {
     return (int) text.length();
 }
bool beast::String::matchesWildcard (const String & wildcard, bool ignoreCase) const noexcept
Returns true if the string matches this simple wildcard expression.
So for example String ("abcdef").matchesWildcard ("*DEF", true) would return true.
This isn't a full-blown regex though! The only wildcard characters supported are "*" and "?". It's mainly intended for filename pattern matching.
Definition at line 945 of file String.cpp.
References beast::WildCardMatcher< CharPointer >::matches().
Referenced by beast::fileMatches().
 {
     return WildCardMatcher<CharPointerType>::matches (wildcard.text, text, ignoreCase);
 }
beast::String::operator bool () const inline private noexcept
Definition at line 1248 of file String.h.
 { return false; }
String & beast::String::operator+= (const String & stringToAppend)
Appends another string at the end of this one.
Definition at line 563 of file String.cpp.
References text.
 {
     if (isEmpty())
         return operator= (other);
     appendCharPointer (other.text);
     return *this;
 }
String & beast::String::operator+= (const char * textToAppend)
Appends another string at the end of this one.
Definition at line 542 of file String.cpp.
References bassert, beast::CharPointer_ASCII::isValidString(), and ripple::max().
 {
     /*  If you get an assertion here, then you're trying to create a string from 8-bit data
         that contains values greater than 127. These can NOT be correctly converted to unicode
         because there's no way for the String class to know what encoding was used to
         create them. The source data could be UTF-8, ASCII or one of many local code-pages.
         To get around this problem, you must be more explicit when you pass an ambiguous 8-bit
         string to the String class - so for example if your source data is actually UTF-8,
         you'd call String (CharPointer_UTF8 ("my utf8 string..")), and it would be able to
         correctly convert the multi-byte characters to unicode. It's *highly* recommended that
         you use UTF-8 with escape characters in your source code to represent extended characters,
         because there's no other way to represent these strings in a way that isn't dependent on
         the compiler, source code editor and platform.
     */
     bassert (t == nullptr || CharPointer_ASCII::isValidString (t, std::numeric_limits<int>::max()));
     appendCharPointer (CharPointer_ASCII (t));
     return *this;
 }
String & beast::String::operator+= (const wchar_t * textToAppend)
Appends another string at the end of this one.
Definition at line 536 of file String.cpp.
References beast::castToCharPointer_wchar_t().
 {
     appendCharPointer (castToCharPointer_wchar_t (t));
     return *this;
 }
String & beast::String::operator+= (int numberToAppend)
Appends a decimal number at the end of this string.
Definition at line 593 of file String.cpp.
References beast::addBytesToPointer(), beast::StringHolder::makeUniqueWithByteSize(), beast::NumberToStringConverters::numberToString(), beast::numElementsInArray(), and beast::CharPointer_UTF8::writeWithCharLimit().
 {
     char buffer [16];
     char* const end = buffer + numElementsInArray (buffer);
     char* const start = NumberToStringConverters::numberToString (end, number);
     const int numExtraChars = (int) (end - start);
     if (numExtraChars > 0)
     {
         const size_t byteOffsetOfNull = getByteOffsetOfEnd();
         const size_t newBytesNeeded = sizeof (CharPointerType::CharType) + byteOffsetOfNull
                                         + sizeof (CharPointerType::CharType) * (size_t) numExtraChars;
         text = StringHolder::makeUniqueWithByteSize (text, newBytesNeeded);
         CharPointerType newEnd (addBytesToPointer (text.getAddress(), (int) byteOffsetOfNull));
         newEnd.writeWithCharLimit (CharPointer_ASCII (start), numExtraChars);
     }
     return *this;
 }
String & beast::String::operator+= (char characterToAppend)
Appends a character at the end of this string.
Definition at line 572 of file String.cpp.
 {
     const char asString[] = { ch, 0 };
     return operator+= (asString);
 }
String & beast::String::operator+= (wchar_t characterToAppend)
Appends a character at the end of this string.
Definition at line 578 of file String.cpp.
 {
     const wchar_t asString[] = { ch, 0 };
     return operator+= (asString);
 }
String & beast::String::operator= (const String & other) noexcept
Replaces this string's contents with another string.
Definition at line 285 of file String.cpp.
References beast::StringHolder::release(), and beast::StringHolder::retain().
 {
     StringHolder::retain (other.text);
     StringHolder::release (text.atomicSwap (other.text));
     return *this;
 }
beast_wchar beast::String::operator[] (int index) const noexcept
Returns the character at this index in the string. In a release build, no checks are made to see if the index is within a valid range, so be careful! In a debug build, the index is checked and an assertion fires if it's out-of-range.
Also beware that depending on the encoding format that the string is using internally, this method may execute in either O(1) or O(n) time, so be careful when using it in your algorithms. If you're scanning through a string to inspect its characters, you should never use this operator for random access, it's far more efficient to call getCharPointer() to return a pointer, and then to use that to iterate the string.
See Also
getCharPointer
Definition at line 405 of file String.cpp.
References bassert.
 {
     bassert (index == 0 || (index > 0 && index <= (int) text.lengthUpTo ((size_t) index + 1)));
     return text [index];
 }
String beast::String::paddedLeft (beast_wchar padCharacter, int minimumLength) const
Returns a copy of this string with the specified character repeatedly added to its beginning until the total length is at least the minimum length specified.
Definition at line 965 of file String.cpp.
References bassert, beast::CharPointer_UTF8::getAddress(), beast::CharPointer_UTF8::isEmpty(), text, beast::CharPointer_UTF8::write(), and beast::CharPointer_UTF8::writeAll().
Referenced by ripple::Validators::Utilities::itos().
 {
     bassert (padCharacter != 0);
     int extraChars = minimumLength;
     CharPointerType end (text);
     while (! end.isEmpty())
     {
         --extraChars;
         ++end;
     }
     if (extraChars <= 0 || padCharacter == 0)
         return *this;
     const size_t currentByteSize = (size_t) (((char*) end.getAddress()) - (char*) text.getAddress());
     String result (PreallocationBytes (currentByteSize + (size_t) extraChars * CharPointerType::getBytesRequiredFor (padCharacter)));
     CharPointerType n (result.text);
     while (--extraChars >= 0)
         n.write (padCharacter);
     n.writeAll (text);
     return result;
 }
String beast::String::paddedRight (beast_wchar padCharacter, int minimumLength) const
Returns a copy of this string with the specified character repeatedly added to its end until the total length is at least the minimum length specified.
Definition at line 992 of file String.cpp.
References bassert, beast::CharPointer_UTF8::getAddress(), beast::CharPointer_UTF8::isEmpty(), text, beast::CharPointer_UTF8::write(), beast::CharPointer_UTF8::writeAll(), and beast::CharPointer_UTF8::writeNull().
 {
     bassert (padCharacter != 0);
     int extraChars = minimumLength;
     CharPointerType end (text);
     while (! end.isEmpty())
     {
         --extraChars;
         ++end;
     }
     if (extraChars <= 0 || padCharacter == 0)
         return *this;
     const size_t currentByteSize = (size_t) (((char*) end.getAddress()) - (char*) text.getAddress());
     String result (PreallocationBytes (currentByteSize + (size_t) extraChars * CharPointerType::getBytesRequiredFor (padCharacter)));
     CharPointerType n (result.text);
     n.writeAll (text);
     while (--extraChars >= 0)
         n.write (padCharacter);
     n.writeNull();
     return result;
 }
void beast::String::preallocateBytes (size_t numBytesNeeded)
Increases the string's internally allocated storage.
Although the string's contents won't be affected by this call, it will increase the amount of memory allocated internally for the string to grow into.
If you're about to make a large number of calls to methods such as += or <<, it's more efficient to preallocate enough extra space beforehand, so that these methods won't have to keep resizing the string to append the extra characters.
Parameters
numBytesNeeded the number of bytes to allocate storage for. If this value is less than the currently allocated size, it will have no effect.
Definition at line 257 of file String.cpp.
References beast::StringHolder::makeUniqueWithByteSize(), and text.
Referenced by appendCharPointer(), beast::StringEncodingConverter< CharPointerType_Src, CharPointerType_Dest >::convert(), beast::FatalError::Reporter::formatMessage(), beast::RelativeTime::getDescription(), beast::StringArray::joinIntoString(), and beast::MemoryBlock::toBase64Encoding().
 {
     text = StringHolder::makeUniqueWithByteSize (
         text, numBytesNeeded + sizeof (CharPointerType::CharType));
 }
String beast::String::quoted (beast_wchar quoteCharacter = '"') const
Adds quotation marks around a string.
This will return a copy of the string with a quote at the start and end, (but won't add the quote if there's already one there, so it's safe to call this on strings that may already have quotes around them).
Note that this is a const method, and won't alter the string itself.
Parameters
quoteCharacter the character to add at the start and end
See Also
isQuotedString, unquoted
Definition at line 1430 of file String.cpp.
References endsWithChar(), and startsWithChar().
Referenced by beast::Process::openDocument().
 {
     if (isEmpty())
         return charToString (quoteCharacter) + quoteCharacter;
     String t (*this);
     if (! t.startsWithChar (quoteCharacter))
         t = charToString (quoteCharacter) + t;
     if (! t.endsWithChar (quoteCharacter))
         t += quoteCharacter;
     return t;
 }
String beast::String::removeCharacters (const String & charactersToRemove) const
Returns a version of this string with a set of characters removed.
This will return a copy of this string, omitting any characters which are found in the string passed-in.
e.g. for "1122334455", removeCharacters ("432") would return "1155"
Note that this is a const method, and won't alter the string itself.
Definition at line 1564 of file String.cpp.
References containsChar(), beast::CharPointer_UTF8::getAndAdvance(), beast::StringCreationHelper::result, beast::StringCreationHelper::source, and beast::StringCreationHelper::write().
Referenced by beast::File::createLegalFileName(), and beast::File::createLegalPathName().
 {
     if (isEmpty())
         return empty;
     StringCreationHelper builder (text);
     for (;;)
     {
         beast_wchar c = builder.source.getAndAdvance();
         if (! charactersToRemove.containsChar (c))
             builder.write (c);
         if (c == 0)
             break;
     }
     return builder.result;
 }
String beast::String::repeatedString (const String & stringToRepeat, int numberOfTimesToRepeat) static
Creates a string which is a version of a string repeated and joined together.
Parameters
stringToRepeat the string to repeat
numberOfTimesToRepeat how many times to repeat it
Definition at line 951 of file String.cpp.
References getByteOffsetOfEnd(), and text.
Referenced by beast::File::getRelativePathFrom().
 {
     if (numberOfTimesToRepeat <= 0)
         return empty;
     String result (PreallocationBytes (stringToRepeat.getByteOffsetOfEnd() * (size_t) numberOfTimesToRepeat));
     CharPointerType n (result.text);
     while (--numberOfTimesToRepeat >= 0)
         n.writeAll (stringToRepeat.text);
     return result;
 }
String beast::String::replace (const String & stringToReplace, const String & stringToInsertInstead, bool ignoreCase = false) const
Replaces all occurrences of a substring with another string.
Returns a copy of this string, with any occurrences of stringToReplace swapped for stringToInsertInstead.
Note that this is a const method, and won't alter the string itself.
Definition at line 1088 of file String.cpp.
References indexOf(), indexOfIgnoreCase(), length(), and replaceSection().
Referenced by beast::Process::openDocument(), and beast::resolveXDGFolder().
 {
     const int stringToReplaceLen = stringToReplace.length();
     const int stringToInsertLen = stringToInsert.length();
     int i = 0;
     String result (*this);
     while ((i = (ignoreCase ? result.indexOfIgnoreCase (i, stringToReplace)
                             : result.indexOf (i, stringToReplace))) >= 0)
     {
         result = result.replaceSection (i, stringToReplaceLen, stringToInsert);
         i += stringToInsertLen;
     }
     return result;
 }
String beast::String::replaceCharacter (beast_wchar characterToReplace, beast_wchar characterToInsertInstead) const
Returns a string with all occurrences of a character replaced with a different one.
Definition at line 1146 of file String.cpp.
References beast::CharPointer_UTF8::getAndAdvance(), beast::StringCreationHelper::result, beast::StringCreationHelper::source, and beast::StringCreationHelper::write().
Referenced by beast::File::getChildFile(), beast::Debug::getFileNameFromPath(), and beast::File::parseAbsolutePath().
 {
     if (! containsChar (charToReplace))
         return *this;
     StringCreationHelper builder (text);
     for (;;)
     {
         beast_wchar c = builder.source.getAndAdvance();
         if (c == charToReplace)
             c = charToInsert;
         builder.write (c);
         if (c == 0)
             break;
     }
     return builder.result;
 }
String beast::String::replaceCharacters (const String & charactersToReplace, const String & charactersToInsertInstead) const
Replaces a set of characters with another set.
Returns a string in which each character from charactersToReplace has been replaced by the character at the equivalent position in newCharacters (so the two strings passed in must be the same length).
e.g. replaceCharacters ("abc", "def") replaces 'a' with 'd', 'b' with 'e', etc.
Note that this is a const method, and won't affect the string itself.
Definition at line 1169 of file String.cpp.
References beast::CharPointer_UTF8::getAndAdvance(), indexOfChar(), beast::StringCreationHelper::result, beast::StringCreationHelper::source, and beast::StringCreationHelper::write().
 {
     StringCreationHelper builder (text);
     for (;;)
     {
         beast_wchar c = builder.source.getAndAdvance();
         const int index = charactersToReplace.indexOfChar (c);
         if (index >= 0)
             c = charactersToInsertInstead [index];
         builder.write (c);
         if (c == 0)
             break;
     }
     return builder.result;
 }
String beast::String::replaceSection (int startIndex, int numCharactersToReplace, const String & stringToInsert) const
Replaces a sub-section of the string with another string.
This will return a copy of this string, with a set of characters from startIndex to startIndex + numCharsToReplace removed, and with a new string inserted in their place.
Note that this is a const method, and won't alter the string itself.
Parameters
startIndex the first character to remove. If this is beyond the bounds of the string, it will be constrained to a valid range.
numCharactersToReplace the number of characters to remove. If zero or less, no characters will be taken out.
stringToInsert the new string to insert at startIndex after the characters have been removed.
Definition at line 1022 of file String.cpp.
References bassertfalse, empty, beast::CharPointer_UTF8::findTerminatingNull(), beast::CharPointer_UTF8::getAddress(), getByteOffsetOfEnd(), beast::CharPointer_UTF8::isEmpty(), text, and beast::CharPointer_UTF8::writeNull().
Referenced by replace().
 {
     if (index < 0)
     {
         // a negative index to replace from?
         bassertfalse;
         index = 0;
     }
     if (numCharsToReplace < 0)
     {
         // replacing a negative number of characters?
         numCharsToReplace = 0;
         bassertfalse;
     }
     int i = 0;
     CharPointerType insertPoint (text);
     while (i < index)
     {
         if (insertPoint.isEmpty())
         {
             // replacing beyond the end of the string?
             bassertfalse;
             return *this + stringToInsert;
         }
         ++insertPoint;
         ++i;
     }
     CharPointerType startOfRemainder (insertPoint);
     i = 0;
     while (i < numCharsToReplace && ! startOfRemainder.isEmpty())
     {
         ++startOfRemainder;
         ++i;
     }
     if (insertPoint == text && startOfRemainder.isEmpty())
         return stringToInsert;
     const size_t initialBytes = (size_t) (((char*) insertPoint.getAddress()) - (char*) text.getAddress());
     const size_t newStringBytes = stringToInsert.getByteOffsetOfEnd();
     const size_t remainderBytes = (size_t) (((char*) startOfRemainder.findTerminatingNull().getAddress()) - (char*) startOfRemainder.getAddress());
     const size_t newTotalBytes = initialBytes + newStringBytes + remainderBytes;
     if (newTotalBytes <= 0)
         return String::empty;
     String result (PreallocationBytes ((size_t) newTotalBytes));
     char* dest = (char*) result.text.getAddress();
     memcpy (dest, text.getAddress(), initialBytes);
     dest += initialBytes;
     memcpy (dest, stringToInsert.text.getAddress(), newStringBytes);
     dest += newStringBytes;
     memcpy (dest, startOfRemainder.getAddress(), remainderBytes);
     dest += remainderBytes;
     CharPointerType ((CharPointerType::CharType*) dest).writeNull();
     return result;
 }
String beast::String::retainCharacters (const String & charactersToRetain) const
Returns a version of this string that only retains a fixed set of characters.
This will return a copy of this string, omitting any characters which are not found in the string passed-in.
e.g. for "1122334455", retainCharacters ("432") would return "223344"
Note that this is a const method, and won't alter the string itself.
Definition at line 1542 of file String.cpp.
References containsChar(), beast::CharPointer_UTF8::getAndAdvance(), beast::StringCreationHelper::result, beast::StringCreationHelper::source, and beast::StringCreationHelper::write().
 {
     if (isEmpty())
         return empty;
     StringCreationHelper builder (text);
     for (;;)
     {
         beast_wchar c = builder.source.getAndAdvance();
         if (charactersToRetain.containsChar (c))
             builder.write (c);
         if (c == 0)
             break;
     }
     builder.write (0);
     return builder.result;
 }
bool beast::String::startsWith (const String & text) const noexcept
Tests whether the string begins with another string. If the parameter is an empty string, this will always return true. Uses a case-sensitive comparison.
Definition at line 1191 of file String.cpp.
Referenced by beast::SemanticVersion::chop(), beast::File::parseAbsolutePath(), and beast::resolveXDGFolder().
 {
     return text.compareUpTo (other.text, other.length()) == 0;
 }
bool beast::String::startsWithChar (beast_wchar character) const noexcept
Tests whether the string begins with a particular character. If the character is 0, this will always return false. Uses a case-sensitive comparison.
Definition at line 1201 of file String.cpp.
References bassert.
Referenced by beast::File::hasFileExtension(), beast::File::isAbsolutePath(), beast::File::isHidden(), beast::FileHelpers::isHiddenFile(), beast::DirectoryIterator::NativeIterator::Pimpl::next(), beast::File::parseAbsolutePath(), quoted(), and beast::File::withFileExtension().
 {
     bassert (character != 0); // strings can't contain a null character!
     return *text == character;
 }
bool beast::String::startsWithIgnoreCase (const String & text) const noexcept
Tests whether the string begins with another string. If the parameter is an empty string, this will always return true. Uses a case-insensitive comparison.
Definition at line 1196 of file String.cpp.
Referenced by beast::RegistryKeyWrapper::RegistryKeyWrapper().
 {
     return text.compareIgnoreCaseUpTo (other.text, other.length()) == 0;
 }
String beast::String::substring (int startIndex, int endIndex) const
Returns a subsection of the string.
If the range specified is beyond the limits of the string, as much as possible is returned.
Parameters
startIndex the index of the start of the substring needed
endIndex all characters from startIndex up to (but not including) this index are returned
See Also
fromFirstOccurrenceOf, dropLastCharacters, getLastCharacters, upToFirstOccurrenceOf
Definition at line 1294 of file String.cpp.
References beast::CharPointer_UTF8::isEmpty().
Referenced by beast::SemanticVersion::chop(), beast::SemanticVersion::chopIdentifier(), beast::SemanticVersion::chopUInt(), beast::Debug::commandLineToString(), beast::File::createLegalPathName(), beast::MemoryBlock::fromBase64Encoding(), ripple::MultiSocket_test::MultiSocketDetails::getArgName(), beast::File::getChildFile(), beast::File::getFileExtension(), beast::File::getFileName(), beast::Debug::getFileNameFromPath(), beast::File::getFileNameWithoutExtension(), beast::File::getNonexistentChildFile(), beast::File::getPathUpToLastSlash(), beast::Time::getTimeZone(), beast::File::hasFileExtension(), beast::File::parseAbsolutePath(), ripple::parseDelimitedKeyValueString(), ripple::parseKeyValueSection(), beast::RegistryKeyWrapper::RegistryKeyWrapper(), ripple::Config::setRpcIpAndOptionalPort(), ripple::Validators::Utilities::stoi(), beast::Debug::withEscapedQuotes(), beast::File::withFileExtension(), and beast::Debug::withUnescapedQuotes().
 {
     if (start < 0)
         start = 0;
     if (end <= start)
         return empty;
     int i = 0;
     CharPointerType t1 (text);
     while (i < start)
     {
         if (t1.isEmpty())
             return empty;
         ++i;
         ++t1;
     }
     CharPointerType t2 (t1);
     while (i < end)
     {
         if (t2.isEmpty())
         {
             if (start == 0)
                 return *this;
             break;
         }
         ++i;
         ++t2;
     }
     return String (t1, t2);
 }
String beast::String::substring (int startIndex) const
Returns a section of the string, starting from a given position.
Parameters
startIndex the first character to include. If this is beyond the end of the string, an empty string is returned. If it is zero or less, the whole string is returned.
Returns
the substring from startIndex up to the end of the string
See Also
dropLastCharacters, getLastCharacters, fromFirstOccurrenceOf, upToFirstOccurrenceOf, fromLastOccurrenceOf
Definition at line 1332 of file String.cpp.
References beast::CharPointer_UTF8::isEmpty().
 {
     if (start <= 0)
         return *this;
     CharPointerType t (text);
     while (--start >= 0)
     {
         if (t.isEmpty())
             return empty;
         ++t;
     }
     return String (t);
 }
void beast::String::swapWith (String & other) noexcept
Swaps the contents of this string with another one. This is a very fast operation, as no allocation or copying needs to be done.
Definition at line 280 of file String.cpp.
References beast::asio::swap().
 {
     std::swap (text, other.text);
 }
String beast::String::toHexString (int number) static
Creates a string representing this 32-bit value in hexadecimal.
Definition at line 1769 of file String.cpp.
Referenced by beast::beast_getOutputFromCommand(), beast::File::createTempFile(), beast::ObjCClass< SuperclassType >::getRandomisedName(), and beast::SystemStats::getStackBacktrace().
 {
     return HexConverter <unsigned int>::hexToString ((unsigned int) number);
 }
String beast::String::toHexString (std::int64_t number) static
Creates a string representing this 64-bit value in hexadecimal.
Definition at line 1774 of file String.cpp.
 {
     return HexConverter <std::uint64_t>::hexToString ((std::uint64_t) number);
 }
String beast::String::toHexString (short number) static
Creates a string representing this 16-bit value in hexadecimal.
Definition at line 1779 of file String.cpp.
 {
     return toHexString ((int) (unsigned short) number);
 }
String beast::String::toHexString (const void * data, int size, int groupSize = 1) static
Creates a string containing a hex dump of a block of binary data.
Parameters
data the binary data to use as input
size how many bytes of data to use
groupSize how many bytes are grouped together before inserting a space into the output. e.g. group size 0 has no spaces, group size 1 looks like: "be a1 c2 ff", group size 2 looks like "bea1 c2ff".
Definition at line 1784 of file String.cpp.
References beast::hexDigits, and text.
 {
     if (size <= 0)
         return empty;
     int numChars = (size * 2) + 2;
     if (groupSize > 0)
         numChars += size / groupSize;
     String s (PreallocationBytes (sizeof (CharPointerType::CharType) * (size_t) numChars));
     const unsigned char* data = static_cast <const unsigned char*> (d);
     CharPointerType dest (s.text);
     for (int i = 0; i < size; ++i)
     {
         const unsigned char nextByte = *data++;
         dest.write ((beast_wchar) hexDigits [nextByte >> 4]);
         dest.write ((beast_wchar) hexDigits [nextByte & 0xf]);
         if (groupSize > 0 && (i % groupSize) == (groupSize - 1) && i < (size - 1))
             dest.write ((beast_wchar) ' ');
     }
     dest.writeNull();
     return s;
 }
String beast::String::toLowerCase () const
Returns an lower-case version of this string.
Definition at line 1271 of file String.cpp.
References beast::StringCreationHelper::result, beast::StringCreationHelper::source, beast::CharPointer_UTF8::toLowerCase(), and beast::StringCreationHelper::write().
 {
     StringCreationHelper builder (text);
     for (;;)
     {
         const beast_wchar c = builder.source.toLowerCase();
         ++(builder.source);
         builder.write (c);
         if (c == 0)
             break;
     }
     return builder.result;
 }
const char * beast::String::toRawUTF8 () const
Returns a pointer to a UTF-8 version of this string.
Because it returns a reference to the string's internal data, the pointer that is returned must not be stored anywhere, as it can be deleted whenever the string changes.
To find out how many bytes you need to store this string as UTF-8, you can call CharPointer_UTF8::getBytesRequiredFor (myString.getCharPointer())
See Also
getCharPointer, toUTF8, toUTF16, toUTF32
Definition at line 1916 of file String.cpp.
Referenced by beast::FatalError::FatalError(), beast::FileHelpers::isHiddenFile(), beast::operator<<(), ripple::FatalErrorReporter::reportMessage(), beast::FatalError::Reporter::reportMessage(), ripple::RPCDoorImp::RPCDoorImp(), beast::Thread::setCurrentThreadName(), ripple::Config::setRpcIpAndOptionalPort(), and ripple::RPCDoorImp::~RPCDoorImp().
 {
     return toUTF8().getAddress();
 }
std::string beast::String::toStdString () const
Definition at line 1926 of file String.cpp.
Referenced by ripple::STAmount_test::expect(), ripple::BuildInfo::getFullVersionString(), beast::LexicalCast< Out, String >::operator()(), beast::LexicalCast< std::string, In >::operator()(), beast::ParsedURL::ParsedURL(), ripple::parseKeyValueSection(), beast::asio::HTTPClientType::queryFromURL(), ripple::run(), ripple::BuildInfo_test::run(), ripple::SqliteBackend::SqliteBackend(), ripple::NodeStore::NodeStoreTiming_test::testBackend(), ripple::Resource::Manager_test::testImports(), ripple::NodeStore::NodeStoreDatabase_test::testNodeStore(), ripple::Validators::SourceFileImp::to_string(), ripple::Validators::SourceStringsImp::to_string(), beast::URL::to_string(), ripple::Validators::Logic_test::TestSource::to_string(), beast::RelativeTime::to_string(), ripple::BuildInfo::Protocol::toStdString(), and Json::Value::Value().
 {
     return std::string (toRawUTF8());
 }
String beast::String::toUpperCase () const
Returns an upper-case version of this string.
Definition at line 1254 of file String.cpp.
References beast::StringCreationHelper::result, beast::StringCreationHelper::source, beast::CharPointer_UTF8::toUpperCase(), and beast::StringCreationHelper::write().
 {
     StringCreationHelper builder (text);
     for (;;)
     {
         const beast_wchar c = builder.source.toUpperCase();
         ++(builder.source);
         builder.write (c);
         if (c == 0)
             break;
     }
     return builder.result;
 }
CharPointer_UTF16 beast::String::toUTF16 () const
Returns a pointer to a UTF-16 version of this string.
Because it returns a reference to the string's internal data, the pointer that is returned must not be stored anywhere, as it can be deleted whenever the string changes.
To find out how many bytes you need to store this string as UTF-16, you can call CharPointer_UTF16::getBytesRequiredFor (myString.getCharPointer())
See Also
getCharPointer, toUTF8, toUTF32
Definition at line 1913 of file String.cpp.
 { return StringEncodingConverter <CharPointerType, CharPointer_UTF16>::convert (*this); }
CharPointer_UTF32 beast::String::toUTF32 () const
Returns a pointer to a UTF-32 version of this string.
Because it returns a reference to the string's internal data, the pointer that is returned must not be stored anywhere, as it can be deleted whenever the string changes.
See Also
getCharPointer, toUTF8, toUTF16
Definition at line 1914 of file String.cpp.
Referenced by beast::TimeHelpers::formatString().
 { return StringEncodingConverter <CharPointerType, CharPointer_UTF32>::convert (*this); }
CharPointer_UTF8 beast::String::toUTF8 () const
Returns a pointer to a UTF-8 version of this string.
Because it returns a reference to the string's internal data, the pointer that is returned must not be stored anywhere, as it can be deleted whenever the string changes.
To find out how many bytes you need to store this string as UTF-8, you can call CharPointer_UTF8::getBytesRequiredFor (myString.getCharPointer())
See Also
toRawUTF8, getCharPointer, toUTF16, toUTF32
Definition at line 1912 of file String.cpp.
Referenced by beast::beast_runSystemCommand(), beast::File::createDirectoryInternal(), beast::File::deleteFile(), beast::sqdb::detail::standard_use_type::do_use(), beast::File::exists(), beast::TimeHelpers::formatString(), formatted(), beast::SystemStats::getEnvironmentVariable(), beast::File::getVolumeLabel(), beast::File::hasWriteAccess(), beast::isFileExecutable(), beast::FileHelpers::launchExecutable(), beast::File::moveInternal(), beast::RandomAccessFile::nativeOpen(), beast::DirectoryIterator::NativeIterator::Pimpl::next(), beast::DynamicLibrary::open(), beast::sqdb::session::open(), beast::Process::openDocument(), beast::FileInputStream::openHandle(), beast::FileOutputStream::openHandle(), beast::File::setFileReadOnlyInternal(), beast::File::setFileTimesInternal(), beast::Error::what(), and beast::OutputStream::writeText().
 { return StringEncodingConverter <CharPointerType, CharPointer_UTF8 >::convert (*this); }
const wchar_t * beast::String::toWideCharPointer () const
Returns a pointer to a wchar_t version of this string.
Because it returns a reference to the string's internal data, the pointer that is returned must not be stored anywhere, as it can be deleted whenever the string changes.
Bear in mind that the wchar_t type is different on different platforms, so on Windows, this will be equivalent to calling toUTF16(), on unix it'll be the same as calling toUTF32(), etc.
See Also
getCharPointer, toUTF8, toUTF16, toUTF32
Definition at line 1921 of file String.cpp.
Referenced by beast::TimeHelpers::formatString(), formatted(), beast::WindowsFileHelpers::getAtts(), beast::operator<<(), and beast::RegistryKeyWrapper::RegistryKeyWrapper().
 {
     return StringEncodingConverter <CharPointerType, CharPointer_wchar_t>::convert (*this).getAddress();
 }
String beast::String::trim () const
Returns a copy of this string with any whitespace characters removed from the start and end.
Definition at line 1462 of file String.cpp.
References beast::findTrimmedEnd().
Referenced by beast::File::getNonexistentChildFile(), beast::Process::openDocument(), beast::SemanticVersion::parse(), beast::resolveXDGFolder(), and beast::StringArray::trim().
 {
     if (isNotEmpty())
     {
         CharPointerType start (text.findEndOfWhitespace());
         const CharPointerType end (start.findTerminatingNull());
         CharPointerType trimmedEnd (findTrimmedEnd (start, end));
         if (trimmedEnd <= start)
             return empty;
         if (text < start || trimmedEnd < end)
             return String (start, trimmedEnd);
     }
     return *this;
 }
String beast::String::trimCharactersAtEnd (const String & charactersToTrim) const
Returns a copy of this string, having removed a specified set of characters from its end. Characters are removed from the end of the string until it finds one that is not in the specified set, and then it stops.
Parameters
charactersToTrim the set of characters to remove.
See Also
trim, trimEnd, trimCharactersAtStart
Definition at line 1518 of file String.cpp.
References containsChar().
Referenced by beast::File::createDirectory().
 {
     if (isNotEmpty())
     {
         const CharPointerType end (text.findTerminatingNull());
         CharPointerType trimmedEnd (end);
         while (trimmedEnd > text)
         {
             if (! charactersToTrim.containsChar (*--trimmedEnd))
             {
                 ++trimmedEnd;
                 break;
             }
         }
         if (trimmedEnd < end)
             return String (text, trimmedEnd);
     }
     return *this;
 }
String beast::String::trimCharactersAtStart (const String & charactersToTrim) const
Returns a copy of this string, having removed a specified set of characters from its start. Characters are removed from the start of the string until it finds one that is not in the specified set, and then it stops.
Parameters
charactersToTrim the set of characters to remove.
See Also
trim, trimStart, trimCharactersAtEnd
Definition at line 1508 of file String.cpp.
References containsChar().
 {
     CharPointerType t (text);
     while (charactersToTrim.containsChar (*t))
         ++t;
     return t == text ? *this : String (t);
 }
String beast::String::trimEnd () const
Returns a copy of this string with any whitespace characters removed from the end.
Definition at line 1494 of file String.cpp.
References beast::findTrimmedEnd().
Referenced by beast::RelativeTime::getDescription(), beast::File::hasFileExtension(), and beast::Time::toString().
 {
     if (isNotEmpty())
     {
         const CharPointerType end (text.findTerminatingNull());
         CharPointerType trimmedEnd (findTrimmedEnd (text, end));
         if (trimmedEnd < end)
             return String (text, trimmedEnd);
     }
     return *this;
 }
String beast::String::trimStart () const
Returns a copy of this string with any whitespace characters removed from the start.
Definition at line 1481 of file String.cpp.
Referenced by beast::File::hasFileExtension().
 {
     if (isNotEmpty())
     {
         const CharPointerType t (text.findEndOfWhitespace());
         if (t != text)
             return String (t);
     }
     return *this;
 }
String beast::String::unquoted () const
Removes quotation marks from around the string, (if there are any).
Returns a copy of this string with any quotes removed from its ends. Quotes that aren't at the ends of the string are not affected. If there aren't any quotes, the original string is returned.
Note that this is a const method, and won't alter the string itself.
See Also
isQuotedString, quoted
Definition at line 1416 of file String.cpp.
Referenced by beast::SystemStats::getCpuVendor(), and beast::resolveXDGFolder().
 {
     const int len = length();
     if (len == 0)
         return empty;
     const beast_wchar lastChar = text [len - 1];
     const int dropAtStart = (*text == '"' || *text == '\'') ? 1 : 0;
     const int dropAtEnd = (lastChar == '"' || lastChar == '\'') ? 1 : 0;
     return substring (dropAtStart, len - dropAtEnd);
 }
String beast::String::upToFirstOccurrenceOf (const String & substringToEndWith, bool includeSubStringInResult, bool ignoreCase) const
Returns the start of this string, up to the first occurrence of a substring.
This will search for the first occurrence of a given substring, and then return a copy of the string, up to the position of this substring, optionally including or excluding the substring itself in the result.
e.g. for the string "123456", upTo ("34", false) would return "12", and upTo ("34", true) would return "1234".
If the substring isn't found, this will return the whole of the original string.
See Also
upToLastOccurrenceOf, fromFirstOccurrenceOf
Definition at line 1384 of file String.cpp.
References length().
Referenced by beast::SystemStats::getCpuVendor(), and beast::File::parseAbsolutePath().
 {
     const int i = ignoreCase ? indexOfIgnoreCase (sub)
                              : indexOf (sub);
     if (i < 0)
         return *this;
     return substring (0, includeSubString ? i + sub.length() : i);
 }
String beast::String::upToLastOccurrenceOf (const String & substringToFind, bool includeSubStringInResult, bool ignoreCase) const
Returns the start of this string, up to the last occurrence of a substring.
Similar to upToFirstOccurrenceOf(), but this finds the last occurrence rather than the first. If the substring isn't found, this will return the whole of the original string.
See Also
upToFirstOccurrenceOf, fromFirstOccurrenceOf
Definition at line 1396 of file String.cpp.
References length().
 {
     const int i = ignoreCase ? lastIndexOfIgnoreCase (sub)
                              : lastIndexOf (sub);
     if (i < 0)
         return *this;
     return substring (0, includeSubString ? i + sub.length() : i);
 }
Friends And Related Function Documentation
template<class Hasher > void hash_append (Hasher & h, String const & s) friend
Definition at line 1221 of file String.h.
     {
         h.append(s.text.getAddress(), s.text.sizeInBytes());
     }
Member Data Documentation
const String beast::String::empty static
This is an empty string that can be used whenever one is needed.
It's better to use this than String() because it explains what's going on and is more efficient.
Definition at line 186 of file String.h.
Referenced by beast::sqdb::session::close(), ripple::Validators::SourceStringsImp::createParam(), ripple::Validators::Logic_test::TestSource::createParam(), beast::ServiceQueue_timing_test::Consumer< ServiceType >::do_handler(), beast::ServiceQueue_test::ServiceThread::do_handler(), beast::URL::empty(), ripple::Validators::Logic_test::TestSource::fetch(), fromUTF8(), ripple::MultiSocket_test::MultiSocketDetails::getArgName(), beast::SystemStats::getComputerName(), beast::LinuxStatsHelpers::getCpuInfo(), beast::BSDStatsHelpers::getDmesgInfo(), beast::File::getFileExtension(), beast::File::getVersion(), beast::File::getVolumeLabel(), beast::StringArray::joinIntoString(), beast::File::loadFileAsString(), ripple::Config::Error::operator bool(), beast::Error::operator=(), beast::StringArray::operator[](), beast::File::parseAbsolutePath(), ripple::parseDelimitedKeyValueString(), replaceSection(), beast::Error::reset(), beast::ServiceQueue_timing_test::Producer< ServiceType >::run(), ripple::Validators::Utilities::timeToString(), beast::URL::toString(), and ripple::Validators::SourceStringsImp::uniqueID().
CharPointerType beast::String::text private
Definition at line 1231 of file String.h.
Referenced by append(), charToString(), getByteOffsetOfEnd(), getCharPointer(), length(), operator+=(), paddedLeft(), paddedRight(), preallocateBytes(), repeatedString(), replaceSection(), toHexString(), and ~String().
The documentation for this class was generated from the following files:
rippled/src/beast/beast/strings/String.h
rippled/src/beast/beast/strings/impl/String.cpp