rippled: rippled/src/ripple/rocksdb/rocksdb/utilities/merge_operators/string_append/stringappend_test.cc File Reference
stringappend_test.cc File Reference
#include <iostream>
#include <map>
#include "rocksdb/db.h"
#include "rocksdb/merge_operator.h"
#include "utilities/merge_operators.h"
#include "utilities/merge_operators/string_append/stringappend.h"
#include "utilities/merge_operators/string_append/stringappend2.h"
#include "utilities/ttl/db_ttl.h"
#include "util/testharness.h"
#include "util/random.h"
Classes
class rocksdb::StringLists
class rocksdb::StringAppendOperatorTest
Namespaces
rocksdb
Constant Groups
rocksdb
Functions
std::shared_ptr< DB > rocksdb::OpenNormalDb (char delim_char)
std::shared_ptr< DB > rocksdb::OpenTtlDb (char delim_char)
rocksdb::TEST (StringAppendOperatorTest, IteratorTest)
rocksdb::TEST (StringAppendOperatorTest, SimpleTest)
rocksdb::TEST (StringAppendOperatorTest, SimpleDelimiterTest)
rocksdb::TEST (StringAppendOperatorTest, OneValueNoDelimiterTest)
rocksdb::TEST (StringAppendOperatorTest, VariousKeys)
rocksdb::TEST (StringAppendOperatorTest, RandomMixGetAppend)
rocksdb::TEST (StringAppendOperatorTest, BIGRandomMixGetAppend)
rocksdb::TEST (StringAppendOperatorTest, PersistentVariousKeys)
rocksdb::TEST (StringAppendOperatorTest, PersistentFlushAndCompaction)
rocksdb::TEST (StringAppendOperatorTest, SimpleTestNullDelimiter)
int main (int arc, char **argv)
Variables
const std::string rocksdb::kDbName = "/tmp/mergetestdb"
Function Documentation
int main (int arc, char ** argv)
Definition at line 578 of file stringappend_test.cc.
References rocksdb::OpenNormalDb(), rocksdb::OpenTtlDb(), rocksdb::test::RunAllTests(), and rocksdb::StringAppendOperatorTest::SetOpenDbFunction().
{
   // Run with regular database
   {
     fprintf(stderr, "Running tests with regular db and operator.\n");
     StringAppendOperatorTest::SetOpenDbFunction(&OpenNormalDb);
     rocksdb::test::RunAllTests();
   }
   // Run with TTL
   {
     fprintf(stderr, "Running tests with ttl db and generic operator.\n");
     StringAppendOperatorTest::SetOpenDbFunction(&OpenTtlDb);
     rocksdb::test::RunAllTests();
   }
   return 0;
 }