rippled: beast::Thread Class Reference
beast::Thread Class Reference abstract
#include <Thread.h>
Public Types
typedef void * ThreadID
Public Member Functions
Thread (const String &threadName)
virtual ~Thread ()
virtual void run ()=0
void startThread ()
void startThread (int priority)
bool stopThread (int timeOutMilliseconds=-1)
void stopThreadAsync ()
bool isThreadRunning () const
void signalThreadShouldExit ()
bool threadShouldExit () const
bool waitForThreadToExit (int timeOutMilliseconds=-1) const
bool setPriority (int priority)
void setAffinityMask (std::uint32_t affinityMask)
bool wait (int timeOutMilliseconds=-1) const
void notify () const
ThreadID getThreadId () const noexcept
const String & getThreadName () const
Static Public Member Functions
static bool setCurrentThreadPriority (int priority)
static void setCurrentThreadAffinityMask (std::uint32_t affinityMask)
static void sleep (int milliseconds)
static void yield ()
static ThreadID getCurrentThreadId ()
static Thread * getCurrentThread ()
static void setCurrentThreadName (const String &newThreadName)
Private Member Functions
void launchThread ()
void closeThreadHandle ()
void killThread ()
void threadEntryPoint ()
Static Private Member Functions
static bool setThreadPriority (void *, int)
Private Attributes
const String threadName
void *volatile threadHandle
ThreadID threadId
RecursiveMutex startStopLock
WaitableEvent startSuspensionEvent
WaitableEvent defaultEvent
int threadPriority
std::uint32_t affinityMask
bool volatile shouldExit
Friends
void beast_threadEntryPoint (void *)
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
Encapsulates a thread.
Subclasses derive from Thread and implement the run() method, in which they do their business. The thread can then be started with the startThread() method and controlled with various other methods.
This class also contains some thread-related static methods, such as sleep(), yield(), getCurrentThreadId() etc.
See Also
CriticalSection, WaitableEvent, Process, ThreadWithProgressWindow, MessageManagerLock
Definition at line 48 of file Thread.h.
Member Typedef Documentation
typedef void* beast::Thread::ThreadID
A value type used for thread IDs.
See Also
getCurrentThreadId(), getThreadId()
Definition at line 229 of file Thread.h.
Constructor & Destructor Documentation
beast::Thread::Thread (const String & threadName) explicit
Creates a thread.
When first created, the thread is not running. Use the startThread() method to start it.
Definition at line 33 of file Thread.cpp.
     : threadName (threadName_),
       threadHandle (nullptr),
       threadId (0),
       threadPriority (5),
       affinityMask (0),
       shouldExit (false)
 {
 }
beast::Thread::~Thread () virtual
Destructor.
If the thread has not been stopped first, this will generate a fatal error.
Definition at line 43 of file Thread.cpp.
References isThreadRunning(), and stopThread().
 {
     /* If your thread class's destructor has been called without first stopping the thread, that
        means that this partially destructed object is still performing some work - and that's
        probably a Bad Thing!
        To avoid this type of nastiness, always make sure you call stopThread() before or during
        your subclass's destructor.
     */
     assert (! isThreadRunning());
     stopThread ();
 }
Member Function Documentation
void beast::Thread::closeThreadHandle () private
Definition at line 509 of file Thread.cpp.
References threadHandle, and threadId.
Referenced by threadEntryPoint().
 {
     threadId = 0;
     threadHandle = 0;
 }
Thread * beast::Thread::getCurrentThread () static
Finds the thread object that is currently running.
Note that the main UI thread (or other non-Beast threads) don't have a Thread object associated with them, so this will return 0.
Definition at line 149 of file Thread.cpp.
References beast::SharedPtr< T >::get(), and beast::getCurrentThreadHolder().
 {
     return getCurrentThreadHolder()->value.get();
 }
Thread::ThreadID beast::Thread::getCurrentThreadId () static
Returns an id that identifies the caller thread.
To find the ID of a particular thread object, use getThreadId().
Returns
a unique identifier that identifies the calling thread.
See Also
getThreadId
Definition at line 564 of file Thread.cpp.
Referenced by beast::ThreadLocalValue< beast::Thread * >::get(), beast::ThreadLocalValue< beast::Thread * >::releaseCurrentThreadStorage(), setPriority(), stopThread(), threadEntryPoint(), and waitForThreadToExit().
 {
     return (ThreadID) pthread_self();
 }
ThreadID beast::Thread::getThreadId () const inline noexcept
Returns the ID of this thread.
That means the ID of this thread object - not of the thread that's calling the method.
This can change when the thread is started and stopped, and will be invalid if the thread's not actually running.
See Also
getCurrentThreadId
Definition at line 256 of file Thread.h.
References threadId.
Referenced by setPriority(), stopThread(), and waitForThreadToExit().
 { return threadId; }
const String& beast::Thread::getThreadName () const inline
Returns the name of the thread.
This is the name that gets set in the constructor.
Definition at line 262 of file Thread.h.
References threadName.
Referenced by beast::Workers::Worker::run().
 { return threadName; }
bool beast::Thread::isThreadRunning () const
Returns true if the thread is currently active
Definition at line 144 of file Thread.cpp.
References threadHandle.
Referenced by ripple::LoadManagerImp::onStop(), stopThread(), stopThreadAsync(), waitForThreadToExit(), and ~Thread().
 {
     return threadHandle != nullptr;
 }
void beast::Thread::killThread () private
Definition at line 515 of file Thread.cpp.
References bassertfalse, and threadHandle.
Referenced by stopThread().
 {
     if (threadHandle != 0)
     {
        #if BEAST_ANDROID
         bassertfalse; // pthread_cancel not available!
        #else
         pthread_cancel ((pthread_t) threadHandle);
        #endif
     }
 }
void beast::Thread::launchThread () private
Definition at line 496 of file Thread.cpp.
References beast::threadEntryProcBeast(), threadHandle, and threadId.
Referenced by startThread().
 {
     threadHandle = 0;
     pthread_t handle = 0;
     if (pthread_create (&handle, 0, threadEntryProcBeast, this) == 0)
     {
         pthread_detach (handle);
         threadHandle = (void*) handle;
         threadId = (ThreadID) threadHandle;
     }
 }
void beast::Thread::notify () const
Wakes up the thread.
If the thread has called the wait() method, this will wake it up.
See Also
wait
Definition at line 266 of file Thread.cpp.
References defaultEvent, and beast::WaitableEvent::signal().
Referenced by beast::DeadlineTimer::Manager::activate(), beast::DeadlineTimer::Manager::deactivate(), ripple::LedgerCleanerImp::doClean(), ripple::SqliteDatabase::doHook(), ripple::LedgerCleanerImp::onStop(), beast::Workers::setNumberOfThreads(), stopThread(), stopThreadAsync(), and beast::DeadlineTimer::Manager::~Manager().
 {
     defaultEvent.signal();
 }
virtual void beast::Thread::run () pure virtual
Must be implemented to perform the thread's actual code.
Remember that the thread must regularly check the threadShouldExit() method whilst running, and if this returns true it should return from the run() method as soon as possible to avoid being forcibly killed.
See Also
threadShouldExit, startThread
Implemented in beast::asio::HTTPClient_test::IoServiceThread, ripple::Validators::ManagerImp, ripple::PeerFinder::ManagerImp, beast::ServiceQueue_test::ServiceThread, ripple::LedgerCleanerImp, beast::asio::TestPeerType< Logic, Details >, ripple::LoadManagerImp, beast::Workers::Worker, ripple::PeerFinder::CheckerImp, ripple::SiteFiles::ManagerImp, ripple::SNTPClientImp, beast::ServiceQueue_timing_test::Producer< ServiceType >, ripple::Resource::ManagerImp, beast::ServiceQueue_timing_test::Consumer< ServiceType >, beast::DeadlineTimer::Manager, ripple::SqliteDatabase, ripple::HTTP::ServerImpl, ripple::WSDoorImp, and ripple::IoServicePool::ServiceThread.
Referenced by threadEntryPoint().
void beast::Thread::setAffinityMask (std::uint32_t affinityMask)
Sets the affinity mask for the thread.
This will only have an effect next time the thread is started - i.e. if the thread is already running when called, it'll have no effect.
See Also
setCurrentThreadAffinityMask
Definition at line 255 of file Thread.cpp.
References affinityMask.
 {
     affinityMask = newAffinityMask;
 }
void beast::Thread::setCurrentThreadAffinityMask (std::uint32_t affinityMask) static
Changes the affinity mask for the caller thread.
This will change the affinity mask for the thread that calls this static method.
See Also
setAffinityMask
Definition at line 583 of file Thread.cpp.
References bassertfalse.
Referenced by threadEntryPoint().
 {
    #if SUPPORT_AFFINITIES
     cpu_set_t affinity;
     CPU_ZERO (&affinity);
     for (int i = 0; i < 32; ++i)
         if ((affinityMask & (1 << i)) != 0)
             CPU_SET (i, &affinity);
     /*
        N.B. If this line causes a compile error, then you've probably not got the latest
        version of glibc installed.
        If you don't want to update your copy of glibc and don't care about cpu affinities,
        then you can just disable all this stuff by setting the SUPPORT_AFFINITIES macro to 0.
     */
     sched_setaffinity (getpid(), sizeof (cpu_set_t), &affinity);
     sched_yield();
    #else
     /* affinities aren't supported because either the appropriate header files weren't found,
        or the SUPPORT_AFFINITIES macro was turned off
     */
     bassertfalse;
     (void) affinityMask;
    #endif
 }
void beast::Thread::setCurrentThreadName (const String & newThreadName) static
Changes the name of the caller thread. Different OSes may place different length or content limits on this name.
Definition at line 527 of file Thread.cpp.
References BEAST_AUTORELEASEPOOL, and beast::String::toRawUTF8().
Referenced by ripple::JobQueueImp::processTask(), beast::Workers::Worker::run(), ripple::NodeStore::DatabaseImp::threadEntry(), and threadEntryPoint().
 {
    #if BEAST_IOS || (BEAST_MAC && defined (MAC_OS_X_VERSION_10_5) && MAC_OS_X_VERSION_MIN_REQUIRED >= MAC_OS_X_VERSION_10_5)
     BEAST_AUTORELEASEPOOL
     {
         [[NSThread currentThread] setName: beastStringToNS (name)];
     }
    #elif BEAST_LINUX
     #if (__GLIBC__ * 1000 + __GLIBC_MINOR__) >= 2012
      pthread_setname_np (pthread_self(), name.toRawUTF8());
     #else
      prctl (PR_SET_NAME, name.toRawUTF8(), 0, 0, 0);
     #endif
    #endif
 }
bool beast::Thread::setCurrentThreadPriority (int priority) static
Changes the priority of the caller thread.
Similar to setPriority(), but this static method acts on the caller thread. May return false if for some reason the priority can't be changed.
See Also
setPriority
Definition at line 250 of file Thread.cpp.
References setThreadPriority().
Referenced by setPriority().
 {
     return setThreadPriority (0, newPriority);
 }
bool beast::Thread::setPriority (int priority)
Changes the thread's priority. May return false if for some reason the priority can't be changed.
Parameters
priority the new priority, in the range 0 (lowest) to 10 (highest). A priority of 5 is normal.
Definition at line 232 of file Thread.cpp.
References getCurrentThreadId(), getThreadId(), setCurrentThreadPriority(), setThreadPriority(), startStopLock, threadHandle, and threadPriority.
Referenced by startThread().
 {
     // NB: deadlock possible if you try to set the thread prio from the thread itself,
     // so using setCurrentThreadPriority instead in that case.
     if (getCurrentThreadId() == getThreadId())
         return setCurrentThreadPriority (newPriority);
     const RecursiveMutex::ScopedLockType sl (startStopLock);
     if (setThreadPriority (threadHandle, newPriority))
     {
         threadPriority = newPriority;
         return true;
     }
     return false;
 }
bool beast::Thread::setThreadPriority (void * handle, int priority) static private
Definition at line 543 of file Thread.cpp.
References beast::blimit().
Referenced by setCurrentThreadPriority(), setPriority(), and startThread().
 {
     struct sched_param param;
     int policy;
     priority = blimit (0, 10, priority);
     if (handle == nullptr)
         handle = (void*) pthread_self();
     if (pthread_getschedparam ((pthread_t) handle, &policy, &param) != 0)
         return false;
     policy = priority == 0 ? SCHED_OTHER : SCHED_RR;
     const int minPriority = sched_get_priority_min (policy);
     const int maxPriority = sched_get_priority_max (policy);
     param.sched_priority = ((maxPriority - minPriority) * priority) / 10 + minPriority;
     return pthread_setschedparam ((pthread_t) handle, policy, &param) == 0;
 }
void beast::Thread::signalThreadShouldExit ()
Sets a flag to tell the thread it should stop.
Calling this means that the threadShouldExit() method will then return true. The thread should be regularly checking this to see whether it should exit.
If your thread makes use of wait(), you might want to call notify() after calling this method, to interrupt any waits that might be in progress, and allow it to reach a point where it can exit.
See Also
threadShouldExit
waitForThreadToExit
Definition at line 155 of file Thread.cpp.
References shouldExit.
Referenced by ripple::LedgerCleanerImp::onStop(), beast::ServiceQueue_timing_test::Consumer< ServiceType >::stop_one(), beast::ServiceQueue_test::ServiceThread::stop_one(), stopThread(), stopThreadAsync(), and beast::DeadlineTimer::Manager::~Manager().
 {
     shouldExit = true;
 }
void beast::Thread::sleep (int milliseconds) static
Definition at line 465 of file Thread.cpp.
Referenced by beast::TemporaryFile::deleteTemporaryFile(), ripple::LedgerCleanerImp::doLedgerCleaner(), beast::TemporaryFile::overwriteTargetFileWithTemporary(), beast::detail::staticObjectWait(), beast::Time::waitForMillisecondCounter(), and waitForThreadToExit().
 {
     struct timespec time;
     time.tv_sec = millisecs / 1000;
     time.tv_nsec = (millisecs % 1000) * 1000000;
     nanosleep (&time, nullptr);
 }
void beast::Thread::startThread ()
Starts the thread running.
This will start the thread's run() method. (if it's already started, startThread() won't do anything).
See Also
stopThread
Definition at line 115 of file Thread.cpp.
References launchThread(), setThreadPriority(), shouldExit, beast::WaitableEvent::signal(), startStopLock, startSuspensionEvent, threadHandle, and threadPriority.
Referenced by ripple::PeerFinder::CheckerImp::CheckerImp(), beast::ServiceQueue_timing_test::Consumer< ServiceType >::Consumer(), beast::DeadlineTimer::Manager::Manager(), ripple::Resource::ManagerImp::ManagerImp(), ripple::SiteFiles::ManagerImp::onStart(), ripple::LedgerCleanerImp::onStart(), ripple::SNTPClientImp::onStart(), ripple::LoadManagerImp::onStart(), ripple::PeerFinder::ManagerImp::onStart(), ripple::Validators::ManagerImp::onStart(), ripple::HTTP::ServerImpl::ServerImpl(), ripple::IoServicePool::ServiceThread::ServiceThread(), beast::ServiceQueue_test::ServiceThread::ServiceThread(), ripple::SqliteDatabase::SqliteDatabase(), ripple::IoServicePool::ServiceThread::start(), beast::asio::TestPeerType< Logic, Details >::start(), beast::asio::HTTPClient_test::IoServiceThread::start(), startThread(), and beast::Workers::Worker::Worker().
 {
     const RecursiveMutex::ScopedLockType  sl (startStopLock);
     shouldExit = false;
     if (threadHandle == nullptr)
     {
         launchThread();
         setThreadPriority (threadHandle, threadPriority);
         startSuspensionEvent.signal();
     }
 }
void beast::Thread::startThread (int priority)
Starts the thread with a given priority.
Launches the thread with a given priority, where 0 = lowest, 10 = highest. If the thread is already running, its priority will be changed.
See Also
startThread, setPriority
Definition at line 129 of file Thread.cpp.
References setPriority(), startStopLock, startThread(), threadHandle, and threadPriority.
 {
     const RecursiveMutex::ScopedLockType sl (startStopLock);
     if (threadHandle == nullptr)
     {
         threadPriority = priority;
         startThread();
     }
     else
     {
         setPriority (priority);
     }
 }
bool beast::Thread::stopThread (int timeOutMilliseconds = -1)
Attempts to stop the thread running.
This method will cause the threadShouldExit() method to return true and call notify() in case the thread is currently waiting.
Hopefully the thread will then respond to this by exiting cleanly, and the stopThread method will wait for a given time-period for this to happen.
If the thread is stuck and fails to respond after the time-out, it gets forcibly killed, which is a very bad thing to happen, as it could still be holding locks, etc. which are needed by other parts of your program.
Parameters
timeOutMilliseconds The number of milliseconds to wait for the thread to finish before killing it by force. A negative value in here will wait forever.
See Also
signalThreadShouldExit, threadShouldExit, waitForThreadToExit, isThreadRunning
Returns
true if the thread exits, or false if the timeout expires first.
Definition at line 178 of file Thread.cpp.
References bassert, getCurrentThreadId(), getThreadId(), isThreadRunning(), killThread(), notify(), signalThreadShouldExit(), startStopLock, threadHandle, threadId, and waitForThreadToExit().
Referenced by beast::asio::TestPeerType< Logic, Details >::join(), ripple::PeerFinder::CheckerImp::~CheckerImp(), beast::ServiceQueue_timing_test::Consumer< ServiceType >::~Consumer(), ripple::LedgerCleanerImp::~LedgerCleanerImp(), ripple::LoadManagerImp::~LoadManagerImp(), ripple::Resource::ManagerImp::~ManagerImp(), ripple::SiteFiles::ManagerImp::~ManagerImp(), ripple::PeerFinder::ManagerImp::~ManagerImp(), ripple::Validators::ManagerImp::~ManagerImp(), beast::ServiceQueue_timing_test::Producer< ServiceType >::~Producer(), ripple::HTTP::ServerImpl::~ServerImpl(), ripple::IoServicePool::ServiceThread::~ServiceThread(), beast::ServiceQueue_test::ServiceThread::~ServiceThread(), ripple::SNTPClientImp::~SNTPClientImp(), ripple::SqliteDatabase::~SqliteDatabase(), and ~Thread().
 {
     bool cleanExit = true;
     // agh! You can't stop the thread that's calling this method! How on earth
     // would that work??
     bassert (getCurrentThreadId() != getThreadId());
     const RecursiveMutex::ScopedLockType sl (startStopLock);
     if (isThreadRunning())
     {
         signalThreadShouldExit();
         notify();
         if (timeOutMilliseconds != 0)
         {
             cleanExit = waitForThreadToExit (timeOutMilliseconds);
         }
         if (isThreadRunning())
         {
             bassert (! cleanExit);
             // very bad karma if this point is reached, as there are bound to be
             // locks and events left in silly states when a thread is killed by force..
             killThread();
             threadHandle = nullptr;
             threadId = 0;
             cleanExit = false;
         }
         else
         {
             cleanExit = true;
         }
     }
     return cleanExit;
 }
void beast::Thread::stopThreadAsync ()
Stop the thread without blocking. This calls signalThreadShouldExit followed by notify.
Definition at line 220 of file Thread.cpp.
References isThreadRunning(), notify(), signalThreadShouldExit(), and startStopLock.
Referenced by ripple::LoadManagerImp::onStop().
 {
     const RecursiveMutex::ScopedLockType sl (startStopLock);
     if (isThreadRunning())
     {
         signalThreadShouldExit();
         notify();
     }
 }
void beast::Thread::threadEntryPoint () private
Definition at line 86 of file Thread.cpp.
References affinityMask, bassert, closeThreadHandle(), beast::getCurrentThreadHolder(), getCurrentThreadId(), beast::String::isNotEmpty(), run(), setCurrentThreadAffinityMask(), setCurrentThreadName(), startSuspensionEvent, threadId, threadName, and beast::WaitableEvent::wait().
 {
     const CurrentThreadHolder::Ptr currentThreadHolder (getCurrentThreadHolder());
     currentThreadHolder->value = this;
     if (threadName.isNotEmpty())
         setCurrentThreadName (threadName);
     if (startSuspensionEvent.wait (10000))
     {
         bassert (getCurrentThreadId() == threadId);
         if (affinityMask != 0)
             setCurrentThreadAffinityMask (affinityMask);
         run();
     }
     currentThreadHolder->value.releaseCurrentThreadStorage();
     closeThreadHandle();
 }
bool beast::Thread::threadShouldExit () const inline
Checks whether the thread has been told to stop running.
Threads need to check this regularly, and if it returns true, they should return from their run() method at the first possible opportunity.
See Also
signalThreadShouldExit
Definition at line 150 of file Thread.h.
References shouldExit.
Referenced by ripple::LedgerCleanerImp::doLedgerCleaner(), ripple::SqliteDatabase::run(), beast::DeadlineTimer::Manager::run(), beast::ServiceQueue_timing_test::Consumer< ServiceType >::run(), ripple::Resource::ManagerImp::run(), ripple::LoadManagerImp::run(), ripple::LedgerCleanerImp::run(), beast::ServiceQueue_test::ServiceThread::run(), ripple::PeerFinder::ManagerImp::run(), and ripple::Validators::ManagerImp::run().
 { return shouldExit; }
bool beast::Thread::wait (int timeOutMilliseconds = -1) const
Makes the thread wait for a notification.
This puts the thread to sleep until either the timeout period expires, or another thread calls the notify() method to wake it up.
A negative time-out value means that the method will wait indefinitely.
Returns
true if the event has been signalled, false if the timeout expires.
Definition at line 261 of file Thread.cpp.
References defaultEvent, and beast::WaitableEvent::wait().
Referenced by ripple::SqliteDatabase::run(), beast::DeadlineTimer::Manager::run(), ripple::Resource::ManagerImp::run(), and ripple::LedgerCleanerImp::run().
 {
     return defaultEvent.wait (timeOutMilliseconds);
 }
bool beast::Thread::waitForThreadToExit (int timeOutMilliseconds = -1) const
Waits for the thread to stop.
This will waits until isThreadRunning() is false or until a timeout expires.
Parameters
timeOutMilliseconds the time to wait, in milliseconds. If this value is less than zero, it will wait forever.
Returns
true if the thread exits, or false if the timeout expires first.
Definition at line 160 of file Thread.cpp.
References bassert, getCurrentThreadId(), beast::Time::getMillisecondCounter(), getThreadId(), isThreadRunning(), and sleep().
Referenced by beast::asio::HTTPClient_test::IoServiceThread::join(), stopThread(), and beast::DeadlineTimer::Manager::~Manager().
 {
     // Doh! So how exactly do you expect this thread to wait for itself to stop??
     bassert (getThreadId() != getCurrentThreadId() || getCurrentThreadId() == 0);
     const std::uint32_t timeoutEnd = Time::getMillisecondCounter() + (std::uint32_t) timeOutMilliseconds;
     while (isThreadRunning())
     {
         if (timeOutMilliseconds >= 0 && Time::getMillisecondCounter() > timeoutEnd)
             return false;
         sleep (2);
     }
     return true;
 }
void beast::Thread::yield () static
Yields the calling thread's current time-slot.
Definition at line 569 of file Thread.cpp.
Referenced by beast::SpinLock::enter(), beast::detail::staticObjectWait(), and beast::Time::waitForMillisecondCounter().
 {
     sched_yield();
 }
Friends And Related Function Documentation
void beast_threadEntryPoint (void *) friend
Definition at line 109 of file Thread.cpp.
 {
     static_cast <Thread*> (userData)->threadEntryPoint();
 }
Member Data Documentation
std::uint32_t beast::Thread::affinityMask private
Definition at line 278 of file Thread.h.
Referenced by setAffinityMask(), and threadEntryPoint().
WaitableEvent beast::Thread::defaultEvent private
Definition at line 276 of file Thread.h.
Referenced by notify(), and wait().
bool volatile beast::Thread::shouldExit private
Definition at line 279 of file Thread.h.
Referenced by signalThreadShouldExit(), startThread(), and threadShouldExit().
RecursiveMutex beast::Thread::startStopLock private
Definition at line 275 of file Thread.h.
Referenced by setPriority(), startThread(), stopThread(), and stopThreadAsync().
WaitableEvent beast::Thread::startSuspensionEvent private
Definition at line 276 of file Thread.h.
Referenced by startThread(), and threadEntryPoint().
void* volatile beast::Thread::threadHandle private
Definition at line 273 of file Thread.h.
Referenced by closeThreadHandle(), isThreadRunning(), killThread(), launchThread(), setPriority(), startThread(), and stopThread().
ThreadID beast::Thread::threadId private
Definition at line 274 of file Thread.h.
Referenced by closeThreadHandle(), getThreadId(), launchThread(), stopThread(), and threadEntryPoint().
const String beast::Thread::threadName private
Definition at line 272 of file Thread.h.
Referenced by getThreadName(), and threadEntryPoint().
int beast::Thread::threadPriority private
Definition at line 277 of file Thread.h.
Referenced by setPriority(), and startThread().
The documentation for this class was generated from the following files:
rippled/src/beast/beast/threads/Thread.h
rippled/src/beast/beast/threads/impl/Thread.cpp