rippled: ripple::ParameterNode Class Reference
ripple::ParameterNode Class Reference
#include <ParameterTable.h>
Public Member Functions
ParameterNode (Parameter::ref parent, const std::string &name)
bool addChildNode (Parameter::ref node)
bool setValue (const std::string &name, const Json::Value &value, Json::Value &error)
bool addNode (const std::string &name, Parameter::ref node)
virtual Json::Value getValue (int) const
virtual bool setValue (const Json::Value &value, Json::Value &error)
Public Member Functions inherited from ripple::Parameter
Parameter (Parameter::ref parent, const std::string &name)
virtual ~Parameter ()
const std::string & getName () const
Parameter::pointer getShared ()
Private Attributes
std::map< std::string,
Parameter::pointer > mChildren
Additional Inherited Members
Public Types inherited from ripple::Parameter
typedef boost::shared_ptr
< Parameter > pointer
typedef const
boost::shared_ptr< Parameter > & ref
Detailed Description
Definition at line 60 of file ParameterTable.h.
Constructor & Destructor Documentation
ripple::ParameterNode::ParameterNode (Parameter::ref parent, const std::string & name) inline
Definition at line 63 of file ParameterTable.h.
                                                                : Parameter (parent, name)
     {
         ;
     }
Member Function Documentation
bool ripple::ParameterNode::addChildNode (Parameter::ref node)
bool ripple::ParameterNode::addNode (const std::string & name, Parameter::ref node)
Definition at line 67 of file ParameterTable.cpp.
References addNode(), ripple::Parameter::getShared(), mChildren, and name.
Referenced by addNode().
 {
     if (name.empty ()) // this node
         return false;
     size_t dot = name.find ('.');
     if (dot == std::string::npos) // a child of this node
     {
         std::map<std::string, Parameter::pointer>::iterator it = mChildren.find (name);
         if (it != mChildren.end ())
             return false;
         mChildren[name] = node;
         return true;
     }
     std::map<std::string, Parameter::pointer>::iterator it = mChildren.find (name.substr (0, dot));
     ParameterNode* n;
     if (it == mChildren.end ())
     {
         // create a new inner node
         ParameterNode::pointer node = boost::make_shared<ParameterNode> (getShared (), name.substr (0, dot));
         n = dynamic_cast<ParameterNode*> (node.get ());
         assert (n);
         mChildren[name] = node;
     }
     else
     {
         // existing node passed through must be inner
         n = dynamic_cast<ParameterNode*> (it->second.get ());
         if (!n)
             return false;
     }
     return n->addNode (name.substr (dot + 1), node);
 }
Json::Value ripple::ParameterNode::getValue (int i) const virtual
Implements ripple::Parameter.
Definition at line 108 of file ParameterTable.cpp.
References mChildren, and Json::objectValue.
 {
     Json::Value v (Json::objectValue);
     typedef std::map<std::string, Parameter::pointer>::value_type string_ref_pair;
     BOOST_FOREACH (const string_ref_pair & it, mChildren)
     {
         v[it.first] = it.second->getValue (i);
     }
     return v;
 }
bool ripple::ParameterNode::setValue (const std::string & name, const Json::Value & value, Json::Value & error)
Definition at line 22 of file ParameterTable.cpp.
References mChildren, name, Json::objectValue, setValue(), and value.
Referenced by setValue().
 {
     if (name.empty ()) // this node
         return setValue (value, error);
     size_t dot = name.find ('.');
     if (dot == std::string::npos) // a child of this node
     {
         std::map<std::string, Parameter::pointer>::iterator it = mChildren.find (name);
         if (it == mChildren.end ())
         {
             error = Json::objectValue;
             error["error"] = "Name not found";
             error["name"] = name;
             return false;
         }
         return it->second->setValue (value, error);
     }
     std::map<std::string, Parameter::pointer>::iterator it = mChildren.find (name.substr (0, dot));
     if (it == mChildren.end ())
     {
         error = Json::objectValue;
         error["error"] = "Name not found";
         error["name"] = name;
         return false;
     }
     ParameterNode* n = dynamic_cast<ParameterNode*> (it->second.get ());
     if (!n)
     {
         error = Json::objectValue;
         error["error"] = "Node has no children";
         error["name"] = it->second->getName ();
         return false;
     }
     return n->setValue (name.substr (dot + 1), value, error);
 }
bool ripple::ParameterNode::setValue (const Json::Value & value, Json::Value & error) virtual
Implements ripple::Parameter.
Definition at line 119 of file ParameterTable.cpp.
References Json::Value::append(), Json::arrayValue, mChildren, and Json::objectValue.
 {
     error = Json::objectValue;
     error["error"] = "Cannot end on an inner node";
     Json::Value nodes (Json::arrayValue);
     typedef std::map<std::string, Parameter::pointer>::value_type string_ref_pair;
     BOOST_FOREACH (const string_ref_pair & it, mChildren)
     {
         nodes.append (it.first);
     }
     error["legal_nodes"] = nodes;
     return false;
 }
Member Data Documentation
std::map<std::string, Parameter::pointer> ripple::ParameterNode::mChildren private
Definition at line 76 of file ParameterTable.h.
Referenced by addNode(), getValue(), and setValue().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/main/ParameterTable.h
rippled/src/ripple_app/main/ParameterTable.cpp