rippled: ripple::RangeSet Class Reference
ripple::RangeSet Class Reference
#include <RangeSet.h>
Public Member Functions
RangeSet ()
bool hasValue (std::uint32_t) const
std::uint32_t getFirst () const
std::uint32_t getNext (std::uint32_t) const
std::uint32_t getLast () const
std::uint32_t getPrev (std::uint32_t) const
std::uint32_t prevMissing (std::uint32_t) const
void setValue (std::uint32_t)
void setRange (std::uint32_t, std::uint32_t)
void clearValue (std::uint32_t)
std::string toString () const
void checkInternalConsistency () const noexcept
Static Public Attributes
static const std::uint32_t absent = static_cast <std::uint32_t> (-1)
Private Types
typedef std::map
< std::uint32_t, std::uint32_t > Map
typedef Map::const_iterator const_iterator
typedef Map::const_reverse_iterator const_reverse_iterator
typedef Map::value_type value_type
typedef Map::iterator iterator
Private Member Functions
void simplify ()
Static Private Member Functions
static bool contains (value_type const &it, std::uint32_t v)
Private Attributes
Map mRanges
Detailed Description
A sparse set of integers.
Definition at line 27 of file RangeSet.h.
Member Typedef Documentation
typedef Map::const_iterator ripple::RangeSet::const_iterator private
Definition at line 67 of file RangeSet.h.
typedef Map::const_reverse_iterator ripple::RangeSet::const_reverse_iterator private
Definition at line 68 of file RangeSet.h.
typedef Map::iterator ripple::RangeSet::iterator private
Definition at line 70 of file RangeSet.h.
typedef std::map<std::uint32_t, std::uint32_t> ripple::RangeSet::Map private
Definition at line 65 of file RangeSet.h.
typedef Map::value_type ripple::RangeSet::value_type private
Definition at line 69 of file RangeSet.h.
Constructor & Destructor Documentation
ripple::RangeSet::RangeSet () inline
Definition at line 33 of file RangeSet.h.
 { }
Member Function Documentation
void ripple::RangeSet::checkInternalConsistency () const noexcept
Check invariants of the data.
This is for diagnostics, and does nothing in release builds.
Definition at line 235 of file RangeSet.cpp.
References bassert, mRanges, next, and prev.
Referenced by clearValue(), prevMissing(), and simplify().
 {
 #if BEAST_DEBUG
     if (mRanges.size () > 1)
     {
         const_iterator const last = std::prev (mRanges.end ());
         for (const_iterator cur = mRanges.begin (); cur != last; ++cur)
         {
             const_iterator const next = std::next (cur);
             bassert (cur->first <= cur->second);
             bassert (next->first <= next->second);
             bassert (cur->second + 1 < next->first);
         }
     }
     else if (mRanges.size () == 1)
     {
         const_iterator const iter = mRanges.begin ();
         bassert (iter->first <= iter->second);
     }
 #endif
 }
void ripple::RangeSet::clearValue (std::uint32_t v)
Definition at line 151 of file RangeSet.cpp.
References checkInternalConsistency(), contains(), and mRanges.
Referenced by ripple::LedgerMasterImp::clearLedger(), and ripple::RangeSet_test::testMembership().
 {
     for (iterator it = mRanges.begin (); it != mRanges.end (); ++it)
     {
         if (contains (*it, v))
         {
             if (it->first == v)
             {
                 if (it->second == v)
                 {
                     mRanges.erase (it);
                 }
                 else
                 {
                     std::uint32_t oldEnd = it->second;
                     mRanges.erase(it);
                     mRanges[v + 1] = oldEnd;
                 }
             }
             else if (it->second == v)
             {
                 -- (it->second);
             }
             else
             {
                 std::uint32_t oldEnd = it->second;
                 it->second = v - 1;
                 mRanges[v + 1] = oldEnd;
             }
             checkInternalConsistency();
             return;
         }
     }
 }
static bool ripple::RangeSet::contains (value_type const & it, std::uint32_t v) inline static private
Definition at line 72 of file RangeSet.h.
Referenced by clearValue(), getNext(), getPrev(), hasValue(), and prevMissing().
     {
         return (it.first <= v) && (it.second >= v);
     }
std::uint32_t ripple::RangeSet::getFirst () const
Definition at line 50 of file RangeSet.cpp.
References absent, and mRanges.
 {
     const_iterator it = mRanges.begin ();
     if (it == mRanges.end ())
         return absent;
     return it->first;
 }
std::uint32_t ripple::RangeSet::getLast () const
Definition at line 73 of file RangeSet.cpp.
References absent, and mRanges.
 {
     const_reverse_iterator it = mRanges.rbegin ();
     if (it == mRanges.rend ())
         return absent;
     return it->second;
 }
std::uint32_t ripple::RangeSet::getNext (std::uint32_t v) const
Definition at line 60 of file RangeSet.cpp.
References absent, contains(), and mRanges.
 {
     BOOST_FOREACH (const value_type & it, mRanges)
     {
         if (it.first > v)
             return it.first;
         if (contains (it, v + 1))
             return v + 1;
     }
     return absent;
 }
std::uint32_t ripple::RangeSet::getPrev (std::uint32_t v) const
Definition at line 83 of file RangeSet.cpp.
References absent, contains(), and mRanges.
 {
     BOOST_REVERSE_FOREACH (const value_type & it, mRanges)
     {
         if (it.second < v)
             return it.second;
         if (contains (it, v + 1))
             return v - 1;
     }
     return absent;
 }
bool ripple::RangeSet::hasValue (std::uint32_t v) const
Definition at line 40 of file RangeSet.cpp.
References contains(), and mRanges.
Referenced by ripple::LedgerMasterImp::haveLedger(), prevMissing(), setRange(), setValue(), and ripple::RangeSet_test::testMembership().
 {
     BOOST_FOREACH (const value_type & it, mRanges)
     {
         if (contains (it, v))
             return true;
     }
     return false;
 }
std::uint32_t ripple::RangeSet::prevMissing (std::uint32_t v) const
Definition at line 98 of file RangeSet.cpp.
References absent, bassert, checkInternalConsistency(), contains(), hasValue(), and mRanges.
Referenced by ripple::LedgerMasterImp::doAdvance(), ripple::LedgerMasterImp::getFullValidatedRange(), ripple::LedgerMasterImp::getValidatedRange(), ripple::LedgerMasterImp::haveLedgerRange(), and ripple::RangeSet_test::testPrevMissing().
 {
     std::uint32_t result = absent;
     if (v != 0)
     {
         checkInternalConsistency ();
         // Handle the case where the loop reaches the terminating condition
         //
         result = v - 1;
         for (const_reverse_iterator cur = mRanges.rbegin (); cur != mRanges.rend (); ++cur)
         {
             // See if v-1 is in the range
             if (contains (*cur, result))
             {
                 result = cur->first - 1;
                 break;
             }
         }
     }
     bassert (result == absent || !hasValue (result));
     return result;
 }
void ripple::RangeSet::setRange (std::uint32_t minV, std::uint32_t maxV)
Definition at line 136 of file RangeSet.cpp.
References hasValue(), mRanges, and simplify().
Referenced by ripple::RangeSet_test::createPredefinedSet(), ripple::LedgerMasterImp::setLedgerRangePresent(), ripple::RangeSet_test::testMembership(), and ripple::LedgerMasterImp::tryFill().
 {
     while (hasValue (minV))
     {
         ++minV;
         if (minV >= maxV)
             return;
     }
     mRanges[minV] = maxV;
     simplify ();
 }
void ripple::RangeSet::setValue (std::uint32_t v)
Definition at line 126 of file RangeSet.cpp.
References hasValue(), mRanges, and simplify().
Referenced by ripple::LedgerMasterImp::setFullLedger().
 {
     if (!hasValue (v))
     {
         mRanges[v] = v;
         simplify ();
     }
 }
void ripple::RangeSet::simplify () private
Definition at line 208 of file RangeSet.cpp.
References checkInternalConsistency(), ripple::max(), and mRanges.
Referenced by setRange(), and setValue().
 {
     iterator it = mRanges.begin ();
     while (1)
     {
         iterator nit = it;
         if (++nit == mRanges.end ())
         {
             checkInternalConsistency();
             return;
         }
         if (it->second >= (nit->first - 1))
         {
             // ranges overlap
             it->second = std::max(it->second, nit->second);
             mRanges.erase (nit);
         }
         else
         {
             it = nit;
         }
     }
 }
std::string ripple::RangeSet::toString () const
Definition at line 187 of file RangeSet.cpp.
References mRanges.
Referenced by ripple::LedgerMasterImp::getCompleteLedgers().
 {
     std::string ret;
     BOOST_FOREACH (value_type const & it, mRanges)
     {
         if (!ret.empty ())
             ret += ",";
         if (it.first == it.second)
             ret += beast::lexicalCastThrow <std::string> ((it.first));
         else
             ret += beast::lexicalCastThrow <std::string> (it.first) + "-"
                    + beast::lexicalCastThrow <std::string> (it.second);
     }
     if (ret.empty ())
         return "empty";
     return ret;
 }
Member Data Documentation
const std::uint32_t ripple::RangeSet::absent = static_cast <std::uint32_t> (-1) static
Definition at line 30 of file RangeSet.h.
Referenced by ripple::LedgerMasterImp::doAdvance(), getFirst(), ripple::LedgerMasterImp::getFullValidatedRange(), getLast(), getNext(), getPrev(), ripple::LedgerMasterImp::getValidatedRange(), ripple::LedgerMasterImp::haveLedgerRange(), and prevMissing().
Map ripple::RangeSet::mRanges private
Definition at line 78 of file RangeSet.h.
Referenced by checkInternalConsistency(), clearValue(), getFirst(), getLast(), getNext(), getPrev(), hasValue(), prevMissing(), setRange(), setValue(), simplify(), and toString().
The documentation for this class was generated from the following files:
rippled/src/ripple_basics/containers/RangeSet.h
rippled/src/ripple_basics/containers/RangeSet.cpp