rippled: beast::asio::TestPeerType< Logic, Details > Class Template Reference
beast::asio::TestPeerType< Logic, Details > Class Template Reference
#include <TestPeerType.h>
Public Types
typedef Details::arg_type arg_type
typedef Details::native_socket_type native_socket_type
typedef
Details::native_acceptor_type native_acceptor_type
Public Types inherited from beast::asio::TestPeer
enum { defaultTimeout = 10 }
Public Types inherited from beast::Thread
typedef void * ThreadID
Public Member Functions
TestPeerType (arg_type const &arg)
~TestPeerType ()
String name () const
bool is_async () const noexcept
void start (int timeoutSeconds)
error_code join ()
void run ()
void run_sync_server ()
void on_accept (error_code const &ec)
void run_async_server ()
void run_sync_client ()
void run_async_client ()
void do_listen ()
void on_deadline (error_code const &ec)
void finished ()
Public Member Functions inherited from beast::asio::TestPeer
virtual ~TestPeer ()
Public Member Functions inherited from beast::Thread
Thread (const String &threadName)
virtual ~Thread ()
void startThread ()
void startThread (int priority)
bool stopThread (int timeOutMilliseconds=-1)
void stopThreadAsync ()
bool isThreadRunning () const
void signalThreadShouldExit ()
bool threadShouldExit () const
bool waitForThreadToExit (int timeOutMilliseconds=-1) const
bool setPriority (int priority)
void setAffinityMask (std::uint32_t affinityMask)
bool wait (int timeOutMilliseconds=-1) const
void notify () const
ThreadID getThreadId () const noexcept
const String & getThreadName () const
Protected Types
typedef Details::protocol_type protocol_type
typedef Details::socket_type socket_type
typedef Details::acceptor_type acceptor_type
typedef Details::endpoint_type endpoint_type
typedef Details::resolver_type resolver_type
typedef Logic::error_code error_code
typedef TestPeerType< Logic,
Details > This
Private Attributes
WaitableEvent m_listening
WaitableEvent m_join
boost::asio::deadline_timer m_timer
bool m_timer_set
bool m_timed_out
int m_timeoutSeconds
Additional Inherited Members
Static Public Member Functions inherited from beast::asio::TestPeerBasics
static
boost::asio::ssl::stream_base::handshake_type to_handshake_type (PeerRole const &role)
static
boost::system::error_category
const & test_category () noexcept
static boost::system::error_code make_error (errc::errc_t ev) noexcept
static boost::system::error_code make_error (errc::errc_t ev, boost::system::error_code &ec) noexcept
static bool success (boost::system::error_code const &ec, bool eofIsOkay=false) noexcept
static bool failure (boost::system::error_code const &ec, bool eofIsOkay=false) noexcept
static bool expected (bool condition, boost::system::error_code &ec) noexcept
static bool unexpected (bool condition, boost::system::error_code &ec) noexcept
static bool aborted (boost::system::error_code const &ec) noexcept
static void breakpoint (boost::system::error_code const &ec)
static void breakpoint (char const *const message)
Static Public Member Functions inherited from beast::Thread
static bool setCurrentThreadPriority (int priority)
static void setCurrentThreadAffinityMask (std::uint32_t affinityMask)
static void sleep (int milliseconds)
static void yield ()
static ThreadID getCurrentThreadId ()
static Thread * getCurrentThread ()
static void setCurrentThreadName (const String &newThreadName)
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
template<typename Logic, typename Details>
class beast::asio::TestPeerType< Logic, Details >
Definition at line 27 of file TestPeerType.h.
Member Typedef Documentation
template<typename Logic, typename Details> typedef Details::acceptor_type beast::asio::TestPeerType< Logic, Details >::acceptor_type protected
Definition at line 42 of file TestPeerType.h.
template<typename Logic, typename Details> typedef Details::arg_type beast::asio::TestPeerType< Logic, Details >::arg_type
Definition at line 64 of file TestPeerType.h.
template<typename Logic, typename Details> typedef Details::endpoint_type beast::asio::TestPeerType< Logic, Details >::endpoint_type protected
Definition at line 43 of file TestPeerType.h.
template<typename Logic, typename Details> typedef Logic::error_code beast::asio::TestPeerType< Logic, Details >::error_code protected
Definition at line 51 of file TestPeerType.h.
template<typename Logic, typename Details> typedef Details::native_acceptor_type beast::asio::TestPeerType< Logic, Details >::native_acceptor_type
Definition at line 66 of file TestPeerType.h.
template<typename Logic, typename Details> typedef Details::native_socket_type beast::asio::TestPeerType< Logic, Details >::native_socket_type
Definition at line 65 of file TestPeerType.h.
template<typename Logic, typename Details> typedef Details::protocol_type beast::asio::TestPeerType< Logic, Details >::protocol_type protected
Definition at line 40 of file TestPeerType.h.
template<typename Logic, typename Details> typedef Details::resolver_type beast::asio::TestPeerType< Logic, Details >::resolver_type protected
Definition at line 44 of file TestPeerType.h.
template<typename Logic, typename Details> typedef Details::socket_type beast::asio::TestPeerType< Logic, Details >::socket_type protected
Definition at line 41 of file TestPeerType.h.
template<typename Logic, typename Details> typedef TestPeerType<Logic, Details> beast::asio::TestPeerType< Logic, Details >::This protected
Definition at line 60 of file TestPeerType.h.
Constructor & Destructor Documentation
template<typename Logic, typename Details> beast::asio::TestPeerType< Logic, Details >::TestPeerType (arg_type const & arg) inline
Definition at line 68 of file TestPeerType.h.
         : Details (arg)
         , Logic (get_socket ())
         , Thread (name ())
         , m_timer (get_io_service ())
         , m_timer_set (false)
         , m_timed_out (false)
     {
     }
template<typename Logic, typename Details> beast::asio::TestPeerType< Logic, Details >::~TestPeerType () inline
Definition at line 78 of file TestPeerType.h.
     {
     }
Member Function Documentation
template<typename Logic, typename Details> void beast::asio::TestPeerType< Logic, Details >::do_listen () inline
Definition at line 297 of file TestPeerType.h.
References beast::asio::TestPeerBasics::failure(), beast::asio::TestPeerType< Logic, Details >::m_listening, and beast::WaitableEvent::signal().
Referenced by beast::asio::TestPeerType< Logic, Details >::run_async_server(), and beast::asio::TestPeerType< Logic, Details >::run_sync_server().
     {
         if (failure (get_native_acceptor ().open (
             get_endpoint (get_role ()).protocol (), error ())))
                 return;
         // VFALCO TODO Figure out how to not hard code boost::asio::socket_base
         if (failure (get_native_acceptor ().set_option (
                 boost::asio::socket_base::reuse_address (true), error ())))
             return;
         if (failure (get_native_acceptor ().bind (get_endpoint (get_role ()), error ())))
             return;
         // VFALCO TODO Figure out how to not hard code boost::asio::socket_base
         if (failure (get_native_acceptor ().listen (
                 boost::asio::socket_base::max_connections, error ())))
             return;
         m_listening.signal ();
     }
template<typename Logic, typename Details> void beast::asio::TestPeerType< Logic, Details >::finished () inline
Definition at line 344 of file TestPeerType.h.
References beast::asio::TestPeerType< Logic, Details >::m_join, beast::asio::TestPeerType< Logic, Details >::m_listening, beast::asio::TestPeerType< Logic, Details >::m_timer, beast::asio::TestPeerType< Logic, Details >::m_timer_set, beast::asio::PeerRole::server, beast::WaitableEvent::signal(), and beast::asio::TestPeerBasics::unexpected().
Referenced by beast::asio::TestPeerType< Logic, Details >::on_accept(), beast::asio::TestPeerType< Logic, Details >::on_deadline(), beast::asio::TestPeerType< Logic, Details >::run_async_server(), beast::asio::TestPeerType< Logic, Details >::run_sync_client(), and beast::asio::TestPeerType< Logic, Details >::run_sync_server().
     {
         // If the server errors out it will come through
         // here so signal the listening event and unblock
         // the main thread.
         //
         if (get_role () == PeerRole::server)
             m_listening.signal ();
         if (m_timer_set)
         {
             error_code ec;
             std::size_t const amount = m_timer.cancel (ec);
             // The Logic should not have any I/O pending when
             // it calls finished, so amount should be zero.
             //
             unexpected (amount == 0, ec);
         }
         // The logic should close the socket at the end of
         // its operations, unless it encounters an error.
         // Therefore, we will clean everything up and squelch
         // any errors, so that io_service::run() will return.
         //
         {
             error_code ec;
             this->get_socket ().close (ec);
         }
         // The acceptor will not have closed if the client
         // never established the connection, so do it here.
         {
             error_code ec;
             this->get_acceptor ().close (ec);
         }
         // Wake up the thread blocked on join()
         m_join.signal ();
     }
template<typename Logic, typename Details> bool beast::asio::TestPeerType< Logic, Details >::is_async () const inline noexcept
Definition at line 87 of file TestPeerType.h.
References beast::asio::TestPeerBasics::Model::async.
Referenced by beast::asio::TestPeerType< Logic, Details >::join(), beast::asio::TestPeerType< Logic, Details >::run(), and beast::asio::TestPeerType< Logic, Details >::start().
     {
         return get_model () == Model::async;
     }
template<typename Logic, typename Details> error_code beast::asio::TestPeerType< Logic, Details >::join () inline virtual
Wait for the peer to finish.
Returns
Any error code generated during the server operation.
Implements beast::asio::TestPeer.
Definition at line 126 of file TestPeerType.h.
References beast::asio::TestPeerType< Logic, Details >::is_async(), beast::asio::TestPeerType< Logic, Details >::m_join, beast::asio::TestPeerType< Logic, Details >::m_timed_out, beast::asio::TestPeerType< Logic, Details >::m_timeoutSeconds, beast::asio::TestPeerBasics::make_error(), beast::Thread::stopThread(), beast::asio::TestPeerBasics::errc::timeout, and beast::WaitableEvent::wait().
Referenced by beast::asio::PeerTest::run().
     {
         if (is_async ())
         {
             // If the timer expired, then all our i/o should be
             // aborted and the thread will exit. So we will wait
             // for the thread for an infinite amount of time to
             // prevent undefined behavior. If an asynchronous logic
             // fails to end when the deadline timer expires, it
             // means there's a bug in the logic code.
             //
             m_join.wait ();
             // The wait was satisfied but now the thread is still on
             // it's way out of the thread function, so block until
             // we know its done.
             //
             stopThread ();
             // If we timed out then always report the custom error
             if (m_timed_out)
                 return error (make_error (errc::timeout));
         }
         else
         {
             if (m_timeoutSeconds > 0)
             {
                 // Wait for the thread to finish
                 //
                 if (! m_join.wait (m_timeoutSeconds * 1000))
                 {
                     // Uh oh, we timed out! This is bad.
                     // The synchronous model requires that the thread
                     // be forcibly killed, which can result in undefined
                     // behavior. It's best not to perform tests with
                     // synchronous Logic objects that are supposed to time out.
                     // Force the thread to be killed, without waiting.
                     stopThread (0);
                     error () = make_error (errc::timeout);
                 }
                 else
                 {
                     stopThread ();
                 }
             }
             else
             {
                 // They requested an infinite wait.
                 //
                 m_join.wait ();
                 stopThread ();
             }
         }
         return error ();
     }
template<typename Logic, typename Details> String beast::asio::TestPeerType< Logic, Details >::name () const inline virtual
Get the name of this peer.
Implements beast::asio::TestPeer.
Definition at line 82 of file TestPeerType.h.
Referenced by beast::asio::PeerTest::run().
     {
         return get_model ().name () + "_" + get_role ().name ();
     }
template<typename Logic, typename Details> void beast::asio::TestPeerType< Logic, Details >::on_accept (error_code const & ec) inline
Definition at line 250 of file TestPeerType.h.
References beast::asio::TestPeerBasics::failure(), and beast::asio::TestPeerType< Logic, Details >::finished().
Referenced by beast::asio::TestPeerType< Logic, Details >::run_async_server().
     {
         if (failure (ec))
             return finished ();
         // Close the acceptor down so we don't block the io_service forever
         //
         // VFALCO NOTE what difference between cancel and close?
 #if 0
         if (failure (get_acceptor ().close (error ())))
             return finished ();
 #endif
         this->on_connect_async (ec);
     }
template<typename Logic, typename Details> void beast::asio::TestPeerType< Logic, Details >::on_deadline (error_code const & ec) inline
Definition at line 319 of file TestPeerType.h.
References beast::asio::TestPeerBasics::expected(), beast::asio::TestPeerType< Logic, Details >::finished(), beast::asio::TestPeerType< Logic, Details >::m_timed_out, and beast::asio::TestPeerType< Logic, Details >::m_timer_set.
Referenced by beast::asio::TestPeerType< Logic, Details >::start().
     {
         m_timer_set = false;
         if (ec != boost::asio::error::operation_aborted)
         {
             // We expect that ec represents no error, since the
             // timer expired and the operation wasn't aborted.
             //
             // If by some chance there is an error in ec we will
             // report that as an unexpected test condition instead
             // of a timeout.
             //
             if (expected (! ec, error ()))
                 m_timed_out = true;
         }
         else
         {
             // The timer was canceled because the Logic
             // called finished(), so we do nothing here.
         }
         finished ();
     }
template<typename Logic, typename Details> void beast::asio::TestPeerType< Logic, Details >::run () inline virtual
Must be implemented to perform the thread's actual code.
Remember that the thread must regularly check the threadShouldExit() method whilst running, and if this returns true it should return from the run() method as soon as possible to avoid being forcibly killed.
See Also
threadShouldExit, startThread
Implements beast::Thread.
Definition at line 188 of file TestPeerType.h.
References beast::asio::PeerRole::client, beast::asio::TestPeerType< Logic, Details >::is_async(), beast::asio::TestPeerBasics::make_error(), beast::asio::TestPeerType< Logic, Details >::run_async_client(), beast::asio::TestPeerType< Logic, Details >::run_async_server(), beast::asio::TestPeerType< Logic, Details >::run_sync_client(), beast::asio::TestPeerType< Logic, Details >::run_sync_server(), beast::asio::PeerRole::server, beast::asio::TestPeerBasics::Model::sync, and beast::asio::TestPeerBasics::errc::unexpected.
     {
         if (is_async ())
         {
             if (get_role () == PeerRole::server)
             {
                 run_async_server ();
             }
             else if (get_role () == PeerRole::client)
             {
                 run_async_client ();
             }
             else
             {
                 error () = make_error (errc::unexpected);
             }
         }
         else if (get_model () == Model::sync)
         {
             if (get_role () == PeerRole::server)
             {
                 run_sync_server ();
             }
             else if (get_role () == PeerRole::client)
             {
                 run_sync_client ();
             }
             else
             {
                 error () = make_error (errc::unexpected);
             }
         }
         else
         {
             error () = make_error (errc::unexpected);
         }
         get_io_service ().run ();
     }
template<typename Logic, typename Details> void beast::asio::TestPeerType< Logic, Details >::run_async_client () inline
Definition at line 289 of file TestPeerType.h.
Referenced by beast::asio::TestPeerType< Logic, Details >::run().
     {
         get_native_socket ().async_connect (get_endpoint (get_role ()),
             boost::bind (&Logic::on_connect_async, this, boost::asio::placeholders::error));
     }
template<typename Logic, typename Details> void beast::asio::TestPeerType< Logic, Details >::run_async_server () inline
Definition at line 266 of file TestPeerType.h.
References beast::asio::TestPeerType< Logic, Details >::do_listen(), beast::asio::TestPeerBasics::failure(), beast::asio::TestPeerType< Logic, Details >::finished(), and beast::asio::TestPeerType< Logic, Details >::on_accept().
Referenced by beast::asio::TestPeerType< Logic, Details >::run().
     {
         do_listen ();
         if (failure (error ()))
             return finished ();
         get_acceptor ().async_accept (get_socket (), boost::bind (
             &This::on_accept, this, boost::asio::placeholders::error));
     }
template<typename Logic, typename Details> void beast::asio::TestPeerType< Logic, Details >::run_sync_client () inline
Definition at line 279 of file TestPeerType.h.
References beast::asio::TestPeerBasics::failure(), and beast::asio::TestPeerType< Logic, Details >::finished().
Referenced by beast::asio::TestPeerType< Logic, Details >::run().
     {
         if (failure (get_native_socket ().connect (get_endpoint (get_role ()), error ())))
             return finished ();
         this->on_connect ();
         finished ();
     }
template<typename Logic, typename Details> void beast::asio::TestPeerType< Logic, Details >::run_sync_server () inline
Definition at line 230 of file TestPeerType.h.
References beast::asio::TestPeerType< Logic, Details >::do_listen(), beast::asio::TestPeerBasics::failure(), and beast::asio::TestPeerType< Logic, Details >::finished().
Referenced by beast::asio::TestPeerType< Logic, Details >::run().
     {
         do_listen ();
         if (failure (error ()))
             return finished ();
         if (failure (get_acceptor ().accept (get_socket (), error ())))
             return finished ();
         if (failure (get_acceptor ().close (error ())))
             return finished ();
         this->on_connect ();
         finished ();
     }
template<typename Logic, typename Details> void beast::asio::TestPeerType< Logic, Details >::start (int timeoutSeconds) inline virtual
Start the peer. If timeoutSeconds is 0 or less, the wait is infinite.
Parameters
timeoutSeconds How long until the peer should be considered timed out.
Implements beast::asio::TestPeer.
Definition at line 92 of file TestPeerType.h.
References beast::asio::TestPeerType< Logic, Details >::is_async(), beast::asio::TestPeerType< Logic, Details >::m_listening, beast::asio::TestPeerType< Logic, Details >::m_timeoutSeconds, beast::asio::TestPeerType< Logic, Details >::m_timer, beast::asio::TestPeerType< Logic, Details >::m_timer_set, beast::asio::TestPeerType< Logic, Details >::on_deadline(), beast::asio::PeerRole::server, beast::Thread::startThread(), and beast::WaitableEvent::wait().
Referenced by beast::asio::PeerTest::run().
     {
         if (is_async ())
         {
             if (timeoutSeconds > 0)
             {
                 m_timer.expires_from_now (
                     boost::posix_time::seconds (timeoutSeconds));
                 m_timer.async_wait (boost::bind (&This::on_deadline,
                     this, boost::asio::placeholders::error));
                 m_timer_set = true;
             }
             else
             {
                 // Don't set the timer, so infinite wait.
             }
         }
         else
         {
             // Save the value for when join() is called later.
             //
             m_timeoutSeconds = timeoutSeconds;
         }
         startThread ();
         // For server roles block until the thread is litening.
         //
         if (get_role () == PeerRole::server)
             m_listening.wait ();
     }
Member Data Documentation
template<typename Logic, typename Details> WaitableEvent beast::asio::TestPeerType< Logic, Details >::m_join private
Definition at line 387 of file TestPeerType.h.
Referenced by beast::asio::TestPeerType< Logic, Details >::finished(), and beast::asio::TestPeerType< Logic, Details >::join().
template<typename Logic, typename Details> WaitableEvent beast::asio::TestPeerType< Logic, Details >::m_listening private
Definition at line 386 of file TestPeerType.h.
Referenced by beast::asio::TestPeerType< Logic, Details >::do_listen(), beast::asio::TestPeerType< Logic, Details >::finished(), and beast::asio::TestPeerType< Logic, Details >::start().
template<typename Logic, typename Details> bool beast::asio::TestPeerType< Logic, Details >::m_timed_out private
Definition at line 392 of file TestPeerType.h.
Referenced by beast::asio::TestPeerType< Logic, Details >::join(), and beast::asio::TestPeerType< Logic, Details >::on_deadline().
template<typename Logic, typename Details> int beast::asio::TestPeerType< Logic, Details >::m_timeoutSeconds private
Definition at line 395 of file TestPeerType.h.
Referenced by beast::asio::TestPeerType< Logic, Details >::join(), and beast::asio::TestPeerType< Logic, Details >::start().
template<typename Logic, typename Details> boost::asio::deadline_timer beast::asio::TestPeerType< Logic, Details >::m_timer private
Definition at line 390 of file TestPeerType.h.
Referenced by beast::asio::TestPeerType< Logic, Details >::finished(), and beast::asio::TestPeerType< Logic, Details >::start().
template<typename Logic, typename Details> bool beast::asio::TestPeerType< Logic, Details >::m_timer_set private
Definition at line 391 of file TestPeerType.h.
Referenced by beast::asio::TestPeerType< Logic, Details >::finished(), beast::asio::TestPeerType< Logic, Details >::on_deadline(), and beast::asio::TestPeerType< Logic, Details >::start().
The documentation for this class was generated from the following file:
rippled/src/beast/modules/beast_asio/tests/TestPeerType.h