rippled: beast Namespace Reference
beast Namespace Reference
Namespaces
asio
BSDStatsHelpers
Debug
detail
env
FileHelpers
hash_append_tests
hash_metrics
HeapBlockHelper
http
insight
IP
is_call_possible_detail
joyent
LinuxStatsHelpers
multiprecsion
Murmur
platform
Sha256
sqdb
StringArrayHelpers
SystemStatsHelpers
TimeHelpers
unit_test
UnitTestUtilities
util
WindowsFileHelpers
Classes
class io_latency_probe
struct IPAddressConversion
class enable_wait_for_async_test
class shared_handler_test
class Atomic
class ByteOrder
class abstract_clock
class basic_seconds_clock
class manual_clock
class RelativeTime
class abstract_clock_test
class basic_seconds_clock_test
struct is_aged_container
struct buffer_view_default_tag
class buffer_view
class const_container
class cyclic_iterator
An iterator adaptor that cycles through a range.
class aged_ordered_container
struct is_aged_container< detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator > >
struct is_aged_container< detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator > >
class hardened_hash
struct is_contiguously_hashable
struct is_contiguously_hashable< std::pair< T, U > >
struct is_contiguously_hashable< std::tuple< T...> >
struct is_contiguously_hashable< std::array< T, N > >
struct uhash
struct call_hash_value
class aged_associative_container_test_base
class aged_set_test
class aged_map_test
class aged_multiset_test
class aged_multimap_test
class aged_unordered_set_test
class aged_unordered_map_test
class aged_unordered_multiset_test
class aged_unordered_multimap_test
class buffer_view_test
class unsigned_integer
class hardened_hash_test
class hardened_hash_sha256_test
class block_stream
struct is_contiguously_hashable< hash_append_tests::FastKey >
class hash_append_test
class BinaryEncoding
class BaseConversion
class HexEncoding
class BitcoinBase58Conversion
class RippleBase58Conversion
class Base64Conversion
class Base16Conversion
class BinaryEncoding_test
class UnsignedInteger_test
class UnsignedInteger
class UnsignedIntegerCalc
class HeapBlock
class ParsedURL
class ParsedURL_test
class URL
class List
class LockFreeStackIterator
class LockFreeStack
class DynamicBuffer
struct is_contiguously_hashable< IP::AddressV4 >
struct ContainerDeletePolicy
class ScopedPointer
class SharedObject
class SharedPtr
struct BeastStaticAssert
struct BeastStaticAssert< true >
class basic_abstract_ostream
class basic_scoped_ostream
class basic_std_ostream
class debug_ostream
class basic_abstract_ostream_test
class CharacterFunctions
class CharPointer_ASCII
class CharPointer_UTF16
class CharPointer_UTF32
class CharPointer_UTF8
class StringHolder
struct WildCardMatcher
class StringCreationHelper
struct HexConverter
struct StringEncodingConverter
struct StringEncodingConverter< CharPointer_UTF8, CharPointer_UTF8 >
struct StringEncodingConverter< CharPointer_UTF16, CharPointer_UTF16 >
struct StringEncodingConverter< CharPointer_UTF32, CharPointer_UTF32 >
struct StringCopier
class NewLine
class String
class NumberToStringConverters
struct CurrentThreadHolder
class RecursiveMutex
class ScopedWrapperContext
class basic_semaphore
class ServiceQueueBase
class ServiceQueueType
class SharedData
class SharedLockGuard
class SharedMutexAdapter
class SpinLock
class Stoppable
class RootStoppable
class Atomic_test
class ServiceQueue_timing_test
class ServiceQueue_test
class Thread
class ThreadLocalValue
class TryLockGuard
class UnlockGuard
class WaitableEvent
class Uncopyable
class empty_base_optimization
class empty_base_optimization< T, UniqueID, false >
class Error
class Debug_test
class NullJournalSink
class PropertyStream_test
class Journal
struct maybe_const
struct static_and
struct static_and< b0, bN...>
struct static_and<>
struct static_sum
struct static_sum< s0, sN...>
struct static_sum<>
class PropertyStream
class StaticObject
class tagged_integer
struct is_contiguously_hashable< tagged_integer< Int, Tag > >
class bassert_test
class empty_base_optimization_test
class tagged_integer_test
struct adl_tester
class Zero_test
struct Zero
class HTTPField
class HTTPHeaders
class HTTPMessage
class HTTPParser
class HTTPParserImpl
class HTTPRequest
class HTTPRequestParser
class HTTPResponse
class HTTPResponseParser
class HTTPVersion
class Array
class ArrayAllocationBase
struct SortFunctionConverter
class DefaultElementComparator
class LinkedListPointer
class ScopedValueSetter
class FatalError_test
class FatalError
class SemanticVersion_test
class SemanticVersion
class DirectoryIterator
class NonexistentHolder
class File_test
class File
class FileInputStream
class FileOutputStream
class FileSearchPath
class RandomAccessFile_test
class RandomAccessFile
class TemporaryFile
class Logger
class Random_test
class Random
class Range
class MemoryBlock
class SingletonLifetime
class SharedSingleton
class Result
struct sysinfo
class HiResCounterHandler
struct NSObjectRetainer
struct ObjCClass
struct UUIDGetter
class ComSmartPtr
class ComBaseClassHelperBase
class ComBaseClassHelper
struct RegistryKeyWrapper
class FileInputSource
class InputSource
class InputStream
class MemoryOutputStream
class OutputStream
struct CPUInformation
class SystemStats
class LexicalCast_test
struct LexicalCastUtilities
struct BadLexicalCast
struct LexicalCast
struct LexicalCast< String, In >
struct LexicalCast< Out, String >
struct LexicalCast< std::string, In >
struct LexicalCast< Out, std::string >
struct LexicalCast< Out, char const * >
struct LexicalCast< Out, char * >
struct InternalStringArrayComparator_CaseSensitive
struct InternalStringArrayComparator_CaseInsensitive
class StringArray
class StringPairArray
class DeadlineTimer
struct MutexTraits
struct MutexTraits< CriticalSection >
class Workers_test
class Workers
class CriticalSection
class DummyCriticalSection
class DynamicLibrary
class Process
class GenericScopedLock
class GenericScopedUnlock
class GenericScopedTryLock
class AtExitHook
class AtExitMemberHook
class Time
struct leftw
struct divider
struct fpad
class field_t
Typedefs
typedef boost::system::error_code ErrorCode
template<class Key , class T , class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator <std::pair <Key const, T>>>
using aged_map = detail::aged_ordered_container< false, true, Key, T, Duration, Compare, Allocator >
template<class Key , class T , class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator <std::pair <Key const, T>>>
using aged_multimap = detail::aged_ordered_container< true, true, Key, T, Duration, Compare, Allocator >
template<class Key , class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator <Key>>
using aged_multiset = detail::aged_ordered_container< true, false, Key, void, Duration, Compare, Allocator >
template<class Key , class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator <Key>>
using aged_set = detail::aged_ordered_container< false, false, Key, void, Duration, Compare, Allocator >
template<class Key , class T , class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator <std::pair <Key const, T>>>
using aged_unordered_map = detail::aged_unordered_container< false, true, Key, T, Duration, Hash, KeyEqual, Allocator >
template<class Key , class T , class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator <std::pair <Key const, T>>>
using aged_unordered_multimap = detail::aged_unordered_container< true, true, Key, T, Duration, Hash, KeyEqual, Allocator >
template<class Key , class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator <Key>>
using aged_unordered_multiset = detail::aged_unordered_container< true, false, Key, void, Duration, Hash, KeyEqual, Allocator >
template<class Key , class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator <Key>>
using aged_unordered_set = detail::aged_unordered_container< false, false, Key, void, Duration, Hash, KeyEqual, Allocator >
template<class T , class Tag = buffer_view_default_tag>
using const_buffer_view = buffer_view< std::add_const_t< T >, Tag >
typedef unsigned_integer
< 256, std::size_t > sha256_t
typedef basic_abstract_ostream
< char > abstract_ostream
typedef basic_std_ostream< char > std_ostream
typedef wchar_t beast_wchar
typedef CharPointer_UTF32 CharPointer_wchar_t
typedef CharPointer_UTF8 StringCharPointerType
typedef basic_semaphore
< std::mutex,
std::condition_variable > semaphore
typedef ServiceQueueType
< std::allocator< char > > ServiceQueue
template<bool IsConst, class T >
using maybe_const_t = typename maybe_const< IsConst, T >::type
typedef
CriticalSection::ScopedLockType ScopedLock
typedef
CriticalSection::ScopedUnlockType ScopedUnlock
typedef
CriticalSection::ScopedTryLockType ScopedTryLock
template<typename T >
typedef beast::implementation_type who
Enumerations
enum { U_ISOFS_SUPER_MAGIC = 5, U_MSDOS_SUPER_MAGIC = 2, U_NFS_SUPER_MAGIC = 1, U_SMB_SUPER_MAGIC = 8 }
enum { U_ISOFS_SUPER_MAGIC = 5, U_MSDOS_SUPER_MAGIC = 2, U_NFS_SUPER_MAGIC = 1, U_SMB_SUPER_MAGIC = 8 }
Functions
template<typename Type >
Type bmax (const Type a, const Type b)
template<typename Type >
Type bmax (const Type a, const Type b, const Type c)
template<typename Type >
Type bmax (const Type a, const Type b, const Type c, const Type d)
template<typename Type >
Type bmin (const Type a, const Type b)
template<typename Type >
Type bmin (const Type a, const Type b, const Type c)
template<typename Type >
Type bmin (const Type a, const Type b, const Type c, const Type d)
template<typename Type >
const Type findMinimum (const Type *data, int numValues)
template<typename Type >
const Type findMaximum (const Type *values, int numValues)
template<typename Type >
void findMinAndMax (const Type *values, int numValues, Type &lowest, Type &highest)
template<typename Type >
Type blimit (const Type lowerLimit, const Type upperLimit, const Type valueToConstrain) noexcept
template<typename Type >
bool isPositiveAndBelow (Type valueToTest, Type upperLimit) noexcept
template<>
bool isPositiveAndBelow (const int valueToTest, const int upperLimit) noexcept
template<typename Type >
bool isPositiveAndNotGreaterThan (Type valueToTest, Type upperLimit) noexcept
template<>
bool isPositiveAndNotGreaterThan (const int valueToTest, const int upperLimit) noexcept
template<typename Type , int N>
int numElementsInArray (Type(&array)[N])
std::int64_t abs64 (const std::int64_t n) noexcept
template<typename FloatType >
int roundToInt (const FloatType value) noexcept
BEAST_DEFINE_TESTSUITE (enable_wait_for_async, asio, beast)
BEAST_DEFINE_TESTSUITE (shared_handler, asio, beast)
long beast_InterlockedExchange (volatile long *a, long b) noexcept
long beast_InterlockedIncrement (volatile long *a) noexcept
long beast_InterlockedDecrement (volatile long *a) noexcept
long beast_InterlockedExchangeAdd (volatile long *a, long b) noexcept
long beast_InterlockedCompareExchange (volatile long *a, long b, long c) noexcept
__int64 beast_InterlockedCompareExchange64 (volatile __int64 *a, __int64 b, __int64 c) noexcept
void beast_MemoryBarrier () noexcept
template<typename Type >
static Type beast_InterlockedExchangeAdd64 (volatile Type *a, Type b) noexcept
template<typename Type >
static Type beast_InterlockedExchange64 (volatile Type *a, Type b) noexcept
template<typename Type >
static Type beast_InterlockedIncrement64 (volatile Type *a) noexcept
template<typename Type >
static Type beast_InterlockedDecrement64 (volatile Type *a) noexcept
void memoryBarrier () noexcept
template<class IntegralType >
IntegralType swapBytes (IntegralType value) noexcept
template<typename IntegralType >
IntegralType toLittleEndian (IntegralType value) noexcept
template<typename IntegralType >
IntegralType toBigEndian (IntegralType value) noexcept
template<typename IntegralType >
IntegralType toNetworkByteOrder (IntegralType value) noexcept
template<typename IntegralType >
IntegralType fromNetworkByteOrder (IntegralType value) noexcept
template<class TrivialClock , class Duration >
abstract_clock< Duration > & get_abstract_clock ()
template<class CharT , class Traits , class Duration , class Resolution >
std::basic_ostream< CharT,
Traits > & operator<< (std::basic_ostream< CharT, Traits > &os, std::chrono::time_point< abstract_clock< Resolution >, Duration > const &tp)
RelativeTime operator+ (RelativeTime t1, RelativeTime t2) noexcept
RelativeTime operator- (RelativeTime t1, RelativeTime t2) noexcept
bool operator== (RelativeTime t1, RelativeTime t2) noexcept
bool operator!= (RelativeTime t1, RelativeTime t2) noexcept
bool operator> (RelativeTime t1, RelativeTime t2) noexcept
bool operator< (RelativeTime t1, RelativeTime t2) noexcept
bool operator>= (RelativeTime t1, RelativeTime t2) noexcept
bool operator<= (RelativeTime t1, RelativeTime t2) noexcept
static void translateTimeField (String &result, int n, const char *singular, const char *plural)
std::ostream & operator<< (std::ostream &os, RelativeTime const &diff)
BEAST_DEFINE_TESTSUITE (abstract_clock, chrono, beast)
BEAST_DEFINE_TESTSUITE (basic_seconds_clock, chrono, beast)
template<class AgedContainer , class Rep , class Period >
std::enable_if
< is_aged_container
< AgedContainer >::value,
std::size_t >::type expire (AgedContainer &c, std::chrono::duration< Rep, Period > const &age)
template<class T , class Tag >
bool operator== (buffer_view< T, Tag > lhs, buffer_view< T, Tag > rhs)
template<class T , class Tag >
bool operator!= (buffer_view< T, Tag > lhs, buffer_view< T, Tag > rhs)
template<class T , class Tag >
bool operator< (buffer_view< T, Tag > lhs, buffer_view< T, Tag > rhs)
template<class T , class Tag >
bool operator>= (buffer_view< T, Tag > lhs, buffer_view< T, Tag > rhs)
template<class T , class Tag >
bool operator> (buffer_view< T, Tag > lhs, buffer_view< T, Tag > rhs)
template<class T , class Tag >
bool operator<= (buffer_view< T, Tag > lhs, buffer_view< T, Tag > rhs)
template<class T , class Tag >
void swap (buffer_view< T, Tag > &lhs, buffer_view< T, Tag > &rhs) noexcept
template<typename ContainerIterator >
cyclic_iterator
< ContainerIterator > make_cyclic (ContainerIterator const &pos, ContainerIterator const &begin, ContainerIterator const &end)
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare , class Allocator >
void swap (detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator > &lhs, detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator > &rhs) noexcept
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare , class Allocator , class Rep , class Period >
std::size_t expire (detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator > &c, std::chrono::duration< Rep, Period > const &age)
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash , class KeyEqual , class Allocator >
void swap (detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator > &lhs, detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator > &rhs) noexcept
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash , class KeyEqual , class Allocator , class Rep , class Period >
std::size_t expire (detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator > &c, std::chrono::duration< Rep, Period > const &age) noexcept
BEAST_DEFINE_TESTSUITE (aged_set, container, beast)
BEAST_DEFINE_TESTSUITE (aged_map, container, beast)
BEAST_DEFINE_TESTSUITE (aged_multiset, container, beast)
BEAST_DEFINE_TESTSUITE (aged_multimap, container, beast)
BEAST_DEFINE_TESTSUITE (aged_unordered_set, container, beast)
BEAST_DEFINE_TESTSUITE (aged_unordered_map, container, beast)
BEAST_DEFINE_TESTSUITE (aged_unordered_multiset, container, beast)
BEAST_DEFINE_TESTSUITE (aged_unordered_multimap, container, beast)
BEAST_DEFINE_TESTSUITE (buffer_view, container, beast)
BEAST_DEFINE_TESTSUITE (hardened_hash, utility, beast)
BEAST_DEFINE_TESTSUITE_MANUAL (hardened_hash_sha256, utility, beast)
BEAST_DEFINE_TESTSUITE_MANUAL (hash_append, container, beast)
BEAST_DEFINE_TESTSUITE_MANUAL (BinaryEncoding, crypto, beast)
BEAST_DEFINE_TESTSUITE (UnsignedInteger, crypto, beast)
std::ostream & operator<< (std::ostream &os, URL const &url)
std::size_t hash_value (URL const &v)
BEAST_DEFINE_TESTSUITE (ParsedURL, http, beast)
template<class Hasher >
void hash_append (Hasher &h, URL const &url)
template<class Container , bool LhsIsConst, bool RhsIsConst>
bool operator== (LockFreeStackIterator< Container, LhsIsConst > const &lhs, LockFreeStackIterator< Container, RhsIsConst > const &rhs)
template<class Container , bool LhsIsConst, bool RhsIsConst>
bool operator!= (LockFreeStackIterator< Container, LhsIsConst > const &lhs, LockFreeStackIterator< Container, RhsIsConst > const &rhs)
void zeromem (void *memory, size_t numBytes) noexcept
template<typename Type >
void zerostruct (Type &structure) noexcept
template<typename Type >
void deleteAndZero (Type &pointer)
template<typename Type , typename IntegerType >
Type * addBytesToPointer (Type *pointer, IntegerType bytes) noexcept
template<typename Type1 , typename Type2 >
int getAddressDifference (Type1 *pointer1, Type2 *pointer2) noexcept
template<class Type >
Type * createCopyIfNotNull (const Type *pointer)
template<class ObjectType >
bool operator== (const ScopedPointer< ObjectType > &pointer1, ObjectType *const pointer2)
template<class ObjectType >
bool operator!= (const ScopedPointer< ObjectType > &pointer1, ObjectType *const pointer2)
template<typename Type >
void deleteAndZero (ScopedPointer< Type > &)
template<class T >
const T * get_pointer (SharedPtr< T > const &ptr)
template<class T >
T * get_pointer (SharedPtr< T > &ptr)
template<class CharT , class Traits = std::char_traits <CharT>>
basic_std_ostream< CharT, Traits > make_std_ostream (std::basic_ostream< CharT, Traits > &stream)
BEAST_DEFINE_TESTSUITE (basic_abstract_ostream, streams, beast)
static CharPointer_wchar_t castToCharPointer_wchar_t (const void *t) noexcept
bool operator== (const String &s1, const String &s2) noexcept
bool operator== (const String &s1, const char *const s2) noexcept
bool operator== (const String &s1, const wchar_t *const s2) noexcept
bool operator== (const String &s1, const CharPointer_UTF8 s2) noexcept
bool operator== (const String &s1, const CharPointer_UTF16 s2) noexcept
bool operator== (const String &s1, const CharPointer_UTF32 s2) noexcept
bool operator!= (const String &s1, const String &s2) noexcept
bool operator!= (const String &s1, const char *const s2) noexcept
bool operator!= (const String &s1, const wchar_t *const s2) noexcept
bool operator!= (const String &s1, const CharPointer_UTF8 s2) noexcept
bool operator!= (const String &s1, const CharPointer_UTF16 s2) noexcept
bool operator!= (const String &s1, const CharPointer_UTF32 s2) noexcept
bool operator> (const String &s1, const String &s2) noexcept
bool operator< (const String &s1, const String &s2) noexcept
bool operator>= (const String &s1, const String &s2) noexcept
bool operator<= (const String &s1, const String &s2) noexcept
String operator+ (const char *const string1, const String &string2)
String operator+ (const wchar_t *const string1, const String &string2)
String operator+ (const char s1, const String &s2)
String operator+ (const wchar_t s1, const String &s2)
String operator+ (String s1, const String &s2)
String operator+ (String s1, const char *const s2)
String operator+ (String s1, const wchar_t *s2)
String operator+ (String s1, const char s2)
String operator+ (String s1, const wchar_t s2)
String & operator<< (String &s1, const char s2)
String & operator<< (String &s1, const wchar_t s2)
String & operator<< (String &s1, const char *const s2)
String & operator<< (String &s1, const wchar_t *const s2)
String & operator<< (String &s1, const String &s2)
String & operator<< (String &s1, const short number)
String & operator<< (String &s1, const int number)
String & operator<< (String &s1, const long number)
String & operator<< (String &s1, const long long number)
String & operator<< (String &s1, const float number)
String & operator<< (String &s1, const double number)
String & operator<< (String &string1, const NewLine &)
static String::CharPointerType findTrimmedEnd (const String::CharPointerType start, String::CharPointerType end)
String & operator<< (String &string1, std::int64_t number)
template<class traits >
std::basic_ostream< char,
traits > & operator<< (std::basic_ostream< char, traits > &stream, const String &stringToWrite)
template<class traits >
std::basic_ostream< wchar_t,
traits > & operator<< (std::basic_ostream< wchar_t, traits > &stream, const String &stringToWrite)
static SpinLock * castToSpinLockWithoutAliasingWarning (void *s)
static CurrentThreadHolder::Ptr getCurrentThreadHolder ()
void beast_threadEntryPoint (void *userData)
void * threadEntryProcBeast (void *)
BEAST_DEFINE_TESTSUITE (Atomic, thread, beast)
BEAST_DEFINE_TESTSUITE_MANUAL (ServiceQueue_timing, threads, beast)
BEAST_DEFINE_TESTSUITE (ServiceQueue, threads, beast)
BEAST_DEFINE_TESTSUITE_MANUAL (Debug, utility, beast)
BEAST_DEFINE_TESTSUITE (PropertyStream, utility, beast)
BEAST_DEFINE_TESTSUITE_MANUAL (bassert, utility, beast)
BEAST_DEFINE_TESTSUITE (empty_base_optimization, utility, beast)
BEAST_DEFINE_TESTSUITE (tagged_integer, utility, beast)
int signum (adl_tester)
BEAST_DEFINE_TESTSUITE (Zero, types, beast)
template<typename T >
std::string type_name ()
template<typename T >
int signum (T const &t)
template<typename T >
bool operator== (T const &t, Zero)
template<typename T >
bool operator!= (T const &t, Zero)
template<typename T >
bool operator< (T const &t, Zero)
template<typename T >
bool operator> (T const &t, Zero)
template<typename T >
bool operator>= (T const &t, Zero)
template<typename T >
bool operator<= (T const &t, Zero)
template<typename T >
bool operator== (Zero, T const &t)
template<typename T >
bool operator!= (Zero, T const &t)
template<typename T >
bool operator< (Zero, T const &t)
template<typename T >
bool operator> (Zero, T const &t)
template<typename T >
bool operator>= (Zero, T const &t)
template<typename T >
bool operator<= (Zero, T const &t)
template<class ElementType , class ElementComparator >
static void sortArray (ElementComparator &comparator, ElementType *const array, int firstElement, int lastElement, const bool retainOrderOfEquivalentItems)
template<class ElementType , class ElementComparator >
static int findInsertIndexInSortedArray (ElementComparator &comparator, ElementType *const array, const ElementType newElement, int firstElement, int lastElement)
BEAST_DEFINE_TESTSUITE_MANUAL (FatalError, beast_core, beast)
BEAST_DEFINE_TESTSUITE (SemanticVersion, beast_core, beast)
static StringArray parseWildcards (const String &pattern)
static bool fileMatches (const StringArray &wildCards, const String &filename)
static int compareFilenames (const String &name1, const String &name2) noexcept
static int countNumberOfSeparators (String::CharPointerType s)
BEAST_DEFINE_TESTSUITE (File, beast_core, beast)
std::int64_t beast_fileSetPosition (void *handle, std::int64_t pos)
BEAST_DEFINE_TESTSUITE (RandomAccessFile, beast_core, beast)
static File createTempFile (const File &parentDirectory, String name, const String &suffix, const int optionFlags)
template<typename Ty >
Ty calc_bin (Ty value, int size)
template<typename Ty >
Ty calc_bin_start (Ty value, int size)
template<class T >
T pi () noexcept
template<class T >
T twoPi () noexcept
template<class T >
T oneOverTwoPi () noexcept
template<class T , class U >
T degreesToRadians (U degrees)
template<class T , class U >
T radiansToDegrees (U radians)
BEAST_DEFINE_TESTSUITE (Random, beast_core, beast)
static File resolveXDGFolder (const char *const type, const char *const fallbackFolder)
static bool isFileExecutable (const String &filename)
static int getsysctl (char *name, void *ptr, size_t len)
int sysinfo (struct sysinfo *info)
String getLocaleValue (nl_item key)
std::uint32_t beast_millisecondsSinceStartup () noexcept
bool beast_isRunningUnderDebugger ()
static void swapUserAndEffectiveUser ()
static File resolveXDGFolder (const char *const type, const char *const fallbackFolder)
static bool isFileExecutable (const String &filename)
static void swapUserAndEffectiveUser ()
static String getOSXVersion ()
static String getLocaleValue (CFStringRef key)
static HiResCounterHandler & hiResCounterHandler ()
int beast_siginterrupt (int sig, int flag)
File beast_getExecutableFile ()
void beast_runSystemCommand (const String &)
String beast_getOutputFromCommand (const String &)
GUID uuidFromString (const char *const s) noexcept
static void beast_getCpuVendor (char *const v)
static bool isWindowsVersionOrLater (SystemStats::OperatingSystemType target)
static std::int64_t beast_getClockCycleCounter () noexcept
static String getLocaleValue (LCID locale, LCTYPE key, const char *defaultValue)
void * getUser32Function (const char *functionName)
void beast_repeatLastProcessPriority ()
bool beast_isRunningInWine ()
template<>
std::int32_t InputStream::readType< std::int32_t > ()
template<>
std::int64_t InputStream::readType< std::int64_t > ()
template<>
std::uint32_t InputStream::readType< std::uint32_t > ()
template<>
std::uint64_t InputStream::readType< std::uint64_t > ()
template<>
std::int32_t InputStream::readTypeBigEndian< std::int32_t > ()
template<>
std::int64_t InputStream::readTypeBigEndian< std::int64_t > ()
template<>
std::uint32_t InputStream::readTypeBigEndian< std::uint32_t > ()
template<>
std::uint64_t InputStream::readTypeBigEndian< std::uint64_t > ()
OutputStream & operator<< (OutputStream &stream, const MemoryOutputStream &streamToRead)
OutputStream & operator<< (OutputStream &stream, const int number)
OutputStream & operator<< (OutputStream &stream, const std::int64_t number)
OutputStream & operator<< (OutputStream &stream, const double number)
OutputStream & operator<< (OutputStream &stream, const char character)
OutputStream & operator<< (OutputStream &stream, const char *const text)
OutputStream & operator<< (OutputStream &stream, const MemoryBlock &data)
OutputStream & operator<< (OutputStream &stream, const File &fileToRead)
OutputStream & operator<< (OutputStream &stream, InputStream &streamToRead)
OutputStream & operator<< (OutputStream &stream, const NewLine &)
template<>
bool OutputStream::writeType< std::int32_t > (std::int32_t v)
template<>
bool OutputStream::writeType< std::int64_t > (std::int64_t v)
template<>
bool OutputStream::writeType< std::uint32_t > (std::uint32_t v)
template<>
bool OutputStream::writeType< std::uint64_t > (std::uint64_t v)
template<>
bool OutputStream::writeTypeBigEndian< std::int32_t > (std::int32_t v)
template<>
bool OutputStream::writeTypeBigEndian< std::int64_t > (std::int64_t v)
template<>
bool OutputStream::writeTypeBigEndian< std::uint32_t > (std::uint32_t v)
template<>
bool OutputStream::writeTypeBigEndian< std::uint64_t > (std::uint64_t v)
OutputStream & operator<< (OutputStream &stream, const String &text)
static const CPUInformation & getCPUInformation () noexcept
static void handleCrash (int)
BEAST_DEFINE_TESTSUITE (LexicalCast, beast_core, beast)
template<class Out , class In >
bool lexicalCastChecked (Out &out, In in)
template<class Out , class In >
Out lexicalCastThrow (In in)
template<class Out , class In >
Out lexicalCast (In in, Out defaultValue=Out())
BEAST_DEFINE_TESTSUITE (Workers, beast_core, beast)
Time operator+ (Time time, RelativeTime delta)
Time operator- (Time time, RelativeTime delta)
Time operator+ (RelativeTime delta, Time time)
const RelativeTime operator- (Time time1, Time time2)
bool operator== (Time time1, Time time2)
bool operator!= (Time time1, Time time2)
bool operator< (Time time1, Time time2)
bool operator> (Time time1, Time time2)
bool operator<= (Time time1, Time time2)
bool operator>= (Time time1, Time time2)
template<class CharT , class Traits , class Allocator >
std::basic_string< CharT,
Traits, Allocator > heading (std::basic_string< CharT, Traits, Allocator > title, int width=80, CharT fill=CharT('-'))
template<class Hasher , class T >
std::enable_if
< is_contiguously_hashable< T >
::value >::type hash_append (Hasher &h, T const &t) noexcept
template<class Hasher , class T >
std::enable_if
< std::is_floating_point< T >
::value >::type hash_append (Hasher &h, T t) noexcept
template<class Hasher , class T , std::size_t N>
std::enable_if
< !is_contiguously_hashable< T >
::value >::type hash_append (Hasher &h, T(&a)[N]) noexcept
template<class Hasher , class T , std::size_t N>
std::enable_if
< is_contiguously_hashable< T >
::value >::type hash_append (Hasher &h, T(&a)[N]) noexcept
template<class Hasher >
void hash_append (Hasher &h, std::nullptr_t p) noexcept
template<class Hasher , class CharT , class Traits , class Alloc >
void hash_append (Hasher &h, std::basic_string< CharT, Traits, Alloc > const &s) noexcept
template<class Hasher , class T , class U >
std::enable_if
< !is_contiguously_hashable
< std::pair< T, U > >::value >
::type hash_append (Hasher &h, std::pair< T, U > const &p) noexcept
template<class Hasher , class T , class Alloc >
std::enable_if
< !is_contiguously_hashable< T >
::value >::type hash_append (Hasher &h, std::vector< T, Alloc > const &v) noexcept
template<class Hasher , class T , class Alloc >
std::enable_if
< is_contiguously_hashable< T >
::value >::type hash_append (Hasher &h, std::vector< T, Alloc > const &v) noexcept
template<class Hasher , class T , std::size_t N>
std::enable_if
< !is_contiguously_hashable
< std::array< T, N > >::value >
::type hash_append (Hasher &h, std::array< T, N > const &a) noexcept
template<class Hasher >
void hash_append (Hasher &h, std::tuple<> const &t) noexcept
template<class Hasher , class... T>
std::enable_if
< !is_contiguously_hashable
< std::tuple< T...> >::value >
::type hash_append (Hasher &h, std::tuple< T...> const &t) noexcept
template<class Hasher , class T >
void hash_append (Hasher &h, std::shared_ptr< T > const &p) noexcept
template<class Hasher , class T0 , class T1 , class... T>
void hash_append (Hasher &h, T0 const &t0, T1 const &t1, T const &...t) noexcept
bool operator== (URL const &lhs, URL const &rhs)
bool operator!= (URL const &lhs, URL const &rhs)
bool operator< (URL const &lhs, URL const &rhs)
bool operator> (URL const &lhs, URL const &rhs)
bool operator<= (URL const &lhs, URL const &rhs)
bool operator>= (URL const &lhs, URL const &rhs)
template<class T , class U >
bool operator== (SharedPtr< T > const &lhs, U *const rhs) noexcept
template<class T , class U >
bool operator== (SharedPtr< T > const &lhs, SharedPtr< U > const &rhs) noexcept
template<class T , class U >
bool operator== (T const *lhs, SharedPtr< U > const &rhs) noexcept
template<class T , class U >
bool operator!= (SharedPtr< T > const &lhs, U const *rhs) noexcept
template<class T , class U >
bool operator!= (SharedPtr< T > const &lhs, SharedPtr< U > const &rhs) noexcept
template<class T , class U >
bool operator!= (T const *lhs, SharedPtr< U > const &rhs) noexcept
template<typename Function >
double measureFunctionCallTime (Function f)
template<class CharT , class Traits , class Allocator >
field_t< CharT, Traits, Allocator > field (std::basic_string< CharT, Traits, Allocator > const &text, int width=8, int pad=0, bool right=false)
template<class CharT >
field_t< CharT > field (CharT const *text, int width=8, int pad=0, bool right=false)
template<typename T >
field_t< char > field (T const &t, int width=8, int pad=0, bool right=false)
template<class CharT , class Traits , class Allocator >
field_t< CharT, Traits, Allocator > rfield (std::basic_string< CharT, Traits, Allocator > const &text, int width=8, int pad=0)
template<class CharT >
field_t< CharT > rfield (CharT const *text, int width=8, int pad=0)
template<typename T >
field_t< char > rfield (T const &t, int width=8, int pad=0)
Variables
NewLine newLine
static const char hexDigits [] = "0123456789abcdef"
static const beast_wchar emptyChar = 0
static char currentThreadHolderLock [sizeof(SpinLock)]
static char const *const base64EncodingTable = ".ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+"
const char *const * beast_argv = nullptr
int beast_argc = 0
static HiResCounterHandler hiResCounterHandler
static int lastProcessPriority = -1
static void * currentModuleHandle = nullptr
static
SystemStats::CrashHandlerFunction globalCrashHandler = nullptr
Typedef Documentation
typedef basic_abstract_ostream<char> beast::abstract_ostream
An abstract ostream for char.
Definition at line 28 of file abstract_ostream.h.
template<class Key , class T , class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator <std::pair <Key const, T>>> using beast::aged_map = typedef detail::aged_ordered_container < false, true, Key, T, Duration, Compare, Allocator>
Definition at line 39 of file aged_map.h.
template<class Key , class T , class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator <std::pair <Key const, T>>> using beast::aged_multimap = typedef detail::aged_ordered_container < true, true, Key, T, Duration, Compare, Allocator>
Definition at line 39 of file aged_multimap.h.
template<class Key , class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator <Key>> using beast::aged_multiset = typedef detail::aged_ordered_container < true, false, Key, void, Duration, Compare, Allocator>
Definition at line 38 of file aged_multiset.h.
template<class Key , class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator <Key>> using beast::aged_set = typedef detail::aged_ordered_container < false, false, Key, void, Duration, Compare, Allocator>
Definition at line 38 of file aged_set.h.
template<class Key , class T , class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator <std::pair <Key const, T>>> using beast::aged_unordered_map = typedef detail::aged_unordered_container < false, true, Key, T, Duration, Hash, KeyEqual, Allocator>
Definition at line 40 of file aged_unordered_map.h.
template<class Key , class T , class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator <std::pair <Key const, T>>> using beast::aged_unordered_multimap = typedef detail::aged_unordered_container < true, true, Key, T, Duration, Hash, KeyEqual, Allocator>
Definition at line 40 of file aged_unordered_multimap.h.
template<class Key , class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator <Key>> using beast::aged_unordered_multiset = typedef detail::aged_unordered_container < true, false, Key, void, Duration, Hash, KeyEqual, Allocator>
Definition at line 39 of file aged_unordered_multiset.h.
template<class Key , class Duration = std::chrono::seconds, class Hash = std::hash <Key>, class KeyEqual = std::equal_to <Key>, class Allocator = std::allocator <Key>> using beast::aged_unordered_set = typedef detail::aged_unordered_container < false, false, Key, void, Duration, Hash, KeyEqual, Allocator>
Definition at line 39 of file aged_unordered_set.h.
typedef wchar_t beast::beast_wchar
A platform-independent 32-bit unicode character type.
Definition at line 52 of file CharacterFunctions.h.
typedef CharPointer_UTF32 beast::CharPointer_wchar_t
Definition at line 56 of file String.h.
template<class T , class Tag = buffer_view_default_tag> using beast::const_buffer_view = typedef buffer_view < std::add_const_t <T>, Tag>
Definition at line 516 of file buffer_view.h.
typedef boost::system::error_code beast::ErrorCode
Definition at line 31 of file ErrorCode.h.
template<bool IsConst, class T > using beast::maybe_const_t = typedef typename maybe_const <IsConst,T>::type
Alias for omitting typename.
Definition at line 38 of file maybe_const.h.
typedef CriticalSection::ScopedLockType beast::ScopedLock
Automatically locks and unlocks a CriticalSection object.
Use one of these as a local variable to provide RAII-based locking of a CriticalSection.
e.g.
CriticalSection myCriticalSection;
for (;;)
{
    const ScopedLock myScopedLock (myCriticalSection);
    // myCriticalSection is now locked
    ...do some stuff...
    // myCriticalSection gets unlocked here.
}
See Also
CriticalSection, ScopedUnlock
Definition at line 184 of file CriticalSection.h.
typedef CriticalSection::ScopedTryLockType beast::ScopedTryLock
Automatically tries to lock and unlock a CriticalSection object.
Use one of these as a local variable to control access to a CriticalSection.
e.g.
CriticalSection myCriticalSection;
for (;;)
{
    const ScopedTryLock myScopedTryLock (myCriticalSection);
    // Unlike using a ScopedLock, this may fail to actually get the lock, so you
    // should test this with the isLocked() method before doing your thread-unsafe
    // action..
    if (myScopedTryLock.isLocked())
    {
       ...do some stuff...
    }
    else
    {
        ..our attempt at locking failed because another thread had already locked it..
    }
    // myCriticalSection gets unlocked here (if it was locked)
}
See Also
CriticalSection::tryEnter, ScopedLock, ScopedUnlock, ScopedReadLock
Definition at line 257 of file CriticalSection.h.
typedef CriticalSection::ScopedUnlockType beast::ScopedUnlock
Automatically unlocks and re-locks a CriticalSection object.
This is the reverse of a ScopedLock object - instead of locking the critical section for the lifetime of this object, it unlocks it.
Make sure you don't try to unlock critical sections that aren't actually locked!
e.g.
CriticalSection myCriticalSection;
for (;;)
{
    const ScopedLock myScopedLock (myCriticalSection);
    // myCriticalSection is now locked
    ... do some stuff with it locked ..
    while (xyz)
    {
        ... do some stuff with it locked ..
        const ScopedUnlock unlocker (myCriticalSection);
        // myCriticalSection is now unlocked for the remainder of this block,
        // and re-locked at the end.
        ...do some stuff with it unlocked ...
    }
    // myCriticalSection gets unlocked here.
}
See Also
CriticalSection, ScopedLock
Definition at line 224 of file CriticalSection.h.
typedef basic_semaphore<std::mutex, std::condition_variable> beast::semaphore
Definition at line 82 of file semaphore.h.
typedef ServiceQueueType<std::allocator <char> > beast::ServiceQueue
Definition at line 619 of file ServiceQueue.h.
typedef unsigned_integer<256, std::size_t> beast::sha256_t
Definition at line 179 of file hardened_hash.test.cpp.
typedef basic_std_ostream<char> beast::std_ostream
Definition at line 56 of file basic_std_ostream.h.
typedef CharPointer_UTF8 beast::StringCharPointerType
This is the character encoding type used internally to store the string.
By setting the value of BEAST_STRING_UTF_TYPE to 8, 16, or 32, you can change the internal storage format of the String class. UTF-8 uses the least space (if your strings contain few extended characters), but call operator[] involves iterating the string to find the required index. UTF-32 provides instant random access to its characters, but uses 4 bytes per character to store them. UTF-16 uses more space than UTF-8 and is also slow to index, but is the native wchar_t format used in Windows.
It doesn't matter too much which format you pick, because the toUTF8(), toUTF16() and toUTF32() methods let you access the string's content in any of the other formats.
Definition at line 53 of file StringCharPointerType.h.
template<typename T > typedef beast::implementation_type beast::who
A synchronous timer.
Definition at line 29 of file sync_timer.h.
Enumeration Type Documentation
anonymous enum
Enumerator
U_ISOFS_SUPER_MAGIC
U_MSDOS_SUPER_MAGIC
U_NFS_SUPER_MAGIC
U_SMB_SUPER_MAGIC
Definition at line 27 of file bsd_Files.cpp.
 {
     U_ISOFS_SUPER_MAGIC = 5,
     U_MSDOS_SUPER_MAGIC = 2,
     U_NFS_SUPER_MAGIC = 1,
     U_SMB_SUPER_MAGIC = 8
 };
anonymous enum
Enumerator
U_ISOFS_SUPER_MAGIC
U_MSDOS_SUPER_MAGIC
U_NFS_SUPER_MAGIC
U_SMB_SUPER_MAGIC
Definition at line 27 of file linux_Files.cpp.
 {
     U_ISOFS_SUPER_MAGIC = 0x9660,   // linux/iso_fs.h
     U_MSDOS_SUPER_MAGIC = 0x4d44,   // linux/msdos_fs.h
     U_NFS_SUPER_MAGIC = 0x6969,     // linux/nfs_fs.h
     U_SMB_SUPER_MAGIC = 0x517B      // linux/smb_fs.h
 };
Function Documentation
std::int64_t beast::abs64 (const std::int64_t n) inline noexcept
64-bit abs function.
Definition at line 218 of file Arithmetic.h.
Referenced by beast::HiResCounterHandler::getHighResolutionTicks.
 {
     return (n >= 0) ? n : -n;
 }
template<typename Type , typename IntegerType > Type* beast::addBytesToPointer (Type * pointer, IntegerType bytes) noexcept
A handy function which adds a number of bytes to any type of pointer and returns the result. This can be useful to avoid casting pointers to a char* and back when you want to move them by a specific number of bytes,
Definition at line 58 of file Memory.h.
Referenced by beast::String::appendCharPointer(), beast::MemoryBlock::cend(), beast::StringEncodingConverter< CharPointerType_Src, CharPointerType_Dest >::convert(), beast::MemoryBlock::end(), beast::String::operator+=(), and beast::StringCreationHelper::write().
     { return (Type*) (((char*) pointer) + bytes); }
beast::BEAST_DEFINE_TESTSUITE (basic_seconds_clock , chrono , beast)
beast::BEAST_DEFINE_TESTSUITE (ParsedURL , http , beast)
beast::BEAST_DEFINE_TESTSUITE (basic_abstract_ostream , streams , beast)
beast::BEAST_DEFINE_TESTSUITE (UnsignedInteger , crypto , beast)
beast::BEAST_DEFINE_TESTSUITE (abstract_clock , chrono , beast)
beast::BEAST_DEFINE_TESTSUITE (enable_wait_for_async , asio , beast)
beast::BEAST_DEFINE_TESTSUITE (empty_base_optimization , utility , beast)
beast::BEAST_DEFINE_TESTSUITE (LexicalCast , beast_core , beast)
beast::BEAST_DEFINE_TESTSUITE (Atomic , thread , beast)
beast::BEAST_DEFINE_TESTSUITE (Zero , types , beast)
beast::BEAST_DEFINE_TESTSUITE (tagged_integer , utility , beast)
beast::BEAST_DEFINE_TESTSUITE (Random , beast_core , beast)
beast::BEAST_DEFINE_TESTSUITE (shared_handler , asio , beast)
beast::BEAST_DEFINE_TESTSUITE (RandomAccessFile , beast_core , beast)
beast::BEAST_DEFINE_TESTSUITE (ServiceQueue , threads , beast)
beast::BEAST_DEFINE_TESTSUITE (Workers , beast_core , beast)
beast::BEAST_DEFINE_TESTSUITE (hardened_hash , utility , beast)
beast::BEAST_DEFINE_TESTSUITE (buffer_view , container , beast)
beast::BEAST_DEFINE_TESTSUITE (SemanticVersion , beast_core , beast)
beast::BEAST_DEFINE_TESTSUITE (PropertyStream , utility , beast)
beast::BEAST_DEFINE_TESTSUITE (File , beast_core , beast)
beast::BEAST_DEFINE_TESTSUITE (aged_set , container , beast)
beast::BEAST_DEFINE_TESTSUITE (aged_map , container , beast)
beast::BEAST_DEFINE_TESTSUITE (aged_multiset , container , beast)
beast::BEAST_DEFINE_TESTSUITE (aged_multimap , container , beast)
beast::BEAST_DEFINE_TESTSUITE (aged_unordered_set , container , beast)
beast::BEAST_DEFINE_TESTSUITE (aged_unordered_map , container , beast)
beast::BEAST_DEFINE_TESTSUITE (aged_unordered_multiset , container , beast)
beast::BEAST_DEFINE_TESTSUITE (aged_unordered_multimap , container , beast)
beast::BEAST_DEFINE_TESTSUITE_MANUAL (bassert , utility , beast)
beast::BEAST_DEFINE_TESTSUITE_MANUAL (FatalError , beast_core , beast)
beast::BEAST_DEFINE_TESTSUITE_MANUAL (ServiceQueue_timing , threads , beast)
beast::BEAST_DEFINE_TESTSUITE_MANUAL (hardened_hash_sha256 , utility , beast)
beast::BEAST_DEFINE_TESTSUITE_MANUAL (Debug , utility , beast)
beast::BEAST_DEFINE_TESTSUITE_MANUAL (BinaryEncoding , crypto , beast)
beast::BEAST_DEFINE_TESTSUITE_MANUAL (hash_append , container , beast)
std::int64_t beast::beast_fileSetPosition (void * handle, std::int64_t pos)
Definition at line 281 of file posix_SharedCode.h.
Referenced by beast::FileInputStream::read(), and beast::FileOutputStream::setPosition().
 {
     if (handle != 0 && lseek (getFD (handle), pos, SEEK_SET) == pos)
         return pos;
     return -1;
 }
static std::int64_t beast::beast_getClockCycleCounter () static noexcept
Definition at line 284 of file win32_SystemStats.cpp.
 {
    #if BEAST_USE_INTRINSICS
     // MS intrinsics version...
     return (std::int64_t) __rdtsc();
    #elif BEAST_GCC
     // GNU inline asm version...
     unsigned int hi = 0, lo = 0;
     __asm__ __volatile__ (
         "xor %%eax, %%eax               \n\
          xor %%edx, %%edx               \n\
          rdtsc                          \n\
          movl %%eax, %[lo]              \n\
          movl %%edx, %[hi]"
          :
          : [hi] "m" (hi),
            [lo] "m" (lo)
          : "cc", "eax", "ebx", "ecx", "edx", "memory");
     return (std::int64_t) ((((std::uint64_t) hi) << 32) | lo);
    #else
     // MSVC inline asm version...
     unsigned int hi = 0, lo = 0;
     __asm
     {
         xor eax, eax
         xor edx, edx
         rdtsc
         mov lo, eax
         mov hi, edx
     }
     return (std::int64_t) ((((std::uint64_t) hi) << 32) | lo);
    #endif
 }
static void beast::beast_getCpuVendor (char *const v) static
Definition at line 64 of file win32_SystemStats.cpp.
 {
     int vendor[4] = { 0 };
    #if ! BEAST_MINGW
     __try
    #endif
     {
        #if BEAST_GCC
         unsigned int dummy = 0;
         __asm__ ("cpuid" : "=a" (dummy), "=b" (vendor[0]), "=c" (vendor[2]),"=d" (vendor[1]) : "a" (0));
        #else
         __asm
         {
             mov eax, 0
             cpuid
             mov [vendor], ebx
             mov [vendor + 4], edx
             mov [vendor + 8], ecx
         }
        #endif
     }
    #if ! BEAST_MINGW
     __except (EXCEPTION_EXECUTE_HANDLER)
     {
     }
    #endif
     memcpy (v, vendor, 16);
 }
File beast::beast_getExecutableFile ()
Definition at line 607 of file posix_SharedCode.h.
References filename, beast::File::getChildFile(), and beast::File::getCurrentWorkingDirectory().
Referenced by beast::File::getSpecialLocation().
 {
    #if BEAST_PROBEASTR_LIVE_BUILD
     return File (beast_getCurrentExecutablePath());
    #elif BEAST_ANDROID
     return File (android.appFile);
    #else
     struct DLAddrReader
     {
         static String getFilename()
         {
             Dl_info exeInfo;
             dladdr ((void*) beast_getExecutableFile, &exeInfo);
             return CharPointer_UTF8 (exeInfo.dli_fname);
         }
     };
     static String filename (DLAddrReader::getFilename());
     return File::getCurrentWorkingDirectory().getChildFile (filename);
    #endif
 }
String beast::beast_getOutputFromCommand (const String & command)
Definition at line 713 of file posix_SharedCode.h.
References beast_runSystemCommand(), beast::File::deleteFile(), beast::File::getFullPathName(), beast::File::getSpecialLocation(), beast::Random::getSystemRandom(), beast::File::loadFileAsString(), beast::File::tempDirectory, and beast::String::toHexString().
 {
     // slight bodge here, as we just pipe the output into a temp file and read it...
     const File tempFile (File::getSpecialLocation (File::tempDirectory)
                            .getNonexistentChildFile (String::toHexString (Random::getSystemRandom().nextInt()), ".tmp", false));
     beast_runSystemCommand (command + " > " + tempFile.getFullPathName());
     String result (tempFile.loadFileAsString());
     tempFile.deleteFile();
     return result;
 }
long beast::beast_InterlockedCompareExchange (volatile long * a, long b, long c) noexcept
Definition at line 42 of file win32_Threads.cpp.
Referenced by beast::Atomic< Type >::compareAndSetValue().
 { return InterlockedCompareExchange (a, b, c); }
__int64 beast::beast_InterlockedCompareExchange64 (volatile __int64 * a, __int64 b, __int64 c) noexcept
Definition at line 44 of file win32_Threads.cpp.
References bassertfalse, and value.
Referenced by beast::Atomic< Type >::compareAndSetValue().
 {
     bassertfalse; // This operation isn't available in old MS compiler versions!
     __int64 oldValue = *value;
     if (oldValue == valueToCompare)
         *value = newValue;
     return oldValue;
 }
long beast::beast_InterlockedDecrement (volatile long * a) noexcept
Definition at line 40 of file win32_Threads.cpp.
Referenced by beast::Atomic< Type >::operator--().
 { return InterlockedDecrement (a); }
template<typename Type > static Type beast::beast_InterlockedDecrement64 (volatile Type * a) static noexcept
Definition at line 263 of file Atomic.h.
References bassertfalse.
Referenced by beast::Atomic< Type >::operator--().
 { bassertfalse; return --*a; }
long beast::beast_InterlockedExchange (volatile long * a, long b) noexcept
Definition at line 38 of file win32_Threads.cpp.
Referenced by beast::Atomic< Type >::exchange().
 { return InterlockedExchange (a, b); }
template<typename Type > static Type beast::beast_InterlockedExchange64 (volatile Type * a, Type b) static noexcept
Definition at line 261 of file Atomic.h.
References bassertfalse.
Referenced by beast::Atomic< Type >::exchange().
 { bassertfalse; Type old = *a; *a = b; return old; }
long beast::beast_InterlockedExchangeAdd (volatile long * a, long b) noexcept
Definition at line 41 of file win32_Threads.cpp.
Referenced by beast::Atomic< Type >::get(), and beast::Atomic< Type >::operator+=().
 { return InterlockedExchangeAdd (a, b); }
template<typename Type > static Type beast::beast_InterlockedExchangeAdd64 (volatile Type * a, Type b) static noexcept
Definition at line 260 of file Atomic.h.
References bassertfalse.
Referenced by beast::Atomic< Type >::get(), and beast::Atomic< Type >::operator+=().
 { bassertfalse; Type old = *a; *a += b; return old; }
long beast::beast_InterlockedIncrement (volatile long * a) noexcept
Definition at line 39 of file win32_Threads.cpp.
Referenced by beast_MemoryBarrier(), and beast::Atomic< Type >::operator++().
 { return InterlockedIncrement (a); }
template<typename Type > static Type beast::beast_InterlockedIncrement64 (volatile Type * a) static noexcept
Definition at line 262 of file Atomic.h.
References bassertfalse.
Referenced by beast::Atomic< Type >::operator++().
 { bassertfalse; return ++*a; }
bool beast::beast_isRunningInWine ()
Definition at line 156 of file win32_Threads.cpp.
 {
     HMODULE ntdll = GetModuleHandleA ("ntdll");
     return ntdll != 0 && GetProcAddress (ntdll, "wine_get_version") != nullptr;
 }
bool beast::beast_isRunningUnderDebugger ()
Definition at line 53 of file bsd_Threads.cpp.
Referenced by beast_reportFatalError(), beast::Debug::breakPoint(), beast::Process::isRunningUnderDebugger(), and ripple::LogSink::write_console().
 {
     // XXX not implemented for FreeBSD!
     // bassertfalse; // commented out since it calls isRunningUnderDebugger recursively
     return false;
 }
void beast::beast_MemoryBarrier () inline noexcept
Definition at line 247 of file Atomic.h.
References beast_InterlockedIncrement().
Referenced by memoryBarrier().
 { long x = 0; beast_InterlockedIncrement (&x); }
std::uint32_t beast::beast_millisecondsSinceStartup () noexcept
Definition at line 321 of file bsd_SystemStats.cpp.
Referenced by beast::HiResCounterHandler::getHighResolutionTicks, and beast::Time::getMillisecondCounter().
 {
     timespec t;
     clock_gettime (CLOCK_MONOTONIC, &t);
     return t.tv_sec * 1000 + t.tv_nsec / 1000000;
 }
void beast::beast_repeatLastProcessPriority ()
Definition at line 81 of file win32_Threads.cpp.
References bassertfalse, beast::Process::HighPriority, lastProcessPriority, beast::Process::LowPriority, beast::Process::NormalPriority, and beast::Process::RealtimePriority.
 {
     if (lastProcessPriority >= 0) // (avoid changing this if it's not been explicitly set by the app..)
     {
         DWORD p;
         switch (lastProcessPriority)
         {
             case Process::LowPriority:          p = IDLE_PRIORITY_CLASS; break;
             case Process::NormalPriority:       p = NORMAL_PRIORITY_CLASS; break;
             case Process::HighPriority:         p = HIGH_PRIORITY_CLASS; break;
             case Process::RealtimePriority:     p = REALTIME_PRIORITY_CLASS; break;
             default:                            bassertfalse; return; // bad priority value
         }
         SetPriorityClass (GetCurrentProcess(), p);
     }
 }
void beast::beast_runSystemCommand (const String & command)
Definition at line 706 of file posix_SharedCode.h.
References beast::String::toUTF8().
Referenced by beast_getOutputFromCommand().
 {
     int result = system (command.toUTF8());
     (void) result;
 }
int beast::beast_siginterrupt (int sig, int flag)
Definition at line 86 of file posix_SharedCode.h.
Referenced by beast::SystemStats::setApplicationCrashHandler().
 {
     struct ::sigaction act;
     (void) ::sigaction (sig, nullptr, &act);
     if (flag != 0)
         act.sa_flags &= ~SA_RESTART;
     else
         act.sa_flags |= SA_RESTART;
     return ::sigaction (sig, &act, nullptr);
 }
void beast::beast_threadEntryPoint (void * userData)
Definition at line 109 of file Thread.cpp.
Referenced by threadEntryProcBeast().
 {
     static_cast <Thread*> (userData)->threadEntryPoint();
 }
template<typename Type > Type beast::blimit (const Type lowerLimit, const Type upperLimit, const Type valueToConstrain) inline noexcept
Constrains a value to keep it within a given range.
This will check that the specified value lies between the lower and upper bounds specified, and if not, will return the nearest value that would be in-range. Effectively, it's like calling bmax (lowerLimit, bmin (upperLimit, value)).
Note that it expects that lowerLimit <= upperLimit. If this isn't true, the results will be unpredictable.
Parameters
lowerLimit the minimum value to return
upperLimit the maximum value to return
valueToConstrain the value to try to return
Returns
the closest value to valueToConstrain which lies between lowerLimit and upperLimit (inclusive)
See Also
blimit0To, bmin, bmax
Definition at line 150 of file Arithmetic.h.
References bassert.
Referenced by beast::Range< ValueType >::clipValue(), beast::Range< ValueType >::constrainRange(), beast::Array< beast::String >::removeRange(), beast::FileInputStream::setPosition(), beast::MemoryOutputStream::setPosition(), and beast::Thread::setThreadPriority().
 {
     bassert (lowerLimit <= upperLimit); // if these are in the wrong order, results are unpredictable..
     return (valueToConstrain < lowerLimit) ? lowerLimit
                                            : ((upperLimit < valueToConstrain) ? upperLimit
                                                                               : valueToConstrain);
 }
template<typename Type > Type beast::bmax (const Type a, const Type b) inline
Returns the larger of two values.
Definition at line 41 of file Arithmetic.h.
Referenced by bmax(), beast::SemanticVersion::compare(), beast::File::createLegalFileName(), ripple::NodeStore::DecodedBlob::DecodedBlob(), beast::String::dropLastCharacters(), beast::Range< ValueType >::getIntersectionWith(), beast::String::getLastCharacters(), beast::Range< ValueType >::getUnionWith(), beast::StringHolder::makeUniqueWithByteSize(), beast::Array< beast::String >::minimiseStorageAfterRemoval(), beast::MemoryOutputStream::prepareToWrite(), beast::Range< ValueType >::setLength(), beast::Range< ValueType >::withStart(), and beast::StringCreationHelper::write().
     { return (a < b) ? b : a; }
template<typename Type > Type beast::bmax (const Type a, const Type b, const Type c) inline
Returns the larger of three values.
Definition at line 46 of file Arithmetic.h.
     { return (a < b) ? ((b < c) ? c : b) : ((a < c) ? c : a); }
template<typename Type > Type beast::bmax (const Type a, const Type b, const Type c, const Type d) inline
Returns the larger of four values.
Definition at line 51 of file Arithmetic.h.
References bmax().
     { return bmax (a, bmax (b, c, d)); }
template<typename Type > Type beast::bmin (const Type a, const Type b) inline
Returns the smaller of two values.
Definition at line 56 of file Arithmetic.h.
Referenced by bmin(), beast::StringEncodingConverter< CharPointerType_Src, CharPointerType_Dest >::convert(), beast::MemoryBlock::getBitRange(), beast::Range< ValueType >::getIntersectionWith(), beast::Range< ValueType >::getUnionWith(), beast::MemoryBlock::insert(), beast::StringArray::joinIntoString(), beast::MemoryOutputStream::prepareToWrite(), beast::MemoryBlock::setBitRange(), beast::InputStream::skipNextBytes(), beast::Time::waitForMillisecondCounter(), beast::Range< ValueType >::withEnd(), and beast::OutputStream::writeFromInputStream().
     { return (b < a) ? b : a; }
template<typename Type > Type beast::bmin (const Type a, const Type b, const Type c) inline
Returns the smaller of three values.
Definition at line 61 of file Arithmetic.h.
     { return (b < a) ? ((c < b) ? c : b) : ((c < a) ? c : a); }
template<typename Type > Type beast::bmin (const Type a, const Type b, const Type c, const Type d) inline
Returns the smaller of four values.
Definition at line 66 of file Arithmetic.h.
References bmin().
     { return bmin (a, bmin (b, c, d)); }
template<typename Ty > Ty beast::calc_bin (Ty value, int size) inline
Definition at line 34 of file Math.h.
Referenced by calc_bin_start().
 {
     if (value >= 0)
         return value / size;
     else
         return (value - size + 1) / size;
 }
template<typename Ty > Ty beast::calc_bin_start (Ty value, int size) inline
Definition at line 47 of file Math.h.
References calc_bin().
 {
     return calc_bin (value, size) * size;
 }
static CharPointer_wchar_t beast::castToCharPointer_wchar_t (const void * t) inline static noexcept
Definition at line 52 of file String.cpp.
Referenced by beast::String::compare(), beast::String::equalsIgnoreCase(), and beast::String::operator+=().
 {
     return CharPointer_wchar_t (static_cast <const CharPointer_wchar_t::CharType*> (t));
 }
static SpinLock* beast::castToSpinLockWithoutAliasingWarning (void * s) static
Definition at line 70 of file Thread.cpp.
Referenced by getCurrentThreadHolder().
 {
     return static_cast<SpinLock*> (s);
 }
static int beast::compareFilenames (const String & name1, const String & name2) static noexcept
Definition at line 207 of file File.cpp.
Referenced by beast::File::isAChildOf(), beast::File::operator!=(), beast::File::operator<(), beast::File::operator==(), and beast::File::operator>().
 {
    #if NAMES_ARE_CASE_SENSITIVE
     return name1.compare (name2);
    #else
     return name1.compareIgnoreCase (name2);
    #endif
 }
static int beast::countNumberOfSeparators (String::CharPointerType s) static
Definition at line 815 of file File.cpp.
References beast::CharPointer_UTF8::getAndAdvance(), and beast::File::separator.
Referenced by beast::File::getRelativePathFrom().
 {
     int num = 0;
     for (;;)
     {
         const beast_wchar c = s.getAndAdvance();
         if (c == 0)
             break;
         if (c == File::separator)
             ++num;
     }
     return num;
 }
template<class Type > Type* beast::createCopyIfNotNull (const Type * pointer)
If a pointer is non-null, this returns a new copy of the object that it points to, or safely returns nullptr if the pointer is null.
Definition at line 72 of file Memory.h.
Referenced by beast::ScopedPointer< beast::DirectoryIterator::NativeIterator::Pimpl >::createCopy().
     { return pointer != nullptr ? new Type (*pointer) : nullptr; }
static File beast::createTempFile (const File & parentDirectory, String name, const String & suffix, const int optionFlags) static
Definition at line 27 of file TemporaryFile.cpp.
References beast::File::getNonexistentChildFile(), name, beast::TemporaryFile::putNumbersInBrackets, and beast::TemporaryFile::useHiddenFile.
 {
     if ((optionFlags & TemporaryFile::useHiddenFile) != 0)
         name = "." + name;
     return parentDirectory.getNonexistentChildFile (name, suffix, (optionFlags & TemporaryFile::putNumbersInBrackets) != 0);
 }
template<class T , class U > T beast::degreesToRadians (U degrees) inline
Definition at line 71 of file Math.h.
References T.
 {
     return T (degrees * 0.0174532925199433);
 }
template<typename Type > void beast::deleteAndZero (Type & pointer)
Delete an object pointer, and sets the pointer to null.
Remember that it's not good c++ practice to use delete directly - always try to use a ScopedPointer or other automatic lifetime-management system rather than resorting to deleting raw pointers!
Definition at line 50 of file Memory.h.
     { delete pointer; pointer = nullptr; }
template<typename Type > void beast::deleteAndZero (ScopedPointer< Type > &)
Definition at line 265 of file ScopedPointer.h.
References static_bassert.
 { static_bassert (sizeof (Type) == 12345); }
template<class AgedContainer , class Rep , class Period > std::enable_if< is_aged_container <AgedContainer>::value, std::size_t>::type beast::expire (AgedContainer & c, std::chrono::duration< Rep, Period > const & age)
Expire aged container items past the specified age.
Definition at line 35 of file aged_container_utility.h.
Referenced by ripple::PeerFinder::SlotImp::recent_t::expire(), ripple::PeerFinder::Logic::expire(), and ripple::ProofOfWorkFactoryImp::sweep().
 {
     std::size_t n (0);
     auto const expired (c.clock().now() - age);
     for (auto iter (c.chronological.cbegin());
         iter != c.chronological.cend() &&
             iter.when() <= expired;)
     {
         iter = c.erase (iter);
         ++n;
     }
     return n;
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare , class Allocator , class Rep , class Period > std::size_t beast::expire (detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator > & c, std::chrono::duration< Rep, Period > const & age)
Expire aged container items past the specified age.
Definition at line 1907 of file aged_ordered_container.h.
 {
     std::size_t n (0);
     auto const expired (c.clock().now() - age);
     for (auto iter (c.chronological.cbegin());
         iter != c.chronological.cend() &&
             iter.when() <= expired;)
     {
         iter = c.erase (iter);
         ++n;
     }
     return n;
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash , class KeyEqual , class Allocator , class Rep , class Period > std::size_t beast::expire (detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator > & c, std::chrono::duration< Rep, Period > const & age) noexcept
Expire aged container items past the specified age.
Definition at line 2465 of file aged_unordered_container.h.
 {
     std::size_t n (0);
     auto const expired (c.clock().now() - age);
     for (auto iter (c.chronological.cbegin());
         iter != c.chronological.cend() &&
             iter.when() <= expired;)
     {
         iter = c.erase (iter);
         ++n;
     }
     return n;
 }
template<class CharT , class Traits , class Allocator > field_t<CharT, Traits, Allocator> beast::field (std::basic_string< CharT, Traits, Allocator > const & text, int width = 8, int pad = 0, bool right = false)
Definition at line 158 of file iosformat.h.
Referenced by ripple::STObject::add(), ripple::STArray::construct(), field(), beast::HTTPHeaders::get(), ripple::TransactionMetaSet::getAffectedAccounts(), ripple::STObject::getFieldIndex(), ripple::STParsedJSON::make_name(), beast::HTTPHeaders::operator[](), ripple::STParsedJSON::parse(), ripple::OrderBookDB::processTxn(), rfield(), ripple::STObject::set(), and beast::HTTPHeaders::toString().
 {
     return field_t <CharT, Traits, Allocator> (
         text, width, pad, right);
 }
template<class CharT > field_t<CharT> beast::field (CharT const * text, int width = 8, int pad = 0, bool right = false)
Definition at line 167 of file iosformat.h.
 {
     return field_t <CharT, std::char_traits <CharT>,
         std::allocator <CharT>> (std::basic_string <CharT,
             std::char_traits <CharT>, std::allocator <CharT>> (text),
                 width, pad, right);
 }
template<typename T > field_t<char> beast::field (T const & t, int width = 8, int pad = 0, bool right = false)
Definition at line 177 of file iosformat.h.
References field(), and beast::detail::to_string().
 {
     std::string const text (detail::to_string (t));
     return field (text, width, pad, right);
 }
static bool beast::fileMatches (const StringArray & wildCards, const String & filename) static
Definition at line 36 of file DirectoryIterator.cpp.
References beast::File::areFileNamesCaseSensitive(), beast::String::matchesWildcard(), and beast::StringArray::size().
Referenced by beast::DirectoryIterator::next().
 {
     for (int i = 0; i < wildCards.size(); ++i)
         if (filename.matchesWildcard (wildCards[i], ! File::areFileNamesCaseSensitive()))
             return true;
     return false;
 }
template<class ElementType , class ElementComparator > static int beast::findInsertIndexInSortedArray (ElementComparator & comparator, ElementType *const array, const ElementType newElement, int firstElement, int lastElement) static
Searches a sorted array of elements, looking for the index at which a specified value should be inserted for it to be in the correct order.
The comparator object that is passed-in must define a public method with the following signature:
int compareElements (ElementType first, ElementType second);
..and this method must return:
a value of < 0 if the first comes before the second
a value of 0 if the two objects are equivalent
a value of > 0 if the second comes before the first
To improve performance, the compareElements() method can be declared as static or const.
Parameters
comparator an object which defines a compareElements() method
array the array to search
newElement the value that is going to be inserted
firstElement the index of the first element to search
lastElement the index of the last element in the range (this is non-inclusive)
Definition at line 120 of file ElementComparator.h.
References bassert.
Referenced by beast::Array< beast::String >::addSorted().
 {
     bassert (firstElement <= lastElement);
     (void) comparator;  // if you pass in an object with a static compareElements() method, this
                         // avoids getting warning messages about the parameter being unused
     while (firstElement < lastElement)
     {
         if (comparator.compareElements (newElement, array [firstElement]) == 0)
         {
             ++firstElement;
             break;
         }
         else
         {
             const int halfway = (firstElement + lastElement) >> 1;
             if (halfway == firstElement)
             {
                 if (comparator.compareElements (newElement, array [halfway]) >= 0)
                     ++firstElement;
                 break;
             }
             else if (comparator.compareElements (newElement, array [halfway]) >= 0)
             {
                 firstElement = halfway;
             }
             else
             {
                 lastElement = halfway;
             }
         }
     }
     return firstElement;
 }
template<typename Type > const Type beast::findMaximum (const Type * values, int numValues)
Scans an array of values, returning the maximum value that it contains.
Definition at line 89 of file Arithmetic.h.
 {
     if (numValues <= 0)
         return Type();
     Type result (*values++);
     while (--numValues > 0) // (> 0 rather than >= 0 because we've already taken the first sample)
     {
         const Type& v = *values++;
         if (result < v)  result = v;
     }
     return result;
 }
template<typename Type > void beast::findMinAndMax (const Type * values, int numValues, Type & lowest, Type & highest)
Scans an array of values, returning the minimum and maximum values that it contains.
Definition at line 107 of file Arithmetic.h.
 {
     if (numValues <= 0)
     {
         lowest = Type();
         highest = Type();
     }
     else
     {
         Type mn (*values++);
         Type mx (mn);
         while (--numValues > 0) // (> 0 rather than >= 0 because we've already taken the first sample)
         {
             const Type& v = *values++;
             if (mx < v)  mx = v;
             if (v < mn)  mn = v;
         }
         lowest = mn;
         highest = mx;
     }
 }
template<typename Type > const Type beast::findMinimum (const Type * data, int numValues)
Scans an array of values, returning the minimum value that it contains.
Definition at line 71 of file Arithmetic.h.
 {
     if (numValues <= 0)
         return Type();
     Type result (*data++);
     while (--numValues > 0) // (> 0 rather than >= 0 because we've already taken the first sample)
     {
         const Type& v = *data++;
         if (v < result)  result = v;
     }
     return result;
 }
static String::CharPointerType beast::findTrimmedEnd (const String::CharPointerType start, String::CharPointerType end) static
Definition at line 1447 of file String.cpp.
Referenced by beast::String::trim(), and beast::String::trimEnd().
 {
     while (end > start)
     {
         if (! (--end).isWhitespace())
         {
             ++end;
             break;
         }
     }
     return end;
 }
template<typename IntegralType > IntegralType beast::fromNetworkByteOrder (IntegralType value) inline noexcept
Converts from network byte order to machine byte order.
Definition at line 286 of file ByteOrder.h.
References swapBytes(), and value.
Referenced by beast::asio::HandshakeDetectLogicSSL3::analyze(), and beast::asio::FixedInputBuffer::readNetworkInteger().
 {
 #if BEAST_LITTLE_ENDIAN
     return swapBytes (value);
 #else
     return value;
 #endif
 }
template<class TrivialClock , class Duration > abstract_clock<Duration>& beast::get_abstract_clock ()
Retrieve a discrete clock for a type implementing the Clock concept. The interface is created as an object with static storage duration.
Definition at line 160 of file abstract_clock.h.
Referenced by beast::abstract_clock_test::run().
 {
     static detail::abstract_clock_wrapper <
         TrivialClock, Duration> clock;
     return clock;
 }
template<class T > const T* beast::get_pointer (SharedPtr< T > const & ptr)
Definition at line 273 of file SharedPtr.h.
References beast::SharedPtr< T >::get().
 {
     return ptr.get();
 }
template<class T > T* beast::get_pointer (SharedPtr< T > & ptr)
Definition at line 279 of file SharedPtr.h.
References beast::SharedPtr< T >::get().
 {
     return ptr.get();
 }
template<typename Type1 , typename Type2 > int beast::getAddressDifference (Type1 * pointer1, Type2 * pointer2) noexcept
A handy function which returns the difference between any two pointers, in bytes. The address of the second pointer is subtracted from the first, and the difference in bytes is returned.
Definition at line 65 of file Memory.h.
Referenced by beast::String::appendCharPointer(), and beast::CharacterFunctions::copyWithDestByteLimit().
     { return (int) (((const char*) pointer1) - (const char*) pointer2); }
static const CPUInformation& beast::getCPUInformation () static noexcept
Definition at line 62 of file SystemStats.cpp.
Referenced by beast::SystemStats::getNumCpus(), beast::SystemStats::has3DNow(), beast::SystemStats::hasMMX(), beast::SystemStats::hasSSE(), beast::SystemStats::hasSSE2(), and beast::SystemStats::hasSSE3().
 {
     static CPUInformation info;
     return info;
 }
static CurrentThreadHolder::Ptr beast::getCurrentThreadHolder () static
Definition at line 75 of file Thread.cpp.
References castToSpinLockWithoutAliasingWarning(), and currentThreadHolderLock.
Referenced by beast::Thread::getCurrentThread(), and beast::Thread::threadEntryPoint().
 {
     static CurrentThreadHolder::Ptr currentThreadHolder;
     SpinLock::ScopedLockType lock (*castToSpinLockWithoutAliasingWarning (currentThreadHolderLock));
     if (currentThreadHolder == nullptr)
         currentThreadHolder = new CurrentThreadHolder();
     return currentThreadHolder;
 }
static String beast::getLocaleValue (CFStringRef key) static
Definition at line 213 of file mac_SystemStats.mm.
 {
     CFLocaleRef cfLocale = CFLocaleCopyCurrent();
     const String result (String::fromCFString ((CFStringRef) CFLocaleGetValue (cfLocale, key)));
     CFRelease (cfLocale);
     return result;
 }
static String beast::getLocaleValue (nl_item key)
Definition at line 282 of file bsd_SystemStats.cpp.
 {
     const char* oldLocale = ::setlocale (LC_ALL, "");
     return String (const_cast <const char*> (nl_langinfo (key)));
     ::setlocale (LC_ALL, oldLocale);
 }
static String beast::getLocaleValue (LCID locale, LCTYPE key, const char * defaultValue) static
Definition at line 400 of file win32_SystemStats.cpp.
 {
     TCHAR buffer [256] = { 0 };
     if (GetLocaleInfo (locale, key, buffer, 255) > 0)
         return buffer;
     return defaultValue;
 }
static String beast::getOSXVersion () static
Definition at line 107 of file mac_SystemStats.mm.
References BEAST_AUTORELEASEPOOL.
 {
     BEAST_AUTORELEASEPOOL
     {
         NSDictionary* dict = [NSDictionary dictionaryWithContentsOfFile:
                                     nsStringLiteral ("/System/Library/CoreServices/SystemVersion.plist")];
         return nsStringToBeast ([dict objectForKey: nsStringLiteral ("ProductVersion")]);
     }
 }
static int beast::getsysctl (char * name, void * ptr, size_t len) static
Definition at line 86 of file bsd_SystemStats.cpp.
{
         size_t nlen = len;
         if (sysctlbyname(name, ptr, &nlen, NULL, 0) == -1)
                 return -1;
         if (nlen != len)
                 return -1;
         return 0;
 }
void* beast::getUser32Function (const char * functionName)
Definition at line 27 of file win32_Threads.cpp.
References bassert.
 {
     HMODULE module = GetModuleHandleA ("user32.dll");
     bassert (module != 0);
     return (void*) GetProcAddress (module, functionName);
 }
static void beast::handleCrash (int) static
Definition at line 138 of file SystemStats.cpp.
References globalCrashHandler.
Referenced by beast::SystemStats::setApplicationCrashHandler().
 {
     globalCrashHandler();
     kill (getpid(), SIGKILL);
 }
template<class Hasher > void beast::hash_append (Hasher & h, URL const & url) inline
boost::hash support
Definition at line 128 of file URL.h.
References hash_append(), and beast::URL::toString().
 {
     using beast::hash_append;
     hash_append (h, url.toString());
 }
template<class Hasher , class T > std::enable_if< is_contiguously_hashable<T>::value>::type beast::hash_append (Hasher & h, T const & t) inline noexcept
Logically concatenate input data to a Hasher.
Hasher requirements:
`X` is the type `Hasher`
`h` is a value of type `x`
`p` is a value convertible to `void const*`
`n` is a value of type `std::size_t`, greater than zero
Expression:
    `h.append (p, n);`
Throws:
    Never
Effect:
    Adds the input data to the hasher state.
Expression:
    `static_cast<std::size_t>(j)`
Throws:
    Never
Effect:
    Returns the reslting hash of all the input data.
Definition at line 184 of file hash_append.h.
Referenced by ripple::hash_append(), hash_append(), beast::detail::hash_one(), beast::hash_append_test::make_hashes(), beast::hardened_hash< T, Hasher >::operator()(), and beast::uhash< Hasher >::operator()().
 {
     h.append (&t, sizeof(t));
 }
template<class Hasher , class T > std::enable_if< std::is_floating_point<T>::value>::type beast::hash_append (Hasher & h, T t) inline noexcept
Definition at line 195 of file hash_append.h.
 {
     // hash both signed zeroes identically
     if (t == 0)
         t = 0;
     h.append (&t, sizeof(t));
 }
template<class Hasher , class T , std::size_t N> std::enable_if< !is_contiguously_hashable<T>::value>::type beast::hash_append (Hasher & h, T(&) a[N]) inline noexcept
Definition at line 211 of file hash_append.h.
References hash_append().
 {
     for (auto const& t : a)
         hash_append (h, t);
 }
template<class Hasher , class T , std::size_t N> std::enable_if< is_contiguously_hashable<T>::value>::type beast::hash_append (Hasher & h, T(&) a[N]) inline noexcept
Definition at line 223 of file hash_append.h.
References T.
 {
     h.append (a, N*sizeof(T));
 }
template<class Hasher > void beast::hash_append (Hasher & h, std::nullptr_t p) inline noexcept
Definition at line 233 of file hash_append.h.
 {
     h.append (&p, sizeof(p));
 }
template<class Hasher , class CharT , class Traits , class Alloc > void beast::hash_append (Hasher & h, std::basic_string< CharT, Traits, Alloc > const & s) inline noexcept
Definition at line 243 of file hash_append.h.
 {
     h.append (s.data (), (s.size()+1)*sizeof(CharT));
 }
template<class Hasher , class T , class U > std::enable_if< !is_contiguously_hashable< std::pair< T, U > >::value >::type beast::hash_append (Hasher & h, std::pair< T, U > const & p) inline noexcept
Definition at line 597 of file hash_append.h.
References hash_append().
 {
     hash_append (h, p.first);
     hash_append (h, p.second);
 }
template<class Hasher , class T , class Alloc > std::enable_if< !is_contiguously_hashable< T >::value >::type beast::hash_append (Hasher & h, std::vector< T, Alloc > const & v) inline noexcept
Definition at line 611 of file hash_append.h.
References hash_append().
 {
     for (auto const& t : v)
         hash_append (h, t);
 }
template<class Hasher , class T , class Alloc > std::enable_if< is_contiguously_hashable< T >::value >::type beast::hash_append (Hasher & h, std::vector< T, Alloc > const & v) inline noexcept
Definition at line 623 of file hash_append.h.
References T.
 {
     h.append (v.data(), v.size()*sizeof(T));
 }
template<class Hasher , class T , std::size_t N> std::enable_if< !is_contiguously_hashable<std::array<T, N> >::value>::type beast::hash_append (Hasher & h, std::array< T, N > const & a) noexcept
template<class Hasher > void beast::hash_append (Hasher & h, std::tuple<> const & t) inline noexcept
Definition at line 395 of file hash_append.h.
References hash_append().
 {
     hash_append (h, nullptr);
 }
template<class Hasher , class... T> std::enable_if< !is_contiguously_hashable<std::tuple<T...> >::value>::type beast::hash_append (Hasher & h, std::tuple< T...> const & t) inline noexcept
Definition at line 582 of file hash_append.h.
References beast::detail::tuple_hash().
 {
     detail::tuple_hash(h, t, std::index_sequence_for<T...>{});
 }
template<class Hasher , class T > void beast::hash_append (Hasher & h, std::shared_ptr< T > const & p) inline noexcept
Definition at line 633 of file hash_append.h.
References hash_append().
 {
     hash_append(h, p.get());
 }
template<class Hasher , class T0 , class T1 , class... T> void beast::hash_append (Hasher & h, T0 const & t0, T1 const & t1, T const &... t) inline noexcept
Definition at line 653 of file hash_append.h.
References hash_append().
 {
     hash_append (h, t0);
     hash_append (h, t1, t...);
 }
std::size_t beast::hash_value (URL const & v)
Definition at line 169 of file URL.cpp.
References beast::String::hash(), and beast::URL::toString().
Referenced by std::hash< beast::IP::AddressV6 >::operator()(), std::hash< beast::URL >::operator()(), std::hash< beast::IP::Endpoint >::operator()(), std::hash< beast::IP::AddressV4 >::operator()(), std::hash< beast::IP::Address >::operator()(), and beast::call_hash_value::operator()().
 {
     return std::size_t (v.toString().hash());
 }
template<class CharT , class Traits , class Allocator > std::basic_string<CharT, Traits, Allocator> beast::heading (std::basic_string< CharT, Traits, Allocator > title, int width = 80, CharT fill = CharT ('-'))
Produce a section heading and fill the rest of the line with dashes.
Definition at line 51 of file iosformat.h.
 {
     title.reserve (width);
     title.push_back (CharT (' '));
     title.resize (width, fill);
     return title;
 }
static HiResCounterHandler& beast::hiResCounterHandler () static
Definition at line 273 of file mac_SystemStats.mm.
References hiResCounterHandler.
 {
     static HiResCounterHandler hiResCounterHandler;
     return hiResCounterHandler;
 }
template<> std::int32_t beast::InputStream::readType< std::int32_t > ()
Definition at line 271 of file InputStream.cpp.
 { return readInt32 (); }
template<> std::int64_t beast::InputStream::readType< std::int64_t > ()
Definition at line 274 of file InputStream.cpp.
 { return readInt64 (); }
template<> std::uint32_t beast::InputStream::readType< std::uint32_t > ()
Definition at line 283 of file InputStream.cpp.
 { return static_cast <std::uint32_t> (readInt32 ()); }
template<> std::uint64_t beast::InputStream::readType< std::uint64_t > ()
Definition at line 286 of file InputStream.cpp.
 { return static_cast <std::uint64_t> (readInt64 ()); }
template<> std::int32_t beast::InputStream::readTypeBigEndian< std::int32_t > ()
Definition at line 303 of file InputStream.cpp.
 { return readInt32BigEndian (); }
template<> std::int64_t beast::InputStream::readTypeBigEndian< std::int64_t > ()
Definition at line 306 of file InputStream.cpp.
 { return readInt64BigEndian (); }
template<> std::uint32_t beast::InputStream::readTypeBigEndian< std::uint32_t > ()
Definition at line 315 of file InputStream.cpp.
 { return static_cast <std::uint32_t> (readInt32BigEndian ()); }
template<> std::uint64_t beast::InputStream::readTypeBigEndian< std::uint64_t > ()
Definition at line 318 of file InputStream.cpp.
 { return static_cast <std::uint64_t> (readInt64BigEndian ()); }
static bool beast::isFileExecutable (const String & filename) static
Definition at line 321 of file bsd_Files.cpp.
References beast::String::toUTF8().
Referenced by beast::Process::openDocument().
 {
     beast_statStruct info;
     return beast_stat (filename, info)
             && S_ISREG (info.st_mode)
             && access (filename.toUTF8(), X_OK) == 0;
 }
static bool beast::isFileExecutable (const String & filename) static
Definition at line 321 of file linux_Files.cpp.
References beast::String::toUTF8().
 {
     beast_statStruct info;
     return beast_stat (filename, info)
             && S_ISREG (info.st_mode)
             && access (filename.toUTF8(), X_OK) == 0;
 }
template<typename Type > bool beast::isPositiveAndBelow (Type valueToTest, Type upperLimit) inline noexcept
Returns true if a value is at least zero, and also below a specified upper limit. This is basically a quicker way to write:
valueToTest >= 0 && valueToTest < upperLimit
Definition at line 167 of file Arithmetic.h.
References bassert.
Referenced by beast::StringArray::getReference(), beast::Array< beast::String >::getReference(), beast::Array< beast::String >::getUnchecked(), beast::Array< beast::String >::insert(), beast::Array< beast::String >::insertArray(), beast::Array< beast::String >::insertMultiple(), beast::Array< beast::String >::move(), beast::StringArray::operator[](), beast::Array< beast::String >::operator[](), beast::Array< beast::String >::remove(), beast::Array< beast::String >::set(), beast::Array< beast::String >::setUnchecked(), and beast::Array< beast::String >::swap().
 {
     bassert (Type() <= upperLimit); // makes no sense to call this if the upper limit is itself below zero..
     return Type() <= valueToTest && valueToTest < upperLimit;
 }
template<> bool beast::isPositiveAndBelow (const int valueToTest, const int upperLimit) inline noexcept
Definition at line 174 of file Arithmetic.h.
References bassert.
 {
     bassert (upperLimit >= 0); // makes no sense to call this if the upper limit is itself below zero..
     return static_cast <unsigned int> (valueToTest) < static_cast <unsigned int> (upperLimit);
 }
template<typename Type > bool beast::isPositiveAndNotGreaterThan (Type valueToTest, Type upperLimit) inline noexcept
Returns true if a value is at least zero, and also less than or equal to a specified upper limit. This is basically a quicker way to write:
valueToTest >= 0 && valueToTest <= upperLimit
Definition at line 186 of file Arithmetic.h.
References bassert.
 {
     bassert (Type() <= upperLimit); // makes no sense to call this if the upper limit is itself below zero..
     return Type() <= valueToTest && valueToTest <= upperLimit;
 }
template<> bool beast::isPositiveAndNotGreaterThan (const int valueToTest, const int upperLimit) inline noexcept
Definition at line 193 of file Arithmetic.h.
References bassert.
 {
     bassert (upperLimit >= 0); // makes no sense to call this if the upper limit is itself below zero..
     return static_cast <unsigned int> (valueToTest) <= static_cast <unsigned int> (upperLimit);
 }
static bool beast::isWindowsVersionOrLater (SystemStats::OperatingSystemType target) static
Definition at line 119 of file win32_SystemStats.cpp.
References bassertfalse, FALSE, beast::SystemStats::Windows7, beast::SystemStats::Windows8, beast::SystemStats::WinVista, beast::SystemStats::WinXP, and zerostruct().
 {
     OSVERSIONINFOEX info;
     zerostruct (info);
     info.dwOSVersionInfoSize = sizeof (OSVERSIONINFOEX);
     if (target >= SystemStats::WinVista)
     {
         info.dwMajorVersion = 6;
         switch (target)
         {
             case SystemStats::WinVista:  info.dwMinorVersion = 0; break;
             case SystemStats::Windows7:  info.dwMinorVersion = 1; break;
             case SystemStats::Windows8:  info.dwMinorVersion = 2; break;
             default:                     bassertfalse; break;
         }
     }
     else
     {
         info.dwMajorVersion = 5;
         info.dwMinorVersion = target >= SystemStats::WinXP ? 1 : 0;
     }
     DWORDLONG mask = 0;
     VER_SET_CONDITION (mask, VER_MAJORVERSION,     VER_GREATER_EQUAL);
     VER_SET_CONDITION (mask, VER_MINORVERSION,     VER_GREATER_EQUAL);
     VER_SET_CONDITION (mask, VER_SERVICEPACKMAJOR, VER_GREATER_EQUAL);
     VER_SET_CONDITION (mask, VER_SERVICEPACKMINOR, VER_GREATER_EQUAL);
     return VerifyVersionInfo (&info,
                               VER_MAJORVERSION | VER_MINORVERSION
                                | VER_SERVICEPACKMAJOR | VER_SERVICEPACKMINOR,
                               mask) != FALSE;
 }
template<class Out , class In > Out beast::lexicalCast (In in, Out defaultValue = Out ())
Convert from one type to another.
Parameters
defaultValue The value returned if parsing fails
Returns
The new type.
Definition at line 296 of file LexicalCast.h.
References lexicalCastChecked().
 {
     Out out;
     if (lexicalCastChecked (out, in))
         return out;
     return defaultValue;
 }
template<class Out , class In > bool beast::lexicalCastChecked (Out & out, In in)
Intelligently convert from one type to another.
Returns
false if there was a parsing or range error
Definition at line 266 of file LexicalCast.h.
Referenced by lexicalCast(), lexicalCastThrow(), and beast::LexicalCast_test::testInteger().
 {
     return LexicalCast <Out, In> () (out, in);
 }
template<class Out , class In > Out beast::lexicalCastThrow (In in)
Convert from one type to another, throw on error
An exception of type BadLexicalCast is thrown if the conversion fails.
Returns
The new type.
Definition at line 278 of file LexicalCast.h.
References lexicalCastChecked().
 {
     Out out;
     if (lexicalCastChecked (out, in))
         return out;
     throw BadLexicalCast ();
     return Out ();
 }
template<typename ContainerIterator > cyclic_iterator<ContainerIterator> beast::make_cyclic (ContainerIterator const & pos, ContainerIterator const & begin, ContainerIterator const & end)
template<class CharT , class Traits = std::char_traits <CharT>> basic_std_ostream<CharT, Traits> beast::make_std_ostream (std::basic_ostream< CharT, Traits > & stream)
Returns a basic_std_ostream using template argument deduction.
Definition at line 66 of file basic_std_ostream.h.
Referenced by beast::unit_test::print().
 {
     return basic_std_ostream <CharT, Traits> (stream);
 }
template<typename Function > double beast::measureFunctionCallTime (Function f)
Measures the speed of invoking a function.
Definition at line 29 of file MeasureFunctionCallTime.h.
References ripple::f, beast::Time::getHighResolutionTicks(), and beast::Time::highResolutionTicksToSeconds().
Referenced by ripple::logTimedCall().
 {
     std::int64_t const startTime (Time::getHighResolutionTicks ());
     f ();
     return Time::highResolutionTicksToSeconds (
             Time::getHighResolutionTicks () - startTime);
 }
void beast::memoryBarrier () inline noexcept
Definition at line 411 of file Atomic.h.
References beast_MemoryBarrier().
Referenced by beast::SharedSingleton< beast::sqdb::session::Sqlite3 >::get(), ripple::UptimeTimer::getElapsedSeconds(), beast::Stoppable::stopRecursive(), beast::Atomic_test::testFloat(), and beast::Atomic_test::testInteger().
 {
   #if BEAST_ATOMICS_MAC
     OSMemoryBarrier();
   #elif BEAST_ATOMICS_GCC
     __sync_synchronize();
   #elif BEAST_ATOMICS_WINDOWS
     beast_MemoryBarrier();
   #endif
 }
template<typename Type , int N> int beast::numElementsInArray (Type(&) array[N])
Handy function for getting the number of elements in a simple const C array. E.g.
static int myArray[] = { 1, 2, 3 };
int numElements = numElementsInArray (myArray) // returns 3
Definition at line 210 of file Arithmetic.h.
Referenced by beast::NumberToStringConverters::createFromDouble(), beast::NumberToStringConverters::createFromInteger(), beast::WindowsFileHelpers::getModuleFileName(), beast::WindowsFileHelpers::getResultForLastError(), beast::SystemStats::getStackBacktrace(), beast::Process::openDocument(), beast::String::operator+=(), beast::Atomic_test::run(), and beast::SystemStats::setApplicationCrashHandler().
 {
     (void) array; // (required to avoid a spurious warning in MS compilers)
     (void) sizeof (0[array]); // This line should cause an error if you pass an object with a user-defined subscript operator
     return N;
 }
template<class T > T beast::oneOverTwoPi () inline noexcept
Definition at line 65 of file Math.h.
 {
     return 0.1591549430918955;
 }
template<typename T > bool beast::operator!= (T const & t, Zero)
Definition at line 93 of file Zero.h.
References beast::detail::zero_helper::call_signum().
 {
     return detail::zero_helper::call_signum(t) != 0;
 }
bool beast::operator!= (URL const & lhs, URL const & rhs) inline
Definition at line 114 of file URL.h.
References beast::URL::toString().
 { return ! (lhs.toString() == rhs.toString()); }
template<class Container , bool LhsIsConst, bool RhsIsConst> bool beast::operator!= (LockFreeStackIterator< Container, LhsIsConst > const & lhs, LockFreeStackIterator< Container, RhsIsConst > const & rhs)
Definition at line 124 of file LockFreeStack.h.
References beast::LockFreeStackIterator< Container, IsConst >::node().
 {
     return lhs.node() != rhs.node();
 }
template<typename T > bool beast::operator!= (Zero , T const & t)
Definition at line 132 of file Zero.h.
 {
     return t != zero;
 }
bool beast::operator!= (RelativeTime t1, RelativeTime t2) noexcept
Definition at line 153 of file RelativeTime.cpp.
 {
     return t1.inSeconds() != t2.inSeconds();
 }
template<class ObjectType > bool beast::operator!= (const ScopedPointer< ObjectType > & pointer1, ObjectType *const pointer2)
Compares a ScopedPointer with another pointer. This can be handy for checking whether this is a null pointer.
Definition at line 256 of file ScopedPointer.h.
 {
     return static_cast <ObjectType*> (pointer1) != pointer2;
 }
template<class T , class U > bool beast::operator!= (SharedPtr< T > const & lhs, U const * rhs) noexcept
Definition at line 307 of file SharedPtr.h.
References lhs.
 {
     return lhs.get() != rhs;
 }
template<class T , class U > bool beast::operator!= (SharedPtr< T > const & lhs, SharedPtr< U > const & rhs) noexcept
Definition at line 313 of file SharedPtr.h.
References lhs.
 {
     return lhs.get() != rhs.get();
 }
template<class T , class U > bool beast::operator!= (T const * lhs, SharedPtr< U > const & rhs) noexcept
Definition at line 319 of file SharedPtr.h.
References lhs.
 {
     return lhs != rhs.get();
 }
bool beast::operator!= (Time time1, Time time2)
Compares two Time objects.
Definition at line 440 of file Time.cpp.
References beast::Time::toMilliseconds().
 { return time1.toMilliseconds() != time2.toMilliseconds(); }
bool beast::operator!= (const String & string1, const String & string2) noexcept
Case-sensitive comparison of two strings.
Definition at line 456 of file String.cpp.
 { return s1.compare (s2) != 0; }
bool beast::operator!= (const String & string1, const char * string2) noexcept
Case-sensitive comparison of two strings.
Definition at line 457 of file String.cpp.
 { return s1.compare (s2) != 0; }
bool beast::operator!= (const String & string1, const wchar_t * string2) noexcept
Case-sensitive comparison of two strings.
Definition at line 458 of file String.cpp.
 { return s1.compare (s2) != 0; }
bool beast::operator!= (const String & string1, const CharPointer_UTF8 string2) noexcept
Case-sensitive comparison of two strings.
Definition at line 459 of file String.cpp.
 { return s1.getCharPointer().compare (s2) != 0; }
bool beast::operator!= (const String & string1, const CharPointer_UTF16 string2) noexcept
Case-sensitive comparison of two strings.
Definition at line 460 of file String.cpp.
 { return s1.getCharPointer().compare (s2) != 0; }
bool beast::operator!= (const String & string1, const CharPointer_UTF32 string2) noexcept
Case-sensitive comparison of two strings.
Definition at line 461 of file String.cpp.
 { return s1.getCharPointer().compare (s2) != 0; }
template<class T , class Tag > bool beast::operator!= (buffer_view< T, Tag > lhs, buffer_view< T, Tag > rhs) inline
Definition at line 462 of file buffer_view.h.
 {
     return ! (lhs == rhs);
 }
RelativeTime beast::operator+ (RelativeTime t1, RelativeTime t2) noexcept
Adds two RelativeTimes together.
Definition at line 138 of file RelativeTime.cpp.
 {
     return t1 += t2;
 }
Time beast::operator+ (Time time, RelativeTime delta)
Adds a RelativeTime to a Time.
Definition at line 434 of file Time.cpp.
 { Time t (time); return t += delta; }
Time beast::operator+ (RelativeTime delta, Time time)
Adds a RelativeTime to a Time.
Definition at line 436 of file Time.cpp.
 { Time t (time); return t += delta; }
String beast::operator+ (const char * string1, const String & string2)
Concatenates two strings.
Definition at line 617 of file String.cpp.
 {
     String s (string1);
     return s += string2;
 }
String beast::operator+ (const wchar_t * string1, const String & string2)
Concatenates two strings.
Definition at line 623 of file String.cpp.
 {
     String s (string1);
     return s += string2;
 }
String beast::operator+ (char string1, const String & string2)
Concatenates two strings.
Definition at line 629 of file String.cpp.
References beast::String::charToString().
 { return String::charToString ((beast_wchar) (std::uint8_t) s1) + s2; }
String beast::operator+ (wchar_t string1, const String & string2)
Concatenates two strings.
Definition at line 630 of file String.cpp.
References beast::String::charToString().
 { return String::charToString (s1) + s2; }
String beast::operator+ (String string1, const String & string2)
Concatenates two strings.
Definition at line 635 of file String.cpp.
 { return s1 += s2; }
String beast::operator+ (String string1, const char * string2)
Concatenates two strings.
Definition at line 636 of file String.cpp.
 { return s1 += s2; }
String beast::operator+ (String string1, const wchar_t * string2)
Concatenates two strings.
Definition at line 637 of file String.cpp.
 { return s1 += s2; }
String beast::operator+ (String string1, char characterToAppend)
Concatenates two strings.
Definition at line 639 of file String.cpp.
 { return s1 += s2; }
String beast::operator+ (String string1, wchar_t characterToAppend)
Concatenates two strings.
Definition at line 640 of file String.cpp.
 { return s1 += s2; }
RelativeTime beast::operator- (RelativeTime t1, RelativeTime t2) noexcept
Subtracts two RelativeTimes.
Definition at line 143 of file RelativeTime.cpp.
 {
     return t1 -= t2;
 }
Time beast::operator- (Time time, RelativeTime delta)
Subtracts a RelativeTime from a Time.
Definition at line 435 of file Time.cpp.
 { Time t (time); return t -= delta; }
const RelativeTime beast::operator- (Time time1, Time time2)
Returns the relative time difference between two times.
Definition at line 437 of file Time.cpp.
References beast::RelativeTime::milliseconds(), and beast::Time::toMilliseconds().
 { return RelativeTime::milliseconds (time1.toMilliseconds() - time2.toMilliseconds()); }
template<typename T > bool beast::operator< (T const & t, Zero)
Definition at line 99 of file Zero.h.
References beast::detail::zero_helper::call_signum().
 {
     return detail::zero_helper::call_signum(t) < 0;
 }
bool beast::operator< (URL const & lhs, URL const & rhs) inline
Definition at line 115 of file URL.h.
References beast::URL::toString().
 { return    lhs.toString() <  rhs.toString(); }
template<typename T > bool beast::operator< (Zero , T const & t)
Definition at line 138 of file Zero.h.
 {
     return t > zero;
 }
bool beast::operator< (RelativeTime t1, RelativeTime t2) noexcept
Definition at line 163 of file RelativeTime.cpp.
 {
     return t1.inSeconds() <  t2.inSeconds();
 }
bool beast::operator< (Time time1, Time time2)
Compares two Time objects.
Definition at line 441 of file Time.cpp.
References beast::Time::toMilliseconds().
 { return time1.toMilliseconds() <  time2.toMilliseconds(); }
bool beast::operator< (const String & string1, const String & string2) noexcept
Case-sensitive comparison of two strings.
Definition at line 463 of file String.cpp.
 { return s1.compare (s2) < 0; }
template<class T , class Tag > bool beast::operator< (buffer_view< T, Tag > lhs, buffer_view< T, Tag > rhs) inline
Definition at line 470 of file buffer_view.h.
References lhs.
 {
     return std::lexicographical_compare (
         lhs.cbegin(), lhs.cend(), rhs.cbegin(), rhs.cend());
 }
template<class CharT , class Traits , class Duration , class Resolution > std::basic_ostream<CharT, Traits>& beast::operator<< (std::basic_ostream< CharT, Traits > & os, std::chrono::time_point< abstract_clock< Resolution >, Duration > const & tp)
Definition at line 29 of file abstract_clock_io.h.
 {
     return os << tp.time_since_epoch() << " since epoch";
 }
std::ostream & beast::operator<< (std::ostream & os, URL const & url)
Output stream conversion.
Definition at line 161 of file URL.cpp.
References beast::URL::to_string().
 {
     os << url.to_string();
     return os;
 }
OutputStream & beast::operator<< (OutputStream & stream, const MemoryOutputStream & streamToRead)
Copies all the data that has been written to a MemoryOutputStream into another stream.
Definition at line 204 of file MemoryOutputStream.cpp.
References beast::MemoryOutputStream::getData(), beast::MemoryOutputStream::getDataSize(), and beast::OutputStream::write().
 {
     const size_t dataSize = streamToRead.getDataSize();
     if (dataSize > 0)
         stream.write (streamToRead.getData(), dataSize);
     return stream;
 }
std::ostream& beast::operator<< (std::ostream & os, RelativeTime const & diff) inline
Definition at line 208 of file RelativeTime.h.
References beast::RelativeTime::to_string().
 {
     os << diff.to_string();
     return os;
 }
OutputStream & beast::operator<< (OutputStream & stream, int number)
Writes a number to a stream as 8-bit characters in the default system encoding.
Definition at line 298 of file OutputStream.cpp.
 {
     return stream << String (number);
 }
OutputStream & beast::operator<< (OutputStream & stream, std::int64_t number)
Writes a number to a stream as 8-bit characters in the default system encoding.
Definition at line 303 of file OutputStream.cpp.
 {
     return stream << String (number);
 }
OutputStream & beast::operator<< (OutputStream & stream, double number)
Writes a number to a stream as 8-bit characters in the default system encoding.
Definition at line 308 of file OutputStream.cpp.
 {
     return stream << String (number);
 }
OutputStream & beast::operator<< (OutputStream & stream, char character)
Writes a character to a stream.
Definition at line 313 of file OutputStream.cpp.
References beast::OutputStream::writeByte().
 {
     stream.writeByte (character);
     return stream;
 }
OutputStream & beast::operator<< (OutputStream & stream, const char * text)
Writes a null-terminated text string to a stream.
Definition at line 319 of file OutputStream.cpp.
References beast::OutputStream::write().
 {
     stream.write (text, strlen (text));
     return stream;
 }
OutputStream & beast::operator<< (OutputStream & stream, const MemoryBlock & data)
Writes a block of data from a MemoryBlock to a stream.
Definition at line 325 of file OutputStream.cpp.
References beast::MemoryBlock::getData(), beast::MemoryBlock::getSize(), and beast::OutputStream::write().
 {
     if (data.getSize() > 0)
         stream.write (data.getData(), data.getSize());
     return stream;
 }
OutputStream & beast::operator<< (OutputStream & stream, const File & fileToRead)
Writes the contents of a file to a stream.
Definition at line 333 of file OutputStream.cpp.
References Json::in(), and beast::FileInputStream::openedOk().
 {
     FileInputStream in (fileToRead);
     if (in.openedOk())
         return stream << in;
     return stream;
 }
OutputStream & beast::operator<< (OutputStream & stream, InputStream & streamToRead)
Writes the complete contents of an input stream to an output stream.
Definition at line 343 of file OutputStream.cpp.
References beast::OutputStream::writeFromInputStream().
 {
     stream.writeFromInputStream (streamToRead, -1);
     return stream;
 }
OutputStream & beast::operator<< (OutputStream & stream, const NewLine &)
Writes a new-line to a stream. You can use the predefined symbol 'newLine' to invoke this, e.g.
myOutputStream << "Hello World" << newLine << newLine;
See Also
OutputStream::setNewLineString
Definition at line 349 of file OutputStream.cpp.
References beast::OutputStream::getNewLineString().
 {
     return stream << stream.getNewLineString();
 }
OutputStream & beast::operator<< (OutputStream & stream, const String & stringToWrite)
Writes a string to an OutputStream as UTF8.
Definition at line 421 of file OutputStream.cpp.
References beast::CharPointer_UTF8::getAddress(), beast::String::getCharPointer(), beast::String::getNumBytesAsUTF8(), beast::OutputStream::write(), and beast::CharPointer_UTF8::writeAll().
 {
     const size_t numBytes = text.getNumBytesAsUTF8();
    #if (BEAST_STRING_UTF_TYPE == 8)
     stream.write (text.getCharPointer().getAddress(), numBytes);
    #else
     // (This avoids using toUTF8() to prevent the memory bloat that it would leave behind
     // if lots of large, persistent strings were to be written to streams).
     HeapBlock<char> temp (numBytes + 1);
     CharPointer_UTF8 (temp).writeAll (text.getCharPointer());
     stream.write (temp, numBytes);
    #endif
     return stream;
 }
String & beast::operator<< (String & string1, char characterToAppend)
Appends a character at the end of a string.
Definition at line 645 of file String.cpp.
 { return s1 += s2; }
String & beast::operator<< (String & string1, wchar_t characterToAppend)
Appends a character at the end of a string.
Definition at line 646 of file String.cpp.
 { return s1 += s2; }
String & beast::operator<< (String & string1, const char * string2)
Appends a string to the end of the first one.
Definition at line 651 of file String.cpp.
 { return s1 += s2; }
String & beast::operator<< (String & string1, const wchar_t * string2)
Appends a string to the end of the first one.
Definition at line 652 of file String.cpp.
 { return s1 += s2; }
String & beast::operator<< (String & string1, const String & string2)
Appends a string to the end of the first one.
Definition at line 653 of file String.cpp.
 { return s1 += s2; }
String & beast::operator<< (String & string1, short number)
Appends a decimal number at the end of a string.
Definition at line 655 of file String.cpp.
 { return s1 += (int) number; }
String & beast::operator<< (String & string1, int number)
Appends a decimal number at the end of a string.
Definition at line 656 of file String.cpp.
 { return s1 += number; }
String & beast::operator<< (String & string1, long number)
Appends a decimal number at the end of a string.
Definition at line 657 of file String.cpp.
 { return s1 += (int) number; }
String& beast::operator<< (String & s1, const long long number)
Definition at line 658 of file String.cpp.
 { return s1 << String (number); }
String & beast::operator<< (String & string1, float number)
Appends a decimal number at the end of a string.
Definition at line 659 of file String.cpp.
 { return s1 += String (number); }
String & beast::operator<< (String & string1, double number)
Appends a decimal number at the end of a string.
Definition at line 660 of file String.cpp.
 { return s1 += String (number); }
String & beast::operator<< (String & string1, const NewLine &)
Writes a new-line sequence to a string. You can use the predefined object 'newLine' to invoke this, e.g.
myString << "Hello World" << newLine << newLine;
Definition at line 662 of file String.cpp.
References beast::NewLine::getDefault().
 {
     return string1 += NewLine::getDefault();
 }
String& beast::operator<< (String & string1, std::int64_t number)
Appends a decimal number at the end of a string.
template<class traits > std::basic_ostream<wchar_t, traits>& beast::operator<< (std::basic_ostream< wchar_t, traits > & stream, const String & stringToWrite)
This operator allows you to write a beast String directly to std output streams. This is handy for writing strings to std::wcout, std::wcerr, etc.
Definition at line 1387 of file String.h.
References beast::String::toWideCharPointer().
 {
     return stream << stringToWrite.toWideCharPointer();
 }
template<class traits > std::basic_ostream<char, traits>& beast::operator<< (std::basic_ostream< char, traits > & stream, const String & stringToWrite)
This operator allows you to write a beast String directly to std output streams. This is handy for writing strings to std::cout, std::cerr, etc.
Definition at line 1378 of file String.h.
References beast::String::toRawUTF8().
 {
     return stream << stringToWrite.toRawUTF8();
 }
template<typename T > bool beast::operator<= (T const & t, Zero)
Definition at line 117 of file Zero.h.
References beast::detail::zero_helper::call_signum().
 {
     return detail::zero_helper::call_signum(t) <= 0;
 }
bool beast::operator<= (URL const & lhs, URL const & rhs) inline
Definition at line 117 of file URL.h.
References beast::URL::toString().
 { return ! (rhs.toString() <  lhs.toString()); }
template<typename T > bool beast::operator<= (Zero , T const & t)
Definition at line 156 of file Zero.h.
 {
     return t >= zero;
 }
bool beast::operator<= (RelativeTime t1, RelativeTime t2) noexcept
Definition at line 173 of file RelativeTime.cpp.
 {
     return t1.inSeconds() <= t2.inSeconds();
 }
bool beast::operator<= (Time time1, Time time2)
Compares two Time objects.
Definition at line 443 of file Time.cpp.
References beast::Time::toMilliseconds().
 { return time1.toMilliseconds() <= time2.toMilliseconds(); }
bool beast::operator<= (const String & string1, const String & string2) noexcept
Case-sensitive comparison of two strings.
Definition at line 465 of file String.cpp.
 { return s1.compare (s2) <= 0; }
template<class T , class Tag > bool beast::operator<= (buffer_view< T, Tag > lhs, buffer_view< T, Tag > rhs) inline
Definition at line 495 of file buffer_view.h.
References lhs.
 {
     return ! (rhs < lhs);
 }
template<typename T > bool beast::operator== (T const & t, Zero)
Definition at line 87 of file Zero.h.
References beast::detail::zero_helper::call_signum().
 {
     return detail::zero_helper::call_signum(t) == 0;
 }
bool beast::operator== (URL const & lhs, URL const & rhs) inline
URL comparisons.
Definition at line 113 of file URL.h.
References beast::URL::toString().
 { return    lhs.toString() == rhs.toString(); }
template<class Container , bool LhsIsConst, bool RhsIsConst> bool beast::operator== (LockFreeStackIterator< Container, LhsIsConst > const & lhs, LockFreeStackIterator< Container, RhsIsConst > const & rhs)
Definition at line 117 of file LockFreeStack.h.
References beast::LockFreeStackIterator< Container, IsConst >::node().
 {
     return lhs.node() == rhs.node();
 }
template<typename T > bool beast::operator== (Zero , T const & t)
Definition at line 126 of file Zero.h.
 {
     return t == zero;
 }
bool beast::operator== (RelativeTime t1, RelativeTime t2) noexcept
Definition at line 148 of file RelativeTime.cpp.
Referenced by beast::MemoryBlock::operator!=(), and beast::StringArray::operator!=().
 {
     return t1.inSeconds() == t2.inSeconds();
 }
template<class ObjectType > bool beast::operator== (const ScopedPointer< ObjectType > & pointer1, ObjectType *const pointer2)
Compares a ScopedPointer with another pointer. This can be handy for checking whether this is a null pointer.
Definition at line 247 of file ScopedPointer.h.
 {
     return static_cast <ObjectType*> (pointer1) == pointer2;
 }
template<class T , class U > bool beast::operator== (SharedPtr< T > const & lhs, U *const rhs) noexcept
SharedPtr comparisons.
Definition at line 289 of file SharedPtr.h.
References lhs.
 {
     return lhs.get() == rhs;
 }
template<class T , class U > bool beast::operator== (SharedPtr< T > const & lhs, SharedPtr< U > const & rhs) noexcept
Definition at line 295 of file SharedPtr.h.
References lhs.
 {
     return lhs.get() == rhs.get();
 }
template<class T , class U > bool beast::operator== (T const * lhs, SharedPtr< U > const & rhs) noexcept
Definition at line 301 of file SharedPtr.h.
References lhs.
 {
     return lhs == rhs.get();
 }
bool beast::operator== (Time time1, Time time2)
Compares two Time objects.
Definition at line 439 of file Time.cpp.
References beast::Time::toMilliseconds().
 { return time1.toMilliseconds() == time2.toMilliseconds(); }
bool beast::operator== (const String & string1, const String & string2) noexcept
Case-sensitive comparison of two strings.
Definition at line 450 of file String.cpp.
 { return s1.compare (s2) == 0; }
bool beast::operator== (const String & string1, const char * string2) noexcept
Case-sensitive comparison of two strings.
Definition at line 451 of file String.cpp.
 { return s1.compare (s2) == 0; }
bool beast::operator== (const String & string1, const wchar_t * string2) noexcept
Case-sensitive comparison of two strings.
Definition at line 452 of file String.cpp.
 { return s1.compare (s2) == 0; }
bool beast::operator== (const String & string1, const CharPointer_UTF8 string2) noexcept
Case-sensitive comparison of two strings.
Definition at line 453 of file String.cpp.
 { return s1.getCharPointer().compare (s2) == 0; }
template<class T , class Tag > bool beast::operator== (buffer_view< T, Tag > lhs, buffer_view< T, Tag > rhs) inline
Definition at line 453 of file buffer_view.h.
References beast::buffer_view< T, Tag >::cbegin(), beast::buffer_view< T, Tag >::cend(), and std::detail::equal().
 {
     return std::equal (
         lhs.cbegin(), lhs.cend(), rhs.cbegin(), rhs.cend());
 }
bool beast::operator== (const String & string1, const CharPointer_UTF16 string2) noexcept
Case-sensitive comparison of two strings.
Definition at line 454 of file String.cpp.
 { return s1.getCharPointer().compare (s2) == 0; }
bool beast::operator== (const String & string1, const CharPointer_UTF32 string2) noexcept
Case-sensitive comparison of two strings.
Definition at line 455 of file String.cpp.
 { return s1.getCharPointer().compare (s2) == 0; }
template<typename T > bool beast::operator> (T const & t, Zero)
Definition at line 105 of file Zero.h.
References beast::detail::zero_helper::call_signum().
 {
     return detail::zero_helper::call_signum(t) > 0;
 }
bool beast::operator> (URL const & lhs, URL const & rhs) inline
Definition at line 116 of file URL.h.
References beast::URL::toString().
 { return    rhs.toString() <  lhs.toString(); }
template<typename T > bool beast::operator> (Zero , T const & t)
Definition at line 144 of file Zero.h.
 {
     return t < zero;
 }
bool beast::operator> (RelativeTime t1, RelativeTime t2) noexcept
Definition at line 158 of file RelativeTime.cpp.
 {
     return t1.inSeconds() >  t2.inSeconds();
 }
bool beast::operator> (Time time1, Time time2)
Compares two Time objects.
Definition at line 442 of file Time.cpp.
References beast::Time::toMilliseconds().
 { return time1.toMilliseconds() >  time2.toMilliseconds(); }
bool beast::operator> (const String & string1, const String & string2) noexcept
Case-sensitive comparison of two strings.
Definition at line 462 of file String.cpp.
 { return s1.compare (s2) > 0; }
template<class T , class Tag > bool beast::operator> (buffer_view< T, Tag > lhs, buffer_view< T, Tag > rhs) inline
Definition at line 487 of file buffer_view.h.
References lhs.
 {
     return rhs < lhs;
 }
template<typename T > bool beast::operator>= (T const & t, Zero)
Definition at line 111 of file Zero.h.
References beast::detail::zero_helper::call_signum().
 {
     return detail::zero_helper::call_signum(t) >= 0;
 }
bool beast::operator>= (URL const & lhs, URL const & rhs) inline
Definition at line 118 of file URL.h.
References beast::URL::toString().
 { return ! (lhs.toString() <  rhs.toString()); }
template<typename T > bool beast::operator>= (Zero , T const & t)
Definition at line 150 of file Zero.h.
 {
     return t <= zero;
 }
bool beast::operator>= (RelativeTime t1, RelativeTime t2) noexcept
Definition at line 168 of file RelativeTime.cpp.
 {
     return t1.inSeconds() >= t2.inSeconds();
 }
bool beast::operator>= (Time time1, Time time2)
Compares two Time objects.
Definition at line 444 of file Time.cpp.
References beast::Time::toMilliseconds().
 { return time1.toMilliseconds() >= time2.toMilliseconds(); }
bool beast::operator>= (const String & string1, const String & string2) noexcept
Case-sensitive comparison of two strings.
Definition at line 464 of file String.cpp.
 { return s1.compare (s2) >= 0; }
template<class T , class Tag > bool beast::operator>= (buffer_view< T, Tag > lhs, buffer_view< T, Tag > rhs) inline
Definition at line 479 of file buffer_view.h.
 {
     return ! (lhs < rhs);
 }
template<> bool beast::OutputStream::writeType< std::int32_t > (std::int32_t v)
Definition at line 366 of file OutputStream.cpp.
 { return writeInt32 (v); }
template<> bool beast::OutputStream::writeType< std::int64_t > (std::int64_t v)
Definition at line 369 of file OutputStream.cpp.
 { return writeInt64 (v); }
template<> bool beast::OutputStream::writeType< std::uint32_t > (std::uint32_t v)
Definition at line 378 of file OutputStream.cpp.
 { return writeInt32 (static_cast <std::int32_t> (v)); }
template<> bool beast::OutputStream::writeType< std::uint64_t > (std::uint64_t v)
Definition at line 381 of file OutputStream.cpp.
 { return writeInt64 (static_cast <std::int64_t> (v)); }
template<> bool beast::OutputStream::writeTypeBigEndian< std::int32_t > (std::int32_t v)
Definition at line 398 of file OutputStream.cpp.
 { return writeInt32BigEndian (v); }
template<> bool beast::OutputStream::writeTypeBigEndian< std::int64_t > (std::int64_t v)
Definition at line 401 of file OutputStream.cpp.
 { return writeInt64BigEndian (v); }
template<> bool beast::OutputStream::writeTypeBigEndian< std::uint32_t > (std::uint32_t v)
Definition at line 410 of file OutputStream.cpp.
 { return writeInt32BigEndian (static_cast <std::int32_t> (v)); }
template<> bool beast::OutputStream::writeTypeBigEndian< std::uint64_t > (std::uint64_t v)
Definition at line 413 of file OutputStream.cpp.
 { return writeInt64BigEndian (static_cast <std::int64_t> (v)); }
static StringArray beast::parseWildcards (const String & pattern) static
Definition at line 27 of file DirectoryIterator.cpp.
References beast::StringArray::addTokens(), beast::StringArray::removeEmptyStrings(), and beast::StringArray::trim().
 {
     StringArray s;
     s.addTokens (pattern, ";,", "\"'");
     s.trim();
     s.removeEmptyStrings();
     return s;
 }
template<class T > T beast::pi () inline noexcept
Definition at line 53 of file Math.h.
 {
     return 3.14159265358979;
 }
template<class T , class U > T beast::radiansToDegrees (U radians) inline
Definition at line 77 of file Math.h.
References T.
 {
     T deg = T (radians * U (57.29577951308238));
     if (deg < 0)
         deg += 360;
     return deg;
 }
static File beast::resolveXDGFolder (const char *const type, const char *const fallbackFolder) static
Definition at line 133 of file bsd_Files.cpp.
References ripple::f, beast::String::fromFirstOccurrenceOf(), beast::File::readLines(), beast::String::replace(), beast::StringArray::size(), beast::String::startsWith(), beast::String::trim(), and beast::String::unquoted().
Referenced by beast::File::getSpecialLocation().
 {
     StringArray confLines;
     File ("~/.config/user-dirs.dirs").readLines (confLines);
     for (int i = 0; i < confLines.size(); ++i)
     {
         const String line (confLines[i].trimStart());
         if (line.startsWith (type))
         {
             // eg. resolve XDG_MUSIC_DIR="$HOME/Music" to /home/user/Music
             const File f (line.replace ("$HOME", File ("~").getFullPathName())
                               .fromFirstOccurrenceOf ("=", false, false)
                               .trim().unquoted());
             if (f.isDirectory())
                 return f;
         }
     }
     return File (fallbackFolder);
 }
static File beast::resolveXDGFolder (const char *const type, const char *const fallbackFolder) static
Definition at line 133 of file linux_Files.cpp.
References ripple::f, beast::String::fromFirstOccurrenceOf(), beast::File::readLines(), beast::String::replace(), beast::StringArray::size(), beast::String::startsWith(), beast::String::trim(), and beast::String::unquoted().
 {
     StringArray confLines;
     File ("~/.config/user-dirs.dirs").readLines (confLines);
     for (int i = 0; i < confLines.size(); ++i)
     {
         const String line (confLines[i].trimStart());
         if (line.startsWith (type))
         {
             // eg. resolve XDG_MUSIC_DIR="$HOME/Music" to /home/user/Music
             const File f (line.replace ("$HOME", File ("~").getFullPathName())
                               .fromFirstOccurrenceOf ("=", false, false)
                               .trim().unquoted());
             if (f.isDirectory())
                 return f;
         }
     }
     return File (fallbackFolder);
 }
template<class CharT , class Traits , class Allocator > field_t<CharT, Traits, Allocator> beast::rfield (std::basic_string< CharT, Traits, Allocator > const & text, int width = 8, int pad = 0)
Definition at line 185 of file iosformat.h.
 {
     return field_t <CharT, Traits, Allocator> (
         text, width, pad, true);
 }
template<class CharT > field_t<CharT> beast::rfield (CharT const * text, int width = 8, int pad = 0)
Definition at line 194 of file iosformat.h.
 {
     return field_t <CharT, std::char_traits <CharT>,
         std::allocator <CharT>> (std::basic_string <CharT,
             std::char_traits <CharT>, std::allocator <CharT>> (text),
                 width, pad, true);
 }
template<typename T > field_t<char> beast::rfield (T const & t, int width = 8, int pad = 0)
Definition at line 204 of file iosformat.h.
References field(), and beast::detail::to_string().
 {
     std::string const text (detail::to_string (t));
     return field (text, width, pad, true);
 }
template<typename FloatType > int beast::roundToInt (const FloatType value) inline noexcept
Fast floating-point-to-integer conversion.
This is faster than using the normal c++ cast to convert a float to an int, and it will round the value to the nearest integer, rather than rounding it down like the normal cast does.
Note that this routine gets its speed at the expense of some accuracy, and when rounding values whose floating point component is exactly 0.5, odd numbers and even numbers will be rounded up or down differently.
Definition at line 243 of file Arithmetic.h.
References value.
Referenced by beast::SystemStats::getCpuSpeedInMegaherz().
 {
   #ifdef __INTEL_COMPILER
    #pragma float_control (precise, on, push)
   #endif
     union { int asInt[2]; double asDouble; } n;
     n.asDouble = ((double) value) + 6755399441055744.0;
    #if BEAST_BIG_ENDIAN
     return n.asInt [1];
    #else
     return n.asInt [0];
    #endif
 }
int beast::signum (adl_tester)
Definition at line 28 of file Zero.test.cpp.
 {
     return 0;
 }
template<typename T > int beast::signum (T const & t)
Default implementation of signum calls the method on the class.
Definition at line 58 of file Zero.h.
 {
     return t.signum();
 }
template<class ElementType , class ElementComparator > static void beast::sortArray (ElementComparator & comparator, ElementType *const array, int firstElement, int lastElement, const bool retainOrderOfEquivalentItems) static
Sorts a range of elements in an array.
The comparator object that is passed-in must define a public method with the following signature:
int compareElements (ElementType first, ElementType second);
..and this method must return:
a value of < 0 if the first comes before the second
a value of 0 if the two objects are equivalent
a value of > 0 if the second comes before the first
To improve performance, the compareElements() method can be declared as static or const.
Parameters
comparator an object which defines a compareElements() method
array the array to sort
firstElement the index of the first element of the range to be sorted
lastElement the index of the last element in the range that needs sorting (this is inclusive)
retainOrderOfEquivalentItems if true, the order of items that the comparator deems the same will be maintained - this will be a slower algorithm than if they are allowed to be moved around.
See Also
sortArrayRetainingOrder
Definition at line 80 of file ElementComparator.h.
Referenced by beast::Array< beast::String >::sort().
 {
     SortFunctionConverter<ElementComparator> converter (comparator);
     if (retainOrderOfEquivalentItems)
         std::stable_sort (array + firstElement, array + lastElement + 1, converter);
     else
         std::sort        (array + firstElement, array + lastElement + 1, converter);
 }
template<class T , class Tag > void beast::swap (buffer_view< T, Tag > & lhs, buffer_view< T, Tag > & rhs) inline noexcept
Definition at line 503 of file buffer_view.h.
References lhs, and beast::asio::swap().
Referenced by beast::buffer_view_test::testEmpty().
 {
     std::swap (lhs.m_base, rhs.m_base);
     std::swap (lhs.m_size, rhs.m_size);
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Compare , class Allocator > void beast::swap (detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator > & lhs, detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator > & rhs) noexcept
Definition at line 1894 of file aged_ordered_container.h.
References lhs.
 {
     lhs.swap (rhs);
 }
template<bool IsMulti, bool IsMap, class Key , class T , class Duration , class Hash , class KeyEqual , class Allocator > void beast::swap (detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator > & lhs, detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator > & rhs) noexcept
Definition at line 2452 of file aged_unordered_container.h.
References lhs.
 {
     lhs.swap (rhs);
 }
template<class IntegralType > IntegralType beast::swapBytes (IntegralType value) inline noexcept
Returns a type with the bytes swapped. Little endian becomes big endian and vice versa. The underlying type must be an integral type or behave like one.
Definition at line 250 of file ByteOrder.h.
References value.
Referenced by fromNetworkByteOrder(), toBigEndian(), and toLittleEndian().
 {
     return detail::SwapBytes <IntegralType> () (value);
 }
static void beast::swapUserAndEffectiveUser () static
Definition at line 65 of file bsd_Threads.cpp.
Referenced by beast::Process::lowerPrivilege(), and beast::Process::raisePrivilege().
 {
     (void) setreuid (geteuid(), getuid());
     (void) setregid (getegid(), getgid());
 }
static void beast::swapUserAndEffectiveUser () static
Definition at line 76 of file linux_Threads.cpp.
 {
     (void) setreuid (geteuid(), getuid());
     (void) setregid (getegid(), getgid());
 }
int beast::sysinfo (struct sysinfo * info)
Definition at line 97 of file bsd_SystemStats.cpp.
References GETSYSCTL, rocksdb::if(), NLOADS, O_RDONLY, PAGE_2_UNIT, R_ERROR, R_IGNORE, and UNIT_S.
{
         kvm_t *kvmh;
         double load_avg[NLOADS];
         int page_s = getpagesize();
         if (info == NULL)
                 R_ERROR(EFAULT);
         memset(info, 0, sizeof(struct sysinfo));
         info -> mem_unit = UNIT_S;
         /*kvm init*/
         if ((kvmh = kvm_open(NULL, "/dev/null", "/dev/null",
         O_RDONLY, "kvm_open")) == NULL)
                 R_ERROR(0);
         /*load averages*/
         if (kvm_getloadavg(kvmh, load_avg, NLOADS) == -1)
                 R_ERROR(0);
         info -> loads[0] = (u_long)((float)load_avg[0] * USHRT_MAX);
         info -> loads[1] = (u_long)((float)load_avg[1] * USHRT_MAX);
         info -> loads[2] = (u_long)((float)load_avg[2] * USHRT_MAX);
         /*swap space*/
         struct kvm_swap k_swap;
         if (kvm_getswapinfo(kvmh, &k_swap, 1, 0) == -1)
                 R_ERROR(0);
         info -> totalswap =
         (u_long)PAGE_2_UNIT(k_swap.ksw_total);
         info -> freeswap = info -> totalswap -
         (u_long)PAGE_2_UNIT(k_swap.ksw_used);
         /*processes*/
         int n_procs;
         if (kvm_getprocs(kvmh, KERN_PROC_ALL, 0, &n_procs) == NULL)
                 R_ERROR(0);
         info -> procs = (u_short)n_procs;
         /*end of kvm session*/
         if (kvm_close(kvmh) == -1)
                 R_ERROR(0);
         /*uptime*/
         struct timespec ts;
         if (clock_gettime(CLOCK_UPTIME, &ts) == -1)
                 R_ERROR(R_IGNORE);
         info -> uptime = (long)ts.tv_sec;
         /*ram*/
         int total_pages,
             free_pages,
             active_pages,
             inactive_pages;
         u_long shmmax;
         if (GETSYSCTL("vm.stats.vm.v_page_count", total_pages) == -1)
                 R_ERROR(R_IGNORE);
         if (GETSYSCTL("vm.stats.vm.v_free_count", free_pages) == -1)
                 R_ERROR(R_IGNORE);
         if (GETSYSCTL("vm.stats.vm.v_active_count", active_pages) == -1)
                 R_ERROR(R_IGNORE);
         if (GETSYSCTL("vm.stats.vm.v_inactive_count", inactive_pages) == -1)
                 R_ERROR(R_IGNORE);
         if (GETSYSCTL("kern.ipc.shmmax", shmmax) == -1)
                 R_ERROR(R_IGNORE);
         info -> totalram = (u_long)PAGE_2_UNIT(total_pages);
         info -> freeram = (u_long)PAGE_2_UNIT(free_pages);
         info -> bufferram = (u_long)PAGE_2_UNIT(active_pages);
         info -> sharedram = shmmax / UNIT_S;
         /*high mem (todo)*/
         info -> totalhigh = 0; /*Does this supose to refer to HMA or reserved ram?*/
         info -> freehigh = 0;
         return 0;
 }
void * beast::threadEntryProcBeast (void * userData)
Definition at line 476 of file Thread.cpp.
References BEAST_AUTORELEASEPOOL, and beast_threadEntryPoint().
Referenced by beast::Thread::launchThread().
 {
     BEAST_AUTORELEASEPOOL
     {
        #if BEAST_ANDROID
         struct AndroidThreadScope
         {
             AndroidThreadScope()   { threadLocalJNIEnvHolder.attach(); }
             ~AndroidThreadScope()  { threadLocalJNIEnvHolder.detach(); }
         };
         const AndroidThreadScope androidEnv;
        #endif
         beast_threadEntryPoint (userData);
     }
     return nullptr;
 }
template<typename IntegralType > IntegralType beast::toBigEndian (IntegralType value) inline noexcept
Returns the machine byte-order value to big-endian byte order.
Definition at line 268 of file ByteOrder.h.
References swapBytes(), and value.
Referenced by toNetworkByteOrder().
 {
 #if BEAST_LITTLE_ENDIAN
     return swapBytes (value);
 #else
     return value;
 #endif
 }
template<typename IntegralType > IntegralType beast::toLittleEndian (IntegralType value) inline noexcept
Returns the machine byte-order value to little-endian byte order.
Definition at line 257 of file ByteOrder.h.
References swapBytes(), and value.
 {
 #if BEAST_LITTLE_ENDIAN
     return value;
 #else
     return swapBytes (value);
 #endif
 }
template<typename IntegralType > IntegralType beast::toNetworkByteOrder (IntegralType value) inline noexcept
Returns the machine byte-order value to network byte order.
Definition at line 279 of file ByteOrder.h.
References toBigEndian(), and value.
Referenced by ripple::OverlayImpl::send().
 {
     return toBigEndian (value);
 }
static void beast::translateTimeField (String & result, int n, const char * singular, const char * plural) static
Definition at line 180 of file RelativeTime.cpp.
References TRANS.
Referenced by beast::RelativeTime::getDescription().
 {
     result << TRANS (String((n == 1) ? singular : plural))
                 .replace (n == 1 ? "1" : "2", String (n))
            << ' ';
 }
template<class T > T beast::twoPi () inline noexcept
Definition at line 59 of file Math.h.
 {
     return 6.28318530717958;
 }
template<typename T > std::string beast::type_name ()
Definition at line 43 of file type_name.h.
References name, and value.
 {
     typedef typename std::remove_reference<T>::type TR;
     std::unique_ptr<char, void(*)(void*)> own (
     #ifndef _MSC_VER
         abi::__cxa_demangle (typeid(TR).name(), nullptr,
             nullptr, nullptr),
     #else
             nullptr,
     #endif
             std::free
     );
     std::string r = own != nullptr ? own.get() : typeid(TR).name();
     if (std::is_const<TR>::value)
         r += " const";
     if (std::is_volatile<TR>::value)
         r += " volatile";
     if (std::is_lvalue_reference<T>::value)
         r += "&";
     else if (std::is_rvalue_reference<T>::value)
         r += "&&";
     return r;
 }
GUID beast::uuidFromString (const char *const s) inline noexcept
Definition at line 35 of file win32_ComSmartPtr.h.
 {
     unsigned long p0;
     unsigned int p1, p2, p3, p4, p5, p6, p7, p8, p9, p10;
   #ifndef _MSC_VER
     sscanf
   #else
     sscanf_s
   #endif
         (s, "%08lX-%04X-%04X-%02X%02X-%02X%02X%02X%02X%02X%02X",
               &p0, &p1, &p2, &p3, &p4, &p5, &p6, &p7, &p8, &p9, &p10);
     GUID g = { p0, (std::uint16_t) p1, (std::uint16_t) p2, { (std::uint8_t) p3, (std::uint8_t) p4, (std::uint8_t) p5, (std::uint8_t) p6,
                                                (std::uint8_t) p7, (std::uint8_t) p8, (std::uint8_t) p9, (std::uint8_t) p10 }};
     return g;
 }
void beast::zeromem (void * memory, size_t numBytes) inline noexcept
Fills a block of memory with zeros.
Definition at line 36 of file Memory.h.
Referenced by beast::HeapBlock< ElementType >::clear(), beast::StringEncodingConverter< CharPointerType_Src, CharPointerType_Dest >::convert(), beast::MemoryBlock::copyTo(), and beast::MemoryBlock::setSize().
     { memset (memory, 0, numBytes); }
template<typename Type > void beast::zerostruct (Type & structure) noexcept
Overwrites a structure or object with zeros.
Definition at line 41 of file Memory.h.
Referenced by beast::SystemStats::getStackBacktrace(), beast::File::getVolumeLabel(), isWindowsVersionOrLater(), and beast::TimeHelpers::millisToLocal().
     { memset (&structure, 0, sizeof (structure)); }
Variable Documentation
char const* const beast::base64EncodingTable = ".ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+" static
Definition at line 354 of file MemoryBlock.cpp.
Referenced by beast::MemoryBlock::fromBase64Encoding(), and beast::MemoryBlock::toBase64Encoding().
int beast::beast_argc = 0
Definition at line 158 of file bsd_Files.cpp.
Referenced by beast::File::getSpecialLocation().
const char *const * beast::beast_argv = nullptr
Definition at line 157 of file bsd_Files.cpp.
Referenced by beast::File::getSpecialLocation().
void* beast::currentModuleHandle = nullptr static
Definition at line 121 of file win32_Threads.cpp.
char beast::currentThreadHolderLock[sizeof(SpinLock)] static
Definition at line 68 of file Thread.cpp.
Referenced by getCurrentThreadHolder().
const beast_wchar beast::emptyChar = 0 static
Definition at line 1860 of file String.cpp.
Referenced by beast::StringEncodingConverter< CharPointerType_Src, CharPointerType_Dest >::convert().
SystemStats::CrashHandlerFunction beast::globalCrashHandler = nullptr static
Definition at line 129 of file SystemStats.cpp.
Referenced by handleCrash(), and beast::SystemStats::setApplicationCrashHandler().
const char beast::hexDigits[] = "0123456789abcdef" static
Definition at line 1731 of file String.cpp.
Referenced by beast::HexConverter< Type >::hexToString(), and beast::String::toHexString().
HiResCounterHandler beast::hiResCounterHandler static
Definition at line 277 of file win32_SystemStats.cpp.
Referenced by hiResCounterHandler().
int beast::lastProcessPriority = -1 static
Definition at line 77 of file win32_Threads.cpp.
Referenced by beast_repeatLastProcessPriority().
NewLine beast::newLine
A predefined object representing a new-line, which can be written to a string or stream.
To write a new-line to a stream, you can use the predefined 'newLine' variable like this:
myOutputStream << "Hello World" << newLine << newLine;
Definition at line 46 of file String.cpp.
Referenced by beast::FatalError::Reporter::formatMessage(), beast::SystemStats::getStackBacktrace(), beast::HTTPResponse::toString(), beast::HTTPRequest::toString(), beast::HTTPMessage::toString(), and beast::HTTPHeaders::toString().