rippled: beast::LockFreeStack< Element, Tag > Class Template Reference
beast::LockFreeStack< Element, Tag > Class Template Reference
#include <LockFreeStack.h>
Classes
class Node
Public Types
typedef Element value_type
typedef Element * pointer
typedef Element & reference
typedef Element const * const_pointer
typedef Element const & const_reference
typedef std::size_t size_type
typedef std::ptrdiff_t difference_type
typedef LockFreeStackIterator
< LockFreeStack< Element, Tag >
, false > iterator
typedef LockFreeStackIterator
< LockFreeStack< Element, Tag >
, true > const_iterator
Public Member Functions
LockFreeStack ()
bool empty () const
bool push_front (Node *node)
Element * pop_front ()
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
const_iterator cbegin () const
const_iterator cend () const
Private Attributes
Node m_end
Atomic< Node * > m_head
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
template<class Element, class Tag = void>
class beast::LockFreeStack< Element, Tag >
Multiple Producer, Multiple Consumer (MPMC) intrusive stack.
This stack is implemented using the same intrusive interface as List. All mutations are lock-free.
The caller is responsible for preventing the "ABA" problem: http://en.wikipedia.org/wiki/ABA_problem
Parameters
Tag A type name used to distinguish lists and nodes, for putting objects in multiple lists. If this parameter is omitted, the default tag is used.
Definition at line 145 of file LockFreeStack.h.
Member Typedef Documentation
template<class Element, class Tag = void> typedef LockFreeStackIterator< LockFreeStack <Element, Tag>, true> beast::LockFreeStack< Element, Tag >::const_iterator
Definition at line 179 of file LockFreeStack.h.
template<class Element, class Tag = void> typedef Element const* beast::LockFreeStack< Element, Tag >::const_pointer
Definition at line 172 of file LockFreeStack.h.
template<class Element, class Tag = void> typedef Element const& beast::LockFreeStack< Element, Tag >::const_reference
Definition at line 173 of file LockFreeStack.h.
template<class Element, class Tag = void> typedef std::ptrdiff_t beast::LockFreeStack< Element, Tag >::difference_type
Definition at line 175 of file LockFreeStack.h.
template<class Element, class Tag = void> typedef LockFreeStackIterator< LockFreeStack <Element, Tag>, false> beast::LockFreeStack< Element, Tag >::iterator
Definition at line 177 of file LockFreeStack.h.
template<class Element, class Tag = void> typedef Element* beast::LockFreeStack< Element, Tag >::pointer
Definition at line 170 of file LockFreeStack.h.
template<class Element, class Tag = void> typedef Element& beast::LockFreeStack< Element, Tag >::reference
Definition at line 171 of file LockFreeStack.h.
template<class Element, class Tag = void> typedef std::size_t beast::LockFreeStack< Element, Tag >::size_type
Definition at line 174 of file LockFreeStack.h.
template<class Element, class Tag = void> typedef Element beast::LockFreeStack< Element, Tag >::value_type
Definition at line 169 of file LockFreeStack.h.
Constructor & Destructor Documentation
template<class Element, class Tag = void> beast::LockFreeStack< Element, Tag >::LockFreeStack () inline
Definition at line 181 of file LockFreeStack.h.
         : m_end (nullptr)
         , m_head (&m_end)
     {
     }
Member Function Documentation
template<class Element, class Tag = void> iterator beast::LockFreeStack< Element, Tag >::begin () inline
Return a forward iterator to the beginning or end of the stack. Undefined behavior results if push_front or pop_front is called while an iteration is in progress. Thread safety: Caller is responsible for synchronization.
Definition at line 250 of file LockFreeStack.h.
     {
         return iterator (m_head.get ());
     }
template<class Element, class Tag = void> const_iterator beast::LockFreeStack< Element, Tag >::begin () const inline
Definition at line 260 of file LockFreeStack.h.
     {
         return const_iterator (m_head.get ());
     }
template<class Element, class Tag = void> const_iterator beast::LockFreeStack< Element, Tag >::cbegin () const inline
Definition at line 270 of file LockFreeStack.h.
Referenced by beast::Stoppable::prepareRecursive(), beast::Stoppable::startRecursive(), beast::Stoppable::stopAsyncRecursive(), and beast::Stoppable::stopRecursive().
     {
         return const_iterator (m_head.get ());
     }
template<class Element, class Tag = void> const_iterator beast::LockFreeStack< Element, Tag >::cend () const inline
Definition at line 275 of file LockFreeStack.h.
Referenced by beast::Stoppable::prepareRecursive(), beast::Stoppable::startRecursive(), beast::Stoppable::stopAsyncRecursive(), and beast::Stoppable::stopRecursive().
     {
         return const_iterator (&m_end);
     }
template<class Element, class Tag = void> bool beast::LockFreeStack< Element, Tag >::empty () const inline
Returns true if the stack is empty.
Definition at line 188 of file LockFreeStack.h.
     {
         return m_head.get() == &m_end;
     }
template<class Element, class Tag = void> iterator beast::LockFreeStack< Element, Tag >::end () inline
Definition at line 255 of file LockFreeStack.h.
     {
         return iterator (&m_end);
     }
template<class Element, class Tag = void> const_iterator beast::LockFreeStack< Element, Tag >::end () const inline
Definition at line 265 of file LockFreeStack.h.
     {
         return const_iterator (&m_end);
     }
template<class Element, class Tag = void> Element* beast::LockFreeStack< Element, Tag >::pop_front () inline
Pop an element off the stack. The caller is responsible for preventing the ABA problem. This operation is lock-free. Thread safety: Safe to call from any thread.
Returns
The element that was popped, or nullptr if the stack was empty.
Definition at line 228 of file LockFreeStack.h.
Referenced by beast::Workers::deleteWorkers().
     {
         Node* node;
         Node* head;
         do
         {
             node = m_head.get ();
             if (node == &m_end)
                 return nullptr;
             head = node->m_next.get ();
         }
         while (!m_head.compareAndSetBool (head, node));
         return static_cast <Element*> (node);
     }
template<class Element, class Tag = void> bool beast::LockFreeStack< Element, Tag >::push_front (Node * node) inline
Push a node onto the stack. The caller is responsible for preventing the ABA problem. This operation is lock-free. Thread safety: Safe to call from any thread.
Parameters
node The node to push.
Returns
true if the stack was previously empty. If multiple threads are attempting to push, only one will receive true.
Definition at line 205 of file LockFreeStack.h.
Referenced by beast::Stoppable::Stoppable().
     {
         bool first;
         Node* head;
         do
         {
             head = m_head.get ();
             first = head == &m_end;
             node->m_next = head;
         }
         while (!m_head.compareAndSetBool (node, head));
         return first;
     }
Member Data Documentation
template<class Element, class Tag = void> Node beast::LockFreeStack< Element, Tag >::m_end private
Definition at line 282 of file LockFreeStack.h.
Referenced by beast::LockFreeStack< beast::Workers::Worker >::cend(), beast::LockFreeStack< beast::Workers::Worker >::empty(), beast::LockFreeStack< beast::Workers::Worker >::end(), beast::LockFreeStack< beast::Workers::Worker >::pop_front(), and beast::LockFreeStack< beast::Workers::Worker >::push_front().
template<class Element, class Tag = void> Atomic<Node*> beast::LockFreeStack< Element, Tag >::m_head private
Definition at line 283 of file LockFreeStack.h.
Referenced by beast::LockFreeStack< beast::Workers::Worker >::begin(), beast::LockFreeStack< beast::Workers::Worker >::cbegin(), beast::LockFreeStack< beast::Workers::Worker >::empty(), beast::LockFreeStack< beast::Workers::Worker >::pop_front(), and beast::LockFreeStack< beast::Workers::Worker >::push_front().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/intrusive/LockFreeStack.h