rippled: ripple::SField Class Reference
ripple::SField Class Reference
#include <FieldNames.h>
Public Types
typedef const SField & ref
typedef SField const * ptr
Public Member Functions
SField (int fc, SerializedTypeID tid, int fv, const char *fn)
SField (SerializedTypeID tid, int fv, const char *fn)
SField (int fc)
~SField ()
std::string getName () const
bool hasName () const
bool isGeneric () const
bool isInvalid () const
bool isUseful () const
bool isKnown () const
bool isBinary () const
bool isDiscardable () const
int getCode () const
int getNum () const
bool isSigningField () const
void notSigningField ()
bool shouldMeta (int c) const
void setMeta (int c)
bool shouldInclude (bool withSigningField) const
bool operator== (const SField &f) const
bool operator!= (const SField &f) const
Static Public Member Functions
static SField::ref getField (int fieldCode)
static SField::ref getField (const std::string &fieldName)
static SField::ref getField (int type, int value)
static SField::ref getField (SerializedTypeID type, int value)
static int getNumFields ()
static int compare (SField::ref f1, SField::ref f2)
Public Attributes
const int fieldCode
const SerializedTypeID fieldType
const int fieldValue
std::string fieldName
int fieldMeta
int fieldNum
bool signingField
Static Public Attributes
static const int sMD_Never = 0x00
static const int sMD_ChangeOrig = 0x01
static const int sMD_ChangeNew = 0x02
static const int sMD_DeleteFinal = 0x04
static const int sMD_Create = 0x08
static const int sMD_Always = 0x10
static const int sMD_Default = sMD_ChangeOrig | sMD_ChangeNew | sMD_DeleteFinal | sMD_Create
Protected Types
typedef RippleMutex StaticLockType
typedef std::lock_guard
< StaticLockType > StaticScopedLockType
Protected Member Functions
SField (SerializedTypeID id, int val)
Static Protected Member Functions
static StaticLockType & getMutex ()
Static Protected Attributes
static std::map< int, ptr > codeToField
static int num = 0
Detailed Description
Identifies fields.
Fields are necessary to tag data in signed transactions so that the binary format of the transaction can be canonicalized.
Definition at line 53 of file FieldNames.h.
Member Typedef Documentation
typedef SField const* ripple::SField::ptr
Definition at line 57 of file FieldNames.h.
typedef const SField& ripple::SField::ref
Definition at line 56 of file FieldNames.h.
typedef RippleMutex ripple::SField::StaticLockType protected
Definition at line 215 of file FieldNames.h.
typedef std::lock_guard<StaticLockType> ripple::SField::StaticScopedLockType protected
Definition at line 216 of file FieldNames.h.
Constructor & Destructor Documentation
ripple::SField::SField (int fc, SerializedTypeID tid, int fv, const char * fn) inline
Definition at line 77 of file FieldNames.h.
References codeToField, fieldCode, fieldNum, getMutex(), and num.
         : fieldCode (fc)
         , fieldType (tid)
         , fieldValue (fv)
         , fieldName (fn)
         , fieldMeta (sMD_Default)
         , signingField (true)
     {
         StaticScopedLockType sl (getMutex ());
         codeToField[fieldCode] = this;
         fieldNum = ++num;
     }
ripple::SField::SField (SerializedTypeID tid, int fv, const char * fn) inline
Definition at line 92 of file FieldNames.h.
References codeToField, fieldCode, fieldNum, getMutex(), and num.
         : fieldCode (FIELD_CODE (tid, fv))
         , fieldType (tid)
         , fieldValue (fv)
         , fieldName (fn)
         , fieldMeta (sMD_Default)
         , signingField (true)
     {
         StaticScopedLockType sl (getMutex ());
         codeToField[fieldCode] = this;
         fieldNum = ++num;
     }
ripple::SField::SField (int fc) inline explicit
Definition at line 107 of file FieldNames.h.
References fieldNum, getMutex(), and num.
         : fieldCode (fc)
         , fieldType (STI_UNKNOWN)
         , fieldValue (0)
         , fieldMeta (sMD_Never)
         , signingField (true)
     {
         StaticScopedLockType sl (getMutex ());
         fieldNum = ++num;
     }
ripple::SField::~SField ()
Definition at line 151 of file FieldNames.cpp.
 {
     StaticScopedLockType sl (getMutex ());
     std::map<int, ptr>::iterator it = codeToField.find (fieldCode);
     if ((it != codeToField.end ()) && (it->second == this))
         codeToField.erase (it);
 }
ripple::SField::SField (SerializedTypeID id, int val) protected
Definition at line 229 of file FieldNames.cpp.
Member Function Documentation
int ripple::SField::compare (SField::ref f1, SField::ref f2) static
Definition at line 111 of file FieldNames.cpp.
References fieldCode.
 {
     // -1 = f1 comes before f2, 0 = illegal combination, 1 = f1 comes after f2
     if ((f1.fieldCode <= 0) || (f2.fieldCode <= 0))
         return 0;
     if (f1.fieldCode < f2.fieldCode)
         return -1;
     if (f2.fieldCode < f1.fieldCode)
         return 1;
     return 0;
 }
int ripple::SField::getCode () const inline
Definition at line 164 of file FieldNames.h.
References fieldCode.
     {
         return fieldCode;
     }
SField::ref ripple::SField::getField (int fieldCode) static
Definition at line 239 of file FieldNames.cpp.
Referenced by ripple::STArray::construct(), getField(), ripple::STParsedJSON::parse(), and ripple::STObject::set().
SField::ref ripple::SField::getField (const std::string & fieldName) static
Definition at line 138 of file FieldNames.cpp.
References ripple::sfInvalid.
 {
     // OPTIMIZEME me with a map. CHECKME this is case sensitive
     StaticScopedLockType sl (getMutex ());
     typedef std::map<int, SField::ptr>::value_type int_sfref_pair;
     BOOST_FOREACH (const int_sfref_pair & fieldPair, codeToField)
     {
         if (fieldPair.second->fieldName == fieldName)
             return * (fieldPair.second);
     }
     return sfInvalid;
 }
static SField::ref ripple::SField::getField (int type, int value) inline static
Definition at line 122 of file FieldNames.h.
References FIELD_CODE, and getField().
     {
         return getField (FIELD_CODE (type, value));
     }
static SField::ref ripple::SField::getField (SerializedTypeID type, int value) inline static
Definition at line 126 of file FieldNames.h.
References FIELD_CODE, and getField().
     {
         return getField (FIELD_CODE (type, value));
     }
SField::StaticLockType & ripple::SField::getMutex () static protected
Definition at line 28 of file FieldNames.cpp.
Referenced by SField().
 {
     static StaticLockType mutex;
     return mutex;
 }
std::string ripple::SField::getName () const
Definition at line 126 of file FieldNames.cpp.
Referenced by ripple::STObject::operator==(), and ripple::STObject::setType().
 {
     if (!fieldName.empty ())
         return fieldName;
     if (fieldValue == 0)
         return "";
     return beast::lexicalCastThrow <std::string> (static_cast<int> (fieldType)) + "/" +
            beast::lexicalCastThrow <std::string> (fieldValue);
 }
int ripple::SField::getNum () const inline
Definition at line 168 of file FieldNames.h.
References fieldNum.
Referenced by ripple::SOTemplate::getIndex(), and ripple::SOTemplate::push_back().
     {
         return fieldNum;
     }
static int ripple::SField::getNumFields () inline static
Definition at line 172 of file FieldNames.h.
References num.
Referenced by ripple::SOTemplate::push_back().
     {
         return num;
     }
bool ripple::SField::hasName () const inline
Definition at line 132 of file FieldNames.h.
References fieldName.
Referenced by ripple::STObject::getJson().
     {
         return !fieldName.empty ();
     }
bool ripple::SField::isBinary () const inline
Definition at line 153 of file FieldNames.h.
References fieldValue.
Referenced by ripple::STObject::operator==().
     {
         return fieldValue < 256;
     }
bool ripple::SField::isDiscardable () const inline
Definition at line 159 of file FieldNames.h.
References fieldValue.
Referenced by ripple::STObject::setType().
     {
         return fieldValue > 256;
     }
bool ripple::SField::isGeneric () const inline
Definition at line 137 of file FieldNames.h.
References fieldCode.
     {
         return fieldCode == 0;
     }
bool ripple::SField::isInvalid () const inline
Definition at line 141 of file FieldNames.h.
References fieldCode.
Referenced by ripple::STArray::construct(), and ripple::STObject::set().
     {
         return fieldCode == -1;
     }
bool ripple::SField::isKnown () const inline
Definition at line 149 of file FieldNames.h.
References fieldType, and ripple::STI_UNKNOWN.
     {
         return fieldType != STI_UNKNOWN;
     }
bool ripple::SField::isSigningField () const inline
Definition at line 177 of file FieldNames.h.
References signingField.
     {
         return signingField;
     }
bool ripple::SField::isUseful () const inline
Definition at line 145 of file FieldNames.h.
References fieldCode.
Referenced by ripple::SerializedObject_test::testSerialization().
     {
         return fieldCode > 0;
     }
void ripple::SField::notSigningField () inline
Definition at line 181 of file FieldNames.h.
References signingField.
     {
         signingField = false;
     }
bool ripple::SField::operator!= (const SField & f) const inline
Definition at line 204 of file FieldNames.h.
References fieldCode.
     {
         return fieldCode != f.fieldCode;
     }
bool ripple::SField::operator== (const SField & f) const inline
Definition at line 199 of file FieldNames.h.
References fieldCode.
     {
         return fieldCode == f.fieldCode;
     }
void ripple::SField::setMeta (int c) inline
Definition at line 189 of file FieldNames.h.
References fieldMeta.
     {
         fieldMeta = c;
     }
bool ripple::SField::shouldInclude (bool withSigningField) const inline
Definition at line 194 of file FieldNames.h.
References fieldValue, and signingField.
Referenced by ripple::STObject::add().
     {
         return (fieldValue < 256) && (withSigningField || signingField);
     }
bool ripple::SField::shouldMeta (int c) const inline
Definition at line 185 of file FieldNames.h.
References fieldMeta.
Referenced by ripple::LedgerEntrySet::calcRawMeta().
     {
         return (fieldMeta & c) != 0;
     }
Member Data Documentation
std::map< int, SField::ptr > ripple::SField::codeToField static protected
Definition at line 213 of file FieldNames.h.
Referenced by SField().
const int ripple::SField::fieldCode
Definition at line 69 of file FieldNames.h.
Referenced by ripple::STObject::add(), compare(), getCode(), isGeneric(), isInvalid(), isUseful(), operator!=(), operator==(), and SField().
int ripple::SField::fieldMeta
Definition at line 73 of file FieldNames.h.
Referenced by setMeta(), and shouldMeta().
std::string ripple::SField::fieldName
Definition at line 72 of file FieldNames.h.
Referenced by hasName().
int ripple::SField::fieldNum
Definition at line 74 of file FieldNames.h.
Referenced by getNum(), and SField().
const SerializedTypeID ripple::SField::fieldType
Definition at line 70 of file FieldNames.h.
Referenced by isKnown(), ripple::STObject::makeDefaultObject(), ripple::STParsedJSON::parse(), and ripple::STObject::set().
const int ripple::SField::fieldValue
Definition at line 71 of file FieldNames.h.
Referenced by isBinary(), isDiscardable(), and shouldInclude().
int ripple::SField::num = 0 static protected
Definition at line 221 of file FieldNames.h.
Referenced by getNumFields(), and SField().
bool ripple::SField::signingField
Definition at line 75 of file FieldNames.h.
Referenced by isSigningField(), notSigningField(), and shouldInclude().
const int ripple::SField::sMD_Always = 0x10 static
Definition at line 64 of file FieldNames.h.
Referenced by ripple::LedgerEntrySet::calcRawMeta().
const int ripple::SField::sMD_ChangeNew = 0x02 static
Definition at line 61 of file FieldNames.h.
Referenced by ripple::LedgerEntrySet::calcRawMeta().
const int ripple::SField::sMD_ChangeOrig = 0x01 static
Definition at line 60 of file FieldNames.h.
Referenced by ripple::LedgerEntrySet::calcRawMeta().
const int ripple::SField::sMD_Create = 0x08 static
Definition at line 63 of file FieldNames.h.
Referenced by ripple::LedgerEntrySet::calcRawMeta().
const int ripple::SField::sMD_Default = sMD_ChangeOrig | sMD_ChangeNew | sMD_DeleteFinal | sMD_Create static
Definition at line 65 of file FieldNames.h.
const int ripple::SField::sMD_DeleteFinal = 0x04 static
Definition at line 62 of file FieldNames.h.
Referenced by ripple::LedgerEntrySet::calcRawMeta().
const int ripple::SField::sMD_Never = 0x00 static
Definition at line 59 of file FieldNames.h.
The documentation for this class was generated from the following files:
rippled/src/ripple_data/protocol/FieldNames.h
rippled/src/ripple_data/protocol/FieldNames.cpp
rippled/src/ripple_data/protocol/SerializeDeclarations.h