rippled: TestOverlay::ConnectionType< Config > Class Template Reference
TestOverlay::ConnectionType< Config > Class Template Reference
#include <ConnectionType.h>
Classes
class Any
class IsNotPeer
class IsPeer
Public Types
typedef Config::Peer Peer
typedef Config::Message Message
typedef Config::State State
typedef State::UniqueID UniqueID
typedef std::vector< Message > Messages
typedef boost::unordered_set
< UniqueID > MessageTable
Public Member Functions
ConnectionType ()
ConnectionType (Peer &peer, bool inbound)
ConnectionType (ConnectionType const &other)
ConnectionType & operator= (ConnectionType const &other)
bool empty () const
bool inbound () const
Peer & peer ()
Peer const & peer () const
Messages & messages ()
Messages const & messages () const
Messages & pending ()
Messages const & pending () const
Private Attributes
Peer * m_peer
bool m_inbound
Messages m_messages
Messages m_pending
Detailed Description
template<class Config>
class TestOverlay::ConnectionType< Config >
A connection between two nodes.
Definition at line 28 of file ConnectionType.h.
Member Typedef Documentation
template<class Config > typedef Config::Message TestOverlay::ConnectionType< Config >::Message
Definition at line 32 of file ConnectionType.h.
template<class Config > typedef std::vector<Message> TestOverlay::ConnectionType< Config >::Messages
Definition at line 36 of file ConnectionType.h.
template<class Config > typedef boost::unordered_set<UniqueID> TestOverlay::ConnectionType< Config >::MessageTable
Definition at line 37 of file ConnectionType.h.
template<class Config > typedef Config::Peer TestOverlay::ConnectionType< Config >::Peer
Definition at line 31 of file ConnectionType.h.
template<class Config > typedef Config::State TestOverlay::ConnectionType< Config >::State
Definition at line 33 of file ConnectionType.h.
template<class Config > typedef State::UniqueID TestOverlay::ConnectionType< Config >::UniqueID
Definition at line 34 of file ConnectionType.h.
Constructor & Destructor Documentation
template<class Config > TestOverlay::ConnectionType< Config >::ConnectionType () inline
Create the 'no connection' object.
Definition at line 40 of file ConnectionType.h.
         : m_peer (nullptr)
     {
     }
template<class Config > TestOverlay::ConnectionType< Config >::ConnectionType (Peer & peer, bool inbound) inline
Definition at line 45 of file ConnectionType.h.
         : m_peer (&peer)
         , m_inbound (inbound)
     {
     }
template<class Config > TestOverlay::ConnectionType< Config >::ConnectionType (ConnectionType< Config > const & other) inline
Definition at line 51 of file ConnectionType.h.
         : m_peer (other.m_peer)
         , m_inbound (other.m_inbound)
     {
     }
Member Function Documentation
template<class Config > bool TestOverlay::ConnectionType< Config >::empty () const inline
Returns true if there is no connection.
Definition at line 65 of file ConnectionType.h.
References TestOverlay::ConnectionType< Config >::m_peer.
     {
         return m_peer == nullptr;
     }
template<class Config > bool TestOverlay::ConnectionType< Config >::inbound () const inline
Returns true if this is an inbound connection. If there is no connection, the return value is undefined.
Definition at line 73 of file ConnectionType.h.
References TestOverlay::ConnectionType< Config >::m_inbound.
     {
         return m_inbound;
     }
template<class Config > Messages& TestOverlay::ConnectionType< Config >::messages () inline
Returns a container with the current step's incoming messages.
Definition at line 95 of file ConnectionType.h.
References TestOverlay::ConnectionType< Config >::m_messages.
Referenced by TestOverlay::PeerType< Config >::post_step(), and TestOverlay::PeerType< Config >::step().
     {
         return m_messages;
     }
template<class Config > Messages const& TestOverlay::ConnectionType< Config >::messages () const inline
Definition at line 100 of file ConnectionType.h.
References TestOverlay::ConnectionType< Config >::m_messages.
     {
         return m_messages;
     }
template<class Config > ConnectionType& TestOverlay::ConnectionType< Config >::operator= (ConnectionType< Config > const & other) inline
Definition at line 57 of file ConnectionType.h.
References TestOverlay::ConnectionType< Config >::m_inbound, and TestOverlay::ConnectionType< Config >::m_peer.
     {
         m_peer = other.m_peer;
         m_inbound = other.m_inbound;
         return *this;
     }
template<class Config > Peer& TestOverlay::ConnectionType< Config >::peer () inline
Returns the peer on the other end. If there is no connection, the return value is undefined.
Definition at line 82 of file ConnectionType.h.
References TestOverlay::ConnectionType< Config >::m_peer.
Referenced by TestOverlay::ConnectionType< Config >::IsPeer::operator()(), and TestOverlay::ConnectionType< Config >::IsNotPeer::operator()().
     {
         return *m_peer;
     }
template<class Config > Peer const& TestOverlay::ConnectionType< Config >::peer () const inline
Definition at line 87 of file ConnectionType.h.
References TestOverlay::ConnectionType< Config >::m_peer.
     {
         return *m_peer;
     }
template<class Config > Messages& TestOverlay::ConnectionType< Config >::pending () inline
Returns a container with the next step's incoming messages. During each step, peers process the current step's message list, but post new messages to the pending messages list. This way, new messages will always process in the next step and not the current one.
Definition at line 113 of file ConnectionType.h.
References TestOverlay::ConnectionType< Config >::m_pending.
Referenced by TestOverlay::PeerType< Config >::post_step().
     {
         return m_pending;
     }
template<class Config > Messages const& TestOverlay::ConnectionType< Config >::pending () const inline
Definition at line 118 of file ConnectionType.h.
References TestOverlay::ConnectionType< Config >::m_pending.
     {
         return m_pending;
     }
Member Data Documentation
template<class Config > bool TestOverlay::ConnectionType< Config >::m_inbound private
Definition at line 181 of file ConnectionType.h.
Referenced by TestOverlay::ConnectionType< Config >::inbound(), and TestOverlay::ConnectionType< Config >::operator=().
template<class Config > Messages TestOverlay::ConnectionType< Config >::m_messages private
Definition at line 182 of file ConnectionType.h.
Referenced by TestOverlay::ConnectionType< Config >::messages().
template<class Config > Peer* TestOverlay::ConnectionType< Config >::m_peer private
Definition at line 180 of file ConnectionType.h.
Referenced by TestOverlay::ConnectionType< Config >::empty(), TestOverlay::ConnectionType< Config >::operator=(), and TestOverlay::ConnectionType< Config >::peer().
template<class Config > Messages TestOverlay::ConnectionType< Config >::m_pending private
Definition at line 183 of file ConnectionType.h.
Referenced by TestOverlay::ConnectionType< Config >::pending().
The documentation for this class was generated from the following file:
rippled/src/ripple/testoverlay/api/ConnectionType.h