rippled: ripple::CollectorManagerImp Class Reference
ripple::CollectorManagerImp Class Reference
Public Member Functions
CollectorManagerImp (beast::StringPairArray const &params, beast::Journal journal)
~CollectorManagerImp ()
beast::insight::Collector::ptr
const & collector ()
beast::insight::Group::ptr const & group (std::string const &name)
Public Member Functions inherited from ripple::CollectorManager
virtual ~CollectorManager ()=0
Public Attributes
beast::Journal m_journal
beast::insight::Collector::ptr m_collector
std::unique_ptr
< beast::insight::Groups > m_groups
Additional Inherited Members
Static Public Member Functions inherited from ripple::CollectorManager
static CollectorManager * New (beast::StringPairArray const &params, beast::Journal journal)
Detailed Description
Definition at line 22 of file CollectorManager.cpp.
Constructor & Destructor Documentation
ripple::CollectorManagerImp::CollectorManagerImp (beast::StringPairArray const & params, beast::Journal journal) inline
Definition at line 30 of file CollectorManager.cpp.
References beast::IP::Endpoint::from_string(), m_collector, m_groups, beast::insight::make_Groups(), beast::insight::NullCollector::New(), beast::insight::StatsDCollector::New(), and std::chrono::prefix.
         : m_journal (journal)
     {
         std::string const& server (params ["server"].toStdString());
         if (server == "statsd")
         {
             beast::IP::Endpoint const address (beast::IP::Endpoint::from_string (
                 params ["address"].toStdString ()));
             std::string const& prefix (params ["prefix"].toStdString ());
             m_collector = beast::insight::StatsDCollector::New (address, prefix, journal);
         }
         else
         {
             m_collector = beast::insight::NullCollector::New ();
         }
         m_groups = beast::insight::make_Groups (m_collector);
     }
ripple::CollectorManagerImp::~CollectorManagerImp () inline
Definition at line 52 of file CollectorManager.cpp.
     {
     }
Member Function Documentation
beast::insight::Collector::ptr const& ripple::CollectorManagerImp::collector () inline virtual
Implements ripple::CollectorManager.
Definition at line 56 of file CollectorManager.cpp.
References m_collector.
     {
         return m_collector;
     }
beast::insight::Group::ptr const& ripple::CollectorManagerImp::group (std::string const & name) inline virtual
Implements ripple::CollectorManager.
Definition at line 61 of file CollectorManager.cpp.
References m_groups.
     {
         return m_groups->get (name);
     }
Member Data Documentation
beast::insight::Collector::ptr ripple::CollectorManagerImp::m_collector
Definition at line 27 of file CollectorManager.cpp.
Referenced by collector(), and CollectorManagerImp().
std::unique_ptr<beast::insight::Groups> ripple::CollectorManagerImp::m_groups
Definition at line 28 of file CollectorManager.cpp.
Referenced by CollectorManagerImp(), and group().
beast::Journal ripple::CollectorManagerImp::m_journal
Definition at line 26 of file CollectorManager.cpp.
The documentation for this class was generated from the following file:
rippled/src/ripple_app/main/CollectorManager.cpp