rippled: ripple::AgedHistory< Container > Class Template Reference
ripple::AgedHistory< Container > Class Template Reference
#include <AgedHistory.h>
Public Types
typedef Container container_type
Public Member Functions
AgedHistory ()
AgedHistory (AgedHistory const &other)
AgedHistory & operator= (AgedHistory const &other)
void swap ()
Container * operator-> ()
Container const * operator-> () const
Container & front ()
Container const & front () const
Container & back ()
Container const & back () const
Private Attributes
Container m_c1
Container m_c2
Container * m_p1
Container * m_p2
Detailed Description
template<class Container>
class ripple::AgedHistory< Container >
Definition at line 27 of file AgedHistory.h.
Member Typedef Documentation
template<class Container > typedef Container ripple::AgedHistory< Container >::container_type
Definition at line 30 of file AgedHistory.h.
Constructor & Destructor Documentation
template<class Container > ripple::AgedHistory< Container >::AgedHistory () inline
Definition at line 32 of file AgedHistory.h.
         : m_p1 (&m_c1)
         , m_p2 (&m_c2)
     {
     }
template<class Container > ripple::AgedHistory< Container >::AgedHistory (AgedHistory< Container > const & other) inline
Definition at line 38 of file AgedHistory.h.
         : m_c1 (other.front())
         , m_c2 (other.back())
         , m_p1 (&m_c1)
         , m_p2 (&m_c2)
     {
     }
Member Function Documentation
template<class Container > Container& ripple::AgedHistory< Container >::back () inline
Definition at line 62 of file AgedHistory.h.
References ripple::AgedHistory< Container >::m_p2.
Referenced by ripple::AgedHistory< Container >::operator=().
 { return *m_p2; }
template<class Container > Container const& ripple::AgedHistory< Container >::back () const inline
Definition at line 63 of file AgedHistory.h.
References ripple::AgedHistory< Container >::m_p2.
 { return *m_p2; }
template<class Container > Container& ripple::AgedHistory< Container >::front () inline
Definition at line 60 of file AgedHistory.h.
References ripple::AgedHistory< Container >::m_p1.
Referenced by ripple::AgedHistory< Container >::operator=().
 { return *m_p1; }
template<class Container > Container const& ripple::AgedHistory< Container >::front () const inline
Definition at line 61 of file AgedHistory.h.
References ripple::AgedHistory< Container >::m_p1.
 { return *m_p1; }
template<class Container > Container* ripple::AgedHistory< Container >::operator-> () inline
Definition at line 57 of file AgedHistory.h.
References ripple::AgedHistory< Container >::m_p1.
 { return m_p1; }
template<class Container > Container const* ripple::AgedHistory< Container >::operator-> () const inline
Definition at line 58 of file AgedHistory.h.
References ripple::AgedHistory< Container >::m_p1.
 { return m_p1; }
template<class Container > AgedHistory& ripple::AgedHistory< Container >::operator= (AgedHistory< Container > const & other) inline
Definition at line 46 of file AgedHistory.h.
References ripple::AgedHistory< Container >::back(), ripple::AgedHistory< Container >::front(), ripple::AgedHistory< Container >::m_c1, ripple::AgedHistory< Container >::m_c2, ripple::AgedHistory< Container >::m_p1, and ripple::AgedHistory< Container >::m_p2.
     {
         m_c1 = other.front();
         m_c2 = other.back();
         m_p1 = &m_c1;
         m_p2 = &m_c2;
         return *this;
     }
template<class Container > void ripple::AgedHistory< Container >::swap () inline
Definition at line 55 of file AgedHistory.h.
References ripple::AgedHistory< Container >::m_p1, ripple::AgedHistory< Container >::m_p2, and beast::asio::swap().
 { std::swap (m_p1, m_p2); }
Member Data Documentation
template<class Container > Container ripple::AgedHistory< Container >::m_c1 private
Definition at line 66 of file AgedHistory.h.
Referenced by ripple::AgedHistory< Container >::operator=().
template<class Container > Container ripple::AgedHistory< Container >::m_c2 private
Definition at line 67 of file AgedHistory.h.
Referenced by ripple::AgedHistory< Container >::operator=().
template<class Container > Container* ripple::AgedHistory< Container >::m_p1 private
Definition at line 68 of file AgedHistory.h.
Referenced by ripple::AgedHistory< Container >::front(), ripple::AgedHistory< Container >::operator->(), ripple::AgedHistory< Container >::operator=(), and ripple::AgedHistory< Container >::swap().
template<class Container > Container* ripple::AgedHistory< Container >::m_p2 private
Definition at line 69 of file AgedHistory.h.
Referenced by ripple::AgedHistory< Container >::back(), ripple::AgedHistory< Container >::operator=(), and ripple::AgedHistory< Container >::swap().
The documentation for this class was generated from the following file:
rippled/src/ripple/types/api/AgedHistory.h