rippled: rocksdb::TtlCompactionFilter Class Reference
rocksdb::TtlCompactionFilter Class Reference
#include <db_ttl.h>
Public Member Functions
TtlCompactionFilter (int32_t ttl, const CompactionFilter *user_comp_filter, std::unique_ptr< const CompactionFilter > user_comp_filter_from_factory=nullptr)
virtual bool Filter (int level, const Slice &key, const Slice &old_val, std::string *new_val, bool *value_changed) const override
virtual const char * Name () const override
Public Member Functions inherited from rocksdb::CompactionFilter
virtual ~CompactionFilter ()
Private Attributes
int32_t ttl_
const CompactionFilter * user_comp_filter_
std::unique_ptr< const
CompactionFilter > user_comp_filter_from_factory_
Detailed Description
Definition at line 177 of file db_ttl.h.
Constructor & Destructor Documentation
rocksdb::TtlCompactionFilter::TtlCompactionFilter (int32_t ttl, const CompactionFilter * user_comp_filter, std::unique_ptr< const CompactionFilter > user_comp_filter_from_factory = nullptr) inline
Definition at line 180 of file db_ttl.h.
References user_comp_filter_, and user_comp_filter_from_factory_.
     : ttl_(ttl),
       user_comp_filter_(user_comp_filter),
       user_comp_filter_from_factory_(std::move(user_comp_filter_from_factory)) {
     // Unlike the merge operator, compaction filter is necessary for TTL, hence
     // this would be called even if user doesn't specify any compaction-filter
     if (!user_comp_filter_) {
       user_comp_filter_ = user_comp_filter_from_factory_.get();
     }
   }
Member Function Documentation
virtual bool rocksdb::TtlCompactionFilter::Filter (int level, const Slice & key, const Slice & old_val, std::string * new_val, bool * value_changed) const inline override virtual
Implements rocksdb::CompactionFilter.
Definition at line 195 of file db_ttl.h.
References rocksdb::Slice::data(), rocksdb::CompactionFilter::Filter(), rocksdb::DBWithTTL::IsStale(), rocksdb::DBWithTTL::kTSLength, rocksdb::Slice::size(), ttl_, and user_comp_filter_.
{
     if (DBWithTTL::IsStale(old_val, ttl_)) {
       return true;
     }
     if (user_comp_filter_ == nullptr) {
       return false;
     }
     assert(old_val.size() >= DBWithTTL::kTSLength);
     Slice old_val_without_ts(old_val.data(),
                              old_val.size() - DBWithTTL::kTSLength);
     if (user_comp_filter_->Filter(level, key, old_val_without_ts, new_val,
                                   value_changed)) {
       return true;
     }
     if (*value_changed) {
       new_val->append(old_val.data() + old_val.size() - DBWithTTL::kTSLength,
                       DBWithTTL::kTSLength);
     }
     return false;
   }
virtual const char* rocksdb::TtlCompactionFilter::Name () const inline override virtual
Implements rocksdb::CompactionFilter.
Definition at line 220 of file db_ttl.h.
{
     return "Delete By TTL";
   }
Member Data Documentation
int32_t rocksdb::TtlCompactionFilter::ttl_ private
Definition at line 225 of file db_ttl.h.
Referenced by Filter().
const CompactionFilter* rocksdb::TtlCompactionFilter::user_comp_filter_ private
Definition at line 226 of file db_ttl.h.
Referenced by Filter(), and TtlCompactionFilter().
std::unique_ptr<const CompactionFilter> rocksdb::TtlCompactionFilter::user_comp_filter_from_factory_ private
Definition at line 227 of file db_ttl.h.
Referenced by TtlCompactionFilter().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/utilities/ttl/db_ttl.h