rippled: beast::insight::Event Class Reference
beast::insight::Event Class Reference
#include <Event.h>
Public Types
typedef EventImpl::value_type value_type
Public Member Functions
Event ()
Event (std::shared_ptr< EventImpl > const &impl)
template<class Rep , class Period >
void notify (std::chrono::duration< Rep, Period > const &value) const
std::shared_ptr< EventImpl >
const & impl () const
Public Member Functions inherited from beast::insight::Base
virtual ~Base ()=0
Private Attributes
std::shared_ptr< EventImpl > m_impl
Detailed Description
A metric for reporting event timing.
An event is an operation that has an associated millisecond time, or other integral value. Because events happen at a specific moment, the metric only supports a push-style interface.
This is a lightweight reference wrapper which is cheap to copy and assign. When the last reference goes away, the metric is no longer collected.
Definition at line 43 of file Event.h.
Member Typedef Documentation
typedef EventImpl::value_type beast::insight::Event::value_type
Definition at line 46 of file Event.h.
Constructor & Destructor Documentation
beast::insight::Event::Event () inline
Create a null metric. A null metric reports no information.
Definition at line 51 of file Event.h.
         { }
beast::insight::Event::Event (std::shared_ptr< EventImpl > const & impl) inline explicit
Create the metric reference the specified implementation. Normally this won't be called directly. Instead, call the appropriate factory function in the Collector interface.
See Also
Collector.
Definition at line 59 of file Event.h.
         : m_impl (impl)
         { }
Member Function Documentation
std::shared_ptr<EventImpl> const& beast::insight::Event::impl () const inline
Definition at line 72 of file Event.h.
References m_impl.
     {
         return m_impl;
     }
template<class Rep , class Period > void beast::insight::Event::notify (std::chrono::duration< Rep, Period > const & value) const inline
Push an event notification.
Definition at line 66 of file Event.h.
References m_impl.
Referenced by ripple::JobQueueImp::on_dequeue(), ripple::JobQueueImp::on_execute(), ripple::ApplicationImp::sample_io_service_latency::operator()(), ripple::PathRequests::reportFast(), and ripple::PathRequests::reportFull().
     {
         if (m_impl)
             m_impl->notify (ceil <value_type> (value));
     }
Member Data Documentation
std::shared_ptr<EventImpl> beast::insight::Event::m_impl private
Definition at line 78 of file Event.h.
Referenced by impl(), and notify().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/insight/Event.h