rippled: ripple::ParameterString Class Reference
ripple::ParameterString Class Reference
#include <ParameterTable.h>
Public Member Functions
ParameterString (Parameter::ref parent, const std::string &name, const std::string &value)
virtual Json::Value getValue (int) const
virtual bool setValue (const Json::Value &value, Json::Value &error)
Public Member Functions inherited from ripple::Parameter
Parameter (Parameter::ref parent, const std::string &name)
virtual ~Parameter ()
const std::string & getName () const
Parameter::pointer getShared ()
Private Attributes
std::string mValue
Additional Inherited Members
Public Types inherited from ripple::Parameter
typedef boost::shared_ptr
< Parameter > pointer
typedef const
boost::shared_ptr< Parameter > & ref
Detailed Description
Definition at line 79 of file ParameterTable.h.
Constructor & Destructor Documentation
ripple::ParameterString::ParameterString (Parameter::ref parent, const std::string & name, const std::string & value)
Definition at line 134 of file ParameterTable.cpp.
     : Parameter (parent, name), mValue (value)
 {
     ;
 }
Member Function Documentation
Json::Value ripple::ParameterString::getValue (int) const virtual
Implements ripple::Parameter.
Definition at line 140 of file ParameterTable.cpp.
References mValue, and rocksdb::crc32c::Value().
 {
     return Json::Value (mValue);
 }
bool ripple::ParameterString::setValue (const Json::Value & value, Json::Value & error) virtual
Implements ripple::Parameter.
Definition at line 145 of file ParameterTable.cpp.
References Json::Value::asString(), Json::Value::isConvertibleTo(), mValue, Json::objectValue, Json::stringValue, and value.
 {
     if (!value.isConvertibleTo (Json::stringValue))
     {
         error = Json::objectValue;
         error["error"] = "Cannot convert to string";
         error["value"] = value;
         return false;
     }
     mValue = value.asString ();
     return true;
 }
Member Data Documentation
std::string ripple::ParameterString::mValue private
Definition at line 87 of file ParameterTable.h.
Referenced by getValue(), and setValue().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/main/ParameterTable.h
rippled/src/ripple_app/main/ParameterTable.cpp