rippled: rocksdb::MergeOperators Class Reference
rocksdb::MergeOperators Class Reference
#include <merge_operators.h>
Static Public Member Functions
static std::shared_ptr
< MergeOperator > CreatePutOperator ()
static std::shared_ptr
< MergeOperator > CreateUInt64AddOperator ()
static std::shared_ptr
< MergeOperator > CreateStringAppendOperator ()
static std::shared_ptr
< MergeOperator > CreateStringAppendTESTOperator ()
static std::shared_ptr
< MergeOperator > CreateFromStringId (const std::string &name)
Detailed Description
Definition at line 16 of file merge_operators.h.
Member Function Documentation
static std::shared_ptr<MergeOperator> rocksdb::MergeOperators::CreateFromStringId (const std::string & name) inline static
Definition at line 25 of file merge_operators.h.
References CreatePutOperator(), CreateStringAppendOperator(), CreateStringAppendTESTOperator(), and CreateUInt64AddOperator().
Referenced by rocksdb::Benchmark::Open().
{
     if (name == "put") {
       return CreatePutOperator();
     } else if ( name == "uint64add") {
       return CreateUInt64AddOperator();
     } else if (name == "stringappend") {
       return CreateStringAppendOperator();
     } else if (name == "stringappendtest") {
       return CreateStringAppendTESTOperator();
     } else {
       // Empty or unknown, just return nullptr
       return nullptr;
     }
   }
std::shared_ptr< MergeOperator > rocksdb::MergeOperators::CreatePutOperator () static
Definition at line 50 of file put.cc.
Referenced by CreateFromStringId(), rocksdb::DBTest::CurrentOptions(), and rocksdb::StressTest::Open().
{
   return std::make_shared<PutOperator>();
 }
std::shared_ptr< MergeOperator > rocksdb::MergeOperators::CreateStringAppendOperator () static
Definition at line 53 of file stringappend.cc.
Referenced by CreateFromStringId().
{
   return std::make_shared<StringAppendOperator>(',');
 }
std::shared_ptr< MergeOperator > rocksdb::MergeOperators::CreateStringAppendTESTOperator () static
Definition at line 99 of file stringappend2.cc.
Referenced by CreateFromStringId().
{
   return std::make_shared<StringAppendTESTOperator>(',');
 }
std::shared_ptr< MergeOperator > rocksdb::MergeOperators::CreateUInt64AddOperator () static
Definition at line 61 of file uint64add.cc.
Referenced by CreateFromStringId().
{
   return std::make_shared<UInt64AddOperator>();
 }
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/utilities/merge_operators.h
rippled/src/ripple/rocksdb/rocksdb/utilities/merge_operators/put.cc
rippled/src/ripple/rocksdb/rocksdb/utilities/merge_operators/string_append/stringappend.cc
rippled/src/ripple/rocksdb/rocksdb/utilities/merge_operators/string_append/stringappend2.cc
rippled/src/ripple/rocksdb/rocksdb/utilities/merge_operators/uint64add.cc