rippled: ripple::RPCServerHandler Class Reference
ripple::RPCServerHandler Class Reference
#include <RPCServerHandler.h>
Public Member Functions
RPCServerHandler (NetworkOPs &networkOPs, Resource::Manager &resourceManager)
std::string createResponse (int statusCode, std::string const &description)
bool isAuthorized (std::map< std::string, std::string > const &headers)
std::string processRequest (std::string const &request, beast::IP::Endpoint const &remoteIPAddress)
Public Member Functions inherited from ripple::RPCServer::Handler
virtual ~Handler ()
Private Attributes
NetworkOPs & m_networkOPs
Resource::Manager & m_resourceManager
Detailed Description
Handles RPC requests.
Definition at line 29 of file RPCServerHandler.h.
Constructor & Destructor Documentation
ripple::RPCServerHandler::RPCServerHandler (NetworkOPs & networkOPs, Resource::Manager & resourceManager) explicit
Definition at line 22 of file RPCServerHandler.cpp.
     : m_networkOPs (networkOPs)
     , m_resourceManager (resourceManager)
 {
 }
Member Function Documentation
std::string ripple::RPCServerHandler::createResponse (int statusCode, std::string const & description) virtual
Construct a HTTP response string.
Implements ripple::RPCServer::Handler.
Definition at line 28 of file RPCServerHandler.cpp.
References ripple::HTTPReply().
Referenced by processRequest().
 {
     return HTTPReply (statusCode, description);
 }
bool ripple::RPCServerHandler::isAuthorized (std::map< std::string, std::string > const & headers) virtual
Determine if the connection is authorized.
Implements ripple::RPCServer::Handler.
Definition at line 35 of file RPCServerHandler.cpp.
References ripple::HTTPAuthorized().
 {
     return HTTPAuthorized (headers);
 }
std::string ripple::RPCServerHandler::processRequest (std::string const & request, beast::IP::Endpoint const & remoteIPAddress) virtual
Produce a response for a given request.
Parameters
request The RPC request string.
Returns
The server's response.
Implements ripple::RPCServer::Handler.
Definition at line 41 of file RPCServerHandler.cpp.
References ripple::Config::ADMIN, Json::arrayValue, Json::Value::asString(), ripple::Resource::Consumer::charge(), createResponse(), ripple::Resource::Consumer::disconnect(), ripple::RPCHandler::doRpcCommand(), ripple::RPC::Request::fee, ripple::Resource::feeReferenceRPC, ripple::Config::FORBID, ripple::getApp(), ripple::getConfig(), ripple::HTTPReply(), Json::Value::isArray(), Json::Value::isNull(), Json::Value::isObject(), Json::Value::isString(), ripple::JSONRPCReply(), ripple::lsDEBUG, m_networkOPs, m_resourceManager, ripple::Resource::Manager::newAdminEndpoint(), ripple::Resource::Manager::newInboundEndpoint(), Json::objectValue, Json::Reader::parse(), ripple::RPC::Request::result, beast::IP::Endpoint::to_string(), usage(), rocksdb::crc32c::Value(), and WriteLog.
Referenced by ripple::RPCHTTPServerImp::processSession().
 {
     Json::Value jsonRequest;
     {
         Json::Reader reader;
         if ((request.size() > 1000000) ||
             ! reader.parse (request, jsonRequest) ||
             jsonRequest.isNull () ||
             ! jsonRequest.isObject ())
         {
             return createResponse (400, "Unable to parse request");
         }
     }
     Config::Role const role (getConfig ().getAdminRole (jsonRequest, remoteIPAddress));
     Resource::Consumer usage;
     if (role == Config::ADMIN)
         usage = m_resourceManager.newAdminEndpoint (remoteIPAddress.to_string());
     else
         usage = m_resourceManager.newInboundEndpoint (remoteIPAddress);
     if (usage.disconnect ())
         return createResponse (503, "Server is overloaded");
     // Parse id now so errors from here on will have the id
     //
     // VFALCO NOTE Except that "id" isn't included in the following errors...
     //
     Json::Value const& id = jsonRequest ["id"];
     Json::Value const& method = jsonRequest ["method"];
     if (method.isNull ())
     {
         return createResponse (400, "Null method");
     }
     else if (! method.isString ())
     {
         return createResponse (400, "method is not string");
     }
     std::string strMethod = method.asString ();
     if (jsonRequest["params"].isNull())
         jsonRequest["params"] = Json::Value (Json::arrayValue);
     // Parse params
     Json::Value& params = jsonRequest ["params"];
     if (!params.isArray ())
         return HTTPReply (400, "params unparseable");
     // VFALCO TODO Shouldn't we handle this earlier?
     //
     if (role == Config::FORBID)
     {
         // VFALCO TODO Needs implementing
         // FIXME Needs implementing
         // XXX This needs rate limiting to prevent brute forcing password.
         return HTTPReply (403, "Forbidden");
     }
     // This code does all the work on the io_service thread and
     // has no rate-limiting based on source IP or anything.
     // This is a temporary safety
     if ((role != Config::ADMIN) && (getApp().getFeeTrack().isLoadedLocal()))
     {
         return HTTPReply (503, "Unable to service at this time");
     }
     std::string response;
     WriteLog (lsDEBUG, RPCServer) << "Query: " << strMethod << params;
     {
         Json::Value ripple_params (params.size()
             ? params [0u] : Json::Value (Json::objectValue));
         if (!ripple_params.isObject())
             return HTTPReply (400, "params must be an object");
         ripple_params ["command"] = strMethod;
         RPC::Request req (LogPartition::getJournal <RPCServer> (),
             strMethod, ripple_params, getApp ());
         // VFALCO Try processing the command using the new code
         if (getApp().getRPCManager().dispatch (req))
         {
             usage.charge (req.fee);
             WriteLog (lsDEBUG, RPCServer) << "Reply: " << req.result;
             return createResponse (200,
                 JSONRPCReply (req.result, Json::Value (), id));
         }
     }
     // legacy dispatcher
     Resource::Charge fee (Resource::feeReferenceRPC);
     RPCHandler rpcHandler (&m_networkOPs);
     Json::Value const result = rpcHandler.doRpcCommand (
         strMethod, params, role, fee);
     usage.charge (fee);
     WriteLog (lsDEBUG, RPCServer) << "Reply: " << result;
     response = JSONRPCReply (result, Json::Value (), id);
     return createResponse (200, response);
 }
Member Data Documentation
NetworkOPs& ripple::RPCServerHandler::m_networkOPs private
Definition at line 42 of file RPCServerHandler.h.
Referenced by processRequest().
Resource::Manager& ripple::RPCServerHandler::m_resourceManager private
Definition at line 43 of file RPCServerHandler.h.
Referenced by processRequest().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/rpc/RPCServerHandler.h
rippled/src/ripple_app/rpc/RPCServerHandler.cpp