rippled: beast::ServiceQueue_timing_test::Stopwatch Class Reference
beast::ServiceQueue_timing_test::Stopwatch Class Reference
Public Member Functions
Stopwatch ()
void start ()
double getElapsed ()
Private Attributes
std::int64_t m_startTime
Detailed Description
Definition at line 35 of file ServiceQueue.cpp.
Constructor & Destructor Documentation
beast::ServiceQueue_timing_test::Stopwatch::Stopwatch () inline
Definition at line 38 of file ServiceQueue.cpp.
References start().
 { start(); }
Member Function Documentation
double beast::ServiceQueue_timing_test::Stopwatch::getElapsed () inline
Definition at line 40 of file ServiceQueue.cpp.
References beast::Time::getHighResolutionTicks(), beast::Time::highResolutionTicksToSeconds(), and m_startTime.
Referenced by beast::ServiceQueue_timing_test::testThreads().
         {
             std::int64_t const now = Time::getHighResolutionTicks();
             return Time::highResolutionTicksToSeconds (now - m_startTime);
         }
void beast::ServiceQueue_timing_test::Stopwatch::start () inline
Definition at line 39 of file ServiceQueue.cpp.
References beast::Time::getHighResolutionTicks(), and m_startTime.
Referenced by Stopwatch().
 { m_startTime = Time::getHighResolutionTicks (); }
Member Data Documentation
std::int64_t beast::ServiceQueue_timing_test::Stopwatch::m_startTime private
Definition at line 46 of file ServiceQueue.cpp.
Referenced by getElapsed(), and start().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/threads/tests/ServiceQueue.cpp