rippled: ripple::Pathfinder Class Reference
ripple::Pathfinder Class Reference
#include <Pathfinder.h>
Public Member Functions
Pathfinder (RippleLineCache::ref cache, const RippleAddress &srcAccountID, const RippleAddress &dstAccountID, const uint160 &srcCurrencyID, const uint160 &srcIssuerID, const STAmount &dstAmount, bool &bValid)
bool findPaths (int iLevel, const unsigned int iMaxPaths, STPathSet &spsDst, STPath &spExtraPath)
Static Public Member Functions
static void initPathTable ()
Private Types
enum PaymentType {
pt_XRP_to_XRP, pt_XRP_to_nonXRP, pt_nonXRP_to_XRP, pt_nonXRP_to_same,
pt_nonXRP_to_nonXRP
}
enum NodeType {
nt_SOURCE, nt_ACCOUNTS, nt_BOOKS, nt_XRP_BOOK,
nt_DEST_BOOK, nt_DESTINATION
}
typedef std::vector< NodeType > PathType_t
typedef std::pair< int,
PathType_t > CostedPath_t
typedef std::vector< CostedPath_t > CostedPathList_t
Private Member Functions
bool checkComplete (STPathSet &retPathSet)
bool matchesOrigin (const uint160 &currency, const uint160 &issuer)
int getPathsOut (const uint160 &currency, const uint160 &accountID, bool isDestCurrency, const uint160 &dest)
void addLink (const STPath &currentPath, STPathSet &incompletePaths, int addFlags)
void addLink (const STPathSet &currentPaths, STPathSet &incompletePaths, int addFlags)
STPathSet & getPaths (const PathType_t &type, bool addComplete=true)
STPathSet filterPaths (int iMaxPaths, STPath &extraPath)
bool isNoRippleOut (const STPath &currentPath)
bool isNoRipple (uint160 const &setByID, uint160 const &setOnID, uint160 const &currencyID)
Static Private Member Functions
static std::string pathTypeToString (PathType_t const &)
static PathType_t makePath (char const *)
Private Attributes
uint160 mSrcAccountID
uint160 mDstAccountID
STAmount mDstAmount
uint160 mSrcCurrencyID
uint160 mSrcIssuerID
STAmount mSrcAmount
Ledger::pointer mLedger
LoadEvent::pointer m_loadEvent
RippleLineCache::pointer mRLCache
STPathElement mSource
STPathSet mCompletePaths
std::map< PathType_t, STPathSet > mPaths
ripple::unordered_map< uint160,
AccountItems::pointer > mRLMap
ripple::unordered_map
< std::pair< uint160, uint160 >
, int > mPOMap
Static Private Attributes
static std::map< PaymentType,
CostedPathList_t > mPathTable
static const std::uint32_t afADD_ACCOUNTS = 0x001
static const std::uint32_t afADD_BOOKS = 0x002
static const std::uint32_t afOB_XRP = 0x010
static const std::uint32_t afOB_LAST = 0x040
static const std::uint32_t afAC_LAST = 0x080
Detailed Description
Calculates payment paths.
The RippleCalc determines the quality of the found paths.
See Also
RippleCalc
Definition at line 58 of file Pathfinder.h.
Member Typedef Documentation
typedef std::pair<int, PathType_t> ripple::Pathfinder::CostedPath_t private
Definition at line 90 of file Pathfinder.h.
typedef std::vector<CostedPath_t> ripple::Pathfinder::CostedPathList_t private
Definition at line 91 of file Pathfinder.h.
typedef std::vector<NodeType> ripple::Pathfinder::PathType_t private
Definition at line 89 of file Pathfinder.h.
Member Enumeration Documentation
enum ripple::Pathfinder::NodeType private
Enumerator
nt_SOURCE
nt_ACCOUNTS
nt_BOOKS
nt_XRP_BOOK
nt_DEST_BOOK
nt_DESTINATION
Definition at line 79 of file Pathfinder.h.
     {
         nt_SOURCE,       // The source account with an issuer account, if required
         nt_ACCOUNTS,     // Accounts that connect from this source/currency
         nt_BOOKS,        // Order books that connect to this currency
         nt_XRP_BOOK,     // The order book from this currency to XRP
         nt_DEST_BOOK,    // The order book to the destination currency/issuer
         nt_DESTINATION   // The destination account only
     };
enum ripple::Pathfinder::PaymentType private
Enumerator
pt_XRP_to_XRP
pt_XRP_to_nonXRP
pt_nonXRP_to_XRP
pt_nonXRP_to_same
pt_nonXRP_to_nonXRP
Definition at line 70 of file Pathfinder.h.
     {
         pt_XRP_to_XRP,
         pt_XRP_to_nonXRP,
         pt_nonXRP_to_XRP,
         pt_nonXRP_to_same,
         pt_nonXRP_to_nonXRP
     };
Constructor & Destructor Documentation
ripple::Pathfinder::Pathfinder (RippleLineCache::ref cache, const RippleAddress & srcAccountID, const RippleAddress & dstAccountID, const uint160 & srcCurrencyID, const uint160 & srcIssuerID, const STAmount & dstAmount, bool & bValid)
Definition at line 97 of file Pathfinder.cpp.
References ripple::getApp(), ripple::STAmount::getCurrency(), ripple::Application::getJobQueue(), ripple::JobQueue::getLoadEvent(), ripple::base_uint< BITS >::isNonZero(), ripple::base_uint< BITS >::isZero(), ripple::jtPATH_FIND, m_loadEvent, mDstAccountID, mDstAmount, mLedger, mSource, mSrcAccountID, mSrcCurrencyID, and mSrcIssuerID.
Referenced by getPaths().
     :   mSrcAccountID (uSrcAccountID.getAccountID ()),
         mDstAccountID (uDstAccountID.getAccountID ()),
         mDstAmount (saDstAmount),
         mSrcCurrencyID (uSrcCurrencyID),
         mSrcIssuerID (uSrcIssuerID),
         mSrcAmount (uSrcCurrencyID, uSrcIssuerID, 1u, 0, true),
         mLedger (cache->getLedger ()), mRLCache (cache)
 {
     if ((mSrcAccountID == mDstAccountID && mSrcCurrencyID == mDstAmount.getCurrency ()) || mDstAmount == zero)
     {
         // no need to send to same account with same currency, must send non-zero
         bValid = false;
         mLedger.reset ();
         return;
     }
     bValid = true;
     m_loadEvent = getApp().getJobQueue ().getLoadEvent (jtPATH_FIND, "FindPath");
     bool bIssuer = mSrcCurrencyID.isNonZero() && mSrcIssuerID.isNonZero() && (mSrcIssuerID != mSrcAccountID);
     mSource = STPathElement(                       // Where does an empty path start?
         bIssuer ? mSrcIssuerID : mSrcAccountID,    // On the source account or issuer account
         mSrcCurrencyID,                            // In the source currency
         mSrcCurrencyID.isZero() ? uint160() : (bIssuer ? mSrcIssuerID : mSrcAccountID));
 }
Member Function Documentation
void ripple::Pathfinder::addLink (const STPath & currentPath, STPathSet & incompletePaths, int addFlags) private
Definition at line 620 of file Pathfinder.cpp.
References ACCOUNT_XRP, ripple::STPath::addElement(), ripple::STPathSet::addPath(), ripple::STPathSet::addUniquePath(), afAC_LAST, afADD_ACCOUNTS, afADD_BOOKS, afOB_LAST, afOB_XRP, ripple::STPathSet::assembleAdd(), BIND_TYPE, ripple::candCmp(), CURRENCY_XRP, ripple::RippleState::getAccountIDPeer(), ripple::Ledger::getAccountRootIndex(), ripple::getApp(), ripple::RippleState::getAuth(), ripple::RippleState::getBalance(), ripple::OrderBookDB::getBooksByTakerPays(), ripple::STAmount::getCurrency(), ripple::STPath::getJson(), ripple::RippleState::getLimit(), ripple::RippleState::getLimitPeer(), ripple::RippleState::getNoRipple(), ripple::Application::getOrderBookDB(), getPathsOut(), ripple::STPath::hasSeen(), ripple::is_bit_set(), ripple::STPath::isEmpty(), ripple::STAmount::isNative(), isNoRippleOut(), ripple::base_uint< BITS >::isZero(), ripple::lsfRequireAuth, ripple::lsTRACE, ripple::lsWARNING, ripple::STPathElement::mAccountID, matchesOrigin(), mCompletePaths, ripple::STPathElement::mCurrencyID, mDstAccountID, mDstAmount, ripple::STPathElement::mIssuerID, mLedger, ripple::STPath::mPath, mRLCache, mSource, mSrcAccountID, P_1, P_2, ripple::STPathElement::typeAccount, ripple::STPathElement::typeCurrency, ripple::STPathElement::typeIssuer, and WriteLog.
Referenced by addLink(), and getPaths().
 {
     STPathElement const& pathEnd   = currentPath.isEmpty() ? mSource : currentPath.mPath.back ();
     uint160 const& uEndCurrency    = pathEnd.mCurrencyID;
     uint160 const& uEndIssuer      = pathEnd.mIssuerID;
     uint160 const& uEndAccount     = pathEnd.mAccountID;
     bool const bOnXRP              = uEndCurrency.isZero();
     WriteLog (lsTRACE, Pathfinder) << "addLink< flags=" << addFlags << " onXRP=" << bOnXRP;
     WriteLog (lsTRACE, Pathfinder) << currentPath.getJson(0);
     if (addFlags & afADD_ACCOUNTS)
     { // add accounts
         if (bOnXRP)
         {
             if (mDstAmount.isNative() && !currentPath.isEmpty())
             { // non-default path to XRP destination
                 WriteLog (lsTRACE, Pathfinder) << "complete path found ax: " << currentPath.getJson(0);
                 mCompletePaths.addUniquePath(currentPath);
             }
         }
         else
         { // search for accounts to add
             SLE::pointer sleEnd = mLedger->getSLEi(Ledger::getAccountRootIndex(uEndAccount));
             if (sleEnd)
             {
                 bool const bRequireAuth = is_bit_set(sleEnd->getFieldU32(sfFlags), lsfRequireAuth);
                 bool const bIsEndCurrency = (uEndCurrency == mDstAmount.getCurrency());
                 bool const bIsNoRippleOut = isNoRippleOut (currentPath);
                 AccountItems& rippleLines (mRLCache->getRippleLines(uEndAccount));
                 std::vector< std::pair<int, uint160> > candidates;
                 candidates.reserve(rippleLines.getItems().size());
                 BOOST_FOREACH(AccountItem::ref item, rippleLines.getItems())
                 {
                     RippleState const& rspEntry = * reinterpret_cast<RippleState const *>(item.get());
                     uint160 const& acctID = rspEntry.getAccountIDPeer();
                     if ((uEndCurrency == rspEntry.getLimit().getCurrency()) &&
                         !currentPath.hasSeen(acctID, uEndCurrency, acctID))
                     { // path is for correct currency and has not been seen
                         if (rspEntry.getBalance() <= zero
                             && (!rspEntry.getLimitPeer()
                                 || -rspEntry.getBalance() >= rspEntry.getLimitPeer()
                                 || (bRequireAuth && !rspEntry.getAuth())))
{
                             // path has no credit
                         }
                         else if (bIsNoRippleOut && rspEntry.getNoRipple())
{
                             // Can't leave on this path
                         }
                         else if (acctID == mDstAccountID)
                         { // destination is always worth trying
                             if (uEndCurrency == mDstAmount.getCurrency())
                             { // this is a complete path
                                 if (!currentPath.isEmpty())
{
                                     WriteLog (lsTRACE, Pathfinder) << "complete path found ae: " << currentPath.getJson(0);
                                     mCompletePaths.addUniquePath(currentPath);
                                 }
                             }
                             else if ((addFlags & afAC_LAST) == 0)
                             { // this is a high-priority candidate
                                 candidates.push_back(std::make_pair(100000, acctID));
                             }
                         }
                         else if (acctID == mSrcAccountID)
{
                             // going back to the source is bad
                         }
                         else if ((addFlags & afAC_LAST) == 0)
                         { // save this candidate
                             int out = getPathsOut(uEndCurrency, acctID, bIsEndCurrency, mDstAccountID);
                             if (out)
                                 candidates.push_back(std::make_pair(out, acctID));
                         }
                     }
                 }
                 if (!candidates.empty())
                 {
                     std::sort (candidates.begin(), candidates.end(),
                         BIND_TYPE(candCmp, mLedger->getLedgerSeq(), P_1, P_2));
                     int count = candidates.size();
                     if ((count > 10) && (uEndAccount != mSrcAccountID)) // allow more paths from source
                         count = 10;
                     else if (count > 50)
                         count = 50;
                     std::vector< std::pair<int, uint160> >::const_iterator it = candidates.begin();
                     while (count-- != 0)
                     { // Add accounts to incompletePaths
                         incompletePaths.assembleAdd(currentPath, STPathElement(STPathElement::typeAccount, it->second, uEndCurrency, it->second));
                         ++it;
                     }
                 }
             }
             else
             {
                 WriteLog(lsWARNING, Pathfinder) << "Path ends on non-existent issuer";
             }
         }
     }
     if (addFlags & afADD_BOOKS)
     { // add order books
         if (addFlags & afOB_XRP)
         { // to XRP only
             if (!bOnXRP && getApp().getOrderBookDB().isBookToXRP(uEndIssuer, uEndCurrency))
             {
                 incompletePaths.assembleAdd(currentPath, STPathElement(STPathElement::typeCurrency, ACCOUNT_XRP, CURRENCY_XRP, ACCOUNT_XRP));
             }
         }
         else
         {
             bool bDestOnly = (addFlags & afOB_LAST) != 0;
             std::vector<OrderBook::pointer> books;
             getApp().getOrderBookDB().getBooksByTakerPays(uEndIssuer, uEndCurrency, books);
             WriteLog (lsTRACE, Pathfinder) << books.size() << " books found from this currency/issuer";
             BOOST_FOREACH(OrderBook::ref book, books)
             {
                 if (!currentPath.hasSeen (ACCOUNT_XRP, book->getCurrencyOut(), book->getIssuerOut()) &&
                         !matchesOrigin(book->getCurrencyOut(), book->getIssuerOut()) &&
                         (!bDestOnly || (book->getCurrencyOut() == mDstAmount.getCurrency())))
                 {
                     STPath newPath(currentPath);
                     if (book->getCurrencyOut().isZero())
                     { // to XRP
                         // add the order book itself
                         newPath.addElement(STPathElement(STPathElement::typeCurrency, ACCOUNT_XRP, CURRENCY_XRP, ACCOUNT_XRP));
                         if (mDstAmount.getCurrency().isZero())
                         { // destination is XRP, add account and path is complete
                             WriteLog (lsTRACE, Pathfinder) << "complete path found bx: " << currentPath.getJson(0);
                             mCompletePaths.addUniquePath(newPath);
                         }
                         else
                             incompletePaths.addPath(newPath);
                     }
                     else if (!currentPath.hasSeen(book->getIssuerOut(), book->getCurrencyOut(), book->getIssuerOut()))
                     { // Don't want the book if we've already seen the issuer
                         // add the order book itself
                         newPath.addElement(STPathElement(STPathElement::typeCurrency | STPathElement::typeIssuer,
                             ACCOUNT_XRP, book->getCurrencyOut(), book->getIssuerOut()));
                         if ((book->getIssuerOut() == mDstAccountID) && book->getCurrencyOut() == mDstAmount.getCurrency())
                         { // with the destination account, this path is complete
                             WriteLog (lsTRACE, Pathfinder) << "complete path found ba: " << currentPath.getJson(0);
                             mCompletePaths.addUniquePath(newPath);
                         }
                         else
                         { // add issuer's account, path still incomplete
                             incompletePaths.assembleAdd(newPath,
                                 STPathElement(STPathElement::typeAccount,
                                     book->getIssuerOut(), book->getCurrencyOut(), book->getIssuerOut()));
                         }
                     }
                 }
             }
         }
     }
 }
void ripple::Pathfinder::addLink (const STPathSet & currentPaths, STPathSet & incompletePaths, int addFlags) private
Definition at line 514 of file Pathfinder.cpp.
References addLink(), ripple::lsDEBUG, beast.util.CleanCPPFiles::path, ripple::STPathSet::size(), and WriteLog.
 {
     WriteLog (lsDEBUG, Pathfinder) << "addLink< on " << currentPaths.size() << " source(s), flags=" << addFlags;
     BOOST_FOREACH(const STPath& path, currentPaths)
     {
         addLink(path, incompletePaths, addFlags);
     }
 }
bool ripple::Pathfinder::checkComplete (STPathSet & retPathSet) private
STPathSet ripple::Pathfinder::filterPaths (int iMaxPaths, STPath & extraPath) private
Definition at line 233 of file Pathfinder.cpp.
References ripple::STPathSet::addPath(), ripple::bQualityCmp(), ripple::STAmount::divide(), ripple::STPath::getJson(), ripple::STPathSet::getJson(), ripple::STAmount::getRate(), ripple::lsDEBUG, ripple::lsINFO, mCompletePaths, mDstAccountID, mDstAmount, mLedger, ripple::STPath::mPath, mSrcAccountID, mSrcAmount, ripple::RippleCalc::rippleCalc(), ripple::STPath::size(), ripple::STPathSet::size(), ripple::tapNONE, ripple::tefEXCEPTION, ripple::tesSUCCESS, ripple::transToken(), and WriteLog.
Referenced by findPaths().
 {
     if (mCompletePaths.size() <= iMaxPaths)
         return mCompletePaths;
     STAmount remaining = mDstAmount;
     // must subtract liquidity in default path from remaining amount
     try
     {
         STAmount saMaxAmountAct, saDstAmountAct;
         std::vector<PathState::pointer> vpsExpanded;
         LedgerEntrySet lesSandbox (mLedger, tapNONE);
         TER result = RippleCalc::rippleCalc (
                  lesSandbox,
                  saMaxAmountAct,
                  saDstAmountAct,
                  vpsExpanded,
                  mSrcAmount,
                  mDstAmount,
                  mDstAccountID,
                  mSrcAccountID,
                  STPathSet (),
                  true,       // allow partial payment
                  false,
                  false,      // don't suppress default paths, that's the point
                  true);
         if (tesSUCCESS == result)
         {
             WriteLog (lsDEBUG, Pathfinder) << "Default path contributes: " << saDstAmountAct;
             remaining -= saDstAmountAct;
         }
         else
         {
             WriteLog (lsDEBUG, Pathfinder) << "Default path fails: " << transToken (result);
         }
     }
     catch (...)
     {
         WriteLog (lsDEBUG, Pathfinder) << "Default path causes exception";
     }
     std::vector<path_LQ_t> vMap;
     // Ignore paths that move only very small amounts
     STAmount saMinDstAmount = STAmount::divide(mDstAmount, STAmount(iMaxPaths + 2), mDstAmount);
     // Build map of quality to entry.
     for (int i = mCompletePaths.size (); i--;)
     {
         STAmount    saMaxAmountAct;
         STAmount    saDstAmountAct;
         std::vector<PathState::pointer> vpsExpanded;
         STPathSet   spsPaths;
         STPath&     spCurrent   = mCompletePaths[i];
         spsPaths.addPath (spCurrent);               // Just checking the current path.
         TER         terResult;
         try
         {
             LedgerEntrySet lesSandbox (mLedger, tapNONE);
             terResult   = RippleCalc::rippleCalc (
                               lesSandbox,
                               saMaxAmountAct,     // --> computed input
                               saDstAmountAct,     // --> computed output
                               vpsExpanded,
                               mSrcAmount,         // --> amount to send max.
                               mDstAmount,         // --> amount to deliver.
                               mDstAccountID,
                               mSrcAccountID,
                               spsPaths,
                               true,               // --> bPartialPayment: Allow, it might contribute.
                               false,              // --> bLimitQuality: Assume normal transaction.
                               true,               // --> bNoRippleDirect: Providing the only path.
                               true);              // --> bStandAlone: Don't need to delete unfundeds.
         }
         catch (const std::exception& e)
         {
             WriteLog (lsINFO, Pathfinder) << "findPaths: Caught throw: " << e.what ();
             terResult   = tefEXCEPTION;
         }
         if (tesSUCCESS != terResult)
         {
             WriteLog (lsDEBUG, Pathfinder) <<
                 "findPaths: dropping: " << transToken (terResult) <<
                 ": " << spCurrent.getJson (0);
         }
         else if (saDstAmountAct < saMinDstAmount)
         {
             WriteLog (lsDEBUG, Pathfinder) <<
                 "findPaths: dropping: outputs " << saDstAmountAct <<
                 ": %s" << spCurrent.getJson (0);
         }
         else
         {
             std::uint64_t  uQuality (
                 STAmount::getRate (saDstAmountAct, saMaxAmountAct));
             WriteLog (lsDEBUG, Pathfinder) <<
                 "findPaths: quality: " << uQuality <<
                 ": " << spCurrent.getJson (0);
             vMap.push_back (path_LQ_t (
                 uQuality, spCurrent.mPath.size (), saDstAmountAct, i));
         }
     }
     STPathSet spsDst;
     if (vMap.size())
     {
         std::sort (vMap.begin (), vMap.end (), bQualityCmp); // Lower is better and should be first.
         for (int i = 0, iPathsLeft = iMaxPaths;
             ((iPathsLeft > 0) || (extraPath.size() == 0)) && (i < vMap.size ()); ++i)
         {
             path_LQ_t& lqt = vMap[i];
             if ((iPathsLeft > 1) || ((iPathsLeft > 0) && (std::get<2> (lqt) >= remaining)))
             {
                 // last path must fill
                 --iPathsLeft;
                 remaining -= std::get<2> (lqt);
                 spsDst.addPath (mCompletePaths[std::get<3> (lqt)]);
             }
             else if ((iPathsLeft == 0) && (std::get<2>(lqt) >= mDstAmount) && (extraPath.size() == 0))
             {
                 // found an extra path that can move the whole amount
                 extraPath = mCompletePaths[std::get<3>(lqt)];
                 WriteLog (lsDEBUG, Pathfinder) <<
                     "Found extra full path: " << extraPath.getJson(0);
             }
             else
                 WriteLog (lsDEBUG, Pathfinder) <<
                     "Skipping a non-filling path: " <<
                     mCompletePaths[std::get<3> (lqt)].getJson (0);
         }
         if (remaining > zero)
         {
             WriteLog (lsINFO, Pathfinder) <<
                 "Paths could not send " << remaining << " of " << mDstAmount;
         }
         else
         {
             WriteLog (lsDEBUG, Pathfinder) <<
                 "findPaths: RESULTS: " << spsDst.getJson (0);
         }
     }
     else
     {
         WriteLog (lsDEBUG, Pathfinder) <<
             "findPaths: RESULTS: non-defaults filtered away";
     }
     return spsDst;
 }
bool ripple::Pathfinder::findPaths (int iLevel, const unsigned int iMaxPaths, STPathSet & spsDst, STPath & spExtraPath)
Definition at line 129 of file Pathfinder.cpp.
References ripple::STPathSet::addPath(), ripple::RippleAddress::createHumanAccountID(), ripple::STAmount::createHumanCurrency(), filterPaths(), ripple::Ledger::getAccountRootIndex(), ripple::STAmount::getCurrency(), ripple::STAmount::getFullText(), getPaths(), ripple::STPath::isEmpty(), ripple::base_uint< BITS >::isZero(), ripple::lsDEBUG, ripple::lsTRACE, mCompletePaths, mDstAccountID, mDstAmount, mLedger, mPathTable, mSrcAccountID, mSrcCurrencyID, mSrcIssuerID, beast.util.CleanCPPFiles::path, pt_nonXRP_to_nonXRP, pt_nonXRP_to_same, pt_nonXRP_to_XRP, pt_XRP_to_nonXRP, pt_XRP_to_XRP, ripple::STPathSet::size(), and WriteLog.
Referenced by ripple::RPCHandler::doRipplePathFind(), and ripple::PathRequest::doUpdate().
 { // pathsOut contains only non-default paths without source or destiation
 // On input, pathsOut contains any paths you want to ensure are included if still good
     WriteLog (lsTRACE, Pathfinder) << "findPaths>"
         " mSrcAccountID=" << RippleAddress::createHumanAccountID (mSrcAccountID) <<
         " mDstAccountID=" << RippleAddress::createHumanAccountID (mDstAccountID) <<
         " mDstAmount=" << mDstAmount.getFullText () <<
         " mSrcCurrencyID=" << STAmount::createHumanCurrency (mSrcCurrencyID) <<
         " mSrcIssuerID=" << RippleAddress::createHumanAccountID (mSrcIssuerID);
     if (!mLedger)
     {
         WriteLog (lsDEBUG, Pathfinder) << "findPaths< no ledger";
         return false;
     }
     bool bSrcXrp       = mSrcCurrencyID.isZero();
     bool bDstXrp       = mDstAmount.getCurrency().isZero();
     SLE::pointer sleSrc = mLedger->getSLEi(Ledger::getAccountRootIndex(mSrcAccountID));
     if (!sleSrc)
         return false;
     SLE::pointer sleDest = mLedger->getSLEi(Ledger::getAccountRootIndex(mDstAccountID));
     if (!sleDest && (!bDstXrp || (mDstAmount < mLedger->getReserve(0))))
         return false;
     PaymentType paymentType;
     if (bSrcXrp && bDstXrp)
     { // XRP -> XRP
         WriteLog (lsDEBUG, Pathfinder) << "XRP to XRP payment";
         paymentType = pt_XRP_to_XRP;
     }
     else if (bSrcXrp)
     { // XRP -> non-XRP
         WriteLog (lsDEBUG, Pathfinder) << "XRP to non-XRP payment";
         paymentType = pt_XRP_to_nonXRP;
     }
     else if (bDstXrp)
     { // non-XRP -> XRP
         WriteLog (lsDEBUG, Pathfinder) << "non-XRP to XRP payment";
         paymentType = pt_nonXRP_to_XRP;
     }
     else if (mSrcCurrencyID == mDstAmount.getCurrency())
     { // non-XRP -> non-XRP - Same currency
         WriteLog (lsDEBUG, Pathfinder) << "non-XRP to non-XRP - same currency";
         paymentType = pt_nonXRP_to_same;
     }
     else
     { // non-XRP to non-XRP - Different currency
         WriteLog (lsDEBUG, Pathfinder) << "non-XRP to non-XRP - cross currency";
         paymentType = pt_nonXRP_to_nonXRP;
     }
     BOOST_FOREACH(CostedPath_t const& costedPath, mPathTable[paymentType])
     {
        if (costedPath.first <= iLevel)
        {
            getPaths(costedPath.second);
        }
     }
     WriteLog (lsDEBUG, Pathfinder) << mCompletePaths.size() << " complete paths found";
     BOOST_FOREACH(const STPath& path, pathsOut)
     { // make sure no paths were lost
         bool found = false;
         if (!path.isEmpty ())
         {
             BOOST_FOREACH(const STPath& ePath, mCompletePaths)
             {
                 if (ePath == path)
                 {
                     found = true;
                     break;
                 }
             }
             if (!found)
                 mCompletePaths.addPath(path);
         }
     }
     WriteLog (lsDEBUG, Pathfinder) << mCompletePaths.size() << " paths to filter";
     if (mCompletePaths.size() > iMaxPaths)
         pathsOut = filterPaths(iMaxPaths, extraPath);
     else
         pathsOut = mCompletePaths;
     return true; // Even if we find no paths, default paths may work, and we don't check them currently
 }
STPathSet & ripple::Pathfinder::getPaths (const PathType_t & type, bool addComplete = true) private
Definition at line 526 of file Pathfinder.cpp.
References addLink(), ripple::STPathSet::addPath(), afAC_LAST, afADD_ACCOUNTS, afADD_BOOKS, afOB_LAST, afOB_XRP, CondLog, rocksdb::if(), ripple::STPathSet::isEmpty(), ripple::lsDEBUG, mCompletePaths, mPaths, nt_ACCOUNTS, nt_BOOKS, nt_DEST_BOOK, nt_DESTINATION, nt_SOURCE, nt_XRP_BOOK, Pathfinder(), pathTypeToString(), ripple::STPathSet::size(), and WriteLog.
Referenced by findPaths().
 {
     std::map< PathType_t, STPathSet >::iterator it = mPaths.find(type);
     // We already have these paths
     if (it != mPaths.end())
         return it->second;
     // The type is empty
     if (type.empty())
         return mPaths[type];
     NodeType toAdd = type.back();
     PathType_t pathType(type);
     pathType.pop_back();
     STPathSet pathsIn = getPaths(pathType, false);
     STPathSet& pathsOut = mPaths[type];
     WriteLog (lsDEBUG, Pathfinder)
         << "getPaths< adding onto '"
         << pathTypeToString(pathType) << "' to get '"
         << pathTypeToString(type) << "'";
     int cp = mCompletePaths.size();
     switch (toAdd)
     {
         case nt_SOURCE:
         { // source is an empty path
             assert(pathsOut.isEmpty());
             pathsOut.addPath(STPath());
         }
         break;
         case nt_ACCOUNTS:
             addLink(pathsIn, pathsOut, afADD_ACCOUNTS);
             break;
         case nt_BOOKS:
             addLink(pathsIn, pathsOut, afADD_BOOKS);
             break;
         case nt_XRP_BOOK:
             addLink(pathsIn, pathsOut, afADD_BOOKS | afOB_XRP);
             break;
         case nt_DEST_BOOK:
             addLink(pathsIn, pathsOut, afADD_BOOKS | afOB_LAST);
             break;
         case nt_DESTINATION:
             // FIXME: What if a different issuer was specified on the destination amount
             addLink(pathsIn, pathsOut, afADD_ACCOUNTS | afAC_LAST);
             break;
     }
     CondLog (mCompletePaths.size() != cp, lsDEBUG, Pathfinder)
         << (mCompletePaths.size() - cp)
         << " complete paths added";
     WriteLog (lsDEBUG, Pathfinder) << "getPaths> " << pathsOut.size() << " partial paths found";
     return pathsOut;
 }
int ripple::Pathfinder::getPathsOut (const uint160 & currency, const uint160 & accountID, bool isDestCurrency, const uint160 & dest) private
Definition at line 468 of file Pathfinder.cpp.
References ripple::RippleState::getAccountIDPeer(), ripple::Ledger::getAccountRootIndex(), ripple::RippleState::getAuth(), ripple::RippleState::getBalance(), ripple::STAmount::getCurrency(), ripple::RippleState::getLimit(), ripple::RippleState::getLimitPeer(), ripple::RippleState::getNoRipplePeer(), ripple::lsfRequireAuth, mLedger, mPOMap, mRLCache, and nothing.
Referenced by addLink().
 {
     // VFALCO TODO Use RippleAsset here
     std::pair<const uint160&, const uint160&> accountCurrency (currencyID, accountID);
     // VFALCO TODO Use RippleAsset here
     ripple::unordered_map<std::pair<uint160, uint160>, int>::iterator it = mPOMap.find (accountCurrency);
     if (it != mPOMap.end ())
         return it->second;
     SLE::pointer sleAccount = mLedger->getSLEi(Ledger::getAccountRootIndex(accountID));
     if (!sleAccount)
     {
         mPOMap[accountCurrency] = 0;
         return 0;
     }
     int aFlags = sleAccount->getFieldU32(sfFlags);
     bool const bAuthRequired = (aFlags & lsfRequireAuth) != 0;
     int count = 0;
     AccountItems& rippleLines (mRLCache->getRippleLines (accountID));
     BOOST_FOREACH (AccountItem::ref item, rippleLines.getItems ())
     {
         RippleState* rspEntry = (RippleState*) item.get ();
         if (currencyID != rspEntry->getLimit ().getCurrency ())
             nothing ();
         else if (rspEntry->getBalance () <= zero &&
                  (!rspEntry->getLimitPeer ()
                   || -rspEntry->getBalance () >= rspEntry->getLimitPeer ()
                   ||  (bAuthRequired && !rspEntry->getAuth ())))
             nothing ();
         else if (isDstCurrency && (dstAccount == rspEntry->getAccountIDPeer ()))
             count += 10000; // count a path to the destination extra
         else if (rspEntry->getNoRipplePeer ())
             nothing (); // This probably isn't a useful path out
         else
             ++count;
     }
     mPOMap[accountCurrency] = count;
     return count;
 }
void ripple::Pathfinder::initPathTable () static
Definition at line 872 of file Pathfinder.cpp.
References makePath(), mPathTable, pt_nonXRP_to_nonXRP, pt_nonXRP_to_same, pt_nonXRP_to_XRP, pt_XRP_to_nonXRP, and pt_XRP_to_XRP.
Referenced by ripple::ApplicationImp::setup().
 { // CAUTION: Do not include rules that build default paths
     { // XRP to XRP
         // do not remove this - it's necessary to build the table.
         /*CostedPathList_t& list =*/ mPathTable[pt_XRP_to_XRP];
 //        list.push_back(CostedPath_t(8, makePath("sbxd")));   // source -> book -> book_to_XRP -> destination
 //        list.push_back(CostedPath_t(9, makePath("sbaxd")));  // source -> book -> gateway -> to_XRP ->destination
     }
     { // XRP to non-XRP
         CostedPathList_t& list = mPathTable[pt_XRP_to_nonXRP];
         list.push_back(CostedPath_t(1,  makePath("sfd")));       // source -> book -> gateway
         list.push_back(CostedPath_t(3,  makePath("sfad")));      // source -> book -> account -> destination
         list.push_back(CostedPath_t(5,  makePath("sfaad")));     // source -> book -> account -> account -> destination
         list.push_back(CostedPath_t(6,  makePath("sbfd")));      // source -> book -> book -> destination
         list.push_back(CostedPath_t(8,  makePath("sbafd")));     // source -> book -> account -> book -> destination
         list.push_back(CostedPath_t(9,  makePath("sbfad")));     // source -> book -> book -> account -> destination
         list.push_back(CostedPath_t(10, makePath("sbafad")));
     }
     { // non-XRP to XRP
         CostedPathList_t& list = mPathTable[pt_nonXRP_to_XRP];
         list.push_back(CostedPath_t(1, makePath("sxd")));              // gateway buys XRP
         list.push_back(CostedPath_t(2, makePath("saxd")));             // source -> gateway -> book(XRP) -> dest
         list.push_back(CostedPath_t(6, makePath("saaxd")));
         list.push_back(CostedPath_t(7, makePath("sbxd")));
         list.push_back(CostedPath_t(8, makePath("sabxd")));
         list.push_back(CostedPath_t(9, makePath("sabaxd")));
     }
     { // non-XRP to non-XRP (same currency)
         CostedPathList_t& list = mPathTable[pt_nonXRP_to_same];
         list.push_back(CostedPath_t(1, makePath("sad")));               // source -> gateway -> destination
         list.push_back(CostedPath_t(1, makePath("sfd")));               // source -> book -> destination
         list.push_back(CostedPath_t(4, makePath("safd")));              // source -> gateway -> book -> destination
         list.push_back(CostedPath_t(4, makePath("sfad")));
         list.push_back(CostedPath_t(5, makePath("saad")));
         list.push_back(CostedPath_t(5, makePath("sxfd")));
         list.push_back(CostedPath_t(6, makePath("sxfad")));
         list.push_back(CostedPath_t(6, makePath("safad")));
         list.push_back(CostedPath_t(6, makePath("saxfd")));             // source -> gateway -> book to XRP -> book -> destination
         list.push_back(CostedPath_t(6, makePath("saxfad")));
         list.push_back(CostedPath_t(7, makePath("saaad")));
     }
     { // non-XRP to non-XRP (different currency)
         CostedPathList_t& list = mPathTable[pt_nonXRP_to_nonXRP];
         list.push_back(CostedPath_t(1, makePath("sfad")));
         list.push_back(CostedPath_t(1, makePath("safd")));
         list.push_back(CostedPath_t(3, makePath("safad")));
         list.push_back(CostedPath_t(4, makePath("sxfd")));
         list.push_back(CostedPath_t(5, makePath("saxfd")));
         list.push_back(CostedPath_t(5, makePath("sxfad")));
         list.push_back(CostedPath_t(6, makePath("saxfad")));
         list.push_back(CostedPath_t(7, makePath("saafd")));
         list.push_back(CostedPath_t(8, makePath("saafad")));
         list.push_back(CostedPath_t(9, makePath("safaad")));
     }
 }
bool ripple::Pathfinder::isNoRipple (uint160 const & setByID, uint160 const & setOnID, uint160 const & currencyID) private
Definition at line 593 of file Pathfinder.cpp.
References ripple::Ledger::getRippleStateIndex(), ripple::is_bit_set(), ripple::lsfHighNoRipple, ripple::lsfLowNoRipple, and mLedger.
Referenced by isNoRippleOut().
 {
     SLE::pointer sleRipple = mLedger->getSLEi (Ledger::getRippleStateIndex (setByID, setOnID, currencyID));
     return sleRipple &&
         is_bit_set (sleRipple->getFieldU32 (sfFlags), (setByID > setOnID) ? lsfHighNoRipple : lsfLowNoRipple);
 }
bool ripple::Pathfinder::isNoRippleOut (const STPath & currentPath) private
Definition at line 602 of file Pathfinder.cpp.
References ripple::STPath::end(), ripple::STPathElement::getNodeType(), ripple::is_bit_set(), isNoRipple(), ripple::STPathElement::mAccountID, ripple::STPathElement::mCurrencyID, mSrcAccountID, ripple::STPath::size(), and ripple::STPathElement::typeAccount.
Referenced by addLink().
 {
     // Must have at least one link
     if (currentPath.size() == 0)
         return false;
     // Last link must be an account
     STPathElement const& endElement = *(currentPath.end() - 1);
     if (!is_bit_set(endElement.getNodeType(), STPathElement::typeAccount))
         return false;
     // What account are we leaving?
     uint160 const& fromAccount =
         (currentPath.size() == 1) ? mSrcAccountID : (currentPath.end() - 2)->mAccountID;
     return isNoRipple (endElement.mAccountID, fromAccount, endElement.mCurrencyID);
 }
Pathfinder::PathType_t ripple::Pathfinder::makePath (char const * string) static private
Definition at line 795 of file Pathfinder.cpp.
References nt_ACCOUNTS, nt_BOOKS, nt_DEST_BOOK, nt_DESTINATION, nt_SOURCE, and nt_XRP_BOOK.
Referenced by initPathTable().
 {
     PathType_t ret;
     while (true)
     {
         switch (*string++)
         {
             case 's': // source
                 ret.push_back(nt_SOURCE);
                 break;
             case 'a': // accounts
                 ret.push_back(nt_ACCOUNTS);
                 break;
             case 'b': // books
                 ret.push_back(nt_BOOKS);
                 break;
             case 'x': // xrp book
                 ret.push_back(nt_XRP_BOOK);
                 break;
             case 'f': // book to final currency
                 ret.push_back(nt_DEST_BOOK);
                 break;
             case 'd': // destination (with account, if required and not already present)
                 ret.push_back(nt_DESTINATION);
                 break;
             case 0:
                 return ret;
         }
     }
 }
bool ripple::Pathfinder::matchesOrigin (const uint160 & currency, const uint160 & issuer) private
Definition at line 456 of file Pathfinder.cpp.
References ripple::base_uint< BITS >::isZero(), mSrcAccountID, mSrcCurrencyID, and mSrcIssuerID.
Referenced by addLink().
 {
     if (currency != mSrcCurrencyID)
         return false;
     if (currency.isZero())
         return true;
     return (issuer == mSrcIssuerID) || (issuer == mSrcAccountID);
 }
std::string ripple::Pathfinder::pathTypeToString (PathType_t const & type) static private
Definition at line 833 of file Pathfinder.cpp.
References nt_ACCOUNTS, nt_BOOKS, nt_DEST_BOOK, nt_DESTINATION, nt_SOURCE, and nt_XRP_BOOK.
Referenced by getPaths().
 {
     std::string ret;
     BOOST_FOREACH(NodeType const& node, type)
     {
         switch (node)
         {
             case nt_SOURCE:
                 ret.append("s");
                 break;
             case nt_ACCOUNTS:
                 ret.append("a");
                 break;
             case nt_BOOKS:
                 ret.append("b");
                 break;
             case nt_XRP_BOOK:
                 ret.append("x");
                 break;
             case nt_DEST_BOOK:
                 ret.append("f");
                 break;
             case nt_DESTINATION:
                 ret.append("d");
                 break;
         }
     }
     return ret;
 }
Member Data Documentation
const std::uint32_t ripple::Pathfinder::afAC_LAST = 0x080 static private
Definition at line 138 of file Pathfinder.h.
Referenced by addLink(), and getPaths().
const std::uint32_t ripple::Pathfinder::afADD_ACCOUNTS = 0x001 static private
Definition at line 134 of file Pathfinder.h.
Referenced by addLink(), and getPaths().
const std::uint32_t ripple::Pathfinder::afADD_BOOKS = 0x002 static private
Definition at line 135 of file Pathfinder.h.
Referenced by addLink(), and getPaths().
const std::uint32_t ripple::Pathfinder::afOB_LAST = 0x040 static private
Definition at line 137 of file Pathfinder.h.
Referenced by addLink(), and getPaths().
const std::uint32_t ripple::Pathfinder::afOB_XRP = 0x010 static private
Definition at line 136 of file Pathfinder.h.
Referenced by addLink(), and getPaths().
LoadEvent::pointer ripple::Pathfinder::m_loadEvent private
Definition at line 124 of file Pathfinder.h.
Referenced by Pathfinder().
STPathSet ripple::Pathfinder::mCompletePaths private
Definition at line 128 of file Pathfinder.h.
Referenced by addLink(), filterPaths(), findPaths(), and getPaths().
uint160 ripple::Pathfinder::mDstAccountID private
Definition at line 117 of file Pathfinder.h.
Referenced by addLink(), filterPaths(), findPaths(), and Pathfinder().
STAmount ripple::Pathfinder::mDstAmount private
Definition at line 118 of file Pathfinder.h.
Referenced by addLink(), filterPaths(), findPaths(), and Pathfinder().
Ledger::pointer ripple::Pathfinder::mLedger private
Definition at line 123 of file Pathfinder.h.
Referenced by addLink(), filterPaths(), findPaths(), getPathsOut(), isNoRipple(), and Pathfinder().
std::map< PathType_t, STPathSet > ripple::Pathfinder::mPaths private
Definition at line 129 of file Pathfinder.h.
Referenced by getPaths().
std::map< Pathfinder::PaymentType, Pathfinder::CostedPathList_t > ripple::Pathfinder::mPathTable static private
Definition at line 113 of file Pathfinder.h.
Referenced by findPaths(), and initPathTable().
ripple::unordered_map<std::pair<uint160, uint160>, int> ripple::Pathfinder::mPOMap private
Definition at line 132 of file Pathfinder.h.
Referenced by getPathsOut().
RippleLineCache::pointer ripple::Pathfinder::mRLCache private
Definition at line 125 of file Pathfinder.h.
Referenced by addLink(), and getPathsOut().
ripple::unordered_map<uint160, AccountItems::pointer> ripple::Pathfinder::mRLMap private
Definition at line 131 of file Pathfinder.h.
STPathElement ripple::Pathfinder::mSource private
Definition at line 127 of file Pathfinder.h.
Referenced by addLink(), and Pathfinder().
uint160 ripple::Pathfinder::mSrcAccountID private
Definition at line 116 of file Pathfinder.h.
Referenced by addLink(), filterPaths(), findPaths(), isNoRippleOut(), matchesOrigin(), and Pathfinder().
STAmount ripple::Pathfinder::mSrcAmount private
Definition at line 121 of file Pathfinder.h.
Referenced by filterPaths().
uint160 ripple::Pathfinder::mSrcCurrencyID private
Definition at line 119 of file Pathfinder.h.
Referenced by findPaths(), matchesOrigin(), and Pathfinder().
uint160 ripple::Pathfinder::mSrcIssuerID private
Definition at line 120 of file Pathfinder.h.
Referenced by findPaths(), matchesOrigin(), and Pathfinder().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/paths/Pathfinder.h
rippled/src/ripple_app/paths/Pathfinder.cpp