rippled: rocksdb::SimpleTableBuilder Class Reference
rocksdb::SimpleTableBuilder Class Reference
Classes
struct Rep
Public Member Functions
SimpleTableBuilder (const Options &options, WritableFile *file, CompressionType compression_type)
~SimpleTableBuilder ()
void Add (const Slice &key, const Slice &value) override
Status status () const override
Status Finish () override
void Abandon () override
uint64_t NumEntries () const override
uint64_t FileSize () const override
Public Member Functions inherited from rocksdb::TableBuilder
virtual ~TableBuilder ()
Private Member Functions
SimpleTableBuilder (const SimpleTableBuilder &)=delete
void operator= (const SimpleTableBuilder &)=delete
Private Attributes
Rep * rep_
Detailed Description
Definition at line 391 of file simple_table_db_test.cc.
Constructor & Destructor Documentation
rocksdb::SimpleTableBuilder::SimpleTableBuilder (const Options & options, WritableFile * file, CompressionType compression_type)
Definition at line 467 of file simple_table_db_test.cc.
                                                                          :
     rep_(new SimpleTableBuilder::Rep(options, file)) {
 }
rocksdb::SimpleTableBuilder::~SimpleTableBuilder ()
Definition at line 473 of file simple_table_db_test.cc.
References rep_.
{
   delete (rep_);
 }
rocksdb::SimpleTableBuilder::SimpleTableBuilder (const SimpleTableBuilder &) private delete
Member Function Documentation
void rocksdb::SimpleTableBuilder::Abandon () override virtual
Implements rocksdb::TableBuilder.
Definition at line 522 of file simple_table_db_test.cc.
References rocksdb::SimpleTableBuilder::Rep::closed, and rep_.
{
   rep_->closed = true;
 }
void rocksdb::SimpleTableBuilder::Add (const Slice & key, const Slice & value) override virtual
Implements rocksdb::TableBuilder.
Definition at line 477 of file simple_table_db_test.cc.
References rocksdb::WritableFile::Append(), rocksdb::Slice::data(), rocksdb::SimpleTableBuilder::Rep::file, rocksdb::SimpleTableBuilder::Rep::GetInternalKeyLength(), rocksdb::SimpleTableBuilder::Rep::index, rocksdb::SimpleTableBuilder::Rep::num_entries, rocksdb::SimpleTableBuilder::Rep::offset, rocksdb::PutFixed32(), rocksdb::PutFixed64(), rep_, and rocksdb::Slice::size().
{
   assert((int ) key.size() == Rep::GetInternalKeyLength());
   // Update index
   rep_->index.append(key.data(), key.size());
   PutFixed64(&(rep_->index), rep_->offset);
   // Write key-value pair
   rep_->file->Append(key);
   rep_->offset += Rep::GetInternalKeyLength();
   std::string size;
   int value_size = value.size();
   PutFixed32(&size, value_size);
   Slice sizeSlice(size);
   rep_->file->Append(sizeSlice);
   rep_->file->Append(value);
   rep_->offset += value_size + 4;
   rep_->num_entries++;
 }
uint64_t rocksdb::SimpleTableBuilder::FileSize () const override virtual
Implements rocksdb::TableBuilder.
Definition at line 530 of file simple_table_db_test.cc.
References rocksdb::SimpleTableBuilder::Rep::offset, and rep_.
{
   return rep_->offset;
 }
Status rocksdb::SimpleTableBuilder::Finish () override virtual
Implements rocksdb::TableBuilder.
Definition at line 503 of file simple_table_db_test.cc.
References rocksdb::WritableFile::Append(), rocksdb::SimpleTableBuilder::Rep::closed, rocksdb::SimpleTableBuilder::Rep::file, rocksdb::SimpleTableBuilder::Rep::index, rocksdb::SimpleTableBuilder::Rep::offset, rocksdb::Status::OK(), rocksdb::PutFixed64(), rep_, and rocksdb::Slice::size().
{
   Rep* r = rep_;
   assert(!r->closed);
   r->closed = true;
   uint64_t index_offset = rep_->offset;
   Slice index_slice(rep_->index);
   rep_->file->Append(index_slice);
   rep_->offset += index_slice.size();
   std::string index_offset_str;
   PutFixed64(&index_offset_str, index_offset);
   Slice foot_slice(index_offset_str);
   rep_->file->Append(foot_slice);
   rep_->offset += foot_slice.size();
   return Status::OK();
 }
uint64_t rocksdb::SimpleTableBuilder::NumEntries () const override virtual
Implements rocksdb::TableBuilder.
Definition at line 526 of file simple_table_db_test.cc.
References rocksdb::SimpleTableBuilder::Rep::num_entries, and rep_.
{
   return rep_->num_entries;
 }
void rocksdb::SimpleTableBuilder::operator= (const SimpleTableBuilder &) private delete
Status rocksdb::SimpleTableBuilder::status () const override virtual
Implements rocksdb::TableBuilder.
Definition at line 499 of file simple_table_db_test.cc.
References rocksdb::Status::OK().
{
   return Status::OK();
 }
Member Data Documentation
Rep* rocksdb::SimpleTableBuilder::rep_ private
Definition at line 432 of file simple_table_db_test.cc.
Referenced by Abandon(), Add(), FileSize(), Finish(), NumEntries(), and ~SimpleTableBuilder().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/db/simple_table_db_test.cc