rippled: ripple::detail::SignaturePart Class Reference
ripple::detail::SignaturePart Class Reference
Public Member Functions
SignaturePart (unsigned char const *sig, size_t size)
bool valid () const
BigNum getBigNum () const
size_t skip () const
Private Attributes
size_t m_skip
BigNum m_bn
Detailed Description
Definition at line 84 of file ECDSACanonical.cpp.
Constructor & Destructor Documentation
ripple::detail::SignaturePart::SignaturePart (unsigned char const * sig, size_t size) inline
Definition at line 91 of file ECDSACanonical.cpp.
References m_bn, m_skip, and ripple::detail::BigNum::set().
             : m_skip (0)
         {
             // The format is: <02> <length of signature> <signature>
             if ((sig[0] != 0x02) || (size < 3))
                 return;
             size_t const len (sig[1]);
             // Claimed length can't be longer than amount of data available
             if (len > (size - 2))
                 return;
             // Signature must be between 1 and 33 bytes.
             if ((len < 1) || (len > 33))
                 return;
             // The signature can't be negative
             if ((sig[2] & 0x80) != 0)
                 return;
             // It can't be zero
             if ((sig[2] == 0) && (len == 1))
                 return;
             // And it can't be padded
             if ((sig[2] == 0) && ((sig[3] & 0x80) == 0))
                 return;
             // Load the signature (ignore the marker prefix and length) and if
             // successful, count the number of bytes we consumed.
             if (m_bn.set (sig + 2, len))
                 m_skip = len + 2;
         }
Member Function Documentation
BigNum ripple::detail::SignaturePart::getBigNum () const inline
Definition at line 132 of file ECDSACanonical.cpp.
References m_bn.
Referenced by ripple::isCanonicalECDSASig().
         {
             return m_bn;
         }
size_t ripple::detail::SignaturePart::skip () const inline
Definition at line 138 of file ECDSACanonical.cpp.
References m_skip.
Referenced by ripple::isCanonicalECDSASig().
         {
             return m_skip;
         }
bool ripple::detail::SignaturePart::valid () const inline
Definition at line 126 of file ECDSACanonical.cpp.
References m_skip.
Referenced by ripple::isCanonicalECDSASig().
         {
             return m_skip != 0;
         }
Member Data Documentation
BigNum ripple::detail::SignaturePart::m_bn private
Definition at line 88 of file ECDSACanonical.cpp.
Referenced by getBigNum(), and SignaturePart().
size_t ripple::detail::SignaturePart::m_skip private
Definition at line 87 of file ECDSACanonical.cpp.
Referenced by SignaturePart(), skip(), and valid().
The documentation for this class was generated from the following file:
rippled/src/ripple/sslutil/impl/ECDSACanonical.cpp