rippled: beast::asio::PeerTest Class Reference
beast::asio::PeerTest Class Reference
#include <PeerTest.h>
Classes
class Result
struct Results
Public Types
enum { defaultTimeoutSeconds = 30 }
Static Public Member Functions
template<class Details , class ClientLogic , class ServerLogic , class ClientArg , class ServerArg >
static Results run (ClientArg const &clientArg, ServerArg const &serverArg, int timeoutSeconds=defaultTimeoutSeconds)
template<class Details , class ClientLogic , class ServerLogic , class Arg >
static Results run (Arg const &arg, int timeoutSeconds=defaultTimeoutSeconds)
template<class Details , class Arg >
static void report_async (unit_test::suite &suite, Arg const &arg, int timeoutSeconds=defaultTimeoutSeconds, bool beginTestCase=true)
template<class Details , class Arg >
static void report (unit_test::suite &suite, Arg const &arg, int timeoutSeconds=defaultTimeoutSeconds, bool beginTestCase=true)
Detailed Description
Performs a test of two peers defined by template parameters.
Definition at line 29 of file PeerTest.h.
Member Enumeration Documentation
anonymous enum
Enumerator
defaultTimeoutSeconds
How long to wait before aborting a peer and reporting a timeout.
Note
Aborting synchronous logics may cause undefined behavior.
Definition at line 32 of file PeerTest.h.
     {
         defaultTimeoutSeconds = 30
     };
Member Function Documentation
template<class Details , class Arg > static void beast::asio::PeerTest::report (unit_test::suite & suite, Arg const & arg, int timeoutSeconds = defaultTimeoutSeconds, bool beginTestCase = true) inline static
Definition at line 228 of file PeerTest.h.
References arg.
Referenced by report_async().
     {
         run <Details, TestPeerLogicSyncClient, TestPeerLogicSyncServer>
             (arg, timeoutSeconds).report (suite, beginTestCase);
         run <Details, TestPeerLogicAsyncClient, TestPeerLogicSyncServer>
             (arg, timeoutSeconds).report (suite, beginTestCase);
         run <Details, TestPeerLogicSyncClient, TestPeerLogicAsyncServer>
             (arg, timeoutSeconds).report (suite, beginTestCase);
         report_async <Details> (suite, arg, timeoutSeconds, beginTestCase);
     }
template<class Details , class Arg > static void beast::asio::PeerTest::report_async (unit_test::suite & suite, Arg const & arg, int timeoutSeconds = defaultTimeoutSeconds, bool beginTestCase = true) inline static
Definition at line 217 of file PeerTest.h.
References arg, and report().
     {
         run <Details, TestPeerLogicAsyncClient, TestPeerLogicAsyncServer>
             (arg, timeoutSeconds).report (suite, beginTestCase);
     }
template<class Details , class ClientLogic , class ServerLogic , class ClientArg , class ServerArg > static Results beast::asio::PeerTest::run (ClientArg const & clientArg, ServerArg const & serverArg, int timeoutSeconds = defaultTimeoutSeconds) inline static
Test two peers and return the results.
Definition at line 116 of file PeerTest.h.
References beast::asio::PeerTest::Results::client, beast::asio::TestPeerBasics::errc::exceptioned, beast::Process::isRunningUnderDebugger(), beast::asio::TestPeerType< Logic, Details >::join(), beast::asio::TestPeerBasics::make_error(), beast::asio::TestPeerType< Logic, Details >::name(), beast::asio::PeerTest::Results::name, beast::asio::PeerTest::Results::server, and beast::asio::TestPeerType< Logic, Details >::start().
     {
         Results results;
         if (Process::isRunningUnderDebugger ())
             timeoutSeconds = -1;
         try
         {
             TestPeerType <ServerLogic, Details> server (serverArg);
             results.name = server.name () + Details::getArgName (serverArg);
             try
             {
                 TestPeerType <ClientLogic, Details> client (clientArg);
                 results.name << " / " + client.name () + Details::getArgName (clientArg);
                 try
                 {
                     server.start (timeoutSeconds);
                     try
                     {
                         client.start (timeoutSeconds);
                         boost::system::error_code const ec = client.join ();
                         results.client = Result (ec, client.name ());
                         try
{
                             boost::system::error_code const ec = server.join ();
                             results.server = Result (ec, server.name ());
                         }
                         catch (std::exception& e)
{
                             results.server = Result (e, server.name ());
                         }
                         catch (...)
{
                             results.server = Result (TestPeerBasics::make_error (
                                 TestPeerBasics::errc::exceptioned), server.name ());
                         }
                     }
                     catch (std::exception& e)
                     {
                         results.server = Result (e, client.name ());
                     }
                     catch (...)
                     {
                         results.client = Result (TestPeerBasics::make_error (
                             TestPeerBasics::errc::exceptioned), client.name ());
                     }
                 }
                 catch (std::exception& e)
                 {
                     results.server = Result (e, server.name ());
                 }
                 catch (...)
                 {
                     results.server = Result (TestPeerBasics::make_error (
                         TestPeerBasics::errc::exceptioned), server.name ());
                 }
             }
             catch (std::exception& e)
             {
                 results.server = Result (e, "client");
             }
             catch (...)
             {
                 results.client = Result (TestPeerBasics::make_error (
                     TestPeerBasics::errc::exceptioned), "client");
             }
         }
         catch (std::exception& e)
         {
             results.server = Result (e, "server");
         }
         catch (...)
         {
             results.server = Result (TestPeerBasics::make_error (
                 TestPeerBasics::errc::exceptioned), "server");
         }
         return results;
     }
template<class Details , class ClientLogic , class ServerLogic , class Arg > static Results beast::asio::PeerTest::run (Arg const & arg, int timeoutSeconds = defaultTimeoutSeconds) inline static
Definition at line 208 of file PeerTest.h.
References arg.
     {
         return run <Details, ClientLogic, ServerLogic, Arg, Arg> (
             arg, arg, timeoutSeconds);
     }
The documentation for this class was generated from the following file:
rippled/src/beast/modules/beast_asio/tests/PeerTest.h