rippled: ripple::core::Offer Class Reference
ripple::core::Offer Class Reference
#include <Offer.h>
Public Types
typedef Amount amount_type
Public Member Functions
Offer ()=default
Offer (SLE::pointer const &entry, Quality quality)
Quality const quality () const noexcept
Account const account () const
Amounts const amount () const noexcept
SLE::pointer entry () const noexcept
Private Attributes
SLE::pointer m_entry
Quality m_quality
Detailed Description
Definition at line 35 of file Offer.h.
Member Typedef Documentation
typedef Amount ripple::core::Offer::amount_type
Definition at line 38 of file Offer.h.
Constructor & Destructor Documentation
ripple::core::Offer::Offer () default
ripple::core::Offer::Offer (SLE::pointer const & entry, Quality quality) inline
Definition at line 47 of file Offer.h.
         : m_entry (entry)
         , m_quality (quality)
     {
     }
Member Function Documentation
Account const ripple::core::Offer::account () const inline
Returns the account id of the offer's owner.
Definition at line 70 of file Offer.h.
References m_entry.
Referenced by ripple::core::Taker::fill(), ripple::core::Taker::process(), and ripple::core::OfferStream::step().
     {
         return m_entry->getFieldAccount160 (sfAccount);
     }
Amounts const ripple::core::Offer::amount () const inline noexcept
Returns the in and out amounts. Some or all of the out amount may be unfunded.
Definition at line 79 of file Offer.h.
References m_entry.
Referenced by ripple::core::Taker::fill(), and ripple::core::OfferStream::step().
     {
         return Amounts (m_entry->getFieldAmount (sfTakerPays),
             m_entry->getFieldAmount (sfTakerGets));
     }
SLE::pointer ripple::core::Offer::entry () const inline noexcept
Returns the ledger entry underlying the offer.
Definition at line 88 of file Offer.h.
References m_entry.
Referenced by ripple::core::Taker::fill(), ripple::core::operator<<(), and ripple::core::Taker::process().
     {
         return m_entry;
     }
Quality const ripple::core::Offer::quality () const inline noexcept
Returns the quality of the offer. Conceptually, the quality is the ratio of output to input currency. The implementation calculates it as the ratio of input to output currency (so it sorts ascending). The quality is computed at the time the offer is placed, and never changes for the lifetime of the offer. This is an important business rule that maintains accuracy when an offer is partially filled; Subsequent partial fills will use the original quality.
Definition at line 63 of file Offer.h.
References m_quality.
Referenced by ripple::core::Taker::fill().
     {
         return m_quality;
     }
Member Data Documentation
SLE::pointer ripple::core::Offer::m_entry private
Definition at line 41 of file Offer.h.
Referenced by account(), amount(), and entry().
Quality ripple::core::Offer::m_quality private
Definition at line 42 of file Offer.h.
Referenced by quality().
The documentation for this class was generated from the following file:
rippled/src/ripple_app/book/Offer.h