rippled: ripple::ProofOfWork Class Reference
ripple::ProofOfWork Class Reference
#include <ProofOfWork.h>
Public Types
enum { kMaxIterations = (1 << 23) }
typedef boost::shared_ptr
< ProofOfWork > pointer
Public Member Functions
ProofOfWork (const std::string &token, int iterations, uint256 const &challenge, uint256 const &target)
ProofOfWork (const std::string &token)
bool isValid () const
uint256 solve (int maxIterations=2 *kMaxIterations) const
bool checkSolution (uint256 const &solution) const
const std::string & getToken () const
uint256 const & getChallenge () const
std::uint64_t getDifficulty () const
Static Public Member Functions
static std::uint64_t getDifficulty (uint256 const &target, int iterations)
static bool validateToken (const std::string &strToken)
static bool calcResultInfo (PowResult powCode, std::string &strToken, std::string &strHuman)
Private Attributes
std::string mToken
uint256 mChallenge
uint256 mTarget
int mIterations
Static Private Attributes
static const uint256 sMinTarget
static const int maxIterations
Detailed Description
Definition at line 27 of file ProofOfWork.h.
Member Typedef Documentation
typedef boost::shared_ptr<ProofOfWork> ripple::ProofOfWork::pointer
Definition at line 35 of file ProofOfWork.h.
Member Enumeration Documentation
anonymous enum
Enumerator
kMaxIterations
Definition at line 30 of file ProofOfWork.h.
     {
         kMaxIterations = (1 << 23)
     };
Constructor & Destructor Documentation
ripple::ProofOfWork::ProofOfWork (const std::string & token, int iterations, uint256 const & challenge, uint256 const & target)
Definition at line 30 of file ProofOfWork.cpp.
     : mToken (token)
     , mChallenge (challenge)
     , mTarget (target)
     , mIterations (iterations)
 {
 }
ripple::ProofOfWork::ProofOfWork (const std::string & token) explicit
Definition at line 41 of file ProofOfWork.cpp.
References mChallenge, mIterations, mTarget, mToken, and ripple::base_uint< BITS >::SetHex().
 {
     std::vector<std::string> fields;
     boost::split (fields, token, boost::algorithm::is_any_of ("-"));
     if (fields.size () != 5)
         throw std::runtime_error ("invalid token");
     mToken = token;
     mChallenge.SetHex (fields[0]);
     mTarget.SetHex (fields[1]);
     mIterations = beast::lexicalCast <int> (fields[2]);
 }
Member Function Documentation
bool ripple::ProofOfWork::calcResultInfo (PowResult powCode, std::string & strToken, std::string & strHuman) static
Definition at line 166 of file ProofOfWork.cpp.
References NUMBER, ripple::powBADNONCE, ripple::powCORRUPT, ripple::powEXPIRED, ripple::powOK, ripple::powREUSED, and ripple::powTOOEASY.
Referenced by ripple::RPCHandler::doProofVerify().
 {
     static struct
     {
         PowResult       powCode;
         const char*     cpToken;
         const char*     cpHuman;
     } powResultInfoA[] =
     {
         {   powREUSED,              "powREUSED",                "Proof-of-work has already been used."                  },
         {   powBADNONCE,            "powBADNONCE",              "The solution does not meet the required difficulty."   },
         {   powEXPIRED,             "powEXPIRED",               "Token is expired."                                     },
         {   powCORRUPT,             "powCORRUPT",               "Invalid token."                                        },
         {   powTOOEASY,             "powTOOEASY",               "Difficulty has increased since token was issued."      },
         {   powOK,                  "powOK",                    "Valid proof-of-work."                                  },
     };
     int iIndex  = NUMBER (powResultInfoA);
     while (iIndex-- && powResultInfoA[iIndex].powCode != powCode)
         ;
     if (iIndex >= 0)
     {
         strToken    = powResultInfoA[iIndex].cpToken;
         strHuman    = powResultInfoA[iIndex].cpHuman;
     }
     return iIndex >= 0;
 }
bool ripple::ProofOfWork::checkSolution (uint256 const & solution) const
Definition at line 134 of file ProofOfWork.cpp.
References ripple::getSHA512Half(), kMaxIterations, mChallenge, mIterations, and mTarget.
Referenced by ripple::ProofOfWorkFactoryImp::checkProof().
 {
     if (mIterations > kMaxIterations)
         return false;
     std::vector<uint256> buf1;
     buf1.push_back (mChallenge);
     buf1.push_back (solution);
     buf1.push_back (uint256 ());
     std::vector<uint256> buf2;
     buf2.resize (mIterations);
     for (int i = (mIterations - 1); i >= 0; --i)
     {
         buf1[2] = getSHA512Half (buf1);
         buf2[i] = buf1[2];
     }
     return getSHA512Half (buf2) <= mTarget;
 }
uint256 const& ripple::ProofOfWork::getChallenge () const inline
Definition at line 53 of file ProofOfWork.h.
References mChallenge.
     {
         return mChallenge;
     }
std::uint64_t ripple::ProofOfWork::getDifficulty () const inline
Definition at line 58 of file ProofOfWork.h.
References mIterations, and mTarget.
Referenced by ripple::ProofOfWorkFactoryImp::getDifficulty(), and ripple::ProofOfWork_test::run().
     {
         return getDifficulty (mTarget, mIterations);
     }
std::uint64_t ripple::ProofOfWork::getDifficulty (uint256 const & target, int iterations) static
Definition at line 64 of file ProofOfWork.cpp.
References ripple::base_uint< BITS >::begin(), kMaxIterations, ripple::lsINFO, sMinTarget, and WriteLog.
 {
     // calculate the approximate number of hashes required to solve this proof of work
     if ((iterations > kMaxIterations) || (target < sMinTarget))
     {
         WriteLog (lsINFO, ProofOfWork) << "Iterations:" << iterations;
         WriteLog (lsINFO, ProofOfWork) << "MaxIterat: " << kMaxIterations;
         WriteLog (lsINFO, ProofOfWork) << "Target:    " << target;
         WriteLog (lsINFO, ProofOfWork) << "MinTarget: " << sMinTarget;
         throw std::runtime_error ("invalid proof of work target/iteration");
     }
     // more iterations means more hashes per iteration but also a larger final hash
     std::uint64_t difficulty = iterations + (iterations / 8);
     // Multiply the number of hashes needed by 256 for each leading zero byte in the difficulty
     const unsigned char* ptr = target.begin ();
     while (*ptr == 0)
     {
         difficulty *= 256;
         ++ptr;
     }
     difficulty = (difficulty * 256) / (*ptr + 1);
     return difficulty;
 }
const std::string& ripple::ProofOfWork::getToken () const inline
Definition at line 49 of file ProofOfWork.h.
References mToken.
Referenced by ripple::RPCHandler::doProofCreate(), and ripple::ProofOfWork_test::run().
     {
         return mToken;
     }
bool ripple::ProofOfWork::isValid () const
Definition at line 55 of file ProofOfWork.cpp.
References kMaxIterations, ripple::lsWARNING, mIterations, mTarget, sMinTarget, and WriteLog.
Referenced by solve().
 {
     if ((mIterations <= kMaxIterations) && (mTarget >= sMinTarget))
         return true;
     WriteLog (lsWARNING, ProofOfWork) << "Invalid PoW: " << mIterations << ", " << mTarget;
     return false;
 }
uint256 ripple::ProofOfWork::solve (int maxIterations = 2 * kMaxIterations) const
Definition at line 98 of file ProofOfWork.cpp.
References ripple::RandomNumbers::fill(), ripple::RandomNumbers::getInstance(), ripple::getSHA512Half(), isValid(), maxIterations, mChallenge, mIterations, and mTarget.
Referenced by ripple::RPCHandler::doProofSolve(), and ripple::ProofOfWork_test::run().
 {
     if (!isValid ())
         throw std::runtime_error ("invalid proof of work target/iteration");
     uint256 nonce;
     RandomNumbers::getInstance ().fill (&nonce);
     std::vector<uint256> buf2;
     buf2.resize (mIterations);
     std::vector<uint256> buf1;
     buf1.resize (3);
     buf1[0] = mChallenge;
     while (maxIterations > 0)
     {
         buf1[1] = nonce;
         buf1[2].zero ();
         for (int i = (mIterations - 1); i >= 0; --i)
         {
             buf1[2] = getSHA512Half (buf1);
             buf2[i] = buf1[2];
         }
         if (getSHA512Half (buf2) <= mTarget)
             return nonce;
         ++nonce;
         --maxIterations;
     }
     return uint256 ();
 }
bool ripple::ProofOfWork::validateToken (const std::string & strToken) static
Definition at line 156 of file ProofOfWork.cpp.
Referenced by ripple::RPCHandler::doProofSolve().
 {
     static boost::regex reToken ("[[:xdigit:]]{64}-[[:xdigit:]]{64}-[[:digit:]]+-[[:digit:]]+-[[:xdigit:]]{64}");
     boost::smatch       smMatch;
     return boost::regex_match (strToken, smMatch, reToken);
 }
Member Data Documentation
const int ripple::ProofOfWork::maxIterations static private
Definition at line 77 of file ProofOfWork.h.
Referenced by solve().
uint256 ripple::ProofOfWork::mChallenge private
Definition at line 72 of file ProofOfWork.h.
Referenced by checkSolution(), getChallenge(), ProofOfWork(), and solve().
int ripple::ProofOfWork::mIterations private
Definition at line 74 of file ProofOfWork.h.
Referenced by checkSolution(), getDifficulty(), isValid(), ProofOfWork(), and solve().
uint256 ripple::ProofOfWork::mTarget private
Definition at line 73 of file ProofOfWork.h.
Referenced by checkSolution(), getDifficulty(), isValid(), ProofOfWork(), and solve().
std::string ripple::ProofOfWork::mToken private
Definition at line 71 of file ProofOfWork.h.
Referenced by getToken(), and ProofOfWork().
const uint256 ripple::ProofOfWork::sMinTarget static private
Definition at line 76 of file ProofOfWork.h.
Referenced by getDifficulty(), and isValid().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/misc/ProofOfWork.h
rippled/src/ripple_app/misc/ProofOfWork.cpp