rippled: ripple::MultiSocketType< StreamSocket > Class Template Reference
ripple::MultiSocketType< StreamSocket > Class Template Reference
#include <MultiSocketType.h>
Classes
class AsyncOp
Public Types
typedef
std::remove_reference_t
< StreamSocket > next_layer_type
typedef
next_layer_type::lowest_layer_type lowest_layer_type
Public Types inherited from ripple::MultiSocket
enum Flags {
none = 0, client_ssl = 1, server_ssl = 2, server_ssl_required = 4,
server_proxy = 8
}
typedef
beast::asio::HandshakeDetectLogicPROXY::ProxyInfo ProxyInfo
Public Member Functions
template<typename Arg >
MultiSocketType (Arg &arg, boost::asio::ssl::context &ssl_context, int flags)
Protected Types
typedef boost::system::error_code error_code
Protected Member Functions
Flag getFlags () override
beast::IP::Endpoint local_endpoint () override
beast::IP::Endpoint remote_endpoint () override
ProxyInfo getProxyInfo () override
SSL * ssl_handle () override
beast::asio::abstract_socket & stream () const noexcept
void * this_layer_ptr (char const *type_name) const override
bool native_handle (char const *, void *) override
boost::asio::io_service & get_io_service () override
void * lowest_layer_ptr (char const *type_name) const override
error_code cancel (error_code &ec) override
error_code shutdown (abstract_socket::shutdown_type what, error_code &ec) override
error_code close (error_code &ec) override
std::size_t read_some (beast::asio::mutable_buffers buffers, error_code &ec) override
std::size_t write_some (beast::asio::const_buffers buffers, error_code &ec) override
void async_read_some (beast::asio::mutable_buffers buffers, transfer_handler handler) override
void async_write_some (beast::asio::const_buffers buffers, transfer_handler handler) override
void * next_layer_ptr (char const *type_name) const override
bool needs_handshake () override
void set_verify_mode (int verify_mode) override
error_code handshake (abstract_socket::handshake_type type, error_code &ec) override
error_code handshake (handshake_type type, beast::asio::const_buffers buffers, error_code &ec) override
void async_handshake (handshake_type type, error_handler handler) override
error_code shutdown (error_code &ec) override
void async_shutdown (error_handler handler) override
bool is_client () const noexcept
bool is_server () const noexcept
error_code handshake_error ()
error_code handshake_error (error_code &ec)
void initState ()
error_code initHandshake (handshake_type type)
error_code initHandshake (handshake_type type, beast::asio::const_buffers const &buffers)
template<typename Stream >
void set_ssl_stream (boost::asio::ssl::stream< Stream > &ssl_stream)
beast::asio::abstract_socket * new_plain_stream ()
template<typename ConstBufferSequence >
beast::asio::abstract_socket * new_plain_stream (ConstBufferSequence const &buffers)
beast::asio::abstract_socket * new_ssl_stream ()
template<typename ConstBufferSequence >
beast::asio::abstract_socket * new_ssl_stream (ConstBufferSequence const &buffers)
error_code do_handshake (handshake_type type, beast::asio::const_buffers const &buffers, error_code &ec)
Static Protected Member Functions
static Flag cleaned_flags (Flag flags)
Private Types
enum State {
stateNone, stateHandshake, stateExpectPROXY, stateDetectSSL,
stateHandshakeFinal, stateReady
}
Private Attributes
Flag m_flags
State m_state
boost::asio::ssl::context & m_ssl_context
int m_verify_mode
std::unique_ptr
< beast::asio::abstract_socket > m_stream
std::unique_ptr
< beast::asio::abstract_socket > m_ssl_stream
bool m_needsShutdown
StreamSocket m_next_layer
ProxyInfo m_proxyInfo
bool m_proxyInfoSet
SSL * m_native_ssl_handle
Flag m_origFlags
Additional Inherited Members
Static Public Member Functions inherited from ripple::MultiSocket
static MultiSocket * New (boost::asio::ip::tcp::socket &socket, boost::asio::ssl::context &ssl_context, int flags=0)
static MultiSocket * New (boost::asio::io_service &io_service, boost::asio::ssl::context &ssl_context, int flags=0)
Detailed Description
template<class StreamSocket>
class ripple::MultiSocketType< StreamSocket >
Template for producing instances of MultiSocket
Definition at line 41 of file MultiSocketType.h.
Member Typedef Documentation
template<class StreamSocket> typedef boost::system::error_code ripple::MultiSocketType< StreamSocket >::error_code protected
Definition at line 74 of file MultiSocketType.h.
template<class StreamSocket> typedef next_layer_type::lowest_layer_type ripple::MultiSocketType< StreamSocket >::lowest_layer_type
Definition at line 78 of file MultiSocketType.h.
template<class StreamSocket> typedef std::remove_reference_t<StreamSocket> ripple::MultiSocketType< StreamSocket >::next_layer_type
Definition at line 77 of file MultiSocketType.h.
Member Enumeration Documentation
template<class StreamSocket> enum ripple::MultiSocketType::State private
Enumerator
stateNone
stateHandshake
stateExpectPROXY
stateDetectSSL
stateHandshakeFinal
stateReady
Definition at line 47 of file MultiSocketType.h.
     {
         stateNone,              // Uninitialized, unloved.
         stateHandshake,         // We need a call to handshake() to proceed
         stateExpectPROXY,       // We expect to see a proxy handshake
         stateDetectSSL,         // We should detect SSL
         stateHandshakeFinal,    // Final call to underlying stream handshake()
         stateReady              // Stream is set and ready to go
     };
Constructor & Destructor Documentation
template<class StreamSocket> template<typename Arg > ripple::MultiSocketType< StreamSocket >::MultiSocketType (Arg & arg, boost::asio::ssl::context & ssl_context, int flags) inline
Definition at line 81 of file MultiSocketType.h.
         : m_flags (flags)
         , m_state (stateNone)
         , m_ssl_context (ssl_context)
         , m_verify_mode (0)
         , m_stream (nullptr)
         , m_needsShutdown (false)
         , m_next_layer (arg)
         , m_proxyInfoSet (false)
         , m_native_ssl_handle (nullptr)
         , m_origFlags (cleaned_flags (flags))
     {
         // See if our flags allow us to go directly
         // into the ready state with an active stream.
         initState ();
     }
Member Function Documentation
template<class StreamSocket> void ripple::MultiSocketType< StreamSocket >::async_handshake (handshake_type type, error_handler handler) inline override protected virtual
Reimplemented from beast::asio::abstract_socket.
Definition at line 330 of file MultiSocketType.h.
     {
         typedef AsyncOp <next_layer_type> Op;
         auto const op (std::make_shared <Op> (
             std::ref (*this), std::ref (m_next_layer), type,
                 beast::asio::const_buffers(), handler));
         op->start();
     }
template<class StreamSocket> void ripple::MultiSocketType< StreamSocket >::async_read_some (beast::asio::mutable_buffers buffers, transfer_handler handler) inline override protected virtual
Reimplemented from beast::asio::abstract_socket.
Definition at line 264 of file MultiSocketType.h.
     {
         stream ().async_read_some (buffers, handler);
     }
template<class StreamSocket> void ripple::MultiSocketType< StreamSocket >::async_shutdown (error_handler handler) inline override protected virtual
Reimplemented from beast::asio::abstract_socket.
Definition at line 359 of file MultiSocketType.h.
     {
         error_code ec;
         if (m_needsShutdown)
         {
             if (stream ().needs_handshake ())
             {
                 stream ().async_shutdown (handler);
                 return;
             }
         }
         else
         {
             // Our interface didn't require a shutdown but someone called
             // it anyone so generate an error code.
             ec = handshake_error ();
         }
         get_io_service ().post (bind_handler (handler, ec));
     }
template<class StreamSocket> void ripple::MultiSocketType< StreamSocket >::async_write_some (beast::asio::const_buffers buffers, transfer_handler handler) inline override protected virtual
Reimplemented from beast::asio::abstract_socket.
Definition at line 270 of file MultiSocketType.h.
     {
         stream ().async_write_some (buffers, handler);
     }
template<class StreamSocket> error_code ripple::MultiSocketType< StreamSocket >::cancel (error_code & ec) inline override protected virtual
Reimplemented from beast::asio::abstract_socket.
Definition at line 230 of file MultiSocketType.h.
     {
         return m_next_layer.lowest_layer ().cancel (ec);
     }
template<class StreamSocket> static Flag ripple::MultiSocketType< StreamSocket >::cleaned_flags (Flag flags) inline static protected
Definition at line 389 of file MultiSocketType.h.
Referenced by ripple::MultiSocketType< socket_type & >::initHandshake(), and ripple::MultiSocketType< socket_type & >::initState().
     {
         // Can't set both client and server
         assert (! flags.set (
             Flag::client_role | Flag::server_role));
         if (flags.set (Flag::client_role))
         {
             // clients ignore ssl_required
             flags = flags.without (Flag::ssl_required);
         }
         else if (flags.set (Flag::server_role))
         {
             // servers ignore ssl when ssl_required is set
             if (flags.set (Flag::ssl_required))
                 flags = flags.without (Flag::ssl);
         }
         return flags;
     }
template<class StreamSocket> error_code ripple::MultiSocketType< StreamSocket >::close (error_code & ec) inline override protected virtual
Reimplemented from beast::asio::abstract_socket.
Definition at line 241 of file MultiSocketType.h.
     {
         return m_next_layer.lowest_layer ().close (ec);
     }
template<class StreamSocket> error_code ripple::MultiSocketType< StreamSocket >::do_handshake (handshake_type type, beast::asio::const_buffers const & buffers, error_code & ec) inline protected
Definition at line 724 of file MultiSocketType.h.
Referenced by ripple::MultiSocketType< socket_type & >::handshake().
     {
         ec = initHandshake (type);
         if (ec)
             return ec;
         // How can we be ready if a handshake is needed?
         bassert (m_state != stateReady);
         // Prepare our rolling detect buffer with any input
         boost::asio::streambuf buffer;
         buffer.commit (boost::asio::buffer_copy (
             buffer.prepare (boost::asio::buffer_size (buffers)),
                 buffers));
         // Run a loop of processing and detecting handshakes
         // layer after layer until we arrive at the ready state
         // with a final stream.
         //
         do
         {
             switch (m_state)
             {
             case stateHandshakeFinal:
                 {
                     // A 'real' final handshake on the stream is needed.
                     m_state = stateReady;
                     stream ().handshake (type, ec);
                 }
                 break;
             case stateExpectPROXY:
                 {
                     typedef beast::asio::HandshakeDetectorType <next_layer_type,
                         beast::asio::HandshakeDetectLogicPROXY> op_type;
                     op_type op;
                     ec = op.detect (m_next_layer, buffer);
                     if (! ec)
                     {
                         bassert (op.getLogic ().finished ());
                         if (op.getLogic ().success ())
{
                             m_proxyInfo = op.getLogic ().getInfo ();
                             m_proxyInfoSet = true;
                             // Strip off the PROXY flag.
                             m_flags = m_flags.without (Flag::proxy);
                             // Update handshake state with the leftover bytes.
                             ec = initHandshake (type, buffer.data ());
                             // buffer input sequence intentionally untouched
                         }
                         else
{
                             // Didn't get the PROXY handshake we needed
                             ec = handshake_error ();
                         }
                     }
                 }
                 break;
             case stateDetectSSL:
                 {
                     typedef beast::asio::HandshakeDetectorType <next_layer_type,
                         beast::asio::HandshakeDetectLogicSSL3> op_type;
                     op_type op;
                     ec = op.detect (m_next_layer, buffer);
                     if (! ec)
                     {
                         bassert (op.getLogic ().finished ());
                         // Was it SSL?
                         if (op.getLogic ().success ())
{
                             // Convert the ssl flag to ssl_required
                             m_flags = m_flags.with (
                                 Flag::ssl_required).without (Flag::ssl);
                         }
                         else
{
                             // Not SSL, strip the ssl flag
                             m_flags = m_flags.without (Flag::ssl);
                         }
                         // Update handshake state with the leftover bytes.
                         ec = initHandshake (type, buffer.data ());
                         // buffer input sequence intentionally untouched
                     }
                 }
                 break;
             case stateNone:
             case stateReady:
             case stateHandshake:
             default:
                 fatal_error ("invalid state");
                 ec = handshake_error ();
                 break;
             }
             if (ec)
                 break;
         }
         while (m_state != stateReady);
         if (! ec)
         {
             // We should be in the ready state now.
             bassert (m_state == stateReady);
             // Always need shutdown if handshake successful.
             m_needsShutdown = true;
         }
         return ec;
     }
template<class StreamSocket> boost::asio::io_service& ripple::MultiSocketType< StreamSocket >::get_io_service () inline override protected virtual
Reimplemented from beast::asio::abstract_socket.
Definition at line 209 of file MultiSocketType.h.
Referenced by ripple::MultiSocketType< socket_type & >::async_shutdown().
     {
         return m_next_layer.get_io_service ();
     }
template<class StreamSocket> Flag ripple::MultiSocketType< StreamSocket >::getFlags () inline override protected virtual
Implements ripple::MultiSocket.
Definition at line 107 of file MultiSocketType.h.
     {
         return m_origFlags;
     }
template<class StreamSocket> ProxyInfo ripple::MultiSocketType< StreamSocket >::getProxyInfo () inline override protected virtual
Implements ripple::MultiSocket.
Definition at line 152 of file MultiSocketType.h.
     {
         return m_proxyInfo;
     }
template<class StreamSocket> error_code ripple::MultiSocketType< StreamSocket >::handshake (abstract_socket::handshake_type type, error_code & ec) inline override protected
Definition at line 315 of file MultiSocketType.h.
Referenced by ripple::MultiSocketType< socket_type & >::handshake().
     {
         return handshake (type, beast::asio::const_buffers (), ec);
     }
template<class StreamSocket> error_code ripple::MultiSocketType< StreamSocket >::handshake (handshake_type type, beast::asio::const_buffers buffers, error_code & ec) inline override protected virtual
Reimplemented from beast::asio::abstract_socket.
Definition at line 321 of file MultiSocketType.h.
     {
         return do_handshake (type, buffers, ec);
     }
template<class StreamSocket> error_code ripple::MultiSocketType< StreamSocket >::handshake_error () inline protected
Definition at line 422 of file MultiSocketType.h.
Referenced by ripple::MultiSocketType< socket_type & >::async_shutdown(), ripple::MultiSocketType< socket_type & >::do_handshake(), ripple::MultiSocketType< socket_type & >::handshake_error(), ripple::MultiSocketType< socket_type & >::initHandshake(), and ripple::MultiSocketType< socket_type & >::shutdown().
     {
         // VFALCO TODO maybe use a ripple error category?
         // set this to something custom that we can recognize later?
         //
         m_needsShutdown = false;
         return boost::asio::error::invalid_argument;
     }
template<class StreamSocket> error_code ripple::MultiSocketType< StreamSocket >::handshake_error (error_code & ec) inline protected
Definition at line 431 of file MultiSocketType.h.
     {
         return ec = handshake_error ();
     }
template<class StreamSocket> error_code ripple::MultiSocketType< StreamSocket >::initHandshake (handshake_type type) inline protected
Definition at line 538 of file MultiSocketType.h.
Referenced by ripple::MultiSocketType< socket_type & >::do_handshake(), and ripple::MultiSocketType< socket_type & >::initHandshake().
     {
         return initHandshake (type, beast::asio::const_buffers ());
     }
template<class StreamSocket> error_code ripple::MultiSocketType< StreamSocket >::initHandshake (handshake_type type, beast::asio::const_buffers const & buffers) inline protected
Definition at line 548 of file MultiSocketType.h.
     {
         switch (m_state)
         {
         case stateExpectPROXY:
         case stateDetectSSL:
             m_state = stateHandshake;
         case stateHandshake:
         case stateHandshakeFinal:
             break;
         case stateNone:
         case stateReady:
         default:
             // Didn't need handshake, but someone called us anyway?
             fatal_error ("invalid state");
             return handshake_error ();
         }
         // Set flags based on handshake if necessary
         if (! m_flags.any_set (Flag::client_role | Flag::server_role))
         {
             switch (type)
             {
             case client:
                 m_flags = m_flags.with (Flag::client_role);
                 break;
             case server:
                 m_flags = m_flags.with (Flag::server_role);
                 break;
             default:
                 fatal_error ("invalid tyoe");
                 break;
             }
             m_flags = cleaned_flags (m_flags);
         }
         // Handshake type must match the role flags
         if ( (type == client && ! is_client ()) ||
              (type == server && ! is_server ()))
             return handshake_error ();
         if (is_client ())
         {
             // if PROXY flag is set, then it should have already
             // been sent in the clear before calling handshake()
             // so strip the flag away.
             //
             m_flags = m_flags.without (Flag::proxy);
             // Someone forgot to call needs_handshake
             if (! m_flags.set (Flag::ssl))
                 return handshake_error ();
             m_state = stateHandshakeFinal;
             m_stream.reset (new_ssl_stream (buffers));
         }
         else
         {
             bassert (is_server ());
             if (m_flags.set (Flag::proxy))
             {
                 // We will expect and consume a PROXY handshake,
                 // then come back here with the flag cleared.
                 m_state = stateExpectPROXY;
                 m_stream.reset (new_plain_stream ());
             }
             else if (m_flags.set (Flag::ssl_required))
             {
                 // WE will perform a required final SSL handshake.
                 m_state = stateHandshakeFinal;
                 m_stream.reset (new_ssl_stream (buffers));
             }
             else if (m_flags.set (Flag::ssl))
             {
                 // We will use the SSL detector to update
                 // our flags and come back through here.
                 m_state = stateDetectSSL;
                 m_stream.reset (nullptr);
             }
             else
             {
                 // Done with auto-detect
                 m_state = stateReady;
                 m_stream.reset (new_plain_stream (buffers));
             }
         }
         return error_code ();
     }
template<class StreamSocket> void ripple::MultiSocketType< StreamSocket >::initState () inline protected
Definition at line 448 of file MultiSocketType.h.
Referenced by ripple::MultiSocketType< socket_type & >::MultiSocketType().
     {
         // Clean our flags up
         m_flags = cleaned_flags (m_flags);
         if (is_client ())
         {
             if (m_flags.set (Flag::proxy))
             {
                 if (m_flags.set (Flag::ssl))
                     m_state = stateHandshake;
                 else
                     m_state = stateReady;
                 // Client sends PROXY in the plain so make
                 // sure they have an underlying stream right away.
                 m_stream.reset (new_plain_stream ());
             }
             else if (m_flags.set (Flag::ssl))
             {
                 m_state = stateHandshakeFinal;
                 m_stream.reset (nullptr);
             }
             else
             {
                 m_state = stateReady;
                 m_stream.reset (new_plain_stream ());
             }
         }
         else if (is_server ())
         {
             if (m_flags.set (Flag::proxy))
             {
                 // We expect a PROXY handshake.
                 // Create the plain stream at handshake time.
                 m_state = stateHandshake;
                 m_stream.reset (nullptr);
             }
             else if (m_flags.set (Flag::ssl_required))
             {
                 // We require an SSL handshake.
                 // Create the stream at handshake time.
                 m_state = stateHandshakeFinal;
                 m_stream.reset (nullptr);
             }
             else if (m_flags.set (Flag::ssl))
             {
                 // We will use the SSL detector at handshake
                 // time decide which type of stream to create.
                 m_state = stateHandshake;
                 m_stream.reset (nullptr);
             }
             else
             {
                 // No handshaking required.
                 m_state = stateReady;
                 m_stream.reset (new_plain_stream ());
             }
         }
         else
         {
             // We will determine client/server mode
             // at the time handshake is called.
             bassert (! m_flags.set (Flag::proxy));
             m_flags = m_flags.without (Flag::proxy);
             if (m_flags.any_set (Flag::ssl | Flag::ssl_required))
             {
                 // We will decide stream type at handshake time
                 m_state = stateHandshake;
                 m_stream.reset (nullptr);
             }
             else
             {
                 m_state = stateReady;
                 m_stream.reset (new_plain_stream ());
             }
         }
         // We only set this to true in stateHandshake and
         // after the handshake completes without an error.
         //
         m_needsShutdown = false;
     }
template<class StreamSocket> bool ripple::MultiSocketType< StreamSocket >::is_client () const inline protected noexcept
Definition at line 410 of file MultiSocketType.h.
Referenced by ripple::MultiSocketType< socket_type & >::initHandshake(), and ripple::MultiSocketType< socket_type & >::initState().
     {
         return m_flags.set (Flag::client_role);
     }
template<class StreamSocket> bool ripple::MultiSocketType< StreamSocket >::is_server () const inline protected noexcept
Definition at line 415 of file MultiSocketType.h.
Referenced by ripple::MultiSocketType< socket_type & >::initHandshake(), and ripple::MultiSocketType< socket_type & >::initState().
     {
         return m_flags.set (Flag::server_role);
     }
template<class StreamSocket> beast::IP::Endpoint ripple::MultiSocketType< StreamSocket >::local_endpoint () inline override protected virtual
Implements ripple::MultiSocket.
Definition at line 113 of file MultiSocketType.h.
     {
         return beast::IPAddressConversion::from_asio (
             m_next_layer.local_endpoint());
     }
template<class StreamSocket> void* ripple::MultiSocketType< StreamSocket >::lowest_layer_ptr (char const * type_name) const inline override protected virtual
Always the lowest_layer of the underlying StreamSocket.
Reimplemented from beast::asio::abstract_socket.
Definition at line 221 of file MultiSocketType.h.
     {
         char const* const name (typeid (lowest_layer_type).name ());
         if (strcmp (name, type_name) == 0)
             return const_cast <void*> (
                 static_cast <void const*>(&m_next_layer.lowest_layer ()));
         return nullptr;
     }
template<class StreamSocket> bool ripple::MultiSocketType< StreamSocket >::native_handle (char const * , void *) inline override protected virtual
Reimplemented from beast::asio::abstract_socket.
Definition at line 197 of file MultiSocketType.h.
     {
         pure_virtual_called ();
         return false;
     }
template<class StreamSocket> bool ripple::MultiSocketType< StreamSocket >::needs_handshake () inline override protected virtual
Determine if the caller needs to call a handshaking function. This is also used to determine if the handshaking shutdown() has to be called.
Reimplemented from beast::asio::abstract_socket.
Definition at line 300 of file MultiSocketType.h.
Referenced by ripple::MultiSocketType< socket_type & >::async_shutdown(), and ripple::MultiSocketType< socket_type & >::shutdown().
     {
         return m_state == stateHandshake ||
                m_state == stateHandshakeFinal ||
                m_needsShutdown;
     }
template<class StreamSocket> beast::asio::abstract_socket* ripple::MultiSocketType< StreamSocket >::new_plain_stream () inline protected
Definition at line 661 of file MultiSocketType.h.
Referenced by ripple::MultiSocketType< socket_type & >::initHandshake(), ripple::MultiSocketType< socket_type & >::initState(), and ripple::MultiSocketType< socket_type & >::new_plain_stream().
     {
         typedef beast::asio::socket_wrapper <next_layer_type&> Wrapper;
         Wrapper* const socket (new Wrapper (m_next_layer));
         return socket;
     }
template<class StreamSocket> template<typename ConstBufferSequence > beast::asio::abstract_socket* ripple::MultiSocketType< StreamSocket >::new_plain_stream (ConstBufferSequence const & buffers) inline protected
Definition at line 673 of file MultiSocketType.h.
     {
         if (boost::asio::buffer_size (buffers) > 0)
         {
             typedef beast::asio::socket_wrapper <
                 beast::asio::PrefilledReadStream <next_layer_type&> > Wrapper;
             Wrapper* const socket (new Wrapper (m_next_layer));
             socket->this_layer ().fill (buffers);
             return socket;
         }
         return new_plain_stream ();
     }
template<class StreamSocket> beast::asio::abstract_socket* ripple::MultiSocketType< StreamSocket >::new_ssl_stream () inline protected
Definition at line 689 of file MultiSocketType.h.
Referenced by ripple::MultiSocketType< socket_type & >::initHandshake(), and ripple::MultiSocketType< socket_type & >::new_ssl_stream().
     {
         typedef typename boost::asio::ssl::stream <next_layer_type&> SslStream;
         typedef beast::asio::socket_wrapper <SslStream> Wrapper;
         Wrapper* const socket = new Wrapper (m_next_layer, m_ssl_context);
         set_ssl_stream (socket->this_layer ());
         return socket;
     }
template<class StreamSocket> template<typename ConstBufferSequence > beast::asio::abstract_socket* ripple::MultiSocketType< StreamSocket >::new_ssl_stream (ConstBufferSequence const & buffers) inline protected
Definition at line 703 of file MultiSocketType.h.
     {
         if (boost::asio::buffer_size (buffers) > 0)
         {
             typedef boost::asio::ssl::stream <
                 beast::asio::PrefilledReadStream <next_layer_type&> > SslStream;
             typedef beast::asio::socket_wrapper <SslStream> Wrapper;
             Wrapper* const socket = new Wrapper (m_next_layer, m_ssl_context);
             socket->this_layer ().next_layer().fill (buffers);
             set_ssl_stream (socket->this_layer ());
             return socket;
         }
         return new_ssl_stream ();
     }
template<class StreamSocket> void* ripple::MultiSocketType< StreamSocket >::next_layer_ptr (char const * type_name) const inline override protected virtual
Retrieve the next_layer. The next_layer_type is always the StreamSocket, regardless of what we have put around it in terms of SSL or buffering.
Reimplemented from beast::asio::abstract_socket.
Definition at line 286 of file MultiSocketType.h.
     {
         char const* const name (typeid (next_layer_type).name ());
         if (strcmp (name, type_name) == 0)
             return const_cast <void*> (
                 static_cast <void const*> (&m_next_layer));
         return nullptr;
     }
template<class StreamSocket> std::size_t ripple::MultiSocketType< StreamSocket >::read_some (beast::asio::mutable_buffers buffers, error_code & ec) inline override protected virtual
Reimplemented from beast::asio::abstract_socket.
Definition at line 252 of file MultiSocketType.h.
     {
         return stream ().read_some (buffers, ec);
     }
template<class StreamSocket> beast::IP::Endpoint ripple::MultiSocketType< StreamSocket >::remote_endpoint () inline override protected virtual
Implements ripple::MultiSocket.
Definition at line 120 of file MultiSocketType.h.
     {
         if (m_proxyInfoSet)
         {
             if (m_proxyInfo.protocol == "TCP4")
             {
                 return beast::IP::Endpoint (
                     beast::IP::AddressV4 (
                         m_proxyInfo.destAddress.value [0],
                         m_proxyInfo.destAddress.value [1],
                         m_proxyInfo.destAddress.value [2],
                         m_proxyInfo.destAddress.value [3])
                     , m_proxyInfo.destPort);
             }
             // VFALCO TODO IPv6 support
             bassertfalse;
             return beast::IP::Endpoint();
         }
         try
         {
             return beast::IPAddressConversion::from_asio (
                 m_next_layer.remote_endpoint());
         }
         catch (...)
         {
             return beast::IP::Endpoint ();
         }
     }
template<class StreamSocket> template<typename Stream > void ripple::MultiSocketType< StreamSocket >::set_ssl_stream (boost::asio::ssl::stream< Stream > & ssl_stream) inline protected
Definition at line 646 of file MultiSocketType.h.
Referenced by ripple::MultiSocketType< socket_type & >::new_ssl_stream().
     {
         m_ssl_stream.reset (new beast::asio::socket_wrapper <
             boost::asio::ssl::stream <Stream>&> (ssl_stream));
         m_ssl_stream->set_verify_mode (m_verify_mode);
         m_native_ssl_handle = ssl_stream.native_handle ();
     }
template<class StreamSocket> void ripple::MultiSocketType< StreamSocket >::set_verify_mode (int verify_mode) inline override protected virtual
Reimplemented from beast::asio::abstract_socket.
Definition at line 307 of file MultiSocketType.h.
     {
         if (m_ssl_stream != nullptr)
             m_ssl_stream->set_verify_mode (verify_mode);
         else
             m_verify_mode = verify_mode;
     }
template<class StreamSocket> error_code ripple::MultiSocketType< StreamSocket >::shutdown (abstract_socket::shutdown_type what, error_code & ec) inline override protected
Definition at line 235 of file MultiSocketType.h.
     {
         return m_next_layer.lowest_layer ().shutdown (what, ec);
     }
template<class StreamSocket> error_code ripple::MultiSocketType< StreamSocket >::shutdown (error_code & ec) inline override protected virtual
Reimplemented from beast::asio::abstract_socket.
Definition at line 345 of file MultiSocketType.h.
     {
         if (m_needsShutdown)
         {
             // Only do the shutdown if the stream really needs it.
             if (stream ().needs_handshake ())
                 return ec = stream ().shutdown (ec);
             return ec = error_code ();
         }
         return ec = handshake_error ();
     }
template<class StreamSocket> SSL* ripple::MultiSocketType< StreamSocket >::ssl_handle () inline override protected virtual
Returns a pointer to the SSL handle or nullptr if no SSL.
Implements ripple::MultiSocket.
Definition at line 158 of file MultiSocketType.h.
     {
         return m_native_ssl_handle;
     }
template<class StreamSocket> beast::asio::abstract_socket& ripple::MultiSocketType< StreamSocket >::stream () const inline protected noexcept
The current stream we are passing everything through. This object gets dynamically created and replaced with other objects as we process the various flags for handshaking.
Definition at line 174 of file MultiSocketType.h.
Referenced by ripple::MultiSocketType< socket_type & >::async_read_some(), ripple::MultiSocketType< socket_type & >::async_shutdown(), ripple::MultiSocketType< socket_type & >::async_write_some(), ripple::MultiSocketType< socket_type & >::do_handshake(), ripple::MultiSocketType< socket_type & >::read_some(), ripple::MultiSocketType< socket_type & >::shutdown(), and ripple::MultiSocketType< socket_type & >::write_some().
     {
         bassert (m_stream != nullptr);
         return *m_stream;
     }
template<class StreamSocket> void* ripple::MultiSocketType< StreamSocket >::this_layer_ptr (char const * type_name) const inline override protected virtual
Reimplemented from beast::asio::abstract_socket.
Definition at line 187 of file MultiSocketType.h.
     {
         char const* const name (typeid (next_layer_type).name ());
         if (strcmp (name, type_name) == 0)
             return const_cast <void*> (
                 static_cast <void const*> (&m_next_layer));
         return nullptr;
     }
template<class StreamSocket> std::size_t ripple::MultiSocketType< StreamSocket >::write_some (beast::asio::const_buffers buffers, error_code & ec) inline override protected virtual
Reimplemented from beast::asio::abstract_socket.
Definition at line 258 of file MultiSocketType.h.
     {
         return stream ().write_some (buffers, ec);
     }
Member Data Documentation
template<class StreamSocket> Flag ripple::MultiSocketType< StreamSocket >::m_flags private
Definition at line 57 of file MultiSocketType.h.
Referenced by ripple::MultiSocketType< socket_type & >::do_handshake(), ripple::MultiSocketType< socket_type & >::initHandshake(), ripple::MultiSocketType< socket_type & >::initState(), ripple::MultiSocketType< socket_type & >::is_client(), and ripple::MultiSocketType< socket_type & >::is_server().
template<class StreamSocket> SSL* ripple::MultiSocketType< StreamSocket >::m_native_ssl_handle private
Definition at line 70 of file MultiSocketType.h.
Referenced by ripple::MultiSocketType< socket_type & >::set_ssl_stream(), and ripple::MultiSocketType< socket_type & >::ssl_handle().
template<class StreamSocket> bool ripple::MultiSocketType< StreamSocket >::m_needsShutdown private
Definition at line 66 of file MultiSocketType.h.
Referenced by ripple::MultiSocketType< socket_type & >::async_shutdown(), ripple::MultiSocketType< socket_type & >::do_handshake(), ripple::MultiSocketType< socket_type & >::handshake_error(), ripple::MultiSocketType< socket_type & >::initState(), ripple::MultiSocketType< socket_type & >::needs_handshake(), and ripple::MultiSocketType< socket_type & >::shutdown().
template<class StreamSocket> StreamSocket ripple::MultiSocketType< StreamSocket >::m_next_layer private
Definition at line 67 of file MultiSocketType.h.
Referenced by ripple::MultiSocketType< socket_type & >::async_handshake(), ripple::MultiSocketType< socket_type & >::cancel(), ripple::MultiSocketType< socket_type & >::close(), ripple::MultiSocketType< socket_type & >::do_handshake(), ripple::MultiSocketType< socket_type & >::get_io_service(), ripple::MultiSocketType< socket_type & >::local_endpoint(), ripple::MultiSocketType< socket_type & >::lowest_layer_ptr(), ripple::MultiSocketType< socket_type & >::new_plain_stream(), ripple::MultiSocketType< socket_type & >::new_ssl_stream(), ripple::MultiSocketType< socket_type & >::next_layer_ptr(), ripple::MultiSocketType< socket_type & >::remote_endpoint(), ripple::MultiSocketType< socket_type & >::shutdown(), and ripple::MultiSocketType< socket_type & >::this_layer_ptr().
template<class StreamSocket> Flag ripple::MultiSocketType< StreamSocket >::m_origFlags private
Definition at line 71 of file MultiSocketType.h.
Referenced by ripple::MultiSocketType< socket_type & >::getFlags().
template<class StreamSocket> ProxyInfo ripple::MultiSocketType< StreamSocket >::m_proxyInfo private
Definition at line 68 of file MultiSocketType.h.
Referenced by ripple::MultiSocketType< socket_type & >::do_handshake(), ripple::MultiSocketType< socket_type & >::getProxyInfo(), and ripple::MultiSocketType< socket_type & >::remote_endpoint().
template<class StreamSocket> bool ripple::MultiSocketType< StreamSocket >::m_proxyInfoSet private
Definition at line 69 of file MultiSocketType.h.
Referenced by ripple::MultiSocketType< socket_type & >::do_handshake(), and ripple::MultiSocketType< socket_type & >::remote_endpoint().
template<class StreamSocket> boost::asio::ssl::context& ripple::MultiSocketType< StreamSocket >::m_ssl_context private
Definition at line 59 of file MultiSocketType.h.
Referenced by ripple::MultiSocketType< socket_type & >::new_ssl_stream().
template<class StreamSocket> std::unique_ptr< beast::asio::abstract_socket > ripple::MultiSocketType< StreamSocket >::m_ssl_stream private
Definition at line 65 of file MultiSocketType.h.
Referenced by ripple::MultiSocketType< socket_type & >::set_ssl_stream(), and ripple::MultiSocketType< socket_type & >::set_verify_mode().
template<class StreamSocket> State ripple::MultiSocketType< StreamSocket >::m_state private
Definition at line 58 of file MultiSocketType.h.
Referenced by ripple::MultiSocketType< socket_type & >::do_handshake(), ripple::MultiSocketType< socket_type & >::initHandshake(), ripple::MultiSocketType< socket_type & >::initState(), and ripple::MultiSocketType< socket_type & >::needs_handshake().
template<class StreamSocket> std::unique_ptr< beast::asio::abstract_socket> ripple::MultiSocketType< StreamSocket >::m_stream private
Definition at line 62 of file MultiSocketType.h.
Referenced by ripple::MultiSocketType< socket_type & >::initHandshake(), ripple::MultiSocketType< socket_type & >::initState(), and ripple::MultiSocketType< socket_type & >::stream().
template<class StreamSocket> int ripple::MultiSocketType< StreamSocket >::m_verify_mode private
Definition at line 60 of file MultiSocketType.h.
Referenced by ripple::MultiSocketType< socket_type & >::set_ssl_stream(), and ripple::MultiSocketType< socket_type & >::set_verify_mode().
The documentation for this class was generated from the following file:
rippled/src/ripple/common/impl/MultiSocketType.h