rippled: beast::Process Class Reference
beast::Process Class Reference
#include <Process.h>
Public Types
enum ProcessPriority { LowPriority = 0, NormalPriority = 1, HighPriority = 2, RealtimePriority = 3 }
Static Public Member Functions
static void setPriority (const ProcessPriority priority)
static void terminate ()
static bool isForegroundProcess ()
static void makeForegroundProcess ()
static void raisePrivilege ()
static void lowerPrivilege ()
static bool isRunningUnderDebugger ()
static bool openDocument (const String &documentURL, const String &parameters)
Private Member Functions
Process ()
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
Represents the current executable's process.
This contains methods for controlling the current application at the process-level.
See Also
Thread, BEASTApplication
Definition at line 37 of file Process.h.
Member Enumeration Documentation
enum beast::Process::ProcessPriority
Enumerator
LowPriority
NormalPriority
HighPriority
RealtimePriority
Definition at line 41 of file Process.h.
     {
         LowPriority         = 0,
         NormalPriority      = 1,
         HighPriority        = 2,
         RealtimePriority    = 3
     };
Constructor & Destructor Documentation
beast::Process::Process () private
Member Function Documentation
bool beast::Process::isForegroundProcess () static
Returns true if this application process is the one that the user is currently using.
Definition at line 33 of file mac_Threads.mm.
 {
    #if BEAST_MAC
     return [NSApp isActive];
    #else
     return true; // xxx change this if more than one app is ever possible on iOS!
    #endif
 }
bool beast::Process::isRunningUnderDebugger () static
Returns true if this process is being hosted by a debugger.
Definition at line 60 of file bsd_Threads.cpp.
References beast::beast_isRunningUnderDebugger().
Referenced by beast::asio::PeerTest::run().
 {
     return beast_isRunningUnderDebugger();
 }
void beast::Process::lowerPrivilege () static
Lowers the current process's privilege level.
Does nothing if this isn't supported by the current OS, or if process privilege level is fixed.
Definition at line 72 of file bsd_Threads.cpp.
References beast::swapUserAndEffectiveUser().
 { if (geteuid() == 0 && getuid() != 0) swapUserAndEffectiveUser(); }
void beast::Process::makeForegroundProcess () static
Attempts to make the current process the active one. (This is not possible on some platforms).
Definition at line 42 of file mac_Threads.mm.
 {
    #if BEAST_MAC
     [NSApp activateIgnoringOtherApps: YES];
    #endif
 }
bool beast::Process::openDocument (const String & documentURL, const String & parameters) static
Tries to launch the OS's default reader application for a given file or URL.
Definition at line 330 of file bsd_Files.cpp.
References beast::StringArray::add(), beast::File::createFileWithoutCheckingPath(), beast::File::isDirectory(), beast::isFileExecutable(), beast::StringArray::joinIntoString(), beast::numElementsInArray(), beast::String::quoted(), beast::String::replace(), beast::String::toUTF8(), and beast::String::trim().
Referenced by beast::File::startAsProcess().
 {
     String cmdString (fileName.replace (" ", "\\ ",false));
     cmdString << " " << parameters;
     if (    cmdString.startsWithIgnoreCase ("file:")
          || File::createFileWithoutCheckingPath (fileName).isDirectory()
          || ! isFileExecutable (fileName))
     {
         // create a command that tries to launch a bunch of likely browsers
         const char* const browserNames[] = { "xdg-open", "firefox", "seamonkey",
                                              "chrome", "opera", "konqueror" };
         StringArray cmdLines;
         for (int i = 0; i < numElementsInArray (browserNames); ++i)
             cmdLines.add (String (browserNames[i]) + " " + cmdString.trim().quoted());
         cmdString = cmdLines.joinIntoString (" || ");
     }
     const char* const argv[4] = { "/bin/sh", "-c", cmdString.toUTF8(), 0 };
     const int cpid = fork();
     if (cpid == 0)
     {
         setsid();
         // Child process
         execve (argv[0], (char**) argv, environ);
         exit (0);
     }
     return cpid >= 0;
 }
void beast::Process::raisePrivilege () static
Raises the current process's privilege level.
Does nothing if this isn't supported by the current OS, or if process privilege level is fixed.
Definition at line 71 of file bsd_Threads.cpp.
References beast::swapUserAndEffectiveUser().
 { if (geteuid() != 0 && getuid() == 0) swapUserAndEffectiveUser(); }
void beast::Process::setPriority (const ProcessPriority priority) static
Changes the current process's priority.
Parameters
priority the process priority, where 0=low, 1=normal, 2=high, 3=realtime
Definition at line 33 of file bsd_Threads.cpp.
References bassertfalse, HighPriority, LowPriority, NormalPriority, and RealtimePriority.
 {
     const int policy = (prior <= NormalPriority) ? SCHED_OTHER : SCHED_RR;
     const int minp = sched_get_priority_min (policy);
     const int maxp = sched_get_priority_max (policy);
     struct sched_param param;
     switch (prior)
     {
         case LowPriority:
         case NormalPriority:    param.sched_priority = 0; break;
         case HighPriority:      param.sched_priority = minp + (maxp - minp) / 4; break;
         case RealtimePriority:  param.sched_priority = minp + (3 * (maxp - minp) / 4); break;
         default:                bassertfalse; break;
     }
     pthread_setschedparam (pthread_self(), policy, &param);
 }
void beast::Process::terminate () static
Kills the current process immediately.
This is an emergency process terminator that kills the application immediately - it's intended only for use only when something goes horribly wrong.
See Also
BEASTApplication::quit
Definition at line 46 of file posix_SharedCode.h.
Referenced by beast::FatalError::FatalError().
 {
 #if BEAST_ANDROID || BEAST_BSD
    // http://www.unix.com/man-page/FreeBSD/2/_exit/
     ::_exit (EXIT_FAILURE);
 #else
     std::_Exit (EXIT_FAILURE);
 #endif
 }
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_core/threads/Process.h
rippled/src/beast/modules/beast_core/native/bsd_Files.cpp
rippled/src/beast/modules/beast_core/native/bsd_Threads.cpp
rippled/src/beast/modules/beast_core/native/linux_Files.cpp
rippled/src/beast/modules/beast_core/native/linux_Threads.cpp
rippled/src/beast/modules/beast_core/native/mac_Threads.mm
rippled/src/beast/modules/beast_core/native/posix_SharedCode.h
rippled/src/beast/modules/beast_core/native/win32_Files.cpp
rippled/src/beast/modules/beast_core/native/win32_Threads.cpp