rippled: ripple::SHAMapSync_test Class Reference
ripple::SHAMapSync_test Class Reference
Public Member Functions
bool confuseMap (SHAMap &map, int count)
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Static Public Member Functions
static SHAMapItem::pointer makeRandomAS ()
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 738 of file SHAMapSync.cpp.
Member Function Documentation
bool ripple::SHAMapSync_test::confuseMap (SHAMap & map, int count) inline
Definition at line 750 of file SHAMapSync.cpp.
References ripple::SHAMap::addItem(), ripple::SHAMap::delItem(), ripple::SHAMap::getHash(), beast::unit_test::suite::log, and makeRandomAS().
Referenced by run().
     {
         // add a bunch of random states to a map, then remove them
         // map should be the same
         uint256 beforeHash = map.getHash ();
         std::list<uint256> items;
         for (int i = 0; i < count; ++i)
         {
             SHAMapItem::pointer item = makeRandomAS ();
             items.push_back (item->getTag ());
             if (!map.addItem (*item, false, false))
             {
                 log <<
                     "Unable to add item to map";
                 return false;
             }
         }
         for (std::list<uint256>::iterator it = items.begin (); it != items.end (); ++it)
         {
             if (!map.delItem (*it))
             {
                 log <<
                     "Unable to remove item from map";
                 return false;
             }
         }
         if (beforeHash != map.getHash ())
         {
             log <<
                 "Hashes do not match";
             return false;
         }
         return true;
     }
static SHAMapItem::pointer ripple::SHAMapSync_test::makeRandomAS () inline static
Definition at line 741 of file SHAMapSync.cpp.
References ripple::Serializer::add32(), ripple::Serializer::getRIPEMD160(), ripple::Serializer::peekData(), rand, and ripple::uint160::to256().
Referenced by confuseMap(), and run().
     {
         Serializer s;
         for (int d = 0; d < 3; ++d) s.add32 (rand ());
         return boost::make_shared<SHAMapItem> (s.getRIPEMD160 ().to256 (), s.peekData ());
     }
void ripple::SHAMapSync_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 791 of file SHAMapSync.cpp.
References ripple::SHAMap::addItem(), ripple::SHAMap::addKnownNode(), ripple::SHAMap::addRootNode(), ripple::SHAMap::clearSynching(), confuseMap(), ripple::SHAMap::deepCompare(), beast::unit_test::suite::fail(), ripple::get_seconds_clock(), ripple::SHAMap::getMissingNodes(), ripple::SHAMap::getNodeFat(), ripple::SHAMapAddNode::isGood(), ripple::lsFATAL, ripple::lsINFO, ripple::lsTRACE, makeRandomAS(), beast::unit_test::suite::pass(), rand, ripple::SHAMap::setImmutable(), ripple::SHAMap::setSynching(), ripple::smtFREE, ripple::snfWIRE, beast::unit_test::suite::unexpected(), and WriteLog.
     {
         unsigned int seed;
         // VFALCO TODO Replace this with beast::Random
         RAND_pseudo_bytes (reinterpret_cast<unsigned char*> (&seed), sizeof (seed));
         srand (seed);
         FullBelowCache fullBelowCache ("test.full_below",
             get_seconds_clock ());
         SHAMap source (smtFREE, fullBelowCache);
         SHAMap destination (smtFREE, fullBelowCache);
         int items = 10000;
         for (int i = 0; i < items; ++i)
             source.addItem (*makeRandomAS (), false, false);
         unexpected (!confuseMap (source, 500), "ConfuseMap");
         source.setImmutable ();
         std::vector<SHAMapNode> nodeIDs, gotNodeIDs;
         std::list< Blob > gotNodes;
         std::vector<uint256> hashes;
         std::vector<SHAMapNode>::iterator nodeIDIterator;
         std::list< Blob >::iterator rawNodeIterator;
         int passes = 0;
         int nodes = 0;
         destination.setSynching ();
         unexpected (!source.getNodeFat (SHAMapNode (), nodeIDs, gotNodes, (rand () % 2) == 0, (rand () % 2) == 0),
             "GetNodeFat");
         unexpected (gotNodes.size () < 1, "NodeSize");
         unexpected (!destination.addRootNode (*gotNodes.begin (), snfWIRE, nullptr).isGood(), "AddRootNode");
         nodeIDs.clear ();
         gotNodes.clear ();
 #ifdef SMS_DEBUG
         int bytes = 0;
 #endif
         do
         {
             ++passes;
             hashes.clear ();
             // get the list of nodes we know we need
             destination.getMissingNodes (nodeIDs, hashes, 2048, nullptr);
             if (nodeIDs.empty ()) break;
             // get as many nodes as possible based on this information
             for (nodeIDIterator = nodeIDs.begin (); nodeIDIterator != nodeIDs.end (); ++nodeIDIterator)
             {
                 if (!source.getNodeFat (*nodeIDIterator, gotNodeIDs, gotNodes, (rand () % 2) == 0, (rand () % 2) == 0))
                 {
                     WriteLog (lsFATAL, SHAMap) << "GetNodeFat fails";
                     fail ("GetNodeFat");
                 }
                 else
                 {
                     pass ();
                 }
             }
             assert (gotNodeIDs.size () == gotNodes.size ());
             nodeIDs.clear ();
             hashes.clear ();
             if (gotNodeIDs.empty ())
             {
                 fail ("Got Node ID");
             }
             else
             {
                 pass ();
             }
             for (nodeIDIterator = gotNodeIDs.begin (), rawNodeIterator = gotNodes.begin ();
                     nodeIDIterator != gotNodeIDs.end (); ++nodeIDIterator, ++rawNodeIterator)
             {
                 ++nodes;
 #ifdef SMS_DEBUG
                 bytes += rawNodeIterator->size ();
 #endif
                 if (!destination.addKnownNode (*nodeIDIterator, *rawNodeIterator, nullptr).isGood ())
                 {
                     WriteLog (lsTRACE, SHAMap) << "AddKnownNode fails";
                     fail ("AddKnownNode");
                 }
                 else
                 {
                     pass ();
                 }
             }
             gotNodeIDs.clear ();
             gotNodes.clear ();
         }
         while (true);
         destination.clearSynching ();
 #ifdef SMS_DEBUG
         WriteLog (lsINFO, SHAMap) << "SYNCHING COMPLETE " << items << " items, " << nodes << " nodes, " <<
                                   bytes / 1024 << " KB";
 #endif
         if (!source.deepCompare (destination))
         {
             fail ("Deep Compare");
         }
         else
         {
             pass ();
         }
 #ifdef SMS_DEBUG
         WriteLog (lsINFO, SHAMap) << "SHAMapSync test passed: " << items << " items, " <<
                                   passes << " passes, " << nodes << " nodes";
 #endif
     }
The documentation for this class was generated from the following file:
rippled/src/ripple_app/shamap/SHAMapSync.cpp