rippled: beast::detail::TrackedScopedTryLock< Mutex > Class Template Reference
beast::detail::TrackedScopedTryLock< Mutex > Class Template Reference
#include <ScopedLock.h>
Public Member Functions
TrackedScopedTryLock (Mutex const &mutex, char const *fileName, int lineNumber) noexcept
~TrackedScopedTryLock () noexcept
bool owns_lock () const noexcept
bool try_lock (char const *fileName, int lineNumber) noexcept
void unlock () noexcept
Private Attributes
Mutex const & m_mutex
int m_lock_count
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
template<typename Mutex>
class beast::detail::TrackedScopedTryLock< Mutex >
Definition at line 69 of file ScopedLock.h.
Constructor & Destructor Documentation
template<typename Mutex > beast::detail::TrackedScopedTryLock< Mutex >::TrackedScopedTryLock (Mutex const & mutex, char const * fileName, int lineNumber) inline explicit noexcept
Definition at line 72 of file ScopedLock.h.
References beast::detail::TrackedScopedTryLock< Mutex >::try_lock().
         : m_mutex (mutex)
         , m_lock_count (0)
     {
         try_lock (fileName, lineNumber);
     }
template<typename Mutex > beast::detail::TrackedScopedTryLock< Mutex >::~TrackedScopedTryLock () inline noexcept
Definition at line 80 of file ScopedLock.h.
References beast::detail::TrackedScopedTryLock< Mutex >::m_lock_count, and beast::detail::TrackedScopedTryLock< Mutex >::unlock().
     {
         if (m_lock_count > 0)
             unlock ();
     }
Member Function Documentation
template<typename Mutex > bool beast::detail::TrackedScopedTryLock< Mutex >::owns_lock () const inline noexcept
Definition at line 86 of file ScopedLock.h.
References beast::detail::TrackedScopedTryLock< Mutex >::m_lock_count.
     {
         return m_lock_count > 0;
     }
template<typename Mutex > bool beast::detail::TrackedScopedTryLock< Mutex >::try_lock (char const * fileName, int lineNumber) inline noexcept
Definition at line 91 of file ScopedLock.h.
References beast::detail::TrackedScopedTryLock< Mutex >::m_lock_count, and beast::detail::TrackedScopedTryLock< Mutex >::m_mutex.
Referenced by beast::detail::TrackedScopedTryLock< Mutex >::TrackedScopedTryLock().
     {
         bool const success = m_mutex.try_lock (fileName, lineNumber);
         if (success)
             ++m_lock_count;
         return success;
     }
template<typename Mutex > void beast::detail::TrackedScopedTryLock< Mutex >::unlock () inline noexcept
Definition at line 99 of file ScopedLock.h.
References beast::detail::TrackedScopedTryLock< Mutex >::m_lock_count, and beast::detail::TrackedScopedTryLock< Mutex >::m_mutex.
Referenced by beast::detail::TrackedScopedTryLock< Mutex >::~TrackedScopedTryLock().
     {
         m_mutex.unlock ();
         --m_lock_count;
     }
Member Data Documentation
template<typename Mutex > int beast::detail::TrackedScopedTryLock< Mutex >::m_lock_count private
Definition at line 107 of file ScopedLock.h.
Referenced by beast::detail::TrackedScopedTryLock< Mutex >::owns_lock(), beast::detail::TrackedScopedTryLock< Mutex >::try_lock(), beast::detail::TrackedScopedTryLock< Mutex >::unlock(), and beast::detail::TrackedScopedTryLock< Mutex >::~TrackedScopedTryLock().
template<typename Mutex > Mutex const& beast::detail::TrackedScopedTryLock< Mutex >::m_mutex private
Definition at line 106 of file ScopedLock.h.
Referenced by beast::detail::TrackedScopedTryLock< Mutex >::try_lock(), and beast::detail::TrackedScopedTryLock< Mutex >::unlock().
The documentation for this class was generated from the following file:
rippled/src/beast/modules/beast_core/thread/detail/ScopedLock.h