rippled: ripple::CBase58Data Class Reference
ripple::CBase58Data Class Reference
#include <Base58Data.h>
Public Member Functions
bool SetString (const char *psz, unsigned char version, Base58::Alphabet const &alphabet=Base58::getCurrentAlphabet())
bool SetString (const std::string &str, unsigned char version)
std::string ToString () const
int CompareTo (const CBase58Data &b58) const
bool operator== (const CBase58Data &b58) const
bool operator!= (const CBase58Data &b58) const
bool operator<= (const CBase58Data &b58) const
bool operator>= (const CBase58Data &b58) const
bool operator< (const CBase58Data &b58) const
bool operator> (const CBase58Data &b58) const
Protected Member Functions
CBase58Data ()
~CBase58Data ()
void SetData (int nVersionIn, Blob const &vchDataIn)
void SetData (int nVersionIn, const void *pdata, size_t nSize)
void SetData (int nVersionIn, const unsigned char *pbegin, const unsigned char *pend)
Protected Attributes
unsigned char nVersion
Blob vchData
Friends
std::size_t hash_value (const CBase58Data &b58)
Detailed Description
Definition at line 39 of file Base58Data.h.
Constructor & Destructor Documentation
ripple::CBase58Data::CBase58Data () protected
Definition at line 35 of file Base58Data.cpp.
     : nVersion (1)
 {
 }
ripple::CBase58Data::~CBase58Data () protected
Definition at line 40 of file Base58Data.cpp.
References vchData.
 {
     if (!vchData.empty ())
         memset (&vchData[0], 0, vchData.size ());
 }
Member Function Documentation
int ripple::CBase58Data::CompareTo (const CBase58Data & b58) const
Definition at line 102 of file Base58Data.cpp.
References nVersion, and vchData.
Referenced by operator!=(), operator<(), operator<=(), operator==(), operator>(), and operator>=().
 {
     if (nVersion < b58.nVersion) return -1;
     if (nVersion > b58.nVersion) return  1;
     if (vchData < b58.vchData)   return -1;
     if (vchData > b58.vchData)   return  1;
     return 0;
 }
bool ripple::CBase58Data::operator!= (const CBase58Data & b58) const
Definition at line 119 of file Base58Data.cpp.
References CompareTo().
 {
     return CompareTo (b58) != 0;
 }
bool ripple::CBase58Data::operator< (const CBase58Data & b58) const
Definition at line 131 of file Base58Data.cpp.
References CompareTo().
 {
     return CompareTo (b58) <  0;
 }
bool ripple::CBase58Data::operator<= (const CBase58Data & b58) const
Definition at line 123 of file Base58Data.cpp.
References CompareTo().
 {
     return CompareTo (b58) <= 0;
 }
bool ripple::CBase58Data::operator== (const CBase58Data & b58) const
Definition at line 115 of file Base58Data.cpp.
References CompareTo().
 {
     return CompareTo (b58) == 0;
 }
bool ripple::CBase58Data::operator> (const CBase58Data & b58) const
Definition at line 135 of file Base58Data.cpp.
References CompareTo().
 {
     return CompareTo (b58) >  0;
 }
bool ripple::CBase58Data::operator>= (const CBase58Data & b58) const
Definition at line 127 of file Base58Data.cpp.
References CompareTo().
 {
     return CompareTo (b58) >= 0;
 }
void ripple::CBase58Data::SetData (int nVersionIn, Blob const & vchDataIn) protected
Definition at line 46 of file Base58Data.cpp.
References nVersion, and vchData.
Referenced by ripple::RippleAddress::setAccountID(), ripple::RippleAddress::setAccountPrivate(), ripple::RippleAddress::setAccountPublic(), SetData(), ripple::RippleAddress::setGenerator(), ripple::RippleAddress::setNodePrivate(), ripple::RippleAddress::setNodePublic(), and ripple::RippleAddress::setSeed().
 {
     nVersion    = nVersionIn;
     vchData     = vchDataIn;
 }
void ripple::CBase58Data::SetData (int nVersionIn, const void * pdata, size_t nSize) protected
Definition at line 52 of file Base58Data.cpp.
References nVersion, and vchData.
 {
     nVersion = nVersionIn;
     vchData.resize (nSize);
     if (nSize)
         memcpy (&vchData[0], pdata, nSize);
 }
void ripple::CBase58Data::SetData (int nVersionIn, const unsigned char * pbegin, const unsigned char * pend) protected
Definition at line 61 of file Base58Data.cpp.
References SetData().
 {
     SetData (nVersionIn, (void*)pbegin, pend - pbegin);
 }
bool ripple::CBase58Data::SetString (const char * psz, unsigned char version, Base58::Alphabet const & alphabet = Base58::getCurrentAlphabet ())
Definition at line 66 of file Base58Data.cpp.
References ripple::Base58::decodeWithCheck(), nVersion, vchData, and version.
Referenced by ripple::RippleAddress::setAccountID(), ripple::RippleAddress::setAccountPrivate(), ripple::RippleAddress::setAccountPublic(), ripple::RippleAddress::setGenerator(), ripple::RippleAddress::setNodePrivate(), ripple::RippleAddress::setNodePublic(), ripple::RippleAddress::setSeed(), and SetString().
 {
     Blob vchTemp;
     Base58::decodeWithCheck (psz, vchTemp, alphabet);
     if (vchTemp.empty () || vchTemp[0] != version)
     {
         vchData.clear ();
         nVersion = 1;
         return false;
     }
     nVersion = vchTemp[0];
     vchData.resize (vchTemp.size () - 1);
     if (!vchData.empty ())
         memcpy (&vchData[0], &vchTemp[1], vchData.size ());
     memset (&vchTemp[0], 0, vchTemp.size ());
     return true;
 }
bool ripple::CBase58Data::SetString (const std::string & str, unsigned char version)
Definition at line 88 of file Base58Data.cpp.
References SetString(), and version.
 {
     return SetString (str.c_str (), version);
 }
std::string ripple::CBase58Data::ToString () const
Definition at line 93 of file Base58Data.cpp.
References ripple::Base58::encodeWithCheck(), nVersion, and vchData.
Referenced by ripple::RippleAddress::humanAccountID(), ripple::RippleAddress::humanAccountPrivate(), ripple::RippleAddress::humanAccountPublic(), ripple::RippleAddress::humanGenerator(), ripple::RippleAddress::humanNodePrivate(), ripple::RippleAddress::humanNodePublic(), ripple::RippleAddress::humanSeed(), and ripple::PeerImp::json().
 {
     Blob vch (1, nVersion);
     vch.insert (vch.end (), vchData.begin (), vchData.end ());
     return Base58::encodeWithCheck (vch);
 }
Friends And Related Function Documentation
std::size_t hash_value (const CBase58Data & b58) friend
Definition at line 140 of file Base58Data.cpp.
 {
     std::size_t seed = HashMaps::getInstance ().getNonce <size_t> ()
                        + (b58.nVersion * HashMaps::goldenRatio);
     boost::hash_combine (seed, b58.vchData);
     return seed;
 }
Member Data Documentation
unsigned char ripple::CBase58Data::nVersion protected
Definition at line 42 of file Base58Data.h.
Referenced by ripple::RippleAddress::clear(), CompareTo(), ripple::RippleAddress::getAccountID(), ripple::RippleAddress::getAccountPrivate(), ripple::RippleAddress::getAccountPublic(), ripple::RippleAddress::getGenerator(), ripple::RippleAddress::getGeneratorBN(), ripple::RippleAddress::getNodeID(), ripple::RippleAddress::getNodePrivate(), ripple::RippleAddress::getNodePrivateData(), ripple::RippleAddress::getNodePublic(), ripple::RippleAddress::getSeed(), ripple::hash_value(), ripple::RippleAddress::humanAccountID(), ripple::RippleAddress::humanAccountPrivate(), ripple::RippleAddress::humanAccountPublic(), ripple::RippleAddress::humanAddressType(), ripple::RippleAddress::humanGenerator(), ripple::RippleAddress::humanNodePrivate(), ripple::RippleAddress::humanNodePublic(), ripple::RippleAddress::humanSeed(), ripple::RippleAddress::humanSeed1751(), ripple::RippleAddress::isSet(), SetData(), SetString(), and ToString().
Blob ripple::CBase58Data::vchData protected
Definition at line 43 of file Base58Data.h.
Referenced by ripple::RippleAddress::clear(), CompareTo(), ripple::RippleAddress::getAccountID(), ripple::RippleAddress::getAccountPrivate(), ripple::RippleAddress::getAccountPublic(), ripple::RippleAddress::getGenerator(), ripple::RippleAddress::getGeneratorBN(), ripple::RippleAddress::getNodeID(), ripple::RippleAddress::getNodePrivate(), ripple::RippleAddress::getNodePrivateData(), ripple::RippleAddress::getNodePublic(), ripple::RippleAddress::getSeed(), ripple::hash_value(), ripple::RippleAddress::humanAccountID(), SetData(), SetString(), ToString(), and ~CBase58Data().
The documentation for this class was generated from the following files:
rippled/src/ripple_data/crypto/Base58Data.h
rippled/src/ripple_data/crypto/Base58Data.cpp