rippled: beast::detail Namespace Reference
beast::detail Namespace Reference
Namespaces
disabled
zero_helper
Classes
struct SwapBytes
struct SwapBytes< std::int16_t >
struct SwapBytes< std::int32_t >
struct SwapBytes< std::int64_t >
struct basic_abstract_clock_wrapper
struct abstract_clock_wrapper
class seconds_clock_worker
class seconds_clock_thread
struct StartupTimeStaticInitializer
struct apply_const
struct apply_const< T, U, true >
struct is_contiguous
struct is_contiguous< C const >
struct is_contiguous< std::vector< T, Alloc > >
struct is_contiguous< std::basic_string< CharT, Traits, Alloc > >
struct is_contiguous< std::array< T, N > >
struct buffer_view_const_compatible
struct buffer_view_ptr_compatible
struct buffer_view_convertible
struct buffer_view_container_compatible
struct cyclic_iterator_category
struct cyclic_iterator_category< std::forward_iterator_tag >
struct cyclic_iterator_category< std::bidirectional_iterator_tag >
struct cyclic_iterator_category< std::random_access_iterator_tag >
struct cyclic_iterator_base
struct aged_associative_container_extract_t
struct aged_associative_container_extract_t< false >
class aged_container_iterator
class aged_ordered_container
class aged_unordered_container
class hardened_hash_base
class spooky_wrapper
class test_user_type_member
class test_user_type_free
struct DoubleWidthUInt
struct DoubleWidthUInt< std::uint16_t >
struct DoubleWidthUInt< std::uint32_t >
struct CopyConst
struct CopyConst< T const, U >
class ListNode
class ListIterator
struct HashGenerator
class BindHandler1
class BindHandler2
class BindHandler3
class BindHandler4
class BindHandler5
class BindHandler6
class DispatchedHandler
class ScopedWrapper
struct empty_base_optimization_decide
class LeakCheckedBase
class LeakChecked
struct adl_tester2
class TrackedScopedLock
class TrackedScopedTryLock
class TrackedScopedUnlock
class UntrackedScopedLock
class UntrackedScopedTryLock
class UntrackedScopedUnlock
Typedefs
template<class T >
using test_hardened_unordered_set = std::unordered_set< T, hardened_hash< T >>
template<class T >
using test_hardened_unordered_map = std::unordered_map< T, int, hardened_hash< T >>
template<class T >
using test_hardened_unordered_multiset = std::unordered_multiset< T, hardened_hash< T >>
template<class T >
using test_hardened_unordered_multimap = std::unordered_multimap< T, int, hardened_hash< T >>
Functions
static double monotonicCurrentTimeInSeconds ()
static double getStartupTime ()
template<class Hasher , class T >
int hash_one (Hasher &h, T const &t) noexcept
template<class Hasher , class... T, std::size_t... I>
void tuple_hash (Hasher &h, std::tuple< T...> const &t, std::index_sequence< I...>) noexcept
void staticObjectWait (std::size_t n)
int signum (adl_tester2)
template<typename T >
std::string to_string (T const &t)
template<class Handler , class P1 >
BindHandler1< Handler, P1 > bindHandler (Handler handler, P1 const &p1)
template<class Handler , class P1 , class P2 >
BindHandler2< Handler, P1, P2 > bindHandler (Handler handler, P1 const &p1, P2 const &p2)
template<class Handler , class P1 , class P2 , class P3 >
BindHandler3< Handler, P1, P2, P3 > bindHandler (Handler handler, P1 const &p1, P2 const &p2, P3 const &p3)
template<class Handler , class P1 , class P2 , class P3 , class P4 >
BindHandler4< Handler, P1, P2,
P3, P4 > bindHandler (Handler handler, P1 const &p1, P2 const &p2, P3 const &p3, P4 const &p4)
template<class Handler , class P1 , class P2 , class P3 , class P4 , class P5 >
BindHandler5< Handler, P1, P2,
P3, P4, P5 > bindHandler (Handler handler, P1 const &p1, P2 const &p2, P3 const &p3, P4 const &p4, P5 const &p5)
template<class Handler , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
BindHandler6< Handler, P1, P2,
P3, P4, P5, P6 > bindHandler (Handler handler, P1 const &p1, P2 const &p2, P3 const &p3, P4 const &p4, P5 const &p5, P6 const &p6)
Variables
static StartupTimeStaticInitializer startupTimeStaticInitializer
Detailed Description
Wraps a function object so invocation happens during a scoped container lifetime.
Typedef Documentation
template<class T > using beast::detail::test_hardened_unordered_map = typedef std::unordered_map <T, int, hardened_hash <T>>
Definition at line 97 of file hardened_hash.test.cpp.
template<class T > using beast::detail::test_hardened_unordered_multimap = typedef std::unordered_multimap <T, int, hardened_hash <T>>
Definition at line 105 of file hardened_hash.test.cpp.
template<class T > using beast::detail::test_hardened_unordered_multiset = typedef std::unordered_multiset <T, hardened_hash <T>>
Definition at line 101 of file hardened_hash.test.cpp.
template<class T > using beast::detail::test_hardened_unordered_set = typedef std::unordered_set <T, hardened_hash <T>>
Definition at line 93 of file hardened_hash.test.cpp.
Function Documentation
template<class Handler , class P1 > BindHandler1<Handler, P1> beast::detail::bindHandler (Handler handler, P1 const & p1)
Definition at line 60 of file BindHandler.h.
Referenced by beast::detail::DispatchedHandler< Dispatcher, Handler >::operator()().
 {
     return BindHandler1 <Handler, P1> (handler, p1);
 }
template<class Handler , class P1 , class P2 > BindHandler2<Handler, P1, P2> beast::detail::bindHandler (Handler handler, P1 const & p1, P2 const & p2)
Definition at line 98 of file BindHandler.h.
 {
     return BindHandler2 <Handler, P1, P2> (
         handler, p1, p2);
 }
template<class Handler , class P1 , class P2 , class P3 > BindHandler3<Handler, P1, P2, P3> beast::detail::bindHandler (Handler handler, P1 const & p1, P2 const & p2, P3 const & p3)
Definition at line 138 of file BindHandler.h.
 {
     return BindHandler3 <Handler, P1, P2, P3> (
         handler, p1, p2, p3);
 }
template<class Handler , class P1 , class P2 , class P3 , class P4 > BindHandler4<Handler, P1, P2, P3, P4> beast::detail::bindHandler (Handler handler, P1 const & p1, P2 const & p2, P3 const & p3, P4 const & p4)
Definition at line 180 of file BindHandler.h.
 {
     return BindHandler4 <Handler, P1, P2, P3, P4> (
         handler, p1, p2, p3, p4);
 }
template<class Handler , class P1 , class P2 , class P3 , class P4 , class P5 > BindHandler5<Handler, P1, P2, P3, P4, P5> beast::detail::bindHandler (Handler handler, P1 const & p1, P2 const & p2, P3 const & p3, P4 const & p4, P5 const & p5)
Definition at line 222 of file BindHandler.h.
 {
     return BindHandler5 <Handler, P1, P2, P3, P4, P5> (
         handler, p1, p2, p3, p4, p5);
 }
template<class Handler , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > BindHandler6<Handler, P1, P2, P3, P4, P5, P6> beast::detail::bindHandler (Handler handler, P1 const & p1, P2 const & p2, P3 const & p3, P4 const & p4, P5 const & p5, P6 const & p6)
Definition at line 264 of file BindHandler.h.
 {
     return BindHandler6 <Handler, P1, P2, P3, P4, P5, P6> (
         handler, p1, p2, p3, p4, p5, p6);
 }
static double beast::detail::getStartupTime () static
Definition at line 344 of file RelativeTime.cpp.
References monotonicCurrentTimeInSeconds().
Referenced by beast::RelativeTime::fromStartup(), and beast::detail::StartupTimeStaticInitializer::StartupTimeStaticInitializer().
 {
     struct StaticInitializer
     {
         StaticInitializer ()
         {
             when = detail::monotonicCurrentTimeInSeconds();
         }
         double when;
     };
     static StaticInitializer const data;
     return data.when;
 }
template<class Hasher , class T > int beast::detail::hash_one (Hasher & h, T const & t) inline noexcept
Definition at line 380 of file hash_append.h.
References beast::hash_append().
Referenced by tuple_hash().
 {
     hash_append (h, t);
     return 0;
 }
static double beast::detail::monotonicCurrentTimeInSeconds () static
Definition at line 328 of file RelativeTime.cpp.
Referenced by beast::RelativeTime::fromStartup(), and getStartupTime().
 {
     timespec t;
     clock_gettime (CLOCK_MONOTONIC, &t);
     return t.tv_sec + t.tv_nsec / 1000000000.0;
 }
int beast::detail::signum (adl_tester2)
Definition at line 38 of file Zero.test.cpp.
Referenced by beast::detail::zero_helper::call_signum().
 {
     return 0;
 }
void beast::detail::staticObjectWait (std::size_t n)
Definition at line 29 of file StaticObject.cpp.
References beast::Thread::sleep(), and beast::Thread::yield().
Referenced by beast::StaticObject< Object, Tag >::get().
 {
     // Wait for initialization
     Thread::yield ();
     if (n > 10)
         Thread::sleep (1);
     else if (n > 100)
         Thread::sleep (10);
 }
template<typename T > std::string beast::detail::to_string (T const & t)
Definition at line 103 of file iosformat.h.
Referenced by beast::field(), and beast::rfield().
 {
     std::stringstream ss;
     ss << t;
     return ss.str();
 }
template<class Hasher , class... T, std::size_t... I> void beast::detail::tuple_hash (Hasher & h, std::tuple< T...> const & t, std::index_sequence< I...>) inline noexcept
Definition at line 565 of file hash_append.h.
References hash_one().
Referenced by beast::hash_append().
 {
     struct for_each_item {
         for_each_item (...) { }
     };
     for_each_item (hash_one(h, std::get<I>(t))...);
 }
Variable Documentation
StartupTimeStaticInitializer beast::detail::startupTimeStaticInitializer static
Definition at line 370 of file RelativeTime.cpp.