rippled: ripple::SerializedType Class Reference
ripple::SerializedType Class Reference
#include <SerializedTypes.h>
Public Member Functions
SerializedType ()
SerializedType (SField::ref n)
virtual ~SerializedType ()
void setFName (SField::ref n)
SField::ref getFName () const
std::string getName () const
virtual SerializedTypeID getSType () const
std::unique_ptr< SerializedType > clone () const
virtual std::string getFullText () const
virtual std::string getText () const
virtual Json::Value getJson (int) const
virtual void add (Serializer &s) const
virtual bool isEquivalent (const SerializedType &t) const
void addFieldID (Serializer &s) const
SerializedType & operator= (const SerializedType &t)
bool operator== (const SerializedType &t) const
bool operator!= (const SerializedType &t) const
virtual bool isDefault () const
template<class D >
D & downcast ()
template<class D >
D const & downcast () const
Static Public Member Functions
static std::unique_ptr
< SerializedType > deserialize (SField::ref name)
Protected Attributes
SField::ptr fName
Private Member Functions
virtual SerializedType * duplicate () const
Detailed Description
A type which can be exported to a well known binary format.
A SerializedType:
Always a field
Can always go inside an eligible enclosing SerializedType (such as STArray)
Has a field name
Like JSON, a SerializedObject is a basket which has rules on what it can hold.
Definition at line 87 of file SerializedTypes.h.
Constructor & Destructor Documentation
ripple::SerializedType::SerializedType () inline
Definition at line 90 of file SerializedTypes.h.
Referenced by deserialize(), and duplicate().
                       : fName (&sfGeneric)
     {
         ;
     }
ripple::SerializedType::SerializedType (SField::ref n) inline explicit
Definition at line 95 of file SerializedTypes.h.
References fName.
                                           : fName (&n)
     {
         assert (fName);
     }
virtual ripple::SerializedType::~SerializedType () inline virtual
Definition at line 100 of file SerializedTypes.h.
 { }
Member Function Documentation
virtual void ripple::SerializedType::add (Serializer & s) const inline virtual
Reimplemented in ripple::STVector256, ripple::STPathSet, ripple::STVariableLength, ripple::STHash256, ripple::STHash160, ripple::STHash128, ripple::STAmount, ripple::STArray, ripple::STUInt64, ripple::STUInt32, ripple::STUInt16, ripple::STUInt8, and ripple::STObject.
Definition at line 143 of file SerializedTypes.h.
Referenced by ripple::STObject::add().
     {
         ;
     }
void ripple::SerializedType::addFieldID (Serializer & s) const inline
Definition at line 150 of file SerializedTypes.h.
References ripple::Serializer::addFieldID(), and fName.
Referenced by ripple::STObject::add().
     {
         s.addFieldID (fName->fieldType, fName->fieldValue);
     }
std::unique_ptr<SerializedType> ripple::SerializedType::clone () const inline
Definition at line 128 of file SerializedTypes.h.
References duplicate().
Referenced by ripple::STObject::addObject(), and ripple::new_clone().
     {
         return std::unique_ptr<SerializedType> (duplicate ());
     }
static std::unique_ptr<SerializedType> ripple::SerializedType::deserialize (SField::ref name) inline static
Definition at line 102 of file SerializedTypes.h.
References SerializedType().
Referenced by ripple::STObject::makeDeserializedObject().
     {
         return std::unique_ptr<SerializedType> (new SerializedType (name));
     }
template<class D > D& ripple::SerializedType::downcast () inline
Definition at line 172 of file SerializedTypes.h.
     {
         D* ptr = dynamic_cast<D*> (this);
         if (ptr == nullptr)
             throw std::runtime_error ("type mismatch");
         return *ptr;
     }
template<class D > D const& ripple::SerializedType::downcast () const inline
Definition at line 181 of file SerializedTypes.h.
     {
         D const * ptr = dynamic_cast<D const*> (this);
         if (ptr == nullptr)
             throw std::runtime_error ("type mismatch");
         return *ptr;
     }
virtual SerializedType* ripple::SerializedType::duplicate () const inline private virtual
Reimplemented in ripple::STVector256, ripple::STPathSet, ripple::STAccount, ripple::STVariableLength, ripple::STHash256, ripple::STHash160, ripple::STHash128, ripple::STAmount, ripple::STArray, ripple::STUInt64, ripple::STUInt32, ripple::STUInt16, ripple::STObject, ripple::STUInt8, ripple::SerializedTransaction, and ripple::SerializedLedgerEntry.
Definition at line 194 of file SerializedTypes.h.
References fName, and SerializedType().
Referenced by clone().
     {
         return new SerializedType (*fName);
     }
SField::ref ripple::SerializedType::getFName () const inline
Definition at line 115 of file SerializedTypes.h.
References fName.
Referenced by ripple::STObject::add(), ripple::STAmount::addRound(), ripple::LedgerEntrySet::calcRawMeta(), ripple::TransactionMetaSet::getAffectedAccounts(), ripple::TransactionMetaSet::getAffectedNode(), ripple::STObject::getFieldIndex(), ripple::STObject::getJson(), ripple::STUInt8::getJson(), ripple::STUInt16::getJson(), ripple::STArray::getJson(), ripple::STUInt8::getText(), ripple::STUInt16::getText(), ripple::STObject::hasMatchingEntry(), ripple::STObject::makeFieldAbsent(), ripple::STObject::makeFieldPresent(), ripple::STAmount::mulRound(), ripple::STAmount::multiply(), ripple::STAmount::operator+(), ripple::operator+(), ripple::STAmount::operator-(), ripple::operator-(), ripple::STObject::operator==(), ripple::OrderBookDB::processTxn(), ripple::TransactionMetaSet::setAffectedNode(), ripple::STObject::setType(), and ripple::STAmount::subRound().
     {
         return *fName;
     }
std::string ripple::SerializedType::getFullText () const virtual
Reimplemented in ripple::STAmount, ripple::STArray, ripple::STObject, ripple::SerializedLedgerEntry, and ripple::SerializedTransaction.
Definition at line 83 of file SerializedTypes.cpp.
References fName, getSType(), getText(), and ripple::STI_NOTPRESENT.
Referenced by ripple::STObject::getFullText(), isEquivalent(), and ripple::operator<<().
 {
     std::string ret;
     if (getSType () != STI_NOTPRESENT)
     {
         if (fName->hasName ())
         {
             ret = fName->fieldName;
             ret += " = ";
         }
         ret += getText ();
     }
     return ret;
 }
virtual Json::Value ripple::SerializedType::getJson (int) const inline virtual
Reimplemented in ripple::STVector256, ripple::STPathSet, ripple::STAmount, ripple::STArray, ripple::STUInt64, ripple::STUInt32, ripple::STUInt16, ripple::STUInt8, ripple::STObject, ripple::SerializedTransaction, and ripple::SerializedLedgerEntry.
Definition at line 138 of file SerializedTypes.h.
References getText().
Referenced by ripple::TransactionMetaSet::getAffectedAccounts(), and ripple::STObject::getJson().
     {
         return getText ();
     }
std::string ripple::SerializedType::getName () const inline
Definition at line 119 of file SerializedTypes.h.
References fName.
Referenced by ripple::STObject::getJson().
     {
         return fName->fieldName;
     }
virtual SerializedTypeID ripple::SerializedType::getSType () const inline virtual
Reimplemented in ripple::STVector256, ripple::STPathSet, ripple::STAccount, ripple::STVariableLength, ripple::STHash256, ripple::STHash160, ripple::STHash128, ripple::STAmount, ripple::STArray, ripple::STUInt64, ripple::STUInt32, ripple::STUInt16, ripple::STUInt8, ripple::STObject, ripple::SerializedLedgerEntry, and ripple::SerializedTransaction.
Definition at line 124 of file SerializedTypes.h.
References ripple::STI_NOTPRESENT.
Referenced by ripple::STObject::add(), ripple::STObject::getFieldAccount(), ripple::STObject::getFieldAccount160(), ripple::STObject::getFieldAmount(), ripple::STObject::getFieldArray(), ripple::STObject::getFieldH128(), ripple::STObject::getFieldH160(), ripple::STObject::getFieldH256(), ripple::STObject::getFieldPathSet(), ripple::STObject::getFieldU16(), ripple::STObject::getFieldU32(), ripple::STObject::getFieldU64(), ripple::STObject::getFieldU8(), ripple::STObject::getFieldV256(), ripple::STObject::getFieldVL(), ripple::STObject::getFullText(), getFullText(), ripple::STObject::getJson(), isEquivalent(), ripple::STObject::isFieldPresent(), ripple::STObject::makeFieldAbsent(), ripple::STObject::makeFieldPresent(), operator!=(), operator==(), ripple::STObject::operator==(), ripple::STObject::peekFieldObject(), ripple::STObject::setFieldAccount(), ripple::STObject::setFieldAmount(), ripple::STObject::setFieldH128(), ripple::STObject::setFieldH160(), ripple::STObject::setFieldH256(), ripple::STObject::setFieldPathSet(), ripple::STObject::setFieldU16(), ripple::STObject::setFieldU32(), ripple::STObject::setFieldU64(), ripple::STObject::setFieldU8(), ripple::STObject::setFieldV256(), and ripple::STObject::setFieldVL().
     {
         return STI_NOTPRESENT;
     }
virtual std::string ripple::SerializedType::getText () const inline virtual
Reimplemented in ripple::STAccount, ripple::STVariableLength, ripple::STHash256, ripple::STHash160, ripple::STHash128, ripple::STAmount, ripple::STArray, ripple::STUInt64, ripple::STUInt32, ripple::STUInt16, ripple::STUInt8, ripple::STObject, ripple::SerializedLedgerEntry, and ripple::SerializedTransaction.
Definition at line 134 of file SerializedTypes.h.
Referenced by ripple::STObject::getFieldString(), getFullText(), getJson(), and ripple::STObject::getText().
     {
         return std::string ();
     }
virtual bool ripple::SerializedType::isDefault () const inline virtual
Reimplemented in ripple::STVector256, ripple::STPathSet, ripple::STVariableLength, ripple::STHash256, ripple::STHash160, ripple::STHash128, ripple::STAmount, ripple::STArray, ripple::STUInt64, ripple::STUInt32, ripple::STUInt16, ripple::STUInt8, and ripple::STObject.
Definition at line 166 of file SerializedTypes.h.
Referenced by ripple::LedgerEntrySet::calcRawMeta().
     {
         return true;
     }
bool ripple::SerializedType::isEquivalent (const SerializedType & t) const virtual
Reimplemented in ripple::STVector256, ripple::STPathSet, ripple::STVariableLength, ripple::STHash256, ripple::STHash160, ripple::STHash128, ripple::STAmount, ripple::STArray, ripple::STUInt64, ripple::STUInt32, ripple::STUInt16, ripple::STUInt8, and ripple::STObject.
Definition at line 40 of file SerializedTypes.cpp.
References getFullText(), getSType(), ripple::lsDEBUG, ripple::STI_NOTPRESENT, and WriteLog.
Referenced by operator!=(), and operator==().
 {
     assert (getSType () == STI_NOTPRESENT);
     if (t.getSType () == STI_NOTPRESENT)
         return true;
     WriteLog (lsDEBUG, SerializedType) << "notEquiv " << getFullText() << " not STI_NOTPRESENT";
     return false;
 }
bool ripple::SerializedType::operator!= (const SerializedType & t) const inline
Definition at line 161 of file SerializedTypes.h.
References getSType(), and isEquivalent().
     {
         return (getSType () != t.getSType ()) || !isEquivalent (t);
     }
SerializedType & ripple::SerializedType::operator= (const SerializedType & t)
Definition at line 27 of file SerializedTypes.cpp.
References ripple::lsTRACE, ripple::lsWARNING, and WriteLog.
 {
     if ((t.fName != fName) && fName->isUseful () && t.fName->isUseful ())
     {
         WriteLog ((t.getSType () == STI_AMOUNT) ? lsTRACE : lsWARNING, SerializedType) // This is common for amounts
                 << "Caution: " << t.fName->getName () << " not replacing " << fName->getName ();
     }
     if (!fName->isUseful ()) fName = t.fName;
     return *this;
 }
bool ripple::SerializedType::operator== (const SerializedType & t) const inline
Definition at line 157 of file SerializedTypes.h.
References getSType(), and isEquivalent().
     {
         return (getSType () == t.getSType ()) && isEquivalent (t);
     }
void ripple::SerializedType::setFName (SField::ref n) inline
A SerializeType is a field. This sets the name.
Definition at line 110 of file SerializedTypes.h.
References fName.
Referenced by ripple::TransactionMetaSet::setAffectedNode().
     {
         fName = &n;
         assert (fName);
     }
Member Data Documentation
SField::ptr ripple::SerializedType::fName protected
Definition at line 191 of file SerializedTypes.h.
Referenced by addFieldID(), duplicate(), getFName(), ripple::STObject::getFullText(), getFullText(), getName(), SerializedType(), and setFName().
The documentation for this class was generated from the following files:
rippled/src/ripple_data/protocol/SerializedTypes.h
rippled/src/ripple_data/protocol/SerializedTypes.cpp