rippled: ripple::Validators::Store Class Reference
ripple::Validators::Store Class Reference abstract
#include <Store.h>
Public Member Functions
virtual ~Store ()
virtual void insert (SourceDesc &desc)=0
virtual void update (SourceDesc &desc, bool updateFetchResults=false)=0
Protected Member Functions
Store ()
Detailed Description
Abstract persistence for Validators data.
Definition at line 27 of file Store.h.
Constructor & Destructor Documentation
virtual ripple::Validators::Store::~Store () inline virtual
Definition at line 30 of file Store.h.
 { }
ripple::Validators::Store::Store () inline protected
Definition at line 42 of file Store.h.
 { }
Member Function Documentation
virtual void ripple::Validators::Store::insert (SourceDesc & desc) pure virtual
Insert a new SourceDesc to the Store. The caller's SourceDesc will have any available persistent information filled in from the Store.
Implemented in ripple::Validators::StoreSqdb.
Referenced by ripple::Validators::Logic::add().
virtual void ripple::Validators::Store::update (SourceDesc & desc, bool updateFetchResults = false) pure virtual
Update the SourceDesc fixed fields.
Implemented in ripple::Validators::StoreSqdb.
Referenced by ripple::Validators::Logic::expire(), and ripple::Validators::Logic::fetch().
The documentation for this class was generated from the following file:
rippled/src/ripple/validators/impl/Store.h