rippled: beast::unit_test::selector Class Reference
beast::unit_test::selector Class Reference
#include <match.h>
Public Types
enum mode_t {
all, automatch, suite, library,
module, none
}
Public Member Functions
selector (mode_t mode, std::string const &pattern="")
bool operator() (suite_info const &s)
Private Attributes
mode_t m_mode
std::string m_pat
std::string m_library
Detailed Description
Definition at line 29 of file match.h.
Member Enumeration Documentation
enum beast::unit_test::selector::mode_t
Enumerator
all
automatch
suite
library
module
none
Definition at line 32 of file match.h.
     {
         // Run all tests except manual ones
         all,
         // Run tests that match in any field
         automatch,
         // Match on suite
         suite,
         // Match on library
         library,
         // Match on module (used internally)
         module,
         // Match nothing (used internally)
         none
     };
Constructor & Destructor Documentation
beast::unit_test::selector::selector (mode_t mode, std::string const & pattern = "") inline explicit
Definition at line 60 of file match.h.
References all, automatch, and m_mode.
         : m_mode (mode)
         , m_pat (pattern)
     {
         if (m_mode == automatch && pattern.empty())
             m_mode = all;
     }
Member Function Documentation
bool beast::unit_test::selector::operator() (suite_info const & s) inline
Definition at line 69 of file match.h.
References all, automatch, library, beast::unit_test::suite_info::library(), m_library, m_mode, m_pat, beast::unit_test::suite_info::manual(), module, beast::unit_test::suite_info::module(), beast::unit_test::suite_info::name(), and none.
     {
         switch (m_mode)
         {
         case automatch:
             // check suite
             if (m_pat == s.name())
             {
                 m_mode = none;
                 return true;
             }
             // check module
             if (m_pat == s.module())
             {
                 m_mode = module;
                 m_library = s.library();
                 return ! s.manual();
             }
             // check library
             if (m_pat == s.library())
             {
                 m_mode = library;
                 return ! s.manual();
             }
             return false;
         case suite:
             return m_pat == s.name();
         case module:
             return m_pat == s.module() && ! s.manual();
         case library:
             return m_pat == s.library() && ! s.manual();
         case none:
             return false;
         case all:
         default:
             // fall through
             break;
         };
         return ! s.manual();
     }
Member Data Documentation
std::string beast::unit_test::selector::m_library private
Definition at line 56 of file match.h.
Referenced by operator()().
mode_t beast::unit_test::selector::m_mode private
Definition at line 54 of file match.h.
Referenced by operator()(), and selector().
std::string beast::unit_test::selector::m_pat private
Definition at line 55 of file match.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/unit_test/match.h