rippled: ripple::LocalCredentials Class Reference
ripple::LocalCredentials Class Reference
#include <LocalCredentials.h>
Public Member Functions
LocalCredentials ()
void start ()
RippleAddress const & getNodePublic () const
RippleAddress const & getNodePrivate () const
bool dataDelete (std::string const &strKey)
bool dataFetch (std::string const &strKey, std::string &strValue)
bool dataStore (std::string const &strKey, std::string const &strValue)
Private Member Functions
LocalCredentials (LocalCredentials const &)
LocalCredentials & operator= (const LocalCredentials &)
bool nodeIdentityLoad ()
bool nodeIdentityCreate ()
Private Attributes
boost::recursive_mutex mLock
RippleAddress mNodePublicKey
RippleAddress mNodePrivateKey
LedgerIndex mLedger
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
Holds the cryptographic credentials identifying this instance of the server.
Definition at line 26 of file LocalCredentials.h.
Constructor & Destructor Documentation
ripple::LocalCredentials::LocalCredentials ()
Definition at line 22 of file LocalCredentials.cpp.
     : mLedger (0)
 {
 }
ripple::LocalCredentials::LocalCredentials (LocalCredentials const &) private
Member Function Documentation
bool ripple::LocalCredentials::dataDelete (std::string const & strKey)
Definition at line 123 of file LocalCredentials.cpp.
References db, ripple::Database::executeSQL(), ripple::getApp(), ripple::DatabaseCon::getDB(), ripple::Application::getRpcDB(), and ripple::sqlEscape().
 {
     Database* db    = getApp().getRpcDB ()->getDB ();
     DeprecatedScopedLock sl (getApp().getRpcDB ()->getDBLock ());
     return db->executeSQL (str (boost::format ("DELETE FROM RPCData WHERE Key=%s;")
                                 % sqlEscape (strKey)));
 }
bool ripple::LocalCredentials::dataFetch (std::string const & strKey, std::string & strValue)
Definition at line 133 of file LocalCredentials.cpp.
References db, ripple::Database::endIterRows(), ripple::Database::executeSQL(), ripple::getApp(), ripple::Database::getBinary(), ripple::DatabaseCon::getDB(), ripple::Application::getRpcDB(), ripple::sqlEscape(), and ripple::Database::startIterRows().
 {
     Database* db    = getApp().getRpcDB ()->getDB ();
     DeprecatedScopedLock sl (getApp().getRpcDB ()->getDBLock ());
     bool        bSuccess    = false;
     if (db->executeSQL (str (boost::format ("SELECT Value FROM RPCData WHERE Key=%s;")
                              % sqlEscape (strKey))) && db->startIterRows ())
     {
         Blob vucData    = db->getBinary ("Value");
         strValue.assign (vucData.begin (), vucData.end ());
         db->endIterRows ();
         bSuccess    = true;
     }
     return bSuccess;
 }
bool ripple::LocalCredentials::dataStore (std::string const & strKey, std::string const & strValue)
Definition at line 155 of file LocalCredentials.cpp.
References db, ripple::Database::executeSQL(), ripple::getApp(), ripple::DatabaseCon::getDB(), ripple::Application::getRpcDB(), and ripple::sqlEscape().
 {
     Database* db    = getApp().getRpcDB ()->getDB ();
     DeprecatedScopedLock sl (getApp().getRpcDB ()->getDBLock ());
     bool        bSuccess    = false;
     return (db->executeSQL (str (boost::format ("REPLACE INTO RPCData (Key, Value) VALUES (%s,%s);")
                                  % sqlEscape (strKey)
                                  % sqlEscape (strValue)
                                 )));
     return bSuccess;
 }
RippleAddress const& ripple::LocalCredentials::getNodePrivate () const inline
Definition at line 40 of file LocalCredentials.h.
References mNodePrivateKey.
Referenced by ripple::PeerImp::sendHello().
     {
         return mNodePrivateKey;
     }
RippleAddress const& ripple::LocalCredentials::getNodePublic () const inline
Definition at line 35 of file LocalCredentials.h.
References mNodePublicKey.
Referenced by ripple::UniqueNodeListImp::addClusterStatus(), ripple::NetworkOPsImp::checkLastClosedLedger(), and ripple::NetworkOPsImp::getServerInfo().
     {
         return mNodePublicKey;
     }
bool ripple::LocalCredentials::nodeIdentityCreate () private
Definition at line 78 of file LocalCredentials.cpp.
References ripple::RippleAddress::createNodePrivate(), ripple::RippleAddress::createNodePublic(), ripple::RippleAddress::createSeedRandom(), db, ripple::DH_der_gen(), ripple::Database::executeSQL(), ripple::getApp(), ripple::getConfig(), ripple::DatabaseCon::getDB(), ripple::RippleSSLContext::getRawDHParams(), ripple::Application::getWalletDB(), ripple::RippleAddress::humanNodePrivate(), ripple::RippleAddress::humanNodePublic(), ripple::Config::QUIET, and ripple::sqlEscape().
Referenced by start().
 {
     if (!getConfig ().QUIET)
         Log::out() << "NodeIdentity: Creating.";
     //
     // Generate the public and private key
     //
     RippleAddress   naSeed          = RippleAddress::createSeedRandom ();
     RippleAddress   naNodePublic    = RippleAddress::createNodePublic (naSeed);
     RippleAddress   naNodePrivate   = RippleAddress::createNodePrivate (naSeed);
     // Make new key.
 #ifdef CREATE_NEW_DH_PARAMS
     std::string strDh512 = DH_der_gen (512);
 #else
     std::string strDh512 (RippleSSLContext::getRawDHParams (512));
 #endif
 #if 1
     std::string     strDh1024       = strDh512;             // For testing and most cases 512 is fine.
 #else
     std::string     strDh1024       = DH_der_gen (1024);
 #endif
     //
     // Store the node information
     //
     Database* db    = getApp().getWalletDB ()->getDB ();
     DeprecatedScopedLock sl (getApp().getWalletDB ()->getDBLock ());
     db->executeSQL (str (boost::format ("INSERT INTO NodeIdentity (PublicKey,PrivateKey,Dh512,Dh1024) VALUES ('%s','%s',%s,%s);")
                          % naNodePublic.humanNodePublic ()
                          % naNodePrivate.humanNodePrivate ()
                          % sqlEscape (strDh512)
                          % sqlEscape (strDh1024)));
     // XXX Check error result.
     if (!getConfig ().QUIET)
         Log::out() << "NodeIdentity: Created.";
     return true;
 }
bool ripple::LocalCredentials::nodeIdentityLoad () private
Definition at line 48 of file LocalCredentials.cpp.
References db, ripple::Database::endIterRows(), ripple::Database::executeSQL(), ripple::getApp(), ripple::getConfig(), ripple::DatabaseCon::getDB(), ripple::Database::getStr(), ripple::Application::getWalletDB(), ripple::RippleAddress::isValid(), mNodePrivateKey, mNodePublicKey, ripple::Config::NODE_PRIV, ripple::Config::NODE_PUB, ripple::RippleAddress::setNodePrivate(), ripple::RippleAddress::setNodePublic(), and ripple::Database::startIterRows().
Referenced by start().
 {
     Database*   db = getApp().getWalletDB ()->getDB ();
     DeprecatedScopedLock  sl (getApp().getWalletDB ()->getDBLock ());
     bool        bSuccess    = false;
     if (db->executeSQL ("SELECT * FROM NodeIdentity;") && db->startIterRows ())
     {
         std::string strPublicKey, strPrivateKey;
         db->getStr ("PublicKey", strPublicKey);
         db->getStr ("PrivateKey", strPrivateKey);
         mNodePublicKey.setNodePublic (strPublicKey);
         mNodePrivateKey.setNodePrivate (strPrivateKey);
         db->endIterRows ();
         bSuccess    = true;
     }
     if (getConfig ().NODE_PUB.isValid () && getConfig ().NODE_PRIV.isValid ())
     {
         mNodePublicKey = getConfig ().NODE_PUB;
         mNodePrivateKey = getConfig ().NODE_PRIV;
     }
     return bSuccess;
 }
LocalCredentials& ripple::LocalCredentials::operator= (const LocalCredentials &) private
void ripple::LocalCredentials::start ()
Definition at line 27 of file LocalCredentials.cpp.
References ripple::getApp(), ripple::getConfig(), ripple::Application::getUNL(), ripple::RippleAddress::humanNodePublic(), mNodePublicKey, nodeIdentityCreate(), nodeIdentityLoad(), and ripple::UniqueNodeList::start().
Referenced by ripple::ApplicationImp::setup().
 {
     // We need our node identity before we begin networking.
     // - Allows others to identify if they have connected multiple times.
     // - Determines our CAS routing and responsibilities.
     // - This is not our validation identity.
     if (!nodeIdentityLoad ())
     {
         nodeIdentityCreate ();
         if (!nodeIdentityLoad ())
             throw std::runtime_error ("unable to retrieve new node identity.");
     }
     if (!getConfig ().QUIET)
         Log::out() << "NodeIdentity: " << mNodePublicKey.humanNodePublic ();
     getApp().getUNL ().start ();
 }
Member Data Documentation
LedgerIndex ripple::LocalCredentials::mLedger private
Definition at line 65 of file LocalCredentials.h.
boost::recursive_mutex ripple::LocalCredentials::mLock private
Definition at line 60 of file LocalCredentials.h.
RippleAddress ripple::LocalCredentials::mNodePrivateKey private
Definition at line 63 of file LocalCredentials.h.
Referenced by getNodePrivate(), and nodeIdentityLoad().
RippleAddress ripple::LocalCredentials::mNodePublicKey private
Definition at line 62 of file LocalCredentials.h.
Referenced by getNodePublic(), nodeIdentityLoad(), and start().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/main/LocalCredentials.h
rippled/src/ripple_app/main/LocalCredentials.cpp