rippled: beast::asio::PeerTest::Result Class Reference
beast::asio::PeerTest::Result Class Reference
#include <PeerTest.h>
Public Member Functions
Result ()
Result (boost::system::error_code const &ec, String const &prefix="")
Result (std::exception const &e, String const &prefix="")
bool operator== (Result const &other) const noexcept
bool operator!= (Result const &other) const noexcept
bool failed () const noexcept
bool timedout () const noexcept
String message () const noexcept
bool report (unit_test::suite &suite, bool reportPassingTests=false) const
Private Attributes
boost::system::error_code m_ec
String m_message
Detailed Description
Holds the test results for one peer.
Definition at line 45 of file PeerTest.h.
Constructor & Destructor Documentation
beast::asio::PeerTest::Result::Result ()
Default constructor indicates the test was skipped.
Definition at line 23 of file PeerTest.cpp.
     : m_ec (TestPeerBasics::make_error (TestPeerBasics::errc::skipped))
     , m_message (m_ec.message ())
 {
 }
beast::asio::PeerTest::Result::Result (boost::system::error_code const & ec, String const & prefix = "") explicit
Construct from an error code. The prefix is prepended to the error message.
Definition at line 29 of file PeerTest.cpp.
     : m_ec (ec)
     , m_message ((prefix == String::empty) ? ec.message ()
                 : prefix + ": " + ec.message ())
 {
 }
beast::asio::PeerTest::Result::Result (std::exception const & e, String const & prefix = "") explicit
Definition at line 36 of file PeerTest.cpp.
     : m_ec (TestPeerBasics::make_error (TestPeerBasics::errc::exceptioned))
     , m_message ((prefix == String::empty) ? e.what ()
                 : prefix + ": " + e.what ())
 {
 }
Member Function Documentation
bool beast::asio::PeerTest::Result::failed () const noexcept
Returns true if the peer failed.
Definition at line 53 of file PeerTest.cpp.
References beast::asio::TestPeerBasics::failure().
 {
     return TestPeerBasics::failure (m_ec);
 }
String beast::asio::PeerTest::Result::message () const noexcept
Provides a descriptive message. This is suitable to pass to suite::fail.
Definition at line 63 of file PeerTest.cpp.
 {
     return m_message;
 }
bool beast::asio::PeerTest::Result::operator!= (Result const & other) const noexcept
Definition at line 48 of file PeerTest.cpp.
 {
     return m_ec != other.m_ec;
 }
bool beast::asio::PeerTest::Result::operator== (Result const & other) const noexcept
Returns true if the error codes match (message is ignored).
Definition at line 43 of file PeerTest.cpp.
 {
     return m_ec == other.m_ec;
 }
bool beast::asio::PeerTest::Result::report (unit_test::suite & suite, bool reportPassingTests = false) const
Report the result to a testsuite. A return value of true indicates success.
Definition at line 68 of file PeerTest.cpp.
References beast::unit_test::suite::expect(), and beast::unit_test::suite::log.
 {
     bool const success = suite.expect (! failed (),
         message ().toStdString());
     if (reportPassingTests && success)
         suite.log <<
             "pass " + message().toStdString();
     return success;
 }
bool beast::asio::PeerTest::Result::timedout () const noexcept
Convenience for determining if the peer timed out.
Definition at line 58 of file PeerTest.cpp.
References beast::asio::TestPeerBasics::make_error(), and beast::asio::TestPeerBasics::errc::timeout.
 {
     return m_ec == TestPeerBasics::make_error (TestPeerBasics::errc::timeout);
 }
Member Data Documentation
boost::system::error_code beast::asio::PeerTest::Result::m_ec private
Definition at line 83 of file PeerTest.h.
String beast::asio::PeerTest::Result::m_message private
Definition at line 84 of file PeerTest.h.
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_asio/tests/PeerTest.h
rippled/src/beast/modules/beast_asio/tests/PeerTest.cpp