rippled: ripple::RPCSubImp Class Reference
ripple::RPCSubImp Class Reference
Public Member Functions
RPCSubImp (InfoSub::Source &source, boost::asio::io_service &io_service, JobQueue &jobQueue, const std::string &strUrl, const std::string &strUsername, const std::string &strPassword)
~RPCSubImp ()
void send (const Json::Value &jvObj, bool broadcast)
void setUsername (const std::string &strUsername)
void setPassword (const std::string &strPassword)
Private Types
enum { eventQueueMax = 32 }
Private Member Functions
void sendThread ()
Private Attributes
boost::asio::io_service & m_io_service
JobQueue & m_jobQueue
std::string mUrl
std::string mIp
int mPort
bool mSSL
std::string mUsername
std::string mPassword
std::string mPath
int mSeq
bool mSending
std::deque< std::pair< int,
Json::Value > > mDeque
Additional Inherited Members
Public Types inherited from ripple::RPCSub
typedef boost::shared_ptr< RPCSub > pointer
typedef pointer const & ref
Static Public Member Functions inherited from ripple::RPCSub
static pointer New (InfoSub::Source &source, boost::asio::io_service &io_service, JobQueue &jobQueue, const std::string &strUrl, const std::string &strUsername, const std::string &strPassword)
Protected Types inherited from ripple::InfoSub
typedef RippleMutex LockType
typedef std::lock_guard< LockType > ScopedLockType
Protected Member Functions inherited from ripple::RPCSub
RPCSub (InfoSub::Source &source)
Protected Attributes inherited from ripple::InfoSub
LockType mLock
Detailed Description
Definition at line 25 of file RPCSub.cpp.
Member Enumeration Documentation
anonymous enum private
Enumerator
eventQueueMax
Definition at line 173 of file RPCSub.cpp.
     {
         eventQueueMax = 32
     };
Constructor & Destructor Documentation
ripple::RPCSubImp::RPCSubImp (InfoSub::Source & source, boost::asio::io_service & io_service, JobQueue & jobQueue, const std::string & strUrl, const std::string & strUsername, const std::string & strPassword) inline
Definition at line 30 of file RPCSub.cpp.
References ripple::lsINFO, ripple::parseUrl(), and WriteLog.
         : RPCSub (source)
         , m_io_service (io_service)
         , m_jobQueue (jobQueue)
         , mUrl (strUrl)
         , mSSL (false)
         , mUsername (strUsername)
         , mPassword (strPassword)
         , mSending (false)
     {
         std::string strScheme;
         if (!parseUrl (strUrl, strScheme, mIp, mPort, mPath))
         {
             throw std::runtime_error ("Failed to parse url.");
         }
         else if (strScheme == "https")
         {
             mSSL    = true;
         }
         else if (strScheme != "http")
         {
             throw std::runtime_error ("Only http and https is supported.");
         }
         mSeq    = 1;
         if (mPort < 0)
             mPort   = mSSL ? 443 : 80;
         WriteLog (lsINFO, RPCSub) <<
             "RPCCall::fromNetwork sub: ip=" << mIp <<
             " port=" << mPort <<
             " ssl= "<< (mSSL ? "yes" : "no") <<
             " path='" << mPath << "'";
     }
ripple::RPCSubImp::~RPCSubImp () inline
Definition at line 69 of file RPCSub.cpp.
     {
     }
Member Function Documentation
void ripple::RPCSubImp::send (const Json::Value & jvObj, bool broadcast) inline virtual
Implements ripple::InfoSub.
Definition at line 73 of file RPCSub.cpp.
References BIND_TYPE, ripple::jtCLIENT, ripple::lsDEBUG, ripple::lsINFO, ripple::lsWARNING, sendThread(), and WriteLog.
     {
         ScopedLockType sl (mLock);
         if (mDeque.size () >= eventQueueMax)
         {
             // Drop the previous event.
             WriteLog (lsWARNING, RPCSub) << "RPCCall::fromNetwork drop";
             mDeque.pop_back ();
         }
         WriteLog (broadcast ? lsDEBUG : lsINFO, RPCSub) <<
             "RPCCall::fromNetwork push: " << jvObj;
         mDeque.push_back (std::make_pair (mSeq++, jvObj));
         if (!mSending)
         {
             // Start a sending thread.
             mSending    = true;
             WriteLog (lsINFO, RPCSub) << "RPCCall::fromNetwork start";
             m_jobQueue.addJob (
                 jtCLIENT, "RPCSub::sendThread", BIND_TYPE (&RPCSubImp::sendThread, this));
         }
     }
void ripple::RPCSubImp::sendThread () inline private
Definition at line 117 of file RPCSub.cpp.
References ripple::RPCCall::fromNetwork(), ripple::lsINFO, and WriteLog.
Referenced by send().
     {
         Json::Value jvEvent;
         bool bSend;
         do
         {
             {
                 // Obtain the lock to manipulate the queue and change sending.
                 ScopedLockType sl (mLock);
                 if (mDeque.empty ())
                 {
                     mSending    = false;
                     bSend       = false;
                 }
                 else
                 {
                     std::pair<int, Json::Value> pEvent  = mDeque.front ();
                     mDeque.pop_front ();
                     jvEvent     = pEvent.second;
                     jvEvent["seq"]  = pEvent.first;
                     bSend       = true;
                 }
             }
             // Send outside of the lock.
             if (bSend)
             {
                 // XXX Might not need this in a try.
                 try
                 {
                     WriteLog (lsINFO, RPCSub) << "RPCCall::fromNetwork: " << mIp;
                     RPCCall::fromNetwork (
                         m_io_service,
                         mIp, mPort,
                         mUsername, mPassword,
                         mPath, "event",
                         jvEvent,
                         mSSL);
                 }
                 catch (const std::exception& e)
                 {
                     WriteLog (lsINFO, RPCSub) << "RPCCall::fromNetwork exception: " << e.what ();
                 }
             }
         }
         while (bSend);
     }
void ripple::RPCSubImp::setPassword (const std::string & strPassword) inline virtual
Implements ripple::RPCSub.
Definition at line 108 of file RPCSub.cpp.
     {
         ScopedLockType sl (mLock);
         mPassword = strPassword;
     }
void ripple::RPCSubImp::setUsername (const std::string & strUsername) inline virtual
Implements ripple::RPCSub.
Definition at line 101 of file RPCSub.cpp.
     {
         ScopedLockType sl (mLock);
         mUsername = strUsername;
     }
Member Data Documentation
boost::asio::io_service& ripple::RPCSubImp::m_io_service private
Definition at line 178 of file RPCSub.cpp.
JobQueue& ripple::RPCSubImp::m_jobQueue private
Definition at line 179 of file RPCSub.cpp.
std::deque<std::pair<int, Json::Value> > ripple::RPCSubImp::mDeque private
Definition at line 193 of file RPCSub.cpp.
std::string ripple::RPCSubImp::mIp private
Definition at line 182 of file RPCSub.cpp.
std::string ripple::RPCSubImp::mPassword private
Definition at line 186 of file RPCSub.cpp.
std::string ripple::RPCSubImp::mPath private
Definition at line 187 of file RPCSub.cpp.
int ripple::RPCSubImp::mPort private
Definition at line 183 of file RPCSub.cpp.
bool ripple::RPCSubImp::mSending private
Definition at line 191 of file RPCSub.cpp.
int ripple::RPCSubImp::mSeq private
Definition at line 189 of file RPCSub.cpp.
bool ripple::RPCSubImp::mSSL private
Definition at line 184 of file RPCSub.cpp.
std::string ripple::RPCSubImp::mUrl private
Definition at line 181 of file RPCSub.cpp.
std::string ripple::RPCSubImp::mUsername private
Definition at line 185 of file RPCSub.cpp.
The documentation for this class was generated from the following file:
rippled/src/ripple_net/rpc/RPCSub.cpp