rippled: beast::ServiceQueueType< Allocator > Class Template Reference
beast::ServiceQueueType< Allocator > Class Template Reference
#include <ServiceQueue.h>
Classes
class ItemType
Public Types
typedef Allocator allocator_type
Public Member Functions
ServiceQueueType (std::size_t expectedConcurrency=1, Allocator alloc=Allocator())
~ServiceQueueType ()
allocator_type get_allocator () const
bool is_service_thread () const
template<typename Handler >
void dispatch (BEAST_MOVE_ARG(Handler) handler)
template<typename Handler >
void post (BEAST_MOVE_ARG(Handler) handler)
template<typename Handler >
detail::DispatchedHandler
< ServiceQueueType &, Handler > wrap (BEAST_MOVE_ARG(Handler) handler)
std::size_t poll ()
std::size_t poll_one ()
std::size_t run ()
std::size_t run_one ()
void stop ()
bool stopped () const
void reset ()
Public Member Functions inherited from beast::ServiceQueueBase
ServiceQueueBase ()
~ServiceQueueBase ()
std::size_t poll ()
std::size_t poll_one ()
std::size_t run ()
std::size_t run_one ()
void stop ()
bool stopped () const
void reset ()
Private Member Functions
std::size_t dequeue ()
Waiter * new_waiter ()
Private Attributes
Allocator m_alloc
Additional Inherited Members
Protected Types inherited from beast::ServiceQueueBase
typedef SharedData< State > SharedState
Protected Member Functions inherited from beast::ServiceQueueBase
void wait ()
virtual void enqueue (Item *item)
bool empty ()
Protected Attributes inherited from beast::ServiceQueueBase
SharedState m_state
Atomic< int > m_stopped
Static Protected Attributes inherited from beast::ServiceQueueBase
static ThreadLocalValue
< ServiceQueueBase * > s_service
Detailed Description
template<class Allocator = std::allocator <char>>
class beast::ServiceQueueType< Allocator >
A queue for disatching function calls on other threads. Handlers are guaranteed to be called only from threads that are currently calling run, run_one, poll, or poll_one.
Definition at line 409 of file ServiceQueue.h.
Member Typedef Documentation
template<class Allocator = std::allocator <char>> typedef Allocator beast::ServiceQueueType< Allocator >::allocator_type
Definition at line 431 of file ServiceQueue.h.
Constructor & Destructor Documentation
template<class Allocator = std::allocator <char>> beast::ServiceQueueType< Allocator >::ServiceQueueType (std::size_t expectedConcurrency = 1, Allocator alloc = Allocator()) inline explicit
Definition at line 433 of file ServiceQueue.h.
References beast::ServiceQueueType< Allocator >::m_alloc, and beast::ServiceQueueBase::m_state.
         : m_alloc (alloc)
     {
         typename Allocator::template rebind <Waiter>::other a (m_alloc);
         SharedState::Access state (m_state);
         while (expectedConcurrency--)
             state->unused.push_front (
                 *new (a.allocate (1)) Waiter);
     }
template<class Allocator = std::allocator <char>> beast::ServiceQueueType< Allocator >::~ServiceQueueType () inline
Definition at line 444 of file ServiceQueue.h.
References bassert, beast::ServiceQueueType< Allocator >::m_alloc, and beast::ServiceQueueBase::m_state.
     {
         SharedState::Access state (m_state);
         // Must be empty
         //bassert (state->handlers.empty());
         // Cannot destroy while threads are waiting
         bassert (state->waiting.empty());
         typename Allocator::template rebind <Waiter>::other a (m_alloc);
         while (! state->unused.empty ())
         {
             Waiter* const waiter (&state->unused.front ());
             state->unused.pop_front ();
             a.destroy (waiter);
             a.deallocate (waiter, 1);
         }
     }
Member Function Documentation
template<class Allocator = std::allocator <char>> std::size_t beast::ServiceQueueType< Allocator >::dequeue () inline private virtual
Implements beast::ServiceQueueBase.
Definition at line 584 of file ServiceQueue.h.
References beast::ServiceQueueType< Allocator >::m_alloc, beast::ServiceQueueBase::m_state, beast::ServiceQueueBase::Item::size(), beast::ServiceQueueType< Allocator >::stopped(), and beast::ServiceQueueBase::Item::~Item().
     {
         if (stopped())
             return 0;
         Item* item (nullptr);
         {
             SharedState::Access state (m_state);
             if (state->handlers.empty())
                 return 0;
             item = &state->handlers.front();
             state->handlers.erase (
                 state->handlers.iterator_to (*item));
         }
         (*item)();
         typename Allocator::template rebind <std::uint8_t>::other a (m_alloc);
         std::size_t const size (item->size());
         item->~Item();
         a.deallocate (reinterpret_cast<std::uint8_t*>(item), size);
         return 1;
     }
template<class Allocator = std::allocator <char>> template<typename Handler > void beast::ServiceQueueType< Allocator >::dispatch (BEAST_MOVE_ARG(Handler) handler) inline
Run the handler on a service thread. If the current thread of execution is a service thread then this function wil dispatch the handler on the caller's thread before returning. The function signature of the handler must be:
void handler();
Definition at line 487 of file ServiceQueue.h.
References BEAST_MOVE_CAST, beast::ServiceQueueBase::enqueue(), beast::ServiceQueueType< Allocator >::is_service_thread(), and beast::ServiceQueueType< Allocator >::m_alloc.
Referenced by ripple::PeerFinder::ManagerImp::addFallbackStrings(), ripple::PeerFinder::ManagerImp::addFixedPeer(), ripple::Validators::ManagerImp::addSource(), ripple::Validators::ManagerImp::addStaticSource(), ripple::Validators::ManagerImp::ledgerClosed(), ripple::PeerFinder::ManagerImp::onDeadlineTimer(), ripple::Validators::ManagerImp::onDeadlineTimer(), ripple::Validators::ManagerImp::onStart(), ripple::PeerFinder::ManagerImp::onStop(), ripple::Validators::ManagerImp::onStop(), ripple::Validators::ManagerImp::receiveValidation(), ripple::PeerFinder::ManagerImp::setConfig(), and beast::ServiceQueue_test::testThreads().
     {
         if (is_service_thread())
         {
             handler();
         }
         else
         {
             typename Allocator::template rebind <ItemType <Handler> >::other a (m_alloc);
             enqueue (new (a.allocate (1))
                 ItemType <Handler> (BEAST_MOVE_CAST(Handler)(handler)));
         }
     }
template<class Allocator = std::allocator <char>> allocator_type beast::ServiceQueueType< Allocator >::get_allocator () const inline
Returns the allocator associated with the container.
Definition at line 465 of file ServiceQueue.h.
References beast::ServiceQueueType< Allocator >::m_alloc.
     {
         return m_alloc;
     }
template<class Allocator = std::allocator <char>> bool beast::ServiceQueueType< Allocator >::is_service_thread () const inline
Returns true if the current thread is processing events. If the current thread of execution is inside a call to run, run_one, poll, or poll_one, this function returns true.
Definition at line 474 of file ServiceQueue.h.
References beast::ServiceQueueBase::s_service.
Referenced by beast::ServiceQueueType< Allocator >::dispatch().
         { return s_service.get() == this; }
template<class Allocator = std::allocator <char>> Waiter* beast::ServiceQueueType< Allocator >::new_waiter () inline private virtual
Implements beast::ServiceQueueBase.
Definition at line 610 of file ServiceQueue.h.
References beast::ServiceQueueType< Allocator >::m_alloc.
     {
         typename Allocator::template rebind <Waiter>::other a (m_alloc);
         return new (a.allocate (1)) Waiter;
     }
template<class Allocator = std::allocator <char>> std::size_t beast::ServiceQueueType< Allocator >::poll () inline
Run the event loop to execute ready handlers. This runs handlers that are ready to run, without blocking, until there are no more handlers ready or the service queue has been stopped.
Returns
The number of handlers that were executed.
Definition at line 531 of file ServiceQueue.h.
References beast::ServiceQueueBase::poll().
Referenced by ripple::SiteFiles::ManagerImp::run().
         { return ServiceQueueBase::poll(); }
template<class Allocator = std::allocator <char>> std::size_t beast::ServiceQueueType< Allocator >::poll_one () inline
Run the event loop to execute at most one ready handler. This will run zero or one handlers, without blocking, depending on whether or not there is handler immediately ready to run.
Returns
The number of handlers that were executed.
Definition at line 539 of file ServiceQueue.h.
References beast::ServiceQueueBase::poll_one().
         { return ServiceQueueBase::poll_one(); }
template<class Allocator = std::allocator <char>> template<typename Handler > void beast::ServiceQueueType< Allocator >::post (BEAST_MOVE_ARG(Handler) handler) inline
Request the handler to run on a service thread. This returns immediately, even if the current thread of execution is a service thread. The function signature of the handler must be:
void handler();
Definition at line 510 of file ServiceQueue.h.
References BEAST_MOVE_CAST, beast::ServiceQueueBase::enqueue(), and beast::ServiceQueueType< Allocator >::m_alloc.
Referenced by ripple::SiteFiles::ManagerImp::addListener(), ripple::SiteFiles::ManagerImp::addURL(), and ripple::SiteFiles::ManagerImp::removeListener().
     {
         typename Allocator::template rebind <ItemType <Handler> >::other a (m_alloc);
         enqueue (new (a.allocate (1))
             ItemType <Handler> (BEAST_MOVE_CAST(Handler)(handler)));
     }
template<class Allocator = std::allocator <char>> void beast::ServiceQueueType< Allocator >::reset () inline
Reset the queue after a stop. This allows the event loop to be restarted. This may not be called while there are any threads currently executing the run, run_one, poll, or poll_one functions, or undefined behavior will result.
Definition at line 577 of file ServiceQueue.h.
References beast::ServiceQueueBase::reset().
Referenced by ripple::SiteFiles::ManagerImp::run().
         { return ServiceQueueBase::reset(); }
template<class Allocator = std::allocator <char>> std::size_t beast::ServiceQueueType< Allocator >::run () inline
Runs the queue's processing loop. The current thread of execution becomes a service thread. This call blocks until there is no more work remaining.
Returns
The number of handlers that were executed.
Definition at line 547 of file ServiceQueue.h.
References beast::ServiceQueueBase::run().
Referenced by ripple::SiteFiles::ManagerImp::run().
         { return ServiceQueueBase::run(); }
template<class Allocator = std::allocator <char>> std::size_t beast::ServiceQueueType< Allocator >::run_one () inline
Runs the queue's processing loop to execute at most one handler.
Returns
The number of handlers that were executed.
Definition at line 553 of file ServiceQueue.h.
References beast::ServiceQueueBase::run_one().
Referenced by beast::ServiceQueue_test::ServiceThread::run(), ripple::PeerFinder::ManagerImp::run(), and ripple::Validators::ManagerImp::run().
         { return ServiceQueueBase::run_one(); }
template<class Allocator = std::allocator <char>> void beast::ServiceQueueType< Allocator >::stop () inline
Stop the queue's processing loop. All threads executing run or run_one will return as soon as possible. Future calls to run, run_one, poll, or poll_one will return immediately until reset is called.
See Also
reset
Definition at line 562 of file ServiceQueue.h.
References beast::ServiceQueueBase::stop().
Referenced by ripple::SiteFiles::ManagerImp::onStop().
         { return ServiceQueueBase::stop(); }
template<class Allocator = std::allocator <char>> bool beast::ServiceQueueType< Allocator >::stopped () const inline
Returns true if the queue has been stopped. When a queue is stopped, calls to run, run_one, poll, or poll_one will return immediately without invoking any handlers.
Definition at line 569 of file ServiceQueue.h.
References beast::ServiceQueueBase::stopped().
Referenced by beast::ServiceQueueType< Allocator >::dequeue().
         { return ServiceQueueBase::stopped(); }
template<class Allocator = std::allocator <char>> template<typename Handler > detail::DispatchedHandler<ServiceQueueType&, Handler> beast::ServiceQueueType< Allocator >::wrap (BEAST_MOVE_ARG(Handler) handler) inline
Return a new handler that dispatches the wrapped handler on the queue.
Definition at line 519 of file ServiceQueue.h.
References BEAST_MOVE_CAST.
Referenced by ripple::PeerFinder::CheckerAdapter::Handler::operator()().
     {
         return detail::DispatchedHandler <ServiceQueueType&, Handler> (
             *this, BEAST_MOVE_CAST(Handler)(handler));
     }
Member Data Documentation
template<class Allocator = std::allocator <char>> Allocator beast::ServiceQueueType< Allocator >::m_alloc private
Definition at line 616 of file ServiceQueue.h.
Referenced by beast::ServiceQueueType< Allocator >::dequeue(), beast::ServiceQueueType< Allocator >::dispatch(), beast::ServiceQueueType< Allocator >::get_allocator(), beast::ServiceQueueType< Allocator >::new_waiter(), beast::ServiceQueueType< Allocator >::post(), beast::ServiceQueueType< Allocator >::ServiceQueueType(), and beast::ServiceQueueType< Allocator >::~ServiceQueueType().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/threads/ServiceQueue.h