rippled: ripple::TransactionMaster Class Reference
ripple::TransactionMaster Class Reference
#include <TransactionMaster.h>
Public Member Functions
TransactionMaster ()
Transaction::pointer fetch (uint256 const &, bool checkDisk)
SerializedTransaction::pointer fetch (SHAMapItem::ref item, SHAMapTreeNode::TNType type, bool checkDisk, std::uint32_t uCommitLedger)
bool inLedger (uint256 const &hash, std::uint32_t ledger)
bool canonicalize (Transaction::pointer *pTransaction)
void sweep (void)
Private Attributes
TaggedCache< uint256, Transaction > mCache
Detailed Description
Definition at line 27 of file TransactionMaster.h.
Constructor & Destructor Documentation
ripple::TransactionMaster::TransactionMaster ()
Definition at line 22 of file TransactionMaster.cpp.
     : mCache ("TransactionCache", 65536, 1800, get_seconds_clock (),
         LogPartition::getJournal <TaggedCacheLog> ())
 {
 }
Member Function Documentation
bool ripple::TransactionMaster::canonicalize (Transaction::pointer * pTransaction)
Definition at line 92 of file TransactionMaster.cpp.
References mCache, and tid.
Referenced by ripple::Ledger::getTransaction(), ripple::NetworkOPsImp::processTransactionCb(), and ripple::NetworkOPsImp::runTransactionQueue().
 {
     Transaction::pointer txn (*pTransaction);
     uint256 tid = txn->getID ();
     if (!tid)
         return false;
     // VFALCO NOTE canonicalize can change the value of txn!
     if (mCache.canonicalize (tid, txn))
     {
         *pTransaction = txn;
         return true;
     }
     // VFALCO NOTE I am unsure if this is necessary but better safe than sorry.
     *pTransaction = txn;
     return false;
 }
Transaction::pointer ripple::TransactionMaster::fetch (uint256 const & txnID, bool checkDisk)
Definition at line 39 of file TransactionMaster.cpp.
References ripple::Transaction::load(), and mCache.
Referenced by ripple::RPCHandler::doTx(), fetch(), ripple::Ledger::getTransaction(), ripple::ConsensusTransSetSF::haveNode(), and ripple::NetworkOPsImp::runTransactionQueue().
 {
     Transaction::pointer txn = mCache.fetch (txnID);
     if (!checkDisk || txn)
         return txn;
     txn = Transaction::load (txnID);
     if (!txn)
         return txn;
     mCache.canonicalize (txnID, txn);
     return txn;
 }
SerializedTransaction::pointer ripple::TransactionMaster::fetch (SHAMapItem::ref item, SHAMapTreeNode::TNType type, bool checkDisk, std::uint32_t uCommitLedger)
Definition at line 56 of file TransactionMaster.cpp.
References ripple::COMMITTED, fetch(), ripple::getApp(), ripple::Application::getMasterTransaction(), ripple::Serializer::getVL(), ripple::Serializer::modData(), ripple::SHAMapTreeNode::tnTRANSACTION_MD, and ripple::SHAMapTreeNode::tnTRANSACTION_NM.
 {
     SerializedTransaction::pointer  txn;
     Transaction::pointer            iTx = getApp().getMasterTransaction ().fetch (item->getTag (), false);
     if (!iTx)
     {
         if (type == SHAMapTreeNode::tnTRANSACTION_NM)
         {
             SerializerIterator sit (item->peekSerializer ());
             txn = boost::make_shared<SerializedTransaction> (boost::ref (sit));
         }
         else if (type == SHAMapTreeNode::tnTRANSACTION_MD)
         {
             Serializer s;
             int length;
             item->peekSerializer ().getVL (s.modData (), 0, length);
             SerializerIterator sit (s);
             txn = boost::make_shared<SerializedTransaction> (boost::ref (sit));
         }
     }
     else
     {
         if (uCommitLedger)
             iTx->setStatus (COMMITTED, uCommitLedger);
         txn = iTx->getSTransaction ();
     }
     return txn;
 }
bool ripple::TransactionMaster::inLedger (uint256 const & hash, std::uint32_t ledger)
Definition at line 28 of file TransactionMaster.cpp.
References ripple::COMMITTED, and mCache.
Referenced by ripple::Ledger::saveValidatedLedger().
 {
     Transaction::pointer txn = mCache.fetch (hash);
     if (!txn)
         return false;
     txn->setStatus (COMMITTED, ledger);
     return true;
 }
void ripple::TransactionMaster::sweep (void)
Definition at line 113 of file TransactionMaster.cpp.
References mCache.
Referenced by ripple::ApplicationImp::doSweep().
 {
     mCache.sweep ();
 }
Member Data Documentation
TaggedCache<uint256, Transaction> ripple::TransactionMaster::mCache private
Definition at line 42 of file TransactionMaster.h.
Referenced by canonicalize(), fetch(), inLedger(), and sweep().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/tx/TransactionMaster.h
rippled/src/ripple_app/tx/TransactionMaster.cpp