rippled: beast::hardened_hash_test Class Reference
beast::hardened_hash_test Class Reference
Public Member Functions
template<class T >
void check ()
template<template< class T > class U>
void check_user_type ()
template<template< class T > class C>
void check_container ()
void test_user_types ()
void test_containers ()
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 190 of file hardened_hash.test.cpp.
Member Function Documentation
template<class T > void beast::hardened_hash_test::check () inline
Definition at line 196 of file hardened_hash.test.cpp.
References beast::unit_test::suite::pass(), and T.
     {
         T t{};
         hardened_hash <T>() (t);
         pass();
     }
template<template< class T > class C> void beast::hardened_hash_test::check_container () inline
Definition at line 230 of file hardened_hash.test.cpp.
References beast::unit_test::suite::pass().
     {
         {
             C <detail::test_user_type_member <std::string>> c;
         }
         pass();
         {
             C <detail::test_user_type_free <std::string>> c;
         }
         pass();
     }
template<template< class T > class U> void beast::hardened_hash_test::check_user_type () inline
Definition at line 205 of file hardened_hash.test.cpp.
     {
         check <U <bool>> ();
         check <U <char>> ();
         check <U <signed char>> ();
         check <U <unsigned char>> ();
         // These cause trouble for boost
         //check <U <char16_t>> ();
         //check <U <char32_t>> ();
         check <U <wchar_t>> ();
         check <U <short>> ();
         check <U <unsigned short>> ();
         check <U <int>> ();
         check <U <unsigned int>> ();
         check <U <long>> ();
         check <U <long long>> ();
         check <U <unsigned long>> ();
         check <U <unsigned long long>> ();
         check <U <float>> ();
         check <U <double>> ();
         check <U <long double>> ();
     }
void beast::hardened_hash_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 264 of file hardened_hash.test.cpp.
References test_containers(), and test_user_types().
     {
         test_user_types();
         test_containers();
     }
void beast::hardened_hash_test::test_containers () inline
Definition at line 254 of file hardened_hash.test.cpp.
References beast::unit_test::suite::testcase().
Referenced by run().
     {
         testcase ("containers");
         check_container <detail::test_hardened_unordered_set>();
         check_container <detail::test_hardened_unordered_map>();
         check_container <detail::test_hardened_unordered_multiset>();
         check_container <detail::test_hardened_unordered_multimap>();
     }
void beast::hardened_hash_test::test_user_types () inline
Definition at line 246 of file hardened_hash.test.cpp.
References beast::unit_test::suite::testcase().
Referenced by run().
     {
         testcase ("user types");
         check_user_type <detail::test_user_type_member> ();
         check_user_type <detail::test_user_type_free> ();
     }
The documentation for this class was generated from the following file:
rippled/src/beast/beast/container/tests/hardened_hash.test.cpp