rippled: beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize > Class Template Reference
beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize > Class Template Reference
#include <Array.h>
Public Types
typedef
TypeOfCriticalSectionToUse::ScopedLockType ScopedLockType
Public Member Functions
Array () noexcept
Array (const Array< ElementType, TypeOfCriticalSectionToUse > &other)
template<typename TypeToCreateFrom >
Array (const TypeToCreateFrom *values)
template<typename TypeToCreateFrom >
Array (const TypeToCreateFrom *values, int numValues)
~Array ()
Array & operator= (const Array &other)
template<class OtherArrayType >
bool operator== (const OtherArrayType &other) const
template<class OtherArrayType >
bool operator!= (const OtherArrayType &other) const
void clear ()
void clearQuick ()
int size () const noexcept
ElementType operator[] (const int index) const
ElementType getUnchecked (const int index) const
ElementType & getReference (const int index) const noexcept
ElementType getFirst () const
ElementType getLast () const
ElementType * getRawDataPointer () noexcept
ElementType * begin () const noexcept
ElementType * end () const noexcept
int indexOf (ParameterType elementToLookFor) const
bool contains (ParameterType elementToLookFor) const
int add (ParameterType newElement)
void insert (int indexToInsertAt, ParameterType newElement)
void insertMultiple (int indexToInsertAt, ParameterType newElement, int numberOfTimesToInsertIt)
void insertArray (int indexToInsertAt, const ElementType *newElements, int numberOfElements)
int addIfNotAlreadyThere (ParameterType newElement)
void set (const int indexToChange, ParameterType newValue)
void setUnchecked (const int indexToChange, ParameterType newValue)
void addArray (const ElementType *elementsToAdd, int numElementsToAdd)
template<class OtherArrayType >
void swapWith (OtherArrayType &otherArray) noexcept
template<class OtherArrayType >
void addArray (const OtherArrayType &arrayToAddFrom, int startIndex=0, int numElementsToAdd=-1)
void resize (const int targetNumItems)
template<class ElementComparator >
int addSorted (ElementComparator &comparator, ParameterType newElement)
void addUsingDefaultSort (ParameterType newElement)
template<typename ElementComparator , typename TargetValueType >
int indexOfSorted (ElementComparator &comparator, TargetValueType elementToLookFor) const
ElementType remove (const int indexToRemove)
void removeFirstMatchingValue (ParameterType valueToRemove)
void removeAllInstancesOf (ParameterType valueToRemove)
void removeRange (int startIndex, int numberToRemove)
void removeLast (int howManyToRemove=1)
template<class OtherArrayType >
void removeValuesIn (const OtherArrayType &otherArray)
template<class OtherArrayType >
void removeValuesNotIn (const OtherArrayType &otherArray)
void swap (const int index1, const int index2)
void move (const int currentIndex, int newIndex) noexcept
void minimiseStorageOverheads ()
void ensureStorageAllocated (const int minNumElements)
template<class ElementComparator >
void sort (ElementComparator &comparator, const bool retainOrderOfEquivalentItems=false) const
const TypeOfCriticalSectionToUse & getLock () const noexcept
Private Types
typedef ElementType ParameterType
Private Member Functions
void removeInternal (const int indexToRemove)
void deleteAllElements () noexcept
void minimiseStorageAfterRemoval ()
Private Attributes
ArrayAllocationBase
< ElementType,
TypeOfCriticalSectionToUse > data
int numUsed
Detailed Description
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0>
class beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >
Holds a resizable array of primitive or copy-by-value objects.
Examples of arrays are: Array<int>, Array<Rectangle> or Array<MyClass*>
The Array class can be used to hold simple, non-polymorphic objects as well as primitive types - to do so, the class must fulfil these requirements:
it must have a copy constructor and assignment operator
it must be able to be relocated in memory by a memcpy without this causing any problems - so objects whose functionality relies on external pointers or references to themselves can be used.
For holding lists of strings, you can use Array<String>, but it's usually better to use the specialised class StringArray, which provides more useful functions.
To make all the array's methods thread-safe, pass in "CriticalSection" as the templated TypeOfCriticalSectionToUse parameter, instead of the default DummyCriticalSection.
See Also
SharedObjectArray, StringArray, CriticalSection
Definition at line 56 of file Array.h.
Member Typedef Documentation
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> typedef ElementType beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::ParameterType private
Definition at line 59 of file Array.h.
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> typedef TypeOfCriticalSectionToUse::ScopedLockType beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::ScopedLockType
Returns the type of scoped lock to use for locking this array
Definition at line 1023 of file Array.h.
Constructor & Destructor Documentation
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::Array () inline noexcept
Creates an empty array.
Definition at line 64 of file Array.h.
        : numUsed (0)
     {
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::Array (const Array< ElementType, TypeOfCriticalSectionToUse > & other) inline
Creates a copy of another array.
Parameters
other the array to copy
Definition at line 72 of file Array.h.
     {
         const ScopedLockType lock (other.getLock());
         numUsed = other.numUsed;
         data.setAllocatedSize (other.numUsed);
         for (int i = 0; i < numUsed; ++i)
             new (data.elements + i) ElementType (other.data.elements[i]);
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> template<typename TypeToCreateFrom > beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::Array (const TypeToCreateFrom * values) inline explicit
Initalises from a null-terminated C array of values.
Parameters
values the array to copy from
Definition at line 96 of file Array.h.
        : numUsed (0)
     {
         while (*values != TypeToCreateFrom())
             add (*values++);
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> template<typename TypeToCreateFrom > beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::Array (const TypeToCreateFrom * values, int numValues) inline
Initalises from a C array of values.
Parameters
values the array to copy from
numValues the number of values in the array
Definition at line 109 of file Array.h.
        : numUsed (numValues)
     {
         data.setAllocatedSize (numValues);
         for (int i = 0; i < numValues; ++i)
             new (data.elements + i) ElementType (values[i]);
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::~Array () inline
Destructor.
Definition at line 119 of file Array.h.
     {
         deleteAllElements();
     }
Member Function Documentation
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> int beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::add (ParameterType newElement) inline
Appends a new element at the end of the array.
Parameters
newElement the new object to add to the array
Returns
The index of the new item, or -1 if it already existed.
See Also
set, insert, addIfNotAlreadyThere, addSorted, addUsingDefaultSort, addArray
Definition at line 367 of file Array.h.
Referenced by beast::StringArrayHelpers::addArray(), beast::Array< beast::String >::addArray(), beast::Array< beast::String >::addIfNotAlreadyThere(), beast::Array< beast::String >::Array(), beast::File::findChildFiles(), and beast::File::findFileSystemRoots().
     {
         const ScopedLockType lock (getLock());
         data.ensureAllocatedSize (numUsed + 1);
         new (data.elements + numUsed++) ElementType (newElement);
         return numUsed;
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::addArray (const ElementType * elementsToAdd, int numElementsToAdd) inline
Adds elements from an array to the end of this array.
Parameters
elementsToAdd the array of elements to add
numElementsToAdd how many elements are in this other array
See Also
add
Definition at line 555 of file Array.h.
     {
         const ScopedLockType lock (getLock());
         if (numElementsToAdd > 0)
         {
             data.ensureAllocatedSize (numUsed + numElementsToAdd);
             while (--numElementsToAdd >= 0)
             {
                 new (data.elements + numUsed) ElementType (*elementsToAdd++);
                 ++numUsed;
             }
         }
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> template<class OtherArrayType > void beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::addArray (const OtherArrayType & arrayToAddFrom, int startIndex = 0, int numElementsToAdd = -1) inline
Adds elements from another array to the end of this array.
Parameters
arrayToAddFrom the array from which to copy the elements
startIndex the first element of the other array to start copying from
numElementsToAdd how many elements to add from the other array. If this value is negative or greater than the number of available elements, all available elements will be copied.
See Also
add
Definition at line 596 of file Array.h.
     {
         const typename OtherArrayType::ScopedLockType lock1 (arrayToAddFrom.getLock());
         {
             const ScopedLockType lock2 (getLock());
             if (startIndex < 0)
             {
                 bassertfalse;
                 startIndex = 0;
             }
             if (numElementsToAdd < 0 || startIndex + numElementsToAdd > arrayToAddFrom.size())
                 numElementsToAdd = arrayToAddFrom.size() - startIndex;
             while (--numElementsToAdd >= 0)
                 add (arrayToAddFrom.getUnchecked (startIndex++));
         }
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> int beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::addIfNotAlreadyThere (ParameterType newElement) inline
Appends a new element at the end of the array as long as the array doesn't already contain it.
If the array already contains an element that matches the one passed in, nothing will be done.
Parameters
newElement the new object to add to the array
Returns
The index of the new item, or -1 if it already existed.
Definition at line 498 of file Array.h.
     {
         const ScopedLockType lock (getLock());
         if (! contains (newElement))
             return add (newElement);
         return -1;
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> template<class ElementComparator > int beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::addSorted (ElementComparator & comparator, ParameterType newElement) inline
Inserts a new element into the array, assuming that the array is sorted.
This will use a comparator to find the position at which the new element should go. If the array isn't sorted, the behaviour of this method will be unpredictable.
Parameters
comparator the comparator to use to compare the elements - see the sort() method for details about the form this object should take
newElement the new element to insert to the array
Returns
the index at which the new item was added
See Also
addUsingDefaultSort, add, sort
Definition at line 650 of file Array.h.
Referenced by beast::Array< beast::String >::addUsingDefaultSort().
     {
         const ScopedLockType lock (getLock());
         const int index = findInsertIndexInSortedArray (comparator, data.elements.getData(), newElement, 0, numUsed);
         insert (index, newElement);
         return index;
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::addUsingDefaultSort (ParameterType newElement) inline
Inserts a new element into the array, assuming that the array is sorted.
This will use the DefaultElementComparator class for sorting, so your ElementType must be suitable for use with that class. If the array isn't sorted, the behaviour of this method will be unpredictable.
Parameters
newElement the new element to insert to the array
See Also
addSorted, sort
Definition at line 667 of file Array.h.
     {
         DefaultElementComparator <ElementType> comparator;
         addSorted (comparator, newElement);
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> ElementType* beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::begin () const inline noexcept
Returns a pointer to the first element in the array. This method is provided for compatibility with standard C++ iteration mechanisms.
Definition at line 307 of file Array.h.
     {
         return data.elements;
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::clear () inline
Removes all elements from the array. This will remove all the elements, and free any storage that the array is using. To clear the array without freeing the storage, use the clearQuick() method instead.
See Also
clearQuick
Definition at line 190 of file Array.h.
Referenced by beast::File::copyDirectoryTo(), beast::Array< beast::String >::removeValuesIn(), and beast::Array< beast::String >::removeValuesNotIn().
     {
         const ScopedLockType lock (getLock());
         deleteAllElements();
         data.setAllocatedSize (0);
         numUsed = 0;
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::clearQuick () inline
Removes all elements from the array without freeing the array's allocated storage.
See Also
clear
Definition at line 202 of file Array.h.
     {
         const ScopedLockType lock (getLock());
         deleteAllElements();
         numUsed = 0;
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> bool beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::contains (ParameterType elementToLookFor) const inline
Returns true if the array contains at least one occurrence of an object.
Parameters
elementToLookFor the value or object to look for
Returns
true if the item is found
Definition at line 347 of file Array.h.
Referenced by beast::Array< beast::String >::addIfNotAlreadyThere(), and beast::File_test::run().
     {
         const ScopedLockType lock (getLock());
         const ElementType* e = data.elements.getData();
         const ElementType* const end_ = e + numUsed;
         for (; e != end_; ++e)
             if (elementToLookFor == *e)
                 return true;
         return false;
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::deleteAllElements () inline private noexcept
Definition at line 1044 of file Array.h.
Referenced by beast::Array< beast::String >::clear(), beast::Array< beast::String >::clearQuick(), and beast::Array< beast::String >::~Array().
     {
         for (int i = 0; i < numUsed; ++i)
             data.elements[i].~ElementType();
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> ElementType* beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::end () const inline noexcept
Returns a pointer to the element which follows the last element in the array. This method is provided for compatibility with standard C++ iteration mechanisms.
Definition at line 315 of file Array.h.
     {
         return data.elements + numUsed;
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::ensureStorageAllocated (const int minNumElements) inline
Increases the array's internal storage to hold a minimum number of elements.
Calling this before adding a large known number of elements means that the array won't have to keep dynamically resizing itself as the elements are added, and it'll therefore be more efficient.
Definition at line 972 of file Array.h.
     {
         const ScopedLockType lock (getLock());
         data.ensureAllocatedSize (minNumElements);
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> ElementType beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getFirst () const inline
Returns the first element in the array, or a default value if the array is empty.
See Also
operator[], getUnchecked, getLast
Definition at line 276 of file Array.h.
     {
         const ScopedLockType lock (getLock());
         return (numUsed > 0) ? data.elements [0]
                              : ElementType();
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> ElementType beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getLast () const inline
Returns the last element in the array, or a default value if the array is empty.
See Also
operator[], getUnchecked, getFirst
Definition at line 287 of file Array.h.
     {
         const ScopedLockType lock (getLock());
         return (numUsed > 0) ? data.elements [numUsed - 1]
                              : ElementType();
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> const TypeOfCriticalSectionToUse& beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getLock () const inline noexcept
Returns the CriticalSection that locks this array. To lock, you can call getLock().enter() and getLock().exit(), or preferably use an object of ScopedLockType as an RAII lock for it.
Definition at line 1020 of file Array.h.
Referenced by beast::Array< beast::String >::add(), beast::Array< beast::String >::addArray(), beast::Array< beast::String >::addIfNotAlreadyThere(), beast::Array< beast::String >::addSorted(), beast::Array< beast::String >::Array(), beast::Array< beast::String >::clear(), beast::Array< beast::String >::clearQuick(), beast::Array< beast::String >::contains(), beast::Array< beast::String >::ensureStorageAllocated(), beast::Array< beast::String >::getFirst(), beast::Array< beast::String >::getLast(), beast::Array< beast::String >::getReference(), beast::Array< beast::String >::getUnchecked(), beast::Array< beast::String >::indexOf(), beast::Array< beast::String >::indexOfSorted(), beast::Array< beast::String >::insert(), beast::Array< beast::String >::insertArray(), beast::Array< beast::String >::insertMultiple(), beast::Array< beast::String >::minimiseStorageOverheads(), beast::Array< beast::String >::move(), beast::Array< beast::String >::operator==(), beast::Array< beast::String >::operator[](), beast::Array< beast::String >::remove(), beast::Array< beast::String >::removeAllInstancesOf(), beast::Array< beast::String >::removeFirstMatchingValue(), beast::Array< beast::String >::removeLast(), beast::Array< beast::String >::removeRange(), beast::Array< beast::String >::removeValuesIn(), beast::Array< beast::String >::removeValuesNotIn(), beast::Array< beast::String >::set(), beast::Array< beast::String >::setUnchecked(), beast::Array< beast::String >::sort(), beast::Array< beast::String >::swap(), and beast::Array< beast::String >::swapWith().
 { return data; }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> ElementType* beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getRawDataPointer () inline noexcept
Returns a pointer to the actual array data. This pointer will only be valid until the next time a non-const method is called on the array.
Definition at line 298 of file Array.h.
     {
         return data.elements;
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> ElementType& beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getReference (const int index) const inline noexcept
Returns a direct reference to one of the elements in the array, without checking the index passed in.
This is like getUnchecked, but returns a direct reference to the element, so that you can alter it directly. Obviously this can be dangerous, so only use it when absolutely necessary.
Parameters
index the index of the element being requested (0 is the first element in the array)
See Also
operator[], getFirst, getLast
Definition at line 265 of file Array.h.
Referenced by beast::File::copyDirectoryTo(), beast::File::deleteRecursively(), and beast::File::setReadOnly().
     {
         const ScopedLockType lock (getLock());
         bassert (isPositiveAndBelow (index, numUsed) && data.elements != nullptr);
         return data.elements [index];
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> ElementType beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getUnchecked (const int index) const inline
Returns one of the elements in the array, without checking the index passed in.
Unlike the operator[] method, this will try to return an element without checking that the index is within the bounds of the array, so should only be used when you're confident that it will always be a valid index.
Parameters
index the index of the element being requested (0 is the first element in the array)
See Also
operator[], getFirst, getLast
Definition at line 249 of file Array.h.
     {
         const ScopedLockType lock (getLock());
         bassert (isPositiveAndBelow (index, numUsed) && data.elements != nullptr);
         return data.elements [index];
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> int beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::indexOf (ParameterType elementToLookFor) const inline
Finds the index of the first element which matches the value passed in.
This will search the array for the given object, and return the index of its first occurrence. If the object isn't found, the method will return -1.
Parameters
elementToLookFor the value or object to look for
Returns
the index of the object, or -1 if it's not found
Definition at line 329 of file Array.h.
     {
         const ScopedLockType lock (getLock());
         const ElementType* e = data.elements.getData();
         const ElementType* const end_ = e + numUsed;
         for (; e != end_; ++e)
             if (elementToLookFor == *e)
                 return static_cast <int> (e - data.elements.getData());
         return -1;
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> template<typename ElementComparator , typename TargetValueType > int beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::indexOfSorted (ElementComparator & comparator, TargetValueType elementToLookFor) const inline
Finds the index of an element in the array, assuming that the array is sorted.
This will use a comparator to do a binary-chop to find the index of the given element, if it exists. If the array isn't sorted, the behaviour of this method will be unpredictable.
Parameters
comparator the comparator to use to compare the elements - see the sort() method for details about the form this object should take
elementToLookFor the element to search for
Returns
the index of the element, or -1 if it's not found
See Also
addSorted, sort
Definition at line 686 of file Array.h.
     {
         (void) comparator;  // if you pass in an object with a static compareElements() method, this
                             // avoids getting warning messages about the parameter being unused
         const ScopedLockType lock (getLock());
         for (int s = 0, e = numUsed;;)
         {
             if (s >= e)
                 return -1;
             if (comparator.compareElements (elementToLookFor, data.elements [s]) == 0)
                 return s;
             const int halfway = (s + e) / 2;
             if (halfway == s)
                 return -1;
             if (comparator.compareElements (elementToLookFor, data.elements [halfway]) >= 0)
                 s = halfway;
             else
                 e = halfway;
         }
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::insert (int indexToInsertAt, ParameterType newElement) inline
Inserts a new element into the array at a given position.
If the index is less than 0 or greater than the size of the array, the element will be added to the end of the array. Otherwise, it will be inserted into the array, moving all the later elements along to make room.
Parameters
indexToInsertAt the index at which the new element should be inserted (pass in -1 to add it to the end)
newElement the new object to add to the array
See Also
add, addSorted, addUsingDefaultSort, set
Definition at line 387 of file Array.h.
Referenced by beast::Array< beast::String >::addSorted().
     {
         const ScopedLockType lock (getLock());
         data.ensureAllocatedSize (numUsed + 1);
         bassert (data.elements != nullptr);
         if (isPositiveAndBelow (indexToInsertAt, numUsed))
         {
             ElementType* const insertPos = data.elements + indexToInsertAt;
             const int numberToMove = numUsed - indexToInsertAt;
             if (numberToMove > 0)
                 memmove (insertPos + 1, insertPos, ((size_t) numberToMove) * sizeof (ElementType));
             new (insertPos) ElementType (newElement);
             ++numUsed;
         }
         else
         {
             new (data.elements + numUsed++) ElementType (newElement);
         }
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::insertArray (int indexToInsertAt, const ElementType * newElements, int numberOfElements) inline
Inserts an array of values into this array at a given position.
If the index is less than 0 or greater than the size of the array, the new elements will be added to the end of the array. Otherwise, they will be inserted into the array, moving all the later elements along to make room.
Parameters
indexToInsertAt the index at which the first new element should be inserted
newElements the new values to add to the array
numberOfElements how many items are in the array
See Also
insert, add, addSorted, set
Definition at line 461 of file Array.h.
     {
         if (numberOfElements > 0)
         {
             const ScopedLockType lock (getLock());
             data.ensureAllocatedSize (numUsed + numberOfElements);
             ElementType* insertPos = data.elements;
             if (isPositiveAndBelow (indexToInsertAt, numUsed))
             {
                 insertPos += indexToInsertAt;
                 const int numberToMove = numUsed - indexToInsertAt;
                 memmove (insertPos + numberOfElements, insertPos, numberToMove * sizeof (ElementType));
             }
             else
             {
                 insertPos += numUsed;
             }
             numUsed += numberOfElements;
             while (--numberOfElements >= 0)
                 new (insertPos++) ElementType (*newElements++);
         }
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::insertMultiple (int indexToInsertAt, ParameterType newElement, int numberOfTimesToInsertIt) inline
Inserts multiple copies of an element into the array at a given position.
If the index is less than 0 or greater than the size of the array, the element will be added to the end of the array. Otherwise, it will be inserted into the array, moving all the later elements along to make room.
Parameters
indexToInsertAt the index at which the new element should be inserted
newElement the new object to add to the array
numberOfTimesToInsertIt how many copies of the value to insert
See Also
insert, add, addSorted, set
Definition at line 422 of file Array.h.
Referenced by beast::Array< beast::String >::resize().
     {
         if (numberOfTimesToInsertIt > 0)
         {
             const ScopedLockType lock (getLock());
             data.ensureAllocatedSize (numUsed + numberOfTimesToInsertIt);
             ElementType* insertPos;
             if (isPositiveAndBelow (indexToInsertAt, numUsed))
             {
                 insertPos = data.elements + indexToInsertAt;
                 const int numberToMove = numUsed - indexToInsertAt;
                 memmove (insertPos + numberOfTimesToInsertIt, insertPos, ((size_t) numberToMove) * sizeof (ElementType));
             }
             else
             {
                 insertPos = data.elements + numUsed;
             }
             numUsed += numberOfTimesToInsertIt;
             while (--numberOfTimesToInsertIt >= 0)
                 new (insertPos++) ElementType (newElement);
         }
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::minimiseStorageAfterRemoval () inline private
Definition at line 1050 of file Array.h.
Referenced by beast::Array< beast::String >::removeInternal(), beast::Array< beast::String >::removeLast(), and beast::Array< beast::String >::removeRange().
     {
         if (data.numAllocated > bmax (minimumAllocatedSize, numUsed * 2))
             data.shrinkToNoMoreThan (bmax (numUsed, bmax (minimumAllocatedSize, 64 / (int) sizeof (ElementType))));
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::minimiseStorageOverheads () inline
Reduces the amount of storage being used by the array.
Arrays typically allocate slightly more storage than they need, and after removing elements, they may have quite a lot of unused space allocated. This method will reduce the amount of allocated storage to a minimum.
Definition at line 960 of file Array.h.
     {
         const ScopedLockType lock (getLock());
         data.shrinkToNoMoreThan (numUsed);
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::move (const int currentIndex, int newIndex) inline noexcept
Moves one of the values to a different position.
This will move the value to a specified index, shuffling along any intervening elements as required.
So for example, if you have the array { 0, 1, 2, 3, 4, 5 } then calling move (2, 4) would result in { 0, 1, 3, 4, 2, 5 }.
Parameters
currentIndex the index of the value to be moved. If this isn't a valid index, then nothing will be done
newIndex the index at which you'd like this value to end up. If this is less than zero, the value will be moved to the end of the array
Definition at line 921 of file Array.h.
     {
         if (currentIndex != newIndex)
         {
             const ScopedLockType lock (getLock());
             if (isPositiveAndBelow (currentIndex, numUsed))
             {
                 if (! isPositiveAndBelow (newIndex, numUsed))
                     newIndex = numUsed - 1;
                 char tempCopy [sizeof (ElementType)];
                 memcpy (tempCopy, data.elements + currentIndex, sizeof (ElementType));
                 if (newIndex > currentIndex)
                 {
                     memmove (data.elements + currentIndex,
                              data.elements + currentIndex + 1,
                              sizeof (ElementType) * (size_t) (newIndex - currentIndex));
                 }
                 else
                 {
                     memmove (data.elements + newIndex + 1,
                              data.elements + newIndex,
                              sizeof (ElementType) * (size_t) (currentIndex - newIndex));
                 }
                 memcpy (data.elements + newIndex, tempCopy, sizeof (ElementType));
             }
         }
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> template<class OtherArrayType > bool beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::operator!= (const OtherArrayType & other) const inline
Compares this array to another one. Two arrays are considered equal if they both contain the same set of elements, in the same order.
Parameters
other the other array to compare with
Definition at line 177 of file Array.h.
     {
         return ! operator== (other);
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> Array& beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::operator= (const Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize > & other) inline
Copies another array.
Parameters
other the array to copy
Definition at line 127 of file Array.h.
     {
         if (this != &other)
         {
             Array<ElementType, TypeOfCriticalSectionToUse> otherCopy (other);
             swapWith (otherCopy);
         }
         return *this;
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> template<class OtherArrayType > bool beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::operator== (const OtherArrayType & other) const inline
Compares this array to another one. Two arrays are considered equal if they both contain the same set of elements, in the same order.
Parameters
other the other array to compare with
Definition at line 156 of file Array.h.
Referenced by beast::Array< beast::String >::operator!=().
     {
         const ScopedLockType lock (getLock());
         const typename OtherArrayType::ScopedLockType lock2 (other.getLock());
         if (numUsed != other.numUsed)
             return false;
         for (int i = numUsed; --i >= 0;)
             if (! (data.elements [i] == other.data.elements [i]))
                 return false;
         return true;
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> ElementType beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::operator[] (const int index) const inline
Returns one of the elements in the array. If the index passed in is beyond the range of valid elements, this will return a default value.
If you're certain that the index will always be a valid element, you can call getUnchecked() instead, which is faster.
Parameters
index the index of the element being requested (0 is the first element in the array)
See Also
getUnchecked, getFirst, getLast
Definition at line 227 of file Array.h.
     {
         const ScopedLockType lock (getLock());
         if (isPositiveAndBelow (index, numUsed))
         {
             bassert (data.elements != nullptr);
             return data.elements [index];
         }
         return ElementType();
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> ElementType beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::remove (const int indexToRemove) inline
Removes an element from the array.
This will remove the element at a given index, and move back all the subsequent elements to close the gap. If the index passed in is out-of-range, nothing will happen.
Parameters
indexToRemove the index of the element to remove
Returns
the element that has been removed
See Also
removeValue, removeRange
Definition at line 723 of file Array.h.
     {
         const ScopedLockType lock (getLock());
         if (isPositiveAndBelow (indexToRemove, numUsed))
         {
             bassert (data.elements != nullptr);
             ElementType removed (data.elements[indexToRemove]);
             removeInternal (indexToRemove);
             return removed;
         }
         return ElementType();
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::removeAllInstancesOf (ParameterType valueToRemove) inline
Removes an item from the array.
This will remove the first occurrence of the given element from the array. If the item isn't found, no action is taken.
Parameters
valueToRemove the object to try to remove
See Also
remove, removeRange
Definition at line 769 of file Array.h.
     {
         const ScopedLockType lock (getLock());
         for (int i = numUsed; --i >= 0;)
             if (valueToRemove == data.elements[i])
                 removeInternal (i);
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::removeFirstMatchingValue (ParameterType valueToRemove) inline
Removes an item from the array.
This will remove the first occurrence of the given element from the array. If the item isn't found, no action is taken.
Parameters
valueToRemove the object to try to remove
See Also
remove, removeRange
Definition at line 746 of file Array.h.
     {
         const ScopedLockType lock (getLock());
         ElementType* const e = data.elements;
         for (int i = 0; i < numUsed; ++i)
         {
             if (valueToRemove == e[i])
             {
                 removeInternal (i);
                 break;
             }
         }
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::removeInternal (const int indexToRemove) inline private
Definition at line 1031 of file Array.h.
Referenced by beast::Array< beast::String >::remove(), beast::Array< beast::String >::removeAllInstancesOf(), beast::Array< beast::String >::removeFirstMatchingValue(), beast::Array< beast::String >::removeValuesIn(), and beast::Array< beast::String >::removeValuesNotIn().
     {
         --numUsed;
         ElementType* const e = data.elements + indexToRemove;
         e->~ElementType();
         const int numberToShift = numUsed - indexToRemove;
         if (numberToShift > 0)
             memmove (e, e + 1, ((size_t) numberToShift) * sizeof (ElementType));
         minimiseStorageAfterRemoval();
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::removeLast (int howManyToRemove = 1) inline
Removes the last n elements from the array.
Parameters
howManyToRemove how many elements to remove from the end of the array
See Also
remove, removeFirstMatchingValue, removeAllInstancesOf, removeRange
Definition at line 818 of file Array.h.
     {
         const ScopedLockType lock (getLock());
         if (howManyToRemove > numUsed)
             howManyToRemove = numUsed;
         for (int i = 1; i <= howManyToRemove; ++i)
             data.elements [numUsed - i].~ElementType();
         numUsed -= howManyToRemove;
         minimiseStorageAfterRemoval();
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::removeRange (int startIndex, int numberToRemove) inline
Removes a range of elements from the array.
This will remove a set of elements, starting from the given index, and move subsequent elements down to close the gap.
If the range extends beyond the bounds of the array, it will be safely clipped to the size of the array.
Parameters
startIndex the index of the first element to remove
numberToRemove how many elements should be removed
See Also
remove, removeFirstMatchingValue, removeAllInstancesOf
Definition at line 790 of file Array.h.
Referenced by beast::Array< beast::String >::resize().
     {
         const ScopedLockType lock (getLock());
         const int endIndex = blimit (0, numUsed, startIndex + numberToRemove);
         startIndex = blimit (0, numUsed, startIndex);
         if (endIndex > startIndex)
         {
             ElementType* const e = data.elements + startIndex;
             numberToRemove = endIndex - startIndex;
             for (int i = 0; i < numberToRemove; ++i)
                 e[i].~ElementType();
             const int numToShift = numUsed - endIndex;
             if (numToShift > 0)
                 memmove (e, e + numberToRemove, ((size_t) numToShift) * sizeof (ElementType));
             numUsed -= numberToRemove;
             minimiseStorageAfterRemoval();
         }
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> template<class OtherArrayType > void beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::removeValuesIn (const OtherArrayType & otherArray) inline
Removes any elements which are also in another array.
Parameters
otherArray the other array in which to look for elements to remove
See Also
removeValuesNotIn, remove, removeFirstMatchingValue, removeAllInstancesOf, removeRange
Definition at line 838 of file Array.h.
     {
         const typename OtherArrayType::ScopedLockType lock1 (otherArray.getLock());
         const ScopedLockType lock2 (getLock());
         if (this == &otherArray)
         {
             clear();
         }
         else
         {
             if (otherArray.size() > 0)
             {
                 for (int i = numUsed; --i >= 0;)
                     if (otherArray.contains (data.elements [i]))
                         removeInternal (i);
             }
         }
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> template<class OtherArrayType > void beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::removeValuesNotIn (const OtherArrayType & otherArray) inline
Removes any elements which are not found in another array.
Only elements which occur in this other array will be retained.
Parameters
otherArray the array in which to look for elements NOT to remove
See Also
removeValuesIn, remove, removeFirstMatchingValue, removeAllInstancesOf, removeRange
Definition at line 866 of file Array.h.
     {
         const typename OtherArrayType::ScopedLockType lock1 (otherArray.getLock());
         const ScopedLockType lock2 (getLock());
         if (this != &otherArray)
         {
             if (otherArray.size() <= 0)
             {
                 clear();
             }
             else
             {
                 for (int i = numUsed; --i >= 0;)
                     if (! otherArray.contains (data.elements [i]))
                         removeInternal (i);
             }
         }
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::resize (const int targetNumItems) inline
This will enlarge or shrink the array to the given number of elements, by adding or removing items from its end.
If the array is smaller than the given target size, empty elements will be appended until its size is as specified. If its size is larger than the target, items will be removed from its end to shorten it.
Definition at line 626 of file Array.h.
     {
         bassert (targetNumItems >= 0);
         const int numToAdd = targetNumItems - numUsed;
         if (numToAdd > 0)
             insertMultiple (numUsed, ElementType(), numToAdd);
         else if (numToAdd < 0)
             removeRange (targetNumItems, -numToAdd);
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::set (const int indexToChange, ParameterType newValue) inline
Replaces an element with a new value.
If the index is less than zero, this method does nothing. If the index is beyond the end of the array, the item is added to the end of the array.
Parameters
indexToChange the index whose value you want to change
newValue the new value to set for this index.
See Also
add, insert
Definition at line 517 of file Array.h.
     {
         bassert (indexToChange >= 0);
         const ScopedLockType lock (getLock());
         if (isPositiveAndBelow (indexToChange, numUsed))
         {
             data.elements [indexToChange] = newValue;
         }
         else if (indexToChange >= 0)
         {
             data.ensureAllocatedSize (numUsed + 1);
             new (data.elements + numUsed++) ElementType (newValue);
         }
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::setUnchecked (const int indexToChange, ParameterType newValue) inline
Replaces an element with a new value without doing any bounds-checking.
This just sets a value directly in the array's internal storage, so you'd better make sure it's in range!
Parameters
indexToChange the index whose value you want to change
newValue the new value to set for this index.
See Also
set, getUnchecked
Definition at line 542 of file Array.h.
     {
         const ScopedLockType lock (getLock());
         bassert (isPositiveAndBelow (indexToChange, numUsed));
         data.elements [indexToChange] = newValue;
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> int beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size () const inline noexcept
Returns the current number of elements in the array.
Definition at line 212 of file Array.h.
Referenced by beast::File::copyDirectoryTo(), beast::File::deleteRecursively(), beast::File_test::run(), beast::File::setReadOnly(), and beast::Array< beast::String >::sort().
     {
         return numUsed;
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> template<class ElementComparator > void beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::sort (ElementComparator & comparator, const bool retainOrderOfEquivalentItems = false) const inline
Sorts the elements in the array.
This will use a comparator object to sort the elements into order. The object passed must have a method of the form:
int compareElements (ElementType first, ElementType second);
..and this method must return:
a value of < 0 if the first comes before the second
a value of 0 if the two objects are equivalent
a value of > 0 if the second comes before the first
To improve performance, the compareElements() method can be declared as static or const.
Parameters
comparator the comparator to use for comparing elements.
retainOrderOfEquivalentItems if this is true, then items which the comparator says are equivalent will be kept in the order in which they currently appear in the array. This is slower to perform, but may be important in some cases. If it's false, a faster algorithm is used, but equivalent elements may be rearranged.
See Also
addSorted, indexOfSorted, sortArray
Definition at line 1006 of file Array.h.
     {
         const ScopedLockType lock (getLock());
         (void) comparator;  // if you pass in an object with a static compareElements() method, this
                             // avoids getting warning messages about the parameter being unused
         sortArray (comparator, data.elements.getData(), 0, size() - 1, retainOrderOfEquivalentItems);
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> void beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::swap (const int index1, const int index2) inline
Swaps over two elements in the array.
This swaps over the elements found at the two indexes passed in. If either index is out-of-range, this method will do nothing.
Parameters
index1 index of one of the elements to swap
index2 index of the other element to swap
Definition at line 894 of file Array.h.
     {
         const ScopedLockType lock (getLock());
         if (isPositiveAndBelow (index1, numUsed)
              && isPositiveAndBelow (index2, numUsed))
         {
             std::swap (data.elements [index1],
                        data.elements [index2]);
         }
     }
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> template<class OtherArrayType > void beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::swapWith (OtherArrayType & otherArray) inline noexcept
This swaps the contents of this array with those of another array.
If you need to exchange two arrays, this is vastly quicker than using copy-by-value because it just swaps their internal pointers.
Definition at line 577 of file Array.h.
Referenced by beast::Array< beast::String >::operator=().
     {
         const ScopedLockType lock1 (getLock());
         const typename OtherArrayType::ScopedLockType lock2 (otherArray.getLock());
         data.swapWith (otherArray.data);
         std::swap (numUsed, otherArray.numUsed);
     }
Member Data Documentation
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> ArrayAllocationBase<ElementType, TypeOfCriticalSectionToUse> beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::data private
Definition at line 1028 of file Array.h.
Referenced by beast::Array< beast::String >::add(), beast::Array< beast::String >::addArray(), beast::Array< beast::String >::addSorted(), beast::Array< beast::String >::Array(), beast::Array< beast::String >::begin(), beast::Array< beast::String >::clear(), beast::Array< beast::String >::contains(), beast::Array< beast::String >::deleteAllElements(), beast::Array< beast::String >::end(), beast::Array< beast::String >::ensureStorageAllocated(), beast::Array< beast::String >::getFirst(), beast::Array< beast::String >::getLast(), beast::Array< beast::String >::getLock(), beast::Array< beast::String >::getRawDataPointer(), beast::Array< beast::String >::getReference(), beast::Array< beast::String >::getUnchecked(), beast::Array< beast::String >::indexOf(), beast::Array< beast::String >::indexOfSorted(), beast::Array< beast::String >::insert(), beast::Array< beast::String >::insertArray(), beast::Array< beast::String >::insertMultiple(), beast::Array< beast::String >::minimiseStorageAfterRemoval(), beast::Array< beast::String >::minimiseStorageOverheads(), beast::Array< beast::String >::move(), beast::Array< beast::String >::operator==(), beast::Array< beast::String >::operator[](), beast::Array< beast::String >::remove(), beast::Array< beast::String >::removeAllInstancesOf(), beast::Array< beast::String >::removeFirstMatchingValue(), beast::Array< beast::String >::removeInternal(), beast::Array< beast::String >::removeLast(), beast::Array< beast::String >::removeRange(), beast::Array< beast::String >::removeValuesIn(), beast::Array< beast::String >::removeValuesNotIn(), beast::Array< beast::String >::set(), beast::Array< beast::String >::setUnchecked(), beast::Array< beast::String >::sort(), beast::Array< beast::String >::swap(), and beast::Array< beast::String >::swapWith().
template<typename ElementType, typename TypeOfCriticalSectionToUse = DummyCriticalSection, int minimumAllocatedSize = 0> int beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::numUsed private
Definition at line 1029 of file Array.h.
Referenced by beast::Array< beast::String >::add(), beast::Array< beast::String >::addArray(), beast::Array< beast::String >::addSorted(), beast::Array< beast::String >::Array(), beast::Array< beast::String >::clear(), beast::Array< beast::String >::clearQuick(), beast::Array< beast::String >::contains(), beast::Array< beast::String >::deleteAllElements(), beast::Array< beast::String >::end(), beast::Array< beast::String >::getFirst(), beast::Array< beast::String >::getLast(), beast::Array< beast::String >::getReference(), beast::Array< beast::String >::getUnchecked(), beast::Array< beast::String >::indexOf(), beast::Array< beast::String >::indexOfSorted(), beast::Array< beast::String >::insert(), beast::Array< beast::String >::insertArray(), beast::Array< beast::String >::insertMultiple(), beast::Array< beast::String >::minimiseStorageAfterRemoval(), beast::Array< beast::String >::minimiseStorageOverheads(), beast::Array< beast::String >::move(), beast::Array< beast::String >::operator==(), beast::Array< beast::String >::operator[](), beast::Array< beast::String >::remove(), beast::Array< beast::String >::removeAllInstancesOf(), beast::Array< beast::String >::removeFirstMatchingValue(), beast::Array< beast::String >::removeInternal(), beast::Array< beast::String >::removeLast(), beast::Array< beast::String >::removeRange(), beast::Array< beast::String >::removeValuesIn(), beast::Array< beast::String >::removeValuesNotIn(), beast::Array< beast::String >::resize(), beast::Array< beast::String >::set(), beast::Array< beast::String >::setUnchecked(), beast::Array< beast::String >::size(), beast::Array< beast::String >::swap(), and beast::Array< beast::String >::swapWith().
The documentation for this class was generated from the following file:
rippled/src/beast/modules/beast_core/containers/Array.h