rippled: beast::InputStream Class Reference
beast::InputStream Class Reference abstract
#include <InputStream.h>
Public Member Functions
virtual ~InputStream ()
virtual std::int64_t getTotalLength ()=0
std::int64_t getNumBytesRemaining ()
virtual bool isExhausted ()=0
virtual int read (void *destBuffer, int maxBytesToRead)=0
virtual char readByte ()
virtual bool readBool ()
virtual short readShort ()
virtual short readShortBigEndian ()
virtual std::int32_t readInt32 ()
virtual int readInt ()
virtual std::int32_t readInt32BigEndian ()
virtual int readIntBigEndian ()
virtual std::int64_t readInt64 ()
virtual std::int64_t readInt64BigEndian ()
virtual float readFloat ()
virtual float readFloatBigEndian ()
virtual double readDouble ()
virtual double readDoubleBigEndian ()
virtual int readCompressedInt ()
template<class T >
T readType ()
template<class T >
bool readTypeInto (T *p)
template<class T >
T readTypeBigEndian ()
template<class T >
bool readTypeBigEndianInto (T *p)
virtual String readNextLine ()
virtual String readString ()
virtual String readEntireStreamAsString ()
virtual int readIntoMemoryBlock (MemoryBlock &destBlock, std::ptrdiff_t maxNumBytesToRead=-1)
virtual std::int64_t getPosition ()=0
virtual bool setPosition (std::int64_t newPosition)=0
virtual void skipNextBytes (std::int64_t numBytesToSkip)
template<>
char readType ()
template<>
short readType ()
template<>
unsigned char readType ()
template<>
unsigned short readType ()
template<>
float readType ()
template<>
double readType ()
template<>
char readTypeBigEndian ()
template<>
short readTypeBigEndian ()
template<>
unsigned char readTypeBigEndian ()
template<>
unsigned short readTypeBigEndian ()
template<>
float readTypeBigEndian ()
template<>
double readTypeBigEndian ()
Protected Member Functions
InputStream () noexcept
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
The base class for streams that read data.
Input and output streams are used throughout the library - subclasses can override some or all of the virtual functions to implement their behaviour.
See Also
OutputStream, FileInputStream
Definition at line 40 of file InputStream.h.
Constructor & Destructor Documentation
virtual beast::InputStream::~InputStream () inline virtual
Destructor.
Definition at line 46 of file InputStream.h.
 {}
beast::InputStream::InputStream () inline protected noexcept
Definition at line 355 of file InputStream.h.
 {}
Member Function Documentation
std::int64_t beast::InputStream::getNumBytesRemaining ()
Returns the number of bytes available for reading, or a negative value if the remaining length is not known.
See Also
getTotalLength
Definition at line 27 of file InputStream.cpp.
References getPosition(), and getTotalLength().
Referenced by readTypeBigEndianInto(), and readTypeInto().
 {
     std::int64_t len = getTotalLength();
     if (len >= 0)
         len -= getPosition();
     return len;
 }
virtual std::int64_t beast::InputStream::getPosition () pure virtual
Returns the offset of the next byte that will be read from the stream.
See Also
setPosition
Implemented in beast::FileInputStream.
Referenced by getNumBytesRemaining(), readNextLine(), and beast::MemoryOutputStream::writeFromInputStream().
virtual std::int64_t beast::InputStream::getTotalLength () pure virtual
Returns the total number of bytes available for reading in this stream.
Note that this is the number of bytes available from the start of the stream, not from the current position.
If the size of the stream isn't actually known, this will return -1.
See Also
getNumBytesRemaining
Implemented in beast::FileInputStream.
Referenced by getNumBytesRemaining(), and beast::MemoryOutputStream::writeFromInputStream().
virtual bool beast::InputStream::isExhausted () pure virtual
Returns true if the stream has no more data to read.
Implemented in beast::FileInputStream.
Referenced by skipNextBytes().
virtual int beast::InputStream::read (void * destBuffer, int maxBytesToRead) pure virtual
Reads some data from the stream into a memory buffer.
This is the only read method that subclasses actually need to implement, as the InputStream base class implements the other read methods in terms of this one (although it's often more efficient for subclasses to implement them directly).
Parameters
destBuffer the destination buffer for the data. This must not be null.
maxBytesToRead the maximum number of bytes to read - make sure the memory block passed in is big enough to contain this many bytes. This value must not be negative.
Returns
the actual number of bytes that were read, which may be less than maxBytesToRead if the stream is exhausted before it gets that far
Implemented in beast::FileInputStream.
Referenced by readByte(), readCompressedInt(), readInt(), readInt32(), readInt32BigEndian(), readInt64(), readInt64BigEndian(), readIntBigEndian(), readShort(), readShortBigEndian(), skipNextBytes(), and beast::OutputStream::writeFromInputStream().
bool beast::InputStream::readBool () virtual
Reads a boolean from the stream.
The bool is encoded as a single byte - non-zero for true, 0 for false.
If the stream is exhausted, this will return false.
See Also
OutputStream::writeBool
Definition at line 44 of file InputStream.cpp.
References readByte().
 {
     return readByte() != 0;
 }
char beast::InputStream::readByte () virtual
Reads a byte from the stream.
If the stream is exhausted, this will return zero.
See Also
OutputStream::writeByte
Definition at line 37 of file InputStream.cpp.
References read().
Referenced by readBool(), readCompressedInt(), readNextLine(), and readString().
 {
     char temp = 0;
     read (&temp, 1);
     return temp;
 }
int beast::InputStream::readCompressedInt () virtual
Reads an encoded 32-bit number from the stream using a space-saving compressed format.
For small values, this is more space-efficient than using readInt() and OutputStream::writeInt()
The format used is: number of significant bytes + up to 4 bytes in little-endian order.
See Also
OutputStream::writeCompressedInt()
Definition at line 111 of file InputStream.cpp.
References bassertfalse, beast::ByteOrder::littleEndianInt(), read(), and readByte().
 {
     const std::uint8_t sizeByte = (std::uint8_t) readByte();
     if (sizeByte == 0)
         return 0;
     const int numBytes = (sizeByte & 0x7f);
     if (numBytes > 4)
     {
         bassertfalse;    // trying to read corrupt data - this method must only be used
                        // to read data that was written by OutputStream::writeCompressedInt()
         return 0;
     }
     char bytes[4] = { 0, 0, 0, 0 };
     if (read (bytes, numBytes) != numBytes)
         return 0;
     const int num = (int) ByteOrder::littleEndianInt (bytes);
     return (sizeByte >> 7) ? -num : num;
 }
double beast::InputStream::readDouble () virtual
Reads eight bytes as a 64-bit floating point value.
The raw 64-bit encoding of the double is read from the stream as a little-endian std::int64_t.
If the stream is exhausted partway through reading the bytes, this will return zero.
See Also
OutputStream::writeDouble, readFloat
Definition at line 169 of file InputStream.cpp.
References readInt64().
 {
     union { std::int64_t asInt; double asDouble; } n;
     n.asInt = readInt64();
     return n.asDouble;
 }
double beast::InputStream::readDoubleBigEndian () virtual
Reads eight bytes as a 64-bit floating point value.
The raw 64-bit encoding of the double is read from the stream as a big-endian std::int64_t.
If the stream is exhausted partway through reading the bytes, this will return zero.
See Also
OutputStream::writeDoubleBigEndian, readFloatBigEndian
Definition at line 176 of file InputStream.cpp.
References readInt64BigEndian().
 {
     union { std::int64_t asInt; double asDouble; } n;
     n.asInt = readInt64BigEndian();
     return n.asDouble;
 }
String beast::InputStream::readEntireStreamAsString () virtual
Tries to read the whole stream and turn it into a string.
This will read from the stream's current position until the end-of-stream. It can read from either UTF-16 or UTF-8 formats.
Definition at line 239 of file InputStream.cpp.
References beast::MemoryOutputStream::toString().
Referenced by beast::File::loadFileAsString().
 {
     MemoryOutputStream mo;
     mo << *this;
     return mo.toString();
 }
float beast::InputStream::readFloat () virtual
Reads four bytes as a 32-bit floating point value.
The raw 32-bit encoding of the float is read from the stream as a little-endian int.
If the stream is exhausted partway through reading the bytes, this will return zero.
See Also
OutputStream::writeFloat, readDouble
Definition at line 153 of file InputStream.cpp.
References readInt(), and static_bassert.
 {
     // the union below relies on these types being the same size...
     static_bassert (sizeof (std::int32_t) == sizeof (float));
     union { std::int32_t asInt; float asFloat; } n;
     n.asInt = (std::int32_t) readInt();
     return n.asFloat;
 }
float beast::InputStream::readFloatBigEndian () virtual
Reads four bytes as a 32-bit floating point value.
The raw 32-bit encoding of the float is read from the stream as a big-endian int.
If the stream is exhausted partway through reading the bytes, this will return zero.
See Also
OutputStream::writeFloatBigEndian, readDoubleBigEndian
Definition at line 162 of file InputStream.cpp.
References readIntBigEndian().
 {
     union { std::int32_t asInt; float asFloat; } n;
     n.asInt = (std::int32_t) readIntBigEndian();
     return n.asFloat;
 }
int beast::InputStream::readInt () virtual
Definition at line 69 of file InputStream.cpp.
References beast::ByteOrder::littleEndianInt(), read(), and static_bassert.
Referenced by readFloat().
 {
     static_bassert (sizeof (int) == 4);
     char temp[4];
     if (read (temp, 4) == 4)
         return (int) ByteOrder::littleEndianInt (temp);
     return 0;
 }
std::int32_t beast::InputStream::readInt32 () virtual
Reads four bytes from the stream as a little-endian 32-bit value.
If the next four bytes are byte1 to byte4, this returns (byte1 | (byte2 << 8) | (byte3 << 16) | (byte4 << 24)).
If the stream is exhausted partway through reading the bytes, this will return zero.
See Also
OutputStream::writeInt, readIntBigEndian
Definition at line 81 of file InputStream.cpp.
References beast::ByteOrder::littleEndianInt(), and read().
 {
     char temp[4];
     if (read (temp, 4) == 4)
         return (std::int32_t) ByteOrder::littleEndianInt (temp);
     return 0;
 }
std::int32_t beast::InputStream::readInt32BigEndian () virtual
Reads four bytes from the stream as a big-endian 32-bit value.
If the next four bytes are byte1 to byte4, this returns (byte4 | (byte3 << 8) | (byte2 << 16) | (byte1 << 24)).
If the stream is exhausted partway through reading the bytes, this will return zero.
See Also
OutputStream::writeIntBigEndian, readInt
Definition at line 101 of file InputStream.cpp.
References beast::ByteOrder::bigEndianInt(), and read().
 {
     char temp[4];
     if (read (temp, 4) == 4)
         return (std::int32_t) ByteOrder::bigEndianInt (temp);
     return 0;
 }
std::int64_t beast::InputStream::readInt64 () virtual
Reads eight bytes from the stream as a little-endian 64-bit value.
If the next eight bytes are byte1 to byte8, this returns (byte1 | (byte2 << 8) | (byte3 << 16) | (byte4 << 24) | (byte5 << 32) | (byte6 << 40) | (byte7 << 48) | (byte8 << 56)).
If the stream is exhausted partway through reading the bytes, this will return zero.
See Also
OutputStream::writeInt64, readInt64BigEndian
Definition at line 133 of file InputStream.cpp.
References read(), and beast::ByteOrder::swapIfBigEndian().
Referenced by readDouble().
 {
     union { std::uint8_t asBytes[8]; std::uint64_t asInt64; } n;
     if (read (n.asBytes, 8) == 8)
         return (std::int64_t) ByteOrder::swapIfBigEndian (n.asInt64);
     return 0;
 }
std::int64_t beast::InputStream::readInt64BigEndian () virtual
Reads eight bytes from the stream as a big-endian 64-bit value.
If the next eight bytes are byte1 to byte8, this returns (byte8 | (byte7 << 8) | (byte6 << 16) | (byte5 << 24) | (byte4 << 32) | (byte3 << 40) | (byte2 << 48) | (byte1 << 56)).
If the stream is exhausted partway through reading the bytes, this will return zero.
See Also
OutputStream::writeInt64BigEndian, readInt64
Definition at line 143 of file InputStream.cpp.
References read(), and beast::ByteOrder::swapIfLittleEndian().
Referenced by readDoubleBigEndian().
 {
     union { std::uint8_t asBytes[8]; std::uint64_t asInt64; } n;
     if (read (n.asBytes, 8) == 8)
         return (std::int64_t) ByteOrder::swapIfLittleEndian (n.asInt64);
     return 0;
 }
int beast::InputStream::readIntBigEndian () virtual
Definition at line 91 of file InputStream.cpp.
References beast::ByteOrder::bigEndianInt(), and read().
Referenced by readFloatBigEndian().
 {
     char temp[4];
     if (read (temp, 4) == 4)
         return (int) ByteOrder::bigEndianInt (temp);
     return 0;
 }
int beast::InputStream::readIntoMemoryBlock (MemoryBlock & destBlock, std::ptrdiff_t maxNumBytesToRead = -1) virtual
Reads from the stream and appends the data to a MemoryBlock.
Parameters
destBlock the block to append the data onto
maxNumBytesToRead if this is a positive value, it sets a limit to the number of bytes that will be read - if it's negative, data will be read until the stream is exhausted.
Returns
the number of bytes that were added to the memory block
Definition at line 233 of file InputStream.cpp.
References beast::MemoryOutputStream::writeFromInputStream().
Referenced by beast::File::loadFileAsData().
 {
     MemoryOutputStream mo (block, true);
     return mo.writeFromInputStream (*this, numBytes);
 }
String beast::InputStream::readNextLine () virtual
Reads a UTF-8 string from the stream, up to the next linefeed or carriage return.
This will read up to the next "\n" or "\r\n" or end-of-stream.
After this call, the stream's position will be left pointing to the next character following the line-feed, but the linefeeds aren't included in the string that is returned.
Definition at line 202 of file InputStream.cpp.
References beast::String::fromUTF8(), beast::MemoryBlock::getData(), getPosition(), beast::MemoryBlock::getSize(), readByte(), setPosition(), and beast::MemoryBlock::setSize().
 {
     MemoryBlock buffer (256);
     char* data = static_cast<char*> (buffer.getData());
     size_t i = 0;
     while ((data[i] = readByte()) != 0)
     {
         if (data[i] == '\n')
             break;
         if (data[i] == '\r')
         {
             const std::int64_t lastPos = getPosition();
             if (readByte() != '\n')
                 setPosition (lastPos);
             break;
         }
         if (++i >= buffer.getSize())
         {
             buffer.setSize (buffer.getSize() + 512);
             data = static_cast<char*> (buffer.getData());
         }
     }
     return String::fromUTF8 (data, (int) i);
 }
short beast::InputStream::readShort () virtual
Reads two bytes from the stream as a little-endian 16-bit value.
If the next two bytes read are byte1 and byte2, this returns (byte1 | (byte2 << 8)).
If the stream is exhausted partway through reading the bytes, this will return zero.
See Also
OutputStream::writeShort, readShortBigEndian
Definition at line 49 of file InputStream.cpp.
References beast::ByteOrder::littleEndianShort(), and read().
 {
     char temp[2];
     if (read (temp, 2) == 2)
         return (short) ByteOrder::littleEndianShort (temp);
     return 0;
 }
short beast::InputStream::readShortBigEndian () virtual
Reads two bytes from the stream as a little-endian 16-bit value.
If the next two bytes read are byte1 and byte2, this returns (byte1 | (byte2 << 8)).
If the stream is exhausted partway through reading the bytes, this will return zero.
See Also
OutputStream::writeShortBigEndian, readShort
Definition at line 59 of file InputStream.cpp.
References beast::ByteOrder::bigEndianShort(), and read().
 {
     char temp[2];
     if (read (temp, 2) == 2)
         return (short) ByteOrder::bigEndianShort (temp);
     return 0;
 }
String beast::InputStream::readString () virtual
Reads a zero-terminated UTF-8 string from the stream.
This will read characters from the stream until it hits a null character or end-of-stream.
See Also
OutputStream::writeString, readEntireStreamAsString
Definition at line 183 of file InputStream.cpp.
References beast::MemoryBlock::getData(), beast::MemoryBlock::getSize(), readByte(), and beast::MemoryBlock::setSize().
 {
     MemoryBlock buffer (256);
     char* data = static_cast<char*> (buffer.getData());
     size_t i = 0;
     while ((data[i] = readByte()) != 0)
     {
         if (++i >= buffer.getSize())
         {
             buffer.setSize (buffer.getSize() + 512);
             data = static_cast<char*> (buffer.getData());
         }
     }
     return String (CharPointer_UTF8 (data),
                    CharPointer_UTF8 (data + i));
 }
template<class T > T beast::InputStream::readType ()
Reads a type using a template specialization.
This is useful when doing template meta-programming.
template<> char beast::InputStream::readType ()
Definition at line 265 of file InputStream.cpp.
 { return readByte (); }
template<> short beast::InputStream::readType ()
Definition at line 268 of file InputStream.cpp.
 { return readShort (); }
template<> unsigned char beast::InputStream::readType ()
Definition at line 277 of file InputStream.cpp.
 { return static_cast <unsigned char> (readByte ()); }
template<> unsigned short beast::InputStream::readType ()
Definition at line 280 of file InputStream.cpp.
 { return static_cast <unsigned short> (readShort ()); }
template<> float beast::InputStream::readType ()
Definition at line 289 of file InputStream.cpp.
 { return readFloat (); }
template<> double beast::InputStream::readType ()
Definition at line 292 of file InputStream.cpp.
 { return readDouble (); }
template<class T > T beast::InputStream::readTypeBigEndian ()
Reads a type from a big endian stream using a template specialization.
The raw encoding of the type is read from the stream as a big-endian value where applicable.
This is useful when doing template meta-programming.
template<> char beast::InputStream::readTypeBigEndian ()
Definition at line 297 of file InputStream.cpp.
 { return readByte (); }
template<> short beast::InputStream::readTypeBigEndian ()
Definition at line 300 of file InputStream.cpp.
 { return readShortBigEndian (); }
template<> unsigned char beast::InputStream::readTypeBigEndian ()
Definition at line 309 of file InputStream.cpp.
 { return static_cast <unsigned char> (readByte ()); }
template<> unsigned short beast::InputStream::readTypeBigEndian ()
Definition at line 312 of file InputStream.cpp.
 { return static_cast <unsigned short> (readShortBigEndian ()); }
template<> float beast::InputStream::readTypeBigEndian ()
Definition at line 321 of file InputStream.cpp.
 { return readFloatBigEndian (); }
template<> double beast::InputStream::readTypeBigEndian ()
Definition at line 324 of file InputStream.cpp.
 { return readDoubleBigEndian (); }
template<class T > bool beast::InputStream::readTypeBigEndianInto (T * p) inline
Reads a type using a template specialization.
The variable is passed as a parameter so that the template type can be deduced. The return value indicates whether or not there was sufficient data in the stream to read the value.
Definition at line 275 of file InputStream.h.
References getNumBytesRemaining(), and T.
     {
         if (getNumBytesRemaining () >= sizeof (T))
         {
             *p = readTypeBigEndian <T> ();
             return true;
         }
         return false;
     }
template<class T > bool beast::InputStream::readTypeInto (T * p) inline
Reads a type using a template specialization.
The variable is passed as a parameter so that the template type can be deduced. The return value indicates whether or not there was sufficient data in the stream to read the value.
Definition at line 248 of file InputStream.h.
References getNumBytesRemaining(), and T.
     {
         if (getNumBytesRemaining () >= sizeof (T))
         {
             *p = readType <T> ();
             return true;
         }
         return false;
     }
virtual bool beast::InputStream::setPosition (std::int64_t newPosition) pure virtual
Tries to move the current read position of the stream.
The position is an absolute number of bytes from the stream's start.
Some streams might not be able to do this, in which case they should do nothing and return false. Others might be able to manage it by resetting themselves and skipping to the correct position, although this is obviously a bit slow.
Returns
true if the stream manages to reposition itself correctly
See Also
getPosition
Implemented in beast::FileInputStream.
Referenced by readNextLine().
void beast::InputStream::skipNextBytes (std::int64_t numBytesToSkip) virtual
Reads and discards a number of bytes from the stream.
Some input streams might implement this efficiently, but the base class will just keep reading data until the requisite number of bytes have been done.
Definition at line 247 of file InputStream.cpp.
References beast::bmin(), isExhausted(), and read().
 {
     if (numBytesToSkip > 0)
     {
         const int skipBufferSize = (int) bmin (numBytesToSkip, (std::int64_t) 16384);
         HeapBlock<char> temp ((size_t) skipBufferSize);
         while (numBytesToSkip > 0 && ! isExhausted())
             numBytesToSkip -= read (temp, (int) bmin (numBytesToSkip, (std::int64_t) skipBufferSize));
     }
 }
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_core/streams/InputStream.h
rippled/src/beast/modules/beast_core/streams/InputStream.cpp