rippled: ripple::SerializedTransaction_test Class Reference
ripple::SerializedTransaction_test Class Reference
Public Member Functions
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 369 of file SerializedTransaction.cpp.
Member Function Documentation
void ripple::SerializedTransaction_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 372 of file SerializedTransaction.cpp.
References ripple::STObject::add(), ripple::SerializedTransaction::checkSign(), ripple::RippleAddress::createAccountPrivate(), ripple::RippleAddress::createAccountPublic(), ripple::RippleAddress::createGeneratorPublic(), beast::unit_test::suite::fail(), ripple::RippleAddress::getAccountPublic(), ripple::SerializedTransaction::getJson(), beast::unit_test::suite::log, beast::unit_test::suite::pass(), ripple::STObject::setFieldVL(), ripple::RippleAddress::setSeedRandom(), ripple::SerializedTransaction::setSigningPubKey(), ripple::SerializedTransaction::setSourceAccount(), ripple::SerializedTransaction::sign(), ripple::ttACCOUNT_SET, and beast::unit_test::suite::unexpected().
     {
         RippleAddress seed;
         seed.setSeedRandom ();
         RippleAddress generator = RippleAddress::createGeneratorPublic (seed);
         RippleAddress publicAcct = RippleAddress::createAccountPublic (generator, 1);
         RippleAddress privateAcct = RippleAddress::createAccountPrivate (generator, seed, 1);
         SerializedTransaction j (ttACCOUNT_SET);
         j.setSourceAccount (publicAcct);
         j.setSigningPubKey (publicAcct);
         j.setFieldVL (sfMessageKey, publicAcct.getAccountPublic ());
         j.sign (privateAcct);
         unexpected (!j.checkSign (), "Transaction fails signature test");
         Serializer rawTxn;
         j.add (rawTxn);
         SerializerIterator sit (rawTxn);
         SerializedTransaction copy (sit);
         if (copy != j)
         {
             log << j.getJson (0);
             log << copy.getJson (0);
             fail ("Transaction fails serialize/deserialize test");
         }
         else
         {
             pass ();
         }
         STParsedJSON parsed ("test", j.getJson (0));
         std::unique_ptr <STObject> new_obj (std::move (parsed.object));
         if (new_obj.get () == nullptr)
             fail ("Unable to build object from json");
         if (STObject (j) != *new_obj)
         {
             log << "ORIG: " << j.getJson (0);
             log << "BUILT " << new_obj->getJson (0);
             fail ("Built a different transaction");
         }
         else
         {
             pass ();
         }
     }
The documentation for this class was generated from the following file:
rippled/src/ripple_app/misc/SerializedTransaction.cpp