rippled: beast.util.Terminal Namespace Reference
beast.util.Terminal Namespace Reference
Functions
def add_mode
def blue
def green
def red
def warn
Variables
tuple CAN_CHANGE_COLOR
int RED = 91
int GREEN = 92
int BLUE = 94
Function Documentation
def beast.util.Terminal.add_mode (text, modes)
Definition at line 19 of file Terminal.py.
Referenced by beast.util.Terminal.blue(), beast.util.Terminal.green(), and beast.util.Terminal.red().
 def add_mode(text, *modes):
     if CAN_CHANGE_COLOR:
         modes = ';'.join(str(m) for m in modes)
         return '\033[%sm%s\033[0m' % (modes, text)
     else:
         return text
def beast.util.Terminal.blue (text)
Definition at line 26 of file Terminal.py.
References beast.util.Terminal.add_mode().
 def blue(text):
     return add_mode(text, BLUE)
def beast.util.Terminal.green (text)
Definition at line 29 of file Terminal.py.
References beast.util.Terminal.add_mode().
 def green(text):
     return add_mode(text, GREEN)
def beast.util.Terminal.red (text)
Definition at line 32 of file Terminal.py.
References beast.util.Terminal.add_mode().
Referenced by beast.util.Terminal.warn().
 def red(text):
     return add_mode(text, RED)
def beast.util.Terminal.warn (text, print = print)
Definition at line 35 of file Terminal.py.
References beast::unit_test.print(), and beast.util.Terminal.red().
 def warn(text, print=print):
     print('%s %s' % (red('WARNING:'), text))
Variable Documentation
int beast.util.Terminal.BLUE = 94
Definition at line 17 of file Terminal.py.
tuple beast.util.Terminal.CAN_CHANGE_COLOR
Initial value:
 = (
     hasattr(sys.stderr, "isatty")
     and sys.stderr.isatty()
     and not PLATFORM.startswith('Windows'))
Definition at line 8 of file Terminal.py.
int beast.util.Terminal.GREEN = 92
Definition at line 16 of file Terminal.py.
int beast.util.Terminal.RED = 91
Definition at line 15 of file Terminal.py.