rippled: beast::insight::Meter Class Reference
beast::insight::Meter Class Reference
#include <Meter.h>
Public Types
typedef MeterImpl::value_type value_type
Public Member Functions
Meter ()
Meter (std::shared_ptr< MeterImpl > const &impl)
std::shared_ptr< MeterImpl >
const & impl () const
void increment (value_type amount) const
Meter const & operator+= (value_type amount) const
Meter const & operator++ () const
Meter const & operator++ (int) const
Public Member Functions inherited from beast::insight::Base
virtual ~Base ()=0
Private Attributes
std::shared_ptr< MeterImpl > m_impl
Detailed Description
A metric for measuring an integral value.
A meter may be thought of as an increment-only counter.
This is a lightweight reference wrapper which is cheap to copy and assign. When the last reference goes away, the metric is no longer collected.
Definition at line 38 of file Meter.h.
Member Typedef Documentation
typedef MeterImpl::value_type beast::insight::Meter::value_type
Definition at line 41 of file Meter.h.
Constructor & Destructor Documentation
beast::insight::Meter::Meter () inline
Create a null metric. A null metric reports no information.
Definition at line 46 of file Meter.h.
         { }
beast::insight::Meter::Meter (std::shared_ptr< MeterImpl > const & impl) inline explicit
Create the metric reference the specified implementation. Normally this won't be called directly. Instead, call the appropriate factory function in the Collector interface.
See Also
Collector.
Definition at line 54 of file Meter.h.
         : m_impl (impl)
         { }
Member Function Documentation
std::shared_ptr<MeterImpl> const& beast::insight::Meter::impl () const inline
Definition at line 85 of file Meter.h.
References m_impl.
     {
         return m_impl;
     }
void beast::insight::Meter::increment (value_type amount) const inline
Increment the meter.
Definition at line 60 of file Meter.h.
References m_impl.
Referenced by operator++(), and operator+=().
     {
         if (m_impl)
             m_impl->increment (amount);
     }
Meter const& beast::insight::Meter::operator++ () const inline
Definition at line 72 of file Meter.h.
References increment().
     {
         increment (1);
         return *this;
     }
Meter const& beast::insight::Meter::operator++ (int) const inline
Definition at line 78 of file Meter.h.
References increment().
     {
         increment (1);
         return *this;
     }
Meter const& beast::insight::Meter::operator+= (value_type amount) const inline
Definition at line 66 of file Meter.h.
References increment().
     {
         increment (amount);
         return *this;
     }
Member Data Documentation
std::shared_ptr<MeterImpl> beast::insight::Meter::m_impl private
Definition at line 91 of file Meter.h.
Referenced by impl(), and increment().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/insight/Meter.h