rippled: ripple::AccountItems Class Reference
ripple::AccountItems Class Reference
#include <AccountItems.h>
Public Types
typedef boost::shared_ptr
< AccountItems > pointer
typedef std::vector
< AccountItem::pointer > Container
Public Member Functions
AccountItems (uint160 const &accountID, Ledger::ref ledger, AccountItem::pointer ofType)
Container & getItems ()
Json::Value getJson (int)
Private Member Functions
void fillItems (const uint160 &accountID, Ledger::ref ledger)
Private Attributes
AccountItem::pointer mOfType
Container mItems
Detailed Description
A set of AccountItem objects.
Definition at line 26 of file AccountItems.h.
Member Typedef Documentation
typedef std::vector<AccountItem::pointer> ripple::AccountItems::Container
Definition at line 31 of file AccountItems.h.
typedef boost::shared_ptr<AccountItems> ripple::AccountItems::pointer
Definition at line 29 of file AccountItems.h.
Constructor & Destructor Documentation
ripple::AccountItems::AccountItems (uint160 const & accountID, Ledger::ref ledger, AccountItem::pointer ofType)
Definition at line 22 of file AccountItems.cpp.
References fillItems(), and mOfType.
 {
     mOfType = ofType;
     fillItems (accountID, ledger);
 }
Member Function Documentation
void ripple::AccountItems::fillItems (const uint160 & accountID, Ledger::ref ledger) private
Definition at line 31 of file AccountItems.cpp.
References ripple::Ledger::getDirNodeIndex(), ripple::Ledger::getOwnerDirIndex(), mItems, and mOfType.
Referenced by AccountItems().
 {
     uint256 const rootIndex = Ledger::getOwnerDirIndex (accountID);
     uint256 currentIndex    = rootIndex;
     // VFALCO TODO Rewrite all infinite loops to have clear terminating
     //             conditions defined in one location.
     //
     while (1)
     {
         SLE::pointer ownerDir   = ledger->getDirNode (currentIndex);
         // VFALCO TODO Rewrite to not return from the middle of the function
         if (!ownerDir)
             return;
         BOOST_FOREACH (uint256 const & uNode, ownerDir->getFieldV256 (sfIndexes).peekValue ())
         {
             // VFALCO TODO rename getSLEi() to something legible.
             SLE::pointer sleCur = ledger->getSLEi (uNode);
             if (!sleCur)
             {
                 // item in directory not in ledger
             }
             else
             {
                 AccountItem::pointer item = mOfType->makeItem (accountID, sleCur);
                 // VFALCO NOTE Under what conditions would makeItem() return nullptr?
                 // DJS NOTE If the item wasn't one this particular AccountItems was interested in
                 // (For example, if the owner is only interested in ripple lines and this is an offer)
                 if (item)
                 {
                     mItems.push_back (item);
                 }
             }
         }
         std::uint64_t uNodeNext    = ownerDir->getFieldU64 (sfIndexNext);
         // VFALCO TODO Rewrite to not return from the middle of the function
         if (!uNodeNext)
             return;
         currentIndex = Ledger::getDirNodeIndex (rootIndex, uNodeNext);
     }
 }
Container& ripple::AccountItems::getItems () inline
Definition at line 41 of file AccountItems.h.
References mItems.
Referenced by ripple::usAccountDestCurrencies(), and ripple::usAccountSourceCurrencies().
     {
         return mItems;
     }
Json::Value ripple::AccountItems::getJson (int v)
Definition at line 80 of file AccountItems.cpp.
References Json::Value::append(), Json::arrayValue, and mItems.
 {
     Json::Value ret (Json::arrayValue);
     BOOST_FOREACH (AccountItem::ref ai, mItems)
     {
         ret.append (ai->getJson (v));
     }
     return ret;
 }
Member Data Documentation
Container ripple::AccountItems::mItems private
Definition at line 56 of file AccountItems.h.
Referenced by fillItems(), getItems(), and getJson().
AccountItem::pointer ripple::AccountItems::mOfType private
Definition at line 54 of file AccountItems.h.
Referenced by AccountItems(), and fillItems().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/misc/AccountItems.h
rippled/src/ripple_app/misc/AccountItems.cpp