rippled: rocksdb::BlobStore Class Reference
rocksdb::BlobStore Class Reference
#include <blob_store.h>
Public Member Functions
BlobStore (const std::string &directory, uint64_t block_size, uint32_t blocks_per_bucket, uint32_t max_buckets, Env *env)
~BlobStore ()
Status Put (const Slice &value, Blob *blob)
Status Get (const Blob &blob, std::string *value) const
Status Delete (const Blob &blob)
Status Sync ()
Private Member Functions
Status Allocate (uint32_t blocks, Blob *blob)
Status CreateNewBucket ()
Private Attributes
const std::string directory_
const uint64_t block_size_
const uint32_t blocks_per_bucket_
Env * env_
EnvOptions storage_options_
FreeList free_list_
port::Mutex free_list_mutex_
unique_ptr< RandomRWFile > * buckets_
uint32_t buckets_size_
uint32_t max_buckets_
port::Mutex buckets_mutex_
Detailed Description
Definition at line 96 of file blob_store.h.
Constructor & Destructor Documentation
rocksdb::BlobStore::BlobStore (const std::string & directory, uint64_t block_size, uint32_t blocks_per_bucket, uint32_t max_buckets, Env * env)
Definition at line 106 of file blob_store.cc.
References buckets_, buckets_size_, rocksdb::Env::CreateDirIfMissing(), CreateNewBucket(), directory_, env_, max_buckets_, storage_options_, rocksdb::EnvOptions::use_mmap_reads, and rocksdb::EnvOptions::use_mmap_writes.
                                :
     directory_(directory),
     block_size_(block_size),
     blocks_per_bucket_(blocks_per_bucket),
     env_(env),
     max_buckets_(max_buckets) {
   env_->CreateDirIfMissing(directory_);
   storage_options_.use_mmap_writes = false;
   storage_options_.use_mmap_reads = false;
   buckets_size_ = 0;
   buckets_ = new unique_ptr<RandomRWFile>[max_buckets_];
   CreateNewBucket();
 }
rocksdb::BlobStore::~BlobStore ()
Definition at line 127 of file blob_store.cc.
References buckets_.
                       {
   // TODO we don't care about recovery for now
   delete [] buckets_;
 }
Member Function Documentation
Status rocksdb::BlobStore::Allocate (uint32_t blocks, Blob * blob) private
Definition at line 218 of file blob_store.cc.
References rocksdb::FreeList::Allocate(), CreateNewBucket(), free_list_, free_list_mutex_, and rocksdb::Status::ok().
Referenced by Put().
{
   MutexLock l(&free_list_mutex_);
   Status s;
   s = free_list_.Allocate(blocks, blob);
   if (!s.ok()) {
     s = CreateNewBucket();
     if (!s.ok()) {
       return s;
     }
     s = free_list_.Allocate(blocks, blob);
   }
   return s;
 }
Status rocksdb::BlobStore::CreateNewBucket () private
Definition at line 235 of file blob_store.cc.
References block_size_, blocks_per_bucket_, buckets_, buckets_mutex_, buckets_size_, directory_, env_, rocksdb::FreeList::Free(), free_list_, rocksdb::Status::IOError(), max_buckets_, rocksdb::Env::NewRandomRWFile(), and storage_options_.
Referenced by Allocate(), and BlobStore().
{
   MutexLock l(&buckets_mutex_);
   if (buckets_size_ >= max_buckets_) {
     return Status::IOError("Max size exceeded\n");
   }
   int new_bucket_id = buckets_size_;
   char fname[200];
   sprintf(fname, "%s/%d.bs", directory_.c_str(), new_bucket_id);
   Status s = env_->NewRandomRWFile(string(fname),
                                    &buckets_[new_bucket_id],
                                    storage_options_);
   if (!s.ok()) {
     return s;
   }
   // whether Allocate succeeds or not, does not affect the overall correctness
   // of this function - calling Allocate is really optional
   // (also, tmpfs does not support allocate)
   buckets_[new_bucket_id].get()->Allocate(0, block_size_ * blocks_per_bucket_);
   buckets_size_ = new_bucket_id + 1;
   return free_list_.Free(Blob(new_bucket_id, 0, blocks_per_bucket_));
 }
Status rocksdb::BlobStore::Delete (const Blob & blob)
Definition at line 203 of file blob_store.cc.
References rocksdb::FreeList::Free(), free_list_, and free_list_mutex_.
Referenced by Put(), rocksdb::TEST(), and WorkerThreadBody().
{
   MutexLock l(&free_list_mutex_);
   return free_list_.Free(blob);
 }
Status rocksdb::BlobStore::Get (const Blob & blob, std::string * value) const
Definition at line 170 of file blob_store.cc.
References block_size_, buckets_, buckets_size_, rocksdb::Blob::chunks, free_list_, free_list_mutex_, rocksdb::Status::IOError(), rocksdb::Status::OK(), rocksdb::Status::ok(), rocksdb::FreeList::Overlap(), rocksdb::Slice::size(), and rocksdb::Blob::Size().
Referenced by rocksdb::TEST(), and WorkerThreadBody().
{
   {
     // assert that it doesn't overlap with free list
     // it will get compiled out for release
     MutexLock l(&free_list_mutex_);
     assert(!free_list_.Overlap(blob));
   }
   value->resize(blob.Size() * block_size_);
   uint64_t offset = 0; // in bytes, not blocks
   for (auto chunk : blob.chunks) {
     Slice result;
     assert(chunk.bucket_id < buckets_size_);
     Status s;
     s = buckets_[chunk.bucket_id].get()->Read(chunk.offset * block_size_,
                                               chunk.size * block_size_,
                                               &result,
                                               &value->at(offset));
     if (!s.ok() || result.size() < chunk.size * block_size_) {
       value->clear();
       return Status::IOError("Could not read in from file");
     }
     offset += chunk.size * block_size_;
   }
   // remove the '\0's at the end of the string
   value->erase(find(value->begin(), value->end(), '\0'), value->end());
   return Status::OK();
 }
Status rocksdb::BlobStore::Put (const Slice & value, Blob * blob)
Definition at line 132 of file blob_store.cc.
References Allocate(), block_size_, buckets_, buckets_size_, rocksdb::Blob::chunks, rocksdb::Slice::data(), Delete(), rocksdb::Status::IOError(), ripple::min(), rocksdb::Status::OK(), rocksdb::Status::ok(), and rocksdb::Slice::size().
Referenced by rocksdb::TEST(), and WorkerThreadBody().
{
   // convert size to number of blocks
   Status s = Allocate((value.size() + block_size_ - 1) / block_size_, blob);
   if (!s.ok()) {
     return s;
   }
   auto size_left = (uint64_t) value.size();
   uint64_t offset = 0; // in bytes, not blocks
   for (auto chunk : blob->chunks) {
     uint64_t write_size = min(chunk.size * block_size_, size_left);
     assert(chunk.bucket_id < buckets_size_);
     s = buckets_[chunk.bucket_id].get()->Write(chunk.offset * block_size_,
                                                Slice(value.data() + offset,
                                                      write_size));
     if (!s.ok()) {
       Delete(*blob);
       return s;
     }
     offset += write_size;
     size_left -= write_size;
     if (write_size < chunk.size * block_size_) {
       // if we have any space left in the block, fill it up with zeros
       string zero_string(chunk.size * block_size_ - write_size, 0);
       s = buckets_[chunk.bucket_id].get()->Write(chunk.offset * block_size_ +
                                                     write_size,
                                                  Slice(zero_string));
     }
   }
   if (size_left > 0) {
     Delete(*blob);
     return Status::IOError("Tried to write more data than fits in the blob");
   }
   return Status::OK();
 }
Status rocksdb::BlobStore::Sync ()
Definition at line 208 of file blob_store.cc.
References buckets_, buckets_size_, rocksdb::Status::OK(), and rocksdb::Status::ok().
Referenced by rocksdb::TEST().
{
   for (size_t i = 0; i < buckets_size_; ++i) {
     Status s = buckets_[i].get()->Sync();
     if (!s.ok()) {
       return s;
     }
   }
   return Status::OK();
 }
Member Data Documentation
const uint64_t rocksdb::BlobStore::block_size_ private
Definition at line 135 of file blob_store.h.
Referenced by CreateNewBucket(), Get(), and Put().
const uint32_t rocksdb::BlobStore::blocks_per_bucket_ private
Definition at line 136 of file blob_store.h.
Referenced by CreateNewBucket().
unique_ptr<RandomRWFile>* rocksdb::BlobStore::buckets_ private
Definition at line 145 of file blob_store.h.
Referenced by BlobStore(), CreateNewBucket(), Get(), Put(), Sync(), and ~BlobStore().
port::Mutex rocksdb::BlobStore::buckets_mutex_ mutable private
Definition at line 149 of file blob_store.h.
Referenced by CreateNewBucket().
uint32_t rocksdb::BlobStore::buckets_size_ private
Definition at line 147 of file blob_store.h.
Referenced by BlobStore(), CreateNewBucket(), Get(), Put(), and Sync().
const std::string rocksdb::BlobStore::directory_ private
Definition at line 131 of file blob_store.h.
Referenced by BlobStore(), and CreateNewBucket().
Env* rocksdb::BlobStore::env_ private
Definition at line 137 of file blob_store.h.
Referenced by BlobStore(), and CreateNewBucket().
FreeList rocksdb::BlobStore::free_list_ private
Definition at line 140 of file blob_store.h.
Referenced by Allocate(), CreateNewBucket(), Delete(), and Get().
port::Mutex rocksdb::BlobStore::free_list_mutex_ mutable private
Definition at line 142 of file blob_store.h.
Referenced by Allocate(), Delete(), and Get().
uint32_t rocksdb::BlobStore::max_buckets_ private
Definition at line 148 of file blob_store.h.
Referenced by BlobStore(), and CreateNewBucket().
EnvOptions rocksdb::BlobStore::storage_options_ private
Definition at line 138 of file blob_store.h.
Referenced by BlobStore(), and CreateNewBucket().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/util/blob_store.h
rippled/src/ripple/rocksdb/rocksdb/util/blob_store.cc