rippled: beast::FileInputSource Class Reference
beast::FileInputSource Class Reference
#include <FileInputSource.h>
Public Member Functions
FileInputSource (const File &file, bool useFileTimeInHashGeneration=false)
~FileInputSource ()
InputStream * createInputStream ()
InputStream * createInputStreamFor (const String &relatedItemPath)
std::int64_t hashCode () const
Public Member Functions inherited from beast::InputSource
InputSource () noexcept
virtual ~InputSource ()
Private Attributes
const File file
bool useFileTimeInHashGeneration
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
A type of InputSource that represents a normal file.
See Also
InputSource
Definition at line 36 of file FileInputSource.h.
Constructor & Destructor Documentation
beast::FileInputSource::FileInputSource (const File & file, bool useFileTimeInHashGeneration = false)
Creates a FileInputSource for a file. If the useFileTimeInHashGeneration parameter is true, then this object's hashCode() method will incorporate the file time into its hash code; if false, only the file name will be used for the hash.
Definition at line 27 of file FileInputSource.cpp.
     : file (f), useFileTimeInHashGeneration (useFileTimeInHash)
 {
 }
beast::FileInputSource::~FileInputSource ()
Destructor.
Definition at line 32 of file FileInputSource.cpp.
 {
 }
Member Function Documentation
InputStream * beast::FileInputSource::createInputStream () virtual
Returns a new InputStream to read this item.
Returns
an inputstream that the caller will delete, or nullptr if the filename isn't found.
Implements beast::InputSource.
Definition at line 36 of file FileInputSource.cpp.
References beast::File::createInputStream(), and file.
 {
     return file.createInputStream();
 }
InputStream * beast::FileInputSource::createInputStreamFor (const String & relatedItemPath) virtual
Returns a new InputStream to read an item, relative.
Parameters
relatedItemPath the relative pathname of the resource that is required
Returns
an inputstream that the caller will delete, or nullptr if the item isn't found.
Implements beast::InputSource.
Definition at line 41 of file FileInputSource.cpp.
References beast::File::createInputStream(), file, and beast::File::getSiblingFile().
 {
     return file.getSiblingFile (relatedItemPath).createInputStream();
 }
std::int64_t beast::FileInputSource::hashCode () const virtual
Returns a hash code that uniquely represents this item.
Implements beast::InputSource.
Definition at line 46 of file FileInputSource.cpp.
References file, beast::File::getLastModificationTime(), beast::File::hashCode(), beast::Time::toMilliseconds(), and useFileTimeInHashGeneration.
 {
     std::int64_t h = file.hashCode();
     if (useFileTimeInHashGeneration)
         h ^= file.getLastModificationTime().toMilliseconds();
     return h;
 }
Member Data Documentation
const File beast::FileInputSource::file private
Definition at line 59 of file FileInputSource.h.
Referenced by createInputStream(), createInputStreamFor(), and hashCode().
bool beast::FileInputSource::useFileTimeInHashGeneration private
Definition at line 60 of file FileInputSource.h.
Referenced by hashCode().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_core/streams/FileInputSource.h
rippled/src/beast/modules/beast_core/streams/FileInputSource.cpp