rippled: rocksdb::DBImplReadOnly Class Reference
rocksdb::DBImplReadOnly Class Reference
#include <db_impl_readonly.h>
Public Member Functions
DBImplReadOnly (const Options &options, const std::string &dbname)
virtual ~DBImplReadOnly ()
virtual Status Get (const ReadOptions &options, const Slice &key, std::string *value)
virtual Iterator * NewIterator (const ReadOptions &)
virtual Status Put (const WriteOptions &, const Slice &key, const Slice &value)
virtual Status Merge (const WriteOptions &, const Slice &key, const Slice &value)
virtual Status Delete (const WriteOptions &, const Slice &key)
virtual Status Write (const WriteOptions &options, WriteBatch *updates)
virtual void CompactRange (const Slice *begin, const Slice *end, bool reduce_level=false, int target_level=-1)
virtual Status DisableFileDeletions ()
virtual Status EnableFileDeletions ()
virtual Status GetLiveFiles (std::vector< std::string > &, uint64_t *manifest_file_size, bool flush_memtable=true)
virtual Status Flush (const FlushOptions &options)
Public Member Functions inherited from rocksdb::DBImpl
DBImpl (const Options &options, const std::string &dbname)
virtual ~DBImpl ()
virtual std::vector< Status > MultiGet (const ReadOptions &options, const std::vector< Slice > &keys, std::vector< std::string > *values)
virtual bool KeyMayExist (const ReadOptions &options, const Slice &key, std::string *value, bool *value_found=nullptr)
virtual const Snapshot * GetSnapshot ()
virtual void ReleaseSnapshot (const Snapshot *snapshot)
virtual bool GetProperty (const Slice &property, std::string *value)
virtual void GetApproximateSizes (const Range *range, int n, uint64_t *sizes)
virtual int NumberLevels ()
virtual int MaxMemCompactionLevel ()
virtual int Level0StopWriteTrigger ()
virtual Status GetSortedWalFiles (VectorLogPtr &files)
virtual SequenceNumber GetLatestSequenceNumber () const
virtual Status GetUpdatesSince (SequenceNumber seq_number, unique_ptr< TransactionLogIterator > *iter)
virtual Status DeleteFile (std::string name)
virtual void GetLiveFilesMetaData (std::vector< LiveFileMetaData > *metadata)
void TEST_CompactRange (int level, const Slice *begin, const Slice *end)
Status TEST_FlushMemTable ()
Status TEST_WaitForFlushMemTable ()
Status TEST_WaitForCompact ()
Iterator * TEST_NewInternalIterator ()
int64_t TEST_MaxNextLevelOverlappingBytes ()
void TEST_Destroy_DBImpl ()
uint64_t TEST_Current_Manifest_FileNo ()
void TEST_PurgeObsoleteteWAL ()
uint64_t TEST_GetLevel0TotalSize ()
void TEST_SetDefaultTimeToCheck (uint64_t default_interval_to_delete_obsolete_WAL)
void FindObsoleteFiles (DeletionState &deletion_state, bool force, bool no_full_scan=false)
void PurgeObsoleteFiles (DeletionState &deletion_state)
Public Member Functions inherited from rocksdb::DB
DB ()
virtual ~DB ()
Private Member Functions
DBImplReadOnly (const DBImplReadOnly &)
void operator= (const DBImplReadOnly &)
Friends
class DB
Additional Inherited Members
Static Public Member Functions inherited from rocksdb::DB
static Status Open (const Options &options, const std::string &name, DB **dbptr)
static Status OpenForReadOnly (const Options &options, const std::string &name, DB **dbptr, bool error_if_log_file_exist=false)
Protected Member Functions inherited from rocksdb::DBImpl
const Comparator * user_comparator () const
MemTable * GetMemTable ()
Iterator * NewInternalIterator (const ReadOptions &, SequenceNumber *latest_snapshot)
Protected Attributes inherited from rocksdb::DBImpl
Env *const env_
const std::string dbname_
unique_ptr< VersionSet > versions_
const InternalKeyComparator internal_comparator_
const Options options_
Detailed Description
Definition at line 25 of file db_impl_readonly.h.
Constructor & Destructor Documentation
rocksdb::DBImplReadOnly::DBImplReadOnly (const Options & options, const std::string & dbname)
Definition at line 43 of file db_impl_readonly.cc.
References rocksdb::Options::info_log, rocksdb::Log(), and rocksdb::DBImpl::options_.
     : DBImpl(options, dbname) {
   Log(options_.info_log, "Opening the db in read only mode");
 }
rocksdb::DBImplReadOnly::~DBImplReadOnly () virtual
Definition at line 49 of file db_impl_readonly.cc.
{
 }
rocksdb::DBImplReadOnly::DBImplReadOnly (const DBImplReadOnly &) private
Member Function Documentation
virtual void rocksdb::DBImplReadOnly::CompactRange (const Slice * begin, const Slice * end, bool reduce_level = false, int target_level = -1) inline virtual
Reimplemented from rocksdb::DBImpl.
Definition at line 52 of file db_impl_readonly.h.
{
  }
virtual Status rocksdb::DBImplReadOnly::Delete (const WriteOptions & , const Slice & key) inline virtual
Reimplemented from rocksdb::DBImpl.
Definition at line 46 of file db_impl_readonly.h.
References rocksdb::Status::NotSupported().
{
    return Status::NotSupported("Not supported operation in read only mode.");
  }
virtual Status rocksdb::DBImplReadOnly::DisableFileDeletions () inline virtual
Reimplemented from rocksdb::DBImpl.
Definition at line 55 of file db_impl_readonly.h.
References rocksdb::Status::NotSupported().
{
    return Status::NotSupported("Not supported operation in read only mode.");
  }
virtual Status rocksdb::DBImplReadOnly::EnableFileDeletions () inline virtual
Reimplemented from rocksdb::DBImpl.
Definition at line 58 of file db_impl_readonly.h.
References rocksdb::Status::NotSupported().
{
    return Status::NotSupported("Not supported operation in read only mode.");
  }
virtual Status rocksdb::DBImplReadOnly::Flush (const FlushOptions & options) inline virtual
Reimplemented from rocksdb::DBImpl.
Definition at line 66 of file db_impl_readonly.h.
References rocksdb::Status::NotSupported().
{
    return Status::NotSupported("Not supported operation in read only mode.");
  }
Status rocksdb::DBImplReadOnly::Get (const ReadOptions & options, const Slice & key, std::string * value) virtual
Reimplemented from rocksdb::DBImpl.
Definition at line 53 of file db_impl_readonly.cc.
References rocksdb::Version::Get(), rocksdb::MemTable::Get(), rocksdb::DBImpl::GetMemTable(), mem, merge_operands, rocksdb::DBImpl::options_, stats, and rocksdb::DBImpl::versions_.
{
   Status s;
   MemTable* mem = GetMemTable();
   Version* current = versions_->current();
   SequenceNumber snapshot = versions_->LastSequence();
   std::deque<std::string> merge_operands;
   LookupKey lkey(key, snapshot);
   if (mem->Get(lkey, value, &s, &merge_operands, options_)) {
   } else {
     Version::GetStats stats;
     current->Get(options, lkey, value, &s, &merge_operands, &stats, options_);
   }
   return s;
 }
virtual Status rocksdb::DBImplReadOnly::GetLiveFiles (std::vector< std::string > & , uint64_t * manifest_file_size, bool flush_memtable = true) inline virtual
Reimplemented from rocksdb::DBImpl.
Definition at line 61 of file db_impl_readonly.h.
References rocksdb::Status::NotSupported().
{
    return Status::NotSupported("Not supported operation in read only mode.");
  }
virtual Status rocksdb::DBImplReadOnly::Merge (const WriteOptions & , const Slice & key, const Slice & value) inline virtual
Reimplemented from rocksdb::DBImpl.
Definition at line 42 of file db_impl_readonly.h.
References rocksdb::Status::NotSupported().
{
    return Status::NotSupported("Not supported operation in read only mode.");
  }
Iterator * rocksdb::DBImplReadOnly::NewIterator (const ReadOptions & options) virtual
Reimplemented from rocksdb::DBImpl.
Definition at line 70 of file db_impl_readonly.cc.
References rocksdb::DBImpl::dbname_, rocksdb::DBImpl::env_, rocksdb::NewDBIterator(), rocksdb::DBImpl::NewInternalIterator(), rocksdb::DBImpl::options_, rocksdb::ReadOptions::snapshot, and rocksdb::DBImpl::user_comparator().
{
   SequenceNumber latest_snapshot;
   Iterator* internal_iter = NewInternalIterator(options, &latest_snapshot);
   return NewDBIterator(
     &dbname_, env_, options_,  user_comparator(),internal_iter,
       (options.snapshot != nullptr
       ? reinterpret_cast<const SnapshotImpl*>(options.snapshot)->number_
       : latest_snapshot));
 }
void rocksdb::DBImplReadOnly::operator= (const DBImplReadOnly &) private
virtual Status rocksdb::DBImplReadOnly::Put (const WriteOptions & , const Slice & key, const Slice & value) inline virtual
Reimplemented from rocksdb::DBImpl.
Definition at line 39 of file db_impl_readonly.h.
References rocksdb::Status::NotSupported().
{
    return Status::NotSupported("Not supported operation in read only mode.");
  }
virtual Status rocksdb::DBImplReadOnly::Write (const WriteOptions & options, WriteBatch * updates) inline virtual
Reimplemented from rocksdb::DBImpl.
Definition at line 49 of file db_impl_readonly.h.
References rocksdb::Status::NotSupported().
{
    return Status::NotSupported("Not supported operation in read only mode.");
  }
Friends And Related Function Documentation
friend class DB friend
Definition at line 71 of file db_impl_readonly.h.
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/db/db_impl_readonly.h
rippled/src/ripple/rocksdb/rocksdb/db/db_impl_readonly.cc