rippled: beast::sqdb::detail::prepare_temp_type Class Reference
beast::sqdb::detail::prepare_temp_type Class Reference
#include <prepare_temp_type.h>
Public Member Functions
prepare_temp_type (session &s)
prepare_temp_type (prepare_temp_type const &o)
prepare_temp_type & operator= (prepare_temp_type const &o)
~prepare_temp_type ()
template<typename T >
prepare_temp_type & operator<< (T const &t)
prepare_temp_type & operator, (into_type_ptr const &i)
prepare_temp_type & operator, (use_type_ptr const &u)
ref_counted_prepare_info & get_prepare_info () const
Private Attributes
ref_counted_prepare_info * m_rcpi
Detailed Description
Definition at line 68 of file prepare_temp_type.h.
Constructor & Destructor Documentation
beast::sqdb::detail::prepare_temp_type::prepare_temp_type (session & s)
Definition at line 64 of file prepare_temp_type.cpp.
References beast::sqdb::session::get_query_stream().
     : m_rcpi(new ref_counted_prepare_info(s))
 {
     // new query
     s.get_query_stream().str("");
 }
beast::sqdb::detail::prepare_temp_type::prepare_temp_type (prepare_temp_type const & o)
Definition at line 71 of file prepare_temp_type.cpp.
References beast::sqdb::detail::ref_counted_statement_base::addref(), and m_rcpi.
     : m_rcpi(o.m_rcpi)
 {
     m_rcpi->addref();
 }
beast::sqdb::detail::prepare_temp_type::~prepare_temp_type ()
Definition at line 85 of file prepare_temp_type.cpp.
References m_rcpi, and beast::sqdb::detail::ref_counted_statement_base::release().
 {
     m_rcpi->release();
 }
Member Function Documentation
ref_counted_prepare_info& beast::sqdb::detail::prepare_temp_type::get_prepare_info () const inline
Definition at line 87 of file prepare_temp_type.h.
References m_rcpi.
Referenced by beast::sqdb::detail::statement_imp::statement_imp().
     {
         return *m_rcpi;
     }
prepare_temp_type & beast::sqdb::detail::prepare_temp_type::operator, (into_type_ptr const & i)
Definition at line 90 of file prepare_temp_type.cpp.
References beast::sqdb::detail::ref_counted_prepare_info::exchange(), and m_rcpi.
 {
     m_rcpi->exchange(i);
     return *this;
 }
prepare_temp_type & beast::sqdb::detail::prepare_temp_type::operator, (use_type_ptr const & u)
Definition at line 96 of file prepare_temp_type.cpp.
References beast::sqdb::detail::ref_counted_prepare_info::exchange(), and m_rcpi.
 {
     m_rcpi->exchange(u);
     return *this;
 }
template<typename T > prepare_temp_type& beast::sqdb::detail::prepare_temp_type::operator<< (T const & t) inline
Definition at line 78 of file prepare_temp_type.h.
References beast::sqdb::detail::ref_counted_statement_base::accumulate(), and m_rcpi.
     {
         m_rcpi->accumulate(t);
         return *this;
     }
prepare_temp_type & beast::sqdb::detail::prepare_temp_type::operator= (prepare_temp_type const & o)
Definition at line 77 of file prepare_temp_type.cpp.
References beast::sqdb::detail::ref_counted_statement_base::addref(), m_rcpi, and beast::sqdb::detail::ref_counted_statement_base::release().
 {
     o.m_rcpi->addref();
     m_rcpi->release();
     m_rcpi = o.m_rcpi;
     return *this;
 }
Member Data Documentation
ref_counted_prepare_info* beast::sqdb::detail::prepare_temp_type::m_rcpi private
Definition at line 93 of file prepare_temp_type.h.
Referenced by get_prepare_info(), operator,(), operator<<(), operator=(), prepare_temp_type(), and ~prepare_temp_type().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_sqdb/detail/prepare_temp_type.h
rippled/src/beast/modules/beast_sqdb/source/prepare_temp_type.cpp