rippled: rocksdb::SequentialFile Class Reference
rocksdb::SequentialFile Class Reference abstract
#include <env.h>
Public Member Functions
SequentialFile ()
virtual ~SequentialFile ()
virtual Status Read (size_t n, Slice *result, char *scratch)=0
virtual Status Skip (uint64_t n)=0
virtual Status InvalidateCache (size_t offset, size_t length)
Detailed Description
Definition at line 249 of file env.h.
Constructor & Destructor Documentation
rocksdb::SequentialFile::SequentialFile () inline
Definition at line 251 of file env.h.
 { }
rocksdb::SequentialFile::~SequentialFile () virtual
Definition at line 18 of file env.cc.
{
 }
Member Function Documentation
virtual Status rocksdb::SequentialFile::InvalidateCache (size_t offset, size_t length) inline virtual
Definition at line 276 of file env.h.
References rocksdb::Status::NotSupported().
{
     return Status::NotSupported("InvalidateCache not supported.");
   }
virtual Status rocksdb::SequentialFile::Read (size_t n, Slice * result, char * scratch) pure virtual
Implemented in rocksdb::log::LogTest::StringSource.
Referenced by rocksdb::ReadFileToString(), and rocksdb::TEST().
virtual Status rocksdb::SequentialFile::Skip (uint64_t n) pure virtual
Implemented in rocksdb::log::LogTest::StringSource.
Referenced by rocksdb::TEST().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/include/rocksdb/env.h
rippled/src/ripple/rocksdb/rocksdb/util/env.cc