rippled: ripple::HTTP::ServerImpl Class Reference
ripple::HTTP::ServerImpl Class Reference
#include <ServerImpl.h>
Classes
struct State
Public Types
typedef beast::SharedData< State > SharedState
typedef std::vector
< beast::SharedPtr< Door > > Doors
Public Types inherited from beast::Thread
typedef void * ThreadID
Public Member Functions
ServerImpl (Server &server, Handler &handler, beast::Journal journal)
~ServerImpl ()
beast::Journal const & journal () const
Ports const & getPorts () const
void setPorts (Ports const &ports)
bool stopping () const
void stop (bool wait)
Handler & handler ()
boost::asio::io_service & get_io_service ()
void add (Peer &peer)
void add (Door &door)
void remove (Peer &peer)
void remove (Door &door)
void handle_update ()
void update ()
void run ()
Public Member Functions inherited from beast::Thread
Thread (const String &threadName)
virtual ~Thread ()
void startThread ()
void startThread (int priority)
bool stopThread (int timeOutMilliseconds=-1)
void stopThreadAsync ()
bool isThreadRunning () const
void signalThreadShouldExit ()
bool threadShouldExit () const
bool waitForThreadToExit (int timeOutMilliseconds=-1) const
bool setPriority (int priority)
void setAffinityMask (std::uint32_t affinityMask)
bool wait (int timeOutMilliseconds=-1) const
void notify () const
ThreadID getThreadId () const noexcept
const String & getThreadName () const
Static Public Member Functions
static int compare (Port const &lhs, Port const &rhs)
Static Public Member Functions inherited from beast::Thread
static bool setCurrentThreadPriority (int priority)
static void setCurrentThreadAffinityMask (std::uint32_t affinityMask)
static void sleep (int milliseconds)
static void yield ()
static ThreadID getCurrentThreadId ()
static Thread * getCurrentThread ()
static void setCurrentThreadName (const String &newThreadName)
Public Attributes
Server & m_server
Handler & m_handler
beast::Journal m_journal
boost::asio::io_service m_io_service
boost::asio::io_service::strand m_strand
boost::optional
< boost::asio::io_service::work > m_work
beast::WaitableEvent m_stopped
SharedState m_state
Doors m_doors
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
Definition at line 29 of file ServerImpl.h.
Member Typedef Documentation
typedef std::vector<beast::SharedPtr <Door> > ripple::HTTP::ServerImpl::Doors
Definition at line 45 of file ServerImpl.h.
typedef beast::SharedData<State> ripple::HTTP::ServerImpl::SharedState
Definition at line 44 of file ServerImpl.h.
Constructor & Destructor Documentation
ripple::HTTP::ServerImpl::ServerImpl (Server & server, Handler & handler, beast::Journal journal)
Definition at line 23 of file ServerImpl.cpp.
References beast::Thread::startThread().
     : Thread ("HTTP::Server")
     , m_server (server)
     , m_handler (handler)
     , m_journal (journal)
     , m_strand (m_io_service)
     , m_work (boost::in_place (boost::ref (m_io_service)))
     , m_stopped (true)
 {
     startThread ();
 }
ripple::HTTP::ServerImpl::~ServerImpl ()
Definition at line 35 of file ServerImpl.cpp.
References beast::Thread::stopThread().
 {
     stopThread ();
 }
Member Function Documentation
void ripple::HTTP::ServerImpl::add (Peer & peer)
Definition at line 94 of file ServerImpl.cpp.
References m_state.
Referenced by ripple::HTTP::Door::Door(), and ripple::HTTP::Peer::Peer().
 {
     SharedState::Access state (m_state);
     state->peers.push_back (peer);
 }
void ripple::HTTP::ServerImpl::add (Door & door)
Definition at line 100 of file ServerImpl.cpp.
References m_state.
 {
     SharedState::Access state (m_state);
     state->doors.push_back (door);
 }
int ripple::HTTP::ServerImpl::compare (Port const & lhs, Port const & rhs) static
Definition at line 128 of file ServerImpl.cpp.
Referenced by handle_update().
 {
     if (lhs < rhs)
         return -1;
     else if (lhs > rhs)
         return 1;
     return 0;
 }
boost::asio::io_service & ripple::HTTP::ServerImpl::get_io_service ()
Definition at line 85 of file ServerImpl.cpp.
References m_io_service.
Referenced by ripple::HTTP::Peer::close(), ripple::HTTP::Peer::detach(), ripple::HTTP::Peer::Peer(), and ripple::HTTP::Peer::write().
 {
     return m_io_service;
 }
Ports const & ripple::HTTP::ServerImpl::getPorts () const
Definition at line 45 of file ServerImpl.cpp.
References m_state.
 {
     SharedState::ConstUnlockedAccess state (m_state);
     return state->ports;
 }
void ripple::HTTP::ServerImpl::handle_update ()
Definition at line 139 of file ServerImpl.cpp.
References compare(), m_doors, m_state, and stopping().
Referenced by update().
 {
     if (! stopping())
     {
         // Make a local copy to shorten the lock
         //
         Ports ports;
         {
             SharedState::ConstAccess state (m_state);
             ports = state->ports;
         }
         std::sort (ports.begin(), ports.end());
         // Walk the Door list and the Port list simultaneously and
         // build a replacement Door vector which we will then swap in.
         //
         Doors doors;
         Doors::iterator door (m_doors.begin());
         for (Ports::const_iterator port (ports.begin());
             port != ports.end(); ++port)
         {
             int comp;
             while (door != m_doors.end() &&
                     ((comp = compare (*port, (*door)->port())) > 0))
             {
                 (*door)->cancel();
                 ++door;
             }
             if (door != m_doors.end())
             {
                 if (comp < 0)
                 {
                     doors.push_back (new Door (*this, *port));
                 }
                 else
                 {
                     // old Port and new Port are the same
                     doors.push_back (*door);
                     ++door;
                 }
             }
             else
             {
                 doors.push_back (new Door (*this, *port));
             }
         }
         // Any remaining Door objects are not in the new set, so cancel them.
         //
         for (;door != m_doors.end();)
             (*door)->cancel();
         m_doors.swap (doors);
     }
     else
     {
         // Cancel pending I/O on all doors.
         //
         for (Doors::iterator iter (m_doors.begin());
             iter != m_doors.end(); ++iter)
         {
             (*iter)->cancel();
         }
         // Remove our references to the old doors.
         //
         m_doors.resize (0);
     }
 }
Handler & ripple::HTTP::ServerImpl::handler ()
Definition at line 80 of file ServerImpl.cpp.
References m_handler.
Referenced by ripple::HTTP::Peer::handle_accept(), ripple::HTTP::Peer::handle_headers(), ripple::HTTP::Peer::handle_request(), and ripple::HTTP::Peer::~Peer().
 {
     return m_handler;
 }
beast::Journal const & ripple::HTTP::ServerImpl::journal () const
Definition at line 40 of file ServerImpl.cpp.
References m_journal.
Referenced by ripple::HTTP::Door::Door(), ripple::HTTP::Door::handle_accept(), and ripple::HTTP::Peer::journal().
 {
     return m_journal;
 }
void ripple::HTTP::ServerImpl::remove (Peer & peer)
Definition at line 110 of file ServerImpl.cpp.
References m_state.
Referenced by ripple::HTTP::Door::~Door(), and ripple::HTTP::Peer::~Peer().
 {
     SharedState::Access state (m_state);
     state->peers.erase (state->peers.iterator_to (peer));
 }
void ripple::HTTP::ServerImpl::remove (Door & door)
Definition at line 116 of file ServerImpl.cpp.
References m_state.
 {
     SharedState::Access state (m_state);
     state->doors.push_back (door);
 }
void ripple::HTTP::ServerImpl::run () virtual
Must be implemented to perform the thread's actual code.
Remember that the thread must regularly check the threadShouldExit() method whilst running, and if this returns true it should return from the run() method as soon as possible to avoid being forcibly killed.
See Also
threadShouldExit, startThread
Implements beast::Thread.
Definition at line 222 of file ServerImpl.cpp.
References m_handler, m_io_service, m_server, m_stopped, ripple::HTTP::Handler::onStopped(), and beast::WaitableEvent::signal().
 {
     m_io_service.run ();
     m_stopped.signal();
     m_handler.onStopped (m_server);
 }
void ripple::HTTP::ServerImpl::setPorts (Ports const & ports)
Definition at line 51 of file ServerImpl.cpp.
References m_state, and update().
 {
     SharedState::Access state (m_state);
     state->ports = ports;
     update();
 }
void ripple::HTTP::ServerImpl::stop (bool wait)
Definition at line 63 of file ServerImpl.cpp.
References m_stopped, m_work, stopping(), update(), and beast::WaitableEvent::wait().
 {
     if (! stopping())
     {
         m_work = boost::none;
         update();
     }
     if (wait)
         m_stopped.wait();
 }
bool ripple::HTTP::ServerImpl::stopping () const
Definition at line 58 of file ServerImpl.cpp.
References m_work.
Referenced by handle_update(), and stop().
 {
     return ! m_work;
 }
void ripple::HTTP::ServerImpl::update ()
Definition at line 214 of file ServerImpl.cpp.
References handle_update(), m_io_service, and m_strand.
Referenced by setPorts(), and stop().
 {
     m_io_service.post (m_strand.wrap (boost::bind (
         &ServerImpl::handle_update, this)));
 }
Member Data Documentation
Doors ripple::HTTP::ServerImpl::m_doors
Definition at line 55 of file ServerImpl.h.
Referenced by handle_update().
Handler& ripple::HTTP::ServerImpl::m_handler
Definition at line 48 of file ServerImpl.h.
Referenced by handler(), and run().
boost::asio::io_service ripple::HTTP::ServerImpl::m_io_service
Definition at line 50 of file ServerImpl.h.
Referenced by get_io_service(), run(), and update().
beast::Journal ripple::HTTP::ServerImpl::m_journal
Definition at line 49 of file ServerImpl.h.
Referenced by journal().
Server& ripple::HTTP::ServerImpl::m_server
Definition at line 47 of file ServerImpl.h.
Referenced by run().
SharedState ripple::HTTP::ServerImpl::m_state
Definition at line 54 of file ServerImpl.h.
Referenced by add(), getPorts(), handle_update(), remove(), and setPorts().
beast::WaitableEvent ripple::HTTP::ServerImpl::m_stopped
Definition at line 53 of file ServerImpl.h.
Referenced by run(), and stop().
boost::asio::io_service::strand ripple::HTTP::ServerImpl::m_strand
Definition at line 51 of file ServerImpl.h.
Referenced by update().
boost::optional<boost::asio::io_service::work> ripple::HTTP::ServerImpl::m_work
Definition at line 52 of file ServerImpl.h.
Referenced by stop(), and stopping().
The documentation for this class was generated from the following files:
rippled/src/ripple/http/impl/ServerImpl.h
rippled/src/ripple/http/impl/ServerImpl.cpp