rippled: beast::IP Namespace Reference
beast::IP Namespace Reference
Namespaces
detail
Classes
class Address
struct AddressV4
struct AddressV6
class Endpoint
class IPEndpoint_test
Typedefs
typedef std::uint16_t Port
Functions
Endpoint from_asio (boost::asio::ip::address const &address)
Endpoint from_asio (boost::asio::ip::tcp::endpoint const &endpoint)
boost::asio::ip::address to_asio_address (Endpoint const &endpoint)
boost::asio::ip::tcp::endpoint to_asio_endpoint (Endpoint const &endpoint)
bool is_loopback (AddressV4 const &addr)
bool is_unspecified (AddressV4 const &addr)
bool is_multicast (AddressV4 const &addr)
bool is_private (AddressV4 const &addr)
bool is_public (AddressV4 const &addr)
std::string to_string (AddressV4 const &addr)
std::istream & operator>> (std::istream &is, AddressV4 &addr)
bool is_loopback (AddressV6 const &)
bool is_unspecified (AddressV6 const &)
bool is_multicast (AddressV6 const &)
bool is_private (AddressV6 const &)
bool is_public (AddressV6 const &)
std::string to_string (AddressV6 const &)
std::istream & operator>> (std::istream &is, AddressV6 &)
bool operator== (Endpoint const &lhs, Endpoint const &rhs)
bool operator< (Endpoint const &lhs, Endpoint const &rhs)
std::size_t hash_value (Endpoint const &endpoint)
std::istream & operator>> (std::istream &is, Endpoint &endpoint)
bool is_loopback (Address const &addr)
bool is_unspecified (Address const &addr)
bool is_multicast (Address const &addr)
bool is_private (Address const &addr)
bool is_public (Address const &addr)
std::size_t hash_value (Address const &addr)
std::string to_string (Address const &addr)
template<typename OutputStream >
OutputStream & operator<< (OutputStream &os, Address const &addr)
std::istream & operator>> (std::istream &is, Address &addr)
std::size_t hash_value (AddressV4 const &addr)
template<typename OutputStream >
OutputStream & operator<< (OutputStream &os, AddressV4 const &addr)
template<class Hasher >
void hash_append (Hasher &, AddressV6 const &)
std::size_t hash_value (AddressV6 const &)
template<typename OutputStream >
OutputStream & operator<< (OutputStream &os, AddressV6 const &addr)
bool is_loopback (Endpoint const &endpoint)
bool is_unspecified (Endpoint const &endpoint)
bool is_multicast (Endpoint const &endpoint)
bool is_private (Endpoint const &endpoint)
bool is_public (Endpoint const &endpoint)
std::string to_string (Endpoint const &endpoint)
template<typename OutputStream >
OutputStream & operator<< (OutputStream &os, Endpoint const &endpoint)
BEAST_DEFINE_TESTSUITE (IPEndpoint, net, beast)
Typedef Documentation
typedef std::uint16_t beast::IP::Port
Definition at line 33 of file IPEndpoint.h.
Function Documentation
beast::IP::BEAST_DEFINE_TESTSUITE (IPEndpoint , net , beast)
Endpoint beast::IP::from_asio (boost::asio::ip::address const & address)
Convert to Endpoint. The port is set to zero.
Definition at line 25 of file IPAddressConversion.cpp.
Referenced by from_asio(), and beast::IPAddressConversion::from_asio().
 {
     if (address.is_v4 ())
     {
         boost::asio::ip::address_v4::bytes_type const bytes (
             address.to_v4().to_bytes());
         return Endpoint (AddressV4 (
             bytes [0], bytes [1], bytes [2], bytes [3]));
     }
     // VFALCO TODO IPv6 support
     assert(false);
     return Endpoint();
 }
Endpoint beast::IP::from_asio (boost::asio::ip::tcp::endpoint const & endpoint)
Convert to Endpoint.
Definition at line 40 of file IPAddressConversion.cpp.
References from_asio().
 {
     return from_asio (endpoint.address()).at_port (endpoint.port());
 }
template<class Hasher > void beast::IP::hash_append (Hasher & , AddressV6 const &)
Definition at line 76 of file IPAddressV6.h.
 {
     assert(false);
 }
std::size_t beast::IP::hash_value (AddressV6 const &) inline
boost::hash support.
Definition at line 82 of file IPAddressV6.h.
     { assert(false); return 0; }
std::size_t beast::IP::hash_value (Endpoint const & endpoint)
boost::hash support.
Definition at line 140 of file IPEndpoint.cpp.
References beast::IP::Endpoint::address(), and beast::IP::Endpoint::port().
Referenced by hash_value().
 {
     std::size_t seed (hash_value (endpoint.address ()));
     // boost::hash_combine()
     seed ^= (std::hash <Port> () (endpoint.port ()))
         + 0x9e3779b9 + (seed << 6) + (seed >> 2);
     return seed;
 }
std::size_t beast::IP::hash_value (AddressV4 const & addr) inline
boost::hash support.
Definition at line 168 of file IPAddressV4.h.
References beast::IP::AddressV4::value.
     { return addr.value; }
std::size_t beast::IP::hash_value (Address const & addr) inline
boost::hash support.
Definition at line 283 of file IPAddress.h.
References hash_value(), beast::IP::Address::is_v4(), beast::IP::Address::to_v4(), and beast::IP::Address::to_v6().
 {
     return (addr.is_v4 ())
         ? hash_value (addr.to_v4())
         : hash_value (addr.to_v6());
 }
bool beast::IP::is_loopback (AddressV6 const & addr)
Returns true if this is a loopback address.
Definition at line 31 of file IPAddressV6.cpp.
 {
     // VFALCO TODO
     assert(false);
     return false;
 }
bool beast::IP::is_loopback (Endpoint const & endpoint) inline
Returns true if the endpoint is a loopback address.
Definition at line 114 of file IPEndpoint.h.
References beast::IP::Endpoint::address(), and is_loopback().
     { return is_loopback (endpoint.address ()); }
bool beast::IP::is_loopback (AddressV4 const & addr)
Returns true if this is a loopback address.
Definition at line 122 of file IPAddressV4.cpp.
References beast::IP::AddressV4::value.
Referenced by is_loopback(), is_private(), ripple::RPCHTTPServerImp::onAccept(), and beast::IP::IPEndpoint_test::testEndpoint().
 {
     return (addr.value & 0xff000000) == 0x7f000000;
 }
bool beast::IP::is_loopback (Address const & addr) inline
Returns true if this is a loopback address.
Definition at line 231 of file IPAddress.h.
References is_loopback(), beast::IP::Address::is_v4(), beast::IP::Address::to_v4(), and beast::IP::Address::to_v6().
 {
     return (addr.is_v4 ())
         ? is_loopback (addr.to_v4 ())
         : is_loopback (addr.to_v6 ());
 }
bool beast::IP::is_multicast (AddressV6 const & addr)
Returns true if the address is a multicast address.
Definition at line 45 of file IPAddressV6.cpp.
 {
     // VFALCO TODO
     assert(false);
     return false;
 }
bool beast::IP::is_multicast (Endpoint const & endpoint) inline
Returns true if the endpoint is a multicast address.
Definition at line 122 of file IPEndpoint.h.
References beast::IP::Endpoint::address(), and is_multicast().
     { return is_multicast (endpoint.address ()); }
bool beast::IP::is_multicast (AddressV4 const & addr)
Returns true if the address is a multicast address.
Definition at line 132 of file IPAddressV4.cpp.
References beast::IP::AddressV4::value.
Referenced by is_multicast(), is_public(), and beast::IP::IPEndpoint_test::testEndpoint().
 {
     return (addr.value & 0xf0000000) == 0xe0000000;
 }
bool beast::IP::is_multicast (Address const & addr) inline
Returns true if the address is a multicast address.
Definition at line 251 of file IPAddress.h.
References is_multicast(), beast::IP::Address::is_v4(), beast::IP::Address::to_v4(), and beast::IP::Address::to_v6().
 {
     return (addr.is_v4 ())
         ? is_multicast (addr.to_v4 ())
         : is_multicast (addr.to_v6 ());
 }
bool beast::IP::is_private (AddressV6 const & addr)
Returns true if the address is a private unroutable address.
Definition at line 52 of file IPAddressV6.cpp.
 {
     // VFALCO TODO
     assert(false);
     return false;
 }
bool beast::IP::is_private (Endpoint const & endpoint) inline
Returns true if the endpoint is a private unroutable address.
Definition at line 126 of file IPEndpoint.h.
References beast::IP::Endpoint::address(), and is_private().
     { return is_private (endpoint.address ()); }
bool beast::IP::is_private (AddressV4 const & addr)
Returns true if the address is a private unroutable address.
Definition at line 137 of file IPAddressV4.cpp.
References is_loopback(), and beast::IP::AddressV4::value.
Referenced by is_private(), is_public(), and beast::IP::IPEndpoint_test::testEndpoint().
 {
     return
         ((addr.value & 0xff000000) == 0x0a000000) || // Prefix /8,    10.  #.#.#
         ((addr.value & 0xfff00000) == 0xac100000) || // Prefix /12   172. 16.#.# - 172.31.#.#
         ((addr.value & 0xffff0000) == 0xc0a80000) || // Prefix /16   192.168.#.#
         is_loopback (addr);
 }
bool beast::IP::is_private (Address const & addr) inline
Returns true if the address is a private unroutable address.
Definition at line 261 of file IPAddress.h.
References is_private(), beast::IP::Address::is_v4(), beast::IP::Address::to_v4(), and beast::IP::Address::to_v6().
 {
     return (addr.is_v4 ())
         ? is_private (addr.to_v4 ())
         : is_private (addr.to_v6 ());
 }
bool beast::IP::is_public (AddressV6 const & addr)
Returns true if the address is a public routable address.
Definition at line 59 of file IPAddressV6.cpp.
 {
     // VFALCO TODO
     assert(false);
     return false;
 }
bool beast::IP::is_public (Endpoint const & endpoint) inline
Returns true if the endpoint is a public routable address.
Definition at line 130 of file IPEndpoint.h.
References beast::IP::Endpoint::address(), and is_public().
     { return is_public (endpoint.address ()); }
bool beast::IP::is_public (AddressV4 const & addr)
Returns true if the address is a public routable address.
Definition at line 146 of file IPAddressV4.cpp.
References beast::IP::AddressV4::broadcast(), is_multicast(), and is_private().
Referenced by is_public(), ripple::PeerFinder::Logic::is_valid_address(), ripple::Resource::Logic::isWhitelisted(), and beast::IP::IPEndpoint_test::testEndpoint().
 {
     return
         ! is_private (addr) &&
         ! is_multicast (addr) &&
         (addr != AddressV4::broadcast (addr));
 }
bool beast::IP::is_public (Address const & addr) inline
Returns true if the address is a public routable address.
Definition at line 271 of file IPAddress.h.
References is_public(), beast::IP::Address::is_v4(), beast::IP::Address::to_v4(), and beast::IP::Address::to_v6().
 {
     return (addr.is_v4 ())
         ? is_public (addr.to_v4 ())
         : is_public (addr.to_v6 ());
 }
bool beast::IP::is_unspecified (AddressV6 const & addr)
Returns true if the address is unspecified.
Definition at line 38 of file IPAddressV6.cpp.
 {
     // VFALCO TODO
     assert(false);
     return false;
 }
bool beast::IP::is_unspecified (Endpoint const & endpoint) inline
Returns true if the endpoint is unspecified.
Definition at line 118 of file IPEndpoint.h.
References beast::IP::Endpoint::address(), and is_unspecified().
     { return is_unspecified (endpoint.address ()); }
bool beast::IP::is_unspecified (AddressV4 const & addr)
Returns true if the address is unspecified.
Definition at line 127 of file IPAddressV4.cpp.
References beast::IP::AddressV4::value.
Referenced by ripple::RPCHandler::doConnect(), ripple::PeerFinder::SourceStringsImp::fetch(), beast::IP::Endpoint::from_string_altform(), is_unspecified(), ripple::PeerFinder::Logic::is_valid_address(), ripple::PeerFinder::StoreSqdb::load(), ripple::parseAddresses(), ripple::PeerFinder::ManagerImp::parseBootstrapIPs(), ripple::PeerFinder::ManagerImp::parseFixedIPs(), ripple::RPCHTTPServerImp::setup(), beast::IP::IPEndpoint_test::testAddressV4(), beast::IP::IPEndpoint_test::testEndpoint(), and ripple::PeerFinder::StoreSqdb::update().
 {
     return addr.value == 0;
 }
bool beast::IP::is_unspecified (Address const & addr) inline
Returns true if the address is unspecified.
Definition at line 241 of file IPAddress.h.
References is_unspecified(), beast::IP::Address::is_v4(), beast::IP::Address::to_v4(), and beast::IP::Address::to_v6().
 {
     return (addr.is_v4 ())
         ? is_unspecified (addr.to_v4 ())
         : is_unspecified (addr.to_v6 ());
 }
bool beast::IP::operator< (Endpoint const & lhs, Endpoint const & rhs)
Definition at line 129 of file IPEndpoint.cpp.
References beast::IP::Endpoint::address(), and beast::IP::Endpoint::port().
 {
     if (lhs.address() < rhs.address())
         return true;
     if (lhs.address() > rhs.address())
         return false;
     return lhs.port() < rhs.port();
 }
template<typename OutputStream > OutputStream& beast::IP::operator<< (OutputStream & os, AddressV6 const & addr)
Output stream conversion.
Definition at line 90 of file IPAddressV6.h.
References to_string().
     { return os << to_string (addr); }
template<typename OutputStream > OutputStream& beast::IP::operator<< (OutputStream & os, Endpoint const & endpoint)
Output stream conversion.
Definition at line 144 of file IPEndpoint.h.
References to_string().
 {
     os << to_string (endpoint);
     return os;
 }
template<typename OutputStream > OutputStream& beast::IP::operator<< (OutputStream & os, AddressV4 const & addr)
Output stream conversion.
Definition at line 176 of file IPAddressV4.h.
References to_string().
     { return os << to_string (addr); }
template<typename OutputStream > OutputStream& beast::IP::operator<< (OutputStream & os, Address const & addr)
Output stream conversion.
Definition at line 299 of file IPAddress.h.
References to_string().
 {
     return os << to_string (addr);
 }
bool beast::IP::operator== (Endpoint const & lhs, Endpoint const & rhs)
Arithmetic comparison.
Definition at line 123 of file IPEndpoint.cpp.
References beast::IP::Endpoint::address(), and beast::IP::Endpoint::port().
 {
     return lhs.address() == rhs.address() &&
            lhs.port() == rhs.port();
 }
std::istream & beast::IP::operator>> (std::istream & is, AddressV6 & addr)
Input stream conversion.
Definition at line 75 of file IPAddressV6.cpp.
 {
     // VFALCO TODO
     assert(false);
     return is;
 }
std::istream & beast::IP::operator>> (std::istream & is, Endpoint & endpoint)
Input stream conversion.
Definition at line 149 of file IPEndpoint.cpp.
 {
     // VFALCO TODO Support ipv6!
     Address addr;
     is >> addr;
     if (is.fail())
         return is;
     if (is.rdbuf()->in_avail()>0)
     {
         char c;
         is.get(c);
         if (c != ':')
         {
             is.unget();
             endpoint = Endpoint (addr);
             return is;
         }
         Port port;
         is >> port;
         if (is.fail())
             return is;
         endpoint = Endpoint (addr, port);
         return is;
     }
     endpoint = Endpoint (addr);
     return is;
 }
std::istream & beast::IP::operator>> (std::istream & is, AddressV4 & addr)
Input stream conversion.
Definition at line 168 of file IPAddressV4.cpp.
References beast::IP::detail::expect(), and beast::IP::detail::integer().
 {
     std::uint8_t octet [4];
     is >> IP::detail::integer (octet [0]);
     for (int i = 1; i < 4; ++i)
     {
         if (!is || !IP::detail::expect (is, '.'))
             return is;
         is >> IP::detail::integer (octet [i]);
         if (!is)
             return is;
     }
     addr = AddressV4 (octet[0], octet[1], octet[2], octet[3]);
     return is;
 }
std::istream& beast::IP::operator>> (std::istream & is, Address & addr) inline
Input stream conversion.
Definition at line 307 of file IPAddress.h.
 {
     // VFALCO TODO Support ipv6!
     AddressV4 addrv4;
     is >> addrv4;
     addr = Address (addrv4);
     return is;
 }
boost::asio::ip::address beast::IP::to_asio_address (Endpoint const & endpoint)
Convert to asio::ip::address. The port is ignored.
Definition at line 45 of file IPAddressConversion.cpp.
References beast::IP::Endpoint::address(), beast::IP::Address::is_v4(), beast::IP::Address::to_v4(), and beast::IP::AddressV4::value.
Referenced by beast::IPAddressConversion::to_asio_address(), and to_asio_endpoint().
 {
     if (endpoint.address().is_v4())
     {
         return boost::asio::ip::address (
             boost::asio::ip::address_v4 (
                 endpoint.address().to_v4().value));
     }
     // VFALCO TODO IPv6 support
     assert(false);
     return boost::asio::ip::address (
         boost::asio::ip::address_v6 ());
 }
boost::asio::ip::tcp::endpoint beast::IP::to_asio_endpoint (Endpoint const & endpoint)
Convert to asio::ip::tcp::endpoint.
Definition at line 60 of file IPAddressConversion.cpp.
References beast::IP::Endpoint::port(), and to_asio_address().
Referenced by beast::IPAddressConversion::to_asio_endpoint().
 {
     return boost::asio::ip::tcp::endpoint (
         to_asio_address (endpoint), endpoint.port());
 }
std::string beast::IP::to_string (AddressV6 const & addr)
Returns the address represented as a string.
Definition at line 68 of file IPAddressV6.cpp.
 {
     // VFALCO TODO
     assert(false);
     return "";
 }
std::string beast::IP::to_string (Endpoint const & endpoint) inline
Returns the endpoint represented as a string.
Definition at line 139 of file IPEndpoint.h.
References beast::IP::Endpoint::to_string().
     { return endpoint.to_string(); }
std::string beast::IP::to_string (AddressV4 const & addr)
Returns the address represented as a string.
Definition at line 156 of file IPAddressV4.cpp.
Referenced by rocksdb::DeleteFileTest::AddKeys(), rocksdb::ChangeCompactionStyleCommand::DoCommand(), rocksdb::DBImpl::GetProperty(), rocksdb::InternalKeyPropertiesCollector::GetReadableProperties(), ripple::HTTPReply(), operator<<(), rocksdb::ReduceDBLevelsCommand::PrepareArgs(), rocksdb::ProfileKeyComparison(), rocksdb::DBImpl::ReadFirstRecord(), beast::IP::IPEndpoint_test::shouldParseV4(), beast::IP::IPEndpoint_test::shouldPass(), rocksdb::TEST(), beast::IP::IPEndpoint_test::testAddressV4(), beast::IP::IPEndpoint_test::testEndpoint(), beast::IP::Endpoint::to_string(), beast::IP::Address::to_string(), and ripple::IdentifierType< RippleLedgerHashTraits >::to_string().
 {
     std::string s;
     s.reserve (15);
     s =
         std::to_string (addr[0]) + "." +
         std::to_string (addr[1]) + "." +
         std::to_string (addr[2]) + "." +
         std::to_string (addr[3]);
     return s;
 }
std::string beast::IP::to_string (Address const & addr) inline
Returns the address represented as a string.
Definition at line 291 of file IPAddress.h.
References beast::IP::Address::to_string().
 {
     return addr.to_string ();
 }