rippled: ripple::LedgerMaster Class Reference
ripple::LedgerMaster Class Reference abstract
#include <LedgerMaster.h>
Public Types
typedef std::function< void(Ledger::ref)> callback
typedef RippleRecursiveMutex LockType
typedef std::unique_lock
< LockType > ScopedLockType
typedef
beast::GenericScopedUnlock
< LockType > ScopedUnlockType
Public Member Functions
virtual ~LedgerMaster ()=0
virtual LedgerIndex getCurrentLedgerIndex ()=0
virtual LedgerIndex getValidLedgerIndex ()=0
virtual LockType & peekMutex ()=0
virtual Ledger::pointer getCurrentLedger ()=0
virtual Ledger::pointer getClosedLedger ()=0
virtual Ledger::pointer getValidatedLedger ()=0
virtual Ledger::ref getPublishedLedger ()=0
virtual int getPublishedLedgerAge ()=0
virtual int getValidatedLedgerAge ()=0
virtual bool isCaughtUp (std::string &reason)=0
virtual TER doTransaction (SerializedTransaction::ref txn, TransactionEngineParams params, bool &didApply)=0
virtual int getMinValidations ()=0
virtual void setMinValidations (int v)=0
virtual std::uint32_t getEarliestFetch ()=0
virtual void pushLedger (Ledger::pointer newLedger)=0
virtual void pushLedger (Ledger::pointer newLCL, Ledger::pointer newOL)=0
virtual bool storeLedger (Ledger::pointer)=0
virtual void forceValid (Ledger::pointer)=0
virtual void setFullLedger (Ledger::pointer ledger, bool isSynchronous, bool isCurrent)=0
virtual void switchLedgers (Ledger::pointer lastClosed, Ledger::pointer newCurrent)=0
virtual void failedSave (std::uint32_t seq, uint256 const &hash)=0
virtual std::string getCompleteLedgers ()=0
virtual void closeLedger (bool recoverHeldTransactions)=0
virtual uint256 getHashBySeq (std::uint32_t index)=0
virtual uint256 walkHashBySeq (std::uint32_t index)=0
virtual uint256 walkHashBySeq (std::uint32_t index, Ledger::ref referenceLedger)=0
virtual Ledger::pointer findAcquireLedger (std::uint32_t index, uint256 const &hash)=0
virtual Ledger::pointer getLedgerBySeq (std::uint32_t index)=0
virtual Ledger::pointer getLedgerByHash (uint256 const &hash)=0
virtual void setLedgerRangePresent (std::uint32_t minV, std::uint32_t maxV)=0
virtual uint256 getLedgerHash (std::uint32_t desiredSeq, Ledger::ref knownGoodLedger)=0
virtual void addHeldTransaction (Transaction::ref trans)=0
virtual void fixMismatch (Ledger::ref ledger)=0
virtual bool haveLedgerRange (std::uint32_t from, std::uint32_t to)=0
virtual bool haveLedger (std::uint32_t seq)=0
virtual void clearLedger (std::uint32_t seq)=0
virtual bool getValidatedRange (std::uint32_t &minVal, std::uint32_t &maxVal)=0
virtual bool getFullValidatedRange (std::uint32_t &minVal, std::uint32_t &maxVal)=0
virtual void tune (int size, int age)=0
virtual void sweep ()=0
virtual float getCacheHitRate ()=0
virtual void addValidateCallback (callback &c)=0
virtual void checkAccept (Ledger::ref ledger)=0
virtual void checkAccept (uint256 const &hash, std::uint32_t seq)=0
virtual void consensusBuilt (Ledger::ref ledger)=0
virtual LedgerIndex getBuildingLedger ()=0
virtual void setBuildingLedger (LedgerIndex index)=0
virtual void tryAdvance ()=0
virtual void newPathRequest ()=0
virtual bool isNewPathRequest ()=0
virtual void newOrderBookDB ()=0
virtual bool fixIndex (LedgerIndex ledgerIndex, LedgerHash const &ledgerHash)=0
virtual void doLedgerCleaner (const Json::Value &parameters)=0
virtual
beast::PropertyStream::Source & getPropertySource ()=0
Public Member Functions inherited from beast::Stoppable
Stoppable (char const *name, Stoppable &parent)
virtual ~Stoppable ()
bool isStopping () const
bool isStopped () const
bool areChildrenStopped () const
void stopped ()
virtual void onPrepare ()
virtual void onStart ()
virtual void onStop ()
virtual void onChildrenStopped ()
Static Public Member Functions
static LedgerMaster * New (Stoppable &parent, beast::Journal journal)
static bool shouldAcquire (std::uint32_t currentLedgerID, std::uint32_t ledgerHistory, std::uint32_t targetLedger)
Protected Member Functions
LedgerMaster (Stoppable &parent)
Protected Member Functions inherited from beast::Stoppable
Stoppable (char const *name, RootStoppable &root)
Additional Inherited Members
Protected Attributes inherited from beast::Stoppable
char const * m_name
RootStoppable & m_root
Child m_child
Atomic< int > m_started
bool volatile m_stopped
bool volatile m_childrenStopped
Children m_children
WaitableEvent m_stoppedEvent
Detailed Description
Definition at line 32 of file LedgerMaster.h.
Member Typedef Documentation
typedef std::function<void (Ledger::ref)> ripple::LedgerMaster::callback
Definition at line 39 of file LedgerMaster.h.
typedef RippleRecursiveMutex ripple::LedgerMaster::LockType
Definition at line 42 of file LedgerMaster.h.
typedef std::unique_lock<LockType> ripple::LedgerMaster::ScopedLockType
Definition at line 43 of file LedgerMaster.h.
typedef beast::GenericScopedUnlock<LockType> ripple::LedgerMaster::ScopedUnlockType
Definition at line 44 of file LedgerMaster.h.
Constructor & Destructor Documentation
ripple::LedgerMaster::LedgerMaster (Stoppable & parent) explicit protected
Definition at line 1444 of file LedgerMaster.cpp.
     : Stoppable ("LedgerMaster", parent)
 {
 }
ripple::LedgerMaster::~LedgerMaster () pure virtual
Definition at line 1449 of file LedgerMaster.cpp.
 {
 }
Member Function Documentation
virtual void ripple::LedgerMaster::addHeldTransaction (Transaction::ref trans) pure virtual
Implemented in ripple::LedgerMasterImp.
Referenced by ripple::NetworkOPsImp::processTransactionCb(), and ripple::NetworkOPsImp::runTransactionQueue().
virtual void ripple::LedgerMaster::addValidateCallback (callback & c) pure virtual
Implemented in ripple::LedgerMasterImp.
virtual void ripple::LedgerMaster::checkAccept (Ledger::ref ledger) pure virtual
Implemented in ripple::LedgerMasterImp.
Referenced by ripple::ValidationsImp::addValidation(), ripple::InboundLedger::init(), and ripple::LADispatch().
virtual void ripple::LedgerMaster::checkAccept (uint256 const & hash, std::uint32_t seq) pure virtual
Implemented in ripple::LedgerMasterImp.
virtual void ripple::LedgerMaster::clearLedger (std::uint32_t seq) pure virtual
Implemented in ripple::LedgerMasterImp.
virtual void ripple::LedgerMaster::closeLedger (bool recoverHeldTransactions) pure virtual
Implemented in ripple::LedgerMasterImp.
Referenced by ripple::LedgerConsensusImp::closeLedger().
virtual void ripple::LedgerMaster::consensusBuilt (Ledger::ref ledger) pure virtual
Implemented in ripple::LedgerMasterImp.
Referenced by ripple::LedgerConsensusImp::accept().
virtual void ripple::LedgerMaster::doLedgerCleaner (const Json::Value & parameters) pure virtual
Implemented in ripple::LedgerMasterImp.
Referenced by ripple::RPCHandler::doLedgerCleaner().
virtual TER ripple::LedgerMaster::doTransaction (SerializedTransaction::ref txn, TransactionEngineParams params, bool & didApply) pure virtual
Implemented in ripple::LedgerMasterImp.
Referenced by ripple::NetworkOPsImp::processTransactionCb(), and ripple::NetworkOPsImp::runTransactionQueue().
virtual void ripple::LedgerMaster::failedSave (std::uint32_t seq, uint256 const & hash) pure virtual
Implemented in ripple::LedgerMasterImp.
Referenced by ripple::Ledger::saveValidatedLedger().
virtual Ledger::pointer ripple::LedgerMaster::findAcquireLedger (std::uint32_t index, uint256 const & hash) pure virtual
Implemented in ripple::LedgerMasterImp.
Referenced by ripple::LedgerCleanerImp::doLedger(), and ripple::LedgerCleanerImp::getHash().
virtual bool ripple::LedgerMaster::fixIndex (LedgerIndex ledgerIndex, LedgerHash const & ledgerHash) pure virtual
Implemented in ripple::LedgerMasterImp.
Referenced by ripple::LedgerCleanerImp::doLedger().
virtual void ripple::LedgerMaster::fixMismatch (Ledger::ref ledger) pure virtual
Implemented in ripple::LedgerMasterImp.
virtual void ripple::LedgerMaster::forceValid (Ledger::pointer) pure virtual
Implemented in ripple::LedgerMasterImp.
virtual LedgerIndex ripple::LedgerMaster::getBuildingLedger () pure virtual
Implemented in ripple::LedgerMasterImp.
virtual float ripple::LedgerMaster::getCacheHitRate () pure virtual
Implemented in ripple::LedgerMasterImp.
Referenced by ripple::RPCHandler::doGetCounts().
virtual Ledger::pointer ripple::LedgerMaster::getClosedLedger () pure virtual
Implemented in ripple::LedgerMasterImp.
Referenced by ripple::NetworkOPsImp::acceptLedger(), ripple::NetworkOPsImp::beginConsensus(), ripple::NetworkOPsImp::checkLastClosedLedger(), ripple::RPCHandler::doLedger(), ripple::NetworkOPsImp::endConsensus(), ripple::NetworkOPsImp::getClosedLedger(), ripple::NetworkOPsImp::getClosedLedgerHash(), ripple::PeerImp::getLedger(), ripple::RPC::lookupLedger(), and ripple::PeerImp::sendHello().
virtual std::string ripple::LedgerMaster::getCompleteLedgers () pure virtual
Implemented in ripple::LedgerMasterImp.
Referenced by ripple::LedgerMasterImp::doAdvance(), ripple::NetworkOPsImp::getServerInfo(), ripple::NetworkOPsImp::pubLedger(), and ripple::NetworkOPsImp::subLedger().
virtual Ledger::pointer ripple::LedgerMaster::getCurrentLedger () pure virtual
Implemented in ripple::LedgerMasterImp.
Referenced by ripple::NetworkOPsImp::acceptLedger(), ripple::NetworkOPsImp::beginConsensus(), ripple::RPCHandler::doLedger(), ripple::NetworkOPsImp::getCurrentLedger(), ripple::NetworkOPsImp::getCurrentLedgerID(), ripple::PeerImp::getLedger(), ripple::LedgerConsensusImp::getTransactionTree(), ripple::NetworkOPsImp::haveConsensusObject(), ripple::ApplicationImp::loadOldLedger(), ripple::NetworkOPsImp::processTransactionCb(), ripple::LedgerConsensusImp::statePreClose(), and ripple::NetworkOPsImp::tryStartConsensus().
virtual LedgerIndex ripple::LedgerMaster::getCurrentLedgerIndex () pure virtual
Implemented in ripple::LedgerMasterImp.
virtual std::uint32_t ripple::LedgerMaster::getEarliestFetch () pure virtual
Implemented in ripple::LedgerMasterImp.
Referenced by ripple::PeerImp::doFetchPack(), ripple::PeerImp::getLedger(), and ripple::LedgerConsensusImp::statusChange().
virtual bool ripple::LedgerMaster::getFullValidatedRange (std::uint32_t & minVal, std::uint32_t & maxVal) pure virtual
Implemented in ripple::LedgerMasterImp.
Referenced by ripple::LedgerCleanerImp::doClean(), and ripple::NetworkOPsImp::getFullValidatedRange().
virtual uint256 ripple::LedgerMaster::getHashBySeq (std::uint32_t index) pure virtual
Get a ledger's hash by sequence number using the cache
Implemented in ripple::LedgerMasterImp.
Referenced by ripple::NetworkOPsImp::isValidated(), and ripple::NetworkOPsImp::missingNodeInLedger().
virtual Ledger::pointer ripple::LedgerMaster::getLedgerByHash (uint256 const & hash) pure virtual
Implemented in ripple::LedgerMasterImp.
Referenced by ripple::NetworkOPsImp::beginConsensus(), ripple::NetworkOPsImp::checkLastClosedLedger(), ripple::PeerImp::getLedger(), ripple::NetworkOPsImp::getLedgerByHash(), ripple::NetworkOPsImp::getLedgerID(), and ripple::LedgerConsensusImp::handleLCL().
virtual Ledger::pointer ripple::LedgerMaster::getLedgerBySeq (std::uint32_t index) pure virtual
Implemented in ripple::LedgerMasterImp.
Referenced by ripple::Transaction::getJson(), ripple::PeerImp::getLedger(), and ripple::NetworkOPsImp::getLedgerBySeq().
virtual uint256 ripple::LedgerMaster::getLedgerHash (std::uint32_t desiredSeq, Ledger::ref knownGoodLedger) pure virtual
Implemented in ripple::LedgerMasterImp.
virtual int ripple::LedgerMaster::getMinValidations () pure virtual
Implemented in ripple::LedgerMasterImp.
Referenced by ripple::NetworkOPsImp::getServerInfo(), and ripple::NetworkOPsImp::haveConsensusObject().
virtual beast::PropertyStream::Source& ripple::LedgerMaster::getPropertySource () pure virtual
Implemented in ripple::LedgerMasterImp.
virtual Ledger::ref ripple::LedgerMaster::getPublishedLedger () pure virtual
Implemented in ripple::LedgerMasterImp.
Referenced by ripple::RPCHandler::doSubscribe(), and ripple::NetworkOPsImp::getPublishedLedger().
virtual int ripple::LedgerMaster::getPublishedLedgerAge () pure virtual
Implemented in ripple::LedgerMasterImp.
virtual Ledger::pointer ripple::LedgerMaster::getValidatedLedger () pure virtual
Implemented in ripple::LedgerMasterImp.
Referenced by ripple::LedgerCleanerImp::getHash(), ripple::NetworkOPsImp::getValidatedLedger(), ripple::NetworkOPsImp::getValidatedSeq(), and ripple::NetworkOPsImp::isValidated().
virtual int ripple::LedgerMaster::getValidatedLedgerAge () pure virtual
Implemented in ripple::LedgerMasterImp.
Referenced by ripple::NetworkOPsImp::processClusterTimer(), and ripple::RPC::transactionSign().
virtual bool ripple::LedgerMaster::getValidatedRange (std::uint32_t & minVal, std::uint32_t & maxVal) pure virtual
Implemented in ripple::LedgerMasterImp.
Referenced by ripple::NetworkOPsImp::getValidatedRange().
virtual LedgerIndex ripple::LedgerMaster::getValidLedgerIndex () pure virtual
Implemented in ripple::LedgerMasterImp.
Referenced by ripple::PeerImp::checkTransaction().
virtual bool ripple::LedgerMaster::haveLedger (std::uint32_t seq) pure virtual
Implemented in ripple::LedgerMasterImp.
Referenced by ripple::NetworkOPsImp::haveLedger().
virtual bool ripple::LedgerMaster::haveLedgerRange (std::uint32_t from, std::uint32_t to) pure virtual
Implemented in ripple::LedgerMasterImp.
Referenced by ripple::NetworkOPsImp::haveLedgerRange().
virtual bool ripple::LedgerMaster::isCaughtUp (std::string & reason) pure virtual
Implemented in ripple::LedgerMasterImp.
virtual bool ripple::LedgerMaster::isNewPathRequest () pure virtual
Implemented in ripple::LedgerMasterImp.
Referenced by ripple::PathRequests::updateAll().
LedgerMaster * ripple::LedgerMaster::New (Stoppable & parent, beast::Journal journal) static
Definition at line 1468 of file LedgerMaster.cpp.
 {
     return new LedgerMasterImp (parent, journal);
 }
virtual void ripple::LedgerMaster::newOrderBookDB () pure virtual
Implemented in ripple::LedgerMasterImp.
Referenced by ripple::OrderBookDB::update().
virtual void ripple::LedgerMaster::newPathRequest () pure virtual
Implemented in ripple::LedgerMasterImp.
Referenced by ripple::PathRequests::makePathRequest().
virtual LockType& ripple::LedgerMaster::peekMutex () pure virtual
Implemented in ripple::LedgerMasterImp.
virtual void ripple::LedgerMaster::pushLedger (Ledger::pointer newLedger) pure virtual
Implemented in ripple::LedgerMasterImp.
Referenced by ripple::LedgerConsensusImp::accept().
virtual void ripple::LedgerMaster::pushLedger (Ledger::pointer newLCL, Ledger::pointer newOL) pure virtual
Implemented in ripple::LedgerMasterImp.
virtual void ripple::LedgerMaster::setBuildingLedger (LedgerIndex index) pure virtual
Implemented in ripple::LedgerMasterImp.
Referenced by ripple::LedgerConsensusImp::takeInitialPosition().
virtual void ripple::LedgerMaster::setFullLedger (Ledger::pointer ledger, bool isSynchronous, bool isCurrent) pure virtual
Implemented in ripple::LedgerMasterImp.
virtual void ripple::LedgerMaster::setLedgerRangePresent (std::uint32_t minV, std::uint32_t maxV) pure virtual
Implemented in ripple::LedgerMasterImp.
virtual void ripple::LedgerMaster::setMinValidations (int v) pure virtual
Implemented in ripple::LedgerMasterImp.
bool ripple::LedgerMaster::shouldAcquire (std::uint32_t currentLedgerID, std::uint32_t ledgerHistory, std::uint32_t targetLedger) static
Definition at line 1453 of file LedgerMaster.cpp.
References ripple::lsTRACE, and WriteLog.
Referenced by ripple::LedgerMasterImp::doAdvance().
 {
     bool ret;
     if (candidateLedger >= currentLedger)
         ret = true;
     else
         ret = (currentLedger - candidateLedger) <= ledgerHistory;
     WriteLog (lsTRACE, LedgerMaster) << "Missing ledger " << candidateLedger << (ret ? " should" : " should NOT") << " be acquired";
     return ret;
 }
virtual bool ripple::LedgerMaster::storeLedger (Ledger::pointer) pure virtual
Implemented in ripple::LedgerMasterImp.
Referenced by ripple::InboundLedger::done(), and ripple::InboundLedger::init().
virtual void ripple::LedgerMaster::sweep () pure virtual
Implemented in ripple::LedgerMasterImp.
Referenced by ripple::ApplicationImp::doSweep().
virtual void ripple::LedgerMaster::switchLedgers (Ledger::pointer lastClosed, Ledger::pointer newCurrent) pure virtual
Implemented in ripple::LedgerMasterImp.
Referenced by ripple::NetworkOPsImp::switchLastClosedLedger().
virtual void ripple::LedgerMaster::tryAdvance () pure virtual
Implemented in ripple::LedgerMasterImp.
Referenced by ripple::LADispatch().
virtual void ripple::LedgerMaster::tune (int size, int age) pure virtual
Implemented in ripple::LedgerMasterImp.
virtual uint256 ripple::LedgerMaster::walkHashBySeq (std::uint32_t index) pure virtual
Walk to a ledger's hash using the skip list
Implemented in ripple::LedgerMasterImp.
virtual uint256 ripple::LedgerMaster::walkHashBySeq (std::uint32_t index, Ledger::ref referenceLedger) pure virtual
Implemented in ripple::LedgerMasterImp.
The documentation for this class was generated from the following files:
rippled/src/ripple_app/ledger/LedgerMaster.h
rippled/src/ripple_app/ledger/LedgerMaster.cpp