rippled: ripple::IoServicePool::ServiceThread Class Reference
ripple::IoServicePool::ServiceThread Class Reference
Public Member Functions
ServiceThread (beast::String const &name, IoServicePool &owner, boost::asio::io_service &service)
~ServiceThread ()
void start ()
void run ()
Private Attributes
IoServicePool & m_owner
boost::asio::io_service & m_service
Additional Inherited Members
Private Types inherited from beast::Thread
typedef void * ThreadID
Private Member Functions inherited from beast::Thread
Thread (const String &threadName)
virtual ~Thread ()
void startThread ()
void startThread (int priority)
bool stopThread (int timeOutMilliseconds=-1)
void stopThreadAsync ()
bool isThreadRunning () const
void signalThreadShouldExit ()
bool threadShouldExit () const
bool waitForThreadToExit (int timeOutMilliseconds=-1) const
bool setPriority (int priority)
void setAffinityMask (std::uint32_t affinityMask)
bool wait (int timeOutMilliseconds=-1) const
void notify () const
ThreadID getThreadId () const noexcept
const String & getThreadName () const
Static Private Member Functions inherited from beast::Thread
static bool setCurrentThreadPriority (int priority)
static void setCurrentThreadAffinityMask (std::uint32_t affinityMask)
static void sleep (int milliseconds)
static void yield ()
static ThreadID getCurrentThreadId ()
static Thread * getCurrentThread ()
static void setCurrentThreadName (const String &newThreadName)
Detailed Description
Definition at line 24 of file IoServicePool.cpp.
Constructor & Destructor Documentation
ripple::IoServicePool::ServiceThread::ServiceThread (beast::String const & name, IoServicePool & owner, boost::asio::io_service & service) inline explicit
Definition at line 27 of file IoServicePool.cpp.
References beast::Thread::startThread().
         : Thread (name)
         , m_owner (owner)
         , m_service (service)
     {
         startThread ();
     }
ripple::IoServicePool::ServiceThread::~ServiceThread () inline
Definition at line 38 of file IoServicePool.cpp.
References beast::Thread::stopThread().
     {
         // block until thread exits
         stopThread ();
     }
Member Function Documentation
void ripple::IoServicePool::ServiceThread::run () inline virtual
Must be implemented to perform the thread's actual code.
Remember that the thread must regularly check the threadShouldExit() method whilst running, and if this returns true it should return from the run() method as soon as possible to avoid being forcibly killed.
See Also
threadShouldExit, startThread
Implements beast::Thread.
Definition at line 49 of file IoServicePool.cpp.
References m_owner, m_service, and ripple::IoServicePool::onThreadExit().
     {
         m_service.run ();
         m_owner.onThreadExit();
     }
void ripple::IoServicePool::ServiceThread::start () inline
Definition at line 44 of file IoServicePool.cpp.
References beast::Thread::startThread().
     {
         startThread ();
     }
Member Data Documentation
IoServicePool& ripple::IoServicePool::ServiceThread::m_owner private
Definition at line 57 of file IoServicePool.cpp.
Referenced by run().
boost::asio::io_service& ripple::IoServicePool::ServiceThread::m_service private
Definition at line 58 of file IoServicePool.cpp.
Referenced by run().
The documentation for this class was generated from the following file:
rippled/src/ripple_app/main/IoServicePool.cpp