rippled: ripple::SiteFiles::ManagerImp Class Reference
ripple::SiteFiles::ManagerImp Class Reference
Public Member Functions
ManagerImp (Stoppable &stoppable, beast::Journal journal)
~ManagerImp ()
void addListener (SiteFiles::Listener &listener)
void removeListener (SiteFiles::Listener &listener)
void addURL (std::string const &urlstr)
void onPrepare ()
void onStart ()
void onStop ()
void onWrite (beast::PropertyStream::Map &map)
void onDeadlineTimer (beast::DeadlineTimer &timer)
void run ()
Public Member Functions inherited from ripple::SiteFiles::Manager
virtual ~Manager ()
Public Member Functions inherited from beast::Stoppable
Stoppable (char const *name, Stoppable &parent)
virtual ~Stoppable ()
bool isStopping () const
bool isStopped () const
bool areChildrenStopped () const
void stopped ()
virtual void onChildrenStopped ()
Public Member Functions inherited from beast::PropertyStream::Source
Source (std::string const &name)
~Source ()
std::string const & name () const
void add (Source &source)
template<class Derived >
Derived * add (Derived *child)
void remove (Source &child)
void removeAll ()
void write_one (PropertyStream &stream)
void write (PropertyStream &stream)
void write (PropertyStream &stream, std::string const &path)
std::pair< Source *, bool > find (std::string path)
Source * find_one_deep (std::string const &name)
PropertyStream::Source * find_path (std::string path)
PropertyStream::Source * find_one (std::string const &name)
Public Member Functions inherited from beast::Thread
Thread (const String &threadName)
virtual ~Thread ()
void startThread ()
void startThread (int priority)
bool stopThread (int timeOutMilliseconds=-1)
void stopThreadAsync ()
bool isThreadRunning () const
void signalThreadShouldExit ()
bool threadShouldExit () const
bool waitForThreadToExit (int timeOutMilliseconds=-1) const
bool setPriority (int priority)
void setAffinityMask (std::uint32_t affinityMask)
bool wait (int timeOutMilliseconds=-1) const
void notify () const
ThreadID getThreadId () const noexcept
const String & getThreadName () const
Public Attributes
Logic m_logic
beast::Journal m_journal
beast::ServiceQueue m_queue
Additional Inherited Members
Public Types inherited from beast::Thread
typedef void * ThreadID
Static Public Member Functions inherited from ripple::SiteFiles::Manager
static Manager * New (beast::Stoppable &parent, beast::Journal journal)
Static Public Member Functions inherited from beast::Thread
static bool setCurrentThreadPriority (int priority)
static void setCurrentThreadAffinityMask (std::uint32_t affinityMask)
static void sleep (int milliseconds)
static void yield ()
static ThreadID getCurrentThreadId ()
static Thread * getCurrentThread ()
static void setCurrentThreadName (const String &newThreadName)
Protected Member Functions inherited from ripple::SiteFiles::Manager
Manager (Stoppable &parent)
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Protected Attributes inherited from beast::Stoppable
char const * m_name
RootStoppable & m_root
Child m_child
Atomic< int > m_started
bool volatile m_stopped
bool volatile m_childrenStopped
Children m_children
WaitableEvent m_stoppedEvent
Detailed Description
Definition at line 28 of file Manager.cpp.
Constructor & Destructor Documentation
ripple::SiteFiles::ManagerImp::ManagerImp (Stoppable & stoppable, beast::Journal journal) inline
Definition at line 41 of file Manager.cpp.
         : Manager (stoppable)
         , Thread ("SiteFiles")
         , m_logic (journal)
         , m_journal (journal)
     {
         // Turned off for now, this is for testing
         //addURL ("https://ripple.com/ripple.txt");
     }
ripple::SiteFiles::ManagerImp::~ManagerImp () inline
Definition at line 51 of file Manager.cpp.
References beast::Thread::stopThread().
     {
         stopThread ();
     }
Member Function Documentation
void ripple::SiteFiles::ManagerImp::addListener (SiteFiles::Listener & listener) inline virtual
Adds a listener.
Implements ripple::SiteFiles::Manager.
Definition at line 62 of file Manager.cpp.
References ripple::SiteFiles::Logic::addListener(), m_logic, m_queue, and beast::ServiceQueueType< Allocator >::post().
     {
         m_queue.post (beast::bind (
             &Logic::addListener, &m_logic, std::ref (listener)));
     }
void ripple::SiteFiles::ManagerImp::addURL (std::string const & urlstr) inline virtual
Add a URL leading to a ripple.txt file. This call does not block. The URL will be fetched asynchronously. Parsing errors are reported to the journal.
Implements ripple::SiteFiles::Manager.
Definition at line 74 of file Manager.cpp.
References ripple::SiteFiles::Logic::addURL(), m_logic, m_queue, and beast::ServiceQueueType< Allocator >::post().
     {
         m_queue.post (beast::bind (&Logic::addURL, &m_logic, urlstr));
     }
void ripple::SiteFiles::ManagerImp::onDeadlineTimer (beast::DeadlineTimer & timer) inline virtual
Reimplemented from beast::DeadlineTimer::Listener.
Definition at line 115 of file Manager.cpp.
     {
     }
void ripple::SiteFiles::ManagerImp::onPrepare () inline virtual
Override called during preparation. Since all other Stoppable objects in the tree have already been constructed, this provides an opportunity to perform initialization which depends on calling into other Stoppable objects. This call is made on the same thread that called prepare(). The default implementation does nothing. Guaranteed to only be called once.
Reimplemented from beast::Stoppable.
Definition at line 85 of file Manager.cpp.
     {
     }
void ripple::SiteFiles::ManagerImp::onStart () inline virtual
Override called during start.
Reimplemented from beast::Stoppable.
Definition at line 89 of file Manager.cpp.
References beast::Thread::startThread().
     {
         startThread();
     }
void ripple::SiteFiles::ManagerImp::onStop () inline virtual
Override called when the stop notification is issued.
The call is made on an unspecified, implementation-specific thread. onStop and onChildrenStopped will never be called concurrently, across all Stoppable objects descended from the same root, inclusive of the root.
It is safe to call isStopping, isStopped, and areChildrenStopped from within this function; The values returned will always be valid and never change during the callback.
The default implementation simply calls stopped(). This is applicable when the Stoppable has a trivial stop operation (or no stop operation), and we are merely using the Stoppable API to position it as a dependency of some parent service.
Thread safety: May not block for long periods. Guaranteed only to be called once. Must be safe to call from any thread at any time.
Reimplemented from beast::Stoppable.
Definition at line 94 of file Manager.cpp.
References beast::Journal::debug, m_journal, m_queue, and beast::ServiceQueueType< Allocator >::stop().
     {
         m_journal.debug << "Stopping";
         m_queue.stop ();
     }
void ripple::SiteFiles::ManagerImp::onWrite (beast::PropertyStream::Map &) inline virtual
Subclass override. The default version does nothing.
Reimplemented from beast::PropertyStream::Source.
Definition at line 106 of file Manager.cpp.
     {
         //SerializedContext::Scope scope (m_context);
         // ...
     }
void ripple::SiteFiles::ManagerImp::removeListener (SiteFiles::Listener & listener) inline virtual
Remove a listener.
Implements ripple::SiteFiles::Manager.
Definition at line 68 of file Manager.cpp.
References m_logic, m_queue, beast::ServiceQueueType< Allocator >::post(), and ripple::SiteFiles::Logic::removeListener().
     {
         m_queue.post (beast::bind (
             &Logic::removeListener, &m_logic, std::ref (listener)));
     }
void ripple::SiteFiles::ManagerImp::run () inline virtual
Must be implemented to perform the thread's actual code.
Remember that the thread must regularly check the threadShouldExit() method whilst running, and if this returns true it should return from the run() method as soon as possible to avoid being forcibly killed.
See Also
threadShouldExit, startThread
Implements beast::Thread.
Definition at line 119 of file Manager.cpp.
References beast::Journal::debug, m_journal, m_queue, beast::ServiceQueueType< Allocator >::poll(), beast::ServiceQueueType< Allocator >::reset(), beast::ServiceQueueType< Allocator >::run(), and beast::Stoppable::stopped().
     {
         m_journal.debug << "Started";
         m_queue.run();
         m_queue.reset();
         m_queue.poll();
         stopped();
     }
Member Data Documentation
beast::Journal ripple::SiteFiles::ManagerImp::m_journal
Definition at line 36 of file Manager.cpp.
Referenced by onStop(), and run().
Logic ripple::SiteFiles::ManagerImp::m_logic
Definition at line 35 of file Manager.cpp.
Referenced by addListener(), addURL(), and removeListener().
beast::ServiceQueue ripple::SiteFiles::ManagerImp::m_queue
Definition at line 37 of file Manager.cpp.
Referenced by addListener(), addURL(), onStop(), removeListener(), and run().
The documentation for this class was generated from the following file:
rippled/src/ripple/sitefiles/impl/Manager.cpp