rippled: ripple::TxFormats Class Reference
ripple::TxFormats Class Reference
#include <TxFormats.h>
Public Member Functions
TxFormats ()
Public Member Functions inherited from ripple::KnownFormats< TxType >
KnownFormats ()
~KnownFormats ()
TxType findTypeByName (std::string const name) const
Item const * findByType (TxTypetype) const noexcept
Static Public Member Functions
static TxFormats * getInstance ()
Private Member Functions
void addCommonFields (Item &item)
Additional Inherited Members
Protected Member Functions inherited from ripple::KnownFormats< TxType >
Item const * findByName (std::string const &name) const noexcept
Item & add (char const *name, TxTypetype)
Detailed Description
Manages the list of known transaction formats.
Definition at line 55 of file TxFormats.h.
Constructor & Destructor Documentation
ripple::TxFormats::TxFormats ()
Create the object. This will load the object will all the known transaction formats.
Definition at line 22 of file TxFormats.cpp.
References ripple::KnownFormats< TxType >::add(), ripple::SOE_DEFAULT, ripple::SOE_OPTIONAL, ripple::SOE_REQUIRED, ripple::ttACCOUNT_SET, ripple::ttCONTRACT, ripple::ttCONTRACT_REMOVE, ripple::ttFEATURE, ripple::ttFEE, ripple::ttOFFER_CANCEL, ripple::ttOFFER_CREATE, ripple::ttPAYMENT, ripple::ttREGULAR_KEY_SET, and ripple::ttTRUST_SET.
 {
     add ("AccountSet", ttACCOUNT_SET)
             << SOElement (sfEmailHash,       SOE_OPTIONAL)
             << SOElement (sfWalletLocator,   SOE_OPTIONAL)
             << SOElement (sfWalletSize,      SOE_OPTIONAL)
             << SOElement (sfMessageKey,      SOE_OPTIONAL)
             << SOElement (sfDomain,          SOE_OPTIONAL)
             << SOElement (sfTransferRate,    SOE_OPTIONAL)
             << SOElement (sfSetFlag,         SOE_OPTIONAL)
             << SOElement (sfClearFlag,       SOE_OPTIONAL)
             ;
     add ("TrustSet", ttTRUST_SET)
             << SOElement (sfLimitAmount,     SOE_OPTIONAL)
             << SOElement (sfQualityIn,       SOE_OPTIONAL)
             << SOElement (sfQualityOut,      SOE_OPTIONAL)
             ;
     add ("OfferCreate", ttOFFER_CREATE)
             << SOElement (sfTakerPays,       SOE_REQUIRED)
             << SOElement (sfTakerGets,       SOE_REQUIRED)
             << SOElement (sfExpiration,      SOE_OPTIONAL)
             << SOElement (sfOfferSequence,   SOE_OPTIONAL)
             ;
     add ("OfferCancel", ttOFFER_CANCEL)
             << SOElement (sfOfferSequence,   SOE_REQUIRED)
             ;
     add ("SetRegularKey", ttREGULAR_KEY_SET)
             << SOElement (sfRegularKey,  SOE_OPTIONAL)
             ;
     add ("Payment", ttPAYMENT)
             << SOElement (sfDestination,     SOE_REQUIRED)
             << SOElement (sfAmount,          SOE_REQUIRED)
             << SOElement (sfSendMax,         SOE_OPTIONAL)
             << SOElement (sfPaths,           SOE_DEFAULT)
             << SOElement (sfInvoiceID,       SOE_OPTIONAL)
             << SOElement (sfDestinationTag,  SOE_OPTIONAL)
             ;
     add ("Contract", ttCONTRACT)
             << SOElement (sfExpiration,      SOE_REQUIRED)
             << SOElement (sfBondAmount,      SOE_REQUIRED)
             << SOElement (sfStampEscrow,     SOE_REQUIRED)
             << SOElement (sfRippleEscrow,    SOE_REQUIRED)
             << SOElement (sfCreateCode,      SOE_OPTIONAL)
             << SOElement (sfFundCode,        SOE_OPTIONAL)
             << SOElement (sfRemoveCode,      SOE_OPTIONAL)
             << SOElement (sfExpireCode,      SOE_OPTIONAL)
             ;
     add ("RemoveContract", ttCONTRACT_REMOVE)
             << SOElement (sfTarget,          SOE_REQUIRED)
             ;
     add ("EnableFeature", ttFEATURE)
             << SOElement (sfFeature,         SOE_REQUIRED)
             ;
     add ("SetFee", ttFEE)
             << SOElement (sfBaseFee,             SOE_REQUIRED)
             << SOElement (sfReferenceFeeUnits,   SOE_REQUIRED)
             << SOElement (sfReserveBase,         SOE_REQUIRED)
             << SOElement (sfReserveIncrement,    SOE_REQUIRED)
             ;
 }
Member Function Documentation
void ripple::TxFormats::addCommonFields (Item & item) private virtual
Adds common fields.
This is called for every new item.
Implements ripple::KnownFormats< TxType >.
Definition at line 92 of file TxFormats.cpp.
References ripple::SOE_OPTIONAL, and ripple::SOE_REQUIRED.
 {
     item
         << SOElement(sfTransactionType,     SOE_REQUIRED)
         << SOElement(sfFlags,               SOE_OPTIONAL)
         << SOElement(sfSourceTag,           SOE_OPTIONAL)
         << SOElement(sfAccount,             SOE_REQUIRED)
         << SOElement(sfSequence,            SOE_REQUIRED)
         << SOElement(sfPreviousTxnID,       SOE_OPTIONAL) // Deprecated: Do not use
         << SOElement(sfLastLedgerSequence,  SOE_OPTIONAL)
         << SOElement(sfAccountTxnID,        SOE_OPTIONAL)
         << SOElement(sfFee,                 SOE_REQUIRED)
         << SOElement(sfOperationLimit,      SOE_OPTIONAL)
         << SOElement(sfMemos,               SOE_OPTIONAL)
         << SOElement(sfSigningPubKey,       SOE_REQUIRED)
         << SOElement(sfTxnSignature,        SOE_OPTIONAL)
         ;
 }
TxFormats * ripple::TxFormats::getInstance (void) static
Definition at line 111 of file TxFormats.cpp.
References instance.
Referenced by ripple::STUInt16::getJson(), ripple::STUInt16::getText(), ripple::STParsedJSON::parse(), and ripple::SerializedTransaction::SerializedTransaction().
 {
     static TxFormats instance;
     //return SharedSingleton <TxFormats>::getInstance ();
     return &instance;
 }
The documentation for this class was generated from the following files:
rippled/src/ripple_data/protocol/TxFormats.h
rippled/src/ripple_data/protocol/TxFormats.cpp