rippled: ripple::IdentifierType< Traits > Class Template Reference
ripple::IdentifierType< Traits > Class Template Reference
#include <IdentifierType.h>
Classes
class hasher
class key_equal
Public Types
typedef Traits::value_type value_type
typedef value_type::const_iterator const_iterator
typedef
value_type::const_reverse_iterator const_reverse_iterator
Public Member Functions
IdentifierType ()
IdentifierType (value_type const &value)
IdentifierType (std::uint8_t const *begin, std::uint8_t const *end)
template<typename Other >
IdentifierType (Other const &other)
IdentifierType & operator= (value_type const &value)
template<typename Other >
IdentifierType & operator= (Other const &other)
value_type const & value () const
operator value_type const & () const
std::string to_string () const
value_type const * operator-> () const
value_type const & operator* () const
const_iterator begin () const
const_iterator end () const
const_iterator cbegin () const
const_iterator cend () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
Static Public Member Functions
static std::pair
< IdentifierType, bool > from_string (std::string const &s)
Static Public Attributes
static std::size_t const size = Traits::size
Private Attributes
value_type m_value
Detailed Description
template<class Traits>
class ripple::IdentifierType< Traits >
Template for generalizing the cryptographic primitives used.
Definition at line 35 of file IdentifierType.h.
Member Typedef Documentation
template<class Traits> typedef value_type::const_iterator ripple::IdentifierType< Traits >::const_iterator
Definition at line 40 of file IdentifierType.h.
template<class Traits> typedef value_type::const_reverse_iterator ripple::IdentifierType< Traits >::const_reverse_iterator
Definition at line 41 of file IdentifierType.h.
template<class Traits> typedef Traits::value_type ripple::IdentifierType< Traits >::value_type
Definition at line 39 of file IdentifierType.h.
Constructor & Destructor Documentation
template<class Traits> ripple::IdentifierType< Traits >::IdentifierType () inline
Create an uninitialized value.
Definition at line 75 of file IdentifierType.h.
         { }
template<class Traits> ripple::IdentifierType< Traits >::IdentifierType (value_type const & value) inline
Implicit conversion construction from value_type. This allows the IdentifierType to appear as an lvalue where the rvalue is the underlying container type.
Definition at line 82 of file IdentifierType.h.
         : m_value (value)
         { }
template<class Traits> ripple::IdentifierType< Traits >::IdentifierType (std::uint8_t const * begin, std::uint8_t const * end) inline
Create a copy of the value from range of bytes.
Definition at line 87 of file IdentifierType.h.
         { Traits::construct (begin, end, m_value); }
template<class Traits> template<typename Other > ripple::IdentifierType< Traits >::IdentifierType (Other const & other) inline explicit
Conversion construction from any specialized type.
Definition at line 92 of file IdentifierType.h.
     {
         this->operator= (other);
     }
Member Function Documentation
template<class Traits> const_iterator ripple::IdentifierType< Traits >::begin () const inline
Iterator access.
Definition at line 140 of file IdentifierType.h.
 { return value().begin(); }
template<class Traits> const_iterator ripple::IdentifierType< Traits >::cbegin () const inline
Definition at line 142 of file IdentifierType.h.
 { return value().cbegin(); }
template<class Traits> const_iterator ripple::IdentifierType< Traits >::cend () const inline
Definition at line 143 of file IdentifierType.h.
 { return value().cend(); }
template<class Traits> const_reverse_iterator ripple::IdentifierType< Traits >::crbegin () const inline
Definition at line 146 of file IdentifierType.h.
 { return value().crbegin(); }
template<class Traits> const_reverse_iterator ripple::IdentifierType< Traits >::crend () const inline
Definition at line 147 of file IdentifierType.h.
 { return value().crend(); }
template<class Traits> const_iterator ripple::IdentifierType< Traits >::end () const inline
Definition at line 141 of file IdentifierType.h.
 { return value().end(); }
template<class Traits> static std::pair<IdentifierType, bool> ripple::IdentifierType< Traits >::from_string (std::string const & s) inline static
Conversion from std::string. The bool indicates the success of the conversion.
Definition at line 159 of file IdentifierType.h.
     {
         return Traits::from_string (s);
     }
template<class Traits> ripple::IdentifierType< Traits >::operator value_type const & () const inline
Implicit conversion to value_type. This lets the IdentifierType appear as an rvalue in an assignment where the lvalue is of type value_type.
Definition at line 133 of file IdentifierType.h.
     {
         return value();
     }
template<class Traits> value_type const& ripple::IdentifierType< Traits >::operator* () const inline
Definition at line 125 of file IdentifierType.h.
         { return value(); }
template<class Traits> value_type const* ripple::IdentifierType< Traits >::operator-> () const inline
Smart dereference. This provides access to the underlying container for compatibility. For example, to call member functions that are otherwise not available.
Definition at line 123 of file IdentifierType.h.
         { return &value(); }
template<class Traits> IdentifierType& ripple::IdentifierType< Traits >::operator= (value_type const & value) inline
Assign a copy from another value.
Definition at line 98 of file IdentifierType.h.
Referenced by ripple::IdentifierType< RippleLedgerHashTraits >::IdentifierType().
     {
         m_value = value;
         return *this;
     }
template<class Traits> template<typename Other > IdentifierType& ripple::IdentifierType< Traits >::operator= (Other const & other) inline
Copy conversion from any specialized type.
Definition at line 106 of file IdentifierType.h.
     {
         typename Traits::template assign <Other> () (
             m_value, other);
         return *this;
     }
template<class Traits> const_reverse_iterator ripple::IdentifierType< Traits >::rbegin () const inline
Definition at line 144 of file IdentifierType.h.
 { return value().rbegin(); }
template<class Traits> const_reverse_iterator ripple::IdentifierType< Traits >::rend () const inline
Definition at line 145 of file IdentifierType.h.
 { return value().rend(); }
template<class Traits> std::string ripple::IdentifierType< Traits >::to_string () const inline
Conversion to std::string.
Definition at line 151 of file IdentifierType.h.
Referenced by ripple::Validators::ManagerImp::onWrite(), and ripple::Validators::StoreSqdb::update().
     {
         return Traits::to_string (m_value);
     }
template<class Traits> value_type const& ripple::IdentifierType< Traits >::value () const inline
Access the value.
Definition at line 114 of file IdentifierType.h.
Referenced by ripple::IdentifierType< RippleLedgerHashTraits >::begin(), ripple::IdentifierType< RippleLedgerHashTraits >::cbegin(), ripple::IdentifierType< RippleLedgerHashTraits >::cend(), ripple::IdentifierType< RippleLedgerHashTraits >::crbegin(), ripple::IdentifierType< RippleLedgerHashTraits >::crend(), ripple::IdentifierType< RippleLedgerHashTraits >::end(), ripple::IdentifierType< RippleLedgerHashTraits >::operator value_type const &(), ripple::operator!=(), ripple::IdentifierType< Traits >::hasher::operator()(), ripple::IdentifierType< RippleLedgerHashTraits >::operator*(), ripple::IdentifierType< RippleLedgerHashTraits >::operator->(), ripple::IdentifierType< RippleLedgerHashTraits >::operator=(), ripple::operator==(), ripple::operator>(), ripple::operator>=(), ripple::IdentifierType< RippleLedgerHashTraits >::rbegin(), and ripple::IdentifierType< RippleLedgerHashTraits >::rend().
         { return m_value; }
Member Data Documentation
template<class Traits> value_type ripple::IdentifierType< Traits >::m_value private
Definition at line 166 of file IdentifierType.h.
Referenced by ripple::IdentifierType< RippleLedgerHashTraits >::IdentifierType(), ripple::IdentifierType< RippleLedgerHashTraits >::operator=(), ripple::IdentifierType< RippleLedgerHashTraits >::to_string(), and ripple::IdentifierType< RippleLedgerHashTraits >::value().
template<class Traits> std::size_t const ripple::IdentifierType< Traits >::size = Traits::size static
Definition at line 38 of file IdentifierType.h.
The documentation for this class was generated from the following file:
rippled/src/ripple/types/api/IdentifierType.h