rippled: Json::Path Class Reference
Json::Path Class Reference
Experimental and untested: represents a "path" to access a node.
#include <json_value.h>
Public Member Functions
Path (const std::string &path, const PathArgument &a1=PathArgument(), const PathArgument &a2=PathArgument(), const PathArgument &a3=PathArgument(), const PathArgument &a4=PathArgument(), const PathArgument &a5=PathArgument())
const Value & resolve (const Value &root) const
Value resolve (const Value &root, const Value &defaultValue) const
Value & make (Value &root) const
Creates the "path" to access the specified node and returns a reference on the node.
Private Types
typedef std::vector< const
PathArgument * > InArgs
typedef std::vector< PathArgument > Args
Private Member Functions
void makePath (const std::string &path, const InArgs &in)
void addPathInArg (const std::string &path, const InArgs &in, InArgs::const_iterator &itInArg, PathArgument::Kind kind)
void invalidPath (const std::string &path, int location)
Private Attributes
Args args_
Detailed Description
Experimental and untested: represents a "path" to access a node.
Syntax:
"." => root node
".[n]" => elements at index 'n' of root node (an array value)
".name" => member named 'name' of root node (an object value)
".name1.name2.name3"
".[0][1][2].name1[3]"
".%" => member name is provided as parameter
".[%]" => index is provied as parameter
Definition at line 496 of file json_value.h.
Member Typedef Documentation
typedef std::vector<PathArgument> Json::Path::Args private
Definition at line 514 of file json_value.h.
typedef std::vector<const PathArgument*> Json::Path::InArgs private
Definition at line 513 of file json_value.h.
Constructor & Destructor Documentation
Json::Path::Path (const std::string & path, const PathArgument & a1 = PathArgument (), const PathArgument & a2 = PathArgument (), const PathArgument & a3 = PathArgument (), const PathArgument & a4 = PathArgument (), const PathArgument & a5 = PathArgument ())
Definition at line 1770 of file json_value.cpp.
References Json::in(), and makePath().
 {
     InArgs in;
     in.push_back ( &a1 );
     in.push_back ( &a2 );
     in.push_back ( &a3 );
     in.push_back ( &a4 );
     in.push_back ( &a5 );
     makePath ( path, in );
 }
Member Function Documentation
void Json::Path::addPathInArg (const std::string & path, const InArgs & in, InArgs::const_iterator & itInArg, PathArgument::Kind kind) private
Definition at line 1839 of file json_value.cpp.
References args_.
Referenced by makePath().
 {
     if ( itInArg == in.end () )
     {
         // Error: missing argument %d
     }
     else if ( (*itInArg)->kind_ != kind )
     {
         // Error: bad argument type
     }
     else
     {
         args_.push_back ( **itInArg );
     }
 }
void Json::Path::invalidPath (const std::string & path, int location) private
Definition at line 1860 of file json_value.cpp.
Referenced by makePath().
 {
     // Error: invalid path.
 }
Value & Json::Path::make (Value & root) const
Creates the "path" to access the specified node and returns a reference on the node.
Definition at line 1939 of file json_value.cpp.
References arg, args_, Json::PathArgument::index_, Json::Value::isArray(), Json::Value::isObject(), Json::PathArgument::key_, Json::PathArgument::kind_, Json::PathArgument::kindIndex, and Json::PathArgument::kindKey.
 {
     Value* node = &root;
     for ( Args::const_iterator it = args_.begin (); it != args_.end (); ++it )
     {
         const PathArgument& arg = *it;
         if ( arg.kind_ == PathArgument::kindIndex )
         {
             if ( !node->isArray () )
             {
                 // Error: node is not an array at position ...
             }
             node = & ((*node)[arg.index_]);
         }
         else if ( arg.kind_ == PathArgument::kindKey )
         {
             if ( !node->isObject () )
             {
                 // Error: node is not an object at position...
             }
             node = & ((*node)[arg.key_]);
         }
     }
     return *node;
 }
void Json::Path::makePath (const std::string & path, const InArgs & in) private
Definition at line 1788 of file json_value.cpp.
References addPathInArg(), args_, invalidPath(), Json::PathArgument::kindIndex, and Json::PathArgument::kindKey.
Referenced by Path().
 {
     const char* current = path.c_str ();
     const char* end = current + path.length ();
     InArgs::const_iterator itInArg = in.begin ();
     while ( current != end )
     {
         if ( *current == '[' )
         {
             ++current;
             if ( *current == '%' )
                 addPathInArg ( path, in, itInArg, PathArgument::kindIndex );
             else
             {
                 Value::UInt index = 0;
                 for ( ; current != end && *current >= '0'  &&  *current <= '9'; ++current )
                     index = index * 10 + Value::UInt (*current - '0');
                 args_.push_back ( index );
             }
             if ( current == end  ||  *current++ != ']' )
                 invalidPath ( path, int (current - path.c_str ()) );
         }
         else if ( *current == '%' )
         {
             addPathInArg ( path, in, itInArg, PathArgument::kindKey );
             ++current;
         }
         else if ( *current == '.' )
         {
             ++current;
         }
         else
         {
             const char* beginName = current;
             while ( current != end  &&  !strchr ( "[.", *current ) )
                 ++current;
             args_.push_back ( std::string ( beginName, current ) );
         }
     }
 }
const Value & Json::Path::resolve (const Value & root) const
Definition at line 1868 of file json_value.cpp.
References arg, args_, Json::PathArgument::index_, Json::Value::isArray(), Json::Value::isObject(), Json::Value::isValidIndex(), Json::PathArgument::key_, Json::PathArgument::kind_, Json::PathArgument::kindIndex, Json::PathArgument::kindKey, and Json::Value::null.
 {
     const Value* node = &root;
     for ( Args::const_iterator it = args_.begin (); it != args_.end (); ++it )
     {
         const PathArgument& arg = *it;
         if ( arg.kind_ == PathArgument::kindIndex )
         {
             if ( !node->isArray ()  ||  node->isValidIndex ( arg.index_ ) )
             {
                 // Error: unable to resolve path (array value expected at position...
             }
             node = & ((*node)[arg.index_]);
         }
         else if ( arg.kind_ == PathArgument::kindKey )
         {
             if ( !node->isObject () )
             {
                 // Error: unable to resolve path (object value expected at position...)
             }
             node = & ((*node)[arg.key_]);
             if ( node == &Value::null )
             {
                 // Error: unable to resolve path (object has no member named '' at position...)
             }
         }
     }
     return *node;
 }
Value Json::Path::resolve (const Value & root, const Value & defaultValue) const
Definition at line 1906 of file json_value.cpp.
References arg, args_, Json::PathArgument::index_, Json::Value::isArray(), Json::Value::isObject(), Json::Value::isValidIndex(), Json::PathArgument::key_, Json::PathArgument::kind_, Json::PathArgument::kindIndex, Json::PathArgument::kindKey, and Json::Value::null.
 {
     const Value* node = &root;
     for ( Args::const_iterator it = args_.begin (); it != args_.end (); ++it )
     {
         const PathArgument& arg = *it;
         if ( arg.kind_ == PathArgument::kindIndex )
         {
             if ( !node->isArray ()  ||  node->isValidIndex ( arg.index_ ) )
                 return defaultValue;
             node = & ((*node)[arg.index_]);
         }
         else if ( arg.kind_ == PathArgument::kindKey )
         {
             if ( !node->isObject () )
                 return defaultValue;
             node = & ((*node)[arg.key_]);
             if ( node == &Value::null )
                 return defaultValue;
         }
     }
     return *node;
 }
Member Data Documentation
Args Json::Path::args_ private
Definition at line 525 of file json_value.h.
Referenced by addPathInArg(), make(), makePath(), and resolve().
The documentation for this class was generated from the following files:
rippled/src/ripple/json/api/json_value.h
rippled/src/ripple/json/impl/json_value.cpp