rippled: ripple::OfferCancelTransactor Class Reference
ripple::OfferCancelTransactor Class Reference
#include <OfferCancelTransactor.h>
Public Member Functions
OfferCancelTransactor (SerializedTransaction const &txn, TransactionEngineParams params, TransactionEngine *engine)
TER doApply () override
Public Member Functions inherited from ripple::Transactor
TER apply ()
Additional Inherited Members
Static Public Member Functions inherited from ripple::Transactor
static std::unique_ptr
< Transactor > makeTransactor (SerializedTransaction const &txn, TransactionEngineParams params, TransactionEngine *engine)
Protected Member Functions inherited from ripple::Transactor
virtual TER preCheck ()
virtual TER checkSeq ()
virtual TER payFee ()
void calculateFee ()
virtual std::uint64_t calculateBaseFee ()
virtual TER checkSig ()
Transactor (const SerializedTransaction &txn, TransactionEngineParams params, TransactionEngine *engine, beast::Journal journal=beast::Journal())
virtual bool mustHaveValidAccount ()
Protected Attributes inherited from ripple::Transactor
SerializedTransaction const & mTxn
TransactionEngine * mEngine
TransactionEngineParams mParams
uint160 mTxnAccountID
STAmount mFeeDue
STAmount mPriorBalance
STAmount mSourceBalance
SLE::pointer mTxnAccount
bool mHasAuthKey
bool mSigMaster
RippleAddress mSigningPubKey
beast::Journal m_journal
Detailed Description
Definition at line 34 of file OfferCancelTransactor.h.
Constructor & Destructor Documentation
ripple::OfferCancelTransactor::OfferCancelTransactor (SerializedTransaction const & txn, TransactionEngineParams params, TransactionEngine * engine) inline
Definition at line 38 of file OfferCancelTransactor.h.
         : Transactor (
             txn,
             params,
             engine,
             LogPartition::getJournal <OfferCancelTransactorLog> ())
     {
     }
Member Function Documentation
TER ripple::OfferCancelTransactor::doApply () override virtual
Implements ripple::Transactor.
Definition at line 23 of file OfferCancelTransactor.cpp.
References ripple::RippleAddress::createHumanAccountID(), beast::Journal::debug, ripple::TransactionEngine::entryCache(), ripple::STObject::getFieldU32(), ripple::STObject::getFlags(), ripple::Ledger::getOfferIndex(), ripple::ltOFFER, ripple::Transactor::m_journal, ripple::Transactor::mEngine, ripple::Transactor::mTxn, ripple::Transactor::mTxnAccount, ripple::Transactor::mTxnAccountID, ripple::LedgerEntrySet::offerDelete(), ripple::temBAD_SEQUENCE, ripple::temINVALID_FLAG, ripple::tesSUCCESS, ripple::tfUniversalMask, ripple::base_uint< BITS >::ToString(), beast::Journal::trace, ripple::TransactionEngine::view(), and beast::Journal::warning.
 {
     std::uint32_t const uOfferSequence = mTxn.getFieldU32 (sfOfferSequence);
     std::uint32_t const uAccountSequenceNext = mTxnAccount->getFieldU32 (sfSequence);
     m_journal.debug <<
         "uAccountSequenceNext=" << uAccountSequenceNext <<
         " uOfferSequence=" << uOfferSequence;
     std::uint32_t const uTxFlags (mTxn.getFlags ());
     if (uTxFlags & tfUniversalMask)
     {
         m_journal.trace <<
             "Malformed transaction: Invalid flags set.";
         return temINVALID_FLAG;
     }
     if (!uOfferSequence || uAccountSequenceNext - 1 <= uOfferSequence)
     {
         m_journal.trace <<
             "uAccountSequenceNext=" << uAccountSequenceNext <<
             " uOfferSequence=" << uOfferSequence;
         return temBAD_SEQUENCE;
     }
     uint256 const uOfferIndex (
         Ledger::getOfferIndex (mTxnAccountID, uOfferSequence));
     SLE::pointer sleOffer (
         mEngine->entryCache (ltOFFER, uOfferIndex));
     if (sleOffer)
     {
         m_journal.debug <<
             "OfferCancel: uOfferSequence=" << uOfferSequence;
         return mEngine->view ().offerDelete (sleOffer);
     }
     m_journal.warning <<
         "OfferCancel: offer not found: " <<
         RippleAddress::createHumanAccountID (mTxnAccountID) <<
         " : " << uOfferSequence <<
         " : " << uOfferIndex.ToString ();
     return tesSUCCESS;
 }
The documentation for this class was generated from the following files:
rippled/src/ripple_app/transactors/OfferCancelTransactor.h
rippled/src/ripple_app/transactors/OfferCancelTransactor.cpp