rippled: beast::asio::PrefilledReadStream< Stream > Class Template Reference
beast::asio::PrefilledReadStream< Stream > Class Template Reference
#include <PrefilledReadStream.h>
Public Types
typedef
std::remove_reference_t
< Stream > next_layer_type
typedef
next_layer_type::lowest_layer_type lowest_layer_type
Public Member Functions
template<class Arg >
PrefilledReadStream (Arg &arg)
template<class Arg , class ConstBufferSequence >
PrefilledReadStream (Arg &arg, ConstBufferSequence const &buffers)
template<class ConstBufferSequence >
void fill (ConstBufferSequence const &buffers)
next_layer_type & next_layer ()
next_layer_type const & next_layer () const
lowest_layer_type & lowest_layer ()
const lowest_layer_type & lowest_layer () const
boost::asio::io_service & get_io_service ()
void close ()
error_code close (error_code &ec)
template<class MutableBufferSequence >
std::size_t read_some (MutableBufferSequence const &buffers)
template<class MutableBufferSequence >
std::size_t read_some (MutableBufferSequence const &buffers, error_code &ec)
template<class ConstBufferSequence >
std::size_t write_some (ConstBufferSequence const &buffers)
template<class ConstBufferSequence >
std::size_t write_some (ConstBufferSequence const &buffers, error_code &ec)
template<class MutableBufferSequence , class ReadHandler >
void async_read_some (MutableBufferSequence const &buffers, ReadHandler &&handler)
template<class ConstBufferSequence , class WriteHandler >
void async_write_some (ConstBufferSequence const &buffers, WriteHandler &&handler)
Protected Types
typedef boost::system::error_code error_code
Static Protected Member Functions
static void throw_if (error_code const &ec)
Private Attributes
Stream m_next_layer
boost::asio::streambuf m_buffer
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
template<class Stream>
class beast::asio::PrefilledReadStream< Stream >
Front-ends a stream with a provided block of data.
When read operations are performed on this object, bytes will first be returned from the buffer provided on construction. When those bytes are exhausted, read operations will then pass through to the underlying stream.
Write operations are all simply passed through.
Definition at line 39 of file PrefilledReadStream.h.
Member Typedef Documentation
template<class Stream > typedef boost::system::error_code beast::asio::PrefilledReadStream< Stream >::error_code protected
Definition at line 42 of file PrefilledReadStream.h.
template<class Stream > typedef next_layer_type::lowest_layer_type beast::asio::PrefilledReadStream< Stream >::lowest_layer_type
Definition at line 51 of file PrefilledReadStream.h.
template<class Stream > typedef std::remove_reference_t<Stream> beast::asio::PrefilledReadStream< Stream >::next_layer_type
Definition at line 50 of file PrefilledReadStream.h.
Constructor & Destructor Documentation
template<class Stream > template<class Arg > beast::asio::PrefilledReadStream< Stream >::PrefilledReadStream (Arg & arg) inline explicit
Single argument constructor for when we are wrapped in something. arg is passed through to the next layer's constructor.
Definition at line 57 of file PrefilledReadStream.h.
         : m_next_layer (arg)
     {
     }
template<class Stream > template<class Arg , class ConstBufferSequence > beast::asio::PrefilledReadStream< Stream >::PrefilledReadStream (Arg & arg, ConstBufferSequence const & buffers) inline
Construct with the buffer, and argument passed through. This creates a copy of the data. The argument is passed through to the constructor of Stream.
Definition at line 67 of file PrefilledReadStream.h.
References beast::asio::PrefilledReadStream< Stream >::fill().
         : m_next_layer (arg)
     {
         fill (buffers);
     }
Member Function Documentation
template<class Stream > template<class MutableBufferSequence , class ReadHandler > void beast::asio::PrefilledReadStream< Stream >::async_read_some (MutableBufferSequence const & buffers, ReadHandler && handler) inline
Definition at line 171 of file PrefilledReadStream.h.
References beast::asio::bind_handler(), beast::asio::PrefilledReadStream< Stream >::get_io_service(), beast::asio::PrefilledReadStream< Stream >::m_buffer, and beast::asio::PrefilledReadStream< Stream >::m_next_layer.
     {
         if (m_buffer.size () > 0)
         {
             auto const bytes_transferred (boost::asio::buffer_copy (
                 buffers, m_buffer.data ()));
             m_buffer.consume (bytes_transferred);
             get_io_service ().post (bind_handler (
                 std::forward <ReadHandler> (handler),
                     error_code (), bytes_transferred));
             return;
         }
         m_next_layer.async_read_some (buffers,
             std::forward <ReadHandler> (handler));
     }
template<class Stream > template<class ConstBufferSequence , class WriteHandler > void beast::asio::PrefilledReadStream< Stream >::async_write_some (ConstBufferSequence const & buffers, WriteHandler && handler) inline
Definition at line 189 of file PrefilledReadStream.h.
References beast::asio::PrefilledReadStream< Stream >::m_next_layer.
     {
         m_next_layer.async_write_some (buffers,
             std::forward <WriteHandler> (handler));
     }
template<class Stream > void beast::asio::PrefilledReadStream< Stream >::close () inline
Definition at line 114 of file PrefilledReadStream.h.
References beast::asio::PrefilledReadStream< Stream >::throw_if().
     {
         error_code ec;
         close (ec);
         throw_if (ec);
     }
template<class Stream > error_code beast::asio::PrefilledReadStream< Stream >::close (error_code & ec) inline
Definition at line 121 of file PrefilledReadStream.h.
References beast::asio::PrefilledReadStream< Stream >::lowest_layer().
     {
         // VFALCO NOTE This is questionable. We can't
         // call m_next_layer.close() because Stream might not
         // support that function. For example, ssl::stream has no close()
         //
         return lowest_layer ().close(ec);
     }
template<class Stream > template<class ConstBufferSequence > void beast::asio::PrefilledReadStream< Stream >::fill (ConstBufferSequence const & buffers) inline
Place some input into the prefilled buffer. Note that this is in no way thread safe. The only reason this function is here is for the case when you can't pass the buffer through the constructor because there is another object wrapping this stream.
Definition at line 79 of file PrefilledReadStream.h.
References beast::asio::PrefilledReadStream< Stream >::m_buffer.
Referenced by beast::asio::PrefilledReadStream< Stream >::PrefilledReadStream().
     {
         // We don't assume the caller's buffers will
         // remain valid for the lifetime of this object.
         //
         m_buffer.commit (boost::asio::buffer_copy (
             m_buffer.prepare (boost::asio::buffer_size (buffers)),
                 buffers));
     }
template<class Stream > boost::asio::io_service& beast::asio::PrefilledReadStream< Stream >::get_io_service () inline
Definition at line 109 of file PrefilledReadStream.h.
References beast::asio::PrefilledReadStream< Stream >::m_next_layer.
Referenced by beast::asio::PrefilledReadStream< Stream >::async_read_some().
     {
         return m_next_layer.get_io_service();
     }
template<class Stream > lowest_layer_type& beast::asio::PrefilledReadStream< Stream >::lowest_layer () inline
Definition at line 99 of file PrefilledReadStream.h.
References beast::asio::PrefilledReadStream< Stream >::m_next_layer.
Referenced by beast::asio::PrefilledReadStream< Stream >::close().
     {
         return m_next_layer.lowest_layer();
     }
template<class Stream > const lowest_layer_type& beast::asio::PrefilledReadStream< Stream >::lowest_layer () const inline
Definition at line 104 of file PrefilledReadStream.h.
References beast::asio::PrefilledReadStream< Stream >::m_next_layer.
     {
         return m_next_layer.lowest_layer();
     }
template<class Stream > next_layer_type& beast::asio::PrefilledReadStream< Stream >::next_layer () inline
Definition at line 89 of file PrefilledReadStream.h.
References beast::asio::PrefilledReadStream< Stream >::m_next_layer.
     {
         return m_next_layer;
     }
template<class Stream > next_layer_type const& beast::asio::PrefilledReadStream< Stream >::next_layer () const inline
Definition at line 94 of file PrefilledReadStream.h.
References beast::asio::PrefilledReadStream< Stream >::m_next_layer.
     {
         return m_next_layer;
     }
template<class Stream > template<class MutableBufferSequence > std::size_t beast::asio::PrefilledReadStream< Stream >::read_some (MutableBufferSequence const & buffers) inline
Definition at line 131 of file PrefilledReadStream.h.
References beast::asio::PrefilledReadStream< Stream >::throw_if().
     {
         error_code ec;
         std::size_t const amount = read_some (buffers, ec);
         throw_if (ec);
         return amount;
     }
template<class Stream > template<class MutableBufferSequence > std::size_t beast::asio::PrefilledReadStream< Stream >::read_some (MutableBufferSequence const & buffers, error_code & ec) inline
Definition at line 140 of file PrefilledReadStream.h.
References beast::asio::PrefilledReadStream< Stream >::m_buffer, and beast::asio::PrefilledReadStream< Stream >::m_next_layer.
     {
         if (m_buffer.size () > 0)
         {
             ec = error_code ();
             std::size_t const bytes_transferred = boost::asio::buffer_copy (
                 buffers, m_buffer.data ());
             m_buffer.consume (bytes_transferred);
             return bytes_transferred;
         }
         return m_next_layer.read_some (buffers, ec);
     }
template<class Stream > static void beast::asio::PrefilledReadStream< Stream >::throw_if (error_code const & ec) inline static protected
Definition at line 44 of file PrefilledReadStream.h.
Referenced by beast::asio::PrefilledReadStream< Stream >::close(), beast::asio::PrefilledReadStream< Stream >::read_some(), and beast::asio::PrefilledReadStream< Stream >::write_some().
     {
         throw boost::system::system_error (ec);
     }
template<class Stream > template<class ConstBufferSequence > std::size_t beast::asio::PrefilledReadStream< Stream >::write_some (ConstBufferSequence const & buffers) inline
Definition at line 155 of file PrefilledReadStream.h.
References beast::asio::PrefilledReadStream< Stream >::throw_if().
     {
         error_code ec;
         auto const amount (write_some (buffers, ec));
         throw_if (ec);
         return amount;
     }
template<class Stream > template<class ConstBufferSequence > std::size_t beast::asio::PrefilledReadStream< Stream >::write_some (ConstBufferSequence const & buffers, error_code & ec) inline
Definition at line 164 of file PrefilledReadStream.h.
References beast::asio::PrefilledReadStream< Stream >::m_next_layer.
     {
         return m_next_layer.write_some (buffers, ec);
     }
Member Data Documentation
template<class Stream > boost::asio::streambuf beast::asio::PrefilledReadStream< Stream >::m_buffer private
Definition at line 198 of file PrefilledReadStream.h.
Referenced by beast::asio::PrefilledReadStream< Stream >::async_read_some(), beast::asio::PrefilledReadStream< Stream >::fill(), and beast::asio::PrefilledReadStream< Stream >::read_some().
template<class Stream > Stream beast::asio::PrefilledReadStream< Stream >::m_next_layer private
Definition at line 197 of file PrefilledReadStream.h.
Referenced by beast::asio::PrefilledReadStream< Stream >::async_read_some(), beast::asio::PrefilledReadStream< Stream >::async_write_some(), beast::asio::PrefilledReadStream< Stream >::get_io_service(), beast::asio::PrefilledReadStream< Stream >::lowest_layer(), beast::asio::PrefilledReadStream< Stream >::next_layer(), beast::asio::PrefilledReadStream< Stream >::read_some(), and beast::asio::PrefilledReadStream< Stream >::write_some().
The documentation for this class was generated from the following file:
rippled/src/beast/modules/beast_asio/protocol/PrefilledReadStream.h