rippled: ripple::LedgerHistory Class Reference
ripple::LedgerHistory Class Reference
#include <LedgerHistory.h>
Public Member Functions
LedgerHistory ()
bool addLedger (Ledger::pointer ledger, bool validated)
float getCacheHitRate ()
Ledger::pointer getLedgerBySeq (LedgerIndex ledgerIndex)
LedgerHash getLedgerHash (LedgerIndex ledgerIndex)
Ledger::pointer getLedgerByHash (LedgerHash const &ledgerHash)
void tune (int size, int age)
void sweep ()
void builtLedger (Ledger::ref)
void validatedLedger (Ledger::ref)
bool fixIndex (LedgerIndex ledgerIndex, LedgerHash const &ledgerHash)
Private Types
typedef TaggedCache
< LedgerHash, Ledger > LedgersByHash
typedef TaggedCache
< LedgerIndex, std::pair
< LedgerHash, LedgerHash > > ConsensusValidated
Private Attributes
LedgersByHash m_ledgers_by_hash
ConsensusValidated m_consensus_validated
std::map< LedgerIndex, LedgerHash > mLedgersByIndex
Detailed Description
Retains historical ledgers.
Definition at line 28 of file LedgerHistory.h.
Member Typedef Documentation
typedef TaggedCache<LedgerIndex, std::pair< LedgerHash, LedgerHash > > ripple::LedgerHistory::ConsensusValidated private
Definition at line 102 of file LedgerHistory.h.
typedef TaggedCache<LedgerHash, Ledger> ripple::LedgerHistory::LedgersByHash private
Definition at line 93 of file LedgerHistory.h.
Constructor & Destructor Documentation
ripple::LedgerHistory::LedgerHistory ()
Definition at line 34 of file LedgerHistory.cpp.
     : m_ledgers_by_hash ("LedgerCache", CACHED_LEDGER_NUM, CACHED_LEDGER_AGE,
         get_seconds_clock (), LogPartition::getJournal <TaggedCacheLog> ())
     , m_consensus_validated ("ConsensusValidated", 64, 300,
         get_seconds_clock (), LogPartition::getJournal <TaggedCacheLog> ())
 {
 }
Member Function Documentation
bool ripple::LedgerHistory::addLedger (Ledger::pointer ledger, bool validated)
Track a ledger
Returns
true if the ledger was already tracked
Definition at line 42 of file LedgerHistory.cpp.
References ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::canonicalize(), m_ledgers_by_hash, mLedgersByIndex, and ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::peekMutex().
Referenced by ripple::LedgerMasterImp::setFullLedger(), and ripple::LedgerMasterImp::storeLedger().
 {
     assert (ledger && ledger->isImmutable ());
     assert (ledger->peekAccountStateMap ()->getHash ().isNonZero ());
     LedgersByHash::ScopedLockType sl (m_ledgers_by_hash.peekMutex ());
     const bool alreadyHad = m_ledgers_by_hash.canonicalize (ledger->getHash(), ledger, true);
     if (validated)
         mLedgersByIndex[ledger->getLedgerSeq()] = ledger->getHash();
     return alreadyHad;
 }
void ripple::LedgerHistory::builtLedger (Ledger::ref ledger)
Report that we have locally built a particular ledger
Definition at line 123 of file LedgerHistory.cpp.
References ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::canonicalize(), hash, ripple::base_uint< BITS >::isZero(), ripple::lsERROR, m_consensus_validated, ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::peekMutex(), and WriteLog.
Referenced by ripple::LedgerMasterImp::pushLedger().
 {
     LedgerIndex index = ledger->getLedgerSeq();
     LedgerHash hash = ledger->getHash();
     assert (!hash.isZero());
     ConsensusValidated::ScopedLockType sl (
         m_consensus_validated.peekMutex());
     auto entry = boost::make_shared<std::pair< LedgerHash, LedgerHash >>();
     m_consensus_validated.canonicalize(index, entry, false);
     if (entry->first != hash)
     {
         if (entry->first.isNonZero() && (entry->first != hash))
         {
             WriteLog (lsERROR, LedgerMaster) << "MISMATCH: seq=" << index << " built:" << entry->first << " then:" << hash;
         }
         if (entry->second.isNonZero() && (entry->second != hash))
         {
             WriteLog (lsERROR, LedgerMaster) << "MISMATCH: seq=" << index << " validated:" << entry->second << " accepted:" << hash;
         }
         entry->first = hash;
     }
 }
bool ripple::LedgerHistory::fixIndex (LedgerIndex ledgerIndex, LedgerHash const & ledgerHash)
Repair a hash to index mapping
Parameters
ledgerIndex The index whose mapping is to be repaired
ledgerHash The hash it is to be mapped to
Returns
true if the mapping was repaired
Ensure m_ledgers_by_hash doesn't have the wrong hash for a particular index
Definition at line 175 of file LedgerHistory.cpp.
References m_ledgers_by_hash, mLedgersByIndex, and ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::peekMutex().
Referenced by ripple::LedgerMasterImp::fixIndex().
 {
     LedgersByHash::ScopedLockType sl (m_ledgers_by_hash.peekMutex ());
     std::map<std::uint32_t, uint256>::iterator it (mLedgersByIndex.find (ledgerIndex));
     if ((it != mLedgersByIndex.end ()) && (it->second != ledgerHash) )
     {
         it->second = ledgerHash;
         return false;
     }
     return true;
 }
float ripple::LedgerHistory::getCacheHitRate () inline
Get the ledgers_by_hash cache hit rate
Returns
the hit rate
Definition at line 41 of file LedgerHistory.h.
References ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::getHitRate(), and m_ledgers_by_hash.
Referenced by ripple::LedgerMasterImp::getCacheHitRate().
     {
         return m_ledgers_by_hash.getHitRate ();
     }
Ledger::pointer ripple::LedgerHistory::getLedgerByHash (LedgerHash const & ledgerHash)
Retrieve a ledger given its hash
Parameters
ledgerHash The hash of the requested ledger
Returns
The ledger requested
Definition at line 99 of file LedgerHistory.cpp.
References ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::canonicalize(), ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::fetch(), hash, ripple::Ledger::loadByHash(), and m_ledgers_by_hash.
Referenced by ripple::LedgerMasterImp::checkAccept(), ripple::LedgerMasterImp::findNewLedgersToPublish(), ripple::LedgerMasterImp::getLedgerByHash(), and getLedgerBySeq().
 {
     Ledger::pointer ret = m_ledgers_by_hash.fetch (hash);
     if (ret)
     {
         assert (ret->isImmutable ());
         assert (ret->getHash () == hash);
         return ret;
     }
     ret = Ledger::loadByHash (hash);
     if (!ret)
         return ret;
     assert (ret->isImmutable ());
     assert (ret->getHash () == hash);
     m_ledgers_by_hash.canonicalize (ret->getHash (), ret);
     assert (ret->getHash () == hash);
     return ret;
 }
Ledger::pointer ripple::LedgerHistory::getLedgerBySeq (LedgerIndex ledgerIndex)
Get a ledger given its squence number
Parameters
ledgerIndex The sequence number of the desired ledger
Definition at line 67 of file LedgerHistory.cpp.
References ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::canonicalize(), getLedgerByHash(), hash, ripple::Ledger::loadByIndex(), m_ledgers_by_hash, mLedgersByIndex, and ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::peekMutex().
Referenced by ripple::LedgerMasterImp::doAdvance(), and ripple::LedgerMasterImp::getLedgerBySeq().
 {
     {
         LedgersByHash::ScopedLockType sl (m_ledgers_by_hash.peekMutex ());
         std::map <std::uint32_t, uint256>::iterator it (mLedgersByIndex.find (index));
         if (it != mLedgersByIndex.end ())
         {
             uint256 hash = it->second;
             sl.unlock ();
             return getLedgerByHash (hash);
         }
     }
     Ledger::pointer ret (Ledger::loadByIndex (index));
     if (!ret)
         return ret;
     assert (ret->getLedgerSeq () == index);
     {
         // Add this ledger to the local tracking by index
         LedgersByHash::ScopedLockType sl (m_ledgers_by_hash.peekMutex ());
         assert (ret->isImmutable ());
         m_ledgers_by_hash.canonicalize (ret->getHash (), ret);
         mLedgersByIndex[ret->getLedgerSeq ()] = ret->getHash ();
         return (ret->getLedgerSeq () == index) ? ret : Ledger::pointer ();
     }
 }
uint256 ripple::LedgerHistory::getLedgerHash (LedgerIndex ledgerIndex)
Get a ledger's hash given its sequence number
Parameters
ledgerIndex The sequence number of the desired ledger
Returns
The hash of the specified ledger
Definition at line 56 of file LedgerHistory.cpp.
References m_ledgers_by_hash, mLedgersByIndex, and ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::peekMutex().
Referenced by ripple::LedgerMasterImp::getHashBySeq().
 {
     LedgersByHash::ScopedLockType sl (m_ledgers_by_hash.peekMutex ());
     std::map<std::uint32_t, uint256>::iterator it (mLedgersByIndex.find (index));
     if (it != mLedgersByIndex.end ())
         return it->second;
     return uint256 ();
 }
void ripple::LedgerHistory::sweep () inline
Remove stale cache entries
Definition at line 71 of file LedgerHistory.h.
References m_consensus_validated, m_ledgers_by_hash, and ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::sweep().
Referenced by ripple::LedgerMasterImp::sweep().
     {
         m_ledgers_by_hash.sweep ();
         m_consensus_validated.sweep ();
     }
void ripple::LedgerHistory::tune (int size, int age)
Set the history cache's paramters
Parameters
size The target size of the cache
age The target age of the cache, in seconds
Definition at line 188 of file LedgerHistory.cpp.
References m_ledgers_by_hash, ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::setTargetAge(), and ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::setTargetSize().
Referenced by ripple::LedgerMasterImp::tune().
 {
     m_ledgers_by_hash.setTargetSize (size);
     m_ledgers_by_hash.setTargetAge (age);
 }
void ripple::LedgerHistory::validatedLedger (Ledger::ref ledger)
Report that we have validated a particular ledger
Definition at line 148 of file LedgerHistory.cpp.
References ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::canonicalize(), hash, ripple::base_uint< BITS >::isZero(), ripple::lsERROR, m_consensus_validated, ripple::TaggedCache< Key, T, Hash, KeyEqual, Mutex >::peekMutex(), and WriteLog.
 {
     LedgerIndex index = ledger->getLedgerSeq();
     LedgerHash hash = ledger->getHash();
     assert (!hash.isZero());
     ConsensusValidated::ScopedLockType sl (
         m_consensus_validated.peekMutex());
     boost::shared_ptr< std::pair< LedgerHash, LedgerHash > > entry = boost::make_shared<std::pair< LedgerHash, LedgerHash >>();
     m_consensus_validated.canonicalize(index, entry, false);
     if (entry->second != hash)
     {
         if (entry->second.isNonZero() && (entry->second != hash))
         {
             WriteLog (lsERROR, LedgerMaster) << "MISMATCH: seq=" << index << " validated:" << entry->second << " then:" << hash;
         }
         if (entry->first.isNonZero() && (entry->first != hash))
         {
             WriteLog (lsERROR, LedgerMaster) << "MISMATCH: seq=" << index << " built:" << entry->first << " validated:" << hash;
         }
         entry->second = hash;
     }
 }
Member Data Documentation
ConsensusValidated ripple::LedgerHistory::m_consensus_validated private
Definition at line 103 of file LedgerHistory.h.
Referenced by builtLedger(), sweep(), and validatedLedger().
LedgersByHash ripple::LedgerHistory::m_ledgers_by_hash private
Definition at line 95 of file LedgerHistory.h.
Referenced by addLedger(), fixIndex(), getCacheHitRate(), getLedgerByHash(), getLedgerBySeq(), getLedgerHash(), sweep(), and tune().
std::map<LedgerIndex, LedgerHash> ripple::LedgerHistory::mLedgersByIndex private
Definition at line 107 of file LedgerHistory.h.
Referenced by addLedger(), fixIndex(), getLedgerBySeq(), and getLedgerHash().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/ledger/LedgerHistory.h
rippled/src/ripple_app/ledger/LedgerHistory.cpp