rippled: rocksdb::log::LogTest::StringSource Class Reference
rocksdb::log::LogTest::StringSource Class Reference
Public Member Functions
StringSource ()
virtual Status Read (size_t n, Slice *result, char *scratch)
virtual Status Skip (uint64_t n)
Public Member Functions inherited from rocksdb::SequentialFile
SequentialFile ()
virtual ~SequentialFile ()
virtual Status InvalidateCache (size_t offset, size_t length)
Public Attributes
Slice contents_
bool force_error_
bool returned_partial_
Detailed Description
Definition at line 59 of file log_test.cc.
Constructor & Destructor Documentation
rocksdb::log::LogTest::StringSource::StringSource () inline
Definition at line 64 of file log_test.cc.
 : force_error_(false), returned_partial_(false) { }
Member Function Documentation
virtual Status rocksdb::log::LogTest::StringSource::Read (size_t n, Slice * result, char * scratch) inline virtual
Implements rocksdb::SequentialFile.
Definition at line 66 of file log_test.cc.
References ASSERT_TRUE, contents_, rocksdb::Status::Corruption(), rocksdb::Slice::data(), force_error_, rocksdb::Status::OK(), rocksdb::Slice::remove_prefix(), returned_partial_, and rocksdb::Slice::size().
{
       ASSERT_TRUE(!returned_partial_) << "must not Read() after eof/error";
       if (force_error_) {
         force_error_ = false;
         returned_partial_ = true;
         return Status::Corruption("read error");
       }
       if (contents_.size() < n) {
         n = contents_.size();
         returned_partial_ = true;
       }
       *result = Slice(contents_.data(), n);
       contents_.remove_prefix(n);
       return Status::OK();
     }
virtual Status rocksdb::log::LogTest::StringSource::Skip (uint64_t n) inline virtual
Implements rocksdb::SequentialFile.
Definition at line 84 of file log_test.cc.
References rocksdb::Slice::clear(), contents_, rocksdb::Status::NotFound(), rocksdb::Status::OK(), rocksdb::Slice::remove_prefix(), and rocksdb::Slice::size().
{
       if (n > contents_.size()) {
         contents_.clear();
         return Status::NotFound("in-memory file skipepd past end");
       }
       contents_.remove_prefix(n);
       return Status::OK();
     }
Member Data Documentation
Slice rocksdb::log::LogTest::StringSource::contents_
Definition at line 61 of file log_test.cc.
Referenced by rocksdb::log::LogTest::CheckInitialOffsetRecord(), rocksdb::log::LogTest::CheckOffsetPastEndReturnsNoRecords(), Read(), and Skip().
bool rocksdb::log::LogTest::StringSource::force_error_
Definition at line 62 of file log_test.cc.
Referenced by rocksdb::log::LogTest::ForceError(), and Read().
bool rocksdb::log::LogTest::StringSource::returned_partial_
Definition at line 63 of file log_test.cc.
Referenced by Read().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/db/log_test.cc