rippled: beast::abstract_clock_test Class Reference
beast::abstract_clock_test Class Reference
Public Member Functions
void test (abstract_clock< std::chrono::seconds > &c)
void test_manual ()
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 34 of file abstract_clock.test.cpp.
Member Function Documentation
void beast::abstract_clock_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 72 of file abstract_clock.test.cpp.
References beast::get_abstract_clock(), beast::unit_test::suite::log, beast::unit_test::suite::pass(), test(), and test_manual().
     {
         log << "steady_clock";
         test (get_abstract_clock <std::chrono::steady_clock,
             std::chrono::seconds> ());
         log << "system_clock";
         test (get_abstract_clock <std::chrono::system_clock,
             std::chrono::seconds> ());
         log << "high_resolution_clock";
         test (get_abstract_clock <std::chrono::high_resolution_clock,
             std::chrono::seconds> ());
         log << "manual_clock";
         test_manual ();
         pass ();
     }
void beast::abstract_clock_test::test (abstract_clock< std::chrono::seconds > & c) inline
Definition at line 37 of file abstract_clock.test.cpp.
References beast::unit_test::suite::log, and beast::abstract_clock< Duration >::now().
Referenced by run().
     {
         {
             auto const t1 (c.now ());
             std::this_thread::sleep_for (
                 std::chrono::milliseconds (1500));
             auto const t2 (c.now ());
             std::stringstream ss;
             ss <<
                 "t1= " << t1.time_since_epoch() <<
                 ", t2= " << t2.time_since_epoch() <<
                 ", elapsed= " << (t2 - t1);
             log << ss.str();
         }
     }
void beast::abstract_clock_test::test_manual () inline
Definition at line 54 of file abstract_clock.test.cpp.
References beast::unit_test::suite::log, and beast::abstract_clock< Duration >::now().
Referenced by run().
     {
         typedef manual_clock <std::chrono::seconds> clock_type;
         clock_type c;
         std::stringstream ss;
         ss << "now() = " << c.now () << std::endl;
         c.set (clock_type::time_point (std::chrono::seconds (1)));
         ss << "now() = " << c.now () << std::endl;
         c.set (clock_type::time_point (std::chrono::seconds (2)));
         ss << "now() = " << c.now () << std::endl;
         log << ss.str();
     }
The documentation for this class was generated from the following file:
rippled/src/beast/beast/chrono/tests/abstract_clock.test.cpp