rippled: ripple::CBigNum Class Reference
ripple::CBigNum Class Reference
#include <CBigNum.h>
Public Member Functions
CBigNum ()
CBigNum (const CBigNum &b)
CBigNum & operator= (const CBigNum &b)
CBigNum (char n)
CBigNum (short n)
CBigNum (int n)
CBigNum (long n)
CBigNum (long long n)
CBigNum (unsigned char n)
CBigNum (unsigned short n)
CBigNum (unsigned int n)
CBigNum (unsigned long long n)
CBigNum (uint256 n)
CBigNum (Blob const &vch)
CBigNum (unsigned char const *begin, unsigned char const *end)
~CBigNum ()
void setuint (unsigned int n)
unsigned int getuint () const
int getint () const
void setint64 (std::int64_t n)
std::uint64_t getuint64 () const
void setuint64 (std::uint64_t n)
void setuint256 (uint256 const &n)
uint256 getuint256 ()
void setvch (unsigned char const *begin, unsigned char const *end)
void setvch (Blob const &vch)
Blob getvch () const
CBigNum & SetCompact (unsigned int nCompact)
unsigned int GetCompact () const
void SetHex (const std::string &str)
std::string ToString (int nBase=10) const
std::string GetHex () const
bool operator! () const
CBigNum & operator+= (const CBigNum &b)
CBigNum & operator-= (const CBigNum &b)
CBigNum & operator*= (const CBigNum &b)
CBigNum & operator/= (const CBigNum &b)
CBigNum & operator%= (const CBigNum &b)
CBigNum & operator<<= (unsigned int shift)
CBigNum & operator>>= (unsigned int shift)
CBigNum & operator++ ()
CBigNum & operator-- ()
const CBigNum operator++ (int)
const CBigNum operator-- (int)
Private Member Functions
void setulong (unsigned long n)
unsigned long getulong () const
Friends
const CBigNum operator- (const CBigNum &a, const CBigNum &b)
const CBigNum operator/ (const CBigNum &a, const CBigNum &b)
const CBigNum operator% (const CBigNum &a, const CBigNum &b)
Detailed Description
Definition at line 35 of file CBigNum.h.
Constructor & Destructor Documentation
ripple::CBigNum::CBigNum ()
Definition at line 27 of file CBigNum.cpp.
 {
     BN_init (this);
 }
ripple::CBigNum::CBigNum (const CBigNum & b)
Definition at line 32 of file CBigNum.cpp.
 {
     BN_init (this);
     if (!BN_copy (this, &b))
     {
         BN_clear_free (this);
         throw bignum_error ("CBigNum::CBigNum(const CBigNum&) : BN_copy failed");
     }
 }
ripple::CBigNum::CBigNum (char n)
Definition at line 56 of file CBigNum.cpp.
References setint64(), and setulong().
 {
     BN_init (this);
     if (n >= 0) setulong (n);
     else setint64 (n);
 }
ripple::CBigNum::CBigNum (short n)
Definition at line 63 of file CBigNum.cpp.
References setint64(), and setulong().
 {
     BN_init (this);
     if (n >= 0) setulong (n);
     else setint64 (n);
 }
ripple::CBigNum::CBigNum (int n)
Definition at line 70 of file CBigNum.cpp.
References setint64(), and setulong().
 {
     BN_init (this);
     if (n >= 0) setulong (n);
     else setint64 (n);
 }
ripple::CBigNum::CBigNum (long n)
Definition at line 77 of file CBigNum.cpp.
References setint64(), and setulong().
 {
     BN_init (this);
     if (n >= 0) setulong (n);
     else setint64 (n);
 }
ripple::CBigNum::CBigNum (long long n)
Definition at line 84 of file CBigNum.cpp.
References setint64().
 {
     BN_init (this);
     setint64 (n);
 }
ripple::CBigNum::CBigNum (unsigned char n)
Definition at line 89 of file CBigNum.cpp.
References setulong().
 {
     BN_init (this);
     setulong (n);
 }
ripple::CBigNum::CBigNum (unsigned short n)
Definition at line 94 of file CBigNum.cpp.
References setulong().
 {
     BN_init (this);
     setulong (n);
 }
ripple::CBigNum::CBigNum (unsigned int n)
Definition at line 99 of file CBigNum.cpp.
References setulong().
 {
     BN_init (this);
     setulong (n);
 }
ripple::CBigNum::CBigNum (unsigned long long n)
Definition at line 104 of file CBigNum.cpp.
References setuint64().
 {
     BN_init (this);
     setuint64 (n);
 }
ripple::CBigNum::CBigNum (uint256 n) explicit
Definition at line 109 of file CBigNum.cpp.
References setuint256().
 {
     BN_init (this);
     setuint256 (n);
 }
ripple::CBigNum::CBigNum (Blob const & vch) explicit
Definition at line 115 of file CBigNum.cpp.
References setvch().
 {
     BN_init (this);
     setvch (&vch.front(), &vch.back()+1);
 }
ripple::CBigNum::CBigNum (unsigned char const * begin, unsigned char const * end)
Definition at line 121 of file CBigNum.cpp.
References setvch().
 {
     BN_init (this);
     setvch (begin, end);
 }
ripple::CBigNum::~CBigNum ()
Definition at line 51 of file CBigNum.cpp.
 {
     BN_clear_free (this);
 }
Member Function Documentation
unsigned int ripple::CBigNum::GetCompact () const
Definition at line 297 of file CBigNum.cpp.
 {
     unsigned int nSize = BN_bn2mpi (this, nullptr);
     Blob vch (nSize);
     nSize -= 4;
     BN_bn2mpi (this, &vch[0]);
     unsigned int nCompact = nSize << 24;
     if (nSize >= 1) nCompact |= (vch[4] << 16);
     if (nSize >= 2) nCompact |= (vch[5] << 8);
     if (nSize >= 3) nCompact |= (vch[6] << 0);
     return nCompact;
 }
std::string ripple::CBigNum::GetHex () const
Definition at line 391 of file CBigNum.cpp.
References ToString().
 {
     return ToString (16);
 }
int ripple::CBigNum::getint () const
Definition at line 137 of file CBigNum.cpp.
 {
     unsigned long n = BN_get_word (this);
     if (!BN_is_negative (this))
         return (n > INT_MAX ? INT_MAX : n);
     else
         return (n > INT_MAX ? INT_MIN : - (int)n);
 }
unsigned int ripple::CBigNum::getuint () const
Definition at line 132 of file CBigNum.cpp.
Referenced by ripple::Base58::raw_encode(), and ToString().
 {
     return BN_get_word (this);
 }
uint256 ripple::CBigNum::getuint256 ()
Definition at line 234 of file CBigNum.cpp.
References ripple::base_uint< BITS >::begin(), and ripple::base_uint< BITS >::size().
 {
     uint256 ret;
     unsigned int size = BN_num_bytes (this);
     if (size > ret.size ())
         return ret;
     BN_bn2bin (this, ret.begin () + (ret.size () - BN_num_bytes (this)));
     return ret;
 }
std::uint64_t ripple::CBigNum::getuint64 () const
Definition at line 190 of file CBigNum.cpp.
References getulong().
Referenced by ripple::STAmount::divide(), ripple::STAmount::divRound(), ripple::STAmount::mulRound(), ripple::STAmount::multiply(), and ripple::STAmount_test::testArithmetic().
 {
 #if (ULONG_MAX > UINT_MAX)
     return static_cast<std::uint64_t> (getulong ());
 #else
     int len = BN_num_bytes (this);
     if (len > 8)
         throw std::runtime_error ("BN getuint64 overflow");
     unsigned char buf[8];
     memset (buf, 0, sizeof (buf));
     BN_bn2bin (this, buf + 8 - len);
     return
         static_cast<std::uint64_t> (buf[0]) << 56 | static_cast<std::uint64_t> (buf[1]) << 48 |
         static_cast<std::uint64_t> (buf[2]) << 40 | static_cast<std::uint64_t> (buf[3]) << 32 |
         static_cast<std::uint64_t> (buf[4]) << 24 | static_cast<std::uint64_t> (buf[5]) << 16 |
         static_cast<std::uint64_t> (buf[6]) << 8 | static_cast<std::uint64_t> (buf[7]);
 #endif
 }
unsigned long ripple::CBigNum::getulong () const private
Definition at line 508 of file CBigNum.cpp.
Referenced by getuint64().
 {
     return BN_get_word (this);
 }
Blob ripple::CBigNum::getvch () const
Definition at line 267 of file CBigNum.cpp.
Referenced by ripple::Base58::decode(), and ripple::Base58::raw_decode().
 {
     unsigned int nSize = BN_bn2mpi (this, nullptr);
     if (nSize < 4)
         return Blob ();
     Blob vch (nSize);
     BN_bn2mpi (this, &vch[0]);
     vch.erase (vch.begin (), vch.begin () + 4);
     reverse (vch.begin (), vch.end ());
     return vch;
 }
bool ripple::CBigNum::operator! () const
Definition at line 396 of file CBigNum.cpp.
 {
     return BN_is_zero (this);
 }
CBigNum & ripple::CBigNum::operator%= (const CBigNum & b)
Definition at line 431 of file CBigNum.cpp.
 {
     *this = *this % b;
     return *this;
 }
CBigNum & ripple::CBigNum::operator*= (const CBigNum & b)
Definition at line 415 of file CBigNum.cpp.
 {
     CAutoBN_CTX pctx;
     if (!BN_mul (this, this, &b, pctx))
         throw bignum_error ("CBigNum::operator*= : BN_mul failed");
     return *this;
 }
CBigNum & ripple::CBigNum::operator++ ()
Definition at line 465 of file CBigNum.cpp.
 {
     // prefix operator
     if (!BN_add (this, this, BN_value_one ()))
         throw bignum_error ("CBigNum::operator++ : BN_add failed");
     return *this;
 }
const CBigNum ripple::CBigNum::operator++ (int)
Definition at line 474 of file CBigNum.cpp.
 {
     // postfix operator
     const CBigNum ret = *this;
     ++ (*this);
     return ret;
 }
CBigNum & ripple::CBigNum::operator+= (const CBigNum & b)
Definition at line 401 of file CBigNum.cpp.
 {
     if (!BN_add (this, this, &b))
         throw bignum_error ("CBigNum::operator+= : BN_add failed");
     return *this;
 }
CBigNum & ripple::CBigNum::operator-- ()
Definition at line 482 of file CBigNum.cpp.
 {
     // prefix operator
     CBigNum r;
     if (!BN_sub (&r, this, BN_value_one ()))
         throw bignum_error ("CBigNum::operator-- : BN_sub failed");
     *this = r;
     return *this;
 }
const CBigNum ripple::CBigNum::operator-- (int)
Definition at line 494 of file CBigNum.cpp.
 {
     // postfix operator
     const CBigNum ret = *this;
     -- (*this);
     return ret;
 }
CBigNum & ripple::CBigNum::operator-= (const CBigNum & b)
Definition at line 409 of file CBigNum.cpp.
 {
     *this = *this - b;
     return *this;
 }
CBigNum & ripple::CBigNum::operator/= (const CBigNum & b)
Definition at line 425 of file CBigNum.cpp.
 {
     *this = *this / b;
     return *this;
 }
CBigNum & ripple::CBigNum::operator<<= (unsigned int shift)
Definition at line 437 of file CBigNum.cpp.
 {
     if (!BN_lshift (this, this, shift))
         throw bignum_error ("CBigNum:operator<<= : BN_lshift failed");
     return *this;
 }
CBigNum & ripple::CBigNum::operator= (const CBigNum & b)
Definition at line 43 of file CBigNum.cpp.
 {
     if (!BN_copy (this, &b))
         throw bignum_error ("CBigNum::operator= : BN_copy failed");
     return (*this);
 }
CBigNum & ripple::CBigNum::operator>>= (unsigned int shift)
Definition at line 445 of file CBigNum.cpp.
 {
     // Note: BN_rshift segfaults on 64-bit if 2^shift is greater than the number
     //   if built on ubuntu 9.04 or 9.10, probably depends on version of openssl
     CBigNum a = 1;
     a <<= shift;
     if (BN_cmp (&a, this) > 0)
     {
         *this = 0;
         return *this;
     }
     if (!BN_rshift (this, this, shift))
         throw bignum_error ("CBigNum:operator>>= : BN_rshift failed");
     return *this;
 }
CBigNum & ripple::CBigNum::SetCompact (unsigned int nCompact)
Definition at line 281 of file CBigNum.cpp.
 {
     unsigned int nSize = nCompact >> 24;
     Blob vch (4 + nSize);
     vch[3] = nSize;
     if (nSize >= 1) vch[4] = (nCompact >> 16) & 0xff;
     if (nSize >= 2) vch[5] = (nCompact >> 8) & 0xff;
     if (nSize >= 3) vch[6] = (nCompact >> 0) & 0xff;
     BN_mpi2bn (&vch[0], vch.size (), this);
     return *this;
 }
void ripple::CBigNum::SetHex (const std::string & str)
Definition at line 314 of file CBigNum.cpp.
 {
     // skip 0x
     const char* psz = str.c_str ();
     while (isspace (*psz))
         psz++;
     bool fNegative = false;
     if (*psz == '-')
     {
         fNegative = true;
         psz++;
     }
     if (psz[0] == '0' && tolower (psz[1]) == 'x')
         psz += 2;
     while (isspace (*psz))
         psz++;
     // hex string to bignum
     static char phexdigit[256] =
     {
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 0, 0, 0, 0, 0,
         0, 0xa, 0xb, 0xc, 0xd, 0xe, 0xf, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0xa, 0xb, 0xc, 0xd, 0xe, 0xf, 0, 0, 0, 0, 0, 0, 0, 0, 0
     };
     *this = 0;
     while (isxdigit (*psz))
     {
         *this <<= 4;
         int n = phexdigit[ (int) * psz++];
         *this += n;
     }
     if (fNegative)
         *this = 0 - *this;
 }
void ripple::CBigNum::setint64 (std::int64_t n)
Definition at line 147 of file CBigNum.cpp.
Referenced by CBigNum().
 {
     unsigned char pch[sizeof (n) + 6];
     unsigned char* p = pch + 4;
     bool fNegative = false;
     if (n < (std::int64_t)0)
     {
         n = -n;
         fNegative = true;
     }
     bool fLeadingZeroes = true;
     for (int i = 0; i < 8; i++)
     {
         unsigned char c = (n >> 56) & 0xff;
         n <<= 8;
         if (fLeadingZeroes)
         {
             if (c == 0)
                 continue;
             if (c & 0x80)
                 *p++ = (fNegative ? 0x80 : 0);
             else if (fNegative)
                 c |= 0x80;
             fLeadingZeroes = false;
         }
         *p++ = c;
     }
     unsigned int nSize = p - (pch + 4);
     pch[0] = (nSize >> 24) & 0xff;
     pch[1] = (nSize >> 16) & 0xff;
     pch[2] = (nSize >> 8) & 0xff;
     pch[3] = (nSize) & 0xff;
     BN_mpi2bn (pch, p - pch, this);
 }
void ripple::CBigNum::setuint (unsigned int n)
Definition at line 127 of file CBigNum.cpp.
References setulong().
Referenced by ripple::Base58::decode(), and ripple::Base58::raw_decode().
 {
     setulong (static_cast<unsigned long> (n));
 }
void ripple::CBigNum::setuint256 (uint256 const & n)
Definition at line 229 of file CBigNum.cpp.
References ripple::base_uint< BITS >::begin(), and ripple::base_uint< BITS >::size().
Referenced by CBigNum().
 {
     BN_bin2bn (n.begin (), n.size (), this);
 }
void ripple::CBigNum::setuint64 (std::uint64_t n)
Definition at line 211 of file CBigNum.cpp.
References setulong().
Referenced by CBigNum(), and ripple::STAmount_test::testArithmetic().
 {
 #if (ULONG_MAX > UINT_MAX)
     setulong (static_cast<unsigned long> (n));
 #else
     unsigned char buf[8];
     buf[0] = static_cast<unsigned char> ((n >> 56) & 0xff);
     buf[1] = static_cast<unsigned char> ((n >> 48) & 0xff);
     buf[2] = static_cast<unsigned char> ((n >> 40) & 0xff);
     buf[3] = static_cast<unsigned char> ((n >> 32) & 0xff);
     buf[4] = static_cast<unsigned char> ((n >> 24) & 0xff);
     buf[5] = static_cast<unsigned char> ((n >> 16) & 0xff);
     buf[6] = static_cast<unsigned char> ((n >> 8) & 0xff);
     buf[7] = static_cast<unsigned char> ((n) & 0xff);
     BN_bin2bn (buf, 8, this);
 #endif
 }
void ripple::CBigNum::setulong (unsigned long n) private
Definition at line 502 of file CBigNum.cpp.
Referenced by CBigNum(), setuint(), and setuint64().
 {
     if (!BN_set_word (this, n))
         throw bignum_error ("CBigNum conversion from unsigned long : BN_set_word failed");
 }
void ripple::CBigNum::setvch (unsigned char const * begin, unsigned char const * end)
Definition at line 246 of file CBigNum.cpp.
Referenced by CBigNum(), and setvch().
 {
     std::size_t const size (std::distance (begin, end));
     Blob vch2 (size + 4);
     unsigned int nSize (size);
     // BIGNUM's byte stream format expects 4 bytes of
     // big endian size data info at the front
     vch2[0] = (nSize >> 24) & 0xff;
     vch2[1] = (nSize >> 16) & 0xff;
     vch2[2] = (nSize >> 8) & 0xff;
     vch2[3] = (nSize >> 0) & 0xff;
     // swap data to big endian
     std::reverse_copy (begin, end, vch2.begin() + 4);
     BN_mpi2bn (&vch2[0], vch2.size (), this);
 }
void ripple::CBigNum::setvch (Blob const & vch)
Definition at line 262 of file CBigNum.cpp.
References setvch().
 {
     setvch (&vch.front(), &vch.back()+1);
 }
std::string ripple::CBigNum::ToString (int nBase = 10) const
Definition at line 360 of file CBigNum.cpp.
References getuint().
Referenced by GetHex(), and ripple::STAmount_test::testArithmetic().
 {
     CAutoBN_CTX pctx;
     CBigNum bnBase = nBase;
     CBigNum bn0 = 0;
     std::string str;
     CBigNum bn = *this;
     BN_set_negative (&bn, false);
     CBigNum dv;
     CBigNum rem;
     if (BN_cmp (&bn, &bn0) == 0)
         return "0";
     while (BN_cmp (&bn, &bn0) > 0)
     {
         if (!BN_div (&dv, &rem, &bn, &bnBase, pctx))
             throw bignum_error ("CBigNum::ToString() : BN_div failed");
         bn = dv;
         unsigned int c = rem.getuint ();
         str += "0123456789abcdef"[c];
     }
     if (BN_is_negative (this))
         str += "-";
     reverse (str.begin (), str.end ());
     return str;
 }
Friends And Related Function Documentation
const CBigNum operator% (const CBigNum & a, const CBigNum & b) friend
const CBigNum operator- (const CBigNum & a, const CBigNum & b) friend
const CBigNum operator/ (const CBigNum & a, const CBigNum & b) friend
The documentation for this class was generated from the following files:
rippled/src/ripple/sslutil/api/CBigNum.h
rippled/src/ripple/sslutil/impl/CBigNum.cpp