rippled: ripple::PeerFinder::SourceStringsImp Class Reference
ripple::PeerFinder::SourceStringsImp Class Reference
Public Member Functions
SourceStringsImp (std::string const &name, Strings const &strings)
~SourceStringsImp ()
std::string const & name ()
void fetch (Results &results, beast::Journal journal)
Private Attributes
std::string m_name
Strings m_strings
Additional Inherited Members
Public Types inherited from ripple::PeerFinder::SourceStrings
typedef std::vector< std::string > Strings
Static Public Member Functions inherited from ripple::PeerFinder::SourceStrings
static beast::SharedPtr< Source > New (std::string const &name, Strings const &strings)
Protected Member Functions inherited from beast::SharedObject
SharedObject ()
virtual ~SharedObject ()
virtual void destroy () const
void resetReferenceCount () noexcept
Detailed Description
Definition at line 23 of file SourceStrings.cpp.
Constructor & Destructor Documentation
ripple::PeerFinder::SourceStringsImp::SourceStringsImp (std::string const & name, Strings const & strings) inline
Definition at line 26 of file SourceStrings.cpp.
         : m_name (name)
         , m_strings (strings)
     {
     }
ripple::PeerFinder::SourceStringsImp::~SourceStringsImp () inline
Definition at line 32 of file SourceStrings.cpp.
     {
     }
Member Function Documentation
void ripple::PeerFinder::SourceStringsImp::fetch (Results & results, beast::Journal journal) inline virtual
Implements ripple::PeerFinder::Source.
Definition at line 41 of file SourceStrings.cpp.
References ripple::PeerFinder::Source::Results::addresses, beast::IP::Endpoint::from_string(), beast::IP::Endpoint::from_string_altform(), beast::IP::is_unspecified(), and m_strings.
     {
         results.addresses.resize (0);
         results.addresses.reserve (m_strings.size());
         for (int i = 0; i < m_strings.size (); ++i)
         {
             beast::IP::Endpoint ep (beast::IP::Endpoint::from_string (m_strings [i]));
             if (is_unspecified (ep))
                 ep = beast::IP::Endpoint::from_string_altform (m_strings [i]);
             if (! is_unspecified (ep))
                 results.addresses.push_back (ep);
         }
     }
std::string const& ripple::PeerFinder::SourceStringsImp::name () inline virtual
Implements ripple::PeerFinder::Source.
Definition at line 36 of file SourceStrings.cpp.
References m_name.
     {
         return m_name;
     }
Member Data Documentation
std::string ripple::PeerFinder::SourceStringsImp::m_name private
Definition at line 56 of file SourceStrings.cpp.
Referenced by name().
Strings ripple::PeerFinder::SourceStringsImp::m_strings private
Definition at line 57 of file SourceStrings.cpp.
Referenced by fetch().
The documentation for this class was generated from the following file:
rippled/src/ripple/peerfinder/impl/SourceStrings.cpp