rippled: beast::File_test Class Reference
beast::File_test Class Reference
Public Member Functions
template<class T1 , class T2 >
bool expectEquals (T1 const &t1, T2 const &t2)
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 908 of file File.cpp.
Member Function Documentation
template<class T1 , class T2 > bool beast::File_test::expectEquals (T1 const & t1, T2 const & t2) inline
Definition at line 913 of file File.cpp.
References beast::unit_test::suite::expect().
Referenced by run().
     {
         return expect (t1 == t2);
     }
void beast::File_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 918 of file File.cpp.
References beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::contains(), beast::File::currentApplicationFile, beast::File::currentExecutableFile, beast::File::exists(), beast::File::existsAsFile(), beast::unit_test::suite::expect(), expectEquals(), beast::File::findChildFiles(), beast::File::findDirectories, beast::File::findFiles, beast::File::findFilesAndDirectories, beast::File::findFileSystemRoots(), beast::File::getBytesFreeOnVolume(), beast::File::getChildFile(), beast::Time::getCurrentTime(), beast::File::getCurrentWorkingDirectory(), beast::MemoryBlock::getSize(), beast::File::getSpecialLocation(), beast::File::getVolumeTotalSize(), beast::File::invokedExecutableFile, beast::File::isDirectory(), beast::File::isHidden(), beast::File::isOnCDRomDrive(), beast::File::isOnHardDisk(), beast::File::nonexistent(), beast::File::separatorString, beast::File::setAsCurrentWorkingDirectory(), beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size(), beast::File::tempDirectory, beast::unit_test::suite::testcase(), beast::Time::toMilliseconds(), beast::File::userApplicationDataDirectory, beast::File::userDocumentsDirectory, beast::File::userHomeDirectory, and beast::FileOutputStream::write().
     {
         testcase ("Reading");
         const File home (File::getSpecialLocation (File::userHomeDirectory));
         const File temp (File::getSpecialLocation (File::tempDirectory));
         expect (! File::nonexistent ().exists());
         expect (home.isDirectory());
         expect (home.exists());
         expect (! home.existsAsFile());
         expect (File::getSpecialLocation (File::userDocumentsDirectory).isDirectory());
         expect (File::getSpecialLocation (File::userApplicationDataDirectory).isDirectory());
         expect (File::getSpecialLocation (File::currentExecutableFile).exists());
         expect (File::getSpecialLocation (File::currentApplicationFile).exists());
         expect (File::getSpecialLocation (File::invokedExecutableFile).exists());
         expect (home.getVolumeTotalSize() > 1024 * 1024);
         expect (home.getBytesFreeOnVolume() > 0);
         expect (! home.isHidden());
         expect (home.isOnHardDisk());
         expect (! home.isOnCDRomDrive());
         expect (File::getCurrentWorkingDirectory().exists());
         expect (home.setAsCurrentWorkingDirectory());
        #if BEAST_WINDOWS
         expect (File::getCurrentWorkingDirectory() == home);
        #endif
         {
             Array<File> roots;
             File::findFileSystemRoots (roots);
             expect (roots.size() > 0);
             int numRootsExisting = 0;
             for (int i = 0; i < roots.size(); ++i)
                 if (roots[i].exists())
                     ++numRootsExisting;
             // (on windows, some of the drives may not contain media, so as long as at least one is ok..)
             expect (numRootsExisting > 0);
         }
         testcase ("Writing");
         File demoFolder (temp.getChildFile ("Beast UnitTests Temp Folder.folder"));
         expect (demoFolder.deleteRecursively());
         expect (demoFolder.createDirectory());
         expect (demoFolder.isDirectory());
         expect (demoFolder.getParentDirectory() == temp);
         expect (temp.isDirectory());
         {
             Array<File> files;
             temp.findChildFiles (files, File::findFilesAndDirectories, false, "*");
             expect (files.contains (demoFolder));
         }
         {
             Array<File> files;
             temp.findChildFiles (files, File::findDirectories, true, "*.folder");
             expect (files.contains (demoFolder));
         }
         File tempFile (demoFolder.getNonexistentChildFile ("test", ".txt", false));
         expect (tempFile.getFileExtension() == ".txt");
         expect (tempFile.hasFileExtension (".txt"));
         expect (tempFile.hasFileExtension ("txt"));
         expect (tempFile.withFileExtension ("xyz").hasFileExtension (".xyz"));
         expect (tempFile.withFileExtension ("xyz").hasFileExtension ("abc;xyz;foo"));
         expect (tempFile.withFileExtension ("xyz").hasFileExtension ("xyz;foo"));
         expect (! tempFile.withFileExtension ("h").hasFileExtension ("bar;foo;xx"));
         expect (tempFile.getSiblingFile ("foo").isAChildOf (temp));
         expect (tempFile.hasWriteAccess());
         {
             FileOutputStream fo (tempFile);
             fo.write ("0123456789", 10);
         }
         expect (tempFile.exists());
         expect (tempFile.getSize() == 10);
         expect (std::abs ((int) (tempFile.getLastModificationTime().toMilliseconds() - Time::getCurrentTime().toMilliseconds())) < 3000);
         expect (tempFile.loadFileAsString() == String ("0123456789"));
         expect (! demoFolder.containsSubDirectories());
         expectEquals (tempFile.getRelativePathFrom (demoFolder.getParentDirectory()), demoFolder.getFileName() + File::separatorString + tempFile.getFileName());
         expectEquals (demoFolder.getParentDirectory().getRelativePathFrom (tempFile), ".." + File::separatorString + ".." + File::separatorString + demoFolder.getParentDirectory().getFileName());
         expect (demoFolder.getNumberOfChildFiles (File::findFiles) == 1);
         expect (demoFolder.getNumberOfChildFiles (File::findFilesAndDirectories) == 1);
         expect (demoFolder.getNumberOfChildFiles (File::findDirectories) == 0);
         demoFolder.getNonexistentChildFile ("tempFolder", "", false).createDirectory();
         expect (demoFolder.getNumberOfChildFiles (File::findDirectories) == 1);
         expect (demoFolder.getNumberOfChildFiles (File::findFilesAndDirectories) == 2);
         expect (demoFolder.containsSubDirectories());
         expect (tempFile.hasWriteAccess());
         tempFile.setReadOnly (true);
         expect (! tempFile.hasWriteAccess());
         tempFile.setReadOnly (false);
         expect (tempFile.hasWriteAccess());
         Time t (Time::getCurrentTime());
         tempFile.setLastModificationTime (t);
         Time t2 = tempFile.getLastModificationTime();
         expect (std::abs ((int) (t2.toMilliseconds() - t.toMilliseconds())) <= 1000);
         {
             MemoryBlock mb;
             tempFile.loadFileAsData (mb);
             expect (mb.getSize() == 10);
             expect (mb[0] == '0');
         }
         {
             expect (tempFile.getSize() == 10);
             FileOutputStream fo (tempFile);
             expect (fo.openedOk());
             expect (fo.setPosition  (7));
             expect (fo.truncate().wasOk());
             expect (tempFile.getSize() == 7);
             fo.write ("789", 3);
             fo.flush();
             expect (tempFile.getSize() == 10);
         }
         testcase ("More writing");
         expect (tempFile.appendData ("abcdefghij", 10));
         expect (tempFile.getSize() == 20);
         expect (tempFile.replaceWithData ("abcdefghij", 10));
         expect (tempFile.getSize() == 10);
         File tempFile2 (tempFile.getNonexistentSibling (false));
         expect (tempFile.copyFileTo (tempFile2));
         expect (tempFile2.exists());
         expect (tempFile2.hasIdenticalContentTo (tempFile));
         expect (tempFile.deleteFile());
         expect (! tempFile.exists());
         expect (tempFile2.moveFileTo (tempFile));
         expect (tempFile.exists());
         expect (! tempFile2.exists());
         expect (demoFolder.deleteRecursively());
         expect (! demoFolder.exists());
     }
The documentation for this class was generated from the following file:
rippled/src/beast/modules/beast_core/files/File.cpp