rippled: rocksdb::BlockConstructor Class Reference
rocksdb::BlockConstructor Class Reference
Public Member Functions
BlockConstructor (const Comparator *cmp)
~BlockConstructor ()
virtual Status FinishImpl (const Options &options, const KVMap &data)
virtual Iterator * NewIterator () const
Public Member Functions inherited from rocksdb::Constructor
Constructor (const Comparator *cmp)
virtual ~Constructor ()
void Add (const std::string &key, const Slice &value)
void Finish (const Options &options, std::vector< std::string > *keys, KVMap *kvmap)
virtual const KVMap & data ()
virtual DB * db () const
Private Member Functions
BlockConstructor ()
Private Attributes
const Comparator * comparator_
std::string data_
Block * block_
Detailed Description
Definition at line 203 of file table_test.cc.
Constructor & Destructor Documentation
rocksdb::BlockConstructor::BlockConstructor (const Comparator * cmp) inline explicit
Definition at line 205 of file table_test.cc.
       : Constructor(cmp),
         comparator_(cmp),
         block_(nullptr) { }
rocksdb::BlockConstructor::~BlockConstructor () inline
Definition at line 209 of file table_test.cc.
References block_.
                       {
     delete block_;
   }
rocksdb::BlockConstructor::BlockConstructor () private
Member Function Documentation
virtual Status rocksdb::BlockConstructor::FinishImpl (const Options & options, const KVMap & data) inline virtual
Implements rocksdb::Constructor.
Definition at line 212 of file table_test.cc.
References rocksdb::BlockBuilder::Add(), block_, rocksdb::BlockContents::cachable, rocksdb::BlockContents::data, data_, rocksdb::BlockBuilder::Finish(), rocksdb::BlockContents::heap_allocated, rocksdb::Status::OK(), and rocksdb::Slice::ToString().
{
     delete block_;
     block_ = nullptr;
     BlockBuilder builder(options);
     for (KVMap::const_iterator it = data.begin();
          it != data.end();
          ++it) {
       builder.Add(it->first, it->second);
     }
     // Open the block
     data_ = builder.Finish().ToString();
     BlockContents contents;
     contents.data = data_;
     contents.cachable = false;
     contents.heap_allocated = false;
     block_ = new Block(contents);
     return Status::OK();
   }
virtual Iterator* rocksdb::BlockConstructor::NewIterator () const inline virtual
Implements rocksdb::Constructor.
Definition at line 231 of file table_test.cc.
References block_, comparator_, and rocksdb::Block::NewIterator().
{
     return block_->NewIterator(comparator_);
   }
Member Data Documentation
Block* rocksdb::BlockConstructor::block_ private
Definition at line 238 of file table_test.cc.
Referenced by FinishImpl(), NewIterator(), and ~BlockConstructor().
const Comparator* rocksdb::BlockConstructor::comparator_ private
Definition at line 236 of file table_test.cc.
Referenced by NewIterator().
std::string rocksdb::BlockConstructor::data_ private
Definition at line 237 of file table_test.cc.
Referenced by FinishImpl().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/table/table_test.cc