rippled: rocksdb::TransactionLogIterator Class Reference
rocksdb::TransactionLogIterator Class Reference abstract
#include <transaction_log.h>
Public Member Functions
TransactionLogIterator ()
virtual ~TransactionLogIterator ()
virtual bool Valid ()=0
virtual void Next ()=0
virtual Status status ()=0
virtual BatchResult GetBatch ()=0
Detailed Description
Definition at line 66 of file transaction_log.h.
Constructor & Destructor Documentation
rocksdb::TransactionLogIterator::TransactionLogIterator () inline
Definition at line 68 of file transaction_log.h.
 {}
virtual rocksdb::TransactionLogIterator::~TransactionLogIterator () inline virtual
Definition at line 69 of file transaction_log.h.
 {}
Member Function Documentation
virtual BatchResult rocksdb::TransactionLogIterator::GetBatch () pure virtual
Implemented in rocksdb::TransactionLogIteratorImpl.
Referenced by rocksdb::ReadRecords(), and ReplicationThreadBody().
virtual void rocksdb::TransactionLogIterator::Next () pure virtual
Implemented in rocksdb::TransactionLogIteratorImpl.
Referenced by rocksdb::ReadRecords(), and ReplicationThreadBody().
virtual Status rocksdb::TransactionLogIterator::status () pure virtual
Implemented in rocksdb::TransactionLogIteratorImpl.
Referenced by rocksdb::ReadRecords().
virtual bool rocksdb::TransactionLogIterator::Valid () pure virtual
Implemented in rocksdb::TransactionLogIteratorImpl.
Referenced by rocksdb::ReadRecords(), ReplicationThreadBody(), and rocksdb::TEST().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/include/rocksdb/transaction_log.h