rippled: beast::buffer_view_test Class Reference
beast::buffer_view_test Class Reference
Public Member Functions
template<class C , class T >
void check (C const &c, buffer_view< T > v)
template<class V >
void checkBadIndex (V &v, std::enable_if_t< std::is_const< typename V::value_type >::value > *=0)
template<class V >
void checkBadIndex (V &v, std::enable_if_t< !std::is_const< typename V::value_type >::value > *=0)
template<class V >
void checkEmpty (V &v)
void testEmpty ()
template<class C >
void testConstructConst (C const &c)
template<class C >
void testConstruct (C const &c)
void testConstruct ()
void testCoerce ()
void testAssign ()
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Static Public Member Functions
template<class FwdIt , class Size >
static bool eq_dist (FwdIt first, FwdIt last, Size size)
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 28 of file buffer_view.test.cpp.
Member Function Documentation
template<class C , class T > void beast::buffer_view_test::check (C const & c, buffer_view< T > v) inline
Definition at line 48 of file buffer_view.test.cpp.
References beast::buffer_view< T, Tag >::back(), beast::buffer_view< T, Tag >::begin(), beast::buffer_view< T, Tag >::capacity(), beast::buffer_view< T, Tag >::cbegin(), beast::buffer_view< T, Tag >::cend(), beast::buffer_view< T, Tag >::crbegin(), beast::buffer_view< T, Tag >::crend(), beast::buffer_view< T, Tag >::empty(), beast::buffer_view< T, Tag >::end(), eq_dist(), std::detail::equal(), beast::unit_test::suite::expect(), beast::buffer_view< T, Tag >::front(), beast::buffer_view< T, Tag >::max_size(), beast::buffer_view< T, Tag >::rbegin(), beast::buffer_view< T, Tag >::rend(), and beast::buffer_view< T, Tag >::size().
Referenced by testConstruct(), and testConstructConst().
     {
         expect (! v.empty() || c.empty());
         expect (v.size() == c.size());
         expect (v.max_size() == v.size());
         expect (v.capacity() == v.size());
         expect (eq_dist (v.begin(), v.end(), v.size()));
         expect (eq_dist (v.cbegin(), v.cend(), v.size()));
         expect (eq_dist (v.rbegin(), v.rend(), v.size()));
         expect (eq_dist (v.crbegin(), v.crend(), v.size()));
         expect (std::equal (
             c.cbegin(), c.cend(), v.cbegin(), v.cend()));
         expect (std::equal (
             c.crbegin(), c.crend(), v.crbegin(), v.crend()));
         if (v.size() == c.size())
         {
             if (! v.empty())
             {
                 expect (v.front() == c.front());
                 expect (v.back() == c.back());
             }
             for (std::size_t i (0); i < v.size(); ++i)
                 expect (v[i] == c[i]);
         }
     }
template<class V > void beast::buffer_view_test::checkBadIndex (V & v, std::enable_if_t< std::is_const< typename V::value_type >::value > * = 0) inline
Definition at line 83 of file buffer_view.test.cpp.
References beast::unit_test::suite::fail(), and beast::unit_test::suite::pass().
Referenced by checkEmpty().
     {
         try
         {
             v.at(0);
             fail();
         }
         catch (std::out_of_range e)
         {
             pass();
         }
         catch (...)
         {
             fail();
         }
     }
template<class V > void beast::buffer_view_test::checkBadIndex (V & v, std::enable_if_t< !std::is_const< typename V::value_type >::value > * = 0) inline
Definition at line 104 of file buffer_view.test.cpp.
References beast::unit_test::suite::fail(), and beast::unit_test::suite::pass().
     {
         try
         {
             v.at(0);
             fail();
         }
         catch (std::out_of_range e)
         {
             pass();
         }
         catch (...)
         {
             fail();
         }
         try
         {
             v.at(0) = 1;
             fail();
         }
         catch (std::out_of_range e)
         {
             pass();
         }
         catch (...)
         {
             fail();
         }
     }
template<class V > void beast::buffer_view_test::checkEmpty (V & v) inline
Definition at line 139 of file buffer_view.test.cpp.
References checkBadIndex(), and beast::unit_test::suite::expect().
Referenced by testEmpty().
     {
         expect (v.empty());
         expect (v.size() == 0);
         expect (v.max_size() == v.size());
         expect (v.capacity() == v.size());
         expect (v.begin() == v.end());
         expect (v.cbegin() == v.cend());
         expect (v.begin() == v.cend());
         expect (v.rbegin() == v.rend());
         expect (v.crbegin() == v.rend());
         checkBadIndex (v);
     }
template<class FwdIt , class Size > static bool beast::buffer_view_test::eq_dist (FwdIt first, FwdIt last, Size size) inline static
Definition at line 33 of file buffer_view.test.cpp.
References value.
Referenced by check().
     {
         auto const dist (std::distance (first, last));
         static_assert (std::is_signed <decltype (dist)>::value,
             "dist must be signed");
         if (dist < 0)
             return false;
         return static_cast <Size> (dist) == size;
     }
void beast::buffer_view_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 309 of file buffer_view.test.cpp.
References testAssign(), testCoerce(), testConstruct(), and testEmpty().
     {
         testEmpty();
         testConstruct();
         testCoerce();
         testAssign();
     }
void beast::buffer_view_test::testAssign () inline
Definition at line 266 of file buffer_view.test.cpp.
References std::detail::equal(), beast::unit_test::suite::expect(), and beast::unit_test::suite::testcase().
Referenced by run().
     {
         testcase ("testAssign");
         std::vector <int> v1({1, 2, 3});
         buffer_view<int> r1(v1);
         std::vector <int> v2({4, 5, 6, 7});
         buffer_view<int> r2(v2);
         r1 = r2;
         expect (std::equal (r1.begin(), r1.end(), v2.begin(), v2.end()));
     }
void beast::buffer_view_test::testCoerce () inline
Definition at line 254 of file buffer_view.test.cpp.
References beast::unit_test::suite::pass(), and beast::unit_test::suite::testcase().
Referenced by run().
     {
         testcase ("coerce");
         std::string const s ("hello");
         const_buffer_view <unsigned char> v (s);
         pass();
     }
template<class C > void beast::buffer_view_test::testConstruct (C const & c) inline
Definition at line 221 of file buffer_view.test.cpp.
References check(), std::detail::equal(), beast::unit_test::suite::expect(), testConstructConst(), and value.
     {
         static_assert (! std::is_const <typename C::value_type>::value,
             "Container value_type cannot be const");
         testConstructConst (c);
         typedef buffer_view <typename C::value_type> V;
         C cp (c);
         V v (cp);
         check (cp, v);
         std::reverse (v.begin(), v.end());
         check (cp, v);
         expect (std::equal (v.rbegin(), v.rend(),
             c.begin(), c.end()));
     }
void beast::buffer_view_test::testConstruct () inline
Definition at line 241 of file buffer_view.test.cpp.
References beast::unit_test::suite::testcase().
Referenced by run().
     {
         testcase ("std::vector <char>");
         testConstruct (
             std::vector <char> ({'h', 'e', 'l', 'l', 'o'}));
         testcase ("std::string <char>");
         testConstruct (
             std::basic_string <char> ("hello"));
     }
template<class C > void beast::buffer_view_test::testConstructConst (C const & c) inline
Definition at line 175 of file buffer_view.test.cpp.
References check().
Referenced by testConstruct().
     {
         typedef buffer_view <std::add_const_t <
             typename C::value_type>> V;
         {
             // construct from container
             V v (c);
             check (c, v);
             // construct from buffer_view
             V v2 (v);
             check (c, v2);
         }
         if (! c.empty())
         {
             {
                 // construct from const pointer range
                 V v (&c.front(), &c.back()+1);
                 check (c, v);
                 // construct from pointer and size
                 V v2 (&c.front(), c.size());
                 check (v, v2);
             }
             {
                 // construct from non const pointer range
                 C cp (c);
                 V v (&cp.front(), &cp.back()+1);
                 check (cp, v);
                 // construct from pointer and size
                 V v2 (&cp.front(), cp.size());
                 check (v, v2);
                 // construct from data and size
                 V v3 (v2.data(), v2.size());
                 check (c, v3);
             }
         }
     }
void beast::buffer_view_test::testEmpty () inline
Definition at line 155 of file buffer_view.test.cpp.
References checkEmpty(), beast::swap(), and beast::unit_test::suite::testcase().
Referenced by run().
     {
         testcase ("empty");
         buffer_view <char> v1;
         checkEmpty (v1);
         buffer_view <char> v2;
         swap (v1, v2);
         checkEmpty (v1);
         checkEmpty (v2);
         buffer_view <char const> v3 (v2);
         checkEmpty (v3);
     }
The documentation for this class was generated from the following file:
rippled/src/beast/beast/container/tests/buffer_view.test.cpp