rippled: ripple::Resource::Logic Class Reference
ripple::Resource::Logic Class Reference
#include <Logic.h>
Classes
struct State
struct Stats
Public Types
typedef beast::abstract_clock
< std::chrono::seconds > clock_type
typedef ripple::unordered_map
< std::string, Import > Imports
typedef ripple::unordered_map
< Key, Entry, Key::hasher,
Key::key_equal > Table
typedef beast::SharedData< State > SharedState
Public Member Functions
Logic (beast::insight::Collector::ptr const &collector, clock_type &clock, beast::Journal journal)
~Logic ()
Consumer newInboundEndpoint (beast::IP::Endpoint const &address)
Consumer newOutboundEndpoint (beast::IP::Endpoint const &address)
Consumer newAdminEndpoint (std::string const &name)
Entry & elevateToAdminEndpoint (Entry &prior, std::string const &name)
Json::Value getJson ()
Json::Value getJson (int threshold)
Gossip exportConsumers ()
void importConsumers (std::string const &origin, Gossip const &gossip)
bool isWhitelisted (beast::IP::Endpoint const &address)
void periodicActivity ()
void acquire (Entry &entry, SharedState::Access &state)
void release (Entry &entry, SharedState::Access &state)
void erase (Table::iterator iter, SharedState::Access &state)
Disposition charge (Entry &entry, Charge const &fee, SharedState::Access &state)
bool warn (Entry &entry, SharedState::Access &state)
bool disconnect (Entry &entry, SharedState::Access &state)
int balance (Entry &entry, SharedState::Access &state)
void acquire (Entry &entry)
void release (Entry &entry)
Disposition charge (Entry &entry, Charge const &fee)
bool warn (Entry &entry)
bool disconnect (Entry &entry)
int balance (Entry &entry)
void writeList (clock_type::rep const now, beast::PropertyStream::Set &items, beast::List< Entry > &list)
void onWrite (beast::PropertyStream::Map &map)
Static Public Member Functions
static Disposition disposition (int balance)
Public Attributes
SharedState m_state
Stats m_stats
beast::abstract_clock
< std::chrono::seconds > & m_clock
beast::Journal m_journal
Detailed Description
Definition at line 30 of file Logic.h.
Member Typedef Documentation
typedef beast::abstract_clock<std::chrono::seconds> ripple::Resource::Logic::clock_type
Definition at line 33 of file Logic.h.
typedef ripple::unordered_map<std::string, Import> ripple::Resource::Logic::Imports
Definition at line 34 of file Logic.h.
typedef beast::SharedData<State> ripple::Resource::Logic::SharedState
Definition at line 58 of file Logic.h.
typedef ripple::unordered_map<Key, Entry, Key::hasher, Key::key_equal> ripple::Resource::Logic::Table
Definition at line 35 of file Logic.h.
Constructor & Destructor Documentation
ripple::Resource::Logic::Logic (beast::insight::Collector::ptr const & collector, clock_type & clock, beast::Journal journal) inline
Definition at line 79 of file Logic.h.
         : m_stats (collector)
         , m_clock (clock)
         , m_journal (journal)
     {
     }
ripple::Resource::Logic::~Logic () inline
Definition at line 87 of file Logic.h.
References m_state.
     {
         // These have to be cleared before the Logic is destroyed
         // since their destructors call back into the class.
         // Order matters here as well, the import table has to be
         // destroyed before the consumer table.
         //
         SharedState::UnlockedAccess state (m_state);
         state->import_table.clear();
         state->table.clear();
     }
Member Function Documentation
void ripple::Resource::Logic::acquire (Entry & entry, SharedState::Access & state) inline
Definition at line 431 of file Logic.h.
References ripple::Resource::Entry::refcount.
Referenced by acquire(), ripple::Resource::Consumer::Consumer(), and ripple::Resource::Consumer::operator=().
     {
         ++entry.refcount;
     }
void ripple::Resource::Logic::acquire (Entry & entry) inline
Definition at line 526 of file Logic.h.
References acquire(), and m_state.
     {
         SharedState::Access state (m_state);
         acquire (entry, state);
     }
int ripple::Resource::Logic::balance (Entry & entry, SharedState::Access & state) inline
Definition at line 519 of file Logic.h.
References ripple::Resource::Entry::balance(), beast::abstract_clock< Duration >::elapsed(), and m_clock.
Referenced by ripple::Resource::Consumer::balance(), balance(), and charge().
     {
         return entry.balance (m_clock.elapsed());
     }
int ripple::Resource::Logic::balance (Entry & entry) inline
Definition at line 562 of file Logic.h.
References balance(), and m_state.
     {
         SharedState::Access state (m_state);
         return balance (entry, state);
     }
Disposition ripple::Resource::Logic::charge (Entry & entry, Charge const & fee, SharedState::Access & state) inline
Definition at line 475 of file Logic.h.
References ripple::Resource::Entry::add(), balance(), ripple::Resource::Charge::cost(), disposition(), beast::abstract_clock< Duration >::elapsed(), m_clock, m_journal, and beast::Journal::trace.
Referenced by ripple::Resource::Consumer::charge(), charge(), disconnect(), and warn().
     {
         clock_type::rep const now (m_clock.elapsed());
         int const balance (entry.add (fee.cost(), now));
         m_journal.trace <<
             "Charging " << entry << " for " << fee;
         return disposition (balance);
     }
Disposition ripple::Resource::Logic::charge (Entry & entry, Charge const & fee) inline
Definition at line 538 of file Logic.h.
References charge(), and m_state.
     {
         SharedState::Access state (m_state);
         return charge (entry, fee, state);
     }
bool ripple::Resource::Logic::disconnect (Entry & entry, SharedState::Access & state) inline
Definition at line 505 of file Logic.h.
References ripple::Resource::Entry::balance(), charge(), ripple::Resource::drop, ripple::Resource::Logic::Stats::drop, ripple::Resource::dropThreshold, beast::abstract_clock< Duration >::elapsed(), ripple::Resource::feeDrop, m_clock, and m_stats.
Referenced by ripple::Resource::Consumer::disconnect(), and disconnect().
     {
         bool drop (false);
         clock_type::rep const now (m_clock.elapsed());
         if (entry.balance (now) >= dropThreshold)
         {
             charge (entry, feeDrop, state);
             drop = true;
         }
         if (drop)
             ++m_stats.drop;
         return drop;
     }
bool ripple::Resource::Logic::disconnect (Entry & entry) inline
Definition at line 553 of file Logic.h.
References ripple::Resource::Entry::admin(), disconnect(), and m_state.
     {
         if (entry.admin())
             return false;
         SharedState::Access state (m_state);
         return disconnect (entry, state);
     }
static Disposition ripple::Resource::Logic::disposition (int balance) inline static
Definition at line 420 of file Logic.h.
References ripple::Resource::drop, ripple::Resource::dropThreshold, ripple::Resource::ok, ripple::Resource::warn, and ripple::Resource::warningThreshold.
Referenced by charge().
     {
         if (balance >= dropThreshold)
             return Disposition::drop;
         if (balance >= warningThreshold)
             return Disposition::warn;
         return Disposition::ok;
     }
Entry& ripple::Resource::Logic::elevateToAdminEndpoint (Entry & prior, std::string const & name) inline
Definition at line 195 of file Logic.h.
References beast::Journal::info, ripple::Resource::Entry::key, ripple::Resource::Key::kind, ripple::Resource::kindAdmin, m_journal, m_state, ripple::Resource::Key::name, name, and release().
Referenced by ripple::Resource::Consumer::elevate().
     {
         Key key;
         key.kind = kindAdmin;
         key.name = name;
         m_journal.info <<
             "Elevate " << prior << " to " << name;
         Entry* entry (nullptr);
         {
             SharedState::Access state (m_state);
             std::pair <Table::iterator, bool> result (
                 state->table.emplace (key, 0));
             entry = &result.first->second;
             entry->key = &result.first->first;
             ++entry->refcount;
             if (entry->refcount == 1)
             {
                 if (! result.second)
                     state->inactive.erase (
                         state->inactive.iterator_to (*entry));
                 state->admin.push_back (*entry);
             }
             release (prior, state);
         }
         return *entry;
     }
void ripple::Resource::Logic::erase (Table::iterator iter, SharedState::Access & state) inline
Definition at line 466 of file Logic.h.
References bassert, and ripple::Resource::Entry::refcount.
Referenced by periodicActivity().
     {
         Entry& entry (iter->second);
         bassert (entry.refcount == 0);
         state->inactive.erase (
             state->inactive.iterator_to (entry));
         state->table.erase (iter);
     }
Gossip ripple::Resource::Logic::exportConsumers () inline
Definition at line 282 of file Logic.h.
References ripple::Resource::Gossip::Item::address, beast::IP::Endpoint::address(), ripple::Resource::Gossip::Item::balance, beast::abstract_clock< Duration >::elapsed(), m_clock, m_state, and ripple::Resource::minimumGossipBalance.
Referenced by ripple::Resource::ManagerImp::exportConsumers().
     {
         clock_type::rep const now (m_clock.elapsed());
         Gossip gossip;
         SharedState::Access state (m_state);
         gossip.items.reserve (state->inbound.size());
         for (beast::List <Entry>::iterator iter (state->inbound.begin());
             iter != state->inbound.end(); ++iter)
         {
             Gossip::Item item;
             item.balance = iter->local_balance.value (now);
             if (item.balance >= minimumGossipBalance)
             {
                 item.address = iter->key->address;
                 gossip.items.push_back (item);
             }
         }
         return gossip;
     }
Json::Value ripple::Resource::Logic::getJson () inline
Definition at line 227 of file Logic.h.
References ripple::Resource::warningThreshold.
Referenced by ripple::Resource::ManagerImp::getJson().
     {
         return getJson (warningThreshold);
     }
Json::Value ripple::Resource::Logic::getJson (int threshold) inline
Definition at line 232 of file Logic.h.
References beast::abstract_clock< Duration >::elapsed(), m_clock, m_state, and Json::objectValue.
     {
         clock_type::rep const now (m_clock.elapsed());
         Json::Value ret (Json::objectValue);
         SharedState::Access state (m_state);
         for (beast::List <Entry>::iterator iter (state->inbound.begin());
             iter != state->inbound.end(); ++iter)
         {
             int localBalance = iter->local_balance.value (now);
             if ((localBalance + iter->remote_balance) >= threshold)
             {
                 Json::Value& entry = (ret[iter->to_string()] = Json::objectValue);
                 entry["local"] = localBalance;
                 entry["remote"] = iter->remote_balance;
                 entry["type"] = "outbound";
             }
         }
         for (beast::List <Entry>::iterator iter (state->outbound.begin());
             iter != state->outbound.end(); ++iter)
         {
             int localBalance = iter->local_balance.value (now);
             if ((localBalance + iter->remote_balance) >= threshold)
             {
                 Json::Value& entry = (ret[iter->to_string()] = Json::objectValue);
                 entry["local"] = localBalance;
                 entry["remote"] = iter->remote_balance;
                 entry["type"] = "outbound";
             }
         }
         for (beast::List <Entry>::iterator iter (state->admin.begin());
             iter != state->admin.end(); ++iter)
         {
             int localBalance = iter->local_balance.value (now);
             if ((localBalance + iter->remote_balance) >= threshold)
             {
                 Json::Value& entry = (ret[iter->to_string()] = Json::objectValue);
                 entry["local"] = localBalance;
                 entry["remote"] = iter->remote_balance;
                 entry["type"] = "admin";
             }
         }
         return ret;
     }
void ripple::Resource::Logic::importConsumers (std::string const & origin, Gossip const & gossip) inline
Definition at line 308 of file Logic.h.
References ripple::Resource::Import::Item::balance, ripple::Resource::Import::Item::consumer, beast::abstract_clock< Duration >::elapsed(), ripple::Resource::Consumer::entry(), ripple::Resource::gossipExpirationSeconds, ripple::Resource::Gossip::items, ripple::Resource::Import::items, m_clock, m_state, newInboundEndpoint(), next, prev, ripple::Resource::Entry::remote_balance, beast::asio::swap(), and ripple::Resource::Import::whenExpires.
Referenced by ripple::Resource::ManagerImp::importConsumers(), ripple::Resource::Manager_test::testImport(), and ripple::Resource::Manager_test::testImports().
     {
         clock_type::rep const now (m_clock.elapsed());
         {
             SharedState::Access state (m_state);
             std::pair <Imports::iterator, bool> result (
                 state->import_table.emplace (origin, 0));
             if (result.second)
             {
                 // This is a new import
                 Import& next (result.first->second);
                 next.whenExpires = now + gossipExpirationSeconds;
                 next.items.reserve (gossip.items.size());
                 for (std::vector <Gossip::Item>::const_iterator iter (gossip.items.begin());
                     iter != gossip.items.end(); ++iter)
                 {
                     Import::Item item;
                     item.balance = iter->balance;
                     item.consumer = newInboundEndpoint (iter->address);
                     item.consumer.entry().remote_balance += item.balance;
                     next.items.push_back (item);
                 }
             }
             else
             {
                 // Previous import exists so add the new remote
                 // balances and then deduct the old remote balances.
                 Import next;
                 next.whenExpires = now + gossipExpirationSeconds;
                 next.items.reserve (gossip.items.size());
                 for (std::vector <Gossip::Item>::const_iterator iter (gossip.items.begin());
                     iter != gossip.items.end(); ++iter)
                 {
                     Import::Item item;
                     item.balance = iter->balance;
                     item.consumer = newInboundEndpoint (iter->address);
                     item.consumer.entry().remote_balance += item.balance;
                     next.items.push_back (item);
                 }
                 Import& prev (result.first->second);
                 for (std::vector <Import::Item>::iterator iter (prev.items.begin());
                     iter != prev.items.end(); ++iter)
                 {
                     iter->consumer.entry().remote_balance -= iter->balance;
                 }
                 std::swap (next, prev);
             }
         }
     }
bool ripple::Resource::Logic::isWhitelisted (beast::IP::Endpoint const & address) inline
Definition at line 365 of file Logic.h.
References beast::IP::is_public().
Referenced by newInboundEndpoint(), and newOutboundEndpoint().
     {
         if (! is_public (address))
             return true;
         return false;
     }
Consumer ripple::Resource::Logic::newAdminEndpoint (std::string const & name) inline
Definition at line 165 of file Logic.h.
References beast::Journal::debug, ripple::Resource::Entry::key, ripple::Resource::Key::kind, ripple::Resource::kindAdmin, m_journal, m_state, ripple::Resource::Key::name, and name.
Referenced by ripple::Resource::ManagerImp::newAdminEndpoint(), newInboundEndpoint(), and newOutboundEndpoint().
     {
         Key key;
         key.kind = kindAdmin;
         key.name = name;
         Entry* entry (nullptr);
         {
             SharedState::Access state (m_state);
             std::pair <Table::iterator, bool> result (
                 state->table.emplace (key, 0));
             entry = &result.first->second;
             entry->key = &result.first->first;
             ++entry->refcount;
             if (entry->refcount == 1)
             {
                 if (! result.second)
                     state->inactive.erase (
                         state->inactive.iterator_to (*entry));
                 state->admin.push_back (*entry);
             }
         }
         m_journal.debug <<
             "New admin endpoint " << *entry;
         return Consumer (*this, *entry);
     }
Consumer ripple::Resource::Logic::newInboundEndpoint (beast::IP::Endpoint const & address) inline
Definition at line 99 of file Logic.h.
References ripple::Resource::Key::address, beast::IP::Endpoint::at_port(), beast::Journal::debug, isWhitelisted(), ripple::Resource::Entry::key, ripple::Resource::Key::kind, ripple::Resource::kindInbound, m_journal, m_state, newAdminEndpoint(), and ripple::to_string().
Referenced by importConsumers(), ripple::Resource::ManagerImp::newInboundEndpoint(), ripple::Resource::Manager_test::testCharges(), and ripple::Resource::Manager_test::testDrop().
     {
         if (isWhitelisted (address))
             return newAdminEndpoint (to_string (address));
         Key key;
         key.kind = kindInbound;
         key.address = address.at_port (0);
         Entry* entry (nullptr);
         {
             SharedState::Access state (m_state);
             std::pair <Table::iterator, bool> result (
                 state->table.emplace (key, 0));
             entry = &result.first->second;
             entry->key = &result.first->first;
             ++entry->refcount;
             if (entry->refcount == 1)
             {
                 if (! result.second)
                     state->inactive.erase (
                         state->inactive.iterator_to (*entry));
                 state->inbound.push_back (*entry);
             }
         }
         m_journal.debug <<
             "New inbound endpoint " << *entry;
         return Consumer (*this, *entry);
     }
Consumer ripple::Resource::Logic::newOutboundEndpoint (beast::IP::Endpoint const & address) inline
Definition at line 132 of file Logic.h.
References ripple::Resource::Key::address, beast::Journal::debug, isWhitelisted(), ripple::Resource::Entry::key, ripple::Resource::Key::kind, ripple::Resource::kindOutbound, m_journal, m_state, newAdminEndpoint(), and ripple::to_string().
Referenced by ripple::Resource::ManagerImp::newOutboundEndpoint().
     {
         if (isWhitelisted (address))
             return newAdminEndpoint (to_string (address));
         Key key;
         key.kind = kindOutbound;
         key.address = address;
         Entry* entry (nullptr);
         {
             SharedState::Access state (m_state);
             std::pair <Table::iterator, bool> result (
                 state->table.emplace (key, 0));
             entry = &result.first->second;
             entry->key = &result.first->first;
             ++entry->refcount;
             if (entry->refcount == 1)
             {
                 if (! result.second)
                     state->inactive.erase (
                         state->inactive.iterator_to (*entry));
                 state->outbound.push_back (*entry);
             }
         }
         m_journal.debug <<
             "New outbound endpoint " << *entry;
         return Consumer (*this, *entry);
     }
void ripple::Resource::Logic::onWrite (beast::PropertyStream::Map & map) inline
Definition at line 588 of file Logic.h.
References beast::abstract_clock< Duration >::elapsed(), m_clock, m_state, and writeList().
Referenced by ripple::Resource::ManagerImp::onWrite().
     {
         clock_type::rep const now (m_clock.elapsed());
         SharedState::Access state (m_state);
         {
             beast::PropertyStream::Set s ("inbound", map);
             writeList (now, s, state->inbound);
         }
         {
             beast::PropertyStream::Set s ("outbound", map);
             writeList (now, s, state->outbound);
         }
         {
             beast::PropertyStream::Set s ("admin", map);
             writeList (now, s, state->admin);
         }
         {
             beast::PropertyStream::Set s ("inactive", map);
             writeList (now, s, state->inactive);
         }
     }
void ripple::Resource::Logic::periodicActivity () inline
Definition at line 375 of file Logic.h.
References beast::Journal::debug, beast::abstract_clock< Duration >::elapsed(), erase(), m_clock, m_journal, and m_state.
Referenced by ripple::Resource::ManagerImp::run().
     {
         SharedState::Access state (m_state);
         clock_type::rep const now (m_clock.elapsed());
         for (beast::List <Entry>::iterator iter (
             state->inactive.begin()); iter != state->inactive.end();)
         {
             if (iter->whenExpires <= now)
             {
                 m_journal.debug << "Expired " << *iter;
                 Table::iterator table_iter (
                     state->table.find (*iter->key));
                 ++iter;
                 erase (table_iter, state);
             }
             else
             {
                 break;
             }
         }
         Imports::iterator iter (state->import_table.begin());
         while (iter != state->import_table.end())
         {
             Import& import (iter->second);
             if (iter->second.whenExpires <= now)
             {
                 for (std::vector <Import::Item>::iterator item_iter (import.items.begin());
                     item_iter != import.items.end(); ++item_iter)
                 {
                     item_iter->consumer.entry().remote_balance -= item_iter->balance;
                 }
                 iter = state->import_table.erase (iter);
             }
             else
                 ++iter;
         }
     }
void ripple::Resource::Logic::release (Entry & entry, SharedState::Access & state) inline
Definition at line 436 of file Logic.h.
References bassertfalse, beast::Journal::debug, beast::abstract_clock< Duration >::elapsed(), ripple::Resource::Entry::key, ripple::Resource::Key::kind, ripple::Resource::kindAdmin, ripple::Resource::kindInbound, ripple::Resource::kindOutbound, m_clock, m_journal, ripple::Resource::Entry::refcount, ripple::Resource::secondsUntilExpiration, and ripple::Resource::Entry::whenExpires.
Referenced by elevateToAdminEndpoint(), ripple::Resource::Consumer::operator=(), release(), and ripple::Resource::Consumer::~Consumer().
     {
         if (--entry.refcount == 0)
         {
             m_journal.debug <<
                 "Inactive " << entry;
             switch (entry.key->kind)
             {
             case kindInbound:
                 state->inbound.erase (
                     state->inbound.iterator_to (entry));
                 break;
             case kindOutbound:
                 state->outbound.erase (
                     state->outbound.iterator_to (entry));
                 break;
             case kindAdmin:
                 state->admin.erase (
                     state->admin.iterator_to (entry));
                 break;
             default:
                 bassertfalse;
                 break;
             }
             state->inactive.push_back (entry);
             entry.whenExpires = m_clock.elapsed() + secondsUntilExpiration;
         }
     }
void ripple::Resource::Logic::release (Entry & entry) inline
Definition at line 532 of file Logic.h.
References m_state, and release().
     {
         SharedState::Access state (m_state);
         release (entry, state);
     }
bool ripple::Resource::Logic::warn (Entry & entry, SharedState::Access & state) inline
Definition at line 484 of file Logic.h.
References ripple::Resource::Entry::balance(), charge(), beast::abstract_clock< Duration >::elapsed(), ripple::Resource::feeWarning, beast::Journal::info, ripple::Resource::Entry::lastWarningTime, m_clock, m_journal, m_stats, ripple::Resource::Logic::Stats::warn, and ripple::Resource::warningThreshold.
Referenced by ripple::Resource::Consumer::warn(), and warn().
     {
         bool notify (false);
         clock_type::rep const now (m_clock.elapsed());
         if (entry.balance (now) >= warningThreshold && now != entry.lastWarningTime)
         {
             charge (entry, feeWarning, state);
             notify = true;
             entry.lastWarningTime = now;
         }
         if (notify)
             m_journal.info <<
                 "Load warning: " << entry;
         if (notify)
             ++m_stats.warn;
         return notify;
     }
bool ripple::Resource::Logic::warn (Entry & entry) inline
Definition at line 544 of file Logic.h.
References ripple::Resource::Entry::admin(), m_state, and warn().
     {
         if (entry.admin())
             return false;
         SharedState::Access state (m_state);
         return warn (entry, state);
     }
void ripple::Resource::Logic::writeList (clock_type::rep const now, beast::PropertyStream::Set & items, beast::List< Entry > & list) inline
Definition at line 570 of file Logic.h.
References beast::List< typename, typename >::begin(), and beast::List< typename, typename >::end().
Referenced by onWrite().
     {
         for (beast::List <Entry>::iterator iter (list.begin());
             iter != list.end(); ++iter)
         {
             beast::PropertyStream::Map item (items);
             if (iter->refcount != 0)
                 item ["count"] = iter->refcount;
             item ["name"] = iter->to_string();
             item ["balance"] = iter->balance(now);
             if (iter->remote_balance != 0)
                 item ["remote_balance"] = iter->remote_balance;
         }
     }
Member Data Documentation
beast::abstract_clock<std::chrono::seconds>& ripple::Resource::Logic::m_clock
Definition at line 74 of file Logic.h.
Referenced by balance(), charge(), disconnect(), exportConsumers(), getJson(), importConsumers(), onWrite(), periodicActivity(), release(), and warn().
beast::Journal ripple::Resource::Logic::m_journal
Definition at line 75 of file Logic.h.
Referenced by charge(), elevateToAdminEndpoint(), newAdminEndpoint(), newInboundEndpoint(), newOutboundEndpoint(), periodicActivity(), release(), and warn().
SharedState ripple::Resource::Logic::m_state
Definition at line 72 of file Logic.h.
Referenced by acquire(), balance(), charge(), disconnect(), elevateToAdminEndpoint(), exportConsumers(), getJson(), importConsumers(), newAdminEndpoint(), newInboundEndpoint(), newOutboundEndpoint(), onWrite(), periodicActivity(), release(), warn(), and ~Logic().
Stats ripple::Resource::Logic::m_stats
Definition at line 73 of file Logic.h.
Referenced by disconnect(), and warn().
The documentation for this class was generated from the following file:
rippled/src/ripple/resource/impl/Logic.h