rippled: rippled/src/beast/beast/crypto/impl/sha2/sha2prog.c File Reference
sha2prog.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <sysexits.h>
#include <sys/types.h>
#include <sys/uio.h>
#include <unistd.h>
#include "sha2.h"
Macros
#define BUFLEN 16384
Functions
void usage (char *prog, char *msg)
int main (int argc, char **argv)
Macro Definition Documentation
#define BUFLEN 16384
Definition at line 48 of file sha2prog.c.
Referenced by main().
Function Documentation
int main (int argc, char ** argv)
Definition at line 50 of file sha2prog.c.
References BUFLEN, hash, beast::asio::InputParser::read(), SHA256_End(), SHA256_Init(), SHA256_Update(), SHA384_End(), SHA384_Init(), SHA384_Update(), SHA512_End(), SHA512_Init(), SHA512_Update(), and usage().
{
     int     kl, l, fd, ac;
     int     quiet = 0, hash = 0;
     char        *av, *file = (char*)0;
     FILE        *IN = (FILE*)0;
     SHA256_CTX  ctx256;
     SHA384_CTX  ctx384;
     SHA512_CTX  ctx512;
     unsigned char   buf[BUFLEN];
     SHA256_Init(&ctx256);
     SHA384_Init(&ctx384);
     SHA512_Init(&ctx512);
     /* Read data from STDIN by default */
     fd = fileno(stdin);
     ac = 1;
     while (ac < argc) {
         if (*argv[ac] == '-') {
             av = argv[ac] + 1;
             if (!strcmp(av, "q")) {
                 quiet = 1;
             } else if (!strcmp(av, "256")) {
                 hash |= 1;
             } else if (!strcmp(av, "384")) {
                 hash |= 2;
             } else if (!strcmp(av, "512")) {
                 hash |= 4;
             } else if (!strcmp(av, "ALL")) {
                 hash = 7;
             } else {
                 usage(argv[0], "Invalid option.");
             }
             ac++;
         } else {
             file = argv[ac++];
             if (ac != argc) {
                 usage(argv[0], "Too many arguments.");
             }
             if ((IN = fopen(file, "r")) == NULL) {
                 perror(argv[0]);
                 exit(-1);
             }
             fd = fileno(IN);
         }
     }
     if (hash == 0)
         hash = 7;   /* Default to ALL */
     kl = 0;
     while ((l = read(fd,buf,BUFLEN)) > 0) {
         kl += l;
         SHA256_Update(&ctx256, (unsigned char*)buf, l);
         SHA384_Update(&ctx384, (unsigned char*)buf, l);
         SHA512_Update(&ctx512, (unsigned char*)buf, l);
     }
     if (file) {
         fclose(IN);
     }
     if (hash & 1) {
         SHA256_End(&ctx256, buf);
         if (!quiet)
             printf("SHA-256 (%s) = ", file);
         printf("%s\n", buf);
     }
     if (hash & 2) {
         SHA384_End(&ctx384, buf);
         if (!quiet)
             printf("SHA-384 (%s) = ", file);
         printf("%s\n", buf);
     }
     if (hash & 4) {
         SHA512_End(&ctx512, buf);
         if (!quiet)
             printf("SHA-512 (%s) = ", file);
         printf("%s\n", buf);
     }
     return 1;
 }
void usage (char * prog, char * msg)
Definition at line 43 of file sha2prog.c.
Referenced by main(), ripple::RPCServerHandler::processRequest(), and ripple::RPCHTTPServerImp::processRequest().
{
     fprintf(stderr, "%s\nUsage:\t%s [options] [<file>]\nOptions:\n\t-256\tGenerate SHA-256 hash\n\t-384\tGenerate SHA-284 hash\n\t-512\tGenerate SHA-512 hash\n\t-ALL\tGenerate all three hashes\n\t-q\tQuiet mode - only output hexadecimal hashes, one per line\n\n", msg, prog);
     exit(-1);
 }