rippled: beast::Range< ValueType > Class Template Reference
beast::Range< ValueType > Class Template Reference
#include <Range.h>
Public Member Functions
Range () noexcept
Range (const ValueType startValue, const ValueType endValue) noexcept
Range (const Range &other) noexcept
Range & operator= (Range other) noexcept
ValueType getStart () const noexcept
ValueType getLength () const noexcept
ValueType getEnd () const noexcept
bool isEmpty () const noexcept
void setStart (const ValueType newStart) noexcept
Range withStart (const ValueType newStart) const noexcept
Range movedToStartAt (const ValueType newStart) const noexcept
void setEnd (const ValueType newEnd) noexcept
Range withEnd (const ValueType newEnd) const noexcept
Range movedToEndAt (const ValueType newEnd) const noexcept
void setLength (const ValueType newLength) noexcept
Range withLength (const ValueType newLength) const noexcept
Range operator+= (const ValueType amountToAdd) noexcept
Range operator-= (const ValueType amountToSubtract) noexcept
Range operator+ (const ValueType amountToAdd) const noexcept
Range operator- (const ValueType amountToSubtract) const noexcept
bool operator== (Range other) const noexcept
bool operator!= (Range other) const noexcept
bool contains (const ValueType position) const noexcept
ValueType clipValue (const ValueType value) const noexcept
bool contains (Range other) const noexcept
bool intersects (Range other) const noexcept
Range getIntersectionWith (Range other) const noexcept
Range getUnionWith (Range other) const noexcept
Range constrainRange (Range rangeToConstrain) const noexcept
Static Public Member Functions
static Range between (const ValueType position1, const ValueType position2) noexcept
static Range emptyRange (const ValueType start) noexcept
Private Attributes
ValueType start
ValueType end
Detailed Description
template<typename ValueType>
class beast::Range< ValueType >
A general-purpose range object, that simply represents any linear range with a start and end point.
The templated parameter is expected to be a primitive integer or floating point type, though class types could also be used if they behave in a number-like way.
Definition at line 39 of file Range.h.
Constructor & Destructor Documentation
template<typename ValueType > beast::Range< ValueType >::Range () inline noexcept
Constructs an empty range.
Definition at line 44 of file Range.h.
Referenced by beast::Range< ValueType >::between(), beast::Range< ValueType >::emptyRange(), beast::Range< ValueType >::getIntersectionWith(), beast::Range< ValueType >::getUnionWith(), beast::Range< ValueType >::movedToEndAt(), beast::Range< ValueType >::movedToStartAt(), beast::Range< ValueType >::operator+(), beast::Range< ValueType >::operator-(), beast::Range< ValueType >::withEnd(), beast::Range< ValueType >::withLength(), and beast::Range< ValueType >::withStart().
                       : start(), end()
     {
     }
template<typename ValueType > beast::Range< ValueType >::Range (const ValueType startValue, const ValueType endValue) inline noexcept
Constructs a range with given start and end values.
Definition at line 49 of file Range.h.
         : start (startValue), end (bmax (startValue, endValue))
     {
     }
template<typename ValueType > beast::Range< ValueType >::Range (const Range< ValueType > & other) inline noexcept
Constructs a copy of another range.
Definition at line 55 of file Range.h.
         : start (other.start), end (other.end)
     {
     }
Member Function Documentation
template<typename ValueType > static Range beast::Range< ValueType >::between (const ValueType position1, const ValueType position2) inline static noexcept
Returns the range that lies between two positions (in either order).
Definition at line 69 of file Range.h.
References beast::Range< ValueType >::Range().
     {
         return position1 < position2 ? Range (position1, position2)
                                      : Range (position2, position1);
     }
template<typename ValueType > ValueType beast::Range< ValueType >::clipValue (const ValueType value) const inline noexcept
Returns the nearest value to the one supplied, which lies within the range.
Definition at line 206 of file Range.h.
References beast::blimit(), beast::Range< ValueType >::end, beast::Range< ValueType >::start, and value.
     {
         return blimit (start, end, value);
     }
template<typename ValueType > Range beast::Range< ValueType >::constrainRange (Range< ValueType > rangeToConstrain) const inline noexcept
Returns a given range, after moving it forwards or backwards to fit it within this range.
If the supplied range has a greater length than this one, the return value will be this range.
Otherwise, if the supplied range is smaller than this one, the return value will be the new range, shifted forwards or backwards so that it doesn't extend beyond this one, but keeping its original length.
Definition at line 248 of file Range.h.
References beast::blimit(), beast::Range< ValueType >::end, beast::Range< ValueType >::getLength(), and beast::Range< ValueType >::start.
     {
         const ValueType otherLen = rangeToConstrain.getLength();
         return getLength() <= otherLen
                 ? *this
                 : rangeToConstrain.movedToStartAt (blimit (start, end - otherLen, rangeToConstrain.getStart()));
     }
template<typename ValueType > bool beast::Range< ValueType >::contains (const ValueType position) const inline noexcept
Returns true if the given position lies inside this range.
Definition at line 200 of file Range.h.
References beast::Range< ValueType >::end, and beast::Range< ValueType >::start.
     {
         return start <= position && position < end;
     }
template<typename ValueType > bool beast::Range< ValueType >::contains (Range< ValueType > other) const inline noexcept
Returns true if the given range lies entirely inside this range.
Definition at line 212 of file Range.h.
References beast::Range< ValueType >::end, and beast::Range< ValueType >::start.
     {
         return start <= other.start && end >= other.end;
     }
template<typename ValueType > static Range beast::Range< ValueType >::emptyRange (const ValueType start) inline static noexcept
Returns a range with the specified start position and a length of zero.
Definition at line 76 of file Range.h.
References beast::Range< ValueType >::Range(), and beast::Range< ValueType >::start.
     {
         return Range (start, start);
     }
template<typename ValueType > ValueType beast::Range< ValueType >::getEnd () const inline noexcept
Returns the end of the range.
Definition at line 89 of file Range.h.
References beast::Range< ValueType >::end.
 { return end; }
template<typename ValueType > Range beast::Range< ValueType >::getIntersectionWith (Range< ValueType > other) const inline noexcept
Returns the range that is the intersection of the two ranges, or an empty range with an undefined start position if they don't overlap.
Definition at line 225 of file Range.h.
References beast::bmax(), beast::bmin(), beast::Range< ValueType >::end, beast::Range< ValueType >::Range(), and beast::Range< ValueType >::start.
     {
         return Range (bmax (start, other.start),
                       bmin (end, other.end));
     }
template<typename ValueType > ValueType beast::Range< ValueType >::getLength () const inline noexcept
Returns the length of the range.
Definition at line 86 of file Range.h.
References beast::Range< ValueType >::end, and beast::Range< ValueType >::start.
Referenced by beast::Range< ValueType >::constrainRange().
 { return end - start; }
template<typename ValueType > ValueType beast::Range< ValueType >::getStart () const inline noexcept
Returns the start of the range.
Definition at line 83 of file Range.h.
References beast::Range< ValueType >::start.
 { return start; }
template<typename ValueType > Range beast::Range< ValueType >::getUnionWith (Range< ValueType > other) const inline noexcept
Returns the smallest range that contains both this one and the other one.
Definition at line 232 of file Range.h.
References beast::bmax(), beast::bmin(), beast::Range< ValueType >::end, beast::Range< ValueType >::Range(), and beast::Range< ValueType >::start.
     {
         return Range (bmin (start, other.start),
                       bmax (end, other.end));
     }
template<typename ValueType > bool beast::Range< ValueType >::intersects (Range< ValueType > other) const inline noexcept
Returns true if the given range intersects this one.
Definition at line 218 of file Range.h.
References beast::Range< ValueType >::end, and beast::Range< ValueType >::start.
     {
         return other.start < end && start < other.end;
     }
template<typename ValueType > bool beast::Range< ValueType >::isEmpty () const inline noexcept
Returns true if the range has a length of zero.
Definition at line 92 of file Range.h.
References beast::Range< ValueType >::end, and beast::Range< ValueType >::start.
 { return start == end; }
template<typename ValueType > Range beast::Range< ValueType >::movedToEndAt (const ValueType newEnd) const inline noexcept
Returns a range with the same length as this one, but moved to have the given end position.
Definition at line 142 of file Range.h.
References beast::Range< ValueType >::end, beast::Range< ValueType >::Range(), and beast::Range< ValueType >::start.
     {
         return Range (start + (newEnd - end), newEnd);
     }
template<typename ValueType > Range beast::Range< ValueType >::movedToStartAt (const ValueType newStart) const inline noexcept
Returns a range with the same length as this one, but moved to have the given start position.
Definition at line 116 of file Range.h.
References beast::Range< ValueType >::end, beast::Range< ValueType >::Range(), and beast::Range< ValueType >::start.
     {
         return Range (newStart, end + (newStart - start));
     }
template<typename ValueType > bool beast::Range< ValueType >::operator!= (Range< ValueType > other) const inline noexcept
Definition at line 196 of file Range.h.
References beast::Range< ValueType >::end, and beast::Range< ValueType >::start.
 { return start != other.start || end != other.end; }
template<typename ValueType > Range beast::Range< ValueType >::operator+ (const ValueType amountToAdd) const inline noexcept
Returns a range that is equal to this one with an amount added to its start and end.
Definition at line 183 of file Range.h.
References beast::Range< ValueType >::end, beast::Range< ValueType >::Range(), and beast::Range< ValueType >::start.
     {
         return Range (start + amountToAdd, end + amountToAdd);
     }
template<typename ValueType > Range beast::Range< ValueType >::operator+= (const ValueType amountToAdd) inline noexcept
Adds an amount to the start and end of the range.
Definition at line 165 of file Range.h.
References beast::Range< ValueType >::end, and beast::Range< ValueType >::start.
     {
         start += amountToAdd;
         end += amountToAdd;
         return *this;
     }
template<typename ValueType > Range beast::Range< ValueType >::operator- (const ValueType amountToSubtract) const inline noexcept
Returns a range that is equal to this one with the specified amount subtracted from its start and end.
Definition at line 190 of file Range.h.
References beast::Range< ValueType >::end, beast::Range< ValueType >::Range(), and beast::Range< ValueType >::start.
     {
         return Range (start - amountToSubtract, end - amountToSubtract);
     }
template<typename ValueType > Range beast::Range< ValueType >::operator-= (const ValueType amountToSubtract) inline noexcept
Subtracts an amount from the start and end of the range.
Definition at line 173 of file Range.h.
References beast::Range< ValueType >::end, and beast::Range< ValueType >::start.
     {
         start -= amountToSubtract;
         end -= amountToSubtract;
         return *this;
     }
template<typename ValueType > Range& beast::Range< ValueType >::operator= (Range< ValueType > other) inline noexcept
Copies another range object.
Definition at line 61 of file Range.h.
References beast::Range< ValueType >::end, and beast::Range< ValueType >::start.
     {
         start = other.start;
         end = other.end;
         return *this;
     }
template<typename ValueType > bool beast::Range< ValueType >::operator== (Range< ValueType > other) const inline noexcept
Definition at line 195 of file Range.h.
References beast::Range< ValueType >::end, and beast::Range< ValueType >::start.
 { return start == other.start && end == other.end; }
template<typename ValueType > void beast::Range< ValueType >::setEnd (const ValueType newEnd) inline noexcept
Changes the end position of the range, leaving the start unchanged. If the new end position is below the current start of the range, the start point will be pushed back to equal the new end point.
Definition at line 125 of file Range.h.
References beast::Range< ValueType >::end, and beast::Range< ValueType >::start.
     {
         end = newEnd;
         if (newEnd < start)
             start = newEnd;
     }
template<typename ValueType > void beast::Range< ValueType >::setLength (const ValueType newLength) inline noexcept
Changes the length of the range. Lengths less than zero are treated as zero.
Definition at line 150 of file Range.h.
References beast::bmax(), beast::Range< ValueType >::end, and beast::Range< ValueType >::start.
     {
         end = start + bmax (ValueType(), newLength);
     }
template<typename ValueType > void beast::Range< ValueType >::setStart (const ValueType newStart) inline noexcept
Changes the start position of the range, leaving the end position unchanged. If the new start position is higher than the current end of the range, the end point will be pushed along to equal it, leaving an empty range at the new position.
Definition at line 99 of file Range.h.
References beast::Range< ValueType >::end, and beast::Range< ValueType >::start.
     {
         start = newStart;
         if (end < newStart)
             end = newStart;
     }
template<typename ValueType > Range beast::Range< ValueType >::withEnd (const ValueType newEnd) const inline noexcept
Returns a range with the same start position as this one, but a different end. If the new end position is below the current start of the range, the start point will be pushed back to equal the new end point.
Definition at line 136 of file Range.h.
References beast::bmin(), beast::Range< ValueType >::Range(), and beast::Range< ValueType >::start.
     {
         return Range (bmin (start, newEnd), newEnd);
     }
template<typename ValueType > Range beast::Range< ValueType >::withLength (const ValueType newLength) const inline noexcept
Returns a range with the same start as this one, but a different length. Lengths less than zero are treated as zero.
Definition at line 158 of file Range.h.
References beast::Range< ValueType >::Range(), and beast::Range< ValueType >::start.
     {
         return Range (start, start + newLength);
     }
template<typename ValueType > Range beast::Range< ValueType >::withStart (const ValueType newStart) const inline noexcept
Returns a range with the same end as this one, but a different start. If the new start position is higher than the current end of the range, the end point will be pushed along to equal it, returning an empty range at the new position.
Definition at line 110 of file Range.h.
References beast::bmax(), beast::Range< ValueType >::end, and beast::Range< ValueType >::Range().
     {
         return Range (newStart, bmax (newStart, end));
     }
Member Data Documentation
template<typename ValueType > ValueType beast::Range< ValueType >::end private
Definition at line 258 of file Range.h.
Referenced by beast::Range< ValueType >::clipValue(), beast::Range< ValueType >::constrainRange(), beast::Range< ValueType >::contains(), beast::Range< ValueType >::getEnd(), beast::Range< ValueType >::getIntersectionWith(), beast::Range< ValueType >::getLength(), beast::Range< ValueType >::getUnionWith(), beast::Range< ValueType >::intersects(), beast::Range< ValueType >::isEmpty(), beast::Range< ValueType >::movedToEndAt(), beast::Range< ValueType >::movedToStartAt(), beast::Range< ValueType >::operator!=(), beast::Range< ValueType >::operator+(), beast::Range< ValueType >::operator+=(), beast::Range< ValueType >::operator-(), beast::Range< ValueType >::operator-=(), beast::Range< ValueType >::operator=(), beast::Range< ValueType >::operator==(), beast::Range< ValueType >::setEnd(), beast::Range< ValueType >::setLength(), beast::Range< ValueType >::setStart(), and beast::Range< ValueType >::withStart().
template<typename ValueType > ValueType beast::Range< ValueType >::start private
Definition at line 258 of file Range.h.
Referenced by beast::Range< ValueType >::clipValue(), beast::Range< ValueType >::constrainRange(), beast::Range< ValueType >::contains(), beast::Range< ValueType >::emptyRange(), beast::Range< ValueType >::getIntersectionWith(), beast::Range< ValueType >::getLength(), beast::Range< ValueType >::getStart(), beast::Range< ValueType >::getUnionWith(), beast::Range< ValueType >::intersects(), beast::Range< ValueType >::isEmpty(), beast::Range< ValueType >::movedToEndAt(), beast::Range< ValueType >::movedToStartAt(), beast::Range< ValueType >::operator!=(), beast::Range< ValueType >::operator+(), beast::Range< ValueType >::operator+=(), beast::Range< ValueType >::operator-(), beast::Range< ValueType >::operator-=(), beast::Range< ValueType >::operator=(), beast::Range< ValueType >::operator==(), beast::Range< ValueType >::setEnd(), beast::Range< ValueType >::setLength(), beast::Range< ValueType >::setStart(), beast::Range< ValueType >::withEnd(), and beast::Range< ValueType >::withLength().
The documentation for this class was generated from the following file:
rippled/src/beast/modules/beast_core/maths/Range.h