rippled: rocksdb::ConcurrentTest::State Struct Reference
rocksdb::ConcurrentTest::State Struct Reference
Public Member Functions
void Set (int k, intptr_t v)
intptr_t Get (int k)
State ()
Public Attributes
port::AtomicPointer generation [K]
Detailed Description
Definition at line 193 of file skiplist_test.cc.
Constructor & Destructor Documentation
rocksdb::ConcurrentTest::State::State () inline
Definition at line 202 of file skiplist_test.cc.
References rocksdb::ConcurrentTest::K, and Set().
             {
       for (unsigned int k = 0; k < K; k++) {
         Set(k, 0);
       }
     }
Member Function Documentation
intptr_t rocksdb::ConcurrentTest::State::Get (int k) inline
Definition at line 198 of file skiplist_test.cc.
References rocksdb::port::AtomicPointer::Acquire_Load(), and generation.
Referenced by rocksdb::ConcurrentTest::ReadStep(), and rocksdb::ConcurrentTest::WriteStep().
{
       return reinterpret_cast<intptr_t>(generation[k].Acquire_Load());
     }
void rocksdb::ConcurrentTest::State::Set (int k, intptr_t v) inline
Definition at line 195 of file skiplist_test.cc.
References generation, and rocksdb::port::AtomicPointer::Release_Store().
Referenced by rocksdb::ConcurrentTest::ReadStep(), State(), and rocksdb::ConcurrentTest::WriteStep().
{
       generation[k].Release_Store(reinterpret_cast<void*>(v));
     }
Member Data Documentation
port::AtomicPointer rocksdb::ConcurrentTest::State::generation[K]
Definition at line 194 of file skiplist_test.cc.
Referenced by Get(), and Set().
The documentation for this struct was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/db/skiplist_test.cc