rippled: beast::StringHolder Class Reference
beast::StringHolder Class Reference
Public Types
typedef String::CharPointerType CharPointerType
typedef
String::CharPointerType::CharType CharType
Public Member Functions
StringHolder () noexcept
Static Public Member Functions
static CharPointerType createUninitialisedBytes (const size_t numBytes)
template<class CharPointer >
static CharPointerType createFromCharPointer (const CharPointer text)
template<class CharPointer >
static CharPointerType createFromCharPointer (const CharPointer text, size_t maxChars)
template<class CharPointer >
static CharPointerType createFromCharPointer (const CharPointer start, const CharPointer end)
static CharPointerType createFromCharPointer (const CharPointerType start, const CharPointerType end)
static CharPointerType createFromFixedLength (const char *const src, const size_t numChars)
static CharPointerType getEmpty () noexcept
static void retain (const CharPointerType text) noexcept
static void release (StringHolder *const b) noexcept
static void release (const CharPointerType text) noexcept
static CharPointerType makeUnique (const CharPointerType text)
static CharPointerType makeUniqueWithByteSize (const CharPointerType text, size_t numBytes)
static size_t getAllocatedNumBytes (const CharPointerType text) noexcept
Public Attributes
Atomic< int > refCount
size_t allocatedNumBytes
CharType text [1]
Static Public Attributes
static StringHolder empty
Private Member Functions
void compileTimeChecks ()
Static Private Member Functions
static StringHolder * bufferFromText (const CharPointerType text) noexcept
Detailed Description
Definition at line 58 of file String.cpp.
Member Typedef Documentation
typedef String::CharPointerType beast::StringHolder::CharPointerType
Definition at line 67 of file String.cpp.
typedef String::CharPointerType::CharType beast::StringHolder::CharType
Definition at line 68 of file String.cpp.
Constructor & Destructor Documentation
beast::StringHolder::StringHolder () inline noexcept
Definition at line 61 of file String.cpp.
Referenced by createUninitialisedBytes().
         : refCount (0x3fffffff), allocatedNumBytes (sizeof (*text))
     {
         text[0] = 0;
     }
Member Function Documentation
static StringHolder* beast::StringHolder::bufferFromText (const CharPointerType text) inline static private noexcept
Definition at line 222 of file String.cpp.
References text.
Referenced by getAllocatedNumBytes(), makeUnique(), makeUniqueWithByteSize(), release(), and retain().
     {
         // (Can't use offsetof() here because of warnings about this not being a POD)
         return reinterpret_cast <StringHolder*> (reinterpret_cast <char*> (text.getAddress())
                     - (reinterpret_cast <size_t> (reinterpret_cast <StringHolder*> (1)->text) - 1));
     }
void beast::StringHolder::compileTimeChecks () inline private
Definition at line 229 of file String.cpp.
References static_bassert.
     {
         // Let me know if any of these assertions fail on your system!
        #if BEAST_NATIVE_WCHAR_IS_UTF8
         static_bassert (sizeof (wchar_t) == 1);
        #elif BEAST_NATIVE_WCHAR_IS_UTF16
         static_bassert (sizeof (wchar_t) == 2);
        #elif BEAST_NATIVE_WCHAR_IS_UTF32
         static_bassert (sizeof (wchar_t) == 4);
        #else
         #error "native wchar_t size is unknown"
        #endif
     }
template<class CharPointer > static CharPointerType beast::StringHolder::createFromCharPointer (const CharPointer text) inline static
Definition at line 80 of file String.cpp.
References createUninitialisedBytes(), beast::CharPointer_UTF8::getBytesRequiredFor(), getEmpty(), and beast::CharPointer_UTF8::writeAll().
     {
         if (text.getAddress() == nullptr || text.isEmpty())
             return getEmpty();
         CharPointer t (text);
         size_t bytesNeeded = sizeof (CharType);
         while (! t.isEmpty())
             bytesNeeded += CharPointerType::getBytesRequiredFor (t.getAndAdvance());
         const CharPointerType dest (createUninitialisedBytes (bytesNeeded));
         CharPointerType (dest).writeAll (text);
         return dest;
     }
template<class CharPointer > static CharPointerType beast::StringHolder::createFromCharPointer (const CharPointer text, size_t maxChars) inline static
Definition at line 97 of file String.cpp.
References createUninitialisedBytes(), beast::CharPointer_UTF8::getBytesRequiredFor(), getEmpty(), and beast::CharPointer_UTF8::writeWithCharLimit().
     {
         if (text.getAddress() == nullptr || text.isEmpty() || maxChars == 0)
             return getEmpty();
         CharPointer end (text);
         size_t numChars = 0;
         size_t bytesNeeded = sizeof (CharType);
         while (numChars < maxChars && ! end.isEmpty())
         {
             bytesNeeded += CharPointerType::getBytesRequiredFor (end.getAndAdvance());
             ++numChars;
         }
         const CharPointerType dest (createUninitialisedBytes (bytesNeeded));
         CharPointerType (dest).writeWithCharLimit (text, (int) numChars + 1);
         return dest;
     }
template<class CharPointer > static CharPointerType beast::StringHolder::createFromCharPointer (const CharPointer start, const CharPointer end) inline static
Definition at line 118 of file String.cpp.
References createUninitialisedBytes(), beast::CharPointer_UTF8::getBytesRequiredFor(), getEmpty(), and beast::CharPointer_UTF8::writeWithCharLimit().
     {
         if (start.getAddress() == nullptr || start.isEmpty())
             return getEmpty();
         CharPointer e (start);
         int numChars = 0;
         size_t bytesNeeded = sizeof (CharType);
         while (e < end && ! e.isEmpty())
         {
             bytesNeeded += CharPointerType::getBytesRequiredFor (e.getAndAdvance());
             ++numChars;
         }
         const CharPointerType dest (createUninitialisedBytes (bytesNeeded));
         CharPointerType (dest).writeWithCharLimit (start, numChars + 1);
         return dest;
     }
static CharPointerType beast::StringHolder::createFromCharPointer (const CharPointerType start, const CharPointerType end) inline static
Definition at line 138 of file String.cpp.
References createUninitialisedBytes(), beast::CharPointer_UTF8::getAddress(), getEmpty(), and beast::CharPointer_UTF8::isEmpty().
     {
         if (start.getAddress() == nullptr || start.isEmpty())
             return getEmpty();
         const size_t numBytes = (size_t) (reinterpret_cast<const char*> (end.getAddress())
                                            - reinterpret_cast<const char*> (start.getAddress()));
         const CharPointerType dest (createUninitialisedBytes (numBytes + sizeof (CharType)));
         memcpy (dest.getAddress(), start, numBytes);
         dest.getAddress()[numBytes / sizeof (CharType)] = 0;
         return dest;
     }
static CharPointerType beast::StringHolder::createFromFixedLength (const char *const src, const size_t numChars) inline static
Definition at line 151 of file String.cpp.
References createUninitialisedBytes(), and beast::CharPointer_UTF8::writeWithCharLimit().
Referenced by beast::NumberToStringConverters::createFromFixedLength().
     {
         const CharPointerType dest (createUninitialisedBytes (numChars * sizeof (CharType) + sizeof (CharType)));
         CharPointerType (dest).writeWithCharLimit (CharPointer_UTF8 (src), (int) (numChars + 1));
         return dest;
     }
static CharPointerType beast::StringHolder::createUninitialisedBytes (const size_t numBytes) inline static
Definition at line 71 of file String.cpp.
References allocatedNumBytes, refCount, StringHolder(), text, and beast::Atomic< Type >::value.
Referenced by createFromCharPointer(), createFromFixedLength(), makeUnique(), and makeUniqueWithByteSize().
     {
         StringHolder* const s = reinterpret_cast <StringHolder*> (new char [sizeof (StringHolder) - sizeof (CharType) + numBytes]);
         s->refCount.value = 0;
         s->allocatedNumBytes = numBytes;
         return CharPointerType (s->text);
     }
static size_t beast::StringHolder::getAllocatedNumBytes (const CharPointerType text) inline static noexcept
Definition at line 209 of file String.cpp.
References allocatedNumBytes, bufferFromText(), and text.
     {
         return bufferFromText (text)->allocatedNumBytes;
     }
static CharPointerType beast::StringHolder::getEmpty () inline static noexcept
Definition at line 158 of file String.cpp.
References empty, and text.
Referenced by createFromCharPointer().
     {
         return CharPointerType (empty.text);
     }
static CharPointerType beast::StringHolder::makeUnique (const CharPointerType text) inline static
Definition at line 181 of file String.cpp.
References allocatedNumBytes, bufferFromText(), createUninitialisedBytes(), beast::Atomic< Type >::get(), beast::CharPointer_UTF8::getAddress(), refCount, and release().
     {
         StringHolder* const b = bufferFromText (text);
         if (b->refCount.get() <= 0)
             return text;
         CharPointerType newText (createUninitialisedBytes (b->allocatedNumBytes));
         memcpy (newText.getAddress(), text.getAddress(), b->allocatedNumBytes);
         release (b);
         return newText;
     }
static CharPointerType beast::StringHolder::makeUniqueWithByteSize (const CharPointerType text, size_t numBytes) inline static
Definition at line 195 of file String.cpp.
References allocatedNumBytes, beast::bmax(), bufferFromText(), createUninitialisedBytes(), beast::Atomic< Type >::get(), beast::CharPointer_UTF8::getAddress(), refCount, and release().
Referenced by beast::String::operator+=(), and beast::String::preallocateBytes().
     {
         StringHolder* const b = bufferFromText (text);
         if (b->refCount.get() <= 0 && b->allocatedNumBytes >= numBytes)
             return text;
         CharPointerType newText (createUninitialisedBytes (bmax (b->allocatedNumBytes, numBytes)));
         memcpy (newText.getAddress(), text.getAddress(), b->allocatedNumBytes);
         release (b);
         return newText;
     }
static void beast::StringHolder::release (StringHolder *const b) inline static noexcept
Definition at line 169 of file String.cpp.
References empty.
Referenced by makeUnique(), makeUniqueWithByteSize(), beast::String::operator=(), release(), and beast::String::~String().
     {
         if (--(b->refCount) == -1 && b != &empty)
             delete[] reinterpret_cast <char*> (b);
     }
static void beast::StringHolder::release (const CharPointerType text) inline static noexcept
Definition at line 175 of file String.cpp.
References bufferFromText(), release(), and text.
     {
         release (bufferFromText (text));
     }
static void beast::StringHolder::retain (const CharPointerType text) inline static noexcept
Definition at line 164 of file String.cpp.
References bufferFromText(), refCount, and text.
Referenced by beast::String::operator=(), and beast::String::String().
     {
         ++(bufferFromText (text)->refCount);
     }
Member Data Documentation
size_t beast::StringHolder::allocatedNumBytes
Definition at line 216 of file String.cpp.
Referenced by createUninitialisedBytes(), getAllocatedNumBytes(), makeUnique(), and makeUniqueWithByteSize().
StringHolder beast::StringHolder::empty static
Definition at line 219 of file String.cpp.
Referenced by getEmpty(), and release().
Atomic<int> beast::StringHolder::refCount
Definition at line 215 of file String.cpp.
Referenced by createUninitialisedBytes(), makeUnique(), makeUniqueWithByteSize(), and retain().
CharType beast::StringHolder::text[1]
Definition at line 217 of file String.cpp.
Referenced by bufferFromText(), createUninitialisedBytes(), getAllocatedNumBytes(), getEmpty(), release(), and retain().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/strings/impl/String.cpp