rippled: beast::sqdb::statement Class Reference
beast::sqdb::statement Class Reference
#include <statement.h>
Public Member Functions
statement (session &s)
statement (detail::prepare_temp_type const &prep)
~statement ()
statement (statement const &o)
void operator= (statement const &o)
void exchange (detail::into_type_ptr const &i)
void exchange (detail::use_type_ptr const &u)
void prepare (std::string const &query, bool bRepeatable=true)
Error execute ()
bool execute_and_fetch (Error &error)
bool fetch (Error &error)
bool got_data () const
rowid last_insert_rowid ()
Private Member Functions
void clean_up ()
Private Attributes
std::shared_ptr
< detail::statement_imp > m_imp
Friends
class detail::ref_counted_statement
Detailed Description
Definition at line 72 of file statement.h.
Constructor & Destructor Documentation
beast::sqdb::statement::statement (session & s)
Definition at line 63 of file statement.cpp.
     : m_imp(new detail::statement_imp(s))
 {
 }
beast::sqdb::statement::statement (detail::prepare_temp_type const & prep)
Definition at line 68 of file statement.cpp.
     : m_imp(new detail::statement_imp(prep))
 {
 }
beast::sqdb::statement::~statement ()
Definition at line 73 of file statement.cpp.
 {
 }
beast::sqdb::statement::statement (statement const & o)
Definition at line 77 of file statement.cpp.
     : m_imp(o.m_imp)
 {
 }
Member Function Documentation
void beast::sqdb::statement::clean_up () private
Definition at line 134 of file statement.cpp.
References m_imp.
Referenced by beast::sqdb::detail::ref_counted_statement::final_action().
 {
     m_imp->clean_up();
 }
void beast::sqdb::statement::exchange (detail::into_type_ptr const & i)
Definition at line 87 of file statement.cpp.
References m_imp.
Referenced by beast::sqdb::detail::ref_counted_statement::exchange().
 {
     m_imp->exchange(i);
 }
void beast::sqdb::statement::exchange (detail::use_type_ptr const & u)
Definition at line 92 of file statement.cpp.
References m_imp.
 {
     m_imp->exchange(u);
 }
Error beast::sqdb::statement::execute ()
Definition at line 102 of file statement.cpp.
References m_imp.
 {
     return m_imp->execute();
 }
bool beast::sqdb::statement::execute_and_fetch (Error & error)
Definition at line 107 of file statement.cpp.
References fetch(), and m_imp.
Referenced by beast::sqdb::detail::ref_counted_statement::final_action(), ripple::Validators::StoreSqdb::insert(), ripple::PeerFinder::StoreSqdb::load(), ripple::PeerFinder::StoreSqdb::save(), ripple::Validators::StoreSqdb::select(), ripple::Validators::StoreSqdb::selectList(), ripple::Validators::StoreSqdb::update(), and ripple::PeerFinder::StoreSqdb::update().
 {
     bool gotData = false;
     error = m_imp->execute();
     if (!error)
         gotData = fetch(error);
     return gotData;
 }
bool beast::sqdb::statement::fetch (Error & error)
Definition at line 119 of file statement.cpp.
References m_imp.
Referenced by execute_and_fetch(), ripple::PeerFinder::StoreSqdb::load(), ripple::Validators::StoreSqdb::selectList(), and ripple::PeerFinder::StoreSqdb::update().
 {
     return m_imp->fetch(error);
 }
bool beast::sqdb::statement::got_data () const
Definition at line 124 of file statement.cpp.
References m_imp.
 {
     return m_imp->got_data();
 }
rowid beast::sqdb::statement::last_insert_rowid ()
Definition at line 129 of file statement.cpp.
References m_imp.
 {
     return m_imp->last_insert_rowid();
 }
void beast::sqdb::statement::operator= (statement const & o)
Definition at line 82 of file statement.cpp.
References m_imp.
 {
     m_imp = o.m_imp;
 }
void beast::sqdb::statement::prepare (std::string const & query, bool bRepeatable = true)
Definition at line 97 of file statement.cpp.
References m_imp.
Referenced by beast::sqdb::detail::ref_counted_statement::final_action().
 {
     m_imp->prepare(query, bRepeatable);
 }
Friends And Related Function Documentation
friend class detail::ref_counted_statement friend
Definition at line 95 of file statement.h.
Member Data Documentation
std::shared_ptr<detail::statement_imp> beast::sqdb::statement::m_imp private
Definition at line 100 of file statement.h.
Referenced by clean_up(), exchange(), execute(), execute_and_fetch(), fetch(), got_data(), last_insert_rowid(), operator=(), and prepare().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_sqdb/api/statement.h
rippled/src/beast/modules/beast_sqdb/source/statement.cpp