rippled: beast::asio::TestPeerLogic Class Reference
beast::asio::TestPeerLogic Class Reference abstract
#include <TestPeerLogic.h>
Public Types
typedef boost::system::error_code error_code
Public Member Functions
TestPeerLogic (abstract_socket &socket)
error_code & error () noexcept
error_code const & error () const noexcept
error_code const & error (error_code const &ec) noexcept
abstract_socket & socket () noexcept
virtual PeerRole get_role () const noexcept=0
virtual Model get_model () const noexcept=0
virtual void on_connect ()
virtual void on_connect_async (error_code const &)
virtual void finished ()
Static Public Member Functions
static void pure_virtual ()
Static Public Member Functions inherited from beast::asio::TestPeerBasics
static
boost::asio::ssl::stream_base::handshake_type to_handshake_type (PeerRole const &role)
static
boost::system::error_category
const & test_category () noexcept
static boost::system::error_code make_error (errc::errc_t ev) noexcept
static boost::system::error_code make_error (errc::errc_t ev, boost::system::error_code &ec) noexcept
static bool success (boost::system::error_code const &ec, bool eofIsOkay=false) noexcept
static bool failure (boost::system::error_code const &ec, bool eofIsOkay=false) noexcept
static bool expected (bool condition, boost::system::error_code &ec) noexcept
static bool unexpected (bool condition, boost::system::error_code &ec) noexcept
static bool aborted (boost::system::error_code const &ec) noexcept
static void breakpoint (boost::system::error_code const &ec)
static void breakpoint (char const *const message)
Private Attributes
error_code m_ec
abstract_socket * m_socket
Detailed Description
Interface for implementing the logic part of a peer test.
Definition at line 27 of file TestPeerLogic.h.
Member Typedef Documentation
typedef boost::system::error_code beast::asio::TestPeerLogic::error_code
Definition at line 30 of file TestPeerLogic.h.
Constructor & Destructor Documentation
beast::asio::TestPeerLogic::TestPeerLogic (abstract_socket & socket) explicit
Definition at line 23 of file TestPeerLogic.cpp.
     : m_socket (&socket)
 {
 }
Member Function Documentation
TestPeerLogic::error_code & beast::asio::TestPeerLogic::error () noexcept
Definition at line 28 of file TestPeerLogic.cpp.
References m_ec.
Referenced by beast::asio::TestPeerLogicSyncClient::on_connect(), beast::asio::TestPeerLogicSyncServer::on_connect(), beast::asio::TestPeerLogicAsyncServer::on_connect_async(), beast::asio::TestPeerLogicAsyncClient::on_connect_async(), beast::asio::TestPeerLogicAsyncClient::on_handshake(), beast::asio::TestPeerLogicAsyncServer::on_handshake(), beast::asio::TestPeerLogicProxyClient::on_pre_handshake(), beast::asio::TestPeerLogicAsyncServer::on_read(), beast::asio::TestPeerLogicAsyncClient::on_read(), beast::asio::TestPeerLogicAsyncClient::on_read_final(), beast::asio::TestPeerLogicAsyncServer::on_shutdown(), beast::asio::TestPeerLogicAsyncClient::on_shutdown(), beast::asio::TestPeerLogicAsyncClient::on_write(), and beast::asio::TestPeerLogicAsyncServer::on_write().
 {
     return m_ec;
 }
TestPeerLogic::error_code const & beast::asio::TestPeerLogic::error () const noexcept
Definition at line 33 of file TestPeerLogic.cpp.
References m_ec.
 {
     return m_ec;
 }
TestPeerLogic::error_code const & beast::asio::TestPeerLogic::error (error_code const & ec) noexcept
Definition at line 38 of file TestPeerLogic.cpp.
 {
     return m_ec = ec;
 }
void beast::asio::TestPeerLogic::finished () virtual
Definition at line 58 of file TestPeerLogic.cpp.
References pure_virtual().
Referenced by beast::asio::TestPeerLogicAsyncClient::on_connect_async(), beast::asio::TestPeerLogicAsyncServer::on_connect_async(), beast::asio::TestPeerLogicAsyncClient::on_handshake(), beast::asio::TestPeerLogicAsyncServer::on_handshake(), beast::asio::TestPeerLogicAsyncServer::on_read(), beast::asio::TestPeerLogicAsyncClient::on_read(), beast::asio::TestPeerLogicAsyncClient::on_read_final(), beast::asio::TestPeerLogicAsyncServer::on_shutdown(), beast::asio::TestPeerLogicAsyncClient::on_shutdown(), beast::asio::TestPeerLogicAsyncClient::on_write(), and beast::asio::TestPeerLogicAsyncServer::on_write().
 {
     pure_virtual ();
 }
virtual Model beast::asio::TestPeerLogic::get_model () const pure virtual noexcept
Implemented in beast::asio::TestPeerLogicAsyncClient, beast::asio::TestPeerLogicAsyncServer, beast::asio::TestPeerLogicSyncClient, and beast::asio::TestPeerLogicSyncServer.
virtual PeerRole beast::asio::TestPeerLogic::get_role () const pure virtual noexcept
Implemented in beast::asio::TestPeerLogicAsyncClient, beast::asio::TestPeerLogicAsyncServer, beast::asio::TestPeerLogicSyncClient, and beast::asio::TestPeerLogicSyncServer.
void beast::asio::TestPeerLogic::on_connect () virtual
Reimplemented in beast::asio::TestPeerLogicSyncClient, and beast::asio::TestPeerLogicSyncServer.
Definition at line 48 of file TestPeerLogic.cpp.
References pure_virtual().
 {
     pure_virtual ();
 }
void beast::asio::TestPeerLogic::on_connect_async (error_code const &) virtual
Reimplemented in beast::asio::TestPeerLogicAsyncClient, and beast::asio::TestPeerLogicAsyncServer.
Definition at line 53 of file TestPeerLogic.cpp.
References pure_virtual().
 {
     pure_virtual ();
 }
void beast::asio::TestPeerLogic::pure_virtual () static
Definition at line 63 of file TestPeerLogic.cpp.
Referenced by finished(), on_connect(), and on_connect_async().
 {
     fatal_error ("A TestPeerLogic function was called incorrectly");
 }
abstract_socket & beast::asio::TestPeerLogic::socket () noexcept
Definition at line 43 of file TestPeerLogic.cpp.
References m_socket.
Referenced by beast::asio::TestPeerLogicSyncClient::on_connect(), beast::asio::TestPeerLogicSyncServer::on_connect(), beast::asio::TestPeerLogicAsyncServer::on_connect_async(), beast::asio::TestPeerLogicAsyncClient::on_connect_async(), beast::asio::TestPeerLogicAsyncClient::on_handshake(), beast::asio::TestPeerLogicAsyncServer::on_handshake(), beast::asio::TestPeerLogicProxyClient::on_pre_handshake(), beast::asio::TestPeerLogicAsyncServer::on_read(), beast::asio::TestPeerLogicAsyncClient::on_read(), beast::asio::TestPeerLogicAsyncClient::on_read_final(), beast::asio::TestPeerLogicAsyncServer::on_shutdown(), beast::asio::TestPeerLogicAsyncClient::on_shutdown(), beast::asio::TestPeerLogicAsyncClient::on_write(), and beast::asio::TestPeerLogicAsyncServer::on_write().
 {
     return *m_socket;
 }
Member Data Documentation
error_code beast::asio::TestPeerLogic::m_ec private
Definition at line 55 of file TestPeerLogic.h.
Referenced by error().
abstract_socket* beast::asio::TestPeerLogic::m_socket private
Definition at line 56 of file TestPeerLogic.h.
Referenced by socket().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_asio/tests/TestPeerLogic.h
rippled/src/beast/modules/beast_asio/tests/TestPeerLogic.cpp