rippled: ripple::Resource::Consumer Class Reference
ripple::Resource::Consumer Class Reference
#include <Consumer.h>
Public Member Functions
Consumer ()
~Consumer ()
Consumer (Consumer const &other)
Consumer & operator= (Consumer const &other)
std::string to_string () const
bool admin () const
void elevate (std::string const &name)
Disposition disposition () const
Disposition charge (Charge const &fee)
bool warn ()
bool disconnect ()
int balance ()
Entry & entry ()
Private Member Functions
Consumer (Logic &logic, Entry &entry)
Private Attributes
Logic * m_logic
Entry * m_entry
Friends
class Logic
Detailed Description
An endpoint that consumes resources.
Definition at line 32 of file Consumer.h.
Constructor & Destructor Documentation
ripple::Resource::Consumer::Consumer (Logic & logic, Entry & entry) private
Definition at line 23 of file Consumer.cpp.
     : m_logic (&logic)
     , m_entry (&entry)
 {
 }
ripple::Resource::Consumer::Consumer ()
Definition at line 29 of file Consumer.cpp.
     : m_logic (nullptr)
     , m_entry (nullptr)
 {
 }
ripple::Resource::Consumer::~Consumer ()
Definition at line 49 of file Consumer.cpp.
References m_entry, m_logic, and ripple::Resource::Logic::release().
 {
     if (m_logic != nullptr)
     {
         if (m_entry != nullptr)
             m_logic->release (*m_entry);
     }
 }
ripple::Resource::Consumer::Consumer (Consumer const & other)
Definition at line 35 of file Consumer.cpp.
References ripple::Resource::Logic::acquire(), m_entry, and m_logic.
     : m_logic (other.m_logic)
     , m_entry (nullptr)
 {
     if (m_logic != nullptr)
     {
         if (other.m_entry != nullptr)
         {
             m_entry = other.m_entry;
             m_logic->acquire (*m_entry);
         }
     }
 }
Member Function Documentation
bool ripple::Resource::Consumer::admin () const
Returns true if this is a privileged endpoint.
Definition at line 88 of file Consumer.cpp.
References ripple::Resource::Entry::admin(), and m_entry.
 {
     if (m_entry != nullptr)
         return m_entry->admin();
     return false;
 }
int ripple::Resource::Consumer::balance ()
Returns the credit balance representing consumption.
Definition at line 125 of file Consumer.cpp.
References ripple::Resource::Logic::balance(), bassert, m_entry, and m_logic.
 {
     bassert (m_entry != nullptr);
     return m_logic->balance (*m_entry);
 }
Disposition ripple::Resource::Consumer::charge (Charge const & fee)
Apply a load charge to the consumer.
Definition at line 107 of file Consumer.cpp.
References bassert, ripple::Resource::Logic::charge(), m_entry, and m_logic.
Referenced by ripple::PeerImp::charge(), ripple::WSConnection::invokeCommand(), ripple::RPCServerHandler::processRequest(), and ripple::RPCHTTPServerImp::processRequest().
 {
     bassert (m_entry != nullptr);
     return m_logic->charge (*m_entry, what);
 }
bool ripple::Resource::Consumer::disconnect ()
Returns true if the consumer should be disconnected.
Definition at line 119 of file Consumer.cpp.
References bassert, ripple::Resource::Logic::disconnect(), m_entry, and m_logic.
Referenced by ripple::PeerImp::charge(), ripple::PeerImp::handleStart(), ripple::RPCServerHandler::processRequest(), and ripple::RPCHTTPServerImp::processRequest().
 {
     bassert (m_entry != nullptr);
     return m_logic->disconnect (*m_entry);
 }
Disposition ripple::Resource::Consumer::disposition () const
Returns the current disposition of this consumer. This should be checked upon creation to determine if the consumer should be disconnected immediately.
Definition at line 102 of file Consumer.cpp.
References ripple::Resource::ok.
 {
     return ok;
 }
void ripple::Resource::Consumer::elevate (std::string const & name)
Raise the Consumer's privilege level to a Named endpoint. The reference to the original endpoint descriptor is released.
Definition at line 96 of file Consumer.cpp.
References bassert, ripple::Resource::Logic::elevateToAdminEndpoint(), m_entry, and m_logic.
 {
     bassert (m_entry != nullptr);
     m_entry = &m_logic->elevateToAdminEndpoint (*m_entry, name);
 }
Entry & ripple::Resource::Consumer::entry ()
Definition at line 131 of file Consumer.cpp.
References bassert, and m_entry.
Referenced by ripple::Resource::Logic::importConsumers().
 {
     bassert (m_entry != nullptr);
     return *m_entry;
 }
Consumer & ripple::Resource::Consumer::operator= (Consumer const & other)
Definition at line 58 of file Consumer.cpp.
References ripple::Resource::Logic::acquire(), m_entry, m_logic, and ripple::Resource::Logic::release().
 {
     // remove old ref
     if (m_logic != nullptr)
     {
         if (m_entry != nullptr)
             m_logic->release (*m_entry);
     }
     m_logic = other.m_logic;
     m_entry = other.m_entry;
     // add new ref
     if (m_logic != nullptr)
     {
         if (m_entry != nullptr)
             m_logic->acquire (*m_entry);
     }
     return *this;
 }
std::string ripple::Resource::Consumer::to_string () const
Return a human readable string uniquely identifying this consumer.
Definition at line 80 of file Consumer.cpp.
References m_entry, m_logic, and ripple::Resource::Entry::to_string().
Referenced by ripple::Resource::operator<<().
 {
     if (m_logic == nullptr)
         return "(none)";
     return m_entry->to_string();
 }
bool ripple::Resource::Consumer::warn ()
Returns true if the consumer should be warned. This consumes the warning.
Definition at line 113 of file Consumer.cpp.
References bassert, m_entry, m_logic, and ripple::Resource::Logic::warn().
 {
     bassert (m_entry != nullptr);
     return m_logic->warn (*m_entry);
 }
Friends And Related Function Documentation
friend class Logic friend
Definition at line 35 of file Consumer.h.
Member Data Documentation
Entry* ripple::Resource::Consumer::m_entry private
Definition at line 80 of file Consumer.h.
Referenced by admin(), balance(), charge(), Consumer(), disconnect(), elevate(), entry(), operator=(), to_string(), warn(), and ~Consumer().
Logic* ripple::Resource::Consumer::m_logic private
Definition at line 79 of file Consumer.h.
Referenced by balance(), charge(), Consumer(), disconnect(), elevate(), operator=(), to_string(), warn(), and ~Consumer().
The documentation for this class was generated from the following files:
rippled/src/ripple/resource/api/Consumer.h
rippled/src/ripple/resource/impl/Consumer.cpp