rippled: ripple::Transactor Class Reference
ripple::Transactor Class Reference abstract
#include <Transactor.h>
Public Member Functions
TER apply ()
Static Public Member Functions
static std::unique_ptr
< Transactor > makeTransactor (SerializedTransaction const &txn, TransactionEngineParams params, TransactionEngine *engine)
Protected Member Functions
virtual TER preCheck ()
virtual TER checkSeq ()
virtual TER payFee ()
void calculateFee ()
virtual std::uint64_t calculateBaseFee ()
virtual TER checkSig ()
virtual TER doApply ()=0
Transactor (const SerializedTransaction &txn, TransactionEngineParams params, TransactionEngine *engine, beast::Journal journal=beast::Journal())
virtual bool mustHaveValidAccount ()
Protected Attributes
SerializedTransaction const & mTxn
TransactionEngine * mEngine
TransactionEngineParams mParams
uint160 mTxnAccountID
STAmount mFeeDue
STAmount mPriorBalance
STAmount mSourceBalance
SLE::pointer mTxnAccount
bool mHasAuthKey
bool mSigMaster
RippleAddress mSigningPubKey
beast::Journal m_journal
Detailed Description
Definition at line 25 of file Transactor.h.
Constructor & Destructor Documentation
ripple::Transactor::Transactor (const SerializedTransaction & txn, TransactionEngineParams params, TransactionEngine * engine, beast::Journal journal = beast::Journal ()) protected
Definition at line 78 of file Transactor.cpp.
     : mTxn (txn)
     , mEngine (engine)
     , mParams (params)
     , mHasAuthKey (false)
     , mSigMaster (false)
     , m_journal (journal)
 {
 }
Member Function Documentation
TER ripple::Transactor::apply ()
Definition at line 255 of file Transactor.cpp.
References calculateFee(), checkSeq(), checkSig(), doApply(), ripple::TransactionEngine::entryCache(), ripple::TransactionEngine::entryModify(), ripple::Ledger::getAccountRootIndex(), ripple::TransactionEngine::getLedger(), ripple::SerializedTransaction::getSourceAccount(), ripple::RippleAddress::humanAccountID(), ripple::ltACCOUNT_ROOT, m_journal, mEngine, mHasAuthKey, mPriorBalance, mSourceBalance, mTxn, mTxnAccount, mTxnAccountID, mustHaveValidAccount(), payFee(), preCheck(), ripple::terNO_ACCOUNT, ripple::tesSUCCESS, and beast::Journal::trace.
 {
     TER terResult (preCheck ());
     if (terResult != tesSUCCESS)
         return (terResult);
     // Restructure this to avoid the dependency on LedgerBase::mLock
     Ledger::ScopedLockType sl (mEngine->getLedger ()->mLock);
     mTxnAccount = mEngine->entryCache (ltACCOUNT_ROOT,
         Ledger::getAccountRootIndex (mTxnAccountID));
     calculateFee ();
     // Find source account
     // If are only forwarding, due to resource limitations, we might verifying
     // only some transactions, this would be probabilistic.
     if (!mTxnAccount)
     {
         if (mustHaveValidAccount ())
         {
             m_journal.trace <<
                 "apply: delay transaction: source account does not exist " <<
                 mTxn.getSourceAccount ().humanAccountID ();
             return terNO_ACCOUNT;
         }
     }
     else
     {
         mPriorBalance   = mTxnAccount->getFieldAmount (sfBalance);
         mSourceBalance  = mPriorBalance;
         mHasAuthKey     = mTxnAccount->isFieldPresent (sfRegularKey);
     }
     terResult = checkSeq ();
     if (terResult != tesSUCCESS) return (terResult);
     terResult = payFee ();
     if (terResult != tesSUCCESS) return (terResult);
     terResult = checkSig ();
     if (terResult != tesSUCCESS) return (terResult);
     if (mTxnAccount)
         mEngine->entryModify (mTxnAccount);
     return doApply ();
 }
std::uint64_t ripple::Transactor::calculateBaseFee () protected virtual
Reimplemented in ripple::RegularKeySetTransactor.
Definition at line 98 of file Transactor.cpp.
References ripple::Config::FEE_DEFAULT, and ripple::getConfig().
Referenced by ripple::RegularKeySetTransactor::calculateBaseFee(), and calculateFee().
 {
     return getConfig ().FEE_DEFAULT;
 }
void ripple::Transactor::calculateFee () protected
Definition at line 92 of file Transactor.cpp.
References calculateBaseFee(), ripple::TransactionEngine::getLedger(), ripple::is_bit_set(), mEngine, mFeeDue, mParams, and ripple::tapADMIN.
Referenced by apply().
 {
     mFeeDue = STAmount (mEngine->getLedger ()->scaleFeeLoad (
         calculateBaseFee (), is_bit_set (mParams, tapADMIN)));
 }
TER ripple::Transactor::checkSeq () protected virtual
Reimplemented in ripple::ChangeTransactor.
Definition at line 172 of file Transactor.cpp.
References ripple::STObject::getFieldH256(), ripple::STObject::getFieldU32(), ripple::TransactionEngine::getLedger(), ripple::SerializedTransaction::getSequence(), ripple::SerializedTransaction::getTransactionID(), ripple::STObject::isFieldPresent(), m_journal, mEngine, mTxn, mTxnAccount, ripple::tefALREADY, ripple::tefMAX_LEDGER, ripple::tefPAST_SEQ, ripple::tefWRONG_PRIOR, ripple::terPRE_SEQ, ripple::tesSUCCESS, beast::Journal::trace, and beast::Journal::warning.
Referenced by apply().
 {
     std::uint32_t t_seq = mTxn.getSequence ();
     std::uint32_t a_seq = mTxnAccount->getFieldU32 (sfSequence);
     m_journal.trace << "Aseq=" << a_seq << ", Tseq=" << t_seq;
     if (t_seq != a_seq)
     {
         if (a_seq < t_seq)
         {
             m_journal.trace << "apply: transaction has future sequence number";
             return terPRE_SEQ;
         }
         else
         {
             uint256 txID = mTxn.getTransactionID ();
             if (mEngine->getLedger ()->hasTransaction (txID))
                 return tefALREADY;
         }
         m_journal.warning << "apply: transaction has past sequence number";
         return tefPAST_SEQ;
     }
     // Deprecated: Do not use
     if (mTxn.isFieldPresent (sfPreviousTxnID) &&
             (mTxnAccount->getFieldH256 (sfPreviousTxnID) != mTxn.getFieldH256 (sfPreviousTxnID)))
         return tefWRONG_PRIOR;
     if (mTxn.isFieldPresent (sfAccountTxnID) &&
             (mTxnAccount->getFieldH256 (sfAccountTxnID) != mTxn.getFieldH256 (sfAccountTxnID)))
         return tefWRONG_PRIOR;
     if (mTxn.isFieldPresent (sfLastLedgerSequence) &&
             (mEngine->getLedger()->getLedgerSeq() > mTxn.getFieldU32 (sfLastLedgerSequence)))
         return tefMAX_LEDGER;
     mTxnAccount->setFieldU32 (sfSequence, t_seq + 1);
     if (mTxnAccount->isFieldPresent (sfAccountTxnID))
         mTxnAccount->setFieldH256 (sfAccountTxnID, mTxn.getTransactionID ());
     return tesSUCCESS;
 }
TER ripple::Transactor::checkSig () protected virtual
Reimplemented in ripple::ChangeTransactor.
Definition at line 141 of file Transactor.cpp.
References ripple::RippleAddress::getAccountID(), ripple::lsfDisableMaster, m_journal, mHasAuthKey, mSigMaster, mSigningPubKey, mTxnAccount, mTxnAccountID, nothing, ripple::tefBAD_AUTH, ripple::tefMASTER_DISABLED, ripple::temBAD_AUTH_MASTER, ripple::tesSUCCESS, and beast::Journal::trace.
Referenced by apply().
 {
     // Consistency: Check signature
     // Verify the transaction's signing public key is the key authorized for signing.
     if (mSigningPubKey.getAccountID () == mTxnAccountID)
     {
         // Authorized to continue.
         mSigMaster = true;
         if (mTxnAccount->isFlag(lsfDisableMaster))
         return tefMASTER_DISABLED;
     }
     else if (mHasAuthKey && mSigningPubKey.getAccountID () == mTxnAccount->getFieldAccount160 (sfRegularKey))
     {
         // Authorized to continue.
         nothing ();
     }
     else if (mHasAuthKey)
     {
         m_journal.trace << "applyTransaction: Delay: Not authorized to use account.";
         return tefBAD_AUTH;
     }
     else
     {
         m_journal.trace << "applyTransaction: Invalid: Not authorized to use account.";
         return temBAD_AUTH_MASTER;
     }
     return tesSUCCESS;
 }
virtual TER ripple::Transactor::doApply () protected pure virtual
Implemented in ripple::OfferCreateTransactor, ripple::PaymentTransactor, ripple::RegularKeySetTransactor, ripple::AccountSetTransactor, ripple::OfferCancelTransactor, ripple::ChangeTransactor, ripple::TrustSetTransactor, and ripple::WalletAddTransactor.
Referenced by apply().
std::unique_ptr< Transactor > ripple::Transactor::makeTransactor (SerializedTransaction const & txn, TransactionEngineParams params, TransactionEngine * engine) static
Definition at line 32 of file Transactor.cpp.
References ripple::SerializedTransaction::getTxnType(), ripple::ttACCOUNT_SET, ripple::ttFEATURE, ripple::ttFEE, ripple::ttOFFER_CANCEL, ripple::ttOFFER_CREATE, ripple::ttPAYMENT, ripple::ttREGULAR_KEY_SET, ripple::ttTRUST_SET, and ripple::ttWALLET_ADD.
Referenced by ripple::TransactionEngine::applyTransaction().
 {
     switch (txn.getTxnType ())
     {
     case ttPAYMENT:
         return std::unique_ptr<Transactor> (
             new PaymentTransactor (txn, params, engine));
     case ttACCOUNT_SET:
         return std::unique_ptr<Transactor> (
             new AccountSetTransactor (txn, params, engine));
     case ttREGULAR_KEY_SET:
         return std::unique_ptr<Transactor> (
             new RegularKeySetTransactor (txn, params, engine));
     case ttTRUST_SET:
         return std::unique_ptr<Transactor> (
             new TrustSetTransactor (txn, params, engine));
     case ttOFFER_CREATE:
         return std::unique_ptr<Transactor> (
             new OfferCreateTransactor (txn, params, engine));
     case ttOFFER_CANCEL:
         return std::unique_ptr<Transactor> (
             new OfferCancelTransactor (txn, params, engine));
     case ttWALLET_ADD:
         return std::unique_ptr<Transactor> (
             new WalletAddTransactor (txn, params, engine));
     case ttFEATURE:
     case ttFEE:
         return std::unique_ptr<Transactor> (
             new ChangeTransactor (txn, params, engine));
     default:
         return std::unique_ptr<Transactor> ();
     }
 }
virtual bool ripple::Transactor::mustHaveValidAccount () inline protected virtual
Reimplemented in ripple::ChangeTransactor.
Definition at line 69 of file Transactor.h.
Referenced by apply().
     {
         return true;
     }
TER ripple::Transactor::payFee () protected virtual
Reimplemented in ripple::ChangeTransactor.
Definition at line 103 of file Transactor.cpp.
References ripple::STAmount::getText(), ripple::SerializedTransaction::getTransactionFee(), ripple::is_bit_set(), ripple::STAmount::isLegalNet(), ripple::STAmount::isNative(), m_journal, mFeeDue, mParams, mSourceBalance, mTxn, mTxnAccount, ripple::tapOPEN_LEDGER, ripple::telINSUF_FEE_P, ripple::temBAD_AMOUNT, ripple::temBAD_FEE, ripple::terINSUF_FEE_B, ripple::tesSUCCESS, and beast::Journal::trace.
Referenced by apply().
 {
     STAmount saPaid = mTxn.getTransactionFee ();
     if (!saPaid.isLegalNet ())
         return temBAD_AMOUNT;
     // Only check fee is sufficient when the ledger is open.
     if (is_bit_set (mParams, tapOPEN_LEDGER) && saPaid < mFeeDue)
     {
         m_journal.trace << "Insufficient fee paid: " <<
             saPaid.getText () << "/" << mFeeDue.getText ();
         return telINSUF_FEE_P;
     }
     if (saPaid < zero || !saPaid.isNative ())
         return temBAD_FEE;
     if (!saPaid) return tesSUCCESS;
     // Deduct the fee, so it's not available during the transaction.
     // Will only write the account back, if the transaction succeeds.
     if (mSourceBalance < saPaid)
     {
         m_journal.trace << "Insufficient balance:" <<
             " balance=" << mSourceBalance.getText () <<
             " paid=" << saPaid.getText ();
         return terINSUF_FEE_B;
     }
     mSourceBalance -= saPaid;
     mTxnAccount->setFieldAmount (sfBalance, mSourceBalance);
     return tesSUCCESS;
 }
TER ripple::Transactor::preCheck () protected virtual
Reimplemented in ripple::ChangeTransactor.
Definition at line 222 of file Transactor.cpp.
References ripple::SerializedTransaction::checkSign(), ripple::RippleAddress::createAccountPublic(), ripple::RippleAddress::getAccountID(), ripple::SerializedTransaction::getSigningPubKey(), ripple::SerializedTransaction::getSourceAccount(), ripple::is_bit_set(), ripple::SerializedTransaction::isKnownBad(), ripple::SerializedTransaction::isKnownGood(), m_journal, mParams, mSigningPubKey, mTxn, mTxnAccountID, ripple::SerializedTransaction::setBad(), ripple::SerializedTransaction::setGood(), ripple::tapNO_CHECK_SIGN, ripple::temBAD_SRC_ACCOUNT, ripple::temINVALID, ripple::tesSUCCESS, and beast::Journal::warning.
Referenced by apply().
 {
     mTxnAccountID   = mTxn.getSourceAccount ().getAccountID ();
     if (!mTxnAccountID)
     {
         m_journal.warning << "apply: bad transaction source id";
         return temBAD_SRC_ACCOUNT;
     }
     // Extract signing key
     // Transactions contain a signing key.  This allows us to trivially verify a transaction has at least been properly signed
     // without going to disk.  Each transaction also notes a source account id.  This is used to verify that the signing key is
     // associated with the account.
     // XXX This could be a lot cleaner to prevent unnecessary copying.
     mSigningPubKey  = RippleAddress::createAccountPublic (mTxn.getSigningPubKey ());
     // Consistency: really signed.
     if (!mTxn.isKnownGood ())
     {
         if (mTxn.isKnownBad () || (!is_bit_set (mParams, tapNO_CHECK_SIGN) && !mTxn.checkSign (mSigningPubKey)))
         {
             mTxn.setBad ();
             m_journal.warning << "apply: Invalid transaction (bad signature)";
             return temINVALID;
         }
         mTxn.setGood ();
     }
     return tesSUCCESS;
 }
Member Data Documentation
beast::Journal ripple::Transactor::m_journal protected
Definition at line 49 of file Transactor.h.
Referenced by apply(), ripple::ChangeTransactor::applyFee(), ripple::ChangeTransactor::checkSeq(), checkSeq(), ripple::ChangeTransactor::checkSig(), checkSig(), ripple::TrustSetTransactor::doApply(), ripple::WalletAddTransactor::doApply(), ripple::AccountSetTransactor::doApply(), ripple::OfferCancelTransactor::doApply(), ripple::PaymentTransactor::doApply(), ripple::RegularKeySetTransactor::doApply(), ripple::OfferCreateTransactor::doApply(), ripple::OfferCreateTransactor::isValidOffer(), payFee(), ripple::ChangeTransactor::payFee(), preCheck(), ripple::ChangeTransactor::preCheck(), and ripple::OfferCreateTransactor::takeOffers().
TransactionEngine* ripple::Transactor::mEngine protected
Definition at line 37 of file Transactor.h.
Referenced by apply(), ripple::ChangeTransactor::applyFeature(), ripple::ChangeTransactor::applyFee(), calculateFee(), checkSeq(), ripple::WalletAddTransactor::doApply(), ripple::TrustSetTransactor::doApply(), ripple::OfferCancelTransactor::doApply(), ripple::AccountSetTransactor::doApply(), ripple::PaymentTransactor::doApply(), ripple::OfferCreateTransactor::doApply(), ripple::OfferCreateTransactor::isValidOffer(), and ripple::OfferCreateTransactor::takeOffers().
STAmount ripple::Transactor::mFeeDue protected
Definition at line 41 of file Transactor.h.
Referenced by calculateFee(), ripple::RegularKeySetTransactor::doApply(), and payFee().
bool ripple::Transactor::mHasAuthKey protected
Definition at line 45 of file Transactor.h.
Referenced by apply(), and checkSig().
TransactionEngineParams ripple::Transactor::mParams protected
Definition at line 38 of file Transactor.h.
Referenced by calculateFee(), ripple::AccountSetTransactor::doApply(), ripple::PaymentTransactor::doApply(), ripple::OfferCreateTransactor::doApply(), payFee(), preCheck(), and ripple::ChangeTransactor::preCheck().
STAmount ripple::Transactor::mPriorBalance protected
Definition at line 42 of file Transactor.h.
Referenced by apply(), ripple::TrustSetTransactor::doApply(), ripple::PaymentTransactor::doApply(), and ripple::OfferCreateTransactor::doApply().
bool ripple::Transactor::mSigMaster protected
Definition at line 46 of file Transactor.h.
Referenced by checkSig().
RippleAddress ripple::Transactor::mSigningPubKey protected
Definition at line 47 of file Transactor.h.
Referenced by ripple::RegularKeySetTransactor::calculateBaseFee(), checkSig(), and preCheck().
STAmount ripple::Transactor::mSourceBalance protected
Definition at line 43 of file Transactor.h.
Referenced by apply(), ripple::PaymentTransactor::doApply(), and payFee().
SerializedTransaction const& ripple::Transactor::mTxn protected
Definition at line 36 of file Transactor.h.
Referenced by apply(), ripple::ChangeTransactor::applyFeature(), ripple::ChangeTransactor::applyFee(), ripple::ChangeTransactor::checkSeq(), checkSeq(), ripple::ChangeTransactor::checkSig(), ripple::TrustSetTransactor::doApply(), ripple::WalletAddTransactor::doApply(), ripple::ChangeTransactor::doApply(), ripple::OfferCancelTransactor::doApply(), ripple::AccountSetTransactor::doApply(), ripple::PaymentTransactor::doApply(), ripple::RegularKeySetTransactor::doApply(), ripple::OfferCreateTransactor::doApply(), ripple::ChangeTransactor::payFee(), payFee(), preCheck(), and ripple::ChangeTransactor::preCheck().
SLE::pointer ripple::Transactor::mTxnAccount protected
Definition at line 44 of file Transactor.h.
Referenced by apply(), ripple::RegularKeySetTransactor::calculateBaseFee(), checkSeq(), checkSig(), ripple::TrustSetTransactor::doApply(), ripple::WalletAddTransactor::doApply(), ripple::AccountSetTransactor::doApply(), ripple::OfferCancelTransactor::doApply(), ripple::PaymentTransactor::doApply(), ripple::RegularKeySetTransactor::doApply(), ripple::OfferCreateTransactor::doApply(), and payFee().
uint160 ripple::Transactor::mTxnAccountID protected
Definition at line 40 of file Transactor.h.
Referenced by apply(), ripple::RegularKeySetTransactor::calculateBaseFee(), checkSig(), ripple::TrustSetTransactor::doApply(), ripple::AccountSetTransactor::doApply(), ripple::OfferCancelTransactor::doApply(), ripple::PaymentTransactor::doApply(), ripple::OfferCreateTransactor::doApply(), preCheck(), and ripple::ChangeTransactor::preCheck().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/transactors/Transactor.h
rippled/src/ripple_app/transactors/Transactor.cpp