rippled: rocksdb::port Namespace Reference
rocksdb::port Namespace Reference
Classes
class Mutex
class CondVar
class AtomicPointer
class RWMutex
Typedefs
typedef intptr_t OnceType
Functions
void InitOnce (port::OnceType *, void(*initializer)())
bool Snappy_Compress (const char *input, size_t input_length, std::string *output)
bool Snappy_GetUncompressedLength (const char *input, size_t length, size_t *result)
bool Snappy_Uncompress (const char *input_data, size_t input_length, char *output)
bool GetHeapProfile (void(*func)(void *, const char *, int), void *arg)
static void PthreadCall (const char *label, int result)
bool Snappy_Compress (const CompressionOptions &opts, const char *input, size_t length,::std::string *output)
bool Zlib_Compress (const CompressionOptions &opts, const char *input, size_t length,::std::string *output)
char * Zlib_Uncompress (const char *input_data, size_t input_length, int *decompress_size, int windowBits=-14)
bool BZip2_Compress (const CompressionOptions &opts, const char *input, size_t length,::std::string *output)
char * BZip2_Uncompress (const char *input_data, size_t input_length, int *decompress_size)
Variables
static const bool kLittleEndian = true
static const bool kLittleEndian = PLATFORM_IS_LITTLE_ENDIAN
Typedef Documentation
typedef pthread_once_t rocksdb::port::OnceType
Definition at line 74 of file port_example.h.
Function Documentation
bool rocksdb::port::BZip2_Compress (const CompressionOptions & opts, const char * input, size_t length, ::std::string * output) inline
Definition at line 300 of file port_posix.h.
Referenced by rocksdb::BZip2CompressionSupported(), rocksdb::Benchmark::PrintWarnings(), and rocksdb::BlockBasedTableBuilder::WriteBlock().
{
 #ifdef BZIP2
   bz_stream _stream;
   memset(&_stream, 0, sizeof(bz_stream));
   // Block size 1 is 100K.
   // 0 is for silent.
   // 30 is the default workFactor
   int st = BZ2_bzCompressInit(&_stream, 1, 0, 30);
   if (st != BZ_OK) {
     return false;
   }
   // Resize output to be the plain data length.
   // This may not be big enough if the compression actually expands data.
   output->resize(length);
   // Compress the input, and put compressed data in output.
   _stream.next_in = (char *)input;
   _stream.avail_in = length;
   // Initialize the output size.
   _stream.next_out = (char *)&(*output)[0];
   _stream.avail_out = length;
   int old_sz =0, new_sz =0;
   while(_stream.next_in != nullptr && _stream.avail_in != 0) {
     int st = BZ2_bzCompress(&_stream, BZ_FINISH);
     switch (st) {
       case BZ_STREAM_END:
         break;
       case BZ_FINISH_OK:
         // No output space. Increase the output space by 20%.
         // (Should we fail the compression since it expands the size?)
         old_sz = output->size();
         new_sz = (int)(output->size() * 1.2);
         output->resize(new_sz);
         // Set more output.
         _stream.next_out = (char *)&(*output)[old_sz];
         _stream.avail_out = new_sz - old_sz;
         break;
       case BZ_SEQUENCE_ERROR:
       default:
         BZ2_bzCompressEnd(&_stream);
         return false;
     }
   }
   output->resize(output->size() - _stream.avail_out);
   BZ2_bzCompressEnd(&_stream);
   return true;
   return output;
 #endif
   return false;
 }
char* rocksdb::port::BZip2_Uncompress (const char * input_data, size_t input_length, int * decompress_size) inline
Definition at line 357 of file port_posix.h.
Referenced by rocksdb::UncompressBlockContents().
{
 #ifdef BZIP2
   bz_stream _stream;
   memset(&_stream, 0, sizeof(bz_stream));
   int st = BZ2_bzDecompressInit(&_stream, 0, 0);
   if (st != BZ_OK) {
     return nullptr;
   }
   _stream.next_in = (char *)input_data;
   _stream.avail_in = input_length;
   // Assume the decompressed data size will be 5x of compressed size.
   int output_len = input_length * 5;
   char* output = new char[output_len];
   int old_sz = output_len;
   _stream.next_out = (char *)output;
   _stream.avail_out = output_len;
   char* tmp = nullptr;
   while(_stream.next_in != nullptr && _stream.avail_in != 0) {
     int st = BZ2_bzDecompress(&_stream);
     switch (st) {
       case BZ_STREAM_END:
         break;
       case BZ_OK:
         // No output space. Increase the output space by 20%.
         old_sz = output_len;
         output_len = (int)(output_len * 1.2);
         tmp = new char[output_len];
         memcpy(tmp, output, old_sz);
         delete[] output;
         output = tmp;
         // Set more output.
         _stream.next_out = (char *)(output + old_sz);
         _stream.avail_out = output_len - old_sz;
         break;
       case Z_BUF_ERROR:
       default:
         delete[] output;
         BZ2_bzDecompressEnd(&_stream);
         return nullptr;
     }
   }
   *decompress_size = output_len - _stream.avail_out;
   BZ2_bzDecompressEnd(&_stream);
   return output;
 #endif
   return nullptr;
 }
bool rocksdb::port::GetHeapProfile (void(*)(void *, const char *, int) func, void * arg) inline
Definition at line 414 of file port_posix.h.
Referenced by rocksdb::Benchmark::HeapProfile().
{
   return false;
 }
void rocksdb::port::InitOnce (port::OnceType * , void(*)() initializer)
Definition at line 81 of file port_posix.cc.
References PthreadCall().
Referenced by rocksdb::BytewiseComparator().
{
   PthreadCall("once", pthread_once(once, initializer));
 }
static void rocksdb::port::PthreadCall (const char * label, int result) static
Definition at line 20 of file port_posix.cc.
Referenced by rocksdb::port::CondVar::CondVar(), InitOnce(), rocksdb::port::Mutex::Lock(), rocksdb::port::Mutex::Mutex(), rocksdb::port::RWMutex::ReadLock(), rocksdb::port::RWMutex::RWMutex(), rocksdb::port::CondVar::Signal(), rocksdb::port::CondVar::SignalAll(), rocksdb::port::Mutex::Unlock(), rocksdb::port::RWMutex::Unlock(), rocksdb::port::CondVar::Wait(), rocksdb::port::RWMutex::WriteLock(), rocksdb::port::CondVar::~CondVar(), rocksdb::port::Mutex::~Mutex(), and rocksdb::port::RWMutex::~RWMutex().
{
   if (result != 0) {
     fprintf(stderr, "pthread %s: %s\n", label, strerror(result));
     abort();
   }
 }
bool rocksdb::port::Snappy_Compress (const char * input, size_t input_length, std::string * output)
Referenced by rocksdb::Benchmark::PrintWarnings(), rocksdb::Benchmark::SnappyCompress(), rocksdb::SnappyCompressionSupported(), rocksdb::Benchmark::SnappyUncompress(), and rocksdb::BlockBasedTableBuilder::WriteBlock().
bool rocksdb::port::Snappy_Compress (const CompressionOptions & opts, const char * input, size_t length, ::std::string * output) inline
Definition at line 140 of file port_posix.h.
{
 #ifdef SNAPPY
   output->resize(snappy::MaxCompressedLength(length));
   size_t outlen;
   snappy::RawCompress(input, length, &(*output)[0], &outlen);
   output->resize(outlen);
   return true;
 #endif
   return false;
 }
bool rocksdb::port::Snappy_GetUncompressedLength (const char * input, size_t length, size_t * result) inline
Definition at line 153 of file port_posix.h.
Referenced by rocksdb::UncompressBlockContents().
{
 #ifdef SNAPPY
   return snappy::GetUncompressedLength(input, length, result);
 #else
   return false;
 #endif
 }
bool rocksdb::port::Snappy_Uncompress (const char * input_data, size_t input_length, char * output) inline
Definition at line 162 of file port_posix.h.
Referenced by rocksdb::Benchmark::SnappyUncompress(), and rocksdb::UncompressBlockContents().
{
 #ifdef SNAPPY
   return snappy::RawUncompress(input, length, output);
 #else
   return false;
 #endif
 }
bool rocksdb::port::Zlib_Compress (const CompressionOptions & opts, const char * input, size_t length, ::std::string * output) inline
Definition at line 171 of file port_posix.h.
References rocksdb::CompressionOptions::level, rocksdb::CompressionOptions::strategy, and rocksdb::CompressionOptions::window_bits.
Referenced by rocksdb::Benchmark::PrintWarnings(), rocksdb::BlockBasedTableBuilder::WriteBlock(), and rocksdb::ZlibCompressionSupported().
{
 #ifdef ZLIB
   // The memLevel parameter specifies how much memory should be allocated for
   // the internal compression state.
   // memLevel=1 uses minimum memory but is slow and reduces compression ratio.
   // memLevel=9 uses maximum memory for optimal speed.
   // The default value is 8. See zconf.h for more details.
   static const int memLevel = 8;
   z_stream _stream;
   memset(&_stream, 0, sizeof(z_stream));
   int st = deflateInit2(&_stream, opts.level, Z_DEFLATED, opts.window_bits,
                         memLevel, opts.strategy);
   if (st != Z_OK) {
     return false;
   }
   // Resize output to be the plain data length.
   // This may not be big enough if the compression actually expands data.
   output->resize(length);
   // Compress the input, and put compressed data in output.
   _stream.next_in = (Bytef *)input;
   _stream.avail_in = length;
   // Initialize the output size.
   _stream.avail_out = length;
   _stream.next_out = (Bytef *)&(*output)[0];
   int old_sz =0, new_sz =0, new_sz_delta =0;
   bool done = false;
   while (!done) {
     int st = deflate(&_stream, Z_FINISH);
     switch (st) {
       case Z_STREAM_END:
         done = true;
         break;
       case Z_OK:
         // No output space. Increase the output space by 20%.
         // (Should we fail the compression since it expands the size?)
         old_sz = output->size();
         new_sz_delta = (int)(output->size() * 0.2);
         new_sz = output->size() + (new_sz_delta < 10 ? 10 : new_sz_delta);
         output->resize(new_sz);
         // Set more output.
         _stream.next_out = (Bytef *)&(*output)[old_sz];
         _stream.avail_out = new_sz - old_sz;
         break;
       case Z_BUF_ERROR:
       default:
         deflateEnd(&_stream);
         return false;
     }
   }
   output->resize(output->size() - _stream.avail_out);
   deflateEnd(&_stream);
   return true;
 #endif
   return false;
 }
char* rocksdb::port::Zlib_Uncompress (const char * input_data, size_t input_length, int * decompress_size, int windowBits = -14) inline
Definition at line 233 of file port_posix.h.
Referenced by rocksdb::UncompressBlockContents().
{
 #ifdef ZLIB
   z_stream _stream;
   memset(&_stream, 0, sizeof(z_stream));
   // For raw inflate, the windowBits should be -8..-15.
   // If windowBits is bigger than zero, it will use either zlib
   // header or gzip header. Adding 32 to it will do automatic detection.
   int st = inflateInit2(&_stream,
       windowBits > 0 ? windowBits + 32 : windowBits);
   if (st != Z_OK) {
     return nullptr;
   }
   _stream.next_in = (Bytef *)input_data;
   _stream.avail_in = input_length;
   // Assume the decompressed data size will 5x of compressed size.
   int output_len = input_length * 5;
   char* output = new char[output_len];
   int old_sz = output_len;
   _stream.next_out = (Bytef *)output;
   _stream.avail_out = output_len;
   char* tmp = nullptr;
   int output_len_delta;
   bool done = false;
   //while(_stream.next_in != nullptr && _stream.avail_in != 0) {
   while (!done) {
     int st = inflate(&_stream, Z_SYNC_FLUSH);
     switch (st) {
       case Z_STREAM_END:
         done = true;
         break;
       case Z_OK:
         // No output space. Increase the output space by 20%.
         old_sz = output_len;
         output_len_delta = (int)(output_len * 0.2);
         output_len += output_len_delta < 10 ? 10 : output_len_delta;
         tmp = new char[output_len];
         memcpy(tmp, output, old_sz);
         delete[] output;
         output = tmp;
         // Set more output.
         _stream.next_out = (Bytef *)(output + old_sz);
         _stream.avail_out = output_len - old_sz;
         break;
       case Z_BUF_ERROR:
       default:
         delete[] output;
         inflateEnd(&_stream);
         return nullptr;
     }
   }
   *decompress_size = output_len - _stream.avail_out;
   inflateEnd(&_stream);
   return output;
 #endif
   return nullptr;
 }
Variable Documentation
const bool rocksdb::port::kLittleEndian = true static
Definition at line 26 of file port_example.h.
Referenced by rocksdb::DecodeFixed32(), and rocksdb::DecodeFixed64().
const bool rocksdb::port::kLittleEndian = PLATFORM_IS_LITTLE_ENDIAN static
Definition at line 83 of file port_posix.h.