rippled: ripple::Job Class Reference
ripple::Job Class Reference
#include <Job.h>
Public Types
typedef std::chrono::steady_clock clock_type
Public Member Functions
Job ()
Job (JobType type, std::uint64_t index)
Job (JobType type, std::string const &name, std::uint64_t index, LoadMonitor &lm, std::function< void(Job &)> const &job, CancelCallback cancelCallback)
JobType getType () const
CancelCallback getCancelCallback () const
clock_type::time_point const & queue_time () const
bool shouldCancel () const
void doJob ()
void rename (const std::string &n)
bool operator< (const Job &j) const
bool operator> (const Job &j) const
bool operator<= (const Job &j) const
bool operator>= (const Job &j) const
Private Attributes
CancelCallback m_cancelCallback
JobType mType
std::uint64_t mJobIndex
std::function< void(Job &)> mJob
LoadEvent::pointer m_loadEvent
std::string mName
clock_type::time_point m_queue_time
Detailed Description
Definition at line 73 of file Job.h.
Member Typedef Documentation
typedef std::chrono::steady_clock ripple::Job::clock_type
Definition at line 76 of file Job.h.
Constructor & Destructor Documentation
ripple::Job::Job ()
Default constructor.
Allows Job to be used as a container type.
This is used to allow things like jobMap [key] = value.
Definition at line 22 of file Job.cpp.
     : mType (jtINVALID)
     , mJobIndex (0)
 {
 }
ripple::Job::Job (JobType type, std::uint64_t index)
Definition at line 28 of file Job.cpp.
     : mType (type)
     , mJobIndex (index)
 {
 }
ripple::Job::Job (JobType type, std::string const & name, std::uint64_t index, LoadMonitor & lm, std::function< void(Job &)> const & job, CancelCallback cancelCallback)
Definition at line 34 of file Job.cpp.
References m_loadEvent, and name.
     : m_cancelCallback (cancelCallback)
     , mType (type)
     , mJobIndex (index)
     , mJob (job)
     , mName (name)
     , m_queue_time (clock_type::now ())
 {
     m_loadEvent = boost::make_shared <LoadEvent> (boost::ref (lm), name, false);
 }
Member Function Documentation
void ripple::Job::doJob ()
Definition at line 73 of file Job.cpp.
References m_loadEvent, mJob, and mName.
Referenced by ripple::JobQueueImp::processTask().
 {
     m_loadEvent->start ();
     m_loadEvent->reName (mName);
     mJob (*this);
 }
CancelCallback ripple::Job::getCancelCallback () const
Definition at line 55 of file Job.cpp.
References bassert, and m_cancelCallback.
Referenced by ripple::LedgerMasterImp::updatePaths().
 {
     bassert (m_cancelCallback);
     return m_cancelCallback;
 }
JobType ripple::Job::getType () const
Definition at line 50 of file Job.cpp.
References mType.
Referenced by ripple::PeerImp::checkPropose(), ripple::JobQueueImp::finishJob(), ripple::JobQueueImp::processTask(), and ripple::JobQueueImp::queueJob().
 {
     return mType;
 }
bool ripple::Job::operator< (const Job & j) const
Definition at line 108 of file Job.cpp.
References mJobIndex, and mType.
 {
     if (mType < j.mType)
         return false;
     if (mType > j.mType)
         return true;
     return mJobIndex < j.mJobIndex;
 }
bool ripple::Job::operator<= (const Job & j) const
Definition at line 119 of file Job.cpp.
References mJobIndex, and mType.
 {
     if (mType < j.mType)
         return false;
     if (mType > j.mType)
         return true;
     return mJobIndex <= j.mJobIndex;
 }
bool ripple::Job::operator> (const Job & j) const
Definition at line 86 of file Job.cpp.
References mJobIndex, and mType.
 {
     if (mType < j.mType)
         return true;
     if (mType > j.mType)
         return false;
     return mJobIndex > j.mJobIndex;
 }
bool ripple::Job::operator>= (const Job & j) const
Definition at line 97 of file Job.cpp.
References mJobIndex, and mType.
 {
     if (mType < j.mType)
         return true;
     if (mType > j.mType)
         return false;
     return mJobIndex >= j.mJobIndex;
 }
Job::clock_type::time_point const & ripple::Job::queue_time () const
Returns the time when the job was queued.
Definition at line 61 of file Job.cpp.
References m_queue_time.
Referenced by ripple::JobQueueImp::processTask().
 {
     return m_queue_time;
 }
void ripple::Job::rename (const std::string & n)
Definition at line 81 of file Job.cpp.
References mName.
Referenced by ripple::WSServerHandler< endpoint_type >::do_message().
 {
     mName = newName;
 }
bool ripple::Job::shouldCancel () const
Returns true if the running job should make a best-effort cancel.
Definition at line 66 of file Job.cpp.
References m_cancelCallback.
Referenced by ripple::LedgerMasterImp::tryFill(), and ripple::LedgerMasterImp::updatePaths().
 {
     if (m_cancelCallback)
         return m_cancelCallback ();
     return false;
 }
Member Data Documentation
CancelCallback ripple::Job::m_cancelCallback private
Definition at line 127 of file Job.h.
Referenced by getCancelCallback(), and shouldCancel().
LoadEvent::pointer ripple::Job::m_loadEvent private
Definition at line 131 of file Job.h.
Referenced by doJob(), and Job().
clock_type::time_point ripple::Job::m_queue_time private
Definition at line 133 of file Job.h.
Referenced by queue_time().
std::function<void (Job&)> ripple::Job::mJob private
Definition at line 130 of file Job.h.
Referenced by doJob().
std::uint64_t ripple::Job::mJobIndex private
Definition at line 129 of file Job.h.
Referenced by operator<(), operator<=(), operator>(), and operator>=().
std::string ripple::Job::mName private
Definition at line 132 of file Job.h.
Referenced by doJob(), and rename().
JobType ripple::Job::mType private
Definition at line 128 of file Job.h.
Referenced by getType(), operator<(), operator<=(), operator>(), and operator>=().
The documentation for this class was generated from the following files:
rippled/src/ripple_core/functional/Job.h
rippled/src/ripple_core/functional/Job.cpp