rippled: ripple::WSConnectionType< endpoint_type > Class Template Reference
ripple::WSConnectionType< endpoint_type > Class Template Reference
#include <WSConnection.h>
Public Types
typedef
endpoint_type::connection_type connection
typedef boost::shared_ptr
< connection > connection_ptr
typedef boost::weak_ptr
< connection > weak_connection_ptr
typedef WSServerHandler
< endpoint_type > server_type
Public Member Functions
WSConnectionType (Resource::Manager &resourceManager, InfoSub::Source &source, server_type &serverHandler, connection_ptr const &cpConnection)
void preDestroy ()
void send (const Json::Value &jvObj, bool broadcast)
void send (const Json::Value &jvObj, const std::string &sObj, bool broadcast)
void disconnect ()
bool onPingTimer (std::string &)
void setPingTimer ()
Public Member Functions inherited from ripple::WSConnection
void onPong (const std::string &)
void rcvMessage (message_ptr msg, bool &msgRejected, bool &runQueue)
message_ptr getMessage ()
bool checkMessage ()
void returnMessage (message_ptr ptr)
Json::Value invokeCommand (Json::Value &jvRequest)
Public Member Functions inherited from ripple::InfoSub
InfoSub (Source &source, Consumer consumer)
virtual ~InfoSub ()
Consumer & getConsumer ()
std::uint64_t getSeq ()
void onSendEmpty ()
void insertSubAccountInfo (RippleAddress addr, std::uint32_t uLedgerIndex)
void clearPathRequest ()
void setPathRequest (const boost::shared_ptr< PathRequest > &req)
boost::shared_ptr< PathRequest >
const & getPathRequest ()
Public Member Functions inherited from ripple::CountedObject< InfoSub >
CountedObject ()
CountedObject (CountedObject const &)
~CountedObject ()
Public Member Functions inherited from ripple::CountedObject< WSConnection >
CountedObject ()
CountedObject (CountedObject const &)
~CountedObject ()
Static Public Member Functions
static void destroy (boost::shared_ptr< WSConnectionType< endpoint_type > >)
static void handle_disconnect (weak_connection_ptr c)
static void pingTimer (weak_connection_ptr c, server_type *h, boost::system::error_code const &e)
Static Public Member Functions inherited from ripple::WSConnection
static char const * getCountedObjectName ()
Static Public Member Functions inherited from ripple::InfoSub
static char const * getCountedObjectName ()
Private Attributes
server_type & m_serverHandler
weak_connection_ptr m_connection
Additional Inherited Members
Protected Types inherited from ripple::WSConnection
typedef
websocketpp::message::data::ptr message_ptr
Protected Member Functions inherited from ripple::WSConnection
WSConnection (Resource::Manager &resourceManager, Resource::Consumer usage, InfoSub::Source &source, bool isPublic, beast::IP::Endpoint const &remoteAddress, boost::asio::io_service &io_service)
virtual ~WSConnection ()
Protected Attributes inherited from ripple::WSConnection
Resource::Manager & m_resourceManager
Resource::Consumer m_usage
bool const m_isPublic
beast::IP::Endpoint const m_remoteAddress
LockType m_receiveQueueMutex
std::deque< message_ptr > m_receiveQueue
NetworkOPs & m_netOPs
boost::asio::deadline_timer m_pingTimer
bool m_sentPing
bool m_receiveQueueRunning
bool m_isDead
boost::asio::io_service & m_io_service
Detailed Description
template<typename endpoint_type>
class ripple::WSConnectionType< endpoint_type >
A Ripple WebSocket connection handler for a specific endpoint_type.
Definition at line 84 of file WSConnection.h.
Member Typedef Documentation
template<typename endpoint_type > typedef endpoint_type::connection_type ripple::WSConnectionType< endpoint_type >::connection
Definition at line 88 of file WSConnection.h.
template<typename endpoint_type > typedef boost::shared_ptr<connection> ripple::WSConnectionType< endpoint_type >::connection_ptr
Definition at line 89 of file WSConnection.h.
template<typename endpoint_type > typedef WSServerHandler<endpoint_type> ripple::WSConnectionType< endpoint_type >::server_type
Definition at line 91 of file WSConnection.h.
template<typename endpoint_type > typedef boost::weak_ptr<connection> ripple::WSConnectionType< endpoint_type >::weak_connection_ptr
Definition at line 90 of file WSConnection.h.
Constructor & Destructor Documentation
template<typename endpoint_type > ripple::WSConnectionType< endpoint_type >::WSConnectionType (Resource::Manager & resourceManager, InfoSub::Source & source, server_type & serverHandler, connection_ptr const & cpConnection) inline
Definition at line 94 of file WSConnection.h.
References ripple::WSConnectionType< endpoint_type >::setPingTimer().
         : WSConnection (
             resourceManager,
             resourceManager.newInboundEndpoint (cpConnection->get_socket ().remote_endpoint ()),
             source,
             serverHandler.getPublic (),
             cpConnection->get_socket ().remote_endpoint (),
             cpConnection->get_io_service ())
         , m_serverHandler (serverHandler)
         , m_connection (cpConnection)
     {
         setPingTimer ();
     }
Member Function Documentation
template<typename endpoint_type > static void ripple::WSConnectionType< endpoint_type >::destroy (boost::shared_ptr< WSConnectionType< endpoint_type > >) inline static
Definition at line 122 of file WSConnection.h.
     {
         // Just discards the reference
     }
template<typename endpoint_type > void ripple::WSConnectionType< endpoint_type >::disconnect () inline virtual
Implements ripple::WSConnection.
Definition at line 144 of file WSConnection.h.
References ripple::WSConnectionType< endpoint_type >::m_connection, and ripple::WSConnection::m_io_service.
     {
         connection_ptr ptr = m_connection.lock ();
         if (ptr)
             m_io_service.dispatch (ptr->get_strand ().wrap (boost::bind (
                 &WSConnectionType <endpoint_type>::handle_disconnect,
                     m_connection)));
     }
template<typename endpoint_type > static void ripple::WSConnectionType< endpoint_type >::handle_disconnect (weak_connection_ptr c) inline static
Definition at line 154 of file WSConnection.h.
     {
         connection_ptr ptr = c.lock ();
         if (ptr)
             ptr->close (websocketpp::close::status::PROTOCOL_ERROR, "overload");
     }
template<typename endpoint_type > bool ripple::WSConnectionType< endpoint_type >::onPingTimer (std::string &) inline
Definition at line 162 of file WSConnection.h.
References ripple::WSConnection::m_sentPing, and ripple::WSConnectionType< endpoint_type >::setPingTimer().
     {
         if (m_sentPing)
             return true; // causes connection to close
         m_sentPing = true;
         setPingTimer ();
         return false; // causes ping to be sent
     }
template<typename endpoint_type > static void ripple::WSConnectionType< endpoint_type >::pingTimer (weak_connection_ptr c, server_type * h, boost::system::error_code const & e) inline static
Definition at line 174 of file WSConnection.h.
References ripple::WSServerHandler< endpoint_type >::pingTimer().
     {
         if (e)
             return;
         connection_ptr ptr = c.lock ();
         if (ptr)
             h->pingTimer (ptr);
     }
template<typename endpoint_type > void ripple::WSConnectionType< endpoint_type >::preDestroy () inline virtual
Implements ripple::WSConnection.
Definition at line 110 of file WSConnection.h.
References ripple::WSConnectionType< endpoint_type >::m_connection, ripple::WSConnection::m_isDead, ripple::WSConnection::m_pingTimer, and ripple::WSConnection::m_receiveQueueMutex.
     {
         // sever connection
         m_pingTimer.cancel ();
         m_connection.reset ();
         {
             ScopedLockType sl (m_receiveQueueMutex);
             m_isDead = true;
         }
     }
template<typename endpoint_type > void ripple::WSConnectionType< endpoint_type >::send (const Json::Value & jvObj, bool broadcast) inline virtual
Implements ripple::InfoSub.
Definition at line 128 of file WSConnection.h.
References ripple::WSConnectionType< endpoint_type >::m_connection, ripple::WSConnectionType< endpoint_type >::m_serverHandler, and ripple::WSServerHandler< endpoint_type >::send().
     {
         connection_ptr ptr = m_connection.lock ();
         if (ptr)
             m_serverHandler.send (ptr, jvObj, broadcast);
     }
template<typename endpoint_type > void ripple::WSConnectionType< endpoint_type >::send (const Json::Value & jvObj, const std::string & sObj, bool broadcast) inline virtual
Reimplemented from ripple::InfoSub.
Definition at line 136 of file WSConnection.h.
References ripple::WSConnectionType< endpoint_type >::m_connection, ripple::WSConnectionType< endpoint_type >::m_serverHandler, and ripple::WSServerHandler< endpoint_type >::send().
     {
         connection_ptr ptr = m_connection.lock ();
         if (ptr)
             m_serverHandler.send (ptr, sObj, broadcast);
     }
template<typename endpoint_type > void ripple::WSConnectionType< endpoint_type >::setPingTimer () inline
Definition at line 186 of file WSConnection.h.
References ripple::getConfig(), ripple::WSConnectionType< endpoint_type >::m_connection, ripple::WSConnection::m_pingTimer, and ripple::WSConnectionType< endpoint_type >::m_serverHandler.
Referenced by ripple::WSConnectionType< endpoint_type >::onPingTimer(), and ripple::WSConnectionType< endpoint_type >::WSConnectionType().
     {
         connection_ptr ptr = m_connection.lock ();
         if (ptr)
         {
             m_pingTimer.expires_from_now (boost::posix_time::seconds
                 (getConfig ().WEBSOCKET_PING_FREQ));
             m_pingTimer.async_wait (ptr->get_strand ().wrap (
                 boost::bind (&WSConnectionType <endpoint_type>::pingTimer,
                     m_connection, &m_serverHandler, boost::asio::placeholders::error)));
         }
     }
Member Data Documentation
template<typename endpoint_type > weak_connection_ptr ripple::WSConnectionType< endpoint_type >::m_connection private
Definition at line 203 of file WSConnection.h.
Referenced by ripple::WSConnectionType< endpoint_type >::disconnect(), ripple::WSConnectionType< endpoint_type >::preDestroy(), ripple::WSConnectionType< endpoint_type >::send(), and ripple::WSConnectionType< endpoint_type >::setPingTimer().
template<typename endpoint_type > server_type& ripple::WSConnectionType< endpoint_type >::m_serverHandler private
Definition at line 202 of file WSConnection.h.
Referenced by ripple::WSConnectionType< endpoint_type >::send(), and ripple::WSConnectionType< endpoint_type >::setPingTimer().
The documentation for this class was generated from the following file:
rippled/src/ripple_app/websocket/WSConnection.h