rippled: beast::asio::detail::bound_handler< DeducedHandler, Args > Class Template Reference
beast::asio::detail::bound_handler< DeducedHandler, Args > Class Template Reference
#include <bind_handler.h>
Public Types
typedef void result_type
Public Member Functions
bound_handler (DeducedHandler &&handler, Args &&...args)
void operator() ()
void operator() () const
Private Types
typedef std::tuple
< std::decay_t< Args >...> args_type
Static Private Member Functions
template<class Handler , class Tuple , std::size_t... S>
static void invoke (Handler &h, Tuple &args, std::index_sequence< S...>)
Private Attributes
std::decay_t< DeducedHandler > m_handler
args_type m_args
Friends
template<class Function >
void asio_handler_invoke (Function &f, bound_handler *h)
template<class Function >
void asio_handler_invoke (Function const &f, bound_handler *h)
void * asio_handler_allocate (std::size_t size, bound_handler *h)
void asio_handler_deallocate (void *p, std::size_t size, bound_handler *h)
bool asio_handler_is_continuation (bound_handler *h)
Detailed Description
template<class DeducedHandler, class... Args>
class beast::asio::detail::bound_handler< DeducedHandler, Args >
Nullary handler that calls Handler with bound arguments. The rebound handler provides the same io_service execution guarantees as the original handler.
Definition at line 41 of file bind_handler.h.
Member Typedef Documentation
template<class DeducedHandler , class... Args> typedef std::tuple<std::decay_t <Args>...> beast::asio::detail::bound_handler< DeducedHandler, Args >::args_type private
Definition at line 44 of file bind_handler.h.
template<class DeducedHandler , class... Args> typedef void beast::asio::detail::bound_handler< DeducedHandler, Args >::result_type
Definition at line 57 of file bind_handler.h.
Constructor & Destructor Documentation
template<class DeducedHandler , class... Args> beast::asio::detail::bound_handler< DeducedHandler, Args >::bound_handler (DeducedHandler && handler, Args &&... args) inline
Definition at line 59 of file bind_handler.h.
         : m_handler (std::forward <DeducedHandler> (handler))
         , m_args (std::forward <Args> (args)...)
     {
     }
Member Function Documentation
template<class DeducedHandler , class... Args> template<class Handler , class Tuple , std::size_t... S> static void beast::asio::detail::bound_handler< DeducedHandler, Args >::invoke (Handler & h, Tuple & args, std::index_sequence< S...>) inline static private
Definition at line 50 of file bind_handler.h.
Referenced by beast::asio::detail::bound_handler< DeducedHandler, Args >::operator()().
     {
         h (std::get <S> (args)...);
     }
template<class DeducedHandler , class... Args> void beast::asio::detail::bound_handler< DeducedHandler, Args >::operator() () inline
Definition at line 66 of file bind_handler.h.
References beast::asio::detail::bound_handler< DeducedHandler, Args >::invoke(), beast::asio::detail::bound_handler< DeducedHandler, Args >::m_args, and beast::asio::detail::bound_handler< DeducedHandler, Args >::m_handler.
     {
         invoke (m_handler, m_args,
             std::index_sequence_for <Args...> ());
     }
template<class DeducedHandler , class... Args> void beast::asio::detail::bound_handler< DeducedHandler, Args >::operator() () const inline
Definition at line 73 of file bind_handler.h.
References beast::asio::detail::bound_handler< DeducedHandler, Args >::invoke(), beast::asio::detail::bound_handler< DeducedHandler, Args >::m_args, and beast::asio::detail::bound_handler< DeducedHandler, Args >::m_handler.
     {
         invoke (m_handler, m_args,
             std::index_sequence_for <Args...> ());
     }
Friends And Related Function Documentation
template<class DeducedHandler , class... Args> void* asio_handler_allocate (std::size_t size, bound_handler< DeducedHandler, Args > * h) friend
Definition at line 99 of file bind_handler.h.
     {
         return boost_asio_handler_alloc_helpers::
             allocate (size, h->m_handler);
     }
template<class DeducedHandler , class... Args> void asio_handler_deallocate (void * p, std::size_t size, bound_handler< DeducedHandler, Args > * h) friend
Definition at line 107 of file bind_handler.h.
     {
         boost_asio_handler_alloc_helpers::
             deallocate (p, size, h->m_handler);
     }
template<class DeducedHandler , class... Args> template<class Function > void asio_handler_invoke (Function & f, bound_handler< DeducedHandler, Args > * h) friend
Definition at line 82 of file bind_handler.h.
     {
         boost_asio_handler_invoke_helpers::
             invoke (f, h->m_handler);
     }
template<class DeducedHandler , class... Args> template<class Function > void asio_handler_invoke (Function const & f, bound_handler< DeducedHandler, Args > * h) friend
Definition at line 91 of file bind_handler.h.
     {
         boost_asio_handler_invoke_helpers::
             invoke (f, h->m_handler);
     }
template<class DeducedHandler , class... Args> bool asio_handler_is_continuation (bound_handler< DeducedHandler, Args > * h) friend
Definition at line 115 of file bind_handler.h.
     {
         return boost_asio_handler_cont_helpers::
             is_continuation (h->m_handler);
     }
Member Data Documentation
template<class DeducedHandler , class... Args> args_type beast::asio::detail::bound_handler< DeducedHandler, Args >::m_args private
Definition at line 47 of file bind_handler.h.
Referenced by beast::asio::detail::bound_handler< DeducedHandler, Args >::operator()().
template<class DeducedHandler , class... Args> std::decay_t<DeducedHandler> beast::asio::detail::bound_handler< DeducedHandler, Args >::m_handler private
Definition at line 46 of file bind_handler.h.
Referenced by beast::asio::detail::bound_handler< DeducedHandler, Args >::operator()().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/asio/bind_handler.h