rippled: beast::aged_associative_container_test_base Class Reference
beast::aged_associative_container_test_base Class Reference
Classes
struct AllocT
struct CompT
struct ContType
struct ContType< Base, true >
struct equal_value
struct EqualT
class HashT
class MaybeMap
class MaybeMap< Base, true >
class MaybeMulti
class MaybeMulti< Base, true >
class MaybeUnordered
class MaybeUnordered< Base, true >
struct TestTraits
struct TestTraitsBase
struct TestTraitsHelper
Public Member Functions
template<class Container , class Values >
std::enable_if
< Container::is_map::value
&&!Container::is_multi::value >
::type checkMapContents (Container &c, Values const &v)
template<class Container , class Values >
std::enable_if
<!(Container::is_map::value
&&!Container::is_multi::value)>
::type checkMapContents (Container, Values const &)
template<class C , class Values >
std::enable_if
< std::remove_reference< C >
::type::is_unordered::value >
::type checkUnorderedContentsRefRef (C &&c, Values const &v)
template<class C , class Values >
std::enable_if
<!std::remove_reference< C >
::type::is_unordered::value >
::type checkUnorderedContentsRefRef (C &&, Values const &)
template<class C , class Values >
void checkContentsRefRef (C &&c, Values const &v)
template<class Cont , class Values >
void checkContents (Cont &c, Values const &v)
template<class Cont >
void checkContents (Cont &c)
template<bool IsUnordered, bool IsMulti, bool IsMap>
std::enable_if<!IsUnordered >::type testConstructEmpty ()
template<bool IsUnordered, bool IsMulti, bool IsMap>
std::enable_if< IsUnordered >::type testConstructEmpty ()
template<bool IsUnordered, bool IsMulti, bool IsMap>
std::enable_if<!IsUnordered >::type testConstructRange ()
template<bool IsUnordered, bool IsMulti, bool IsMap>
std::enable_if< IsUnordered >::type testConstructRange ()
template<bool IsUnordered, bool IsMulti, bool IsMap>
std::enable_if<!IsUnordered >::type testConstructInitList ()
template<bool IsUnordered, bool IsMulti, bool IsMap>
std::enable_if< IsUnordered >::type testConstructInitList ()
template<bool IsUnordered, bool IsMulti, bool IsMap>
void testCopyMove ()
template<class Container , class Values >
void checkInsertCopy (Container &c, Values const &v)
template<class Container , class Values >
void checkInsertMove (Container &c, Values const &v)
template<class Container , class Values >
void checkInsertHintCopy (Container &c, Values const &v)
template<class Container , class Values >
void checkInsertHintMove (Container &c, Values const &v)
template<class Container , class Values >
void checkEmplace (Container &c, Values const &v)
template<class Container , class Values >
void checkEmplaceHint (Container &c, Values const &v)
template<bool IsUnordered, bool IsMulti, bool IsMap>
void testModifiers ()
template<bool IsUnordered, bool IsMulti, bool IsMap>
void testChronological ()
template<bool IsUnordered, bool IsMulti, bool IsMap>
std::enable_if< IsMap
&&!IsMulti >::type testArrayCreate ()
template<bool IsUnordered, bool IsMulti, bool IsMap>
std::enable_if<!(IsMap
&&!IsMulti)>::type testArrayCreate ()
template<bool IsUnordered, bool IsMulti, bool IsMap>
std::enable_if<!IsUnordered >::type testCompare ()
template<bool IsUnordered, bool IsMulti, bool IsMap>
std::enable_if< IsUnordered >::type testCompare ()
template<bool IsUnordered, bool IsMulti, bool IsMap>
std::enable_if<!IsUnordered >::type testObservers ()
template<bool IsUnordered, bool IsMulti, bool IsMap>
std::enable_if< IsUnordered >::type testObservers ()
template<bool IsUnordered, bool IsMulti, bool IsMap>
void testMaybeUnorderedMultiMap ()
template<bool IsUnordered, bool IsMulti>
void testMaybeUnorderedMulti ()
template<bool IsUnordered>
void testMaybeUnordered ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Static Public Member Functions
template<class Cont >
static std::string name (Cont const &)
template<class Cont >
static std::list< typename
Cont::value_type > make_list (Cont const &c)
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 53 of file aged_associative_container.test.cpp.
Member Function Documentation
template<class Cont , class Values > void beast::aged_associative_container_test_base::checkContents (Cont & c, Values const & v)
Definition at line 668 of file aged_associative_container.test.cpp.
References checkContentsRefRef(), and checkMapContents().
Referenced by checkContents(), checkEmplace(), checkEmplaceHint(), checkInsertCopy(), checkInsertHintCopy(), checkInsertHintMove(), checkInsertMove(), testArrayCreate(), testConstructEmpty(), testConstructRange(), and testCopyMove().
 {
     checkContentsRefRef (c, v);
     checkContentsRefRef (const_cast <Cont const&> (c), v);
     checkMapContents (c, v);
 }
template<class Cont > void beast::aged_associative_container_test_base::checkContents (Cont & c)
Definition at line 678 of file aged_associative_container.test.cpp.
References checkContents(), and value.
 {
     typedef TestTraits <
         Cont::is_unordered::value,
             Cont::is_multi::value,
                 Cont::is_map::value
                 > Traits;
     typedef typename Traits::Values Values;
     checkContents (c, Values());
 }
template<class C , class Values > void beast::aged_associative_container_test_base::checkContentsRefRef (C && c, Values const & v)
Definition at line 638 of file aged_associative_container.test.cpp.
References checkUnorderedContentsRefRef(), beast::unit_test::suite::expect(), and value.
Referenced by checkContents().
 {
     typedef typename std::remove_reference <C>::type Cont;
     typedef TestTraits <
         Cont::is_unordered::value,
             Cont::is_multi::value,
                 Cont::is_map::value
                 > Traits;
     typedef typename Cont::size_type size_type;
     expect (c.size() == v.size());
     expect (size_type (std::distance (
         c.begin(), c.end())) == v.size());
     expect (size_type (std::distance (
         c.cbegin(), c.cend())) == v.size());
     expect (size_type (std::distance (
         c.chronological.begin(), c.chronological.end())) == v.size());
     expect (size_type (std::distance (
         c.chronological.cbegin(), c.chronological.cend())) == v.size());
     expect (size_type (std::distance (
         c.chronological.rbegin(), c.chronological.rend())) == v.size());
     expect (size_type (std::distance (
         c.chronological.crbegin(), c.chronological.crend())) == v.size());
     checkUnorderedContentsRefRef (c, v);
 }
template<class Container , class Values > void beast::aged_associative_container_test_base::checkEmplace (Container & c, Values const & v)
Definition at line 1138 of file aged_associative_container.test.cpp.
References checkContents().
 {
     for (auto const& e : v)
         c.emplace (e);
     checkContents (c, v);
 }
template<class Container , class Values > void beast::aged_associative_container_test_base::checkEmplaceHint (Container & c, Values const & v)
Definition at line 1148 of file aged_associative_container.test.cpp.
References checkContents().
 {
     for (auto const& e : v)
         c.emplace_hint (c.cend(), e);
     checkContents (c, v);
 }
template<class Container , class Values > void beast::aged_associative_container_test_base::checkInsertCopy (Container & c, Values const & v)
Definition at line 1096 of file aged_associative_container.test.cpp.
References checkContents().
Referenced by testModifiers().
 {
     for (auto const& e : v)
         c.insert (e);
     checkContents (c, v);
 }
template<class Container , class Values > void beast::aged_associative_container_test_base::checkInsertHintCopy (Container & c, Values const & v)
Definition at line 1117 of file aged_associative_container.test.cpp.
References checkContents().
Referenced by testModifiers().
 {
     for (auto const& e : v)
         c.insert (c.cend(), e);
     checkContents (c, v);
 }
template<class Container , class Values > void beast::aged_associative_container_test_base::checkInsertHintMove (Container & c, Values const & v)
Definition at line 1127 of file aged_associative_container.test.cpp.
References checkContents().
Referenced by testModifiers().
 {
     Values v2 (v);
     for (auto& e : v2)
         c.insert (c.cend(), std::move (e));
     checkContents (c, v);
 }
template<class Container , class Values > void beast::aged_associative_container_test_base::checkInsertMove (Container & c, Values const & v)
Definition at line 1106 of file aged_associative_container.test.cpp.
References checkContents().
Referenced by testModifiers().
 {
     Values v2 (v);
     for (auto& e : v2)
         c.insert (std::move (e));
     checkContents (c, v);
 }
template<class Container , class Values > std::enable_if< Container::is_map::value &&!Container::is_multi::value >::type beast::aged_associative_container_test_base::checkMapContents (Container & c, Values const & v)
Definition at line 573 of file aged_associative_container.test.cpp.
References beast::unit_test::suite::expect(), and beast::unit_test::suite::fail().
Referenced by checkContents().
 {
     if (v.empty())
     {
         expect (c.empty());
         expect (c.size() == 0);
         return;
     }
     try
     {
         // Make sure no exception is thrown
         for (auto const& e : v)
             c.at (e.first);
         for (auto const& e : v)
             expect (c.operator[](e.first) == e.second);
     }
     catch (std::out_of_range const&)
     {
         fail ("caught exception");
     }
 }
template<class Container , class Values > std::enable_if<! (Container::is_map::value && ! Container::is_multi::value)>::type beast::aged_associative_container_test_base::checkMapContents (Container , Values const &) inline
Definition at line 413 of file aged_associative_container.test.cpp.
     {
     }
template<class C , class Values > std::enable_if< std::remove_reference< C >::type::is_unordered::value >::type beast::aged_associative_container_test_base::checkUnorderedContentsRefRef (C && c, Values const & v)
Definition at line 604 of file aged_associative_container.test.cpp.
References beast::unit_test::suite::expect(), hash, beast::asio::InputParser::match(), and value.
Referenced by checkContentsRefRef().
 {
     typedef typename std::remove_reference <C>::type Cont;
     typedef TestTraits <
         Cont::is_unordered::value,
             Cont::is_multi::value,
                 Cont::is_map::value
                 > Traits;
     typedef typename Cont::size_type size_type;
     auto const hash (c.hash_function());
     auto const key_eq (c.key_eq());
     for (size_type i (0); i < c.bucket_count(); ++i)
     {
         auto const last (c.end(i));
         for (auto iter (c.begin (i)); iter != last; ++iter)
         {
             auto const match (std::find_if (v.begin(), v.end(),
                 [iter](typename Values::value_type const& e)
                 {
                     return Traits::extract (*iter) ==
                         Traits::extract (e);
                 }));
             expect (match != v.end());
             expect (key_eq (Traits::extract (*iter),
                 Traits::extract (*match)));
             expect (hash (Traits::extract (*iter)) ==
                 hash (Traits::extract (*match)));
         }
     }
 }
template<class C , class Values > std::enable_if<! std::remove_reference <C>::type::is_unordered::value>::type beast::aged_associative_container_test_base::checkUnorderedContentsRefRef (C && , Values const &) inline
Definition at line 432 of file aged_associative_container.test.cpp.
     {
     }
template<class Cont > static std::list<typename Cont::value_type> beast::aged_associative_container_test_base::make_list (Cont const & c) inline static
Definition at line 391 of file aged_associative_container.test.cpp.
Referenced by testModifiers().
     {
         return std::list <typename Cont::value_type> (
             c.begin(), c.end());
     }
template<class Cont > static std::string beast::aged_associative_container_test_base::name (Cont const &) inline static
Definition at line 370 of file aged_associative_container.test.cpp.
     {
         return TestTraits <
             Cont::is_unordered,
             Cont::is_multi,
             Cont::is_map>::name();
     }
template<bool IsUnordered, bool IsMulti, bool IsMap> std::enable_if< IsMap &&!IsMulti >::type beast::aged_associative_container_test_base::testArrayCreate ()
Definition at line 1259 of file aged_associative_container.test.cpp.
References checkContents(), and beast::unit_test::suite::testcase().
 {
     typedef TestTraits <IsUnordered, IsMulti, IsMap> Traits;
     typename Traits::Clock clock;
     auto v (Traits::values());
     //testcase (Traits::name() + " array create");
     testcase ("array create");
     {
         // Copy construct key
         typename Traits::template Cont <> c (clock);
         for (auto e : v)
             c [e.first] = e.second;
         checkContents (c, v);
     }
     {
         // Move construct key
         typename Traits::template Cont <> c (clock);
         for (auto e : v)
             c [std::move (e.first)] = e.second;
         checkContents (c, v);
     }
 }
template<bool IsUnordered, bool IsMulti, bool IsMap> std::enable_if<! (IsMap && ! IsMulti)>::type beast::aged_associative_container_test_base::testArrayCreate () inline
Definition at line 521 of file aged_associative_container.test.cpp.
     {
     }
template<bool IsUnordered, bool IsMulti, bool IsMap> void beast::aged_associative_container_test_base::testChronological ()
Definition at line 1218 of file aged_associative_container.test.cpp.
References std::detail::equal(), beast::unit_test::suite::expect(), beast::unit_test::suite::testcase(), and rocksdb::crc32c::Value().
 {
     typedef TestTraits <IsUnordered, IsMulti, IsMap> Traits;
     typedef typename Traits::Value Value;
     typename Traits::Clock clock;
     auto const v (Traits::values());
     //testcase (Traits::name() + " chronological");
     testcase ("chronological");
     typename Traits::template Cont <> c (
         v.begin(), v.end(), clock);
     expect (std::equal (
         c.chronological.cbegin(), c.chronological.cend(),
             v.begin(), v.end(), equal_value <Traits> ()));
     for (auto iter (v.rbegin()); iter != v.rend(); ++iter)
     {
         auto found (c.find (Traits::extract (*iter)));
         expect (found != c.cend());
         if (found == c.cend())
             return;
         c.touch (found);
     }
     expect (std::equal (
         c.chronological.cbegin(), c.chronological.cend(),
             v.rbegin(), v.rend(), equal_value <Traits> ()));
 }
template<bool IsUnordered, bool IsMulti, bool IsMap> std::enable_if<!IsUnordered >::type beast::aged_associative_container_test_base::testCompare ()
Definition at line 1295 of file aged_associative_container.test.cpp.
References beast::unit_test::suite::expect(), beast::unit_test::suite::testcase(), beast::unit_test::suite::unexpected(), and rocksdb::crc32c::Value().
 {
     typedef TestTraits <IsUnordered, IsMulti, IsMap> Traits;
     typedef typename Traits::Value Value;
     typename Traits::Clock clock;
     auto const v (Traits::values());
     //testcase (Traits::name() + " array create");
     testcase ("array create");
     typename Traits::template Cont <> c1 (
         v.begin(), v.end(), clock);
     typename Traits::template Cont <> c2 (
         v.begin(), v.end(), clock);
     c2.erase (c2.cbegin());
     expect      (c1 != c2);
     unexpected  (c1 == c2);
     expect      (c1 <  c2);
     expect      (c1 <= c2);
     unexpected  (c1 >  c2);
     unexpected  (c1 >= c2);
 }
template<bool IsUnordered, bool IsMulti, bool IsMap> std::enable_if<IsUnordered>::type beast::aged_associative_container_test_base::testCompare () inline
Definition at line 534 of file aged_associative_container.test.cpp.
     {
     }
template<bool IsUnordered, bool IsMulti, bool IsMap> std::enable_if<!IsUnordered >::type beast::aged_associative_container_test_base::testConstructEmpty ()
Definition at line 699 of file aged_associative_container.test.cpp.
References checkContents(), T, beast::unit_test::suite::testcase(), and rocksdb::crc32c::Value().
 {
     typedef TestTraits <IsUnordered, IsMulti, IsMap> Traits;
     typedef typename Traits::Value Value;
     typedef typename Traits::Key Key;
     typedef typename Traits::T T;
     typedef typename Traits::Dur Dur;
     typedef typename Traits::Comp Comp;
     typedef typename Traits::Alloc Alloc;
     typedef typename Traits::MyComp MyComp;
     typedef typename Traits::MyAlloc MyAlloc;
     typename Traits::Clock clock;
     //testcase (Traits::name() + " empty");
     testcase ("empty");
     {
         typename Traits::template Cont <Comp, Alloc> c (
             clock);
         checkContents (c);
     }
     {
         typename Traits::template Cont <MyComp, Alloc> c (
             clock, MyComp(1));
         checkContents (c);
     }
     {
         typename Traits::template Cont <Comp, MyAlloc> c (
             clock, MyAlloc(1));
         checkContents (c);
     }
     {
         typename Traits::template Cont <MyComp, MyAlloc> c (
             clock, MyComp(1), MyAlloc(1));
         checkContents (c);
     }
 }
template<bool IsUnordered, bool IsMulti, bool IsMap> std::enable_if< IsUnordered >::type beast::aged_associative_container_test_base::testConstructEmpty ()
Definition at line 744 of file aged_associative_container.test.cpp.
References checkContents(), T, beast::unit_test::suite::testcase(), and rocksdb::crc32c::Value().
 {
     typedef TestTraits <IsUnordered, IsMulti, IsMap> Traits;
     typedef typename Traits::Value Value;
     typedef typename Traits::Key Key;
     typedef typename Traits::T T;
     typedef typename Traits::Dur Dur;
     typedef typename Traits::Hash Hash;
     typedef typename Traits::Equal Equal;
     typedef typename Traits::Alloc Alloc;
     typedef typename Traits::MyHash MyHash;
     typedef typename Traits::MyEqual MyEqual;
     typedef typename Traits::MyAlloc MyAlloc;
     typename Traits::Clock clock;
     //testcase (Traits::name() + " empty");
     testcase ("empty");
     {
         typename Traits::template Cont <Hash, Equal, Alloc> c (
             clock);
         checkContents (c);
     }
     {
         typename Traits::template Cont <MyHash, Equal, Alloc> c (
             clock, MyHash(1));
         checkContents (c);
     }
     {
         typename Traits::template Cont <Hash, MyEqual, Alloc> c (
             clock, MyEqual (1));
         checkContents (c);
     }
     {
         typename Traits::template Cont <Hash, Equal, MyAlloc> c (
             clock, MyAlloc (1));
         checkContents (c);
     }
     {
         typename Traits::template Cont <MyHash, MyEqual, Alloc> c (
             clock, MyHash(1), MyEqual(1));
         checkContents (c);
     }
     {
         typename Traits::template Cont <MyHash, Equal, MyAlloc> c (
             clock, MyHash(1), MyAlloc(1));
         checkContents (c);
     }
     {
         typename Traits::template Cont <Hash, MyEqual, MyAlloc> c (
             clock, MyEqual(1), MyAlloc(1));
         checkContents (c);
     }
     {
         typename Traits::template Cont <MyHash, MyEqual, MyAlloc> c (
             clock, MyHash(1), MyEqual(1), MyAlloc(1));
         checkContents (c);
     }
 }
template<bool IsUnordered, bool IsMulti, bool IsMap> std::enable_if<!IsUnordered >::type beast::aged_associative_container_test_base::testConstructInitList ()
Definition at line 957 of file aged_associative_container.test.cpp.
References beast::unit_test::suite::pass(), T, beast::unit_test::suite::testcase(), and rocksdb::crc32c::Value().
 {
     typedef TestTraits <IsUnordered, IsMulti, IsMap> Traits;
     typedef typename Traits::Value Value;
     typedef typename Traits::Key Key;
     typedef typename Traits::T T;
     typedef typename Traits::Dur Dur;
     typedef typename Traits::Comp Comp;
     typedef typename Traits::Alloc Alloc;
     typedef typename Traits::MyComp MyComp;
     typedef typename Traits::MyAlloc MyAlloc;
     typename Traits::Clock clock;
     //testcase (Traits::name() + " init-list");
     testcase ("init-list");
     // VFALCO TODO
     pass();
 }
template<bool IsUnordered, bool IsMulti, bool IsMap> std::enable_if< IsUnordered >::type beast::aged_associative_container_test_base::testConstructInitList ()
Definition at line 982 of file aged_associative_container.test.cpp.
References beast::unit_test::suite::pass(), T, beast::unit_test::suite::testcase(), and rocksdb::crc32c::Value().
 {
     typedef TestTraits <IsUnordered, IsMulti, IsMap> Traits;
     typedef typename Traits::Value Value;
     typedef typename Traits::Key Key;
     typedef typename Traits::T T;
     typedef typename Traits::Dur Dur;
     typedef typename Traits::Hash Hash;
     typedef typename Traits::Equal Equal;
     typedef typename Traits::Alloc Alloc;
     typedef typename Traits::MyHash MyHash;
     typedef typename Traits::MyEqual MyEqual;
     typedef typename Traits::MyAlloc MyAlloc;
     typename Traits::Clock clock;
     //testcase (Traits::name() + " init-list");
     testcase ("init-list");
     // VFALCO TODO
     pass();
 }
template<bool IsUnordered, bool IsMulti, bool IsMap> std::enable_if<!IsUnordered >::type beast::aged_associative_container_test_base::testConstructRange ()
Definition at line 814 of file aged_associative_container.test.cpp.
References checkContents(), beast::asio::swap(), T, beast::unit_test::suite::testcase(), and rocksdb::crc32c::Value().
 {
     typedef TestTraits <IsUnordered, IsMulti, IsMap> Traits;
     typedef typename Traits::Value Value;
     typedef typename Traits::Key Key;
     typedef typename Traits::T T;
     typedef typename Traits::Dur Dur;
     typedef typename Traits::Comp Comp;
     typedef typename Traits::Alloc Alloc;
     typedef typename Traits::MyComp MyComp;
     typedef typename Traits::MyAlloc MyAlloc;
     typename Traits::Clock clock;
     auto const v (Traits::values());
     //testcase (Traits::name() + " range");
     testcase ("range");
     {
         typename Traits::template Cont <Comp, Alloc> c (
             v.begin(), v.end(),
             clock);
         checkContents (c, v);
     }
     {
         typename Traits::template Cont <MyComp, Alloc> c (
             v.begin(), v.end(),
             clock, MyComp(1));
         checkContents (c, v);
     }
     {
         typename Traits::template Cont <Comp, MyAlloc> c (
             v.begin(), v.end(),
             clock, MyAlloc(1));
         checkContents (c, v);
     }
     {
         typename Traits::template Cont <MyComp, MyAlloc> c (
             v.begin(), v.end(),
             clock, MyComp(1), MyAlloc(1));
         checkContents (c, v);
     }
     // swap
     {
         typename Traits::template Cont <Comp, Alloc> c1 (
             v.begin(), v.end(),
             clock);
         typename Traits::template Cont <Comp, Alloc> c2 (
             clock);
         std::swap (c1, c2);
         checkContents (c2, v);
     }
 }
template<bool IsUnordered, bool IsMulti, bool IsMap> std::enable_if< IsUnordered >::type beast::aged_associative_container_test_base::testConstructRange ()
Definition at line 877 of file aged_associative_container.test.cpp.
References checkContents(), T, beast::unit_test::suite::testcase(), and rocksdb::crc32c::Value().
 {
     typedef TestTraits <IsUnordered, IsMulti, IsMap> Traits;
     typedef typename Traits::Value Value;
     typedef typename Traits::Key Key;
     typedef typename Traits::T T;
     typedef typename Traits::Dur Dur;
     typedef typename Traits::Hash Hash;
     typedef typename Traits::Equal Equal;
     typedef typename Traits::Alloc Alloc;
     typedef typename Traits::MyHash MyHash;
     typedef typename Traits::MyEqual MyEqual;
     typedef typename Traits::MyAlloc MyAlloc;
     typename Traits::Clock clock;
     auto const v (Traits::values());
     //testcase (Traits::name() + " range");
     testcase ("range");
     {
         typename Traits::template Cont <Hash, Equal, Alloc> c (
             v.begin(), v.end(),
             clock);
         checkContents (c, v);
     }
     {
         typename Traits::template Cont <MyHash, Equal, Alloc> c (
             v.begin(), v.end(),
             clock, MyHash(1));
         checkContents (c, v);
     }
     {
         typename Traits::template Cont <Hash, MyEqual, Alloc> c (
             v.begin(), v.end(),
             clock, MyEqual (1));
         checkContents (c, v);
     }
     {
         typename Traits::template Cont <Hash, Equal, MyAlloc> c (
             v.begin(), v.end(),
             clock, MyAlloc (1));
         checkContents (c, v);
     }
     {
         typename Traits::template Cont <MyHash, MyEqual, Alloc> c (
             v.begin(), v.end(),
             clock, MyHash(1), MyEqual(1));
         checkContents (c, v);
     }
     {
         typename Traits::template Cont <MyHash, Equal, MyAlloc> c (
             v.begin(), v.end(),
             clock, MyHash(1), MyAlloc(1));
         checkContents (c, v);
     }
     {
         typename Traits::template Cont <Hash, MyEqual, MyAlloc> c (
             v.begin(), v.end(),
             clock, MyEqual(1), MyAlloc(1));
         checkContents (c, v);
     }
     {
         typename Traits::template Cont <MyHash, MyEqual, MyAlloc> c (
             v.begin(), v.end(),
             clock, MyHash(1), MyEqual(1), MyAlloc(1));
         checkContents (c, v);
     }
 }
template<bool IsUnordered, bool IsMulti, bool IsMap> void beast::aged_associative_container_test_base::testCopyMove ()
Definition at line 1013 of file aged_associative_container.test.cpp.
References checkContents(), beast::unit_test::suite::expect(), beast::unit_test::suite::testcase(), beast::unit_test::suite::unexpected(), and rocksdb::crc32c::Value().
 {
     typedef TestTraits <IsUnordered, IsMulti, IsMap> Traits;
     typedef typename Traits::Value Value;
     typedef typename Traits::Alloc Alloc;
     typename Traits::Clock clock;
     auto const v (Traits::values());
     //testcase (Traits::name() + " copy/move");
     testcase ("copy/move");
     // copy
     {
         typename Traits::template Cont <> c (
             v.begin(), v.end(), clock);
         typename Traits::template Cont <> c2 (c);
         checkContents (c, v);
         checkContents (c2, v);
         expect (c == c2);
         unexpected (c != c2);
     }
     {
         typename Traits::template Cont <> c (
             v.begin(), v.end(), clock);
         typename Traits::template Cont <> c2 (c, Alloc());
         checkContents (c, v);
         checkContents (c2, v);
         expect (c == c2);
         unexpected (c != c2);
     }
     {
         typename Traits::template Cont <> c (
             v.begin(), v.end(), clock);
         typename Traits::template Cont <> c2 (
             clock);
         c2 = c;
         checkContents (c, v);
         checkContents (c2, v);
         expect (c == c2);
         unexpected (c != c2);
     }
     // move
     {
         typename Traits::template Cont <> c (
             v.begin(), v.end(), clock);
         typename Traits::template Cont <> c2 (
             std::move (c));
         checkContents (c2, v);
     }
     {
         typename Traits::template Cont <> c (
             v.begin(), v.end(), clock);
         typename Traits::template Cont <> c2 (
             std::move (c), Alloc());
         checkContents (c2, v);
     }
     {
         typename Traits::template Cont <> c (
             v.begin(), v.end(), clock);
         typename Traits::template Cont <> c2 (
             clock);
         c2 = std::move (c);
         checkContents (c2, v);
     }
 }
template<bool IsUnordered> void beast::aged_associative_container_test_base::testMaybeUnordered ()
template<bool IsUnordered, bool IsMulti> void beast::aged_associative_container_test_base::testMaybeUnorderedMulti ()
template<bool IsUnordered, bool IsMulti, bool IsMap> void beast::aged_associative_container_test_base::testMaybeUnorderedMultiMap ()
Definition at line 1373 of file aged_associative_container.test.cpp.
 {
     typedef TestTraits <IsUnordered, IsMulti, IsMap> Traits;
     testConstructEmpty      <IsUnordered, IsMulti, IsMap> ();
     testConstructRange      <IsUnordered, IsMulti, IsMap> ();
     testConstructInitList   <IsUnordered, IsMulti, IsMap> ();
     testCopyMove            <IsUnordered, IsMulti, IsMap> ();
     testModifiers           <IsUnordered, IsMulti, IsMap> ();
     testChronological       <IsUnordered, IsMulti, IsMap> ();
     testArrayCreate         <IsUnordered, IsMulti, IsMap> ();
     testCompare             <IsUnordered, IsMulti, IsMap> ();
     testObservers           <IsUnordered, IsMulti, IsMap> ();
 }
template<bool IsUnordered, bool IsMulti, bool IsMap> void beast::aged_associative_container_test_base::testModifiers ()
Definition at line 1158 of file aged_associative_container.test.cpp.
References checkInsertCopy(), checkInsertHintCopy(), checkInsertHintMove(), checkInsertMove(), make_list(), and beast::unit_test::suite::testcase().
 {
     typedef TestTraits <IsUnordered, IsMulti, IsMap> Traits;
     typename Traits::Clock clock;
     auto const v (Traits::values());
     auto const l (make_list (v));
     //testcase (Traits::name() + " modify");
     testcase ("modify");
     {
         typename Traits::template Cont <> c (clock);
         checkInsertCopy (c, v);
     }
     {
         typename Traits::template Cont <> c (clock);
         checkInsertCopy (c, l);
     }
     {
         typename Traits::template Cont <> c (clock);
         checkInsertMove (c, v);
     }
     {
         typename Traits::template Cont <> c (clock);
         checkInsertMove (c, l);
     }
     {
         typename Traits::template Cont <> c (clock);
         checkInsertHintCopy (c, v);
     }
     {
         typename Traits::template Cont <> c (clock);
         checkInsertHintCopy (c, l);
     }
     {
         typename Traits::template Cont <> c (clock);
         checkInsertHintMove (c, v);
     }
     {
         typename Traits::template Cont <> c (clock);
         checkInsertHintMove (c, l);
     }
 }
template<bool IsUnordered, bool IsMulti, bool IsMap> std::enable_if<!IsUnordered >::type beast::aged_associative_container_test_base::testObservers ()
Definition at line 1330 of file aged_associative_container.test.cpp.
References beast::unit_test::suite::pass(), and beast::unit_test::suite::testcase().
 {
     typedef TestTraits <IsUnordered, IsMulti, IsMap> Traits;
     typename Traits::Clock clock;
     //testcase (Traits::name() + " observers");
     testcase ("observers");
     typename Traits::template Cont <> c (clock);
     c.key_comp();
     c.value_comp();
     pass();
 }
template<bool IsUnordered, bool IsMulti, bool IsMap> std::enable_if< IsUnordered >::type beast::aged_associative_container_test_base::testObservers ()
Definition at line 1349 of file aged_associative_container.test.cpp.
References beast::unit_test::suite::pass(), and beast::unit_test::suite::testcase().
 {
     typedef TestTraits <IsUnordered, IsMulti, IsMap> Traits;
     typename Traits::Clock clock;
     //testcase (Traits::name() + " observers");
     testcase ("observers");
     typename Traits::template Cont <> c (clock);
     c.hash_function();
     c.key_eq();
     pass();
 }
The documentation for this class was generated from the following file:
rippled/src/beast/beast/container/tests/aged_associative_container.test.cpp