rippled: beast::manual_clock< Duration, IsSteady > Class Template Reference
beast::manual_clock< Duration, IsSteady > Class Template Reference
#include <manual_clock.h>
Public Member Functions
manual_clock (time_point const &t=time_point(Duration(0)))
bool is_steady () const
time_point now () const
void set (time_point const &t)
void set (rep v)
manual_clock & operator++ ()
Public Member Functions inherited from beast::abstract_clock< Duration >
virtual ~abstract_clock ()
rep elapsed () const
Private Attributes
time_point m_now
Additional Inherited Members
Public Types inherited from beast::abstract_clock< Duration >
typedef Duration::rep rep
typedef Duration::period period
typedef Duration duration
typedef
std::chrono::time_point
< abstract_clock, duration > time_point
Detailed Description
template<class Duration, bool IsSteady = true>
class beast::manual_clock< Duration, IsSteady >
Manual clock implementation. This concrete class implements the abstract_clock interface and allows the time to be advanced manually, mainly for the purpose of providing a clock in unit tests.
Template Parameters
The length of time, in seconds, corresponding to one tick.
Definition at line 34 of file manual_clock.h.
Constructor & Destructor Documentation
template<class Duration, bool IsSteady = true> beast::manual_clock< Duration, IsSteady >::manual_clock (time_point const & t = time_point (Duration (0))) inline explicit
Definition at line 41 of file manual_clock.h.
         : m_now (t)
     {
     }
Member Function Documentation
template<class Duration, bool IsSteady = true> bool beast::manual_clock< Duration, IsSteady >::is_steady () const inline virtual
Returns true if this is a steady clock.
Implements beast::abstract_clock< Duration >.
Definition at line 46 of file manual_clock.h.
     {
         return IsSteady;
     }
template<class Duration, bool IsSteady = true> time_point beast::manual_clock< Duration, IsSteady >::now () const inline virtual
Returns the current time.
Implements beast::abstract_clock< Duration >.
Definition at line 51 of file manual_clock.h.
     {
         return m_now;
     }
template<class Duration, bool IsSteady = true> manual_clock& beast::manual_clock< Duration, IsSteady >::operator++ () inline
Convenience for advancing the clock by one.
Definition at line 82 of file manual_clock.h.
     {
         m_now += duration (1);
         return *this;
     }
template<class Duration, bool IsSteady = true> void beast::manual_clock< Duration, IsSteady >::set (time_point const & t) inline
Set the current time of the manual clock. Precondition: ! IsSteady || t > now()
Definition at line 69 of file manual_clock.h.
Referenced by ripple::KeyCache_test::run(), ripple::TaggedCache_test::run(), and beast::manual_clock< beast::abstract_clock::duration >::set().
     {
         //if (IsSteady)
         m_now = t;
     }
template<class Duration, bool IsSteady = true> void beast::manual_clock< Duration, IsSteady >::set (rep v) inline
Convenience for setting the time using a duration in rep units.
Definition at line 76 of file manual_clock.h.
     {
         set (time_point (duration (v)));
     }
Member Data Documentation
template<class Duration, bool IsSteady = true> time_point beast::manual_clock< Duration, IsSteady >::m_now private
Definition at line 89 of file manual_clock.h.
Referenced by beast::manual_clock< beast::abstract_clock::duration >::now(), beast::manual_clock< beast::abstract_clock::duration >::operator++(), and beast::manual_clock< beast::abstract_clock::duration >::set().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/chrono/manual_clock.h