rippled: beast::io_latency_probe< Clock >::sample_op< Handler > Struct Template Reference
beast::io_latency_probe< Clock >::sample_op< Handler > Struct Template Reference
Public Member Functions
sample_op (Handler const &handler, time_point const &start, bool repeat, io_latency_probe *probe)
sample_op (sample_op const &other)
~sample_op ()
void operator() () const
void operator() (boost::system::error_code const &ec)
Public Attributes
Handler m_handler
time_point m_start
bool m_repeat
io_latency_probe * m_probe
Detailed Description
template<class Clock>
template<class Handler>
struct beast::io_latency_probe< Clock >::sample_op< Handler >
Definition at line 161 of file io_latency_probe.h.
Constructor & Destructor Documentation
template<class Clock> template<class Handler > beast::io_latency_probe< Clock >::sample_op< Handler >::sample_op (Handler const & handler, time_point const & start, bool repeat, io_latency_probe * probe) inline
Definition at line 168 of file io_latency_probe.h.
References beast::io_latency_probe< Clock >::addref(), and beast::io_latency_probe< Clock >::sample_op< Handler >::m_probe.
             : m_handler (handler)
             , m_start (start)
             , m_repeat (repeat)
             , m_probe (probe)
         {
             m_probe->addref();
         }
template<class Clock> template<class Handler > beast::io_latency_probe< Clock >::sample_op< Handler >::sample_op (sample_op< Handler > const & other) inline
Definition at line 178 of file io_latency_probe.h.
References beast::io_latency_probe< Clock >::addref(), and beast::io_latency_probe< Clock >::sample_op< Handler >::m_probe.
             : m_handler (other.m_handler)
             , m_start (other.m_start)
             , m_probe (other.m_probe)
         {
             m_probe->addref();
         }
template<class Clock> template<class Handler > beast::io_latency_probe< Clock >::sample_op< Handler >::~sample_op () inline
Definition at line 186 of file io_latency_probe.h.
References beast::io_latency_probe< Clock >::sample_op< Handler >::m_probe, and beast::io_latency_probe< Clock >::release().
         {
             m_probe->release();
         }
Member Function Documentation
template<class Clock> template<class Handler > void beast::io_latency_probe< Clock >::sample_op< Handler >::operator() () const inline
Definition at line 191 of file io_latency_probe.h.
References beast::io_latency_probe< Clock >::m_cancel, beast::io_latency_probe< Clock >::sample_op< Handler >::m_handler, beast::io_latency_probe< Clock >::m_ios, beast::io_latency_probe< Clock >::m_mutex, beast::io_latency_probe< Clock >::m_period, beast::io_latency_probe< Clock >::sample_op< Handler >::m_probe, beast::io_latency_probe< Clock >::sample_op< Handler >::m_repeat, beast::io_latency_probe< Clock >::sample_op< Handler >::m_start, and beast::io_latency_probe< Clock >::m_timer.
         {
             typename Clock::time_point const now (Clock::now());
             typename Clock::duration const elapsed (now - m_start);
             m_handler (elapsed);
             {
                 std::lock_guard <decltype (m_probe->m_mutex)
                     > lock (m_probe->m_mutex);
                 if (m_probe->m_cancel)
                     return;
             }
             if (m_repeat)
             {
                 // Calculate when we want to sample again, and
                 // adjust for the expected latency.
                 //
                 typename Clock::time_point const when (
                     now + m_probe->m_period - 2 * elapsed);
                 if (when <= now)
                 {
                     // The latency is too high to maintain the desired
                     // period so don't bother with a timer.
                     //
                     m_probe->m_ios.post (sample_op <Handler> (
                         m_handler, now, m_repeat, m_probe));
                 }
                 else
                 {
                     boost::posix_time::microseconds mms (
                         std::chrono::duration_cast <
                             std::chrono::microseconds> (
                                 when - now).count ());
                     m_probe->m_timer.expires_from_now (mms);
                     m_probe->m_timer.async_wait (sample_op <Handler> (
                         m_handler, now, m_repeat, m_probe));
                 }
             }
         }
template<class Clock> template<class Handler > void beast::io_latency_probe< Clock >::sample_op< Handler >::operator() (boost::system::error_code const & ec) inline
Definition at line 234 of file io_latency_probe.h.
References beast::io_latency_probe< Clock >::sample_op< Handler >::m_handler, beast::io_latency_probe< Clock >::m_ios, beast::io_latency_probe< Clock >::sample_op< Handler >::m_probe, and beast::io_latency_probe< Clock >::sample_op< Handler >::m_repeat.
         {
             typename Clock::time_point const now (Clock::now());
             m_probe->m_ios.post (sample_op <Handler> (
                 m_handler, now, m_repeat, m_probe));
         }
Member Data Documentation
template<class Clock> template<class Handler > Handler beast::io_latency_probe< Clock >::sample_op< Handler >::m_handler
Definition at line 163 of file io_latency_probe.h.
Referenced by beast::io_latency_probe< Clock >::sample_op< Handler >::operator()().
template<class Clock> template<class Handler > io_latency_probe* beast::io_latency_probe< Clock >::sample_op< Handler >::m_probe
Definition at line 166 of file io_latency_probe.h.
Referenced by beast::io_latency_probe< Clock >::sample_op< Handler >::operator()(), beast::io_latency_probe< Clock >::sample_op< Handler >::sample_op(), and beast::io_latency_probe< Clock >::sample_op< Handler >::~sample_op().
template<class Clock> template<class Handler > bool beast::io_latency_probe< Clock >::sample_op< Handler >::m_repeat
Definition at line 165 of file io_latency_probe.h.
Referenced by beast::io_latency_probe< Clock >::sample_op< Handler >::operator()().
template<class Clock> template<class Handler > time_point beast::io_latency_probe< Clock >::sample_op< Handler >::m_start
Definition at line 164 of file io_latency_probe.h.
Referenced by beast::io_latency_probe< Clock >::sample_op< Handler >::operator()().
The documentation for this struct was generated from the following file:
rippled/src/beast/beast/asio/io_latency_probe.h