rippled: beast::RootStoppable Class Reference
beast::RootStoppable Class Reference
#include <Stoppable.h>
Public Member Functions
RootStoppable (char const *name)
~RootStoppable ()
bool isStopping () const
void prepare ()
void start ()
void stop (Journal journal=Journal())
void stopAsync ()
Public Member Functions inherited from beast::Stoppable
Stoppable (char const *name, Stoppable &parent)
virtual ~Stoppable ()
bool isStopping () const
bool isStopped () const
bool areChildrenStopped () const
void stopped ()
virtual void onPrepare ()
virtual void onStart ()
virtual void onStop ()
virtual void onChildrenStopped ()
Private Attributes
Atomic< int > m_prepared
Atomic< int > m_calledStop
Atomic< int > m_calledStopAsync
Additional Inherited Members
Protected Member Functions inherited from beast::Stoppable
Stoppable (char const *name, RootStoppable &root)
Protected Attributes inherited from beast::Stoppable
char const * m_name
RootStoppable & m_root
Child m_child
Atomic< int > m_started
bool volatile m_stopped
bool volatile m_childrenStopped
Children m_children
WaitableEvent m_stoppedEvent
Detailed Description
Definition at line 277 of file Stoppable.h.
Constructor & Destructor Documentation
beast::RootStoppable::RootStoppable (char const * name) explicit
Definition at line 144 of file Stoppable.cpp.
     : Stoppable (name, *this)
 {
 }
beast::RootStoppable::~RootStoppable ()
Definition at line 149 of file Stoppable.cpp.
 {
 }
Member Function Documentation
bool beast::RootStoppable::isStopping () const
Definition at line 153 of file Stoppable.cpp.
References beast::Atomic< Type >::get(), and m_calledStopAsync.
Referenced by beast::Stoppable::isStopping().
 {
     return m_calledStopAsync.get() != 0;
 }
void beast::RootStoppable::prepare ()
Prepare all contained Stoppable objects. This calls onPrepare for all Stoppable objects in the tree. Calls made after the first have no effect. Thread safety: May be called from any thread.
Definition at line 158 of file Stoppable.cpp.
References beast::Atomic< Type >::compareAndSetBool(), m_prepared, and beast::Stoppable::prepareRecursive().
Referenced by ripple::ApplicationImp::run().
 {
     if (! m_prepared.compareAndSetBool (1, 0))
         return;
     prepareRecursive ();
 }
void beast::RootStoppable::start ()
Start all contained Stoppable objects. The default implementation does nothing. Calls made after the first have no effect. Thread safety: May be called from any thread.
Definition at line 166 of file Stoppable.cpp.
References beast::Atomic< Type >::compareAndSetBool(), m_prepared, beast::Stoppable::m_started, beast::Stoppable::prepareRecursive(), and beast::Stoppable::startRecursive().
Referenced by ripple::ApplicationImp::run().
 {
     // Courtesy call to prepare.
     if (m_prepared.compareAndSetBool (1, 0))
         prepareRecursive ();
     if (! m_started.compareAndSetBool (1, 0))
         return;
     startRecursive ();
 }
void beast::RootStoppable::stop (Journal journal = Journal())
Notify a root stoppable and children to stop, and block until stopped. Has no effect if the stoppable was already notified. This blocks until the stoppable and all of its children have stopped. Undefined behavior results if stop() is called without a previous call to start(). Thread safety: Safe to call from any thread not associated with a Stoppable.
Definition at line 178 of file Stoppable.cpp.
References bassert, beast::Atomic< Type >::compareAndSetBool(), beast::Atomic< Type >::get(), m_calledStop, beast::Stoppable::m_started, stopAsync(), beast::Stoppable::stopRecursive(), and beast::Journal::warning.
Referenced by ripple::ApplicationImp::doStop().
 {
     // Must have a prior call to start()
     bassert (m_started.get() != 0);
     if (! m_calledStop.compareAndSetBool (1, 0))
     {
         journal.warning << "Stoppable::stop called again";
         return;
     }
     stopAsync ();
     stopRecursive (journal);
 }
void beast::RootStoppable::stopAsync ()
Notify a root stoppable and children to stop, without waiting. Has no effect if the stoppable was already notified.
Thread safety: Safe to call from any thread at any time.
Definition at line 193 of file Stoppable.cpp.
References beast::Atomic< Type >::compareAndSetBool(), m_calledStopAsync, and beast::Stoppable::stopAsyncRecursive().
Referenced by stop().
 {
     if (! m_calledStopAsync.compareAndSetBool (1, 0))
         return;
     stopAsyncRecursive ();
 }
Member Data Documentation
Atomic<int> beast::RootStoppable::m_calledStop private
Definition at line 322 of file Stoppable.h.
Referenced by stop().
Atomic<int> beast::RootStoppable::m_calledStopAsync private
Definition at line 323 of file Stoppable.h.
Referenced by isStopping(), and stopAsync().
Atomic<int> beast::RootStoppable::m_prepared private
Definition at line 321 of file Stoppable.h.
Referenced by prepare(), and start().
The documentation for this class was generated from the following files:
rippled/src/beast/beast/threads/Stoppable.h
rippled/src/beast/beast/threads/impl/Stoppable.cpp