rippled: beast::detail::spooky_wrapper Class Reference
beast::detail::spooky_wrapper Class Reference
#include <hash_append.h>
Public Types
using result_type = std::size_t
Public Member Functions
spooky_wrapper (std::size_t seed1=1, std::size_t seed2=2) noexcept
void append (void const *key, std::size_t len) noexcept
operator std::size_t () noexcept
Private Attributes
SpookyHash state_
Detailed Description
Definition at line 662 of file hash_append.h.
Member Typedef Documentation
using beast::detail::spooky_wrapper::result_type = std::size_t
Definition at line 666 of file hash_append.h.
Constructor & Destructor Documentation
beast::detail::spooky_wrapper::spooky_wrapper (std::size_t seed1 = 1, std::size_t seed2 = 2) inline noexcept
Definition at line 668 of file hash_append.h.
References SpookyHash::Init(), and state_.
     {
         state_.Init (seed1, seed2);
     }
Member Function Documentation
void beast::detail::spooky_wrapper::append (void const * key, std::size_t len) inline noexcept
Definition at line 674 of file hash_append.h.
References state_, and SpookyHash::Update().
     {
         state_.Update (key, len);
     }
beast::detail::spooky_wrapper::operator std::size_t () inline explicit noexcept
Definition at line 680 of file hash_append.h.
References SpookyHash::Final(), and state_.
     {
         std::uint64_t h1, h2;
         state_.Final (&h1, &h2);
         return static_cast <std::size_t> (h1);
     }
Member Data Documentation
SpookyHash beast::detail::spooky_wrapper::state_ private
Definition at line 664 of file hash_append.h.
Referenced by append(), operator std::size_t(), and spooky_wrapper().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/container/hash_append.h