rippled: beast::asio::boost_bind_test Class Reference
beast::asio::boost_bind_test Class Reference
Classes
struct Arg
struct Payload
struct Result
Public Member Functions
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Static Public Member Functions
static void foo (Arg const &, Arg const &, Arg const &)
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 41 of file wrap_handler.test.cpp.
Member Function Documentation
static void beast::asio::boost_bind_test::foo (Arg const & , Arg const & , Arg const &) inline static
Definition at line 83 of file wrap_handler.test.cpp.
Referenced by run().
     {
     }
void beast::asio::boost_bind_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 87 of file wrap_handler.test.cpp.
References foo(), beast::unit_test::suite::log, beast::unit_test::suite::pass(), and beast::asio::boost_bind_test::Result::text.
     {
         {
             Result r;
             {
                 boost::bind (&foo,
                     Arg (r, "one"),
                     Arg (r, "two"),
                     Arg (r, "three"));
             }
             log <<
                 std::string ("boost::bind (") + r.text + ")";
         }
         {
             Result r;
             {
                 std::bind (&foo,
                     Arg (r, "one"),
                     Arg (r, "two"),
                     Arg (r, "three"));
             }
             log <<
                 std::string ("std::bind (") + r.text + ")";
         }
         pass();
     }
The documentation for this class was generated from the following file:
rippled/src/beast/beast/asio/tests/wrap_handler.test.cpp