rippled: ripple::SiteFiles::Logic Class Reference
ripple::SiteFiles::Logic Class Reference
#include <Logic.h>
Classes
struct State
Public Types
typedef std::set< Listener * > Listeners
typedef ripple::unordered_map
< beast::URL, SiteFile > SiteFiles
typedef beast::SharedData< State > SharedState
Public Member Functions
Logic (beast::Journal journal)
~Logic ()
void addListener (Listener &listener)
void removeListener (Listener &listener)
void addURL (std::string const &urlstr)
void processResponse (beast::URL const &url, beast::HTTPResponse const &response)
template<typename BidirectionalIterator >
void parse (SiteFile &siteFile, BidirectionalIterator start, BidirectionalIterator end)
void parse (SiteFile &siteFile, beast::HTTPResponse const &response)
Static Public Member Functions
static boost::regex const & reHeader ()
static boost::regex const & reData ()
Public Attributes
SharedState m_state
beast::Journal m_journal
std::unique_ptr
< beast::asio::HTTPClientBase > m_client
Detailed Description
Definition at line 61 of file Logic.h.
Member Typedef Documentation
typedef std::set<Listener*> ripple::SiteFiles::Logic::Listeners
Definition at line 64 of file Logic.h.
typedef beast::SharedData<State> ripple::SiteFiles::Logic::SharedState
Definition at line 77 of file Logic.h.
typedef ripple::unordered_map<beast::URL, SiteFile> ripple::SiteFiles::Logic::SiteFiles
Definition at line 65 of file Logic.h.
Constructor & Destructor Documentation
ripple::SiteFiles::Logic::Logic (beast::Journal journal) inline explicit
Definition at line 83 of file Logic.h.
         : m_journal (journal)
         , m_client (beast::asio::HTTPClientBase::New (journal))
     {
     }
ripple::SiteFiles::Logic::~Logic () inline
Definition at line 89 of file Logic.h.
     {
     }
Member Function Documentation
void ripple::SiteFiles::Logic::addListener (Listener & listener) inline
Definition at line 99 of file Logic.h.
References m_state, and ripple::SiteFiles::Listener::onSiteFileFetch().
Referenced by ripple::SiteFiles::ManagerImp::addListener().
     {
         SharedState::Access state (m_state);
         // Notify the listener for each site file already added
         for (SiteFiles::const_iterator iter (state->files.begin());
             iter != state->files.end(); ++iter)
         {
             listener.onSiteFileFetch (iter->first.to_string(), iter->second);
         }
         state->listeners.insert (&listener);
     }
void ripple::SiteFiles::Logic::addURL (std::string const & urlstr) inline
Definition at line 119 of file Logic.h.
References beast::ParsedURL::error(), beast::Journal::error, m_client, m_journal, processResponse(), and beast::ParsedURL::url().
Referenced by ripple::SiteFiles::ManagerImp::addURL().
     {
         beast::ParsedURL const p (urlstr);
         if (p.error())
         {
             m_journal.error <<
                 "Error parsing '" << urlstr << "'";
             return;
         }
         beast::URL const& url (p.url());
         auto const result (m_client->get (url));
         //---
         boost::system::error_code const error (result.first);
         if (error)
         {
             m_journal.error
                 << "HTTP GET '" << url <<
                 "' failed: " << error.message();
             return;
         }
         beast::HTTPResponse const& response (*result.second);
         processResponse (url, response);
     }
template<typename BidirectionalIterator > void ripple::SiteFiles::Logic::parse (SiteFile & siteFile, BidirectionalIterator start, BidirectionalIterator end) inline
Definition at line 262 of file Logic.h.
References ripple::SiteFiles::SiteFile::insert(), reData(), and reHeader().
Referenced by parse(), and processResponse().
     {
         Section* section (&siteFile.insert (""));
         boost::match_results <BidirectionalIterator> m;
         for (;start != end;)
         {
             if (boost::regex_search (start, end, m, reHeader(),
                 boost::regex_constants::match_continuous))
             {
                 std::string const& s (m[1]);
                 section = &siteFile.insert (s);
             }
             else
             {
                 boost::regex_search (start, end, m, reData(),
                                      boost::regex_constants::match_continuous);
                 std::string const& s (m[1]);
                 section->push_back (s);
             }
             start = m[0].second;
         }
     }
void ripple::SiteFiles::Logic::parse (SiteFile & siteFile, beast::HTTPResponse const & response) inline
Definition at line 291 of file Logic.h.
References beast::HTTPMessage::body(), parse(), and beast::DynamicBuffer::to_string().
     {
         std::string const s (response.body().to_string());
         parse (siteFile, s.begin(), s.end());
     }
void ripple::SiteFiles::Logic::processResponse (beast::URL const & url, beast::HTTPResponse const & response) inline
Definition at line 157 of file Logic.h.
References beast::Journal::error, m_journal, m_state, ripple::SiteFiles::Listener::onSiteFileFetch(), parse(), and beast::URL::to_string().
Referenced by addURL().
     {
         SharedState::Access state (m_state);
         std::pair <SiteFiles::iterator, bool> result (
             state->files.emplace (url, 0));
         if (! result.second)
         {
             m_journal.error <<
                 "Duplicate URL '" << url << "' ignored";
             return;
         }
         SiteFile& siteFile (result.first->second);
         parse (siteFile, response);
         for (Listeners::iterator iter (state->listeners.begin());
             iter != state->listeners.end(); ++iter)
         {
             Listener* const listener (*iter);
             listener->onSiteFileFetch (url.to_string(), siteFile);
         }
     }
static boost::regex const& ripple::SiteFiles::Logic::reData () inline static
Definition at line 249 of file Logic.h.
Referenced by parse().
     {
         static boost::regex re (
             "(?:\\h*(?:#\\V*)?\\v)*"    //      Zero or more comments
             "(\\V*)"                    // [1]  Rest of the line
             "(?:\\h*(?:#\\V*)?\\v)*"    //      Zero or more comments
             ,   boost::regex::perl
         );
         return re;
     }
static boost::regex const& ripple::SiteFiles::Logic::reHeader () inline static
Definition at line 232 of file Logic.h.
Referenced by parse().
     {
         static boost::regex re (
             "(?:\\h*(?:#\\V*)?\\v)*"    //      Zero or more comments
             "(?:\\v*)"                  //      Line break (optional)
             "(?:\\h*)"                  //      Horizontal whitespace (optional)
             "(?:\\[)"                   //      Open bracket
             "([^\\]]*)"                 // [1]  Everything between the brackets
             "(?:\\])"                   //      Close bracket
             "(?:\\V*)"                  //      Rest of the line
             "(?:\\h*(?:#\\V*)?\\v)*"    //      Zero or more comments
             , boost::regex::perl
         );
         return re;
     }
void ripple::SiteFiles::Logic::removeListener (Listener & listener) inline
Definition at line 113 of file Logic.h.
References m_state.
Referenced by ripple::SiteFiles::ManagerImp::removeListener().
     {
         SharedState::Access state (m_state);
         state->listeners.erase (&listener);
     }
Member Data Documentation
std::unique_ptr<beast::asio::HTTPClientBase> ripple::SiteFiles::Logic::m_client
Definition at line 81 of file Logic.h.
Referenced by addURL().
beast::Journal ripple::SiteFiles::Logic::m_journal
Definition at line 80 of file Logic.h.
Referenced by addURL(), and processResponse().
SharedState ripple::SiteFiles::Logic::m_state
Definition at line 79 of file Logic.h.
Referenced by addListener(), processResponse(), and removeListener().
The documentation for this class was generated from the following file:
rippled/src/ripple/sitefiles/impl/Logic.h