rippled: ripple::HTTP Namespace Reference
ripple::HTTP Namespace Reference
Classes
struct Handler
struct Port
class ScopedStream
class Server
class Session
class Door
class Peer
class ServerImpl
Typedefs
typedef std::vector< Port > Ports
typedef beast::asio::SharedArg
< std::string > SharedBuffer
typedef boost::system::error_code error_code
typedef boost::asio::ip::tcp Protocol
typedef boost::asio::ip::address address
typedef Protocol::endpoint endpoint_t
typedef Protocol::acceptor acceptor
typedef Protocol::socket socket
Functions
bool operator== (Port const &lhs, Port const &rhs)
bool operator!= (Port const &lhs, Port const &rhs)
bool operator< (Port const &lhs, Port const &rhs)
bool operator<= (Port const &lhs, Port const &rhs)
bool operator> (Port const &lhs, Port const &rhs)
bool operator>= (Port const &lhs, Port const &rhs)
std::string to_string (address const &addr)
std::string to_string (endpoint_t const &endpoint)
endpoint_t to_asio (Port const &port)
beast::IP::Endpoint from_asio (endpoint_t const &endpoint)
Typedef Documentation
typedef Protocol::acceptor ripple::HTTP::acceptor
Definition at line 30 of file Types.h.
typedef boost::asio::ip::address ripple::HTTP::address
Definition at line 28 of file Types.h.
typedef Protocol::endpoint ripple::HTTP::endpoint_t
Definition at line 29 of file Types.h.
typedef boost::system::error_code ripple::HTTP::error_code
Definition at line 26 of file Types.h.
typedef std::vector<Port> ripple::HTTP::Ports
A set of listening ports settings.
Definition at line 57 of file Port.h.
typedef boost::asio::ip::tcp ripple::HTTP::Protocol
Definition at line 27 of file Types.h.
typedef beast::asio::SharedArg<std::string> ripple::HTTP::SharedBuffer
Definition at line 31 of file Peer.h.
typedef Protocol::socket ripple::HTTP::socket
Definition at line 31 of file Types.h.
Function Documentation
beast::IP::Endpoint ripple::HTTP::from_asio (endpoint_t const & endpoint) inline
Definition at line 60 of file Types.h.
References to_string().
Referenced by ripple::HTTP::Peer::remoteAddress().
 {
     std::stringstream ss (to_string (endpoint));
     beast::IP::Endpoint ep;
     ss >> ep;
     return ep;
 }
bool ripple::HTTP::operator!= (Port const & lhs, Port const & rhs)
Definition at line 91 of file Port.cpp.
     { return ! (lhs == rhs); }
bool ripple::HTTP::operator< (Port const & lhs, Port const & rhs)
Definition at line 71 of file Port.cpp.
References ripple::HTTP::Port::addr, ripple::HTTP::Port::port, and ripple::HTTP::Port::security.
 {
     if (lhs.addr > rhs.addr)
         return false;
     else if (lhs.addr < rhs.addr)
         return true;
     if (lhs.port > rhs.port)
         return false;
     else if (lhs.port < rhs.port)
         return true;
     if (lhs.security > rhs.security)
         return false;
     else if (lhs.security < rhs.security)
         return true;
     return true;
 }
bool ripple::HTTP::operator<= (Port const & lhs, Port const & rhs)
Definition at line 97 of file Port.cpp.
References lhs.
     { return ! (rhs < lhs); }
bool ripple::HTTP::operator== (Port const & lhs, Port const & rhs)
Definition at line 59 of file Port.cpp.
References ripple::HTTP::Port::addr, ripple::HTTP::Port::port, and ripple::HTTP::Port::security.
 {
     if (lhs.addr != rhs.addr)
         return false;
     if (lhs.port != rhs.port)
         return false;
     if (lhs.security != rhs.security)
         return false;
     // 'context' does not participate in the comparison
     return true;
 }
bool ripple::HTTP::operator> (Port const & lhs, Port const & rhs)
Definition at line 94 of file Port.cpp.
References lhs.
     { return rhs < lhs; }
bool ripple::HTTP::operator>= (Port const & lhs, Port const & rhs)
Definition at line 100 of file Port.cpp.
     { return ! (lhs < rhs); }
endpoint_t ripple::HTTP::to_asio (Port const & port) inline
Definition at line 47 of file Types.h.
References ripple::HTTP::Port::addr, beast::IP::Endpoint::is_v4(), ripple::HTTP::Port::port, to_string(), and beast::IP::Endpoint::to_v4().
 {
     if (port.addr.is_v4())
     {
         beast::IP::AddressV4 v4 (port.addr.to_v4());
         std::string const& s (to_string (v4));
         return endpoint_t (address().from_string (s), port.port);
     }
     //IP::Endpoint::V6 v6 (ep.v6());
     return endpoint_t ();
 }
std::string ripple::HTTP::to_string (address const & addr) inline
Definition at line 33 of file Types.h.
Referenced by ripple::HTTP::Door::Door(), from_asio(), to_asio(), and to_string().
 {
     return addr.to_string();
 }
std::string ripple::HTTP::to_string (endpoint_t const & endpoint) inline
Definition at line 38 of file Types.h.
References to_string().
 {
     std::stringstream ss;
     ss << to_string (endpoint.address());
     if (endpoint.port() != 0)
         ss << ":" << std::dec << endpoint.port();
     return std::string (ss.str());
 }