rippled: ripple::SerializedLedgerEntry Class Reference
ripple::SerializedLedgerEntry Class Reference
#include <SerializedLedger.h>
Public Types
typedef boost::shared_ptr
< SerializedLedgerEntry > pointer
typedef const
boost::shared_ptr
< SerializedLedgerEntry > & ref
Public Types inherited from ripple::STObject
typedef boost::ptr_vector
< SerializedType >::iterator iterator
typedef boost::ptr_vector
< SerializedType >
::const_iterator const_iterator
Public Member Functions
SerializedLedgerEntry (const Serializer &s, uint256 const &index)
SerializedLedgerEntry (SerializerIterator &sit, uint256 const &index)
SerializedLedgerEntry (LedgerEntryType type, uint256 const &index)
SerializedTypeID getSType () const
std::string getFullText () const
std::string getText () const
Json::Value getJson (int options) const
uint256 const & getIndex () const
void setIndex (uint256 const &i)
void setImmutable ()
bool isMutable ()
SerializedLedgerEntry::pointer getMutable () const
LedgerEntryType getType () const
std::uint16_t getVersion () const
LedgerFormats::Item const * getFormat ()
bool isThreadedType ()
bool isThreaded ()
bool hasOneOwner ()
bool hasTwoOwners ()
RippleAddress getOwner ()
RippleAddress getFirstOwner ()
RippleAddress getSecondOwner ()
uint256 getThreadedTransaction ()
std::uint32_t getThreadedLedger ()
bool thread (uint256 const &txID, std::uint32_t ledgerSeq, uint256 &prevTxID, std::uint32_t &prevLedgerID)
std::vector< uint256 > getOwners ()
Public Member Functions inherited from ripple::STObject
STObject ()
STObject (SField::ref name)
STObject (const SOTemplate &type, SField::ref name)
STObject (const SOTemplate &type, SerializerIterator &sit, SField::ref name)
STObject (SField::ref name, boost::ptr_vector< SerializedType > &data)
std::unique_ptr< STObject > oClone () const
virtual ~STObject ()
bool setType (const SOTemplate &type)
bool isValidForType ()
bool isFieldAllowed (SField::ref)
bool isFree () const
void set (const SOTemplate &)
bool set (SerializerIterator &u, int depth=0)
virtual bool isEquivalent (const SerializedType &t) const
virtual bool isDefault () const
virtual void add (Serializer &s) const
void add (Serializer &s, bool withSignature) const
Serializer getSerializer () const
std::string getFullText () const
std::string getText () const
int addObject (const SerializedType &t)
int giveObject (std::unique_ptr< SerializedType > t)
int giveObject (SerializedType *t)
const boost::ptr_vector
< SerializedType > & peekData () const
boost::ptr_vector
< SerializedType > & peekData ()
SerializedType & front ()
const SerializedType & front () const
SerializedType & back ()
const SerializedType & back () const
int getCount () const
bool setFlag (std::uint32_t)
bool clearFlag (std::uint32_t)
bool isFlag (std::uint32_t) const
std::uint32_t getFlags () const
uint256 getHash (std::uint32_t prefix) const
uint256 getSigningHash (std::uint32_t prefix) const
const SerializedType & peekAtIndex (int offset) const
SerializedType & getIndex (int offset)
const SerializedType * peekAtPIndex (int offset) const
SerializedType * getPIndex (int offset)
int getFieldIndex (SField::ref field) const
SField::ref getFieldSType (int index) const
const SerializedType & peekAtField (SField::ref field) const
SerializedType & getField (SField::ref field)
const SerializedType * peekAtPField (SField::ref field) const
SerializedType * getPField (SField::ref field, bool createOkay=false)
std::string getFieldString (SField::ref field) const
unsigned char getFieldU8 (SField::ref field) const
std::uint16_t getFieldU16 (SField::ref field) const
std::uint32_t getFieldU32 (SField::ref field) const
std::uint64_t getFieldU64 (SField::ref field) const
uint128 getFieldH128 (SField::ref field) const
uint160 getFieldH160 (SField::ref field) const
uint256 getFieldH256 (SField::ref field) const
RippleAddress getFieldAccount (SField::ref field) const
uint160 getFieldAccount160 (SField::ref field) const
Blob getFieldVL (SField::ref field) const
const STAmount & getFieldAmount (SField::ref field) const
const STPathSet & getFieldPathSet (SField::ref field) const
const STVector256 & getFieldV256 (SField::ref field) const
const STArray & getFieldArray (SField::ref field) const
void setFieldU8 (SField::ref field, unsigned char)
void setFieldU16 (SField::ref field, std::uint16_t)
void setFieldU32 (SField::ref field, std::uint32_t)
void setFieldU64 (SField::ref field, std::uint64_t)
void setFieldH128 (SField::ref field, const uint128 &)
void setFieldH160 (SField::ref field, const uint160 &)
void setFieldH256 (SField::ref field, uint256 const &)
void setFieldVL (SField::ref field, Blob const &)
void setFieldAccount (SField::ref field, const uint160 &)
void setFieldAccount (SField::ref field, const RippleAddress &addr)
void setFieldAmount (SField::ref field, const STAmount &)
void setFieldPathSet (SField::ref field, const STPathSet &)
void setFieldV256 (SField::ref field, const STVector256 &v)
STObject & peekFieldObject (SField::ref field)
bool isFieldPresent (SField::ref field) const
SerializedType * makeFieldPresent (SField::ref field)
void makeFieldAbsent (SField::ref field)
bool delField (SField::ref field)
void delField (int index)
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
bool empty () const
bool hasMatchingEntry (const SerializedType &)
bool operator== (const STObject &o) const
bool operator!= (const STObject &o) const
Public Member Functions inherited from ripple::SerializedType
SerializedType ()
SerializedType (SField::ref n)
virtual ~SerializedType ()
void setFName (SField::ref n)
SField::ref getFName () const
std::string getName () const
std::unique_ptr< SerializedType > clone () const
void addFieldID (Serializer &s) const
SerializedType & operator= (const SerializedType &t)
bool operator== (const SerializedType &t) const
bool operator!= (const SerializedType &t) const
template<class D >
D & downcast ()
template<class D >
D const & downcast () const
Public Member Functions inherited from ripple::CountedObject< STObject >
CountedObject ()
CountedObject (CountedObject const &)
~CountedObject ()
Public Member Functions inherited from ripple::CountedObject< SerializedLedgerEntry >
CountedObject ()
CountedObject (CountedObject const &)
~CountedObject ()
Static Public Member Functions
static char const * getCountedObjectName ()
Static Public Member Functions inherited from ripple::STObject
static char const * getCountedObjectName ()
static std::unique_ptr
< SerializedType > deserialize (SerializerIterator &sit, SField::ref name)
static std::unique_ptr
< SerializedType > makeDefaultObject (SerializedTypeID id, SField::ref name)
static std::unique_ptr
< SerializedType > makeDeserializedObject (SerializedTypeID id, SField::ref name, SerializerIterator &, int depth)
static std::unique_ptr
< SerializedType > makeNonPresentObject (SField::ref name)
static std::unique_ptr
< SerializedType > makeDefaultObject (SField::ref name)
Static Public Member Functions inherited from ripple::SerializedType
static std::unique_ptr
< SerializedType > deserialize (SField::ref name)
Private Member Functions
SerializedLedgerEntry * duplicate () const
Private Attributes
uint256 mIndex
LedgerEntryType mType
LedgerFormats::Item const * mFormat
bool mMutable
Additional Inherited Members
Protected Attributes inherited from ripple::SerializedType
SField::ptr fName
Detailed Description
Definition at line 40 of file SerializedLedger.h.
Member Typedef Documentation
typedef boost::shared_ptr<SerializedLedgerEntry> ripple::SerializedLedgerEntry::pointer
Definition at line 47 of file SerializedLedger.h.
typedef const boost::shared_ptr<SerializedLedgerEntry>& ripple::SerializedLedgerEntry::ref
Definition at line 48 of file SerializedLedger.h.
Constructor & Destructor Documentation
ripple::SerializedLedgerEntry::SerializedLedgerEntry (const Serializer & s, uint256 const & index)
Definition at line 44 of file SerializedLedger.cpp.
References ripple::KnownFormats< KeyType >::findByType(), ripple::STObject::getFieldU16(), ripple::LedgerFormats::getInstance(), getJson(), ripple::lsWARNING, mFormat, mType, ripple::STObject::set(), ripple::STObject::setType(), and WriteLog.
Referenced by duplicate().
     : STObject (sfLedgerEntry), mIndex (index), mMutable (true)
 {
     SerializerIterator sit (const_cast<Serializer&> (s)); // we know 's' isn't going away
     set (sit);
     std::uint16_t type = getFieldU16 (sfLedgerEntryType);
     LedgerFormats::Item const* const item =
         LedgerFormats::getInstance()->findByType (static_cast <LedgerEntryType> (type));
     if (item == nullptr)
         throw std::runtime_error ("invalid ledger entry type");
     mType = item->getType ();
     if (!setType (item->elements))
     {
         WriteLog (lsWARNING, SerializedLedgerLog) << "Ledger entry not valid for type " << mFormat->getName ();
         WriteLog (lsWARNING, SerializedLedgerLog) << getJson (0);
         throw std::runtime_error ("ledger entry not valid for type");
     }
 }
ripple::SerializedLedgerEntry::SerializedLedgerEntry (SerializerIterator & sit, uint256 const & index)
Definition at line 26 of file SerializedLedger.cpp.
References ripple::KnownFormats< KeyType >::findByType(), and ripple::LedgerFormats::getInstance().
     : STObject (sfLedgerEntry), mIndex (index), mMutable (true)
 {
     set (sit);
     std::uint16_t type = getFieldU16 (sfLedgerEntryType);
     LedgerFormats::Item const* const item =
         LedgerFormats::getInstance()->findByType (static_cast <LedgerEntryType> (type));
     if (item == nullptr)
         throw std::runtime_error ("invalid ledger entry type");
     mType = item->getType ();
     if (!setType (item->elements))
         throw std::runtime_error ("ledger entry not valid for type");
 }
ripple::SerializedLedgerEntry::SerializedLedgerEntry (LedgerEntryType type, uint256 const & index)
Definition at line 68 of file SerializedLedger.cpp.
References ripple::KnownFormats< KeyType >::findByType(), ripple::LedgerFormats::getInstance(), ripple::STObject::set(), and ripple::STObject::setFieldU16().
                                                                                         :
     STObject (sfLedgerEntry), mIndex (index), mType (type), mMutable (true)
 {
     LedgerFormats::Item const* const item =
         LedgerFormats::getInstance()->findByType (type);
     if (item != nullptr)
     {
         set (item->elements);
         setFieldU16 (sfLedgerEntryType, static_cast <std::uint16_t> (item->getType ()));
     }
     else
     {
         throw std::runtime_error ("invalid ledger entry type");
     }
 }
Member Function Documentation
SerializedLedgerEntry* ripple::SerializedLedgerEntry::duplicate () const inline private virtual
Reimplemented from ripple::SerializedType.
Definition at line 109 of file SerializedLedger.h.
References SerializedLedgerEntry().
     {
         return new SerializedLedgerEntry (*this);
     }
static char const* ripple::SerializedLedgerEntry::getCountedObjectName () inline static
Definition at line 45 of file SerializedLedger.h.
 { return "SerializedLedgerEntry"; }
RippleAddress ripple::SerializedLedgerEntry::getFirstOwner ()
Definition at line 176 of file SerializedLedger.cpp.
References ripple::RippleAddress::createAccountID(), and ripple::STObject::getFieldAmount().
 {
     return RippleAddress::createAccountID (getFieldAmount (sfLowLimit).getIssuer ());
 }
LedgerFormats::Item const* ripple::SerializedLedgerEntry::getFormat () inline
Definition at line 90 of file SerializedLedger.h.
References mFormat.
     {
         return mFormat;
     }
std::string ripple::SerializedLedgerEntry::getFullText () const virtual
Reimplemented from ripple::SerializedType.
Definition at line 93 of file SerializedLedger.cpp.
References ripple::STObject::getFullText(), ripple::base_uint< BITS >::GetHex(), mFormat, and mIndex.
 {
     std::string ret = "\"";
     ret += mIndex.GetHex ();
     ret += "\" = { ";
     ret += mFormat->getName ();
     ret += ", ";
     ret += STObject::getFullText ();
     ret += "}";
     return ret;
 }
uint256 const& ripple::SerializedLedgerEntry::getIndex () const inline
Definition at line 63 of file SerializedLedger.h.
References mIndex.
     {
         return mIndex;
     }
Json::Value ripple::SerializedLedgerEntry::getJson (int options) const virtual
Reimplemented from ripple::STObject.
Definition at line 112 of file SerializedLedger.cpp.
References ripple::base_uint< BITS >::GetHex(), ripple::STObject::getJson(), and mIndex.
Referenced by SerializedLedgerEntry().
 {
     Json::Value ret (STObject::getJson (options));
     ret["index"]    = mIndex.GetHex ();
     return ret;
 }
SerializedLedgerEntry::pointer ripple::SerializedLedgerEntry::getMutable () const
Definition at line 86 of file SerializedLedger.cpp.
 {
     SerializedLedgerEntry::pointer ret = boost::make_shared<SerializedLedgerEntry> (boost::cref (*this));
     ret->mMutable = true;
     return ret;
 }
RippleAddress ripple::SerializedLedgerEntry::getOwner ()
Definition at line 171 of file SerializedLedger.cpp.
References ripple::STObject::getFieldAccount().
 {
     return getFieldAccount (sfAccount);
 }
std::vector< uint256 > ripple::SerializedLedgerEntry::getOwners ()
Definition at line 186 of file SerializedLedger.cpp.
References ripple::Ledger::getAccountRootIndex(), ripple::STObject::getCount(), ripple::STObject::getFieldSType(), ripple::STAmount::getIssuer(), ripple::STAccount::getValueH160(), ripple::base_uint< BITS >::isNonZero(), and ripple::STObject::peekAtPIndex().
 {
     std::vector<uint256> owners;
     uint160 account;
     for (int i = 0, fields = getCount (); i < fields; ++i)
     {
         SField::ref fc = getFieldSType (i);
         if ((fc == sfAccount) || (fc == sfOwner))
         {
             const STAccount* entry = dynamic_cast<const STAccount*> (peekAtPIndex (i));
             if ((entry != nullptr) && entry->getValueH160 (account))
                 owners.push_back (Ledger::getAccountRootIndex (account));
         }
         if ((fc == sfLowLimit) || (fc == sfHighLimit))
         {
             const STAmount* entry = dynamic_cast<const STAmount*> (peekAtPIndex (i));
             if ((entry != nullptr))
             {
                 uint160 issuer = entry->getIssuer ();
                 if (issuer.isNonZero ())
                     owners.push_back (Ledger::getAccountRootIndex (issuer));
             }
         }
     }
     return owners;
 }
RippleAddress ripple::SerializedLedgerEntry::getSecondOwner ()
Definition at line 181 of file SerializedLedger.cpp.
References ripple::RippleAddress::createAccountID(), and ripple::STObject::getFieldAmount().
 {
     return RippleAddress::createAccountID (getFieldAmount (sfHighLimit).getIssuer ());
 }
SerializedTypeID ripple::SerializedLedgerEntry::getSType () const inline virtual
Reimplemented from ripple::STObject.
Definition at line 55 of file SerializedLedger.h.
References ripple::STI_LEDGERENTRY.
     {
         return STI_LEDGERENTRY;
     }
std::string ripple::SerializedLedgerEntry::getText () const virtual
Reimplemented from ripple::SerializedType.
Definition at line 105 of file SerializedLedger.cpp.
References ripple::base_uint< BITS >::GetHex(), ripple::STObject::getText(), and mIndex.
 {
     return str (boost::format ("{ %s, %s }")
                 % mIndex.GetHex ()
                 % STObject::getText ());
 }
std::uint32_t ripple::SerializedLedgerEntry::getThreadedLedger ()
Definition at line 136 of file SerializedLedger.cpp.
References ripple::STObject::getFieldU32().
 {
     return getFieldU32 (sfPreviousTxnLgrSeq);
 }
uint256 ripple::SerializedLedgerEntry::getThreadedTransaction ()
Definition at line 131 of file SerializedLedger.cpp.
References ripple::STObject::getFieldH256().
 {
     return getFieldH256 (sfPreviousTxnID);
 }
LedgerEntryType ripple::SerializedLedgerEntry::getType () const inline
Definition at line 82 of file SerializedLedger.h.
References mType.
     {
         return mType;
     }
std::uint16_t ripple::SerializedLedgerEntry::getVersion () const inline
Definition at line 86 of file SerializedLedger.h.
References ripple::STObject::getFieldU16().
     {
         return getFieldU16 (sfLedgerEntryType);
     }
bool ripple::SerializedLedgerEntry::hasOneOwner ()
Definition at line 161 of file SerializedLedger.cpp.
References ripple::STObject::getFieldIndex(), ripple::ltACCOUNT_ROOT, and mType.
 {
     return (mType != ltACCOUNT_ROOT) && (getFieldIndex (sfAccount) != -1);
 }
bool ripple::SerializedLedgerEntry::hasTwoOwners ()
Definition at line 166 of file SerializedLedger.cpp.
References ripple::ltRIPPLE_STATE, and mType.
 {
     return mType == ltRIPPLE_STATE;
 }
bool ripple::SerializedLedgerEntry::isMutable () inline
Definition at line 76 of file SerializedLedger.h.
References mMutable.
     {
         return mMutable;
     }
bool ripple::SerializedLedgerEntry::isThreaded ()
Definition at line 126 of file SerializedLedger.cpp.
References ripple::STObject::isFieldPresent().
 {
     return isFieldPresent (sfPreviousTxnID);
 }
bool ripple::SerializedLedgerEntry::isThreadedType ()
Definition at line 121 of file SerializedLedger.cpp.
References ripple::STObject::getFieldIndex().
 {
     return getFieldIndex (sfPreviousTxnID) != -1;
 }
void ripple::SerializedLedgerEntry::setImmutable () inline
Definition at line 72 of file SerializedLedger.h.
References mMutable.
     {
         mMutable = false;
     }
void ripple::SerializedLedgerEntry::setIndex (uint256 const & i) inline
Definition at line 67 of file SerializedLedger.h.
References mIndex.
     {
         mIndex = i;
     }
bool ripple::SerializedLedgerEntry::thread (uint256 const & txID, std::uint32_t ledgerSeq, uint256 & prevTxID, std::uint32_t & prevLedgerID)
Definition at line 141 of file SerializedLedger.cpp.
References ripple::STObject::getFieldH256(), ripple::STObject::getFieldU32(), ripple::lsTRACE, ripple::STObject::setFieldH256(), ripple::STObject::setFieldU32(), and WriteLog.
 {
     uint256 oldPrevTxID = getFieldH256 (sfPreviousTxnID);
     WriteLog (lsTRACE, SerializedLedgerLog) << "Thread Tx:" << txID << " prev:" << oldPrevTxID;
     if (oldPrevTxID == txID)
     {
         // this transaction is already threaded
         assert (getFieldU32 (sfPreviousTxnLgrSeq) == ledgerSeq);
         return false;
     }
     prevTxID = oldPrevTxID;
     prevLedgerID = getFieldU32 (sfPreviousTxnLgrSeq);
     setFieldH256 (sfPreviousTxnID, txID);
     setFieldU32 (sfPreviousTxnLgrSeq, ledgerSeq);
     return true;
 }
Member Data Documentation
LedgerFormats::Item const* ripple::SerializedLedgerEntry::mFormat private
Definition at line 117 of file SerializedLedger.h.
Referenced by getFormat(), getFullText(), and SerializedLedgerEntry().
uint256 ripple::SerializedLedgerEntry::mIndex private
Definition at line 115 of file SerializedLedger.h.
Referenced by getFullText(), getIndex(), getJson(), getText(), and setIndex().
bool ripple::SerializedLedgerEntry::mMutable private
Definition at line 118 of file SerializedLedger.h.
Referenced by isMutable(), and setImmutable().
LedgerEntryType ripple::SerializedLedgerEntry::mType private
Definition at line 116 of file SerializedLedger.h.
Referenced by getType(), hasOneOwner(), hasTwoOwners(), and SerializedLedgerEntry().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/misc/SerializedLedger.h
rippled/src/ripple_app/misc/SerializedLedger.cpp