rippled: beast::asio Namespace Reference
beast::asio Namespace Reference
Namespaces
detail
InputParser
placeholders
Classes
class abstract_socket
class buffer_sequence
class enable_wait_for_async
class memory_buffer
class shared_handler_wrapper_base
class shared_handler_wrapper_func
class shared_handler
class shared_handler_allocator
class socket_wrapper
class bind_handler_test
class boost_bind_test
class wrap_handler_test
class integer_sequence_test
class AsyncObject
class FixedInputBuffer
class FixedInputBufferSize
struct PeerRole
struct SharedArg
class SSLContext
class HTTPClientType
class HTTPClient_test
class HTTPClientBase
class HandshakeDetectLogic
class HandshakeDetectLogicType
class HandshakeDetectLogicPROXY
class HandshakeDetectLogicSSL2
class HandshakeDetectLogicSSL3
class HandshakeDetectorType
class PrefilledReadStream
class PeerTest
class TestPeer
class TestPeerBasics
class TestPeerDetails
struct TcpDetails
class TestPeerLogic
class TestPeerLogicAsyncClient
class TestPeerLogicAsyncServer
class TestPeerLogicProxyClient
class TestPeerLogicSyncClient
class TestPeerLogicSyncServer
class TestPeerType
class TestPeer_test
Typedefs
typedef buffer_sequence
< boost::asio::const_buffer > const_buffers
typedef buffer_sequence
< boost::asio::mutable_buffer > mutable_buffers
Enumerations
enum continuation_t { continuation }
Functions
template<class DeducedHandler , class... Args>
detail::bound_handler
< DeducedHandler, Args...> bind_handler (DeducedHandler &&handler, Args &&...args)
template<class T , class Alloc >
void swap (memory_buffer< T, Alloc > &lhs, memory_buffer< T, Alloc > &rhs) noexcept
template<class T , class A1 , class A2 >
bool operator== (memory_buffer< T, A1 > const &lhs, memory_buffer< T, A2 > const &rhs)
template<class T , class A1 , class A2 >
bool operator!= (memory_buffer< T, A1 > const &lhs, memory_buffer< T, A2 > const &rhs)
template<class T , class A1 , class A2 >
bool operator< (memory_buffer< T, A1 > const &lhs, memory_buffer< T, A2 > const &rhs)
template<class T , class A1 , class A2 >
bool operator>= (memory_buffer< T, A1 > const &lhs, memory_buffer< T, A2 > const &rhs)
template<class T , class A1 , class A2 >
bool operator> (memory_buffer< T, A1 > const &lhs, memory_buffer< T, A2 > const &rhs)
template<class T , class A1 , class A2 >
bool operator<= (memory_buffer< T, A1 > const &lhs, memory_buffer< T, A2 > const &rhs)
BEAST_DEFINE_TESTSUITE (bind_handler, asio, beast)
BEAST_DEFINE_TESTSUITE (boost_bind, asio, beast)
BEAST_DEFINE_TESTSUITE (wrap_handler, asio, beast)
BEAST_DEFINE_TESTSUITE (integer_sequence, cxx14, beast)
BEAST_DEFINE_TESTSUITE_MANUAL (HTTPClient, beast_asio, beast)
BEAST_DEFINE_TESTSUITE (TestPeer, beast_asio, beast)
template<class DeducedHandler , class Context >
detail::wrapped_handler
< std::remove_reference_t
< DeducedHandler >, Context > wrap_handler (DeducedHandler &&handler, Context const &context, bool continuation=false)
template<class DeducedHandler , class Context >
detail::wrapped_handler
< std::remove_reference_t
< DeducedHandler >, Context > wrap_handler (continuation_t, DeducedHandler &&handler, Context const &context)
Typedef Documentation
typedef buffer_sequence<boost::asio::const_buffer> beast::asio::const_buffers
Definition at line 120 of file buffer_sequence.h.
typedef buffer_sequence<boost::asio::mutable_buffer> beast::asio::mutable_buffers
Definition at line 121 of file buffer_sequence.h.
Enumeration Type Documentation
enum beast::asio::continuation_t
Enumerator
continuation
Definition at line 135 of file wrap_handler.h.
 {
     continuation
 };
Function Documentation
beast::asio::BEAST_DEFINE_TESTSUITE (TestPeer , beast_asio , beast)
beast::asio::BEAST_DEFINE_TESTSUITE (bind_handler , asio , beast)
beast::asio::BEAST_DEFINE_TESTSUITE (integer_sequence , cxx14 , beast)
beast::asio::BEAST_DEFINE_TESTSUITE (boost_bind , asio , beast)
beast::asio::BEAST_DEFINE_TESTSUITE (wrap_handler , asio , beast)
beast::asio::BEAST_DEFINE_TESTSUITE_MANUAL (HTTPClient , beast_asio , beast)
template<class DeducedHandler , class... Args> detail::bound_handler<DeducedHandler, Args...> beast::asio::bind_handler (DeducedHandler && handler, Args &&... args)
Binds parameters to a handler to produce a nullary functor. The returned handler provides the same io_service execution guarantees as the original handler. This is designed to use as a replacement for io_service::wrap, to ensure that the handler will not be invoked immediately by the calling function.
Definition at line 134 of file bind_handler.h.
Referenced by beast::asio::abstract_socket::async_accept(), beast::asio::socket_wrapper< acceptor_type & >::async_accept(), AutoSocket::async_handshake(), beast::asio::abstract_socket::async_handshake(), beast::asio::socket_wrapper< acceptor_type & >::async_handshake(), beast::asio::HandshakeDetectorType< Stream, Logic >::AsyncOp< Allocator >::async_read_some(), beast::asio::PrefilledReadStream< Stream >::async_read_some(), beast::asio::abstract_socket::async_read_some(), beast::asio::socket_wrapper< acceptor_type & >::async_read_some(), AutoSocket::async_shutdown(), ripple::MultiSocketType< socket_type & >::async_shutdown(), beast::asio::abstract_socket::async_shutdown(), beast::asio::socket_wrapper< acceptor_type & >::async_shutdown(), beast::asio::abstract_socket::async_write_some(), beast::asio::socket_wrapper< acceptor_type & >::async_write_some(), beast::asio::bind_handler_test::run(), beast::enable_wait_for_async_test::test(), and beast::asio::HTTPClientType::Session::~Session().
 {
     return detail::bound_handler <DeducedHandler, Args...> (
         std::forward <DeducedHandler> (handler),
             std::forward <Args> (args)...);
 }
template<class T , class A1 , class A2 > bool beast::asio::operator!= (memory_buffer< T, A1 > const & lhs, memory_buffer< T, A2 > const & rhs) inline
Definition at line 380 of file memory_buffer.h.
 {
     return ! (lhs == rhs);
 }
template<class T , class A1 , class A2 > bool beast::asio::operator< (memory_buffer< T, A1 > const & lhs, memory_buffer< T, A2 > const & rhs) inline
Definition at line 389 of file memory_buffer.h.
References lhs.
 {
     return std::lexicographical_compare (
         lhs.cbegin(), lhs.cend(), rhs.cbegin(), rhs.cend());
 }
template<class T , class A1 , class A2 > bool beast::asio::operator<= (memory_buffer< T, A1 > const & lhs, memory_buffer< T, A2 > const & rhs) inline
Definition at line 417 of file memory_buffer.h.
References lhs.
 {
     return ! (rhs < lhs);
 }
template<class T , class A1 , class A2 > bool beast::asio::operator== (memory_buffer< T, A1 > const & lhs, memory_buffer< T, A2 > const & rhs) inline
Definition at line 370 of file memory_buffer.h.
References beast::asio::memory_buffer< T, Alloc >::cbegin(), beast::asio::memory_buffer< T, Alloc >::cend(), and std::detail::equal().
 {
     return std::equal (lhs.cbegin(), lhs.cend(),
         rhs.cbegin(), rhs.cend());
 }
template<class T , class A1 , class A2 > bool beast::asio::operator> (memory_buffer< T, A1 > const & lhs, memory_buffer< T, A2 > const & rhs) inline
Definition at line 408 of file memory_buffer.h.
References lhs.
 {
     return rhs < lhs;
 }
template<class T , class A1 , class A2 > bool beast::asio::operator>= (memory_buffer< T, A1 > const & lhs, memory_buffer< T, A2 > const & rhs) inline
Definition at line 399 of file memory_buffer.h.
 {
     return ! (lhs < rhs);
 }
template<class T , class Alloc > void beast::asio::swap (memory_buffer< T, Alloc > & lhs, memory_buffer< T, Alloc > & rhs) noexcept
Definition at line 360 of file memory_buffer.h.
References lhs.
Referenced by ripple::CycledSet< ReceivedValidation, ReceivedValidationHash, ReceivedValidationKeyEqual >::cycle(), ripple::Validators::CycledMap< RippleLedgerHash, Ledger, Count, beast::hardened_hash< RippleLedgerHash >, RippleLedgerHash::key_equal >::cycle(), ripple::Validators::Logic::fetch(), beast::UnsignedIntegerCalc< UInt >::fromCanonical(), rocksdb::AssociativeMergeOperator::FullMerge(), rocksdb::MemTable::Get(), ripple::Resource::Logic::importConsumers(), rocksdb::MergeHelper::MergeUntil(), ripple::TestOverlay::BasicLink< PeerType, MessageType >::pre_step(), beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::Buckets::rehash(), beast::UnitTestUtilities::repeatableShuffle(), rocksdb::SaveValue(), ripple::AgedHistory< Container >::swap(), AutoSocket::swap(), Json::Value::CZString::swap(), Json::Value::swap(), beast::swap(), beast::Array< beast::String >::swap(), beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::swap(), beast::detail::aged_unordered_container< IsMulti, IsMap, Key, T, Duration, Hash, KeyEqual, Allocator >::swap(), beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::swap_data(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::swap_data(), ContentBodyBuffer::swapWith(), beast::DynamicBuffer::swapWith(), beast::StringPairArray::swapWith(), ripple::LedgerEntrySet::swapWith(), beast::ArrayAllocationBase< beast::String, DummyCriticalSection >::swapWith(), beast::ScopedPointer< beast::DirectoryIterator::NativeIterator::Pimpl >::swapWith(), beast::MemoryBlock::swapWith(), beast::HeapBlock< ElementType >::swapWith(), beast::LinkedListPointer< ObjectType >::swapWith(), beast::Array< beast::String >::swapWith(), beast::String::swapWith(), beast::aged_associative_container_test_base::testConstructRange(), and beast::UnsignedIntegerCalc< UInt >::toCanonical().
 {
     std::swap (lhs.m_base, rhs.m_base);
     std::swap (lhs.m_size, rhs.m_size);
 }
template<class DeducedHandler , class Context > detail::wrapped_handler< std::remove_reference_t <DeducedHandler>, Context> beast::asio::wrap_handler (DeducedHandler && handler, Context const & context, bool continuation = false)
Returns a wrapped handler so it executes within another context. The handler is invoked with the same io_service execution guarantees as the provided context. The handler will be copied if necessary.
Note
A copy of Context is made.
Definition at line 151 of file wrap_handler.h.
References continuation.
Referenced by beast::asio::HandshakeDetectorType< next_layer_type, beast::asio::HandshakeDetectLogicPROXY >::async_detect(), ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::async_handshake(), beast::asio::HandshakeDetectorType< Stream, Logic >::AsyncOp< Allocator >::async_read_some(), beast::asio::HTTPClientType::Session::async_read_some(), beast::asio::HTTPClientType::Session::handle_connect(), beast::asio::HTTPClientType::Session::handle_handshake(), beast::asio::HTTPClientType::Session::handle_read(), beast::asio::HTTPClientType::Session::handle_resolve(), beast::asio::HTTPClientType::Session::handle_start(), ripple::PeerFinder::CheckerImp::Request::Request(), beast::asio::wrap_handler_test::run(), beast::asio::HTTPClientType::Session::Session(), and ripple::MultiSocketType< StreamSocket >::AsyncOp< Stream >::start().
 {
     typedef std::remove_reference_t <DeducedHandler> Handler;
     return detail::wrapped_handler <Handler, Context> (continuation,
         std::forward <DeducedHandler> (handler), context);
 }
template<class DeducedHandler , class Context > detail::wrapped_handler< std::remove_reference_t <DeducedHandler>, Context> beast::asio::wrap_handler (continuation_t , DeducedHandler && handler, Context const & context)
Definition at line 164 of file wrap_handler.h.
 {
     typedef std::remove_reference_t <DeducedHandler> Handler;
     return detail::wrapped_handler <Handler, Context> (true,
         std::forward <DeducedHandler> (handler), context);
 }