rippled: rocksdb::AutoRollLoggerTest Class Reference
rocksdb::AutoRollLoggerTest Class Reference
Public Member Functions
void RollLogFileBySizeTest (AutoRollLogger *logger, size_t log_max_size, const string &log_message)
uint64_t RollLogFileByTimeTest (AutoRollLogger *logger, size_t time, const string &log_message)
Static Public Member Functions
static void InitTestDb ()
Static Public Attributes
static const string kSampleMessage
static const string kTestDir
static const string kLogFile
static Env * env = Env::Default()
Detailed Description
Definition at line 19 of file auto_roll_logger_test.cc.
Member Function Documentation
static void rocksdb::AutoRollLoggerTest::InitTestDb () inline static
Definition at line 21 of file auto_roll_logger_test.cc.
References ASSERT_TRUE.
{
     string deleteCmd = "rm -rf " + kTestDir;
     ASSERT_TRUE(system(deleteCmd.c_str()) == 0);
     Env::Default()->CreateDir(kTestDir);
   }
void rocksdb::AutoRollLoggerTest::RollLogFileBySizeTest (AutoRollLogger * logger, size_t log_max_size, const string & log_message)
Definition at line 64 of file auto_roll_logger_test.cc.
References ASSERT_EQ, ASSERT_TRUE, rocksdb::AutoRollLogger::GetLogFileSize(), and rocksdb::LogMessage().
{
   // measure the size of each message, which is supposed
   // to be equal or greater than log_message.size()
   LogMessage(logger, log_message.c_str());
   size_t message_size = logger->GetLogFileSize();
   size_t current_log_size = message_size;
   // Test the cases when the log file will not be rolled.
   while (current_log_size + message_size < log_max_size) {
     LogMessage(logger, log_message.c_str());
     current_log_size += message_size;
     ASSERT_EQ(current_log_size, logger->GetLogFileSize());
   }
   // Now the log file will be rolled
   LogMessage(logger, log_message.c_str());
   // Since rotation is checked before actual logging, we need to
   // trigger the rotation by logging another message.
   LogMessage(logger, log_message.c_str());
   ASSERT_TRUE(message_size == logger->GetLogFileSize());
 }
uint64_t rocksdb::AutoRollLoggerTest::RollLogFileByTimeTest (AutoRollLogger * logger, size_t time, const string & log_message)
Definition at line 89 of file auto_roll_logger_test.cc.
References ASSERT_EQ, ASSERT_GT, ASSERT_LT, ASSERT_OK, env, rocksdb::GetFileCreateTime(), rocksdb::AutoRollLogger::GetLogFileSize(), rocksdb::AutoRollLogger::GetStatus(), rocksdb::kLogFile, rocksdb::LogMessage(), and rocksdb::AutoRollLogger::SetCallNowMicrosEveryNRecords().
{
   uint64_t expected_create_time;
   uint64_t actual_create_time;
   uint64_t total_log_size;
   ASSERT_OK(env->GetFileSize(kLogFile, &total_log_size));
   GetFileCreateTime(kLogFile, &expected_create_time);
   logger->SetCallNowMicrosEveryNRecords(0);
   // -- Write to the log for several times, which is supposed
   // to be finished before time.
   for (int i = 0; i < 10; ++i) {
      LogMessage(logger, log_message.c_str());
      ASSERT_OK(logger->GetStatus());
      // Make sure we always write to the same log file (by
      // checking the create time);
      GetFileCreateTime(kLogFile, &actual_create_time);
      // Also make sure the log size is increasing.
      ASSERT_EQ(expected_create_time, actual_create_time);
      ASSERT_GT(logger->GetLogFileSize(), total_log_size);
      total_log_size = logger->GetLogFileSize();
   }
   // -- Make the log file expire
   sleep(time);
   LogMessage(logger, log_message.c_str());
   // At this time, the new log file should be created.
   GetFileCreateTime(kLogFile, &actual_create_time);
   ASSERT_GT(actual_create_time, expected_create_time);
   ASSERT_LT(logger->GetLogFileSize(), total_log_size);
   expected_create_time = actual_create_time;
   return expected_create_time;
 }
Member Data Documentation
Env * rocksdb::AutoRollLoggerTest::env = Env::Default() static
Definition at line 37 of file auto_roll_logger_test.cc.
const string rocksdb::AutoRollLoggerTest::kLogFile static
Definition at line 36 of file auto_roll_logger_test.cc.
const string rocksdb::AutoRollLoggerTest::kSampleMessage static
Definition at line 34 of file auto_roll_logger_test.cc.
const string rocksdb::AutoRollLoggerTest::kTestDir static
Definition at line 35 of file auto_roll_logger_test.cc.
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/util/auto_roll_logger_test.cc