rippled: ripple::core::Taker Class Reference
ripple::core::Taker Class Reference
#include <Taker.h>
Classes
struct Options
Public Member Functions
Taker (LedgerView &view, BookRef const &book, Account const &account, Amounts const &amount, Options const &options)
LedgerView & view () const noexcept
Book const & book () const noexcept
Account const & account () const noexcept
bool done () const noexcept
Quality threshold () const noexcept
bool reject (Quality const &quality) const noexcept
std::pair< Amounts, bool > fill (Offer const &offer) const
TER process (Amounts const &flow, Offer const &offer)
Private Member Functions
Amount funds () const
Private Attributes
std::reference_wrapper
< LedgerView > m_view
Book m_book
Account m_account
Options m_options
Quality m_quality
Quality m_threshold
Amounts m_amount
Amount m_in
Amount m_out
Detailed Description
State for the active party during order book or payment operations.
Definition at line 35 of file Taker.h.
Constructor & Destructor Documentation
ripple::core::Taker::Taker (LedgerView & view, BookRef const & book, Account const & account, Amounts const & amount, Options const & options) inline
Definition at line 78 of file Taker.h.
References m_options, m_threshold, and ripple::core::Taker::Options::passive.
         : m_view (view)
         , m_book (book)
         , m_account (account)
         , m_options (options)
         , m_quality (amount)
         , m_threshold (m_quality)
         , m_amount (amount)
         , m_in (amount.in)
         , m_out (amount.out.getCurrency(), amount.out.getIssuer())
     {
         // If this is a passive order (tfPassive), this prevents
         // offers at the same quality level from being consumed.
         if (m_options.passive)
             --m_threshold;
     }
Member Function Documentation
Account const& ripple::core::Taker::account () const inline noexcept
Returns the account identifier of the taker.
Definition at line 112 of file Taker.h.
References m_account.
Referenced by fill(), funds(), ripple::core::operator<<(), and process().
     {
         return m_account;
     }
Book const& ripple::core::Taker::book () const inline noexcept
Returns the input and output asset pair identifier.
Definition at line 105 of file Taker.h.
References m_book.
     {
         return m_book;
     }
bool ripple::core::Taker::done () const inline noexcept
Returns true if order crossing should not continue. Order processing is stopped if the taker's order quantities have been reached, or if the taker has run out of input funds.
Definition at line 122 of file Taker.h.
References funds(), m_amount, m_in, m_options, m_out, ripple::core::Amounts::out, and ripple::core::Taker::Options::sell.
     {
         if (m_options.sell)
         {
             // With the sell option, we are finished when
             // we have consumed all the input currency.
             if (! m_in.isPositive())
                 return true;
         }
         else if (m_out >= m_amount.out)
         {
             // With the buy option (!sell) we are finished when we
             // have received the desired amount of output currency.
             return true;
         }
         // We are finished if the taker is out of funds
         return ! funds().isPositive();
     }
std::pair<Amounts, bool> ripple::core::Taker::fill (Offer const & offer) const inline
Calcualtes the result of applying the taker's funds to the offer.
Returns
The flow and flag indicating if the order was consumed.
Definition at line 159 of file Taker.h.
References ripple::core::Offer::account(), account(), ripple::core::Offer::amount(), ripple::core::Quality::ceil_in(), ripple::core::Quality::ceil_out(), ripple::STAmount::divide(), ripple::core::Offer::entry(), m_amount, m_in, m_options, m_out, ripple::core::Amounts::out, ripple::core::Offer::quality(), QUALITY_ONE, ripple::STAmount::saFromRate(), ripple::core::Taker::Options::sell, and view().
     {
         // Best flow the owner can get.
         // Start out assuming entire offer will flow.
         Amounts owner_amount (offer.amount());
         // Limit owner's output by available funds less fees
         // VFALCO TODO Rename accountFounds to make it clear that
         //             it can return a clamped value.
         Amount const owner_funds (view().accountFunds (
             offer.account(), owner_amount.out));
         // Get fee rate paid by owner
         std::uint32_t const owner_charge_rate (view().rippleTransferRate (
             offer.account(), account(), offer.entry()->getFieldAmount (
                 sfTakerGets).getIssuer()));
         Amount const owner_charge (Amount::saFromRate (owner_charge_rate));
         // VFALCO Make Amount::divide skip math if v2 == QUALITY_ONE
         if (owner_charge_rate == QUALITY_ONE)
         {
             // Skip some math when there's no fee
             owner_amount = offer.quality().ceil_out (
                 owner_amount, owner_funds);
         }
         else
         {
             owner_amount = offer.quality().ceil_out (owner_amount,
                 Amount::divide (owner_funds, owner_charge));
         }
         // Best flow the taker can get.
         // Start out assuming entire offer will flow.
         Amounts taker_amount (offer.amount());
         // Limit taker's input by available funds less fees
         Amount const taker_funds (view().accountFunds (account(), m_in));
         // Get fee rate paid by taker
         std::uint32_t const taker_charge_rate (view().rippleTransferRate (
             account(), offer.account(), offer.entry()->getFieldAmount (
                 sfTakerPays).getIssuer()));
         Amount const taker_charge (Amount::saFromRate (taker_charge_rate));
         // VFALCO Make Amount::divide skip math if v2 == QUALITY_ONE
         if (taker_charge_rate == QUALITY_ONE)
         {
             // Skip some math when there's no fee
             taker_amount = offer.quality().ceil_in (
                 taker_amount, taker_funds);
         }
         else
         {
             taker_amount = offer.quality().ceil_in (taker_amount,
                 Amount::divide (taker_funds, taker_charge));
         }
         // Limit taker's input by options
         if (! m_options.sell)
         {
             assert (m_out < m_amount.out);
             taker_amount = offer.quality().ceil_out (
                 taker_amount, m_amount.out - m_out);
             assert (! taker_amount.in.isZero());
         }
         // Calculate the amount that will flow through the offer
         // This does not include the fees.
         Amounts const flow ((owner_amount.in < taker_amount.in) ?
             owner_amount : taker_amount);
         bool const consumed (flow.out >= owner_amount.out);
         return std::make_pair (flow, consumed);
     }
Amount ripple::core::Taker::funds () const inline private
Definition at line 72 of file Taker.h.
References account(), ripple::LedgerEntrySet::accountFunds(), m_in, and view().
Referenced by done().
     {
         return view().accountFunds (account(), m_in);
     }
TER ripple::core::Taker::process (Amounts const & flow, Offer const & offer) inline
Process the result of fee and funds calculation on the offer.
To protect the ledger, conditions which should never occur are checked. If the invariants are broken, the processing fails.
If processing succeeds, the funds are distributed to the taker, owner, and issuers.
Returns
false if processing failed (due to math errors).
Definition at line 248 of file Taker.h.
References ripple::core::Offer::account(), account(), ripple::LedgerEntrySet::accountSend(), ripple::core::Offer::entry(), ripple::LedgerEntrySet::entryModify(), ripple::core::Amounts::in, m_amount, m_in, m_options, m_out, ripple::core::Amounts::out, ripple::core::Taker::Options::sell, ripple::tesSUCCESS, and view().
     {
         TER result (tesSUCCESS);
         // VFALCO For the case of !sell, is it possible for the taker
         //        to get a tiny bit more than he asked for?
         assert (m_options.sell || flow.out <= m_amount.out);
         // Calculate remaining portion of offer
         Amounts const remain (
             offer.entry()->getFieldAmount (sfTakerPays) - flow.in,
             offer.entry()->getFieldAmount (sfTakerGets) - flow.out);
         offer.entry()->setFieldAmount (sfTakerPays, remain.in);
         offer.entry()->setFieldAmount (sfTakerGets, remain.out);
         view().entryModify (offer.entry());
         // Pay the taker
         result = view().accountSend (offer.account(), account(), flow.out);
         if (result == tesSUCCESS)
         {
             m_out += flow.out;
             // Pay the owner
             result = view().accountSend (account(), offer.account(), flow.in);
             if (result == tesSUCCESS)
             {
                 m_in -= flow.in;
             }
         }
         return result;
     }
bool ripple::core::Taker::reject (Quality const & quality) const inline noexcept
Returns true if the quality does not meet the taker's requirements.
Definition at line 150 of file Taker.h.
References m_threshold.
     {
         return quality < m_threshold;
     }
Quality ripple::core::Taker::threshold () const inline noexcept
Definition at line 143 of file Taker.h.
References m_threshold.
 {
     return m_threshold;
 }
LedgerView& ripple::core::Taker::view () const inline noexcept
Definition at line 98 of file Taker.h.
References m_view.
Referenced by fill(), funds(), and process().
     {
         return m_view;
     }
Member Data Documentation
Account ripple::core::Taker::m_account private
Definition at line 56 of file Taker.h.
Referenced by account().
Amounts ripple::core::Taker::m_amount private
Definition at line 62 of file Taker.h.
Referenced by done(), fill(), and process().
Book ripple::core::Taker::m_book private
Definition at line 55 of file Taker.h.
Referenced by book().
Amount ripple::core::Taker::m_in private
Definition at line 65 of file Taker.h.
Referenced by done(), fill(), funds(), and process().
Options ripple::core::Taker::m_options private
Definition at line 57 of file Taker.h.
Referenced by done(), fill(), process(), and Taker().
Amount ripple::core::Taker::m_out private
Definition at line 68 of file Taker.h.
Referenced by done(), fill(), and process().
Quality ripple::core::Taker::m_quality private
Definition at line 58 of file Taker.h.
Quality ripple::core::Taker::m_threshold private
Definition at line 59 of file Taker.h.
Referenced by reject(), Taker(), and threshold().
std::reference_wrapper<LedgerView> ripple::core::Taker::m_view private
Definition at line 54 of file Taker.h.
Referenced by view().
The documentation for this class was generated from the following file:
rippled/src/ripple_app/book/Taker.h