rippled: ripple::PeerFinder::Tuning Namespace Reference
ripple::PeerFinder::Tuning Namespace Reference
Enumerations
enum {
secondsPerConnect = 10, maxConnectAttempts = 20, outPercent = 15, minOutCount = 10,
defaultMaxPeers = 21
}
enum { bootcacheSize = 1000, bootcachePrunePercent = 10 }
enum {
maxHops = 6, numberOfEndpoints = 2 * maxHops, numberOfEndpointsMax = 20, defaultMaxPeerCount = 21,
redirectEndpointCount = 10
}
Functions
static std::chrono::seconds const bootcacheCooldownTime (60)
static std::chrono::seconds const secondsPerMessage (5)
static std::chrono::seconds const liveCacheSecondsToLive (30)
static std::chrono::seconds const recentAttemptDuration (60)
Variables
static std::array< int, 10 > const connectionBackoff { 1, 1, 2, 3, 5, 8, 13, 21, 34, 55 }}
Detailed Description
Heuristically tuned constants.
Enumeration Type Documentation
anonymous enum
Enumerator
secondsPerConnect
Time to wait between making batches of connection attempts
maxConnectAttempts
outPercent
minOutCount
defaultMaxPeers
Definition at line 32 of file Tuning.h.
 {
     //---------------------------------------------------------
     //
     // Automatic Connection Policy
     //
     //---------------------------------------------------------
     secondsPerConnect = 10
     ,maxConnectAttempts = 20
     ,outPercent = 15
     ,minOutCount = 10
     ,defaultMaxPeers = 21
 };
anonymous enum
Enumerator
bootcacheSize
bootcachePrunePercent
Definition at line 78 of file Tuning.h.
 {
     // Threshold of cache entries above which we trim.
     bootcacheSize = 1000
     // The percentage of addresses we prune when we trim the cache.
     ,bootcachePrunePercent = 10
 };
anonymous enum
Enumerator
maxHops
numberOfEndpoints
numberOfEndpointsMax
defaultMaxPeerCount
redirectEndpointCount
Definition at line 99 of file Tuning.h.
 {
     // Drop incoming messages with hops greater than this number
     maxHops = 6
     // How many Endpoint to send in each mtENDPOINTS
     ,numberOfEndpoints = 2 * maxHops
     // The most Endpoint we will accept in mtENDPOINTS
     ,numberOfEndpointsMax = 20
     // The number of peers that we want by default, unless an
     // explicit value is set in the config file.
     ,defaultMaxPeerCount = 21
     ,redirectEndpointCount = 10
 };
Function Documentation
static std::chrono::seconds const ripple::PeerFinder::Tuning::bootcacheCooldownTime (60) static
Referenced by ripple::PeerFinder::Bootcache::update().
static std::chrono::seconds const ripple::PeerFinder::Tuning::liveCacheSecondsToLive (30) static
Referenced by ripple::PeerFinder::SlotImp::recent_t::expire(), ripple::PeerFinder::Livecache< class >::expire(), and ripple::PeerFinder::Livecache< class >::onWrite().
static std::chrono::seconds const ripple::PeerFinder::Tuning::recentAttemptDuration (60) static
Referenced by ripple::PeerFinder::Logic::expire().
static std::chrono::seconds const ripple::PeerFinder::Tuning::secondsPerMessage (5) static
Referenced by ripple::PeerFinder::Logic::on_endpoints(), and ripple::PeerFinder::Logic::periodicActivity().
Variable Documentation
std::array<int, 10> const ripple::PeerFinder::Tuning::connectionBackoff { 1, 1, 2, 3, 5, 8, 13, 21, 34, 55 }} static
Definition at line 70 of file Tuning.h.
Referenced by ripple::PeerFinder::Fixed::failure().