rippled: beast::abstract_clock< Duration > Class Template Reference
beast::abstract_clock< Duration > Class Template Reference abstract
#include <abstract_clock.h>
Public Types
typedef Duration::rep rep
typedef Duration::period period
typedef Duration duration
typedef
std::chrono::time_point
< abstract_clock, duration > time_point
Public Member Functions
virtual ~abstract_clock ()
virtual bool is_steady () const =0
virtual time_point now () const =0
rep elapsed () const
Detailed Description
template<class Duration>
class beast::abstract_clock< Duration >
Abstract interface to a clock.
The abstract clock interface allows a dependency injection to take place so that the choice of implementation can be made at run-time instead of compile time. The trade-off is that the Duration used to represent the clock must be chosen at compile time and cannot be changed. This includes both the choice of representation (integers for example) and the period in ticks corresponding to one second.
Example:
struct Implementation
{
    abstract_clock <std::chrono::seconds>& m_clock;
    // Dependency injection
    //
    explicit Implementation (
        abstract_clock <std::chrono::seconds>& clock)
        : m_clock (clock)
    {
    }
};
Template Parameters
The length of time, in seconds, corresponding to one tick.
Definition at line 59 of file abstract_clock.h.
Member Typedef Documentation
template<class Duration> typedef Duration beast::abstract_clock< Duration >::duration
Definition at line 64 of file abstract_clock.h.
template<class Duration> typedef Duration::period beast::abstract_clock< Duration >::period
Definition at line 63 of file abstract_clock.h.
template<class Duration> typedef Duration::rep beast::abstract_clock< Duration >::rep
Definition at line 62 of file abstract_clock.h.
template<class Duration> typedef std::chrono::time_point< abstract_clock, duration> beast::abstract_clock< Duration >::time_point
Definition at line 66 of file abstract_clock.h.
Constructor & Destructor Documentation
template<class Duration> virtual beast::abstract_clock< Duration >::~abstract_clock () inline virtual
Definition at line 68 of file abstract_clock.h.
 { }
Member Function Documentation
template<class Duration> rep beast::abstract_clock< Duration >::elapsed () const inline
Returning elapsed ticks since the epoch.
Definition at line 92 of file abstract_clock.h.
Referenced by ripple::Resource::Logic::balance(), ripple::Resource::Logic::charge(), ripple::Resource::Logic::disconnect(), ripple::Resource::Logic::exportConsumers(), ripple::Resource::Logic::getJson(), ripple::Resource::Logic::importConsumers(), ripple::Resource::Logic::onWrite(), ripple::Resource::Logic::periodicActivity(), ripple::Resource::Logic::release(), and ripple::Resource::Logic::warn().
     {
         return now().time_since_epoch().count();
     }
template<class Duration> virtual bool beast::abstract_clock< Duration >::is_steady () const pure virtual
Returns true if this is a steady clock.
Implemented in beast::detail::basic_abstract_clock_wrapper< TrivialClock, Duration >, beast::manual_clock< Duration, IsSteady >, and beast::manual_clock< beast::abstract_clock::duration >.
template<class Duration> virtual time_point beast::abstract_clock< Duration >::now () const pure virtual
Returns the current time.
Implemented in beast::detail::basic_abstract_clock_wrapper< TrivialClock, Duration >, beast::manual_clock< Duration, IsSteady >, and beast::manual_clock< beast::abstract_clock::duration >.
Referenced by ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::canonicalize(), beast::abstract_clock< std::chrono::seconds >::elapsed(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::fetch(), ripple::PeerFinder::Logic::get_fixed(), ripple::KeyCache< Key >::insert(), beast::detail::aged_ordered_container< beast::IP::Address >::new_element(), beast::detail::aged_unordered_container< beast::IP::Endpoint, int >::new_element(), ripple::PeerFinder::Logic::on_closed(), ripple::PeerFinder::Logic::on_endpoints(), ripple::PeerFinder::Logic::on_handshake(), ripple::PeerSet::PeerSet(), ripple::PeerFinder::Logic::periodicActivity(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::refreshIfPresent(), ripple::TaggedCache< LedgerIndex, std::pair< LedgerHash, LedgerHash > >::sweep(), ripple::KeyCache< Key >::sweep(), ripple::InboundLedgersImp::sweep(), beast::abstract_clock_test::test(), beast::abstract_clock_test::test_manual(), ripple::PeerSet::touch(), and ripple::KeyCache< Key >::touch_if_exists().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/chrono/abstract_clock.h