rippled: ripple::LedgerMasterImp Class Reference
ripple::LedgerMasterImp Class Reference
Public Types
typedef std::function< void(Ledger::ref)> callback
typedef RippleRecursiveMutex LockType
typedef std::lock_guard< LockType > ScopedLockType
typedef
beast::GenericScopedUnlock
< LockType > ScopedUnlockType
Public Types inherited from ripple::LedgerMaster
typedef std::function< void(Ledger::ref)> callback
typedef RippleRecursiveMutex LockType
typedef std::unique_lock
< LockType > ScopedLockType
typedef
beast::GenericScopedUnlock
< LockType > ScopedUnlockType
Public Member Functions
LedgerMasterImp (Stoppable &parent, beast::Journal journal)
~LedgerMasterImp ()
LedgerIndex getCurrentLedgerIndex ()
LedgerIndex getValidLedgerIndex ()
int getPublishedLedgerAge ()
int getValidatedLedgerAge ()
bool isCaughtUp (std::string &reason)
void setValidLedger (Ledger::ref l)
void setPubLedger (Ledger::ref l)
void addHeldTransaction (Transaction::ref transaction)
void pushLedger (Ledger::pointer newLedger)
void pushLedger (Ledger::pointer newLCL, Ledger::pointer newOL)
void switchLedgers (Ledger::pointer lastClosed, Ledger::pointer current)
bool fixIndex (LedgerIndex ledgerIndex, LedgerHash const &ledgerHash)
bool storeLedger (Ledger::pointer ledger)
void forceValid (Ledger::pointer ledger)
void closeLedger (bool recover)
LedgerIndex getBuildingLedger ()
void setBuildingLedger (LedgerIndex i)
TER doTransaction (SerializedTransaction::ref txn, TransactionEngineParams params, bool &didApply)
bool haveLedgerRange (std::uint32_t from, std::uint32_t to)
bool haveLedger (std::uint32_t seq)
void clearLedger (std::uint32_t seq)
bool getFullValidatedRange (std::uint32_t &minVal, std::uint32_t &maxVal)
bool getValidatedRange (std::uint32_t &minVal, std::uint32_t &maxVal)
std::uint32_t getEarliestFetch ()
void tryFill (Job &job, Ledger::pointer ledger)
void getFetchPack (Ledger::ref nextLedger)
void fixMismatch (Ledger::ref ledger)
void setFullLedger (Ledger::pointer ledger, bool isSynchronous, bool isCurrent)
void failedSave (std::uint32_t seq, uint256 const &hash)
void checkAccept (uint256 const &hash, std::uint32_t seq)
int getNeededValidations ()
void checkAccept (Ledger::ref ledger)
void consensusBuilt (Ledger::ref ledger) override
void advanceThread ()
void doAdvance ()
std::list< Ledger::pointer > findNewLedgersToPublish ()
void tryAdvance ()
uint256 getLedgerHash (std::uint32_t desiredSeq, Ledger::ref knownGoodLedger)
void updatePaths (Job &job)
void newPathRequest ()
bool isNewPathRequest ()
void newOrderBookDB ()
void newPFWork (const char *name)
LockType & peekMutex ()
Ledger::pointer getCurrentLedger ()
Ledger::pointer getClosedLedger ()
Ledger::pointer getValidatedLedger ()
Ledger::ref getPublishedLedger ()
int getMinValidations ()
void setMinValidations (int v)
std::string getCompleteLedgers ()
Ledger::pointer findAcquireLedger (std::uint32_t index, uint256 const &hash)
uint256 getHashBySeq (std::uint32_t index)
uint256 walkHashBySeq (std::uint32_t index)
uint256 walkHashBySeq (std::uint32_t index, Ledger::ref referenceLedger)
Ledger::pointer getLedgerBySeq (std::uint32_t index)
Ledger::pointer getLedgerByHash (uint256 const &hash)
void doLedgerCleaner (const Json::Value &parameters)
void setLedgerRangePresent (std::uint32_t minV, std::uint32_t maxV)
void tune (int size, int age)
void sweep ()
float getCacheHitRate ()
void addValidateCallback (callback &c)
beast::PropertyStream::Source & getPropertySource ()
Public Member Functions inherited from ripple::LedgerMaster
virtual ~LedgerMaster ()=0
Public Member Functions inherited from beast::Stoppable
Stoppable (char const *name, Stoppable &parent)
virtual ~Stoppable ()
bool isStopping () const
bool isStopped () const
bool areChildrenStopped () const
void stopped ()
virtual void onPrepare ()
virtual void onStart ()
virtual void onStop ()
virtual void onChildrenStopped ()
Public Attributes
beast::Journal m_journal
LockType m_mutex
TransactionEngine mEngine
LedgerHolder mCurrentLedger
LedgerHolder mClosedLedger
LedgerHolder mValidLedger
Ledger::pointer mPubLedger
Ledger::pointer mPathLedger
LedgerHistory mLedgerHistory
CanonicalTXSet mHeldTransactions
LockType mCompleteLock
RangeSet mCompleteLedgers
std::unique_ptr< LedgerCleaner > mLedgerCleaner
int mMinValidations
uint256 mLastValidateHash
std::uint32_t mLastValidateSeq
std::list< callback > mOnValidate
bool mAdvanceThread
bool mAdvanceWork
int mFillInProgress
int mPathFindThread
bool mPathFindNewLedger
bool mPathFindNewRequest
std::atomic< std::uint32_t > mPubLedgerClose
std::atomic< std::uint32_t > mPubLedgerSeq
std::atomic< std::uint32_t > mValidLedgerClose
std::atomic< std::uint32_t > mValidLedgerSeq
std::atomic< std::uint32_t > mBuildingLedgerSeq
Additional Inherited Members
Static Public Member Functions inherited from ripple::LedgerMaster
static LedgerMaster * New (Stoppable &parent, beast::Journal journal)
static bool shouldAcquire (std::uint32_t currentLedgerID, std::uint32_t ledgerHistory, std::uint32_t targetLedger)
Protected Member Functions inherited from ripple::LedgerMaster
LedgerMaster (Stoppable &parent)
Protected Attributes inherited from beast::Stoppable
char const * m_name
RootStoppable & m_root
Child m_child
Atomic< int > m_started
bool volatile m_stopped
bool volatile m_childrenStopped
Children m_children
WaitableEvent m_stoppedEvent
Detailed Description
Definition at line 32 of file LedgerMaster.cpp.
Member Typedef Documentation
typedef std::function<void (Ledger::ref)> ripple::LedgerMasterImp::callback
Definition at line 37 of file LedgerMaster.cpp.
typedef RippleRecursiveMutex ripple::LedgerMasterImp::LockType
Definition at line 39 of file LedgerMaster.cpp.
typedef std::lock_guard<LockType> ripple::LedgerMasterImp::ScopedLockType
Definition at line 40 of file LedgerMaster.cpp.
typedef beast::GenericScopedUnlock<LockType> ripple::LedgerMasterImp::ScopedUnlockType
Definition at line 41 of file LedgerMaster.cpp.
Constructor & Destructor Documentation
ripple::LedgerMasterImp::LedgerMasterImp (Stoppable & parent, beast::Journal journal) inline explicit
Definition at line 85 of file LedgerMaster.cpp.
         : LedgerMaster (parent)
         , m_journal (journal)
         , mHeldTransactions (uint256 ())
         , mLedgerCleaner (LedgerCleaner::New(*this, LogPartition::getJournal<LedgerCleanerLog>()))
         , mMinValidations (0)
         , mLastValidateSeq (0)
         , mAdvanceThread (false)
         , mAdvanceWork (false)
         , mFillInProgress (0)
         , mPathFindThread (0)
         , mPathFindNewRequest (false)
         , mPubLedgerClose (0)
         , mPubLedgerSeq (0)
         , mValidLedgerClose (0)
         , mValidLedgerSeq (0)
         , mBuildingLedgerSeq (0)
     {
     }
ripple::LedgerMasterImp::~LedgerMasterImp () inline
Definition at line 105 of file LedgerMaster.cpp.
     {
     }
Member Function Documentation
void ripple::LedgerMasterImp::addHeldTransaction (Transaction::ref transaction) inline virtual
Implements ripple::LedgerMaster.
Definition at line 190 of file LedgerMaster.cpp.
References m_mutex, mHeldTransactions, and ripple::CanonicalTXSet::push_back().
     {
         // returns true if transaction was added
         ScopedLockType ml (m_mutex);
         mHeldTransactions.push_back (transaction->getSTransaction ());
     }
void ripple::LedgerMasterImp::addValidateCallback (callback & c) inline virtual
Implements ripple::LedgerMaster.
Definition at line 1431 of file LedgerMaster.cpp.
References mOnValidate.
     {
         mOnValidate.push_back (c);
     }
void ripple::LedgerMasterImp::advanceThread () inline
Definition at line 856 of file LedgerMaster.cpp.
References doAdvance(), ripple::LedgerHolder::empty(), ripple::lsFATAL, ripple::lsTRACE, m_mutex, mAdvanceThread, mValidLedger, and WriteLog.
Referenced by tryAdvance().
     {
         ScopedLockType sl (m_mutex);
         assert (!mValidLedger.empty () && mAdvanceThread);
         WriteLog (lsTRACE, LedgerMaster) << "advanceThread<";
         try
         {
             doAdvance();
         }
         catch (...)
         {
             WriteLog (lsFATAL, LedgerMaster) << "doAdvance throws an exception";
         }
         mAdvanceThread = false;
         WriteLog (lsTRACE, LedgerMaster) << "advanceThread>";
     }
void ripple::LedgerMasterImp::checkAccept (uint256 const & hash, std::uint32_t seq) inline virtual
Implements ripple::LedgerMaster.
Definition at line 659 of file LedgerMaster.cpp.
References ripple::InboundLedger::fcGENERIC, ripple::InboundLedgers::findCreate(), ripple::getApp(), ripple::base_uint< BITS >::GetHex(), ripple::Application::getInboundLedgers(), ripple::LedgerHistory::getLedgerByHash(), ripple::lsDEBUG, mBuildingLedgerSeq, mLedgerHistory, mValidLedgerSeq, and WriteLog.
Referenced by consensusBuilt(), pushLedger(), and switchLedgers().
     {
         if (seq != 0)
         {
             // Ledger is too old
             if (seq <= mValidLedgerSeq)
                 return;
             // Ledger could match the ledger we're already building
         if (seq == mBuildingLedgerSeq)
             return;
     }
         Ledger::pointer ledger = mLedgerHistory.getLedgerByHash (hash);
         if (!ledger)
         {
             // FIXME: We should really only fetch if the ledger
             //has sufficient validations to accept it
             InboundLedger::pointer l =
                 getApp().getInboundLedgers().findCreate(hash, 0, InboundLedger::fcGENERIC);
             if (l && l->isComplete() && !l->isFailed())
                 ledger = l->getLedger();
             else
             {
                 WriteLog (lsDEBUG, LedgerMaster) << "checkAccept triggers acquire " << hash.GetHex();
             }
         }
         if (ledger)
             checkAccept (ledger);
     }
void ripple::LedgerMasterImp::checkAccept (Ledger::ref ledger) inline virtual
Implements ripple::LedgerMaster.
Definition at line 719 of file LedgerMaster.cpp.
References ripple::getApp(), ripple::Validations::getFeeAverage(), ripple::Application::getFeeTrack(), ripple::LoadFeeTrack::getLoadBase(), getNeededValidations(), ripple::Application::getOrderBookDB(), ripple::Validations::getTrustedValidationCount(), ripple::Application::getValidations(), ripple::lsINFO, ripple::lsTRACE, m_mutex, mLastValidateHash, mLastValidateSeq, mPubLedger, mValidLedgerSeq, setPubLedger(), ripple::LoadFeeTrack::setRemoteFee(), ripple::OrderBookDB::setup(), setValidLedger(), tryAdvance(), and WriteLog.
     {
         if (ledger->getLedgerSeq() <= mValidLedgerSeq)
             return;
         // Can we advance the last fully-validated ledger? If so, can we publish?
         ScopedLockType ml (m_mutex);
         if (ledger->getLedgerSeq() <= mValidLedgerSeq)
             return;
         int minVal = getNeededValidations();
         int tvc = getApp().getValidations().getTrustedValidationCount(ledger->getHash());
         if (tvc < minVal) // nothing we can do
         {
             WriteLog (lsTRACE, LedgerMaster) << "Only " << tvc << " validations for " << ledger->getHash();
             return;
         }
         WriteLog (lsINFO, LedgerMaster) << "Advancing accepted ledger to " << ledger->getLedgerSeq() << " with >= " << minVal << " validations";
         mLastValidateHash = ledger->getHash();
         mLastValidateSeq = ledger->getLedgerSeq();
         ledger->setValidated();
         ledger->setFull();
         setValidLedger(ledger);
         if (!mPubLedger)
         {
             ledger->pendSaveValidated(true, true);
             setPubLedger(ledger);
             getApp().getOrderBookDB().setup(ledger);
         }
         std::uint64_t fee, fee2, ref;
         ref = getApp().getFeeTrack().getLoadBase();
         int count = getApp().getValidations().getFeeAverage(ledger->getHash(), ref, fee);
         int count2 = getApp().getValidations().getFeeAverage(ledger->getParentHash(), ref, fee2);
         if ((count + count2) == 0)
             getApp().getFeeTrack().setRemoteFee(ref);
         else
             getApp().getFeeTrack().setRemoteFee(((fee * count) + (fee2 * count2)) / (count + count2));
         tryAdvance ();
     }
void ripple::LedgerMasterImp::clearLedger (std::uint32_t seq) inline virtual
Implements ripple::LedgerMaster.
Definition at line 376 of file LedgerMaster.cpp.
References ripple::RangeSet::clearValue(), mCompleteLedgers, and mCompleteLock.
Referenced by doAdvance(), failedSave(), fixMismatch(), and getLedgerBySeq().
     {
         ScopedLockType sl (mCompleteLock);
         return mCompleteLedgers.clearValue (seq);
     }
void ripple::LedgerMasterImp::closeLedger (bool recover) inline virtual
Implements ripple::LedgerMaster.
Definition at line 288 of file LedgerMaster.cpp.
References ripple::IHashRouter::addSuppressionFlags(), ripple::TransactionEngine::applyTransaction(), ripple::CanonicalTXSet::begin(), CondLog, ripple::CanonicalTXSet::end(), ripple::getApp(), ripple::Application::getHashRouter(), ripple::LedgerHolder::getMutable(), ripple::lsINFO, ripple::lsWARNING, m_mutex, mCurrentLedger, mEngine, mHeldTransactions, ripple::CanonicalTXSet::reset(), ripple::LedgerHolder::set(), ripple::TransactionEngine::setLedger(), SF_SIGGOOD, ripple::tapNO_CHECK_SIGN, ripple::tapOPEN_LEDGER, and WriteLog.
     {
         ScopedLockType sl (m_mutex);
         Ledger::pointer closingLedger = mCurrentLedger.getMutable ();
         if (recover)
         {
             int recovers = 0;
             for (CanonicalTXSet::iterator it = mHeldTransactions.begin (), end = mHeldTransactions.end (); it != end; ++it)
             {
                 try
                 {
                     TransactionEngineParams tepFlags = tapOPEN_LEDGER;
                     if (getApp().getHashRouter ().addSuppressionFlags (it->first.getTXID (), SF_SIGGOOD))
                         tepFlags = static_cast<TransactionEngineParams> (tepFlags | tapNO_CHECK_SIGN);
                     bool didApply;
                     mEngine.applyTransaction (*it->second, tepFlags, didApply);
                     if (didApply)
                         ++recovers;
                     // If a transaction is recovered but hasn't been relayed,
                     // it will become disputed in the consensus process, which
                     // will cause it to be relayed.
                 }
                 catch (...)
                 {
                     // CHECKME: We got a few of these
                     WriteLog (lsWARNING, LedgerMaster) << "Held transaction throws";
                 }
             }
             CondLog (recovers != 0, lsINFO, LedgerMaster) << "Recovered " << recovers << " held transactions";
             // VFALCO TODO recreate the CanonicalTxSet object instead of resetting it
             mHeldTransactions.reset (closingLedger->getHash ());
         }
         mCurrentLedger.set (closingLedger);
         mEngine.setLedger (mCurrentLedger.getMutable ());
     }
void ripple::LedgerMasterImp::consensusBuilt (Ledger::ref ledger) inline override virtual
Report that the consensus process built a particular ledger
Implements ripple::LedgerMaster.
Definition at line 767 of file LedgerMaster.cpp.
References checkAccept(), ripple::getApp(), ripple::Validations::getCurrentTrustedValidations(), getLedgerByHash(), getNeededValidations(), ripple::Application::getValidations(), ripple::lsDEBUG, ripple::lsINFO, mValidLedgerSeq, setBuildingLedger(), and WriteLog.
     {
         // Because we just built a ledger, we are no longer building one
         setBuildingLedger (0);
         if (ledger->getLedgerSeq() <= mValidLedgerSeq)
         {
             WriteLog (lsINFO,  LedgerConsensus)
                << "Consensus built old ledger: "
                << ledger->getLedgerSeq() << " <= " << mValidLedgerSeq;
             return;
         }
         // See if this ledger can be the new fully-validated ledger
         checkAccept (ledger);
         if (ledger->getLedgerSeq() <= mValidLedgerSeq)
         {
             WriteLog (lsDEBUG, LedgerConsensus)
                 << "Consensus ledger fully validated";
             return;
         }
         // This ledger cannot be the new fully-validated ledger, but
         // maybe we saved up validations for some other ledger that can be
         auto const val = getApp().getValidations().getCurrentTrustedValidations();
         // Track validation counts with sequence numbers
         class valSeq
         {
             public:
             valSeq () : valCount_ (0), ledgerSeq_ (0) { ; }
             void mergeValidation (LedgerSeq seq)
             {
                 valCount_++;
                 // If we didn't already know the sequence, now we do
                 if (ledgerSeq_ == 0)
                     ledgerSeq_ = seq;
             }
             int valCount_;
             LedgerSeq ledgerSeq_;
         };
         // Count the number of current, trusted validations
         ripple::unordered_map <uint256, valSeq> count;
         for (auto const& v : val)
         {
             valSeq& vs = count[v->getLedgerHash()];
             vs.mergeValidation (v->getFieldU32 (sfLedgerSequence));
         }
         int neededValidations = getNeededValidations ();
         LedgerSeq maxSeq = mValidLedgerSeq;
         uint256 maxLedger = ledger->getHash();
         // Of the ledgers with sufficient validations,
         // find the one with the highest sequence
         for (auto& v : count)
             if (v.second.valCount_ > neededValidations)
             {
                 // If we still don't know the sequence, get it
                 if (v.second.ledgerSeq_ == 0)
                 {
                     Ledger::pointer ledger = getLedgerByHash (v.first);
                     if (ledger)
                         v.second.ledgerSeq_ = ledger->getLedgerSeq();
                 }
                 if (v.second.ledgerSeq_ > maxSeq)
                 {
                     maxSeq = v.second.ledgerSeq_;
                     maxLedger = v.first;
                 }
             }
         if (maxSeq > mValidLedgerSeq)
         {
             WriteLog (lsDEBUG, LedgerConsensus)
                 << "Consensus triggered check of ledger";
             checkAccept (maxLedger, maxSeq);
         }
     }
void ripple::LedgerMasterImp::doAdvance () inline
Definition at line 877 of file LedgerMaster.cpp.
References ripple::RangeSet::absent, ripple::JobQueue::addJob(), BIND_TYPE, clearLedger(), ripple::NetworkOPs::clearNeedNetworkLedger(), ripple::InboundLedger::fcHISTORY, ripple::InboundLedgers::findCreate(), findNewLedgersToPublish(), ripple::getApp(), ripple::LedgerMaster::getCompleteLedgers(), ripple::getConfig(), ripple::Application::getFeeTrack(), getFetchPack(), ripple::Ledger::getHashByIndex(), ripple::Application::getInboundLedgers(), ripple::JobQueue::getJobCount(), ripple::Application::getJobQueue(), getLedgerByHash(), ripple::LedgerHistory::getLedgerBySeq(), ripple::Application::getLedgerMaster(), ripple::Application::getOPs(), ripple::Config::getSize(), hash, ripple::InboundLedgers::isFailure(), ripple::LoadFeeTrack::isLoadedLocal(), ripple::base_uint< BITS >::isNonZero(), ripple::jtADVANCE, ripple::jtPUBOLDLEDGER, ripple::lsDEBUG, ripple::lsFATAL, ripple::lsTRACE, ripple::lsWARNING, m_mutex, mAdvanceWork, mCompleteLedgers, mCompleteLock, mFillInProgress, mLedgerHistory, mPubLedger, mPubLedgerSeq, mValidLedgerSeq, newPFWork(), P_1, ripple::RangeSet::prevMissing(), ripple::NetworkOPs::pubLedger(), ripple::Config::RUN_STANDALONE, setFullLedger(), setPubLedger(), ripple::LedgerMaster::shouldAcquire(), ripple::siLedgerFetch, tryFill(), and WriteLog.
Referenced by advanceThread().
     {
         do
         {
             mAdvanceWork = false; // If there's work to do, we'll make progress
             bool progress = false;
             std::list<Ledger::pointer> pubLedgers = findNewLedgersToPublish ();
             if (pubLedgers.empty())
             {
                 if (!getConfig().RUN_STANDALONE && !getApp().getFeeTrack().isLoadedLocal() &&
                     (getApp().getJobQueue().getJobCount(jtPUBOLDLEDGER) < 10) &&
                     (mValidLedgerSeq == mPubLedgerSeq))
                 { // We are in sync, so can acquire
                     std::uint32_t missing;
                     {
                         ScopedLockType sl (mCompleteLock);
                         missing = mCompleteLedgers.prevMissing(mPubLedger->getLedgerSeq());
                     }
                     WriteLog (lsTRACE, LedgerMaster) << "tryAdvance discovered missing " << missing;
                     if ((missing != RangeSet::absent) && (missing > 0) &&
                         shouldAcquire(mValidLedgerSeq, getConfig().LEDGER_HISTORY, missing) &&
                         ((mFillInProgress == 0) || (missing > mFillInProgress)))
                     {
                         WriteLog (lsTRACE, LedgerMaster) << "advanceThread should acquire";
{
                             ScopedUnlockType sl(m_mutex);
                             Ledger::pointer nextLedger = mLedgerHistory.getLedgerBySeq(missing + 1);
                             if (nextLedger)
{
                                 assert (nextLedger->getLedgerSeq() == (missing + 1));
                                 Ledger::pointer ledger = getLedgerByHash(nextLedger->getParentHash());
                                 if (!ledger)
{
                                     if (!getApp().getInboundLedgers().isFailure(nextLedger->getParentHash()))
{
                                         InboundLedger::pointer acq =
                                             getApp().getInboundLedgers().findCreate(nextLedger->getParentHash(),
                                                                                     nextLedger->getLedgerSeq() - 1,
                                                                                     InboundLedger::fcHISTORY);
                                         if (acq->isComplete() && !acq->isFailed())
                                             ledger = acq->getLedger();
                                         else if ((missing > 40000) && getApp().getOPs().shouldFetchPack(missing))
{
                                             WriteLog (lsTRACE, LedgerMaster) << "tryAdvance want fetch pack " << missing;
                                             getFetchPack(nextLedger);
                                         }
                                         else
                                             WriteLog (lsTRACE, LedgerMaster) << "tryAdvance no fetch pack for " << missing;
                                     }
                                     else
                                         WriteLog (lsDEBUG, LedgerMaster) << "tryAdvance found failed acquire";
                                 }
                                 if (ledger)
{
                                     assert(ledger->getLedgerSeq() == missing);
                                     WriteLog (lsTRACE, LedgerMaster) << "tryAdvance acquired " << ledger->getLedgerSeq();
                                     setFullLedger(ledger, false, false);
                                     if ((mFillInProgress == 0) && (Ledger::getHashByIndex(ledger->getLedgerSeq() - 1) == ledger->getParentHash()))
                                     { // Previous ledger is in DB
                                         ScopedLockType sl(m_mutex);
                                         mFillInProgress = ledger->getLedgerSeq();
                                         getApp().getJobQueue().addJob(jtADVANCE, "tryFill", BIND_TYPE (
                                             &LedgerMasterImp::tryFill, this, P_1, ledger));
                                     }
                                     progress = true;
                                 }
                                 else
{
                                     try
{
                                         for (int i = 0; i < getConfig().getSize(siLedgerFetch); ++i)
{
                                             std::uint32_t seq = missing - i;
                                             uint256 hash = nextLedger->getLedgerHash(seq);
                                             if (hash.isNonZero())
                                                 getApp().getInboundLedgers().findCreate(hash,
                                                      seq, InboundLedger::fcHISTORY);
                                         }
                                     }
                                     catch (...)
{
                                         WriteLog (lsWARNING, LedgerMaster) << "Threw while prefecthing";
                                     }
                                 }
                             }
                             else
{
                                 WriteLog (lsFATAL, LedgerMaster) << "Unable to find ledger following prevMissing " << missing;
                                 WriteLog (lsFATAL, LedgerMaster) << "Pub:" << mPubLedgerSeq << " Val:" << mValidLedgerSeq;
                                 WriteLog (lsFATAL, LedgerMaster) << "Ledgers: " << getApp().getLedgerMaster().getCompleteLedgers();
                                 clearLedger (missing + 1);
                                 progress = true;
                             }
                         }
                         if (mValidLedgerSeq != mPubLedgerSeq)
{
                             WriteLog (lsDEBUG, LedgerMaster) << "tryAdvance found last valid changed";
                             progress = true;
                         }
                     }
                 }
                 else
                     WriteLog (lsTRACE, LedgerMaster) << "tryAdvance not fetching history";
             }
             else
             {
                 WriteLog (lsTRACE, LedgerMaster) << "tryAdvance found " << pubLedgers.size() << " ledgers to publish";
                 BOOST_FOREACH(Ledger::ref ledger, pubLedgers)
                 {
                     {
                         ScopedUnlockType sul (m_mutex);
                         WriteLog(lsDEBUG, LedgerMaster) << "tryAdvance publishing seq " << ledger->getLedgerSeq();
                         setFullLedger(ledger, true, true);
                         getApp().getOPs().pubLedger(ledger);
                     }
                     setPubLedger(ledger);
                     progress = true;
                 }
                 getApp().getOPs().clearNeedNetworkLedger();
                 newPFWork ("pf:newLedger");
             }
             if (progress)
                 mAdvanceWork = true;
         } while (mAdvanceWork);
     }
void ripple::LedgerMasterImp::doLedgerCleaner (const Json::Value & parameters) inline virtual
Implements ripple::LedgerMaster.
Definition at line 1406 of file LedgerMaster.cpp.
References mLedgerCleaner.
     {
         mLedgerCleaner->doClean (parameters);
     }
TER ripple::LedgerMasterImp::doTransaction (SerializedTransaction::ref txn, TransactionEngineParams params, bool & didApply) inline virtual
Implements ripple::LedgerMaster.
Definition at line 345 of file LedgerMaster.cpp.
References ripple::TransactionEngine::applyTransaction(), ripple::getApp(), ripple::TransactionEngine::getLedger(), ripple::Application::getOPs(), m_mutex, mCurrentLedger, mEngine, ripple::NetworkOPs::pubProposedTransaction(), and ripple::LedgerHolder::set().
     {
         Ledger::pointer ledger;
         TER result;
         {
             ScopedLockType sl (m_mutex);
             result = mEngine.applyTransaction (*txn, params, didApply);
             ledger = mEngine.getLedger ();
         }
         if (didApply)
         {
            mCurrentLedger.set (ledger);
            getApp().getOPs ().pubProposedTransaction (ledger, txn, result);
         }
         return result;
     }
void ripple::LedgerMasterImp::failedSave (std::uint32_t seq, uint256 const & hash) inline virtual
Implements ripple::LedgerMaster.
Definition at line 652 of file LedgerMaster.cpp.
References clearLedger(), ripple::InboundLedger::fcGENERIC, ripple::InboundLedgers::findCreate(), ripple::getApp(), and ripple::Application::getInboundLedgers().
     {
         clearLedger(seq);
         getApp().getInboundLedgers().findCreate(hash, seq, InboundLedger::fcGENERIC);
     }
Ledger::pointer ripple::LedgerMasterImp::findAcquireLedger (std::uint32_t index, uint256 const & hash) inline virtual
Find or acquire the ledger with the specified index and the specified hash Return a pointer to that ledger if it is immediately available
Implements ripple::LedgerMaster.
Definition at line 1296 of file LedgerMaster.cpp.
References ripple::InboundLedger::fcGENERIC, ripple::InboundLedgers::findCreate(), ripple::getApp(), ripple::Application::getInboundLedgers(), and getLedgerByHash().
Referenced by walkHashBySeq().
     {
         Ledger::pointer ledger (getLedgerByHash (hash));
         if (!ledger)
         {
             InboundLedger::pointer inboundLedger =
                 getApp().getInboundLedgers().findCreate (hash, index, InboundLedger::fcGENERIC);
             if (inboundLedger && inboundLedger->isComplete() && !inboundLedger->isFailed())
                 ledger = inboundLedger->getLedger();
         }
         return ledger;
     }
std::list<Ledger::pointer> ripple::LedgerMasterImp::findNewLedgersToPublish () inline
Definition at line 1007 of file LedgerMaster.cpp.
References ripple::InboundLedgers::dropLedger(), ripple::InboundLedger::fcGENERIC, ripple::InboundLedgers::findCreate(), ripple::LedgerHolder::get(), ripple::getApp(), ripple::Application::getInboundLedgers(), ripple::LedgerHistory::getLedgerByHash(), ripple::Application::getOrderBookDB(), hash, ripple::base_uint< BITS >::isZero(), ripple::lsERROR, ripple::lsFATAL, ripple::lsINFO, ripple::lsTRACE, ripple::lsWARNING, m_mutex, MAX_LEDGER_GAP, mLedgerHistory, mPubLedger, mPubLedgerSeq, mValidLedger, mValidLedgerSeq, nothing, setPubLedger(), ripple::OrderBookDB::setup(), and WriteLog.
Referenced by doAdvance().
     {
         std::list<Ledger::pointer> ret;
         WriteLog (lsTRACE, LedgerMaster) << "findNewLedgersToPublish<";
         if (!mPubLedger)
         {
             WriteLog (lsINFO, LedgerMaster) << "First published ledger will be " << mValidLedgerSeq;
             ret.push_back (mValidLedger.get ());
         }
         else if (mValidLedgerSeq > (mPubLedgerSeq + MAX_LEDGER_GAP))
         {
             WriteLog (lsWARNING, LedgerMaster) << "Gap in validated ledger stream " << mPubLedgerSeq << " - " <<
                                                mValidLedgerSeq - 1;
             Ledger::pointer valLedger = mValidLedger.get ();
             ret.push_back (valLedger);
             setPubLedger (valLedger);
             getApp().getOrderBookDB().setup(valLedger);
         }
         else if (mValidLedgerSeq > mPubLedgerSeq)
         {
             int acqCount = 0;
             std::uint32_t pubSeq = mPubLedgerSeq + 1; // Next sequence to publish
             Ledger::pointer valLedger = mValidLedger.get ();
             std::uint32_t valSeq = valLedger->getLedgerSeq ();
             ScopedUnlockType sul(m_mutex);
             try
             {
                 for (std::uint32_t seq = pubSeq; seq <= valSeq; ++seq)
                 {
                     WriteLog (lsTRACE, LedgerMaster) << "Trying to fetch/publish valid ledger " << seq;
                     Ledger::pointer ledger;
                     uint256 hash = valLedger->getLedgerHash (seq); // This can throw
                     if (seq == valSeq)
                     { // We need to publish the ledger we just fully validated
                         ledger = valLedger;
                     }
                     else
                     {
                         if (hash.isZero ())
{
                             WriteLog (lsFATAL, LedgerMaster) << "Ledger: " << valSeq << " does not have hash for " << seq;
                             assert (false);
                         }
                         ledger = mLedgerHistory.getLedgerByHash (hash);
                     }
                     if (!ledger && (++acqCount < 4))
                     { // We can try to acquire the ledger we need
                         InboundLedger::pointer acq =
                             getApp().getInboundLedgers ().findCreate (hash, seq, InboundLedger::fcGENERIC);
                         if (!acq->isDone ())
{
                             nothing ();
                         }
                         else if (acq->isComplete () && !acq->isFailed ())
{
                             ledger = acq->getLedger();
                         }
                         else
{
                             WriteLog (lsWARNING, LedgerMaster) << "Failed to acquire a published ledger";
                             getApp().getInboundLedgers().dropLedger(hash);
                             acq = getApp().getInboundLedgers().findCreate(hash, seq, InboundLedger::fcGENERIC);
                             if (acq->isComplete())
{
                                 if (acq->isFailed())
                                     getApp().getInboundLedgers().dropLedger(hash);
                                 else
                                     ledger = acq->getLedger();
                             }
                         }
                     }
                     if (ledger && (ledger->getLedgerSeq() == pubSeq))
                     { // We acquired the next ledger we need to publish
                         ledger->setValidated();
                         ret.push_back (ledger);
                         ++pubSeq;
                     }
                 }
             }
             catch (...)
             {
                 WriteLog (lsERROR, LedgerMaster) << "findNewLedgersToPublish catches an exception";
             }
         }
         WriteLog (lsTRACE, LedgerMaster) << "findNewLedgersToPublish> " << ret.size();
         return ret;
     }
bool ripple::LedgerMasterImp::fixIndex (LedgerIndex ledgerIndex, LedgerHash const & ledgerHash) inline virtual
Implements ripple::LedgerMaster.
Definition at line 271 of file LedgerMaster.cpp.
References ripple::LedgerHistory::fixIndex(), and mLedgerHistory.
     {
         return mLedgerHistory.fixIndex (ledgerIndex, ledgerHash);
     }
void ripple::LedgerMasterImp::fixMismatch (Ledger::ref ledger) inline virtual
Implements ripple::LedgerMaster.
Definition at line 559 of file LedgerMaster.cpp.
References clearLedger(), CondLog, getLedgerBySeq(), hash, haveLedger(), ripple::base_uint< BITS >::isNonZero(), ripple::lsWARNING, and WriteLog.
Referenced by setFullLedger().
     {
         int invalidate = 0;
         uint256 hash;
         for (std::uint32_t lSeq = ledger->getLedgerSeq () - 1; lSeq > 0; --lSeq)
             if (haveLedger (lSeq))
             {
                 try
                 {
                     hash = ledger->getLedgerHash (lSeq);
             }
             catch (...)
             {
                 WriteLog (lsWARNING, LedgerMaster) << "fixMismatch encounters partial ledger";
                 clearLedger(lSeq);
                 return;
             }
                 if (hash.isNonZero ())
                 {
                     // try to close the seam
                     Ledger::pointer otherLedger = getLedgerBySeq (lSeq);
                     if (otherLedger && (otherLedger->getHash () == hash))
                     {
                         // we closed the seam
                         CondLog (invalidate != 0, lsWARNING, LedgerMaster) << "Match at " << lSeq << ", " <<
                                 invalidate << " prior ledgers invalidated";
                         return;
                     }
                 }
                 clearLedger (lSeq);
                 ++invalidate;
             }
         // all prior ledgers invalidated
         CondLog (invalidate != 0, lsWARNING, LedgerMaster) << "All " << invalidate << " prior ledgers invalidated";
     }
void ripple::LedgerMasterImp::forceValid (Ledger::pointer ledger) inline virtual
Implements ripple::LedgerMaster.
Definition at line 282 of file LedgerMaster.cpp.
References setFullLedger().
     {
         ledger->setValidated();
         setFullLedger(ledger, true, false);
     }
LedgerIndex ripple::LedgerMasterImp::getBuildingLedger () inline virtual
Implements ripple::LedgerMaster.
Definition at line 334 of file LedgerMaster.cpp.
References mBuildingLedgerSeq.
     {
         // The ledger we are currently building, 0 of none
         return mBuildingLedgerSeq.load ();
     }
float ripple::LedgerMasterImp::getCacheHitRate () inline virtual
Implements ripple::LedgerMaster.
Definition at line 1426 of file LedgerMaster.cpp.
References ripple::LedgerHistory::getCacheHitRate(), and mLedgerHistory.
     {
         return mLedgerHistory.getCacheHitRate ();
     }
Ledger::pointer ripple::LedgerMasterImp::getClosedLedger () inline virtual
Implements ripple::LedgerMaster.
Definition at line 1260 of file LedgerMaster.cpp.
References ripple::LedgerHolder::get(), and mClosedLedger.
Referenced by getEarliestFetch().
     {
         return mClosedLedger.get ();
     }
std::string ripple::LedgerMasterImp::getCompleteLedgers () inline virtual
Implements ripple::LedgerMaster.
Definition at line 1287 of file LedgerMaster.cpp.
References mCompleteLedgers, mCompleteLock, and ripple::RangeSet::toString().
     {
         ScopedLockType sl (mCompleteLock);
         return mCompleteLedgers.toString ();
     }
Ledger::pointer ripple::LedgerMasterImp::getCurrentLedger () inline virtual
Implements ripple::LedgerMaster.
Definition at line 1254 of file LedgerMaster.cpp.
References ripple::LedgerHolder::get(), and mCurrentLedger.
     {
         return mCurrentLedger.get ();
     }
LedgerIndex ripple::LedgerMasterImp::getCurrentLedgerIndex () inline virtual
Implements ripple::LedgerMaster.
Definition at line 109 of file LedgerMaster.cpp.
References ripple::LedgerHolder::get(), and mCurrentLedger.
     {
         return mCurrentLedger.get ()->getLedgerSeq ();
     }
std::uint32_t ripple::LedgerMasterImp::getEarliestFetch () inline virtual
Implements ripple::LedgerMaster.
Definition at line 456 of file LedgerMaster.cpp.
References ripple::Config::FETCH_DEPTH, getClosedLedger(), and ripple::getConfig().
     {
         // The earliest ledger we will let people fetch is ledger zero,
         // unless that creates a larger range than allowed
         std::uint32_t e = getClosedLedger()->getLedgerSeq();
         if (e > getConfig().FETCH_DEPTH)
             e -= getConfig().FETCH_DEPTH;
         else
             e = 0;
         return e;
     }
void ripple::LedgerMasterImp::getFetchPack (Ledger::ref nextLedger) inline
Request a fetch pack to get the ledger prior to 'nextLedger'
Definition at line 527 of file LedgerMaster.cpp.
References ripple::Overlay::getActivePeers(), ripple::getApp(), ripple::lsDEBUG, ripple::lsTRACE, ripple::Application::overlay(), rand, and WriteLog.
Referenced by doAdvance().
     {
         Peer::ptr target;
         int count = 0;
         Overlay::PeerSequence peerList = getApp().overlay ().getActivePeers ();
         BOOST_FOREACH (const Peer::ptr & peer, peerList)
         {
             if (peer->hasRange (nextLedger->getLedgerSeq() - 1, nextLedger->getLedgerSeq()))
             {
                 if (count++ == 0)
                     target = peer;
                 else if ((rand () % ++count) == 0)
                     target = peer;
             }
         }
         if (target)
         {
             protocol::TMGetObjectByHash tmBH;
             tmBH.set_query (true);
             tmBH.set_type (protocol::TMGetObjectByHash::otFETCH_PACK);
             tmBH.set_ledgerhash (nextLedger->getHash().begin (), 32);
             Message::pointer packet = boost::make_shared<Message> (tmBH, protocol::mtGET_OBJECTS);
             target->sendPacket (packet, false);
             WriteLog (lsTRACE, LedgerMaster) << "Requested fetch pack for " << nextLedger->getLedgerSeq() - 1;
         }
         else
             WriteLog (lsDEBUG, LedgerMaster) << "No peer for fetch pack";
     }
bool ripple::LedgerMasterImp::getFullValidatedRange (std::uint32_t & minVal, std::uint32_t & maxVal) inline virtual
Implements ripple::LedgerMaster.
Definition at line 383 of file LedgerMaster.cpp.
References ripple::RangeSet::absent, mCompleteLedgers, mCompleteLock, mPubLedgerSeq, and ripple::RangeSet::prevMissing().
     {
         maxVal = mPubLedgerSeq.load();
         if (!maxVal)
             return false;
         {
             ScopedLockType sl (mCompleteLock);
             minVal = mCompleteLedgers.prevMissing (maxVal);
         }
         if (minVal == RangeSet::absent)
             minVal = maxVal;
         else
             ++minVal;
         return true;
     }
uint256 ripple::LedgerMasterImp::getHashBySeq (std::uint32_t index) inline virtual
Get a ledger's hash by sequence number using the cache
Implements ripple::LedgerMaster.
Definition at line 1309 of file LedgerMaster.cpp.
References ripple::Ledger::getHashByIndex(), ripple::LedgerHistory::getLedgerHash(), hash, ripple::base_uint< BITS >::isNonZero(), and mLedgerHistory.
     {
         uint256 hash = mLedgerHistory.getLedgerHash (index);
         if (hash.isNonZero ())
             return hash;
         return Ledger::getHashByIndex (index);
     }
Ledger::pointer ripple::LedgerMasterImp::getLedgerByHash (uint256 const & hash) inline virtual
Implements ripple::LedgerMaster.
Definition at line 1386 of file LedgerMaster.cpp.
References ripple::LedgerHolder::get(), ripple::LedgerHistory::getLedgerByHash(), hash, ripple::base_uint< BITS >::isZero(), mClosedLedger, mCurrentLedger, and mLedgerHistory.
Referenced by consensusBuilt(), doAdvance(), findAcquireLedger(), and getLedgerHash().
     {
         if (hash.isZero ())
             return mCurrentLedger.get ();
         Ledger::pointer ret = mLedgerHistory.getLedgerByHash (hash);
         if (ret)
             return ret;
         ret = mCurrentLedger.get ();
         if (ret && (ret->getHash () == hash))
             return ret;
         ret = mClosedLedger.get ();
         if (ret && (ret->getHash () == hash))
             return ret;
         return Ledger::pointer ();
     }
Ledger::pointer ripple::LedgerMasterImp::getLedgerBySeq (std::uint32_t index) inline virtual
Implements ripple::LedgerMaster.
Definition at line 1368 of file LedgerMaster.cpp.
References clearLedger(), ripple::LedgerHolder::get(), ripple::LedgerHistory::getLedgerBySeq(), mClosedLedger, mCurrentLedger, and mLedgerHistory.
Referenced by fixMismatch(), and setFullLedger().
     {
         Ledger::pointer ret = mLedgerHistory.getLedgerBySeq (index);
         if (ret)
             return ret;
         ret = mCurrentLedger.get ();
         if (ret && (ret->getLedgerSeq () == index))
             return ret;
         ret = mClosedLedger.get ();
         if (ret && (ret->getLedgerSeq () == index))
             return ret;
         clearLedger (index);
         return Ledger::pointer();
     }
uint256 ripple::LedgerMasterImp::getLedgerHash (std::uint32_t desiredSeq, Ledger::ref knownGoodLedger) inline virtual
Implements ripple::LedgerMaster.
Definition at line 1121 of file LedgerMaster.cpp.
References getLedgerByHash(), hash, ripple::base_uint< BITS >::isNonZero(), and ripple::base_uint< BITS >::isZero().
     {
         assert(desiredSeq < knownGoodLedger->getLedgerSeq());
         uint256 hash = knownGoodLedger->getLedgerHash(desiredSeq);
         // Not directly in the given ledger
         if (hash.isZero ())
         {
             std::uint32_t seq = (desiredSeq + 255) % 256;
             assert(seq < desiredSeq);
             uint256 i = knownGoodLedger->getLedgerHash(seq);
             if (i.isNonZero())
             {
                 Ledger::pointer l = getLedgerByHash(i);
                 if (l)
                 {
                     hash = l->getLedgerHash(desiredSeq);
                     assert (hash.isNonZero());
                 }
             }
             else
                 assert(false);
         }
         return hash;
     }
int ripple::LedgerMasterImp::getMinValidations () inline virtual
Implements ripple::LedgerMaster.
Definition at line 1277 of file LedgerMaster.cpp.
References mMinValidations.
     {
         return mMinValidations;
     }
int ripple::LedgerMasterImp::getNeededValidations () inline
Determines how many validations are needed to fully-validated a ledger
Returns
Number of validations needed
Definition at line 699 of file LedgerMaster.cpp.
References ripple::getApp(), ripple::getConfig(), ripple::Validations::getTrustedValidationCount(), ripple::Application::getValidations(), ripple::base_uint< BITS >::isNonZero(), MIN_VALIDATION_RATIO, mLastValidateHash, and mMinValidations.
Referenced by checkAccept(), and consensusBuilt().
     {
         if (getConfig ().RUN_STANDALONE)
             return 0;
         int minVal = mMinValidations;
         if (mLastValidateHash.isNonZero ())
         {
             int val = getApp().getValidations ().getTrustedValidationCount (mLastValidateHash);
             val *= MIN_VALIDATION_RATIO;
             val /= 256;
             if (val > minVal)
                 minVal = val;
         }
         return minVal;
     }
beast::PropertyStream::Source& ripple::LedgerMasterImp::getPropertySource () inline virtual
Implements ripple::LedgerMaster.
Definition at line 1436 of file LedgerMaster.cpp.
References mLedgerCleaner.
     {
         return *mLedgerCleaner;
     }
Ledger::ref ripple::LedgerMasterImp::getPublishedLedger () inline virtual
Implements ripple::LedgerMaster.
Definition at line 1272 of file LedgerMaster.cpp.
References mPubLedger.
     {
         return mPubLedger;
     }
int ripple::LedgerMasterImp::getPublishedLedgerAge () inline virtual
Implements ripple::LedgerMaster.
Definition at line 119 of file LedgerMaster.cpp.
References ripple::getApp(), ripple::NetworkOPs::getCloseTimeNC(), ripple::Application::getOPs(), ripple::lsDEBUG, ripple::lsTRACE, mPubLedgerClose, and WriteLog.
Referenced by isCaughtUp().
     {
         std::uint32_t pubClose = mPubLedgerClose.load();
         if (!pubClose)
         {
             WriteLog (lsDEBUG, LedgerMaster) << "No published ledger";
             return 999999;
         }
         std::int64_t ret = getApp().getOPs ().getCloseTimeNC ();
         ret -= static_cast<std::int64_t> (pubClose);
         ret = (ret > 0) ? ret : 0;
         WriteLog (lsTRACE, LedgerMaster) << "Published ledger age is " << ret;
         return static_cast<int> (ret);
     }
Ledger::pointer ripple::LedgerMasterImp::getValidatedLedger () inline virtual
Implements ripple::LedgerMaster.
Definition at line 1266 of file LedgerMaster.cpp.
References ripple::LedgerHolder::get(), and mValidLedger.
     {
         return mValidLedger.get ();
     }
int ripple::LedgerMasterImp::getValidatedLedgerAge () inline virtual
Implements ripple::LedgerMaster.
Definition at line 136 of file LedgerMaster.cpp.
References ripple::getApp(), ripple::NetworkOPs::getCloseTimeNC(), ripple::Application::getOPs(), ripple::lsDEBUG, ripple::lsTRACE, mValidLedgerClose, and WriteLog.
     {
         std::uint32_t valClose = mValidLedgerClose.load();
         if (!valClose)
         {
             WriteLog (lsDEBUG, LedgerMaster) << "No validated ledger";
             return 999999;
         }
         std::int64_t ret = getApp().getOPs ().getCloseTimeNC ();
         ret -= static_cast<std::int64_t> (valClose);
         ret = (ret > 0) ? ret : 0;
         WriteLog (lsTRACE, LedgerMaster) << "Validated ledger age is " << ret;
         return static_cast<int> (ret);
     }
bool ripple::LedgerMasterImp::getValidatedRange (std::uint32_t & minVal, std::uint32_t & maxVal) inline virtual
Implements ripple::LedgerMaster.
Definition at line 404 of file LedgerMaster.cpp.
References ripple::RangeSet::absent, ripple::Ledger::getPendingSaves(), mCompleteLedgers, mCompleteLock, mPubLedgerSeq, and ripple::RangeSet::prevMissing().
     {
         maxVal = mPubLedgerSeq.load();
         if (!maxVal)
             return false;
         {
             ScopedLockType sl (mCompleteLock);
             minVal = mCompleteLedgers.prevMissing (maxVal);
         }
         if (minVal == RangeSet::absent)
             minVal = maxVal;
         else
             ++minVal;
         // Remove from the validated range any ledger sequences that may not be
         // fully updated in the database yet
         std::set<std::uint32_t> sPendingSaves = Ledger::getPendingSaves();
         if (!sPendingSaves.empty() && ((minVal != 0) || (maxVal != 0)))
         {
             // Ensure we shrink the tips as much as possible
             // If we have 7-9 and 8,9 are invalid, we don't want to see the 8 and shrink to just 9
             // because then we'll have nothing when we could have 7.
             while (sPendingSaves.count(maxVal) > 0)
                 --maxVal;
             while (sPendingSaves.count(minVal) > 0)
                 ++minVal;
             // Best effort for remaining exclusions
             BOOST_FOREACH(std::uint32_t v, sPendingSaves)
             {
                 if ((v >= minVal) && (v <= maxVal))
                 {
                     if (v > ((minVal + maxVal) / 2))
                         maxVal = v - 1;
                     else
                         minVal = v + 1;
                 }
             }
             if (minVal > maxVal)
                 minVal = maxVal = 0;
         }
         return true;
     }
LedgerIndex ripple::LedgerMasterImp::getValidLedgerIndex () inline virtual
Implements ripple::LedgerMaster.
Definition at line 114 of file LedgerMaster.cpp.
References mValidLedgerSeq.
     {
         return mValidLedgerSeq;
     }
bool ripple::LedgerMasterImp::haveLedger (std::uint32_t seq) inline virtual
Implements ripple::LedgerMaster.
Definition at line 370 of file LedgerMaster.cpp.
References ripple::RangeSet::hasValue(), mCompleteLedgers, and mCompleteLock.
Referenced by fixMismatch(), setFullLedger(), and tryFill().
     {
         ScopedLockType sl (mCompleteLock);
         return mCompleteLedgers.hasValue (seq);
     }
bool ripple::LedgerMasterImp::haveLedgerRange (std::uint32_t from, std::uint32_t to) inline virtual
Implements ripple::LedgerMaster.
Definition at line 363 of file LedgerMaster.cpp.
References ripple::RangeSet::absent, mCompleteLedgers, mCompleteLock, and ripple::RangeSet::prevMissing().
     {
         ScopedLockType sl (mCompleteLock);
         std::uint32_t prevMissing = mCompleteLedgers.prevMissing (to + 1);
         return (prevMissing == RangeSet::absent) || (prevMissing < from);
     }
bool ripple::LedgerMasterImp::isCaughtUp (std::string & reason) inline virtual
Implements ripple::LedgerMaster.
Definition at line 153 of file LedgerMaster.cpp.
References getPublishedLedgerAge(), mPubLedgerClose, and mValidLedgerClose.
     {
         if (getPublishedLedgerAge() > 180)
         {
             reason = "No recently-published ledger";
             return false;
         }
         std::uint32_t validClose = mValidLedgerClose.load();
         std::uint32_t pubClose = mPubLedgerClose.load();
         if (!validClose || !pubClose)
         {
             reason = "No published ledger";
             return false;
         }
         if (validClose  > (pubClose + 90))
         {
             reason = "Published ledger lags validated ledger";
             return false;
         }
         return true;
     }
bool ripple::LedgerMasterImp::isNewPathRequest () inline virtual
Implements ripple::LedgerMaster.
Definition at line 1218 of file LedgerMaster.cpp.
References m_mutex, and mPathFindNewRequest.
     {
         ScopedLockType ml (m_mutex);
         if (!mPathFindNewRequest)
             return false;
         mPathFindNewRequest = false;
         return true;
     }
void ripple::LedgerMasterImp::newOrderBookDB () inline virtual
Implements ripple::LedgerMaster.
Definition at line 1228 of file LedgerMaster.cpp.
References m_mutex, mPathLedger, and newPFWork().
     {
         ScopedLockType ml (m_mutex);
         mPathLedger.reset();
         newPFWork("pf:newOBDB");
     }
void ripple::LedgerMasterImp::newPathRequest () inline virtual
Implements ripple::LedgerMaster.
Definition at line 1210 of file LedgerMaster.cpp.
References m_mutex, mPathFindNewRequest, and newPFWork().
     {
         ScopedLockType ml (m_mutex);
         mPathFindNewRequest = true;
         newPFWork("pf:newRequest");
     }
void ripple::LedgerMasterImp::newPFWork (const char * name) inline
A thread needs to be dispatched to handle pathfinding work of some kind
Definition at line 1238 of file LedgerMaster.cpp.
References ripple::JobQueue::addJob(), BIND_TYPE, ripple::getApp(), ripple::Application::getJobQueue(), ripple::jtUPDATE_PF, mPathFindThread, P_1, and updatePaths().
Referenced by doAdvance(), newOrderBookDB(), and newPathRequest().
     {
         if (mPathFindThread < 2)
         {
             ++mPathFindThread;
             getApp().getJobQueue().addJob (jtUPDATE_PF, name,
                 BIND_TYPE (&LedgerMasterImp::updatePaths, this, P_1));
         }
     }
LockType& ripple::LedgerMasterImp::peekMutex () inline virtual
Implements ripple::LedgerMaster.
Definition at line 1248 of file LedgerMaster.cpp.
References m_mutex.
     {
         return m_mutex;
     }
void ripple::LedgerMasterImp::pushLedger (Ledger::pointer newLedger) inline virtual
Implements ripple::LedgerMaster.
Definition at line 197 of file LedgerMaster.cpp.
References checkAccept(), ripple::getConfig(), ripple::LedgerHolder::getMutable(), ripple::lsINFO, m_mutex, mClosedLedger, mCurrentLedger, mEngine, ripple::LedgerHolder::set(), setFullLedger(), ripple::TransactionEngine::setLedger(), tryAdvance(), and WriteLog.
     {
         // Caller should already have properly assembled this ledger into "ready-to-close" form --
         // all candidate transactions must already be applied
         WriteLog (lsINFO, LedgerMaster) << "PushLedger: " << newLedger->getHash ();
         {
             ScopedLockType ml (m_mutex);
             Ledger::pointer closedLedger = mCurrentLedger.getMutable ();
             if (closedLedger)
             {
                 closedLedger->setClosed ();
                 closedLedger->setImmutable ();
                 mClosedLedger.set (closedLedger);
         }
             mCurrentLedger.set (newLedger);
             mEngine.setLedger (newLedger);
         }
         if (getConfig().RUN_STANDALONE)
         {
             setFullLedger(newLedger, true, false);
             tryAdvance();
         }
         else
             checkAccept(newLedger);
     }
void ripple::LedgerMasterImp::pushLedger (Ledger::pointer newLCL, Ledger::pointer newOL) inline virtual
Implements ripple::LedgerMaster.
Definition at line 227 of file LedgerMaster.cpp.
References ripple::LedgerHistory::builtLedger(), checkAccept(), ripple::getConfig(), m_mutex, mClosedLedger, mCurrentLedger, mEngine, mLedgerHistory, ripple::LedgerHolder::set(), setFullLedger(), ripple::TransactionEngine::setLedger(), and tryAdvance().
     {
         assert (newLCL->isClosed () && newLCL->isAccepted ());
         assert (!newOL->isClosed () && !newOL->isAccepted ());
         {
             ScopedLockType ml (m_mutex);
             mClosedLedger.set (newLCL);
             mCurrentLedger.set (newOL);
             mEngine.setLedger (newOL);
         }
         if (getConfig().RUN_STANDALONE)
         {
             setFullLedger(newLCL, true, false);
             tryAdvance();
         }
         else
         {
             mLedgerHistory.builtLedger (newLCL);
             checkAccept (newLCL);
         }
     }
void ripple::LedgerMasterImp::setBuildingLedger (LedgerIndex i) inline virtual
Implements ripple::LedgerMaster.
Definition at line 340 of file LedgerMaster.cpp.
References mBuildingLedgerSeq.
Referenced by consensusBuilt().
     {
         mBuildingLedgerSeq.store (i);
     }
void ripple::LedgerMasterImp::setFullLedger (Ledger::pointer ledger, bool isSynchronous, bool isCurrent) inline virtual
Implements ripple::LedgerMaster.
Definition at line 600 of file LedgerMaster.cpp.
References ripple::LedgerHistory::addLedger(), fixMismatch(), ripple::getApp(), getLedgerBySeq(), ripple::Application::getOrderBookDB(), ripple::Application::getValidators(), haveLedger(), ripple::Validators::Manager::ledgerClosed(), ripple::lsDEBUG, ripple::lsWARNING, m_mutex, mCompleteLedgers, mCompleteLock, mLedgerHistory, mPubLedger, mValidLedgerSeq, setPubLedger(), ripple::OrderBookDB::setup(), setValidLedger(), ripple::RangeSet::setValue(), and WriteLog.
Referenced by doAdvance(), forceValid(), and pushLedger().
     {
         // A new ledger has been accepted as part of the trusted chain
         WriteLog (lsDEBUG, LedgerMaster) << "Ledger " << ledger->getLedgerSeq () << " accepted :" << ledger->getHash ();
         assert (ledger->peekAccountStateMap ()->getHash ().isNonZero ());
         ledger->setValidated();
         mLedgerHistory.addLedger(ledger, true);
         ledger->setFull();
         ledger->pendSaveValidated (isSynchronous, isCurrent);
         {
             {
                 ScopedLockType ml (mCompleteLock);
                 mCompleteLedgers.setValue (ledger->getLedgerSeq ());
             }
             ScopedLockType ml (m_mutex);
             if (ledger->getLedgerSeq() > mValidLedgerSeq)
                 setValidLedger(ledger);
             if (!mPubLedger)
             {
                 setPubLedger(ledger);
                 getApp().getOrderBookDB().setup(ledger);
             }
             if ((ledger->getLedgerSeq () != 0) && haveLedger (ledger->getLedgerSeq () - 1))
             {
                 // we think we have the previous ledger, double check
                 Ledger::pointer prevLedger = getLedgerBySeq (ledger->getLedgerSeq () - 1);
                 if (!prevLedger || (prevLedger->getHash () != ledger->getParentHash ()))
                 {
                     WriteLog (lsWARNING, LedgerMaster) << "Acquired ledger invalidates previous ledger: " <<
                                                        (prevLedger ? "hashMismatch" : "missingLedger");
                     fixMismatch (ledger);
                 }
             }
         }
         //--------------------------------------------------------------------------
         //
         {
             if (isCurrent)
                 getApp ().getValidators ().ledgerClosed (ledger->getHash());
         }
         //
         //--------------------------------------------------------------------------
     }
void ripple::LedgerMasterImp::setLedgerRangePresent (std::uint32_t minV, std::uint32_t maxV) inline virtual
Implements ripple::LedgerMaster.
Definition at line 1411 of file LedgerMaster.cpp.
References mCompleteLedgers, mCompleteLock, and ripple::RangeSet::setRange().
     {
         ScopedLockType sl (mCompleteLock);
         mCompleteLedgers.setRange (minV, maxV);
     }
void ripple::LedgerMasterImp::setMinValidations (int v) inline virtual
Implements ripple::LedgerMaster.
Definition at line 1282 of file LedgerMaster.cpp.
References mMinValidations.
     {
         mMinValidations = v;
     }
void ripple::LedgerMasterImp::setPubLedger (Ledger::ref l) inline
Definition at line 183 of file LedgerMaster.cpp.
References mPubLedger, mPubLedgerClose, and mPubLedgerSeq.
Referenced by checkAccept(), doAdvance(), findNewLedgersToPublish(), and setFullLedger().
     {
         mPubLedger = l;
         mPubLedgerClose = l->getCloseTimeNC();
         mPubLedgerSeq = l->getLedgerSeq();
     }
void ripple::LedgerMasterImp::setValidLedger (Ledger::ref l) inline
Definition at line 175 of file LedgerMaster.cpp.
References ripple::getApp(), ripple::Application::getOPs(), mValidLedger, mValidLedgerClose, mValidLedgerSeq, ripple::LedgerHolder::set(), and ripple::NetworkOPs::updateLocalTx().
Referenced by checkAccept(), and setFullLedger().
     {
         mValidLedger.set (l);
         mValidLedgerClose = l->getCloseTimeNC();
         mValidLedgerSeq = l->getLedgerSeq();
         getApp().getOPs().updateLocalTx (l);
     }
bool ripple::LedgerMasterImp::storeLedger (Ledger::pointer ledger) inline virtual
Implements ripple::LedgerMaster.
Definition at line 276 of file LedgerMaster.cpp.
References ripple::LedgerHistory::addLedger(), and mLedgerHistory.
     {
         // Returns true if we already had the ledger
         return mLedgerHistory.addLedger (ledger, false);
     }
void ripple::LedgerMasterImp::sweep () inline virtual
Implements ripple::LedgerMaster.
Definition at line 1421 of file LedgerMaster.cpp.
References mLedgerHistory, and ripple::LedgerHistory::sweep().
     {
         mLedgerHistory.sweep ();
     }
void ripple::LedgerMasterImp::switchLedgers (Ledger::pointer lastClosed, Ledger::pointer current) inline virtual
Implements ripple::LedgerMaster.
Definition at line 252 of file LedgerMaster.cpp.
References checkAccept(), m_mutex, mClosedLedger, mCurrentLedger, mEngine, ripple::LedgerHolder::set(), and ripple::TransactionEngine::setLedger().
     {
         assert (lastClosed && current);
         {
             ScopedLockType ml (m_mutex);
             lastClosed->setClosed ();
             lastClosed->setAccepted ();
             mCurrentLedger.set (current);
             mClosedLedger.set (lastClosed);
             assert (!current->isClosed ());
             mEngine.setLedger (current);
         }
         checkAccept (lastClosed);
     }
void ripple::LedgerMasterImp::tryAdvance () inline virtual
Implements ripple::LedgerMaster.
Definition at line 1106 of file LedgerMaster.cpp.
References ripple::JobQueue::addJob(), advanceThread(), BIND_TYPE, ripple::LedgerHolder::empty(), ripple::getApp(), ripple::Application::getJobQueue(), ripple::jtADVANCE, m_mutex, mAdvanceThread, mAdvanceWork, and mValidLedger.
Referenced by checkAccept(), pushLedger(), and tryFill().
     {
         ScopedLockType ml (m_mutex);
         // Can't advance without at least one fully-valid ledger
         mAdvanceWork = true;
         if (!mAdvanceThread && !mValidLedger.empty ())
         {
             mAdvanceThread = true;
             getApp().getJobQueue ().addJob (jtADVANCE, "advanceLedger",
                                             BIND_TYPE (&LedgerMasterImp::advanceThread, this));
         }
     }
void ripple::LedgerMasterImp::tryFill (Job & job, Ledger::pointer ledger) inline
Definition at line 468 of file LedgerMaster.cpp.
References ripple::getApp(), ripple::Ledger::getHashesByIndex(), haveLedger(), ripple::Application::isShutdown(), m_mutex, mCompleteLedgers, mCompleteLock, mFillInProgress, ripple::RangeSet::setRange(), ripple::Job::shouldCancel(), and tryAdvance().
Referenced by doAdvance().
     {
         std::uint32_t seq = ledger->getLedgerSeq ();
         uint256 prevHash = ledger->getParentHash ();
         std::map< std::uint32_t, std::pair<uint256, uint256> > ledgerHashes;
         std::uint32_t minHas = ledger->getLedgerSeq ();
         std::uint32_t maxHas = ledger->getLedgerSeq ();
         while (! job.shouldCancel() && seq > 0)
         {
             {
                 ScopedLockType ml (m_mutex);
                 minHas = seq;
                 --seq;
                 if (haveLedger (seq))
                     break;
             }
             std::map< std::uint32_t, std::pair<uint256, uint256> >::iterator it = ledgerHashes.find (seq);
             if (it == ledgerHashes.end ())
             {
                 if (getApp().isShutdown ())
                     return;
                 {
                     ScopedLockType ml (mCompleteLock);
                     mCompleteLedgers.setRange (minHas, maxHas);
                 }
                 maxHas = minHas;
                 ledgerHashes = Ledger::getHashesByIndex ((seq < 500) ? 0 : (seq - 499), seq);
                 it = ledgerHashes.find (seq);
                 if (it == ledgerHashes.end ())
                     break;
             }
             if (it->second.first != prevHash)
                 break;
             prevHash = it->second.second;
         }
         {
             ScopedLockType ml (mCompleteLock);
             mCompleteLedgers.setRange (minHas, maxHas);
         }
         {
             ScopedLockType ml (m_mutex);
             mFillInProgress = 0;
             tryAdvance();
         }
     }
void ripple::LedgerMasterImp::tune (int size, int age) inline virtual
Implements ripple::LedgerMaster.
Definition at line 1416 of file LedgerMaster.cpp.
References mLedgerHistory, and ripple::LedgerHistory::tune().
     {
         mLedgerHistory.tune (size, age);
     }
void ripple::LedgerMasterImp::updatePaths (Job & job) inline
Definition at line 1150 of file LedgerMaster.cpp.
References ripple::LedgerHolder::empty(), ripple::InboundLedger::fcGENERIC, ripple::InboundLedgers::findCreate(), ripple::LedgerHolder::get(), ripple::getApp(), ripple::Job::getCancelCallback(), ripple::NetworkOPs::getCloseTimeNC(), ripple::getConfig(), ripple::Application::getInboundLedgers(), ripple::Application::getOPs(), ripple::Application::getPathRequests(), ripple::lsDEBUG, ripple::lsINFO, m_mutex, mCurrentLedger, mPathFindNewRequest, mPathFindThread, mPathLedger, mValidLedger, mValidLedgerSeq, ripple::Job::shouldCancel(), ripple::PathRequests::updateAll(), and WriteLog.
Referenced by newPFWork().
     {
         {
             ScopedLockType ml (m_mutex);
             if (getApp().getOPs().isNeedNetworkLedger () || mCurrentLedger.empty ())
             {
                 --mPathFindThread;
                 return;
             }
         }
         while (! job.shouldCancel())
         {
             Ledger::pointer lastLedger;
             {
                 ScopedLockType ml (m_mutex);
                 if (!mValidLedger.empty() &&
                     (!mPathLedger || (mPathLedger->getLedgerSeq() != mValidLedgerSeq)))
                 { // We have a new valid ledger since the last full pathfinding
                     mPathLedger = mValidLedger.get ();
                     lastLedger = mPathLedger;
                 }
                 else if (mPathFindNewRequest)
                 { // We have a new request but no new ledger
                     lastLedger = mCurrentLedger.get ();
                 }
                 else
                 { // Nothing to do
                     --mPathFindThread;
                     return;
                 }
             }
             if (!getConfig().RUN_STANDALONE)
             { // don't pathfind with a ledger that's more than 60 seconds old
                 std::int64_t age = getApp().getOPs().getCloseTimeNC();
                 age -= static_cast<std::int64_t> (lastLedger->getCloseTimeNC());
                 if (age > 60)
                 {
                     WriteLog (lsDEBUG, LedgerMaster) << "Published ledger too old for updating paths";
                     --mPathFindThread;
                     return;
                 }
             }
             try
             {
                 getApp().getPathRequests().updateAll (lastLedger, job.getCancelCallback ());
             }
             catch (SHAMapMissingNode&)
             {
                 WriteLog (lsINFO, LedgerMaster) << "Missing node detected during pathfinding";
                 getApp().getInboundLedgers().findCreate(lastLedger->getHash (), lastLedger->getLedgerSeq (),
                     InboundLedger::fcGENERIC);
             }
         }
     }
uint256 ripple::LedgerMasterImp::walkHashBySeq (std::uint32_t index) inline virtual
Walk to a ledger's hash using the skip list
Implements ripple::LedgerMaster.
Definition at line 1319 of file LedgerMaster.cpp.
References ripple::LedgerHolder::get(), and mValidLedger.
     {
         uint256 ledgerHash;
         Ledger::pointer referenceLedger;
         referenceLedger = mValidLedger.get ();
         if (referenceLedger)
             ledgerHash = walkHashBySeq (index, referenceLedger);
         return ledgerHash;
     }
uint256 ripple::LedgerMasterImp::walkHashBySeq (std::uint32_t index, Ledger::ref referenceLedger) inline virtual
Walk the chain of ledger hashed to determine the hash of the ledger with the specified index. The referenceLedger is used as the base of the chain and should be fully validated and must not precede the target index. This function may throw if nodes from the reference ledger or any prior ledger are not present in the node store.
Implements ripple::LedgerMaster.
Definition at line 1337 of file LedgerMaster.cpp.
References findAcquireLedger(), ripple::base_uint< BITS >::isNonZero(), and ripple::base_uint< BITS >::isZero().
     {
         uint256 ledgerHash;
         if (!referenceLedger || (referenceLedger->getLedgerSeq() < index))
             return ledgerHash; // Nothing we can do. No validated ledger.
         // See if the hash for the ledger we need is in the reference ledger
         ledgerHash = referenceLedger->getLedgerHash (index);
         if (ledgerHash.isZero())
         {
             // No, Try to get another ledger that might have the hash we need
             // Compute the index and hash of a ledger that will have the hash we need
             LedgerIndex refIndex = (index + 255) & (~255);
             LedgerHash refHash = referenceLedger->getLedgerHash (refIndex);
             bool const nonzero (refHash.isNonZero ());
             assert (nonzero);
             if (nonzero)
             {
                 // We found the hash and sequence of a better reference ledger
                 Ledger::pointer ledger = findAcquireLedger (refIndex, refHash);
                 if (ledger)
                 {
                     ledgerHash = ledger->getLedgerHash (index);
                     assert (ledgerHash.isNonZero());
                 }
             }
         }
         return ledgerHash;
     }
Member Data Documentation
beast::Journal ripple::LedgerMasterImp::m_journal
Definition at line 43 of file LedgerMaster.cpp.
LockType ripple::LedgerMasterImp::m_mutex
Definition at line 45 of file LedgerMaster.cpp.
Referenced by addHeldTransaction(), advanceThread(), checkAccept(), closeLedger(), doAdvance(), doTransaction(), findNewLedgersToPublish(), isNewPathRequest(), newOrderBookDB(), newPathRequest(), peekMutex(), pushLedger(), setFullLedger(), switchLedgers(), tryAdvance(), tryFill(), and updatePaths().
bool ripple::LedgerMasterImp::mAdvanceThread
Definition at line 69 of file LedgerMaster.cpp.
Referenced by advanceThread(), and tryAdvance().
bool ripple::LedgerMasterImp::mAdvanceWork
Definition at line 70 of file LedgerMaster.cpp.
Referenced by doAdvance(), and tryAdvance().
std::atomic<std::uint32_t> ripple::LedgerMasterImp::mBuildingLedgerSeq
Definition at line 81 of file LedgerMaster.cpp.
Referenced by checkAccept(), getBuildingLedger(), and setBuildingLedger().
LedgerHolder ripple::LedgerMasterImp::mClosedLedger
Definition at line 50 of file LedgerMaster.cpp.
Referenced by getClosedLedger(), getLedgerByHash(), getLedgerBySeq(), pushLedger(), and switchLedgers().
RangeSet ripple::LedgerMasterImp::mCompleteLedgers
Definition at line 60 of file LedgerMaster.cpp.
Referenced by clearLedger(), doAdvance(), getCompleteLedgers(), getFullValidatedRange(), getValidatedRange(), haveLedger(), haveLedgerRange(), setFullLedger(), setLedgerRangePresent(), and tryFill().
LockType ripple::LedgerMasterImp::mCompleteLock
Definition at line 59 of file LedgerMaster.cpp.
Referenced by clearLedger(), doAdvance(), getCompleteLedgers(), getFullValidatedRange(), getValidatedRange(), haveLedger(), haveLedgerRange(), setFullLedger(), setLedgerRangePresent(), and tryFill().
LedgerHolder ripple::LedgerMasterImp::mCurrentLedger
Definition at line 49 of file LedgerMaster.cpp.
Referenced by closeLedger(), doTransaction(), getCurrentLedger(), getCurrentLedgerIndex(), getLedgerByHash(), getLedgerBySeq(), pushLedger(), switchLedgers(), and updatePaths().
TransactionEngine ripple::LedgerMasterImp::mEngine
Definition at line 47 of file LedgerMaster.cpp.
Referenced by closeLedger(), doTransaction(), pushLedger(), and switchLedgers().
int ripple::LedgerMasterImp::mFillInProgress
Definition at line 71 of file LedgerMaster.cpp.
Referenced by doAdvance(), and tryFill().
CanonicalTXSet ripple::LedgerMasterImp::mHeldTransactions
Definition at line 57 of file LedgerMaster.cpp.
Referenced by addHeldTransaction(), and closeLedger().
uint256 ripple::LedgerMasterImp::mLastValidateHash
Definition at line 65 of file LedgerMaster.cpp.
Referenced by checkAccept(), and getNeededValidations().
std::uint32_t ripple::LedgerMasterImp::mLastValidateSeq
Definition at line 66 of file LedgerMaster.cpp.
Referenced by checkAccept().
std::unique_ptr<LedgerCleaner> ripple::LedgerMasterImp::mLedgerCleaner
Definition at line 62 of file LedgerMaster.cpp.
Referenced by doLedgerCleaner(), and getPropertySource().
LedgerHistory ripple::LedgerMasterImp::mLedgerHistory
Definition at line 55 of file LedgerMaster.cpp.
Referenced by checkAccept(), doAdvance(), findNewLedgersToPublish(), fixIndex(), getCacheHitRate(), getHashBySeq(), getLedgerByHash(), getLedgerBySeq(), pushLedger(), setFullLedger(), storeLedger(), sweep(), and tune().
int ripple::LedgerMasterImp::mMinValidations
Definition at line 64 of file LedgerMaster.cpp.
Referenced by getMinValidations(), getNeededValidations(), and setMinValidations().
std::list<callback> ripple::LedgerMasterImp::mOnValidate
Definition at line 67 of file LedgerMaster.cpp.
Referenced by addValidateCallback().
bool ripple::LedgerMasterImp::mPathFindNewLedger
Definition at line 74 of file LedgerMaster.cpp.
bool ripple::LedgerMasterImp::mPathFindNewRequest
Definition at line 75 of file LedgerMaster.cpp.
Referenced by isNewPathRequest(), newPathRequest(), and updatePaths().
int ripple::LedgerMasterImp::mPathFindThread
Definition at line 73 of file LedgerMaster.cpp.
Referenced by newPFWork(), and updatePaths().
Ledger::pointer ripple::LedgerMasterImp::mPathLedger
Definition at line 53 of file LedgerMaster.cpp.
Referenced by newOrderBookDB(), and updatePaths().
Ledger::pointer ripple::LedgerMasterImp::mPubLedger
Definition at line 52 of file LedgerMaster.cpp.
Referenced by checkAccept(), doAdvance(), findNewLedgersToPublish(), getPublishedLedger(), setFullLedger(), and setPubLedger().
std::atomic<std::uint32_t> ripple::LedgerMasterImp::mPubLedgerClose
Definition at line 77 of file LedgerMaster.cpp.
Referenced by getPublishedLedgerAge(), isCaughtUp(), and setPubLedger().
std::atomic<std::uint32_t> ripple::LedgerMasterImp::mPubLedgerSeq
Definition at line 78 of file LedgerMaster.cpp.
Referenced by doAdvance(), findNewLedgersToPublish(), getFullValidatedRange(), getValidatedRange(), and setPubLedger().
LedgerHolder ripple::LedgerMasterImp::mValidLedger
Definition at line 51 of file LedgerMaster.cpp.
Referenced by advanceThread(), findNewLedgersToPublish(), getValidatedLedger(), setValidLedger(), tryAdvance(), updatePaths(), and walkHashBySeq().
std::atomic<std::uint32_t> ripple::LedgerMasterImp::mValidLedgerClose
Definition at line 79 of file LedgerMaster.cpp.
Referenced by getValidatedLedgerAge(), isCaughtUp(), and setValidLedger().
std::atomic<std::uint32_t> ripple::LedgerMasterImp::mValidLedgerSeq
Definition at line 80 of file LedgerMaster.cpp.
Referenced by checkAccept(), consensusBuilt(), doAdvance(), findNewLedgersToPublish(), getValidLedgerIndex(), setFullLedger(), setValidLedger(), and updatePaths().
The documentation for this class was generated from the following file:
rippled/src/ripple_app/ledger/LedgerMaster.cpp