rippled: beast::SharedObject Class Reference
beast::SharedObject Class Reference
#include <SharedObject.h>
Public Member Functions
void incReferenceCount () const noexcept
void decReferenceCount () const
int getReferenceCount () const noexcept
Protected Member Functions
SharedObject ()
virtual ~SharedObject ()
virtual void destroy () const
void resetReferenceCount () noexcept
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Private Attributes
std::atomic< int > refCount
Detailed Description
Adds reference-counting to an object.
To add reference-counting to a class, derive it from this class, and use the SharedPtr class to point to it.
e.g.
class MyClass : public SharedObject
{
    void foo();
    // This is a neat way of declaring a typedef for a pointer class,
    // rather than typing out the full templated name each time..
    typedef SharedPtr<MyClass> Ptr;
};
MyClass::Ptr p = new MyClass();
MyClass::Ptr p2 = p;
p = nullptr;
p2->foo();
Once a new SharedObject has been assigned to a pointer, be careful not to delete the object manually.
This class uses an Atomic<int> value to hold the reference count, so that it the pointers can be passed between threads safely. For a faster but non-thread-safe version, use SingleThreadedSharedObject instead.
See Also
SharedPtr, SharedObjectArray, SingleThreadedSharedObject
Definition at line 66 of file SharedObject.h.
Constructor & Destructor Documentation
beast::SharedObject::SharedObject () inline protected
Creates the reference-counted object (with an initial ref count of zero).
Definition at line 105 of file SharedObject.h.
         : refCount (0)
     {
     }
virtual beast::SharedObject::~SharedObject () inline protected virtual
Destructor.
Definition at line 111 of file SharedObject.h.
References bassert, and getReferenceCount().
     {
         // it's dangerous to delete an object that's still referenced by something else!
         bassert (getReferenceCount() == 0);
     }
Member Function Documentation
void beast::SharedObject::decReferenceCount () const inline
Decreases the object's reference count.
If doDelete is true the object will be deleted when the reference count drops to zero. The delete is performed using the regular operator and does NOT go through the ContainerDeletePolicy.
The return value indicates if the reference count dropped to zero, so callers who know the derived type can use the ContainerDeletePolicy.
Definition at line 89 of file SharedObject.h.
References bassert, destroy(), getReferenceCount(), and refCount.
Referenced by beast::SharedSingleton< beast::sqdb::session::Sqlite3 >::onExit().
     {
         bassert (getReferenceCount() > 0);
         if (--refCount == 0)
             destroy ();
     }
virtual void beast::SharedObject::destroy () const inline protected virtual
Destroy the object. Derived classes can override this for different behaviors.
Reimplemented in beast::SharedSingleton< Object >, beast::SharedSingleton< beast::DeadlineTimer::Manager >, and beast::SharedSingleton< beast::sqdb::session::Sqlite3 >.
Definition at line 120 of file SharedObject.h.
Referenced by decReferenceCount().
     {
         delete this;
     }
int beast::SharedObject::getReferenceCount () const inline noexcept
Returns the object's current reference count.
Definition at line 97 of file SharedObject.h.
References refCount.
Referenced by decReferenceCount(), beast::SharedSingleton< beast::sqdb::session::Sqlite3 >::destroy(), and ~SharedObject().
     {
         return refCount.load();
     }
void beast::SharedObject::incReferenceCount () const inline noexcept
Increments the object's reference count.
This is done automatically by the smart pointer, but is public just in case it's needed for nefarious purposes.
Definition at line 75 of file SharedObject.h.
References refCount.
Referenced by beast::SharedPtr< beast::SharedSingleton< beast::sqdb::session::Sqlite3 > >::acquire(), and beast::SharedSingleton< beast::sqdb::session::Sqlite3 >::SharedSingleton().
     {
         ++refCount;
     }
void beast::SharedObject::resetReferenceCount () inline protected noexcept
Resets the reference count to zero without deleting the object. You should probably never need to use this!
Definition at line 128 of file SharedObject.h.
References refCount.
     {
         refCount.store (0);
     }
Member Data Documentation
std::atomic<int> beast::SharedObject::refCount mutable private
Definition at line 135 of file SharedObject.h.
Referenced by decReferenceCount(), getReferenceCount(), incReferenceCount(), and resetReferenceCount().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/smart_ptr/SharedObject.h