rippled: ripple::AccountStateSF Class Reference
ripple::AccountStateSF Class Reference
#include <SHAMapSyncFilters.h>
Public Member Functions
AccountStateSF (std::uint32_t ledgerSeq)
void gotNode (bool fromFilter, SHAMapNode const &id, uint256 const &nodeHash, Blob &nodeData, SHAMapTreeNode::TNType)
bool haveNode (SHAMapNode const &id, uint256 const &nodeHash, Blob &nodeData)
Public Member Functions inherited from ripple::SHAMapSyncFilter
virtual ~SHAMapSyncFilter ()
Private Attributes
std::uint32_t mLedgerSeq
Detailed Description
Definition at line 55 of file SHAMapSyncFilters.h.
Constructor & Destructor Documentation
ripple::AccountStateSF::AccountStateSF (std::uint32_t ledgerSeq) explicit
Definition at line 82 of file SHAMapSyncFilters.cpp.
     : mLedgerSeq (ledgerSeq)
 {
 }
Member Function Documentation
void ripple::AccountStateSF::gotNode (bool fromFilter, SHAMapNode const & id, uint256 const & nodeHash, Blob & nodeData, SHAMapTreeNode::TNType) virtual
Implements ripple::SHAMapSyncFilter.
Definition at line 87 of file SHAMapSyncFilters.cpp.
References ripple::getApp(), ripple::Application::getNodeStore(), ripple::hotACCOUNT_NODE, mLedgerSeq, and ripple::NodeStore::Database::store().
 {
     getApp().getNodeStore ().store (hotACCOUNT_NODE, mLedgerSeq, nodeData, nodeHash);
 }
bool ripple::AccountStateSF::haveNode (SHAMapNode const & id, uint256 const & nodeHash, Blob & nodeData) virtual
Implements ripple::SHAMapSyncFilter.
Definition at line 96 of file SHAMapSyncFilters.cpp.
References ripple::getApp(), ripple::NetworkOPs::getFetchPack(), and ripple::Application::getOPs().
 {
     return getApp().getOPs ().getFetchPack (nodeHash, nodeData);
 }
Member Data Documentation
std::uint32_t ripple::AccountStateSF::mLedgerSeq private
Definition at line 72 of file SHAMapSyncFilters.h.
Referenced by gotNode().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/shamap/SHAMapSyncFilters.h
rippled/src/ripple_app/shamap/SHAMapSyncFilters.cpp