rippled: ripple::PeerFinder::ManagerImp Class Reference
ripple::PeerFinder::ManagerImp Class Reference
Public Member Functions
ManagerImp (Stoppable &stoppable, SiteFiles::Manager &siteFiles, beast::File const &pathToDbFileOrDirectory, Callback &callback, clock_type &clock, beast::Journal journal)
~ManagerImp ()
void setConfig (Config const &config)
void addFixedPeer (std::string const &name, std::vector< beast::IP::Endpoint > const &addresses)
void addFallbackStrings (std::string const &name, std::vector< std::string > const &strings)
void addFallbackURL (std::string const &name, std::string const &url)
Slot::ptr new_inbound_slot (beast::IP::Endpoint const &local_endpoint, beast::IP::Endpoint const &remote_endpoint)
Slot::ptr new_outbound_slot (beast::IP::Endpoint const &remote_endpoint)
void on_connected (Slot::ptr const &slot, beast::IP::Endpoint const &local_endpoint)
void on_handshake (Slot::ptr const &slot, RipplePublicKey const &key, bool cluster)
void on_endpoints (Slot::ptr const &slot, Endpoints const &endpoints)
void on_legacy_endpoints (IPAddresses const &addresses)
void on_closed (Slot::ptr const &slot)
void on_cancel (Slot::ptr const &slot)
void parseBootstrapIPs (std::string const &name, SiteFiles::Section const &section)
void parseFixedIPs (SiteFiles::Section const &section)
void onSiteFileFetch (std::string const &name, SiteFiles::SiteFile const &siteFile)
void onPrepare ()
void onStart ()
void onStop ()
void onWrite (beast::PropertyStream::Map &map)
void onDeadlineTimer (beast::DeadlineTimer &timer)
void init ()
void run ()
Public Member Functions inherited from ripple::PeerFinder::Manager
virtual ~Manager ()
Public Member Functions inherited from beast::Stoppable
Stoppable (char const *name, Stoppable &parent)
virtual ~Stoppable ()
bool isStopping () const
bool isStopped () const
bool areChildrenStopped () const
void stopped ()
virtual void onChildrenStopped ()
Public Member Functions inherited from beast::PropertyStream::Source
Source (std::string const &name)
~Source ()
std::string const & name () const
void add (Source &source)
template<class Derived >
Derived * add (Derived *child)
void remove (Source &child)
void removeAll ()
void write_one (PropertyStream &stream)
void write (PropertyStream &stream)
void write (PropertyStream &stream, std::string const &path)
std::pair< Source *, bool > find (std::string path)
Source * find_one_deep (std::string const &name)
PropertyStream::Source * find_path (std::string path)
PropertyStream::Source * find_one (std::string const &name)
Public Member Functions inherited from beast::Thread
Thread (const String &threadName)
virtual ~Thread ()
void startThread ()
void startThread (int priority)
bool stopThread (int timeOutMilliseconds=-1)
void stopThreadAsync ()
bool isThreadRunning () const
void signalThreadShouldExit ()
bool threadShouldExit () const
bool waitForThreadToExit (int timeOutMilliseconds=-1) const
bool setPriority (int priority)
void setAffinityMask (std::uint32_t affinityMask)
bool wait (int timeOutMilliseconds=-1) const
void notify () const
ThreadID getThreadId () const noexcept
const String & getThreadName () const
Public Attributes
beast::ServiceQueue m_queue
SiteFiles::Manager & m_siteFiles
beast::File m_databaseFile
clock_type & m_clock
beast::Journal m_journal
StoreSqdb m_store
SerializedContext m_context
CheckerAdapter m_checker
Logic m_logic
beast::DeadlineTimer m_secondsTimer
Additional Inherited Members
Public Types inherited from beast::Thread
typedef void * ThreadID
Static Public Member Functions inherited from ripple::PeerFinder::Manager
static Manager * New (Stoppable &parent, SiteFiles::Manager &siteFiles, beast::File const &pathToDbFileOrDirectory, Callback &callback, clock_type &clock, beast::Journal journal)
Static Public Member Functions inherited from beast::Thread
static bool setCurrentThreadPriority (int priority)
static void setCurrentThreadAffinityMask (std::uint32_t affinityMask)
static void sleep (int milliseconds)
static void yield ()
static ThreadID getCurrentThreadId ()
static Thread * getCurrentThread ()
static void setCurrentThreadName (const String &newThreadName)
Protected Member Functions inherited from ripple::PeerFinder::Manager
Manager (Stoppable &parent)
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Protected Attributes inherited from beast::Stoppable
char const * m_name
RootStoppable & m_root
Child m_child
Atomic< int > m_started
bool volatile m_stopped
bool volatile m_childrenStopped
Children m_children
WaitableEvent m_stoppedEvent
Detailed Description
Definition at line 23 of file Manager.cpp.
Constructor & Destructor Documentation
ripple::PeerFinder::ManagerImp::ManagerImp (Stoppable & stoppable, SiteFiles::Manager & siteFiles, beast::File const & pathToDbFileOrDirectory, Callback & callback, clock_type & clock, beast::Journal journal) inline
Definition at line 44 of file Manager.cpp.
References beast::File::getChildFile(), beast::File::isDirectory(), and m_databaseFile.
         : Manager (stoppable)
         , Thread ("PeerFinder")
         , m_siteFiles (siteFiles)
         , m_databaseFile (pathToDbFileOrDirectory)
         , m_clock (clock)
         , m_journal (journal)
         , m_store (journal)
         , m_checker (m_context, m_queue)
         , m_logic (clock, callback, m_store, m_checker, journal)
         , m_secondsTimer (this)
     {
         if (m_databaseFile.isDirectory ())
             m_databaseFile = m_databaseFile.getChildFile("peerfinder.sqlite");
     }
ripple::PeerFinder::ManagerImp::~ManagerImp () inline
Definition at line 66 of file Manager.cpp.
References beast::Thread::stopThread().
     {
         stopThread ();
     }
Member Function Documentation
void ripple::PeerFinder::ManagerImp::addFallbackStrings (std::string const & name, std::vector< std::string > const & strings) inline virtual
Add a set of strings as fallback IP::Endpoint sources.
Parameters
name A label used for diagnostics.
Implements ripple::PeerFinder::Manager.
Definition at line 94 of file Manager.cpp.
References ripple::PeerFinder::Logic::addStaticSource(), beast::ServiceQueueType< Allocator >::dispatch(), m_context, m_logic, m_queue, ripple::PeerFinder::SourceStrings::New(), and beast::ScopedWrapperContext< Context, ScopedType >::wrap().
     {
         m_queue.dispatch (
             m_context.wrap (
                 std::bind (&Logic::addStaticSource, &m_logic,
                     SourceStrings::New (name, strings))));
     }
void ripple::PeerFinder::ManagerImp::addFallbackURL (std::string const & name, std::string const & url) inline
Definition at line 103 of file Manager.cpp.
     {
         // VFALCO TODO This needs to be implemented
     }
void ripple::PeerFinder::ManagerImp::addFixedPeer (std::string const & name, std::vector< beast::IP::Endpoint > const & addresses) inline virtual
Add a peer that should always be connected. This is useful for maintaining a private cluster of peers. The string is the name as specified in the configuration file, along with the set of corresponding IP addresses.
Implements ripple::PeerFinder::Manager.
Definition at line 85 of file Manager.cpp.
References ripple::PeerFinder::Logic::addFixedPeer(), beast::ServiceQueueType< Allocator >::dispatch(), m_context, m_logic, m_queue, and beast::ScopedWrapperContext< Context, ScopedType >::wrap().
     {
         m_queue.dispatch (
             m_context.wrap (
                 boost::bind (&Logic::addFixedPeer, &m_logic,
                     name, addresses)));
     }
void ripple::PeerFinder::ManagerImp::init () inline
Definition at line 266 of file Manager.cpp.
References beast::Journal::debug, beast::Journal::fatal, beast::File::getFullPathName(), ripple::PeerFinder::Logic::load(), m_databaseFile, m_journal, m_logic, m_secondsTimer, m_store, ripple::PeerFinder::StoreSqdb::open(), and beast::DeadlineTimer::setExpiration().
Referenced by run().
     {
         m_journal.debug << "Initializing";
         beast::Error error (m_store.open (m_databaseFile));
         if (error)
         {
             m_journal.fatal <<
                 "Failed to open '" << m_databaseFile.getFullPathName() << "'";
         }
         if (! error)
         {
             m_logic.load ();
         }
         m_secondsTimer.setExpiration (std::chrono::seconds (1));
     }
Slot::ptr ripple::PeerFinder::ManagerImp::new_inbound_slot (beast::IP::Endpoint const & local_endpoint, beast::IP::Endpoint const & remote_endpoint) inline virtual
Add a URL as a fallback location to obtain IP::Endpoint sources.
Parameters
name A label used for diagnostics.Create a new inbound slot with the specified remote endpoint. If nullptr is returned, then the slot could not be assigned. Usually this is because of a detected self-connection.
Implements ripple::PeerFinder::Manager.
Definition at line 110 of file Manager.cpp.
References m_logic, and ripple::PeerFinder::Logic::new_inbound_slot().
     {
         return m_logic.new_inbound_slot (local_endpoint, remote_endpoint);
     }
Slot::ptr ripple::PeerFinder::ManagerImp::new_outbound_slot (beast::IP::Endpoint const & remote_endpoint) inline virtual
Create a new outbound slot with the specified remote endpoint. If nullptr is returned, then the slot could not be assigned. Usually this is because of a duplicate connection.
Implements ripple::PeerFinder::Manager.
Definition at line 117 of file Manager.cpp.
References m_logic, and ripple::PeerFinder::Logic::new_outbound_slot().
     {
         return m_logic.new_outbound_slot (remote_endpoint);
     }
void ripple::PeerFinder::ManagerImp::on_cancel (Slot::ptr const & slot) inline virtual
Called when the slot is closed via canceling operations. This is instead of on_closed.
Implements ripple::PeerFinder::Manager.
Definition at line 154 of file Manager.cpp.
References m_logic, and ripple::PeerFinder::Logic::on_cancel().
     {
         SlotImp::ptr impl (std::dynamic_pointer_cast <SlotImp> (slot));
         m_logic.on_cancel (impl);
     }
void ripple::PeerFinder::ManagerImp::on_closed (Slot::ptr const & slot) inline virtual
Called when the slot is closed. This always happens when the socket is closed, unless the socket was canceled.
Implements ripple::PeerFinder::Manager.
Definition at line 148 of file Manager.cpp.
References m_logic, and ripple::PeerFinder::Logic::on_closed().
     {
         SlotImp::ptr impl (std::dynamic_pointer_cast <SlotImp> (slot));
         m_logic.on_closed (impl);
     }
void ripple::PeerFinder::ManagerImp::on_connected (Slot::ptr const & slot, beast::IP::Endpoint const & local_endpoint) inline virtual
Called when an outbound connection attempt succeeds. The local endpoint must be valid. If the caller receives an error when retrieving the local endpoint from the socket, it should proceed as if the connection attempt failed by calling on_closed instead of on_connected.
Implements ripple::PeerFinder::Manager.
Definition at line 122 of file Manager.cpp.
References m_logic, and ripple::PeerFinder::Logic::on_connected().
     {
         SlotImp::ptr impl (std::dynamic_pointer_cast <SlotImp> (slot));
         m_logic.on_connected (impl, local_endpoint);
     }
void ripple::PeerFinder::ManagerImp::on_endpoints (Slot::ptr const & slot, Endpoints const & endpoints) inline virtual
Called when mtENDPOINTS is received.
Implements ripple::PeerFinder::Manager.
Definition at line 136 of file Manager.cpp.
References m_logic, and ripple::PeerFinder::Logic::on_endpoints().
     {
         SlotImp::ptr impl (std::dynamic_pointer_cast <SlotImp> (slot));
         m_logic.on_endpoints (impl, endpoints);
     }
void ripple::PeerFinder::ManagerImp::on_handshake (Slot::ptr const & slot, RipplePublicKey const & key, bool cluster) inline virtual
Called when a handshake is completed.
Implements ripple::PeerFinder::Manager.
Definition at line 129 of file Manager.cpp.
References m_logic, and ripple::PeerFinder::Logic::on_handshake().
     {
         SlotImp::ptr impl (std::dynamic_pointer_cast <SlotImp> (slot));
         m_logic.on_handshake (impl, key, cluster);
     }
void ripple::PeerFinder::ManagerImp::on_legacy_endpoints (IPAddresses const & addresses) inline virtual
Called when legacy IP/port addresses are received.
Implements ripple::PeerFinder::Manager.
Definition at line 143 of file Manager.cpp.
References m_logic, and ripple::PeerFinder::Logic::on_legacy_endpoints().
     {
         m_logic.on_legacy_endpoints (addresses);
     }
void ripple::PeerFinder::ManagerImp::onDeadlineTimer (beast::DeadlineTimer & timer) inline virtual
Reimplemented from beast::DeadlineTimer::Listener.
Definition at line 254 of file Manager.cpp.
References beast::ServiceQueueType< Allocator >::dispatch(), m_context, m_logic, m_queue, m_secondsTimer, ripple::PeerFinder::Logic::periodicActivity(), ripple::PeerFinder::Tuning::secondsPerConnect, beast::DeadlineTimer::setExpiration(), and beast::ScopedWrapperContext< Context, ScopedType >::wrap().
     {
         if (timer == m_secondsTimer)
         {
             m_queue.dispatch (
                 m_context.wrap (
                     std::bind (&Logic::periodicActivity, &m_logic)));
             m_secondsTimer.setExpiration (Tuning::secondsPerConnect);
         }
     }
void ripple::PeerFinder::ManagerImp::onPrepare () inline virtual
Override called during preparation. Since all other Stoppable objects in the tree have already been constructed, this provides an opportunity to perform initialization which depends on calling into other Stoppable objects. This call is made on the same thread that called prepare(). The default implementation does nothing. Guaranteed to only be called once.
Reimplemented from beast::Stoppable.
Definition at line 219 of file Manager.cpp.
     {
     }
void ripple::PeerFinder::ManagerImp::onSiteFileFetch (std::string const & name, SiteFiles::SiteFile const & siteFile) inline virtual
Called every time a new site file is retrieved. Notifications for Site files retrieved before a listener was added will be sent at the time the listener is added.
Implements ripple::SiteFiles::Listener.
Definition at line 204 of file Manager.cpp.
References parseBootstrapIPs().
     {
         parseBootstrapIPs (name, siteFile["ips"]);
         //if (name == "local")
         //  parseFixedIPs (name, siteFile["ips_fixed"]);
     }
void ripple::PeerFinder::ManagerImp::onStart () inline virtual
Override called during start.
Reimplemented from beast::Stoppable.
Definition at line 223 of file Manager.cpp.
References beast::Thread::startThread().
     {
         startThread();
     }
void ripple::PeerFinder::ManagerImp::onStop () inline virtual
Override called when the stop notification is issued.
The call is made on an unspecified, implementation-specific thread. onStop and onChildrenStopped will never be called concurrently, across all Stoppable objects descended from the same root, inclusive of the root.
It is safe to call isStopping, isStopped, and areChildrenStopped from within this function; The values returned will always be valid and never change during the callback.
The default implementation simply calls stopped(). This is applicable when the Stoppable has a trivial stop operation (or no stop operation), and we are merely using the Stoppable API to position it as a dependency of some parent service.
Thread safety: May not block for long periods. Guaranteed only to be called once. Must be safe to call from any thread at any time.
Reimplemented from beast::Stoppable.
Definition at line 228 of file Manager.cpp.
References beast::DeadlineTimer::cancel(), ripple::PeerFinder::CheckerAdapter::cancel(), beast::Journal::debug, beast::ServiceQueueType< Allocator >::dispatch(), m_checker, m_context, m_journal, m_logic, m_queue, m_secondsTimer, ripple::PeerFinder::Logic::stop(), and beast::ScopedWrapperContext< Context, ScopedType >::wrap().
     {
         m_journal.debug << "Stopping";
         m_checker.cancel ();
         m_logic.stop ();
         m_secondsTimer.cancel();
         m_queue.dispatch (
             m_context.wrap (
                 std::bind (&Thread::signalThreadShouldExit, this)));
     }
void ripple::PeerFinder::ManagerImp::onWrite (beast::PropertyStream::Map &) inline virtual
Subclass override. The default version does nothing.
Reimplemented from beast::PropertyStream::Source.
Definition at line 245 of file Manager.cpp.
References m_context, m_logic, and ripple::PeerFinder::Logic::onWrite().
     {
         SerializedContext::Scope scope (m_context);
         m_logic.onWrite (map);
     }
void ripple::PeerFinder::ManagerImp::parseBootstrapIPs (std::string const & name, SiteFiles::Section const & section) inline
Definition at line 166 of file Manager.cpp.
References ripple::SiteFiles::Section::data(), beast::IP::Endpoint::from_string(), beast::IP::Endpoint::from_string_altform(), beast::Journal::info, beast::IP::is_unspecified(), m_journal, and beast::PropertyStream::Source::name().
Referenced by onSiteFileFetch().
     {
         std::size_t n (0);
         for (SiteFiles::Section::DataType::const_iterator iter (
             section.data().begin()); iter != section.data().end(); ++iter)
         {
             std::string const& s (*iter);
             beast::IP::Endpoint addr (beast::IP::Endpoint::from_string (s));
             if (is_unspecified (addr))
                 addr = beast::IP::Endpoint::from_string_altform(s);
             if (! is_unspecified (addr))
             {
                 // add IP::Endpoint to bootstrap cache
                 ++n;
             }
         }
         m_journal.info <<
             "Added " << n <<
             " bootstrap IPs from " << name;
     }
void ripple::PeerFinder::ManagerImp::parseFixedIPs (SiteFiles::Section const & section) inline
Definition at line 188 of file Manager.cpp.
References ripple::SiteFiles::Section::data(), beast::IP::Endpoint::from_string(), beast::IP::Endpoint::from_string_altform(), and beast::IP::is_unspecified().
     {
         for (SiteFiles::Section::DataType::const_iterator iter (
             section.data().begin()); iter != section.data().end(); ++iter)
         {
             std::string const& s (*iter);
             beast::IP::Endpoint addr (beast::IP::Endpoint::from_string (s));
             if (is_unspecified (addr))
                 addr = beast::IP::Endpoint::from_string_altform(s);
             if (! is_unspecified (addr))
             {
                 // add IP::Endpoint to fixed peers
             }
         }
     }
void ripple::PeerFinder::ManagerImp::run () inline virtual
Must be implemented to perform the thread's actual code.
Remember that the thread must regularly check the threadShouldExit() method whilst running, and if this returns true it should return from the run() method as soon as possible to avoid being forcibly killed.
See Also
threadShouldExit, startThread
Implements beast::Thread.
Definition at line 286 of file Manager.cpp.
References ripple::SiteFiles::Manager::addListener(), beast::Journal::debug, init(), m_journal, m_queue, m_siteFiles, ripple::SiteFiles::Manager::removeListener(), beast::ServiceQueueType< Allocator >::run_one(), beast::Stoppable::stopped(), and beast::Thread::threadShouldExit().
     {
         m_journal.debug << "Started";
         init ();
         m_siteFiles.addListener (*this);
         while (! this->threadShouldExit())
         {
             m_queue.run_one();
         }
         m_siteFiles.removeListener (*this);
         stopped();
     }
void ripple::PeerFinder::ManagerImp::setConfig (Config const & config) inline virtual
Set the configuration for the manager. The new settings will be applied asynchronously. Thread safety: Can be called from any threads at any time.
Implements ripple::PeerFinder::Manager.
Definition at line 77 of file Manager.cpp.
References beast::ServiceQueueType< Allocator >::dispatch(), m_context, m_logic, m_queue, ripple::PeerFinder::Logic::setConfig(), and beast::ScopedWrapperContext< Context, ScopedType >::wrap().
     {
         m_queue.dispatch (
             m_context.wrap (
                 std::bind (&Logic::setConfig, &m_logic,
                     config)));
     }
Member Data Documentation
CheckerAdapter ripple::PeerFinder::ManagerImp::m_checker
Definition at line 38 of file Manager.cpp.
Referenced by onStop().
clock_type& ripple::PeerFinder::ManagerImp::m_clock
Definition at line 34 of file Manager.cpp.
SerializedContext ripple::PeerFinder::ManagerImp::m_context
Definition at line 37 of file Manager.cpp.
Referenced by addFallbackStrings(), addFixedPeer(), onDeadlineTimer(), onStop(), onWrite(), and setConfig().
beast::File ripple::PeerFinder::ManagerImp::m_databaseFile
Definition at line 33 of file Manager.cpp.
Referenced by init(), and ManagerImp().
beast::Journal ripple::PeerFinder::ManagerImp::m_journal
Definition at line 35 of file Manager.cpp.
Referenced by init(), onStop(), parseBootstrapIPs(), and run().
Logic ripple::PeerFinder::ManagerImp::m_logic
Definition at line 39 of file Manager.cpp.
Referenced by addFallbackStrings(), addFixedPeer(), init(), new_inbound_slot(), new_outbound_slot(), on_cancel(), on_closed(), on_connected(), on_endpoints(), on_handshake(), on_legacy_endpoints(), onDeadlineTimer(), onStop(), onWrite(), and setConfig().
beast::ServiceQueue ripple::PeerFinder::ManagerImp::m_queue
Definition at line 31 of file Manager.cpp.
Referenced by addFallbackStrings(), addFixedPeer(), onDeadlineTimer(), onStop(), run(), and setConfig().
beast::DeadlineTimer ripple::PeerFinder::ManagerImp::m_secondsTimer
Definition at line 40 of file Manager.cpp.
Referenced by init(), onDeadlineTimer(), and onStop().
SiteFiles::Manager& ripple::PeerFinder::ManagerImp::m_siteFiles
Definition at line 32 of file Manager.cpp.
Referenced by run().
StoreSqdb ripple::PeerFinder::ManagerImp::m_store
Definition at line 36 of file Manager.cpp.
Referenced by init().
The documentation for this class was generated from the following file:
rippled/src/ripple/peerfinder/impl/Manager.cpp