rippled: ripple::SHAMapMissingNode Class Reference
ripple::SHAMapMissingNode Class Reference
#include <SHAMapMissingNode.h>
Public Member Functions
SHAMapMissingNode (SHAMapType t, SHAMapNode const &nodeID, uint256 const &nodeHash)
SHAMapMissingNode (SHAMapType t, SHAMapNode const &nodeID, uint256 const &nodeHash, uint256 const &targetIndex)
virtual ~SHAMapMissingNode () throw ()
void setTargetNode (uint256 const &tn)
SHAMapType getMapType () const
SHAMapNode const & getNodeID () const
uint256 const & getNodeHash () const
uint256 const & getTargetIndex () const
bool hasTargetIndex () const
Private Attributes
SHAMapType mType
SHAMapNode mNodeID
uint256 mNodeHash
uint256 mTargetIndex
Detailed Description
Definition at line 32 of file SHAMapMissingNode.h.
Constructor & Destructor Documentation
ripple::SHAMapMissingNode::SHAMapMissingNode (SHAMapType t, SHAMapNode const & nodeID, uint256 const & nodeHash) inline
Definition at line 35 of file SHAMapMissingNode.h.
         : std::runtime_error ("SHAMapMissingNode")
         , mType (t)
         , mNodeID (nodeID)
         , mNodeHash (nodeHash)
     {
     }
ripple::SHAMapMissingNode::SHAMapMissingNode (SHAMapType t, SHAMapNode const & nodeID, uint256 const & nodeHash, uint256 const & targetIndex) inline
Definition at line 45 of file SHAMapMissingNode.h.
         : std::runtime_error (nodeID.getString ())
         , mType (t)
         , mNodeID (nodeID)
         , mNodeHash (nodeHash)
         , mTargetIndex (targetIndex)
     {
     }
virtual ripple::SHAMapMissingNode::~SHAMapMissingNode () throw () inline virtual
Definition at line 57 of file SHAMapMissingNode.h.
     {
     }
Member Function Documentation
SHAMapType ripple::SHAMapMissingNode::getMapType () const inline
Definition at line 66 of file SHAMapMissingNode.h.
References mType.
Referenced by ripple::operator<<().
     {
         return mType;
     }
uint256 const& ripple::SHAMapMissingNode::getNodeHash () const inline
Definition at line 76 of file SHAMapMissingNode.h.
References mNodeHash.
Referenced by ripple::operator<<().
     {
         return mNodeHash;
     }
SHAMapNode const& ripple::SHAMapMissingNode::getNodeID () const inline
Definition at line 71 of file SHAMapMissingNode.h.
References mNodeID.
Referenced by ripple::operator<<().
     {
         return mNodeID;
     }
uint256 const& ripple::SHAMapMissingNode::getTargetIndex () const inline
Definition at line 81 of file SHAMapMissingNode.h.
References mTargetIndex.
     {
         return mTargetIndex;
     }
bool ripple::SHAMapMissingNode::hasTargetIndex () const inline
Definition at line 86 of file SHAMapMissingNode.h.
References ripple::base_uint< BITS >::isZero(), and mTargetIndex.
     {
         return !mTargetIndex.isZero ();
     }
void ripple::SHAMapMissingNode::setTargetNode (uint256 const & tn) inline
Definition at line 61 of file SHAMapMissingNode.h.
References mTargetIndex.
Referenced by ripple::SHAMap::getStack(), and ripple::SHAMap::walkTo().
     {
         mTargetIndex = tn;
     }
Member Data Documentation
uint256 ripple::SHAMapMissingNode::mNodeHash private
Definition at line 94 of file SHAMapMissingNode.h.
Referenced by getNodeHash().
SHAMapNode ripple::SHAMapMissingNode::mNodeID private
Definition at line 93 of file SHAMapMissingNode.h.
Referenced by getNodeID().
uint256 ripple::SHAMapMissingNode::mTargetIndex private
Definition at line 95 of file SHAMapMissingNode.h.
Referenced by getTargetIndex(), hasTargetIndex(), and setTargetNode().
SHAMapType ripple::SHAMapMissingNode::mType private
Definition at line 92 of file SHAMapMissingNode.h.
Referenced by getMapType().
The documentation for this class was generated from the following file:
rippled/src/ripple_app/shamap/SHAMapMissingNode.h