rippled: rocksdb::BlockHandle Class Reference
rocksdb::BlockHandle Class Reference
#include <format.h>
Public Types
enum { kMaxEncodedLength = 10 + 10 }
Public Member Functions
BlockHandle ()
uint64_t offset () const
void set_offset (uint64_t offset)
uint64_t size () const
void set_size (uint64_t size)
void EncodeTo (std::string *dst) const
Status DecodeFrom (Slice *input)
Private Attributes
uint64_t offset_
uint64_t size_
Detailed Description
Definition at line 26 of file format.h.
Member Enumeration Documentation
anonymous enum
Enumerator
kMaxEncodedLength
Definition at line 42 of file format.h.
 { kMaxEncodedLength = 10 + 10 };
Constructor & Destructor Documentation
rocksdb::BlockHandle::BlockHandle () inline
Definition at line 117 of file format.h.
     : offset_(~static_cast<uint64_t>(0)),
       size_(~static_cast<uint64_t>(0)) {
 }
Member Function Documentation
Status rocksdb::BlockHandle::DecodeFrom (Slice * input)
Definition at line 29 of file format.cc.
References rocksdb::Status::Corruption(), rocksdb::GetVarint64(), offset_, rocksdb::Status::OK(), and size_.
Referenced by rocksdb::BlockBasedTable::ApproximateOffsetOf(), rocksdb::BlockBasedTable::BlockReader(), rocksdb::Footer::DecodeFrom(), rocksdb::BlockBasedTable::Get(), rocksdb::BlockBasedTable::PrefixMayMatch(), rocksdb::BlockBasedTable::ReadFilter(), and rocksdb::BlockBasedTable::ReadProperties().
{
   if (GetVarint64(input, &offset_) &&
       GetVarint64(input, &size_)) {
     return Status::OK();
   } else {
     return Status::Corruption("bad block handle");
   }
 }
void rocksdb::BlockHandle::EncodeTo (std::string * dst) const
Definition at line 21 of file format.cc.
References offset_, rocksdb::PutVarint64(), and size_.
Referenced by rocksdb::BlockBasedTableBuilder::Add(), rocksdb::Footer::EncodeTo(), and rocksdb::BlockBasedTableBuilder::Finish().
{
   // Sanity check that all fields have been set
   assert(offset_ != ~static_cast<uint64_t>(0));
   assert(size_ != ~static_cast<uint64_t>(0));
   PutVarint64(dst, offset_);
   PutVarint64(dst, size_);
 }
uint64_t rocksdb::BlockHandle::offset () const inline
Definition at line 31 of file format.h.
References offset_.
Referenced by rocksdb::BlockBasedTable::ApproximateOffsetOf(), rocksdb::BlockBasedTable::Get(), rocksdb::BlockBasedTableBuilder::InsertBlockInCache(), rocksdb::BlockBasedTable::PrefixMayMatch(), rocksdb::ReadBlockContents(), and set_offset().
 { return offset_; }
void rocksdb::BlockHandle::set_offset (uint64_t offset) inline
Definition at line 32 of file format.h.
References offset(), and offset_.
Referenced by rocksdb::BlockBasedTableBuilder::WriteRawBlock().
 { offset_ = offset; }
void rocksdb::BlockHandle::set_size (uint64_t size) inline
Definition at line 36 of file format.h.
References size(), and size_.
Referenced by rocksdb::BlockBasedTableBuilder::WriteRawBlock().
 { size_ = size; }
uint64_t rocksdb::BlockHandle::size () const inline
Definition at line 35 of file format.h.
References size_.
Referenced by rocksdb::ReadBlockContents(), and set_size().
 { return size_; }
Member Data Documentation
uint64_t rocksdb::BlockHandle::offset_ private
Definition at line 45 of file format.h.
Referenced by DecodeFrom(), EncodeTo(), offset(), and set_offset().
uint64_t rocksdb::BlockHandle::size_ private
Definition at line 46 of file format.h.
Referenced by DecodeFrom(), EncodeTo(), set_size(), and size().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/table/format.h
rippled/src/ripple/rocksdb/rocksdb/table/format.cc