rippled: ripple::LogPartition Class Reference
ripple::LogPartition Class Reference
#include <LogPartition.h>
Public Types
typedef std::vector< std::pair
< std::string, std::string > > Severities
Public Member Functions
void write (beast::Journal::Severity level, std::string const &text)
LogPartition (std::string const &name)
bool doLog (LogSeverity s) const
std::string const & getName () const
LogSeverity getSeverity () const
void setMinimumSeverity (LogSeverity severity)
template<>
char const * getPartitionName ()
template<>
char const * getPartitionName ()
template<>
char const * getPartitionName ()
template<>
char const * getPartitionName ()
template<>
char const * getPartitionName ()
template<>
char const * getPartitionName ()
template<>
char const * getPartitionName ()
template<>
char const * getPartitionName ()
template<>
char const * getPartitionName ()
template<>
char const * getPartitionName ()
template<>
char const * getPartitionName ()
template<>
char const * getPartitionName ()
template<>
char const * getPartitionName ()
template<>
char const * getPartitionName ()
template<>
char const * getPartitionName ()
template<>
char const * getPartitionName ()
template<>
char const * getPartitionName ()
template<>
char const * getPartitionName ()
template<>
char const * getPartitionName ()
template<>
char const * getPartitionName ()
template<>
char const * getPartitionName ()
template<>
char const * getPartitionName ()
template<>
char const * getPartitionName ()
template<>
char const * getPartitionName ()
template<>
char const * getPartitionName ()
template<>
char const * getPartitionName ()
template<class Key >
LogPartition & get ()
template<>
char const * getPartitionName ()
template<>
char const * getPartitionName ()
template<>
char const * getPartitionName ()
Public Member Functions inherited from beast::Journal::Sink
Sink ()
virtual ~Sink ()=0
virtual bool active (Severity level) const
virtual bool console () const
virtual void console (bool output)
virtual Severity severity () const
virtual void severity (Severity level)
Static Public Member Functions
template<class Key >
static LogPartition & get ()
template<class Key >
static beast::Journal getJournal ()
static std::string canonicalFileName (char const *fileName)
static LogPartition * find (std::string const &name)
static void setSeverity (LogSeverity severity)
static bool setSeverity (std::string const &name, LogSeverity severity)
static void setConsoleOutput (std::string const &list)
static Severities getSeverities ()
template<class Key >
static char const * getPartitionName ()
static LogSeverity convertSeverity (beast::Journal::Severity level)
static beast::Journal::Severity convertLogSeverity (LogSeverity level)
Private Attributes
LogPartition * mNextLog
std::string mName
Static Private Attributes
static LogPartition * headLog = nullptr
Detailed Description
Definition at line 25 of file LogPartition.h.
Member Typedef Documentation
typedef std::vector<std::pair <std::string, std::string> > ripple::LogPartition::Severities
Returns a list of all partitions and their severity levels.
Definition at line 82 of file LogPartition.h.
Constructor & Destructor Documentation
ripple::LogPartition::LogPartition (std::string const & name) explicit
Construct the partition with the specified name.
Definition at line 36 of file LogPartition.cpp.
References headLog, beast::Journal::kWarning, and beast::Journal::Sink::severity().
     : mNextLog (headLog)
     , mName (canonicalFileName (name.c_str()))
 {
     severity (beast::Journal::kWarning);
     // VFALCO TODO Use an intrusive list.
     headLog = this;
 }
Member Function Documentation
std::string ripple::LogPartition::canonicalFileName (char const * fileName) static
Returns a cleaned up source code file name.
Definition at line 69 of file LogPartition.cpp.
 {
     std::string result;
     char const* ptr (strrchr (fileName, '/'));
     result = (ptr == nullptr) ? fileName : (ptr + 1);
     size_t p = result.find (".cpp");
     if (p != std::string::npos)
         result.erase (result.begin () + p, result.end ());
     return result;
 }
beast::Journal::Severity ripple::LogPartition::convertLogSeverity (LogSeverity level) static
Definition at line 162 of file LogPartition.cpp.
References bassertfalse, ripple::lsDEBUG, ripple::lsERROR, ripple::lsFATAL, ripple::lsINFO, ripple::lsTRACE, and ripple::lsWARNING.
Referenced by setMinimumSeverity(), and ripple::Log::~Log().
 {
     using beast::Journal;
     switch (level)
     {
     case lsTRACE:   return Journal::kTrace;
     case lsDEBUG:   return Journal::kDebug;
     case lsINFO:    return Journal::kInfo;
     case lsWARNING: return Journal::kWarning;
     case lsERROR:   return Journal::kError;
     default:
         bassertfalse;
     case lsFATAL:
         break;
     }
     return Journal::kFatal;
 }
LogSeverity ripple::LogPartition::convertSeverity (beast::Journal::Severity level) static
Convert the Journal::Severity to and from a LogSeverity.
Definition at line 142 of file LogPartition.cpp.
References bassertfalse, ripple::lsDEBUG, ripple::lsERROR, ripple::lsFATAL, ripple::lsINFO, ripple::lsTRACE, and ripple::lsWARNING.
Referenced by getSeverity(), and write().
 {
     using beast::Journal;
     switch (level)
     {
     case Journal::kTrace:   return lsTRACE;
     case Journal::kDebug:   return lsDEBUG;
     case Journal::kInfo:    return lsINFO;
     case Journal::kWarning: return lsWARNING;
     case Journal::kError:   return lsERROR;
     default:
         bassertfalse;
     case Journal::kFatal:
         break;
     }
     return lsFATAL;
 }
bool ripple::LogPartition::doLog (LogSeverity s) const
Returns true output is produced at the given severity.
Definition at line 45 of file LogPartition.cpp.
References getSeverity().
Referenced by AutoSocket::handle_autodetect(), websocketpp::log::websocketLog(), and ripple::Log::~Log().
 {
     return s >= getSeverity();
 }
LogPartition * ripple::LogPartition::find (std::string const & name) static
Returns the partition with the given name or nullptr if no match.
Definition at line 83 of file LogPartition.cpp.
References headLog, mNextLog, and name.
Referenced by setConsoleOutput(), and setSeverity().
 {
     for (LogPartition* p = headLog; p != nullptr; p = p->mNextLog)
         if (boost::iequals (p->getName(), name))
             return p;
     return nullptr;
 }
template<class Key > static static_call init_NameResolverLog & ripple::LogPartition::get () static
Returns the LogPartition based on a type key.
Definition at line 52 of file OverlayImpl.cpp.
template<class Key > LogPartition& ripple::LogPartition::get ()
Definition at line 118 of file LogPartition.h.
 {
     return *beast::SharedSingleton <
       detail::LogPartitionType <Key>>::getInstance();
 }
template<class Key > static beast::Journal ripple::LogPartition::getJournal () inline static
Returns a Journal using the specified LogPartition type key.
Definition at line 61 of file LogPartition.h.
     {
         return beast::Journal (get <Key> ());
     }
std::string const & ripple::LogPartition::getName () const
Returns the name of this partition.
Definition at line 50 of file LogPartition.cpp.
References mName.
 {
     return mName;
 }
template<> char const* ripple::LogPartition::getPartitionName ()
Definition at line 25 of file InboundLedger.cpp.
 { return "InLedger"; }
template<> char const* ripple::LogPartition::getPartitionName ()
Definition at line 25 of file TransactionAcquire.cpp.
 { return "TxAcquire"; }
template<> char const* ripple::LogPartition::getPartitionName ()
Definition at line 29 of file AccountSetTransactor.h.
 {
     return "Tx/AccountSet";
 }
template<> char const* ripple::LogPartition::getPartitionName ()
Definition at line 29 of file ChangeTransactor.h.
 {
     return "Tx/Change";
 }
template<> char const* ripple::LogPartition::getPartitionName ()
Definition at line 29 of file OfferCancelTransactor.h.
 {
     return "Tx/OfferCancel";
 }
template<> char const* ripple::LogPartition::getPartitionName ()
Definition at line 29 of file PaymentTransactor.h.
 {
     return "Tx/Payment";
 }
template<> char const* ripple::LogPartition::getPartitionName ()
Definition at line 29 of file WalletAddTransactor.h.
 {
     return "Tx/WalletAdd";
 }
template<> char const* ripple::LogPartition::getPartitionName ()
Definition at line 29 of file TrustSetTransactor.h.
 {
     return "Tx/TrustSet";
 }
template<> char const* ripple::LogPartition::getPartitionName ()
Definition at line 29 of file RegularKeySetTransactor.h.
 {
     return "Tx/RegularKeySet";
 }
template<> char const* ripple::LogPartition::getPartitionName ()
Definition at line 31 of file OfferCreateTransactor.h.
 {
     return "Tx/OfferCreate";
 }
template<> char const* ripple::LogPartition::getPartitionName ()
Definition at line 31 of file NetworkOPs.cpp.
 { return "FeeVote"; }
template<> char const* ripple::LogPartition::getPartitionName ()
Definition at line 30 of file LedgerMaster.cpp.
 { return "LedgerCleaner"; }
template<> char const* ripple::LogPartition::getPartitionName ()
Definition at line 31 of file OverlayImpl.cpp.
 { return "Overlay"; }
template<> char const* ripple::LogPartition::getPartitionName ()
Definition at line 34 of file OverlayImpl.cpp.
 { return "PeerFinder"; }
template<> char const* ripple::LogPartition::getPartitionName ()
Definition at line 37 of file OverlayImpl.cpp.
 { return "NameResolver"; }
template<> char const* ripple::LogPartition::getPartitionName ()
Definition at line 41 of file Application.cpp.
 { return "Application"; }
template<> char const* ripple::LogPartition::getPartitionName ()
Definition at line 43 of file Application.cpp.
 { return "SiteFiles"; }
template<> char const* ripple::LogPartition::getPartitionName ()
Definition at line 45 of file Application.cpp.
 { return "Validators"; }
template<> char const* ripple::LogPartition::getPartitionName ()
Definition at line 47 of file Application.cpp.
 { return "JobQueue"; }
template<> char const* ripple::LogPartition::getPartitionName ()
Definition at line 49 of file Application.cpp.
 { return "NetworkOPs"; }
template<> char const* ripple::LogPartition::getPartitionName ()
Definition at line 51 of file Application.cpp.
 { return "RPCServiceManager"; }
template<> char const* ripple::LogPartition::getPartitionName ()
Definition at line 53 of file Application.cpp.
 { return "RPCServer"; }
template<> char const* ripple::LogPartition::getPartitionName ()
Definition at line 55 of file Application.cpp.
 { return "LoadManager"; }
template<> char const* ripple::LogPartition::getPartitionName ()
Definition at line 57 of file Application.cpp.
 { return "ResourceManager"; }
template<> char const* ripple::LogPartition::getPartitionName ()
Definition at line 59 of file Application.cpp.
 { return "PathRequest"; }
template<> char const* ripple::LogPartition::getPartitionName ()
Definition at line 61 of file Application.cpp.
 { return "RPCManager"; }
template<> char const* ripple::LogPartition::getPartitionName ()
Definition at line 63 of file Application.cpp.
 { return "FeatureTable"; }
template<> char const* ripple::LogPartition::getPartitionName ()
Definition at line 65 of file Application.cpp.
 { return "Collector"; }
template<> char const* ripple::LogPartition::getPartitionName ()
Definition at line 68 of file Application.cpp.
 { return "TaggedCache"; }
template<class Key > static char const* ripple::LogPartition::getPartitionName () static
Retrieve the name for a log partition.
LogPartition::Severities ripple::LogPartition::getSeverities () static
Definition at line 129 of file LogPartition.cpp.
References headLog, mNextLog, and ripple::Log::severityToString().
Referenced by ripple::RPCHandler::doLogLevel().
 {
     LogPartition::Severities result;
     for (LogPartition* l = headLog; l != nullptr; l = l->mNextLog)
         result.push_back (std::make_pair (
             l->mName, Log::severityToString (l->getSeverity ())));
     return result;
 }
LogSeverity ripple::LogPartition::getSeverity () const
Return the lowest severity reported on the partition.
Definition at line 55 of file LogPartition.cpp.
References convertSeverity(), and beast::Journal::Sink::severity().
Referenced by doLog().
 {
     return convertSeverity (severity ());
 }
void ripple::LogPartition::setConsoleOutput (std::string const & list) static
Activate console output for the specified comma-separated partition list.
Definition at line 110 of file LogPartition.cpp.
References beast::Journal::Sink::console(), find(), and beast.util.Iter::first().
Referenced by ripple::ApplicationImp::setup().
 {
     std::string::const_iterator first (list.begin());
     for(;;)
     {
         std::string::const_iterator last (std::find (
             first, list.end(), ','));
         LogPartition* const p (find (std::string (first, last)));
         if (p != nullptr)
             p->console (true);
         if (last != list.end())
             first = last + 1;
         else
             break;
     }
 }
void ripple::LogPartition::setMinimumSeverity (LogSeverity severity)
Sets the lowest severity reported on the partition.
Definition at line 60 of file LogPartition.cpp.
References convertLogSeverity(), and beast::Journal::Sink::severity().
Referenced by setSeverity().
 {
     severity (convertLogSeverity (level));
 }
void ripple::LogPartition::setSeverity (LogSeverity severity) static
Set the minimum severity of all existing partitions at once.
Definition at line 91 of file LogPartition.cpp.
References headLog, and mNextLog.
Referenced by ripple::RPCHandler::doLogLevel(), ripple::LogSink::setMinSeverity(), and ripple::ApplicationImp::setup().
 {
     for (LogPartition* p = headLog; p != nullptr; p = p->mNextLog)
         p->setMinimumSeverity (level);
 }
bool ripple::LogPartition::setSeverity (std::string const & name, LogSeverity severity) static
Set the minimum severity of a partition by name.
Definition at line 97 of file LogPartition.cpp.
References find(), and setMinimumSeverity().
 {
     LogPartition* const p (find (partition));
     if (p)
     {
         p->setMinimumSeverity (level);
         return true;
     }
     return false;
 }
void ripple::LogPartition::write (beast::Journal::Severity level, std::string const & text) virtual
Write text to the sink at the specified severity. The caller is responsible for checking the minimum severity level before using this function.
Implements beast::Journal::Sink.
Definition at line 24 of file LogPartition.cpp.
References beast::Journal::Sink::console(), convertSeverity(), ripple::LogSink::get(), and mName.
Referenced by ripple::Log::~Log().
 {
     std::string output;
     LogSeverity const logSeverity (convertSeverity (level));
     LogSink::get()->format (output, text, logSeverity, mName);
     LogSink::get()->write (output, logSeverity);
     if (console ())
         LogSink::get()->write_console (output);
 }
Member Data Documentation
LogPartition * ripple::LogPartition::headLog = nullptr static private
Definition at line 98 of file LogPartition.h.
Referenced by find(), getSeverities(), LogPartition(), and setSeverity().
std::string ripple::LogPartition::mName private
Definition at line 101 of file LogPartition.h.
Referenced by getName(), and write().
LogPartition* ripple::LogPartition::mNextLog private
Definition at line 100 of file LogPartition.h.
Referenced by find(), getSeverities(), and setSeverity().
The documentation for this class was generated from the following files:
rippled/src/ripple_basics/log/LogPartition.h
rippled/src/ripple_app/ledger/InboundLedger.cpp
rippled/src/ripple_app/ledger/LedgerMaster.cpp
rippled/src/ripple_app/main/Application.cpp
rippled/src/ripple_app/misc/NetworkOPs.cpp
rippled/src/ripple_app/transactors/AccountSetTransactor.h
rippled/src/ripple_app/transactors/ChangeTransactor.h
rippled/src/ripple_app/transactors/OfferCancelTransactor.h
rippled/src/ripple_app/transactors/OfferCreateTransactor.h
rippled/src/ripple_app/transactors/PaymentTransactor.h
rippled/src/ripple_app/transactors/RegularKeySetTransactor.h
rippled/src/ripple_app/transactors/TrustSetTransactor.h
rippled/src/ripple_app/transactors/WalletAddTransactor.h
rippled/src/ripple_app/tx/TransactionAcquire.cpp
rippled/src/ripple_basics/log/LogPartition.cpp
rippled/src/ripple_overlay/impl/OverlayImpl.cpp