rippled: beast::RandomAccessFile_test Class Reference
beast::RandomAccessFile_test Class Reference
Classes
struct Record
Public Types
enum { maxPayload = 8192 }
typedef HeapBlock< Record > Records
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Member Functions
void writeRecords (RandomAccessFile &file, int numRecords, HeapBlock< Record > const &records, std::int64_t seedValue)
void readRecords (RandomAccessFile &file, int numRecords, HeapBlock< Record > const &records, std::int64_t seedValue)
void testFile (int const numRecords)
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Static Public Member Functions
static void createRecords (HeapBlock< Record > &records, int numRecords, int maxBytes, std::int64_t seedValue)
Additional Inherited Members
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 105 of file RandomAccessFile.cpp.
Member Typedef Documentation
typedef HeapBlock<Record> beast::RandomAccessFile_test::Records
Definition at line 125 of file RandomAccessFile.cpp.
Member Enumeration Documentation
anonymous enum
Enumerator
maxPayload
Definition at line 108 of file RandomAccessFile.cpp.
     {
         maxPayload = 8192
     };
Member Function Documentation
static void beast::RandomAccessFile_test::createRecords (HeapBlock< Record > & records, int numRecords, int maxBytes, std::int64_t seedValue) inline static
Definition at line 128 of file RandomAccessFile.cpp.
References beast::HeapBlock< ElementType, throwOnFailure >::malloc(), beast::Random::nextInt(), and beast::UnitTestUtilities::repeatableShuffle().
Referenced by testFile().
     {
         using namespace UnitTestUtilities;
         Random r (seedValue);
         records.malloc (numRecords);
         int offset = 0;
         for (int i = 0; i < numRecords; ++i)
         {
             int const bytes = r.nextInt (maxBytes) + 1;
             records [i].index = i;
             records [i].bytes = bytes;
             records [i].offset = offset;
             offset += bytes;
         }
         repeatableShuffle (numRecords, records, seedValue);
     }
void beast::RandomAccessFile_test::readRecords (RandomAccessFile & file, int numRecords, HeapBlock< Record > const & records, std::int64_t seedValue) inline
Definition at line 181 of file RandomAccessFile.cpp.
References beast::RandomAccessFile_test::Record::bytes, beast::unit_test::suite::expect(), beast::RandomAccessFile_test::Record::index, beast::RandomAccessFile_test::Record::offset, beast::RandomAccessFile::read(), beast::RandomAccessFile::setPosition(), and beast::Result::wasOk().
Referenced by testFile().
     {
         using namespace UnitTestUtilities;
         for (int i = 0; i < numRecords; ++i)
         {
             Record const& record (records [i]);
             int const bytes = record.bytes;
             Payload p1 (bytes);
             Payload p2 (bytes);
             p1.repeatableRandomFill (bytes, bytes, record.index + seedValue);
             file.setPosition (record.offset);
             Result result = file.read (p2.data.getData (), bytes);
             expect (result.wasOk (), "Should be ok");
             if (result.wasOk ())
             {
                 p2.bytes = bytes;
                 expect (p1 == p2, "Should be equal");
             }
         }
     }
void beast::RandomAccessFile_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 266 of file RandomAccessFile.cpp.
References testFile().
     {
         testFile (10000);
     }
void beast::RandomAccessFile_test::testFile (int const numRecords) inline
Definition at line 215 of file RandomAccessFile.cpp.
References createRecords(), beast::File::createTempFile(), beast::unit_test::suite::expect(), maxPayload, beast::Result::ok(), beast::RandomAccessFile::open(), beast.util.CleanCPPFiles::path, beast::RandomAccessFile::readOnly, readRecords(), beast::RandomAccessFile::readWrite, beast::UnitTestUtilities::repeatableShuffle(), beast::unit_test::suite::testcase(), beast::Result::wasOk(), and writeRecords().
Referenced by run().
     {
         using namespace UnitTestUtilities;
         int const seedValue = 50;
         std::stringstream ss;
         ss << numRecords << " records";
         testcase (ss.str());
         // Calculate the path
         File const path (File::createTempFile ("RandomAccessFile"));
         // Create a predictable set of records
         HeapBlock <Record> records (numRecords);
         createRecords (records, numRecords, maxPayload, seedValue);
         Result result (Result::ok ());
         {
             // Create the file
             RandomAccessFile file;
             result = file.open (path, RandomAccessFile::readWrite);
             expect (result.wasOk (), "Should be ok");
             if (result.wasOk ())
             {
                 writeRecords (file, numRecords, records, seedValue);
                 readRecords (file, numRecords, records, seedValue);
                 repeatableShuffle (numRecords, records, seedValue);
                 readRecords (file, numRecords, records, seedValue);
             }
         }
         if (result.wasOk ())
         {
             // Re-open the file in read only mode
             RandomAccessFile file;
             result = file.open (path, RandomAccessFile::readOnly);
             expect (result.wasOk (), "Should be ok");
             if (result.wasOk ())
             {
                 readRecords (file, numRecords, records, seedValue);
             }
         }
     }
void beast::RandomAccessFile_test::writeRecords (RandomAccessFile & file, int numRecords, HeapBlock< Record > const & records, std::int64_t seedValue) inline
Definition at line 157 of file RandomAccessFile.cpp.
References beast::unit_test::suite::expect(), beast::RandomAccessFile::setPosition(), beast::Result::wasOk(), and beast::RandomAccessFile::write().
Referenced by testFile().
     {
         using namespace UnitTestUtilities;
         for (int i = 0; i < numRecords; ++i)
         {
             Payload p (records [i].bytes);
             p.repeatableRandomFill (records [i].bytes,
                                     records [i].bytes,
                                     records [i].index + seedValue);
             file.setPosition (records [i].offset);
             Result result = file.write (p.data.getData (), p.bytes);
             expect (result.wasOk (), "Should be ok");
         }
     }
The documentation for this class was generated from the following file:
rippled/src/beast/modules/beast_core/files/RandomAccessFile.cpp