rippled: ripple::STVariableLength Class Reference
ripple::STVariableLength Class Reference
#include <SerializedTypes.h>
Public Member Functions
STVariableLength (Blob const &v)
STVariableLength (SField::ref n, Blob const &v)
STVariableLength (SField::ref n)
STVariableLength (SerializerIterator &, SField::ref name=sfGeneric)
STVariableLength ()
virtual SerializedTypeID getSType () const
virtual std::string getText () const
void add (Serializer &s) const
Blob const & peekValue () const
Blob & peekValue ()
Blob getValue () const
void setValue (Blob const &v)
operator Blob () const
virtual bool isEquivalent (const SerializedType &t) const
virtual bool isDefault () const
Public Member Functions inherited from ripple::SerializedType
SerializedType ()
SerializedType (SField::ref n)
virtual ~SerializedType ()
void setFName (SField::ref n)
SField::ref getFName () const
std::string getName () const
std::unique_ptr< SerializedType > clone () const
virtual std::string getFullText () const
virtual Json::Value getJson (int) const
void addFieldID (Serializer &s) const
SerializedType & operator= (const SerializedType &t)
bool operator== (const SerializedType &t) const
bool operator!= (const SerializedType &t) const
template<class D >
D & downcast ()
template<class D >
D const & downcast () const
Static Public Member Functions
static std::unique_ptr
< SerializedType > deserialize (SerializerIterator &sit, SField::ref name)
Static Public Member Functions inherited from ripple::SerializedType
static std::unique_ptr
< SerializedType > deserialize (SField::ref name)
Private Member Functions
virtual STVariableLength * duplicate () const
Static Private Member Functions
static STVariableLength * construct (SerializerIterator &, SField::ref)
Private Attributes
Blob value
Additional Inherited Members
Protected Attributes inherited from ripple::SerializedType
SField::ptr fName
Detailed Description
Definition at line 1062 of file SerializedTypes.h.
Constructor & Destructor Documentation
ripple::STVariableLength::STVariableLength (Blob const & v) inline
Definition at line 1065 of file SerializedTypes.h.
                                      : value (v)
     {
         ;
     }
ripple::STVariableLength::STVariableLength (SField::ref n, Blob const & v) inline
Definition at line 1069 of file SerializedTypes.h.
                                                   : SerializedType (n), value (v)
     {
         ;
     }
ripple::STVariableLength::STVariableLength (SField::ref n) inline
Definition at line 1073 of file SerializedTypes.h.
                                    : SerializedType (n)
     {
         ;
     }
ripple::STVariableLength::STVariableLength (SerializerIterator & st, SField::ref name = sfGeneric)
Definition at line 287 of file SerializedTypes.cpp.
References ripple::SerializerIterator::getVL(), and value.
                                                                           : SerializedType (name)
 {
     value = st.getVL ();
 }
ripple::STVariableLength::STVariableLength () inline
Definition at line 1078 of file SerializedTypes.h.
Referenced by construct(), and duplicate().
     {
         ;
     }
Member Function Documentation
void ripple::STVariableLength::add (Serializer & s) const inline virtual
Reimplemented from ripple::SerializedType.
Definition at line 1092 of file SerializedTypes.h.
References ripple::Serializer::addVL(), and value.
     {
         s.addVL (value);
     }
STVariableLength * ripple::STVariableLength::construct (SerializerIterator & u, SField::ref name) static private
Definition at line 297 of file SerializedTypes.cpp.
References ripple::SerializerIterator::getVL(), and STVariableLength().
Referenced by deserialize().
 {
     return new STVariableLength (name, u.getVL ());
 }
static std::unique_ptr<SerializedType> ripple::STVariableLength::deserialize (SerializerIterator & sit, SField::ref name) inline static
Definition at line 1082 of file SerializedTypes.h.
References construct().
Referenced by ripple::STObject::makeDeserializedObject().
     {
         return std::unique_ptr<SerializedType> (construct (sit, name));
     }
virtual STVariableLength* ripple::STVariableLength::duplicate () const inline private virtual
Reimplemented from ripple::SerializedType.
Reimplemented in ripple::STAccount.
Definition at line 1127 of file SerializedTypes.h.
References STVariableLength().
     {
         return new STVariableLength (*this);
     }
virtual SerializedTypeID ripple::STVariableLength::getSType () const inline virtual
Reimplemented from ripple::SerializedType.
Reimplemented in ripple::STAccount.
Definition at line 1087 of file SerializedTypes.h.
     {
         return STI_VL;
     }
std::string ripple::STVariableLength::getText () const virtual
Reimplemented from ripple::SerializedType.
Reimplemented in ripple::STAccount.
Definition at line 292 of file SerializedTypes.cpp.
References ripple::strHex(), and value.
Referenced by ripple::STAccount::getText().
 {
     return strHex (value);
 }
Blob ripple::STVariableLength::getValue () const inline
Definition at line 1105 of file SerializedTypes.h.
References value.
Referenced by ripple::STObject::getFieldVL().
     {
         return value;
     }
virtual bool ripple::STVariableLength::isDefault () const inline virtual
Reimplemented from ripple::SerializedType.
Definition at line 1119 of file SerializedTypes.h.
References value.
     {
         return value.empty ();
     }
bool ripple::STVariableLength::isEquivalent (const SerializedType & t) const virtual
Reimplemented from ripple::SerializedType.
Definition at line 302 of file SerializedTypes.cpp.
References value.
 {
     const STVariableLength* v = dynamic_cast<const STVariableLength*> (&t);
     return v && (value == v->value);
 }
ripple::STVariableLength::operator Blob () const inline
Definition at line 1114 of file SerializedTypes.h.
References value.
     {
         return value;
     }
Blob const& ripple::STVariableLength::peekValue () const inline
Definition at line 1097 of file SerializedTypes.h.
References value.
Referenced by ripple::STAccount::getValueH160(), ripple::STAccount::isValueH160(), ripple::STAccount::setValueH160(), and ripple::STAccount::STAccount().
     {
         return value;
     }
Blob& ripple::STVariableLength::peekValue () inline
Definition at line 1101 of file SerializedTypes.h.
References value.
     {
         return value;
     }
void ripple::STVariableLength::setValue (Blob const & v) inline
Definition at line 1109 of file SerializedTypes.h.
References value.
Referenced by ripple::STObject::setFieldVL().
     {
         value = v;
     }
Member Data Documentation
Blob ripple::STVariableLength::value private
Definition at line 1125 of file SerializedTypes.h.
Referenced by add(), getText(), getValue(), isDefault(), isEquivalent(), operator Blob(), peekValue(), setValue(), and STVariableLength().
The documentation for this class was generated from the following files:
rippled/src/ripple_data/protocol/SerializedTypes.h
rippled/src/ripple_data/protocol/SerializedTypes.cpp