rippled: ripple::RippleIdentifier_test Class Reference
ripple::RippleIdentifier_test Class Reference
Public Member Functions
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 969 of file RippleAddress.cpp.
Member Function Documentation
void ripple::RippleIdentifier_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 972 of file RippleAddress.cpp.
References ripple::RippleAddress::createAccountPrivate(), ripple::RippleAddress::createAccountPublic(), ripple::RippleAddress::createGeneratorPublic(), ripple::RippleAddress::createNodePrivate(), ripple::RippleAddress::createNodePublic(), beast::unit_test::suite::expect(), ripple::RippleAddress::humanAccountID(), ripple::RippleAddress::humanAccountPrivate(), ripple::RippleAddress::humanAccountPublic(), ripple::RippleAddress::humanGenerator(), ripple::RippleAddress::humanNodePrivate(), ripple::RippleAddress::humanNodePublic(), ripple::RippleAddress::humanSeed(), ripple::RippleAddress::setSeedGeneric(), and beast::unit_test::suite::testcase().
     {
         testcase ("Seed");
         RippleAddress seed;
         expect (seed.setSeedGeneric ("masterpassphrase"));
         expect (seed.humanSeed () == "snoPBrXtMeMyMHUVTgbuqAfg1SUTb", seed.humanSeed ());
         testcase ("RipplePublicKey");
         RippleAddress deprecatedPublicKey (RippleAddress::createNodePublic (seed));
         expect (deprecatedPublicKey.humanNodePublic () ==
             "n94a1u4jAz288pZLtw6yFWVbi89YamiC6JBXPVUj5zmExe5fTVg9",
                 deprecatedPublicKey.humanNodePublic ());
         RipplePublicKey publicKey (deprecatedPublicKey);
         expect (publicKey.to_string() == deprecatedPublicKey.humanNodePublic(),
             publicKey.to_string());
         testcase ("RipplePrivateKey");
         RippleAddress deprecatedPrivateKey (RippleAddress::createNodePrivate (seed));
         expect (deprecatedPrivateKey.humanNodePrivate () ==
             "pnen77YEeUd4fFKG7iycBWcwKpTaeFRkW2WFostaATy1DSupwXe",
                 deprecatedPrivateKey.humanNodePrivate ());
         RipplePrivateKey privateKey (deprecatedPrivateKey);
         expect (privateKey.to_string() == deprecatedPrivateKey.humanNodePrivate(),
             privateKey.to_string());
         testcase ("Generator");
         RippleAddress generator (RippleAddress::createGeneratorPublic (seed));
         expect (generator.humanGenerator () ==
             "fhuJKrhSDzV2SkjLn9qbwm5AaRmrxDPfFsHDCP6yfDZWcxDFz4mt",
                 generator.humanGenerator ());
         testcase ("RippleAccountID");
         RippleAddress deprecatedAccountPublicKey (
             RippleAddress::createAccountPublic (generator, 0));
         expect (deprecatedAccountPublicKey.humanAccountID () ==
             "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh",
                 deprecatedAccountPublicKey.humanAccountID ());
         RippleAccountID accountID (deprecatedAccountPublicKey);
         expect (accountID.to_string() ==
             deprecatedAccountPublicKey.humanAccountID(),
                 accountID.to_string());
         testcase ("RippleAccountPublicKey");
         expect (deprecatedAccountPublicKey.humanAccountPublic () ==
             "aBQG8RQAzjs1eTKFEAQXr2gS4utcDiEC9wmi7pfUPTi27VCahwgw",
                 deprecatedAccountPublicKey.humanAccountPublic ());
         testcase ("RippleAccountPrivateKey");
         RippleAddress deprecatedAccountPrivateKey (
             RippleAddress::createAccountPrivate (generator, seed, 0));
         expect (deprecatedAccountPrivateKey.humanAccountPrivate () ==
             "p9JfM6HHi64m6mvB6v5k7G2b1cXzGmYiCNJf6GHPKvFTWdeRVjh",
                 deprecatedAccountPrivateKey.humanAccountPrivate ());
         RippleAccountPrivateKey accountPrivateKey (deprecatedAccountPrivateKey);
         expect (accountPrivateKey.to_string() ==
             deprecatedAccountPrivateKey.humanAccountPrivate(),
                 privateKey.to_string());
     }
The documentation for this class was generated from the following file:
rippled/src/ripple_data/protocol/RippleAddress.cpp