rippled: beast::Result Class Reference
beast::Result Class Reference
#include <Result.h>
Public Member Functions
bool wasOk () const noexcept
bool failed () const noexcept
operator bool () const noexcept
bool operator! () const noexcept
const String & getErrorMessage () const noexcept
Result (const Result &)
Result & operator= (const Result &)
bool operator== (const Result &other) const noexcept
bool operator!= (const Result &other) const noexcept
Static Public Member Functions
static Result ok () noexcept
static Result fail (const String &errorMessage) noexcept
Private Member Functions
Result () noexcept
Result (const String &) noexcept
operator int () const
operator void * () const
Private Attributes
String errorMessage
Detailed Description
Represents the 'success' or 'failure' of an operation, and holds an associated error message to describe the error when there's a failure.
E.g.
Result myOperation()
{
    if (doSomeKindOfFoobar())
        return Result::ok();
    else
        return Result::fail ("foobar didn't work!");
}
const Result result (myOperation());
if (result.wasOk())
{
    ...it's all good...
}
else
{
    warnUserAboutFailure ("The foobar operation failed! Error message was: "
                            + result.getErrorMessage());
}
Definition at line 56 of file Result.h.
Constructor & Destructor Documentation
Result::Result (const Result & other)
Definition at line 34 of file Result.cpp.
     : errorMessage (other.errorMessage)
 {
 }
Result::Result () private noexcept
Definition at line 27 of file Result.cpp.
Referenced by ok().
 {}
Result::Result (const String & message) explicit private noexcept
Definition at line 29 of file Result.cpp.
     : errorMessage (message)
 {
 }
Member Function Documentation
Result Result::fail (const String & errorMessage) static noexcept
Creates a 'failure' result. If you pass a blank error message in here, a default "Unknown Error" message will be used instead.
Definition at line 68 of file Result.cpp.
Referenced by ldb_test.LDBTestCase::assertRunFAILFull(), beast::File::create(), beast::File::createDirectory(), beast::WindowsFileHelpers::getResultForLastError(), and beast::RandomAccessFile::nativeOpen().
 {
     return Result (errorMessage.isEmpty() ? "Unknown error" : errorMessage);
 }
bool Result::failed () const noexcept
Returns true if this result indicates a failure. You can use getErrorMessage() to retrieve the error message associated with the failure.
Definition at line 80 of file Result.cpp.
References errorMessage, and beast::String::isNotEmpty().
Referenced by beast::FileInputStream::failedToOpen(), and beast::FileOutputStream::failedToOpen().
 { return errorMessage.isNotEmpty(); }
const String & Result::getErrorMessage () const noexcept
Returns the error message that was set when this result was created. For a successful result, this will be an empty string;
Definition at line 73 of file Result.cpp.
References errorMessage.
 {
     return errorMessage;
 }
static Result beast::Result::ok () inline static noexcept
Creates and returns a 'successful' result.
Definition at line 61 of file Result.h.
References Result().
Referenced by beast::File::create(), beast::File::createDirectory(), beast::RandomAccessFile::nativeFlush(), beast::RandomAccessFile::nativeOpen(), beast::RandomAccessFile::nativeRead(), beast::RandomAccessFile::nativeSetPosition(), beast::RandomAccessFile::nativeWrite(), beast::RandomAccessFile::setPosition(), beast::RandomAccessFile_test::testFile(), and beast::RandomAccessFile::write().
 { return Result(); }
Result::operator bool () const noexcept
Returns true if this result indicates a success. This is equivalent to calling wasOk().
Definition at line 79 of file Result.cpp.
 { return errorMessage.isEmpty(); }
beast::Result::operator int () const private
beast::Result::operator void * () const private
bool Result::operator! () const noexcept
Returns true if this result indicates a failure. This is equivalent to calling failed().
Definition at line 81 of file Result.cpp.
References errorMessage, and beast::String::isNotEmpty().
 { return errorMessage.isNotEmpty(); }
bool Result::operator!= (const Result & other) const noexcept
Definition at line 63 of file Result.cpp.
 {
     return errorMessage != other.errorMessage;
 }
Result & Result::operator= (const Result & other)
Definition at line 39 of file Result.cpp.
References errorMessage.
 {
     errorMessage = other.errorMessage;
     return *this;
 }
bool Result::operator== (const Result & other) const noexcept
Definition at line 58 of file Result.cpp.
 {
     return errorMessage == other.errorMessage;
 }
bool Result::wasOk () const noexcept
Returns true if this result indicates a success.
Definition at line 78 of file Result.cpp.
References errorMessage, and beast::String::isEmpty().
Referenced by beast::FileInputStream::openedOk(), beast::FileOutputStream::openedOk(), beast::RandomAccessFile_test::readRecords(), beast::RandomAccessFile_test::testFile(), beast::RandomAccessFile::truncate(), beast::RandomAccessFile::write(), and beast::RandomAccessFile_test::writeRecords().
 { return errorMessage.isEmpty(); }
Member Data Documentation
String beast::Result::errorMessage private
Definition at line 107 of file Result.h.
Referenced by failed(), getErrorMessage(), operator!(), operator=(), and wasOk().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_core/misc/Result.h
rippled/src/beast/modules/beast_core/misc/Result.cpp