rippled: beast::WindowsFileHelpers Namespace Reference
beast::WindowsFileHelpers Namespace Reference
Functions
DWORD getAtts (const String &path)
std::int64_t fileTimeToTime (const FILETIME *const ft)
FILETIME * timeToFileTime (const std::int64_t time, FILETIME *const ft) noexcept
String getDriveFromPath (String path)
std::int64_t getDiskSpaceInfo (const String &path, const bool total)
unsigned int getWindowsDriveType (const String &path)
File getSpecialFolderPath (int type)
File getModuleFileName (HINSTANCE moduleHandle)
Result getResultForLastError ()
Function Documentation
std::int64_t beast::WindowsFileHelpers::fileTimeToTime (const FILETIME *const ft)
Definition at line 39 of file win32_Files.cpp.
References static_bassert.
Referenced by beast::DirectoryIterator::NativeIterator::Pimpl::next().
     {
         static_bassert (sizeof (ULARGE_INTEGER) == sizeof (FILETIME)); // tell me if this fails!
         return (std::int64_t) ((reinterpret_cast<const ULARGE_INTEGER*> (ft)->QuadPart - 116444736000000000LL) / 10000);
     }
DWORD beast::WindowsFileHelpers::getAtts (const String & path)
Definition at line 34 of file win32_Files.cpp.
References beast::String::toWideCharPointer().
     {
         return GetFileAttributes (path.toWideCharPointer());
     }
std::int64_t beast::WindowsFileHelpers::getDiskSpaceInfo (const String & path, const bool total)
Definition at line 71 of file win32_Files.cpp.
References getDriveFromPath().
     {
         ULARGE_INTEGER spc, tot, totFree;
         if (GetDiskFreeSpaceEx (getDriveFromPath (path).toWideCharPointer(), &spc, &tot, &totFree))
             return total ? (std::int64_t) tot.QuadPart
                          : (std::int64_t) spc.QuadPart;
         return 0;
     }
String beast::WindowsFileHelpers::getDriveFromPath (String path)
Definition at line 55 of file win32_Files.cpp.
References beast::HeapBlock< ElementType, throwOnFailure >::calloc(), beast::String::copyToUTF16(), beast::CharPointer_UTF16::getBytesRequiredFor(), beast::String::getCharPointer(), beast::String::isNotEmpty(), and beast.util.CleanCPPFiles::path.
Referenced by getDiskSpaceInfo(), and getWindowsDriveType().
     {
         if (path.isNotEmpty() && path[1] == ':' && path[2] == 0)
             path << '\\';
         const size_t numBytes = CharPointer_UTF16::getBytesRequiredFor (path.getCharPointer()) + 4;
         HeapBlock<WCHAR> pathCopy;
         pathCopy.calloc (numBytes, 1);
         path.copyToUTF16 (pathCopy, numBytes);
         if (PathStripToRoot (pathCopy))
             path = static_cast <const WCHAR*> (pathCopy);
         return path;
     }
File beast::WindowsFileHelpers::getModuleFileName (HINSTANCE moduleHandle)
Definition at line 97 of file win32_Files.cpp.
References beast::numElementsInArray().
     {
         WCHAR dest [MAX_PATH + 256];
         dest[0] = 0;
         GetModuleFileName (moduleHandle, dest, (DWORD) numElementsInArray (dest));
         return File (String (dest));
     }
Result beast::WindowsFileHelpers::getResultForLastError ()
Definition at line 105 of file win32_Files.cpp.
References beast::Result::fail(), and beast::numElementsInArray().
     {
         TCHAR messageBuffer [256] = { 0 };
         FormatMessage (FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_IGNORE_INSERTS,
                        nullptr, GetLastError(), MAKELANGID (LANG_NEUTRAL, SUBLANG_DEFAULT),
                        messageBuffer, (DWORD) numElementsInArray (messageBuffer) - 1, nullptr);
         return Result::fail (String (messageBuffer));
     }
File beast::WindowsFileHelpers::getSpecialFolderPath (int type)
Definition at line 87 of file win32_Files.cpp.
References FALSE, beast::File::nonexistent(), and beast.util.CleanCPPFiles::path.
     {
         WCHAR path [MAX_PATH + 256];
         if (SHGetSpecialFolderPath (0, path, type, FALSE))
             return File (String (path));
         return File::nonexistent ();
     }
unsigned int beast::WindowsFileHelpers::getWindowsDriveType (const String & path)
Definition at line 82 of file win32_Files.cpp.
References getDriveFromPath().
     {
         return GetDriveType (getDriveFromPath (path).toWideCharPointer());
     }
FILETIME* beast::WindowsFileHelpers::timeToFileTime (const std::int64_t time, FILETIME *const ft) noexcept
Definition at line 46 of file win32_Files.cpp.
     {
         if (time <= 0)
             return nullptr;
         reinterpret_cast<ULARGE_INTEGER*> (ft)->QuadPart = (ULONGLONG) (time * 10000 + 116444736000000000LL);
         return ft;
     }