rippled: beast::asio::TestPeerLogicAsyncServer Class Reference
beast::asio::TestPeerLogicAsyncServer Class Reference
#include <TestPeerLogicAsyncServer.h>
Public Member Functions
TestPeerLogicAsyncServer (abstract_socket &socket)
PeerRole get_role () const noexcept
Model get_model () const noexcept
void on_connect_async (error_code const &ec)
void on_handshake (error_code const &ec)
void on_read (error_code const &ec, std::size_t bytes_transferred)
void on_write (error_code const &ec, std::size_t bytes_transferred)
void on_shutdown (error_code const &ec)
Public Member Functions inherited from beast::asio::TestPeerLogic
TestPeerLogic (abstract_socket &socket)
error_code & error () noexcept
error_code const & error () const noexcept
error_code const & error (error_code const &ec) noexcept
abstract_socket & socket () noexcept
virtual void on_connect ()
virtual void finished ()
Private Attributes
boost::asio::streambuf m_buf
Additional Inherited Members
Public Types inherited from beast::asio::TestPeerLogic
typedef boost::system::error_code error_code
Static Public Member Functions inherited from beast::asio::TestPeerLogic
static void pure_virtual ()
Detailed Description
Definition at line 26 of file TestPeerLogicAsyncServer.h.
Constructor & Destructor Documentation
beast::asio::TestPeerLogicAsyncServer::TestPeerLogicAsyncServer (abstract_socket & socket) explicit
Definition at line 23 of file TestPeerLogicAsyncServer.cpp.
     : TestPeerLogic (socket)
 {
 }
Member Function Documentation
TestPeerBasics::Model beast::asio::TestPeerLogicAsyncServer::get_model () const virtual noexcept
Implements beast::asio::TestPeerLogic.
Definition at line 33 of file TestPeerLogicAsyncServer.cpp.
References beast::asio::TestPeerBasics::Model::async.
 {
     return Model::async;
 }
PeerRole beast::asio::TestPeerLogicAsyncServer::get_role () const virtual noexcept
Implements beast::asio::TestPeerLogic.
Definition at line 28 of file TestPeerLogicAsyncServer.cpp.
References beast::asio::PeerRole::server.
 {
     return PeerRole::server;
 }
void beast::asio::TestPeerLogicAsyncServer::on_connect_async (error_code const & ec) virtual
Reimplemented from beast::asio::TestPeerLogic.
Definition at line 38 of file TestPeerLogicAsyncServer.cpp.
References beast::asio::TestPeerBasics::aborted(), beast::asio::abstract_socket::async_handshake(), beast::asio::TestPeerLogic::error(), beast::asio::TestPeerBasics::failure(), beast::asio::TestPeerLogic::finished(), on_handshake(), and beast::asio::TestPeerLogic::socket().
 {
     if (aborted (ec) || failure (error (ec)))
         return finished ();
     if (socket ().needs_handshake ())
     {
         socket ().async_handshake (abstract_socket::server,
             boost::bind (&TestPeerLogicAsyncServer::on_handshake, this,
             boost::asio::placeholders::error));
     }
     else
     {
         on_handshake (ec);
     }
 }
void beast::asio::TestPeerLogicAsyncServer::on_handshake (error_code const & ec)
Definition at line 55 of file TestPeerLogicAsyncServer.cpp.
References beast::asio::TestPeerBasics::aborted(), beast::asio::TestPeerLogic::error(), beast::asio::TestPeerBasics::failure(), beast::asio::TestPeerLogic::finished(), m_buf, on_read(), and beast::asio::TestPeerLogic::socket().
Referenced by on_connect_async().
 {
     if (aborted (ec) || failure (error (ec)))
         return finished ();
     boost::asio::async_read_until (socket (), m_buf, std::string ("hello"),
         boost::bind (&TestPeerLogicAsyncServer::on_read, this,
         boost::asio::placeholders::error, boost::asio::placeholders::bytes_transferred));
 }
void beast::asio::TestPeerLogicAsyncServer::on_read (error_code const & ec, std::size_t bytes_transferred)
Definition at line 65 of file TestPeerLogicAsyncServer.cpp.
References beast::asio::TestPeerBasics::aborted(), beast::asio::TestPeerLogic::error(), beast::asio::TestPeerBasics::failure(), beast::asio::TestPeerLogic::finished(), on_write(), beast::asio::TestPeerLogic::socket(), and beast::asio::TestPeerBasics::unexpected().
Referenced by on_handshake().
 {
     if (aborted (ec) || failure (error (ec)))
         return finished ();
     if (unexpected (bytes_transferred == 5, error ()))
         return finished ();
     boost::asio::async_write (socket (), boost::asio::buffer ("goodbye", 7),
         boost::bind (&TestPeerLogicAsyncServer::on_write, this,
         boost::asio::placeholders::error, boost::asio::placeholders::bytes_transferred));
 }
void beast::asio::TestPeerLogicAsyncServer::on_shutdown (error_code const & ec)
Definition at line 100 of file TestPeerLogicAsyncServer.cpp.
References beast::asio::TestPeerBasics::aborted(), beast::asio::TestPeerLogic::error(), beast::asio::TestPeerLogic::finished(), beast::asio::abstract_socket::shutdown(), beast::asio::TestPeerLogic::socket(), and beast::asio::TestPeerBasics::success().
Referenced by on_write().
 {
     if (! aborted (ec))
     {
         if (success (error (ec), true))
         {
             if (socket ().needs_handshake ())
             {
                 socket ().shutdown (abstract_socket::shutdown_receive, error ());
             }
             if (success (socket ().close (error ())))
             {
                 // doing nothing here is intended,
                 // as the calls to success() may set error()
             }
         }
     }
     finished ();
 }
void beast::asio::TestPeerLogicAsyncServer::on_write (error_code const & ec, std::size_t bytes_transferred)
Definition at line 78 of file TestPeerLogicAsyncServer.cpp.
References beast::asio::TestPeerBasics::aborted(), beast::asio::abstract_socket::async_shutdown(), beast::asio::TestPeerLogic::error(), beast::asio::TestPeerBasics::failure(), beast::asio::TestPeerLogic::finished(), on_shutdown(), beast::asio::TestPeerLogic::socket(), and beast::asio::TestPeerBasics::unexpected().
Referenced by on_read().
 {
     if (aborted (ec) || failure (error (ec)))
         return finished ();
     if (unexpected (bytes_transferred == 7, error ()))
         return finished ();
     if (socket ().needs_handshake ())
     {
         socket ().async_shutdown (boost::bind (&TestPeerLogicAsyncServer::on_shutdown, this,
             boost::asio::placeholders::error));
     }
     else
     {
         // on_shutdown will call finished ()
         // we need another instance of ec so we can call on_shutdown()
         error_code ec;
         on_shutdown (socket ().shutdown (abstract_socket::shutdown_receive, ec));
     }
 }
Member Data Documentation
boost::asio::streambuf beast::asio::TestPeerLogicAsyncServer::m_buf private
Definition at line 38 of file TestPeerLogicAsyncServer.h.
Referenced by on_handshake().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_asio/tests/TestPeerLogicAsyncServer.h
rippled/src/beast/modules/beast_asio/tests/TestPeerLogicAsyncServer.cpp