rippled: ripple::HashRouter Class Reference
ripple::HashRouter Class Reference
Classes
class Entry
Public Member Functions
HashRouter (int holdTime)
bool addSuppression (uint256 const &index)
bool addSuppressionPeer (uint256 const &index, PeerShortID peer)
bool addSuppressionPeer (uint256 const &index, PeerShortID peer, int &flags)
bool addSuppressionFlags (uint256 const &index, int flag)
bool setFlag (uint256 const &index, int flag)
int getFlags (uint256 const &index)
bool swapSet (uint256 const &index, std::set< PeerShortID > &peers, int flag)
Public Member Functions inherited from ripple::IHashRouter
virtual ~IHashRouter ()
Private Types
typedef RippleMutex LockType
typedef std::lock_guard< LockType > ScopedLockType
Private Member Functions
Entry getEntry (uint256 const &)
Entry & findCreateEntry (uint256 const &, bool &created)
Private Attributes
LockType mLock
ripple::unordered_map< uint256,
Entry > mSuppressionMap
std::map< int, std::list
< uint256 > > mSuppressionTimes
int mHoldTime
Additional Inherited Members
Public Types inherited from ripple::IHashRouter
typedef std::uint32_t PeerShortID
Static Public Member Functions inherited from ripple::IHashRouter
static int getDefaultHoldTime ()
static IHashRouter * New (int holdTime)
Detailed Description
Definition at line 23 of file HashRouter.cpp.
Member Typedef Documentation
typedef RippleMutex ripple::HashRouter::LockType private
Definition at line 105 of file HashRouter.cpp.
typedef std::lock_guard<LockType> ripple::HashRouter::ScopedLockType private
Definition at line 106 of file HashRouter.cpp.
Constructor & Destructor Documentation
ripple::HashRouter::HashRouter (int holdTime) inline explicit
Definition at line 85 of file HashRouter.cpp.
         : mHoldTime (holdTime)
     {
     }
Member Function Documentation
bool ripple::HashRouter::addSuppression (uint256 const & index) virtual
Implements ripple::IHashRouter.
Definition at line 149 of file HashRouter.cpp.
References findCreateEntry(), and mLock.
 {
     ScopedLockType sl (mLock);
     bool created;
     findCreateEntry (index, created);
     return created;
 }
bool ripple::HashRouter::addSuppressionFlags (uint256 const & index, int flag) virtual
Implements ripple::IHashRouter.
Definition at line 194 of file HashRouter.cpp.
References findCreateEntry(), mLock, and ripple::HashRouter::Entry::setFlag().
 {
     ScopedLockType sl (mLock);
     bool created;
     findCreateEntry (index, created).setFlag (flag);
     return created;
 }
bool ripple::HashRouter::addSuppressionPeer (uint256 const & index, PeerShortID peer) virtual
Implements ripple::IHashRouter.
Definition at line 166 of file HashRouter.cpp.
References ripple::HashRouter::Entry::addPeer(), findCreateEntry(), and mLock.
 {
     ScopedLockType sl (mLock);
     bool created;
     findCreateEntry (index, created).addPeer (peer);
     return created;
 }
bool ripple::HashRouter::addSuppressionPeer (uint256 const & index, PeerShortID peer, int & flags) virtual
Implements ripple::IHashRouter.
Definition at line 175 of file HashRouter.cpp.
References ripple::HashRouter::Entry::addPeer(), findCreateEntry(), ripple::HashRouter::Entry::getFlags(), and mLock.
 {
     ScopedLockType sl (mLock);
     bool created;
     Entry& s = findCreateEntry (index, created);
     s.addPeer (peer);
     flags = s.getFlags ();
     return created;
 }
HashRouter::Entry & ripple::HashRouter::findCreateEntry (uint256 const & index, bool & created) private
Definition at line 120 of file HashRouter.cpp.
References ripple::UptimeTimer::getElapsedSeconds(), ripple::UptimeTimer::getInstance(), mHoldTime, mSuppressionMap, and mSuppressionTimes.
Referenced by addSuppression(), addSuppressionFlags(), addSuppressionPeer(), getEntry(), getFlags(), setFlag(), and swapSet().
 {
     ripple::unordered_map<uint256, Entry>::iterator fit = mSuppressionMap.find (index);
     if (fit != mSuppressionMap.end ())
     {
         created = false;
         return fit->second;
     }
     created = true;
     int now = UptimeTimer::getInstance ().getElapsedSeconds ();
     int expireTime = now - mHoldTime;
     // See if any supressions need to be expired
     std::map< int, std::list<uint256> >::iterator it = mSuppressionTimes.begin ();
     if ((it != mSuppressionTimes.end ()) && (it->first <= expireTime))
     {
         BOOST_FOREACH (uint256 const & lit, it->second)
         mSuppressionMap.erase (lit);
         mSuppressionTimes.erase (it);
     }
     mSuppressionTimes[now].push_back (index);
     return mSuppressionMap.emplace (index, Entry ()).first->second;
 }
HashRouter::Entry ripple::HashRouter::getEntry (uint256 const & index) private
Definition at line 158 of file HashRouter.cpp.
References findCreateEntry(), and mLock.
 {
     ScopedLockType sl (mLock);
     bool created;
     return findCreateEntry (index, created);
 }
int ripple::HashRouter::getFlags (uint256 const & index) virtual
Implements ripple::IHashRouter.
Definition at line 186 of file HashRouter.cpp.
References findCreateEntry(), ripple::HashRouter::Entry::getFlags(), and mLock.
 {
     ScopedLockType sl (mLock);
     bool created;
     return findCreateEntry (index, created).getFlags ();
 }
bool ripple::HashRouter::setFlag (uint256 const & index, int mask) virtual
Set the flags on a hash.
Returns
true if the flags were changed.
Implements ripple::IHashRouter.
Definition at line 203 of file HashRouter.cpp.
References findCreateEntry(), ripple::HashRouter::Entry::getFlags(), mLock, and ripple::HashRouter::Entry::setFlag().
 {
     // VFALCO NOTE Comments like this belong in the HEADER file,
     //             and more importantly in a Javadoc comment so
     //             they appear in the generated documentation.
     //
     // return: true = changed, false = unchanged
     assert (flag != 0);
     ScopedLockType sl (mLock);
     bool created;
     Entry& s = findCreateEntry (index, created);
     if ((s.getFlags () & flag) == flag)
         return false;
     s.setFlag (flag);
     return true;
 }
bool ripple::HashRouter::swapSet (uint256 const & index, std::set< PeerShortID > & peers, int flag) virtual
Implements ripple::IHashRouter.
Definition at line 224 of file HashRouter.cpp.
References findCreateEntry(), ripple::HashRouter::Entry::getFlags(), mLock, ripple::HashRouter::Entry::setFlag(), and ripple::HashRouter::Entry::swapSet().
 {
     ScopedLockType sl (mLock);
     bool created;
     Entry& s = findCreateEntry (index, created);
     if ((s.getFlags () & flag) == flag)
         return false;
     s.swapSet (peers);
     s.setFlag (flag);
     return true;
 }
Member Data Documentation
int ripple::HashRouter::mHoldTime private
Definition at line 115 of file HashRouter.cpp.
Referenced by findCreateEntry().
LockType ripple::HashRouter::mLock private
Definition at line 107 of file HashRouter.cpp.
Referenced by addSuppression(), addSuppressionFlags(), addSuppressionPeer(), getEntry(), getFlags(), setFlag(), and swapSet().
ripple::unordered_map<uint256, Entry> ripple::HashRouter::mSuppressionMap private
Definition at line 110 of file HashRouter.cpp.
Referenced by findCreateEntry().
std::map< int, std::list<uint256> > ripple::HashRouter::mSuppressionTimes private
Definition at line 113 of file HashRouter.cpp.
Referenced by findCreateEntry().
The documentation for this class was generated from the following file:
rippled/src/ripple_app/misc/HashRouter.cpp