rippled: beast::DeadlineTimer Class Reference
beast::DeadlineTimer Class Reference
#include <DeadlineTimer.h>
Classes
class Listener
class Manager
Public Member Functions
DeadlineTimer (Listener *listener)
~DeadlineTimer ()
void cancel ()
void setRecurringExpiration (double secondsUntilDeadline)
bool operator== (DeadlineTimer const &other) const
bool operator!= (DeadlineTimer const &other) const
void setExpiration (double secondsUntilDeadline)
template<class Rep , class Period >
void setExpiration (std::chrono::duration< Rep, Period > const &amount)
Private Attributes
Listener *const m_listener
SharedPtr< SharedSingleton
< Manager > > m_manager
bool m_isActive
RelativeTime m_notificationTime
double m_secondsRecurring
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
Provides periodic or one time notifications at a specified time interval.
Definition at line 28 of file DeadlineTimer.h.
Constructor & Destructor Documentation
beast::DeadlineTimer::DeadlineTimer (Listener * listener) explicit
Create a deadline timer with the specified listener attached.
Definition at line 211 of file DeadlineTimer.cpp.
     : m_listener (listener)
     , m_manager (SharedSingleton <Manager>::getInstance ())
     , m_isActive (false)
 {
 }
beast::DeadlineTimer::~DeadlineTimer ()
Definition at line 218 of file DeadlineTimer.cpp.
References m_manager.
 {
     m_manager->deactivate (*this);
 }
Member Function Documentation
void beast::DeadlineTimer::cancel ()
Cancel all notifications. It is okay to call this on an inactive timer.
Note
It is guaranteed that no notifications will occur after this function returns.
Definition at line 223 of file DeadlineTimer.cpp.
References m_manager.
Referenced by ripple::PeerFinder::ManagerImp::onStop(), ripple::NetworkOPsImp::onStop(), and ripple::ApplicationImp::onStop().
 {
     m_manager->deactivate (*this);
 }
bool beast::DeadlineTimer::operator!= (DeadlineTimer const & other) const inline
Inequality comparison.
Definition at line 99 of file DeadlineTimer.h.
     {
         return this != &other;
     }
bool beast::DeadlineTimer::operator== (DeadlineTimer const & other) const inline
Equality comparison. Timers are equal if they have the same address.
Definition at line 93 of file DeadlineTimer.h.
     {
         return this == &other;
     }
void beast::DeadlineTimer::setExpiration (double secondsUntilDeadline)
Set the timer to go off once in the future. If the timer is already active, this will reset it.
Note
If the timer is already active, the old one might go off before this function returns.
Parameters
secondsUntilDeadline The number of seconds until the timer will send a notification. This must be greater than zero.
Definition at line 228 of file DeadlineTimer.cpp.
References bassert, beast::RelativeTime::fromStartup(), and m_manager.
Referenced by ripple::Validators::ManagerImp::checkSources(), ripple::ApplicationImp::doSweep(), ripple::PeerFinder::ManagerImp::init(), ripple::PeerFinder::ManagerImp::onDeadlineTimer(), ripple::ApplicationImp::onStart(), ripple::NetworkOPsImp::setClusterTimer(), setExpiration(), and ripple::NetworkOPsImp::setHeartbeatTimer().
 {
     bassert (secondsUntilDeadline != 0);
     RelativeTime const when (
         RelativeTime::fromStartup() + secondsUntilDeadline);
     m_manager->activate (*this, 0, when);
 }
template<class Rep , class Period > void beast::DeadlineTimer::setExpiration (std::chrono::duration< Rep, Period > const & amount) inline
Definition at line 73 of file DeadlineTimer.h.
References setExpiration().
     {
         setExpiration (std::chrono::duration_cast <
             std::chrono::duration <double>> (amount).count ());
     }
void beast::DeadlineTimer::setRecurringExpiration (double secondsUntilDeadline)
Set the timer to go off repeatedly with the specified frequency. If the timer is already active, this will reset it.
Note
If the timer is already active, the old one might go off before this function returns.
Parameters
secondsUntilDeadline The number of seconds until the timer will send a notification. This must be greater than zero.
Definition at line 238 of file DeadlineTimer.cpp.
References bassert, beast::RelativeTime::fromStartup(), and m_manager.
 {
     bassert (secondsUntilDeadline != 0);
     RelativeTime const when (
         RelativeTime::fromStartup() + secondsUntilDeadline);
     m_manager->activate (*this, secondsUntilDeadline, when);
 }
Member Data Documentation
bool beast::DeadlineTimer::m_isActive private
Definition at line 109 of file DeadlineTimer.h.
Referenced by beast::DeadlineTimer::Manager::activate(), beast::DeadlineTimer::Manager::deactivate(), and beast::DeadlineTimer::Manager::run().
Listener* const beast::DeadlineTimer::m_listener private
Definition at line 105 of file DeadlineTimer.h.
Referenced by beast::DeadlineTimer::Manager::run().
SharedPtr<SharedSingleton <Manager> > beast::DeadlineTimer::m_manager private
Definition at line 108 of file DeadlineTimer.h.
Referenced by cancel(), setExpiration(), setRecurringExpiration(), and ~DeadlineTimer().
RelativeTime beast::DeadlineTimer::m_notificationTime private
Definition at line 110 of file DeadlineTimer.h.
Referenced by beast::DeadlineTimer::Manager::activate(), beast::DeadlineTimer::Manager::insertSorted(), and beast::DeadlineTimer::Manager::run().
double beast::DeadlineTimer::m_secondsRecurring private
Definition at line 111 of file DeadlineTimer.h.
Referenced by beast::DeadlineTimer::Manager::activate(), and beast::DeadlineTimer::Manager::run().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_core/thread/DeadlineTimer.h
rippled/src/beast/modules/beast_core/thread/DeadlineTimer.cpp