rippled: rocksdb::FakeWritableFile Class Reference
rocksdb::FakeWritableFile Class Reference
Public Member Functions
~FakeWritableFile ()
const std::string & contents () const
virtual Status Close ()
virtual Status Flush ()
virtual Status Sync ()
virtual Status Append (const Slice &data)
Public Member Functions inherited from rocksdb::WritableFile
WritableFile ()
virtual ~WritableFile ()
virtual Status Fsync ()
virtual uint64_t GetFileSize ()
void SetPreallocationBlockSize (size_t size)
virtual void GetPreallocationStatus (size_t *block_size, size_t *last_allocated_block)
virtual size_t GetUniqueId (char *id, size_t max_size) const
virtual Status InvalidateCache (size_t offset, size_t length)
Private Attributes
std::string contents_
Additional Inherited Members
Protected Member Functions inherited from rocksdb::WritableFile
void PrepareWrite (size_t offset, size_t len)
virtual Status Allocate (off_t offset, off_t len)
virtual Status RangeSync (off_t offset, off_t nbytes)
Detailed Description
Definition at line 31 of file table_properties_collector_test.cc.
Constructor & Destructor Documentation
rocksdb::FakeWritableFile::~FakeWritableFile () inline
Definition at line 33 of file table_properties_collector_test.cc.
 { }
Member Function Documentation
virtual Status rocksdb::FakeWritableFile::Append (const Slice & data) inline virtual
Implements rocksdb::WritableFile.
Definition at line 41 of file table_properties_collector_test.cc.
References contents_, rocksdb::Slice::data(), rocksdb::Status::OK(), and rocksdb::Slice::size().
{
     contents_.append(data.data(), data.size());
     return Status::OK();
   }
virtual Status rocksdb::FakeWritableFile::Close () inline virtual
Implements rocksdb::WritableFile.
Definition at line 37 of file table_properties_collector_test.cc.
References rocksdb::Status::OK().
 { return Status::OK(); }
const std::string& rocksdb::FakeWritableFile::contents () const inline
Definition at line 35 of file table_properties_collector_test.cc.
References contents_.
Referenced by rocksdb::TEST().
 { return contents_; }
virtual Status rocksdb::FakeWritableFile::Flush () inline virtual
Implements rocksdb::WritableFile.
Definition at line 38 of file table_properties_collector_test.cc.
References rocksdb::Status::OK().
 { return Status::OK(); }
virtual Status rocksdb::FakeWritableFile::Sync () inline virtual
Implements rocksdb::WritableFile.
Definition at line 39 of file table_properties_collector_test.cc.
References rocksdb::Status::OK().
 { return Status::OK(); }
Member Data Documentation
std::string rocksdb::FakeWritableFile::contents_ private
Definition at line 47 of file table_properties_collector_test.cc.
Referenced by Append(), and contents().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/db/table_properties_collector_test.cc