rippled: ripple::JobTypeInfo Class Reference
ripple::JobTypeInfo Class Reference
#include <JobTypeInfo.h>
Public Member Functions
JobTypeInfo ()=delete
JobTypeInfo (JobType type, std::string name, int limit, bool skip, bool special, std::uint64_t avgLatency, std::uint64_t peakLatency)
JobType type () const
std::string name () const
int limit () const
bool skip () const
bool special () const
std::uint64_t getAverageLatency () const
std::uint64_t getPeakLatency () const
Private Attributes
JobType const m_type
std::string const m_name
int const m_limit
bool const m_skip
bool const m_special
std::uint64_t const m_avgLatency
std::uint64_t const m_peakLatency
Detailed Description
Holds all the 'static' information about a job, which does not change
Definition at line 27 of file JobTypeInfo.h.
Constructor & Destructor Documentation
ripple::JobTypeInfo::JobTypeInfo () delete
ripple::JobTypeInfo::JobTypeInfo (JobType type, std::string name, int limit, bool skip, bool special, std::uint64_t avgLatency, std::uint64_t peakLatency) inline
Definition at line 50 of file JobTypeInfo.h.
         : m_type (type)
         , m_name (name)
         , m_limit (limit)
         , m_skip (skip)
         , m_special (special)
         , m_avgLatency (avgLatency)
         , m_peakLatency (peakLatency)
     {
     }
Member Function Documentation
std::uint64_t ripple::JobTypeInfo::getAverageLatency () const inline
Definition at line 88 of file JobTypeInfo.h.
References m_avgLatency.
Referenced by ripple::JobTypeData::JobTypeData().
     {
         return m_avgLatency;
     }
std::uint64_t ripple::JobTypeInfo::getPeakLatency () const inline
Definition at line 93 of file JobTypeInfo.h.
References m_peakLatency.
Referenced by ripple::JobTypeData::JobTypeData().
     {
         return m_peakLatency;
     }
int ripple::JobTypeInfo::limit () const inline
Definition at line 73 of file JobTypeInfo.h.
References m_limit.
Referenced by ripple::JobQueueImp::getJobLimit().
     {
         return m_limit;
     }
std::string ripple::JobTypeInfo::name () const inline
Definition at line 68 of file JobTypeInfo.h.
References m_name.
Referenced by ripple::JobTypeData::JobTypeData(), and ripple::JobTypeData::name().
     {
         return m_name;
     }
bool ripple::JobTypeInfo::skip () const inline
Definition at line 78 of file JobTypeInfo.h.
References m_skip.
Referenced by ripple::JobQueueImp::processTask(), and ripple::JobQueueImp::skipOnStop().
     {
         return m_skip;
     }
bool ripple::JobTypeInfo::special () const inline
Definition at line 83 of file JobTypeInfo.h.
References m_special.
Referenced by ripple::JobTypeData::JobTypeData().
     {
         return m_special;
     }
JobType ripple::JobTypeInfo::type () const inline
Definition at line 63 of file JobTypeInfo.h.
References m_type.
Referenced by ripple::JobQueueImp::getJobLimit(), ripple::JobQueueImp::JobQueueImp(), ripple::JobQueueImp::skipOnStop(), and ripple::JobTypeData::type().
     {
         return m_type;
     }
Member Data Documentation
std::uint64_t const ripple::JobTypeInfo::m_avgLatency private
Average and peak latencies for this job type. 0 is none specified
Definition at line 43 of file JobTypeInfo.h.
Referenced by getAverageLatency().
int const ripple::JobTypeInfo::m_limit private
The limit on the number of running jobs for this job type.
Definition at line 34 of file JobTypeInfo.h.
Referenced by limit().
std::string const ripple::JobTypeInfo::m_name private
Definition at line 31 of file JobTypeInfo.h.
Referenced by name().
std::uint64_t const ripple::JobTypeInfo::m_peakLatency private
Definition at line 44 of file JobTypeInfo.h.
Referenced by getPeakLatency().
bool const ripple::JobTypeInfo::m_skip private
Can be skipped
Definition at line 37 of file JobTypeInfo.h.
Referenced by skip().
bool const ripple::JobTypeInfo::m_special private
Special jobs are not dispatched via the job queue
Definition at line 40 of file JobTypeInfo.h.
Referenced by special().
JobType const ripple::JobTypeInfo::m_type private
Definition at line 30 of file JobTypeInfo.h.
Referenced by type().
The documentation for this class was generated from the following file:
rippled/src/ripple_core/functional/JobTypeInfo.h