rippled: rocksdb::SliceTransform Class Reference
rocksdb::SliceTransform Class Reference abstract
#include <slice_transform.h>
Public Member Functions
virtual ~SliceTransform ()
virtual const char * Name () const =0
virtual Slice Transform (const Slice &src) const =0
virtual bool InDomain (const Slice &src) const =0
virtual bool InRange (const Slice &dst) const =0
Detailed Description
Definition at line 24 of file slice_transform.h.
Constructor & Destructor Documentation
virtual rocksdb::SliceTransform::~SliceTransform () inline virtual
Definition at line 26 of file slice_transform.h.
 {};
Member Function Documentation
virtual bool rocksdb::SliceTransform::InDomain (const Slice & src) const pure virtual
Referenced by rocksdb::FilterBlockBuilder::AddKey(), and rocksdb::FilterBlockBuilder::SamePrefix().
virtual bool rocksdb::SliceTransform::InRange (const Slice & dst) const pure virtual
Referenced by rocksdb::PrefixFilterIterator::PrefixFilterIterator().
virtual const char* rocksdb::SliceTransform::Name () const pure virtual
Referenced by rocksdb::Options::Dump().
virtual Slice rocksdb::SliceTransform::Transform (const Slice & src) const pure virtual
Referenced by rocksdb::FilterBlockBuilder::AddKey(), rocksdb::Benchmark::PrefixScanRandom(), rocksdb::FilterBlockBuilder::SamePrefix(), rocksdb::PrefixFilterIterator::Seek(), and rocksdb::PrefixFilterIterator::Valid().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/include/rocksdb/slice_transform.h