rippled: beast::StaticObject< Object, Tag > Class Template Reference
beast::StaticObject< Object, Tag > Class Template Reference
#include <StaticObject.h>
Classes
class StaticData
Static Public Member Functions
static Object & get ()
Private Types
enum { uninitialized = 0, initializing, initialized }
Detailed Description
template<class Object, typename Tag = void>
class beast::StaticObject< Object, Tag >
Wrapper to produce an object with static storage duration.
The object is constructed in a thread-safe fashion when the get function is first called. Note that the destructor for Object is never called. To invoke the destructor, use the AtExitHook facility (with caution).
The Tag parameter allows multiple instances of the same Object type, by using different tags.
Object must meet these requirements: DefaultConstructible
See Also
AtExitHook
Definition at line 55 of file StaticObject.h.
Member Enumeration Documentation
template<class Object , typename Tag = void> anonymous enum private
Enumerator
uninitialized
initializing
initialized
Definition at line 83 of file StaticObject.h.
     {
         uninitialized = 0,          // must be zero to function properly
         initializing,
         initialized
     };
Member Function Documentation
template<class Object , typename Tag = void> static Object& beast::StaticObject< Object, Tag >::get () inline static
Definition at line 58 of file StaticObject.h.
References beast::Atomic< Type >::compareAndSetBool(), beast::Atomic< Type >::get(), beast::StaticObject< Object, Tag >::StaticData::get(), beast::StaticObject< Object, Tag >::initialized, beast::StaticObject< Object, Tag >::initializing, beast::StaticObject< Object, Tag >::StaticData::object, beast::StaticObject< Object, Tag >::StaticData::state, beast::detail::staticObjectWait(), and beast::StaticObject< Object, Tag >::uninitialized.
     {
         StaticData& staticData (StaticData::get());
         if (staticData.state.get() != initialized)
         {
             if (staticData.state.compareAndSetBool (initializing, uninitialized))
             {
                 // Initialize the object.
                 new (&staticData.object) Object;
                 staticData.state = initialized;
             }
             else
             {
                 for (std::size_t n = 0; staticData.state.get() != initialized; ++n)
                 {
                     detail::staticObjectWait (n);
                 }
             }
         }
         return staticData.object;
     }
The documentation for this class was generated from the following file:
rippled/src/beast/beast/utility/StaticObject.h