rippled: beast::Random_test Class Reference
beast::Random_test Class Reference
Public Member Functions
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 126 of file Random.cpp.
Member Function Documentation
void beast::Random_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 129 of file Random.cpp.
References beast::unit_test::suite::expect(), beast::Random::nextDouble(), beast::Random::nextFloat(), beast::Random::nextInt(), and beast::Random::setSeedRandomly().
     {
         for (int j = 10; --j >= 0;)
         {
             Random r;
             r.setSeedRandomly();
             for (int i = 20; --i >= 0;)
             {
                 expect (r.nextDouble() >= 0.0 && r.nextDouble() < 1.0);
                 expect (r.nextFloat() >= 0.0f && r.nextFloat() < 1.0f);
                 expect (r.nextInt (5) >= 0 && r.nextInt (5) < 5);
                 expect (r.nextInt (1) == 0);
                 int n = r.nextInt (50) + 1;
                 expect (r.nextInt (n) >= 0 && r.nextInt (n) < n);
                 n = r.nextInt (0x7ffffffe) + 1;
                 expect (r.nextInt (n) >= 0 && r.nextInt (n) < n);
             }
         }
     }
The documentation for this class was generated from the following file:
rippled/src/beast/modules/beast_core/maths/Random.cpp