rippled: rocksdb::AutoRollLogger Class Reference
rocksdb::AutoRollLogger Class Reference
#include <auto_roll_logger.h>
Public Member Functions
AutoRollLogger (Env *env, const std::string &dbname, const std::string &db_log_dir, size_t log_max_size, size_t log_file_time_to_roll)
void Logv (const char *format, va_list ap)
Status GetStatus ()
size_t GetLogFileSize () const
virtual ~AutoRollLogger ()
void SetCallNowMicrosEveryNRecords (uint64_t call_NowMicros_every_N_records)
Public Member Functions inherited from rocksdb::Logger
Logger ()
virtual ~Logger ()
virtual void Flush ()
Private Member Functions
bool LogExpired ()
Status ResetLogger ()
void RollLogFile ()
Private Attributes
std::string log_fname_
std::string dbname_
std::string db_log_dir_
std::string db_absolute_path_
Env * env_
std::shared_ptr< Logger > logger_
Status status_
const size_t kMaxLogFileSize
const size_t kLogFileTimeToRoll
uint64_t cached_now
uint64_t ctime_
uint64_t cached_now_access_count
uint64_t call_NowMicros_every_N_records_
port::Mutex mutex_
Additional Inherited Members
Public Types inherited from rocksdb::Logger
enum { DO_NOT_SUPPORT_GET_LOG_FILE_SIZE = -1 }
Detailed Description
Definition at line 17 of file auto_roll_logger.h.
Constructor & Destructor Documentation
rocksdb::AutoRollLogger::AutoRollLogger (Env * env, const std::string & dbname, const std::string & db_log_dir, size_t log_max_size, size_t log_file_time_to_roll) inline
Definition at line 19 of file auto_roll_logger.h.
References db_absolute_path_, db_log_dir_, dbname_, rocksdb::Env::GetAbsolutePath(), rocksdb::InfoLogFileName(), log_fname_, ResetLogger(), and RollLogFile().
                                               :
      dbname_(dbname),
      db_log_dir_(db_log_dir),
      env_(env),
      status_(Status::OK()),
      kMaxLogFileSize(log_max_size),
      kLogFileTimeToRoll(log_file_time_to_roll),
      cached_now(static_cast<uint64_t>(env_->NowMicros() * 1e-6)),
      ctime_(cached_now),
      cached_now_access_count(0),
      call_NowMicros_every_N_records_(100),
      mutex_() {
     env->GetAbsolutePath(dbname, &db_absolute_path_);
     log_fname_ = InfoLogFileName(dbname_, db_absolute_path_, db_log_dir_);
     RollLogFile();
     ResetLogger();
   }
virtual rocksdb::AutoRollLogger::~AutoRollLogger () inline virtual
Definition at line 51 of file auto_roll_logger.h.
{
   }
Member Function Documentation
size_t rocksdb::AutoRollLogger::GetLogFileSize () const inline virtual
Reimplemented from rocksdb::Logger.
Definition at line 47 of file auto_roll_logger.h.
References logger_.
Referenced by rocksdb::AutoRollLoggerTest::RollLogFileBySizeTest(), rocksdb::AutoRollLoggerTest::RollLogFileByTimeTest(), and rocksdb::TEST().
{
     return logger_->GetLogFileSize();
   }
Status rocksdb::AutoRollLogger::GetStatus () inline
Definition at line 43 of file auto_roll_logger.h.
References status_.
Referenced by rocksdb::CreateLoggerFromOptions(), and rocksdb::AutoRollLoggerTest::RollLogFileByTimeTest().
                      {
     return status_;
   }
bool rocksdb::AutoRollLogger::LogExpired () private
Definition at line 66 of file auto_roll_logger.cc.
References env_.
{
   if (cached_now_access_count >= call_NowMicros_every_N_records_) {
     cached_now = static_cast<uint64_t>(env_->NowMicros() * 1e-6);
     cached_now_access_count = 0;
   }
   ++cached_now_access_count;
   return cached_now >= ctime_ + kLogFileTimeToRoll;
 }
void rocksdb::AutoRollLogger::Logv (const char * format, va_list ap) virtual
Implements rocksdb::Logger.
Definition at line 41 of file auto_roll_logger.cc.
References logger, logger_, mutex_, and ripple::Resource::ok.
{
   assert(GetStatus().ok());
   std::shared_ptr<Logger> logger;
   {
     MutexLock l(&mutex_);
     if ((kLogFileTimeToRoll > 0 && LogExpired()) ||
         (kMaxLogFileSize > 0 && logger_->GetLogFileSize() >= kMaxLogFileSize)) {
       RollLogFile();
       ResetLogger();
     }
     // pin down the current logger_ instance before releasing the mutex.
     logger = logger_;
   }
   // Another thread could have put a new Logger instance into logger_ by now.
   // However, since logger is still hanging on to the previous instance
   // (reference count is not zero), we don't have to worry about it being
   // deleted while we are accessing it.
   // Note that logv itself is not mutex protected to allow maximum concurrency,
   // as thread safety should have been handled by the underlying logger.
   logger->Logv(format, ap);
 }
Status rocksdb::AutoRollLogger::ResetLogger () private
Definition at line 14 of file auto_roll_logger.cc.
References env_, logger_, and status_.
Referenced by AutoRollLogger().
{
   status_ = env_->NewLogger(log_fname_, &logger_);
   if (!status_.ok()) {
     return status_;
   }
   if (logger_->GetLogFileSize() ==
       (size_t)Logger::DO_NOT_SUPPORT_GET_LOG_FILE_SIZE) {
     status_ = Status::NotSupported(
         "The underlying logger doesn't support GetLogFileSize()");
   }
   if (status_.ok()) {
     cached_now = static_cast<uint64_t>(env_->NowMicros() * 1e-6);
     ctime_ = cached_now;
     cached_now_access_count = 0;
   }
   return status_;
 }
void rocksdb::AutoRollLogger::RollLogFile () private
Definition at line 35 of file auto_roll_logger.cc.
References dbname_, env_, and rocksdb::OldInfoLogFileName().
Referenced by AutoRollLogger().
{
   std::string old_fname = OldInfoLogFileName(
       dbname_, env_->NowMicros(), db_absolute_path_, db_log_dir_);
   env_->RenameFile(log_fname_, old_fname);
 }
void rocksdb::AutoRollLogger::SetCallNowMicrosEveryNRecords (uint64_t call_NowMicros_every_N_records) inline
Definition at line 54 of file auto_roll_logger.h.
References call_NowMicros_every_N_records_.
Referenced by rocksdb::AutoRollLoggerTest::RollLogFileByTimeTest().
{
     call_NowMicros_every_N_records_ = call_NowMicros_every_N_records;
   }
Member Data Documentation
uint64_t rocksdb::AutoRollLogger::cached_now private
Definition at line 75 of file auto_roll_logger.h.
uint64_t rocksdb::AutoRollLogger::cached_now_access_count private
Definition at line 77 of file auto_roll_logger.h.
uint64_t rocksdb::AutoRollLogger::call_NowMicros_every_N_records_ private
Definition at line 78 of file auto_roll_logger.h.
Referenced by SetCallNowMicrosEveryNRecords().
uint64_t rocksdb::AutoRollLogger::ctime_ private
Definition at line 76 of file auto_roll_logger.h.
std::string rocksdb::AutoRollLogger::db_absolute_path_ private
Definition at line 67 of file auto_roll_logger.h.
Referenced by AutoRollLogger().
std::string rocksdb::AutoRollLogger::db_log_dir_ private
Definition at line 66 of file auto_roll_logger.h.
Referenced by AutoRollLogger().
std::string rocksdb::AutoRollLogger::dbname_ private
Definition at line 65 of file auto_roll_logger.h.
Referenced by AutoRollLogger().
Env* rocksdb::AutoRollLogger::env_ private
Definition at line 68 of file auto_roll_logger.h.
const size_t rocksdb::AutoRollLogger::kLogFileTimeToRoll private
Definition at line 73 of file auto_roll_logger.h.
const size_t rocksdb::AutoRollLogger::kMaxLogFileSize private
Definition at line 72 of file auto_roll_logger.h.
std::string rocksdb::AutoRollLogger::log_fname_ private
Definition at line 64 of file auto_roll_logger.h.
Referenced by AutoRollLogger().
std::shared_ptr<Logger> rocksdb::AutoRollLogger::logger_ private
Definition at line 69 of file auto_roll_logger.h.
Referenced by GetLogFileSize().
port::Mutex rocksdb::AutoRollLogger::mutex_ private
Definition at line 79 of file auto_roll_logger.h.
Status rocksdb::AutoRollLogger::status_ private
Definition at line 71 of file auto_roll_logger.h.
Referenced by GetStatus().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/util/auto_roll_logger.h
rippled/src/ripple/rocksdb/rocksdb/util/auto_roll_logger.cc