rippled: beast::List< typename, typename > Class Template Reference
beast::List< typename, typename > Class Template Reference
#include <List.h>
Public Types
typedef detail::ListNode< T, Tag > Node
typedef T value_type
typedef value_type * pointer
typedef value_type & reference
typedef value_type const * const_pointer
typedef value_type const & const_reference
typedef std::size_t size_type
typedef std::ptrdiff_t difference_type
typedef detail::ListIterator
< Node > iterator
typedef detail::ListIterator
< Node const > const_iterator
Public Member Functions
List ()
bool empty () const noexcept
size_type size () const noexcept
reference front () noexcept
const_reference front () const noexcept
reference back () noexcept
const_reference back () const noexcept
iterator begin () noexcept
const_iterator begin () const noexcept
const_iterator cbegin () const noexcept
iterator end () noexcept
const_iterator end () const noexcept
const_iterator cend () const noexcept
void clear () noexcept
iterator insert (iterator pos, T &element) noexcept
void insert (iterator pos, List &other) noexcept
iterator erase (iterator pos) noexcept
iterator push_front (T &element) noexcept
T & pop_front () noexcept
iterator push_back (T &element) noexcept
T & pop_back () noexcept
void swap (List &other) noexcept
iterator prepend (List &list) noexcept
iterator append (List &list) noexcept
iterator iterator_to (T &element) const noexcept
const_iterator const_iterator_to (T const &element) const noexcept
Private Member Functions
reference element_from (Node *node) noexcept
const_reference element_from (Node const *node) const noexcept
Private Attributes
size_type m_size
Node m_head
Node m_tail
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
template<typename, typename>
class beast::List< typename, typename >
Intrusive doubly linked list.
This intrusive List is a container similar in operation to std::list in the Standard Template Library (STL). Like all intrusive containers, List requires you to first derive your class from List<>::Node:
struct Object : List <Object>::Node
{
    explicit Object (int value) : m_value (value)
    {
    }
    int m_value;
};
Now we define the list, and add a couple of items.
List <Object> list;
list.push_back (* (new Object (1)));
list.push_back (* (new Object (2)));
For compatibility with the standard containers, push_back() expects a reference to the object. Unlike the standard container, however, push_back() places the actual object in the list and not a copy-constructed duplicate.
Iterating over the list follows the same idiom as the STL:
for (List <Object>::iterator iter = list.begin(); iter != list.end; ++iter)
    std::cout << iter->m_value;
You can even use BOOST_FOREACH, or range based for loops:
BOOST_FOREACH (Object& object, list)  // boost only
    std::cout << object.m_value;
for (Object& object : list)           // C++11 only
    std::cout << object.m_value;
Because List is mostly STL compliant, it can be passed into STL algorithms: e.g. std::for_each() or std::find_first_of().
In general, objects placed into a List should be dynamically allocated although this cannot be enforced at compile time. Since the caller provides the storage for the object, the caller is also responsible for deleting the object. An object still exists after being removed from a List, until the caller deletes it. This means an element can be moved from one List to another with practically no overhead.
Unlike the standard containers, an object may only exist in one list at a time, unless special preparations are made. The Tag template parameter is used to distinguish between different list types for the same object, allowing the object to exist in more than one list simultaneously.
For example, consider an actor system where a global list of actors is maintained, so that they can each be periodically receive processing time. We wish to also maintain a list of the subset of actors that require a domain-dependent update. To achieve this, we declare two tags, the associated list types, and the list element thusly:
struct Actor;         // Forward declaration required
struct ProcessTag { };
struct UpdateTag { };
typedef List <Actor, ProcessTag> ProcessList;
typedef List <Actor, UpdateTag> UpdateList;
// Derive from both node types so we can be in each list at once.
//
struct Actor : ProcessList::Node, UpdateList::Node
{
    bool process ();    // returns true if we need an update
    void update ();
};
Template Parameters
T The base type of element which the list will store pointers to.
Tag An optional unique type name used to distinguish lists and nodes, when the object can exist in multiple lists simultaneously.
Definition at line 32 of file List.h.
Member Typedef Documentation
template<typename , typename > typedef detail::ListIterator<Node const> beast::List< typename, typename >::const_iterator
Definition at line 282 of file List.h.
template<typename , typename > typedef value_type const* beast::List< typename, typename >::const_pointer
Definition at line 276 of file List.h.
template<typename , typename > typedef value_type const& beast::List< typename, typename >::const_reference
Definition at line 277 of file List.h.
template<typename , typename > typedef std::ptrdiff_t beast::List< typename, typename >::difference_type
Definition at line 279 of file List.h.
template<typename , typename > typedef detail::ListIterator<Node> beast::List< typename, typename >::iterator
Definition at line 281 of file List.h.
template<typename , typename > typedef detail::ListNode<T, Tag> beast::List< typename, typename >::Node
Definition at line 271 of file List.h.
template<typename , typename > typedef value_type* beast::List< typename, typename >::pointer
Definition at line 274 of file List.h.
template<typename , typename > typedef value_type& beast::List< typename, typename >::reference
Definition at line 275 of file List.h.
template<typename , typename > typedef std::size_t beast::List< typename, typename >::size_type
Definition at line 278 of file List.h.
template<typename , typename > typedef T beast::List< typename, typename >::value_type
Definition at line 273 of file List.h.
Constructor & Destructor Documentation
template<typename , typename > beast::List< typename, typename >::List () inline
Create an empty list.
Definition at line 285 of file List.h.
     {
         m_head.m_prev = nullptr; // identifies the head
         m_tail.m_next = nullptr; // identifies the tail
         clear ();
     }
Member Function Documentation
template<typename , typename > iterator beast::List< typename, typename >::append (List< typename, typename > & list) inline noexcept
Append another list at the end of this list. The other list is cleared.
Parameters
list the other list to append.
Definition at line 513 of file List.h.
Referenced by beast::List< ripple::Resource::Entry >::swap().
     {
         return insert (end (), list);
     }
template<typename , typename > reference beast::List< typename, typename >::back () inline noexcept
Obtain a reference to the last element.
Invariant
The list may not be empty.
Returns
A reference to the last element.
Definition at line 328 of file List.h.
Referenced by beast::List< ripple::Resource::Entry >::pop_back().
     {
         return element_from (m_tail.m_prev);
     }
template<typename , typename > const_reference beast::List< typename, typename >::back () const inline noexcept
Obtain a const reference to the last element.
Invariant
The list may not be empty.
Returns
A const reference to the last element.
Definition at line 337 of file List.h.
     {
         return element_from (m_tail.m_prev);
     }
template<typename , typename > iterator beast::List< typename, typename >::begin () inline noexcept
Obtain an iterator to the beginning of the list.
Returns
An iterator pointing to the beginning of the list.
Definition at line 345 of file List.h.
Referenced by beast::DeadlineTimer::Manager::insertSorted(), beast::List< ripple::Resource::Entry >::pop_front(), beast::List< ripple::Resource::Entry >::prepend(), beast::List< ripple::Resource::Entry >::push_front(), and ripple::Resource::Logic::writeList().
     {
         return iterator (m_head.m_next);
     }
template<typename , typename > const_iterator beast::List< typename, typename >::begin () const inline noexcept
Obtain a const iterator to the beginning of the list.
Returns
A const iterator pointing to the beginning of the list.
Definition at line 353 of file List.h.
     {
         return const_iterator (m_head.m_next);
     }
template<typename , typename > const_iterator beast::List< typename, typename >::cbegin () const inline noexcept
Obtain a const iterator to the beginning of the list.
Returns
A const iterator pointing to the beginning of the list.
Definition at line 361 of file List.h.
     {
         return const_iterator (m_head.m_next);
     }
template<typename , typename > const_iterator beast::List< typename, typename >::cend () const inline noexcept
Obtain a const iterator to the end of the list
Returns
A constiterator pointing to the end of the list.
Definition at line 385 of file List.h.
     {
         return const_iterator (&m_tail);
     }
template<typename , typename > void beast::List< typename, typename >::clear () inline noexcept
Clear the list.
Note
This does not free the elements.
Definition at line 393 of file List.h.
Referenced by beast::List< ripple::Resource::Entry >::List().
     {
         m_head.m_next = &m_tail;
         m_tail.m_prev = &m_head;
         m_size = 0;
     }
template<typename , typename > const_iterator beast::List< typename, typename >::const_iterator_to (T const & element) const inline noexcept
Obtain a const iterator from an element.
Invariant
The element must exist in the list.
Parameters
element The element to obtain an iterator for.
Returns
A const iterator to the element.
Definition at line 533 of file List.h.
     {
         return const_iterator (static_cast <Node const*> (&element));
     }
template<typename , typename > reference beast::List< typename, typename >::element_from (Node * node) inline private noexcept
Definition at line 539 of file List.h.
Referenced by beast::List< ripple::Resource::Entry >::back(), and beast::List< ripple::Resource::Entry >::front().
     {
         return *(static_cast <pointer> (node));
     }
template<typename , typename > const_reference beast::List< typename, typename >::element_from (Node const * node) const inline private noexcept
Definition at line 544 of file List.h.
     {
         return *(static_cast <const_pointer> (node));
     }
template<typename , typename > bool beast::List< typename, typename >::empty () const inline noexcept
Determine if the list is empty.
Returns
true if the list is empty.
Definition at line 295 of file List.h.
Referenced by beast::DeadlineTimer::Manager::insertSorted(), beast::DeadlineTimer::Manager::run(), and beast::DeadlineTimer::Manager::~Manager().
     {
         return size () == 0;
     }
template<typename , typename > iterator beast::List< typename, typename >::end () inline noexcept
Obtain a iterator to the end of the list.
Returns
An iterator pointing to the end of the list.
Definition at line 369 of file List.h.
Referenced by beast::List< ripple::Resource::Entry >::append(), beast::DeadlineTimer::Manager::insertSorted(), beast::List< ripple::Resource::Entry >::pop_back(), beast::List< ripple::Resource::Entry >::push_back(), and ripple::Resource::Logic::writeList().
     {
         return iterator (&m_tail);
     }
template<typename , typename > const_iterator beast::List< typename, typename >::end () const inline noexcept
Obtain a const iterator to the end of the list.
Returns
A constiterator pointing to the end of the list.
Definition at line 377 of file List.h.
     {
         return const_iterator (&m_tail);
     }
template<typename , typename > iterator beast::List< typename, typename >::erase (iterator pos) inline noexcept
Remove an element.
Invariant
The element must exist in the list.
Parameters
pos An iterator pointing to the element to remove.
Returns
An iterator pointing to the next element after the one removed.
Definition at line 441 of file List.h.
Referenced by beast::DeadlineTimer::Manager::activate(), beast::DeadlineTimer::Manager::deactivate(), beast::List< ripple::Resource::Entry >::pop_back(), and beast::List< ripple::Resource::Entry >::pop_front().
     {
         Node* node = &*pos;
         ++pos;
         node->m_next->m_prev = node->m_prev;
         node->m_prev->m_next = node->m_next;
         --m_size;
         return pos;
     }
template<typename , typename > reference beast::List< typename, typename >::front () inline noexcept
Obtain a reference to the first element.
Invariant
The list may not be empty.
Returns
A reference to the first element.
Definition at line 310 of file List.h.
Referenced by beast::List< ripple::Resource::Entry >::pop_front(), and beast::DeadlineTimer::Manager::run().
     {
         return element_from (m_head.m_next);
     }
template<typename , typename > const_reference beast::List< typename, typename >::front () const inline noexcept
Obtain a const reference to the first element.
Invariant
The list may not be empty.
Returns
A const reference to the first element.
Definition at line 319 of file List.h.
     {
         return element_from (m_head.m_next);
     }
template<typename , typename > iterator beast::List< typename, typename >::insert (iterator pos, T & element) inline noexcept
Insert an element.
Invariant
The element must not already be in the list.
Parameters
pos The location to insert after.
element The element to insert.
Returns
An iterator pointing to the newly inserted element.
Definition at line 406 of file List.h.
Referenced by beast::List< ripple::Resource::Entry >::append(), beast::DeadlineTimer::Manager::insertSorted(), beast::List< ripple::Resource::Entry >::prepend(), beast::List< ripple::Resource::Entry >::push_back(), and beast::List< ripple::Resource::Entry >::push_front().
     {
         Node* node = static_cast <Node*> (&element);
         node->m_next = &*pos;
         node->m_prev = node->m_next->m_prev;
         node->m_next->m_prev = node;
         node->m_prev->m_next = node;
         ++m_size;
         return iterator (node);
     }
template<typename , typename > void beast::List< typename, typename >::insert (iterator pos, List< typename, typename > & other) inline noexcept
Insert another list into this one. The other list is cleared.
Parameters
pos The location to insert after.
other The list to insert.
Definition at line 422 of file List.h.
     {
         if (!other.empty ())
         {
             Node* before = &*pos;
             other.m_head.m_next->m_prev = before->m_prev;
             before->m_prev->m_next = other.m_head.m_next;
             other.m_tail.m_prev->m_next = before;
             before->m_prev = other.m_tail.m_prev;
             m_size += other.m_size;
             other.clear ();
         }
     }
template<typename , typename > iterator beast::List< typename, typename >::iterator_to (T & element) const inline noexcept
Obtain an iterator from an element.
Invariant
The element must exist in the list.
Parameters
element The element to obtain an iterator for.
Returns
An iterator to the element.
Definition at line 523 of file List.h.
Referenced by beast::DeadlineTimer::Manager::activate(), and beast::DeadlineTimer::Manager::deactivate().
     {
         return iterator (static_cast <Node*> (&element));
     }
template<typename , typename > T& beast::List< typename, typename >::pop_back () inline noexcept
Remove the element at the end of the list.
Invariant
The list must not be empty.
Returns
A reference to the popped element.
Definition at line 484 of file List.h.
     {
         T& element (back ());
         erase (--end ());
         return element;
     }
template<typename , typename > T& beast::List< typename, typename >::pop_front () inline noexcept
Remove the element at the beginning of the list.
Invariant
The list must not be empty.
Returns
A reference to the popped element.
Definition at line 464 of file List.h.
Referenced by beast::DeadlineTimer::Manager::run().
     {
         T& element (front ());
         erase (begin ());
         return element;
     }
template<typename , typename > iterator beast::List< typename, typename >::prepend (List< typename, typename > & list) inline noexcept
Insert another list at the beginning of this list. The other list is cleared.
Parameters
list The other list to insert.
Definition at line 504 of file List.h.
     {
         return insert (begin (), list);
     }
template<typename , typename > iterator beast::List< typename, typename >::push_back (T & element) inline noexcept
Append an element at the end of the list.
Invariant
The element must not exist in the list.
Parameters
element The element to append.
Definition at line 475 of file List.h.
Referenced by beast::DeadlineTimer::Manager::insertSorted().
     {
         return insert (end (), element);
     }
template<typename , typename > iterator beast::List< typename, typename >::push_front (T & element) inline noexcept
Insert an element at the beginning of the list.
Invariant
The element must not exist in the list.
Parameters
element The element to insert.
Definition at line 455 of file List.h.
     {
         return insert (begin (), element);
     }
template<typename , typename > size_type beast::List< typename, typename >::size () const inline noexcept
Returns the number of elements in the list.
Definition at line 301 of file List.h.
Referenced by beast::List< ripple::Resource::Entry >::empty().
     {
         return m_size;
     }
template<typename , typename > void beast::List< typename, typename >::swap (List< typename, typename > & other) inline noexcept
Swap contents with another list.
Definition at line 492 of file List.h.
     {
         List temp;
         temp.append (other);
         other.append (*this);
         append (temp);
     }
Member Data Documentation
template<typename , typename > Node beast::List< typename, typename >::m_head private
Definition at line 551 of file List.h.
Referenced by beast::List< ripple::Resource::Entry >::begin(), beast::List< ripple::Resource::Entry >::cbegin(), beast::List< ripple::Resource::Entry >::clear(), beast::List< ripple::Resource::Entry >::front(), and beast::List< ripple::Resource::Entry >::List().
template<typename , typename > size_type beast::List< typename, typename >::m_size private
Definition at line 550 of file List.h.
Referenced by beast::List< ripple::Resource::Entry >::clear(), beast::List< ripple::Resource::Entry >::erase(), beast::List< ripple::Resource::Entry >::insert(), and beast::List< ripple::Resource::Entry >::size().
template<typename , typename > Node beast::List< typename, typename >::m_tail private
Definition at line 552 of file List.h.
Referenced by beast::List< ripple::Resource::Entry >::back(), beast::List< ripple::Resource::Entry >::cend(), beast::List< ripple::Resource::Entry >::clear(), beast::List< ripple::Resource::Entry >::end(), and beast::List< ripple::Resource::Entry >::List().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/intrusive/List.h