rippled: beast::asio::FixedInputBuffer Class Reference
beast::asio::FixedInputBuffer Class Reference
#include <FixedInputBuffer.h>
Classes
struct CtorParams
Public Member Functions
FixedInputBuffer (FixedInputBuffer const &other)
FixedInputBuffer & operator= (FixedInputBuffer const &other)
std::size_t used () const noexcept
std::size_t size () const noexcept
void const * peek (std::size_t bytes)
template<typename T >
bool peek (T *t) const noexcept
bool consume (std::size_t bytes) noexcept
bool read (std::size_t bytes) noexcept
template<typename T >
bool read (T *t) noexcept
std::uint8_t operator[] (std::size_t index) const noexcept
template<typename IntegerType >
bool readNetworkInteger (IntegerType *value)
Protected Member Functions
FixedInputBuffer (CtorParams const &params)
void const * peek_impl (std::size_t bytes, void *buffer) const noexcept
void const * read_impl (std::size_t bytes, void *buffer) noexcept
Private Attributes
std::uint8_t const * m_begin
std::uint8_t const * m_iter
std::uint8_t const * m_end
Detailed Description
Represents a small, fixed size buffer. This provides a convenient interface for doing a bytewise verification/reject test on a handshake protocol.
Definition at line 34 of file FixedInputBuffer.h.
Constructor & Destructor Documentation
beast::asio::FixedInputBuffer::FixedInputBuffer (CtorParams const & params) inline protected
Definition at line 49 of file FixedInputBuffer.h.
         : m_begin (params.begin)
         , m_iter (m_begin)
         , m_end (m_begin + params.bytes)
     {
     }
beast::asio::FixedInputBuffer::FixedInputBuffer (FixedInputBuffer const & other) inline
Definition at line 57 of file FixedInputBuffer.h.
         : m_begin (other.m_begin)
         , m_iter (other.m_iter)
         , m_end (other.m_end)
     {
     }
Member Function Documentation
bool beast::asio::FixedInputBuffer::consume (std::size_t bytes) inline noexcept
Definition at line 95 of file FixedInputBuffer.h.
References read_impl().
Referenced by beast::asio::InputParser::Get< Digit >::func(), and beast::asio::InputParser::match_buffer().
     {
         return read_impl (bytes, nullptr) != nullptr;
     }
FixedInputBuffer& beast::asio::FixedInputBuffer::operator= (FixedInputBuffer const & other) inline
Definition at line 64 of file FixedInputBuffer.h.
References m_begin, m_end, and m_iter.
     {
         m_begin = other.m_begin;
         m_iter = other.m_iter;
         m_end = other.m_end;
         return *this;
     }
std::uint8_t beast::asio::FixedInputBuffer::operator[] (std::size_t index) const inline noexcept
Definition at line 111 of file FixedInputBuffer.h.
References bassert, m_iter, and size().
     {
         bassert (index >= 0 && index < size ());
         return m_iter [index];
     }
void const* beast::asio::FixedInputBuffer::peek (std::size_t bytes) inline
Definition at line 84 of file FixedInputBuffer.h.
References peek_impl().
Referenced by beast::asio::HandshakeDetectLogicSSL2::analyze(), beast::asio::InputParser::Get< Digit >::func(), and beast::asio::InputParser::match_buffer().
     {
         return peek_impl (bytes, nullptr);
     }
template<typename T > bool beast::asio::FixedInputBuffer::peek (T * t) const inline noexcept
Definition at line 90 of file FixedInputBuffer.h.
References peek_impl(), and T.
     {
         return peek_impl (sizeof (T), t) != nullptr;
     }
void const* beast::asio::FixedInputBuffer::peek_impl (std::size_t bytes, void * buffer) const inline protected noexcept
Definition at line 132 of file FixedInputBuffer.h.
References m_iter, and size().
Referenced by peek().
     {
         if (size () >= bytes)
         {
             if (buffer != nullptr)
                 memcpy (buffer, m_iter, bytes);
             return m_iter;
         }
         return nullptr;
     }
bool beast::asio::FixedInputBuffer::read (std::size_t bytes) inline noexcept
Definition at line 100 of file FixedInputBuffer.h.
References read_impl().
Referenced by beast::asio::HandshakeDetectLogicSSL3::analyze(), beast::asio::HandshakeDetectLogicSSL2::analyze(), and readNetworkInteger().
     {
         return read_impl (bytes, nullptr) != nullptr;
     }
template<typename T > bool beast::asio::FixedInputBuffer::read (T * t) inline noexcept
Definition at line 106 of file FixedInputBuffer.h.
References read_impl(), and T.
     {
         return read_impl (sizeof (T), t) != nullptr;
     }
void const* beast::asio::FixedInputBuffer::read_impl (std::size_t bytes, void * buffer) inline protected noexcept
Definition at line 143 of file FixedInputBuffer.h.
References m_iter, and size().
Referenced by consume(), and read().
     {
         if (size () >= bytes)
         {
             if (buffer != nullptr)
                 memcpy (buffer, m_iter, bytes);
             void const* data = m_iter;
             m_iter += bytes;
             return data;
         }
         return nullptr;
     }
template<typename IntegerType > bool beast::asio::FixedInputBuffer::readNetworkInteger (IntegerType * value) inline
Definition at line 119 of file FixedInputBuffer.h.
References beast::fromNetworkByteOrder(), and read().
Referenced by beast::asio::HandshakeDetectLogicSSL2::analyze().
     {
         // Must be an integral type!
         // not available in all versions of std:: unfortunately
         //static_bassert (std::is_integral <IntegerType>::value);
         IntegerType networkValue;
         if (! read (&networkValue))
             return false;
         *value = fromNetworkByteOrder (networkValue);
         return true;
     }
std::size_t beast::asio::FixedInputBuffer::size () const inline noexcept
Definition at line 79 of file FixedInputBuffer.h.
References m_end, and m_iter.
Referenced by beast::asio::InputParser::match_buffer(), operator[](), peek_impl(), and read_impl().
     {
         return m_end - m_iter;
     }
std::size_t beast::asio::FixedInputBuffer::used () const inline noexcept
Definition at line 73 of file FixedInputBuffer.h.
References m_begin, and m_iter.
Referenced by beast::asio::HandshakeDetectLogicPROXY::analyze().
     {
         return m_iter - m_begin;
     }
Member Data Documentation
std::uint8_t const* beast::asio::FixedInputBuffer::m_begin private
Definition at line 157 of file FixedInputBuffer.h.
Referenced by operator=(), and used().
std::uint8_t const* beast::asio::FixedInputBuffer::m_end private
Definition at line 159 of file FixedInputBuffer.h.
Referenced by operator=(), and size().
std::uint8_t const* beast::asio::FixedInputBuffer::m_iter private
Definition at line 158 of file FixedInputBuffer.h.
Referenced by operator=(), operator[](), peek_impl(), read_impl(), size(), and used().
The documentation for this class was generated from the following file:
rippled/src/beast/modules/beast_asio/basics/FixedInputBuffer.h