rippled: rocksdb::TestHashFilter Class Reference
rocksdb::TestHashFilter Class Reference
Public Member Functions
virtual const char * Name () const
virtual void CreateFilter (const Slice *keys, int n, std::string *dst) const
virtual bool KeyMayMatch (const Slice &key, const Slice &filter) const
Public Member Functions inherited from rocksdb::FilterPolicy
virtual ~FilterPolicy ()
Detailed Description
Definition at line 22 of file filter_block_test.cc.
Member Function Documentation
virtual void rocksdb::TestHashFilter::CreateFilter (const Slice * keys, int n, std::string * dst) const inline virtual
Implements rocksdb::FilterPolicy.
Definition at line 28 of file filter_block_test.cc.
References rocksdb::Hash(), and rocksdb::PutFixed32().
{
     for (int i = 0; i < n; i++) {
       uint32_t h = Hash(keys[i].data(), keys[i].size(), 1);
       PutFixed32(dst, h);
     }
   }
virtual bool rocksdb::TestHashFilter::KeyMayMatch (const Slice & key, const Slice & filter) const inline virtual
Implements rocksdb::FilterPolicy.
Definition at line 35 of file filter_block_test.cc.
References rocksdb::Slice::data(), rocksdb::DecodeFixed32(), rocksdb::Hash(), and rocksdb::Slice::size().
{
     uint32_t h = Hash(key.data(), key.size(), 1);
     for (unsigned int i = 0; i + 4 <= filter.size(); i += 4) {
       if (h == DecodeFixed32(filter.data() + i)) {
         return true;
       }
     }
     return false;
   }
virtual const char* rocksdb::TestHashFilter::Name () const inline virtual
Implements rocksdb::FilterPolicy.
Definition at line 24 of file filter_block_test.cc.
{
     return "TestHashFilter";
   }
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/table/filter_block_test.cc