rippled: ripple::RadixMap Namespace Reference
ripple::RadixMap Namespace Reference
Typedefs
typedef SHAMap Table
typedef SHAMapItem Item
Functions
boost::shared_ptr< Item > make_random_item (beast::Random &r)
void add_random_items (std::size_t n, Table &t, beast::Random &r)
Typedef Documentation
typedef SHAMapItem ripple::RadixMap::Item
Definition at line 26 of file RadixMapTest.h.
typedef SHAMap ripple::RadixMap::Table
Definition at line 25 of file RadixMapTest.h.
Function Documentation
void ripple::RadixMap::add_random_items (std::size_t n, Table & t, beast::Random & r)
Adds a set of random items to the Table.
Parameters
n The number of items to add.
t The table to add the items to.
r A pseudo random number generator.
Definition at line 36 of file RadixMapTest.cpp.
References ripple::SHAMap::addItem(), and make_random_item().
 {
     while (n--)
     {
         boost::shared_ptr <SHAMapItem> item (
             make_random_item (r));
         auto const result (t.addItem (*item, false, false));
         assert (result);
     }
 }
boost::shared_ptr< Item > ripple::RadixMap::make_random_item (beast::Random & r)
Returns a pseudo random Table item.
Definition at line 25 of file RadixMapTest.cpp.
References ripple::Serializer::add32(), ripple::Serializer::getRIPEMD160(), beast::Random::nextInt(), ripple::Serializer::peekData(), and ripple::uint160::to256().
Referenced by add_random_items().
 {
     Serializer s;
     for (int d = 0; d < 3; ++d)
         s.add32 (r.nextInt ());
     return boost::make_shared <Item> (
         s.getRIPEMD160().to256(), s.peekData ());
 }