rippled: Counters Class Reference
Counters Class Reference
Public Member Functions
Counters (std::shared_ptr< DB > db, uint64_t defaultCount=0)
virtual ~Counters ()
bool set (const string &key, uint64_t value)
bool remove (const string &key)
bool get (const string &key, uint64_t *value)
virtual bool add (const string &key, uint64_t value)
void assert_set (const string &key, uint64_t value)
void assert_remove (const string &key)
uint64_t assert_get (const string &key)
void assert_add (const string &key, uint64_t value)
Protected Attributes
std::shared_ptr< DB > db_
WriteOptions put_option_
ReadOptions get_option_
WriteOptions delete_option_
uint64_t default_
Detailed Description
Definition at line 52 of file merge_test.cc.
Constructor & Destructor Documentation
Counters::Counters (std::shared_ptr< DB > db, uint64_t defaultCount = 0) inline explicit
Definition at line 64 of file merge_test.cc.
References db_.
       : db_(db),
         put_option_(),
         get_option_(),
         delete_option_(),
         default_(defaultCount) {
     assert(db_);
   }
virtual Counters::~Counters () inline virtual
Definition at line 73 of file merge_test.cc.
 {}
Member Function Documentation
virtual bool Counters::add (const string & key, uint64_t value) inline virtual
Reimplemented in MergeBasedCounters.
Definition at line 130 of file merge_test.cc.
References base.
{
     uint64_t base = default_;
     return get(key, &base) && set(key, base + value);
   }
void Counters::assert_add (const string & key, uint64_t value) inline
Definition at line 151 of file merge_test.cc.
Referenced by testCounters().
{
     assert(add(key, value));
   }
uint64_t Counters::assert_get (const string & key) inline
Definition at line 145 of file merge_test.cc.
References value.
Referenced by testCounters().
{
     uint64_t value = default_;
     assert(get(key, &value));
     return value;
   }
void Counters::assert_remove (const string & key) inline
Definition at line 141 of file merge_test.cc.
Referenced by testCounters().
{
     assert(remove(key));
   }
void Counters::assert_set (const string & key, uint64_t value) inline
Definition at line 137 of file merge_test.cc.
Referenced by testCounters().
{
     assert(set(key, value));
   }
bool Counters::get (const string & key, uint64_t * value) inline
Definition at line 106 of file merge_test.cc.
References db_, rocksdb::DecodeFixed64(), rocksdb::DBImpl::Get(), and value.
{
     string str;
     auto s = db_->Get(get_option_, key, &str);
     if (s.IsNotFound()) {
       // return default value if not found;
       *value = default_;
       return true;
     } else if (s.ok()) {
       // deserialization
       if (str.size() != sizeof(uint64_t)) {
         cerr << "value corruption\n";
         return false;
       }
       *value = DecodeFixed64(&str[0]);
       return true;
     } else {
       cerr << s.ToString() << std::endl;
       return false;
     }
   }
bool Counters::remove (const string & key) inline
Definition at line 94 of file merge_test.cc.
References db_, rocksdb::DBImpl::Delete(), and rocksdb::Status::ToString().
{
     auto s = db_->Delete(delete_option_, key);
     if (s.ok()) {
       return true;
     } else {
       cerr << s.ToString() << std::endl;
       return false;
     }
   }
bool Counters::set (const string & key, uint64_t value) inline
Definition at line 80 of file merge_test.cc.
References db_, rocksdb::DBImpl::Put(), and rocksdb::Status::ToString().
{
     // just treat the internal rep of int64 as the string
     Slice slice((char *)&value, sizeof(value));
     auto s = db_->Put(put_option_, key, slice);
     if (s.ok()) {
       return true;
     } else {
       cerr << s.ToString() << endl;
       return false;
     }
   }
Member Data Documentation
std::shared_ptr<DB> Counters::db_ protected
Definition at line 55 of file merge_test.cc.
uint64_t Counters::default_ protected
Definition at line 61 of file merge_test.cc.
WriteOptions Counters::delete_option_ protected
Definition at line 59 of file merge_test.cc.
ReadOptions Counters::get_option_ protected
Definition at line 58 of file merge_test.cc.
WriteOptions Counters::put_option_ protected
Definition at line 57 of file merge_test.cc.
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/db/merge_test.cc