rippled: beast::CriticalSection Class Reference
beast::CriticalSection Class Reference
#include <CriticalSection.h>
Public Types
typedef GenericScopedLock
< CriticalSection > ScopedLockType
typedef GenericScopedUnlock
< CriticalSection > ScopedUnlockType
typedef GenericScopedTryLock
< CriticalSection > ScopedTryLockType
Public Member Functions
CriticalSection () noexcept
~CriticalSection () noexcept
void enter () const noexcept
bool tryEnter () const noexcept
void exit () const noexcept
void lock () const noexcept
void unlock () const noexcept
bool try_lock () const noexcept
Private Attributes
pthread_mutex_t mutex
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
A re-entrant mutex.
A CriticalSection acts as a re-entrant mutex object. The best way to lock and unlock one of these is by using RAII in the form of a local ScopedLock object - have a look through the codebase for many examples of how to do this.
See Also
ScopedLock, ScopedTryLock, ScopedUnlock, SpinLock, Thread
Definition at line 41 of file CriticalSection.h.
Member Typedef Documentation
typedef GenericScopedLock<CriticalSection> beast::CriticalSection::ScopedLockType
Provides the type of scoped lock to use with a CriticalSection.
Definition at line 91 of file CriticalSection.h.
typedef GenericScopedTryLock<CriticalSection> beast::CriticalSection::ScopedTryLockType
Provides the type of scoped try-locker to use with a CriticalSection.
Definition at line 97 of file CriticalSection.h.
typedef GenericScopedUnlock<CriticalSection> beast::CriticalSection::ScopedUnlockType
Provides the type of scoped unlocker to use with a CriticalSection.
Definition at line 94 of file CriticalSection.h.
Constructor & Destructor Documentation
beast::CriticalSection::CriticalSection () noexcept
Creates a CriticalSection object.
Definition at line 27 of file posix_SharedCode.h.
References mutex.
 {
     pthread_mutexattr_t atts;
     pthread_mutexattr_init (&atts);
     pthread_mutexattr_settype (&atts, PTHREAD_MUTEX_RECURSIVE);
    #if ! BEAST_ANDROID
     pthread_mutexattr_setprotocol (&atts, PTHREAD_PRIO_INHERIT);
    #endif
     pthread_mutex_init (&mutex, &atts);
     pthread_mutexattr_destroy (&atts);
 }
beast::CriticalSection::~CriticalSection () noexcept
Destructor. If the critical section is deleted whilst locked, any subsequent behaviour is unpredictable.
Definition at line 39 of file posix_SharedCode.h.
References mutex.
 { pthread_mutex_destroy (&mutex); }
Member Function Documentation
void beast::CriticalSection::enter () const noexcept
Acquires the lock.
If the lock is already held by the caller thread, the method returns immediately. If the lock is currently held by another thread, this will wait until it becomes free.
It's strongly recommended that you never call this method directly - instead use the ScopedLock class to manage the locking using an RAII pattern instead.
See Also
exit, tryEnter, ScopedLock
Definition at line 40 of file posix_SharedCode.h.
References mutex.
Referenced by lock().
 { pthread_mutex_lock (&mutex); }
void beast::CriticalSection::exit () const noexcept
Releases the lock.
If the caller thread hasn't got the lock, this can have unpredictable results.
If the enter() method has been called multiple times by the thread, each call must be matched by a call to exit() before other threads will be allowed to take over the lock.
See Also
enter, ScopedLock
Definition at line 42 of file posix_SharedCode.h.
References mutex.
Referenced by unlock().
 { pthread_mutex_unlock (&mutex); }
void beast::CriticalSection::lock () const inline noexcept
Definition at line 106 of file CriticalSection.h.
References enter().
 { enter (); }
bool beast::CriticalSection::try_lock () const inline noexcept
Definition at line 110 of file CriticalSection.h.
References tryEnter().
 { return tryEnter (); }
bool beast::CriticalSection::tryEnter () const noexcept
Attempts to lock this critical section without blocking.
This method behaves identically to CriticalSection::enter, except that the caller thread does not wait if the lock is currently held by another thread but returns false immediately.
Returns
false if the lock is currently held by another thread, true otherwise.
See Also
enter
Definition at line 41 of file posix_SharedCode.h.
References mutex.
Referenced by try_lock().
 { return pthread_mutex_trylock (&mutex) == 0; }
void beast::CriticalSection::unlock () const inline noexcept
Definition at line 107 of file CriticalSection.h.
References exit().
 { exit (); }
Member Data Documentation
pthread_mutex_t beast::CriticalSection::mutex mutable private
Definition at line 126 of file CriticalSection.h.
Referenced by CriticalSection(), enter(), exit(), tryEnter(), and ~CriticalSection().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_core/threads/CriticalSection.h
rippled/src/beast/modules/beast_core/native/posix_SharedCode.h
rippled/src/beast/modules/beast_core/native/win32_Threads.cpp