rippled: rocksdb::IteratorWrapper Class Reference
rocksdb::IteratorWrapper Class Reference
#include <iterator_wrapper.h>
Public Member Functions
IteratorWrapper ()
IteratorWrapper (Iterator *iter)
~IteratorWrapper ()
Iterator * iter () const
void Set (Iterator *iter)
bool Valid () const
Slice key () const
Slice value () const
Status status () const
void Next ()
void Prev ()
void Seek (const Slice &k)
void SeekToFirst ()
void SeekToLast ()
Private Member Functions
void Update ()
Private Attributes
Iterator * iter_
bool valid_
Slice key_
Detailed Description
Definition at line 17 of file iterator_wrapper.h.
Constructor & Destructor Documentation
rocksdb::IteratorWrapper::IteratorWrapper () inline
Definition at line 19 of file iterator_wrapper.h.
 : iter_(nullptr), valid_(false) { }
rocksdb::IteratorWrapper::IteratorWrapper (Iterator * iter) inline explicit
Definition at line 20 of file iterator_wrapper.h.
References Set().
                                           : iter_(nullptr) {
     Set(iter);
   }
rocksdb::IteratorWrapper::~IteratorWrapper () inline
Definition at line 23 of file iterator_wrapper.h.
References iter_.
 { delete iter_; }
Member Function Documentation
Iterator* rocksdb::IteratorWrapper::iter () const inline
Definition at line 24 of file iterator_wrapper.h.
References iter_.
Referenced by Set().
 { return iter_; }
Slice rocksdb::IteratorWrapper::key () const inline
Definition at line 41 of file iterator_wrapper.h.
References key_, and Valid().
Referenced by rocksdb::MaxIteratorComparator::operator()(), and rocksdb::MinIteratorComparator::operator()().
 { assert(Valid()); return key_; }
void rocksdb::IteratorWrapper::Next () inline
Definition at line 45 of file iterator_wrapper.h.
References iter_, rocksdb::Iterator::Next(), and Update().
 { assert(iter_); iter_->Next();        Update(); }
void rocksdb::IteratorWrapper::Prev () inline
Definition at line 46 of file iterator_wrapper.h.
References iter_, rocksdb::Iterator::Prev(), and Update().
 { assert(iter_); iter_->Prev();        Update(); }
void rocksdb::IteratorWrapper::Seek (const Slice & k) inline
Definition at line 47 of file iterator_wrapper.h.
References iter_, rocksdb::Iterator::Seek(), and Update().
 { assert(iter_); iter_->Seek(k);       Update(); }
void rocksdb::IteratorWrapper::SeekToFirst () inline
Definition at line 48 of file iterator_wrapper.h.
References iter_, rocksdb::Iterator::SeekToFirst(), and Update().
 { assert(iter_); iter_->SeekToFirst(); Update(); }
void rocksdb::IteratorWrapper::SeekToLast () inline
Definition at line 49 of file iterator_wrapper.h.
References iter_, rocksdb::Iterator::SeekToLast(), and Update().
 { assert(iter_); iter_->SeekToLast();  Update(); }
void rocksdb::IteratorWrapper::Set (Iterator * iter) inline
Definition at line 28 of file iterator_wrapper.h.
References iter(), iter_, Update(), and valid_.
Referenced by IteratorWrapper().
{
     delete iter_;
     iter_ = iter;
     if (iter_ == nullptr) {
       valid_ = false;
     } else {
       Update();
     }
   }
Status rocksdb::IteratorWrapper::status () const inline
Definition at line 44 of file iterator_wrapper.h.
References iter_, and rocksdb::Iterator::status().
 { assert(iter_); return iter_->status(); }
void rocksdb::IteratorWrapper::Update () inline private
Definition at line 52 of file iterator_wrapper.h.
References iter_, rocksdb::Iterator::key(), key_, rocksdb::Iterator::Valid(), and valid_.
Referenced by Next(), Prev(), Seek(), SeekToFirst(), SeekToLast(), and Set().
                 {
     valid_ = iter_->Valid();
     if (valid_) {
       key_ = iter_->key();
     }
   }
bool rocksdb::IteratorWrapper::Valid () const inline
Definition at line 40 of file iterator_wrapper.h.
References valid_.
Referenced by key(), and value().
 { return valid_; }
Slice rocksdb::IteratorWrapper::value () const inline
Definition at line 42 of file iterator_wrapper.h.
References iter_, Valid(), and rocksdb::Iterator::value().
 { assert(Valid()); return iter_->value(); }
Member Data Documentation
Iterator* rocksdb::IteratorWrapper::iter_ private
Definition at line 59 of file iterator_wrapper.h.
Referenced by iter(), Next(), Prev(), Seek(), SeekToFirst(), SeekToLast(), Set(), status(), Update(), value(), and ~IteratorWrapper().
Slice rocksdb::IteratorWrapper::key_ private
Definition at line 61 of file iterator_wrapper.h.
Referenced by key(), and Update().
bool rocksdb::IteratorWrapper::valid_ private
Definition at line 60 of file iterator_wrapper.h.
Referenced by Set(), Update(), and Valid().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/table/iterator_wrapper.h