rippled: ripple::FeatureTable Class Reference
ripple::FeatureTable Class Reference abstract
#include <FeatureTable.h>
Public Member Functions
virtual ~FeatureTable ()
virtual void addInitial ()=0
virtual FeatureState * addKnown (const char *featureID, const char *friendlyName, bool veto)=0
virtual uint256 get (const std::string &name)=0
virtual bool veto (uint256 const &feature)=0
virtual bool unVeto (uint256 const &feature)=0
virtual bool enable (uint256 const &feature)=0
virtual bool disable (uint256 const &feature)=0
virtual bool isEnabled (uint256 const &feature)=0
virtual bool isSupported (uint256 const &feature)=0
virtual void setEnabled (const std::vector< uint256 > &features)=0
virtual void setSupported (const std::vector< uint256 > &features)=0
virtual void reportValidations (const FeatureSet &)=0
virtual Json::Value getJson (int)=0
virtual Json::Value getJson (uint256 const &)=0
virtual void doValidation (Ledger::ref lastClosedLedger, STObject &baseValidation)=0
virtual void doVoting (Ledger::ref lastClosedLedger, SHAMap::ref initialPosition)=0
Detailed Description
Feature table interface.
The feature table stores the list of enabled and potential features. Individuals features are voted on by validators during the consensus process.
Definition at line 109 of file FeatureTable.h.
Constructor & Destructor Documentation
virtual ripple::FeatureTable::~FeatureTable () inline virtual
Create a new FeatureTable.
Parameters
majorityTime the number of seconds a feature must hold a majority before we're willing to vote yes on it.
majorityFraction ratio, out of 256, of servers that must say they want a feature before we consider it to have a majority.
journal
Definition at line 122 of file FeatureTable.h.
 { }
Member Function Documentation
virtual void ripple::FeatureTable::addInitial () pure virtual
Implemented in ripple::FeaturesImpl.
virtual FeatureState* ripple::FeatureTable::addKnown (const char * featureID, const char * friendlyName, bool veto) pure virtual
Implemented in ripple::FeaturesImpl.
virtual bool ripple::FeatureTable::disable (uint256 const & feature) pure virtual
Implemented in ripple::FeaturesImpl.
virtual void ripple::FeatureTable::doValidation (Ledger::ref lastClosedLedger, STObject & baseValidation) pure virtual
Implemented in ripple::FeaturesImpl.
Referenced by ripple::LedgerConsensusImp::accept().
virtual void ripple::FeatureTable::doVoting (Ledger::ref lastClosedLedger, SHAMap::ref initialPosition) pure virtual
Implemented in ripple::FeaturesImpl.
Referenced by ripple::LedgerConsensusImp::takeInitialPosition().
virtual bool ripple::FeatureTable::enable (uint256 const & feature) pure virtual
Implemented in ripple::FeaturesImpl.
Referenced by ripple::ChangeTransactor::applyFeature().
virtual uint256 ripple::FeatureTable::get (const std::string & name) pure virtual
Implemented in ripple::FeaturesImpl.
Referenced by ripple::RPCHandler::doFeature().
virtual Json::Value ripple::FeatureTable::getJson (int) pure virtual
Implemented in ripple::FeaturesImpl.
Referenced by ripple::RPCHandler::doFeature().
virtual Json::Value ripple::FeatureTable::getJson (uint256 const &) pure virtual
Implemented in ripple::FeaturesImpl.
virtual bool ripple::FeatureTable::isEnabled (uint256 const & feature) pure virtual
Implemented in ripple::FeaturesImpl.
virtual bool ripple::FeatureTable::isSupported (uint256 const & feature) pure virtual
Implemented in ripple::FeaturesImpl.
virtual void ripple::FeatureTable::reportValidations (const FeatureSet &) pure virtual
Implemented in ripple::FeaturesImpl.
virtual void ripple::FeatureTable::setEnabled (const std::vector< uint256 > & features) pure virtual
Implemented in ripple::FeaturesImpl.
virtual void ripple::FeatureTable::setSupported (const std::vector< uint256 > & features) pure virtual
Implemented in ripple::FeaturesImpl.
virtual bool ripple::FeatureTable::unVeto (uint256 const & feature) pure virtual
Implemented in ripple::FeaturesImpl.
virtual bool ripple::FeatureTable::veto (uint256 const & feature) pure virtual
Implemented in ripple::FeaturesImpl.
The documentation for this class was generated from the following file:
rippled/src/ripple_app/misc/FeatureTable.h