rippled: rocksdb::ReduceLevelTest Class Reference
rocksdb::ReduceLevelTest Class Reference
Public Member Functions
ReduceLevelTest ()
Status OpenDB (bool create_if_missing, int levels, int mem_table_compact_level)
Status Put (const std::string &k, const std::string &v)
std::string Get (const std::string &k)
Status CompactMemTable ()
void CloseDB ()
bool ReduceLevels (int target_level)
int FilesOnLevel (int level)
Private Attributes
std::string dbname_
DB * db_
Detailed Description
Definition at line 16 of file reduce_levels_test.cc.
Constructor & Destructor Documentation
rocksdb::ReduceLevelTest::ReduceLevelTest () inline
Definition at line 18 of file reduce_levels_test.cc.
References db_, dbname_, rocksdb::DestroyDB(), and rocksdb::test::TmpDir().
                     {
     dbname_ = test::TmpDir() + "/db_reduce_levels_test";
     DestroyDB(dbname_, Options());
     db_ = nullptr;
   }
Member Function Documentation
void rocksdb::ReduceLevelTest::CloseDB () inline
Definition at line 51 of file reduce_levels_test.cc.
References db_.
                  {
     if (db_ != nullptr) {
       delete db_;
       db_ = nullptr;
     }
   }
Status rocksdb::ReduceLevelTest::CompactMemTable () inline
Definition at line 43 of file reduce_levels_test.cc.
References db_, rocksdb::Status::InvalidArgument(), and rocksdb::DBImpl::TEST_FlushMemTable().
{
     if (db_ == nullptr) {
       return Status::InvalidArgument("DB not opened.");
     }
     DBImpl* db_impl = reinterpret_cast<DBImpl*>(db_);
     return db_impl->TEST_FlushMemTable();
   }
int rocksdb::ReduceLevelTest::FilesOnLevel (int level) inline
Definition at line 60 of file reduce_levels_test.cc.
References ASSERT_TRUE, db_, rocksdb::DB::GetProperty(), and rocksdb::NumberToString().
{
     std::string property;
     ASSERT_TRUE(
         db_->GetProperty("rocksdb.num-files-at-level" + NumberToString(level),
                          &property));
     return atoi(property.c_str());
   }
std::string rocksdb::ReduceLevelTest::Get (const std::string & k) inline
Definition at line 31 of file reduce_levels_test.cc.
References db_, rocksdb::DB::Get(), rocksdb::Status::IsNotFound(), rocksdb::Status::ok(), and rocksdb::Status::ToString().
{
     ReadOptions options;
     std::string result;
     Status s = db_->Get(options, k, &result);
     if (s.IsNotFound()) {
       result = "NOT_FOUND";
     } else if (!s.ok()) {
       result = s.ToString();
     }
     return result;
   }
Status rocksdb::ReduceLevelTest::OpenDB (bool create_if_missing, int levels, int mem_table_compact_level)
Definition at line 73 of file reduce_levels_test.cc.
References rocksdb::Options::create_if_missing, db_, dbname_, rocksdb::Options::max_mem_compaction_level, rocksdb::Options::num_levels, rocksdb::Status::ok(), rocksdb::DB::Open(), and rocksdb::Status::ToString().
{
   rocksdb::Options opt;
   opt.num_levels = num_levels;
   opt.create_if_missing = create_if_missing;
   opt.max_mem_compaction_level = mem_table_compact_level;
   rocksdb::Status st = rocksdb::DB::Open(opt, dbname_, &db_);
   if (!st.ok()) {
     fprintf(stderr, "Can't open the db:%s\n", st.ToString().c_str());
   }
   return st;
 }
Status rocksdb::ReduceLevelTest::Put (const std::string & k, const std::string & v) inline
Definition at line 27 of file reduce_levels_test.cc.
References db_, and rocksdb::DB::Put().
{
     return db_->Put(WriteOptions(), k, v);
   }
bool rocksdb::ReduceLevelTest::ReduceLevels (int target_level)
Definition at line 86 of file reduce_levels_test.cc.
References dbname_, rocksdb::LDBCommand::GetExecuteState(), rocksdb::LDBCommand::InitFromCmdLineArgs(), rocksdb::LDBCommandExecuteResult::IsSucceed(), rocksdb::ReduceDBLevelsCommand::PrepareArgs(), and rocksdb::LDBCommand::Run().
{
   std::vector<std::string> args = rocksdb::ReduceDBLevelsCommand::PrepareArgs(
       dbname_, target_level, false);
   LDBCommand* level_reducer = LDBCommand::InitFromCmdLineArgs(args);
   level_reducer->Run();
   bool is_succeed = level_reducer->GetExecuteState().IsSucceed();
   delete level_reducer;
   return is_succeed;
 }
Member Data Documentation
DB* rocksdb::ReduceLevelTest::db_ private
Definition at line 70 of file reduce_levels_test.cc.
Referenced by CloseDB(), CompactMemTable(), FilesOnLevel(), Get(), OpenDB(), Put(), and ReduceLevelTest().
std::string rocksdb::ReduceLevelTest::dbname_ private
Definition at line 69 of file reduce_levels_test.cc.
Referenced by OpenDB(), ReduceLevels(), and ReduceLevelTest().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/tools/reduce_levels_test.cc