rippled: ripple::IHashRouter Class Reference
ripple::IHashRouter Class Reference abstract
#include <IHashRouter.h>
Public Types
typedef std::uint32_t PeerShortID
Public Member Functions
virtual ~IHashRouter ()
virtual bool addSuppression (uint256 const &index)=0
virtual bool addSuppressionPeer (uint256 const &index, PeerShortID peer)=0
virtual bool addSuppressionPeer (uint256 const &index, PeerShortID peer, int &flags)=0
virtual bool addSuppressionFlags (uint256 const &index, int flag)=0
virtual bool setFlag (uint256 const &index, int mask)=0
virtual int getFlags (uint256 const &index)=0
virtual bool swapSet (uint256 const &index, std::set< PeerShortID > &peers, int flag)=0
Static Public Member Functions
static int getDefaultHoldTime ()
static IHashRouter * New (int holdTime)
Detailed Description
Routing table for objects identified by hash.
This table keeps track of which hashes have been received by which peers. It is used to manage the routing and broadcasting of messages in the peer to peer overlay.
Definition at line 41 of file IHashRouter.h.
Member Typedef Documentation
typedef std::uint32_t ripple::IHashRouter::PeerShortID
Definition at line 45 of file IHashRouter.h.
Constructor & Destructor Documentation
virtual ripple::IHashRouter::~IHashRouter () inline virtual
Definition at line 58 of file IHashRouter.h.
 { }
Member Function Documentation
virtual bool ripple::IHashRouter::addSuppression (uint256 const & index) pure virtual
Implemented in ripple::HashRouter.
Referenced by ripple::LedgerConsensusImp::accept(), and ripple::LedgerConsensusImp::checkOurValidation().
virtual bool ripple::IHashRouter::addSuppressionFlags (uint256 const & index, int flag) pure virtual
Implemented in ripple::HashRouter.
Referenced by ripple::LedgerMasterImp::closeLedger().
virtual bool ripple::IHashRouter::addSuppressionPeer (uint256 const & index, PeerShortID peer) pure virtual
Implemented in ripple::HashRouter.
virtual bool ripple::IHashRouter::addSuppressionPeer (uint256 const & index, PeerShortID peer, int & flags) pure virtual
Implemented in ripple::HashRouter.
static int ripple::IHashRouter::getDefaultHoldTime () inline static
Definition at line 50 of file IHashRouter.h.
     {
         return 300;
     }
virtual int ripple::IHashRouter::getFlags (uint256 const & index) pure virtual
Implemented in ripple::HashRouter.
Referenced by ripple::NetworkOPsImp::processTransactionCb().
IHashRouter * ripple::IHashRouter::New (int holdTime) static
Definition at line 240 of file HashRouter.cpp.
 {
     return new HashRouter (holdTime);
 }
virtual bool ripple::IHashRouter::setFlag (uint256 const & index, int mask) pure virtual
Set the flags on a hash.
Returns
true if the flags were changed.
Implemented in ripple::HashRouter.
Referenced by ripple::LedgerConsensusImp::addDisputedTransaction(), ripple::LedgerConsensusImp::applyTransaction(), ripple::PeerImp::checkTransaction(), ripple::NetworkOPsImp::processTransactionCb(), ripple::NetworkOPsImp::runTransactionQueue(), and ripple::NetworkOPsImp::submitTransaction().
virtual bool ripple::IHashRouter::swapSet (uint256 const & index, std::set< PeerShortID > & peers, int flag) pure virtual
Implemented in ripple::HashRouter.
Referenced by ripple::NetworkOPsImp::processTransactionCb().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/misc/IHashRouter.h
rippled/src/ripple_app/misc/HashRouter.cpp