rippled: ripple::PeerFinder::CheckerImp::Request Class Reference
ripple::PeerFinder::CheckerImp::Request Class Reference
Public Types
typedef beast::SharedPtr< Request > Ptr
typedef boost::asio::ip::tcp Protocol
typedef boost::system::error_code error_code
typedef Protocol::socket socket_type
typedef Protocol::endpoint endpoint_type
Public Member Functions
Request (CheckerImp &owner, boost::asio::io_service &io_service, beast::IP::Endpoint const &address, beast::asio::shared_handler< void(Result)> const &handler)
~Request ()
void cancel ()
void handle_connect (boost::system::error_code ec)
Public Member Functions inherited from beast::SharedObject
void incReferenceCount () const noexcept
void decReferenceCount () const
int getReferenceCount () const noexcept
Public Attributes
CheckerImp & m_owner
boost::asio::io_service & m_io_service
beast::IP::Endpoint m_address
beast::asio::shared_handler
< void(Result)> m_handler
socket_type m_socket
boost::system::error_code m_error
bool m_canAccept
Additional Inherited Members
Protected Member Functions inherited from beast::SharedObject
SharedObject ()
virtual ~SharedObject ()
virtual void destroy () const
void resetReferenceCount () noexcept
Detailed Description
Definition at line 47 of file Checker.cpp.
Member Typedef Documentation
typedef Protocol::endpoint ripple::PeerFinder::CheckerImp::Request::endpoint_type
Definition at line 57 of file Checker.cpp.
typedef boost::system::error_code ripple::PeerFinder::CheckerImp::Request::error_code
Definition at line 55 of file Checker.cpp.
typedef boost::asio::ip::tcp ripple::PeerFinder::CheckerImp::Request::Protocol
Definition at line 54 of file Checker.cpp.
typedef beast::SharedPtr<Request> ripple::PeerFinder::CheckerImp::Request::Ptr
Definition at line 53 of file Checker.cpp.
typedef Protocol::socket ripple::PeerFinder::CheckerImp::Request::socket_type
Definition at line 56 of file Checker.cpp.
Constructor & Destructor Documentation
ripple::PeerFinder::CheckerImp::Request::Request (CheckerImp & owner, boost::asio::io_service & io_service, beast::IP::Endpoint const & address, beast::asio::shared_handler< void(Result)> const & handler) inline
Definition at line 67 of file Checker.cpp.
References ripple::PeerFinder::CheckerImp::add(), handle_connect(), m_address, m_handler, m_owner, m_socket, beast::IPAddressConversion::to_asio_endpoint(), and beast::asio::wrap_handler().
             : m_owner (owner)
             , m_io_service (io_service)
             , m_address (address)
             , m_handler (handler)
             , m_socket (m_io_service)
             , m_canAccept (false)
         {
             m_owner.add (*this);
             m_socket.async_connect (beast::IPAddressConversion::to_asio_endpoint (
                 m_address), beast::asio::wrap_handler (std::bind (
                     &Request::handle_connect, Ptr(this),
                         beast::asio::placeholders::error), m_handler));
         }
ripple::PeerFinder::CheckerImp::Request::~Request () inline
Definition at line 85 of file Checker.cpp.
References ripple::PeerFinder::Checker::Result::address, ripple::PeerFinder::Checker::Result::error, m_address, m_error, m_handler, m_io_service, m_owner, and ripple::PeerFinder::CheckerImp::remove().
         {
             Result result;
             result.address = m_address;
             result.error = m_error;
             m_io_service.wrap (m_handler) (result);
             m_owner.remove (*this);
         }
Member Function Documentation
void ripple::PeerFinder::CheckerImp::Request::cancel () inline
Definition at line 95 of file Checker.cpp.
References m_socket.
         {
             m_socket.cancel();
         }
void ripple::PeerFinder::CheckerImp::Request::handle_connect (boost::system::error_code ec) inline
Definition at line 100 of file Checker.cpp.
References m_canAccept, and m_error.
Referenced by Request().
         {
             m_error = ec;
             if (ec)
                 return;
             m_canAccept = true;
         }
Member Data Documentation
beast::IP::Endpoint ripple::PeerFinder::CheckerImp::Request::m_address
Definition at line 61 of file Checker.cpp.
Referenced by Request(), and ~Request().
bool ripple::PeerFinder::CheckerImp::Request::m_canAccept
Definition at line 65 of file Checker.cpp.
Referenced by handle_connect().
boost::system::error_code ripple::PeerFinder::CheckerImp::Request::m_error
Definition at line 64 of file Checker.cpp.
Referenced by handle_connect(), and ~Request().
beast::asio::shared_handler<void (Result)> ripple::PeerFinder::CheckerImp::Request::m_handler
Definition at line 62 of file Checker.cpp.
Referenced by Request(), and ~Request().
boost::asio::io_service& ripple::PeerFinder::CheckerImp::Request::m_io_service
Definition at line 60 of file Checker.cpp.
Referenced by ~Request().
CheckerImp& ripple::PeerFinder::CheckerImp::Request::m_owner
Definition at line 59 of file Checker.cpp.
Referenced by Request(), and ~Request().
socket_type ripple::PeerFinder::CheckerImp::Request::m_socket
Definition at line 63 of file Checker.cpp.
Referenced by cancel(), and Request().
The documentation for this class was generated from the following file:
rippled/src/ripple/peerfinder/impl/Checker.cpp