rippled: ripple::MultiSocket_test::MultiSocketDetails Class Reference
ripple::MultiSocket_test::MultiSocketDetails Class Reference
Public Types
typedef int arg_type
Public Member Functions
MultiSocketDetails (int flags)
beast::String name () const
arg_type getFlags () const noexcept
Public Member Functions inherited from beast::asio::TestPeerDetails
virtual ~TestPeerDetails ()
virtual abstract_socket & get_socket ()=0
virtual abstract_socket & get_acceptor ()=0
boost::asio::io_service & get_io_service ()
Static Public Member Functions
static beast::String getArgName (arg_type arg)
static boost::asio::ssl::context & getSSLContext ()
Protected Attributes
arg_type m_flags
Detailed Description
Definition at line 55 of file MultiSocket.cpp.
Member Typedef Documentation
typedef int ripple::MultiSocket_test::MultiSocketDetails::arg_type
Definition at line 58 of file MultiSocket.cpp.
Constructor & Destructor Documentation
ripple::MultiSocket_test::MultiSocketDetails::MultiSocketDetails (int flags) inline
Definition at line 60 of file MultiSocket.cpp.
             : m_flags (flags)
         {
         }
Member Function Documentation
static beast::String ripple::MultiSocket_test::MultiSocketDetails::getArgName (arg_type arg) inline static
Definition at line 65 of file MultiSocket.cpp.
References ripple::MultiSocket::Flag::client_role, beast::String::empty, beast::String::length(), ripple::MultiSocket::Flag::proxy, ripple::MultiSocket::Flag::server_role, ripple::MultiSocket::Flag::ssl, ripple::MultiSocket::Flag::ssl_required, and beast::String::substring().
Referenced by name().
         {
             beast::String s;
             if (arg & MultiSocket::Flag::client_role)
                 s << "client,";
             if (arg & MultiSocket::Flag::server_role)
                 s << "server,";
             if (arg & MultiSocket::Flag::ssl)
                 s << "ssl,";
             if (arg & MultiSocket::Flag::ssl_required)
                 s << "ssl_required,";
             if (arg & MultiSocket::Flag::proxy)
                 s << "proxy,";
             if (s != beast::String::empty)
             {
                 s = "(" + s.substring (0, s.length () - 1) + ")";
             }
             return s;
         }
arg_type ripple::MultiSocket_test::MultiSocketDetails::getFlags () const inline noexcept
Definition at line 118 of file MultiSocket.cpp.
References m_flags.
         {
             return m_flags;
         }
static boost::asio::ssl::context& ripple::MultiSocket_test::MultiSocketDetails::getSSLContext () inline static
Definition at line 92 of file MultiSocket.cpp.
References ripple::RippleSSLContext::createAnonymous().
         {
             struct ContextHolder
             {
                 ContextHolder ()
                     : context (RippleSSLContext::createAnonymous (
                         "ALL:!LOW:!EXP:!MD5:@STRENGTH"))
                 {
                     // VFALCO NOTE Not sure if this is needed?
                     context->get().set_verify_mode (
                         boost::asio::ssl::verify_none);
                 }
                 std::unique_ptr <RippleSSLContext> context;
             };
             static ContextHolder holder;
             return holder.context->get ();
         }
beast::String ripple::MultiSocket_test::MultiSocketDetails::name () const inline virtual
Implements beast::asio::TestPeerDetails.
Definition at line 113 of file MultiSocket.cpp.
References getArgName(), and m_flags.
         {
             return getArgName (m_flags);
         }
Member Data Documentation
arg_type ripple::MultiSocket_test::MultiSocketDetails::m_flags protected
Definition at line 124 of file MultiSocket.cpp.
Referenced by getFlags(), and name().
The documentation for this class was generated from the following file:
rippled/src/ripple/common/impl/MultiSocket.cpp