rippled: beast::unit_test::recorder Class Reference
beast::unit_test::recorder Class Reference
#include <recorder.h>
Public Member Functions
recorder (recorder const &)=default
recorder & operator= (recorder const &)=default
recorder ()
results const & report () const
Public Member Functions inherited from beast::unit_test::runner
virtual ~runner ()=default
runner (runner const &)=default
runner & operator= (runner const &)=default
runner ()
bool run (suite_info const &s)
template<class FwdIter >
bool run (FwdIter first, FwdIter last)
template<class FwdIter , class Pred >
bool run_if (FwdIter first, FwdIter last, Pred pred=Pred())
template<class SequenceContainer >
bool run_each (SequenceContainer const &c)
template<class SequenceContainer , class Pred >
bool run_each_if (SequenceContainer const &c, Pred pred=Pred())
Private Member Functions
virtual void on_suite_begin (suite_info const &info) override
virtual void on_suite_end () override
virtual void on_case_begin (std::string const &name) override
virtual void on_case_end () override
virtual void on_pass () override
virtual void on_fail (std::string const &reason) override
virtual void on_log (std::string const &s) override
Private Attributes
results m_results
suite_results m_suite
case_results m_case
Detailed Description
A test runner that stores the results.
Definition at line 30 of file recorder.h.
Constructor & Destructor Documentation
beast::unit_test::recorder::recorder (recorder const &) default
beast::unit_test::recorder::recorder () inline
Definition at line 41 of file recorder.h.
     {
     }
Member Function Documentation
virtual void beast::unit_test::recorder::on_case_begin (std::string const &) inline override private virtual
Called when a new case starts.
Reimplemented from beast::unit_test::runner.
Definition at line 68 of file recorder.h.
References m_case.
     {
         m_case = case_results (name);
     }
virtual void beast::unit_test::recorder::on_case_end () inline override private virtual
Called when a new case ends.
Reimplemented from beast::unit_test::runner.
Definition at line 75 of file recorder.h.
References beast::unit_test::suite_results::insert(), m_case, m_suite, beast::const_container< Container >::size(), and beast::unit_test::case_results::tests.
     {
         if (m_case.tests.size() > 0)
             m_suite.insert (std::move (m_case));
     }
virtual void beast::unit_test::recorder::on_fail (std::string const &) inline override private virtual
Called for each failing condition.
Reimplemented from beast::unit_test::runner.
Definition at line 90 of file recorder.h.
References beast::unit_test::case_results::tests_t::fail(), m_case, and beast::unit_test::case_results::tests.
     {
         m_case.tests.fail (reason);
     }
virtual void beast::unit_test::recorder::on_log (std::string const &) inline override private virtual
Called when a test logs output.
Reimplemented from beast::unit_test::runner.
Definition at line 97 of file recorder.h.
References beast::unit_test::case_results::log_t::insert(), beast::unit_test::case_results::log, and m_case.
     {
         m_case.log.insert (s);
     }
virtual void beast::unit_test::recorder::on_pass () inline override private virtual
Called for each passing condition.
Reimplemented from beast::unit_test::runner.
Definition at line 83 of file recorder.h.
References m_case, beast::unit_test::case_results::tests_t::pass(), and beast::unit_test::case_results::tests.
     {
         m_case.tests.pass();
     }
virtual void beast::unit_test::recorder::on_suite_begin (suite_info const &) inline override private virtual
Called when a new suite starts.
Reimplemented from beast::unit_test::runner.
Definition at line 54 of file recorder.h.
References beast::unit_test::suite_info::full_name(), and m_suite.
     {
         m_suite = suite_results (info.full_name());
     }
virtual void beast::unit_test::recorder::on_suite_end () inline override private virtual
Called when a suite ends.
Reimplemented from beast::unit_test::runner.
Definition at line 61 of file recorder.h.
References beast::unit_test::results::insert(), m_results, and m_suite.
     {
         m_results.insert (std::move (m_suite));
     }
recorder& beast::unit_test::recorder::operator= (recorder const &) default
results const& beast::unit_test::recorder::report () const inline
Returns a report with the results of all completed suites.
Definition at line 46 of file recorder.h.
References m_results.
     {
         return m_results;
     }
Member Data Documentation
case_results beast::unit_test::recorder::m_case private
Definition at line 35 of file recorder.h.
Referenced by on_case_begin(), on_case_end(), on_fail(), on_log(), and on_pass().
results beast::unit_test::recorder::m_results private
Definition at line 33 of file recorder.h.
Referenced by on_suite_end(), and report().
suite_results beast::unit_test::recorder::m_suite private
Definition at line 34 of file recorder.h.
Referenced by on_case_end(), on_suite_begin(), and on_suite_end().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/unit_test/recorder.h