rippled: rocksdb::EnvWrapper Class Reference
rocksdb::EnvWrapper Class Reference
#include <env.h>
Public Member Functions
EnvWrapper (Env *t)
virtual ~EnvWrapper ()
Env * target () const
Status NewSequentialFile (const std::string &f, unique_ptr< SequentialFile > *r, const EnvOptions &options)
Status NewRandomAccessFile (const std::string &f, unique_ptr< RandomAccessFile > *r, const EnvOptions &options)
Status NewWritableFile (const std::string &f, unique_ptr< WritableFile > *r, const EnvOptions &options)
Status NewRandomRWFile (const std::string &f, unique_ptr< RandomRWFile > *r, const EnvOptions &options)
bool FileExists (const std::string &f)
Status GetChildren (const std::string &dir, std::vector< std::string > *r)
Status DeleteFile (const std::string &f)
Status CreateDir (const std::string &d)
Status CreateDirIfMissing (const std::string &d)
Status DeleteDir (const std::string &d)
Status GetFileSize (const std::string &f, uint64_t *s)
Status GetFileModificationTime (const std::string &fname, uint64_t *file_mtime)
Status RenameFile (const std::string &s, const std::string &t)
Status LockFile (const std::string &f, FileLock **l)
Status UnlockFile (FileLock *l)
void Schedule (void(*f)(void *), void *a, Priority pri)
void StartThread (void(*f)(void *), void *a)
virtual Status GetTestDirectory (std::string *path)
virtual Status NewLogger (const std::string &fname, shared_ptr< Logger > *result)
uint64_t NowMicros ()
void SleepForMicroseconds (int micros)
Status GetHostName (char *name, uint64_t len)
Status GetCurrentTime (int64_t *unix_time)
Status GetAbsolutePath (const std::string &db_path, std::string *output_path)
void SetBackgroundThreads (int num, Priority pri)
std::string TimeToString (uint64_t time)
Public Member Functions inherited from rocksdb::Env
Env ()
virtual ~Env ()
virtual void Schedule (void(*function)(void *arg), void *arg, Priority pri=LOW)=0
virtual void StartThread (void(*function)(void *arg), void *arg)=0
virtual uint64_t NowNanos ()
virtual std::string GenerateUniqueId ()
Private Attributes
Env * target_
Additional Inherited Members
Public Types inherited from rocksdb::Env
enum Priority { LOW, HIGH, TOTAL }
Static Public Member Functions inherited from rocksdb::Env
static Env * Default ()
Detailed Description
Definition at line 553 of file env.h.
Constructor & Destructor Documentation
rocksdb::EnvWrapper::EnvWrapper (Env * t) inline explicit
Definition at line 556 of file env.h.
 : target_(t) { }
rocksdb::EnvWrapper::~EnvWrapper () virtual
Definition at line 117 of file env.cc.
{
 }
Member Function Documentation
Status rocksdb::EnvWrapper::CreateDir (const std::string & d) inline virtual
Implements rocksdb::Env.
Definition at line 586 of file env.h.
References rocksdb::Env::CreateDir(), and target_.
 { return target_->CreateDir(d); }
Status rocksdb::EnvWrapper::CreateDirIfMissing (const std::string & d) inline virtual
Implements rocksdb::Env.
Definition at line 587 of file env.h.
References rocksdb::Env::CreateDirIfMissing(), and target_.
{
     return target_->CreateDirIfMissing(d);
   }
Status rocksdb::EnvWrapper::DeleteDir (const std::string & d) inline virtual
Implements rocksdb::Env.
Definition at line 590 of file env.h.
References rocksdb::Env::DeleteDir(), and target_.
 { return target_->DeleteDir(d); }
Status rocksdb::EnvWrapper::DeleteFile (const std::string & f) inline virtual
Implements rocksdb::Env.
Definition at line 585 of file env.h.
References rocksdb::Env::DeleteFile(), and target_.
 { return target_->DeleteFile(f); }
bool rocksdb::EnvWrapper::FileExists (const std::string & f) inline virtual
Implements rocksdb::Env.
Definition at line 581 of file env.h.
References rocksdb::Env::FileExists(), and target_.
 { return target_->FileExists(f); }
Status rocksdb::EnvWrapper::GetAbsolutePath (const std::string & db_path, std::string * output_path) inline virtual
Implements rocksdb::Env.
Definition at line 632 of file env.h.
References rocksdb::Env::GetAbsolutePath(), and target_.
{
     return target_->GetAbsolutePath(db_path, output_path);
   }
Status rocksdb::EnvWrapper::GetChildren (const std::string & dir, std::vector< std::string > * r) inline virtual
Implements rocksdb::Env.
Definition at line 582 of file env.h.
References rocksdb::Env::GetChildren(), and target_.
Referenced by rocksdb::CorruptionTest::Corrupt(), rocksdb::DBTest::CountFiles(), and rocksdb::GetLogDirSize().
{
     return target_->GetChildren(dir, r);
   }
Status rocksdb::EnvWrapper::GetCurrentTime (int64_t * unix_time) inline virtual
Implements rocksdb::Env.
Definition at line 629 of file env.h.
References rocksdb::Env::GetCurrentTime(), and target_.
{
     return target_->GetCurrentTime(unix_time);
   }
Status rocksdb::EnvWrapper::GetFileModificationTime (const std::string & fname, uint64_t * file_mtime) inline virtual
Implements rocksdb::Env.
Definition at line 595 of file env.h.
References rocksdb::Env::GetFileModificationTime(), and target_.
{
     return target_->GetFileModificationTime(fname, file_mtime);
   }
Status rocksdb::EnvWrapper::GetFileSize (const std::string & f, uint64_t * s) inline virtual
Implements rocksdb::Env.
Definition at line 591 of file env.h.
References rocksdb::Env::GetFileSize(), and target_.
Referenced by rocksdb::GetLogDirSize().
{
     return target_->GetFileSize(f, s);
   }
Status rocksdb::EnvWrapper::GetHostName (char * name, uint64_t len) inline virtual
Implements rocksdb::Env.
Definition at line 626 of file env.h.
References rocksdb::Env::GetHostName(), and target_.
{
     return target_->GetHostName(name, len);
   }
virtual Status rocksdb::EnvWrapper::GetTestDirectory (std::string * path) inline virtual
Implements rocksdb::Env.
Definition at line 613 of file env.h.
References rocksdb::Env::GetTestDirectory(), and target_.
{
     return target_->GetTestDirectory(path);
   }
Status rocksdb::EnvWrapper::LockFile (const std::string & f, FileLock ** l) inline virtual
Implements rocksdb::Env.
Definition at line 603 of file env.h.
References rocksdb::Env::LockFile(), and target_.
{
     return target_->LockFile(f, l);
   }
virtual Status rocksdb::EnvWrapper::NewLogger (const std::string & fname, shared_ptr< Logger > * result) inline virtual
Implements rocksdb::Env.
Definition at line 616 of file env.h.
References rocksdb::Env::NewLogger(), and target_.
{
     return target_->NewLogger(fname, result);
   }
Status rocksdb::EnvWrapper::NewRandomAccessFile (const std::string & f, unique_ptr< RandomAccessFile > * r, const EnvOptions & options) inline virtual
Implements rocksdb::Env.
Definition at line 568 of file env.h.
References rocksdb::Env::NewRandomAccessFile(), and target_.
{
     return target_->NewRandomAccessFile(f, r, options);
   }
Status rocksdb::EnvWrapper::NewRandomRWFile (const std::string & f, unique_ptr< RandomRWFile > * r, const EnvOptions & options) inline virtual
Implements rocksdb::Env.
Definition at line 577 of file env.h.
References rocksdb::Env::NewRandomRWFile(), and target_.
{
     return target_->NewRandomRWFile(f, r, options);
   }
Status rocksdb::EnvWrapper::NewSequentialFile (const std::string & f, unique_ptr< SequentialFile > * r, const EnvOptions & options) inline virtual
Implements rocksdb::Env.
Definition at line 563 of file env.h.
References rocksdb::Env::NewSequentialFile(), and target_.
{
     return target_->NewSequentialFile(f, r, options);
   }
Status rocksdb::EnvWrapper::NewWritableFile (const std::string & f, unique_ptr< WritableFile > * r, const EnvOptions & options) inline virtual
Implements rocksdb::Env.
Reimplemented in rocksdb::test::ErrorEnv.
Definition at line 573 of file env.h.
References rocksdb::Env::NewWritableFile(), and target_.
{
     return target_->NewWritableFile(f, r, options);
   }
uint64_t rocksdb::EnvWrapper::NowMicros () inline virtual
Implements rocksdb::Env.
Definition at line 620 of file env.h.
References rocksdb::Env::NowMicros(), and target_.
{
     return target_->NowMicros();
   }
Status rocksdb::EnvWrapper::RenameFile (const std::string & s, const std::string & t) inline virtual
Implements rocksdb::Env.
Definition at line 600 of file env.h.
References rocksdb::Env::RenameFile(), and target_.
{
     return target_->RenameFile(s, t);
   }
void rocksdb::EnvWrapper::Schedule (void(*)(void *) f, void * a, Priority pri) inline
Definition at line 607 of file env.h.
References ripple::f, rocksdb::Env::Schedule(), and target_.
{
     return target_->Schedule(f, a, pri);
   }
void rocksdb::EnvWrapper::SetBackgroundThreads (int num, Priority pri) inline virtual
Implements rocksdb::Env.
Definition at line 636 of file env.h.
References rocksdb::Env::SetBackgroundThreads(), and target_.
{
     return target_->SetBackgroundThreads(num, pri);
   }
void rocksdb::EnvWrapper::SleepForMicroseconds (int micros) inline virtual
Implements rocksdb::Env.
Definition at line 623 of file env.h.
References rocksdb::Env::SleepForMicroseconds(), and target_.
{
     target_->SleepForMicroseconds(micros);
   }
void rocksdb::EnvWrapper::StartThread (void(*)(void *) f, void * a) inline
Definition at line 610 of file env.h.
References ripple::f, rocksdb::Env::StartThread(), and target_.
{
     return target_->StartThread(f, a);
   }
Env* rocksdb::EnvWrapper::target () const inline
Definition at line 560 of file env.h.
References target_.
Referenced by rocksdb::SpecialEnv::NewRandomAccessFile(), rocksdb::test::ErrorEnv::NewWritableFile(), rocksdb::SpecialEnv::NewWritableFile(), and rocksdb::SpecialEnv::SleepForMicroseconds().
 { return target_; }
std::string rocksdb::EnvWrapper::TimeToString (uint64_t time) inline virtual
Implements rocksdb::Env.
Definition at line 639 of file env.h.
References target_, and rocksdb::Env::TimeToString().
{
     return target_->TimeToString(time);
   }
Status rocksdb::EnvWrapper::UnlockFile (FileLock * l) inline virtual
Implements rocksdb::Env.
Definition at line 606 of file env.h.
References target_, and rocksdb::Env::UnlockFile().
 { return target_->UnlockFile(l); }
Member Data Documentation
Env* rocksdb::EnvWrapper::target_ private
Definition at line 644 of file env.h.
Referenced by CreateDir(), CreateDirIfMissing(), DeleteDir(), DeleteFile(), FileExists(), GetAbsolutePath(), GetChildren(), GetCurrentTime(), GetFileModificationTime(), GetFileSize(), GetHostName(), GetTestDirectory(), LockFile(), NewLogger(), rocksdb::SpecialEnv::NewRandomAccessFile(), NewRandomAccessFile(), NewRandomRWFile(), NewSequentialFile(), NewWritableFile(), NowMicros(), RenameFile(), Schedule(), SetBackgroundThreads(), SleepForMicroseconds(), StartThread(), target(), TimeToString(), and UnlockFile().
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/include/rocksdb/env.h
rippled/src/ripple/rocksdb/rocksdb/util/env.cc