rippled: ShellStateConnected Class Reference
ShellStateConnected Class Reference
#include <ShellState.h>
Public Member Functions
virtual void run (ShellContext *)
Public Member Functions inherited from ShellState
virtual ~ShellState ()
Static Public Member Functions
static ShellStateConnected * getInstance (void)
Private Member Functions
ShellStateConnected ()
virtual ~ShellStateConnected ()
void unknownCmd ()
void handleConError (ShellContext *)
void helpMsg ()
Detailed Description
Definition at line 68 of file ShellState.h.
Constructor & Destructor Documentation
ShellStateConnected::ShellStateConnected () inline private
Definition at line 78 of file ShellState.h.
 {}
virtual ShellStateConnected::~ShellStateConnected () inline private virtual
Definition at line 79 of file ShellState.h.
 {}
Member Function Documentation
static ShellStateConnected* ShellStateConnected::getInstance (void) inline static
Definition at line 70 of file ShellState.h.
References instance.
Referenced by ShellStateConnecting::run().
{
     static ShellStateConnected instance;
     return &instance;
   }
void ShellStateConnected::handleConError (ShellContext * c) private
Definition at line 56 of file ShellState.cpp.
References ShellContext::changeState(), ShellStateStop::getInstance(), and ShellStateConnecting::getInstance().
{
   cout << "Connection down" << endl;
   cout << "Reconnect ? (y/n) :" << endl;
   string s;
   while(getline(cin, s)) {
     if("y" == s) {
       c->changeState(ShellStateConnecting::getInstance());
       break;
     } else if("n" == s) {
       c->changeState(ShellStateStop::getInstance());
       break;
     } else {
       cout << "Reconnect ? (y/n) :" << endl;
     }
   }
 }
void ShellStateConnected::helpMsg (void) private
Definition at line 47 of file ShellState.cpp.
{
   cout << "Currently supported commands:" << endl;
   cout << "create db" << endl;
   cout << "get db key" << endl;
   cout << "scan db start_key end_key limit" << endl;
   cout << "put db key value" << endl;
   cout << "exit/quit" << endl;
 }
void ShellStateConnected::run (ShellContext * c) virtual
Implements ShellState.
Definition at line 73 of file ShellState.cpp.
References ShellContext::changeState(), ShellContext::create(), ShellContext::get(), ShellStateStop::getInstance(), PMT, ShellContext::put(), and ShellContext::scan().
{
   string line;
   cout << PMT;
   getline(cin, line);
   istringstream is(line);
   vector<string> params;
   string param;
   while(is >> param) {
     params.push_back(param);
   }
   // empty input line
   if(params.empty())
     return;
   if("quit" == params[0] || "exit" == params[0]) {
     c->changeState(ShellStateStop::getInstance());
   } else if("get" == params[0]) {
     if(params.size() == 3) {
       try {
         c->get(params[1], params[2]);
       } catch (const TTransportException & e) {
         cout << e.what() << endl;
         handleConError(c);
       }
     } else {
       unknownCmd();
     }
   } else if("create" == params[0]) {
     if(params.size() == 2) {
       try {
         c->create(params[1]);
       } catch (const TTransportException & e) {
         cout << e.what() << endl;
         handleConError(c);
       }
     } else {
       unknownCmd();
     }
   }else if("put" == params[0]) {
     if(params.size() == 4) {
       try {
         c->put(params[1], params[2], params[3]);
       } catch (const TTransportException & e) {
         cout << e.what() << endl;
         handleConError(c);
       }
     } else {
       unknownCmd();
     }
   } else if("scan" == params[0]) {
     if(params.size() == 5) {
       try {
         c->scan(params[1], params[2], params[3], params[4]);
       } catch (const TTransportException & e) {
         cout << e.what() << endl;
         handleConError(c);
       }
     } else {
       unknownCmd();
     }
   } else if("help" == params[0]) {
     helpMsg();
   } else {
     unknownCmd();
   }
 }
void ShellStateConnected::unknownCmd (void) private
Definition at line 42 of file ShellState.cpp.
{
   cout << "Unknown command!" << endl;
   cout << "Use help to list all available commands" << endl;
 }
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/tools/shell/ShellState.h
rippled/src/ripple/rocksdb/rocksdb/tools/shell/ShellState.cpp