rippled: beast::insight::detail::StatsDCollectorImp Class Reference
beast::insight::detail::StatsDCollectorImp Class Reference
Classes
struct StateType
Public Member Functions
StatsDCollectorImp (IP::Endpoint const &address, std::string const &prefix, Journal journal)
~StatsDCollectorImp ()
Hook make_hook (HookImpl::HandlerType const &handler)
Counter make_counter (std::string const &name)
Event make_event (std::string const &name)
Gauge make_gauge (std::string const &name)
Meter make_meter (std::string const &name)
void add (StatsDMetricBase &metric)
void remove (StatsDMetricBase &metric)
boost::asio::io_service & get_io_service ()
std::string const & prefix () const
void do_post_buffer (std::string const &buffer)
void post_buffer (std::string &&buffer)
void on_send (boost::system::error_code ec, std::size_t)
void log (std::vector< boost::asio::const_buffer > const &buffers)
void send_buffers ()
void set_timer ()
void on_timer (boost::system::error_code ec)
void run ()
Private Types
enum { max_packet_size = 1472 }
typedef SharedData< StateType > State
Static Private Member Functions
static
boost::asio::ip::udp::endpoint to_endpoint (IP::Endpoint const &address)
Private Attributes
Journal m_journal
IP::Endpoint m_address
std::string m_prefix
boost::asio::io_service m_io_service
boost::optional
< boost::asio::io_service::work > m_work
boost::asio::deadline_timer m_timer
boost::asio::ip::udp::socket m_socket
std::deque< std::string > m_data
State m_state
std::thread m_thread
Additional Inherited Members
Public Types inherited from beast::insight::Collector
typedef std::shared_ptr
< Collector > ptr
Static Public Member Functions inherited from beast::insight::StatsDCollector
static std::shared_ptr
< StatsDCollector > New (IP::Endpoint const &address, std::string const &prefix, Journal journal)
Detailed Description
Definition at line 186 of file StatsDCollector.cpp.
Member Typedef Documentation
typedef SharedData<StateType> beast::insight::detail::StatsDCollectorImp::State private
Definition at line 202 of file StatsDCollector.cpp.
Member Enumeration Documentation
anonymous enum private
Enumerator
max_packet_size
Definition at line 191 of file StatsDCollector.cpp.
     {
         //max_packet_size = 484
         max_packet_size = 1472
     };
Constructor & Destructor Documentation
beast::insight::detail::StatsDCollectorImp::StatsDCollectorImp (IP::Endpoint const & address, std::string const & prefix, Journal journal) inline
Definition at line 234 of file StatsDCollector.cpp.
         : m_journal (journal)
         , m_address (address)
         , m_prefix (prefix)
         , m_work (boost::ref (m_io_service))
         , m_timer (m_io_service)
         , m_socket (m_io_service)
         , m_thread (&StatsDCollectorImp::run, this)
     {
     }
beast::insight::detail::StatsDCollectorImp::~StatsDCollectorImp () inline
Definition at line 248 of file StatsDCollector.cpp.
References m_thread, m_timer, and m_work.
     {
         boost::system::error_code ec;
         m_timer.cancel (ec);
         m_work = boost::none;
         m_thread.join ();
     }
Member Function Documentation
void beast::insight::detail::StatsDCollectorImp::add (StatsDMetricBase & metric) inline
Definition at line 289 of file StatsDCollector.cpp.
References m_state.
     {
         State::Access state (m_state);
         state->metrics.push_back (metric);
     }
void beast::insight::detail::StatsDCollectorImp::do_post_buffer (std::string const & buffer) inline
Definition at line 313 of file StatsDCollector.cpp.
References m_data.
Referenced by post_buffer().
     {
         m_data.emplace_back (buffer);
     }
boost::asio::io_service& beast::insight::detail::StatsDCollectorImp::get_io_service () inline
Definition at line 303 of file StatsDCollector.cpp.
References m_io_service.
     {
         return m_io_service;
     }
void beast::insight::detail::StatsDCollectorImp::log (std::vector< boost::asio::const_buffer > const & buffers) inline
Definition at line 338 of file StatsDCollector.cpp.
References beast::Logger::outputDebugString().
Referenced by send_buffers().
     {
         (void)buffers;
 #if BEAST_STATSDCOLLECTOR_TRACING_ENABLED
         std::stringstream ss;
         for (auto const& buffer : buffers)
         {
             std::string const s (boost::asio::buffer_cast <char const*> (buffer),
                 boost::asio::buffer_size (buffer));
             ss << s;
         }
         //m_journal.trace << std::endl << ss.str ();
         Logger::outputDebugString (ss.str ());
 #endif
     }
Counter beast::insight::detail::StatsDCollectorImp::make_counter (std::string const & name) inline virtual
Create a counter with the specified name.
See Also
Counter
Implements beast::insight::Collector.
Definition at line 263 of file StatsDCollector.cpp.
     {
         return Counter (std::make_shared <detail::StatsDCounterImpl> (
             name, shared_from_this ()));
     }
Event beast::insight::detail::StatsDCollectorImp::make_event (std::string const & name) inline virtual
Create an event with the specified name.
See Also
Event
Implements beast::insight::Collector.
Definition at line 269 of file StatsDCollector.cpp.
     {
         return Event (std::make_shared <detail::StatsDEventImpl> (
             name, shared_from_this ()));
     }
Gauge beast::insight::detail::StatsDCollectorImp::make_gauge (std::string const & name) inline virtual
Create a gauge with the specified name.
See Also
Gauge
Implements beast::insight::Collector.
Definition at line 275 of file StatsDCollector.cpp.
     {
         return Gauge (std::make_shared <detail::StatsDGaugeImpl> (
             name, shared_from_this ()));
     }
Hook beast::insight::detail::StatsDCollectorImp::make_hook (HookImpl::HandlerType const & handler) inline virtual
Implements beast::insight::Collector.
Definition at line 257 of file StatsDCollector.cpp.
     {
         return Hook (std::make_shared <detail::StatsDHookImpl> (
             handler, shared_from_this ()));
     }
Meter beast::insight::detail::StatsDCollectorImp::make_meter (std::string const & name) inline virtual
Create a meter with the specified name.
See Also
Meter
Implements beast::insight::Collector.
Definition at line 281 of file StatsDCollector.cpp.
     {
         return Meter (std::make_shared <detail::StatsDMeterImpl> (
             name, shared_from_this ()));
     }
void beast::insight::detail::StatsDCollectorImp::on_send (boost::system::error_code ec, std::size_t) inline
Definition at line 325 of file StatsDCollector.cpp.
References beast::Journal::error, and m_journal.
Referenced by send_buffers().
     {
         if (ec == boost::asio::error::operation_aborted)
             return;
         if (ec)
         {
             m_journal.error <<
                 "async_send failed: " << ec.message();
             return;
         }
     }
void beast::insight::detail::StatsDCollectorImp::on_timer (boost::system::error_code ec) inline
Definition at line 406 of file StatsDCollector.cpp.
References beast::Journal::error, m_journal, m_state, send_buffers(), and set_timer().
Referenced by set_timer().
     {
         if (ec == boost::asio::error::operation_aborted)
             return;
         if (ec)
         {
             m_journal.error <<
                 "on_timer failed: " << ec.message();
             return;
         }
         State::Access state (m_state);
         for (List <StatsDMetricBase>::iterator iter (state->metrics.begin());
             iter != state->metrics.end(); ++iter)
             iter->do_process();
         send_buffers ();
         set_timer ();
     }
void beast::insight::detail::StatsDCollectorImp::post_buffer (std::string && buffer) inline
Definition at line 318 of file StatsDCollector.cpp.
References do_post_buffer(), and m_io_service.
     {
         m_io_service.dispatch (std::bind (
             &StatsDCollectorImp::do_post_buffer, this,
                 std::move (buffer)));
     }
std::string const& beast::insight::detail::StatsDCollectorImp::prefix () const inline
Definition at line 308 of file StatsDCollector.cpp.
References m_prefix.
     {
         return m_prefix;
     }
void beast::insight::detail::StatsDCollectorImp::remove (StatsDMetricBase & metric) inline
Definition at line 295 of file StatsDCollector.cpp.
References m_state.
     {
         State::Access state (m_state);
         state->metrics.erase (state->metrics.iterator_to (metric));
     }
void beast::insight::detail::StatsDCollectorImp::run () inline
Definition at line 429 of file StatsDCollector.cpp.
References beast::Journal::error, m_address, m_io_service, m_journal, m_socket, set_timer(), and to_endpoint().
     {
         boost::system::error_code ec;
         if (m_socket.connect (to_endpoint (m_address), ec))
         {
             m_journal.error <<
                 "Connect failed: " << ec.message();
             return;
         }
         set_timer ();
         m_io_service.run ();
         m_socket.shutdown (
             boost::asio::ip::udp::socket::shutdown_send, ec);
         m_socket.close ();
         m_io_service.poll ();
     }
void beast::insight::detail::StatsDCollectorImp::send_buffers () inline
Definition at line 355 of file StatsDCollector.cpp.
References log(), m_data, m_socket, max_packet_size, and on_send().
Referenced by on_timer().
     {
         // Break up the array of strings into blocks
         // that each fit into one UDP packet.
         //
         boost::system::error_code ec;
         std::vector <boost::asio::const_buffer> buffers;
         buffers.reserve (m_data.size ());
         std::size_t size (0);
         for (std::deque <std::string>::const_iterator iter (m_data.begin());
             iter != m_data.end(); ++iter)
         {
             std::string const& buffer (*iter);
             std::size_t const length (buffer.size ());
             assert (! buffer.empty ());
             if (! buffers.empty () && (size + length) > max_packet_size)
             {
 #if BEAST_STATSDCOLLECTOR_TRACING_ENABLED
                 log (buffers);
 #endif
                 m_socket.async_send (buffers, boost::bind (
                     &StatsDCollectorImp::on_send, this,
                         boost::asio::placeholders::error,
                             boost::asio::placeholders::bytes_transferred));
                 buffers.clear ();
                 size = 0;
             }
             buffers.emplace_back (&buffer[0], length);
             size += length;
         }
         if (! buffers.empty ())
         {
 #if BEAST_STATSDCOLLECTOR_TRACING_ENABLED
             log (buffers);
 #endif
             m_socket.async_send (buffers, boost::bind (
                 &StatsDCollectorImp::on_send, this,
                     boost::asio::placeholders::error,
                         boost::asio::placeholders::bytes_transferred));
         }
         m_data.clear ();
     }
void beast::insight::detail::StatsDCollectorImp::set_timer () inline
Definition at line 398 of file StatsDCollector.cpp.
References m_timer, and on_timer().
Referenced by on_timer(), and run().
     {
         m_timer.expires_from_now (boost::posix_time::seconds (1));
         m_timer.async_wait (boost::bind (
             &StatsDCollectorImp::on_timer, this,
                 boost::asio::placeholders::error));
     }
static boost::asio::ip::udp::endpoint beast::insight::detail::StatsDCollectorImp::to_endpoint (IP::Endpoint const & address) inline static private
Definition at line 217 of file StatsDCollector.cpp.
References bassertfalse, beast::IP::Endpoint::is_v4(), beast::IP::Endpoint::port(), beast::IP::Endpoint::to_v4(), and beast::IP::AddressV4::value.
Referenced by run().
     {
         if (address.is_v4 ())
         {
             return boost::asio::ip::udp::endpoint (
                 boost::asio::ip::address_v4 (
                     address.to_v4().value), address.port ());
         }
         // VFALCO TODO IPv6 support
         bassertfalse;
         return boost::asio::ip::udp::endpoint (
             boost::asio::ip::address_v6 (), 0);
     }
Member Data Documentation
IP::Endpoint beast::insight::detail::StatsDCollectorImp::m_address private
Definition at line 205 of file StatsDCollector.cpp.
Referenced by run().
std::deque<std::string> beast::insight::detail::StatsDCollectorImp::m_data private
Definition at line 211 of file StatsDCollector.cpp.
Referenced by do_post_buffer(), and send_buffers().
boost::asio::io_service beast::insight::detail::StatsDCollectorImp::m_io_service private
Definition at line 207 of file StatsDCollector.cpp.
Referenced by get_io_service(), post_buffer(), and run().
Journal beast::insight::detail::StatsDCollectorImp::m_journal private
Definition at line 204 of file StatsDCollector.cpp.
Referenced by on_send(), on_timer(), and run().
std::string beast::insight::detail::StatsDCollectorImp::m_prefix private
Definition at line 206 of file StatsDCollector.cpp.
Referenced by prefix().
boost::asio::ip::udp::socket beast::insight::detail::StatsDCollectorImp::m_socket private
Definition at line 210 of file StatsDCollector.cpp.
Referenced by run(), and send_buffers().
State beast::insight::detail::StatsDCollectorImp::m_state private
Definition at line 212 of file StatsDCollector.cpp.
Referenced by add(), on_timer(), and remove().
std::thread beast::insight::detail::StatsDCollectorImp::m_thread private
Definition at line 215 of file StatsDCollector.cpp.
Referenced by ~StatsDCollectorImp().
boost::asio::deadline_timer beast::insight::detail::StatsDCollectorImp::m_timer private
Definition at line 209 of file StatsDCollector.cpp.
Referenced by set_timer(), and ~StatsDCollectorImp().
boost::optional<boost::asio::io_service::work> beast::insight::detail::StatsDCollectorImp::m_work private
Definition at line 208 of file StatsDCollector.cpp.
Referenced by ~StatsDCollectorImp().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/insight/impl/StatsDCollector.cpp