rippled: beast::asio::socket_wrapper< Object > Class Template Reference
beast::asio::socket_wrapper< Object > Class Template Reference
#include <socket_wrapper.h>
Classes
struct Enabled
struct extract_lowest_layer_type
struct extract_lowest_layer_type< T, false >
struct extract_native_handle_type
struct extract_native_handle_type< T, false >
struct extract_next_layer_type
struct extract_next_layer_type< T, false >
struct has_type_lowest_layer_type
struct has_type_native_handle_type
struct has_type_next_layer_type
struct native_socket
struct native_socket< T, typename boost::enable_if< boost::is_class< typename T::protocol_type::socket > >::type >
Public Types
typedef
boost::remove_reference
< Object >::type this_layer_type
Public Member Functions
template<class... Args>
socket_wrapper (Args &&...args)
socket_wrapper (socket_wrapper const &)=delete
socket_wrapper & operator= (socket_wrapper const &)=delete
this_layer_type & this_layer () noexcept
this_layer_type const & this_layer () const noexcept
void * this_layer_ptr (char const *type_name) const override
Public Member Functions inherited from beast::asio::abstract_socket
virtual ~abstract_socket ()
template<typename Handle >
void native_handle (Handle *dest)
void cancel ()
void shutdown (shutdown_type what)
void close ()
void handshake (handshake_type type)
void shutdown ()
template<class Object >
Object & this_layer ()
template<class Object >
Object const & this_layer () const
template<class Object >
Object * this_layer_ptr ()
template<class Object >
Object const * this_layer_ptr () const
template<class Object >
Object & lowest_layer ()
template<class Object >
Object const & lowest_layer () const
template<class Object >
Object * lowest_layer_ptr ()
template<class Object >
Object const * lowest_layer_ptr () const
template<class Object >
Object & next_layer ()
template<class Object >
Object const & next_layer () const
template<class Object >
Object * next_layer_ptr ()
template<class Object >
Object const * next_layer_ptr () const
Private Types
typedef
extract_native_handle_type
< this_layer_type >::type native_handle_type
typedef
extract_lowest_layer_type
< this_layer_type >::type lowest_layer_type
typedef
extract_next_layer_type
< this_layer_type >::type next_layer_type
Private Member Functions
BEAST_DEFINE_IS_CALL_POSSIBLE (has_get_io_service, get_io_service)
BEAST_DEFINE_IS_CALL_POSSIBLE (has_lowest_layer, lowest_layer)
BEAST_DEFINE_IS_CALL_POSSIBLE (has_cancel, cancel)
BEAST_DEFINE_IS_CALL_POSSIBLE (has_shutdown, shutdown)
BEAST_DEFINE_IS_CALL_POSSIBLE (has_close, close)
BEAST_DEFINE_IS_CALL_POSSIBLE (has_accept, accept)
BEAST_DEFINE_IS_CALL_POSSIBLE (has_async_accept, async_accept)
BEAST_DEFINE_IS_CALL_POSSIBLE (has_read_some, read_some)
BEAST_DEFINE_IS_CALL_POSSIBLE (has_write_some, write_some)
BEAST_DEFINE_IS_CALL_POSSIBLE (has_async_read_some, async_read_some)
BEAST_DEFINE_IS_CALL_POSSIBLE (has_async_write_some, async_write_some)
BEAST_DEFINE_IS_CALL_POSSIBLE (has_set_verify_mode, set_verify_mode)
BEAST_DEFINE_IS_CALL_POSSIBLE (has_handshake, handshake)
BEAST_DEFINE_IS_CALL_POSSIBLE (has_async_handshake, async_handshake)
BEAST_DEFINE_IS_CALL_POSSIBLE (has_async_shutdown, async_shutdown)
bool native_handle (char const *type_name, void *dest) override
bool native_handle (char const *type_name, void *dest, std::true_type)
bool native_handle (char const *, void *, std::false_type)
boost::asio::io_service & get_io_service () override
boost::asio::io_service & get_io_service (std::true_type)
boost::asio::io_service & get_io_service (std::false_type)
void * lowest_layer_ptr (char const *type_name) const override
void * lowest_layer_ptr (char const *type_name, std::true_type) const
void * lowest_layer_ptr (char const *, std::false_type) const
error_code cancel (error_code &ec) override
error_code cancel (error_code &ec, std::true_type)
error_code cancel (error_code &ec, std::false_type)
error_code shutdown (shutdown_type what, error_code &ec) override
error_code shutdown (shutdown_type what, error_code &ec, std::true_type)
error_code shutdown (shutdown_type, error_code &ec, std::false_type)
error_code close (error_code &ec) override
error_code close (error_code &ec, std::true_type)
error_code close (error_code &ec, std::false_type)
error_code accept (abstract_socket &peer, error_code &ec) override
error_code accept (abstract_socket &peer, error_code &ec, std::true_type)
error_code accept (abstract_socket &, error_code &ec, std::false_type)
void async_accept (abstract_socket &peer, error_handler handler) override
void async_accept (abstract_socket &peer, error_handler const &handler, std::true_type)
void async_accept (abstract_socket &, error_handler const &handler, std::false_type)
std::size_t read_some (mutable_buffers buffers, error_code &ec) override
std::size_t read_some (mutable_buffers const &buffers, error_code &ec, std::true_type)
std::size_t read_some (mutable_buffers const &, error_code &ec, std::false_type)
std::size_t write_some (const_buffers buffers, error_code &ec) override
std::size_t write_some (const_buffers const &buffers, error_code &ec, std::true_type)
std::size_t write_some (const_buffers const &, error_code &ec, std::false_type)
void async_read_some (mutable_buffers buffers, transfer_handler handler) override
void async_read_some (mutable_buffers const &buffers, transfer_handler const &handler, std::true_type)
void async_read_some (mutable_buffers const &, transfer_handler const &handler, std::false_type)
void async_write_some (const_buffers buffers, transfer_handler handler) override
void async_write_some (const_buffers const &buffers, transfer_handler const &handler, std::true_type)
void async_write_some (const_buffers const &, transfer_handler const &handler, std::false_type)
void * next_layer_ptr (char const *type_name) const override
void * next_layer_ptr (char const *type_name, std::true_type) const
void * next_layer_ptr (char const *, std::false_type) const
bool needs_handshake () override
void set_verify_mode (int verify_mode) override
void set_verify_mode (int verify_mode, std::true_type)
void set_verify_mode (int, std::false_type)
error_code handshake (handshake_type type, error_code &ec) override
error_code handshake (handshake_type type, error_code &ec, std::true_type)
error_code handshake (handshake_type, error_code &ec, std::false_type)
void async_handshake (handshake_type type, error_handler handler) override
void async_handshake (handshake_type type, error_handler const &handler, std::true_type)
void async_handshake (handshake_type, error_handler const &handler, std::false_type)
error_code handshake (handshake_type type, const_buffers buffers, error_code &ec) override
error_code handshake (handshake_type type, const_buffers const &buffers, error_code &ec, std::true_type)
error_code handshake (handshake_type, const_buffers const &, error_code &ec, std::false_type)
void async_handshake (handshake_type type, const_buffers buffers, transfer_handler handler) override
void async_handshake (handshake_type type, const_buffers const &buffers, transfer_handler const &handler, std::true_type)
void async_handshake (handshake_type, const_buffers const &, transfer_handler const &handler, std::false_type)
error_code shutdown (error_code &ec) override
error_code shutdown (error_code &ec, std::true_type)
error_code shutdown (error_code &ec, std::false_type)
void async_shutdown (error_handler handler) override
void async_shutdown (error_handler const &handler, std::true_type)
void async_shutdown (error_handler const &handler, std::false_type)
Private Attributes
Object m_object
Additional Inherited Members
Protected Types inherited from beast::asio::abstract_socket
typedef boost::system::error_code error_code
typedef asio::shared_handler
< void(void)> post_handler
typedef asio::shared_handler
< void(error_code)> error_handler
typedef asio::shared_handler
< void(error_code, std::size_t)> transfer_handler
Static Protected Member Functions inherited from beast::asio::abstract_socket
static void pure_virtual_called ()
static error_code pure_virtual_error ()
static error_code pure_virtual_error (error_code &ec)
static void throw_if (error_code const &ec)
Detailed Description
template<typename Object>
class beast::asio::socket_wrapper< Object >
Wraps a reference to any object and exports all availble interfaces.
If the object does not support an interface, calling those member functions will behave as if a pure virtual was called.
Note that only a reference to the underlying is stored. Management of the lifetime of the object is controlled by the caller.
Examples of the type of Object:
asio::ip::tcp::socket asio::ip::tcp::socket& asio::ssl::stream <asio::ip::tcp::socket> asio::ssl::stream <asio::ip::tcp::socket&> explain arg must be an io_context explain socket_wrapper will create and take ownership of the tcp::socket explain this_layer_type will be tcp::socket explain next_layer () returns a asio::ip::tcp::socket& explain lowest_layer () returns a asio::ip::tcp::socket&
asio::ssl::stream <asio::buffered_stream <asio::ip::tcp::socket> > > This makes my head explode
Definition at line 55 of file socket_wrapper.h.
Member Typedef Documentation
template<typename Object> typedef extract_lowest_layer_type<this_layer_type>::type beast::asio::socket_wrapper< Object >::lowest_layer_type private
Definition at line 291 of file socket_wrapper.h.
template<typename Object> typedef extract_native_handle_type< this_layer_type>::type beast::asio::socket_wrapper< Object >::native_handle_type private
Definition at line 190 of file socket_wrapper.h.
template<typename Object> typedef extract_next_layer_type<this_layer_type>::type beast::asio::socket_wrapper< Object >::next_layer_type private
Definition at line 621 of file socket_wrapper.h.
template<typename Object> typedef boost::remove_reference<Object>::type beast::asio::socket_wrapper< Object >::this_layer_type
The type of the object being wrapped.
Definition at line 77 of file socket_wrapper.h.
Constructor & Destructor Documentation
template<typename Object> template<class... Args> beast::asio::socket_wrapper< Object >::socket_wrapper (Args &&... args) inline explicit
Definition at line 62 of file socket_wrapper.h.
         : m_object (std::forward <Args> (args)...)
     {
     }
template<typename Object> beast::asio::socket_wrapper< Object >::socket_wrapper (socket_wrapper< Object > const &) delete
Member Function Documentation
template<typename Object> error_code beast::asio::socket_wrapper< Object >::accept (abstract_socket & peer, error_code & ec) inline override private virtual
Reimplemented from beast::asio::abstract_socket.
Definition at line 434 of file socket_wrapper.h.
Referenced by beast::asio::socket_wrapper< acceptor_type & >::accept().
     {
         typedef typename native_socket <this_layer_type>::socket_type socket_type;
         return accept (peer, ec,
             Enabled <has_accept <this_layer_type,
                 error_code (socket_type&, error_code&)> > ());
     }
template<typename Object> error_code beast::asio::socket_wrapper< Object >::accept (abstract_socket & peer, error_code & ec, std::true_type) inline private
Definition at line 442 of file socket_wrapper.h.
     {
         return m_object.accept (
             native_socket <this_layer_type> (peer).get (), ec);
     }
template<typename Object> error_code beast::asio::socket_wrapper< Object >::accept (abstract_socket & , error_code & ec, std::false_type) inline private
Definition at line 449 of file socket_wrapper.h.
     {
         return pure_virtual_error (ec);
     }
template<typename Object> void beast::asio::socket_wrapper< Object >::async_accept (abstract_socket & peer, error_handler handler) inline override private virtual
Reimplemented from beast::asio::abstract_socket.
Definition at line 457 of file socket_wrapper.h.
Referenced by beast::asio::socket_wrapper< acceptor_type & >::async_accept().
     {
         typedef typename native_socket <this_layer_type>::socket_type socket_type;
         async_accept (peer, handler,
             Enabled <has_async_accept <this_layer_type,
                 void (socket_type&, error_handler)> > ());
     }
template<typename Object> void beast::asio::socket_wrapper< Object >::async_accept (abstract_socket & peer, error_handler const & handler, std::true_type) inline private
Definition at line 465 of file socket_wrapper.h.
     {
         m_object.async_accept (
             native_socket <this_layer_type> (peer).get (), handler);
     }
template<typename Object> void beast::asio::socket_wrapper< Object >::async_accept (abstract_socket & , error_handler const & handler, std::false_type) inline private
Definition at line 472 of file socket_wrapper.h.
     {
         get_io_service ().post (bind_handler (
             handler, pure_virtual_error()));
     }
template<typename Object> void beast::asio::socket_wrapper< Object >::async_handshake (handshake_type type, error_handler handler) inline override private virtual
Reimplemented from beast::asio::abstract_socket.
Definition at line 706 of file socket_wrapper.h.
Referenced by beast::asio::socket_wrapper< acceptor_type & >::async_handshake().
     {
         async_handshake (type, handler,
             Enabled <has_async_handshake <this_layer_type,
                 void (handshake_type, error_handler)> > ());
     }
template<typename Object> void beast::asio::socket_wrapper< Object >::async_handshake (handshake_type type, error_handler const & handler, std::true_type) inline private
Definition at line 713 of file socket_wrapper.h.
     {
         m_object.async_handshake (type, handler);
     }
template<typename Object> void beast::asio::socket_wrapper< Object >::async_handshake (handshake_type , error_handler const & handler, std::false_type) inline private
Definition at line 719 of file socket_wrapper.h.
     {
         get_io_service ().post (bind_handler (
             handler, pure_virtual_error()));
     }
template<typename Object> void beast::asio::socket_wrapper< Object >::async_handshake (handshake_type type, const_buffers buffers, transfer_handler handler) inline override private virtual
Reimplemented from beast::asio::abstract_socket.
Definition at line 755 of file socket_wrapper.h.
     {
         async_handshake (type, buffers, handler,
             Enabled <has_async_handshake <this_layer_type,
                 void (handshake_type, const_buffers const&,
                     transfer_handler)> > ());
     }
template<typename Object> void beast::asio::socket_wrapper< Object >::async_handshake (handshake_type type, const_buffers const & buffers, transfer_handler const & handler, std::true_type) inline private
Definition at line 764 of file socket_wrapper.h.
     {
         m_object.async_handshake (type, buffers, handler);
     }
template<typename Object> void beast::asio::socket_wrapper< Object >::async_handshake (handshake_type , const_buffers const & , transfer_handler const & handler, std::false_type) inline private
Definition at line 771 of file socket_wrapper.h.
     {
         get_io_service ().post (bind_handler (
             handler, pure_virtual_error(), 0));
     }
template<typename Object> void beast::asio::socket_wrapper< Object >::async_read_some (mutable_buffers buffers, transfer_handler handler) inline override private virtual
Reimplemented from beast::asio::abstract_socket.
Definition at line 534 of file socket_wrapper.h.
Referenced by beast::asio::socket_wrapper< acceptor_type & >::async_read_some().
     {
         async_read_some (buffers, handler,
             Enabled <has_async_read_some <this_layer_type,
                 void (mutable_buffers const&, transfer_handler const&)> > ());
     }
template<typename Object> void beast::asio::socket_wrapper< Object >::async_read_some (mutable_buffers const & buffers, transfer_handler const & handler, std::true_type) inline private
Definition at line 543 of file socket_wrapper.h.
     {
         m_object.async_read_some (buffers, handler);
     }
template<typename Object> void beast::asio::socket_wrapper< Object >::async_read_some (mutable_buffers const & , transfer_handler const & handler, std::false_type) inline private
Definition at line 551 of file socket_wrapper.h.
     {
         get_io_service ().post (bind_handler (
             handler, pure_virtual_error(), 0));
     }
template<typename Object> void beast::asio::socket_wrapper< Object >::async_shutdown (error_handler handler) inline override private virtual
Reimplemented from beast::asio::abstract_socket.
Definition at line 802 of file socket_wrapper.h.
Referenced by beast::asio::socket_wrapper< acceptor_type & >::async_shutdown().
     {
         async_shutdown (handler,
             Enabled <has_async_shutdown <this_layer_type,
                 void (error_handler)> > ());
     }
template<typename Object> void beast::asio::socket_wrapper< Object >::async_shutdown (error_handler const & handler, std::true_type) inline private
Definition at line 809 of file socket_wrapper.h.
     {
         m_object.async_shutdown (handler);
     }
template<typename Object> void beast::asio::socket_wrapper< Object >::async_shutdown (error_handler const & handler, std::false_type) inline private
Definition at line 815 of file socket_wrapper.h.
     {
         get_io_service ().post (bind_handler (
             handler, pure_virtual_error()));
     }
template<typename Object> void beast::asio::socket_wrapper< Object >::async_write_some (const_buffers buffers, transfer_handler handler) inline override private virtual
Reimplemented from beast::asio::abstract_socket.
Definition at line 562 of file socket_wrapper.h.
Referenced by beast::asio::socket_wrapper< acceptor_type & >::async_write_some().
     {
         async_write_some (buffers, handler,
             Enabled <has_async_write_some <this_layer_type,
                 void (const_buffers const&, transfer_handler const&)> > ());
     }
template<typename Object> void beast::asio::socket_wrapper< Object >::async_write_some (const_buffers const & buffers, transfer_handler const & handler, std::true_type) inline private
Definition at line 571 of file socket_wrapper.h.
     {
         m_object.async_write_some (buffers, handler);
     }
template<typename Object> void beast::asio::socket_wrapper< Object >::async_write_some (const_buffers const & , transfer_handler const & handler, std::false_type) inline private
Definition at line 579 of file socket_wrapper.h.
     {
         get_io_service ().post (bind_handler (
             handler, pure_virtual_error(), 0));
     }
template<typename Object> beast::asio::socket_wrapper< Object >::BEAST_DEFINE_IS_CALL_POSSIBLE (has_get_io_service , get_io_service) private
template<typename Object> beast::asio::socket_wrapper< Object >::BEAST_DEFINE_IS_CALL_POSSIBLE (has_lowest_layer , lowest_layer) private
template<typename Object> beast::asio::socket_wrapper< Object >::BEAST_DEFINE_IS_CALL_POSSIBLE (has_cancel , cancel) private
template<typename Object> beast::asio::socket_wrapper< Object >::BEAST_DEFINE_IS_CALL_POSSIBLE (has_shutdown , shutdown) private
template<typename Object> beast::asio::socket_wrapper< Object >::BEAST_DEFINE_IS_CALL_POSSIBLE (has_close , close) private
template<typename Object> beast::asio::socket_wrapper< Object >::BEAST_DEFINE_IS_CALL_POSSIBLE (has_accept , accept) private
template<typename Object> beast::asio::socket_wrapper< Object >::BEAST_DEFINE_IS_CALL_POSSIBLE (has_async_accept , async_accept) private
template<typename Object> beast::asio::socket_wrapper< Object >::BEAST_DEFINE_IS_CALL_POSSIBLE (has_read_some , read_some) private
template<typename Object> beast::asio::socket_wrapper< Object >::BEAST_DEFINE_IS_CALL_POSSIBLE (has_write_some , write_some) private
template<typename Object> beast::asio::socket_wrapper< Object >::BEAST_DEFINE_IS_CALL_POSSIBLE (has_async_read_some , async_read_some) private
template<typename Object> beast::asio::socket_wrapper< Object >::BEAST_DEFINE_IS_CALL_POSSIBLE (has_async_write_some , async_write_some) private
template<typename Object> beast::asio::socket_wrapper< Object >::BEAST_DEFINE_IS_CALL_POSSIBLE (has_set_verify_mode , set_verify_mode) private
template<typename Object> beast::asio::socket_wrapper< Object >::BEAST_DEFINE_IS_CALL_POSSIBLE (has_handshake , handshake) private
template<typename Object> beast::asio::socket_wrapper< Object >::BEAST_DEFINE_IS_CALL_POSSIBLE (has_async_handshake , async_handshake) private
template<typename Object> beast::asio::socket_wrapper< Object >::BEAST_DEFINE_IS_CALL_POSSIBLE (has_async_shutdown , async_shutdown) private
template<typename Object> error_code beast::asio::socket_wrapper< Object >::cancel (error_code & ec) inline override private virtual
Reimplemented from beast::asio::abstract_socket.
Definition at line 319 of file socket_wrapper.h.
     {
         return cancel (ec,
             Enabled <has_cancel <this_layer_type,
                 error_code (error_code&)> > ());
     }
template<typename Object> error_code beast::asio::socket_wrapper< Object >::cancel (error_code & ec, std::true_type) inline private
Definition at line 326 of file socket_wrapper.h.
     {
         return m_object.cancel (ec);
     }
template<typename Object> error_code beast::asio::socket_wrapper< Object >::cancel (error_code & ec, std::false_type) inline private
Definition at line 332 of file socket_wrapper.h.
     {
         return pure_virtual_error (ec);
     }
template<typename Object> error_code beast::asio::socket_wrapper< Object >::close (error_code & ec) inline override private virtual
Reimplemented from beast::asio::abstract_socket.
Definition at line 362 of file socket_wrapper.h.
     {
         return close (ec,
             Enabled <has_close <this_layer_type,
                 error_code (error_code&)> > ());
     }
template<typename Object> error_code beast::asio::socket_wrapper< Object >::close (error_code & ec, std::true_type) inline private
Definition at line 369 of file socket_wrapper.h.
     {
         return m_object.close (ec);
     }
template<typename Object> error_code beast::asio::socket_wrapper< Object >::close (error_code & ec, std::false_type) inline private
Definition at line 375 of file socket_wrapper.h.
     {
         return pure_virtual_error (ec);
     }
template<typename Object> boost::asio::io_service& beast::asio::socket_wrapper< Object >::get_io_service () inline override private virtual
Reimplemented from beast::asio::abstract_socket.
Definition at line 228 of file socket_wrapper.h.
Referenced by beast::asio::socket_wrapper< acceptor_type & >::async_accept(), beast::asio::socket_wrapper< acceptor_type & >::async_handshake(), beast::asio::socket_wrapper< acceptor_type & >::async_read_some(), beast::asio::socket_wrapper< acceptor_type & >::async_shutdown(), beast::asio::socket_wrapper< acceptor_type & >::async_write_some(), and beast::asio::socket_wrapper< acceptor_type & >::get_io_service().
     {
         return get_io_service (
             Enabled <has_get_io_service <this_layer_type,
                 boost::asio::io_service&()> > ());
     }
template<typename Object> boost::asio::io_service& beast::asio::socket_wrapper< Object >::get_io_service (std::true_type) inline private
Definition at line 235 of file socket_wrapper.h.
     {
         return m_object.get_io_service ();
     }
template<typename Object> boost::asio::io_service& beast::asio::socket_wrapper< Object >::get_io_service (std::false_type) inline private
Definition at line 241 of file socket_wrapper.h.
     {
         pure_virtual_called();
         return *static_cast <boost::asio::io_service*>(nullptr);
     }
template<typename Object> error_code beast::asio::socket_wrapper< Object >::handshake (handshake_type type, error_code & ec) inline override private virtual
Reimplemented from beast::asio::abstract_socket.
Definition at line 683 of file socket_wrapper.h.
Referenced by beast::asio::socket_wrapper< acceptor_type & >::handshake().
     {
         return handshake (type, ec,
             Enabled <has_handshake <this_layer_type,
                 error_code (handshake_type, error_code&)> > ());
     }
template<typename Object> error_code beast::asio::socket_wrapper< Object >::handshake (handshake_type type, error_code & ec, std::true_type) inline private
Definition at line 691 of file socket_wrapper.h.
     {
         return m_object.handshake (type, ec);
     }
template<typename Object> error_code beast::asio::socket_wrapper< Object >::handshake (handshake_type , error_code & ec, std::false_type) inline private
Definition at line 698 of file socket_wrapper.h.
     {
         return pure_virtual_error (ec);
     }
template<typename Object> error_code beast::asio::socket_wrapper< Object >::handshake (handshake_type type, const_buffers buffers, error_code & ec) inline override private virtual
Reimplemented from beast::asio::abstract_socket.
Definition at line 729 of file socket_wrapper.h.
     {
         return handshake (type, buffers, ec,
             Enabled <has_handshake <this_layer_type,
                 error_code (handshake_type, const_buffers const&, error_code&)> > ());
     }
template<typename Object> error_code beast::asio::socket_wrapper< Object >::handshake (handshake_type type, const_buffers const & buffers, error_code & ec, std::true_type) inline private
Definition at line 738 of file socket_wrapper.h.
     {
         return m_object.handshake (type, buffers, ec);
     }
template<typename Object> error_code beast::asio::socket_wrapper< Object >::handshake (handshake_type , const_buffers const & , error_code & ec, std::false_type) inline private
Definition at line 746 of file socket_wrapper.h.
     {
         return pure_virtual_error (ec);
     }
template<typename Object> void* beast::asio::socket_wrapper< Object >::lowest_layer_ptr (char const * type_name) const inline override private virtual
Reimplemented from beast::asio::abstract_socket.
Definition at line 295 of file socket_wrapper.h.
     {
         return lowest_layer_ptr (type_name,
             Enabled <has_type_lowest_layer_type <this_layer_type> > ());
     }
template<typename Object> void* beast::asio::socket_wrapper< Object >::lowest_layer_ptr (char const * type_name, std::true_type) const inline private
Definition at line 301 of file socket_wrapper.h.
     {
         char const* const name (typeid (typename this_layer_type::lowest_layer_type).name ());
         if (strcmp (name, type_name) == 0)
             return const_cast <void*> (static_cast <void const*> (&m_object.lowest_layer ()));
         return nullptr;
     }
template<typename Object> void* beast::asio::socket_wrapper< Object >::lowest_layer_ptr (char const * , std::false_type) const inline private
Definition at line 310 of file socket_wrapper.h.
     {
         pure_virtual_called();
         return nullptr;
     }
template<typename Object> bool beast::asio::socket_wrapper< Object >::native_handle (char const * type_name, void * dest) inline override private virtual
Reimplemented from beast::asio::abstract_socket.
Definition at line 194 of file socket_wrapper.h.
Referenced by beast::asio::socket_wrapper< acceptor_type & >::native_handle().
     {
         return native_handle (type_name, dest,
             Enabled <has_type_native_handle_type <this_layer_type> > ());
     }
template<typename Object> bool beast::asio::socket_wrapper< Object >::native_handle (char const * type_name, void * dest, std::true_type) inline private
Definition at line 200 of file socket_wrapper.h.
     {
         char const* const name (typeid (
             typename this_layer_type::native_handle_type).name ());
         if (strcmp (name, type_name) == 0)
         {
             native_handle_type* const p (reinterpret_cast <
                 native_handle_type*> (dest));
             *p = m_object.native_handle ();
             return true;
         }
         return false;
     }
template<typename Object> bool beast::asio::socket_wrapper< Object >::native_handle (char const * , void * , std::false_type) inline private
Definition at line 215 of file socket_wrapper.h.
     {
         pure_virtual_called();
         return false;
     }
template<typename Object> bool beast::asio::socket_wrapper< Object >::needs_handshake () inline override private virtual
Determines if the underlying stream requires a handshake.
If needs_handshake is true, it will be necessary to call handshake or async_handshake after the connection is established. Furthermore it will be necessary to call the shutdown member from the HandshakeInterface to close the connection. Do not close the underlying socket or else the closure will not be graceful. Only one side should initiate the handshaking shutdon. The other side should observe it. Which side does what is up to the user.
The default version returns false.
Reimplemented from beast::asio::abstract_socket.
Definition at line 649 of file socket_wrapper.h.
     {
         return
             has_handshake <this_layer_type,
                 error_code (handshake_type, error_code&)>::value ||
             has_async_handshake <this_layer_type,
                 void (handshake_type, error_handler)>::value;
     }
template<typename Object> void* beast::asio::socket_wrapper< Object >::next_layer_ptr (char const * type_name) const inline override private virtual
Reimplemented from beast::asio::abstract_socket.
Definition at line 625 of file socket_wrapper.h.
     {
         return next_layer_ptr (type_name,
             Enabled <has_type_next_layer_type <this_layer_type> > ());
     }
template<typename Object> void* beast::asio::socket_wrapper< Object >::next_layer_ptr (char const * type_name, std::true_type) const inline private
Definition at line 631 of file socket_wrapper.h.
     {
         char const* const name (typeid (typename this_layer_type::next_layer_type).name ());
         if (strcmp (name, type_name) == 0)
             return const_cast <void*> (static_cast <void const*> (&m_object.next_layer ()));
         return nullptr;
     }
template<typename Object> void* beast::asio::socket_wrapper< Object >::next_layer_ptr (char const * , std::false_type) const inline private
Definition at line 640 of file socket_wrapper.h.
     {
         pure_virtual_called();
         return nullptr;
     }
template<typename Object> socket_wrapper& beast::asio::socket_wrapper< Object >::operator= (socket_wrapper< Object > const &) delete
template<typename Object> std::size_t beast::asio::socket_wrapper< Object >::read_some (mutable_buffers buffers, error_code & ec) inline override private virtual
Reimplemented from beast::asio::abstract_socket.
Definition at line 486 of file socket_wrapper.h.
Referenced by beast::asio::socket_wrapper< acceptor_type & >::read_some().
     {
         return read_some (buffers, ec,
             Enabled <has_read_some <this_layer_type,
                 std::size_t (mutable_buffers const&, error_code&)> > ());
     }
template<typename Object> std::size_t beast::asio::socket_wrapper< Object >::read_some (mutable_buffers const & buffers, error_code & ec, std::true_type) inline private
Definition at line 494 of file socket_wrapper.h.
     {
         return m_object.read_some (buffers, ec);
     }
template<typename Object> std::size_t beast::asio::socket_wrapper< Object >::read_some (mutable_buffers const & , error_code & ec, std::false_type) inline private
Definition at line 500 of file socket_wrapper.h.
     {
         ec = pure_virtual_error ();
         return 0;
     }
template<typename Object> void beast::asio::socket_wrapper< Object >::set_verify_mode (int verify_mode) inline override private virtual
Reimplemented from beast::asio::abstract_socket.
Definition at line 660 of file socket_wrapper.h.
Referenced by beast::asio::socket_wrapper< acceptor_type & >::set_verify_mode().
     {
         set_verify_mode (verify_mode,
             Enabled <has_set_verify_mode <this_layer_type,
                 void (int)> > ());
     }
template<typename Object> void beast::asio::socket_wrapper< Object >::set_verify_mode (int verify_mode, std::true_type) inline private
Definition at line 668 of file socket_wrapper.h.
     {
         m_object.set_verify_mode (verify_mode);
     }
template<typename Object> void beast::asio::socket_wrapper< Object >::set_verify_mode (int , std::false_type) inline private
Definition at line 674 of file socket_wrapper.h.
     {
         pure_virtual_called();
     }
template<typename Object> error_code beast::asio::socket_wrapper< Object >::shutdown (shutdown_type what, error_code & ec) inline override private virtual
Reimplemented from beast::asio::abstract_socket.
Definition at line 340 of file socket_wrapper.h.
     {
         return shutdown (what, ec,
             Enabled <has_shutdown <this_layer_type,
                 error_code (shutdown_type, error_code&)> > ());
     }
template<typename Object> error_code beast::asio::socket_wrapper< Object >::shutdown (shutdown_type what, error_code & ec, std::true_type) inline private
Definition at line 348 of file socket_wrapper.h.
     {
         return m_object.shutdown (what, ec);
     }
template<typename Object> error_code beast::asio::socket_wrapper< Object >::shutdown (shutdown_type , error_code & ec, std::false_type) inline private
Definition at line 354 of file socket_wrapper.h.
     {
         return pure_virtual_error (ec);
     }
template<typename Object> error_code beast::asio::socket_wrapper< Object >::shutdown (error_code & ec) inline override private virtual
Reimplemented from beast::asio::abstract_socket.
Definition at line 781 of file socket_wrapper.h.
     {
         return shutdown (ec,
             Enabled <has_shutdown <this_layer_type,
                 error_code (error_code&)> > ());
     }
template<typename Object> error_code beast::asio::socket_wrapper< Object >::shutdown (error_code & ec, std::true_type) inline private
Definition at line 788 of file socket_wrapper.h.
     {
         return m_object.shutdown (ec);
     }
template<typename Object> error_code beast::asio::socket_wrapper< Object >::shutdown (error_code & ec, std::false_type) inline private
Definition at line 794 of file socket_wrapper.h.
     {
         return pure_virtual_error (ec);
     }
template<typename Object> this_layer_type& beast::asio::socket_wrapper< Object >::this_layer () inline noexcept
Get a reference to this layer.
Definition at line 80 of file socket_wrapper.h.
     {
         return m_object;
     }
template<typename Object> this_layer_type const& beast::asio::socket_wrapper< Object >::this_layer () const inline noexcept
Get a const reference to this layer.
Definition at line 86 of file socket_wrapper.h.
     {
         return m_object;
     }
template<typename Object> void* beast::asio::socket_wrapper< Object >::this_layer_ptr (char const * type_name) const inline override virtual
Reimplemented from beast::asio::abstract_socket.
Definition at line 97 of file socket_wrapper.h.
     {
         char const* const name (typeid (this_layer_type).name ());
         if (strcmp (name, type_name) == 0)
             return const_cast <void*> (static_cast <void const*> (&m_object));
         return nullptr;
     }
template<typename Object> std::size_t beast::asio::socket_wrapper< Object >::write_some (const_buffers buffers, error_code & ec) inline override private virtual
Reimplemented from beast::asio::abstract_socket.
Definition at line 510 of file socket_wrapper.h.
Referenced by beast::asio::socket_wrapper< acceptor_type & >::write_some().
     {
         return write_some (buffers, ec,
             Enabled <has_write_some <this_layer_type,
                 std::size_t (const_buffers const&, error_code&)> > ());
     }
template<typename Object> std::size_t beast::asio::socket_wrapper< Object >::write_some (const_buffers const & buffers, error_code & ec, std::true_type) inline private
Definition at line 518 of file socket_wrapper.h.
     {
         return m_object.write_some (buffers, ec);
     }
template<typename Object> std::size_t beast::asio::socket_wrapper< Object >::write_some (const_buffers const & , error_code & ec, std::false_type) inline private
Definition at line 525 of file socket_wrapper.h.
     {
         ec = pure_virtual_error ();
         return 0;
     }
Member Data Documentation
template<typename Object> Object beast::asio::socket_wrapper< Object >::m_object private
Definition at line 58 of file socket_wrapper.h.
Referenced by beast::asio::socket_wrapper< acceptor_type & >::accept(), beast::asio::socket_wrapper< acceptor_type & >::async_accept(), beast::asio::socket_wrapper< acceptor_type & >::async_handshake(), beast::asio::socket_wrapper< acceptor_type & >::async_read_some(), beast::asio::socket_wrapper< acceptor_type & >::async_shutdown(), beast::asio::socket_wrapper< acceptor_type & >::async_write_some(), beast::asio::socket_wrapper< acceptor_type & >::cancel(), beast::asio::socket_wrapper< acceptor_type & >::close(), beast::asio::socket_wrapper< acceptor_type & >::get_io_service(), beast::asio::socket_wrapper< acceptor_type & >::handshake(), beast::asio::socket_wrapper< acceptor_type & >::lowest_layer_ptr(), beast::asio::socket_wrapper< acceptor_type & >::native_handle(), beast::asio::socket_wrapper< acceptor_type & >::next_layer_ptr(), beast::asio::socket_wrapper< acceptor_type & >::read_some(), beast::asio::socket_wrapper< acceptor_type & >::set_verify_mode(), beast::asio::socket_wrapper< acceptor_type & >::shutdown(), beast::asio::socket_wrapper< acceptor_type & >::this_layer(), beast::asio::socket_wrapper< acceptor_type & >::this_layer_ptr(), and beast::asio::socket_wrapper< acceptor_type & >::write_some().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/asio/socket_wrapper.h