rippled: rocksdb::BlockBasedTableConstructor Class Reference
rocksdb::BlockBasedTableConstructor Class Reference
Public Member Functions
BlockBasedTableConstructor (const Comparator *cmp)
~BlockBasedTableConstructor ()
virtual Status FinishImpl (const Options &options, const KVMap &data)
virtual Iterator * NewIterator () const
uint64_t ApproximateOffsetOf (const Slice &key) const
virtual Status Reopen (const Options &options)
virtual TableReader * table_reader ()
Public Member Functions inherited from rocksdb::Constructor
Constructor (const Comparator *cmp)
virtual ~Constructor ()
void Add (const std::string &key, const Slice &value)
void Finish (const Options &options, std::vector< std::string > *keys, KVMap *kvmap)
virtual const KVMap & data ()
virtual DB * db () const
Private Member Functions
void Reset ()
BlockBasedTableConstructor ()
Private Attributes
uint64_t uniq_id_
unique_ptr< StringSink > sink_
unique_ptr< StringSource > source_
unique_ptr< TableReader > table_reader_
const EnvOptions soptions
Static Private Attributes
static uint64_t cur_uniq_id_ = 1
Detailed Description
Definition at line 243 of file table_test.cc.
Constructor & Destructor Documentation
rocksdb::BlockBasedTableConstructor::BlockBasedTableConstructor (const Comparator * cmp) inline explicit
Definition at line 245 of file table_test.cc.
       : Constructor(cmp) {
   }
rocksdb::BlockBasedTableConstructor::~BlockBasedTableConstructor () inline
Definition at line 249 of file table_test.cc.
References Reset().
{
     Reset();
   }
rocksdb::BlockBasedTableConstructor::BlockBasedTableConstructor () private
Member Function Documentation
uint64_t rocksdb::BlockBasedTableConstructor::ApproximateOffsetOf (const Slice & key) const inline
Definition at line 290 of file table_test.cc.
References table_reader_.
Referenced by rocksdb::Do_Compression_Test(), and rocksdb::TEST().
{
     return table_reader_->ApproximateOffsetOf(key);
   }
virtual Status rocksdb::BlockBasedTableConstructor::FinishImpl (const Options & options, const KVMap & data) inline virtual
Implements rocksdb::Constructor.
Definition at line 252 of file table_test.cc.
References rocksdb::BlockBasedTableBuilder::Add(), ASSERT_EQ, ASSERT_TRUE, rocksdb::Options::block_size, rocksdb::Options::block_size_deviation, rocksdb::Options::compression, cur_uniq_id_, rocksdb::Status::ok(), Reset(), sink_, soptions, source_, rocksdb::Options::table_factory, table_reader_, rocksdb::Status::ToString(), and uniq_id_.
{
     Reset();
     sink_.reset(new StringSink());
     std::unique_ptr<FlushBlockBySizePolicyFactory> flush_policy_factory(
         new FlushBlockBySizePolicyFactory(options.block_size,
                                           options.block_size_deviation));
     BlockBasedTableBuilder builder(
         options,
         sink_.get(),
         flush_policy_factory.get(),
         options.compression);
     for (KVMap::const_iterator it = data.begin();
          it != data.end();
          ++it) {
       builder.Add(it->first, it->second);
       ASSERT_TRUE(builder.status().ok());
     }
     Status s = builder.Finish();
     ASSERT_TRUE(s.ok()) << s.ToString();
     ASSERT_EQ(sink_->contents().size(), builder.FileSize());
     // Open the table
     uniq_id_ = cur_uniq_id_++;
     source_.reset(new StringSource(sink_->contents(), uniq_id_));
     unique_ptr<TableFactory> table_factory;
     return options.table_factory->GetTableReader(options, soptions,
                                                  std::move(source_),
                                                  sink_->contents().size(),
                                                  &table_reader_);
   }
virtual Iterator* rocksdb::BlockBasedTableConstructor::NewIterator () const inline virtual
Implements rocksdb::Constructor.
Definition at line 286 of file table_test.cc.
References table_reader_.
Referenced by rocksdb::TEST().
{
     return table_reader_->NewIterator(ReadOptions());
   }
virtual Status rocksdb::BlockBasedTableConstructor::Reopen (const Options & options) inline virtual
Definition at line 294 of file table_test.cc.
References sink_, soptions, source_, rocksdb::Options::table_factory, table_reader_, and uniq_id_.
Referenced by rocksdb::TEST().
{
     source_.reset(new StringSource(sink_->contents(), uniq_id_));
     return options.table_factory->GetTableReader(options, soptions,
                                                  std::move(source_),
                                                  sink_->contents().size(),
                                                  &table_reader_);
   }
void rocksdb::BlockBasedTableConstructor::Reset () inline private
Definition at line 307 of file table_test.cc.
References sink_, source_, table_reader_, and uniq_id_.
Referenced by FinishImpl(), and ~BlockBasedTableConstructor().
                {
     uniq_id_ = 0;
     table_reader_.reset();
     sink_.reset();
     source_.reset();
   }
virtual TableReader* rocksdb::BlockBasedTableConstructor::table_reader () inline virtual
Definition at line 302 of file table_test.cc.
References table_reader_.
Referenced by rocksdb::TEST().
{
     return table_reader_.get();
   }
Member Data Documentation
uint64_t rocksdb::BlockBasedTableConstructor::cur_uniq_id_ = 1 static private
Definition at line 321 of file table_test.cc.
Referenced by FinishImpl().
unique_ptr<StringSink> rocksdb::BlockBasedTableConstructor::sink_ private
Definition at line 315 of file table_test.cc.
Referenced by FinishImpl(), Reopen(), and Reset().
const EnvOptions rocksdb::BlockBasedTableConstructor::soptions private
Definition at line 322 of file table_test.cc.
Referenced by FinishImpl(), and Reopen().
unique_ptr<StringSource> rocksdb::BlockBasedTableConstructor::source_ private
Definition at line 316 of file table_test.cc.
Referenced by FinishImpl(), Reopen(), and Reset().
unique_ptr<TableReader> rocksdb::BlockBasedTableConstructor::table_reader_ private
Definition at line 317 of file table_test.cc.
Referenced by ApproximateOffsetOf(), FinishImpl(), NewIterator(), Reopen(), Reset(), and table_reader().
uint64_t rocksdb::BlockBasedTableConstructor::uniq_id_ private
Definition at line 314 of file table_test.cc.
Referenced by FinishImpl(), Reopen(), and Reset().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/table/table_test.cc