rippled: ripple::Log Class Reference
ripple::Log Class Reference
#include <Log.h>
Classes
class out
Public Member Functions
Log (LogSeverity s)
Log (LogSeverity s, LogPartition &partition)
~Log ()
template<class T >
std::ostream & operator<< (const T &t) const
std::ostringstream & ref () const
Static Public Member Functions
static std::string severityToString (LogSeverity)
static LogSeverity stringToSeverity (std::string const &)
Static Private Member Functions
static std::string replaceFirstSecretWithAsterisks (std::string s)
Private Attributes
std::ostringstream m_os
LogSeverity m_level
LogPartition * m_partition
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
RAII helper for writing to the LogSink.
Definition at line 26 of file Log.h.
Constructor & Destructor Documentation
ripple::Log::Log (LogSeverity s) explicit
Definition at line 24 of file Log.cpp.
     : m_level (s)
     , m_partition (nullptr)
 {
 }
ripple::Log::Log (LogSeverity s, LogPartition & partition)
Definition at line 30 of file Log.cpp.
     : m_level (s)
     , m_partition (&partition)
 {
 }
ripple::Log::~Log ()
Definition at line 36 of file Log.cpp.
References ripple::LogPartition::convertLogSeverity(), ripple::LogPartition::doLog(), ripple::LogSink::get(), m_level, m_os, m_partition, and ripple::LogPartition::write().
 {
     if (m_partition != nullptr)
     {
         if (m_partition->doLog (m_level))
             m_partition->write (
                 LogPartition::convertLogSeverity (m_level), m_os.str());
     }
     else
     {
         LogSink::get()->write (m_os.str(), m_level, "");
     }
 }
Member Function Documentation
template<class T > std::ostream& ripple::Log::operator<< (const T & t) const inline
Definition at line 34 of file Log.h.
References m_os.
     {
         return m_os << t;
     }
std::ostringstream& ripple::Log::ref () const inline
Definition at line 39 of file Log.h.
References m_os.
     {
         return m_os;
     }
std::string ripple::Log::replaceFirstSecretWithAsterisks (std::string s) static private
Definition at line 52 of file Log.cpp.
References ripple::min().
 {
     using namespace std;
     char const* secretToken = "\"secret\"";
     // Look for the first occurrence of "secret" in the string.
     //
     size_t startingPosition = s.find (secretToken);
     if (startingPosition != string::npos)
     {
         // Found it, advance past the token.
         //
         startingPosition += strlen (secretToken);
         // Replace the next 35 characters at most, without overwriting the end.
         //
         size_t endingPosition = std::min (startingPosition + 35, s.size () - 1);
         for (size_t i = startingPosition; i < endingPosition; ++i)
             s [i] = '*';
     }
     return s;
 }
std::string ripple::Log::severityToString (LogSeverity s) static
Definition at line 81 of file Log.cpp.
References ripple::lsDEBUG, ripple::lsERROR, ripple::lsFATAL, ripple::lsINFO, ripple::lsTRACE, and ripple::lsWARNING.
Referenced by ripple::RPCHandler::doLogLevel(), and ripple::LogPartition::getSeverities().
 {
     switch (s)
     {
     case lsTRACE:
         return "Trace";
     case lsDEBUG:
         return "Debug";
     case lsINFO:
         return "Info";
     case lsWARNING:
         return "Warning";
     case lsERROR:
         return "Error";
     case lsFATAL:
         return "Fatal";
     default:
         assert (false);
         return "Unknown";
     }
 }
LogSeverity ripple::Log::stringToSeverity (std::string const & s) static
Definition at line 109 of file Log.cpp.
References ripple::lsDEBUG, ripple::lsERROR, ripple::lsFATAL, ripple::lsINFO, ripple::lsINVALID, ripple::lsTRACE, and ripple::lsWARNING.
Referenced by ripple::RPCHandler::doLogLevel().
 {
     if (boost::iequals (s, "trace"))
         return lsTRACE;
     if (boost::iequals (s, "debug"))
         return lsDEBUG;
     if (boost::iequals (s, "info") || boost::iequals (s, "information"))
         return lsINFO;
     if (boost::iequals (s, "warn") || boost::iequals (s, "warning") || boost::iequals (s, "warnings"))
         return lsWARNING;
     if (boost::iequals (s, "error") || boost::iequals (s, "errors"))
         return lsERROR;
     if (boost::iequals (s, "fatal") || boost::iequals (s, "fatals"))
         return lsFATAL;
     return lsINVALID;
 }
Member Data Documentation
LogSeverity ripple::Log::m_level private
Definition at line 65 of file Log.h.
Referenced by ~Log().
std::ostringstream ripple::Log::m_os mutable private
Definition at line 64 of file Log.h.
Referenced by operator<<(), ref(), and ~Log().
LogPartition* ripple::Log::m_partition private
Definition at line 66 of file Log.h.
Referenced by ~Log().
The documentation for this class was generated from the following files:
rippled/src/ripple_basics/log/Log.h
rippled/src/ripple_basics/log/Log.cpp