rippled: ripple::RippleState Class Reference
ripple::RippleState Class Reference
#include <RippleState.h>
Public Types
typedef boost::shared_ptr
< RippleState > pointer
Public Types inherited from ripple::AccountItem
typedef boost::shared_ptr
< AccountItem > pointer
typedef const pointer & ref
Public Member Functions
RippleState ()
virtual ~RippleState ()
AccountItem::pointer makeItem (const uint160 &accountID, SerializedLedgerEntry::ref ledgerEntry)
LedgerEntryType getType ()
void setViewAccount (const uint160 &accountID)
const uint160 & getAccountID () const
const uint160 & getAccountIDPeer () const
bool getAuth () const
bool getAuthPeer () const
bool getNoRipple () const
bool getNoRipplePeer () const
const STAmount & getBalance () const
const STAmount & getLimit () const
const STAmount & getLimitPeer () const
std::uint32_t getQualityIn () const
std::uint32_t getQualityOut () const
SerializedLedgerEntry::pointer getSLE ()
const SerializedLedgerEntry & peekSLE () const
SerializedLedgerEntry & peekSLE ()
Json::Value getJson (int)
Blob getRaw () const
Public Member Functions inherited from ripple::AccountItem
AccountItem ()
AccountItem (SerializedLedgerEntry::ref ledger)
virtual ~AccountItem ()
SerializedLedgerEntry::pointer getSLE ()
const SerializedLedgerEntry & peekSLE () const
SerializedLedgerEntry & peekSLE ()
Blob getRaw () const
Private Member Functions
RippleState (SerializedLedgerEntry::ref ledgerEntry)
Private Attributes
bool mValid
bool mViewLowest
std::uint32_t mFlags
STAmount mLowLimit
STAmount mHighLimit
uint160 mLowID
uint160 mHighID
std::uint64_t mLowQualityIn
std::uint64_t mLowQualityOut
std::uint64_t mHighQualityIn
std::uint64_t mHighQualityOut
STAmount mBalance
Additional Inherited Members
Protected Attributes inherited from ripple::AccountItem
SerializedLedgerEntry::pointer mLedgerEntry
Detailed Description
Definition at line 30 of file RippleState.h.
Member Typedef Documentation
typedef boost::shared_ptr<RippleState> ripple::RippleState::pointer
Definition at line 33 of file RippleState.h.
Constructor & Destructor Documentation
ripple::RippleState::RippleState () inline
Definition at line 36 of file RippleState.h.
Referenced by makeItem().
 { }
virtual ripple::RippleState::~RippleState () inline virtual
Definition at line 38 of file RippleState.h.
 { }
ripple::RippleState::RippleState (SerializedLedgerEntry::ref ledgerEntry) explicit private
Definition at line 33 of file RippleState.cpp.
References mFlags, mHighQualityIn, mHighQualityOut, ripple::AccountItem::mLedgerEntry, mLowQualityIn, mLowQualityOut, and mValid.
                                                               : AccountItem (ledgerEntry),
     mValid (false),
     mViewLowest (true),
     mLowLimit (ledgerEntry->getFieldAmount (sfLowLimit)),
     mHighLimit (ledgerEntry->getFieldAmount (sfHighLimit)),
     mLowID (mLowLimit.getIssuer ()),
     mHighID (mHighLimit.getIssuer ()),
     mBalance (ledgerEntry->getFieldAmount (sfBalance))
 {
     mFlags          = mLedgerEntry->getFieldU32 (sfFlags);
     mLowQualityIn   = mLedgerEntry->getFieldU32 (sfLowQualityIn);
     mLowQualityOut  = mLedgerEntry->getFieldU32 (sfLowQualityOut);
     mHighQualityIn  = mLedgerEntry->getFieldU32 (sfHighQualityIn);
     mHighQualityOut = mLedgerEntry->getFieldU32 (sfHighQualityOut);
     mValid      = true;
 }
Member Function Documentation
const uint160& ripple::RippleState::getAccountID () const inline
Definition at line 49 of file RippleState.h.
References mHighID, mLowID, and mViewLowest.
     {
         return  mViewLowest ? mLowID : mHighID;
     }
const uint160& ripple::RippleState::getAccountIDPeer () const inline
Definition at line 54 of file RippleState.h.
References mHighID, mLowID, and mViewLowest.
Referenced by ripple::Pathfinder::addLink(), ripple::RPCHandler::doAccountLines(), and ripple::Pathfinder::getPathsOut().
     {
         return !mViewLowest ? mLowID : mHighID;
     }
bool ripple::RippleState::getAuth () const inline
Definition at line 60 of file RippleState.h.
References ripple::is_bit_set(), ripple::lsfHighAuth, ripple::lsfLowAuth, mFlags, and mViewLowest.
Referenced by ripple::Pathfinder::addLink(), ripple::RPCHandler::doAccountLines(), and ripple::Pathfinder::getPathsOut().
     {
         return is_bit_set (mFlags,  mViewLowest ? lsfLowAuth : lsfHighAuth);
     }
bool ripple::RippleState::getAuthPeer () const inline
Definition at line 65 of file RippleState.h.
References ripple::is_bit_set(), ripple::lsfHighAuth, ripple::lsfLowAuth, mFlags, and mViewLowest.
Referenced by ripple::RPCHandler::doAccountLines().
     {
         return is_bit_set (mFlags, !mViewLowest ? lsfLowAuth : lsfHighAuth);
     }
const STAmount& ripple::RippleState::getBalance () const inline
Definition at line 80 of file RippleState.h.
References mBalance.
Referenced by ripple::Pathfinder::addLink(), ripple::RPCHandler::doAccountCurrencies(), ripple::RPCHandler::doAccountLines(), ripple::Pathfinder::getPathsOut(), ripple::usAccountDestCurrencies(), and ripple::usAccountSourceCurrencies().
     {
         return mBalance;
     }
Json::Value ripple::RippleState::getJson (int) virtual
Implements ripple::AccountItem.
Definition at line 67 of file RippleState.cpp.
References ripple::base_uint< BITS >::GetHex(), mHighID, mLowID, and Json::objectValue.
 {
     Json::Value ret (Json::objectValue);
     ret["low_id"] = mLowID.GetHex ();
     ret["high_id"] = mHighID.GetHex ();
     return ret;
 }
const STAmount& ripple::RippleState::getLimit () const inline
Definition at line 85 of file RippleState.h.
References mHighLimit, mLowLimit, and mViewLowest.
Referenced by ripple::Pathfinder::addLink(), ripple::RPCHandler::doAccountLines(), and ripple::Pathfinder::getPathsOut().
     {
         return  mViewLowest ? mLowLimit : mHighLimit;
     }
const STAmount& ripple::RippleState::getLimitPeer () const inline
Definition at line 90 of file RippleState.h.
References mHighLimit, mLowLimit, and mViewLowest.
Referenced by ripple::Pathfinder::addLink(), ripple::RPCHandler::doAccountCurrencies(), ripple::RPCHandler::doAccountLines(), ripple::Pathfinder::getPathsOut(), and ripple::usAccountSourceCurrencies().
     {
         return !mViewLowest ? mLowLimit : mHighLimit;
     }
bool ripple::RippleState::getNoRipple () const inline
Definition at line 70 of file RippleState.h.
References ripple::is_bit_set(), ripple::lsfHighNoRipple, ripple::lsfLowNoRipple, mFlags, and mViewLowest.
Referenced by ripple::Pathfinder::addLink(), and ripple::RPCHandler::doAccountLines().
     {
         return is_bit_set (mFlags, mViewLowest ? lsfLowNoRipple : lsfHighNoRipple);
     }
bool ripple::RippleState::getNoRipplePeer () const inline
Definition at line 75 of file RippleState.h.
References ripple::is_bit_set(), ripple::lsfHighNoRipple, ripple::lsfLowNoRipple, mFlags, and mViewLowest.
Referenced by ripple::RPCHandler::doAccountLines(), and ripple::Pathfinder::getPathsOut().
     {
         return is_bit_set (mFlags, !mViewLowest ? lsfLowNoRipple : lsfHighNoRipple);
     }
std::uint32_t ripple::RippleState::getQualityIn () const inline
Definition at line 95 of file RippleState.h.
References mHighQualityIn, mLowQualityIn, and mViewLowest.
Referenced by ripple::RPCHandler::doAccountLines().
     {
         return ((std::uint32_t) (mViewLowest ? mLowQualityIn : mHighQualityIn));
     }
std::uint32_t ripple::RippleState::getQualityOut () const inline
Definition at line 100 of file RippleState.h.
References mHighQualityOut, mLowQualityOut, and mViewLowest.
Referenced by ripple::RPCHandler::doAccountLines().
     {
         return ((std::uint32_t) (mViewLowest ? mLowQualityOut : mHighQualityOut));
     }
Blob ripple::RippleState::getRaw () const
SerializedLedgerEntry::pointer ripple::RippleState::getSLE () inline
Definition at line 105 of file RippleState.h.
References ripple::AccountItem::mLedgerEntry.
     {
         return mLedgerEntry;
     }
LedgerEntryType ripple::RippleState::getType () inline virtual
Implements ripple::AccountItem.
Definition at line 42 of file RippleState.h.
References ripple::ltRIPPLE_STATE.
     {
         return ltRIPPLE_STATE;
     }
AccountItem::pointer ripple::RippleState::makeItem (const uint160 & accountID, SerializedLedgerEntry::ref ledgerEntry) virtual
Implements ripple::AccountItem.
Definition at line 22 of file RippleState.cpp.
References ripple::ltRIPPLE_STATE, RippleState(), and setViewAccount().
 {
     if (!ledgerEntry || ledgerEntry->getType () != ltRIPPLE_STATE)
         return AccountItem::pointer ();
     RippleState* rs = new RippleState (ledgerEntry);
     rs->setViewAccount (accountID);
     return AccountItem::pointer (rs);
 }
const SerializedLedgerEntry& ripple::RippleState::peekSLE () const inline
Definition at line 110 of file RippleState.h.
References ripple::AccountItem::mLedgerEntry.
     {
         return *mLedgerEntry;
     }
SerializedLedgerEntry& ripple::RippleState::peekSLE () inline
Definition at line 115 of file RippleState.h.
References ripple::AccountItem::mLedgerEntry.
     {
         return *mLedgerEntry;
     }
void ripple::RippleState::setViewAccount (const uint160 & accountID)
Definition at line 56 of file RippleState.cpp.
References mBalance, mLowID, mViewLowest, and ripple::STAmount::negate().
Referenced by makeItem().
 {
     bool    bViewLowestNew  = mLowID == accountID;
     if (bViewLowestNew != mViewLowest)
     {
         mViewLowest = bViewLowestNew;
         mBalance.negate ();
     }
 }
Member Data Documentation
STAmount ripple::RippleState::mBalance private
Definition at line 144 of file RippleState.h.
Referenced by getBalance(), and setViewAccount().
std::uint32_t ripple::RippleState::mFlags private
Definition at line 131 of file RippleState.h.
Referenced by getAuth(), getAuthPeer(), getNoRipple(), getNoRipplePeer(), and RippleState().
uint160 ripple::RippleState::mHighID private
Definition at line 137 of file RippleState.h.
Referenced by getAccountID(), getAccountIDPeer(), and getJson().
STAmount ripple::RippleState::mHighLimit private
Definition at line 134 of file RippleState.h.
Referenced by getLimit(), and getLimitPeer().
std::uint64_t ripple::RippleState::mHighQualityIn private
Definition at line 141 of file RippleState.h.
Referenced by getQualityIn(), and RippleState().
std::uint64_t ripple::RippleState::mHighQualityOut private
Definition at line 142 of file RippleState.h.
Referenced by getQualityOut(), and RippleState().
uint160 ripple::RippleState::mLowID private
Definition at line 136 of file RippleState.h.
Referenced by getAccountID(), getAccountIDPeer(), getJson(), and setViewAccount().
STAmount ripple::RippleState::mLowLimit private
Definition at line 133 of file RippleState.h.
Referenced by getLimit(), and getLimitPeer().
std::uint64_t ripple::RippleState::mLowQualityIn private
Definition at line 139 of file RippleState.h.
Referenced by getQualityIn(), and RippleState().
std::uint64_t ripple::RippleState::mLowQualityOut private
Definition at line 140 of file RippleState.h.
Referenced by getQualityOut(), and RippleState().
bool ripple::RippleState::mValid private
Definition at line 128 of file RippleState.h.
Referenced by RippleState().
bool ripple::RippleState::mViewLowest private
Definition at line 129 of file RippleState.h.
Referenced by getAccountID(), getAccountIDPeer(), getAuth(), getAuthPeer(), getLimit(), getLimitPeer(), getNoRipple(), getNoRipplePeer(), getQualityIn(), getQualityOut(), and setViewAccount().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/paths/RippleState.h
rippled/src/ripple_app/paths/RippleState.cpp