rippled: rocksdb::BloomTest Class Reference
rocksdb::BloomTest Class Reference
Public Member Functions
BloomTest ()
~BloomTest ()
void Reset ()
void Add (const Slice &s)
void Build ()
size_t FilterSize () const
void DumpFilter ()
bool Matches (const Slice &s)
double FalsePositiveRate ()
Private Attributes
const FilterPolicy * policy_
std::string filter_
std::vector< std::string > keys_
Detailed Description
Definition at line 25 of file bloom_test.cc.
Constructor & Destructor Documentation
rocksdb::BloomTest::BloomTest () inline
Definition at line 32 of file bloom_test.cc.
 : policy_(NewBloomFilterPolicy(10)) { }
rocksdb::BloomTest::~BloomTest () inline
Definition at line 34 of file bloom_test.cc.
References policy_.
                {
     delete policy_;
   }
Member Function Documentation
void rocksdb::BloomTest::Add (const Slice & s) inline
Definition at line 43 of file bloom_test.cc.
References keys_, and rocksdb::Slice::ToString().
{
     keys_.push_back(s.ToString());
   }
void rocksdb::BloomTest::Build () inline
Definition at line 47 of file bloom_test.cc.
References rocksdb::FilterPolicy::CreateFilter(), DumpFilter(), filter_, keys_, rocksdb::kVerbose, and policy_.
Referenced by Matches().
                {
     std::vector<Slice> key_slices;
     for (size_t i = 0; i < keys_.size(); i++) {
       key_slices.push_back(Slice(keys_[i]));
     }
     filter_.clear();
     policy_->CreateFilter(&key_slices[0], key_slices.size(), &filter_);
     keys_.clear();
     if (kVerbose >= 2) DumpFilter();
   }
void rocksdb::BloomTest::DumpFilter () inline
Definition at line 62 of file bloom_test.cc.
References filter_.
Referenced by Build().
                     {
     fprintf(stderr, "F(");
     for (size_t i = 0; i+1 < filter_.size(); i++) {
       const unsigned int c = static_cast<unsigned int>(filter_[i]);
       for (int j = 0; j < 8; j++) {
         fprintf(stderr, "%c", (c & (1 <<j)) ? '1' : '.');
       }
     }
     fprintf(stderr, ")\n");
   }
double rocksdb::BloomTest::FalsePositiveRate () inline
Definition at line 80 of file bloom_test.cc.
References Matches().
{
     char buffer[sizeof(int)];
     int result = 0;
     for (int i = 0; i < 10000; i++) {
       if (Matches(Key(i + 1000000000, buffer))) {
         result++;
       }
     }
     return result / 10000.0;
   }
size_t rocksdb::BloomTest::FilterSize () const inline
Definition at line 58 of file bloom_test.cc.
References filter_.
{
     return filter_.size();
   }
bool rocksdb::BloomTest::Matches (const Slice & s) inline
Definition at line 73 of file bloom_test.cc.
References Build(), filter_, rocksdb::FilterPolicy::KeyMayMatch(), keys_, and policy_.
Referenced by FalsePositiveRate().
{
     if (!keys_.empty()) {
       Build();
     }
     return policy_->KeyMayMatch(s, filter_);
   }
void rocksdb::BloomTest::Reset () inline
Definition at line 38 of file bloom_test.cc.
References filter_, and keys_.
                {
     keys_.clear();
     filter_.clear();
   }
Member Data Documentation
std::string rocksdb::BloomTest::filter_ private
Definition at line 28 of file bloom_test.cc.
Referenced by Build(), DumpFilter(), FilterSize(), Matches(), and Reset().
std::vector<std::string> rocksdb::BloomTest::keys_ private
Definition at line 29 of file bloom_test.cc.
Referenced by Add(), Build(), Matches(), and Reset().
const FilterPolicy* rocksdb::BloomTest::policy_ private
Definition at line 27 of file bloom_test.cc.
Referenced by Build(), Matches(), and ~BloomTest().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/util/bloom_test.cc