rippled: beast::StringArrayHelpers Namespace Reference
beast::StringArrayHelpers Namespace Reference
Functions
template<typename CharType >
void addArray (Array< String > &dest, const CharType *const *strings)
template<typename Type >
void addArray (Array< String > &dest, const Type *const strings, const int numberOfStrings)
Function Documentation
template<typename CharType > void beast::StringArrayHelpers::addArray (Array< String > & dest, const CharType *const * strings)
Definition at line 51 of file StringArray.cpp.
References beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::add().
Referenced by beast::StringArray::StringArray().
     {
         if (strings != nullptr)
             while (*strings != nullptr)
                 dest.add (*strings++);
     }
template<typename Type > void beast::StringArrayHelpers::addArray (Array< String > & dest, const Type *const strings, const int numberOfStrings)
Definition at line 59 of file StringArray.cpp.
References beast::Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::add().
     {
         for (int i = 0; i < numberOfStrings; ++i)
             dest.add (strings [i]);
     }