rippled: beast::HTTPMessage Class Reference
beast::HTTPMessage Class Reference
#include <HTTPMessage.h>
Public Member Functions
HTTPMessage (HTTPVersion const &version_, StringPairArray &fields, DynamicBuffer &body)
HTTPVersion const & version () const
HTTPHeaders const & headers () const
DynamicBuffer const & body () const
String toString () const
Public Member Functions inherited from beast::SharedObject
void incReferenceCount () const noexcept
void decReferenceCount () const
int getReferenceCount () const noexcept
Private Attributes
HTTPVersion m_version
HTTPHeaders m_headers
DynamicBuffer m_body
Additional Inherited Members
Protected Member Functions inherited from beast::SharedObject
SharedObject ()
virtual ~SharedObject ()
virtual void destroy () const
void resetReferenceCount () noexcept
Detailed Description
A complete HTTP message.
This provides the information common to all HTTP messages, including the version, content body, and headers. Derived classes provide the request or response specific data.
Because a single HTTP message can be a fairly expensive object to make copies of, this is a SharedObject.
See Also
HTTPRequest, HTTPResponse
Definition at line 38 of file HTTPMessage.h.
Constructor & Destructor Documentation
beast::HTTPMessage::HTTPMessage (HTTPVersion const & version_, StringPairArray & fields, DynamicBuffer & body)
Construct the common HTTP message parts from values. Ownership of the fields and body parameters are transferred from the caller.
Definition at line 22 of file HTTPMessage.cpp.
References m_body, and beast::DynamicBuffer::swapWith().
     : m_version (version_)
     , m_headers (fields)
 {
     m_body.swapWith (body);
 }
Member Function Documentation
DynamicBuffer const & beast::HTTPMessage::body () const
Returns the content-body.
Definition at line 41 of file HTTPMessage.cpp.
References m_body.
Referenced by ripple::SiteFiles::Logic::parse().
 {
     return m_body;
 }
HTTPHeaders const & beast::HTTPMessage::headers () const
Returns the set of HTTP headers associated with this message.
Definition at line 36 of file HTTPMessage.cpp.
References m_headers.
Referenced by beast::asio::HTTPClient_test::print().
 {
     return m_headers;
 }
String beast::HTTPMessage::toString () const
Outputs all the HTTPMessage data excluding the body into a string.
Definition at line 46 of file HTTPMessage.cpp.
References m_headers, beast::newLine, beast::HTTPVersion::toString(), beast::HTTPHeaders::toString(), and version().
Referenced by beast::HTTPRequest::toString(), and beast::HTTPResponse::toString().
 {
     String s;
     s << "HTTP " << version().toString() << newLine;
     s << m_headers.toString ();
     return s;
 }
HTTPVersion const & beast::HTTPMessage::version () const
Returns the HTTP version of this message.
Definition at line 31 of file HTTPMessage.cpp.
References m_version.
Referenced by toString().
 {
     return m_version;
 }
Member Data Documentation
DynamicBuffer beast::HTTPMessage::m_body private
Definition at line 64 of file HTTPMessage.h.
Referenced by body(), and HTTPMessage().
HTTPHeaders beast::HTTPMessage::m_headers private
Definition at line 63 of file HTTPMessage.h.
Referenced by headers(), and toString().
HTTPVersion beast::HTTPMessage::m_version private
Definition at line 62 of file HTTPMessage.h.
Referenced by version().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_asio/http/HTTPMessage.h
rippled/src/beast/modules/beast_asio/http/HTTPMessage.cpp