rippled: beast::Time Class Reference
beast::Time Class Reference
#include <Time.h>
Public Member Functions
Time () noexcept
Time (std::int64_t millisecondsSinceEpoch) noexcept
Time (int year, int month, int day, int hours, int minutes, int seconds=0, int milliseconds=0, bool useLocalTime=true) noexcept
Time (const Time &other) noexcept
~Time () noexcept
Time & operator= (const Time &other) noexcept
std::int64_t toMilliseconds () const noexcept
int getYear () const noexcept
int getMonth () const noexcept
String getMonthName (bool threeLetterVersion) const
int getDayOfMonth () const noexcept
int getDayOfWeek () const noexcept
int getDayOfYear () const noexcept
String getWeekdayName (bool threeLetterVersion) const
int getHours () const noexcept
bool isAfternoon () const noexcept
int getHoursInAmPmFormat () const noexcept
int getMinutes () const noexcept
int getSeconds () const noexcept
int getMilliseconds () const noexcept
bool isDaylightSavingTime () const noexcept
String getTimeZone () const noexcept
String toString (bool includeDate, bool includeTime, bool includeSeconds=true, bool use24HourClock=false) const noexcept
String formatted (const String &format) const
Time & operator+= (RelativeTime delta)
Time & operator-= (RelativeTime delta)
bool setSystemTimeToThisTime () const
bool isNull () const noexcept
bool isNotNull () const noexcept
Static Public Member Functions
static Time getCurrentTime () noexcept
static String getWeekdayName (int dayNumber, bool threeLetterVersion)
static String getMonthName (int monthNumber, bool threeLetterVersion)
static std::int64_t currentTimeMillis () noexcept
static std::uint32_t getMillisecondCounter () noexcept
static double getMillisecondCounterHiRes () noexcept
static void waitForMillisecondCounter (std::uint32_t targetTime) noexcept
static std::uint32_t getApproximateMillisecondCounter () noexcept
static std::int64_t getHighResolutionTicks () noexcept
static std::int64_t getHighResolutionTicksPerSecond () noexcept
static double highResolutionTicksToSeconds (std::int64_t ticks) noexcept
static std::int64_t secondsToHighResolutionTicks (double seconds) noexcept
Private Attributes
std::int64_t millisSinceEpoch
Detailed Description
Holds an absolute date and time.
Internally, the time is stored at millisecond precision.
See Also
RelativeTime
Definition at line 39 of file Time.h.
Constructor & Destructor Documentation
beast::Time::Time () noexcept
Creates a Time object.
This default constructor creates a time of 1st January 1970, (which is represented internally as 0ms).
To create a time object representing the current time, use getCurrentTime().
See Also
getCurrentTime
Definition at line 121 of file Time.cpp.
Referenced by getCurrentTime().
     : millisSinceEpoch (0)
 {
 }
beast::Time::Time (std::int64_t millisecondsSinceEpoch) explicit noexcept
Creates a time based on a number of milliseconds.
The internal millisecond count is set to 0 (1st January 1970). To create a time object set to the current time, use getCurrentTime().
Parameters
millisecondsSinceEpoch the number of milliseconds since the unix 'epoch' (midnight Jan 1st 1970).
See Also
getCurrentTime, currentTimeMillis
Definition at line 131 of file Time.cpp.
     : millisSinceEpoch (ms)
 {
 }
beast::Time::Time (int year, int month, int day, int hours, int minutes, int seconds = 0, int milliseconds = 0, bool useLocalTime = true) noexcept
Creates a time from a set of date components.
The timezone is assumed to be whatever the system is using as its locale.
Parameters
year the year, in 4-digit format, e.g. 2004
month the month, in the range 0 to 11
day the day of the month, in the range 1 to 31
hours hours in 24-hour clock format, 0 to 23
minutes minutes 0 to 59
seconds seconds 0 to 59
milliseconds milliseconds 0 to 999
useLocalTime if true, encode using the current machine's local time; if false, it will always work in GMT.
Definition at line 136 of file Time.cpp.
References bassert, and toMilliseconds().
 {
     bassert (year > 100); // year must be a 4-digit version
     if (year < 1971 || year >= 2038 || ! useLocalTime)
     {
         // use extended maths for dates beyond 1970 to 2037..
         const int timeZoneAdjustment = useLocalTime ? (31536000 - (int) (Time (1971, 0, 1, 0, 0).toMilliseconds() / 1000))
                                                     : 0;
         const int a = (13 - month) / 12;
         const int y = year + 4800 - a;
         const int jd = day + (153 * (month + 12 * a - 2) + 2) / 5
                            + (y * 365) + (y /  4) - (y / 100) + (y / 400)
                            - 32045;
         const std::int64_t s = ((std::int64_t) jd) * 86400LL - 210866803200LL;
         millisSinceEpoch = 1000 * (s + (hours * 3600 + minutes * 60 + seconds - timeZoneAdjustment))
                              + milliseconds;
     }
     else
     {
         struct tm t;
         t.tm_year   = year - 1900;
         t.tm_mon    = month;
         t.tm_mday   = day;
         t.tm_hour   = hours;
         t.tm_min    = minutes;
         t.tm_sec    = seconds;
         t.tm_isdst  = -1;
         millisSinceEpoch = 1000 * (std::int64_t) mktime (&t);
         if (millisSinceEpoch < 0)
             millisSinceEpoch = 0;
         else
             millisSinceEpoch += milliseconds;
     }
 }
beast::Time::Time (const Time & other) noexcept
Creates a copy of another Time object.
Definition at line 126 of file Time.cpp.
     : millisSinceEpoch (other.millisSinceEpoch)
 {
 }
beast::Time::~Time () noexcept
Destructor.
Definition at line 183 of file Time.cpp.
 {
 }
Member Function Documentation
std::int64_t beast::Time::currentTimeMillis () static noexcept
Returns the current system time.
Returns the number of milliseconds since midnight jan 1st 1970.
Should be accurate to within a few millisecs, depending on platform, hardware, etc.
Definition at line 194 of file Time.cpp.
Referenced by getCurrentTime(), and beast::Random::setSeedRandomly().
 {
   #if BEAST_WINDOWS
     struct _timeb t;
    #ifdef _INC_TIME_INL
     _ftime_s (&t);
    #else
     _ftime (&t);
    #endif
     return ((std::int64_t) t.time) * 1000 + t.millitm;
   #else
     struct timeval tv;
     gettimeofday (&tv, nullptr);
     return ((std::int64_t) tv.tv_sec) * 1000 + tv.tv_usec / 1000;
   #endif
 }
String beast::Time::formatted (const String & format) const
Converts this date/time to a string with a user-defined format.
This uses the C strftime() function to format this time as a string. To save you looking it up, these are the escape codes that strftime uses (other codes might work on some platforms and not others, but these are the common ones):
a is replaced by the locale's abbreviated weekday name. A is replaced by the locale's full weekday name. b is replaced by the locale's abbreviated month name. B is replaced by the locale's full month name. c is replaced by the locale's appropriate date and time representation. d is replaced by the day of the month as a decimal number [01,31]. H is replaced by the hour (24-hour clock) as a decimal number [00,23]. I is replaced by the hour (12-hour clock) as a decimal number [01,12]. j is replaced by the day of the year as a decimal number [001,366]. m is replaced by the month as a decimal number [01,12]. M is replaced by the minute as a decimal number [00,59]. p is replaced by the locale's equivalent of either a.m. or p.m. S is replaced by the second as a decimal number [00,61]. U is replaced by the week number of the year (Sunday as the first day of the week) as a decimal number [00,53]. w is replaced by the weekday as a decimal number [0,6], with 0 representing Sunday. W is replaced by the week number of the year (Monday as the first day of the week) as a decimal number [00,53]. All days in a new year preceding the first Monday are considered to be in week 0. x is replaced by the locale's appropriate date representation. X is replaced by the locale's appropriate time representation. y is replaced by the year without century as a decimal number [00,99]. Y is replaced by the year with century as a decimal number. Z is replaced by the timezone name or abbreviation, or by no bytes if no timezone information exists. %% is replaced by %.
See Also
toString
Definition at line 321 of file Time.cpp.
References beast::TimeHelpers::formatString(), and beast::TimeHelpers::millisToLocal().
 {
     struct tm t (TimeHelpers::millisToLocal (millisSinceEpoch));
     return TimeHelpers::formatString (format, &t);
 }
std::uint32_t beast::Time::getApproximateMillisecondCounter () static noexcept
Less-accurate but faster version of getMillisecondCounter().
This will return the last value that getMillisecondCounter() returned, so doesn't need to make a system call, but is less accurate - it shouldn't be more than 100ms away from the correct time, though, so is still accurate enough for a lot of purposes.
See Also
getMillisecondCounter
Definition at line 239 of file Time.cpp.
References getMillisecondCounter(), and beast::TimeHelpers::lastMSCounterValue.
 {
     if (TimeHelpers::lastMSCounterValue == 0)
         getMillisecondCounter();
     return TimeHelpers::lastMSCounterValue;
 }
Time beast::Time::getCurrentTime () static noexcept
Returns a Time object that is set to the current system time.
See Also
currentTimeMillis
Definition at line 211 of file Time.cpp.
References currentTimeMillis(), and Time().
Referenced by ripple::Validators::SourceStringsImp::fetch(), ripple::Validators::Logic::fetch(), ripple::Validators::Logic::fetch_one(), and beast::File_test::run().
 {
     return Time (currentTimeMillis());
 }
int beast::Time::getDayOfMonth () const noexcept
Returns the day of the month. The value returned is in the range 1 to 31.
Definition at line 331 of file Time.cpp.
References millisSinceEpoch, and beast::TimeHelpers::millisToLocal().
Referenced by ripple::Validators::Utilities::timeToString().
 { return TimeHelpers::millisToLocal (millisSinceEpoch).tm_mday; }
int beast::Time::getDayOfWeek () const noexcept
Returns the number of the day of the week. The value returned is in the range 0 to 6 (0 = sunday, 1 = monday, etc).
Definition at line 332 of file Time.cpp.
References millisSinceEpoch, and beast::TimeHelpers::millisToLocal().
Referenced by getWeekdayName().
 { return TimeHelpers::millisToLocal (millisSinceEpoch).tm_wday; }
int beast::Time::getDayOfYear () const noexcept
Returns the number of the day of the year. The value returned is in the range 0 to 365.
Definition at line 330 of file Time.cpp.
References millisSinceEpoch, and beast::TimeHelpers::millisToLocal().
 { return TimeHelpers::millisToLocal (millisSinceEpoch).tm_yday; }
std::int64_t beast::Time::getHighResolutionTicks () static noexcept
Returns the current high-resolution counter's tick-count.
This is a similar idea to getMillisecondCounter(), but with a higher resolution.
See Also
getHighResolutionTicksPerSecond, highResolutionTicksToSeconds, secondsToHighResolutionTicks
Definition at line 329 of file bsd_SystemStats.cpp.
Referenced by beast::ServiceQueue_timing_test::Stopwatch::getElapsed(), ripple::NodeStore::NodeStoreTiming_test::Stopwatch::getElapsed(), getMillisecondCounterHiRes(), beast::measureFunctionCallTime(), beast::Random::setSeedRandomly(), ripple::NodeStore::NodeStoreTiming_test::Stopwatch::start(), beast::ServiceQueue_timing_test::Stopwatch::start(), and ripple::timedDestroy().
 {
     timespec t;
     clock_gettime (CLOCK_MONOTONIC, &t);
     return (t.tv_sec * (std::int64_t) 1000000) + (t.tv_nsec / 1000);
 }
std::int64_t beast::Time::getHighResolutionTicksPerSecond () static noexcept
Returns the resolution of the high-resolution counter in ticks per second.
See Also
getHighResolutionTicks, highResolutionTicksToSeconds, secondsToHighResolutionTicks
Definition at line 337 of file bsd_SystemStats.cpp.
Referenced by beast::Random::setSeedRandomly().
 {
     return 1000000;  // (microseconds)
 }
int beast::Time::getHours () const noexcept
Returns the number of hours since midnight.
This is in 24-hour clock format, in the range 0 to 23.
See Also
getHoursInAmPmFormat, isAfternoon
Definition at line 333 of file Time.cpp.
References millisSinceEpoch, and beast::TimeHelpers::millisToLocal().
Referenced by getHoursInAmPmFormat(), isAfternoon(), and ripple::Validators::Utilities::timeToString().
 { return TimeHelpers::millisToLocal (millisSinceEpoch).tm_hour; }
int beast::Time::getHoursInAmPmFormat () const noexcept
Returns the hours in 12-hour clock format.
This will return a value 1 to 12 - use isAfternoon() to find out whether this is in the afternoon or morning.
See Also
getHours, isAfternoon
Definition at line 338 of file Time.cpp.
References getHours().
 {
     const int hours = getHours();
     if (hours == 0)  return 12;
     if (hours <= 12) return hours;
     return hours - 12;
 }
std::uint32_t beast::Time::getMillisecondCounter () static noexcept
Returns the number of millisecs since a fixed event (usually system startup).
This returns a monotonically increasing value which it unaffected by changes to the system clock. It should be accurate to within a few millisecs, depending on platform, hardware, etc.
Being a 32-bit return value, it will of course wrap back to 0 after 2^32 seconds of uptime, so be careful to take that into account. If you need a 64-bit time, you can use currentTimeMillis() instead.
See Also
getApproximateMillisecondCounter
Definition at line 219 of file Time.cpp.
References beast::beast_millisecondsSinceStartup(), and beast::TimeHelpers::lastMSCounterValue.
Referenced by getApproximateMillisecondCounter(), beast::Random::setSeedRandomly(), and beast::Thread::waitForThreadToExit().
 {
     const std::uint32_t now = beast_millisecondsSinceStartup();
     if (now < TimeHelpers::lastMSCounterValue)
     {
         // in multi-threaded apps this might be called concurrently, so
         // make sure that our last counter value only increases and doesn't
         // go backwards..
         if (now < TimeHelpers::lastMSCounterValue - 1000)
             TimeHelpers::lastMSCounterValue = now;
     }
     else
     {
         TimeHelpers::lastMSCounterValue = now;
     }
     return now;
 }
double beast::Time::getMillisecondCounterHiRes () static noexcept
Returns the number of millisecs since a fixed event (usually system startup).
This has the same function as getMillisecondCounter(), but returns a more accurate value, using a higher-resolution timer if one is available.
See Also
getMillisecondCounter
Definition at line 342 of file bsd_SystemStats.cpp.
References getHighResolutionTicks().
 {
     return getHighResolutionTicks() * 0.001;
 }
int beast::Time::getMilliseconds () const noexcept
Returns the number of milliseconds, 0 to 999.
Unlike toMilliseconds(), this just returns the position within the current second rather than the total number since the epoch.
See Also
toMilliseconds
Definition at line 336 of file Time.cpp.
References beast::TimeHelpers::extendedModulo(), and millisSinceEpoch.
 { return TimeHelpers::extendedModulo (millisSinceEpoch, 1000); }
int beast::Time::getMinutes () const noexcept
Returns the number of minutes, 0 to 59.
Definition at line 334 of file Time.cpp.
References millisSinceEpoch, and beast::TimeHelpers::millisToLocal().
Referenced by ripple::Validators::Utilities::timeToString().
 { return TimeHelpers::millisToLocal (millisSinceEpoch).tm_min; }
int beast::Time::getMonth () const noexcept
Returns the number of the month.
The value returned is in the range 0 to 11.
See Also
getMonthName
Definition at line 329 of file Time.cpp.
References millisSinceEpoch, and beast::TimeHelpers::millisToLocal().
Referenced by getMonthName(), and ripple::Validators::Utilities::timeToString().
 { return TimeHelpers::millisToLocal (millisSinceEpoch).tm_mon; }
String beast::Time::getMonthName (bool threeLetterVersion) const
Returns the name of the month.
Parameters
threeLetterVersion if true, it'll be a 3-letter abbreviation, e.g. "Jan"; if false it'll return the long form, e.g. "January"
See Also
getMonth
Definition at line 398 of file Time.cpp.
References getMonth().
 {
     return getMonthName (getMonth(), threeLetterVersion);
 }
String beast::Time::getMonthName (int monthNumber, bool threeLetterVersion) static
Returns the name of one of the months.
Parameters
monthNumber the month, 0 to 11
threeLetterVersion if true, it'll be a 3-letter abbreviation, e.g. "Jan"; if false it'll return the long form, e.g. "January"
Definition at line 408 of file Time.cpp.
 {
     const char* const shortMonthNames[] = { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" };
     const char* const longMonthNames[]  = { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" };
     monthNumber %= 12;
     return threeLetterVersion ? shortMonthNames [monthNumber]
                                      : longMonthNames [monthNumber];
 }
int beast::Time::getSeconds () const noexcept
Returns the number of seconds, 0 to 59.
Definition at line 335 of file Time.cpp.
References beast::TimeHelpers::extendedModulo(), and millisSinceEpoch.
Referenced by ripple::Validators::Utilities::timeToString().
 { return TimeHelpers::extendedModulo (millisSinceEpoch / 1000, 60); }
String beast::Time::getTimeZone () const noexcept
Returns a 3-character string to indicate the local timezone.
Definition at line 358 of file Time.cpp.
References beast::String::contains(), beast::String::containsIgnoreCase(), isDaylightSavingTime(), name, and beast::String::substring().
 {
     String zone[2];
   #if BEAST_WINDOWS
     _tzset();
    #ifdef _INC_TIME_INL
     for (int i = 0; i < 2; ++i)
     {
         char name[128] = { 0 };
         size_t length;
         _get_tzname (&length, name, 127, i);
         zone[i] = name;
     }
    #else
     const char** const zonePtr = (const char**) _tzname;
     zone[0] = zonePtr[0];
     zone[1] = zonePtr[1];
    #endif
   #else
     tzset();
     const char** const zonePtr = (const char**) tzname;
     zone[0] = zonePtr[0];
     zone[1] = zonePtr[1];
   #endif
     if (isDaylightSavingTime())
     {
         zone[0] = zone[1];
         if (zone[0].length() > 3
              && zone[0].containsIgnoreCase ("daylight")
              && zone[0].contains ("GMT"))
             zone[0] = "BST";
     }
     return zone[0].substring (0, 3);
 }
String beast::Time::getWeekdayName (bool threeLetterVersion) const
Returns the name of the weekday.
Parameters
threeLetterVersion if true, it'll return a 3-letter abbreviation, e.g. "Tue"; if false, it'll return the full version, e.g. "Tuesday".
Definition at line 403 of file Time.cpp.
References getDayOfWeek().
 {
     return getWeekdayName (getDayOfWeek(), threeLetterVersion);
 }
String beast::Time::getWeekdayName (int dayNumber, bool threeLetterVersion) static
Returns the name of a day of the week.
Parameters
dayNumber the day, 0 to 6 (0 = sunday, 1 = monday, etc)
threeLetterVersion if true, it'll return a 3-letter abbreviation, e.g. "Tue"; if false, it'll return the full version, e.g. "Tuesday".
Definition at line 419 of file Time.cpp.
 {
     const char* const shortDayNames[] = { "Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat" };
     const char* const longDayNames[]  = { "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday" };
     day %= 7;
     return threeLetterVersion ? shortDayNames [day]
                                      : longDayNames [day];
 }
int beast::Time::getYear () const noexcept
Returns the year.
A 4-digit format is used, e.g. 2004.
Definition at line 328 of file Time.cpp.
References millisSinceEpoch, and beast::TimeHelpers::millisToLocal().
Referenced by ripple::Validators::Utilities::timeToString().
 { return TimeHelpers::millisToLocal (millisSinceEpoch).tm_year + 1900; }
double beast::Time::highResolutionTicksToSeconds (std::int64_t ticks) static noexcept
Converts a number of high-resolution ticks into seconds.
See Also
getHighResolutionTicks, getHighResolutionTicksPerSecond, secondsToHighResolutionTicks
Definition at line 273 of file Time.cpp.
Referenced by beast::ServiceQueue_timing_test::Stopwatch::getElapsed(), ripple::NodeStore::NodeStoreTiming_test::Stopwatch::getElapsed(), beast::measureFunctionCallTime(), and ripple::timedDestroy().
 {
     return ticks / (double) getHighResolutionTicksPerSecond();
 }
bool beast::Time::isAfternoon () const noexcept
Returns true if the time is in the afternoon.
So it returns true for "PM", false for "AM".
See Also
getHoursInAmPmFormat, getHours
Definition at line 348 of file Time.cpp.
References getHours().
 {
     return getHours() >= 12;
 }
bool beast::Time::isDaylightSavingTime () const noexcept
Returns true if the local timezone uses a daylight saving correction.
Definition at line 353 of file Time.cpp.
References millisSinceEpoch, and beast::TimeHelpers::millisToLocal().
Referenced by getTimeZone().
 {
     return TimeHelpers::millisToLocal (millisSinceEpoch).tm_isdst != 0;
 }
bool beast::Time::isNotNull () const inline noexcept
Definition at line 113 of file Time.h.
References millisSinceEpoch.
Referenced by ripple::Validators::Logic::fetch_one(), and ripple::Validators::Utilities::timeToString().
     {
         return millisSinceEpoch != 0;
     }
bool beast::Time::isNull () const inline noexcept
Returns true if this object represents "no time", or NULL. Internally we check for milliseconds since Epoch equal to zero.
Definition at line 108 of file Time.h.
References millisSinceEpoch.
     {
         return millisSinceEpoch == 0;
     }
Time & beast::Time::operator+= (RelativeTime delta)
Adds a RelativeTime to this time.
Definition at line 431 of file Time.cpp.
References beast::RelativeTime::inMilliseconds(), and millisSinceEpoch.
 { millisSinceEpoch += delta.inMilliseconds(); return *this; }
Time & beast::Time::operator-= (RelativeTime delta)
Subtracts a RelativeTime from this time.
Definition at line 432 of file Time.cpp.
References beast::RelativeTime::inMilliseconds(), and millisSinceEpoch.
 { millisSinceEpoch -= delta.inMilliseconds(); return *this; }
Time & beast::Time::operator= (const Time & other) noexcept
Copies this time from another one.
Definition at line 187 of file Time.cpp.
References millisSinceEpoch.
 {
     millisSinceEpoch = other.millisSinceEpoch;
     return *this;
 }
std::int64_t beast::Time::secondsToHighResolutionTicks (double seconds) static noexcept
Converts a number seconds into high-resolution ticks.
See Also
getHighResolutionTicks, getHighResolutionTicksPerSecond, highResolutionTicksToSeconds
Definition at line 278 of file Time.cpp.
 {
     return (std::int64_t) (seconds * (double) getHighResolutionTicksPerSecond());
 }
bool beast::Time::setSystemTimeToThisTime () const
Tries to set the computer's clock.
Returns
true if this succeeds, although depending on the system, the application might not have sufficient privileges to do this.
Definition at line 347 of file bsd_SystemStats.cpp.
References millisSinceEpoch.
 {
     timeval t;
     t.tv_sec = millisSinceEpoch / 1000;
     t.tv_usec = (millisSinceEpoch - t.tv_sec * 1000) * 1000;
     return settimeofday (&t, 0) == 0;
 }
std::int64_t beast::Time::toMilliseconds () const inline noexcept
Returns the time as a number of milliseconds.
Returns
the number of milliseconds this Time object represents, since midnight jan 1st 1970.
See Also
getMilliseconds
Definition at line 125 of file Time.h.
References millisSinceEpoch.
Referenced by beast::FileInputSource::hashCode(), beast::TimeHelpers::millisToLocal(), beast::operator!=(), beast::operator-(), beast::operator<(), beast::operator<=(), beast::operator==(), beast::operator>(), beast::operator>=(), beast::File_test::run(), beast::File::setCreationTime(), beast::File::setLastAccessTime(), beast::File::setLastModificationTime(), Time(), and beast::sqdb::type_conversion< Time >::to_base().
 { return millisSinceEpoch; }
String beast::Time::toString (bool includeDate, bool includeTime, bool includeSeconds = true, bool use24HourClock = false) const noexcept
Quick way of getting a string version of a date and time.
For a more powerful way of formatting the date and time, see the formatted() method.
Parameters
includeDate whether to include the date in the string
includeTime whether to include the time in the string
includeSeconds if the time is being included, this provides an option not to include the seconds in it
use24HourClock if the time is being included, sets whether to use am/pm or 24 hour notation.
See Also
formatted
Definition at line 284 of file Time.cpp.
References beast::String::trimEnd().
 {
     String result;
     if (includeDate)
     {
         result << getDayOfMonth() << ' '
                << getMonthName (true) << ' '
                << getYear();
         if (includeTime)
             result << ' ';
     }
     if (includeTime)
     {
         const int mins = getMinutes();
         result << (use24HourClock ? getHours() : getHoursInAmPmFormat())
                << (mins < 10 ? ":0" : ":") << mins;
         if (includeSeconds)
         {
             const int secs = getSeconds();
             result << (secs < 10 ? ":0" : ":") << secs;
         }
         if (! use24HourClock)
             result << (isAfternoon() ? "pm" : "am");
     }
     return result.trimEnd();
 }
void beast::Time::waitForMillisecondCounter (std::uint32_t targetTime) static noexcept
Waits until the getMillisecondCounter() reaches a given value.
This will make the thread sleep as efficiently as it can while it's waiting.
Definition at line 247 of file Time.cpp.
References beast::bmin(), beast::Thread::sleep(), and beast::Thread::yield().
 {
     for (;;)
     {
         const std::uint32_t now = getMillisecondCounter();
         if (now >= targetTime)
             break;
         const int toWait = (int) (targetTime - now);
         if (toWait > 2)
         {
             Thread::sleep (bmin (20, toWait >> 1));
         }
         else
         {
             // xxx should consider using mutex_pause on the mac as it apparently
             // makes it seem less like a spinlock and avoids lowering the thread pri.
             for (int i = 10; --i >= 0;)
                 Thread::yield();
         }
     }
 }
Member Data Documentation
std::int64_t beast::Time::millisSinceEpoch private
Definition at line 389 of file Time.h.
Referenced by getDayOfMonth(), getDayOfWeek(), getDayOfYear(), getHours(), getMilliseconds(), getMinutes(), getMonth(), getSeconds(), getYear(), isDaylightSavingTime(), isNotNull(), isNull(), operator+=(), operator-=(), operator=(), setSystemTimeToThisTime(), and toMilliseconds().
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_core/time/Time.h
rippled/src/beast/modules/beast_core/native/bsd_SystemStats.cpp
rippled/src/beast/modules/beast_core/native/linux_SystemStats.cpp
rippled/src/beast/modules/beast_core/native/mac_SystemStats.mm
rippled/src/beast/modules/beast_core/native/win32_SystemStats.cpp
rippled/src/beast/modules/beast_core/time/Time.cpp