rippled: ripple::PathRequest Class Reference
ripple::PathRequest Class Reference
#include <PathRequest.h>
Public Types
typedef boost::weak_ptr
< PathRequest > wptr
typedef boost::shared_ptr
< PathRequest > pointer
typedef const pointer & ref
typedef const wptr & wref
typedef std::pair< uint160,
uint160 > currIssuer_t
Public Member Functions
PathRequest (boost::shared_ptr< InfoSub > const &subscriber, int id, PathRequests &, beast::Journal journal)
~PathRequest ()
bool isValid (RippleLineCache::ref crCache)
bool isValid ()
bool isNew ()
bool needsUpdate (bool newOnly, LedgerIndex index)
Json::Value getStatus ()
Json::Value doCreate (const boost::shared_ptr< Ledger > &, const RippleLineCache::pointer &, const Json::Value &, bool &)
Json::Value doClose (const Json::Value &)
Json::Value doStatus (const Json::Value &)
Json::Value doUpdate (const boost::shared_ptr< RippleLineCache > &, bool fast)
InfoSub::pointer getSubscriber ()
Public Member Functions inherited from ripple::CountedObject< PathRequest >
CountedObject ()
CountedObject (CountedObject const &)
~CountedObject ()
Static Public Member Functions
static char const * getCountedObjectName ()
Private Types
typedef RippleRecursiveMutex LockType
typedef std::lock_guard< LockType > ScopedLockType
Private Member Functions
void setValid ()
void resetLevel (int level)
int parseJson (const Json::Value &, bool complete)
Private Attributes
beast::Journal m_journal
LockType mLock
PathRequests & mOwner
boost::weak_ptr< InfoSub > wpSubscriber
Json::Value jvId
Json::Value jvStatus
RippleAddress raSrcAccount
RippleAddress raDstAccount
STAmount saDstAmount
std::set< currIssuer_t > sciSourceCurrencies
std::map< currIssuer_t, STPathSet > mContext
bool bValid
std::atomic< LedgerIndex > iLastIndex
int iLastLevel
bool bLastSuccess
int iIdentifier
boost::posix_time::ptime ptCreated
boost::posix_time::ptime ptQuickReply
boost::posix_time::ptime ptFullReply
Detailed Description
Definition at line 36 of file PathRequest.h.
Member Typedef Documentation
typedef std::pair<uint160, uint160> ripple::PathRequest::currIssuer_t
Definition at line 47 of file PathRequest.h.
typedef RippleRecursiveMutex ripple::PathRequest::LockType private
Definition at line 76 of file PathRequest.h.
typedef boost::shared_ptr<PathRequest> ripple::PathRequest::pointer
Definition at line 44 of file PathRequest.h.
typedef const pointer& ripple::PathRequest::ref
Definition at line 45 of file PathRequest.h.
typedef std::lock_guard<LockType> ripple::PathRequest::ScopedLockType private
Definition at line 77 of file PathRequest.h.
typedef boost::weak_ptr<PathRequest> ripple::PathRequest::wptr
Definition at line 43 of file PathRequest.h.
typedef const wptr& ripple::PathRequest::wref
Definition at line 46 of file PathRequest.h.
Constructor & Destructor Documentation
ripple::PathRequest::PathRequest (boost::shared_ptr< InfoSub > const & subscriber, int id, PathRequests & owner, beast::Journal journal)
Definition at line 24 of file PathRequest.cpp.
     : m_journal (journal)
     , mOwner (owner)
     , wpSubscriber (subscriber)
     , jvStatus (Json::objectValue)
     , bValid (false)
     , iLastIndex (0)
     , iLastLevel (0)
     , bLastSuccess (false)
     , iIdentifier (id)
 {
     if (m_journal.debug)
         m_journal.debug << iIdentifier << " created";
     ptCreated = boost::posix_time::microsec_clock::universal_time ();
 }
ripple::PathRequest::~PathRequest ()
Definition at line 52 of file PathRequest.cpp.
References ripple::get_milli_diff(), iIdentifier, beast::Journal::info, m_journal, ptCreated, ptFullReply, and ptQuickReply.
 {
     std::string fast, full;
     if (!ptQuickReply.is_not_a_date_time())
     {
         fast = " fast:";
         fast += get_milli_diff (ptQuickReply, ptCreated);
         fast += "ms";
     }
     if (!ptFullReply.is_not_a_date_time())
     {
         full = " full:";
         full += get_milli_diff (ptFullReply, ptCreated);
         full += "ms";
     }
     if (m_journal.info)
         m_journal.info << iIdentifier << " complete:" << fast << full <<
         " total:" << get_milli_diff(ptCreated) << "ms";
 }
Member Function Documentation
Json::Value ripple::PathRequest::doClose (const Json::Value &)
Definition at line 304 of file PathRequest.cpp.
References beast::Journal::debug, iIdentifier, jvStatus, m_journal, and mLock.
 {
     m_journal.debug << iIdentifier << " closed";
     ScopedLockType sl (mLock);
     return jvStatus;
 }
Json::Value ripple::PathRequest::doCreate (const boost::shared_ptr< Ledger > & , const RippleLineCache::pointer & , const Json::Value & , bool &)
Definition at line 176 of file PathRequest.cpp.
References bValid, beast::Journal::debug, doUpdate(), ripple::STAmount::getFullText(), ripple::RippleAddress::humanAccountID(), iIdentifier, isValid(), jvStatus, m_journal, parseJson(), PFR_PJ_INVALID, raSrcAccount, and saDstAmount.
 {
     Json::Value status;
     if (parseJson (value, true) != PFR_PJ_INVALID)
     {
         bValid = isValid (cache);
         if (bValid)
             status = doUpdate (cache, true);
         else
             status = jvStatus;
     }
     else
     {
         bValid = false;
         status = jvStatus;
     }
     if (m_journal.debug)
     {
         if (bValid)
         {
             m_journal.debug << iIdentifier << " valid: " << raSrcAccount.humanAccountID ();
             m_journal.debug << iIdentifier << " Deliver: " << saDstAmount.getFullText ();
         }
         else
             m_journal.debug << iIdentifier << " invalid";
     }
     valid = bValid;
     return status;
 }
Json::Value ripple::PathRequest::doStatus (const Json::Value &)
Definition at line 311 of file PathRequest.cpp.
References jvStatus, and mLock.
 {
     ScopedLockType sl (mLock);
     return jvStatus;
 }
Json::Value ripple::PathRequest::doUpdate (const boost::shared_ptr< RippleLineCache > & , bool fast)
Definition at line 323 of file PathRequest.cpp.
References ACCOUNT_XRP, ripple::STPathSet::addPath(), Json::Value::append(), Json::arrayValue, bLastSuccess, CondLog, beast::Journal::debug, ripple::Pathfinder::findPaths(), ripple::RippleAddress::getAccountID(), ripple::getApp(), ripple::getConfig(), ripple::STAmount::getCurrency(), ripple::Application::getFeeTrack(), ripple::STAmount::getFullText(), ripple::STAmount::getJson(), ripple::STPathSet::getJson(), ripple::RippleAddress::humanAccountID(), iIdentifier, iLastLevel, ripple::LoadFeeTrack::isLoadedLocal(), Json::Value::isNull(), isValid(), ripple::base_uint< BITS >::isZero(), jvId, jvStatus, ripple::lsDEBUG, m_journal, mContext, mLock, mOwner, ripple::STAmount::negate(), Json::objectValue, ripple::Config::PATH_SEARCH, ripple::Config::PATH_SEARCH_FAST, ptCreated, ptFullReply, ptQuickReply, raDstAccount, raSrcAccount, ripple::PathRequests::reportFast(), ripple::PathRequests::reportFull(), ripple::RippleCalc::rippleCalc(), saDstAmount, sciSourceCurrencies, ripple::STPath::size(), ripple::tapNONE, ripple::tecPATH_PARTIAL, ripple::terNO_LINE, ripple::tesSUCCESS, test, ripple::transHuman(), and ripple::usAccountSourceCurrencies().
Referenced by doCreate().
 {
     m_journal.debug << iIdentifier << " update " << (fast ? "fast" : "normal");
     ScopedLockType sl (mLock);
     if (!isValid (cache))
         return jvStatus;
     jvStatus = Json::objectValue;
     std::set<currIssuer_t> sourceCurrencies (sciSourceCurrencies);
     if (sourceCurrencies.empty ())
     {
         boost::unordered_set<uint160> usCurrencies =
             usAccountSourceCurrencies (raSrcAccount, cache, true);
         bool sameAccount = raSrcAccount == raDstAccount;
         BOOST_FOREACH (const uint160 & c, usCurrencies)
         {
             if (!sameAccount || (c != saDstAmount.getCurrency ()))
             {
                 if (c.isZero ())
                     sourceCurrencies.insert (std::make_pair (c, ACCOUNT_XRP));
                 else
                     sourceCurrencies.insert (std::make_pair (c, raSrcAccount.getAccountID ()));
             }
         }
     }
     jvStatus["source_account"] = raSrcAccount.humanAccountID ();
     jvStatus["destination_account"] = raDstAccount.humanAccountID ();
     jvStatus["destination_amount"] = saDstAmount.getJson (0);
     if (!jvId.isNull ())
         jvStatus["id"] = jvId;
     Json::Value jvArray = Json::arrayValue;
     int iLevel = iLastLevel;
     bool loaded = getApp().getFeeTrack().isLoadedLocal();
     if (iLevel == 0)
     { // first pass
         if (loaded || fast)
             iLevel = getConfig().PATH_SEARCH_FAST;
         else
             iLevel = getConfig().PATH_SEARCH;
     }
     else if ((iLevel == getConfig().PATH_SEARCH_FAST) && !fast)
     { // leaving fast pathfinding
         iLevel = getConfig().PATH_SEARCH;
         if (loaded && (iLevel > getConfig().PATH_SEARCH_FAST))
             --iLevel;
     }
     else if (bLastSuccess)
     { // decrement, if possible
         if ((iLevel > getConfig().PATH_SEARCH) || (loaded && (iLevel > getConfig().PATH_SEARCH_FAST)))
             --iLevel;
     }
     else
     { // adjust as needed
         if (!loaded && (iLevel < getConfig().PATH_SEARCH_MAX))
             ++iLevel;
         if (loaded && (iLevel > getConfig().PATH_SEARCH_FAST))
             --iLevel;
     }
     m_journal.debug << iIdentifier << " processing at level " << iLevel;
     bool found = false;
     BOOST_FOREACH (const currIssuer_t & currIssuer, sourceCurrencies)
     {
         {
             STAmount test (currIssuer.first, currIssuer.second, 1);
             if (m_journal.debug)
                 m_journal.debug << iIdentifier << " Trying to find paths: " << test.getFullText ();
         }
         bool valid;
         STPathSet& spsPaths = mContext[currIssuer];
         Pathfinder pf (cache, raSrcAccount, raDstAccount,
                        currIssuer.first, currIssuer.second, saDstAmount, valid);
         CondLog (!valid, lsDEBUG, PathRequest) << iIdentifier << " PF request not valid";
         STPath extraPath;
         if (valid && pf.findPaths (iLevel, 4, spsPaths, extraPath))
         {
             LedgerEntrySet                      lesSandbox (cache->getLedger (), tapNONE);
             std::vector<PathState::pointer>     vpsExpanded;
             STAmount                            saMaxAmountAct;
             STAmount                            saDstAmountAct;
             STAmount                            saMaxAmount (currIssuer.first,
                     currIssuer.second.isNonZero () ? currIssuer.second :
                     (currIssuer.first.isZero () ? ACCOUNT_XRP : raSrcAccount.getAccountID ()), 1);
             saMaxAmount.negate ();
             m_journal.debug << iIdentifier << " Paths found, calling rippleCalc";
             TER terResult = RippleCalc::rippleCalc (lesSandbox, saMaxAmountAct, saDstAmountAct,
                                                     vpsExpanded, saMaxAmount, saDstAmount,
                                                     raDstAccount.getAccountID (), raSrcAccount.getAccountID (),
                                                     spsPaths, false, false, false, true);
             if ((extraPath.size() > 0) && ((terResult == terNO_LINE) || (terResult == tecPATH_PARTIAL)))
             {
                 m_journal.debug << iIdentifier << " Trying with an extra path element";
                 spsPaths.addPath(extraPath);
                 vpsExpanded.clear ();
                 terResult = RippleCalc::rippleCalc (lesSandbox, saMaxAmountAct, saDstAmountAct,
                                                     vpsExpanded, saMaxAmount, saDstAmount,
                                                     raDstAccount.getAccountID (), raSrcAccount.getAccountID (),
                                                     spsPaths, false, false, false, true);
                 m_journal.debug << iIdentifier << " Extra path element gives " << transHuman (terResult);
             }
             if (terResult == tesSUCCESS)
             {
                 Json::Value jvEntry (Json::objectValue);
                 jvEntry["source_amount"]    = saMaxAmountAct.getJson (0);
                 jvEntry["paths_computed"]   = spsPaths.getJson (0);
                 found  = true;
                 jvArray.append (jvEntry);
             }
             else
             {
                 m_journal.debug << iIdentifier << " rippleCalc returns " << transHuman (terResult);
             }
         }
         else
         {
             m_journal.debug << iIdentifier << " No paths found";
         }
     }
     iLastLevel = iLevel;
     bLastSuccess = found;
     if (fast && ptQuickReply.is_not_a_date_time())
     {
         ptQuickReply = boost::posix_time::microsec_clock::universal_time();
         mOwner.reportFast ((ptQuickReply-ptCreated).total_milliseconds());
     }
     else if (!fast && ptFullReply.is_not_a_date_time())
     {
         ptFullReply = boost::posix_time::microsec_clock::universal_time();
         mOwner.reportFull ((ptFullReply-ptCreated).total_milliseconds());
     }
     jvStatus["alternatives"] = jvArray;
     return jvStatus;
 }
static char const* ripple::PathRequest::getCountedObjectName () inline static
Definition at line 41 of file PathRequest.h.
 { return "PathRequest"; }
Json::Value ripple::PathRequest::getStatus ()
InfoSub::pointer ripple::PathRequest::getSubscriber ()
Definition at line 474 of file PathRequest.cpp.
References wpSubscriber.
 {
     return wpSubscriber.lock ();
 }
bool ripple::PathRequest::isNew ()
Definition at line 78 of file PathRequest.cpp.
References iLastIndex.
 {
      // does this path request still need its first full path
      return iLastIndex.load() == 0;
 }
bool ripple::PathRequest::isValid (RippleLineCache::ref crCache)
Definition at line 114 of file PathRequest.cpp.
References Json::Value::append(), Json::arrayValue, bValid, ripple::STAmount::createHumanCurrency(), ripple::NetworkOPs::getAccountState(), ripple::getApp(), ripple::Application::getOPs(), ripple::is_bit_set(), ripple::STAmount::isNative(), ripple::RippleAddress::isSet(), jvStatus, ripple::lsfDisallowXRP, ripple::lsfRequireDestTag, mLock, raDstAccount, raSrcAccount, ripple::rpcACT_NOT_FOUND, ripple::rpcDST_AMT_MALFORMED, ripple::rpcError(), ripple::rpcSRC_ACT_NOT_FOUND, saDstAmount, and ripple::usAccountDestCurrencies().
 {
     ScopedLockType sl (mLock);
     bValid = raSrcAccount.isSet () && raDstAccount.isSet () && saDstAmount > zero;
     Ledger::pointer lrLedger = crCache->getLedger ();
     if (bValid)
     {
         AccountState::pointer asSrc = getApp().getOPs ().getAccountState (crCache->getLedger(), raSrcAccount);
         if (!asSrc)
         {
             // no source account
             bValid = false;
             jvStatus = rpcError (rpcSRC_ACT_NOT_FOUND);
         }
         else
         {
             AccountState::pointer asDst = getApp().getOPs ().getAccountState (lrLedger, raDstAccount);
             Json::Value& jvDestCur = (jvStatus["destination_currencies"] = Json::arrayValue);
             if (!asDst)
             {
                 // no destination account
                 jvDestCur.append (Json::Value ("XRP"));
                 if (!saDstAmount.isNative ())
                 {
                     // only XRP can be send to a non-existent account
                     bValid = false;
                     jvStatus = rpcError (rpcACT_NOT_FOUND);
                 }
                 else if (saDstAmount < STAmount (lrLedger->getReserve (0)))
                 {
                     // payment must meet reserve
                     bValid = false;
                     jvStatus = rpcError (rpcDST_AMT_MALFORMED);
                 }
             }
             else
             {
                 bool includeXRP = !is_bit_set (asDst->peekSLE ().getFlags(), lsfDisallowXRP);
                 boost::unordered_set<uint160> usDestCurrID =
                     usAccountDestCurrencies (raDstAccount, crCache, includeXRP);
                 BOOST_FOREACH (const uint160 & uCurrency, usDestCurrID)
                     jvDestCur.append (STAmount::createHumanCurrency (uCurrency));
                 jvStatus["destination_tag"] = (asDst->peekSLE ().getFlags () & lsfRequireDestTag) != 0;
             }
         }
     }
     if (bValid)
     {
         jvStatus["ledger_hash"] = lrLedger->getHash ().GetHex ();
         jvStatus["ledger_index"] = lrLedger->getLedgerSeq ();
     }
     return bValid;
 }
bool ripple::PathRequest::isValid ()
Definition at line 72 of file PathRequest.cpp.
References bValid, and mLock.
Referenced by doCreate(), and doUpdate().
 {
     ScopedLockType sl (mLock);
     return bValid;
 }
bool ripple::PathRequest::needsUpdate (bool newOnly, LedgerIndex index)
Definition at line 84 of file PathRequest.cpp.
References iLastIndex.
 {
     LedgerIndex lastIndex = iLastIndex.load();
     for (;;)
     {
         if (newOnly)
         {
             // Is this request new
             if (lastIndex != 0)
                 return false;
             // This thread marks this request handled
             if (iLastIndex.compare_exchange_weak (lastIndex, 1,
                     std::memory_order_release, std::memory_order_relaxed))
                 return true;
         }
         else
         {
             // Has the request already been handled?
             if (lastIndex >= index)
                 return false;
             // This thread marks this request handled
             if (iLastIndex.compare_exchange_weak (lastIndex, index,
                     std::memory_order_release, std::memory_order_relaxed))
                 return true;
         }
     }
 }
int ripple::PathRequest::parseJson (const Json::Value & jvParams, bool complete) private
Definition at line 212 of file PathRequest.cpp.
References Json::Value::asString(), ripple::STAmount::bSetJson(), CURRENCY_BAD, ripple::STAmount::currencyFromString(), ripple::STAmount::getCurrency(), ripple::STAmount::getIssuer(), Json::Value::isArray(), Json::Value::isMember(), ripple::base_uint< BITS >::isNonZero(), Json::Value::isObject(), ripple::STAmount::issuerFromString(), ripple::base_uint< BITS >::isZero(), jvId, jvStatus, PFR_PJ_INVALID, PFR_PJ_NOCHANGE, raDstAccount, raSrcAccount, ripple::rpcDST_ACT_MALFORMED, ripple::rpcDST_ACT_MISSING, ripple::rpcDST_AMT_MALFORMED, ripple::rpcError(), ripple::rpcSRC_ACT_MALFORMED, ripple::rpcSRC_ACT_MISSING, ripple::rpcSRC_CUR_MALFORMED, ripple::rpcSRC_ISR_MALFORMED, saDstAmount, sciSourceCurrencies, ripple::RippleAddress::setAccountID(), and Json::Value::size().
Referenced by doCreate().
 {
     int ret = PFR_PJ_NOCHANGE;
     if (jvParams.isMember ("source_account"))
     {
         if (!raSrcAccount.setAccountID (jvParams["source_account"].asString ()))
         {
             jvStatus = rpcError (rpcSRC_ACT_MALFORMED);
             return PFR_PJ_INVALID;
         }
     }
     else if (complete)
     {
         jvStatus = rpcError (rpcSRC_ACT_MISSING);
         return PFR_PJ_INVALID;
     }
     if (jvParams.isMember ("destination_account"))
     {
         if (!raDstAccount.setAccountID (jvParams["destination_account"].asString ()))
         {
             jvStatus = rpcError (rpcDST_ACT_MALFORMED);
             return PFR_PJ_INVALID;
         }
     }
     else if (complete)
     {
         jvStatus = rpcError (rpcDST_ACT_MISSING);
         return PFR_PJ_INVALID;
     }
     if (jvParams.isMember ("destination_amount"))
     {
         if (!saDstAmount.bSetJson (jvParams["destination_amount"]) ||
                 (saDstAmount.getCurrency ().isZero () && saDstAmount.getIssuer ().isNonZero ()) ||
                 (saDstAmount.getCurrency () == CURRENCY_BAD) ||
                 saDstAmount <= zero)
         {
             jvStatus = rpcError (rpcDST_AMT_MALFORMED);
             return PFR_PJ_INVALID;
         }
     }
     else if (complete)
     {
         jvStatus = rpcError (rpcDST_ACT_MISSING);
         return PFR_PJ_INVALID;
     }
     if (jvParams.isMember ("source_currencies"))
     {
         const Json::Value& jvSrcCur = jvParams["source_currencies"];
         if (!jvSrcCur.isArray ())
         {
             jvStatus = rpcError (rpcSRC_CUR_MALFORMED);
             return PFR_PJ_INVALID;
         }
         sciSourceCurrencies.clear ();
         for (unsigned i = 0; i < jvSrcCur.size (); ++i)
         {
             const Json::Value& jvCur = jvSrcCur[i];
             uint160 uCur, uIss;
             if (!jvCur.isObject() || !jvCur.isMember ("currency") || !STAmount::currencyFromString (uCur, jvCur["currency"].asString ()))
             {
                 jvStatus = rpcError (rpcSRC_CUR_MALFORMED);
                 return PFR_PJ_INVALID;
             }
             if (jvCur.isMember ("issuer") && !STAmount::issuerFromString (uIss, jvCur["issuer"].asString ()))
             {
                 jvStatus = rpcError (rpcSRC_ISR_MALFORMED);
             }
             if (uCur.isZero () && uIss.isNonZero ())
             {
                 jvStatus = rpcError (rpcSRC_CUR_MALFORMED);
                 return PFR_PJ_INVALID;
             }
             sciSourceCurrencies.insert (currIssuer_t (uCur, uIss));
         }
     }
     if (jvParams.isMember ("id"))
         jvId = jvParams["id"];
     return ret;
 }
void ripple::PathRequest::resetLevel (int level) private
Definition at line 317 of file PathRequest.cpp.
References iLastLevel.
 {
     if (iLastLevel > l)
         iLastLevel = l;
 }
void ripple::PathRequest::setValid () private
Member Data Documentation
bool ripple::PathRequest::bLastSuccess private
Definition at line 99 of file PathRequest.h.
Referenced by doUpdate().
bool ripple::PathRequest::bValid private
Definition at line 94 of file PathRequest.h.
Referenced by doCreate(), and isValid().
int ripple::PathRequest::iIdentifier private
Definition at line 101 of file PathRequest.h.
Referenced by doClose(), doCreate(), doUpdate(), and ~PathRequest().
std::atomic<LedgerIndex> ripple::PathRequest::iLastIndex private
Definition at line 96 of file PathRequest.h.
Referenced by isNew(), and needsUpdate().
int ripple::PathRequest::iLastLevel private
Definition at line 98 of file PathRequest.h.
Referenced by doUpdate(), and resetLevel().
Json::Value ripple::PathRequest::jvId private
Definition at line 83 of file PathRequest.h.
Referenced by doUpdate(), and parseJson().
Json::Value ripple::PathRequest::jvStatus private
Definition at line 84 of file PathRequest.h.
Referenced by doClose(), doCreate(), doStatus(), doUpdate(), isValid(), and parseJson().
beast::Journal ripple::PathRequest::m_journal private
Definition at line 74 of file PathRequest.h.
Referenced by doClose(), doCreate(), doUpdate(), and ~PathRequest().
std::map<currIssuer_t, STPathSet> ripple::PathRequest::mContext private
Definition at line 92 of file PathRequest.h.
Referenced by doUpdate().
LockType ripple::PathRequest::mLock private
Definition at line 78 of file PathRequest.h.
Referenced by doClose(), doStatus(), doUpdate(), and isValid().
PathRequests& ripple::PathRequest::mOwner private
Definition at line 80 of file PathRequest.h.
Referenced by doUpdate().
boost::posix_time::ptime ripple::PathRequest::ptCreated private
Definition at line 103 of file PathRequest.h.
Referenced by doUpdate(), and ~PathRequest().
boost::posix_time::ptime ripple::PathRequest::ptFullReply private
Definition at line 105 of file PathRequest.h.
Referenced by doUpdate(), and ~PathRequest().
boost::posix_time::ptime ripple::PathRequest::ptQuickReply private
Definition at line 104 of file PathRequest.h.
Referenced by doUpdate(), and ~PathRequest().
RippleAddress ripple::PathRequest::raDstAccount private
Definition at line 88 of file PathRequest.h.
Referenced by doUpdate(), isValid(), and parseJson().
RippleAddress ripple::PathRequest::raSrcAccount private
Definition at line 87 of file PathRequest.h.
Referenced by doCreate(), doUpdate(), isValid(), and parseJson().
STAmount ripple::PathRequest::saDstAmount private
Definition at line 89 of file PathRequest.h.
Referenced by doCreate(), doUpdate(), isValid(), and parseJson().
std::set<currIssuer_t> ripple::PathRequest::sciSourceCurrencies private
Definition at line 90 of file PathRequest.h.
Referenced by doUpdate(), and parseJson().
boost::weak_ptr<InfoSub> ripple::PathRequest::wpSubscriber private
Definition at line 82 of file PathRequest.h.
Referenced by getSubscriber().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/paths/PathRequest.h
rippled/src/ripple_app/paths/PathRequest.cpp