rippled: ripple::TransactionStateSF Class Reference
ripple::TransactionStateSF Class Reference
#include <SHAMapSyncFilters.h>
Public Member Functions
TransactionStateSF (std::uint32_t ledgerSeq)
void gotNode (bool fromFilter, SHAMapNode const &id, uint256 const &nodeHash, Blob &nodeData, SHAMapTreeNode::TNType)
bool haveNode (SHAMapNode const &id, uint256 const &nodeHash, Blob &nodeData)
Public Member Functions inherited from ripple::SHAMapSyncFilter
virtual ~SHAMapSyncFilter ()
Private Attributes
std::uint32_t mLedgerSeq
Detailed Description
Definition at line 77 of file SHAMapSyncFilters.h.
Constructor & Destructor Documentation
ripple::TransactionStateSF::TransactionStateSF (std::uint32_t ledgerSeq) explicit
Definition at line 105 of file SHAMapSyncFilters.cpp.
     : mLedgerSeq (ledgerSeq)
 {
 }
Member Function Documentation
void ripple::TransactionStateSF::gotNode (bool fromFilter, SHAMapNode const & id, uint256 const & nodeHash, Blob & nodeData, SHAMapTreeNode::TNType type) virtual
Implements ripple::SHAMapSyncFilter.
Definition at line 110 of file SHAMapSyncFilters.cpp.
References ripple::getApp(), ripple::Application::getNodeStore(), ripple::hotTRANSACTION, ripple::hotTRANSACTION_NODE, mLedgerSeq, ripple::NodeStore::Database::store(), and ripple::SHAMapTreeNode::tnTRANSACTION_NM.
 {
     getApp().getNodeStore ().store (
         (type == SHAMapTreeNode::tnTRANSACTION_NM) ? hotTRANSACTION : hotTRANSACTION_NODE,
         mLedgerSeq,
         nodeData,
         nodeHash);
 }
bool ripple::TransactionStateSF::haveNode (SHAMapNode const & id, uint256 const & nodeHash, Blob & nodeData) virtual
Implements ripple::SHAMapSyncFilter.
Definition at line 123 of file SHAMapSyncFilters.cpp.
References ripple::getApp(), ripple::NetworkOPs::getFetchPack(), and ripple::Application::getOPs().
 {
     return getApp().getOPs ().getFetchPack (nodeHash, nodeData);
 }
Member Data Documentation
std::uint32_t ripple::TransactionStateSF::mLedgerSeq private
Definition at line 94 of file SHAMapSyncFilters.h.
Referenced by gotNode().
The documentation for this class was generated from the following files:
rippled/src/ripple_app/shamap/SHAMapSyncFilters.h
rippled/src/ripple_app/shamap/SHAMapSyncFilters.cpp