rippled: rocksdb::KeyConvertingIterator Class Reference
rocksdb::KeyConvertingIterator Class Reference
Public Member Functions
KeyConvertingIterator (Iterator *iter)
virtual ~KeyConvertingIterator ()
virtual bool Valid () const
virtual void Seek (const Slice &target)
virtual void SeekToFirst ()
virtual void SeekToLast ()
virtual void Next ()
virtual void Prev ()
virtual Slice key () const
virtual Slice value () const
virtual Status status () const
Public Member Functions inherited from rocksdb::Iterator
Iterator ()
virtual ~Iterator ()
void RegisterCleanup (CleanupFunction function, void *arg1, void *arg2)
Private Member Functions
KeyConvertingIterator (const KeyConvertingIterator &)
void operator= (const KeyConvertingIterator &)
Private Attributes
Status status_
Iterator * iter_
Additional Inherited Members
Public Types inherited from rocksdb::Iterator
typedef void(* CleanupFunction)(void *arg1, void *arg2)
Detailed Description
Definition at line 327 of file table_test.cc.
Constructor & Destructor Documentation
rocksdb::KeyConvertingIterator::KeyConvertingIterator (Iterator * iter) inline explicit
Definition at line 329 of file table_test.cc.
 : iter_(iter) { }
virtual rocksdb::KeyConvertingIterator::~KeyConvertingIterator () inline virtual
Definition at line 330 of file table_test.cc.
References iter_.
 { delete iter_; }
rocksdb::KeyConvertingIterator::KeyConvertingIterator (const KeyConvertingIterator &) private
Member Function Documentation
virtual Slice rocksdb::KeyConvertingIterator::key () const inline virtual
Implements rocksdb::Iterator.
Definition at line 343 of file table_test.cc.
References rocksdb::Status::Corruption(), iter_, rocksdb::Iterator::key(), rocksdb::ParseInternalKey(), status_, rocksdb::ParsedInternalKey::user_key, and Valid().
{
     assert(Valid());
     ParsedInternalKey key;
     if (!ParseInternalKey(iter_->key(), &key)) {
       status_ = Status::Corruption("malformed internal key");
       return Slice("corrupted key");
     }
     return key.user_key;
   }
virtual void rocksdb::KeyConvertingIterator::Next () inline virtual
Implements rocksdb::Iterator.
Definition at line 340 of file table_test.cc.
References iter_, and rocksdb::Iterator::Next().
 { iter_->Next(); }
void rocksdb::KeyConvertingIterator::operator= (const KeyConvertingIterator &) private
virtual void rocksdb::KeyConvertingIterator::Prev () inline virtual
Implements rocksdb::Iterator.
Definition at line 341 of file table_test.cc.
References iter_, and rocksdb::Iterator::Prev().
 { iter_->Prev(); }
virtual void rocksdb::KeyConvertingIterator::Seek (const Slice & target) inline virtual
Implements rocksdb::Iterator.
Definition at line 332 of file table_test.cc.
References rocksdb::AppendInternalKey(), iter_, rocksdb::kMaxSequenceNumber, rocksdb::kTypeValue, and rocksdb::Iterator::Seek().
{
     ParsedInternalKey ikey(target, kMaxSequenceNumber, kTypeValue);
     std::string encoded;
     AppendInternalKey(&encoded, ikey);
     iter_->Seek(encoded);
   }
virtual void rocksdb::KeyConvertingIterator::SeekToFirst () inline virtual
Implements rocksdb::Iterator.
Definition at line 338 of file table_test.cc.
References iter_, and rocksdb::Iterator::SeekToFirst().
 { iter_->SeekToFirst(); }
virtual void rocksdb::KeyConvertingIterator::SeekToLast () inline virtual
Implements rocksdb::Iterator.
Definition at line 339 of file table_test.cc.
References iter_, and rocksdb::Iterator::SeekToLast().
 { iter_->SeekToLast(); }
virtual Status rocksdb::KeyConvertingIterator::status () const inline virtual
Implements rocksdb::Iterator.
Definition at line 354 of file table_test.cc.
References iter_, rocksdb::Status::ok(), rocksdb::Iterator::status(), and status_.
{
     return status_.ok() ? iter_->status() : status_;
   }
virtual bool rocksdb::KeyConvertingIterator::Valid () const inline virtual
Implements rocksdb::Iterator.
Definition at line 331 of file table_test.cc.
References iter_, and rocksdb::Iterator::Valid().
Referenced by key().
 { return iter_->Valid(); }
virtual Slice rocksdb::KeyConvertingIterator::value () const inline virtual
Implements rocksdb::Iterator.
Definition at line 353 of file table_test.cc.
References iter_, and rocksdb::Iterator::value().
 { return iter_->value(); }
Member Data Documentation
Iterator* rocksdb::KeyConvertingIterator::iter_ private
Definition at line 360 of file table_test.cc.
Referenced by key(), Next(), Prev(), Seek(), SeekToFirst(), SeekToLast(), status(), Valid(), value(), and ~KeyConvertingIterator().
Status rocksdb::KeyConvertingIterator::status_ mutable private
Definition at line 359 of file table_test.cc.
Referenced by key(), and status().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/table/table_test.cc