rippled: ShellStateStop Class Reference
ShellStateStop Class Reference
#include <ShellState.h>
Public Member Functions
virtual void run (ShellContext *)
Public Member Functions inherited from ShellState
virtual ~ShellState ()
Static Public Member Functions
static ShellStateStop * getInstance (void)
Private Member Functions
ShellStateStop ()
virtual ~ShellStateStop ()
Detailed Description
Definition at line 38 of file ShellState.h.
Constructor & Destructor Documentation
ShellStateStop::ShellStateStop () inline private
Definition at line 48 of file ShellState.h.
 {}
virtual ShellStateStop::~ShellStateStop () inline private virtual
Definition at line 49 of file ShellState.h.
 {}
Member Function Documentation
static ShellStateStop* ShellStateStop::getInstance (void) inline static
Definition at line 40 of file ShellState.h.
References instance.
Referenced by ShellStateConnected::handleConError(), ShellStateStart::run(), ShellStateConnecting::run(), and ShellStateConnected::run().
{
     static ShellStateStop instance;
     return &instance;
   }
void ShellStateStop::run (ShellContext * c) virtual
Implements ShellState.
Definition at line 26 of file ShellState.cpp.
References ShellContext::stop().
{
   c->stop();
 }
The documentation for this class was generated from the following files:
rippled/src/ripple/rocksdb/rocksdb/tools/shell/ShellState.h
rippled/src/ripple/rocksdb/rocksdb/tools/shell/ShellState.cpp