rippled: ripple::HTTP::Session Class Reference
ripple::HTTP::Session Class Reference abstract
#include <Session.h>
Public Member Functions
virtual beast::Journal journal ()=0
virtual beast::IP::Endpoint remoteAddress ()=0
virtual bool headersComplete ()=0
virtual beast::HTTPHeaders headers ()=0
virtual beast::SharedPtr
< beast::HTTPRequest > const & request ()=0
virtual std::string content ()=0
virtual void detach ()=0
virtual void close ()=0
void write (std::string const &s)
template<typename BufferSequence >
void write (BufferSequence const &buffers)
virtual void write (void const *buffer, std::size_t bytes)=0
ScopedStream operator<< (std::ostream &manip(std::ostream &))
template<typename T >
ScopedStream operator<< (T const &t)
Public Attributes
void * tag
Additional Inherited Members
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
Persistent state information for a connection session. These values are preserved between calls for efficiency. Some fields are input parameters, some are output parameters, and all only become defined during specific callbacks.
Definition at line 34 of file Session.h.
Member Function Documentation
virtual void ripple::HTTP::Session::close () pure virtual
Close the session. This will be performed asynchronously. The session will be closed gracefully after all pending writes have completed.
Implemented in ripple::HTTP::Peer.
Referenced by ripple::RPCHTTPServerImp::onAccept(), and ripple::RPCHTTPServerImp::processSession().
virtual std::string ripple::HTTP::Session::content () pure virtual
Returns the entire Content-Body, if the request is complete.
Implemented in ripple::HTTP::Peer.
Referenced by ripple::RPCHTTPServerImp::processSession().
virtual void ripple::HTTP::Session::detach () pure virtual
Detach the session. This holds the session open so that the response can be sent asynchronously. Calls to io_service::run made by the server will not return until all detached sessions are closed.
Implemented in ripple::HTTP::Peer.
Referenced by ripple::RPCHTTPServerImp::onRequest().
virtual beast::HTTPHeaders ripple::HTTP::Session::headers () pure virtual
Returns the currently known set of headers.
Implemented in ripple::HTTP::Peer.
virtual bool ripple::HTTP::Session::headersComplete () pure virtual
Returns true if the full HTTP headers have been received.
Implemented in ripple::HTTP::Peer.
virtual beast::Journal ripple::HTTP::Session::journal () pure virtual
Returns the Journal to use for logging.
Implemented in ripple::HTTP::Peer.
ScopedStream ripple::HTTP::Session::operator<< (std::ostream & manipstd::ostream &) inline
Output support using ostream.
Definition at line 87 of file Session.h.
     {
         return ScopedStream (*this, manip);
     }
template<typename T > ScopedStream ripple::HTTP::Session::operator<< (T const & t) inline
Definition at line 93 of file Session.h.
     {
         return ScopedStream (*this, t);
     }
virtual beast::IP::Endpoint ripple::HTTP::Session::remoteAddress () pure virtual
Returns the remote address of the connection.
Implemented in ripple::HTTP::Peer.
Referenced by ripple::RPCHTTPServerImp::onAccept(), and ripple::RPCHTTPServerImp::processSession().
virtual beast::SharedPtr<beast::HTTPRequest> const& ripple::HTTP::Session::request () pure virtual
Returns the complete HTTP request when it is known.
Implemented in ripple::HTTP::Peer.
void ripple::HTTP::Session::write (std::string const & s) inline
Send a copy of data asynchronously.
Definition at line 63 of file Session.h.
Referenced by ripple::RPCHTTPServerImp::processSession(), write(), and ripple::HTTP::ScopedStream::~ScopedStream().
     {
         if (! s.empty())
             write (&s[0],
                 std::distance (s.begin(), s.end()));
     }
template<typename BufferSequence > void ripple::HTTP::Session::write (BufferSequence const & buffers) inline
Definition at line 71 of file Session.h.
References write().
     {
         for (typename BufferSequence::const_iterator iter (buffers.begin());
             iter != buffers.end(); ++iter)
         {
             typename BufferSequence::value_type const& buffer (*iter);
             write (boost::asio::buffer_cast <void const*> (buffer),
                 boost::asio::buffer_size (buffer));
         }
     }
virtual void ripple::HTTP::Session::write (void const * buffer, std::size_t bytes) pure virtual
Implemented in ripple::HTTP::Peer.
Member Data Documentation
void* ripple::HTTP::Session::tag
A user-definable pointer. The initial value is always zero. Changes to the value are persisted between calls.
Definition at line 41 of file Session.h.
Referenced by ripple::HTTP::Peer::Peer().
The documentation for this class was generated from the following file:
rippled/src/ripple/http/api/Session.h