rippled: ripple::InboundLedgersImp Class Reference
ripple::InboundLedgersImp Class Reference
Public Types
typedef std::pair< uint256,
InboundLedger::pointer > u256_acq_pair
Public Types inherited from ripple::InboundLedgers
typedef beast::abstract_clock
< std::chrono::seconds > clock_type
Public Member Functions
InboundLedgersImp (clock_type &clock, Stoppable &parent, beast::insight::Collector::ptr const &collector)
InboundLedger::pointer findCreate (uint256 const &hash, std::uint32_t seq, InboundLedger::fcReason reason)
InboundLedger::pointer find (uint256 const &hash)
bool hasLedger (LedgerHash const &hash)
void dropLedger (LedgerHash const &hash)
bool gotLedgerData (LedgerHash const &hash, boost::shared_ptr< Peer > peer, boost::shared_ptr< protocol::TMLedgerData > packet_ptr)
int getFetchCount (int &timeoutCount)
void logFailure (uint256 const &h)
bool isFailure (uint256 const &h)
void doLedgerData (Job &, LedgerHash hash)
void gotStaleData (boost::shared_ptr< protocol::TMLedgerData > packet_ptr)
void clearFailures ()
Json::Value getInfo ()
void gotFetchPack (Job &)
void sweep ()
void onStop ()
Public Member Functions inherited from ripple::InboundLedgers
virtual ~InboundLedgers ()=0
Public Member Functions inherited from beast::Stoppable
Stoppable (char const *name, Stoppable &parent)
virtual ~Stoppable ()
bool isStopping () const
bool isStopped () const
bool areChildrenStopped () const
void stopped ()
virtual void onPrepare ()
virtual void onStart ()
virtual void onChildrenStopped ()
Static Public Attributes
static const int kReacquireIntervalSeconds = 300
Private Types
typedef ripple::unordered_map
< uint256,
InboundLedger::pointer > MapType
typedef RippleRecursiveMutex LockType
typedef std::unique_lock
< LockType > ScopedLockType
Private Attributes
clock_type & m_clock
LockType mLock
MapType mLedgers
KeyCache< uint256 > mRecentFailures
uint256 mConsensusLedger
uint256 mValidationLedger
beast::insight::Counter mCounter
Additional Inherited Members
Static Public Member Functions inherited from ripple::InboundLedgers
static InboundLedgers * New (clock_type &clock, beast::Stoppable &parent, beast::insight::Collector::ptr const &collector)
Protected Member Functions inherited from beast::Stoppable
Stoppable (char const *name, RootStoppable &root)
Protected Attributes inherited from beast::Stoppable
char const * m_name
RootStoppable & m_root
Child m_child
Atomic< int > m_started
bool volatile m_stopped
bool volatile m_childrenStopped
Children m_children
WaitableEvent m_stoppedEvent
Detailed Description
Definition at line 22 of file InboundLedgers.cpp.
Member Typedef Documentation
typedef RippleRecursiveMutex ripple::InboundLedgersImp::LockType private
Definition at line 379 of file InboundLedgers.cpp.
typedef ripple::unordered_map<uint256, InboundLedger::pointer> ripple::InboundLedgersImp::MapType private
Definition at line 377 of file InboundLedgers.cpp.
typedef std::unique_lock<LockType> ripple::InboundLedgersImp::ScopedLockType private
Definition at line 380 of file InboundLedgers.cpp.
typedef std::pair<uint256, InboundLedger::pointer> ripple::InboundLedgersImp::u256_acq_pair
Definition at line 28 of file InboundLedgers.cpp.
Constructor & Destructor Documentation
ripple::InboundLedgersImp::InboundLedgersImp (clock_type & clock, Stoppable & parent, beast::insight::Collector::ptr const & collector) inline
Definition at line 32 of file InboundLedgers.cpp.
         : Stoppable ("InboundLedgers", parent)
         , m_clock (clock)
         , mRecentFailures ("LedgerAcquireRecentFailures",
             clock, 0, kReacquireIntervalSeconds)
         , mCounter(collector->make_counter("ledger_fetches"))
     {
     }
Member Function Documentation
void ripple::InboundLedgersImp::clearFailures () inline virtual
Implements ripple::InboundLedgers.
Definition at line 267 of file InboundLedgers.cpp.
References mLedgers, mLock, and mRecentFailures.
     {
         ScopedLockType sl (mLock);
         mRecentFailures.clear();
         mLedgers.clear();
     }
void ripple::InboundLedgersImp::doLedgerData (Job & , LedgerHash hash) inline virtual
Implements ripple::InboundLedgers.
Definition at line 226 of file InboundLedgers.cpp.
References find().
     {
         InboundLedger::pointer ledger = find (hash);
         if (ledger)
             ledger->runData ();
     }
void ripple::InboundLedgersImp::dropLedger (LedgerHash const & hash) inline virtual
Implements ripple::InboundLedgers.
Definition at line 132 of file InboundLedgers.cpp.
References ripple::base_uint< BITS >::isNonZero(), mLedgers, and mLock.
     {
         assert (hash.isNonZero ());
         ScopedLockType sl (mLock);
         mLedgers.erase (hash);
     }
InboundLedger::pointer ripple::InboundLedgersImp::find (uint256 const & hash) inline virtual
Implements ripple::InboundLedgers.
Definition at line 105 of file InboundLedgers.cpp.
References ripple::base_uint< BITS >::isNonZero(), mLedgers, and mLock.
Referenced by doLedgerData(), and gotLedgerData().
     {
         assert (hash.isNonZero ());
         InboundLedger::pointer ret;
         {
             ScopedLockType sl (mLock);
             ripple::unordered_map<uint256, InboundLedger::pointer>::iterator it = mLedgers.find (hash);
             if (it != mLedgers.end ())
             {
                 ret = it->second;
             }
         }
         return ret;
     }
InboundLedger::pointer ripple::InboundLedgersImp::findCreate (uint256 const & hash, std::uint32_t seq, InboundLedger::fcReason reason) inline virtual
Implements ripple::InboundLedgers.
Definition at line 44 of file InboundLedgers.cpp.
References ripple::InboundLedger::fcCONSENSUS, ripple::InboundLedger::fcVALIDATION, hash, ripple::base_uint< BITS >::isNonZero(), beast::Stoppable::isStopping(), m_clock, mConsensusLedger, mCounter, mLedgers, mLock, and mValidationLedger.
     {
         assert (hash.isNonZero ());
         InboundLedger::pointer ret;
         // Ensure that any previous IL is destroyed outside the lock
         InboundLedger::pointer oldLedger;
         {
             ScopedLockType sl (mLock);
             if (! isStopping ())
             {
                 if (reason == InboundLedger::fcCONSENSUS)
                 {
             if (mConsensusLedger.isNonZero() && (mValidationLedger != mConsensusLedger) && (hash != mConsensusLedger))
             {
             ripple::unordered_map<uint256, InboundLedger::pointer>::iterator it = mLedgers.find (mConsensusLedger);
             if (it != mLedgers.end ())
             {
                 oldLedger = it->second;
                 mLedgers.erase (it);
                }
             }
             mConsensusLedger = hash;
                 }
                 else if (reason == InboundLedger::fcVALIDATION)
                 {
             if (mValidationLedger.isNonZero() && (mValidationLedger != mConsensusLedger) && (hash != mValidationLedger))
             {
             ripple::unordered_map<uint256, InboundLedger::pointer>::iterator it = mLedgers.find (mValidationLedger);
             if (it != mLedgers.end ())
             {
                 oldLedger = it->second;
                 mLedgers.erase (it);
                }
             }
             mValidationLedger = hash;
                 }
                 ripple::unordered_map<uint256, InboundLedger::pointer>::iterator it = mLedgers.find (hash);
                 if (it != mLedgers.end ())
                 {
                     ret = it->second;
                     // FIXME: Should set the sequence if it's not set
                 }
                 else
                 {
                     ret = boost::make_shared <InboundLedger> (hash, seq, reason, std::ref (m_clock));
                     assert (ret);
                     mLedgers.insert (std::make_pair (hash, ret));
                     ret->init (sl);
                     ++mCounter;
                 }
             }
         }
         return ret;
     }
int ripple::InboundLedgersImp::getFetchCount (int & timeoutCount) inline virtual
Implements ripple::InboundLedgers.
Definition at line 188 of file InboundLedgers.cpp.
References mLedgers, and mLock.
     {
         timeoutCount = 0;
         int ret = 0;
         std::vector<u256_acq_pair> inboundLedgers;
         {
             ScopedLockType sl (mLock);
             inboundLedgers.reserve(mLedgers.size());
             BOOST_FOREACH (const u256_acq_pair & it, mLedgers)
             {
                 inboundLedgers.push_back(it);
             }
         }
         BOOST_FOREACH (const u256_acq_pair & it, inboundLedgers)
         {
             if (it.second->isActive ())
             {
                 ++ret;
                 timeoutCount += it.second->getTimeouts ();
             }
         }
         return ret;
     }
Json::Value ripple::InboundLedgersImp::getInfo () inline virtual
Implements ripple::InboundLedgers.
Definition at line 275 of file InboundLedgers.cpp.
References mLedgers, mLock, and Json::objectValue.
     {
         Json::Value ret(Json::objectValue);
         std::vector<u256_acq_pair> acquires;
         {
             ScopedLockType sl (mLock);
             acquires.reserve (mLedgers.size ());
             BOOST_FOREACH (const u256_acq_pair & it, mLedgers)
             {
                 assert (it.second);
                 acquires.push_back (it);
             }
         }
         BOOST_FOREACH (const u256_acq_pair& it, acquires)
         {
             std::uint32_t seq = it.second->getSeq();
             if (seq > 1)
                 ret[beast::lexicalCastThrow <std::string>(seq)] = it.second->getJson(0);
             else
                 ret[it.first.GetHex()] = it.second->getJson(0);
         }
     return ret;
     }
void ripple::InboundLedgersImp::gotFetchPack (Job &) inline virtual
Implements ripple::InboundLedgers.
Definition at line 303 of file InboundLedgers.cpp.
References mLedgers, and mLock.
     {
         std::vector<InboundLedger::pointer> acquires;
         {
             ScopedLockType sl (mLock);
             acquires.reserve (mLedgers.size ());
             BOOST_FOREACH (const u256_acq_pair & it, mLedgers)
             {
                 assert (it.second);
                 acquires.push_back (it.second);
             }
         }
         BOOST_FOREACH (const InboundLedger::pointer & acquire, acquires)
         {
             acquire->checkLocal ();
         }
     }
bool ripple::InboundLedgersImp::gotLedgerData (LedgerHash const & hash, boost::shared_ptr< Peer > peer, boost::shared_ptr< protocol::TMLedgerData > packet_ptr) inline virtual
We received a TMLedgerData from a peer.
Implements ripple::InboundLedgers.
Definition at line 156 of file InboundLedgers.cpp.
References ripple::JobQueue::addJob(), BIND_TYPE, ripple::InboundLedgers::doLedgerData(), find(), ripple::getApp(), ripple::Application::getJobQueue(), ripple::InboundLedgers::gotStaleData(), hash, ripple::jtLEDGER_DATA, ripple::lsTRACE, P_1, and WriteLog.
     {
         protocol::TMLedgerData& packet = *packet_ptr;
         WriteLog (lsTRACE, InboundLedger) << "Got data (" << packet.nodes ().size () << ") for acquiring ledger: " << hash;
         InboundLedger::pointer ledger = find (hash);
         if (!ledger)
         {
             WriteLog (lsTRACE, InboundLedger) << "Got data for ledger we're no longer acquiring";
             // If it's state node data, stash it because it still might be useful
             if (packet.type () == protocol::liAS_NODE)
             {
                 getApp().getJobQueue().addJob(jtLEDGER_DATA, "gotStaleData",
                     BIND_TYPE(&InboundLedgers::gotStaleData, this, packet_ptr));
             }
             return false;
         }
         // Stash the data for later processing and see if we need to dispatch
         if (ledger->gotData(boost::weak_ptr<Peer>(peer), packet_ptr))
             getApp().getJobQueue().addJob (jtLEDGER_DATA, "processLedgerData",
                 BIND_TYPE (&InboundLedgers::doLedgerData, this, P_1, hash));
         return true;
     }
void ripple::InboundLedgersImp::gotStaleData (boost::shared_ptr< protocol::TMLedgerData > packet_ptr) inline virtual
We got some data for a ledger we are no longer acquiring Since we paid the price to receive it, we might as well stash it in case we need it. Nodes are received in wire format and must be stashed/hashed in prefix format
Implements ripple::InboundLedgers.
Definition at line 238 of file InboundLedgers.cpp.
References ripple::NetworkOPs::addFetchPack(), ripple::SHAMapTreeNode::addRaw(), ripple::Serializer::begin(), ripple::Serializer::end(), ripple::getApp(), ripple::SHAMapTreeNode::getNodeHash(), ripple::Application::getOPs(), ripple::snfPREFIX, ripple::snfWIRE, and ripple::uZero.
     {
         const uint256 uZero;
         try
         {
             for (int i = 0; i < packet_ptr->nodes ().size (); ++i)
             {
                 const protocol::TMLedgerNode& node = packet_ptr->nodes (i);
                 if (!node.has_nodeid () || !node.has_nodedata ())
                     return;
                 Serializer s;
                 SHAMapTreeNode newNode(
                     SHAMapNode (node.nodeid().data(), node.nodeid().size()),
                     Blob (node.nodedata().begin(), node.nodedata().end()),
                     0, snfWIRE, uZero, false);
                 newNode.addRaw(s, snfPREFIX);
                 boost::shared_ptr<Blob> blob = boost::make_shared<Blob> (s.begin(), s.end());
                 getApp().getOPs().addFetchPack (newNode.getNodeHash(), blob);
             }
         }
         catch (...)
         {
         }
     }
bool ripple::InboundLedgersImp::hasLedger (LedgerHash const & hash) inline virtual
Implements ripple::InboundLedgers.
Definition at line 124 of file InboundLedgers.cpp.
References ripple::base_uint< BITS >::isNonZero(), mLedgers, and mLock.
     {
         assert (hash.isNonZero ());
         ScopedLockType sl (mLock);
         return mLedgers.find (hash) != mLedgers.end ();
     }
bool ripple::InboundLedgersImp::isFailure (uint256 const & h) inline virtual
Implements ripple::InboundLedgers.
Definition at line 221 of file InboundLedgers.cpp.
References mRecentFailures.
     {
         return mRecentFailures.exists (h);
     }
void ripple::InboundLedgersImp::logFailure (uint256 const & h) inline virtual
Implements ripple::InboundLedgers.
Definition at line 216 of file InboundLedgers.cpp.
References mRecentFailures.
     {
         mRecentFailures.insert (h);
     }
void ripple::InboundLedgersImp::onStop () inline virtual
Override called when the stop notification is issued.
The call is made on an unspecified, implementation-specific thread. onStop and onChildrenStopped will never be called concurrently, across all Stoppable objects descended from the same root, inclusive of the root.
It is safe to call isStopping, isStopped, and areChildrenStopped from within this function; The values returned will always be valid and never change during the callback.
The default implementation simply calls stopped(). This is applicable when the Stoppable has a trivial stop operation (or no stop operation), and we are merely using the Stoppable API to position it as a dependency of some parent service.
Thread safety: May not block for long periods. Guaranteed only to be called once. Must be safe to call from any thread at any time.
Reimplemented from beast::Stoppable.
Definition at line 364 of file InboundLedgers.cpp.
References mLedgers, mLock, mRecentFailures, and beast::Stoppable::stopped().
     {
         ScopedLockType lock (mLock);
         mLedgers.clear();
         mRecentFailures.clear();
         stopped();
     }
void ripple::InboundLedgersImp::sweep () inline virtual
Implements ripple::InboundLedgers.
Definition at line 323 of file InboundLedgers.cpp.
References ripple::lsDEBUG, m_clock, mLedgers, mLock, mRecentFailures, beast::abstract_clock< Duration >::now(), and WriteLog.
     {
         mRecentFailures.sweep ();
         clock_type::time_point const now (m_clock.now());
         // Make a list of things to sweep, while holding the lock
         std::vector <MapType::mapped_type> stuffToSweep;
         std::size_t total;
         {
             ScopedLockType sl (mLock);
             MapType::iterator it (mLedgers.begin ());
             total = mLedgers.size ();
             stuffToSweep.reserve (total);
             while (it != mLedgers.end ())
             {
                 if (it->second->getLastAction () > now)
                 {
                     it->second->touch ();
                     ++it;
                 }
                 else if ((it->second->getLastAction () + std::chrono::minutes (1)) < now)
                 {
                     stuffToSweep.push_back (it->second);
                     // shouldn't cause the actual final delete
                     // since we are holding a reference in the vector.
                     it = mLedgers.erase (it);
                 }
                 else
                 {
                     ++it;
                 }
             }
         }
         WriteLog (lsDEBUG, InboundLedger) <<
             "Sweeped " << stuffToSweep.size () <<
             " out of " << total << " inbound ledgers.";
     }
Member Data Documentation
const int ripple::InboundLedgersImp::kReacquireIntervalSeconds = 300 static
Definition at line 30 of file InboundLedgers.cpp.
clock_type& ripple::InboundLedgersImp::m_clock private
Definition at line 375 of file InboundLedgers.cpp.
Referenced by findCreate(), and sweep().
uint256 ripple::InboundLedgersImp::mConsensusLedger private
Definition at line 386 of file InboundLedgers.cpp.
Referenced by findCreate().
beast::insight::Counter ripple::InboundLedgersImp::mCounter private
Definition at line 389 of file InboundLedgers.cpp.
Referenced by findCreate().
MapType ripple::InboundLedgersImp::mLedgers private
Definition at line 383 of file InboundLedgers.cpp.
Referenced by clearFailures(), dropLedger(), find(), findCreate(), getFetchCount(), getInfo(), gotFetchPack(), hasLedger(), onStop(), and sweep().
LockType ripple::InboundLedgersImp::mLock private
Definition at line 381 of file InboundLedgers.cpp.
Referenced by clearFailures(), dropLedger(), find(), findCreate(), getFetchCount(), getInfo(), gotFetchPack(), hasLedger(), onStop(), and sweep().
KeyCache<uint256> ripple::InboundLedgersImp::mRecentFailures private
Definition at line 384 of file InboundLedgers.cpp.
Referenced by clearFailures(), isFailure(), logFailure(), onStop(), and sweep().
uint256 ripple::InboundLedgersImp::mValidationLedger private
Definition at line 387 of file InboundLedgers.cpp.
Referenced by findCreate().
The documentation for this class was generated from the following file:
rippled/src/ripple_app/ledger/InboundLedgers.cpp