rippled: rocksdb::RandomGenerator Class Reference
rocksdb::RandomGenerator Class Reference
Public Member Functions
RandomGenerator ()
Slice Generate (unsigned int len)
Private Attributes
std::string data_
unsigned int pos_
Detailed Description
Definition at line 497 of file db_bench.cc.
Constructor & Destructor Documentation
rocksdb::RandomGenerator::RandomGenerator () inline
Definition at line 503 of file db_bench.cc.
References rocksdb::test::CompressibleString(), data_, ripple::max(), and pos_.
                     {
     // We use a limited amount of data over and over again and ensure
     // that it is larger than the compression window (32KB), and also
     // large enough to serve all typical value sizes we want to write.
     Random rnd(301);
     std::string piece;
     while (data_.size() < (unsigned)std::max(1048576, FLAGS_value_size)) {
       // Add a short fragment that is as compressible as specified
       // by FLAGS_compression_ratio.
       test::CompressibleString(&rnd, FLAGS_compression_ratio, 100, &piece);
       data_.append(piece);
     }
     pos_ = 0;
   }
Member Function Documentation
Slice rocksdb::RandomGenerator::Generate (unsigned int len) inline
Definition at line 518 of file db_bench.cc.
References data_, and pos_.
Referenced by rocksdb::Benchmark::AppendRandom(), rocksdb::Benchmark::DoWrite(), rocksdb::Benchmark::MergeRandom(), rocksdb::Benchmark::RandomWithVerify(), rocksdb::Benchmark::ReadRandomWriteRandom(), rocksdb::Benchmark::ReadRandomWriteRandomMultiGet(), rocksdb::Benchmark::ReadWhileWriting(), rocksdb::Benchmark::SnappyCompress(), rocksdb::Benchmark::SnappyUncompress(), and rocksdb::Benchmark::UpdateRandom().
{
     if (pos_ + len > data_.size()) {
       pos_ = 0;
       assert(len < data_.size());
     }
     pos_ += len;
     return Slice(data_.data() + pos_ - len, len);
   }
Member Data Documentation
std::string rocksdb::RandomGenerator::data_ private
Definition at line 499 of file db_bench.cc.
Referenced by Generate(), and RandomGenerator().
unsigned int rocksdb::RandomGenerator::pos_ private
Definition at line 500 of file db_bench.cc.
Referenced by Generate(), and RandomGenerator().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/db/db_bench.cc