rippled: Json::Value Class Reference
Json::Value Class Reference
Represents a JSON value.
#include <json_value.h>
Classes
struct CommentInfo
class CZString
union ValueHolder
Public Types
typedef std::vector< std::string > Members
typedef ValueIterator iterator
typedef ValueConstIterator const_iterator
typedef Json::UInt UInt
typedef Json::Int Int
typedef UInt ArrayIndex
typedef std::map< CZString, Value > ObjectValues
Public Member Functions
Value (ValueType type=nullValue)
Create a default Value of the given type.
Value (Int value)
Value (UInt value)
Value (double value)
Value (const char *value)
Value (const char *beginValue, const char *endValue)
Value (const StaticString &value)
Constructs a value from a static string.
Value (const std::string &value)
Value (beast::String const &beastString)
Value (bool value)
Value (const Value &other)
~Value ()
Value & operator= (const Value &other)
Value (Value &&other)
Value & operator= (Value &&other)
void swap (Value &other)
ValueType type () const
bool operator< (const Value &other) const
bool operator<= (const Value &other) const
bool operator>= (const Value &other) const
bool operator> (const Value &other) const
bool operator== (const Value &other) const
bool operator!= (const Value &other) const
int compare (const Value &other)
const char * asCString () const
std::string asString () const
Int asInt () const
UInt asUInt () const
double asDouble () const
bool asBool () const
bool isNull () const
bool isBool () const
bool isInt () const
bool isUInt () const
bool isIntegral () const
bool isDouble () const
bool isNumeric () const
bool isString () const
bool isArray () const
bool isObject () const
bool isConvertibleTo (ValueType other) const
UInt size () const
Number of values in array or object.
bool empty () const
Return true if empty array, empty object, or null; otherwise, false.
bool operator! () const
Return isNull()
void clear ()
void resize (UInt size)
Value & operator[] (UInt index)
const Value & operator[] (UInt index) const
Value get (UInt index, const Value &defaultValue) const
bool isValidIndex (UInt index) const
Return true if index < size().
Value & append (const Value &value)
Append value to array at the end.
Value & operator[] (const char *key)
Access an object value by name, create a null member if it does not exist.
const Value & operator[] (const char *key) const
Access an object value by name, returns null if there is no member with that name.
Value & operator[] (const std::string &key)
Access an object value by name, create a null member if it does not exist.
const Value & operator[] (const std::string &key) const
Access an object value by name, returns null if there is no member with that name.
Value & operator[] (const StaticString &key)
Access an object value by name, create a null member if it does not exist.
Value get (const char *key, const Value &defaultValue) const
Return the member named key if it exist, defaultValue otherwise.
Value get (const std::string &key, const Value &defaultValue) const
Return the member named key if it exist, defaultValue otherwise.
Value removeMember (const char *key)
Remove and return the named member.
Value removeMember (const std::string &key)
Same as removeMember(const char*)
bool isMember (const char *key) const
Return true if the object has a member named key.
bool isMember (const std::string &key) const
Return true if the object has a member named key.
Members getMemberNames () const
Return a list of the member names.
void setComment (const char *comment, CommentPlacement placement)
Comments must be //... or /* ... */.
void setComment (const std::string &comment, CommentPlacement placement)
Comments must be //... or /* ... */.
bool hasComment (CommentPlacement placement) const
std::string getComment (CommentPlacement placement) const
Include delimiters and embedded newlines.
std::string toStyledString () const
const_iterator begin () const
const_iterator end () const
iterator begin ()
iterator end ()
Static Public Attributes
static const Value null
static const Int minInt = Int (~ (UInt (-1) / 2))
static const Int maxInt = Int (UInt (-1) / 2)
static const UInt maxUInt = UInt (-1)
Private Member Functions
Value & resolveReference (const char *key, bool isStatic)
Private Attributes
union Json::Value::ValueHolder value_
ValueType type_: 8
int allocated_: 1
CommentInfo * comments_
Friends
class ValueIteratorBase
Detailed Description
Represents a JSON value.
This class is a discriminated union wrapper that can represents a:
signed integer [range: Value::minInt - Value::maxInt]
unsigned integer (range: 0 - Value::maxUInt)
double
UTF-8 string
boolean
'null'
an ordered list of Value
collection of name/value pairs (javascript object)
The type of the held value is represented by a ValueType and can be obtained using type().
values of an objectValue or arrayValue can be accessed using operator[]() methods. Non const methods will automatically create the a nullValue element if it does not exist. The sequence of an arrayValue will be automatically resize and initialized with nullValue. resize() can be used to enlarge or truncate an arrayValue.
The get() methods can be used to obtanis default value in the case the required element does not exist.
It is possible to iterate over the list of a objectValue values using the getMemberNames() method.
Definition at line 118 of file json_value.h.
Member Typedef Documentation
typedef UInt Json::Value::ArrayIndex
Definition at line 131 of file json_value.h.
typedef ValueConstIterator Json::Value::const_iterator
Definition at line 128 of file json_value.h.
typedef Json::Int Json::Value::Int
Definition at line 130 of file json_value.h.
typedef ValueIterator Json::Value::iterator
Definition at line 127 of file json_value.h.
typedef std::vector<std::string> Json::Value::Members
Definition at line 126 of file json_value.h.
typedef std::map<CZString, Value> Json::Value::ObjectValues
Definition at line 168 of file json_value.h.
typedef Json::UInt Json::Value::UInt
Definition at line 129 of file json_value.h.
Constructor & Destructor Documentation
Json::Value::Value (ValueType type = nullValue)
Create a default Value of the given type.
This is a very useful constructor. To create an empty array, pass arrayValue. To create an empty object, pass objectValue. Another Value can then be set to this one by assignment. This is useful since clear() and resize() will not alter types.
   Examples:
Json::Value null_value; // null
Json::Value arr_value(Json::arrayValue); // []
Json::Value obj_value(Json::objectValue); // {}
Definition at line 274 of file json_value.cpp.
Referenced by operator[](), resize(), and resolveReference().
     : type_ ( type )
     , allocated_ ( 0 )
     , comments_ ( 0 )
 # ifdef JSON_VALUE_USE_INTERNAL_MAP
     , itemIsUsed_ ( 0 )
 #endif
 {
     switch ( type )
     {
     case nullValue:
         break;
     case intValue:
     case uintValue:
         value_.int_ = 0;
         break;
     case realValue:
         value_.real_ = 0.0;
         break;
     case stringValue:
         value_.string_ = 0;
         break;
 #ifndef JSON_VALUE_USE_INTERNAL_MAP
     case arrayValue:
     case objectValue:
         value_.map_ = new ObjectValues ();
         break;
 #else
     case arrayValue:
         value_.array_ = arrayAllocator ()->newArray ();
         break;
     case objectValue:
         value_.map_ = mapAllocator ()->newMap ();
         break;
 #endif
     case booleanValue:
         value_.bool_ = false;
         break;
     default:
         JSON_ASSERT_UNREACHABLE;
     }
 }
Json::Value::Value (Int value)
Definition at line 326 of file json_value.cpp.
     : type_ ( intValue )
     , comments_ ( 0 )
 # ifdef JSON_VALUE_USE_INTERNAL_MAP
     , itemIsUsed_ ( 0 )
 #endif
 {
     value_.int_ = value;
 }
Json::Value::Value (UInt value)
Definition at line 337 of file json_value.cpp.
     : type_ ( uintValue )
     , comments_ ( 0 )
 # ifdef JSON_VALUE_USE_INTERNAL_MAP
     , itemIsUsed_ ( 0 )
 #endif
 {
     value_.uint_ = value;
 }
Json::Value::Value (double value)
Definition at line 347 of file json_value.cpp.
References Json::Value::ValueHolder::real_, value, and value_.
     : type_ ( realValue )
     , comments_ ( 0 )
 # ifdef JSON_VALUE_USE_INTERNAL_MAP
     , itemIsUsed_ ( 0 )
 #endif
 {
     value_.real_ = value;
 }
Json::Value::Value (const char * value)
Definition at line 357 of file json_value.cpp.
References Json::ValueAllocator::duplicateStringValue(), Json::Value::ValueHolder::string_, value_, and Json::valueAllocator().
     : type_ ( stringValue )
     , allocated_ ( true )
     , comments_ ( 0 )
 # ifdef JSON_VALUE_USE_INTERNAL_MAP
     , itemIsUsed_ ( 0 )
 #endif
 {
     value_.string_ = valueAllocator ()->duplicateStringValue ( value );
 }
Json::Value::Value (const char * beginValue, const char * endValue)
Definition at line 369 of file json_value.cpp.
References Json::ValueAllocator::duplicateStringValue(), Json::Value::ValueHolder::string_, value_, and Json::valueAllocator().
     : type_ ( stringValue )
     , allocated_ ( true )
     , comments_ ( 0 )
 # ifdef JSON_VALUE_USE_INTERNAL_MAP
     , itemIsUsed_ ( 0 )
 #endif
 {
     value_.string_ = valueAllocator ()->duplicateStringValue ( beginValue,
                      UInt (endValue - beginValue) );
 }
Json::Value::Value (const StaticString & value)
Constructs a value from a static string.
Like other value string constructor but do not duplicate the string for internal storage. The given string must remain alive after the call to this constructor. Example of usage:
Json::Value aValue(StaticString("some text"));
Definition at line 409 of file json_value.cpp.
References Json::StaticString::c_str(), Json::Value::ValueHolder::string_, and value_.
     : type_ ( stringValue )
     , allocated_ ( false )
     , comments_ ( 0 )
 # ifdef JSON_VALUE_USE_INTERNAL_MAP
     , itemIsUsed_ ( 0 )
 #endif
 {
     value_.string_ = const_cast<char*> ( value.c_str () );
 }
Json::Value::Value (const std::string & value)
Definition at line 383 of file json_value.cpp.
References Json::ValueAllocator::duplicateStringValue(), Json::Value::ValueHolder::string_, value_, and Json::valueAllocator().
     : type_ ( stringValue )
     , allocated_ ( true )
     , comments_ ( 0 )
 # ifdef JSON_VALUE_USE_INTERNAL_MAP
     , itemIsUsed_ ( 0 )
 #endif
 {
     value_.string_ = valueAllocator ()->duplicateStringValue ( value.c_str (),
                      (unsigned int)value.length () );
 }
Json::Value::Value (beast::String const & beastString)
Definition at line 396 of file json_value.cpp.
References Json::ValueAllocator::duplicateStringValue(), beast::String::length(), Json::Value::ValueHolder::string_, beast::String::toStdString(), value_, and Json::valueAllocator().
     : type_ ( stringValue )
     , allocated_ ( true )
     , comments_ ( 0 )
 # ifdef JSON_VALUE_USE_INTERNAL_MAP
     , itemIsUsed_ ( 0 )
 #endif
 {
     value_.string_ = valueAllocator ()->duplicateStringValue ( beastString.toStdString ().c_str (),
                      (unsigned int)beastString.length () );
 }
Json::Value::Value (bool value)
Definition at line 434 of file json_value.cpp.
References Json::Value::ValueHolder::bool_, value, and value_.
     : type_ ( booleanValue )
     , comments_ ( 0 )
 # ifdef JSON_VALUE_USE_INTERNAL_MAP
     , itemIsUsed_ ( 0 )
 #endif
 {
     value_.bool_ = value;
 }
Json::Value::Value (const Value & other)
Definition at line 445 of file json_value.cpp.
References allocated_, arrayAllocator(), Json::arrayValue, Json::booleanValue, Json::Value::CommentInfo::comment_, comments_, Json::ValueAllocator::duplicateStringValue(), Json::intValue, JSON_ASSERT_UNREACHABLE, Json::Value::ValueHolder::map_, mapAllocator(), Json::nullValue, Json::numberOfCommentPlacement, Json::objectValue, Json::realValue, Json::Value::CommentInfo::setComment(), Json::Value::ValueHolder::string_, Json::stringValue, type_, Json::uintValue, value_, and Json::valueAllocator().
     : type_ ( other.type_ )
     , comments_ ( 0 )
 # ifdef JSON_VALUE_USE_INTERNAL_MAP
     , itemIsUsed_ ( 0 )
 #endif
 {
     switch ( type_ )
     {
     case nullValue:
     case intValue:
     case uintValue:
     case realValue:
     case booleanValue:
         value_ = other.value_;
         break;
     case stringValue:
         if ( other.value_.string_ )
         {
             value_.string_ = valueAllocator ()->duplicateStringValue ( other.value_.string_ );
             allocated_ = true;
         }
         else
             value_.string_ = 0;
         break;
 #ifndef JSON_VALUE_USE_INTERNAL_MAP
     case arrayValue:
     case objectValue:
         value_.map_ = new ObjectValues ( *other.value_.map_ );
         break;
 #else
     case arrayValue:
         value_.array_ = arrayAllocator ()->newArrayCopy ( *other.value_.array_ );
         break;
     case objectValue:
         value_.map_ = mapAllocator ()->newMapCopy ( *other.value_.map_ );
         break;
 #endif
     default:
         JSON_ASSERT_UNREACHABLE;
     }
     if ( other.comments_ )
     {
         comments_ = new CommentInfo[numberOfCommentPlacement];
         for ( int comment = 0; comment < numberOfCommentPlacement; ++comment )
         {
             const CommentInfo& otherComment = other.comments_[comment];
             if ( otherComment.comment_ )
                 comments_[comment].setComment ( otherComment.comment_ );
         }
     }
 }
Json::Value::~Value ()
Definition at line 508 of file json_value.cpp.
References allocated_, arrayAllocator(), Json::arrayValue, Json::booleanValue, comments_, Json::intValue, JSON_ASSERT_UNREACHABLE, Json::Value::ValueHolder::map_, mapAllocator(), Json::nullValue, Json::objectValue, Json::realValue, Json::ValueAllocator::releaseStringValue(), Json::Value::ValueHolder::string_, Json::stringValue, type_, Json::uintValue, value_, and Json::valueAllocator().
 {
     switch ( type_ )
     {
     case nullValue:
     case intValue:
     case uintValue:
     case realValue:
     case booleanValue:
         break;
     case stringValue:
         if ( allocated_ )
             valueAllocator ()->releaseStringValue ( value_.string_ );
         break;
 #ifndef JSON_VALUE_USE_INTERNAL_MAP
     case arrayValue:
     case objectValue:
         delete value_.map_;
         break;
 #else
     case arrayValue:
         arrayAllocator ()->destructArray ( value_.array_ );
         break;
     case objectValue:
         mapAllocator ()->destructMap ( value_.map_ );
         break;
 #endif
     default:
         JSON_ASSERT_UNREACHABLE;
     }
     if ( comments_ )
         delete[] comments_;
 }
Json::Value::Value (Value && other)
Definition at line 557 of file json_value.cpp.
     : value_ ( other.value_ )
     , type_ ( other.type_ )
     , allocated_ ( other.allocated_ )
 # ifdef JSON_VALUE_USE_INTERNAL_MAP
     , itemIsUsed_ ( other.itemIsUsed_ )
     , memberNameIsStatic_ ( other.memberNameIsStatic_ )
 #endif  // JSON_VALUE_USE_INTERNAL_MAP
     , comments_ ( other.comments_ )
 {
     std::memset( &other, 0, sizeof(Value) );
 }
Member Function Documentation
Value & Json::Value::append (const Value & value)
Append value to array at the end.
Equivalent to jsonvalue[jsonvalue.size()] = value;
Definition at line 1298 of file json_value.cpp.
References size(), and value.
Referenced by ripple::RPC::accounts(), ripple::JsonPropertyStream::array_begin(), ripple::AcceptedLedgerTx::buildJson(), ripple::RPCHandler::doAccountCurrencies(), ripple::RPCHandler::doAccountLines(), ripple::RPCHandler::doAccountTx(), ripple::RPCHandler::doAccountTxOld(), ripple::RPCHandler::doLedgerData(), ripple::RPCHandler::doRipplePathFind(), ripple::RPCHandler::doTxHistory(), ripple::PathRequest::doUpdate(), ripple::RPCCall::fromCommandLine(), ripple::NetworkOPsImp::getBookPage(), ripple::PathState::Node::getJson(), ripple::AccountItems::getJson(), ripple::InboundLedger::getJson(), ripple::LedgerConsensusImp::getJson(), ripple::PathState::getJson(), ripple::LedgerEntrySet::getJson(), ripple::JobQueueImp::getJson(), ripple::Ledger::getJson(), ripple::STArray::getJson(), ripple::STPath::getJson(), ripple::STPathSet::getJson(), ripple::STVector256::getJson(), ripple::NetworkOPsImp::getOwnerInfo(), ripple::UniqueNodeListImp::getUnlJson(), ripple::PathRequest::isValid(), ripple::Config::load(), ripple::JsonPropertyStream::map_begin(), ripple::offerAdder(), ripple::get_peer_json::operator()(), ripple::RPCParser::parseInternal(), ripple::ParameterNode::setValue(), ripple::stateItemFullAppender(), and ripple::stateItemTagAppender().
 {
     return (*this)[size ()] = value;
 }
bool Json::Value::asBool () const
Definition at line 929 of file json_value.cpp.
References Json::arrayValue, Json::Value::ValueHolder::bool_, Json::booleanValue, Json::Value::ValueHolder::int_, Json::intValue, JSON_ASSERT_UNREACHABLE, Json::Value::ValueHolder::map_, Json::nullValue, Json::objectValue, Json::Value::ValueHolder::real_, Json::realValue, Json::Value::ValueHolder::string_, Json::stringValue, type_, Json::uintValue, and value_.
Referenced by ripple::RPCHandler::doAccountCurrencies(), ripple::RPCHandler::doAccountInfo(), ripple::RPCHandler::doAccountTx(), ripple::RPCHandler::doAccountTxOld(), ripple::LedgerCleanerImp::doClean(), ripple::RPCHandler::doFetchInfo(), ripple::RPCHandler::doLedger(), ripple::RPCHandler::doLedgerData(), ripple::RPCHandler::doSign(), ripple::RPCHandler::doSubmit(), ripple::RPCHandler::doSubscribe(), ripple::RPCHandler::doTx(), ripple::RPCHandler::doUnsubscribe(), ripple::RPC::transactionSign(), Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), and Json::StyledStreamWriter::writeValue().
 {
     switch ( type_ )
     {
     case nullValue:
         return false;
     case intValue:
     case uintValue:
         return value_.int_ != 0;
     case realValue:
         return value_.real_ != 0.0;
     case booleanValue:
         return value_.bool_;
     case stringValue:
         return value_.string_  &&  value_.string_[0] != 0;
     case arrayValue:
     case objectValue:
         return value_.map_->size () != 0;
     default:
         JSON_ASSERT_UNREACHABLE;
     }
     return false; // unreachable;
 }
const char * Json::Value::asCString () const
Definition at line 779 of file json_value.cpp.
References JSON_ASSERT, Json::Value::ValueHolder::string_, Json::stringValue, type_, and value_.
Referenced by Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), and Json::StyledStreamWriter::writeValue().
 {
     JSON_ASSERT ( type_ == stringValue );
     return value_.string_;
 }
double Json::Value::asDouble () const
Definition at line 897 of file json_value.cpp.
References Json::arrayValue, Json::Value::ValueHolder::bool_, Json::booleanValue, Json::Value::ValueHolder::int_, Json::intValue, JSON_ASSERT_MESSAGE, JSON_ASSERT_UNREACHABLE, Json::nullValue, Json::objectValue, Json::Value::ValueHolder::real_, Json::realValue, Json::stringValue, type_, Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
Referenced by ripple::JsonCpp_test::test_copy(), ripple::JsonCpp_test::test_move(), Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), and Json::StyledStreamWriter::writeValue().
 {
     switch ( type_ )
     {
     case nullValue:
         return 0.0;
     case intValue:
         return value_.int_;
     case uintValue:
         return value_.uint_;
     case realValue:
         return value_.real_;
     case booleanValue:
         return value_.bool_ ? 1.0 : 0.0;
     case stringValue:
     case arrayValue:
     case objectValue:
         JSON_ASSERT_MESSAGE ( false, "Type is not convertible to double" );
     default:
         JSON_ASSERT_UNREACHABLE;
     }
     return 0; // unreachable;
 }
Value::Int Json::Value::asInt () const
Definition at line 825 of file json_value.cpp.
References Json::arrayValue, Json::Value::ValueHolder::bool_, Json::booleanValue, Json::Value::ValueHolder::int_, Json::intValue, JSON_ASSERT_MESSAGE, JSON_ASSERT_UNREACHABLE, maxInt, minInt, Json::nullValue, Json::objectValue, Json::Value::ValueHolder::real_, Json::realValue, Json::Value::ValueHolder::string_, Json::stringValue, type_, Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
Referenced by ripple::RPC::autofill_fee(), ripple::RPCHandler::doAccountTx(), ripple::RPCHandler::doAccountTxOld(), ripple::RPCHandler::doLedgerData(), ripple::RPCHandler::doProofVerify(), ripple::RPCHandler::doRipplePathFind(), ripple::ErrorReply(), ripple::NetworkOPsImp::getTxsAccount(), ripple::NetworkOPsImp::getTxsAccountB(), ripple::RPC::lookupLedger(), ripple::STParsedJSON::parse(), ripple::RPCParser::parseAccountTransactions(), ripple::RPCParser::parseBookOffers(), ripple::RPCParser::parseTxAccount(), ripple::ParameterInt::setValue(), ripple::STAmount::STAmount(), Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), and Json::StyledStreamWriter::writeValue().
 {
     switch ( type_ )
     {
     case nullValue:
         return 0;
     case intValue:
         return value_.int_;
     case uintValue:
         JSON_ASSERT_MESSAGE ( value_.uint_ < (unsigned)maxInt, "integer out of signed integer range" );
         return value_.uint_;
     case realValue:
         JSON_ASSERT_MESSAGE ( value_.real_ >= minInt  &&  value_.real_ <= maxInt, "Real out of signed integer range" );
         return Int ( value_.real_ );
     case booleanValue:
         return value_.bool_ ? 1 : 0;
     case stringValue:
         return beast::lexicalCastThrow <int> (value_.string_);
     case arrayValue:
     case objectValue:
         JSON_ASSERT_MESSAGE ( false, "Type is not convertible to int" );
     default:
         JSON_ASSERT_UNREACHABLE;
     }
     return 0; // unreachable;
 }
std::string Json::Value::asString () const
Definition at line 787 of file json_value.cpp.
References Json::arrayValue, Json::Value::ValueHolder::bool_, Json::booleanValue, Json::Value::ValueHolder::int_, Json::intValue, JSON_ASSERT_MESSAGE, JSON_ASSERT_UNREACHABLE, Json::nullValue, Json::objectValue, Json::realValue, Json::Value::ValueHolder::string_, Json::stringValue, type_, Json::uintValue, and value_.
Referenced by ripple::WSServerHandler< endpoint_type >::do_message(), ripple::RPCHandler::doAccountCurrencies(), ripple::RPCHandler::doAccountInfo(), ripple::RPCHandler::doAccountLines(), ripple::RPCHandler::doAccountOffers(), ripple::RPCHandler::doAccountTx(), ripple::RPCHandler::doAccountTxOld(), ripple::RPCHandler::doBookOffers(), ripple::RPCHandler::doCommand(), ripple::RPCHandler::doLedgerData(), ripple::RPCHandler::doLedgerEntry(), ripple::RPCHandler::doOwnerInfo(), ripple::RPCHandler::doPathFind(), ripple::RPCHandler::doProofSolve(), ripple::RPCHandler::doProofVerify(), ripple::RPCHandler::doRipplePathFind(), ripple::RPCHandler::doSubscribe(), ripple::RPCHandler::doTx(), ripple::RPCHandler::doUnlAdd(), ripple::RPCHandler::doUnlDelete(), ripple::RPCHandler::doUnsubscribe(), ripple::RPCHandler::doValidationCreate(), ripple::RPCHandler::doValidationSeed(), ripple::RPCHandler::doWalletPropose(), ripple::RPCHandler::doWalletSeed(), ripple::RPCCall::fromCommandLine(), ripple::Config::getAdminRole(), ripple::RPC::lookupLedger(), ripple::RPC::DoPrint::operator()(), ripple::STParsedJSON::parse(), ripple::RPCParser::parseAccountRaw(), ripple::RPCParser::parseAccountTransactions(), ripple::RPCParser::parseBookOffers(), ripple::RPCParser::parseConnect(), ripple::RPCParser::parseFetchInfo(), ripple::PathRequest::parseJson(), ripple::RPCParser::parseJson(), ripple::RPCParser::parseLedger(), ripple::RPCParser::parseLedgerId(), ripple::RPCParser::parseLogLevel(), ripple::RPCParser::parseProofSolve(), ripple::RPCParser::parseProofVerify(), ripple::RPCParser::parseRipplePathFind(), ripple::RPCParser::parseSignSubmit(), ripple::RPCParser::parseSMS(), ripple::RPCParser::parseTx(), ripple::RPCParser::parseTxAccount(), ripple::RPCParser::parseUnlAdd(), ripple::RPCParser::parseUnlDelete(), ripple::RPCParser::parseWalletAccounts(), ripple::RPCServerHandler::processRequest(), ripple::RPCHTTPServerImp::processRequest(), ripple::DirectoryEntryIterator::setJson(), ripple::BookDirIterator::setJson(), ripple::ParameterString::setValue(), ripple::ParameterInt::setValue(), ripple::STAmount::STAmount(), and ripple::RPC::transactionSign().
 {
     switch ( type_ )
     {
     case nullValue:
         return "";
     case stringValue:
         return value_.string_ ? value_.string_ : "";
     case booleanValue:
         return value_.bool_ ? "true" : "false";
     case intValue:
         return beast::lexicalCastThrow <std::string> (value_.int_);
     case uintValue:
     case realValue:
     case arrayValue:
     case objectValue:
         JSON_ASSERT_MESSAGE ( false, "Type is not convertible to string" );
     default:
         JSON_ASSERT_UNREACHABLE;
     }
     return ""; // unreachable
 }
Value::UInt Json::Value::asUInt () const
Definition at line 861 of file json_value.cpp.
References Json::arrayValue, Json::Value::ValueHolder::bool_, Json::booleanValue, Json::Value::ValueHolder::int_, Json::intValue, JSON_ASSERT_MESSAGE, JSON_ASSERT_UNREACHABLE, maxUInt, Json::nullValue, Json::objectValue, Json::Value::ValueHolder::real_, Json::realValue, Json::Value::ValueHolder::string_, Json::stringValue, type_, Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
Referenced by ripple::RPCHandler::doAccountCurrencies(), ripple::RPCHandler::doAccountInfo(), ripple::RPCHandler::doAccountLines(), ripple::RPCHandler::doAccountOffers(), ripple::RPCHandler::doAccountTx(), ripple::RPCHandler::doAccountTxOld(), ripple::RPCHandler::doBookOffers(), ripple::LedgerCleanerImp::doClean(), ripple::RPCHandler::doLedgerEntry(), ripple::RPCHandler::doOwnerInfo(), ripple::RPCHandler::doSubscribe(), ripple::RPCHandler::doTxHistory(), ripple::STParsedJSON::parse(), ripple::RPCParser::parseTxHistory(), ripple::DirectoryEntryIterator::setJson(), ripple::STAmount::STAmount(), Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), and Json::StyledStreamWriter::writeValue().
 {
     switch ( type_ )
     {
     case nullValue:
         return 0;
     case intValue:
         JSON_ASSERT_MESSAGE ( value_.int_ >= 0, "Negative integer can not be converted to unsigned integer" );
         return value_.int_;
     case uintValue:
         return value_.uint_;
     case realValue:
         JSON_ASSERT_MESSAGE ( value_.real_ >= 0  &&  value_.real_ <= maxUInt,  "Real out of unsigned integer range" );
         return UInt ( value_.real_ );
     case booleanValue:
         return value_.bool_ ? 1 : 0;
     case stringValue:
         return beast::lexicalCastThrow <unsigned int> (value_.string_);
     case arrayValue:
     case objectValue:
         JSON_ASSERT_MESSAGE ( false, "Type is not convertible to uint" );
     default:
         JSON_ASSERT_UNREACHABLE;
     }
     return 0; // unreachable;
 }
Value::const_iterator Json::Value::begin () const
Definition at line 1565 of file json_value.cpp.
References Json::arrayValue, Json::Value::ValueHolder::map_, Json::objectValue, type_, and value_.
Referenced by ripple::RPC::parseAccountIds().
 {
     switch ( type_ )
     {
 #ifdef JSON_VALUE_USE_INTERNAL_MAP
     case arrayValue:
         if ( value_.array_ )
         {
             ValueInternalArray::IteratorState it;
             value_.array_->makeBeginIterator ( it );
             return const_iterator ( it );
         }
         break;
     case objectValue:
         if ( value_.map_ )
         {
             ValueInternalMap::IteratorState it;
             value_.map_->makeBeginIterator ( it );
             return const_iterator ( it );
         }
         break;
 #else
     case arrayValue:
     case objectValue:
         if ( value_.map_ )
             return const_iterator ( value_.map_->begin () );
         break;
 #endif
     default:
         break;
     }
     return const_iterator ();
 }
Value::iterator Json::Value::begin ()
Definition at line 1652 of file json_value.cpp.
References Json::arrayValue, Json::Value::ValueHolder::map_, Json::objectValue, type_, and value_.
 {
     switch ( type_ )
     {
 #ifdef JSON_VALUE_USE_INTERNAL_MAP
     case arrayValue:
         if ( value_.array_ )
         {
             ValueInternalArray::IteratorState it;
             value_.array_->makeBeginIterator ( it );
             return iterator ( it );
         }
         break;
     case objectValue:
         if ( value_.map_ )
         {
             ValueInternalMap::IteratorState it;
             value_.map_->makeBeginIterator ( it );
             return iterator ( it );
         }
         break;
 #else
     case arrayValue:
     case objectValue:
         if ( value_.map_ )
             return iterator ( value_.map_->begin () );
         break;
 #endif
     default:
         break;
     }
     return iterator ();
 }
void Json::Value::clear ()
Remove all object members and array elements.
Precondition
type() is arrayValue, objectValue, or nullValue
Postcondition
type() is unchanged
Definition at line 1083 of file json_value.cpp.
References Json::arrayValue, JSON_ASSERT, Json::Value::ValueHolder::map_, Json::nullValue, Json::objectValue, type_, and value_.
Referenced by resize().
 {
     JSON_ASSERT ( type_ == nullValue  ||  type_ == arrayValue  || type_ == objectValue );
     switch ( type_ )
     {
 #ifndef JSON_VALUE_USE_INTERNAL_MAP
     case arrayValue:
     case objectValue:
         value_.map_->clear ();
         break;
 #else
     case arrayValue:
         value_.array_->clear ();
         break;
     case objectValue:
         value_.map_->clear ();
         break;
 #endif
     default:
         break;
     }
 }
int Json::Value::compare (const Value & other)
Definition at line 610 of file json_value.cpp.
 {
     /*
     int typeDelta = other.type_ - type_;
     switch ( type_ )
     {
     case nullValue:
        return other.type_ == type_;
     case intValue:
        if ( other.type_.isNumeric()
     case uintValue:
     case realValue:
     case booleanValue:
        break;
     case stringValue,
        break;
     case arrayValue:
        delete value_.array_;
        break;
     case objectValue:
        delete value_.map_;
     default:
        JSON_ASSERT_UNREACHABLE;
     }
     */
     return 0;  // unreachable
 }
bool Json::Value::empty () const
Return true if empty array, empty object, or null; otherwise, false.
Definition at line 1066 of file json_value.cpp.
References isArray(), isNull(), isObject(), and size().
Referenced by ripple::RPC::authorize(), ripple::RPCHandler::doAccountCurrencies(), ripple::RPCHandler::doAccountInfo(), ripple::RPCHandler::doAccountLines(), ripple::RPCHandler::doAccountOffers(), ripple::RPCHandler::doOwnerInfo(), and ripple::RPCHandler::doWalletAccounts().
 {
     if ( isNull () || isArray () || isObject () )
         return size () == 0u;
     else
         return false;
 }
Value::const_iterator Json::Value::end () const
Definition at line 1608 of file json_value.cpp.
References Json::arrayValue, Json::Value::ValueHolder::map_, Json::objectValue, type_, and value_.
Referenced by ripple::RPCHandler::doSubscribe(), ripple::RPCHandler::doUnsubscribe(), and ripple::RPC::parseAccountIds().
 {
     switch ( type_ )
     {
 #ifdef JSON_VALUE_USE_INTERNAL_MAP
     case arrayValue:
         if ( value_.array_ )
         {
             ValueInternalArray::IteratorState it;
             value_.array_->makeEndIterator ( it );
             return const_iterator ( it );
         }
         break;
     case objectValue:
         if ( value_.map_ )
         {
             ValueInternalMap::IteratorState it;
             value_.map_->makeEndIterator ( it );
             return const_iterator ( it );
         }
         break;
 #else
     case arrayValue:
     case objectValue:
         if ( value_.map_ )
             return const_iterator ( value_.map_->end () );
         break;
 #endif
     default:
         break;
     }
     return const_iterator ();
 }
Value::iterator Json::Value::end ()
Definition at line 1695 of file json_value.cpp.
References Json::arrayValue, Json::Value::ValueHolder::map_, Json::objectValue, type_, and value_.
 {
     switch ( type_ )
     {
 #ifdef JSON_VALUE_USE_INTERNAL_MAP
     case arrayValue:
         if ( value_.array_ )
         {
             ValueInternalArray::IteratorState it;
             value_.array_->makeEndIterator ( it );
             return iterator ( it );
         }
         break;
     case objectValue:
         if ( value_.map_ )
         {
             ValueInternalMap::IteratorState it;
             value_.map_->makeEndIterator ( it );
             return iterator ( it );
         }
         break;
 #else
     case arrayValue:
     case objectValue:
         if ( value_.map_ )
             return iterator ( value_.map_->end () );
         break;
 #endif
     default:
         break;
     }
     return iterator ();
 }
Value Json::Value::get (UInt index, const Value & defaultValue) const
If the array contains at least index+1 elements, returns the element value, otherwise returns defaultValue.
Definition at line 1222 of file json_value.cpp.
References null, and value.
Referenced by ripple::RPC::lookupLedger(), and ripple::STAmount::STAmount().
 {
     const Value* value = & ((*this)[index]);
     return value == &null ? defaultValue : *value;
 }
Value Json::Value::get (const char * key, const Value & defaultValue) const
Return the member named key if it exist, defaultValue otherwise.
Definition at line 1305 of file json_value.cpp.
References null, and value.
 {
     const Value* value = & ((*this)[key]);
     return value == &null ? defaultValue : *value;
 }
Value Json::Value::get (const std::string & key, const Value & defaultValue) const
Return the member named key if it exist, defaultValue otherwise.
Definition at line 1314 of file json_value.cpp.
 {
     return get ( key.c_str (), defaultValue );
 }
std::string Json::Value::getComment (CommentPlacement placement) const
Include delimiters and embedded newlines.
Definition at line 1547 of file json_value.cpp.
References Json::Value::CommentInfo::comment_, comments_, and hasComment().
Referenced by Json::StyledWriter::writeCommentAfterValueOnSameLine(), Json::StyledStreamWriter::writeCommentAfterValueOnSameLine(), Json::StyledWriter::writeCommentBeforeValue(), and Json::StyledStreamWriter::writeCommentBeforeValue().
 {
     if ( hasComment (placement) )
         return comments_[placement].comment_;
     return "";
 }
Value::Members Json::Value::getMemberNames () const
Return a list of the member names.
If null, return an empty list.
Precondition
type() is objectValue or nullValue
Postcondition
if type() was nullValue, it remains nullValue
Definition at line 1394 of file json_value.cpp.
References JSON_ASSERT, Json::Value::ValueHolder::map_, Json::nullValue, Json::objectValue, type_, and value_.
Referenced by ripple::STParsedJSON::parse(), Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), and Json::StyledStreamWriter::writeValue().
 {
     JSON_ASSERT ( type_ == nullValue  ||  type_ == objectValue );
     if ( type_ == nullValue )
         return Value::Members ();
     Members members;
     members.reserve ( value_.map_->size () );
 #ifndef JSON_VALUE_USE_INTERNAL_MAP
     ObjectValues::const_iterator it = value_.map_->begin ();
     ObjectValues::const_iterator itEnd = value_.map_->end ();
     for ( ; it != itEnd; ++it )
         members.push_back ( std::string ( (*it).first.c_str () ) );
 #else
     ValueInternalMap::IteratorState it;
     ValueInternalMap::IteratorState itEnd;
     value_.map_->makeBeginIterator ( it );
     value_.map_->makeEndIterator ( itEnd );
     for ( ; !ValueInternalMap::equals ( it, itEnd ); ValueInternalMap::increment (it) )
         members.push_back ( std::string ( ValueInternalMap::key ( it ) ) );
 #endif
     return members;
 }
bool Json::Value::hasComment (CommentPlacement placement) const
Definition at line 1541 of file json_value.cpp.
References Json::Value::CommentInfo::comment_, and comments_.
Referenced by getComment(), Json::StyledWriter::hasCommentForValue(), Json::StyledStreamWriter::hasCommentForValue(), Json::StyledWriter::writeCommentAfterValueOnSameLine(), Json::StyledStreamWriter::writeCommentAfterValueOnSameLine(), Json::StyledWriter::writeCommentBeforeValue(), and Json::StyledStreamWriter::writeCommentBeforeValue().
 {
     return comments_ != 0  &&  comments_[placement].comment_ != 0;
 }
bool Json::Value::isArray () const
Definition at line 1508 of file json_value.cpp.
References Json::arrayValue, Json::nullValue, and type_.
Referenced by ripple::RPCHandler::doLedgerEntry(), ripple::RPCHandler::doPrint(), ripple::RPCHandler::doRipplePathFind(), empty(), Json::StyledWriter::isMultineArray(), Json::StyledStreamWriter::isMultineArray(), Json::Path::make(), ripple::RPC::DoPrint::operator()(), Json::Reader::parse(), ripple::STParsedJSON::parse(), ripple::RPCParser::parseAsIs(), ripple::PathRequest::parseJson(), ripple::RPCServerHandler::processRequest(), ripple::RPCHTTPServerImp::processRequest(), Json::Path::resolve(), and ripple::STAmount::STAmount().
 {
     return type_ == nullValue  ||  type_ == arrayValue;
 }
bool Json::Value::isBool () const
Definition at line 1457 of file json_value.cpp.
References Json::booleanValue, and type_.
Referenced by ripple::RPCHandler::doLedgerData().
 {
     return type_ == booleanValue;
 }
bool Json::Value::isConvertibleTo (ValueType other) const
Definition at line 962 of file json_value.cpp.
References Json::arrayValue, Json::Value::ValueHolder::bool_, Json::booleanValue, Json::Value::ValueHolder::int_, Json::intValue, JSON_ASSERT_UNREACHABLE, Json::Value::ValueHolder::map_, maxInt, maxUInt, minInt, Json::nullValue, Json::objectValue, Json::Value::ValueHolder::real_, Json::realValue, Json::Value::ValueHolder::string_, Json::stringValue, type_, Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
Referenced by ripple::RPCHandler::doConnect(), ripple::ParameterString::setValue(), and ripple::ParameterInt::setValue().
 {
     switch ( type_ )
     {
     case nullValue:
         return true;
     case intValue:
         return ( other == nullValue  &&  value_.int_ == 0 )
                || other == intValue
                || ( other == uintValue  && value_.int_ >= 0 )
                || other == realValue
                || other == stringValue
                || other == booleanValue;
     case uintValue:
         return ( other == nullValue  &&  value_.uint_ == 0 )
                || ( other == intValue  && value_.uint_ <= (unsigned)maxInt )
                || other == uintValue
                || other == realValue
                || other == stringValue
                || other == booleanValue;
     case realValue:
         return ( other == nullValue  &&  value_.real_ == 0.0 )
                || ( other == intValue  &&  value_.real_ >= minInt  &&  value_.real_ <= maxInt )
                || ( other == uintValue  &&  value_.real_ >= 0  &&  value_.real_ <= maxUInt )
                || other == realValue
                || other == stringValue
                || other == booleanValue;
     case booleanValue:
         return ( other == nullValue  &&  value_.bool_ == false )
                || other == intValue
                || other == uintValue
                || other == realValue
                || other == stringValue
                || other == booleanValue;
     case stringValue:
         return other == stringValue
                || ( other == nullValue  &&  (!value_.string_  ||  value_.string_[0] == 0) );
     case arrayValue:
         return other == arrayValue
                ||  ( other == nullValue  &&  value_.map_->size () == 0 );
     case objectValue:
         return other == objectValue
                ||  ( other == nullValue  &&  value_.map_->size () == 0 );
     default:
         JSON_ASSERT_UNREACHABLE;
     }
     return false; // unreachable;
 }
bool Json::Value::isDouble () const
Definition at line 1487 of file json_value.cpp.
References Json::realValue, and type_.
Referenced by isNumeric(), ripple::JsonCpp_test::test_copy(), and ripple::JsonCpp_test::test_move().
 {
     return type_ == realValue;
 }
bool Json::Value::isInt () const
Definition at line 1464 of file json_value.cpp.
References Json::intValue, and type_.
Referenced by ripple::STParsedJSON::parse(), and ripple::STAmount::STAmount().
 {
     return type_ == intValue;
 }
bool Json::Value::isIntegral () const
Definition at line 1478 of file json_value.cpp.
References Json::booleanValue, Json::intValue, type_, and Json::uintValue.
Referenced by ripple::RPCHandler::doBookOffers(), ripple::RPCHandler::doLedgerData(), ripple::RPCHandler::doRipplePathFind(), and isNumeric().
 {
     return type_ == intValue
            ||  type_ == uintValue
            ||  type_ == booleanValue;
 }
bool Json::Value::isMember (const char * key) const
Return true if the object has a member named key.
Definition at line 1371 of file json_value.cpp.
References null.
Referenced by ripple::RPC::autofill_fee(), ripple::RPC::contains_error(), ripple::WSServerHandler< endpoint_type >::do_message(), ripple::RPCHandler::doAccountCurrencies(), ripple::RPCHandler::doAccountInfo(), ripple::RPCHandler::doAccountLines(), ripple::RPCHandler::doAccountOffers(), ripple::RPCHandler::doAccountTx(), ripple::RPCHandler::doAccountTxOld(), ripple::RPCHandler::doAccountTxSwitch(), ripple::RPCHandler::doBlackList(), ripple::RPCHandler::doBookOffers(), ripple::LedgerCleanerImp::doClean(), ripple::RPCHandler::doCommand(), ripple::RPCHandler::doConnect(), ripple::RPCHandler::doFeature(), ripple::RPCHandler::doFetchInfo(), ripple::RPCHandler::doGetCounts(), ripple::RPCHandler::doInternal(), ripple::RPCHandler::doLedger(), ripple::RPCHandler::doLedgerData(), ripple::RPCHandler::doLedgerEntry(), ripple::RPCHandler::doLogLevel(), ripple::RPCHandler::doOwnerInfo(), ripple::RPCHandler::doPathFind(), ripple::RPCHandler::doProofCreate(), ripple::RPCHandler::doProofSolve(), ripple::RPCHandler::doProofVerify(), ripple::RPCHandler::doRipplePathFind(), ripple::RPCHandler::doRpcCommand(), ripple::RPCHandler::doSign(), ripple::RPCHandler::doSMS(), ripple::RPCHandler::doSubmit(), ripple::RPCHandler::doSubscribe(), ripple::RPCHandler::doTransactionEntry(), ripple::RPCHandler::doTx(), ripple::RPCHandler::doTxHistory(), ripple::RPCHandler::doUnlAdd(), ripple::RPCHandler::doUnlDelete(), ripple::RPCHandler::doUnsubscribe(), ripple::RPCHandler::doValidationCreate(), ripple::RPCHandler::doValidationSeed(), ripple::RPCHandler::doWalletAccounts(), ripple::RPCHandler::doWalletPropose(), ripple::RPCHandler::doWalletSeed(), ripple::RPCCall::fromCommandLine(), ripple::Config::getAdminRole(), ripple::NetworkOPsImp::getOwnerInfo(), ripple::NetworkOPsImp::getTxsAccount(), ripple::NetworkOPsImp::getTxsAccountB(), ripple::WSConnection::invokeCommand(), isMember(), ripple::isRpcError(), ripple::RPC::lookupLedger(), ripple::PathRequest::parseJson(), ripple::DirectoryEntryIterator::setJson(), ripple::BookDirIterator::setJson(), and ripple::RPC::transactionSign().
 {
     const Value* value = & ((*this)[key]);
     return value != &null;
 }
bool Json::Value::isMember (const std::string & key) const
Return true if the object has a member named key.
Definition at line 1379 of file json_value.cpp.
References isMember().
 {
     return isMember ( key.c_str () );
 }
bool Json::Value::isNull () const
Definition at line 1450 of file json_value.cpp.
References Json::nullValue, and type_.
Referenced by ripple::WSServerHandler< endpoint_type >::do_message(), ripple::RPCHandler::doAccountTx(), ripple::PathRequest::doUpdate(), empty(), ripple::NetworkOPsImp::getTxsAccount(), ripple::NetworkOPsImp::getTxsAccountB(), ripple::RPCCallImp::onResponse(), operator!(), ripple::STParsedJSON::parse(), ripple::SerializedObject_test::parseJSONString(), ripple::RPCServerHandler::processRequest(), ripple::RPCHTTPServerImp::processRequest(), and ripple::JsonCpp_test::test_move().
 {
     return type_ == nullValue;
 }
bool Json::Value::isNumeric () const
Definition at line 1494 of file json_value.cpp.
References isDouble(), and isIntegral().
Referenced by ripple::RPCHandler::doSubscribe(), and ripple::RPC::lookupLedger().
 {
     return isIntegral () || isDouble ();
 }
bool Json::Value::isObject () const
Definition at line 1515 of file json_value.cpp.
References Json::nullValue, Json::objectValue, and type_.
Referenced by ripple::RPC::contains_error(), ripple::WSServerHandler< endpoint_type >::do_message(), ripple::RPCHandler::doCommand(), ripple::RPCHandler::doLedgerEntry(), ripple::RPCHandler::doPrint(), ripple::RPCHandler::doRipplePathFind(), ripple::RPCHandler::doRpcCommand(), ripple::RPCHandler::doSubscribe(), ripple::RPCHandler::doUnsubscribe(), empty(), ripple::NetworkOPsImp::getTxsAccount(), ripple::NetworkOPsImp::getTxsAccountB(), Json::StyledWriter::isMultineArray(), Json::StyledStreamWriter::isMultineArray(), ripple::isRpcError(), Json::Path::make(), ripple::RPC::DoPrint::operator()(), Json::Reader::parse(), ripple::STParsedJSON::parse(), ripple::PathRequest::parseJson(), ripple::RPCParser::parseJson(), ripple::SerializedObject_test::parseJSONString(), ripple::RPCServerHandler::processRequest(), ripple::RPCHTTPServerImp::processRequest(), Json::Path::resolve(), ripple::STAmount::STAmount(), and ripple::RPC::transactionSign().
 {
     return type_ == nullValue  ||  type_ == objectValue;
 }
bool Json::Value::isString () const
Definition at line 1501 of file json_value.cpp.
References Json::stringValue, and type_.
Referenced by ripple::WSServerHandler< endpoint_type >::do_message(), ripple::RPCHandler::doLedgerData(), ripple::RPCHandler::doLedgerEntry(), ripple::RPCHandler::doPathFind(), ripple::RPCHandler::doPrint(), ripple::RPCHandler::doRipplePathFind(), ripple::RPC::lookupLedger(), ripple::RPC::DoPrint::operator()(), ripple::STParsedJSON::parse(), ripple::RPCServerHandler::processRequest(), ripple::RPCHTTPServerImp::processRequest(), ripple::BookDirIterator::setJson(), and ripple::STAmount::STAmount().
 {
     return type_ == stringValue;
 }
bool Json::Value::isUInt () const
Definition at line 1471 of file json_value.cpp.
References type_, and Json::uintValue.
Referenced by ripple::STParsedJSON::parse(), and ripple::STAmount::STAmount().
 {
     return type_ == uintValue;
 }
bool Json::Value::isValidIndex (UInt index) const
Return true if index < size().
Definition at line 1231 of file json_value.cpp.
References size().
Referenced by ripple::STParsedJSON::parse(), and Json::Path::resolve().
 {
     return index < size ();
 }
bool Json::Value::operator! () const
Return isNull()
Definition at line 1076 of file json_value.cpp.
References isNull().
 {
     return isNull ();
 }
bool Json::Value::operator!= (const Value & other) const
Definition at line 773 of file json_value.cpp.
 {
     return ! ( *this == other );
 }
bool Json::Value::operator< (const Value & other) const
Definition at line 640 of file json_value.cpp.
References Json::arrayValue, Json::Value::ValueHolder::bool_, Json::booleanValue, Json::Value::ValueHolder::int_, Json::intValue, JSON_ASSERT_UNREACHABLE, Json::Value::ValueHolder::map_, Json::nullValue, Json::objectValue, Json::Value::ValueHolder::real_, Json::realValue, Json::Value::ValueHolder::string_, Json::stringValue, type_, Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
 {
     int typeDelta = type_ - other.type_;
     if ( typeDelta )
         return typeDelta < 0 ? true : false;
     switch ( type_ )
     {
     case nullValue:
         return false;
     case intValue:
         return value_.int_ < other.value_.int_;
     case uintValue:
         return value_.uint_ < other.value_.uint_;
     case realValue:
         return value_.real_ < other.value_.real_;
     case booleanValue:
         return value_.bool_ < other.value_.bool_;
     case stringValue:
         return ( value_.string_ == 0  &&  other.value_.string_ )
                || ( other.value_.string_
                     &&  value_.string_
                     && strcmp ( value_.string_, other.value_.string_ ) < 0 );
 #ifndef JSON_VALUE_USE_INTERNAL_MAP
     case arrayValue:
     case objectValue:
     {
         int delta = int ( value_.map_->size () - other.value_.map_->size () );
         if ( delta )
             return delta < 0;
         return (*value_.map_) < (*other.value_.map_);
     }
 #else
     case arrayValue:
         return value_.array_->compare ( * (other.value_.array_) ) < 0;
     case objectValue:
         return value_.map_->compare ( * (other.value_.map_) ) < 0;
 #endif
     default:
         JSON_ASSERT_UNREACHABLE;
     }
     return 0;  // unreachable
 }
bool Json::Value::operator<= (const Value & other) const
Definition at line 699 of file json_value.cpp.
 {
     return ! (other > *this);
 }
Value & Json::Value::operator= (const Value & other)
Definition at line 550 of file json_value.cpp.
References swap().
 {
     Value temp ( other );
     swap ( temp );
     return *this;
 }
Value & Json::Value::operator= (Value && other)
Definition at line 571 of file json_value.cpp.
References swap().
 {
     swap ( other );
     return *this;
 }
bool Json::Value::operator== (const Value & other) const
Definition at line 717 of file json_value.cpp.
References Json::arrayValue, Json::Value::ValueHolder::bool_, Json::booleanValue, Json::Value::ValueHolder::int_, Json::intValue, JSON_ASSERT_UNREACHABLE, Json::Value::ValueHolder::map_, Json::nullValue, Json::objectValue, Json::Value::ValueHolder::real_, Json::realValue, Json::Value::ValueHolder::string_, Json::stringValue, type_, Json::Value::ValueHolder::uint_, Json::uintValue, and value_.
 {
     //if ( type_ != other.type_ )
     // GCC 2.95.3 says:
     // attempt to take address of bit-field structure member `Json::Value::type_'
     // Beats me, but a temp solves the problem.
     int temp = other.type_;
     if ( type_ != temp )
         return false;
     switch ( type_ )
     {
     case nullValue:
         return true;
     case intValue:
         return value_.int_ == other.value_.int_;
     case uintValue:
         return value_.uint_ == other.value_.uint_;
     case realValue:
         return value_.real_ == other.value_.real_;
     case booleanValue:
         return value_.bool_ == other.value_.bool_;
     case stringValue:
         return ( value_.string_ == other.value_.string_ )
                || ( other.value_.string_
                     &&  value_.string_
                     && strcmp ( value_.string_, other.value_.string_ ) == 0 );
 #ifndef JSON_VALUE_USE_INTERNAL_MAP
     case arrayValue:
     case objectValue:
         return value_.map_->size () == other.value_.map_->size ()
                && (*value_.map_) == (*other.value_.map_);
 #else
     case arrayValue:
         return value_.array_->compare ( * (other.value_.array_) ) == 0;
     case objectValue:
         return value_.map_->compare ( * (other.value_.map_) ) == 0;
 #endif
     default:
         JSON_ASSERT_UNREACHABLE;
     }
     return 0;  // unreachable
 }
bool Json::Value::operator> (const Value & other) const
Definition at line 711 of file json_value.cpp.
 {
     return other < *this;
 }
bool Json::Value::operator>= (const Value & other) const
Definition at line 705 of file json_value.cpp.
 {
     return ! (*this < other);
 }
Value & Json::Value::operator[] (UInt index)
Access an array element (zero based index). If the array contains less than index element, then null value are inserted in the array so that its size is index+1. (You may need to say 'value[0u]' to get your compiler to distinguish this from the operator[] which takes a string.)
Definition at line 1141 of file json_value.cpp.
References Json::arrayValue, JSON_ASSERT, Json::Value::ValueHolder::map_, null, Json::nullValue, type_, Value(), and value_.
 {
     JSON_ASSERT ( type_ == nullValue  ||  type_ == arrayValue );
     if ( type_ == nullValue )
         *this = Value ( arrayValue );
 #ifndef JSON_VALUE_USE_INTERNAL_MAP
     CZString key ( index );
     ObjectValues::iterator it = value_.map_->lower_bound ( key );
     if ( it != value_.map_->end ()  &&  (*it).first == key )
         return (*it).second;
     ObjectValues::value_type defaultValue ( key, null );
     it = value_.map_->insert ( it, defaultValue );
     return (*it).second;
 #else
     return value_.array_->resolveReference ( index );
 #endif
 }
const Value & Json::Value::operator[] (UInt index) const
Access an array element (zero based index) (You may need to say 'value[0u]' to get your compiler to distinguish this from the operator[] which takes a string.)
Definition at line 1165 of file json_value.cpp.
References Json::arrayValue, JSON_ASSERT, Json::Value::ValueHolder::map_, null, Json::nullValue, type_, and value_.
 {
     JSON_ASSERT ( type_ == nullValue  ||  type_ == arrayValue );
     if ( type_ == nullValue )
         return null;
 #ifndef JSON_VALUE_USE_INTERNAL_MAP
     CZString key ( index );
     ObjectValues::const_iterator it = value_.map_->find ( key );
     if ( it == value_.map_->end () )
         return null;
     return (*it).second;
 #else
     Value* value = value_.array_->find ( index );
     return value ? *value : null;
 #endif
 }
Value & Json::Value::operator[] (const char * key)
Access an object value by name, create a null member if it does not exist.
Definition at line 1188 of file json_value.cpp.
References resolveReference().
 {
     return resolveReference ( key, false );
 }
const Value & Json::Value::operator[] (const char * key) const
Access an object value by name, returns null if there is no member with that name.
Definition at line 1239 of file json_value.cpp.
References JSON_ASSERT, Json::Value::ValueHolder::map_, Json::Value::CZString::noDuplication, null, Json::nullValue, Json::objectValue, type_, and value_.
 {
     JSON_ASSERT ( type_ == nullValue  ||  type_ == objectValue );
     if ( type_ == nullValue )
         return null;
 #ifndef JSON_VALUE_USE_INTERNAL_MAP
     CZString actualKey ( key, CZString::noDuplication );
     ObjectValues::const_iterator it = value_.map_->find ( actualKey );
     if ( it == value_.map_->end () )
         return null;
     return (*it).second;
 #else
     const Value* value = value_.map_->find ( key );
     return value ? *value : null;
 #endif
 }
Value & Json::Value::operator[] (const std::string & key)
Access an object value by name, create a null member if it does not exist.
Definition at line 1262 of file json_value.cpp.
 {
     return (*this)[ key.c_str () ];
 }
const Value & Json::Value::operator[] (const std::string & key) const
Access an object value by name, returns null if there is no member with that name.
Definition at line 1269 of file json_value.cpp.
 {
     return (*this)[ key.c_str () ];
 }
Value & Json::Value::operator[] (const StaticString & key)
Access an object value by name, create a null member if it does not exist.
If the object as no entry for that name, then the member name used to store the new entry is not duplicated. Example of use:
Json::Value object;
static const StaticString code("code");
object[code] = 1234;
Definition at line 1275 of file json_value.cpp.
References resolveReference().
 {
     return resolveReference ( key, true );
 }
Value Json::Value::removeMember (const char * key)
Remove and return the named member.
Do nothing if it did not exist.
Returns
the removed Value, or null.
Precondition
type() is objectValue or nullValue
Postcondition
type() is unchanged
Definition at line 1321 of file json_value.cpp.
References JSON_ASSERT, Json::Value::ValueHolder::map_, Json::Value::CZString::noDuplication, null, Json::nullValue, Json::objectValue, type_, and value_.
Referenced by removeMember().
 {
     JSON_ASSERT ( type_ == nullValue  ||  type_ == objectValue );
     if ( type_ == nullValue )
         return null;
 #ifndef JSON_VALUE_USE_INTERNAL_MAP
     CZString actualKey ( key, CZString::noDuplication );
     ObjectValues::iterator it = value_.map_->find ( actualKey );
     if ( it == value_.map_->end () )
         return null;
     Value old (it->second);
     value_.map_->erase (it);
     return old;
 #else
     Value* value = value_.map_->find ( key );
     if (value)
     {
         Value old (*value);
         value_.map_.remove ( key );
         return old;
     }
     else
     {
         return null;
     }
 #endif
 }
Value Json::Value::removeMember (const std::string & key)
Same as removeMember(const char*)
Definition at line 1356 of file json_value.cpp.
References removeMember().
 {
     return removeMember ( key.c_str () );
 }
void Json::Value::resize (UInt size)
Resize the array to size elements. New elements are initialized to null. May only be called on nullValue or arrayValue.
Precondition
type() is arrayValue or nullValue
Postcondition
type() is arrayValue
Definition at line 1112 of file json_value.cpp.
References Json::arrayValue, clear(), JSON_ASSERT, Json::Value::ValueHolder::map_, Json::nullValue, size(), type_, Value(), and value_.
 {
     JSON_ASSERT ( type_ == nullValue  ||  type_ == arrayValue );
     if ( type_ == nullValue )
         *this = Value ( arrayValue );
 #ifndef JSON_VALUE_USE_INTERNAL_MAP
     UInt oldSize = size ();
     if ( newSize == 0 )
         clear ();
     else if ( newSize > oldSize )
         (*this)[ newSize - 1 ];
     else
     {
         for ( UInt index = newSize; index < oldSize; ++index )
             value_.map_->erase ( index );
         assert ( size () == newSize );
     }
 #else
     value_.array_->resize ( newSize );
 #endif
 }
Value & Json::Value::resolveReference (const char * key, bool isStatic) private
Definition at line 1195 of file json_value.cpp.
References Json::Value::CZString::duplicateOnCopy, JSON_ASSERT, Json::Value::ValueHolder::map_, Json::Value::CZString::noDuplication, null, Json::nullValue, Json::objectValue, type_, Value(), value, and value_.
Referenced by operator[]().
 {
     JSON_ASSERT ( type_ == nullValue  ||  type_ == objectValue );
     if ( type_ == nullValue )
         *this = Value ( objectValue );
 #ifndef JSON_VALUE_USE_INTERNAL_MAP
     CZString actualKey ( key, isStatic ? CZString::noDuplication
                          : CZString::duplicateOnCopy );
     ObjectValues::iterator it = value_.map_->lower_bound ( actualKey );
     if ( it != value_.map_->end ()  &&  (*it).first == actualKey )
         return (*it).second;
     ObjectValues::value_type defaultValue ( actualKey, null );
     it = value_.map_->insert ( it, defaultValue );
     Value& value = (*it).second;
     return value;
 #else
     return value_.map_->resolveReference ( key, isStatic );
 #endif
 }
void Json::Value::setComment (const char * comment, CommentPlacement placement)
Comments must be //... or /* ... */.
Definition at line 1522 of file json_value.cpp.
References comments_, Json::numberOfCommentPlacement, and Json::Value::CommentInfo::setComment().
Referenced by Json::Reader::addComment(), Json::Reader::parse(), Json::Reader::readValue(), and setComment().
 {
     if ( !comments_ )
         comments_ = new CommentInfo[numberOfCommentPlacement];
     comments_[placement].setComment ( comment );
 }
void Json::Value::setComment (const std::string & comment, CommentPlacement placement)
Comments must be //... or /* ... */.
Definition at line 1533 of file json_value.cpp.
References setComment().
 {
     setComment ( comment.c_str (), placement );
 }
Value::UInt Json::Value::size () const
Number of values in array or object.
Definition at line 1023 of file json_value.cpp.
References Json::arrayValue, Json::booleanValue, Json::intValue, JSON_ASSERT_UNREACHABLE, Json::Value::ValueHolder::map_, Json::nullValue, Json::objectValue, Json::realValue, Json::stringValue, type_, Json::uintValue, and value_.
Referenced by append(), ripple::RPCHandler::doLedgerEntry(), ripple::RPCHandler::doRipplePathFind(), ripple::RPCHandler::doRpcCommand(), empty(), ripple::LedgerConsensusImp::getJson(), Json::StyledWriter::isMultineArray(), Json::StyledStreamWriter::isMultineArray(), isValidIndex(), ripple::RPC::lookupLedger(), ripple::STParsedJSON::parse(), ripple::RPCParser::parseAccountRaw(), ripple::RPCParser::parseAccountTransactions(), ripple::RPCParser::parseAsIs(), ripple::RPCParser::parseBookOffers(), ripple::RPCParser::parseCommand(), ripple::RPCParser::parseConnect(), ripple::RPCParser::parseFeature(), ripple::RPCParser::parseFetchInfo(), ripple::RPCParser::parseGetCounts(), ripple::RPCParser::parseInternal(), ripple::PathRequest::parseJson(), ripple::RPCParser::parseLedger(), ripple::RPCParser::parseLogLevel(), ripple::RPCParser::parseProofCreate(), ripple::RPCParser::parseProofVerify(), ripple::RPCParser::parseRipplePathFind(), ripple::RPCParser::parseSignSubmit(), ripple::RPCParser::parseTx(), ripple::RPCParser::parseTxAccount(), ripple::RPCParser::parseUnlAdd(), ripple::RPCParser::parseValidationCreate(), ripple::RPCParser::parseValidationSeed(), ripple::RPCParser::parseWalletPropose(), ripple::RPCParser::parseWalletSeed(), resize(), ripple::startServer(), Json::StyledWriter::writeArrayValue(), Json::StyledStreamWriter::writeArrayValue(), and Json::FastWriter::writeValue().
 {
     switch ( type_ )
     {
     case nullValue:
     case intValue:
     case uintValue:
     case realValue:
     case booleanValue:
     case stringValue:
         return 0;
 #ifndef JSON_VALUE_USE_INTERNAL_MAP
     case arrayValue:  // size of the array is highest index + 1
         if ( !value_.map_->empty () )
         {
             ObjectValues::const_iterator itLast = value_.map_->end ();
             --itLast;
             return (*itLast).first.index () + 1;
         }
         return 0;
     case objectValue:
         return Int ( value_.map_->size () );
 #else
     case arrayValue:
         return Int ( value_.array_->size () );
     case objectValue:
         return Int ( value_.map_->size () );
 #endif
     default:
         JSON_ASSERT_UNREACHABLE;
     }
     return 0; // unreachable;
 }
void Json::Value::swap (Value & other)
Swap values.
Note
Currently, comments are intentionally not swapped, for both logic and efficiency.
Definition at line 578 of file json_value.cpp.
References allocated_, comments_, beast::asio::swap(), type_, and value_.
Referenced by Json::Value::CZString::operator=(), and operator=().
 {
     std::swap ( value_, other.value_ );
     ValueType temp = type_;
     type_ = other.type_;
     other.type_ = temp;
     int temp2 = allocated_;
     allocated_ = other.allocated_;
     other.allocated_ = temp2;
 # ifdef JSON_VALUE_USE_INTERNAL_MAP
     unsigned temp3 = itemIsUsed_;
     itemIsUsed_ = other.itemIsUsed_;
     other.itemIsUsed_ = itemIsUsed_;
     temp2 = memberNameIsStatic_;
     memberNameIsStatic_ = other.memberNameIsStatic_;
     other.memberNameIsStatic_ = temp2
 # endif
     std::swap(comments_, other.comments_);
 }
std::string Json::Value::toStyledString () const
Definition at line 1557 of file json_value.cpp.
References Json::StyledWriter::write().
Referenced by ripple::RPCCall::fromCommandLine().
 {
     StyledWriter writer;
     return writer.write ( *this );
 }
ValueType Json::Value::type () const
Definition at line 603 of file json_value.cpp.
References type_.
Referenced by Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), and Json::StyledStreamWriter::writeValue().
 {
     return type_;
 }
Friends And Related Function Documentation
friend class ValueIteratorBase friend
Definition at line 120 of file json_value.h.
Member Data Documentation
int Json::Value::allocated_ private
Definition at line 452 of file json_value.h.
Referenced by swap(), Value(), and ~Value().
CommentInfo* Json::Value::comments_ private
Definition at line 457 of file json_value.h.
Referenced by getComment(), hasComment(), setComment(), swap(), Value(), and ~Value().
const Int Json::Value::maxInt = Int (UInt (-1) / 2) static
Definition at line 135 of file json_value.h.
Referenced by asInt(), Json::Reader::decodeNumber(), and isConvertibleTo().
const UInt Json::Value::maxUInt = UInt (-1) static
Definition at line 136 of file json_value.h.
Referenced by asUInt(), Json::Reader::decodeNumber(), and isConvertibleTo().
const Int Json::Value::minInt = Int (~ (UInt (-1) / 2)) static
Definition at line 134 of file json_value.h.
Referenced by asInt(), Json::Reader::decodeNumber(), and isConvertibleTo().
const Value Json::Value::null static
Definition at line 133 of file json_value.h.
Referenced by get(), isMember(), operator[](), removeMember(), Json::Path::resolve(), and resolveReference().
ValueType Json::Value::type_ private
Definition at line 451 of file json_value.h.
Referenced by asBool(), asCString(), asDouble(), asInt(), asString(), asUInt(), begin(), clear(), end(), getMemberNames(), isArray(), isBool(), isConvertibleTo(), isDouble(), isInt(), isIntegral(), isNull(), isObject(), isString(), isUInt(), operator<(), operator==(), operator[](), removeMember(), resize(), resolveReference(), size(), swap(), type(), Value(), and ~Value().
union Json::Value::ValueHolder Json::Value::value_ private
Referenced by asBool(), asCString(), asDouble(), asInt(), asString(), asUInt(), begin(), clear(), end(), getMemberNames(), isConvertibleTo(), operator<(), operator==(), operator[](), removeMember(), resize(), resolveReference(), size(), swap(), Value(), and ~Value().
The documentation for this class was generated from the following files:
rippled/src/ripple/json/api/json_value.h
rippled/src/ripple/json/impl/json_value.cpp