rippled: ripple::RadMap::BasicFullBelowCache< Key > Class Template Reference
ripple::RadMap::BasicFullBelowCache< Key > Class Template Reference
#include <BasicFullBelowCache.h>
Public Types
typedef Key key_type
typedef CacheType::size_type size_type
typedef CacheType::clock_type clock_type
Public Member Functions
BasicFullBelowCache (std::string const &name, clock_type &clock, beast::insight::Collector::ptr const &collector=beast::insight::NullCollector::New(), std::size_t target_size=defaultCacheTargetSize, std::size_t expiration_seconds=defaultCacheExpirationSeconds)
clock_type & clock ()
size_type size () const
void sweep ()
bool touch_if_exists (key_type const &key)
void insert (key_type const &key)
Private Types
typedef KeyCache< Key > CacheType
Private Attributes
KeyCache< Key > m_cache
Detailed Description
template<class Key>
class ripple::RadMap::BasicFullBelowCache< Key >
Remembers which tree keys have all descendants resident. This optimizes the process of acquiring a complete tree.
Definition at line 36 of file BasicFullBelowCache.h.
Member Typedef Documentation
template<class Key > typedef KeyCache<Key> ripple::RadMap::BasicFullBelowCache< Key >::CacheType private
Definition at line 39 of file BasicFullBelowCache.h.
template<class Key > typedef CacheType::clock_type ripple::RadMap::BasicFullBelowCache< Key >::clock_type
Definition at line 44 of file BasicFullBelowCache.h.
template<class Key > typedef Key ripple::RadMap::BasicFullBelowCache< Key >::key_type
Definition at line 42 of file BasicFullBelowCache.h.
template<class Key > typedef CacheType::size_type ripple::RadMap::BasicFullBelowCache< Key >::size_type
Definition at line 43 of file BasicFullBelowCache.h.
Constructor & Destructor Documentation
template<class Key > ripple::RadMap::BasicFullBelowCache< Key >::BasicFullBelowCache (std::string const & name, clock_type & clock, beast::insight::Collector::ptr const & collector = beast::insight::NullCollector::New (), std::size_t target_size = defaultCacheTargetSize, std::size_t expiration_seconds = defaultCacheExpirationSeconds) inline
Construct the cache.
Parameters
name A label for diagnostics and stats reporting.
collector The collector to use for reporting stats.
targetSize The cache target size.
targetExpirationSeconds The expiration time for items.
Definition at line 53 of file BasicFullBelowCache.h.
         : m_cache (name, clock, collector, target_size,
             expiration_seconds)
     {
     }
Member Function Documentation
template<class Key > clock_type& ripple::RadMap::BasicFullBelowCache< Key >::clock () inline
Return the clock associated with the cache.
Definition at line 64 of file BasicFullBelowCache.h.
References ripple::KeyCache< Key, Hash, KeyEqual, Mutex >::clock(), and ripple::RadMap::BasicFullBelowCache< Key >::m_cache.
     {
         return m_cache.clock ();
     }
template<class Key > void ripple::RadMap::BasicFullBelowCache< Key >::insert (key_type const & key) inline
Insert a key into the cache. If the key already exists, the last access time will still be refreshed. Thread safety: Safe to call from any thread.
Parameters
key The key to insert.
Definition at line 105 of file BasicFullBelowCache.h.
References ripple::KeyCache< Key, Hash, KeyEqual, Mutex >::insert(), and ripple::RadMap::BasicFullBelowCache< Key >::m_cache.
Referenced by ripple::SHAMap::getMissingNodes().
     {
         m_cache.insert (key);
     }
template<class Key > size_type ripple::RadMap::BasicFullBelowCache< Key >::size () const inline
Return the number of elements in the cache. Thread safety: Safe to call from any thread.
Definition at line 73 of file BasicFullBelowCache.h.
References ripple::RadMap::BasicFullBelowCache< Key >::m_cache, and ripple::KeyCache< Key, Hash, KeyEqual, Mutex >::size().
     {
         return m_cache.size ();
     }
template<class Key > void ripple::RadMap::BasicFullBelowCache< Key >::sweep () inline
Remove expired cache items. Thread safety: Safe to call from any thread.
Definition at line 82 of file BasicFullBelowCache.h.
References ripple::RadMap::BasicFullBelowCache< Key >::m_cache, and ripple::KeyCache< Key, Hash, KeyEqual, Mutex >::sweep().
     {
         m_cache.sweep ();
     }
template<class Key > bool ripple::RadMap::BasicFullBelowCache< Key >::touch_if_exists (key_type const & key) inline
Refresh the last access time of an item, if it exists. Thread safety: Safe to call from any thread.
Parameters
key The key to refresh.
Returns
true If the key exists.
Definition at line 93 of file BasicFullBelowCache.h.
References ripple::RadMap::BasicFullBelowCache< Key >::m_cache, and ripple::KeyCache< Key, Hash, KeyEqual, Mutex >::touch_if_exists().
Referenced by ripple::SHAMap::addKnownNode(), and ripple::SHAMap::getMissingNodes().
     {
         return m_cache.touch_if_exists (key);
     }
Member Data Documentation
template<class Key > KeyCache<Key> ripple::RadMap::BasicFullBelowCache< Key >::m_cache private
Definition at line 111 of file BasicFullBelowCache.h.
Referenced by ripple::RadMap::BasicFullBelowCache< Key >::clock(), ripple::RadMap::BasicFullBelowCache< Key >::insert(), ripple::RadMap::BasicFullBelowCache< Key >::size(), ripple::RadMap::BasicFullBelowCache< Key >::sweep(), and ripple::RadMap::BasicFullBelowCache< Key >::touch_if_exists().
The documentation for this class was generated from the following file:
rippled/src/ripple/radmap/api/BasicFullBelowCache.h