rippled: rocksdb::SnapshotList Class Reference
rocksdb::SnapshotList Class Reference
#include <snapshot.h>
Public Member Functions
SnapshotList ()
bool empty () const
SnapshotImpl * oldest () const
SnapshotImpl * newest () const
const SnapshotImpl * New (SequenceNumber seq)
void Delete (const SnapshotImpl *s)
void getAll (std::vector< SequenceNumber > &ret)
const SequenceNumber GetNewest ()
Private Attributes
SnapshotImpl list_
Detailed Description
Definition at line 33 of file snapshot.h.
Constructor & Destructor Documentation
rocksdb::SnapshotList::SnapshotList () inline
Definition at line 35 of file snapshot.h.
References list_, rocksdb::SnapshotImpl::next_, rocksdb::SnapshotImpl::number_, and rocksdb::SnapshotImpl::prev_.
                  {
     list_.prev_ = &list_;
     list_.next_ = &list_;
     list_.number_ = 0xFFFFFFFFL;      // placeholder marker, for debugging
   }
Member Function Documentation
void rocksdb::SnapshotList::Delete (const SnapshotImpl * s) inline
Definition at line 56 of file snapshot.h.
References rocksdb::SnapshotImpl::list_, rocksdb::SnapshotImpl::next_, and rocksdb::SnapshotImpl::prev_.
Referenced by rocksdb::DBImpl::ReleaseSnapshot().
{
     assert(s->list_ == this);
     s->prev_->next_ = s->next_;
     s->next_->prev_ = s->prev_;
     delete s;
   }
bool rocksdb::SnapshotList::empty () const inline
Definition at line 41 of file snapshot.h.
References list_, and rocksdb::SnapshotImpl::next_.
Referenced by getAll(), GetNewest(), newest(), and oldest().
 { return list_.next_ == &list_; }
void rocksdb::SnapshotList::getAll (std::vector< SequenceNumber > & ret) inline
Definition at line 64 of file snapshot.h.
References empty(), list_, rocksdb::SnapshotImpl::next_, and rocksdb::SnapshotImpl::number_.
Referenced by rocksdb::DBImpl::DoCompactionWork().
{
     if (empty()) return;
     SnapshotImpl* s = &list_;
     while (s->next_ != &list_) {
       ret.push_back(s->next_->number_);
       s = s ->next_;
     }
   }
const SequenceNumber rocksdb::SnapshotList::GetNewest () inline
Definition at line 74 of file snapshot.h.
References empty(), newest(), and rocksdb::SnapshotImpl::number_.
Referenced by rocksdb::DBImpl::WriteLevel0Table(), and rocksdb::DBImpl::WriteLevel0TableForRecovery().
{
     if (empty()) {
       return 0;
     }
     return newest()->number_;
   }
const SnapshotImpl* rocksdb::SnapshotList::New (SequenceNumber seq) inline
Definition at line 45 of file snapshot.h.
References rocksdb::SnapshotImpl::list_, list_, rocksdb::SnapshotImpl::next_, rocksdb::SnapshotImpl::number_, and rocksdb::SnapshotImpl::prev_.
Referenced by rocksdb::DBImpl::GetSnapshot().
{
     SnapshotImpl* s = new SnapshotImpl;
     s->number_ = seq;
     s->list_ = this;
     s->next_ = &list_;
     s->prev_ = list_.prev_;
     s->prev_->next_ = s;
     s->next_->prev_ = s;
     return s;
   }
SnapshotImpl* rocksdb::SnapshotList::newest () const inline
Definition at line 43 of file snapshot.h.
References empty(), list_, and rocksdb::SnapshotImpl::prev_.
Referenced by GetNewest().
 { assert(!empty()); return list_.prev_; }
SnapshotImpl* rocksdb::SnapshotList::oldest () const inline
Definition at line 42 of file snapshot.h.
References empty(), list_, and rocksdb::SnapshotImpl::next_.
 { assert(!empty()); return list_.next_; }
Member Data Documentation
SnapshotImpl rocksdb::SnapshotList::list_ private
Definition at line 83 of file snapshot.h.
Referenced by empty(), getAll(), New(), newest(), oldest(), and SnapshotList().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/db/snapshot.h