rippled: beast::ServiceQueue_test::ServiceThread Struct Reference
beast::ServiceQueue_test::ServiceThread Struct Reference
Public Member Functions
ServiceThread (int id, std::int64_t seedValue, ServiceQueue &service)
~ServiceThread ()
void do_handler ()
void run ()
Public Member Functions inherited from beast::Thread
Thread (const String &threadName)
virtual ~Thread ()
void startThread ()
void startThread (int priority)
bool stopThread (int timeOutMilliseconds=-1)
void stopThreadAsync ()
bool isThreadRunning () const
void signalThreadShouldExit ()
bool threadShouldExit () const
bool waitForThreadToExit (int timeOutMilliseconds=-1) const
bool setPriority (int priority)
void setAffinityMask (std::uint32_t affinityMask)
bool wait (int timeOutMilliseconds=-1) const
void notify () const
ThreadID getThreadId () const noexcept
const String & getThreadName () const
Static Public Member Functions
static ServiceThread *& thread ()
static void stop_one ()
static void handler ()
Static Public Member Functions inherited from beast::Thread
static bool setCurrentThreadPriority (int priority)
static void setCurrentThreadAffinityMask (std::uint32_t affinityMask)
static void sleep (int milliseconds)
static void yield ()
static ThreadID getCurrentThreadId ()
static Thread * getCurrentThread ()
static void setCurrentThreadName (const String &newThreadName)
Public Attributes
Random m_random
ServiceQueue & m_service
String m_string
Additional Inherited Members
Public Types inherited from beast::Thread
typedef void * ThreadID
Protected Member Functions inherited from beast::Uncopyable
Uncopyable ()
~Uncopyable ()
Detailed Description
Definition at line 205 of file ServiceQueue.cpp.
Constructor & Destructor Documentation
beast::ServiceQueue_test::ServiceThread::ServiceThread (int id, std::int64_t seedValue, ServiceQueue & service) inline
Definition at line 211 of file ServiceQueue.cpp.
References beast::Thread::startThread().
             : Thread ("#" + String::fromNumber (id))
             , m_random (seedValue)
             , m_service (service)
         {
             startThread();
         }
beast::ServiceQueue_test::ServiceThread::~ServiceThread () inline
Definition at line 220 of file ServiceQueue.cpp.
References beast::Thread::stopThread().
         {
             stopThread();
         }
Member Function Documentation
void beast::ServiceQueue_test::ServiceThread::do_handler () inline
Definition at line 241 of file ServiceQueue.cpp.
References beast::String::empty, beast::String::fromNumber(), beast::String::length(), m_random, m_string, and beast::Random::nextInt().
Referenced by handler().
         {
 #if 1
             String const s (String::fromNumber (m_random.nextInt()));
             m_string += s;
             if (m_string.length() > 100)
                 m_string = String::empty;
 #endif
         }
static void beast::ServiceQueue_test::ServiceThread::handler () inline static
Definition at line 236 of file ServiceQueue.cpp.
References do_handler(), and thread().
Referenced by beast::ServiceQueue_test::testThreads().
         {
             thread()->do_handler();
         }
void beast::ServiceQueue_test::ServiceThread::run () inline virtual
Must be implemented to perform the thread's actual code.
Remember that the thread must regularly check the threadShouldExit() method whilst running, and if this returns true it should return from the run() method as soon as possible to avoid being forcibly killed.
See Also
threadShouldExit, startThread
Implements beast::Thread.
Definition at line 251 of file ServiceQueue.cpp.
References m_service, beast::ServiceQueueType< Allocator >::run_one(), thread(), and beast::Thread::threadShouldExit().
         {
             thread() = this;
             while (! threadShouldExit())
                 m_service.run_one();
         }
static void beast::ServiceQueue_test::ServiceThread::stop_one () inline static
Definition at line 231 of file ServiceQueue.cpp.
References beast::Thread::signalThreadShouldExit(), and thread().
Referenced by beast::ServiceQueue_test::testThreads().
         {
             thread()->signalThreadShouldExit();
         }
static ServiceThread*& beast::ServiceQueue_test::ServiceThread::thread () inline static
Definition at line 225 of file ServiceQueue.cpp.
References beast::ThreadLocalValue< Type >::get(), and std::chrono::local.
Referenced by handler(), run(), and stop_one().
         {
             static ThreadLocalValue <ServiceThread*> local;
             return local.get();
         }
Member Data Documentation
Random beast::ServiceQueue_test::ServiceThread::m_random
Definition at line 207 of file ServiceQueue.cpp.
Referenced by do_handler().
ServiceQueue& beast::ServiceQueue_test::ServiceThread::m_service
Definition at line 208 of file ServiceQueue.cpp.
Referenced by run().
String beast::ServiceQueue_test::ServiceThread::m_string
Definition at line 209 of file ServiceQueue.cpp.
Referenced by do_handler().
The documentation for this struct was generated from the following file:
rippled/src/beast/beast/threads/tests/ServiceQueue.cpp