rippled: beast::AtExitHook::Manager Class Reference
beast::AtExitHook::Manager Class Reference
Classes
struct StaticDestructor
Public Member Functions
Manager ()
void insert (Item &item)
void erase (Item &item)
Static Public Member Functions
static Manager & get ()
Private Types
typedef CriticalSection MutexType
typedef MutexType::ScopedLockType ScopedLockType
Private Member Functions
void doStaticDetruction ()
Private Attributes
MutexType m_mutex
List< Item > m_list
bool m_didStaticDestruction
Static Private Attributes
static StaticDestructor s_staticDestructor
Detailed Description
Definition at line 26 of file AtExitHook.cpp.
Member Typedef Documentation
typedef CriticalSection beast::AtExitHook::Manager::MutexType private
Definition at line 89 of file AtExitHook.cpp.
typedef MutexType::ScopedLockType beast::AtExitHook::Manager::ScopedLockType private
Definition at line 90 of file AtExitHook.cpp.
Constructor & Destructor Documentation
beast::AtExitHook::Manager::Manager () inline
Definition at line 29 of file AtExitHook.cpp.
         : m_didStaticDestruction (false)
     {
     }
Member Function Documentation
void beast::AtExitHook::Manager::doStaticDetruction () inline private
Definition at line 62 of file AtExitHook.cpp.
References bassert, beast::AtExitHook::Item::hook(), m_didStaticDestruction, m_list, m_mutex, and beast::AtExitHook::onExit().
Referenced by beast::AtExitHook::Manager::StaticDestructor::~StaticDestructor().
     {
         // In theory this shouldn't be needed (?)
         ScopedLockType lock (m_mutex);
         bassert (! m_didStaticDestruction);
         for (List <Item>::iterator iter (m_list.begin()); iter != m_list.end();)
         {
             Item& item (*iter++);
             AtExitHook* const hook (item.hook ());
             hook->onExit ();
         }
         // Now do the leak checking
         //
         LeakCheckedBase::checkForLeaks ();
     }
void beast::AtExitHook::Manager::erase (Item & item) inline
Definition at line 51 of file AtExitHook.cpp.
References m_list, and m_mutex.
Referenced by beast::AtExitHook::~AtExitHook().
     {
         ScopedLockType lock (m_mutex);
         m_list.erase (m_list.iterator_to (item));
     }
static Manager& beast::AtExitHook::Manager::get () inline static
Definition at line 34 of file AtExitHook.cpp.
Referenced by beast::AtExitHook::AtExitHook(), beast::AtExitHook::~AtExitHook(), and beast::AtExitHook::Manager::StaticDestructor::~StaticDestructor().
     {
         return StaticObject <Manager>::get();
     }
void beast::AtExitHook::Manager::insert (Item & item) inline
Definition at line 39 of file AtExitHook.cpp.
References bassert, m_didStaticDestruction, m_list, and m_mutex.
Referenced by beast::AtExitHook::AtExitHook().
     {
         ScopedLockType lock (m_mutex);
         // Adding a new AtExitHook during or after the destruction
         // of objects with static storage duration has taken place?
         // Surely something has gone wrong.
         //
         bassert (! m_didStaticDestruction);
         m_list.push_front (item);
     }
Member Data Documentation
bool beast::AtExitHook::Manager::m_didStaticDestruction private
Definition at line 96 of file AtExitHook.cpp.
Referenced by doStaticDetruction(), and insert().
List<Item> beast::AtExitHook::Manager::m_list private
Definition at line 95 of file AtExitHook.cpp.
Referenced by doStaticDetruction(), erase(), and insert().
MutexType beast::AtExitHook::Manager::m_mutex private
Definition at line 94 of file AtExitHook.cpp.
Referenced by doStaticDetruction(), erase(), and insert().
AtExitHook::Manager::StaticDestructor beast::AtExitHook::Manager::s_staticDestructor static private
Definition at line 92 of file AtExitHook.cpp.
The documentation for this class was generated from the following file:
rippled/src/beast/modules/beast_core/time/AtExitHook.cpp