rippled: rippled/src/beast/beast/http/impl/http-parser/http_parser.h File Reference
http_parser.h File Reference
#include <sys/types.h>
#include <stdint.h>
Classes
struct http_parser
struct http_parser_settings
struct http_parser_url
Macros
#define HTTP_PARSER_VERSION_MAJOR 2
#define HTTP_PARSER_VERSION_MINOR 2
#define HTTP_PARSER_VERSION_PATCH 1
#define HTTP_PARSER_STRICT 1
#define HTTP_MAX_HEADER_SIZE (80*1024)
#define HTTP_METHOD_MAP(XX)
#define XX(num, name, string) HTTP_##name = num,
#define HTTP_ERRNO_MAP(XX)
#define HTTP_ERRNO_GEN(n, s) HPE_##n,
#define HTTP_PARSER_ERRNO(p) ((enum http_errno) (p)->http_errno)
#define http_parser_h
#define HTTP_PARSER_VERSION_MAJOR 2
#define HTTP_PARSER_VERSION_MINOR 2
#define HTTP_PARSER_VERSION_PATCH 1
#define HTTP_MAX_HEADER_SIZE (80*1024)
#define HTTP_METHOD_MAP(XX)
#define XX(num, name, string) HTTP_##name = num,
#define HTTP_ERRNO_MAP(XX)
#define HTTP_ERRNO_GEN(n, s) HPE_##n,
#define HTTP_PARSER_ERRNO(p) ((enum http_errno) (p)->http_errno)
Typedefs
typedef struct http_parser http_parser
typedef struct http_parser_settings http_parser_settings
typedef int(* http_data_cb)(http_parser *, const char *at, size_t length)
typedef int(* http_cb)(http_parser *)
Enumerations
enum http_method
enum http_parser_type { HTTP_REQUEST, HTTP_RESPONSE, HTTP_BOTH }
enum flags {
F_CHUNKED = 1 << 0, F_CONNECTION_KEEP_ALIVE = 1 << 1, F_CONNECTION_CLOSE = 1 << 2, F_TRAILING = 1 << 3,
F_UPGRADE = 1 << 4, F_SKIPBODY = 1 << 5
}
enum http_errno
enum http_parser_url_fields {
UF_SCHEMA = 0, UF_HOST = 1, UF_PORT = 2, UF_PATH = 3,
UF_QUERY = 4, UF_FRAGMENT = 5, UF_USERINFO = 6, UF_MAX = 7
}
Functions
unsigned long http_parser_version (void)
void http_parser_init (http_parser *parser, enum http_parser_type type)
size_t http_parser_execute (http_parser *parser, const http_parser_settings *settings, const char *data, size_t len)
int http_should_keep_alive (const http_parser *parser)
const char * http_method_str (enum http_method m)
const char * http_errno_name (enum http_errno err)
const char * http_errno_description (enum http_errno err)
int http_parser_parse_url (const char *buf, size_t buflen, int is_connect, struct http_parser_url *u)
void http_parser_pause (http_parser *parser, int paused)
int http_body_is_final (const http_parser *parser)
Macro Definition Documentation
#define HTTP_ERRNO_GEN (n, s) HPE_##n,
Definition at line 184 of file joyent_parser.cpp.
#define HTTP_ERRNO_GEN (n, s) HPE_##n,
#define HTTP_ERRNO_MAP (XX)
Value:
/* No error */                                                     \
  XX(OK, "success")                                                  \
                                                                     \
  /* Callback-related errors */                                      \
  XX(CB_message_begin, "the on_message_begin callback failed")       \
  XX(CB_url, "the on_url callback failed")                           \
  XX(CB_header_field, "the on_header_field callback failed")         \
  XX(CB_header_value, "the on_header_value callback failed")         \
  XX(CB_headers_complete, "the on_headers_complete callback failed") \
  XX(CB_body, "the on_body callback failed")                         \
  XX(CB_message_complete, "the on_message_complete callback failed") \
  XX(CB_status, "the on_status callback failed")                     \
                                                                     \
  /* Parsing-related errors */                                       \
  XX(INVALID_EOF_STATE, "stream ended at an unexpected time")        \
  XX(HEADER_OVERFLOW,                                                \
     "too many header bytes seen; overflow detected")                \
  XX(CLOSED_CONNECTION,                                              \
     "data received after completed connection: close message")      \
  XX(INVALID_VERSION, "invalid HTTP version")                        \
  XX(INVALID_STATUS, "invalid HTTP status code")                     \
  XX(INVALID_METHOD, "invalid HTTP method")                          \
  XX(INVALID_URL, "invalid URL")                                     \
  XX(INVALID_HOST, "invalid host")                                   \
  XX(INVALID_PORT, "invalid port")                                   \
  XX(INVALID_PATH, "invalid path")                                   \
  XX(INVALID_QUERY_STRING, "invalid query string")                   \
  XX(INVALID_FRAGMENT, "invalid fragment")                           \
  XX(LF_EXPECTED, "LF character expected")                           \
  XX(INVALID_HEADER_TOKEN, "invalid character in header")            \
  XX(INVALID_CONTENT_LENGTH,                                         \
     "invalid character in content-length header")                   \
  XX(INVALID_CHUNK_SIZE,                                             \
     "invalid character in chunk size header")                       \
  XX(INVALID_CONSTANT, "invalid constant string")                    \
  XX(INVALID_INTERNAL_STATE, "encountered unexpected internal state")\
  XX(STRICT, "strict mode assertion failed")                         \
  XX(PAUSED, "parser is paused")                                     \
  XX(UNKNOWN, "an unknown error occurred")
Definition at line 141 of file joyent_parser.cpp.
#define HTTP_ERRNO_MAP (XX)
Value:
/* No error */                                                     \
  XX(OK, "success")                                                  \
                                                                     \
  /* Callback-related errors */                                      \
  XX(CB_message_begin, "the on_message_begin callback failed")       \
  XX(CB_url, "the on_url callback failed")                           \
  XX(CB_header_field, "the on_header_field callback failed")         \
  XX(CB_header_value, "the on_header_value callback failed")         \
  XX(CB_headers_complete, "the on_headers_complete callback failed") \
  XX(CB_body, "the on_body callback failed")                         \
  XX(CB_message_complete, "the on_message_complete callback failed") \
  XX(CB_status, "the on_status callback failed")                     \
                                                                     \
  /* Parsing-related errors */                                       \
  XX(INVALID_EOF_STATE, "stream ended at an unexpected time")        \
  XX(HEADER_OVERFLOW,                                                \
     "too many header bytes seen; overflow detected")                \
  XX(CLOSED_CONNECTION,                                              \
     "data received after completed connection: close message")      \
  XX(INVALID_VERSION, "invalid HTTP version")                        \
  XX(INVALID_STATUS, "invalid HTTP status code")                     \
  XX(INVALID_METHOD, "invalid HTTP method")                          \
  XX(INVALID_URL, "invalid URL")                                     \
  XX(INVALID_HOST, "invalid host")                                   \
  XX(INVALID_PORT, "invalid port")                                   \
  XX(INVALID_PATH, "invalid path")                                   \
  XX(INVALID_QUERY_STRING, "invalid query string")                   \
  XX(INVALID_FRAGMENT, "invalid fragment")                           \
  XX(LF_EXPECTED, "LF character expected")                           \
  XX(INVALID_HEADER_TOKEN, "invalid character in header")            \
  XX(INVALID_CONTENT_LENGTH,                                         \
     "invalid character in content-length header")                   \
  XX(INVALID_CHUNK_SIZE,                                             \
     "invalid character in chunk size header")                       \
  XX(INVALID_CONSTANT, "invalid constant string")                    \
  XX(INVALID_INTERNAL_STATE, "encountered unexpected internal state")\
  XX(STRICT, "strict mode assertion failed")                         \
  XX(PAUSED, "parser is paused")                                     \
  XX(UNKNOWN, "an unknown error occurred")
#define HTTP_MAX_HEADER_SIZE (80*1024)
Definition at line 57 of file joyent_parser.cpp.
Referenced by http_parser_execute().
#define HTTP_MAX_HEADER_SIZE (80*1024)
#define HTTP_METHOD_MAP (XX)
Value:
XX(0,  DELETE,      DELETE)       \
  XX(1,  GET,         GET)          \
  XX(2,  HEAD,        HEAD)         \
  XX(3,  POST,        POST)         \
  XX(4,  PUT,         PUT)          \
  /* pathological */                \
  XX(5,  CONNECT,     CONNECT)      \
  XX(6,  OPTIONS,     OPTIONS)      \
  XX(7,  TRACE,       TRACE)        \
  /* webdav */                      \
  XX(8,  COPY,        COPY)         \
  XX(9,  LOCK,        LOCK)         \
  XX(10, MKCOL,       MKCOL)        \
  XX(11, MOVE,        MOVE)         \
  XX(12, PROPFIND,    PROPFIND)     \
  XX(13, PROPPATCH,   PROPPATCH)    \
  XX(14, SEARCH,      SEARCH)       \
  XX(15, UNLOCK,      UNLOCK)       \
  /* subversion */                  \
  XX(16, REPORT,      REPORT)       \
  XX(17, MKACTIVITY,  MKACTIVITY)   \
  XX(18, CHECKOUT,    CHECKOUT)     \
  XX(19, MERGE,       MERGE)        \
  /* upnp */                        \
  XX(20, MSEARCH,     M-SEARCH)     \
  XX(21, NOTIFY,      NOTIFY)       \
  XX(22, SUBSCRIBE,   SUBSCRIBE)    \
  XX(23, UNSUBSCRIBE, UNSUBSCRIBE)  \
  /* RFC-5789 */                    \
  XX(24, PATCH,       PATCH)        \
  XX(25, PURGE,       PURGE)        \
#define HTTP_METHOD_MAP (XX)
Value:
XX(0,  DELETE,      DELETE)       \
  XX(1,  GET,         GET)          \
  XX(2,  HEAD,        HEAD)         \
  XX(3,  POST,        POST)         \
  XX(4,  PUT,         PUT)          \
  /* pathological */                \
  XX(5,  CONNECT,     CONNECT)      \
  XX(6,  OPTIONS,     OPTIONS)      \
  XX(7,  TRACE,       TRACE)        \
  /* webdav */                      \
  XX(8,  COPY,        COPY)         \
  XX(9,  LOCK,        LOCK)         \
  XX(10, MKCOL,       MKCOL)        \
  XX(11, MOVE,        MOVE)         \
  XX(12, PROPFIND,    PROPFIND)     \
  XX(13, PROPPATCH,   PROPPATCH)    \
  XX(14, SEARCH,      SEARCH)       \
  XX(15, UNLOCK,      UNLOCK)       \
  /* subversion */                  \
  XX(16, REPORT,      REPORT)       \
  XX(17, MKACTIVITY,  MKACTIVITY)   \
  XX(18, CHECKOUT,    CHECKOUT)     \
  XX(19, MERGE,       MERGE)        \
  /* upnp */                        \
  XX(20, MSEARCH,     M-SEARCH)     \
  XX(21, NOTIFY,      NOTIFY)       \
  XX(22, SUBSCRIBE,   SUBSCRIBE)    \
  XX(23, UNSUBSCRIBE, UNSUBSCRIBE)  \
  /* RFC-5789 */                    \
  XX(24, PATCH,       PATCH)        \
  XX(25, PURGE,       PURGE)        \
Definition at line 82 of file joyent_parser.cpp.
#define HTTP_PARSER_ERRNO (p) ((enum http_errno) (p)->http_errno)
Definition at line 192 of file joyent_parser.cpp.
Referenced by http_parser_execute(), http_parser_pause(), main(), print_error(), test_content_length_overflow(), test_header_overflow_error(), test_message_pause(), and test_simple().
#define HTTP_PARSER_ERRNO (p) ((enum http_errno) (p)->http_errno)
#define http_parser_h
Definition at line 23 of file joyent_parser.cpp.
#define HTTP_PARSER_STRICT 1
Definition at line 52 of file http_parser.h.
#define HTTP_PARSER_VERSION_MAJOR 2
Definition at line 29 of file joyent_parser.cpp.
Referenced by http_parser_version().
#define HTTP_PARSER_VERSION_MAJOR 2
#define HTTP_PARSER_VERSION_MINOR 2
Definition at line 30 of file joyent_parser.cpp.
Referenced by http_parser_version().
#define HTTP_PARSER_VERSION_MINOR 2
#define HTTP_PARSER_VERSION_PATCH 1
Definition at line 31 of file joyent_parser.cpp.
Referenced by http_parser_version().
#define HTTP_PARSER_VERSION_PATCH 1
#define XX (num, name, string) HTTP_##name = num,
Definition at line 117 of file joyent_parser.cpp.
#define XX (num, name, string) HTTP_##name = num,
Typedef Documentation
typedef int(* http_cb)(http_parser *)
Definition at line 77 of file http_parser.h.
typedef int(* http_data_cb)(http_parser *, const char *at, size_t length)
Definition at line 76 of file http_parser.h.
typedef struct http_parser http_parser
Definition at line 59 of file http_parser.h.
typedef struct http_parser_settings http_parser_settings
Definition at line 60 of file http_parser.h.
Enumeration Type Documentation
enum flags
Enumerator
F_CHUNKED
F_CONNECTION_KEEP_ALIVE
F_CONNECTION_CLOSE
F_TRAILING
F_UPGRADE
F_SKIPBODY
Definition at line 126 of file http_parser.h.
   { F_CHUNKED               = 1 << 0
   , F_CONNECTION_KEEP_ALIVE = 1 << 1
   , F_CONNECTION_CLOSE      = 1 << 2
   , F_TRAILING              = 1 << 3
   , F_UPGRADE               = 1 << 4
   , F_SKIPBODY              = 1 << 5
   };
enum http_errno
Definition at line 184 of file http_parser.h.
                 {
   HTTP_ERRNO_MAP(HTTP_ERRNO_GEN)
 };
enum http_method
Definition at line 114 of file http_parser.h.
   {
 #define XX(num, name, string) HTTP_##name = num,
   HTTP_METHOD_MAP(XX)
 #undef XX
   };
enum http_parser_type
Enumerator
HTTP_REQUEST
HTTP_RESPONSE
HTTP_BOTH
Definition at line 122 of file http_parser.h.
 { HTTP_REQUEST, HTTP_RESPONSE, HTTP_BOTH };
enum http_parser_url_fields
Enumerator
UF_SCHEMA
UF_HOST
UF_PORT
UF_PATH
UF_QUERY
UF_FRAGMENT
UF_USERINFO
UF_MAX
Definition at line 236 of file http_parser.h.
   { UF_SCHEMA           = 0
   , UF_HOST             = 1
   , UF_PORT             = 2
   , UF_PATH             = 3
   , UF_QUERY            = 4
   , UF_FRAGMENT         = 5
   , UF_USERINFO         = 6
   , UF_MAX              = 7
   };
Function Documentation
int http_body_is_final (const http_parser * parser)
const char* http_errno_description (enum http_errno err)
Definition at line 1968 of file http_parser.c.
References http_strerror_tab.
Referenced by main(), and print_error().
{
   assert(err < (sizeof(http_strerror_tab)/sizeof(http_strerror_tab[0])));
   return http_strerror_tab[err].description;
 }
const char* http_errno_name (enum http_errno err)
Definition at line 1962 of file http_parser.c.
References http_strerror_tab.
Referenced by main(), and test_simple().
{
   assert(err < (sizeof(http_strerror_tab)/sizeof(http_strerror_tab[0])));
   return http_strerror_tab[err].name;
 }
const char* http_method_str (enum http_method m)
Definition at line 1944 of file http_parser.c.
References ELEM_AT, and method_strings.
Referenced by test_method_str().
 {
   return ELEM_AT(method_strings, m, "<unknown>");
 }
size_t http_parser_execute (http_parser * parser, const http_parser_settings * settings, const char * data, size_t len)
Definition at line 573 of file http_parser.c.
References CALLBACK_DATA, CALLBACK_DATA_, CALLBACK_DATA_NOADVANCE, CALLBACK_NOTIFY, CALLBACK_NOTIFY_NOADVANCE, CHUNKED, CLOSE, CONNECTION, CONTENT_LENGTH, http_parser::content_length, CR, F_CHUNKED, F_CONNECTION_CLOSE, F_CONNECTION_KEEP_ALIVE, F_SKIPBODY, F_TRAILING, F_UPGRADE, http_parser::flags, h_C, h_CO, h_CON, h_connection, h_connection_close, h_connection_keep_alive, h_content_length, h_general, h_matching_connection, h_matching_connection_close, h_matching_connection_keep_alive, h_matching_content_length, h_matching_proxy_connection, h_matching_transfer_encoding, h_matching_transfer_encoding_chunked, h_matching_upgrade, h_transfer_encoding, h_transfer_encoding_chunked, h_upgrade, http_parser::header_state, http_parser::http_major, HTTP_MAX_HEADER_SIZE, http_message_needs_eof(), http_parser::http_minor, HTTP_PARSER_ERRNO, HTTP_REQUEST, HTTP_RESPONSE, http_parser::index, IS_ALPHA, IS_NUM, KEEP_ALIVE, LF, LOWER, MARK, http_parser::method, method_strings, MIN, NEW_MESSAGE, http_parser::nread, http_parser_settings::on_headers_complete, parse_url_char(), PARSING_HEADER, PROXY_CONNECTION, s_body_identity, s_body_identity_eof, s_chunk_data, s_chunk_data_almost_done, s_chunk_data_done, s_chunk_parameters, s_chunk_size, s_chunk_size_almost_done, s_chunk_size_start, s_dead, s_header_almost_done, s_header_field, s_header_field_start, s_header_value, s_header_value_lws, s_header_value_start, s_headers_almost_done, s_headers_done, s_message_done, s_req_first_http_major, s_req_first_http_minor, s_req_fragment, s_req_fragment_start, s_req_http_H, s_req_http_HT, s_req_http_HTT, s_req_http_HTTP, s_req_http_major, s_req_http_minor, s_req_http_start, s_req_line_almost_done, s_req_method, s_req_path, s_req_query_string, s_req_query_string_start, s_req_schema, s_req_schema_slash, s_req_schema_slash_slash, s_req_server, s_req_server_start, s_req_server_with_at, s_req_spaces_before_url, s_res_first_http_major, s_res_first_http_minor, s_res_first_status_code, s_res_H, s_res_HT, s_res_HTT, s_res_HTTP, s_res_http_major, s_res_http_minor, s_res_line_almost_done, s_res_or_resp_H, s_res_status, s_res_status_code, s_res_status_start, s_start_req, s_start_req_or_res, s_start_res, SET_ERRNO, http_parser::state, http_parser::status_code, STRICT_CHECK, TOKEN, TRANSFER_ENCODING, http_parser::type, ULLONG_MAX, unhex, UPGRADE, and http_parser::upgrade.
Referenced by main(), parse(), parse_count_body(), parse_pause(), test_content_length_overflow(), test_header_overflow_error(), and test_no_overflow_long_body().
 {
   char c, ch;
   int8_t unhex_val;
   const char *p = data;
   const char *header_field_mark = 0;
   const char *header_value_mark = 0;
   const char *url_mark = 0;
   const char *body_mark = 0;
   const char *status_mark = 0;
   /* We're in an error state. Don't bother doing anything. */
   if (HTTP_PARSER_ERRNO(parser) != HPE_OK) {
     return 0;
   }
   if (len == 0) {
     switch (parser->state) {
       case s_body_identity_eof:
         /* Use of CALLBACK_NOTIFY() here would erroneously return 1 byte read if
          * we got paused.
          */
         CALLBACK_NOTIFY_NOADVANCE(message_complete);
         return 0;
       case s_dead:
       case s_start_req_or_res:
       case s_start_res:
       case s_start_req:
         return 0;
       default:
         SET_ERRNO(HPE_INVALID_EOF_STATE);
         return 1;
     }
   }
   if (parser->state == s_header_field)
     header_field_mark = data;
   if (parser->state == s_header_value)
     header_value_mark = data;
   switch (parser->state) {
   case s_req_path:
   case s_req_schema:
   case s_req_schema_slash:
   case s_req_schema_slash_slash:
   case s_req_server_start:
   case s_req_server:
   case s_req_server_with_at:
   case s_req_query_string_start:
   case s_req_query_string:
   case s_req_fragment_start:
   case s_req_fragment:
     url_mark = data;
     break;
   case s_res_status:
     status_mark = data;
     break;
   }
   for (p=data; p != data + len; p++) {
     ch = *p;
     if (PARSING_HEADER(parser->state)) {
       ++parser->nread;
       /* Don't allow the total size of the HTTP headers (including the status
        * line) to exceed HTTP_MAX_HEADER_SIZE.  This check is here to protect
        * embedders against denial-of-service attacks where the attacker feeds
        * us a never-ending header that the embedder keeps buffering.
        *
        * This check is arguably the responsibility of embedders but we're doing
        * it on the embedder's behalf because most won't bother and this way we
        * make the web a little safer.  HTTP_MAX_HEADER_SIZE is still far bigger
        * than any reasonable request or response so this should never affect
        * day-to-day operation.
        */
       if (parser->nread > HTTP_MAX_HEADER_SIZE) {
         SET_ERRNO(HPE_HEADER_OVERFLOW);
         goto error;
       }
     }
     reexecute_byte:
     switch (parser->state) {
       case s_dead:
         /* this state is used after a 'Connection: close' message
          * the parser will error out if it reads another message
          */
         if (ch == CR || ch == LF)
           break;
         SET_ERRNO(HPE_CLOSED_CONNECTION);
         goto error;
       case s_start_req_or_res:
       {
         if (ch == CR || ch == LF)
           break;
         parser->flags = 0;
         parser->content_length = ULLONG_MAX;
         if (ch == 'H') {
           parser->state = s_res_or_resp_H;
           CALLBACK_NOTIFY(message_begin);
         } else {
           parser->type = HTTP_REQUEST;
           parser->state = s_start_req;
           goto reexecute_byte;
         }
         break;
       }
       case s_res_or_resp_H:
         if (ch == 'T') {
           parser->type = HTTP_RESPONSE;
           parser->state = s_res_HT;
         } else {
           if (ch != 'E') {
             SET_ERRNO(HPE_INVALID_CONSTANT);
             goto error;
           }
           parser->type = HTTP_REQUEST;
           parser->method = HTTP_HEAD;
           parser->index = 2;
           parser->state = s_req_method;
         }
         break;
       case s_start_res:
       {
         parser->flags = 0;
         parser->content_length = ULLONG_MAX;
         switch (ch) {
           case 'H':
             parser->state = s_res_H;
             break;
           case CR:
           case LF:
             break;
           default:
             SET_ERRNO(HPE_INVALID_CONSTANT);
             goto error;
         }
         CALLBACK_NOTIFY(message_begin);
         break;
       }
       case s_res_H:
         STRICT_CHECK(ch != 'T');
         parser->state = s_res_HT;
         break;
       case s_res_HT:
         STRICT_CHECK(ch != 'T');
         parser->state = s_res_HTT;
         break;
       case s_res_HTT:
         STRICT_CHECK(ch != 'P');
         parser->state = s_res_HTTP;
         break;
       case s_res_HTTP:
         STRICT_CHECK(ch != '/');
         parser->state = s_res_first_http_major;
         break;
       case s_res_first_http_major:
         if (ch < '0' || ch > '9') {
           SET_ERRNO(HPE_INVALID_VERSION);
           goto error;
         }
         parser->http_major = ch - '0';
         parser->state = s_res_http_major;
         break;
       /* major HTTP version or dot */
       case s_res_http_major:
       {
         if (ch == '.') {
           parser->state = s_res_first_http_minor;
           break;
         }
         if (!IS_NUM(ch)) {
           SET_ERRNO(HPE_INVALID_VERSION);
           goto error;
         }
         parser->http_major *= 10;
         parser->http_major += ch - '0';
         if (parser->http_major > 999) {
           SET_ERRNO(HPE_INVALID_VERSION);
           goto error;
         }
         break;
       }
       /* first digit of minor HTTP version */
       case s_res_first_http_minor:
         if (!IS_NUM(ch)) {
           SET_ERRNO(HPE_INVALID_VERSION);
           goto error;
         }
         parser->http_minor = ch - '0';
         parser->state = s_res_http_minor;
         break;
       /* minor HTTP version or end of request line */
       case s_res_http_minor:
       {
         if (ch == ' ') {
           parser->state = s_res_first_status_code;
           break;
         }
         if (!IS_NUM(ch)) {
           SET_ERRNO(HPE_INVALID_VERSION);
           goto error;
         }
         parser->http_minor *= 10;
         parser->http_minor += ch - '0';
         if (parser->http_minor > 999) {
           SET_ERRNO(HPE_INVALID_VERSION);
           goto error;
         }
         break;
       }
       case s_res_first_status_code:
       {
         if (!IS_NUM(ch)) {
           if (ch == ' ') {
             break;
           }
           SET_ERRNO(HPE_INVALID_STATUS);
           goto error;
         }
         parser->status_code = ch - '0';
         parser->state = s_res_status_code;
         break;
       }
       case s_res_status_code:
       {
         if (!IS_NUM(ch)) {
           switch (ch) {
             case ' ':
               parser->state = s_res_status_start;
               break;
             case CR:
               parser->state = s_res_line_almost_done;
               break;
             case LF:
               parser->state = s_header_field_start;
               break;
             default:
               SET_ERRNO(HPE_INVALID_STATUS);
               goto error;
           }
           break;
         }
         parser->status_code *= 10;
         parser->status_code += ch - '0';
         if (parser->status_code > 999) {
           SET_ERRNO(HPE_INVALID_STATUS);
           goto error;
         }
         break;
       }
       case s_res_status_start:
       {
         if (ch == CR) {
           parser->state = s_res_line_almost_done;
           break;
         }
         if (ch == LF) {
           parser->state = s_header_field_start;
           break;
         }
         MARK(status);
         parser->state = s_res_status;
         parser->index = 0;
         break;
       }
       case s_res_status:
         if (ch == CR) {
           parser->state = s_res_line_almost_done;
           CALLBACK_DATA(status);
           break;
         }
         if (ch == LF) {
           parser->state = s_header_field_start;
           CALLBACK_DATA(status);
           break;
         }
         break;
       case s_res_line_almost_done:
         STRICT_CHECK(ch != LF);
         parser->state = s_header_field_start;
         break;
       case s_start_req:
       {
         if (ch == CR || ch == LF)
           break;
         parser->flags = 0;
         parser->content_length = ULLONG_MAX;
         if (!IS_ALPHA(ch)) {
           SET_ERRNO(HPE_INVALID_METHOD);
           goto error;
         }
         parser->method = (enum http_method) 0;
         parser->index = 1;
         switch (ch) {
           case 'C': parser->method = HTTP_CONNECT; /* or COPY, CHECKOUT */ break;
           case 'D': parser->method = HTTP_DELETE; break;
           case 'G': parser->method = HTTP_GET; break;
           case 'H': parser->method = HTTP_HEAD; break;
           case 'L': parser->method = HTTP_LOCK; break;
           case 'M': parser->method = HTTP_MKCOL; /* or MOVE, MKACTIVITY, MERGE, M-SEARCH */ break;
           case 'N': parser->method = HTTP_NOTIFY; break;
           case 'O': parser->method = HTTP_OPTIONS; break;
           case 'P': parser->method = HTTP_POST;
             /* or PROPFIND|PROPPATCH|PUT|PATCH|PURGE */
             break;
           case 'R': parser->method = HTTP_REPORT; break;
           case 'S': parser->method = HTTP_SUBSCRIBE; /* or SEARCH */ break;
           case 'T': parser->method = HTTP_TRACE; break;
           case 'U': parser->method = HTTP_UNLOCK; /* or UNSUBSCRIBE */ break;
           default:
             SET_ERRNO(HPE_INVALID_METHOD);
             goto error;
         }
         parser->state = s_req_method;
         CALLBACK_NOTIFY(message_begin);
         break;
       }
       case s_req_method:
       {
         const char *matcher;
         if (ch == '\0') {
           SET_ERRNO(HPE_INVALID_METHOD);
           goto error;
         }
         matcher = method_strings[parser->method];
         if (ch == ' ' && matcher[parser->index] == '\0') {
           parser->state = s_req_spaces_before_url;
         } else if (ch == matcher[parser->index]) {
           ; /* nada */
         } else if (parser->method == HTTP_CONNECT) {
           if (parser->index == 1 && ch == 'H') {
             parser->method = HTTP_CHECKOUT;
           } else if (parser->index == 2  && ch == 'P') {
             parser->method = HTTP_COPY;
           } else {
             SET_ERRNO(HPE_INVALID_METHOD);
             goto error;
           }
         } else if (parser->method == HTTP_MKCOL) {
           if (parser->index == 1 && ch == 'O') {
             parser->method = HTTP_MOVE;
           } else if (parser->index == 1 && ch == 'E') {
             parser->method = HTTP_MERGE;
           } else if (parser->index == 1 && ch == '-') {
             parser->method = HTTP_MSEARCH;
           } else if (parser->index == 2 && ch == 'A') {
             parser->method = HTTP_MKACTIVITY;
           } else {
             SET_ERRNO(HPE_INVALID_METHOD);
             goto error;
           }
         } else if (parser->method == HTTP_SUBSCRIBE) {
           if (parser->index == 1 && ch == 'E') {
             parser->method = HTTP_SEARCH;
           } else {
             SET_ERRNO(HPE_INVALID_METHOD);
             goto error;
           }
         } else if (parser->index == 1 && parser->method == HTTP_POST) {
           if (ch == 'R') {
             parser->method = HTTP_PROPFIND; /* or HTTP_PROPPATCH */
           } else if (ch == 'U') {
             parser->method = HTTP_PUT; /* or HTTP_PURGE */
           } else if (ch == 'A') {
             parser->method = HTTP_PATCH;
           } else {
             SET_ERRNO(HPE_INVALID_METHOD);
             goto error;
           }
         } else if (parser->index == 2) {
           if (parser->method == HTTP_PUT) {
             if (ch == 'R') {
               parser->method = HTTP_PURGE;
             } else {
               SET_ERRNO(HPE_INVALID_METHOD);
               goto error;
             }
           } else if (parser->method == HTTP_UNLOCK) {
             if (ch == 'S') {
               parser->method = HTTP_UNSUBSCRIBE;
             } else {
               SET_ERRNO(HPE_INVALID_METHOD);
               goto error;
             }
           } else {
             SET_ERRNO(HPE_INVALID_METHOD);
             goto error;
           }
         } else if (parser->index == 4 && parser->method == HTTP_PROPFIND && ch == 'P') {
           parser->method = HTTP_PROPPATCH;
         } else {
           SET_ERRNO(HPE_INVALID_METHOD);
           goto error;
         }
         ++parser->index;
         break;
       }
       case s_req_spaces_before_url:
       {
         if (ch == ' ') break;
         MARK(url);
         if (parser->method == HTTP_CONNECT) {
           parser->state = s_req_server_start;
         }
         parser->state = parse_url_char((enum state)parser->state, ch);
         if (parser->state == s_dead) {
           SET_ERRNO(HPE_INVALID_URL);
           goto error;
         }
         break;
       }
       case s_req_schema:
       case s_req_schema_slash:
       case s_req_schema_slash_slash:
       case s_req_server_start:
       {
         switch (ch) {
           /* No whitespace allowed here */
           case ' ':
           case CR:
           case LF:
             SET_ERRNO(HPE_INVALID_URL);
             goto error;
           default:
             parser->state = parse_url_char((enum state)parser->state, ch);
             if (parser->state == s_dead) {
               SET_ERRNO(HPE_INVALID_URL);
               goto error;
             }
         }
         break;
       }
       case s_req_server:
       case s_req_server_with_at:
       case s_req_path:
       case s_req_query_string_start:
       case s_req_query_string:
       case s_req_fragment_start:
       case s_req_fragment:
       {
         switch (ch) {
           case ' ':
             parser->state = s_req_http_start;
             CALLBACK_DATA(url);
             break;
           case CR:
           case LF:
             parser->http_major = 0;
             parser->http_minor = 9;
             parser->state = (ch == CR) ?
               s_req_line_almost_done :
               s_header_field_start;
             CALLBACK_DATA(url);
             break;
           default:
             parser->state = parse_url_char((enum state)parser->state, ch);
             if (parser->state == s_dead) {
               SET_ERRNO(HPE_INVALID_URL);
               goto error;
             }
         }
         break;
       }
       case s_req_http_start:
         switch (ch) {
           case 'H':
             parser->state = s_req_http_H;
             break;
           case ' ':
             break;
           default:
             SET_ERRNO(HPE_INVALID_CONSTANT);
             goto error;
         }
         break;
       case s_req_http_H:
         STRICT_CHECK(ch != 'T');
         parser->state = s_req_http_HT;
         break;
       case s_req_http_HT:
         STRICT_CHECK(ch != 'T');
         parser->state = s_req_http_HTT;
         break;
       case s_req_http_HTT:
         STRICT_CHECK(ch != 'P');
         parser->state = s_req_http_HTTP;
         break;
       case s_req_http_HTTP:
         STRICT_CHECK(ch != '/');
         parser->state = s_req_first_http_major;
         break;
       /* first digit of major HTTP version */
       case s_req_first_http_major:
         if (ch < '1' || ch > '9') {
           SET_ERRNO(HPE_INVALID_VERSION);
           goto error;
         }
         parser->http_major = ch - '0';
         parser->state = s_req_http_major;
         break;
       /* major HTTP version or dot */
       case s_req_http_major:
       {
         if (ch == '.') {
           parser->state = s_req_first_http_minor;
           break;
         }
         if (!IS_NUM(ch)) {
           SET_ERRNO(HPE_INVALID_VERSION);
           goto error;
         }
         parser->http_major *= 10;
         parser->http_major += ch - '0';
         if (parser->http_major > 999) {
           SET_ERRNO(HPE_INVALID_VERSION);
           goto error;
         }
         break;
       }
       /* first digit of minor HTTP version */
       case s_req_first_http_minor:
         if (!IS_NUM(ch)) {
           SET_ERRNO(HPE_INVALID_VERSION);
           goto error;
         }
         parser->http_minor = ch - '0';
         parser->state = s_req_http_minor;
         break;
       /* minor HTTP version or end of request line */
       case s_req_http_minor:
       {
         if (ch == CR) {
           parser->state = s_req_line_almost_done;
           break;
         }
         if (ch == LF) {
           parser->state = s_header_field_start;
           break;
         }
         /* XXX allow spaces after digit? */
         if (!IS_NUM(ch)) {
           SET_ERRNO(HPE_INVALID_VERSION);
           goto error;
         }
         parser->http_minor *= 10;
         parser->http_minor += ch - '0';
         if (parser->http_minor > 999) {
           SET_ERRNO(HPE_INVALID_VERSION);
           goto error;
         }
         break;
       }
       /* end of request line */
       case s_req_line_almost_done:
       {
         if (ch != LF) {
           SET_ERRNO(HPE_LF_EXPECTED);
           goto error;
         }
         parser->state = s_header_field_start;
         break;
       }
       case s_header_field_start:
       {
         if (ch == CR) {
           parser->state = s_headers_almost_done;
           break;
         }
         if (ch == LF) {
           /* they might be just sending \n instead of \r\n so this would be
            * the second \n to denote the end of headers*/
           parser->state = s_headers_almost_done;
           goto reexecute_byte;
         }
         c = TOKEN(ch);
         if (!c) {
           SET_ERRNO(HPE_INVALID_HEADER_TOKEN);
           goto error;
         }
         MARK(header_field);
         parser->index = 0;
         parser->state = s_header_field;
         switch (c) {
           case 'c':
             parser->header_state = h_C;
             break;
           case 'p':
             parser->header_state = h_matching_proxy_connection;
             break;
           case 't':
             parser->header_state = h_matching_transfer_encoding;
             break;
           case 'u':
             parser->header_state = h_matching_upgrade;
             break;
           default:
             parser->header_state = h_general;
             break;
         }
         break;
       }
       case s_header_field:
       {
         c = TOKEN(ch);
         if (c) {
           switch (parser->header_state) {
             case h_general:
               break;
             case h_C:
               parser->index++;
               parser->header_state = (c == 'o' ? h_CO : h_general);
               break;
             case h_CO:
               parser->index++;
               parser->header_state = (c == 'n' ? h_CON : h_general);
               break;
             case h_CON:
               parser->index++;
               switch (c) {
                 case 'n':
                   parser->header_state = h_matching_connection;
                   break;
                 case 't':
                   parser->header_state = h_matching_content_length;
                   break;
                 default:
                   parser->header_state = h_general;
                   break;
               }
               break;
             /* connection */
             case h_matching_connection:
               parser->index++;
               if (parser->index > sizeof(CONNECTION)-1
                   || c != CONNECTION[parser->index]) {
                 parser->header_state = h_general;
               } else if (parser->index == sizeof(CONNECTION)-2) {
                 parser->header_state = h_connection;
               }
               break;
             /* proxy-connection */
             case h_matching_proxy_connection:
               parser->index++;
               if (parser->index > sizeof(PROXY_CONNECTION)-1
                   || c != PROXY_CONNECTION[parser->index]) {
                 parser->header_state = h_general;
               } else if (parser->index == sizeof(PROXY_CONNECTION)-2) {
                 parser->header_state = h_connection;
               }
               break;
             /* content-length */
             case h_matching_content_length:
               parser->index++;
               if (parser->index > sizeof(CONTENT_LENGTH)-1
                   || c != CONTENT_LENGTH[parser->index]) {
                 parser->header_state = h_general;
               } else if (parser->index == sizeof(CONTENT_LENGTH)-2) {
                 parser->header_state = h_content_length;
               }
               break;
             /* transfer-encoding */
             case h_matching_transfer_encoding:
               parser->index++;
               if (parser->index > sizeof(TRANSFER_ENCODING)-1
                   || c != TRANSFER_ENCODING[parser->index]) {
                 parser->header_state = h_general;
               } else if (parser->index == sizeof(TRANSFER_ENCODING)-2) {
                 parser->header_state = h_transfer_encoding;
               }
               break;
             /* upgrade */
             case h_matching_upgrade:
               parser->index++;
               if (parser->index > sizeof(UPGRADE)-1
                   || c != UPGRADE[parser->index]) {
                 parser->header_state = h_general;
               } else if (parser->index == sizeof(UPGRADE)-2) {
                 parser->header_state = h_upgrade;
               }
               break;
             case h_connection:
             case h_content_length:
             case h_transfer_encoding:
             case h_upgrade:
               if (ch != ' ') parser->header_state = h_general;
               break;
             default:
               assert(0 && "Unknown header_state");
               break;
           }
           break;
         }
         if (ch == ':') {
           parser->state = s_header_value_start;
           CALLBACK_DATA(header_field);
           break;
         }
         if (ch == CR) {
           parser->state = s_header_almost_done;
           CALLBACK_DATA(header_field);
           break;
         }
         if (ch == LF) {
           parser->state = s_header_field_start;
           CALLBACK_DATA(header_field);
           break;
         }
         SET_ERRNO(HPE_INVALID_HEADER_TOKEN);
         goto error;
       }
       case s_header_value_start:
       {
         if (ch == ' ' || ch == '\t') break;
         MARK(header_value);
         parser->state = s_header_value;
         parser->index = 0;
         if (ch == CR) {
           parser->header_state = h_general;
           parser->state = s_header_almost_done;
           CALLBACK_DATA(header_value);
           break;
         }
         if (ch == LF) {
           parser->state = s_header_field_start;
           CALLBACK_DATA(header_value);
           break;
         }
         c = LOWER(ch);
         switch (parser->header_state) {
           case h_upgrade:
             parser->flags |= F_UPGRADE;
             parser->header_state = h_general;
             break;
           case h_transfer_encoding:
             /* looking for 'Transfer-Encoding: chunked' */
             if ('c' == c) {
               parser->header_state = h_matching_transfer_encoding_chunked;
             } else {
               parser->header_state = h_general;
             }
             break;
           case h_content_length:
             if (!IS_NUM(ch)) {
               SET_ERRNO(HPE_INVALID_CONTENT_LENGTH);
               goto error;
             }
             parser->content_length = ch - '0';
             break;
           case h_connection:
             /* looking for 'Connection: keep-alive' */
             if (c == 'k') {
               parser->header_state = h_matching_connection_keep_alive;
             /* looking for 'Connection: close' */
             } else if (c == 'c') {
               parser->header_state = h_matching_connection_close;
             } else {
               parser->header_state = h_general;
             }
             break;
           default:
             parser->header_state = h_general;
             break;
         }
         break;
       }
       case s_header_value:
       {
         if (ch == CR) {
           parser->state = s_header_almost_done;
           CALLBACK_DATA(header_value);
           break;
         }
         if (ch == LF) {
           parser->state = s_header_almost_done;
           CALLBACK_DATA_NOADVANCE(header_value);
           goto reexecute_byte;
         }
         c = LOWER(ch);
         switch (parser->header_state) {
           case h_general:
             break;
           case h_connection:
           case h_transfer_encoding:
             assert(0 && "Shouldn't get here.");
             break;
           case h_content_length:
           {
             uint64_t t;
             if (ch == ' ') break;
             if (!IS_NUM(ch)) {
               SET_ERRNO(HPE_INVALID_CONTENT_LENGTH);
               goto error;
             }
             t = parser->content_length;
             t *= 10;
             t += ch - '0';
             /* Overflow? Test against a conservative limit for simplicity. */
             if ((ULLONG_MAX - 10) / 10 < parser->content_length) {
               SET_ERRNO(HPE_INVALID_CONTENT_LENGTH);
               goto error;
             }
             parser->content_length = t;
             break;
           }
           /* Transfer-Encoding: chunked */
           case h_matching_transfer_encoding_chunked:
             parser->index++;
             if (parser->index > sizeof(CHUNKED)-1
                 || c != CHUNKED[parser->index]) {
               parser->header_state = h_general;
             } else if (parser->index == sizeof(CHUNKED)-2) {
               parser->header_state = h_transfer_encoding_chunked;
             }
             break;
           /* looking for 'Connection: keep-alive' */
           case h_matching_connection_keep_alive:
             parser->index++;
             if (parser->index > sizeof(KEEP_ALIVE)-1
                 || c != KEEP_ALIVE[parser->index]) {
               parser->header_state = h_general;
             } else if (parser->index == sizeof(KEEP_ALIVE)-2) {
               parser->header_state = h_connection_keep_alive;
             }
             break;
           /* looking for 'Connection: close' */
           case h_matching_connection_close:
             parser->index++;
             if (parser->index > sizeof(CLOSE)-1 || c != CLOSE[parser->index]) {
               parser->header_state = h_general;
             } else if (parser->index == sizeof(CLOSE)-2) {
               parser->header_state = h_connection_close;
             }
             break;
           case h_transfer_encoding_chunked:
           case h_connection_keep_alive:
           case h_connection_close:
             if (ch != ' ') parser->header_state = h_general;
             break;
           default:
             parser->state = s_header_value;
             parser->header_state = h_general;
             break;
         }
         break;
       }
       case s_header_almost_done:
       {
         STRICT_CHECK(ch != LF);
         parser->state = s_header_value_lws;
         switch (parser->header_state) {
           case h_connection_keep_alive:
             parser->flags |= F_CONNECTION_KEEP_ALIVE;
             break;
           case h_connection_close:
             parser->flags |= F_CONNECTION_CLOSE;
             break;
           case h_transfer_encoding_chunked:
             parser->flags |= F_CHUNKED;
             break;
           default:
             break;
         }
         break;
       }
       case s_header_value_lws:
       {
         if (ch == ' ' || ch == '\t')
           parser->state = s_header_value_start;
         else
         {
           parser->state = s_header_field_start;
           goto reexecute_byte;
         }
         break;
       }
       case s_headers_almost_done:
       {
         STRICT_CHECK(ch != LF);
         if (parser->flags & F_TRAILING) {
           /* End of a chunked request */
           parser->state = NEW_MESSAGE();
           CALLBACK_NOTIFY(message_complete);
           break;
         }
         parser->state = s_headers_done;
         /* Set this here so that on_headers_complete() callbacks can see it */
         parser->upgrade =
           (parser->flags & F_UPGRADE || parser->method == HTTP_CONNECT);
         /* Here we call the headers_complete callback. This is somewhat
          * different than other callbacks because if the user returns 1, we
          * will interpret that as saying that this message has no body. This
          * is needed for the annoying case of recieving a response to a HEAD
          * request.
          *
          * We'd like to use CALLBACK_NOTIFY_NOADVANCE() here but we cannot, so
          * we have to simulate it by handling a change in errno below.
          */
         if (settings->on_headers_complete) {
           switch (settings->on_headers_complete(parser)) {
             case 0:
               break;
             case 1:
               parser->flags |= F_SKIPBODY;
               break;
             default:
               SET_ERRNO(HPE_CB_headers_complete);
               return p - data; /* Error */
           }
         }
         if (HTTP_PARSER_ERRNO(parser) != HPE_OK) {
           return p - data;
         }
         goto reexecute_byte;
       }
       case s_headers_done:
       {
         STRICT_CHECK(ch != LF);
         parser->nread = 0;
         /* Exit, the rest of the connect is in a different protocol. */
         if (parser->upgrade) {
           parser->state = NEW_MESSAGE();
           CALLBACK_NOTIFY(message_complete);
           return (p - data) + 1;
         }
         if (parser->flags & F_SKIPBODY) {
           parser->state = NEW_MESSAGE();
           CALLBACK_NOTIFY(message_complete);
         } else if (parser->flags & F_CHUNKED) {
           /* chunked encoding - ignore Content-Length header */
           parser->state = s_chunk_size_start;
         } else {
           if (parser->content_length == 0) {
             /* Content-Length header given but zero: Content-Length: 0\r\n */
             parser->state = NEW_MESSAGE();
             CALLBACK_NOTIFY(message_complete);
           } else if (parser->content_length != ULLONG_MAX) {
             /* Content-Length header given and non-zero */
             parser->state = s_body_identity;
           } else {
             if (parser->type == HTTP_REQUEST ||
                 !http_message_needs_eof(parser)) {
               /* Assume content-length 0 - read the next */
               parser->state = NEW_MESSAGE();
               CALLBACK_NOTIFY(message_complete);
             } else {
               /* Read body until EOF */
               parser->state = s_body_identity_eof;
             }
           }
         }
         break;
       }
       case s_body_identity:
       {
         uint64_t to_read = MIN(parser->content_length,
                                (uint64_t) ((data + len) - p));
         assert(parser->content_length != 0
             && parser->content_length != ULLONG_MAX);
         /* The difference between advancing content_length and p is because
          * the latter will automaticaly advance on the next loop iteration.
          * Further, if content_length ends up at 0, we want to see the last
          * byte again for our message complete callback.
          */
         MARK(body);
         parser->content_length -= to_read;
         p += to_read - 1;
         if (parser->content_length == 0) {
           parser->state = s_message_done;
           /* Mimic CALLBACK_DATA_NOADVANCE() but with one extra byte.
            *
            * The alternative to doing this is to wait for the next byte to
            * trigger the data callback, just as in every other case. The
            * problem with this is that this makes it difficult for the test
            * harness to distinguish between complete-on-EOF and
            * complete-on-length. It's not clear that this distinction is
            * important for applications, but let's keep it for now.
            */
           CALLBACK_DATA_(body, p - body_mark + 1, p - data);
           goto reexecute_byte;
         }
         break;
       }
       /* read until EOF */
       case s_body_identity_eof:
         MARK(body);
         p = data + len - 1;
         break;
       case s_message_done:
         parser->state = NEW_MESSAGE();
         CALLBACK_NOTIFY(message_complete);
         break;
       case s_chunk_size_start:
       {
         assert(parser->nread == 1);
         assert(parser->flags & F_CHUNKED);
         unhex_val = unhex[(unsigned char)ch];
         if (unhex_val == -1) {
           SET_ERRNO(HPE_INVALID_CHUNK_SIZE);
           goto error;
         }
         parser->content_length = unhex_val;
         parser->state = s_chunk_size;
         break;
       }
       case s_chunk_size:
       {
         uint64_t t;
         assert(parser->flags & F_CHUNKED);
         if (ch == CR) {
           parser->state = s_chunk_size_almost_done;
           break;
         }
         unhex_val = unhex[(unsigned char)ch];
         if (unhex_val == -1) {
           if (ch == ';' || ch == ' ') {
             parser->state = s_chunk_parameters;
             break;
           }
           SET_ERRNO(HPE_INVALID_CHUNK_SIZE);
           goto error;
         }
         t = parser->content_length;
         t *= 16;
         t += unhex_val;
         /* Overflow? Test against a conservative limit for simplicity. */
         if ((ULLONG_MAX - 16) / 16 < parser->content_length) {
           SET_ERRNO(HPE_INVALID_CONTENT_LENGTH);
           goto error;
         }
         parser->content_length = t;
         break;
       }
       case s_chunk_parameters:
       {
         assert(parser->flags & F_CHUNKED);
         /* just ignore this shit. TODO check for overflow */
         if (ch == CR) {
           parser->state = s_chunk_size_almost_done;
           break;
         }
         break;
       }
       case s_chunk_size_almost_done:
       {
         assert(parser->flags & F_CHUNKED);
         STRICT_CHECK(ch != LF);
         parser->nread = 0;
         if (parser->content_length == 0) {
           parser->flags |= F_TRAILING;
           parser->state = s_header_field_start;
         } else {
           parser->state = s_chunk_data;
         }
         break;
       }
       case s_chunk_data:
       {
         uint64_t to_read = MIN(parser->content_length,
                                (uint64_t) ((data + len) - p));
         assert(parser->flags & F_CHUNKED);
         assert(parser->content_length != 0
             && parser->content_length != ULLONG_MAX);
         /* See the explanation in s_body_identity for why the content
          * length and data pointers are managed this way.
          */
         MARK(body);
         parser->content_length -= to_read;
         p += to_read - 1;
         if (parser->content_length == 0) {
           parser->state = s_chunk_data_almost_done;
         }
         break;
       }
       case s_chunk_data_almost_done:
         assert(parser->flags & F_CHUNKED);
         assert(parser->content_length == 0);
         STRICT_CHECK(ch != CR);
         parser->state = s_chunk_data_done;
         CALLBACK_DATA(body);
         break;
       case s_chunk_data_done:
         assert(parser->flags & F_CHUNKED);
         STRICT_CHECK(ch != LF);
         parser->nread = 0;
         parser->state = s_chunk_size_start;
         break;
       default:
         assert(0 && "unhandled state");
         SET_ERRNO(HPE_INVALID_INTERNAL_STATE);
         goto error;
     }
   }
   /* Run callbacks for any marks that we have leftover after we ran our of
    * bytes. There should be at most one of these set, so it's OK to invoke
    * them in series (unset marks will not result in callbacks).
    *
    * We use the NOADVANCE() variety of callbacks here because 'p' has already
    * overflowed 'data' and this allows us to correct for the off-by-one that
    * we'd otherwise have (since CALLBACK_DATA() is meant to be run with a 'p'
    * value that's in-bounds).
    */
   assert(((header_field_mark ? 1 : 0) +
           (header_value_mark ? 1 : 0) +
           (url_mark ? 1 : 0)  +
           (body_mark ? 1 : 0) +
           (status_mark ? 1 : 0)) <= 1);
   CALLBACK_DATA_NOADVANCE(header_field);
   CALLBACK_DATA_NOADVANCE(header_value);
   CALLBACK_DATA_NOADVANCE(url);
   CALLBACK_DATA_NOADVANCE(body);
   CALLBACK_DATA_NOADVANCE(status);
   return len;
 error:
   if (HTTP_PARSER_ERRNO(parser) == HPE_OK) {
     SET_ERRNO(HPE_UNKNOWN);
   }
   return (p - data);
 }
void http_parser_init (http_parser * parser, enum http_parser_type type)
Definition at line 1951 of file http_parser.c.
References http_parser::data, http_parser::http_errno, HTTP_REQUEST, HTTP_RESPONSE, s_start_req, s_start_req_or_res, s_start_res, http_parser::state, and http_parser::type.
Referenced by main(), parser_init(), beast::http::raw_parser::reset(), test_content_length_overflow(), test_header_overflow_error(), test_no_overflow_long_body(), and test_preserve_data().
 {
   void *data = parser->data; /* preserve application data */
   memset(parser, 0, sizeof(*parser));
   parser->data = data;
   parser->type = t;
   parser->state = (t == HTTP_REQUEST ? s_start_req : (t == HTTP_RESPONSE ? s_start_res : s_start_req_or_res));
   parser->http_errno = HPE_OK;
 }
int http_parser_parse_url (const char * buf, size_t buflen, int is_connect, struct http_parser_url * u)
Definition at line 2112 of file http_parser.c.
References http_parser_url::field_data, http_parser_url::field_set, http_parse_host(), http_parser_url::len, http_parser_url::off, parse_url_char(), http_parser_url::port, s_dead, s_req_fragment, s_req_fragment_start, s_req_path, s_req_query_string, s_req_query_string_start, s_req_schema, s_req_schema_slash, s_req_schema_slash_slash, s_req_server, s_req_server_start, s_req_server_with_at, s_req_spaces_before_url, UF_FRAGMENT, UF_HOST, UF_MAX, UF_PATH, UF_PORT, UF_QUERY, and UF_SCHEMA.
Referenced by main(), message_eq(), and test_parse_url().
 {
   enum state s;
   const char *p;
   enum http_parser_url_fields uf, old_uf;
   int found_at = 0;
   u->port = u->field_set = 0;
   s = is_connect ? s_req_server_start : s_req_spaces_before_url;
   uf = old_uf = UF_MAX;
   for (p = buf; p < buf + buflen; p++) {
     s = parse_url_char(s, *p);
     /* Figure out the next field that we're operating on */
     switch (s) {
       case s_dead:
         return 1;
       /* Skip delimeters */
       case s_req_schema_slash:
       case s_req_schema_slash_slash:
       case s_req_server_start:
       case s_req_query_string_start:
       case s_req_fragment_start:
         continue;
       case s_req_schema:
         uf = UF_SCHEMA;
         break;
       case s_req_server_with_at:
         found_at = 1;
       /* FALLTROUGH */
       case s_req_server:
         uf = UF_HOST;
         break;
       case s_req_path:
         uf = UF_PATH;
         break;
       case s_req_query_string:
         uf = UF_QUERY;
         break;
       case s_req_fragment:
         uf = UF_FRAGMENT;
         break;
       default:
         assert(!"Unexpected state");
         return 1;
     }
     /* Nothing's changed; soldier on */
     if (uf == old_uf) {
       u->field_data[uf].len++;
       continue;
     }
     u->field_data[uf].off = p - buf;
     u->field_data[uf].len = 1;
     u->field_set |= (1 << uf);
     old_uf = uf;
   }
   /* host must be present if there is a schema */
   /* parsing http:///toto will fail */
   if ((u->field_set & ((1 << UF_SCHEMA) | (1 << UF_HOST))) != 0) {
     if (http_parse_host(buf, u, found_at) != 0) {
       return 1;
     }
   }
   /* CONNECT requests can only contain "hostname:port" */
   if (is_connect && u->field_set != ((1 << UF_HOST)|(1 << UF_PORT))) {
     return 1;
   }
   if (u->field_set & (1 << UF_PORT)) {
     /* Don't bother with endp; we've already validated the string */
     unsigned long v = strtoul(buf + u->field_data[UF_PORT].off, NULL, 10);
     /* Ports have a max value of 2^16 */
     if (v > 0xffff) {
       return 1;
     }
     u->port = (uint16_t) v;
   }
   return 0;
 }
void http_parser_pause (http_parser * parser, int paused)
Definition at line 2211 of file http_parser.c.
References HTTP_PARSER_ERRNO, and SET_ERRNO.
Referenced by pause_body_cb(), pause_header_field_cb(), pause_header_value_cb(), pause_headers_complete_cb(), pause_message_begin_cb(), pause_message_complete_cb(), pause_request_url_cb(), pause_response_status_cb(), and test_message_pause().
{
   /* Users should only be pausing/unpausing a parser that is not in an error
    * state. In non-debug builds, there's not much that we can do about this
    * other than ignore it.
    */
   if (HTTP_PARSER_ERRNO(parser) == HPE_OK ||
       HTTP_PARSER_ERRNO(parser) == HPE_PAUSED) {
     SET_ERRNO((paused) ? HPE_PAUSED : HPE_OK);
   } else {
     assert(0 && "Attempting to pause parser in error state");
   }
 }
unsigned long http_parser_version (void)
Definition at line 2230 of file http_parser.c.
References HTTP_PARSER_VERSION_MAJOR, HTTP_PARSER_VERSION_MINOR, and HTTP_PARSER_VERSION_PATCH.
Referenced by main().
{
   return HTTP_PARSER_VERSION_MAJOR * 0x10000 |
          HTTP_PARSER_VERSION_MINOR * 0x00100 |
          HTTP_PARSER_VERSION_PATCH * 0x00001;
 }
int http_should_keep_alive (const http_parser * parser)
Definition at line 1925 of file http_parser.c.
References F_CONNECTION_CLOSE, F_CONNECTION_KEEP_ALIVE, http_parser::flags, http_parser::http_major, http_message_needs_eof(), and http_parser::http_minor.
Referenced by headers_complete_cb(), and message_complete_cb().
 {
   if (parser->http_major > 0 && parser->http_minor > 0) {
     /* HTTP/1.1 */
     if (parser->flags & F_CONNECTION_CLOSE) {
       return 0;
     }
   } else {
     /* HTTP/1.0 or earlier */
     if (!(parser->flags & F_CONNECTION_KEEP_ALIVE)) {
       return 0;
     }
   }
   return !http_message_needs_eof(parser);
 }