rippled: ripple::RPC::DoPrint Class Reference
ripple::RPC::DoPrint Class Reference
#include <DoPrint.h>
Public Member Functions
void operator() (Request &req)
Detailed Description
Definition at line 26 of file DoPrint.h.
Member Function Documentation
void ripple::RPC::DoPrint::operator() (Request & req) inline
Definition at line 29 of file DoPrint.h.
References ripple::RPC::Request::app, Json::Value::asString(), Json::Value::isArray(), Json::Value::isObject(), Json::Value::isString(), ripple::RPC::Request::params, ripple::RPC::Request::result, ripple::JsonPropertyStream::top(), and beast::PropertyStream::Source::write().
     {
         JsonPropertyStream stream;
         if (req.params.isObject() &&
             req.params["params"].isArray() &&
             req.params["params"][0u].isString ())
         {
             req.app.write (stream, req.params["params"][0u].asString());
         }
         else
         {
             req.app.write (stream);
         }
         req.result = stream.top();
     }
The documentation for this class was generated from the following file:
rippled/src/ripple_rpc/impl/DoPrint.h