rippled: beast::hash_append_tests::spooky Class Reference
beast::hash_append_tests::spooky Class Reference
Public Member Functions
spooky (std::size_t seed1=1, std::size_t seed2=2) noexcept
void append (void const *key, std::size_t len) noexcept
operator std::size_t () noexcept
Private Attributes
SpookyHash state_
Detailed Description
Definition at line 205 of file hash_append.test.cpp.
Constructor & Destructor Documentation
beast::hash_append_tests::spooky::spooky (std::size_t seed1 = 1, std::size_t seed2 = 2) inline noexcept
Definition at line 211 of file hash_append.test.cpp.
References SpookyHash::Init(), and state_.
     {
         state_.Init(seed1, seed2);
     }
Member Function Documentation
void beast::hash_append_tests::spooky::append (void const * key, std::size_t len) inline noexcept
Definition at line 217 of file hash_append.test.cpp.
References state_, and SpookyHash::Update().
     {
         state_.Update(key, len);
     }
beast::hash_append_tests::spooky::operator std::size_t () inline explicit noexcept
Definition at line 223 of file hash_append.test.cpp.
References SpookyHash::Final(), and state_.
     {
         std::uint64_t h1, h2;
         state_.Final(&h1, &h2);
         return h1;
     }
Member Data Documentation
SpookyHash beast::hash_append_tests::spooky::state_ private
Definition at line 208 of file hash_append.test.cpp.
Referenced by append(), operator std::size_t(), and spooky().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/container/tests/hash_append.test.cpp