rippled: beast::insight::detail::GroupImp Class Reference
beast::insight::detail::GroupImp Class Reference
Public Types
typedef std::vector
< std::shared_ptr< BaseImpl > > Items
Public Types inherited from beast::insight::Group
typedef std::shared_ptr< Group > ptr
Public Types inherited from beast::insight::Collector
typedef std::shared_ptr
< Collector > ptr
Public Member Functions
GroupImp (std::string const &name_, Collector::ptr const &collector)
~GroupImp ()
std::string const & name () const
std::string make_name (std::string const &name)
Hook make_hook (HookImpl::HandlerType const &handler)
Counter make_counter (std::string const &name)
Event make_event (std::string const &name)
Gauge make_gauge (std::string const &name)
Meter make_meter (std::string const &name)
Public Attributes
std::string const m_name
Collector::ptr m_collector
Private Member Functions
GroupImp & operator= (GroupImp const &)
Detailed Description
Definition at line 29 of file Groups.cpp.
Member Typedef Documentation
typedef std::vector<std::shared_ptr <BaseImpl> > beast::insight::detail::GroupImp::Items
Definition at line 34 of file Groups.cpp.
Constructor & Destructor Documentation
beast::insight::detail::GroupImp::GroupImp (std::string const & name_, Collector::ptr const & collector) inline
Definition at line 39 of file Groups.cpp.
         : m_name (name_)
         , m_collector (collector)
     {
     }
beast::insight::detail::GroupImp::~GroupImp () inline
Definition at line 46 of file Groups.cpp.
     {
     }
Member Function Documentation
Counter beast::insight::detail::GroupImp::make_counter (std::string const & name) inline virtual
Create a counter with the specified name.
See Also
Counter
Implements beast::insight::Collector.
Definition at line 65 of file Groups.cpp.
References m_collector, and make_name().
     {
         return m_collector->make_counter (make_name (name));
     }
Event beast::insight::detail::GroupImp::make_event (std::string const & name) inline virtual
Create an event with the specified name.
See Also
Event
Implements beast::insight::Collector.
Definition at line 70 of file Groups.cpp.
References m_collector, and make_name().
     {
         return m_collector->make_event (make_name (name));
     }
Gauge beast::insight::detail::GroupImp::make_gauge (std::string const & name) inline virtual
Create a gauge with the specified name.
See Also
Gauge
Implements beast::insight::Collector.
Definition at line 75 of file Groups.cpp.
References m_collector, and make_name().
     {
         return m_collector->make_gauge (make_name (name));
     }
Hook beast::insight::detail::GroupImp::make_hook (HookImpl::HandlerType const & handler) inline virtual
Implements beast::insight::Collector.
Definition at line 60 of file Groups.cpp.
References m_collector.
     {
         return m_collector->make_hook (handler);
     }
Meter beast::insight::detail::GroupImp::make_meter (std::string const & name) inline virtual
Create a meter with the specified name.
See Also
Meter
Implements beast::insight::Collector.
Definition at line 80 of file Groups.cpp.
References m_collector, and make_name().
     {
         return m_collector->make_meter (make_name (name));
     }
std::string beast::insight::detail::GroupImp::make_name (std::string const & name) inline
Definition at line 55 of file Groups.cpp.
References m_name, and name().
Referenced by make_counter(), make_event(), make_gauge(), and make_meter().
     {
         return m_name + "." + name;
     }
std::string const& beast::insight::detail::GroupImp::name () const inline virtual
Returns the name of this group, for diagnostics.
Implements beast::insight::Group.
Definition at line 50 of file Groups.cpp.
References m_name.
Referenced by make_name().
     {
         return m_name;
     }
GroupImp& beast::insight::detail::GroupImp::operator= (GroupImp const &) private
Member Data Documentation
Collector::ptr beast::insight::detail::GroupImp::m_collector
Definition at line 37 of file Groups.cpp.
Referenced by make_counter(), make_event(), make_gauge(), make_hook(), and make_meter().
std::string const beast::insight::detail::GroupImp::m_name
Definition at line 36 of file Groups.cpp.
Referenced by make_name(), and name().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/insight/impl/Groups.cpp