rippled: beast::sqdb::blob Class Reference
beast::sqdb::blob Class Reference
#include <blob.h>
Public Member Functions
blob ()
~blob ()
Error select (session &s, char const *zTable, char const *zColumn, rowid id, bool readAndWrite=false) noexcept
int get_len ()
Error read (int offset, void *buf, int toRead)
Error write (int offset, void const *buf, int toWrite)
void close ()
Private Attributes
session * m_session
sqlite3_blob * m_blob
Detailed Description
Definition at line 67 of file blob.h.
Constructor & Destructor Documentation
beast::sqdb::blob::blob ()
Definition at line 63 of file blob.cpp.
     : m_blob(0)
 {
 }
beast::sqdb::blob::~blob ()
Definition at line 68 of file blob.cpp.
References close().
 {
     close();
 }
Member Function Documentation
void beast::sqdb::blob::close ()
Definition at line 111 of file blob.cpp.
References m_blob, and sqlite3_blob_close.
Referenced by ~blob().
 {
     if (m_blob)
     {
         sqlite3_blob_close(m_blob);
         m_blob = 0;
     }
 }
int beast::sqdb::blob::get_len ()
Definition at line 94 of file blob.cpp.
References m_blob, and sqlite3_blob_bytes.
 {
     return sqlite3_blob_bytes(m_blob);
 }
Error beast::sqdb::blob::read (int offset, void * buf, int toRead)
Definition at line 99 of file blob.cpp.
References m_blob, sqlite3_blob_read, and beast::sqdb::detail::sqliteError().
 {
     return detail::sqliteError(__FILE__, __LINE__,
                                sqlite3_blob_read(m_blob, static_cast<char*>(buf), toRead, offset));
 }
Error beast::sqdb::blob::select (session & s, char const * zTable, char const * zColumn, rowid id, bool readAndWrite = false) noexcept
Definition at line 73 of file blob.cpp.
References id, sqlite3_blob_open, and beast::sqdb::detail::sqliteError().
 {
     close();
     m_session = &s;
     int result = sqlite3_blob_open(s.get_connection(),
     "main",
     zTable,
     zColumn,
     id,
     readAndWrite ? 1 : 0,
     &m_blob);
     return detail::sqliteError(__FILE__, __LINE__, result);
 }
Error beast::sqdb::blob::write (int offset, void const * buf, int toWrite)
Definition at line 105 of file blob.cpp.
References m_blob, sqlite3_blob_write, and beast::sqdb::detail::sqliteError().
 {
     return detail::sqliteError(__FILE__, __LINE__,
                                sqlite3_blob_write(m_blob, buf, toWrite, offset));
 }
Member Data Documentation
sqlite3_blob* beast::sqdb::blob::m_blob private
Definition at line 86 of file blob.h.
Referenced by close(), get_len(), read(), and write().
session* beast::sqdb::blob::m_session private
Definition at line 85 of file blob.h.
The documentation for this class was generated from the following files:
rippled/src/beast/modules/beast_sqdb/api/blob.h
rippled/src/beast/modules/beast_sqdb/source/blob.cpp