rippled: beast::asio::abstract_socket Class Reference
beast::asio::abstract_socket Class Reference
#include <abstract_socket.h>
Public Member Functions
virtual ~abstract_socket ()
virtual void * this_layer_ptr (char const *type_name) const BEAST_SOCKET_VIRTUAL
template<typename Handle >
void native_handle (Handle *dest)
virtual bool native_handle (char const *type_name, void *dest) BEAST_SOCKET_VIRTUAL
virtual boost::asio::io_service & get_io_service () BEAST_SOCKET_VIRTUAL
virtual void * lowest_layer_ptr (char const *type_name) const BEAST_SOCKET_VIRTUAL
void cancel ()
virtual error_code cancel (error_code &ec) BEAST_SOCKET_VIRTUAL
void shutdown (shutdown_type what)
virtual error_code shutdown (shutdown_type what, error_code &ec) BEAST_SOCKET_VIRTUAL
void close ()
virtual error_code close (error_code &ec) BEAST_SOCKET_VIRTUAL
virtual error_code accept (abstract_socket &peer, error_code &ec) BEAST_SOCKET_VIRTUAL
virtual void async_accept (abstract_socket &peer, error_handler handler) BEAST_SOCKET_VIRTUAL
virtual std::size_t read_some (mutable_buffers buffers, error_code &ec) BEAST_SOCKET_VIRTUAL
virtual std::size_t write_some (const_buffers buffers, error_code &ec) BEAST_SOCKET_VIRTUAL
virtual void async_read_some (mutable_buffers buffers, transfer_handler handler) BEAST_SOCKET_VIRTUAL
virtual void async_write_some (const_buffers buffers, transfer_handler handler) BEAST_SOCKET_VIRTUAL
virtual void * next_layer_ptr (char const *type_name) const BEAST_SOCKET_VIRTUAL
virtual bool needs_handshake () BEAST_SOCKET_VIRTUAL
virtual void set_verify_mode (int verify_mode) BEAST_SOCKET_VIRTUAL
void handshake (handshake_type type)
virtual error_code handshake (handshake_type type, error_code &ec) BEAST_SOCKET_VIRTUAL
virtual void async_handshake (handshake_type type, error_handler handler) BEAST_SOCKET_VIRTUAL
virtual error_code handshake (handshake_type type, const_buffers buffers, error_code &ec) BEAST_SOCKET_VIRTUAL
virtual void async_handshake (handshake_type type, const_buffers buffers, transfer_handler handler) BEAST_SOCKET_VIRTUAL
void shutdown ()
virtual error_code shutdown (error_code &ec) BEAST_SOCKET_VIRTUAL
virtual void async_shutdown (error_handler handler) BEAST_SOCKET_VIRTUAL
template<class Object >
Object & this_layer ()
template<class Object >
Object const & this_layer () const
template<class Object >
Object * this_layer_ptr ()
template<class Object >
Object const * this_layer_ptr () const
template<class Object >
Object & lowest_layer ()
template<class Object >
Object const & lowest_layer () const
template<class Object >
Object * lowest_layer_ptr ()
template<class Object >
Object const * lowest_layer_ptr () const
template<class Object >
Object & next_layer ()
template<class Object >
Object const & next_layer () const
template<class Object >
Object * next_layer_ptr ()
template<class Object >
Object const * next_layer_ptr () const
Protected Types
typedef boost::system::error_code error_code
typedef asio::shared_handler
< void(void)> post_handler
typedef asio::shared_handler
< void(error_code)> error_handler
typedef asio::shared_handler
< void(error_code, std::size_t)> transfer_handler
Static Protected Member Functions
static void pure_virtual_called ()
static error_code pure_virtual_error ()
static error_code pure_virtual_error (error_code &ec)
static void throw_if (error_code const &ec)
Detailed Description
A high level socket abstraction.
This combines the capabilities of multiple socket interfaces such as listening, connecting, streaming, and handshaking. It brings everything together into a single abstract interface.
When member functions are called and the underlying implementation does not support the operation, a fatal error is generated.
Definition at line 52 of file abstract_socket.h.
Member Typedef Documentation
typedef boost::system::error_code beast::asio::abstract_socket::error_code protected
Definition at line 57 of file abstract_socket.h.
typedef asio::shared_handler<void (error_code)> beast::asio::abstract_socket::error_handler protected
Definition at line 61 of file abstract_socket.h.
typedef asio::shared_handler<void (void)> beast::asio::abstract_socket::post_handler protected
Definition at line 59 of file abstract_socket.h.
typedef asio::shared_handler< void (error_code, std::size_t)> beast::asio::abstract_socket::transfer_handler protected
Definition at line 64 of file abstract_socket.h.
Constructor & Destructor Documentation
virtual beast::asio::abstract_socket::~abstract_socket () inline virtual
Definition at line 98 of file abstract_socket.h.
     {
     }
Member Function Documentation
auto beast::asio::abstract_socket::accept (abstract_socket & peer, error_code & ec) virtual
Reimplemented in beast::asio::socket_wrapper< Object >, beast::asio::socket_wrapper< socket_type & >, and beast::asio::socket_wrapper< acceptor_type & >.
Definition at line 102 of file abstract_socket.cpp.
 {
     return pure_virtual_error (ec);
 }
void beast::asio::abstract_socket::async_accept (abstract_socket & peer, error_handler handler) virtual
Reimplemented in beast::asio::socket_wrapper< Object >, beast::asio::socket_wrapper< socket_type & >, and beast::asio::socket_wrapper< acceptor_type & >.
Definition at line 108 of file abstract_socket.cpp.
References beast::asio::bind_handler(), get_io_service(), and pure_virtual_error().
 {
     get_io_service ().post (bind_handler (
         handler, pure_virtual_error()));
 }
void beast::asio::abstract_socket::async_handshake (handshake_type type, error_handler handler) virtual
Reimplemented in beast::asio::socket_wrapper< Object >, beast::asio::socket_wrapper< socket_type & >, beast::asio::socket_wrapper< acceptor_type & >, ripple::MultiSocketType< StreamSocket >, and ripple::MultiSocketType< socket_type & >.
Definition at line 180 of file abstract_socket.cpp.
References beast::asio::bind_handler(), get_io_service(), and pure_virtual_error().
Referenced by beast::asio::TestPeerLogicAsyncClient::on_connect_async(), and beast::asio::TestPeerLogicAsyncServer::on_connect_async().
 {
     get_io_service ().post (bind_handler (
         handler, pure_virtual_error()));
 }
void beast::asio::abstract_socket::async_handshake (handshake_type type, const_buffers buffers, transfer_handler handler) virtual
Reimplemented in beast::asio::socket_wrapper< Object >, beast::asio::socket_wrapper< socket_type & >, and beast::asio::socket_wrapper< acceptor_type & >.
Definition at line 194 of file abstract_socket.cpp.
References beast::asio::bind_handler(), get_io_service(), and pure_virtual_error().
 {
     get_io_service ().post (bind_handler (
         handler, pure_virtual_error(), 0));
 }
void beast::asio::abstract_socket::async_read_some (mutable_buffers buffers, transfer_handler handler) virtual
Reimplemented in beast::asio::socket_wrapper< Object >, beast::asio::socket_wrapper< socket_type & >, beast::asio::socket_wrapper< acceptor_type & >, ripple::MultiSocketType< StreamSocket >, and ripple::MultiSocketType< socket_type & >.
Definition at line 135 of file abstract_socket.cpp.
References beast::asio::bind_handler(), get_io_service(), and pure_virtual_error().
Referenced by ripple::MultiSocketType< socket_type & >::async_read_some().
 {
     get_io_service ().post (bind_handler (
         handler, pure_virtual_error(), 0));
 }
void beast::asio::abstract_socket::async_shutdown (error_handler handler) virtual
Reimplemented in beast::asio::socket_wrapper< Object >, beast::asio::socket_wrapper< socket_type & >, beast::asio::socket_wrapper< acceptor_type & >, ripple::MultiSocketType< StreamSocket >, and ripple::MultiSocketType< socket_type & >.
Definition at line 208 of file abstract_socket.cpp.
References beast::asio::bind_handler(), get_io_service(), and pure_virtual_error().
Referenced by ripple::MultiSocketType< socket_type & >::async_shutdown(), beast::asio::TestPeerLogicAsyncClient::on_read_final(), and beast::asio::TestPeerLogicAsyncServer::on_write().
 {
     get_io_service ().post (bind_handler (
         handler, pure_virtual_error()));
 }
void beast::asio::abstract_socket::async_write_some (const_buffers buffers, transfer_handler handler) virtual
Reimplemented in beast::asio::socket_wrapper< Object >, beast::asio::socket_wrapper< socket_type & >, beast::asio::socket_wrapper< acceptor_type & >, ripple::MultiSocketType< StreamSocket >, and ripple::MultiSocketType< socket_type & >.
Definition at line 142 of file abstract_socket.cpp.
References beast::asio::bind_handler(), get_io_service(), and pure_virtual_error().
Referenced by ripple::MultiSocketType< socket_type & >::async_write_some().
 {
     get_io_service ().post (bind_handler (
         handler, pure_virtual_error(), 0));
 }
void beast::asio::abstract_socket::cancel () inline
Definition at line 233 of file abstract_socket.h.
References throw_if().
Referenced by beast::asio::socket_wrapper< acceptor_type & >::cancel().
     {
         error_code ec;
         cancel (ec);
         throw_if (ec);
     }
auto beast::asio::abstract_socket::cancel (error_code & ec) virtual
Reimplemented in beast::asio::socket_wrapper< Object >, beast::asio::socket_wrapper< socket_type & >, beast::asio::socket_wrapper< acceptor_type & >, ripple::MultiSocketType< StreamSocket >, and ripple::MultiSocketType< socket_type & >.
Definition at line 78 of file abstract_socket.cpp.
 {
     return pure_virtual_error (ec);
 }
void beast::asio::abstract_socket::close () inline
Definition at line 254 of file abstract_socket.h.
References throw_if().
Referenced by beast::asio::socket_wrapper< acceptor_type & >::close().
     {
         error_code ec;
         close (ec);
         throw_if (ec);
     }
auto beast::asio::abstract_socket::close (error_code & ec) virtual
Reimplemented in beast::asio::socket_wrapper< Object >, beast::asio::socket_wrapper< socket_type & >, beast::asio::socket_wrapper< acceptor_type & >, ripple::MultiSocketType< StreamSocket >, and ripple::MultiSocketType< socket_type & >.
Definition at line 90 of file abstract_socket.cpp.
 {
     return pure_virtual_error (ec);
 }
boost::asio::io_service & beast::asio::abstract_socket::get_io_service () virtual
Reimplemented in beast::asio::socket_wrapper< Object >, beast::asio::socket_wrapper< socket_type & >, beast::asio::socket_wrapper< acceptor_type & >, ripple::MultiSocketType< StreamSocket >, and ripple::MultiSocketType< socket_type & >.
Definition at line 58 of file abstract_socket.cpp.
References pure_virtual_called().
Referenced by async_accept(), async_handshake(), async_read_some(), async_shutdown(), and async_write_some().
 {
     pure_virtual_called ();
     return *static_cast <boost::asio::io_service*>(nullptr);
 }
void beast::asio::abstract_socket::handshake (handshake_type type) inline
Definition at line 362 of file abstract_socket.h.
References throw_if().
Referenced by ripple::MultiSocketType< socket_type & >::do_handshake().
     {
         error_code ec;
         handshake (type, ec);
         throw_if (ec);
     }
auto beast::asio::abstract_socket::handshake (handshake_type type, error_code & ec) virtual
Reimplemented in beast::asio::socket_wrapper< Object >, beast::asio::socket_wrapper< socket_type & >, and beast::asio::socket_wrapper< acceptor_type & >.
Definition at line 174 of file abstract_socket.cpp.
 {
     return pure_virtual_error (ec);
 }
auto beast::asio::abstract_socket::handshake (handshake_type type, const_buffers buffers, error_code & ec) virtual
Reimplemented in beast::asio::socket_wrapper< Object >, beast::asio::socket_wrapper< socket_type & >, beast::asio::socket_wrapper< acceptor_type & >, ripple::MultiSocketType< StreamSocket >, and ripple::MultiSocketType< socket_type & >.
Definition at line 187 of file abstract_socket.cpp.
 {
     return pure_virtual_error (ec);
 }
template<class Object > Object& beast::asio::abstract_socket::lowest_layer () inline
Retrieve the lowest layer object.
Note
If the type doesn't match, nullptr is returned or an exception is thrown if trying to acquire a reference.
Definition at line 196 of file abstract_socket.h.
     {
         Object* object (this->lowest_layer_ptr <Object> ());
         if (object == nullptr)
             throw std::bad_cast ();
         return *object;
     }
template<class Object > Object const& beast::asio::abstract_socket::lowest_layer () const inline
Definition at line 205 of file abstract_socket.h.
     {
         Object const* object (this->lowest_layer_ptr <Object> ());
         if (object == nullptr)
             throw std::bad_cast ();
         return *object;
     }
template<class Object > Object* beast::asio::abstract_socket::lowest_layer_ptr () inline
Definition at line 214 of file abstract_socket.h.
References name.
Referenced by lowest_layer_ptr(), and beast::asio::socket_wrapper< acceptor_type & >::lowest_layer_ptr().
     {
         return static_cast <Object*> (
             this->lowest_layer_ptr (typeid (Object).name ()));
     }
template<class Object > Object const* beast::asio::abstract_socket::lowest_layer_ptr () const inline
Definition at line 221 of file abstract_socket.h.
References lowest_layer_ptr(), and name.
     {
         return static_cast <Object const*> (
             this->lowest_layer_ptr (typeid (Object).name ()));
     }
void * beast::asio::abstract_socket::lowest_layer_ptr (char const * type_name) const virtual
Reimplemented in beast::asio::socket_wrapper< Object >, beast::asio::socket_wrapper< socket_type & >, beast::asio::socket_wrapper< acceptor_type & >, ripple::MultiSocketType< StreamSocket >, and ripple::MultiSocketType< socket_type & >.
Definition at line 71 of file abstract_socket.cpp.
References pure_virtual_called().
 {
     pure_virtual_called ();
     return nullptr;
 }
template<typename Handle > void beast::asio::abstract_socket::native_handle (Handle * dest) inline
Retrieve the native representation of the object.
Since we dont know the return type, and because almost every asio implementation passes the result by value, you need to provide a pointer to a default-constructed object of the matching type.
Note
If the type doesn't match, an exception is thrown.
Definition at line 165 of file abstract_socket.h.
References name.
     {
         if (! native_handle (typeid (Handle).name (), dest))
             throw std::bad_cast ();
     }
bool beast::asio::abstract_socket::native_handle (char const * type_name, void * dest) virtual
Reimplemented in ripple::MultiSocketType< StreamSocket >, ripple::MultiSocketType< socket_type & >, beast::asio::socket_wrapper< Object >, beast::asio::socket_wrapper< socket_type & >, and beast::asio::socket_wrapper< acceptor_type & >.
Definition at line 46 of file abstract_socket.cpp.
References pure_virtual_called().
 {
     pure_virtual_called ();
     return false;
 }
bool beast::asio::abstract_socket::needs_handshake () virtual
Determines if the underlying stream requires a handshake.
If needs_handshake is true, it will be necessary to call handshake or async_handshake after the connection is established. Furthermore it will be necessary to call the shutdown member from the HandshakeInterface to close the connection. Do not close the underlying socket or else the closure will not be graceful. Only one side should initiate the handshaking shutdon. The other side should observe it. Which side does what is up to the user.
The default version returns false.
Reimplemented in beast::asio::socket_wrapper< Object >, beast::asio::socket_wrapper< socket_type & >, beast::asio::socket_wrapper< acceptor_type & >, ripple::MultiSocketType< StreamSocket >, and ripple::MultiSocketType< socket_type & >.
Definition at line 162 of file abstract_socket.cpp.
 {
     return false;
 }
template<class Object > Object& beast::asio::abstract_socket::next_layer () inline
Retrieve the next layer object.
Note
If the type doesn't match, nullptr is returned or an exception is thrown if trying to acquire a reference.
Definition at line 309 of file abstract_socket.h.
     {
         Object* object (this->next_layer_ptr <Object> ());
         if (object == nullptr)
             throw std::bad_cast ();
         return *object;
     }
template<class Object > Object const& beast::asio::abstract_socket::next_layer () const inline
Definition at line 318 of file abstract_socket.h.
     {
         Object const* object (this->next_layer_ptr <Object> ());
         if (object == nullptr)
             throw std::bad_cast ();
         return *object;
     }
template<class Object > Object* beast::asio::abstract_socket::next_layer_ptr () inline
Definition at line 327 of file abstract_socket.h.
References name.
Referenced by next_layer_ptr(), and beast::asio::socket_wrapper< acceptor_type & >::next_layer_ptr().
     {
         return static_cast <Object*> (
             this->next_layer_ptr (typeid (Object).name ()));
     }
template<class Object > Object const* beast::asio::abstract_socket::next_layer_ptr () const inline
Definition at line 334 of file abstract_socket.h.
References name, and next_layer_ptr().
     {
         return static_cast <Object const*> (
             this->next_layer_ptr (typeid (Object).name ()));
     }
void * beast::asio::abstract_socket::next_layer_ptr (char const * type_name) const virtual
Reimplemented in beast::asio::socket_wrapper< Object >, beast::asio::socket_wrapper< socket_type & >, beast::asio::socket_wrapper< acceptor_type & >, ripple::MultiSocketType< StreamSocket >, and ripple::MultiSocketType< socket_type & >.
Definition at line 155 of file abstract_socket.cpp.
References pure_virtual_called().
 {
     pure_virtual_called ();
     return nullptr;
 }
static void beast::asio::abstract_socket::pure_virtual_called () inline static protected
Definition at line 68 of file abstract_socket.h.
Referenced by beast::asio::socket_wrapper< Object >::native_socket< T, Enable >::get(), get_io_service(), beast::asio::socket_wrapper< acceptor_type & >::get_io_service(), lowest_layer_ptr(), beast::asio::socket_wrapper< acceptor_type & >::lowest_layer_ptr(), native_handle(), ripple::MultiSocketType< socket_type & >::native_handle(), beast::asio::socket_wrapper< acceptor_type & >::native_handle(), beast::asio::socket_wrapper< Object >::native_socket< T, Enable >::native_socket(), next_layer_ptr(), beast::asio::socket_wrapper< acceptor_type & >::next_layer_ptr(), pure_virtual_error(), set_verify_mode(), beast::asio::socket_wrapper< acceptor_type & >::set_verify_mode(), and this_layer_ptr().
     {
         throw std::runtime_error ("pure virtual called");
     }
static error_code beast::asio::abstract_socket::pure_virtual_error () inline static protected
Definition at line 75 of file abstract_socket.h.
References pure_virtual_called().
Referenced by beast::asio::socket_wrapper< acceptor_type & >::accept(), async_accept(), beast::asio::socket_wrapper< acceptor_type & >::async_accept(), async_handshake(), beast::asio::socket_wrapper< acceptor_type & >::async_handshake(), async_read_some(), beast::asio::socket_wrapper< acceptor_type & >::async_read_some(), async_shutdown(), beast::asio::socket_wrapper< acceptor_type & >::async_shutdown(), async_write_some(), beast::asio::socket_wrapper< acceptor_type & >::async_write_some(), beast::asio::socket_wrapper< acceptor_type & >::cancel(), beast::asio::socket_wrapper< acceptor_type & >::close(), beast::asio::socket_wrapper< acceptor_type & >::handshake(), pure_virtual_error(), read_some(), beast::asio::socket_wrapper< acceptor_type & >::read_some(), beast::asio::socket_wrapper< acceptor_type & >::shutdown(), write_some(), and beast::asio::socket_wrapper< acceptor_type & >::write_some().
     {
         pure_virtual_called();
         return boost::system::errc::make_error_code (
             boost::system::errc::function_not_supported);
     }
static error_code beast::asio::abstract_socket::pure_virtual_error (error_code & ec) inline static protected
Definition at line 84 of file abstract_socket.h.
References pure_virtual_error().
     {
         return ec = pure_virtual_error();
     }
std::size_t beast::asio::abstract_socket::read_some (mutable_buffers buffers, error_code & ec) virtual
Reimplemented in beast::asio::socket_wrapper< Object >, beast::asio::socket_wrapper< socket_type & >, beast::asio::socket_wrapper< acceptor_type & >, ripple::MultiSocketType< StreamSocket >, and ripple::MultiSocketType< socket_type & >.
Definition at line 121 of file abstract_socket.cpp.
References pure_virtual_error().
Referenced by ripple::MultiSocketType< socket_type & >::read_some().
 {
     ec = pure_virtual_error ();
     return 0;
 }
void beast::asio::abstract_socket::set_verify_mode (int verify_mode) virtual
Reimplemented in beast::asio::socket_wrapper< Object >, beast::asio::socket_wrapper< socket_type & >, beast::asio::socket_wrapper< acceptor_type & >, ripple::MultiSocketType< StreamSocket >, and ripple::MultiSocketType< socket_type & >.
Definition at line 168 of file abstract_socket.cpp.
References pure_virtual_called().
 {
     pure_virtual_called ();
 }
void beast::asio::abstract_socket::shutdown (shutdown_type what) inline
Definition at line 243 of file abstract_socket.h.
References shutdown(), and throw_if().
Referenced by beast::asio::TestPeerLogicAsyncServer::on_shutdown(), beast::asio::TestPeerLogicAsyncClient::on_shutdown(), and ripple::MultiSocketType< socket_type & >::shutdown().
     {
         error_code ec;
         shutdown (what, ec);
         throw_if (ec);
     }
auto beast::asio::abstract_socket::shutdown (shutdown_type what, error_code & ec) virtual
Reimplemented in beast::asio::socket_wrapper< Object >, beast::asio::socket_wrapper< socket_type & >, and beast::asio::socket_wrapper< acceptor_type & >.
Definition at line 84 of file abstract_socket.cpp.
 {
     return pure_virtual_error (ec);
 }
void beast::asio::abstract_socket::shutdown () inline
Definition at line 387 of file abstract_socket.h.
References throw_if().
Referenced by shutdown(), and beast::asio::socket_wrapper< acceptor_type & >::shutdown().
     {
         error_code ec;
         shutdown (ec);
         throw_if (ec);
     }
auto beast::asio::abstract_socket::shutdown (error_code & ec) virtual
Reimplemented in beast::asio::socket_wrapper< Object >, beast::asio::socket_wrapper< socket_type & >, beast::asio::socket_wrapper< acceptor_type & >, ripple::MultiSocketType< StreamSocket >, and ripple::MultiSocketType< socket_type & >.
Definition at line 202 of file abstract_socket.cpp.
 {
     return pure_virtual_error (ec);
 }
template<class Object > Object& beast::asio::abstract_socket::this_layer () inline
Retrieve the underlying object.
Note
If the type doesn't match, nullptr is returned or an exception is thrown if trying to acquire a reference.
Definition at line 115 of file abstract_socket.h.
     {
         Object* object (this->this_layer_ptr <Object> ());
         if (object == nullptr)
             throw std::bad_cast ();
         return *object;
     }
template<class Object > Object const& beast::asio::abstract_socket::this_layer () const inline
Definition at line 124 of file abstract_socket.h.
     {
         Object const* object (this->this_layer_ptr <Object> ());
         if (object == nullptr)
             throw std::bad_cast ();
         return *object;
     }
template<class Object > Object* beast::asio::abstract_socket::this_layer_ptr () inline
Definition at line 133 of file abstract_socket.h.
References name.
Referenced by this_layer_ptr().
     {
         return static_cast <Object*> (
             this->this_layer_ptr (typeid (Object).name ()));
     }
template<class Object > Object const* beast::asio::abstract_socket::this_layer_ptr () const inline
Definition at line 140 of file abstract_socket.h.
References name, and this_layer_ptr().
     {
         return static_cast <Object const*> (
             this->this_layer_ptr (typeid (Object).name ()));
     }
void * beast::asio::abstract_socket::this_layer_ptr (char const * type_name) const virtual
Reimplemented in ripple::MultiSocketType< StreamSocket >, ripple::MultiSocketType< socket_type & >, beast::asio::socket_wrapper< Object >, beast::asio::socket_wrapper< socket_type & >, and beast::asio::socket_wrapper< acceptor_type & >.
Definition at line 34 of file abstract_socket.cpp.
References pure_virtual_called().
 {
     pure_virtual_called ();
     return nullptr;
 }
static void beast::asio::abstract_socket::throw_if (error_code const & ec) inline static protected
Definition at line 91 of file abstract_socket.h.
Referenced by cancel(), close(), handshake(), and shutdown().
     {
         if (ec)
             throw boost::system::system_error (ec);
     }
std::size_t beast::asio::abstract_socket::write_some (const_buffers buffers, error_code & ec) virtual
Reimplemented in beast::asio::socket_wrapper< Object >, beast::asio::socket_wrapper< socket_type & >, beast::asio::socket_wrapper< acceptor_type & >, ripple::MultiSocketType< StreamSocket >, and ripple::MultiSocketType< socket_type & >.
Definition at line 128 of file abstract_socket.cpp.
References pure_virtual_error().
Referenced by ripple::MultiSocketType< socket_type & >::write_some().
 {
     ec = pure_virtual_error ();
     return 0;
 }
The documentation for this class was generated from the following files:
rippled/src/beast/beast/asio/abstract_socket.h
rippled/src/beast/beast/asio/abstract_socket.cpp