rippled: ripple::KnownFormats< KeyType > Class Template Reference
ripple::KnownFormats< KeyType > Class Template Reference abstract
#include <KnownFormats.h>
Classes
class Item
Public Member Functions
KnownFormats ()
~KnownFormats ()
KeyType findTypeByName (std::string const name) const
Item const * findByType (KeyType type) const noexcept
Protected Member Functions
Item const * findByName (std::string const &name) const noexcept
Item & add (char const *name, KeyType type)
virtual void addCommonFields (Item &item)=0
Private Types
typedef std::map< std::string,
Item * > NameMap
typedef std::map< KeyType, Item * > TypeMap
Private Attributes
std::vector< std::unique_ptr
< Item > > m_formats
NameMap m_names
TypeMap m_types
Detailed Description
template<class KeyType>
class ripple::KnownFormats< KeyType >
Manages a list of known formats.
Each format has a name, an associated KeyType (typically an enumeration), and a predefined SOElement.
Template Parameters
KeyType The type of key identifying the format.
Definition at line 35 of file KnownFormats.h.
Member Typedef Documentation
template<class KeyType> typedef std::map<std::string, Item*> ripple::KnownFormats< KeyType >::NameMap private
Definition at line 80 of file KnownFormats.h.
template<class KeyType> typedef std::map<KeyType, Item*> ripple::KnownFormats< KeyType >::TypeMap private
Definition at line 81 of file KnownFormats.h.
Constructor & Destructor Documentation
template<class KeyType> ripple::KnownFormats< KeyType >::KnownFormats () inline
Create the known formats object.
Derived classes will load the object will all the known formats.
Definition at line 88 of file KnownFormats.h.
     {
     }
template<class KeyType> ripple::KnownFormats< KeyType >::~KnownFormats () inline
Destroy the known formats object.
The defined formats are deleted.
Definition at line 96 of file KnownFormats.h.
     {
     }
Member Function Documentation
template<class KeyType> Item& ripple::KnownFormats< KeyType >::add (char const * name, KeyType type) inline protected
Add a new format.
The new format has the set of common fields already added.
Parameters
name The name of this format.
type The type of this format.
Returns
The created format.
Definition at line 164 of file KnownFormats.h.
     {
         m_formats.emplace_back (
             std::make_unique <Item> (name, type));
         auto& item (*m_formats.back());
         addCommonFields (item);
         m_types [item.getType ()] = &item;
         m_names [item.getName ()] = &item;
         return item;
     }
template<class KeyType> virtual void ripple::KnownFormats< KeyType >::addCommonFields (Item & item) protected pure virtual
Adds common fields.
This is called for every new item.
Implemented in ripple::LedgerFormats, and ripple::TxFormats.
Referenced by ripple::KnownFormats< TxType >::add().
template<class KeyType> Item const* ripple::KnownFormats< KeyType >::findByName (std::string const & name) const inline protected noexcept
Retrieve a format based on its name.
Definition at line 141 of file KnownFormats.h.
Referenced by ripple::KnownFormats< TxType >::findTypeByName().
     {
         Item* result = nullptr;
         typename NameMap::const_iterator const iter = m_names.find (name);
         if (iter != m_names.end ())
         {
             result = iter->second;
         }
         return result;
     }
template<class KeyType> Item const* ripple::KnownFormats< KeyType >::findByType (KeyType type) const inline noexcept
Retrieve a format based on its type.
Definition at line 124 of file KnownFormats.h.
Referenced by ripple::STUInt16::getJson(), ripple::STUInt16::getText(), ripple::SerializedLedgerEntry::SerializedLedgerEntry(), and ripple::SerializedTransaction::SerializedTransaction().
     {
         Item* result = nullptr;
         typename TypeMap::const_iterator const iter = m_types.find (type);
         if (iter != m_types.end ())
         {
             result = iter->second;
         }
         return result;
     }
template<class KeyType> KeyType ripple::KnownFormats< KeyType >::findTypeByName (std::string const name) const inline
Retrieve the type for a format specified by name.
If the format name is unknown, an exception is thrown.
Parameters
name The name of the type.
Returns
The type.
Definition at line 107 of file KnownFormats.h.
     {
         Item const* const result = findByName (name);
         if (result != nullptr)
         {
             return result->getType ();
         }
         else
         {
             throw std::runtime_error ("Unknown format name");
         }
     }
Member Data Documentation
template<class KeyType> std::vector<std::unique_ptr <Item> > ripple::KnownFormats< KeyType >::m_formats private
Definition at line 185 of file KnownFormats.h.
Referenced by ripple::KnownFormats< TxType >::add().
template<class KeyType> NameMap ripple::KnownFormats< KeyType >::m_names private
Definition at line 186 of file KnownFormats.h.
Referenced by ripple::KnownFormats< TxType >::add(), and ripple::KnownFormats< TxType >::findByName().
template<class KeyType> TypeMap ripple::KnownFormats< KeyType >::m_types private
Definition at line 187 of file KnownFormats.h.
Referenced by ripple::KnownFormats< TxType >::add(), and ripple::KnownFormats< TxType >::findByType().
The documentation for this class was generated from the following file:
rippled/src/ripple_data/protocol/KnownFormats.h