rippled: rippled/src/ripple/json/impl/json_internalmap.inl File Reference
json_internalmap.inl File Reference
Classes
class DefaultValueMapAllocator
struct DummyMapAllocatorInitializer
Functions
static ValueMapAllocator *& mapAllocator ()
Variables
static struct
DummyMapAllocatorInitializer dummyMapAllocatorInitializer
Function Documentation
static ValueMapAllocator*& mapAllocator () static
Definition at line 155 of file json_internalmap.inl.
Referenced by DummyMapAllocatorInitializer::DummyMapAllocatorInitializer(), Json::Value::Value(), and Json::Value::~Value().
 {
     static DefaultValueMapAllocator defaultAllocator;
     static ValueMapAllocator* mapAllocator = &defaultAllocator;
     return mapAllocator;
 }
Variable Documentation
struct DummyMapAllocatorInitializer dummyMapAllocatorInitializer static