rippled: beast::RelativeTime Class Reference
beast::RelativeTime Class Reference
#include <RelativeTime.h>
Public Types
typedef double value_type
Public Member Functions
RelativeTime (value_type seconds=0.0) noexcept
RelativeTime (const RelativeTime &other) noexcept
RelativeTime & operator= (const RelativeTime &other) noexcept
~RelativeTime () noexcept
bool isZero () const
bool isNotZero () const
std::int64_t inMilliseconds () const noexcept
value_type inSeconds () const noexcept
value_type inMinutes () const noexcept
value_type inHours () const noexcept
value_type inDays () const noexcept
value_type inWeeks () const noexcept
String getDescription (const String &returnValueForZeroTime="0") const
std::string to_string () const
template<typename Number >
RelativeTime operator+ (Number seconds) const noexcept
template<typename Number >
RelativeTime operator- (Number seconds) const noexcept
RelativeTime operator+= (RelativeTime timeToAdd) noexcept
RelativeTime operator-= (RelativeTime timeToSubtract) noexcept
RelativeTime operator+= (value_type secondsToAdd) noexcept
RelativeTime operator-= (value_type secondsToSubtract) noexcept
Static Public Member Functions
static RelativeTime fromStartup ()
static RelativeTime milliseconds (int milliseconds) noexcept
static RelativeTime milliseconds (std::int64_t milliseconds) noexcept
static RelativeTime seconds (value_type seconds) noexcept
static RelativeTime minutes (value_type numberOfMinutes) noexcept
static RelativeTime hours (value_type numberOfHours) noexcept
static RelativeTime days (value_type numberOfDays) noexcept
static RelativeTime weeks (value_type numberOfWeeks) noexcept
Private Attributes
value_type numSeconds
Detailed Description
A relative measure of time.
The time is stored as a number of seconds, at double-precision floating point accuracy, and may be positive or negative.
If you need an absolute time, (i.e. a date + time), see the Time class.
Definition at line 44 of file RelativeTime.h.
Member Typedef Documentation
typedef double beast::RelativeTime::value_type
The underlying data type used by RelativeTime.
If you need to get to the underlying time and manipulate it you can use this to declare a type that is guaranteed to work cleanly.
Definition at line 54 of file RelativeTime.h.
Constructor & Destructor Documentation
beast::RelativeTime::RelativeTime (const RelativeTime::value_type secs = 0.0) explicit noexcept
Creates a RelativeTime.
Parameters
seconds the number of seconds, which may be +ve or -ve.
See Also
milliseconds, minutes, hours, days, weeks
Definition at line 38 of file RelativeTime.cpp.
Referenced by fromStartup(), operator+(), and operator-().
     : numSeconds (secs)
 {
 }
beast::RelativeTime::RelativeTime (const RelativeTime & other) noexcept
Copies another relative time.
Definition at line 43 of file RelativeTime.cpp.
     : numSeconds (other.numSeconds)
 {
 }
beast::RelativeTime::~RelativeTime () noexcept
Destructor.
Definition at line 48 of file RelativeTime.cpp.
 {}
Member Function Documentation
RelativeTime beast::RelativeTime::days (const RelativeTime::value_type numberOfDays) static noexcept
Creates a new RelativeTime object representing a number of days.
See Also
milliseconds, minutes, hours, weeks
Definition at line 77 of file RelativeTime.cpp.
 {
     return RelativeTime (numberOfDays  * (60.0 * 60.0 * 24.0));
 }
RelativeTime beast::RelativeTime::fromStartup () static
Returns the amount of time since the process was started.
Definition at line 374 of file RelativeTime.cpp.
References beast::detail::getStartupTime(), beast::detail::monotonicCurrentTimeInSeconds(), and RelativeTime().
Referenced by beast::DeadlineTimer::Manager::run(), beast::DeadlineTimer::setExpiration(), beast::DeadlineTimer::setRecurringExpiration(), ripple::LoadEvent::start(), and ripple::LoadEvent::stop().
 {
     return RelativeTime (
         detail::monotonicCurrentTimeInSeconds() - detail::getStartupTime());
 }
String beast::RelativeTime::getDescription (const String & returnValueForZeroTime = "0") const
Returns a readable textual description of the time.
The exact format of the string returned will depend on the magnitude of the time - e.g.
"1 min 4 secs", "1 hr 45 mins", "2 weeks 5 days", "140 ms"
so that only the two most significant units are printed.
The returnValueForZeroTime value is the result that is returned if the length is zero. Depending on your application you might want to use this to return something more relevant like "empty" or "0 secs", etc.
See Also
inMilliseconds, inSeconds, inMinutes, inHours, inDays, inWeeks
Definition at line 187 of file RelativeTime.cpp.
References inDays(), inHours(), inMilliseconds(), inMinutes(), inSeconds(), inWeeks(), NEEDS_TRANS, numSeconds, beast::String::preallocateBytes(), TRANS, beast::translateTimeField(), and beast::String::trimEnd().
Referenced by to_string().
 {
     if (numSeconds < 0.001 && numSeconds > -0.001)
         return returnValueForZeroTime;
     String result;
     result.preallocateBytes (32);
     if (numSeconds < 0)
         result << '-';
     int fieldsShown = 0;
     int n = std::abs ((int) inWeeks());
     if (n > 0)
     {
         translateTimeField (result, n, NEEDS_TRANS("1 week"), NEEDS_TRANS("2 weeks"));
         ++fieldsShown;
     }
     n = std::abs ((int) inDays()) % 7;
     if (n > 0)
     {
         translateTimeField (result, n, NEEDS_TRANS("1 day"), NEEDS_TRANS("2 days"));
         ++fieldsShown;
     }
     if (fieldsShown < 2)
     {
         n = std::abs ((int) inHours()) % 24;
         if (n > 0)
         {
             translateTimeField (result, n, NEEDS_TRANS("1 hour"), NEEDS_TRANS("2 hours"));
             ++fieldsShown;
         }
         if (fieldsShown < 2)
         {
             n = std::abs ((int) inMinutes()) % 60;
             if (n > 0)
             {
                 translateTimeField (result, n, NEEDS_TRANS("1 minute"), NEEDS_TRANS("2 minutes"));
                 ++fieldsShown;
             }
             if (fieldsShown < 2)
             {
                 n = std::abs ((int) inSeconds()) % 60;
                 if (n > 0)
                 {
                     translateTimeField (result, n, NEEDS_TRANS("1 seconds"), NEEDS_TRANS("2 seconds"));
                     ++fieldsShown;
                 }
                 if (fieldsShown == 0)
                 {
                     n = std::abs ((int) inMilliseconds()) % 1000;
                     if (n > 0)
                         result << n << ' ' << TRANS ("ms");
                 }
             }
         }
     }
     return result.trimEnd();
 }
RelativeTime beast::RelativeTime::hours (const RelativeTime::value_type numberOfHours) static noexcept
Creates a new RelativeTime object representing a number of hours.
See Also
milliseconds, minutes, days, weeks
Definition at line 72 of file RelativeTime.cpp.
Referenced by ripple::Validators::SourceStringsImp::fetch().
 {
     return RelativeTime (numberOfHours * (60.0 * 60.0));
 }
RelativeTime::value_type beast::RelativeTime::inDays () const noexcept
Returns the number of days this time represents.
See Also
inMilliseconds, inSeconds, inMinutes, inHours, inWeeks
Definition at line 104 of file RelativeTime.cpp.
References numSeconds.
Referenced by getDescription().
 {
     return numSeconds / (60.0 * 60.0 * 24.0);
 }
RelativeTime::value_type beast::RelativeTime::inHours () const noexcept
Returns the number of hours this time represents.
See Also
inMilliseconds, inSeconds, inMinutes, inDays, inWeeks
Definition at line 99 of file RelativeTime.cpp.
References numSeconds.
Referenced by getDescription().
 {
     return numSeconds / (60.0 * 60.0);
 }
std::int64_t beast::RelativeTime::inMilliseconds () const noexcept
Returns the number of milliseconds this time represents.
See Also
milliseconds, inSeconds, inMinutes, inHours, inDays, inWeeks
Definition at line 89 of file RelativeTime.cpp.
References numSeconds.
Referenced by getDescription(), beast::Time::operator+=(), and beast::Time::operator-=().
 {
     return (std::int64_t) (numSeconds * 1000.0);
 }
RelativeTime::value_type beast::RelativeTime::inMinutes () const noexcept
Returns the number of minutes this time represents.
See Also
inMilliseconds, inSeconds, inHours, inDays, inWeeks
Definition at line 94 of file RelativeTime.cpp.
References numSeconds.
Referenced by getDescription().
 {
     return numSeconds / 60.0;
 }
value_type beast::RelativeTime::inSeconds () const inline noexcept
Returns the number of seconds this time represents.
See Also
inMilliseconds, inMinutes, inHours, inDays, inWeeks
Definition at line 127 of file RelativeTime.h.
References numSeconds.
Referenced by getDescription().
 { return numSeconds; }
RelativeTime::value_type beast::RelativeTime::inWeeks () const noexcept
Returns the number of weeks this time represents.
See Also
inMilliseconds, inSeconds, inMinutes, inHours, inDays
Definition at line 109 of file RelativeTime.cpp.
References numSeconds.
Referenced by getDescription().
 {
     return numSeconds / (60.0 * 60.0 * 24.0 * 7.0);
 }
bool beast::RelativeTime::isNotZero () const inline
Definition at line 76 of file RelativeTime.h.
References numSeconds.
         { return numSeconds != 0; }
bool beast::RelativeTime::isZero () const inline
Definition at line 73 of file RelativeTime.h.
References numSeconds.
         { return numSeconds == 0; }
RelativeTime beast::RelativeTime::milliseconds (int milliseconds) static noexcept
Creates a new RelativeTime object representing a number of milliseconds.
See Also
seconds, minutes, hours, days, weeks
Definition at line 52 of file RelativeTime.cpp.
Referenced by beast::operator-().
 {
     return RelativeTime (milliseconds * 0.001);
 }
RelativeTime beast::RelativeTime::milliseconds (std::int64_t milliseconds) static noexcept
Creates a new RelativeTime object representing a number of milliseconds.
See Also
seconds, minutes, hours, days, weeks
Definition at line 57 of file RelativeTime.cpp.
 {
     return RelativeTime (milliseconds * 0.001);
 }
RelativeTime beast::RelativeTime::minutes (const RelativeTime::value_type numberOfMinutes) static noexcept
Creates a new RelativeTime object representing a number of minutes.
See Also
milliseconds, hours, days, weeks
Definition at line 67 of file RelativeTime.cpp.
 {
     return RelativeTime (numberOfMinutes * 60.0);
 }
template<typename Number > RelativeTime beast::RelativeTime::operator+ (Number seconds) const inline noexcept
Definition at line 168 of file RelativeTime.h.
References numSeconds, RelativeTime(), and seconds().
         { return RelativeTime (numSeconds + seconds); }
RelativeTime beast::RelativeTime::operator+= (RelativeTime timeToAdd) noexcept
Adds another RelativeTime to this one.
Definition at line 118 of file RelativeTime.cpp.
References numSeconds.
 {
     numSeconds += t.numSeconds; return *this;
 }
RelativeTime beast::RelativeTime::operator+= (const RelativeTime::value_type secs) noexcept
Adds a number of seconds to this time.
Definition at line 128 of file RelativeTime.cpp.
 {
     numSeconds += secs; return *this;
 }
template<typename Number > RelativeTime beast::RelativeTime::operator- (Number seconds) const inline noexcept
Definition at line 172 of file RelativeTime.h.
References numSeconds, RelativeTime(), and seconds().
         { return RelativeTime (numSeconds - seconds); }
RelativeTime beast::RelativeTime::operator-= (RelativeTime timeToSubtract) noexcept
Subtracts another RelativeTime from this one.
Definition at line 123 of file RelativeTime.cpp.
References numSeconds.
 {
     numSeconds -= t.numSeconds; return *this;
 }
RelativeTime beast::RelativeTime::operator-= (const RelativeTime::value_type secs) noexcept
Subtracts a number of seconds from this time.
Definition at line 133 of file RelativeTime.cpp.
 {
     numSeconds -= secs; return *this;
 }
RelativeTime & beast::RelativeTime::operator= (const RelativeTime & other) noexcept
Copies another relative time.
Definition at line 116 of file RelativeTime.cpp.
References numSeconds.
 { numSeconds = other.numSeconds; return *this; }
RelativeTime beast::RelativeTime::seconds (RelativeTime::value_type s) static noexcept
Creates a new RelativeTime object representing a number of seconds.
See Also
milliseconds, minutes, hours, days, weeks
Definition at line 62 of file RelativeTime.cpp.
Referenced by ripple::Validators::ManagerImp::checkSources(), operator+(), and operator-().
 {
     return RelativeTime (s);
 }
std::string beast::RelativeTime::to_string () const
Definition at line 253 of file RelativeTime.cpp.
References getDescription(), and beast::String::toStdString().
Referenced by beast::operator<<().
 {
     return getDescription ().toStdString();
 }
RelativeTime beast::RelativeTime::weeks (const RelativeTime::value_type numberOfWeeks) static noexcept
Creates a new RelativeTime object representing a number of weeks.
See Also
milliseconds, minutes, hours, days
Definition at line 82 of file RelativeTime.cpp.
 {
     return RelativeTime (numberOfWeeks * (60.0 * 60.0 * 24.0 * 7.0));
 }
Member Data Documentation
value_type beast::RelativeTime::numSeconds private
Definition at line 188 of file RelativeTime.h.
Referenced by getDescription(), inDays(), inHours(), inMilliseconds(), inMinutes(), inSeconds(), inWeeks(), isNotZero(), isZero(), operator+(), operator+=(), operator-(), operator-=(), and operator=().
The documentation for this class was generated from the following files:
rippled/src/beast/beast/chrono/RelativeTime.h
rippled/src/beast/beast/chrono/impl/RelativeTime.cpp