rippled: ripple::Validations Class Reference
ripple::Validations Class Reference abstract
#include <Validations.h>
Public Member Functions
virtual ~Validations ()
virtual bool addValidation (SerializedValidation::ref, const std::string &source)=0
virtual ValidationSet getValidations (uint256 const &ledger)=0
virtual void getValidationCount (uint256 const &ledger, bool currentOnly, int &trusted, int &untrusted)=0
virtual void getValidationTypes (uint256 const &ledger, int &full, int &partial)=0
virtual int getTrustedValidationCount (uint256 const &ledger)=0
virtual int getFeeAverage (uint256 const &ledger, std::uint64_t ref, std::uint64_t &fee)=0
virtual int getNodesAfter (uint256 const &ledger)=0
virtual int getLoadRatio (bool overLoaded)=0
virtual ripple::unordered_map
< uint256,
currentValidationCount > getCurrentValidations (uint256 currentLedger, uint256 previousLedger)=0
virtual std::list
< SerializedValidation::pointer > getCurrentTrustedValidations ()=0
virtual void tune (int size, int age)=0
virtual void flush ()=0
virtual void sweep ()=0
Static Public Member Functions
static Validations * New ()
Detailed Description
Definition at line 29 of file Validations.h.
Constructor & Destructor Documentation
virtual ripple::Validations::~Validations () inline virtual
Definition at line 34 of file Validations.h.
 { }
Member Function Documentation
virtual bool ripple::Validations::addValidation (SerializedValidation::ref , const std::string & source) pure virtual
Implemented in ripple::ValidationsImp.
Referenced by ripple::LedgerConsensusImp::accept(), ripple::LedgerConsensusImp::checkOurValidation(), and ripple::NetworkOPsImp::recvValidation().
virtual void ripple::Validations::flush () pure virtual
Implemented in ripple::ValidationsImp.
virtual std::list<SerializedValidation::pointer> ripple::Validations::getCurrentTrustedValidations () pure virtual
Implemented in ripple::ValidationsImp.
Referenced by ripple::LedgerMasterImp::consensusBuilt().
virtual ripple::unordered_map<uint256, currentValidationCount> ripple::Validations::getCurrentValidations (uint256 currentLedger, uint256 previousLedger) pure virtual
Implemented in ripple::ValidationsImp.
Referenced by ripple::NetworkOPsImp::checkLastClosedLedger(), and ripple::LedgerConsensusImp::checkLCL().
virtual int ripple::Validations::getFeeAverage (uint256 const & ledger, std::uint64_t ref, std::uint64_t & fee) pure virtual
Implemented in ripple::ValidationsImp.
Referenced by ripple::LedgerMasterImp::checkAccept().
virtual int ripple::Validations::getLoadRatio (bool overLoaded) pure virtual
Implemented in ripple::ValidationsImp.
virtual int ripple::Validations::getNodesAfter (uint256 const & ledger) pure virtual
Implemented in ripple::ValidationsImp.
Referenced by ripple::LedgerConsensusImp::haveConsensus().
virtual int ripple::Validations::getTrustedValidationCount (uint256 const & ledger) pure virtual
Implemented in ripple::ValidationsImp.
Referenced by ripple::LedgerMasterImp::checkAccept(), ripple::LedgerMasterImp::getNeededValidations(), and ripple::LedgerConsensusImp::statePreClose().
virtual void ripple::Validations::getValidationCount (uint256 const & ledger, bool currentOnly, int & trusted, int & untrusted) pure virtual
Implemented in ripple::ValidationsImp.
virtual ValidationSet ripple::Validations::getValidations (uint256 const & ledger) pure virtual
Implemented in ripple::ValidationsImp.
Referenced by ripple::FeaturesImpl::doVoting(), and ripple::FeeVoteImpl::doVoting().
virtual void ripple::Validations::getValidationTypes (uint256 const & ledger, int & full, int & partial) pure virtual
Implemented in ripple::ValidationsImp.
Validations * ripple::Validations::New () static
Definition at line 471 of file Validations.cpp.
 {
     return new ValidationsImp;
 }
virtual void ripple::Validations::sweep () pure virtual
Implemented in ripple::ValidationsImp.
Referenced by ripple::ApplicationImp::doSweep().
virtual void ripple::Validations::tune (int size, int age) pure virtual
Implemented in ripple::ValidationsImp.
The documentation for this class was generated from the following files:
rippled/src/ripple_app/misc/Validations.h
rippled/src/ripple_app/misc/Validations.cpp