rippled: beast::empty_base_optimization_test::test1< T > Class Template Reference
beast::empty_base_optimization_test::test1< T > Class Template Reference
Public Member Functions
test1 (T const &t)
T & member ()
T const & member () const
Private Types
typedef
empty_base_optimization< T > Base
Private Attributes
void * m_p
Additional Inherited Members
Private Member Functions inherited from beast::empty_base_optimization< T >
empty_base_optimization ()=default
empty_base_optimization (T const &t)
empty_base_optimization (T &&t)
T & member () noexcept
T const & member () const noexcept
Detailed Description
template<class T>
class beast::empty_base_optimization_test::test1< T >
Definition at line 35 of file empty_base_optimization.test.cpp.
Member Typedef Documentation
template<class T> typedef empty_base_optimization<T> beast::empty_base_optimization_test::test1< T >::Base private
Definition at line 38 of file empty_base_optimization.test.cpp.
Constructor & Destructor Documentation
template<class T> beast::empty_base_optimization_test::test1< T >::test1 (T const & t) inline explicit
Definition at line 41 of file empty_base_optimization.test.cpp.
             : Base (t)
         {}
Member Function Documentation
template<class T> T& beast::empty_base_optimization_test::test1< T >::member () inline
Definition at line 45 of file empty_base_optimization.test.cpp.
References beast::empty_base_optimization< T >::member().
Referenced by beast::empty_base_optimization_test::test_one(), and beast::empty_base_optimization_test::test_two().
 {return Base::member();}
template<class T> T const& beast::empty_base_optimization_test::test1< T >::member () const inline
Definition at line 46 of file empty_base_optimization.test.cpp.
References beast::empty_base_optimization< T >::member().
 {return Base::member();}
Member Data Documentation
template<class T> void* beast::empty_base_optimization_test::test1< T >::m_p private
Definition at line 39 of file empty_base_optimization.test.cpp.
The documentation for this class was generated from the following file:
rippled/src/beast/beast/utility/tests/empty_base_optimization.test.cpp