rippled: ripple::LoadMonitor Class Reference
ripple::LoadMonitor Class Reference
#include <LoadMonitor.h>
Classes
struct Stats
Public Member Functions
LoadMonitor ()
void addCount ()
void addLatency (int latency)
void addLoadSample (LoadEvent const &sample)
void setTargetLatency (std::uint64_t avg, std::uint64_t pk)
bool isOverTarget (std::uint64_t avg, std::uint64_t peak)
Stats getStats ()
bool isOver ()
Private Types
typedef RippleMutex LockType
typedef std::lock_guard< LockType > ScopedLockType
Private Member Functions
void update ()
Static Private Member Functions
static std::string printElapsed (double seconds)
Private Attributes
LockType mLock
std::uint64_t mCounts
int mLatencyEvents
std::uint64_t mLatencyMSAvg
std::uint64_t mLatencyMSPeak
std::uint64_t mTargetLatencyAvg
std::uint64_t mTargetLatencyPk
int mLastUpdate
Detailed Description
Definition at line 29 of file LoadMonitor.h.
Member Typedef Documentation
typedef RippleMutex ripple::LoadMonitor::LockType private
Definition at line 64 of file LoadMonitor.h.
typedef std::lock_guard<LockType> ripple::LoadMonitor::ScopedLockType private
Definition at line 65 of file LoadMonitor.h.
Constructor & Destructor Documentation
ripple::LoadMonitor::LoadMonitor ()
Definition at line 45 of file LoadMonitor.cpp.
Referenced by addLoadSample().
     : mCounts (0)
     , mLatencyEvents (0)
     , mLatencyMSAvg (0)
     , mLatencyMSPeak (0)
     , mTargetLatencyAvg (0)
     , mTargetLatencyPk (0)
     , mLastUpdate (UptimeTimer::getInstance ().getElapsedSeconds ())
 {
 }
Member Function Documentation
void ripple::LoadMonitor::addCount ()
Definition at line 103 of file LoadMonitor.cpp.
References mCounts, mLock, and update().
 {
     ScopedLockType sl (mLock);
     update ();
     ++mCounts;
 }
void ripple::LoadMonitor::addLatency (int latency)
Definition at line 111 of file LoadMonitor.cpp.
References mLatencyEvents, mLatencyMSAvg, mLatencyMSPeak, mLock, and update().
 {
     // VFALCO NOTE Why does 1 become 0?
     if (latency == 1)
         latency = 0;
     ScopedLockType sl (mLock);
     update ();
     ++mLatencyEvents;
     mLatencyMSAvg += latency;
     mLatencyMSPeak += latency;
     // VFALCO NOTE Why are we multiplying by 4?
     int const latencyPeak = mLatencyEvents * latency * 4;
     if (mLatencyMSPeak < latencyPeak)
         mLatencyMSPeak = latencyPeak;
 }
void ripple::LoadMonitor::addLoadSample (LoadEvent const & sample)
Definition at line 139 of file LoadMonitor.cpp.
References ripple::LoadEvent::getSecondsRunning(), ripple::LoadEvent::getSecondsTotal(), ripple::LoadEvent::getSecondsWaiting(), LoadMonitor(), ripple::lsINFO, ripple::lsWARNING, mCounts, mLatencyEvents, mLatencyMSAvg, mLatencyMSPeak, mLock, ripple::LoadEvent::name(), name, printElapsed(), update(), and WriteLog.
Referenced by ripple::LoadEvent::stop().
 {
     std::string const& name (sample.name());
     beast::RelativeTime const latency (sample.getSecondsTotal());
     if (latency.inSeconds() > 0.5)
     {
         WriteLog ((latency.inSeconds() > 1.0) ? lsWARNING : lsINFO, LoadMonitor)
             << "Job: " << name << " ExecutionTime: " << printElapsed (sample.getSecondsRunning()) <<
             " WaitingTime: " << printElapsed (sample.getSecondsWaiting());
     }
     // VFALCO NOTE Why does 1 become 0?
     std::size_t latencyMilliseconds (latency.inMilliseconds());
     if (latencyMilliseconds == 1)
         latencyMilliseconds = 0;
     ScopedLockType sl (mLock);
     update ();
     ++mCounts;
     ++mLatencyEvents;
     mLatencyMSAvg += latencyMilliseconds;
     mLatencyMSPeak += latencyMilliseconds;
     // VFALCO NOTE Why are we multiplying by 4?
     int const latencyPeak = mLatencyEvents * latencyMilliseconds * 4;
     if (mLatencyMSPeak < latencyPeak)
         mLatencyMSPeak = latencyPeak;
 }
LoadMonitor::Stats ripple::LoadMonitor::getStats ()
Definition at line 195 of file LoadMonitor.cpp.
References ripple::LoadMonitor::Stats::count, ripple::LoadMonitor::Stats::isOverloaded, isOverTarget(), ripple::LoadMonitor::Stats::latencyAvg, ripple::LoadMonitor::Stats::latencyPeak, mCounts, mLatencyEvents, mLatencyMSAvg, mLatencyMSPeak, mLock, stats, and update().
Referenced by ripple::JobTypeData::stats().
 {
     Stats stats;
     ScopedLockType sl (mLock);
     update ();
     stats.count = mCounts / 4;
     if (mLatencyEvents == 0)
     {
         stats.latencyAvg = 0;
         stats.latencyPeak = 0;
     }
     else
     {
         stats.latencyAvg = mLatencyMSAvg / (mLatencyEvents * 4);
         stats.latencyPeak = mLatencyMSPeak / (mLatencyEvents * 4);
     }
     stats.isOverloaded = isOverTarget (stats.latencyAvg, stats.latencyPeak);
     return stats;
 }
bool ripple::LoadMonitor::isOver ()
Definition at line 183 of file LoadMonitor.cpp.
References isOverTarget(), mLatencyEvents, mLatencyMSAvg, mLatencyMSPeak, mLock, and update().
 {
     ScopedLockType sl (mLock);
     update ();
     if (mLatencyEvents == 0)
         return 0;
     return isOverTarget (mLatencyMSAvg / (mLatencyEvents * 4), mLatencyMSPeak / (mLatencyEvents * 4));
 }
bool ripple::LoadMonitor::isOverTarget (std::uint64_t avg, std::uint64_t peak)
Definition at line 177 of file LoadMonitor.cpp.
References mTargetLatencyAvg, and mTargetLatencyPk.
Referenced by getStats(), and isOver().
 {
     return (mTargetLatencyPk && (peak > mTargetLatencyPk)) ||
            (mTargetLatencyAvg && (avg > mTargetLatencyAvg));
 }
std::string ripple::LoadMonitor::printElapsed (double seconds) static private
Definition at line 132 of file LoadMonitor.cpp.
Referenced by addLoadSample().
 {
     std::stringstream ss;
     ss << (std::size_t (seconds * 1000 + 0.5)) << " ms";
     return ss.str();
 }
void ripple::LoadMonitor::setTargetLatency (std::uint64_t avg, std::uint64_t pk)
Definition at line 171 of file LoadMonitor.cpp.
References mTargetLatencyAvg, and mTargetLatencyPk.
Referenced by ripple::JobTypeData::JobTypeData().
 {
     mTargetLatencyAvg  = avg;
     mTargetLatencyPk = pk;
 }
void ripple::LoadMonitor::update () private
Definition at line 62 of file LoadMonitor.cpp.
References ripple::UptimeTimer::getElapsedSeconds(), ripple::UptimeTimer::getInstance(), mCounts, mLastUpdate, mLatencyEvents, mLatencyMSAvg, and mLatencyMSPeak.
Referenced by addCount(), addLatency(), addLoadSample(), getStats(), and isOver().
 {
     int now = UptimeTimer::getInstance ().getElapsedSeconds ();
     // VFALCO TODO stop returning from the middle of functions.
     if (now == mLastUpdate) // current
         return;
     // VFALCO TODO Why 8?
     if ((now < mLastUpdate) || (now > (mLastUpdate + 8)))
     {
         // way out of date
         mCounts = 0;
         mLatencyEvents = 0;
         mLatencyMSAvg = 0;
         mLatencyMSPeak = 0;
         mLastUpdate = now;
         // VFALCO TODO don't return from the middle...
         return;
     }
     // do exponential decay
     /*
         David:
         "Imagine if you add 10 to something every second. And you
          also reduce it by 1/4 every second. It will "idle" at 40,
          correponding to 10 counts per second."
     */
     do
     {
         ++mLastUpdate;
         mCounts -= ((mCounts + 3) / 4);
         mLatencyEvents -= ((mLatencyEvents + 3) / 4);
         mLatencyMSAvg -= (mLatencyMSAvg / 4);
         mLatencyMSPeak -= (mLatencyMSPeak / 4);
     }
     while (mLastUpdate < now);
 }
Member Data Documentation
std::uint64_t ripple::LoadMonitor::mCounts private
Definition at line 68 of file LoadMonitor.h.
Referenced by addCount(), addLoadSample(), getStats(), and update().
int ripple::LoadMonitor::mLastUpdate private
Definition at line 74 of file LoadMonitor.h.
Referenced by update().
int ripple::LoadMonitor::mLatencyEvents private
Definition at line 69 of file LoadMonitor.h.
Referenced by addLatency(), addLoadSample(), getStats(), isOver(), and update().
std::uint64_t ripple::LoadMonitor::mLatencyMSAvg private
Definition at line 70 of file LoadMonitor.h.
Referenced by addLatency(), addLoadSample(), getStats(), isOver(), and update().
std::uint64_t ripple::LoadMonitor::mLatencyMSPeak private
Definition at line 71 of file LoadMonitor.h.
Referenced by addLatency(), addLoadSample(), getStats(), isOver(), and update().
LockType ripple::LoadMonitor::mLock private
Definition at line 66 of file LoadMonitor.h.
Referenced by addCount(), addLatency(), addLoadSample(), getStats(), and isOver().
std::uint64_t ripple::LoadMonitor::mTargetLatencyAvg private
Definition at line 72 of file LoadMonitor.h.
Referenced by isOverTarget(), and setTargetLatency().
std::uint64_t ripple::LoadMonitor::mTargetLatencyPk private
Definition at line 73 of file LoadMonitor.h.
Referenced by isOverTarget(), and setTargetLatency().
The documentation for this class was generated from the following files:
rippled/src/ripple_core/functional/LoadMonitor.h
rippled/src/ripple_core/functional/LoadMonitor.cpp