rippled: beast::insight::Counter Class Reference
beast::insight::Counter Class Reference
#include <Counter.h>
Public Types
typedef CounterImpl::value_type value_type
Public Member Functions
Counter ()
Counter (std::shared_ptr< CounterImpl > const &impl)
std::shared_ptr< CounterImpl >
const & impl () const
void increment (value_type amount) const
Counter const & operator+= (value_type amount) const
Counter const & operator-= (value_type amount) const
Counter const & operator++ () const
Counter const & operator++ (int) const
Counter const & operator-- () const
Counter const & operator-- (int) const
Public Member Functions inherited from beast::insight::Base
virtual ~Base ()=0
Private Attributes
std::shared_ptr< CounterImpl > m_impl
Detailed Description
A metric for measuring an integral value.
A counter is a gauge calculated at the server. The owner of the counter may increment and decrement the value by an amount.
This is a lightweight reference wrapper which is cheap to copy and assign. When the last reference goes away, the metric is no longer collected.
Definition at line 39 of file Counter.h.
Member Typedef Documentation
typedef CounterImpl::value_type beast::insight::Counter::value_type
Definition at line 42 of file Counter.h.
Constructor & Destructor Documentation
beast::insight::Counter::Counter () inline
Create a null metric. A null metric reports no information.
Definition at line 47 of file Counter.h.
     {
     }
beast::insight::Counter::Counter (std::shared_ptr< CounterImpl > const & impl) inline explicit
Create the metric reference the specified implementation. Normally this won't be called directly. Instead, call the appropriate factory function in the Collector interface.
See Also
Collector.
Definition at line 56 of file Counter.h.
         : m_impl (impl)
     {
     }
Member Function Documentation
std::shared_ptr<CounterImpl> const& beast::insight::Counter::impl () const inline
Definition at line 114 of file Counter.h.
References m_impl.
     {
         return m_impl;
     }
void beast::insight::Counter::increment (value_type amount) const inline
Increment the counter.
Definition at line 64 of file Counter.h.
References m_impl.
Referenced by operator++(), operator+=(), operator--(), and operator-=().
     {
         if (m_impl)
             m_impl->increment (amount);
     }
Counter const& beast::insight::Counter::operator++ () const inline
Definition at line 85 of file Counter.h.
References increment().
     {
         increment (1);
         return *this;
     }
Counter const& beast::insight::Counter::operator++ (int) const inline
Definition at line 92 of file Counter.h.
References increment().
     {
         increment (1);
         return *this;
     }
Counter const& beast::insight::Counter::operator+= (value_type amount) const inline
Definition at line 71 of file Counter.h.
References increment().
     {
         increment (amount);
         return *this;
     }
Counter const& beast::insight::Counter::operator-- () const inline
Definition at line 99 of file Counter.h.
References increment().
     {
         increment (-1);
         return *this;
     }
Counter const& beast::insight::Counter::operator-- (int) const inline
Definition at line 106 of file Counter.h.
References increment().
     {
         increment (-1);
         return *this;
     }
Counter const& beast::insight::Counter::operator-= (value_type amount) const inline
Definition at line 78 of file Counter.h.
References increment().
     {
         increment (-amount);
         return *this;
     }
Member Data Documentation
std::shared_ptr<CounterImpl> beast::insight::Counter::m_impl private
Definition at line 120 of file Counter.h.
Referenced by impl(), and increment().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/insight/Counter.h