rippled: rocksdb::RedisListIterator Class Reference
rocksdb::RedisListIterator Class Reference
#include <redis_list_iterator.h>
Public Member Functions
RedisListIterator (const std::string &list_data)
void Reserve (int bytes)
RedisListIterator & Push ()
RedisListIterator & Skip ()
void InsertElement (const Slice &elem)
void GetCurrent (Slice *curElem)
Access the current element, and save the result into *curElem.
int Length () const
int Size () const
bool Done () const
Slice WriteResult ()
Static Public Member Functions
static uint32_t SizeOf (const Slice &elem)
Private Member Functions
void InitializeResult ()
void MoveNext ()
Go to the next element (used in Push() and Skip())
void WriteCurrentElement ()
void CheckErrors ()
void ThrowError (const char *const msg=NULL)
Private Attributes
const char *const data_
const uint32_t num_bytes_
uint32_t cur_byte_
uint32_t cur_elem_
uint32_t cur_elem_length_
uint32_t length_
std::vector< char > result_
Detailed Description
An abstraction over the "list" concept. All operations may throw a RedisListException
Definition at line 52 of file redis_list_iterator.h.
Constructor & Destructor Documentation
rocksdb::RedisListIterator::RedisListIterator (const std::string & list_data) inline
Construct a redis-list-iterator based on data. If the data is non-empty, it must formatted according to above.
If the data is valid, we can assume the following invariant(s): a) length_, num_bytes_ are set correctly. b) cur_byte_ always refers to the start of the current element, just before the bytes that specify element length. c) cur_elem_ is always the index of the current element. d) cur_elem_length_ is always the number of bytes in current element, excluding the 4-byte header itself. e) result_ will always contain data_[0..cur_byte_) and a header f) Whenever corrupt data is encountered or an invalid operation is attempted, a RedisListException will immediately be thrown.
Definition at line 67 of file redis_list_iterator.h.
References cur_byte_, cur_elem_length_, data_, rocksdb::DecodeFixed32(), InitializeResult(), length_, num_bytes_, and ThrowError().
       : data_(list_data.data()),
         num_bytes_(list_data.size()),
         cur_byte_(0),
         cur_elem_(0),
         cur_elem_length_(0),
         length_(0),
         result_() {
     // Initialize the result_ (reserve enough space for header)
     InitializeResult();
     // Parse the data only if it is not empty.
     if (num_bytes_ == 0) {
       return;
     }
     // If non-empty, but less than 4 bytes, data must be corrupt
     if (num_bytes_ < sizeof(length_)) {
       ThrowError("Corrupt header.");    // Will break control flow
     }
     // Good. The first bytes specify the number of elements
     length_ = DecodeFixed32(data_);
     cur_byte_ = sizeof(length_);
     // If we have at least one element, point to that element.
     // Also, read the first integer of the element (specifying the size),
     //   if possible.
     if (length_ > 0) {
       if (cur_byte_ + sizeof(cur_elem_length_) <= num_bytes_) {
         cur_elem_length_ = DecodeFixed32(data_+cur_byte_);
       } else {
         ThrowError("Corrupt data for first element.");
       }
     }
     // At this point, we are fully set-up.
     // The invariants described in the header should now be true.
   }
Member Function Documentation
void rocksdb::RedisListIterator::CheckErrors () inline private
Will ThrowError() if neccessary. Checks for common/ubiquitous errors that can arise after most operations. This method should be called before any reading operation. If this function succeeds, then we are guaranteed to be in a valid state. Other member functions should check for errors and ThrowError() also if an error occurs that is specific to it even while in a valid state.
Definition at line 277 of file redis_list_iterator.h.
References cur_byte_, cur_elem_, cur_elem_length_, length_, num_bytes_, and ThrowError().
Referenced by GetCurrent(), InsertElement(), MoveNext(), WriteCurrentElement(), and WriteResult().
                      {
     // Check if any crazy thing has happened recently
     if ((cur_elem_ > length_) ||                              // Bad index
         (cur_byte_ > num_bytes_) ||                           // No more bytes
         (cur_byte_ + cur_elem_length_ > num_bytes_) ||        // Item too large
         (cur_byte_ == num_bytes_ && cur_elem_ != length_) ||  // Too many items
         (cur_elem_ == length_ && cur_byte_ != num_bytes_)) {  // Too many bytes
       ThrowError("Corrupt data.");
     }
   }
bool rocksdb::RedisListIterator::Done () const inline
Definition at line 175 of file redis_list_iterator.h.
References cur_byte_, cur_elem_, length_, and num_bytes_.
Referenced by GetCurrent(), rocksdb::RedisLists::Index(), rocksdb::RedisLists::Insert(), MoveNext(), rocksdb::RedisLists::PopRight(), rocksdb::RedisLists::Print(), rocksdb::RedisLists::PushRight(), rocksdb::RedisLists::Range(), rocksdb::RedisLists::RemoveFirst(), rocksdb::RedisLists::RemoveLast(), rocksdb::RedisLists::Set(), rocksdb::RedisLists::Trim(), and WriteCurrentElement().
                     {
     return cur_byte_ >= num_bytes_ || cur_elem_ >= length_;
   }
void rocksdb::RedisListIterator::GetCurrent (Slice * curElem) inline
Access the current element, and save the result into *curElem.
Definition at line 148 of file redis_list_iterator.h.
References CheckErrors(), cur_byte_, cur_elem_length_, data_, Done(), and ThrowError().
Referenced by rocksdb::RedisLists::Index(), rocksdb::RedisLists::Insert(), rocksdb::RedisLists::PopLeft(), rocksdb::RedisLists::PopRight(), rocksdb::RedisLists::RemoveFirst(), and rocksdb::RedisLists::RemoveLast().
{
     // Ensure we are in a valid state
     CheckErrors();
     // Ensure that we are not past the last element.
     if (Done()) {
       ThrowError("Invalid dereferencing.");
     }
     // Dereference the element
     *curElem = Slice(data_+cur_byte_+sizeof(cur_elem_length_),
                      cur_elem_length_);
   }
void rocksdb::RedisListIterator::InitializeResult () inline private
Initializes the result_ string. It will fill the first few bytes with 0's so that there is enough space for header information when we need to write later. Currently, "header information" means: the length (number of elements) Assumes that result_ is empty to begin with
Definition at line 221 of file redis_list_iterator.h.
References result_.
Referenced by RedisListIterator().
{
     assert(result_.empty());            // Should always be true.
     result_.resize(sizeof(uint32_t),0); // Put a block of 0's as the header
   }
void rocksdb::RedisListIterator::InsertElement (const Slice & elem) inline
Insert elem into the result_ (just BEFORE the current element / byte) Note: if Done() (i.e.: iterator points to end), this will append elem.
Definition at line 133 of file redis_list_iterator.h.
References CheckErrors(), cur_elem_, rocksdb::Slice::data(), rocksdb::EncodeFixed32(), length_, result_, rocksdb::Slice::size(), and SizeOf().
Referenced by rocksdb::RedisLists::Insert(), rocksdb::RedisLists::PushLeft(), rocksdb::RedisLists::PushRight(), and rocksdb::RedisLists::Set().
{
     // Ensure we are in a valid state
     CheckErrors();
     const int kOrigSize = result_.size();
     result_.resize(kOrigSize + SizeOf(elem));
     EncodeFixed32(result_.data() + kOrigSize, elem.size());
     memcpy(result_.data() + kOrigSize + sizeof(uint32_t),
            elem.data(),
            elem.size());
     ++length_;
     ++cur_elem_;
   }
int rocksdb::RedisListIterator::Length () const inline
Definition at line 163 of file redis_list_iterator.h.
References length_.
Referenced by rocksdb::RedisLists::Insert(), rocksdb::RedisLists::Length(), rocksdb::RedisLists::PopLeft(), rocksdb::RedisLists::PopRight(), rocksdb::RedisLists::Print(), rocksdb::RedisLists::PushLeft(), and rocksdb::RedisLists::PushRight().
                      {
     return length_;
   }
void rocksdb::RedisListIterator::MoveNext () inline private
Go to the next element (used in Push() and Skip())
Definition at line 227 of file redis_list_iterator.h.
References CheckErrors(), cur_byte_, cur_elem_, cur_elem_length_, data_, rocksdb::DecodeFixed32(), Done(), num_bytes_, and ThrowError().
Referenced by Push(), and Skip().
                   {
     CheckErrors();
     // Check to make sure we are not already in a finished state
     if (Done()) {
       ThrowError("Attempting to iterate past end of list.");
     }
     // Move forward one element.
     cur_byte_ += sizeof(cur_elem_length_) + cur_elem_length_;
     ++cur_elem_;
     // If we are at the end, finish
     if (Done()) {
       cur_elem_length_ = 0;
       return;
     }
     // Otherwise, we should be able to read the new element's length
     if (cur_byte_ + sizeof(cur_elem_length_) > num_bytes_) {
       ThrowError("Corrupt element data.");
     }
     // Set the new element's length
     cur_elem_length_ = DecodeFixed32(data_+cur_byte_);
     return;
   }
RedisListIterator& rocksdb::RedisListIterator::Push () inline
Go to next element in data file. Also writes the current element to result_.
Definition at line 116 of file redis_list_iterator.h.
References MoveNext(), and WriteCurrentElement().
Referenced by rocksdb::RedisLists::Insert(), rocksdb::RedisLists::PopRight(), rocksdb::RedisLists::PushRight(), rocksdb::RedisLists::RemoveFirst(), rocksdb::RedisLists::RemoveLast(), rocksdb::RedisLists::Set(), and rocksdb::RedisLists::Trim().
{
     WriteCurrentElement();
     MoveNext();
     return *this;
   }
void rocksdb::RedisListIterator::Reserve (int bytes) inline
Reserve some space for the result_. Equivalent to result_.reserve(bytes).
Definition at line 110 of file redis_list_iterator.h.
References result_.
Referenced by rocksdb::RedisLists::Insert(), rocksdb::RedisLists::PopLeft(), rocksdb::RedisLists::PopRight(), rocksdb::RedisLists::PushLeft(), rocksdb::RedisLists::PushRight(), rocksdb::RedisLists::RemoveFirst(), rocksdb::RedisLists::RemoveLast(), rocksdb::RedisLists::Set(), and rocksdb::RedisLists::Trim().
{
     result_.reserve(bytes);
   }
int rocksdb::RedisListIterator::Size () const inline
Definition at line 168 of file redis_list_iterator.h.
References cur_byte_, num_bytes_, and result_.
Referenced by rocksdb::RedisLists::Insert(), rocksdb::RedisLists::PopLeft(), rocksdb::RedisLists::PopRight(), rocksdb::RedisLists::Print(), rocksdb::RedisLists::PushLeft(), rocksdb::RedisLists::PushRight(), rocksdb::RedisLists::RemoveFirst(), rocksdb::RedisLists::RemoveLast(), rocksdb::RedisLists::Set(), and rocksdb::RedisLists::Trim().
                    {
     // result_ holds the currently written data
     // data_[cur_byte..num_bytes-1] is the remainder of the data
     return result_.size() + (num_bytes_ - cur_byte_);
   }
static uint32_t rocksdb::RedisListIterator::SizeOf (const Slice & elem) inline static
An upper-bound on the amount of bytes needed to store this element. This is used to hide representation information from the client. E.G. This can be used to compute the bytes we want to Reserve().
Definition at line 209 of file redis_list_iterator.h.
References rocksdb::Slice::size().
Referenced by rocksdb::RedisLists::Insert(), InsertElement(), rocksdb::RedisLists::PopLeft(), rocksdb::RedisLists::PushLeft(), rocksdb::RedisLists::PushRight(), rocksdb::RedisLists::RemoveLast(), and rocksdb::RedisLists::Set().
{
     // [Integer Length . Data]
     return sizeof(uint32_t) + elem.size();
   }
RedisListIterator& rocksdb::RedisListIterator::Skip () inline
Go to next element in data file. Drops/skips the current element. It will not be written to result_.
Definition at line 124 of file redis_list_iterator.h.
References cur_elem_, length_, and MoveNext().
Referenced by rocksdb::RedisLists::Index(), rocksdb::RedisLists::PopLeft(), rocksdb::RedisLists::PopRight(), rocksdb::RedisLists::RemoveFirst(), rocksdb::RedisLists::RemoveLast(), rocksdb::RedisLists::Set(), and rocksdb::RedisLists::Trim().
{
     MoveNext();
     --length_;          // One less item
     --cur_elem_;        // We moved one forward, but index did not change
     return *this;
   }
void rocksdb::RedisListIterator::ThrowError (const char *const msg = NULL) inline private
Will throw an exception based on the passed-in message. This function is guaranteed to STOP THE CONTROL-FLOW. (i.e.: you do not have to call "return" after calling ThrowError)
Definition at line 291 of file redis_list_iterator.h.
Referenced by CheckErrors(), GetCurrent(), MoveNext(), RedisListIterator(), and WriteCurrentElement().
{
     // TODO: For now we ignore the msg parameter. This can be expanded later.
     throw RedisListException();
   }
void rocksdb::RedisListIterator::WriteCurrentElement () inline private
Append the current element (pointed to by cur_byte_) to result_ Assumes result_ has already been reserved appropriately.
Definition at line 258 of file redis_list_iterator.h.
References CheckErrors(), cur_byte_, cur_elem_length_, data_, Done(), result_, and ThrowError().
Referenced by Push().
{
     // First verify that the iterator is still valid.
     CheckErrors();
     if (Done()) {
       ThrowError("Attempting to write invalid element.");
     }
     // Append the cur element.
     result_.insert(result_.end(),
                    data_+cur_byte_,
                    data_+cur_byte_+ sizeof(uint32_t) + cur_elem_length_);
   }
Slice rocksdb::RedisListIterator::WriteResult () inline
Returns a string representing the final, edited, data. Assumes that all bytes of data_ in the range [0,cur_byte_) have been read and that result_ contains this data. The rest of the data must still be written. So, this method ADVANCES THE ITERATOR TO THE END before writing.
Definition at line 184 of file redis_list_iterator.h.
References CheckErrors(), cur_byte_, cur_elem_, cur_elem_length_, data_, rocksdb::EncodeFixed32(), length_, num_bytes_, and result_.
Referenced by rocksdb::RedisLists::Insert(), rocksdb::RedisLists::PopLeft(), rocksdb::RedisLists::PopRight(), rocksdb::RedisLists::Print(), rocksdb::RedisLists::PushLeft(), rocksdb::RedisLists::PushRight(), rocksdb::RedisLists::RemoveFirst(), rocksdb::RedisLists::RemoveLast(), rocksdb::RedisLists::Set(), and rocksdb::RedisLists::Trim().
                       {
     CheckErrors();
     // The header should currently be filled with dummy data (0's)
     // Correctly update the header.
     // Note, this is safe since result_ is a vector (guaranteed contiguous)
     EncodeFixed32(&result_[0],length_);
     // Append the remainder of the data to the result.
     result_.insert(result_.end(),data_+cur_byte_, data_ +num_bytes_);
     // Seek to end of file
     cur_byte_ = num_bytes_;
     cur_elem_ = length_;
     cur_elem_length_ = 0;
     // Return the result
     return Slice(result_.data(),result_.size());
   }
Member Data Documentation
uint32_t rocksdb::RedisListIterator::cur_byte_ private
Definition at line 300 of file redis_list_iterator.h.
Referenced by CheckErrors(), Done(), GetCurrent(), MoveNext(), RedisListIterator(), Size(), WriteCurrentElement(), and WriteResult().
uint32_t rocksdb::RedisListIterator::cur_elem_ private
Definition at line 301 of file redis_list_iterator.h.
Referenced by CheckErrors(), Done(), InsertElement(), MoveNext(), Skip(), and WriteResult().
uint32_t rocksdb::RedisListIterator::cur_elem_length_ private
Definition at line 302 of file redis_list_iterator.h.
Referenced by CheckErrors(), GetCurrent(), MoveNext(), RedisListIterator(), WriteCurrentElement(), and WriteResult().
const char* const rocksdb::RedisListIterator::data_ private
Definition at line 297 of file redis_list_iterator.h.
Referenced by GetCurrent(), MoveNext(), RedisListIterator(), WriteCurrentElement(), and WriteResult().
uint32_t rocksdb::RedisListIterator::length_ private
Definition at line 304 of file redis_list_iterator.h.
Referenced by CheckErrors(), Done(), InsertElement(), Length(), RedisListIterator(), Skip(), and WriteResult().
const uint32_t rocksdb::RedisListIterator::num_bytes_ private
Definition at line 298 of file redis_list_iterator.h.
Referenced by CheckErrors(), Done(), MoveNext(), RedisListIterator(), Size(), and WriteResult().
std::vector<char> rocksdb::RedisListIterator::result_ private
Definition at line 305 of file redis_list_iterator.h.
Referenced by InitializeResult(), InsertElement(), Reserve(), Size(), WriteCurrentElement(), and WriteResult().
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/utilities/redis/redis_list_iterator.h