rippled: beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::KeyValueCompare Class Reference
beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::KeyValueCompare Class Reference
Public Member Functions
KeyValueCompare ()
KeyValueCompare (Compare const &compare)
bool operator() (Key const &k, element const &e) const
bool operator() (element const &e, Key const &k) const
Compare & compare ()
Compare const & compare () const
Additional Inherited Members
Private Member Functions inherited from beast::empty_base_optimization< Compare >
empty_base_optimization ()=default
empty_base_optimization (Compareconst &t)
empty_base_optimization (Compare &&t)
Compare & member () noexcept
Compareconst & member () const noexcept
Detailed Description
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>>
class beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::KeyValueCompare
Definition at line 184 of file aged_ordered_container.h.
Constructor & Destructor Documentation
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::KeyValueCompare::KeyValueCompare () inline
Definition at line 189 of file aged_ordered_container.h.
         {
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::KeyValueCompare::KeyValueCompare (Compare const & compare) inline
Definition at line 193 of file aged_ordered_container.h.
             : empty_base_optimization <Compare> (compare)
         {
         }
Member Function Documentation
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> Compare& beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::KeyValueCompare::compare () inline
Definition at line 224 of file aged_ordered_container.h.
Referenced by beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::config_t::compare().
         {
             return empty_base_optimization <Compare>::member();
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> Compare const& beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::KeyValueCompare::compare () const inline
Definition at line 229 of file aged_ordered_container.h.
         {
             return empty_base_optimization <Compare>::member();
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> bool beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::KeyValueCompare::operator() (Key const & k, element const & e) const inline
Definition at line 214 of file aged_ordered_container.h.
References beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::extract(), and beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::element::value.
         {
             return this->member() (k, extract (e.value));
         }
template<bool IsMulti, bool IsMap, class Key, class T, class Duration = std::chrono::seconds, class Compare = std::less <Key>, class Allocator = std::allocator < typename std::conditional <IsMap, std::pair <Key const, T>, Key>::type>> bool beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::KeyValueCompare::operator() (element const & e, Key const & k) const inline
Definition at line 219 of file aged_ordered_container.h.
References beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::extract(), and beast::detail::aged_ordered_container< IsMulti, IsMap, Key, T, Duration, Compare, Allocator >::element::value.
         {
             return this->member() (extract (e.value), k);
         }
The documentation for this class was generated from the following file:
rippled/src/beast/beast/container/detail/aged_ordered_container.h