rippled: rocksdb::SkipList< Key, Comparator >::Iterator Class Reference
rocksdb::SkipList< Key, Comparator >::Iterator Class Reference
#include <skiplist.h>
Public Member Functions
Iterator (const SkipList *list)
void SetList (const SkipList *list)
bool Valid () const
const Key & key () const
void Next ()
void Prev ()
void Seek (const Key &target)
void SeekToFirst ()
void SeekToLast ()
Private Attributes
const SkipList * list_
Node * node_
Detailed Description
template<typename Key, class Comparator>
class rocksdb::SkipList< Key, Comparator >::Iterator
Definition at line 60 of file skiplist.h.
Constructor & Destructor Documentation
template<typename Key , class Comparator > rocksdb::SkipList< Key, Comparator >::Iterator::Iterator (const SkipList * list) inline explicit
Definition at line 201 of file skiplist.h.
References rocksdb::SkipList< Key, Comparator >::Iterator::SetList().
{
   SetList(list);
 }
Member Function Documentation
template<typename Key , class Comparator > const Key & rocksdb::SkipList< Key, Comparator >::Iterator::key () const inline
Definition at line 217 of file skiplist.h.
Referenced by rocksdb::ConcurrentTest::ReadStep(), and rocksdb::TEST().
{
   assert(Valid());
   return node_->key;
 }
template<typename Key , class Comparator > void rocksdb::SkipList< Key, Comparator >::Iterator::Next () inline
Definition at line 223 of file skiplist.h.
Referenced by rocksdb::ConcurrentTest::ReadStep(), and rocksdb::TEST().
{
   assert(Valid());
   node_ = node_->Next(0);
 }
template<typename Key , class Comparator > void rocksdb::SkipList< Key, Comparator >::Iterator::Prev () inline
Definition at line 229 of file skiplist.h.
References list_.
Referenced by rocksdb::TEST().
{
   // Instead of using explicit "prev" links, we just search for the
   // last node that falls before key.
   assert(Valid());
   node_ = list_->FindLessThan(node_->key);
   if (node_ == list_->head_) {
     node_ = nullptr;
   }
 }
template<typename Key, class Comparator > void rocksdb::SkipList< Key, Comparator >::Iterator::Seek (const Key & target) inline
Definition at line 240 of file skiplist.h.
References list_.
Referenced by rocksdb::ConcurrentTest::ReadStep(), and rocksdb::TEST().
{
   node_ = list_->FindGreaterOrEqual(target, nullptr);
 }
template<typename Key , class Comparator > void rocksdb::SkipList< Key, Comparator >::Iterator::SeekToFirst () inline
Definition at line 245 of file skiplist.h.
References list_.
Referenced by rocksdb::TEST().
{
   node_ = list_->head_->Next(0);
 }
template<typename Key , class Comparator > void rocksdb::SkipList< Key, Comparator >::Iterator::SeekToLast () inline
Definition at line 250 of file skiplist.h.
References list_.
Referenced by rocksdb::TEST().
{
   node_ = list_->FindLast();
   if (node_ == list_->head_) {
     node_ = nullptr;
   }
 }
template<typename Key , class Comparator > void rocksdb::SkipList< Key, Comparator >::Iterator::SetList (const SkipList * list) inline
Definition at line 206 of file skiplist.h.
References list_.
Referenced by rocksdb::SkipList< Key, Comparator >::Iterator::Iterator().
{
   list_ = list;
   node_ = nullptr;
 }
template<typename Key , class Comparator > bool rocksdb::SkipList< Key, Comparator >::Iterator::Valid () const inline
Definition at line 212 of file skiplist.h.
Referenced by rocksdb::ConcurrentTest::ReadStep(), and rocksdb::TEST().
{
   return node_ != nullptr;
 }
Member Data Documentation
template<typename Key, class Comparator> const SkipList* rocksdb::SkipList< Key, Comparator >::Iterator::list_ private
Definition at line 98 of file skiplist.h.
template<typename Key, class Comparator> Node* rocksdb::SkipList< Key, Comparator >::Iterator::node_ private
Definition at line 99 of file skiplist.h.
The documentation for this class was generated from the following file:
rippled/src/ripple/rocksdb/rocksdb/db/skiplist.h