rippled: beast::unit_test::case_results::tests_t Class Reference
beast::unit_test::case_results::tests_t Class Reference
Public Member Functions
tests_t ()
std::size_t total () const
std::size_t failed () const
void pass ()
void fail (std::string const &reason="")
Public Member Functions inherited from beast::const_container< std::vector< test > >
bool empty () const
size_type size () const
const_iterator begin () const
const_iterator cbegin () const
const_iterator end () const
const_iterator cend () const
Private Attributes
std::size_t m_failed
Additional Inherited Members
Public Types inherited from beast::const_container< std::vector< test > >
typedef cont_type::value_type value_type
typedef cont_type::size_type size_type
typedef cont_type::difference_type difference_type
typedef cont_type::const_iterator iterator
typedef cont_type::const_iterator const_iterator
Protected Member Functions inherited from beast::const_container< std::vector< test > >
cont_type & cont ()
cont_type const & cont () const
Detailed Description
Definition at line 54 of file results.h.
Constructor & Destructor Documentation
beast::unit_test::case_results::tests_t::tests_t () inline
Definition at line 61 of file results.h.
             : m_failed (0)
         {
         }
Member Function Documentation
void beast::unit_test::case_results::tests_t::fail (std::string const & reason = "") inline
Register a failed test condition.
Definition at line 89 of file results.h.
References beast::const_container< std::vector< test > >::cont(), and m_failed.
Referenced by ldb_test.LDBTestCase::assertRunFAILFull(), and beast::unit_test::recorder::on_fail().
         {
             ++m_failed;
             cont().emplace_back (false, reason);
         }
std::size_t beast::unit_test::case_results::tests_t::failed () const inline
Returns the number of failed test conditions.
Definition at line 75 of file results.h.
References m_failed.
Referenced by beast::unit_test::suite_results::insert().
         {
             return m_failed;
         }
void beast::unit_test::case_results::tests_t::pass () inline
Register a successful test condition.
Definition at line 82 of file results.h.
References beast::const_container< std::vector< test > >::cont().
Referenced by beast::unit_test::recorder::on_pass().
         {
             cont().emplace_back (true);
         }
std::size_t beast::unit_test::case_results::tests_t::total () const inline
Returns the total number of test conditions.
Definition at line 68 of file results.h.
References beast::const_container< std::vector< test > >::cont().
Referenced by beast::unit_test::suite_results::insert().
         {
             return cont().size();
         }
Member Data Documentation
std::size_t beast::unit_test::case_results::tests_t::m_failed private
Definition at line 58 of file results.h.
Referenced by fail(), and failed().
The documentation for this class was generated from the following file:
rippled/src/beast/beast/unit_test/results.h