rippled: ripple::PeerFinder::StoreSqdb Class Reference
ripple::PeerFinder::StoreSqdb Class Reference
#include <StoreSqdb.h>
Public Types
enum { currentSchemaVersion = 4 }
Public Types inherited from ripple::PeerFinder::Store
typedef std::function< void(beast::IP::Endpoint,
int)> load_callback
Public Member Functions
StoreSqdb (beast::Journal journal=beast::Journal())
~StoreSqdb ()
beast::Error open (beast::File const &file)
std::size_t load (load_callback const &cb)
void save (std::vector< Entry > const &v)
beast::Error update ()
Public Member Functions inherited from ripple::PeerFinder::Store
virtual ~Store ()
Private Member Functions
beast::Error init ()
void report (beast::Error const &error, char const *fileName, int lineNumber)
Private Attributes
beast::Journal m_journal
beast::sqdb::session m_session
Detailed Description
Database persistence for PeerFinder using SQLite
Definition at line 27 of file StoreSqdb.h.
Member Enumeration Documentation
anonymous enum
Enumerator
currentSchemaVersion
Definition at line 36 of file StoreSqdb.h.
     {
         // This determines the on-database format of the data
         currentSchemaVersion = 4
     };
Constructor & Destructor Documentation
ripple::PeerFinder::StoreSqdb::StoreSqdb (beast::Journal journal = beast::Journal()) inline explicit
Definition at line 42 of file StoreSqdb.h.
         : m_journal (journal)
     {
     }
ripple::PeerFinder::StoreSqdb::~StoreSqdb () inline
Definition at line 47 of file StoreSqdb.h.
     {
     }
Member Function Documentation
beast::Error ripple::PeerFinder::StoreSqdb::init () inline private
Definition at line 359 of file StoreSqdb.h.
References beast::sqdb::transaction::commit(), m_session, beast::sqdb::session::once(), report(), and beast::sqdb::transaction::rollback().
Referenced by open().
     {
         beast::Error error;
         beast::sqdb::transaction tr (m_session);
         if (! error)
             m_session.once (error) <<
                 "PRAGMA encoding=\"UTF-8\"";
         if (! error)
             m_session.once (error) <<
                 "CREATE TABLE IF NOT EXISTS SchemaVersion ( "
                 "  name             TEXT PRIMARY KEY, "
                 "  version          INTEGER"
                 ");"
                 ;
         if (! error)
             m_session.once (error) <<
                 "CREATE TABLE IF NOT EXISTS PeerFinder_BootstrapCache ( "
                 "  id       INTEGER PRIMARY KEY AUTOINCREMENT, "
                 "  address  TEXT UNIQUE NOT NULL, "
                 "  valence  INTEGER"
                 ");"
                 ;
         if (! error)
             m_session.once (error) <<
                 "CREATE INDEX IF NOT EXISTS "
                 "  PeerFinder_BootstrapCache_Index ON PeerFinder_BootstrapCache "
                 "  (  "
                 "    address "
                 "  ); "
                 ;
         if (! error)
             error = tr.commit();
         if (error)
         {
             tr.rollback ();
             report (error, __FILE__, __LINE__);
         }
         return error;
     }
std::size_t ripple::PeerFinder::StoreSqdb::load (load_callback const & cb) inline virtual
Implements ripple::PeerFinder::Store.
Definition at line 68 of file StoreSqdb.h.
References beast::Journal::error, beast::sqdb::statement::execute_and_fetch(), beast::sqdb::statement::fetch(), beast::IP::Endpoint::from_string(), beast::sqdb::into(), beast::IP::is_unspecified(), m_journal, m_session, beast::sqdb::session::prepare, and report().
     {
         std::size_t n (0);
         beast::Error error;
         std::string s;
         int valence;
         beast::sqdb::statement st = (m_session.prepare <<
             "SELECT "
             " address, "
             " valence "
             "FROM PeerFinder_BootstrapCache "
             , beast::sqdb::into (s)
             , beast::sqdb::into (valence)
             );
         if (st.execute_and_fetch (error))
         {
             do
             {
                 beast::IP::Endpoint const endpoint (
                     beast::IP::Endpoint::from_string (s));
                 if (! is_unspecified (endpoint))
                 {
                     cb (endpoint, valence);
                     ++n;
                 }
                 else
                 {
                     m_journal.error <<
                         "Bad address string '" << s << "' in Bootcache table";
                 }
             }
             while (st.fetch (error));
         }
         if (error)
             report (error, __FILE__, __LINE__);
         return n;
     }
beast::Error ripple::PeerFinder::StoreSqdb::open (beast::File const & file) inline
Definition at line 51 of file StoreSqdb.h.
References beast::File::getFullPathName(), beast::Journal::info, init(), m_journal, m_session, beast::sqdb::session::open(), and update().
Referenced by ripple::PeerFinder::ManagerImp::init().
     {
         beast::Error error (m_session.open (file.getFullPathName ()));
         m_journal.info << "Opening database at '" << file.getFullPathName() << "'";
         if (! error)
             error = init ();
         if (! error)
             error = update ();
         return error;
     }
void ripple::PeerFinder::StoreSqdb::report (beast::Error const & error, char const * fileName, int lineNumber) inline private
Definition at line 406 of file StoreSqdb.h.
References beast::Journal::error, beast::Error::getReasonText(), beast::Debug::getSourceLocation(), and m_journal.
Referenced by init(), load(), save(), and update().
     {
         if (error)
         {
             m_journal.error <<
                 "Failure: '"<< error.getReasonText() << "' " <<
                 " at " << beast::Debug::getSourceLocation (fileName, lineNumber);
         }
     }
void ripple::PeerFinder::StoreSqdb::save (std::vector< Entry > const & v) inline virtual
Implements ripple::PeerFinder::Store.
Definition at line 112 of file StoreSqdb.h.
References beast::sqdb::transaction::commit(), beast::sqdb::statement::execute_and_fetch(), m_session, beast::sqdb::session::once(), beast::sqdb::session::prepare, report(), beast::sqdb::transaction::rollback(), ripple::to_string(), and beast::sqdb::use().
     {
         beast::Error error;
         beast::sqdb::transaction tr (m_session);
         m_session.once (error) <<
             "DELETE FROM PeerFinder_BootstrapCache";
         if (! error)
         {
             std::string s;
             int valence;
             beast::sqdb::statement st = (m_session.prepare <<
                 "INSERT INTO PeerFinder_BootstrapCache ( "
                 "  address, "
                 "  valence "
                 ") VALUES ( "
                 "  ?, ? "
                 ");"
                 , beast::sqdb::use (s)
                 , beast::sqdb::use (valence)
                 );
             for (auto const& e : v)
             {
                 s = to_string (e.endpoint);
                 valence = e.valence;
                 st.execute_and_fetch (error);
                 if (error)
                     break;
             }
         }
         if (! error)
             error = tr.commit();
         if (error)
         {
             tr.rollback ();
             report (error, __FILE__, __LINE__);
         }
     }
beast::Error ripple::PeerFinder::StoreSqdb::update () inline
Definition at line 157 of file StoreSqdb.h.
References beast::sqdb::transaction::commit(), currentSchemaVersion, ripple::PeerFinder::Store::Entry::endpoint, beast::Journal::error, beast::sqdb::statement::execute_and_fetch(), beast::Error::fail(), beast::sqdb::statement::fetch(), beast::IP::Endpoint::from_string(), beast::sqdb::session::got_data(), beast::Journal::info, beast::sqdb::into(), beast::IP::is_unspecified(), m_journal, m_session, beast::sqdb::session::once(), beast::sqdb::session::prepare, report(), beast::sqdb::transaction::rollback(), ripple::to_string(), beast::sqdb::use(), ripple::PeerFinder::Store::Entry::valence, and version.
Referenced by open().
     {
         beast::Error error;
         beast::sqdb::transaction tr (m_session);
         // get version
         int version (0);
         if (! error)
         {
             m_session.once (error) <<
                 "SELECT "
                 "  version "
                 "FROM SchemaVersion WHERE "
                 "  name = 'PeerFinder'"
                 ,beast::sqdb::into (version)
                 ;
             if (! error)
             {
                 if (!m_session.got_data())
                     version = 0;
                 m_journal.info <<
                     "Opened version " << version << " database";
             }
         }
         if (!error)
         {
             if (version < currentSchemaVersion)
                 m_journal.info <<
                     "Updating database to version " << currentSchemaVersion;
             else if (version > currentSchemaVersion)
                 error.fail (__FILE__, __LINE__,
                     "The PeerFinder database version is higher than expected");
         }
         if (! error && version < 4)
         {
             //
             // Remove the "uptime" column from the bootstrap table
             //
             if (! error)
                 m_session.once (error) <<
                     "CREATE TABLE IF NOT EXISTS PeerFinder_BootstrapCache_Next ( "
                     "  id       INTEGER PRIMARY KEY AUTOINCREMENT, "
                     "  address  TEXT UNIQUE NOT NULL, "
                     "  valence  INTEGER"
                     ");"
                     ;
             if (! error)
                 m_session.once (error) <<
                     "CREATE INDEX IF NOT EXISTS "
                     "  PeerFinder_BootstrapCache_Next_Index ON "
                     "    PeerFinder_BootstrapCache_Next "
                     "  ( address ); "
                     ;
             std::size_t count;
             if (! error)
                 m_session.once (error) <<
                     "SELECT COUNT(*) FROM PeerFinder_BootstrapCache "
                     ,beast::sqdb::into (count)
                     ;
             std::vector <Store::Entry> list;
             if (! error)
             {
                 list.reserve (count);
                 std::string s;
                 int valence;
                 beast::sqdb::statement st = (m_session.prepare <<
                     "SELECT "
                     " address, "
                     " valence "
                     "FROM PeerFinder_BootstrapCache "
                     , beast::sqdb::into (s)
                     , beast::sqdb::into (valence)
                     );
                 if (st.execute_and_fetch (error))
                 {
                     do
                     {
                         Store::Entry entry;
                         entry.endpoint = beast::IP::Endpoint::from_string (s);
                         if (! is_unspecified (entry.endpoint))
{
                             entry.valence = valence;
                             list.push_back (entry);
                         }
                         else
{
                             m_journal.error <<
                                 "Bad address string '" << s << "' in Bootcache table";
                         }
                     }
                     while (st.fetch (error));
                 }
             }
             if (! error)
             {
                 std::string s;
                 int valence;
                 beast::sqdb::statement st = (m_session.prepare <<
                     "INSERT INTO PeerFinder_BootstrapCache_Next ( "
                     "  address, "
                     "  valence "
                     ") VALUES ( "
                     "  ?, ?"
                     ");"
                     , beast::sqdb::use (s)
                     , beast::sqdb::use (valence)
                     );
                 for (auto iter (list.cbegin());
                     !error && iter != list.cend(); ++iter)
                 {
                     s = to_string (iter->endpoint);
                     valence = iter->valence;
                     st.execute_and_fetch (error);
                 }
             }
             if (! error)
                 m_session.once (error) <<
                     "DROP TABLE IF EXISTS PeerFinder_BootstrapCache";
             if (! error)
                 m_session.once (error) <<
                     "DROP INDEX IF EXISTS PeerFinder_BootstrapCache_Index";
             if (! error)
                 m_session.once (error) <<
                     "ALTER TABLE PeerFinder_BootstrapCache_Next "
                     "  RENAME TO PeerFinder_BootstrapCache";
             if (! error)
                 m_session.once (error) <<
                     "CREATE INDEX IF NOT EXISTS "
                     "  PeerFinder_BootstrapCache_Index ON PeerFinder_BootstrapCache "
                     "  (  "
                     "    address "
                     "  ); "
                     ;
         }
         if (! error && version < 3)
         {
             //
             // Remove legacy endpoints from the schema
             //
             if (! error)
                 m_session.once (error) <<
                     "DROP TABLE IF EXISTS LegacyEndpoints";
             if (! error)
                 m_session.once (error) <<
                     "DROP TABLE IF EXISTS PeerFinderLegacyEndpoints";
             if (! error)
                 m_session.once (error) <<
                     "DROP TABLE IF EXISTS PeerFinder_LegacyEndpoints";
             if (! error)
                 m_session.once (error) <<
                     "DROP TABLE IF EXISTS PeerFinder_LegacyEndpoints_Index";
         }
         if (! error)
         {
             int const version (currentSchemaVersion);
             m_session.once (error) <<
                 "INSERT OR REPLACE INTO SchemaVersion ("
                 "   name "
                 "  ,version "
                 ") VALUES ( "
                 "  'PeerFinder', ? "
                 ")"
                 ,beast::sqdb::use(version);
         }
         if (! error)
             error = tr.commit();
         if (error)
         {
             tr.rollback();
             report (error, __FILE__, __LINE__);
         }
         return error;
     }
Member Data Documentation
beast::Journal ripple::PeerFinder::StoreSqdb::m_journal private
Definition at line 32 of file StoreSqdb.h.
Referenced by load(), open(), report(), and update().
beast::sqdb::session ripple::PeerFinder::StoreSqdb::m_session private
Definition at line 33 of file StoreSqdb.h.
Referenced by init(), load(), open(), save(), and update().
The documentation for this class was generated from the following file:
rippled/src/ripple/peerfinder/impl/StoreSqdb.h