rippled: ripple::NodeStore Namespace Reference
ripple::NodeStore Namespace Reference
Classes
class Backend
class Database
class DummyScheduler
class Factory
class Manager
class Scheduler
struct Task
struct VisitCallback
class LevelDBBackend
class LevelDBFactory
class MemoryBackend
class MemoryFactory
class NullBackend
class NullFactory
class BatchWriter
class DatabaseImp
class DecodedBlob
struct EncodedBlob
class ManagerImp
class Backend_test
class NodeStoreBasic_test
class NodeStoreDatabase_test
class TestBase
class NodeStoreTiming_test
Typedefs
typedef std::vector
< NodeObject::Ptr > Batch
typedef beast::StringPairArray Parameters
Enumerations
enum { batchWritePreallocationSize = 128 }
enum Status {
ok, notFound, dataCorrupt, unknown,
customCode = 100
}
enum { cacheTargetSize = 16384, cacheTargetSeconds = 300 }
Functions
std::unique_ptr< Manager > make_Manager (std::vector< std::unique_ptr< Factory >> factories=std::vector< std::unique_ptr< Factory >>())
std::unique_ptr< Factory > make_LevelDBFactory ()
std::unique_ptr< Factory > make_MemoryFactory ()
std::unique_ptr< Factory > make_NullFactory ()
std::unique_ptr< Factory > make_RocksDBFactory ()
BEAST_DEFINE_TESTSUITE (Backend, ripple_core, ripple)
BEAST_DEFINE_TESTSUITE (NodeStoreBasic, ripple_core, ripple)
BEAST_DEFINE_TESTSUITE (NodeStoreDatabase, ripple_core, ripple)
BEAST_DEFINE_TESTSUITE (NodeStoreTiming, ripple_core, ripple)
Typedef Documentation
typedef std::vector<NodeObject::Ptr> ripple::NodeStore::Batch
A batch of NodeObjects to write at once.
Definition at line 46 of file Types.h.
typedef beast::StringPairArray ripple::NodeStore::Parameters
A list of key/value parameter pairs passed to the backend.
Definition at line 50 of file Types.h.
Enumeration Type Documentation
anonymous enum
Enumerator
batchWritePreallocationSize
Definition at line 26 of file Types.h.
 {
     // This is only used to pre-allocate the array for
     // batch objects and does not affect the amount written.
     //
     batchWritePreallocationSize = 128
 };
anonymous enum
Enumerator
cacheTargetSize
cacheTargetSeconds
Definition at line 26 of file Tuning.h.
 {
     // Target cache size of the TaggedCache used to hold nodes
     cacheTargetSize     = 16384
     // Expiration time for cached nodes
     ,cacheTargetSeconds = 300
 };
enum ripple::NodeStore::Status
Return codes from Backend operations.
Enumerator
ok
notFound
dataCorrupt
unknown
customCode
Definition at line 35 of file Types.h.
 {
     ok,
     notFound,
     dataCorrupt,
     unknown,
     customCode = 100
 };
Function Documentation
ripple::NodeStore::BEAST_DEFINE_TESTSUITE (NodeStoreBasic , ripple_core , ripple)
ripple::NodeStore::BEAST_DEFINE_TESTSUITE (Backend , ripple_core , ripple)
ripple::NodeStore::BEAST_DEFINE_TESTSUITE (NodeStoreTiming , ripple_core , ripple)
ripple::NodeStore::BEAST_DEFINE_TESTSUITE (NodeStoreDatabase , ripple_core , ripple)
std::unique_ptr< Factory > ripple::NodeStore::make_LevelDBFactory ()
Factory to produce LevelDBFactory backends for the NodeStore.
See Also
Database
Definition at line 251 of file LevelDBFactory.cpp.
Referenced by ripple::NodeStore::ManagerImp::add_known_factories().
 {
     return std::make_unique <LevelDBFactory> ();
 }
std::unique_ptr< Manager > ripple::NodeStore::make_Manager (std::vector< std::unique_ptr< Factory >> factories = std::vector <std::unique_ptr <Factory>>())
Create a Manager.
Parameters
factories An optional array of additional factories to add.
Definition at line 135 of file Manager.cpp.
Referenced by ripple::NodeStore::Backend_test::testBackend(), ripple::NodeStore::NodeStoreTiming_test::testBackend(), ripple::NodeStore::NodeStoreDatabase_test::testImport(), and ripple::NodeStore::NodeStoreDatabase_test::testNodeStore().
 {
     return std::make_unique <ManagerImp> (std::move (factories));
 }
std::unique_ptr< Factory > ripple::NodeStore::make_MemoryFactory ()
Factory to produce a RAM based backend for the NodeStore.
See Also
Database
Definition at line 118 of file MemoryFactory.cpp.
Referenced by ripple::NodeStore::ManagerImp::add_known_factories().
 {
     return std::make_unique <MemoryFactory> ();
 }
std::unique_ptr< Factory > ripple::NodeStore::make_NullFactory ()
Factory to produce a null backend. This is for standalone / testing mode.
See Also
Database
Definition at line 83 of file NullFactory.cpp.
Referenced by ripple::NodeStore::ManagerImp::add_known_factories().
 {
     return std::make_unique <NullFactory> ();
 }
std::unique_ptr<Factory> ripple::NodeStore::make_RocksDBFactory ()
Factory to produce RocksDB backends for the NodeStore.
See Also
Database
Referenced by ripple::NodeStore::ManagerImp::add_known_factories().