rippled: beast::Workers_test Class Reference
beast::Workers_test Class Reference
Classes
struct TestCallback
Public Member Functions
template<class T1 , class T2 >
bool expectEquals (T1 const &t1, T2 const &t2)
void testThreads (int const threadCount)
void run ()
Public Member Functions inherited from beast::unit_test::suite
void operator() (runner &r)
void testcase (std::string const &name, abort_t abort=no_abort_on_fail)
template<class Condition >
bool expect (Condition shouldBeTrue, std::string const &reason="")
template<class Condition >
bool unexpected (Condition shouldBeFalse, std::string const &reason="")
void pass ()
void fail (std::string const &reason="")
Additional Inherited Members
Public Types inherited from beast::unit_test::suite
enum abort_t { no_abort_on_fail, abort_on_fail }
typedef
abstract_ostream::scoped_stream_type scoped_stream
Public Attributes inherited from beast::unit_test::suite
log_t log
Detailed Description
Definition at line 226 of file Workers.cpp.
Member Function Documentation
template<class T1 , class T2 > bool beast::Workers_test::expectEquals (T1 const & t1, T2 const & t2) inline
Definition at line 250 of file Workers.cpp.
References beast::IP::detail::expect().
     {
         return expect (t1 == t2);
     }
void beast::Workers_test::run () inline virtual
Runs the suite.
Implements beast::unit_test::suite.
Definition at line 286 of file Workers.cpp.
     {
         testThreads (0);
         testThreads (1);
         testThreads (2);
         testThreads (4);
         testThreads (16);
         testThreads (64);
     }
void beast::Workers_test::testThreads (int const threadCount) inline
Definition at line 255 of file Workers.cpp.
References beast::Workers::addTask(), beast::IP::detail::expect(), beast::Workers::getNumberOfThreads(), beast::Workers::pauseAllThreadsAndWait(), beast::Workers::setNumberOfThreads(), and testcase.
     {
         std::stringstream ss;
         ss <<
             "threadCount = " << threadCount;
         testcase (ss.str());
         TestCallback cb (threadCount);
         Workers w (cb, "Test", 0);
         expect (w.getNumberOfThreads () == 0);
         w.setNumberOfThreads (threadCount);
         expect (w.getNumberOfThreads () == threadCount);
         for (int i = 0; i < threadCount; ++i)
             w.addTask ();
         // 10 seconds should be enough to finish on any system
         //
         bool signaled = cb.finished.wait (10 * 1000);
         expect (signaled, "timed out");
         w.pauseAllThreadsAndWait ();
         int const count (cb.count.get ());
         expectEquals (count, 0);
     }
The documentation for this class was generated from the following file:
rippled/src/beast/modules/beast_core/thread/Workers.cpp