rippled: ripple::Validators::StoreSqdb Class Reference
ripple::Validators::StoreSqdb Class Reference
#include <StoreSqdb.h>
Public Types
enum { currentSchemaVersion = 2 }
Public Member Functions
StoreSqdb (beast::Journal journal=beast::Journal())
~StoreSqdb ()
beast::Error open (beast::File const &file)
void insert (SourceDesc &desc)
void update (SourceDesc &desc, bool updateFetchResults)
void remove (RipplePublicKey const &publicKey)
Public Member Functions inherited from ripple::Validators::Store
virtual ~Store ()
Private Member Functions
void report (beast::Error const &error, char const *fileName, int lineNumber)
bool select (SourceDesc &desc)
void selectList (SourceDesc &desc)
beast::Error update ()
beast::Error init ()
Private Attributes
beast::Journal m_journal
beast::sqdb::session m_session
Additional Inherited Members
Protected Member Functions inherited from ripple::Validators::Store
Store ()
Detailed Description
Database persistence for Validators using SQLite
Definition at line 27 of file StoreSqdb.h.
Member Enumeration Documentation
anonymous enum
Enumerator
currentSchemaVersion
Definition at line 32 of file StoreSqdb.h.
     {
         // This affects the format of the data!
         currentSchemaVersion = 2
     };
Constructor & Destructor Documentation
ripple::Validators::StoreSqdb::StoreSqdb (beast::Journal journal = beast::Journal()) explicit
Definition at line 23 of file StoreSqdb.cpp.
     : m_journal (journal)
 {
 }
ripple::Validators::StoreSqdb::~StoreSqdb ()
Definition at line 28 of file StoreSqdb.cpp.
 {
 }
Member Function Documentation
beast::Error ripple::Validators::StoreSqdb::init () private
Definition at line 411 of file StoreSqdb.cpp.
References beast::sqdb::transaction::commit(), m_session, beast::sqdb::session::once(), report(), and beast::sqdb::transaction::rollback().
Referenced by open().
 {
     beast::Error error;
     beast::sqdb::transaction tr (m_session);
     if (! error)
     {
         m_session.once (error) <<
             "PRAGMA encoding=\"UTF-8\"";
     }
     if (! error)
     {
         // This table maps component names like "Validators" to their
         // corresponding schema version number. This method allows us
         // to keep all logic data in one database, or each in its own
         // database, or in any grouping of databases, while still being
         // able to let an individual component know what version of its
         // schema it is opening.
         //
         m_session.once (error) <<
             "CREATE TABLE IF NOT EXISTS SchemaVersion ( "
             "  name             TEXT PRIMARY KEY, "
             "  version          INTEGER"
             ");"
             ;
     }
     if (! error)
     {
         m_session.once (error) <<
             "CREATE TABLE IF NOT EXISTS Validators_Source ( "
             "  id               INTEGER PRIMARY KEY AUTOINCREMENT, "
             "  sourceID         TEXT UNIQUE,   "
             "  createParam      TEXT NOT NULL, "
             "  lastFetchTime    TEXT NOT NULL, "
             "  expirationTime   TEXT NOT NULL "
             ");"
             ;
     }
     if (! error)
     {
         m_session.once (error) <<
             "CREATE TABLE IF NOT EXISTS Validators_SourceItem ( "
             "  id               INTEGER PRIMARY KEY AUTOINCREMENT, "
             "  sourceID         TEXT NOT NULL, "
             "  publicKey        TEXT NOT NULL, "
             "  label            TEXT NOT NULL  "
             ");"
             ;
     }
     if (! error)
     {
         m_session.once (error) <<
             "CREATE INDEX IF NOT EXISTS "
             "  Validators_SourceItem_Index ON Validators_SourceItem "
             "  (  "
             "    sourceID "
             "  ); "
             ;
     }
 #if 0
     if (! error)
     {
         m_session.once (error) <<
             "CREATE TABLE IF NOT EXISTS ValidatorsValidator ( "
             "  id               INTEGER PRIMARY KEY AUTOINCREMENT, "
             "  publicKey        TEXT UNIQUE "
             ");"
             ;
     }
     if (! error)
     {
         m_session.once (error) <<
             "CREATE TABLE IF NOT EXISTS ValidatorsValidatorStats ( "
             "  id               INTEGER PRIMARY KEY AUTOINCREMENT, "
             "  publicKey        TEXT UNIQUE "
             ");"
             ;
     }
 #endif
     if (! error)
     {
         error = tr.commit();
     }
     if (error)
     {
         tr.rollback ();
         report (error, __FILE__, __LINE__);
     }
     return error;
 }
void ripple::Validators::StoreSqdb::insert (SourceDesc & desc) virtual
Insert a new SourceDesc to the Store. The caller's SourceDesc will have any available persistent information filled in from the Store.
Implements ripple::Validators::Store.
Definition at line 54 of file StoreSqdb.cpp.
References beast::sqdb::transaction::commit(), beast::sqdb::statement::execute_and_fetch(), ripple::Validators::SourceDesc::expirationTime, ripple::Validators::SourceDesc::lastFetchTime, m_session, beast::sqdb::session::prepare, report(), beast::sqdb::transaction::rollback(), select(), selectList(), ripple::Validators::SourceDesc::source, ripple::Validators::Utilities::timeToString(), and beast::sqdb::use().
 {
     beast::sqdb::transaction tr (m_session);
     bool const found (select (desc));
     if (found)
     {
         selectList (desc);
     }
     else
     {
         beast::Error error;
         beast::String const sourceID (desc.source->uniqueID().toStdString());
         beast::String const createParam (desc.source->createParam().toStdString());
         beast::String const lastFetchTime (Utilities::timeToString (desc.lastFetchTime));
         beast::String const expirationTime (Utilities::timeToString (desc.expirationTime));
         beast::sqdb::statement st = (m_session.prepare <<
             "INSERT INTO Validators_Source ( "
             "  sourceID, "
             "  createParam, "
             "  lastFetchTime, "
             "  expirationTime "
             ") VALUES ( "
             "  ?, ?, ?, ? "
             "); "
             ,beast::sqdb::use (sourceID)
             ,beast::sqdb::use (createParam)
             ,beast::sqdb::use (lastFetchTime)
             ,beast::sqdb::use (expirationTime)
             );
         st.execute_and_fetch (error);
         if (! error)
         {
             error = tr.commit ();
         }
         if (error)
         {
             tr.rollback ();
             report (error, __FILE__, __LINE__);
         }
     }
 }
beast::Error ripple::Validators::StoreSqdb::open (beast::File const & file)
Definition at line 32 of file StoreSqdb.cpp.
References beast::Journal::error, beast::File::getFullPathName(), beast::Journal::info, init(), m_journal, m_session, beast::sqdb::session::open(), update(), and beast::Error::what().
Referenced by ripple::Validators::ManagerImp::init(), and ripple::Validators::Logic_test::testLogic().
 {
     beast::Error error (m_session.open (file.getFullPathName ()));
     m_journal.info <<
         "Opening " << file.getFullPathName();
     if (!error)
         error = init ();
     if (!error)
         error = update ();
     if (error)
         m_journal.error <<
             "Failed opening database: " << error.what();
     return error;
 }
void ripple::Validators::StoreSqdb::remove (RipplePublicKey const & publicKey)
void ripple::Validators::StoreSqdb::report (beast::Error const & error, char const * fileName, int lineNumber) private
Definition at line 179 of file StoreSqdb.cpp.
References beast::Journal::error, beast::Error::getReasonText(), beast::Debug::getSourceLocation(), and m_journal.
Referenced by init(), insert(), select(), selectList(), and update().
 {
     if (error)
     {
         m_journal.error <<
             "Failure: '"<< error.getReasonText() << "' " <<
             " at " << beast::Debug::getSourceLocation (fileName, lineNumber);
     }
 }
bool ripple::Validators::StoreSqdb::select (SourceDesc & desc) private
Reads the fixed information into the SourceDesc if it exists. Returns true if the record was found.
Definition at line 194 of file StoreSqdb.cpp.
References beast::Journal::debug, beast::sqdb::statement::execute_and_fetch(), ripple::Validators::SourceDesc::expirationTime, beast::Journal::info, beast::sqdb::into(), ripple::Validators::SourceDesc::lastFetchTime, m_journal, m_session, beast::sqdb::session::prepare, report(), ripple::Validators::SourceDesc::source, ripple::Validators::Utilities::stringToTime(), and beast::sqdb::use().
Referenced by insert().
 {
     bool found (false);
     beast::Error error;
     beast::String const sourceID (desc.source->uniqueID());
     beast::String lastFetchTime;
     beast::String expirationTime;
     beast::sqdb::statement st = (m_session.prepare <<
         "SELECT "
         "  lastFetchTime, "
         "  expirationTime "
         "FROM Validators_Source WHERE "
         "  sourceID = ? "
         ,beast::sqdb::into (lastFetchTime)
         ,beast::sqdb::into (expirationTime)
         ,beast::sqdb::use (sourceID)
         );
     if (st.execute_and_fetch (error))
     {
         m_journal.debug <<
             "Found record for " << *desc.source;
         found = true;
         desc.lastFetchTime = Utilities::stringToTime (lastFetchTime);
         desc.expirationTime = Utilities::stringToTime (expirationTime);
     }
     else if (! error)
     {
         m_journal.info <<
             "No previous record for " << *desc.source;
     }
     if (error)
     {
         report (error, __FILE__, __LINE__);
     }
     return found;
 }
void ripple::Validators::StoreSqdb::selectList (SourceDesc & desc) private
Reads the variable information into the SourceDesc. This should only be called when the sourceID was already found.
Definition at line 242 of file StoreSqdb.cpp.
References bassert, beast::Journal::error, beast::sqdb::statement::execute_and_fetch(), beast::sqdb::statement::fetch(), ripple::IdentifierType< RipplePublicKeyTraits >::from_string(), beast::Journal::info, beast::sqdb::into(), ripple::Validators::Source::Item::label, ripple::Validators::Source::Results::list, m_journal, m_session, beast::sqdb::session::once(), beast::sqdb::session::prepare, ripple::Validators::Source::Item::publicKey, report(), ripple::Validators::SourceDesc::results, ripple::Validators::SourceDesc::source, and beast::sqdb::use().
Referenced by insert().
 {
     beast::Error error;
     beast::String const sourceID (desc.source->uniqueID());
     // Get the count
     std::size_t count;
     if (! error)
     {
         m_session.once (error) <<
             "SELECT "
             "  COUNT(*) "
             "FROM Validators_SourceItem WHERE "
             "  sourceID = ? "
             ,beast::sqdb::into (count)
             ,beast::sqdb::use (sourceID)
             ;
     }
     if (error)
     {
         report (error, __FILE__, __LINE__);
         return;
     }
     // Precondition: the list must be empty.
     bassert (desc.results.list.size() == 0);
     // Pre-allocate some storage
     desc.results.list.reserve (count);
     // Prepare the select
     {
         std::string publicKeyString;
         std::string label;
         beast::sqdb::statement st = (m_session.prepare <<
             "SELECT "
             "  publicKey, "
             "  label "
             "FROM Validators_SourceItem WHERE "
             "  sourceID = ? "
             ,beast::sqdb::into (publicKeyString)
             ,beast::sqdb::into (label)
             ,beast::sqdb::use (sourceID)
             );
         // Add all the records to the list
         if (st.execute_and_fetch (error))
         {
             do
             {
                 Source::Item info;
                 std::pair <RipplePublicKey, bool> result (
                     RipplePublicKey::from_string (publicKeyString));
                 if (result.second)
                 {
                     bassert (result.first.to_string() == publicKeyString);
                     info.publicKey = result.first;
                     info.label = label;
                     desc.results.list.push_back (info);
                 }
                 else
                 {
                     m_journal.error <<
                         "Invalid public key '" << publicKeyString <<
                         "' found in database";
                 }
             }
             while (st.fetch (error));
             if (! error)
             {
                 m_journal.info <<
                     "Loaded " << desc.results.list.size() <<
                     " trusted validators for " << *desc.source;
             }
         }
     }
     if (error)
     {
         report (error, __FILE__, __LINE__);
     }
 }
void ripple::Validators::StoreSqdb::update (SourceDesc & desc, bool updateFetchResults) virtual
Update the SourceDesc fixed fields.
Implements ripple::Validators::Store.
Definition at line 105 of file StoreSqdb.cpp.
References beast::sqdb::transaction::commit(), beast::sqdb::statement::execute_and_fetch(), ripple::Validators::SourceDesc::expirationTime, ripple::Validators::SourceDesc::lastFetchTime, ripple::Validators::Source::Results::list, m_session, beast::sqdb::session::once(), beast::sqdb::session::prepare, ripple::Validators::Source::Item::publicKey, report(), ripple::Validators::SourceDesc::results, beast::sqdb::transaction::rollback(), ripple::Validators::SourceDesc::source, ripple::Validators::Utilities::timeToString(), ripple::IdentifierType< Traits >::to_string(), and beast::sqdb::use().
 {
     beast::Error error;
     beast::String const sourceID (desc.source->uniqueID());
     beast::String const lastFetchTime (Utilities::timeToString (desc.lastFetchTime));
     beast::String const expirationTime (Utilities::timeToString (desc.expirationTime));
     beast::sqdb::transaction tr (m_session);
     m_session.once (error) <<
         "UPDATE Validators_Source SET "
         "  lastFetchTime = ?, "
         "  expirationTime = ? "
         "WHERE "
         "  sourceID = ? "
         ,beast::sqdb::use (lastFetchTime)
         ,beast::sqdb::use (expirationTime)
         ,beast::sqdb::use (sourceID)
         ;
     if (! error && updateFetchResults)
     {
         // Delete the previous data set
         m_session.once (error) <<
             "DELETE FROM Validators_SourceItem WHERE "
             "  sourceID = ?; "
             ,beast::sqdb::use (sourceID)
             ;
         // Insert the new data set
         if (! error)
         {
             std::string publicKeyString;
             beast::String label;
             beast::sqdb::statement st = (m_session.prepare <<
                 "INSERT INTO Validators_SourceItem ( "
                 "  sourceID, "
                 "  publicKey, "
                 "  label "
                 ") VALUES ( "
                 "  ?, ?, ? "
                 ");"
                 ,beast::sqdb::use (sourceID)
                 ,beast::sqdb::use (publicKeyString)
                 ,beast::sqdb::use (label)
                 );
             std::vector <Source::Item>& list (desc.results.list);
             for (std::size_t i = 0; ! error && i < list.size(); ++i)
             {
                 Source::Item& item (list [i]);
                 publicKeyString = item.publicKey.to_string ();
                 label = list[i].label;
                 st.execute_and_fetch (error);
             }
         }
     }
     if (! error)
     {
         error = tr.commit();
     }
     if (error)
     {
         tr.rollback ();
         report (error, __FILE__, __LINE__);
     }
 }
beast::Error ripple::Validators::StoreSqdb::update () private
Definition at line 331 of file StoreSqdb.cpp.
References beast::sqdb::transaction::commit(), currentSchemaVersion, beast::sqdb::session::got_data(), beast::Journal::info, beast::sqdb::into(), m_journal, m_session, beast::sqdb::session::once(), report(), beast::sqdb::transaction::rollback(), beast::sqdb::use(), and version.
Referenced by open().
 {
     beast::Error error;
     beast::sqdb::transaction tr (m_session);
     // Get the version from the database
     int version (0);
     if (! error)
     {
         m_session.once (error) <<
             "SELECT "
             "  version "
             "FROM SchemaVersion WHERE "
             "  name = 'Validators' "
             ,beast::sqdb::into (version)
             ;
         if (! m_session.got_data ())
         {
             // pre-dates the "SchemaVersion" table
             version = 0;
         }
     }
     if (! error && version != currentSchemaVersion)
     {
         m_journal.info <<
             "Update database to version " << currentSchemaVersion <<
             " from version " << version;
     }
     // Update database based on version
     if (! error && version < 2)
     {
         if (! error)
             m_session.once (error) <<
                 "DROP TABLE IF EXISTS ValidatorsSource";
         if (! error)
             m_session.once (error) <<
                 "DROP TABLE IF EXISTS ValidatorsSourceInfo";
         if (! error)
             m_session.once (error) <<
                 "DROP INDEX IF EXISTS ValidatorsSourceInfoIndex";
     }
     // Update the version to the current version
     if (! error)
     {
         int const version (currentSchemaVersion);
         m_session.once (error) <<
             "INSERT OR REPLACE INTO SchemaVersion ( "
             "  name, "
             "  version "
             ") VALUES ( "
             "  'Validators', ? "
             "); "
             ,beast::sqdb::use (version)
             ;
     }
     if (! error)
     {
         error = tr.commit();
     }
     if (error)
     {
         tr.rollback ();
         report (error, __FILE__, __LINE__);
     }
     return error;
 }
Member Data Documentation
beast::Journal ripple::Validators::StoreSqdb::m_journal private
Definition at line 59 of file StoreSqdb.h.
Referenced by open(), report(), select(), selectList(), and update().
beast::sqdb::session ripple::Validators::StoreSqdb::m_session private
Definition at line 60 of file StoreSqdb.h.
Referenced by init(), insert(), open(), select(), selectList(), and update().
The documentation for this class was generated from the following files:
rippled/src/ripple/validators/impl/StoreSqdb.h
rippled/src/ripple/validators/impl/StoreSqdb.cpp